### ISSUE TITLE
Small withdrawals aren't counted

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#1000]
I am running Firefly III version 4.6.10

#### Description of my issue:
If I create a new withdrawal with a small number like 0.00000233, Firefly doesn’t count the payment. I can see the payment in the expenses, but it shows 0.00000000. The balance of the account doesn’t change too. If I try to edit the payment I get the error “Trying to get property of non-object”. Deleting the payment doesn’t work either. This happens to numbers smaller than 0.0001. It's not a rounding problem as a number of 0.09980233 is counted as it is.

Funnily a deposit with the same value does work without a problem. This is reproducible on your demo instance too.

#### Steps to reproduce 
Create a currency with more than 4 decimals. Add a withdrawal with a value below 0.0001.

**Comment by JC5** [comment]
Nice find! Also, issue 1000, congrats 🎉  ;)

I can see that some views work but others do not. I have pushed some fixes to the demo site that should fix some of these issues but I've yet to fix the charts, this is a little more complex.

**Comment by JC5** [comment]
Unfortunately I cannot fix all the charts, especially when they use mixed currencies. I believe I have fixed all other problems. The next release is next week. Let me know if you find any lingering issues.
