### ISSUE TITLE
2FA is only required once

### ISSUE THREAD

**Issue by ursweiss** [firefly-iii/firefly-iii#1002]
I am running Firefly III version 4.6.10

#### Description of my issue:
Installed FF yesterday and of course enabled 2FA right away.

Today i recognized that i was asked for a user/password, but no 2FA token. As far i see from the code, the cookie "twoFactorAuthenticated" is set to "true" after the first successful authentication. If i then log out and try again, the  "twoFactorAuthenticated" cookie value seems to still be set to "true", and therefore it's not asking me for the token again, which is not good at all.

Also i saw that the 2FA cookie expiration date is set to "now + 5y" when logging in, even if i don't check the "Remember me" checkbox. If i login and leave the browser window open without touching it, the session expires after two hours, but the 2FA token doesn't for another 5y, which makes it possible to login with user and password only during this time. The expiration date of the 2FA cookie should always be the same as for the session (or the remember) cookie itself.

#### Steps to reproduce 
Login with 2FA enabled, log out and try again.

**Comment by JC5** [comment]
Indeed! It should not function like this, thanks for reporting it. So much for regression testing.

I'll get right on it.

**Comment by JC5** [comment]
Alright I've pushed some fixes that work locally. Unfortunately you won't be able to test this, but since I use 2FA myself I shall play around on my local installation.

I shall keep you posted on the progress!

**Comment by JC5** [comment]
Found no further issues, the next release will have the fixes :)
