### ISSUE TITLE
Show deposits not ticked after saving

### ISSUE THREAD

**Issue by ursweiss** [firefly-iii/firefly-iii#1003]
I am running Firefly III version 4.6.10

#### Description of my issue:
Small bug:
If i set "Show deposits on the home screen" (Preferences >> Home Screen), it's saved and shown on the dashboard, but if i open the preferences again the option is not ticked. And, if i save the preferences again, it's gone from the dashboard.

#### Steps to reproduce 
(See above)
Happens on the demo site too.

**Comment by JC5** [comment]
Indeed, nice find. I've fixed it, and it will be live in the next release.

The function should work, it's just that the checkbox doesn't.

**Comment by JC5** [comment]
Will be fixed in the next release.
