### ISSUE TITLE
Lists need to be scrollable in the report (and maybe elsewhere)

### ISSUE THREAD

**Issue by Aquariu** [firefly-iii/firefly-iii#1004]
I am running Firefly III version 4.6.10
#### Description of my issue:
I have about 20 Categories. When trying to select which one I need for a Category Report, I can't because they don't fit all in the screen (vertically). This list is not scrollable so I can't select the last ones. The search feature solves only part of this issue (I need to remember the name) and is not as fast (for me) as clicking on the few I need.

This happens in this case for me for this specific report, but you might also want to have a look at other such lists (Account selection in any report, Budget lists in the Budget report, Tag list in the Tag report...)

#### Steps to reproduce 
- Create many Catagories
- Go to the Category report page
- Try to select the last ones (alphabetically ordered).

**Comment by JC5** [comment]
Unfortunately the current plugin I use is no longer maintained. I'll keep a lookout for a proper replacement.

**Comment by JC5** [comment]
This issue will be fixed in the next release. It's not visible on the demo site but it works.
