### ISSUE TITLE
Login via LDAP Accounts

### ISSUE THREAD

**Issue by BirgerK** [firefly-iii/firefly-iii#1005]
I am running no Firefly III, yet. 

#### Description of my issue:
FEATURE

A login will be checked by given LDAP connection. LDAP is a technique where accounts/logins can be stored centraly.

#### Other important details (log files, system info):
Is this idea already on the roadmap? Or even implemented and I didn't find it?

Regards from Hamburg
Birger

**Comment by JC5** [comment]
I'll write it down :).

**Comment by gavu** [comment]
I’ll add a +1 (but only if you add the possibility to “migrate” from local auth to ldap if the user id changes)

**Comment by Aquariu** [comment]
+1 for auth method :)

On a very related note: there are countless software out there that rely on third party plugins to authenticate. My `prosody` Jabber/XMPP server uses my mail server authentification as a backend, for exemple. My `nextcloud` server also does that as a fallback : it has it's own user database  (hashed and salted passwords) AND when the user is not found there, it sends an auth request to the mail server (`dovecot `in my case, also with hased and salted passwords).

See [how they do this in Nextcloud.](https://docs.nextcloud.com/server/12/admin_manual/configuration_user/user_auth_ftp_smb_imap.html)

On my system, Firefly is almost the only application that is not using this scheme.  Now, I suppose you are using the proposed tools by the Laravel, and I suppose they're doing their best. but an outside option would be nice.

I've googled a bit and didn't find much of interest, but this is way out of my league.

**Comment by GaLaKtIkUs** [comment]
+1 for LDAP

**Comment by gavu** [comment]
+1

**Comment by anmol26s** [comment]
+1
YunoHost have LDAP support. It will be awesome to have LDAP integration for the Firefly III package.
https://github.com/YunoHost-Apps/firefly3_ynh

**Comment by Xia0ben** [comment]
Hello there =).
First, thank you for your amazing work, this application rocks.
It would indeed be even more awesome if Firefly had LDAP, SAML or openID support to allow it to be integrated more easily in any infrastructure: gigantic +1 !

**Comment by pc-zookeeper** [comment]
+1 for LDAP support

**Comment by philthynz** [comment]
+1, with services like jumpcloud and foxpass it makes is easy to have LDAP for home projects

**Comment by gunnertwin** [comment]
+1 for LDAP!

**Comment by JC5** [comment]
This morning I successfully authenticated against this [free open LDAP server](http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/). I am going to clean up the code and make some arrangements and then push it to the `develop`-branch. Anybody interested can test and play. When there are no major issues this will be part of the next release.

**Comment by JC5** [comment]
I've pushed the code. I was able to connect to an online example server.

For more details: https://firefly-iii.readthedocs.io/en/latest/installation/authentication.html

**Comment by luisfavila** [comment]
@JC5 It still requires an email on the login page. Would it be possible to change that to a username when using ldap?

**Comment by JC5** [comment]
It doesn't require an email on the login page when LDAP is properly configured. Did you change the `LOGIN_PROVIDER` to `ldldap`?

**Comment by anmol26s** [comment]
@JC5 
Hi 
I am unable to configure ldap for the yunohost. Can you please provide the details for the settings?

Server: openLDAP
localhost:389
Base: "ou=users,dc=yunohost,dc=org"
login: "uid"
email: "mail"
firstname: "givenName"
lastname: "sn"

**Comment by JC5** [comment]
I would have to get Yunohost working first 😅 

Try the following, but you might need to experiment a bit:

```
LOGIN_PROVIDER=adldap
ADLDAP_CONNECTION_SCHEME=OpenLDAP
ADLDAP_BASEDN="ou=users,dc=yunohost,dc=org"
ADLDAP_DISCOVER_FIELD=uid
ADLDAP_AUTH_FIELD=uid
ADLDAP_SYNC_FIELD=uid
```

Possibly, try editing these:
```
ADLDAP_ACCOUNT_PREFIX="uid="
ADLDAP_ACCOUNT_SUFFIX=",ou=users,dc=yunohost,dc=org"
```

**Comment by anmol26s** [comment]
I am did some experiment with these settings but none of these work.

**Comment by JC5** [comment]
Could you share some debug logs? I believe the library can log quite extensively what it's doing. If you [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) you should find the library's attempts to log you in in the logs.
