### ISSUE TITLE
Dockerhub build configuration

### ISSUE THREAD

**Issue by ms32035** [firefly-iii/firefly-iii#1006]
Don't know how Dockerhub builds are configured but looking at the timestamps and the code, `jc5x/firefly-iii:latest` seems not to be following the `master` branch, as it should be by convention with Docker images.

![capture](https://user-images.githubusercontent.com/5060473/32996385-d97c3da0-cd79-11e7-804d-79e3b58828c1.PNG)

**Comment by JC5** [comment]
Indeed! The configuration should be updated and the build should no longer respond to pushing to develop.

**Comment by JC5** [comment]
I have also rebuilt the image based on the master branch.

**Comment by ms32035** [comment]
Thx. It's sourceref `master` now

**Comment by ms32035** [comment]
![image](https://user-images.githubusercontent.com/5060473/33240614-b6545470-d2b0-11e7-9f74-989cc48740b8.png)

![image](https://user-images.githubusercontent.com/5060473/33240641-353c088c-d2b1-11e7-8906-2b2be0a5b23b.png)


Something still looks not ok. The `latest` tag does not match last automated build for master. Some CI server pushing?

**Comment by JC5** [comment]
According to the config, "latest" should trail the master branch and nothing else. I've pushed it 6 days ago when I updated the config per your original issue. That could explain the difference.

I'm not sure what happened 5 hours ago. I've been developing but pushed nothing to master.

**Comment by ms32035** [comment]
At the same time you see that `develop` tag was last updated 7 days ago so it seem like there is still some configuration problem

**Comment by JC5** [comment]
![screen shot 2017-11-26 at 15 03 28](https://user-images.githubusercontent.com/5889984/33240722-feaa8c6c-d2ba-11e7-8feb-c2e692364ef7.png)

This is the current config. I'm not sure what could be wrong with it.

**Comment by ms32035** [comment]
Looks ok, can you manually trigger a develop build to check what happens?

**Comment by JC5** [comment]
Just triggered a develop build (second row).

**Comment by ms32035** [comment]
```
root@vps:~/docker/firefly# docker history jc5x/firefly-iii
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
203c9396eaeb        5 hours ago         /bin/sh -c #(nop)  ENTRYPOINT ["docker/ent...   0B
<missing>           5 hours ago         /bin/sh -c #(nop)  EXPOSE 80/tcp                0B
<missing>           5 hours ago         /bin/sh -c composer install --prefer-dist ...   191MB
<missing>           5 hours ago         /bin/sh -c chown -R www-data:www-data /var...   51.8MB
<missing>           5 hours ago         /bin/sh -c #(nop) COPY dir:798b66ef8aac831...   51.8MB
<missing>           6 days ago          /bin/sh -c #(nop) WORKDIR /var/www/firefly...   0B
<missing>           6 days ago          /bin/sh -c #(nop)  ENV FIREFLY_PATH=/var/w...   0B
```

Looking at dockerhub config and image history feels like we have 2 issues here:
1. Something outside of dockehub pushed `develop` branch to `latest` tag
2. dockerhub builds don't run on push to `develop`

**Comment by JC5** [comment]
I've checked the post triggers, but the log is empty. The develop branch can be pushed easily, I'll do it now. Should send me an email as well.

**Comment by JC5** [comment]
I'm going to push the master branch this evening, let's see what happens. I'm closing this one to tidy up.
