### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by wprauchholz** [firefly-iii/firefly-iii#1007]
I want to install Firefly III version 4.6.10 
#### Description of my issue:
I follwed the installation guide. and troubleshooting page too
http://localhost/firefly-iii/public results in:
**This site can’t be reached localhost refused to connect.**
If I try to acces with the domain name
http://www.mydomain.com/firefly-iii/public I get the following error
**Not Found The requested URL /firefly-iii/public/login was not found on this server.**

apache error log is empty

in /storage/logs I see the following:
[2017-11-20 14:03:39] local.DEBUG: Set new value for  {"name":"is_demo_site"}
[2017-11-20 14:03:39] local.DEBUG: Does not exist yet  {"name":"is_demo_site"}

#### Steps to reproduce 

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):
I run under CENTOS 7, PHP 7.1.11 (cli) (built: Oct 27 2017 14:45:51 and httpd-2.4.6-67

Thanks for your help
[env.txt](https://github.com/firefly-iii/firefly-iii/files/1487951/env.txt)

**Comment by JC5** [comment]
Do you have the rewrite module enabled?

**Comment by wprauchholz** [comment]
Yes, to force SSL

**Comment by JC5** [comment]
OK, where did you add this rule?

Is `AllowOverride` enabled? Firefly III has an [htaccess](https://github.com/firefly-iii/firefly-iii/blob/master/public/.htaccess) file with the correct rules.

**Comment by wprauchholz** [comment]
mod-rewrite.conf is a module loaded by httpd. Currently firefly-ii is not set in that file.
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^/horde/(.*) https://%{SERVER_NAME}/horde/$1 [R,L]
RewriteRule ^/piwigo/(.*) https://%{SERVER_NAME}/piwigo/$1 [R,L]
RewriteRule ^/suitecrm/(.*) https://%{SERVER_NAME}/suitecrm/$1 [R,L]


AllowOverride is set in httpd.conf:
<Directory "/var/www">
    AllowOverride All
    Require all granted
</Directory>

Further up I found
<Directory />
    AllowOverride none
    Require all denied
</Directory>

**Comment by JC5** [comment]
OK good, but I see no particular errors in the error log. Perhaps the dynamic library, but since it's a warning it should not freeze PHP. Especially not when other applications are working.

Your rewrite rules seem to be focussed on redirecting users to https, am I right?

**Comment by wprauchholz** [comment]
Your rewrite rules seem to be focussed on redirecting users to https, am I right?
WPR: This is correct. I assume this is equivalent to the parameter sent in .env APP_FORCE_SSL=true

I disabled the rewrite entirely, but the result is the same
I enabled it then again and added arewrite for firefly-iii
Entering the following in Chrome: http://<my domain)/firefly-iii
Results in Forbidden - You don't have permission to access /firefly-iii/ on this server.

Entering https://wo-lar.com/firefly-iii/public/login results in
Not Found - The requested URL /firefly-iii/public/login was not found on this server.
firefly-iii/public directory exists
chown is set to apache.apache and chmod to 775

I changed in .env 
APP_URL=http://localhost to APP_URL=https://<my domain> and ran initialize database again, but the result is the same.

**Comment by JC5** [comment]
If /login does not exist something is wrong with the rewrite rules, it should redirect the 404 to /firefly-iii/index.php which should resolve it.

Try restoring the original .htaccess in /public/ and add the following:

RewriteBase /firefly-iii/public/

I would suggest trying to move Firefly III out of the public root and create a symlink.

**Comment by wprauchholz** [comment]
I did as suggested.
I re-installed firefly in my home directory and set a symlink
lrwxrwxrwx   1 apache apache    30 Nov 23 19:43 firefly-iii -> /home/wp.rauchholz/firefly-iii

I added RewriteBase /firefly-iii/public/ to /public/.htaccess

Sorry to say, but the same result.
I pay you more than 1 beer if this gets fixed... :)

**Comment by gavu** [comment]
Hi, sorry for being late to the party. Can you post your apache config? Specifically the config part of your FF website

**Comment by wprauchholz** [comment]
In apache.conf is really nothing specific to firefly-iii (I assume that is what FF means).
AllowOverride is set to All
As all other services (horde, etc.) it is placed in /var/www/html
[httpd.conf.txt](https://github.com/firefly-iii/firefly-iii/files/1500138/httpd.conf.txt)

**Comment by gavu** [comment]
I'm on my phone right now, so please excuse me if I missed something. I checked your httpd.conf file and if I understand correctly, you are are running multiple websites like http://my.domain.tld/website1, http://my.domain.tld/website2, http://my.domain.tld/website3.

you could try to add something like this to your httpd.conf:

```
	# your firefly-iii public directory
	<Directory /var/www/firefly-iii/public>
        	Options Indexes FollowSymLinks
        	AllowOverride All
        	Require all granted
	</Directory>
```

If this also fails, you can always check for any kind of config/permission issues on your system and point your entire apache service to the firefly-iii/public folder (`DocumentRoot /var/www/firefly-iii/public`)

**Comment by wprauchholz** [comment]
I appreciate your help, but....
http://localhost/firefly-iii/public > This site can’t be reached localhost refused to connect.
https://wo-lar.com/firefly-iii/ > Forbidden You don't have permission to access /firefly-iii/ on this server.
http://wo-lar.com/firefly/public > Not Found The requested URL /firefly/public was not found on this server.

Do you know of another installation for firefly on CENTOS7?

**Comment by gavu** [comment]
I am downloading an ISO as we speak :) this is getting annoying - I'm sure this is only a permission issue. You installed firefly-iii via composer, right?

**Comment by gavu** [comment]
I just installed centos7 in a VM, installed (hopefully) everything and ran into the following error:

`my.ip.add.ress is currently unable to handle this request. HTTP ERROR 500`

Since I haven't used centos in almost 10 years, I need to see what went wrong... currently the FF logs show no errors but the httpd logs say that PHP is `Unable to create the cache directory in /var/www/firefly-iii/storage/framework/views/twig/13`

**Comment by JC5** [comment]
Make sure the httpd user has write access to the storage directory.

@wprauchholz 
- /firefly-iii/ is probably not accessible because there is no index.php. This is default behavior when directory listing is off
- /firefly-iii/public "not found" probably means that the htaccess file is not refering to the correct index.php I think.

What's its current contents?

**Comment by gavu** [comment]
@JC5, I made sure it has, the centos' apache user is `apache` (not `http` or `www-data`). I also double-checked it against the `/etc/passwd` and `/etc/groups`, so, I adapted the `chown` command accordingly. I'm almost sure the issue is on the apache/permissions/redirect side as the centos httpd config is way more strict than your default run-of-the-mill ubuntu/debian

**Comment by wprauchholz** [comment]
There is a permission issue. When I enter in Chrome localhost only I get also a 'localhost refused to connect.'. Googling now to see how to fix this, no solution yet.
Entering the server's IP address and domain name work fine.
I can ping localhost 
[root@home firefly-iii]# ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.076 ms
^C
--- localhost ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.057/0.065/0.076/0.010 ms




here is the full script of what I am doing in chronological order.

httpd-2.4.6-67.el7.centos.6.x86_64
mariadb-5.5.56-2.el7.x86_64

apache loads from /etc/httpd/conf.d/mod-rewrite.conf to force SSL mode

Steps:
1) curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
Result:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/xsl.so' - libexslt.so.0: cannot open shared object file: No such file or directory in Unknown on line 0
All settings correct for using Composer
Downloading...

Composer (version 1.5.2) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

2) composer -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/xsl.so' - libexslt.so.0: cannot open shared object file: No such file or directory in Unknown on line 0
Do not run Composer as root/super user! See https://getcomposer.org/root for details
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.5.2 2017-09-11 16:59:25


3) cd /var/www/html

4) composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.6.10
......
 Thank you for installing Firefly III, v4.6.10! 
......
 @php artisan key:generate
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/xsl.so' - libexslt.so.0: cannot open shared object file: No such file or directory in Unknown on line 0
Application key [base64:some code=] set successfully.

5) vi .env
* APP_DEBUG=true
* APP_FORCE_SSL=true
*** APP_URL=http://localhost (shouldn't I change this to https://<domain name>?)**
* DB_DATABASE=<db name>
* DB_USERNAME=<user name>
* DB_PASSWORD=<passwd>
* MAIL_HOST=<domain name>
* MAIL_FROM=<user name>@<domain name>
* MAIL_USERNAME=<user name>
* MAIL_PASSWORD=<passwd>
* SITE_OWNER=<user name>@<domain name> (same as MAIL_FROM)

6) mysql -u root -p
* create database <db name>;
* grant all privileges on <db name>.* to '<user name>'@'localhost' identified by '<passwd>';
* flush privileges;

7) php artisan migrate:refresh --seed
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/xsl.so' - libexslt.so.0: cannot open shared object file: No such file or directory in Unknown on line 0
Migration table not found.
Migration table created successfully.
Migrating: 2016_06_16_000000_create_support_tables
........
Migrated:  2017_08_20_062014_changes_for_v470
Seeding: AccountTypeSeeder
Seeding: TransactionCurrencySeeder
Seeding: TransactionTypeSeeder
Seeding: PermissionSeeder
Seeding: LinkTypeSeeder

8)
chown -R apache.apache /var/www/html/firefly-iii
chmod -R 775 /var/www/html/firefly-iii

**Comment by wprauchholz** [comment]
Logging...
* /var/www/html/firefly-iii/storage/upload > only file in here is .gitignore
* Nothing in /var/log/messages
* Nothing in /var/log/httpd/error_log
* Nothing in /var/log/httpd/access_log

**Comment by wprauchholz** [comment]
/firefly-iii/public "not found" probably means that the htaccess file is not refering to the correct index.php I 
think.
Content of firefly-iii/public
drwxrwxr-x  7 apache apache  4096 Nov  3 07:26 .
drwxrwxr-x 15 apache apache  4096 Nov 24 12:05 ..
-rwxrwxr-x  1 apache apache 14879 Nov  3 07:26 android-chrome-192x192.png
-rwxrwxr-x  1 apache apache 31871 Nov  3 07:26 android-chrome-512x512.png
-rwxrwxr-x  1 apache apache 10757 Nov  3 07:26 apple-touch-icon.png
-rwxrwxr-x  1 apache apache  1032 Nov  3 07:26 browserconfig.xml
drwxrwxr-x  3 apache apache  4096 Nov  3 07:26 css
-rwxrwxr-x  1 apache apache  1457 Nov  3 07:26 favicon-16x16.png
-rwxrwxr-x  1 apache apache  2325 Nov  3 07:26 favicon-32x32.png
-rwxrwxr-x  1 apache apache 15086 Nov  3 07:26 favicon.ico
drwxrwxr-x  2 apache apache  4096 Nov  3 07:26 fonts
-rwxrwxr-x  1 apache apache   584 Nov  3 07:26 .htaccess
drwxrwxr-x  3 apache apache   147 Nov  3 07:26 images
-rwxrwxr-x  1 apache apache  2580 Nov  3 07:26 index.php
drwxrwxr-x  4 apache apache    25 Nov  3 07:26 js
drwxrwxr-x  7 apache apache    82 Nov  3 07:26 lib
-rwxrwxr-x  1 apache apache   394 Nov  3 07:26 manifest.json
-rwxrwxr-x  1 apache apache 10455 Nov  3 07:26 mstile-150x150.png
-rwxrwxr-x  1 apache apache    25 Nov  3 07:26 robots.txt
-rwxrwxr-x  1 apache apache  4119 Nov  3 07:26 safari-pinned-tab.svg
-rwxrwxr-x  1 apache apache   914 Nov  3 07:26 web.config

**Comment by wprauchholz** [comment]
Trying to debug php warning too. But being a warning only, that should not be the problem

Interesting result.
* rpm -V php71u-xml returns blank.

* Though when I try to install it gives me this.
yum install php71u-xml
......
.......
Package php71u-xml-7.1.11-1.ius.centos7.x86_64 already installed and latest version
Nothing to do

**Comment by wprauchholz** [comment]
localhost can connect to apache on port 80.

[root@home ~]# curl -v localhost
* About to connect() to localhost port 80 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 24 Nov 2017 16:38:15 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_python/3.5.0- Python/2.7.5 PHP/7.1.11
< Last-Modified: Fri, 03 Feb 2017 07:00:08 GMT
< ETag: "ab-5479ad509dcff"
< Accept-Ranges: bytes
< Content-Length: 171
< Content-Type: text/html; charset=UTF-8
<
<html>

<head>
<title>Welcome to my new web server</title>
</head>

<body bgcolor="white" text="blue">

<h1> wo-lar.com Linux Home Server </h1>
Have fun

</body>

</html>
* Connection #0 to host localhost left intact

**Comment by wprauchholz** [comment]
It appears that I solved it.
The trick was to create a .htaccess file in the default document root, /var/www/html, for Apache.
to activate the RewriteEngine, which instructs Apache to process any rules that follow:

RewriteEngine On

**Comment by JC5** [comment]
Very strange indeed! I am glad it works now.

As for the forcing of SSL, I know that my Google Chrome has the tendency _not_ to go back to http when it has detected that https works as well. But this could also be a plugin.

If anything happens, or breaks again, let me know 👍

**Comment by wprauchholz** [comment]
You might consider that Centos 7 has this requirements.
I found it here in this howto.
https://www.digitalocean.com/community/tutorials/how-to-set-up-mod_rewrite-for-apache-on-centos-7
