### ISSUE TITLE
Ability to add attachments to split transaction

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1008]
I am running Firefly III version 4.6.11 

#### Description of my issue:

I took out 40 euros, cash, and payed 2 things, from which I got 2 separate receipts. The transaction looks like this

- 9.90Euro (Car - Winter-check): received a receipt which I'd like to keep for insurance purposes
- 9.00Euro (Car - Antifreeze)
- 15Euro (PS4 game): would keep the receipt in case the CD fails too soon
- 6.1Euro remaining

Right now, I can add attachments directly to the main transaction. If adding attachments to transaction-parts is not something you would do, maybe add a select-box where the user could select which attachment from the main transaction is mapped to which transaction-part

**Comment by JC5** [comment]
That seems way too specific to be useful to a lot of people. I would suggest renaming the files to refer to the correct split.

**Comment by gavu** [comment]
That's just what I did, thanks anyway. I had to give it a try though 👍

**Comment by JC5** [comment]
:D :+1:
