### ISSUE TITLE
Cannot change amount if it was zero

### ISSUE THREAD

**Issue by ursweiss** [firefly-iii/firefly-iii#1014]
I am running Firefly III version 4.6.10

#### Description of my issue:
If i create a transaction with an amount of "0" and try to save it, i get an "amount must be larger than zero." error. If i then change it to another value (f.ex. 10) i still cannot save the transaction. While saving i can see an input field named "Native amount" marked red for a very short time. Error: "native amount must be larger than zero."

**Comment by JC5** [comment]
Indeed. Once you fail, you cannot unfail. I'll check it out, thanks for reporting!

**Comment by JC5** [comment]
I've pushed a fix to [the demo site](https://firefly-iii.nder.be/). I you could clear your cache and try it, I would be most obliged. As far as I can tell, it works again.

**Comment by ursweiss** [comment]
Seems to work as expected. Thank you.

**Comment by JC5** [comment]
Great! I'm closing this one, expect a new release around December 1st! 👍
