### ISSUE TITLE
Enhance link type options

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1018]
Linking transactions has been possible for a while now. Think about how those links can be used.

**Comment by gavu** [comment]
I don’t know if this is an open discussion, but you could link multiple transactions to pay off a bigger debt/bill and name/describe that group of links accordingly

**Comment by david-me** [comment]
Perhaps links can help in the event someone pays a portion towards a budget (i.e, there's a budget, you pay $15 towards it, then another person pays you back $5 so you link your payment as partially reimbursed, so Firefly only counts $10 towards your budget)

**Comment by JC5** [comment]
Linked transactions will not influence each other. As such, the current set of features for transaction links will not change.
