### ISSUE TITLE
After upgrade firefly fails

### ISSUE THREAD

**Issue by tomazsustar** [firefly-iii/firefly-iii#1019]
I am running Firefly III version 4.6.10

#### Description of my issue:
I have upgraded to this version from 4.6.2 i think. I did this:

git pull
git checkout 4.6.10
rm -rf bootstrap/cache/*
rm -rf vendor/
composer install --no-scripts --no-dev
composer install --no-dev
php artisan migrate --env=production
Answer yes when asked.
php artisan cache:clear
php artisan firefly:upgrade-database

#### Steps to reproduce 
I visit the url: http://my-ip/firefly-iii/public

#### Other important details (log files, system info):

`Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)

Error

This error occured in file /var/www/html/firefly-iii/app/Support/Twig/General.php on line 161 with code 0.

Stack trace

#0 /var/www/html/firefly-iii/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/f...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('FireflyIII\\Supp...')
#2 /var/www/html/firefly-iii/app/Providers/FireflyServiceProvider.php(87): spl_autoload_call('FireflyIII\\Supp...')
#3 [internal function]: FireflyIII\Providers\FireflyServiceProvider->boot()
#4 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#5 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->call(Array)
#9 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(764): Illuminate\Foundation\Application->bootProvider(Object(FireflyIII\Providers\FireflyServiceProvider))
#10 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(FireflyIII\Providers\FireflyServiceProvider), 28)
#11 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(765): array_walk(Array, Object(Closure))
#12 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#13 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#14 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#15 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()
#16 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#17 /var/www/html/firefly-iii/public/index.php(74): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#18 {main}`

**Comment by tomazsustar** [comment]
Oh I needed PHP 7.1. Now it works.

**Comment by JC5** [comment]
Yep, that's it! Let me know if you have other questions.
