### ISSUE TITLE
Ability to link externally stored files

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1021]
I am running Firefly III version 4.6.11

#### Description of my issue:

The way FF handles uploads is great, although, having two document stores is not really productive. For example, on my NAS, I have a share where *all* my documents are stored (contracts, bills, receipts, personal documents, etc). Since I started using FF, I started re-uploading the contracts and receipts I already have stored on my NAS, just to have them linked to my financial data.

I currently use the "Internal reference" field to add the full path to the uploaded document, which can be really long. Although this (almost) works for me, there are 2 small draw-backs: you do not know which transaction uses this field (no icon like for the attachments) and also the field does not transform into a link.

I was thinking something like:
1. Full SMB access. This would allow FF to save the files directly onto shared drives, inside specific folders. Something like the browsers' option to ask where to save the downloaded file
2. Limited SMB access. You would save your file somewhere on a share, then go to FF, browse the share and "link" it. As a bonus, when opening the transaction (view/edit) you would be notified if the file is no longer there (deleted/renamed)
3. Transform links [the "Microsoft" way](https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/)

**Comment by JC5** [comment]
Mmm. I see several solutions but none of them seem viable.

* I could build in SMB, NFC, <etc> support but that is a lot of work for a very narrow use case. I really rather not focus my efforts on this. Just for file uploads.
* I can make you customize the place where files are uploaded. As long as your webserver can reach that path you can place files there. Of course, you could always turn `/storage/upload` into a symlink which is effectively the same, and saves me the trouble of adding yet another option.
* I could add a setting not to encrypt attachments but it would make everything less secure, especially on shared hosting. Even when the default is on, and I would have one user that would turn it off (you).

The thing is, Firefly supports pretty basic file uploads and beyond that you're really on your own.

I can tie into other solutions (export, import, command line options, API's) up to a point but I really rather focus on the product itself.

Personally, I don't store a lot of attachments on my instance for the same reason. So I suggest you pick one storage location and use that.

**Comment by gavu** [comment]
The `/storage/upload` solution is ok, I use it also (symlink), mainly because the NAS is a backed up storage. I forgot the uploads are encrypted, and the option to not encrypt attachments is definitely not secure. Would the 3rd option be a possibility?

1. User uploads the file onto the external storage
2. Copies the link to the file
3. Enters the link in a _special_ FF field
4. FF displays an icon (similar to the attachment icon) and transforms the link to a full URI

**Comment by JC5** [comment]
I'm not going to add a custom field with an URL parser for NAS attachments. If Firefly's attachments are no good fit for your use case, don't use them.
