### ISSUE TITLE
Markdown renders no line breaks

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1022]
I am running Firefly III version 4.6.11 

#### Description of my issue:

I have added the following text in a bill description

```
**Type**: Dauerauftrag
**Start**: 2012-08-01
**End**: -
```
which generated the following output:

**Type**: Dauerauftrag **Start**: 2012-08-01 **End**: -

but according to the [link](https://en.support.wordpress.com/markdown-quick-reference/) it should render line breaks just nicely:

> Line breaks | We do not support Markdown’s typical double-space to generate a line  break due to our built-in auto-linebreaking function. A regular line  break will generate a line break on output.

**Comment by JC5** [comment]
I'm not using the Wordpress Markdown dialect, so that makes sense.

Either use a double space at the end of a line, or use a double enter.

[Example](https://firefly-iii.nder.be/bills/show/2):

```
A  
B  
C  
```

Note the double space after A, B and C.

**Comment by gavu** [comment]
You are absolutely right, I don't know what I was thinking. It works exactly as you said. Thanks

**Comment by JC5** [comment]
No problem!
