### ISSUE TITLE
No currency found with code "EUR"

### ISSUE THREAD

**Issue by sprucify** [firefly-iii/firefly-iii#1023]
I am running Firefly III version 4.6.10 

#### Description of my issue:
No currency found with code "EUR"

#### Steps to reproduce
- Update repo
- Build docker
- docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
- docker-compose exec firefly-app composer install
- docker-compose exec firefly-app php artisan migrate
- create account on the panel
- after redirect I get the Whoops window with No currency found with code "EUR"

**Comment by JC5** [comment]
docker-compose exec firefly-app php artisan migrate

The correct command is:

docker-compose exec firefly-app php artisan migrate:refresh —seed

**Comment by JC5** [comment]
That’s - - without spaces.

**Comment by sprucify** [comment]
I had that command in my notes, but that would empty all existing data right?

**Comment by sprucify** [comment]
Yep I was trying to upgrade, but my docker volume somehow got renamed.
The seed command makes sense.

**Comment by JC5** [comment]
Glad to hear it’s not all gone :D

**Comment by sprucify** [comment]
well it is :p but it was time to start clean anyways to test #721
