### ISSUE TITLE
Pagination links for transaction tables are missing

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1024]
I am running Firefly III version 4.6.11 

#### Description of my issue:

https://firefly-iii.nder.be/transactions/withdrawal/all only shows 50 transactions (as configured in https://firefly-iii.nder.be/preferences). I hope I am not imagining it, but I remember there were pagination links at the bottom of the transaction list

**Comment by JC5** [comment]
No you're not, they're gone! I'll fix it before the next release.

**Comment by gavu** [comment]
I thought I started loosing it...
