### ISSUE TITLE
Deleting "Internal reference" does not update field

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1025]
I am running Firefly III version 4.6.11 

#### Description of my issue:

For some transactions, I added "Internal reference", now, because I do not need it any more, I tried to delete it. After deleting the field, I got the ` Success! Updated withdrawal "Going out for drinks again" `  message but the field was not updated

#### Steps to reproduce 

this problem also exists on the demo page: https://firefly-iii.nder.be/transactions/show/698

**Comment by JC5** [comment]
Nice find, fixed!
