### ISSUE TITLE
Translation missing for firefly.reconcile

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1026]
I am running Firefly III version 4.6.11 

#### Description of my issue:

`firefly.reconcile` translation missing (hover over button)

#### Steps to reproduce 

1. Go to https://firefly-iii.nder.be/accounts/asset
2. Hover over the reconcile button

![screen shot 2017-11-30 at 20 52 38](https://user-images.githubusercontent.com/3742238/33451827-796a8b52-d610-11e7-994f-88651958ae29.png)

**Comment by JC5** [comment]
Nice, must have missed that one. Will get it fixed :+1:

**Comment by zjean** [comment]
I found a translation issue as well at the reconcile page:
![image](https://user-images.githubusercontent.com/441924/33500401-f43c8862-d6d8-11e7-966c-f1bfbe71b2aa.png)

**Comment by JC5** [comment]
Nice, I've pushed a fix.
