### ISSUE TITLE
Today's indicator is set on October 1st

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1028]
I am running Firefly III version 4.6.11

#### Description of my issue:
When I change the default reporting period to a quarter of a year (in preferences), the main chart shows the today indicator on the wrong date.

#### Steps to reproduce 
Change reporting period to three months. Look (today, December 1st) to the main chart.

It is also wrong on the demo site.
![image](https://user-images.githubusercontent.com/441924/33499397-0d95a4f0-d6d5-11e7-8f92-23c5cc609990.png)

#### Other important details (log files, system info):
-

**Comment by JC5** [comment]
Indeed, it doesn't count right. I've pushed a fix (also visible on the demo site). Thx for reporting!

**Comment by JC5** [comment]
Oh, before I forget, I will build a new release end of next week to fix this one and some other bugs.
