### ISSUE TITLE
Next expected bill date

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1029]
I am running Firefly III version 4.6.11

#### Description of my issue:
The next expected bill date on /bills is different from bills/show. The latter seems correct.

#### Steps to reproduce 
Check the demo site:

Index:
![image](https://user-images.githubusercontent.com/441924/33500112-edb42adc-d6d7-11e7-9e89-215df2a41010.png)

Show:
![image](https://user-images.githubusercontent.com/441924/33500136-06737852-d6d8-11e7-9ac9-c12fb9bed4a3.png)

In code I see difference between the index method
https://github.com/firefly-iii/firefly-iii/blob/f7eb78364db044a673ab2777fa8d79ef5d5c70b8/app/Http/Controllers/BillController.php#L193 and the show method
https://github.com/firefly-iii/firefly-iii/blob/f7eb78364db044a673ab2777fa8d79ef5d5c70b8/app/Http/Controllers/BillController.php#L252 method.

#### Other important details (log files, system info):

Please visit the /debug page to get extra debug information.

**Comment by JC5** [comment]
I've pushed some fixes to make this more consistent. It should now report the correct date. It's live on the demo site, and I welcome your feedback!
