### ISSUE TITLE
Dashboard charts don't show in French language

### ISSUE THREAD

**Issue by Traxxi** [firefly-iii/firefly-iii#1030]
I am running Firefly III version 4.6.11

#### Description of my issue:
Since the 4.6.11 version, the dashboard's charts and "counters" ("Balance", "Bills to pay", etc.) don't show when language is set to french. (some JS errors?)
It's ok with all other languages.
Charts on other pages seems to work.
#### Steps to reproduce 
Change the language setting and come back to the dashboard.
This happens on demo site too.

#### Other important details (log files, system info):

And thank you so much for this amazing app !! it's just a wonderful work ! :)

**Comment by JC5** [comment]
Thanks for the compliments! 

I can confirm your bug. I forgot to escape the text. I shall push a new release end of next week that will fix this. The demo site in the meantime works again. You'll have to use the English variant for now.

**Comment by naber** [comment]
Hi,
I am using  Version 4.7.4 and same problem using Turkish language.

**Comment by JC5** [comment]
Which charts do not work, exactly? I cannot replicate the problem.

**Comment by naber** [comment]
Hi,
i attached screenshot below.  Can you look at.
![screenshot_20180629-212001](https://user-images.githubusercontent.com/870815/42108145-5d881f3a-7be2-11e8-9122-9fe26283204c.png)
![screenshot_20180629-211929](https://user-images.githubusercontent.com/870815/42108151-63af0644-7be2-11e8-85cb-9acec5cbdd57.png)

**Comment by naber** [comment]
Also not work desktop versiyon.

**Comment by naber** [comment]
hi again,
When English, 
<div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>

when Turkish 
<canvas id="accounts-chart" height="400" width="100%" style="width: 100%; height: 400px;" class="general-chart-error"></canvas>

![2018-06-29 22_35_50-neler oluyor_ firefly iii](https://user-images.githubusercontent.com/870815/42111415-1588d2aa-7bed-11e8-8d3a-1748ecd2ca2f.png)

**Comment by JC5** [comment]
Please share the console and any log errors you see in your Firefly III log files.

**Comment by naber** [comment]
Hi again,
I also updated Turkish translation.

[ff3-litespeed-2018-06-29 (1).log](https://github.com/firefly-iii/firefly-iii/files/2150898/ff3-litespeed-2018-06-29.1.log)

**Comment by JC5** [comment]
I suspect that the files you have edited have not been saved as UTF-8.

If you are on Windows, use Notepad++ to "Save with encoding" or "Save as UTF-8". Or download the original Turkish files from the site.

**Comment by naber** [comment]
Himmm, i used to softaculous installer.  And i think we need to all turkish files change to save as utf-8 an source.

**Comment by JC5** [comment]
They _are_. I am not sure what Softaculous does but they shouldn't change the encoding.
