### ISSUE TITLE
Import now creates double records and ignores already imported records

### ISSUE THREAD

**Issue by NimdaBE** [firefly-iii/firefly-iii#1031]
I am running Firefly III version 4.6.11

#### Description of my issue:
Hi,

I have upgraded my firefly installation and all was going well... I have my bankstatements as csv (Fintro bank) and they contain the transactions from the last 6 months (starting from the export-date). Now, when i try to import them it seems to ignore the already imported records (from before the upgrade) so now i have double records and none of the amount are correct anymore... Before the upgrade the import skipped the already imported records nicely... Please advice on how to proceed...

regards

**Comment by JC5** [comment]
Did you download the transactions again, from your bank? Or did you upload the same files again?

**Comment by NimdaBE** [comment]
i downloaded a new file from the bank to get the latest transactions. This file contains all transactions from today and the last 6 months... When i try to import the file from previous week (and before the upgrade) it skips all the transactions because they were already imported. But now with the file from this week the transactions ALL are imported. Those that were not present in the database are created (so those from the last few days). Those that were already present are imported again thus creating double records...

As far as i can see there is no change in the format of the csv file and the old records seem to be exactly like they are in the file of last week...

**Comment by gavu** [comment]
If you are using the latest version from the `develop` branch, the rules might not trigger because of an enhancement it is currently being developed

**Comment by NimdaBE** [comment]
I do not use the develop branch and i followed the instructions exactly as described on https://firefly-iii.github.io/using-upgrading.html

**Comment by JC5** [comment]
They seem exactly but they may not be. I fear that there is a difference between the two files, small as it may be.

Could you [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode)?

Then:

- Import the old file. Go to `storage/logs` and store the log file somewhere safe. It may be several MB. 
- Import the new file. The file may be several MB again.

Each import routine starts with this line:

```
local.INFO: Start with import job rNiM6pqFkhHS  
```

Where the ID is the same as the ID in the URL. It will continue parsing the CSV file:

```
local.NOTICE: Building importable objects from CSV file.  
```

After this, X objects will have been created:

```
local.INFO: Returned 4 valid objects from file processor  
```

Then it will start storing transactions line by line. At the end of each successful storage, you will see something like this:

```
local.DEBUG: Going to set "importHash" with value ""xxxx""  
local.DEBUG: Created journal with ID #xxx
```

This hash value is connected to the transaction that has just been created (ID). This can help you find the CSV line that has just been imported.

If this particular line has been imported before, the logs will reflect this:

```
local.INFO: Start with import job and1p2oS6jUE  
local.DEBUG: Job is configured, start with run()  
local.DEBUG: Now in CsvProcessor run(). Job is now running...  
local.DEBUG: Content size is 236 bytes.  
local.DEBUG: Created a CSV reader starting at offset 1  
local.NOTICE: Building importable objects from CSV file.  
local.DEBUG: Number of entries: 4  
local.INFO: Row #1 has already been imported.  
local.INFO: Row #2 has already been imported.  
local.INFO: Row #3 has already been imported.  
local.INFO: Row #4 has already been imported.  
```

For version 4.6.11.1 I can extend this line to reflect which transaction it is exactly, but you get the idea.

Even when the smallest details are different, or when field are in a different order, the hash will be different.

**Comment by NimdaBE** [comment]
Ok, i will test it this afternoon...

**Comment by NimdaBE** [comment]
i seem to have found the culprit... At first site the statements appear to be the same, but i used the compare plugin of Notepad++ and then the difference was immediately clear: for some reason my bank has changed the notation of the decimal mark from comma ("49,99") to points ("49.99") so i guess (i haven't verified this with the logfiles yet) that the import sees this as a different transaction with a different hash and thus imports it anyway...

What is the best way to continue? Is it best to start all over with the new type of notation? Is it best to change the decimal mark every time i'm going to import the bank statements? Can i change the previously imported lines so the future imports will match on the hash and nicely skipping all the previously imported lines?

**Comment by JC5** [comment]
Yes, the importer sees this as a different transaction and will import it as new. Personally, I would start over with the new notation and hope that they will not change it _again_. That way you don't have to edit your files all the time.

However, is there the possibility to export from your bank using some kind of time constraint? Constantly importing data that is already there seems less efficient.

**Comment by NimdaBE** [comment]
Yeah, i'm going to contact my bank tomorrow to see if this is a temporary bug on their website or if this is the new notation forever... In the second case, they could've warned us because i guess i won't be the only one that uses third party software for finance/budgetting and having this problem now...

There is no possibility to change the export options from my bank. For every account on their website there are 2 buttons. One for export to csv, and one for export to pdf. These buttons export all transactions from today up to 6 months ago from today, but there are no options that can be changed. That's why i always have a lot of transactions that are skipped and only the most recent between now and the previous import should be imported...

Starting all over again is a pain in the ass (for example, re-matching all the paypal transactions because there is no unique identifier in the statements etc...) and i don't have a way to export my transactions from the start of the account. So then i have manually change all the old csv-exportfiles to the new notation and importing them again...

I hope that when i contact them tomorrow they acknowledge a bug, and not a new way of notation... Fingers crossed...

**Comment by NimdaBE** [comment]
ok, a small update: i got a hold on the helpdesk of my bank and they confirmed that this is an error on their side... The development team will fix the bug and change it back to the comma-notation in the next few hours/days...

Thanks for the help and the great software you're making 👍

**Comment by JC5** [comment]
Glad to hear it, and you're most welcome! :+1:
