### ISSUE TITLE
Reconcile button is shown in expense and revenue accounts

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1032]
I am running Firefly III version 4.6.11

#### Description of my issue:
https://firefly-iii.nder.be/accounts/show/4

When clicking the blue Reconcile button, I get an error saying that only asset accounts can be reconciled.
Fair enough, but shouldn't this button be hidden?

#### Steps to reproduce 

https://firefly-iii.nder.be/accounts/show/4

#### Other important details (log files, system info):
 -

**Comment by JC5** [comment]
Nice find, I've pushed a fix that will hide the button when the account is not an asset account :)
