### ISSUE TITLE
[Feature request] Budget index page,current choice of hidden column on mobile

### ISSUE THREAD

**Issue by Jumanjii** [firefly-iii/firefly-iii#1033]
Current version : 4.6.8

Hi, 

On mobile, the current responsive settings are" hidden-sm hidden-xs" on 'spent' and 'left'.
If they were not, we could know how much we can spend directly on our smartphones from the front door of the bar ;-D

Personally, I find more pertinent to show these two columns and to hide the 'budgeted' one.
Or maybe that could be a choice accessible via the preferences panel ? 

Hoping that you like the idea :-)

**Comment by JC5** [comment]
I like your idea! I shall do some experiments tomorrow. I agree that
knowing what you spent and have left are important to know. I’ll keep you
updated!

**Comment by JC5** [comment]
I've pushed a fix (visible on the demo site) that will make the "left" column appear as well on mobile.
