### ISSUE TITLE
linked transaction count not correct

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1038]
I am running Firefly III version 4.6.11

#### Description of my issue:

`/admin/links` Number of transactions shows `4` but actually only 2 transactions are actually shown in the table on `/admin/links/show/4`

```
transaction_id_2 partially reimburses transaction_id_1
transaction_id_3 partially reimburses transaction_id_1
```

![screen shot 2017-12-05 at 08 33 35](https://user-images.githubusercontent.com/3742238/33595139-20672e68-d997-11e7-9ba6-296f48a40013.png)

#### Steps to reproduce 

cannot reproduce on demo site because the `/admin` page is not active

**Comment by JC5** [comment]
Well technically there are four transactions :wink: It's on the list to fix!

**Comment by gavu** [comment]
You are, of course, technically correct. Thanks!
