### ISSUE TITLE
[Sandstorm] Cannot create currencies, error message unhelpful

### ISSUE THREAD

**Issue by ocdtrekkie** [firefly-iii/firefly-iii#1039]
I am running Firefly III version 4.6.11 on Sandstorm

#### Description of my issue:

Creating currencies specifies to email "mail@example.com" if you'd like currencies added. This is both in the form of a blue banner that appears on the currencies tab and a red banner that appears when you attempt to press the Create currency button.

**Comment by simhnna** [comment]
That's because you are not an admin for the instance. Refer to #741 on how to promote your user if you have access to the database

**Comment by ocdtrekkie** [comment]
@simhnna That isn't really an option on the Sandstorm version.

**Comment by ocdtrekkie** [comment]
As a useful note on this: This is only still an issue on instances of Firefly III that were upgraded from earlier versions. I just created a new one, and it works correctly.

It may make sense as a migration somewhere in a future version, if Firefly III only has one user and is running on Sandstorm, to upgrade the user to admin, if that is what is missing.

**Comment by JC5** [comment]
Thanks for letting me know! I've seen it before, some times users aren't raised to the admin level even when they're the only one around.

I shall add something to the login routine. That should catch them all.
