### ISSUE TITLE
Where/How to get the Database Schema?

### ISSUE THREAD

**Issue by lowercase00** [firefly-iii/firefly-iii#1041]
I am running Firefly III version x.x.x 

#### Steps to reproduce 

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):

Please visit the /debug page to get extra debug information.

**Comment by JC5** [comment]
It’s in [database/migrations](https://github.com/firefly-iii/firefly-iii/tree/master/database/migrations).

**Comment by JC5** [comment]
You're welcome mate.

**Comment by lowercase00** [comment]
Thanks a lot, appreciate that.
Sorry for neglecting the importance of explicit "thanks".
Cheers
