### ISSUE TITLE
Docker image fails to build (Automatic builds on docker hub failing)

### ISSUE THREAD

**Issue by zabouth** [firefly-iii/firefly-iii#1042]
I am running Firefly III version 4.6.11

#### Description of my issue:

Docker image is failing to build with error `E: Package 'libpng12-dev' has no installation candidate`.
After updating dockerfile to use libpng-dev build fails with. 

```
error: /usr/src/php/ext/mcrypt does not exist

usage: /usr/local/bin/docker-php-ext-install [-jN] ext-name [ext-name ...]
   ie: /usr/local/bin/docker-php-ext-install gd mysqli
       /usr/local/bin/docker-php-ext-install pdo pdo_mysql
       /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop

if custom ./configure arguments are necessary, see docker-php-ext-configure
```

#### Steps to reproduce 

- Clone
- run `docker-compose up` or `docker build .`

#### Other important details (log files, system info):

It looks like the build has been failing since 2017-12-01
https://hub.docker.com/r/jc5x/firefly-iii/builds/

**Comment by JC5** [comment]
I'll check it out!

**Comment by JC5** [comment]
I've fixed the develop-branch, master/latest will follow tomorrow!

**Comment by zabouth** [comment]
Thank you for your quick response it's really appreciated.

**Comment by JC5** [comment]
Latest is building again, thanks!
