### ISSUE TITLE
Import using Salt Edge

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1044]
See https://www.saltedge.com/

**Comment by dckc** [comment]
What's the difference between fixed and closed?

I'm trying to use this feature via sandstorm and I'm getting prompted by Salt Edge to request test access. Am I doing it wrong? Should I stand by for a future release?

**Comment by JC5** [comment]
The Salt Edge import feature is about to be released at the end of the month. Hence, the issue is "fixed" but not yet closed: it's not actually there yet. So yes, you'll have to stand by for a future release.

As for Salt Edge: to access their system you need API keys. To get API keys, you need an account. Unfortunately, I can't share my own account details since Firefly III is open source. Each user who wants to use Salt Edge as a method of importing data must create an account with Salt Edge and request test access in order for it to work. You can tell them you use Firefly III to fast-track the process but it's a bit of a hassle.

Salt Edge is a really useful system but not really designed for something like Firefly III.
