### ISSUE TITLE
Question regarding imports

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1045]
I am running Firefly III version 4.6.11.1

This is just a question, not an issue or a feature request

#### Description of my issue:

I was trying to import with a pre-formatted notes (sepa-debet) field with markdown like this:

> ### Attachments:
> _(none)_
> 
> ### Original description:
> dafhjkhdf aklsjfaklsdfjaskldfjha lkajaf lk fa f asdfafs a

I use a bash script to manipulate my bank statements as they are not really user-friendly, so adding some extra `\n` to the field was no problem. 

- I noticed the finished import-csv was created correctly,  I could see the new lines (not the characters) and all the `#` and `_`
- FF even showed the titles and italic texts correctly after the import
- however, the new lines / line breaks were missing. 

Is FF escaping them somehow during the import?

**Comment by JC5** [comment]
The current CSV library strips these. I've pushed an updated composer.json file that will update this library from v8 to v9. It should no longer happen in the updated version.

Once you do a `git pull` you should run `composer update` to install it.https://github.com/thephpleague/csv/issues/124
This is a major version update however and I haven't tested if Firefly III will remain working with it. So no guarantees, yet ;)

**Comment by gavu** [comment]
I updated as described. I’ll check it out and let you know. Thanks!

**Comment by JC5** [comment]
I believe this is working as expected, isn't it? I recall you have a daily cronjob :)

**Comment by gavu** [comment]
Hi,

sorry, was busy with Christmas-stuff. I updated everything as described:

The csv-column file looks like this:
```
[...];

##Attachments##

_(none)_

sadhsilfh lsf asldfg asljdhfg kasdjhfg askdjfg askjhfg sa
;[...]
```

The transaction imported correctly, everything looks fine, except the notes field, it is empty. Any suggestions?

**Comment by JC5** [comment]
Make sure it is encased in quotes.

```
[..],"Some note", [..]
[..],"Some multi
line note", [..]
```

That should fix it. Also, there is now the option to select the "Note" field. I remembered I promised to add it.

**Comment by gavu** [comment]
I’ll give it a try tomorrow. I’m sure it will work now. 

Regarding the notes field, thanks! It’s like an early Christmas present!

**Comment by gavu** [comment]
Quick question: what will happen to the “notes” imported into the sepa-debet field? Would I have to “move” them via SQL? Or does FF just “concat” both columns into the new notes field?

**Comment by JC5** [comment]
They're all concatenated into the same note.
