### ISSUE TITLE
Can't open second page of all transactions from category

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1046]
I am running Firefly III version 4.6.11, but problem also exists on demo using 4.6.11.1.

#### Description of my issue:

Can't open second page of all transactions from category.

#### Steps to reproduce 

1. Open category with many transactions - eg. ["Car" on demo site](https://firefly-iii.nder.be/categories/show/2).
2. Click "Show all transactions without grouping them by date." - URL changes to `/categories/show/2/all`
3. Click second page - URL changes to `/categories/show/2?page=2` without `/all`.

#### Other important details (log files, system info):

Checked also transactions from tags, but problem doesn't exists there - only in categories.

**Comment by JC5** [comment]
Indeed you cannot, nice find! I've pushed a fixed to the demo site, the next release (end of the month) will include it.

**Comment by pkoziol** [comment]
👍
