### ISSUE TITLE
Reconciliation page doesn't work

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1047]
I am running Firefly III version 4.6.11.1 at demo site.

#### Description of my issue:

Wanted to translate reconciliation strings, but I don't know how it works, so I wanted to test it using demo site. Unfortunately I failed.

#### Steps to reproduce 

1. Go to: https://firefly-iii.nder.be/accounts/reconcile/1/index/2017-12-01/2017-12-31
2. Check first two checkboxes or whatever you want.
3. Click button "Store reconciliation".
4. Browser sends AJAX/XHR to https://firefly-iii.nder.be/accounts/reconcile/1/overview/2017-12-01/2017-12-31?... and gets some HTML as a response, but there is no visual effect.

#### Other important details (log files, system info):

Browser's JavaScript console is empty. Turning off uBlock Origin didn't help. Refreshing cache with Ctrl+F5 also didn't help.

**Comment by JC5** [comment]
I've found the bug and fixed it. It will be live next come the next release, and on the demo site right now. Thanks for reporting it!

**Comment by pkoziol** [comment]
👍
