### ISSUE TITLE
Asset-Account overview shows "firefly.openingBalance"

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#1049]
The hover-text of the star-icon says "firefly.openingBalance" (Asset-Account Overview -> Transactions).

![screenshot_20171210_205500](https://user-images.githubusercontent.com/31184224/33808798-7a922b5a-ddec-11e7-8ffd-7f1a7e122de2.png)

I checked this on the demo-page. It is there too.

**Comment by JC5** [comment]
Yay, nice find. I must have forgotten to add this string to the translation list. I shall add it and it will be gone!

**Comment by nicoschreiner** [comment]
Thanks! :D

**Comment by JC5** [comment]
Closed to clean up the list.
