### ISSUE TITLE
New Version Notification

### ISSUE THREAD

**Issue by 8bitgentleman** [firefly-iii/firefly-iii#1050]
As of right now the only way, that I know of, to see if there is a new version of firefly iii is to check the github releases page. It would be nice to have some kind of notification within firefly iii to notify the user/admin to update firefly. For example when there is a new version released there could be a bar across the top of the page notifying the user of the new version with links to the github releases page or the wiki update instructions.

**Comment by JC5** [comment]
Sounds like a good idea. It shouldn't be hard to track the releases page. I will do some research to see what's possible.

**Comment by JC5** [comment]
Note to self:

If user is admin, store "permission_update_check" with value -1 and "last_update_check" with value `time()`. 

FF3 will check every week for an update (1), do nothing (0) or ask the user what to do (-1), enable or disable check? If yes, do a check and then wait a week again.

This means that FF3 will first prompt about updates after a week of usage (so user is not overwhelmed with popups).

When a new version is released, will link to github release. Also means that Github releases must have a clear link to update instructions.

**Comment by JC5** [comment]
The new version of Firefly (I plan to release it tomorrow) will already have some code to check for an updated version.

After about a week it will ask you to [change a setting](https://demo.firefly-iii.org/admin/update-check). When you set it to check, it won't actually do anything (it doesn't work yet).

However, the button on the right _does_ work. It doesn't work on the demo-site btw, but it will work in your version.

Next version will do the actual check.
