### ISSUE TITLE
Be right back after upgrade from 4.6.9 to 4.6.11.1

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#1052]
I am running Firefly III version 4.6.11.1, right after running upgrade via CLI (.sh script) from 4.6.9

#### Description of my issue:
Be right back message is displayed, similar to issue #889 and I followed all the php artisan recommendations there, problem appears to be different. Checked permissions on the files and that is all ok. Have reverted to snapshot on the webserver but can repeat process again happily enough

#### Steps to reproduce 
Upgrade from 4.6.9 direct to 4.6.11.1

#### Other important details (log files, system info):

Enabling debug provides following output:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'transactions.reconciled' in 'field list' (SQL: select `transaction_journals`.`id` as `journal_id`, `transaction_journals`.`description`, `transaction_journals`.`date`, `transaction_journals`.`encrypted`, `transaction_types`.`type` as `transaction_type_type`, `transaction_journals`.`bill_id`, `transaction_journals`.`updated_at`, `bills`.`name` as `bill_name`, `bills`.`name_encrypted` as `bill_name_encrypted`, `transactions`.`id` as `id`, `transactions`.`description` as `transaction_description`, `transactions`.`account_id`, `transactions`.`reconciled`, `transactions`.`identifier`, `transactions`.`transaction_journal_id`, `transactions`.`amount` as `transaction_amount`, `transactions`.`transaction_currency_id` as `transaction_currency_id`, `transaction_currencies`.`code` as `transaction_currency_code`, `transaction_currencies`.`symbol` as `transaction_currency_symbol`, `transaction_currencies`.`decimal_places` as `transaction_currency_dp`, `transactions`.`foreign_amount` as `transaction_foreign_amount`, `transactions`.`foreign_currency_id` as `foreign_currency_id`, `foreign_currencies`.`code` as `foreign_currency_code`, `foreign_currencies`.`symbol` as `foreign_currency_symbol`, `foreign_currencies`.`decimal_places` as `foreign_currency_dp`, `accounts`.`name` as `account_name`, `accounts`.`encrypted` as `account_encrypted`, `accounts`.`iban` as `account_iban`, `account_types`.`type` as `account_type` from `transactions` left join `transaction_journals` on `transaction_journals`.`id` = `transactions`.`transaction_journal_id` left join `transaction_types` on `transaction_types`.`id` = `transaction_journals`.`transaction_type_id` left join `bills` on `bills`.`id` = `transaction_journals`.`bill_id` left join `accounts` on `accounts`.`id` = `transactions`.`account_id` left join `account_types` on `accounts`.`account_type_id` = `account_types`.`id` left join `transaction_currencies` on `transaction_currencies`.`id` = `transactions`.`transaction_currency_id` left join `transaction_currencies` as `foreign_currencies` on `foreign_currencies`.`id` = `transactions`.`foreign_currency_id` where `transactions`.`deleted_at` is null and `transaction_journals`.`deleted_at` is null and `transaction_journals`.`user_id` = 1 and `transactions`.`account_id` in (1) and `transaction_journals`.`date` >= 2017-12-01 and `transaction_journals`.`date` <= 2017-12-31 and `transactions`.`deleted_at` is null order by `transaction_journals`.`date` desc, `transaction_journals`.`order` asc, `transaction_journals`.`id` desc, `transaction_journals`.`description` desc, `transactions`.`amount` desc limit 10 offset 0)`

Any recommendations?

**Comment by JC5** [comment]
Back up your database (!!!!)

Then run:

```
php artisan migrate
php artisan firefly:upgrade-database
php artisan firefly:verify
```

**Comment by ragnarkarlsson** [comment]
I added 

`php artisan firefly:verify`

Into my script and ran it again (had reverted to snapshot), seems to have resolved it. Thanks!
