### ISSUE TITLE
Checking paid spendings by the bank

### ISSUE THREAD

**Issue by pereverti** [firefly-iii/firefly-iii#1054]
Hi,

I am running Firefly III version 4.6.11.1. Congratulations for the huge work and the application \o/
I'm new with it and I'm looking for how to check debts as soon as they're paid by the bank.
Indeed, when I create an expense, the associated funds are still in my bank account. So this expense is not really paid. When I compare with my internet banking app, I'd like to check the FFIII expense row to confirm the payment (just a checkbox).
Does exist a way to do it ? Or maybe it will be a nice feature to follow in details bank payments ?
Thank you for your attention :)

++

**Comment by JC5** [comment]
Thanks for the compliments! ^^

Let's see if I get this right: you spend 25,- at the grocery store, and you pay using your bank account (be it by card, by check, whatever). 

If you register this in Firefly III, your balance is changed immediately.

Your bank takes some time to reflect this. Could be 1 hour, could be 1 week.

Are you looking to reconcile your transactions? That would allow you to "sync" your bank transactions with Firefly IIIThere is a [page on the demo site](https://demo.firefly-iii.org/accounts/reconcile/1/index) where you can try this.

The idea is this: select a range (for example a month) and enter the start and endbalance that your bank says you have. You can use a paper bank statement for this. Then, start reconciling by checking all transactions that are on the bank statement. This is the checkbox you're looking for I think.

Let me know if this is what you had in mind.

**Comment by pereverti** [comment]
Hi,

It's just what I want to do. It's just perfect :-)
You're application is amazing. You can be prout of it 👍 

Thank you again for your fast answer and sorry to not find this feature by myself.

**Comment by JC5** [comment]
:tada: :+1:
