### ISSUE TITLE
Can't import CSV on Sanstorm Oasis

### ISSUE THREAD

**Issue by repercussion** [firefly-iii/firefly-iii#1056]
I've been keen to try firefly-iii for a long time but have never had the time to work through it. Pumped to see that it was available as a Sandstorm app, I installed it and set up a few things. 

Trying to import a CSV, though, I hit a roadblock. I kept dumbing down the CSV as it came from the bank to eliminate possibilties. This is arguably the most simple csv available. Seven transactions. Three columns. Simple dates, no headers. Every time, I get the [error](https://i.imgur.com/7L4MORH.png):

```
Time out while waiting for job to finish.
```
[Here's a CSV I'm not able to import](https://pastebin.com/raw/AvR4Kgyn)

[Here are my mappings](https://i.imgur.com/MxvFAjC.png)

**Comment by JC5** [comment]
Thanks for reporting this!

Something is broken indeed. I can replicate your issue. It works fine on my local installation, but Sandstorm is having none of it.

Could you click on the version number at the bottom right of the page? That should show you some debug info. Could you share that with me?

I will investigate further later today.

**Comment by repercussion** [comment]
More bad news! Clicking the version number yields another error.

https://i.imgur.com/sWm21RF.png

**Comment by repercussion** [comment]
Tried again and got this:

```
Debug information generated at 2017-12-19 17:39:26 UTC for Firefly III version **4.6.11.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.6.11.1 |
| PHP version | 7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3 |
| Host | Linux sandbox 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 |
| Interface | fpm-fcgi |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache |
| UserID | 1 |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | yes |
| Sandstorm anon? | no || Is Sandstorm (.env) | true |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14 |
```

and 

```
Truncated from this point <----|[2017-12-19 17:38:04] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_get_contents(\/opt\/app\/storage\/logs\/ff3-fpm-fcgi-2017-12-19.log): failed to open stream: No such file or directory","time":"Tue, 19 Dec 2017 17:38:04 +0000","file":"\/opt\/app\/app\/Http\/Controllers\/HomeController.php","line":115,"code":0,"version":"4.6.11.1"}  
[2017-12-19 17:38:04] local.ERROR: Swift Transport ExceptionConnection could not be established with host smtp.mailtrap.io [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]  
[2017-12-19 17:38:04] local.ERROR: file_get_contents(/opt/app/storage/logs/ff3-fpm-fcgi-2017-12-19.log): failed to open stream: No such file or directory {"userId":1,"email":"ec62e34213ccb07153fa70ff7e49dee6@firefly","exception":"[object] (ErrorException(code: 0): file_get_contents(/opt/app/storage/logs/ff3-fpm-fcgi-2017-12-19.log): failed to open stream: No such file or directory at /opt/app/app/Http/Controllers/HomeController.php:115)"} 

```

**Comment by JC5** [comment]
Makes sense, should have known, Sandstorm has a different way of collecting log files. I shall adapt the code. 

I'll try to replicate the issue locally and get back to you!

**Comment by JC5** [comment]
I think I found the problem. It works now, locally. I shall  push this fix into the next release, which should arrive close to new year's.

Unfortunately, you'll have to wait until then before you can import.

**Comment by repercussion** [comment]
Lovely. I'll have a full year's worth of imports ready! Thank you!
