### ISSUE TITLE
[Coinbase] Unable to import simple CSV with bitcoin transactions - "No Decimal Character Found"

### ISSUE THREAD

**Issue by 4oo4** [firefly-iii/firefly-iii#1059]
I am running Firefly III version 4.6.11.1

#### Description of my issue:
I'm attempting to import a CSV from my bitcoin exchange (Coinbase), but Firefly seems to get the BTC amount wrong each time (showing an impossibly postive/negative bitcoin balance), as if it's ignoring the decimals. At first, I was attempting to import the whole file (about 70 transactions), but for some reason Firefly kept saying there were 350 transactions while importing. From there, I started stripping off columns (the transaction count issue may be due to a weirdly-formatted CSV, I'll dig into that later), and still got the incorrect balances. From looking in the logs, I noticed it was saying that it wasn't recognizing the decimal character.

#### Steps to reproduce 
 - Attempt to import following CSV file in to new bitcoin asset account (config is selecting headers, date format as `Y-m-d`, and then using Date and Amount columns):
```
"Date","Amount"
"2013-10-10","0.208"
"2013-10-12","-0.15"
"2013-10-19","-0.03881677"
"2013-10-21","0.33"
"2013-10-22","-0.34918323"
"2013-12-01","0.1"
"2013-12-01","-0.1"
"2013-12-11","0.01124"
"2013-12-11","-0.01124"
"2014-02-14","0.115"
"2014-02-14","-0.115"
"2014-04-04","1.33"
```

#### Other important details (log files, system info):
![selection_018](https://user-images.githubusercontent.com/15698835/34176385-5c20b31e-e4c5-11e7-8911-7460a26f41c0.png)
![selection_019](https://user-images.githubusercontent.com/15698835/34176512-bc0c2f60-e4c5-11e7-9dc7-f45f76de3106.png)

`/firefly/storage/logs/ff3-apache2handler-2017-12-19.log`
```
[2017-12-19 19:45:15] production.DEBUG: debet amount is NULL  
[2017-12-19 19:45:15] production.DEBUG: credit amount is NULL  
[2017-12-19 19:45:15] production.DEBUG: convertedAmount is NULL  
[2017-12-19 19:45:15] production.DEBUG: Amount value is not NULL, assume this is the correct value.  
[2017-12-19 19:45:15] production.DEBUG: Converter class is FireflyIII\Import\Converter\Amount  
[2017-12-19 19:45:15] production.DEBUG: Start with amount "-0.115"  
[2017-12-19 19:45:15] production.DEBUG: No decimal character found. Converted amount from "-0.115" to "-0115".  
[2017-12-19 19:45:15] production.DEBUG: First attempt to convert gives "-115.000000000000"  
[2017-12-19 19:45:15] production.DEBUG: After modifiers the result is: "-115.000000000000"  
[2017-12-19 19:45:15] production.DEBUG: convertedAmount is: "-115.000000000000"  
[2017-12-19 19:45:15] production.DEBUG: In createCurrency()  
```

**Comment by JC5** [comment]
Thanks for including the logs, and thanks of course for reporting this bug. I believe that the amount converter is unable to handle more than 2 decimals. I’ll check it out and get back to you!

**Comment by JC5** [comment]
I've pushed a fix that will go live with the next release (around 1-1-18). 

You can see the test cases [here](https://github.com/firefly-iii/firefly-iii/blob/develop/tests/Unit/Import/Converter/AmountTest.php). They should all work as expected.

**Comment by 4oo4** [comment]
Sounds good, thanks for the quick fix! I'll check it out with the next release.

**Comment by JC5** [comment]
It's the number of lines * the number of steps, which is 5. So 20 transactions is about 100 steps. It's not perfect (not all steps are the same size) but it works fairly well.

I've linked this to the next release and I'll close it when it goes live!

**Comment by JC5** [comment]
Closed to clean up the list.
