### ISSUE TITLE
Delete all unused creditors\crediteuren at once

### ISSUE THREAD

**Issue by marviins87** [firefly-iii/firefly-iii#1060]
I am running Firefly III version 4.6.11

#Feature request:
I try to keep my creditors list clean. Would it be possible to create a function\button to delete all unused creditors at one click? We've to delete all the unused creditors one by one manually at the moment.

Current steps:
1) Search for unused creditor
2) Click delete
3) Confirm deletion
4) page will refresh, go back to step 1 to proceed deleting the next one. 

Kind Regards,
Marvin

**Comment by simhnna** [comment]
By unused creditor you mean creditors that were never part in any transaction?
* If the answer is **yes**, why were they created in the first place. This sounds like a custom need, and is best resolved using a db query.
* If the answer is **no**, what should happen to the transactions associated with it? I don't think deleting them is a viable option...

**Comment by JC5** [comment]
There will be no mass-delete routine: it's a lot of work to build for a very small use case.

However, to clean up your accounts (all of them!) quickly, run this query:

```
update accounts SET deleted_at = NOW() where id not in(
select distinct account_id from transactions where deleted_at is null)
```

This will soft-delete (which means you can restore them) all accounts that have no undeleted transactions linked to them.

Let me know if this is what you're looking for.

**Comment by JC5** [comment]
Setting up  a cron job with this should not be difficult to arrange. A simple pdo_mysql query should do the trick.

**Comment by JC5** [comment]
Closed to clean up the list.
