### ISSUE TITLE
Cannot budget money to specific envelope

### ISSUE THREAD

**Issue by Meizikyn** [firefly-iii/firefly-iii#1061]
I am running Firefly III version 4.6.11.1
 
On the Budgets page, attempting to "budget" money to a Budget object (envelope), via. the "budgeted" field causes the "left" field to load indefinitely, and is not saved upon re-accessing the page.

Money is added to the total budget via. the pencil icon when viewing a month.

This problem exists on both the Demo site and when self-hosting sandstorm.io

**Comment by JC5** [comment]
I cannot replicate this. I have successfully changed the budgets on this page:

https://demo.firefly-iii.org/budgets/2018-01-01

(123, 456, 789, 111)

I was able to do so in Firefly, Chrome and Safari.

Are you using Internet Explorer / Edge?

**Comment by Meizikyn** [comment]
It is worth noting I'm running firefly iii on Sandstorm.io, referring to the demo they provide, and deployment hosted on my home server.

My browsers (Chromium and Firefox) work with the demo link you provided, this may only be in the sandstorm version, unsure if it was better to post here on in sandstorm Git

**Comment by JC5** [comment]
Ah yes, that is definitely a bug and I know what is going wrong. I shall push a fix immediately!

It will go live when the new version is released, which is around New Year's. You'll have to do without envelope amounts until then, I'm afraid :(.

Thanks for reporting this, I appreciate it!

**Comment by JC5** [comment]
Cool! Closed to clean up the list.
