### ISSUE TITLE
Firefly in docker behind reverse proxy, APP_URL does not work?

### ISSUE THREAD

**Issue by Xeli** [firefly-iii/firefly-iii#1062]
I am running Firefly III via the docker image: 'jc5x/firefly-iii' I do not use the docker-compose file from this repo, because it maps port 80 to the host, and I already have a webserver running there. Instead I map port 80 of docker to port 9001 on my host machine.

What I would like is to run firefly behind this webserver and have the webserver act as a (reverse) proxy.
At the moment I can connect to firefly via http://192.168.1.123:9001/login this works fine as the 9001 port points to the docker container, but because it does not go via my webserver I have to type the port number and have no ssl.

When I try to connect to firefly via my webserver (firefly.mydomain.com) firefly redirects me to http://localhost:9001/login I assume this is because the proxy connects to firefly via the url http://localhost:9001 and firefly uses this to build all the urls right?

I had hoped the APP_URL in the .env would fix this, but when I set the env APP_URL=https://firefly.mydomain.com nothing changes. How can I convince firefly the url should be firefly.mydomain.com ?

**Comment by nicoschreiner** [comment]
You should take a look at issue #921 and #882. These describe a similar problem like yours.

In short: There is a .env-variable `TRUSTED_PROXIES` which should be set to the IP of your reverse-proxy. You can also use `**` to allow all proxy-servers.

**Comment by nicoschreiner** [comment]
For example this is a part of my `.env` file:

```bash
# ...
APP_URL=https://firefly.example.com
TRUSTED_PROXIES=**
# ...
```

**Comment by Xeli** [comment]
Great that works, it just wants to retrieve the stylesheets via http now, any idea how to fix this? APP_FORCE_SSL does not seem to change anything

**Comment by JC5** [comment]
`APP_FORCE_SSL` is no longer applicable, hence it is no longer in any of the configuration files. It was abandoned in favor of the `TRUSTED_PROXIES` line.

I see that @nicoschreiner used the `APP_URL`. Did you try that?

**Comment by Xeli** [comment]
Yeah specifically I've set these env variables in the docker compose:

`     - FF_DB_HOST=mysql
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=somepw
      - FF_APP_KEY=base64:some-secret-string
      - FF_APP_ENV=local
      - APP_URL=https://firefly.example.com
      - APP_FORCE_SSL=true
      - TRUSTED_PROXIES=**`

**Comment by Xeli** [comment]
Ok I fixed it. Firefly (or rather laravel) respects the http header: X-Forwarded-Proto when set to https all the links get fixed.

In my cache I added this to my (ssl) vhost file: **RequestHeader set X-Forwarded-Proto "https"**

This along with the .env provided by @nicoschreiner fixed this :)

**Comment by JC5** [comment]
Thanks for sharing, I shall update the website to reflect this!

**Comment by danger89** [comment]
Actually this is my working example in Nginx:

Ps. Change `your.domain.com` to your public domain name.

```
# this section is needed to proxy web-socket connections
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    server_name your.domain.com;
    server_tokens off;    
    return 301 https://$host$request_uri;
}

server {
    # listen on ssl
    listen 443 ssl http2;
    server_name your.domain.com;
    server_tokens off;

    ssl on;
    # Certificate & key
    ssl_certificate /etc/letsencrypt/live/your.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/your.domain.com/privkey.pem; # managed by Certbot

    # Increase security (using the Diffie-Hellman Group file)
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    
    ssl_protocols TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES265-SHA:!aNULL;
    ssl_prefer_server_ciphers on;
    ssl_ecdh_curve secp521r1:secp384r1:secp256k1;
    
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_stapling on;
    ssl_stapling_verify on;
    
    #  Feature to support on your site and strengthens your implementation of TLS by getting the User Agent to enforce the use of HTTPS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    # Don't allow the browser to render the page inside an frame or iframe and avoid clickjacking
    add_header X-Frame-Options SAMEORIGIN;
    # When serving user-supplied content, include a X-Content-Type-Options: nosniff header along with the Content-Type: header,
    # to disable content-type sniffing on some browsers.
    add_header X-Content-Type-Options nosniff;
    # Enable the Cross-site scripting (XSS) filter built into most recent web browsers.
    add_header X-XSS-Protection "1; mode=block";
    # Referrer Policy will allow a site to control the value of the referer header in links away from their pages.
    add_header Referrer-Policy "no-referrer";
    
    # Pass request to Firefly iii
    location / {
        proxy_pass http://127.0.0.1:84;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
    }
}
```
