### ISSUE TITLE
Wrong balance difference after starting reconcilation with all transactions already reconciled

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1063]
I am running Firefly III version 4.6.12 on the demo site.

#### Description of my issue:

Tried to reconcile account with all transactions marked as already reconciled in given period. Firefly said in "Reconciliation options" that I'm missing €1,336.52. Changing end balance and reverting it back correctly displays €0.00.

#### Steps to reproduce 

https://gfycat.com/FluffyMeekIrishsetter

#### Other important details (log files, system info):

Please visit the /debug page to get extra debug information.

**Comment by JC5** [comment]
Aha, nice find! I shall try to fix this before the next release!

**Comment by pkoziol** [comment]
Fixed as fast as always. 👍
