### ISSUE TITLE
Wrong title for generated Expense/revenue account report

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1064]
I am running Firefly III version 4.6.12 on demo site.

#### Description of my issue:

Generated newest report type - Expense/revenue account report. Not sure how it works, because there is to little transactions on the demo site, but... found copy-pasted title: Default financial report between January 2017 and December 2017

![](https://i.imgur.com/9iEFpoX.png)

#### Steps to reproduce 

https://demo.firefly-iii.org/reports/account/1,32,2,3/5,11/20170101/20171231

PS: Demo's help message says:
> Firefly III supports **four** types of reports. Read about them by clicking on the (?)-icon in the top right corner. 

(?)-icon popup describes **five** report types and "Report type" `<select>` allows to choose one of **six** types 😉

**Comment by JC5** [comment]
Nice find! I have elected to only say "there are a number of reports available" so my count can no longer lag behind the number of options.

Honestly, I never expected to offer 6 types of reports 😉

**Comment by pkoziol** [comment]
👍
