### ISSUE TITLE
Not all env variables exposed via .env.docker

### ISSUE THREAD

**Issue by vicmosin** [firefly-iii/firefly-iii#1067]
I am wondering why not all of them exposed? For example, if I want to specify custom APP_HOST and proxy I have to fork the repo and inject my own code.. 
Any reason for that?

**Comment by JC5** [comment]
I don't think you have to. Laravel takes environment variables into account and will not overwrite them. So you should be able to run Docker with `-e TRUSTED_PROXIES=**` for example.

I'll test this to be sure.

**Comment by JC5** [comment]
I was able to overrule `APP_LOG_LEVEL` by adding `APP_LOG_LEVEL=debug` to the Docker compose file. I'm going to assume that this would work for the other options to launch Docker containers as well (setting env vars).

Let me know if this works, OK?
