### ISSUE TITLE
Wrong URL when deploying with docker

### ISSUE THREAD

**Issue by Zegorax** [firefly-iii/firefly-iii#1068]
I am running Firefly III latest version

#### Description of my issue:

When deploying using the instruction for Docker, the website shows the wrong URL. Every link points to localhost:50009 instead of the domain for example. I don't where to change this.

#### Steps to reproduce 

Use this docker-compose : 

version: '2'

services:
  firefly-db:
    image: mysql:8
    network_mode: bridge
    restart: always
    environment:
      - MYSQL_DATABASE=firefly_iii_db
      - MYSQL_USER=firefly_db
      - MYSQL_PASSWORD=firefly_db_secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./firefly-db:/var/lib/mysql

  firefly-app:
    image: jc5x/firefly-iii
    network_mode: bridge
    restart: always
    hostname: xxx.mydomain.com
    environment:
      - FF_DB_HOST=firefly-db
      - FF_DB_NAME=firefly_iii_db
      - FF_DB_USER=firefly_db
      - FF_DB_PASSWORD=firefly_db_secret
      - FF_APP_KEY=SomeRandomStringOf32CharsExactly
      - FF_APP_ENV=local
      - 
    ports:
      - "50009:80"
    volumes:
      - ./firefly-export:/var/www/firefly-iii/storage/export
      - ./firefly-upload:/var/www/firefly-iii/storage/upload
    links:
      - firefly-db

#### Other important details (log files, system info):
Not necessary here I guess. 
Here's a screenshot : 

https://imgur.com/a/kzVQm

**Comment by JC5** [comment]
Thx for letting me know!

There's no need to update anything. A new release is almost done and the documentation has been updated as well. I spotted this too and it will be correct in the new documentation.

**Comment by Zegorax** [comment]
Okay perfect ! Do you have an estimation of time for this next release ?

**Comment by JC5** [comment]
Should be before the end of the year!

**Comment by Zegorax** [comment]
Okay perfect. I really need Firefly it's a very good project !

**Comment by JC5** [comment]
:+1:
