### ISSUE TITLE
[Question] Languages

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#1069]
I am running Firefly III version  4.6.11.1

#### Description of my issue:

Hello.

I put the pt-BR folder in languages, but you do not have the Portuguese option in the preferences. How can I include it?

**Comment by pkoziol** [comment]
Hi! You problably have to uncomment line in `config/firefly.php`:

https://github.com/firefly-iii/firefly-iii/blob/e47b218fc1ebb2ba5b5ca50dcf39401b9219c7da/config/firefly.php#L137

**Comment by JC5** [comment]
Yes, that should do it.

**Comment by wtercato** [comment]
Thank you so much for the quick reply!

You do a great job!

**Comment by JC5** [comment]
:+1:
