### ISSUE TITLE
"Be right back" after confirming reconciliation

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1070]
I am running Firefly III version 4.6.12 on the demo site.

#### Description of my issue:

Wanted to test creation of reconciliation transaction that corrects balance. Selected transactions were cleared, but there is no correcting transaction.

#### Steps to reproduce 

1. Start reconciling [Checking Account](https://demo.firefly-iii.org/accounts/reconcile/1/index/2017-12-01/2017-12-31).
2. Select all transactions except transfer from December 28, 2017
3. Click "Store reconciliation".
4. Select "Clear the selected transactions, and create a correction removing €-140.00 from this asset account."
5. Click "Confirm reconciliation".

Firefly shows "Be right back" page (and problably sends you an e-mail?). Selected transactions were cleared, but there is no correcting transaction.

**Comment by JC5** [comment]
There should be an error in the logs, could you share it?

**Comment by pkoziol** [comment]
Check your demo installation, I only break it not mine 😛

**Comment by JC5** [comment]
Should be fixed! Thanks for reporting! :+1:

**Comment by JC5** [comment]
Closed to clean up the list.
