### ISSUE TITLE
[Question] AWS-S3

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#1072]
I am running Firefly III version 4.6.11.1 

Hello.

The file "firefly-iii/config/filesystems.php" mentions the AWS-S3 as a storage option.

Is this feature already working? I did not find in the .env configuration file the field to enter the settings of my AWS-S3.

**Comment by JC5** [comment]
It is not, and it probably will not be included. The option to support AWS requires some extra code and other packages as well.

**Comment by wtercato** [comment]
Hello.

I am running under Amazon AWS, with EC2, RDS, etc. .. for now, I will try to mount a S3 bucket in the direct upload folder in linux. thank you so much

**Comment by JC5** [comment]
:+1:
