### ISSUE TITLE
Notes field on accounts

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#1074]
I am running Firefly III version 4.6.11.1

#### Description of my issue:
Would it be possible to add some kind of Notes field to the Asset accounts? To be able to connect to my Web Banking sometimes I need a specific number to identify my digipass.
On my previous software I stored these codes in the notes field of my accounts.

It could also be used to store any remarks for the accounts

**Comment by JC5** [comment]
Yes, should not be difficult. Will be in the release from January.
