### ISSUE TITLE
Change piggy bank for a transaction

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#1075]
I am running Firefly III version 4.6.11.1

#### Description of my issue:
When you create a new transaction of Transfer type you have the piggy bank field to link that transaction to one of your piggy banks.
When you edit that transaction you can't change that value as the field does not appear...

#### Steps to reproduce 
Store a transfer transaction and choose a piggy bank (or leave it to none). Edit that transaction and that field does not appear.

The only way to change that is to clone the transaction as the field appears at that time, then delete the old one...

**Comment by JC5** [comment]
The link you're referring to is only cosmetic. Each time you add money to a piggy bank, or remove money from it, a log-entry is created. You can see some [here](https://demo.firefly-iii.org/piggy-banks/show/1).

If a transaction is linked to that log-entry the transaction will also show the log entry. But when the transaction is updated or removed the original log-entry is not changed.

**Comment by MacPaille** [comment]
OK I see, I thought it was linked to the transactions :)
Then no need for this feature. Thanks!

And thanks again for this wonderful product! Keep improving it!

**Comment by JC5** [comment]
You're welcome, will do! :D
