### ISSUE TITLE
[Question] left side menu

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#1076]
I am running Firefly III version 4.6.11.1 

#### Description of question:

Hello.

Paweł Kozioł explained that commenting the php code in the config/firefly.php, I modify the items that appears in the language preferences. Is there any file(s) where I can comment and make some options disappear from the left side menu?

For example, the "Money Management" option.

**Comment by JC5** [comment]
You could edit the HTML files if you want to?

**Comment by wtercato** [comment]
Great. What are the left side menu files?

**Comment by JC5** [comment]
`resources/views/partials/menu-sidebar.twig`

**Comment by wtercato** [comment]
great. I'm not very familiar with this architecture. thank you so much.

**Comment by JC5** [comment]
:+1:
