### ISSUE TITLE
creating tags

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#1077]
I am running Firefly III version 4.6.12

#### Description of my issue:

Hello!

After creating the first tag, there is no more option to create more tags.

![tags](https://user-images.githubusercontent.com/30444736/34449871-ba7ace32-ece4-11e7-9b44-0fe136227ec2.jpg)

**Comment by JC5** [comment]
No matter. Every tag can be created freehand by simply typing in the tag name when you create a new transaction. Press enter for each tag and it will be created along with the transaction.

I shall make sure the button is always there, but you shouldn't really need it.

**Comment by JC5** [comment]
Release is live, issue will be closed.
