### ISSUE TITLE
Interface 'FireflyIII\Services\Github\Request\GitHubRequest' not found

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1080]
I am running Firefly III version 4.6.12

#### Description of my issue:
The update button is not working.

Firefly III v4.6.12 ran into an error: Interface 'FireflyIII\Services\Github\Request\GitHubRequest' not found

The error was of type "Symfony\Component\Debug\Exception\FatalErrorException".

#### Steps to reproduce 
Click the update button
Also exists on the demo site.

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
Fix pushed. MacOS is case insensitive, so it never caught this. It'll work again with the next release, which that button will not tell you about :wink:
