### ISSUE TITLE
[Suggestion] Simple installation and update on a virtual hosting

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1084]
I am running Firefly III version 2.6.2  (and can not upgrade to a newer version).

I really want to use Firefly every laziness, but I have a virtual hosting and I can not update my installation normally. I need to update the local copy each time, and then manually transfer the new version to my hosting. This is very inconvenient and often leads to problems.
Please make it possible to update (and install) your program to a virtual hosting without using a composer, using only PHP-scripts (like Wordpress and other CMS).
Such a program as FireFly is needed not only for administrators of web servers, and a simpler installation will help ordinary people to use it without technical problems.

PS. Happy New Year to all!

**Comment by JC5** [comment]
I'm sorry, but I can't help you with this. I cannot provide a version of Firefly with all the dependencies inside of it. I cannot recreate composer so it works on virtual hosting. I'm afraid that would ruin the point of using composer. After all, it's all for dependency management.

What I can only suggest is that you stop hosting Firefly III on virtual hosting, but get something like Heroku, Sandstorm, or a Docker hosting provider such as AWS, Azure or Google to host a dockerized instance of the latest version of Firefly III.

Those are easy to upgrade and easy to maintain. I assume you are running version 4.6.2 and I can always help you upgrade your database. But I cannot improve support for virtual hosting.

I'm seeing a trend where people move away from virtual hosting in complex (and often outdated) environments but simply opt to host single-serving apps "in the cloud". Or even local, in what people tend to call a "private cloud". Regardless, I feel that FTP-based hosting providers with only a `www` folder are on the decline.

Hence, I would suggest moving away from virtual hosting instead :).

**Comment by Nik-vr** [comment]
Oh ... I'm too old for all this :) Maybe you just can sometimes make a "snapshot" of your program, which can be easily copied to a virtual hosting.

**Comment by Nik-vr** [comment]
I installed FireFly on https: //oasis.sandstorm.io. But there I can not fully control the program. Only make a backup copy of the database. Also I can not change anything in .php-files (translation into Russian, for example, I can not add). In a copy on the local server, there is no problem with this, since I completely control the program.

**Comment by Nik-vr** [comment]
On my server, I can update the main part of the FireFly files (download master.zip). But I can not update the catalog "vendor" correctly. I think that to successfully update the virtual hosting, you just need to upload the archive with fresh FireFly code and fresh versions of the "vendor" catalog. Probably, I still need somehow to update the database to the new version.

**Comment by JC5** [comment]
Is it not an option to run a virtual machine on your own PC?

**Comment by Nik-vr** [comment]
Now I use WAMP server (not virtual PC), similar to my virtual hosting (the same version of the software). I also started using the SQLite database. So it's easier to update the software.

**Comment by JC5** [comment]
Make sure you backup the database and the .env file regularly. You will need both to rescue your database in case of trouble. If anything is not working, please let me know!

**Comment by Nik-vr** [comment]
Ok! Thank you!
