### ISSUE TITLE
Change language of login page

### ISSUE THREAD

**Issue by Findus23** [firefly-iii/firefly-iii#1090]
*I am running Firefly III version 4.6.12.*

Maybe that's a stupid question or has been asked before, but I just noticed that the Login (and 2FA) pages are always displayed in English for me. This makes sense as the language is a user setting and before logging in Firefly can't know my Language.
But if all users of an instance are speaking the same language it would be nice if one could set a default locale (or respect `Accept-Language`).

**Comment by JC5** [comment]
I can add the strings from these files to the translation files. That way, I think at least the 2FA page will pick up on it (at that point FF3 knows which user it is and can pick up on preferences).

Others pages will not, unless you change the `locale` config var in `config/app.php` yourself (at your own peril). If you set it to `de_DE` Firefly III will default to German.

Firefly III will not be responding to the `Accept-Language` header, especially not for logged in users. For other users, using English on one page should not be _that_ big of a deal. :wink:

**Comment by Findus23** [comment]
As it took me a few months of using Firefly to notice it, I guess it really isn't important. I just thought I had missed an option.

**Comment by JC5** [comment]
Release is live, issue will be closed.
