### ISSUE TITLE
Error - Query Exception

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#1091]
I am running Firefly III version 4.6.12

#### Description of my issue:

Hello.
When you try to write a new transaction, this error appears.
I can change the transactions that I have already recorded normally.

---
(3/3) QueryException
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`compras`.`transaction_journals`, CONSTRAINT `transaction_journals_transaction_currency_id_foreign` FOREIGN KEY (`transaction_currency_id`) REFERENCES `transaction_currencies` (`id`) ON DELETE) (SQL: insert into `transaction_journals` (`user_id`, `transaction_type_id`, `transaction_currency_id`, `description`, `encrypted`, `completed`, `date`, `tag_count`, `updated_at`, `created_at`) values (1, 1, 0, 10kg farinha trigo, 0, 0, 2018-01-02 00:00:00, 0, 2018-01-02 17:29:19, 2018-01-02 17:29:19))

---
(2/3) PDOException
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`compras`.`transaction_journals`, CONSTRAINT `transaction_journals_transaction_currency_id_foreign` FOREIGN KEY (`transaction_currency_id`) REFERENCES `transaction_currencies` (`id`) ON DELETE)

---
(1/3) PDOException
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`compras`.`transaction_journals`, CONSTRAINT `transaction_journals_transaction_currency_id_foreign` FOREIGN KEY (`transaction_currency_id`) REFERENCES `transaction_currencies` (`id`) ON DELETE)

[Error.pdf](https://github.com/firefly-iii/firefly-iii/files/1598225/Error.pdf)

**Comment by JC5** [comment]
That's quite impossible. Could you please share from your database the content of the table "transaction_currencies"?

If you would, in text is fine, not a PDF.

**Comment by JC5** [comment]
Never mind, I found it!

I suspect you forgot to run the following commands when upgrading. Do this on the command line, from the Firefly III directory.

```bash
php artisan firefly:upgrade
php artisan firefly:verify
```

If that does not help, run this query on your database:

```sql
delete from account_meta where name="currency_id";
```

Then do:

```bash
php artisan firefly:upgrade
php artisan firefly:verify
```

**Comment by wtercato** [comment]
Hello. I did a new installation of version 4.6.12, does not make an update, so it is not runthe commands whit the update script.

After the delete in the table of the database, and run the php artisan, the system returned to work. Thats great!

However, since 3 old transactions are like wrong accounts in the transaction screen, but when I enter the respective transaction, it is correct.

Should I update the 4 files you fixed?

**Comment by JC5** [comment]
Go to your asset accounts, edit each one and select the currency they have. Then it should be fixed.

**Comment by wtercato** [comment]
OK.

I'll check the account settings ..

I can apply the fixes to the files:
app/Console/Commands/UpgradeDatabase.php
app/Http/Requests/JournalFormRequest.php
app/Repositories/Journal/SupportJournalsTrait.php
app/Support/Steam.php

Can I also apply in the versions that I have been running and have not experienced this problem?

**Comment by JC5** [comment]
Yes, you can. However, once you have edited the accounts and saved them, it should not be necessary.

**Comment by JC5** [comment]
Release is live, issue will be closed.
