### ISSUE TITLE
[Feature Request] Link budget and categories

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1094]
I am running Firefly III version 4.6.12.

Example. I use the category "Products". I also created a budget "For products". If I create a new withdrawal, I need to select the "Products" category and specify the "For Products" budget. It would be convenient if the budget was immediately associated with the definite category (or several), so that it would not be necessary to choose manually and category and budget each time you created the withdrawal.

**Comment by JC5** [comment]
You can create rules to link them.

![screen shot 2018-01-05 at 11 23 57](https://user-images.githubusercontent.com/5889984/34605189-f32dde60-f20a-11e7-9af1-244fd92c096c.png)

The first rule sets the appropriate category when the budget is set to "Product". The second rule sets the appropriate budget when the category is "Products".

The third rule sets _both_ when the description contains "something about products".

**Comment by Nik-vr** [comment]
Oh! ... I have not yet found this wonderful feature. Thanks for the help!

**Comment by JC5** [comment]
:+1: You're welcome!
