### ISSUE TITLE
Can't translate some strings

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1098]
I can't translate some strings. 

"Initial balance for [asset_account_name]" on Dashboard and account's history.

PS. Please add Russian language to list on options page (now I need to edit firefly.php to add this). Also, add, please, Russian Ruble to default currencies list.

**Comment by JC5** [comment]
The Russian Ruble is already in the currencies list. It will only be added to new installations, so if you do not have it right now, you can add it yourself under Options > Currencies.

I shall add the requested string to the language files. Currently, Russian [is only at 33%](https://crowdin.com/project/firefly-iii), and I would like it to be at 75% before I can add it.

If you have a lot of strings you have translated already, send them to me over email and I shall update Crowdin.

**Comment by Nik-vr** [comment]
I created the currency "Russian ruble" back in the old version. If it exists in the new version, it's good.

Now I'm translating FirFly hrough Crowdin. Please approve new lines.

**Comment by Nik-vr** [comment]
On the "Rules" page 2 lines are not translated. I translate it in the file firefly.php (see on crowdin), but they are displayed in English.

![rules-page](https://user-images.githubusercontent.com/520760/34647250-c9bf0970-f38e-11e7-899f-d03f298d5466.jpg)

**Comment by JC5** [comment]
That rule group, and its description, is created when you first visit the /rules page. If it was in English back then, it will be saved in English.

When you delete all of your rules and visit the page again, they will be recreated in Russian.

**Comment by Nik-vr** [comment]
Thank you! I recreate all rules, and now all OK.

**Comment by Nik-vr** [comment]
PS. I translated 75% of the text into Russian :) 

There are texts left for correct translation of which I need to study in more detail the corresponding functions of the FireFly.

**Comment by Nik-vr** [comment]
All the strings on the login page remain in English. All of these strings are translated in the file firefly.php.

![login-form](https://user-images.githubusercontent.com/520760/34661647-1c4819e8-f45c-11e7-9573-bb268dc78da5.jpg)

**Comment by JC5** [comment]
That is correct. At this point you are not logged in, so Firefly does not know you are Russian. You can force Firefly to show this page in Russian by changing the locale setting in config/app.php.

**Comment by Nik-vr** [comment]
Hmm ... It turns out that these strings are in the localization files, but not used?
Maybe it would be more logical to translate the input form if one user mode is on and the language is selected for it?

**Comment by Nik-vr** [comment]
String "Select all" are not in the files for translation.

![reports-page](https://user-images.githubusercontent.com/520760/34663835-e234face-f469-11e7-962f-79d4fcada0c1.jpg)

**Comment by JC5** [comment]
I'll make sure that "Select all" can be translated. The login I cannot help, I'm afraid. The only option is to change config/app.php.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1109
