### ISSUE TITLE
[Question] Budget for revenue planning

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1099]
In my old program for financial management, I used the budget not only to account for expenses, but also for revenue planning. Similarly created a "revenue plan for the month" for a particular income category, and on the chart saw the "filling" of this budget.

As I understand it, in FireFly the budget serves only to account for expenses. Is it possible to make a budget for revenue planning too?

It would also be convenient to divide the categories into "expense categories" and "income categories" so that when you record a transaction, you only see the categories of the desired type.

**Comment by JC5** [comment]
The categories will remain as is: you'll have to keep them apart yourself. You can use the category report to see how you're doing.

Isn't budgeting exactly what you mean? On the /budgets page you can set a total amount, and an amount per month. The total amount shows bars that slowly fill as you spend and budget money.

**Comment by Nik-vr** [comment]
> Isn't budgeting exactly what you mean? On the /budgets page you can set a total amount, and an amount per month. The total amount shows bars that slowly fill as you spend and budget money.

Unfortunately, this does not work. For example, I have a "Job" category, according to which I receive revenue in small parts within a month. I have a plan for how much I should earn on this revenue category. But when creating a new revenue, I just do not see the Budget field.

**Comment by JC5** [comment]
On the budgets page, you can set the total amount of money you expect to receive that month. You cannot work towards it as you would with expenses.

**Comment by Nik-vr** [comment]
This is not the most convenient option. In our family there are several sources of income and we are used to watching each of them.

**Comment by JC5** [comment]
Firefly III isn't built for it. In Firefly you budget your expenses for the next month (February). You make sure you have the money you have budgeted on or before February 1st.

Any money you earn in February is kept separate for March. You budget your expenses again for March. On or before the 1st of March you make sure you have the money you need.

**Comment by Nik-vr** [comment]
I understood. I have been keeping track of family finances for many years and are used to another scheme. I will think about how to change this.
