### ISSUE TITLE
Error while editing the opening balance of the account

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1100]
I am running Firefly III version 4.6.12. 

Little bug.

1. Create a new account, specify the opening balance. For example $1.
2. Edit the account (name, or opening balance). For example $2. Save.
3. The opening balance of the account becomes negative (the amount does not change).  -$2.

To correctly change the opening balance or account name, you must first make the opening balance equal to 0, save. Then specify a new name / opening balance (and date!) and save again.

I use the main currency "Russian ruble" (created manually) and the database SQLite.

The log is attached.

[ff3-apache2handler-2018-01-06.log](https://github.com/firefly-iii/firefly-iii/files/1608884/ff3-apache2handler-2018-01-06.log)

**Comment by JC5** [comment]
Yes, it's a known issue. If nothing else breaks I shall release a fix this weekend.

**Comment by Nik-vr** [comment]
ok! Thank!

**Comment by JC5** [comment]
Release is live, issue will be closed.
