### ISSUE TITLE
Amount in "Net worth" block, if the accounts are in different currencies

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1101]
The amount in the "Net worth" block takes into account only accounts in the base currency. I have one account, the currency of which differs from the main one, and its balance is not taken into account in the "Net worth".
Can you make this possible? Apparently, you need to receive exchange rates from some source and convert.

**Comment by JC5** [comment]
Yes, future versions will support this. There is already a routine present that can do conversions, but the box will probably display both currencies.

**Comment by Nik-vr** [comment]
>  box will probably display both currencies
You mean two amounts will be shown (the amount for "currency 1" and the amount for "currency 2")?

**Comment by JC5** [comment]
Yes, that's what I'm thinking of now. I am not yet sure. Firefly III can already do currency conversion, but it is always "inaccurate" because banks will often use slightly different exchange rates.
