### ISSUE TITLE
Add Total Row for Bills

### ISSUE THREAD

**Issue by kelvinhammond** [firefly-iii/firefly-iii#1102]
I am running Firefly III version x.x.x 

#### Description of my issue:
The bills page doesn't have a total, can you add one.

#### Steps to reproduce 
Go to the bills list page.
See demo.

#### Other important details (log files, system info):
Version: develop

**Comment by JC5** [comment]
I'm not sure which column would be the most useful to sum up. Any suggestions?

**Comment by gavu** [comment]
Are you still considering this? If yes, I’d suggest all of them:

* max_amount
* min_amount
* max_amount/2 (as shown in the dashboard panel)

This way the user would know exactly what to expect.

**Comment by Jumanjii** [comment]
What is the max_amount/2 that you speak about?

**Comment by Torpis** [comment]
I imagine he meant min+max/2

**Comment by JC5** [comment]
This has been added, and is now visible on the demo site. For additional questions, please open a new issue. Thanks for the suggestion!

https://demo.firefly-iii.org/bills

**Comment by Jumanjii** [comment]
Cool :+1:
