### ISSUE TITLE
Update in terminal

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#1104]
I am running Firefly III version 4.6.12

#### Description of my issue:

Hello.

when I'm going to do the upgrade process from version 4.6.12 to version 4.6.13, the system indicates that the new version is not yet available. 

is there any step I should take?

![7633bc9b-19c4-49c3-a584-bc7ae9bd112b](https://user-images.githubusercontent.com/30444736/34650624-3e7b117a-f3ab-11e7-9e7b-0fdfc7245e4b.jpeg)

**Comment by JC5** [comment]
How did you originally install Firefly III?

https://firefly-iii.org/using-upgrading.html

**Comment by wtercato** [comment]
I'm sorry, I misunderstood a command.

**Comment by wtercato** [comment]
Hello.

I made several upgrades (4.6.12 to 4.6.13), and setup from zero of version 4.6.13. Everything worked perfectly.

Thank you!
