### ISSUE TITLE
Add legend to accounts chart

### ISSUE THREAD

**Issue by Findus23** [firefly-iii/firefly-iii#1105]
Hi, an idea for a small feature:

With a lot of account of which some are saving accounts that don't really change a lot, the nice accounts chart on the homepage isn't as useful as it could be.

I think allowing to temporarily hide accounts would make it much easier to see the day-to-day changes.

A simple fix would be adding the default legend:
```diff
diff --git a/public/js/ff/charts.js b/public/js/ff/charts.js
index a67009b72..4566b3748 100644
--- a/public/js/ff/charts.js
+++ b/public/js/ff/charts.js
@@ -132,7 +132,7 @@ function lineChart(URI, container) {
 function lineChartWithDay(URI, container, today) {
     "use strict";
     var colorData = true;
-    var options = $.extend(true, {}, defaultChartOptions);
+    var options = $.extend(true, {legend:{display:true,position:"bottom"}}, defaultChartOptions);
     var chartType = 'line';
 
     drawAChart(URI, container, chartType, options, colorData, today);
```

**Comment by JC5** [comment]
In your preferences, you can set which accounts should appear on the frontpage. Personally I've turned off all but two accounts.

**Comment by Findus23** [comment]
Thanks, seems like I have missed that setting. 
Disabling some accounts makes this graph far better.
