### ISSUE TITLE
Total amount in reports

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#1106]
I am running Firefly III version 4.6.13 

I'm mainly using the category report to verify my monthly balance and note all the values of each category in an Excel. To be able to quickly compare both I was used to compare the total value of all the Earned and the Spent columns. In your reports these totals do not exists.

Would it be possible to add it? Both in the Accounts part and in the Categories part

Thanks :)

**Comment by JC5** [comment]
Sure thing!
