### ISSUE TITLE
Budget Ordering

### ISSUE THREAD

**Issue by Torpis** [firefly-iii/firefly-iii#1108]
I am running Firefly III version 4.6.12

#### Steps to reproduce 

It would be great to have a way to reorder budgets. Maybe by adding an "order" field to the budget edit page and then being able to sort by that - could be a hidden field for users who don't want custom ordering?

Or possibly even use the same drag as drop as on transactions on category pages

#### Other important details (log files, system info):

NA

**Comment by JC5** [comment]
That's a good idea, I'll write it down!

Please note that it won't be for a few versions before I can implement this. I want the database to be stable for a few versions. But I'll keep you posted.

**Comment by JC5** [comment]
This will be possible in the next release.
