### ISSUE TITLE
Feedback for overspending a budget

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1110]
As suggested by a user on reddit. Perhaps a warning or an error bar?

**Comment by Torpis** [comment]
Maybe add a similar bar to the one used on Piggybanks, it stays yellow until you go over your budget which it then goes red. This would be a clear visual when going over budget.

I'm not sure how easy it would be but including it on the Budget page, but also when adding a transaction. So you select the budget on the transactions and it then loads the bar showing current spent + this transaction.

**Comment by JC5** [comment]
That is a very good idea!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937669
