### ISSUE TITLE
Suggest budget changes

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1111]
Suggest user changes or updates budgets:

- When user sets a budget for amount more than last time (or last x times)
- When budget is spent, ask to move money from other budgets. Auto-suggest correct amount.
- When user forgets to set money, but had money last time.

**Comment by jinformatique** [comment]
Hello, I am not sure if I have a bug that is linked to this:
At the beginning of the month I set 50€, then some days later I changed it to 200€.
Now I see two lines, is it normal? I prefer to see only the last one.
![image](https://user-images.githubusercontent.com/487038/35284854-273b20aa-005c-11e8-81f6-f235e0e70828.png)

**Comment by JC5** [comment]
It's not normal. It is supposed to be impossible but it happens every now and then. I shall try to make sure that in the future, such double entries get cleared up automatically.

**Comment by jinformatique** [comment]
I don't know if this is linked or not but I have a full page with budgets. I made as many budget as I have categories.

There are 2 things:
- On my second budget line, I have put an amount (243), and each time I change page and come back, the amount is at 1 instead of 243. This drives me nuts!

- As my list of budget is so long, I have 2 pages and on the second page I have one budget.
Then the graph at the top does only take into account the budget from the second page and not from all the other budget entries.
It would be better to not have pagination for budget page.

**Comment by JC5** [comment]
* You second budget line, you mean the second budget in the list?
* I can fix the problems you mention. Pagination I cannot help I'm afraid. Creating so many budgets, especially when they are equal to your categories, is not something that many users do.

**Comment by jinformatique** [comment]
Each time I put a value in it:
![budget2](https://user-images.githubusercontent.com/487038/35727568-d09de48a-0808-11e8-9178-7e1c88ca67ec.png)


I go on another page, dashboard, or categories, or whatever, when I come back, it's like this:


![budget1](https://user-images.githubusercontent.com/487038/35727567-ce100a40-0808-11e8-8346-e68872b8dcce.png)

In fact, I deleted this budget line and recreated again. It's working now.
But to test, I put the same amount on the first and third line, and then when I try to change it, I cannot as it stays the same value I entered the first time.
So what I understand here is that only the first entry is taken into account, then we cannot change it.


> Creating so many budgets, especially when they are equal to your categories, is not something that many users do.

I prefer to stick to the method as described by [YNAB](https://www.youneedabudget.com/method/). There is a rule "Give Every Dollar A Job". So I created as many envelope as I have categories. This way I can track every euro spent.

**Comment by JC5** [comment]
Could you try the following.

1. In another tab, click the version number (bottom right) to go to the debug screen.
2. In the first tab, change the amount like you demonstrate in the screenshot. Do nothing else.
3. Refresh the debug page. Copy both boxes here in a reply.

With a little luck the log file shows more details and I can see what is going on exactly.

**Comment by jinformatique** [comment]
Debug information generated at 2018-02-02 21:07:18 UTC for Firefly III version **4.7.0**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.0 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.13-1+ubuntu16.04.1+deb.sury.org+1 |
| Display errors | Off |
| Error reporting | ALL errors |
| Host | Linux ThinkPad-T460s 4.13.0-32-generic # 35\~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 |
| Interface | apache2handler |
| UserID | 1 |
| DB drivers | mysql, sqlite |
| Current driver | sqlite |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, vlucas/phpdotenv@v2.4.0, symfony/css-selector@v4.0.4, tijsverkoyen/css-to-inline-styles@2.2.1, symfony/polyfill-mbstring@v1.6.0, symfony/var-dumper@v3.4.4, symfony/routing@v3.4.4, symfony/process@v3.4.4, paragonie/random_compat@v2.0.11, symfony/polyfill-php70@v1.6.0, symfony/http-foundation@v3.4.4, symfony/event-dispatcher@v4.0.4, psr/log@1.0.2, symfony/debug@v3.4.4, symfony/http-kernel@v3.4.4, symfony/finder@v3.4.4, symfony/console@v3.4.4, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, swiftmailer/swiftmailer@v6.0.2, ramsey/uuid@3.7.3, psr/simple-cache@1.0.0, psr/container@1.0.0, symfony/translation@v3.4.4, nesbot/carbon@1.22.1, mtdowling/cron-expression@v1.2.1, monolog/monolog@1.23.0, league/flysystem@1.0.42, erusev/parsedown@1.6.4, doctrine/inflector@v1.3.0, laravel/framework@v5.5.33, davejamesmiller/laravel-breadcrumbs@4.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, fideloper/proxy@3.3.4, laravelcollective/html@v5.5.1, league/commonmark@0.17.0, league/csv@9.1.1, paragonie/constant_time_encoding@v2.2.1, symfony/polyfill-util@v1.6.0, symfony/polyfill-php56@v1.6.0, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, twig/twig@v1.35.0, rcrowe/twigbridge@v0.9.5, rmccue/requests@v1.7.0, watson/validating@3.1.2,  |





Debug information generated at 2018-02-02 21:08:11 UTC for Firefly III version **4.7.0**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.0 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.13-1+ubuntu16.04.1+deb.sury.org+1 |
| Display errors | Off |
| Error reporting | ALL errors |
| Host | Linux ThinkPad-T460s 4.13.0-32-generic # 35\~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 |
| Interface | apache2handler |
| UserID | 1 |
| DB drivers | mysql, sqlite |
| Current driver | sqlite |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, vlucas/phpdotenv@v2.4.0, symfony/css-selector@v4.0.4, tijsverkoyen/css-to-inline-styles@2.2.1, symfony/polyfill-mbstring@v1.6.0, symfony/var-dumper@v3.4.4, symfony/routing@v3.4.4, symfony/process@v3.4.4, paragonie/random_compat@v2.0.11, symfony/polyfill-php70@v1.6.0, symfony/http-foundation@v3.4.4, symfony/event-dispatcher@v4.0.4, psr/log@1.0.2, symfony/debug@v3.4.4, symfony/http-kernel@v3.4.4, symfony/finder@v3.4.4, symfony/console@v3.4.4, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, swiftmailer/swiftmailer@v6.0.2, ramsey/uuid@3.7.3, psr/simple-cache@1.0.0, psr/container@1.0.0, symfony/translation@v3.4.4, nesbot/carbon@1.22.1, mtdowling/cron-expression@v1.2.1, monolog/monolog@1.23.0, league/flysystem@1.0.42, erusev/parsedown@1.6.4, doctrine/inflector@v1.3.0, laravel/framework@v5.5.33, davejamesmiller/laravel-breadcrumbs@4.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, fideloper/proxy@3.3.4, laravelcollective/html@v5.5.1, league/commonmark@0.17.0, league/csv@9.1.1, paragonie/constant_time_encoding@v2.2.1, symfony/polyfill-util@v1.6.0, symfony/polyfill-php56@v1.6.0, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, twig/twig@v1.35.0, rcrowe/twigbridge@v0.9.5, rmccue/requests@v1.7.0, watson/validating@3.1.2,  |

**Comment by jinformatique** [comment]
I compared them, and they are identical. I changed page and came back on budget page to see that my amounts were reseted again at the previous entry. I checked the debug and it's the same.

**Comment by JC5** [comment]
I will do some debugging using sqlite, see if I can find what is going on.

**Comment by JC5** [comment]
Oh, and could you share the content of the *second* box? Not the first one, but the second one with the log entries. 

You can also share it over email (thegrumpydictator@gmail.com) or share the latest log file whole. I think something is going wrong but I can't put my finger on it.

**Comment by jinformatique** [comment]
Hello James, on version 4.7.0 I still cannot change a budget that was already set. Is it still linked to sqlite?

**Comment by JC5** [comment]
I believe this is fixed for the next release but I will double check this and get back to you this evening.

**Comment by JC5** [comment]
I have verified that this will work as expected in the next release.
