### ISSUE TITLE
Basic API functionality

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1112]
Let's do this MVP style.

First things first. 

- Think of a permission scheme.
- OAuth2 access screen
- OAuth2 tokens in profile
- Add/remove/refresh access tokens etc.

Then, first feature:

API REST endpoint for profile (read-only).

**Comment by Findus23** [comment]
In my opinion the most important endpoint for an REST API is for adding a new transaction as that's at least what I do most of the time on my phone and a native user interface that starts quickly when one just bought something in a shop would be really nice.

**Comment by 8bitgentleman** [comment]
I agree with @Findus23, entering transactions via REST API would be very useful. I think it would also be nice to be able to grab the current balance from an asset account as well as its last few transactions.

**Comment by JC5** [comment]
Yes. Currently I'm working on:

- Basic info page (/about and /about/user).
- Full CRUD for bills (create, read, update, delete). Mostly because bills are fairly "independent" from the rest of the system.
- Full CRUD for accounts (slightly more complex and it's the first actual object in the database).
- Full CRUD for users (fairly easy, only accessible for admin users)
- Full CRUD for transactions (annoyingly complex)

So to answer your question: YES this will be possible in the first API release.

**Comment by Findus23** [comment]
Now we just need a volunteer, who creates a great android app for quickly registering transactions on the go 😄
