### ISSUE TITLE
[Question] IBAN and BIC fields

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#1115]
I am running Firefly III version 4.6.13 

#### Description of my issue:
Hello.

I have checked that the IBAN and BIC fields have restrictions on the data format that they can receive.

In my country, these datas are not relevant. Is it possible to disable this check of the format of the accepted number, so that I can put other datas in these fields?

**Comment by JC5** [comment]
Sorry, I can't. You can use the account number field and the notes, both are restriction-free.
