### ISSUE TITLE
Can't translate some strings (part 2)

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1116]
I found a few more strings that can not be translated.

In the pop-up window with tips, I can not translate text on the navigation buttons.

![tips-window](https://user-images.githubusercontent.com/520760/34758327-89288926-f5e7-11e7-9c5f-97d1d28d015d.jpg)

In the help window it is not possible to translate the title ("Help for this page") - this line is missing in the files for translation.

![help-window](https://user-images.githubusercontent.com/520760/34758326-89082b9a-f5e7-11e7-9e65-8493b2bf9713.jpg)

**Comment by JC5** [comment]
I've added the requested strings to Crowdin. I don't think you can see them yet in your own installation, but they will be visible in the next release.

**Comment by Nik-vr** [comment]
OK! Thank!
