### ISSUE TITLE
New opportunities for piggy bank's

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1117]
1. Add an image to the piggy bank. When a person sees his goal, this is a good incentive. Now the piggy bank on the main page is invisible, just one more block with information in the corner.

![firefly-piggi](https://user-images.githubusercontent.com/520760/34760355-9abd0992-f5f0-11e7-8340-dfe643ca20fc.jpg)

![my-old-soft-piggi](https://user-images.githubusercontent.com/520760/34760356-9adc3812-f5f0-11e7-9436-d12b111331aa.jpg)

2. I would like to be able to link several accounts to one piggy bank. For example, my wife and I have separate savings accounts. But we are copying for a vacation together. It would be convenient to have one piggy bank and save money in it from our two accounts.

**Comment by JC5** [comment]
Haha that looks very nice but is way too crowded for my tastes. Sorry. You can add a picture on the piggy bank page itself, using this markdown code:

```
![alt text](image-url)
```

As for linking several accounts, this would require a huge database overhaul, so I am afraid it is not possible.

**Comment by Nik-vr** [comment]
I already tried to add an image this way. But the main page does not display the contents of the "Notes" field at all.

Here is the page with the piggy bank:

![create-piggy](https://user-images.githubusercontent.com/520760/34762064-694577f8-f5f7-11e7-96ba-eafdb91aad29.jpg)

But the main page with the same piggy bank:

![firefly-piggi](https://user-images.githubusercontent.com/520760/34760355-9abd0992-f5f0-11e7-8340-dfe643ca20fc.jpg)

**Comment by JC5** [comment]
I know, I'm not going to add them there. Like I said, it would be way too crowded. Sorry.

**Comment by Nik-vr** [comment]
Very sorry.
