### ISSUE TITLE
Incomplete translation of validation notices.

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1118]
When validating the warning forms, the field names are in English. Although the signatures to these fields have been translated. As a result, the warning turns out to be incomprehensible, because field names do not match.

![validation](https://user-images.githubusercontent.com/520760/34766385-4325180e-f605-11e7-9260-a0afa58810ad.jpg)

Perhaps, when forming messages, use not the internal names of fields, but the translated signatures to them?

**Comment by JC5** [comment]
Turns out I can! I've uploaded new strings.

Please note that the word "add_tag" and other values in the error below can not be translated.

![screen shot 2018-01-10 at 12 25 16](https://user-images.githubusercontent.com/5889984/34770501-af22ffd4-f601-11e7-84d7-b81573fc35b3.png)

**Comment by Nik-vr** [comment]
Excellent! I will translate a new line. And it is impossible to substitute not new lines, but existing signatures for fields? So there will be fewer lines for translation and fewer possible errors.

**Comment by JC5** [comment]
Unfortunately, Crowdin does not allow it. There are quite a few lines which are "double" and you have to translate them two or three times. It cannot be helped.

**Comment by Nik-vr** [comment]
Ok, no problem!
