### ISSUE TITLE
Changing data of initial balance

### ISSUE THREAD

**Issue by wprauchholz** [firefly-iii/firefly-iii#1119]
I am running Firefly III version x4.6.12

#### Description of my issue:
I entered a wrong initial date on the account (30.12.2017 insted of 30.12.2018). How can I change it?

#### Steps to reproduce 

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by Torpis** [comment]
Accounts > Asset Accounts > Edit your main account.

Amend the value/date there.

**Comment by JC5** [comment]
Thats it! :+1:
