### ISSUE TITLE
Rules/Bills not auto-matching anymore

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1121]
I am running Firefly III version 4.6.13 (master) 

#### Description of my issue:

I moved from FF 4.6.13 develop to master. Fresh install, changed key and DB-details after install. Everything works perfectly. I noticed that some of the imports were not complete (app was broken a few weeks ago), so I decided to delete all transactions starting 2017-12-01 and re-import them. The import showed no relevant errors, but now, my rules do not trigger, and because of that, the bills will not match.

This is one of my config files:

```
{
  "initial-config-complete": false,
    "has-headers": true,
    "date-format": "Y\/m\/d",
    "delimiter": ";",
    "import-account": 2,
    "specifics": [],
    "column-count": 7,
    "column-roles": [
      "date-transaction",
      "account-iban",
      "opposing-iban",
      "amount",
      "currency-code",
      "description",
      "sepa-db"
    ],
    "column-do-mapping": [
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ],
    "column-roles-complete": false,
    "column-mapping-config": {
      "1": {
        "[redacted]": 2
      },
      "2": {
        "[redacted]": 4,
	"[redacted]": 3,
	"[redacted]": 2,
	"[redacted]": 1
      },
      "4": {
	"EUR": 1
      }
    },
    "column-mapping-complete": false,
    "apply_rules": true,
    "match_bills": true
}
```

#### Steps to reproduce 

cannot test on demo site

#### Other important details (log files, system info):

Debug information generated at 2018-01-10 20:14:43 UTC for Firefly III version **4.6.13**.

| Variable | Content |
| --- | --- |
| FF version | 4.6.13 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | warning, daily |
| PHP version | 7.1.8-1 |
| Display errors | Off |
| Error reporting | ALL errors |
| Host | Linux budget 4.9.41+ # 1023 Tue Aug 8 15:47:12 BST 2017 armv6l |
| Interface | apache2handler |
| UserID | 1 |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, vlucas/phpdotenv@v2.4.0, symfony/css-selector@v3.4.3, tijsverkoyen/css-to-inline-styles@2.2.0, symfony/polyfill-mbstring@v1.6.0, symfony/var-dumper@v3.4.3, symfony/routing@v3.4.3, symfony/process@v3.4.3, paragonie/random_compat@v2.0.11, symfony/polyfill-php70@v1.6.0, symfony/http-foundation@v3.4.3, symfony/event-dispatcher@v4.0.3, psr/log@1.0.2, symfony/debug@v3.4.3, symfony/http-kernel@v3.4.3, symfony/finder@v3.4.3, symfony/console@v3.4.3, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, swiftmailer/swiftmailer@v6.0.2, ramsey/uuid@3.7.1, psr/simple-cache@1.0.0, psr/container@1.0.0, symfony/translation@v3.4.3, nesbot/carbon@1.22.1, mtdowling/cron-expression@v1.2.1, monolog/monolog@1.23.0, league/flysystem@1.0.41, erusev/parsedown@1.6.4, doctrine/inflector@v1.2.0, laravel/framework@v5.5.28, davejamesmiller/laravel-breadcrumbs@4.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, fideloper/proxy@3.3.4, laravelcollective/html@v5.5.1, league/commonmark@0.17.0, league/csv@9.1.1, paragonie/constant_time_encoding@v2.2.0, symfony/polyfill-util@v1.6.0, symfony/polyfill-php56@v1.6.0, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, twig/twig@v1.35.0, rcrowe/twigbridge@v0.9.5, rmccue/requests@v1.7.0, watson/validating@3.1.2,  |

**Comment by JC5** [comment]
Try changing the underscore in match_bills and apply_rules to a dash (-). That should fix it. I have changed this but forgot to build in a check! Sorry about that.

**Comment by gavu** [comment]
I'll give it a try, thanks!

**Comment by gavu** [comment]
As always, the fix worked. Thanks again!

**Comment by JC5** [comment]
:+1:
