### ISSUE TITLE
The chart of accounts on the main page is empty

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1122]
I am running Firefly III version 4.6.13 

I've been contributing all my expenses and incomes in FireFly for a week already. I specified the starot balance for all accounts. But the chart of accounts on the main page is still empty. In this case, the transactions in the block on the right are displayed correctly, the budget diagrams are also correct.

![assets](https://user-images.githubusercontent.com/520760/34810059-39db971e-f6aa-11e7-8e90-4a5df71835c5.jpg)

Is this a bug, or am I doing something wrong?

**Comment by JC5** [comment]
It's a bug. See also https://github.com/firefly-iii/firefly-iii/issues/1088

I am not yet sure of the cause. If you would execute the query in the other issue and share with me the results, I would be very grateful. I shall do some investigating later today.

**Comment by Nik-vr** [comment]
I use SQLite database. How do I make this query?
