### ISSUE TITLE
Bulk edit buttons in search results missing

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1124]
I am running Firefly III version 4.6.13

#### Description of my issue:

I just noticed I can no longer edit transactions from the search results. You can select them but the buttons are missing. 

![2018-01-11 14_03_44-search results search firefly iii](https://user-images.githubusercontent.com/3742238/34826891-a0a1588e-f6d8-11e7-871c-1679fab832dc.png)

Debug information generated at 2018-01-11 13:07:09 UTC for Firefly III version **4.6.13**.

| Variable | Content |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0 |

**Comment by JC5** [comment]
Will be back in the next release :+1:

**Comment by gavu** [comment]
Great! Thanks for the quick fix!
