### ISSUE TITLE
User Administration: "Has 2FA" flag is wrong

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1125]
I am running Firefly III version 4.6.13

#### Description of my issue:

My account shows as having 2FA inactive, but I enabled it _weeks_ ago, still use it 
![2018-01-11 14_34_20-user administration administration firefly iii](https://user-images.githubusercontent.com/3742238/34828156-e98d2d08-f6dc-11e7-8bf2-23482befc09d.png)

#### Steps to reproduce 

cannot reproduce on demo site - no access

On a side note, what is the "Block code" column?

**Comment by Torpis** [comment]
"Block Code" shows if like the person has changed their email and then hasn't verified it I believe. I had the same bug with Has 2FA, I disabled then renenabled and it corrected it.

**Comment by JC5** [comment]
For example yes. There used to be more codes but they are mostly obsolete. 

I will check the code for the 2FA thing.

**Comment by JC5** [comment]
Fixed!
