### ISSUE TITLE
Bills: "&amp;" shown instead of "&" in title

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1126]
I am running Firefly III version 4.6.13

#### Description of my issue:

* The bill name (next to the "Bills" page title) and the breadcrumb element on the `bills/show/*` pages
* The breadcrumb element on the `/bills/edit/*` pages

**Comment by JC5** [comment]
I fixed that one, plus all the others. Piggy banks, categories, etc. Thanks for notifying me!

**Comment by gavu** [comment]
Any time! Thanks for fixing it this fast! I think you got the all by the looks of the breadcrumbs commit :)
