### ISSUE TITLE
"Report" email after import

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1128]
I am running Firefly III version 4.6.13

#### Description of my issue:

Is there any way you would consider adding an email "notification" for those users using automated imports? I know you want to have users as active as possible, to be aware of their financial status, that's why we, the ones importing automatically, are losing focus of what was imported and when. 

A simple email containing a list of transaction details (description, amount, date, account) would suffice. You could also add this feature as an option, maybe not everyone wants to send unencrypted financial information over the web via email.

... just one of those shower-ideas

**Comment by JC5** [comment]
Haha, very nicely put :wink:.

I can't do an email report yet. First, I'd like to improve error/feedback methods for import jobs, both on the command line and in the interface. Then it would become possible to use that info in a notification, an email, etc.

**Comment by JC5** [comment]
I'll put it on "one day" for now but I expect it to move up fairly soon.

**Comment by JC5** [comment]
OK fairly soon is six months later but for the recurring transactions feature I am also writing an email feature. It would trigger after running the recurring routine and send a list of transactions to you.

I'll keep you posted when this happens, because that would also become an option for the import routine.

**Comment by gavu** [comment]
It’s never too late. Thanks for remembering!

Just so I understand, by recurring transactions you mean bills and? Or anything matched by rules (which now include bills)?

**Comment by JC5** [comment]
https://demo.firefly-iii.org/recurring

I’ll explain about the email when I get home.

**Comment by JC5** [comment]
So Firefly III can generate periodic, recurring transactions if you set up the cron job. When a transaction (or more) are created, an email is sent saying something like "FF3 created X transactions, here is a list".

That email could be re-used for imports.

**Comment by JC5** [comment]
This will be implemented in the next release :+1:

If you import transactions, and have set up email, you will get an email from Firefly III detailing which transactions were created.

**Comment by gavu** [comment]
Awesome news! Is it Christmas already?!

Thank you for your work!

**Comment by JC5** [comment]
I'm closing this since it's fixed. Look for this feature in the next release, and let me know if you encounter any problems!
