### ISSUE TITLE
Search: Possible cache issue

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1129]
I am running Firefly III version 4.6.13 stable

#### Description of my issue:

I used the search function to look up "duplicates" to set up a rule. I found 8 transactions that matched. I set up the rule, it ran, it processed them accordingly, but when searching again, to see if everything was matched, nothing changed. Clicking on the transaction, to check the details, everything was changed by the rule (as it should)

#### Steps to reproduce 

1. Go to search, search for "Power"
2. Open a new tab (**important**) and...
3. Set up a rule to set the following (description, source account, destination account, 2 tags, category - see https://demo.firefly-iii.org/transactions/show/485 as an example)
4. Run the rule
5. Go to the search tab, search again or refresh the page (the results did not change)

I went to another computer (to open this issue), **the search is correct**
I went back to the previous computer, **the issue persists**

I _did_ reproduce it on the demo site

#### Other important details (log files, system info):

debug not possible on demo site and no access to logs

**Comment by JC5** [comment]
That could be a cache issue indeed.

Is the search correct on one computer, but incorrect on another computer? Did I read that right?

**Comment by gavu** [comment]
You read it right, but, I used this before, it did not happen, also, why would my browser cache the contents of a table, I mean, I understand div positions, images, etc. but content...

**Comment by JC5** [comment]
I've been playing around with the cache (related to a Sandstorm.io) issue and the cache will clear out sooner after rules have been applied. I hope that will fix it.
