### ISSUE TITLE
Not a valid IBAN number

### ISSUE THREAD

**Issue by dp87** [firefly-iii/firefly-iii#1131]
I am running Firefly III version 4.6.10

#### Description of my issue:

If you add a new asset account and enter an IBAN number with spaces between the IBAN fields, FF tells you that this is not a valid IBAN. This is not technically correct, but in any case I think we could just strip any white space in the number if we notice any, without having the user do it.

#### Steps to reproduce 

1. Create a new asset account
2. Enter an IBAN number with spaces in it
3. Click on Store new asset account

This will display the error message and, until you remove the spaces, you won't be able to create the new asset account.

**Comment by JC5** [comment]
That's  good idea!

**Comment by pkoziol** [comment]
Hmm... all my accounts have IBAN with spaces (in form PLkk bbbs sssx cccc cccc cccc cccc which is 10x cleaner than without spaces) and I've never encountered problems. I've been using it since 4.6.4. Currently on 4.6.13.

Am I right that this fix changes only validation and IBAN still will be saved with spaces?

**Comment by JC5** [comment]
In the validation routine, normal spaces are being quietly replaced, but if users use weird spaces or tabs the validation will fail. Now, those will be filtered away before the validation runs.

As you can see in [the commit](https://github.com/firefly-iii/firefly-iii/commit/79d6055a78ff0d8ca3ff0385e13fd190d4fdfd90) unicode has a lot of weird space characters and this isn't even half of them.

**Comment by gavu** [comment]
Just a suggestion, you could remove all spaces in the DB but _display_ the IBAN with spaces using JS (like a phone number mask)

**Comment by dp87** [comment]
@JC5 Thanks for taking care of this! I thought about opening a pull request but before I could even start looking into it, you had solved this already :P

@gavu That's also a good idea, I agree it would be much more legible this way. How often do you even need to look at the IBAN number in a software like FFIII though? Just curious, so we can prioritize things correctly.
