### ISSUE TITLE
Markdown font-size bigger than FF

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1132]
I am running Firefly III version 4.6.13

#### Description of my issue:

During my early spring cleaning, I added notes to bills and noticed the following inconsistencies. (I used `blockquote` to add contract cancellation confirmations

* `h1`
  * Firefly III: `font-size: 24px`
  * Markdown: `font-size: 36px`
* `blockquote`
  * Firefly III: _not used_
  * Markdown: `font-size: 17.5px`
* `body` is consistent
  * Firefly III: `font-size: 14px`
  * Markdown: `font-size: 14px`

**Comment by JC5** [comment]
Mmm, nice. I'll check what's causing it.
