### ISSUE TITLE
is there a way to change the date format?

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#1133]
I am running Firefly III version 4.6.13
Fedora 27
4.14.11-300.fc27.x86_64
Server version: Apache/2.4.29 (Fedora)
Server built: Oct 25 2017 12:34:45
mysql Ver 15.1 Distrib 10.2.9-MariaDB, for Linux (x86_64) using readline 5.1

#### Description of my issue:
Question: Is there a way to change date formate from MM/DD/YYYY to DD/MM/YYYY or YYYY/MM/DD?

**Comment by pkoziol** [comment]
You have to change few lines in file [resources/lang/en_US/config.php](https://github.com/firefly-iii/firefly-iii/blob/4.6.13/resources/lang/en_US/config.php#L25) or change language (which should have appropriate date format for your country) in Options > Preferences.

You can find available placeholders in [PHP's strftime documentation](http://php.net/manual/en/function.strftime.php).

**Comment by JC5** [comment]
I’m not really sure which date you mean exactly. There are no fields in Firefly III that display “MM/DD/YYYY” as you describe, as far as I know. 

The closest to that format is defined by your locale. When you use English (US) the dates will be formatted “January 12, 2018” which is in line with that language. Other languages have their own particular formatting. 

If you’re looking for any particular format, I can only suggest you use Firefly III in your own language. Or if that language is not available, help me translate :wink:

**Comment by lverissimo** [comment]
@JC5 
Lets do it! I accept the challenge, if you don't have anyone yet working on translating to portuguese (Portugal), I will give it a try. 

Regarding the date format, I must have something screwed up on my http server, as I change the language, for instance, from english to french and the date picker fields, like for instance, "Fiscal year start date", still shows mm/dd/yyyy.

**Comment by pkoziol** [comment]
This probably depends od Firefox (or system?) locale as I see 17.01.2018 while using polish Firefox and Windows:
![image](https://user-images.githubusercontent.com/3846677/35042158-b7be60da-fb87-11e7-940b-1b7a18d0715d.png)

**Comment by lverissimo** [comment]
JC5, 
I finnally found how to fix this! Date format is dependent on:  1) locale date format of the OS, 2) the language settings of the operating system and 3) language settings of the browser.  In my case the locale date format was already dd.mm.yyyy, so I had to change the language settings of both the browser and OS fronm English (US) to English(UK) to get it to work!  It has nothing to do with your code, or settings!
Regards,
Luis verissimo

**Comment by JC5** [comment]
:+1: Thanks for letting me know!
