### ISSUE TITLE
Forecast reports?

### ISSUE THREAD

**Issue by juan-manuel-alberro** [firefly-iii/firefly-iii#1135]
Hello,

First at all, thanks for this awesome product!

I've a question regarding the future of the app, is any [forecast report](https://en.wikipedia.org/wiki/Financial_forecast) in the roadmap? 
Basically a forecast report is shows you the evolution of your money in the future based on your current and scheduled transactions.
I think it will be pretty cool feature and almost all the financial management software includes that kind of reports.

Thanks and keep up the good work ❤️

**Comment by JC5** [comment]
Thanks I appreciate the compliments!

It is on the roadmap, but very far away. Firefly III has very limited capabilities in regards to recurring transactions and income (not entirely by accident) and as such does not have the data to do much prediction.

Financial forecasts are pretty difficult. They start simple enough, meaning you might as well start using Excel. But when you start including all expenses it generally turns messy. Previous versions of Firefly III did feature limited forecasts but they were generally off by miles.

Having said that: yes, it's on the road map.

**Comment by pikaille** [comment]
I'd like to see that feature as well!

**Comment by villspor** [comment]
*upvote* this is very important to me. great job! thanks :)

**Comment by anandasudarshan** [comment]
+1

**Comment by JC5** [comment]
There is no need to leave a vote. Thank you.

**Comment by JC5** [comment]
Forecast reports will not be a feature of Firefly III. With the API and the unencrypted database however, it should not be difficult to write a tool that can do this based on Firefly III data.
