### ISSUE TITLE
Amount in "Net worth" block does not include one deposit transactions

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1136]
I am running Firefly III version 4.6.13

At some point, the amount in the "Net worth" block became less real than exactly the amount of one transaction of income. I deliberately manually counted the amounts on all accounts and found the amount of the discrepancy.
The sum of the sums for all accounts, calculated manually, does not coincide with the amount in the block "Net worth".

How can I correct this discrepancy?

**Comment by JC5** [comment]
Browse to `/flush` to clear the cache, just to be sure.

Did you recently delete transactions? Is the amount meaningful to you? Is it perhaps the amount of a recent transaction?

**Comment by Nik-vr** [comment]
I've cleared the cache, and now everything is displayed correctly.

**Comment by JC5** [comment]
The next version of Firefly III will have some cache changes, so this should not happen anymore.

**Comment by Nik-vr** [comment]
ok. Thank!
