### ISSUE TITLE
[Feature Request] "Create a new split"

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1137]
Now, if I need to create a split-withdrawal, I first create a normal withdrawal, I fill in all the fields, and then duplicate the same data for the split.
Perhaps it would be more convenient to fill in the split form immediately.

**Comment by JC5** [comment]
Yes, this is on the list:

https://github.com/firefly-iii/firefly-iii/issues/998

**Comment by Nik-vr** [comment]
Sorry, did not notice this issue.
