### ISSUE TITLE
404 error on Expense/revenue account report

### ISSUE THREAD

**Issue by trinhit** [firefly-iii/firefly-iii#1138]
I am running Firefly III version 4.6.13

#### Description of my issue:

Expense/revenue account report gives 404 error

#### Steps to reproduce 

1) Go to Reports.
2) Select Expense/revenue account report
3) Select any account(s)
4) Click Submit
5) 404 error

This also happens on demo site.

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
I’m not able to reproduce it. Did you select any accounts below the date selection?

[This is the report you’re looking for](https://demo.firefly-iii.org/reports/account/1,32,33,2,3/11/20180101/20180131) although it’s kind of empty.

**Comment by trinhit** [comment]
No I didn't. That's why! Thank you!
