### ISSUE TITLE
deposit less cash - combination Deposit, Withdrawl

### ISSUE THREAD

**Issue by dckc** [firefly-iii/firefly-iii#1139]
Suppose I get a check for $150 and I want to deposit $100 and take the rest as cash -- and I consider cash an expense. I consider it spent already.

I don't see how to include expense accounts in a deposit.

I am running Firefly III version 4.6.13 Firefly III (in standstorm)

**Comment by dckc** [comment]
p.s. I ran into this when trying to figure out how to migrate a couple week's worth of GnuCash data.

**Comment by JC5** [comment]
I think you can go two ways about this:

* Deposit 100,- in your account and put "150,- check" in the description.
* Deposit 150,- in your account, same as above, and create a cash withdrawal for 50,-. To create a cash withdrawal just make a normal withdrawal but leave the expense account empty.

There's no option to combine the two I'm afraid.

**Comment by dckc** [comment]
Empty? How does that work w.r.t. double-entry accounting?

I'm used to the usual income - expenses = assets - liabilities. Firefly sure is cool, but I'm not sure it's a good fit for me. We'll see.

p.s. My hacking these days is mostly in the area of syncing: https://bitbucket.org/DanC/finquick / https://github.com/dckc/finquick . In fact, I found firefly yesterday while working on the plaid API.

I do most of the rest with gnucash, though I've been wishing for something web based at least as far back as 2006 (https://bitbucket.org/DanC/quacken -> http://www.madmode.com/2006/breadcrumbs_0096.html )

**Comment by JC5** [comment]
Firefly III has a semi-hidden "cash account" that will be used when you leave the expense account empty.

The Plaid API is the next step for me :+1: Thanks for your feedback!
