### ISSUE TITLE
Browser auto complete is shown over firefly auto complete inputs

### ISSUE THREAD

**Issue by ErikFontanel** [firefly-iii/firefly-iii#1141]
I am running Firefly III version 4.6.13

#### Description of my issue:
At least in Chrome the native auto complete overlays the JS autocomplete box.

![image](https://user-images.githubusercontent.com/917819/35216911-9597897e-ff69-11e7-9385-6ed74d485213.png)

Adding the `autocomplete="off"` attribute to the `input` should disable the native auto complete.

#### Steps to reproduce 

1. Add a new item (rule, budget, tag, category, whatever)
2. Enter something as a value
3. Save
4. Add a new item (rule, budget, tag, category, whatever)
5. Start typing a value with the same first letter as in step 2.

This also happens on the demo site.

**Comment by JC5** [comment]
Thanks for notifying me, I must have forgotten it! I shall fix it ASAP :D
