### ISSUE TITLE
Allow more attachment formats and view attachments directly on browsers

### ISSUE THREAD

**Issue by trinhit** [firefly-iii/firefly-iii#1146]
### 1) Allow more attachment formats
Office formats such as doc, docx, xls, xlsx, etc. are preferred.

### 2) View images and PDF files:
As far as I know, modern browsers have built-in support for viewing images and PDF files.
Suggestions: Make a view icon beside attachment links, allowing render and display images and PDF directly on browsers.

### 3) View other file types:
(If item no.1 is rejected, then you may skip this.)

Currently browsers do not have built-in support for rendering those file types directly. We can use Google Docs Viewer. For example: https://docs.google.com/gview?url=http://ieee802.org/secmail/docIZSEwEqHFr.doc, or https://docs.google.com/gview?url=http://firefly.local/public/attachments/download/1

Since Google Docs Viewer requires public accessible links, we want to tweak the script that handles /public/attachments/download/1 so that it allows public access. Here are my idea:

1. When user clicks on View icon, generate one-time public token for the clicked attachment. Optional: set token expiration.
2. Modify some script so that it take one more parameter, for example: http://firefly.local/public/attachments/download/1/{onetimePublicToken}. If token is valid, allow public access (i.e. without login).
3. Redirect user to https://docs.google.com/gview?url=http://firefly.local/public/attachments/download/1/{onetimePublicToken} to view attachment directly on browsers.
4. Once http://firefly.local/public/attachments/download/1/{onetimePublicToken} is accessed (by Google or whoever), mark it as expired.

Problem: Although I think my idea reduces the risk of data leak to minimum, exposing attachments to public - Google in this case - has security concerns. Who knows Google will steal the attachments or not? So we can make this feature configurable. User has the choice of using it or not. For me, I don't mind exposing my attachments to Google.

P/S: Google Docs Viewer's supported file formats can be found here: https://www.geek.com/news/google-docs-viewer-can-now-open-12-more-file-formats-1316411/

Thanks

**Comment by JC5** [comment]
Hi! Thanks for your feedback!

For now, you can extend the list of allowed mime types by editing [this line](https://github.com/firefly-iii/firefly-iii/blob/master/config/firefly.php#L38) in `config/firefly.php`. I shall make a note to extend the list and include various MS Office related mime types. These will be included with the next release.

A "view"-icon is a good idea next to the download button. It might replace the download button completely: when you're viewing the document it is a small step to download the file yourself.

The process for viewing attachments is very nice, but it's not something I am going to implement. I have a few reasons: First, the main goal of attachments in Firefly III is availability: a bill, a contract, a note should be there with the transaction. Having to view it is only secondary. I feel that downloading / viewing in browser is the correct level of functionality.

Second, it is a potential security gap, uploading attachments to Google and potentially exposing them to the world. If I were to make any mistake there, user's files would be available for everybody.

Third, most users use their Firefly III offline only. In Docker instances, Vagrant machines, etc. And these methods are getting more popular by the day, meaning less and less users have their Firefly III connected to the internet. Opening ports or exposing a server can be quite a difficult task.

I hope this answers your questions :)

**Comment by trinhit** [comment]
Thank you!
