### ISSUE TITLE
Display account's final amount at the end of current time period

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1150]
I am running Firefly III version 4.6.13

I always add some transaction in advance when a new time period (month) starts. These are recurring transaction of which I know the date at which they will be charged. Thereby, in the dashboard graph, I can see an estimation of how much money will be left on certain accounts at the end of the period. To me, this information is particularly useful for at least 1 of the 5 accounts that I display on the dashboard. 
Maybe this is a piece of information that could as well be displayed more prominently somwhere else. Because currently, I have to hover the graph and find the correct account in the tooltip.

While I was typing this, I found out that the 'Current balance' column on the accounts page seem to show exactly the value. I am wishing for. 'Current balance' is a little misleading here. Maybe there should be a column 'Current balance' and 'Final balance' (or some better name), where 'Current balance' shows the balance for the current date (alwas for today) and 'Final balance' shows the value for the current period.

**Comment by JC5** [comment]
Indeed, the "current" balance always shows the balance at the end of the given period. It's not really "current". I understand that it can be confusing, but it is correct for almost all of the times people view that page to check their balances.

I understand your wish, given the way you use Firefly III. Nevertheless, I am leaving this particular view as it is. The added complexity supports a very small use case.

Firefly III could use a method of planning (recurring) transactions and it is already on the list somewhere.
