### ISSUE TITLE
Build package for Yunohost

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1151]
See title.

**Comment by Limezy** [comment]
Would love to have Firefly on my Yunohost account !
For the moment I use it on a separate server.
Maybe I can help on this matter ?

**Comment by JC5** [comment]
That would be great! I have no plans to build this for the next release but in May I could get started. By that time I could use some testers.

**Comment by Limezy** [comment]
Perfect. It shouldn't be difficult, the only issue I can see is to have PHP5.6 and PHP7.1 working together.

**Comment by JC5** [comment]
Yunohost is available!

https://github.com/YunoHost-Apps/Firefly-III_ynh
