### ISSUE TITLE
The "today" label on the dashboard gets hidden towards the end of the month

### ISSUE THREAD

**Issue by ndandanov** [firefly-iii/firefly-iii#1155]
Hi,

I am running Firefly III version 4.6.12 and found a cosmetic bug.

#### Description of my issue:
The `today` label on the dashboard gets hidden towards the end of the month.
Please compare these two screenshots:

**Correctly displayed**:
![Correct](https://firefly-iii.org/static/screenshots/4.7.0/index.png)

**Incorrectly displayed** (please look at the `t` letter on the right):
![Incorrect](https://user-images.githubusercontent.com/17270267/35621325-a31edd7a-068c-11e8-8e82-8d1526ce2ba6.png)

#### Steps to reproduce 

Install the latest stable version of Firefly III and open the dashboard.
The problem also exists on the demo site.

**Comment by JC5** [comment]
Yes, I saw it myself earlier. Thanks for notifying me!

**Comment by JC5** [comment]
I've pushed a fix. The next release of Firefly III will have the next on the left at the end of the month.

**Comment by ndandanov** [comment]
Thank you for your assistance, James!

**Comment by JC5** [comment]
Closed to clear the list.
