### ISSUE TITLE
[Feature Request] Hide "zero" accounts

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1161]
A small suggestion. Sometimes it happens that some account is not used for some time. But the block for it is displayed on the main page, and for it there is a graph on the general diagram.

I propose to hide the account from the main page and the chart if two conditions are met: the amount on the account is zero, in the current period (month) there were no transactions on the account.
Yes, you can hide the account manually in the settings, and then show it again. But this is inconvenient.

![zero](https://user-images.githubusercontent.com/520760/35719135-f93200bc-07f8-11e8-8516-95bf3569c14a.jpg)

**Comment by JC5** [comment]
The idea is nice, and it would certainly declutter the chart.

It would however, introduce a new unwritten rule about when accounts are visible. Apart from the existing options. This kind of magic is something I want to avoid.

I am afraid you must suffer through the inconvenience ;).

**Comment by Nik-vr** [comment]
You can make this option optional. Who needs it - will include. By default - turn off.

**Comment by JC5** [comment]
Sorry, I'm not going to build this. Other stuff has priority and I don't feel like adding another option.

**Comment by Tarkken** [comment]
Why not instead of applying this to a specific rule (the account having zero value) make it so that you can set an account as being hidden on the graph? I bring this up as conversely to when an account is zero is when an account is so large that it skews the visibility of the graph.

**Comment by JC5** [comment]
You can hide an account from the chart already, it is in the preferences at `/preferences`. Is that what you meant?
