### ISSUE TITLE
Feature requests on bills : manual association + no repeating

### ISSUE THREAD

**Issue by Ziwobukaj** [firefly-iii/firefly-iii#1162]
I am running Firefly III version 4.7.0 

Suggestion of enhancements on the bill module : 
* Enable/Disable Automatch is good. Better would be that we can associate manually a line with a bill. At this moment, this means that the association between a bill and a line would be kept, no matter that the bill settings change or not.
* Now we can choose the repeating frequency from "weekly" to "annually". What about a "none" choice ? (E.g : I have 2 times the same bill to pay this month. And I have another bill to pay monthly during 6 months)

Thanks in advance

**Comment by JC5** [comment]
Hi! Thanks for your suggestions. For the first, see #991. It's on the list!

As for the frequency, a "none"-frequency is possible. It would mean the bill is recognized and is active but will not count on the frontpage (box) or in reports when not recognized.

To "reset" transactions when you have changed a bill, use the "rescan" button.

**Comment by JC5** [comment]
(closed by accident)

**Comment by Ziwobukaj** [comment]
Thanks for your answer !

The problem with the "rescan" button is that this delete what doesn't correspond anymore to the criterias.
E.g : until last month, my phone bill was 0.99 € and from now jumps to 19.99 €.
And I can't put interval 0.99 - 19.99 as I have another phone bill from the same operator which value is 2.99 €

Another request : have the possibility to add **positive** amounts
E.g : I have monthly fee from my bank but because I'm good customer, they refund me part of it **on a separate line**

**Comment by JC5** [comment]
That's something else entirely. The bill must match all relevant lines, that's kind of the point. If you just want to group these transactions, I would suggest using a tag. But the rescan button will remove any transactions that no longer match.

If you have two bills from the same operator I suggest splitting them in two bills as well. For bills that vary wildly in the amount I have no solution: personally I have bills that range from 4,- to 40,-. It is tricky.

Incoming transactions (refunds) cannot be linked to bills, I'm afraid. Ultimately, the goal of bills is to make sure you remember what you still need to pay (on your index).

**Comment by Ziwobukaj** [comment]
Thanks for your answer.

I’m agree : bills feature is about to summarize what is to pay and when.
However, in the home screen for example, Firefly shows the total amount of bills, which is quite irrelevant because of the issue I expose now (inability to match bills with incomes / transfers) . Because of that I can’t get rid of my old Excel file :-(

**Comment by JC5** [comment]
I don't think I understand it. A bill is a recurring expense. Phone bill, rent, etc. So you give Firefly III some info about your bill and it will show up every period as "bills to pay".

A monthly bill shows up every month, a weekly bill will show up * 4 (assuming you view Firefly III per month) and yearly bills show up every year.

The fact that you *also* get income every month (a cashback, a refund) is irrelevant to this feature. The bill still needs to be paid.

**Comment by Ziwobukaj** [comment]
Imagine that every month I have this :
- bank fee : 40€
- refund on bank fee : 25€

I don’t know why my bank makes this instead of billing me 15€ but this is it’s way.

With firefly I can only put the first line to bill. This is nice for planning but irrelevant when it’s about to summarize the total amount I’ll have to pay this month.

What about considering that bills can be when you owe something or when somebody owes something to you ?
(In this way, monthly salary can be considered as well as bill)

**Comment by Ziwobukaj** [comment]
Hello, any answer to my question ?

**Comment by JC5** [comment]
In the future, I want to add something like you say, "incoming bills". It would be called something like recurring income or something, I am not sure yet. For now, i can't help you but future versions of Firefly III will support this :)
