### ISSUE TITLE
Category keeps auto-completing

### ISSUE THREAD

**Issue by kristophr** [firefly-iii/firefly-iii#1164]
I am running Firefly III version x.x.x 

#### Steps to reproduce 
Add a new withdrawl and put category in as "Software Subscription"
Add another withdrawl and put category as "Software" - it won't let you and keeps autofilling in to "Software Subscriptions"

Could not replicate on demo site.

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):
Version: 4.6.13
Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
Thanks for reporting! This is a known bug, that has been fixed in 4.7.0.

**Comment by kristophr** [comment]
dammit!  Sorry lol - I searched first to see if it was listed yet.  I'll upgrade to 4.7.  So sorry!

**Comment by JC5** [comment]
No problem! :D
