### ISSUE TITLE
Question regarding new vs old buttons

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1165]
I am running Firefly III version 4.7.0 

#### Description of my issue:

I just noticed you added new buttons, but the old ones are still available. Are you planning to remove those or will there be an option to enable/disable one of them?

**Comment by JC5** [comment]
Hey gavu!

I’m assuming you mean the (+) menu?

**Comment by JC5** [comment]
Sorry, submitted too soon. I intend to leave it, it’s not that much of a space eater.
