### ISSUE TITLE
Feature request: Keyboard shortcuts for common tasks.

### ISSUE THREAD

**Issue by dzaikos** [firefly-iii/firefly-iii#1166]
I would love to see some simple keyboard shortcuts to speed up common tasks. Namely new expense, deposit and transfer. Something like `Ctrl e` for expense `Ctrl d` deposit, etc.

**Comment by JC5** [comment]
Sorry, I'm not going to add those.

**Comment by Finkregh** [comment]
could you elaborate why? sort-of-blind entry would be a really cool feature
