### ISSUE TITLE
Isssue with Docker

### ISSUE THREAD

**Issue by monsieurpouet** [firefly-iii/firefly-iii#1170]
Hi ! 

I am running Firefly III version 4.7.0 

#### Description of my issue:
When I launch the first docker command, everything is Ok ! But !
If I launch this:
`docker exec -it <container> php artisan migrate --seed`

I've this error:
```
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select * from information_schema.tables where table_schema = CHANGEME and table_name = migrations)
In PDOConnection.php line 47:
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
In PDOConnection.php line 43:
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
In PDOConnection.php line 43:
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known
```

Perhaps, It's me ?

**Comment by JC5** [comment]
Hi there!

Which first docker command are you running _exactly_? There are several :).

From the error you get it seems you have only launched the Firefly III docker container, which does not include a database. So I think you may need to use the "docker compose" command, or prepare a database server beforehand.

**Comment by phosphotungstic** [comment]
Looks like you used the docker command provided from the [startup page](https://firefly-iii.readthedocs.io/en/latest/installation/docker.html#straight-from-docker-hub) but didn't change the environment variables in the command. 

If you want/have a db instance up and running (I use a mysql docker personally) I would change those values to be the same as in that container and link it in.

For example: 
- Create the volumes
```
docker volume create firefly_iii_export
docker volume create firefly_iii_upload
```

- Get the db up and running
```
docker run -d \
--name=DBHOSTNAME \
-e MYSQL_DATABASE=DBNAME \
-e MYSQL_USER=DBUSER \
-e MYSQL_PASSWORD=DBPASSWORD \
-e MYSQL_RANDOM_ROOT_PASSWORD=yes \
-p 3306:3306 \
mysql:latest
```

- Link and run firefly
```
docker run -d \
--link=DBHOSTNAME \
--name=NAMEOFYOURCONTAINER \
-v firefly_iii_export:/var/www/firefly-iii/storage/export \
-v firefly_iii_upload:/var/www/firefly-iii/storage/upload \
-p EXTERNAL_PORT:80 \
-e FF_APP_ENV=local \
-e FF_APP_KEY=S0m3R@nd0mString0f32Ch@rsEx@ct1y \
-e FF_DB_HOST=DBHOSTNAME \
-e FF_DB_NAME=DBNAME \
-e FF_DB_USER=DBUSER \
-e FF_DB_PASSWORD=DBPASSWORD \
jc5x/firefly-iii:latest
```
When I run these, it looks fine and the artisan commands work. Usually when you run docker commands, things that are fully capitalized should be looked at. Hope this helps!

**Comment by monsieurpouet** [comment]
@JC5 : Thanks for your answer.
I had try the docker-compose,, but I've an error with:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "firefly_iii_upload". Valid top-level sections for this Compose file are: services, secrets, version, networks, volumes, and extensions starting with "x-".
```
I guess, it's a problem of docker-compose version. I didn't succeed :/


@phosphotungstic ; Thanks for your demonstration :)It help me a lot !!
Okay for the database, but if I want use a database system hosted on my own server. I suppose the variable of FF_DB_HOST will be the IP of my server not that my docker ?
I thinked that the link option was depreceted at Docker ? :o My mistake ?

I've installed firefly with Docker ! Finally ! But I've an error about the Euro currency ^_^. But step by step.. It will be good !

**Comment by JC5** [comment]
I'm glad you have it running so far. I am assuming the error is that "the EUR currency is not present"?

Make sure you run the correct commands _after_ the docker compose command:

```
docker-compose exec firefly_iii_app php artisan migrate --seed
docker-compose exec firefly_iii_app php artisan firefly:upgrade-database
docker-compose exec firefly_iii_app php artisan firefly:verify
```

**Comment by monsieurpouet** [comment]
Thanks for your support !
The logs:

```
root@XX:~# docker exec -it 5db1feca12a9 php artisan migrate --seed
Nothing to migrate.
Seeding: AccountTypeSeeder
Seeding: TransactionCurrencySeeder
Seeding: TransactionTypeSeeder
Seeding: PermissionSeeder
Seeding: LinkTypeSeeder
root@XX:~# docker exec -it 5db1feca12a9 php artisan firefly:upgrade-database
Updating currency information..
Done updating currency information..
Firefly III database is up to date.
root@XX:~# docker exec -it 5db1feca12a9 php artisan firefly:verify
No orphaned transactions!
No orphaned journals!
All link types OK!
All access tokens OK!
Amount integrity OK!
root@XX:~#

Its works ! Weird stuff :p
```

**Comment by phosphotungstic** [comment]
Woops. Guess I missed out on that! You're right, link IS technically deprecated. Just put it on the same Docker container network then and then you should be able to use the container name I think!

**Comment by JC5** [comment]
:+1:
