### ISSUE TITLE
Importing semicolon delimited CSV is not mapped correctly 

### ISSUE THREAD

**Issue by mirkof** [firefly-iii/firefly-iii#1172]
I am running Firefly III version 4.7.0 

#### Description of my issue: 

I download my transactions from ABN AMRO as `xls`, and then save the file as `csv`. Microsoft automatically saves this as colon delimited.

When I try to import a that file, and select a delimiter as a semicolon (;), it's ignored, and behaves like it's a coma (,).

#### Steps to reproduce 

As stated above.

#### Other important details (log files, system info):

Debug information generated at 2018-02-10 16:28:55 UTC for Firefly III version **4.7.0**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.0 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, errorlog |
| PHP version | 7.2.1 |
| Display errors | Off |
| Error reporting | ALL errors |
| Host | Linux 8ba966fe-3780-4a7c-954e-f2b87028593e 4.4.0-1011-aws # 11-Ubuntu SMP Fri Jan 12 23:24:17 UTC 2018 x86_64 |
| Interface | fpm-fcgi |
| UserID | 1 |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, mbstring, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@4.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.6.4, fideloper/proxy@3.3.4, laravel/framework@v5.5.33, laravelcollective/html@v5.5.1, league/commonmark@0.17.0, league/csv@9.1.1, league/flysystem@1.0.42, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.22.1, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/log@1.0.2, psr/simple-cache@1.0.0, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.5, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v3.4.4, symfony/css-selector@v4.0.4, symfony/debug@v3.4.4, symfony/event-dispatcher@v4.0.4, symfony/finder@v3.4.4, symfony/http-foundation@v3.4.4, symfony/http-kernel@v3.4.4, symfony/polyfill-mbstring@v1.6.0, symfony/polyfill-php56@v1.6.0, symfony/polyfill-php70@v1.6.0, symfony/polyfill-util@v1.6.0, symfony/process@v3.4.4, symfony/routing@v3.4.4, symfony/translation@v3.4.4, symfony/var-dumper@v3.4.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.0, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2,  |

**Comment by JC5** [comment]
Thanks for reporting this!

I'm having some trouble reproducing your issue. I've used the very basic file + config attached, and my installation seems to separate these correctly. I've attached a screenshot.

![screen shot 2018-02-10 at 18 47 04](https://user-images.githubusercontent.com/5889984/36064914-cfd2ece0-0e92-11e8-8639-8bbcf464b607.png)

[very-basic-semi-colon.txt](https://github.com/firefly-iii/firefly-iii/files/1713633/very-basic-semi-colon.txt) + [very-basic-semi-colon-config.txt](https://github.com/firefly-iii/firefly-iii/files/1713635/very-basic-semi-colon-config.txt)

Could you share one or two lines from your CSV file? Feel free to censor them. I am curious to see if I am missing something.

**Comment by mirkof** [comment]
Here is the file I've used.

[CSV180210164054.txt](https://github.com/firefly-iii/firefly-iii/files/1714399/CSV180210164054.txt)

And the configuration

<img width="626" alt="screen shot 2018-02-11 at 14 37 58" src="https://user-images.githubusercontent.com/5755799/36073977-724768d8-0f39-11e8-9794-4064566a0631.png">

And this is what I get...

<img width="1137" alt="screen shot 2018-02-11 at 14 38 06" src="https://user-images.githubusercontent.com/5755799/36073976-723151b0-0f39-11e8-811d-df4e11cf7fba.png">

**Comment by JC5** [comment]
Strange. The problem was in an area where my test file should have bugged out as well. But never mind, you're on roll! Bug nr. 3 fixed.

**Comment by JC5** [comment]
Closed to clear the issue list.
