### ISSUE TITLE
Liability Accounts

### ISSUE THREAD

**Issue by jsykes** [firefly-iii/firefly-iii#1173]
I wanted to ask your input on how I’d track a liability account. I basically want to put in an account for a debt and allow myself to pay it down while also tracking the interest by adding them as transactions to it. A withdrawal would only let me go to a transfer or to an expense account. 

Can an expense account support a balance? Also for credit card accounts should I put in a negative balance showing what has been used up on it so far? Reconciling then would be useful

**Comment by JC5** [comment]
It's not yet possible although it is on the roadmap somewhere.

Although expense accounts do have a balance (see `/accounts/expense` most right column), I would suggest creating an asset account with an initial balance of minus the amount in question.

That way the asset account would slowly fill to zero when you move money to it. Once it is paid off you can disable the account removing it from most views while at the same time keeping all related data.

For credit cards I personally fill in a virtual balance of <credit card limit>.

Let me know if this works!

**Comment by jsykes** [comment]
That could work. What insight would I lose by not having an expense account for the loan and instead using an asset account? If I did transfers to it for principal payment and for fees and charges I could do withdrawals on it to an expense account. Then that sounds like it’d work. The expense account would reflect what I paid them and the loan amount asset account would reflect just a return of borrowed money. Would this confuse any charts?

Also, for credit cards.. virtual balances could work. Do you put a balance of available credit or use all virtual?

**Comment by JC5** [comment]
If you keep that specific asset account outside of any reports, transfers to that asset account would count as expenses correcting your reports. It would not allow you to easily see your total net worth but the income / expense records would be most accurate.

I see my sentence was missing a part. The virtual balance is positive: the limit of the credit card. Then, I create transactions as I would normally do.

**Comment by jsykes** [comment]
That makes sense.

I had one more question, If I had one bank account and wanted to designate a portion of it to be for bills but not get the balance confused thinking I had more available.. Would it be better to use a negative virtual balance against it or have another asset account for bills?

**Comment by JC5** [comment]
I saw your donation! Thanks! :tada:!

It's the same: I kind of "ignore" the balance. But that took some getting used to. It taught me the difference between being able to pay for something and being able to afford something. But yes, in the beginning I tended to overspend my savings since I forgot that money was there for a reason.

The bottom of the `/piggy-banks` page shows you how much you actually have "left".

**Comment by jsykes** [comment]
You're welcome!

So going back to the original question.. If I had a negative asset account for student loans, how would I be able to transfer money to that account while also covering it in the bills? If I did transfer money to that account and when reconcile showed a difference, would I just do withdrawals on that for an interest / fee category?

Also, I see you are pretty active with development on this. Mind if I ask what your motivation is?

**Comment by JC5** [comment]
At the moment, you cannot. Bills will not be triggered by transfers. You can mark the rent but not the main payments. This is something for future development.

And for your second question. I've been typing out some replies but basically I do this because I like it. :grin:
