### ISSUE TITLE
New transfer from `transactions/create/transfers` returns a 404

### ISSUE THREAD

**Issue by mirkof** [firefly-iii/firefly-iii#1175]
I am running Firefly III version 4.7.0 This happens on the demo too.

#### Description of my issue:
New transfer from `transactions/create/transfers` returns a 404

#### Steps to reproduce 

Go to `Transactions` ->`Transfers` -> `New transfer` -> 404

#### Other important details (log files, system info):

Debug information generated at 2018-02-11 13:27:45 UTC for Firefly III version **4.7.0**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.0 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, errorlog |
| PHP version | 7.2.1 |
| Display errors | Off |
| Error reporting | ALL errors |
| Host | Linux aba676be-b353-451a-bf24-64d3ea503992 4.4.0-1011-aws # 11-Ubuntu SMP Fri Jan 12 23:24:17 UTC 2018 x86_64 |
| Interface | fpm-fcgi |
| UserID | 1 |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, mbstring, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@4.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.6.4, fideloper/proxy@3.3.4, laravel/framework@v5.5.33, laravelcollective/html@v5.5.1, league/commonmark@0.17.0, league/csv@9.1.1, league/flysystem@1.0.42, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.22.1, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/log@1.0.2, psr/simple-cache@1.0.0, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.5, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v3.4.4, symfony/css-selector@v4.0.4, symfony/debug@v3.4.4, symfony/event-dispatcher@v4.0.4, symfony/finder@v3.4.4, symfony/http-foundation@v3.4.4, symfony/http-kernel@v3.4.4, symfony/polyfill-mbstring@v1.6.0, symfony/polyfill-php56@v1.6.0, symfony/polyfill-php70@v1.6.0, symfony/polyfill-util@v1.6.0, symfony/process@v3.4.4, symfony/routing@v3.4.4, symfony/translation@v3.4.4, symfony/var-dumper@v3.4.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.0, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2,  |

**Comment by JC5** [comment]
Indeed! Thanks for reporting. I've pushed a fix that will go live in the next release.

**Comment by JC5** [comment]
Closed to clear the issue list.

**Comment by Ekvilog** [comment]
Hi, I started to use Firefly. I really like it. Thank you for the developing it.

Could you please help me with the same problem an described above:
when I go to Transactions ->Transfers -> New transfer -> 404
I receive this message: 404 — Firefly III cannot find this page.
The page you have requested does not exist. Please check that you have not entered the wrong URL. Did you make a typo perhaps?

How to fix it?

**Comment by JC5** [comment]
If you wait for the new release, it will be fixed automatically. It should be a few days of patience :-)

**Comment by Ekvilog** [comment]
Great! Thank you

**Comment by Ekvilog** [comment]
Hi again,
I wonder when to expect the new release, because the "new transfer" still gives 404 error and I stuck with my accounting :) 
Thanks

**Comment by JC5** [comment]
4.1.7.4 is the new release and it’s been out for a few days now :)

**Comment by Ekvilog** [comment]
Thank you! Now I found it. Works perfectly!
