### ISSUE TITLE
Tags autocomplete doesn't work

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1178]
I am running Firefly III version 4.7.0 on the demo site.

#### Description of my issue:

I usually only type few letters of tag and then select first suggesstion. Recently I've discovered that tag autocomplete (suggestions) doesn't work on Firefox. It might never worked - I'm not sure - I've recently switched from Chrome to Firefox.

Just checked Chrome and it also doesn't work.

#### Steps to reproduce 

1. Open the demo site.
2. Start creating new transaction.
3. Type "Bal" in "Tags".
4. There should be suggestion "Balancing act tag".

#### Other important details (log files, system info):

Firefox 58.0.2
Chrome 64.0.3282.167
Windows 10
I've tried to force refresh (Ctrl+F5) and disabling cache in Developer Tools. It didn't help.

**Comment by JC5** [comment]
Confirmed. Will get it fixed!

**Comment by JC5** [comment]
Fixed in the next release.
