### ISSUE TITLE
Firefly behind reverse proxy not using https for some parts (css/login...)

### ISSUE THREAD

**Issue by Babo96** [firefly-iii/firefly-iii#1179]
I am running Firefly III version 4.7.0 

#### Description of my issue:
When I configure my FF iii to use apache as reverse proxy, configured as described in the documentation I can access FF via firefly.mydomain.com but it looks like it does not load the css file, I also get a "this connection is not secure" when trying to login with Firefox.

I tried fixes suggested in: #275

I set the environment variables APP_URL and TRUSTED_PROXIES and checked in the image that they were were set correctly

#### Steps to reproduce 

I don't know how to reproduce it but I'll attach my apache conf (section for FF)

#### Other important details (log files, system info):

        <VirtualHost *:443>
                ServerName firefly.mydomain.com
                ProxyPreserveHost On

                SSLEngine on
                SSLCertificateFile /cert.pem
                SSLCertificateKeyFile   /privkey.pem
                SSLCertificateChainFile /fullchain.pem

                RequestHeader set X-Forwarded-Proto "https"
                RequestHeader set X-Forwarded-Port "443"

                ProxyPass / http://192.168.2.XXX:8082/
                ProxyPassReverse / http://192.168.2.XXX:8082/
        </VirtualHost>

**Comment by JC5** [comment]
Combined with the headers this should work just fine. Did you set trusted proxies to "**"?

**Comment by Babo96** [comment]
ok sorry that fixed it, I tried it yesterday and it did not, pretty sure my damn browser cached the wrong page then.

thanks for the quick answer and for helping me out

**Comment by JC5** [comment]
No problem, glad it works! :+1:
