### ISSUE TITLE
Installing Firefly III on Raspberry PI 3

### ISSUE THREAD

**Issue by rogerillu** [firefly-iii/firefly-iii#1180]
I am running Firefly III version 4.7.0

#### Description of my issue: Blank page and "The requested URL /login was not found on this server."
I have tried to install Firefly on my RPI3 and it is not working. I have an apache server configured with wordpress working finet to test if the webpage and folder permissions were working fine. I tried to install firefly in the /var/www/html/ folder following the instructions:
1.-  composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii
2.- edit the .env file in the firefly generated folder with the configuration of my database
3.- php artisan migrate:refresh --seed

I have redirected the root folder from public to /

It seems that everything is installed and generated correctly, but when trying to enter to the localhost/ it gives an error trying to reach login or a blank page when I executed "sudo a2enmod rewrite"

There are no logs in the storage/logs folder as there was no errors in the installtion process.

I have edited the apache configuration file with the directory allow options.

Do you know what could be wrong?

Thanks!!

**Comment by JC5** [comment]
What does the file `/var/log/apache2/error.log` tell you? It will probably give some hints what is happening.

Also, what is the output of `php -v` on the command line?

**Comment by rogerillu** [comment]
Hi JC5!

The error.log:

[Sun Feb 18 10:16:41.445456 2018] [php7:error] [pid 5414] [client 192.168.1.34:48302] PHP Fatal error:  Uncaught RuntimeException: Unable to write in the cache directory (/var/www/html/firefly-iii/storage/framework/views/twig/$


I have tried in the root folder:

sudo chown -R www-data:www-data var/cache

But nothing changed.


This is the output for the php-v:

PHP 7.1.13-1 (cli) (built: Jan  5 2018 12:14:37) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13-1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by JC5** [comment]
Try the following:

```
chown -R www-data:www-data /var/www/html/firefly-iii
chmod -R 775 /var/www/html/firefly-iii/storage
php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan view:clear
```

It's not just ownership but access rights as well. That should make it work.

**Comment by rogerillu** [comment]
No way. I haver reinstalled all and giving the permissions from your comment but I still have the message:
Not Found

The requested URL /login was not found on this server.

I have cleaned the firefox cache.

Thanks!

**Comment by JC5** [comment]
OK, but that's another message, and we can fix it as well!

Check out the error logs again. A 404 on the /login means that either the rewrite mod does not work (enabled or not) or perhaps the htaccess file is being ignored.

What is the value for AllowOverride in your Apache config?

**Comment by rogerillu** [comment]
The apache configuration:

<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

#<Directory /srv/>
#       Options Indexes FollowSymLinks
#       AllowOverride None
#       Require all granted
#</Directory>

<Directory /var/www/firefly-iii/public>
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        allow from all
</Directory>


this is the content of my .htaccess from the firefly-iii folder:

# Optional: force HTTPS:
# <IfModule mod_rewrite.c>
#       RewriteEngine On
#       RewriteCond %{HTTPS} off
#       RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
# </IfModule>

# To hide directory listing
Options All -Indexes

# To prevent access to .env and other files
<Files .*>
    Deny from all
</Files>

Thanks!

**Comment by JC5** [comment]
```
<Directory /var/www/firefly-iii/public>
```

Should be:

```
<Directory /var/www/html/firefly-iii/public>
```

**Comment by rogerillu** [comment]
Finally!! Working!!! thanks a lot for your help!!! I will re-do it all again, beucase now it give a warning about the language, but when I got all working I will try to do a how-to guide to configure it in a raspberry pi 3. Thanks a lot for your help!

**Comment by JC5** [comment]
:+1:

You're welcome! To fix the language errors, make sure that you install the packages for es_ES. I believe you can do this automatically by running 

```
sudo apt-get install language-pack-es-base
```

But you must Google it to be sure. 

If you see errors in the translations or weird things, I would appreciate it a lot of you submit it at Crowdin: https://crowdin.com/project/firefly-iii

**Comment by MichelFreund** [comment]
@rogerillu ; I would like that how to guide. Where you able to compose it?

**Comment by trgraglia** [comment]
> @rogerillu ; I would like that how to guide. Where you able to compose it?

I think an even easier install guide would help adoption here. A lot of people just want to paste a few commands and be done with it. Even if a command runs a script which does most of the heavy listing. Solid product. Thanks.
