### ISSUE TITLE
Wrong CSV field delimiter

### ISSUE THREAD

**Issue by megawario** [firefly-iii/firefly-iii#1183]
Hi there,

#### Description of my issue:
When importing a CSV with ";" separated fields, the column mapping uses the "," even after choosing ";" in the import options.

Exchanging the "," for a "." in the numbers made it add everything to one single column.

#### Steps to reproduce 
Import file ( csv file with ; delimiter and , for decimal numbers (ex: 3,49).
OR
Import file (csv with ";" delimiter and "." for deciman numbers.

**Comment by phosphotungstic** [comment]
Looks similar to

https://github.com/firefly-iii/firefly-iii/issues/1172

**Comment by JC5** [comment]
It does indeed. Could you share some example rows from your file and tell me which options you use?

**Comment by IcyPalm** [comment]
I have the same issue when trying to import a CSV with ";" as separator

Version 4.7.0

Rows:
```
"Date";"Amount";"Account";"Counterparty";"Name";"Description"
"2016-09-02";"20,00";"NL99IBAN1234567890";"NL99IBAN1234567890";"NAME";"DESCRIPTION"
"2016-09-02";"-0,01";"NL99IBAN1234567890";"NL99IBAN1234567890";"NAME";""
```

![settings](https://user-images.githubusercontent.com/2883482/36537228-d0beb8dc-17cf-11e8-8e60-8ba003dcd4d2.PNG)
![result](https://user-images.githubusercontent.com/2883482/36537235-d518ce90-17cf-11e8-9131-854f5871bffd.PNG)

**Comment by JC5** [comment]
Thanks for letting me know! I've been able to pinpoint this and I believe it'll be fixed in the next release (around the start of March).

I will double check your lines before the release.

**Comment by JC5** [comment]
Fixed in the new release, which will arrive end of the month.

![screen shot 2018-02-22 at 18 56 31](https://user-images.githubusercontent.com/5889984/36555406-31998272-1802-11e8-9e7d-4e9a495d35b5.png)

**Comment by JC5** [comment]
Closed to clear the list

**Comment by IcyPalm** [comment]
Great work! 👍
