### ISSUE TITLE
The unclear behavior of the "New Transaction" button

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1185]
I am running Firefly III version 4.7.0

If I click the button "Create a new transaction" in the block of one of the accounts, I expect that a new transaction will be created for this account. But no matter in which block I clicked the "New Transaction" button, I always see the default account in the form.
In my opinion, this is illogical behavior.

![1](https://user-images.githubusercontent.com/520760/36466332-9ec8e432-16ea-11e8-8db1-1f68a29de3f2.jpg)

**Comment by JC5** [comment]
Indeed it is! I shall make sure the correct account gets selected.

**Comment by Nik-vr** [comment]
Thank!

**Comment by JC5** [comment]
You can try this on the demo site. The following links (after login) should automatically select different accounts. The links on the front page are adjusted as well:

https://demo.firefly-iii.org/transactions/create/withdrawal?source=32
https://demo.firefly-iii.org/transactions/create/withdrawal?source=1

**Comment by Nik-vr** [comment]
I can't login to this demo (with demo@firefly / demo):

> Error!! These credentials do not match our records.

**Comment by JC5** [comment]
Strange, it works for me. Did you type it or copy/paste it?

**Comment by Nik-vr** [comment]
Login - copy/paste, password - type. Try to copy/paste password - now it's work :) 

Youк links work - different  accounts has selected.
