### ISSUE TITLE
To see the amount on the account when creating the transfer

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1186]
When I make a transfer between accounts or in a piggy bank, I would like to see the amount that is available on the source account.

Something like this:

![2](https://user-images.githubusercontent.com/520760/36466495-98bd4e42-16eb-11e8-9fb1-39a2dc5a8d7a.jpg)

**Comment by JC5** [comment]
Perhaps not yet in the next release, but certainly a good idea!

**Comment by JC5** [comment]
This is visible on the demo site. Please note that the account will always show the latest amount, even when you go back in time using the date navigator.

https://demo.firefly-iii.org/transactions/create/withdrawal

If you have additional questions, just open a new issue :+1:

**Comment by Nik-vr** [comment]
This good! Thank you!
