### ISSUE TITLE
Enhancement : Create my own currency

### ISSUE THREAD

**Issue by Zciwobukaj** [firefly-iii/firefly-iii#1188]
Hello, 

Each month my company gives me 20 meal cheques, each worths 10.50 €
So I created an account in Firefly where I track the expenses I made with these. Each line is in euros now.

What would be nice : that I can manage this account with the "meal cheque" currency, means the ability to create my personalized currency.

What do you think ?

**Comment by JC5** [comment]
I think you should check out the currencies page under administration. This is already possible :wink:

**Comment by JC5** [comment]
It requires a currency code which is three capital letters. You can safely make one up. For example, the euro is EUR, the US dollar is USD. 

You can safely use ABC. Currency standards would have you start with an X, like XAB but this is not mandatory.

**Comment by Zciwobukaj** [comment]
Wow it's nice ! Thank you I didn't understand this in this way. So maybe this should be specified in the help section ?

Another question : now that I set my new currency, I want apply this to the corresponding account.
So I edit it, change the currency, validate... And nothing changes.
Note that I already have transactions in euros. So should I convert them all in "meal cheques" currency before editing my account ?

**Comment by JC5** [comment]
That’s ok! You will have to convert the transactions by hand. It doesn’t matter if you do this before or after, but I recommend after.

**Comment by Zciwobukaj** [comment]
Ok so I found bug : 
* I converted all my transactions in "CHD" (my new currency) and tried once again to set CHD as the account currency => fail (when I come back to the account property, the currency is still EUR)
* So I deleted ALL transactions on this account and tried to set the currency as CHD => fail (same behaviour).

The only way I saw was to delete the account, create another with the same name and CHD currency and next to write manually all the transactions. But it's not convenient :-(

**Comment by JC5** [comment]
No it’s not! I will check it out!

**Comment by Zciwobukaj** [comment]
Thanks 👍

**Comment by JC5** [comment]
I was successfully able to change the currency in my test environment. You can try this on the demo site as well. As far as I can tell this works. Updating transactions also works for me.

Which version are you running?

**Comment by Zciwobukaj** [comment]
I perform a test on the demo platform : 
1) Create the CHD currency
2) Create account with EUR currency
3) Enter several transactions with EUR currency
4) Edit the account and set the currency as CHD
Result : pass

The behaviour is different than on my platform.
Note that my platform is in french (this includes the use of the "," as decimal separator and the date format "dd/mm/yyyy") and that this is slightly slower than the demo platform.

**Comment by JC5** [comment]
Could you share the content of your-firefly.com/debug with me? (top box)

**Comment by Zciwobukaj** [comment]
Here it is : 

Debug information generated at 2018-02-23 16:07:37 UTC for Firefly III version **4.7.0**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | warning, daily |
| PHP version | 7.1.13 |
| Display errors | Off |
| Error reporting | ALL errors |
| Host | Linux 3dde4266684d 4.2.8 # 1 SMP Tue Feb 13 01:28:44 CST 2018 x86_64 |
| Interface | apache2handler |
| UserID | 1 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, pdo_mysql, pdo_pgsql, tidy, zip |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@4.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.6.4, fideloper/proxy@3.3.4, laravel/framework@v5.5.33, laravelcollective/html@v5.5.1, league/commonmark@0.17.0, league/csv@9.1.1, league/flysystem@1.0.42, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.22.1, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/log@1.0.2, psr/simple-cache@1.0.0, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.5, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v3.4.4, symfony/css-selector@v4.0.4, symfony/debug@v3.4.4, symfony/event-dispatcher@v4.0.4, symfony/finder@v3.4.4, symfony/http-foundation@v3.4.4, symfony/http-kernel@v3.4.4, symfony/polyfill-mbstring@v1.6.0, symfony/polyfill-php56@v1.6.0, symfony/polyfill-php70@v1.6.0, symfony/polyfill-util@v1.6.0, symfony/process@v3.4.4, symfony/routing@v3.4.4, symfony/translation@v3.4.4, symfony/var-dumper@v3.4.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.0, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2,  |

**Comment by JC5** [comment]
Using French as a language should not matter. Could you browse to your-firefly.com/flush to see if this clears any issues?
