### ISSUE TITLE
Inactive account with different currency

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1189]
I am running Firefly III version 4.7.0

#### Description of my issue:

Hi,
for my vacation I've created a temporary asset account to track cash money in a different currency. Now after my holidays the account's balance is exactly 0 and I basically do not need it anymore. Yet I do not want to remove it because I want to keep the associated transactions. Thus I set the account to be inactive but now in the _total net worth_ box, firefly still shows two numbers: my actual net worth in my default currency and an amount of 0 british pounds.

Speaking about different currencies: Is there a way to track money lost/gained through exchange rates? Say I have two asset accounts with different currencies: Account A in EUR and Account B in GBP.
When I transfer money from A to B and some time later transfer it back from B to A, the exchange rates might have changed in the meanwhile. Then I'm basically losing/gaining money through a transfer. But normally this should only be possible through an expense/revenue transaction.

**Comment by JC5** [comment]
I can make sure that inactive accounts are removed from the net worth box, no problem. It's not something anybody has run into until now.

As for your second question: when it comes to exchange rates the balances become a bit strange indeed. Yes, you can lose money through such transfers but they should not make your balances "unbalanced". However, there is no way to track such differences except by linking the transactions together.

**Comment by JC5** [comment]
Fixed in 4.7.2
