### ISSUE TITLE
Firefly new transfer transaction error 404

### ISSUE THREAD

**Issue by japsikado** [firefly-iii/firefly-iii#1190]
I am running Firefly III version 4.7.0

Description of my issue:

if i click the new transfer button it redirect to http://myfireflyiiiurl.com/transactions/create/transfers

but it should be http://myfireflyiiiurl.com/transactions/create/transfer      <-- without the 's' at the end

it is very annoying that you need to remove the 's' at the end to make a new transfer transaction

srry for my bad english :P

**Comment by JC5** [comment]
No problem! This bug will be fixed in the next release.

https://github.com/firefly-iii/firefly-iii/issues/1175
