### ISSUE TITLE
Chart not updated when changing the budget we're viewing

### ISSUE THREAD

**Issue by versvs** [firefly-iii/firefly-iii#1192]
I am running Firefly III version 4.7.0

#### Description of my issue:

The bars chart for a budget showing all transactions for a given budget is not updated if "show everything" was selected.

#### Steps to reproduce 

1. Navigate to `/budgets`
2. Select any budget, enjoy your curve graph with points and tooltips for every single day
3. In the bottom right corner, below the widgets for the different periods in which this budget has been active click the "show everything" button. A bars graph belonging to the current budget will substitute the curve one.
4. Navigate to `/budgets` again and select another budget (not the one before). Enjoy your curve graph.
5. Click "show everything" again.
6. Et voilà, the bars graph that appears is the one from the first budget visited.

Logging out and in of Firefly let's you restart the process (the first time you will see the right graph, the second time you will get an unexpected behaviour).

(please include if this problem also exists on the demo site)
Yes, this bug can be observed when switching from `Bills` to `Groceries` (though, perhaps importantly, i didnt reproduce it at first when switching from `Bills` to `Car`).

#### Other important details (log files, system info):
System info extracted from the debug window:

Debug information generated at XXXX-XX-XX UTC for Firefly III version **4.7.0**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.2.2-3+ubuntu16.04 |
| Display errors | Off |
| Error reporting | ALL errors |
| Host | Linux 4.4.0-116-generic # 140-Ubuntu x86_64 |
| Interface | apache2handler |
| UserID | 42 |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@4.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.6.4, fideloper/proxy@3.3.4, laravel/framework@v5.5.33, laravelcollective/html@v5.5.1, league/commonmark@0.17.0, league/csv@9.1.1, league/flysystem@1.0.42, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.22.1, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/log@1.0.2, psr/simple-cache@1.0.0, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.5, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v3.4.4, symfony/css-selector@v4.0.4, symfony/debug@v3.4.4, symfony/event-dispatcher@v4.0.4, symfony/finder@v3.4.4, symfony/http-foundation@v3.4.4, symfony/http-kernel@v3.4.4, symfony/polyfill-mbstring@v1.6.0, symfony/polyfill-php56@v1.6.0, symfony/polyfill-php70@v1.6.0, symfony/polyfill-util@v1.6.0, symfony/process@v3.4.4, symfony/routing@v3.4.4, symfony/translation@v3.4.4, symfony/var-dumper@v3.4.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.0, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2,  |

**Comment by JC5** [comment]
Nice find! Thanks for reporting it. It will be fixed in the next release.
