### ISSUE TITLE
Widget showing accumulated balance for a budget

### ISSUE THREAD

**Issue by versvs** [firefly-iii/firefly-iii#1193]
I'm quite new to Firefly, but i've been using it for a few days (tasting the waters before deciding if switching all my accountability to Firefly) and there is something I would find very useful:

When viewing budgets, whether in the `/budgets` list or in the single budget view, It would be very useful to have a widget telling you the accumulated balance for this budget in the selected period.

## How it would work

Say you allocated €100 for this budget during each one of a series of 3 months, and that in the first month you only spent €70 (balance +30€), in the second month you spent €50 (balance +50, accumulated balance +80€) and in the third month selected you spent 120€ (balance -20€, total balance +60€). 

The widget would show the from-to dates (similar as other widgets already present in the single view) and a number telling you the accumulated balance for the given period.

Ideally, if this balance for a multi-period is made available app-wide, it could be even shown in the budget list as a column, as it really helps you detect at first glance if you're spending on something way more (or way less, too) than you had planned/intended.

**Comment by JC5** [comment]
Thanks for the suggestion! I'll think about how i could add something like this :)

**Comment by versvs** [comment]
Nice! The reasoning behind this feature is that most of my monthly budgets are repeated through months (the exact allocation may vary, but in the end I put some € every single month on fitness & entertainment, in example), thus having the chance of viewing the balance of a budget through out a given period or a whole year makes sense :)

**Comment by JC5** [comment]
I'm sorry, but budgets won't accumulate over the year in Firefly III. So I'm closing this one.

**Comment by versvs** [comment]
Thanks anyway. I got it working with a quick-and-dirty javascript script that I load using Greasemonkey. Some native support would have been nice, but i understand it is not a mainstream feature :)

![imagen](https://user-images.githubusercontent.com/11803/49043206-ae043800-f1ca-11e8-9e8d-fbd77283b596.png)
