### ISSUE TITLE
Paging/sorting on accounts page

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1195]
I am running Firefly III version 4.7.0

#### Description of my issue:
When I sort the expense accounts by current balance, firefly sorts them pagewise. That is, it only sorts the data shown on current page without considering the whole data. This results in rather useless sorting behavior. As sorting seems to be done on client side, this seems like a generall problem which would be worth solving.

**Comment by JC5** [comment]
Yes, this is an effect of the pagination of the account list. I didn't account for it, sorry about that.

You could set the lists to be longer to mitigate this (in your preferences). I shall write it down as a future enhancement.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937737
