### ISSUE TITLE
To register the same extension twice ("TwigBridge_Extension_Loader_Functions") is deprecated since version 1.23

### ISSUE THREAD

**Issue by Nitramakloh** [firefly-iii/firefly-iii#1196]
I am running Firefly III version 4.7.0 

#### Description of my issue:

> I get following error: Whoops! An error occurred.
> Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> 
> The possibility to register the same extension twice ("TwigBridge_Extension_Loader_Functions") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead.

Is this because I use PHP 7.1 on my server?

#### Steps to reproduce 

Just open the firefly page on my server. Problem doesn't exist on the demo site.

#### Other important details (log files, system info):

`[2018-02-25 09:58:53] local.ERROR: The possibility to register the same extension twice ("TwigBridge_Extension_Loader_Functions") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead. {"exception":"[object] (ErrorException(code: 0): The possibility to register the same extension twice (\"TwigBridge_Extension_Loader_Functions\") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead. at /var/www/html/firefly-iii/vendor/twig/twig/lib/Twig/Environment.php:944)"} `

**Comment by JC5** [comment]
Is this during the running, or during the installation?

How exactly are you running or installing Firefly III?

**Comment by Nitramakloh** [comment]
Hello @JC5 
This happens during running, when I try to access any URL beginning with /firefly/public/*

**Comment by JC5** [comment]
What method did you use to install FF3?

**Comment by Nitramakloh** [comment]
I installed it with composer as mentioned in the instructions. After that FF3 works fine for some months. A few days ago, however, it didn't work any more. My guess is that I made an update of PHP. Other websites on my server work still fine.

**Comment by JC5** [comment]
I must admit I have to idea yet what is happening. The upgrade was to PHP7.1 or to PHP7.2?

**Comment by Nitramakloh** [comment]
It was from 7.0 to 7.1. But maybe the cause is something different. I will search deeper.

**Comment by JC5** [comment]
OK, but Firefly III does not work on PHP 7.0. There is code in there that will break when you try it. So I am curious to know how you managed to get it to work on 7.0 ;)

**Comment by Nitramakloh** [comment]
You're right. This was my mistake. :D

I found a workaround for me and edited these files:

# firefly-iii/vendor/symfony/http-foundation/Request.php:682

`    public static function setTrustedHeaderName($key, $value)
    {
        //@trigger_error(sprintf('The "%s()" method is deprecated since Symfony 3.3 and will be removed in 4.0. Use the $trustedHeaderSet argument of the Request::setTrustedProxies() method instead.', __METHOD__), E_USER_DEPRECATED);`

# firefly-iii/vendor/twig/twig/lib/Twig/Environment.php:944

`    public function addExtension(Twig_ExtensionInterface $extension)
    {
        if ($this->extensionInitialized) {
            throw new LogicException(sprintf('Unable to register extension "%s" as extensions have already been initialized.', $extension->getName()));
        }

        $class = get_class($extension);
        if ($class !== $extension->getName()) {
            if (isset($this->extensions[$extension->getName()])) {
                unset($this->extensions[$extension->getName()], $this->extensionsByClass[$class]);
                //@trigger_error(sprintf('The possibility to register the same extension twice ("%s") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead.', $extension->getName()), E_USER_DEPRECATED);`

As you can see I just disabled the trigger_error statements. It's not the best way, but now FF3 works again.

**Comment by JC5** [comment]
Well I'm glad to hear it works. Keep in mind it might break when you upgrade!
