### ISSUE TITLE
How can I send email?

### ISSUE THREAD

**Issue by Ekvilog** [firefly-iii/firefly-iii#1204]
I am running Firefly III version x.x.x 

#### Steps to reproduce 

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
> I am running Firefly III version 4.7.0. I would like to change my email address, but sending test email message for verifying the new email address does not work. I receive this error message: Error! Possible email error: Connection could not be established with host smtp.mailtrap.io [Connection refused #111]. My question is where can I configure the test email sending? How does it work?

Open the `.env` file and read the instructions :)

**Comment by Ekvilog** [comment]
Thanks, very funny. I opened the file, but I am not a programer. I just install this from our Cpanel to our server and would like to use it like a simple user. If there are settings available, then this software will probably be useless for me. But thanks anyway

**Comment by JC5** [comment]
Sorry, if you started with that I could have been more clear about it :wink:

Firefly III comes with a default email configuration that doesn't work. It's a set of default values. Configuration of those values is normally done by the user. People with installations outside of Softalicious (this is the product in CPanel that provides FF3) are capable of editing this file according to their wishes. They would configure GMail, Outlook or something similar.

I will contact the guys at Softalicious to reconfigure the default Firefly III package. They should be able to configure it in such a way that it is able to send email.

Do you have access to the database that Firefly III uses?

**Comment by Ekvilog** [comment]
Hi James, thank you for the clarification! Later I figured out where can I change it in the file, but when I attempted to open .env file in the Word, it somehow rewrited my normal.dot file and my Word crashes since then. The default package would be real help for such user as me :)

**Comment by simhnna** [comment]
@ekvilog the .env file is just a plain text file. Word isn't the correct program to edit those. Word stores it's data in very complex XML files or even archives. 
If you edit the file using notepad everything should behave.

**Comment by JC5** [comment]
When Notepad does not properly format your file, please download [Notepad++](https://notepad-plus-plus.org/).
