### ISSUE TITLE
Increase bill matching possibilities

### ISSUE THREAD

**Issue by Ircghost** [firefly-iii/firefly-iii#1205]
I am running Firefly III version 4.7.0

#### Description of my issue:
Currently I'm trying to setup bill recognition. I pay my rent through different expense accounts (sometimes paypal, sometimes iDeal). I'm trying to recognize them both in one bill.

Since the matching is (I think) mostly done on destination source name/account I can't just link it to either one provider, because every added argument works with 'AND'. In my rules section I also apply the label 'rent' through 2 rules to identify these transactions. But if I create two bills, my expected $$ of to be paid bills is completely incorrect.

#### Steps to reproduce 
Try to make one bill that matches two (or more) different expense accounts.

#### Suggestions:
1) Make matching possible by same way as rules work (i.e. if tag = rent)
2) Create possibility to match to a bill as an option in the rules section (just like you can set category or tag)
3) Introduce the 'OR' operator, but that has been suggested before of course.

Thank you for your consideration!

**Comment by JC5** [comment]
Bills are matched using a primitive version of what rules are. So indeed, I want to expand the bills routines to match what rules are doing now. Or rather: expand the rules so bills can be matched through rules. I have yet to find a useful way to combine the two. But I believe that would answer your questions.

However, your initial problem doesn't exist: it is possible to match a bill to different expense accounts or different asset accounts. It works by matching on the description as well.

You can experiment with this on the demo site. I was able to match [this bill](https://demo.firefly-iii.org/bills/show/4) to different expense and asset accounts without losing the match.

Please note that the bill might be deleted once you have time to check it out: the demo site resets every so often.

**Comment by Ircghost** [comment]
Thank you for your response! Unfortunately your suggestion doesn't work for my situation. Paypal doesn't have information in the description that explains what has been bought / destination. So in this particular case I can only match on amount + source combination.

**Comment by JC5** [comment]
Ah, so you're importing data using CSV files? Because then there's not much I can do.

**Comment by Ircghost** [comment]
Indeed I am! I know your philosophy is to enable more awareness for expenditures, I'm however mostly looking for a tool can help with visualizing expenses and a big picture overview, which Firefly is also great at.

**Comment by JC5** [comment]
Well I am as much surprised about PayPal honestly ;).

**Comment by JC5** [comment]
Solved.

**Comment by Ircghost** [comment]
Your suggestion with weekly payment, skipped by 1, solves the situation. For both double payment on the same day as for twice in one month :).

**Comment by JC5** [comment]
Good to hear! :+1:
