### ISSUE TITLE
Identify double payments for bill

### ISSUE THREAD

**Issue by Ircghost** [firefly-iii/firefly-iii#1206]
I am running Firefly III version 4.7.0

#### Description of my issue:
One of my accounts has a couple of double payments to a single expense account within one month. Examples:
1) Mobile phone bill for my partner and myself
2) Insurance idem
3) Gym membership idem

Currently I'm identifying them through the expense account name and amount range, which for the gym is €35 a month. This is however separately deducted from my account (usually on the same day, but not always). Therefore, my expected bill is either €70 or twice €35, but right now all I can make Firefly identify is €35 once a month.

I guess in theory I could just add the same bill twice, but then I wouldn't know which one it's hitting on, i.e. when one monthly phone charge is much higher for example. 

#### Steps to reproduce 
Setup a bill that matches for two near identical expenses and identify them both as bills.
Setup a bill that matches for two full identical expenses and identify them both as bills.

#### Suggestion
Make it possible to identify double payments within the same period. I.e. currently the frequency is weekly, monthly,.. but this is twice a month, which is neither.

Thank you for your consideration!

**Comment by JC5** [comment]
When you can't distinguish these payments, neither will Firefly III I'm afraid.

I would suggest either of two suggestions:

- Making the bill repeat weekly, but skipping 1 week. Effectively making it hit twice a month.
- Add something to the description of the expense. "Insurance [your name]" or "Insurance [their name]" should do it.

Would that work?

**Comment by Ircghost** [comment]
I'll try the repeat + skip function. The description won't work because the title is empty. I'll let you know tomorrow.

**Comment by JC5** [comment]
Solved! :+1:
