### ISSUE TITLE
bunq exported statement can contain double transactions

### ISSUE THREAD

**Issue by IcyPalm** [firefly-iii/firefly-iii#1208]
I am running Firefly III version 4.7.0 in a local Docker

#### Description of my issue:
While importing a complete export from bunq I noticed that the total amount at the end did not match my actual balance.

I exported the imported data from Firefly and gave the input csv a very close compare to the exported data and noticed something funny. 

```
"Date","Amount","Account","Counterparty","Name","Description"
"2017-04-03","-13,00","NL12BUNQ1234567890","","Some Business Name","Some Business Name(Groningen, NL)"
"2017-04-03","13,00","NL12BUNQ1234567890","","Some Business Name","Refund: Some Business Name(Groningen, NL)"
"2017-04-03","-13,00","NL12BUNQ1234567890","","Some Business Name","Some Business Name(Groningen, NL)"
```
This was a denied transaction by the payment terminal and I tried again and it work. The second withdrawal gets skipped in the import process. I presume since the lines are exactly the same Firefly sees it as a double transaction.

And indeed, according to the debug:
```
[2018-02-28 13:49:31] local.ERROR: A journal with hash 3e8dae7ffa4524f347c32f6ec0778003088bf285e1209294caaff77bc35c0a5b has already been imported (spoiler: it's journal #3889)  
[2018-02-28 13:49:31] local.ERROR: Detected a possible duplicate, skip this one (hash: 3e8dae7ffa4524f347c32f6ec0778003088bf285e1209294caaff77bc35c0a5b). {"type":"Withdrawal","description":"Some Business Name(Groningen, NL)","amount":"-13.000000000000","date":"2017-06-17","asset":"Bunq","opposing":"Some Business Name"} 
```

I created a workaround for myself: add an incremented number as an extra column to make every statement truely unique. Then it went all fine.

However, these are direct export files from bunq and I would appreciate if they could be imported directly without any hitch.

**Comment by JC5** [comment]
They won't be a solution from my side, I'm afraid. If Firefly III can't tell the difference because the lines are literally exactly the same, there's not much I can do.

There's a similar issue regarding NFC transactions, when you buy two things in the same minute.

To fix this, bunq needs to be more precise. Either they add a sequence number or they add the time in seconds.

**Comment by IcyPalm** [comment]
Fair point. I understand you cannot do anything about this

For future reference: I asked bunq to fix this:
https://together.bunq.com/topic/export-statement-contains-identical-lines

**Comment by JC5** [comment]
:+1:

I look forward to their update. Use of their API is on my todo list (and quite a lot of code is already present) so if they do nothing the issue becomes moot.

Thanks for reporting!

**Comment by IcyPalm** [comment]
Is the API something you are working on for 4.7.1 or for later? I am very willing to help with implementing/testing the API
