### ISSUE TITLE
Caught an error in Firely III...

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1209]
I am running Firefly III version 4.7.0

#### Description of my issue:
Trying to view a transaction that has other transactions linked to it.
Some of the linked transactions have been removed, without first removing the links. Might that have caused the issue?
#### Steps to reproduce 

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):

Firefly III v4.7.0 ran into an error: Type error: Argument 1 passed to FireflyIII\Support\Twig\Extension\TransactionJournal::totalAmount() must be an instance of FireflyIII\Models\TransactionJournal, null given, called in /var/.../public_html/storage/framework/views/twig/83/8362843339544584e7cb7c7e16ec4b169ddefe64c6fac43885985ab915e346f6.php on line 841

The error was of type "Symfony\Component\Debug\Exception\FatalThrowableError".

The error occured on/at: Wed, 28 Feb 2018 18:48:30 +0000.

This error occured in file /var/.../public_html/app/Support/Twig/Extension/TransactionJournal.php on line 40 with code 0.

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by zjean** [comment]
I fixed by removing the orphan records from the journal_links table.

**Comment by JC5** [comment]
Nice. I have not had the time to check this out but I will make sure that journal links will be able to handle this!

**Comment by JC5** [comment]
I think I found the problem, and it will be fixed in the next release.
