### ISSUE TITLE
CSV - encoding and semicolon

### ISSUE THREAD

**Issue by FrodeMMeling** [firefly-iii/firefly-iii#1210]
I am running Firefly III version 4.7.0 

#### Description of my issue:
2 Issues:

1. can you add support for setting encoding on CSV file beeing imported. My bank exports with Western ISO. Would be nice to be able to set this.

2. Maybe this is related to 1. When I import a csv with ; it does not detect ; as separator.

#### Steps to reproduce 

Save this 
```
Date;Description;Interestdate;In;Out;
27.02.2018;Småsparing 1 stk fast beløp;27.02.2018;;-50,00;;
```

#### Other important details (log files, system info):

Debug information generated at 2018-03-01 12:14:46 UTC for Firefly III version **4.7.0**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, daily |
| PHP version | 7.1.14 |
| Display errors | Off |
| Error reporting | ALL errors |
| Host | Darwin Frodes-Mac-mini.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2\~1/RELEASE_X86_64 x86_64 |
| Interface | fpm-fcgi |
| UserID | 1 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, json, ldap, mbstring, session, standard, odbc, pcntl, mysqlnd, PDO, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, readline, Reflection, mysqli, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi |
| Installed packages | bacon/bacon-qr-code@1.0.3, barryvdh/laravel-debugbar@v3.1.3, barryvdh/laravel-ide-helper@v2.4.3, barryvdh/reflection-docblock@v2.0.4, davejamesmiller/laravel-breadcrumbs@4.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/instantiator@1.1.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.7.0, fideloper/proxy@3.3.4, filp/whoops@2.1.14, fzaninotto/faker@v1.7.1, guzzlehttp/guzzle@6.3.0, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, hamcrest/hamcrest-php@v2.0.0, laravel/framework@v5.5.35, laravelcollective/html@v5.5.3, league/commonmark@0.17.0, league/csv@9.1.2, league/flysystem@1.0.42, maximebf/debugbar@v1.15.0, mockery/mockery@1.0, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, myclabs/deep-copy@1.7.0, nesbot/carbon@1.22.1, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, phar-io/manifest@1.0.1, phar-io/version@1.0.1, php-coveralls/php-coveralls@v2.0.0, phpdocumentor/reflection-common@1.0.1, phpdocumentor/reflection-docblock@4.3.0, phpdocumentor/type-resolver@0.4.0, phpspec/prophecy@1.7.5, phpunit/php-code-coverage@5.3.0, phpunit/php-file-iterator@1.4.5, phpunit/php-text-template@1.2.1, phpunit/php-timer@1.0.9, phpunit/php-token-stream@2.0.2, phpunit/phpunit@6.5.7, phpunit/phpunit-mock-objects@5.0.6, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.0, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, sebastian/code-unit-reverse-lookup@1.0.1, sebastian/comparator@2.1.3, sebastian/diff@2.0.1, sebastian/environment@3.1.0, sebastian/exporter@3.1.0, sebastian/global-state@2.0.0, sebastian/object-enumerator@3.0.3, sebastian/object-reflector@1.1.1, sebastian/recursion-context@3.0.0, sebastian/resource-operations@1.0.0, sebastian/version@2.0.1, swiftmailer/swiftmailer@v6.0.2, symfony/class-loader@v3.4.4, symfony/config@v4.0.4, symfony/console@v3.4.4, symfony/css-selector@v4.0.4, symfony/debug@v3.4.4, symfony/event-dispatcher@v4.0.4, symfony/filesystem@v4.0.4, symfony/finder@v3.4.4, symfony/http-foundation@v3.4.4, symfony/http-kernel@v3.4.4, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php70@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v3.4.4, symfony/routing@v3.4.4, symfony/stopwatch@v4.0.4, symfony/translation@v3.4.4, symfony/var-dumper@v3.4.4, symfony/yaml@v4.0.4, theseer/tokenizer@1.1.0, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.0, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2, webmozart/assert@1.3.0,  |

**Comment by JC5** [comment]
Indeed! I hope to finish up this weekend.

As for the encoding: unfortunately I have to _reliable_ way of detecting and converting file encoding. I cannot make sure that the file is actually encoding `X` so converting it to UTF-8 won't be smart.

I would suggest converting the file using Notepad++ or a similar tool.

**Comment by FrodeMMeling** [comment]
Ok, why not have the option to select encoding if you know it, then you convert it to UTF-8.
Then you can see in the preview if it is correct or not.. Or a live preview of result while changing encoding. I would never expect auto-detection of encoding, just option to override it on import and that its saved in configuration

**Comment by JC5** [comment]
It is a lot easier for me to assume UTF-8 and let users convert their files themselves.

**Comment by FrodeMMeling** [comment]
Ofcourse. But isn’t end users experience important?
If I have a user that I need to tell to take the excel from bank, open in notepad++, then save, then upload to firefly, chances of problems rise. I want this process as smooth as possible. I can fork firefly and fix it myself.

Få Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JC5** [comment]
The effort of building a file conversion routine that is usable, reliable and maintainable does not weigh up against the gain of having it, which is why I won't do it. You're the third one in five years who wants to import files with non-UTF8 encoding. Why would I spend my time building a feature to handle such files? Have you seen the backlog I have? :grin: 

And end user experience is important to me, of course it is. That's why I built the import process in the first place. I don't even use it myself. 

But please remember that this is open source software and my time is limited. Feel free to fork Firefly III and add the features you're missing. After all, that's half the point of open source software :wink:

Otherwise, take the time to convert the file yourself, or ask your bank to join the 21th century.

**Comment by FrodeMMeling** [comment]
This supports encoding.. I will try using this.
https://packagist.org/packages/monokakure/laravel-csv

Also I looked at this : https://quickadminpanel.com/blog/how-to-import-csv-in-laravel-and-choose-matching-fields/

I can ask the bank ofcourse.. I do not understand why it is like this.

**Comment by JC5** [comment]
:+1:

If you need help with the codebase or pointers or something like that, please let me know and I'll help where I can!

Assuming this has answered your question, I'm closing this issue. Don't hesitate to contact me.

**Comment by Obbi89** [comment]
Hey,

maybe you should at least check for valid utf-8 encoding with iconv or similar and show an error message in the browser stating that it is not valid utf-8 encoding.

Currently people just see an import error and that is not very helpful.

For converting, yes you cannot detect the input format, but you can validate a selected input format.
So it would be possible to give the user the option to select the input encoding and then do the conversion. But I wouldn't do that either.
But simply assuming it is utf8 is really not a good idea. At least validate there are no invalid bytes first.
This should reduce headache when people search for the error of an import.

**Comment by JC5** [comment]
That should not be difficult to do. It already happens at some places. Thanks for the suggestion!
