### ISSUE TITLE
Category report - accounts sum is tripled

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1213]
I am running Firefly III version 4.7.0

#### Description of my issue:

In category report there is table with list of accounts and sum in the last row. That sum is three times too large.

#### Steps to reproduce 

https://demo.firefly-iii.org/reports/category/1/1/20160101/20180331

#### Other important details (log files, system info):

Bug found on my local instance and reproduced on demo site.

**Comment by JC5** [comment]
I see it, nice find. Not sure if I can fix this in the current release.

**Comment by JC5** [comment]
Will be fixed in 4.7.2 :+1:

**Comment by skuzzle** [comment]
FYI: This currently (4.7.1.4) also happens in the tag report.
