### ISSUE TITLE
How do I put the due date on each split?

### ISSUE THREAD

**Issue by adailton-farf** [firefly-iii/firefly-iii#1215]
Hi I'm from Brazil. And I installed Firefly on my machine. The system is good, but I have some doubts.
I saw that you have a system to split the payment. But it has a detail, I could not put the expiration date. Are there any ways to put the expiration date on each split?

**Comment by JC5** [comment]
A split transaction is not meant to split transactions over a few days or months. I'm not sure what you need exactly?

**Comment by adailton-farf** [comment]
@JC5 Suppose I divide into 4 payments. I want each split to have a due date:
1st split - 04/15/2018
2nd split - 05/15/2018
3rd split - 06/15/2018
4th split - 07/15/2018

**Comment by JC5** [comment]
Ah I see. Unfortunately this is not possible with firefly iii.

**Comment by adailton-farf** [comment]
But has no plugin that can help?

**Comment by JC5** [comment]
No, sorry.
