### ISSUE TITLE
Problem with using Softaculous.

### ISSUE THREAD

**Issue by adailton-farf** [firefly-iii/firefly-iii#1217]
I'm trying to install Firefly 3 by Softaculous. But when it reaches 88% it appears:

"The following errors were found:

Could not make the query numbered: 29
MySQL Error No: 1071
MySQL Error: Specified key was too long; max key length is 1000 bytes "

can anybody help me? I need to install this system urgently.

**Comment by JC5** [comment]
It has to do with the MySQL database on your end. I've seen it before but I'm not sure what the cause is. What version of MySQL are you running?

**Comment by adailton-farf** [comment]
Thank you for your help. It was actually an internal problem, but I managed to resolve it.

**Comment by m4heshd** [comment]
> Thank you for your help. It was actually an internal problem, but I managed to resolve it.

Would you be willing to explain how?
