### ISSUE TITLE
Problem in translation. Instead of "ç" appears "?"

### ISSUE THREAD

**Issue by adailton-farf** [firefly-iii/firefly-iii#1218]
I installed Firefly III on my client machine. Well there are some characters in particular the "ç" that appear only "?". The problem is that it's not all the "c's" that appear. I wonder if there is a solution for this.

Screenshot: https://uploaddeimagens.com.br/imagens/capturar-png--5012

**Comment by JC5** [comment]
This happens when the server is not properly configured for UTF-8. It has happened in the past to some users but I haven't seen in in a while. I'm not sure what the correct solution it, but I know it is outside of Firefly III.

Are you running with Apache or nginx?

**Comment by adailton-farf** [comment]
Apache.

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/536

Could you run `locale -a` and place the output here?

**Comment by adailton-farf** [comment]
Unfortunately the server does not have the command line. I asked the call center and they said that this is a security measure, and so it was deactivated. And now what do I do?

**Comment by adailton-farf** [comment]
Infelizmente, o servidor não tem a linha de comando. Perguntei ao call center e eles disseram que esta é uma medida de segurança e, portanto, foi desativada. E agora, o que eu faço?

**Comment by JC5** [comment]
Go to your Firefly III page.

If you have Chrome: go to the menu and click "More tools" > "Developer toolbar". There should be a big block on the side of the browser or on the bottom. Select the network tab and refresh the page.

The top request looks a bit like this:

![screen shot 2018-03-09 at 20 17 11](https://user-images.githubusercontent.com/5889984/37225475-065e8022-23d7-11e8-94a1-189e17aabf9c.png)

What does it say at the red dot?

**Comment by adailton-farf** [comment]
Content-Type: text/html; charset=UTF-8

**Comment by adailton-farf** [comment]
Cache-Control: no-cache, private
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
Date: Fri, 09 Mar 2018 19:24:18 GMT
Keep-Alive: timeout=5, max=92
Server: Apache

**Comment by JC5** [comment]
OK, I am afraid I am running out of ideas for now. I have created something for the next release that can help us debug this problem. Because of the nature of the problem I am sure it is something on the web server but I cannot find out what it could be.

I am afraid you must suffer this problem for now while I think of something smart to do.

**Comment by adailton-farf** [comment]
I just tested the French language and it worked well. I just tested to see if it was not a problem with another language. But the problem seems to be specific in Portuguese.

**Comment by adailton-farf** [comment]
And I do not know the reason, but it seems that when I put in the Portuguese language, the chart stops working.

**Comment by adailton-farf** [comment]
What could i change?:

<?php
/**
 * config.php
 * Copyright (c) 2017 thegrumpydictator@gmail.com
 *
 * This file is part of Firefly III.
 *
 * Firefly III is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Firefly III is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Firefly III. If not, see <http://www.gnu.org/licenses/>.
 */
declare(strict_types=1);

return [
    'html_language' => 'pt-br',
    'locale'        => 'pt-br, pt_BR, pt_BR.utf8, pt_BR.UTF-8',
    'month'         => '%B %Y端',
    'month_and_day' => '%e de %B de %Y',
    'date_time'     => '%B %e, %Y, @ %T',
    'specific_day'  => '%e %B %Y',
    'week_in_year'  => 'Semana %W, %Y',
    'year'          => '%Y',
    'half_year'     => '%B %Y端',
];

**Comment by adailton-farf** [comment]
Another error that is appearing is:
iconv_substr (): Detected an illegal character in input string

**Comment by adailton-farf** [comment]
Modified: 'locale'        => 'pt_BR.utf8, pt_BR.UTF-8',
Original: 'locale'        => 'pt-br, pt_BR, pt_BR.utf8, pt_BR.UTF-8',

Hello, I have made some modifications, same as in the German version. It ran partially, left the "?". But there are some problems in other parts of the site now appears: Relatório financeiro padrão entre fevereiro 2018ü e março 2018ü. And the chart is not working yet.

**Comment by JC5** [comment]
```
iconv_substr (): Detected an illegal character in input string
```

It looks like the files on your webserver are not encoded in UTF8 or ASCII but something else. This is causing the problems. The web hoster might be able to fix this.

**Comment by JC5** [comment]
```
iconv_substr (): Detected an illegal character in input string
```

It looks like the files on your webserver are not encoded in UTF8 or ASCII but something else. This is causing the problems. The web hoster might be able to fix this.

**Comment by adailton-farf** [comment]
I was able to solve the problem.
The problem was in the date format, when it is in Brazilian format it does not work. But when it's in American format it works.
See the following changes:

<? php
/ **
 * config.php
 * Copyright (c) 2017 thegrumpydictator@gmail.com
 *
 * This file is part of Firefly III.
 *
 * Firefly III is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Firefly III is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Firefly III. If not, see <http://www.gnu.org/licenses/>.
 * /
declare (strict_types = 1);

return [
    'html_language' => 'pt-Br',
    'locale' => 'pt_BR.utf8, pt_BR.UTF-8', altered version
    'month' => '% B% Y',
    'month_and_day' => '% B% e,% Y',
    'date_time' => '% B% e,% Y, @% T',
    'specific_day' => '% and% B% Y',
    'week_in_year' => 'Week% W,% Y',
    'year' => '% Y',
    'half_year' => '% B% Y',
    // 'locale' => 'en, pt_BR, pt_BR.utf8, pt_BR.UTF-8', original version
    // 'month' => '% B% Y 端',
    // 'month_and_day' => '% e of% B of% Y',
    // 'date_time' => '% B% e,% Y, @% T',
    // 'specific_day' => '% e% B% Y',
    // 'week_in_year' => 'Week% W,% Y',
    // 'year' => '% Y',
    // 'half_year' => '% B% Y 端',
];

**Comment by JC5** [comment]
I see what you mean. I never realized those characters were present. They would cause problems everywhere. 

I have fixed the characters. Thanks for getting to the bottom of this problem!
