### ISSUE TITLE
Error with requests and memory

### ISSUE THREAD

**Issue by adailton-farf** [firefly-iii/firefly-iii#1224]
Hi since yesterday, I noticed a strange error in Firefly III. The graphs are not displaying correctly, and the problem seems to be because of the number of requests that are made at one time. I would like to know if it is possible to do each request at a time, without overloading the memory, as this is hindering the performance of the system.
I even got the server log and see that:

[Sun Mar 04 14:37:14.689705 2018] [:error] [pid 27289:tid 139627507709696] (12)Cannot allocate memory: [client *MY IP*::51118] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:37:14.633443 2018] [:error] [pid 31937:tid 139627465746176] (12)Cannot allocate memory: [client *MY IP*::51123] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:37:14.573768 2018] [:error] [pid 27393:tid 139627440568064] (12)Cannot allocate memory: [client *MY IP*::51119] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:37:14.457610 2018] [:error] [pid 3134:tid 139627574851328] (12)Cannot allocate memory: [client *MY IP*::51112] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:37:14.445113 2018] [:error] [pid 27439:tid 139627474138880] (12)Cannot allocate memory: [client *MY IP*::51116] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:37:14.336266 2018] [:error] [pid 27289:tid 139627432175360] (12)Cannot allocate memory: [client *MY IP*::51108] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:37:14.304441 2018] [:error] [pid 27285:tid 139627440568064] (12)Cannot allocate memory: [client *MY IP*::51111] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:37:14.281504 2018] [:error] [pid 31937:tid 139627507709696] (12)Cannot allocate memory: [client *MY IP*::51110] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:37:14.279757 2018] [:error] [pid 27393:tid 139627574851328] (12)Cannot allocate memory: [client *MY IP*::51109] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:42.491833 2018] [:error] [pid 27393:tid 139627532887808] (12)Cannot allocate memory: [client *MY IP*::51062] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:42.358051 2018] [:error] [pid 27289:tid 139627549673216] (12)Cannot allocate memory: [client *MY IP*::51060] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:42.324540 2018] [:error] [pid 27285:tid 139627432175360] (12)Cannot allocate memory: [client *MY IP*::51061] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:42.264787 2018] [:error] [pid 27285:tid 139627549673216] (12)Cannot allocate memory: [client *MY IP*::51044] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:40.875916 2018] [:error] [pid 27478:tid 139627465746176] (12)Cannot allocate memory: [client *MY IP*::51040] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:40.801286 2018] [:error] [pid 31937:tid 139627415389952] (12)Cannot allocate memory: [client *MY IP*::51045] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:40.712324 2018] [:error] [pid 27301:tid 139627558065920] (12)Cannot allocate memory: [client *MY IP*::51047] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:40.667416 2018] [:error] [pid 27289:tid 139627448960768] (12)Cannot allocate memory: [client *MY IP*::51043] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:20.800082 2018] [:error] [pid 27285:tid 139627432175360] (12)Cannot allocate memory: [client *MY IP*::51025] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:20.683996 2018] [:error] [pid 27301:tid 139627398604544] (12)Cannot allocate memory: [client *MY IP*::51028] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:20.672429 2018] [:error] [pid 27393:tid 139627532887808] (12)Cannot allocate memory: [client *MY IP*::51027] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:20.620492 2018] [:error] [pid 31937:tid 139627558065920] (12)Cannot allocate memory: [client *MY IP*::51026] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:20.555566 2018] [:error] [pid 27393:tid 139627516102400] (12)Cannot allocate memory: [client *MY IP*::51020] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:20.454835 2018] [:error] [pid 27478:tid 139627415389952] (12)Cannot allocate memory: [client *MY IP*::51024] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:20.452381 2018] [:error] [pid 3134:tid 139627566458624] (12)Cannot allocate memory: [client *MY IP*::51023] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:20.407759 2018] [:error] [pid 27439:tid 139627406997248] (12)Cannot allocate memory: [client *MY IP*::51022] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/
[Sun Mar 04 14:36:20.376577 2018] [:error] [pid 27301:tid 139627558065920] (12)Cannot allocate memory: [client *MY IP*::51021] couldn't create child process: /usr/sbin/suphp for /home/viajandosem/public_html/firefly/public/index.php, referer: http://*MY WEBSITE*/firefly/public/

**Comment by JC5** [comment]
It seems your machine has run out of memory.

**Comment by JC5** [comment]
Sorry, that was not your question. You realized that already.

There is not much I can do I'm afraid :(

**Comment by adailton-farf** [comment]
I need something to take so long to make the requisition. For example, the system make one request and it takes 5 seconds to do another, you see?

**Comment by JC5** [comment]
Checking if the request was a success from Firefly III would only make it slower. Plus, there is no guarantee it would work the second time.

If I understand correctly, you have a machine that is not very fast, but you still wish to run Firefly III on it?

**Comment by adailton-farf** [comment]
It is not a slow machine. The problem is, I do not know how it overloading.
I think it would work for the second time, because when I go through Chrome and click replay, instead of the 500 error, the 200 answer appears.

**Comment by adailton-farf** [comment]
I think the problem lies in the fact that the system makes quite a few requests at once. What I was thinking is like this:

1- Make each request at a time.
2- Or when you give an error such as "500", the server tries again to make the request.

**Comment by JC5** [comment]
I see from your errors that Firefly III is doing to much at once. How much memory is available in the machine?

**Comment by adailton-farf** [comment]
Physical memory:
512 MB
Virtual memory:
1GB

**Comment by JC5** [comment]
That is not enough I'm afraid. The demo server has 1.7, which is pretty much minimum.

What database system are you using?

**Comment by adailton-farf** [comment]
I am using the MySQL database.
It's okay that it has very little memory, but in the case there I think if I had a script or a structured plugin I would get it.
Is there any way or trick to make the requisitions take time to happen? Do not say a long delay. But a delay of seconds, not to get too crowded.

**Comment by JC5** [comment]
I don't think so, sorry.

**Comment by adailton-farf** [comment]
It seems that the charts consume a lot of server memory. Is there any way they do not consume so much? Because there are some charts that appear normally, but others do not appear.

**Comment by adailton-farf** [comment]
If you have a function that leaves simple, because it does not need so much just showing the chart is already good, it would get better.
Do not have any PHP settings that I can make to work on my server?

**Comment by JC5** [comment]
It is always my goal to optimize the code. However, sometimes there is a choice between code complexity (making the charts less heavy) and code maintainability (making the charts more heavy).

I try strike a balance between these two. It is not always possible to optimize.

For your server, 512MB (or 1GB virtual) is simply very little. You can try to change some of the PHP settings. [Drupal](https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements#memory) has a very nice list. 

Know that most charts are cached, so the second time they load it should be faster.

**Comment by adailton-farf** [comment]
I was able to solve the problem by changing some parts of the code.
How can I send these codes to you, so that you can study them to implement in the future?

**Comment by JC5** [comment]
You can send them by mail, that would be easiest. Use thegrumpydictator@gmail.com

**Comment by JC5** [comment]
If you prefer not to use email, create a Gist at [gist.github.com](https://gist.github.com/)
