### ISSUE TITLE
Category overview in default report shows no income.

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1226]
I am running Firefly III version 4.7.1.3 

The default financial report does not show income. At all. In this case, in the report for a particular category (income), all transactions are in place, the amount is correct.

![3](https://user-images.githubusercontent.com/520760/36965715-83dfc660-206b-11e8-862c-4a5bfda3b09b.jpg)

**Comment by JC5** [comment]
Confirmed, will be fixed in the next release. Thx for reporting :)

**Comment by Nik-vr** [comment]
ok. Thank!

**Comment by JC5** [comment]
I've just released 4.7.1.4. The issue should be fixed.

**Comment by Nik-vr** [comment]
In 4.7.1.4 all is OK. Thank!
