### ISSUE TITLE
Incorrect time in the logs.

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1227]
I am running Firefly III version 4.7.1.3 

The time of operations and errors fixed in the logs (/storage/logs/*.log) does not take into account the time zone set on the server. The time in the logs is written in the UTC, whereas in the server settings the UTTC +3 (Moscow) is specified. Because of this, it is inconvenient to look for errors in the logs.
Perhaps somewhere else time is used that does not include time zones?

**Comment by JC5** [comment]
I will make a note to make this configurable in the next release.

**Comment by Nik-vr** [comment]
ok!

**Comment by JC5** [comment]
Please see the updated `.env.example` file in 4.7.1.4.

**Comment by Nik-vr** [comment]
It's work! Thank!
