### ISSUE TITLE
Change default start & end date displayed

### ISSUE THREAD

**Issue by wouterDeneyer** [firefly-iii/firefly-iii#1230]
I am running Firefly III version 4.7.1

I love the app! 

However, I'd like to make a feature request. 
Our salaries get paid in the last week of the month. (so somewhere between the 23th and the 30th). Firefly periods default to calendar months. This means that 99% of the time, I have to manually adjust the time displayed from 23th of last month, untill 23th of current month. 
Is there a possibility to change the default startdate & enddate? 
![image](https://user-images.githubusercontent.com/5738736/36995703-1351449c-20b5-11e8-8a27-03c162f14ead.png)

Thanks!

**Comment by JC5** [comment]
You're touching one of the primary reasons I started building Firefly III. I lived from paycheck to paycheck, and not from month to month.

I strongly recommend [you do what I did](http://firefly-iii.readthedocs.io/en/latest/about/grand-theory.html).

So the answer is no, unfortunately.

**Comment by wouterDeneyer** [comment]
Okay, clear! 
We'll try it for sure!

**Comment by JC5** [comment]
It’s massively useful, I really recommend it. I saved like 10, 15% without even trying. 

First month will suck though, having to cover those extra days.
