### ISSUE TITLE
Net worth report

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1231]
I have multiple accounts, some with a few euros, some with a few hundreds, and one with an overdraft. 

The sum of all accounts is somewhere above zero. Is it possible to create a report of how my total net worth changed during the past years?

I’d like to see if my status is declining or not, how drastically, or if I am doing better this month in comparison to the last period.

**Comment by JC5** [comment]
I believe the default report includes such a chart. Is that not exactly what you're looking for?

https://demo.firefly-iii.org/reports/default/1,32,33,2,3/20170101/20171231

**Comment by gavu** [comment]
You're right, I just missed the big net worth chart in the middle of the page. 

FYI, the link you posted above, just says "Be right back"
