### ISSUE TITLE
Errors when running on the WAMP server

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1233]
I am running Firefly III version 4.7.1.4 

When you start Firefly on the WAMP-server does not work chart, there is no data in several blocks on the main page. Also there are strange symbols instead of delimiters.
When you transfer the same copy Firefly to a virtual LAMP server, all these problems disappear.

![2](https://user-images.githubusercontent.com/520760/37078215-62ef99dc-21ef-11e8-8cbe-711b6526d657.jpg)

**Comment by JC5** [comment]
Check the log files. I suspect you see 500 errors mentioning "UTF-8". Is this the case?

**Comment by Nik-vr** [comment]
Log from Chrome:

[fin.loc-1520405955041.log](https://github.com/firefly-iii/firefly-iii/files/1788256/fin.loc-1520405955041.log)

Log from FF3:
[ff3-apache2handler-2018-03-07.log](https://github.com/firefly-iii/firefly-iii/files/1788260/ff3-apache2handler-2018-03-07.log)

**Comment by JC5** [comment]
It seems the files are corrupted. Either windows or WAMP is doing this. There’s not much I can do.

**Comment by adailton-farf** [comment]
Although it is not official support, I can try to help you. I had this same problem on my client's computer. Then I discovered that the problem actually is that I was using PHP 7.2. When I put PHP 7.1 the graphics returned normally.

**Comment by Nik-vr** [comment]
I use the PHP 7.1. But today I conducted an experiment and temporarily switched the server to PHP 7.2 - no changes occurred, the problem persisted. Perhaps some error in the configuration of my local server (I'm using https://ospanel.io/)

**Comment by JC5** [comment]
I suspect that ospanel is configured to expose the files as Windows encoding or Russian encoding. This is normally not a problem but ironically this breaks the Russian translations. 

The errors point to files with Russian characters that get encoded in the wrong way. 

I’m pretty sure that ospanel can be configured to use utf8.

I’ve already verified that the files are correct on this side.

**Comment by Nik-vr** [comment]
I check all config (Apach and PHP) on my local servet - server use  utf8. Any other script work without errors. When I install Firefly first time (in Dec 2017, version 4.6.x?), it's also work good.

**Comment by JC5** [comment]
It's about the content of the files. All files are distributed as utf8 or ascii but it's possible to change that once you install the files. Once you do that, they will break. That is what the error is about.
