### ISSUE TITLE
How does the "Left to spend" block work?

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1234]
I can not understand how the "Left to spend" works. I created budgets, set the available amount for the current period. But in the block "Left to spend" zero.
In past periods, I made income, there is money for budget planning.
Also, it is impossible to change the "available amount" if it pointed it wrong (I press the button again, enter the amount, I'll let you in, but nothing happens).

![1](https://user-images.githubusercontent.com/520760/37094634-808c5716-2224-11e8-9e5b-7afde3b1969f.jpg)

I checked the work of this block on your demo site. There's a "Left to spend" block. A change in the amount works strange (in one place the amount changes, in the other it remains the same).

![2](https://user-images.githubusercontent.com/520760/37094675-a462f6cc-2224-11e8-97f3-d42e72da602e.jpg)

PS. I use SQLite, maybe the problem is again because of this?

**Comment by JC5** [comment]
Let's see.

1. The "amount budgeted" on the left side of the two bars is the sum of the budget amounts you have set. On the demo site, this is usually 1500,-.
2. The "amount available" is something you can set yourself to tell yourself how much money you will have this month.
3. If you add more money to your budgets than "amount available" the top bar will change color (you are budgeting more than you have).
4. If you add less money to your budgets, it will not fill the entire top bar.

So the top bar should normally be blue for 100%.

The bottom bar ("spent between 1 mar and 31 mar") will fill according to how much you spend.

The "left to spend" on the front page is simply: the amount available (top bar right) minus the amount spent (bottom bar). The amount spent is only taken from transactions with a budget.

**Comment by Nik-vr** [comment]
Hmm ... I created several budgets, indicated the amount. On the left side, the top bar displays the amount of these budgets. OK. The top bar is red. Next, I'm trying to set "amount available". And I click on the button, enter the amount in the pop-up window, click "Update amount". And nothing happens. The figure to the right of the top bar remains zero. Bug or do I still do not understand something?
With the  bottom bar everything is clear, it works and the principle of its operation is clear.

**Comment by JC5** [comment]
Probably a bug. I will test with SQLite.

**Comment by JC5** [comment]
SQLite bug. Will be fixed in the next release.

**Comment by Nik-vr** [comment]
OK! Thank!

**Comment by Nik-vr** [comment]
PS. I have made changes to the code manually, everything works fine! Thank you!
