### ISSUE TITLE
Error when bulk deleting transactions

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1237]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
Error when bulk deleting transactions

#### Steps to reproduce 
Select multiple transactions in the details of a tag, and try to delete them.

Exists on demo site as well.

#### Other important details (log files, system info):
Firefly III v4.7.1.4 ran into an error: Call to undefined method FireflyIII\Repositories\Journal\JournalRepository::delete()

The error was of type "Symfony\Component\Debug\Exception\FatalThrowableError".

The error occured on/at: Fri, 09 Mar 2018 19:17:07 +0000.

This error occured in file /var/www/domain.com/public_html/app/Http/Controllers/Transaction/MassController.php on line 106 with code 0.

#0 [internal function]: FireflyIII\Http\Controllers\Transaction\MassController->destroy(Object(FireflyIII\Http\Requests\MassDeleteJournalRequest))
#1 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#2 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('destroy', Array)
#3 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Controllers\Transaction\MassController), 'destroy')
#4 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#5 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#6 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /var/www/domain.com/public_html/app/Http/Controllers/Transaction/MassController.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): FireflyIII\Http\Controllers\Transaction\MassController->FireflyIII\Http\Controllers\Transaction\{closure}(Object(Illuminate\Http\Request), Object(Closure))
Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
Nice find! I have pushed a fix that will be included in the next release :+1:
