### ISSUE TITLE
JournalRepository::getMetaField() must be of the type string or null, object returned

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1238]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
Trying to create a split for a transaction that has a linked transaction.

#### Steps to reproduce 
Create a new withdrawal. Create a link to a refund transaction. Try to create a split for the first one.

I can't reproduce this on the demo site, sorry.
This is how my transaction (the one I try to split), looks like.

![image](https://user-images.githubusercontent.com/441924/37226898-b686cbae-23db-11e8-822d-6d3e15fc92d5.png)

#### Other important details (log files, system info):
Firefly III v4.7.1.4 ran into an error: Type error: Return value of FireflyIII\Repositories\Journal\JournalRepository::getMetaField() must be of the type string or null, object returned

The error was of type "Symfony\Component\Debug\Exception\FatalThrowableError".

The error occured on/at: Fri, 09 Mar 2018 19:43:52 +0000.

This error occured in file /var/www/domain.com/public_html/app/Repositories/Journal/JournalRepository.php on line 386 with code 0.

#0 /var/www/domain.com/public_html/app/Http/Controllers/Transaction/SplitController.php(201): FireflyIII\Repositories\Journal\JournalRepository->getMetaField(Object(FireflyIII\Models\TransactionJournal), 'interest_date')
#1 /var/www/domain.com/public_html/app/Http/Controllers/Transaction/SplitController.php(107): FireflyIII\Http\Controllers\Transaction\SplitController->arrayFromJournal(Object(Illuminate\Http\Request), Object(FireflyIII\Models\TransactionJournal))
#2 [internal function]: FireflyIII\Http\Controllers\Transaction\SplitController->edit(Object(Illuminate\Http\Request), Object(FireflyIII\Models\TransactionJournal))
#3 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('edit', Array)
#5 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Controllers\Transaction\SplitController), 'edit')
#6 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#7 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#8 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/domain.com/public_html/app/Http/Controllers/Transaction/SplitController.php(84): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): FireflyIII\Http\Controllers\Transaction\SplitController->FireflyIII\Http\Controllers\Transaction\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/domain.com/public_html/app/Http/Controllers/Controller.php(106): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
I never actually tried that! :grin:

Thanks for the expanded bug report. I'll check it out and get back to you.

**Comment by JC5** [comment]
I've added some code to prevent this. It was possible although I was not able to reproduce it. I had to "force" the issue.

Could you check your database? In the table `journal_meta`, find the entry with `transaction_journaL_id` and whatever the ID is of the withdrawal.

If it doesn't seem to be sensitive information, could you share the `name` + `data` of those entries?

**Comment by zjean** [comment]
Hi,
Thanks!
I had a look in the journal_meta table, and found two rows that have the transaction_journal_id that's the same as the id in the url of the screenshot (/transactions/show/_1863_)

This is the data:
importHash: "6bd2dfa061bb9f73796c28d595dc2372dbfdc10a20c8d594341e9a6d4919066b"
interest_date: "2018-02-07T00:00:00+00:00"

Does that make sense?

**Comment by zjean** [comment]
I cleared the cache (`php artisan cache:clear`) and that fixed the problem somehow.

**Comment by JC5** [comment]
Very strange. I've changed some things internally and it should happen no longer, cache or no cache. If you run into other issues, don't hesitate to open an issue!
