### ISSUE TITLE
Extra Step needed for installation

### ISSUE THREAD

**Issue by TheGammelgalopper** [firefly-iii/firefly-iii#1242]
I am running Firefly III version 4.7.1.4

#### Description of my issue:

With both of my firefly installations I had to still change the `DocumentRoot` in `/etc/apache2/sites-enabled/000-default.conf` to `/var/www/firefly-iii/public` to not get a 404 error.

This is not documented in the guide.

**Comment by JC5** [comment]
Hi, thanks for reporting this! You're right that this isn't included in the guide. 

I won't be adding it, I'm afraid. I used to have custom instructions for Apache and nginx but it became a massive list of options, possibilities, buttons and checks users *could* do when installing Firefly III. 

This 15-page installation guide only confused users giving me even more issues to resolve.

So instead, I now explain the important steps for Firefly III, and allow users to search the web themselves for custom instructions for their own system.

**Comment by TheGammelgalopper** [comment]
Ah ok, totally makes sense! Now this issue is in the issues :D And other users can find it!

Would you mind, if I created an installation script for one specific OS?

**Comment by JC5** [comment]
Not at all! Just create a gist on gist.github.com and I can refer to it from the FAQ.

**Comment by TheGammelgalopper** [comment]
Great! Will do so, when I get my own installation working! Looking forward to this!
