### ISSUE TITLE
Transferring the database to new installation with new version: How To?

### ISSUE THREAD

**Issue by TheGammelgalopper** [firefly-iii/firefly-iii#1243]
I am running Firefly III version 4.7.1.4

#### Description of my issue:

I did run a Firefly 4.6.5 installation for some time now. Although I had quite a few problems setting it up, it then worked without any problems...
Now I changed hosts and installed 4.7.1.4 successfully. But I would like to have my old database...

I already tried the import/export function in the webgui... There I was lost at step 3/4 (matching values). I tried my best, but it just threw errors...

I then copied my old database and inserted it into the new machine. Same database names and everything. But that didn't work either...

I know that there has to be done some stuff with php artisan xxx...

And I guess the .env file also plays a role... but they are so different between the two versions, so I didn't just want to copy them...

**Comment by JC5** [comment]
To safely migrate (make sure you have backups!) you can do the following:

- Create a new (empty) installation of Firefly III.
- Copy your old `.env` file into the new installation. This will not break anything.
- Enter the following commands on your command line:

```
php artisan migrate --seed
php artisan firefly:upgrade-database
php artisan firefly:verify
```

That should work just fine! :+1:

If not, let me know!

**Comment by TheGammelgalopper** [comment]
wait, what black sorcery is this? I just copy the .env file and all my data comes with it? This is cool!

BUT sadly it didn't work... when I try logging in, it says that credentials dont much and if I try to create a new account it gives me this error: 'Could not decrypt preference #1'

**Comment by JC5** [comment]
Try this command as well.

```
php artisan cache:clear
```

The data in your database is encrypted with a key that resides in the .env file. So copying the .env file should prevent that error from happening.

**Comment by JC5** [comment]
Make sure you copy the .env file over any existing .env files in the new installation.

**Comment by TheGammelgalopper** [comment]
yep did that, no change

I made sure to delete the .env in my new installation beforehand and then copied over the old .env

But wait this would mean that I also have to copy the database doesn't it? Do I copy the database before running those commands ('php artisan migrate --seed, php artisan firefly:upgrade-database, php artisan firefly:verify'), or after?

**Comment by JC5** [comment]
Yes, sorry. The database must be present as well. It's not that magical yet :wink:

**Comment by TheGammelgalopper** [comment]
You are my true hero! It worked!

So to sums things up (for everybody who might have the same problem in the future...):

What to do when installing firefly on a new system:

1. create the default installation, but this 'composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii <latest>' should be the last step, but make sure there is already a database in mysql with the same names as in your last installation. DON'T run the the php artisan commands yet!!!

2. go to '/var/www/firefly-iii'

3. sudo rm -v .env (for deleting the new .env)

4. copy over the old .env and insert the old database with 'mysql -u *user* -p *database-name-current system* < *backup-database-name*' (your database can be exported with the following command: 'mysqldump -u *user* -p *database-name* > *backup-database-name*')

5. then run these commands: 'sudo php artisan migrate --seed', 'sudo php artisan firefly:upgrade-database', 'php artisan firefly:verify' (you migh need to run a 'sudo php artisan cache:clear' inbetween)

**Comment by TheGammelgalopper** [comment]
so these subdirs throw errors:

- /accounts/assets
- /accounts/expense
- /accounts/revenue
- /categories/list/no-category
- /transactions/transfers

Error looks like so:

(2/2) Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Unable to write in the cache directory (/var/www/firefly-iii/storage/framework/views/twig/0e).") in "/var/www/firefly-iii/resources/views/accounts/index.twig" at line 35.

**Comment by JC5** [comment]
Make sure that the directory `/var/www/firefly-iii/storage/framework/views` is empty (so delete `twig` as well).

Run from `/var/www/`:

```
sudo chown -R www-data:www-data firefly-iii
sudo chmod -R 775 firefly-iii
```

It has to do with system access rights in the new installation.

**Comment by TheGammelgalopper** [comment]
yes, sorry to bother you, the minute I hit comment, it hit me as well :D "unable to write" sounds an awful lot like missing rights...

**Comment by pedrom34** [comment]
This should be in the FAQ!

Thanks a lot @TheGammelgalopper
