### ISSUE TITLE
Adding today line on account details graph

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#1244]
I am running Firefly III version 4.7.1.3 

#### Description of my issue:
I think it could be nice to have a today line on account details graph (accounts/show/N) - just like in main dashboard graph.

**Comment by JC5** [comment]
Currently working on #1214, will pick this up as well. :+1:

**Comment by JC5** [comment]
Visible on the [demo site now](https://demo.firefly-iii.org/accounts/show/1).
