### ISSUE TITLE
Overspent budget overview in dashboard

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1247]
I am running Firefly III version 4.7.1.4

The dashboard currently shows the amount of money which is left for spending according to the budgets I defined. It would be great if when I overspent my budgets, this box would become red and show the amount I overspent.

**Comment by JC5** [comment]
It does, right?

![screen shot 2018-03-12 at 17 08 34](https://user-images.githubusercontent.com/5889984/37295268-066f12f0-2618-11e8-9369-417f782eafd7.png)

**Comment by skuzzle** [comment]
Yes, but I meant the 'Left to spend' box at the top:

![image](https://user-images.githubusercontent.com/317179/37295599-db3f9a22-2618-11e8-8fd1-d54b6679686e.png)

It currently only shows that I f*cked up my spendings, but not how much I overspent in total. This is currently only shown in the second progress bar on the budget page. I believe it would be great to have this information available at quick glance.

**Comment by JC5** [comment]
Ah that one! No, it doesn't. I can make it show the amount when you hover? That would be the cleanest in terms over user interface.

**Comment by skuzzle** [comment]
Hmm. One could consider simply displaying the negative left to spend amount? Not sure though whether this would be best in terms of user experience

**Comment by JC5** [comment]
Just thinking out loud. I just realized I could change the text to match (“overspent”).

**Comment by JC5** [comment]
Box will turn red and show the overspent amount in 4.7.2. You can try this on [the demo site](https://demo.firefly-iii.org/). Make sure you give the big expense a budget for it to work.
