### ISSUE TITLE
Summing in the Amount field

### ISSUE THREAD

**Issue by liquidblasted** [firefly-iii/firefly-iii#1250]
Hi, this is just a suggestion.

Say, I spent 100$ in a supermarket - 17.5$ for alcohol or housewares, and 82.5$ for food.
I want to divide this summ separately as food and alcohol expenses for more detailed reports.

So, 1stly I enter "17.5" expense for alcohol,
and 2ndly, for food I enter "100-17.5" in Amount field and automaticaly have 82.5 in transaction after submitting.

That would be really convenient!

**Comment by JC5** [comment]
It's been suggested in the past (https://github.com/firefly-iii/firefly-iii/issues/535), but it's very complicated to build for a small use case. I'm sorry, but you must do the calculations from the top of your head ;).

**Comment by liquidblasted** [comment]
Ok I understand, that's sad but thanx for eplanation and cool work anyway :)
