### ISSUE TITLE
Droplists of Expense, Revenue accounts and Categories

### ISSUE THREAD

**Issue by liquidblasted** [firefly-iii/firefly-iii#1251]
I am running Firefly III version 4.7.1.4 

This is a suggestion - would be more convenient if you can select Expense, Revenue accounts and Categories from an expanding droplist also as Asset accounts while creating any kind of transaction.

**Comment by JC5** [comment]
They're on a free-format field because you can add new ones if you want to. A select list would block that feature.

If you start typing, Firefly III will suggest new entries.

**Comment by liquidblasted** [comment]
Maybe as an option in settings in future releases? Sometime just can't remember how I named such items (and if they exists already) and have duplicates with synonym words

**Comment by t-rascal** [comment]
+1 we find the dropdown functionality more useful than free-format. I end up creating similarly-named (but different) duplicate accounts.

**Comment by Obbi89** [comment]
A possible solution would be to add datalist to the free form textfield that would help people with supporting browsers for now. (see https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist)

**Comment by JC5** [comment]
I'll check it out, thanks!
