### ISSUE TITLE
Issues Hosting Behind NGINX

### ISSUE THREAD

**Issue by Zorbeen98** [firefly-iii/firefly-iii#1253]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
Source code continues to point to local server and uses http rather than https.

#### Steps to reproduce 
I have Firefly installed on Apache using HTTP. 
I then have a NGINX reverse proxy server that's open to to the internet and has HTTPS configured on it.

When I browse to https://external.domain.com/firefly i get to a login page with no CSS.
When i look at the Chrome console, there's various errors complaining that my content security policy does not allow style sheets from http://localdns/firefly/...

Thanks in advance for any help!

See below for config files.

#### Other important details (log files, system info):

NGINX Proxy File (Just the Firefly part.)
-----------------------------------------------------------
```
location /firefly 
{
    proxy_pass http://localdns/firefly;
}
```

Apache File (Just the Firefly part.)
-----------------------------------------------------------
```
Alias /firefly /var/www/firefly/firefly-iii/public
<Directory /var/www/firefly/firefly-iii/public>

        AllowOverride All

</Directory>
```

.env File
-----------------------------------------------------------
```
APP_ENV=local
APP_DEBUG=false

SITE_OWNER=[omitted]

APP_KEY=[Omitted]

TZ=UTC

APP_URL=https:https://external.domain.com/firefly
TRUSTED_PROXIES=**

DB_CONNECTION=mysql
DB_HOST=[omitted]
DB_PORT=[omitted]
DB_DATABASE=[omitted]
DB_USERNAME=[omitted]
DB_PASSWORD=[omitted]

APP_LOG=daily

APP_LOG_LEVEL=notice

CACHE_DRIVER=file
SESSION_DRIVER=file

COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false

MAIL_DRIVER=smtp
MAIL_HOST=[omitted]
MAIL_PORT=[omitted]
MAIL_FROM=[omitted]
MAIL_USERNAME=[omitted]
MAIL_PASSWORD=[omitted]
MAIL_ENCRYPTION=[omitted]

SEND_REGISTRATION_MAIL=true
SEND_ERROR_MESSAGE=true

MAPBOX_API_KEY=

ANALYTICS_ID=

USE_ENCRYPTION=true

APP_NAME=FireflyIII
BROADCAST_DRIVER=log
QUEUE_DRIVER=sync
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
CACHE_PREFIX=firefly
SEARCH_RESULT_LIMIT=50
EXCHANGE_RATE_SERVICE=fixerio
PUSHER_KEY=
PUSHER_SECRET=
PUSHER_ID=
DEMO_USERNAME=
DEMO_PASSWORD=
IS_DOCKER=false
IS_SANDSTORM=false
IS_HEROKU=false
```

**Comment by JC5** [comment]
For https, use this in nginx.

```
RequestHeader set X-Forwarded-Proto "https"
```
Also, check out these instructions (use Google translate) from user @setevoy2: https://rtfm.co.ua/firefly-iii-domashnyaya-buxgalteriya/

**Comment by Zorbeen98** [comment]
Fixed! 

Not quite what you said, I think what you suggested might be for Apache reverse proxy;  but the article you linked pointed me in the right direction. 

I simply changed my NGINX file from this: 

```
location /firefly 
{
    proxy_pass http://localdns/firefly;
}
```

To This: 

```
location /firefly 
{
   add_header X-Forwarded-Proto "https";
   proxy_set_header Host $host;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_pass http://localdns/firefly;
}
```

Thanks for your help and your work on the project!

**Comment by triDcontrols** [comment]
Never mind, I reloaded the configuration and it didn't work, but restarted nginx and works now.
