### ISSUE TITLE
How to handle transactions with expenses and multiple deposits (a paycheck)?

### ISSUE THREAD

**Issue by ytjohn** [firefly-iii/firefly-iii#1256]
I'm just started testing out firefly-iii today. I am really liking it. Currently I'm using Quicken, though I have used ledger/hledger/beancount tools in the past. I like the double-entry method they provide, but find them hard to keep up with and to find things like how much money I have left.

I'm trying to figure out how to enter a paycheck and split it. I tried as a deposit, but that just lets you select multiple revenuse sources. I'd like to track what I pay in taxes, insurance, and establish transfers from my revenue source to the various accounts it hits (401k, HSA savings, checking).

I had started to ask this in #1255, but after some more experimentation, I realize I have a much bigger question. I think selecting destination accounts in a split is the way to go, but perhaps I'm looking at this from the perspective of other tools.

An example paycheck as a gross pay (say $3000) and then expenses are paid out of it like Taxes and Insurances. Additionally deposits are made into 1 or more accounts - a 401k savings account, an FSA or HSA medical savings account, and finally, a net amount is made into your checking or savings accounts. 

Expenses:

| Expense Account  | Amount | Category |
|:-----------------|-------:|----------|
| Federal Income Tax | 210 | Federal Taxes |
| Social Security Tax | 180| Federal Taxes |
| State Income Tax | 101 | State Taxes |
| Medical | 73.35  | 
| Dental   | 17.50 | Medical Insurance |
| Supp Life | 0.78 | Life Insurance |

Transfers:

| Destination Account | Amount |
|:--------------------|-------:|
| Dep Care/FSA        | 153.85 |
| HSA Savings         | 115.38 |
| 401k Regular        | 700.00 | 
| 401k Loan           | 200.00 | 
| Checking            | 2000.00|
| Checking 2          |  150.00|

I took an example of a paycheck transaction from [beancount](http://furius.ca/beancount/) which is a [ledger like](http://plaintextaccounting.org/) tool.

```
2017-12-29 * "Paycheck"
    Income:Employer  -xxxx.xx USD
    Expenses:Tax:FederalIncome xxx.xx USD
    Expenses:Tax:Medicare xx.xx USD
    Expenses:Tax:XX xxx.xx USD
    Expenses:Tax:Township xx.xx USD
    Expenses:Tax:XX-SUI x.xx USD
    Expenses:Insurance:Basic-Life xx.xx USD
    Expenses:Insurance:Child-Life x.xx USD
    Expenses:Insurance:Dental xx.xx USD
    Assets:Savings:HSA xxx.xx USD
    Assets:Savings:FSA-Dependent xxx.xx USD
    Assets:Savings:FSA-Limited xx.xx USD
    Expenses:Insurance:Life-Plus xx.xx USD
    Expenses:Insurance:Medical xx.xx USD
    Assets:Savings:401k xxx.xx USD
    Expenses:Insurance:Life-Spouse x.xx USD
    Expenses:Insurance:Life-std-buyup xx.xx USD
    Expenses:Insurance:Life-Supplemental xx.xx USD
    Expenses:Insurance:Vision x.xx USD
    Liabilities:Loan401k xxx.xx USD
    Assets:Daily xxx.xx USD
    Assets:Checking-Joint xxxx.xx USD
```

**Comment by JC5** [comment]
It's been asked before. Generally speaking, your paycheck is divided over several posts that can be positive and negative. Base salary, bonus, insurance, taxes, etc.

The short answer is that Firefly III can't (and won't) support the amount of detail you're looking for.

The reason you can split the way you can split right now is fairly simple: it focuses on transaction as you see it on your bank statement.

**Expenses** (groceries are a great example) can be split to distinguish food from drinks, from personal hygiene, etc. This reflects your bank statements (one line), but Firefly II can show the specifics.

**Income** can be split to come from multiple parties. It's still _one_ deposit (one lump sum) but you can split it into several parts. Base salary, bonus, reimbursements.

So the splits that you can make right now are based on the idea that it should come together in one place: your bank account. Either as a source of money (groceries) or as a destination (salary).

In your example:

> An example paycheck as a gross pay (say $3000) and then expenses are paid out of it like Taxes and Insurances. Additionally deposits are made into 1 or more accounts - a 401k savings account, an FSA or HSA medical savings account, and finally, a net amount is made into your checking or savings accounts.

It seems to me you receive one lump sum that you split yourself. This is represented in Firefly III as one deposit and then several transfers (or expenses).

If your employer already does some "splitting", these are multiple deposits that you could split even further with expenses and transfers.

However, Firefly III will not allow you to put this in one big fat transaction. Technically it's possible but that's not something that's going to make Firefly III any easier to use.

**Comment by ytjohn** [comment]
The more I research, the more aware I become of the difference between budgeting applications and personal finance/accounting applications. :) I get now that Firefly III is a budgeting application, concerned with managing how you handle your take home pay.

I'd like to clarify my question a bit for reference, but otherwise we can close this out. Just for a bit of clarification, FSA and HSAs are asset accounts  (checking/saving accounts, complete with a debit card) that you can pay medical and childcare expenses out of. Similarly, taxes are expenses I pay each towards out of each paycheck, and then a final amount (or refund) once a year. A 401k is like another asset/saving account, but I will admit it is less important in terms of a budget app because one shouldn't really factor that into their budgeting.

![image](https://user-images.githubusercontent.com/163156/37597343-9192ade6-2b55-11e8-9bd2-7428808df4a2.png)

That is 21 transactions. Most of them are expenses, while 5 of them are deposits hitting asset accounts (checkin 1, checking 2, hsa, fsa, 401k).

What seems to work in Firefly III, though it's not easy by any means, is to create an asset account "Paycheck Processing".  I can deposit a gross pay income into that, then perform all the expenses and transfer out of that. 

This was a bit time consuming and I made some mistakes in my data entry that were hard to reconcile. I wouldn't want to do it each paycheck, unless I had some sort of "clone group of transactions" or a bulk entry/edit screen that is similar in approach to how the split screen works. That displays a list of related, editable transactions and updates them all when you click the button.

**Comment by JC5** [comment]
I get what you're trying to do, and Firefly III isn't really made to handle this.

I wonder, why do you want a carbon copy of this overview? What's your endgame? Like you deduced yourself it's going to be tricky to do this in FF3 and when you mentioned that you'd like to clone the effort each time my question becomes "why?"

If you tell me what you want to learn from this screenshot that you don't already know I might be able to accomodate you.
