### ISSUE TITLE
Timeout on Transactions lists

### ISSUE THREAD

**Issue by Serjlee** [firefly-iii/firefly-iii#1257]
Hello, I'm a new user of this interesting project, but I encountered an issue stopping me from using it :(

I am running Firefly III version 4.7.1.4

#### Description of my issue:
PHP Timeout while getting list of Expenses or Revenues, with high CPU usage. There are no more than ~200 lines total, so I suspect there is something wrong in my setup.
PHP timeout is set to 30secs.

#### Steps to reproduce 

Have ~200 lines distributed between november 1 and january 31 (mostly expenses), filter by a range from today to last 6 months.
Clicking on any Transactions menu item causes a PHP timeout after 30(!) seconds

#### Other important details (log files, system info):
Running PHP 7.1 (w/ opcache), NGINX, Postgres 9.6
Using Redis as caching engine
System is a Vultr VPS with 1GB RAM

Debug information generated at 2018-03-14 21:51:16 UTC for Firefly III version **4.7.1.4**.:

| Variable | Content |
| --- | --- |
| FF version | 4.7.1.4 |
| FF API version | 0.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, daily |
| PHP version | 7.1.11-0ubuntu0.17.10.1 |
| Display errors | Off |
| Session start | 2017-10-01 00:00:00 |
| Session end | 2018-03-15 00:00:00 |
| Session first | 0017-10-10 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux luca-server 4.13.0-25-generic # 29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 |
| Interface | fpm-fcgi |
| UserID | 1 |
| DB drivers | pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, exif, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, barryvdh/laravel-debugbar@v3.1.3, barryvdh/laravel-ide-helper@v2.4.3, barryvdh/reflection-docblock@v2.0.4, davejamesmiller/laravel-breadcrumbs@4.2.0, defuse/php-encryption@v2.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.7.0, fideloper/proxy@3.3.4, filp/whoops@2.1.14, firebase/php-jwt@v5.0.0, fzaninotto/faker@v1.7.1, guzzlehttp/guzzle@6.3.0, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, hamcrest/hamcrest-php@v2.0.0, laravel/framework@v5.5.36, laravel/passport@v4.0.3, laravelcollective/html@v5.5.3, lcobucci/jwt@3.2.2, league/commonmark@0.17.0, league/csv@9.1.2, league/event@2.1.2, league/flysystem@1.0.43, league/fractal@0.17.0, league/oauth2-server@6.1.1, maximebf/debugbar@v1.15.0, mockery/mockery@1.0, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.23.0, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, php-coveralls/php-coveralls@v2.0.0, phpseclib/phpseclib@2.0.10, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, predis/predis@v1.1.1, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.0, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, sebastian/version@2.0.1, swiftmailer/swiftmailer@v6.0.2, symfony/class-loader@v3.4.5, symfony/config@v4.0.5, symfony/console@v3.4.5, symfony/css-selector@v4.0.5, symfony/debug@v3.4.5, symfony/event-dispatcher@v4.0.5, symfony/filesystem@v4.0.5, symfony/finder@v3.4.5, symfony/http-foundation@v3.4.5, symfony/http-kernel@v3.4.5, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php70@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v3.4.5, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v3.4.5, symfony/stopwatch@v4.0.5, symfony/translation@v4.0.5, symfony/var-dumper@v3.4.5, symfony/yaml@v4.0.5, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.2, vetruvet/laravel-phpredis@v1.0.4, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2, zendframework/zend-diactoros@1.7.1,  |

The logs shows those errors:
```
[2018-03-14 21:45:24] local.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"email":"-----","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 30 seconds exceeded at /var/www/money/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:35)"} 
[2018-03-14 21:47:47] local.ERROR: Exception is: {"class":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","errorMessage":"Maximum execution time of 30 seconds exceeded","time":"Wed, 14 Mar 2018 21:47:47 +0000","file":"\/var\/www\/money\/app\/Helpers\/Collector\/JournalCollector.php","line":255,"code":1,"version":"4.7.1.4"}  
[2018-03-14 21:47:49] local.ERROR: Swift Transport ExceptionExpected response code 250 but got code "530", with message "530 5.7.1 Authentication required
"  
[2018-03-14 21:47:49] local.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"email":"----","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 30 seconds exceeded at /var/www/money/app/Helpers/Collector/JournalCollector.php:255)"} 
```

**Comment by Serjlee** [comment]
After multiple attempts at using Postgres (which makes the app hangs with as few as 100 transactions), I re-imported everything into a MySQL DB with succcess.

As soon as I get the time, I'll prepare an importable CSV to help make the problem reproducible.

**Comment by JC5** [comment]
It's a pretty heavy query, I'll check it out. It could use some optimizations.

**Comment by JC5** [comment]
I've greatly reduced the number of queries used for this overview. That should already improve matters.

I'm closing this in preparation for the next release. Please let me know if you have an example file, or need help with something (else).
