### ISSUE TITLE
Date mismatch in piggy bank

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1258]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
I have a transaction that is dated to 1st of March and which is associated with a piggy bank. When viewing the piggy bank details, the transaction is displayed as dated on 27th of February:
![image](https://user-images.githubusercontent.com/317179/37447872-543a5b1c-2824-11e8-94e2-95aa2989bf02.png)

On the transfers page, the transaction is displayed correctly:
![image](https://user-images.githubusercontent.com/317179/37447920-81864388-2824-11e8-836d-517a8ba58489.png)

I know there were some issues regarding February dates but I'm not sure whether this one is already covered there.

**Comment by JC5** [comment]
Seems to work just fine on the demo site. Are you running SQLite?

**Comment by skuzzle** [comment]
No, I'm using MySQL.

**Comment by JC5** [comment]
So far I found nothing. Could you open the table `piggy_bank_events`? There should be an entry with the ID of the transaction. Is also has a date field. Is that date field wrong?

**Comment by skuzzle** [comment]
Yep, the field there is wrong. Maybe it is because it has been created with an older firefly version?

![image](https://user-images.githubusercontent.com/317179/37584439-c24ddda2-2b55-11e8-9d5f-afbbafce3b3c.png)

**Comment by JC5** [comment]
I've pushed a fix that will prevent it in the future. You can edit this one by hand. I hope it won't happen again!
