### ISSUE TITLE
Request: Apply rule to existing transaction

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1260]
I am running Firefly III version 4.7.1.4 

#### Description of my issue:

I created rules for almost everything, there's a huge list of rules to help me organize my transactions, however, the ATM-withdrawal transactions can't really be bundled in one rule, so every once in a while, I manually edit all withdrawals and "move" them to the "cash" budget and rename/tag them and so on. It would be really nice if one could manually apply a rule to the "unmatched" transaction.

**Comment by JC5** [comment]
You can manually apply rules to transactions, is there something missing in that particular mechanism?

**Comment by gavu** [comment]
Hi, sorry, here's what I had in mind:

`apply_rule`-button in transactions list or transaction details and a dropdown or autocomplete to select which rule you want to apply to that specific transaction
![apply_rule_transaction_list](https://user-images.githubusercontent.com/3742238/37584215-e9bf7450-2b54-11e8-9c73-5382ccae3765.png)

`apply_rule_to_ids`-input field where a user can add id's on which he wants to apply that specific rule, instead of date range and accounts
![apply_rule_rules_selection](https://user-images.githubusercontent.com/3742238/37584294-372f0278-2b55-11e8-81c4-0f010579a447.png)

It's just one of those shower-thoughts...

**Comment by JC5** [comment]
Ah I see. Quite a small use case I'm afraid, sorry!
