### ISSUE TITLE
CSV import breaks with headers and empty columns 

### ISSUE THREAD

**Issue by greghensley** [firefly-iii/firefly-iii#1262]
Firefly version 4.7.1.4

When importing a CSV file which includes a header row and empty columns, Firefly displays the "Be Right Back" message.

This appears to be a result of the way League uses the header column. It imposes the requirement that each column header be a unique value, which makes sense given the way it composes the header with each row. However, it treats blank columns as having a header value of "", and more than one blank column results in a collision.

Is my assumption correct that Firefly only uses column headers for display during the mapping phase of the import config? If that's the case, perhaps Firefly could abandon League's built-in header support and just extract the header row explicitly, for display.

**Comment by JC5** [comment]
That's true, and I'll check it out. Thanks!

**Comment by JC5** [comment]
Both double and empty headers are supported in the next release. :+1:
