### ISSUE TITLE
Import option to negate amounts

### ISSUE THREAD

**Issue by greghensley** [firefly-iii/firefly-iii#1263]
Firefly version 4.7.1.4 

For some of my credit card providers, the exported transactions indicate charges with _positive_ amounts and payments/credits as _negative_ amounts. Since Firefly treats all accounts as Assets, this results in charges being recorded as credits and credits as debits. Rather than have to remember to touch up the CSV each time I import, can you add an option to the import workflow to automatically negate transaction amounts? A new mapping type may work well for this (i.e., "Amount (negated)"), since you already have mapping types which treat amounts as absolute values ("Amount (debit)", etc).

**Comment by JC5** [comment]
I can add a checkbox before import to negate the values in the imported CSV. It won't be a role, they generally don't actually change the values you pick.

**Comment by JC5** [comment]
The next version of Firefly III will feature a "Amount (negated)" column that will allow this.
