### ISSUE TITLE
be right back 

### ISSUE THREAD

**Issue by ianxzone** [firefly-iii/firefly-iii#1264]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
Hello my firefly iii show error
HP Fatal error:  strict_types declaration must be the very first statement in the script in /home/user/public_html/doamin/index.php on line 24, referer: http://domain/public/
[Sat Mar 17 00:44:00 2018] [error] [client 182.253.163.72]

i was try all command in this issue

https://github.com/firefly-iii/firefly-iii/issues/889
Still problem
php artisan twig:clean
http://prntscr.com/isb27b3
php artisan view:clearphp artisan view:clear
http://prntscr.com/isb2c7

all chown file was true use.

#### Steps to reproduce 

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):
HP Fatal error:  strict_types declaration must be the very first statement in the script in /home/user/public_html/doamin/index.php on line 24, referer: http://domain/public/
[Sat Mar 17 00:44:00 2018] [error] [client 182.253.163.72]

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by ianxzone** [comment]
om debug mode showerro 
storage/logs/ff3-apache2handler-2018-03-17.log

but in the folder storage/logs its ff3-cli-2018-03-17.log

**Comment by ianxzone** [comment]
in error log storage/logs/ff3-cli-2018-03-17.log
2018-03-17 01:17:30] local.ERROR: Method TwigBridge\Command\Clean::handle() does not exist 
{"exception":"[object] (ReflectionException(code: 0): Method TwigBridge\\Command\\Clean::handle()
 does not exist at /home/user/public_html/domain/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:135)"}

**Comment by JC5** [comment]
This error happens on the command line? Not yet in the browser?
