### ISSUE TITLE
problem update 4.7.0 to 4.7.1.4

### ISSUE THREAD

**Issue by ianxzone** [firefly-iii/firefly-iii#1265]
I am running Firefly III version 4.7.0

#### Description of my issue:
i was see https://firefly-iii.readthedocs.io/en/latest/installation/upgrading.html#virtual-or-real-server
now i in this step
Then, run the following commands to finish the upgrade:
====================
note : i download from master because i got problem this 
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated <next_version> 
not working.

and try this command : 
php artisan migrate --env=production
show error

PHP Warning:  require(/home/user/public_html/domain/vendor/autoload.php): failed to open stream: No such file or directory in /home/user/public_html/domain/artisan on line 18

#### Steps to reproduce 

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
If you download from master, run the following command as well:

```
composer install --no-dev
```

However I am curious to know why did the `create-project` command not work?
