### ISSUE TITLE
Error after setting up firefly on server

### ISSUE THREAD

**Issue by georgecartridge** [firefly-iii/firefly-iii#1266]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
This is my first time setting up firefly and I installed version 4.7.1.4 with PHP 7.1. After installation, when I tried to access my localhost/firefly-iii/public folder, I am shown the following error:

`Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)`

#### Steps to reproduce 
Install fresh version of firefly-iii, and complete the setup on server. Upon trying to access localhost/firefly-iii/public I continue to get the error

#### Other important details (log files, system info):
Log of error:

`local.ERROR: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) at /var/ww/html/firefly-iii/app/Support/Twig/General.php:159)"}`

**Comment by JC5** [comment]
It seems you're not running PHP7.1 after all. Perhaps your Apache is still linked to PHP7.0?
