### ISSUE TITLE
Error when editing an expense account

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#1267]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
When I edit an expense account, I get this error message:
**Whoops! An error occurred.**
**Unfortunately, this error was not recoverable. Firefly III broke. The error is:**
**Trying to get property of non-object**
**More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.**

#### Steps to reproduce 
Edit any expense account in the list

**Comment by JC5** [comment]
Yes, this is a known issue, and will be fixed in the next release :+1:
