### ISSUE TITLE
Search field for expense accounts

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#1268]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
When going to the expense account list, it would be nice to have a search field to be able to find on easily, otherwise you have to go through the list to find the one you want.

**Comment by JC5** [comment]
I'll see if one can fit. No promises though ;).

**Comment by MacPaille** [comment]
No problem, thanks for considering this request :)

**Comment by jinformatique** [comment]
To the same request, would it be possible to use the main search field at the top left, to search in Description, Expense account, Notes ?
That would help a lot.

**Comment by MacPaille** [comment]
Is it still in the plan to implement this change?

**Comment by JC5** [comment]
If the issue is still open it’s on the list

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937737
