### ISSUE TITLE
Updating in 4.7.1... But still I'm in 4.7.0 !

### ISSUE THREAD

**Issue by Zciwobukaj** [firefly-iii/firefly-iii#1269]
Hello,

I just perform the 4.7.0 -> 4.7.1 update, according to the guide : https://firefly-iii.readthedocs.io/en/latest/installation/upgrading.html#upgrade-straight-from-docker-hub

Everything went without any error.
But when I log in back, I see the 4.7.0 version.

What went wrong ?

Thanks

**Comment by JC5** [comment]
Try `docker pull jc5x/firefly-iii:latest --force`.

Make sure you have backups!

**Comment by Zciwobukaj** [comment]
Here is the result : 
```
docker pull jc5x/firefly-iii:latest --force
unknown flag: --force
```
