### ISSUE TITLE
Only an idea about zero-based budgeting

### ISSUE THREAD

**Issue by nrob81** [firefly-iii/firefly-iii#1271]
Hello it isn't an issue, only an idea/question.

What do you think about zero-based budgeting?
The budgeted amount should be show:
the _actual_ months filled in value + the sum of all _previous_ amounts to that budget. 
This way, the remaining amount can be moved to the next months.

Plus, it would be nice to view the _difference_ of actual incomes and the budgeted amount to see, how much can be budgeted to use up all of the money. 

Thanks

**Comment by JC5** [comment]
Zero-based budgeting is a very nice method, but it doesn't fit Firefly III at the moment. I believe it is used in YNAB and other tools: all your income must be budgeted, and what you have left goes to the next month, leaving you more money to budget.

Firefly III works in reverse: you determine your budgets (possibly based on previous expenses) and you make sure this amount is present on your main asset account. You can do this on a monthly, weekly or even yearly basis. But I do it monthly. [Read more about it here](http://firefly-iii.readthedocs.io/en/latest/about/grand-theory.html).

I agree that Firefly III could use some better tools to see trends over multiple periods, but zero-based budgeting will not feature in FF3 any time soon.

**Comment by nrob81** [comment]
Ok, thank you!
