### ISSUE TITLE
Wrong sum in category report

### ISSUE THREAD

**Issue by robin5210** [firefly-iii/firefly-iii#1275]
I am running Firefly III version 4.7.1.4 

#### Description of my issue:

When generating a category report, the sum of all expenses and incomes isn't correctly calculated as shown in the screen shot below.

![screenshot_20180319_202658](https://user-images.githubusercontent.com/3855197/37617704-322bc8e2-2bb4-11e8-8f8a-bb0a331591bd.png)

#### Steps to reproduce 

I selected a single category with all my accounts enabled. The date range was set so all entries are covered.

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1213
