### ISSUE TITLE
I have a question regarding the due date and also the printing of the reports.

### ISSUE THREAD

**Issue by adailton-farf** [firefly-iii/firefly-iii#1277]
Good evening. I have two doubts, come on:

1 - How do I see all the bills that will expire on April 1, which have not yet been paid?

2- How do I print reports? My friend is in doubt about this, and so I decided to ask here, to see if you have a plugin, or another method to print.

**Comment by JC5** [comment]
1. On the /bills page.
2. Just print them. There is a dedicated print CSS.

**Comment by adailton-farf** [comment]
1- That was not what I meant. I talk about the other invoices, for example, do you know there in expenses? I want to get only those who have not yet been paid and who will win on April 1st.

2- I will analyze this part.

**Comment by JC5** [comment]
Do I get this right?

In `/transactions/withdrawals`, you have withdrawals (expenses) that not actually paid yet. Unpaid invoices. You have created the expense (for a specific invoice) but it is not yet paid by you.

For example, you have an invoice for a dentist that expires on April 1. You create it today, with the date set to April 1. Then what do you do to mark it as paid when you do not use "/bills"?

**Comment by adailton-farf** [comment]
There are some unpaid ones, but only what appears the most recent purchases made in March, than of other months. Like that, let's say I bought something in December 2017, which now expires on April 1, 2018. Well, I want that expense to appear too. What I want is a way to select all the expenses that will expire the 1st April, you know?

**Comment by JC5** [comment]
What exactly expires? Is it a deadline for payment? As far as I can tell Firefly III does not support what you want.

**Comment by adailton-farf** [comment]
Does the system have a due date?
I want to get all those debts that are going to win, do you understand?
I bought a car today to pay on May 1, so when I get close to that day I want this account to be displayed, so I do not forget to pay.

**Comment by JC5** [comment]
Ah I get it. No Firefly III doesn’t support this. You must set reminders in your own agenda.

**Comment by adailton-farf** [comment]
I was thinking here, is there any way to create a simple system in PHP? Because in this case, I'm just going to need him to pass the expense information that expires on April 1, in case it could be something like this: "reports / audit / 1,8,6,5,7 / 20161122 / currentMonthEnd" only that instead of printing all the bills would print out all the expenses that have to be paid until the other month.

**Comment by JC5** [comment]
I can provide a query that will return such transactions (based on the due date field) but you'll have to build your own system.

**Comment by adailton-farf** [comment]
It might be.
Only you make such a system with "url", there the field can let that I myself provide.

**Comment by JC5** [comment]
No.
