### ISSUE TITLE
Implement Yodlee

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1278]
See title.

https://www.yodlee.com/

**Comment by JC5** [comment]
Not going to happen.

**Comment by droidkoder** [comment]
Any reason why this is not going to happen?
Yodlee seems like a good idea to add integration to along with the Spectre API for automatic linking of bank accounts...

**Comment by JC5** [comment]
Spectre is already there. Firefly III has an API now, and building import tools is not worth my time. If you want to import from Yodlee to FF3, feel free to build a tool.
