### ISSUE TITLE
Transactions with 2 currencies behave wrong

### ISSUE THREAD

**Issue by Zciwobukaj** [firefly-iii/firefly-iii#1280]
Hello, here is my problem : 

I manage all my accounts in euro, except one. For this one, I want input expenses with both currencies : local currency CHD and euro. 1 CHD = 10,50 €
So I put all these expenses accordingly to this rate.
The problem is that *still*, Firefly wants that 1 CHD = 1€ . So it changes the inputs I made in both CHD and euro amounts fields *after* I put the correct amount...

How to fix this ?

**Comment by JC5** [comment]
If the conversion is 1=1 then the Fixer API cannot be reached, or is broken.  I see they're moving to a new API key based subscription thing.

Anyway, to answer your question. You change the currency to CHD. The top input will be CHD, the bottom one will be EUR. Correct?

Changing the top one will trigger a fix on the bottom. Changing the bottom will not trigger anything. So first change the top one (CHD), then enter the bottom one (EUR).

That should fix it.

**Comment by Zciwobukaj** [comment]
Hello,

this is contrary : top is EUR (amount), bottom is CHD (native amount).
When I input 10,50 EUR, Firefly puts 11 CHD (because of precision settings). So I correct to 1 CHD and validate.
When I create a second transaction and input once again 10.50 EUR, Firefly keeps putting 11 CHD instead of 1 CHD...

**Comment by JC5** [comment]
Firefly III will always automatically convert when you change the top field. This will change in the future.

What is wrong with the precision settings?

**Comment by Zciwobukaj** [comment]
So i don’t understand this behavior : i say that 1 CHD = 10.50 EUR and it stills make 1 CHD = 1 EUR.

Nothing is wrong with precision, I just set in this way in currency settings.

**Comment by pkoziol** [comment]
@Zciwobukaj, I belive that Firefly doesn't remember last conversion rate from previous transactions (as you probably want to). It always checks current rate using [Fixer](https://fixer.io/). Since CHD is your fictional currency it fails and uses 1=1.

**Comment by JC5** [comment]
Well, this problem is "solved".

Fixer.IO charges 10 euro's a month to do currency conversion. You can get a API key for free but it won't allow you to change the base currency. Which makes it pretty pointless.

Other currency conversion API's suffer from similar fates. 

So unless you have paid Fixer.IO account Firefly III won't convert at all in the next release. However, if you fork over the money one positive change remains: fictional or unknown currencies will not be converted 1:1 but will be ignored.

**Comment by simhnna** [comment]
You can look at how gnucash is doing this. Afaik they store the conversion rate in the database and then convert on the fly. The rates are stored with dates, since the rates can change daily.

**Comment by JC5** [comment]
I like the suggestion, but Firefly III already works like that :wink:

Like gnucash, I need to get the conversion rates from somewhere. And most, if not all API's available are either paid or severely limited in their functions. That's the issue I'm facing now.

**Comment by simhnna** [comment]
Let the users provide them. Even if you get a conversion rate online, it will always be just an approximation

**Comment by JC5** [comment]
That's an idea as well. It's a convenience service. I'll tinker with it this weekend :)

**Comment by Zciwobukaj** [comment]
Hi, I’m agree with Simon.
Let’s take the problem from the correct side : the currency system behave technically and functionally wrong.
One idea to solve this is to use API for standard currencies, and user inputs (eg : in settings > currencies) for personalized ones.

**Comment by JC5** [comment]
The state for the next release is as follows:

- Currency conversion works for existing currencies. The code is OK, all you need is a service. The services Firefly III currently supports are paid. This could change in the future if you know about an free service, then I can add it.
- Currency conversion for "fake" currencies or currencies that are not supported by the API (Bitcoin) is not-existing. Firefly III will not respond to these.

I don't see anything inherently wrong with this. It could be better of course, but it's not wrong.

For the future, I can build something to enter custom currency rates. For currency A to currency B, on a specific date (or date range, or forever?) with a specific conversion rate. But please know that this is a lot of work and I am not sure if I can do this any time soon.

**Comment by Zciwobukaj** [comment]
Hi,
The wrong thing with the actual mode is that the automatic conversion erase the user input in the double currency transaction.
Now I know it and I’m very careful when I use this. But few times I had wrong transactions because of this => wrong summary at the end.

I understand your development choices but this automatic conversion should be at least disabled or secured in Firefly iii when it’s about custom currency.

**Comment by JC5** [comment]
Like I said, it will be in the next release.
