### ISSUE TITLE
Regex trigger in rules

### ISSUE THREAD

**Issue by miclnl** [firefly-iii/firefly-iii#1281]
I am running Firefly III version 4.7.1.1

Feature request

#### Description of my issue:
As the rules only allow for AND, my situation would require a lot of rules for something which could be solved easily using 1 regex expression. Would it be possible to allow for regex matching as a trigger?

#### Steps to reproduce 
My specific situation:
Trying to categorize cafeteria meals in breakfast/lunch/diner using the timestamp given in the description:

* 06,07,08,09 = breakfast regex: `0[6-9]` instead of 4 rules
* 11,12,13 = lunch regex `[11-13]` instead of 3 rules
* 16,17,18 = diner regex `[16-18]` instead of 3 rules

#### Other important details (log files, system info):
n.a.

**Comment by JC5** [comment]
Sorry, no. The rules engine will remain about as basic as it is now.

What I would suggest is write a script that pre-parses your import (if feasible).

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/1338

This might make it a little easier.
