### ISSUE TITLE
The unclear behavior of the "New withdrawal"/"New deposit" button

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1282]
If I press one of the buttons "New withdrawal"/"New deposit" from the main menu (not in the block of a specific account!), The first account from my list is always selected in the account field. As a result, I often forget to change the account and create a transaction from the account to the wrong account.

It would be more logical if the "account" field was empty by default when creating a transaction from the menu. And when you try to save a transaction with an empty "account" field, you receive an error message.

And when creating a specific account from the block on the main page - the behavior is now logical, the required account is substituted in the form.

![1](https://user-images.githubusercontent.com/520760/37719481-2a5455a2-2d36-11e8-8b87-1576344b4671.jpg)
![2](https://user-images.githubusercontent.com/520760/37719482-2a819472-2d36-11e8-95b7-ae51607337b4.jpg)

**Comment by JC5** [comment]
I believe the current behaviour is fine. I am not going to break a form intentionally.
