### ISSUE TITLE
Error when bulk deleting transactions

### ISSUE THREAD

**Issue by geertplaisier** [firefly-iii/firefly-iii#1283]
When bulk removing transactions, I'm getting the following error:

Call to undefined method FireflyIII\Repositories\Journal\JournalRepository::delete() 

Looking at the code I think the line below should be change from ->delete to ->destroy to fix the issue.

https://github.com/firefly-iii/firefly-iii/blob/ef4018934ccb1cb167173f897f368a127562aff6/app/Http/Controllers/Transaction/MassController.php#L106

**Comment by JC5** [comment]
Hi! Thanks for letting me know!

I've replaced the line in the develop-branch, meaning this will be fixed in the next release:

https://github.com/firefly-iii/firefly-iii/blob/develop/app/Http/Controllers/Transaction/MassController.php#L106

Let me know if you find something else! :+1:
