### ISSUE TITLE
Locale issue on Rasbian + Nginx

### ISSUE THREAD

**Issue by roinou** [firefly-iii/firefly-iii#1285]
I am running Firefly III version 4.7.1.4

I have the warning message about invalid config and locales missing. The amounts therefore display without the "," (I'm super rich now!).

I just can't seem to see where to configure this, or how it even works. Running "locale -a" displays all the locales installed, I've regenerated multiple times the locales from my system, yet no success.

How does it work in firefly? what does it take for it to determine the locale to apply?

I'm running FF3 on a raspberry pi, raspbian stretch, PHP 7.1 (from buster), nginx and postgres.

any help will be appreciated!

**Comment by JC5** [comment]
Which language are you trying to use in Firefly III, and what is the output of `locale -a`?

**Comment by roinou** [comment]
I'm ok using english for the interface, and I'd like to have the currencies and dates displayed European style, preferably French (comma for decimal, space for thousands).

My "locale -a" displays:

> C
> C.UTF-8
> en_GB.utf8
> fr_BE.utf8
> POSIX
>

**Comment by JC5** [comment]
That won't be possible when you use English as the interface. Numbers will be formatted according to en_US.

**Comment by roinou** [comment]
OK, I changed the interface to French, reboot the Pi, and still a balance of 41000 € (how I wish). Should I install **fr-FR** locale? Should fr be the default one?

**Comment by roinou** [comment]
after installing fr-FR, rebooting, and switching languages back and forth it now works. Or maybe it was browser caching somehow. Isn't it possible to stick to the language's installed locale? so you can choose french, and still have locale from Canada or Belgium rather than France?

**Comment by JC5** [comment]
No, it's all or nothing at the moment.

**Comment by roinou** [comment]
ok, understood. Thanks for the fast support!
