### ISSUE TITLE
csv import with bad csv

### ISSUE THREAD

**Issue by Mindar** [firefly-iii/firefly-iii#1286]
Hey,
I love your software and I'm very happy with it so far. Unfortunately my bank generates pretty bad "csv" files, so I can't import them directly. Right now I have to preprocess these files by hand, which is very time-consuming. The problems I've encountered are:

**Leading non-csv lines**
Before the header there are several lines of text. This problem could be solved by adding the option to ignore the first x lines of a csv file.

**Unusual Encoding**
I'm from germany and the csv file contains letters such as ä, ö, ü, ß, etc. The csv file is encoded in an unusual encoding (not UTF-8). Special letters are displayed as questionmarks. This problem might be solved by allowing users to select the encoding manually. The main issue I see with that approach is that most users probably don't know the encoding either (I certainly don't know the encoding yet and I've tried several common encodings already). *Edit: I've figured out what is happening: The file is utf-8 encoded, however my bank has replaced all special characters with the utf-8 replacement character (that questionmark thing). There is nothing Firefly could do to fix this issue for me. However selecting the encoding might be useful for other people in some cases.*

Thank you for developing Firefly :)

Cheers,
Mindar

**Comment by JC5** [comment]
Hi Mindar, thanks for the compliments!

Leading lines in a CSV file is a bad form and I really can't create anything user friendly to counter it. I'm not sure there are programs on the market that can handle such files. I would suggest you contact your bank about this.

I see that your bank is also using a very special beta version of UTF-8 :wink:. Firefly III will be fitted with a detection routine in the next release, but not with a conversion routine. It will simply break nicely when confronted with non-utf8 files.

Thanks for your suggestions!
