### ISSUE TITLE
"Show all transactions without grouping them by date"-Button not working on account page

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#1292]
I am running Firefly III version 4.7.1.4

#### Description of my issue:

The _Show the current period and overview_-Button isn't working.
![image](https://user-images.githubusercontent.com/31184224/37877120-82e012ce-3056-11e8-8032-611872946107.png)
This problem also exists on the demo site.

#### Steps to reproduce 

1. open the detail-page of an account (_Asset account_, _Expense account_ or _Revenue accout_).
2. scroll down to the transaction-list
3. notice a button which
   1. says _Show the current period and overview_ instead of _Show all transactions without grouping them by date._ (see e.g the detail-page of a category)
   2. isn't working as expected (should show all transactions [first click] and then [second click] the current period - like the button in the category detail page)

**Comment by JC5** [comment]
Indeed, that code is a bit messy. I have pushed a fix to the [demo site](https://demo.firefly-iii.org/accounts/show/1). Let me know if this is more in line with what you expected.

**Comment by nicoschreiner** [comment]
It's better now, but I would expect the graphs to stay there (Like on the [Category-Page](https://demo.firefly-iii.org/categories/show/1/all)). Currently they are removed if I click on _Show all transactions without grouping them by date_.

**Comment by JC5** [comment]
Indeed. The top chart will be back, but the pie-charts won't.

**Comment by nicoschreiner** [comment]
Okay. But are you going to remove them in the [Budget-Page](https://demo.firefly-iii.org/budgets/show/2/112) too then? (Currently they are shown, if you click on _Show all transactions without grouping them by date_)

Just to be consistent with this :smile:

**Comment by JC5** [comment]
I think I will, they aren't very useful when there is so much data.

**Comment by nicoschreiner** [comment]
That's true :smiley:

**Comment by JC5** [comment]
Fixed :+1:
