### ISSUE TITLE
Notes-Box touches border

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#1293]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
The Layout of the _Notes_-Box in the account detail-page is not in line with other boxes (it touches the border).

![image](https://user-images.githubusercontent.com/31184224/37878648-9af39956-306c-11e8-8dc4-f22f3260409e.png)

This is on the demo site too.

#### Steps to reproduce 
1. Add a note to an account.
2. Open the detail-page of that account.

**Comment by JC5** [comment]
Nicely spotted! Fixed! :+1:

**Comment by nicoschreiner** [comment]
How can you be that fast? :flushed: 
Thanks!

**Comment by JC5** [comment]
It's a lazy Sunday evening. I'm sitting behind my PC :wink:.
