### ISSUE TITLE
Incorrect values in balance difference on the asset accounts page

### ISSUE THREAD

**Issue by lgp171188** [firefly-iii/firefly-iii#1295]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
In the asset accounts page, there is a column named 'Balance difference' which kind of implies that it is the difference between 2 balance values (for example, starting balance and current balance) but it has the same value as the current balance column.

Note that I have been entering data only for the past 3-4 days and I am not sure if the page requires data for at least a month to be able to show correct values.

#### Steps to reproduce 

<img width="560" alt="screen shot 2018-03-26 at 18 52 56" src="https://user-images.githubusercontent.com/218870/37909042-7dd8ba84-3127-11e8-9386-323622baa293.png">

#### Other important details (log files, system info):

Debug information generated at 2018-03-26 13:27:34 UTC for Firefly III version **4.7.1.4**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.1.4 |
| FF API version | 0.1 |
| App environment | production |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.15 |
| Display errors | Off |
| Session start | 2018-03-01 00:00:00 |
| Session end | 2018-03-31 23:59:59 |
| Session first | 2018-03-24 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux 69e3f233788e 4.9.0-6-amd64 # 1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 |
| Interface | apache2handler |
| UserID | 1 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, pdo_mysql, pdo_pgsql, tidy, zip |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@4.2.0, defuse/php-encryption@v2.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.7.0, fideloper/proxy@3.3.4, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.0, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.5.36, laravel/passport@v4.0.3, laravelcollective/html@v5.5.3, lcobucci/jwt@3.2.2, league/commonmark@0.17.0, league/csv@9.1.2, league/event@2.1.2, league/flysystem@1.0.43, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.23.0, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, phpseclib/phpseclib@2.0.10, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v3.4.6, symfony/css-selector@v4.0.6, symfony/debug@v3.4.6, symfony/event-dispatcher@v4.0.6, symfony/finder@v3.4.6, symfony/http-foundation@v3.4.6, symfony/http-kernel@v3.4.6, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php70@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v3.4.6, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v3.4.6, symfony/translation@v4.0.6, symfony/var-dumper@v3.4.6, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.2, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2, zendframework/zend-diactoros@1.7.1,  |

**Comment by JC5** [comment]
I am assuming that all accounts started at zero?

**Comment by lgp171188** [comment]
No, all accounts had a non-zero starting balance.

**Comment by JC5** [comment]
What date did you give those opening balances?

**Comment by lgp171188** [comment]
I started using my Firefly III instance on 24 March 2018 and added all the asset accounts with opening balances on the same day.

**Comment by JC5** [comment]
Ah I understand it. The difference is over your session range (top right). Which is between 1 Mar and 31 Mar. On 1 Mar the balance was 0.00 (technically). 

It will correct next month as you say :)

**Comment by lgp171188** [comment]
> On 1 Mar the balance was 0.00 (technically).
Though it is technically correct, wouldn't it be better to actually use the starting balance of the account in case the account was not added on the 1st of the month? That would be the semantically correct option because the account didn't exist on 1 March and hence it is wrong to treat the balance as 0.00. In the following month, though the difference values will get corrected, it will be the difference from the balance at the start of the next month. There is no period where the difference is against the starting balance of the account.

**Comment by JC5** [comment]
Yes, and no. It's error prone and it's a small issue.
