### ISSUE TITLE
Firefly III throws a 500 internal server error when trying to send email

### ISSUE THREAD

**Issue by lgp171188** [firefly-iii/firefly-iii#1296]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
When I click the forgot password link in the login page or the send test email link in the administration page, Firefly III crashes with a 500 error.

I am currently running Firefly III on docker using the `docker-compose.yml` file provided in the repository and referenced in the documentation. An apache2 web server running on the host (up-to-date Debian Stretch amd64) does SSL termination and acts as a reverse proxy to the Firefly III instance.

#### Steps to reproduce 

This error happens in 2 scenarios:

* In the Firefly III login page, click on 'I forgot my password' and in the next page enter the email address associated with an account.
* In the administration page, click 'Send email'.

This causes Firefly III to crash and throw a 500 error with the following message.

        Unfortunately, this error was not recoverable. Firefly III broke. The error is:

        Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 88 and exactly 1 expected

I haven't explicitly configured the SMTP settings for Firefly III to send email and there seems to be no way to do so.

The problem doesn't exist on the demo site since the 'send email' feature is disabled for demo user and I don't know the details of any existing user on the demo instance to request a password reset email.

#### Other important details (log files, system info):

Debug information generated at 2018-03-26 13:41:33 UTC for Firefly III version **4.7.1.4**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.1.4 |
| FF API version | 0.1 |
| App environment | production |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.15 |
| Display errors | Off |
| Session start | 2018-03-01 00:00:00 |
| Session end | 2018-03-31 23:59:59 |
| Session first | 2018-03-24 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux 69e3f233788e 4.9.0-6-amd64 # 1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 |
| Interface | apache2handler |
| UserID | 1 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, pdo_mysql, pdo_pgsql, tidy, zip |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@4.2.0, defuse/php-encryption@v2.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.7.0, fideloper/proxy@3.3.4, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.0, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.5.36, laravel/passport@v4.0.3, laravelcollective/html@v5.5.3, lcobucci/jwt@3.2.2, league/commonmark@0.17.0, league/csv@9.1.2, league/event@2.1.2, league/flysystem@1.0.43, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.23.0, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, phpseclib/phpseclib@2.0.10, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v3.4.6, symfony/css-selector@v4.0.6, symfony/debug@v3.4.6, symfony/event-dispatcher@v4.0.6, symfony/finder@v3.4.6, symfony/http-foundation@v3.4.6, symfony/http-kernel@v3.4.6, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php70@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v3.4.6, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v3.4.6, symfony/translation@v4.0.6, symfony/var-dumper@v3.4.6, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.2, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2, zendframework/zend-diactoros@1.7.1,  |

**Comment by JC5** [comment]
I can fix the error for the next release. Thanks for reporting!

For possible environment variables, please see the .env.docker file in the repository.

**Comment by JC5** [comment]
I've updated some config vars but without a mail configuration it might fail next time too.

**Comment by lgp171188** [comment]
It would be good to have a section in the documentation detailing the configuration needed for sending emails. While it is there in .env* files, for some one new to Firefly III, it is very difficult to find.

If this is okay, I am willing to contribute to the documentation changes needed.

**Comment by JC5** [comment]
That is a very good suggestion. I have expanded the docker documentation to point to the .env.docker file. There's plenty of explanation in that file already :+1:
