### ISSUE TITLE
Error Undefined index: account_type_id when converting transaction to withdrawal

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#1297]
I am running Firefly III version 4.7.1.4

#### Description of my issue:
Error when converting transaction to withdrawal
#### Steps to reproduce 
Try to convert a deposit to a withdrawal. Firefly throw's  a error  Undefined index: account_type_id. The problem exists also on the demo site 
(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
Nice find! I have pushed a fix, that will go live in the next release. It's live on the demo site already. Could you check it as well?

**Comment by leander091** [comment]
Thanks for the quick fix. It is working for me
