### ISSUE TITLE
Firefly III docker version not working on local

### ISSUE THREAD

**Issue by ganeshkrajendran** [firefly-iii/firefly-iii#1299]
I am trying to run Firefly III docker version as per instruction from 
http://firefly-iii.readthedocs.io/en/latest/installation/docker.html

**Description of my issue:**
Firefly III docker version not working on local with docker exec commands as described here.
docker exec -it fd7398e6aebe php artisan migrate --seed
http://firefly-iii.readthedocs.io/en/latest/installation/docker.html

**Steps to reproduce** 
http://firefly-iii.readthedocs.io/en/latest/installation/docker.html
I have started with "straight from docker hub" step by step having mysql running on localhost and mysql version is 5.7.21 but ended with below error when try with docker exec. 

docker exec -it fd7398e6aebe php artisan migrate --seed

**In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from inform  
  ation_schema.tables where table_schema = firefly_db and table_name = migrat  
  ions)                                                                        

In PDOConnection.php line 47:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  

In PDOConnection.php line 43:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory**  

Here is my docker run command:
docker run -d \
-v firefly_iii_export:/var/www/firefly-iii/storage/export \
-v firefly_iii_upload:/var/www/firefly-iii/storage/upload \
-p 80:80 \
-e FF_APP_ENV=local \
-e FF_APP_KEY=something@Wanted@by@2018For@me12 \
-e FF_DB_HOST=localhost \
-e FF_DB_NAME=firefly_db \
-e FF_DB_USER=root \
-e FF_DB_PASSWORD=root \
jc5x/firefly-iii:latest

Docker ps shows me the firefly is running on port 80.

Any help on this really appreciated!!!

**Comment by JC5** [comment]
The DB_HOST cannot be localhost. That would be the docker instance itself. You must use the IP of the machine where MySQL is installed. If that is your personal machine (and not another docker instance) I am not sure which config you should use.

**Comment by ganeshkrajendran** [comment]
Thanks, tip really helped my long struggle on this setup, could you please update the document to have this note. may help others!!.

**Comment by JC5** [comment]
I’ll see what I can do. Glad it works!
