### ISSUE TITLE
Net worth includes the credit limit of credit card asset accounts

### ISSUE THREAD

**Issue by lgp171188** [firefly-iii/firefly-iii#1300]
I am running Firefly III version 4.7.1.4
#### Description of my issue:
I have multiple asset accounts out of which a few are credit card accounts. I have entered the credit limit details of my credit card accounts in the virtual balance section of the account.

The Net worth amount shown in the dashboard page includes the unspent credit amount which imho is incorrect because it is not actually my money to spend. Even if I spent all the money in my credit limit, I owe it back to the credit card company.

If this interpretation is correct and this is not a bug, replacing the 'Net worth' term with say 'Spendable amount' it might make more sense.

#### Steps to reproduce 

Add an asset account of type credit card and enter the credit limit of the account in the virtual balance section.

The net worth amount includes the credit limit left in the credit card accounts.

#### Other important details (log files, system info):

Debug information generated at 2018-03-27 14:22:58 Asia/Kolkata for Firefly III version **4.7.1.4**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.1.4 |
| FF API version | 0.1 |
| App environment | production |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.15 |
| Display errors | Off |
| Session start | 2018-03-01 00:00:00 |
| Session end | 2018-03-31 23:59:59 |
| Session first | 2018-03-24 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux 7184880d385e 4.9.0-6-amd64 # 1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 |
| Interface | apache2handler |
| UserID | 1 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, pdo_mysql, pdo_pgsql, tidy, zip |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@4.2.0, defuse/php-encryption@v2.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.7.0, fideloper/proxy@3.3.4, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.0, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.5.36, laravel/passport@v4.0.3, laravelcollective/html@v5.5.3, lcobucci/jwt@3.2.2, league/commonmark@0.17.0, league/csv@9.1.2, league/event@2.1.2, league/flysystem@1.0.43, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.23.0, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, phpseclib/phpseclib@2.0.10, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v3.4.6, symfony/css-selector@v4.0.6, symfony/debug@v3.4.6, symfony/event-dispatcher@v4.0.6, symfony/finder@v3.4.6, symfony/http-foundation@v3.4.6, symfony/http-kernel@v3.4.6, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php70@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v3.4.6, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v3.4.6, symfony/translation@v4.0.6, symfony/var-dumper@v3.4.6, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.2, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2, zendframework/zend-diactoros@1.7.1,  |

**Comment by JC5** [comment]
I'll make sure that the virtual balance for credit cards is not included in the net worth calculations :)

**Comment by JC5** [comment]
Fixed. Will be live in next release.
