### ISSUE TITLE
Linking of transactions does not work

### ISSUE THREAD

**Issue by tomazsustar** [firefly-iii/firefly-iii#1304]
I am running Firefly III version 4.7.1.4 

#### Description of my issue:
Linking of transactions does not work. (Great feature by the way)

#### Steps to reproduce 
I am using chromium on linux. The list to select a type of the link is empty.
![screenshot from 2018-03-28 02-08-58](https://user-images.githubusercontent.com/2174572/38001537-9729aa28-322d-11e8-8b1a-5fe299bcf2f8.png)

It does not happen on the demo site. Do you have an idea what can be the problem?

**Comment by JC5** [comment]
It could be that the entries have not been created properly. Try the following.

1. Backup your database.
2. Run `php artisan migrate --seed` on the command line.
3. Run `php artisan ca:cl`

Let me know if this fixes the problem.

**Comment by tomazsustar** [comment]
That helped. Thanks a lot!

**Comment by JC5** [comment]
:+1:
