### ISSUE TITLE
Rename bank account

### ISSUE THREAD

**Issue by cyberax17** [firefly-iii/firefly-iii#1307]
Hi 
is it possible to rename existing bank accounts?

Cheers
andy

**Comment by JC5** [comment]
Yes, two options:

- Press the Pencil icon in the list of accounts. (`/accounts/asset` for example)
- Press the little ellipse button on the show page (`/accounts/show/xx`)

**Comment by cyberax17** [comment]
great thanks! Somehow this button was missing in the mobile version, but the desktop version is fine :-) Cheers andy

**Comment by JC5** [comment]
:+1:
