### ISSUE TITLE
import ready, nothing was imported

### ISSUE THREAD

**Issue by Mysensed** [firefly-iii/firefly-iii#1308]
I am running Firefly III version 4.7.1

**Description of my issue:**
I am trying to use firefly for the first time and i created a free sandstorm account to use it. 
While importing a CSV file i get the error "De import is klaar. Er is niets uit je bestand geïmporteerd." (dutch) "import ready, nothing was imported" (translated). 

I am using a CSV export from the ING bank in the netherlands. The CSV seems to be good, because all the fields show up during the configuration and mapping. Below is an export of the import settings that i have selected 
`{
    "has-headers": true,
    "date-format": "Ymd",
    "delimiter": ",",
    "import-account": 1,
    "specifics": {
        "IngDescription": 1
    },
    "column-count": 9,
    "column-roles": [
        "date-book",
        "description",
        "account-iban",
        "opposing-iban",
        "_ignore",
        "ing-debit-credit",
        "amount",
        "tags-space",
        "note"
    ],
    "column-do-mapping": [
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false
    ],
    "column-mapping-config": {
        "2": {
            "NL95INGB0008671856": 1
        },
        "3": []
    },
    "file-type": "csv",
    "has-config-file": true,
    "apply-rules": true,
    "match-bills": false,
    "auto-start": false,
    "column-roles-complete": false,
    "column-mapping-complete": false,
    "initial-config-complete": false,
    "has-file-upload": false
}`

It seems like it does not recognize the date on the first field, even though i selected that the file has headers.

**Steps to reproduce** 

- Use a fresh installation, possibly on sandstorm.io
- set account and savings account
- try to run a import using the example csv below (i replaced my personal data)

I can't test this on the demo because importing csv is not allowed.

debug info:

Debug information generated at 2018-03-30 19:18:59 UTC for Firefly III version **4.7.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.1 |
| FF API version | 0.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.13-1+0\~20180105151310.14+jessie\~1.gbp1086fa |
| Display errors | Off |
| Session start | 2018-03-01 00:00:00 |
| Session end | 2018-03-31 23:59:59 |
| Session first | 2018-03-30 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux sandbox 4.9.0-6-amd64 # 1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 |
| Interface | fpm-fcgi |
| UserID | 1 |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | yes |
| Sandstorm anon? | no || Is Sandstorm (.env) | true |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@4.2.0, defuse/php-encryption@v2.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.7.0, fideloper/proxy@3.3.4, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.0, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.5.36, laravel/passport@v4.0.3, laravelcollective/html@v5.5.3, lcobucci/jwt@3.2.2, league/commonmark@0.17.0, league/csv@9.1.2, league/event@2.1.2, league/flysystem@1.0.43, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.23.0, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, phpseclib/phpseclib@2.0.10, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.0, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v3.4.5, symfony/css-selector@v4.0.5, symfony/debug@v3.4.5, symfony/event-dispatcher@v4.0.5, symfony/finder@v3.4.5, symfony/http-foundation@v3.4.5, symfony/http-kernel@v3.4.5, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php70@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v3.4.5, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v3.4.5, symfony/translation@v4.0.5, symfony/var-dumper@v3.4.5, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.2, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2, zendframework/zend-diactoros@1.7.1,  |

```
Truncated from this point <----|[2018-03-30 19:18:55] local.INFO: Start with import job RJfiTtdabEFE  
[2018-03-30 19:18:55] local.NOTICE: Building importable objects from CSV file.  
[2018-03-30 19:18:55] local.INFO: Returned 1 valid objects from file processor  
[2018-03-30 19:18:55] local.ERROR: Import journal cannot parse date "Ymd" from value "" so will return current date instead.  
[2018-03-30 19:18:55] local.ERROR: Cannot import row #0 because: Undefined index: account_type_id  
[2018-03-30 19:18:55] local.INFO: ImportStorage has finished.  
[2018-03-30 19:18:55] local.INFO: Back in storeObjects()  
[2018-03-30 19:18:55] local.INFO: Will not create tag, 0 journals imported.  
[2018-03-30 19:18:55] local.INFO: Done with import job RJfiTtdabEFE  
```

**test csv**
`"Datum","Naam / Omschrijving","Rekening","Tegenrekening","Code","Af Bij","Bedrag (EUR)","MutatieSoort","Mededelingen"
"20180329","NAME","NL91ABNA0417164300","","GT","Af","2000,00","Online bankieren","description"
`

**Comment by JC5** [comment]
Thanks for reporting this issue, with all the logs and entries!

You have stumbled upon a bug that will be fixed in the next release. During or after Easter I plan to push a new release that should fix this. When it's released on Sandstorm (I suspect during next week) this will be fixed as well.

**Comment by Mysensed** [comment]
Thanks, anything i can do now to start testing and the initial set-up? Or is it a lot easier if i just wait a couple of days?

**Comment by JC5** [comment]
I suggest you start by simply entering all of your transactions for this month. Or wait a few days and start fresh on April 1st. By hand, yes.

I can assure you it'll be way more insightful than trying to import ING data. Their exports are crap anyway and you'll learn nothing new. You'll spend the better part of your weekend trying to their data and you will end up frustrated and annoyed. 

If you want to see what the result could be like, use the demo site. Otherwise, just get started with a fresh Sandstorm instance or a docker image or build your own server.

Just don't start randomly importing data. Enter it yourself. Believe me, if you're serious about getting to know your finances, do it by hand.

**Comment by Mysensed** [comment]
Hmm ok. i have not use the tool yet and so far i am just checking it out (hence my question in regards to your reply). It really seems like a the best one i have seen so far. I tried, but don't like the one from AFAS because there is so much manual work involved putting tags and labels on everything.
I was hoping to be able to set import rules and such. So that i can put (recurring) transactions in a certain category, label or tag. 

I can see why doing this manually will allow you to get the most out of the tool. But it just seems like too much of hassle. 

I am also not sure what more you could expect from the bank besides dates, accounts, descriptions. Maybe i am wrong but i thought thats all there is to it. I did notice that my savings account was not in the CSV. 

PS: maybe this is not the place for these no-issue topics. feel free not to reply and leave it as is.

**Comment by JC5** [comment]
Yeah you're right. It's a pet peeve of mine, forgive me if I came across as harsh. But it is the best tool out there so stop searching :wink:

You won't get a lot from the file indeed, although transfers should be included. The trouble is that stores like Albert Heijn have about 15 billion different names in CSV files. Ranging from `ALB HE 1022` to `AHTGO 1201` and everything in between. Something to keep an eye on.

Then again, most other transactions will look fine.

And no it's no trouble!
