### ISSUE TITLE
Sandstorm: Spanish and Portuguese show error about missing locale packages

### ISSUE THREAD

**Issue by kentonv** [firefly-iii/firefly-iii#1310]
I am running Firefly III version 4.7.1-sandstorm

#### Description of my issue:

(This was originally reported by a Sandstorm user, but I've confirmed it locally.)

In the Sandstorm version, when switching the language to Spanish or Brazilian Portuguese, a blue warning box appears linking to: https://github.com/firefly-iii/help/wiki/Missing-locale-packages

The box does not appear for other languages.

On Sandstorm, the user cannot follow the instructions at the link. The files in question need to be added to the Sandstorm package. This probably means that it's necessary to try every language while running Firefly in `spk dev` mode, so that `spk` can observe that these files are used and add them to the package.

#### Steps to reproduce 

1. Install Firefly on Sandstorm.
2. Visit "options".
3. Switch the language to Spanish.

**Comment by JC5** [comment]
Thanks for letting me know! I've added them to the installation routine, which will make sure they're included in the next release. Although 4.7.2 is out, the Sandstorm package has not been released yet. So it'll be fixed soon :)

**Comment by JC5** [comment]
The new release of Sandstorm is live, so this can be closed.
