### ISSUE TITLE
Upgrade docker from 4.7.1.4 to 4.7.2.1

### ISSUE THREAD

**Issue by vwasthename** [firefly-iii/firefly-iii#1311]
I am running Firefly III version 4.7.1.4 in a docker environment. I have followed the manual on the official documentation page, called "Docker Hub with automatic updates via docker compose".

#### Description of my issue:
I'd like to upgrade to the latest version, 4.7.2.1 at the moment, however i'm unable to upgrade to this version. I don't have any critical errors(?), while no upgrade is performed.

#### Steps to reproduce 
Follow the first step of the upgrade process:
```
docker-compose pull firefly_iii_app
WARNING: The h variable is not set. Defaulting to a blank string.
Pulling firefly_iii_app (jc5x/firefly-iii:latest)...
latest: Pulling from jc5x/firefly-iii
f2b6b4884fc8: Pull complete
8db887c45800: Pull complete
6e0e41c52c70: Pull complete
fbc9ac078c49: Pull complete
c4c6f6be7488: Pull complete
a28db8adaf05: Pull complete
61afa9c0aff1: Pull complete
a30b1659c046: Pull complete
b04c4f5caef7: Pull complete
e95e8ef45129: Pull complete
1f2c27a4fb1a: Pull complete
0ae56ef7f816: Pull complete
8dd1b5a7a5ad: Pull complete
44ea7feb46b1: Pull complete
1ea25c770338: Pull complete
6163f5415e5e: Pull complete
98fbf4fb1c94: Pull complete
20e64bef709b: Pull complete
8f8edf67df27: Pull complete
16e48e439928: Pull complete
63399f33a817: Pull complete
a3e9ab804e4c: Pull complete
35bb159ec97b: Pull complete
14797a49a804: Pull complete
f9f1531e016c: Pull complete
cd5dd205c8a2: Pull complete
Digest: sha256:7fcb39386032e6cd9a411178819fa272631a32be7649102783d7efeb350354bb
Status: Downloaded newer image for jc5x/firefly-iii:latest
```

AND

```
docker-compose restart firefly_iii_app
WARNING: The h variable is not set. Defaulting to a blank string.
Restarting desktop_firefly_iii_app_1 ... done
```

Then a had to execute the following 4 commands:
```
docker exec -it 95be8ddc7019 php artisan migrate
Nothing to migrate.
```

```
docker exec -it 95be8ddc7019 php artisan firefly:upgrade-database
Updating currency information..
Done updating currency information..
Firefly III database is up to date.
```

```
docker exec -it 95be8ddc7019 php artisan firefly:verify
User #3 (*****) has budget #1 ("Travel 2017") which has no transactions.
User #3 (*****) has category #1 ("Boodschappen") which has no transactions.
User #3 (*****) has category #2 ("Uiteten") which has no transactions.
...
...
User #3 (*****) has category #22 ("Openbaar vervoer") which has no transactions.
Amount integrity OK for user #3
No orphaned transactions!
No orphaned journals!
All link types OK!
All access tokens OK!
Amount integrity OK!
```

```
docker exec -it 95be8ddc7019 php artisan passport:install
_Encryption keys already exist. Use the --force option to overwrite them._
Personal access client created successfully.
Client ID: 3
Client Secret: ******************************
Password grant client created successfully.
Client ID: 4
Client Secret: *******************************************
```

** Note, due to the "Encryption keys already exist" I used the force option **

```
 docker exec -it 95be8ddc7019 php artisan passport:install --force
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 5
Client Secret: *****************************OK
Password grant client created successfully.
Client ID: 6
Client Secret: `***************************`
```

Finally i'd expected an updated version, but i'm still with the old version. I've rebooted both dockers without any effect. 

#### Other important details (log files, system info):

Debug information generated at 2018-04-02 15:58:17 UTC for Firefly III version **4.7.1.4**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.1.4 |
| FF API version | 0.1 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.15 |
| Display errors | Off |
| Session start | 2018-04-01 00:00:00 |
| Session end | 2018-04-30 23:59:59 |
| Session first | 2013-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux 95be8ddc7019 4.9.87-linuxkit-aufs # 1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 |
| Interface | apache2handler |
| UserID | 3 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, pdo_mysql, pdo_pgsql, tidy, zip |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@4.2.0, defuse/php-encryption@v2.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.3, erusev/parsedown@1.7.0, fideloper/proxy@3.3.4, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.0, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.5.36, laravel/passport@v4.0.3, laravelcollective/html@v5.5.3, lcobucci/jwt@3.2.2, league/commonmark@0.17.0, league/csv@9.1.2, league/event@2.1.2, league/flysystem@1.0.43, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, mtdowling/cron-expression@v1.2.1, nesbot/carbon@1.23.0, paragonie/constant_time_encoding@v2.2.1, paragonie/random_compat@v2.0.11, phpseclib/phpseclib@2.0.10, pragmarx/google2fa@v2.0.7, pragmarx/google2fa-laravel@v0.1.4, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v3.4.6, symfony/css-selector@v4.0.6, symfony/debug@v3.4.6, symfony/event-dispatcher@v4.0.6, symfony/finder@v3.4.6, symfony/http-foundation@v3.4.6, symfony/http-kernel@v3.4.6, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php70@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v3.4.6, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v3.4.6, symfony/translation@v4.0.6, symfony/var-dumper@v3.4.6, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.2, vlucas/phpdotenv@v2.4.0, watson/validating@3.1.2, zendframework/zend-diactoros@1.7.1,  |

**Comment by JC5** [comment]
Thanks for logging the issue. Make sure you have backups of everything!

There was no need to do the --force thing, btw, but it doesn't matter much.

What happens when you add `--force-recreate` to the command? So:

`docker-compose restart firefly_iii_app --force-recreate`
