### ISSUE TITLE
Error 500 when creating an asset account with no virtual balance

### ISSUE THREAD

**Issue by s-uds** [firefly-iii/firefly-iii#1313]
Hi!

I am running Firefly III version 4.7.2.1 

When trying to create an **asset account** and leaving `virtual balance` empty, it leads to the "Be right back" page.

Examining the logs reveals the following:

```
[HY000]: General error: 1366 Incorrect decimal value: '' for column 'virtual_balance' at row 1 at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)
```

Setting the amount to 0 is a workaround.

Thanks!

**Comment by JC5** [comment]
Thanks for reporting! That's a sloppy one. I will push a new release somewhere this week to fix it.

**Comment by JC5** [comment]
I've pushed and tested a fix that will be live in the next release. Should be tomorrow if nothing else pops up.

I'm closing this one to keep the list clear. Thanks again for letting me know!

**Comment by JC5** [comment]
New release is live!
