### ISSUE TITLE
hide transactions between own accounts

### ISSUE THREAD

**Issue by Pzz70** [firefly-iii/firefly-iii#1314]
I'm not using Firefly yet.

But a functionalitily I'm looking for is to hide transactions between my own accounts in some reports.

Is that possible?

**Comment by JC5** [comment]
Well that depends on what you mean by hiding, but by default transfers between asset accounts do not count as an expense as long as both asset accounts are included in the report. So effectively they're hidden.

**Comment by Pzz70** [comment]
That's good enough I guess.
