### ISSUE TITLE
Bug when switching between New expense / New income / New transfer

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1323]
I am running Firefly III version 4.7.2 

If you create any kind of transaction, and then without closing the page, click on the tab and select a different transaction type, the text on the button does not change in the block on the right.
![1](https://user-images.githubusercontent.com/520760/38427048-e239918c-39c0-11e8-87ce-25631d426a29.jpg)

**Comment by JC5** [comment]
This works in 4.7.2.2. I was not aware this was broken. Did you try doing a hard refresh (Command Shift R on mac, Shift F5 on Windows)?

**Comment by Nik-vr** [comment]
If I open the form for creating a new transaction with the "New transfer" button, when the page is loaded, the inscriptions on both buttons are correct. In the address line of the browser with this link:

/public/transactions/create/transfer

Then I just click in this form on the "Withdrawal" tab. The link in the address bar of the browser remains the same. The form changes at the same time. But the right button does not change the text on the button.
If I press F5, the page will reboot completely. And since in the address bar of the browser with this "/public/transactions/create/transfer", the form of transfet will be loaded again (although I have already opened the form of the expense by clicking on the tab).
But if I click on the "Save new ..." button without filling in one of the fields, the next page will reboot (with the error message) and the text on both buttons becomes the same. The link in the address bar of the browser at the same time remains the same, but the form is opened correctly.

**Comment by JC5** [comment]
OK. Which error exactly? Any errors in the console of your browser? Should be Ctrl-Shift-i in Chrome.

**Comment by Nik-vr** [comment]
Chrome concole (first load of page):

> Failed to decode downloaded font: /public/fonts/SourceSansPro-Italic-cyrillic.woff2
> transfer:1 OTS parsing error: cmap: No subtables in cmap!
> common.js?v=4.7.2:27 in common.js document.ready
> common.js?v=4.7.2:49 In setCommonAutoComplete()
> create.js?v=4.7.2:241 End of update form
> create.js?v=4.7.2:80 selectsDifferenctSource(): Set source account currency to 9
> create.js?v=4.7.2:104 selectsDifferentDestination(): Set destinationId account currency to 9
> common.js?v=4.7.2:93 In selectsForeignCurrency()
> transfer:1 Failed to decode downloaded font: /public/fonts/SourceSansPro-Italic-cyrillic.woff2
> transfer:1 OTS parsing error: cmap: No subtables in cmap!

After click on other tab has added:

> End of update form
> create.js?v=4.7.2:80 selectsDifferenctSource(): Set source account currency to 9
> common.js?v=4.7.2:93 In selectsForeignCurrency()
> create.js?v=4.7.2:96 User is making a withdrawal. Don't bother with destination.
> common.js?v=4.7.2:93 In selectsForeignCurrency()

**Comment by Nik-vr** [comment]
Unfortunately, the update to 4.7.2.2 did not help.

**Comment by JC5** [comment]
I honestly just got it. I apologize. I will fix it in the next release!

https://github.com/firefly-iii/firefly-iii/issues/1434
