### ISSUE TITLE
Giant tags

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1325]
I am running Firefly III version 4.7.2.2

#### Description of my issue:
The 'Tags' page displays giant tags. Tested in Chrome and Firefox:
![image](https://user-images.githubusercontent.com/317179/38452961-571a99a0-3a4e-11e8-8427-9722a68d64f4.png)

Some are even bigger than those in the screenshot. I dont't visit the tags page all too often but I'm sure this issue persists since upgrading to 4.7.2.
The demo site seems not to have this problem.

**Comment by JC5** [comment]
I thought I pushed a fix for this in 4.7.2.2 already. But it looks as if that one failed :(. I'll get it fixed!

**Comment by JC5** [comment]
OK, I've pushed a fix that works well on my personal installation. Tags now have a decent size (between 12 and 20px).

**Comment by JC5** [comment]
Closed to clean up the list.
