### ISSUE TITLE
bunq import gives error: A fatal error occurred

### ISSUE THREAD

**Issue by FreekBloemhof** [firefly-iii/firefly-iii#1330]
I am running Firefly III version 4.7.2.2

#### Description of my issue:
bunq import gives error: A fatal error occurred

Complete text:
A fatal error occurred, which the import-routine cannot recover from. Please see the explanation in red below.

Submitting the job returned an error: error Internal Server Error

If the error is a time-out, the import will have stopped half-way. For some server configurations, it is merely the server that stopped while the import keeps running in the background. To verify this, check out the log files. If the problem persists, consider importing over the command line instead.

#### Steps to reproduce 
New instance installed on AMPPS, created account and started bunq import.

#### Other important details (log files, system info):
Tried restarting instance but it did not matter.

**Comment by JC5** [comment]
Hi Freek, thanks for opening the issue. I did not want to overflow bunq's forums with debugging stuff.

There should be log files in `/firefly-iii/storage/logs`. The file should be called `ff3-fpm-fcgi-2018-04-08.log` (or a different date).

It should at least contain the error message, and we can work from there.

**Comment by FreekBloemhof** [comment]
Sure, not a problem!

Found the logging. 

I suppose this is the issue:

[2018-04-10 16:23:42] local.ERROR: Could not retrieve external IP: cURL error 60: SSL certificate problem: unable to get local issuer certificate {"userId":1,"email":"x@x","exception":"[object] (FireflyIII\\Exceptions\\FireflyException(code: 0): Could not retrieve external IP: cURL error 60: SSL certificate problem: unable to get local issuer certificate at C:\\Program Files (x86)\\Ampps\\www\\firefly\\app\\Import\\Routine\\BunqRoutine.php:547)

Are you expecting that firefly is connected directly to the internet?

**Comment by JC5** [comment]
Bunq wants to know the IP that will be linked to the API key. The easiest solution is to poll some external service and get the IP back. I’ll think about possible solutions.

**Comment by JC5** [comment]
I am surprised about the SSL error though. But that might be a Windows thing. I'll catch it and ask for user input.

**Comment by JC5** [comment]
I've added several routines to fix this problem. One is, that the import will ask for your IP. That way any errors will not break the import. This should be live with the next release which is around May 1st.

**Comment by japsikado** [comment]
I have installed firefly from the develop branch version 4.7.3 with the new fixes that are commited here https://github.com/firefly-iii/firefly-iii/commit/90cf7a3bf5f50dd2bd11f9ed09a826c4e0637571

but got the same issue: 'Submitting the job returned an error: error Internal Server Error' in red

I have running it locally in xampp, maybe if you run firefly locally bunq can't check the ip address, In the bunq app i have made a new ip with a wildcard in ip whitelisting, didn't work either.

i did tried my own sandbox api key but gives the same error.

error log

```
#84 {main}
"} 
[2018-04-20 12:24:53] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"openssl_pkey_export(): cannot get key from parameter 1","time":"Fri, 20 Apr 2018 12:24:53 +0000","file":"C:\\xampp\\htdocs\\firefly-iii\\app\\Import\\Routine\\BunqRoutine.php","line":392,"code":0,"version":"4.7.3"}  
[2018-04-20 12:24:53] local.ERROR: openssl_pkey_export(): cannot get key from parameter 1 {"userId":1,"email":"example@mail.com","exception":"[object] (ErrorException(code: 0): openssl_pkey_export(): cannot get key from parameter 1 at C:\\xampp\\htdocs\\firefly-iii\\app\\Import\\Routine\\BunqRoutine.php:392)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'openssl_pkey_ex...', 'C:\\\\xampp\\\\htdocs...', 392, Array)

```
srry for my bad english :P

**Comment by OGKevin** [comment]
Fresh newly generated key is giving the following error: 

```
production.ERROR: Bunq ERROR 400: User credentials are incorrect. Incorrect API key or IP address.
```

i'll read the code and help debug tomo to see why this could be happening. This error message (with an unregistered API key) normally means that either the key is for the wrong env. In this case I was using a PROD key. Or that the ip that is being sent does not match the ip where the request is actually originating from. I've triple checked and can confirm that ive filled to correct pub ip of my host. 🤔  

For now ill just import via CSV

**Comment by OGKevin** [comment]
Ah nvm `sandbox.public.api.bunq.com` 😊
