### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by cyberax17** [firefly-iii/firefly-iii#1333]
Hi,
Which would be the best / most recommended way to backup the firefly iii installation and data? 
I have it running in a VM right now.

Cheers and thanks
Andy

**Comment by cyberax17** [comment]
Thanks,
Does this include all attachments and other personal files in firefly then? 
Cheers

**Comment by JC5** [comment]
Good point, I forgot those! Back up the folders storage/upload and storage/export as well. 

I will add something to the documentation.

**Comment by lverissimo** [comment]
James,
Just out of curiosity. What are those folders used for? storage/upload and storage/export ?
Regads,
Luis

**Comment by cyberax17** [comment]
Great thanks James!! Really a pleasure to work with this piece of nice software :-)

**Comment by lverissimo** [comment]
James, thanks! it is clear!

**Comment by JC5** [comment]
They're used for the API. They can be regenerated, if you need them.

**Comment by ErikFontanel** [comment]
I use these scripts to automatically backup my database:

https://gist.github.com/ErikFontanel/74b91628f3c8c7241fd09dc5a182cc01

Feel free to fork them and use them to your liking :)

**Comment by nhaarman** [comment]
Perhaps including [Laravel-Backup](https://github.com/spatie/laravel-backup) would be an option?
