### ISSUE TITLE
Piggy bank currency issue

### ISSUE THREAD

**Issue by Sovica** [firefly-iii/firefly-iii#1334]
I am running Firefly III version 4.7.2.2 

#### Description of my issue:
Whenever I create a new piggy bank, I set it to a specific currency ($ or euro) but the moment I save it, it appears in my piggy bank list but with my default set currency (new custom set currency) on the platform level.

#### Steps to reproduce 

Reproducible on demo site as well. Just create a new currency and set it as default. Then navigate to your piggy bank list and you should see all piggy banks inherited the default currency setting including the account which it is tied to.

#### Other important details (log files, system info):

Nothing special here. A new Firefly III installation from Softaculous on a shared hosting provider.
Debug info here:

Debug information generated at 2018-04-12 09:52:43 UTC for Firefly III version **4.7.2.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.2.2 |
| FF API version | 0.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.16 |
| Display errors | Off |
| Session start | 2018-04-01 00:00:00 |
| Session end | 2018-04-30 23:59:59 |
| Session first | 2018-04-10 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | litespeed |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | 'en_US' |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, litespeed, PDO, pdo_mysql, fileinfo, intl, bcmath, Phar, gd, xmlwriter, sockets, json, exif, soap, zip, mysqli, imap, dom, mysqlnd, pdo_sqlite, xmlreader, posix, mcrypt |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@5.0.0, defuse/php-encryption@v2.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.6.3, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.0.0, egulias/email-validator@2.1.3, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.2, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.15, laravel/passport@v5.0.3, laravelcollective/html@v5.6.5, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.3, league/event@2.1.2, league/flysystem@1.0.43, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.11, phpseclib/phpseclib@2.0.10, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.0.6, symfony/css-selector@v4.0.6, symfony/debug@v4.0.6, symfony/event-dispatcher@v4.0.6, symfony/finder@v4.0.6, symfony/http-foundation@v4.0.6, symfony/http-kernel@v4.0.6, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php72@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v4.0.6, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.0.6, symfony/translation@v4.0.6, symfony/var-dumper@v4.0.6, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.1,  |

**Comment by JC5** [comment]
Piggy banks are tied to the account you're saving on, so setting a currency is kind of strange. I will make sure that:

1. In the future, you cannot set a currency for the piggy bank (since the account determines the currency).
2. All views will correctly report the currency (so € or $ or whatever the account has).

I think that would solve your problem, right?

**Comment by Sovica** [comment]
Yeah I think that should work. Thanks!

**Comment by JC5** [comment]
This is now available on the demo site and will be featured in the next release. To clean up the list, I will close this issue.
