### ISSUE TITLE
Import: CSV-import duplicates transactions check fails

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1335]
I am running Firefly III version 4.7.2.2 

#### Description of my issue:

I believe that since updating to `4.7.2.2`, the import duplicate check fails allthough the exact same file has already been imported.

I have a cron-job running 3 times / day which downloads, converts and imports the data into FF. I had some bank connection issues and did not notice this since I updated to `4.7.2.2` because I had to "reset" the last month.

I tested this via CLI and via WebUI:
1. download CSV from bank
2. import
3. check result: `The 2 transactions imported can be found in tag...`
4. import **same** csv
5. check result: `The 2 transactions imported can be found in tag...`

#### Steps to reproduce 

CSV:
```
Date;Asset account (IBAN);Opposing account (IBAN);Amount;Currency code (ISO 4217);Description;Notes
2018/04/11;DE00000000000000000001;DE00000000000000000002;-8.10;EUR;Shop - 090417151798792191256012785 SHOP. 66300183           ;Shop - 090417151798792191256012785 SHOP. 66300183
2018/04/11;DE00000000000000000001;DE00000000000000000003;-12.41;EUR;SHOP - 090417022113894191220010120 ELV65334967 09.04 17.02 ME2           ;SHOP - 090417022113894191220010120 ELV65334967 09.04 17.02 ME2
```

#### Other important details (log files, system info):

I could not test it on the demo since importing is restricted

**Comment by JC5** [comment]
Mmmm I’ll do some research! Thanks for letting me know!

**Comment by gavu** [comment]
No problem, just let me know if you need _anything_. Maybe it's connected to the UTF-8 check of the csv-files you were talking about in other issues? .. just a thought

**Comment by JC5** [comment]
Found the problem, will be fixed. The storage routine didn't store the hashes, so no comparisons could be made.

**Comment by JC5** [comment]
Closed to clean up the list.
