### ISSUE TITLE
need help installing firefly (404) on /install

### ISSUE THREAD

**Issue by jasondaigo** [firefly-iii/firefly-iii#1337]
I am running Firefly III version 4.7.2.2 

#### Steps to reproduce 
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-4.7.2.2
created mysql database &user homestead, granted access 
edited [.env file](https://pastebin.com/kaq2tBtq)
php artisan migrate:refresh --seed (passed)
php artisan passport:install (passed)
created additional [nginx conf file](https://pastebin.com/UyQFVhAg) & reload NGINX
when i call money.jasondaigo.de he redirects to money.jasondaigo.de/install and shows 404 not found
i dont even know why he calls that url. if root changed to firefly root it shows the common known "dont expose public" error

**Comment by jasondaigo** [comment]
error log is empty

**Comment by jasondaigo** [comment]
php artisan firefly:verify
No orphaned transactions!
No orphaned journals!
All link types OK!
All access tokens OK!
Amount integrity OK!

**Comment by jasondaigo** [comment]
thanks for reply man ; works now anyway; i copied something stupid from elsewhere :-) 
many thanks

**Comment by JC5** [comment]
:+1:
