### ISSUE TITLE
Is Firefly compatible with PHP 7.2 ?

### ISSUE THREAD

**Issue by Limezy** [firefly-iii/firefly-iii#1342]
I am currently running Firefly III version 4.7.1.3.
I have tried to update to Firefly 4.7.2.2 but I get a white page.
I suspect my PHP version (7.2.x) to be my problem.
Is Firefly compatible with PHP 7.2.x ? If not maybe you could indicate that in the documentation ?

Thanks for this awsome piece of software I plan to use everyday.

**Comment by Limezy** [comment]
```
[2018-04-15 07:45:28] local.ERROR: Preference #5 ("currencyPreference") was stored as serialised object. It will be deleted and recreated.  
[2018-04-15 07:45:36] local.ERROR: Preference #18 ("access_token") was stored as serialised object. It will be deleted and recreated.
```
Nothing related, I guess ?

**Comment by JC5** [comment]
Nope, should not matter. Are access rights OK? If you delete all log files, are they recreated when you reload the page? 

I've just pushed a test build that includes PHP 7.2

https://travis-ci.org/firefly-iii/firefly-iii/builds/366724130

**Comment by Limezy** [comment]
All good ! Fixed by changing access rights.
Sorry for that !

**Comment by JC5** [comment]
No problem! :+1:
