### ISSUE TITLE
Cannot edit Expense account

### ISSUE THREAD

**Issue by Limezy** [firefly-iii/firefly-iii#1343]
I am running Firefly III version 4.7.1.3

Steps to reproduce : 
1. Create expense account
2. Edit expense account

I get : 

> Whoops! An error occurred.
> 
> Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> 
> Trying to get property 'id' of non-object
> 
> More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.
> 
> If you cannot find the cause of this error or when you need some help, please open a ticket on GitHub.

**Comment by JC5** [comment]
This is fixed in [4.7.2](https://github.com/firefly-iii/firefly-iii/releases) or higher.
