### ISSUE TITLE
Transaction added by API not showing up on transaction list

### ISSUE THREAD

**Issue by tornoz** [firefly-iii/firefly-iii#1347]
I am running Firefly III version 4.7.2.2

#### Description of my issue:

When adding a transaction with the API, it does not show up in the transaction list.
The balance and the graphics are correctly updated, but the transaction doesn't show up on the Transactions > Expenses page or on the dashboard widget. It does show up on the account page, though.
If there is a modification to another transaction through the web UI, the transaction added by the API show up.

#### Steps to reproduce 

* Create withdrawal transaction through API
Example: 

{"type":"withdrawal","description":"TEST TORNOZ","date":"2018-04-16","transactions":[{"source_id":"1","destination_name":"TEST","currency_code":"EUR","description":"TEST","amount":"42"}]}

* Go to https://demo.firefly-iii.org/accounts/show/1
* Transaction is there
* Go to https://demo.firefly-iii.org/transactions/withdrawal
* The transaction is not there

**Comment by JC5** [comment]
Thanks for reporting this! 

I have confirmed what you mean. The transactions are visible in the search but not in the list. I see several errors popping up. I will do some research.

Note that the demo sites resets pretty often so they might be gone in a few hours.

**Comment by JC5** [comment]
I believe this one is fixed as well. Can you confirm?
