### ISSUE TITLE
Import CSV : Transfer can be a "deposit"

### ISSUE THREAD

**Issue by NyKoF** [firefly-iii/firefly-iii#1349]
I am running Firefly III version 4.7.2.2

#### Description of my issue:
When I import a csv, I have transfers between my own accounts. If the amount is positive, the asset account and the destination account are not switched.

#### Steps to reproduce 
Import a CSV with two transfer between asset accounts :
- one having a negative amount
- one with a positive amount

#### Other important details (log files, system info):
To fix the problem with my csv file, I have modified ImportStorage.php at line 227 from :
`if ($transactionType === TransactionType::DEPOSIT) {`

to :

`if ($transactionType === TransactionType::DEPOSIT || $transactionType === TransactionType::TRANSFER && 1 === bccomp($amount, '0')) {`

**Comment by JC5** [comment]
Could you share some example lines and your config with me? I can't reproduce this using the most basic settings, so something must be messing up the import. Attached you will find my test CSV file and the associated JSON file. You can use the command line to quickly import these files:

```
php artisan firefly:create-import two-transfers.csv two-transfers.json --start --token=<TOKEN HERE> --user=1
```

Please note that my Checking Account has ID 1 and Savings Account has ID 2.

![screen shot 2018-04-16 at 19 55 05](https://user-images.githubusercontent.com/5889984/38826438-1aaa40b0-41b0-11e8-8eff-6703ee62d90f.png)


[two-transfers.csv.txt](https://github.com/firefly-iii/firefly-iii/files/1916573/two-transfers.csv.txt)
[two-transfers.json.txt](https://github.com/firefly-iii/firefly-iii/files/1916574/two-transfers.json.txt)

**Comment by NyKoF** [comment]
In fact, my bank would have given me the following CSV lines for the same transfers : 

Checking,Saving,20170101,"Some test from Checking to Saving",12.34
Checking,Saving,20170101,"Some test from Saving to Checking",-45.67

**Comment by JC5** [comment]
Lol of course, sorry about that. I'll check it out tonight.

**Comment by JC5** [comment]
Confirmed. A fix is on the way.

**Comment by JC5** [comment]
Please note that I did reverse your bccomp instruction. In the example CSV as you corrected it, the negative amount indicates that Checking is _losing_ the money. So, to get that imported correctly, the comparison function must be reversed.
