### ISSUE TITLE
Cannot change spectre import settings

### ISSUE THREAD

**Issue by bconte** [firefly-iii/firefly-iii#1351]
I am running Firefly III version 4.7.3

#### Description of my issue:
Can't reset spectre import settings

#### Steps to reproduce 
1. Try to find a place to change spectre import settings

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):
I put in incorrect information, but now I can't clear it to put in correct information.

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by bconte** [comment]
Pretty much all of them.  I put the wrong values in the wrong fields
(secret, key, app).  Basically i want to be able to reset it and start over.

**Comment by JC5** [comment]
Ah cool, I wasn't thinking of those. Such an interface does not exist yet. However, in your database (the `preferences`-table) you can safely delete the entries that contain "spectre". Verify with me if you want to be sure.

Then, browse to `/flush` on your installation to reset the cache.

**Comment by JC5** [comment]
I've pushed code for a simple interface. It is [visible on the demo site](https://demo.firefly-iii.org/import)
