### ISSUE TITLE
Not all users have a company

### ISSUE THREAD

**Issue by Want100Cookies** [firefly-iii/firefly-iii#1352]
https://github.com/firefly-iii/firefly-iii/blob/ebbbe1a62030f8836fc1da80b71dfadce3264bfa/app/Services/Bunq/Request/DeviceSessionRequest.php#L62

Wanted to try out Firefly III with bunq but could not get it set up. 
I got stuck at this point.
After some investigation I found out that the response array does not contain a UserCompany key for me, only the UserPerson key. Perhaps because I do not have a company. 

I do find it weird the bunq docs say the UserCompany is a required child in the response (source: https://doc.bunq.com/api/1/call/session-server/method/post)

Perhaps checking if the keys exists before creating the objects?

**Comment by JC5** [comment]
I’ll make sure it will work with a user only. I was under the impression it did already. But alas!

Thanks for the feedback! :+1:

**Comment by JC5** [comment]
I assumed that the company would always be present, as the documentation suggests ☹️ 

I have added a fix for the next release, but I'll need you to test it to be sure it works. So please keep an eye on it at the end of the month and let me know if the problem is fixed!
