### ISSUE TITLE
Recurring transactions for regular income

### ISSUE THREAD

**Issue by Phenex1978** [firefly-iii/firefly-iii#1354]
I am running Firefly III version 4.7.2.2

#### Description of my issue:
Would it be possible to add a feature to automatically generate recurring transactions (like Gnucash) ? It would be great for regular income like salaries (may be linked to issue #995 ?) 

If it's not possible (or not easily), would it be possible to generate this kind of action through the console (to add it in a cron job for instance) ?

Thanx

**Comment by JC5** [comment]
Yes, this is on the list somewhere. For the cron job, you could technically use the API but it would have to be complex cURL commands so that's far from ideal.

**Comment by JC5** [comment]
Please subscribe to, or comment on #1469 to track progress of this feature :+1:
