### ISSUE TITLE
Balance is wrong.

### ISSUE THREAD

**Issue by jcgruenhage** [firefly-iii/firefly-iii#1355]
I am running Firefly III version 4.7.2.2

#### Description of my issue:
The current balance of my accounts is wrong. I've triple checked every transaction and manually calculated it too. Firefly seems to think I have about 239£ in my account, my bank and I are sure its 236£. For my wallet it's even worse, it currently has 6.60£ in it, Firefly claims it has 27£. I'd rather not share too much more information about my transactions publicly, that's private data after all, I could give you access to the system for debugging if that would help though. What's even weirder, Firefly correctly calculates the totally spend money, and subtracting that from the initial incoming transfer would result in the right balance.

#### Steps to reproduce 
No idea

#### Other important details (log files, system info):

I run the official Docker Container on a Fedora 27 Host.
Debug information generated at 2018-04-18 21:00:41 UTC for Firefly III version **4.7.2.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.2.2 |
| FF API version | 0.1 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.15 |
| Display errors | Off |
| Session start | 2018-04-01 00:00:00 |
| Session end | 2018-04-30 23:59:59 |
| Session first | 2017-10-13 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, pdo_mysql, pdo_pgsql, tidy, zip |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@5.0.0, defuse/php-encryption@v2.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.0.0, egulias/email-validator@2.1.3, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.2, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.15, laravel/passport@v5.0.3, laravelcollective/html@v5.6.5, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.3, league/event@2.1.2, league/flysystem@1.0.43, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.11, phpseclib/phpseclib@2.0.10, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.0.7, symfony/css-selector@v4.0.7, symfony/debug@v4.0.7, symfony/event-dispatcher@v4.0.7, symfony/finder@v4.0.7, symfony/http-foundation@v4.0.7, symfony/http-kernel@v4.0.7, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php72@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v4.0.7, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.0.7, symfony/translation@v4.0.7, symfony/var-dumper@v4.0.7, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.1,  |

**Comment by JC5** [comment]
Could you tell me _exactly_ which balance indicators are wrong? Make screenshots if possible. There are a lot of them.

Another question: could you browse to `/flush` to clear your cache?

**Comment by jcgruenhage** [comment]
It's wrong in all places I could find..

<img width="298" alt="screen shot 2018-04-19 at 11 40 23" src="https://user-images.githubusercontent.com/6861958/38987149-b423e9fe-43c6-11e8-8cc2-24a559c68437.png">
<img width="172" alt="screen shot 2018-04-19 at 11 40 39" src="https://user-images.githubusercontent.com/6861958/38987150-b437c384-43c6-11e8-9755-f88a7b088035.png">

Those screenshots don't seem very helpful, but that's the wrong balance in multiple places. If needed I can take larger screenshots and blur out sensible data later.

Navigating to `/flush` didn't seem to have any effect..

**Comment by JC5** [comment]
I have to find out what is causing this before I can conclude this is a bug. It’s so bad that there’s no way this app would even work for anybody without me noticing. Since my inbox is not overflowing with people complaining about bad balances it’s probably a very obscure bug, not a very big one. 

Having said that, it sucks and it should not happen at all! 

What I will do tonight is try to see what could be broken, potentially with the code behind these balance indicators. If I cannot find anything, I might need from you a minimal set of (private) data that shows a broken balance. 

Which rough edges did you see, besides this one? Make sure you open issues and ill fix those too ;)

**Comment by jcgruenhage** [comment]
I had some issues with not being able to update transactions in the past, the network log in the firefox log said there were some HTTP 302s in there, causing a POST to get converted to a GET.. but that works now and might have been my reverse proxy.

**Comment by jcgruenhage** [comment]
On the balance thing: I believe it has started with some split GBP withdrawels.

**Comment by JC5** [comment]
Good to know! I’ll try to replicate that.

**Comment by jcgruenhage** [comment]
Is there a more private way to reach you than this issue tracker or your google mail address?

**Comment by JC5** [comment]
You can use my PGP key to encrypt any private data.  https://keybase.io/jc5

**Comment by jcgruenhage** [comment]
Oh yeah, that should work

**Comment by jcgruenhage** [comment]
So the issue seems to be fixed on develop (no idea what was causing it)
