### ISSUE TITLE
Merging expense accounts?

### ISSUE THREAD

**Issue by jp1987** [firefly-iii/firefly-iii#1359]
First of all, excellent tool, thanks very much for all the effort that goes into this!

I wonder if it's possible to merge expense accounts? When making payments to (for instance) Albert Heijn, the description is sometimes different depending on the source bank account (ING or ABN), for instance:

ABN: Albert Heijn 1596 HELLEV
ING: Albert Heijn 1596 HELLEVOETSLUI

I guess this is possible to map during the import? When doing large imports, it's a bit tedious to find out which expense accounts should be merged, so it would be nice to be able to do it from the Expense Accounts GUI afterwards. Good idea or no? :)

**Comment by JC5** [comment]
You can also use rules to do this. These will trigger during import (if configured correctly) and set the right expense account. 

There is also a mass-edit button at the bottom of each list of transactions.

But a merge tool is not available, and probably won't be.

**Comment by JC5** [comment]
And of course, thanks for the compliments! 😀

**Comment by jp1987** [comment]
Sounds good, thanks!
