### ISSUE TITLE
Importing MT940 bank statements

### ISSUE THREAD

**Issue by JamborJan** [firefly-iii/firefly-iii#1360]
I am running Firefly III version 4.7.2.2 (on Sandstorm)

#### Description of my issue:
I would like to import MT940 bank statements (*.STA files I can download from my bank) into Firefly iii to keep my information in Fyerfly iii up to date.

#### Steps to reproduce 
It's not possible right now to import MT940 *.STA files. Converting them to CSV seems also to be a pain as I didn't find a proper solution yet.

#### Other important details (log files, system info):
I'm not sure that helps as I didn't start any import ...

**Comment by JC5** [comment]
I thought about it before, yes, and it's on the list!

**Comment by JamborJan** [comment]
Awesome! If there is anything I can do to help implementing / testing this, please let me know. Thanks for all the good work!

**Comment by tobru** [comment]
Looking forward to this feature as my bank (ZKB - Zürcher Kantonalbank) offers this data format. Unfortunately the available CSV formats from ZKB are not useable.

**Comment by timothydejongh** [comment]
Also looking forward since my bank ABN AMRO does not export CSV.

**Comment by tobru** [comment]
@JC5 Do you have any plans to implement MT940 import in the near future?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520

**Comment by JamborJan** [comment]
I like the idea postet in the roadmap to use an API for imports. This gives on the one hand a lot of options and flexibility for imports and in the other hand it streamlines code within firefly. As far as I can say now: wise choise!
