### ISSUE TITLE
Cant run 4.7.2.2 via docker-compose due to mysql errors. 

### ISSUE THREAD

**Issue by OGKevin** [firefly-iii/firefly-iii#1366]
I am running Firefly III version `4.7.2.2`

#### Description of my issue:
After getting the docker containers up. When executing the migrations I'll encounter a mysql error
```
  SQLSTATE[HY000] [2054] The server requested authentication method unknown t
  o the client (SQL: select * from information_schema.tables where table_sche
  ma = firefly_db and table_name = migrations)
```

After some googling I decided to downgrade and use mysql:5.7 where then I ran in the following error:
```
 php_network_getaddresses: getaddrinfo failed: No add
  ress associated with hostname (SQL: select * from information_schema.tables
   where table_schema = firefly_db and table_name = migrations)
```

Which sounds like the php is missing an extension ? 

#### Steps to reproduce 
Follow the docker compose guide located at http://firefly-iii.readthedocs.io/en/latest/installation/docker.html#download-compose-file

#### Other important details (log files, system info):
Running on ubuntu 16.04

**Comment by JC5** [comment]
Thanks for letting me know! I appreciate the feedback.

I'm getting pretty tired of the issues the MySQL images seem to have, so I will experiment with replacing it with mariadb.

**Comment by JC5** [comment]
OK, as far as I can tell Firefly III works fine with mariaDB. I have to see if this solves the issues people have. I'm closing this one to clear the list. Please tell me if you run into problems, OK?

**Comment by OGKevin** [comment]
Can confirm it is working now! 

BTW, feel free to contact me if you need some help working on the bunq integration see my GitHub profile 😉

**Comment by JC5** [comment]
I will :+1: :D
