### ISSUE TITLE
Implement new layout

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1368]
https://www.creative-tim.com/product/material-dashboard-pro-angular2

Donations are appreciated :wink:

**Comment by anykia** [comment]
What do you think about: [ng-alain](https://cipchk.github.io/ng-alain)?

**Comment by JC5** [comment]
Not bad, I'll check it out!

**Comment by OGKevin** [comment]
What about https://tabler.github.io/ ?

**Comment by Kovah** [comment]
Ah darn, have absolutely no experience with Angular so wouldn't able to help with this. :/

**Comment by JC5** [comment]
See the column in the roadmap.
