### ISSUE TITLE
Rule matching not finding records

### ISSUE THREAD

**Issue by PeterXQChen** [firefly-iii/firefly-iii#1371]
Hi,

Im running the latest version of Firefly and very pleased with it so far (1st day).

Im having issues setting rules for some of my transactions, they rules dont seem to match if I use the exact term when filtering against description.

e.g.

Description = Master Card Payment

Rule:
Description is: "Master Card Payment"

With the rule above, it finds 0 records, however when I use "Master Card" as the rule, it finds all the records that contains Master Card.

Im not sure if its a bug or Im just using it wrong.

Thanks,
Peter

**Comment by JC5** [comment]
Hi, thanks for reporting this!

I did a quick test on the [demo site](https://demo.firefly-iii.org/) and it seems to work as advertised. I made a rule with trigger "Description is" and value "Master Card Payment". It correctly triggers for transactions with description "Master Card Payment". These rules are not case sensitive by the way.

I assume that in the second case, you've used "Description contains.."?

Check if you're having extra spaces in the values. That might be it. When you still can't find anything, you can turn on [debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) and scan the logs when you create a transaction that should match.

Let me know if this helps!

**Comment by PeterXQChen** [comment]
Hi JC5,

Thanks for the quick response! It seems like there were multiple spaces between two words that wasnt being shown on the page, could only be seen when viewing the source. All of the transactions were imported and in the original file those records didnt have those spaces. I'll see if its reproducible.

Thanks,
Peter

**Comment by JC5** [comment]
Which browser are you using? The spaces you mention will not be visible on the /rules page, but they should be visible when editing the rule. Is that behavior the same with you?
