### ISSUE TITLE
Budget always on overspent

### ISSUE THREAD

**Issue by ImLemni** [firefly-iii/firefly-iii#1373]
I am running Firefly III version 4.7.2.1, also visible on the demo version

#### Description of my issue:

The dashboard should show the remaining amount of money in all the budget while it has not reached the "overspent" state for the sum of all budgets, that seems to have been introduced in https://github.com/firefly-iii/firefly-iii/issues/1247 . 
It seems to always show the total spend amount.

![image](https://user-images.githubusercontent.com/6094111/39125831-aa86eeea-4700-11e8-928b-6d3e062614b0.png)
![image](https://user-images.githubusercontent.com/6094111/39125904-e3f2494a-4700-11e8-9e98-eb9f93a1e2db.png)

#### Steps to reproduce 

Probably just create a budget and a withdrawal. 
It is possible that is is a feature and not a bug.

**Comment by ImLemni** [comment]
Thank you for your quick answer, indeed it does work. 
Would you consider set the value to the sum if no other value is specified ?

**Comment by JC5** [comment]
I'm sorry no, it's always a manual action. The budgets themselves and this amount can differ in date-range.
