### ISSUE TITLE
There is no dot separator for coins in russian translation

### ISSUE THREAD

**Issue by Acvarium** [firefly-iii/firefly-iii#1374]
I am running Firefly III version 4.7.2.2

#### Description of my issue:
Instead of $123.45 I see $123456 when I switch to russian translation

#### Other important details (log files, system info):
And this is even can be recreated on demo page

**Comment by Acvarium** [comment]
The same with all the languages except English and French

**Comment by Acvarium** [comment]
Sorry. I found your explanation about 'Missing locale packages'

**Comment by JC5** [comment]
Glad to hear it's fixed! :+1:
