### ISSUE TITLE
SimpleXMLElement not found

### ISSUE THREAD

**Issue by mbinns** [firefly-iii/firefly-iii#1375]
I am running Firefly III version 4.7.1.3

#### Description of my issue:
Application was working great, until I enabled update checking. After which the application crashes after successful log in with the following screen.

![image](https://user-images.githubusercontent.com/14008591/39162791-1553053a-472c-11e8-959f-424658d63b18.png)

Went to log files to track down the error, identified two errors related to SELinux

1. httpd cannot send email
`local.ERROR: Swift Transport ExceptionConnection could not be established with host smtp.mailtrap.io [Permission denied #13`
This was resolved by:
`setsebool -P httpd_can_sendmail 1`

2. httpd cannot connect to internet resource, same error as above
resolved by
`setsebool -P httpd_can_network_connect 1`

Neither of those resolved the issue. But the error message below cropped up which I think is the true cause of the issue.

3. SimpleXML missing
`local.ERROR: Class 'SimpleXMLElement' not found {"userId":1,"email":"mackbinns@gmail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'SimpleXMLElement' not found at /usr/share/nginx/html/firefly-iii/app/Services/Github/Request/UpdateRequest.php:57)"}`

Attempted troubleshooting:
- Install php-simplexml (for php version 7+)
- php artisan cache:clear
- restart nginx

None of those steps work, and I am at a loss on next steps?

#### Steps to reproduce 
Enable update checking on centos minimal install with SElinux enabled, and the installation guide followed. Application was working before setting was enabled

#### Other important details (log files, system info):
Cannot get to the debugging information

Thanks!

**Comment by JC5** [comment]
It seems that last step should have done it. PHP xml is required to parse the result from Github. 

- I will update the config so it will use "log" by default as email delivery system.
- Not being allowed online is something I can't help in an update checker :wink:

Did you also reset php-fpm, if relevant?

**Comment by mbinns** [comment]
The restart of php-fpm was the missing link.

Thank you for your great application and time 😃
