### ISSUE TITLE
Add rolling budget support?

### ISSUE THREAD

**Issue by Sovica** [firefly-iii/firefly-iii#1376]
This is a feature request of course.

It would be nice if FF III would support rolling budgets. 
Example:

Let's say you have a budget with a limit of $100 and spend only $75, then $25 rolls over and your limit for the next month would be $125. Similarly, if you spend $120, then the next month leaves you with a limit of $80.

**Comment by JC5** [comment]
Thanks for the suggestion! Firefly III focuses on budgeting again every month. If you want to make budgets roll-over, this is something you must do yourself.

**Comment by Sovica** [comment]
As I mentioned, it's more of a quality of life kind of thing that would speed up budgeting for next month etc. I can do without it just thought it would be a nice feature. 

If I get the time to look into the code on how to do this, would you accept a pull request?

**Comment by JC5** [comment]
Although I appreciate the argument, I'm afraid I must decline. Rollover can "auto-fill" the next budget but that budget needs to be adjusted anyway since you have money left. That is a way more important step than it is to fill it with a small amount. I don't want to add magic, where the system assumes that this is actually what you want to use the money for.

I would rather have users take action on this manually, so they execute these actions consciously and deliberately.

**Comment by Sovica** [comment]
Fair enough. Feel free to close the thread.

**Comment by JC5** [comment]
Will do. Don't hesitate to open more issues if you think of something :+1:

**Comment by mrahmadt** [comment]
@JC5 

This is a very important feature for me, I want to be able to allocate a monthly budget for my personal expenses, car, travel...etc. to make sure I'm controlling my spending on a monthly bases.

Anyway, I'm planning to use the API to automate this part, hopefully, maybe you will change your mind later and make it in your code :-)

**Comment by JC5** [comment]
You can already do that. But if there is money left it will not be set to the next month automatically.

**Comment by jcrben** [comment]
Is there any chance you might be open to making this configurable, if someone were to put in the work? Or is there some way to build it as an extension? YNAB-style rollover budgeting is quite popular, and I know it's super helpful for me...

**Comment by JC5** [comment]
Sorry, nope.

**Comment by zawnk** [comment]
Just +1ing here. Now that YNAB's development (on the client) is about to be stopped, I'm evaluating Firefly currently. I get that you don't want to auto-fill the next month's budget (even though that would be ideal), is there a way or possibility, that the balance from this balance from last month can be shown? E.g. you budget in November 2019 100 EUR for clothes, but only spend 80 EUR. When you enter the budgets for December 2019, it shows the +20 EUR somewhere on that page, so I can at least manually enter 120 EUR without having to check on the other page for each budget. Any chance?

**Comment by JC5** [comment]
Hi all. Just to inform you that this feature will be implemented. See #2578 for more details.
