### ISSUE TITLE
Cannot initialise new mysql database using docker

### ISSUE THREAD

**Issue by peedub** [firefly-iii/firefly-iii#1382]
I am running Firefly III version 7.2.2. using most current docker-compose.yml from GitHub

#### Description of my issue:
When initialising the newly created mysql database, I get the following errors:

`In Connection.php line 664:
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = firefly_db and table_name = migrations)`

`In PDOConnection.php line 50:
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client`

`In PDOConnection.php line 46:
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client`

`In PDOConnection.php line 46:
PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]`

#### Steps to reproduce 
Follow instructions as per http://firefly-iii.readthedocs.io/en/latest/installation/docker.html#docker-hub-with-automatic-updates-via-docker-compose
Try to initialise the mysql database: 
`docker-compose exec firefly_iii_app php artisan migrate --seed`

#### Other important details (log files, system info):
mysql:latest
jc5x/firefly-iii:latest

**Comment by peedub** [comment]
A workaround is to use mariadb:latest in place of mysql:latest

**Comment by JC5** [comment]
No that should work. Did you run all of the the migration commands?

I suspect that an answer might be in the log files. In your docker container, find /var/www/firefly-iii/storage/logs/laravel.log.

It might hold the answer!

**Comment by peedub** [comment]
Having trouble seeing anything obviously wrong here.

`[2018-04-26 08:15:18] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:181)
[stacktrace]
#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(115): Illuminate\\Log\\LogManager->resolve('')
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(103): Illuminate\\Log\\LogManager->get('')
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(519): Illuminate\\Log\\LogManager->driver()
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(113): Illuminate\\Log\\LogManager->error('Command \"optimi...', Array)
#4 /var/www/firefly-iii/app/Exceptions/Handler.php(150): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Symfony\\Component\\Console\\Exception\\CommandNotFoundException))
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(353): FireflyIII\\Exceptions\\Handler->report(Object(Symfony\\Component\\Console\\Exception\\CommandNotFoundException))
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(124): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Symfony\\Component\\Console\\Exception\\CommandNotFoundException))
#7 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 {main}
"} 
[2018-04-26 08:15:18] laravel.ERROR: Command "optimize" is not defined. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"optimize\" is not defined. at /var/www/firefly-iii/vendor/symfony/console/Application.php:611)
[stacktrace]
#0 /var/www/firefly-iii/vendor/symfony/console/Application.php(224): Symfony\\Component\\Console\\Application->find('optimize')
#1 /var/www/firefly-iii/vendor/symfony/console/Application.php(143): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"} 
[2018-04-26 08:16:01] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:181)
[stacktrace]
#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(115): Illuminate\\Log\\LogManager->resolve('')
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(103): Illuminate\\Log\\LogManager->get('')
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(535): Illuminate\\Log\\LogManager->driver()
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Log\\LogManager->warning('No database ver...')
#4 /var/www/firefly-iii/database/seeds/ConfigSeeder.php(18): Illuminate\\Support\\Facades\\Facade::__callStatic('warning', Array)
#5 [internal function]: ConfigSeeder->run()
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(122): Illuminate\\Container\\Container->call(Array)
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(42): Illuminate\\Database\\Seeder->__invoke()
#12 /var/www/firefly-iii/database/seeds/DatabaseSeeder.php(40): Illuminate\\Database\\Seeder->call('ConfigSeeder')
#13 [internal function]: DatabaseSeeder->run()
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(122): Illuminate\\Container\\Container->call(Array)
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): Illuminate\\Database\\Seeder->__invoke()
#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php(122): Illuminate\\Database\\Console\\Seeds\\SeedCommand->Illuminate\\Database\\Console\\Seeds\\{closure}()
#21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\\Database\\Eloquent\\Model::unguarded(Object(Closure))
#22 [internal function]: Illuminate\\Database\\Console\\Seeds\\SeedCommand->handle()
#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#28 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(198): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Console\\Command->call('db:seed', Array)
#32 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#38 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#39 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#40 /var/www/firefly-iii/vendor/symfony/console/Application.php(865): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 /var/www/firefly-iii/vendor/symfony/console/Application.php(241): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 /var/www/firefly-iii/vendor/symfony/console/Application.php(143): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 {main}
"} 
[2018-04-26 08:16:01] laravel.WARNING: No database version entry is present. Database is assumed to be OLD (version 1).  
`

**Comment by JC5** [comment]
Which LOG_CHANNEL is in your .env file?

**Comment by peedub** [comment]
I don't have a .env file, only the docker-compose.yml file. When I run docker logs firefly... I see this line: # The log channel defines where your log entries go to.
LOG_CHANNEL=

It's blank.

**Comment by JC5** [comment]
A fix is live, and the results are as follows (for me).

To test this, please pull "image: jc5x/firefly-iii:develop" and of course `image: "mariadb:latest"`.

This will be reflected in the next release.

```
Mac-mini:issue-1382 james$ docker-compose -f docker-compose.yml up -d
Creating network "issue-1382_firefly_iii_net" with driver "bridge"
Creating volume "issue-1382_firefly_iii_db" with default driver
Creating volume "issue-1382_firefly_iii_export" with default driver
Creating volume "issue-1382_firefly_iii_upload" with default driver
Pulling firefly_iii_db (mariadb:latest)...
latest: Pulling from library/mariadb
f2b6b4884fc8: Pull complete
26d8bdca4f3e: Pull complete
74f09e820cce: Pull complete
5390f1fe4554: Pull complete
3d3f1706a741: Pull complete
2942f66426ea: Pull complete
97ee11d39c75: Pull complete
590c46ef722b: Pull complete
32eb4b9666e5: Pull complete
fc883f98a064: Pull complete
bb8bee61bc1e: Pull complete
Digest: sha256:6135f5b851e7fe263dcf0edf3480cdab1ab28c4287e867c5d83fbe967412ea14
Status: Downloaded newer image for mariadb:latest
Pulling firefly_iii_app (jc5x/firefly-iii:develop)...
develop: Pulling from jc5x/firefly-iii
f2b6b4884fc8: Already exists
8db887c45800: Pull complete
6e0e41c52c70: Pull complete
fbc9ac078c49: Pull complete
c4c6f6be7488: Pull complete
a28db8adaf05: Pull complete
61afa9c0aff1: Pull complete
a30b1659c046: Pull complete
b04c4f5caef7: Pull complete
7278cc5a29f0: Pull complete
147f057d2659: Pull complete
3cf22ca2bf74: Pull complete
4d669540c272: Pull complete
664d22e8fc73: Pull complete
2d473ef279a3: Pull complete
03f428c35519: Pull complete
b2360ee5782e: Pull complete
62b8d29ce11e: Pull complete
21b10c639d17: Pull complete
29b1fd940d08: Pull complete
8b680c6a1501: Pull complete
5fbafb492de7: Pull complete
a4fe4aed3409: Pull complete
4d8a7aca71c1: Pull complete
ca40fe428ae6: Pull complete
6ec7740313fa: Pull complete
Digest: sha256:518e1203c7e243c2a71c04a593fbbc8ff805f4215122edb3f9e2d5d78b4b62ff
Status: Downloaded newer image for jc5x/firefly-iii:develop
Creating issue-1382_firefly_iii_db_1 ... done
Creating issue-1382_firefly_iii_app_1 ... done
Mac-mini:issue-1382 james$ docker-compose exec firefly_iii_app php artisan migrate --seed
Migration table created successfully.
Migrating: 2016_06_16_000000_create_support_tables
Migrated:  2016_06_16_000000_create_support_tables
Migrating: 2016_06_16_000001_create_users_table
Migrated:  2016_06_16_000001_create_users_table
Migrating: 2016_06_16_000002_create_main_tables
Migrated:  2016_06_16_000002_create_main_tables
Migrating: 2016_08_25_091522_changes_for_3101
Migrated:  2016_08_25_091522_changes_for_3101
Migrating: 2016_09_12_121359_fix_nullables
Migrated:  2016_09_12_121359_fix_nullables
Migrating: 2016_10_09_150037_expand_transactions_table
Migrated:  2016_10_09_150037_expand_transactions_table
Migrating: 2016_10_22_075804_changes_for_v410
Migrated:  2016_10_22_075804_changes_for_v410
Migrating: 2016_11_24_210552_changes_for_v420
Migrated:  2016_11_24_210552_changes_for_v420
Migrating: 2016_12_22_150431_changes_for_v430
Migrated:  2016_12_22_150431_changes_for_v430
Migrating: 2016_12_28_203205_changes_for_v431
Migrated:  2016_12_28_203205_changes_for_v431
Migrating: 2017_04_13_163623_changes_for_v440
Migrated:  2017_04_13_163623_changes_for_v440
Migrating: 2017_06_02_105232_changes_for_v450
Migrated:  2017_06_02_105232_changes_for_v450
Migrating: 2017_08_20_062014_changes_for_v470
Migrated:  2017_08_20_062014_changes_for_v470
Migrating: 2017_11_04_170844_changes_for_v470a
Migrated:  2017_11_04_170844_changes_for_v470a
Migrating: 2018_01_01_000001_create_oauth_auth_codes_table
Migrated:  2018_01_01_000001_create_oauth_auth_codes_table
Migrating: 2018_01_01_000002_create_oauth_access_tokens_table
Migrated:  2018_01_01_000002_create_oauth_access_tokens_table
Migrating: 2018_01_01_000003_create_oauth_refresh_tokens_table
Migrated:  2018_01_01_000003_create_oauth_refresh_tokens_table
Migrating: 2018_01_01_000004_create_oauth_clients_table
Migrated:  2018_01_01_000004_create_oauth_clients_table
Migrating: 2018_01_01_000005_create_oauth_personal_access_clients_table
Migrated:  2018_01_01_000005_create_oauth_personal_access_clients_table
Migrating: 2018_03_19_141348_changes_for_v472
Migrated:  2018_03_19_141348_changes_for_v472
Migrating: 2018_04_07_210913_changes_for_v473
Migrated:  2018_04_07_210913_changes_for_v473
Seeding: AccountTypeSeeder
Seeding: TransactionCurrencySeeder
Seeding: TransactionTypeSeeder
Seeding: PermissionSeeder
Seeding: LinkTypeSeeder
Seeding: ConfigSeeder
Mac-mini:issue-1382 james$ docker-compose exec firefly_iii_app php artisan firefly:upgrade-database
Updating currency information..
Done updating currency information..
Firefly III database is up to date.
Mac-mini:issue-1382 james$ docker-compose exec firefly_iii_app php artisan firefly:verify
No orphaned transactions!
No orphaned journals!
All link types OK!
All access tokens OK!
Amount integrity OK!
Mac-mini:issue-1382 james$ docker-compose exec firefly_iii_app php artisan passport:install
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 1
Client Secret: 6OoHtJI3OJmymyfBOyBfJtva6zA6kSL6PXGn3Wnr
Password grant client created successfully.
Client ID: 2
Client Secret: RT0zcYhxgAZrJtlfyXG9dpfIrISuKSeiLrGQ5Ou9
Mac-mini:issue-1382 james$
```

**Comment by dfrost999** [comment]
I tested the new docker image (jc5x/firefly-iii:develop + mariadb:latest) and this works for me now. (I had the same issue with "Be right back" after fresh install with jc5x/firefly-iii + mariadb:latest and db-connection issues with mysql:latest)
Thanks!!

**Comment by JC5** [comment]
Glad to hear it!

These fixes will be live with the new release, meaning you could potentially remove the :develop flag. Notice how you're running 4.7.3, which isn't out yet. 

I'm closing this one as solved. Please don't hesitate to contact me in case of questions or issues!

**Comment by JC5** [comment]
I will need a little bit more info :)
