### ISSUE TITLE
Upgrade to develop causes contracts to use "Omschrijving is" instead "omschrijving bevat"

### ISSUE THREAD

**Issue by paul999** [firefly-iii/firefly-iii#1383]
I am running Firefly III version develop branch, upgraded from 4.7.2.2. 

#### Description of my issue:
I upgraded my instance of firefly yesterday and after that the existing contracts where converted to rules. These rules are now all written as "Omschrijving is", while I expected them to be "Omschrijving bevat" too match the actual transactions.

#### Steps to reproduce 
Install 4.7.2.2
Create a few contracts within the UI.
Upgrade to develop
Check the created rules to see the matched properties.

Expected:
To match transactions the rule uses "Omschrijving bevat"

Actual:
The rule uses "Omschrijving is", which causes transactions not to be matched.

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
Thanks for reporting this!

The "omschrijving is" ("description is") is chosen automatically. I could change it to "description contains" for future upgrades, but a similar problem would pop up.

I expect the automatically generated rules not to work for anybody. My own bills also have the name of the opposing party in the "match"-field which brakes "description contains" as well.

I can change the field of course but it won't make a big difference, is my impression right now. What do you think is the best choice?

**Comment by JC5** [comment]
I'll fix it over the weekend.

There is a warning in the upgrade commands, but not every user receives the feedback. It will also be included in the release notes.

A method to recheck transactions is on `/bills/show/x` :)

**Comment by JC5** [comment]
https://github.com/firefly-iii/help/wiki/New-bills-feature

**Comment by JC5** [comment]
A fix is about to be pushed, fixing this for users who will install 4.7.3!

Thanks for the suggestions :+1:
