### ISSUE TITLE
Feature Request: Quicklink to certain pages/reports from dashboard boxes

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1386]
I am running Firefly III version 4.7.2.2

Just a very simple idea: I'd find it helpful if the dashboard boxes would provide a link to quickly reach certain pages.
* The _Balance_ box could link to some kind of report (maybe to the current month's default financial report)
* The _Bills to pay_ box could provide a link to the bill page
* The _Left to spend_ box could provide a link to the budget page
* The _Net worth_ box could provide a link to some kind of report (maybe to the all time default financial report)

**Comment by JC5** [comment]
Sounds like a good idea. I'll see what could work!

**Comment by JC5** [comment]
Fixed, and should be visible on the demo site in a few minutes. :+1:
