### ISSUE TITLE
Bunq API improvements and issues

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1387]
For currently released version 4.7.3 (to be fixed in a future versions).

Ping for @OGKeving

- I'll make sure that the constructors at least can handle null values, that should fix most problems. 

But to answer your question:

- Somebody at bunq decides to take down all API documentation without any prior warning.
- The sandbox api contains one (1) account with one (1) transaction.
- The sandbox is not representative for what I can expect from actual users (userperson / usercompany).
- The now-restored documentation is outright wrong in many places. I've complained about it but nothing changes.

So can you imagine how keen I am to try your SDK?

**Comment by OGKevin** [comment]
1. bunq, we like to surprise our users i guess xD 
2. Not sure, you can create multiple sandbox users and create transactions by request 500EU from suggerdaddy@bunq.com and them spam transactions/requests to bravo@bunq.com have a look [here](https://github.com/bunq/tinker_php/blob/baa8fc51f8b065bb84f0da5b0197141ef1271c26/src/BunqLib.php#L481-L495)
3. Hmm, sandbox is a copy of production with some minor differences like fake money and fake bunqTo links etc, and some minor entries missing. However, sandbox is really good to check if your implementation actually works and if you can parse response and build requests correctly. For actual real data you must use production of course. Sandbox is purely for playing around and testing the basic stuff.
4. With `now-restored` you mean the [renewal](https://together.bunq.com/topic/new-api-doc) of last Thursday ? 

With the new doc system I've created maintaining and correcting it is 10x easier then the old crap :). Could you point me to your complains so i can have a looksie. And adjust where/if needed when it comes to the doc.

**Comment by JC5** [comment]
![screen shot 2018-04-28 at 22 06 43](https://user-images.githubusercontent.com/5889984/39400430-7a642ee2-4b30-11e8-979b-fa360d487aa4.png)

Don't mind me, just opening the API docs...

Could you expand the docs to explain the difference between usercompany, userlight and userperson? Because the sandbox returns perfect data. I'm pretty sure it's impossible for the api to return a userlight.

And the one transaction, would it be too much to ask to add some ideal payments, maybe a request or two, some variation going back and forth?

Current docs don't indicate which values will be present and which ones won't but you were working on it.

**Comment by OGKevin** [comment]
> Don't mind me, just opening the API docs...

Yea, waiting on https://github.com/Rebilly/ReDoc/issues/475 to fix that if not i need to look for another alternative. There is no lazy rendering :( Our API has quite a lot of endpoints. 

>  I'm pretty sure it's impossible for the api to return a userlight.

Correct, API will never return UserLight. UserLight is like the user who is in sign up, which of course, doesn't have access to the public API. 

> difference between usercompany, userlight and userperson? 

Hmm, there is not a lot of difference between company and person. Only that the company has some company values like Chamber of Commerce number, a director etc. Company can also create a cash register and tabs, but dont think that is important to firefly. While person has a BSN number and person names etc. Most of the difference should be spotted in the response tho ? Other then that there is nothing special to it. They both have the same type of monetary account bank's etc. 

> And the one transaction, would it be too much to ask to add some ideal payments, maybe a request or two, some variation going back and forth?

Not sure if we will do that, as the idea of sandbox is for it to be a copy of the production environment, as in when you create an account you start from 0 :thinking:. As we have introduced tinker, would it be cool to just add a script there that populates a new sandbox user with some data ?  [This](https://github.com/bunq/tinker_php/blob/baa8fc51f8b065bb84f0da5b0197141ef1271c26/src/BunqLib.php#L116) is how you create a new user on sandbox btw.

> Current docs don't indicate which values will be present and which ones won't but you were working on it.

Yes this is indeed on my list. Basically to add null-ables to responses. Our API always returns the field tho, but it will be `null`. Created an [issue](https://github.com/bunq/doc/issues/13) for it so you can track progress if interested. The SDK's however are build via a generator and therefore are always nicely updated once if introduced proper CI.

**Comment by OGKevin** [comment]
@JC5 can you give a heads up once you've fixed the null issue :) ?

**Comment by OGKevin** [comment]
Alright

**Comment by OGKevin** [comment]
@JC5 be aware of https://github.com/bunq/sdk_php/issues/76. It is fixed on develop branch but not in release yet. Until `1.0.0` all SDK's will be released at the same time. After that dynamic hotfix will be easier :).

**Comment by JC5** [comment]
Closed in favour of #1443
