### ISSUE TITLE
New Feature: two more account types

### ISSUE THREAD

**Issue by SimonHoenscheid** [firefly-iii/firefly-iii#1390]
I am running Firefly III version Latest

I am missing two account types: 

* mortgage
* credit

With information how long it is running and the payment cycle (monthly, yearly, etc.) and the interest rates. Interest rates would also be helpful on credit cards.

**Comment by OGKevin** [comment]
@SimonHoenscheid version `latest` is not a valid version.  If tomorrow a new version is released then your `latest` is not the latest version anymore which makes this ambiguous. Could you update your issue with the actual version number for better reference.

**Comment by JC5** [comment]
Hi! Thanks for the suggestion, I appreciate it.

You can already set the credit card info you want to using the asset account. You can select a "role", namely the "credit card" role.

For your other idea, please see https://github.com/firefly-iii/firefly-iii/issues/306
