### ISSUE TITLE
Bill Rules: "Active" button broken

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1391]
I am running Firefly III version 4.7.3

#### Description of my issue:

I was trying to concatenate the bill rules to the already existing rules that rename my bill transactions. I wanted to disable your auto-generated rules to see how/if this would work

#### Steps to reproduce 

the active button does not save states on autogenerated rules
- disable "active"
- save
- edit rule again: "active" is still checked

**Comment by JC5** [comment]
Sorry, I can [de-activate the rules](https://demo.firefly-iii.org/rules/edit/2), no problem. Both on the demo site and my local installation.

**Comment by gavu** [comment]
*insert-ashamed-emoticon* - my browser had a cache issue... sorry
