### ISSUE TITLE
Bill Rules: autocomplete for the "link to a bill..." field

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1392]
I am running Firefly III version 4.7.3

#### Description of my issue:

When creating a new bill rule, you need to copy-paste the bill name into the `link to a bill...` field. It would be great if we would be able to select it from a list/autocomplete

(this might already be implemented, I run on a very slow RPi, so it could be a webserver issue)

**Comment by JC5** [comment]
It is auto-completed, but it might show up a little to the left and then to the top. It is a render issue I haven't had time to fix.

If you ever rename a bill, the rule will also be updated.

**Comment by gavu** [comment]
you're right, I totally missed it since there was only one result for me.

slightly off-topic question. should disabled rules appear as related on bills? if yes, maybe add the strikethrough style on the titles as-well?

**Comment by JC5** [comment]
The next release will explicitly say that inactive rules are inactive.
