### ISSUE TITLE
Q: Does bunq import prevent duplicate transactions from previous CSV import?

### ISSUE THREAD

**Issue by jonathanjuursema** [firefly-iii/firefly-iii#1393]
I am running Firefly III version 4.7.3.

#### Description of my question:

Hey! I'm a bunq user and looking forward to using Firefly. I've noticed that integrating with bunq is running into some problems based on earlier issues I saw and #1387, which I am also running into. So I was starting to look into a way to start using Firefly in anticipation of the resolution of the bunq import feature.

Which leads me to my question: if I manually add all transactions via CSV now and link my bunq account via the Firefly functionality later, will it recognize the already existing transactions and skip those in a future bunq import to prevent duplicates? This way I can already start using Firefly in anticipation of the automated sync. :)

I looked through some earlier issues and the docs using the keyword 'duplicate' and could not find an answer to this question. My apologies if this has already been answered!

Thanks in advance for an answer and all the hard work on the project!

**Comment by JC5** [comment]
Probably not. Firefly III can recognise double transfers when importing from CSV (so you don't have to keep track of your files) AND it can detect duplicates from bunq and spectre. It won't detect the combination, I'm afraid.

**Comment by jonathanjuursema** [comment]
Thanks for the quick reply! No problem, I'll just wait patiently for the bunq import!

From what I understand from the other issues you already have the source nailed down, but if there's anything I can do to help troubleshoot a bunq issue as a customer, do let me know. :)

**Comment by OGKevin** [comment]
This shouldn't be to hard to detect i think. You can hash the fields in the CSV. name, counter name, IBANs etc etc. Then create the same hash from the results from the api import and detected duplicates :thinking:.

Or provide a date pointer and import from that date to the future. So I think we can easily solve this issue :)
