### ISSUE TITLE
Few tags are bigger than normal on tag section

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1396]
I am running Firefly III version 4.7.3 on a Raspberry Pi 2 with Arch Linux, Apache 2.4 and MariaDB 10.

#### Description of my issue:
As you can see in the image attached, a few tags in the tag section are bigger than normal.
![ff3__issue_bigtags](https://user-images.githubusercontent.com/2808166/39406443-0a1a92d4-4bb7-11e8-902d-57b2c32c04e0.jpeg)

#### Steps to reproduce 
It seems OK on the demo site, I do not have a clue on how to reproduce the issue.

#### Other important details (log files, system info):
Debug information generated at 2018-04-29 14:09:15 Europe/Rome for Firefly III version **4.7.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.3 |
| FF API version | 0.3 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.2.5 |
| Display errors | Off |
| Session start | 2018-04-01 00:00:00 |
| Session end | 2018-04-30 23:59:59 |
| Session first | 2017-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | false |
| Attempt at "en_US.utf8" | false |
| Attempt at "en_US.UTF-8" | false |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, curl, gd, iconv, intl, mysqli, pdo_mysql, zip, apcu |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@5.0.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.1.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.18, laravel/passport@v5.0.3, laravelcollective/html@v5.6.7, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.3, league/event@2.1.2, league/flysystem@1.0.44, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.12, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.0.8, symfony/css-selector@v4.0.8, symfony/debug@v4.0.8, symfony/event-dispatcher@v4.0.8, symfony/finder@v4.0.8, symfony/http-foundation@v4.0.8, symfony/http-kernel@v4.0.8, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php72@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v4.0.8, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.0.8, symfony/translation@v4.0.8, symfony/var-dumper@v4.0.8, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.1,  |

**Comment by JC5** [comment]
Yes, this is normal. The more money is spent or received under a tag, the bigger they are. It was supposed to be a tag cloud. 

It seems I am so bad at making a tag cloud, that people don't even recognise them 🤔 :wink:

**Comment by gavu** [comment]
I've used this in a few project and it's pretty easy to implement: https://timdream.org/wordcloud2.js/#les-miz

**Comment by lucavallerini** [comment]
My bad, I thought it was just a list of all the tags :smile:

**Comment by JC5** [comment]
Fixed :wink:
