### ISSUE TITLE
Credit Card Payment Method

### ISSUE THREAD

**Issue by SimonHoenscheid** [firefly-iii/firefly-iii#1397]
I am running Firefly III version  4.7.2.2

#### Description of my issue:
Only Full Payment available, it would be nice if the can be deactivated trough a checkbox if no other options are available

I guess this is due to recurring payments are not available at the moment. Is this correct?

**Comment by JC5** [comment]
It is all cosmetic at this point, since Firefly III does not respond to it. Recurring payments and income will have to be built first before this would lead to anything.
