### ISSUE TITLE
Automaticly choose account when importing from bunq

### ISSUE THREAD

**Issue by paul999** [firefly-iii/firefly-iii#1398]
I am running Firefly III version 4.7.3

#### Description of my issue:

Currently, when import from bunq you need to make a selection on what bunq account matches what account in firefly:
![image](https://user-images.githubusercontent.com/65767/39406964-49c17300-4bbf-11e8-8d2c-2c6111317a18.png)
I have multiple bunq accounts, and even more none bunq accounts, making it more difficult to use the import.

I would be nice if the importer, based on, I guess iban, select the potentially correct account. This will make the import process much easier to use.

**Comment by JC5** [comment]
Yes, that would be a nice addition!

**Comment by OGKevin** [comment]
Related to #1387 for reference.
