### ISSUE TITLE
Allow to assign Budget to Transfers

### ISSUE THREAD

**Issue by SimonHoenscheid** [firefly-iii/firefly-iii#1399]
I am running Firefly III version 4.7.2

#### Description of my issue:

Depending on the account system it can make sense that a transfer from one account to an other is part of a set budget. Currently I have to use an expense and an income to realize this.

**Comment by JC5** [comment]
Firefly III works on the assumption that if money doesn't leave the accounts you have control over, it's not spent. Ergo, it cannot be part of a budget since it's not spent yet.

Or is the transfer connected to a budget in another way?

**Comment by SimonHoenscheid** [comment]
I am using a multi account model. one account for fixed costs, one for flexible. I charge the account for the flexible costs every moth with a sum which falls into my fixed budget

**Comment by JC5** [comment]
I see. Firefly III can only count the actual expenses on the flexible account towards the budget.

**Comment by SimonHoenscheid** [comment]
thx @JC5
