### ISSUE TITLE
Asset-Account selection shows "firefly.opt_group_cashWalletAsset"

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#1400]
I am running Firefly III version 4.7.3.

#### Description of my issue:
Dropdown for Asset-Account shows `firefly.opt_group_cashWalletAsset` instead of the correct text.

##### Screenshot from Demo-Page
![img](https://user-images.githubusercontent.com/31184224/39407437-616ad01c-4bc6-11e8-8fe9-8e236a644cdb.png)

#### Steps to reproduce 
1. Create a Asset Account with the Account Role `cash wallet`.
2. Create a new `withdrawal`, `deposit` or `transfer`.
3. Try to select the Asset Account

**Comment by JC5** [comment]
Looks like I forgot a translation! I'll fix it for the next release :+1:. Thanks for letting me know!
