### ISSUE TITLE
cert error when importing from spectre after upgrading

### ISSUE THREAD

**Issue by danikuci1** [firefly-iii/firefly-iii#1402]
hello again - 

I am running Firefly III version 4.7.3

#### Description of my issue:
after upgrading, i deleted the existing key in firefly. after inputting api key info from spectre, i received an SSL error during import. i then deleted the key in both spectre and in firefly and generated a new one but got the same error. i'm assuming the cert it is referring to is whatever firefly uses to try to communicate with spectre? the web cert on the web server is not self-signed and is valid.

#### Steps to reproduce 

this error occurs each time i try to import.

#### Other important details (log files, system info):

from the webpage:

```
A fatal error occurred
A fatal error occurred, which the import-routine cannot recover from. Please see the explanation in red below.

Submitting the job returned an error: error

If the error is a time-out, the import will have stopped half-way. For some server configurations, it is merely the server that stopped while the import keeps running in the background. To verify this, check out the log files. If the problem persists, consider importing over the command line instead.
```

from the email:
```
Hi there,

Firefly III v4.7.3 ran into an error: Request Exception: cURL error 60: SSL certificate problem: self signed certificate in certificate chain
The error was of type "FireflyIII\Exceptions\FireflyException".
The error occured on/at: Mon, 30 Apr 2018 10:32:46 -0700.

This error occured in file C:\wampstack\apache2\htdocs\firefly\app\Services\Spectre\Request\SpectreRequest.php on line 199 with code 0.
```

Please click the version number in the right corner of any Firefly III page to get debug information. 

Debug information generated at 2018-04-30 10:40:58 America/Los_Angeles for Firefly III version **4.7.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.3 |
| FF API version | 0.3 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.14 |
| Display errors | Off |
| Session start | 2018-04-01 00:00:00 |
| Session end | 2018-04-30 23:59:59 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | WINNT |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | 'English_United States.1252' |
| Attempt at "en_US" | false |
| Attempt at "en_US.utf8" | false |
| Attempt at "en_US.UTF-8" | false |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 |
| Loaded extensions | Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, mcrypt, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, openssl, SimpleXML, xml, wddx, xmlreader, xmlwriter, apache2handler, curl, gd, intl, imap, mbstring, exif, mysqli, Phar, pdo_mysql, xmlrpc, sockets, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@5.0.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.1.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.18, laravel/passport@v5.0.3, laravelcollective/html@v5.6.7, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.3, league/event@2.1.2, league/flysystem@1.0.44, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.12, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.0.8, symfony/css-selector@v4.0.8, symfony/debug@v4.0.8, symfony/event-dispatcher@v4.0.8, symfony/finder@v4.0.8, symfony/http-foundation@v4.0.8, symfony/http-kernel@v4.0.8, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php72@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v4.0.8, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.0.8, symfony/translation@v4.0.8, symfony/var-dumper@v4.0.8, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.1,  |

**Comment by JC5** [comment]
Firefly III does not use a self-signed certificate to communicate with Spectre. It relies on the certificate from Spectre. What could be the cause is that the root certificate store in PHP is outdated.

See: https://curl.haxx.se/docs/caextract.html

To install such a bundle, see: https://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/

**Comment by danikuci1** [comment]
ok-

the `curl.cainfo` value was configured in php.ini already. 

regardless, i downloaded an updated extract from the link you posted, pointed  `curl.cainfo` to it - comparing the two files they appear the same. i restarted apache but the error remains the same.

is there another value I should check? or another suggestion?

**Comment by danikuci1** [comment]
thanks for the suggestion, but that did not fix the issue. upon further investigation, it appears that the digicert root ca g2 is part of that file, although the formatting is slightly different. starting from line 2265:

```
DigiCert Global Root G2
=======================
-----BEGIN CERTIFICATE-----
MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQG
EwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAw
HgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBHMjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUx
MjAwMDBaMGExCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3
dy5kaWdpY2VydC5jb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI2/Ou8jqJ
kTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx1x7e/dfgy5SDN67sH0NO
3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQq2EGnI/yuum06ZIya7XzV+hdG82MHauV
BJVJ8zUtluNJbd134/tJS7SsVQepj5WztCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyM
UNGPHgm+F6HmIcr9g+UQvIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQAB
o0IwQDAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV5uNu
5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY1Yl9PMWLSn/pvtsr
F9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4NeF22d+mQrvHRAiGfzZ0JFrabA0U
WTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NGFdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBH
QRFXGU7Aj64GxJUTFy8bJZ918rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/
iyK5S9kJRaTepLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl
MrY=
-----END CERTIFICATE-----
```

**Comment by JC5** [comment]
Ah nice! I searched for it under a different name. At least the content is the same.

For as far as I can find, that should fix it. You could search for the intermediate certificate but that should not matter. I'm afraid I'm running out of ideas.

Did you do a full reboot already?

**Comment by danikuci1** [comment]
I did reboot (rather than just restart apache). unfortunately the error
remains the same SSL cert problem.

I've forwarded you the stack trace in case anything else jumps out at you.
I will post the problem on a couple of php forums and ask for help there.
if you think of anything else, please let me know.

**Comment by danikuci1** [comment]
I think you misunderstand. firefly doesn't connect to `
https://www.saltedge.com/` because that URL doesn't contain any of the API
key information. It connects to something like `https://www.saltedge.com
/api/something?appid=xxxxxxxxxxxxxxx&appsecret=xxxxxxxxxxxxxxxxxxxx`

it looks like you are constructing it in the spectrerequest.php file ->
https://github.com/firefly-iii/firefly-iii/blob/84ac3df5806de7be2852d625cfdd11543a247935/app/Services/Spectre/Request/SpectreRequest.php#L61

can you help me put together this full string? that's what I want to test
with curl

**Comment by JC5** [comment]
Yes, of course. 

Do a post request to the following URL: https://www.saltedge.com/api/v4/customers/

Add the following headers:

* `App-id` with your App ID
* `Secret` with your secret
* `Accept` with content `application/json
* `Content-type` with content `application/json`
* `Cache-Control` with content `no-cache`
* `User-Agent` with content `FireflyIII v4.7.3`
* `Expires-at` with a time stamp 5 minutes into the future (see https://www.epochconverter.com/)
* `Signature` with any random data. I suggest `abc`

See also this page: https://docs.saltedge.com/guides/authentication/

This will give you either certificate exception as PHP is giving you, or a Signature failure exception. I am curious to see which one it is.

**Comment by danikuci1** [comment]
thanks! here is the full curl line and output. looks like its the signature not match error. let me know your thoughts, 

```
C:\wampstack>curl -v -H "Accept: application/json" -H "Signature: abc" -H "Content-type: application/json" -H "Cache-Control: no-cache" -H "User-Agent: FireflyIII v4.7.3" -H "App-id: xxxxxxxxxxxxxxxxxxx" -H "Secret: xxxxxxxxxxxxxxxxxxx" -H "Expires-at: 1525368508" -X POST https://www.saltedge.com/api/v4/customers/


* About to connect() to www.saltedge.com port 443 (#0)
*   Trying 148.251.96.153... connected
* Connected to www.saltedge.com (148.251.96.153) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\wampstack\php\curl-ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using DHE-RSA-AES128-SHA
* Server certificate:
*        subject: CN=*.saltedge.com
*        start date: 2018-02-13 00:00:00 GMT
*        expire date: 2020-04-30 12:00:00 GMT
*        subjectAltName: www.saltedge.com matched
*        issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=RapidSSL TLS RSA CA G1
*        SSL certificate verify ok.
> POST /api/v4/customers/ HTTP/1.1
> Host: www.saltedge.com
> Accept: application/json
> Signature: abc
> Content-type: application/json
> Cache-Control: no-cache
> User-Agent: FireflyIII v4.7.3
> App-id: xxxxxxxxxxxxxxxxxxx
> Secret: xxxxxxxxxxxxxxxxxxx
> Expires-at: 1525368508
>
< HTTP/1.1 400 Bad Request
< Server: nginx
< Date: Thu, 03 May 2018 17:23:49 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Status: 400 Bad Request
< Cache-Control: no-cache
< X-Request-Id: b8ee54f7-61e8-42e6-86e9-2db282fc76c6
< X-Runtime: 0.013157
< Strict-Transport-Security: max-age=631138519
< Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src 'self' www.google.com/recaptcha/; connect-src 'self' www.google-analytics.com mc.yandex.ru; font-src 'self' fonts.googleapis.com fonts.gstatic.com d1uuj3mi6rzwpm.cloudfront.net; form-action 'self'; img-src *; media-src 'none'; object-src d1uuj3mi6rzwpm.cloudfront.net; plugin-types application/x-shockwave-flash; script-src 'self' www.gstatic.com www.googletagmanager.com tagmanager.google.com www.googleadservices.com www.google.com www.google-analytics.com mc.yandex.ru googleads.g.doubleclick.net d1uuj3mi6rzwpm.cloudfront.net; style-src 'self' 'unsafe-inline' fonts.googleapis.com d1uuj3mi6rzwpm.cloudfront.net; report-uri /logger/csp
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-XSS-Protection: 1; mode=block
<
{"error_class":"SignatureNotMatch","error_message":"Signature not match.","request":{}}* Connection #0 to host www.saltedge.com left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
```

**Comment by JC5** [comment]
It means that cURL is able to connect to the server. So whatever is wrong with PHP and curl, it seems it is not using the config files or variables you've enabled for your command line cURL.

Could you verify which config file your PHP cURL uses?

**Comment by danikuci1** [comment]
`php.ini` is using the `curl-ca-bundle.crt` file that is called out by curl above. this is the default for WAMP. the file is valid, of the correct path, and accessible by PHP/apache

**Comment by JC5** [comment]
I'm sorry, then I don't know what it could be. 

- There are no multiple php.ini files? Multiple versions of PHP, packaged with WAMP?
- You're also sure that PHP is actually configured to use _that_ php.ini? For example, by checking phpinfo()?

**Comment by danikuci1** [comment]
this is definitely the php.ini file in use. when i first installed firefly iii I was unable to because PHP BCMath Arbitrary Precision Mathematics extension wasnt enabled and I had to add it in this file. there is no other php on this server, WAMP is the only web stack intalled and just two other applications (both php) are on it.

running `php -i` from command line shows 

``
phpinfo()
PHP Version => 7.1.14
Loaded Configuration File => C:\wampstack\php\php.ini
```

I've posted this problem a couple other places as well, let's wait and see if anyone knows what might be going on. thanks for your help up to this point.

**Comment by pkoziol** [comment]
Could you execute curl from PHP?

```
php -r "$curl = curl_init(); curl_setopt($curl, CURLOPT_URL, 'https://www.saltedge.com/api/v4/customers/'); curl_setopt($curl, CURLOPT_POST, 1); curl_setopt($curl, CURLOPT_HTTPHEADER, [ 'Accept: application/json', 'Signature: abc', 'Content-type: application/json', 'Cache-Control: no-cache', 'User-Agent: FireflyIII v4.7.3', 'App-id: xxxxxxxxxxxxxxxxxxx', 'Secret: xxxxxxxxxxxxxxxxxxx', 'Expires-at: 1525368508']); curl_setopt($curl, CURLOPT_VERBOSE, true); curl_exec($curl); printf(\"\ncURL errno: %d\n\", curl_errno($curl));"
```

Linux variation of this command executed in Firefly's container prints paths to CAfile and CApath. On Windows it doesn't print that, but I only have PHP 5.6.16 available. Maybe it'll work for you.

**Comment by danikuci1** [comment]
thank you for the suggestion:

```

C:\wampstack>php -r "$curl = curl_init(); curl_setopt($curl, CURLOPT_URL, 'https://www.saltedge.com/api/v4/customers/'); curl_setopt($curl, CURLOPT_POST, 1); curl_setopt($curl, CURLOPT_HTTPHEADER, [ 'Accept: application/json', 'Signature: abc', 'Content-type: application/json', 'Cache-Control: no-cache', 'User-Agent: FireflyIII v4.7.3', 'App-id: xxxxxxxxxxxxxxxxxxx', 'Secret: xxxxxxxxxxxxxxxxxxx', 'Expires-at: 1525387759']); curl_setopt($curl, CURLOPT_VERBOSE, true); curl_exec($curl); printf(\"\ncURL errno: %d\n\", curl_errno($curl));"
*   Trying 148.251.96.153...
* TCP_NODELAY set
* Connected to www.saltedge.com (148.251.96.153) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\wampstack\php\cacert.pem
  CApath: none
* NPN, negotiated HTTP1.1
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.saltedge.com
*  start date: Feb 13 00:00:00 2018 GMT
*  expire date: Apr 30 12:00:00 2020 GMT
*  subjectAltName: host "www.saltedge.com" matched cert's "*.saltedge.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=RapidSSL TLS RSA CA G1
*  SSL certificate verify ok.
> POST /api/v4/customers/ HTTP/1.1
Host: www.saltedge.com
Accept: application/json
Signature: abc
Content-type: application/json
Cache-Control: no-cache
User-Agent: FireflyIII v4.7.3
App-id: xxxxxxxxxxxxxxxxxxx
Secret: xxxxxxxxxxxxxxxxxxx
Expires-at: 1525387759
Expect: 100-continue

< HTTP/1.1 100 Continue
< HTTP/1.1 400 Bad Request
< Server: nginx
< Date: Thu, 03 May 2018 22:42:08 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Status: 400 Bad Request
< Cache-Control: no-cache
< X-Request-Id: 8eecb89e-32a6-4866-b82d-152537b8a82f
< X-Runtime: 0.005792
< Strict-Transport-Security: max-age=631138519
< Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src 'self' www.google.com/recaptcha/; connect-src 'self' www.google-analytics.com mc.yandex.ru; font-src 'self' fonts.googleapis.com fonts.gstatic.com d1uuj3mi6rzwpm.cloudfront.net; form-action 'self'; img-src *; media-src 'none'; object-src d1uuj3mi6rzwpm.cloudfront.net; plugin-types application/x-shockwave-flash; script-src 'self' www.gstatic.com www.googletagmanager.com tagmanager.google.com www.googleadservices.com www.google.com www.google-analytics.com mc.yandex.ru googleads.g.doubleclick.net d1uuj3mi6rzwpm.cloudfront.net; style-src 'self' 'unsafe-inline' fonts.googleapis.com d1uuj3mi6rzwpm.cloudfront.net; report-uri /logger/csp
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-XSS-Protection: 1; mode=block
* HTTP error before end of send, stop sending
<
{"error_class":"SignatureNotMatch","error_message":"Signature not match.","request":{}}* Closing connection 0

cURL errno: 0

C:\wampstack>
```

**Comment by pkoziol** [comment]
So, PHP can connect to the server. The only (?) thing that differs is used CAfile. Do you know why it uses `C:\wampstack\php\cacert.pem` instead of `curl-ca-bundle.crt`?

Could you backup `curl-ca-bundle.crt`, replace it's content with one from `C:\wampstack\php\cacert.pem`, restart WAMP and see if would fix Firefly?

**Comment by danikuci1** [comment]
so this is rather interesting: in `php.ini` we define `curl.cainfo` and `openssl.cafile`

by default out of the box install of WAMP, they are configured for `C:\pathto\php\curl-ca-bundle.crt` and that file is included in the stack. 

when @JC5 made his original suggestion, I downloaded `cacert.pem` from curl website and changed the variables in `php.ini`. `openssl.cafile` seems to take the new value ok but `curl.cainfo` remains the same. looking at the content of the two files, they contain all the same signatures. nevertheless I will try your suggestion of replacing the file contents.

**Comment by danikuci1** [comment]
unfortunately, the results were the same. i also noticed in the help file that it said that if no file were specified, it would rely on the OS's CA store. Since i can browse to the page fine from the machine without a cert error, i figured I'd try it, but it too did not work.

is there a way to tell curl to tell us exactly which cert it is that is failing? or which signature is not matching? perhaps then we can manually add the failing cert? kinda like manually installing a self-signed cert or something?

**Comment by pkoziol** [comment]
> unfortunately, the results were the same.

😞

> i also noticed in the help file that it said that if no file were specified, it would rely on the OS's CA store. Since i can browse to the page fine from the machine without a cert error, i figured I'd try it, but it too did not work.

They probably meant some Linux CA store which probably is another file (as most configs on Linux). On Windows it would require to use some Microsoft API which I doubt PHP uses.

> is there a way to tell curl to tell us exactly which cert it is that is failing? or which signature is not matching? perhaps then we can manually add the failing cert? kinda like manually installing a self-signed cert or something?

That's what JC5 wanted you to do [3 days ago](https://github.com/firefly-iii/firefly-iii/issues/1402#issuecomment-385697981)

I was goint to write about modifying Firefly source, adding `curl_setopt($curl, CURLOPT_VERBOSE, true);`, etc, but... I noticed that [Firefly uses some Requests](https://github.com/firefly-iii/firefly-iii/blob/4.7.3/app/Services/Spectre/Request/SpectreRequest.php#L240) library, not curl directly. I found documentation and on [Advanced Usage](http://requests.ryanmccue.info/docs/usage-advanced.html) page they say that:

> Requests bundles certificates from the Mozilla certificate authority list, which is the same list of root certificates used in most browsers. If you’re accessing sites with certificates from other CAs, or self-signed certificates, you can point Requests to a custom CA list in PEM form (the same format accepted by cURL and OpenSSL):
>
>```
>$options = array(
>	'verify' => '/path/to/cacert.pem'
>);
>$response = Requests::get('https://httpbin.org/', array(), $options);
>```

And they do!

```
root@2fcf19f61abf:/var/www/firefly-iii# head vendor/rmccue/requests/library/Requests/Transport/cacert.pem
##
## ca-bundle.crt -- Bundle of CA Root Certificates
##
## Certificate data from Mozilla as of: Sat Dec 29 20:03:40 2012
##
## This is a bundle of X.509 certificates of public Certificate Authorities
## (CA). These were automatically extracted from Mozilla's root certificates
## file (certdata.txt).  This file can be found in the mozilla source tree:
## http://mxr.mozilla.org/mozilla/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1
##
```

And it doesn;t contain DigiCert Global Root G2 (at least in docker image jc5x/firefly-iii:release-4.7.3).

```
root@2fcf19f61abf:/var/www/firefly-iii# grep -i digicert -A4 vendor/rmccue/requests/library/Requests/Transport/cacert.pem
DigiCert Assured ID Root CA
===========================
-----BEGIN CERTIFICATE-----
MIIDtzCCAp+gAwIBAgIQDOfg5RfYRv6P5WD8G/AwOTANBgkqhkiG9w0BAQUFADBlMQswCQYDVQQG
EwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSQw
--
DigiCert Global Root CA
=======================
-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBhMQswCQYDVQQG
EwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAw
--
DigiCert High Assurance EV Root CA
==================================
-----BEGIN CERTIFICATE-----
MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBsMQswCQYDVQQG
EwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSsw
```

@danikuci1 could you add certificate to that file and see what happens?

**Comment by danikuci1** [comment]
[What JC5 asked me to do was done](https://github.com/firefly-iii/firefly-iii/issues/1402#issuecomment-385697981) although I didn't fully understand that he was getting that info from the curl output. The default file `curl-ca-bundle.crt` contained the signature that he posted already. And actually it contains all the ones you posted as well. again, (here is that file's contents)[https://pastebin.com/xygxEKYY]

could you double-check and let me know if i'm just missing something?

**Comment by pkoziol** [comment]
Sorry. I might be little to fast.

I believe you done it, but if I read it correctly you added it to `C:\wampstack\php\cacert.pem`.

There is third file containing certificates - `<firefly dir>/vendor/rmccue/requests/library/Requests/Transport/cacert.pem` and if I understood code right [Requests library tells curl to use that file](https://github.com/rmccue/Requests/blob/master/library/Requests/Transport/cURL.php#L154) (Firefly uses Requests library which uses curl).

I wanted you to open `<firefly dir>/vendor/rmccue/requests/library/Requests/Transport/cacert.pem` and search for:
```
MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh
```

If it's not there add following certificate at the bottom of the file, restart WAMP and re-run import.

```
DigiCert Global Root CA G2
==========================
-----BEGIN CERTIFICATE-----
MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
MjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI
2/Ou8jqJkTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx
1x7e/dfgy5SDN67sH0NO3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQ
q2EGnI/yuum06ZIya7XzV+hdG82MHauVBJVJ8zUtluNJbd134/tJS7SsVQepj5Wz
tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ
vIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQABo0IwQDAP
BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV
5uNu5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY
1Yl9PMWLSn/pvtsrF9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4
NeF22d+mQrvHRAiGfzZ0JFrabA0UWTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NG
Fdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBHQRFXGU7Aj64GxJUTFy8bJZ91
8rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/iyK5S9kJRaTe
pLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl
MrY=
-----END CERTIFICATE-----
```

**Comment by danikuci1** [comment]
WELL LA DE FRIKKIN DA. ladies and gentlemen, we have a new error:

```
A fatal error occurred, which the import-routine cannot recover from. Please see the explanation in red below.

Spectre connection failed. Did you use invalid credentials, press Cancel or failed the 2FA challenge?

If the error is a time-out, the import will have stopped half-way. For some server configurations, it is merely the server that stopped while the import keeps running in the background. To verify this, check out the log files. If the problem persists, consider importing over the command line instead.
```

do i have 2FA turned on for my spectre account so maybe thats the problem now?

**Comment by danikuci1** [comment]
also, i'm curious @JC5 when you told me to update the cacert.pem file were you referring to the one packaged with firefly or the one you had me download from curl website?

**Comment by pkoziol** [comment]
🎉 Hooray! 🎉

Looks like Firefly needs to ship with own `cacert.pem` until rmccue/Requests#212 is merged and released.

**Comment by JC5** [comment]
Thanks guys for the help in debugging this. I wasn't aware that this library ships with an old list. I suspect my own test-machine doesn't have / use cURL, or I would have noticed.

Since I flat out refuse to ship a list of root certificates with my app, I will see if they merge the change soon or I'll move to another library.

**Comment by pkoziol** [comment]
There is another transport - `Requests_Transport_fsockopen`. You could force it for everyone by passing
```
$options = array(
  'transport' => 'Requests_Transport_fsockopen'
);
```
as the 4th parameter to `Requests::post`.

Strange thing is that [it also uses `$options['verify']`](https://github.com/rmccue/Requests/blob/master/library/Requests/Transport/fsockopen.php#L97) (meaning: their custom `cacert.pem` file), so it should (not) work same as curl...

**Comment by JC5** [comment]
I'm in the process of rewriting the import routine(s). The current routine is heavily biased towards a file-based import. I will probably move towards guzzle.
