### ISSUE TITLE
Adding new asset type

### ISSUE THREAD

**Issue by ajinkyagadewar** [firefly-iii/firefly-iii#1404]
I am running Firefly III version 4.7.3

#### Impact on net worth: This will add impact on net worth.

**Comment by JC5** [comment]
OK, so I've thought about doing stock management in Firefly III, and I've decided not to add it. 

I believe it will be better for Firefly III to focus on personal finance, with mortgages and debts in the future. These functions alone give FF3 a clear direction and boundary.

Although I am not opposed to stock management itself, I would suggest leaning on Firefly III through the API. You can create transactions from and to the Firefly III accounts and use the authentication of Firefly III to authenticate users of the stock management app.

It's been asked before, and I shall give the message to other people as well. There is a lot of potential in Firefly III. There are about a thousand things I could add. It's just that I believe that _not_ adding all of those things will be better for Firefly III in the long run.

Unfortunately, this includes stock management.

Insofar as that Firefly III has an architecture, it leans heavily on the Laravel framework and the libraries that surround it. Database management, user management and most code uses concepts from Laravel. Laravel in turns uses Symfony and many standard design patterns. Please feel free to borrow code or ideas, or consult me if you have to.

I am sorry to disappoint you. I hope I don't turn you away from Firefly III. I welcome all ideas and additions, even though I have to turn them down sometimes.

Cheers,
James

**Comment by ajinkyagadewar** [comment]
Thanks for the reply. I understand your plans and roadmap for Firefly III. 

From an architecture perspective, I understand that it is using Laravel as a framework and all other components of it; I wanted to know if you created any flow diagram for the product if some developer wants to do some changes to the core product.
