### ISSUE TITLE
Show proposed amount/month in /piggy-banks table

### ISSUE THREAD

**Issue by nhaarman** [firefly-iii/firefly-iii#1405]
I have a couple of piggy banks with dates, and when assigning money to them you'd have to 'enter' each piggy bank to see the proposed amount per month. It would be handy if this amount is directly shown in the table, next to goal and amount left.

**Comment by JC5** [comment]
That's a good idea, I'll see if it fits!

**Comment by JC5** [comment]
Fixed! Also visible on the demo site. :+1:

**Comment by nhaarman** [comment]
Awesome! Great work 😁
