### ISSUE TITLE
Minor bug regarding the auto generated bill matching rules

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1406]
I am running Firefly III version 4.7.3

#### Description of my issue:
After upgrading to 4.7.3, transactions are no longer matched to a bill. Nearly all my rules used to have the same lower and upper bound. This condition is not correctly translated into a rule. It becomes:
![image](https://user-images.githubusercontent.com/317179/39485857-6a2a5258-4d7a-11e8-80a4-0f9552c95856.png)
Thus the rule never matches. Its not a big issue though because I can manually edit the rules.

**Comment by JC5** [comment]
Mmm, I noticed that. The rule is more strict than the bill was (not inclusive).

I could remove one cent but it seems a bit much. It's a one time process users are going through. Once users have updated, it'll never happen again.

I'm inclined to leave it as is, what do you think?

**Comment by skuzzle** [comment]
Hmm,

I believe it is pretty common for bills to have identical upper and lower bounds. Leaving the migration broken could confuse users. Isn't it possible to generate the correct condition using 'Amount equals' in the first place?

**Comment by JC5** [comment]
I don't know. All of my bills have gone up in the past :sweat_smile: 

I like your idea! And I have another, I'll tag you.

**Comment by JC5** [comment]
Will be fixed. When bills have the same upper and lower amount, the auto-generated rule will use "amount is exactly".
