### ISSUE TITLE
bunq api not working with deployement on Heroku

### ISSUE THREAD

**Issue by gldrenthe89** [firefly-iii/firefly-iii#1417]
I am running Firefly III version 4.7.3 (heroku)

#### Description of my issue:
bunq api not working with deployement on Heroku

#### Steps to reproduce 
Import-> start
(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):
![screenshot_3](https://user-images.githubusercontent.com/6988259/39574735-807a5a58-4ed8-11e8-91da-3b7cb0aebf75.png)

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by OGKevin** [comment]
References #1387 

Can you take a look in the logs of firefly so we know whats is going wrong here. I have a feling it has to do with the constructors not being able to handle null values.

**Comment by gldrenthe89** [comment]
Thats a quick reply, Thumbs up.

Can you tell how to do that wihtin Heroku. I'm new to heroku ;-)

**Comment by OGKevin** [comment]
You must connect to your dyno: https://devcenter.heroku.com/changelog-items/1264 

and then afterwards there should be logs in `storage/logs/laravel.log` from the project root. However might be that there are no logs due to https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

**Comment by gldrenthe89** [comment]
I removed the Heroku dyno because of this. I'm working on sandstorm now. Same problem but different version is on sandstorm 4.7.2.2? how to get latest?

**Comment by OGKevin** [comment]
Hm im not sure about that. I think @JC5 is the only one who can udpate it 🤔. Me myself dont have a lot of experience with sandstrom. I would suggest to craete a new issue for this as this has nothing to do with this issue.

**Comment by gldrenthe89** [comment]
No problem. I'm also installing a VM with ubuntu for AMPPS. Thanks for the quick replys

**Comment by JC5** [comment]
Yes, like @OGKevin is saying, because the bunq api + docs don't mention or return nulls until you go into production, Firefly III can't actually import from bunq.

I hope to fix this in the next release. I suspect this is the error you're running into. I apologize for the inconvenience. I believe Firefly III can import their CSV files just fine, and an example configuration file can be found [in the configuration repository](https://github.com/firefly-iii/import-configurations/blob/master/nl/bunq/bunq.json).

**Comment by gldrenthe89** [comment]
@JC5 I will let you now if on a LAMP server running ono Ubuntu 16.04 this problem is still there. Thanks

**Comment by OGKevin** [comment]
@gldrenthe89 if its indeed due to the null issue then it wont matter on which platform you are running it on 😉.

**Comment by JC5** [comment]
I'm closing this one in anticipation of #1443
