### ISSUE TITLE
Bills: Notes not showing on 'show' page

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1418]
I am running Firefly III version 4.7.3

#### Description of my issue:

I updated my bills (added customer information and other details) but the notes field appears only on the edit page, not on the `https://my.domain.tld/bills/show/5` page

#### Steps to reproduce 

1. edit bill
2. add text to notes
3. go back to bill
4. notes not showing (even if enabled from the preferences page)

#### Other important details (log files, system info):

could reproduce it on the demo page

**Comment by JC5** [comment]
Must have forgotten that one, thanks for informing me!

**Comment by JC5** [comment]
This will be fixed in the next release!
