### ISSUE TITLE
Bills: 'Active' checkbox is unchecked when editing an active bill

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1419]
I am running Firefly III version 4.7.3

#### Description of my issue:

I edited some bills, noticed that, upon saving, they were deactivated. I checked the demo site and saw that, the `active` checkbox does not retreive the status from the database and is unchecked (by default?), thus, deactivating the bill

#### Steps to reproduce 

1. edit a bill
2. do not do anything, just save it again
3. check bill - it is deactivated

#### Other important details (log files, system info):

could reproduce it on the demo site

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1403
