### ISSUE TITLE
Can't get to homepage, apache error unexpected '?'

### ISSUE THREAD

**Issue by andreapx** [firefly-iii/firefly-iii#1423]
I am running Firefly III version 4.7.3 on Ubuntu 16.04 

#### Description of my issue:
As soon as I go to the homepage I get this apache error:
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/firefly-iii/vendor/symfony/http-kernel/Exception/HttpException.php on line 24
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0

#### Steps to reproduce 
Go to http://firefly-iii.example.com/

(please include if this problem also exists on the demo site)
No

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information. 
...I can't :(

**Comment by JC5** [comment]
It seems you’re not running PHP 7.1 or higher, which is required.

**Comment by JC5** [comment]
:+1:
