### ISSUE TITLE
Wrong current balance at default asset account

### ISSUE THREAD

**Issue by marviins87** [firefly-iii/firefly-iii#1426]
I am running Firefly III version 4.7.3

#### Description of my issue:
It looks like the account balance of my default asset account isn't showed correct anymore. 
I'm not sure if this is due to the upgrade to 4.7.3

Strange thing is; when i use the reconcile option and put in the balance from my bank statement (04/30/2018) and also put in the current balance from my banks website (5/7/2018), Firefly says that there is no difference in balance.

"Your Firefly III ledger and your bank statements match. There is nothing to do. Please press "Confirm reconciliation" to confirm your input. "

When i look at the the current balance of my default asset account there is a ~€1000 difference.

Summary;
Reconcile option says there is no difference in balance, but i do see a difference.

**Comment by JC5** [comment]
OK, this is very strange. Thanks for reporting! Let's see if we can debug this.

- In short: this URL gives the correct balance: `/accounts/reconcile/x/index`.
- This URL says your balance is incorrect: `/accounts/asset`

Right?

- There are several places where you can see your balance: the chart on the frontpage, on the index to the right (list of transactions), on `/accounts/show/n` and various other places. Please indicate if they're all wrong or just one of them.
- Browse to `/flush`. Does this help?
- Is there a moment in the past where it _is_ correct?

So far, I haven't run into balance issues where the math was wrong. But unexpected expenses, weird reconciliations or strange settings can mess things up. If you can answer these questions we can see where the difference comes from.

**Comment by marviins87** [comment]
I think i've found the cause of the issue or at least related to the imbalance.

It looks like my new imported transfers are messed up since the upgrade to 4.7.3 (i came from 4.7.1.x) resulting in incorrect balances.

![visai](https://user-images.githubusercontent.com/31892758/39771289-dedc1768-52f1-11e8-8b0e-a0741e4f4408.png)

51* is a savings account
72* is default asset account

First line is a bank transaction from 51* (source) to 72* (destination)
Second line is a payment to VISA company with the same account

Did you changed something related in the import function? 

I've been using this import for a while now and never had issues with it. 

Below you'll find my import config file (until now worked for KNAB bank):
```
{
    "stage": "ready",
    "has-headers": true,
    "date-format": "d-m-Y",
    "delimiter": ";",
    "import-account": 1964,
    "specifics": [],
    "column-count": 16,
    "column-roles": [
        "account-id",
        "date-transaction",
        "currency-id",
        "rabo-debit-credit",
        "amount",
        "opposing-id",
        "opposing-name",
        "_ignore",
        "_ignore",
        "description",
        "_ignore",
        "sepa-ct-id",
        "sepa-ct-op",
        "_ignore",
        "_ignore",
        "_ignore"
    ],
    "column-do-mapping": [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "column-mapping-config": {
        "0": {
            "72*": 1964
        },
        "5": {
            "51*": 1965,
            "52*": 1967,
            "53*": 1969
        }
    },
    "file-type": "csv",
    "has-config-file": true,
    "apply-rules": true,
    "match-bills": true,
    "auto-start": false,
    "initial-config-complete": false,
    "column-roles-complete": false,
    "column-mapping-complete": false,
    "has-file-upload": false
}
```

I'm looking forward to your reply.

**Comment by JC5** [comment]
I’m not at home right now so I have to do some digging later. Could it be related to this?

https://github.com/firefly-iii/firefly-iii/issues/1349

**Comment by marviins87** [comment]
it doesn't look like the same issue because he has positive and negative amounts. KNAB only uses positive amounts (combined with a "C" or "D" for defining the flow), just like Rabobank, that's why i'm using that option.

I'll wait for your reply :-) thanks in advance !

**Comment by JC5** [comment]
I come to the same conclusion. I shall write some tests.

Could you share with me 2 or 3 offending lines via email, or via attachment? Feel free to censor amounts and IBAN's, as long as you do it consistently (so don't censor your IBAN to A in one line and B in the other).

I shall add it as a test case and fix it.

**Comment by marviins87** [comment]
Here you go;

```
Rekeningnummer;Transactiedatum;Valutacode;CreditDebet;Bedrag;Tegenrekeningnummer;Tegenrekeninghouder;Valutadatum;Betaalwijze;Omschrijving;Type betaling;Machtigingsnummer;Incassant ID;Adres;Referentie;
"72";"08-05-2018";"EUR";"D";"16,76";"";"Action";"08-05-2018";"Betaalautomaat";"";"";"";"";"";"";
"72";"08-05-2018";"EUR";"D";"0,6";"";"ALBERT HEIJN";"08-05-2018";"Betaalautomaat";"";"";"";"";"";"";
"72";"07-05-2018";"EUR";"D";"25,42";"";"Kruidvat";"07-05-2018";"Betaalautomaat";"";"";"";"";"";"";
"72";"07-05-2018";"EUR";"D";"3,71";"";"ALBERT HEIJN";"07-05-2018";"Betaalautomaat";"";"";"";"";"";"";
"72";"06-05-2018";"EUR";"D";"36,46";"";"ETOS";"07-05-2018";"Betaalautomaat";"";"";"";"";"";"";
"72";"05-05-2018";"EUR";"D";"45,78";"";"Albert Heijn BV";"07-05-2018";"Betaalautomaat";"";"";"";"";"";"";
"72";"05-05-2018";"EUR";"D";"61,95";"";"Jumbo";"07-05-2018";"Betaalautomaat";"";"";"";"";"";"";
_"72";"04-05-2018";"EUR";"C";"215";"NL55";"Person A";"04-05-2018";"Ontvangen betaling";"";"";"";"";"";"";_
"72";"04-05-2018";"EUR";"D";"1333,64";"6773";"VISA";"04-05-2018";"iDEAL";"Betaling";"";"";"";"";"";
**"72";"04-05-2018";"EUR";"C";"1333,64";"5110";"MS";"04-05-2018";"Ontvangen betaling";"";"";"";"";"";"";**
**"72";"26-04-2018";"EUR";"D";"50";"5227";"MS";"26-04-2018";"Periodieke overboeking";"";"";"";"";"";"";**
**"72";"18-04-2018";"EUR";"D";"150";"5220";"MS";"18-04-2018";"Periodieke overboeking";"";"";"";"";"";"";**
**"72";"16-04-2018";"EUR";"C";"1000";"5110";"MS";"16-04-2018";"Ontvangen betaling";"";"";"";"";"";"";**
**"72";"04-04-2018";"EUR";"D";"200";"5227";"MS";"04-04-2018";"Overboeking";"";"";"";"";"";"";**
**"72";"03-04-2018";"EUR";"C";"300";"5110";"MS";"03-04-2018";"Ontvangen betaling";"";"";"";"";"";"";**
"72";"30-03-2018";"EUR";"D";"19,09";" ";"ALBERT HEIJN";"03-04-2018";"Betaalautomaat";"";"";"";"";"";"";
"72";"30-03-2018";"EUR";"D";"8,55";" ";"KFC";"03-04-2018";"Betaalautomaat";"";"";"";"";"";"";
```

5110 is a savings account
5220 is another savings account
5227 is another savings account
72 is the default asset account

All **bold** lines are transfers & all incorrect when imported in 4.7.3. Before they weren't.
I've added one _Italic_ line for completeness. That's also a 'C' but correctly imported. Only difference is that the amount came from a revenue account instead of transfer between my own accounts. 

I hope you're able to find the cause of it with the details above.

Looking forward to your reply and again thanks in advance!

**Comment by JC5** [comment]
Alright, it took me a few days but this is the result in Firefly III 4.7.4 (the next release):

* 72: Mapped to Checking Account
* 5110: Mapped to Savings A
* 5220: Mapped to Savings B
* 5227: Mapped to Savings C

![screen shot 2018-05-12 at 20 54 55](https://user-images.githubusercontent.com/5889984/39960664-dd3f737c-5626-11e8-88e2-a11347ca2df7.png)


I think it's pretty accurate, right?

**Comment by marviins87** [comment]
That looks perfect!

**Comment by JC5** [comment]
Great! I'll consider this problem fixed. The next release should go live at the end of the month.
