### ISSUE TITLE
White screen + exception thrown. New install .

### ISSUE THREAD

**Issue by TinkerFu** [firefly-iii/firefly-iii#1429]
I am running Firefly III version 4.7.3
Debian stretch

# Fresh installation. White screen. Error thrown. 
[Fri May 11 10:35:18.030060 2018] [:error] [pid 7607] [client 173.163.129.22:13272] PHP Parse error:  syntax error, unexpected '?' in /var/www/tinkerfu.com/firefly-iii/vendor/symfony/http-foundation/Response.php on line 499
[Fri May 11 10:35:18.030128 2018] [:error] [pid 7607] [client 173.163.129.22:13272] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0

#### Steps to reproduce 
Install as per installation instructions. 

#### Other important details (log files, system info):
I did turn on debug, but no info is displayed.

I did attempt to remove the offending "?" but it still throws the exception.

**Comment by JC5** [comment]
http://firefly-iii.readthedocs.io/en/latest/support/faq.html#i-get-unexpected-question-mark

Make sure you're running PHP 7.1

**Comment by OGKevin** [comment]
What php version are you using  ?

**Comment by TinkerFu** [comment]
That's most likely it.  I misread the install and saw the php 7.2. Let me downgrade and see if it goes away.

**Comment by TinkerFu** [comment]
Yep. that was it. Thanks.
