### ISSUE TITLE
404 for /login

### ISSUE THREAD

**Issue by TinkerFu** [firefly-iii/firefly-iii#1430]
I am running Firefly III version 4.7.3
Debian stretch
PHP 7.2

/storage is writeable. 
rewrite is enabled
Database is created, credentials tested. 

#### Description of my issue:
404 for /login
#### Steps to reproduce 
Clean install. 
Go to main url. 404
#### Other important details (log files, system info):
Only errors I'm seeing are in the apache log.
[11/May/2018:18:25:52 +0200] "GET /login HTTP/1.1" 404 687 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"

Here's the pertinent apache config. 
<VirtualHost *:80>
        ServerName xxx.com
    ServerAlias moolah.xxx.com

        ServerAdmin webmaster@tinkerfu.com
        DocumentRoot /var/www/xxx.com/firefly-iii/public

    <Directory "/var/www/xxx.com/firefly-iii/public">
        AllowOverride ALL
        Order Allow, Deny
        Allow from ALL
    </Directory>

        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
RewriteEngine on
RewriteCond %{SERVER_NAME} =moolah.xxx.com [OR]
RewriteCond %{SERVER_NAME} =xxx.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

I did see this https://github.com/firefly-iii/firefly-iii/issues/317 but I've checked everything from there.

**Comment by JC5** [comment]
I'm assuming from your configuration that the rewrite module is enabled (for the vhost)?

```
sudo a2enmod rewrite
```

It could be that your own rewrite rules throw Firefly III's out of whack (see `public/.htaccess`) but I believe the latter would overwrite the former.

Could you disable your own redirecting rules and see what happens after you reload Apache?

**Comment by TinkerFu** [comment]
That was it, thanks!

**Comment by JC5** [comment]
Another case closed! Good work, Watson! 😁 

I'm online for about another hour, so if you run into problems, just open an issue :+1:

**Comment by abctaylor** [comment]
Just adding to this - does anyone have a fix for nginx?
