### ISSUE TITLE
Issue with transaction validation button

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#1434]
I am running Firefly III version 4.7.3

#### Description of my issue:
When I use the menu to create a new transaction, the new pages load with the form validation button as the type of transaction (eg. Store new withdrawal).
If I then change the transaction type, the button on the left part changes name but not the one on the right part of the form that stays the old name.

![firefly-button](https://user-images.githubusercontent.com/31923233/40057919-e6db2748-584f-11e8-9c34-003e3ad187c7.png)

It's an easy to find bug, now I'm thinking why would you need 2 buttons that do the same on this page?

**Comment by JC5** [comment]
Oh that can be an easy fix, thanks for letting me know! I added the left button because there were people who unable to spot the right button on the page. 

See https://github.com/firefly-iii/firefly-iii/issues/1323

**Comment by MacPaille** [comment]
Is it normal this bug is still not fixed in 4.7.4 release?

**Comment by JC5** [comment]
No, I usually tend to fix the bugs I promise to fix :wink:. This one however, it seems the fix didn't work. I've pushed another attempt. It's live on the demo site as well and seems to work for me.

**Comment by MacPaille** [comment]
Cool let's wait next release then :) Thanks!
