### ISSUE TITLE
Exclude specific category from the graphs on the dashboard

### ISSUE THREAD

**Issue by likeitneverwentaway** [firefly-iii/firefly-iii#1435]
I am running Firefly III version 4.7.3

#### Description of my issue:

I'd like to exclude certain categories from being shown on the different graphs on the dashboard. For example if the "monthly rent" is taking 70% of the deposits then the graphs are useless, because of the scale and how the less expansive categories are small compared to it. The everyday life is not represented at all, when the graphs are here for just that.

So a cool feature would be to have an option when editing a category to prevent it from showing on the dashboard. Thanks! :)

**Comment by JC5** [comment]
Thanks for opening this issue! I see the problem, but I'm not sure if this is the solution.

I have the same skewed charts, but for me personally financial gain isn't in the categories to the right (the very small ones). It's in the categories right next to the "rent"-column. Groceries, debts, insurance, garden (yes, I actually go outside :wink:).

I know what you mean, but I don't believe that hiding the column is a good idea.
