### ISSUE TITLE
Question about CLI importer

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1437]
I am running Firefly III version 4.7.3 

#### Description of my issue:

I updated to 4.7.3.2 today, and rolled back to 4.7.3 when I noticed that a I have a lot of expense accounts with the `name` and `description` being the actual `IBAN` of the "receiver". I never changed anything to my import-export scripts, thus, the question is, did someone (you or the bank) change anything? at the beginning, when I wrote the script, the 'unknown' recipients were all added to the `(no name)` account

**Comment by JC5** [comment]
There have been no significant changes to the import routine between these versions.

Version 4.7.4 _will_ introduce changes but in 4.7.3(.2) there are no particular changes.
