### ISSUE TITLE
Spectre connection failed. Did you use invalid credentials...

### ISSUE THREAD

**Issue by greensmith** [firefly-iii/firefly-iii#1438]
I am running Firefly III version 4.7.3

#### Description of my issue:

Setting up spectre api starts import then fails with 

`A fatal error occurred, which the import-routine cannot recover from. Please see the explanation in red below.

Spectre connection failed. Did you use invalid credentials, press Cancel or failed the 2FA challenge?

If the error is a time-out, the import will have stopped half-way. For some server configurations, it is merely the server that stopped while the import keeps running in the background. To verify this, check out the log files. If the problem persists, consider importing over the command line instead.`

#### Steps to reproduce 

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):

Debug information generated at 2018-05-17 19:02:38 UTC for Firefly III version **4.7.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.3 |
| FF API version | 0.3 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.16 |
| Display errors | Off |
| Session start | 2018-05-01 00:00:00 |
| Session end | 2018-05-31 23:59:59 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, pdo_mysql, pdo_pgsql, tidy, zip |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@5.0.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.1.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.18, laravel/passport@v5.0.3, laravelcollective/html@v5.6.7, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.3, league/event@2.1.2, league/flysystem@1.0.44, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.12, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.0.8, symfony/css-selector@v4.0.8, symfony/debug@v4.0.8, symfony/event-dispatcher@v4.0.8, symfony/finder@v4.0.8, symfony/http-foundation@v4.0.8, symfony/http-kernel@v4.0.8, symfony/polyfill-mbstring@v1.7.0, symfony/polyfill-php56@v1.7.0, symfony/polyfill-php72@v1.7.0, symfony/polyfill-util@v1.7.0, symfony/process@v4.0.8, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.0.8, symfony/translation@v4.0.8, symfony/var-dumper@v4.0.8, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.1,  |

[2018-05-17 18:52:42] local.INFO: User is being redirected to Spectre.  
[2018-05-17 18:52:43] local.INFO: Start with import job Crd5taInAa8k using Spectre.  
[2018-05-17 18:52:43] local.ERROR: Could not find a valid login for this user.  
[2018-05-17 18:57:28] local.INFO: Start with import job iXEtKURQBIzz using Spectre.  
[2018-05-17 18:57:29] local.INFO: User is being redirected to Spectre.  
[2018-05-17 18:57:30] local.INFO: Start with import job iXEtKURQBIzz using Spectre.  
[2018-05-17 18:57:30] local.ERROR: Could not find a valid login for this user.  
[2018-05-17 18:58:13] local.INFO: Config var "spectre_app_id" is missing.  
[2018-05-17 18:59:02] local.INFO: Config var "spectre_app_id" is missing.  
[2018-05-17 18:59:03] local.INFO: Start with import job tJViWkflFEOX using Spectre.  
[2018-05-17 18:59:05] local.INFO: User is being redirected to Spectre.  
[2018-05-17 18:59:05] local.INFO: Start with import job tJViWkflFEOX using Spectre.  
[2018-05-17 18:59:05] local.ERROR: Could not find a valid login for this user.

**Comment by greensmith** [comment]
I did delete the default_ff customer and let it recreate - got the same outcome.

I am wondering though, I have a second customer, id is my email address, that I used to test logging into my bank. could it be an issue with more than one customer? I'll try deleting the 2nd customer when I get a chance.

**Comment by greensmith** [comment]
I have I to assume that the bank login was correct, as it has detected I have two accounts under that username.
![image](https://user-images.githubusercontent.com/2641887/40201573-560b6b3c-5a17-11e8-9587-2a1269d2a97f.png)

![image](https://user-images.githubusercontent.com/2641887/40201602-67e3baf8-5a17-11e8-85a7-9b02f2b9b1de.png)

I deleted both customers, reset the spectre apis and am still getting the same errors. It does successfully recreate the default_ff3_user though....

```
Truncated from this point <----|\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#79 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#80 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#81 /var/www/firefly-iii/public/index.php(75): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#82 {main}
"} 
[2018-05-17 20:16:26] local.INFO: Config var "spectre_app_id" is missing.  
[2018-05-17 20:16:54] local.INFO: Config var "spectre_app_id" is missing.  
[2018-05-17 20:16:55] local.INFO: Start with import job ASExr8YgeP0k using Spectre.  
[2018-05-17 20:16:56] local.INFO: User is being redirected to Spectre.  
[2018-05-17 20:16:57] local.INFO: Start with import job ASExr8YgeP0k using Spectre.  
[2018-05-17 20:16:57] local.ERROR: Could not find a valid login for this user.  
```

**Comment by greensmith** [comment]
I decided to start from scratch, I wiped the database and reinstalled firefly. Unfortunately still getting the same issue. 

`[2018-05-27 13:12:53] local.INFO: Start with import job KMlPegVZWYbi using Spectre.  
[2018-05-27 13:12:53] local.WARNING: Customer exists already for user, fetch it: Customer with identifier: 'default_ff3_customer' already exists.  
[2018-05-27 13:12:54] local.INFO: User is being redirected to Spectre.  
[2018-05-27 13:12:54] local.INFO: Start with import job KMlPegVZWYbi using Spectre.  
[2018-05-27 13:12:55] local.ERROR: Could not find a valid login for this user.`

When I log in to Spectre, I can see that the default_ff3_customer exists, with 0 logins associated with it, which makes the "Could not find a valid login..." make sense.

However if I manually add a provider within Spectre, it saves it as a customer with my own email address, as seen in the screenshots above. 

Is the default_ff3_customer value optional? can it be changed?

**Comment by JC5** [comment]
Alright, sorry for the late reply. The new release has some code to tackle this issue, and I hope it will be fixed when this release goes live, which should be over the weekend.

The customer's name and value is mandatory, and changing it to your email address wouldn't matter much. The database entry you found doesn't contain the name but also technical connection data. It cannot be changed, unfortunately.

**Comment by JC5** [comment]
Alright, I'm cleaning up and closing some issues. The new release will probably go live tomorrow. Please report back in a new issue.
