### ISSUE TITLE
Update transaction type (if necessary) when rule changes accounts

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1440]
Right now, the rule engine allows you to change the destination account to an asset account. If that makes the transaction go from an asset account to an asset account, it will not be updated to a transfer. That must be changed.

**Comment by JC5** [comment]
This isn't actually possible.

**Comment by Ludo444** [comment]
Maybe would be possible to add a new rule instead? Using the "Convert a withdrawal into a transfer" functionality, which takes only asset account as a parameter

**Comment by JC5** [comment]
Conversion by rule is tricky. I've created a card to look into this. If I can make it work, it will be in the changelog!
