### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mackcoding** [firefly-iii/firefly-iii#1444]
Hello,

I am installing the latest version of Firefly III - 4.7.3.2 with a freshly install Debian 9 (latest) container, running php7 and nginx. 

First off, running the command per the documentation gives the following error:

```
 [InvalidArgumentException]
  Could not find package grumpydictator/firefly-iii with version 4.7.3.2 in a version installable using your PHP version 7.0.27.
```

> PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
>     with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
>  cat /etc/debian_version 9.4

I am able to get around this error with the flag **--ignore-platform-reqs**

I got everything installed and now I get a 500 error. The logs are reporting this for multiple lines:

```
2018/05/24 02:21:39 [error] 471#471: *3 FastCGI sent in stderr: "PHP Parse error:  syntax error, unexpected '?' in /home/domain/public_html/firefly-iii/vendor/symfony/http-foundation/Response.php on line 499
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
PHP Parse error:  syntax error, unexpected '?' in /home/domain/public_html/firefly-iii/vendor/symfony/http-foundation/Response.php on line 499
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0" while reading response header from upstream, client: 96.227.248.30, server: domain request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/php-nginx/15271251048407.sock/socket:", host: "domain"
```

Any suggestions are welcomed. Seems like it should be a fairly simple install.

**Comment by JC5** [comment]
Please make sure you’re running php 7.1. That should fix it.
