### ISSUE TITLE
Piggy savings : Non technical issue :-)

### ISSUE THREAD

**Issue by Jumanjii** [firefly-iii/firefly-iii#1447]
Hi, I have a savings issue I do not find a solution for ;-D

I want to have an annual budget for clothes.

In the beginning, I was thinking to do a piggy about it but, we can not link a transaction to a piggy.

Another solution I was thinking was to have budget "clothes" and to add the left over on the next month each month. Problem: that would destroy monthly budgeted information (that is really valuable).

I am torturing myself about it from 2 days so *"Why not ask on the GitHub repo ?* ^_^

If anyone has an idea to solve my issue of annual budget, thanks for sharing :-)
 
Regards,

**Comment by JC5** [comment]
Good idea! ;)

What you could do:

* Go to `/preferences`
* Go to tab "Layout"
* Set the view range to "One year"
* Save your preferences
* Go to `/budgets`
* Each budget amount you change will now be set for one year.
* Go to `/preferences` again and set the range back to one month.

You will now have a budget that you have set for one year. You can also set the one month as well, and both will be tracked by Firefly III.

**Comment by Jumanjii** [comment]
It works! :-) 

I'm just asking if it could be perfect: it is already possible to not add a yearly budget in month summary? ;-D

Example: Add a transaction and link it to "clothes", it will increase spent on yearly budget "clothes" but will not increase monthly spent in the header summary of "/budgets"

I'm not sure if I'm understandable, and I know that would be a highly complex task, I'm just asking to be sure a way do not already exist ;-D

**Comment by JC5** [comment]
Unfortunately, that's not possible. Expenses spent in budgets count for the monthly "available budget" as well as the yearly one.

I know that this skews your monthly budgets, but that is the disadvantage of budgeting over two time periods (yearly _and_ monthly).

**Comment by Jumanjii** [comment]
I think we can close this issue :-)
