### ISSUE TITLE
Incorrect calculations of budgets spent a day

### ISSUE THREAD

**Issue by paul999** [firefly-iii/firefly-iii#1449]
I am running Firefly III version current develop branch

#### Description of my issue:
The amount for a budget spent in the past is calculated over the upcoming 3 days, while it is spent over the earlier 28 days in the month:
![image](https://user-images.githubusercontent.com/65767/40614942-127e9c9c-6285-11e8-8345-80ba5820c842.png)

#### Steps to reproduce 
Spending budgets and seeing the calculated amounts in spent (per day)

**Comment by JC5** [comment]
Yep. That's a silly bug. Fixed on the demo site, will go live with 4.7.4!
