### ISSUE TITLE
YNAB import

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#145]
Hi,
I am trying to import a YNAB export file as I am planning to migrate from YNAB to Firefly.

I try to make some changes to the importer code as YNAB uses two columns, one for Credit and one for Debit. 
I already added some fields to the csv.php that defines the fields, however YNAB returns the amounts as '€15,95' and the normal Amount class that does the conversion doesn't recognize it as a valid number.
I was thinking, maybe some kind of locale information is needed to know how to parse the numbers in the csv file.
Can you guide me in the correct direction to implement this, so I can test is and create a PR?

**Comment by JC5** [comment]
Does YNAB not export raw amounts? That is weird, and pretty sloppy. But looking at their support pages, it seems they do. Oh well, more people for me! Yay!

To support this you would either need more options at the initial screen (and there are seven already) or some way of knowing how to format the number.

Does YNAB export locale information? Do they always export in a specific locale? Or can you change this?

Oh and if you can, check if the raw text of the CSV actually exports the "€".

**Comment by roberthorlings** [comment]
I actually ran into something similar with the CSV file provided by ABN AMRO: they contain amounts with a comma as decimal separator. I have implemented a [simple converter](https://github.com/roberthorlings/firefly-iii/blob/4909fcc8b4bb744d2dceb74065dbec3a6ca43c80/app/Helpers/Csv/Converter/AmountComma.php) to handle the amounts. However, a way of working with a locale could be a better solution. Would there be any other locale-specific information in the files?

**Comment by JC5** [comment]
I just thought of something. On the bottom of the page is room for specifix.

I'll write something to do two things:

* "clean" the amounts: remove spaces, remove euro-signs, dollar-signs, etc.
* Format the amount according to your Firefly III language, which can be Dutch or English.

This would be an option in the checkbox-list on the bottom of the page.

**Comment by zjean** [comment]
That's a nice solution!

**Comment by zjean** [comment]
I think I need to wait before implementing this, because YNAB supports splitting transactions and I see that issue #142 is not finished yet.

**Comment by mkasu** [comment]
interested in this. support for splitting transactions also seems to be implemented. @zjean still working on this? any way I can help?

**Comment by JC5** [comment]
Alright split transactions exist now, and the importer has been rewritten. I could use a file with 10/20 transactions, anonymised of course, to start implementing this.

**Comment by zjean** [comment]
Hi,
I created two test files (one for each account, that's how YNAB exports) that contain some split transactions.

[My Budget as of 2016-11-24 703 PM-Budget.txt](https://github.com/JC5/firefly-iii/files/611956/My.Budget.as.of.2016-11-24.703.PM-Budget.txt)
[My Budget as of 2016-11-24 703 PM-Register.txt](https://github.com/JC5/firefly-iii/files/611955/My.Budget.as.of.2016-11-24.703.PM-Register.txt)

**Comment by JC5** [comment]
Wow, those splits are horrible. Not your fault though :D.

I'll see what I can do. Thanks for generating these!

**Comment by tomazsustar** [comment]
Hi, there is a lot of banks that generate exports where the amount is in two columns. One for revenue one for expenses. Currently the firefly can not handle this. I was assuming I could map both columns to amount, but than I got the message that the amount is 0 and the transaction can not be imported.

I thing that decimal comma/dot, basically number format should be selectable with each import similar as for date format. For example on three different accounts I get 3 different number formats from their exports.
1234.65
1'234.56
1234,56

I would also find it useful to be able save/link the import configuration to asset account on server, so that I could for example select the asset account and the import file instead of uploading both, the config file and the import file.

**Comment by JC5** [comment]
Yes, this is a common issue. I hadn't expected banks to be that crappy but there you are. There's a custom fix for one specific bank but it needs a more permanent thing. I can add a column "type" for both accounts that should take care of it.

Storing the configuration on the server is definitely a good idea.

**Comment by JC5** [comment]
There is now a YNAB API for which I signed up. I hope they respond positively.

**Comment by JC5** [comment]
I'm closing this since it's fixed. Look for this feature in the next release, and let me know if you encounter any problems!
