### ISSUE TITLE
A rule action to allow the change from deposit/withdrawal to transfer

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1450]
Make sure user enters the opposing account that should be associated with the new transfer.

**Comment by hamuz** [comment]
+1

**Comment by JC5** [comment]
The code for this feature is now live on [the demo site](https://demo.firefly-iii.org/) where you can try it. Since the docs aren't online yet for this feature:

---

If you set an action to convert your transaction to a deposit, a transfer or a withdrawal, make sure that you configure the rule action correctly. If you don't do this right the rule action wil *silently* fail and nothing will happen. Here you can read what will happen to your transaction. This is dependent on the original type and the future type of the transaction.

These conversions will *not* be applied to split transactions.

**From a deposit to a withdrawal**
The money will be transferred away from the asset account instead of deposited into it. The "action value" you must provide must be the name of a valid expense account. If it does not exist, it will be created.

If you leave the action value blank, the new expense account will be named after the revenue account. So, a deposit from "Your Boss" becomes a withdrawal at "Your Boss".

**From a transfer to a withdrawal**
Firefly III will replace the "destination" asset account with an expense account. So, a transfer from your Checking Account to your Savings Account will be converted into a withdrawal from your Checkings Account to Account X, where X is an expense account. The "action value" you must provide must be the name of a valid expense account. If it does not exist, it will be created.

If you leave the action value blank, the new expense account will be named after the original destination asset account.

**From a withdrawal to a deposit**
The money will be deposited into the asset account instead of withdrawn from it. The "action value" you must provide must be the name of a valid revenue account. If it does not exist, it will be created.

If you leave the action value blank, the new revenue account will be named after the original expense account. So, a withdrawal from "Walmart" becomes a deposit from "Walmart".

**From a transfer to a deposit.**
Firefly III will replace the "source" asset account with an revenue account. So, a transfer from your Savings Account to your Checking Account will be converted into a deposit into your Checkings Account from Account X, where X is a revenue account. The "action value" you must provide must be the name of a valid revenue account. If it does not exist, it will be created.

If you leave the action value blank, the new revenue account will be named after the original source asset account.

**From a withdrawal to a transfer**
The money will be moved away from the original asset account, into another asset account. The "action value" you must provide must be the name of a valid destination asset account. If it does not exist, the action will fail.

If you leave the action value empty, the action will fail.

**From a deposit to a transfer**
The money will be moved into from the original asset account, from another asset account. The "action value" you must provide must be the name of a valid asset account. If it does not exist, the action will fail.

If you leave the action value empty, the action will fail.

@hamuz @dasbaumwolltier @marcelbrueckner

**Comment by hamuz** [comment]
If you ask me, I would combine this with existing 'Set destination' and 'Set source', based on whether the account chosen is asset/revenue/expense.
Otherwise all the weird behavior of old actions still exists.

What use-cases you envision for new actions?
What use-cases you believe that old actions used for?
How are those different?

**Comment by JC5** [comment]
The old actions do exactly one thing: they change the account based on the type of the transaction. You suggestion would mean that one action would do two things, and unpredictably too.

You set the destination account of a withdrawal to X, and X is an asset account. This magically turns the withdrawal into a transfer, which is not what you did. But what if X is an expense account? Then nothing happens. Or X is a revenue account. It magically turns into a deposit. But if X does not exist, the type of the transaction won't change. That's unpredictable.

The single action "turn transaction into X" can be used with trigger "transaction is a X" where X is a transaction type. An often heard complaint is that Firefly III imports stuff badly or the other way around. And voila.

* Trigger: Transaction is deposit
* Trigger: Description contains ATM
* Action: turn into withdrawal.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
