### ISSUE TITLE
Database inconsistencies for tags

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1452]
I am running Firefly III version 4.7.4 

#### Description of my issue:

I cleaned up my import tags, as I do not really use them, but noticed they were still available to be selected on the transaction page:

![2018-05-31 19_13_49-edit transaction _strafe_ transactions firefly iii](https://user-images.githubusercontent.com/3742238/40797050-310159e6-6507-11e8-97da-54b29ab38143.png)
![2018-05-31 19_15_34-tags firefly iii](https://user-images.githubusercontent.com/3742238/40797087-460ed732-6507-11e8-94d2-c1b62c23af18.png)

Is it possible I have some kind of inconsistencies within the tags tables?

#### Steps to reproduce 

I created a test-tag on the demo installation, deleted it but did not find it in the tag autocomplete list

**Comment by gavu** [comment]
Hi @JC5, thanks for the quick answer, unfortunatelly the `/flush`, the `php artisan ca:cl` and the browser cache delete did not help. I noticed that only these 8 imports are displayed, is it because the autocomplete selects the first 8 entries found? or is it only these 8 entries that are affected somehow?

**Comment by JC5** [comment]
If they're still there they must still exist in the database somehow. But they're no longer on the `/tags` page?

**Comment by gavu** [comment]
I'm sure of that, can't post the screenshot as I have client names as tags... you'll just have to trust the user this time 😊

**Comment by JC5** [comment]
OK, use one of the import tags for a transaction, then visit the transaction page. Click the import tag to visit its page.

Is that ID still in the database?

**Comment by JC5** [comment]
And is the `deleted_at` column empty?

**Comment by gavu** [comment]
I finally got to it
1. I added the 'deleted' tag to the transaction, it was accepted, and I can click on it. It works just like the others, it shows the tag page with only one transaction in it, the correct one
2. The `deleted_at` column is `NULL` and `tagMode` is `Nothing`

**Comment by JC5** [comment]
OK, so that works. What happens when you try to add one of these "Import with key" tags to a transaction?

**Comment by gavu** [comment]
I did exactly that. I now have a tagged transaction with a tag that does not show up on the tags page.

**Comment by JC5** [comment]
I think I found it. I'm pretty sure you're on the dev-branch, so let me know if this solves it for you. :+1:
