### ISSUE TITLE
Budget prepopulate (auto-fill)

### ISSUE THREAD

**Issue by kitkan87** [firefly-iii/firefly-iii#1457]
I am running Firefly III version 4.7.3

Would it be possible for the budget to prepopulate with the previous months budget automatically. For example, I have to pay a monthly condo fee of $600 every month due on the 1st and it only changes about 1 time a year.

Would it be possible for next month budget to auto-fill (prepopulate) with the previous month "condo fee" budget. Then when there is an increase, the user will manually edit the current month and when the next month comes it will now auto-fill with the previous month newly manually edited budget.

Thanks.

**Comment by kitkan87** [comment]
I understand. Thanks for taking the time to reply.

**Comment by techytuppers** [comment]
Ah disappointing, I was about the ask the same query having noticed that June's budgets have all been set to 0, compared to all the numbers set in May.

Does this feature request not sound similar to the same functionality that is already in place for creating a new transaction? There is a checkbox there that loads a pre-populated transaction once the user has submitted a transaction. Could the budgets individually have the same opt-in?
