### ISSUE TITLE
"All transactions for category" -> Doesn't show all transactions

### ISSUE THREAD

**Issue by techytuppers** [firefly-iii/firefly-iii#1458]
I am running Firefly III version 4.7.3.2

#### Description of my issue:
When trying to look at all transactions within a certain category, "all" does not show all transactions.

Examples:
I see 1 transaction, the oldest, there are a total of 4, all from May (screenshots attached to detail this instance of the bug)
I see 3 transactions, the most recent ones from May, where there are a total of 14 (all from May)

#### Steps to reproduce 
Locate a transaction with a category
Click that category
Click "Show all transactions without grouping them by date." or "Show everything" or update URL to be /categories/show/X/all where X is the category number

Cannot replicate on the demo site

#### Other important details (log files, system info):

Debug information generated at 2018-06-01 20:23:05 Europe/London for Firefly III version **4.7.3.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.3.2 |
| FF API version | 0.3 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.17 |
| Display errors | Off |
| Session start | 2018-06-01 00:00:00 |
| Session end | 2018-06-30 23:59:59 |
| Session first | 2018-05-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true | 

![category-all](https://user-images.githubusercontent.com/2923033/40859467-d7fd5c2c-65d9-11e8-9bd0-a230d93025dc.jpg)
![category-june](https://user-images.githubusercontent.com/2923033/40859468-d818f950-65d9-11e8-99ae-620181d177be.jpg)
![category-may](https://user-images.githubusercontent.com/2923033/40859469-d83592cc-65d9-11e8-88db-ae65352b6576.jpg)

**Comment by techytuppers** [comment]
Thanks for replying so quickly!

Correct, the top screenshot should have 3 transactions. Unfortunately `/flush` didn't change the result

**Comment by JC5** [comment]
I was able to replicate your issue, and I've fixed it. Turns out the error was in an SQL query.
