### ISSUE TITLE
Apply rules yes/no for bunq imports

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1459]
Will be global provider option.

**Comment by OGKevin** [comment]
What does this actually mean ? :p Im not sure what rules yes/now mean.

**Comment by JC5** [comment]
Whether or not to apply your rules after importing isn't an option right now. They will always be applied.

**Comment by OGKevin** [comment]
Ah i see, thanks.

**Comment by JC5** [comment]
Implemented in 4.7.5 :+1:
