### ISSUE TITLE
Import over command line (bunq + Spectre + others)

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1461]
File import can already be done over command line.

**Comment by crummy** [comment]
Is there a URL or similar we can use to trigger this now, e.g. via IFTTT?

**Comment by colinerd** [comment]
+1 would like to automate daily imports from bunq

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
