### ISSUE TITLE
Import over API (file + bunq + Spectre)

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1462]
See title.

**Comment by philthynz** [comment]
Hey. I am running 4.7.5. Has this already been implemented in 4.6.7 already?

**Comment by JC5** [comment]
No I’ve mixed up my numbers on the roadmap.

**Comment by JC5** [comment]
Some notes, ignore me.

API for import routine:

- end point to create a job. Should be fairly easy.
- end point to start a job. This is more difficult. Some import routines run well over 30 seconds and need constant attention. With a 30s job time out this won't work. Some job routines auto-stop after 25 seconds and indicate that you need to "start" the job again. Same applies here.
- end point to read status of job. Is also easy.

**Comment by joshwapohlmann** [comment]
I' also like request this to work with FinTS

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
