### ISSUE TITLE
Remove unactive asset account from transaction

### ISSUE THREAD

**Issue by jinformatique** [firefly-iii/firefly-iii#1463]
I am running Firefly III version 4.7.3

This is more a new request, not an issue. It would be nice to remove the account name in an expense from the **Asset account (source)** when the account is no longer active.
For example, I closed one of my bank account and I unchecked the box **active** in the asset account detail. But then when I do a new withdrawal, I still see the account name in the list **Asset account (source)**. Same for new deposit.

Thank you.

**Comment by JC5** [comment]
Yeah that feature got lost in translation somehow. I’ll get it back in 4.7.5

**Comment by JC5** [comment]
Will be fixed in the next version :+1:
