### ISSUE TITLE
Sorting columns in transaction overview

### ISSUE THREAD

**Issue by LvanWissen** [firefly-iii/firefly-iii#1465]
**Description**
While browsing through my just imported transactions, I noticed it is not possible to sort columns on for instance the transaction amount (high-low) or the destination account (A-Z). 

Version: 4.7.4

**Solution**
The ability to sort columns in the tabular overview in Transactions and Categories on e.g. 'Amount' or 'Destination'.  

**What are alternatives?**
Sorting is possible in the accounts overview, but not on the same data.

**Comment by JC5** [comment]
I am not sure it would add anything useful, to be honest.

**Comment by JC5** [comment]
Yes, I can see how sorting would clarify the data on that page. However, there are several types of reports that show these kinds of things, and I'd rather direct users to those. I'll admit there is no specific report focussed on revenue accounts or expense accounts, but that's in the works.

I feel that sorting individual lists wouldn't bring more clarity.

**Comment by LvanWissen** [comment]
Alright, thanks for your comments. I will have a further look at the reports functionality!
