### ISSUE TITLE
Add Monero to supported currencies

### ISSUE THREAD

**Issue by chelmzy** [firefly-iii/firefly-iii#1466]
**Description**
I see that you aren't looking to add any more currencies, but I feel that a significant percentage of Firefly users currently hold or are interested in Monero. I hope that you will consider adding it. Thanks for all your hard work on this project!

**Solution**
```
$currencies[] = ['code' => 'XMR', 'name' => 'Monero', 'symbol' => 'ɱ', 'decimal_places' => 12]; 
```

**Comment by JC5** [comment]
You can add it yourself under /currencies, did you find that page already? That’s also the reason I don’t add currencies anymore. I don’t need to :wink:
