### ISSUE TITLE
Support QIF file format for imports

### ISSUE THREAD

**Issue by pommetjehorlepiep** [firefly-iii/firefly-iii#1467]
I would like Firefly III to be able to import QIF files  (Quicken Interchange Format)

**Solution**
QIF is a widely used format by banks for exporting  transaction data. Format was originally developed
for MS Quicken.
This is a better format than CSV + banks I use support it (...they don't support Bunq or Spectre).

**What are alternatives?**
CSV, Bunq & Spectre, QFX (see feature request #965)

**Additional context**

**Comment by JC5** [comment]
:+1: on the list!

**Comment by BongoEADGC6** [comment]
Please? =(

**Comment by mwolfaardt** [comment]
Where can I upvote for this feature?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
