### ISSUE TITLE
Tag not added when creating new tag in transaction

### ISSUE THREAD

**Issue by geryduyck** [firefly-iii/firefly-iii#1468]
**Bug description**
I am running Firefly III version  4.7.3.2

After creating a few transactions (I currently have 10 tags) it is not longer possible to create new tags by entering a new keyword/tag in the add transaction window meta data panel. 
The transaction is saved but, the tag is not created and added.

I remember this was possible when first starting to add transactions, but noticed after some tags were missing from transactions.

You can create a tag manually and add it.

**Steps to reproduce**
- transaction -> new transaction
- add some data
- enter unexisting tag keyword
- save transaction

**Extra info**
My installation runs the docker image (jc5x/firefly-iii) latest on a Ubuntu VPS cloud hosting,
not that I assume this to be the error source. 

Browsers tried: (same problem)
- Safari
- Chrome

Debug information generated at 2018-06-05 22:15:33 Europe/Amsterdam for Firefly III version **4.7.3.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.3.2 |
| FF API version | 0.3 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.17 |
| Display errors | Off |
| Session start | 2017-09-01 00:00:00 |
| Session end | 2018-06-05 00:00:00 |
| Session first | 2017-09-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, pdo_mysql, pdo_pgsql, tidy, zip |
| Installed packages | bacon/bacon-qr-code@1.0.3, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.1.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.22, laravel/passport@v5.0.3, laravelcollective/html@v5.6.8, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.12, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.0.9, symfony/css-selector@v4.0.9, symfony/debug@v4.0.9, symfony/event-dispatcher@v4.0.9, symfony/finder@v4.0.9, symfony/http-foundation@v4.0.9, symfony/http-kernel@v4.0.9, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.0.9, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.0.9, symfony/translation@v4.0.9, symfony/var-dumper@v4.0.9, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.1,  |

**Comment by JC5** [comment]
It seems to work on the demo site. Trick question: is the tag blue before you submit the transaction?

**Comment by geryduyck** [comment]
OK I feel stupid, somehow I must have missed to press the enter button and used tab instead.
My mistake, still a newbie user of the platform!

**Comment by JC5** [comment]
No problem!
