### ISSUE TITLE
Recurring transactions

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1469]
This is an issue where I collect notes and ideas for recurring transactions, something that is going to be added to Firefly III v4.7.5.

The idea is that you define a "recurring transaction" (RT) with a few properties such as description, amount, accounts, tags, etc.

Start of first transaction is a must or assumed to be today.

The repetition requires some thinking but will probably something along the lines of what Google Calendar does (offering "smart" suggestions and a dialog for a custom repetition). I still have to think about how repetitions can be customized per RT and what the best storage solution is.

Many online solutions try to do a full in-database calculation of when the repetition hits but that's not something I want to use. Probably something like this:

* Repetition type: daily, weekly, monthly on day _n_, yearly, *n*th *wednes*day of the month. Possibly others?
* Repetition skip: 0 (every X), 1 (every other X), 2 (every third X), etc

Needs a cron job / command line thing to generate the transactions.

Firefly III will calculate the next occurrence live during the cron job or some other event. Will use the date of the last occurence to calculate further ahead.

Placeholders (%month, %year) might be added as well. Probably iteration 2.

**Comment by jtasseroul** [comment]
I'd be very interested in a mechanism similar to GNUCash's Recurring Transactions. I'm currently toying with Firefly-III in parallel with GNUCash before completely switching, and it is the most glaring difference in features that I'm heavily using between the two.

**Comment by JC5** [comment]
I'm thinking of something similar. Biggest differences are:

- It won't create transactions in advance or remind you in advance. Perhaps in a later stage it'll remind you but that's it.
- Frequencies are the same, but bi-monthly is missing. Skipping days is possible.
- The "weekly"-frequency will only accept one day of the week for now. Support is present for multiple days is present but not added to the user interface.


Things I hadn't thought of:

- Skip the weekend to next or prev weekday
- Use more calendars

Things GNUcash doesn't do:
- Yearly recurring.
- Xth X-day of the month, like second thursday or first tuesday.

**Comment by JC5** [comment]
Haha, that is good to hear!

Bi-weekly, bi-monthly and quarterly are all possible by skipping one or two months. The 15th _and_ the 30th of the month won't be possible in the first release. The database supports it and the API will allow it but the user interface won't have room for it.

**Comment by JC5** [comment]
Code is OK, will be live in 4.7.5.

**Comment by Kovah** [comment]
Is there any chance to get more advanced recurring options for the schedule into the interface? I have many recurring transactions that are due every two or three months which is not possible with the current interface.
I would try to implement a non-breaking option if you are ok with that.

**Comment by JC5** [comment]
Unless you want to alternate a transaction to appear every 2 _and_ 3 months (for example January, March, June, August, etc) I suggest you use the "skip" field that is already present.

**Comment by Kovah** [comment]
So if I understand this right, I select "Every Month" as the recurring option and set "Skip" to 2. Then the app will create one transaction in the first month, skip two creations and create a transation in the 4th month. Is that correct?

**Comment by JC5** [comment]
That's correct.

**Comment by Kovah** [comment]
Awesome, thanks!
