### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by cusco** [firefly-iii/firefly-iii#1470]
Hello

I'm attempting to install for the first time. I'm new on docker too, but tried it and want to use it for everything now.

I've checked docs at http://firefly-iii.readthedocs.io/en/latest/installation/docker.html and followed the path of using docker-compose

Got the docker-compose.yml from github, changed some values in there and I'm getting:

> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Is the docker-compose badly formatted? I was thinking of removing the version and placing the service at the root of the file. But I'm unsure on how to proceed.

**Comment by JC5** [comment]
The Docker file is at version 3.2, which means you must run at least Docker version 17.04.0+.

What is the output of `docker --version`?

**Comment by cusco** [comment]
Hello JC5, thank you for prompt reply

I upgraded my "docker-compose" from https://github.com/docker/compose/releases and it works now :)

```
cusco@neptune:~$ /usr/bin/docker-compose version
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

cusco@neptune:~$ /usr/local/bin/docker-compose version
/bin/sh: /tmp/_MEIGAn5PN/libtinfo.so.5: no version information available (required by /bin/sh)
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

Still, docker version:
> Docker version 18.03.1-ce, build 9ee9f40


I

**Comment by JC5** [comment]
:+1: glad to hear it works!
