### ISSUE TITLE
firefly in docker behind apache reverse proxy - https

### ISSUE THREAD

**Issue by cusco** [firefly-iii/firefly-iii#1471]
Hello,
I commented on the issue https://github.com/firefly-iii/firefly-iii/issues/864 but it is already closed, as such I'm creating a new one. 

Just installed firefly from docker and am happy with it.

Configured apache reverse, works fine, except browser is blocking elements that resource to http:// instead of https://

Looking at the previously mentioned issue found that should set 2 env variables. I did so. I can see in docker inspect that the env variables are there
ran php artisan config:cache inside the docker

but it is still sourcing http:// content.

Is there something I can do about this?

**Comment by cusco** [comment]
Hello,

The comment https://github.com/firefly-iii/firefly-iii/issues/882#issuecomment-333507270 resolved my issue.

Thank you!

**Comment by JC5** [comment]
Glad to hear it works!
