### ISSUE TITLE
How can I have the latest version of firefly on sandstorm?

### ISSUE THREAD

**Issue by eduedp** [firefly-iii/firefly-iii#1473]
I'm running my Firefly on sandstorm, but it's some versions behind the latest release. 
I noticed some fixes that were made between those versions corrects bugs I came across, so I want to upgrade to the latest release if possible.

Is there a way, and how difficult is it for someone to run/compile/mount (I don't know the word) the latest version of Firefly on Sandstorm?

Thanks

**Comment by JC5** [comment]
I was under the impression that Sandstorm instances would auto-upgrade, but I'm not really sure. I'm going to tag @ocdtrekkie because I can't find it in the documentation. Please stay tuned!

**Comment by ocdtrekkie** [comment]
Unless your administrator has shut it off, @eduedp, you should get a notification on the top right when apps have updates available with a one-click button to apply them. If you do not see this notification, you can go to the app market, and click to install the app on your Sandstorm server again. Sandstorm should ask if you'd like to upgrade the app, and then once you've upgraded the app, the app page on Sandstorm should offer you a button to upgrade all of your existing grains.

**Comment by ocdtrekkie** [comment]
Note that the current release on Sandstorm is 4.7.2.2. @JC5, are you going to push 4.7.4?

**Comment by JC5** [comment]
Yes, thanks for reminding me! I always wait a few days in case of bugs.

**Comment by ocdtrekkie** [comment]
Oh, and the other point of note with regard to @eduedp's question is that since apps are signed, while it is not too hard to build a Sandstorm app package yourself, you can't upgrade a Sandstorm app unless your new app is signed with the same app publishing key, which only @JC5 has.

**Comment by JC5** [comment]
I've just pushed 4.7.4 to the Sandstorm servers. :+1:

**Comment by ocdtrekkie** [comment]
I'll take care of testing and approvals either today or tomorrow. I did do a "install upgrade, make sure my data is still there" glance.

Note that (at your own risk, take backups first), you can manually upgrade by installing from the experimental release URL: https://apps.sandstorm.io/app/uws252ya9mep4t77tevn85333xzsgrpgth8q4y1rhknn1hammw70?experimental=true

**Comment by ocdtrekkie** [comment]
I approved it to the main app store, so @eduedp should get a notification to update, or can go to apps.sandstorm.io and install Firefly III to manually trigger the upgrade (if you do the latter, remember to upgrade your grains from the app's page as well!).

This can be closed.

**Comment by JC5** [comment]
:+1:
