### ISSUE TITLE
Import CSV doesn't handle reversals correctly

### ISSUE THREAD

**Issue by pommetjehorlepiep** [firefly-iii/firefly-iii#1474]
I am running Firefly III version 4.7.4

I've imported a CSV which contained a so-called reversal, looking like this:

> ,12/10/2017,Rev:Purchase  Ref: 2017285739676352,--$21.78
> ,12/10/2017,Purchase Ref: 2017285739676352,-$21.78

Both transactions get imported OK, but the amount for the actual reversal (top transaction)
ends up being recorded as **$ 0.00**, instead of being credited(+) $21.78.

So actual reversal gets ignored and net change is -$21.78 instead of $0.00.

**Steps to reproduce**
Create a CSV file containing a simular transaction as described above and import CSV
file as per normal.

**Extra info**

**Bonus points**

**Comment by JC5** [comment]
That's not a surprise. Firefly III doesn't parse monetary amounts. It can't do math. 

I am very curious to hear which bank does -- btw. Let me know!

Fix will be live in 4.7.5.

**Comment by JC5** [comment]
Closing this to clear the list.
