### ISSUE TITLE
Transactions page navigation problem

### ISSUE THREAD

**Issue by pommetjehorlepiep** [firefly-iii/firefly-iii#1475]
**Bug description**
I am running Firefly III version 4.7.4

When in the Transactions screen where you can view all the transactions, on the
right it shows summaries by the month.
Clicking on one of these months, the transactions for that month are selected including
the proper number of page buttons expected are displayed.

But once you click on say '2' or next, the transactions displayed are not for the month displayed,
but it actually reverts back to the 1st page of the global selected date range (including the pagination buttons)

Expected:  2nd page of transactions for the selected month

**Steps to reproduce**

1. Open Transactions -> Expenses  (see Screenshot 1)
2. Click on one of the Month summaries on the right  (result see Screenshot 2)
3. Now click on the 2nd or next page button  (result see Screenshot 3)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom).

**Bonus points**

__Screenshot 1__
![transactions-expenses 1of3](https://user-images.githubusercontent.com/8982487/41187754-a2aa9366-6bf4-11e8-95bd-5abca80a2d30.png)

__Screenshot 2__
![transactions-expenses 2of3](https://user-images.githubusercontent.com/8982487/41187755-a2e08da4-6bf4-11e8-80c8-2a11ef852267.png)

__Screenshot 3__
![transactions-expenses 3of3](https://user-images.githubusercontent.com/8982487/41187756-a31c1afe-6bf4-11e8-8626-99c62a6d1204.png)

**Comment by JC5** [comment]
:+1 nice find! Will be fixed in the next release.

**Comment by JC5** [comment]
I'm closing this to clear up the list. 4.7.5 should be released end of the month.
