### ISSUE TITLE
Add and update transaction links with bulk edit

### ISSUE THREAD

**Issue by Elissarc** [firefly-iii/firefly-iii#1477]
**Description**

I often have a lot of expenses that are reimbursed by my employer. I usually get the money back at the end of the month and it takes quite some time to link all the expenses to the reimbursement.

**Solution**

I would like to update transaction links with bulk edits so I could just select all my expenses and link them to the reimbursement.

**What are alternatives?**

Create the links one by one.

**Comment by JC5** [comment]
I'm sorry, that is way too small a use case to build.

**Comment by Elissarc** [comment]
I agree that it is a small use case and that there are more useful features to implement. But still, I think the bulk edit functionality could deserve an enhancement so it can update more than the 3 available fields.

Anyway, I am using firefly since 3 weeks and I think it is a great piece of software. Thank you for the time you put into it!
