### ISSUE TITLE
Clear Application Cache after account import

### ISSUE THREAD

**Issue by 4oo4** [firefly-iii/firefly-iii#1478]
**Bug description**
I am running Firefly III version 4.7.4
I've noticed recently that whenever I run an import, the account balance on the main accounts screen takes a while to update I run `artisan cache:clear`.  Is it possible to have that happen automatically after running an import, at least for the GUI?

**Steps to reproduce**
 1. Import CSV data into an account (cli or via web upload)
 2. Go to Accounts page, see account with old data for Amount/Date
 3. Refresh page a few times, get impatient, run `artisan cache:clear` and new data is shown

**Extra info**

OS: Ubuntu 16.04
Browser: Firefox 60.0/Chrome 68.0

Debug information generated at 2018-06-09 22:53:10 UTC for Firefly III version **4.7.4**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.4 |
| FF API version | 0.3 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, daily |
| PHP version | 7.1.17-1+ubuntu16.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2018-06-01 00:00:00 |
| Session end | 2018-06-30 23:59:59 |
| Session first | 2013-10-02 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | 'en_US' |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite, sqlsrv |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | 'unknown' |
| Trusted proxies (.env) | 127.0.0.1 |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, interbase, intl, json, ldap, exif, mcrypt, mongodb, msgpack, mysqli, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, recode, redis, shmop, SimpleXML, smbclient, snmp, soap, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, psr/http-message@1.0.1, guzzlehttp/psr7@1.4.2, guzzlehttp/promises@v1.3.1, guzzlehttp/guzzle@6.3.3, bunq/sdk_php@dev-master, vlucas/phpdotenv@v2.4.0, symfony/css-selector@v4.1.0, tijsverkoyen/css-to-inline-styles@2.2.1, symfony/polyfill-php72@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/var-dumper@v4.1.0, symfony/routing@v4.1.0, symfony/process@v4.1.0, symfony/polyfill-ctype@v1.8.0, symfony/http-foundation@v4.1.0, symfony/event-dispatcher@v4.1.0, psr/log@1.0.2, symfony/debug@v4.1.0, symfony/http-kernel@v4.1.0, symfony/finder@v4.1.0, symfony/console@v4.1.0, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.4, swiftmailer/swiftmailer@v6.0.2, paragonie/random_compat@v2.0.12, ramsey/uuid@3.7.3, psr/simple-cache@1.0.1, psr/container@1.0.0, symfony/translation@v4.1.0, nesbot/carbon@1.25.0, monolog/monolog@1.23.0, league/flysystem@1.0.45, erusev/parsedown@1.7.1, dragonmantank/cron-expression@v2.1.0, doctrine/inflector@v1.3.0, laravel/framework@v5.6.23, davejamesmiller/laravel-breadcrumbs@5.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, fideloper/proxy@4.0.0, zendframework/zend-diactoros@1.7.2, symfony/psr-http-message-bridge@v1.0.2, phpseclib/phpseclib@2.0.11, league/event@2.1.2, lcobucci/jwt@3.2.2, defuse/php-encryption@v2.2.0, league/oauth2-server@6.1.1, firebase/php-jwt@v5.0.0, laravel/passport@v5.0.3, laravelcollective/html@v5.6.9, league/commonmark@0.17.5, league/csv@9.1.4, league/fractal@0.17.0, paragonie/constant_time_encoding@v2.2.2, symfony/polyfill-util@v1.8.0, symfony/polyfill-php56@v1.8.0, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, twig/twig@v1.35.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0,  |

Cheers

**Comment by JC5** [comment]
Mmm, thanks for letting me know! I thought code was present to do exactly this: it's been suggested before.

I'll do some digging. I should be able to replicate this easily and report back.

For the time being, you can also browse to `/flush` which does the same thing.

**Comment by JC5** [comment]
Code to do this is now present. Will be live with 4.7.5. I'm closing this one, don't hesitate to contact me if you have questions.
