### ISSUE TITLE
Access denied error

### ISSUE THREAD

**Issue by THExGOLDDEVIL** [firefly-iii/firefly-iii#1479]
Hi,
I'm new to linux so please forgive my ineptness on my description.
I have been following your setup guide for self hosting and I am stuck on an access denied error when I run the "php artisan migrate:refresh --seed" command. It pops up with 3 errors.

In connection.php line 664:
SQLSTATE[HY000] [1698] Access denied for users 'homestead'@'localhost' (SQL:  select * from information_schema.tables where table_schema = homestead and table_name = migrations

In pdoconnection.php line 50:
SQLSTATE[HY000] [1698] Access denied for user 'homestead'@'localhost'

In PDOConnection.php line 46:
SQLSTATE[HY000] [1698] Access denied for user 'homestead'@'localhost'

I did not modify the .env file in those sections so they are still using "homestead" so I know that where there username is coming from. 
I am just not sure how to correct it. 
Is this something you could help me with?
I did change the APP_KEY as you suggested. 

Thanks for your assistance!

**Comment by THExGOLDDEVIL** [comment]
Yes. I was able to figure that piece out. The database was actually never created so I had to continue to read through the documentation.

I have gotten to the point where I have access to the database, but the webpage is not working. I’ll eventually get it figured out!

Thanks for getting back to me!

**Comment by JC5** [comment]
That's OK! When you said you were a noob I had to guess what you knew and what you didn't know.

To debug blank or broken pages, checkout the log files in /storage/logs and the logs of your webserver, Apache or nginx.
