### ISSUE TITLE
bunq trigger for new transactions

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1482]
Shouldn’t be massively difficult to build.

**Comment by tbrasser** [comment]
Would this mean that firefly will import transactions as soon as they're made? That would be awesome! 

I use bunq and just got started with using firefly. Import works, and I can later import again which adds the new transactions fine. Only all the "duplicates" give a warning (but they're not duplicated in the end so this is fine for now)

**Comment by JC5** [comment]
Yep. The duplicates thing is something I’m working on for the next release :+1:

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
