### ISSUE TITLE
SQL Connection errors on install - Docker

### ISSUE THREAD

**Issue by hakubaspring** [firefly-iii/firefly-iii#1484]
Ubuntu 16.

This is the build command;

docker run -d \
-v firefly_iii_export:/var/www/firefly-iii/storage/export \
-v firefly_iii_upload:/var/www/firefly-iii/storage/upload \
-p 8093:80 \
-e FF_APP_ENV=local \
-e FF_APP_KEY=ybsZH3WhGq1****************j8MmJ9fm7hA \
-e FF_DB_HOST=192.xxx.x.140 \
-e FF_DB_NAME=firefly \
-e FF_DB_USER=firefly \
-e FF_DB_PASSWORD=[thepw] \
jc5x/firefly-iii:latest

The command 

_`- docker exec -it <container> php artisan migrate --seed`

returns connection refused errors. I have confirmed in MYSQL that the database name, user, password are correct.

In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
  chema.tables where table_schema = firefly and table_name = migrations)       
                                                                               

In PDOConnection.php line 50:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 46:
                                             
  SQLSTATE[HY000] [2002] Connection refused

**Comment by JC5** [comment]
Trick question: you're also using the correct IP address? I'm not sure if the docker image contains telnet, but you could try `telnet <ip> 3306`.

**Comment by hakubaspring** [comment]
When checking mysql config, I realised the bind was set to 127.0.0.1. So I removed container, restarted with 127.0.0.1 ff_db_host. No luck, same error. In MYSQL i can see firefly@127.0.0.1 and have granted privileges to firefly db. However;

`MYSERVER$  mysql -u firefly -p'password' -h 127.0.0.1`

Logs me in fine...

**Comment by JC5** [comment]
127.0.0.1 is an IP address that is strictly local. Both machines have IP 127.0.0.1. It makes sense that it works from the MySQL machine itself.

What does `ifconfig` tell you?

**Comment by hakubaspring** [comment]
Oh my word...I knew that...how did that not occur to me. First time using docker! Thanks

Okey. Commented bind address to remove it, added 192.x.x.140 to the docker command. Got this error

` SQLSTATE[HY000] [1130] Host '172.17.0.5' is not allowed to connect to this MySQL server  `

so I;

`GRANT ALL ON firefly TO firefly@172.170.0.5 IDENTIFIED BY 'passwordused'`

` flush privileges;`

But still not allowed to connect

**Comment by SimonHoenscheid** [comment]
You will not reach your local mysql DB on 127.0.0.1. Try a linked Mysql container:
https://severalnines.com/blog/mysql-docker-containers-understanding-basics

**Comment by hakubaspring** [comment]
Hi Simon, 

Thanks, but I eventually figured it out with some pointers.

**Comment by JC5** [comment]
:+1:

**Comment by casenjo** [comment]
@hakubaspring would you mind posting those pointers? I'm running into the same issue trying to connect to a local MySQL DB running on the docker host
