### ISSUE TITLE
Firefly hosted on Heroku redirects to Homepage when trying to access API Endpoints

### ISSUE THREAD

**Issue by SathyaBhat** [firefly-iii/firefly-iii#1486]
**Bug description**
I am running Firefly III version 4.7.4 

**Steps to reproduce**
1. Setup an instance on Heroku
2. Do the initial setup
3. Try access an API endpoint, ex: `http://<name>.herokuapp.com/api/v1/about`

**Extra info**
From the server logs it _looks_ like when trying to access the API, it redirects it to the login page & since I am already logged in, it does another  redirect to home page

```
2018-06-15T10:08:25.298044+00:00 app[web.1]: 10.10.156.201 - - [15/Jun/2018:10:08:25 +0000] "GET /api/v1/about HTTP/1.1" 302 416 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
2018-06-15T10:08:25.530362+00:00 app[web.1]: 10.127.19.214 - - [15/Jun/2018:10:08:25 +0000] "GET /login HTTP/1.1" 302 392 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
2018-06-15T10:08:25.299797+00:00 heroku[router]: at=info method=GET path="/api/v1/about" host=app-name.herokuapp.com request_id=641387b7-b956-4247-93be-3317d12859af fwd="119.82.122.232" dyno=web.1 connect=0ms service=13ms status=302 bytes=663 protocol=http
2018-06-15T10:08:25.894252+00:00 app[web.1]: 10.127.19.214 - - [15/Jun/2018:10:08:25 +0000] "GET / HTTP/1.1" 200 54388 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
2018-06-15T10:08:25.531106+00:00 heroku[router]: at=info method=GET path="/login" host=app-name.herokuapp.com request_id=80be91f2-9749-46f7-84f4-15cee4fd78d4 fwd="119.82.122.232" dyno=web.1 connect=1ms service=50ms status=302 bytes=1380 protocol=http
2018-06-15T10:08:25.894727+00:00 heroku[router]: at=info method=GET path="/" host=app-name.herokuapp.com request_id=32c3b8d3-710c-4623-a03a-5ac05491f31d fwd="119.82.122.232" dyno=web.1 connect=1ms service=181ms status=200 bytes=55964 protocol=http
```

**Bonus points**
Earn bonus points by:

Debug info: 

Debug information generated at 2018-06-15 10:14:04 UTC for Firefly III version **4.7.4**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.4 |
| FF API version | 0.3 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, errorlog |
| PHP version | 7.2.6 |
| Display errors | Off |
| Session start | 2018-06-01 00:00:00 |
| Session end | 2018-06-30 23:59:59 |
| Session first | 2018-05-30 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, mbstring, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.1.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.23, laravel/passport@v5.0.3, laravelcollective/html@v5.6.9, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.12, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.1.0, symfony/css-selector@v4.1.0, symfony/debug@v4.1.0, symfony/event-dispatcher@v4.1.0, symfony/finder@v4.1.0, symfony/http-foundation@v4.1.0, symfony/http-kernel@v4.1.0, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.0, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.0, symfony/translation@v4.1.0, symfony/var-dumper@v4.1.0, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.2,  |

**Comment by JC5** [comment]
Are you trying to access the end points with a valid OAuth2 token?

**Comment by SathyaBhat** [comment]
@JC5 Hm, no, I don't have a oAuth2 token, but I'm not sure how to get the token? `http://<name>.herokuapp.com/api/v1/oauth/authorize` returns a 404, `http://<name>.herokuapp.com/oauth/authorize` returns a 500 and the API authorisation documentation doesn't explain more https://firefly-iii.readthedocs.io/en/latest/api/start.html

**Comment by JC5** [comment]
To access the API you need a token. To get a token, you need to create a client ID + secret in your profile (`/profile`). I'll expand the docs to explain this. 

Once you have a client ID (and secret) you can use for example Postman to get an access token from `oauth/authorize`. Then Postman can use the returned access token to access `/api/v1/about`.

**Comment by SathyaBhat** [comment]
Thank you, I have created the client ID & token but it was not clear how to get the access token via `oauth/authorize` - would help if there was a swagger doc or just more info on what parameters/headers are required
