### ISSUE TITLE
Current balance and net worth not correct

### ISSUE THREAD

**Issue by philthynz** [firefly-iii/firefly-iii#1488]
I am running Firefly III version 4.7.4

**Description of my issue:**
I can't seem to get the actual account balance to reflect what i currently have. I have only 1 default account under assets, i have set the current amount and the date as of today (the account balance is accurate to whats in the checking account as of today). The current balance does not show correctly after running a csv import of the transactions from 01.01.2018 - 17.06.2018. It is off by around 150 EUR.

Shouldn't the current balance and net worth be showing what I currently say in opening balance?

**Steps to reproduce** 

Create a default account, add the opening balance and the date as 17.06.2018. Run a csv import of all transactions from 01.01.2018 - 17.06.2018.

**Comment by JC5** [comment]
First, I would suggest setting the opening balance to what it was on January 1st, but that should not matter much.

If the final balance is off I can only imagine that specific transactions haven't been imported, or have been imported badly somehow.

Did you run an "audit report" (see `/reports`) for a detailed view of the transactions in that account?

**Comment by philthynz** [comment]
Yea, so setting the opening balance from the day the first transaction is worked. Imports are from 1st Jan 2018, so that should be the balance to go off.

Thanks for the tip, i'm still getting my head around my finances, never did any money management before. Firefly is helping me so much 😁
