### ISSUE TITLE
Badge's in mobile view or when zoomed in

### ISSUE THREAD

**Issue by philthynz** [firefly-iii/firefly-iii#1489]
**Description**
I use firefly on my mobile, just in chrome. One of the most handy features on the dashboard is the badges. Like Balance, Bills to pay, Left to spend and Net worth. But they do not show. Probably because the page is zoomed in when viewing on a mobile. It's the same behavior if you zoom in on any web browser, the badges disappear.

**Solution**
It would be nice if they adjusted their size to fit for a mobile device, or just collapsed under each other.

**Comment by JC5** [comment]
Yes, that is the choice I had to make when I made the mobile view. There's not a nice way to format them.

**Comment by philthynz** [comment]
Is there another way to see the badges in the mobile view? It's such a handy thing to have those in front of your face when your out and about.

**Comment by JC5** [comment]
Not yet, I'm afraid. I'm thinking about a nice way to show that information.
