### ISSUE TITLE
Odd Import Date Formatting

### ISSUE THREAD

**Issue by Vanguard4893** [firefly-iii/firefly-iii#1490]
I am running Firefly III version 4.7.4

**Description of my issue:**
I am having some trouble getting dates in my bank's CSV files to be recognised properly, as there are extra characters embedded within the date column.

The dates are formatted as follows:
`2018-06-16T12:00:03Z`

My date format is entered as Y-m-d H:i:s, but the dates aren't being detected correctly, all transactions are defaulting to the date of the import.

The overall format of the CSV export from my bank is:
`id,created,amount,currency,local_amount,local_currency,category,emoji,description,address,notes,receipt
tx_00009XhVjq1wCNAg31xxBJ,2018-06-16T12:00:03Z,00.00,GBP,00.00,GBP,<CATEGORY>,,<DESCRIPTION>,,<NOTES>,`

Thanks in advance

**Comment by JC5** [comment]
Try the following:

`Y-m-d\TH:i:s\Z`

Since the letters are to be ignored, they should be included with a backslash. I must warn you, you're the first that needs this so I am not sure if it'll work.

**Comment by Vanguard4893** [comment]
I did wonder if they could be escaped like that, I will give it a go on an import & let you know what happens

**Comment by Vanguard4893** [comment]
That worked great, Firefly now gets the dates correct on import, thanks for the help!
