### ISSUE TITLE
Firefly 4.7.4 Spectre import Fatal error

### ISSUE THREAD

**Issue by philthynz** [firefly-iii/firefly-iii#1492]
I am running Firefly III version 4.7.4

**Description of my issue:**

After signing up for a Spectre account and upgrading it to a Test account, then adding the app and secret key the import fails.

Portal error:
![image](https://user-images.githubusercontent.com/17504095/41557367-b5d520be-733d-11e8-8131-4ffa9d20651a.png)

Email logs show:
```
Hi there,

Firefly III v4.7.4 ran into an error: Return value of FireflyIII\Services\Spectre\Request\NewCustomerRequest::getCustomer() must be an instance of FireflyIII\Services\Spectre\Object\Customer, null returned

The error was of type "Symfony\Component\Debug\Exception\FatalThrowableError".

The error occured on/at: Mon, 18 Jun 2018 19:02:04 +0000.

This error occured in file /opt/firefly-iii/app/Services/Spectre/Request/NewCustomerRequest.php on line 56 with code 0.
```

I would expect I would be taken to Spectre to create a bank connection. However I can't get past the error.

**Steps to reproduce**

 - Sign up for Spectre and upgrade to Test account
 - Create the Service keys in Specture for API v4 and add the public key from Firefly
 - Add the App ID and Secret from Spectre to Firefly
 - Start an import

**Comment by nlseven** [comment]
I am experiencing the same issue – this can be reproduced immediately on a fresh install of 4.7.4. I have not tested other Firefly versions, but have tried both PHP 7.1 and 7.2 in different browsers.
Happy to collect any additional data that would help finding the root cause.

Error:
```
[2018-06-19 12:43:41] local.ERROR: Exception is: {"class":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","errorMessage":"Return value of FireflyIII\\Services\\Spectre\\Request\\NewCustomerRequest::getCustomer() must be an instance of FireflyIII\\Services\\Spectre\\Object\\Customer, null returned","time":"Tue, 19 Jun 2018 12:43:41 +1000","file":"\/var\/www\/vhosts\/fireflyiii\/app\/Services\/Spectre\/Request\/NewCustomerRequest.php","line":56,"code":0,"version":"4.7.4","url":"https:\/\/firefly_address\/import\/job\/start\/gc7WQl12BrfA","userAgent":"Mozilla\/5.0 (Windows NT 6.1) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/53.0.2785.143 Safari\/537.36","json":true}  
[2018-06-19 12:43:42] local.ERROR: Return value of FireflyIII\Services\Spectre\Request\NewCustomerRequest::getCustomer() must be an instance of FireflyIII\Services\Spectre\Object\Customer, null returned {"userId":1,"email":"email@addre.ss","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of FireflyIII\\Services\\Spectre\\Request\\NewCustomerRequest::getCustomer() must be an instance of FireflyIII\\Services\\Spectre\\Object\\Customer, null returned at /var/www/vhosts/fireflyiii/app/Services/Spectre/Request/NewCustomerRequest.php:56)
```

Debug info:
```
Debug information generated at 2018-06-19 12:40:13 Australia/Brisbane for Firefly III version **4.7.4**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.4 |
| FF API version | 0.3 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.18 |
| Display errors | Off |
| Session start | 2018-06-01 00:00:00 |
| Session end | 2018-06-30 23:59:59 |
| Session first | 2018-06-18 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | 'en_US' |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, imagick |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.1.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.23, laravel/passport@v5.0.3, laravelcollective/html@v5.6.9, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.12, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.1.0, symfony/css-selector@v4.1.0, symfony/debug@v4.1.0, symfony/event-dispatcher@v4.1.0, symfony/finder@v4.1.0, symfony/http-foundation@v4.1.0, symfony/http-kernel@v4.1.0, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.0, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.0, symfony/translation@v4.1.0, symfony/var-dumper@v4.1.0, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.2,  |
```

**Comment by JC5** [comment]
Thanks for the debug info guys, I'll check it out.

**Comment by brusapa** [comment]
Same problem here while reproducing the steps in a docker image through the following docker-compose:

`version: '3'
services:
  firefly_iii:
    container_name: firefly_iii
    environment:
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly_db
      - FF_DB_USER=firefly_db
      - FF_DB_PASSWORD=DELETEDFORGITHUB
      - FF_APP_KEY=DELETEDFORGITHUB
      - FF_APP_ENV=local
      - TZ=DELETEDFORGITHUB/DELETEDFORGITHUB
      - VIRTUAL_HOST=DELETEDFORGITHUB
      - LETSENCRYPT_HOST=DELETEDFORGITHUB
      - LETSENCRYPT_EMAIL=DELETEDFORGITHUB
      - APP_URL=DELETEDFORGITHUB
      - TRUSTED_PROXIES=**
    depends_on:
      - firefly_iii_db
    expose:
      - 80
    image: jc5x/firefly-iii
    restart: always
    volumes:
      - DELETEDFORGITHUB:/var/www/firefly-iii/storage/export
      - DELETEDFORGITHUB:/var/www/firefly-iii/storage/upload

  firefly_iii_db:
    container_name: firefly_iii_db
    environment:
      - MYSQL_DATABASE=firefly_db
      - MYSQL_USER=firefly_db
      - MYSQL_PASSWORD=DELETEDFORGITHUB
      - MYSQL_ROOT_PASSWORD=DELETEDFORGITHUB
    image: mariadb
    restart: always
    volumes:
      - DELETEDFORGITHUB:/var/lib/mysql

networks:
  default:
    external:
      name: proxynet`

Error:

`local.ERROR: Return value of FireflyIII\Services\Spectre\Request\NewCustomerRequest::getCustomer() must be an instance of FireflyIII\Services\Spectre\Object\Customer, null returned {"userId":1,"email":"DELETEDFORGITHUB","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of FireflyIII\\Services\\Spectre\\Request\\NewCustomerRequest::getCustomer() must be an instance of FireflyIII\\Services\\Spectre\\Object\\Customer, null returned at /var/www/firefly-iii/app/Services/Spectre/Request/NewCustomerRequest.php:56)`

[Complete stacktrace](https://pastebin.com/wCTYmPNT)

I'm quite new with docker and I don't have much idea of what I'm doing, but I would be glad to help in anything I can

**Comment by JC5** [comment]
I've found the problem. It is an easy fix if you can access the source code (in your Docker repository). If you follow the reference to my push you can see that it is one easy change.

This will be automatically included in 4.7.5 (end of the month).

**Comment by brusapa** [comment]
It seems to work now with the change, I'm not able to confirm that the whole importing process is working due to spectre having some trouble with my bank...

Thanks for the quick fix!

**Comment by philthynz** [comment]
Confirmed working. Thanks for the speedy fix!
