### ISSUE TITLE
Change url?

### ISSUE THREAD

**Issue by anmol26s** [firefly-iii/firefly-iii#1495]
Hi 
YunoHost have option to change the url. But I don't know what changes are needed in Firefly III to make this happen. Is it possible to change the url of the Firefly III once installed ? If yes, please tell me the changes which needs to be done.

**Comment by JC5** [comment]
Yes, you can freely change the URL of Firefly III once it's installed.

**Comment by anmol26s** [comment]
I just need to change the nginx configuration ? No change in .core app ?

**Comment by JC5** [comment]
No changes necessary, to my knowledge.
