### ISSUE TITLE
Spectre imports - Auto and rules

### ISSUE THREAD

**Issue by philthynz** [firefly-iii/firefly-iii#1496]
I am running Firefly III version 4.7.4

Just some questions regarding Spectre imports... 

1. Is it possible to run auto imports from Spectre? I can only see a manual way to do it from the interface. I guess with a cron and cli it might be possible.

2. Can we run rules on Spectre imports? I currently use it to filter and organize the data. Wouldn't be very handy if I had to run them with each import.

**Comment by JC5** [comment]
1. See #1462 and and #1494 
2. I'll make sure this is the case in 4.7.5. It is on my list, but it doesn't have an issue.

**Comment by philthynz** [comment]
Nice! I look forward to the new release then :)
