### ISSUE TITLE
import is trying to create empty currencies

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#1498]
**Bug description**

I am running Firefly III version 4.7.4

Hi, 
I'm trying to import my transactions in firefly but the import crashed with a internal server error. After looking in to the logs it looks like the program is trying to create new but empty currencies. 

I guess the import routine should fallback to the default currency, if the imported transaction has not any currency information?

I have included some of the logging. 

2018-06-21 22:43:31] local.DEBUG: Now in CurrencyMapper::map()  
[2018-06-21 22:43:31] local.DEBUG: Array does not contain a value for code. Continue  
[2018-06-21 22:43:31] local.DEBUG: Array does not contain a value for symbol. Continue  
[2018-06-21 22:43:31] local.DEBUG: Array does not contain a value for name. Continue  
[2018-06-21 22:43:31] local.ERROR: Could not create new currency: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (SQL: insert into `transaction_currencies` (`name`, `code`, `symbol`, `decimal_places`, `updated_at`, `created_at`) values (, , , 2, 2018-06-21 22:43:31, 2018-06-21 22:43:31))  

**Steps to reproduce**

Import a csv without currency information.
 

**Extra info**
Debug information generated at 2018-06-21 22:44:39 Europe/Amsterdam for Firefly III version **4.7.4**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.4 |
| FF API version | 0.3 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, daily |
| PHP version | 7.1.8 |
| Display errors | Off |
| Session start | 2014-12-31 00:00:00 |
| Session end | 2018-06-21 00:00:00 |
| Session first | 2014-12-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | 'en_US' |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | 'unknown' |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, igbinary, redis, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.1.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.23, laravel/passport@v5.0.3, laravelcollective/html@v5.6.9, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.12, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.1.0, symfony/css-selector@v4.1.0, symfony/debug@v4.1.0, symfony/event-dispatcher@v4.1.0, symfony/finder@v4.1.0, symfony/http-foundation@v4.1.0, symfony/http-kernel@v4.1.0, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.0, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.0, symfony/translation@v4.1.0, symfony/var-dumper@v4.1.0, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.2,  |

**Bonus points**
Earn bonus points by:

- Post a stacktrace from your log files
- Add a screenshot

**Comment by JC5** [comment]
I know it happens, but it shouldn't be a problem. The system does a fallback to your default currency. In the next release the error will be gone.

Do you have other log files, besides this crash? Because this is probably not the cause of the problem.

**Comment by leander091** [comment]
Yes i do, It looks like i need to increase the max_allowed_packet size in the mysql-server. 
[2018-06-21 22:44:27] local.ERROR: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes (SQL: update `import_jobs` set `status` = error, `transactions`

**Comment by JC5** [comment]
That would be very nice, thanks. The provider_finished routine means that the CSV file has been imported. The user layout should push the next stage.

**Comment by leander091** [comment]
After doing some digging and importing some different types of transactions without any problems. I saw the following javascript error in the console of Firefox.  The import has been finished according to the logs on  the webserver but somehow the JavaScript does not know that. 
![ff](https://user-images.githubusercontent.com/5831104/42234001-53ad4fb2-7ef3-11e8-868a-a31e559b14e1.png)

**Comment by JC5** [comment]
Alright sorry for the late reply. Is this still going on, assuming you've upgraded to 4.7.5?

**Comment by leander091** [comment]
I could reproduce this in 4.7.5. I have not upgraded yet to 4.7.5.1.  I have done some further testing and i could successful import the file on the cli.

**Comment by JC5** [comment]
Alright. The reason I ask is that in itself it's not a problem. "Running" doesn't require the code to do much. I will make sure it does not display as an error any more (confusing).

It's probable that the original error, related to `max_allowed_packet` might still be the culprit.

**Comment by leander091** [comment]
That is a possible indeed.
I have changed various parameters to control execution time and maximal upload size to the following values  on my system:
Mariadb
```
max_allowed_packet=100M
```
Nginx
```
fastcgi_read_timeout 90
keepalive_timeout   65;

```

php-fpm
`none`

php.ini
```
max_execution_time = 30
max_input_time = 60
upload_max_filesize = 2M
max_file_uploads = 20
default_socket_timeout = 60
```

**Comment by JC5** [comment]
I can see how large imports would generate large queries. I'll think about a solution to prevent this from happening in the future. That should speed up both the web interface and the command line interface.
