### ISSUE TITLE
Android app? React or anything like that? 

### ISSUE THREAD

**Issue by TobiasDev** [firefly-iii/firefly-iii#1502]
Hello! 
Is there any chance we could see an Android app for this? I know you can log in on the website through mobile, but adding transactions on the go through the browser is not really working. If you accidentally clean the cache or close Firefox you need to login again, etc. I would love to have it as an app where I can save everything easier and use this! :+1: 
Great work with the Interface! Looks amazing and easy to understand.

**Comment by JC5** [comment]
There’s a public android in the Play Store. It’s very much in beta and not developed by me. 

https://play.google.com/store/apps/details?id=com.zerobyte.firefly

Feel free to contribute to it!

**Comment by TobiasDev** [comment]
Ah, cool. :D Thanks for the info. 

And I wonder if that is why someone else also asked about OAuth through Sandstorm since that would be needed. :) 

I know Tiny Tiny RSS can create OAuth links on Sandstorm to connect to mobile. I wonder how that is done... 

Once again, thanks for the info and keep up the good work!

**Comment by JC5** [comment]
You're welcome! And yes, I think that might be it. Something for the next version :)

**Comment by TobiasDev** [comment]
Awesome! I got another question.
Is it possible to remove that a _Description_ has to be added but instead have that you have to pick a category?

**Comment by JC5** [comment]
It isn't, no. The app developer will have to push a default value.

**Comment by Findus23** [comment]
This app just appeared on F-Droid:
https://f-droid.org/en/packages/xyz.hisname.fireflyiii/
https://github.com/emansih/FireflyMobile

**Comment by misternils** [comment]
was OAuth ever implemented  in firefly-iii for sandstorm like talked about above?

**Comment by daraul** [comment]
I would never get either of the apps mentioned above to log in to my instance on heroku. I think it's a problem with the redirect

**Comment by JC5** [comment]
It's not implemented yet. Sandstorm requires a different implementation. It's on the roadmap though. For Heroku, it shouldn't be a problem but their non-persistent storage can break things.

**Comment by daraul** [comment]
I thought the issue might be something like that. How do you even get passport's private key to stay on heroku at all?
