### ISSUE TITLE
TOTP: show the key and not only the QR code

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1503]
Today I was messing with the settings of Firefly III and I was glad that it does support 2FA. 

I have one suggestion: it is possible to show the key too and not only the QR code? Otherwise it is not possible to set the TOTP on password managers such as KeepassXC.

In the end I managed to do it thanks to Enpass (it shows the key in the settings) but doing it without jumping through some hoops would be a glad welcome.

**Comment by JC5** [comment]
Good idea, will do!

**Comment by JC5** [comment]
![screen shot 2018-06-23 at 17 54 18](https://user-images.githubusercontent.com/5889984/41811361-8413f864-770e-11e8-9165-b894518c2e98.png)

I'm pretty sure this is what you were looking for, right? I haven't checked if it works yet but I'm fairly sure that if you enter this code, you can access my local development environment :wink:

**Comment by lucavallerini** [comment]
Exactly that, thank you! :)
