### ISSUE TITLE
Split transactions: destination account ignored the first time and categories not cleared when a split is removed

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1509]
I'm on the latest version and this behavior is replicable on the demo site too.

Step to replicate the issues:
1. Create a new withdrawal
2. Check the split transaction checkbox
3. Add some splits: compile them with a destination account and with different categories.
4. Save the transaction

Now, if you go to the transaction overview you can see that the destination account was not saved and each split defaulted to (cash). The only way to save the destination account is to edit the transaction.

Now, remove a split and note the category of that split. After you save the transaction, in the overview of the transaction the categories listed comprise the category of the split removed: if it was the only split with that category that category shouldn't be listed.

Same problem with deposits.

**Comment by JC5** [comment]
That's not supposed to happen! Thanks for reporting this, I'll look into it.

**Comment by JC5** [comment]
I've pushed a fix to the demo site. Could you clear your browser cache and check it out?

**Comment by lucavallerini** [comment]
Everything works correctly now!

**Comment by JC5** [comment]
Also fixed on the demo site! :+1:

**Comment by lucavallerini** [comment]
Amazing!
