### ISSUE TITLE
after last update Imported transaction cause Twig exception on formatting date

### ISSUE THREAD

**Issue by fco64** [firefly-iii/firefly-iii#1510]
Imported transaction since 4.7.4 cause a Twig exception like this:
 (2/2) Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("DateTime::__construct(): Failed to parse time string (29/05/2018) at position 0 (2): Unexpected character") in "/HTTPdevel/web_mmanager_firefly/resources/views/transactions/show.twig" at line 208.

Datas was imported from CSV, date was in Italin format d/m/Y, this is import config:

{
    "stage": "ready",
    "has-headers": true,
    "date-format": "d\/m\/Y",
    "delimiter": "tab",
    "import-account": 1,
    "specifics": [],
    "column-count": 6,
    "column-roles": [
        "date-transaction",
        "date-process",
        "amount_credit",
        "amount_debit",
        "description",
        "note"
    ],
    "column-do-mapping": [
        true,
        true,
        true,
        true,
        true,
        true
    ],
    "column-mapping-config": [],
    "file-type": "csv",
    "has-config-file": true,
    "apply-rules": true,
    "match-bills": false,
    "auto-start": false,
    "column-roles-complete": false,
    "column-mapping-complete": false,
    "initial-config-complete": false,
    "has-file-upload": false
}

Trying some stuff on twig code I discover that the probem is about field "process_date", so, I found that in the table journal_meta the field "data" for last imported datas is in a wrong format

process_date	"21\/06\/2018"    //this is Italian style ( since 4.7.4 )
process_date	"2018-05-06T00:00:00+00:00"   // this is the correct form ( previous version )

Actually, I solved exporting SQL and reimport after manual regex correction but obviously is not an elegant method.

Thanks
Ciao
Franco

**Comment by JC5** [comment]
Nice find!

I've added a fix for the next release that will store the dates as "2018-05-06". Those can be parsed without any issue.

Thanks for letting me know!

**Comment by fco64** [comment]
Great, thanks to You.
