### ISSUE TITLE
[question] import bank statements

### ISSUE THREAD

**Issue by cusco** [firefly-iii/firefly-iii#1511]
Hello,

I'm a new user to firefly3 and to accounting in general.

I only have one bank account, my bank sends me monthly statements to my e-mail in pdf.

Is there such feature that one could import the statement to firefly?

**Comment by JC5** [comment]
I'm sorry but Firefly III cannot import PDF files. Does your bank have the option to send you CSV files?

**Comment by cusco** [comment]
It does not. I wish

**Comment by JC5** [comment]
Then I cannot help you I'm afraid.
