### ISSUE TITLE
Tags adds to field when scroll list, not at ENTER keystroke

### ISSUE THREAD

**Issue by victordariovera** [firefly-iii/firefly-iii#1519]
**Bug description**
I am running Firefly III version 4.7.4

When I want to add Tags to a transaction and type the first letters a list of coincidences appears. When I scroll into that list each tag on focus add to the field. I think that the correct way to add tags from coincidence list would be pressing ENTER to confirm the desired tag.

**Steps to reproduce**
When you try to select a tag from coincidence list. Here a video of it https://youtu.be/FwAraaeeh5E

**Comment by JC5** [comment]
Thanks for reporting! It is a known issue. The library I'm using at the moment is quite old and needs replacing. it's on the list!

**Comment by JC5** [comment]
This will be fixed in the next release :+1:

**Comment by JC5** [comment]
Closed pending the next release this weekend.
