### ISSUE TITLE
Empty 'Native amount' field causes an 'unrecoverable error' losing any contents of the filled in unsaved transaction

### ISSUE THREAD

**Issue by ajh0912** [firefly-iii/firefly-iii#1521]
**Bug description**
I am running Firefly III version 4.7.4

Empty 'Native amount' field causes an 'unrecoverable error' losing any contents of the filled in unsaved transaction

**Steps to reproduce**
Create a new transaction
Change the transaction currency to a non native currency of the specified asset account
Submit the form while the 'Native amount' field is blank
![chrome_2018-07-01_22-32-58](https://user-images.githubusercontent.com/40744246/42139233-c02b969e-7d81-11e8-8007-7e89299f1b37.png)
![chrome_2018-07-01_22-18-32](https://user-images.githubusercontent.com/40744246/42139234-cc3d86e0-7d81-11e8-8248-5d032762f5b7.png)

**Suggested Fix**
Use input validation on the form, highlighting the empty field and disabling submitting the form until it is populated.
Suggested improvement: Automatically calculate the 'native amount' based on current exchange rates, as both currencies are known, as well as the non-native amount [I realise this is actually the documented behavior already on [this page](https://firefly-iii.readthedocs.io/en/latest/concepts/currencies.html#creating-transactions) but it doesn't seem to work for me]

**Extra info**
Server: Ubuntu 16.04 with nginx
Client: Windows 10

**Comment by JC5** [comment]
Nice, thanks for reporting. I ran into this issue earlier but I couldn't find the offending field. I will make sure that the form will handle this well in the next release.

As for the currency exchange: if you enter an API key in your settings it should work as described. If you need currency exchange rates that aren't between EUR and something else, you'll have to get a paid Fixer.io subscription.

**Comment by JC5** [comment]
OK, I've pushed some changes that are live on the demo site. Could you verify?

**Comment by JC5** [comment]
OK, I've pushed some changes that are live on the demo site. Could you verify?

**Comment by ajh0912** [comment]
Looks like the error no longer happens, and there's a red text warning about the field must be a number. Maybe make it a bit more intuitive, rather than referencing 'native_amount'. But I'm sure that'll come in due course, along with translations etc. Thanks, it's a good improvement as you won't lose progress anymore

**Comment by JC5** [comment]
Yep, fixed!
