### ISSUE TITLE
500 internal server error after install

### ISSUE THREAD

**Issue by latepaul** [firefly-iii/firefly-iii#1525]
I am trying to install Firefly III version 4.7.4 on my hosted web space. That means I have access to the command line but not root. 

Anyway I went through the install process, manually installing composer and it all seemed to work ok. I set up the database (MySQL 5.5.6). I did get the error about max key length but it looks like that's a known issue and not a showstopper?

So now if I navigate to the sub domain I've assigned for it I get a 500 Internal Server Error. 

storage/logs is writeable by the web user but I don't get any errors there. There's an "ff3-cli-2018-07-02.log" but that seems to have come from the database setup at the command line.

> Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

> Please contact the server administrator at to inform them of the time this error occurred, and the  actions you performed just before this error.

> More information about this error may be available in the server error log.

> Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

I've looked through some old issues but it seems like not even writing a log file is unusual. Just getting a bit more information about the failure would be useful.

**Comment by JC5** [comment]
Since the error document also fails I suspect you need to check out the Apache error logs to see what is going on. Try /var/log/apache2/error.log and check if it reports anything useful.

**Comment by latepaul** [comment]
I can't see /var/log/apache2. It may exist but I don't see it - I think my view of the world is limited, might be a VPS I'm not sure. 

There's a logs directory in my home directory where they put some server logs including the access.log but the last update on that doesn't match when I tried to use the firefly page. 

I'll see if I can get more information from the hosting web interface.
