### ISSUE TITLE
What's an inactive budget?

### ISSUE THREAD

**Issue by alex6480** [firefly-iii/firefly-iii#1526]
Hi

I attempted to create a budget. I then renamed it immediately afterwards.
Now the budget is inactive:

![image](https://user-images.githubusercontent.com/8026279/42175130-ceb7c284-7e24-11e8-8522-4ee810ffae6a.png)

I can't figure out how to add transactions to it and I can't delete it.
What is going on? When does a budget become inactive and what does it mean?

**Comment by JC5** [comment]
Which version of Firefly III are you running?

**Comment by alex6480** [comment]
Version 4.7.4

**Comment by alex6480** [comment]
I think I know why it got disabled. When I renamed it, the "enabled" checkbox was off by default. I think this should be set to whatever the budget currently is.

I also think it should be able to modify/reenable disabled budgets, but I may just be overlooking how to do that.

**Comment by JC5** [comment]
You may have discovered a bug! Edit the budget and make sure to check the “active” checkbox. That should fix it.

**Comment by alex6480** [comment]
How do I edit it? I don't see any button anywhere.
I can edit it by navigating to the URL manually, but I think it would be more usable if there were edit/delete links on disabled budgets just like the active ones.

**Comment by JC5** [comment]
You can go to the page of the budget itself, there's an ellipsis menu.

**Comment by alex6480** [comment]
Alright. I finally found it.
I'll close the question.

However, I think there's some room for improvement in this process.
1. When editing budgets, the default state should be the current state.
2. It should be possible to edit inactive budgets from the overview like the active ones
3. The ellipsis button is very small and easy to miss. Perhaps it could be made more clear?

**Comment by JC5** [comment]
1. Yes, that is the bug you found :grin:
2. I'll see if there's room!
3. Yep, agreed. Many other views already have dedicated buttons.

Thanks for the feedback!
