### ISSUE TITLE
Make split transactions more clear

### ISSUE THREAD

**Issue by alex6480** [firefly-iii/firefly-iii#1528]
Hi again

I think the way the split transactions are displayed is a bit confusing. It's not easy to see which transactions are connected, especially when you have multiple split transactions.

![image](https://user-images.githubusercontent.com/8026279/42209680-8ec9416c-7eaf-11e8-9b67-d956f4e11b89.png)

I instead suggest that the grouping is displayed in the table. I've made a quick mockup of a way to do this.
I think the font size gets a bit small in the split rows, but I think it helps a lot to differentiate them from complete transactions.
This layout could also easily be made collapsible.
Since the buttons point to the main transaction I would perhaps remove those from the child transactions as well. I think a user could reasonably expect that clicking delete on a split transaction would only delete that part of the split and not the entire transaction like it does at the moment. Removing them from the splits would prevent this confusion.

![image](https://user-images.githubusercontent.com/8026279/42209745-b7ed9d90-7eaf-11e8-9ef3-11c80c4885ba.png)

What do you think?
I'm up for the task of implementing this myself and making a pull request if you agree with the changes.

**Comment by JC5** [comment]
That looks just fine! Feel free to submit something, but remember to use the develop branch :+1:

**Comment by xXSTrikeXx** [comment]
Maybe it can be clear with adding the tags? Atm it´s only the category. So the tags can also be used as Sub categories.

**Comment by JC5** [comment]
Will be part of https://github.com/firefly-iii/firefly-iii/projects/5#card-19937456
