### ISSUE TITLE
Bills only taking first match of rule for paid total

### ISSUE THREAD

**Issue by Narsat** [firefly-iii/firefly-iii#1530]
**Bug description**
I am running Firefly III version 4.7.4

Split transactions do not seem to be summed up correctly when in bills (Only first match is counted)

![image](https://user-images.githubusercontent.com/616363/42225906-3d00e2a6-7ea3-11e8-9bb2-079711ecace2.png)

**Steps to reproduce**
1. Create a bill and matching rule
2. Create a transaction that matches that rule
3. Split the transaction
4. Only the first hit of the rule is counted.

Running the rule against transactions again does not seem to yield different results.

_I might be missing something, but couldn't find another issue regarding this, so I'd thought I'd report._

Thanks!

**PD After I finished drafting this up, I noticed only the graph took the first value, it seems to be correctly counted here:**
![image](https://user-images.githubusercontent.com/616363/42226511-c0e0ad6c-7ea4-11e8-91a0-efb02f0b8b18.png)
_Also, while the bill is set for transactions from 8,200-10,000 this is not enforced by the rule, the rule has no lower/upper amount limit._

**Comment by JC5** [comment]
Hi!

I am not sure I can replicate the problem. When I split a transaction into multiple parts both parts are counted towards the bill.

I also see that you have linked transfers to a bill. Did you convert them afterwards?

It is true that the amount in the bill does not match the rule. In previous versions, these amounts would be used to match to the bill but this is no longer the case. I am not sure yet what I will do with these fields.

**Comment by Narsat** [comment]
Hey! Thanks for the quick reply!

I did try changing the bill amount to make sure that wasn't the cause, but didn't affect at all.

It also seems to happen with expenses to some extent.

In this particular case I converted these transactions that were previously expenses to transfers, then split them, as I'm trying to have better accountability of my mortgage payments, interests, etc. 

**1. Creating an expense:**
![image](https://user-images.githubusercontent.com/616363/42229404-09e7635a-7eac-11e8-9baf-3f2c1e9d1d4d.png)



**2. Splitting said expense:**
![image](https://user-images.githubusercontent.com/616363/42229589-6b780548-7eac-11e8-9d32-3e9b9476c6ad.png)


**Naturally created test transfer for August**
![image](https://user-images.githubusercontent.com/616363/42229195-82a6fa04-7eab-11e8-956d-de1bb341488c.png)


Overall it seems the graph has weird behavior. However, the correct amount is always displayed in the "Average bill amount".

**Comment by JC5** [comment]
I see. Only withdrawals should be linked to bills which is why the chart is buggy. The next version of Firefly III will correct this.

**Comment by Narsat** [comment]
Sounds good, Thanks!

**Comment by Narsat** [comment]
Update.

Because I can't really decide on how to actually manage my mortgage, I actually re-switched back to withdrawals, but kept the split transactions. Seems like I'm experiencing the same behavior on transfers and withdrawals in the sense that it only takes a single record for the chart.

![image](https://user-images.githubusercontent.com/616363/42245392-41349e7c-7ede-11e8-8927-00ff631a85f6.png)

**Comment by JC5** [comment]
Alright, I'll do some digging this week to see what is going wrong.

**Comment by JC5** [comment]
It's OK bot I'm on it!

**Comment by Narsat** [comment]
Silly bot! Thanks for all your hard work JC

**Comment by JC5** [comment]
I found the problem and fixed it. The result will be included in the next release.
