### ISSUE TITLE
Verify database routine reports incorrect that category has no transactions

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1531]
**Bug description**
I am running Firefly III version 4.7.5
During the upgrade of 4.7.4 to 4.7.5 I got the message that my category has no transactions:
User #1 (xx@xx.com) has category #15 ("Auto") which has no transactions.

But when I look to the web interface, this category has transactions linked.

**Steps to reproduce**
Update to v 4.7.5

**Extra info**
Debug information generated at 2018-07-04 18:16:53 UTC for Firefly III version **4.7.5**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.5 |
| FF API version | 0.4 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug,  |
| PHP version | 7.1.16-1+0\~20180405085551.16+jessie\~1.gbp4937aa |
| Display errors | Off |
| Session start | 2018-07-01 00:00:00 |
| Session end | 2018-07-31 23:59:59 |
| Session first | 2014-12-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | 'unknown' |
| Trusted proxies (.env) | * |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, psr/http-message@1.0.1, guzzlehttp/psr7@1.4.2, guzzlehttp/promises@v1.3.1, guzzlehttp/guzzle@6.3.3, bunq/sdk_php@dev-master, vlucas/phpdotenv@v2.5.0, symfony/css-selector@v4.1.1, tijsverkoyen/css-to-inline-styles@2.2.1, symfony/polyfill-php72@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/var-dumper@v4.1.1, symfony/routing@v4.1.1, symfony/process@v4.1.1, symfony/polyfill-ctype@v1.8.0, symfony/http-foundation@v4.1.1, symfony/event-dispatcher@v4.1.1, psr/log@1.0.2, symfony/debug@v4.1.1, symfony/http-kernel@v4.1.1, symfony/finder@v4.1.1, symfony/console@v4.1.1, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.4, swiftmailer/swiftmailer@v6.1.0, paragonie/random_compat@v2.0.15, ramsey/uuid@3.7.3, psr/simple-cache@1.0.1, psr/container@1.0.0, symfony/translation@v4.1.1, nesbot/carbon@1.25.0, monolog/monolog@1.23.0, league/flysystem@1.0.45, erusev/parsedown@1.7.1, dragonmantank/cron-expression@v2.2.0, doctrine/inflector@v1.3.0, laravel/framework@v5.6.26, davejamesmiller/laravel-breadcrumbs@5.1.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, fideloper/proxy@4.0.0, zendframework/zend-diactoros@1.8.0, symfony/psr-http-message-bridge@v1.0.2, phpseclib/phpseclib@2.0.11, league/event@2.1.2, lcobucci/jwt@3.2.2, defuse/php-encryption@v2.2.0, league/oauth2-server@6.1.1, firebase/php-jwt@v5.0.0, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, league/commonmark@0.17.5, league/csv@9.1.4, league/fractal@0.17.0, paragonie/constant_time_encoding@v2.2.2, symfony/polyfill-util@v1.8.0, symfony/polyfill-php56@v1.8.0, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, twig/twig@v1.35.3, rcrowe/twigbridge@v0.9.6,  |
It looks like the query is not correct, or my data has been corrupted somewhere.

**Comment by JC5** [comment]
The query is not correct, because the database model changed slightly. I will update the verification routine!
