### ISSUE TITLE
No named account and no category after csv import

### ISSUE THREAD

**Issue by Bubka** [firefly-iii/firefly-iii#1533]
Hi,

**Bug description**
I am running Firefly III version 4.7.5

Revenue accounts are set as `(no name)` and categories are never set when i import a csv file.

**Steps to reproduce**
Set a csv file with this content :
```
Date;Tags;Destination;Description;Catégorie;Sous-catégorie;Montant
04/01/2006;Dépôt de chèque;Bernard Simonet;Noel;Revenus;Noel - Anniv - Thunes;400
21/03/2006;Dépôt de chèque;Degueldre;remboursement depot de garantie;Habitation;Loyer;1025,86
06/04/2006;Dépôt de chèque;Christophe Dosreis;cheque ski;Loisirs;Snowboard;43
```

These records correspond to checks deposit in my "Compte courant LBP" asset account.

Import the csv using these options :
- Headers in csv
- ";" as separator
- Date format: `d/m/Y`
- Account to import: Compte courant LBP (see my screenshot bellow)
- No rules

Columns mapping as :
![bug_import_ffiii_02](https://user-images.githubusercontent.com/858858/42388026-7d50b9e6-8144-11e8-959b-3b2cfd17ab47.png)

where (for non french users) : 
- Compte d'actif = Asset Account
- Nom de catégorie = Category name
- Montant = Amount

After the import 3 records are created with no name account and without any category:
![bug_import_ffiii_01](https://user-images.githubusercontent.com/858858/42388167-f4e641d8-8144-11e8-9696-d7b39cdd351b.png)

FYI, it tried without any category/account set in firefly-iii and with provided category/account previously created, it makes no differences :(

**Extra info**
Debug information generated at 2018-07-06 18:05:38 Europe/Paris for Firefly III version **4.7.5**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.5 |
| FF API version | 0.4 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.17 |
| Display errors | Off |
| Session start | 2018-07-01 00:00:00 |
| Session end | 2018-07-31 23:59:59 |
| Session first | 2006-01-04 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | 'en_US' |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, imagick, session, intl, json, mbstring, mcrypt, memcached, standard, mysqlnd, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, Reflection, imap, SimpleXML, soap, sockets, mongodb, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, mysqli, cgi-fcgi, ionCube Loader, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.26, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.15, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.0, symfony/console@v4.1.1, symfony/css-selector@v4.1.1, symfony/debug@v4.1.1, symfony/event-dispatcher@v4.1.1, symfony/finder@v4.1.1, symfony/http-foundation@v4.1.1, symfony/http-kernel@v4.1.1, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.1, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.1, symfony/translation@v4.1.1, symfony/var-dumper@v4.1.1, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.5.0, zendframework/zend-diactoros@1.8.0,  |

New lines in my log file just after the import:
```
[2018-07-06 18:22:14] local.WARNING: Cannot find anything on empty currency code and empty currency ID!  
[2018-07-06 18:22:15] local.WARNING: Cannot find anything on empty currency code and empty currency ID!  
[2018-07-06 18:22:15] local.WARNING: Cannot find anything on empty currency code and empty currency ID!
```

For the record, i'm new to firefly so maybe my csv is malformed or i missed something.

**Comment by JC5** [comment]
It seems you have found a bug, congratulations! :wink:

I have created a fix that will go live with Firefly v4.7.5.1 next Friday. In the mean time, a solution is to create the categories yourself and map them by hand. Create them under `/categories`.

Select the checkbox next to "nom de catégorie" and match them by hand. That will have to be the solution until this fix is live.

I apologise for the inconvenience!

**Comment by JC5** [comment]
Glad to be of service! :+1:

No it should not. I have been cleaning up code and all the tests still work. I expect no problems. I expect you’ll have no difficulty reversing the change should problems occur.

**Comment by Bubka** [comment]
Ok, I edited my `ImportableConverter.php` file and test the import again, the category is correctly set in new records.

But the *From* account is still set as `(no name)` account. Is this the default behavior of the import routine ? I expected that firefly will create missing accounts (as revenue account in this case) and set them up in the imported records.
![firefly bug noname](https://user-images.githubusercontent.com/858858/42410651-5b746c92-81ed-11e8-9426-b37683e4aedd.png)

**Comment by JC5** [comment]
Try using "Compte destinataire (nom)" instead of "Compte d’actif (nom)".

I believe the first one translate to "destination account" or "recipient account" but the correct translation would be of "opposing account". And you need to link this to the opposing account.

"Opposing account" does not imply a direction for the amount, if you know what I mean. "Destination" and "recipient" imply that is where the money would go to, and that is why I believe you selected "Compte d’actif (nom)". Am I correct?

If you can help me with the correct translation of "opposing account" I will make this more clear in the next translation. I am not French myself so I must rely on the translations of other users.

**Comment by Bubka** [comment]
You're right, the translation misled me with the idea of a direction. the word "opposite" make more sense,  besides, it was displayed in v4.7.4 (the french term was missing i guess) and i now remember that i had imported some csv successfully by using it.

With this mapping the import feature creates records with their correct "From" account :+1: 

Regarding the translation of *Opposite account* i think the best one would be *Compte opposé* (so the literal translation from EN to FR), it covers any type of transaction without implying the idea of a direction for the amount, like in English.

**Comment by JC5** [comment]
I've updated the translation and it'll be included in the next release. :+1:
