### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by Ircghost** [firefly-iii/firefly-iii#1534]
Hi all,

I've been trying to update from 4.7.0 to the latest version on a self-hosted server using Ubuntu 18 (GUI version). I've had many issues during installation, although it's been working fine since, so my guess is that one my initial setup mistakes is now messing with the upgrade. 

I have been trying for days now to get the new update running, however I keep getting stuck at a screen saying: "Please wait...
An unknown error prevented Firefly III from executing the upgrade commands. Sorry."
My old version does still work (at localhost/firefly-iii-old/public). 

At this point I have tried so many different things, that I can't really easily fall back to where I started. Luckily I did back-up the .env, upload, export and full DB's folders. At least I hope I did it correctly ;).

I'm stuck at the command: php artisan migrate --env=production # Answer yes when asked. Which results in this error:
- In Connection.php line 664:
- SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'notes'; check that column/key  exists (SQL: alter table `attachments` drop `notes`)                                                
-                                                                                                       
- In PDOStatement.php line 143:
- SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'notes'; check that column/key exists                                                                                              
- 
- In PDOStatement.php line 141:
- SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'notes'; check that column/key exists 

When I check the table 'attachments' in the DB, the entire table is returned as empty, without columns.
What should I do to continue?

**Steps to reproduce** 
Follow upgrade procedure from https://firefly-iii.readthedocs.io/en/latest/installation/upgrading.html

**Bonus points**
![error](https://user-images.githubusercontent.com/36815609/42412357-536feff8-820b-11e8-9032-e4c94a5653fa.PNG)
[ff3-apache2handler-2018-07-07.log](https://github.com/firefly-iii/firefly-iii/files/2172867/ff3-apache2handler-2018-07-07.log)

Thank you guys!

**Comment by JC5** [comment]
It looks like the database migrations failed half-way. I am not sure what the original cause is but it's something we can work out. The best way to facilitate the upgrade is (unfortunately) doing it by hand. 

In the `configuration` table should be a `db_version` entry. If you set it to `4`, the upgrade routine will stop trying to upgrade. That is step 1.

Step 2 would be to create a new 4.7.5 database and compare your database to that one. I've attached a scheme that you could import as firefly_2 or something.

TO finalise the import you must the upgrade commands:

```
php artisan cache:clear
php artisan firefly:upgrade-database
php artisan firefly:verify
php artisan passport:install
```

Make sure you backup everything [as described in the documentation](https://firefly-iii.readthedocs.io/en/latest/installation/backup.html)!

**Comment by JC5** [comment]
And here is the attachment.

[firefly-iii_2018-07-07.sql.txt](https://github.com/firefly-iii/firefly-iii/files/2172894/firefly-iii_2018-07-07.sql.txt)

**Comment by Ircghost** [comment]
Hi James,

Thanks for your quick reply as always!

I executed the steps, however the same screens appears. I don't know what happens underwater but shouldn't I in the .env point to the new DB or so something else?

This is what I see after running the four last codes:
Amount integrity OK for user #1
No orphaned transactions!
No orphaned journals!
All link types OK!
All access tokens OK!
Amount integrity OK!
mark@mark-ubuntu17:/var/www/html/firefly-iii$ php artisan passport:install
Encryption keys already exist. Use the --force option to overwrite them.

In StreamHandler.php line 107: The stream or file "/var/www/html/firefly-iii/storage/logs/ff3-cli-2018-07-07.log" could not be opened: failed to open stream: Permissiondenied                                                        

mark@mark-ubuntu17:/var/www/html/firefly-iii$ sudo -u www-data php artisan passport:install
Encryption keys already exist. Use the --force option to overwrite them.

In StreamHandler.php line 107: The stream or file "/var/www/html/firefly-iii/storage/logs/ff3-cli-2018-07-07.log" could not be opened: failed to open stream: Permissiondenied                                                        
                                                                                                       
mark@mark-ubuntu17:/var/www/html/firefly-iii$ sudo php artisan passport:install
Encryption keys already exist. Use the --force option to overwrite them.
Personal access client created successfully.
Client ID: 3
Client Secret: o****
Password grant client created successfully.
Client ID: 4
Client Secret: R****
mark@mark-ubuntu17:/var/www/html/firefly-iii$ 

It also seems to create client ID's although I only have 1 user.

**Comment by Ircghost** [comment]
Yeah, makes sense now. I guess I was hoping I could import the data into the new DB schema ;). 

I actually don't mind if I need to correct the DB, I'm however worried that the same thing might happen when the next update comes. I'm actually considering just building a fresh new install and then rebuilding my rules and be done with it. However, I've yet to build a new instance. Everytime I build one I get caught in errors (and I have followed both https://firefly-iii.readthedocs.io/en/latest/installation/server.html#accessing-firefly-iii and https://gist.github.com/philthynz/ec04833a8e39c7f7d1b0d33cb4197a95to the letter. However, both manuals don't really mention the basics I need such as, under which user do you install it etc. Since I have a lot of permission errors.

**Comment by JC5** [comment]
To make sure that the migrations work next time, clear out the migrations table and submit the following data:

```
INSERT INTO `migrations` (`id`, `migration`, `batch`)
VALUES
	(1,'2016_06_16_000000_create_support_tables',1),
	(2,'2016_06_16_000001_create_users_table',1),
	(3,'2016_06_16_000002_create_main_tables',1),
	(4,'2016_08_25_091522_changes_for_3101',1),
	(5,'2016_09_12_121359_fix_nullables',1),
	(6,'2016_10_09_150037_expand_transactions_table',1),
	(7,'2016_10_22_075804_changes_for_v410',1),
	(8,'2016_11_24_210552_changes_for_v420',1),
	(9,'2016_12_22_150431_changes_for_v430',1),
	(10,'2016_12_28_203205_changes_for_v431',1),
	(11,'2017_04_13_163623_changes_for_v440',1),
	(12,'2017_06_02_105232_changes_for_v450',1),
	(13,'2017_08_20_062014_changes_for_v470',1),
	(14,'2017_11_04_170844_changes_for_v470a',1),
	(15,'2018_01_01_000001_create_oauth_auth_codes_table',1),
	(16,'2018_01_01_000002_create_oauth_access_tokens_table',1),
	(17,'2018_01_01_000003_create_oauth_refresh_tokens_table',1),
	(18,'2018_01_01_000004_create_oauth_clients_table',1),
	(19,'2018_01_01_000005_create_oauth_personal_access_clients_table',1),
	(20,'2018_03_19_141348_changes_for_v472',1),
	(21,'2018_04_07_210913_changes_for_v473',1),
	(22,'2018_04_29_174524_changes_for_v474',1),
	(23,'2018_06_08_200526_changes_for_v475',1);
```

That should make sure the migrations fire correctly next time!

As for access rights. I intentionally keep it out of the documentation because it a nightmare to maintain (documentation wise).

What I do myself is make a dir in /var/www and give it in full to `james:james`. That user is also a member of `www-data`. Then install, migrate, etc, and give it all back to `www-data:www-data`.

**Comment by Ircghost** [comment]
It's been a long and fun day but it worked! Also extracted the current DB (w/o data) and compared it with your extract through diffuse. Had to add a couple of tables, and re-run those commands and PRESTO!

I owe you a beer James ;)

**Comment by JC5** [comment]
Haha glad to hear it works! :+1:
