### ISSUE TITLE
Investment accounts

### ISSUE THREAD

**Issue by mrahmadt** [firefly-iii/firefly-iii#1536]
Hi

I'm not sure if this is possible or not, but I would like to get your feedback.

Let say I have investment accounts (stocks+funds...etc.), and the account value gets changed almost every hour, what is your suggestion to keep track of such action (if possible)? 

I'm not asking about real-time tracking but what kind of action should I do to maintain the balance similar to the actual account value from time to time?

**Comment by JC5** [comment]
Nothing you can do, really. Stock tracking is something you can build a whole new Firefly III around. It is not something that will feature in Firefly III, it's just too big.
