### ISSUE TITLE
[Bunq import] Changed api key and import doubles all transactions

### ISSUE THREAD

**Issue by Xeli** [firefly-iii/firefly-iii#1539]
**Bug description**
I am running Firefly III version 4.7.5

I test the bunq import a while ago (1 month ago?) And the import worked beatifully. Today I wanted to import again but I accidently removed the api so I had to readd it.

When I ran the import again with the new api key almost all my transactions in firefly have double by this import.

**Steps to reproduce**
I think renewing the API key and importing Bunq caused this but I am not sure.

**Extra info**
Running Firefly via docker-compose

If I can add or debug anything I'd be glad to help but I am not sure what or how I can help

**Comment by JC5** [comment]
It depends a bit on which version you were when you imported the first time.

In Firefly III v4.7.4, I changed the import routine to be able to detect duplicates no matter the source. This also meant that "old" imports would no longer be detected as being a duplicate compared to "new" ones. I believe this is the case here.

However, there's an easy check. Simply renew your API key again and see what happens. It should not import any duplicated transactions.
