### ISSUE TITLE
The cron daemon is not started in the Dockerfile

### ISSUE THREAD

**Issue by chrif** [firefly-iii/firefly-iii#1540]
**Bug description**
I am running Firefly III version 4.7.5

This is not a bug I personally experienced. I was looking at adding a custom cron job and I noticed that a cron daemon is tentatively started in the Dockerfile with `CMD cron`. If you run `top` you won't see your cron daemon running. Here is why:
https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact

Only one process per docker container can be started, unless you use a process manager like supervisor:
https://docs.docker.com/config/containers/multi-service_container/

If you don't want to set up supervisor yourself, there are images by third parties that take care of setting up complex containers with multiple processes. Here is a sophisticated one from a third party we rely upon at work:
https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-apache.html

**Comment by JC5** [comment]
Mmm, thanks for the hint. I’ll do some research.

**Comment by JC5** [comment]
New release is live. The new Docker file should have a working cron job.
