### ISSUE TITLE
composer.lock should not be ignored in .dockerignore

### ISSUE THREAD

**Issue by chrif** [firefly-iii/firefly-iii#1541]
**Bug description**
I am running Firefly III version 4.7.5

I noticed that `composer.lock` is ignored when copying files to the docker container, prior to running `composer install`. It is however saved to version control. Correct me if I'm wrong, but this means that people installing Firefly III on a self-hosted server following the procedure with `composer create-project` will end up with the versions in the `composer.lock` file while those using Docker ends up with whatever is resolved by `composer install` with no lock file when building the container.

If that is so, then you end up with users running the same version of Firefly III with potentially different vendor versions.

**Comment by JC5** [comment]
Indeed, I’ll check it out.
