### ISSUE TITLE
Balance Negative, not an issue, but more of a question.

### ISSUE THREAD

**Issue by triDcontrols** [firefly-iii/firefly-iii#1543]
Great app, but I'm bit confused. If this is the wrong area, my apologies.

Why is my balance negative? Am I not entering the information correctly? Is the balance per month basis? Reset's to 0 on the next month?

I added in my asset accounts, (my bank checking and savings, including credit card) and added in my transactions and get a negative balance. I have not made any deposits, still expecting the work pay check

![screen shot 2018-07-08 at 4 35 43 pm](https://user-images.githubusercontent.com/22411662/42425157-87d2ad36-82cd-11e8-8d28-b5b526264b63.png)
 

Shouldn't the balance be referenced to my total balance of a selected account? checking account? or the account I choose? 

I do see I have 0.00 income, shouldn't the income be what is in the asset account? 

![screen shot 2018-07-08 at 4 41 43 pm](https://user-images.githubusercontent.com/22411662/42425177-df6c38fa-82cd-11e8-9090-820246e53bd1.png)

**Comment by JC5** [comment]
The balance resets to zero every month. Since you have not created any deposits, it is negative. The current balance of the account is not included. The net worth refers to all your income + expenses including your opening balance(s).

**Comment by triDcontrols** [comment]
Awesome, thanks,

**Comment by JC5** [comment]
No problem, I hope this clears things up! I’ll write something in the docs as well :+1:
