### ISSUE TITLE
Simple forecasting based on recurring transactions

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1544]
**Description**
This is a follow up on the discussion we already had in #1150:

Now that we have recurring transactions, it would be great if firefly would calculate some kind of forecast which tells me how much money will be left on account XYZ at the end of a period. The amount left per account is a pretty important value, because the budgeted 'Left to spend' value alone doesn't tell me from which accounts I can still draw money.

**Solution**
A poor man's solution could be a configurable option so firefly would create recurring transactions at the beginning of a new period (but still setting the transaction's date to correct due date). This would mimic the way I currently create some of my transactions (see below).
However, a 'native' support for this would be way cooler. I could imagine the graph to show some grayed out or dashed lines for all upcoming transaction (basically, everything to the right of the today marker). Also, switching the application to any upcoming period could show some preview of the expected account balances.

**What are alternatives?**
Currently I add some transactions to firefly in advance at the beginning of the month. I can then easily figure out at which balance a certain account will come out by reading the dashboard graph

**Comment by JC5** [comment]
Yes, an obvious continuation of this feature! Firefly III used to have such dotted bars. Even prediction! But it was pretty bad.

This could be a very nice way to reintroduce that feature. Not sure yet when, but I'll put it on the list!

**Comment by triDcontrols** [comment]
Vote +1

**Comment by panixx** [comment]
Would love to see this in calendar form (like https://dollarbird.co/).

**Comment by alexpercsi** [comment]
I'm looking to migrate from KMyMoney to Firefly-III and this is a critical feature that is missing for me.
I'd like to try to fork the project and create a second cron job which enters all scheduled transactions up to one month in the future instead of present day. @JC5 - do see any issues with this? Anything I should watch out for? Would it make sense to submit a pull request for this? 
This is the quickest way to get the ball rolling on any kind of projections IMO.

**Comment by JC5** [comment]
I won't accept a PR in that direction, but there's nothing that you can break if you start creating transactions in the future. Firefly III has a very arbitrary view of what "the future" is anyway, when you select other time ranges etc. 

If Firefly III is going to feature prediction, I want it to be another mechanism than just creating the transactions. That's not really predictive. But it won't be a part of Firefly III for the near future.

**Comment by JC5** [comment]
Forecasting won't be a function in Firefly III. Sorry about that.
