### ISSUE TITLE
2FA backup pin code

### ISSUE THREAD

**Issue by triDcontrols** [firefly-iii/firefly-iii#1545]
A Suggestion, 

I am running Firefly III version 4.7.5

**Description**
I have 2FA enabled with google authenticator and my phone died, and needed to get into the firefly, I had to wait until the phone charged up so I can power it up and get in. I have seen other sites implement this backup method to login, (i.e. dropbox) if you don't have your phone to verify, then a backup "pin" can be used to gain access, dropbox took this a step further and also implemented if someone is trying to log in out of the normal login location, you need to get 2FA verified by the authenticator app and the backup pin option is not shown. 

**Bonus points**
![2fa error](https://user-images.githubusercontent.com/22411662/42465059-c5267c48-835f-11e8-9c54-bf7b666d5232.PNG)
![2fa_suggestion](https://user-images.githubusercontent.com/22411662/42465202-21e6bab0-8360-11e8-817c-50caa08c6cea.PNG)

**Comment by JC5** [comment]
That is a good idea to implement. I believe the library that I use did not support it way back when I introduced 2FA for the first time.

But I believe it does now, and it is a logical next step. Thanks for the suggestion! :+1:

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947158

**Comment by JC5** [comment]
<img width="782" alt="Screenshot 2019-08-06 at 17 49 36" src="https://user-images.githubusercontent.com/5889984/62555253-e76d6700-b872-11e9-8d92-ea8152c9fabf.png">
