### ISSUE TITLE
Prevent 2FA replay

### ISSUE THREAD

**Issue by khicks** [firefly-iii/firefly-iii#1547]
Hello! I'm loving Firefly III so far. It's one of the best tools I have. I did notice a (slight?) security issue, though.

It appears that two-factor authentication codes can be used for an unlimited number of times for as long as they are valid. 

For the unfamiliar readers, this means that an attacker that intercepts your 2FA token can quickly use it to log in after you. Most major websites have implemented a system that restricts each 2FA code within a 30-second period to only one use, forcing you (or an attacker) to wait until your code rolls over to the next value to log in again.

Replicating this issue is pretty easy. Enable 2FA on your account and start a fresh browser session. Log in, log out, and then back in within a 30-second time frame, using the same 2FA code both times. For completeness, you can also do this between two separate browsers on the same computer or two separate computers entirely.

Thanks for your hard work!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947158

**Comment by JC5** [comment]
This will be implemented in 4.8.0
