### ISSUE TITLE
Renaming budget breaks "Set budget to..." rule

### ISSUE THREAD

**Issue by jpelgrom** [firefly-iii/firefly-iii#1549]
Using Firefly 4.7.5.

If you create a rule which uses a "Set budget to..." action, renaming the budget afterwards will not update the budget used in the rule.
Considering the nature of budgets, I expect the rule to 'follow' the budget even when it is renamed: it's still the same budget.
However, in case not changing the budget is the intended behaviour, I would at least expect it to continue setting the budget to the old value (so technically that's a new budget?) for new matching transactions, but instead it sets no budget at all.

**Example**
Expected when following the budget:
- Create budget 'A'
- Create rule which includes a "Set budget to..." action, value 'A' (clicked on autosuggest)
- Rename budget 'A' to 'B'
- Create a new transaction which matches the rule, budget set to 'B'

Expected when not changing the budget is intended:
- Create budget 'A' (ID: 1)
- Create rule which includes a "Set budget to..." action, value 'A' (clicked on autosuggest)
- Rename budget 'A' to 'B'
- Create a new transaction which matches the rule, budget set to 'A' which is newly created (ID: 2)

Actual behaviour:
- Create budget 'A'
- Create rule which includes a "Set budget to..." action, value 'A' (clicked on autosuggest)
- Rename budget 'A' to 'B'
- Create a new transaction which matches the rule, no budget set at all (transaction still shows up when clicking the flask icon to test the rule)

---

Clicking 'update rule' after the budget name is updated does show an error message:
![](https://user-images.githubusercontent.com/8148535/42635949-c4da4a82-85e7-11e8-8e9b-2c0319fecf7f.png)
(the budget name was originally "Transport/OV 🚄", changed to "🚄 Transport/OV")

The stack trace on `/debug` doesn't appear to change when adding a new transaction where the rule matches an old category name.

**Comment by JC5** [comment]
That can be fixed. Bills already respond to such changes so it won't be difficult to fix this one as well. Thanks for reporting!
