### ISSUE TITLE
budget API

### ISSUE THREAD

**Issue by mrahmadt** [firefly-iii/firefly-iii#1552]
Hi,

Similar to Accounts, Transactions, and Users APIs. can we have API for the budget?

Thanks

**Comment by JC5** [comment]
Do you mean this one?

https://firefly-iii.readthedocs.io/en/latest/api/budgets.html

**Comment by mrahmadt** [comment]
Thank man I haven't seen it :)

According to the documentation, no way to get or update the budget amount? any workaround?

**Comment by JC5** [comment]
There is no documentation yet but try 

GET /api/v1/budget_limits

**Comment by JC5** [comment]
See:

https://firefly-iii.readthedocs.io/en/latest/api/budget_limits.html

**Comment by mrahmadt** [comment]
Excellent, thank you very much

I'm assuming start_date & end_date are the basically the first & last day of the month, correct?
