### ISSUE TITLE
Income vs. expenses overview graph not correct

### ISSUE THREAD

**Issue by Kail0** [firefly-iii/firefly-iii#1553]
I am running Firefly III version 4.7.5.1

The Income vs. expenses overview graph of Default Financial report doesnt show correct data.
July Income is missing and its included in June column. See included screenshots.

![layer 2](https://user-images.githubusercontent.com/2068046/42788419-bd46a0f6-895f-11e8-8322-bd6896e418c0.png)

![rectangle 1](https://user-images.githubusercontent.com/2068046/42788403-978fe7c8-895f-11e8-8598-1a09709fba2a.png)

**Comment by JC5** [comment]
I haven't been able to reproduce this on the demo site. The current test set contains no deposits, but creating one updates the chart just fine.

See here:

* https://demo.firefly-iii.org/reports/default/34,1,32,33,2,3/currentYearStart/currentYearEnd
* https://demo.firefly-iii.org/transactions/deposit
* https://demo.firefly-iii.org/transactions/show/620

(Please note that the final link may give a 404 because the demo site resets often)

Could you browse to the `/flush`-page and see if that might work? Otherwise, you might run the following command on the command line:

```
php artisan cache:clear
```

If it still doesn't show up, make sure that the account that received the deposit is also included in the report.

**Comment by Kail0** [comment]
Non of these have worked. But it's kinda weird that I found that when I move my deposit after the specific date - 7. July. It will show up in report. As soon as I move the deposit back to original date - 4. July, its included in the wrong collumn of graph.

**Comment by JC5** [comment]
What's the exact URL of the report this is on? Can you copy paste this from the address bar?

**Comment by JC5** [comment]
You can leave out your host name if it's private of course.

**Comment by Kail0** [comment]
It's the report from Dashboard - Net Worth panel - 
https://domain.com/reports/default/allAssetAccounts/currentYearStart/currentYearEnd

**Comment by Kail0** [comment]
Just include some screenshots.
As you can see. When I generate report for only one account (that is receiving deposits) it will show all deposits I made. 
![salary](https://user-images.githubusercontent.com/2068046/42813434-45a4e0f0-89c1-11e8-84ea-7ea64127f4cc.png)

**Comment by JC5** [comment]
Alright, I'm not able to replicate this just yet, but we're getting there. Could you help me out?

1. Have you set a custom fiscal year?
2. Given this URL: ``/reports/default/allAssetAccounts/currentYearStart/currentYearEnd``: what is the bread crumb (top of page, Home > Reports > Default financial report between ..). Can you share the entire line?
3. Did you set the opening balance of the CSOB account to May 7?
4. Was the first transaction to that account on May 7?

**Comment by Kail0** [comment]
1. Nope, I'm not currently using fiscal year option.
2. `Home > Reports > Default financial report between May 7, 2018 and December 31, 2018`
3. Nope. I think I didnt set opening balance. I just started with first transaction: Deposit to my bank account from 7th July. Then, I added previous transactions (adding entries in this order July > June > May >etc..)
4. First transaction ever was 4th July.

----
PS
Excuse my english, I've got a feeling that I could explain that little better.
Also, the whole problem will be definitely only my fault.

Ad. 
I just want to take advantage and thank you for this application and great support.

**Comment by JC5** [comment]
It's OK, I found the issue and I've pushed a fix (see above). You can apply this manually by checking out the differences in the commit. You can also [replace the content of the entire file](https://github.com/firefly-iii/firefly-iii/blob/9299efd08604b8765f0ac2345306e2ae2ee39239/app/Http/Controllers/ReportController.php) and it should work again.

I'm glad I could help, and happy to see you like the app!

**Comment by Kail0** [comment]
It's working! Thank you again. 

Enjoy your beer. ^^

**Comment by JC5** [comment]
I will, thanks! :grin:
