### ISSUE TITLE
Could not check for updates

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1554]
**Bug description**
I am running Firefly III version 4.7.5. Firefly shows an error message where normally the update notification would occur.

Excerpt from log file:
```
[2018-07-17 05:23:57] production.DEBUG: Have not checked for a new version in a week!  
[2018-07-17 05:23:57] production.DEBUG: Going to call https://github.com/firefly-iii/firefly-iii/releases.atom  
[2018-07-17 05:23:57] production.ERROR: Could not check for updates: Response error from Github: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  
```

The error, according to libcurl, is:
```
CURLE_SSL_CACERT (60)

Peer certificate cannot be authenticated with known CA certificates.
```
That is pretty strange given that we are trying to call `github.com`. I suppose that might be some configuration issue on my server but I'm not quite sure where to look.

**Comment by JC5** [comment]
Your cURL installation may be old, and thus use an old list of root certificates (one that doesn't list GitHub's root cert).

You can download a new set here: https://curl.haxx.se/docs/caextract.html

I am not sure however where cURL stores this file and if it can easily be replaced.

Simply upgrading cURL to a recent version might be enough to fix this.

**Comment by skuzzle** [comment]
That did the trick. The CA file for curl to use can be configured in the php.ini. Per default the ini entry is empty and curl is likely using some outdated baked in list of CAs. By pointing the entry `curl.cainfo` to the pem file generated (or downloaded) from the link you posted, everything works fine again.
