### ISSUE TITLE
Fields filling in new transaction form based on last similar record

### ISSUE THREAD

**Issue by Bubka** [firefly-iii/firefly-iii#1555]
**Usage context**
I manage my finances usually once a month, after receiving my monthly bank statement.
During this session I record all my transactions in firefly, one by one, using my credit card receipts and my bills as reference (I only use my bank statement as a comparison basis to perform a reconciliation and validate balances)

When I input my transactions I regularly have to record similar transaction to those already recorded in firefly. Those transactions are not recurring transaction, i.e the hairdresser: I don't visit him on a regular basis, it can be one or 2x a month or every 3 month. But the metadata of this expense (description, category, tags, budget, etc...) are always the same.

**Description**
The suggested feature consists in an automatic filling of some fields in the new transaction form.
On demand, after having set the opposite account, some other fields would be filled with same values as in the last transaction of this opposite account.

##### Example
On June I recorded a hairdresser expense like this:
- Description: Hairdresser
- Amount: 20€
- Asset Account: MyAssetAccount
- Expense Account: Provost
- Category: Beauty care
- Tags: Credit Card, Mandatory

On July, I visit my hairdresser again, so here is what would be my routine in Firefly:
- I open the new transaction form (set as new expense with **MyAssetAccount** set as default asset account)
- I set the expense account to **Provost**
- I click a button (with something like "replicate last transaction of this opposite account" as caption||title)
- Firefly fetches *Description*, *Category* and *Tags* of the last expense matching the selected asset and expense accounts via an ajax request and fills the form with fetched values.
- I just have to fill the amount to complete and submit the form

**Solution**
This feature has 2 pro:
- Input of usual and similar transactions is much faster (2x faster at least). It becomes significant when you have lots of usual expenses each month.
- Usual transactions are always recorded alike. This is really an important point when you want consistent and relevant reports.

**What are alternatives?**
The duplicate transaction feature of firefly is an alternative. The cons of this method is that it requires to first search for a similar transaction. So during a batch of transaction inputs the "return here" option becomes useless. At the end you have consistency but you spend lots of time searching for similar records to duplicate.

**Comment by JC5** [comment]
I suspect you can do this with rules. It would be enough to enter the description, amount, and possibly the destination account to trigger a rule. That rule could fill in all the other details.

I use this myself to store groceries, some bill-related transactions and other regular things like lunch.

**Comment by Bubka** [comment]
hum, havn't thought about the rules to address this needs 🤔
i will give it a try :+1: (even though i suspect that the feature will be a little bit constraining, at least at the beginning)
