### ISSUE TITLE
Importing 2 transfers with the same values = error

### ISSUE THREAD

**Issue by notDavid** [firefly-iii/firefly-iii#1556]
Hi there,

as the title says, importing 2 transfers from a savings account to a normal asset account, where both transfers have the same `date`, `amount` and `description` results in error:

`Row #1 ("INTERNAL TRANSFER") could not be imported. It already exists.`

Tested in version 4.7.4 and 4.7.5.1.

When manually adding it, it just gets created without any problems.

**Comment by JC5** [comment]
Yes, this is by design. It is designed to prevent importing duplicate rows.

If there is too little data to meaningfully distinguish rows it could happen inadvertently, but this cannot be prevented by Firefly III. 

If you run into this a lot, a solution is to add a unique number to the CSV file so rows are unique again. This number must be imported as the “external ID”.

**Comment by notDavid** [comment]
Okay i understand importing duplicates has to be prevented.

But since you download a .csv file from your bank, and then import it, do you think this "check" is needed when the 2 duplicate items are **in the same file** ?
I doubt the bank will have an error in their export?

**Comment by JC5** [comment]
You would be surprised the kind of mistakes banks make. :wink:

But ultimately the verification is over multiple files. Firefly III stores a hash of the transaction and will compare future rows and future files to this hash.

**Comment by notDavid** [comment]
👍

**Comment by Skaronator** [comment]
I'm currently importing from my own finances manager and run in the same issue. Is there a way to disable this check?

**Comment by notDavid** [comment]
@JC5 ...i spent waaay too much time manually correcting this. I agree that a way to skip (a warning instead of an error) would be great.

**Comment by Skaronator** [comment]
@notDavid What do you mean with "manually correcting"? Did you just renamed each transaction so it has a unique name?

My CSV for internal transactions looks like this:
```csv

**Comment by notDavid** [comment]
@Skaronator You can either add the transactions manually via the web interface by simply clicking the "+" and adding a new transaction and typing in all the values. You **CAN** create duplicate transactions this way.

Or, as @JC5 said above, change the .csv to make it unique:

> if you run into this a lot, a solution is to add a unique number to the CSV file so rows are unique again. This number must be imported as the “external ID”.

**Comment by notDavid** [comment]
@JC5 Stubling upon this error again;

So when you first import a .csv from "account1" and after that import another .csv from "account2" (both from the same month) you get the above error (`Row #1 ("INTERNAL TRANSFER") could not be imported. Such a transfer already exists`) for transfers between the 2 accounts. This is "normal" because you are importing the exact same transaction again from the opposite account.

So in other words, sometimes when you get this error it's OK (when doing internal transactions.)
But sometimes when you get this error it's not OK and your data will become inconsistent (if you do an identical transaction from "account1" to 2 different external accounts.

So now, i have to manually inspect all these errors (10 in my case) to find out if they are "valid" or not?

It's a real PITA and consumes a lot of time! Is there really no solution to this?

**Comment by JC5** [comment]
Alright keep me posted. I have test files for most edge cases but I don’t always run them for each release. So it’s totally possible something sneaked through.
