### ISSUE TITLE
Show tags in lists

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1557]
Hi,

Sometimes I am missing the tags associated with a transactions in the list views (for example the list of transactions for a specific account).
Due to space constraints it might not be possible to add them there, but would it be possible to add it to the financial report for example as an extra checkbox that gives you a comma separated list of tags?

**Comment by JC5** [comment]
I have an issue somewhere to clean up these lists. They're inconsistently missing data and are a bit messy. I think it'll have to be an option. Will get back to you!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947295
