### ISSUE TITLE
Extra column in Category report

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1558]
Is it possible to add a sum column in the Category report?

![image](https://user-images.githubusercontent.com/441924/42995601-8f7f2aee-8c11-11e8-8a5e-28e80540df7c.png)

I use some categories like this: I went on holiday, and created an account called 'Holidays'. My expenses are linked to this account. However some people refund me the ATM withdrawals I did for them as well. These refunds are linked to this category as well.
Therefore I would like to see the sum of the earnings minus the expenses.

**Comment by JC5** [comment]
Sure thing, plenty of room!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947339
