### ISSUE TITLE
Problem getting oauth 2 token

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#1559]
I am running Firefly III version 4.7.5.1. I am sending a HTTP POST request to _https://firefly.xxx.com/oauth/token_ using the following parameters _https://firefly.xxx.com/oauth/token?grant_type=authorization_code&client_id=3&redirect_uri=fireflyiii://oauth&client_secret=xxx&code=xxx. It throws an error saying: 

> {
    "error": "unsupported_grant_type",
    "message": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check the `grant_type` parameter"
}

The log says 
```local.ERROR: Exception is: {"class":"League\\OAuth2\\Server\\Exception\\OAuthServerException","errorMessage":"The authorization grant type is not supported by the authorization server.","time":"Fri, 20 Jul 2018 21:19:59 +0800","file":"\/var\/www\/firefly.xxx.com\/vendor\/league\/oauth2-server\/src\/Exception\/OAuthServerException.php","line":65,"code":2,"version":"4.7.5.1","url":"https:\/\/firefly.xxx.com\/oauth\/token?client_id=3&client_secret=xxx&code=xxx&grant_type=authorization_code&redirect_uri=fireflyiii%3A%2F%2Foauth","userAgent":"PostmanRuntime\/7.1.5","json":true}
[2018-07-20 21:19:59] local.ERROR: The authorization grant type is not supported by the authorization server. {"exception":"[object] (League\\OAuth2\\Server\\Exception\\OAuthServerException(code: 2): The authorization grant type is not supported by the authorization server. at /var/www/firefly.xxx.com/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:65)
[stacktrace]
```
What am i doing wrong? From the docs it says i need  authorization_code grant type. so why did it fail?

**Comment by emansih** [comment]
yes, the request works if i were to use postman `Get Access Token` function. 
![untitled](https://user-images.githubusercontent.com/5896415/43009247-b5279f0c-8c6f-11e8-969a-e42bfdd3f4eb.png)

**Comment by JC5** [comment]
Mmmm, there must be a difference between the two. All I can find in the Laravel code is that it is a fallback for when nothing else works. 

If you Google "unsupportedGrantType laravel" you can find some hints. It seems that the token you've generated on the /profile is being mislabeled somehow.

I am not sure what hints to give you, it'll require some experimentation.

**Comment by emansih** [comment]
Ah! I figured it out after a long night of debugging. For future readers here is what i did. 

I am using cURL as an example. 

Enter this into the browser.  https://firefly.YOURENDPOINT.com/oauth/authorize?response_type=code&client_id=<YOUR_CLIENT_ID>&redirect_uri=http://empty&scope=&state=
(Use the appropriate values)

Login to your firefly instance and your URL bar will change to `empty/?code=xxxxxxxxxxxx`. Copy the value of the code and you can use curl to get your access token. 

curl --request POST --data "code=<YOUR_CODE_VALUE>&client_id=<YOUR_CLIENT_ID>&client_secret=<YOUR_CLIENT_SECRET>&redirect_uri=http://empty&grant_type=authorization_code" https://firefly.YOURENDPOINT.com/oauth/token

Now I'm able to build some CLI stuff

**Comment by JC5** [comment]
So, this is what you would expect right? You submit your client ID + secret to the authorize end point which gives you a code in response (sent to the redirect_uri).

**Comment by emansih** [comment]
yea, i suppose so...the document is sparse in telling me that. i had to read documentation from other blogs.

**Comment by JC5** [comment]
True, but OAuth is a pretty well known standard. I would only be repeating others.
