### ISSUE TITLE
Allow narrowing transaction queries from API with date ranges

### ISSUE THREAD

**Issue by mconway** [firefly-iii/firefly-iii#1560]
**Description**
Please describe your feature request:

This would be 2 parts, and could possibly be broken into 2 separate feature requests. First, on the transactions API endpoint, allow specifying a start and end date for transactions to be returned.

Second, when including transactions as part of another query (budgets or categories, for example), allow the same date parameters to be used.

**Solution**
Currently, in order to limit a date range through the API, I have been having to download several pages of transactions, and search each returned instance for the earliest date requested. By implementing a date filter, this would allow applications using the API to function more closely to the Firefly web client.

For example, in the Firefly Mobile App, I'd like to add a visual of the amounts spent per category. In order to currently implement this feature, I will have to download 50 transactions at a time, then search each item for the earliest and latest date requested.

**What are alternatives?**
Do nothing. This will require extra work by integrators when building against the application. It also results in more web calls, which on mobile applications can be detrimental to performance or individual's data plans.

**Comment by JC5** [comment]
Hey, thanks for the suggestions!

Start and end are valid parameters for the list of transactions. See [here](http://firefly-iii.readthedocs.io/en/latest/api/transactions.html). Is that not what you're looking for, or is it not working perhaps?

Accounts, budgets and categories have the option to include transactions, and they all accept the `page`, `start` and `end` parameter to limit the list of transactions you get back.

If something is not working please get back to me. They all use the same piece of code.

**Comment by mconway** [comment]
interesting, I was trying to use start and end the other day on transactions and it was not working. I'll give it another shot. I did discover some odd data today in my instance anyways. Will report back.

**Comment by JC5** [comment]
You probably know this already, but the preferred format is YYYY-MM-DD. I'm working on something else but if you need me to investigate just let me know.

**Comment by mconway** [comment]
OK, I was able to get start and end to work on /transactions. Interestingly enough, I'm trying ?include=transactions on /budgets and /categories and nothing is being included.

**Comment by JC5** [comment]
I see that it only works on individual budgets, accounts and categories. But that can be changed, would that help?

**Comment by mconway** [comment]
It would, but leads more into #1561 - the goal was to take a list of categories and show the amount spent per each, basically like you do on the dashboard. My way was to just get transactions for a timespan, then total them all.
