### ISSUE TITLE
Create an API endpoint to provide summary details of an account

### ISSUE THREAD

**Issue by mconway** [firefly-iii/firefly-iii#1561]
**Description**
There may be a better way to do this, but I am trying to replicate the Firefly web app's ability to show the dashboard summary cards in the mobile app. Currently, the app is pulling each account, sorting them into separate account types, then totaling each up. This ignores currency type and some other items, creating one total for all accounts of a type.

**Solution**
By adding an endpoint o show the calculated fields from the dashboard, the information can be quickly pulled and displayed in other manners.

**What are alternatives?**
For @mconway to stop being lazy and write this into the mobile app :) This may be perfectly viable, I'm just unaware if there is actually a set of methods within firefly that could be used for this purpose already.

**Additional context**
Feel free to tell me to suck it up. I'm just throwing out ideas.

**Comment by JC5** [comment]
No please continue. I had in mind to extend the budget_limits end point to include how much you actually spent in a period. Same could be done for categories (spent / earned info if start and end date are present).

So this would probably become a new `overview` end point where I can put stuff like that.

**Comment by mconway** [comment]
Obviously, anything included in overview would save other apps calculation time. I'm really focused on the following data currently:
Balance
Bills to Pay
Overspent/left to spend
Net Worth.

I can calculate bills to pay as-is if I need to, but the others would be great.

I can also do the categories totals by totaling the transactions for a time period. That said, it might be easier to just include the "total spent" in the category endpoint as a property? Doing the same for budgets would be useful as well.

**Comment by gavu** [comment]
+1

I thought about adding some of these infos on a magic mirror, so this would be great to have.

**Comment by JC5** [comment]
There is a new endpoint that offers this info. Please open a new ticket if anything is missing. 

https://api-docs.firefly-iii.org/#/summary/getBasicSummary
