### ISSUE TITLE
Unable to get data from available_budgets endpoint.

### ISSUE THREAD

**Issue by mconway** [firefly-iii/firefly-iii#1562]
I am running Firefly III version 4.7.5

**Description**
When trying to utilize the available_budgets endpoint, I always am returned an empty array.

**Steps to reproduce** 
<GET> http://localhost:8082/api/v1/available_budgets?start=2018-07-01&end=2018-07-31

```
{
    "data": [],
    "meta": {
        "pagination": {
            "total": 0,
            "count": 0,
            "per_page": 50,
            "current_page": 1,
            "total_pages": 1
        }
    },
    "links": {
        "self": "http://localhost:8082/api/v1/available_budgets?start=2018-07-01&end=2018-07-31&page=1",
        "first": "http://localhost:8082/api/v1/available_budgets?start=2018-07-01&end=2018-07-31&page=1",
        "last": "http://localhost:8082/api/v1/available_budgets?start=2018-07-01&end=2018-07-31&page=1"
    }
}
```

**Extra info**
I'm trying this through postman, for testing before adding to the mobile application.

**Bonus points**
I lose my bonus points, It works successfully on the demo site.

**Comment by JC5** [comment]
Trick question: have you set any available budget?

<img width="1054" alt="screen shot 2018-07-21 at 07 04 36" src="https://user-images.githubusercontent.com/5889984/43032329-5ea5deb0-8cb4-11e8-9d49-6e07d92ab10d.png">

That's the object that that specific end point returns. ($1234)

**Comment by mconway** [comment]
hmm. maybe I misunderstand the budgets page. I always just set the individual buckets, and thought that was what available budgets referred to?

![image](https://user-images.githubusercontent.com/411506/43032341-3b733c08-8c69-11e8-92cd-7398727db025.png)

**Comment by JC5** [comment]
It reflects my way of budgeting. If I set a (total) available budget, I can see by the bar if I budgeted everything nicely.

I have an excel list somewhere (still have to replicate it in FF3) that gives me a year overview of all budgets and the total amount.

**Comment by mconway** [comment]
So what you do is plug in the total budget at the top bar. Then the smaller buckets are applied against that to ensure you budgeted everything accordingly? I'll give that a shot and see what I can come up with.

**Comment by JC5** [comment]
Yes. The total amount (as set in available_budget) also influences the "left to spend"-box on the front page.

**Comment by mconway** [comment]
I've always wondered that :) I keep meaning to go re-read some of the documentation for FF# now that I've dug into much more.

**Comment by JC5** [comment]
Yep. All correct.

I intend to expand budget_limits with the spent amount because the date range makes it a logical place. I also want to expand budget_limits with the transactions, for the same reason.
