### ISSUE TITLE
'Suggested per month' seems to be broken on piggy bank page

### ISSUE THREAD

**Issue by nhaarman** [firefly-iii/firefly-iii#1563]
The suggested amount per month on the piggy bank page (#1405) seems to be broken as of version 4.7.5: the entire column is empty for all piggy banks.
More specifically, I did a `git bisect` which points at 12a84572e20da93ba9d236bafc4b334f65c22054 for the first bad commit.

**Comment by JC5** [comment]
Nice find. Turns out I used the wrong field name. Thanks for letting me know!

**Comment by JC5** [comment]
This will be fixed in the next release :)

**Comment by nhaarman** [comment]
Awesome!
