### ISSUE TITLE
When a transfer from one bunq account to another bunq account the transaction is imported twice

### ISSUE THREAD

**Issue by paul999** [firefly-iii/firefly-iii#1564]
**Bug description**
I am running Firefly III version 4.7.5.1

When I do a transfer from one account to another, but within the same BUNQ user the transfer is imported twice. The internal/bunq ID is different for these two transactions.

Removing one of them is okay, untill the next import as it is then imported again.

**Steps to reproduce**
What do you need to do to trigger this bug?

See above.

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

**Bonus points**
Earn bonus points by:

- Post a stacktrace from your log files
- Add a screenshot
![image](https://user-images.githubusercontent.com/65767/43035741-3834c188-8cf5-11e8-8907-580f1e61b5fc.png)

**Comment by JC5** [comment]
Mmm, tricky. Normally the import routine should detect duplicate transfers, but i don't believe this is done for bunq imports. Something to check.

For the second point, I will make sure that deleted transactions are checked as well. That should prevent it from popping up again.

Thanks for letting me know. :+1:

**Comment by JC5** [comment]
This is fixed. If you map your bunq accounts to Firefly III accounts, the system will recognise and skip double transactions.

It will give you an error for the "duplicated transaction", which is something I'll fix later.
