### ISSUE TITLE
Not all items in the graph are labeled while there is enough space in the graph

### ISSUE THREAD

**Issue by paul999** [firefly-iii/firefly-iii#1565]
**Bug description**
I am running Firefly III version 4.7.5.1

Not all items in a graph (This applies to all graphs on the homepage. The budget one being the worst of them) are labelled, while there is a lot of whitespace to label  them correctly

**Steps to reproduce**
What do you need to do to trigger this bug?
Open the homepage and notice the missing labels in the graphs.

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

Happens at least in chrome & firefox on WIN & OSX

**Bonus points**
Earn bonus points by:

![image](https://user-images.githubusercontent.com/65767/43035807-e9777b20-8cf5-11e8-8188-f101fe88377a.png)

**Comment by JC5** [comment]
It's part of the library I use to generate charts. Technically there is room, but I know it's a bit conservative in selecting the items to give a title. I can wiggle with the setting but I'd rather just leave it like this.
