### ISSUE TITLE
4.7.5.2 broke the wildcard Trusted Proxy

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1572]
**Bug description**
I am running Firefly III version 4.7.5.2

I used the trusted proxies wildcard (**) instead of hard coding my trusted proxy ip in the .env file.
However, this behaviour has changes in this [commit](https://github.com/firefly-iii/firefly-iii/commit/44fb307da4975658ae56361505e27e4772ac97ad#diff-621413a353ff80dd6f3855204be3d274)

According to the [documentation](https://laravel.com/docs/5.5/requests#configuring-trusted-proxies) the double asterisk should not be an array element, but the $trustedProxies variable should be a string '**'

**Steps to reproduce**
Have ** as trusted proxy ip in .env

**Extra info**
Reverse proxy installation

**Bonus points**
Earn bonus points by:

**Comment by JC5** [comment]
Oh goddamnit leave it to Taylor to be consistent about something. I'll push a hotfix.

**Comment by JC5** [comment]
@zjean, can you verify this works?

https://github.com/firefly-iii/firefly-iii/commit/fb122ba0972613a60534d9e55c7124788c525209

**Comment by JC5** [comment]
Pushed 4.7.5.3.

**Comment by zjean** [comment]
Works perfect

**Comment by JC5** [comment]
Great, because I was impatient and pushed it already :wink:
