### ISSUE TITLE
Problem with docker installation

### ISSUE THREAD

**Issue by xosem47** [firefly-iii/firefly-iii#1573]
I am running Firefly III version latest

**Description**
After installation, I try to initialize database and it does not work.

$ docker exec -it firefly php artisan migrate --seed

In Connection.php line 664:
                                                                                                                                                     
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations)  
                                                                                                                                                     

In PDOConnection.php line 50:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 46:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

**Steps to reproduce** 
I am using https://firefly-iii.readthedocs.io/en/latest/installation/docker.html#straight-from-docker-hub

I checked that user and password are correct. Also used remote host, localhost and 127.0.0.1

This is the installation command 
$ docker run -d -v firefly_iii_export:/var/www/firefly-iii/storage/export -v firefly_iii_upload:/var/www/firefly-iii/storage/upload -p 80:80 -e FF_APP_ENV=local -e FF_APP_KEY=zKH2PvbKPib4muSaJzm6ogpwK9QEdsWi -e FF_DB_HOST=127.0.0.1 -e FF_DB_NAME=firefly -e FF_DB_USER=root -e FF_DB_PASSWORD=<mypassword> --name firefly jc5x/firefly-iii:latest

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by xosem47** [comment]
Sorry! I was using wrong FF_DB_HOST, I wanted to connect to other docker instance so is FF_DB_HOST=mysql0

**Comment by JC5** [comment]
No problem, glad to hear it's fixed!
