### ISSUE TITLE
Changes to .env not saved in Docker Container. 

### ISSUE THREAD

**Issue by triDcontrols** [firefly-iii/firefly-iii#1574]
I am running Firefly III version 4.7.5.1

I have firefly III behind nginx proxy in a docker container. I edited the .env and added the APP_URL and the TRUSTED_PROXIES to **

saved it, and on reboot, the .env is returned to defaults, my changes are not saved. 

If I save the .env and reload apache2, then settings stick, but on a container reboot, defaults are loaded.

**Comment by JC5** [comment]
In the docker container you must use environment variables.

**Comment by triDcontrols** [comment]
How can use environment variable after container creation?

**Comment by JC5** [comment]
You can [launch the Docker instance](https://firefly-iii.readthedocs.io/en/latest/installation/docker.html) with the -e flag, setting all the environment variables you need. For `TRUSTED_PROXIES`, you would use 

`-e TRUSTED_PROXIES=**`
