### ISSUE TITLE
CSRF-Token not found

### ISSUE THREAD

**Issue by triDcontrols** [firefly-iii/firefly-iii#1575]
I am running Firefly III version 4.7.5.1 in a docker container. 

On initial load of the app, chrome developer console throws an error. CSRF-Token not found. Error: 

`app.js?v=4.7.5.1:1 CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token`

Went to `https://laravel.com/docs/csrf#csrf-x-csrf-token`

and to fix this, the doc says to add the meta tag to the html. 

`<meta name="csrf-token" content="{{ csrf_token() }}">`

Where do I add this meta tag? 

Issue also present on firefly demo site.

**Comment by JC5** [comment]
If I'm not mistaken, every page that needs the token has the token. However, I see that Laravel _always_ complains when it's not there.

For the next release, I've expanded the code so this token is set on every page, even those that won't need it. That will make Laravel shut up about it :wink:

Thanks for letting me know!
