### ISSUE TITLE
Recurring transactions: Multiple suggestions

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1578]
**Description**
Hi, I have three suggestions on how to improve recurring transactions:
1. Shame on me, but I haven't read the documentation and wondered why my recurring transactions have not been created. Firefly should be able to find out whether the cron job has been correctly configured (by checking wheter a transaction that should have been created has actually been created upon visiting the recurring transactions page). Also, as I'm using Windows you can never be sure whether everything works as expected :D. It would be great if firefly could show a warning if it finds out something is misconfigured.
2. Upon login it would be great if firefly could highlight all transactions that have been created by the system (either since last login or transactions must explictly marked as 'reviewed'). That would allow users to review whether everything went correct.
3. I guess most users will create recurring transactions for their bills or bills for their recurring transactions. There is quite a lot of data one needs to enter twice in those cases. It would be great if this step was supported by the system by creating a matching bill to the recurring transaction or vice versa.

**Comment by JC5** [comment]
1. That should be fairly easy to do, but it won't check on the transactions themselves but rather on the cron job. It's a technical difference really.
2. Firefly III creates emails that are sent to the user. So the user would have in his inbox a message saying "FF3 created x new transactions". I will extend the docs to tell people to configure their email.
3. Yes, this is a thing. There are several workflows that pop up often together. Rules are one as well. I have some cards on the project to improve usability on those.

**Comment by skuzzle** [comment]
1. When checking for the cron job, will that work on windows too? Because I'm now using the TaskScheduler for running the recurring transaction command
2. I should eventually set up a mail server then :D

**Comment by JC5** [comment]
Yes. I would simply set a timer, like "last_cron_run". If it's more than 36 hours I can alert the user.

**Comment by JC5** [comment]
The time of the last cron is being kept now, but no alert yet. A new cron job is being developed that can be fired once a day.

**Comment by JC5** [comment]
And this will be fixed in the next release :D

**Comment by JC5** [comment]
New release is live. Please open a new ticket when the problem persists. Thanks!
