### ISSUE TITLE
Missing translatable string and missing date on reconciliation overview

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1580]
I am running Firefly III version 4.7.5.3

As you can see in the image below, the title of the dialog is in English and I cannot find that string on Crowdin.
![reconciliation](https://user-images.githubusercontent.com/2808166/43416623-1f8e0ed2-9439-11e8-91cb-d8f0299fb34a.png)

Also, in the first and fourth line (Start/End balance submitted), between parenthesis there should be an actual date, right?

**Comment by JC5** [comment]
Ah thanks for letting me know, I didn't realise! I've pushed a fix that will be included in the next release, and the new translation should be available in Crowdin now. :+1:

**Comment by JC5** [comment]
I'm closing this since it's fixed. Look for this feature in the next release, and let me know if you encounter any problems!
