### ISSUE TITLE
OFX support a la gnucash

### ISSUE THREAD

**Issue by kaysond** [firefly-iii/firefly-iii#1582]
I'm looking for a browser-based financial management software that supports OFX so I can retrieve my transaction information directly from institutions.

gnucash implements this through https://github.com/aqbanking/aqbanking which in turn uses https://github.com/libofx/libofx

It's nice because in the gnucash implementation your password isn't stored anywhere, and is only sent directly to your institution when you import transactions. It also doesn't at all rely on an external API.

Is there any interest in having this? It's something I'd be interested in contributing.

**Comment by JC5** [comment]
At the moment, Firefly III does not support OFX imports. But yes, it is on the list! One of the issues about this is #965. 

Firefly III has a few import routines already which I want to extend with OFX support in the future. What were your thoughts on this?

**Comment by kaysond** [comment]
I did take a look at that issue. I'm by no means an expert, but I think QFX is just a file format, whereas OFX is both the format and the communication protocol. So you could first start with an OFX format library, which could be easily extended to cover QFX as well.

I think this could definitely be implemented as a new import routine where the user supplies the OFX/QFX files.

The second step would be to implement the communication protocol which just operates over https. ofxhome has a massive list of the institution info needed to pull transactions: http://www.ofxhome.com/index.php/institution/view/424 and a web api to retrieve it too. Users would just have to enter the username/password every time they want to retrieve their data. You could even store the username/passwords encrypted with a master password so the user can retrieve all their institution info with a single password entry. This could be a separate import routine.

**Comment by kaysond** [comment]
Here's a parser library that could be used: https://github.com/asgrim/ofxparser
seems to be actively maintained

**Comment by Aquariu** [comment]
As for Imports, don't forget the awesome Boobank app. It's an open source app (compiled and packaged normally as part of your linux distribution) that does the retrieving of transactions. I believe you can choose various file formats. I personnally use it with a cron job to extract my banking data weekly and automagically import it in Firefly. Works great.

Does it seem possible to call the library from the php code to do the same thing the standalone program does ?

**Comment by PrplHaz4** [comment]
Having just experimented w/GnuCash and BooBank, the OFX import functionality is great...and the complexity of calling something in C or Python from PHP may not be worth it.

In my research I also found this project, which will fetch OFX statements using PHP (and the ofxparser library above), but it is no longer maintained and doesn't support all account types - just Bank, Credit and Investment (it seems).
https://github.com/CentsforChange/banker

To me, OFX support seems extremely important because it bypasses the need for a 3rd party to be involved in transaction imports, and gets data from the source.

**Comment by initrd** [comment]
Adding a +1 to this bug. My bank isn't supported on Salt Edge but they do support OFX. I currently have no convenient means to link firefly-iii to my bank :( OFX support would open up automatic integration with [at least 1100+](https://www.ofxhome.com/index.php/home/directory/all) institutions!

**Comment by kaysond** [comment]
@JC5 Looks like you started working on this? I found app/Support/Import/Routine/File/OFXProcessor.php in the develop branch but its incomplete.

I'm happy to help work on it, or even take it over.

Did you have anything specific in mind as far as implementation?

**Comment by JC5** [comment]
I haven't found a PHP library yet that can do OFX parsing. I'm they're out there, but the ones I found weren't capable of parsing even three different example files without breaking down.

I can build my own, or fork an existing one but it'll be slow going.

**Comment by kaysond** [comment]
Gotcha. If you send me/post your example files I can work on the parsing.

Seems like it should be pretty easy considering there's a spec...

**Comment by JC5** [comment]
Oh you can Google some examples, and check out [this library](https://github.com/asgrim/ofxparser). The fact that there's a spec isn't much consolation :wink:

**Comment by PrplHaz4** [comment]
I think are two major pieces to this feature:
1. Connecting to/managing connections to financial institutions that support OFX (and mapping those to internal accounts) - based on the muddy implementation of aqbanking in gnucash, this is a bit tricky
2. Parsing OFX files and importing them (this will be largely similar to importing other flat file formats)

**Comment by JC5** [comment]
Indeed, but I would consider those two separate features.

**Comment by kaysond** [comment]
> The fact that there's a spec isn't much consolation 😉

Hah. You weren't kidding. Most of my institutions are using qfx, implemented as a subset of ofx v1.0.2, which is from 1997.

Philosophically speaking, do you care about validating the file format? The OFX organization provides xml schema's for the new specs and DTD's for the old specs, so it could be automated pretty easily. Or is the objective to make as robust a parser as possible and do the best even with ill-formed files?

**Comment by JC5** [comment]
I want to use an external parser, so other people can enjoy the parser as well. It should be as robust as possible because when I check out the current best library (see above), it's impossible to keep to the spec and support anybody. I don't think any bank keeps to the spec at all.

I'll build something that utilizes that parser in the near future and add it as an experimental feature. We can continue from there.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
