### ISSUE TITLE
Row could not be imported because it already exists error

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1585]
I am running Firefly III version 4.7.5.3.

I am importing some transactions from a CSV file. I imported them and then deleted them because it is much easier to correct errors directly to the CSV file than in Firefly. Upon importing the new CSV, Firefly does not import them any more because it says that those transactions already exist even though I deleted them.

Am I doing something wrong? I already did this same procedure before and it worked flawlessly.

**Comment by JC5** [comment]
I'm assuming that you also delete rows that you did not correct in the CSV? Because those will be detected indeed.

This is by design. The import routine will also check for deleted transactions to prevent the "reappearance" of previously deleted transactions.

**Comment by JC5** [comment]
Mmm, then you may have detected a bug. If the content that ends up in a transaction is different, the transaction will be different. Examples are:

- New description
- Different amount
- Added tags or categories

However some changes may not be detected:

- Any column that is mapped to "(ignore this column)".
- Any change in columns that are mapped. For example, if you change the opposing account name from "Walmard" to "Walmart",  but the mapping remains "Walmart", the change is not detected.

I will do some experimentation this weekend. See if I can't find the problem.

**Comment by lucavallerini** [comment]
No, I think it works as designed. I removed the category and added it later since it is the same for all transactions and I could import them.

Just to check, the first transactions that I imported was these:
``` 
date;description;amount;label 1;label 2;opposing account
2013-08-13;Acquisto app “Tapatalk”;0,75;Android;;Play Store
2013-09-08;Acquisto app “ePSXe for Android”;2,99;Android;;Play Store
2013-10-13;Acquisto gioco “Final Fantasy”;7;Android;Videogiochi;Play Store
```

Then I deleted all those transactions because the tags were messed up (my fault setting up the import) and I forgot about the mass edit function. Anyway, I tried with these first:
```
date;description;amount;labels;opposing account
2013-08-13;Acquisto app “Tapatalk”;0,75;Android;Play Store
2013-09-08;Acquisto app “ePSXe for Android”;2,99;Android;Play Store
2013-10-13;Acquisto gioco “Final Fantasy”;7;Android,Videogiochi;Play Store
```

and then I tried with
```
id;date;description;amount;labels;opposing account
1;2013-08-13;Acquisto app “Tapatalk”;0,75;Android;Play Store
2;2013-09-08;Acquisto app “ePSXe for Android”;2,99;Android;Play Store
3;2013-10-13;Acquisto gioco “Final Fantasy”;7;Android,Videogiochi;Play Store
```

without mapping the id column. From what you said I think they are not treated as different transactions.

Is this a recent modification? Back in April or May, when I imported most of the transactions, I did many times this same procedure (I was experimenting with the import function) and I never had a problem. However I do not remember exactly what kind of modification I made so perhaps I was just lucky.

Anyway thanks.

**Comment by JC5** [comment]
This is fairly recent, yes. The idea is that any source of transactions can be checked for duplications. To do so, the final transaction is compared, as opposed to the row that will be imported.
