### ISSUE TITLE
CSV import: all date fields but the one specified are filled with the import date

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1586]
I am running Firefly III version 4.7.5.3

Following the import discussed in #1585, all transactions have all date fields except the date one filled with the import date. I noticed this yesterday on my first import. The transactions have only 1 date specified and during the import I set that date as the 'Date' field: this is filled correctly but for some reason all the other date fields are filled with the date of today.

**Comment by JC5** [comment]
That is definitively a bug. I'll pick it up for the next release.

**Comment by lucavallerini** [comment]
There is also another problem with this bug: I can modify those dates but I cannot remove theme.

**Comment by JC5** [comment]
I've found both problems and they'll be fixed for the next release. :+1:

**Comment by lucavallerini** [comment]
Thanks, I applied the fix and now I can remove those dates.

**Comment by lucavallerini** [comment]
Since I imported over a hundred transactions I also mess directly with the DB to erase all those dates. I used this query:
```
DELETE FROM `journal_meta` WHERE `name` IN('book_date', 'process_date', 'due_date', 'payment_date', 'invoice_date', 'interest_date') AND `created_at` >= '2018-08-01' 
```
This should be enough, right? It does not seem I have broken something but you now the DB better than I do.

**Comment by JC5** [comment]
That should work just fine!

**Comment by JC5** [comment]
I'm closing this since it's fixed. Look for this feature in the next release, and let me know if you encounter any problems!
