### ISSUE TITLE
Impossible to remove the initial balance of an account

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1588]
I am running Firefly III version 4.7.5.3

I am not able to remove the initial balance of an account. I can modify the amount and/or the date but I cannot remove it altogether.

**Comment by JC5** [comment]
If you change the amount to zero, it should disappear again.

**Comment by lucavallerini** [comment]
You are right, sorry, I did not think to put it to zero, I only tried to remove both the amount and the opening date.

**Comment by JC5** [comment]
Your attempt is a valid one. That should work as well. I'll fix that.
