### ISSUE TITLE
Initial user not set as owner

### ISSUE THREAD

**Issue by claystation** [firefly-iii/firefly-iii#1589]
**Bug description**
I am running Firefly III version 4.7.5.3

The initial user is not set as owner.

**Steps to reproduce**
Fresh install of Firefly and create the initial user.

**Extra info**
Debug information generated at 2018-08-03 21:56:01 UTC for Firefly III version **4.7.5.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.5.3 |
| FF API version | 0.6 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, syslog |
| PHP version | 7.1.20 |
| Display errors | Off |
| Session start | 2018-08-01 00:00:00 |
| Session end | 2018-08-31 23:59:59 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, pdo_mysql, pdo_pgsql, tidy, zip |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.7.1, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.29, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.2, symfony/css-selector@v4.1.2, symfony/debug@v4.1.2, symfony/event-dispatcher@v4.1.2, symfony/finder@v4.1.2, symfony/http-foundation@v4.1.2, symfony/http-kernel@v4.1.2, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.2, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.2, symfony/translation@v4.1.2, symfony/var-dumper@v4.1.2, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.0, zendframework/zend-diactoros@1.8.3,  |

**Bonus points**
Earn bonus points by:

- Post a stacktrace from your log files

`[2018-08-03 21:54:59] local.INFO: Gave user #1 role #1 ("owner")`  
`[2018-08-03 21:54:59] local.INFO: Query exception when giving user a role: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'owner' for column 'role_id' at row 1 (SQL: insert into `role_user` (`role_id`, `user_id`) values (owner, 1))`

Broken in this commit https://github.com/firefly-iii/firefly-iii/commit/ca096852a5b1863eabb5323324f00c7abeeb0f29#diff-94ff863f5eeff629405ce9b2bff3db25L50

**Comment by claystation** [comment]
Submitted a PR to fix this. Not as lazy as last time. https://github.com/firefly-iii/firefly-iii/pull/1590

**Comment by JC5** [comment]
:+1: 

Thanks!

**Comment by JC5** [comment]
I'm closing this since it's fixed. Look for this feature in the next release, and let me know if you encounter any problems!
