### ISSUE TITLE
Breadcrumbs on Edit Transaction screen look awkward with a long description

### ISSUE THREAD

**Issue by Ditti4** [firefly-iii/firefly-iii#1594]
**Bug description**
I am running Firefly III version 4.7.5.3.

Not really a bug, just a mild design flaw.

When editing a transaction with a really long description, the edit screen's breadcrumbs look a bit... awkward:

https://i.imgur.com/qYvWkJN.png

Maybe the description could be wrapped at some point.

**Steps to reproduce**
1. Create a transaction with a long description
2. Click on the little edit icon
3. Look at the breadcrumbs

**Comment by JC5** [comment]
Mmm, you don’t have a 60K bij 1200 screen? :wink:

I’ll try some things tomorrow, see what works.

**Comment by JC5** [comment]
I'm closing this since it's fixed. Look for this feature in the next release or on the demo site, and let me know if you encounter any problems!

I simply cut away the middle of the string when it's too long.

**Comment by Ditti4** [comment]
I mean, it's a little better, but on the demo site it still looks quite awkward: https://i.imgur.com/5B066BW.png

The breadcrumbs on the right are

Home > Expenses > A transaction with a very long descri ... d to make the breadcrumbs look awkward > Edit transaction "A transaction with a very long description which used to make the breadcrumbs look awkward"

... while the title of the page says

Transactions > Edit transaction "A transaction with a very long description which used to make the breadcrumbs look awkward"

**Comment by JC5** [comment]
Oh good find I forgot about those “action”-titles. Keep me posted if you find others, and I’ll keep an eye out as well.
