### ISSUE TITLE
Remaining budget over per day is calculated wrong

### ISSUE THREAD

**Issue by paul999** [firefly-iii/firefly-iii#1598]
**Bug description**
I am running Firefly III version develop branch

The remaining budget per day is calculated wrong: 
![image](https://user-images.githubusercontent.com/65767/43781749-f46a517c-9a5d-11e8-8eee-96903d6db9b3.png)
It looks like it uses for both spent as remaining the same number of days, and more specificly the days the month is old.

**Steps to reproduce**
Create a budget and validate the correctness of remaining budget a day.

**Comment by paul999** [comment]
https://github.com/firefly-iii/firefly-iii/blob/develop/resources/views/budgets/index.twig#L197 seems to use the same variable as https://github.com/firefly-iii/firefly-iii/blob/develop/resources/views/budgets/index.twig#L191 which I think is incorrect? The one on 197 should be (numberOfDaysInMonth - DaysLeft) ?

**Comment by JC5** [comment]
Alright, I've pushed some fixes to the develop-branch. The code was a bit messy. Could you check it out?

The amount spent per day should be x / 7 (since it's the 7th day of the month) and the amount left per day should be x / 24.

**Comment by JC5** [comment]
New release is live. Please open a new ticket when the problem persists. Thanks!
