### ISSUE TITLE
Add an easier way to set a budget for a revenue/income transaction

### ISSUE THREAD

**Issue by Ditti4** [firefly-iii/firefly-iii#1599]
**Description**
Setting a budget for a revenue transaction can be pretty useful if you split the cost for something with a friend or family member, like a Netflix subscription.

However, there is no easy way of setting a budget for a revenue transaction as there's no combo box on the "Create" and "Edit" screens. If you go back to the overview of all revenue transactions though, you can clearly see that there is a column for this.

**Solution**
A combo box should be added to the "Create" and "Edit" screens, just like it's done for withdrawals

**What are alternatives?**
You can currently set a budget for a revenue transaction using the bulk edit feature. That is the only way known to me to accomplish this.

**Comment by JC5** [comment]
Budgets are exclusive to expenses, since you budget your expenses. You reserve an _x_ amount for bills or groceries and see if you can spend less than that.

Income isn't tied to a specific budget. I am not sure what budgeting incoming money would accomplish exactly? Do you want the income to enlarge the budget? Do you want it to show that you spent less on the budget?

Setting a budget through the bulk editor is a bug, and will be fixed in the next release.

**Comment by Ditti4** [comment]
I'm sharing a Netflix account with friends and am responsible for handling the finances. So once a month, Netflix takes 13.99€ out of my account, which I assign to a certain budget, and my friends' shares enter my account, which I'd like to assign to the same budget.

Essentially what I'd like to achieve is that Firefly doesn't think I spent 13.99€ on that budget already, but rather my share of the 13.99€. The budgeted amount would stay the same, the amount I spent would just be reduced.

But if that's not a use case in your opinion, then I'll adjust my workflow and just assign a larger budget. I get your point of view as well, I think I had just been using YNAB for too long. 😉 

But I'm glad I was able to report that bug! 😄

**Comment by JC5** [comment]
Ah yes, that's more of a YNAB way of thinking indeed. Firefly III takes the long way around: you'll have to expand the budget so you can bear the full cost of the subscription _and_ take the extra income into account when budgeting.

It's just a way of thinking: you take any income, [store it on your savings account](http://firefly-iii.readthedocs.io/en/latest/about/grand-theory.html), and use it to fill your budgets for next month.
