### ISSUE TITLE
Move firefly-iii from http://localhost/ to  http://localhost/finance

### ISSUE THREAD

**Issue by Odyno** [firefly-iii/firefly-iii#1600]
First of all, very good work! 
I'm very happy with this application and I want to move from my local solution to my small home cloud! 

I am running Firefly III github master version, and I built the docker image... all work fine, but I want to add this service near the others... hide it behind my nginx reverse proxy, maybe behind the /finance endpoint.

The problem I'm facing is changing the apache configuration (inside the docker) to move firefly-iii from the **/** to the **/finance**  alias or dir.  I always have error 404 on /finance and it work perfectly on the /

I wondered if I forgot some configuration in the project... can You tell me something... in the documentation or a procedure, or an example of how to make it? I found nothing and it would be very useful

thanks

**Comment by JC5** [comment]
If you are running a single docker container for the firefly app, the configuration should be on the reverse proxy and not on Apache. 

Apache runs happily on https://10.0.3.10/ (or something) while nginx pushes this (as a reverse proxy) to https://example.com/finance.

**Comment by Odyno** [comment]
Sorry, probably I did not understand.

With the current configuration I have the follow beaviewr:

* Nginx forward the request from http://localhost/finance  --> http://localhost:9080/
* Apache make the redirect to *login*
* At this point I have the below page generated and provided and then http://locahost/finance/login

<img width="912" alt="screen shot 2018-08-10 at 14 31 40" src="https://user-images.githubusercontent.com/1727138/43958027-43201830-9caa-11e8-9d53-f5ff2d79fff4.png">

and on the source I see the "/" in any reference of assets.

Do not know if they are in error but... what I think is that also the container should respond on /finance so it can redirect to login and produce the right references in html content.... Am I making a mistake?

**Comment by JC5** [comment]
Ah yes. You can find some hints in the documentation: http://firefly-iii.readthedocs.io/en/latest/installation/docker.html#supported-docker-environment-variables

And in the closed issues if you search for "reverse proxy".

**Comment by Odyno** [comment]
ok... I used the old, trivial and dirty way... I created the directory and moved everything there... and fixed the require on the index.php

now all work fine :) thanks
