### ISSUE TITLE
Sankey Diagram support.

### ISSUE THREAD

**Issue by triDcontrols** [firefly-iii/firefly-iii#1601]
**Description**
Add Sankey Diagaram to better visualize where the finances are coming into and leaving accounts. 

**Solution**
Current charts are ok, but having a sankey diagram I believe would add better clarity of fiances coming and leaving accounts.

**Additional context**
Here's an example. 

https://www.reddit.com/r/dataisbeautiful/comments/9628fb/oc_my_monthly_budget_while_earning_30k_gross/

![capture](https://user-images.githubusercontent.com/22411662/43966109-e13078a6-9c75-11e8-80e4-ee55310f95ce.PNG)

**Comment by JC5** [comment]
Yes, good idea! It’s on the list!

**Comment by JC5** [comment]
Sorry, I'm not going to build this any time soon.
