### ISSUE TITLE
Missing parameter in adding bill documentation 

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#1604]
**Bug description**
I am running Firefly III version 4.7.5

When adding a new bill via Firefly API, I am faced with the following error. 
`
{
    "message": "The given data was invalid.",
    "errors": {
        "currency_id": [
            "The currency id field is required when currency code is not present."
        ],
        "currency_code": [
            "The currency code field is required when currency id is not present."
        ]
    }
}
`
The documentation for updating [bills](http://firefly-iii.readthedocs.io/en/latest/api/bills.html) does not indicate anything with regards to currency.

**Comment by JC5** [comment]
Nice find, I've updated the docs :+1:. If you see things like this, don't hesitate to follow the [GitHub](https://github.com/firefly-iii/docs/blob/master/docs/api/bills.rst) link and edit the page yourself.
