### ISSUE TITLE
Not Installing

### ISSUE THREAD

**Issue by Kyle9982** [firefly-iii/firefly-iii#1606]
I am trying to install you program

I keep getting a "Error 500" on my browser

This is what I grabbed from my logs

[2018-08-12 23:36:54] local.ERROR: Class hash does not exist {"exception":"[object] (ReflectionException(code: -1): Class hash does not exist at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:767)
[stacktrace]
#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('hash')
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build('hash')
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('hash', Array)
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\\Container\\Container->make('hash', Array)
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(1210): Illuminate\\Foundation\\Application->make('hash')
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php(82): Illuminate\\Container\\Container->offsetGet('hash')
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php(40): Illuminate\\Auth\\AuthManager->createEloquentProvider(Array)
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(121): Illuminate\\Auth\\AuthManager->createUserProvider('users')
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(94): Illuminate\\Auth\\AuthManager->createSessionDriver('web', Array)
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\\Auth\\AuthManager->resolve('web')
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(292): Illuminate\\Auth\\AuthManager->guard()
#11 /var/www/firefly-iii/app/Exceptions/Handler.php(127): Illuminate\\Auth\\AuthManager->__call('check', Array)
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): FireflyIII\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#14 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#15 {main}
"}
What am I doing wrong??

**Comment by JC5** [comment]
I need more info. What system are you installing on? Which step in the guide are you getting this error?

**Comment by Kyle9982** [comment]
I am running Ubuntu Server 16.04.5 LTS. I have followed every step on your doc website. 
I have gotten all the way up to building the database and still no luck on getting anything to load. The root index.php page loads, but when redirected to /public/, that is when I get the Error 500

**Comment by Kyle9982** [comment]
Also, this is my .env file. Is there anything else I am supposed to edit??

# You can leave this on "local". If you change it to production most console commands will ask for extra confirmation.
# Never set it to "testing".
APP_ENV=local

# Set to true if you want to see debug information in error screens.
APP_DEBUG=false

# This should be your email address
SITE_OWNER=mail@example.com

# The encryption key for your database and sessions. Keep this very secure.
# If you generate a new one all existing data must be considered LOST.
# Change it to a string of exactly 32 chars or use command `php artisan key:generate` to generate it
APP_KEY=********************************************************************

# Change this value to your preferred time zone.
# Example: Europe/Amsterdam
TZ=UTC

# APP_URL and TRUSTED_PROXIES are useful when using Docker and/or a reverse proxy.
APP_URL=https://www.customcloud.ca/firefly
TRUSTED_PROXIES=

# The log channel defines where your log entries go to.
LOG_CHANNEL=daily

# Database credentials. Make sure the database exists. I recommend a dedicated user for Firefly III
# For other database types, please see the FAQ: http://firefly-iii.readthedocs.io/en/latest/support/faq.html
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=firefly-iii
DB_USERNAME=root
DB_PASSWORD=*************** (Not Real Password)

# 'daily' is the default logging mode giving you 5 daily rotated log files in /storage/logs/.
# Several other options exist. You can use 'single' for one big fat error log (not recommended).
# Also available are 'syslog' and 'errorlog' which will log to the system itself.
APP_LOG=daily

# Log level. You can set this from least severe to most severe:
# debug, info, notice, warning, error, critical, alert, emergency
# If you set it to debug your logs will grow large, and fast. If you set it to emergency probably
# nothing will get logged, ever.
APP_LOG_LEVEL=notice

# If you're looking for performance improvements, you could install memcached.
CACHE_DRIVER=file
SESSION_DRIVER=file

# Cookie settings. Should not be necessary to change these.
COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false

# If you want Firefly III to mail you, update these settings
# For instructions, see: https://firefly-iii.readthedocs.io/en/latest/installation/mail.html
MAIL_DRIVER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_FROM=changeme@example.com
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

# Other mail drivers:
MAILGUN_DOMAIN=
MAILGUN_SECRET=
MANDRILL_SECRET=
SPARKPOST_SECRET=

# Firefly III can send you the following messages
SEND_REGISTRATION_MAIL=true
SEND_ERROR_MESSAGE=true

# Set a Mapbox API key here (see mapbox.com) so there might be a map available at various places.
MAPBOX_API_KEY=

# Set a Fixer IO API key here (see https://fixer.io) to enable live currency exchange rates.
# Please note that this will only work for paid fixer.io accounts because they severly limited
# the free API up to the point where you might as well offer nothing.
FIXER_API_KEY=

# If you wish to track your own behavior over Firefly III, set a valid analytics tracker ID here.
ANALYTICS_ID=

# Most parts of the database are encrypted by default, but you can turn this off if you want to.
# This makes it easier to migrate your database. Not that some fields will never be decrypted.
USE_ENCRYPTION=true

# Leave the following configuration vars as is.
# Unless you like to tinker and know what you're doing.
APP_NAME=FireflyIII
BROADCAST_DRIVER=log
QUEUE_DRIVER=sync
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
CACHE_PREFIX=firefly
SEARCH_RESULT_LIMIT=50
PUSHER_KEY=
PUSHER_SECRET=
PUSHER_ID=
DEMO_USERNAME=
DEMO_PASSWORD=
IS_DOCKER=false
IS_SANDSTORM=false
BUNQ_USE_SANDBOX=false
IS_HEROKU=false
MAILGUN_DOMAIN=
MAILGUN_SECRET=

**Comment by Kyle9982** [comment]
Sorry to bother, but one more thing.

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);
Note: When I add die(); here I get a white page
$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);
Note: When I add die(); here I get the error 500
$response->send();

$kernel->terminate($request, $response);

**Comment by JC5** [comment]
Alright, so if it works until the database:

- You have installed composer
- You were able to run this command: `composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.7.5.3`
-This command breaks: `php artisan migrate:refresh --seed`.

What is the output of `php -v`?

**Comment by Kyle9982** [comment]
kyle@CUSTOMCLOUD:~$ php -v
PHP 7.2.8-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 25 2018 10:51:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.8-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

kyle@CUSTOMCLOUD:~$ composer
Composer version 1.7.1 2018-08-07 09:39:23

Here is my command console output from start to finish

kyle@CUSTOMCLOUD:/var/www$ composer create-project grumpydictator/firefly-iii --                                                                             no-dev --prefer-dist firefly-iii 4.7.5.3
Cannot create cache directory /home/kyle/.composer/cache/repo/https---repo.packa                                                                             gist.org/, or directory is not writable. Proceeding without cache
Installing grumpydictator/firefly-iii (4.7.5.3)
Cannot create cache directory /home/kyle/.composer/cache/files/, or directory is                                                                              not writable. Proceeding without cache
  - Installing grumpydictator/firefly-iii (4.7.5.3): Downloading (100%)
Created project in firefly-iii
Cannot create cache directory /home/kyle/.composer/cache/repo/https---repo.packa                                                                             gist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/kyle/.composer/cache/files/, or directory is                                                                              not writable. Proceeding without cache
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php -r "if (!(getenv('DYNO'))===false){file_exists('.env') || copy('.env.hero                                                                             ku', '.env');}"
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 62 installs, 0 updates, 0 removals
  - Installing bacon/bacon-qr-code (1.0.3): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)
  - Installing bunq/sdk_php (dev-master 8c1faef): Downloading (100%)
  - Installing vlucas/phpdotenv (v2.5.0): Downloading (100%)
  - Installing symfony/css-selector (v4.1.2): Downloading (100%)
  - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.8.0): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.8.0): Downloading (100%)
  - Installing symfony/var-dumper (v4.1.2): Downloading (100%)
  - Installing symfony/routing (v4.1.2): Downloading (100%)
  - Installing symfony/process (v4.1.2): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.8.0): Downloading (100%)
  - Installing symfony/http-foundation (v4.1.2): Downloading (100%)
  - Installing symfony/event-dispatcher (v4.1.2): Downloading (100%)
  - Installing psr/log (1.0.2): Downloading (100%)
  - Installing symfony/debug (v4.1.2): Downloading (100%)
  - Installing symfony/http-kernel (v4.1.2): Downloading (100%)
  - Installing symfony/finder (v4.1.2): Downloading (100%)
  - Installing symfony/console (v4.1.2): Downloading (100%)
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)
  - Installing egulias/email-validator (2.1.4): Downloading (100%)
  - Installing swiftmailer/swiftmailer (v6.1.2): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.17): Downloading (100%)
  - Installing ramsey/uuid (3.8.0): Downloading (100%)
  - Installing psr/simple-cache (1.0.1): Downloading (100%)
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing symfony/translation (v4.1.2): Downloading (100%)
  - Installing nesbot/carbon (1.25.0): Downloading (100%)
  - Installing monolog/monolog (1.23.0): Downloading (100%)
  - Installing league/flysystem (1.0.45): Downloading (100%)
  - Installing erusev/parsedown (1.7.1): Downloading (100%)
  - Installing dragonmantank/cron-expression (v2.2.0): Downloading (100%)
  - Installing doctrine/inflector (v1.3.0): Downloading (100%)
  - Installing laravel/framework (v5.6.29): Downloading (100%)
  - Installing davejamesmiller/laravel-breadcrumbs (5.1.0): Downloading (100%)
  - Installing doctrine/event-manager (v1.0.0): Downloading (100%)
  - Installing doctrine/cache (v1.7.1): Downloading (100%)
  - Installing doctrine/dbal (v2.8.0): Downloading (100%)
  - Installing fideloper/proxy (4.0.0): Downloading (100%)
  - Installing zendframework/zend-diactoros (1.8.3): Downloading (100%)
  - Installing symfony/psr-http-message-bridge (v1.0.2): Downloading (100%)
  - Installing phpseclib/phpseclib (2.0.11): Downloading (100%)
  - Installing league/event (2.1.2): Downloading (100%)
  - Installing lcobucci/jwt (3.2.2): Downloading (100%)
  - Installing defuse/php-encryption (v2.2.1): Downloading (100%)
  - Installing league/oauth2-server (6.1.1): Downloading (100%)
  - Installing firebase/php-jwt (v5.0.0): Downloading (100%)
  - Installing laravel/passport (v5.0.3): Downloading (100%)
  - Installing laravelcollective/html (v5.6.10): Downloading (100%)
  - Installing league/commonmark (0.17.5): Downloading (100%)
  - Installing league/csv (9.1.4): Downloading (100%)
  - Installing league/fractal (0.17.0): Downloading (100%)
  - Installing paragonie/constant_time_encoding (v2.2.2): Downloading (100%)
  - Installing symfony/polyfill-util (v1.8.0): Downloading (100%)
  - Installing symfony/polyfill-php56 (v1.8.0): Downloading (100%)
  - Installing pragmarx/google2fa (v3.0.1): Downloading (100%)
  - Installing pragmarx/google2fa-laravel (v0.2.0): Downloading (100%)
  - Installing twig/twig (v1.35.4): Downloading (100%)
  - Installing rcrowe/twigbridge (v0.9.6): Downloading (100%)
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> php artisan firefly:instructions install
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v4.7.5.3!                              |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
> @php artisan key:generate
Application key ******************************************************************** set successfully.
kyle@CUSTOMCLOUD:/var/www$ vi firefly-iii/.env
kyle@CUSTOMCLOUD:/var/www$ php artisan migrate:refresh --seed
Could not open input file: artisan
kyle@CUSTOMCLOUD:/var/www$ cd firefly-iii
kyle@CUSTOMCLOUD:/var/www/firefly-iii$ php artisan migrate:refresh --seed
Migration table not found.
Migration table created successfully.
Migrating: 2016_06_16_000000_create_support_tables
Migrated:  2016_06_16_000000_create_support_tables
Migrating: 2016_06_16_000001_create_users_table
Migrated:  2016_06_16_000001_create_users_table
Migrating: 2016_06_16_000002_create_main_tables
Migrated:  2016_06_16_000002_create_main_tables
Migrating: 2016_08_25_091522_changes_for_3101
Migrated:  2016_08_25_091522_changes_for_3101
Migrating: 2016_09_12_121359_fix_nullables
Migrated:  2016_09_12_121359_fix_nullables
Migrating: 2016_10_09_150037_expand_transactions_table
Migrated:  2016_10_09_150037_expand_transactions_table
Migrating: 2016_10_22_075804_changes_for_v410
Migrated:  2016_10_22_075804_changes_for_v410
Migrating: 2016_11_24_210552_changes_for_v420
Migrated:  2016_11_24_210552_changes_for_v420
Migrating: 2016_12_22_150431_changes_for_v430
Migrated:  2016_12_22_150431_changes_for_v430
Migrating: 2016_12_28_203205_changes_for_v431
Migrated:  2016_12_28_203205_changes_for_v431
Migrating: 2017_04_13_163623_changes_for_v440
Migrated:  2017_04_13_163623_changes_for_v440
Migrating: 2017_06_02_105232_changes_for_v450
Migrated:  2017_06_02_105232_changes_for_v450
Migrating: 2017_08_20_062014_changes_for_v470
Migrated:  2017_08_20_062014_changes_for_v470
Migrating: 2017_11_04_170844_changes_for_v470a
Migrated:  2017_11_04_170844_changes_for_v470a
Migrating: 2018_01_01_000001_create_oauth_auth_codes_table
Migrated:  2018_01_01_000001_create_oauth_auth_codes_table
Migrating: 2018_01_01_000002_create_oauth_access_tokens_table
Migrated:  2018_01_01_000002_create_oauth_access_tokens_table
Migrating: 2018_01_01_000003_create_oauth_refresh_tokens_table
Migrated:  2018_01_01_000003_create_oauth_refresh_tokens_table
Migrating: 2018_01_01_000004_create_oauth_clients_table
Migrated:  2018_01_01_000004_create_oauth_clients_table
Migrating: 2018_01_01_000005_create_oauth_personal_access_clients_table
Migrated:  2018_01_01_000005_create_oauth_personal_access_clients_table
Migrating: 2018_03_19_141348_changes_for_v472
Migrated:  2018_03_19_141348_changes_for_v472
Migrating: 2018_04_07_210913_changes_for_v473
Migrated:  2018_04_07_210913_changes_for_v473
Migrating: 2018_04_29_174524_changes_for_v474
Migrated:  2018_04_29_174524_changes_for_v474
Migrating: 2018_06_08_200526_changes_for_v475
Migrated:  2018_06_08_200526_changes_for_v475
Seeding: AccountTypeSeeder
Seeding: TransactionCurrencySeeder
Seeding: TransactionTypeSeeder
Seeding: PermissionSeeder
Seeding: LinkTypeSeeder
Seeding: ConfigSeeder
kyle@CUSTOMCLOUD:/var/www/firefly-iii$ php artisan firefly:upgrade-database
Updating currency information..
Done updating currency information..
Firefly III database is up to date.
kyle@CUSTOMCLOUD:/var/www/firefly-iii$ php artisan firefly:verify
No orphaned transactions!
No orphaned journals!
All link types OK!
All access tokens OK!
Amount integrity OK!
kyle@CUSTOMCLOUD:/var/www/firefly-iii$ php artisan passport:install
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 1
Client Secret: ***************************************************
Password grant client created successfully.
Client ID: 2
Client Secret: ******************************************************
kyle@CUSTOMCLOUD:/var/www/firefly-iii$

**Comment by Kyle9982** [comment]
https://www.customcloud.ca/firefly/pi.php

Go ahead and check it out

**Comment by JC5** [comment]
Found the problem. Apache is configured to use PHP7.0, while your command line is using PHP7.2.

I think you (still) have an installation of PHP7.0 linked to Apache. Checkout the configuration files for Apache on how to change this. 

I guess there's a reference to `/etc/php/7.0` somewhere.

**Comment by Kyle9982** [comment]
Still running across the issue here. Any other suggestions

**Comment by JC5** [comment]
Nope, sorry. If this is still giving you problems, I'm pretty much out of ideas ☹️

**Comment by Kyle9982** [comment]
Now when I load the page it redirects me too /login. And says that the page can not be found

**Comment by JC5** [comment]
That's a good sign! Try `sudo a2enmod rewrite` and then `sudo service apache2 restart`.

**Comment by Kyle9982** [comment]
THANK YOU!!!!!

In addition I realised the permissions were set to my user "kyle", so I changed them to "www-data"

And added the following to my apache2 configuration

<Directory "/var/www/html/firefly-iii">
       Allowoverride ALL
</Directory>

**Comment by Kyle9982** [comment]
One last thing. Where can I donate :)

**Comment by JC5** [comment]
:grin: I'm glad to see it works!

You can donate through [PayPal](https://www.paypal.com/donate/?token=Nbg90tSLT4vS6BzIvtpRmVDRAy-tMkTBvT91xBz37N3cPxm0UpAHPKKd_WDSpRfigxK4rm&country.x=US&locale.x=US) :+1:
