### ISSUE TITLE
Typo in command line output

### ISSUE THREAD

**Issue by caseybecking** [firefly-iii/firefly-iii#1608]
**Bug description**
There is a very small typo in the commandline output when running a create-import

**Steps to reproduce**
php artisan firefly:create-import file.csv config.json --start --token=<token>

**Extra info**
Nothing extra just a simple typo -
`The has started.`
```Going to create a job to import file: /tmp/transactions.csv
Using configuration file: /tmp/config.json
Import into user: #1 (derp@derp.com)
Type of import: file
Created job "REMOVED"
File content saved.
Job configuration saved.
The has started. The process is not visible. Please wait.

**Comment by JC5** [comment]
Nice find! Attention for details :+1:

I've submitted a fix for the next release.

**Comment by caseybecking** [comment]
Thank you!
