### ISSUE TITLE
Bug in a link

### ISSUE THREAD

**Issue by Kyle9982** [firefly-iii/firefly-iii#1609]
**Bug description**
I am running Firefly III version 4.7.5.3

Error in a link
https://www.example.ca/firefly/ is my root directory

**Steps to reproduce**
https://www.example.ca/firefly/transactions/create/withdrawal

Under the "Optional meta data" Section
If you click the "<a>Budget</a>" tag, it redirects to https://www.example.ca/budget, not https://www.example.ca/firefly/budget

![1](https://user-images.githubusercontent.com/42327407/44108234-a23ffe96-9fae-11e8-827b-617624f1b1db.png)

**Comment by JC5** [comment]
Nice find! It's a hard coded link so yes, it fails on subdirectories. 

I've pushed a fix (above my reply). It'll be available with the next release, hopefully end of this month.
