### ISSUE TITLE
Time/date error

### ISSUE THREAD

**Issue by Kyle9982** [firefly-iii/firefly-iii#1618]
I am running Firefly III version 4.5.7.3

Today is August 16th @ 19:10. But FireFly says that it is the 17th.
Is there a timezone setting or any suggestions on syncing it to my server

Running Ubuntu Server 18.?? (I don't know yet, just updated)

**Comment by JC5** [comment]
Check out your `.env` file. The default timezone is UTC, where it was 17 Aug, 03:12 when you posted this issue. :wink:
