### ISSUE TITLE
Changing the z-index

### ISSUE THREAD

**Issue by Kyle9982** [firefly-iii/firefly-iii#1619]
Just a little design input. For the smaller pie charts it is sometimes hard to read due to the layers I think. If you could increase the z-index on the floating content that would be great 
![untitled](https://user-images.githubusercontent.com/42327407/44246794-f2784480-a194-11e8-94ce-4932e9cd9a6d.png)

**Comment by JC5** [comment]
Not sure if I can, I'll play around with it :+1:

**Comment by JC5** [comment]
I tried everything but I couldn't improve it much. Sorry about that. A new layout I'm working on should fix this.
