### ISSUE TITLE
can I set the bills to repeat in 2 Months?

### ISSUE THREAD

**Issue by Odyno** [firefly-iii/firefly-iii#1621]
Hello again... :-) I have a simple question... on my version of Firefly III 4.7.5.3 can I set the bills to repeat in 2 Months? here in Italy is very common

**Comment by JC5** [comment]
Yes, that's possible. Just set the "Salta ogni" to 1, so it will skip ever 1 month. This will effectively make it repeat every two months.

**Comment by Odyno** [comment]
Perfect! thanks
