### ISSUE TITLE
Unlink  transaction from a bill

### ISSUE THREAD

**Issue by Odyno** [firefly-iii/firefly-iii#1622]
Hi,
is it possible to disconnect a transaction from a bill? 

I have noticed that the rule has categorised a transaction as a part of bill. I know that I can delete the transaction but I would like to keep it as an outgoing account and not counted as a bill.

is it possible?

**Comment by JC5** [comment]
At the moment, it isn't. It's a "gap" in the code. It used to be so that running the rule again would disconnect the transactions that do not match but it's currently not the case. I'll build something for the next release. Thanks for pointing this out!

**Comment by JC5** [comment]
This will be possible in the next release.
