### ISSUE TITLE
Fields after creating a new category/expense/transactions aren't set to null

### ISSUE THREAD

**Issue by yvovandoorn** [firefly-iii/firefly-iii#1625]
**Bug description**
I am running Firefly III version 4.7.5.3

When wanting to create a new expense account/transaction/category and you have the option "After storing, return here to create another one." enabled, I would expect the fields to be returned to null after a successful save. 

**Steps to reproduce**
Click on Create Categories or Expense Account
Make sure the option "After storing, return here to create another one." is enabled
When you click on Save, the previous values are still present. 

**Extra info**
Chrome 69 on Mac OS X (client)
Ubuntu 18.04 + nginx + php 7.2 (server)

Debug information generated at 2018-08-22 11:48:50 Europe/Amsterdam for Firefly III version **4.7.5.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.5.3 |
| FF API version | 0.6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.2.7-0ubuntu0.18.04.2 |
| Display errors | Off |
| Session start | 2018-08-01 00:00:00 |
| Session end | 2018-08-31 23:59:59 |
| Session first | 2017-12-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.42 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.7.1, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.29, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.2, symfony/css-selector@v4.1.2, symfony/debug@v4.1.2, symfony/event-dispatcher@v4.1.2, symfony/finder@v4.1.2, symfony/http-foundation@v4.1.2, symfony/http-kernel@v4.1.2, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.2, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.2, symfony/translation@v4.1.2, symfony/var-dumper@v4.1.2, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.0, zendframework/zend-diactoros@1.8.3,  |
<img width="1406" alt="create_a_new_expense_account_ _accounts_ _firefly_iii" src="https://user-images.githubusercontent.com/2694655/44456680-7ef58d80-a601-11e8-8361-233dc798d6a4.png">

**Comment by JC5** [comment]
Wow! Ten points for the expansive bug report!

What you have reported however, is intended behavior. Most (if not all) forms do this so you can quickly create successive transactions or entries.

So it's not a bug.. it's a feature ™

**Comment by yvovandoorn** [comment]
Ah so there should be a feature to turn off this behavior (maybe another checkbox under options) because I was rapidly adding different expense accounts and found my workflow was actually faster to store -> go back to main screen -> add new versus clicking the checkbox and then wiping the old content.

**Comment by JC5** [comment]
What you see is what you get I’m afraid. There won’t be an option to disable the auto refill.
