### ISSUE TITLE
[Feature Request] Allow users to sort Piggy bank

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#1626]
**Description**
Please describe your feature request:

Currently the API doesn't allow you to sort and filter out your piggy banks when you have saved up enough. 

**Solution**
Lesser clutter since I'm not concerned about completed piggy banks

**Comment by JC5** [comment]
I've written it down. Not sure yet when I can deliver though.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947513
