### ISSUE TITLE
Change transaction type

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#1627]
I am running Firefly III version 4.7.5.3

I would like to change the type of my transaction. I imported a few deposits/withdraws that are actually a transfer between those accounts. The problem is that I cannot find a way to change a deposit or withdraw to be a Transfer.

**Comment by iwalucas** [comment]
I can't find this option. Here is what I see.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/3654783/44479914-4f9e4b00-a618-11e8-90c8-1939c4c1e112.png">

**Comment by JC5** [comment]
Check out the /show/ page.

**Comment by iwalucas** [comment]
perfect! Found it there... is there a way to bulk change this?

**Comment by JC5** [comment]
Nope, I'm afraid not.
