### ISSUE TITLE
Can't upgrade with docker-compose

### ISSUE THREAD

**Issue by Sudiukil** [firefly-iii/firefly-iii#1628]
[1]: https://firefly-iii.readthedocs.io/en/latest/installation/docker.html#docker-hub-with-automatic-updates-via-docker-compose
[2]: https://firefly-iii.readthedocs.io/en/latest/installation/upgrading.html#docker-hub-via-docker-compose

I can't upgrade my self-hosted Firefly installation from v4.7.2.2 to v4.7.5.3.

Firefly was installed with docker-compose, following [this documentation][1].

To upgrade, I followed [these instructions][2].

When I run `docker-compose restart firefly_app_iii` the container is just restarted and no upgrade is done.

**Additional note**

The [upgrade guide][2] states to run `docker-compose restart firefly-app` but the correct container name seems to be 'firefly_iii_app', it was easy to figure out but I think the docs should be updated to fix this.

**Comment by JC5** [comment]
You're right, that's a mistake!

The correct command is: 

`docker-compose pull firefly_iii_app && docker-compose restart firefly_iii_app`.

I've updated the documentation to reflect this. Thanks!

**Comment by Sudiukil** [comment]
Thanks for the quick reply!

I tried those two commands but my container is still not updated. I ran `docker images` and `docker ps` and noticed that the running 'firefly_iii_app` container still uses the old version, even if the new one was indeed pulled.

**Comment by JC5** [comment]
As far as I can find on Google, this is happening to more people. They suggest the following routine:

```
docker-compose stop
docker-compose rm -f
docker-compose pull   
docker-compose up -d
```

Could be that you need to add `firefly_iii_app`, so something like this:

```
docker-compose stop firefly_iii_app
docker-compose rm -f firefly_iii_app
docker-compose pull firefly_iii_app
docker-compose up -d firefly_iii_app
```

This routine may delete your volumes as well, so make sure you back those up.  I can't experiment for you so use at your own risk.

**Comment by Sudiukil** [comment]
I tried something similar to rebuild the containers: `docker-compose down`! But upon rebuilding (`docker-compose up -d`) I lost access to the database for some unknown reason. Anyway, I have a backup of the database so I went for a full reinstall: I removed everything (images, containers, volumes and network), dowloaded the latest *docker-compose.yml*, but I run into the same database error when running the migrations:

```
In Connection.php line 664:
                                                                                                                    
  SQLSTATE[HY000] [1044] Access denied for user 'firefly'@'%' to database 'firefly' (SQL: select * from informatio  
  n_schema.tables where table_schema = firefly and table_name = migrations)                                         
                                                                                                                    

In PDOConnection.php line 50:
                                                                                     
  SQLSTATE[HY000] [1044] Access denied for user 'firefly'@'%' to database 'firefly'  
                                                                                     

In PDOConnection.php line 46:
                                                                                     
  SQLSTATE[HY000] [1044] Access denied for user 'firefly'@'%' to database 'firefly'

**Comment by Sudiukil** [comment]
Nevermind, it was an issue with my settings in the new *docker-compose.yml*!

**Comment by JC5** [comment]
Phew, glad to hear it is fixed! Such problems can be tricky to diagnose. I'm assuming it's working now?

I'll update the docs to reflect this.

**Comment by Sudiukil** [comment]
I now get an error after restoring my database backup, any tips on that?

The error:

```
An unknown error prevented Firefly III from executing the upgrade commands. Sorry.

Please read the official documentation about this, and upgrade by hand.
```

**Comment by JC5** [comment]
That's a rare one. 

Can you run the upgrade commands using docker compose?

```
docker-compose exec firefly_iii_app php artisan migrate --seed
docker-compose exec firefly_iii_app php artisan firefly:upgrade-database
docker-compose exec firefly_iii_app php artisan firefly:verify
docker-compose exec firefly_iii_app php artisan passport:install
```

**Comment by Sudiukil** [comment]
Well, I tried a full reinstall again and I simply restored my database right after running `docker-compose up` and that's working, it seems running migrations before doing a database restore breaks the database.

All is up and running now, thanks!

**Comment by JC5** [comment]
I apologise, I never replied!

Glad to see it's working! :+1:
