### ISSUE TITLE
Create sub categories

### ISSUE THREAD

**Issue by xXSTrikeXx** [firefly-iii/firefly-iii#1629]
Hello everbody.
Could it be possible to add sub categories like:

Flat -> DSL
Flat -> rental fee
Flat -> electricity
Free time -> books
Free time -> film
Free time -> cinema
Health -> pharmacy
Health -> hospital
Health -> insurance
Vacation -> Flight
Vacation -> hotel
Vacation -> sightseeing.

This will help a lot!

**Comment by JC5** [comment]
Hi! Thanks for your feature request!

Firefly III will not feature subcategories. Generally speaking, these do not add meaningful meta-data to your transactions. For further distinction, I would suggest the use tags.

**Comment by xXSTrikeXx** [comment]
I use tags for big categories. For example I want to know, how much my flat costs I use the tag "flat". But under the categories there are much more subcategories in connection with the categorie flat: electricity, rental fee, DSL, repairs, water, etc. .

**Comment by weslyth** [comment]
I too would love this.

**Comment by mikymigs** [comment]
Agreed! Sub categories are definitely meaningful. Today I have to create a category for each sub category, for example for car expenses, I have to create multiple categories "car - gas", "car - insurance", "car - maintenance" etc. It works but then I'm unable to have graph showing only high level categories. Everything is split in a granular way. And if I do the opposite and only create one "car" category, I loose the precision of being to see what proportion goes into gas and what part goes into insurance for example... 
I really hope sub categories will be implemented eventually...
I agree with @weslyth on the fact that only 1 sub level would be sufficient to cover the needs.

**Comment by JC5** [comment]
Please check out the category report under `/reports`.
