### ISSUE TITLE
PayPal in Firefly

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1630]
I am running Firefly III version latest

Hi,

I'm looking for the best way to add my Paypal transactions to m FireflyIII instance.
I have a Paypal account that is linked to my bank account, so each time I make a Paypal payment, my bank account is charged a few days later.
My back account is already present in Firefly, but the transactions of the withdrawals to Paypal (the company) are not very descriptive.
I would like to have my Paypal transactions in Firefly as well, without too much hassle.
I was thinking about the following solution:
1. Use the current way of entering transactions from my bank account into PayPal.
2. Create a rule that, whenever it detects a withdrawal to Paypal, changes it to a transfer to my (to be created) PayPal asset account.
3. Enter only the PayPal transactions that don't withdraw from my bank account, into Firefly. (That's possible using their CSV export filtering options).

This would work and keep all balances in tact, I think. The only thing is that in step 2, I can't change the type of a transaction in a rule.

Two questions: 
1. Does this sound like a good solution, or do you have better ideas? Any other PayPal users around?
2. Can you implement this rule action type to change a transaction type to a transfer?

**Comment by JC5** [comment]
Mmmm, I've been thinking about this but I haven't got a definitive solution for this.

Personally, I write down the expenses that Paypal takes from my bank accounts without Paypal as the middleman. So if I order from Amazon using Paypal I simply make a transaction between Checking Account <> Amazon. This removes Paypal as the payment method altogether.

This works only for EUR transactions though. I have a modest amount in USD on my Paypal account (from donations) which is used by Paypal if I spend USD: some hosting, some internet purchase. Those get "lost" in my current solution.

The rule action to change the type of a transaction has been requested before and I will write it down for sure.
