### ISSUE TITLE
Problem with Caddy as reverse proxy and https

### ISSUE THREAD

**Issue by matthinc** [firefly-iii/firefly-iii#1632]
I am running Firefly III version *latest*

**Description**

I use caddy as a reverse proxy for firefly_iii. The application itself is running in docker.
The docker-compose looks like that (already tried a few things):
```
...
environment:
      ...
      - APP_FORCE_ROOT=https://ffiii.<my domain>
      - APP_URL=https://ffiii.<my domain>
      - APP_FORCE_SSL=true
ports:
      - "8025:80"
...
```
The Caddyfile looks like that:
```
ffiii.<my domain> {
        proxy / localhost:8025 {
                transparent
        }
}
```
I can open the page in Chrome, the URL says https://... but all css, js... files are delivered via http.
Therefore the page looks very ugly.

I had a look in the html code and it inserts the line `<base href="http://ffiii.<my domain>/">` **not** https.

I'm not sure whether this is a configuration problem in caddy or firefly.

Thank you in advance!

**Comment by JC5** [comment]
APP_FORCE_SSL and APP_FORCE_ROOT are no longer part of Firefly III code. So those won't work I'm afraid. `APP_URL` is only used on the command line and in specific tasks.

But other than that, I have no idea I'm afraid. Docker + Caddy is a complete unknown for me.

**Comment by matthinc** [comment]
Hmm - nevertheless thank you for the fast response. I will have to do some research myself. There are some other people on reddit with the same problem. I will respond here, if I find a solution.

**Comment by tbrasser** [comment]
I have firefly and caddy running without problems, have you set trusted proxies to ** . ?
This is my caddy file entry for firefly:

`firefly.domain.tld {`
`    timeouts none`
`    proxy / 10.0.10.191 {`
`        websocket`
`        transparent`
`    }`
`}`

and the environment variables:
`APP_URL = firefly.domain.tld`
`TRUSTED_PROXIES = **`

**Comment by matthinc** [comment]
Nice, thank you very much @tbrasser!
`TRUSTED_PROXIES=**` Fixed it!

**Comment by JC5** [comment]
https://firefly-iii.readthedocs.io/en/latest/support/faq.html#i-can-t-seem-to-get-https-working-with-caddy
