### ISSUE TITLE
Automatic credit card refund transaction

### ISSUE THREAD

**Issue by fabiograz** [firefly-iii/firefly-iii#1633]
Hi,
I'm using firefly-iii (4.7.5.3) and found it a good work. 
I've configured a credit card account. In configuration form there is the refund due date.
It would be useful:
- connect a bank account to credit card (maybe empty) where at due date money will be charged
- at the due date firefly-iii make automatically a transfer transaction between linked bank account (if not empty, and checked) and credit card to refund all amount (like automatic transactions scheduled).

Thanks,
Fabio

**Comment by JC5** [comment]
I am glad you like Firefly III!

I must admit I am reluctant to build something like this. I know from experience (sadly) that banks can be very inconsistent in doing these transactions by themselves. Most banks prepare these automated transactions a few days in advance. And then the amount is different from Firefly III.

For the time being I would like to leave it like this. Perhaps I will even remove the due date from Firefly III. It's very useful to know about it, but it is very hard to make Firefly III respond to it consistently (for all users).
