### ISSUE TITLE
Credit card account due date

### ISSUE THREAD

**Issue by fabiograz** [firefly-iii/firefly-iii#1634]
Hi,
when I create an account of credit card type, after I save it, firefly-iii (4.7.5.3) report a error because due-date was not filled. 
The problem is these fields are not present in the form, and when I select credit card type for the account the form don't show these new fields.
The solution is to condition show these fields when is selected credit card in account type.
Thanks,
Fabio

**Comment by JC5** [comment]
Mmmm, I can't seem to reproduce this.

When I create an account on [this page](https://demo.firefly-iii.org/accounts/create/asset) I can create a credit card without any problems. Are you getting a different result?
