### ISSUE TITLE
Monzo (mobile bank) integration

### ISSUE THREAD

**Issue by captainhook** [firefly-iii/firefly-iii#1635]
**Description**
Please describe your feature request:

- I would like Firefly III to be able to [connect to Monzo using their API](https://docs.monzo.com/).
The API is designed for individual use, so it works very well in a Firefly environment.

**What are alternatives?**
Currently there is an option for Bunq which is brilliant to see. Monzo is very popular in the UK, along with Revolut, and Starling.

Revolut seems to only have an [API for their business accounts](https://www.revolut.com/business/openapi), and [Starling has an API](https://developer.starlingbank.com/) similar to Monzo's.

**Comment by JC5** [comment]
Look's great, it's on the list!

**Comment by ragnarkarlsson** [comment]
Chipping in my interest also, would be happy to alpha/beta test anything!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
