### ISSUE TITLE
Error 500 on Free

### ISSUE THREAD

**Issue by xorob0** [firefly-iii/firefly-iii#1636]
I am running Firefly III version 4.7.5.3 on FreeNas inside a jail. I have everything setup, the installation returned no errors but when I try to access Firefly-III it retrurns a error 500.
Here are the logs I could get

` 
 [21:04:26] local.ERROR: SQLSTATE[HY000] [1049] Unknown database 'home
stead' (SQL: select * from information_schema.tables where table_schema = homest
ead and table_name = migrations) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'homestead' (
SQL: select * from information_schema.tables where table_schema = homestead and 
table_name = migrations) at /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver
\\PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'homestead' 
at /usr/local/www/apache24/data/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DB
AL/Driver/PDOConnection.php:50, PDOException(code: 1049): SQLSTATE[HY000] [1049]
 Unknown database 'homestead' at /usr/local/www/apache24/data/firefly-iii/vendor
/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:46)                   
[stacktrace]                                                                    
#0 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumin
ate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCall
back('select * from i...', Array, Object(Closure))                              
#1 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumin
ate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from i...', Array, Object(Closure))                                           
#2 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumin
ate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->sele
ct('select * from i...', Array)                                                 
#3 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illuminte/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Databa
se\\Schema\\MySqlBuilder->hasTable('migrations')                                
#4 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumin
ate/Database/Migrations/Migrator.php(555): Illuminate\\Database\\Migrations\\Dat
abaseMigrationRepository->repositoryExists()                                    
#5 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumin
ate/Database/Console/Migrations/ResetCommand.php(63): Illuminate\\Database\\Migr
ations\\Migrator->repositoryExists()                                            
#6 [internal function]: Illuminate\\Database\\Console\\Migrations\\ResetCommand->handle()                                                                       
#7 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumin
ate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)           
#8 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumin
ate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminat
e\\Container\\{closure}()                                                       
#9 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumin
ate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBound
Method(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))     
#10 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Obje
ct(Illuminate\\Foundation\\Application), Array, Array, NULL)                    
#11 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Console/Command.php(184): Illuminate\\Container\\Container->call(Array)  #12 /usr/local/www/apache24/data/firefly-iii/vendor/symfony/console/Command/Comm
and.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\C
onsole\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))           
#13 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Console/Command.php(171): Symfony\\Component\\Console\\Command\\Command->ru
n(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Con
sole\\OutputStyle))                                                             
#14 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Console/Command.php(199): Illuminate\\Console\\Command->run(Object(Symfony\
\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle
))                                                                              
#15 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Database/Console/Migrations/RefreshCommand.php(107): Illuminate\\Console\\C
ommand->call('migrate:reset', Array)                                            
#16 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Database/Console/Migrations/RefreshCommand.php(55): Illuminate\\Database\\C
onsole\\Migrations\\RefreshCommand->runReset(NULL, NULL, false)                 
#17 [internal function]: Illuminate\\Database\\Console\\Migrations\\RefreshComma
nd->handle()                                                                    
#18 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)  nate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)          
#19 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illumina
te\\Container\\{closure}()                                                      
#20 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoun
dMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))    
#21 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Obje
ct(Illuminate\\Foundation\\Application), Array, Array, NULL)                    
#22 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Console/Command.php(184): Illuminate\\Container\\Container->call(Array)    
#23 /usr/local/www/apache24/data/firefly-iii/vendor/symfony/console/Command/Comm
and.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\C
onsole\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))            
#24 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Console/Command.php(171): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Cons
ole\\OutputStyle))                                                              
#25 /usr/local/www/apache24/data/firefly-iii/vendor/symfony/console/Application.
php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\
Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))  
#26 /usr/local/www/apache24/data/firefly-iii/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illumina
te\\Database\\Console\\Migrations\\RefreshCommand), Object(Symfony\\Component\\C
onsole\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOu
tput))                                                                          
#27 /usr/local/www/apache24/data/firefly-iii/vendor/symfony/console/Application.
php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Compon
ent\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\Con
soleOutput))                                                                    
#28 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(
Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component
\\Console\\Output\\ConsoleOutput))                                              
#29 /usr/local/www/apache24/data/firefly-iii/vendor/laravel/framework/src/Illumi
nate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(O
bject(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\
\Console\\Output\\ConsoleOutput))                                               
#30 /usr/local/www/apache24/data/firefly-iii/artisan(37): Illuminate\\Foundation
\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput),
 Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))                    
#31 {main}                                                                      
"}                                                                              
[2018-08-27 21:05:29] local.WARNING: No database version entry is present. Datab
ase is assumed to be OLD (version 1).   
`

What I did on the jail is install Apache and Mysql, set them up, and follow this guide https://firefly-iii.readthedocs.io/en/latest/installation/server.html
I can access http://servername/firefly-iii/public/js/app.js and http://servername/firefly-iii/ tells me:
Danger! This directory should not be open to the public!
/public/ should be the document root of your web server.
Leaving your web server configured like this is a huge security risk.
Please read more on the Github help pages.

Then redirects me to /public which return the error 500.

Thanks in advance for your help.

**Comment by JC5** [comment]
The log file indicates that the database doesn't exist. Can you run commands on a command prompt?
