### ISSUE TITLE
Single user on Heroku doesn't receive admin

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1638]
**Bug description**
I am running Firefly III version 4.7.5.3
And although I'm single user, I don't get admin.
I had to login with pgAdmin to the database to verify this (as API for /users require owner role)
I was the single user on users table. And the table role_user was empty.
I manually added row 1,1 (1st user id, 1st role [owner]), and everything worked.

**Steps to reproduce**
- Deploy on Heroku
- Set on Heroku SITE_OWNER to my email
- Set on Heroku TRUSTED_PROXIES to **
- (Had to follow "update guide" because installation failed - different issue)
- Register with SITE_OWNER email
- Login
- Try to add currency

**Extra info**
Debug information generated at 2018-08-28 05:47:28 UTC for Firefly III version **4.7.5.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.5.3 |
| FF API version | 0.6 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, errorlog |
| PHP version | 7.2.9 |
| Display errors | Off |
| Session start | 2018-08-01 00:00:00 |
| Session end | 2018-08-31 23:59:59 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, mbstring, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.7.1, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.29, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.2, symfony/css-selector@v4.1.2, symfony/debug@v4.1.2, symfony/event-dispatcher@v4.1.2, symfony/finder@v4.1.2, symfony/http-foundation@v4.1.2, symfony/http-kernel@v4.1.2, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.2, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.2, symfony/translation@v4.1.2, symfony/var-dumper@v4.1.2, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.0, zendframework/zend-diactoros@1.8.3,  |

**Comment by JC5** [comment]
Indeed. I have had users reporting this. Thanks for the extensive bug report. I am not yet sure what's happening. I'll keep you posted.

**Comment by JC5** [comment]
Alright I've just tested this and my Heroku installation gives out the admin rights correctly. I'm going to consider this one fixed and add it to the next release :+1:

**Comment by hamuz** [comment]
This is not fixed.

I followed instructions ("Heroku button") from https://firefly-iii.readthedocs.io/en/latest/installation/hosted.html .

First of all, I got the install to run smoothly once I added "my patch" (TRUSTED_PROXIES fix),
and didn't need to log in to dyno and do anything manually.  

Afterwards the bug exists. I tried to register and login, even later setting SITE_OWNER,
but that doesn't help to get owner (as it is only set on Register and Login event).

Attached ironical screenshot.

![image](https://user-images.githubusercontent.com/550499/44739553-c21f9700-ab00-11e8-9f45-1e6488c6ed89.png)

**Comment by JC5** [comment]
Apologies, I had to add the fact that I still have to release the next version. This is something I plan to do this weekend.

The message you see is a leftover from before Heroku was an option: the variable from the `.env` file is only used in messages like these: the expectation is that users would update their `.env` file and include their own email address. This would help other users of their own installation to find them.

The demo site has my address so people know where to find me.

Since Heroku instances are generally single-user and these single users are (should be) admin, this message is not making sense indeed.

I'll close this issue once the new release is live, then you can redeploy to Heroku.

**Comment by hamuz** [comment]
You deployed "develop" branch to heroku  and it was fixed?

**Comment by JC5** [comment]
Yes, what I do to test these things is the following (usually on a fresh vagrant machine):

```
heroku login
heroku create
git push heroku develop:master
```

Then I go to the new app on Heroku, and add the Postgres addon. I then open a console using the web interface and run `php artisan migrate:refresh --seed`.

That's enough to make it possible to visit the index, watch the installer run and register / login.

My new account is then admin, so I consider it fixed. I am not sure if I can get closer to the real thing without releasing a new version.

**Comment by hamuz** [comment]
Use this link to deploy develop branch:
https://heroku.com/deploy?template=https://github.com/firefly-iii/firefly-iii/tree/develop

**Comment by JC5** [comment]
Ah thanks! I completely forgot about that URL :grin:

**Comment by hamuz** [comment]
I re-tested using above URL. I can confirm that this issue is fixed in latest version, which I'm waiting for :P .
