### ISSUE TITLE
unRAID template

### ISSUE THREAD

**Issue by mrkanaly** [firefly-iii/firefly-iii#1640]
**Description**
unRAID is software stack that allows users to do easy virtualization and NAS hosting. There are "templates" that  can be created in the unRAID space for easy installation from the unRAID interface. i.e. check that none of your ports will conflict, and click done, and it will install your favorite application available via docker.

**Solution**
A Firefly iii unRAID template would be great, as it would make it easy for users on the platform to one click install Firefly iii and get going with it.

**Additional context**
[Unraid Community Applications](https://forums.unraid.net/topic/38582-plug-in-community-applications/)
[Repo of unRAID templates](https://github.com/binhex/docker-templates/tree/master/binhex)
[Community applications master list](https://rawgit.com/Squidly271/AppsThread/master/forumpost0.html)

**Comment by JC5** [comment]
Thanks, I appreciate the information and the background info. I can't promise anything for the next release but it's on the list!

**Comment by JC5** [comment]
Feel free to write something to support unraid, I won't be able to do so.
