### ISSUE TITLE
Import from PDF/HTML/Excel/txt

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1641]
**Description**
Please describe your feature request:

I would like Firefly III to be able to import transactions from PDF/HTML/Excel/txt (I know each should be seperate issue, the list is prioritized on my part). Some kind of table detection need to be in place. See working example in alternatives. Develop might include research phase of reversing unobfuscated C# code.

**Solution**
Describe what your feature would add to Firefly III.

This feature would make it easier to import transactions from PDF statements. Many of them are received in email now days, instead of standard post mail.

**What are alternatives?**
Please describe what alternatives currently exist.

Kaching download link:
https://bitbucket.org/hofesh/kaching-dl/downloads/KaChing.zip

Manual - google translated from Hebrew.
https://docs.google.com/document/d/1xHadktPMu4Y0-94D55M-oPZFFqkGdO4T9XikCjRdR04/edit?usp=sharing

**Additional context**

Click auto-import in [google doc](https://docs.google.com/document/d/1xHadktPMu4Y0-94D55M-oPZFFqkGdO4T9XikCjRdR04/edit?usp=sharing) outline.
I can provide such documents (PDF, HTML) in private for development and testing.

**Comment by JC5** [comment]
I am sorry, but Firefly III will not support importing free-format data such as PDF files or text files. Excel files can be converted to CSV and then imported into Firefly III.

**Comment by hamuz** [comment]
Why not? I envision some table detection, similar to Kaching, and then column matching step as present in Firefly-iii today.
Think about it - pdf + config.

**Comment by JC5** [comment]
It's a project in itself, proven by the existence of Kaching, to do this flawlessly. I just don't see the advantage of copying what other tools can do better and faster.

In my experience banks are incapable of delivering even CSV files in a consistent manner. I am not going to invite myself to the nightmare of trying to parse PDF files.

**Comment by hamuz** [comment]
I've found two options for implementing this functionality:
1. https://tabula.technology/ - Java (JVM) based open source (MIT license) which is capable of auto-detection of tables in pdfs and conversion to csv (for example) - which I've chosen to use for now for my use case.
2. Kaching internals revealed rather simple(-ish) handling of import.
It can be classified as a 2 step process:
a. First (in case of PDF) the text from the document is extracted, and tables are parsed from text similarly to TSV parsing.
b. Each column of the table is graded for matching some type (such as date/amount/currency/business name/additional info).

I think Kaching heuristics can be used in Firefly to suggest column types for the configuration.

**Comment by inc-ali** [comment]
Just extract the data from your banking statement into a csv by using Python for example. 

Banking statements vary greatly in structure, I don't think it's worth the effort to try to implement a tool for the masses.
