### ISSUE TITLE
Bug in linking transactions

### ISSUE THREAD

**Issue by cyliang** [firefly-iii/firefly-iii#1642]
**Bug description**
I am running Firefly III version 4.7.5.3

Server error when linking transactions by clicking `Options / Link transaction` and select a listed transaction. The error would not be produced if the ID of the linked transaction is manually filled in the field directly.

**Steps to reproduce**

1. View a transaction. (e.g. `/transactions/show/25`)
2. Click `Option -> Link transaction` to open a modal form to create a link.
3. *Select a populated transaction to link.* (e.g. `24: its_description`)
4. Submit the form.

The modal form may look like this:
![image](https://user-images.githubusercontent.com/6300506/44921228-8856c680-ad74-11e8-9770-cd815c6669e1.png)

**Extra info**
It looks like that the validation ruled [here](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Requests/JournalLinkRequest.php#L85) causes an error of comparing the non-integer field `link_other` (e.g. `24: its_description`) with the integer field `id` of table `transaction_journals`.

**Comment by JC5** [comment]
Thanks for reporting this! :+1:

It seems to work just fine here, but I haven't tested this with anything other than Latin characters. Although it is all UTF8 (and so it should work) I will do some extra testing.

Were you able to verify this on the demo site, by any chance? Thanks again :)

**Comment by cyliang** [comment]
Hi, I've tried the demo site and everything works normally. However, I believe the error is hidden by the database management system the demo site uses. I don't know what database system is used by the demo site, but the one I use is PostgreSQL (the default deployment of FireFly III on Heroku).

From the trace below we can see the query for the [validation rule](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Requests/JournalLinkRequest.php#L85) isn't correct, as I mentioned in my previous post.
![image](https://user-images.githubusercontent.com/6300506/44929856-045e0800-ad8f-11e8-8750-0c131e05dbba.png)

Also, I manually tried a similar incorrect query using both MySQL and PostgreSQL, and found that MySQL does not complain the error. Perhaps the database system the demo site uses has the similar behavior to MySQL?
- MySQL: http://sqlfiddle.com/#!9/817750/2
- PostgreSQL: http://sqlfiddle.com/#!17/dce9d/2

**Comment by JC5** [comment]
Mmmm, I see what the problem could be. The `link_other` field should be splitted. I'll check it out, thanks!

**Comment by JC5** [comment]
Do you see Javascript errors in your console, perhaps?

**Comment by cyliang** [comment]
No, I didn't see any error in the JavaScript console.

**Comment by JC5** [comment]
Alright, found and fixed. Thanks for the extensive information. I hadn't thought to look there. My test database is SQLite and the demo site is MySQL. 

I've pushed a fix for the next release. It should be up and running some time this weekend.

Thanks again for debugging and submitting! :+1:
