### ISSUE TITLE
Wrong reconciliation difference

### ISSUE THREAD

**Issue by Ludo444** [firefly-iii/firefly-iii#1643]
Hi,
I am running Firefly III version 4.7.5.3 and reconciliation correction seems broken to me. It looks like during "Overview of reconciliation" it takes into account all shown transactions, including those that are dated before the start of reconciliation period. The dynamic amount of what is left to reconcile on the other hand seems to be calculated correctly.

The result is that difference shown in amount of what is left and final difference are different. And the suggested correction includes past transaction. I am attaching the screenshots where difference and amount left to reconcile are varying. In my understanding these values should be the same.

![screenshot_20180831_190958](https://user-images.githubusercontent.com/7080959/44923866-32712700-ad52-11e8-9bc3-e9f0791e30b6.png)
![screenshot_20180831_191013](https://user-images.githubusercontent.com/7080959/44923867-32712700-ad52-11e8-8124-c49278639132.png)

**Comment by JC5** [comment]
Yes, transactions from before the period you're trying to reconcile count as well. 

Since this feature is inspired by what other programs offer, please check out [this video](https://www.youtube.com/watch?v=M2uGfm8cnJ8&feature=youtu.be&t=4m22s). It shows the exact same process but in Quicken.

**Comment by Ludo444** [comment]
To me this seems counterintuitive. I previously used Skrooge to manage my finances and there the reconciliation is taking into account the exact amount only from the beginning of period.

If I would want to reconcile previous transactions also, I would include them in my reconciliation period. My statement shows starting balance at the beginning of period, but Firefly is taking into account balance from before of reconciliation.

**Comment by Ludo444** [comment]
Where this actually causes issue is when I want to use "Correct the balance" functionality because it calculates wrong correction and my balance in Firefly is wrong and not reflecting my real account situation. This is because the Reconciliation transaction is either too big or too small.

**Comment by JC5** [comment]
I apologise, I see what you mean. They should not be added. 

Like you say, they're out of range. I was under the impression they were previously unchecked. It seems to be a bug, and those I can fix. Thanks for letting me know.

**Comment by Ludo444** [comment]
Hey, i don't know what got wrong in the process, but this is behaving exactly the same in 4.7.7 as it was in 4.7.5.3

**Comment by brightonjack** [comment]
I am having a similar problem with the reconciliation, @JC5. I am using 4.7.10 on Ubuntu 18.04, PHP 7.2, NGINX server.

I am adding my past bank statements month by month from scratch and for each month I add, I then reconcile and move onto the next month. For example, I add January 2016 statement to Firefly, then reconcile, then move onto the February 2016 statement. When I finish adding February 2016 statement and then go to the reconciliation section, some reconciled transactions from January still shows up on the screen, albeit ticked. When I only tick the transactions from February, it still counts the ticked transactions from January and tells me that they are already reconciled.

It feels like this bug has creeped back from the grave. You can also replicate this issue on the demo website. The issue doesn't appear on all months, but on some months for some reason.

**Comment by JC5** [comment]
Your issue is on my list, sorry for not replying. I haven't been able to give the feature a lot of attention lately but I will in the near future. Thanks for your patience.

**Comment by sergeolkhovik** [comment]
I can confirm that I don't get the proper result with reconciliation as well. May be I misunderstand this, going to setup demo in my environment and generate some test transactions and show result.
For now I simply open audit report, check ending balance and create pos/neg transaction to match the balance.
