### ISSUE TITLE
firefly:cron is not defined

### ISSUE THREAD

**Issue by captainhook** [firefly-iii/firefly-iii#1644]
I am running Firefly III version 4.7.5.3

**Description**
I have run in SSH

`/opt/plesk/php/7.2/bin/php /var/www/vhosts/domain.com/firefly-iii/artisan firefly:cron`

The output I get:

```
  Command "firefly:cron" is not defined.

  Did you mean one of these?
      firefly:create-export
      firefly:create-import
      firefly:decrypt-attachment
      firefly:encrypt-file
      firefly:instructions
      firefly:scan-attachments
      firefly:start-import
      firefly:upgrade-database
      firefly:use-encryption
      firefly:verify
```

I followed the recommendation here: https://firefly-iii.readthedocs.io/en/latest/installation/cronjob.html

Have I done something wrong? Should it be `schedule:run` instead of `firefly:cron`?
I can see some discussion related to this in #1583

**Comment by JC5** [comment]
No it’s not your fault. I pushed the documentation too soon. The command will be available in the next version. I hope to release it this weekend. 

I apologize for the confusion!

**Comment by captainhook** [comment]
Awesome :) Sent a donation your way for some weekend drinks/treats, best wishes!

**Comment by JC5** [comment]
I saw it, thank you! 👍😁

**Comment by JC5** [comment]
The new release is live :+1:
