### ISSUE TITLE
Recommend to add seed migration into the documentation of upgrading

### ISSUE THREAD

**Issue by cyliang** [firefly-iii/firefly-iii#1645]
I have some problem when I upgrade my FireFly III instance on Heroku to 4.7.6 by following [this documentation](https://firefly-iii.readthedocs.io/en/latest/installation/upgrading.html#straight-from-github). Some new account types added in 2290fcde22ba372f53f9dc4de824c71ac3182f19 are not in my database. This causes an error when I was trying to edit an existed account.

I'm not familiar with the migration mechanism. However, the problem is resolved after trying `php artisan migrate --seed`. Am I doing right? Should I do `php artisan migrate --seed` every time I upgrade FireFly III? If yes, would it be better to add some more clear instructions in the documentation? Thank you.

**Comment by JC5** [comment]
Yes, I see that not all blocks of instructions had this. I've added it to the documentation. Thanks for letting me know.
