### ISSUE TITLE
API unable to create new transaction

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#1647]
I am running Firefly III version 4.7.6
api_version: "0.7"
php_version: "7.1.21"
os: "Linux" Fedora 28
driver: "mysql"

**Description**
I am unable to add new transaction via API. 
I can confirm that I am properly authenticated using Personal Access Tokens as I am able to reach other endpoints, and even add accounts. 

I am trying to POST the following JSON with the minimal payload as described in the documentation.
into /api/v1/transactions
{
    "type": "Withdrawal",
    "description": "test",
    "date": "2018-09-02",
    "transactions[0][amount]": 10,
    "transactions[0][source_id]": "32",
    "transactions[0][destination_id]": "42",
    "transactions[0][description]": "test",
    "transactions[0][currency_code]": "EUR"
}

have tried on newly deployed firefly instance in heroku and the demo site and have the same issue... I must be doing something wrong... can you please help?

**Steps to reproduce** 
POST the above JSON into the /api/v1/transactions endpoint

**Extra info**
Debug information generated at 2018-09-02 17:38:36 UTC for Firefly III version **4.7.6**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.6 |
| FF API version | 0.7 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug,  |
| PHP version | 7.1.21 |
| Display errors | Off |
| Session start | 2018-09-01 00:00:00 |
| Session end | 2018-09-30 23:59:59 |
| Session first | 2014-03-20 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | 'unknown' |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3528.4 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, ldap, exif, mcrypt, mysqlnd, PDO, pgsql, Phar, posix, recode, shmop, SimpleXML, snmp, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, wddx, xmlreader, apcu, igbinary, memcache, msgpack, OAuth, propro, raphf, smbclient, zip, http, memcached, mongodb, libsmbclient, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.5, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.35, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.4, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.46, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.4, symfony/css-selector@v4.1.4, symfony/debug@v4.1.4, symfony/event-dispatcher@v4.1.4, symfony/finder@v4.1.4, symfony/http-foundation@v4.1.4, symfony/http-kernel@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.4, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.4, symfony/translation@v4.1.4, symfony/var-dumper@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.5,  |

**Bonus points**
Earn bonus points by:
- I replicated the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
The error message you get back should tell you what's wrong:

1. `Withdrawal` should be `withdrawal`.
2. `transactions[0][description]` should not equal `description`. Both can't be "test".

With these fields changed I can generate a transaction over the API.

**Comment by may-cat** [comment]
I've got the same kind of trouble on my installation. But setting `withdrawal` and `description` didn't work.

Instead of json reply I got html page `Sign in to start your session`. Trouble appears only on POST method, GETs work perfectly.

**Comment by JC5** [comment]
Did you add the Authorization header to POST calls as well?

**Comment by may-cat** [comment]
Yes, of course.

```
Authorization:Bearer bigstring_same_as_in_get_methods
```

**Comment by may-cat** [comment]
I am making telegram bot for firefly III, and making transactions is really necessary. How am I able to debug this trouble?

Can it be trouble with authorization only or it may be validation error, that doesn't make any error messages? Turning on debug in `.env` doesn't help and code is not so easy to understand for me.

**Comment by JC5** [comment]
There should be no validation errors that go undetected. Could you share the whole post request you're sending?

**Comment by may-cat** [comment]
I've tryed different methods. For example:
```
POST /api/v1/transactions HTTP/1.1
Host: 192.168.31.221:8000
Authorization: Bearer mybigbibgibigtoken
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 6469bc9c-af22-5a80-48c4-38b32a65e9b9

{
"type":"withdrawal",
"description":"my message text",
"date":"2018-09-03",
"transactions[0][amount]":"-1313",
"transactions[0][currency_code]":"RUB",
"transactions[0][description]":"test",
"transactions[0][source_id]":"4",
"transactions[0][destination_id]":"34"
}
```
or
```
POST /api/v1/transactions HTTP/1.1
Host: 192.168.31.221:8000
Authorization: Bearer mybigbigtoken
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Cache-Control: no-cache
Postman-Token: 524617c1-d411-8120-4248-e4012ab1d36f

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="type"

withdrawal
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

my message text
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="date"

2018-09-03
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="transactions[0][amount]"

1313
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="transactions[0][currency_code]"

RUB
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="transactions[0][description]"

test
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="transactions[0][source_id]"

4
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="transactions[0][destination_id]"

34
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

or

```
POST /api/v1/transactions HTTP/1.1
Host: 192.168.31.221:8000
Authorization: Bearer mybigbibigbigbigtoken
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: ba6c6539-18fa-f911-9aab-995356daa6e8

type=withdrawal&description=my+message+text&date=2018-09-03&transactions%5B0%5D%5Bamount%5D=1313&transactions%5B0%5D%5Bcurrency_code%5D=RUB&transactions%5B0%5D%5Bdescription%5D=test&transactions%5B0%5D%5Bsource_id%5D=4&transactions%5B0%5D%5Bdestination_id%5D=34
```

All returned the same

**Comment by JC5** [comment]
Mmm, so you also get no error when submitting an empty post to this endpoint?

**Comment by may-cat** [comment]
No error, only html `Sign in to start your session`.
PHP code - from master branch, pulled hour ago.

**Comment by may-cat** [comment]
I can talk through skype (may_cat_ghost)/telegram(@i_tsupko)/google meet(maicatus@gmail.com) and show my desktop next half an hour.

**Comment by JC5** [comment]
That's OK, I'll do some digging tomorrow.

**Comment by lverissimo** [comment]
Thank you for your support. I just want to add that the POST for other endpoins, namely, accounts is working ok.

**Comment by JC5** [comment]
All I see is, that the amount must be positive. I forgot about that one. But I get correct error messages all the way and this works for me:

<img width="574" alt="screen shot 2018-09-04 at 07 28 47" src="https://user-images.githubusercontent.com/5889984/45011717-39c75780-b014-11e8-8c71-52b7b89e6788.png">

**Comment by may-cat** [comment]
Can you show what's in your Authorization and Headers section in postman?

**Comment by JC5** [comment]
Sure!

<img width="795" alt="screen shot 2018-09-04 at 08 33 08" src="https://user-images.githubusercontent.com/5889984/45013943-2ec4f500-b01d-11e8-948a-cc652cf53fd8.png">

<img width="1028" alt="screen shot 2018-09-04 at 08 33 27" src="https://user-images.githubusercontent.com/5889984/45013958-3a182080-b01d-11e8-8f4d-bfc1bd6d3330.png">

**Comment by may-cat** [comment]
Whoa. Added `Accept:application/json` and at last got normal error message: `{"message":"The given data was invalid.","errors":{"transactions.0.destination_id":["This value is invalid for this field."]}}`

And after disabling sending my destination_id everything worked fine.

Thank you a lot!

**Comment by JC5** [comment]
Glad to hear it works now! I’ll check if I can fix the error but it’s all default libraries I’m afraid. Make sure the destination id is a valid expense account (for a withdrawal). Or just send the name (destination_name) and Firefly III will do the matching.

**Comment by lverissimo** [comment]
Thanks James. I also got it working on Postman, however I am not able to replicate the full message in Nodered.  I get the following error:
{"message":"Resource not found","exception":"NotFoundHttpException"}

Any help is welcome.

this is my payload and headers:
"payload":
{ "type":"withdrawal",
  "description":"teste",
  "date":"2018-03-04",
  "transactions[0][amount]":"10",
  "transactions[0][currency_code]":"EUR",
  "transactions[0][description]":"testeLV",
  "transactions[0][source_id]":"4",
  "transactions[0][destination_id]":"8"
},

"headers":
{
"authorization":"Bearer my_big_token",
"Accept":"application/json"
}

**Comment by JC5** [comment]
A "not found" message can only mean you aren't hitting the correct end point I'm afraid. The data looks good otherwise.

**Comment by JC5** [comment]
@lverissimo your question is kind of snowed under, my apologies. Did my answer help?

**Comment by lverissimo** [comment]
thanks James. I have advanced a bit, but I am still struggling. In NodeRed I need the content of my POST to be a json. So I am trying to get it to work with Postman. I got it to work with the Body in form-data and x-www-form-urlencoded, but without success when I try to code the Body as raw. 

![image](https://user-images.githubusercontent.com/8387568/45061866-3a0c3500-b09e-11e8-804c-3ab5a8b9e604.png)

This is my header
![image](https://user-images.githubusercontent.com/8387568/45061912-61fb9880-b09e-11e8-8d15-c8126afefbe3.png)

This format works for the accounts endpoint
![image](https://user-images.githubusercontent.com/8387568/45061956-a6873400-b09e-11e8-8122-74897863879d.png)

Thanks in advance.

**Comment by JC5** [comment]
I see that you're sending `transaction[0][amount]` instead of `transactions[0][amount]`. Could that be the solution?

**Comment by JC5** [comment]
Found it. Not sure why I didn't think of this earlier! If you're submitting JSON, you have to go all the way.

Submit this:

```
{
	"type": "withdrawal",
	"description": "Test transaction",
	"date": "2018-09-05",
	"transactions": [{
		"amount": "10",
		"currency_code": "EUR",
		"source_id": "1",
		"destination_name": "Some expense account"
	}]
}

```

**Comment by lverissimo** [comment]
Eureka! Thank you! It works. 

![image](https://user-images.githubusercontent.com/8387568/45081937-2f7a8b80-b0f0-11e8-961b-7107c7268abe.png)
