### ISSUE TITLE
API Personal Access Tokens becomes unusable after upgrade or between heroku app sleep time

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#1648]
I am running Firefly III version 4.7.6

**Description**
After upgrading from 4.7.3 to 4.7.6 my Personal Access Tokens were unusable. 
I noticed the same experience on my test instance in heroku, which after every application sleep, looses the ability to use the defined Personal Access Tokens.

**Steps to reproduce** 
- deploy a new instance of heroky firefly template
- define a Personal Access Token
- not use this instance for a couple of hours
- Personal Access Tokens previously defined is unusable.

**Extra info**
Debug information generated at 2018-09-02 17:38:36 UTC for Firefly III version **4.7.6**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.6 |
| FF API version | 0.7 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug,  |
| PHP version | 7.1.21 |
| Display errors | Off |
| Session start | 2018-09-01 00:00:00 |
| Session end | 2018-09-30 23:59:59 |
| Session first | 2014-03-20 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | 'unknown' |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3528.4 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, ldap, exif, mcrypt, mysqlnd, PDO, pgsql, Phar, posix, recode, shmop, SimpleXML, snmp, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, wddx, xmlreader, apcu, igbinary, memcache, msgpack, OAuth, propro, raphf, smbclient, zip, http, memcached, mongodb, libsmbclient, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.5, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.35, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.4, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.46, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.4, symfony/css-selector@v4.1.4, symfony/debug@v4.1.4, symfony/event-dispatcher@v4.1.4, symfony/finder@v4.1.4, symfony/http-foundation@v4.1.4, symfony/http-kernel@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.4, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.4, symfony/translation@v4.1.4, symfony/var-dumper@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.5,  |

**Comment by JC5** [comment]
Any errors you're getting from the API when you try to use them?

The tokens are stored in the database, so I am not sure what's going on. I'll have to do some research.

**Comment by JC5** [comment]
I see that if you restart all dynos, the oauth clients fail until you get a new token.

**Comment by JC5** [comment]
Wait bot, still haven't tested this!

**Comment by JC5** [comment]
I'm sorry, this is not something I can fix. Heroku uses an ephemeral file system that doesn't save files between sessions. This is also a problem for attachments and import files.

There is not much I can do unfortunately.

**Comment by hamuz** [comment]
What is the root cause of this? Is this solvable with the new backing storage?

**Comment by JC5** [comment]
Laravel stores the keys that are required for OAuth2 [directly](https://github.com/laravel/passport/blob/7.0/src/Passport.php#L372) in the /storage/ directory. So when Heroku powers down the app, the files are gone. This is why it breaks.

**Comment by hamuz** [comment]
This is my plan, at the time being...

**Comment by hamuz** [comment]
No need to make Passport storage keys in remote storage, because it is possible to set environment variables with the keys to be used: PASSPORT_PRIVATE_KEY and PASSPORT_PUBLIC_KEY. Keys need to be RSA formatted

Proof: 
https://github.com/laravel/passport/blob/7.0/config/passport.php

The service provider:
https://github.com/laravel/passport/blob/7.0/src/PassportServiceProvider.php

That ultimately use this function to get the keys:
https://github.com/laravel/passport/blob/7.0/src/PassportServiceProvider.php#L232

That tries first to get them from the environment rather than the disk.

**It can be documented** that in cases such as Heroku, keys MAY be generated using
``` php artisan passport:keys ``` and copied to environment variables for persistence.

**Comment by JC5** [comment]
That is looking promising! Might be something that can be put into a custom script for Heroku.
