### ISSUE TITLE
On import - negative withdrawal should be a deposit

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1650]
**Bug description**
I am running Firefly III version 4.7.6

When importing my credit card statements from CSV, I've chosen the amount column as amount_debit.
There was a row with negative value, indicating a (partial) refund from the store back to the card.

After the import the balance didn't go to zero. The wrong transaction was half of the difference (because not only it didn't register as a deposit, it registered as withdrawal).

**Steps to reproduce**
What do you need to do to trigger this bug?
import csv, where the row has negative amount in column with config 'amount_debit'

**Expectation**
On import at least, negative amount in column amount_debit should be a deposit, and not withdrawal.

**Comment by JC5** [comment]
If you use the `amount_debit` for a column, all amounts are assumed to be negative, and converted to a negative number if they're not. The behaviour you're expecting fits better with the "Amount" column. If you use that one, the transaction would be converted to a deposit.

**Comment by hamuz** [comment]
I'm missing "Negate transactions amount" option, on import, for amount type (present in Kaching import screen, for example).
My transactions got imported with positive amount, and refund with negative (which is to be expected from csv, but I need them the other way).

On a different note, import using amount caused refund transaction to not get imported due to duplicate flagging. (I'll open another issue, I got a lot to say on the subject)

**Comment by JC5** [comment]
I'll see what I can do about the negate option. It might be something for a future release. But if you make sure that you indicate the source and destination ("opposing") account correctly, it makes sense to make withdrawals in a negative amount and deposits a positive amount. We're talking about the perspective of the asset account after all.

But banks are weird, I know.

**Comment by hamuz** [comment]
It makes sense to me to negate because my scenario is the following:
I do transfer [bank account -> CC account]
In reality transactions on CC stack up during the month (creating negative balance) and the balance is zero-ed with the payment of them (bank -> CC)

**Comment by JC5** [comment]
Yes, so a negative transaction is an expense for the bank account.

**Comment by hamuz** [comment]
yes, and a deposit to CC account. So the CC transactions need to be withdrawals.

**Comment by JC5** [comment]
Mmmm, I'll check what Firefly III is doing now. I believe it's the reverse.

**Comment by JC5** [comment]
Had to check, wasn't sure. Check this example:

```
source-name,dest-name,date-transaction,description,amount
Checking,Saving,20170101,"Some test from Checking to Saving",-45.67
Checking,Saving,20170101,"Some test from Saving to Checking",12.34
```

In the first row, money is removed from Checking, which is why it's negative.
In the second row, money is added to Checking, which is why it's positive.

<img width="1245" alt="screen shot 2018-09-03 at 19 59 55" src="https://user-images.githubusercontent.com/5889984/44998234-2dabad80-afb4-11e8-8553-cf65705bed0e.png">

**Comment by hamuz** [comment]
What did you try to demonstrate with this example?

I'm talking more about something like this

> source-name,date-transaction,description,amount
> CC,20170123,"to A",1.00
> CC,20170124,"to B",2.00
> CC,20170125,"to C",3.00
> CC,20170125,"to D",4.00
> CC,20170125,"from D - refund",-4.00

and

> source-name,dest-name,date-transaction,description,amount
> Checking,CC,20170201,"to CC",6.00

Assuming Checking was 6.00 at the beginning, all accounts should be zero after import, assuming today is 20170202.

**Comment by JC5** [comment]
Ah yes. As you can see, Firefly III works the other way around.

Expenses are assumed to be negative. So the transactions labeled "to A", etc should be negative amounts. Likewise the refund from D should be positive.

Same for the transaction from Checking to CC.

**Comment by JC5** [comment]
There isn't one. I can't make everybody happy.

**Comment by hamuz** [comment]
Is it possible to add such feature, or should this scenario be addressed with specifics mechanism?

**Comment by JC5** [comment]
Something like that. The specifics fire before you map the data, because they influence the data you map in a later stage. And negating the amounts is something for which I really need to know for sure which columns are amounts. Account numbers, identifiers and other fields must not be negated by accident.

It's on the list. :)
