### ISSUE TITLE
Missing import errors strings from translations 

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1652]
**Bug description**
I am running Firefly III version 4.7.6

Extract error strings to language files so they can be translated.

https://github.com/firefly-iii/firefly-iii/blob/835a421909fc3069542dcc41f47e77884768ae0d/app/Import/Storage/ImportArrayStorage.php#L408-L477

**Extra info**
Search for "could not be imported.".
I've also highlighted the lines I've found/

**Comment by JC5** [comment]
Ah yes, very good. Duly noted.

**Comment by JC5** [comment]
I'll mark this as a bug and pick it up for the next release. Depending on the context I might not be able to translate (no user info).
