### ISSUE TITLE
[Rules] When adding actions to a rule, only one is being added

### ISSUE THREAD

**Issue by fllo** [firefly-iii/firefly-iii#1654]
**Bug description**
I am running Firefly III version 4.7.6.1
When adding actions to a rule only the first action is being added.

**Steps to reproduce**
What do you need to do to trigger this bug?
Add at least two actions to a rule (new or already existing).
Usually I use "set category" and "set budget".

Clicking on the button "Add new action"
adds a new tr element always with data-count="1"

I am having the problem with the official composer version, and the version from github (git clone).
But I can't reproduce the behavior using the official docker image, nor the demosite.
Using the demosite it correctly increments the data-count.

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

Debug information generated at 2018-09-03 21:55:44 Europe/Berlin for Firefly III version **4.7.6.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.6.1 |
| FF API version | 0.7 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.2.4-1+b2 |
| Display errors | Off |
| Session start | 2018-09-01 00:00:00 |
| Session end | 2018-09-30 23:59:59 |
| Session first | 0008-10-30 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.5, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.37, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.4, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.46, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.4, symfony/css-selector@v4.1.4, symfony/debug@v4.1.4, symfony/event-dispatcher@v4.1.4, symfony/finder@v4.1.4, symfony/http-foundation@v4.1.4, symfony/http-kernel@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.4, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.4, symfony/translation@v4.1.4, symfony/var-dumper@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.5,  |

**Bonus points**
Earn bonus points by:

- Post a stacktrace from your log files
- Add a screenshot
![image](https://user-images.githubusercontent.com/32941422/45000367-94d15e00-afc4-11e8-9ba8-8cd86b8dd829.png)

**Comment by JC5** [comment]
Mmmm. Any Javascript errors, incidentally?

**Comment by fllo** [comment]
No Javascript errors.

![image](https://user-images.githubusercontent.com/32941422/45001092-779f8e00-afca-11e8-871b-53b681025e38.png)

**Comment by JC5** [comment]
OK, I'm not seeing anything strange in the JS. Are you running Firefly III in a subdirectory, like www.example.com/firefly/  ?

**Comment by fllo** [comment]
Yes. Behind nginx.

**Comment by JC5** [comment]
OK. That might be it. Will check it out tomorrow.

**Comment by fllo** [comment]
Thanks for pointing me in the right direction.

Seems to have been a miss configuration on the nginx side. (Laravel and subdirectory)
The following helped: https://gist.github.com/tsolar/8d45ed05bcff8eb75404
using a solution similar to version 1.

I stumbled upon the following:
GET /json/action
and GET /json/action?count=0 
and GET /json/action?count=1
return the same response.

**Comment by fllo** [comment]
I will create a pull-request for the documentation: FAQ part with my nginx configuration.

Caused by the faulty nginx configuration I previously used, the query part of the url didn't reach firefly.
So firefly always got the GET /json/action instead of GET /json/action?count=2
GET /json/action doesn't return an error.

**Comment by fllo** [comment]
Done. Closing this issue.
