### ISSUE TITLE
4.7.6.1 on Windows - Blank white screen after finishing install

### ISSUE THREAD

**Issue by Foxtrek64** [firefly-iii/firefly-iii#1657]
I am running Firefly III version 4.7.6.1

**Description**
I am running Firefly III on Windows Server 2016 Standard. I installed the IIS role on the server, got MySQL up and running with the appropriate [backwards-compatibility fix](https://dev.mysql.com/doc/apis-php/en/apis-php-pdo-mysql.html), and followed the self-hosting guide.

After working through the guide, I reached the step to open the page in a browser. Navigating to `http://localhost/` results in a blank white screen.

I've followed the FAQ entry for this issue and I have confirmed that IIS_USERS has write access to `C:\inetpub\wwwroot\firefly-iii\storage\logs`, though no log files have been written since I ran into the issue with MySQL that required me to change the default authentication type. As such, I moved on to the next step, confirming the `vendor` folder exists, which it does. The last bit mentions the rewrite module in Apache, so I went and downloaded the IIS equivalent and ran an `iisreset`. This had no result.

**Extra info**
OS: Windows Server 2016 Standard
Browser: Firefox 61.0.2
output from `http://localhost/debug` - `null`
IIS Site path [has been modified](https://firefly-iii.readthedocs.io/en/latest/support/faq.html#i-have-to-access-firefly-iii-through-public-and-it-gives-me-a-warning) to point to `C:\inetpub\wwwroot\firefly-iii\public`

**Comment by Foxtrek64** [comment]
As far as I can tell, no. The IIS logs have entries like the following:
```
2018-09-04 11:21:08 ::1 GET / - 80 - ::1 Mozilla/5.0+(Windows+NT+10.0;+WOW64;+rv:61.0)+Gecko/20100101+Firefox/61.0 - 500 0 0 1031```

As for the .env file, I've included a (redacted) version of my .env as a [gist](https://gist.github.com/Foxtrek64/682f8ec4dccb75327d3f7966acd37e5e)

**Comment by JC5** [comment]
Alright, let's set APP_DEBUG to true and the log level to debug. That might turn up something. Although errors should be reported anyway. 

I suggest a search to make PHP log errors somewhere. A quick Google search turned up [these instructions](https://stackoverflow.com/questions/27608688/display-php-errors-in-iis).

If you create `/public/pi.php` and put in this content, you can be sure of an exception that should be logged in detail somewhere.

```
<?php
phpinfo()
echo "Hi";
```

Then, you can reload Firefly III and see what it has to say.

**Comment by Foxtrek64** [comment]
I followed the instructions above up to the SO post. Upon reloading the page, I see the following exception:
```
 (1/1) UnexpectedValueException

The stream or file "C:\inetpub\wwwroot\firefly-iii\storage\logs/ff3-cgi-fcgi-2018-09-04.log" could not be opened: failed to open stream: Permission denied
```
It seems I'd forgotten that IIS uses `ServerName\IUSR` for permissions, not `ServerName\IIS_IUSRS`. I'll knock the log levels back down to default. Just a strange quirk working with IIS I guess.

**Comment by JC5** [comment]
Of course because why make it easy, MS? :wink:

Glad to hear it works!
