### ISSUE TITLE
Font is a bit too light

### ISSUE THREAD

**Issue by Findus23** [firefly-iii/firefly-iii#1658]
Hi,

Since the latest update (4.7.6) the base font is quite hard to read. I think this is mostly caused by the switch to the light font-weight by the css library.

https://github.com/firefly-iii/firefly-iii/blob/bae40e2cbc14a34f67f96db2a3faa9a1b3a39515/public/lib/adminlte/css/AdminLTE.css#L45

**Extra info**
This is a bit hard to describe as font-rendering is extremely os/browser dependent. 
My environment is:
Firefox 61.0.1 on Debian Testing
1920x1080 on 15'' Screen (So no high-dpi)

**Screenshots**

The screenshots are not scaled, so I hope my point is visible here:

![grafik](https://user-images.githubusercontent.com/6266037/45049955-5dc08280-b080-11e8-86f0-aaf3cb4dfe18.png)

![grafik](https://user-images.githubusercontent.com/6266037/45049996-6f098f00-b080-11e8-8a66-ebca536bf63c.png)
![grafik](https://user-images.githubusercontent.com/6266037/45050008-75980680-b080-11e8-9a00-14b0cb37a56c.png)

**Accessibility**:

I think the pretty light contrasts may cause even more accessibility issues. 

Maybe this should be reported on AdminLTE as I think it isn't caused by the firefly css.

**Comment by JC5** [comment]
Yeah I agree. I'm sure I can overrule it though. I hope to fix this in the next release.

**Comment by JC5** [comment]
I've pushed some CSS to the demo site. That will be the look next release.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
