### ISSUE TITLE
Problem with nginx and location /budget 

### ISSUE THREAD

**Issue by pizzle-d** [firefly-iii/firefly-iii#1659]
I am running Firefly III version 4.7.6.2
I run Firefly on nginx with the snippet from the faq. I changed the fastcgi_pass and include because i run arch. My firefly.conf for nginx looks like this:

```
server {
        listen 192.168.0.1:80;
        server_name server.name;
        root /opt/html/firefly-iii/public/;
        index index.php;
        location ^~ /firefly-iii/ {
                deny all;
        }
        location ^~ /budget {
                alias /opt/html/firefly-iii/public;
                try_files $uri $uri/ @budget;
                location ~* \.php(?:$|/) {F
                        include /etc/nginx/fastcgi.conf;
                        fastcgi_param SCRIPT_FILENAME $request_filename;
                        fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
                        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
                }
        }

        location @budget {
                rewrite ^/budget/(.*)$ /budget/index.php/$1 last;
        }
}
```
Without the index index.php I get a 403 forbidden:
`systemctl status nginx`
`16981#16981: *1 directory index of "/opt/html/firefly-iii/public/" is forbidden`

With it there i get a 404 error: 

> 404 — Firefly III cannot find this page.

```
systemctl status nginx
17033#17033: *1 open() "/opt/html/firefly-iii/public/css/app.css" failed (2: No such file or directory)
```
I guess that is normal because there is no app.css file.

To reproduce:
I think install php, php-fpm, nginx. Install the config I posted. Start all of it and try to access server.name/budget/.

**Comment by JC5** [comment]
I'm pinging @fllo because he wrote that FAQ entry. Could you take a look as well? I am not sure what to look for myself.

**Comment by fllo** [comment]
* your root equals the alias direction.
* the "include snippets/fastcgi-php.conf" was changed to "include /etc/nginx/fastcgi.conf;" these are not the same at least under debian check if you have "/etc/nginx/snippets/fastcgi-php.conf"
(this is probably the cause)

in my config
`root /var/www;
index index.php index.html index.htm;
`

firefly is located in /var/www/firefly-iii
therefore all access to firefly-iii needs to be denied.
firefly-iii/public is the directory we want as the firefly root. => therfore alias to /var/www/firefly-iii/public

I am running debian testing with nginx 1.13

**Comment by fllo** [comment]
Contents of the debian snippets/fastcgi-php.conf
```
# regex to split $uri to $fastcgi_script_name and $fastcgi_path
fastcgi_split_path_info ^(.+\.php)(/.+)$;

# Check that the PHP script exists before passing it
try_files $fastcgi_script_name =404;

# Bypass the fact that try_files resets $fastcgi_path_info
# see: http://trac.nginx.org/nginx/ticket/321
set $path_info $fastcgi_path_info;
fastcgi_param PATH_INFO $path_info;

fastcgi_index index.php;
include fastcgi.conf;
```

**Comment by pizzle-d** [comment]
Thank you. 
I got it to work now with the fastcgi-php.conf
