### ISSUE TITLE
Inverting Credit Card Import

### ISSUE THREAD

**Issue by bm751613** [firefly-iii/firefly-iii#1660]
My credit card provider exports their transactions as positive numbers as if the money is going into their account as opposed to coming from mine. I have no idea if this is normal for them or not, I only have the one card so I don't have anything to compare it to.

I have tried messing with the amount column in the import config with no luck.

Is there a way built into firefly to get the positive values imported from a CSV to negative so my net worth and credit card payments are correctly calculated?

I can easily invert the values in the file itself but one less step would be great.

**Comment by JC5** [comment]
Ah yes! 

I'll think of something. Probably another role. Something like "Amount (inversed)". It's been asked before and another viable solution isn't really there.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1263
