### ISSUE TITLE
Do not show empty currencies in Net Worth summary bar

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#1662]
**Description**
Please describe your feature request:

Firefly 4.7.6.2.
Currenty Net Worth bar displays currencies even if I dont have them anymore:
![obraz](https://user-images.githubusercontent.com/4746858/45115122-3f758800-b14f-11e8-952b-241b9017d951.png)

**Solution**
Do not display currencies that I do not own anymore.

**What are alternatives?**
None

**Additional context**
N/A

**Comment by JC5** [comment]
If you make the associated accounts inactive, it should disappear from your net worth.

**Comment by skibbipl** [comment]
OK, this sound reasonable.
