### ISSUE TITLE
Withdrawal split to asset account and not only expense account

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1664]
I am running Firefly III version 4.6.2

**Description**
Can't transfer a part of a transaction (a split) to asset account.
I'm able to choose expense account.
I would like to do it like a transfer (from one asset account to another).

**Steps to reproduce** 
(if relevant of course)
1. Create Withdrawal transcation
2. Split it
3. Try to transfer it to existing ASSET account - fail - new expense account created.

**Comment by JC5** [comment]
Unfortunately, that's not possible. Split transactions can only be of a single type.
