### ISSUE TITLE
Liability accounts - GUI option for Import/Virtual Balances

### ISSUE THREAD

**Issue by 4oo4** [firefly-iii/firefly-iii#1671]
I am running Firefly III version 4.7.6.2

I just started using the Liability accounts feature (btw, thank you for adding this!) and it seems that currently the only way to mass import transactions is using the cli import, and the only way to add a virtual balance is by directly editing the accounts table in the database. I was wondering if there would eventually be GUI options for these like the other account types?

Cheers

**Extra info**
Debug information generated at 2018-09-08 18:03:42 UTC for Firefly III version **4.7.6.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.6.2 |
| FF API version | 0.7 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug,  |
| PHP version | 7.2.9-1+ubuntu16.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2018-09-01 00:00:00 |
| Session end | 2018-09-30 23:59:59 |
| Session first | 2013-10-02 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite, sqlsrv |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | 'unknown' |
| Trusted proxies (.env) | 127.0.0.1 |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, interbase, intl, json, ldap, exif, mongodb, msgpack, mysqli, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, recode, redis, shmop, SimpleXML, smbclient, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, psr/http-message@1.0.1, guzzlehttp/psr7@1.4.2, guzzlehttp/promises@v1.3.1, guzzlehttp/guzzle@6.3.3, bunq/sdk_php@dev-master, vlucas/phpdotenv@v2.5.1, symfony/css-selector@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, symfony/polyfill-php72@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/var-dumper@v4.1.4, symfony/routing@v4.1.4, symfony/process@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/http-foundation@v4.1.4, symfony/event-dispatcher@v4.1.4, psr/log@1.0.2, symfony/debug@v4.1.4, symfony/http-kernel@v4.1.4, symfony/finder@v4.1.4, symfony/console@v4.1.4, doctrine/lexer@v1.0.1, egulias/email-validator@2.1.5, swiftmailer/swiftmailer@v6.1.2, paragonie/random_compat@v2.0.17, ramsey/uuid@3.8.0, psr/simple-cache@1.0.1, psr/container@1.0.0, symfony/translation@v4.1.4, nesbot/carbon@1.25.0, monolog/monolog@1.23.0, league/flysystem@1.0.46, erusev/parsedown@1.7.1, dragonmantank/cron-expression@v2.2.0, doctrine/inflector@v1.3.0, laravel/framework@v5.6.38, davejamesmiller/laravel-breadcrumbs@5.1.0, doctrine/event-manager@v1.0.0, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, fideloper/proxy@4.0.0, zendframework/zend-diactoros@1.8.5, symfony/psr-http-message-bridge@v1.1.0, phpseclib/phpseclib@2.0.11, league/event@2.1.2, lcobucci/jwt@3.2.4, defuse/php-encryption@v2.2.1, league/oauth2-server@6.1.1, firebase/php-jwt@v5.0.0, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, league/commonmark@0.17.5, league/csv@9.1.4, league/fractal@0.17.0, paragonie/constant_time_encoding@v2.2.2, symfony/polyfill-util@v1.9.0, symfony/polyfill-php56@v1.9.0, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, twig/twig@v1.35.4, rcrowe/twigbridge@v0.9.6,  |

**Comment by JC5** [comment]
What would you like to use the virtual balance field for? The other things I can arrange of course.

**Comment by 4oo4** [comment]
I think in my case it would come down to if Firefly calculates the interest differently than the bank that I have my loan with?

When I imported my loan history, there was a pretty big balance discrepancy (even though I verified that it imported all the transactions correctly) so that seemed like the most logical way to make them agree.

Also, sending you a donation too, since I know this isn't the first feature I've asked you to look at. Thanks again!

**Comment by JC5** [comment]
I saw that, thank you!

Firefly III doesn't do anything with the interest information (yet). In the future it will, but only "cosmetically", because I know that banks can be weird with how they calculate the interest. I would update the chart for example, but not the actual amount.

I'll do some testing locally to see what could go wrong. Keep in mind that a liability is basically an asset account with a negative start balance. The amount you enter when it's created is made negative and then set as "opening balance".

Deposits into the liability, or transfers towards it, make the amount go down (towards zero) and withdrawals and transfers away from it make the amount go up (away from zero).

**Comment by JC5** [comment]
OK, I've pushed some code that expands the import routine. Liabilities are selectable now through the user interface.

**Comment by 4oo4** [comment]
thanks! Will test that out when I get a chance.

**Comment by JC5** [comment]
I'm marking this as fixed for the next release. Please open a new ticket if that's not the case.
