### ISSUE TITLE
Reconciliation not taking already reconciled trasactions into account

### ISSUE THREAD

**Issue by Ludo444** [firefly-iii/firefly-iii#1673]
Hello again,
The issue I mentioned here https://github.com/firefly-iii/firefly-iii/issues/1643 is fixed, but unfortunately the fix causes another problem. If there is reconciled transaction inside the reconciliation period, it is not being taken into account. 

From what I seen, the previously reconciled transactions are being ignored now completely. Correct behavior would be to take them into account, and ignore only the ones that are outside of the reconciliation period (or stop showing transaction that are not in reconciliation period completely).

I am running 4.7.6.

**Comment by JC5** [comment]
Ah good find. I'll try to take a look today or tomorrow. Thanks for reporting!

**Comment by Ludo444** [comment]
Hey, tried it and unfortunately it's not working correctly. You can check this account https://demo.firefly-iii.org/accounts/show/43 and reconcile whole September.

**Comment by JC5** [comment]
That makes sense. I forgot to do a refresh of the code 😅 

Could you do a hard refresh and try again?

**Comment by Ludo444** [comment]
Seems to work :+1:

**Comment by JC5** [comment]
Thanks! I appreciate your quick reply. I'll line this up for the next release. You can apply the update manually if you're technically inclined.

**Comment by cyliang** [comment]
Hi @JC5, when will this fix be released? Thanks.

**Comment by JC5** [comment]
Not sure yet. Perhaps later next week.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
