### ISSUE TITLE
Multiple Additional Features - Cash Tracking, Pivot Table, Bulk Edit, Store Reports

### ISSUE THREAD

**Issue by qwacko** [firefly-iii/firefly-iii#1674]
**Description**
Please describe your feature request:

Hi, I am really liking this system, and I think it will work quite well for me, just a few suggestions that would make my life a little better using this system:
 - Is it possible to add a "Include In Cash" alongside the current "Include in Net Worth" for each account. This is something that I think others might find useful, as keeping track of your cash position is quite important when you have debts etc..., as your net worth can be going up, but your cash position (across multiple accounts) may not be.
 - I would love to see a pivot-table style report available. How I would envisage it would be that the user could decide maybe up to three different groupings for the x and y axis, and then firefly could make a table.
 - Is there a way to store reports?
 - Finally, and I guess alongside another note you made about updating the table formats. Would it be possible, or even practical, to allow for a method to bulk modify transactions. I am imagining like an editable excel sheet. All the actions (adding, copying) so far appear to only affect one transaction, which makes manually entering transactions quite time consuming.

Not trying to appear demanding, I just had some thoughts that might help (for me and others). Correct me if I have a poor understanding of accounting, or there is already a good way to do what i am thinking. I have (poor to below average) php skills and so would be willing to work on getting some of these sorted with some guidance where to start.

**Solution**
Describe what your feature would add to Firefly III.

**What are alternatives?**
Please describe what alternatives currently exist.

**Additional context**

**Comment by JC5** [comment]
Hey, thanks for these suggestions. Don't worry about appearing demanding. Ideas are always welcome.

* The reports you have available adapt to the accounts you select. So if you include only your cash accounts, your net worth will reflect your cash net worth. I believe that should help when trying to keep track of your cash position.
* I could use some examples as to what the user could pivot. Time and budget? Account and budget? Stuff like that?
* Yes. Each report can be bookmarked. The URI will return you to exactly the report you created. There are also some [magic words](https://firefly-iii.readthedocs.io/en/latest/advanced/reports.html) you can use.
* There is a bulk and mass editor available already. Just press the "Select transactions" button at the bottom of each list.

**Comment by qwacko** [comment]
Hi JC5, 

Cheers for the quick reply, just took me a little bit of time to look at your answers.

- I had another thought about this, and something that may also stop people asking about category types etc... Maybe if there was the option to add "Auto Tags" to the accounts, and categories. Then this tag would get applied to all transactions that match that account / category, and removed from those that don't. Then people could do whatever they wanted, and use the tag filtering / reports etc.. to analyse however they wanted. I am working on seeing if there is a way to use the rules to make this happen, but it is a little tricky to get the necessary combination of selections without using lots of intermediate tags.
- I guess pivot tables give some flexibility in terms of analysing data. For example I might like to group by tag, and then category on the side, and year / month across the top, then I could look at summaries etc... This allows for comparing months etc.. pretty simply. Then if you could click on a total and see / edit the transactions it would be useful. Maybe I just love pivot tables too much, and need to get used to working in reports.
 - I see that, but it would be great if you could add your own links to the "Quick Links" section, so you don't need to re-create them.
 - For the bulk editor, I hadn't seen that thanks. It should do the trick.

**Comment by JC5** [comment]
* Generally speaking, everything "auto" (auto-tagging, categorising, storing, editing, etc) will not make you any more aware of how you're doing financially. It makes for neat charts but it gives very little insight. What you can do with rules is already quite extensive, if you know what you're doing. Most people don't, that's part of the problem of course :wink:
* Check out the reports. There are a lot of tabular views already. If you're missing specific views I'm happy to add them but an entire "pivot"-table feature goes way beyond what Firefly III is meant for. With the database and the API however it shouldn't be hard to build something yourself though.
* For those, I suggest you use your browser's bookmarks.
