### ISSUE TITLE
Wrong sum in tag report

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1675]
I believe there has been a bug like this before but I couldn't find the matching issue. 

**Bug description**
I am running Firefly III version 4.7.6.2

When I view a tag report, the 'spent' sum in the _Tags_ section is wrong (see screenshot)
![image](https://user-images.githubusercontent.com/317179/45418818-cb267180-b685-11e8-949c-420242bfe6f4.png)

I haven't used reports for a long time so I can't tell whether this is an issue introduced with 4.7.6

**Steps to reproduce**
I have selected a single tag `X` for the report. Every transaction with tag `X` also has an additional tag `Y`. It seems that the report sums up the expenses for every transaction **per tag** on that transaction. When I remove the tag `Y` from a single transaction, it modifies the sum shown in the report for tag `X`. When I add another tag `Z` to a single transaction, this transaction is counted three times in the report

**Comment by JC5** [comment]
Oh very good, that looks like a bug. I'll verify and fix it. Thanks for reporting it :+1:

**Comment by JC5** [comment]
I've pushed a fix.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
