### ISSUE TITLE
Balance question

### ISSUE THREAD

**Issue by Egge82** [firefly-iii/firefly-iii#1676]
I am running Firefly III version 4.7.6.2

Hi, 

I just started out with Firefly III and so far it looks really good. However I don't understand why the amount money in my starting asset is not counted in the balance header. For example. I started out with one euro as starting asset. Some transactions later my starting asset is 5 (4 euro income) in the graph. So the graph shows it correctly. However my balance states 4 because the starting budget does not get counted. 

Hopefully I explained myself clearly. There's probably something i'm missing out. 

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
The "balance" you see is recalculated every month and indeed, it does not feature your opening balance.

It focuses purely on the difference between your income and your expenses.

So if you add a new account (with an opening balance) this does not skew the balance. The idea is that a new account is a fact of life. You have that account and you have that amount of money.

**Comment by Egge82** [comment]
Clear to me now. Thanks for the quick response!

**Comment by JC5** [comment]
:+:
