### ISSUE TITLE
"Set destination account to" action in rule doesn't work if transaction is withdrawal

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1677]
**Bug description**
I am running Firefly III version 4.7.6.2

"Set destination account to" action in rule doesn't work if transaction is withdrawal

**Steps to reproduce**
1. Make a rule to match your test transaction with action "Set destination account to" to some existing **asset** account
2. Create/update a withdrawal that matches the rule
3. Inspect withdrawal - notice the rule didn't work

Workaround:
- Manually change the withdrawal to transfer
- Update the transfer (in case rule runs on updates)
- Action works ("Set destination account to" is preformed).

**Expected behavior**
- If "Set destination account to" action in rule is present - Withdrawal should be converted to Transfer automatically (show warning if needed).
- Destination account is set to specified one.

@JC5

**Comment by JC5** [comment]
Indeed, it does not. See also this issue: #1450. The plan is to add a separate action if you wish to change the transaction type, to prevent magic from happening.

**Comment by hamuz** [comment]
Maybe use option group to separate actions that require certain type for the transaction?

**Comment by JC5** [comment]
See #1450
