### ISSUE TITLE
Changing transaction type doesn't count as update (and don't fire update rules)

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1679]
**Bug description**
I am running Firefly III version 4.7.6.2

Changing transaction type doesn't count as update (and don't fire update rules)

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Create rule to match test transaction on update (with set destination account action, for example)
2. Create withdrawal
3. Convert to transfer (**rule doesn't run**)

**Questions**
Does transaction creation also count as update? (as far as firing rules goes)

**Comment by JC5** [comment]
Indeed. That action isn't covered. I will add some code to remedy. Never thought to add it.

**Comment by hamuz** [comment]
I guess this one is sort-of fixed, but look at #1689.
