### ISSUE TITLE
Inconsistent formatting of dates when running rules on existing transactions

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1681]
**Bug description**
I am running Firefly III version 4.7.6.2

Inconsistent formatting of dates when running rules on existing transactions.
Formatting of dates should be consistent (and locale-dependent, do you currently address that?)

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Create transaction to match rule
2. Create rule matching transaction
3. Try to run rule group on account with existing transaction,
specifying really old date.

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

Debug information generated at 2018-09-13 08:18:37 UTC for Firefly III version **4.7.6.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.6.2 |
| FF API version | 0.7 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stdout |
| PHP version | 7.2.9 |
| Display errors | Off |
| Session start | 2018-07-01 00:00:00 |
| Session end | 2018-09-30 00:00:00 |
| Session first | 2018-03-08 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, mbstring, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.5, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.38, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.4, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.46, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.4, symfony/css-selector@v4.1.4, symfony/debug@v4.1.4, symfony/event-dispatcher@v4.1.4, symfony/finder@v4.1.4, symfony/http-foundation@v4.1.4, symfony/http-kernel@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.4, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.4, symfony/translation@v4.1.4, symfony/var-dumper@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.5,  |

**Bonus points**
- a screenshot
![image](https://user-images.githubusercontent.com/550499/45476021-97f7e700-b746-11e8-973b-a899cd84f0ae.png)

**Comment by JC5** [comment]
I'm sorry, the format of the error message is determined by Laravel and is locale independent. It's not something I can change.

**Comment by hamuz** [comment]
This means an English form validation error will be presented to non-English user.
I think we should avoid such cases.

Digging in this issue, I've found the language file in Laravel (5.6) at:
laravel-5.6.33\resources\lang\en\validation.php

and I think they should be added to FireFly translation project somehow.

**Comment by JC5** [comment]
No, all validation errors are translatable. For the most part they are translated already. It's just that I cannot change the format "2018-03-07" to something more locally inclined.

**Comment by hamuz** [comment]
Digging more into Laravel I've found it supports date formatting.

https://github.com/laravel/framework/blob/9f313ce9bb5ad49a06ae78d33fbdd1c92a0e21f6/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L150-L172

Maybe try adding here a locale-specific date-format for Laravel?

https://github.com/firefly-iii/firefly-iii/blob/bae40e2cbc14a34f67f96db2a3faa9a1b3a39515/app/Http/Requests/SelectTransactionsRequest.php#L59-L60

**Comment by hamuz** [comment]
Might be error prone. The back-end should have it's own consistent date formatting, also on the front-end a locale-specific date should be shown. Maybe a javascript fix on the front-end for validation error dates?

**Comment by hamuz** [comment]
Maybe correcting before-hand on back-end 

https://laravel.com/docs/5.6/validation - "Displaying The Validation Errors"

with some manipulation to $errors

**Comment by hamuz** [comment]
Note-to-self, might be useful in future: https://stackoverflow.com/questions/33134878/custom-validation-replacers-in-laravel-5-1

**Comment by hamuz** [comment]
how to keep this one open?

**Comment by JC5** [comment]
I've written a note to look into the problem. As far as I am concerned, the issue can be closed.

At the moment, Laravel doesn't seem to offer a decent way of changing this field. Especially not in the standard validation message. 

The user interface is determined by your language selection but this depends on the browser.

Overall I feel that seeing "2018-09-04" instead of "September 4th, 2018" is an issue with much priority.
