### ISSUE TITLE
rule's "See matching transactions" shows transfer transaction twice

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1683]
**Bug description**
I am running Firefly III version 4.7.6.2
Rule's "See matching transactions" shows each transfer transaction twice instead of once.

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Create transfer transaction
2. Create rule that matches transfer
3. Click on "See matching transactions" of rule, in rule page.
4. Transfer is shown twice.

**Bonus points**
Earn bonus points by:
- Add a screenshot
believe me

**Comment by JC5** [comment]
Should be easy to fix.

**Comment by hamuz** [comment]
Confirmed fix in demo.
