### ISSUE TITLE
Auto-completion doesn't work when editing rule with action "Set destination account"

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1685]
**Bug description**
I am running Firefly III version 4.7.6.2

Auto-completion doesn't work when editing rule with action "Set destination account".

Work around is to delete the action, and re-create it,
or change to different action and back to "Set destination account"
then it works again.

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Create rule with action "Set destination account"
2. Try to edit rule, and choose different account - no auto completion.

**Comment by JC5** [comment]
:+1:

**Comment by hamuz** [comment]
Is this deployed to demo already?

**Comment by JC5** [comment]
It should be now.

**Comment by hamuz** [comment]
Fixed. After clearing cache. Maybe some version-based cache busting for next time? To avoid regression reports.

**Comment by JC5** [comment]
There is already. But that’s not activated because I haven’t bumped the version.
