### ISSUE TITLE
Setting order of accounts displayed in home screen

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1686]
**Description**
Please describe your feature request:

- Firefly III doesn't allow setting order of accounts displayed in home screen,
neither in Options > Preferences > Home screen
nor Accounts > Asset Account

The order now seems to be lexical.

**Solution**
Describe what your feature would add to Firefly III.

Show accounts in order the user wants them.

**What are alternatives?**
Please describe what alternatives currently exist.

Scroll down to wanted account

**Additional context**

Allow setting the order (similar in rules order)

**Comment by JC5** [comment]
Indeed, it doesn't. I have no plans to change this.

**Comment by NiFNi** [comment]
Anyone interested in this. You can just put a number in front of the name. So naming your accounts like this:
1. first account 
2. second account
...
results in the ordering the accounts by the number in front of the name. Might be a valid workaround for others aswell.
