### ISSUE TITLE
Sorted column sort direction indicator overlays headings in some locations

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#1687]
**Bug description**
I am running Firefly III version 4.7.6.2

When sorting a column in a table, eg on a report (see screenshot below) if the heading text is right aligned (or long enough on a smaller screen estate) the _1 .. 9_ or _a .. z_ indicator overlays onto the heading.

**Steps to reproduce**

1. Navigate to reports
2. Select type, accounts and relevant dates etc
3. Run report
4. Sort a column eg. under Average spending per account, _Spent (average)_ column
5. See the _1 .. 9_ indicator lie on top of the heading text

May be in other parts of the application where sortable tables exist.

**Extra info**
Am able to replicate this on the demo site also.

**Bonus points**

Screenshot:
![image](https://user-images.githubusercontent.com/3290527/45487140-5de21180-b755-11e8-8f51-72f7d3bf6d36.png)

**Comment by JC5** [comment]
Can't really be helped I'm afraid without pushing the columns out so it fits. And since the strings are translatable as well, this is tricky to do.

**Comment by ragnarkarlsson** [comment]
Fair enough, just thought I'd report it :-)
