### ISSUE TITLE
Bills introduction - step 2 - no button is highlighted

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1690]
**Bug description**
I am running Firefly III version DEMO 4.7.6.2

(please give a clear and concise description of what the bug is)
Bills introduction - step 2 - no button is highlighted

**Steps to reproduce**
What do you need to do to trigger this bug?

1. Go to https://demo.firefly-iii.org/bills/show/2
2. Press next to step (2) - notice no button is highlighted

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).
No /debug in DEMO

**Bonus points**
Earn bonus points by:
- Add a screenshot
![image](https://user-images.githubusercontent.com/550499/45539856-947e6180-b813-11e8-84bb-b35f59e9e9f9.png)

**Comment by JC5** [comment]
Well spotted, fixed.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
