### ISSUE TITLE
Firefly demo - liabilities mention missing

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1691]
**Bug description**
I am running Firefly III version DEMO 4.7.6.2

In Firefly demo - there is no mention of liabilities.

Q: How helpful is it to have separate demo and help texts?

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Go to https://demo.firefly-iii.org/accounts/liabilities

**Bonus points**
Earn bonus points by:
- Add a screenshot
![image](https://user-images.githubusercontent.com/550499/45542120-93503300-b819-11e8-9ab8-c4253bed4e0c.png)

**Comment by JC5** [comment]
Good point, I haven't extended the demo text and content yet. I'll write something. Shouldn't be hard.

**Comment by JC5** [comment]
Oh, and the demo and help text are explicitly separated so I can put emphasis on different things if I need to.
