### ISSUE TITLE
Automate piggy bank saving

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1692]
**Description**
Please describe your feature request:

- I would like Firefly III to help me each period (for example month) to increase the saved amount in piggy bank by constant.

**Solution**
Describe what your feature would add to Firefly III.

Help me think less about reaching my goals.

**What are alternatives?**
Please describe what alternatives currently exist.

Manual.

**Additional context**

I was thinking something like a rule maybe, but rules tied to transactions, and there are none related to piggy banks.

Another option would be to extend the piggy bank model to have the period and amount set.

**Comment by JC5** [comment]
That wouldn't really make sense, since Firefly III is a reflection of your bank account statements. I suggest you put something in your agenda instead :wink:

**Comment by hamuz** [comment]
This is my inspiration in this case: https://www.simple.com/
To be honest, one of the reasons I chose FireFly is to be able to get similar functionality with my existing accounts.
I find their "Safe-to-spend" feature very attractive and missing in FireFly.

**Comment by JC5** [comment]
I find that creating piggy banks on a separate savings account is already an implementation of "safe-to-spend" because the money you can spend is budgeted and on your checking account. The rest of it is locked in piggy banks. That's how I manage my money and that's what Firefly III is modeled on.

[Every month starts](https://firefly-iii.readthedocs.io/en/latest/about/grand-theory.html) with the exact amount you've budgeted on your checking account. That's "safe to spend" right there. No tools needed.

**Comment by ichbestimmtnicht** [comment]
Recurring Transactions are a good step towards it. We need an option to Transfer to Piggy Banks there and we are fine to go, aren't we?

**Comment by JC5** [comment]
:+1:

**Comment by ichbestimmtnicht** [comment]
Nope. You added (wisley) the error that you can't transfer within the same Account. 

Fix: Allow Transfers within the same account when piggy bank is selected or/and show this information.
Further thought about a possible error: Does positive and negative amounts work here?

**Comment by JC5** [comment]
Could you not use the + and - buttons over at the /piggy-banks page? It's what they're for...

**Comment by ichbestimmtnicht** [comment]
Yes I can. We have 'Rundfunkbeitrag' here in Germany. You have to pay 17,50€ for official radios/TVs. (I don't have a TV but this are the only one you possible 'freebies' (Paying this is not a free decision :-1: ) you may wanna watch.) And the only let you pay them quartly, twice a year or yearly. So I like to save my monthly 17,50€ into a piggy bank...
So you may understand why I wanna use this on a regular basis.
