### ISSUE TITLE
Bill doesn't show in default report if bill's date is after report period

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1693]
**Bug description**
I am running Firefly III version DEMO 4.7.6.2

(please give a clear and concise description of what the bug is)

Bill doesn't show in default report if bill's date is after report period

**Steps to reproduce**
What do you need to do to trigger this bug?

1) change health insurance date to 1st of September 2018
https://demo.firefly-iii.org/bills/show/2
2) verify health insurance is missing from August 2018 report
https://demo.firefly-iii.org/reports/default/1/20180801/20180831
3) verify health insurance is present in September 2018 report
https://demo.firefly-iii.org/reports/default/1/20180901/20180930

**Expected behavior**
Bill should appear in report of the month, if there is transaction(s) linked to the bill at that period (regardless of bill date)

**Suggestions / Workaround**
1. Bill date should be back dated to the first bill-linked transaction (keeping the date-in-month intact)
2. Make it work regardless of bill date.

**Comment by JC5** [comment]
Yes, that's intended behaviour, regardless of the fact that you can pre-date transactions.
