### ISSUE TITLE
Bills card on homepage doesn't show different bills, only currency

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1696]
**Bug description**
I am running Firefly III version DEMO 4.7.6.2

Bills card on homepage doesn't show different bills, only currency

**Steps to reproduce**
What do you need to do to trigger this bug?

https://demo.firefly-iii.org/
scroll down to bills card

**Expected behavior**
The pie has a piece for each bill - representing the sum paid for the bill in period.

**Bonus points**
Earn bonus points by:
- Add a screenshot
![image](https://user-images.githubusercontent.com/550499/45559741-fbb80800-b84b-11e8-9bcb-17b50ad39dc4.png)

**Comment by JC5** [comment]
The pie chart is used to signify the paid / unpaid ratio
