### ISSUE TITLE
API: Validations errors redirect to the home page

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [firefly-iii/firefly-iii#1699]
**Bug description**
I am running Firefly III version 4.7.6.2

When you submit a request to the API that isn't correctly formatted, the answer is a 302 redirection to the home page.
What I expect is a JSON-formatted error as per [the documentation](https://firefly-iii.readthedocs.io/en/latest/api/start.html#errors).

**Steps to reproduce**

For example: try to add a category with the key `named` instead of `name`.
![2018-09-16-124041_823x641_scrot](https://user-images.githubusercontent.com/1685403/45595585-a811ff80-b9ae-11e8-82b9-5a61f7a41681.png)
(the screenshots indicates 200 since it followed the redirection)

**Extra info**

I checked that correctly formated informations work as intended.
The redirection might occurs for other errors that the validation ones, I just don't know how to trigger one reliably.
This is the first time I use the API, so maybe it is intended / I made a rookie mistake.

Debug information generated at 2018-09-16 12:28:56 Europe/Paris for Firefly III version **4.7.6**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.6 |
| FF API version | 0.7 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.2.9 |
| Display errors | Off |
| Session start | 2018-09-01 00:00:00 |
| Session end | 2018-10-06 00:00:00 |
| Session first | 2015-05-26 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.11.1 Chrome/65.0.3325.230 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, bcmath, calendar, curl, exif, gd, gettext, iconv, imap, intl, ldap, mysqli, pdo_mysql, pdo_pgsql, pgsql, soap, sockets, zip, apcu, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, barryvdh/laravel-ide-helper@v2.4.3, barryvdh/reflection-docblock@v2.0.4, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.7.1, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/instantiator@1.1.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, filp/whoops@2.2.0, firebase/php-jwt@v5.0.0, fzaninotto/faker@v1.8.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, hamcrest/hamcrest-php@v2.0.0, johnkary/phpunit-speedtrap@v3.0.0, laravel/framework@v5.6.29, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, mockery/mockery@1.1.0, monolog/monolog@1.23.0, myclabs/deep-copy@1.8.1, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phar-io/manifest@1.0.3, phar-io/version@2.0.1, php-coveralls/php-coveralls@v2.1.0, phpdocumentor/reflection-common@1.0.1, phpdocumentor/reflection-docblock@4.3.0, phpdocumentor/type-resolver@0.4.0, phpseclib/phpseclib@2.0.11, phpspec/prophecy@1.7.6, phpunit/php-code-coverage@6.0.7, phpunit/php-file-iterator@2.0.1, phpunit/php-text-template@1.2.1, phpunit/php-timer@2.0.0, phpunit/php-token-stream@3.0.0, phpunit/phpunit@7.2.7, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, roave/security-advisories@dev-master, sebastian/code-unit-reverse-lookup@1.0.1, sebastian/comparator@3.0.2, sebastian/diff@3.0.1, sebastian/environment@3.1.0, sebastian/exporter@3.1.0, sebastian/global-state@2.0.0, sebastian/object-enumerator@3.0.3, sebastian/object-reflector@1.1.1, sebastian/recursion-context@3.0.0, sebastian/resource-operations@1.0.0, sebastian/version@2.0.1, swiftmailer/swiftmailer@v6.1.2, symfony/class-loader@v3.4.13, symfony/config@v4.1.2, symfony/console@v4.1.2, symfony/css-selector@v4.1.2, symfony/debug@v4.1.2, symfony/event-dispatcher@v4.1.2, symfony/filesystem@v4.1.2, symfony/finder@v4.1.2, symfony/http-foundation@v4.1.2, symfony/http-kernel@v4.1.2, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.2, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.2, symfony/stopwatch@v4.1.2, symfony/translation@v4.1.2, symfony/var-dumper@v4.1.2, symfony/yaml@v4.1.2, theseer/tokenizer@1.1.0, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.0, webmozart/assert@1.3.0, zendframework/zend-diactoros@1.8.3,  |

**Comment by JC5** [comment]
Have you added a header `Accept: application/json` to your request? That could be it. 

![screen shot 2018-09-16 at 13 31 39](https://user-images.githubusercontent.com/5889984/45595972-e3afc800-b9b4-11e8-876e-6e535012672d.png)

**Comment by GeoffreyFrogeye** [comment]
Yes, adding it solves the problem, thanks.

Should I add this detail to the documentation?

**Comment by JC5** [comment]
If you would, please. But don't feel pressured.
