### ISSUE TITLE
Adding stocks, and seeing seeing the current value of them

### ISSUE THREAD

**Issue by TobiasDev** [firefly-iii/firefly-iii#1702]
**Description**
I would like to be able to add the stocks I own to Fireflyiii, so and preferably be able to add a API key, so the value also gets updated as the stocks go up or down during a day. 

If we look for example at MoneyDance (another MoneyManager), you can add your stocks as assets in it. And if you get an apiKey from something like Yahoo (or another one), it will update the stocks during certain times of the day to represent the current value of them. 

The reason I would like this is that it helps with represent my net value better. 

If this would be added, I don't really know all the technicallities of it, like I assume I would have to add the stock name (EG. NOK for Nokia, or SQ for Square, etc. and that some is referenced in the api call).

**Comment by JC5** [comment]
Hi!

It's been asked before, and it's not going to be added to Firefly III. Please refer to these issues for more information.

https://github.com/firefly-iii/firefly-iii/issues/844
https://github.com/firefly-iii/firefly-iii/issues/1404

If you have questions or comments, please don't hesitate to reply.

**Comment by TobiasDev** [comment]
Ah, that comment makes sense... I tried looking for it, but didn't see anyone else posting about it... Guess my searching was just bad. But thanks for letting me know. :)
