### ISSUE TITLE
Description field optional? 

### ISSUE THREAD

**Issue by TobiasDev** [firefly-iii/firefly-iii#1703]
Hello! 
Is it possible to make the description field optional? And maybe instead make categories non-optional? 

I tend to just sort my money after my categories and only write a description when it is for something specific I want to remember. Eg. new headphones that has a 2 year warranty. However, currently in the app I must always write a description which I don't think is necessary when I use the category Groceries for example. Like, I don't need to write done where I bought them. :) Not sure this falls into the way you have thought about Firefly iii and if it isn't feel free to close with a comment. :) Just figured I wanted to ask.

**Comment by JC5** [comment]
Mmm, I am not sure if it's possible.

But what some people use might help? They fill in something generic and let the app fill in the rest.

What I do for example, I write down something like "gr-ah" in the description. I have a rule (see `/rules`) that will:

- Change the description to "Groceries" (nice and generic)
- Change the budget, category and expense account (the shop) to Albert Heijn.

I do the same with other stores and places. That could be something for you to consider as well?

**Comment by TobiasDev** [comment]
Hmm, I never thought about expense account as a shop. I do think it is a bit weird not being able to use categories for budget's but like you say, that would give me even more insight in where I buy stuff. Which when you say it isn't really a bad idea. Thanks for the suggestion.

**Comment by JC5** [comment]
No problem! Most people use expense accounts as shops, and revenue accounts for their jobs or other income. The [demo site](https://demo.firefly-iii.org/login) has a neat suggestion of what you could do.

**Comment by TobiasDev** [comment]
Sorry! I should have closed this issue!
