### ISSUE TITLE
Backup and restore data the right way.

### ISSUE THREAD

**Issue by inc-ali** [firefly-iii/firefly-iii#1704]
I am running Firefly III version 4.7.6.2 on a RPi with Docker.

**Description**
How can I backup and restore my data the correct way?
I tried two different methods:
- Just backing up and restore the postgresdb data
- backing up and restoring the firefly_iii_db docker volume.

Using both methods I can successfully restore my data (empty accounts with no transactions), but firefly still shows me the old ' current balance' for the accounts, as well as all the transactions in the overview, which do not exists in the restored backup. 

Am I missing something I must also include in the backup? Or delete after I restored my database?

**Comment by JC5** [comment]
See [this page](https://firefly-iii.readthedocs.io/en/latest/installation/backup.html) in the manual. 

What you need is the database and the app_key. If the app still shows you old values, visit ``/flush`` to clear the cache.
