### ISSUE TITLE
Withdrawal category missing

### ISSUE THREAD

**Issue by gazben** [firefly-iii/firefly-iii#1706]
I am running Firefly III version 4.7.6.2

In the new version the category is missing from the table in /transactions/withdrawal. Can we add it back? It's a nice indicator on what withdrawal has a category (and I should add one if missing).

**Steps to reproduce** 

Go to /transactions/withdrawal page.

**Bonus points**
![image](https://user-images.githubusercontent.com/3780285/45915178-0298d900-be51-11e8-8148-084fe4f29753.png)

**Comment by JC5** [comment]
Yes, I removed most metadata for a cleaner look. I've not yet thought about the best (and most consistent way of replacing it. Stay tuned!
