### ISSUE TITLE
Oauth buttons do not work if you are using webroot in a subdirectory.

### ISSUE THREAD

**Issue by mconway** [firefly-iii/firefly-iii#1709]
**Bug description**
I am running Firefly III version 7.6.2

I had a bug reported on the Mobile App ([here](https://github.com/mconway/firefly-app/issues/12)) that a user is getting a 404 error when pressing the authorize button. I've tracked this down to the OAuth form coming from Firefly-III directly. The form embedded during the authorize process is using a relative URL of "/oauth/authorize". When you have a url root of https://domain.com/firefly, this form breaks the auth flow.

Auth form:
![image](https://user-images.githubusercontent.com/411506/45920011-67553300-be53-11e8-9436-f9b0142af358.png)

Broken:
![image](https://user-images.githubusercontent.com/411506/45920023-7b993000-be53-11e8-88d9-b2448f210247.png)

Here's where the issue is:
```
<div class="buttons">
                            <!-- Authorize Button -->
                            <form method="post" action="/oauth/authorize">
                                <input name="_token" value="" type="hidden">

                                <input name="state" value="" type="hidden">
                                <input name="client_id" value="4" type="hidden">
                                <button type="submit" class="btn btn-success btn-approve">Authorize</button>
                            </form>

                            <!-- Cancel Button -->
                            <form method="post" action="/oauth/authorize">
                                <input name="_token" value="" type="hidden">
                                <input name="_method" value="DELETE" type="hidden">

                                <input name="state" value="" type="hidden">
                                <input name="client_id" value="4" type="hidden">
                                <button class="btn btn-danger">Cancel</button>
                            </form>
                        </div>
```

**Comment by JC5** [comment]
I'll pick this up. In the meantime, please please please change your host so it is directly at the `/` folder instead of `/public/`.

Among other things, your OAuth private key is world accessible which allows anybody to access your data.

**Comment by JC5** [comment]
I've pushed a fix. @TobiasDev, if your refer to the (tiny) changes above, you should be able to fix your own installation for now. I also strongly urge you to fix your hosting situation.

**Comment by mconway** [comment]
Thanks @JC5! I removed the token, it was only for a test account, but i also deleted that oauth client anyway.

**Comment by TobiasDev** [comment]
What should I fix? I'm hosting through NameCheap and the use softoclaus (or what it is called). This is the first app I'm trying to self-host so still learning everything.

**Comment by TobiasDev** [comment]
And I will delete the test account. Was just for some friends to test it.

**Comment by JC5** [comment]
On this page, you can see what I changed and in which file. If you change the exact same thing your installation will be fixed.

https://github.com/firefly-iii/firefly-iii/commit/eefb1c4a47ca03e8817703ef2e282a57b5bbe246

I'll contact the softaculous guys about it. It should install in such a way that /public/ is the web root.

**Comment by TobiasDev** [comment]
Once again thanks! And I changed the same stuff on the server and now I could connect the mobile app! Thanks both of you for helping me! Super excited to try this now and replace my closed source money manager! :)

**Comment by JC5** [comment]
Closed pending the next release this weekend.
