### ISSUE TITLE
How to create bank specific import options

### ISSUE THREAD

**Issue by JamborJan** [firefly-iii/firefly-iii#1711]
I am running Firefly III version 4.7.5.3 (on Sandstorm)

**Description**
I would like to create custom importers to import csv files from Credit Suisse and SwissCard cedit cards. Can you please advise how I best can contribute to make this aviable for all users as import option?

**Steps to reproduce** 
I'm not sure if you want to have a complete separate importer, a import config file or a bank specific option.

**Extra info**
I guess importing Credit Suisse can be done with the available importer and config files. I was not able to import SwissCard so far. For details see the columns description below.

For Credit Suisse accounts, they have these field in CSV:
- Booking date
- Description (multi line text)
- Debit
- Credit
- Valuta date
- Saldo (I guess this can be ignored)

For SwissCard credit cards, they have:
- Transaction Date
- Posting Date
- Card Number (you can have multiple cards on one account)
- Billing Amount (~~always positive, no matter if debi / credi~~)
- Description (multi line text)
- Merchant City (name of a city)
- Merchant State (mostly "000" or empty)
- Merchant Zip (Merchant City zip code)
- Reference Number (external transaction reference code)
- Debit/Credit Flag (important do properly book the Billing amount in column 4)
- SICMCC Code

**Bonus points**
I guess I only can earn bonus points if I implement this as sustainable and reusable as possible :-)

**Comment by JC5** [comment]
The only problem I see is the debit/credit flag. What are the values for debit and credit, respectively?

**Comment by JamborJan** [comment]
Hey @JC5 thanks for your quick reply.

The `Debit/Credit Flag` has two values: 
- `D` for debit, values are e.g. `CHF73.05`
- `C` for credit, values are e.g. `-CHF1'000.00` which is not according to what I wrote before (sorry)

**Comment by JC5** [comment]
Try the “ING specific debit credit indicator”. I believe it’s exactly the same.

**Comment by JamborJan** [comment]
One additional question: what are the field names for amount credi / debi for the importer confit file? I’ll create two files and post them here for anybody else who might need it.

**Comment by JC5** [comment]
They’re all listed in config/csv.php.

**Comment by JamborJan** [comment]
I tested the import. The result: all imported transactions are positive and increase the balance. So that didn't work.

The import file is a bit stupid: when you pay with the card it actually is a positive amount but it should reduce the balance. The flag is `d`, so the import should make a negative transaction and reduce the account balance. When I make a payment, the amount is negative and the flag is `c` and the import is handling it right: the amount is positive and the balance is increased.

**Comment by JC5** [comment]
Apologies. Try the "Rabobank specific debit/credit indicator". Please note that it is case sensitive.

**Comment by JC5** [comment]
Oh and your questions:

- Not yet. The rule actions that you require are scheduled for the next release (see `/rules`).
- I think I will rename the "Rabobank credit/debit indicator" to "Credit/debit indicator" and make it case insensitive.

**Comment by JamborJan** [comment]
That did work. Thanks. I'll send a PR with the two import configurations. When you change the naming I'll update them.
