### ISSUE TITLE
Liability / Mortgage Account: transfers from savings account

### ISSUE THREAD

**Issue by markcs** [firefly-iii/firefly-iii#1714]
I am running Firefly III version 4.7.6.2

I may be misunderstanding how Firefly handles transfers, mortgage accounts and asset/expense accounts.

I've created a mortgage account.  I've created a default asset account.  I transfer money from my savings account to the mortgage account.  My bank doesn't include any information in the csv file of the source or destination accounts.

When I import the csv into the default asset account, expense accounts are created for the transfers.  This is fine.  

How can I link those transfers from the asset account to the home loan, so that the Liability Account (Mortgage account) reduces in value?  

Or is this not how liability accounts are to be used?  (The same would be for the Credit Card Liability account)

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
First of all, you're completely right in the way you use liabilities. Do note that the "credit card" liability is due to [disappear](https://github.com/firefly-iii/help/wiki/Credit-card-liabilities) in the future. 

You can convert each transaction from the `/transactions/show/x` page into the transaction type of your choice. So in this case, from deposits to transfers.

The next version of Firefly III will introduce new rule actions that allow you to automate this. Check out the `/rules` section if you haven't already. Specifically, the next version will introduce the "convert to transfer" action.

Does that answer your questions?

**Comment by Traxxi** [comment]
Hello!
I have also a question about transferts to liabilites accounts : does the next version will make possible to put a budget on theses transferts? and theses transferts could "pay" a bill ?
In the current version, this is not possible (apparently).

Thank you for the precision, and also for this great app ! :)

**Comment by markcs** [comment]
Hi James,

It kind of does.  When I go and select the option to change the withdrawal into a transfer, I see the text _'If you convert this withdrawal into a transfer, A$xxxxx will be transferred from Bank Account Name to a new asset account, instead of being paid to INTERNET TRANSFER HomeLoan MCampbellSmith._

I am not given the option to transfer this into my actual Mortgage account, which I created as a 'Liability' account.  

So should I actually create an Asset Account?  Does it matter what type of Asset account account I create and then I'm a bit confused as to how (and when) to use the Liability Accounts ?

**Comment by JC5** [comment]
@markcs good point. If the liability is not in the dropdown, please wait for the next release, where it will be.
@Traxxi that won't be possible _yet_. I am still figuring out where liabilities fit in the grand scheme of things. It could be that I will reclassify these transfers as expenses and income. When that happens, what you ask will be possible.

**Comment by markcs** [comment]
@JC5 thanks for the update. I'll wait for the next release.

So now that Firefly has liabilities accounts, why not keep the credit cards here and remove them from the assets accounts?  I've never understood why a Credit Card would be an 'asset' as it is not normally handled that way is it?

I don't plan on using the interest calculations you have included, as I'll be importing my statements from my bank, which will include that.

**Comment by JC5** [comment]
Personal preference mostly. Setting the credit card as a liability is technically more correct but I see credit cards as just another payment method. I know it's a debt and therefor a liability (technically speaking) but to me it's just another bank account that happens to "sync" with my checking account every now and then.

Actual debts are interesting as liabilities. Credit cards? Meh.
