### ISSUE TITLE
How to see IBAN in transaction?

### ISSUE THREAD

**Issue by sachawolf** [firefly-iii/firefly-iii#1715]
I am running Firefly III version 4.7.6.2

And some other questions.
- Is it possible to see the raw data in an imported transaction? For example the IBAN number of both source and destination.
- What is the best way of dealing with personal bank accounts that have been deleted? I have lot of transactions from a back account that no longer exists. So these are now seen as revenue/income. Would it be best to create an asset account and manually change these transactions to transfer, or is there a better option?
- Is there a way to mass change a lot of transactions to transfers?
- When adding a new asset account, when it gives an error that the IBAN already appears to be in use, please give a link to where it is in use. Especially since using the search with this IBAN shows no results.

**Comment by JC5** [comment]
* Where would you like to see the IBAN? Generally speaking, it's hidden to show the more user-friendly name.
* I suggest you set them to inactive and leave the transactions be. Keep the account included in your reports (that's the only place where they would count as income).
* Not yet. The next version of Firefly III will contain an action called "convert to transfer" that you can combine with other checks in a rule (see `/rules`).
* At the moment, I can't do either I'm afraid. But it's on the list for future releases :+1:

**Comment by sachawolf** [comment]
Apologies, I have been a tad busy the last week.

- In the mouse-over, or when showing all the transactions for one account show the IBAN withing brackets after the user-friendly name. I would like to see the IBAN as a check that I am indeed looking at the correct account. I have for example several accounts (some of which no longer exist) with my name as friendly, but different IBAN numbers. So the friendly names becomes quite confusing in those circumstances.
- Ok, leaving the transactions be sounds fine.
- It no longer is an issues, I've been playing around with where and how I wanted to Firefly-III. So I started over from scratch a couple of times. I have it running in a docker container now, and I first added the accounts before importing everything. But having the option is always nice.
- Ok, I'll keep checking future releases then.

Now some other things I have found that might be interesting:
- When looking at a transaction overview (either under an account or the transactions overview) you have the option to select all transactions. When using the Search screen, there is no select all. You have to manually select all the transactions that you would like to bulk edit.
- I use Bunq top-up requests to transfer money from my ING (where my income is debited) to my Bunq accounts. These are ideal links. These tend to show up twice. Once as a transfer (when read from my Bunq statements) and once as a credit (when read from my ING statement). For now I have manually deleted the credit transactions to clean it up. But some way of detecting that these are the same would be nice.
- How can I link transactions to a Liability? I am paying off a student loan (will be for some time to come), and I don't really see a way of doing this.

The answers are much appreciated! :)

**Comment by JC5** [comment]
Sorry, I completely forgot about your question. I'll find some time to answer later!

**Comment by JC5** [comment]
* I can add the IBAN's as a title when available, no problem.
* The search screen has a functional "select transactions" button at the bottom. Could you report problems you find?
* This is possible, when during the import from ING, the credit is recognized as a transfer. That means you must link the bunq account mentioned in the ING statement to your own bunq asset account. If that works, and the descriptions are equal, Firefly III can recognize the transfer. Otherwise, Firefly III has nothing to go on.
* You can simply transfer money to the liability. Admittedly, this is not a perfect solution and I haven't found the right way to implement this yet. I'm open to suggestions.
