### ISSUE TITLE
Apply rules to transactions added using API

### ISSUE THREAD

**Issue by itpony** [firefly-iii/firefly-iii#1717]
**Bug description**
I am running Firefly III version 4.7.6.2

I am using firefly-app (https://github.com/mconway/firefly-app) for on-the-go transaction inserts. But I noticed that at least one rule is not being applied to transactions created using the app.

**Steps to reproduce**
1. Create rule that puts transactions of category "Food and Drinks" to budget "Food"
2. Pair the app with Firefly-iii using Oauth2
3. Create transaction with category "Food and Drinks"

**Extra info**
I did not test the API itself because I was not able to get Oauth working. But as I looked into code of the app, it seems it is not sending the Budget with the transaction, so it should not impact the rule.
When I create the same transaction using web browser, the rule is applied correctly.

**Bonus points**
If there is more information to post, I am happy to do it, but I did not see anything relevant.

**Comment by mconway** [comment]
I just tried this myself with the same result. I don't use a lot of auto rules for transactions, so I've never noticed. I wonder how much my reports have been off now... :)

**Comment by JC5** [comment]
Thanks for reporting, I'll check it out.

**Comment by JC5** [comment]
It should be fixed in the new release.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
