### ISSUE TITLE
Issues with reconciliation

### ISSUE THREAD

**Issue by itpony** [firefly-iii/firefly-iii#1718]
**Bug description**
I am running Firefly III version 4.7.6.2

I have some issues with Reconciliation. When I reconcile account, I think split transactions should be added pu. In my bank statement, I have one transaction. I use split transaction to have one transaction in multiple budgets. But in my reconiliation page, it is shown separate, so I have trouble pairing the transactions.
Also I noticed that when I save transfer as reconciled in one account, it is already saved as reconciled when reconciling the other account.

**Extra info**
I am using Firefly-III on Debian server with PHP7.2, as client I have Firefox on Windows 7.

**Comment by JC5** [comment]
Hi,

What exactly would you like me to do with split transactions? I am not sure how exactly you're splitting them right now, so I am not sure what I should do with them.

And yes, transfers will reconcile over both accounts. That's not something I can help unfortunately.

**Comment by itpony** [comment]
Hi,

ad split transactions - I use it to have one transaction in multiple budgets. For example food, alcohol, electronics.

In bank statement is is one line with total sum, but in Firefly, it is separated. I think the transaction should be grouped together and total sum should be shown - as is on bank statement. Now I have to get calculator and add the values manually to check if it is OK. And if I have two split transactions next to each other, there would be trouble to see what transaction it belongs to.

**Comment by itpony** [comment]
OK, thanks for explanation. I will have to live with that.
