### ISSUE TITLE
Mortage Liabilities are not returned via API query to /accounts or /accounts?type=all

### ISSUE THREAD

**Issue by mconway** [firefly-iii/firefly-iii#1719]
**Bug description**
I am running Firefly III version 4.7.6.2

Doing queries with accounts, it seems that the Mortgage account type is not being included when not explicitly calling type=liabilities. I've tried this on both my own instance as well as the demo instance. 

**Steps to reproduce**
Call /accounts or /accounts?type=all from the API

**Comment by JC5** [comment]
Nice find. I'll expand the API to include them.

**Comment by mconway** [comment]
Thanks! What was insteresting to me was that they are returned when using ?type=liabilities. I poked through your code a bit, and the closest i think I got was that it was in the app config somewhere.

**Comment by mconway** [comment]
Ahh ok I see now. Just out of curiosity, why did you seem to deviate from the way other account types work? For asset, revenue and expense, you had one type, then used roles to sub divide those types. I would have expected a liabilities type with roles within it. I'm sure there's a reason, just want to understand more.

**Comment by JC5** [comment]
Closed pending the next release this weekend.

**Comment by mconway** [comment]
So in regard to my question about roles vs type: I understand liabilities are different than assets. What I meant was with assets you have a type "Asset account" then many roles within it. With liabilities, there is no "liability account" with roles such as "mortgage, loan" etc. I was just curious as to why.

**Comment by JC5** [comment]
Ultimately, it's easier to select on account type then it is on role.
