### ISSUE TITLE
Transaction type not working in non-English languages

### ISSUE THREAD

**Issue by dasbaumwolltier** [firefly-iii/firefly-iii#1720]
**Bug description**
I am running Firefly III version 4.7.6.2

If I chose a transaction type on a non-English version of firefly it won't let me save the rule until I use the non-English term as trigger value. However if I use the non-English term, the trigger won't match any transactions.

**Steps to reproduce**
* Change the language to any non-English
* Create a new rule 
* Use transaction is of type.. trigger
* Try to save it with "Deposit"
* Try to match any transactions with the non-English word for "Deposit"

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

**Bonus points**
Earn bonus points by:
Is reproducible on the demo site (see second screenshot)

![image](https://user-images.githubusercontent.com/27744710/45941457-89c78780-bfde-11e8-9dc9-107bd43ad85e.png)
![image](https://user-images.githubusercontent.com/27744710/45941517-d317d700-bfde-11e8-99f1-823e4a6e548d.png)
![image](https://user-images.githubusercontent.com/27744710/45941494-b5e30880-bfde-11e8-80d1-3dc84ae3de2c.png)

**Comment by JC5** [comment]
I see. I'll make it work again, thanks for reporting. Please note that the transaction type trigger will not be localized.

**Comment by hamuz** [comment]
> Please note that the transaction type trigger will not be localized.

Why? the form can't pass back the id of transaction type rather than text value?

**Comment by JC5** [comment]
Closed pending the next release this weekend.
