### ISSUE TITLE
 ERROR: php artisan migrate:refresh --seed

### ISSUE THREAD

**Issue by tonyrulez** [firefly-iii/firefly-iii#1721]
I am running Firefly III version 4.7.6.2 on PHP7.1 with MariaDB.

**Description**
I'm trying to install Firefly. Successfully installed composer, created database and modified the .env file, and when running `php artisan migrate:refresh --seed`, I get this error:

```
In Connection.php line 664:

  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'firefly.
  account_meta' (SQL: drop table `account_meta`)

In PDOStatement.php line 144:

  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'firefly.
  account_meta'

In PDOStatement.php line 142:

  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'firefly.
  account_meta'
```
I know these errors should enlighten me to fix it, but I'm a beginner in this field. If further logs are needed, I'll provide them, I just don't know where to look.

**Steps to reproduce** 
Install PHP7.1 and dependencies
Install composer
Install firefly
Create database
Edit .env
Run the command above

**Extra info**
OS: Debian 9.5

**Comment by tonyrulez** [comment]
Thanks!

I cleared the database, and now it worked. Only I get HTTP ERROR 500 when I open the public page, so I'll need to fix this in apache.

**Comment by JC5** [comment]
Make sure you configure apache so /public/ is the webroot or you will expose private data to the world.

**Comment by tonyrulez** [comment]
Yes, I set it to public after the warning came up. But it's interesting that it worked but not the public page.

**Comment by tonyrulez** [comment]
As a matter of fact, I get this error in the apache error log:

[Mon Sep 24 12:45:43.544347 2018] [:error] [pid 10335] [client 165.225.84.80:6783] PHP Fatal error:  Uncaught Error: Call to undefined function bcscale() in /var/www/firefly-iii/bootstrap/app.php:37\nStack trace:\n#0 /var/www/firefly-ii$

**Comment by JC5** [comment]
https://firefly-iii.readthedocs.io/en/latest/support/faq.html#i-get-bcmath-errors

**Comment by tonyrulez** [comment]
Thank you, I set `bcmath.scale = 2` in php.ini. Now I get DNS error (the host name of the page you are looking for does not exist).

**Comment by tonyrulez** [comment]
Checked Google for tips, but this is how it's supposed to work.

Installed php7.1-bcmath
set bcmath.scale to 2
restart apache2

Still PHP ERROR 500 with the same problem in apache log :(

**Comment by JC5** [comment]
The scale should be at least 12 for Firefly III to work properly. What's the exact error? Could you copy paste from the logs?

**Comment by JC5** [comment]
Mmm. Perhaps /var/log/php somewhere?

The 500 error is caused by php so perhaps php has it logged. 

Also check /firefly-iii/storage/logs

**Comment by tonyrulez** [comment]
There is no /var/log/php folder.
firefly log file that I found: https://pastebin.com/4EaXKuUS

I'll keep looking for the PHP error log

**Comment by JC5** [comment]
Not sure what the folder is called just check for php related stuff in /var/log

I’m on mobile will check the log later

**Comment by tonyrulez** [comment]
Haven't found any php log file there.
Then I added `error_log = /var/log/php_errors.log` to php.ini, restarted apache and tried opening again the website but no php log was created.

**Comment by JC5** [comment]
Mmmm. The log file you shared doesn't seem to contain errors related to this issue. If you could delete the log file from Firefly III we can be sure (if it's a Firefly III error the log file would be recreated).

In the mean time, Google instructions on how to make PHP log (you also need to enable it, I think?). At least turn on display_errors in your php.ini.

**Comment by tonyrulez** [comment]
I followed this instruction: https://davidwinter.me/enable-php-error-logging/
The error log file remains empty. Hmmm...

**Comment by JC5** [comment]
OK if nothing is created by Firefly III then it's definitively not Firefly III. If the error log remains empty there's not much I can do. Are you editing the correct php.ini file? Many systems have two, one for the CLI and one for Apache.

**Comment by tonyrulez** [comment]
My PHP got updated from 7.1 to 7.2. In Webmin I enabled error logging into the /var/log/php-errors.log both for 7,1 and 7.2 and for apache2/cgi/cli ini files. Total there are 6 php.ini files modified to write into the log. File remained empty. Then I set them to write directly into syslog, but no PHP error showed up.

Thanks for your help 👍
