### ISSUE TITLE
Fullscreen in Chrome on Android

### ISSUE THREAD

**Issue by WhiteNoseThunderPants** [firefly-iii/firefly-iii#1725]
**Description**
Please describe your feature request:

I would like for FF to open in fullscreen on Android once the webpage has been added to the Android homescreen. The Web App Manifest on the link below is what, I think, needs to be done. I am not a developer, just a very happy user of FF, but I will try to look into this myself in the mean time.

This is one feature from home Assistant & Kanboard that I very much enjoy and would love to see it in FF.

https://developers.google.com/web/fundamentals/native-hardware/fullscreen/

EDIT: I would be happy to contribute if someone could point my in the general direction of where in the code this would need to be done.

**Comment by JC5** [comment]
This is the file:
https://demo.firefly-iii.org/manifest.json

You could submit a PR to the develop branch and add this line to the file (it's in the public dir):

```
"display": "fullscreen",
```

It's the only thing that's different. I guess they added this as a feature somewhere during the last few years. I never had to define it before to make it work.

**Comment by WhiteNoseThunderPants** [comment]
@JC5 that is what I was thinking, but then I looked at other projects that adding to the home screen worked as expected, and there manifest.json looks the same as the one for FF. I'm not sure why it does not work as expected on my phone. I am going to try modifying on my install to fullscreen and see if it changes anything.

**Comment by JC5** [comment]
I'm sorry, I have no clue! It could be a setting in Chrome or in your system. I remember Android being tricky about fullscreen apps. But I moved to Apple (sorry) so I can't check it anymore.

**Comment by JC5** [comment]
Found the problem. The manifest is not loading due to a misconfigured Content Security Policy. I can fix that.

**Comment by JC5** [comment]
Fixen by @BoGnY in #1963
