### ISSUE TITLE
Problem editing expense accounts

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#1726]
**Bug description**
I am running Firefly III version 4.7.6.2

When I go the the expense accounts and try to edit any of them, I get the following error message:
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:
Trying to get property 'id' of non-object

**Steps to reproduce**
Go in Accounts > Expense accounts and edit any of the accounts listed, they all get the same error message (I did not tried all of them as a have a huge amount...)

**Extra info**
Debug information generated at 2018-09-25 05:21:38 UTC for Firefly III version **4.7.6.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.6.2 |
| FF API version | 0.7 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | error,  |
| PHP version | 7.2.9-1 |
| Display errors | Off |
| Session start | 2018-09-01 00:00:00 |
| Session end | 2018-09-30 23:59:59 |
| Session first | 2006-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | 'unknown' |
| Trusted proxies (.env) | 10.10.10.254 |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, mcrypt, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.5, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.38, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.4, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.46, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.4, symfony/css-selector@v4.1.4, symfony/debug@v4.1.4, symfony/event-dispatcher@v4.1.4, symfony/finder@v4.1.4, symfony/http-foundation@v4.1.4, symfony/http-kernel@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.4, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.4, symfony/translation@v4.1.4, symfony/var-dumper@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.5,  |

**Comment by MacPaille** [comment]
Hey, thanks for the quick reply!
I upgraded when the 4.7.6.2 was available. One point maybe is that I also migrated from one raspberry pi to another when I was running 4.7.6.0 I think.

**Comment by JC5** [comment]
Ok, please make sure you run all commands from the upgrade guide:

php artisan migrate --seed
php artisan cache:clear
php artisan firefly:upgrade-database
php artisan firefly:verify

**Comment by MacPaille** [comment]
migrate --seed is the only command I was not running after an upgrade, I was running --env=production.

Now it seems better but I have randomly this error appearing:
file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/08/48/0848216ff587ef6ce56cc5d0839230f85dd3365a): failed to open stream: No such file or directory

This one is when I go into the Expense Accounts and I click on page 28. Some pages are appearing correctly but most of them gives me such error message...

Any advice?

**Comment by JC5** [comment]
Mmmm. Clear the cache, make sure the directory is owned by the web user? You can try to browse to ` /flush` that helps some times.
