### ISSUE TITLE
Allow for different backing storage in Firefly

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1727]
**Description**
Please describe your feature request:

As a Heroku user, I would like Firefly III to be able to save files (import/export/attachments/logs) in different storage locations. This is important because Heroku has ephemeral filesystem.
Read more at: https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

I would prefer to use off-site SFTP or FTP (in that order). 

**Solution**
Describe what your feature would add to Firefly III.

Ability to persist uploaded files after dyno restart.

**What are alternatives?**
Please describe what alternatives currently exist.

I've researched a few:
1) No additional packages: Laravel supports the FTP adapter for storage.
in this option we just edit https://github.com/firefly-iii/firefly-iii/blob/d49a13b0916c6c9ae065bacf8471e95c67877edc/config/filesystems.php#L73-L80
to use ftp driver (with its configuration from environment, if such available).
I envision in this case some `if`-s before the `return` , or some ugly ternary inside the return to get this right.

2) Use fallback driver - requires https://github.com/Litipk/flysystem-fallback-adapter
Allows to fallback to to remote storage if not available locally. Not exactly what we want, because writes are only local, and we need to provide a service provider for Laravel (too lazy for that).

3) Use:
* https://github.com/danhunsaker/laravel-flysystem-others
* https://github.com/Litipk/flysystem-fallback-adapter
* https://github.com/thephpleague/flysystem-replicate-adapter
* https://github.com/thephpleague/flysystem-sftp
First of all first package registers with Laravel different service providers (if available, after including in composer.json).
Second of all it provides the 'Mirror' meta-adapter which combines fallback adapter (mentioned before), and replicate adapter to fallback on reads, and also to distribute writes.
https://github.com/danhunsaker/laravel-flysystem-others/blob/43c5e3bf8cbb9bc22a2e228cb644882f0be52f29/config/filesystems.php#L297-L300
Third, and last, this opens up the possibility to easily use wide range of backing storage in the future (like Dropbox, for example).
https://github.com/danhunsaker/laravel-flysystem-others/blob/43c5e3bf8cbb9bc22a2e228cb644882f0be52f29/config/filesystems.php#L40-L44

My recommendation is to use the last option, because it's the easiest (drop packages to composer and edit filesystems.php) and allows many options in the future. I'd be happy to implement this with your blessing.

The GUI side is more tricky, but enabling this feature with some environment variables will be easy.
______

In any case, code such as this:
https://github.com/firefly-iii/firefly-iii/blob/bc4ac303e210d63d1c33ff4c515cd61af1dd625a/tests/Unit/Helpers/Attachments/AttachmentHelperTest.php#L59
and
https://github.com/firefly-iii/firefly-iii/blob/bae40e2cbc14a34f67f96db2a3faa9a1b3a39515/app/Export/Exporter/CsvExporter.php#L64
found using https://github.com/firefly-iii/firefly-iii/search?q=storage_path&unscoped_q=storage_path
need to be updated to use the right disk (thru a facade?) rather than to assume its local (I guess that what storage_path does)

@JC5

**Comment by JC5** [comment]
Sounds like a good idea. I'll do some digging!

**Comment by hamuz** [comment]
Any suggestions other than mine? Would you be willing to accept a PR for this?

**Comment by JC5** [comment]
Not yet, I'll keep you posted.

**Comment by JC5** [comment]
I'll close it. I'll do some testing to see if everything works as expected. Personally, I would not start on other backends just yet. The disadvantage of all these new features has pushed the `.env` file to a whopping 172 lines.
