### ISSUE TITLE
Cronjob not running because of error in TransactionFactory.php

### ISSUE THREAD

**Issue by TobiasDev** [firefly-iii/firefly-iii#1728]
**Bug description**
I am running Firefly III version 4.7.6.2

I can't get my cronjob running for recurring transactions. My main currency is EUR.

I have run the cron job via SSH and received the following output:
Argument 1 passed to FireflyIII\Factory\TransactionFactory::findCurrency() must be of the type integer or null, string given, called in /home/www/mydomain.com/app/Factory/TransactionFactory.php on line 101

**Steps to reproduce**
Run a cronjob through SSH and I get the error. I haven't done anything extra except that.

**Comment by JC5** [comment]
Strange. I'll check it and get back to you.

**Comment by TobiasDev** [comment]
Thanks!

**Comment by JC5** [comment]
I've pushed something that should fix this.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
