### ISSUE TITLE
Edit of multiple transactions switches order of transfer accounts

### ISSUE THREAD

**Issue by Ludo444** [firefly-iii/firefly-iii#1729]
Hi,
if I select multiple transactions and edit them the transfers are shown two times, which is fine. The problem is when it is saved, then I suppose the code which is handling the update ignores the original From/To accounts and switches them.

Basically the original From account becomes To account and To account becomes From account.

**Comment by JC5** [comment]
Mmm that's not supposed to happen of course. I'll check it out. Thanks for reporting!

**Comment by JC5** [comment]
This will be fixed in the next release.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
