### ISSUE TITLE
Add a search API

### ISSUE THREAD

**Issue by miyoyo** [firefly-iii/firefly-iii#1730]
**Description**
- Firefly III's search function is an important tool to sift trough thousands of transactions, yet it's not available as an API.

**Solution**
- API Users would be able to use the search to quickly find transactions

**What are alternatives?**
- Get all transactions using `/api/v1/transactions` and filter clientside, this will download explicitly unused data and might cripple mobile app developpers.

**Comment by JC5** [comment]
Good idea, I'll write it down. :+1:

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947668
