### ISSUE TITLE
No option to disable types of email

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#1733]
**Description**
I would like Firefly III to allow me to choose which emails are sent. Essentially I don't want the actual detail of my transactions being sent to my email address, maybe just a summary at best. Don't trust email providers that much!

**Solution**
Suggest that under Options > Preferences there be a section allowing you to opt in/out of certain system emails.

**What are alternatives?**
If not possible to make it configurable by user prefs, perhaps in config? or just remove excessive detail from the email.

**Comment by JC5** [comment]
Good idea. I'll add it to the .env file, like other types of messages.
