### ISSUE TITLE
Can't edit initial balance transaction in account detail view

### ISSUE THREAD

**Issue by gabuzi** [firefly-iii/firefly-iii#1735]
**Bug description**
I am running Firefly III version 4.7.6.2

The edit button pertaining to the "initial balance for '...'" transaction has no effect.

**Steps to reproduce**
What do you need to do to trigger this bug?
Fresh install. Created a new currency. Entered initial amounts in the first-run wizard. Then navigate to the automatically created checking or savings account and press the edit button next to the "initial balance for '...'" transaction.

**Extra info**
The initial balance wizard by default sets the current date as the opening date. I wanted to set the initial balance to the value from the beginning of the current month to be able to import all transactions of the current month. I was able to make the change via the edit button in the asset accounts list. 

Debug information generated at 2018-09-26 23:52:16 Europe/Amsterdam for Firefly III version **4.7.6.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.6.2 |
| FF API version | 0.7 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.20-1+0\~20180910100532.3+stretch\~1.gbp17c613 |
| Display errors | Off |
| Session start | 2018-09-01 00:00:00 |
| Session end | 2018-09-30 23:59:59 |
| Session first | 2018-09-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache, xdebug |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.5, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.38, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.4, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.46, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.4, symfony/css-selector@v4.1.4, symfony/debug@v4.1.4, symfony/event-dispatcher@v4.1.4, symfony/finder@v4.1.4, symfony/http-foundation@v4.1.4, symfony/http-kernel@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.4, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.4, symfony/translation@v4.1.4, symfony/var-dumper@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.5,  |

![screen shot 2018-09-26 at 23 53 53](https://user-images.githubusercontent.com/15203081/46111860-cb2b8300-c1e8-11e8-86d8-0e10e132669d.png)
![screen shot 2018-09-26 at 23 57 39](https://user-images.githubusercontent.com/15203081/46111861-cbc41980-c1e8-11e8-870d-9b1bb06ba9bc.png)

**Comment by JC5** [comment]
Thanks for the nice report!

What you see is intentional. The opening balance is edited through the account it comes from. I'll see if I can add a message to explain this.

**Comment by gabuzi** [comment]
Thanks for taking a look at my issue. I actually thought about this being intentional, but the lack of any hint let me believe that it was a bug.
A message explaining that if one would like to change the initial balance properties, the account configuration page is the place to do so, would be a nice addition indeed. Maybe that's only me, but the edit button next to the initial balance transaction seemed as a really intuitive way to change these properties. Is there no chance that the edit button for the initial balance would redirect to the account configuration page?

**Comment by JC5** [comment]
Should be a nice addition to the message. :+1:
