### ISSUE TITLE
Monthly summary of asset account doesn't count transfers

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1736]
**Bug description**
I am running Firefly III version 4.7.6.2@DEMO
(please give a clear and concise description of what the bug is)

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Go to https://demo.firefly-iii.org/accounts/show/34
2. Make sure at least one of the transactions shown is a transfer, if not transfer funds from another asset account
3. Notice the monthly summary equals the sum of all withdrawals for "Spent", and sum of all deposits for "Earned"

**Expected behavior**
1. Sum of transfers where asset is destination is added to the sum of deposits for "Earned"
2. Sum of transfers where asset is source is added to sum of withdrawals for "Spent"

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

**Bonus points**
Earn bonus points by:
https://demo.firefly-iii.org/accounts/show/34

![image](https://user-images.githubusercontent.com/550499/46142078-70cd0980-c25e-11e8-8c64-d214bd141471.png)

**Comment by JC5** [comment]
I can add a separate box for transfers, that seems best.

**Comment by hamuz** [comment]
Why? if a transaction had been a withdrawal (for example, bank -> cc payment), it would show correctly as spent money in bank.
But now that I transferred it to CC account, it doesn't count, which seems odd to me. I would expect it to stay the same.

To make a distinction, maybe it is possible to add the amount transfered (in/out) appear in some "alt" on hover of the total sum. 

In my opinion it should be part of the sum (in each case in/out [earned/spent]).

**Comment by JC5** [comment]
Transactions between asset accounts are transfers. The expense is the original withdrawal from the CC account.

Transactions between asset accounts and liabilities are also transfers, but that may change in the future.

**Comment by moussaclarke** [comment]
In the context of an individual bank account, you might well want to include transfers in spent/earned, even if they aren't really "spent" as far total your assets are concerned. Maybe a transfer box like you suggest (showing both in and out totals?) or an 'include transfers' toggle/setting?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947712
