### ISSUE TITLE
Crash when trying to upload not existent file

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1737]
**Bug description**
I am running Firefly III version 4.7.6.2@DEVELOP

(please give a clear and concise description of what the bug is)

**Steps to reproduce**
What do you need to do to trigger this bug?
1. go to import file
2. set path to upload to not existing file
3. upload

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

**Bonus points**
Earn bonus points by:

- Post a stacktrace from your log files
- Add a screenshot

![image](https://user-images.githubusercontent.com/550499/46143325-454c1e00-c262-11e8-85ca-43396cc90258.png)

Whoops! An error occurred.

Unfortunately, this error was not recoverable. Firefly III broke. The error is:

SplFileObject::fread(): Length parameter must be greater than 0

More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.

If you cannot find the cause of this error or when you need some help, please open a ticket on GitHub.

**Comment by JC5** [comment]
Will be fixed in the next release.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
