### ISSUE TITLE
nginx reverse proxy content-security-policy issue

### ISSUE THREAD

**Issue by LucaNerlich** [firefly-iii/firefly-iii#1739]
I am running Firefly III version 4.7.6.2

Hello,

ive installed Firefly via dockerhub on my cloud vm, all is working fine. Iam now trying to access it via https (lets encrypt is setup correctly, I can reach the base domain via https just fine.)

Firefly runs as a docker under port :90. Its accessible and fully functional.
But whenever I try to access it via https, certain CSP headers (e.g base-uri and form-action) are not set.

Current nginx.conf (relevant excerpts):

`
location /firefly/ {
   proxy_pass http://mydomain.com:90/;
}
`

ive tried to inlcude in the above 
`
 add_header Content-Security-Policy "form-action 'self'; base-uri 'self' ";
`

or

`
proxy_set_header Content-Security-Policy "form-action 'self'; base-uri 'self' ";
`

I have also tried the same commands with a '*' instead of 'self'.

Does anyone know, what I am doing wrong?
Any help is greatly appreciated.

Screenshots:

Browserconsole Error:
https://imgur.com/a/2eBvNZy

Header Example:
https://imgur.com/a/MyOYWo6

**Comment by LucaNerlich** [comment]
Forgive me for the stupid question, but how would I go about disabling that line? fork and comment?

**Comment by JC5** [comment]
For now, use bash to enter your docker container:

`docker exec -it <container> bash`

Find the file (it's at `/var/www/firefly-iii` somewhere) and comment it out with either a `#` or `//`.

Just to see if that resolves it. No need to restart anything, the effect should be immediate.

**Comment by BamButz** [comment]
I got the same problem.

As soon as I submit the form I receive the following error
Refused to send form data to 'http://xxx/register' because it violates the following Content Security Policy directive: "form-action 'self'".

My setup is also behind a reverse nginx proxy (https://github.com/jwilder/nginx-proxy)

What surprised me is that the form tried to send the request over HTTP although my call was made via HTTPS.
Setting the APP_URL environment variable did not help either.

Maybe would it solve the problem if the form would submit to HTTPS.

**Comment by JC5** [comment]
In both your cases, Firefly III is not able to detect the URL your reverse proxy serves it under. Have you set `TRUSTED_PROXIES` to `**`?

**Comment by BamButz** [comment]
I found it myself in your documentation.
Setting TRUSTED_PROXIES to ** did solve the problem.
Thanks for your fast reponse and awesome work your doing here. 👍

**Comment by LucaNerlich** [comment]
@BamButz could you maybe post your nginx .conf file?
Iam not getting this to work.

Ive set this->proxies = '**'; 

and commented the other lines.
No change.

**Comment by JC5** [comment]
You can edit TRUSTED_PROXIES in the `.env` file and Firefly III will pick it up from there.

**Comment by LucaNerlich** [comment]
that also didnt work. I think something is not correct with my nginx .conf. I Hope @BamButz sees this and could post his.

Ill try to post the relevant stuff below:
```
server {
    listen      80;
    listen [::]:80;
    server_name xxx.de www.xxx.de;

    location / {
        rewrite ^ https://$host$request_uri? permanent;
    }

    #for certbot challenges (renewal process)
    location ~ /.well-known/acme-challenge {
        allow all;
        root /data/letsencrypt;
    }
}

#https://xxx.de
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name xxx.de;

    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/xxx.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxx.de/privkey.pem;

    ssl_buffer_size 8k;

    ssl_dhparam /etc/ssl/certs/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;

    ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

    ssl_ecdh_curve secp384r1;
    ssl_session_tickets off;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8;

    return 301 https://www.xxx.de$request_uri;
}

#https://www.xxx.de
server {
    server_name www.xxx.de;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    location / {
        #security headers
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-Frame-Options "DENY" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "frame-src 'self'; default-src 'self'; script-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; form-action 'self'; upgrade-insecure-requests;" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    }     

    server_tokens off;

    ssl on;

    ssl_buffer_size 8k;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

    ssl_ecdh_curve secp384r1;
    ssl_session_tickets off;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4;

    ssl_certificate /etc/letsencrypt/live/xxx.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxx.de/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;
}

#https://www.xxx.de/firefly
server {
    server_name www.xxx.de/firefly;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    location / {
        #security headers
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-Frame-Options "DENY" always;
        #CSP
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "script-src * 'unsafe-eval'; style-src *";

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:90;
    }     

    server_tokens off;

    ssl on;

    ssl_buffer_size 8k;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

    ssl_ecdh_curve secp384r1;
    ssl_session_tickets off;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4;

    ssl_certificate /etc/letsencrypt/live/xxx.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxx.de/privkey.pem;
}
```

**Comment by BamButz** [comment]
Hi @LucaNerlich,

as i said im using the reverse proxy from jwilder.
Thats a docker image that is using enviroment variables on your other docker containers to automagically configurate your nginx proxy.

On his repository he posted the following default nginx settings:

```
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;

# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
```

I hope it can bring some light into your problem.

**Comment by LucaNerlich** [comment]
Thanks for your response, but this also didnt help. Some of these vars are undefined at my side - no Idea where he retrieves them from.

I am at a loss so far. Ill keep googling - but currently no idea what to do to fix it.

**Comment by LucaNerlich** [comment]
@BamButz wow it took literally 5mins to get the jwilder container forwarding working. Now ill try to include the lets encrypt companion container. What a life saver :)
