### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by JamborJan** [firefly-iii/firefly-iii#1741]
**Bug description**
I am running Firefly III version 4.7.5.3 on Sandstorm

After a while using the app, importing data, checking stuff, adding rules, no matter what, I get a "502 bad gateway" error message.

![bildschirmfoto 2018-09-28 um 19 21 41](https://user-images.githubusercontent.com/7508960/46224034-66da0200-c355-11e8-8402-3934c2950e48.png)

**Steps to reproduce**
Unfortunately I'm not able to 100% reproduce the issue. I only can say that it happens a lot after a while. E.g. I imported 2 or 3 files and it happens. I multi-select a bunch of records and edit them, after the second or third batch it happens.

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

OS: macOS (latest)
Browser: Brave
Debug output: is this the same for every sandstorm instance? If not, let me know if it makes sense to paste it here.

**Bonus points**
Earn bonus points by:

Unfortunately there is no stacktrace from the log files, only:

```
Truncated from this point <----|
```

A screenshot is added above.

**Comment by JC5** [comment]
- Sandstorm doesn't log to file so the empty stacktrace from the `/debug` block makes sense.
- Posting the debug table won't help I'm afraid. Like you say, it's almost equal for all Sandstorm instances

As for the 502, there's a good chance it's a memory issue. I am not sure to resolve those. 

You could try to find more information in the underlying log files (from Sandstorm itself).

**Comment by JamborJan** [comment]
Okay, thanks for your hint. I'll check the sandstorm logs if it occurs more often. Today it didn't happen at all ...
