### ISSUE TITLE
mass/automatic change/delete of expense accounts

### ISSUE THREAD

**Issue by krispek** [firefly-iii/firefly-iii#1743]
**Description**
First of all: I'm impressed by this package! :) This will help me a lot in structuring my financial administration. Thanks for that!

Currently I'm importing my whole administration since 2011, generated in AFAS Personal. This causes me some troubles: the way importing is structured, leads to a lot of unused expense accounts. 

Expense accounts are created at the beginning of the import, but after mapping of expense accounts. Especially with larger files (I tried it with +3.000 transactions initially) this leads to chaos. I can't do it upfront, and afterwards I cannot delete them easily. 

**Solution**
The way I tried to fix this, is by creating rules that result into a better future import. That results in a lot of unused expense accounts. Unlike the transactions pages, there's no mass edit/delete functionality in place. Merging or automatically deleting accounts without a transaction would be even better. :)

**Comment by JC5** [comment]
Thanks! I appreciate the compliment!

Such a feature is never needed, until you start importing thousands of transactions. So you'll have to understand it has zero priority. 

However, if you have access to the database it's an easy fix. Run this query to delete all expense accounts that are not being used in transactions:

```
update accounts set deleted_at = now() where id not in (select account_id from transactions) and account_type_id=6 and deleted_at is null
```

**Comment by krispek** [comment]
Thanks! :) I understand the issue, and that I'm somewhat an exception here. AFAS is not the best package to import from either... I'll use the query. :)
