### ISSUE TITLE
Link Type seeding does not detect existing links

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1748]
**Bug description**
I am running Firefly III version 4.7.6.2@develop(before 4.7.7)

Link Type seeding does not detect existing links

**Steps to reproduce**
What do you need to do to trigger this bug?

1. Go to https://demo.firefly-iii.org/admin/links

**Expected behavior**
What do you expect to see after those steps?

Firefly default link types appearing once.
Migration should be put in place to merge existing default types to one canonical type.
(default detectable by "editable=false" 😄 )

**Bonus points**
Earn bonus points by:

- Add a screenshot
![image](https://user-images.githubusercontent.com/550499/46255184-94809180-c4a2-11e8-89e8-783d292503ff.png)

**Comment by hamuz** [comment]
Fixing above report to my local instance - not reproduced in demo... hold.

**Comment by JC5** [comment]
Strange, thanks for notifying me. I see the demo has reset to the default state.

I'll have to do some testing because the code to prevent this is in place. I think it isn't working properly. I'll check it out.

**Comment by hamuz** [comment]
Please notice this was found in my private instance, and not demo.
Might have cause by having trouble seeding an MySQL database with weird (unreported 😞) errors.
Run installing (and seeding) several times before Firefly was installed correctly.

**Comment by JC5** [comment]
Very strange. Which version of MySQL are you running?

My local instance is working properly, it won't recreate the link types.

**Comment by hamuz** [comment]
Server type: MySQL
Server version: 5.7.23 - MySQL Community Server (GPL)

**Comment by JC5** [comment]
I could do that, but the cat's out of the bag now. If I add or remove such constraints previous installations could break. You seem to be running the latest version so that can't be the problem.

I'll try to replicate it. Did you run into any specific problems when this happened?

**Comment by hamuz** [comment]
I've opened #1750. Can't reproduce this issue either. I'll just hard delete from database since no transactions are linked.

**Comment by hamuz** [comment]
I've recreated this issue while upgrading my existing instance:

[2018-09-30 14:50:27] heroku.WARNING: Could not create transaction currency "ILS". It might exist already.
Seeding: TransactionTypeSeeder
[2018-09-30 14:50:27] heroku.WARNING: Could not create transaction type "Withdrawal". It might exist already.
[2018-09-30 14:50:27] heroku.WARNING: Could not create transaction type "Deposit". It might exist already.
[2018-09-30 14:50:27] heroku.WARNING: Could not create transaction type "Transfer". It might exist already.
[2018-09-30 14:50:27] heroku.WARNING: Could not create transaction type "Opening balance". It might exist already.
[2018-09-30 14:50:27] heroku.WARNING: Could not create transaction type "Reconciliation". It might exist already.
Seeding: PermissionSeeder
[2018-09-30 14:50:27] heroku.WARNING: Could not create role "Site Owner". It might exist already.
[2018-09-30 14:50:27] heroku.WARNING: Could not create role "Demo User". It might exist already.
**Seeding: LinkTypeSeeder**
Seeding: ConfigSeeder
[2018-09-30 14:50:28] heroku.WARNING: Database entry exists. Update to latest version (5)

**Comment by JC5** [comment]
There's a unique constraint on the entire set that can't be created on Heroku:

```
heroku.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table link_types add unique link_types_name_outward_inward_unique(name, outward, inward)) {"exception":"[object] (Illuminate\Database\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violatio```

From that, it follows that new link types with the exact same values won't trigger the constraint: it's not there.

Shall we continue in #1750?

**Comment by hamuz** [comment]
Yap.
