### ISSUE TITLE
javascript object in autocompelete suggestions

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1751]
**Bug description**
I am running Firefly III version 4.7.7@DEMO

(please give a clear and concise description of what the bug is)

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Go to https://demo.firefly-iii.org/transactions/show/629
2. Link transaction: type in 669, and wait for auto complete
![image](https://user-images.githubusercontent.com/550499/46259558-97e83d00-c4e3-11e8-9c74-0f3e134bbdd7.png)

**Expected behavior**
What do you expect to see after those steps?
Transaction name, and not some object's "toString"

**Bonus points**
Earn bonus points by:

- Post a stacktrace from your log files
- Add a screenshot

**Comment by JC5** [comment]
Nice find. I've pushed a fix to the develop branch.

**Comment by JC5** [comment]
And another one. I've rewritten some JS so do a hard refresh.
