### ISSUE TITLE
[firefly hacking] rule-actions-text config role?

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1754]
I am running Firefly III version 4.7.7@develop

**Description**

What is the role of rule-actions-text in config?
https://github.com/firefly-iii/firefly-iii/blob/89cc01ce44ca5aa7f184c7394301eb58f02fd32d/config/firefly.php#L377-L386

seems to be missing a lot of actions that I would guess should be here.

Used in two places:
https://github.com/firefly-iii/firefly-iii/blob/89cc01ce44ca5aa7f184c7394301eb58f02fd32d/app/Api/V1/Requests/RuleRequest.php#L79
and
https://github.com/firefly-iii/firefly-iii/blob/89cc01ce44ca5aa7f184c7394301eb58f02fd32d/app/Http/Requests/RuleFormRequest.php#L79

**Comment by JC5** [comment]
A value is mandatory if the action is of that type. It's a bit superfluous because the `ruleActionValue` also checks if the value is correct and will also break on empty or missing values.

**Comment by JC5** [comment]
An updated config file in the new release lists all triggers _and_ actions that require context:

https://github.com/firefly-iii/firefly-iii/blob/develop/config/firefly.php#L378
