### ISSUE TITLE
Feature request: Recurring Credit Memos (like invoices)

### ISSUE THREAD

**Issue by JamborJan** [firefly-iii/firefly-iii#1756]
**Description**
Please describe your feature request:

- I would like Firefly III to be able to handle recurring credit memos like invoices are handled today
- Enabling this feature would enhance forecasts a lot. I could add expenses as a recurring credit and when the actual transaction is imported the actual value is added (exact same behaviour like for invoices)

**Solution**
Describe what your feature would add to Firefly III.

- Personally I think it is enough to allow negative invoices and the job is done

**What are alternatives?**
Please describe what alternatives currently exist.

- A whole new entity "Credit Memos" could be implemented with own processes but I guess this is overkill

**Additional context**

When you add negative invoices this happens today:

![bildschirmfoto 2018-10-01 um 10 44 48](https://user-images.githubusercontent.com/7508960/46278843-ac6e1900-c567-11e8-94b6-ac8ca9f76a10.png)

**Comment by JC5** [comment]
Firefly III is built to manage your expenses. Your budgets should reflect what you want to spend, not what you're going to earn. [That's the idea](https://firefly-iii.readthedocs.io/en/latest/about/grand-theory.html).

**Comment by JamborJan** [comment]
Okay, you could now make the point that you only can know what you can spend, if you know what your income will be. Especially when you don't have a 100% fixed income e.g. as a freelancer. But I don't want to convince you to do something you don't see in your product. As mentioned I guess the thing is solved if negative invoices would be possible.

Thanks for making Firefly, it's a really good and useful piece of software and you are a really responsive and helpful developer!
