### ISSUE TITLE
Import process hangs with no output

### ISSUE THREAD

**Issue by usulpt** [firefly-iii/firefly-iii#1758]
Attempting to import from a CSV file, after going through the wizard steps for the file type, account to create the transactions, column mapping, everything goes fine and then ...nothing. No values entered into the database, no error output, just a continuous "Please wait, import is running".
Using AMPPS (Windows) in my own machine at home.

**Comment by JC5** [comment]
OK. Anything in the log files? On the browser's console?

**Comment by usulpt** [comment]
nothing in the log files, but I hadn't tried the console and now I have. whole lot of errors there, I'll post the file here:

[127.0.0.1-1538499472360.log](https://github.com/firefly-iii/firefly-iii/files/2438870/127.0.0.1-1538499472360.log)

**Comment by JC5** [comment]
It's pretty long but I see no particular errors. It's just looping. The warning about "nothing to show for running" is OK. 

Can you check the import job key from the URL to the entry in the database (table import_jobs)? Any errors or messages there?

Logs can be found in /storage/logs. Nothing there?

**Comment by usulpt** [comment]
nothing much in the logs apart from this occasional line:

#24 {main}
"} 
[2018-10-02 16:58:18] production.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at C:\\Program Files (x86)\\Ampps\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:42)
[stacktrace]

in the import_jobs there's one row for the import:
key: 0ZaFFbKfDSnG
configuration: {"file-type":"csv","date-format":"Ymd","has-headers":false,"delimiter":",","apply-rules":false,"specifics":[],"import-account":1,"column-count":6,"column-roles":["date-transaction","description","amount","_ignore","_ignore","_ignore"],"column-do-mapping":[false,false,false,false,false,false]}

**Comment by usulpt** [comment]
yup, shouldn't there be one?

**Comment by JC5** [comment]
According to the error, you don't have one.

Could you open the file, [turn on debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode), clear out storage/logs and try again?

It should give you a massive debug log with lots of info. That might give us a hint.

**Comment by usulpt** [comment]
Maximum execution time of 30 seconds exceeded. this might be it. changing to 3000 in php.ini, let's see if it works!

**Comment by usulpt** [comment]
yup, it was all down to php and mysql settings. changed maximum execution time, allocated memory and those typical values (it was a big-ass import file) and it worked. many thanks for the help, gonna try the software out and see if it's on par with the good things I heard about it! :)

**Comment by JC5** [comment]
It’s brilliant stuff believe me ;).

**Comment by shobhitsinghal624** [comment]
Facing same issue. I am using the official firefly docker image. Can someone guide me to the changes needed so that I can import a large csv file. Thanks in advance!

**Comment by JC5** [comment]
Which version of FF3 are you running?

**Comment by shobhitsinghal624** [comment]
Version 4.7.7

**Comment by JC5** [comment]
That version doesn’t have a time limit on the import so I could use some logs to debug your issue.
