### ISSUE TITLE
Miscalculation in tag report when using multiple tags

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1760]
**Bug description**
I am running Firefly III version 4.7.7@DEMO
(please give a clear and concise description of what the bug is)
https://demo.firefly-iii.org/reports/tag/1/6,7/20181001/20181031
![image](https://user-images.githubusercontent.com/550499/46366903-eaad2a80-c684-11e8-896b-b8ce5620c774.png)
![image](https://user-images.githubusercontent.com/550499/46366911-f26ccf00-c684-11e8-82a6-55965684696d.png)
https://demo.firefly-iii.org/reports/tag/1/6,7/20181001/20181031

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Tag transaction with 2 tags: test1, test2
2. Tag different transaction with tag: test1
3. Generate "Tag Report" for tags "test1" and "test2".
4. First transaction counted twice influencing graphs, etc.
5. Neither test1 nor test2 calculated correctly.

**Expected behavior**
What do you expect to see after those steps?
First transaction counted once no matter how many tags in report match it

**Comment by JC5** [comment]
Mmm, I thought I had it fixed already. Thanks for letting me know.

**Comment by JC5** [comment]
Pushed a fix.

**Comment by hamuz** [comment]
Why not to do it on DB side? And request unique transactions?

**Comment by JC5** [comment]
The specific problem is that the join I use to match tags returns multiple rows. It's matched on both TagA, TagB, etc. 

The solution is to group everything so unique entries remain, or to use "select distinct" to filter away duplicate rows. Both have some implementation challenges for queries as big as what the transaction collector is generating. Older versions of MySQL and SQLite especially struggle with large queries, and most MSSQL servers can't really do select distinct well.

So my current strategy is to keep the queries simple (if large) and do special filtering in PHP.
