### ISSUE TITLE
Ability to attach tags to split of a transaction

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1761]
**Description**
Please describe your feature request:

- Firefly III doesn't allow to attach tag to split of a transaction, although you can attach it a budget and category.

**Solution**
Describe what your feature would add to Firefly III.

Allow attaching tags to split of a transaction.

**What are alternatives?**
Please describe what alternatives currently exist.

Tag the original transaction. Specify in notes that the tag is only relevant for the split.
Not perfect, tag calculation take in account the original transaction and not only the split.

**Additional context**
![image](https://user-images.githubusercontent.com/550499/46369110-90af6380-c68a-11e8-8994-95ed00d69d58.png)

**Comment by JC5** [comment]
It's on the list :+1:

**Comment by SteffanH** [comment]
@JC5, your last comment was that "it's on the list" , but the bot has since closed the issue.

Does that mean it's no longer "on the list" ?

**Comment by TiiXel** [comment]
@JC5, I will happily work on a pull request for this feature if you are still planning to implement it. I have looked at the code and it seems a bit difficult because it will require database adjustments, but with your help it should work!

**Comment by JC5** [comment]
It's still on my list but it requires some other changes in Firefly III. "Splitting" transactions isn't viable in the long term so i require some _major_ database changes. I'll have to pick that up first.

**Comment by TiiXel** [comment]
Ok it might not be a good thing to start modifying things if you plan to work on the database later. I understand splits are difficult to handle, for what they might mean for different people, and in term of database entries.
