### ISSUE TITLE
Snap Packaging

### ISSUE THREAD

**Issue by j-atoms** [firefly-iii/firefly-iii#1763]
I would like to see a Snap Package created for this project

Here are some resources
[Link](https://snapcraft.io/)

**Comment by JC5** [comment]
:+1:

**Comment by hamuz** [comment]
https://github.com/nextcloud/nextcloud-snap
Seems like a good example to follow

**Comment by JC5** [comment]
If anybody wants to develop something please feel free. I won't be able to do it.
