### ISSUE TITLE
Unable to PUT data back to a piggybank for updates

### ISSUE THREAD

**Issue by mconway** [firefly-iii/firefly-iii#1764]
**Bug description**
I am running Firefly III version 4.7.7

I discovered that there are inconsistent underscores between the PiggyBankRequest and PiggyBankRepository classes. I've fixed this on my local instance and would like to create a pull request for you :) I think that there is some bigger inconsistency between the variable names on this model, but the quick solution was just to fix the variable names in PiggyBankRequest.php

**Steps to reproduce**
Issue a PUT request via the API 
`{
            "name": "name",
            "account_id": 3,
            "target_amount": 1000,
            "start_date": "2018-01-01",
            "target_date": "2019-01-01",
        }`

Server returns 500 error
`"message": "Undefined index: targetdate",
    "exception": "ErrorException",
    "line": 487,
    "file": "\/var\/www\/firefly-iii\/app\/Repositories\/PiggyBank\/PiggyBankRepository.php",
    "trace": [{
        "file": "\/var\/www\/firefly-iii\/app\/Repositories\/PiggyBank\/PiggyBankRepository.php",
        "line": 487,
        "function": "handleError",
        "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
        "type": "->",
        "args": [8, "Undefined index: targetdate", "\/var\/www\/firefly-iii\/app\/Repositories\/PiggyBank\/PiggyBankRepository.php", 487, {
            "piggyBank": {
                "id": 1,
                "created_at": "2018-02-27 08:11:59",
                "updated_at": "2018-08-06 10:07:05",
                "deleted_at": null,
                "account_id": 3,
                "name": "Rainy Day",
                "targetamount": "5000",
                "startdate": "2018-02-27 00:00:00",
                "targetdate": "2019-01-01 00:00:00",
                "order": 1,
                "active": false
            },
            "data": {
                "name": "Rainy Day",
                "account_id": 3,
                "targetamount": "5000",
                "current_amount": "0",
                "start_date": {
                    "date": "2018-02-27 00:00:00.000000",
                    "timezone_type": 3,
                    "timezone": "America\/Los_Angeles"
                },
                "target_date": {
                    "date": "2019-01-01 00:00:00.000000",
                    "timezone_type": 3,
                    "timezone": "America\/Los_Angeles"
                },
                "notes": ""
            }
        }]`
**Expected behavior**
A 200 response with an updated piggy bank record

**Comment by JC5** [comment]
Thanks for reporting this. What is the inconsistency, according to you? I see the difference of course between the model and the API. I prefer to keep the field `target_date`. But I know the model (in the database) uses `targetdate` so there needs to be a "translation point" from `target_date` to `targetdate`.

Let me know what you have in mind. If you create a PR, make sure it's on the develop branch.

**Comment by mconway** [comment]
I've got it on the develop branch, here's where the issue lies:
if you look at the naming convention of the API's Piggy Bank Request class, the translated variables are inconsistent:

>      return [
>             'name'           => $this->string('name'),
>             'account_id'     => $this->integer('account_id'),
>             'targetamount'   => $this->string('target_amount'),
>             'current_amount' => $current,
>             'start_date'     => $this->date('start_date'),
>             'target_date'    => $this->date('target_date'),
>             'notes'          => $this->string('notes'),
>         ];

When I say inconsistency, it's because there are underscores on some variables/members and not others.

The bug stems from the fact that the repository is accessing `$data[targetdate]` which deson't exist from the API, but according to the App Http request class:

>         return [
>             'name'         => $this->string('name'),
>             'startdate'    => $this->date('startdate'),
>             'account_id'   => $this->integer('account_id'),
>             'targetamount' => $this->string('targetamount'),
>             'targetdate'   => $this->date('targetdate'),
>             'notes'        => $this->string('notes'),
>         ];

targetdate does exist.

The easy fix was just to remove the underscore from targetdate and startdate on the API request class. I'm not sure if you have a standard naming convention for variables, which is why I called it an inconsistency - some variables have underscores and others do not.

Hope that explains it :)

**Comment by JC5** [comment]
I see it, thanks. And yes, this is something that still needs work. Personally I prefer the underscores for word separation. Feel free to point out these inconsistencies, especially on the side of the end user (aka the API). These I would like to get fixed because I want the endpoints to be consistent.

I'll verify the PR later.
