### ISSUE TITLE
Automating bunq import

### ISSUE THREAD

**Issue by bluewalk** [firefly-iii/firefly-iii#1768]
I am running Firefly III version 4.7.7

**Description**
I'd like to automate the bunq import every night. I've found the `php artisan firefly:create-import --provider=bunq --token=xxx` command but it requires a configuration, which I can't find.

**Steps to reproduce** 
Run `php artisan firefly:create-import --provider=bunq --token=xxx`

**Extra info**
Ubuntu 16.04.5
Nginx
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Sorry, no bonus points ;-)

**Comment by JC5** [comment]
Hi, thanks for your question. You get 5 bonus points anyway ;-).

Bunq import over API and command line is on the list: https://github.com/firefly-iii/firefly-iii/issues/1461

If you subscribe to that issue, you will be updated automagically on the progress.

**Comment by bluewalk** [comment]
Ah totally missed that! Thanks, just subscribed. Looking forward to it :-)

**Comment by JC5** [comment]
:+1:
