### ISSUE TITLE
Enabling/disabling bills throws error: AttachmentHelper

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1769]
**Bug description**
I am running Firefly III version 4.7.7

While enabling or disabling a bill, I get the following error:

```
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:
Argument 1 passed to FireflyIII\Helpers\Attachments\AttachmentHelper::saveAttachmentsForModel() must be an instance of FireflyIII\Helpers\Attachments\object, instance of FireflyIII\Models\Bill given, called in /home/home/domains/budget.home.gavriliu.com/public_html/firefly-iii/app/Http/Controllers/BillController.php on line 366
```

**Steps to reproduce**
- go to existing bill
- disable
- save
- error is shown but bill was successfully disabled

**Extra info**
could not reproduce on demo site

**Comment by JC5** [comment]
Version 4.7.7 requires PHP7.2 to work. Once you upgrade, the page will work again.

**Comment by gavu** [comment]
*facepalm* - clear case of `RTFM`... it works now.
