### ISSUE TITLE
Click the paid date of a bill to get to the corresponding transaction

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1771]
**Description**
Please describe your feature request:

- Firefly III doesn't allow to click the paid date of a bill to get to the corresponding transaction.

**Solution**
Describe what your feature would add to Firefly III.

Convenience when analyzing bills. 

**What are alternatives?**
Please describe what alternatives currently exist.

Use provided the date and search across all account, to find transaction.

**Additional context**

Places to update in code:
1. Extract ID with date
https://laravel.com/docs/5.7/collections#method-pluck

https://github.com/firefly-iii/firefly-iii/blob/6f707912391cd4bef0a445d2a0a992095a50c1ab/app/Repositories/Bill/BillRepository.php#L384

2. Store extracted IDS

https://github.com/firefly-iii/firefly-iii/blob/6f707912391cd4bef0a445d2a0a992095a50c1ab/app/Transformers/BillTransformer.php#L256-L262

3. Update GUI

https://github.com/firefly-iii/firefly-iii/blob/6f707912391cd4bef0a445d2a0a992095a50c1ab/resources/views/list/bills.twig#L100-L102

https://github.com/firefly-iii/firefly-iii/blob/6f707912391cd4bef0a445d2a0a992095a50c1ab/resources/assets/js/components/bills/Index.vue#L72

**Comment by JC5** [comment]
Looking good :+1:
