### ISSUE TITLE
PLOT: Disable saving accounts to get a better scale/range of the plot

### ISSUE THREAD

**Issue by xXSTrikeXx** [firefly-iii/firefly-iii#1776]
**Description**
- I would like Firefly III to disable non active/saving accounts from the account owerview plot.

**Solution**
I would like to see more details. I have saving acounts with 3456€ and in the plot there is a big line only with this amount. The important informations are with this scale just to small.

**Comment by xXSTrikeXx** [comment]
Yes

**Comment by JC5** [comment]
Check the preferences. You can select accounts for the front page.

**Comment by xXSTrikeXx** [comment]
thx for fast reply ;)
