### ISSUE TITLE
How to fix !balance when the salary comes at the end of month

### ISSUE THREAD

**Issue by xXSTrikeXx** [firefly-iii/firefly-iii#1777]
Hello I got a question. I have in the month more negative amounts then positive because I got my salary from my job last month. For this month I´ll get my salary on 27th. So I will always have a negative balance until the 27th.

How can I prevent that and how can I use the balance window in the overview/front page to check that I´m not in real negative balance?

**Comment by JC5** [comment]
Something like this perhaps?

https://firefly-iii.readthedocs.io/en/latest/about/grand-theory.html

Or simply set a very high virtual balance ;)

**Comment by xXSTrikeXx** [comment]
So you suggest to set the salaray to the next month. So to the month where the money is wanted?

E.G.: 27.09.18 I got the salary. So the grand theory suggests to set the date of the salary to 01.10.18 (because the money is for this month) and then I add the real date to booking date: 27.09.18.

So I have the real booking date and the date (01.10.18) for which month the money will be used for?
When you suggest to use firefly this way I understand it now. But with bank imports it will be easier, when this will be done automaticly 😉

**Comment by JC5** [comment]
No, what you do is you actually move the money _away_ from your bank account into a savings account.

**Comment by JC5** [comment]
I'm not sure if I can explain it more clearly than I already did on that page. Every income you get you must move to a savings account. Just transfer it away.

The day before the month starts, you have to think: how much money do i need in November? 🤔 

Then you put that amount on your checking account. The rest of the income you leave in your savings account.

**Comment by xXSTrikeXx** [comment]
I used before one of the androids app with no internet connection. I tried to used third sync clients to keep it synchronised between devices and people. Then I discovered firefly and started to use this. It´s now very easy to keep it up to date.

At the beginning I started it for myself. Nowadays not only for me, even for tax purposes to scan the bills and link it directly to each transaction. It´s very easy with firefly and thats the reason why I use it. I understand the grand-theory, but I thought I don´t need to move my money to saving accounts and back. This makes for me no sence actually as student ( no money abundance ).

So I thought I just can do it what I meantioned before: Set the date to the next month and the booking date to the real salary to the last month where the salary came from. I asked, because I want all stuff how it is, so I can give it later the tax or financial office for settlements.

I think this train of thought is in line with the grand theory of firefly, isn´t it?

**Comment by ghprod** [comment]
ping @JC5 , sorry for bothering you

**Comment by JC5** [comment]
Sorry no, the cycle will remain by whole month only.

**Comment by ghprod** [comment]
@JC5 Thanks for confirmed
