### ISSUE TITLE
No auto complete for "transaction type" trigger in rules

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1778]
**Bug description**
I am running Firefly III version 4.7.7
(please give a clear and concise description of what the bug is)

**Steps to reproduce**
What do you need to do to trigger this bug?

1. Create new rule
2. Choose trigger "Transaction is of type.."
3. Type "w"

**Expected behavior**
What do you expect to see after those steps?
2 Options:
1. Preferably drop-down (`<select>`) choosing from a close set of transaction types (withdrawal, deposit, transfer)
2. Or, in case of a "free-text" field - an auto complete appear to indicate correct guess

P.S. How does this work in different locales?

**Comment by JC5** [comment]
Confirmed. I see some caching issues on my local instance but a 404 is breaking the auto-complete in some cases. I'll do some debugging and fix it.

This feature requires the same English string for all locales.
