### ISSUE TITLE
Missing expense/revenue accounts in extra options of expense/revenue report

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1779]
**Bug description**
I am running Firefly III version 4.7.7@DEMO
(please give a clear and concise description of what the bug is)

Missing expense/revenue accounts in extra options of reports

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Go to https://demo.firefly-iii.org/reports
2. Choose report type: Expense/revenue account report
3. Click on drop down in "Extra options"
4. Only 2 accounts listed 

**Expected behavior**
What do you expect to see after those steps?
All the expense and revenue accounts available in FireFly to choose from.
( https://demo.firefly-iii.org/accounts/expense 
and
https://demo.firefly-iii.org/accounts/revenue )

**Bonus points**
Earn bonus points by:
- Add a screenshot
![image](https://user-images.githubusercontent.com/550499/46876271-935a4780-ce46-11e8-87e9-94fb10ddf424.png)

**Comment by JC5** [comment]
Heya,

The expense/revenue report is meant for expense and revenue accounts that share the same name. Take for example your local Tax Department. You pay taxes but perhaps you receive money back as well. Or when you work in retail, you might be able to buy stuff at a discount. This report shows you an overview of such accounts.

As such, the selection of accounts that are available in the drop down is limited.

**Comment by hamuz** [comment]
> You pay taxes but perhaps you receive money back as well
What would be the "expected" balance in this case?

> Or when you work in retail, you might be able to buy stuff at a discount.
How is this report helpful in this scenario?

> As such, the selection of accounts that are available in the drop down is limited.
I understand, but the ability to select asset accounts as well (which are not shown?) confused me in this case.

**Comment by JC5** [comment]
What it currently does is basic addition and subtraction.
