### ISSUE TITLE
Rules created with triggers containing no value, are not created

### ISSUE THREAD

**Issue by TheAntimist** [firefly-iii/firefly-iii#1781]
**Bug description**
I am running Firefly III version 4.7.7

**Steps to reproduce**
What do you need to do to trigger this bug?

1. Go to create a Rule form.
2. Set any Title, when transaction is created. etc...
3. For Trigger, set "Has no category" (Could be any trigger with no value though, I have tried it with "Has no budget", "Has (any) budget", etc...)
4. For action use, "Set category to" and for value, give anything
5. Click on Store new Rule 

**Expected behavior**

Should save the rule for further execution.

**Extra info**

| Variable | Content |
| --- | --- |
| FF version | 4.7.7 |
| FF API version | 0.8 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.2.9-1 |
| Display errors | Off |
| Session start | 2018-10-01 00:00:00 |
| Session end | 2018-10-31 23:59:59 |
| Session first | 2018-10-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | sqlite |
| Current driver | sqlite |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, exif, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.2, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.6, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.7.6, laravel/passport@v7.0.2, laravelcollective/html@v5.7.1, lcobucci/jwt@3.2.4, league/commonmark@0.18.0, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.47, league/fractal@0.17.0, league/oauth2-server@7.2.0, monolog/monolog@1.23.0, nesbot/carbon@1.34.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v9.99.99, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.8, swiftmailer/swiftmailer@v6.1.3, symfony/console@v4.1.4, symfony/css-selector@v4.1.4, symfony/debug@v4.1.4, symfony/event-dispatcher@v4.1.4, symfony/finder@v4.1.4, symfony/http-foundation@v4.1.4, symfony/http-kernel@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.4, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.4, symfony/translation@v4.1.4, symfony/var-dumper@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.6,  |

**Stacktrace**:

In the logs, I get a 'Undefined index ...' error.

```
[2018-10-13 09:25:02] local.ERROR: #0 /home/pi/HDD/pi/firefly/app/Support/Http/Controllers/RuleManagement.php(138): Illu
minate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/home/pi/HDD/pi...', 138, Array)
#1 /home/pi/HDD/pi/firefly/app/Http/Controllers/Rule/CreateController.php(88): FireflyIII\Http\Controllers\Rule\CreateCo
ntroller->getPreviousTriggers(Object(Illuminate\Http\Request))
#2 [internal function]: FireflyIII\Http\Controllers\Rule\CreateController->create(Object(Illuminate\Http\Request), Objec
t(FireflyIII\Models\RuleGroup))
#3 /home/pi/HDD/pi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Arra
y, Array)
#4 /home/pi/HDD/pi/firefly/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Rout
ing\Controller->callAction('create', Array)
#5 /home/pi/HDD/pi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\Controller
Dispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Controllers\Rule\CreateController), 'creat
e')
#6 /home/pi/HDD/pi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->run
Controller()
#7 /home/pi/HDD/pi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\Routing\Route->ru
n()
#8 /home/pi/HDD/pi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->
Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/pi/HDD/pi/firefly/app/Http/Controllers/Rule/CreateController.php(61): Illuminate\Routing\Pipeline->Illuminate\R
outing\{closure}(Object(Illuminate\Http\Request))
#10 /home/pi/HDD/pi/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\Http\Controll
ers\Rule\CreateController->FireflyIII\Http\Controllers\Rule\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/pi/HDD/pi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeli
ne->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /home/pi/HDD/pi/firefly/app/Http/Controllers/Controller.php(88): Illuminate\Routing\Pipeline->Illuminate\Routing\{cl
osure}(Object(Illuminate\Http\Request))
```

**Comment by JC5** [comment]
Nice find, I've written it down.

**Comment by JC5** [comment]
A fix has been pushed that will be available in the next release. You can try it already on the [demo site](https://demo.firefly-iii.org/rules).

**Comment by TheAntimist** [comment]
Cool, thanks! Will update, whenever, or maybe I should use the git version.
