### ISSUE TITLE
Shared asset accounts : share access in Firefly III

### ISSUE THREAD

**Issue by SiM** [firefly-iii/firefly-iii#1783]
**Description**
In the [documentation](https://firefly-iii.readthedocs.io/en/latest/concepts/accounts.html), it's written : 
> Shared asset accounts are shared with a partner, roommate or spouse. Use this to indicate that both (all) of you have access to this account. In Firefly III itself, you won’t be able to actually share access between accounts, so this indication is purely for you.

It would be great if we can share access to theses type of account between Firefly III users. When creating / editing a shared asset account, it would be possible to select which Firefly III users have access to it (I imagine a simple role policy : read-only or full access)

That way, for example, everyone in a family could have their own account and share some account with others

**Comment by JC5** [comment]
Heya,

Indeed, it would be. Unfortunately this requires an almost complete rewrite of Firefly III's code.

**Comment by opalinski** [comment]
maybe some configuration option like "standalone installaton"? If it enabled then all users see all data?

**Comment by xXSTrikeXx** [comment]
I use this method with only one account and it´s working well 😉

**Comment by JC5** [comment]
Disabling the feature would be equally complex. I know some users share login account details. It’s not perfect but it’s the only solution.
