### ISSUE TITLE
Import CSV from USAA fails to

### ISSUE THREAD

**Issue by spirituallyinsane** [firefly-iii/firefly-iii#1786]
**Bug description**
I am running Firefly III version 4.7.7

On importing a CSV export from USAA Bank, import fails to error:
`Job could not be started or crashed: The import routine crashed: Uninitialized string offset: `

![selection_169](https://user-images.githubusercontent.com/14048499/46910649-fd8ded80-cf15-11e8-8a88-167a17fb2f2f.png)

**Steps to reproduce**
1. Export transactions in USAA to CSV
2. Select file in "Import a file" in Firefly III
3. Set date format to "m/d/Y"
4. Select default import account
5. Select no bank-specific options
6. Select "Continue"
7. Assign columns to Date, Description, Category Name, and Amount
8. Select "Continue"

**Expected behavior**
Import presents list of transactions successfully imported

**Extra info**
Debug information generated at 2018-10-13 22:29:11 UTC for Firefly III version **4.7.7**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.7 |
| FF API version | 0.8 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stdout |
| PHP version | 7.2.10 |
| Display errors | Off |
| Session start | 2018-10-01 00:00:00 |
| Session end | 2018-10-31 23:59:59 |
| Session first | 2018-09-28 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, mbstring, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.2, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.6, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.7.6, laravel/passport@v7.0.2, laravelcollective/html@v5.7.1, lcobucci/jwt@3.2.4, league/commonmark@0.18.0, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.47, league/fractal@0.17.0, league/oauth2-server@7.2.0, monolog/monolog@1.23.0, nesbot/carbon@1.34.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v9.99.99, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.8, swiftmailer/swiftmailer@v6.1.3, symfony/console@v4.1.4, symfony/css-selector@v4.1.4, symfony/debug@v4.1.4, symfony/event-dispatcher@v4.1.4, symfony/finder@v4.1.4, symfony/http-foundation@v4.1.4, symfony/http-kernel@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.4, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.4, symfony/translation@v4.1.4, symfony/var-dumper@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.6,  |

**Comment by JC5** [comment]
Mmm. Could you share some example lines with me?

**Comment by spirituallyinsane** [comment]
Certainly, I'll send the offending CSV to your email.

**Comment by JC5** [comment]
Thanks, I got it. Strangely enough I was capable of importing your file locally without much trouble. One thing Firefly III can't really handle are lines like these:

```
posted,,x/x/x,,SHOP DESCR       xxx-xxx-xxxx AA,Restaurants/Dining,-20
posted,,x/x/x,,SHOP DESCR       xxx-xxx-xxxx AA,Restaurants/Dining,-20
```

Where both lines are exactly the same. It will refuse to import those because they're exactly the same. In the file you sent me, see lines 183/184 for an example. Otherwise, your entire file imported just fine:

<img width="1167" alt="screen shot 2018-10-14 at 08 08 52" src="https://user-images.githubusercontent.com/5889984/46913204-eb00cc00-cf88-11e8-9602-f69b0b40e4ba.png">

My next step would be to create rules to create the proper expense account. Here's the import configuration I ended up using. Not that different from yours. [import-configuration-2018-10-14.json.txt](https://github.com/firefly-iii/firefly-iii/files/2476131/import-configuration-2018-10-14.json.txt)

I am not sure where Heroku stores its log files, but to find out what went wrong I would like to see where the error came from.

**Comment by spirituallyinsane** [comment]
I'll dig around and see if I can get the log file.

**Comment by spirituallyinsane** [comment]
Sent you the log file.  It appears the issue stems from an extra comma in the transaction description, causing an offset in the CSV columns, and a non-numeric value getting passed for the "amount".

**Comment by JC5** [comment]
I consider this a bug at your bank, and I would contact them about it.

**Comment by spirituallyinsane** [comment]
Upon further investigation, the errant comma was introduced when I opened the CSV in another program which parsed semicolons as delimiters as well, and converted them to commas on saving.  This error does not occur with a virgin transaction file from USAA.  Closing this issue.
