### ISSUE TITLE
Attachments not shown for bill

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1790]
**Bug description**
I am running Firefly III version 4.7.7
(please give a clear and concise description of what the bug is)

**Steps to reproduce**
What do you need to do to trigger this bug?
1. Create bill
2. Attach file to bill
3. Show bill (/bills/show/1, for example)
4. Notice attachments box shows up, but without attachments

**Expected behavior**
What do you expect to see after those steps?
See list of attachments

**Bonus points**
Earn bonus points by:
- Add a screenshot
![image](https://user-images.githubusercontent.com/550499/46931598-8743d500-d054-11e8-8684-f838e2615644.png)

**Comment by JC5** [comment]
:+1:

**Comment by JC5** [comment]
Pushed a fix.
