### ISSUE TITLE
Brazilian Portuguese language missing from preferences in 4.7.7

### ISSUE THREAD

**Issue by nyex** [firefly-iii/firefly-iii#1791]
I have been using Firefly in Portuguese before this last update (and even contributed with some strings), but after opening the Preferences page and saving changes I made in the "Optional fields for transactions" area, the interface turned to English and Portuguese was missing from the languages drop-down menu.

The pt_BR folder is present in the /resources/lang directory, though, along with some other extra languages that don't show up in the drop-down menu as well (there are 11 different languages in the lang directory, but only 8 available in the app preferences).

Maybe it has something to do with #1775 ?

Let me know if I can help in any other way.

Cheers.

**Comment by nyex** [comment]
Ok, will do (it's the one thing I can do after all, as my coding abilities only go so far as html and css ops)! 

Is there any way I can turn it back on in my instance in the meantime?

**Comment by JC5** [comment]
If you uncomment the language here, it will work again :+1:

https://github.com/firefly-iii/firefly-iii/blob/master/config/firefly.php#L248

**Comment by JC5** [comment]
This has been fixed.
