### ISSUE TITLE
Networth report

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1792]
**Description**
Please describe your feature request:
- I would like Firefly III to show me how my calculated net worth changed over time.

**Solution**
Describe what your feature would add to Firefly III.
Firefly already computes this number, just need to present it better.

**What are alternatives?**
Please describe what alternatives currently exist.
Manually add up all accounts that are marked to be included in net worth.

**Additional context**

I was thinking of a separate report because net worth might not be on scale with other transactions.

**Comment by JC5** [comment]
Are you looking for something different from the net worth chart in the default report?

**Comment by hamuz** [comment]
Maybe I'm missing something. What do you refer to as the net worth chart? can you screenshot in the demo?

**Comment by JC5** [comment]
No worries!

**Comment by hamuz** [comment]
I think a warning should be display for the networth chart, when not all accounts that are tagged to be included in networth are present in the report.
The networth chart would only calculate the networth of included accounts, which might not be what the user intented, given you can choose what is calculated in your net worth.

**Comment by JC5** [comment]
Since it's a relatively new feature, yes, such a note would be useful. Something like this? [Same link as before](https://demo.firefly-iii.org/reports/default/34,1,32,33,2,3/20180101/20181231)

**Comment by hamuz** [comment]
Almost. This says what will NOT be included, but doesn't warn you (from maybe the obvious fact) that not included accounts in the report, are missing from the net worth calculation (and chart).

I have several savings accounts I consider as part of my net worth, but are not tipically included in my "default report" which is based of my checking and credit card account.

**Comment by JC5** [comment]
That should be obvious, and has never lead to questions before. If you don't select an account, it will not be in any chart or list.

**Comment by hamuz** [comment]
The new message is important reassurance I feel.
