### ISSUE TITLE
Heroku install Polish language

### ISSUE THREAD

**Issue by objectprogr** [firefly-iii/firefly-iii#1793]
I am running Firefly III version 4.7.7

**Description**
I have a blue warning bar, your server is missing vital locale information. 
According to your wiki, I use command:
locale -a 
C
C.UTF-8
POSIX
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8

If I try command apt-get install -y language-pack-pl-base 
Reading package lists... Done
Building dependency tree
Reading state information... Done
W: Not using locking for read only lock file /var/lib/dpkg/lock
E: Unable to locate package language-pack-pl-base

How I can install PL language?

**Comment by JC5** [comment]
I am not sure. Could you execute `cat /etc/*-release` and see what happens? I don't know which OS Heroku uses.

**Comment by objectprogr** [comment]
This is output:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by JC5** [comment]
I'm sorry, that should do the trick. I see a similar output on Heroku's buildpack:

https://github.com/heroku/heroku-buildpack-locale/blob/master/bin/compile

Otherwise, I'm afraid that Polish is not available in Heroku for version 4.7.7

**Comment by objectprogr** [comment]
Ok, thanks for your answer :)
