### ISSUE TITLE
Make links to external pages open in new window

### ISSUE THREAD

**Issue by spirituallyinsane** [firefly-iii/firefly-iii#1794]
**Description**
I would like Firefly to open hyperlinks in a new window, so that when I click an information link in Firefly to an external resource in the documentation or elsewhere, it doesn't force me to leave the page I'm on in Firefly.  I think this makes more sense as a default behavior, because that information is usually for reference while using Firefly.

**Solution**
Allows user to remain logged into Firefly in the same location while referencing documentation or external sites.

**What are alternatives?**
Ctrl- or Shift- clicking to open hyperlinks in a new tab or window allows the user to open hyperlinks while keeping Firefly open.  This requires the user to remember to do this.

**Comment by JC5** [comment]
Sorry, you'll have to remember to use the Shift or Command or Ctrl button.

**Comment by spirituallyinsane** [comment]
Normally I'd not mention it, except it can cause an in-process page with unsaved data, like a transaction, to be lost when the page itself often reads "read this documentation for more details".  If the user follows the page's instructions, the user loses data.
