### ISSUE TITLE
Forecast balance chart

### ISSUE THREAD

**Issue by spirituallyinsane** [firefly-iii/firefly-iii#1795]
**Description**
I would love a forecast feature that shows forecast account balance chart based on bills, paychecks, and recurring transactions.  I use this for quick account health checks to make sure I've put all my bills in, and to know I'm not going to overdraw any accounts.  Some programs also include a "lowest balance before next paycheck" feature as well.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1135
