### ISSUE TITLE
Regular salary entry feature like bills

### ISSUE THREAD

**Issue by spirituallyinsane** [firefly-iii/firefly-iii#1796]
**Description**
I would like Firefly to have a recurring revenue option, like bills, but positive cashflow.  This could enable future balance forecasting, and provides for an easy matching rule for salary payments.

**Solution**
Provide a setup similar to the "Bills" dialog that allows a user to set up a recurring salary entry.  

**What are alternatives?**
Recurring transactions can sort of do this, but an automatically entered transaction runs counter to the manual entry and engagement encouraged by Firefly.

**Comment by JC5** [comment]
It's been asked before but it's probably not going to happen. Budgeting should be done based on expenses and not on income. If forecasting happens, it will probably be based on past results, not on user input. For the latter, I recommend Excel.
