### ISSUE TITLE
After deleting an account with an associated piggy bank, it is not possible to create a new piggy bank with the same name

### ISSUE THREAD

**Issue by altazure** [firefly-iii/firefly-iii#1798]
**Bug description**
I am running Firefly III version 4.7.7

After you delete an account with an associated piggy bank, you are unable to create a new piggy bank with the same name as the deleted one.

**Steps to reproduce**
Delete an account with an associated piggy bank. Try to create a new piggy bank with the same name. The program will not allow this, stating that "The name of the piggy bank must be unique" - even though there is no piggy bank with that name anymore.

**Expected behavior**
A new piggy bank with the same name as the deleted one should be created.

**Comment by JC5** [comment]
Nice find. I've pushed a fix. See the commit above my reply. It will be included in the next release.
