### ISSUE TITLE
Save import config in database

### ISSUE THREAD

**Issue by opalinski** [firefly-iii/firefly-iii#1802]
I want to import datafrom various banks from CSV files from time to time.
I think that possiblity to save  my import config in database (for each bank) will be much better than searching for import config file that i created many days ago...

**Comment by JC5** [comment]
Sorry, I never replied. I'll see what I can do but no promises.

**Comment by joshwapohlmann** [comment]
Hey, I'd really like that idea. I have the same problem as I'd like this to be automated in the long run ... so I can receive notifications if a bill has been automatically paid or a transaction above a certain threshold has been deteced. For this ... it is crucial to save the import configuration!

Here an example of how this could look like (?). Sorry, it's in german. But it should convey the idea.

![firefly_userstory_import_fints_1](https://user-images.githubusercontent.com/36891156/50823782-0afc1d80-1335-11e9-96d8-5f682d2aea7b.png)
*1. Simply create a new import with all arguments required*

![firefly_userstory_import_fints_2](https://user-images.githubusercontent.com/36891156/50823808-1fd8b100-1335-11e9-9ae3-b3394eed6b4c.png)
*2. Progress to the last page of the import dialog, track/save all arguments/input data. Click "Safe Import Configuration" instead submit button.*

![firefly_userstory_import_fints_0](https://user-images.githubusercontent.com/36891156/50823872-4f87b900-1335-11e9-8c34-86f4d69c0174.png)
*3. the import configuration is now listed with some details like "associated with <bank account>" or "last import" for convenience.*

**Comment by JC5** [comment]
No problem, I know the view by heart. I appreciate your input, thanks for this.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
