### ISSUE TITLE
Feature Request: Split Liability Account Payments

### ISSUE THREAD

**Issue by spirituallyinsane** [firefly-iii/firefly-iii#1803]
**Description**
Please describe your feature request:

I would like to see a way to split liability account payments in a way that reduces the principal balance on the liability correctly, by applying the principal portion as a _Transfer_ to the loan account principal, and the interest as an expense to the bank or loan's _Expense_ account.

Currently, when I enter a single transfer transaction from my bank account to a liability account, the entire transfer applies to the balance.  I can do a category split, showing the portions of the payment that went to principal and interest, but both reduce the balance of the liability

**Solution**
Normally, when a fixed payment is made to a liability account, the single payment amount recorded on the source account is composed of a principal and an interest portion of the payment.  The principal portion reduces the amount of the loan, while the interest portion does not, and should be treated as an expense.

Allowing loan payments to be split into principal (transfer) and interest (expense/withdrawal) portions would enable the correct reporting of liability account balances, with the details correctly recorded in a single split transaction.  This is how most double-entry bookkeeping applications seem to handle this type of transaction.

**What are alternatives?**
Current workaround is to make payments to a "distribution account", set up as a default asset account, then create two new transactions from that account, one transfer (principal) and one withdrawal (interest).  As long as the transactions balance, this keeps the net worth calculations correct (the distribution account should always have a zero balance)

I could also discard the liability account entirely and use a credit card account to track the liability account, but this is a bit kludgy, as it miscategorizes a liability as a revolving-type credit account, and interest payments will have to be recorded as separate transaction.  It will work, though, keeping the net worth and categories correct.

**Additional context**
I recognize that, depending on how transactions are recorded in the database, this may prove difficult to do, but I haven't dug in too deeply to see if it might be a straightforward modification to the process.

**Comment by JC5** [comment]
Technically speaking this is fairly simple. The database supports any type of split in any direction. 

What I am still trying to figure out is a way to present this so new users will understand it as well. I don't want to turn Firefly III into another GnuCash.

For example, I would like the "transfer" part and the "expense" part of your suggestion to carry a budget as well. However, in the current way of working, transfers cannot have a budget. 

Should I break that rule? If so, how do I explain the difference?
Or perhaps add a new transaction type? If so, how do I make users see the difference?

I haven't had the perfect idea yet. Until then, you'll have to think of a workaround.

**Comment by spaetz** [comment]
I work around this by transfering both parts (principal (transfer) and interest (expense/withdrawal)) to the libailities (mortgage) account and then immediately forward the interest part to the mortgage bank account (an expense account). It kind of works bit is a tad kludgy as I need to remember to perform the exact same procedure each month.

**Comment by JC5** [comment]
Like I mentioned in #1956, I plan to change this. It would also mean that a split would be possible.

**Comment by spaetz** [comment]
> In the meantime would either of you be willing to explain the workflow that you have to make this work.

To be honest, my workaround turned out not to work. So I am stuck without a solution for this as well and stopped using Firefly until this gets solved. I do see that Firefly is targeted towards nonexpert users, but having a mortgage pay with a principal and interest component seems like a common enough requirement to justify this. @JC5 said he would be solving this at some point in time, so I am waiting until then. (and went back to by text based ledger in the meanwhile :-)).

**Comment by apowell656** [comment]
I understand. What I like about ff is that I can share the geekery/numbers
in an easier fashion with my wife.

I guess making the liability accounts expense accounts is a small trade off
for better communication in my case.

**Comment by JC5** [comment]
Will be fixed.

https://github.com/firefly-iii/firefly-iii/projects/5#card-19937456
