### ISSUE TITLE
Field "Native amount" not displayed when editing the Source Account that uses a different currency

### ISSUE THREAD

**Issue by weimdall** [firefly-iii/firefly-iii#1805]
**Bug description**
I am running Firefly III version 4.7.7

Editing the "Source account" of a transaction by choosing one with a different currency do not show the "Native amount" field.
Beside, even if the field pop out when I edit the currency, the "Native amount" is not saved afterwards.

**Steps to reproduce**
Create a withdrawal of 25 C$ sourcing an Canadian Dollar account,
Edit the expense and set the "Source Account" to another account which use a different currency (€ for instance).

* Bug 1 : The field "Native amount" do not appear.
![2018-10-20-022517_1920x1080_scrot](https://user-images.githubusercontent.com/7267440/47249078-c0db5e00-d40f-11e8-8d3a-52fd9ff66f75.png)

* Bug 2 : At this step, changing the currency of the transaction to € and back to C$ will shown the Native amount field, however, the value set in this field will not be saved when clicking on "Update withdrawal".

**Expected behavior**
* The field "Native amount" should appear when i choose an account with a different currency
* The "Native amount" should be saved when I click on "Update withdrawal".

```
Thanks a lot.
I really love this software that I found a few days ago, 
it's exactly what I was looking for with the techno I wanted. 
Awesome.
```

**Comment by JC5** [comment]
Thanks for the compliments! :grin:

I have pushed some fixes that you can already try on [the demo site](https://demo.firefly-iii.org/). Make sure you press "Ctrl F5" or "Command R" when editing a transaction, so your cache is empty.

The fixes (if they work) will be included in the next release :+1:

**Comment by weimdall** [comment]
I've tested in different ways (editing transaction by API and Web UI) , 
everything seems to be working now.  :ok_hand:
Thanks
