### ISSUE TITLE
Cateogrize repetated transaction upon import in the database to suggest Expenses/Income Group

### ISSUE THREAD

**Issue by greenspray** [firefly-iii/firefly-iii#1806]
**Description**
I noticed that I had to create a lot hand written rules for similar transactions that could be categorized into the same Category of expenses or income. 

**Solution**
A decision tree based Rule creation system that can form relationship about the imported data based on past laws and suggest proper Category. The solution could be divided into two types:

1. Database that containers identifiers for common supermarket, bars etc in various countries which can be used to create a plugin that would provide a Category suggestion.
2. Each transaction is randomly visualized and the user groups them visually to form some kind of cluster. This cluster has aggregated information about the transaction which will be used later on to provide Category suggestion.

**What are alternatives?**
For the moment, hand written rules for types of transactions.

**Comment by JC5** [comment]
This sounds like a project all by itself!
