### ISSUE TITLE
Feature request: Budgets for Deposits

### ISSUE THREAD

**Issue by carstenboehm** [firefly-iii/firefly-iii#1808]
Hi,
I want to ask if it's possible to have budgets for despoits as well in a future release.

I want to use this for two things:
- Refunds for payments that have a budget assigned can go directly back into that budget (my current workaround is reducing the original payment by the amount refunded).
- For business travel my budget is zero (as I get reimbursed for the expenses by my company). I want to assign the "travel expenses" budget to the payment from my company so that the budget eventually is balanced.

Please correct me if there's a better way to handle this in Firefly III.

Regards,
Carsten

**Comment by JC5** [comment]
No, sorry. Budgets are for expenses.

To balance things you might consider using tags.
