### ISSUE TITLE
Configure access from outside 

### ISSUE THREAD

**Issue by objectprogr** [firefly-iii/firefly-iii#1809]
I try configure nginx for public ip and my domain, but I can't.
My server is nginx
Firefly III version 4.7.7
What I must edit and how for access from outside?

**Comment by JC5** [comment]
That's really outside of the scope of Firefly III, I'm sorry.

**Comment by objectprogr** [comment]
Maybe someone else has managed to do it?

**Comment by JC5** [comment]
I hope so! But realise that this is probably a setting on your modem and/or your router as well, and there are as many combinations for those, as there are houses in your favorite country.
