### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#1814]
I am running Firefly III version x.x.x

**Description**
when running the command docker-compose -f /Users/myname/Documents/docker-compose.yml up -d

I get this error

ERROR: The Compose file '/Users/myname/Documents/docker-compose.yml' is invalid because:
Invalid top-level property "firefly_iii_upload". Valid top-level sections for this Compose file are: version, services, networks, volumes, secrets, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

I'm running Docker under Mac OS High Sierra Desktop

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
OK, since you downloaded the file from github, try again but this time try "save as" from the file you see here: https://raw.githubusercontent.com/firefly-iii/firefly-iii/master/docker-compose.yml

Then try again.

**Comment by bartmaniac** [comment]
thanks, I was able to proceed with installation. Now looking for solution on how to open the webpage.
