### ISSUE TITLE
Little missing translation

### ISSUE THREAD

**Issue by BoGnY** [firefly-iii/firefly-iii#1815]
**Bug description**
I am running Firefly III version 4.7.7

Just set any languages different from english, and as visible in screenshot, in red circle the translation in missing.. I've searched in Crowdin the text "initial balance" but there are 0 corrispondent string...

![firefly](https://user-images.githubusercontent.com/11542801/47445486-46b52b80-d7b9-11e8-9c20-63980feb57d0.jpg)

So I think the translation isn't set on php code page 👍

**Comment by JC5** [comment]
Nice find, I'll get it fixed :+1:

**Comment by BoGnY** [comment]
Hi, I've just updated to version 4.7.8 but string is not translated.. Any idea why??

**Comment by JC5** [comment]
The translation is only used when the account is created. So your account, having been created already, will not be translated. The name is already fixed in the database and cannot be changed.

Future accounts will be translated correctly.

**Comment by BoGnY** [comment]
@JC5 I've found a solution..

I've removed initial balance from bank account, saving changes, and readded initial balance... The transaction now has correct translation 👍

**Comment by JC5** [comment]
:+1:
