### ISSUE TITLE
Incorrect view of bill

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1817]
**Bug description**
I am running Firefly III version demo
https://demo.firefly-iii.org/rules/edit/2
The minimum and maximum amounts are swapped (only in the view, in edit mode they are okay).

**Steps to reproduce**
https://demo.firefly-iii.org/rules/edit/2

![image](https://user-images.githubusercontent.com/441924/47525746-4c387180-d89e-11e8-9e82-5acabcb15606.png)

**Comment by JC5** [comment]
Nice find, I'll fix it.

**Comment by JC5** [comment]
Looking closely, this seems to be correct, right?

**Comment by zjean** [comment]
Yes you are. Sorry :'(
