### ISSUE TITLE
Incorrect symbol on bills page

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1818]
**Bug description**
Demo

https://demo.firefly-iii.org/bills page shows an incorrect symbol for the totals.

**Steps to reproduce**
https://demo.firefly-iii.org/bills

**Expected behavior**
Euro signs

![image](https://user-images.githubusercontent.com/441924/47526032-e3052e00-d89e-11e8-8edb-3f47dee31f41.png)

**Comment by JC5** [comment]
That's actually the generic currency icon. Since bills can have multiple currencies. But that view can use some work.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19974118
