### ISSUE TITLE
Pre-filled budget amounts

### ISSUE THREAD

**Issue by technoicon** [firefly-iii/firefly-iii#1819]
**Description**
Please describe your feature request:

I would like it if I didn't have to enter my budget amounts each Month/period.  When creating a "budget" it is common practise for this budget to be the same each period, and is often used as follows.
Calculate cost of xyz over a year, divide this by your period and get your budget amount.  This is how you can keep to your budget, hence it shouldn't vary that much.

**Solution**
When creating a budget have a default amount (http://firefly/budgets/create), then this could be zero and have the same functionality as your current system.
If changing periods you could either calculate this based on the original entry or ask users to update it by editing.

I think if you made it so that each day after today updates the default amount to be the current default amount and each day before today saves it in the budget db that would work best.

Changing the default amount would then update all future periods.

**What are alternatives?**
Manually entering the same data for every budget item for every period for the rest of my life.  I don't know how you do it.

**Additional context**
I understand your system is based on a manual entry system but i feel this could add some functionality and keep your original way of doing it.  There has been a few people ask the question but I don't think they provided a solution quite like this.

**Comment by JC5** [comment]
It used to exist but it's a nightmare to build and maintain. I'll think about it.

**Comment by ghprod** [comment]
:+1:

**Comment by empeig** [comment]
I would really appreciate this functionality.
It should be possible to implement it without changing the current functionality. For example : new "Default value" field in "Edit budget" page and a new button "Adopt default value" in "Budgets" page (at line level).
For the user, it would not be as easy as technoicon's solution but it should be easier from a technical point of view.

**Comment by Alpoy** [comment]
This! +1
 I'm testing this software out now for the first time, this was the first "problem" I noticed. So far everything else seems great :-)

**Comment by JC5** [comment]
Budgets will not auto complete or auto fill, FYI.
