### ISSUE TITLE
Attachement (PDF) not showing up

### ISSUE THREAD

**Issue by rxbn** [firefly-iii/firefly-iii#1821]
**Bug description**
I am running Firefly III version 4.7.7

When I upload a PDF to a transaction I'm not able to look at it in the Browser.

**Steps to reproduce**
Upload an attachement, click on the attachement

**Expected behavior**
I'd like to see a preview of the PDF document within my browser.

**Bonus points**
Screenshot: https://imgur.com/a/idmy8DL

**Comment by JC5** [comment]
I need more info. How are you running Firefly III? Docker, self-installed?

**Comment by rxbn** [comment]
Sorry, forgot about that... Running in Docker.

**Comment by JC5** [comment]
I've had this myself before. Not sure what the solution was. Did you try simply restarting the container?

**Comment by rxbn** [comment]
Yes, I tried that several times.

**Comment by JC5** [comment]
What else have you tried already?

**Comment by rxbn** [comment]
Not much more. I tried different browsers, different attachments but it's always the same error. How did you solve that issue?

**Comment by JC5** [comment]
Not sure anymore. I checked the file rights by accessing the container directly but it didn't seem to matter.

There are changes coming up to the file storage engine this weekend and that might resolve the issue.

**Comment by rxbn** [comment]
Okay perfect. I'll give you a report if it works after the update. Keep up the great work! I love firefly :-)

**Comment by rxbn** [comment]
Hey JC5, thanks for the Firefly Update. Attachement viewing is now working correctly!

**Comment by JC5** [comment]
:+1:
