### ISSUE TITLE
'Create now' operation for recurring transactions

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1822]
**Description**
It would be great if firefly offered the possibility to manually create the next occurrence of a recurring transaction on demand. 

I have several recurring expenses which are debited very randomly with up to 5 days off the expected date. If this money is debited from my real bank account 5 days early, firefly is off sync if I do not manually create the transaction.

In such cases it would be great if I could demand firefly to create the recurring transaction right now and thus to skip the next recurrence (because transaction already exists).

I'm not even sure what currently happens if I create the transaction manually? Will firefly recognize the manually created transaction when creating the recurring transaction a few days later or will it create a duplicate?

**Comment by JC5** [comment]
I'll think about it. It shouldn't be hard to do but it requires some database changes. I'm thinking of a magical button that will create the the transaction, _and_ tell Firefly III to skip the next occurrence.

Firefly III won't be able to tell if the transaction has been created. So if you create it now, Firefly III will also create it. Note that they would not be connected either.

**Comment by skuzzle** [comment]
Hey JC,
do you still have plans to build this?

**Comment by JC5** [comment]
Yes I do. Currently focusing on other Firefly III things though. I'll keep you posted.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19974187
