### ISSUE TITLE
Bug when reconciling account with multi-currency transfers

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1825]
**Bug description**
I am running Firefly III version 4.7.5.3 (yea, I need to catch up a little), but I was able to reporduce it on demo site running 4.7.7.

Popup "Overview of reconciliation" has different values than panel "Reconciliation options".

**Steps to reproduce**
1. Create transfer of 100 EUR from Checking Account as 50 USD on Foreign Checking Account (USD).
2. Go to account reconciliation and check all transactions.
3. Panel "Reconciliation options" in top-right should show $0.00 (btw, in red - shouldn't it be blue?).
4. Click button "Store reconciliation".
5. Popup "Overview of reconciliation" says that there is difference of $50.

**Expected behavior**
What do you expect to see after those steps?

**Extra info**
In popup "Overview of reconciliation":
- Submitted start balance (October  1, 2018) | $0.00
- Selected transactions (1) | $50.00
- Already cleared transactions (0) | $0.00
- Submitted end balance (October 31, 2018) | $50.00
- Difference | $0.00

**Screenshots**
Reconciliation page:
![obraz](https://user-images.githubusercontent.com/3846677/47582207-0b9b2f80-d954-11e8-8b9f-f26abe0e8d88.png)

Reconciliation popup:
![obraz](https://user-images.githubusercontent.com/3846677/47582264-2c638500-d954-11e8-91f4-3a3b23b3008a.png)

**Comment by JC5** [comment]
Had to do some magic but I believe I have fixed it. It's live on the demo site.

**Comment by pkoziol** [comment]
Reconciling Foreign Checking Account (USD) looks correct, but reconciling Checking Account broke.

Reconciliation for range with multi-currency transfer:
![obraz](https://user-images.githubusercontent.com/3846677/47602543-ccff8680-d9e0-11e8-9093-191ca356b6e7.png)

Sums amount only of that transfer while ingoring other transaction:
![obraz](https://user-images.githubusercontent.com/3846677/47602544-d557c180-d9e0-11e8-9d6d-93b73a33cb43.png)

Reconciliation for range without multi-currency transfer:
![obraz](https://user-images.githubusercontent.com/3846677/47602556-ea345500-d9e0-11e8-9b6a-c9684f3fa664.png)

Displays €0 for selected transactions:
![obraz](https://user-images.githubusercontent.com/3846677/47602561-f3252680-d9e0-11e8-8a59-6cdfe9ff341e.png)

**Comment by JC5** [comment]
Thanks for the heads up. I'll try it again later tonight :)

**Comment by JC5** [comment]
I've pushed a fix. It's live on the demo site. I am pretty sure this fixes the problem. Let me know if you can confirm this.

**Comment by pkoziol** [comment]
It looks like off-by-one error. I created two new accounts - one for EUR and one for USD.

I created 3 transactions:
![obraz](https://user-images.githubusercontent.com/3846677/47617330-6eacd380-dac6-11e8-8411-d652fab3cb6b.png)

Reconciliation of account "Brand new account EUR" for period:
- 1.10 - 31.10 - OK
- 23.10 - 31.10 - OK
- 24.10 - 31.10 - FAIL - Difference €400.00
- 25.10 - 31.10 - FAIL - Difference €400.00
- 26.10 - 31.10 - FAIL - Difference €400.00
- 27.10 - 31.10 - FAIL - Difference €400.00
- 28.10 - 31.10 - FAIL - Difference €400.00
- 22.10 - 28.10 - OK
- 22.10 - 27.10 - OK
- 22.10 - 26.10 - OK
- 22.10 - 25.10 - OK
- 22.10 - 24.10 - OK
- 22.10 - 23.10 - OK

**Comment by JC5** [comment]
No worries, thanks for debugging. I've pushed another fix. Your scenario now works for me™
