### ISSUE TITLE
Option to not use budget/tags when importing via Spectre

### ISSUE THREAD

**Issue by krispek** [firefly-iii/firefly-iii#1827]
**Description**
Currently tags and categories are applied when I import transactions via Spectre. This is a bit irritating, since Spectre is hardly capable of categorising my transactions in a correct manner, and does this in a different way than I would do. Same applies to tags. 

**Solution**
An option not to use the provided categories by Spectre, and thus rely on the rules. 

**What are alternatives?**
Even better: for each transaction, first apply all the rules and then create categories/tags/accounts when necessary. With each import I need to do some cleaning up. Mapping partly solves the issue, because it requires manual labor or a 'database' with all possible mappings. Doing this via rules (or an equivalent) will be much more sustainable in my opinion. 

**Additional context**
I try to automate almost all imports, so that I barely have to do anything by hand. This is a major dealbreaker, and almost leads to create transactions manually because it's just faster. :)

**Comment by JC5** [comment]
As an alternative, I can build the trigger "created through" with the options Spectre, Bunq, CSV, YNAB, FinTS and of course Firefly III. 

That allows you to create rules that only respond to transactions imported through Spectre. As you may know, the actions to remove or change budgets, categories and tags are already present.

**Comment by krispek** [comment]
Will this also lead to the category/tag/account not being created? In that case, it would indeed save time.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
