### ISSUE TITLE
Automatically focus input fields on certain forms

### ISSUE THREAD

**Issue by Kovah** [firefly-iii/firefly-iii#1828]
**Description**
This is a small UX improvement. The first or the most important input field should be automatically focused when loading a certain form. This would be incredibly helpful when enabling the "After storing, return here to create another one." option in a form. At the moment I have to click into the input field manually or use tab to navigate to the input field.

Examples where this could be added:
- Adding new categories
- Adding new tags

**Solution**
Add an `autofocus` HTML tag to the input fields.

**Comment by Kovah** [comment]
@JC5 I would implement this if you are ok with that.
(Great app btw!)

**Comment by JC5** [comment]
Sure thing, just make sure you create the PR on the `develop` branch. :+1:

**Comment by JC5** [comment]
Most forms will now have this in the next release.
