### ISSUE TITLE
Creating a backup script

### ISSUE THREAD

**Issue by NanneHuiges** [firefly-iii/firefly-iii#1829]
For my own install I created a backupscript to get the information out of the volumes and get them in to a (for me) easier te manage format. Basically I added a mounted dir to the composer file, and created a script that runs a backup copy of files and a dump of the database. Nothing special.

Would this be interesting to make an MR for e.g. the documentation? I'm not sure it's the intended usage or that everyone would think this is the best way, as you could obviously backup the volumes from the docker eco-system, and it does involve editing the docker-compose file.

It needs a bit of a polish which I will do if you'd think its interesting to put somewhere?

```
#!/bin/bash
#
# Backup script for firefly installations that were installed using the method
# 'Docker Hub with automatic updates via docker compose'
#
# Makes a main backup directory inside the current dir,
# and a subdirectory for each day (Ymd).
# within that subdirectory each run will create a db-file and
# 2 directories (export/upload), named with date/time (YmdHMS)
#
# author: Nanne Huiges (nanne@huiges.nl)

# verbose: shows commands for debugging
# set -x

#############################################
############### settings ####################
#############################################
# db-container name (from docker-compose file)
DB_CONTAINER="firefly_iii_db"
APP_CONTAINER="firefly_iii_app"

# db name (from docker-compose file)
DB_USER="firefly"

# backup locations
BACKUP_SUBDIR="$(date +%Y%m%d)"
DB_BACKUP_FILE="firefly_db_$(date +%Y%m%d%H%M%S)"
UPLOADS_SUBDIR="upload_$(date +%Y%m%d%H%M%S)"
EXPORTS_SUBDIR="export_$(date +%Y%m%d%H%M%S)"

#############################################
############### actual script ###############
#############################################

mkdir -p ./backup/${BACKUP_SUBDIR}
mkdir -p ./backup/${BACKUP_SUBDIR}/${EXPORTS_SUBDIR}
mkdir -p ./backup/${BACKUP_SUBDIR}/${UPLOADS_SUBDIR}

docker-compose exec -T ${DB_CONTAINER} bash -c  'pg_dump -U '${DB_USER}' | gzip >/backup/'${BACKUP_SUBDIR}'/'${DB_BACKUP_FILE}.sql.gz''

docker-compose exec -T ${APP_CONTAINER} bash -c  'cp /var/www/firefly-iii/storage/export/* /backup/'${BACKUP_SUBDIR}'/'${EXPORTS_SUBDIR}'/'

docker-compose exec -T ${APP_CONTAINER} bash -c  'cp /var/www/firefly-iii/storage/upload/* /backup/'${BACKUP_SUBDIR}'/'${UPLOADS_SUBDIR}'/'
```

As said, it's nothing fancy but it helps to create backups if you want them in a simple format for emergies.

**Comment by JC5** [comment]
This is absolutely useful, although the repository would not be the best place.

If you create a [Gist](https://gist.github.com/), I can link to it from the documentation. If people run into problems they can comment and leave suggestions. Would that be a good idea?

**Comment by NanneHuiges** [comment]
Yeah, sure! Biggest trick / issue that I think might be giving people some doubt is that because I like them to be actual files and i'm using `docker-compose exec` (so against the currently running container), I need the mount to be in the docker-compose file. Therefore I added a 
```
      - "./backup:/backup"
```
to the volumes of both services, that's not a volume but a mount, so I have somewhere to write :)

that's a bit tricky to add.. maybe just put it in the comments? It isn't a drop-in script then sadly...
