### ISSUE TITLE
Revenue Accounts have been "Globalized" in Auto Complete

### ISSUE THREAD

**Issue by dougbrose** [firefly-iii/firefly-iii#1830]
I am running Firefly III version 4.7.7

I noticed a bug when I'm updating and adding transactions.  I have two accounts in Firefly.  One for my wife (our joint account) and one for me.  In the past, when I was logged in as me I couldn't see her/our revenue accounts in the auto complete, but now I can.  So now I can see "Academic Grants" in my auto complete (which is a revenue account that is in our joint account but not mine).

Thank you,

**Comment by JC5** [comment]
Yes, they are probably shared through your browser cache. I will check if I can make sure they won't collide when you're using multiple users in the same browser.

**Comment by JC5** [comment]
Pushed a fix. This changes the cache key to a unique one so it won't happen anymore.
