### ISSUE TITLE
Improvements for budgets

### ISSUE THREAD

**Issue by Kovah** [firefly-iii/firefly-iii#1831]
**Description**
I have some improvement ideas for budgets which may be pretty handy. At the moment it seems quite cumbersome to plan the budgets for several months or even fill it with values you used last month. Some budgets are not likely to change pretty often, like for simple groceries, insurances or rent. They are more likely to be the same over a couple of months.

**Solution**
* Allow to show budgeted amounts for several months instead of only one, I know a three-months display from YNAB 4.
* Allow some options for each budget field, like a dropdown menu:
  - "Amount budgeted last month" (copies budget amount from last month)
  - "Amount from outflows last month" (sets budget amount to what you spent in total last month)
  - "Balance to zero" (sets budget amount to what you spent this month)
* Vertical align amounts from the "Spent" and "Left" columns in the middle to visually align them with the budget amount

**Alternative**
Show an additional column "Budgeted last month" which simply shows the budget amount from the previous month so you can copy & paste the amounts. Not the best solution but would prevent having to move back and fourth in the months.

**Comment by Kovah** [comment]
@JC5 What do you think about this? If you are okay with that I would try to implement this.

**Comment by Kovah** [comment]
So, I looked into this and I would rather leave my hands off of this. The budget screen is currently built to work with periods of time so it would be way too hacky at the moment to implement something like a 3-months overview.
Waiting for your ideas for the budget screen for now but I'm happy to help if needed. 😊

**Comment by geniusupgrader** [comment]
Start simple and step by step.

Because of your idea with a 3-months overview (which is nice to have), you even didn't start implement something. And remember your initial issue/comment was: 

> At the moment it seems quite cumbersome to plan the budgets for several months or even fill it with values you used last month

My opinion is, that you must target this first and your solution with a dropdown menu sounds fine to me.
Maybe even simplify this one and solely add a button, which says: „get previous“, which copies the budget amount from the last month to the current month.

**Comment by geniusupgrader** [comment]
Also, I want to reference this: #1819

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937790
