### ISSUE TITLE
double records

### ISSUE THREAD

**Issue by filoor** [firefly-iii/firefly-iii#1833]
I am running Firefly III version 4.7.7

Hi i'm trying to import my Rabobank data for a couple days 
I have first created my Rabobank account manualy under assit (See Screenshot 1).
after that i have imported this year as csv
i have only mapped iban and Opposing account iban account NOT name
I have linked the iban with my assist account in Asset account (IBAN) and also in Opposing account (IBAN).

But My balance is not correct and i have also double records see screenshot 2

1
![image](https://user-images.githubusercontent.com/3647638/47681476-d8fa6c80-dbc9-11e8-94f4-acf5be75dfad.png)

2
![image](https://user-images.githubusercontent.com/3647638/47681205-2a562c00-dbc9-11e8-88d7-b6760a1bee81.png)

**Comment by JC5** [comment]
I'll have to try this myself to see what's going on. Stay tuned.

**Comment by filoor** [comment]
Thank you @JC5

**Comment by filoor** [comment]
@JC5
Hi This is a example of it see attachment

with this query 

`

select * from finanace.transaction_journals
inner join  finanace.transactions on finanace.transactions.transaction_journal_id = finanace.transaction_journals.id
where finanace.transaction_journals.id in  ('10073', '9652');
`

[dub.xlsx](https://github.com/firefly-iii/firefly-iii/files/2556933/dub.xlsx)

**Comment by JC5** [comment]
Thanks @filoor. I haven't had time to look into this but it is on my list.

**Comment by filoor** [comment]
@JC5  Thanks will wait for it :D

**Comment by filoor** [comment]
@bot Your wrong :D

**Comment by JC5** [comment]
Reopened.

**Comment by JC5** [comment]
I've not been able to reproduce this, sorry about that.
