### ISSUE TITLE
Transaction bugs

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#1837]
**Bug description**
I am running Firefly III version 4.7.8 

1. I am able to input non-numeric values into transaction form. strangely enough, i am only able to input the alphabet e. (other alphabets don't work) 

2. The "Withdrawal" button text in the quickswitch  needs more UI spacing.

![untitled](https://user-images.githubusercontent.com/5896415/47712655-38f91d80-dc73-11e8-8dd2-d3cf6abc7aa3.png)

**Comment by JC5** [comment]
Let's see, thanks for opening the issue. 

1. The "e" can be used because of scientific notation like so "2.135987e+96"
2. This is not something I can really help, it depends on the screen width. If you need more space, you can minimize the left menu bar.

**Comment by emansih** [comment]
![no](https://user-images.githubusercontent.com/5896415/47713910-57ace380-dc76-11e8-8453-f9b39a258982.png)

![y](https://user-images.githubusercontent.com/5896415/47713947-76ab7580-dc76-11e8-89ed-ce38ae10f1bb.png)

Does not work as expected though

**Comment by JC5** [comment]
It won't no. The validation you are confronted with is local, and I cannot set it more accurately than "number". And scientific numbers are included. So your browser will accept it.

Firefly III itself however only accepts normal numbers.
