### ISSUE TITLE
Import FinTS result in wrong current balance

### ISSUE THREAD

**Issue by danielpondruff** [firefly-iii/firefly-iii#1839]
**Bug description**
I am running Firefly III version 4.7.8

Please let me know what information you need from me.

**Steps to reproduce**
import FinTS. Choose 01.01.2017 - 31.10.2018

**Expected behavior**
the right $balance$ of my bank account

**Comment by JC5** [comment]
Tell me which transactions are wrong, and why. Bad amounts? Bad account?

**Comment by bnw** [comment]
@danielpondruff Note that the FinTS import as of yet only imports transactions and does not modify the starting balance of your account.
So unless the balance of your account was exactly 0 on 01.01.2017, the current balance is bound to be wrong. Check out the "Virtual balance" setting of your account.

That aside, it may very well be that some transactions are not correctly imported. I could imagine that this might be the case for some type of "special" transactions such as fees from your bank or interest payments. If you belive that this is the case, it would be really helpful if you could identify which transactions are causing the problem.
