### ISSUE TITLE
Illegal string offset 'basename'

### ISSUE THREAD

**Issue by raihanulroman** [firefly-iii/firefly-iii#1840]
Hi dear,
Really loving it except I stuck in the following error.

**Bug description**

I am running Firefly III version 4.7.8 on https://myusername.herokuapp.com
When I am trying to export data and click on "Export data" it shows the following error:

```
`Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:
Illegal string offset 'basename'
More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.`
```

Screenshot: http://prntscr.com/lct4mk

**Extra info**
Using google Chrome

Thanks in advance.

**Debug info**
Debug information generated at 2018-10-31 18:55:50 UTC for Firefly III version **4.7.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.8 |
| FF API version | 0.81 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stdout |
| PHP version | 7.2.11 |
| Display errors | Off |
| Session start | 2010-01-01 00:00:00 |
| Session end | 2018-10-31 00:00:00 |
| Session first | 2010-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, ldap, mbstring, Zend OPcache |
| Installed packages | adldap2/adldap2@v8.1.5, adldap2/adldap2-laravel@v4.0.10, bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, danhunsaker/laravel-flysystem-others@v1.3.4, danhunsaker/laravel-flysystem-service@v1.2.2, davejamesmiller/laravel-breadcrumbs@5.1.2, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.6, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.7.11, laravel/passport@v7.0.3, laravelcollective/html@v5.7.1, lcobucci/jwt@3.2.4, league/commonmark@0.18.0, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.48, league/flysystem-replicate-adapter@1.0.1, league/flysystem-sftp@1.0.17, league/fractal@0.17.0, league/oauth2-server@7.2.0, litipk/flysystem-fallback-adapter@0.1.2, monolog/monolog@1.23.0, mschindler83/fints-hbci-php@1.0.4, nesbot/carbon@1.34.0, opis/closure@3.1.1, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v9.99.99, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.9, swiftmailer/swiftmailer@v6.1.3, symfony/console@v4.1.6, symfony/css-selector@v4.1.6, symfony/debug@v4.1.6, symfony/event-dispatcher@v4.1.6, symfony/finder@v4.1.6, symfony/http-foundation@v4.1.6, symfony/http-kernel@v4.1.6, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.6, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.6, symfony/translation@v4.1.6, symfony/var-dumper@v4.1.6, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.6,  |

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
Thanks for submitting, will be fixed in the next release.
