### ISSUE TITLE
Next expected match not updating when bills are paid

### ISSUE THREAD

**Issue by adnix42** [firefly-iii/firefly-iii#1841]
**Bug description**
I am running Firefly III version 4.7.8.

Sometimes when a bill is paid and matched to a transaction the next expected match does not increment to the following month. I have yet to figure out what triggers the bug and what doesn't.

**Steps to reproduce**
Unfortunately this is an intermittent problem. I can't reproduce every time.

**Expected behavior**
When a transaction is tied to a bill within a period and the bill repeats it should push the next expected match date out to the next date per the schedule.

**Extra info**
Debug info:
Debug information generated at 2018-10-31 12:00:58 America/Los_Angeles for Firefly III version **4.7.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.8 |
| FF API version | 0.81 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.11 |
| Display errors | Off |
| Session start | 2018-10-01 00:00:00 |
| Session end | 2018-10-31 23:59:59 |
| Session first | 2018-08-10 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, ldap, pdo_mysql, pdo_pgsql, sodium, tidy, zip |
| Installed packages | adldap2/adldap2@v8.1.5, adldap2/adldap2-laravel@v4.0.10, bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, danhunsaker/laravel-flysystem-others@v1.3.4, danhunsaker/laravel-flysystem-service@v1.2.2, davejamesmiller/laravel-breadcrumbs@5.1.2, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.6, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.7.11, laravel/passport@v7.0.3, laravelcollective/html@v5.7.1, lcobucci/jwt@3.2.4, league/commonmark@0.18.0, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.48, league/flysystem-replicate-adapter@1.0.1, league/flysystem-sftp@1.0.17, league/fractal@0.17.0, league/oauth2-server@7.2.0, litipk/flysystem-fallback-adapter@0.1.2, monolog/monolog@1.23.0, mschindler83/fints-hbci-php@1.0.4, nesbot/carbon@1.34.0, opis/closure@3.1.1, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v9.99.99, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.9, swiftmailer/swiftmailer@v6.1.3, symfony/console@v4.1.6, symfony/css-selector@v4.1.6, symfony/debug@v4.1.6, symfony/event-dispatcher@v4.1.6, symfony/finder@v4.1.6, symfony/http-foundation@v4.1.6, symfony/http-kernel@v4.1.6, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.6, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.6, symfony/translation@v4.1.6, symfony/var-dumper@v4.1.6, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.6,  |

**Bonus points**
Attached screenshot
![image](https://user-images.githubusercontent.com/17954591/47812137-c9337300-dd04-11e8-9b26-91d978f3488a.png)

**Comment by JC5** [comment]
Thanks, I'll try to replicate it as well.

**Comment by adnix42** [comment]
Quick update. Just noticed that when the period switched over to November the Next expected match field updated:
![image](https://user-images.githubusercontent.com/17954591/47928051-4c2e0800-de82-11e8-8098-5e5b0fa90511.png)

**Comment by adnix42** [comment]
I just submitted a transaction for the 168 bill and the same thing happened. I dont know this for sure but it seems like its tied to specific bills. Maybe there is a setting I have set wrong in these instances? Should I delete these bills and re-establish them? I would rather not due that since there is a history with confirmation numbers attached.
![image](https://user-images.githubusercontent.com/17954591/47928739-49ccad80-de84-11e8-9a5b-581ee6430752.png)

**Comment by JC5** [comment]
Could you share with me the min/max, date, repeat freq and skip value?

**Comment by JC5** [comment]
Never mind, I can replicate the issue. Stay tuned.

**Comment by JC5** [comment]
OK, so Firefly III can handle bills that are paid late, but not bills that are paid early. It will assume the next date (the 15th) is still due, unless you pay ON that date or after it. Only then will it jump to the next one.

I can simply assume that any payment is the correct one (and jump to the next period), but this only makes sense when you're viewing a monthly bill in a monthly overview.

Some users have weekly bills that they view by quarter. Then too, Firefly III must assume that the bill is not paid until the actual next date has passed (or the bill is paid on exactly that date).

I see the confusion, but I have no answer. All I can suggest is to put the bill on the 1st of the month. Then the calculation will correctly jump over to the next month.

**Comment by adnix42** [comment]
Hmmm I don't want to make all bills due on the 1st as I use this list to track when things are due and that would confuse my workflow. 

What I will do, I think, is make the transaction date the same as the Next expected match date reguardless of the excat payment date. I will then use the notes field to record the actual pay date along with confirmation numbers. Not very elegant but it will work.
