### ISSUE TITLE
Marking transactions as applying to a different month's budget

### ISSUE THREAD

**Issue by spirituallyinsane** [firefly-iii/firefly-iii#1843]
I am running Firefly III version 4.7.7

**Description**
Is there a way in Firefly to mark a transaction as applying to a different date?  I enter transactions with their correct date from my bank statement, but sometimes things like paychecks and bills process a little early or late, and they show as being on the wrong month (e.g. my salary disburses on a Friday before the 1st of the month if the 1st falls on a weekend.  

I wasn't able to find anything in the documentation on this, but I'd love to have an answer to it.  Otherwise my budgets are far off some months.

![image](https://user-images.githubusercontent.com/14048499/47825690-99f32500-dd49-11e8-93a2-f5dcaa9aa054.png)

**Comment by JC5** [comment]
No, this isn't possible. The other dates are for cosmetic use only, at the moment. To limit complexity Firefly III only uses the date field for time based calculations.

I suggest that you date transactions to when it's most convenient. The goal is not to mimic your bank but to administer your cash flows. If a small change like this is necessary, so be it.

**Comment by spirituallyinsane** [comment]
Understood, thanks.  It'd be nice to have for future accounting purposes, but not a huge deal.
