### ISSUE TITLE
Returning to category list after bulk edit.

### ISSUE THREAD

**Issue by bm751613** [firefly-iii/firefly-iii#1846]
**Bug description**
I am running Firefly III version 4.7.7

I have noticed that depending on the way I edit a transaction (bulk edit, multi-select edit, single edit) there are different results after updating. One will return me to dashboard, another will return me to the previous transaction list and another will return me to the page for a single transaction.

**Steps to reproduce**
I am running into this while I am going through my backlog of transactions and updating their categories. I start on the "without a category" page for a given month and multi-select for whatever category I am updating and selecting one of the way available to edit the transactions.

**Expected behavior**
I would expect to return to the "without a category" filtered transaction list but it does not return me here for all of the different editing methods.

Thanks for all the hard work!

**Comment by JC5** [comment]
The redirect should always redirect you back to where you came from. Do you have multiple tabs open?

**Comment by bm751613** [comment]
No I do not. I notice it mainly when I am looking at a list of transactions with no category. From here I would click on a single transaction and click "edit" from the drop down and update. This will take me back to the list I was at before editing. 

If I select more than one transaction and choose "bulk-edit", after updating I am directed to the dashboard.

**Comment by JC5** [comment]
Sorry, have had no time yet. Will check it out.

**Comment by JC5** [comment]
Alright so the bot closed this but I put it on my list. It's part of a routine that works for all of Firefly III: every page has the same piece of code handling redirections. I hope I can fix this for the next release.
