### ISSUE TITLE
Missing swiss currency

### ISSUE THREAD

**Issue by kriegalex** [firefly-iii/firefly-iii#1847]
**Description**
I wish Firefly to support swiss franc currency.

**Solution**
Add currency in list of currencies.

**What are alternatives?**
Add swiss franc manually on each new install.
Use euros and pretend they are swiss francs.

**Additional context**
A pull request will be dropped soon for this.

**Comment by kriegalex** [comment]
Fixed by PR #1848

**Comment by JC5** [comment]
Nice, merged :+1:
