### ISSUE TITLE
Exporting 'account names' directly from the database (How to decode/decrypt)

### ISSUE THREAD

**Issue by fredericdepuydt** [firefly-iii/firefly-iii#1851]
I am running Firefly III version 4.7.7

** Description **
I'd like to export the account names from the Database using a self written php script. I need this list of names to pre-proces my import CSV documents.

** Question **
How are the names currently encrypted, and how can I decode/decrypt them myself.

**Comment by JC5** [comment]
If you open your `.env` file you can change `USE_ENCRYPTION` to false. Then, use the following command to decrypt the database:

```
php artisan firefly:use-encryption
```

All entries will be available decrypted in the database.

**Comment by fredericdepuydt** [comment]
That's also an option..
Worked great, thanks!
