### ISSUE TITLE
Import data from KMyMoney

### ISSUE THREAD

**Issue by tobru** [firefly-iii/firefly-iii#1856]
I am running Firefly III version `latest`

**Description**

I would like to migrate my data from KMyMoney to Firefly III. Did anyone ever do this? If yes, how? Or if no one ever did this: Any idea how data could be migrated?

**Comment by lucavallerini** [comment]
I used KMyMoney for only a few months so probably I don't remember it very well, but I think you can export the transactions in CVS files and then you can import them in Firefly III.  The CVSs exported from KMyMoney may need some tweaks but I think it could be done.

Probably you'll have do to some tests, so be aware of this behaviour https://github.com/firefly-iii/firefly-iii/issues/1585

**Comment by tobru** [comment]
Thanks for pointing to #1585, this helped a lot.
