### ISSUE TITLE
Default currency not visible in Balance box

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1860]
**Description**
I would like to always see default currency in "Balance" box on the Dashboard. Preferably as the first item.

Why? Because this month I have transactions in both EUR (ID=1) and USD (ID=2), so my default, most important, PLN (ID=9) was unlucky.

![obraz](https://user-images.githubusercontent.com/3846677/48219634-4a39dc80-e38d-11e8-8cfa-bf4df924dc01.png)

**Solution**
Force default currency as first item in response from `/json/box/balance` if we can rely on that web browsers will respect order of keys in JSON object. If not maybe some client-side sorting with `GLOBAL_CONFIG.defaultCurrencyId`. I'm sure you'll figure something out ;)

**What are alternatives?**
1. Do similar thing like with Net worth and add checkbox (or rename and reuse "Include in net worth") allowing to ignore transactions from selected accounts.

2. Get rid of non-default currencies in that box and always display one big number like in three others.

**Additional context**
I'm using Firefly III 4.7.8.

**Comment by JC5** [comment]
Ah yes, that should not be a problem. It's a pretty basic for-each loop.

**Comment by JC5** [comment]
I'm going to treat this as a bug and pick it up for the next release.
