### ISSUE TITLE
Little issues with period selector in navbar

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1861]
1. Custom range selector breaks on Firefox 63.0.1:
![obraz](https://user-images.githubusercontent.com/3846677/48221121-78212000-e391-11e8-9a77-785ce0bb52ce.png)
All the options are below. Probably too little `width` or some additional `margin`/`padding`/`border` only in Firefox. Works OK on IE and Edge.

2. "Today" link is super useful, but I would name it "Current month" or "This month", because "Today" means 1 day. Especially in comparison with "Last seven days".

3. Buttons "Apply" and "Cancel" aren't visible when there are more options (you have to scroll).

4. <del>Do we need first option which does nothing except closing popup and duplicates information displayed on navbar?</del> OK, maybe it plays role similar to `<option selected>...</option>`

5. Selecting custom range orders months in weird way.
![obraz](https://user-images.githubusercontent.com/3846677/48222255-71e07300-e394-11e8-98d7-0dd5490cd397.png)
(somebody changed language to German on demo site :D)
    
    I guess it's:
    - whole month for selected range
    - previous month
    - next month
    but maybe more natural would be:
    - previous month
    - whole month for selected range
    - next month

Nothing serious (except maybe the first point). I just tired to look on things from new-user's point of view.

**Comment by JC5** [comment]
Ah yes, I'll add some margin. The other points I'll see what I can do.

**Comment by JC5** [comment]
Fixed by upgrading the library.
