### ISSUE TITLE
Transfers - How to merge transactions and prevent doubling up?

### ISSUE THREAD

**Issue by kcomplexes** [firefly-iii/firefly-iii#1863]
Hi,

I'm really struggling to work out how to set up transfers. I have two accounts. One is my everyday account while the other is my savings account; both are with the same bank.

The csv I receive looks like this:
Date,Account,Description,Credit,Debit
d/m/Y,111111,text,450,
d,m,Y,222222,text,,-450

I mapped the account numbers to my accounts in Firefly. Everything has imported, and the balances are correct. However, the transfers between accounts were (understandably) not recognized, and as such the transfers show up as transactions in both accounts. 
Everyday account:
![2](https://user-images.githubusercontent.com/16506704/48260251-4b890900-e462-11e8-8cfc-768dd5e4d90e.PNG)
Savings account:
![3](https://user-images.githubusercontent.com/16506704/48260280-6d828b80-e462-11e8-8f7a-a6347f2dc5a7.PNG)

Whatever rule I create seems to end up with either double spending, or double income - one account seems to have a transfer AND a deposit/withdrawal.

For example, This:
![this](https://user-images.githubusercontent.com/16506704/48290843-e5c96b00-e4bb-11e8-8110-1e717057b4af.PNG)
Becomes:
![become](https://user-images.githubusercontent.com/16506704/48291107-be26d280-e4bc-11e8-8f81-0345c4a407e1.PNG)

The internal transfers are doubled (example of one such transfer and transaction pair):
![double](https://user-images.githubusercontent.com/16506704/48291047-8b7cda00-e4bc-11e8-8b95-4f60c4d18c8c.PNG)

with this set of rules:
![ruleno1](https://user-images.githubusercontent.com/16506704/48290940-2aed9d00-e4bc-11e8-9fca-7036465fc254.PNG)

I feel like it's a matter of not quite understanding the process, so if someone could help explain the correct rules to 'merge' the withdrawal and deposit into one transfer?

I am running Firefly III version 4.7.8

**Comment by lucavallerini** [comment]
The rule converts one transaction into a transfer but it does not remove the other transaction, and as far as  I know rules do not support that, so the behaviour is correct. You could try to find a way, with rules, to add a specific label to the transactions that you want to be removed, and after that you can remove all transactions with that label.

What are the specific settings of your imports? Because Firefly III should be able to recognize two transactions as a transfer, I do not remember having problem with that in the past, but I could be wrong.

**Comment by kcomplexes** [comment]
I've only just noticed an almost identical question to this - not sure how I missed it while searching. Apologies about that!  #1845 

> What are the specific settings of your imports? Because Firefly III should be able to recognize two transactions as a transfer, I do not remember having problem with that in the past, but I could be wrong.



> If you properly map the account field from your CSV file to the asset accounts in your installation, Firefly III will create transfers instead of withdrawals or deposits, just like @lucavallerini says. This is also explained in the [documentation](https://firefly-iii.readthedocs.io/en/latest/import/csv.html#mapping-data).

Thanks for responding. I don't think I'm understanding the concept correctly, because I'm not sure how I could map these any more correctly than I already have? Unfortunately, the descriptions are different on the outgoing account than on the ingoing account... and looking at the referenced question, it looks as though that me be the problem here?

The config I've used.
```
{
    "file-type": "csv",
    "date-format": "d\/m\/Y",
    "has-headers": true,
    "delimiter": ",",
    "apply-rules": false,
    "specifics": [],
    "import-account": 9,
    "column-count": 5,
    "column-roles": [
        "date-transaction",
        "account-number",
        "description",
        "amount_credit",
        "amount_debit"
    ],
    "column-do-mapping": [
        false,
        true,
        false,
        false,
        false
    ],
    "column-mapping-config": {
        "1": {
            "11111111": 9,
            "22222222": 10
        }
    }
}
```

import csv:
data,account,description,credit,debit
![image](https://user-images.githubusercontent.com/16506704/48310032-a8550280-e5cd-11e8-946e-bc8dc078fd7b.png)

Thanks again!

**Comment by JC5** [comment]
> Unfortunately, the descriptions are different on the outgoing account than on the ingoing account

That's the problem. With the descriptions being different, Firefly III isn't able to verify the records are equal.

**Comment by kcomplexes** [comment]
Thanks again for responding (and building the software!).

Is there any way to turn this into a feature request? i.e. using rules, or using a 'bank specific options' template? A small bit if messing around in Excel is easy enough to fix this, but would be great to have an inbuilt option.

Either way, thanks again for all the work you have put into the software.

**Comment by NimdaBE** [comment]
i have the same thing with my bank... The descriptions for the same transaction (transfer between accounts at the same bank) are different for the 2 accounts... I usually import one account first, then i reconcile that account. Then i import the statements of the second account and when i go into that account i see with the checkmarks in front if a transaction with the same date and amount (and more or less the same description) has already been verified in another account, and i just delete the other transaction. Because its a transfer the first (reconciled) transaction appears in both account views...

**Comment by rubenverhoef** [comment]
I have the same problem.
I have two CVS files one of my own account and one of my shared account.
The description is different but the transaction is the same and should be handled as duplicates. Is there a method to define custom duplicate rules?

I'm now thinking to make a program which will make the description field of these entries the same so i can upload it into firefly. Is there a method to do this automatically after upload so i do not have to do it manually every time?

**Comment by JC5** [comment]
If the description is different Firefly III won't be able to see it's a duplicate. There is no method to add custom duplication rules. This is a way too small use case. You'll have to fix something yourself for this.
