### ISSUE TITLE
firefly does not display the correct annual total of a category

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#1865]
**Bug description**
I am running Firefly III version 4.7.8. 
I select  a category and a range (eg 01-01-2006 - 31-12-2006)
as you can see, the given total on the red bar chart for 2006 is €859,45 which is correct, but below on the right it puts this total (€859,45) as uitgegeven for the year 2007 instead of 2006. When you hoover the mouse over the 2005 red bar chart it shows (€747,61) but again below on the right this total is shown as is was uitgegeven for the year 2006. The correct totals are those of the bars

I have tried different categories but all with same result. 
![img_20181111_181814](https://user-images.githubusercontent.com/44246750/48316123-895f6c00-e5df-11e8-80df-c450aa7e5f45.jpg)

**Steps to reproduce**
What do you need to do to trigger this bug?

**Expected behavior**
What do you expect to see after those steps?

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

**Bonus points**
Earn bonus points by:

- Post a stacktrace from your log files
- Add a screenshot

**Comment by JC5** [comment]
I am not sure how you execute these steps:

>  I select a category and a range (eg 01-01-2006 - 31-12-2006)

I'm assuming you're  on a page with an URL like this one: `/categories/show/1`.

But how exactly do you select the range?

**Comment by JC5** [comment]
I found some issues with the category charts, and I've pushed some fixes. You can check this out on the [demo site](https://demo.firefly-iii.org/).

**Comment by bartmaniac** [comment]
> I am not sure how you execute these steps:
> 
> > I select a category and a range (eg 01-01-2006 - 31-12-2006)
> 
> I'm assuming you're on a page with an URL like this one: `/categories/show/1`.
> 
> But how exactly do you select the range?

first I select a category and then I select the range zelf bereik kiezen

![schermafbeelding 2018-11-11 om 22 20 56](https://user-images.githubusercontent.com/44246750/48318381-3a75fe80-e600-11e8-99c5-50908b8710d7.png)

My options look like this
Changing 'the range' seems to put is right (eg 3 maanden (kwartaal) or 6 maanden

![schermafbeelding 2018-11-11 om 22 23 05](https://user-images.githubusercontent.com/44246750/48318390-6f825100-e600-11e8-934d-e5233d28835b.png)

**Comment by JC5** [comment]
Alright, I'll check it out.

**Comment by JC5** [comment]
I've pushed some fixes for the next release.
