### ISSUE TITLE
Lack of data from Accounts API 

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#1866]
I am running Firefly III version 4.7.8

Not sure if this is a bug or just not implemented. When calling `https://xxx.firefly.com/api/v1/accounts?type=liability`, the following is shown

```
 {
            "type": "accounts",
            "id": "5",
            "attributes": {
                "updated_at": "2018-11-13T21:32:54+08:00",
                "created_at": "2018-11-13T21:32:54+08:00",
                "name": "test liability",
                "active": true,
                "type": "Loan",
                "currency_id": 3,
                "currency_code": "GBP",
                "currency_symbol": "£",
                "currency_dp": 2,
                "current_balance": -123,
                "current_balance_date": "2018-11-13",
                "notes": null,
                "monthly_payment_date": null,
                "credit_card_type": null,
                "account_number": null,
                "iban": "",
                "bic": null,
                "virtual_balance": 0,
                "opening_balance": null,
                "opening_balance_date": null,
                "role": null
            }
```

From the [docs](https://firefly-iii.readthedocs.io/en/latest/api/accounts.html#id2), the parameters to create a liability account has to include `liability_type`, `liability_amount`, `liability_start_date`, `interest`, `interest_period`. However the API does not return values of those types. This makes editing existing data 
 via the API difficult. 

Another issue with the API is the inconsistent return value, `iban` is returned as an empty string whereas `notes`, `monthly_payment_date`, `credit_card_type`, `bic`, `opening_balance`, `opening_balance_date` and `role` is returned as null value. 

Thanks

**Comment by JC5** [comment]
This will be fixed in the next release.
