### ISSUE TITLE
Houston, we have a problem

### ISSUE THREAD

**Issue by wprauchholz** [firefly-iii/firefly-iii#1867]
I am running Firefly III version 4.7.8

**Description**
I changed the email address in Administration and made a spelling mistake.
I can therefore not verify my email address and hence logged myself out of firefly-iii.
I get this message: "Until you verify your email address, you cannot login.

Is there a trick to fix this?

**Steps to reproduce** 
Every login attempt

**Extra info**

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
There is a cancel message sent to your old email address. If it wasn’t sent you can find it in your log files. 

If that fails you can edit the users table.

**Comment by wprauchholz** [comment]
I went through the log files in 'firefly-iii/storage/logs' and can't find a cancel message.
So what do  Ineed to change in mysql to restore the old email address?

I do not have phpadmin, but could install if required.

Thanks, Wolfgang

**Comment by JC5** [comment]
Change “blocked” to 0 should be enough.

**Comment by wprauchholz** [comment]
Hi JC5, would you mind to elaborate a little bit more that, so that I can make the required. change.

Thanks you, Wolfgang

**Comment by JC5** [comment]
:+1:
