### ISSUE TITLE
Failing on sending FinTS/HBCI import job because of input field restriction

### ISSUE THREAD

**Issue by Lazalatin** [firefly-iii/firefly-iii#1868]
**Bug description**
I am running Firefly III version 4.7.8

Importing with the FinTS/HBCI Feature fails, when the corresponding API awaits only "Bank Code" but no "Username" (User ID)

**Steps to reproduce**
Have a bank account i.e. of the comdirect Bank AG and try to use FinTS/HBCI. Fail at trying to use the import job without setting "Username".

Documentation here (german): https://www.comdirect.de/pbl/service/supportfaq/FaqRH.do?faqId=100

**Expected behavior**
Only one of these input fields should be mandatory.

**Extra info**
Debug information generated at 2018-11-14 08:58:58 Europe/Berlin for Firefly III version **4.7.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.8 |
| FF API version | 0.81 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.2.10-0ubuntu0.18.04.1 |
| Display errors | Off |
| Session start | 2018-11-01 00:00:00 |
| Session end | 2018-11-30 23:59:59 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, memcache, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| Installed packages | adldap2/adldap2@v8.1.5, adldap2/adldap2-laravel@v4.0.10, bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, danhunsaker/laravel-flysystem-others@v1.3.4, danhunsaker/laravel-flysystem-service@v1.2.2, davejamesmiller/laravel-breadcrumbs@5.1.2, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.6, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.7.11, laravel/passport@v7.0.3, laravelcollective/html@v5.7.1, lcobucci/jwt@3.2.4, league/commonmark@0.18.0, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.48, league/flysystem-replicate-adapter@1.0.1, league/flysystem-sftp@1.0.17, league/fractal@0.17.0, league/oauth2-server@7.2.0, litipk/flysystem-fallback-adapter@0.1.2, monolog/monolog@1.23.0, mschindler83/fints-hbci-php@1.0.4, nesbot/carbon@1.34.0, opis/closure@3.1.1, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v9.99.99, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.9, swiftmailer/swiftmailer@v6.1.3, symfony/console@v4.1.6, symfony/css-selector@v4.1.6, symfony/debug@v4.1.6, symfony/event-dispatcher@v4.1.6, symfony/finder@v4.1.6, symfony/http-foundation@v4.1.6, symfony/http-kernel@v4.1.6, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.6, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.6, symfony/translation@v4.1.6, symfony/var-dumper@v4.1.6, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.6,  |

**Comment by JC5** [comment]
I'll see what I can do. I am not sure if the library supports it.

I'm tagging @bnw in case he knows.

**Comment by bnw** [comment]
Ah, when I implemented the UI I just did not think that the username was optional. 
I tested that the library does not crash when used without username.

@Lazalatin Could you try if the import works with the change from #1876? (Its only one line which you could temporarily change in your installation.)

**Comment by JC5** [comment]
PR is merged.

**Comment by Lazalatin** [comment]
> @Lazalatin Could you try if the import works with the change from #1876? (Its only one line which you could temporarily change in your installation.)

I did and sadly I was not able to connect to the fints API of the comdirect bank. Tried some variations on how to "log-in" because there are differences in the naming of the credential fields...
So there seems to be another Issue with that. Maybe we can find out, what is wrong?

Can someone point me to how and where to debug the importing process in order to provide more info about the issue?

**Comment by pew** [comment]
@Lazalatin I'm trying the same thing right this moment, I am able to connect to comdirect this way:

* FinTS API URL: `https://fints.comdirect.de/fints`
* Bank code: Your Bankleitzahl
* Username: your login username without appending 2x `0`
* PIN/Password: well, your login pin

Unfortunately firefly 4.7.8 only recognizes one account by name and fills all other with blank option lines. When I try to select one of the apparently *blank* lines I'm getting an import error: 

```
local.ERROR: The import routine crashed: Request Failed: Die Nachricht enthaelt Fehler.  
```

It works fine for the one account it recognizes though.

**Comment by Lazalatin** [comment]
@pew Thanks! That really helped!
Apparently one should ignore the information from the comdirect bank knowledge base and just enter the credentials as provided by fireflyIII :man_shrugging: 

I can confirm that there is a blank line when importing, I ignored it for now. Will update this comment when I added my other accounts :grin:

**Comment by bnw** [comment]
The list of accounts that are presented to the user in the second step of the import are the IBANs of the "SEPA-Accounts" as reported by the bank. Blank lines probably mean that the accounts have no IBAN.

If importing one of the blank lines does not work, it is most likely not supported by the library we use.
You could try to reproduce a minimum working example (e.g. use https://github.com/mschindler83/fints-hbci-php/blob/master/Samples/statement_of_account.php) and contact the developer.

---

>@Lazalatin I'm trying the same thing right this moment, I am able to connect to comdirect this way:
>
>    FinTS API URL: https://fints.comdirect.de/fints
>    Bank code: Your Bankleitzahl
>    Username: your login username without appending 2x 0
>    PIN/Password: well, your login pin

@JC5 Maybe this is knowledge that could be added to the help page?

**Comment by JC5** [comment]
I've added some basic instructions to the docs.
