### ISSUE TITLE
Import file question: X-reference required

### ISSUE THREAD

**Issue by wprauchholz** [firefly-iii/firefly-iii#1870]
I am running Firefly III version 4.7.8

**Description**
Which value in the drop-dow list 'Column data meaning' corresponds to field 'Destination account(s)' when importing a CSV file?

Thank you.

Wolfgang

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Opposing account name, iban or ID.
