### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by NanneHuiges** [firefly-iii/firefly-iii#1872]
**Bug description**
I am running Firefly III version 4.7.8

Currently I'm getting a 404 on some images on the import/export page. Not sure if more resources are 'missing', but e.g. the images the logos dir (e.g. `images/logos/file.png`) give 404.

De files seem to be there:

```
root@835bea458283:/var/www/firefly-iii/public/v1/images/logos# ls -alh
total 64K
drwxr-xr-x 2 root root 4.0K Nov  6 16:53 .
drwxr-xr-x 4 root root 4.0K Nov  6 16:53 ..
-rw-r--r-- 1 root root   16 Nov  6 16:53 .htaccess
-rw-r--r-- 1 root root 3.3K Nov  6 16:53 bunq.png
-rw-r--r-- 1 root root 3.5K Nov  6 16:53 csv.png
-rw-r--r-- 1 root root 2.7K Nov  6 16:53 fake.png
-rw-r--r-- 1 root root 2.4K Nov  6 16:53 file.png
-rw-r--r-- 1 root root 2.4K Nov  6 16:53 fints.png
-rw-r--r-- 1 root root 8.2K Nov  6 16:53 plaid.png
-rw-r--r-- 1 root root 3.3K Nov  6 16:53 quovo.png
-rw-r--r-- 1 root root 3.4K Nov  6 16:53 spectre.png
-rw-r--r-- 1 root root 5.8K Nov  6 16:53 ynab.png
-rw-r--r-- 1 root root 2.6K Nov  6 16:53 yodlee.png
```

and it might be the ownership? not sure tbh, I'm assuming the v1 is correct and this is the right dir to look at. I might need to run some chmod magic on this?

**Steps to reproduce**
There isn't a specific thing I actually did that stands out? I'm running with the docker-compose method, on a mac. The only thing I did what I don't do daily is reboot (os update) and so I restarted the docker, but I don't think that should do this?

I did run the update script/commands at a point.

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

**Comment by JC5** [comment]
It’s a bug. I forgot to update the path on the import page after I moved them to the “v1” directory. It will be fixed in the next release.

Thanks for reporting this!

**Comment by NanneHuiges** [comment]
Fast response, thanks!
