### ISSUE TITLE
Transaction report

### ISSUE THREAD

**Issue by erdelyijanos** [firefly-iii/firefly-iii#1875]
Transaction report shall have an option that the transactions with split categories are shown as one.
It is very hard to do an "audit" with transactions shown split. In the bank transaction list these are just one sum that I paid by card or bank transfer. It involves a lot of manual work to do this.

**Solution**
This shall be a checkbox in the reports menu under extra options.

**What are alternatives?**
A lot of manually conducted additions on a piece of paper :)

**Additional context**

**Comment by JC5** [comment]
If you need a perfect reflection of your bank account, please don't split transactions. If you need to reconcile your account, please use the appropriate option in the account overview.
