### ISSUE TITLE
Wrong page shown when navigating no-category pages

### ISSUE THREAD

**Issue by RudolfRendier** [firefly-iii/firefly-iii#1878]
**Bug description**
I am running Firefly III version 4.7.8 and when I want to navigate to page 2 of **all** my no-category transactions it takes me back to the current month.

**Steps to reproduce**
Go to:
http://server:port/categories/list/no-category/all
Navigate away from page 1.
To 2: http://server:port/categories/list/no-category?page=2
To 3: http://server:port/categories/list/no-category?page=3

**Expected behavior**
I'd expect to go to:
http://server:port/categories/list/no-category/all?page=2
http://server:port/categories/list/no-category/all?page=3

But the /all is omitted from the URL.

**Extra info**

Debug information generated at 2018-11-19 21:23:24 Europe/Amsterdam for Firefly III version **4.7.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.8 |
| FF API version | 0.81 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | debug, stdout |
| PHP version | 7.2.11 |
| Display errors | Off |
| Session start | 2018-11-01 00:00:00 |
| Session end | 2018-11-30 23:59:59 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 27 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:63.0) Gecko/20100101 Firefox/63.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, ldap, pdo_mysql, pdo_pgsql, sodium, tidy, zip |

**Comment by JC5** [comment]
Nice find, should be an easy fix.
