### ISSUE TITLE
Can't create transactions

### ISSUE THREAD

**Issue by Elmfire** [firefly-iii/firefly-iii#1880]
I am running Firefly III version 4.7.8

Whenever I attempt to create or edit a transaction, firefly throws a fatal error

`Argument 1 passed to FireflyIII\Helpers\Attachments\AttachmentHelper::saveAttachmentsForModel() must be an instance of FireflyIII\Helpers\Attachments\object, instance of FireflyIII\Models\TransactionJournal given, called in /var/www/firefly-iii/app/Http/Controllers/Transaction/SingleController.php on line 358 `

When I re-open firefly, the transaction appears to be stored correctly. I am connecting to firefly via localhost and it is running on Debian under the Windows Subsystem for Linux. Refreshing the page does not work, I have to return to the dashboard. Creating other things (I've tried budgets and accounts) is fine. 

Stacktrace output is here (can't fit the whole thing in one screenshot)
![firefly stacktrace](https://user-images.githubusercontent.com/39219038/48821016-78a6b700-ed92-11e8-9a9a-3589325d6288.JPG)
![image](https://user-images.githubusercontent.com/39219038/48821049-9b38d000-ed92-11e8-8e3f-66facba857a2.png)

Let me know if I've missed any relevant information to include.

**Comment by JC5** [comment]
You need PHP 7.2 to run Firefly III, and this is the error you get when you're on PHP 7.1 or lower.

**Comment by Elmfire** [comment]
Thank you, I had both php7.1 and 7.2 installed but had not correctly configured apache to use use 7.2.
