### ISSUE TITLE
Spectre import error: "Not available for apps"

### ISSUE THREAD

**Issue by andreapx** [firefly-iii/firefly-iii#1881]
I am running Firefly III version 4.7.8

**Description**
When I try to import from Spectre, I get this error (in the Apache log):
```
produxtion.ERROR: The import routine crashed: Guzzle Exception: Client error: `GET https://www.saltedge.com/api/v4/customers/?from_id=0` resulted in a `400 Bad Request` response:
{"error_class":"AppsRestricted","error_message":"Not available for apps.","request":{"from_id":"0"}}

```

When I've created the API Key, I could only create it as a "Service", not as an "App" since the app doesn't accept the Public key.

**Extra info**
Browser: FireFox 63.0.1
Server Apache 2.4.18 with PHP 7.2.12 on Ubuntu 16.04.9

**Comment by JC5** [comment]
I'll have to do some digging to see what's going on. Thanks for reporting this.

**Comment by andreapx** [comment]
I'm using Saltedge API V4 (I can't create the V3 keys). Is this correct?

**Comment by JC5** [comment]
V3 is deprecated and Firefly III supports v4 only. So yes, that's correct.

**Comment by JC5** [comment]
OK I was able to import without any problems. But I suspect this might happen more often in the future. I'll see if I can reconfigure the Spectre import.

**Comment by andreapx** [comment]
In the meanwhile is there something that I can do to work around this issue?

**Comment by JC5** [comment]
Import by hand. Otherwise, no.

**Comment by andreapx** [comment]
After talking with the Spectre support, it turned out that I was creating the key as APP and not as Service (sorry for the miscommunication in the first post, I've done a mess with all the tests!).
Now the connection worked the first time, the other times it ends saying:

`The import has finished. Unknown import result
There were some errors during the import. Please review them carefully.
Row #0 ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyy") could not be imported. It already exists.
Row #1 ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyy") could not be imported. It already exists.
Row #2 ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyy") could not be imported. It already exists.
Row #3 ("Cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyy") could not be imported. It already exists.`

Those transactions do exists, but the new transactions are not fetched, in fact if I try to reimport, on the "Last login" column I see 03/12/18, not today.

**Comment by JC5** [comment]
No worries!

The easiest way to fix this is to manually delete the previously imported entries from your database. They might be imported badly and stored. Firefly III will ignore such transactions. Check out the table `transaction_journals`.

**Comment by andreapx** [comment]
I've got:
- **budget**_transaction_journal (empty)
- **category**_transaction_journal (empty)
- **tag**_transaction_journal (I've truncated it, but the error persist)

**Comment by JC5** [comment]
No table called `transaction_journals`?

**Comment by andreapx** [comment]
...nope...

**Comment by JC5** [comment]
That's not possible. That's the table that contains all of your transactions.

**Comment by andreapx** [comment]
...shame on my...
I was using PhpMyAdmin and I didn't notice the second page on the tables list....SOOORRYYY!
Since I didn't know which were the last transactions imported, I've...well, I've truncated the table :)
But the import problem still persist.

**Comment by JC5** [comment]
Haha no problem. But let's see now. Even in a fresh installation, Firefly III refuses to import specific rows. There's one option left: if the table `transaction_journals` is empty, then `journal_meta` should be as well. Is this correct?

If both tables are empty but the transactions are not imported, these might actual be duplicates. This is not entirely uncommon when importing though.

**Comment by andreapx** [comment]
That table was not empty, I've truncated and now it has imported the transactions, but it has still imported the same (the last beeing of the 12th November) and there are no new transactions (which in the bank are present).
If I try to import again, it says that the last connection was the 30th of November.
...mmm...I'm lost!
