### ISSUE TITLE
Schedule import from Spectre

### ISSUE THREAD

**Issue by andreapx** [firefly-iii/firefly-iii#1882]
**Description**
Please describe your feature request:
It would be nice to be able to schedule a cron job to automatically import transaction from Spectre (and maybe the others).
In this way every time I enter FireflyIII all the transactions are updated. Another thing for which this feature would be useful is that I can run some scripts (that I will create) to check for some transaction into the db.

**Solution**
Describe what your feature would add to Firefly III.
The idea is to create a cron job specifying the bank and the account from which I want to import the transactions

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1461
