### ISSUE TITLE
How to enter this as one transaction? Or split by account?

### ISSUE THREAD

**Issue by cvladan** [firefly-iii/firefly-iii#1883]
I am running Firefly III version 4.7.8

**Description**
I have an expense, fairly typical and often for me, as I usually *carry only credit card* and some small amount of *cash for tipping*.

     Restaurant X. Dinner with Y. Paid 80 usd Card + 8 usd 

Does this needs to be entered as two transactions, almost identical ones?
Is there another, better way?

Personally, every transaction involving dinner, coffee or similar is like this.

**Comment by JC5** [comment]
It’s entirely up to you. Do you track cash in Firefly III? If you do then yes, this would be another expense if you want Firefly III to accurately track your cash balance. Otherwise I’d say don’t bother.

**Comment by cvladan** [comment]
Ok. Thanks
