### ISSUE TITLE
Budget API

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#1884]
I am running Firefly III version 4.7.8

**Description**
How does one retrieve the amount for `Spent between November 1, 2018 and November 30, 2018` in the budget API?
![untitled](https://user-images.githubusercontent.com/5896415/48967828-67bfa500-f021-11e8-8a89-f051efa8f080.png)

**Comment by JC5** [comment]
Not yet. But it's on the list!

**Comment by JC5** [comment]
Whoops

**Comment by emansih** [comment]
i would also like to propose that we merge `/api/v1/available_budgets`, `/api/v1/budgets` and ` /api/v1/budget_limits` into a single unified API. is it possible?

**Comment by JC5** [comment]
Absolutely. The API is not yet final. I want to make sure it is use oriented. Not data oriented. I am also working on a Swagger document and I’ll share it ASAP

**Comment by JC5** [comment]
This will be fixed in the next release.
