### ISSUE TITLE
issue with artisan migrate:refresh

### ISSUE THREAD

**Issue by killmasta93** [firefly-iii/firefly-iii#1886]
**Bug description**
I am running Firefly III version 4.7.8

(please give a clear and concise description of what the bug is)
PHP Warning:  require(/var/www/html/firefly-iii/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/firefly-iii/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/html/firefly-iii/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/firefly-iii/artisan on line 18

**Steps to reproduce**
What do you need to do to trigger this bug?
cd /var/www/html/firefly-iii/
php artisan migrate:refresh --seed

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

Ubuntu 16
NGINX 

Thank you

**Comment by JC5** [comment]
That should be an easy fix. But tell me, did you simply clone the master branch? Which instructions are you following exactly?

**Comment by killmasta93** [comment]
Thank you that did the trick :)

**Comment by chonsanova** [comment]
Hi sorry for necroing this, please let me know if I should create a new issue.

I'n getting the EXACT same error message. I'm following [philthynz's guide](https://gist.github.com/philthynz/ec04833a8e39c7f7d1b0d33cb4197a95). However, it wasn't working when I tried installing Firefly III to /opt, so I did it in /var/www as per [Firefly documentation](https://docs.firefly-iii.org/en/latest/installation/server.html). 

I had been doing `composer install --no-scripts --no-dev` and `composer install --no-dev` but to no avail. I've tried these again after stumbling upon this page, but running those commands gives me the following messages:
![image](https://user-images.githubusercontent.com/16068743/50754687-67baf200-12bb-11e9-8790-b987e39f9604.png)

Any ideas please?

**Comment by chonsanova** [comment]
Nevermind, manage to resolve with a `sudo apt-get install php-ldap` !
