### ISSUE TITLE
Two Factory with U2F

### ISSUE THREAD

**Issue by genofire** [firefly-iii/firefly-iii#1887]
https://en.m.wikipedia.org/wiki/Universal_2nd_Factor

PlayGround for such keys: https://demo.yubico.com/webauthn/

Plugin for NextCloud as PHP Coding Example: https://github.com/nextcloud/twofactor_u2f

**Comment by nearwood** [comment]
Maybe an easier first step would be client cert authentication? Basically the same thing. Would love this for mobile.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947158
