### ISSUE TITLE
internal_reference through API?

### ISSUE THREAD

**Issue by bartonp** [firefly-iii/firefly-iii#1888]
I am running Firefly III version 4.7.8

**Description**
Is there any method to get the value `internal_reference` on all transactions through the API?

**Steps to reproduce** 
1. Add a transaction with an internal_reference
2. Attempt to access via the API

**Extra info**
N/A

**Comment by JC5** [comment]
Most of these fields are not accessible through the API. I'll make a note to expand it.

**Comment by JC5** [comment]
This is fixed in the next release.
