### ISSUE TITLE
Docker on arm

### ISSUE THREAD

**Issue by cwassert** [firefly-iii/firefly-iii#1889]
I tried using the `jc5x/firefly-iii` image on an odroid-c2 running Arch Linux. But I got the error message
```
standard_init_linux.go:207: exec user process caused "exec format error"
```

I have not used docker on arm before, so maybe these problems come from my end.

Then I tried building the image locally (using version 4.7.8), but ran into the following error
```
configure: error: Cannot find ldap libraries in /usr/lib/x86_64-linux-gnu/.
```

By replacing all occurances of `x86_64-linux-gnu` in the Dockerfile with `$(gcc -dumpmachine)` I could make it build. The generated image seems to be working.

```diff
--- a/Dockerfile
+++ b/Dockerfile
@@ -37,7 +37,7 @@ RUN apt-get update -y && \
                                                apt-get clean && \
                                                rm -rf /var/lib/apt/lists/*
 # LDAP install
-RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && docker-php-ext-install ldap
+RUN docker-php-ext-configure ldap --with-libdir=lib/$(gcc -dumpmachine)/ && docker-php-ext-install ldap
 
 # Install latest curl
 RUN cd /tmp && \
@@ -107,7 +107,7 @@ WORKDIR $FIREFLY_PATH
 ADD . $FIREFLY_PATH
 
 # Fix the link to curl:
-RUN rm -rf /usr/local/lib/libcurl.so.4 && ln -s /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0 /usr/local/lib/libcurl.so.4
+RUN rm -rf /usr/local/lib/libcurl.so.4 && ln -s /usr/lib/$(gcc -dumpmachine)/libcurl.so.4.4.0 /usr/local/lib/libcurl.so.4
 
 # Run composer
 RUN composer install --prefer-dist --no-dev --no-scripts --no-suggest
```

I would also recommend merging consecutive ENV and RUN statements as this is considered [best practice](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/), as well as using a multi-stage Dockerfile in order to reduce the image size. But this is more or less cosmetic.

It would be really nice, however, if you could find a way to add the database initialization/migration to the entrypoint script.

Best regards!

**Comment by JC5** [comment]
ARM has been here for a while now.
