### ISSUE TITLE
Updating Bills via API

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#1890]
**Bug description**
I am running Firefly III version 4.7.8

I am unable to update bills via the API. 

```
curl -X PUT \
  'https://demo.firefly-iii.org/api/v1/bills/1?name=Rent&currency_code=EUR&amount_min=795&amount_max=855&date=2015-01-01&repeat_freq=monthly&skip=0&automatch=true&active=true' \
  -H 'Accept: application/json' \
  -H 'Authorization: Bearer  xxxx' \
  -H 'Content-Type: application/vnd.api+json'
```
When the above command was ran an error occurred.
```
{
    "message": "The given data was invalid.",
    "errors": {
        "automatch": [
            "The automatch field must be true or false."
        ],
        "active": [
            "The active field must be true or false."
        ]
    }
}
```

The error messages says to use boolean for automatch and active field. The docs says to use int `0` or `1` for those 2 fields though. So alright, I used an integer. 

```
curl -X PUT \
  'https://demo.firefly-iii.org/api/v1/bills/1?name=Rent&currency_code=EUR&amount_min=795&amount_max=855&date=2015-01-01&repeat_freq=monthly&skip=0&automatch=1&active=0' \
  -H 'Accept: application/json' \
  -H 'Authorization: Bearer xxx' \
  -H 'Content-Type: application/vnd.api+json' 
 ```

Error is still thrown
```
{
    "message": "Internal Firefly III Exception. See log files.",
    "exception": "Illuminate\\Database\\QueryException"
}
```

Here is the log
[bill-error-log.txt](https://github.com/firefly-iii/firefly-iii/files/2636531/bill-error-log.txt)

**Comment by JC5** [comment]
Strange, it fails on the currency. Thanks for letting me know, I'll check it out. 

I'm rewriting the API for the next release and I'll tag you in the issue I'm going to open about it.

**Comment by emansih** [comment]
I think there is a bug in the updating logic. I tried to update Accounts data and failed too.

```
curl -X PUT \
  'https://demo.firefly-iii.org/api/v1/accounts/4?name=Adobe&currency_code=USD&active=1&include_net_worth=1' \
  -H 'Accept: application/json' \
  -H 'Authorization: Bearer xxx' \
  -H 'Content-Type: application/vnd.api+json'
```

```
{
    "message": "The given data was invalid.",
    "errors": {
        "name": [
            "This account name is already in use."
        ]
    }
}
```

**Comment by JC5** [comment]
Thanks. Means my test is broken too. I'll check it out.

**Comment by JC5** [comment]
Found and fixed. I've updated the demo site. I can't verify because my Postman installation is acting up.

**Comment by emansih** [comment]
Thanks James, it is working as expected now
