### ISSUE TITLE
no connection to login screen after updating Docker compose

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#1892]
I am running Firefly III version 4.7.8

After getting the message that an update was available for the mac os version of the Docker Desktop CE version I did the update and the following was updated
Upgrades
  - [Docker compose 1.23.2](https://github.com/docker/compose/releases/tag/1.23.2)

After docker was restarted I fired up the kitematic app in order to get the 2 containers restarted. That went ok, but when i want to go to localhost:8081/login I get a problem loading page 
The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Nightly is permitted to access the Web.

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Run `docker container ls -a` on the command line to see if they're actually running.

**Comment by JC5** [comment]
Mmm, so they are running. But unreachable 🤔 . Try something basic: a system reboot?

**Comment by bartmaniac** [comment]
sadly, it did not help, still getting a "problem loading page. After the reboot I use kitematic to start the 2 containers. Does it matter which one I start first? I can choose between start or restart.

**Comment by bartmaniac** [comment]
I found that sunproxyadmin is started when one of the 2 containers (not the postgres one) is started.
For some reason I just got acces again to the firefly login page and were able to login.

**Comment by JC5** [comment]
I have to admit I never heard of sunproxyadmin. I don't think it's part of my build.
