### ISSUE TITLE
Piggy bank amount not updated from recurring transaction.

### ISSUE THREAD

**Issue by evolsano** [firefly-iii/firefly-iii#1893]
I am running Firefly III version 4.7.8

**Description**

I created few recurring transaction to save money into piggy banks monthly. But the amount in piggy bank not updated despite the transfer transaction created.

**Steps to reproduce** 

1.) Create "Travel" piggy bank.
2.) Create recurring transaction, transfer from Bank A to Bank B, and select piggy bank "Travel". No target date and Category were set.
3.) Transfer transaction created on the selected date when browse to Transactions > Transfers.
4.) Amount not updated when browse to piggy bank, and empty record in Piggy Banks > Transactions.

**Extra info**

Using the docker version of Firefly III.

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for letting me know, I'll fix it.

**Comment by JC5** [comment]
I've pushed a fix that will be included in the next release.

**Comment by evolsano** [comment]
I updated to latest version, but still the same.
