### ISSUE TITLE
Unable to edit transactions & accounts

### ISSUE THREAD

**Issue by colinerd** [firefly-iii/firefly-iii#1894]
**Bug description**
I am running Firefly III version 4.7.9 - dev

When opening a transaction or account and trying to edit it, you will get a "Be right back" page.
The URL it is going to is: http://mydomain/transactions/edit/1066
URL for account: http://mydomain/accounts/edit/7

**Steps to reproduce**
Open a transaction imported via Bunq.  Under Transaction information, click Edit.
"Be right back" message appears.

Open an asset account.  click Edit on the account you want to edit.
"Be right back" message appears.

**Expected behavior**
The screen to be able to edit my transaction / account.

**Extra info**
Firefly iii running in Docker on version 4.7.9 developer, using Firefox.
Debug information generated at 2018-12-03 11:36:47 Europe/Amsterdam for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.12 |
| Display errors | Off |
| Session start | 2017-08-03 00:00:00 |
| Session end | 2018-12-03 00:00:00 |
| Session first | 2017-08-03 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, ldap, pdo_mysql, pdo_pgsql, sodium, tidy, zip |

![afbeelding](https://user-images.githubusercontent.com/15741333/49368754-d53d9680-f6ef-11e8-8cfb-39b021fa8fbc.png)

**Comment by colinerd** [comment]
Updating the issue - I have the same when trying to edit an asset account.
URL: http://mydomain/accounts/edit/7

**Comment by JC5** [comment]
It could be a cache issue. "Be right back" is the general error message you get for everything. Since you're using docker, I suggest restarting your instance with [debug mode enabled](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) and check the page again.

**Comment by JC5** [comment]
Ah. I just noticed you're running dev. Make sure you run the latest migrations.

docker exec -it <container> php artisan migrate --seed
docker exec -it <container> php artisan firefly:upgrade-database
docker exec -it <container> php artisan firefly:verify
docker exec -it <container> php artisan passport:install
docker exec -it <container> php artisan cache:clear

**Comment by colinerd** [comment]
That has done the trick, thanks!
