### ISSUE TITLE
Income double counting in tag report with multiple selected tags

### ISSUE THREAD

**Issue by aHxShUM** [firefly-iii/firefly-iii#1898]
**Bug description**
I am running Firefly III version 4.7.8

**Steps to reproduce**
1. Create an income with multiple tags, says `tag1` & `tag2`
2. Open tag report and select `tag1` `tag2`

**Expected behavior**
Income shows exact amount of income.

**Actual behavior**
Income is double counted.

**Extra info**
- income https://demo.firefly-iii.org/transactions/show/713
- report https://demo.firefly-iii.org/reports/tag/34,1,32,33,2,3/5,6/20181201/20181231

**Comment by JC5** [comment]
Thanks. I thought that one was fixed already. It’s on the list :)

**Comment by aHxShUM** [comment]
Thanks :)

**Comment by JC5** [comment]
Let's leave this open so I don't forget it.
