### ISSUE TITLE
target bills from specific account

### ISSUE THREAD

**Issue by johnnymorris** [firefly-iii/firefly-iii#1899]
I am running Firefly III version 4.7.8

I've just gotten around to setup Firefly (Brilliant App btw very well done!) and there are a few things I'm either missing or maybe could be feature requests?

A bit of background
I have 4 accounts
 - "Automated Account" - Where my money comes into
 - "Spending Account" - My money
 - "Personal Bill Account" - Personal Bills (Such as Mobile Phone).
 - "Joint Bill Account" - Where all the payments are half (Such as Mortgage, Utility Bills etc).

My Income goes into my "Automated Account" and I have standing orders to transfer the correct money to each account (say 200 to the Personal Bill Account, 1,000 to the Joint Bill Account).

I have created my Bills and the total looks correct across both accounts, However I was wondering:
1) Is it possible to either "target" the bill onto a specific account. (For Instance, "target" the mortgage, Utility bills to the joint account. Mobile Phone to my personal bill account. and at the bottom of the bill screen have a summary of these accounts for instance:

Expected Total (Personal Bill Account) - 200
Expected Total (Personal Joint Account) - 1,000

This will allow you to see the expected amount out of each account and if there is enough money in each account.

I also looked into applying either a Category, Tag to show which account the payment will be taken from so I could filter on but then this will show all the amounts with that tag/category.

What is the recommendation for this situation or how do other users deal with this?

Edit: The only other way I may be able to achieve this: have 2 logins. 1 For the "Joint Account" and 1 for my other accounts. Then "sink" my joint payment into a joint expense, and my transfer as a income to the joint. - Would this be the best way?

Thanks

Johnny

**Comment by JC5** [comment]
Thanks for the compliments, they're always appreciated!

What you want is not not possible, unfortunately. Firefly III focuses on the entirety of your financial situation (bills included) and won't split between your own accounts.

It seems such a list wouldn't tell you anything you didn't already know. Do you often overdraw on your personal bill account? If so, I don't expect that Firefly III is the one who notices :wink:
