### ISSUE TITLE
Collapsed Pre-set ranges in Reports page

### ISSUE THREAD

**Issue by Bubka** [firefly-iii/firefly-iii#1900]
Hi,

**Description**
When firefly manage data over a large period (from 2006 in my case), the pre-set ranges consumes lots of space in the page. It requires to scroll ans scroll again, especially when your are not confortable with the report feature and you try to find the one that will best fit your current need and provide adequat extra options.

**Solution**
My suggestion: keep last 2 (or 3) years visible (as is) and collapse all others ranges behind a `show more` link or button that will expand the full list.

**What are alternatives?**
* A user setting to define how many years are available in the reports feature
* In the Reports page: Two lists of radio buttons (in place of pre-set ranges list) : one for Months, one for Years. Check a year, or a year and a month, to set the range. It costs one or two click more compare to the current list but it consumes less space by far.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19974298
