### ISSUE TITLE
Redirect after cloning transaction

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#1901]
**Bug description**
I am running Firefly III version 4.7.8 and reproduced that on demo site just now using 4.7.9

When I clone transaction I always stay on "Add new xxx" page.

**Steps to reproduce**
1. Open transaction - https://demo.firefly-iii.org/transactions/show/714
2. Options > Clome this withdrawal
3. Be redirected to - https://demo.firefly-iii.org/transactions/create/withdrawal
4. Change date/amount/etc
5. Make sure that checkbox "After storing, return here to create another one. " is unchecked.
6. Store new withdrawal
7. New transaction is created, but we are redirected back to https://demo.firefly-iii.org/transactions/create/withdrawal

**Expected behavior**
Not sure what exactly shoud happen, but one of:
1. Redirect to previous page (cloned transaction details, transaction list, wherever there are buttons allowing to clone)
2. Redirect to newly created transaction
3. Always redirect to cloned transaction details.
4. Redirect to dashboard
...

And I think there should be this green box with message saying that transaction was created and link to it?

**Comment by JC5** [comment]
This will be fixed in the next release.
