### ISSUE TITLE
Import between assets

### ISSUE THREAD

**Issue by filoor** [firefly-iii/firefly-iii#1902]
Hi,

I need help i have multiple assets some on Rabobank and also on Bunq.
For "Rabobank" i use "Spectre" looks aal oki 
For Bunq i Use .CSV import what happen is it counts the transaction between Rabobank and BUNQ 2

so let say my Current balance on 1 Raboobank asset = 10 
when i import the bunq transactions it changes the Rabobank balance to -2000

What i think happens
is it counts the transactions from "Rabobank to BUNQ" that i import  for bunq twice.
1. the import from spectre 
2. import for bunq

**Comment by filoor** [comment]
Hi,

Rabo says "b83kefxq 0140000191149524 Storting naar je bunq account. x8639 pasnr.039"
and the bunq import says "Topup account NL74BUNQ203221****F***" (* are last numbers of my account and my last name)

Do you have a easy fix for it?
Will i face the same problem for when the bunq import works again?

**Comment by JC5** [comment]
Sorry, there is no solution forthcoming. The easy fix is to import manually, ie. by entering the transactions by hand. Especially for complex import routines it is impossible to catch all the exceptions.
