### ISSUE TITLE
cannot add an IBAN to account if another one with IBAN already exists

### ISSUE THREAD

**Issue by WolfgangAndreas** [firefly-iii/firefly-iii#1904]
Hi,
when there is already an account with an IBAN assigned to it, then it's not possible to add a IBAN to another account.

FFIII will say, that there's already an account with this number, altough this is a different number.

Could you please verify and fix ? :-)
Thank you!

**Comment by WolfgangAndreas** [comment]
Sure, i will try, please see my screenshots :-)
Could it be, that if the IBAN has been used in any transaction will block assigning an IBAN to an account?

![4](https://user-images.githubusercontent.com/5389375/49686173-fa1b7a80-faf0-11e8-9b30-c65c19e10fd8.png)

**Comment by JC5** [comment]
Is the IBAN already used in any other type of account, such as your revenue accounts? Because yes, then it will be blocked.

**Comment by WolfgangAndreas** [comment]
Hi JC5, that's it! Didn't know, that FFIII automatically extracts the IBAN and adds them to the revenue accounts :-) After removing the IBAN it works for me now :-)

Many thanks for your help, you did a great job with this excellent tool :-)

Kind regards,
Wolfgang
