### ISSUE TITLE
Cannot reimport deleted transaction

### ISSUE THREAD

**Issue by ms32035** [firefly-iii/firefly-iii#1905]
**Bug description**
I am running Firefly III version 4.7.8

After deleting transaction cannot import it again

**Steps to reproduce**
1. Import transaction from CSV
2. Delete it
3. Try importing again

**Expected behavior**
Successful import

**Extra info**

**Bonus points**
Earn bonus points by:

firefly-app_1  | [2018-12-08 15:04:48] production.INFO: Transaction is a duplicate, and will not be imported (the hash exists). {"existing":4587,"description":"xxx","amount":"0","date":"2018-10-03"}

**Comment by ms32035** [comment]
A side question. Is it safe if I delete rows in `transactions` and `transaction_journal` where `deleted_at` is null?

**Comment by JC5** [comment]
This is by design. If you want to reimport those transactions, delete the rows from `transaction_journals` where `deleted_at` is NOT null.

This should also delete the associated entries from `transactions` and `journal_meta` and will allow you to reimport the CSV again.

**Comment by ms32035** [comment]
Thanks for the explanation

**Comment by AndrewSav** [comment]
Hello, if I accidently removed a bunch of transactions and cannot reimport it, is there a way for me to "fix" this? There is no obvious way from the UI to find `transaction_journals`, so I suspect this is about some interal workings of the app. How can I quickly fix it, without the need to figure out how to work the internals? For example is there a script that I can run from command line that fixes this for me, or any other easy way?

**Comment by JC5** [comment]
You can’t. You’ll have to access the database.

**Comment by AndrewSav** [comment]
@JC5 may be worth adding a UI options to aleviate this pain, if you would consider this.

**Comment by JC5** [comment]
No, sorry. This happens very rarely and most people are capable of opening the database.

**Comment by AndrewSav** [comment]
I'm not sure if this is the case, it happened at least twice according this thread and who knows to how many people who did not report. Also in my experience it's seems that _most_ people I know are not capable of opening the database. But let's put this aside.

To me it seems that deleting of these are a very easy thing to do unintentionally, and re-importing them should just work, this is what I think most people would expect. If you do not want re-imported transactions to be there, at least you can delete them again via UI without need to do resort to database editing.

I was wondering if you could explain what is the rationale behind this design, it's not immediately obvious?

**Comment by JC5** [comment]
It's a self-hosted application. I expect some proficiency with computers. If that's not the case, use Mint. I have no desire nor an obligation to be a basic computer support desk.

Deleting is not an easy thing to do unintentionally. There is at least one warning screen. Plus, everything is retained in the database if you want to undo stuff. 

But to explain the rationale: some banks use dummy transactions to report on your current balance. Some banks record transactions twice (when using foreign currencies for example). Once a file is imported, it might be necessary to delete these transactions. To prevent them from appearing again when importing a new file (or a new file with transaction-overlap) these will not be imported again, even when they have the deleted status.
