### ISSUE TITLE
date ranges in transactions overview

### ISSUE THREAD

**Issue by 3ssen** [firefly-iii/firefly-iii#1909]
**Bug description**
I am running Firefly III version 4.7.8

At this time i've added only one transaction. When I look at the transactions overview screen the correct corresponding date isn't showed when clicking on the year 2010.

**Steps to reproduce**
New database with no transactions. Add one transaction with date 2010-11-11 (YYYY-MM-DD). When clicking on the overview page on the standard range 2010 the date range is filled with 2011-01-20 - 2011-01-20. 

**Expected behavior**
Date range field should have 2010-11-11 - 2010-11-11.

As the standard ranges are starting from 2010 and november and december. They are right. Only the corresponding date range is incorrect. See screenshot.
![image](https://user-images.githubusercontent.com/2758036/49876981-bee8b680-fe24-11e8-88fb-a383ee17ab05.png)

**Comment by JC5** [comment]
Nice find. I know the cause and I can fix it. Thanks for reporting it!

**Comment by JC5** [comment]
This will be fixed in the next release. Keep in mind that the start date can never be before the date of the first transaction, so the box will change to a date before "2010-11-11".

**Comment by 3ssen** [comment]
thanks
