### ISSUE TITLE
New Transaction Display Budget left

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#1910]
**Description**
Please describe your feature request:

- I would like the dropdown for budget items to display amount left in the budget for that time period.

**Solution**
When showing the budget dropdown a number next to it should show the amount left for each budget item

**What are alternatives?**
Have to open the budget window in a separate tab to know how much is left in each budget

**Additional context**
Shouldn't matter if a budget item is negative, user would just have to increase it eventually or take out of other budget categories

**Comment by JC5** [comment]
Yes, that's a good idea, thanks for your suggestion!

I believe it is similar to this one: https://github.com/firefly-iii/firefly-iii/issues/1110 so I'm closing this issue. It is on the list of things to build 👍

**Comment by lastlink** [comment]
Ok, I looked through them and wasn't able to easily find it. Thanks
