### ISSUE TITLE
N26 importer

### ISSUE THREAD

**Issue by jcgruenhage** [firefly-iii/firefly-iii#1911]
**Description**
It would be nice if Firefly III could import transactions from N26. They don't support HBCI, and I don't want to use a third party provider like Spectre for it.

**Solution**
Add an importer that uses N26's API for importing

**What are alternatives?**
Using Spectre or switching to a different bank

**Additional context**
There is an unofficial API documentation here: https://github.com/Rots/n26-api

**Comment by JC5** [comment]
It’s on the list. Mind you I won’t implement beta apis or anything like that.

**Comment by GeoffreyFrogeye** [comment]
Just FYI I did a script to import N26 transactions to Firefly via the API. It's Python so it's not going to be simple to implement a Firefly importer (if it requires PHP) but I can be of some help if anyones wants it. 
Specifically one of the problem that needs to be adressed is that the N26 API re-generates new ID for their transactions after a few days resulting in dupplicates if not properly handled (if there is a way to properly handle them...).

**Comment by jcgruenhage** [comment]
Where can I find that script? Having a one time import of everything and doing new things manually would be perfectly fine for me.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
