### ISSUE TITLE
lighttpd support

### ISSUE THREAD

**Issue by DarkWingMcQuack** [firefly-iii/firefly-iii#1913]
I am running Firefly III version 4.7.8

Hi I am currently trying to setup firefly-iii using lighttpd. Is there any documentation or hints how to do this? I get redirected from firefly.my-domain to firefly.my-domain/login, where i get a 404 error.
This is because lighttpd does not support `.htaccess` files. The rewrite rules of the `.htaccess` would need to be rewritten for lighttpd. If someone could provide this, I would be more than happy, because I am not familiar with how to do that.

**Comment by JC5** [comment]
I'm sorry, I never worked with lighttpd myself. I can't find any hints on Github or on reddit.
