### ISSUE TITLE
Bills totals doesn't handle multi-currencies

### ISSUE THREAD

**Issue by niceboss** [firefly-iii/firefly-iii#1915]
**Bug description**
I am running Firefly III version 4.7.9

When using multi-currency in bills, incorrect numbers in Totals. They must be converted to default currency before summing.

Please look at https://demo.firefly-iii.org/bills

![chrome_2018-12-20_20-52-03](https://user-images.githubusercontent.com/37800097/50304631-2512b080-0499-11e9-9601-43869824eaad.png)

**Comment by JC5** [comment]
Thanks for reporting this. Do you mean you want Firefly III to convert the amount?

**Comment by niceboss** [comment]
I've added also bill with 100 XBT (bitcoins)
https://demo.firefly-iii.org/bills

Please have a look at Dashboard, there's Bills to Pay: 200 EUR, but (there 100 XBT and 100 USD), better if possible to convert them before summation ?

Thanks.

**Comment by JC5** [comment]
I see what you mean. I can't fix that without a reliable conversion service. I'll put it on the list but please don't expect anything anytime soon.

**Comment by niceboss** [comment]
Please have a look:

European Central Bank XML Feed
https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

Maybe for cryptocurrencies https://coinmarketcap.com/api/

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1818
