### ISSUE TITLE
Sandstorm.io app market version is out of date

### ISSUE THREAD

**Issue by jonpavelich** [firefly-iii/firefly-iii#1917]
I am running Firefly III version 4.7.7.

**Description**
The latest version of Firefly III is 4.7.8, but the latest version on the [Sandstorm app market](https://apps.sandstorm.io/app/uws252ya9mep4t77tevn85333xzsgrpgth8q4y1rhknn1hammw70) is 4.7.7. I'm not sure how the Sandstorm marketplace checks for updates, but there are a couple fixes that were released in 4.7.8 that would be great to have.

**Comment by JC5** [comment]
I completely forgot to push the last release. I’ll pick it up with 4.7.9 again, is that OK?

**Comment by jonpavelich** [comment]
Of course, thanks! I wasn't sure if you had to manually push releases or whether Sandstorm.io would pick them up automatically from Github. Do you have a planned release date for 4.7.9?

**Comment by bartmaniac** [comment]
Starting October 14, 2018, the Free plan will no longer allow creating grains, only accessing grains shared by others. Pre-existing data will remain available for download.

Machine translation of your reply I found on the Tweakers forum 'Did not know that was going to happen.  This means the end of Sandstorm as a meaningful free place to install Firefly III.  You'll have to upgrade to the paid variant.

**Comment by jonpavelich** [comment]
I'm a little confused by your comment @bartmaniac

My issue refers to the Sandstorm App Market, which is used by all Sandstorm installations, including Oasis and self-hosted installs.

Sandstorm Oasis (which is just a Sandstorm install they're hosting for their users) is indeed discontinuing its free plans,  because its paid users were not generating enough revenue to cover server costs (see [their blog post](https://sandstorm.io/news/2018-10-28-results-of-ending-free-plan)). You can still host Sandstorm yourself, which is what I'm doing (and I'm inclined to believe most of the Firefly users who use Sandstorm probably are as well). The announcement you're referring to simply means sandstorm.io will no longer provide free hosting - you can pay for their hosting, or host it yourself.

**Comment by JC5** [comment]
The new release of Firefly III is out. I have expedited the push to the Sandstorm market for your convenience, but be aware that there may be bugs. I often wait a few days in case of trouble.

Like I said, I have submitted the new release to the Sandstorm market but it could be a few days (because of the holidays) before it is approved.

**Comment by jonpavelich** [comment]
Awesome, thank you @JC5! I'll close this and if anything new comes up I'll open a new issue. Looking forward to getting the update.
