### ISSUE TITLE
Split Withdrawal: Negative items (discounts/bonifications)  sum instead of subtract

### ISSUE THREAD

**Issue by victordariovera** [firefly-iii/firefly-iii#1918]
Hi!

When I try to create a withdrawal, a splited one, sometimes I need to include discounts or bonifications. For example, supermarket discounts or other bonifications. Then I try to use negative values in split items labelling them as "discount" ... but I see that firefly sum instead of subtract them. I add a video with that in this link: https://youtu.be/iyRCwdanPYg

**Comment by JC5** [comment]
Thanks for the video, and thanks for opening this issue.

You cannot add these discounts to a split withdrawal. This is intentional.
