### ISSUE TITLE
still on 4.7.8

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#1919]
I am running Firefly III version 4.7.8
**Description**
I learned the new 4.7.9 was out but after running the upgrade steps I restarted ff-iii and found i'm still with the 4.7.8 version

The steps I took:
1 stop the 2 running docker containers (maybe this is the wrong step?)
2 open a terminal and execute following command
docker-compose pull firefly_iii_app && docker-compose restart firefly_iii_app

followed by

docker-compose exec firefly_iii_app php artisan migrate --seed
docker-compose exec firefly_iii_app php artisan firefly:upgrade-database
docker-compose exec firefly_iii_app php artisan firefly:verify
docker-compose exec firefly_iii_app php artisan passport:install
docker-compose exec firefly_iii_app php artisan cache:clear

there were error messages. I started the postgres container (the other one (firefly-iii) was already automaticaly restarted) and entered the 5 docker-compose exec firefly_iii_app php artisan commands again.

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
I have just updated the commands you need. I was able to upgrade, but make sure you have backups just in case.

```
docker-compose stop firefly_iii_app
docker-compose rm
docker-compose pull firefly_iii_app
docker-compose -f docker-compose.yml up -d
```

**Comment by avkizub** [comment]
Hi!
Try `docker-compose pull firefly_iii_app; docker-compose down && docker-compose up -d` in step 2.

**Comment by bartmaniac** [comment]
I have unfortunatly no idea how to backup the docker volume /var/lib/postgresql/data. I hoped I was able to do that using kitematic, but all I see is change and remove
![schermafbeelding 2018-12-24 om 11 55 27](https://user-images.githubusercontent.com/44246750/50397786-f0da1100-0772-11e9-8419-54af14e6a513.png)

I googled for docker volumes backup and gets lots of results but many of them coming from forums or stackoverflow.

**Comment by bartmaniac** [comment]
some more information

docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
533ca97f923f f0cdf32e1e5f ".deploy/docker/entr…" 7 weeks ago Up 12 hours 0.0.0.0:8081->80/tcp documents_firefly_iii_app_1
6b9f10219e7f postgres:latest "docker-entrypoint.s…" 7 weeks ago Up 13 hours 5432/tcp documents_firefly_iii_db_1

a docker volume inspect documents_firefly_iii_db command 
[
{
"CreatedAt": "2018-12-23T23:41:32Z",
"Driver": "local",
"Labels": {
"com.docker.compose.project": "documents",
"com.docker.compose.version": "1.22.0",
"com.docker.compose.volume": "firefly_iii_db"
},
"Mountpoint": "/var/lib/docker/volumes/documents_firefly_iii_db/_data",
"Name": "documents_firefly_iii_db",
"Options": null,
"Scope": "local"

**Comment by bartmaniac** [comment]
I'm a (little) bit scared of the docker-compose rm command, Removes stopped service containers.
what if every docker container is removed also the one with my database

**Comment by JC5** [comment]
Glad to hear it! :+1:
