### ISSUE TITLE
Unable to authorize Oauth on android app

### ISSUE THREAD

**Issue by mconway** [firefly-iii/firefly-iii#1920]
I am running Firefly III version 4.7.7, 4.7.9

I've noticed that I can't actually authorize an android app login. It's been a bit since I've worked on the app. But it looks like it's because of the Content-Security-Policy header being sent by FireFly when on the "Authorize" screen.

This shows up in the console: `Refused to send form data to 'http://localhost/' because it violates the following Content Security Policy directive: "form-action 'self'".`

I'm not sure this is a bug, it works fine with the windows 10 client, but I've tried on several android devices with the same result now. I'm probably missing something obvious.

**Extra info**
Here are the headers I'm seeing from FireFly: `Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-eval' 'unsafe-inline' ; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; font-src 'self'; connect-src 'self'; img-src 'self' data: https://api.tiles.mapbox.com`

**Comment by mconway** [comment]
Commenting out Line 57 of firefly-iii/app/Http/Middleware/SecureHeaders.php (`"form-action 'self'",`) allowed me to finish the authentication. You can remove the comment once the authentication is complete. I'm sure there's a better solution to this, but I'm posting the workaround for now in case someone else gets stuck.

**Comment by emansih** [comment]
I am able to complete OAuth via Chromium and Firefox based browsers though. What is not working for you?

**Comment by JC5** [comment]
Any Android app in particular?

**Comment by mconway** [comment]
I'm noticing it with the App I've been building. I doubt it's a bug with Firefly itself, just trying to figure out how to make this work.

I'm able to replicate this over and over in google chrome, but not in Edge or Firefox.

Here is the test URL I'm using: https://demo.firefly-iii.org/oauth/authorize?client_id=4&redirect_uri=http%3A%2F%2Flocalhost%2Fcallback&response_type=code&scope=&state=

![image](https://user-images.githubusercontent.com/411506/50396003-eb051100-071b-11e9-96a8-ea87fced4545.png)

**Comment by JC5** [comment]
I can replicate the error when I login using Chrome. I see that the login works. You're being redirected to the /oauth/authorize URL but then it breaks. Not sure yet why Chrome thinks this should be done.

**Comment by mconway** [comment]
I'm guessing it's how Chrome is handling the header. Since the app I've built uses the InAppBrowser (based on Chrome), it fails as well. @emansih are you using the InAppBrowser on your app as well?

**Comment by emansih** [comment]
@mconway no, use I'm using Android's intent to open user's defined browser.

**Comment by mconway** [comment]
@emansih for the callback then, do you use a custom URL Scheme? how does the browser pass the token back to the app?

**Comment by emansih** [comment]
This is strange. 

 ```
https://demo.firefly-iii.org/oauth/authorize?client_id=1&redirect_uri=http://empty&response_type=code&scope=&state=
```
It works whereas

```
https://demo.firefly-iii.org/oauth/authorize?client_id=4&redirect_uri=https://localhost/callback&response_type=code&scope=&state=
```
doesn't work. Could be the extra path in the redirect uri be causing issues?

**Comment by emansih** [comment]
@mconway I'm not so sure about Ionic framework. This is what I did for mine. 

Register a callback for your [redirect URI](https://github.com/emansih/FireflyMobile/blob/a5e8996f3a794027b4401c86eea75cc083316458/app/src/main/AndroidManifest.xml#L31-L38) in your manifest.

Your app will sit in the background listening and intercepting your callback URI (https://localhost/callback). This is all handled by Android itself. Chrome handles it nicely, as for Firefox, you will need an extra step.(https://github.com/emansih/FireflyMobile/issues/15#issuecomment-448617997)

**Comment by emansih** [comment]
https://github.com/emansih/FireflyMobile/releases

**Comment by emansih** [comment]
@mconway no issues for me. https://www.youtube.com/watch?v=8bMweuhJB-8&feature=youtu.be
