### ISSUE TITLE
Can't import csv file from Kbc (belgium)

### ISSUE THREAD

**Issue by roeleboel** [firefly-iii/firefly-iii#1922]
**Bug description**
I am running Firefly III version 4.7.9

(please give a clear and concise description of what the bug is)
I cannot import a csv-file from 'kbc' bank (belgium)

**Steps to reproduce**
What do you need to do to trigger this bug?
Try to import a csv-file from kbc-bank, you will get till step 3, where only the first column is useable for import.

**Expected behavior**
What do you expect to see after those steps?
More recognised columns to map

Attached is an anonimised csv-file (renamed to .txt so I could add it here), length is header line and 1 transaction.
[kbc_csv_export.csv.txt](https://github.com/firefly-iii/firefly-iii/files/2707282/kbc_csv_export.csv.txt)

**Comment by JC5** [comment]
Did you read the manual and select the semi-colon or “puntkomma” when configuring the import?

**Comment by roeleboel** [comment]
> Did you read the manual and select the semi-colon or “puntkomma” when configuring the import?

obviously, but that doesn't work. 
Have you tried an import with the attached file?

**Comment by JC5** [comment]
No. I have to cover the basics first. You’d be surprised.

**Comment by JC5** [comment]
Bingo. The file is not UTF8. Use Notepad++ or a similar to to save the file as UTF8. Once that has been done, it should work perfectly.

![screenshot 2018-12-24 at 13 49 43](https://user-images.githubusercontent.com/5889984/50399868-da3bb600-0782-11e9-8fc5-1bb4422ed047.png)

**Comment by roeleboel** [comment]
For additional info: my workflow:
- on ubuntu 18.04/firefox I go to the site of kbc
- I download the csv-file and save it to a samba-share
- on windows 10 I open this file in notepad++, and select 'encoding - convert to utf-8'
- I save this 'new' file to the desktop
- I open in edge the firefly-site
- I try to import the csv-file above (with 'semicolumn' as separator)
- screenshot above happens :(

**Comment by bartmaniac** [comment]
can you choose to download the .xls or .xlsx file from KBC, open it in MS Excel and then choose "save as" (opslaan als) and pick .csv as "bestandsindeling" ?

**Comment by roeleboel** [comment]
I can only download csv or pdf.
However, you did give me an idea:
I opened the file in openoffice calc, saved it again as csv, imported it to win10, converted to utf8, and behold... now it works...
So something in the original csv does not add up.
Anyhow, I got a functional workaround :) Thanks!

**Comment by bartmaniac** [comment]
could it maybe have something to do with the cell properties of the 'datum kolom" ?

**Comment by T-Grave** [comment]
@roeleboel did you manage to fix this? I'm getting the exact same issue.

**Comment by roeleboel** [comment]
This worked for me:
https://github.com/firefly-iii/firefly-iii/issues/1922#issuecomment-449738346

So:
- open csv in openoffice calc
- save as csv
- convert the new file to utf-8 (notepad++)
- import that file, that should work

Roel
