### ISSUE TITLE
window position

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#1923]
**Bug description**
I am running Firefly III version 4.7.9

postition of this item under "Overzichten"

![schermafbeelding 2018-12-24 om 14 35 08](https://user-images.githubusercontent.com/44246750/50400825-19213a00-078a-11e9-812b-bef405e3686f.png)

it looks like it is positioned a little bit to high (can't read the names of the days) Maybe it is made intentionnly this way?

**Steps to reproduce**
What do you need to do to trigger this bug?

**Expected behavior**
What do you expect to see after those steps?

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

**Bonus points**
Earn bonus points by:

- Post a stacktrace from your log files
- Add a screenshot

**Comment by bartmaniac** [comment]
it looks like this is also happening on other places. was correct with 4.7.8
 
![schermafbeelding 2018-12-24 om 15 48 38](https://user-images.githubusercontent.com/44246750/50402045-9b622c00-0793-11e9-9f18-7b74bb456657.png)

**Comment by JC5** [comment]
Which OS/browser are you using? Your fonts are off in the second screenshot.

**Comment by bartmaniac** [comment]
the same browser that I was using under 4.7.8 (although the browser gets updated daily (firefox nightly builds) but I get same results under firefox quantum 65.0b6 and vivaldi browser.

Also strange is that when choosing 'Vandaag" it returns the date range 1 Juli 2018 - 31-12-2018

**Comment by JC5** [comment]
Sorry, those are not the details I tend to remember :wink:. Any issues in your console? Could you clear your cache just in case?

**Comment by bartmaniac** [comment]
ok (how do I clear the cache? (id also happening in Safari

**Comment by bartmaniac** [comment]
> Which OS/browser are you using? Your fonts are off in the second screenshot.

these are the font settings (which haven"t changed)

![schermafbeelding 2018-12-25 om 03 00 25](https://user-images.githubusercontent.com/44246750/50409276-c3807800-07f1-11e9-8e11-8122a1e2af2a.png)

**Comment by bartmaniac** [comment]
> I haven’t got it in safari either. Windows or Mac?
> 
> Clearing your browser cache I mean, you should be able to find that one I think 😉

clearing the cache did not help (safari, firefox). Im running safari and firefox (quantum and nightly) on mac os high sierra

**Comment by bartmaniac** [comment]
Here you can see the difference between the demo version and mine. 
First = mine
second = demo version


![schermafbeelding 2018-12-26 om 18 10 18](https://user-images.githubusercontent.com/44246750/50452368-f6ce1e80-0939-11e9-8e96-586a81f9105d.png)

![schermafbeelding 2018-12-26 om 18 11 24](https://user-images.githubusercontent.com/44246750/50452369-fc2b6900-0939-11e9-8ad6-0518e6214ef7.png)

When I click in my version in the datumbereik field, the upper row is hidden like this

![schermafbeelding 2018-12-26 om 18 17 28](https://user-images.githubusercontent.com/44246750/50452488-99869d00-093a-11e9-9ab7-b5d67a33ebaf.png)

When I do the same with the demo version, then it is correct

![schermafbeelding 2018-12-26 om 18 19 13](https://user-images.githubusercontent.com/44246750/50452531-cfc41c80-093a-11e9-9a85-d5f287fe035a.png)

**Comment by JC5** [comment]
I see what you mean, and I can replicate the issue. Stay tuned.

**Comment by JC5** [comment]
This will be fixed in the next release.
