### ISSUE TITLE
unable to link transactions

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#1924]
I am running Firefly III version 4.7.9

**Description**
I have some expenses that are covered by incomes

(eg I bought a tv for my mum (-999) and then she paid me back (+1000)on same bankaccount

I read that you have to enter the ID but I cannot find this ID number to get it linked

I did find some transactions with an ID number but could not find this one

![schermafbeelding 2018-12-24 om 15 56 07](https://user-images.githubusercontent.com/44246750/50402203-03654200-0795-11e9-8d91-f6d273063749.png)

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
The ID is the number in the URL if you click on the transaction to view it.

Example: https://demo.firefly-iii.org/transactions/show/723
