### ISSUE TITLE
No skip parameter when editing a recurrent transaction

### ISSUE THREAD

**Issue by a1ex4** [firefly-iii/firefly-iii#1927]
**Bug description**
I am running Firefly III version 4.7.9

(please give a clear and concise description of what the bug is)

**Steps to reproduce**
Edit a recurring transaction, the "skip" input form is left empty, and not taken into account opening the prediction calendar.

**Expected behavior**
What do you expect to see after those steps?
The previously set "skip" parameter to be taken into account and filled in the form.

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

No relevent logs.

**Bonus points**
Earn bonus points by:

- Post a stacktrace from your log files
- Add a screenshot

**Comment by JC5** [comment]
Nice find, should not be a difficult fix.

**Comment by JC5** [comment]
Fixed on the demo site, will go live with the next release.
