### ISSUE TITLE
Multiple 404 errors after upgrading to 4.7.9

### ISSUE THREAD

**Issue by lgp171188** [firefly-iii/firefly-iii#1928]
I am running Firefly III version 4.7.9 using the docker images and after upgrading to 4.7.8, all the API endpoints like the following return 404 errors causing many UI pages to be empty. Some of the pages like the 'Asset accounts' pages return a 404 error.

```
"GET //json/box/balance HTTP/1.1" 404
"GET //chart/account/expense HTTP/1.1" 404
"GET //chart/account/frontpage HTTP/1.1" 404
"GET //accounts/asset HTTP/1.1" 404
```
**Extra info**
This happens on all browsers and OS. Tested on the latest Firefox, Google Chrome on macOS 10.14.x and also with Firefox, Chromium on a latest Arch Linux installation.

Debug information generated at 2018-12-26 19:03:34 Asia/Kolkata for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | production |
| App debug mode | true |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.13 |
| Display errors | Off |
| Session start | 2018-12-01 00:00:00 |
| Session end | 2018-12-31 23:59:59 |
| Session first | 2018-03-24 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, ldap, pdo_mysql, pdo_pgsql, sodium, tidy, zip |

**Comment by JC5** [comment]
Mmm. Those URL's should not 404, even with the added forward slashes. Are you running a proxy?

**Comment by lgp171188** [comment]
@JC5, yes, I have an apache2 reverse proxy running in front of the app. I have mapped the port 80 in the container to `127.0.0.1:8081` on the host and apache2 proxies to it. Is there anything I should change/fix to get this working?

**Comment by lgp171188** [comment]
**Update**: I had a stray trailing slash in my apache2 reverse proxy configuration and removing it seems to have fixed this issue.

**Comment by JC5** [comment]
Glad to hear you found it :+1:
