### ISSUE TITLE
Piggy Bank in Transaction

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#1931]
**Bug description**
I am running Firefly III version 4.7.9

When editing a transfer, I am no longer able to add a piggy bank. however when adding a new transfer, I am able to add a piggy bank.

Also the API does not return piggy bank name from transfers anymore. 

![piggy](https://user-images.githubusercontent.com/5896415/50516112-cd50f680-0ae3-11e9-96b9-e8a5c0bd9d6b.png)

**Comment by JC5** [comment]
To get piggy bank information from a transfer, use [this endpoint](https://api-docs.firefly-iii.org/#/transactions/getEventsByTransactions).

**Comment by iominfra** [comment]
A "link to transaction" field in piggy event creation page or "create from transaction" button can resolve this issue ? 
![image](https://user-images.githubusercontent.com/45977479/53680276-53064380-3cd9-11e9-93cf-8d0272df7f44.png)
