### ISSUE TITLE
Add CAMT / ISO 20022 support

### ISSUE THREAD

**Issue by kriegalex** [firefly-iii/firefly-iii#1932]
**Description**

- ~~In my language format, CSV are created with semicolons instead of commas, so it would be nice that firefly supports CSV with semicolons to avoid editing exported CSV each time~~
- My bank also allows to export data in ISO format (camt.053). I think it relates to ISO 20022 norm for payments and camt.053 describes bank to customer transactions. Since it is an ISO norm, I guess it would (or at least should) be wildly adopted by banks, so maybe Firefly could implement it also.

**Solution**
More compatibility with existing bank exporting tools.

**What are alternatives?**
~~For semicolons CSV, replace manually all semicolons with commas...~~

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
