### ISSUE TITLE
local.WARNING: No database version entry is present. Database is assumed to be OLD (version 1)

### ISSUE THREAD

**Issue by kalakrumanov** [firefly-iii/firefly-iii#1934]
I am running Firefly III version 4.7.9

**Description**

I have just done a fresh install, everything ok until I just run for the first time /website/public and got a BLANK SCREEN.

I have seen the logs and it says:

**local.WARNING: No database version entry is present. Database is assumed to be OLD (version 1)**

And I have search for info on how to solve it, but nothing appeared.

I have a Apache2 with Ubuntu 18.04 installed.

Thanks in advanced,

Kalak

**Comment by JC5** [comment]
Anything in your Apache logs?

**Comment by kalakrumanov** [comment]
Rare thing. I restarted the VPS and everything working perfect now :)

**Comment by JC5** [comment]
Glad to hear it! I will change the warning into a notice (that’s all it is). Case closed, I think! :+1:
