### ISSUE TITLE
Permission issue in container

### ISSUE THREAD

**Issue by mattsmcknight** [firefly-iii/firefly-iii#1935]
Installed the docker container today. Recurring transaction page has permission denied issue. inside the container this directory:
/var/www/firefly-iii/storage/framework/cache/data/03/8e
is owned by root:root

chown www-data:www-data fixed problem

**Comment by JC5** [comment]
Crap. I hoped I had that fixed.  Thanks for letting me know.

**Comment by JC5** [comment]
If this happens, run the following command to clear out the cache. I hope this will be fixed in the next version of Firefly III.

```
docker exec -it <container> php artisan cache:clear
```
