### ISSUE TITLE
[Import] Wrong results for "-1.000,00 €"

### ISSUE THREAD

**Issue by dun3** [firefly-iii/firefly-iii#1938]
**Bug description**
I am running Firefly III version 4.7.9

When importing a negative value in German format with thousand separator and currency symbol e.g. "-1.000,00 €" this gets converted to €-1.00.
When importing a negative value in German format and currency symbol e.g. "-950,00 €" this gets converted to €-95,000.00

**Steps to reproduce**

CSV such as:

Buchungsdatum;Wertstellung;Umsatzart;Buchungsdetails;Auftraggeber;Empfänger;Betrag (€);
28.12.2018;28.12.2018;Überweisung;Uebertrag;Efdg;Hijk;-1.000,00 €;
28.12.2018;28.12.2018;Überweisung;Uebertrag;Efdg2;Hijk2;-950,00 €;

**Expected behavior**
-1.000,00 € should be -1000.00
-950,00 € should be -950.00

Let me know if I can help - point me to the source file and I'll create a PR

**Comment by JC5** [comment]
There's no dancing around it: that's the most stupid way I've ever seen a bank format their currency. Especially since they already mentioned the € in the header. 

Which bank is that? I can fix their idiocy but I won't do it without some proper naming and shaming.

**Comment by dun3** [comment]
:-D I agree.

Shame on them: https://www.postbank.de/

If you really want to go a bit mad - this is their real "CSV" they provide (formatted in ANSI), so it is a bit of a dance before I may even start to import:

```
Umsatzauskunft;
Name;My Name;
BLZ;37010050;
Kontonummer;111111111111;
IBAN;DE9537010050111111111;
Aktueller Kontostand;11.111,11 €;
Summe der Umsätze in den nächsten 14 Tagen;1.000,00 €;

gebuchte Umsätze;
Buchungsdatum;Wertstellung;Umsatzart;Buchungsdetails;Auftraggeber;Empfänger;Betrag (€);Saldo (€);
28.12.2018;31.12.2018;Zinsen/Entgelt;;Xyz;;-111,11 €;11.111,11 €;
28.12.2018;28.12.2018;Überweisung;Uebertrag;Abc;Def;-1.000,00 €;11.111,11 €;
```

Thank you for your help!

**Comment by JC5** [comment]
No problem! I've pushed a fix and some tests so the next version of Firefly III should be able to handle these amounts. You can follow the link above my reply and see my use cases. If these are not correct, please feel free to submit a PR.

Thanks for feedback!

**Comment by dun3** [comment]
Use cases seem to match my problem perfectly. Thank you! (I am closing the issue)

**Comment by alexpercsi** [comment]
@dun3 Could you please share your Postbank import configuration file? I'm going nuts over here! I would REALLY appreciate it if you shared it!
