### ISSUE TITLE
[Feature Request] Manipulate deleted transactions (restore or clear)

### ISSUE THREAD

**Issue by dun3** [firefly-iii/firefly-iii#1940]
**Description**

I would like to manipulate deleted transactions by either restoring wrongfully deleted transactions (not a high prio) or by "really" deleting them so they can get re-imported without triggering the duplication detection.

- When an import of transactions contain faulty formatting (e.g. wrong number format) or some fields where wrongfully assigned those transactions need to get re-imported
- The problem is not there is all transactions are faulty, but if some of the 100 transactions are. Currently then you really have to only delete wrong transactions and only re-import those, which is time consuming. I would like to "clean" all transactions contained in that faulty import session, and just do it again.
- This "real" delete should clean any duplication record, so we can start with that import file from a clean slate

**Solution**

Provide a way to either

a. have a "clean" button next to the "delete" button, or
b. have a view of all deleted entries so some of them can get purged completely (such a view might be a good way to debug anyways)

**What are alternatives?**
I assume I could go into the DB myself, but I have not found documentation what to do and where to delete stuff. A bit dangerous.

Thank you!

**Comment by JC5** [comment]
Since this is a very small use case, I haven't spend time getting it fixed. To really delete transactions (and make sure you can import them again), delete the ID from the URL (/transactions/show/*123*) from the `transaction_journals` table.
