### ISSUE TITLE
Allow special character for tag searching

### ISSUE THREAD

**Issue by aHxShUM** [firefly-iii/firefly-iii#1941]
**Description**
Please describe your feature request:

- Searching with `tag:` allows only `[0-9a-z.]` while tag is free input

**Solution**
Describe what your feature would add to Firefly III.

- Allow tag searching with special character like `-_/`
- Allow wildcard searching if possible

**Comment by JC5** [comment]
The search is getting an overhaul anyway. I'll see what I can do :).

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947668
