### ISSUE TITLE
Favicon not loading: wrong path

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1942]
I am running Firefly III version 4.7.9

I get 404 errors on favicons loading due to wrong paths: the request is made to $FF3_ROOT instead of $FF3_ROOT/public.

It should be a trivial fix but I am not familiar with web applications and do not know where to look, otherwise I would fix it myself.

**Comment by JC5** [comment]
I can fix that!

Can you please make sure you're not running Firefly III from /public? That's a security risk.

**Comment by lucavallerini** [comment]
I run Firefly III under https://www.xxx.yz/firefly that directs me to https://www.xxx.yz/firefly/public. The configuration is up to Softacolous, I am quite sure I cannot install Firefly III myself on the hosting I bought.

**Comment by JC5** [comment]
I told those idiots quite a few times already not to do that. I'll see if I can't reach out to them.

**Comment by JC5** [comment]
Could you please check for me what happens when you try to visit this URL? Please change it as appropriate for your actual location:

`https://www.xxx.yz/firefly/.env`

**Comment by lucavallerini** [comment]
I get a 403 error: that correct, right?
