### ISSUE TITLE
Report suggestions

### ISSUE THREAD

**Issue by jessdaddy** [firefly-iii/firefly-iii#1943]
**Description**
Feature request for a couple of new reporting options.
Display attachment links and file names in reports.
Optionally, and better still, display attachment images in reports.

I love FF and am really enjoying using it. Previously, I used a desktop application i created in Access and  VBA. In my transaction reports, I included options to display file and path names to attachment files and in some reports even displayed actual attachment images (PDF, JPG, GIF, or TIFF) in the reports themselves (one below each line item). Now, while I realize that displaying the actual images in the Firefly reports might be a lot of work, including file names and links in the reports could be very useful for displaying receipts and the like quickly without having to drill down to individual transactions. Would also be nice if could set attachment images to open in new tabs or windows.

Hope this gets implemented at some point. Would be a nice touch I think. Any ideas or thoughts concerning this certainly are welcome.

**Comment by JC5** [comment]
I'll see what I can do but I won't add more meta data than just the icon. I like the clean look of the report. For grouped transactions there's the (i)-icon where I'll see if I can add some more data.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947339
