### ISSUE TITLE
Select All not possible with search results

### ISSUE THREAD

**Issue by sachawolf** [firefly-iii/firefly-iii#1944]
**Bug description**
I am running Firefly III version 4.7.9

**Steps to reproduce**
Search for transactions using the search page. Make sure the result is more then 1 transaction.
Use the 'Select Transactions' button. All you can do is select every transaction by hand.

**Expected behavior**
The option to select all transactions with a specific checkbox at the top of the result list.
![firefly-iii missing select all box search](https://user-images.githubusercontent.com/1969576/50547827-672eb580-0c42-11e9-9ce7-b2fb16774889.jpg)

**Comment by JC5** [comment]
Oh nice find, thanks for letting me know. I'll add the little button in the next release :)

**Comment by JC5** [comment]
Fixed!
