### ISSUE TITLE
Action menu out of bounds

### ISSUE THREAD

**Issue by sachawolf** [firefly-iii/firefly-iii#1945]
**Bug description**
I am running Firefly III version 4.7.9

The 'Actions' menu (to edit, delete, and such) is shown half out of browser window when showing all transaction without grouping by month.

More a UI issue then a real bug.

**Steps to reproduce**
Open any account with some transactions in them.
Click the 'Show all transactions without grouping them by date.' button at the bottom of the list.
Now click the 'Actions' button to show the menu.
This behaviour is more pronounced when using the Dutch language, 'Bewerken' and 'Verwijderen' are long words, so cannot be read completely anymore.

**Expected behavior**
It would be looking a little bit better when the menu is rendered to the left in this instance instead of to the right.

![firefly-iii actions menu out of screen](https://user-images.githubusercontent.com/1969576/50547918-07d1a500-0c44-11e9-92ee-7bccdd895854.jpg)

**Comment by JC5** [comment]
Fixed.
