### ISSUE TITLE
Duplicate entries when breaking of an Bunq import

### ISSUE THREAD

**Issue by sachawolf** [firefly-iii/firefly-iii#1946]
**Bug description**
I am running Firefly III version 4.7.9

When breaking off a running import from Bunq it will store the transactions without running a duplicate check.

**Steps to reproduce**
Start an import.
During the waiting screen close the browser window.

**Expected behavior**
That it only writes transactions after checking for duplicates.

**Extra info**
I spent some time to manually get rid of most of these duplicates. If you are interested I could setup a test version of Firefly-III and see if I can reproduce the issue and make some screenshots.

**Comment by sachawolf** [comment]
My day job is (very) junior technical application manager. And I have loads of years of working support functions.

Nothing is impossible, even if it seems that way ;)

I'll see when I have some time to set up a test docker and mess about with it.

My current live version is running in a docker container on a Plesk hosted VPS. So getting to the logging data is something I haven't figured out yet.

**Comment by JC5** [comment]
Which is why I said "seems". 

Can you check out the table perhaps?

**Comment by sachawolf** [comment]
I have and I cannot find any duplicates in the data field.
On the other hand, I have deleted a lot of transactions today and I still have some correcting amounts for accounts that I have all data for.

Maybe something else happened with the transactions that I can't seem to figure out now.

So yeah, I'll do my best to get a test firefly-iii running and try to break it with duplicate transactions.

**Comment by JC5** [comment]
Mmm. It seems :wink: that Firefly III doesn't see them as being duplicate. There might be meta data that is different.

If you can replicate the problem, visit /transactions/debug/x (as opposed to /transactions/show/x) and store the JSON you see. That is almost all of the data Firefly III has on a transaction and might be a clue as to what is wrong.
