### ISSUE TITLE
[Feature Request] Directed transfer/savings/piggy bank plans

### ISSUE THREAD

**Issue by MatthewDaize** [firefly-iii/firefly-iii#1949]
**Description**
A recurring calculated directed savings/transfer plan.

It would be great if Firefly would provide a prescriptive/directed plan for paying off liabilities and populating savings/asset accounts based on available funds from one/more income transactions or budgets.

**The Problem**
At is stands at this point, the end user adds transactions for income, but then self-directs the moneys into the various accounts. This requires the user to determine how much they have remaining for their various transfers (such as those to savings, investments, or piggy banks).

**Solution**
Introducing a(n optional) recurring report/plan (think: a combination between a budget and account reconciliation operation) that takes a categorized transaction (perhaps income?) and provides a recommendation of where to direct those funds. Of course expenses should be priority, then savings/investments/piggy banks secondary.

Preset/custom strategies for directing these funds would also aid in the recommendations for directing funds.

This may also lead into directed liability pay-off ordering (eg. snowball vs lump sum).
It also may lead into the development of more advanced piggy bank options such as calculating contributions based on priority/ranking, complete-by-dates, or remaining salary funds.

**What are alternatives?**
Currently, one needs to use the budget and transaction history to determine where moneys should flow. Additionally, custom directing funds to piggy banks is also required.

I use the following flowcharts (though slightly modified for personal use) to aid in determining where to direct my monies:
- http://i.imgur.com/zlGnuDO.png (Canadian)
- https://i.imgur.com/CcEVQAV.jpg (American variant for reference)

There is also some obvious functionality using the rules, but may be a bit thin in order to accomplish the above.

**Comment by JC5** [comment]
This is quite impressive, my compliments!

The feature you're suggesting is out of scope for Firefly III. I want the main focus for Firefly III to be to reflect what your *current* situation is. I know there are some tools to help you save and organize "future" money (piggy banks mainly) but I don't want to expand these features. 

I like the idea, don't get me wrong. You could enter your income(s), and depending on the day of the week, the state of your piggy banks and everything else you could create the necessary transfers to move everything around. 

But for the core application of Firefly III, it isn't a good fit.

Having said that: it's entirely possible and feasible to build this against the API of Firefly III. All the information you require is right there. You can even create the transfers and fill the piggy banks. I'm not sure how much of a programmer you are yourself?

**Comment by MatthewDaize** [comment]
Thanks for the response. It would be nice to have that one pane of glass for the entirety of one's finances (past, present, and future), but I understand your position/goals for this project.

Building something against the API is not something I'm too worried about (though I'm definitely not as good a developer as you are based on the clean codebase), but I was more curious if it's something that could become core functionality when looking for a money management tool. It's great to know where you are currently, but I see more value in knowing where I'm trying to get to and the most efficient path to get there.

Thanks again for building this great tool!
