### ISSUE TITLE
searching tags

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#1953]
I am running Firefly III version 4.7.9

I made a tag "Mallorca" and linked it to an expense

![schermafbeelding 2019-01-01 om 17 14 00](https://user-images.githubusercontent.com/44246750/50574439-f1188300-0de8-11e9-8ce0-282a34d10d53.png)

When I tried to do a search for that tag in the searche box it did not result in 1 hit. It returned 50 transactions. I tried with tag: and tags:

but maybe that feature doesn't exist yet

**Description**

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
As per the documentation, this is not yet a feature. But it's on the list now :)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947668
