### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#1954]
**Description**
Please describe your feature request:

-Support for plugins with hooks and other methods

**Solution**
Allow community to contribute modules that are part of core

**What are alternatives?**
https://github.com/kanboard/kanboard currently supports plugins that users and install without having to make changes to the core using a bunch of hooks https://docs.kanboard.org/en/latest/plugins/index.html.

**Comment by JC5** [comment]
I'm sorry, but Firefly III isn't going to feature a webhooks system. There's an API already, and that will have to do for the time being.

**Comment by JC5** [comment]
I just don't see a use case for plugins. Is there anything in particular you'd like to do?

**Comment by lastlink** [comment]
Customizations that the community may want to make that you don't necessarily want part of core. Just some examples, like a budget forecasting support #1831, google oauth (might already be part of core), showing amounts left in a budget category for a month when doing a transaction. 

Especially when some user contributions are hacky and not stable they may be better as plugins until they are mostly finished up and users consider making them part of core. Drupal has many user contributed modules that due to popularity eventually became part of core.

**Comment by lastlink** [comment]
I would like to have the ability to make some custom changes to the application and still be able to pull updates from new releases such as trying to make 1831 work and other changes.

**Comment by lastlink** [comment]
Often core maintainers provide plugin support b/c they don't want to build certain features that go away from their vision of the product so community users can customize to their personal tastes.

**Comment by JC5** [comment]
It's not going to happen. It's a security nightmare in a financial app that is already difficult enough to build and maintain with every other user wanting to go into another direction.

If anything, Firefly III is going to have less features, not more.

Feel free to use the database, the API and the code base in general to build beautiful things but if Firefly III is going to be at the center of any financial ecosystem it's not going to be through plugins.

**Comment by nonbinary** [comment]
I came here looking to work on a plugin, but I see that I should look into the API instead.

I will, however, mention my case as a possible use for plugins.
I intend to write some auto-importing scripts that pull statements from my bank. To use their API, I will use the bank's very good authentication system. There is, of course, a risk of my session to the bank being hijacked. But I feel confident that the bank's API is rather safe to use.
That API is very specific to my country, and there is little point in making a pull request. Having specific connectors to every bank in the world would be horribly cluttered. It would only be usable as an installable plugin.
I'm also interested in writing plugins for an organization that I work for. This would also be quite country-specific, as it would be stuff written to interact with our tax systems, banks etc.
Again, pointless to merge into the mainstream application.

I'll write this as separate applications talking to firefly's API, and hack them into the UI. But I think they would be more usable to other users in my country if they could be written as plugins.

**Comment by rsotnychenko** [comment]
Security is an extremely important aspect of any modern application, especially one that handles sensitive data. However, I do not think that it's an argument against plugins in our case.
Firefly III is a product for "software people", the people who at least know how to use console and launch something on Heroku or Docker. Thus I think that we should approach security from a different side, for example by implementing proper access controls for plugins and audit logs while displaying warnings about risks related to granting plugins access to the data.

Some applications, including Firefly III, are targeting an audience with greatly different needs and requirements, therefore making it impossible to maintain all the features in a single core repository. Having an API is great, but not sufficient to cover all the needs, so plugins is something that needs to be supported.
