### ISSUE TITLE
Reports  - Category report

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#1955]
I am running Firefly III version 4.7.9

I wonder what the purpose is of the calculation - 151,24 (see below) 

![schermafbeelding 2019-01-01 om 18 34 42](https://user-images.githubusercontent.com/44246750/50574998-f5966900-0df3-11e9-84ec-345437f74b9d.png)

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Looks like a bug. I’ll check it out.

**Comment by JC5** [comment]
It was a bug. Will be fixed in the next release. Nicely spotted :+1:
