### ISSUE TITLE
Liability payments as part of budget

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#1956]
**Description**
Please describe your feature request:

- I would like track account transfers to a liability account as part of the budget

**Solution**
Right now account transfers are tracked as transfers and can have categories, piggy banks, and tags. While expenses are the only the ones that can be tracked as part of the budget

**What are alternatives?**

**Additional context**

**Comment by JC5** [comment]
Yes, so do I. I am not sure yet what the solution could be. Once I have something I'll update you.

**Comment by lastlink** [comment]
I'm experimenting with it this month so my understanding of this platform may be off, but my current solution as a process (without making changes to application) is to track liability as expenses (to fit in the budget) and create a fake revenue account and asset account (not tracked in networth) to track transfers to liability accounts. I'll see if the linking transaction ability will work as well.

**Comment by JC5** [comment]
That's what I did originally. Having liability accounts is a step-up but I don't want transfers to have budgets. So right now there's no solution yet. 

I'm thinking introducing a new transaction type when transferring money to liability accounts. That fits the rest of Firefly III and allows me to set rules as to what is allowed (budgets, categories, etc) and what isn't. It would mean a big change for almost everything else though.

**Comment by spaetz** [comment]
Missing that too. What speaks against transfers belonging to budgets? When I have monthly backpayments of my mortgage, I would like to track this with a budget.
Right now, I can only put the interest payments in the budget as these are actual withdrawals.

**Comment by 8bitgentleman** [comment]
I'd also like to request the ability to budget payments to a liability. Without this ability budgeting for loan payments becomes tricky and the budgets inaccurate. Looking forward to your solution :smiley:

**Comment by apowell656** [comment]
I left a comment on #1803 in an effort to better manage liability accounts. In the meantime, I have a thought that I don't think would change too much of the architecture.
- I set up a cash account (Liability Payments) to manage the transfer to the liability accounts - does not show up in the net worth
- Once I make a payment from the asset account I increase the Liability Payments by the same amount as a cash increase - which is planned in the budget and tagged liability payment
- The transfer occurs from Liability Payments
- The payment is placed on the home screen so that I can monitor that the balance always stays at $0.00
- My thought is why not make a rule that can look for a tag and creates a transfer
Just a thought.

**Comment by MacPaille** [comment]
JC, I'm currently looking at the liability usage, but can't find any information in the doc nor usage in the demo site. Can you explain how to use it?
I want to use it for my house and car loan to be able to see inside FF how much I still have to reimburse...
Thanks!

**Comment by JC5** [comment]
All you have to do is create a liability account with the debt you have as the start balance. From there, just transfer money away from or into the debt.

Future releases will improve liability management but my focus is on other things, at the moment.

**Comment by MacPaille** [comment]
Thanks a lot found it. I was looking everywhere except the account list in the transfer transaction...

Would be cool to have the possibility to have 2 amounts in the liability. The one you are borrowing and the one you have to reimburse, as you are not doing anything Ith the interest value (which I totally understand).

**Comment by nbgannet** [comment]
I have a similiar use case whereby I budget to put money into a savings account, but can't applya budget to the transfer.
A workaround would be to withdraw to Cash and then Deposit into the Savings Account?

**Comment by JC5** [comment]
In 4.8.0, this will be how it works. If you have comments, just reply.

<img width="865" alt="Screenshot 2019-04-08 at 20 17 41" src="https://user-images.githubusercontent.com/5889984/55747013-7ee4b980-5a3b-11e9-9872-a0d96a9e0031.png">

https://github.com/firefly-iii/firefly-iii/projects/5#card-19937456
