### ISSUE TITLE
Split a piggy bank into multiple asset accounts

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#1957]
**Description**
Please describe your feature request:

- Difficult to do some piggy banks, b/c might have cash on hand as well amounts in a savings assets set aside for same piggy bank

**Solution**
Should be able to add a piggy bank to multiple assets and track amounts in each allocated to the piggy bank

**What are alternatives?**
I don't know if #18 is part of this.

**Comment by JC5** [comment]
That can be done but it requires a pretty large database change. I'll think about the best way to do this.

**Comment by jasonbone75** [comment]
I'll add a vote to this. My use case is setting aside tax and NI each month when self-employed using regular savers attached to current accounts - you have a limit on deposits so have to spread across multiple accounts but still want to track progress towards the 6 monthly payment deadlines.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19974876

**Comment by lastlink** [comment]
What is the motivation behind closing the issues that are linked in the project cards? why not add the issues directly into the project kanban or convert the cards into issues to track easier. we can't add comments to project cards that aren't issues.

**Comment by JC5** [comment]
It cleans up the list of issues. I can refer people to the roadmap using the issue template.
