### ISSUE TITLE
Organize budgets into categories or sections

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#1959]
**Description**
Please describe your feature request:

- I would like Firefly III to display budgets in more organized sections

**Solution**
Should be able to see budgets in a more organized table view

**What are alternatives?**
Every-dollar does these as categories since we are using this already sections might be better

**Additional context**
![budget section](https://user-images.githubusercontent.com/6679425/50575927-3df25e80-0dd5-11e9-97e3-7f3169b0b48d.png)

**Comment by JC5** [comment]
I'll put it on the list.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19974962
