### ISSUE TITLE
Read only auditor accounts

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#1960]
**Description**
Please describe your feature request:

- I would like Firefly III to allow us to create a user for an accountant to review our transactions

**Solution**
I know that currently there is no shared account support, I thought maybe a read only user might be possible, but does still sound like quite a bit of work.

**What are alternatives?**
Exporting transaction records and giving to accountant

**Comment by JC5** [comment]
That requires a change to the very core of Firefly III. So I’m sorry, but that won’t be possible.
