### ISSUE TITLE
Reconciliation Page Links

### ISSUE THREAD

**Issue by usmcamp0811** [firefly-iii/firefly-iii#1961]
This is just a small annoyance feature request but others might be thinking the same. This is a relatively small tweak that would be nice, and save me some (and maybe others headache). It has to do with links from the account reconciliation page. I think the links going to the transaction details should either display a warning modal warning the user their progress is about to be lost and/or just open the links in a new browser window. Alternatively, some type of memory would be nice so that you don't go to edit/delete a bad transaction on the last day of the month after reconciling 20 other transactions and find out you have to go do all that over again. Let's just say I might know I guy this just happen to.... ;-)

**Comment by JC5** [comment]
Well at least it'll only happen once. :wink:

**Comment by JC5** [comment]
I'm not going to follow up on this, sorry about that.
