### ISSUE TITLE
Upgrading help when installing from Softaculous

### ISSUE THREAD

**Issue by TobiasDev** [firefly-iii/firefly-iii#1962]
I am running Firefly III version 4.7.7

**Description**
I'm hosting my Firefly Instance through a provider that uses Softaculous, however, they don't have a "upgrade" script for Firefly which means it can't be done automatically (sadly). Is there any way I can upgrade my Firefly instance through Firefly itself? Or that I can grab the files here from Github and upload them into my Firefly folder? 

The biggest problem for me is that I'm not sure which files I should not upgrade so my database connection and everything stays the same.

**Comment by JC5** [comment]
I'm sorry, I have no idea what would be the best way to upgrade a softaculous installation. What you can try is to [backup your data](https://docs.firefly-iii.org/en/latest/installation/backup.html) and install Firefly III (v4.7.9) again, and then point it to the old database. In the .env file, you must replace the APP_KEY with the old one and then the web interface should upgrade itself.

**Comment by TobiasDev** [comment]
> 
> 
> I had the same problem and I did what @JC5 said, with an addition: I had to update the database myself since a table changed between version 4.7.8 and 4.7.9.

Sorry, what did you have to do? Because I did get an error when trying to open Firefly after changing the .env file.

**Comment by BoGnY** [comment]
> Sorry, what did you have to do? Because I did get an error when trying to open Firefly after changing the .env file.

If you have SSH access to server, you have to run the following commands (from firefly installation directory) to update your database with the latest changes:
```shell
php artisan migrate --seed
php artisan firefly:upgrade-database
```
If you don't have it, you have to go to `/database/migrations` and open all new file that wasn't be on previous version, then manual apply all changes in your database..
**Make this with CAUTION as you have to understand PHP instructions and how this instructions must be applied on database... MAKE A BACKUP FIRST!!!**

**Comment by TobiasDev** [comment]
It looks like I have Shell, access, so I'm considering just re-installing Firefly myself, through the shell access, because maybe that way it also doesn't get the weird "Public" folder, that it get's when using Softculous. @JC5 Do you think that is possible to do?

**Comment by TobiasDev** [comment]
Hello again! 

I've been trying to run the two commands @BoGnY wrote, and it only partially works. I can do the first one: 

`php artisan migrate --seed`

However, as soon as I get too the second one I get an error:

`In Preference.php line 100:

  Could not decrypt preference #5. If this error persists, please run "php ar
  tisan cache:clear" on the command line.
`

I tried running the cache:clear but it didn't help. 

Any ideas?

**Comment by lucavallerini** [comment]
The APP_KEY in the .env file is correct (the same of your previous installation)?

**Comment by TobiasDev** [comment]
Aha... That was what I missed! Sorry, I see that it also says earlier, but for some reason I missed it. Thanks for the help!
