### ISSUE TITLE
"Amount" field disappears

### ISSUE THREAD

**Issue by qirtaiba** [firefly-iii/firefly-iii#1964]
I am running version 4.7.9 of Firefly on Sandstorm. Since the last update on 27 December, when I try to do a "Transfer" the "Amount" field is gone. The only fields visible are Description, Source account, Destination account, and Date. If I complete those fields and click "Store new transaction" then in the next screen suddenly there is an "Amount (source)" field that appears. But if I add the amount into it and "Store new transaction" again, there is a red error that flashes up briefly saying "The amount must be a number", along with a red outlined box that seems to be labelled "Amount" (but not "Amount (source)". But the page refreshes very fast almost before you can read the red error, and then you are back in the same screen as before. No matter how many times you click "Store new transaction", you can't get any further.

**Comment by JC5** [comment]
I think I fixed that locally by doing a hard refresh. Ctrl-F5 in Windows or Command Shift R on your Mac.

**Comment by qirtaiba** [comment]
I have tried that (I am using Chrome on a Mac) and it hasn't worked. I've also tried switching to a different web browser that I don't normally use (Safari), and it didn't help either. So it seems improbable that it's a browser issue.

Also, this may or may not be related, but when entering other sorts of transactions that aren't a transfer (such as a withdrawal), I have to click "Store new transaction" twice. The first time, it returns me to the data entry screen having done nothing. The second time, it works and tells me that the transaction was successfully saved. This behavior seems to have arisen at about the same time as the problem with the missing amount field.

**Comment by qirtaiba** [comment]
Update: I inspected the source code and found this:

`<div id="amount_holder" class="form-group" style="display: none;">`

So that sure seems like a bug to me.

**Comment by JC5** [comment]
Mmmm. So far I can't replicate your issues in my local Sandstorm installation.

* Creating a transaction just works. Both when I click "New withdrawal" and use the buttons to switch to deposits or transfers, but also when I click "New deposit" or "New transfer".
* The amount field is gone, and this is by design. The "New transfer" screen uses "Amount (source)" and "Amount (destination)" when you create a transfer. 
* The auto-complete dropdown works fine as well.

I'll play around with it some more but so far I got nothing, sorry about that. 

Are there any special errors in your Console, perhaps?

**Comment by qirtaiba** [comment]
Nothing in the Sandstorm console. In the Chrome console there is some suspicious looking stuff:

`jQuery.Deferred exception: Cannot read property 'symbol' of undefined TypeError: Cannot read property 'symbol' of undefined`
`    at selectsForeignCurrency (https://sandstorm-ui-856dd6f613ba7a4c0e70cdab4f293ed9.prost.asia/v1/js/ff/transactions/single/common.js?v=4.7.9:83:82)`
`    at updateForm (https://sandstorm-ui-856dd6f613ba7a4c0e70cdab4f293ed9.prost.asia/v1/js/ff/transactions/single/create.js?v=4.7.9:270:5)`
`    at HTMLDocument.<anonymous> (https://sandstorm-ui-856dd6f613ba7a4c0e70cdab4f293ed9.prost.asia/v1/js/ff/transactions/single/create.js?v=4.7.9:35:5)`
`    at c (https://sandstorm-ui-856dd6f613ba7a4c0e70cdab4f293ed9.prost.asia/v1/js/app.js?v=4.7.9:1:111546)`
`    at l (https://sandstorm-ui-856dd6f613ba7a4c0e70cdab4f293ed9.prost.asia/v1/js/app.js?v=4.7.9:1:111848) undefined`
`C.Deferred.exceptionHook @ app.js?v=4.7.9:1
app.js?v=4.7.9:1 Uncaught TypeError: Cannot read property 'symbol' of undefined`
`    at selectsForeignCurrency (common.js?v=4.7.9:83)`
`    at updateForm (create.js?v=4.7.9:270)`
`    at HTMLDocument.<anonymous> (create.js?v=4.7.9:35)`
`    at c (app.js?v=4.7.9:1)`
`    at l (app.js?v=4.7.9:1)`
`DevTools failed to parse SourceMap: https://sandstorm-ui-a8c9c49052f44d16e47f3803b5764d7a.prost.asia/socket.io/socket.io.js.map`
`DevTools failed to parse SourceMap: https://sandstorm-ui-90f7b707cfbe53eba7d41fb25aa3c254.prost.asia/socket.io/socket.io.js.map`

The workaround that I have been using is to create Transfers as a Deposit or Withdrawal first, and then convert them into a Transfer. But it's messy.

Could I create an account for you on my Sandstorm and share the grain with you?
