### ISSUE TITLE
twig error after updating to 4.7.9

### ISSUE THREAD

**Issue by Rehaell** [firefly-iii/firefly-iii#1966]
I am running Firefly III version x.x.x

**Description**
Every time I press the add or edit button on a transaction or account I'm greeted with the error below:

`(4/4) Twig_Error_RuntimeAn exception has been thrown during the rendering of a template ("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'enabled' in 'where clause' (SQL: select * from `transaction_currencies` where `enabled` = 1 and `transaction_currencies`.`deleted_at` is null order by `code` asc)") in "/var/www/firefly-iii/resources/views/v1/accounts/create.twig" at line 21.
--`

This just happen after I updated to 4.7.9.

**Steps to reproduce** 
- updated to 4.7.9
- add or try to edit any transaction or account

**Extra info**
Debug information generated at 2019-01-03 21:25:43 Asia/Dubai for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | production |
| App debug mode | true |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.13 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-01-31 23:59:59 |
| Session first | 2018-11-23 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, ldap, pdo_mysql, pdo_pgsql, sodium, tidy, zip |
<img width="789" alt="screen" src="https://user-images.githubusercontent.com/274498/50651870-a2035700-0f7c-11e9-8d33-50616f879586.png">

**Comment by JC5** [comment]
Please make sure you also run the upgrade commands (migrations and database cer

**Comment by JC5** [comment]
Hi!

As per [the documentation](https://docs.firefly-iii.org/en/latest/installation/upgrading.html), please run the following commands to complete the upgrade:

```
php artisan cache:clear
php artisan migrate --seed
php artisan firefly:upgrade-database
php artisan firefly:verify
php artisan cache:clear
```

**Comment by Rehaell** [comment]
> Hi!
> 
> As per [the documentation](https://docs.firefly-iii.org/en/latest/installation/upgrading.html), please run the following commands to complete the upgrade:
> 
> ```
> php artisan cache:clear
> php artisan migrate --seed
> php artisan firefly:upgrade-database
> php artisan firefly:verify
> php artisan cache:clear
> ```

Thanks, its fixed.
