### ISSUE TITLE
Attachement on bills not showing up

### ISSUE THREAD

**Issue by filoor** [firefly-iii/firefly-iii#1967]
Hi 

I'm Running v.4.7.9 on docker container.
When i add a attachment on a transaction it shows up but when i add it to a Bill i cant find it back it will say uploaded but when i look to the bill i cant see the attachment.

Do the attachment on bills work the same as on transactions?

**Comment by JC5** [comment]
I think there's a bug in the display of attachments, sorry about that. I'll get it fixed for the next release.

**Comment by filoor** [comment]
Hi @JC5 

Oki Thank you

**Comment by JC5** [comment]
Fixed in the next release.
