### ISSUE TITLE
Interval date after selection shows wrong finish date

### ISSUE THREAD

**Issue by BoGnY** [firefly-iii/firefly-iii#1968]
**Bug description**
I am running Firefly III version 4.7.9

I think is only a visual bug, but I'm not sure..
In homepage, Firefly shows interval date 1 january 2019 - 31 december 2019, but if I change the date, by selecting 2018 (or 2017, or 2016), the interval date became 1 january 2018 - 1 january 2019..
But the correct interval must be 1 january 2018 - 31 december 2018..

**Steps to reproduce**
Change interval date on homepage by selecting a previous year.

**Expected behavior**
Correct interval date..

**Extra info**
Debug information generated at 2019-01-04 09:07:40 Europe/Rome for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.13-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-12-31 23:59:59 |
| Session first | 2015-09-23 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.85 Safari/537.36 Vivaldi/2.3.1401.7 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, bz2, curl, fileinfo, gd, gettext, intl, ldap, mbstring, exif, soap, sockets, sqlite3, xmlrpc, mysqlnd, PDO, xml, bcmath, calendar, ctype, dom, ftp, iconv, json, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache, xdebug |

**Bonus points**
Start homepage shows correctly interval date:
![image](https://user-images.githubusercontent.com/11542801/50678771-9a859180-1000-11e9-9ac1-7c2ba5f344cd.png)

After changing years (2018) don't show 31 december 2018 but 1 january 2019:
![image](https://user-images.githubusercontent.com/11542801/50678809-c4d74f00-1000-11e9-9485-9b32c94cd181.png)

**Comment by JC5** [comment]
Nice find. I've pushed a fix for the next release.
