### ISSUE TITLE
Custom range

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#1969]
I am running Firefly III version 4.7.9

It used to work in the prior version but not anymore. I found it very usefull. 

You could just enter the start and end dates and click on ok and there is was. now you can;t type the date, you hace to select the start date and drag the mouse to the end date but that only works for 2 months not longer

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
I'm using a library to give you the date range thing and they've changed it. It's also not an option anymore. I'm sorry, but I can't fix this.

**Comment by bartmaniac** [comment]
well let's hope one day it will come back
