### ISSUE TITLE
Stuck at installation during composer create-project

### ISSUE THREAD

**Issue by chonsanova** [firefly-iii/firefly-iii#1970]
**Description**
Stuck at installation during composer create-project. Failed to download / clone from github due to "Network is unreachable".

**Steps to reproduce** 
1. Follow installation steps as per [philthynz's instructions](https://gist.github.com/philthynz/ec04833a8e39c7f7d1b0d33cb4197a95)
2. Reach step 'Install Firefly III'

**Extra info**

- I've tried doing it as sudo as per [official documentation](https://firefly-iii.readthedocs.io/en/latest/installation/server.html), to no avail, though don't think it's to do with permission.
- I've tried including the version number (4.7.9 being the latest, 4.7.4 as per documentation), as well as excluding it (which seems to automatically find the latest anyway), to no avail.
-It was showing a different error message at first, but `sudo apt install 7.2-ldap` seemed to have fixed that one. 
- Error message mentions something about port 22, which I had enable in an earlier step. Could it be something to do with my IPv6 only instance (hosted on Vultr)?
- See specific error messages in the screenshot attached.
- OS: Ubuntu 18.04, PHP 7.2, MariaDB

**Screenshot**
![image](https://user-images.githubusercontent.com/16068743/50731623-9ad38780-11ce-11e9-921f-34b260d42709.png)

Please help! I'm quite noob, pretty much just capable of following instructions and pasting in lines of commands... Thanks!

**Comment by JC5** [comment]
Github [cannot be reached over ipv6](https://www.quora.com/Why-doesnt-GitHub-support-IPv6).

**Comment by chonsanova** [comment]
Thank you! Works after I created another instance with ipv4. 
In hindsight I could've probably just added ipv4 to my existing instance, but all good. Thanks again.
