### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by tarmax** [firefly-iii/firefly-iii#1971]
I am trying to run Firefly III version 4.7.9

I am sure this problem is already been, but I am unable to solve it.
https://magzdar.net/firefly-iii/login
404 - not found

I am running opensuse.
I have followed all instruction in https://docs.firefly-iii.org/en/latest/installation/server.html
My FF3 directory is /opt/firefly-iii
Apache follows this links firefly-iii -> /opt/firefly-iii/public/
Db is created without error
I use apache2 for my personal (and obsolete) website, only in https. https://magzdar.net
In stotage/logs there are no files and in /var/log/apache2 there are no notifications

Can you please help me in some way?
Thank's a lot
Max

**Comment by tarmax** [comment]
I have read about this problem, but the command 
**a2enmod rewrite** tells me
"rewrite" already present

**Comment by JC5** [comment]
Alright, but I need to know that. Did you also reset Apache? And don't say "obviously", because if you don't tell me I have to guess and I need to cover the basics.

**Comment by tarmax** [comment]
I have restarted apache now. 
service apache2 restart
but it seems nothing is changed

**Comment by JC5** [comment]
Alright, let's see. What's the configuration of Apache like? Check if the <Directory> statement has "Allowoverride none" for your web directory. It should say "AllowOverride All".

**Comment by tarmax** [comment]
:-) thank's a lot!
it works!
