### ISSUE TITLE
Unable to get a working install on Ubuntu 18.04 and Docker - results in "Be right back"

### ISSUE THREAD

**Issue by apowell656** [firefly-iii/firefly-iii#1972]
**Bug description**
I am running Firefly III version 4.7.9 (Docker install)

(please give a clear and concise description of what the bug is)
I followed the directions to install via Docker and the screen is stuck at Be right back and there is no evidence that database migration happened.

**Steps to reproduce**
What do you need to do to trigger this bug?
- Install on Ubuntu 18.04 using [Docker instructions.](https://firefly-iii.readthedocs.io/en/latest/installation/docker.html)

**Expected behavior**
What do you expect to see after those steps?

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).
- Ubuntu 18.04
- Docker version 18.09.0, build 4d60db4
- Chrome browser

![Be right back screenshot from 2019-01-06 09-59-32](https://user-images.githubusercontent.com/1969515/50737636-e28bec00-1199-11e9-9d54-2d209ebc66e1.png)

**Comment by apowell656** [comment]
I used the docker compose command. My instance of MYSQL is located on the same machine and docker is doing its own thing so I can test firefly.  FWIW - I am a little foreign to docker but I thought this would be a good use case to get more familiar.

**Comment by cwalv** [comment]
Don't forget to run the database setup commands from https://docs.firefly-iii.org/en/latest/installation/docker.html:

```
docker-compose exec firefly_iii_app php artisan migrate --seed
docker-compose exec firefly_iii_app php artisan firefly:upgrade-database
docker-compose exec firefly_iii_app php artisan firefly:verify
docker-compose exec firefly_iii_app php artisan cache:clear
```

**Comment by apowell656** [comment]
Right, I did run those commands and chalk up my issue to my learning of
docker.

It appears that I need to make the IP address of the MySQL location
available inside of docker to make this work.

I don't want to install MySQL inside of a container since I already have a
working instance available.

I will continue to search for a solution. If anyone has any suggestions I
am definitely open to them.

Andre

**Comment by JC5** [comment]
> It appears that I need to make the IP address of the MySQL location available inside of docker to make this work.

> I don't want to install MySQL inside of a container since I already have a working instance available.

These are two different things. You can install a container with MySQL on it, and make Firefly III connect to it. You can also install 5 containers with MySQL on it, and make Firefly III connect to either of them.

If you have a container with MySQL running already, it makes sense not to add another one.  But nothing breaks if you do this.

**Comment by apowell656** [comment]
To clarify I have MySQL running outside of a container. So I would either
have to insatll MySQL in a container or figure out how to reach the host's
version of MySQL.

Andre

**Comment by JC5** [comment]
You won't be able to install MySQL in a container. At least, not easily without essentially rewriting the entire container. Docker doesn't support it out of the box.

I suggest you look at [Docker's documentation](https://docs.docker.com/network/) regarding networks. It's possible to create a network between Firefly III and an arbitrary number of other containers. In fact, this is what the docker-compose file configures out of the box.

**Comment by apowell656** [comment]
And now is not the right time to "explore" Docker since I want to give a fair evaluation of firefly (currently using GnuCash and a former YNAB user). So I took a hint from https://github.com/firefly-iii/firefly-iii/issues/1971 and just installed in a more comfortable way. Thanks for you help on this.
