### ISSUE TITLE
Option to exclude an account from "Balance (Saldo)"

### ISSUE THREAD

**Issue by meizenga** [firefly-iii/firefly-iii#1973]
I would like to have an option to exclude an account from Balance (Saldo). This would help to manage cashflow.

There is already an option to exclude an account from "Net Worth (Kaptiaal)"

**Comment by JC5** [comment]
Meh. I'll think about it when implementing the new layout. If you want to get more details, use the reports.

**Comment by fictitiousexistence** [comment]
I just started using firefly so I think I might be missing something. But I also thought being able to exclude from Balance would be useful especially for credit card payments. 

I am not sure how to reflect a payment to a credit card but I thought using a "Transfer" from my bank account to my credit card would be the best way. 

It seemed to work properly with the net worth amount but did not change the balance. Being able to exclude credit cards from the balance would be a solution to this?

Thanks!

**Comment by JC5** [comment]
Just to clarify on this, the original expense you made on the credit card is what influences your balance. If you pay back your credit card debt you’re just moving funds around.

If I buy a TV on my credit card that expense changes my balance. Paying back my credit card debt doesn’t.

But looking at the original issue: it will not become an option to exclude accounts from the balance.
