### ISSUE TITLE
Reflect contracts in the "Your accounts" overview

### ISSUE THREAD

**Issue by meizenga** [firefly-iii/firefly-iii#1974]
I have setup a number of recurring contracts. It would be very nice to see these contracts and specifically, the future transactions of these contracts, in the monthly graphical overview of Your accounts.

This would be a huge improvement in managing cashflow.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1135

Several forecasting features have been suggested but they are not on my roadmap at the moment. It is difficult enough to get the \*current\* financial overview working correctly.
