### ISSUE TITLE
Import (from spectre) into liability account

### ISSUE THREAD

**Issue by bconte** [firefly-iii/firefly-iii#1975]
**Description**
United States banking customer here.  Most (if not all) of my credit cards are imported in the same manner as bank accounts.  Ffor example, in quicken they are imported via the same channels as my checking and savings accounts, - but with a negative balance.  This seems to also be the case with Spectre.

I would like to be able to select a liability account from the spectre import screen to import credit card and loan transactions into the appropriate category of account.

**Solution**
Allow selection of liability accounts in the spectre account selection screen

**What are alternatives?**
Currently the only alternative i have found is to place my credit cards under the "asset" category.

**Additional context**
A bonus would be to have a "change type" so that when such a feature is implemented, i can just convert my asset accounts to liability accounts and have all the transactions inverted instead of having to do it manually.

**Comment by JC5** [comment]
Credit cards are stored as asset accounts in Firefly III, not as liabilities.

**Comment by bconte** [comment]
Unless i'm missing the point of a liability in firefly...

1. I would respectfully disagree, as credit cards behave more like loans more than checking or saving accounts, with minimum payments and interest, much like any other loan or line of credit (like a HELOC)

2. If you're insistent on this, you may want to change the language under the liability window
![image](https://user-images.githubusercontent.com/1292229/50781533-98773900-1273-11e9-9038-4042e4b39948.png)

**Comment by JC5** [comment]
Oh good point, I'll change the text.

**Comment by bconte** [comment]
Does that mean i also need to have my loans be assets as well to download the transactions?

**Comment by JC5** [comment]
I'll have to check what the code is doing. Stay tuned.

**Comment by bconte** [comment]
Will do, thanks!

**Comment by bconte** [comment]
Any thoughts about downloading loan transactions?

**Comment by bconte** [comment]
Just bumping so that this issue is not forgotten.  How should we download loan transactions?  Do those accounts need to be assets as well?
  
Thanks,
-B

**Comment by JC5** [comment]
Sorry about that. Yes, your credit card has to be an asset account in order to be downloaded.

**Comment by bconte** [comment]
Thanks, JC.  The follow up was actually about loan accounts (mortgage, auto, etc).  Do those need to be an asset account as well?

**Comment by MacPaille** [comment]
JC, I'm currently looking at the liability usage, but can't find any information in the doc nor usage in the demo site. Can you explain how to use it?
I want to use it for my house and car loan to be able to see inside FF how much I still have to reimburse...
Thanks!

**Comment by bconte** [comment]
I'm sorry to see that you decided to close the issue without answering the question about downloading loan assets.

**Comment by JC5** [comment]
Sorry, the issue was auto-closed. It wasn't on purpose. I've added some extra code to make this possible.

**Comment by bconte** [comment]
Hah, that makes more sense; i was surprised as you've been super helpful.

Thank you for getting back and thank you for the changes!
