### ISSUE TITLE
Remember account import associations (Spectre)

### ISSUE THREAD

**Issue by bconte** [firefly-iii/firefly-iii#1976]
**Description**
I have many accounts configured in spectre.  Every time i run an import, i have to re-select the accounts between spectre and my local accounts (also experienced this with YNAB).

I can't think of any reason why i would ever want to mix up which import account gets imported into which firefly account..  It would be amazingly convenient if the system remembered the last associations selected, so that i would not need to re-select them every time i run an import (or worse, allow me to select the wrong one as i try to fly through them quickly)

**Solution**
Spectre remembers which import accounts are associated with which firefly accounts, and sets those values to be the default in the import screen

**What are alternatives?**
Manual selection of every.  account.  every.  single.  import.  And mistakes, as humans are apt to do.

**Additional context**

**Comment by JC5** [comment]
I am fairly sure there was a ticket for this but I can't find it. Good idea regardless :+1:

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520
