### ISSUE TITLE
Account receivables

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#1978]
Thanks for firefly! I've searched the docs and issues but am unsure about how to model an 'receivables' account.
Specifically, I am paying doctors' bills which my health insurance later reimburses (hopefully). So, I would usually book transactions into a 'doctors bills prepaid' account and balance these with my insurance's payments.
How can I model this? It is clearly not a liability account, but it is also not an asset. Having a dedicated receivables account helps me keeping track how much the insurance owes me.

Thanks for hilighting any solutions. I am willing to provide a pull requeston corresponding documentation once I understand how Firefly intents to work.

**Comment by JC5** [comment]
You can’t. You could use a separate asset account to manage the payments.

**Comment by nomachinez** [comment]
If you match an Expense account and Revenue account then the Expense/Revenue account report would get you close to what you're looking for, I think?

**Comment by spaetz** [comment]
OK, thanks for the quick answer. Yes, a revenue account and an expense account with a report between those two could be used, although it feels somewhat clumsy.It clearly is no revenue :-).
I am trying a 'debt' type of account to see whether I can make it do what I want. I have been hampered a few times by the permission to enter negative sums in withdrawals or deposits so far....

In any case, closing this one as it has been answered.
