### ISSUE TITLE
Strip whitespace from tags

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#1979]
Within a few days of usage I have accidentally managed to create duplicate tags with an initial space (oerhaps because I attempted to space delimit new tags rather than by comma) Would it be possible to strip spaces from new tags? I don't see why they would ever be useful....

**Comment by JC5** [comment]
Sure.

**Comment by skuzzle** [comment]
Great point. This is especially useful on mobile, where keyboards happily automatically add a space after a word. I always need to double check to remove those auto-spaces

**Comment by spaetz** [comment]
That was quick, wow thanks! Closing this issue as it has been fixed as far as I am concerned.
