### ISSUE TITLE
YNAB import imports in Cent, but accounts are in EUR

### ISSUE THREAD

**Issue by rixx** [firefly-iii/firefly-iii#1980]
I am running the latest release. I set up a new instance, added empty accounts, and then started the YNAB import. Apart from the frontend gateway timeout, it ran without problems, but all imported transactions were *100 the actual value. 

I can give you any anonymised debug information you need, if you tell me how to get it.

**Comment by JC5** [comment]
Add a new transaction manually. For, say, 12.34 EUR. Is it also * 100?

**Comment by rixx** [comment]
Ah, for future reference: firefly-iii doesn't work with ``en_GB.utf8``, it needs ``en_US.utf8``.

**Comment by JC5** [comment]
:+1:
