### ISSUE TITLE
YNAB import: create budgets

### ISSUE THREAD

**Issue by rixx** [firefly-iii/firefly-iii#1982]
**Description**
Currently, the YNAB import imports cateogories, but not budgets. If it would import all budgets, and associate transactions with the proper budgets, an imported account would look much more useful.

Currently, coming from YNAB, you get a bunch of categories when importing transactions, but no budgets, which are the core feature to somebody coming from YNAB.

**Comment by JC5** [comment]
The API doesn’t provide them.
