### ISSUE TITLE
Amount matching rule expects wrong decimal seperator

### ISSUE THREAD

**Issue by joshwapohlmann** [firefly-iii/firefly-iii#1983]
**Bug description**
I am running Firefly III version 4.7.9 in a Docker environment on a ubuntu bionic server with the german language.
When creating or changing rules the decimal seperator ',' (comma) as argument for matching the amount leads to an error (see image), whereas it works (and is expected) everywhere else in firefly. Rather, the field requires a '.' (dot) to be used as seperator.

![grafik](https://user-images.githubusercontent.com/36891156/50781140-e6586500-12a4-11e9-8b9f-dfd5c487758d.png)

**Steps to reproduce**
1. Configure German language
2. Create a new rule
3. Try to match a transaction amount against a specific value with decimal fractions (like 5,42).

**Expected behavior**
The software should be consistent with decimal seperator usage. It expects ',' everywhere else and it should here also.

**Comment by JC5** [comment]
Nice find, will be fixed in the next release.
