### ISSUE TITLE
Implement using Laravel Forge

### ISSUE THREAD

**Issue by devolper102** [firefly-iii/firefly-iii#1984]
Are you thinking to implement firefly-iii using Laravel Forge? This will be a better idea if you cover this stuff.
Thanks

**Comment by JC5** [comment]
If you pay, sure.

**Comment by devolper102** [comment]
Yeah really paid you if I was not able to install it using forge. I was able to handle it. Thanks ;)

**Comment by howlowck** [comment]
I was able to deploy fireflyiii to Forge with relative ease.  Was there an issue that you encountered when deploying?

I haven't updated firefly since the initial deploy though.
