### ISSUE TITLE
HTTP 500 Error

### ISSUE THREAD

**Issue by ezrix** [firefly-iii/firefly-iii#1985]
Hye I'm new to Docker and Linux.. I tried too install Firefly-iii on a container by pulling image from docker hub.. but when i tried to access it i got 500 error..

Here the log file from the container

Stack trace:
#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1027): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}('')
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap('', Object(Closure))
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\Encryption\EncryptionServiceProvider->key(Array)
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Conta {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44
Stack trace:
#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1027): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}('')
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap('', Object(Closure))
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\\Container\\Conta at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44)
[stacktrace]
#0 {main}
"}

**Comment by JC5** [comment]
What command did you use to start it?
