### ISSUE TITLE
The API should support import commands

### ISSUE THREAD

**Issue by joshwapohlmann** [firefly-iii/firefly-iii#1986]
**Description**
Currently, I don't see a way to automate the import and processing of my bank statements. I'd like to have the power to enrich these statements which meta data, tags, match them to bills, etc. and then have Firefly III notify me about events I care about. 

**Solution**
The API should make it possible to execute the import of bank statements. Either saved configurations or by asking for all relevant arguments for the chosen import method. With this an app/client/cron job/whatever can automatically issue periodical import tasks on a monthly, daily, event basis.

This would enable rules like "notify on transfers above threshold <x>" or "notify on bill payment". 

**What are alternatives?**
Currently imports must be done manually each time. The advantage is, that each change in data or accounting state is a conscious act and therefore nothing changes "automatically in the background".
This active book keeping is more closely to the initial idea of firefly raising awareness of what happens to your finances instead of your bank account getting drained automatically.

This is great, but after you completed that step you are left with repetitive tasks which serve no purpose anymore. After you are awaken and completely aware of expenses and income I'd like Firefly III to notify ME when something interesting happens ... not the other way around.

The day is short enough - it'd be good to have a properly configured financial assistance checking things for you. 

**Additional context**
Profits from #1802 to be implemented.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1462
