### ISSUE TITLE
Earned/Spent column wrong if selecting a limited time span in asset account view

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#1988]
**Bug description**
I am running Firefly III version 4.9.7

**Steps to reproduce**
Select an asset account view and restrict to a limited time span within a month or so. The Spent/Earned box (see right hand box labeled January 2019 in the screenshot) is still showing the full month of expenses/revenues rather than also being limited to the selected time frame.

**Expected behavior**
If I select a custom date range for an account, the Spent and Earned sum should be calculated for that time span and not the full month. See screenshot, it simply shows the (current?) month. It least it is not misleading as it IS labeled "January 2019"...

![screenshot](https://user-images.githubusercontent.com/63132/50836867-8fad6280-135a-11e9-8f81-d66244e7fd2a.jpg)

**Comment by spaetz** [comment]
OK, thank you, understood. It's no big deal once one understands that the box is in the default period view...
BTW, just donated 20$ as a token of gratitude.

**Comment by JC5** [comment]
I saw that indeed, and it's much appreciated :)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947712
