### ISSUE TITLE
Current rule description not shown in edit mode

### ISSUE THREAD

**Issue by joshwapohlmann** [firefly-iii/firefly-iii#1990]
**Bug description**
I am running Firefly III version 4.7.9.
When editing an existing rule, the description is not filled in the corresponding field. It is an empty field.

**Steps to reproduce**
1. Edit a rule with a description

**Expected behavior**
The current description should be filled in the corresponding field for editing.

**Comment by JC5** [comment]
Nice find, I’ll fix it :)

**Comment by JC5** [comment]
Will be fixed in the next release.
