### ISSUE TITLE
Japanese language

### ISSUE THREAD

**Issue by fujineko** [firefly-iii/firefly-iii#1991]
**Description**

I would like help out for the Japanese translation, can you enable it on CrowdIn please?

Thank you and keep on the good work <3

**Comment by JC5** [comment]
I've enabled Japanese. Tell me, what's Japanese in Japanese? As in "The Japanese language". I need it for the settings screen.

**Comment by fujineko** [comment]
@JC5 it's "日本語"

**Comment by JC5** [comment]
I've enabled the language and I look forward to your contributions. Thank you for helping out!
