### ISSUE TITLE
Calendar events preview on new recurring transaction not work

### ISSUE THREAD

**Issue by BoGnY** [firefly-iii/firefly-iii#1993]
**Bug description**
The calendar events preview while creating new recurring transaction redirects to homepage.

**Steps to reproduce**
Go to "Create recurring transaction", insert mandatory infos and click on calendar preview.

**Expected behavior**
Open calendar preview.

**Extra info**
Debug information generated at 2019-01-10 15:33:31 Europe/Rome for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.13-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-12-31 23:59:59 |
| Session first | 2015-09-23 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.3 Safari/537.36 Vivaldi/2.3.1420.4 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, bz2, curl, fileinfo, gd, gettext, intl, ldap, mbstring, exif, soap, sockets, sqlite3, xmlrpc, mysqlnd, PDO, xml, bcmath, calendar, ctype, dom, ftp, iconv, json, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache, xdebug |

**Comment by BoGnY** [comment]
Sorry, already fixed by 2ccbfe45f26f3df475ccb3db9c6b82d16d7dace2 on #1929

**Comment by JC5** [comment]
No problem! :+1:
