### ISSUE TITLE
Password Authentication error when installing via Docker Hub

### ISSUE THREAD

**Issue by Calebs97** [firefly-iii/firefly-iii#1994]
I am running Firefly III version 4.7.6

I'm trying to install firefly using Docker Hub with automatic updates via docker compose (following instructions from documentation). When I try to run the command `docker-compose exec firefly_iii_app php artisan migrate --seed`, I run into the following errors.
"""
password authentication failed for user "firefly" (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations)
SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefly"
SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefly"
"""
I'm not super familiar with docker, so this is probably something wrong with my setup. I downloaded the raw yml file and ran `docker-compose -f docker-compose.yml up -d` with no problems. Then it errored at the next step. Were there other aspects I should have set up beforehand?

**Comment by JC5** [comment]
Is `FF_DB_PASSWORD` the same as `POSTGRES_PASSWORD` in your YAML file?

**Comment by Calebs97** [comment]
Yup, I just tried redownloading the .yaml (raw version), leave the passwords as is ('firefly') and restarting the process by removing the containers/images. But I still ran into the same error. Here's a longer error report if it's helpful.

"""
[2019-01-11 14:43:13] local.ERROR: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefly" (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 7): SQLSTATE[08006] [7] FATAL:  password authentication failed for user \"firefly\" (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations) at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] FATAL:  password authentication failed for user \"firefly\" at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 7): SQLSTATE[08006] [7] FATAL:  password authentication failed for user \"firefly\" at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
"""

**Comment by Calebs97** [comment]
I managed to get it running using the "Docker Hub with automatic updates via run/pull" set of instructions since it didn't have the manual initialization of the db, not sure why the other set of instructions didn't work out for me. Thank you for your help though!

**Comment by JC5** [comment]
Very strange. I'll do some digging just in case. Thanks for letting me know!

**Comment by Calebs97** [comment]
Quick question @JC5 it says on the recurring transaction documentation that "The Docker container should launch a cron job itself." Does that mean I won't need to set up an additional chron job? Thank you again!

**Comment by JC5** [comment]
This functionality will disappear from the next version on, because it makes the image very complex. I suggest you set up a cron job anyway (two cron jobs wont hurt for the time being)

**Comment by killua99** [comment]
I'd the exact issue as Calebs97, The issue perhaps was a wrong setup at the beginning causing the docker-entrypoint.sh for postgres fails.

My solution, was to be sure all the docker-compose.yml was right, and after that run:

`docker-compose down --volumes` 

This also clear the volumes and the broken postgre database.

Also just to mention it, nothing that I think would affect the error, I'm using the postgres image 11-alpine, I'm on a Pine64 with a microSD as storage, space is gold.

**Comment by JC5** [comment]
No that's no problem. It's just that you can't easily migrate from 10 to 11.
