### ISSUE TITLE
Refused to send form data to 'https://api-docs.firefly-iii.org/' because it violates the following Content Security Policy directive: "form-action 'self'".

### ISSUE THREAD

**Issue by simon511000** [firefly-iii/firefly-iii#1995]
**Bug description**
I am running Firefly III version 4.7.9

**Steps to reproduce**
1. Go to https://api-docs.firefly-iii.org/
1. Click on **Authorize** and on **Authorize**

**Expected behavior**
Buttons do not do anything

**Extra info**
![firefly-iii-api-definition- -chromium-11_01_2019-11_23_05](https://user-images.githubusercontent.com/31013205/51028565-0aad8d80-1594-11e9-89a4-1412b2b5bf14.gif)

**Bonus points**
`Refused to send form data to 'https://api-docs.firefly-iii.org/' because it violates the following Content Security Policy directive: "form-action 'self'".`

**Comment by JC5** [comment]
Google Chrome, right? Other users are having this as well. Not sure why Chrome is the only one that has this. I'll do some digging.

**Comment by simon511000** [comment]
Ok thank you

**Comment by JC5** [comment]
This will be fixed in the next release.

**Comment by simon511000** [comment]
nice ;)

**Comment by simon511000** [comment]
I confirm that the bug is gone! Thank you, it's a great job!

**Comment by FabianTe** [comment]
I am sorry to say, but I have this error now too :/ Using the dockerized version `jc5x/firefly-iii:release-4.8.2`

**Comment by JC5** [comment]
Please open a new issue.

**Comment by FabianTe** [comment]
Oh, sorry, it was the missing proxy setting.
