### ISSUE TITLE
New budget/report view range option: Two weeks

### ISSUE THREAD

**Issue by m4ttsavage** [firefly-iii/firefly-iii#2000]
**Description**
A range of two weeks would be ideal for anyone who gets paid on that same interval (every two weeks, i.e. 26 pay periods per year) to budget accordingly.  The discrepancy from using other time periods is just obnoxious enough to make the system hard to use effectively.

**Solution**
In Preferences > Layout > View Range, add a new option: _two weeks_

**What are alternatives?**
Right now, you can attempt to split that budget in half as one week intervals, but that will falsely show you going over/under budget based on which week you pay bills, etc.  Months are similarly inaccurate, as there will be a few months where your pay periods will align to give you 3 checks instead of two.

![two_weeks_fireflyiii](https://user-images.githubusercontent.com/9421099/51082305-9b8a8300-16d2-11e9-8606-c1baa39399c2.png)

**Comment by JC5** [comment]
Congrats on having ticket nr. 2000!

I’ve thought about it before but the hassle, code wise, is not worth it. So unfortunately, Firefly III is not going to have a two week period.

**Comment by m4ttsavage** [comment]
I'm honored to be the lucky winner.  Looks like it'll have to be reward unto itself this time.

Not surprised that it's a hassle; weeks are notoriously problematic time units in my experience, so I wouldn't expect anything less.

Thanks for the quick response and the great tool!  Any suggestions on the best way to handle that in Firefly?  My initial thought is: if you could make a weekly budget that rolls over unused funds into the future, that would be a fairly effective hack of approximating the same period.  I'm happy to modify my feature request to "allow budget rollover" if that seems simpler to implement.

**Comment by JC5** [comment]
Firefly III works [slightly differently](https://docs.firefly-iii.org/en/latest/about/grand-theory.html). I would suggest working monthly.

Budget rollover is typical for tools like YNAB and others, where you budget every penny. Firefly III on the other hand expects you to set your budgets to what you need, and save the rest.
