### ISSUE TITLE
Mapbox

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2001]
I am running Firefly III version 4.7.9. 

Is the tag location still a [gimmick](https://github.com/firefly-iii/firefly-iii/issues/420#issuecomment-262827656)? I have inserted a mapbox API key into my .env file yet I don't see a map render. When I try inserting `zoom level`, `latitude` and `longitude` via the API, it does not store them. (It says `NULL` in my tags table in firefly db)

![mapbox](https://user-images.githubusercontent.com/5896415/51086952-e5817080-1787-11e9-94e5-3280e6a37da2.png)
![mapbox](https://user-images.githubusercontent.com/5896415/51086965-06e25c80-1788-11e9-882a-51bad190bf39.png)

**Comment by JC5** [comment]
Not really, but it needs to be revamped. I had no plans to disable it yet, or remove it or anything. I'm treating this as a bug and I'll check the code.

**Comment by emansih** [comment]
Hey James. Thanks. I pulled d905849 and it works! Thanks again.
