### ISSUE TITLE
Error when saving Transactions

### ISSUE THREAD

**Issue by dthornton292** [firefly-iii/firefly-iii#2004]
This happens when attempting to save any transaction.

Here is the error...
FireflyIII 
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is: 
Argument 1 passed to FireflyIII\Helpers\Attachments\AttachmentHelper::saveAttachmentsForModel() must be an instance of FireflyIII\Helpers\Attachments\object, instance of FireflyIII\Models\TransactionJournal given, called in /home/inthehoa/public_html/dmoney/app/Http/Controllers/Transaction/SingleController.php on line 459 
More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong. 
If you cannot find the cause of this error or when you need some help, please open a ticket on GitHub.

**Comment by JC5** [comment]
Firefly III requires PHP 7.2.

**Comment by dthornton292** [comment]
Ok. That fixed it.. how in the hell did I miss that.. 

 

Heard what sounded like a horse and thought it was a zebra.. damn

 

David Thornton

dave@intheHOA.com <mailto:dave@intheHOA.com> 

573-714-1871

 

In the Heartland Media LLC

Ihe Info You Need, When You Need It!

www.intheHOA.com <http://www.intheHOA.com>

**Comment by dthornton292** [comment]
One question I cannot find the answer for..

 

Did an import today from my account. Everything worked except date…

It put in all the transactions with todays date…. I selected date to map to date… should I have selected a different date selection like transaction date instead of just the plain date?

 

 

David Thornton

dave@intheHOA.com <mailto:dave@intheHOA.com> 

573-714-1871

 

In the Heartland Media LLC

Ihe Info You Need, When You Need It!

www.intheHOA.com <http://www.intheHOA.com>

**Comment by JC5** [comment]
No the field is OK, but what is the date format in your CSV file? Firefly III expects Y-m-d I believe. You can change this during the import.

**Comment by dthornton292** [comment]
ok. I will test again... I thought I switched it to mdY but could have put it incorrect.
