### ISSUE TITLE
Exact time instead of just date

### ISSUE THREAD

**Issue by Lorni22** [firefly-iii/firefly-iii#2006]
Heya,

First of all awesome project and thank you very much for it!
I'd like to ask if it is possible to add a deposit/withdraw etc and also add time instead of just date.

Thank you!

**Comment by JC5** [comment]
Not for the near future but I’ll write it down. :)

**Comment by nearwood** [comment]
I like *not* having the timestamp, but it looks like from the commit that it's optional?

**Comment by JC5** [comment]
Yep. It will store the time as 00:00:00

**Comment by JC5** [comment]
Support for time is now present. User interface will have it in 4.8.0
