### ISSUE TITLE
Transfer fee (deposit/withdraw related)

### ISSUE THREAD

**Issue by Lorni22** [firefly-iii/firefly-iii#2007]
Heya,

I'm also wondering if it is possible to automate this process. For example every time I move money from Account A to Account B there is a transfer fee of minimum 1eu for up to 100eu transfer and then 1% with maximum fee 5eu.

I currently do that manually but I was wondering if there is an option to automate this.

Thank you!

**Comment by JC5** [comment]
I’m sorry no, there’s not going to be an option to automate that.
