### ISSUE TITLE
Updated to the latest version and get the error "Be right back"

### ISSUE THREAD

**Issue by nloshka** [firefly-iii/firefly-iii#2008]
Debug information generated at 2019-01-15 07:04:48 Europe/Amsterdam for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.14 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-01-31 23:59:59 |
| Session first | 2018-12-08 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqlnd, PDO, apcu, posix, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apc, igbinary, msgpack, zip, Phar, memcached, Zend OPcache |

Updated to the latest version and get the error "Be right back" on a white screen. on any operation. what do you advise?

**Comment by JC5** [comment]
So nothing works but the debug screen. That implies database problems. Could you check out your log files in /storage/logs? Might have the exact error message.

**Comment by nloshka** [comment]
[2018-10-31 13:01:38] local.WARNING: No database version entry is present. Database is assumed to be OLD (version 1).

**Comment by JC5** [comment]
Did you run all the upgrade commands?

**Comment by nloshka** [comment]
What kind of update commands do I need to run?

**Comment by nloshka** [comment]
Thanks for the quick answers.
I rolled back to the backup copy, I will try to update it according to the instructions.

**Comment by nloshka** [comment]
It would be nice if you prepared an upgrade instruction for nginx.

**Comment by nloshka** [comment]
# nginx -v
nginx version: nginx/1.12.2
# php -v
PHP 7.2.14 (cli) (built: Jan  8 2019 14:05:15) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.14, Copyright (c) 1999-2018, by Zend Technologies

**Comment by nloshka** [comment]
composer install --no-scripts --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-ldap * is missing from your system. Install or enable PHP's ldap extension.
  Problem 2
    - Installation request for adldap2/adldap2 v8.1.5 -> satisfiable by adldap2/adldap2[v8.1.5].
    - adldap2/adldap2 v8.1.5 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
  Problem 3
    - adldap2/adldap2 v8.1.5 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2-laravel v4.0.10 requires adldap2/adldap2 ^8.0 -> satisfiable by adldap2/adldap2[v8.1.5].
    - Installation request for adldap2/adldap2-laravel v4.0.10 -> satisfiable by adldap2/adldap2-laravel[v4.0.10].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
    - /etc/php.d/10-opcache.ini
    - /etc/php.d/20-bcmath.ini
    - /etc/php.d/20-bz2.ini
    - /etc/php.d/20-calendar.ini
    - /etc/php.d/20-ctype.ini
    - /etc/php.d/20-curl.ini
    - /etc/php.d/20-dom.ini
    - /etc/php.d/20-exif.ini
    - /etc/php.d/20-fileinfo.ini
    - /etc/php.d/20-ftp.ini
    - /etc/php.d/20-gd.ini
    - /etc/php.d/20-gettext.ini
    - /etc/php.d/20-iconv.ini
    - /etc/php.d/20-intl.ini
    - /etc/php.d/20-json.ini
    - /etc/php.d/20-mbstring.ini
    - /etc/php.d/20-mysqlnd.ini
    - /etc/php.d/20-pdo.ini
    - /etc/php.d/20-phar.ini
    - /etc/php.d/20-posix.ini
    - /etc/php.d/20-shmop.ini
    - /etc/php.d/20-simplexml.ini
    - /etc/php.d/20-soap.ini
    - /etc/php.d/20-sockets.ini
    - /etc/php.d/20-sqlite3.ini
    - /etc/php.d/20-sysvmsg.ini
    - /etc/php.d/20-sysvsem.ini
    - /etc/php.d/20-sysvshm.ini
    - /etc/php.d/20-tokenizer.ini
    - /etc/php.d/20-xml.ini
    - /etc/php.d/20-xmlwriter.ini
    - /etc/php.d/20-xsl.ini
    - /etc/php.d/30-mcrypt.ini
    - /etc/php.d/30-mysqli.ini
    - /etc/php.d/30-pdo_mysql.ini
    - /etc/php.d/30-pdo_sqlite.ini
    - /etc/php.d/30-wddx.ini
    - /etc/php.d/30-xmlreader.ini
    - /etc/php.d/40-apcu.ini
    - /etc/php.d/40-igbinary.ini
    - /etc/php.d/40-msgpack.ini
    - /etc/php.d/40-zip.ini
    - /etc/php.d/50-apc.ini
    - /etc/php.d/50-memcached.ini
    - /etc/php.d/apc.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
----------------------
Problems installing or updating.
How to cure a problem?

**Comment by JC5** [comment]
The requested PHP extension ext-ldap * is missing from your system. Install or enable PHP's ldap extension.
