### ISSUE TITLE
Issue updating time/number limited recurring transactions

### ISSUE THREAD

**Issue by Narsat** [firefly-iii/firefly-iii#2009]
**Bug description**
I am running Firefly III version 4.7.9

When a recurring transaction is set to be time-limited or number-limited, changing it back to **Repeat forever** is not possible directly.

**Steps to reproduce**

1. Create/update a Recurring Transaction
1. Set **Repetition ends** to something other than Repeats forever
1. Set a date in the future or a value different from 0 and Save
1. Open the Recurring Transaction and update **Repetition ends** field to Repeats forever and Save
1. Change is ignored

**Expected behavior**
Recurring transaction should have **Repeats forever** value

**Extra info**
**Work around**

Option 1 _(if you have access to account)_
- Set the **Repetition ends** to Repeat a number of times and **Repetitions** to zero.

Option 2 _(if you only have access to DB)_
- Use query:
`UPDATE recurrence SET repeat_until = NULL AND repetitions = 0 WHERE id = ?`

**Comment by JC5** [comment]
Mmm, thanks for letting me know. I wasn't aware of the problem.

**Comment by JC5** [comment]
This will be fixed in the next release.
