### ISSUE TITLE
Warning about /public/ followed by redirect to URL/money/public/ followed by 500 error

### ISSUE THREAD

**Issue by rrbailey89** [firefly-iii/firefly-iii#2012]
I am running Firefly III version 4.7.9

**Description**

I freshly installed into a subdirectory and when going to http://url/money/ I receive a warning about /public/ followed by the screen attempting to forward to http://url/money/public/ which then gives an http 500 error.

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

[Wed Jan 16 15:03:24.410734 2019] [php7:error] [pid 31361] [client redactedip:4222] PHP Fatal error: Uncaught RuntimeException: No application encryption key has been specified. in /var/sites/money/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/sites/money/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1027): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/sites/money/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/sites/money/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/sites/money/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/sites/money/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\\Container\\Container->build(Object(C in /var/sites/money//vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44, referer: https://redactedurl.me/money/

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
What instructions did you follow to do the installation? Did you create an `.env` file for example?

**Comment by rrbailey89** [comment]
So I realized that I didnt completely empty the firefly directory to my /money directory so the .env file was missing, now I still get the /public/ warning but when it auto forwards me to /public/login it gives me a 404 error

**Comment by JC5** [comment]
You can google instructions on how to change the web root for Apache. Is there nothing else in your webroot besides the /money directory?

**Comment by rrbailey89** [comment]
I'm hosting 5 or 6 webapps so there are several directories in my webroot.

**Comment by JC5** [comment]
Then I would suggest using a subdomain for optimal security.

**Comment by rrbailey89** [comment]
Okay I appreciate your patience with me 

Would insert it up like this then?

```
<VirtualHost *:443>
    ServerName john.mysite.com
    DocumentRoot /var/sites/money
    <Directory /var/sites/money/public/>
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```

**Comment by JC5** [comment]
Something like that yes, but I guess it requires some experimentation from your side to see what works exactly :)

**Comment by rrbailey89** [comment]
thanks! a subdomain is the way I went and it is working great!
