### ISSUE TITLE
Why is the ammount shown on the dashboard differnt than what is shown in a report and the assetts page?

### ISSUE THREAD

**Issue by rrbailey89** [firefly-iii/firefly-iii#2014]
I am running Firefly III version 4.7.9

**Description**

Why is the balance shown on the dashboard different than what it shows in Assett Accounts?

I have verified that the ammount shown on the assetts page and in the reports is what my bank reflects as accurate, and I have added up all expenses and triple checked everything and it would appear all the data I have input into firefly is accurate.

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

```
Debug information generated at 2019-01-17 18:08:19 America/Kentucky/Louisville for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.14-1+ubuntu14.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-01-31 23:59:59 |
| Session first | 2019-01-02 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
```

**Bonus points**
Earn bonus points by:

- Add a screenshot
Dashboard
![dashboard](https://user-images.githubusercontent.com/6540217/51354958-6dff5a00-1a83-11e9-93d2-488cce8cac9e.PNG)
Assetts Page
![assetts page](https://user-images.githubusercontent.com/6540217/51354980-853e4780-1a83-11e9-8ad1-1301b622df3e.PNG)
Reports Page
![reports](https://user-images.githubusercontent.com/6540217/51354988-8bccbf00-1a83-11e9-80b3-783dd49735f5.PNG)
Dashboard Graph
![graph](https://user-images.githubusercontent.com/6540217/51355360-f16d7b00-1a84-11e9-89f5-67b44647a993.PNG)

- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
It shows you the sum of your income and expenses in the current period.

**Comment by rrbailey89** [comment]
I get that, but what I don't understand is all the income and expenses match identically to what my bank reports, and there is a $3 discrepancy somewhere between what that dashboard shows and the assets page and my bank shows.

**Comment by JC5** [comment]
So in January, Firefly III has $3 too much somewhere, is that correct?

**Comment by rrbailey89** [comment]
Correct

**Comment by JC5** [comment]
Alright but remember. The "balance" thing only shows the amount you spent in January vs. the amount you earned in January. This could total to (example) 500,-.

If your bank account balance happens to be 504,- this is confusing but remember they're two different numbers.

**Comment by rrbailey89** [comment]
Its interesting and confusing I thought maybe I'd discovered a bug in the logic somewhere
