### ISSUE TITLE
change Account E-Mail

### ISSUE THREAD

**Issue by TheGammelgalopper** [firefly-iii/firefly-iii#2015]
I am running Firefly III version ???

I tried updating my account's email address. But somehow my mail configuration was invalid and I didn't get the confirmation mail....

But now I am in this weird state: I am logged out and can't log in with my old nor my new address. And there is no way to resend that confirmation email...

My mail config works now though....

**Comment by JC5** [comment]
In order to fix this, you must manually edit the `users` table. Change `blocked` to 0 and `blocked_code` to NULL.

**Comment by TheGammelgalopper** [comment]
Thanks! Worked fine!

For others to reproduce (keep in mind, that I only have one user):

1.  log in to mysql
2.  perform the following commands
```
USE firefly;
UPDATE users SET blocked_code='NULL';
UPDATE users SET blocked='0';
```

**Comment by JC5** [comment]
This will also work:
```
UPDATE users SET blocked_code=NULL;
```
