### ISSUE TITLE
Enhancement: order the accounts on the dashboard corresponding to their current balance

### ISSUE THREAD

**Issue by ndandanov** [firefly-iii/firefly-iii#2016]
**Description**
I think ordering the accounts on the dashboard corresponding to their current balance would be helpful.

A sorting functionality in the Asset accounts would also come in handy, as would having a sum of the current balances and balance differences of all accounts.

**Solution**
Let us have a look at some screenshots from the demo site.
![screenshot_2019-01-18_16-21-34](https://user-images.githubusercontent.com/17270267/51392636-58029f80-1b3e-11e9-9915-c2cb6f9faedc.png)

The first screenshots shows that on the selected date, the Cash wallet has higher current balance than the Checking Account. The tooltip legend is ordered in accordance with the alphabetical order of the accounts, as it is in the Asset accounts page:
![screenshot_2019-01-18_16-22-11](https://user-images.githubusercontent.com/17270267/51392639-5a64f980-1b3e-11e9-800c-f3b1ebafae04.png)

If we selected a date with different balance figures, the legend has the same order:
![screenshot_2019-01-18_16-21-19](https://user-images.githubusercontent.com/17270267/51392634-5507af00-1b3e-11e9-91f2-1ee8f48fdebb.png)

However, I think that it would be handier if the tooltip legend entries were ordered corresponding to their current balance and not to their name. So for the selected date in the third screenshot, the first entry would be Checking Account and the second - Cash wallet.

Perhaps a sorting functionality in the Asset accounts itself would also come in handy - then one could quickly see which accounts are high or low in balance.

A third idea would be to have a sum of the current balance and balance difference of all accounts in the Asset accounts page. That way, one can quickly see their current net worth, except that the net worth card on the dashboard adds all liabilities.

**What are alternatives?**
One can determine the relevant accounts by their color. In a setting with more than 6-8 accounts however, this can become less readable. The situation on the accounts page is similar - it is less readable at first glance when the number of accounts increases.

**Comment by JC5** [comment]
You can sort the asset account table by clicking on the table headers. The legend can’t be sorted I’m afraid due to limits in the library.

**Comment by ndandanov** [comment]
Many thanks and sorry for not checking all related previous issues. :)

**Comment by JC5** [comment]
No problem, there are a lot of them. ;)
