### ISSUE TITLE
Type error: Return value of FireflyIII\Http\Controllers\Controller::hasSeenDemo() must be of the type boolean, array returned

### ISSUE THREAD

**Issue by Wav3** [firefly-iii/firefly-iii#2017]
**Bug description**
I am running Firefly III version 4.7.9  
The following error message appears randomly after different actions (e.g. logging in with 2FA, saving a new transaction or go to the dashboard):

`Return value of FireflyIII\Http\Controllers\Controller::hasSeenDemo() must be of the type boolean, array returned`
![Error message](https://user-images.githubusercontent.com/6506725/51398933-04478480-1b45-11e9-9c95-846084664fa9.png)

Mostly if a action writes successfully to the database and Firefly III returns me to the correct page, but after the next action the error appears.
If i remove the cookies and web site data in my browser the issue dissapears.
When i only view the sites and get data, the error does not appear.

**Steps to reproduce**
Just doing random actions on Firefly III like

- logging in with 2FA
- saving a new transaction
- go to the dashboard after saving the preferences
- regenerade commandline token
- etc.

**Expected behavior**
Expected behavior is, that the error does not appear.

**Extra info**
Firefly III is hosted as a docker container with docker-compose.  
Docker version: 18.06.1-ce build e68fc7a
Docker-compose version: 1.17.1 build unknown
OS: independent (Tested on Android 8.0.0 and Windows 10 1809)
Browser: independent (Tested on Google Chrome 71.0.3578.99 on Android, Mozilla Firefox 64.0.2 on W10, Google Chrome 71.0.3578.98 on W10)

Debug trace of Firefly III:
```
Debug information generated at 2019-01-18 17:23:58 Europe/Amsterdam for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.13 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-12-31 23:59:59 |
| Session first | 2015-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, ldap, pdo_mysql, pdo_pgsql, sodium, tidy, zip |
```

**Comment by JC5** [comment]
That's pretty unique. Something is broken in your database. The function that sets this particular value is called twice.

```
app('preferences')->set($key, false);
app('preferences')->set($key, true);
```

So how it got to an array is beyond me. Could you enable [debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) and look for a debug message that starts like this?

```
Check if user has already seen intro with key
```

**Comment by JC5** [comment]
Alright, thanks. Assuming this is a recurring problem, check your `preferences` table and remove all entries that start with `shown_demo`. Then run the following command on the command line:

```
php artisan cache:clear
```

That will reset all demo popups but should get rid of the problem.

**Comment by Wav3** [comment]
Thanks for your help.

After removing all entries that starts with `shown_demo` and clearing the application cache, the problem seems to be fixed.  
Currently i cannot force the error to occur.

**Just as a info for other users with the same issue:**
I've used the following MySQL command for clearing the `shown_demo` entries:
```mysql
DELETE FROM preferences WHERE name LIKE "shown_demo%";
```
