### ISSUE TITLE
Please add configuration import correction for Triodos

### ISSUE THREAD

**Issue by Ircghost** [firefly-iii/firefly-iii#2020]
**Description**
Triodos offers its information in the following format: 

Boekdatum | Rekeningnummer | Bedrag | Debet / Credit | Naam tegenrekening | Tegenrekening | Code | Omschrijving
-- | -- | -- | -- | -- | -- | -- | --

The amount (bedrag) is always positive, and then identified being either debit or credit in the next column. I have seen that there are correction possibilities for ING & Rabobank in Firefly. I have tried to use them, unfortunately those don't work (or maybe I don't know how to use it properly). 

**Solution**
Would it be possible to add the functionality to use the column data of [Debit / Credit] to determine if the value should be positive or negative?

**What are alternatives?**
Currently I would have to manually change the transactions to a deposits in Firefly or change it in Excel prior to uploading.

Thank you in advance!

**Comment by JC5** [comment]
Could you share an example of either?
