### ISSUE TITLE
How use API?

### ISSUE THREAD

**Issue by lucaspaulino** [firefly-iii/firefly-iii#2021]
Are there any examples of using the API in PHP? I do not know how to send an authentication, etc. A practical example in PHP would help me a lot.

Thank you for helping me.

**Comment by JC5** [comment]
None for the Firefly III API specifically, but you won't need them. The API uses OAuth2 and there are  tons of libraries and examples out there that explain to you how to connect to one of those.

Once you're connected the API docs for Firefly III can tell you what each endpoint does and what to expect as return data.


Links:
* http://oauth2-client.thephpleague.com/
* https://docs.firefly-iii.org/en/latest/api/start.html
* https://api-docs.firefly-iii.org/

**Comment by lucaspaulino** [comment]
I did not understand ... For example, this documentation:

I wanted to send commands via CURL to insert transactions, etc. I'm not sure how it's done, how it's authenticated, etc. I know I can generate a validation KEY.

**Comment by JC5** [comment]
I’m sorry but I can’t teach you those things.

**Comment by lucaspaulino** [comment]
@JC5 I know you can send via requests. Only you need to authenticate, right? In the case, there are examples of json_encode with the necessary information, but there it does not speak what information has to send to validate.
