### ISSUE TITLE
API/Token question

### ISSUE THREAD

**Issue by overload08** [firefly-iii/firefly-iii#2022]
I am running Firefly III version 4.7..9

I need to use the API to push some data in Firefly.

How I can use my personal token ? Some exemple with curl ?

Thank's

**Comment by JC5** [comment]
Sorry, no specific example for Firefly III, but since it's all OAuth2 there's a lot that can be found online. The endpoints are described [in the docs](https://api-docs.firefly-iii.org/).

**Comment by overload08** [comment]
Hi ! I found how to use personal token with bearer authorization header. Thank's !
