### ISSUE TITLE
Additional Localisation

### ISSUE THREAD

**Issue by joaoclemencio** [firefly-iii/firefly-iii#2023]
I would like for Firefly to support additional Locales, specifically en-GB. I have it installed on my Yunohost instance but it's causing some issues due to lack of that locale.

Would this be just editing the [config file](https://github.com/firefly-iii/firefly-iii/blob/develop/config/firefly.php) and creating a new lang under resources?
If so, can I just do these and create a PR for it?

Thanks!

**Comment by JC5** [comment]
Yes, but it would also require adding translations specifically for en_GB. I have a thing on my list to make the locale setting separate from the language setting, but it could be a while before it's live.

**Comment by joaoclemencio** [comment]
I see, seems like there are a lot more dependencies on this. I'll see if I can change the yunohost locale, but would still be a good feature. Would you mind if I gave a shot at a PR, looking for mixes between language and locale, or do you think there's too much overall risk of breakage? Thanks

**Comment by JC5** [comment]
I think you could break a lot of things, but feel free to play around with it. I can't accept a PR at the moment, I'm working on a new layout as well so I'm not going for big changes at the moment.
