### ISSUE TITLE
API/Transactions

### ISSUE THREAD

**Issue by overload08** [firefly-iii/firefly-iii#2024]
**Bug description**
I am running Firefly III version 4.7.9

I can use the POST "/api/v1/transactions". When I try to POST somethink, I'm redirected to login page.
(GET is functionnal)

**Steps to reproduce**
What do you need to do to trigger this bug?

curl -v -H "Authorization: Bearer PERSONAL_TOKEN" -H "Content-Type: application/json" -X POST https://firefly.host/api/v1/transactions

**Expected behavior**
A JSON error

**Extra info**
Debug information generated at 2019-01-23 11:27:12 Europe/Paris for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.14-1+0\~20190113100742.14+stretch\~1.gbpd83c69 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-01-31 23:59:59 |
| Session first | 2019-01-23 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, intl, json, ldap, exif, msgpack, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache |

**Comment by JC5** [comment]
Try adding Accept: application/json to get the error back in JSON. It looks like you're token is bad, strangely enough.

**Comment by overload08** [comment]
Great ! It's ok for me ! Thank's !
