### ISSUE TITLE
Can't connect to PostgreSQL

### ISSUE THREAD

**Issue by chocoladisco** [firefly-iii/firefly-iii#2026]
I am running Firefly III from the latest Dockerfile.

**Description**
When I open the webpage for Firefly I get the following error:

```
SQLSTATE[08006] [7] invalid port number: "tcp://172.17.0.2:5432" (SQL: select "id", "name", "data" from "configuration" where "name" = is_demo_site and "configuration"."deleted_at" is null limit 1)
```

After installing telnet on the Docker container I can reach 172.17.0.2:5432 . So there should not be any network issue,

I run the Docker container with the following command:
```
docker run -d \
--name firefly \
--link db:db \
-v firefly_iii_export:/var/www/firefly-iii/storage/export \
-v firefly_iii_upload:/var/www/firefly-iii/storage/upload \
-p 80:80 \
-e FF_APP_ENV=local \
-e FF_APP_KEY=F2cCy4qyPove4vAwweJFQS42QuQmpnxP \
-e FF_DB_HOST=db \
-e FF_DB_NAME=firefly \
-e FF_DB_USER=USERNAME \
-e FF_DB_PASSWORD=PASSWORD \
-e FF_DB_CONNECTION=pgsql \
-e APP_DEBUG=true \
-e APP_LOG_LEVEL=debug \
jc5x/firefly-iii:latest
```

**Comment by JC5** [comment]
Yes that should do the trick. Not sure what else you could try to be honest.

**Comment by chocoladisco** [comment]
@JC5 the problem still exists though.

The DB server is setup using:

```
docker run -d -e POSTGRES_USER=USERNAME -e POSTGRES_PASSWORD=PASSWORD -e POSTGRES_DB=postgres --name db postgres:10
```

So I really wonder what the issue could be, as I can easily use the DB from another dockerized application.

**Comment by chocoladisco** [comment]
@JC5 somehow it seems like somewhere in the call stack the port argument for the DB connection is misused and instead of only getting 5432 it gets "tcp://172.17.0.2:5432"

**Comment by JC5** [comment]
Try setting FF_DB_PORT.

**Comment by chocoladisco** [comment]
@JC5 funnily enough I was able to solve the problem by deleting the port config in both the .env.docker and the config/database.py files.

Setting FF_DB_PORT to 5432 doesn't seem to solve the problem. As somehow the ENVVAR DB_PORT ist set to: "tcp://$FF_DB_HOST:$FF_DB_PORT" but no idea where.

Seems to be a bug in the program.

**Comment by JC5** [comment]
Strange. There is no mention of anything like that in my code, nor in the associated libraries. And if there was, you wouldn't be the first person to run into this issue. The docker image has like a million pulls.

I'll do some research but I can't promise much.

**Comment by chocoladisco** [comment]
If I set the DB_PORT variable in the docker run explicitly the program doesn't even seem to start. Really strange.
