### ISSUE TITLE
Fail to create account by Account api , instead of seeing error info by redirect to "/"

### ISSUE THREAD

**Issue by snakewa** [firefly-iii/firefly-iii#2027]
I am running Firefly III version 4.7.9

**Description**
I found that it is difficult to see what's error of creating account with API. Such as, I try to create an account with the same name or same account number. Instead of letting me know , the API just redirect it to / and immediately redirects to /login .

Is it by designed ?

**Steps to reproduce** 
try to POST to /api/v1/accounts twice:
{
  "name": "My checking account",
  "type": "asset",
  "iban": "GB98MIDL07009312345678",
  "bic": "BOFAUS3N",
  "account_number": "7009312345678",
  "opening_balance": -1012.12,
  "opening_balance_date": "2018-09-17",
  "virtual_balance": 1000,
  "currency_id": 12,
  "currency_code": "EUR",
  "active": true,
  "include_net_worth": true,
  "account_role": "defaultAsset",
  "credit_card_type": "monthlyFull",
  "monthly_payment_date": "2018-09-17",
  "liability_type": "loan",
  "liability_amount": 12000,
  "liability_start_date": "2017-09-17",
  "interest": 3,
  "interest_period": "monthly",
  "notes": "Some example notes"
}

**Comment by JC5** [comment]
Make sure you add a “Accept: application/json” header to your request.
