### ISSUE TITLE
Please add configuration import correction for Triodos

### ISSUE THREAD

**Issue by Ircghost** [firefly-iii/firefly-iii#2031]
**Description**
Triodos offers its information in the following format:

Boekdatum | Rekeningnummer | Bedrag | Debet / Credit | Naam tegenrekening | Tegenrekening | Code | Omschrijving
-- | -- | -- | -- | -- | -- | -- | --
 | 12-1-2019 | -- | "1.005,00" | Debet | -- | -- | ET | --
 | 12-1-2019 | -- | "1.005,00" | Credit | -- | -- | ET | --

The amount (bedrag) is always positive, and then identified being either debit or credit in the next column. I have seen that there are correction possibilities for ING & Rabobank in Firefly. I have tried to use them, unfortunately those don't work (or maybe I don't know how to use it properly).
Solution
Would it be possible to add the functionality to use the column data of [Debit / Credit] to determine if the value should be positive or negative?
What are alternatives?
Currently I would have to manually change the transactions to a deposits in Firefly or change it in Excel prior to uploading.

in response to your question earlier to give examples, do you mean examples of the ING / Rabo corrections? I don't know how I could share those as it's in the import correction rule set.

Import > select file etc > in the dropdown of the column mapping choose rabobank debet correction.

Thank you in advance!

_p.s. started a new one since I was too slow to respond in the other ticket and you closed it._

**Comment by JC5** [comment]
Thanks for sharing the values. I’ll pick it up for the next release :+1:

**Comment by JC5** [comment]
The new release will contain this option that also supports Triodos.

![screenshot 2019-01-28 at 18 35 50](https://user-images.githubusercontent.com/5889984/51854683-9dd41a80-232b-11e9-967f-795d3726b26f.png)

**Comment by DaantjeG** [comment]
Thanks for picking this up, I was also having issues with this. Unfortunately I did need to make one more fix as I was getting the following error:
[2019-04-01 21:14:17] local.ERROR: The import routine crashed: ImportTransaction cannot handle role "generic-debit-credit" with value "Debet"  
[2019-04-01 21:14:17] local.ERROR: #0 ********\firefly-iii\app\Support\Import\Routine\File\ImportableCreator.php(66): FireflyIII\Support\Import\Placeholder\ImportTransaction->addColumnValue(Object(FireflyIII\Support\Import\Placeholder\ColumnValue))

I had to add 'generic-debit-credit' to the modifiers (with rabobank and ing) just above this error at line 198.
```
$modifiers = ['rabo-debit-credit', 'ing-debit-credit', 'generic-debit-credit'];
if (\in_array($role, $modifiers, true)) {
        $this->modifiers[$role] = $columnValue->getValue();

        return;
}
```

**Comment by JC5** [comment]
Thanks, completely missed that one. I'll pick it up as well.

**Comment by Falconne** [comment]
I was trying to import a CSV which uses a Credit/Debit column with values 'C' and 'D' respectively and am getting an error. I just wanted to check if the reason is because of what's mentioned above and if so I'll wait for a new update. I was using the "Generic bank debit/credit" mapping for the column and the error I got was:

`Job could not be started or crashed: The import routine crashed: ImportTransaction cannot handle role "generic-debit-credit" with value "D"`
