### ISSUE TITLE
How to correct the current account(s) balance?

### ISSUE THREAD

**Issue by uzantonomon** [firefly-iii/firefly-iii#2032]
I am running Firefly III version 4.7.9

Hi there!
I've started to use your software and I'm really liking it! Everything seems to work just fine, great job!
I've got one just one question, for now:

- It's possible to correct the current balance on one account? For example, I've got my wallet account and sometimes I forgot to add one or two expenses to it. Is there a way to "update" the current balance without adding an extra transaction?

I've read about the "reconcile" feature, but I'm not sure if that's what I'm looking for.
Thanks for your work, and you attention!

**Steps to reproduce** 
(if relevant of course)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
No, the balance can only be modified by transactions. You could edit the opening balance, but that would probably change your balance over the entire time range of the account.

**Comment by uzantonomon** [comment]
Thanks for the fast answer, @JC5 .
