### ISSUE TITLE
Longitude in Tags

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2033]
**Bug description**
I am running Firefly III from commit d905849b71ba8c58f56ecbc67a8825c4b46243e4

When adding a longitude larger than 90 from the API, it fails saying `The longitude may not be greater than 90`. This should not happen as longitude has a maximum of 180. 

https://stackoverflow.com/questions/15965166/what-is-the-maximum-length-of-latitude-and-longitude

**Comment by JC5** [comment]
Oh lol I thought it was 90 as well. I’ll fix it for 4.7.10.

**Comment by emansih** [comment]
Thanks.

P.S. what does the `size` and `relative` mean in tag cloud?

**Comment by JC5** [comment]
The size is simply the monetary amount, added all together. The relative value is the percentage compared to the highest tag. So if the highest tag is 430,-, it will get relative=1. Another tag with 215,- will get 0.5, etc.

**Comment by JC5** [comment]
Will be fixed in the next release.
