### ISSUE TITLE
Bulk Edit In "Table" Format

### ISSUE THREAD

**Issue by howlowck** [firefly-iii/firefly-iii#2034]
**Description**
Please describe your feature request:
I would like to edit the descriptions of a list of transactions (either through bulk edit or another view).

**Solution**
It would be great to have a feature will the user can set various attribute of a list of transactions, things like "description", "budget", "category", all at once.  Since Bulk Edit seems to be setting multiple transactions to one value, maybe something like a Table Edit is better.

**What are alternatives?**
Alternative solutions: 
* I'm editing the descriptions on each transaction one by one. However this is really time-consuming because there is no easy way to "advance" to the next transaction.
* I could add a new description column in the csv before I import.  However, since I have a lot of "description-driven" rules, if I fat finger a description, it will miss the trigger.

**Additional context**

**Comment by howlowck** [comment]
Thank you! You are right!
Side note, I noticed that in table edit:
* rules do not get triggered
* the description fields do not have the searchable auto-complete

Are those missing features or intended behavior?

**Comment by JC5** [comment]
I’ll have to check it out, thanks for letting me know.

**Comment by JC5** [comment]
Both are fixed in the next release.
