### ISSUE TITLE
Spacing between labels of the x axis of charts in the dashboard

### ISSUE THREAD

**Issue by wangongtsen** [firefly-iii/firefly-iii#2035]
**Description**
While looking at the budget and category charts presented on the dashboard, not every bar is labeled. Depending on how many budgets or categories I have set up, only the name of every other or every third bar is displayed even though there would be enough space to squeeze in twice as many. So one has to hover above a bar to know what budget or category it's associated with, what makes it harder to get a quick overview.

**Solution**
Reduce the minimal horizontal spacing between labels of the x axis of budget and category charts to at least half of what it is right now.
I believe the gain in information you get at a glance is well worth a slight overloading of the arrangement.

**Comment by JC5** [comment]
The library limits the number of ticks at 12. It's a good balance.
