### ISSUE TITLE
What is the real cost of Salt Edge?

### ISSUE THREAD

**Issue by jtbayly** [firefly-iii/firefly-iii#2036]
I really can't see myself using this program unless I can find a way to import transactions from my various accounts. 

I see in the documentation, you wrote:

> "Conversely, each user must request test access to the Spectre API and eventually pay for access to the API."

Currently the Saltedge website says:

>  test the integration with 100 live connections for free.

After that, apparently the cost is $500/month. My question is whether the 100 live connections is per month or total. I won't bother if that's the total number of connections I can ever make to my banks & credit cards, as I'd burn through it in a couple of months at most. 

Thanks for your help.

**Comment by JC5** [comment]
One connection == one bank. So when you bank at two banks, you will use at most 2 connections.

**Comment by jtbayly** [comment]
Thanks. That changes everything.
