### ISSUE TITLE
Extra default reports

### ISSUE THREAD

**Issue by sachawolf** [firefly-iii/firefly-iii#2037]
Under reports there are a couple of Quick links to default financial reports and transaction history overviews.
The option currently are for current month, current year and all-time.

Because Firefly-III is configured to give financial overview per calendar month (instead of per income month) it would make things easier if there is also a Quick link to the previous month. This will quickly show the last full month.

Link to current month: https://fireflyinstall/8082/reports/default/7,6,8,5/currentMonthStart/currentMonthEnd

Suggestion for link to last month:
https://fireflyinstall/8082/reports/default/7,6,8,5/lastMonthStart/lastMonthEnd

This could also be added for the transaction overviews, and for last year.

**Comment by JC5** [comment]
That makes sense, and should not be difficult to add. Thanks for the suggestion!

**Comment by MacPaille** [comment]
In the software I was using before migrating to FF I had the possibility to save a custom report generated so it was easier than selecting specific timeframe each time I want that report generated.
For example report from 25 of the last month to the 24 of this month.

Do you think it would be possible to have such possibility?

**Comment by JC5** [comment]
I'll have to see what could work. I'm not a fan of the custom time ranges. Is the 25th the day you get paid, by any chance? :wink:

**Comment by JC5** [comment]
I've added the "last month" things (the docs will update momentarily but no custom day-of-month feature, I'm afraid.
