### ISSUE TITLE
Wrong currency output when using summary API

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2038]
Hi, I understand that summary API(/api/v1/summary/basic) is not public yet but I went to try it anyway. There seems to be a parsing error caused by UTF8(?) when displaying euro dollar symbol. This is the sample output: 

```
{
    "key": "balance-in-EUR",
    "title": "firefly.box_balance_in_currency",
    "monetary_value": -321,
    "currency_id": 1,
    "currency_code": "EUR",
    "currency_symbol": "\u20ac",
    "currency_decimal_places": 2,
    "value_parsed": "\u20ac-321.00",
    "local_icon": "balance-scale",
    "sub_title": "\u20ac-321.00 + \u20ac0.00"
  }
```

**Comment by JC5** [comment]
It takes the value straight from the database. I’ll check what’s happening at other end points. /currencies/1 doesn’t have this I assume?

**Comment by emansih** [comment]
currency endpoint does not have this issue. seems to be isolated to summary endpoint
```
 {
            "attributes": {
                "name": "Euro",
                "code": "EUR",
                "symbol": "€",
           }
```

**Comment by JC5** [comment]
Cool, thanks for verifying. I’ll check it out.

**Comment by emansih** [comment]
> I'm seeing this in Postman btw, the Raw tab.

Ah crap. That's why....
