### ISSUE TITLE
Font problems when using Russian locale (Firefox)

### ISSUE THREAD

**Issue by bykidi** [firefly-iii/firefly-iii#2040]
**Bug description**
I am running Firefly III version 4.7.9

Bug related with font that used in certain places in FireFly, cyrillic text leads to what you can see on screenshot

**Steps to reproduce**
Switch to Russian

**Extra info**
Debug information generated at 2019-02-01 12:28:12 Europe/Minsk for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.14-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-02-01 00:00:00 |
| Session end | 2019-02-28 23:59:59 |
| Session first | 2019-01-02 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, json, ldap, exif, mysqli, odbc, pdo_mysql, PDO_ODBC, Phar, posix, readline, recode, shmop, SimpleXML, soap, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache |

![default](https://user-images.githubusercontent.com/1337953/52115364-80e76200-261f-11e9-8219-6e67c64fe815.png)

**Comment by JC5** [comment]
Only thing I can think of is that the Russian translation files are not stored as UTF8.

**Comment by bykidi** [comment]
![default](https://user-images.githubusercontent.com/1337953/52123496-586b6200-2637-11e9-9f6b-6abcaa9cba75.png)

**Comment by JC5** [comment]
I see. Then it's probably the font. I'll check it out.

**Comment by JC5** [comment]
The font I'm using doesn't support all glyphs: https://github.com/adobe-fonts/source-sans-pro

Some browsers will automatically use the next font (Arial) but some browsers won't. There's not much I can do I'm afraid. I'm keeping an eye on the font though: since it is included with Firefly III I can update quickly.

I know that it seems to work fine in Firefox.

<img width="1422" alt="screen shot 2019-02-02 at 05 49 29" src="https://user-images.githubusercontent.com/5889984/52160161-12061980-26b0-11e9-8b10-1de45a36c711.png">
