### ISSUE TITLE
Authentication in Safari not working correctly

### ISSUE THREAD

**Issue by bernhardbauer** [firefly-iii/firefly-iii#2042]
I am running Firefly III version 4.7.9 from the official docker image behind an Apache Proxy

**Description**

I tried to log into my firefly instance from Safari Browser (v12.0) on macOS but firefly has an extremely strange behavior. Sometimes I am able to login, and will see the first page which loads after login (e.g. dashboard if I have been redirected to login from dashboard), though the dashboard would not display any data as all async requests (revenue, bills, net-worth, etc.) would return a "401 Unauthorized".

Other times I am not even able to login and will always be redirected back to the login page.

I have figured out that the session cookies which are set by firefly often contain a specific path. Most of the times some cookies had the path `/v1/jscript/ ` assigned to them.

Image of the Cookies set by firefly: https://imgur.com/a/q45AkqE

Safari Console
```
[Error] Refused to execute https://firefly.apps.xxx/v1/jscript/variables?ext=.js&v=4.7.9 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] ReferenceError: Can't find variable: currencySymbol
	(anonymous function) (app.js:1:113219)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (frontpage, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (frontpage, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (expense, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (frontpage, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (balance, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (revenue, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (bills, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (frontpage, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (available, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (piggy-banks, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (net-worth, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (error.png, line 0)
```

Logging in from a Google Chrome browser on macOS interestingly worked.

**Extra info**

| Browser | OS | Working? |
| --- | --- | --- |
| Safari v12.0 | macOS | No |
| Safari | iOS | No |
| Google Chrome | macOS | Yes |

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.13 |
| Display errors | Off |
| Session start |  |
| Session end |  |
| Session first |  |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 3 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, ldap, pdo_mysql, pdo_pgsql, sodium, tidy, zip |

**Comment by JC5** [comment]
I see that there are different sets of cookies set by your installation. Like you say, some have a path while others do not. And some have a dot in front of the URI and others do not. Firefly III does not set cookies with a specific path. It also doesn't set the same cookie three times with different values. 

Firefly III only sets one kind of cookie. Its characteristics are set in configuration and can be overridden if you want to by overruling these values using `-e COOKIE_PATH="xxx"` if you so prefer.

```
COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false
```

There's a good chance that Chrome merges these cookies or ignores others. But I'm getting the strong impression your Apache proxy is editing cookies.

**Comment by bernhardbauer** [comment]
Thanks for your amazingly fast response!

I explicitly set the cookie options as you provided and safari still does not want to cooperate until I have been to a point where it has gone completely crazy (https://imgur.com/c1pPFWt).

As I have investigated the Issue I also saw that the cookie path should always be set to / in the firefly code but unfortunately somehow it does not happen in Safari.

**Here is my apache vhost**
```
<VirtualHost *:443>
    ServerName firefly.apps.xxx
    ServerAdmin admin@xxx

    RequestHeader set X-Forwarded-Proto "https"
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass "/" "http://172.16.1.101/"
    ProxyPassReverse "/" "http://172.16.1.101/"

    SSLEngine on
    SSLProxyEngine On
    SSLCertificateFile /etc/letsencrypt/live/xxx/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/xxx/fullchain.pem
</VirtualHost>
```

**And here is the docker run command I am using to run firefly**
```
docker run -d \
    --name firefly-iii \
    --restart always \
    --network internal \
    --ip 172.16.1.101 \
	--cpus="4" \
	--memory="8g" \
	--memory-swap="8g" \
    -v firefly-iii-export:/var/www/firefly-iii/storage/export \
    -v firefly-iii-upload:/var/www/firefly-iii/storage/upload \
    -e FF_APP_ENV=local \
    -e FF_APP_KEY=xxx \
    -e FF_DB_HOST=xxx \
    -e FF_DB_NAME=xxx \
    -e FF_DB_USER=xxx \
    -e FF_DB_PASSWORD=xxx \
    -e FF_FORCE_SSL=true \
    -e COOKIE_PATH="/" \
    -e COOKIE_DOMAIN= \
    -e COOKIE_SECURE=false \
    -e TRUSTED_PROXIES=** \
    jc5x/firefly-iii:latest
```

**Comment by bernhardbauer** [comment]
I have just tried what happens if I open firefly in a private tab in Safari and it works. My best guess would be that Safari is doing something fishy with the cookies in the regular browsing mode...

**Comment by JC5** [comment]
Would a simple clearing of your browser cache help?

**Comment by bernhardbauer** [comment]
Already tried clearing the cache multiple times, restarted safari, restarted my mac, but no luck. I tried again to see if something changed and interestingly without any further changes it worked again.

Thank you very much for your help!
Keep up the great work.

Kind regards
Bernhard

**Comment by JC5** [comment]
Thank you, just keep me posted if something changes. I'll close this one: feel free to open a new one or reopen the current issue.
