### ISSUE TITLE
 Recurring transactions: Next expected transaction not listed on a weekend

### ISSUE THREAD

**Issue by wangongtsen** [firefly-iii/firefly-iii#2043]
**Bug description**
I am running Firefly III version 4.7.9

If a recurring transaction would normally already have happened, but is delayed due to a Weekend rule, this specific transaction won't be listed under _Expected transactions_.

**Steps to reproduce**
This has to be tested on a weekend and the recurring transaction has to be set up the day before or earlier.
Example: Second of the month is a Saturday and a recurring transaction repeats every month on the second day, but will be delayed to the next Monday if the second happens to be on a weekend. On this weekend (in our case second and third of the month) the first date on the list of _Expected transactions_ will be next month's occurrence.

**Expected behavior**
Display this month's transaction on Monday.

**Extra info**
For future repetitions the reschedule is displayed properly. Just not on the current weekend.

**Comment by JC5** [comment]
Nice find. It will always skip today, and therefore will skip Monday's entry. I've fixed it.
