### ISSUE TITLE
Textual: Dutch debiteuren introduction incorrectly names "crediteuren"

### ISSUE THREAD

**Issue by SixFive7** [firefly-iii/firefly-iii#2044]
**Bug description**
I am running Firefly III version 4.7.9

When starting with Firefly we get the introduction text on the empty debiteuren page. This text incorrectly uses the term Crediteuren where it should name Debiteuren. Probably a small oversight during copy paste.

**Steps to reproduce**
Start new Firefly administration. Set interface to Dutch. Go to the Debiteuren page.

**Expected behavior**
"Debiteuren worden automatisch aangemaakt als je transacties aanmaakt, maar je kan ze ook met de hand maken. Zoals nu:"
Instead of...
"Crediteuren worden automatisch aangemaakt als je transacties aanmaakt, maar je kan ze ook met de hand maken. Zoals nu:"

![image](https://user-images.githubusercontent.com/6650122/52164255-8eb7e880-26ee-11e9-9130-35be2fff7341.png)

**Comment by JC5** [comment]
Nice find, I've fixed this in the [translation files](https://crowdin.com/translate/firefly-iii/142/en-nl#q=hand).
