### ISSUE TITLE
Bunq import import routine crash

### ISSUE THREAD

**Issue by sachawolf** [firefly-iii/firefly-iii#2049]
**Bug description**
I am running Firefly III version 4.7.10

**Steps to reproduce**
After upgrading to a docker container with version 4.7.10 trying to import from Bunq I receive the following error:
![image](https://user-images.githubusercontent.com/1969576/52178292-e462c280-27cc-11e9-9d60-7dab892934f4.png)

This is after decrypting the database using the commands shared in a different issue.

The error itself points to a datarow with ID 19 in the Preferences table, which shows this:
![image](https://user-images.githubusercontent.com/1969576/52178311-1ecc5f80-27cd-11e9-8518-0d00a739fa34.png)

**Expected behavior**
New data from Bunq.

**Extra info**
Debug information generated at 2019-02-03 15:04:15 UTC for Firefly III version **4.7.10**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.10 |
| FF API version | 0.9.1 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.14 |
| Display errors | Off |
| Session start | 2019-02-01 00:00:00 |
| Session end | 2019-02-28 23:59:59 |
| Session first | 2015-04-14 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Vivaldi/2.2.1388.37 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Comment by JC5** [comment]
Nice find, I’ll check it out. I think it’s related to the new database structure.

**Comment by sachawolf** [comment]
> Nice find, I’ll check it out. I think it’s related to the new database structure.

That would be my guess as well.

**Comment by JC5** [comment]
OK, is this error repeatable? If so, could you check your log files for the stack trace? I can't repeat this in the bunq import.

**Comment by JC5** [comment]
Never mind, I found it.

**Comment by sachawolf** [comment]
The current (at time of writing) autobuild develop-amd docker container contains the fix. Imports are working again.

If I am reading the fix correctly, you are now forcing an update when that Preference has data but it somehow gives null back?

To be fair, I am not a developer, so I am probably way off! :D

**Comment by JC5** [comment]
In previous versions, it was possible to set an empty preference, because it would be converted to the literal string "null" and stored encrypted. In the new release, empty values are not converted and not encrypted, leading to database errors. 

Returning an empty Preference object instead of an actual object (and deleting the actual object if necessary) is safe, because the empty Preference results in the same empty value as the previous version would have.

**Comment by JC5** [comment]
This should be fixed with the current release.
