### ISSUE TITLE
"firefly:decrypt-all" is not defined

### ISSUE THREAD

**Issue by bigpness** [firefly-iii/firefly-iii#2050]
I am running Firefly III version 4.7.9, attempting upgrade to 4.7.10

**Description**
Attempting composer "create-project" upgrade process on a virtual server, the **php artisan firefly:decrypt-all** command throws the following error:

> Command "firefly:decrypt-all" is not defined.
> 
>   Did you mean one of these?
>       firefly:apply-rules
>       firefly:create-export
>       firefly:create-import
>       firefly:cron
>       firefly:decrypt-attachment
>       firefly:encrypt-file
>       firefly:instructions
>       firefly:scan-attachments
>       firefly:start-import
>       firefly:upgrade-database
>       firefly:use-encryption
>       firefly:verify

**Extra info**
 

Debug output:
Debug information generated at 2019-02-03 11:25:09 America/Los_Angeles for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.12 |
| Display errors | Off |
| Session start |  |
| Session end |  |
| Session first |  |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | cgi-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Vivaldi/2.2.1388.37 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, bcmath, calendar, ctype, curl, dom, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, mbstring, mysqlnd, PDO, Phar, posix, SimpleXML, soap, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader |

**Bonus points**
James, you're the best, and I appreciate all of your hard work!

**Comment by JC5** [comment]
Thanks, I appreciate the compliments!

The command "decrypt-all" is only available in the new installation, 4.7.10. So make sure that's the directory where you call the command.

Make sure you have a backup, of course.

**Comment by bigpness** [comment]
Did I mention I'm a moron? Time to clean up my directories. Thank you!
