### ISSUE TITLE
Import export for rules

### ISSUE THREAD

**Issue by shindocha** [firefly-iii/firefly-iii#2051]
Please describe your feature request: Ability to import and export user created rules under Money management.   

- I would like Firefly III to do have ability to import and export user created rules under Money management.

**Solution**
- Currently as I am running self-hosted app chances are many other users, home lab goes through upgrades and issues while trying new things so docker save us there very much plus persistence volumes and worst comes is there no app level backup for firefly-iii, transactions can re-imported using api / manually imports, if same could be done for rules and once imported it just have to be re-run that would help to moves between upgrades or recovery of this self-hosted instances very seamless experiences. 

Many thanks for the brilliant app and continues developments.

**Comment by JC5** [comment]
Thanks for the compliments!

Firefly III will not feature app level backups. So I'm sorry, but this feature will not be added.
