### ISSUE TITLE
4.7.9 to 4.9.10 upgrade db failure

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#2053]
**Bug description**
I am running Firefly III version 4.7.9, and my problem is:

Upgrading to v4.7.10 results in the following errors:

In Connection.php line 664:

  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1 (SQL: insert into `rules` (`user_id`, `rule_group_id`, `title`, `description`, `order`, `active`, `upd
  ated_at`, `created_at`) values (1, 9, Auto-generated rule for bill "eyJpdiI6IkV4NU1NaGlDeU1EXC83Ymh5c3J2SExBPT0iLCJ2YWx1ZSI6ImlvNHpTK1hxTFFhVTlVcDNGekE5WW13eTZUeGNNdUdQTTJPVjZScXdKM2ZVU1dpMDBoXC9m
  K3ErZ1FTaWZiOFczIiwibWFjIjoiNDNjNTczNGM5N2FlMTc4MDgyMDhlMjU3NzgyNzEyM2Q3ZDA4N2UwZDIyZDdiN2RkYjRiNTMxODg4NWY3Yjk2ZSJ9", This rule is auto-generated to try to match bill &quot;eyJpdiI6IkV4NU1NaGlDeU
  1EXC83Ymh5c3J2SExBPT0iLCJ2YWx1ZSI6ImlvNHpTK1hxTFFhVTlVcDNGekE5WW13eTZUeGNNdUdQTTJPVjZScXdKM2ZVU1dpMDBoXC9mK3ErZ1FTaWZiOFczIiwibWFjIjoiNDNjNTczNGM5N2FlMTc4MDgyMDhlMjU3NzgyNzEyM2Q3ZDA4N2UwZDIyZDdiN2
  RkYjRiNTMxODg4NWY3Yjk2ZSJ9&quot;., 12, 1, 2019-02-04 17:59:05, 2019-02-04 17:59:05))

In PDOStatement.php line 119:

  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1

In PDOStatement.php line 117:

  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1

I have a backup of the db from before the upgrade, what are the correct steps to restore to 4.7.9?

**Comment by JC5** [comment]
Depending on how you installed Firefly III, please follow the upgrade instructions. Make sure you run the “decrypt-all” command. 

http://docs.firefly-iii.org/en/latest/installation/upgrading.html

**Comment by ragnarkarlsson** [comment]
Ah, looks like the script I had is a bit outdated on the upgrade commands. I'll try that again, restore completed in the meantime!
