### ISSUE TITLE
Allow rules to change "opposing" account

### ISSUE THREAD

**Issue by kaysond** [firefly-iii/firefly-iii#2054]
At the moment I've added a bunch of rules to automatically set the expense accounts for my credit card transactions since the only provided info in my CSV downloads is "Description". However, these rules break on returns (i.e. deposits into my credit card asset account).

This is happening because the only actions available in the rules are "Set source account to..." and "Set destination account to...". So my rule is failing because its incorrectly assuming the transaction is a withdrawal and its trying to set the source account to an asset account that doesn't actually exist because its in fact an expense account.

My current workaround is to have two rules for each vendor: one is for withdrawals (set destination), and one is for deposits (set source). It would be nice to have an action that is "Set opposing account to...", similar to how it works during file import. If the transaction is a deposit, it will automatically set the source. If the transaction is a withdrawal, it will automatically set the destination. I don't think this even requires an argument to be passed since firefly by default treats the asset account as the "master".

**Comment by JC5** [comment]
For the time being, I going leave it like it is right now. The added simplicity makes it easier to understand for new users. It makes the rules less flexible but more predictable. I hope you see why I'm doing it :)

**Comment by kaysond** [comment]
Wouldn't it be simpler to have a single rule instead off two? As a brand new user I was actually quite confused why my rule wasn't working. I ended up having to dig through the log to find out about the subtlety of this behavior. I don't think it was very clear, especially given how the import process uses "opposing accounts". As that was my first experience with Firefly, I was expecting the rules to behave similarly. Food for thought...
