### ISSUE TITLE
4.7.10: cronjobs and docker

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#2057]
I just read the release notes for 4.7.10 and was a bit supprised about the the removal of the cron job. Before, the docker image was a complete, self-contained application which needed no external interaction to function properly. I can't really see how the cron job inside the image contradicts docker's rationale of running a single service. 

However...
what would be the preferred way to set up the cron job now?
1. manually edit the container? - Don't think so. Would require interaction after every update
2. IFTT? - This might not be suitable for everyone. I'd rather not depend on an external service when there is a better alternative.
3. Add cron-job to the docker's host system? - That would contradict the separation of concerns as well, because I don't want the container to depend on the host that it is running on
4. Use a second service inside docker-compose that hosts the cron-job - Probably the best option among the mentioned, but also requires manual setup and testing. As the service probably needs the authentication token for the cron-endpoint we also get some kind of "egg vs. chicken" problem here upon the very first usage

What do you suggest? Am I missing something here?

**Comment by JC5** [comment]
No you're not missing anything. There's no ready-made setup for the cron job anymore. I removed it from the image because the cron job service, the supervisor service and the webservice were making the image unnecessarily complex. 

I guess the best alternative is a second docker image calling the first, but it's not particularly perfect. And indeed without the authentication token it's pretty tricky to set up.

**Comment by NiFNi** [comment]
I have a node-red instance running (https://nodered.org/). Can be used as a selfhosted alternative to IFTTT. I use a simple workflow triggering every day which fires the GET request to start the cron and sending the result as mail. Might be an alternative for people not wanting to use IFTTT.

**Comment by skuzzle** [comment]
It is probably easier to build an `alpine` based image containing curl and a cron tab. This image can then be run in the same docker-compose scenario. I have done something similar for my daily DynDNS renewal. Maybe I find some time on the weekend to experiment

**Comment by NiFNi** [comment]
For sure. But you would need to spin up another container for that and you might find node-red insteresting for other stuff aswell. If not just a simple "cron" container is probably the best solution.

**Comment by Ryonez** [comment]
So... if I understand right, we now **have** to trigger externally?

This does make it more complicated for me.

There is a docker image that does a decent supervisor: https://github.com/just-containers/s6-overlay

This systems has been used heavily by https://github.com/linuxserver/ 
I use a number of their images with unraid and they are straight up amazing. Would you be willing to consider looking at over it and seeing it it'd be useful for you here?

**Comment by Ryonez** [comment]
This seems to have been completely broken. Even with the API saying it's fired the cron trigger, recurring transactions aren't actually processed.

**Comment by JC5** [comment]
Wait, is that another issue altogether?

**Comment by Ryonez** [comment]
Not entirely sure, as I wasn't using this until recently, after cron had been removed from the image. If the issue persists after the .12 update for me I'll open a issue specifically for it.

**Comment by bestlibre** [comment]
As a quick way to solve this, with the use of docker-compose it is possible to add this service definition : 
```
cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget https://<FIREFLYURL>/cron/run/<TOKEN>\" | crontab - && crond -f -L /dev/stdout"
```
For this to work the token is obviously needed. I have solve this by first starting the stack without the cron service to get the token and then add the service to the stack. 

Something could probably be done with a shared volume to pass the token from the main app to the cron service.

**Comment by JC5** [comment]
I think an easy solution would be to allow token-less cron calls when a special ENV var is set (which you can do from the docker-compose.yml file).

Something like `ALLOW_OPEN_CRON` which would allow the token `notsecret` to be used to call the cron endpoint. This can be combined with the service definition from @bestlibre.

Should fix it, right?

**Comment by bestlibre** [comment]
Should be good! One nice thing to have would be to be able to listen for cron on another port. This port could then be internal only.

If it's not possible I could always redirect the cron webhook to the home page on my reverse proxy.

**Comment by Skaronator** [comment]
You can also simply create a container if you don't use docker compose:

```
docker create --name=Firefly-Cronjob -e "FIREFLY_IP=192.168.178.5:5100" -e "FIREFLY_TOKEN=f6atfhio8uajgopihjp0qw9iohej0" alpine sh -c "echo \"0 3 * * * wget $FIREFLY_IP/cron/run/$FIREFLY_TOKEN\" | crontab - && crond -f -L /dev/stdout"
```
