### ISSUE TITLE
How to store transactions for liabilities that are also bills?

### ISSUE THREAD

**Issue by rrbailey89** [firefly-iii/firefly-iii#2059]
Maybe I'm over thinking it, but I have liabilities (car payments) that are also technically Bill's, and I have rules to mark the transactions as such, how should I be inputting these transactions, withdrawals, transfers or deposits? So that the bill is registered by the rule and the transaction is marked as a bill and the liability balance reflects a change.

**Comment by JC5** [comment]
You can't, not yet. You can read more about this in https://github.com/firefly-iii/firefly-iii/issues/1956.
