### ISSUE TITLE
Documentation translated

### ISSUE THREAD

**Issue by jinformatique** [firefly-iii/firefly-iii#2060]
Hello,

I see the Firefly-III documentation is on Read the Docs which doesn't seem to support translation.

Like Read the docs, Docusaurus is a new open source documentation website with localization support via CrowdIn.
https://docusaurus.io/

Is it worth the change?

**Comment by JC5** [comment]
It's pretty similar to readthedocs. They also support [translations](https://docs.readthedocs.io/en/stable/localization.html), and I can connect the repository to Crowdin.

Honestly I'd rather keep the documentation in English. It's hard enough to get quality translations for the help files, let alone the "default" translations.

**Comment by jinformatique** [comment]
Sure I understand. I was willing to help to translate into French, maybe not now but in the long term.
In any case if I start to do it on my side, then later I can send it back to you.

**Comment by JC5** [comment]
Absolutely, all the help is welcome of course. I am a bit cynical always. I have 25 languages enabled in Crowdin but maybe 8 are about 75% 🤐
