### ISSUE TITLE
How to use cron under Sandstorm

### ISSUE THREAD

**Issue by qirtaiba** [firefly-iii/firefly-iii#2062]
Hello,

I wonder if there is a recommended way to use cron under Sandstorm? I tried doing this:

`sudo -u sandstorm php /opt/sandstorm/var/sandstorm/apps/.../opt/app/artisan firefly:cron`

But the result was:

`Access denied for user 'firefly'@'localhost' (using password: YES)`

Is there another way to do it, or a recurring transactions not possible under Sandstorm?

Thanks!

**Comment by JC5** [comment]
There is no option to do cron jobs on Sandstorm yet, sorry about that.

**Comment by qirtaiba** [comment]
Can I suggest a new feature that checks for missed jobs whenever you do something in Sandstorm? It's not quite as good as a real cron job but it should suffice.
