### ISSUE TITLE
Tags for split transactions

### ISSUE THREAD

**Issue by sachawolf** [firefly-iii/firefly-iii#2063]
**Description**
When splitting transactions Tags are only applied to the original singular main transaction.

**Solution**
Allow for split transactions to have different Tags.

**Additional context**
This is important for those cases when you pay for services using other bills. Like the option to pay for a Mobile Store app using your Mobile Phone provider bill. This is something that T-Mobile (my provider) allows for. You then receive a single bill with the total amount and just one transaction for that amount. In my case I also have a subscription for Google Play Music running through there.

Phone bill and streaming music are quite often different Budgets let alone different Categories and Tags.

**Comment by Agraphie** [comment]
I'd love to see this happen :D Can I be of help somehow?

**Comment by JC5** [comment]
I'm working on it :)

**Comment by anandasudarshan** [comment]
+1 would be great to see and need this

**Comment by JC5** [comment]
This will be possible in 4.8.0.

https://github.com/firefly-iii/firefly-iii/projects/5#card-19937456
