### ISSUE TITLE
Mass delete Tags

### ISSUE THREAD

**Issue by sachawolf** [firefly-iii/firefly-iii#2064]
**Description**
Firefly-III creates a lot of automatic tags during import. At the most basic level there are the ones per import. When importing transactions via Spectre API that one also creates extra Tags. This gives for a lot of Tags that are (for me) not needed to beter index my transactions.

Tags seemingly can only be deleted one Tag at a time,

**Solution**
Make it so that several tags (specifically those created per import session) can be selected and deleted at the same time,

**What are alternatives?**
Turn off automatic Tag creation. Or let Tags that are no longer in use be deleted automatically.

**Additional context**
This goes for Categories as well. Even if those are not created automatically, deleting them is one by one. So if you redid your budgets en categories (like I just did) you are left with a lot of extra categories that are no longer needed.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19975465

**Comment by JC5** [comment]
The next release will feature this
