### ISSUE TITLE
Assigning expense accounts during import when file only contains descriptions

### ISSUE THREAD

**Issue by kaysond** [firefly-iii/firefly-iii#2067]
I'm going through somewhat tedious process of importing all of my checking/savings/credit card transactions for the last couple of years. The files that I can get from my banks basically just have three usable fields: Date, Amount, and Description. Description is a mess, so I don't want to use that as the expense account name directly.

Right now I assign Description to the FF3 Description, then use rules to scan the descriptions and set the expense account. This results in me having a ton of rules, and it's cumbersome and tedious, though that'll get easier as time goes on and the rule list grows.

My first attempt was to set Description to Opposing account, and then map the values, but then that just gets rid of the description altogether, and I have to manually select the account for every transaction.

What's the best way to do this? Stick with rules? Switch back to mapping? Or perhaps I can use dummy field as opposing account and map those manually? The goal is to minimize the amount of work needed to consolidate different descriptions into easily-readable expense accounts.

**Comment by JC5** [comment]
I wouldn't bother importing all of your history to be honest. What do you think you'll gain?

**Comment by kaysond** [comment]
One of my main reasons for using FF3 is to categorize and analyze my previous spending. Also, by importing all the old transactions, I can see what descriptions come up frequently and create rules to automate the categorization/analysis for future statements.

**Comment by kaysond** [comment]
I actually started with my last month's CC statement, but when I tried to map descriptions onto opposing accounts, I couldn't because I had no established expense accounts. Which meant either manually create all of the expense accounts by reading from the CSV first, so I could then pick them during import, or import them with no account, and enter accounts manually. I decided I might as well kill two birds with one stone and get my historical spending imported while also creating rules to avoid having to manually map things.

**Comment by JC5** [comment]
Well the database is not that complex, and Firefly III can only do so much. If you expand your CSV files outside of Firefly III, the import will be a lot easier.

**Comment by kaysond** [comment]
You mean like adding the account names to the csv by hand first? I might as well do the rules then, no?

**Comment by JC5** [comment]
Unfortunately you can't use a column twice in Firefly III, but if you copy it (should be a simple task) you can use one for the account name, and the other for the description.

**Comment by kaysond** [comment]
Right, ok. When I tell it to map values, does firefly try to do any guessing on which the correct mapped value is based on the input file?

**Comment by JC5** [comment]
Yes, if you map values it will do a simple string comparison.

**Comment by kaysond** [comment]
Got it. Thanks for the help
