### ISSUE TITLE
file_put_contents - storage/framework/cache/data - failed to open stream

### ISSUE THREAD

**Issue by geryduyck** [firefly-iii/firefly-iii#2068]
What?
Encountered a cache/permissions error when opening the transactions/withdrawal page.
Only this page seemed to be affected, other pages were no problem.

Full Error message:
file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/03/8e/038e9b894ba702dbd7bef2cd2da74eb691163145): failed to open stream: Permission denied

Server info:
firefly-iii runs on my ubuntu VPS, dockerized (image: jc5x/firefly-iii)

Mounted volumes:
   - /mnt/disk/srv/firefly-iii/storage/export:/var/www/firefly-iii/storage/export
   - /mnt/disk/srv/firefly-iii/storage/upload:/var/www/firefly-iii/storage/upload

Solution:
(restarting docker image)
docker-compose down
docker-compose up -d 

Question:
I noticed the system wanted to access storage/framework, do I need to link this folder outside of the docker image as well to avoid future cache issues?

issue is non-blocking, but wanted to provide useful feedback.

Interesting to know is that I recently (2 weeks ago) upgraded my docker image to the latest version of firefly-iii, the system was running smoothly until this error.

Debug information generated at 2019-02-09 11:09:12 Europe/Amsterdam for Firefly III version **4.7.9**. (generated after docker image restart)

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.13 |
| Display errors | Off |
| Session start | 2019-02-01 00:00:00 |
| Session end | 2019-02-28 23:59:59 |
| Session first | 2017-08-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, pdo_sqlite, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, Phar, gd, intl, ldap, pdo_mysql, pdo_pgsql, sodium, tidy, zip |

**Comment by JC5** [comment]
This should be fixed in 4.7.10, it was a known issue for me in 4.7.9.

**Comment by geryduyck** [comment]
great! will update!
