### ISSUE TITLE
Source asset account is not selected

### ISSUE THREAD

**Issue by algirdasc** [firefly-iii/firefly-iii#2069]
**Bug description**
I am running Firefly III version 4.7.10, and my problem is:
When adding new withdrawal/deposit source account is not selected and defaults to first in the list, altough I see in url, that source is set to correct account ID. This is annoying, as I misplaced my expenses to wrong account. 

**Steps to reproduce**
Try to add expence to any account, that is not first in selectbox.

**Expected behavior**
Right account is selected.

**Extra info**
Ubuntu 18.04, tried with Chrome & Firefox - same behaviour.

**Bonus points**
![screenshot from 2019-02-09 13-06-10](https://user-images.githubusercontent.com/18305296/52519962-4a879380-2c6c-11e9-9c4b-fb60c963e23f.png)

![screenshot from 2019-02-09 13-09-25](https://user-images.githubusercontent.com/18305296/52519964-507d7480-2c6c-11e9-8994-0e30bbd77de1.png)

**Comment by JC5** [comment]
I can't replicate this on the demo site. I'll check it out!

It could be a server-side cache thing but I doubt it. You could try clearing your browser caches and those of the server with `php artisan cache:clear`.

**Comment by algirdasc** [comment]
I tried claring browser & server cache - still the same result. Also, tried the demo - it works perfectly. By the way - I have more problems regarding UI. For example, when I try create recurring transaction, I got following error: 

[2019-02-10 22:32:14] local.ERROR: Data missing {"userId":1,"email":"REDACTED","exception":"[object] (InvalidArgumentException(code: 0): Data missing at /var/www/firefly.REDACTED/vendor/nesbot/carbon/src/Carbon/Carbon.php:910)
[stacktrace]


Could this be related?

**Comment by algirdasc** [comment]
Yes, this was related. As I use caddy web server, I misconfigured virtual host:
instead of 
```
    rewrite {
        to {path} {path}/ /index.php?{query}
    }

```
i had:
```
    rewrite {
        to {path} {path}/ /index.php?/{uri} <---Wrong variable & misplaced question mark
    }

```

Note to myself: do not configure anything after 10pm and few cold ones.
