### ISSUE TITLE
Zero values

### ISSUE THREAD

**Issue by TiagoGilMarques** [firefly-iii/firefly-iii#2074]
**Description**
You should allow to insert withdrawals with 0 value. Sometimes exists bills with 0 value. As an organization software we can't associate that bill because Firefly III doesn't allow 0 values.

**What are alternatives?**
There's none, I think.

**Comment by JC5** [comment]
Sorry, but this is not going to change in the near future.

Firefly III is primarily meant as a copy of your personal finances, and mainly your bank statements. I understand that these can contain 0-values (bunq does), but they can't be administered in Firefly III.
