### ISSUE TITLE
Docker: cannot acces cache dir

### ISSUE THREAD

**Issue by andy-nl** [firefly-iii/firefly-iii#2077]
I am running Firefly III version 4.7.11 with docker.
Previous versions worked fine.
After upgrade from 4.7.9 -> 4.7.11 I get the error:

> 
`#6 /var/www/firefly- {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught RuntimeException: Unable to create the cache directory (/var/www/firefly-iii/storage/framework/views/twig/a3). in /var/www/firefly-iii/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:55`

and I cannot access the web interface.
Any idea?

Cheers,
Andy

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2076

**Comment by andy-nl** [comment]
hoerraa thanks JC5, this did the trick!

chown -R www-data:www-data /var/storage

Cheers,
Andy
