### ISSUE TITLE
Repayment Mortgage

### ISSUE THREAD

**Issue by brightonjack** [firefly-iii/firefly-iii#2078]
**Description**
In the UK and many parts of the world, there are interest only mortgages and there are repayment mortgages. When a liability account is added, we can have the option to choose repayment and interest only mortgages. The same applies to non-mortgage liabilities as well as with each month, you pay part interest part what you borrowed.

**Solution**
When a transaction is added, we can "split" this transaction, part of which is an "expense" (ie interest) and part of which is a "transfer" (ie capital repayment). Mortgage statements and bank statements usually show which amount is for interest and which amount is for the capital repayment.

**What are alternatives?**
I only use Firefly-III so I am not sure if there are any other alternatives for managing mortgage accounts.

**Additional context**
At the moment, I make two separate transactions to achieve the desired effect. One as a transfer against the mortgage liability, and one as an expense representing the interest payment.

**Comment by JC5** [comment]
This is already on my list, it was mentioned in another ticket. I appreciate your feedback!

**Comment by JC5** [comment]
See the bottom of this issue:

https://github.com/firefly-iii/firefly-iii/issues/1956
