### ISSUE TITLE
Mortgage Liability Net Worth Calculation

### ISSUE THREAD

**Issue by brightonjack** [firefly-iii/firefly-iii#2079]
**Description**
For people with mortgage liability accounts, the net worth should be calculated differently. A mortgage is against a property. A property has a monetary value. When a payment is made against a mortgage, my net worth increases (but due to the balance on the liability, my net worth is in minus if the property price remains the same as the day I bought it).

**Solution**
For mortgage type liability accounts, there could be an additional field corresponding the value of the property where the user can update as and when s/he feels like it. Let's assume a property was worth €100,000 when bought, and I have a liability of €70,000 against it, meaning I put €30,000 downpayment when I bought it. A year later, the property is worth €120,000, and I made €10,000 capital repayments over the past year against the liability. This should result as €70,0000 - €10,000 = **- €60,000** in the liability (which is the behaviour we have today) AND €100,000 + €20,000 (increase in property value) + €10,000 (capital repayment) - €60,000 (balance on the liability) = **+ €70,000** in net worth.

**What are alternatives?**
I only use Firefly-III to manage my assets so I am not sure if there are any other alternatives.

**Additional context**
Net worth figure that is provided by Firefly remains partially incorrect when a user has mortgage liability accounts.

**Bonus points**
The developers of Firefly-III rock!

**Comment by JC5** [comment]
Thanks for the compliments :)

I am not going to build in full liability management. I appreciate the feedback but I want to keep this feature basic. You can keep track of mortgage payments but that's it.
