### ISSUE TITLE
Credit card without payment date cannot be updated

### ISSUE THREAD

**Issue by Transportman** [firefly-iii/firefly-iii#2080]
**Bug description**
I am running Firefly III version 4.7.11, and my problem is:
I have a credit card that I want to update, but it is not possible to do so if the payment date is not set. It is also not possible to change the account type to something else when the payment date is not set.

**Steps to reproduce**
Create a credit card asset account
Update some of the fields
Fails because the payment date is not set

**Expected behavior**
I would expect that the credit card can be updated/changed when no payment date is set.

**Extra info**
Tested in Firefox using the demo-site

**Bonus points**

**Comment by JC5** [comment]
Yes, this is a mandatory field. If you're not using it, please set it to the 1st of the month.

**Comment by Transportman** [comment]
That is indeed the workaround I have been using. Is it maybe possible to make the error stand out more (at the top of the page for example)? The first few times I encountered this, I missed the message next to the field.

**Comment by NiFNi** [comment]
Adding to this you cannot change a Credit Card Account to a default Asset Account without specifying the date. While this can easily be worked around it still does not seem pretty nice.

**Comment by JC5** [comment]
Indeed. The field is mandatory, even when you change the type of the account. I’ll pick it up as a fix for the next release.

**Comment by NiFNi** [comment]
Same problem when changing to a Credit Card from another Account type. You then can safe a Credit Card without the date. Should probably be included in the fix.
