### ISSUE TITLE
Rules are not executed on FinTS import

### ISSUE THREAD

**Issue by joshwapohlmann** [firefly-iii/firefly-iii#2081]
**Bug description**
I am running Firefly III version 4.7.10.
Whenever I import bank statements via FinTS my rules are not applied to the imported data.
I checked if rules "find" their corresponding and they match successfully. However, apparently none are executed.

**Steps to reproduce**
1. Create rules which trigger whenever a transaction is created
2. Make sure it matches one or more of the transaction to be imported
3. Import any number of transactions with FinTS
4. The rule (nor any other) was not applied on any transaction

**Expected behavior**
Rules with matching transactions should be executed.

**Extra info**
I will add Logs as soon as I have any new transactions I can test this against

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on Github, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by JC5** [comment]
I'm pretty sure the FinTS import routine doesn't ask to apply rules. Hence, they aren't. I'll check if I can safely add it. I can't test this so I'm flying blind.

**Comment by joshwapohlmann** [comment]
I recklessly applied the patch to my 4.7.10 installation. 
1. The checkbox added is shown properly
2. No errors occur
3. rules are applied correctly (matching process shows up in the log and is reflected in the results).

I'd say commit https://github.com/firefly-iii/firefly-iii/commit/2117fc2a5a284a285ed72385bd013bc8fe47c9a5 is a success and closes this issue.

**Comment by JC5** [comment]
Glad to hear it :+1:. I'll close the issue when the new release is live.

**Comment by JC5** [comment]
4.7.12 has been released. Follow the status of the Docker build on [Travis CI](https://travis-ci.com/firefly-iii/firefly-iii/builds).
