### ISSUE TITLE
Accomodate Australian Bank BSB as part of account identifiers

### ISSUE THREAD

**Issue by downforce** [firefly-iii/firefly-iii#2083]
**Description**
- I would like Firefly III to do accomodate BSB (Bank|State|Branch) ID's as a field under Asset Accounts.
- Details of BSB numbers can be found here: https://en.wikipedia.org/wiki/Bank_state_branch
- BSB + Account number form a unique identifier of a bank account in Australia.
- The same bank can have the same account number across different branches (although unlikely a single individual will get the same number twice). 

**Solution**
- If the "currency" is set to Australia, the BSB field is active (or have it as an preference enable/disable).
- Have the ability to match import on both BSB & Account Numbers combined.

**What are alternatives?**
Allow the BIC or IBAN number to accomodate the BSB format (xxx-xxx)

**Comment by JC5** [comment]
Can't you use the account number field to store it?

**Comment by downforce** [comment]
Thanks for the speed reply.

Each account has both a BSB and Account Number and they are different fields in any data export, e.g.
I might have the following account
- 123-456 12345679 - Cheque Account
- 123-456 09876543 - Savings Account

When I do bank transfers etc, I see "from 123-456 123" (usually truncated, thanks banks!) or "from 123-456 098 to 123-456 123". 

It's not really a critical change, just something thatll be a 'nice to have" and also make matching/importing data easier.

**Comment by JC5** [comment]
Fair enough. I'll put it on the list.
