### ISSUE TITLE
Changing directory structure

### ISSUE THREAD

**Issue by wprauchholz** [firefly-iii/firefly-iii#2084]
I am running Firefly III version 4.7.11

**Description**

I am directly changing the structure moving to virtual host configuration. As such the new location for firefly will move from /var/www/html to /var/www/<domain>/html.
Can I simply move  files from ... to or do I need to make a fresh install?
I do have back of /var/www/html/firefly, mysql database and csv file from export

**Comment by JC5** [comment]
No you can just move the files, that should work!
