### ISSUE TITLE
Installation on Synology NAS

### ISSUE THREAD

**Issue by albertsegura** [firefly-iii/firefly-iii#2086]
Hi,
first of all apologies if this has been covered in other issues, although many posts point to installation issues similar to this one I didn't manage to solve my problem.

I'm trying to setup Firefly on a Synology NAS (DS216j), doing a self-hosted/manual installation.

I have followed the installation steps and I have correctly setup the DB and configured it for firefly (mind you it was not straight forward since synology has multiple versions of php installed, and not all the options are available through ssh, plus I'm a bit of a newbie in this area). 

The issue comes when I try to access the webpage. I configure the Virtual Host using the Synology interface (screenshot attached) but when I access "192.168.1.150/firefly" (being 192.168.1.150 my NAS) I get a 404 error. If I try to access the folder directly it warns me about "This directory should not be open to the public! ", and redirects me to "/firefly-iii/public/login" with a 404 error as well. It is fine, I set the permissions to the firefly folder to 777 just to rule out this as a possible problem. The ownership of the folder is set to the http, instead of www-data, since it is the synology web user.

![capture](https://user-images.githubusercontent.com/1588785/52720009-1c28f180-2fa7-11e9-8558-f862ecfb5fe2.png)

The NAS allows to use either nginx or apache2.4, I tried with both and neither has worked. Right now I'm using Apache, the config file that it generates is the following: 
httpd24.conf: https://pastebin.com/Hu1ikMap 
sites-enabled/httpd-vhost.conf: https://pastebin.com/mcNnm6mh

The firefly contains no log, and the apache one looks like this after a service restart:
> 2019-02-13T15:44:06+01:00 NAS [Wed Feb 13 15:44:06.254576 2019] [mpm_worker:notice] [pid 29011:tid 1996133120] AH00292: Apache/2.4.29 (Unix) configured -- resuming normal operations
> 2019-02-13T15:44:06+01:00 NAS [Wed Feb 13 15:44:06.256338 2019] [core:notice] [pid 29011:tid 1996133120] AH00094: Command line: '/var/packages/Apache2.4/target/usr/local/bin/httpd24'
> 2019-02-13T15:44:10+01:00 NAS [Wed Feb 13 15:44:10.176841 2019] [mpm_worker:notice] [pid 29011:tid 1996133120] AH00297: SIGUSR1 received.  Doing graceful restart
> 2019-02-13T15:44:10+01:00 NAS AH00558: httpd24: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
> 2019-02-13T15:44:10+01:00 NAS [Wed Feb 13 15:44:10.338524 2019] [mpm_worker:notice] [pid 29011:tid 1996133120] AH00292: Apache/2.4.29 (Unix) configured -- resuming normal operations
> 2019-02-13T15:44:10+01:00 NAS [Wed Feb 13 15:44:10.338612 2019] [core:notice] [pid 29011:tid 1996133120] AH00094: Command line: '/var/packages/Apache2.4/target/usr/local/bin/httpd24'

Any other test or log I can do please ask.

I am running Firefly III version 4.7.11, PHP 7.2, Apache 4.2, Synology DSM 6.2.1-23824 Update 4.

**Comment by JC5** [comment]
What happens when you browse to /index.php specifically?

**Comment by albertsegura** [comment]
Nothing: 404 and redirects to firefly-iii/public/index.php/login

Nothing new on the apache or firefly error logs

**Comment by JC5** [comment]
OK. Seems that mod rewrite is not working properly. But I can't tell from your config, it seems to be fine.

**Comment by albertsegura** [comment]
I tried with nginx and the result is the same. I will try to use nginx with custom rules(skiping the interface) and see if it works.

**Comment by albertsegura** [comment]
Trying with nginx at least I get some errors on the logs.

> 
> 2019/02/13 22:34:25 [error] 13137#13137: *9278 open() "/var/services/web/firefly" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /firefly HTTP/1.1", host: "192.168.1.150"
> 2019/02/13 22:34:26 [error] 13137#13137: *9280 open() "/var/services/web/missing" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /missing HTTP/1.1", host: "192.168.1.150", referrer: "http://192.168.1.150/firefly"
> 2019/02/13 22:34:26 [error] 13137#13137: *9282 open() "/var/services/web/favicon.ico" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.150"

It seems weird that the server field is empty, like its not detecting it? Also its trying to access /var/services/web/firefly, "/var/services/web" is a soft link to /volume1/web/, where the program is, but in its folder firefly-iii.

Here are the nginx configurations:
nginx.conf: https://pastebin.com/KnwK8gq1
app.d/server.webstation-vhost.conf: https://pastebin.com/M5XcEkxG

**Comment by albertsegura** [comment]
Hi,
I have managed to run firefly directly without using any virtualhost (accessing /firefly-iii/public).

I had to change the default backend to http2.4 in "general settings" of the synology web station interface.  Then I saw this errors on the apache logs:

> 2019-02-13T14:20:14+01:00 NAS [Wed Feb 13 14:20:14.745207 2019] [core:alert] [pid 3860:tid 1784673328] [client 192.168.2.1:59470] /volume1/web/firefly-iii/.htaccess: Invalid command 'Deny', perhaps misspelled or defined by a module not included in the server configuration, referer: https://192.168.1.150:6001/

Which I fixed by changing the line "Deny from all" to "Require all denied" in  firefly-iii/.htaccess

Still I wanted to use the virtual host option, I don't see why is it giving me a 404 still.
The config that I have is this one: https://pastebin.com/PsF4SqyH

httpd24 -t -D DUMP_VHOSTS shows me this: 
> VirtualHost configuration:
> *:443                  is a NameVirtualHost
>          default server 127.0.0.1 (/usr/local/etc/apache24/conf/httpd24.conf:98)
>          port 443 namevhost 127.0.0.1 (/usr/local/etc/apache24/conf/httpd24.conf:98)
>          port 443 namevhost firefly (/usr/local/etc/apache24/sites-enabled/firefly-vhost.conf:1)
> *:80                   is a NameVirtualHost
>          default server 127.0.0.1 (/usr/local/etc/apache24/conf/httpd24.conf:98)
>          port 80 namevhost 127.0.0.1 (/usr/local/etc/apache24/conf/httpd24.conf:98)
>          port 80 namevhost firefly (/usr/local/etc/apache24/sites-enabled/firefly-vhost.conf:1)

httpd24 -M shows: 
> Loaded Modules:
>  core_module (static)
>  so_module (static)
>  http_module (static)
>  mpm_worker_module (static)
>  authn_core_module (shared)
>  authn_file_module (shared)
>  authz_core_module (shared)
>  authz_host_module (shared)
>  authz_groupfile_module (shared)
>  authz_user_module (shared)
>  authz_owner_module (shared)
>  auth_basic_module (shared)
>  auth_digest_module (shared)
>  include_module (shared)
>  filter_module (shared)
>  deflate_module (shared)
>  log_config_module (shared)
>  env_module (shared)
>  mime_magic_module (shared)
>  headers_module (shared)
>  setenvif_module (shared)
>  mime_module (shared)
>  status_module (shared)
>  autoindex_module (shared)
>  asis_module (shared)
>  cgid_module (shared)
>  negotiation_module (shared)
>  dir_module (shared)
>  actions_module (shared)
>  alias_module (shared)
>  rewrite_module (shared)
>  proxy_module (shared)
>  proxy_fcgi_module (shared)
>  unixd_module (shared)
>  xsendfile_module (shared)
>  rpaf_module (shared)
>
