### ISSUE TITLE
Php version 7.1.8 not supported by FireFly, installing with ampps

### ISSUE THREAD

**Issue by Bjorn-c** [firefly-iii/firefly-iii#2087]
I'm trying to install it by using ampps. The current php version of ampps is `7.1.8, 7.0.22, 5.6.31, 5.5.38, 5.4.45 and 5.3.29`, which is not supported by FireFly.
Any chance of adding 7.1.8 to the supported versions in the ampps installation script?

**Comment by JC5** [comment]
Firefly III is not compatible with PHP 7.1. It has several pieces of code that are specific for 7.2.

**Comment by epikkoder** [comment]
So why would AMPPS be included in the list of options where Firefly is install-able? AMPPS doesn't seem to have support for PHP 7.2 yet, and I can't find any solution on Google on how to add 7.2 in it.

**Comment by JC5** [comment]
I wrote that section of the readme when Firefly III was running on PHP v7.1. I'm a bit surprised that two years after its release, AMPPS still doesn't support PHP 7.2.

I'll remove the mention with the next release.

**Comment by epikkoder** [comment]
Is it possible to install it on XAMPP instead? This one supports PHP 7.2, and even 7.3.

**Comment by JC5** [comment]
That should work as well.
