### ISSUE TITLE
Change database user in docker-compose.yml causes database creation failure

### ISSUE THREAD

**Issue by stonewareslord** [firefly-iii/firefly-iii#2090]
If you change the database user in both places, the database will not get created:
```
SQLSTATE[08006] [7] FATAL:  database "firefly" does not exist
```

I also tried this using the `jc5x/firefly-iii:develop` image with the same result. 
Steps to reproduce:
```
git clone https://github.com/firefly-iii/firefly-iii/
cd firefly-iii
vi docker-compose.yml
# Change database user from "firefly" to "firefly2"
docker-compose up
docker-compose exec firefly_iii_app php artisan migrate --seed
# Produces database does not exist errors
```

**Comment by JC5** [comment]
Postgres uses the username as the database name. So if you change the user from "firefly" to "firefly2" in both the Firefly III settings _and_ the Postgres settings in the docker-compose file, you must also set `- FF_DB_NAME=firefly` to "firefly2".
