### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by overload08** [firefly-iii/firefly-iii#2092]
**Description**
I would like Firefly III to notify when a new transation is set.

**Solution**
Add notification action to transation rules (Mail, push...)

**What are alternatives?**
Activate notifications in the user preferences

**Comment by JC5** [comment]
What's your use case?

**Comment by overload08** [comment]
I use scripts to retreive all new transactions fromage my bank. It will be good to receive a mail notification like "Hey, you've got a new transaction". To be more precise, it will be control from transaction rule (exemple, only if the transaction is grather than 100€)

**Comment by JC5** [comment]
Ah yes. I'll think about it, I like the idea. Nothing on the short term I'm afraid though.

**Comment by JC5** [comment]
Firefly III won't support notifications, I'm afraid.
