### ISSUE TITLE
Login fails since 4.7.12

### ISSUE THREAD

**Issue by SamJBerry** [firefly-iii/firefly-iii#2093]
**Bug description**
I am running Firefly III version 4.7.12 and my problem is:

Fails to login with any / non-existent user.

Seems to be caused by 451c86e431e6ef5ea67515b51f3f5467505fed60. If I remove the additions in  app/Http/Controllers/Auth/LoginController.php line 74 to 82 login behaves as normal.

Sorry having trouble copying the whole stacktrace.
`[2019-02-16 21:47:20] local.ERROR: Option port must be an integer. {"exception":"[object] (Adldap\\Configuration\\ConfigurationException(code: 0): Option port must be an integer. at /var/www/firefly-iii/vendor/adldap2/adldap2/src/Configuration/Validators/IntegerValidator.php:22)
#17 [internal function]: FireflyIII\\Http\\Controllers\\Auth\\LoginController->login(Object(Illuminate\\Http\\Request))`

**Comment by JC5** [comment]
Whoops. Stay tuned.

**Comment by JC5** [comment]
Pushed a fix. Travis is running merrily. Since it's merged in the master, new users shouldn't notice. I appreciate that you opened a ticket, I wouldn't have noticed it earlier.

**Comment by Agraphie** [comment]
Damn, beat me to it. Thanks @SamJBerry and thanks @JC5

**Comment by SamJBerry** [comment]
No worries! Speedy find, speedy fix

**Comment by JC5** [comment]
:+1:

I've pinned the issue. It'll take some time for the docker images to build anyway. Thanks again!

**Comment by Agraphie** [comment]
I just tried the new docker image and I was able to login again. Not being able to login with wrong password did also work. Thanks for the quick fix!
