### ISSUE TITLE
Cannot get past first account registration page

### ISSUE THREAD

**Issue by k-wax** [firefly-iii/firefly-iii#2094]
**Bug description**
I am running Firefly III version 4.7.12 on HomelabOS, and my problem is:

Installed Firefly via the official docker image, ran the 4 commands to initialize the database and tried to register a new account. The register -button does nothing and does not produce any log entries for the Firefly container at least.

Compose file & logs: https://0bin.net/paste/SNFDPf4CFtBUlEM1#eJkN0KPeNKPhpQCKIyrDYt25CXVD4RYXSp04MS4pW3i

**Comment by JC5** [comment]
It is a problem with your reverse proxy. Check out the Firefox console. Firefly III believes its running over http, not https.

https://docs.firefly-iii.org/en/latest/installation/docker.html#docker-and-reverse-proxies

**Comment by k-wax** [comment]
I was JUST about to post that it's weird that FF thinks the password fields are sent over http since I have a certificate running. Thanks!

**Comment by JC5** [comment]
:+1:

**Comment by hulloanson** [comment]
Hi, I encountered the same problem on 4.7.14 too. I'm using the `release-4.7.14-amd64` docker image, proxied by apache2.

What were done:
1. Passed the `APP_URL`, prefixed with `https`, in `docker-compose.yml` in the environment section
2. Added `RequestHeader set X-Forwarded-Proto "https"` to the relevant vhost config

What was expected:
The registration form should have an url starting with `https://`.

What was observed:
Firefox warns `Password fields present in a form with an insecure (http://) form action`. An inspect to the form element confirms the action url started with `http://`.

What was done to debug the problem:
Added `var_dump(getallheaders()['X-Forwarded-Proto'])` to the `showRegistrationForm` route. The value "https" was returned.

Now I have no idea what went wrong T0T

**Comment by JC5** [comment]
Check out https://github.com/firefly-iii/firefly-iii/issues/2091 for some suggestions. They might help!

**Comment by hulloanson** [comment]
Oh silly me. I actually wrote `TRUSTED_PROXIES='**'` in an `.env` file which was parsed by docker-compose. Compose took the quotes literally as value which then got persisted into the database.

Thanks for your prompt response and patience, @JC5 ! I like your work 👍

**Comment by JC5** [comment]
No problem, I am glad the answer was simple. :grin:
