### ISSUE TITLE
How can i increase the php max execution time when using docker compose

### ISSUE THREAD

**Issue by Matthijz98** [firefly-iii/firefly-iii#2096]
I am running Firefly III version 4.7.9

**Description**
I want to increase the execution time because if i make a new rule I have to apply it month by month.

**Extra info**
I tryed doing it by just editing the php.ini in the docker container and then restarting the container, but that did not work.
I did a google search but my docker skills where not good enough to understand it.
Is there a way to just do it bij adding a line to the docker compose file or something like that?
Because even if I can get it to work by editing the file I have to do that every time I update.

**Comment by JC5** [comment]
I will have to make a change to the Dockerfile to make it permanent but editing the php.ini file should work. Which file are you editing specifically?

**Comment by Matthijz98** [comment]
Thanks for the reply I am trying to edit /usr/local/etc/php/php.ini-production

**Comment by JC5** [comment]
I can't access my own Docker image right now, but there is no /usr/local/etc/php/php.ini?

If not, copy /usr/local/etc/php/php.ini-production to /usr/local/etc/php/php.ini and see if that helps.

**Comment by Matthijz98** [comment]
That worked like a charm.
This will work for now thanks for the support.

**Comment by JC5** [comment]
The next version of Firefly III will bump the execution time to 300 seconds. That should be enough for most jobs. I'm not setting it to zero to prevent the instance from running wild.
