### ISSUE TITLE
documentation: guide (debian buster) users better

### ISSUE THREAD

**Issue by adrien-n** [firefly-iii/firefly-iii#2098]
I've installed Firefly III on debian buster (it's still unreleased but it is frozen) and hit a couple issues which I've solved and which I believe should go into the documentation.

The "configuration" section of the server guide tells the user to edit the .env file but the file isn't very short and there are some things that are not at the beginning of the file but are important nonetheless. I've noted: the DB configuration and the trusted proxies variable. A short sentence to remind to create the database user, the table and grant enough rights to the user for that table.

The other issue is more specific to debian (buster): I had a 404 on /login but didn't spot the issue in the server FAQ because I was looking for "login" in the page and not "404. It would probably be good to add a mention in the server faq to make it easier to find and maybe rename the section from "I get a 404" to "I get a 404 (especially on /login)". Moreover I think that there should be an explicit link to that section from the server doc, maybe something like "If you're running debian and get a 404 on /login, see [this section in the FAQ]".

Thanks. :)

**Comment by JC5** [comment]
Thanks for the suggestions. I'll pick them up and make sure the documentation gets updated wherever necessary. I hope you like Firefly III!

**Comment by adrien-n** [comment]
Great. :) 

And I definitely like Firefly III so far. \o/
