### ISSUE TITLE
Job could not be started or crashed

### ISSUE THREAD

**Issue by bitttttten** [firefly-iii/firefly-iii#2099]
I am running Firefly III version v4.7.12

**Description**
When trying to import a CSV file generated from my bank I get this error:

```
Fatal error
The import has suffered from an error it could not recover from. Apologies!

Job could not be started or crashed: JobStatusController::start expects status "ready_to_run" instead of "error".

This (possibly very cryptic) error message is complemented by log files, which you can find on your hard drive, or in the Docker container where you run Firefly III from.
```

**Extra info**
My CSV input is 1234 lines long, and looks a bit like:

```
"Datum","Naam / Omschrijving","Rekening","Tegenrekening","Code","Af Bij","Bedrag (EUR)","MutatieSoort","Mededelingen"
"20190125","Hr X Y","NLXXXXXXXXXXXXXXX","","GT","Bij","XXX,XX","Online banking","Savings"
"20190114","B A","NLXXXXXXXXXXXXXXX","NLXXXXXXXXXXXXXXX","GT","Af","XxX,XX","Online banking","Naam: A Z"
"20190112","Coffee","NLXXXXXXXXXXXXXXX","","BA","Af","XX,XX","PIN","Description"
```

And I am using the ING config from: https://raw.githubusercontent.com/firefly-iii/import-configurations/master/nl/ing/default.json

And the logs look like:

```
2019-02-18T19:55:36.027932+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.DEBUG: Array does not contain a value for name. Continue  
2019-02-18T19:55:36.028121+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.DEBUG: "ABC" (#1) is source and "XYZ" (#51) is destination.  
2019-02-18T19:55:36.028355+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.DEBUG: XXX.XX is positive, so "XYZ" (#51) is now source and "ABC" (#1) is now destination.  
2019-02-18T19:55:36.038339+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.DEBUG: Source is a revenue account. This is a deposit.  
2019-02-18T19:55:36.045445+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.DEBUG: Now in CurrencyMapper::map()  
2019-02-18T19:55:36.058887+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.DEBUG: Found currency EUR based on ID, return it.  
2019-02-18T19:55:36.059055+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.DEBUG: Destination is an asset account, and has currency preference EUR  
2019-02-18T19:55:36.059236+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.DEBUG: createFromFormat: Turning "20170118" into "2017-01-18 00:00:00" using "Ymd"  
2019-02-18T19:55:36.059389+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.DEBUG: Set status of job "xxxxxxxxxx" to "provider_finished"  
2019-02-18T19:55:36.252976+00:00 app[web.1]: [2019-02-18 19:55:36] heroku.INFO: Now finished with JobStatusController::start  
```

**Comment by JC5** [comment]
Some times it's as simple as a full browser cache. I've seen it before but it's always been intermittent. Could you try clearing your cache and restarting the app?

**Comment by bitttttten** [comment]
So I ran it in a different browser (Firefox) but before that I deleted the 2 accounts (main, and savings) and made 2 new ones (main and savings, but with different names).

I got a different issue in Firefox now:

> Cannot get status of current job: error: Service Unavailable

If I go to the logs, they look like they are still processing the import. Either my logs are behind or it's still running 😅

**Comment by bitttttten** [comment]
Also I was using Heroku, and uploading almost 2 years worth of logs (a 1234 line CSV). Will this hit the cap of 10k rows on the free tier?

**Comment by JC5** [comment]
You shouldn't get close but personally I'm not a fan of Heroku's performance. They're very stingy with resources in the free tier (which makes sense) and hosting Docker containers in AWS is most certainly cheaper. It's just more expensive.

**Comment by bitttttten** [comment]
So I spun up a docker container and installed it through the docker compose file in the repo. Apart from being way snappier, it imported successfully apart from one error:

> Row #441 ("Naam: XX YY") could not be imported. It already exists.

I think it's a minor error.

**Comment by JC5** [comment]
If the importer doesn't want to import it, it's a duplicate. This can happen (depending on the bank) when you do two of the exact same transactions in the same time period. For some banks this is a day, for others a minute.

**Comment by bitttttten** [comment]
Ah okay. I saw that there were 2 similar transactions, so I edited one to be 1 more Euro than the other and the import did not complain any longer.

Although now there is a discrepancy between the stats on firefly and on my bank. The values are off, one is 73 off and the other is 700 off. Do you have any advice to debug this? Maybe another CSV parser that I can verify the export from my bank is accurate? I went through every item when mapping and made sure to map them correctly.

> Opposing account (name)
> Mr bitttttten > ING
> 
> Asset account (IBAN)
> NLXYPPPPP33333 > ING
> 
> Opposing account (IBAN)
> To savings > ING Savings
> From savings > ING Savings

These were my mappings.

Perhaps the last two need explaining, since my bank exports transfers to and from my savings and lists the description a bit differently. For example (I just made these up for to demonstrate) these two entries are to and from savings.

> "20190101","Mr bitttttten","NLXYPPPPP33333 ","","GT","Af","500,00","Online bankieren","To savings"
> "20190102","Mr bitttttten","NLXYPPPPP33333 ","","GT","Bij","500,00","Online bankieren","From savings"

One entry is adding 500 euros to saving, and the other is removing 500 euros from savings the next day.

**Comment by bitttttten** [comment]
Ah okay. I saw that there were 2 similar transactions, so I edited one to be 1 more Euro than the other and the import did not complain any longer which is great (I do not mind being 1 euro out, as I can add that as a manual entry after the import).

Although now there is a discrepancy between the stats on firefly and on my bank. The values are off, one is 73 off and the other is 700 off. Do you have any advice to debug this? Maybe another CSV parser that I can verify the export from my bank is accurate? I went through every item when mapping and made sure to map them correctly.

> Opposing account (name)
> Mr bitttttten > Default asset account
> Asset account (IBAN)
> NLXYPPPPP33333 > Default asset account
> Opposing account (IBAN)
> To savings > Savings account
> From savings > Savings account

These were my mappings. Maybe I am confused with the asset account and opposing account, as they both map to my default asset account?

Perhaps the last two need explaining, since my bank exports transfers to and from my savings and lists the description a bit differently. For example (I just made these up for to demonstrate) these two entries are to and from savings.

> "20190101","Mr bitttttten","NLXYPPPPP33333 ","","GT","Af","500,00","Online bankieren","To savings"
> "20190102","Mr bitttttten","NLXYPPPPP33333 ","","GT","Bij","500,00","Online bankieren","From savings"

One entry is adding 500 euros to saving, and the other is removing 500 euros from savings the next day.

**Comment by bitttttten** [comment]
Ah okay. I saw that there were 2 similar transactions, so I edited one to be 1 more Euro than the other and the import did not complain any longer which is great (I do not mind being 1 euro out, as I can add that as a manual entry after the import).
