### ISSUE TITLE
Mass-edit date blank

### ISSUE THREAD

**Issue by Aarup** [firefly-iii/firefly-iii#2100]
**Bug description**
I am running Firefly III version 4.7.12, and my problem is:

When I try to do mass-edit of transactions, the value for the date field is empty, which results in all transactions getting todays date set when I save unless I manually set each date to their original value.

![b131c2cd-a872-45a8-b412-830afa4c8623 png](https://user-images.githubusercontent.com/1222464/52999741-dcd72680-3426-11e9-8235-c34a04a48c3a.jpg)

**Comment by JC5** [comment]
Thanks for letting me know. I thought this was fixed. I'll pick it up for the next release.
