### ISSUE TITLE
Set budget by category

### ISSUE THREAD

**Issue by Aarup** [firefly-iii/firefly-iii#2101]
**Description**
Is it possible to have Firefly "link" a category to a budget?
The way I've setup my accounts, a category will almost always be put under the same budget.

**Solution**
When categories are linked to a budget, it makes the assignment of budget much and avoid data errors where the same type of entries doesn't have the same budget/category combination if the budget could automatically be set when the category is set.

**Comment by JC5** [comment]
You could use rules to do that. 

http://docs.firefly-iii.org/en/latest/advanced/rules.html

**Comment by Aarup** [comment]
Yeah, I was already using rules to set destination accounts, category and budget but it seemed like a clumsy way to do it, but I've made a new strategy for my rules which makes the system do it in a way I'm happy with 😃 

There's just one thing that's confusing me right now - in some of my rules I'm trying to use the "Transaction is of type" trigger, but no matter if I use Withdrawal or Deposit I'm getting a "This value is invalid for the selected trigger." eventhough the system suggest using those values?

![a6196e1f-b752-4adc-bc02-c13b8d252958 png](https://user-images.githubusercontent.com/1222464/53051715-177ba600-349d-11e9-8efa-72360e489343.jpg)
![anmaerkning 2019-02-19 232021](https://user-images.githubusercontent.com/1222464/53051716-177ba600-349d-11e9-90da-0a2c1dc4c7db.jpg)

**Comment by JC5** [comment]
Which version are you running? I have no trouble setting those up.

**Comment by Aarup** [comment]
Thanks for the quick feedback, really appreciate it.

I'm running 4.7.12 running on docker setup a couple of days ago.

On the demo site I can create the rule without a problem, so it might be a problem on my end.
