### ISSUE TITLE
The initial balance shows as a negative of what you put in

### ISSUE THREAD

**Issue by coltonhurst** [firefly-iii/firefly-iii#2104]
**Bug description**
I am running Firefly III version 4.7.11, and my problem is:

After setting up Firefly III, and making a new user, you enter the amount of money in your bank (initial checking account setup). After setting it up, on the home dashboard page, there are boxes on the right showing the initial balance of your bank. However, even though I entered a positive number, it's showing the negative of it!

**Steps to reproduce**

Set up Firefly III. Make a new account. Go to preferences and change currency to USD. Enter initial checking balance on the dashboard (make sure it's a positive number).

After reloading the dashboard, on the right, it shows the negative of the number you entered.

**Expected behavior**

On the right, the positive (correct) value of my bank, not the negative.

**Extra info**

Notice the red negative of the values:

<img width="465" alt="firefly-bug" src="https://user-images.githubusercontent.com/5691612/53066362-780ae300-349d-11e9-9656-2699fa3016de.png">

**Comment by coltonhurst** [comment]
Also, if I rename those accounts (which I did), those two boxes show, and two new ones with the new name appear underneath, rather than replacing the old named versions.

**Comment by coltonhurst** [comment]
Also, if I rename those accounts (which I did), those two boxes show, and two new ones with the new name appear underneath, rather than replacing the old named versions.

Just want to make it clear though- thank you everyone for your work on OSS!

**Comment by JC5** [comment]
Oh nice find. I think I know what I messed up. The initial balance account shouldn't appear in that list anyway, so its duplicate shouldn't either. Thanks for letting me know!

**Comment by JC5** [comment]
So far, I haven't been able to replicate this. What database driver are you using? 

This may have been fixed in 4.7.12 already.

**Comment by coltonhurst** [comment]
I'm using a MySQL database... not sure about the database driver. How can I determine that?

(Would it be php pdo?)

**Comment by JC5** [comment]
The fact that it's MySQL is enough. It's strange though, I've been playing around with it but nothing happens. Can you try this with debug logging enabled?

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on Github, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by coltonhurst** [comment]
Sure, I can do that. I'll email it to you.
Also... not sure if this is related or if it should be it's own bug, but if you create a new bank, those sidebar items aren't deleted when you delete the bank.

Here's a video showcasing both bugs... the negative starting amount, as well as the side items not going away (I had no banks, added one, and the other items are still there from prior attempts).

https://www.dropbox.com/s/kty8i3zi628pfwo/FireflyBug.mov?dl=0

**Comment by JC5** [comment]
There's something in your system that's doing very aggressive caching maybe? The sidebar items shouldn't exist when you delete the account. I haven't been able to replicate anything yet :(
