### ISSUE TITLE
allow mathematical operators in amount field

### ISSUE THREAD

**Issue by TMaddox** [firefly-iii/firefly-iii#2105]
**Description**
Sometimes I want to make two expenses a single one, when this is the occasion I previously entered (I used excel before) the amount just as "=19,98+3,24", or "=27,30/3" on a shared expense

**Solution**
allow inputs like 19,98+3,24 in the amount field (just store the final expense, maybe calculate when focus changes)

**What are alternatives?**
calculate externally

**Comment by JC5** [comment]
Nope, sorry. See also https://github.com/firefly-iii/firefly-iii/issues/535

**Comment by TMaddox** [comment]
Hm ok, would be really really cool though, so pls change your mind someday :P
