### ISSUE TITLE
autocomplete not updated on renaming category

### ISSUE THREAD

**Issue by TMaddox** [firefly-iii/firefly-iii#2107]
**Bug description**
I am running Firefly III version 4.7.12, and my problem is:

I renamed a category (f.e. from "food" to "food and drinks"). Now when I type "fo" the autocomplete is showing both, "food" and "food and drinks", but there is no category "food" left (as it has been renamed) and I checked, all transactions have been updated too.

**Steps to reproduce**
1) create category "food"
2) register an expense in firefly-iii with the category "food"
3) rename category "food" to "food and drinks"
4) when registering a new expense, on autocomplete "food" is still available (misleads users to add category "food" again)

**Expected behavior**
when renamed, the old name of a category should be removed from autocomplete.

**Extra info**
OS: Ubuntu 18.04 LTS
nginx version: 1.15.8-1~xenial
php version: 7.2
I installed via composer

**Comment by JC5** [comment]
The auto complete is cached by your browser. Only you clear it, it should be fixed :)

**Comment by TMaddox** [comment]
Perfect, thank you!
