### ISSUE TITLE
Blank screen after fresh install

### ISSUE THREAD

**Issue by nuttin** [firefly-iii/firefly-iii#2110]
I am running Firefly III version 4.7.12.

**Description**
Did a fresh new install following install instructions. Everything installs without any problems but at the last step when I am to visit http://localhost/firefly-iii/, I see the screen shown below
![image](https://user-images.githubusercontent.com/10968555/53241669-af96ac80-36a2-11e9-95b5-e17b07eb0cb4.png)

..and when I try localhost/firefly-iii/public/, all I get is a blank screen.

**Extra info**
OS: Ubuntu 18.04 fresh install
Database: MySQL
PHP: 7.2
Browser: Latest firefox
Cannot supply info from /debug as there's no localhost/firefly-iii/debug page

I'd like to try out firefly but there's no obvious way for me to move forward here. Any guidance is appreciated.

**Comment by nuttin** [comment]
Also, http://localhost/firefly-iii/public/login is a 404 which makes me think that the installation is incomplete but then there were no errors during install!

![image](https://user-images.githubusercontent.com/10968555/53241935-875b7d80-36a3-11e9-81c6-bbd487a83b60.png)

**Comment by JC5** [comment]
Make sure you enable mod_rewrite and make sure that you configure the web root of apache to the correct directory.

**Comment by JC5** [comment]
Both of those problems cannot be detected by me, unfortunately.

**Comment by nuttin** [comment]
> Make sure you enable mod_rewrite and make sure that you configure the web root of apache to the correct directory.

mod_rewrite is enabled and the webroot is configured properly as /var/www/html.
Firefly is installed in /var/www/html/firefly

The apache config file is just the default one, no changes have been made. It's quite unfortunate that there are no remedial steps, no logs, nothing to debug. 

`<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>
`

**Comment by JC5** [comment]
Change DocumentRoot to `/var/www/html/firefly-iii/public`. If /login still gives a 404, add `AllowOverride All` to the VirtualHost section.

**Comment by nuttin** [comment]
> Change DocumentRoot to `/var/www/html/firefly-iii/public`. If /login still gives a 404, add `AllowOverride All` to the VirtualHost section.

Already tried changing `DocumentRoot` to `/var/www/html/firefly-iii/public/` and that didn't help. Adding `AllowOverride All` also did not help.

Brand new LAMP install, brand new firefly install. Shouldn't be this difficult.

**Comment by JC5** [comment]
Did you restart Apache? If that doesn’t change the documentroot you’ve got bigger config problems.

**Comment by nuttin** [comment]
> Did you restart Apache? 
Yes :)

> If that doesn’t change the documentroot you’ve got bigger config problems.
The `DocumentRoot` change did go through and now when I access http://localhost, I can see that it's the /public directory cause if I try and access a specific file in that directory, e.g. safari-pinned-tab.svg, it shows up just fine.
![image](https://user-images.githubusercontent.com/10968555/53266517-3ec2b500-36e1-11e9-9c7c-c1f4b2516fb9.png)
 
I am sure there are problems somewhere else but this would be one of those very few times where I get frustrated installing software because the package refuses to be helpful. I mean there are no logs anywhere that will help me determine what's going on. Moreover, the entire installation went ahead without any issues, warnings or error messages. Plus there are no specific instructions in the install documentation for mods to be made to the LAMP stack, especially Apache.

Guessing, I think the issue is either in web server config or db initialization/connection. 

I do appreciate your willingness to help.

**Comment by JC5** [comment]
I appreciate the frustration but from a package point of view there’s not much I can do to be honest. I can’t even detect what you’re running in terms of software. I have to rely on the web server and the OS to report issues back me. 

I stopped providing very specific documentation because ironically, the more I try to explain and document the more exceptions I run into (from users). To fix those, I have to expand the docs, and then I run into even more rare exceptions.... it’s a never ending story. 

It turns out it’s easier to point people to stackoverflow or google because usually the solution can be found there anyway. 

It’s trial and error for the both of us. :wink:

**Comment by nuttin** [comment]
Understood. I'll keep trying and let you know here in case I find a solution.

BTW, another option for distribution could be a VirtualBox VM that comes with everything pre-installed and ready to do.

**Comment by JC5** [comment]
Mmm, that’s not a bad idea. The docker container could be something for you maybe? It’s basically the VM but with less “core”.

**Comment by nuttin** [comment]
I tried the docker container as well, ran into some challenges and that's why I thought of a VM.
