### ISSUE TITLE
auto populate withdrawal budget or Source account

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#2113]
**Description**
would like to auto populate budget or source account if clicking withdrawal from the detail page of one of these. would save alot of time when filling in new transactions.
There are so many fields to fill out when creating a new transaction that saving any time will be helpful

**Solution**
add a url query for withdrawal to put in id of budget or asset account to attempt to prepopulate

**What are alternatives?**
most personal finance program auto populate these fields

**Comment by JC5** [comment]
You mean from the menu on the side, right?

**Comment by lastlink** [comment]
yes or perhaps have a new withdrawal button from the budget detail/asset account detail page that auto populates either way this would save a lot of time.
