### ISSUE TITLE
Error when editing transaction

### ISSUE THREAD

**Issue by mwolfaardt** [firefly-iii/firefly-iii#2114]
**Bug description**
I'm trying to edit a transaction, but I keep on getting the following error : 

Return value of FireflyIII\Repositories\Journal\JournalRepository::getFirstPosTransaction() must be an instance of FireflyIII\Models\Transaction, null returned

**Comment by JC5** [comment]
Could you run this on the command line?

php artisan firefly:verify

**Comment by mwolfaardt** [comment]
Amount integrity OK for user #1
No orphaned transactions!
No orphaned journals!
All link types OK!
All access tokens OK!
Amount integrity OK!

**Comment by JC5** [comment]
Mmm. Try firefly:upgrade? 

I am getting the impression it’s a database corruption thing.

**Comment by mwolfaardt** [comment]
I'll run the query and report the results

**Comment by mwolfaardt** [comment]
![image](https://user-images.githubusercontent.com/11614412/53336690-c12cbe00-3907-11e9-8744-18ca3461b134.png)
![image](https://user-images.githubusercontent.com/11614412/53336696-c38f1800-3907-11e9-9cb5-176ef800d709.png)

**Comment by mwolfaardt** [comment]
This is my results

**Comment by mwolfaardt** [comment]
I can also see the total amount is empty 
![image](https://user-images.githubusercontent.com/11614412/53336760-fb965b00-3907-11e9-8d6e-af7033e1c5c9.png)

**Comment by JC5** [comment]
You’ll have to delete that specific transaction. I can’t fix it I’m afraid.

**Comment by mwolfaardt** [comment]
Done, thanks, any idea what caused it?

**Comment by JC5** [comment]
No, it's very strange. I'll build some test cases to see if I can replicate it. If you have any tips just let me know :)

**Comment by Iwen86** [comment]
I had the same behaviour yesterday when I imported some transactions with a csv file which had a few rows without amount. The import process finished without errors but the transaction could not be edited in the webinterface and the value in the database was zero.
I set the correct value by hand in the database and everything was fine (remember to set the value for both transactions with the transaction_journal_id) .

**Comment by JC5** [comment]
Could you send me the uncensored lines and the config you used to import them? I am curious to see what happened.

**Comment by mwolfaardt** [comment]
Mine was also a data import

**Comment by JC5** [comment]
In that case, same question. My email address is thegrumpydictator@gmail.com. I would appreciate receiving the offending lines and your import configuration.

**Comment by Iwen86** [comment]
Hm, sorry I can't reproduce it. Maybe my csv file was erroneous in the first place. Now the importer warns perfectly about transactions without amount. Maybe mwolfaardt can help.
