### ISSUE TITLE
Bills calculated expected total

### ISSUE THREAD

**Issue by woolmonkey** [firefly-iii/firefly-iii#2115]
**Bug description**
I am running Firefly III version x.x.x, and my problem is:
4.7.12 the expected total for bills is wrong if set to anything other then a month.
If I set a bill to twice a month the calculation for expected total is off by one of the amount of the repeated bill.  

**Steps to reproduce**

**Expected behavior**

I would expect the expected bills to show the value for the month.
**Extra info**

**Bonus points**

**Comment by JC5** [comment]
The sum doesn't take the period of your session into account. This won't be changed for the foreseeable future.
