### ISSUE TITLE
Migrate to Firefly

### ISSUE THREAD

**Issue by yohky** [firefly-iii/firefly-iii#2117]
**Description**
Hello dude, I discover Firefly yesterday, it's awesome, thanks a lot !
I migrated from my old app (bank perfect) to yours by making a csv and a lot of rules.

Some features could enhance the process, just ideas, and to be sure they not exist.
 - add column to view tables, it could be set up in admin B.O. (ex : show categorie in expenses, or tags)
 - when come from an other app, on first import, I've made mistakes multiples times (my fault!) but no wipe to redo import. Delete thousands of lines by clicking was not an option : so I reinstall. Maybe propose a full wipe (with 3 confirm dialog box ;) )
- in rules could we add "tokens" ?  Meaning I need to copy field content to another (for me description to note)

**Solution**
That's not requests, just few ideas. You made a huge work, congratulations.

**Comment by TMaddox** [comment]
+1 for undo import

**Comment by JC5** [comment]
Thanks for the compliments!

- Yes, this has been on my list for a while and will be fixed in future versions.
- A full wipe can be done by deleting your account. You can use the mass delete option from any list of transactions if you want to delete a lot of entries.
- This will not be possible. The rules are there to do basic fixes only.

**Comment by lastlink** [comment]
I use a managed shared web host, before I do bulk imports I run a website backup from cpanel so I can “undo” my import. I don’t think this should be a key feature of the service

**Comment by nearwood** [comment]
I also just discovered this app and have been toying around. To "undo" and import I went to tags, click "Show all transactions without grouping them by date", then click the bottom `Select Transactions` button, then scroll to the top of the list to check the single checkbox that selects all transactions, then back to the bottom and in the "Actions" dropdown select "Delete".
