### ISSUE TITLE
Add Action: modify amount

### ISSUE THREAD

**Issue by TMaddox** [firefly-iii/firefly-iii#2118]
**Description**
I would like a rule to be able to modify the transaction amount. In my case halve it (/2)

**Use case**
I got a shared account with a roommate. When I buy stuff for both of us we pay from a shared account, but of course, each of us pays only half the amount.

**What are alternatives?**
If the shared accounts could be really shared with other firefly-iii users, this feature would be redundant for me. Do you plan on implementing this? Or do you encrypt the data per user, making shared accounts impossible/very hard to implement?

**Comment by JC5** [comment]
Sorry, no. The rules are there for basic fixes. If you want to change your imports significantly, either do this beforehand or fix it afterwards.

Firefly III [won't](https://docs.firefly-iii.org/en/latest/support/features.html#often-requested-features) offer the option to share accounts.

**Comment by TMaddox** [comment]
I see, ty
