### ISSUE TITLE
Wipeout database

### ISSUE THREAD

**Issue by rpelissi** [firefly-iii/firefly-iii#2121]
I am running Firefly III version x.x.x

**Description**
I am trying this excellent solution and I have imported some data into it to see how it work into my self hosted firefly 3 setup. How, how can I restart from scratch/wire the database inin order to have a clean db?
Thanks!

**Extra info**
Debug information generated at 2019-02-24 16:34:04 America/Montreal for Firefly III version **4.7.10**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.10 |
| FF API version | 0.9.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.10-0ubuntu0.18.04.1 |
| Display errors | Off |
| Session start | 2019-02-01 00:00:00 |
| Session end | 2019-02-28 23:59:59 |
| Session first | 2019-02-24 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**
Again thank you for this excellent solution :) I HATE dealing with money and budget but your solution make me feel better dealing with money :)

**Comment by lastlink** [comment]
This is database related shouldn’t really be an issue. You should delete your database and create a new one, or you can drop all your tables then navigate to your Firefly III url/install and it will setup if the database still exists and tables have been dropped.

**Comment by rpelissi** [comment]
Hi,
Good point to the 2 options, I will try both just to have the right option :) Thanks!
