### ISSUE TITLE
How can I see my database connection

### ISSUE THREAD

**Issue by mwolfaardt** [firefly-iii/firefly-iii#2126]
I am running Firefly III version x.x.x

**Description**
I've got Firefly up in running in a docker container, how can I bash into the container and see what is the connection string? When the app starts up I can see in the logs that the connection is refused

**Comment by JC5** [comment]
```
docker exec -it <container> bash
```

Then you can do `cat /var/www/firefly-iii/.env` I think

**Comment by mwolfaardt** [comment]
Great thanks, and how do i change it?

**Comment by JC5** [comment]
You can change these things when you launch the Docker instance.

https://docs.firefly-iii.org/en/latest/installation/docker.html

**Comment by mwolfaardt** [comment]
Thank you

**Comment by mwolfaardt** [comment]
for some reason the IP of the database changed
