### ISSUE TITLE
Add support for PostgreSQL SSL connections

### ISSUE THREAD

**Issue by s4ke** [firefly-iii/firefly-iii#2128]
**Description**

I would like for Firefly to add support for setting the SSL certificates used for connecting to the PostgreSQL database. Currently it only uses "sslmode=prefer", but I can not set my ssl certificates properly, so I can not enforce connections on my PostgreSQL instance using ssl. 

**Solution**

Add environment variables to provide the ssl certificates.

**Comment by JC5** [comment]
Which environment variables would that be, and what would be their content?

**Comment by s4ke** [comment]
Oh wow, that was fast :).

I would require something along the lines of:

```
FF_PGSQL_SSL: "true"
FF_PGSQL_SSL_MODE: "verify-full"
FF_PGSQL_SSL_ROOT_CERT: "/certs/rootCA.crt"
FF_PGSQL_SSL_CERT: "/certs/client.crt"
FF_PGSQL_SSL_KEY: "/certs/client.key"
```

see https://www.postgresql.org/docs/9.1/libpq-ssl.html for more info

As a workaround, I currently use this config in pg_hba.conf (from my ansible config):

![image](https://user-images.githubusercontent.com/719760/53364775-d7ef0700-393f-11e9-8efe-b2de2a07c5e0.png)

**Comment by s4ke** [comment]
This way I can enforce the clients to present a valid ssl certificate, but also validate the database server identity, which would prevent man in the middle attacks.

**Comment by JC5** [comment]
I was working on something else anyway, so it was easy to reply.

Keep in mind that you can't put the cert files in that particular folder. You'll have to put them in the volume directory. I would suggest using `firefly_iii_upload` which links to `/var/www/firefly-iii/storage/upload`. This requires some manual labor on your end to set it up.

I assume these would be the default values for the env vars you've shared (the FF_ prefix is not necessary)

```
PGSQL_SSL: false
PGSQL_SSL_MODE: "prefer"
PGSQL_SSL_ROOT_CERT: null
PGSQL_SSL_CERT: null
PGSQL_SSL_KEY: null
PGSQL_SSL_CRL_FILE: null
```

Correct?

**Comment by s4ke** [comment]
I honestly do not care that much where to put them as long as I can provide them to the docker container :). 

What I usually do for my containers is mount my ssl certs to some directory, e.g. "/certs" and then configure my applications to read from that directory. This way my certificate mount does not interfere with application logic.

Yes, these would be the default values.

**Comment by JC5** [comment]
Alright. When I find time I'll update the config to include these.

**Comment by s4ke** [comment]
Great!

**Comment by JC5** [comment]
Laravel does not support the [CRL option](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Connectors/PostgresConnector.php#L168) but I've added keys for the other values. 

In the next version I ask you to play around with it to see if you can get it working. Just check out `.env.example`. If it doesn't work, please let me know.
