### ISSUE TITLE
Heroku deployment failed because of uninstallable Chinese language pack

### ISSUE THREAD

**Issue by sandervankasteel** [firefly-iii/firefly-iii#2129]
**Bug description**
I am running Firefly III version 4.7.14, and my problem is: When I do an `git push heroku master` it fails on the installation of the Chinese lanuge packs

**Steps to reproduce**

Push the latest version of Firefly to Heroku

**Expected behavior**
An upgraded version of Firefly III

**Extra info**

Failure log

```
remote: === Updating or installing language-pack-zh-base
remote: Hit:1 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
remote: Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
remote: Hit:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease
remote: Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
remote: Reading package lists...
remote: Reading package lists...
remote: Building dependency tree...
remote: Package language-pack-zh-base is not available, but is referred to by another package.
remote: This may mean that the package is missing, has been obsoleted, or
remote: is only available from another source
remote: However the following packages replace it:
remote:   language-pack-zh-hant-base language-pack-zh-hans-base
remote: 
remote: E: Package 'language-pack-zh-base' has no installation candidate
remote:  !     Push rejected, failed to compile Locale app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to firefly-finances.
remote: 
To https://git.heroku.com/firefly-finances.git
```

**Bonus points**
I tried to apply this fix as described here(https://github.com/heroku/heroku-buildpack-locale/issues/12) but that doesn't work. So what I did as a workaround is to removed all the Chinese languages.

**Comment by JC5** [comment]
From where did you remove all the Chinese languages?

**Comment by sandervankasteel** [comment]
I removed them from `.deploy/heroku/locales`, these two lines to be exact: https://github.com/firefly-iii/firefly-iii/blob/master/.deploy/heroku/.locales#L10-L11

**Comment by JC5** [comment]
Thanks. I'll do some experimentation with their suggestions (zh-hans_CN).
