### ISSUE TITLE
Expense location using mapbox

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#2131]
Right now if the mapbox key is specified in the .env file then tags can have a location assigned to them. I think it would be much more useful to assign it to an expense account. Would be useful to see locations for like different walmart stores. I don't know if asset & revenue accounts make much sense b/c they'd likely be banks/institutions that the location doesn't really matter.

**Solution**
Add location ability to expense account.

**Related**
#2001 #420

**Comment by JC5** [comment]
I have some plans for this, yes.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19975547
