### ISSUE TITLE
No new transactions if bank require security question using Spectre

### ISSUE THREAD

**Issue by Drudoo** [firefly-iii/firefly-iii#2133]
**Bug description**
I am running Firefly III version 4.7.12, and my problem is:

When i use Spectre to import from a bank (PNC Bank) that require a security question, it does not prompt me for answer, but just shows no new transactions. 

**Steps to reproduce**
- Setup a bank account in Spectre that needs a security question answered.
- Import using Firefly
- Firefly will not give any errors, just show no new transactions to import. 

**Expected behavior**
Either: 
- Prompt for security question
or 
- Show error

**Extra info**
A workaround is to:
- Log in to saltedge
- Go to connections
- Refresh the connection
- In the pop-up window, answer the security question
- Go back to Firefly
- Import using Firefly
- New transactions are importet

This issue could be related to #1879

**Comment by JC5** [comment]
It might be the same problem. I forward the user (you) to Spectre to get authentication. You get back in Firefly III with a token. If the token results in no transactions, there's not much I can do.

After all, Spectre is the one to decide whether or not you need to answer the security question again. 

I would suggest you take it up with them.
