### ISSUE TITLE
YNAB Import fails to link Transfers with revenue Account

### ISSUE THREAD

**Issue by bobokun** [firefly-iii/firefly-iii#2134]
**Description**

After completing the import from YNAB I noticed a lot of messages in the logs that show up as 

`Transaction journal #xxx (user #1, xxxx@gmail.com) is of type "Transfer" but is linked to a "Revenue account". The transaction journal should be recreated.`

When analyzing the transactions I notice that for all the "transfers" I've made in YNAB, it created a revenue account because the account name shown in YNAB has a prefix "Transfer:" for example if my account is called Tangerine Checking and I'm transferring to Tangerine Savings, in YNAB it shows the account as "Transfer: Tangerine Savings" which causes an issue in Firefly because it thinks it doesn't know that it is an asset account. See example: 
![image](https://user-images.githubusercontent.com/12660469/53496645-75495880-3a70-11e9-9f05-e96be52624d6.png)

Is there any quick way to go through all transactions and find anything where there is a "Transfer: " prefix to remove it and convert these transaction from revenue account back to the appropriate asset account?
I've tried to dig into the firefly database but I couldn't figure out which tables I'll need to edit and it seems that all the transactions only show ID and not the description column.

**Extra info**
 
Debug information generated at 2019-02-27 09:14:08 America/New_York for Firefly III version **4.7.14**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.14 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.15 |
| Display errors | Off |
| Session start | 2019-02-01 00:00:00 |
| Session end | 2019-02-28 23:59:59 |
| Session first | 2014-12-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Bonus points**

**Comment by JC5** [comment]
Oh great, it seems YNAB is not very consistent here. That's a shame. I'll pick it up as a fix (to remove the prefix)

You can create a rule that changes the type of the transaction based on the source or destination account. That could fix it, perhaps?

**Comment by JC5** [comment]
I'll push a fix but it's a guess if it'll work.
