### ISSUE TITLE
Years selection in transaction overview shows wrong end date

### ISSUE THREAD

**Issue by Iwen86** [firefly-iii/firefly-iii#2135]
**Bug description**
I am running Firefly III version 4.7.14 and my problem is:

Hey there,

in the overview of transactions I can choose on the right hand side the last few months **or** a complete year  like 2017, 2016, 2015, ... , which results in a link like:
https://your-firefly-iii/transactions/withdrawal/2017-01-01/2017-12-30

But they seem to filter always from January 1st to December **30th**.

So my income which is always scheduled for the last day of a month (e.g. December 31th) won't show up. Just a bug or any reason behind it which I couldn't figure out :)? Seems to be connected with #1968

**Comment by JC5** [comment]
Yep, that's probably a bug. I'll do some digging. Thanks for letting me know.

**Comment by JC5** [comment]
Yep, I see it too. I'll get it fixed for the next release.

**Comment by JC5** [comment]
Will be fixed this weekend. I hope to be able to push a new release today.
