### ISSUE TITLE
Personal Access Tokens

### ISSUE THREAD

**Issue by overload08** [firefly-iii/firefly-iii#2137]
**Bug description**
I am running Firefly III version 4.7.12, and my problem is:

Hi.
After upgrade, all my personal tokens doesn't work. I need to recreate it...

**Steps to reproduce**
Upgrade FireflyIII and test a personal token

**Expected behavior**
Personal token must work after upgrade

**Comment by JC5** [comment]
From which version did you upgrade?

**Comment by overload08** [comment]
From 4.7.11 to 4.7.12.

But same from "I don't remember" to 4.7.11

I can test upgrade from 4.7.12 to 4.7.14 if you want

**Comment by JC5** [comment]
OK, I'll check it out. It could be that it's part of the upgrade, because normal bearer tokens also have to be refreshed. Since this is essentially a bearer token I guess that's the case. But I am not sure yet.

**Comment by JC5** [comment]
Sorry, nothing yet. I was able to upgrade and keep my tokens. The tokens do expire at some point, may that have been the issue?

**Comment by overload08** [comment]
I've upgraded my FireflyIII from 4.7.12 to 4.7.16

Now, i've got this message :
{"message":"Unauthenticated","exception":"AuthenticationException"}
