### ISSUE TITLE
Import transations through Tasker

### ISSUE THREAD

**Issue by XeonStaf** [firefly-iii/firefly-iii#2139]
Hi!
I am running Firefly III version 4.7.10

**Description**
I want to import my transactions through tasker. 
Bank->Sms->Tasker->API->Firefly
I have been trying to use Taske plugin RESTask, but i can't use variable in custom body. (without variable it work perfect)

Also I have try use JavaScriplet and call this task, but it didn't work.
```
const url = global('%FF_ADDR') + local('par1');
const token= 'Bearer ' + global('%FF_AUTH');
const xhttp = new XMLHttpRequest();
xhttp.open('POST', url, false);
xhttp.setRequestHeader('Authorization', token);
xhttp.setRequestHeader('Content-Type', 'application/json'); 
xhttp.send(local('par2'));
if( xhttp.status != 200 ) { 
    console.error(xhttp.status + ' - ' + xhttp.responseText); 
}
```
Why this code isn't work?
And what else I can to do?

**Comment by JC5** [comment]
Is this Tasker the Android app?

The bearer token must be a "Personal Access Token".

Could you share the errors you're getting? I hope you understand I can't guess what's happening without a bit more info.

**Comment by emansih** [comment]
Upload your full profile here or taskernet

**Comment by XeonStaf** [comment]
This task work!
You just need to correctly filled token and adress in variable (what i forget to do)
Thanks!
