### ISSUE TITLE
Default financial report showing wrong currency

### ISSUE THREAD

**Issue by brightonjack** [firefly-iii/firefly-iii#2142]
**Bug description**
I am running Firefly III version 4.7.14. I have accounts in different currencies, namely British Pounds and Euros. My default currency is Euros. I am running the default report on a single account whose currency is in British Pounds, however the bottom half of the Default Report shows the Euro currency symbol.

**Steps to reproduce**
1. Make sure the default currency is Euros.
2. Go to Reports.
3. Select "Default financial report" as the report type.
4. Select a single account whose currency is in British pounds (or any other currency other than the default currency) as the Included accounts. 
5. Press Submit.
6. Budgets and Categories tables in the bottom half of the report will show Euro symbol next to the figures.

**Expected behavior**
I would expect to see the Budgets and Categories tables in the bottom half reflect the account's currency, not the default currency.

**Extra info**
Debug information generated at 2019-03-03 13:24:14 Europe/Berlin for Firefly III version **4.7.14**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.14 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.15-0ubuntu0.18.04.1 |
| Display errors | Off |
| Session start | 2012-12-22 00:00:00 |
| Session end | 2013-03-21 00:00:00 |
| Session first | 2011-01-22 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Comment by JC5** [comment]
Hi,

I know. Most reports will fall back to the default currency because it *could* contain multiple currencies. This is a permanent work-in-progress I'm afraid. I'm working on getting all charts and lists to support multiple currencies. If there's really just one currency in the report you'll just have to imagine it says GBP :wink:

**Comment by brightonjack** [comment]
Thank you for the reply. I thought so. But I thought if there was a single currency in the selected account(s), then I thought firefly could simply use that account's currency as a workaround in the interim.

The decision is yours :)
