### ISSUE TITLE
How do you delete all transactions?

### ISSUE THREAD

**Issue by s3w47m88** [firefly-iii/firefly-iii#2143]
I'm experimenting and need to delete all transactions but cannot locate a simple way to do this. Does one exist? If not, would a pull request be accepted if I submitted it?

Thanks!

**Comment by JC5** [comment]
You can use the mass selection button to select all transactions on a page, then delete them.

**Comment by s3w47m88** [comment]
Thanks for the reply. I don't have an "All Transactions" page. And I don't see anything resembling or indicating a mass select on Expenses, Revenue / income or Transfers page. The only bulk select only works for items current visible on the page. In my case I have thousands of transactions paginated across like 50 pages. And the "Show Everything" link that sometimes appears in the lower right doesn't actually show everything.

**Comment by JC5** [comment]
Yes, that's the one I mean. You can make your pages bigger in your preferences, so you can delete more transactions. If you have 2500 transactions to delete it might be easier to delete your account and register again.

**Comment by s3w47m88** [comment]
Thanks. That got me far enough. Would you accept a pull request for add a true "Delete All Transactions" option? Also a PR for keeping the Select All Button (bottom right), respective Checkbox (top left once button is clicked) and Bulk Actions (bottom left once you've select items) to be at the top AND bottom all together? Right now you have to scroll down, click, scroll up, click, scroll back down click.

**Comment by JC5** [comment]
I have something on my list to add mass cleanup buttons. But I happy to see the buttons at the top as well!
