### ISSUE TITLE
Duplicate transactions Bunq

### ISSUE THREAD

**Issue by koenbud** [firefly-iii/firefly-iii#2145]
**Bug description**
I am running Firefly III version 4.7.15, and my problem is: Bunq imports duplicate transactions

**Steps to reproduce**
I've used the Bunq import feature multiple times successfully in the last few weeks (including yesterday). Today I ran import again and it seems to import almost the entire transaction history again. There are about 30 of these errors also:
 
`Row #10 ("[DESCRIPTION REMOVED]") could not be imported. It already exists.`

**Expected behavior**
I expected Firefly to only import todays transactions, because I ran import successfully yesterday.

**Extra info**
Could it be that the Bunq api response changed which made Firefly see this as a new transaction, rather than a duplicate transaction? The API documentation doesn't mention any updates/changes though.

```Debug information generated at 2019-03-04 22:04:28 UTC for Firefly III version **4.7.15**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.15 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.15 |
| Display errors | Off |
| Session start | 2019-03-01 00:00:00 |
| Session end | 2019-03-31 23:59:59 |
| Session first | 2017-11-12 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 4 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |
```

Please let me know if I can help.

**Comment by koenbud** [comment]
I'm looking at the keys of the imports and only older Bunq imports are affected. My most recent imports are not duplicated.

**Comment by JC5** [comment]
Yes, this is an unfortunate side-effect of a database change I can't fix I'm afraid. Sorry about that. Once imported (and deleted again) it should no longer complain about duplicates.

**Comment by koenbud** [comment]
Thanks for your answer. I've resolved the issue using your solution.
