### ISSUE TITLE
Piggy banks and account balance

### ISSUE THREAD

**Issue by vitobotta** [firefly-iii/firefly-iii#2146]
Hi! First of all thanks a lot for this software, I am looking to switch from YNAB and so far I like it.

I have just started setting things up, and one thing I don't get is how piggy banks work... I have created some piggy banks with a target amount and a date, and have added some money to each piggy bank for the current month (by clicking the + button), but the account balance shown seems to ignore the amounts I added to the piggy banks. So if the balance without taking piggy banks into consideration is say 1000, and the total saved so far for the piggy banks is 400, the balance shown in the accounts list etc is still 1000, when I would have expected 600 instead. What am I missing? Am I misunderstanding how piggy banks work?

I am running the latest version.

**Comment by JC5** [comment]
The account balance is not changed when you collect money in piggy banks. It's just a grouping of amounts.

**Comment by vitobotta** [comment]
Hi James, thanks. Shouldn't the amounts saved for the piggy banks be treated as "spent" so that money is actually reserved for those piggy banks? Otherwise what happens if I "save" some money for piggy banks but then that money actually gets spent because account balance and budget don't take it into consideration? Still trying to understand how it works. Thanks!

**Comment by JC5** [comment]
Nah, it's entirely up to the user. The bottom of the page at /piggy-banks will reflect the amount of money left but the balance will remain the same.

**Comment by vitobotta** [comment]
OK, thanks...
