### ISSUE TITLE
Support for bails

### ISSUE THREAD

**Issue by TMaddox** [firefly-iii/firefly-iii#2147]
**Description**
How about adding the support for bails?

**Solution**
Maby a new account type for bails? Or allow negative amounts on "dept" or "loan"?

**Use case**
If I borrow a boat in my holidays, I need to pay a bail, to give the owner a security in case I damage the boat.

**Comment by JC5** [comment]
Nah. That's a very narrow use case.

**Comment by TMaddox** [comment]
Any idea how to input it at the moment?

**Comment by JC5** [comment]
What I do myself is use an asset account for these occasional expenses.

**Comment by TMaddox** [comment]
That's a great idea, thank you!
