### ISSUE TITLE
Last X days and budgets

### ISSUE THREAD

**Issue by Wr0ngName** [firefly-iii/firefly-iii#2149]
**Bug description**
I am running Firefly III version 4.7.15, and the issue is:

When selected main display period to "Last thirty days", budget tag "LEFT TO SPEND" turn to "OVERSPENT". This differs from the /budgets page and therefore brings confusion.  It seems the top item is not taking in consideration the budgets for the transaction period. This is also the case with "Last seven days" it seems. "Today" and other options do not seem impacted.

**Steps to reproduce**
Having a deployment with budgets and transactions is a requirement to run tests.
Steps:
- Go to main page
- From the top banner dropdown menu, select one of the mentioned item "Last 30 days" or "Last 7 days"
- Spot the top item showing the money left allocated to the budget "LEFT TO SPEND", turning into red as "OVERSPENT" shows

**Expected behavior**
As I go into the /budgets management page, two things: on "Last seven days", everything at zero, woops. But for the "Last thirty days", it shows for the previous or current month, no idea which one it chooses and how. The expected behavior would be to have these transactions linked to their budgets as with other time periods, so that the main page does not show these erroneous data. The /budgets would show the budget for the current month, nothing fancy?

**Extra info**
I just got the update running and am pretty happy to test and try the awesome work!

**Bonus points**
First on one full month, next on one week. From what it shows, it seems that none of the transactions were actually budgeted:
![image](https://user-images.githubusercontent.com/1737010/53841445-17030500-3f9d-11e9-84c6-a9dd851886f4.png)
I don't think logs would be useful, this seem quite common, and should be fairly easy to reproduce (already done on demo website, same behavior).

Keep up, amazing work, thanks!

**Comment by JC5** [comment]
Hi,

Thanks for the compliments!

The available amount can be set from the /budgets page (just above the top bar). It is applicable to the current period _only_. So if your view is "1 Mar / 31 Mar" the available amount will be applicable to that period only. If you change the period using the date selector the available amount will appear to reset because there is no known available amount, until you set one.

So if you set an available amount for 27-Feb to 26-Mar, it will display in the top box if and only if the date range is also 27-Feb to 26-Mar.

In this case, the following things happen.

- Current period is 1-Mar / 31-Mar.
- An available amount is set for this period on the /budgets page (EUR 2000)
- The bar on /budgets and the "left to spend" box are equal.
- User changes to "last 7 days", aka Feb-27 to Mar-6
- There is no available amount for this period and Firefly III will not calculate one automatically.
- The box on the front page will start from 0, going into the red immediately. 
- The /budgets page will show amount available as 0 as well.

Transactions are always budgeted. But the available amount isn't calculated for custom periods.

**Comment by Wr0ngName** [comment]
Hi,

Thanks for the answer!

Thing is, does a budget in a time-shifing window make sense? I mean, planning for the "Next 7 days", 30, maybe more, I could see the application if done differently, but budgeting the last X days doesn't seem to be the main use case.

Quick illustration:
- Date range is 26-Feb / 27-Mar
- I enter a budget
- Next day, date range goes 27-Feb / 28-Mar, budget goes empty

The actual budget allocated for February is not taken into account, neither is the one for March, despite the current day (March 27 then 28 in the example) belonging to the period, and past transactions being allocated to budgets for their respective periods.

On the other side, in your example it seems that you allocate a budget to a past time span. Allocating a budget for a past period is not the way for someone to actually use it, perhaps I'm wrong? How do you make use of it?

My way of seeing it would be to have a different behavior regarding budgets for these Last X days situations: 
- Having the budget for the current date's period seems a resonable and easy enough to be understood
- To be more precise, the main page could focus on the overspent from first budget on the running period if any (Feb) + from the ongoing budget (Mar) deduced of the daily money allocation for the days outside the period seen (and could start counting the overspent for the ongoing period on the same idea).

As I understand, you cannot get the budgets because you need a start and a stop. This is a technical limitation? I propose here to have the daily amount calculated for as a reference, which, if possible, represents the closest approximation to the a real budget on the period?

On a KISS basis, I would sugget, splitting the budgets page and the top item in two, to show both budgets and their respective balance, if combining them based on a daily average sounds too mystical. As useful, if not more in some edge cases, and more easily understandable? I throw it out, as categories are already shown as such on the main page's graph.

I would really like to try a push request, at least try it out for myself, and as an illustration, let's see if I can manage that.

Thanks for sharing, always learning :-)

**Comment by JC5** [comment]
I want to keep the budgets and the available amounts focused on similar periods, like weeks or months. The option to go back X days was built at the request of some users but I wasn’t planning on editing the budgets to match. 

In my example, it works equally well if you move forward using the date selector on the budget page or the top right date selector. 

But the page needs an overhaul and I’m thinking about the best way forward.

**Comment by Wr0ngName** [comment]
I see the point, and I get it. I'll deal with that, honestly I only use the last X days options for the graphs to be more representative.

Thanks for your time!
