### ISSUE TITLE
Firefly broke after reboot

### ISSUE THREAD

**Issue by calgara12** [firefly-iii/firefly-iii#2151]
I am running Firefly III version 4.7.15

**Description**
I installed firefly yesterday with docker and everything worked pefectly until today when i restarted my server (I am running Ubuntu Server 16.04). I set firefly up with traefik a reverse proxy to be accessible with firefly.domain.com. This also worked until my reboot

When i now try to reach firefly.domain.com i get the bad gateway message. And i cant reach it. So then i tried accessing it in my local network with 192.168.0.xxx:xxxx and it loads really really long, sometimes i get to the login page of firefly and sometimes i get the "This site cant be reached" message in chrome.

**What i already tried**
- restarting my server
- recreating the container off the app itself (not the db container i was afraid that i was gonna lose all my data)
- restarting both containers

**Extra info**
- Browser: Chrome
- OS: Ubuntu Server 16.04
- Logs of my DB container https://pastebin.com/wVak5w4g

Thanks in advance. :)

**Comment by JC5** [comment]
Tricky. I've been able to reboot my own Docker instance just fine so I expect something local. But what it could be, I have no idea.

Do you have volumes created for the Firefly III upload and export directory? Do you have volumes for the database server's storage location? Could you re-download the image for Firefly III perhaps?

**Comment by calgara12** [comment]
Thanks for your fast reply, 
I have 3 volumes:
- firefly_iii_db
- firefly_iii_export
- firefly_iii_upload

I tried to delete the db container and run it again, but the issue still persists. Any suggestion what i can do?

**Comment by JC5** [comment]
Not really no, sorry about that. I’m not well versed in Traefik or the setup you’re using. You can trace the logs from Firefly III using something like “docker logs -f [container]” to see what’s happening.

**Comment by calgara12** [comment]
Ok thanks anyway, the logs i linked in my first post dont give away anything for you?

**Comment by JC5** [comment]
No, that’s pretty standard. The migrations always fire and the errors are caught and ignored by Firefly III.
