### ISSUE TITLE
Rolling balance column in the lists

### ISSUE THREAD

**Issue by aclex** [firefly-iii/firefly-iii#2152]
I think, it would be very useful to have rolling balance (i.e. the total account (selection or whatever the list belongs to) balance after the transaction of the current line) column in the lists of transactions of certain account or during checking. Now it's possible to get this value from the graph, but having it as another column seems a little bit more handy. I've actually just done a switch from desktop budget application (KMyMoney to be exact), this is a common feature in several of them there, so sorry, if it's just my habit :)

And also thank you very much for your efforts of Firefly III development, tried it, I think, two or three times before considering to switch to it and now I found it ready! Enjoying so much with new features and reports. Thank you!

**Comment by JC5** [comment]
Thanks for the compliments!

You could try the "audit report" under `/reports` perhaps? It features the column you're looking for. It's not part of the standard overview because it gets too crowded but I expect you'll find the report to be useful.

**Comment by aclex** [comment]
@JC5 Oh, nice, thanks for the suggestion, this is what I wanted to see. Why I want this to see is I have to enter my transactions manually, so this column helps a lot to see, where I missed something and balance started to differ) But yes, I agree on the compact size of the standard overview, it really clean and informative now. Maybe just a column chooser is expected here, but I may just not notice it)

Thanks again and good luck with the development!

**Comment by panixx** [comment]
I would also like to see this feature. Maybe make it configurable so those that dont want it or feel it clutters the screen too much can disable it.

**Comment by JC5** [comment]
A column picker is on the list, thanks for the suggestion guys!

**Comment by aclex** [comment]
@JC5 thanks for considering to accept it! Hope it will be useful for many users of Firefly III.
