### ISSUE TITLE
Cannot change asset account type if credit card is chosen

### ISSUE THREAD

**Issue by Aerion** [firefly-iii/firefly-iii#2153]
I mistakenly changed one of my assets account to credit card. When I wanted to change it back I had an error because I didn't specify any Credit card monthly payment date.

Steps to reproduce:
1. Create an asset account with type **credit card** 
2. Edit the account type to Default asset account
3. Error message on save: **The cc monthly payment date is not a valid date.** 

Expected behavior:
3. Asset account type is changed to Default asset account

The quick and dirty workaround I found on the client side is to delete the div _Credit card options_  and save. My asset account was then successfully changed from credit card.

If I may add, when creating a credit card asset account, the field Credit card monthly payment date isn't present, so **not required**
 But it is **mandatory on edit**. It's weird to have a field required but if I never edit the account I wouldn't know.

Firefly version: 4.7.14

_Thank you for your work, I love it._

**Comment by JC5** [comment]
Thanks :)

I’m aware of the issue and I’ve planned a fix. Not sure yet when. 

You could also enter a date to make the form work.
