### ISSUE TITLE
Firefly goes to 404 page after deleting any record/transaction after upgrading to 4.7.16

### ISSUE THREAD

**Issue by airbillion** [firefly-iii/firefly-iii#2159]
I am running Firefly III version 4.7.16

**Description**
Firefly goes to 404 page after deleting any record/transaction after upgrading to 4.7.16

**Extra info**

Debug information generated at 2019-03-08 10:01:42 America/New_York for Firefly III version **4.7.16**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.16 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.15 |
| Display errors | Off |
| Session start | 2019-03-01 00:00:00 |
| Session end | 2019-03-31 23:59:59 |
| Session first | 2018-08-10 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

![firefly error](https://user-images.githubusercontent.com/11315828/54036602-02d02b00-418a-11e9-9969-0703f34ceca8.PNG)

Hello,

I just updated the Docker version of Firefly from 4.7.15 to 4.7.16...and now when I delete anything I get directed to a 404 error page...If I go back a few pages in my browser and refresh the page the record has been deleted, but I cannot seem to delete anything anymore after this latest upgrade...

Any help would be appreciated!

Thank you!

Edit:

I rolled back the docker version to release-4.7.15 and do not have this issue...

**Comment by JC5** [comment]
Yep, you get redirected back to the page you just came from. Since it got deleted, it will give this error. I'll see if a quick fix is available.

**Comment by airbillion** [comment]
Hello,

Great!  Thank you for letting me know!

Glad it will be sorted out.

**Comment by digita1ist** [comment]
I have exact the same behaviour. After I've deleted an asset account it disappeared after I went back from the 404 page to the asset account overview but in my user profile data under /admin/users/show/1 the number of accounts hasn't been decreased.

**Comment by JC5** [comment]
On it.

**Comment by JC5** [comment]
This will be fixed in the next release.
