### ISSUE TITLE
Docker container environment flag DB_CONNECTION=pgsql being ignored

### ISSUE THREAD

**Issue by driverjb** [firefly-iii/firefly-iii#2160]
**Bug description**
I am running Firefly III version 4.7.16 deployed in a docker container. According to the documentation, if you want to use Postgres as your back end, you are to set the additional environment variable:

`DB_CONNECTION=pgsql`

This doesn't work. You will get the 'Be right back' page. Jumping into the container `docker exec -it firefly bash`, installed vim, and opened the .env file. The value, DB_CONNECTION is not set. I set it to `pgsql` and refreshed my browser. All is well.

Just for kicks, I rewrote my docker run command, and this time instead of using the documented `DB_CONNECTION` variable, I changed it to `FF_DB_CONNECTION=pgsql`. Started up a brand new container. Worked as expected. This is a bug, one of two things should occur:

Either change the documentation to set the `FF_DB_CONNECTION` flag to `pgsql` or correct the scripts to properly acquire the value of `-e DB_CONNECTION=pgsql` and set it appropriately in the .env file when the container is built.

dockerRun.sh before (fails to set DB_CONNECTION=pgsql)
```docker
#!/bin/bash
docker run -d \
  --name firefly \
  --restart always \
  -v /docker/firefly/export:/var/www/firefly-iii/storage/export \
  -v /docker/firefly/upload:/var/www/firefly-iii/storage/upload \
  -p 4001:80 \
  -e DB_CONNECTION=pgsql \
  -e FF_APP_ENV=local \
  -e FF_APP_KEY=<a 32 character string> \
  -e FF_DB_HOST=<pgsqlhost> \
  -e FF_DB_NAME=<dbname> \
  -e FF_DB_USER=<theuser> \
  -e FF_DB_PASSWORD=<thepassword> \
  jc5x/firefly-iii:latest
```

dockerRun.sh after I tweaked it to the undocumented variable FF_DB_CONNECTION=pgsql
```docker
#!/bin/bash
docker run -d \
  --name firefly \
  --restart always \
  -v /docker/firefly/export:/var/www/firefly-iii/storage/export \
  -v /docker/firefly/upload:/var/www/firefly-iii/storage/upload \
  -p 4001:80 \
  -e FF_DB_CONNECTION=pgsql \
  -e FF_APP_ENV=local \
  -e FF_APP_KEY=<a 32 character string> \
  -e FF_DB_HOST=<pgsqlhost> \
  -e FF_DB_NAME=<dbname> \
  -e FF_DB_USER=<theuser> \
  -e FF_DB_PASSWORD=<thepassword> \
  jc5x/firefly-iii:latest
```

**Comment by JC5** [comment]
Feel free to write a PR to update the docs. Not sure what you expect from me otherwise.

**Comment by driverjb** [comment]
Will do, sorry new to this kind of thing on Github.
