### ISSUE TITLE
Run rule on future transactions

### ISSUE THREAD

**Issue by cpapaiz** [firefly-iii/firefly-iii#2161]
**Description**
- I would like Firefly III to be able to apply rule on future transactions

**Additional context**
I have imported all future interest transactions on my mortgage but they all loaded in Asset Account.
I would like to run a rule to change all source accounts to my mortgage(liability) account but the rules are only applied on past transactions

**Comment by JC5** [comment]
Sorry, no.

**Comment by cpapaiz** [comment]
Wow, you already replied! Thought you’d be out ...

Let me try to convince you then... 😆

Just kidding..  I have a few extra questions and maybe I can work out something from here...

1) Is the date filter applied only in the UI? 
2) is performance the reason for it ?
3) can I bypass it via API?

Let me add a little background now: I got to a point that spreadsheets aren’t working for me anymore. I have accounts in 3 banks, multiple loans, multiple monthly recurrent expenses and I am mostly worried about the future, since the past is settled so far.

I began looking for a solution to my mess sometime last month, on my spare time and I got really impressed by firefly features and how fast I got it up and running, so I decided to stress it a little more.

I have imported all my monthly payments on my mortgage (up to 2053) and successfully applied a rule to convert them to transfers upon import(that’s why I think the date filter is UI only) but if I don’t import interest transactions as financial expenses in my liability account , the balance won’t match.

So I tried importing them and ran into some issues:

1- I can’t import into liability account 
2- I can’t run a rule on all transactions and change the source account(future transactions)

I won’t give up easily. If applying rules on future transactions is really a no go, I might create all accounts as assets and try again...

Anyway, thank you very much for your attention, and for what you’ve done so far.

**Comment by JC5** [comment]
1. Yes
2. No.
3. The API won't complain about it. 

I see what you're trying to do but unless you are 100% sure your mortgage won't change for the next 30 years it seems a bit weird to do this.

Having said that I am working on improved liability management.

**Comment by cpapaiz** [comment]
Yeah.. Brazil is a weird country. We have 35 year long pre-fixed interest rates.... it is high as f*ck, but at least it is predictable.
