### ISSUE TITLE
Can't login with SSL

### ISSUE THREAD

**Issue by ffidan61** [firefly-iii/firefly-iii#2162]
I am running Firefly III version 4.7.16

**Description**

Hi there,

First thanks to all devs for this amazing software. I managed to install it with docker. Now I wanted to be able to add transactions outside my home network. So I added it so my Nginx Proxy Manager. And ot  works as long as SSL is deactivated. When I want to login in with SSL forced I only can see the login page but won't able to login.

Do I have to configure webhooks or other configurations to be able to connect to firefly with SSL?

**Extra info**
 
Ubuntu 18.04 LTS
Docker

Debug information generated at 2019-03-09 18:32:46 Europe/Amsterdam for Firefly III version **4.7.16**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.16 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.15 |
| Display errors | Off |
| Session start | 2019-03-01 00:00:00 |
| Session end | 2019-03-31 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Bonus points**

**Comment by pkoziol** [comment]
Sounds like: #2094 
Try setting environment variable `TRUSTED_PROXIES=**`

**Comment by ffidan61** [comment]
Well that was easy :) Thanks
