### ISSUE TITLE
'Be right back' error after attempting to upgrade from 4.7.15 to 4.7.16 or 4.7.17

### ISSUE THREAD

**Issue by UhtredTheBold** [firefly-iii/firefly-iii#2163]
**Bug description**
I am running Firefly III version 4.7.15 in docker and I am unable to upgrade beyond this version. Once I attempt to upgrade further I get an error page saying 'be right back'.

Pull docker image for 4.7.16 or 4.7.17 and attempt to upgrade to them.

I originally got this error trying to upgrade from 4.7.10 to 4.7.17. When this failed I performed successful upgrades version by version (excluding 4.7.11 which also failed due to #2076) until I found I could go no further than 4.7.15.

`[2019-03-10 20:16:49] local.ERROR: SQLSTATE[HY000] [2002] Connection refused (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1) at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)`

**Comment by JC5** [comment]
“Connection refused” is not caused by anything in Firefly III.

**Comment by UhtredTheBold** [comment]
Indeed, it was my environment settings where I had 'DB_HOST=db' instead of 'FF_DB_HOST=db'. All my other env settings have the FF_ prefix so I must have omitted this one for a good reason.

Quite how it's worked from 4.6.x all the way up to 4.10.15 I'm not clear on, but I won't lose any sleep over  it :)

**Comment by JC5** [comment]
I plan to fix this in the next release. Your post gave me a hint, thanks.

**Comment by bmols** [comment]
I'm experiencing a similar problem after upgrading from 4.7.8 to 4.7.18.

`[2019-03-26 07:45:03] local.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'fireflyiii'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = fireflyiii and table_name = users) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'fireflyiii'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = fireflyiii and table_name = users) at /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'fireflyiii'@'localhost' (using password: NO) at /var/www/html/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'fireflyiii'@'localhost' (using password: NO) at /var/www/html/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
[stacktrace]
`
That is one thing I notice looking at the log files. It should be using a password and the password in the .env file is right.

**Comment by JC5** [comment]
But it isn't: `Access denied for user 'fireflyiii'@'localhost' (using password: NO)`.

I am sorry, but don't believe it's caused by Firefly III.

**Comment by bmols** [comment]
Solved it.

Turns out my database password with a '#' in it didn't cause a issue in the earlier install, but was causing issues in the current version because my password didnt have quotes around it in the .env file.

**Comment by JC5** [comment]
Thanks for letting me know. I've seen similar issues and I think I can fix this.
