### ISSUE TITLE
DB password using backslash in 4.7.16

### ISSUE THREAD

**Issue by Drudoo** [firefly-iii/firefly-iii#2165]
**Bug description**
I am running Firefly III version 4.7.16, and my problem is:

When upgrading to 4.7.16 i get the error:
`firefly_iii_app    | Failed to parse dotenv file due to an unexpected escape sequence. Failed at ["pass\word"].`

This only happens at .16 and using .15 works fine. I tried to escape the backslash, but that did not fix the problem. I had to roll back. 

**Steps to reproduce**
Have a database password that contains `\`

**Expected behavior**
Accept password when escaped using single or double quotes or `\\`

**Comment by JC5** [comment]
I suggest you use a password without backslashes.
