### ISSUE TITLE
Firefly installation issue on Ubuntu 18.0.4

### ISSUE THREAD

**Issue by devolper102** [firefly-iii/firefly-iii#2171]
I am running Firefly III version 4.7.4

**Description**

I have followed all the step mentioned to install firefly on Ubuntu 18.4.0 but facing an error after adding config same as firefly tutorail but with my domain. I have attached the screenshot of the issue I am facing. I have successfully completed all the steps but facing issue when try to restart nginx after config setting.

http://prntscr.com/mx2h43

- Muhammad Sikander

**Comment by JC5** [comment]
The SSL error is literally in the error you shared.

**Comment by devolper102** [comment]
So I have to create SSL right?

**Comment by JC5** [comment]
Yes.
