### ISSUE TITLE
HTTP 404 after deleting a tag

### ISSUE THREAD

**Issue by tjedrowald** [firefly-iii/firefly-iii#2175]
First of all thanks for all the awesome work on Firefly :+1: 

**Bug description**
I am running Firefly III version 4.7.16, and my problem is: that after deleting a tag I get redirected to the (deleted) tag, which results in a 404.

**Steps to reproduce**
1.Make a new tag (or use an existing one)
2. Click on the tag (to show its details)
3. Remove the tag by clicking on the trash
4. Confirm that you want to delete the tag
5. Firefly shows a 404 page

**Expected behavior**
Redirect to the page with all the tags (<host>/tags).

**Extra info**
Perhaps there is a broader problem with routing after deleting entities (see issue #2159 )

**Comment by JC5** [comment]
#2159
