### ISSUE TITLE
Login page not showing

### ISSUE THREAD

**Issue by Kyle9982** [firefly-iii/firefly-iii#2177]
I am running Firefly III version x.x.x

![image](https://user-images.githubusercontent.com/42327407/54484022-56daaf80-481b-11e9-8ac4-df3dbdef12a6.png)

I have made some changes in the apache configuration and now I am getting this error

Here is my apache config

```
<VirtualHost *:443>
        Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
        ServerName CustomCloudAdmin
        ServerAlias admin.customcloud.ca
        #Documentroot /var/www/html/customcloud.ca
        ############################### <--- Removed Item
        ############################### <--- Removed Item
        Alias /finance /var/www/html/firefly-iii/public

        <Directory "/var/www/html/firefly-iii/public">
                AllowOverride ALL
        </Directory>

        SSLCACertificateFile /ssl/selfsigned/myCA.pem

        <Location>
                SSLRequireSSL
                SSLVerifyClient require
                SSLVerifyDepth 10
        </Location>

        SSLEngine on
        SSLCertificateFile /ssl/selfsigned/dev.customcloud.ca.crt
        SSLCertificateKeyFile /ssl/selfsigned/dev.customcloud.ca.key
</VirtualHost >
```

**Comment by JC5** [comment]
I think it's asking Firefly III to service page "/finance/login" instead of "/login" and naturally that doesn't work. But I don't know enough about Apache to correct it.

**Comment by vins31** [comment]
I got the same issue with aliases.

I found two workarounds: 

1. create a new virtualhost set the Documentroot to /var/www/html/firefly-iii/public
or
2. serve the parent directory of /var/www/html/firefly-iii which is explained to be unsecure.
