### ISSUE TITLE
Import Transaction always has today's date.

### ISSUE THREAD

**Issue by falcon397** [firefly-iii/firefly-iii#2178]
**Bug description**
I am running Firefly III version 7.2.15, and my problem is:

When I try to do a CSV import from Chase bank, the date comes back with today's date instead of the date in the CSV.  I did check out the other tickets that were like this, I don't believe this is an issue with my settings, but I'd love another opinion.

**Steps to reproduce**
Login to Firefly UI.
Select Import and export > Import transactions.
Select Import File icon.
Choose CSV file (attached).
Choose Configuration file (attached).
Click Upload Files.
Click Continue.
Click Continue.
Once processing completes I select the new tag to view my imported data.

**Expected behavior**
I expect to see the dates that the CSV file contains.

**Extra info**
I am running Firefly III from a Docker container on a Debian Linux host.
I am using version 7.2.15 because I the container for latest does not seem to work, this is the latest version that seemed to work.
This instance is supported by a MySQL database.
I am behind a reverse proxy, but accessibility isn't an issue.
My other accounts import dates as expected, it seems to be unique to Chase Bank CSV's.
Docker logs report everything processed normally:
&nbsp;&nbsp;&nbsp;&nbsp;[2019-03-17 00:08:58] local.NOTICE: Done storing. Firefly III has stored 10 transactions.

**Bonus points**
![image](https://user-images.githubusercontent.com/16735223/54486913-36771900-484c-11e9-8b1f-09127942a6bc.png)

Here's the 2 test files I'm using to get this result:
[ImportTestFiles.zip](https://github.com/firefly-iii/firefly-iii/files/2974878/ImportTestFiles.zip)

Godspeed.

**Comment by JC5** [comment]
Make sure you use "Date", not one of the other date fields for at least one date field.

**Comment by falcon397** [comment]
Correct.  I wasn't aware it needed that, in hindsight it seems a bit obvious now.  Thanks.

**Comment by JC5** [comment]
It's OK. I'll update the docs to mention this.

**Comment by mikegeeezy** [comment]
I'm having this same issue running 4.7.17.3 in a docker.  I did it several times just to make sure I wasn't overlooking something.  I tried selecting + mapping the Date field and some of the other Transaction Date fields but they all come through with todays date.

![image](https://user-images.githubusercontent.com/26230753/62016549-68907400-b178-11e9-89cb-5de706ea85d1.png)

**Comment by JC5** [comment]
Please share with me the config file and some example lines over e-mail.
