### ISSUE TITLE
Deleting a piggy bank returns 404

### ISSUE THREAD

**Issue by ZoserLock** [firefly-iii/firefly-iii#2181]
**Bug description**
I am running Firefly III version 4.7.16, and my problem is:

When I delete a Piggy Bank (after the confirmation) firefly return 404.

Please note that the piggy bank is effectively deleted it is just that firefly does not return to a page after the deletion.

**Steps to reproduce**
* Create a Piggy bank
* Delete the piggy bank
* Notice that firefly return a 404 page.

**Expected behavior**
* Firefly should return to another page not a 404 page.

**Extra info**
Debug information generated at 2019-03-17 13:44:41 America/Santiago for Firefly III version **4.7.16**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.16 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.15-0ubuntu0.18.04.1 |
| Display errors | Off |
| Session start | 2019-03-01 00:00:00 |
| Session end | 2019-03-31 23:59:59 |
| Session first | 2019-01-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

![2019-03-17 13_40_03-Delete piggy bank _test_ » Piggy banks » Firefly III](https://user-images.githubusercontent.com/3060653/54494616-02870c80-48bb-11e9-9a6e-4431d9eaf5cb.png)
![2019-03-17 13_40_06-404](https://user-images.githubusercontent.com/3060653/54494618-04e96680-48bb-11e9-8742-fd46c37a3aa3.png)

**Comment by JC5** [comment]
This is fixed in 4.7.17, which came out this afternoon :)
