### ISSUE TITLE
ImportTransaction cannot handle role "generic-debit-credit"

### ISSUE THREAD

**Issue by Dainius14** [firefly-iii/firefly-iii#2182]
**Bug description**
I am running Firefly III version 4.7.17 and my problem is:

Importing from .csv file fails on deciding on credit/debit indicator value with error:

`Job could not be started or crashed: The import routine crashed: ImportTransaction cannot handle role "generic-debit-credit" with value "C"`

**Steps to reproduce**
Have a line in .csv where debit/credit indicator is K/D (my bank specific). Import data.

**Expected behavior**
Values `K`(kreditas, lithuanian language) or `C` are used as credit indicator and value `D` as debit indicator.

**Bonus points**
Stack trace from the log file!
```
[2019-03-18 21:02:11] local.ERROR: The import routine crashed: ImportTransaction cannot handle role "generic-debit-credit" with value "K"
[2019-03-18 21:02:11] local.ERROR: #0 /var/www/firefly-iii/app/Support/Import/Routine/File/ImportableCreator.php(66): FireflyIII\Support\Import\Placeholder\ImportTransaction->addColumn
Value(Object(FireflyIII\Support\Import\Placeholder\ColumnValue))
#1 /var/www/firefly-iii/app/Support/Import/Routine/File/ImportableCreator.php(49): FireflyIII\Support\Import\Routine\File\ImportableCreator->convertSet(Array)
#2 /var/www/firefly-iii/app/Support/Import/Routine/File/CSVProcessor.php(72): FireflyIII\Support\Import\Routine\File\ImportableCreator->convertSets(Array)
#3 /var/www/firefly-iii/app/Import/Routine/FileRoutine.php(57): FireflyIII\Support\Import\Routine\File\CSVProcessor->run()
#4 /var/www/firefly-iii/app/Http/Controllers/Import/JobStatusController.php(172): FireflyIII\Import\Routine\FileRoutine->run()
#5 [internal function]: FireflyIII\Http\Controllers\Import\JobStatusController->start(Object(FireflyIII\Models\ImportJob))
...
```

A simple input box to specify values would be very nice. On the very least, a description of what values are expected would be fine, so the user could change them himself in the file.

Looking through the source I found that converter Rabobank treats value `D` as debit and works for my bank. But that shouldn't be hidden in the source code.

**Comment by JC5** [comment]
I’ll think about it. I’m not a fan of customizing everything, or making option boxes for every single exception. Especially not for a single use case.

**Comment by Dainius14** [comment]
I don't this is important. But a simple explanation when selecting that option would be great :)

**Comment by fiasco** [comment]
My bank also uses "C" and "D" as indicators. Would like to see this supported.
