### ISSUE TITLE
Deleted client from spectre crashes import from firefly

### ISSUE THREAD

**Issue by albertsegura** [firefly-iii/firefly-iii#2183]
**Bug description**
I am running Firefly III version  4.7.11, and my problem is:

I removed the "costumer" from saltedge website. Now when I click on "Import using Spectre" it crashes with the following error: "
Job could not be started or crashed: The import routine crashed: Guzzle Exception: Client error: `GET https://www.saltedge.com/api/v4/logins/?from_id=0&customer_id=3574119` resulted in a `404 Not Found` response: {"error_class":"CustomerNotFound","error_message":"Customer with id: '3574119' was not found.","request":{"from_id":"0", (truncated...) "

Its trying to fetch info about customer_id=3574119 but it cannot found it because of course I removed it. But I cannot remove this "costumer" from firelfy.

**Steps to reproduce**
Setup spectre from saltedge
Import transactions with spectre
Remove the fetched costumer (I also removed the entry on connection tab)
Go to firefly, click on "Import using Spectre"
Crash

Is there a way to remove it from the database?

**Comment by JC5** [comment]
Yes. Delete all entries from the database that begin with “Spectre” and then browse to the /flush URL on your installation. 

That should fix it.

**Comment by albertsegura** [comment]
Worked

Maybe an option in the UI to delete it without having to go to the db would be nice.

**Comment by flopes89** [comment]
I have a similar problem. I keep getting the 404 error with a customer number that doesn't exist in saltedge anymore. How can I change this ID? Where does it even come from?
