### ISSUE TITLE
Dept to wallet

### ISSUE THREAD

**Issue by sasureshkumar** [firefly-iii/firefly-iii#2184]
I borrowed some money from Friend/Bank and as this a liability, I have added this to a debt account.

How I do add the money to the wallet?

When I do a transfer from debt account, it doubles the debt account balance.

Please advise.

**Comment by JC5** [comment]
Just create it empty and then make a transfer.

**Comment by sasureshkumar** [comment]
I can not leave the amount as empty or 0. Getting the validation message as below:

Please enter the original amount of this liability as a positive number. You may also enter the current amount. Make sure to edit the date below to match.

The opening balance must be a number.

**Comment by JC5** [comment]
Which version are you on?

**Comment by sasureshkumar** [comment]
Version 4.7.6.2 Firefly III as my current server PHP version doesn't support the latest one.

**Comment by JC5** [comment]
What you want will only work in the latest version I’m afraid.

**Comment by sasureshkumar** [comment]
Thanks, I have just directly access the DB and changed the value to 0 and transferred.

**Comment by sasureshkumar** [comment]
BTW, a great open source application, I never find like this, in code basis, and document basis, and planning and involvement. Great work, thanks a lot.

And just worried, why not uses the Laravel's blade. But that not a case actually.

**Comment by JC5** [comment]
:+1: Thanks for the compliments!

When Blade came out it didn't have the features I needed. So I moved to Twig.
