### ISSUE TITLE
Duplicate transaction detection when using API

### ISSUE THREAD

**Issue by RobinWeitzel** [firefly-iii/firefly-iii#2185]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

Transactions posted via the API are always created, even if a duplicate already exists.

**Steps to reproduce**
Create a transaction via the API (api/v1/transactions) using the following JSON:
```
{
"type": "deposit",
"description": "Groceries",
"date": "2019-03-20",
"transactions": [
    {
    "amount": 12.95,
    "destination_id": 1,
    "source_name": "test",
    "reconciled": true
    }
 ]
}
```
Then submit the exact same request again.

**Extra info**
I am using the API to automatically sync my bank statements with Firefly III (I unfortunately can not use spectre). I therefore wrote a nodejs script which craws my online bank statement and then inputs this info into my budgeting app (I have used this method in the past with other sites). 

**My question**
Does the API check for duplicates?
If so, which field can I use to store the unique transaction id (I get this id from my bank) via which duplicates are detected?
If not, are there plans to include this feature in the future?

**Comment by JC5** [comment]
The API does not, and will not check for duplicates. It has no extra logic at all. If you want to do duplicate detection, you'll have to do it locally.

**Comment by RobinWeitzel** [comment]
Ok, thanks for your quick reply.
I will do that then :)
