### ISSUE TITLE
404 when bulk editing reconciled transactions

### ISSUE THREAD

**Issue by RobinWeitzel** [firefly-iii/firefly-iii#2187]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

When I only select reconciled transactions and try to bulk edit I get a 404.
If I also select not reconciled transactions as well I get the expected edit and a message telling me I can not edit reconciled transactions (which is expected I guess).

**Steps to reproduce**
Go to Transactions, select one or more reconciled transaction without selecting any non-reconciled transactions. Click bulk edit.

**Expected behavior**
You should get a message telling you that this is not possible because all transactions have already been reconciled.

I know this is not a big issue, I just wanted to let you know :)
Thank you for looking into it!

**Comment by JC5** [comment]
Yes, this is something I still have to improve. Thanks for letting me know!

**Comment by JC5** [comment]
I'm treating this as a bug and I'll pick it up for 4.8.0

**Comment by JC5** [comment]
This will work in 4.8.0. You can edit everything except the amount.
