### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by overload08** [firefly-iii/firefly-iii#2190]
Hi.

I'm using FF 4.7.16.
It will be cool to add capability to add budget to revenues and transfers

For exemples 
Revenues : I receive a refund. That will substract the amount in the budget
Transfer : I transfer some money to my son account monthly and I've a budget for.

**Comment by JC5** [comment]
It's been discussed a few times but influencing budgets from other transactions will not be a feature.

**Comment by overload08** [comment]
Can you Say me why ?Envoyé depuis mon mobile Huawei-------- Message original --------Objet : Re: [firefly-iii/firefly-iii] Budget (#2190)De : James Cole À : firefly-iii/firefly-iii Cc : OverLoad ,Author It's been discussed a few times but influencing budgets from other transactions will not be a feature.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/en/latest/about/grand-theory.html

For income: Income should never influence the budget of the **current** period. If you do that, you don't do financial management correctly. You were able to make the expense, right? You budgeted for the expense, correct? So getting a refund is a bonus. Put it in your savings account and use it for next month.

For transfers: a transfer means the money is not spent. It's still on your accounts. So it's not an expense, so it's not part of a budget.

**Comment by overload08** [comment]
Oh wow... I'm in the same case...That's the reason why i use firefly !My script import automaticly all transactions but i need to see What is done in my accounts...Thank's for sharing your History :)Envoyé depuis mon mobile Huawei-------- Message original --------Objet : Re: [firefly-iii/firefly-iii] Budget (#2190)De : James Cole À : firefly-iii/firefly-iii Cc : OverLoad ,Author https://docs.firefly-iii.org/en/latest/about/grand-theory.html
For income: Income should never influence the budget of the current period. If you do that, you don't do financial management correctly. You were able to make the expense, right? You budgeted for the expense, correct? So getting a refund is a bonus. Put it in your savings account and use it for next month.
For transfers: a transfer means the money is not spent. It's still on your accounts. So it's not an expense, so it's not part of a budget.
