### ISSUE TITLE
Can't get started - hitting an "encryption key not specified error"

### ISSUE THREAD

**Issue by samteezy** [firefly-iii/firefly-iii#2193]
**Bug description**
Version 4.7.17. My issue is that I get the "Go!" message after the successful install message, and then when I try to access in the browser for the first time, I get a 500 error. In the log, here's the last relevant line:

```
[Sun Mar 24 09:00:43.913371 2019] [php7:error] [pid 75] [client 172.17.0.1:59791] PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1122): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}('')\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap('', Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(791): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\\Container\\Conta in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44
```

If it makes a difference, I'm running this in a Synology NAS with the latest DSM software, connected to a database running on MariaDB 10. I have a reverse proxy set up for this as I have other apps running in Docker containers.

**Comment by samteezy** [comment]
Since the .csv output of logs from Synology is funky, here's a .html of the terminal output with a .txt extension added so I can upload it here.
[jc5x-firefly-iii.html.txt](https://github.com/firefly-iii/firefly-iii/files/3000411/jc5x-firefly-iii.html.txt)

**Comment by JC5** [comment]
Alright so you're running this as a Docker container. What's the command you've used to start it? Which environment variables did you set?

**Comment by martinfiers** [comment]
@samteezy did you get this working eventually? I happened to bounce into the same problem (error shown at the bottom). 

I'm also running in a docker container, it's started with the following entry point:  .deploy/docker/entrypoint.sh (basically I've used ansible-nas to set it up, here's the config that sets up firefly: https://github.com/davestephens/ansible-nas/blob/master/tasks/firefly.yml).

Thanks!

> In ServiceProvider.php line 236:  Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': No application encryption key has been specified.
> 
> Go!,
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.10. Set the 'ServerName' directive globally to suppress this message,
> [Mon Sep 09 21:48:53.127153 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND',
> [Mon Sep 09 21:48:53.127058 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.9 OpenSSL/1.1.1c configured -- resuming normal operations,
> [Mon Sep 09 22:00:52.540333 2019] [php7:error] [pid 332] [client 192.168.0.189:54309] PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(785): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\C in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44

**Comment by martinfiers** [comment]
Interestingly, FF_APP_KEY will not be a valid env value. It should probably be just APP_KEY. This seems to be a small bug I think in the config files in ansible-nas (will report to them, too). When I change the env variable to APP_KEY, I can get a bit further but still not working. Here's the error now:

> [Mon Sep 09 22:28:59.763515 2019] [php7:error] [pid 334] [client 192.168.0.189:54705] PHP Fatal error:  Uncaught RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43\nStack trace:\...

**Comment by martinfiers** [comment]
Oh, password has to be exactly 32 chars. Ok. Now I get different errors but probably related to just me not configuring it properly. So this issue doesn't have to be re-opened.
