### ISSUE TITLE
Feature Request: zero line marked more clear

### ISSUE THREAD

**Issue by colinerd** [firefly-iii/firefly-iii#2195]
Can the "zero" line visibility be improved? For example - If I am looking at my budgets, I really need to look closely to notice the zero line. Making it red would increase visiblity (see screenshot for example)

![zero-line](https://user-images.githubusercontent.com/15741333/54882236-181aaa00-4e58-11e9-8cad-34d67b0f2000.png)

**Comment by JC5** [comment]
The 0.00 line is already slightly darker than the other lines but there's nothing else I can do unfortunately.
