### ISSUE TITLE
Feature Request: Theme support (Dark UI and/or custom colors for UI & charts)

### ISSUE THREAD

**Issue by colinerd** [firefly-iii/firefly-iii#2196]
It would be great to be able to adjust the looks and feel of the application to your own liking with the help of theme support or via custom CSS.

Adding the option to change the colors of the FireFly interface and/or adding a dark UI would be nice as well. Same goes for the charts and their coloring.

**Comment by JC5** [comment]
I'm working on a new layout but dark themes / modes won't be a feature any time soon. Sorry.

**Comment by colinerd** [comment]
Hi @JC5, Looking forward to the new layout, when do you expect it to be ready?
Anyway I can help test the new UI or have a sneek peek? :-)
