### ISSUE TITLE
Problem with Softaculous Installation

### ISSUE THREAD

**Issue by lziron** [firefly-iii/firefly-iii#2198]
I am running Firefly III version 4.7.17

Hi, I'm having problems on the platform using the softaculous. the menus will have the link 'public/#'. the graphs do not appear, the dropdown menu does not appear and appears to be incomplete. what can I do?

**Comment by JC5** [comment]
I don't know, but it seems the Javascript isn't loaded properly. Anything in the development console of your browser?

**Comment by lziron** [comment]
Yes. 

`Loading failed for the <script> with source “https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js”. ziron.eti.br:847:1
Content Security Policy: The page’s settings blocked the loading of a resource at https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js (“script-src”).
`

**Comment by JC5** [comment]
I don't know what that is, because I don't use external scripts, and also not the rocket-loader. Could that be an extension?

**Comment by lziron** [comment]
I paused my cloudflare and everything worked perfectly, I'm going to look for the reason for the error and put it here.

I appreciate your attention.
