### ISSUE TITLE
Bunq: Internal transactions get ignored resulting in wrong account total

### ISSUE THREAD

**Issue by timh77** [firefly-iii/firefly-iii#2199]
I am running Firefly III version 4.7.17, and my problem is:

Recently I added my Bunq account to Firefly III. My Bunq account consists of several different bankaccounts. One of these accounts is a general account, others for special purposes and the last one is a long term savings account.

Generally my income arrives at my general account and from there is distributed over all special purpose accounts. At the end of the month the money remaining at these accounts is moved to the long term savings account.

As you can imagine this means a lot of "internal" transfers.

When running the import it seems Firefly is ignoring some transactions resulting in a difference on almost every account. Because of these missing transactions the account total is calculated incorrectly (positive and negative).

Sometimes the outbound transaction is missing, sometimes the inbound transaction. It's hard to pinpoint. Guess it's based on which transaction is imported first.

**Steps to reproduce**
Create several bank accounts and transfer money back and forth between these accounts.
Note these Bunq bank accounts have all been added to Firefly and selected during import.
Next start the import. In my case this always results in several ignored rows.
    Row #0 ("") could not be imported. It already exists.
    Row #1 ("") could not be imported. It already exists.
    Row #2 ("") could not be imported. It already exists.
    Row #3 ("") could not be imported. It already exists.

**Expected behavior**
I guess the duplicate check needs some attention.

**Extra info**
Debug information generated at 2019-03-25 21:23:41 Europe/Amsterdam for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.16-1+ubuntu16.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-03-01 00:00:00 |
| Session end | 2019-03-31 23:59:59 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

[2019-03-25 21:22:28] local.NOTICE: Will now store the transactions. Count of items is 5.  
[2019-03-25 21:22:28] local.WARNING: Row #0 seems to be a duplicate entry and will be ignored.  
[2019-03-25 21:22:28] local.WARNING: Row #1 seems to be a duplicate entry and will be ignored.  
[2019-03-25 21:22:28] local.WARNING: Row #2 seems to be a duplicate entry and will be ignored.  
[2019-03-25 21:22:28] local.WARNING: Row #3 seems to be a duplicate entry and will be ignored.  
[2019-03-25 21:22:28] local.NOTICE: After a first check for duplicates, the count of items is 1.  
[2019-03-25 21:22:28] local.NOTICE: Going to store...  
[2019-03-25 21:22:28] local.NOTICE: Done storing. Firefly III has stored 1 transactions.

**Comment by JC5** [comment]
Mmm.  Thanks for letting me know. I’ll have to check it out this weekend.

**Comment by timh77** [comment]
Sure. Let me know in case you require any additional info. I was able to reproduce this every time so I am sure you will be able to do the same ;-)

**Comment by timh77** [comment]
Just wanted to add... I was able to reproduce the same with my ABN AMRO accounts when transfering money from my current account to savings account. And again when I transfered from Bunq to ABN AMRO.

It seems transactions of the type "transfer", when the inbound and outbound bank accounts are both known in Firefly III. Only one of the transactions, either the inbound or the outbound, is calculated. So it could be the outbound transfer is included (resulting in a negative amount for the outbound account) but the inbound transfer is not (resulting in no possitive amount for the inbound account).

**Comment by JC5** [comment]
Are the distributions you mentioned automated by any chance, by a bunq feature for example?

**Comment by timh77** [comment]
No, just manual transactions.
I could reproduce this with three types of transactions:
1. Bunq to Bunq (both part of my own account)
2. Bunq to ABN (v.v.)
3. ABN current to ABN savings account

All accounts were added in Firefly III as either current or savings account.

**Comment by tapnl** [comment]
I am experiencing the exact same bug. I did some cross checking on loading accounts in different order, etc. But as soon as two accounts are loaded with internal transactions between them. The total numbers get mixed up.

**Comment by samzan** [comment]
I'm having the same issue, any ETA on the fix?
Or can you you give me some hints, as to where (/which code) the problems might exist; so I can take a look?

My php knowledge is rusty, but who knows ;)

If a donation would trigger you, I would be willing to...but I don't have paypal; a bunq.me page would be great ;)

**Comment by JC5** [comment]
It depends on bunq, to be honest. I don't think I can access the API with a free account and I'm not yet sure if the sandbox is still around. 

If I can't fix this, I'll have to drop support for bunq and move the code to the new external import apps, which is a trend for future versions you can read about on the [roadmap](https://github.com/firefly-iii/firefly-iii/projects/5#column-4993744).

**Comment by JC5** [comment]
I can't access the Bunq Sandbox API without a full account. I can't fix this for now.

**Comment by matthijsvdr** [comment]
Not bunq related, but when I import csv from the Rabobank, some transactions get marked as duplicate, however they are not.
They are on the same data, have the same description, but are separate transactions. (Example from a cashback action on some products 4 transactions 2 get marked a duplicate, but they are not duplicates)

And some transactions are not marked a duplicate but they are (But is is because description fields contain differed values thank you Rabobank)

**Comment by JC5** [comment]
If the line in the CSV is the same as any previous ones, and Firefly III can't tell the difference, it's a duplicate. If there is no info in the line to make it unique, there's not much I can do.

**Comment by matthijsvdr** [comment]
> If the line in the CSV is the same as any previous ones, and Firefly III can't tell the difference, it's a duplicate. If there is no info in the line to make it unique, there's not much I can do.

There are unique values in the line, like transaction reference. Its fine for now I manually changed some values added some spaces :) just wanted to let you know

**Comment by JC5** [comment]
And are they included in your import?

**Comment by matthijsvdr** [comment]
Firefly does not have a transaction reference field, and by default its put on ignore. So answer would be no.

**Comment by JC5** [comment]
Use internal reference or another field :)
