### ISSUE TITLE
Access Denied: security.limit_extensions

### ISSUE THREAD

**Issue by Andrewskiz** [firefly-iii/firefly-iii#2200]
I am running Firefly III version 4.7.17

I am running Firefly under nginx, I am using the snippet you provided with a few small changes:

> location ^~ /firefly-iii/ {
>    deny all;
> }
> 
> location ^~ /budget {
>    alias /var/www/firefly-iii/public;
>    try_files $uri $uri/ @budget;
> 
>     location ~* \.php(?:$|/) {
>       include fastcgi.conf;
>       fastcgi_param SCRIPT_FILENAME $request_filename;
>       fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
>       fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
>    }
> }
> 
> location @budget {
>    rewrite ^/budget/(.*)$ /budget/index.php/$1 last;
> }

I get this error in my error log

> FastCGI sent in stderr: "Access to the script '/var/www/drewski.xyz/firefly-iii/public/index.php/login' has been denied (see security.limit_extensions)" while reading response header from upstream,

The website https://example.com/budget/login just says Access denied.

**Comment by JC5** [comment]
Weird. That seems to be an nginx error and I must admit I’m not an expert.
