### ISSUE TITLE
Transfer transactions listed as income on financial report

### ISSUE THREAD

**Issue by dneupart** [firefly-iii/firefly-iii#2201]
**Bug description**
I am running Firefly III version 4.7.17, and after upgrading from version 4.7.8 experienced that regular transfers between accounts are listed as income in the financial report.

**Steps to reproduce**
I'm not able to reproduce on the demo server, but have installed as fresh copy 4.7.17 on my shared host server.

On the fresh install I follow the start guide and create a asset account with a start of 30000€ and a savings account with start of 0€. I then create a transfer of 25000€ from asset account to savings account. The account overview shows the correct current amount of the accounts. The financial report however lists the transfer as income.

As I'm not able to replicate on the demo site it has to be something with my server. However I've followed the install guide to the point and checked that all php extensions are enable.

**Expected behavior**
I expected my server to handle transfer transaction like the demosite.

**Extra info**

***Screenshots***
![default-current-year-report](https://user-images.githubusercontent.com/9382573/54989252-6b0b7300-4fb8-11e9-87f6-990fcb51be15.png)
![account overview](https://user-images.githubusercontent.com/9382573/54989257-7068bd80-4fb8-11e9-8707-1a84b9c3caca.png)
![transaction](https://user-images.githubusercontent.com/9382573/54989265-7494db00-4fb8-11e9-8dd3-7b43d4088d86.png)

***Logs***
[ff3-litespeed-2019-03-25.log](https://github.com/firefly-iii/firefly-iii/files/3007624/ff3-litespeed-2019-03-25.log)
[phpinfo.pdf](https://github.com/firefly-iii/firefly-iii/files/3007626/phpinfo.pdf)

**Comment by JC5** [comment]
It should work as you expect as long as both asset accounts are included in the report. I am not aware of any code changes but I can check it in the weekend. 

Run “php artisan cache:clear” or browse to /flush to clear your cache.

**Comment by JC5** [comment]
Sorry I think this works as expected.

Your 25K income is labeled "test". The transfer you screenshotted is labeled "transfer". These are clearly two different transactions.

**Comment by dneupart** [comment]
Thanks for testing a local setup @JC5 :)

Have tried the Cache:Clear command with no success. It's really strange the fact that "test" is listed as income in screenshot 1. The link when hovering the mouse over it points to: testsite.local/accounts/show/1 so clearly Firefly identifies "test" as an account rather than a transaction. 

Is there anything I can do to help dig deeper into this. I don't feel the logs tell me much and as I'm not able to reproduce on the demoserver and you have tested a local setup as well it all points to a configurations issue with my server. I'm just completely at a loss as to what the issue might be. I'm running a lot of other opensource php systems on the server without any issues and as I mentioned Firefly was listing correct incomes in 4.7.8

**Comment by JC5** [comment]
I'll find some time this weekend :)
