### ISSUE TITLE
Reconcile page redirect failed + gap calculation feature requested

### ISSUE THREAD

**Issue by JacksonHub** [firefly-iii/firefly-iii#2203]
**Bug description**
I am running Firefly III version 4.7.17 **under a subpath by Nginx**,  and my problem is:

When I have done the reconcile page fulfillment, and want to save the reconciliation (By click the 'Confirm reconcile Button'), it jumps to a wrong location (Web Root).

I'm pretty sure the Nginx configuration is fine since other page could work perfectly (including installation, or other daily uses),  but it seems the Reconcile page could not be redirected well...

**Steps to reproduce**
Maybe it needs a workable subpath install environment to reproduce this bug.
**BTW**, the Nginx configuration for subpath in documentation didn't work as expected unless you do some customize job..

**Expected behavior**
It turns to the web root (e.g. https://localhost/accounts/reconcile/... instead of https://localhost/firefly-iii/accounts/reconcile/...)

**Extra info**

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.14-1+0\~20190113100657.14+jessie\~1.gbpd83c69 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-03-31 00:00:00 |
| Session first | 2019-02-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | xxxx |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, bz2, curl, fileinfo, intl, ldap, mbstring, exif, imagick, xmlrpc, mysqlnd, PDO, xml, bcmath, calendar, ctype, dom, ftp, gd, gettext, iconv, json, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**

A small feature requested (not related to this bug)...:
Could there be a **Terminal Amount** when fulfill the Transaction pages?
By now it requires YOU to fill the exact amount in this transaction, but if there is the cases you just want the program do the math by itself since the gap between terminal amount and original amount stored in Firefly is simple, only one transaction?

This could save you a little bit time from calculating the gap by yourself...And maybe, avoid some entering mistakes...

**Comment by JC5** [comment]
I suspect it's a Javascript issue. I'll research it this weekend if I find the time. Thanks for letting me know.

I have no idea what you mean with the feature request. What's a terminal account?

**Comment by JacksonHub** [comment]
Emmm, let's give it into an example:

You have an asset item called 'ABC deposit', its current amount is $1000.66 at the beginning of March.

By 31th, you think it's time to fulfill the your accounting book, you look at the bank reconciliation and find that all of the withdraws could be labeled as 'Daily Purchases', the remaining balance is $222.

So you want to do it into one transaction, normally, you need to calculate the gap by yourself... ($1000.66-$222) 
 
Maybe the program can put a small **CheckBox** labeled as 'Current amount of balances' to let it calculate the amount gap automatically instead of yourself. 

Both Withdrawal or Deposit function could adapt this feature.

**Comment by JC5** [comment]
Right, to fill it up again you mean? That won't be a feature.

**Comment by JacksonHub** [comment]
Pity... I thought it may help doing fast input and spare some coffee time.

**Comment by JacksonHub** [comment]
I have checked the program using a localised port instead of a reverse-proxy subpath , the issue seems to be solved.. 

So the problem jumps to wrong handling on reverse proxy.

Maybe Docker users may also encounter this sort of issues?

 **BTW**,  selecting on date range under the proxy pops a 'Could not change date range' dialog, making this function unavailable.

**Comment by JC5** [comment]
If that happens I suspect the “new recurring transaction” page will also be broken. 

Your reverse proxy doesn’t pass URL query parameters (everything after the “?”) along to Firefly III.

**Comment by JacksonHub** [comment]
Just set up a test recurring transaction, no issue occurred.. 

Maybe need some time for finishing automation..

Reverse configuration is based on [Link](https://github.com/firefly-iii/firefly-iii/issues/1869#issuecomment-450594411).
