### ISSUE TITLE
Cannot set transaction type in rule

### ISSUE THREAD

**Issue by zorose** [firefly-iii/firefly-iii#2204]
I am running Firefly III version 4.7.17 in a Docker container

**Description**

When creating a new rule, selecting the trigger of "Transaction is of type" and entering "Withdrawal" or "Deposit" doesn't allow a rule to be stored or updated. An error message shows up below the trigger value box that says "This value is invalid for the selected trigger." 

![Screenshot_Rules](https://user-images.githubusercontent.com/1754228/55244040-60e2b200-520e-11e9-91c8-4a926c308758.png)

I tried to replicate this on the demo site but didn't have any issues storing and updating a this type of rule there.

**Comment by JC5** [comment]
Which browser are you using? Could you clear your browser cache?

**Comment by zorose** [comment]
Thanks for helping me look into this. I've tried clearing the cache in Firefox 66.0.1 and Chrome 70.0.3538.110, but I'm still having the same issue.

**Extra Info**

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2019-03-01 00:00:00 |
| Session end | 2019-03-31 23:59:59 |
| Session first | 2017-06-10 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Comment by zorose** [comment]
Providing a few more details on this.

I tried creating a separate container on a local instance of Docker that I have running on my laptop. I used the docker-compose file provided on [Github](https://github.com/firefly-iii/firefly-iii/blob/master/docker-compose.yml) to get things up and going quickly, and without configuring anything other than what’s required, I still got the same error when I tried to create a rule with a “Transaction is of type” trigger.

**Steps:**

- Install docker (version 18.09.3, build 774a1f4) and compose (version 1.23.2, build 1110ad01)
- docker-compose -f ~/Downloads/docker-compose.yml up --force-recreate --detach –remove-orphans
- Create username/pass
- Create a bank account with checking and savings balance of 0
- Go to the rules page, select New rule
- Create a test rule with the trigger set to “Transaction is of type” “Withdrawal”, and action set to anything.
- Click Store new rule.

**Result:**
- The error is still there, and the rule is not created.

**Comment by JC5** [comment]
I'll try it in Safari later as well.

**Comment by JC5** [comment]
OK nothing on the demo site in Safari. I'll spin up a container as well.

Could you disable any plugins or extensions?

**Comment by zorose** [comment]
I tried using Chrome without any plugins or extensions, but still have the same issue.

**Comment by Aarup** [comment]
I have the same problem - I'm also running FireFly in Docker and get that error when trying to use transaction type.

**Comment by Falconne** [comment]
Same here. Running in a Docker container and with Chrome, I can't use Transaction Type as a trigger. Other trigger types have been fine.

**Comment by JC5** [comment]
Found it. It depends on the underlying database. I will push a fix. For those of you who feel adventurous, please change `strtolower` into `ucfirst` in [this exact line](https://github.com/firefly-iii/firefly-iii/blob/master/app/Validation/FireflyValidator.php#L344). See also the commit right above this reply.

It will be fixed in 4.8.0. Thanks for your patience!

**Comment by Falconne** [comment]
Thanks for the quick fix!

**Comment by zorose** [comment]
Thank you!
