### ISSUE TITLE
Can’t create recurring transaction in 4.7.17

### ISSUE THREAD

**Issue by mauricemeyer** [firefly-iii/firefly-iii#2207]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

New recurring transactions can’t be created as the „Type of repetition“ dropdown has no values. Changing the first date datepicker value does not change this.

There are no errors in the browser (Chrome 73.0.3683.86) console, nor in the web servers logs.

**Steps to reproduce**
Try to create a recurring transaction

**Expected behavior**
I can select the repetition type

**Extra info**
I’m running on:

* Chrome 73.0.3683.86
* Firefly III 4.7.17
* Ubuntu 18.04 (nginx + php-fpm)

**Bonus points**
I think it has to do with the JavaScript that generates the reptition types, but my JS debugging skills are not good enough for this issue.

**Comment by JC5** [comment]
I expect that your nginx configuration is broken. Can you share the result of browsing to this page on your installation? `/recurring/suggest?date=2019-04-03&pre_select=`.

Change the date to today's date if necessary.

**Comment by mauricemeyer** [comment]
It just returns an empty json array. I have thought about my Content Security Policies as a possible source, but there’s nothing blocked by CSP.

If you need more output from anywhere, I’ll gladly provide it. 

My nginx config btw. is as follows (hostname changed):

```
server {
  listen       *:443 ssl http2;
  listen       [::]:443 ssl http2 ;

  server_name  ff.example.com;

  ssl on;
  ssl_certificate           /etc/letsencrypt/live/ff.example.com/fullchain.pem;
  ssl_certificate_key       /etc/letsencrypt/live/ff.example.com/privkey.pem;
  ssl_session_cache         shared:SSL:50m;
  ssl_session_timeout       1d;
  ssl_session_tickets       off;
  ssl_protocols             TLSv1.2;
  ssl_ciphers               ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;
  ssl_prefer_server_ciphers on;
  ssl_stapling              on;
  ssl_stapling_verify       on;

  access_log            /var/log/nginx/ssl-ff.example.com.access.log vhost_combined;
  error_log             /var/log/nginx/ssl-ff.example.com.error.log;
  root /var/www/ff.example.com/public;


  location ~ ^(.+\.php)(.*)$ {
    include       /etc/nginx/fastcgi.conf;

    fastcgi_pass  unix:/run/php7.2-fpm.sock;
  }

  location ^~ /.well-known/acme-challenge/ {
    allow all;
    root      /var/www/html;
    try_files $uri =404;
  }

  location / {
    index     index.php;
    try_files $uri $uri/ /index.php/$1;
  }
}
```

**Comment by JC5** [comment]
Try the following:
```
    index     index.php; # move outside of location block
location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }
```

**Comment by mauricemeyer** [comment]
Unfortunately, it does not change anything. The index directive would only not match for letsencrypt’s ACME challenge, and there it does not make sense.

But thanks for fixing my `try_files` directive, don’t know what rode me there.

**Comment by JC5** [comment]
Try this one:
```
try_files $uri $uri/ /index.php$query_string;
```

**Comment by JC5** [comment]
Apologies, this one:

```
try_files $uri $uri/ /index.php?$query_string;
```

Notice the question mark.

**Comment by mauricemeyer** [comment]
I just went and debugged if nginx correctly passes the query to PHP-FPM.

FPM gets the request as follows (excerpt from the fpm access log):

```
"GET /index.php?date=2019-04-02&pre_select="
```

So that is correct. 

What I forgot to say until now: I just set up the instance yesterday, so the first entrances to the database are from yesterday. Could this play a role?

**Comment by mauricemeyer** [comment]
I just debugged a bit further and accidentally broke my php-fpm configuration in the process. After fixing that and restarting php-fpm, the endpoint works.

So, thank for the awesome software and fixing my `try_files` :)

**Comment by JC5** [comment]
:+1:
