### ISSUE TITLE
Columns displayed in transactions

### ISSUE THREAD

**Issue by M-Paladin** [firefly-iii/firefly-iii#2210]
Hello,

First sorry for my english. I'm french so english isn't my native language :-p

**Description**
When I show an account, in the transactions box, different columns are displayed if you choose different period :
- View all transactions : Type, Description, Amount, Date, From, To, Budget, Category, Bill and the Action button.
- View transactions on a period (a year for example) : Type, Description, Amount, Date, From, To and the Action button. Budget, Category, Bill are missing
And Tag Column is missing each time.

**Solution**
Display every column by default

**What are alternatives?**
1: Add the possibility to select missing columns to display such as Budget, Category, Bill, Tag
2: Display only functionalities you are using (if no Budget created for example, don't display this column until you have one)

**Additional context**
Show all :
![firefly-account-show-all](https://user-images.githubusercontent.com/49365410/55683583-aeaf9680-5941-11e9-9e51-b72695ca8073.png)

Show period :
![firefly-account-show-period](https://user-images.githubusercontent.com/49365410/55683601-d3a40980-5941-11e9-9e30-5030ac0cd96e.png)

**Bonus points**
I'm a beginner with FireflyIII so maybe I didn't see something.
I choose to move away from Money Manager Ex because there were problems with SMB mounts (database on a NAS) and no updates for many months in linux.
FireflyIII seems really promising as it's server based and has many features. If I can use at least the same features Money Manager Ex had, it would be really great.

**Comment by JC5** [comment]
Thanks for the compliments. It’s been requested before. I don’t have space for all the fields but something will be added.

**Comment by M-Paladin** [comment]
Ok thank you. Maybe in the 4.8 version ?

**Comment by JC5** [comment]
Can’t promise anything.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1557
