### ISSUE TITLE
Passive Account Lost for Mass Edit

### ISSUE THREAD

**Issue by M-Paladin** [firefly-iii/firefly-iii#2211]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

When I Mass Edit transactions, destination Passive account are replaced by first asset account

**Steps to reproduce**
Having some transactions type transfer with a passive account destination
Select all of them and choose Mass Edit (not Bulk)
Destination field is replaced

**Expected behavior**
Passive accounts must be added to the dropdown list for Mass Edit operations

**Extra info**
Debug information generated at 2019-04-07 15:13:18 Europe/Paris for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.16-1+0\~20190307202415.17+stretch\~1.gbpa7be82 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-12-31 23:59:59 |
| Session first | 2012-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**
Passive Account :
![fireflyIII-passive-account](https://user-images.githubusercontent.com/49365410/55684172-98f19f80-5948-11e9-8809-69bb22ea9709.png)

Before Mass Edit
![fireflyIII-before-mass-edit](https://user-images.githubusercontent.com/49365410/55684182-a7d85200-5948-11e9-83a3-0207866325b7.png)

After Mass Edit
![fireflyIII-after-mass-edit](https://user-images.githubusercontent.com/49365410/55684187-ae66c980-5948-11e9-99eb-601d32b53125.png)

**Comment by JC5** [comment]
Thanks, I’ll check it out.

**Comment by JC5** [comment]
This will be fixed in the next release.
