### ISSUE TITLE
Different Color / Amount for Transfert

### ISSUE THREAD

**Issue by M-Paladin** [firefly-iii/firefly-iii#2213]
**Description**
In the Transaction when you have a transfer, it's difficult to see in the flow is entering or is leaving the account because the amount is always positive and the color is always blue.

**Solution**
Change the amount in negative when it's leaving the account
and/or
Use another color to distinguish incoming and leaving

**What are alternatives?**

**Additional context**

**Bonus points**
![fireflyIII-transfer](https://user-images.githubusercontent.com/49365410/55687369-88ebb700-596c-11e9-8b3d-50ffa122dabb.png)

**Comment by JC5** [comment]
Sorry, but this is behavior that won’t change.

**Comment by M-Paladin** [comment]
Ok I understand your point of view

I decided to personalize my installation the display to better correspond what I want.

Here's what I modified (maybe useful for other people)

File : firefly-iii/app/Support/Twig/Extension/Transaction.php
I commented $coloured and $format, and I changed $amount the 2 times it appears in the file
```
        if (TransactionType::TRANSFER === $transaction->transaction_type_type) {
            //$amount   = app('steam')->positive($amount);
            $amount   = $transaction->transaction_amount;
            //$coloured = false;
            //$format   = '<span class="text-info">%s</span>';
```
With these changes, Transfers now display the same way as Withdrawals or Deposits (The icon at the beginning of the line is sufficient to make the difference in my opinion)

File : firefly-iii/app/Support/Amount.php
I changed $space and $result because I prefer the new display
```
        // some complicated switches to format the amount correctly:
        $precedes  = $amount < 0 ? $info['n_cs_precedes'] : $info['p_cs_precedes'];
        $separated = $amount < 0 ? $info['n_sep_by_space'] : $info['p_sep_by_space'];
        //$space     = true === $separated ? ' ' : '';
        $space     = ' ';
        //$result    = false === $precedes ? $formatted . $space . $format->symbol : $format->symbol . $space . $formatted;
        $result    = $formatted . $space . $format->symbol;
```
Before change :
€1 000,00
€-1 000,00

After change
1 000 €
-1 000 €

I don't know if these changes are enough but for the moment they seems satisfying for me.
![firefly-display-currency-change](https://user-images.githubusercontent.com/49365410/55690259-16400300-598f-11e9-9ef7-58fffbc6c2d3.png)

**Comment by M-Paladin** [comment]
In fact, this modification creates new problems with reconcile :

File : firefly-iii/app/Support/Twig/Extension/Transaction.php
I commented $coloured and $format, and I changed $amount the 2 times it appears in the file

        if (TransactionType::TRANSFER === $transaction->transaction_type_type) {
            //$amount   = app('steam')->positive($amount);
            $amount   = $transaction->transaction_amount;
            //$coloured = false;
            //$format   = '<span class="text-info">%s</span>';

I don't have enough time to read the code so I removed the change at the moment.

I'm disappointed this won't change because reading is so much clear when you can quickly identify what goes in and what gets out
