### ISSUE TITLE
Can’t delete attachments on bills in 4.7.17

### ISSUE THREAD

**Issue by tjedrowald** [firefly-iii/firefly-iii#2214]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is: I can't delete attachments on a bill.

**Steps to reproduce**
1. Add a new bill by navigating to /bills/create
2. Add a attachment
3. Save the bill
3. Show the bill by navigation to /bills/show/? (replace the questionmark with the corresponding id)
4. Try to delete the attachment you just added (/attachments/delete/?)

**Expected behavior**
My expectation is that the attachment gets deleted.

**Extra info**
Debug information generated at 2019-04-08 15:18:46 Europe/Amsterdam for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2019-04-01 00:00:00 |
| Session end | 2019-04-30 23:59:59 |
| Session first | 2018-12-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Bonus points**
[Stacktrace.txt](https://github.com/firefly-iii/firefly-iii/files/3054562/Stacktrace.txt)

**Comment by JC5** [comment]
That should be pretty foolproof. Thanks, I’ll check it out.

**Comment by JC5** [comment]
Confirmed. Will be fixed in the next release.

**Comment by tjedrowald** [comment]
Thanks for the quick response! Looking forward to the fix :+1:
