### ISSUE TITLE
Simpler installation process

### ISSUE THREAD

**Issue by brightonjack** [firefly-iii/firefly-iii#2215]
**Description**
One of the reasons that made Wordpress.org the most used content management system out there is its simple installation procedure. Their infamous 5-minute install process require very little input from a newbie during the initial installation process compared to Firefly III.

**Solution**
Simplifying the installation of firefly-iii so that it works on most shared hosting solutions that could also run Wordpress. While this is the solution, I can only assume it is easier said than done. However, it would be great if the version 5 focused on simplifying the installation process similar to that of Wordpress.org's.

While I am nowhere near an expert, I cannot "visually" identify any feature of firefly-iii that would need a very specific dependency that could otherwise not be done with what comes with many Linux / PHP environments out there that can also run WordPress and its countless add-ons.

**What are alternatives?**
I am not aware of any alternatives because Firefly III beats them all.

**Additional context**
N/A

**Bonus points**
🥇

**Comment by JC5** [comment]
I won't put any focus on a Wordpress-like installation, nor will I strive to make Firefly III easier to install on shared hosting installations. Sorry about that.

Both solutions would require almost full-time effort to get right. This distracts from building Firefly III itself, which is way more interesting and way more rewarding.

Many easy installation options exist already. Apart from Docker, there is Sandstorm, Yunohost and Heroku and anybody with time can develop something for Cloudron, Snap or one of the other package managers.

My personal experience is also that users who spent some effort installing Firefly III will also spend some time debugging their installation before they raise an issue here, and I would like that to remain the case.

Thanks for your suggestion :)
