### ISSUE TITLE
Getting Failed to load resource: the server responded with a status of 414 (Request-URI Too Long) on reconciling large #of transactions

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2217]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

I am trying to reconcile over 1k transactions, and the javascript is giving me: 

> Failed to load resource: the server responded with a status of 414 (Request-URI Too Long)

**Steps to reproduce**
Try to reconcile lots of transactions

**Expected behavior**
Being able to finish the reconciliation
**Extra info**
Here is the request I have in the console

`http://localhost:9010/accounts/reconcile/4/overview/2001-04-01/2019-04-30?startBalance=0&endBalance=58.4&startDate=2001-04-01&startEn`

**Comment by JC5** [comment]
Although technically this is an issue with your webserver and not with Firefly III, I’ll see what I can do. I’ll refer you to a card on the roadmap in a sec. Regardless, it might be more constructive to reconcile smaller portions.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937456
