### ISSUE TITLE
create/update budget returns to page regardless of tickbox

### ISSUE THREAD

**Issue by pbartyik** [firefly-iii/firefly-iii#2218]
**Bug description**
I am running Firefly III version 4.7.117, and my problem is:
Fresh install of Firefly III.
When creating new budgets, regardless if tick box 

> After storing, return here to create another one. 
is ticked or not, it returns to create a new budget, not to previous screen. Same with updating budgets.

**Steps to reproduce**
Fresh install, create budget, leave tickbox to return here unticked, click store new budget.

**Expected behavior**
Unless return here is ticked, should redirect to previous page.

**Extra info**
Hosted on Ubuntu 18.04 LTS fully upgraded.
Browser is Firefox 66.0.2 64bits

Debug info:

> Debug information generated at 2019-04-09 18:00:12 Europe/Budapest for Firefly III version **4.7.17**.
> 
> | Variable | Content |
> | --- | --- |
> | FF version | 4.7.17 |
> | FF API version | 0.9.2 |
> | App environment | local |
> | App debug mode | false |
> | App cache driver | file |
> | App logging | , daily |
> | PHP version | 7.3.3-1+ubuntu18.04.1+deb.sury.org+1 |
> | Display errors | Off |
> | Session start | 2019-04-01 00:00:00 |
> | Session end | 2019-04-30 23:59:59 |
> | Session first | 2019-04-09 16:34:09 |
> | Error reporting | ALL errors |
> | Host | Linux |
> | Interface | fpm-fcgi |
> | UserID | 1 |
> | Attempt at "en" | false |
> | Attempt at "English" | false |
> | Attempt at "en_US.utf8" | 'en_US.utf8' |
> | Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
> | DB drivers | mysql |
> | Current driver | mysql |
> | Login provider |   |
> | Storage disks | local-upload  |
> | Using Sandstorm? | no |
> | Is Sandstorm (.env) | false |
> | Is Docker (.env) | false |
> | bunq uses sandbox | false |
> | Trusted proxies (.env) |  |
> | User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0 |
> | Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache |
> 

**Bonus points**
This is the screen I'm referring to.
![budget](https://user-images.githubusercontent.com/39059618/55816087-cc236280-5af1-11e9-89fe-8e83fd2d8857.png)

I might be missing something painfully obvious, in that case please let me know :)

**Comment by JC5** [comment]
No it's a known issue. I'm going to refer you to this issue: https://github.com/firefly-iii/firefly-iii/issues/2179
