### ISSUE TITLE
amount must be less than 10,000,000

### ISSUE THREAD

**Issue by riosmanuel** [firefly-iii/firefly-iii#2219]
I am running Firefly III version  4.7.8, I have a message that  "amount must be less than 10,000,000", I am from colombia and transactions upper to 10.000.000 are very frequent, i was searching in the code but unfortunally I can´t find  a way to change that limit. Can you tell me please how can I change that limit?

Thanks a lot

**Comment by JC5** [comment]
Hi,

[Here is the line](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Requests/JournalFormRequest.php#L169) you can change. Add two zeroes to make it a billion.

For the next release, it will be fixed.

**Comment by riosmanuel** [comment]
Hi James,


Thank you very much for your help, I fix it inmediatly.

Regards,


Manuel

De: James Cole [mailto:notifications@github.com]
Enviado el: miércoles, 10 de abril de 2019 11:04 p. m.
Para: firefly-iii/firefly-iii <firefly-iii@noreply.github.com>
CC: RIOS Manuel <Manuel.RIOS@MANE.com>; Author <author@noreply.github.com>
Asunto: Re: [firefly-iii/firefly-iii] amount must be less than 10,000,000 (#2219)


Hi,

Here is the line<https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Requests/JournalFormRequest.php#L169> you can change. Add two zeroes to make it a billion.

For the next release, it will be fixed.

**Comment by taylorsilva** [comment]
@JC5 Question about the fix for this issue here: https://github.com/firefly-iii/firefly-iii/commit/6f063a134f765be4c59a9bfbbd9f03e880467029#r33591142

**Comment by JC5** [comment]
I saw it, thanks :). Main reason I put in an upper limit is to match potential database limitations.
