### ISSUE TITLE
Import transactions issue

### ISSUE THREAD

**Issue by devolper102** [firefly-iii/firefly-iii#2223]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

I have imported a CSV file of Paypal into Firefly. But Firefly has imported only 9050 transactions from 10236 transactions. Another issue is that Firefly has added the current date to those all imported transactions. They are from 2013 to 2015. Also how many years of transactions Firefly save?

Thanks!
Muhammad Sikander

**Comment by JC5** [comment]
Make sure you use the correct field for the date and make sure the format is set correctly. Every import summarizes the failed transactions so please read those. Import in smaller batches to detect problematic lines.
