### ISSUE TITLE
Bank specific option

### ISSUE THREAD

**Issue by Jumanjii** [firefly-iii/firefly-iii#2224]
Hi there,

I am running Firefly III version 4.7.16

The bank of my wife "BNP" allow to download a CSV as transaction history but, the first line contains information of the account and is definitely not a header.

Even the number of column do not match the rest of the file :-(

When we edit the file to delete the first line of the file, then it's possible to import it into FF.

I was thinking about making a little dumb API where my wife could upload the file and download it as CSV without the first line and then could upload it to FF but I just remembered about bank specific option.

Does a rule already exists for similar case or could guide me to a specific documentation/part of the code to understand how to write my own ?

Thanks a lot

**Comment by JC5** [comment]
Sorry, but the bank specific option also relies on the file being a valid CSV file. It won't help you with this problem.

**Comment by Jumanjii** [comment]
Thanks for the fast answer :-)
I developed the app that serves a simple form to clean the file before uploading it to ff :+1:
