### ISSUE TITLE
Non Ascii Bearer Token

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2225]
Hi James,

An user of my software reported a [bug](https://github.com/emansih/FireflyMobile/issues/46). It appears that the server is providing a non-ascii Bearer Token. Is this an intended behavior? My software using [okhttp](https://github.com/square/okhttp) lib is unable to parse the non-ascii bearer token. If this is an intended behavior, can Firefly III be patched to stop providing non-ascii tokens? 

Thank you.

CC @krichter722

**Comment by JC5** [comment]
Thanks for letting me know. I see the issue but I am not sure what it could be.

The header (`Bearer xxxx`) contains the "[ZERO WIDTH NO-BREAK SPACE](https://unicodemap.org/details/0xFEFF/index.html)" if I understand the error message correctly. But there's no code in Firefly III generating the character, nor is it in the libraries. As far as I can find.

I'll do some digging to see if I can find something.

**Comment by JC5** [comment]
There is nothing in the code that points to this specific issue I'm afraid. I'm asking some follow-up questions.

**Comment by emansih** [comment]
thanks James.
