### ISSUE TITLE
Error:  Trying to get property 'name' of non-object

### ISSUE THREAD

**Issue by airbillion** [firefly-iii/firefly-iii#2226]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

When I try and edit transactions I get the error:  

Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

Trying to get property 'name' of non-object

**Steps to reproduce**

I ran a bill rule that was wrong and it applied to multiple transactions.  I deleted the rule and created a new one.  I then ran the rule successfully.  I looked at a few transctions and they all still are part of teh "Bill"  I try to edit any of the transactions and this error is displayed.  Unfortunately, now I cannot edit 200+ transactions any longer without this error...

**Expected behavior**

I shold be able to edit transaction without an error.

**Extra info**

Docker Install

**Bonus points**

Debug information generated at 2019-04-15 15:24:27 America/New_York for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2019-04-01 00:00:00 |
| Session end | 2019-04-30 23:59:59 |
| Session first | 2018-08-10 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

![image](https://user-images.githubusercontent.com/11315828/56159511-d5e61380-5f92-11e9-9a56-9204e6508f24.png)

-->

**Comment by JC5** [comment]
Could you share the stack trace from the log files please?

**Comment by airbillion** [comment]
Hello,

Sorry, I cannot...I restored a backup of my database that resolved the issue...

I should have captured the stack trace before I restored, but did not.

Thank you for your help!

**Comment by JC5** [comment]
Glad to hear it's fixed! Let me know if you run into other issues.
