### ISSUE TITLE
impossible to recover from a lost of the two-factor authentication key

### ISSUE THREAD

**Issue by RicardoHS** [firefly-iii/firefly-iii#2228]
**Bug description**
Version 4.7.17
When you forget or lose the two factor key there is nothing to do.
In the front there is a message to check storage/logs but in the logs there is no info.

**Steps to reproduce**
Enable the two factor auth and lose the key.

**Expected behavior**
A way to recover from this

**Comment by JC5** [comment]
All you can do is delete the appropriate rows from your preferences table. Open the "preferences" table and delete the entries with the names "twoFactorAuthEnabled" and "twoFactorAuthSecret". Run “php artisan cache:clear” on the command line to confirm it. 

An improvement is in the works. 

https://github.com/firefly-iii/firefly-iii/projects/5#card-19947158

**Comment by RicardoHS** [comment]
> All you can do is delete the appropriate rows from your preferences table. Open the "preferences" table and delete the entries with the names "twoFactorAuthEnabled" and "twoFactorAuthSecret". Run “php artisan cache:clear” on the command line to confirm it.
> 
> An improvement is in the works.
> 
> https://github.com/firefly-iii/firefly-iii/projects/5#card-19947158

Thank you. It works perfectly.

Just in case someone
