### ISSUE TITLE
Transactions Rejected As Duplicate - Different ExternalIDs

### ISSUE THREAD

**Issue by caldraper** [firefly-iii/firefly-iii#2230]
I'm attempting to backfill several months of transactions, but many are being rejected as "duplicates." The transactions in question are all identical (recurring transfers), but they all have unique external ids defined. I've attached a mock file containing two such transactions as well as the import configuration file. This issue is occurring on version 4.7.17 (Docker).

[transfers.txt](https://github.com/firefly-iii/firefly-iii/files/3084456/transfers.txt)
[import-configuration-2019-04-16.txt](https://github.com/firefly-iii/firefly-iii/files/3084463/import-configuration-2019-04-16.txt)

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
Sorry, but I can't replicate this. The transactions are unique.

I do notice that your date format `mdY` does not match the format in the transactions: `01/01/2019`.

**Comment by caldraper** [comment]
Interesting...I completely glossed over that :-( Correcting the date format resulted in a successful import. I'm sorry I did not notice that earlier and wasted your time as a result.
