### ISSUE TITLE
Use DATABASE_URL for MySQL

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#2231]
**Description**

- Currently the database [config](https://github.com/firefly-iii/firefly-iii/blob/master/config/database.php#L50) uses hardcoded values for Forge instead of making use of `DATABASE_URL` environment variable.

**Solution**
Use `$host`, `$database`, `$username` and `$password` variables in MySQL config, similar to PostgreSQL; and default to existing Forge values in case of absence. Additionally, a `$port` variable can be extracted from `$databaseUrl` and used similarly.

**Additional context**
I am trying to install Firefly III on a [Dokku](https://github.com/dokku/dokku) instance. Dokku describes itself as a "mini-Heroku". It makes use of `DATABASE_URL` in the same way. Thus, I think this change would be useful for Heroku MySQL/MariaDB add-ons and Dokku MySQL/MariaDB plugins.

I can create a pull request. I just wanted to discuss this first per the contribution guideline. And I noticed there is a `sqlsrv` config too, which should be able to function the same way.

**Comment by JC5** [comment]
That's a good idea. I have some changes lined up for those files, for the upgrade to 4.8.0. Could you hold this until 4.8.0 is released?

**Comment by halilim** [comment]
Sure thing, waiting for 4.8.0 then (& using `dokku config:set FF_DB_...` in the meantime).

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-20337815
