### ISSUE TITLE
Installation: migrate:refresh initializes configuration with db_version=1

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#2232]
**Bug description**
I am installing Firefly III version 4.7.17 on Dokku which uses Dockerfile. `php artisan migrate:refresh --seed` results in db_version=1 in the database, which fails the `oldDBVersion` check of the installer.

**Steps to reproduce**
1. Create and link the database resource
2. Follow the DB instructions in the docs:

       php artisan migrate:refresh --seed
       php artisan firefly:upgrade-database
       php artisan firefly:verify
       php artisan passport:install

**Expected behavior**
Installation completes successfully.

Logs:
```
$ dokku enter app
root@ce72df74f3d1:/var/www/firefly-iii# php artisan migrate:refresh --seed
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migration table not found.
Migration table created successfully.
Migrating: 2016_06_16_000000_create_support_tables
...
Migrated:  2019_03_11_223700_fix_ldap_configuration
Seeding: AccountTypeSeeder
Seeding: TransactionCurrencySeeder
Seeding: TransactionTypeSeeder
Seeding: PermissionSeeder
Seeding: LinkTypeSeeder
Seeding: ConfigSeeder
[2019-04-16 14:53:22] production.WARNING: No database version entry is present. Database is assumed to be OLD (version 1).  
Database seeding completed successfully.
root@ce72df74f3d1:/var/www/firefly-iii# php artisan firefly:upgrade-database
Updating currency information..
Done updating currency information..
Firefly III database is up to date.
root@ce72df74f3d1:/var/www/firefly-iii# exit
$ dokku mysql:connect app
...
mysql> select * from configuration;
+----+---------------------+---------------------+------------+------------+------+
| id | created_at          | updated_at          | deleted_at | name       | data |
+----+---------------------+---------------------+------------+------------+------+
|  1 | 2019-04-16 14:53:22 | 2019-04-16 14:53:22 | NULL       | db_version | 1    |
+----+---------------------+---------------------+------------+------------+------+
1 row in set (0.01 sec)
```

I have run `php artisan db:seed --class=ConfigSeeder` as a workaround, which updated the version.

**Comment by JC5** [comment]
This is by design.

**Comment by halilim** [comment]
Sorry, I am trying to understand if I missed a part from the installation docs. Which step updates it? (Assuming it is not the workaround that is by design)

**Comment by JC5** [comment]
The web interface will pick it up.

**Comment by halilim** [comment]
Re-installed now and indeed. Previously I saw an error message like "Please check logs". And I saw the DB version discrepancy in the logs, thinking that this was the issue. Apparently it wasn't, sorry for bothering.
