### ISSUE TITLE
session expired

### ISSUE THREAD

**Issue by misternils** [firefly-iii/firefly-iii#2233]
I'm using firefly on a sandstorm oasis server.   A bug which seems that it is maybe related to running on sandstorm is while i'm trying for certain tasks, if i take too long to complete the form it tells me the session is expired.  

An example of where it might happen is when i'm importing a CSV.  Seems to cut off after ~5 minutes,  It's impossible to get through an import if I am adding mappings. 

I thought i'd post here before i post on the sandstorm github, i'm not really sure where the problem is.

**Comment by JC5** [comment]
Do you have a screenshot of the expired session?

**Comment by misternils** [comment]
![fireflytimeout](https://user-images.githubusercontent.com/17713599/56386589-ca3f5a80-61e7-11e9-97dd-05f46cef023d.PNG)

a shot in the dark, maybe the way the API tokens are created? Says they are designed to expire after 5 minutes.  I don't know what i'm talking about though. 
https://github.com/sandstorm-io/sandstorm/blob/master/docs/developing/http-apis.md#creating-an-offer-template

**Comment by JC5** [comment]
Strange. Sorry, I forgot to reply. I know that sessions can expire, but there's not much I can do but to advise you to import in small batches.
