### ISSUE TITLE
Docker OpenLDAP invalid DN

### ISSUE THREAD

**Issue by IBlackI** [firefly-iii/firefly-iii#2234]
**Bug description**
I am running Firefly III version jc5x/firefly-iii, and my problem is:

Firefly running in docker trying to use OpenLDAP is seemingly "escaping" the admin dn. Using the env: 
```
environment: 
      - ADLDAP_CONNECTION_SCHEME=OpenLDAP
      - ADLDAP_AUTO_CONNECT=true
      - ADLDAP_CONTROLLERS=openldap
      - ADLDAP_PORT=389
      - ADLDAP_TIMEOUT=5
      - "ADLDAP_BASEDN=dc=domain,dc=tld"
      - ADLDAP_FOLLOW_REFFERALS=false
      - ADLDAP_USE_SSL=false
      - ADLDAP_USE_TLS=false
      - "ADLDAP_ADMIN_USERNAME=cn=admin,dc=domain,dc=tld"
      - ADLDAP_ADMIN_PASSWORD=root
      - "ADLDAP_ACCOUNT_PREFIX=cn="
      - "ADLDAP_ACCOUNT_SUFFIX=,ou=users,dc=domain,dc=tld"
      - ADLDAP_PASSWORD_SYNC=false
      - ADLDAP_LOGIN_FALLBACK=false
      - ADLDAP_DISCOVER_FIELD=uid
      - ADLDAP_AUTH_FIELD=cn
      - ADLDAP_SYNC_FIELD=uid
```
When trying to log in to firefly III the following  (limited) stacktrace appears.
```
firefly_iii_app_1  | [2019-04-17 16:26:20] local.INFO: Installed Firefly III version (4.7.17) equals expected Firefly III version (4.7.17)
firefly_iii_app_1  | [2019-04-17 16:26:20] local.ERROR: Exception: Invalid DN syntax in /var/www/firefly-iii/vendor/adldap2/adldap2/src/Auth/Guard.php:104
firefly_iii_app_1  | Stack trace:
firefly_iii_app_1  | #0 /var/www/firefly-iii/vendor/adldap2/adldap2/src/Auth/Guard.php(121): Adldap\Auth\Guard->bind('cn=admin,dc=dom...', 'root')
firefly_iii_app_1  | #1 /var/www/firefly-iii/vendor/adldap2/adldap2/src/Connections/Provider.php(234): Adldap\Auth\Guard->bindAsAdministrator()
firefly_iii_app_1  | #2 /var/www/firefly-iii/vendor/adldap2/adldap2-laravel/src/AdldapServiceProvider.php(102): Adldap\Connections\Provider->connect()

```
results in (on the openLDAP server):
```
5cb7378c conn=1099 op=0 do_bind: invalid dn (cn\3dadmin\2cdc\3ddomain\2cdc\3dtld)
5cb7378c conn=1099 op=0 RESULT tag=97 err=34 text=invalid DN
5cb7378c conn=1099 op=1 SRCH base="dc=domain,dc=tld" scope=2 deref=0 filter="(&(objectClass=inetOrgPerson)(objectClass=person)(uid=*)(?userprincipalname=USERNAME))"
5cb7378c conn=1099 op=1 SRCH attr=*
5cb7378c conn=1099 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
5cb7378c conn=1099 op=2 UNBIND
```
Other request on the OpenLDAP server don't have this seemingly escaped dn
**Steps to reproduce**
1. Go to the firefly login page.
2. attempt login.

**Expected behavior**
Able to log in.

**Extra info**
Running on docker in combination with the osixia/openldap image.

I have tried changing the `environment: ` to
1. without quotes
```
      - ADLDAP_ACCOUNT_SUFFIX=,ou=users,dc=domain,dc=tld
```
and this one fails to parse:
2. only quotes around the value behind the = sign
```
      - ADLDAP_ACCOUNT_SUFFIX=",ou=users,dc=domain,dc=tld"

     but probably fails on

      - ADLDAP_ACCOUNT_PREFIX="cn="
```
with logs:
```
firefly_iii_app_1  | The environment file is invalid!
firefly_iii_app_1  | Failed to parse dotenv file due to unexpected whitespace. Failed at [""cn=""].
```

**Comment by IBlackI** [comment]
I have done some further investigation.
This line in the docker.env file is not quoted but the other lines are. 
https://github.com/firefly-iii/firefly-iii/blob/76aa8acf0fd49de59e3550c27e3eb502b83a69f2/.deploy/docker/.env.docker#L141

Changing my config to:
```
      - ADLDAP_BASEDN=dc=domain,dc=tld
      - ADLDAP_FOLLOW_REFFERALS=false
      - ADLDAP_USE_SSL=false
      - ADLDAP_USE_TLS=false
      - ADLDAP_ADMIN_USERNAME="cn=admin,dc=domain,dc=tld"
      - ADLDAP_ADMIN_PASSWORD=root
      - ADLDAP_ACCOUNT_PREFIX=cn=
      - ADLDAP_ACCOUNT_SUFFIX=,ou=users,dc=domain,dc=tld
```
sadly didn't help, but it might still be a good ide to make the quoting consistent.

**Comment by JC5** [comment]
Sorry, not sure what could cause that. I'm changing the way env variables are handled in the next release in Docker, and i hope that will solve it.

**Comment by IBlackI** [comment]
Bug still exists, I have tried looking in the source code but can't find why it would be escaping the dn. Does ADLDap have a setting to always escape?

**Comment by JC5** [comment]
I don't think so. But my tip in this issue might solve yours as well:

https://github.com/firefly-iii/firefly-iii/issues/2249

**Comment by luisfavila** [comment]
@IBlackI did you manage to fix it?

**Comment by IBlackI** [comment]
Sadly I haven't been able to look at it more, I am waiting for the new release in the hope that it fixes it.

**Comment by IBlackI** [comment]
Confirmed to work in new release.
