### ISSUE TITLE
Demo site broken after logon. Be right back

### ISSUE THREAD

**Issue by Sup3rLativ3** [firefly-iii/firefly-iii#2235]
**Bug description**
The demo site allows you to enter the username and password but then gets stuck on the "be right back" message.

**Steps to reproduce**
Go to https://demo.firefly-iii.org/ and login with the demo account

**Expected behavior**
Once you have logged in you should be greeted with the dashboard.

**Extra info**
Tried from the latest Firefox and Chrome on 2 different computers.

**Comment by JC5** [comment]
Thanks for letting me know. It should be up again :+1:

**Comment by porjo** [comment]
Down again

**Comment by JC5** [comment]
Thanks. I'm not yet sure what's happening.
