### ISSUE TITLE
Error during composer step: InvalidArgumentException when specifying version 4.7.17

### ISSUE THREAD

**Issue by y2klol** [firefly-iii/firefly-iii#2236]
**Bug description**
I am trying to run Firefly III version 4.7.17, and my problem is:
When I am at the composer step `sudo composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.7.17` I get the error: 

> [InvalidArgumentException]                                                                
>   Could not find package grumpydictator/firefly-iii with version 4.7.17 in a version insta  
>   llable using your PHP version 7.0.33.

When I run without specifying the version `sudo composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii` the install works but it installs version v4.6.3.1

**Steps to reproduce**
Run `sudo composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.7.17` everytime

**Expected behavior**
Installation works with version 4.7.17

**Extra info**
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
![fireflydebug](https://user-images.githubusercontent.com/7161748/56452212-24b8f200-6373-11e9-8ad0-d209e207b58e.jpg)

**Comment by JC5** [comment]
Firefly III requires PHP7.2.

**Comment by y2klol** [comment]
Updated to PHP 7.2 and updating php modules worked software compiles with composer correctly. Thank you!
