### ISSUE TITLE
Database Migrate error

### ISSUE THREAD

**Issue by limitlessbritt** [firefly-iii/firefly-iii#2238]
I am running Firefly III version 4.7.17

Hey just found Firefly and it looks like a great app! I'm trying to install it on a self-hosted server, I'm on the final steps but i have encounter a problem. When i try to run 
php artisan migrate:refresh --seed
it gives me the following error:

In Connection.php line 664:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
   (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations)

In PDOConnection.php line 31:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

In PDOConnection.php line 27:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

I'm on windows 10

![ConEmu64_2019-04-21_15-51-50](https://user-images.githubusercontent.com/37319328/56474829-6918c080-644d-11e9-92ad-d60fde002a0f.png)

Thanks!

**Comment by JC5** [comment]
That error isn't caused by anything in Firefly III. It seems your database is down or unresponsive.

**Comment by limitlessbritt** [comment]
![ConEmu64_2019-04-22_20-02-39](https://user-images.githubusercontent.com/37319328/56541412-98a4f700-6539-11e9-98b7-57a65cca1f4d.png)
oh okay so i tried again today and this is the error i got.

**Comment by JC5** [comment]
Edit the .env file and change the login data to your database. This is all in the documentation.
