### ISSUE TITLE
Add new trigger "Category Starts With"

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2241]
**Description**
Add a new trigger to match categories that starts with a specific string.

**Solution**
Enable the rules to have a wildcard start for categories

**What are alternatives?**
Manually adding all categories
 
**Bonus points**
I have several categories that belong together on some context like:

Food:Lunch
Food:Dinner

I want to apply rules to those categories, and today I have to add one by one. It would be really nice to have a "Starts With" on the category field.

**Comment by JC5** [comment]
Good idea, it's on the list. 

https://github.com/firefly-iii/firefly-iii/projects/5#card-20639083
