### ISSUE TITLE
Increase the number of suggestions on the Typeahead JS

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2242]
**Description**
By default typeahead brings only 5 suggestions, it would be good to have more suggestions coming on Firefly III.

**Solution**
Change the JS code.

**What are alternatives?**
None

**Bonus points**
I wrote a JS that shows how we can change this behavior (in the example, I set it to 15 on the categories).

(sorry, can't seem to find out how to paste this code without breaking it) 

`
function initCategoryAC() {
    var categories = new Bloodhound({
                                        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                                        queryTokenizer: Bloodhound.tokenizers.whitespace,
                                        prefetch: {
                                            url: 'json/categories?uid=' + uid,
                                            filter: function (list) {
                                                return $.map(list, function (name) {
                                                    return {name: name};
                                                });
                                            }
                                        },
                                        remote: {
                                            url: 'json/categories?search=%QUERY&uid=' + uid,
                                            wildcard: '%QUERY',
                                            filter: function (list) {
                                                return $.map(list, function (name) {
                                                    return {name: name};
                                                });
                                            }
                                        }
                                    });
    categories.initialize();
    $('input[name="category"]').typeahead({hint: true, highlight: true,}, {source: categories, displayKey: 'name', autoSelect: false,limit:15});
}
`

**Comment by JC5** [comment]
I can move to 7 or 8 but I don't want to return big lists.

**Comment by iwalucas** [comment]
Sure, today I am having a hard time specially with similar suggestions. 10 would be great. Having this as an option on the profile is too out of scope?
Tks!
