### ISSUE TITLE
Error: You seem to be using SQLite in a Docker container. Don't do this. If the container restarts all your data will be gone.

### ISSUE THREAD

**Issue by joggie** [firefly-iii/firefly-iii#2243]
Please let me disable this Error Message.
I've mounted /var/www/firefly-iii/storage/database/database.sqlite outside the container so the container can restart and the data is not lost!

**Comment by JC5** [comment]
Launch your instance with the environment variable IS_DOCKER set to false. That should remove it.

**Comment by joggie** [comment]
sadly I don't think this will work since IS_DOCKER is set to true in the .env file:
https://github.com/firefly-iii/firefly-iii/blob/master/.deploy/docker/.env.docker without any variable
it does not work when I set it with an environment variable

**Comment by JC5** [comment]
Have you tried it already?

**Comment by joggie** [comment]
yes, I've added it via docker run -e so the container starts with the variable set to false
"echo $IS_DOCKER" in the container returns false, so it is set as environment variable inside the container but the Warning ist still shown.

**Comment by JC5** [comment]
Ok. Browse to /flush just in case.

**Comment by joggie** [comment]
still there :(

**Comment by JC5** [comment]
You're running the latest version?

The code that does it is [fairly simple](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Middleware/Range.php#L110).
