### ISSUE TITLE
Expense/Revenue report showing wrong information

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2244]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

Running the Expense/Revenue report displays the exact same information on the Expenses (top 10) and Revenue / income (top 10) sections (and it is not showing only the top 10).

**Steps to reproduce**
Run the report Expense/Revenue report
(here is my url:
>/reports/account/15,13,39,4,14,2,11,35,1,9,12,16,3,7,18,5,10,37,17,6,34,8/20,47/20190101/20191231

**Expected behavior**
Have a expense section and a revenue section accordingly 

**Extra info**

 >Debug information generated at 2019-04-25 00:04:00 UTC for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | saxonica |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2019-04-01 00:00:00 |
| Session end | 2019-04-30 23:59:59 |
| Session first | 2009-12-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Bonus points**
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/3654783/56701357-13eee000-66d5-11e9-9b04-524dd9aabcfd.png">

**Comment by JC5** [comment]
That’s strange, thanks for letting me know!

Could you make screenshots of each individual transaction for me please? I wonder what could have caused this.

**Comment by iwalucas** [comment]
@JC5 thats weird, I just ran the same report again and it worked as expected. I will close this for now, but will keep an eye on this report. Tks
