### ISSUE TITLE
Add cron to the firefly container

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2245]
**Description**
I am using the firefly iii docker, but it doesn't have cron installed by default.

**Solution**
Connect to the docker and run `apt install cron`

**What are alternatives?**
Manually installing it

**Comment by JC5** [comment]
I thought this was on the roadmap but it isn't. Sorry about that:

https://github.com/firefly-iii/firefly-iii/projects/5#card-20746359

It is now, thanks!

**Comment by cmantsch** [comment]
Modifying the running container seems to be a bad practice, as the change will be lost when the container is recreated / updated to a new version.
As a workaround I currently set up a cronjob on the host system, which triggers the job via `curl` using the API as mentioned in the [documentation](https://firefly-iii.readthedocs.io/en/latest/installation/cronjob.html#cron-job-that-requests-a-page). This way it won't break on updates.
