### ISSUE TITLE
Trying to disable a currency not possible using listing

### ISSUE THREAD

**Issue by 0x3333** [firefly-iii/firefly-iii#2246]
I'm using Firefly III Version 4.7.17 in a Docker Container.

In a clean installation, I enable BRL currency and set it as Default. When I try to disable EUR in the listing screen, it says it is in use, but the installation is clean, just some accounts with currency set to BRL.

If I enter the EUR edit, and uncheck Enabled and save, it works.

Error message(I used the button highlighted in the image to disable it):
![Screen Shot 2019-04-25 at 16 55 19](https://user-images.githubusercontent.com/289289/56764486-29b6e080-677b-11e9-9d95-3c7862f7f4f1.png)

Screen with EUR disabled after entering the edit page:
![Screen Shot 2019-04-25 at 16 55 44](https://user-images.githubusercontent.com/289289/56764447-173ca700-677b-11e9-870c-f51f2b168fbd.png)

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by bezmi** [comment]
I can confirm that I get this bug as well.

**Comment by JC5** [comment]
Thanks. Sorry, I missed the part where the bot closed the issue.

**Comment by 0x3333** [comment]
Dear Bot, please, don't close it again.. :)

**Comment by jeremyy294** [comment]
Can confirm also experiencing this bug when trying to remove Euro. Can be removed from SQL database but not in UI.

**Comment by JC5** [comment]
I'm aware this his happening guys, there's no need for further confirmations.

**Comment by JC5** [comment]
This will be fixed in the next release. Disabling the EUR can be buggy so I don't recommend it.
