### ISSUE TITLE
Manual for Centos 7

### ISSUE THREAD

**Issue by Dofamin** [firefly-iii/firefly-iii#2247]
I am running Firefly III version 4.7.17

### **Do not forget to change the .env file.**
`yum -y update && yum -y upgrade
yum -y install  unzip net-tools nano yum-cron wget epel-release
##################################
#			   Yum-Cron		               #
##################################
cp /etc/yum/yum-cron.conf /etc/yum/yum-cron.conf.bak
sed -i -e 's/apply_updates = no/apply_updates = yes/g' /etc/yum/yum-cron.conf
systemctl start yum-cron
systemctl enable yum-cron
##################################
#			  MySQL			              #
##################################
yum install -y mariadb mariadb-server
systemctl enable mariadb.service
systemctl start mariadb
/usr/bin/mysql_secure_installation
systemctl restart mariadb
CREATE USER FireFly@localhost IDENTIFIED BY '**PASSWORD**';
CREATE DATABASE FireFly;
GRANT ALL privileges ON `FireFly`.* TO 'FireFly'@localhost;
FLUSH PRIVILEGES;
exit;
##################################
#			  Apach			              #
##################################
yum -y install httpd
firewall-cmd --permanent --zone=work --add-service=http
firewall-cmd --permanent --zone=work --add-service=https
systemctl enable httpd
systemctl start httpd
cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.bak
##################################
#			  PHP			     #
##################################
rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum -y install yum-utils
yum update
##################################
#			  PHP 7.2		     #
##################################
yum-config-manager --enable remi-php72
yum -y install php php-opcache
systemctl restart httpd.service
yum -y install php-mysqlnd php-pdo
yum -y install php-pdo php-pdo-dblib php-mysql
yum -y install php-gd php-ldap php-xml php-intl php-mbstring php-curl php-zip php-mbstring php-bcmath curl curl-devel
systemctl restart httpd.service
##################################
#			  Composer 		     #
##################################
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
composer -v
##################################
#			  Firefly III 	     #
##################################
cd /var/www/
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii **LATEST VERSION**
cp /var/www/firefly-iii/.env /var/www/firefly-iii/.env.bak
sed -i -e 's|TZ=Europe/Amsterdam|TZ=Europe/**CHANGE CITY**|g' /var/www/firefly-iii/.env
cd /var/www/firefly-iii/
php artisan migrate:refresh --seed
php artisan firefly:upgrade-database
php artisan firefly:verify
php artisan passport:install
echo "<VirtualHost *:80>
DocumentRoot /var/www/firefly-iii/public
<Directory /var/www/firefly-iii/public>
Options -Indexes +FollowSymLinks
AllowOverride All
Order allow,deny
allow from all
</Directory>
</VirtualHost>
"> etc/httpd/conf.d/firefly.conf
chown -R apache. /var/www/firefly-iii
##################################
#			  SeLinux		     #
##################################
sed -i -e 's|SELINUX=enforcing|SELINUX=disabled|g' /etc/selinux/config
reboot now

`

**Comment by JC5** [comment]
Thanks! 

Could you use back-ticks to escape the command line entries, and create a [Gist](https://gist.github.com/) out of it? That way, I can include it in the documentation.

**Comment by Dofamin** [comment]
> Thanks!
> 
> Could you use back-ticks to escape the command line entries, and create a [Gist](https://gist.github.com/) out of it? That way, I can include it in the documentation.

This kind?

[FireFly-iii.txt](https://github.com/firefly-iii/firefly-iii/files/3119772/FireFly-iii.txt)

**Comment by JC5** [comment]
Yes, but maybe add some instructions or text as well? That would make it a bit more user friendly.

**Comment by Dofamin** [comment]
Honestly, I do not know what to add there. :)
