### ISSUE TITLE
Fortnightly Bill repeat

### ISSUE THREAD

**Issue by NielsMaschmeyer** [firefly-iii/firefly-iii#2248]
**Description**
- I would like Firefly III to give me the option to have a fortnightly Bill repeat.

**Solution**
- A new drop down "Fortnightly" in the Bill repeat selection.

**Comment by JC5** [comment]
You can set it to weekly and make it skip 1.

**Comment by NielsMaschmeyer** [comment]
Oh yes. Silly me. Thanks!

**Comment by anthonyirwin82** [comment]
I had the same issue and almost gave up on the software, nice to see the skip option.

I still think that it would be good to have a fortnightly option as it is more intuitive to people seeing it in the drop down list then having to know that you can make skip 1.
