### ISSUE TITLE
Revenue Account shows negative amounts

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2251]
I am running Firefly III version 4.7.17

**Description**
Why does the Revenue account shows negative amounts on the charts? I understand it should be positive.

**Bonus points**
<img width="761" alt="image" src="https://user-images.githubusercontent.com/3654783/56919159-46625980-6a96-11e9-80e8-0018cf80878d.png">

**Comment by JC5** [comment]
It’s from their perspective. If a revenue account pays you, it loses money.

**Comment by iwalucas** [comment]
ahhh that makes more sense :)
Tks
