### ISSUE TITLE
Migrate docker installation to new host

### ISSUE THREAD

**Issue by josephbadow** [firefly-iii/firefly-iii#2252]
I am running Firefly III version 4.7.17

**Description**
I installed the current Firefly III on my laptop using docker. This works pretty well and survives reboots and standby. By now I added quite a bit of data into the software and want to migrate it away from my laptop to a raspberry.

I understand now that the raspberry architecture prevents me from simply moving my docker content over - that's what I initially wanted to ask.

So whats the best way for me to move the data to the Raspberry? It is not set up yet, but I think I just go with Raspbian lite as OS.

I have no plans to run other applications on it so I don't have to use docker if somebody advises against it.

Your advise is greatly appreciated.

**Extra info**
- Ubuntu 19.04
- Docker 18.09.5
- I used docker-compose based on the official documentation

**Comment by JC5** [comment]
You can migrate to any new system as long as you save the APP_KEY from the launch command. The database will migrate over smoothly.

The easiest way to migrate attachments is to grab the file from the storage volume (`att-123.data`) and move them over to the new /storage/uploads location.
