### ISSUE TITLE
Sum calculation in Category view

### ISSUE THREAD

**Issue by cyberax17** [firefly-iii/firefly-iii#2253]
Hi,

is there any way to show the total sum (in EUR) if you are in the category view?
If I choose a certain category, it lists me all transactions in this category, and on the very right the sum per month, but is there also a total sum for this category (e.g. in the time window chosen on the very top)?

Thanks for your help in advance!

Runnin FF 4.7.11

**Comment by JC5** [comment]
No, sorry. I'll put it on the list!

https://github.com/firefly-iii/firefly-iii/projects/5#card-20977662
