### ISSUE TITLE
Remember Reconciliation State

### ISSUE THREAD

**Issue by tgrosinger** [firefly-iii/firefly-iii#2254]
**Description**

When reconciling an account in Firefly-III, I often has one or two transactions which were not entered when they occurred. When this happens I need to enter them in a new tab, then refresh my reconciliation window. Refreshing clears all the progress and I must restart the reconciliation.

**Solution**

One possible solution would be to add a "refresh transactions" button on the reconciliation page. This button would look for new transactions to add to the list, without changing anything else.

**What are alternatives?**

Only alternative I have found is to enter the transaction on a new tab, and then refresh/restart the reconciliation.

Thank you!

**Comment by JC5** [comment]
Maybe in the new layout, but it's a lot of work for the current layout I'm afraid.

**Comment by tgrosinger** [comment]
That's fair. Can you point me to information about the new layout? Is there an overview, or an expected release date?

**Comment by JC5** [comment]
You’ll know when I know :)

**Comment by tgrosinger** [comment]
Haha deal, thanks. Should I leave this open so it's considered in the redesign, or close it?

**Comment by JC5** [comment]
Nah you can close it. The redesign will also be a single page application and I'll probably introduce it slowly, so you can switch in the settings. Some things need to be designed from the ground up.
