### ISSUE TITLE
errors  final stage installation

### ISSUE THREAD

**Issue by kdaffef** [firefly-iii/firefly-iii#2255]
**Bug description**
I am running Firefly III version 4.7.17 unr vultr vps, and my problem is:

followed great ubuntu 16.04 with nginx tutorial [link](https://old.reddit.com/r/FireflyIII/comments/8thxuu/fireflyiii_on_ubuntu_server_1604lts_nginx_php72/)  and here is my nginx host file  🥇 

server {
    listen my-ip:80;
    # listen [::]:80 default_server;
    root /var/www/html/firefly-iii/public;
    index index.php index.html index.htm index.nginx-debian.html;
    server_name budget.mydomain.com;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        autoindex on;
        sendfile off;
    }
      location ~ \.php$ {
      include snippets/fastcgi-php.conf;
      fastcgi_pass unix:/run/php/php7.2-fpm.sock;
      }
      location ~ /\.ht {
      deny all;
      }
}

**Steps to reproduce**
at last install stage  :
sudo php artisan migrate:refresh --seed
gives this issue  

PHP Warning:  require(/var/www/firefly-iii/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/firefly-iii/artisan on line 18 

and same for following command "sudo php artisan passport:install"
**Extra info**
- vulr ubuntu 16.04 fine working server / nginx and all requirements 
- checked that /firefly-iii/ not contains /vendor/ sub-folder : should create it ?
- read similar issues topics but no way to finish the install - and land on Firefly greay dashboard ...

**Comment by JC5** [comment]
Did you install composer and run the commands under heading **2. Firefly-III Part**?

**Comment by kdaffef** [comment]
hi, nice to get your reply,

yes, re-run composer instal and here is output :

All settings correct for using Composer
Downloading...

Composer (version 1.8.5) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

**Comment by JC5** [comment]
And this one?

sudo composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.7.17

**Comment by kdaffef** [comment]
Problem 1
    - The requested PHP extension ext-bcmath * is missing from your system.
Install or enable PHP's bcmath extension.
  Problem 2
    - Installation request for adldap2/adldap2 v10.0.4 -> satisfiable by
adldap2/adldap2[v10.0.4].
    - adldap2/adldap2 v10.0.4 requires ext-ldap * -> the requested PHP
extension ldap is missing from your system.
  Problem 3
    - adldap2/adldap2 v10.0.4 requires ext-ldap * -> the requested PHP
extension ldap is missing from your system.
    - adldap2/adldap2-laravel v5.1.2 requires adldap2/adldap2 ^10.0 ->
satisfiable by adldap2/adldap2[v10.0.4].
    - Installation request for adldap2/adldap2-laravel v5.1.2 ->
satisfiable by adldap2/adldap2-laravel[v5.1.2].

Oh!!, 3 issues, any fast way to verify and install missing php extensions
plz ?
(didn't noticed that before, sorry)

**Comment by kdaffef** [comment]
- installed missing bcmath  and ldap php extensions. Install script goes
straight ...

Thank you for you help, will be excited to discover firefly-iii, a lot of
thanks and will pay a coffee!

**Comment by JC5** [comment]
No problem, glad it runs! Thanks!
