### ISSUE TITLE
Prompted to download on fresh install

### ISSUE THREAD

**Issue by eraserpencil** [firefly-iii/firefly-iii#2256]
I am running Firefly III version 4.7.17

**Description**
I am attempting to self-host on a VPS. i have done all the steps up to 
    `php artisan passport:install` successfully. But when I point my browser to my domain or even the ip address of the VPS, I get prompted to download a file.

In /etc/nginx/sites-available/, I have root at /home/$USER/firefly-iii. index.php

I'm not sure why going to the ip address prompts me to download something.

**Extra info**
Ubuntu 16.04.

**Comment by JC5** [comment]
I expect that you have misconfigured the web server, making it unable to serve php files.

**Comment by eraserpencil** [comment]
> I expect that you have misconfigured the web server, making it unable to serve php files.

Could you share your config or guide me?

**Comment by JC5** [comment]
Sure, this is the config from the demo site. Does your config also have the PHP config?

Keep in mind this config also has TLS and HSTS included in it. Just copying it might break things. But it contains everything you need.

```

server {
        listen 443 ssl;
        root /opt/www/demo.firefly-iii.org/public;
        index index.php;
        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
        add_header X-Frame-Options "DENY";
        server_name demo.firefly-iii.org;
	add_header Access-Control-Allow-Origin "*";
	add_header Access-Control-Allow-Methods "GET, PUT, POST, DELETE, OPTIONS";
	add_header Access-Control-Allow-Headers "Content-Type, api_key, Authorization";
        location / {
                try_files $uri $uri/ /index.php$is_args$args;
        }

        client_max_body_size 300M;

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
		add_header Access-Control-Allow-Origin "*" always;
		add_header Access-Control-Allow-Methods "GET, PUT, POST, DELETE, OPTIONS" always;
		add_header Access-Control-Allow-Headers "Content-Type, api_key, Authorization" always;
        }

        location ~ /\.ht {
                deny all;
        }
        location ~ /\.git {
                deny all;
        }
        ssl on;
        ssl_certificate /etc/letsencrypt/live/demo.firefly-iii.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/demo.firefly-iii.org/privkey.pem;
	ssl_ciphers '(snipped)';
	ssl_prefer_server_ciphers on;
	ssl_dhparam /etc/nginx/dhparams.pem;
}

server {
        listen 80;
        server_name demo.firefly-iii.org;
        return 301 https://$host$request_uri;
}

```

**Comment by eraserpencil** [comment]
I'm included what I know and now have 
    ` (1/1) UnexpectedValueException

    The stream or file "/home/$USER/firefly-iii/storage/logs/ff3-fpm-fcgi-2019-05-04.log" could not be opened: failed to open stream: Permission denied`

when checking storage/logs, all I have are ff3-cli logs.. nothing else. I do have php7.2-fpm installed.

**Comment by JC5** [comment]
In that case, user access rights for the /home/$USER/firefly-iii folder are not correct. You must make sure that your web user (usually www-data) has write access to the Firefly III logs folder. To fix that, it might have to be the owner of the directory.
