### ISSUE TITLE
403 Permissions Denied

### ISSUE THREAD

**Issue by SergiuCip** [firefly-iii/firefly-iii#2258]
**Bug description**
I am running Docker Firefly III latest version on a Raspberry PI, and my problem is:

AH00035: access to / denied (filesystem path '/var') because search permissions are missing on a component of the path

**Steps to reproduce**

Start the container and navigate to the URL

**Expected behavior**

Install page?

I have tried the followings to mitigate the issue but I was unsuccessful:

Change permissions for /var/www/firefly-iii to 755
Restart apache

**Comment by JC5** [comment]
I've never seen that error before. Strange. Especially since it's the /var directory. That should be part of the container and that hasn't changed in weeks.

Can't you redeploy the container?

**Comment by SergiuCip** [comment]
I did couple of times using: release-4.7.17-arm and release-4.7.16-arm

**Comment by JC5** [comment]
How did you restart apache?

**Comment by SergiuCip** [comment]
`apachectl graceful`
`apachectl reload` which resulted in the container restarting
`restart the container:` docker stop <container_id> && docker start <container_id>

**Comment by JC5** [comment]
Sorry, I haven't had the time yet to dive into this issue.

**Comment by SergiuCip** [comment]
No worries mate :)

I have fixed it just now by editing the www-data user in /etc/passwd file to match my local UID and GID

Maybe, in your Dockerfile you can add 2 additional environment variables which will allow you to pass the UID and GID to the container.
