### ISSUE TITLE
Initial balance is not taken into account for total balance

### ISSUE THREAD

**Issue by RodrigoLeiteF** [firefly-iii/firefly-iii#2260]
I am running Firefly III version 4.7.17

**Description**
I recently installed Firefly with an account with initial balance of around R$7000. The amount shows up as net worth correctly, but the Balance block shows R$0 (R$-157, since I made a few transactions). Shouldn't the initial balance of my account be taken into account?

**Extra info**
 
Debug information generated at 2019-05-06 17:55:28 America/Sao_Paulo for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2019-05-01 00:00:00 |
| Session end | 2019-05-31 23:59:59 |
| Session first | 2019-05-04 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Bonus points**

![image](https://user-images.githubusercontent.com/16887983/57254679-40d1ba00-7028-11e9-8cea-d6e20cab74bf.png)

**Comment by JC5** [comment]
This is correct. The balance box will only take your transactions into account. It just shows the current periods balance changes.

**Comment by RodrigoLeiteF** [comment]
I see. Thanks for the clarification, and thanks for Firefly. Been loving it so far :)
