### ISSUE TITLE
Salt Edge API v5

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2261]
It appears that Salt Edge v4 will be deprecated on March 31, 2020. Will v5 API be on the roadmap?

**Comment by JC5** [comment]
Not for Firefly III itself. I plan to move import routines to separate apps, utilizing the API.

**Comment by emansih** [comment]
So Spectre will be "modular" next time?

**Comment by JC5** [comment]
I'm not sure what form it would take yet, but I'm moving to take all the import code out of the core of Firefly III. That would mean it would be a separate app, possibly a plugin. This paves the way for improvements to these routines outside of the update cycle of Firefly III and it allows people to develop their own import routine.

**Comment by emansih** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1954#issuecomment-450748674
> I just don't see a use case for plugins.

What made you change your mind?

**Comment by JC5** [comment]
Good point, let me clarify. At best I’d like Firefly III list the options, possibly fed from a curated list on firefly-iii.org. I had a discussion with a friend who suggested plugins. I’m not opposed to making it easier for users to import data but plugins like Wordpress et al are not going to happen.

**Comment by abctaylor** [comment]
Just for the sake of clarity - what is the roadmap on Spectre for the future? It is an elegant way to import automatically from a vast collection of providers.

> Not for Firefly III itself. I plan to move import routines to separate apps, utilizing the API.

What separate apps would these be?

**Comment by JC5** [comment]
I don't know yet. Probably a command-line thing.

**Comment by abctaylor** [comment]
Thanks. Building o this topic, would support for .csv files also be phased out, such as Spectre might (likely) be from the GUI? i.e. will all importing be via cli?

**Comment by JC5** [comment]
It’s more that I want to move the functionality out of Firefly III. It could still be a GUI or anything.
