### ISSUE TITLE
Basic API-Request

### ISSUE THREAD

**Issue by SwapFaceL** [firefly-iii/firefly-iii#2263]
I am running Firefly III version 4.7.17.

**Description**
I've installed firefly on Ubuntu Server 18.04 LTS on apache. I wanted to try using the API now. I've requested an OAUTH Token with postmen like described in the docs. After this was successful I tried sending a simple GET request but instead of an API-Answer (JSON) I just got the website returned. 

The app is hosted as: https://my.url/firefly, so I tried https://my.url/firefly/api/v1 ...
So it seems like the API is not reached properly. Any ideas?

--> Just using firefly-iii for some days and I really like it, great work!

**Comment by JC5** [comment]
Which URI did you try exactly?

If you send the correct authentication and add Accept: application/json it should respond. 

But “api/v1” is not an endpoint in itself.

**Comment by SwapFaceL** [comment]
Thanks for the stellar fast reply.
It works now! I forgot to send "Accept: application/json" in the Header.

Now I just need to find out if I can implement a workaround to automize the data import from the bank ;)
