### ISSUE TITLE
FinTS Import on Sandstorm

### ISSUE THREAD

**Issue by SwapFaceL** [firefly-iii/firefly-iii#2264]
**Bug description**
I've installed firefly-iii (v 4.7.17) manually on my webserver (Ubuntu Server 18.04 LTS + apache) and tried importing data via FinTs.
Worked like a charme!

When installing the app through sandstorm market (v 4.7.9) the import (same configuration) did not work. The displayed error is:
"Warning! An error occurred while trying to connecting to your bank. Please make sure that all the data you entered is correct. Original error message: Failed connection to ---: Could not resolve host: --- "

Maybe a bug in the old version?!

**Comment by JC5** [comment]
This error:

: Failed connection to ---: Could not resolve host: --

indicates that he host could not be found. That's not a Firefly III exception, I'm afraid.

If I recall correctly, Sandstorm will NOT allow you to connect to the outside world. So FinTS + Sandstorm won't work I'm afraid.

**Comment by Athesis** [comment]
Hi,

Would be nice if this problem could be fixed. If I understand it right, the premission must be requested:
https://docs.sandstorm.io/en/latest/developing/auth/#about-sandstorm-http-bridge

... In Sandstorm Admin panel is also "Network capabilities" what suggests at that it should be possible.

**Comment by JC5** [comment]
I've created a card for the next version to fix this.

https://github.com/firefly-iii/firefly-iii/projects/5#card-21931338
