### ISSUE TITLE
iOS shortcut to record withdrawals / CORS

### ISSUE THREAD

**Issue by brasilikum** [firefly-iii/firefly-iii#2265]
I would like to have some kind of a client for my Iphone with a very specific feature-set:
- only for adding of withdrawals
- offline capable
- easy attaching of receipt
- OCR of receipt for easier searchability

I assume this is too much bloat for the firefly III itself and there seem to be no clients for iOS so I looked into possible implementations myself.
I started an iOS shortcut to record withdrawals via the API. Here is what I have to far:
https://www.icloud.com/shortcuts/e86b51fd295a42bca6b007abc8a38a72
- it works but only records description, amount and tags

I realize that at this point it has even less functionality then the web app, but in the future it could potentially gain all of the above, if I find the right tools. On the other hand programming a shortcut is not exactly a straight forward experience.

I could potentially scratch my itch with a modern web-app, but the API would need to support COTS-configuration for that. I have not found any documentation on CORS, is it possible to configure?

Is this a usercase other users are interested in as well?

**Comment by JC5** [comment]
This is pretty interesting :+1:

Why would the API need to support CORS? You can call the API from anywhere with the right authentication, or is this different in iOS?

**Comment by brycecammo** [comment]
@brasilikum Here's a shortcut that allows you to upload an attachment (image or PDF) and assign it to a chosen withdrawal. Works well from the share sheet inside Photos.app. 

https://www.icloud.com/shortcuts/2a62b4e4be9b4573b35cb6368fc710e8

**Comment by emansih** [comment]
Regarding OCR, I find that it is much easier to search the records via transaction description

**Comment by brasilikum** [comment]
@JC5 I think that was what I wanted to ask :) It would have to support transactions from anywhere. Given that you trust the hosted code is the source code, this would allow me to write a static webapp which people could use as clients for their own instances, if they don't want to host it themselves. I will probably take a stab at it these days and report back.

@brycecammo Impressing data transformation skills in this shortcut. I tried this myself but gave up after some time. If you want to make it more usable for other people, you could add the setup questions for instance/auth in the options. I would like to combine our shortcuts, seems like a lot of work given I have to drag stuff around on my phone.

@emansih That's fair, my (maybe unreasonable) dream would be to know how much I spent on tacos last year ;). On a more serious note I think it would be nice to just scan a receipt and have everything filled out but I admit that might produce more errors than if you just type it in.

**Comment by JC5** [comment]
I'm not sure what you're going for, but CORS may not be what you need for that to work. The Firefly III API will allow incoming requests from anywhere, that's the point. 

Personally I doubt there's a use case for "if they don't want to host it themselves" given that Firefly III is a self-hosted app in the first place.

**Comment by brasilikum** [comment]
That would be one more thing to host but I think that's fair to assume.
