### ISSUE TITLE
Export Mapping issue

### ISSUE THREAD

**Issue by AndrewSav** [firefly-iii/firefly-iii#2268]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

When mapping import to Liability account, the program maps to Expense account instead.

**Steps to reproduce**
Create a Liability account. Go to import CVS, and map a column to "Opposing account (name). Mark the checkbox for that column. On the next screen select the Liability account from a dropbox and start the import.

**Expected behavior**
The transaction imported should have the opposing account selected Liability account. It create a new Expense Account with the same name (if does not exist) instead.

**Extra info**
Debug information generated at 2019-05-14 12:22:04 Pacific/Auckland for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2019-05-01 00:00:00 |
| Session end | 2019-05-31 23:59:59 |
| Session first | 2019-05-08 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Comment by AndrewSav** [comment]
Similiraly, if you create a rule to set destination account to a Liability accoun an Expense account is created instead.

**Comment by JC5** [comment]
Thanks, that’s a bug, I’ll write it down.

**Comment by AndrewSav** [comment]
@JC5 Thank you for that. I think that there is also an issue with the autocomplete for `Convert to transfer` It does NOT complete the Liabilty accounts, however, if you type them in manually, lo-and-behold, it works. I'll be using this as a work-around until the above is fixed. Many thanks, again.

**Comment by JC5** [comment]
Thanks for letting me know. Both issues are fixed in the next release.
