### ISSUE TITLE
Which accounts should I "Include in net worth"?

### ISSUE THREAD

**Issue by AndrewSav** [firefly-iii/firefly-iii#2269]
I am running Firefly III version 4.7.17

**Description**
How do I chose when to check / uncheck the "Include in net worth" mark against an account? Expense accounts created from imports get this box automatically checked, which implies that this is a reasonable default, yet I'm not sure how Expense Accounts should affect net worth, could you please explain this to me?

**Comment by JC5** [comment]
Just include everything. You could remove liabilities but otherwise don’t bother with the setting.

**Comment by AndrewSav** [comment]
But can you tell me why it makes sense to include Expense accounts in there? Or are they always ignored for net worth so it does not matter? @JC5

**Comment by JC5** [comment]
They’re always ignored. I’ll write down to update the setting.

**Comment by AndrewSav** [comment]
Thank you!
