### ISSUE TITLE
How should I upgrade my heroku installation? 

### ISSUE THREAD

**Issue by daraul** [firefly-iii/firefly-iii#2271]
I am running Firefly III v4.7.9 on Heroku

**Description**
For a while, now, I've been just clicking the OK button whenever I see an update notification on my installation, thinking it updated in the background. I just noticed it hasn't been updating, and now I'm way behind! I couldn't find any docs on how exactly I should go about updating my installation, so I figured I'd ask.
I suppose I could back up the database (either through heroku itself, or from firefly's export feature), and simply install a new heroku app and import everything back. Would that work the way I expect?
I'm the only user on my instance, so losing the account doesn't matter to me much, so long as I don't stand to lose the transactions and accounts.

**Comment by JC5** [comment]
I have no idea. I think that you could set up a new heroku thing and link it to the old database. Make sure to back it up.

**Comment by Jumanjii** [comment]
@daraul So what did you do?

**Comment by daraul** [comment]
Nothing so far, @jumanjii

**Comment by daraul** [comment]
@Jumanjii I just did a small PR on the docs repo with instructions on migrating to a new heroku installation here: https://github.com/firefly-iii/docs/pull/33

Let me know how it goes.

**Comment by daraul** [comment]
I just realized that you can also attach the PGS database to your new installation as well. Not

**Comment by daraul** [comment]
I just realized that you can also attach the existing PGS database to your new heroku installation, but that might not be the best idea since migrations might not run on the new installation to upgrade the old DB. Thoughts @JC5?

**Comment by JC5** [comment]
They should, they're triggered by the "db_version" field in your database. This also works over the web.
