### ISSUE TITLE
Some notes on importing from YNAB 4

### ISSUE THREAD

**Issue by ment4list** [firefly-iii/firefly-iii#2272]
First of thank you for the great app you've made!

I previously used _You Need a Budget_ (YNAB 4) so had a lot of data in there that I wanted to move into Firefly to get better reports and insights.

The terminology and way to do things in Firefly is a little different than YNAB so it took a bit of time. I just want to put these thoughts down somewhere so that it might be useful to someone else trying to migrate.

I wasn't sure where to post this, hence why it's here. (I searched here for YNAB assistance initially as well.)

### Formatting YNAB export

I imported the YNAB export into a Google Sheets spreadsheet.

I kept the following columns:

- Account
- Date
- Payee
- Master Category
- Sub Category
- Memo
- Outflow <- G
- Inflow  <- H
- Amount

First I created an "Amount" column which combines the "Outflow" and "Inflow" columns.
(Where G = Outlfow column and H = Inflow column)

    =IF(G2,G2*-1, (IF(H2, H2, 0)))

You can then map this "Amount" column to Firefly III's amount column during the import process.

### Setting up Firefly

First I created all my accounts inside Firefly using the exact same names as in YNAB.

Then, I created "Budgets" for all my "Master Categories." This didn't seem to work as expected.
I believe it's because I didn't map it during the import process.

During the import process in Firefly I "mapped" only the "Account Name" field.

**YNAB to Firefly:**

- Account         -> Account Name (_mapped_)
- Date            -> Date (format d/m/Y)
- Payee           -> Opposing Account Name
- Master Category -> Category Name
- Sub Category    -> Category Nane
- Memo            -> Note
- Outflow         -> _Skipped_
- Inflow          -> _Skipped_
- Amount          -> Amount

### Import Setting Config

```
{
    "file-type": "csv",
    "date-format": "d\/m\/Y",
    "has-headers": true,
    "delimiter": ",",
    "apply-rules": false,
    "specifics": [],
    "import-account": 1,
    "column-count": 9,
    "column-roles": [
        "account-name",
        "date-transaction",
        "opposing-name",
        "budget-name",
        "category-name",
        "note",
        "_ignore",
        "_ignore",
        "amount"
    ],
    "column-do-mapping": [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "column-mapping-config": [
        {
            // Your Account Name config...
        }
    ]
}
```

## Troubleshooting

I had some issues with importing and formatting so I had to start over a couple of times.

#### Could not be imported

I had a couple of issues with duplicates (mostly toll gate transactions with the same amounts, date, and description.)

Thankfully it wasn't too many so I manually added them. (I simply added a `Not Duplicate` message in the description for reference)

> Row #Z ("") could not be imported. It already exists.

If you have headers in your import file, remember to increment the row number by 1 ;)

#### Clearing transactions

If you want to restart without clearing all your accounts, categories or budgets, open the PostgreSQL command (`psql -U DB_USERNAME`)
and run the following command to remove and clear all transactions:

    truncate tag_transaction_journal, journal_meta, transaction_journals, budget_transaction_journal, category_transaction_journal, piggy_bank_events, budget_transaction, category_transaction, transactions, journal_links, group_journals;

Thanks again!

**Comment by JC5** [comment]
Thank you! This is an excellent write-up. Although I expect the issue will eventually close, I'll mention it in the docs, for future users to find and respond.

Thanks again. I really appreciate it.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/en/latest/import/ynab.html

**Comment by ment4list** [comment]
That's awesome. Thanks for the great product.

**Comment by sixtyfive** [comment]
> https://docs.firefly-iii.org/en/latest/import/ynab.html

That URL is 404 now, and there is only https://docs.firefly-iii.org/importing-data/ynab, which is about YNAB the cloud service, not YNAB 4. Are the old docs still accessible somewhere?

**Comment by JC5** [comment]
All I did was link to this issue. The documentation was never more extensive.

**Comment by sixtyfive** [comment]
Oh, I see! Perhaps then mention there that Firefly _supports_ the YNAB *5* API and there there's an _Issue_ about importing YNAB *4* exports? Also, thanks for the quick reply :-)

**Comment by sixtyfive** [comment]
About the duplicates that @ment4list also encountered: I'm getting several hundreds of them and have had trouble figuring out how to prevent FIII from seeing them as such. Even adding an ID column and assigning that to something like Internal Reference doesn't work.

How does FIII determine whether or not a transaction is a duplicate?
Is it just the combination of date, amount and the two accounts?

**Comment by JC5** [comment]
It depends, and your logs can tell you why Firefly III considers them duplicates. Are they transfers or expenses / income?

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by sixtyfive** [comment]
Thanks for those instructions, JC! Looking through the logs it seems that YNAB4's split transactions feature. I'll have to see if I can come up with some way of changing them into proper ones before the import.
