### ISSUE TITLE
Installing in a Docker container in DigitalOcean

### ISSUE THREAD

**Issue by epikkoder** [firefly-iii/firefly-iii#2273]
I've never used Docker before, so this is probably a noob question. Will I be able to install Firefly III using my DigitalOcean account, since it supports Docker containers?

**Comment by JC5** [comment]
Yes, it should work just fine. Don't ask me how because I have no idea.

**Comment by chrif** [comment]
I made a project for beginners who want to use Docker + Digital Ocean + reverse proxy with https (Traefik): https://github.com/chrif/cocotte

You won't be able to use it for firefly-iii but you can certainly take it as an example to figure something out for firefly-iii.

**Comment by epikkoder** [comment]
I was watching a Twitch stream earlier of a developer, and he mentioned something that if you can put it in a Docker container, you can put that container anywhere and use it, so I'm assuming that this should work in DigitalOcean. I should probably write a tutorial once I figure this out. :)
