### ISSUE TITLE
Default rule is re-created after deletion

### ISSUE THREAD

**Issue by Kline-** [firefly-iii/firefly-iii#2274]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

When I delete the default rule or default rule group they are re-created automatically. I say re-created because /rules/delete/# is incremented each time I attempt to delete the rule. After some further testing this only seems to occur if there is only a single rule. After creating a new rule I was able to successfully delete the default one.

**Steps to reproduce**
Click the delete icon on a rule or rule group. Confirm the deletion.

**Expected behavior**
The rule or rule group should be removed.

**Extra info**
Debian (testing) / Chrome 74 browser
Debug information generated at 2019-05-17 20:08:12 America/Chicago for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.4-2 |
| Display errors | Off |
| Session start | 2019-05-01 00:00:00 |
| Session end | 2019-05-31 23:59:59 |
| Session first | 2019-05-17 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; CrOS x86_64 11895.95.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.125 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**
WebM video attached (had to zip for GitHub to accept the upload).
[Rules » Firefly III.zip](https://github.com/firefly-iii/firefly-iii/files/3193498/Rules.Firefly.III.zip)

**Comment by JC5** [comment]
The system will always create the default rule as an example and a fallback. This is by design.

**Comment by Kline-** [comment]
Ah, my apologies then. Thanks for the quick response!
