### ISSUE TITLE
Liabilities Question - Owed TO me

### ISSUE THREAD

**Issue by 8bitgentleman** [firefly-iii/firefly-iii#2276]
I am running Firefly III version 4.7.17

**Description**
I am trying to keep track of a debt that is being repaid to me. I have loaned a family member some money and they are steadily repaying it back. I would like to keep track of this using Firefly's liabilities. Is this possible? 

Right now I have a series of deposits from my family member into my bank account. I would like to convert those deposits to a transfer from the liability account into my bank account in order to keep track of how much is still owed to me. I have created a loan liability account and set the initial balance as the amount that is owed to me. When I try to convert the deposit into a transfer the amount of the liability account increases instead of decreases. 

I didn't see much documentation on liabilities in the wiki and am a little confused on how to make this work. Any suggestions? Thanks

**Comment by JC5** [comment]
That could work, but I hope to improve this in the next version. What you could also do is simply create an asset account with the correct amount that you slowly transfer over to your own asset accounts.

**Comment by 8bitgentleman** [comment]
Thanks for the reply. I guess I'll use an asset account for now till next release :smile:

**Comment by staadecker** [comment]
Just wanted to say that I'm also interested in this feature!

**Comment by JC5** [comment]
That's fine because it already works. Just add it as a negative amount and read the help.
