### ISSUE TITLE
Settings to make after installation, before first run

### ISSUE THREAD

**Issue by ohreally** [firefly-iii/firefly-iii#2277]
Hi,

Just installed Firefly-III. Here are some settings I had to change to make stuff work (I never install everything owned by Apache). You may want to add this to the documentation.

First is **AllowOverride all**, which should be set for the DocumentRoot to make the .htaccess work.

And then some permissions:
```
mkdir storage/framework/views/twig
chown apache:apache storage/framework/views/twig
chown apache:apache storage/logs
chown apache:apache storage/framework/cache/data
chown apache:apache storage/framework/sessions
chown apache:apache storage/framework/views/v1
```
Or, using ACL:
```
mkdir storage/framework/views/twig
setfacl -m u:apache:7,d:u:apache:7 storage/framework/views/twig
setfacl -m u:apache:7,d:u:apache:7 storage/logs
setfacl -m u:apache:7,d:u:apache:7 storage/framework/cache/data
setfacl -m u:apache:7,d:u:apache:7 storage/framework/sessions
setfacl -m u:apache:7,d:u:apache:7 storage/framework/views/v1
```
Everything seems to be running smoothly now.

Thanks!

**Comment by JC5** [comment]
Thanks! I'll see what I can add to the documentation that isn't already there. :+1:
