### ISSUE TITLE
Recurring budgets

### ISSUE THREAD

**Issue by ohreally** [firefly-iii/firefly-iii#2278]
Hi,

Just a thought...
Would it be possible to have recurring budgets? So, for example, I grant myself 100 euros each week for groceries. And 100 euros each month for car fuel. Et cetera.
I'm not too motivated already to do my personal bookkeeping, and having to recreate these budgets manually again and again would probably not contribute to the fun...

I guess I'm not the only user just trying to make ends meet each month, and I think this could make things a lot easier.

Thanks for considering!

**Comment by JC5** [comment]
There used to be an automated feature but it's difficult to get correctly. And constant attention to your finances is the point of making personal bookkeeping a success.

**Comment by ohreally** [comment]
Absolutely. And automation is the point of writing software... ;-)

So, my next question would have to be: are you planning on including a plugin system, so I could add this functionality myself?

**Comment by JC5** [comment]
There's an API you can use.

**Comment by JC5** [comment]
But like I said, if automation is your goal your personal budget won't improve. I leave it to you to build something :)

**Comment by ohreally** [comment]
Then I guess I won't be needing Firefly-III. Thanks!

**Comment by viharm** [comment]
> 
> 
> But like I said, if automation is your goal your personal budget won't improve. I leave it to you to build something :)

@JC5, I respectfully disagree with you. Automating recurring tasks does not mean one does not pay attention. A compromise would be to _repeat the previous period's budget_. Most people have similar (if not same) salary/income each month, so they have the same amount to budget. I have a standard list of budgets over which I apportion my salary each month. I am confident that I am not the minority by following this approach.

**Comment by funnym0nk3y** [comment]
I don't want to go over the same things each month. I have a fixed budget each month I can spend (and not save in "Pay yourself first"). This is a guideline to restrict my spendings to a fixed value on average. This does not only need to set a automated budget each month, but also to transfer the balance to the next month. This is very useful when tracking irregular expenses and treats to myself. 
It's not always about saving more or improving the budget. For me it is to create metrics to base my decisions on. 

@viharm In addition I would assume a contrary effect. If I have to do it each month, I do not pay attention at all. It becomes a routine. On the other hand if I get my financial situation boiled down to metrics automatically I can see where room for improvement is. 

@JC5 Budget keeping specific and personal finance management in general **need** to be automated. If bookkeeping and finance managment is a big hassle for the user, motivation will die down and no entries will be made. I would not need financial software if the usage was comparable to pen and paper. And it is without automation.
