### ISSUE TITLE
Problems with traefik reverse proxy and and a subpath

### ISSUE THREAD

**Issue by anp369** [firefly-iii/firefly-iii#2279]
I am running Firefly III version 4.7.17

**Description**
I run the 4.7.17 version in a docker container behind a traefik reverse proxy and want to expose the instance at the subpath `/firefly`. Unfortunately this doesn't work as expected. When I visit the root page `example.com/firefly` I can see the text of the main page, but the css doesn't load, and no links are working). If the domain was `example.com`, all links would get redirected to root for `example.com/admin` instead of `example.com/firefly/admin`. If I type the firefly by hand I'm able to reach the page, but without css.

**Extra info**
traefik listens on port 80 and 443 and redirects all traffic from port 80 to port 443 to enforce a https connection.This works perfectly fine with all of my other applications (portainer, grafana)
The firefly-iii container runs with the following envs and labels:  

Labels:
- `traefik.enable=true`
- `traefik.frontend.entryPoints=http,https`
- `traefik.frontend.redirect.entryPoint=https`
- `traefik.frontend.rule=PathPrefixStrip: /firefly`
- `traefik.port=80`

Envs:
- `APP_FORCE_ROOT=https://rpi.lan/firefly`
- `APP_URL=https://rpi.lan/firefly`
(adding a '/' at the and doesn't make a difference)

Screenshot of the root page:
![firefly_iii_bug](https://user-images.githubusercontent.com/23340440/58126276-e5e8b700-7c12-11e9-9024-1a195fb7a2f8.png)

I'm not quite sure if this is a problem with traefik, since all of my other containers work with the pathprefixstrip rule. Is there a similar setting like grafanas `SERVER_ROOT_URL`? 

Any help is appreciated, I really like your program :)

**Comment by JC5** [comment]
I never got it to work with nginx because I could never get the sub-path to work either. It's not correctly sent through to the app. I have no idea how to fix this yet, so I am also open to suggestions.

**Comment by anp369** [comment]
I got it working with nginx with the help of the snippet in your [docs](https://firefly-iii.readthedocs.io/en/latest/support/faq.html#i-am-using-nginx-and-want-to-expose-firefly-iii-under-budget).
I already deployed jupyter notebooks with docker and traefik and had the same problem. It could be fixed by telling the notebook that it should be reached under a subpath via a line in a config file. Is there such an option in firefly-iii or the framework it uses?

**Comment by JC5** [comment]
Not that I know of, unfortunately. The info is provided by the webserver and can't really be forced as far as I know.

**Comment by anp369** [comment]
is there a possibility to tune the internal apache server to listen to this subpath? Since I never worked with apache I got no clue where to start looking. Maybe there is a solution with <location> tags?

**Comment by JC5** [comment]
Not to my knowledge, sorry :(

**Comment by anp369** [comment]
allright, thanks for your help anyway. I just run firefly-iii under a subdomain for now, which works without problems with traefik.(Just add the frontend rule `host: *subdomain*.domain)` If you see a possibility to enable the subpaths more easily let me know :)

**Comment by anp369** [comment]
alright, thanks for your help anyway. I just run firefly-iii under a subdomain for now, which works without problems with traefik.(Just add the frontend rule `host: *subdomain*.domain)` If you see a possibility to enable the subpaths more easily let me know :)

**Comment by JC5** [comment]
Will do! :+1:
