### ISSUE TITLE
Is there a way to track forecasted recurring income?

### ISSUE THREAD

**Issue by s3w47m88** [firefly-iii/firefly-iii#2282]
I realize that "Forecasting" is officially mentioned as something that will not be included. But that term is really broad and I'm not sure if my question is in that scope or not.

Right now, I have a three finance things I want to track in Firefly:

- Recurring Income - Clients who pay me money every month. I want to see who, how much, when it's due, and the total of them all.
- Outstanding Income - I have clients who have a contract with me, and have paid a deposit, but still owe money by the end of the project. I'd like to see who, how much is left, when I expect it and the total of them all.

**Comment by JC5** [comment]
Mmmm, it might be possible through the API, but Firefly III offers very little functionality for these use cases. I think you might be better off with other tools to be honest.

**Comment by s3w47m88** [comment]
Would you have a recommended alternative? I'm also happy to have my staff
build such a feature as a module / extension for Firefly if it's welcome!

**Comment by JC5** [comment]
I'm thinking of something like gnuCash or a fully fledged administrative problem? I'm not really at home in the world of corporate finance ;)

**Comment by s3w47m88** [comment]
Okay thanks! We're going to build a module. I love Firefly and it's got everything we need. Would love your feedback on it when we're done - hopefully in a week or two.

**Comment by viharm** [comment]
Did anything ever happen to this? This appears similar to #359

**Comment by s3w47m88** [comment]
We built a simple module, little buggy but DM me and I can share the code with you.
