### ISSUE TITLE
Create a new Loan Account type

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2283]
**Description**
I would like Firefly-iii to have some kind of inverse Liability account, so I can keep track of money that I lend to people or that people own me.

**Solution**
Similar to the Liability account, but a Credit starting balance, instead of a Debt.

**What are alternatives?**
Control using the Revenue/Expense account (two accounts in this case)

**Comment by JC5** [comment]
I'll see what I can do. I'm not a fan of adding a feature that allows people to track every buck they lend.
