### ISSUE TITLE
Handling of "stop processing" in rules

### ISSUE THREAD

**Issue by Kline-** [firefly-iii/firefly-iii#2285]
I am running Firefly III version 4.7.17

**Description**
The [official documentation](https://docs.firefly-iii.org/en/latest/advanced/rules.html#rule-groups) states 

> Rules are divided over rule groups. Each rule group has rules in a specific order. You can set rule groups to stop processing other rule (groups).

As I don't see any stop processing setting when editing a rule group (only an individual rule), I'm wondering what the expected behavior is. If I set a single rule in a group to stop processing will rules in later groups execute? Or if a single rule set to stop processing matches does that halt all further rules, even if they are in a different group (this is what I'm inferring from the documentation)?

**Comment by JC5** [comment]
Yeah it's a bit fuzzy and doesn't work as described yet.

My plan for [a future release](https://github.com/firefly-iii/firefly-iii/projects/5#card-21979078) is to make this behavior more consistent. Probably something along the lines of the following:

* The stop processing checkbox in rules' triggers and actions would disappear.
* The option for a rule itself would stop the lower ordered rules in the same group from firing, if the rule itself was triggered.
* Same for rule groups.

Let's say you have three groups, A, B and C. And a bunch or rules. A1, A2, B1, B2, etc.

If rule A1 is triggered and is set to stop processing, A2, A3 and others will **not** fire. Groups B and C will fire just fine. 

If rule B2 has the same setting but isn't triggered, nothing will happen.

If group B is triggered and it has a stop processing checkbox, groups C, D and others won't fire. A would have fired already so isn't influenced.

Makes sense?

**Comment by Kline-** [comment]
Yes, that makes perfect sense and is the behavior I was hoping for. For now as long as rules in subsequent groups will fire irregardless of a single rule in a higher group being set to stop processing then I should be able to setup what I wanted to. Thank you!

**Comment by JC5** [comment]
Yes, that's an important distinction. You can't stop other rule groups from firing from a rule alone.
