### ISSUE TITLE
Current Balance = $0 for Liabilities with "Start date of debt" prior to current year

### ISSUE THREAD

**Issue by s3w47m88** [firefly-iii/firefly-iii#2286]
**Bug description**
I am running Firefly III version 4.7.15, and my problem is that when you view Liabilities the Current Balance is $0 when the "Start date of debt" is prior to the current year.

I also noticed there is no total on that page. Is that by design or accident?

**Comment by JC5** [comment]
There's no total, no, and that's something I can check out. 

I can't replicate that issue, is that something you can make happen on the demo site as well?
