### ISSUE TITLE
Default category for expense/revenue accounts

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#2287]
**Description**
99% of the time when you use an expense/revenue account you will use the same category. Would it be possible to set a default category for each accounts (different if the same name is in expense and revenue) so when you select the account in the list while typing, it will automatically set its default category?

**Solution**
While typing account name a list is shown where you can select the account (based on text search). When selecting the one you want in the list it would automatically set its default category in the category field.

If you create a new account it will pick the category used to set it as its default one

Bonus part: Would be nice to have multi edit option in the accounts view to set default category to multiple accounts at one.

Thanks! :)

As usual your product is amazing I love it!

**Comment by JC5** [comment]
Thanks for the compliments! 

What you want to do can be done using rules. It won't be visible in the screen but it would work none-the-less.

**Comment by MacPaille** [comment]
Good to know it's possible. But then I will have to create a super lot amount of rules to manage all this :)

And how could it work if I want for whatever reason to change the category of one specific transaction?

**Comment by JC5** [comment]
I'm afraid so. I wouldn't be possible to build in exclusions for standard transactions. What some people do is bookmark a link to the "clone transaction" button for a transaction that matches what they want. Others cobble together something using the API and personal access tokens.

**Comment by MacPaille** [comment]
OK will leave it like that for the moment then. Don't wanna add too much rules.

Thanks anyway. If one day you look for improvements on accounts, please keep this in mind :)
