### ISSUE TITLE
Expense/revenue account list sorting

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#2288]
**Description**
The list of expense/revenue is alphabetically sorted but taking into account the first letter being uppercase or lowercase. Meaning all lowercase accounts are pushed to the last page (depending if you add accounts starting with an uppercase or lowercase).
Would be nice to sort alphabetically without taking into account the case of the text.

**Solution**
Change the sorting mechanism to set all names in lowercase/uppercase before sorting it. I don't know if there is an easy way to do that :)

Thanks!

**Comment by JC5** [comment]
Yes, this is something that will be fixed in the next release. It also messes up non-Latin character sorting.

**Comment by MacPaille** [comment]
Perfect, thanks a lot!!!
