### ISSUE TITLE
Field suggestion with more than 5 values

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#2289]
**Description**
While typing test in some fields (account name, category) Firefly suggest you already existing names in a small list. This list is limited to 5 entries.
Would it be possible to increase that number or have it as a parameter in the options so you can decide which value fits you the best?

I'm used to have a lot of same names for account (e.g. supermakets names) with only the location that differs. But it means I have only the first five in the list and not more.
Same for categories I'm used to have "subcategories" so I use a name like "Category - Subcategory". Which means when I add a new account and I want to add it to some subcategory I don't always know which one to pick as 5 in the list is too small.

**Solution**
Increase the number of suggested entries are showedto 10/15/20 or make it a parameter in the options?

**Comment by JC5** [comment]
It won't be an option, but I can see if I can make it longer. There was a suggestion earlier to do this as well.

**Comment by MacPaille** [comment]
Cool thanks for the quick feedback as usual!
