### ISSUE TITLE
Transfer between accounts in different currencies reporting incorrectly

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2291]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

I have a USD account that transferred 100 USD to my BRL account, totaling 350 BRL.

On the Category report, I chose not to list the USD account, but choose to list my BRL account.

On the `Revenue / income (top 10)` and on the `Average income per account` sections of the report, it shows the 100 USD (with the R$ sign) instead of the 350 BRL.

**Steps to reproduce**
Create a USD account.
Create a BRL account.
Create a transfer between USD account to BRL account.

Generate the Categories Report.

**Expected behavior**
The amount on the report should be the converted one (350) and not the source one (100)

**Comment by JC5** [comment]
There's a good chance that happens, yes. These reports have a hard time distinguishing foreign currency accounts, even when you select just that account. There's not much I can do about it right now unfortunately, but it's on my list.

I'll write it down as a bug so I can deep dive into it. OK?

**Comment by iwalucas** [comment]
sure, thanks!

**Comment by JC5** [comment]
This will be fixed in the next release.
