### ISSUE TITLE
Assets like Vehicles, Equipment, etc...?

### ISSUE THREAD

**Issue by s3w47m88** [firefly-iii/firefly-iii#2292]
Howdy. Man I love this application.

Is there a proper place to add assets like vehicles, valuables, equipment, etc...

**Comment by JC5** [comment]
Thanks! There isn't, sorry about that.

**Comment by s3w47m88** [comment]
Okay thanks. Any objection to my team and I introducing such a place?

**Comment by JC5** [comment]
Not sure what you had in mind exactly?

**Comment by s3w47m88** [comment]
I'm not sure where it should be int he navigation but a menu item called Assets. Then a table with a list of items.

Item                      Value     
1996 Suburban     $5,000
Camera                 $2,000
Laptop                  $3,000


And then these would contribute to my net worth.

**Comment by JC5** [comment]
Ah yeah. No that's not on my list of plans at the moment. I want to focus on financial things right now.

**Comment by s3w47m88** [comment]
Ok we'll build another module for this one then. Thanks man!
