### ISSUE TITLE
Rule did not trigger on new deposit

### ISSUE THREAD

**Issue by Kline-** [firefly-iii/firefly-iii#2293]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

I have a rule to set the description of a transaction when it is created, based on the source account. It shows it should have triggered on the transaction when viewing in the rules menu, but did not trigger when I added the transaction.

The rule in question is 21 and I didn't see it mentioned in the first debug log after adding the transaction. When running the rule manually it properly matched and updated the transaction. Logs attached from when I first added the transaction and when I manually ran the rule.

**Steps to reproduce**
Create a rule matching on source account only.

**Expected behavior**
The rule will properly trigger.

**Extra info**
Debian testing

Debug information generated at 2019-05-29 16:17:15 America/Chicago for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.4-2 |
| Display errors | Off |
| Session start | 2019-05-01 00:00:00 |
| Session end | 2019-05-31 23:59:59 |
| Session first | 2019-05-17 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; CrOS x86_64 11895.118.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.159 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**
[ff3-fpm-fcgi-2019-05-29.log](https://github.com/firefly-iii/firefly-iii/files/3234532/ff3-fpm-fcgi-2019-05-29.log)
[ff3-fpm-fcgi-2019-05-29-manual.log](https://github.com/firefly-iii/firefly-iii/files/3234552/ff3-fpm-fcgi-2019-05-29-manual.log)
![Screenshot 2019-05-29 at 4 15 03 PM](https://user-images.githubusercontent.com/1126350/58592433-0a095100-822e-11e9-872d-e5be00582253.png)

**Comment by JC5** [comment]
Is the rule been set to fire at the creation or at update of a transaction? You can see this when you edit the rule.

**Comment by Kline-** [comment]
It's set for on creation.

**Comment by JC5** [comment]
Alright I can't make much of the logs, rule 21 just isn't mentioned. I doubt there's a weird bug at play here. More people would've noticed. I don't see anything weird in the logs. I got to admit, I'm a bit at a loss as to what's going on.

**Comment by Kline-** [comment]
I tried a few tests today to see if it was maybe opcache causing problems or just something wonky in MariaDB/Nginx/PHP; but no luck.

* Added a deposit with description "test" from source account FSA: rule did not trigger. Deleted the transaction.
* Restarted PHP-FPM, Nginx, and MariaDB.
* Verified the rule was correct and enabled.
* Added a deposit with description "test1" from source account FSA: rule did not trigger. Deleted the transaction.
* Disabled opcache and restarted PHP-FPM.
Added a deposit with description "test2" from source account FSA: rule did not trigger. Deleted the transaction.
* Verified that again there is no mention of rule 21 in the debug logs.

I'm more than happy to run more tests, dump my SQL tables, or whatever else may help figure this out.

**Comment by JC5** [comment]
Alright. I just tried it and I know the source-is/set-description routine works. I got that to trigger. The rule isn't included for some reason. From your screenshots it doesn't seem to be inactive. Neither does the rule group. 

Could you dump rule 21 from the DB for me?

**Comment by Kline-** [comment]
Here you go. Please let me know if there's anything else you'd like to see.
[rule21.zip](https://github.com/firefly-iii/firefly-iii/files/3243648/rule21.zip)

**Comment by JC5** [comment]
Alright, the `stop_processing` value is the only thing that I can imagine could break stuff. Could you make sure it's set to `0` on all rules, actions, triggers etc?

**Comment by Kline-** [comment]
That worked, the only rule with stop processing set anywhere is a deleted one. I tried re-enabling stop processing on the rule that preceding this one and things still worked. So something strange is happening with stop processing, someplace. Log attached from both attempts.
[ff3-fpm-fcgi-2019-06-03.log](https://github.com/firefly-iii/firefly-iii/files/3249705/ff3-fpm-fcgi-2019-06-03.log)

**Comment by JC5** [comment]
Alright. I'm already working on this for the next release. I want to make sure there's just one piece of code running the rules. I'll mark this one down as a bug and I'll keep an eye on it after the release.

**Comment by JC5** [comment]
OK, I've rewritten the rule-engine so for the next release this should no longer popup. I'm marking this one as fixed. If you see this in future releases drop me a line and mention this issue.
