### ISSUE TITLE
docker-compose installation process shortcomings

### ISSUE THREAD

**Issue by DennisVonDerBey** [firefly-iii/firefly-iii#2294]
I am running Firefly III version 4.7.17

**Description**
I ran Firefly in the past, but stopped when the installation broke due to an accidentally performed mysql upgrade... Now I wanted to reinstall and start from the beginning. The way I want to run is via docker-compose with a postgres. The installation docs tell me to edit the docker-compose yml with my installation details, but there are missing parameters. On my way through the GitHub issues I found references to edit the `.env` file. As there is only a `.env.example`, I copied it to create one. I edited all options there and tried running it. Still the options don't seem to apply.

I looked at the `entrypoint.sh` doing all the logic and it seems like there is a disorienting use of variable naming and it looks like it is outdated? Many variables in the `.deploy/docker/.env.docker` file are prefixed with `FF_`, but in the `entrypoint.sh` it is trying to substitute it with the normal non prefixed environment variables:

```
DB_CONNECTION=${FF_DB_CONNECTION}
DB_HOST=${FF_DB_HOST}
DB_PORT=${FF_DB_PORT}
```

They're all ignored. Shouldn't they all live in the .env file and the docker-compose should inject the `.env` file inside the containers? Manually editing the compose file should not be necessary.

Also the docker-compose doesn't set the hostnames fixed, so I have no way to know what to connect to.

I'd love to contribute by clearing this up, but first I would like to know if I am the problem and just don't get the right process :) Thanks for your work on the project!

**Comment by JC5** [comment]
Yeah the current process is pretty crappy. I wrote it when I had very little knowledge of docker. Feel free to add improvements, but make sure to check out the `develop`-branch where some changes have already been applied. I've already been cleaning up some of the inconsistent environment variables.

You're more than welcome to clear this up, and I'd love to hear about the standard process for these things. I'm not really sure what the best practice is for configurable environment variables. A `.env` file next to `docker-compose.yml`? I don't mind either way of course, and I'm open to feedback and improvement.

As long as you play around in the `develop`-branch go wild. Once I merge changes, the automated docker build should pick it up. You can follow the progress [here](https://travis-ci.com/firefly-iii/firefly-iii).

**Comment by michelvosje** [comment]
Ah well that explains it all for me haha. I also had troubles starting up the firefly-ii app using `docker-compose`. Now u just ran the `docker run` commands manually and i got it working!
