### ISSUE TITLE
Dockerfile.arm fails building image

### ISSUE THREAD

**Issue by kenimou** [firefly-iii/firefly-iii#2295]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

I got the following error while building the image:
```
Sending build context to Docker daemon  110.8MB
Step 1/15 : FROM arm32v7/php:7.2.8-apache-stretch
 ---> 34639123a7ec
Step 2/15 : ARG ARCH
 ---> Running in b0cd329b4588
 ---> fab8271bdbde
Step 3/15 : COPY temp/qemu-arm-static /usr/bin/qemu-arm-static
COPY failed: stat /var/lib/docker/tmp/docker-builder313672251/temp/qemu-arm-static: no such file or directory
```

**Steps to reproduce**

`docker build -f Dockerfile.arm .`

**Expected behavior**
Successfully build the image. 

**Extra info**
Hardware: Raspberry Pi B+
OS: Raspberian 

**Bonus points**

**Comment by JC5** [comment]
I’m pretty sure it won’t build on the 32 bit chip of the B+. I haven’t got one and no possibilities to experiment online (Travis doesn’t offer 33 bit ARM). 

If you get it working I would love to see a PR though!
