### ISSUE TITLE
CSV file import broken due to dash in amount field

### ISSUE THREAD

**Issue by JamborJan** [firefly-iii/firefly-iii#2296]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

I have been using [this import configuration](https://github.com/firefly-iii/import-configurations/blob/master/ch/creditsuisse/default.json) for a long time and it worked. Now my bank changed the CSV format and instead of leaving the field for credit / debit empty when it is one and not the other, they put a dash (`-`) in the column and this seem to screw up the importer.

**Steps to reproduce**
Use a csv import file like the following and  [this import configuration](https://github.com/firefly-iii/import-configurations/blob/master/ch/creditsuisse/default.json) and after importing this you should see that a broken transactions will be created like shown in the screenshot below. The debit record set is shown twice and with amount zero. The credit record set is just fine.

```
Buchungsdatum,Text,Belastung,Gutschrift,Saldo
27.05.2019,"Dummy Buchung 1",-,500.00,2000.00
24.05.2019,"Dummy Buchung 2",500.00,-,-
```

![Bildschirmfoto 2019-06-01 um 21 39 47](https://user-images.githubusercontent.com/7508960/58752857-2cad9b00-84b6-11e9-9e84-97845b077933.png)

**Expected behavior**
The column containing the dash (`-`) should be recognized as empty.

**Extra info**
```
Debug information generated at 2019-06-01 19:35:54 UTC for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2019-04-01 00:00:00 |
| Session end | 2019-06-09 00:00:00 |
| Session first | 2017-02-21 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |
```

**Bonus points**
I hope all criteria are met incl. the human :-D

**Comment by JC5** [comment]
I saw you posted a PR to fix this. That's the correct solution, thanks :)

**Comment by JamborJan** [comment]
[My PR](https://github.com/firefly-iii/import-configurations/pull/29#event-2385253057) should only solve the column issue (the bank removed one).

To successfully import the file I have to replace the dashes with empty string before import. That’s actually the test result I get.

So from my point of view something is still missing here or behaving different between debit and credit record sets.

**Comment by JC5** [comment]
I see what you mean. There's not much i can do about that I'm afraid. They're delivering invalid CSV files.

**Comment by JamborJan** [comment]
Any chance to handle this in any way? Not sure how your new concept for the importer plugin could handle this. I would also be willing to code something to make it work.

**Comment by JC5** [comment]
Sorry, not at the moment.

**Comment by JamborJan** [comment]
Okay thanks, just this week the bank removed this stupid dash again and the import is working perfectly with the changed I did for the import config. Thanks for your support ans sorry that I bothered with that :-D

**Comment by JC5** [comment]
Typical banks :D 

Glad to hear its fixed.
