### ISSUE TITLE
locale doesn't exist on Alpine linux due to musl (decimal format issue)

### ISSUE THREAD

**Issue by alexmat** [firefly-iii/firefly-iii#2298]
Any thoughts on how to fix the decimal not showing issue when running on Alpine linux? Everything else works well, but there is no way to set a specific locale for musl which has replaced glibc. Is there any workaround for this at a higher level in the stack?

For reference: https://wiki.musl-libc.org/functional-differences-from-glibc.html#Character_sets_and_locale

**Comment by JC5** [comment]
Sorry I have no idea. I just lean on PHP to set the locale for me.

**Comment by DakuTree** [comment]
Ran into this issue myself when trying to setup Firefly under Alpine. 

There is various methods to install locales on Alpine (see https://github.com/gliderlabs/docker-alpine/issues/144), although none of them appear to work with PHP.

Some examples:
```bash
# Install locales via available methods in link above
> locale -a
C
C.UTF-8
de_DE.UTF-8
ch_DE.UTF-8
de_CH.UTF-8
en_GB.UTF-8
fr_FR.UTF-8
en_US.UTF-8
ru_RU.UTF-8
> LANG=en_GB.UTF-8 date
Fri Sep 27 14:23:45 BST 2019
> LANG=ru_RU.UTF-8 date
Пт Сеп 27 14:23:51 BST 2019
# setlocale can see and open the locale file correctly (as seen via strace), however it doesn't load the data
> php -r 'setlocale(LC_MONETARY, "en_GB.UTF-8"); var_dump(localeconv()["mon_decimal_point"]);'
string(0) ""
> php -r 'setlocale(LC_MONETARY, "ru_RU.UTF-8"); var_dump(localeconv()["mon_decimal_point"]);'
string(0) ""

# setlocale fails to load the file as it doesn't exist, but still returns as if it does
> php -r 'var_dump(setlocale(LC_MONETARY, "ThisIsNotValid.UTF-8"));'
string(20) "ThisIsNotValid.UTF-8"
```

Considering the intl extension is already required, wouldn't it be better to use that to handle locales (via `NumberFormatter`) so it's not reliant on what is actually installed on the system?
Either that or just fallback to a local version of the `localeconv()` response if it's empty. 

Also the self-install page should really mention that locales are needed, not hidden in the FAQ. Spent a good while trying thinking that the import config/data was causing this.

**Comment by Herve-M** [comment]
@DakuTree Did you find any solution to make it work under Alpine?

**Comment by DakuTree** [comment]
@Herve-M Sadly not. Tried all the various ways to get locales working, and although they worked with Alpine, PHP would just refuse to acknowledge them.
