### ISSUE TITLE
Problem during install with cipher chain

### ISSUE THREAD

**Issue by Gabbalo** [firefly-iii/firefly-iii#2299]
**Bug description**
I am installing Firefly III version 4.1.17, and i get an error about incompatible ciphers when using the php artisan commands. I am not sure, if this is a bug in Firefly III or a bug anyways. 

**Steps to reproduce**
When issuing the command 
`php artisan migrate:refresh --seed`
I get the error message 
`In ServiceProvider.php line 236:`

`Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.'`

**Expected behavior**
No errormessage 

**Extra info**
Installing on a CentOS 7 environment, php 7.2 via ssh.

**Bonus points**
Unfortunately, there are no further log-entries or such as the installation is incomplete, so no bonus points for me.
I hope, you will help me with this problem nevertheless. 
Anyone an idea how to fix this?

**Comment by JC5** [comment]
Did you create a `.env` file with a valid `APP_KEY`? This is done automatically when you run the `create-project` command from the manual.

**Comment by Gabbalo** [comment]
Your completly right, it WAS an improper APP_KEY. 
After renewing it (by starting the whole procedure over, because the php artisan command to renew the key was not working as well) every command just works fine.

Thank you for your fast response!
