### ISSUE TITLE
[Question] Is Firefly III Free Software?

### ISSUE THREAD

**Issue by asddsaz** [firefly-iii/firefly-iii#2300]
**Question**: Is Firefly III fully free software?
Is all the source code here? Is it all [free'ly licensed](https://www.wikipedia.org/wiki/Free_software_license)?

**Comment by emansih** [comment]
The source is all here(GPL v3). From what I can tell the library used are all FOSS.

**Comment by JC5** [comment]
Yep. It's all open source.
