### ISSUE TITLE
Mail from address is mail_username not mail_from

### ISSUE THREAD

**Issue by Tripwyr** [firefly-iii/firefly-iii#2304]
I am running Firefly III version 4.7.17

**Description**
When email is received, it shows as coming from MAIL_USERNAME instead of MAIL_FROM. I am relaying through gmail (g suite specifically) with the smtp driver.

**Extra info**
Mail env:
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_FROM=firefly@mydomain.com
      - MAIL_USERNAME=myname@mydomain.com
      - MAIL_PASSWORD=myapppassword
      - MAIL_ENCRYPTION=tls

Debug:
Debug information generated at 2019-06-08 10:11:59 America/Toronto for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2019-06-01 00:00:00 |
| Session end | 2019-06-30 23:59:59 |
| Session first | 2019-06-08 07:32:26 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

Screenshot:
![image](https://user-images.githubusercontent.com/16571812/59148418-d02b0e00-89d6-11e9-8aca-5f6563ac5a9c.png)

**Comment by JC5** [comment]
I see what you mean. As far as I can tell Firefly III is configured correctly (there is a [global from address](https://laravel.com/docs/5.8/mail#configuring-the-sender).

I'll mark it down as a bug. Might be a bug in Laravel though.

**Comment by JC5** [comment]
This is not a bug, but a thing that GMail does. If you look at the source of the message, you will see this:

```
X-Google-Original-From: Firefly III Mailer <SOME_OTHER_ADDRESS@firefly-iii.invalid>
```

Where the address will be the original one.

**Comment by Tripwyr** [comment]
This is not an issue I've had with any other service. For example, here is an email from Ombi, authenticated and sent through gmail the same way:

![image](https://user-images.githubusercontent.com/16571812/62320959-8d823100-b46f-11e9-9133-514e7b1fda71.png)

I wish I had the knowledge to dig into this further, but if this issue isn't fixable then I won't push it, firefly functions just fine without it.

**Comment by JC5** [comment]
I have no wiggle room to change the underlying libraries, unfortunately.
