### ISSUE TITLE
Ratesapi.io endpoint is wrong

### ISSUE THREAD

**Issue by zeridon** [firefly-iii/firefly-iii#2307]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is: Exchange rates are not retrieved from ratesapi.io.
Current endpoint: `https://ratesapi.io/api/%s?base=%s&symbols=%s`
Correct endpoint: `https://api.ratesapi.io/api/%s?base=%s&symbols=%s`

**Steps to reproduce**
Add transaction in different currency and check the logs.

**Expected behavior**
exchange rates are automatically pulled and updated where needed.

**Extra info**

Debug information generated at 2019-06-11 13:55:38 Europe/Sofia for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | memcached |
| App logging | , daily |
| PHP version | 7.3.6-1+0\~20190531112735.39+stretch\~1.gbp6131b7 |
| Display errors | Off |
| Session start | 2019-06-01 00:00:00 |
| Session end | 2019-06-30 23:59:59 |
| Session first | 2019-04-21 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, msgpack, mysqli, pdo_mysql, pdo_sqlite, apc, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache |

**Bonus points**
Stacktrace:
```[2019-05-24 12:07:21] local.ERROR: Something went wrong. Received error code 500 and body "Guzzle exception: Client error: `GET https://ratesapi.io/api/2019-05-24?base=EUR&symbols=BGN` resulted in a `404 Not Found` response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found (truncated...)
" from RatesApiIO.
```

<!-- Earn bonus points by:

- Post a stacktrace from your log files
- Add a screenshot
- Remember the human
-->

**Comment by emansih** [comment]
it was fixed in the develop branch a few days back. https://github.com/firefly-iii/firefly-iii/commit/73e32efd79cfee44ca71243c79cd9d17d6b91a1f

**Comment by zeridon** [comment]
Thanks. Then it can be closed

**Comment by JC5** [comment]
:+1:

**Comment by Bravesun** [comment]
I have this issue too, glad to know it's been fixed. Just need to wait for the next update I guess.

**Comment by emansih** [comment]
Just change the endpoint url. no need to wait for next update
