### ISSUE TITLE
Graphs not loading when using Cloudflare

### ISSUE THREAD

**Issue by athphane** [firefly-iii/firefly-iii#2308]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

I am using Cloudflare
After upgrading to 4.7.17, none of the graphs are loading and Chrome says 

```
Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' ". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
**Steps to reproduce**
Run firefly-iii behind cloudflare

**Expected behavior**
None of the graphs work

**Extra info**
Using Chrome on Windows.

Firefly debug

Debug information generated at 2019-06-12 18:11:46 Indian/Maldives for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.16-1+ubuntu16.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-06-01 00:00:00 |
| Session end | 2019-06-30 23:59:59 |
| Session first | 2018-05-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache |

**Comment by JC5** [comment]
The rocket-loader script is not part of Firefly III. Not sure who's injecting code into your instance. 

There was an issue about it earlier but the guy never came back on it: 


https://github.com/firefly-iii/firefly-iii/issues/2198

**Comment by athphane** [comment]
Apparently rocket-loader is run by cloudflare so the page JavaScript waits until all of the HTML loads. I would like to point out that I used to run the version that was before the Laravel 5.8 upgrade and that it worked all fine. Just updated to the latest version a couple of days ago. 

You have the script src line on your SecureHeaders middleware. Is there any possible fix for this? On the other issue the guy said that turning off cloudflare worked for him. I'd like for cloudflare to still be working.

**Comment by JC5** [comment]
The Laravel upgrade was ages ago. Not really sure when that was, to be honest. 

And I’m sorry, but I’m not going to drop security so that Cloudflare can inject random JavaScript into the source code of Firefly III. You can edit the middleware by hand if you want to though but on your own risk.
