### ISSUE TITLE
zh-cn sometimes work error

### ISSUE THREAD

**Issue by kongtir** [firefly-iii/firefly-iii#2310]
zh-cn sometimes work error
i install thsi in server  (CentOS7 x64,php 7.2.19),then select Chinese Simplified(Chinese Simplified)
but this data is 2019年 һ�� 1日 - 2019年 ���� 1日
yes ,some word is not correct
so,i install in my   wondows 10  Docker (CentOs  x64,php 7.2) ,this date is 
2019年 January  1日 - 2019年 July  1日

what much info i need offer?
 What could have happened?

**Comment by JC5** [comment]
It happens when your system also has non-UTF8 locales available. You can make this behavior change.

Find the following file and line: https://github.com/firefly-iii/firefly-iii/blob/master/resources/lang/zh_CN/config.php#L27

Change the content to:

```
    'locale'                => 'zh_CN.utf8,zh_CN.UTF-8',
```

I have submitted a fix for the next release.

**Comment by kongtir** [comment]
Thanks,It's Well

**Comment by kongtir** [comment]
it maybe use '%m 月' replace '%B'  ,i do it latter.

**Comment by JC5** [comment]
You can submit your suggestions here:

https://crowdin.com/translate/firefly-iii/141/en-zhcn
