### ISSUE TITLE
Budgets not detecting related Transactions

### ISSUE THREAD

**Issue by s3w47m88** [firefly-iii/firefly-iii#2311]
I am running Firefly III version 4.7.15

**Description**
I have Budgets. And some of them show Transactions that are related to that. While others do not. I understand this is because it's not seeing an association. So I looked Rules to try and link them but there doesn't appear to be an option to link them.

I also looked at the actual Budget edit view and there is no option to list relation transactions or define Rules.

I also went back to Rules and choose "Set Budget..." and copied and pasted my Budget name. Then ran the rule. But still no luck.

I'm not sure what I'm missing?

**Comment by JC5** [comment]
Are these transactions expenses? Otherwise they can't be linked.

If you create a transaction you can also set the budget of course.

**Comment by s3w47m88** [comment]
Yep. They're regular expense transactions going out of my account.

**Comment by JC5** [comment]
And you set the budget using the Budget dropdown?

**Comment by s3w47m88** [comment]
Does that apply to all instances of that transaction like a rule? I have
done it on some but it seems to not apply to past and future automatically
like a rule.

**Comment by JC5** [comment]
Can you answer the question please?

**Comment by s3w47m88** [comment]
Sorry. I want clear. I did not set it on this transaction. I have set it on
others though and found it does not update all versions of that transaction
to that budget.

**Comment by JC5** [comment]
Firefly III will not automatically change all transactions to match the setting of a single transaction.

You can use a rule to do this, but you must make sure that the triggers of the rule match the transactions you wish to be given the budget. You can read more about that in [the documentation](http://docs.firefly-iii.org/en/latest/advanced/rules.html).

**Comment by s3w47m88** [comment]
That's what I thought. But I'm saying that when creating a Rule there is no
option to assign something to a Budget.

**Comment by JC5** [comment]
Yes there is.

**Comment by s3w47m88** [comment]
Maybe I'm looking in the wrong spot. But here is a video showing the options I have. Notice there is no option to associate a Transaction with a Budget: https://www.loom.com/share/04bcfab6446046cf9730445480e26e90

**Comment by JC5** [comment]
"Set budget to.." is what you want.
