### ISSUE TITLE
Investment, bonds, stock assets

### ISSUE THREAD

**Issue by evertondanilo** [firefly-iii/firefly-iii#2313]
I'm comparing features that I've been using in Acemoney, and a missing feature that I would like to see here is:

__Investment, bonds, stock assets__

In acemoney I use this tab more for bonds, but I would treat everything like a bond. What I need is from time to time update the quote and see how much capital I have overall.

for e.g.

- User go to investment tab
- User select an origin account (I select my broker investment account in acemoney)
- User click buy asset
- User insert Symbol or select from an existing one.
- User input qty, price, commission, etc

- This entry will be deducted from my selected account as a normal transaction..
- A special view show my asset with price, qty, gain, and total
- User can right click on asset and update the last price value.

**Add or sell asset:**
![image](https://user-images.githubusercontent.com/1122784/59639575-8f0fc800-9153-11e9-809a-47bda475c907.png)

**Special view:**
![image](https://user-images.githubusercontent.com/1122784/59639680-dbf39e80-9153-11e9-981c-2667c434a4ee.png)

**Normal transaction in Investment type account:**
![image](https://user-images.githubusercontent.com/1122784/59639766-0d6c6a00-9154-11e9-810f-2d23ea180a18.png)

**Comment by JC5** [comment]
I’m sorry but Firefly III will only focus on personal finances.

**Comment by evertondanilo** [comment]
I see, probably there is no too much people saving/investment in this way.
I use this feature as part of my personal finances anyway.

**Comment by JC5** [comment]
It’s also about giving the tool focus. I don’t want to change it into another GNUCash.

**Comment by netpanda** [comment]
It is undestandable what you are saying about simplicity. But most of users have some kind of investment that add value to their networth. Adding personal Investments are an important part of personal finance.

**Comment by Kail0** [comment]
https://firefly-iii.readthedocs.io/en/latest/support/features.html

![image](https://user-images.githubusercontent.com/2068046/59952449-7ae20880-947c-11e9-8dc9-e0b79fe9e927.png)
