### ISSUE TITLE
Rule did not trigger on new Transfer

### ISSUE THREAD

**Issue by JbalTero** [firefly-iii/firefly-iii#2314]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

Rule did not trigger on new Transfer to a Liability transaction.

**Steps to reproduce**
- Create new Account

![NewAccount](https://user-images.githubusercontent.com/3615746/59642858-3d8a2c00-9199-11e9-80f7-a7abb4635c60.png)

- Create new Bill

![New Bill](https://user-images.githubusercontent.com/3615746/59642957-95c12e00-9199-11e9-95d0-b3ea418afdf4.png)

- For the Rule inputs(everything is default except below)

![Edit Rule](https://user-images.githubusercontent.com/3615746/59642971-a70a3a80-9199-11e9-9666-ca87bab6fb54.png)

- Create Liability

![NewLia](https://user-images.githubusercontent.com/3615746/59642985-af627580-9199-11e9-9db2-1e1b9166681e.png)

- Create a Transfer transaction for paying the Liability that will link to a Bill

![PaymentToLiaTrans](https://user-images.githubusercontent.com/3615746/59642994-b8ebdd80-9199-11e9-9415-700fc295c5c0.png)

- Go to Transaction overview, there's no Bill

![TransfOverview](https://user-images.githubusercontent.com/3615746/59643003-c0ab8200-9199-11e9-9c07-269645ff15a1.png)

- Go to Bills overview, it says, Not (yet)

![BillsOverview](https://user-images.githubusercontent.com/3615746/59643015-c7d29000-9199-11e9-87ba-47507b79613d.png)

- Go to Rule for bill "MyBill" & Click See matching transactions

![MatchingTrans](https://user-images.githubusercontent.com/3615746/59643022-d0c36180-9199-11e9-8696-e6fbfcef2da7.png)

**Expected behavior**
* In the Bills overview, it should'nt say "Not (yet)" instead display the June 18, 2019 transaction.

* In the Transaction overview, there should be a "Bill"

**Extra info**
Debug information generated at 2019-06-18 06:50:39 Asia/Manila for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.18 |
| Display errors | Off |
| Session start | 2019-06-01 00:00:00 |
| Session end | 2019-06-30 23:59:59 |
| Session first | 2018-07-18 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | litespeed |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, litespeed, bcmath, dom, fileinfo, gd, imagick, imap, intl, Phar, json, exif, mysqlnd, mysqli, PDO, pdo_mysql, pdo_sqlite, posix, soap, sockets, tidy, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, phalcon, ldap, ionCube Loader, Zend OPcache |

**Comment by JC5** [comment]
I'll mark it as a bug and do some digging, thanks for reporting.

**Comment by JC5** [comment]
This is confusing, but it's behaving as it's supposed. Bills can't be linked to transfers, so even though it will trigger correctly the link will never be made.

In the next release of Firefly III, the type of transaction you're making here would not be a transfer but a withdrawal and as such, could be linked to a bill.

I'm marking this as solved. Once the new release drops, test it and get back to me. Refer back to this issue.
