### ISSUE TITLE
Is it possible to add the current value of my crypto currency to my net worth?

### ISSUE THREAD

**Issue by calgara12** [firefly-iii/firefly-iii#2315]
I am running Firefly III version 4.7.17

Title.

**Comment by JC5** [comment]
You mean, in euros? Then no.

**Comment by WantedFreak** [comment]
> 
> 
> You mean, in euros? Then no.

Why?
I would love to see it all in one currency instead of multiple currencies that I have to look up and calculate myself. Maybe add a option to enable or disable this.
