### ISSUE TITLE
Cron not running correctly

### ISSUE THREAD

**Issue by jeremyy294** [firefly-iii/firefly-iii#2316]
Hi there, I'm just wondering if anyone can help me diagnose the following error when I attempt to run the cron job.

I am running Firefly III version 4.7.17

PHP Notice:  Undefined index: argv in /home/firefly/public_html/vendor/symfony/console/Input/ArgvInput.php on line 53
PHP Warning:  array_shift() expects parameter 1 to be array, null given in /home/firefly/public_html/vendor/symfony/console/Input/ArgvInput.php on line 57

In ArgvInput.php line 261:
                                           
  Invalid argument supplied for foreach()  
                                           
Any advice much appreciated.

**Comment by JC5** [comment]
What's the command exact you're trying to run?

**Comment by jeremyy294** [comment]
Command is /opt/rh/rh-php72/root/usr/bin/php /home/firefly/public_html/artisan firefly:cron
