### ISSUE TITLE
Best way to join the data of two firefly users into a single user

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#2317]
I am running Firefly III version 4.7.17

**Description**
I have separated the management of my own money and our household money using two firefly users. This starts to annoy me because constantly switching users is quiet cumbersome (especially with 2FA). So I'm thinking about joining the data back into a single firefly user. Is this even feasible? I guess this needs to be done on database level? Can you give me any hints on how to approach this?

**Comment by JC5** [comment]
You'll have to do it on a DB level. You can simply update all user_id's to the user you wish to merge into.

To remove duplicates:

- Sort the following tables by name/title: accounts, budgets, categories, piggies, rules, recurring transactions. There might be others, I'm doing this from the top of my head.
- Rename each double entry to "x" and "x2" so you can see the difference.
- Use either the FF3 interface or a query to update journal meta data.
