### ISSUE TITLE
Firefly 3 trying to use HTTP with Reverse Proxy

### ISSUE THREAD

**Issue by jodfie** [firefly-iii/firefly-iii#2319]
I am running Firefly III version 4.7.17 in a docker container (jc5x/firefly-iii).

**Description**
Firefly 3 log in form keeps trying to use HTTP with Reverse Proxy and it won't allow login due to Content Security Policy.
I've done the following steps:
- Currently using jc21/nginx-proxy-manager and have the `TRUSTED_PROXIES=**` and APP_URL environment variables set which is supposed to work based on #1739
- Manually set the reverse proxy to the configuration in #2109

**Extra info**
OS: Ubuntu 18.04.2 LTS
Docker: 18.09.6
Browser Firefox, Safari, Chrome, and Opera

Debug information generated at 2019-06-23 19:32:42 America/New_York for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2019-06-17 00:00:00 |
| Session end | 2019-06-23 23:59:59 |
| Session first | 2017-01-17 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Bonus points**
![image](https://user-images.githubusercontent.com/151479/59983601-9b7e9f80-95ef-11e9-8c1d-261282a44c46.png)

**Comment by JC5** [comment]
Mmmm sorry, those are the tricks I would have recommended as well.

**Comment by iwalucas** [comment]
I used these on firefly docker:

      - USE_PROXIES=127.0.0.1
      - TRUSTED_PROXIES=**

The USE_PROXIES did the trick

**Comment by Deathhorn** [comment]
Had the same problem; 
as  @iwalucas commented, i only used
```
  - USE_PROXIES=127.0.0.1
  - TRUSTED_PROXIES=**
```
and **didn't** set APP_URL or APP_FORCE_URL
and set
```
RequestHeader set X-Forwarded-Proto "https"
ProxyPreserveHost On
```

now I get the login formular served with "https://myappurl"

Hope it helps anyone (@jodfie ) having this problem.
