### ISSUE TITLE
Bills to pay feature: Not calculating correct amount

### ISSUE THREAD

**Issue by natoleet** [firefly-iii/firefly-iii#2320]
![Billstopaytile](https://user-images.githubusercontent.com/15341205/60235184-375b2480-98ea-11e9-9401-7408d75523e6.PNG)
![BillstopaytileProposed](https://user-images.githubusercontent.com/15341205/60235185-375b2480-98ea-11e9-9269-7732ff3210ae.png)
![RecurringBill](https://user-images.githubusercontent.com/15341205/60235186-375b2480-98ea-11e9-8326-d1936113c35e.PNG)
![RecurringBillProposed](https://user-images.githubusercontent.com/15341205/60235187-37f3bb00-98ea-11e9-9d4e-b46986ce2bb8.png)

**Bug description**
I am running Firefly III version 4.7.17 and my problem is:
When creating a weekly recurring bill, and previous amounts have been paid throughout the period the bill is calculated as if it has been paid in full. 
Example;
Current date is 26/06/2019
Rent = $330 per week.
Item should have 4 amounts that are required to be paid for this period.
Bill has listed 3 payments made for this period, I would expect the 4th installment to list as 'not yet' to indicate that it hasn't been paid yet. Instead, the bill is listed as paid in full.

**Steps to reproduce**
Create a bill that repeats weekly.
Pay a single weeks worth.
Bill is listed as being paid for the complete period, even though 1 or more payments remain for the period.

**Expected behavior**
List remaining payments as 'not yet' similar to how a single bill that hasn't been paid.

Will add screenshots when I get home from work with the issue and photoshop the expected behaviour.

**Comment by JC5** [comment]
Thanks for letting me know, I'll mark it down as a bug and see if I can fix it for the next release.

**Comment by JC5** [comment]
This depends a bit on when the bill starts exactly. What's the start date for this particular bill?

Depending on circumstances the weeks do not overlap with the start of the month, making the period from 31 may until the 6th of June a week, which makes it fall into the previous month.

I suspect that if you jiggle the original start date of the bill around a bit it should fall into place.

**Comment by natoleet** [comment]
Sorry for the late reply, i'll play around with it tonight and post the results.
