### ISSUE TITLE
FinTS import does not work with comdirect accounts

### ISSUE THREAD

**Issue by rbu** [firefly-iii/firefly-iii#2321]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:
Attempting an import on the main account (Girokonto), it fails with the error:
> Warning! Cannot find account with number "XXXXXXX00"

**Steps to reproduce**
1. Login to Firefly III
2. Click Import and export
3. Click Import transactions
4. Click Import with FinTS
5. Fill in FinTS API URL as https://fints.comdirect.de/fints
6. Fill in Bank code as 20041133
7. Fill in Username with comdirect login name (not bank account number)
8. Fill in PIN
9. Click Submit
10. The result shows THREE accounts, two of which have an empty name (Giro and VISA) and one has an account number (Tagesgeld)
11. Select first empty entry (Giro, according to web inspector)

**Expected behavior**
An import runs successfully.

**Extra info**
Not relevant, I hope.

**Bonus points**
I've traced down the problem to app/Support/FinTS/FinTS.php:
```
        if (1 !== count($filteredAccounts)) {
            throw new FireflyException(sprintf('Cannot find account with number "%s"', $accountNumber));
        }
```

The problem is that two accounts match, as I can reproduce with https://github.com/mschindler83/fints-hbci-php/blob/master/Samples/statement_of_account.php . Adding the following code
```
foreach ($fints->getSEPAAccounts() as $account) {
    echo $account->getAccountNumber() . "\n";
}
```
prints:
> XXXXXXX00
> XXXXXXX05
> XXXXXXX00
> XXXXXXXXXXXXXXXX

where "00" is the Giro account mentioned above. Note that the "Transactions" example list from the script works for $accounts[0] as well as $accounts[2].

**Extra Bug**
When listing an account that has no name, but just a number, it would be helpful if Firefly displayed the number (option value) in the option name as a fallback instead of an empty string.

**Comment by JC5** [comment]
I'll check it out, thanks.

**Comment by JC5** [comment]
https://www.patreon.com/posts/30012174

**Comment by MoritzFago** [comment]
Import fails with
```
Warning! An error occurred while trying to connecting to your bank. Please make sure that all the data you entered is correct. Original error message: Request Failed: Die Nachricht enthaelt Fehler. (9050); Dialog abgebrochen (9800); PIN ungültig. (9942); Ungueltige Auftragsnachricht? ( Ungueltige Signatur.) (9340)
```
Because there is no way to enter the mobileTAN.
