### ISSUE TITLE
FinTS product registration

### ISSUE THREAD

**Issue by marcelbrueckner** [firefly-iii/firefly-iii#2322]
According to the [German credit business](https://www.hbci-zka.de/register/register_faq.htm) every product offering FinTS has to be registered for future use of a credit institute's FinTS interface (beginning 1st August 2019, in order to fulfill requirements of upcoming [PSD2](https://en.wikipedia.org/wiki/Payment_Services_Directive), see German credit business' FAQ entries 1 and 2).

Firefly III offers transaction import via FinTS using the [fints-hbci-php](https://github.com/mschindler83/fints-hbci-php) library. While the library is still working fine, it seems - looking at the repository's activity - to be unmaintained.

I wonder if Firefly III should then be registered as such an application?

**Comment by JC5** [comment]
Every single instance would have to be registered. 

> Es ist davon auszugehen, dass diese Aktivitäten in Zusammenhang mit der Einführung der starken Kundenauthentifizierung gemäß PSD2 zu sehen sind, wofür ohnehin neue Produktversionen eingesetzt werden müssen, die dann eine geeignete FinTS-Registrierungsnummer verwenden sollen.

I can't ship this number with Firefly III. I can only leave room to set it.

But these guys also mention:

> FinTS-Bibliothek oder -Kernel
> In die Client- oder Server-Applikation integrierte und gekapselte FinTS-Funktion, die als Kommunikationspartner für die FinTS-Instanz auf Institutsseite dient.

> Zwar werden auch FinTS-Bibliotheken und -Kernels registriert, diese Registrierungsnummern sollten jedoch im praktischen Betrieb nicht verwendet werden.

I can't ship a number without making it public. The library isn't mine so I can't register it. It is however an idea to clone it and repurpose it for the direction Firefly III is going for imports. See below for more info.

I'll drop a request with these guys what the best course of action is. I expect I'll fork the repos, register it and that should be the end of it.

When it comes to importing into Firefly III, this feature is going to be dropped. Instead, separate applications will take over this task, using the API to do so. This saves me a lot of development burden and will allow other people to build importers as well.

**Comment by marcelbrueckner** [comment]
Thank you for taking care. I had a look on all forks of [fints-hbci-php](https://github.com/mschindler83/fints-hbci-php) here on GitHub and some of them actually added some features.

One fork that looks interesting regarding this issue is this one from fbett. It enables the dynamic setting of the product name and version.

> It should be possible to set HKVVB::productName & HKVVB::productVersion while the application is running. Especially when the project is used as a library and not a standalone service, it's needed to register multiple products at "Deutsche Kreditwirtschaft".
https://github.com/fbett/fints-hbci-php/commit/83ffeaff423e6342c851fe868a1a63bf91e8e3b9

Another fork also already took care of the registration topic (and a lot of other things, see further below)
> https://github.com/nemiah/phpFinTS/commit/d21de9ef96809423382764629bea9ca7383bbdc5
https://github.com/nemiah/phpFinTS/commit/f7dfc0e3449f7f4dae2f4c01e2a5dda2051c5a68

And if you plan to take over the library, why not incorporate all other improvements (where appropriate)? Some are interesting. Some probably aren't of much interest for Firefly III as Firefly III doesn't necessarily need to do anything else than reading transaction history? But I will list them all here for the sake of completeness:

> Minor formatting related fixes (and initial implementation of SEPA transfers)
https://github.com/JanFoerste/php-fints/commits/master

> Several fixes and business transaction code handling implementation
https://github.com/roben/fints-hbci-php/commits/master

> Standing orders (could be matched to recurring invoices?), encoding issues, business transaction code, ...
https://github.com/nemiah/phpFinTS/commits/master

> Credit/Debit cancellation
https://github.com/fjogeleit/fints-hbci-php/commits/master
https://github.com/gardenofconcepts/fints-hbci-php/commit/466d79ae994f417b5d2d4c3cdf57cb5ed8d81f1e

> Split description into SEPA reference types
https://github.com/SebastianLeuters/fints-hbci-php/commit/2d972586e02a9231dfc580626f4cbdf07ab68324
and some minor bugfixes
https://github.com/SebastianLeuters/fints-hbci-php/commits/master

> Update MT940.php - I have no clue :D
https://github.com/SudoGetBeer/fints-hbci-php/commit/cd0e8837eb7f2abf9b0f3330ac471ea61777b9d0

**Comment by JC5** [comment]
Don’t get overexcited though. I have nothing to test or run FinTS with and zero interest or time to maintain more OSS. 

I can’t verify anything in this library. At best I can consolidate and let you guys be my guinea pigs but it would never taken prio over Firefly III. 

I’ll get in touch with the German PSD2 guys but I expect they haven’t really thought about this anyway.

**Comment by marcelbrueckner** [comment]
> When it comes to importing into Firefly III, this feature is going to be dropped. Instead, separate applications will take over this task, using the API to do so. This saves me a lot of development burden and will allow other people to build importers as well.

That's fine for me as well. I think one could also use [AqBanking](https://github.com/aqbanking/aqbanking) for getting the transaction history and push the information to Firefly III via it's API.

**Comment by marcelbrueckner** [comment]
Any response from the PSD2 guys on that?

**Comment by JC5** [comment]
Thanks for the reminder. I haven't had the time yet.

**Comment by JC5** [comment]
I've submitted a registration, let's see what happens.

**Comment by JC5** [comment]
I have a code. I guess I have to make it part of the library? It's on the roadmap.

**Comment by marcelbrueckner** [comment]
Thank you. I guess it depends on how you plan to implement it.

>   In die Client- oder Server-Applikation integrierte und gekapselte FinTS-Funktion, die als Kommunikationspartner für die FinTS-Instanz auf Institutsseite dient.

If the FinTS function is tightly integrated with Firefly III and not meant to be reused by other software, it should be fine.

> Zwar werden auch FinTS-Bibliotheken und -Kernels registriert, diese Registrierungsnummern sollten jedoch im praktischen Betrieb nicht verwendet werden.

The German credit business expects the customer-facing application to use it's own registration code. If it's planned to use the fints-hbci-php library further as separate library, the library should accept a custom registration code to send with the requests.

**Comment by oyren** [comment]
Is there any news on this subject?
