### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2323]
Hi,

Would it be possible to change the search to a case insensitive search?

Thanks.

**Comment by JC5** [comment]
It should be. Can you share examples?

**Comment by jlauwers** [comment]
![2019-06-28_11h05_37](https://user-images.githubusercontent.com/1318140/60331382-d9cfe200-9994-11e9-9908-8ccd99920916.png)

Debug information generated at 2019-06-28 11:07:15 Europe/Brussels for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.17 |
| Display errors | Off |
| Session start | 2019-06-01 00:00:00 |
| Session end | 2019-06-30 00:00:00 |
| Session first | 2018-11-30 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Comment by JC5** [comment]
Thanks. It seems it’s database dependent. I’ll see if it’s something I can configure. Otherwise you’re out of luck I’m afraid.

**Comment by jlauwers** [comment]
I'm using postgres:10 (docker)
I followed this [docker-compose](https://raw.githubusercontent.com/firefly-iii/firefly-iii/master/docker-compose.yml).

I guess you could try something along the line of:
`select qt.*
from query_table qt
where LOWER(column_name) LIKE LOWER('%vAlUe%');`

**Comment by JC5** [comment]
That wrecks havoc with non-Latin characters unfortunately. I’ll dive into the problem :)

**Comment by jlauwers** [comment]
Right, didn't think about that. :(

**Comment by JC5** [comment]
Not to worry!
