### ISSUE TITLE
Hide accounts on Reports

### ISSUE THREAD

**Issue by dealanis** [firefly-iii/firefly-iii#2324]
**Description**
Currently, all accounts are shown on the Reports "included accounts" listbox.

**Solution**
Add a configuration similar to the "Home screen accounts" for "Reports accounts" where the user can select which accounts are relevant for reporting and unclutter the reports when selecting "all accounts"

**What are alternatives?**
The user select the accounts manually even if the target of the report is all currently active accounts.

**Additional context**
I understand that attaching this to the active/inactive state of the account could be an option, but considering the firefly approach that would be an "unwritten rule" that could bring confusion. So following the Home screen functionality could be better and simplify reporting when accounts are not operational and kept for historical purposes and are only relevant by use case and not for general reporting or day-to-day use.

Hope this makes sense. :D

**Comment by JC5** [comment]
It makes sense but it’s not going to happen. It’s too much work for too little gain.

**Comment by dealanis** [comment]
I understand, thinking about it, I think this could be achieved with the URL Path or maybe a prefix to the relevant accounts and using it to select them. 

Thank you for the quick reply!
