### ISSUE TITLE
Balance on dashboard and loan/debt

### ISSUE THREAD

**Issue by jlnbdt** [firefly-iii/firefly-iii#2325]
Hi,

Sorry for this noob question: I've read several topics but it's still no clear to me.

On the dashboard, balance for june is -1000.16€ (€2,758.20 / €-3,758.36).
After clicking on the link "balance" to get the month report, it appears that the revenue/income value is the same (2758.20), but not the expenses value. Indeed, this one integrates debt and loan accounts, and is -5155.93.

So I don't understand why balance on the dashboard doesn't include debt and loan accounts.

Thanks a lot (and by the way: Firefly-iii is a great and very usefull app!)

Firefly III version 4.7.8

![2019-06-30_02-54](https://user-images.githubusercontent.com/6383095/60390916-718f1680-9ae2-11e9-901c-7697b935fce0.png)

![2019-06-30_02-50](https://user-images.githubusercontent.com/6383095/60390918-7ce24200-9ae2-11e9-82f3-ec0c3ef6604b.png)

![2019-06-30_02-53](https://user-images.githubusercontent.com/6383095/60390920-8075c900-9ae2-11e9-97be-7db57a2d4e1a.png)

**Comment by JC5** [comment]
It could be a bug. I’ll check it out, thanks for letting me know

**Comment by JC5** [comment]
This will be fixed in the next release. Currently, money sent to loans and debts is stored as a transfer, and this is not counted in the balance. This will change in future versions.
