### ISSUE TITLE
Recurring transaction not created

### ISSUE THREAD

**Issue by Kline-** [firefly-iii/firefly-iii#2327]
I am running Firefly III version 4.7.17

**Description**
I noticed a bill I had set via a recurring transaction for the 30th day of every month wasn't created. The cron email to www-data indicates the job fired successfully but the transaction wasn't created.

**Extra info**
Debug information generated at 2019-07-01 17:28:52 America/Chicago for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.4-2 |
| Display errors | Off |
| Session start | 2019-07-01 00:00:00 |
| Session end | 2019-07-31 23:59:59 |
| Session first | 2019-05-17 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; CrOS x86_64 11895.118.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.159 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**
recurrences table:
```sql
INSERT INTO `recurrences` (`id`, `created_at`, `updated_at`, `deleted_at`, `user_id`, `transaction_type_id`, `title`, `description`, `first_date`, `repeat_until`, `latest_date`, `repetitions`, `apply_rules`, `active`) VALUES
(11,	'2019-05-31 13:03:15',	'2019-05-31 13:03:15',	NULL,	1,	1,	'Charter',	'',	'2019-06-30',	NULL,	NULL,	0,	1,	1);
```

recurrences_repititons table:
```sql
INSERT INTO `recurrences_repetitions` (`id`, `created_at`, `updated_at`, `deleted_at`, `recurrence_id`, `repetition_type`, `repetition_moment`, `repetition_skip`, `weekend`) VALUES
(15,	'2019-05-31 13:03:15',	'2019-05-31 13:03:15',	NULL,	11,	'monthly',	'30',	0,	3);
```

recurrences_transactions table:
```sql
INSERT INTO `recurrences_transactions` (`id`, `created_at`, `updated_at`, `deleted_at`, `recurrence_id`, `transaction_currency_id`, `foreign_currency_id`, `source_id`, `destination_id`, `amount`, `foreign_amount`, `description`) VALUES
(15,	'2019-05-31 13:03:16',	'2019-05-31 13:03:16',	NULL,	11,	7,	NULL,	12,	40,	65.990000000000,	NULL,	'Internet');
```

**Comment by JC5** [comment]
I won’t be able to check this out for a few days. There’s nothing in your log files?

**Comment by JC5** [comment]
OK I did a quick check. It won't do anything on the 30th of the month, because it was set to fire on the Friday before. That would be the 28th.

```
[2019-07-02 05:55:23] production.DEBUG: Date is Sun 30 Jun 2019, and this is in the weekend, so corrected to Fri 28 Jun 2019 (Friday).  
```
But the start date of the recurring transaction is 2019-06-30 so it won't be able to fire before the 30th anyway. That seems to be the reason it skipped this month.

**Comment by Kline-** [comment]
Man, good catch, thank you. It didn't even occur to me that the weekend setting would've done that due to the start date of the transaction.

**Comment by JC5** [comment]
No worries. It’s a unique situation. I’ve made a note to add a validation rule to check for this.

**Comment by JC5** [comment]
And thank you for the donation! 👍
