### ISSUE TITLE
Error on initializing my database Docker version

### ISSUE THREAD

**Issue by JunkyardCat** [firefly-iii/firefly-iii#2330]
Ubuntu 18.04 server

**Description**
I am following this instruction(https://firefly-iii.readthedocs.io/en/stable/installation/docker.html) on how to install firefly on a docker

I am stuck at this command
docker exec -it 6e9c9b720b9d php artisan migrate --seed

it gives me error
![PUTTY_2019-07-07_16-03-28](https://user-images.githubusercontent.com/22941307/60765684-c3cacb80-a0d0-11e9-8641-d02ac6606381.jpg)

This is the command i ran before getting to that

docker volume create firefly_iii_export
docker volume create firefly_iii_upload

docker run -d \
-v firefly_iii_export:/var/www/firefly-iii/storage/export \
-v firefly_iii_upload:/var/www/firefly-iii/storage/upload \
-p 8082:80 \
-e FF_APP_ENV=local \
-e FF_APP_KEY=S0m3R@nd0mString0f32Ch@rsEx@ct1y \
-e FF_DB_HOST=CHANGEME \
-e FF_DB_NAME=CHANGEME \
-e FF_DB_USER=CHANGEME \
-e FF_DB_PASSWORD=CHANGEME \
jc5x/firefly-iii:latest

**Comment by marcelbrueckner** [comment]
Right before the [Straight from Docker Hub](https://firefly-iii.readthedocs.io/en/stable/installation/docker.html#straight-from-docker-hub) section, the documentation says: 
> If you do this, you should already have a MySQL database running somewhere. For example, when you have one central MySQL database for all of your docker containers.

So, do you already have an MySQL database running? If not, take a look at the doc's [Docker Compose](https://firefly-iii.readthedocs.io/en/stable/installation/docker.html#docker-hub-with-automatic-updates-via-docker-compose) section. That may suit better. Make sure to **actually change** the example values.

**Comment by JunkyardCat** [comment]
can i ask how to make a docker mysql database suitable for firefly III?

**Comment by JC5** [comment]
As long as there's a database for Firefly III there's not much you need to do.
