### ISSUE TITLE
Transaction history overview in Reports

### ISSUE THREAD

**Issue by Kuzj** [firefly-iii/firefly-iii#2331]
Extra dates(Interest date, Processing date, ...) are not displayed in report.
![1](https://user-images.githubusercontent.com/7158494/60766003-e1396e80-a0ab-11e9-8472-9890a1de2a7c.png)
![2](https://user-images.githubusercontent.com/7158494/60766006-e4345f00-a0ab-11e9-875d-d1d9fd66c293.png)

**Comment by Kuzj** [comment]
temporary crutch(comment condition) :)
https://github.com/firefly-iii/firefly-iii/blob/master/resources/views/v1/reports/partials/journals-audit.twig
80                {#{% if transaction.transactionJournal.hasMeta('interest_date') %}#}
81                    {{ journalGetMetaDate(transaction.transactionJournal, 'interest_date').formatLocalized(monthAndDayFormat) }}
82                {#{% endif %}#}

**Comment by JC5** [comment]
Thanks for letting me know. I'll pick this up for the next release, where I believe this is fixed already.

**Comment by JC5** [comment]
Fixed in the next release.
