### ISSUE TITLE
Updating Piggy bank using API

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2333]
**Bug description**
Hello James, I am running Firefly III version  4.7.17 and I have issues updating Piggy bank using the API. Editing fields(Piggy bank names, account to be linked, target amount) when current amount is 0 will throw an error. I assume this is a bug since the web interface allows user to update piggy bank even when current amount is 0. 

**Steps to reproduce**

```
curl -X PUT "https://demo.firefly-iii.org/api/v1/piggy_banks/1" -H "accept: application/json" -H "Authorization: Bearer xxx" -H "Content-Type: application/json" -d "{\"name\":\"New digital camera\",\"account_id\":2,\"target_amount\":1000,\"current_amount\":0,\"start_date\":\"2018-09-17\",\"target_date\":\"2020-09-17\",\"notes\":\"Some notes\"}"
```

Error message: 
```
{
  "message": "The given data was invalid.",
  "errors": {
    "current_amount": [
      "current amount must be larger than zero."
    ]
  }
}
```

**Comment by JC5** [comment]
Thanks, I assume it's a bug indeed. I'll pick it up for the next release.

**Comment by JC5** [comment]
Fixed in the develop branch.
