### ISSUE TITLE
Date Range Selection Not Honored in Liabilities Account View

### ISSUE THREAD

**Issue by HalfDemon** [firefly-iii/firefly-iii#2336]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

Manual date range selection not being honored in 'All Transactions Chart' in liabilities account view.

**Steps to reproduce**
Select a date range using the date range selection tool at the top right of the screen, go to Accounts > Liabilities , open one of the liabilities accounts.

**Expected behavior**
Date range for Liabilities all transactions chart should match the range selected using the global selection tool

**Extra info**

Firefox 70.0a1 (2019-07-12) (64-bit)
Debug information generated at 2019-07-15 20:20:19 America/Chicago for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.19 |
| Display errors | Off |
| Session start | 2019-06-01 00:00:00 |
| Session end | 2019-07-31 00:00:00 |
| Session first | 2019-06-13 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite, sqlsrv |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_dblib, pdo_mysql, pdo_sqlite, wddx, xmlreader, sqlsrv, pdo_sqlsrv, zip, Zend OPcache |

Example of date range not being honored in screenshot

![2019-07-15 20_10_24-All transactions for account Car » Accounts » Firefly III - Firefox Nightly](https://user-images.githubusercontent.com/5622363/61259056-1c880d00-a73e-11e9-8503-32475be1be3e.png)

**Comment by JC5** [comment]
I see it, thanks for letting me know.

**Comment by JC5** [comment]
If you select the "all transactions" range, it will ignore the top right date indicator. This is by design.
