### ISSUE TITLE
Split transactions and tags

### ISSUE THREAD

**Issue by caseyhoward** [firefly-iii/firefly-iii#2341]
I am running Firefly III version 4.7.17

Is there a way to view transactions without the splits? They aren't grouped when viewing them or reconciling which makes it super hard and time consuming to reconcile an account since on my statement I see one transaction and in Firefly I see the splits and not the total. I can't match dollar values. I have to re add it up or click on it to see what the total is. Is there a feature I'm not seeing that allows you to view the entire transactions without the splits?

Anyway, Firefly III is great. Keep up the good work.

**Comment by JC5** [comment]
Not yet, but the view will improve in the next release.
