### ISSUE TITLE
How can I mark two transactions as duplicates

### ISSUE THREAD

**Issue by Vici37** [firefly-iii/firefly-iii#2343]
I am running Firefly III version 4.7.17.

**Description**
Stood up and have been playing around with firefly iii for the past few days, really enjoying it! I've uploaded some transaction logs from my banks and I've noticed that a transfer is showing up twice as an expense for one account, revenue for the other. This transfer happens across two different banks, may get processed on different days, have different descriptions from each other, and have the same amount.

I've tried creating a rule that would convert the amount of one of these to zero (and let the other transfer transaction represent the real transfer), but that doesn't appear to be an option. Any suggestions would be appreciated. I did take a look in the DB in an attempt to do it there, but the amounts listed in the `transactions` table don't match what's shown in the UI, so I assume it's stored elsewhere.

Thanks in advance!

**Comment by iwalucas** [comment]
I have the same situation happening, usually I just delete one of them and make one a transfer from asset account #1 to asset account #2. So no revenue/expense account is moved

**Comment by JC5** [comment]
> This transfer happens across two different banks, may get processed on different days, have different descriptions from each other, and have the same amount.

In these cases Firefly III can't detect the duplication, unfortunately.

**Comment by Vici37** [comment]
That's unfortunate but understandable. Thanks for the suggestion @iwalucas, I'll probably do that.

As a feature request, it would be cool if I could define my own duplication rules, though that sounds like a very low priority feature if I've ever heard one.

Thanks for the help!
