### ISSUE TITLE
Docker Images not updated anymore

### ISSUE THREAD

**Issue by markieo1** [firefly-iii/firefly-iii#2344]
The docker images are not being pushed correctly anymore to Docker Hub.
As can be seen on the [Travis CI job log](https://travis-ci.com/firefly-iii/firefly-iii/jobs/217600784#L4753).

I think you should fix the credentials, so that pushing to Docker Hub works again.

**Comment by JC5** [comment]
Thanks for the heads up.

**Comment by JC5** [comment]
The last build seems to have run perfectly.

**Comment by jlauwers** [comment]
I can confirm it works.

**Comment by JC5** [comment]
Thanks, I appreciate the feedback.
