### ISSUE TITLE
Option to pre-fill transaction fields from most recent

### ISSUE THREAD

**Issue by Kline-** [firefly-iii/firefly-iii#2345]
**Description**
I would like the option to have new transactions set their category, description, budget, and tag based on the most recently used values for the last transaction associated to the destination account.

For example I categorize visits to my physician's office as "Medical". Right now I can either fill this in manually or create a rule to fill it in based on the destination expense account. Having to create rules like this for the places I most routinely spend money at just to ensure consistency in categorizing transactions could grow unwieldy.

**Solution**
Simplify adding new transactions without creating rules to ensure consistency.

**What are alternatives?**
Rules can be used in this manner, but it's a bit more cumbersome.

**Comment by JC5** [comment]
This has been discussed a few times already. It has no priority at the moment.

**Comment by Kline-** [comment]
Thanks for letting me know. Sorry that I must have missed it when searching previous issues!
