### ISSUE TITLE
repeat income

### ISSUE THREAD

**Issue by lziron** [firefly-iii/firefly-iii#2347]
Hi, first of all I would like to thank everyone who is involved in this project.

I'd like to suggest a small implementation in the income part.

It would be interesting to add a field suggesting if I would like to repeat this monthly, quarterly, semiannual, yearly income, so adding the receipt automatically in the transactions. thank you!

**Comment by JC5** [comment]
You could create a recurring transaction perhaps?

**Comment by lziron** [comment]
Exactly, that's what I meant. a recurring transaction.

**Comment by JC5** [comment]
http://docs.firefly-iii.org/en/latest/advanced/recurring.html
