### ISSUE TITLE
The Demo is Broken

### ISSUE THREAD

**Issue by hhimanshu** [firefly-iii/firefly-iii#2348]
**Bug description**
I am running Firefly III demo version and it throws an error after giving credentials
<img width="1440" alt="Screen Shot 2019-07-22 at 6 31 35 PM" src="https://user-images.githubusercontent.com/6589036/61675946-11d5f680-acaf-11e9-8740-40cea93f1f9e.png">

**Steps to reproduce**

**Expected behavior**

**Extra info**

**Bonus points**

**Comment by JC5** [comment]
It works. Not sure why you got the error.
