### ISSUE TITLE
Comma Separator in amount field

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2350]
**Bug description**
I am running Firefly III version 4.7.17.3. When submitting a transaction with decimal separator in the amount field using the API, it fails. 

This fails. 
```
curl -X POST "https://demo.firefly-iii.org/api/v1/transactions" -H "accept: application/json" -H "Authorization: Bearer xxxx" -H "Content-Type: application/json" -d "{\"type\":\"withdrawal\",\"description\":\"Groceries\",\"date\":\"2018-09-17\",\"transactions\":[{\"amount\":12,95,\"description\":\"Vegetables\",\"curreny_id\":12,\"currency_code\":\"EUR\",\"source_id\":2,\"destination_name\":\"Buy and Large\"}]}"
```

Error message: 
```

  "message": "The given data was invalid.",
  "errors": {
    "type": [
      "The type field is required."
    ],
    "date": [
      "The date field is required."
    ],
    "description": [
      "Need at least one transaction.",
      "The description field is required."
    ]
  }
}
```

It mistakes the comma as a new json key pair.

This works

```
curl -X POST "https://demo.firefly-iii.org/api/v1/transactions" -H "accept: application/json" -H "Authorization: Bearer xxxx" -H "Content-Type: application/json" -d "{\"type\":\"withdrawal\",\"description\":\"Groceries\",\"date\":\"2018-09-17\",\"transactions\":[{\"amount\":12.95,\"description\":\"Vegetables\",\"curreny_id\":12,\"currency_code\":\"EUR\",\"source_id\":2,\"destination_name\":\"Buy and Large\"}]}"
```

**Comment by jlauwers** [comment]
What about this?
`curl -X POST "https://demo.firefly-iii.org/api/v1/transactions" -H "accept: application/json" -H "Authorization: Bearer xxxx" -H "Content-Type: application/json" -d "{\"type\":\"withdrawal\",\"description\":\"Groceries\",\"date\":\"2018-09-17\",\"transactions\":[{\"amount\":"12,95",\"description\":\"Vegetables\",\"curreny_id\":12,\"currency_code\":\"EUR\",\"source_id\":2,\"destination_name\":\"Buy and Large\"}]}"`

**Comment by JC5** [comment]
As per the JSON standard, numbers can only contain [dots](https://json.org/). Your request isn't valid JSON so it can't be processed.
