### ISSUE TITLE
How do you track money lent or paid to a friend in Firefly?

### ISSUE THREAD

**Issue by eduedp** [firefly-iii/firefly-iii#2351]
I am running Firefly III version 4.7.17.3

**Description**
What is a good way to track money lent or paid to a friend in Firefly?

Simple example:
I lend my credit card to my friend so he can buy something, he transfer to my bank account the entire value later.

Split purchase example:
I purchase something online for me and my friend 50/50 with my credit card. Total $100.
He pays me later his part, $50 in cash.

How to track these situations correctly?
By correctly, I mean in the end his expenses won't be my expenses, or at least it will be deducted.

**Comment by JC5** [comment]
You can't really track it. You can keep track of the expenses + income but if you want to totally ignore it, that's more difficult.

One solution would be to make a separate asset account and make the expense from that account. Then, when the friend pays you back, create a deposit into that asset account.

**Comment by eduedp** [comment]
I think I found a "better" approach. Now I'm testing how reports will deal with it.

I created a debt liability with value $0, then I make transfers to it when I pay, and transfer from it when I receive the money back. This way it does not count as one of my expenses.
I tried using a normal asset account, but that way I think "pollutes" the accounts view.
