### ISSUE TITLE
Transfers are totaled incorrectly during a second reconciliation

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2352]
**Bug description**
I am running Firefly III version 4.7.17.3.

I have several checking accounts and the reconciliation was not working correctly after I edited the description of several transfers.  After editing and re-reconciling, the "Difference" calculation was not totaling $0.

I've isolated the problem and demonstrate it below.  The bug is reproducible on the demo site.

**Steps to reproduce**
- Create three accounts: "test 1", "test 2", "test 3"
- Set a $7 balance in "test 1", no balance in the other accounts
- Create a new transfer from "test 1" to "test 2" of $2, and another transfer to "test 3" of $1.

You'll end up with three accounts with balances of $4, $2, and $1.

- Reconcile "test 1".  Check the three boxes (initial balance, two transfers).  Reconciliation Options shows $0, Overview shows the following values

Submitted start balance (July 1, 2019) | $0.00
-- | --
Selected transactions (3) | $4.00
Already cleared transactions (0) | $0.00
Submitted end balance (July 31, 2019) | $4.00
Difference | $0.00

- Store reconciliation.
- Edit the $2 transfer.  Change the description only (amount unchanged).
- Reconcile "test 1" again.  Check the box, Reconciliation Options $0, Overview shows the following values

Submitted start balance (July 1, 2019) | $0.00
-- | --
Selected transactions (1) | $-2.00
Already cleared transactions (2) | $8.00
Submitted end balance (July 31, 2019) | $4.00
Difference | $2.00

The Difference should be $0, but it's $2.

I used dollar values equal to powers of 2 to make this easier to figure out.

I suspect that the "Already cleared transactions" calculation is adding the absolute values ($7 + $1) to $8 instead of treating the transfer out as a negative ($7 - $1).  During the second reconciliation, the already cleared transactions should total $6.

**Comment by JC5** [comment]
Thanks, this is very helpful! I'll check if this is still a bug in the next release, which is running [on the dev site])(https://dev.firefly-iii.org/login). With this breakdown I can further chase the bug.

**Comment by JC5** [comment]
This will be fixed in the next release. The reconciliation remains 0 after editing.
