### ISSUE TITLE
Repeated valid transactions should be allowed on import

### ISSUE THREAD

**Issue by viraptor** [firefly-iii/firefly-iii#2353]
**Bug description**
I am running Firefly III version 4.7.17.3, and my problem is:

When importing from CSV file I'm running into a situation where there are multiple valid entries with the same date/description/amount. For example:
```
24/07/2019,"-1.49",APPLE ITUNES STORE        SYDNEY
24/07/2019,"-1.49",APPLE ITUNES STORE        SYDNEY
```
or multiple tram rides which are separate lines:
```
24/05/2019,"-6.76",TRANSPORTFORNSW TAP       SYDNEY
24/05/2019,"-6.76",TRANSPORTFORNSW TAP       SYDNEY
```
Currently firefly doesn't like importing the repeated entries, but this does happen quite a lot for me. (12 over 3 months, mostly from taking public transport)

This was previously mentioned in https://github.com/firefly-iii/firefly-iii/issues/1037

**Steps to reproduce**
Import lines mentioned above.

**Expected behavior**
I see that this is an interesting issue and not everyone may have the same expectations here.
I'd like to propose a resolution which I used in previous previously in my custom statement processing:

- Assume that when importing, the file will have a full day included (there won't be missing entries for a given date if another transaction is available there)
- Merge the number of entries. For example if the imported statement contains 3 entries, and the database does not, add 3 entries. If the import contains 3 entries and the database contains 2, add 1 entry as new.
- Possibly warn if the database contains more matches than the import

This also allows easy import of CSVs where the bank makes old entries suddenly appear, for example when pending transactions don't resolve all in the same time. (Yes, that kind of shows two use cases as one really)

Maybe this could be possible to implement behind some extra import option ("allow duplicates and merge"?)

I'm happy to chat about alternative approaches.

**Comment by JC5** [comment]
If Firefly III can't distinguish individual lines they'll be treated as a duplicate, and they won't be imported. This is way more useful for a lot of people than the assumption there is no overlap between imports. The logic to add 2 out of 3 entries is unsustainable and very complex. Your last point could be an option, but not in the current version.

You should approach this from the other end. The lines should be unique. CSV exports should contain at least transaction ID's or other unique values.

**Comment by viraptor** [comment]
Unfortunately the available feeds are really broken :-( My banks don't provide any csv id fields, and even their ofx export has duplicates in the "unique ID" field.

**Comment by basilgohar** [comment]
> If Firefly III can't distinguish individual lines they'll be treated as a duplicate, and they won't be imported. This is way more useful for a lot of people than the assumption there is no overlap between imports. The logic to add 2 out of 3 entries is unsustainable and very complex. Your last point could be an option, but not in the current version.
> 
> You should approach this from the other end. The lines should be unique. CSV exports should contain at least transaction ID's or other unique values.

This unfortunately a problem with my bank (U.S. Bank) as well with the CSV export they provide.  I haven't looked at the internals of the other formats it provides to see if they're transaction-unique, but I wouldn't be surprised if there were some issues with them as well.

Perhaps it could be a configurable option as opposed to a purely heuristic behavior (that is, how to deal with duplicate records)?

**Comment by viraptor** [comment]
If anyone's looking for a quick fix for pre-processing CSV files for now, this is what I'm currently using: https://gist.github.com/viraptor/7e6fba2e76931faa586609cc6ba0b9b1
It appends a value I'm using as "External ID". It's consistent between runs, so it both makes multiple lines in one statement unique, and detects them as duplicates on the next run, so you can safely import overlapping statements.
