### ISSUE TITLE
403 Forbidden Fresh Install

### ISSUE THREAD

**Issue by ctetuk** [firefly-iii/firefly-iii#2354]
I am running Firefly III version 4.7.17.3

**Description**
After a fresh install got a warning about my document root not being the public folder but it redirected to the home page and appeared to be working.
Before doing anything else I changed the document root to the public folder as the warning suggested and now I'm getting a permission error "403 Forbidden" in the title of the page and in the body "Forbidden
You don't have permission to access / on this server."

Would have thought that I would of had a permission issue when the document root was the firefly root as well if that was the case, so think the error is misleading.

The www-data user is owner on all of the files and folders.

Does anyone have any ideas please?

**Extra info**
OS is Ubuntu 18.04.2 LTS using apache webserver and PHP 7.2

**Bonus points**

**Comment by JC5** [comment]
Are the access rights correct on all directories?

**Comment by ctetuk** [comment]
I have had a look in several of the folders and all files/folders have www-data:www-data with 0755 for folders and 0644 for files.
I left everything as default from installer, should they be any different from this?

Have also attached screenshot if helps.

Thanks

![Capture](https://user-images.githubusercontent.com/53432962/62062719-764e0400-b221-11e9-8ff0-e5cda61fc01f.PNG)

**Comment by JC5** [comment]
Did you also change the web root in the global Apache config, if applicable?

**Comment by ctetuk** [comment]
I am using virtual hosts so firefly has it's own conf in the sites-available folder.

Screenshot of the config below if that helps. The pix-elated bits are the FQN of the website.

![config](https://user-images.githubusercontent.com/53432962/62115060-b5c33180-b2af-11e9-962b-a1cab176a195.png)

**Comment by ctetuk** [comment]
I have got it working, I was being a bit thick about it... Was editing the apache http config file when trying to use the site with https... now that I have updated the apache config for 443 it is working.

Thanks for having a look.
