### ISSUE TITLE
Issues with OpenLDAP

### ISSUE THREAD

**Issue by sparchatus** [firefly-iii/firefly-iii#2355]
**Bug description**

I am running Firefly III version 1.7.17, and my problem is:

I am using OpenLDAP and adldap2 is not using the ADLDAP_DISCOVER_FIELD and the ADLDAP_AUTH_FIELD which I have set to 'uid'.

I was able to fix it with:

adldap2-laravel version v5.1.2 should be using the Version 5 config. Following this https://adldap2.github.io/Adldap2-Laravel/#/upgrading?id=upgrading-from-5-to-6 I have changed back some config names in ldap_auth.php:
- identifiers -> usernames
- locate_users_by -> discover
- bind_users_by -> authenticate 

There was a second problem with openldap because it could not handle DN that went through ldap_escape. This is fixed since adldap2 v10.0.5 but composer.lock is still on version 10.0.4. maybe we could update 

I guess both issues might be resolved by using never versions of adldap. If I should have done that already when installing firefly-iii myself then I guess we can close this issue again :smile:

**Comment by JC5** [comment]
I'm not sure what your question is?

**Comment by sparchatus** [comment]
Oups! I tried to report two bugs with solutions I found at the same time. Not a good idea I guess...

#### Problem1:
I need adldap to use uid instead of userprincipalname so I did set the ADLDAP_DISCOVER_FIELD 
and ADLDAP_AUTH_FIELD to 'uid'.

But the openldap server log shows that the setting was not respected
conn=4096 op=1 SRCH base="MASKED" scope=2 deref=0 filter="(&(objectClass=inetOrgPerson)(objectClass=person)(uid=*)(?userprincipalname=MASKED))

The fix was to apply the following changes to _config/ldap\_auth.php_ because the adldap2-laravel version 5.* which we have as a dependency uses the left hand values. I think the right hand ones are for version 6.*

|v5|v6|
|---|---|
|usernames|identifiers|
|discover|locate_users_by|
|authenticate|bind_users_by|

#### Problem2:
adldap2 pre v10.0.5 has a bug with openldap so I guess I am asking if you could update this dependency :smile:

**Comment by JC5** [comment]
Ah yes, I think this is already planned for the next release but I'll keep it open as a bug so I won't miss it :+1:

**Comment by JC5** [comment]
Yep, it's fixed. :+1:

**Comment by sparchatus** [comment]
I have updated and can confirm that the problem has disappeared for me. Thanks a lot :-)
