### ISSUE TITLE
Auto update feature

### ISSUE THREAD

**Issue by lucianor** [firefly-iii/firefly-iii#2357]
**Description**
I would like Firefly to have the ability to auto update by clicking on a button after the update check has identified there is a newer version available.

**Solution**
This feature would reduce the amount of effort for the users to upgrade the software after it has been released, therefore ensuring there is always a larger set of users running the latest version. It would also reduce the amount of errors and data losses during an upgrade.

**What are alternatives?**
There are currently no alternatives to this feature, the process needs to be ran manually.

**Additional context**
This feature is already available on many web software - WordPress is the one that comes to mind right now, but I know also Radarr and Sonarr also offer this functionality - although they ran on different platforms.

**Comment by JC5** [comment]
Not going to happen. I like to spend my time on Firefly III, not on some upgrade routine that has to work perfectly on a bazillion platforms. This is an intentional choice and it's not going to change.

Easy upgrades can be accomplished by migrating to the docker image.
