### ISSUE TITLE
Show examples when asking for date format

### ISSUE THREAD

**Issue by viraptor** [firefly-iii/firefly-iii#2359]
**Description**

I'd like to see an example of the row to be imported when choosing a date format.
Currently I have to first specify the format, then on the next page/step I see some samples.

**Solution**

It would be great to either:
- see the first two rows when being asked for the date format, or
- if the date format question was moved to the next page with value samples

**Comment by JC5** [comment]
I assume you know the date format from the file, and it won't be easy to change the routine. So sorry, but this won't change.
