### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by jonny190** [firefly-iii/firefly-iii#2360]
**Bug description**
I am running Firefly III version 4.7.17.3, and my problem is:

Job could not be started or crashed: The import routine crashed: Guzzle Exception: Client error: `GET https://www.saltedge.com/api/v4/customers/?from_id=0` resulted in a `400 Bad Request` response: {"error_class":"RequestExpired","error_message":"Request has expired. Server time: 2019-07-31 16:28:34 UTC, expires at: (truncated...)

**Steps to reproduce**
Configure the import settings then try to do an import

**Expected behavior**
import accounts 

**Extra info**
It looks like the request time 16:28:34 is an hour out it was ran at 17:28

**Comment by JC5** [comment]
Mmm, a bad request could be a lot of things. Are you sure your API code is correct?

The time is in UTC, so that explains the difference.

**Comment by jonny190** [comment]
Hi,
Yeah I've copied and pasted them and checked for spaces at the begining and end of each

**Comment by jonny190** [comment]
![Screenshot_20190801-005130_Chrome](https://user-images.githubusercontent.com/8059327/62255789-ae5a7000-b3f6-11e9-8154-0288122a0b75.jpg)

**Comment by JC5** [comment]
Strange. This looks like it's a salt edge bug because I can't seem to replicate any errors. 

What's the output of this command?

```
 date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S %Z %z"
```

**Comment by jonny190** [comment]
turns out my servers time was out by 4 mins and upon correcting this all is good with the world

**Comment by JC5** [comment]
Glad to hear it! It's an unfortunate side-effect of Salt Edge's API. I have to submit a time-out moment (which is weird).
