### ISSUE TITLE
Rules reordering arrows have a one-off

### ISSUE THREAD

**Issue by viraptor** [firefly-iii/firefly-iii#2361]
**Bug description**
I am running Firefly III version 4.7.17.3, and my problem is:

The arrows for reordering rules are in incorrect rows. First row has both up/down arrows, but the last two have only up arrows.

**Steps to reproduce**
Create/delete some rules? I'm not sure how I ended up with this.

**Expected behavior**
No up arrow on the top entry, no down arrow on the bottom entry.

**Extra info**

Debug information generated at 2019-08-01 21:10:05 Australia/Melbourne for Firefly III version **4.7.17.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17.3 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.20 |
| Display errors | Off |
| Session start | 2019-08-01 00:00:00 |
| Session end | 2019-08-31 23:59:59 |
| Session first | 2018-08-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

**Bonus points**
![rules_ordering](https://user-images.githubusercontent.com/188063/62288890-b4a52680-b4a0-11e9-9ea6-ec876dcaa87a.png)

**Comment by JC5** [comment]
Moving one up or down should already correct this. I think I can fix this for the next release. Thx for letting me know.
