### ISSUE TITLE
Best way to eliminate duplicated Expense/Revenue Accounts (&nbsp chararcter)

### ISSUE THREAD

**Issue by dealanis** [firefly-iii/firefly-iii#2369]
I am running Firefly III version 4.7.17

**Description**
Hi, when I migrated my transactions to firefly I identified (late by the way) that my source had the **"&nbsp"** character for spaces. So several of my Revenue/Expense accounts were created with this character instead of space. 

The problem propagates when introducing new transactions into the system, the listbox show the account ("Best&nbspBuy"), when selected it seems that the character translates to a regular space ("Best Buy"), and when saved it creates a new account ("Best Buy") that seems to be duplicated.

I identified all the cases on databases but I'm not sure what would be the recommended steps or approach to follow, so I can unify the accounts and eliminate this invisible but problematic character of the names. 

Because of the behavior of this character, it is very difficult to manually modify the transactions so if there is a procedure that I could follow at the database level would be great. 

**Extra info**
Account Name showed on firefly: "Best Buy"
Account Name saved on database: "Best&nbspBuy" shows as "Best Buy"
When selecting the account: "Best Buy" saved as "Best day"

**Bonus points**
![Example2](https://user-images.githubusercontent.com/1350480/62396774-a6efaf80-b539-11e9-9b19-3e746121791a.PNG)
![Example1](https://user-images.githubusercontent.com/1350480/62396775-a6efaf80-b539-11e9-81b3-7de35bb78391.PNG)

Thank you again for your great work! If there is anything I could do to help let me know.

**Comment by JC5** [comment]
The easiest way would be to edit the database directly, and update the transactions to point to the correct account.

To do this, you'll need the account ID's which are visible in the URL when you edit, view or delete an account (`accounts/show/xxx`).

So if 23 is the correct account ID, and 83 is the incorrect account ID, this query will replace the incorrect entries with the correct entries.

```sql
UPDATE transactions SET account_id = 23 WHERE account_id = 83;
```

You should update the numbers with the correct ID's, of course.

Once you've done that for all offending accounts, you can browse to /flush on your installation to clear the cache. The offending accounts will still be in the system but you can safely delete them using the user interface.

**Comment by JC5** [comment]
I've edited the CSV import routine to filter out HTML non-breaking spaces.

**Comment by dealanis** [comment]
Will do that!

Thanks for the guidance, I was almost there. I thought the data was cached, but didn't figure out the flush part, so better asked away to be sure.

Thank you again! Greetings from Mexico.
