### ISSUE TITLE
Stored XSS in liability error.

### ISSUE THREAD

**Issue by 0x2500** [firefly-iii/firefly-iii#2370]
**Bug description**
Current version of Firefly III Version 4.7.17.5 is vulnerable to stored XSS due to lack of filtration of user-supplied data in liability name field. Malicious attacker can create specially crafted request, which contains javascript code in it. Malicious javascript code will be executed when user visit link below.

**Steps to reproduce**
1. Set a new liability account with name "<script>alert("XSS in liability error")</script>" , also set "Start amount of debt" to 1, "start date of debt" to any date, "interest" to 1. Save it.
![craft_liability](https://user-images.githubusercontent.com/46705704/62397694-942ea800-b544-11e9-87db-77eb5da894d5.png)
2. Go to /accounts/show/[id_of_your_liability]/all. You will see transaction with "to" and "from" fields. Grab id of account from link in "to" field. It's often id_of_your_liability + 1.
3. Go to /accounts/delete/[id_of_your_liability], and delete liability.
4. Now every time you visit /accounts/show/[Id which you grab before from "to" field] xss will execute. 
![error_xss_liability](https://user-images.githubusercontent.com/46705704/62398095-b70d8c00-b545-11e9-8018-f15aade1278c.png)

**Extra info**
Tested on Mozilla 60.4.0esr (64-bit)

**Comment by JC5** [comment]
Fixed, could you confirm?

**Comment by 0x2500** [comment]
Bug is fixed.
