### ISSUE TITLE
Cron not running in Docker?

### ISSUE THREAD

**Issue by agilob** [firefly-iii/firefly-iii#2372]
**Bug description**
I am running Firefly III version 4.7.17.3 default docker image and would like to have cron job with to create repeating transactions be enabled by default.

**Steps to reproduce**
Run firefly iii in docker with default setup.

**Expected behaviour**
Would expect repeating transactions to be created automatically without forking docker to own image with cron setup.

I'm currently getting this error:
![Screenshot_20190805_194642](https://user-images.githubusercontent.com/2544251/62487449-c7c63800-b7b9-11e9-9219-34aabe6541a9.png)

**Comment by JC5** [comment]
There are some related issued about this already. Cron will not be added to the docker image but to the docker compose thing probably.
