### ISSUE TITLE
Account numbers with spaces are not being matched

### ISSUE THREAD

**Issue by carbolymer** [firefly-iii/firefly-iii#2373]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is: that accounts with spaces are not mapped automatically.

**Steps to reproduce**
1. Add a new account - set account number to the one with spaces e.g. `78 1010 1023 0000 2613 9520 0000`
2. Try to import CSV file with this account number but without spaces
3. Select column for mapping

**Expected behavior**
Account is automatically mapped against account number from CSV

**Actual behaviour**
Account is not mapped against account number - `no mapping` value on drop-down. After import new account with the same number, but without spaces is created.

**Comment by JC5** [comment]
That's correct, there has to be an exact match.

**Comment by carbolymer** [comment]
Can you reveal why? Documentation does not say a word about it. My banks use 3 different formats for account numbers plus country code is sometimes present or not. So for firefly one account number in 6 different formats is a 6 different accounts. Why?

**Comment by JC5** [comment]
I can fix the spaces maybe in a future release but that’s it.
