### ISSUE TITLE
Unreadable plot tooltip when having >15 accounts

### ISSUE THREAD

**Issue by carbolymer** [firefly-iii/firefly-iii#2375]
**Bug description**
I am running Firefly III version  4.7.17, and my problem is that plot legend is unreadable when having more than 15 accounts. 

**Steps to reproduce**
1. Create 15 asset accounts
2. Open dashboard

**Expected behavior**
All accounts are visible on the tooltip

**Actual behaviour**
16th and further ones are clipped. See screenshots below for example.

![Screenshot_2019-08-06_01-45-56](https://user-images.githubusercontent.com/228866/62501683-3ae8a200-b7ec-11e9-97c0-e672f89aeef4.png)

![2019-08-06-014540_5560x1920_scrot](https://user-images.githubusercontent.com/228866/62501687-3d4afc00-b7ec-11e9-826a-481b40d0fd78.png)

**Comment by JC5** [comment]
I can only suggest you limit the number of visible accounts in your preferences.
