### ISSUE TITLE
Use step plot on all plots

### ISSUE THREAD

**Issue by carbolymer** [firefly-iii/firefly-iii#2376]
**Bug description**
I am running Firefly III version  4.7.17, and my problem is that plots with splines are hard to interpret.

**Steps to reproduce**
Open dashboard with significant transfer on a single day.

**Actual behaviour**
Right now, a plot is composed of splines which present situation far from the truth. The transfer of €3000 occured on 6th of August, and that amount was available not earlier. The plot presents steady flow of cash from 5th of august, till the amount of €3000 accumulated on 6th of august, which is not the case!
![Screenshot_2019-08-06_02-01-28](https://user-images.githubusercontent.com/228866/62502185-5a80ca00-b7ee-11e9-9234-85a825b17b62.png)

**Expected behaviour**
Step plot is used with the jumps happening at the transfer moment. See `post` plot below:
![](https://matplotlib.org/3.1.1/_images/sphx_glr_step_demo_001.png)

**Comment by JC5** [comment]
Sorry, but I'm not going to change that. Step charts are ugly.

**Comment by carbolymer** [comment]
>Step charts are ugly.

I beg to differ. Spline charts bring no value and look cheap as hell. It would be better to use no interpolation at all than to use them. Step charts on the other hand present true account balance between data points. That's not only my opinion:

https://m.signalvnoise.com/lets-chart-stop-those-lying-line-charts/

https://peltiertech.com/smooth-talking-lies/

https://wmbriggs.com/post/195/

http://www.vizwiz.com/2011/12/when-you-use-smoothed-line-chart-your.html

You can leave a toggle in options for spline fanboys, but please, please, do not use them.

**Comment by JC5** [comment]
Meh.
