### ISSUE TITLE
Allow the possibility of having transactions with zero amount

### ISSUE THREAD

**Issue by mbacicc** [firefly-iii/firefly-iii#2378]
**Description**
Sometimes I have the need of storing  a transaction with zero amount. This happens usually for taxes payment, when there is excess or a reimbursement of taxes, I still want to have a placeholder transaction to remember that I managed that event and store an attachment and a text description.
At the moment it doesn't work, the transaction is not stored.

** current workaround**
At the moment I store a 0.01€ transaction from the web interface and then I edit it on the db to be 0.001€.

**Comment by JC5** [comment]
Sorry, but that's not going to be added.
