### ISSUE TITLE
Known issues in 4.8.0

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#2379]
I will update the replies below to notify you of any known issues in the new release of Firefly III.

If necessary, weekly releases will follow 4.8.0 to fix them. If you run into an issue that prevents you from using Firefly III, please revert back to the previous version and wait for an update.

**Known issues**

- The "new transaction"-form isn't translated.
- You can't drag and drop transactions.
- You can't clone transactions.
- You'll have to set up 2FA again.
- The environment variable names have changed. Check out [this file](https://github.com/firefly-iii/firefly-iii/blob/master/docker-variables.txt) for the correct names. The most notable changes are:
    - The `FF_` prefix has been dropped from all variables.
    - `DB_USER` has become `DB_USERNAME`
    - `DB_NAME` has become `DB_DATABASE`
- Creating a withdrawal with a _new_ expense account will not allow you to select a budget.
- #2405 Due date can't be edited.
- #2404 bad page indicator in the "no category" transaction overview.
- #2402 bad amounts in default report
- #2400 editing splits doesnt work in Opera.

**Fixed issues**
These issues will be fixed in the next release, 4.8.0.1, which will be available **Friday August 16th**.  If you don't want to wait, use the development version (`dev-master`) or `jc5x/firefly-iii:develop`

- Selecting or using tags in new transactions results in an error.
- #2384: When upgrading manually, you may see: `The command "generate-keys" does not exist.``
- #2385: When upgrading manually, the `firefly:verify` command may fail to run. You can safely run `firefly-iii:correct-database` instead, or skip the "verify"-command if you have previously executed  `firefly-iii:upgrade-database`.
- #2388: When registering as a new user, leaving the opening balance at 0 will give you an error.
- Editing a transaction with tags will drop the tags from the transaction.
- The balance box on the dashboard shows only negative numbers, skewing the results.
- #2397: Transfers are stored the wrong way around.
- #2395: Editing split transactions is broken.
- #2399: Not all account balances are updated after you create a new transaction.
- #2401: Could not delete a split from a split transaction.

**Comment by agilob** [comment]
I haven't change anything in my config, but latest release doesn't work:


> [Fri Aug 09 20:04:05.632432 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
> [Fri Aug 09 20:04:06.375593 2019] [php7:error] [pid 277] [client 192.168.1.1:1033] PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\C in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44
> [Fri Aug 09 20:04:06.376240 2019] [php7:error] [pid 277] [client 192.168.1.1:1033] PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\C in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44
> 192.168.1.1 - - [09/Aug/2019:20:04:06 +0000] "GET / HTTP/1.1" 500 211 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
```

**Comment by JC5** [comment]
This error indicates you're not setting an application key. Could you open a new issue so we can debug this?

**Comment by JC5** [comment]
An addition. The prefix "FF_" is no longer necessary for Docker environment variables.

**Comment by aelsenaar** [comment]
I have almost same issue with the latest docker image (4.8.0). Did not change any docker configuration.

> Now in entrypoint.sh for Firefly III,
Making directories...,
Touch DB file (if SQLlite)...,
Run chown on /var/www/firefly-iii/storage...,
Run chmod on /var/www/firefly-iii/storage...,
Remove log file...,
Dump auto load...,
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump,
Generated optimized autoload files containing 4923 classes,
Discover packages...,
,
In ServiceProvider.php line 236:,
                                                                               ,
  Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': N  ,
  o application encryption key has been specified.                             ,
                                                                               ,
,
Run various artisan commands...,
,
In ServiceProvider.php line 236:,
                                                                               ,
  Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': N  ,
  o application encryption key has been specified.                             ,
                                                                               ,
,

Can this also be related to the FF_ docker prefix?

**Comment by agilob** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2380

**Comment by JacksonHub** [comment]
I have lost my 2FA credentials after upgradeing from 4.7.17.6 to 4.8.0, while previous upgrading works fine on this.

**Comment by JC5** [comment]
Yes, this is documented in the changelog.

**Comment by aelsenaar** [comment]
When trying to edit a transaction with a tag the tag is not shown in the edit form. When I save the transaction the tag is removed from the transaction.

**Comment by tinloaf** [comment]
Has #2321 been fixed? Because I can't find it in the list of known bugs.

**Comment by JC5** [comment]
No. I can’t debug FinTS because there are no debug or trial websites for it. Every fix is a gamble. I’ve skipped it for this release.

**Comment by xpfgsyb** [comment]
If I want to create a new withdrawal and select an existing tag in the tags field I get an error when I try to submit the transaction:
MethodNotAllowedHttpException
The POST method is not supported for this route. Supported methods: GET, HEAD.
In RouteCollection.php line 256

If I type in a new value in the tags field the transaction is saved, but the tag isn't saved,

**Comment by JC5** [comment]
I see it, thanks.

**Comment by jwouda** [comment]
I still have problems connecting to the bunq bank, don't know if you will fix that? The error I get is:
_"Error! Use of undefined constant CURLOPT_PINNEDPUBLICKEY - assumed 'CURLOPT_PINNEDPUBLICKEY' (this will throw an Error in a future version of PHP)"_
My OS:  CentOS 7 + LAMP (7.2)

**Comment by JC5** [comment]
That’s an error in Bunq’s code I believe, not mine.

**Comment by JC5** [comment]
4.8.0.1 will be released in about one hour. Let's continue here:

https://github.com/firefly-iii/firefly-iii/issues/2407
