### ISSUE TITLE
password authentication failed for user "root"

### ISSUE THREAD

**Issue by vjFaLk** [firefly-iii/firefly-iii#2381]
**Bug description**
I'm getting this error on boot. Not sure why it's trying to use `root` even though I've specified the DB User using the new ENV Var naming scheme. Hope I'm not missing anything. 

**Steps to reproduce**
Upgrade Docker image to latest Firefly III and run it with existing postgres 10 docker image and database.

**Extra info**
Traceback - 
```
8/10/2019 1:56:10 AMIn Connection.php line 664:
8/10/2019 1:56:10 AM                                                                               
8/10/2019 1:56:10 AM  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "root"   
8/10/2019 1:56:10 AM  (SQL: select * from information_schema.tables where table_schema = public a  
8/10/2019 1:56:10 AM  nd table_name = migrations and table_type = 'BASE TABLE')                    
8/10/2019 1:56:10 AM                                                                               
```

```
ENV VARS - 


DB_HOST 	  |   | firefly-db
DB_CONNECTION |   | pgsql
DB_NAME		  |   | firefly
DB_USER 	  |   | firefly
DB_PASSWORD   |   | firefly


```

**Comment by Agraphie** [comment]
try DB_USERNAME instead of DB_USER

**Comment by JC5** [comment]
Yes, please see the top of the known issues list and #2380 for more information.

https://github.com/firefly-iii/firefly-iii/issues/2379

**Comment by vjFaLk** [comment]
Yep, that helped! Thanks!
