### ISSUE TITLE
[Reports] Percentage Column

### ISSUE THREAD

**Issue by scott-mcnulty** [firefly-iii/firefly-iii#2383]
**Description**

Would it be possible to add a percentage column for some of the generated reports? This would be useful for people who try to follow larger budget strategies like the 50/30/20 budget or 25% or income spent on rent

**Solution**

Add a percentage column in the generated reports

**What are alternatives?**

Haven't found one after searching the issues

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
Yes, that is certainly possible. I'm not sure yet where it would fit and what 100% should signify for example, but I'll take a look :+1:

**Comment by scott-mcnulty** [comment]
I only mocked this up by editing the site html directly in the budgets report but you'll get the idea.

![Screenshot from 2019-08-25 21-03-58](https://user-images.githubusercontent.com/8903363/63660430-0ed19880-c77c-11e9-8742-d76e18c4fc4a.png)

Could also have the percentage column in the accounts, average spending per account, and expenses (top 10) tables as well as display the percentage with the value in the hover tooltip on the pie charts

**Comment by JC5** [comment]
This will be fixed in the next release.
