### ISSUE TITLE
Add column Category to transaction overview

### ISSUE THREAD

**Issue by aelsenaar** [firefly-iii/firefly-iii#2389]
I am running Firefly III version 4.8.0

**Description**
Is it possible to add the column Category to the transaction overview again?

**Extra info**
Now I am unable to check (easy) which transactions are not categorized during the import (via the rules).

**Comment by JC5** [comment]
Absolutely. I'm not entirely happy yet with the view and I hope to improve it in the next release.

**Comment by aelsenaar** [comment]
Great!

**Comment by JC5** [comment]
This will be fixed in the next release.
