### ISSUE TITLE
Implement an API

### ISSUE THREAD

**Issue by sqrtroot** [firefly-iii/firefly-iii#239]
Hi there,

First of all love your project. 
I would like to know if you are considering building an API (preferably a json api) for this project? :)

sqrtroot

**Comment by JC5** [comment]
Thanks for the compliment!

I've considered it in the past, but I haven't made any substantial plans. It would be very useful to offer a (oAuth powered) API for applications, widgets and other things.

With the current lack of actual usage for such an API, it has a very low priority.

**Comment by tonicospinelli** [comment]
hummm REST API it would be awesome! It could help to develop mobile apps, desktop apps and also web app to hit api!

We could create a `FireflyIII\Http\Api\Controllers` namespace, adding a new `ApiRouteProvider` and migrate all in baby steps... I know it is a big monkey job, but it will help to grow up this project!

We can document API with swagger (because it creates API Client to a lot of languages) Take a look _Generate Client_ section at menu from [http://editor.swagger.io/#/](http://editor.swagger.io/#/)

Slowly, we can move all endpoints to hit API and we can do it for 4.0 milestone!

@JC5, I understand the low-priority, but what you think about? 😄 
@sqrtroot is it you think about API?

**Comment by JC5** [comment]
At the moment, adding an API would effectively make all the work required be twice as much. Any time the application changes, it would need to be fixed in the app AND in the API.

There are too many changes coming.

If you want to help, get test coverage going. The API will have to wait for a stable FF3.

**Comment by tonicospinelli** [comment]
ok @JC5 I will help you with code coverage 👍 

> There are too many changes coming.

What it means? Could you create a quick roadmap?

**Comment by JC5** [comment]
All issues are the road map 😆 

I'll write a detailed list soon. Also for test coverage.

**Comment by sqrtroot** [comment]
It might be an idea to create a nice roadmap and progress tracker on taiga.io

**Comment by tonicospinelli** [comment]
@JC5 😆  perfect!!!

@sqrtroot milestones linked with issues from github is perfect for that, I don't know third party tool is good for this project

**Comment by tonicospinelli** [comment]
@JC5 probably, this issue could be next major version? look like 4.0.0

**Comment by nekromoff** [comment]
If not API, could you please put documentation together, so e.g. anyone can extend you great app with custom transactions, rules etc. (or alternatively database tables' columns' description could help)

**Comment by JC5** [comment]
Writing documentation and help content is indeed on my todo list! And if you need help building something I'll help wherever I can.

Is there anything specific you had in mind, that you need information about?

**Comment by nekromoff** [comment]
Right now, I would just need a description on what function(s) to use to:
- add an expense or a revenue transaction
- add a bill
- create budget (or allocate an expense to a budget)

What I am trying to do is this situation:
I have two or three external systems that could push updates to Firefly III, e.g. transactions updates realtime from bank when they happen or bill payments etc.

I see much potential in Firefly III not only for tracking personal expenses, but also use it as a accouting software backend for a small company (basically acting as umbrella for external invoicing, banking reports etc.)

**Comment by JC5** [comment]
I'll start writing documentation, it should not be complex. It depends though, do you wish to use the web interface, or would you add stuff to the database directly?

Having said that, a description of tables and fields would be most useful first, I think.

**Comment by nekromoff** [comment]
Thanks for the answer! I would be doing it directly in the DB as an export
bridge from the other application.

Yes, description of the database tables would help.

**Comment by JC5** [comment]
Sounds good, I'll get started on the wiki on [this page](https://github.com/firefly-iii/help/wiki/database). When I have significant updates, I'll let you know!

**Comment by nekromoff** [comment]
Cool, thanks.

**Comment by nekromoff** [comment]
Well, I have been thinking about this. Actually, since there multiple cross-references in the tables, I would rather welcome particular functions to create transactions etc. that also take care of the journals and any other foreign keys (creation/ updates). Is that possible?

**Comment by nekromoff** [comment]
Hey, how is the documentation of the functions / DB going on? Thanks!

**Comment by kevinjon27** [comment]
is there any update for this? I think I want to implement an API access token.

**Comment by JC5** [comment]
It has no priority at the moment.

**Comment by JC5** [comment]
Guys: first basic API is now up (see the [docs](http://firefly-iii.readthedocs.io/en/latest/api/start.html)) so I'm closing this issue.

Please report bugs if you see them. Future versions of Firefly III will slowly expand the API's possibilities.
