### ISSUE TITLE
UnRaid Docker not working

### ISSUE THREAD

**Issue by JakeLadson** [firefly-iii/firefly-iii#2390]
**Bug description**
I am running Firefly III version 4.8.0 (:latest), and my problem is: when I try and open the container I get a 500 error, here are the log files:

`[Sat Aug 10 10:39:19.244623 2019] [php7:error] [pid 277] [client 192.168.1.110:49919] PHP Fatal error: Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\C in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44, referer: http://192.168.1.124/Docker`

**Steps to reproduce**
Upgrade to latest version on Community Apps 

**Expected behavior**
500 error will occur. 

Thanks!

**Comment by JC5** [comment]
Did you change the environment variables, as detailed in #2379 ?

**Comment by JakeLadson** [comment]
I've changed the variables and now I am getting a fatal error.

`
In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select `id`, `name`, `data`
from `configuration` where `name` = 4780_migrated_to_groups and `configura
tion`.`deleted_at` is null limit 1)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select `id`, `name`, `data`
from `configuration` where `name` = 4780_rename_account_meta and `configur
ation`.`deleted_at` is null limit 1)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `piggy_bank_e
vents`)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `link_types`
where `name` = Related and `link_types`.`deleted_at` is null limit 1)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select `users`.* from `user
s` order by `id` desc)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `transaction_
types` where `type` = Withdrawal and `transaction_types`.`deleted_at` is nu
ll limit 1)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select `data` from `account
_meta` where `name` = currency_id group by `data`)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select distinct `transactio
n_journals`.* from `transaction_journals` left join `transaction_types` on
`transaction_types`.`id` = `transaction_journals`.`transaction_type_id` lef
t join `budget_transaction_journal` on `transaction_journals`.`id` = `budge
t_transaction_journal`.`transaction_journal_id` where `transaction_types`.`
type` not in (Withdrawal) and `budget_transaction_journal`.`budget_id` is n
ot null and `transaction_journals`.`deleted_at` is null)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select `transaction_journal
_id`, SUM(amount) AS the_sum from `transactions` where `deleted_at` is null
group by `transaction_journal_id`)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select `transaction_journal
_id` from `transactions` where `amount` = 0 and `transactions`.`deleted_at`
is null)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select `transaction_journal
s`.`id` as `journal_id`, `transactions`.`id` as `transaction_id` from `tran
sactions` left join `transaction_journals` on `transactions`.`transaction_j
ournal_id` = `transaction_journals`.`id` where `transaction_journals`.`dele
ted_at` is not null and `transactions`.`deleted_at` is null and `transactio
ns`.`id` is not null and `transactions`.`deleted_at` is null)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select COUNT(transactions.t
ransaction_journal_id) as the_count, `transaction_journal_id` from `transac
tions` where `deleted_at` is null and `transactions`.`deleted_at` is null g
roup by `transactions`.`transaction_journal_id`)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select `transaction_group_i
d` from `transaction_journals` where `transaction_journals`.`deleted_at` is
null)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `transaction_
journals` where `transaction_journals`.`deleted_at` is null)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: update `journal_meta` set `
name` = original_source where `name` = original-source)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select distinct `budgets`.`
id`, `budgets`.`name`, `budgets`.`user_id`, `users`.`email` from `budgets`
left join `budget_transaction_journal` on `budgets`.`id` = `budget_transact
ion_journal`.`budget_id` left join `users` on `budgets`.`user_id` = `users`
.`id` where `budget_transaction_journal`.`budget_id` is null and `budgets`.
`deleted_at` is null and `budgets`.`deleted_at` is null)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused



In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: select `users`.* from `user
s` order by `id` desc)


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused


Encryption keys generated successfully.

In Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: insert into `oauth_clients`
(`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `passw
ord_client`, `revoked`, `updated_at`, `created_at`) values (?, Firefly III
Personal Access Client, qwDq2ywzjj9mYwXpZxcWr9zsSVk69h6kC3RbpFtA, http://lo
calhost, 1, 0, 0, 2019-08-10 12:03:12, 2019-08-10 12:03:12))


In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused


Application cache cleared!
+------------------------------------------------------------------------------+
| |
| Thank you for installing Firefly III, v4.8.0! |
| This is a huge upgrade for Firefly III. Please expect bugs and errors, and |
| bear with me as I fix them. I tested a lot of things but pretty sure I |
| missed some. Thanks for understanding. |
| |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
[Sat Aug 10 12:03:13.168788 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.2.21 OpenSSL/1.1.1c configured -- resuming normal operations
[Sat Aug 10 12:03:13.168841 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.1.110 - - [10/Aug/2019:12:04:47 -0500] "GET / HTTP/1.1" 500 2286 "http://192.168.1.124/Docker" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
192.168.1.110 - - [10/Aug/2019:12:04:47 -0500] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3731 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
192.168.1.110 - - [10/Aug/2019:12:04:47 -0500] "GET /fonts/lato-100.woff HTTP/1.1" 404 3731 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
192.168.1.110 - - [10/Aug/2019:12:04:47 -0500] "GET /favicon.ico HTTP/1.1" 200 12317 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"`

**Comment by JC5** [comment]
Is the database up and running?

**Comment by JakeLadson** [comment]
I'm sorry, I'm new to this. Yes the database is up and running.

**Comment by JC5** [comment]
OK. Stop and start the Firefly III container. The log files should show "wait-for-it.sh" results. In the output is the IP address of the database server.

Is this IP correct? Can you connect to the database yourself?

Whatever this is, it's misconfiguration so we have to try and find out where it is.

**Comment by JakeLadson** [comment]
The IP address is correct and I can connect to it.

**Comment by ben-nl** [comment]
I am on UnRaid myself and the docker Firefly III version 4.8.0 is running fine.
In the docker-template was the variable DB_HOST set with host and port.
I split this to DB_HOST (eg. 192.168.1.5) and DB_PORT (eg, 3306).
Maybe this will help.

**Comment by MstrDC** [comment]
Indeed, I also now splitup the host and port into 2 separate variables.
I also:
- removed all FF_ prefixes, 
- updated FF_DB_USER to DB_USERNAME
- updated FF_DB_NAME to DB_DATABASE
- updated FF_DB_HOST to DB_HOST and removed the port
- added DB_PORT variable

After this it seems to be working, but not sure my data is correctly displayed. Waiting for release with this fix: https://github.com/firefly-iii/firefly-iii/issues/2384

FYI: I also maintain the unraid docker template for firefly, so updated that as well now.
https://github.com/MstrDC/docker-templates/blob/master/firefly-iii.xml

**Comment by JakeLadson** [comment]
Thanks guys! Splitting into ip and port worked like a charm. 

My data is also displaying incorrectly so hopefully will be fix in the next update!

**Comment by JC5** [comment]
Open a ticket please, I can't magic the problem away if I don't know about it.

**Comment by JakeLadson** [comment]
I'm not entirely sure what the problem is. After looking though it looks like there was some issues with transfers. For example some switched source and destination account.

**Comment by JC5** [comment]
Ah yes, this happens with new transfers I believe: #2397 

Sorry about that.

**Comment by JakeLadson** [comment]
No problem. Should I fix the transactions or will they auto fix after the update?

**Comment by JC5** [comment]
You'll have to fix them yourself I'm afraid.
