### ISSUE TITLE
Docker ARM is out of date

### ISSUE THREAD

**Issue by agilob** [firefly-iii/firefly-iii#2391]
Docker for ARM is still on 4.7.17.6, while AMD64 is 4.8.0, causes crashes due to changes in database when accessing firefly via arm container.

**Comment by JC5** [comment]
Yes, the build didn’t finish. It works now and the script will be released with 4.8.0.1. Are you accessing the same database using two different versions of Firefly III? Otherwise it won’t matter.

**Comment by agilob** [comment]
Yes, I have a load balancer between backup raspberry pi and master amd64, they use the same database.

**Comment by JC5** [comment]
Then you'll have to wait until 4.8.0.1 or run the develop image on ARM.
