### ISSUE TITLE
ERROR: update firefly to latest Docker

### ISSUE THREAD

**Issue by karkaaa** [firefly-iii/firefly-iii#2394]
Hello,

i got error after firelfy latest update:

> [Sun Aug 11 09:28:36.648728 2019] [php7:error] [pid 277] [client 172.17.0.1:40156] PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\C in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44, referer: https://192.168.1.111/
[Sun Aug 11 09:28:36.649240 2019] [php7:error] [pid 277] [client 172.17.0.1:40156] PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\C in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44, referer: https://192.168.1.111/
172.17.0.1 - - [11/Aug/2019:09:28:36 +0300] "GET / HTTP/1.1" 500 211 "https://192.168.1.111/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

Docker version 19.03.1
"Ubuntu 18.04.3 LTS"

**Comment by JC5** [comment]
Did you read #2379 and update the Docker variable names?

**Comment by karkaaa** [comment]
i run:

> docker run -d \
> --name=firefly_iii_app \
> --link=firefly_iii_db \
> --restart unless-stopped \
> --restart=always \
> -e FF_DB_HOST=firefly_iii_db \
> -e FF_DB_CONNECTION=pgsql \
> -e FF_DB_NAME=name \
> -e FF_DB_USER=name \
> -e FF_DB_PASSWORD=pass \
> -e FF_APP_KEY=ksksdad3242kj24kjr2kjDF \
> -e APP_URL=https://sub.domain.com \
> -e TRUSTED_PROXIES=** \
> -e FF_APP_ENV=local \
> -p 80:80 \
> -v firefly_iii_export:/mnt/sdb1/docker/firefly/storage/export \
> -v firefly_iii_upload:/mnt/sdb1/docker/firefly/storage/upload \
> jc5x/firefly-iii



> docker run -d \
> --name=firefly_iii_db \
> --restart unless-stopped \
> --restart=always \
> -e POSTGRES_PASSWORD=pass \
> -e POSTGRES_USER=name \
> -v firefly_iii_db:/var/lib/postgresql/data \
> postgres:10

**Comment by JC5** [comment]
So no. Please read #2379, the [documentation](http://docs.firefly-iii.org/en/latest/installation/upgrading.html) and come back to me if you have questions.

**Comment by karkaaa** [comment]
how can install previous version?

**Comment by korzq** [comment]
you just use an older docker image.

**Comment by karkaaa** [comment]
how can use?

**Comment by korzq** [comment]
docker <your usual stuff>  jc5x/firefly-iii:<tag here>
Ex. docker run  jc5x/firefly-iii:release-4.7.17.3

See tags at https://hub.docker.com/r/jc5x/firefly-iii/tags

**Comment by karkaaa** [comment]
thx
