### ISSUE TITLE
Transfer to credit card is incorrectly calculated?

### ISSUE THREAD

**Issue by agilob** [firefly-iii/firefly-iii#2397]
**Bug description**
I am running Firefly III version 4.8.0, and my problem is:

When CC account has -300 and I make a transfer of 700 from debit account to CC account (+700 on CC) state of CC is now -1000

![Screenshot_20190811_153509](https://user-images.githubusercontent.com/2544251/62835251-e1e69700-bc4d-11e9-8bab-c0acf48f266c.png)

![Screenshot_20190811_153559](https://user-images.githubusercontent.com/2544251/62835250-e14e0080-bc4d-11e9-9947-dbf7a8b5262e.png)

**Expected behavior**
Credit card should have positive balance, not negative.

**Comment by JC5** [comment]
Confirmed, unfortunately. I fixed a bug in the import routine and I introduced another one. Thanks for letting me know.

**Comment by agilob** [comment]
Seems like this also affects other transfers, my savings are now negative as well :(

**Comment by agilob** [comment]
Will a fix require any DB operation or is it just software?

**Comment by JC5** [comment]
All my previously generated transfers are correct.

**Comment by agilob** [comment]
does that mean I shouldn't store any transfers now until fix?

**Comment by JC5** [comment]
Yes.

**Comment by JC5** [comment]
I found the issue and it'll be fixed in 4.8.0.1, which should be available next Friday.

**Comment by agilob** [comment]
This is critical enough that it should be addresses in a hot-fix release asap.

**Comment by JC5** [comment]
I won't push out a hotfix just like that. I won't object to bringing the release of the new version forward of course. Stay tuned.
