### ISSUE TITLE
Accounts with have different balances deepening on page

### ISSUE THREAD

**Issue by JakeLadson** [firefly-iii/firefly-iii#2398]
**Bug description**
I am running Firefly III version 4.8.0, and my problem is: Depending on what page you are on it will show different balances for accounts.

This is the balance on the account page (correct balance):
![image](https://user-images.githubusercontent.com/26978529/62836725-c8ccee80-bc2b-11e9-8cee-bec369a8bb2d.png)

This is the balance on the home page and asset account page are showing 837.30
![image](https://user-images.githubusercontent.com/26978529/62836741-f6199c80-bc2b-11e9-8099-46c5c87cbe42.png)

This is a problem with the 2 "main" accounts I use, the accounts with only a few transactions a month are displaying correctly.

**Comment by JC5** [comment]
Could you browse to `/flush` to clear your cache? The two pages use the same logic to calculate the amounts.

**Comment by JakeLadson** [comment]
Worked like a charm!

**Comment by JC5** [comment]
Glad to hear it 😅 . There is a related bug (see #2399) which has the same cause.
