### ISSUE TITLE
New withdrawal not reflected in balance calculation

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2399]
I am running Firefly III version 4.8.0. 

After creating a new withdrawal transaction, the balance is not correctly recalculated on the Asset Accounts page, or the account's balance graph. 

If I edit the transaction and save it, it's correctly calculated on all pages.

**Comment by JC5** [comment]
When you say it's incorrect. Is the amount missing or is a different amount calculated?

**Comment by hamfactorial** [comment]
I will provide some screenshots later, if necessary. I'm on my mobile phone now, not the most user-friendly input method.

**Comment by hamfactorial** [comment]
The amount is not calculated. The balance is the same before and after the withdrawal entry.

**Comment by JC5** [comment]
OK. Probably a cache thing. Should be an easy fix.

**Comment by JC5** [comment]
You can always browse to /flush to manually flush the cache. A fix will be released next week (see #2379)

**Comment by hamfactorial** [comment]
Excellent, thank you. Confirmed that using /flush displays the correct balance.

**Comment by 4oo4** [comment]
I think this might be related, right after upgrading I saw that trying to calculate the balance when setting the timeframe to last 30 days took an extremely long time. However the `/flush` URL fixed this for me too.

![Selection_008](https://user-images.githubusercontent.com/15698835/62838785-3733a000-bc70-11e9-9f8e-881f31d99d42.png)
