### ISSUE TITLE
Problem in add split in edit already splitted transaction

### ISSUE THREAD

**Issue by fvezzoli** [firefly-iii/firefly-iii#2400]
**Bug description**
I am running Firefly III version 4.8.0.
If I add new split in the splitted transaction the already present split is duplicate and is impossible to remove.

**Steps to reproduce**

1. Add new splitted transaction with two part
2. After save this edit the transaction and add one new part
3. Select the control to return on same page to edit
4. Save the modification

**Expected behavior**
The transaction part is 3 and in the transaction show and account list is correctly listed.
Now in the first edit page access is 3 but if I return in the page is 5, the first two part is duplicated.

**Extra info**
I use opera on Ubuntu Linux system.

**Bonus points**

**Comment by JC5** [comment]
I'll have to test this in Opera because it works fine in Firefox

**Comment by JC5** [comment]
I'm sorry, this works as expected on Opera/Mac.

**Comment by fvezzoli** [comment]
The problem is on update from previous version.
I think all javascript is loaded correctly, but after some try all work correctly.

I see when an update is made the javascript is not updated at first reload, but after the complete page reload.
I think is a Opera cache problem, on Firefox and Chrome works correctly.
