### ISSUE TITLE
Impossible to remove part in splitted transaction

### ISSUE THREAD

**Issue by fvezzoli** [firefly-iii/firefly-iii#2401]
**Bug description**
I am running Firefly III version 4.8.0, and my problem is:
when edit transaction is impossible to remove a part of splitted transaction

**Steps to reproduce**
1. Create a transaction with more than 2 part
2. Save the transaction
3. Enter to edit the transaction
4. Remove one of the part of transaction

**Expected behavior**
The deleted transaction is removed.

**Extra info**
I use Opera on Ubuntu Linux system

**Bonus points**

**Comment by JC5** [comment]
Nice find, fixed.
