### ISSUE TITLE
income balance is negative

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2402]
Hello :-)

Since 4.8.0, my income is negative.

![image](https://user-images.githubusercontent.com/1318140/62838781-f09a7180-bc80-11e9-8066-f10ab67b3738.png)

I already tried to flush.
I tried to delete and recreate the transaction too.

It's the same if I go back in time and check other period.

**Comment by jlauwers** [comment]
Should have tested the develop branch before posting.
It's working with the latest docker:develop

**Comment by jlauwers** [comment]
I should go sleep...
It's seems to be fixed but not everywhere (not in the screenshot)
I will try to post more details tomorrow.

**Comment by JC5** [comment]
It's a bug, thanks for reporting!

**Comment by agilob** [comment]
Duplicate of https://github.com/firefly-iii/firefly-iii/issues/2397

**Comment by JC5** [comment]
I think this is a different issue, it's something in the default report.

**Comment by JC5** [comment]
Fixed in the next release.
