### ISSUE TITLE
Subcategories

### ISSUE THREAD

**Issue by corch1988** [firefly-iii/firefly-iii#2403]
It would be awesome to categorize certain expenses or incomes in subcategories.
For example:
```
{
   category: "food",
   total: "60$",
    subcategories: {
        {category: "Beverages", total: "20$"},
        {category: "Sweets", total: "10$"},
        {category: "Fruits:", total: "30$"}   
     }
}
```

**Comment by Sotam** [comment]
I think that tags are appropriate for this situation.

**Comment by JC5** [comment]
http://docs.firefly-iii.org/en/latest/support/features.html#often-requested-features
