### ISSUE TITLE
Page indicator 1 page behind

### ISSUE THREAD

**Issue by spockster1985** [firefly-iii/firefly-iii#2404]
When you go to the overview list of all transactions in a category and it has multiple pages. If you click on page 2, it will bring you to page 2. But the page indicator is still indicating page 1. If you go to page 3, the indicator will have page 2 higlighted.

![Firefly](https://user-images.githubusercontent.com/50197737/62849281-4c93e300-bcdf-11e9-9b56-1b9735a8f107.jpg)

**Comment by JC5** [comment]
Thanks, duly noted!

**Comment by JC5** [comment]
This is fixed in the next release.
