### ISSUE TITLE
Not show due date in edit transaction

### ISSUE THREAD

**Issue by andersonrosilva** [firefly-iii/firefly-iii#2405]
**Bug description**
I am running Firefly III version 4.8.0, and my problem is:
When I edit a split transaction and each split has a due date, it is not displayed again on the edit screen.

**Steps to reproduce**
Create a transaction with more than 2 parts
Save the transaction
Enter to edit transaction

**Expected behavior**
Display due dates.

**Extra info**

**Bonus points**
I use Chrome on Windows 10 system

![split-1](https://user-images.githubusercontent.com/4675914/62868775-c54d6c00-bcec-11e9-9c98-b212475d8ce9.png)
![split-2](https://user-images.githubusercontent.com/4675914/62868776-c54d6c00-bcec-11e9-9526-29ccbec39427.png)

-->

**Comment by JC5** [comment]
Thanks, I'll pick it up!

**Comment by JC5** [comment]
Should be fixed in the next release.
