### ISSUE TITLE
Cannot link transactions

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#2410]
I am running Firefly III version , and my problem is:

Issue on versions 4.8.0 and 4.8.0.1: I cannot link two transactions (two revenues but I do not think this is relevant).

If I try to link revenue ID 2658 with revenue ID 2659, I am redirected to https://xxx.xxx.xx/transactions/show/3142 (which, in my case, is a 404), failing to link the two transactions. On the form, "Selected transaction" is empty.

**Comment by JC5** [comment]
Did you find your transaction in the dropdown, and did you click it to confirm the link, so the "selected transaction" is filled in?

http://docs.firefly-iii.org/en/latest/advanced/links.html

**Comment by lucavallerini** [comment]
No, I usually insert the transaction ID and confirm the form, probably I have to change that habit.

Anyway, there is an issue with the transaction ID I think. In fact, transaction ID 2659 does not exist under the dropdown, however, searching for its description results in that same transaction but with ID 3143. The "show" pages works with IDs 2658 and 2659 but not with 3143 (404).

**Comment by JC5** [comment]
I see what you mean. It's mixing up the ID's for the groups and the journals themselves.

Single transactions (unsplit) have two ID's, 1 for the group and 1 for the journal.

Split transactions have 1+_n_ ID's. 1 for the group and _n_ ID's for each journal (=split).

That could be confusing, I'll change the description of the items in the dropdown.

**Comment by JC5** [comment]
This will be fixed in the next release.
