### ISSUE TITLE
Tags ind split transactions

### ISSUE THREAD

**Issue by corch1988** [firefly-iii/firefly-iii#2413]
It woul be awesome when splitting a transaction to not just categorize the single elements but to tag them too.

**Comment by lucavallerini** [comment]
You can in the latest versions, 4.8.x

**Comment by corch1988** [comment]
Thanks.
Trying to update the docker container.

So far receiving error "Uncaught RuntimeException: No application encryption key has been specified." even though "FF_APP_KEY" is set with the correct key.

**Comment by lucavallerini** [comment]
The new version is a big one, you should read here #2407

**Comment by corch1988** [comment]
Thank you! =)
