### ISSUE TITLE
Transaction form disappear when 'Reset form after submission' is checked

### ISSUE THREAD

**Issue by spockster1985** [firefly-iii/firefly-iii#2415]
**Bug description**
I am running Firefly III version 4.8.0.1, and my problem is:
The transaction form disappears when you check both 'After storing, return here to create another one.' and 'Reset form after submission'

**Steps to reproduce**
Create a transfer, check both checkboxes and press submit. The transaction form will now disapear.

**Expected behavior**
An empty transaction form

![FireflyIII](https://user-images.githubusercontent.com/50197737/62923235-9c40e000-bdad-11e9-94af-4779a16f438c.jpg)

**Comment by JC5** [comment]
Found it, will be fixed.
