### ISSUE TITLE
Transaction Deposit Entry Goes to Withdrawal Entry

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#2416]
Version 4.8.0.1 and Dev.

From Income entry page "/transactions/deposit" (and also transfers) the button to add a new transaction directs to "/transactions/create/withdrawal"

------- Also using the right side menu I get to the "transactions/create/deposit" but the source and destination both only show my asset accounts as drop down options only no revenue accounts listed

**Comment by JC5** [comment]
1. Good point, I'll fix that.
2. If you start typing more suggestions will come up.
