### ISSUE TITLE
wrong values in report

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2418]
Hi again.
I can see now the income as positive... (from #2402) but the values are wrong. (that was the case before... Maybe I should have started with that...)

Shouldn't the difference be equal in the next screenshot?
(The data from the left seems to be the right values)

![image](https://user-images.githubusercontent.com/1318140/62968567-9aa60500-be0b-11e9-8f19-3bd99423bf3a.png)

Same in the graph from /reports/default/allAssetAccounts/currentYearStart/currentYearEnd

**Comment by JC5** [comment]
I think they should be but I have to double check it. Stay tuned.

**Comment by jlauwers** [comment]
I think I understand the issue.
In the "Revenue / income" panel, we can see the destination account and not the source account.
(we should see my employer's account and we see my back account)

And as #2402, I think the transaction is read in the wrong way.

It doesn't seem the same for Expenses but the values are also wrong.
![image](https://user-images.githubusercontent.com/1318140/62999010-70852f00-be6d-11e9-87b0-5a3506fe1725.png)
![image](https://user-images.githubusercontent.com/1318140/62999079-9ad6ec80-be6d-11e9-8daf-cb2124198823.png)
The reports thinks I spent 444.54€ (no idea where it comes from) at amazon and when I go in the details, I realy spent way more.

**Comment by jlauwers** [comment]
Maybe it should be group by source here?
https://github.com/firefly-iii/firefly-iii/blob/81cc138700acf0fc8d1c9f3422c1be2ecd35de35/app/Repositories/Account/AccountTasker.php#L173

**Comment by jlauwers** [comment]
Can confirm it works for income but not for expense. Should I open a new issue?

**Comment by jlauwers** [comment]
The income part is working but not the expense part.
