### ISSUE TITLE
Cannot make an authenticated request via curl

### ISSUE THREAD

**Issue by BennyLi** [firefly-iii/firefly-iii#2419]
I am running Firefly III version 4.7.17

**Description**
I'm trying to use the API via curl. Got the TOKEN via /oauth/token with this command:

```
token="$(curl --silent --data 'grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$SECRET&scopes=*' $SERVER/oauth/token | jq --raw-output .access_token)"
```

After that I tried to do a request with this token via
```
curl --silent -H "Accept: application/json" -H "Authorization: Bearer $token" $SERVER/api/v1/about/user | jq
```

But I always get this response:
```
{
  "message": "Unauthenticated",
  "exception": "AuthenticationException"
}
```

Any advice?

**Comment by BennyLi** [comment]
Just tested it with the demo site with this script:

```
bin/sh                                                                                                                           # Requirements                                                    # * [jq](https://github.com/stedolan/jq)                                                                                                                                                              SERVER="https://demo.firefly-iii.org"                             CLIENT_ID="2"                                                     CLIENT_SECRET="tfWoJQbmV88Fxej1ysAPIxFireflyIIIApiToken"          
token="$(curl --silent -H "Accept: application/json" --data "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&scope=*" $SERVER/oauth/token | jq --raw-output .access_token)"                                                                                                                               echo $token                                                                                                                         curl --silent -H "Accept: application/json" -H "Authorization: Bearer $token" $SERVER/api/v1/about
```

Just the same error...

**Comment by JC5** [comment]
I'm pretty sure there's an approval step somewhere before this works.

**Comment by BennyLi** [comment]
I don't think so. But digging deeper it looks like firefly does not yet include the `CheckClientCredentials` middleware.

See [Laravel Passport Docs](https://laravel.com/docs/5.8/passport#client-credentials-grant-tokens) and [/app/Http/Kernel.php#](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Kernel.php#L210)

Any chance you add this? 
Or can you please guide me another way of interacting via `curl` with your API?

**Comment by JC5** [comment]
Thanks, I had the time to dive into this. I'll make sure the middleware is added.

**Comment by JC5** [comment]
I can't get Laravel to recognize the user from the Bearer token, if the Bearer has been requested using your method. The CheckClientCredentials will only verify that the Bearer token is valid, but it won't return user information. 

Without it, this won't fly. You'll have to use the  Personal Access Tokens that are available in the /profile to use the API in this fashion/
