### ISSUE TITLE
while importing from .cvs it doesnt map date from csv instead shows date and time of import

### ISSUE THREAD

**Issue by shindocha** [firefly-iii/firefly-iii#2420]
I am running Firefly III version 4.8.0.1Firefly III
Description
while importing from .cvs it doesn’t map date from entries from cvs file instead it shows date and time of import, so all my imported transactions are for same date which is date of import. Tired with and without 'map the values' options too.
Extra info
Tired few other versions and its the same, also tried previous config file for import which use to work before my home datacentre 🔥 ⬇️ since rebuilt I am not able to use the app because of this import issue from CVS.
Specter api works fine but there is no option to choose what fields to import /map as they categorise the data on their database and then allows us to import it which messes up with user defined categories.
Bonus points
 
•	Add a screenshot - Done 😃
:nothingwashere:
:heretoo:
•	Replicate the problem on the demo site https://demo.firefly-iii.org/ - Cant Import on demo site
•	Remember the human 🤜
-->

**Comment by JC5** [comment]
Could you verify that the date format you have configured is correct for the file you’re trying to import?

**Comment by shindocha** [comment]
dmY On 14 Aug 2019 5:01 am, James Cole <notifications@github.com> wrote:Could you verify that the date format you have configured is correct for the file you’re trying to import?
