### ISSUE TITLE
Artisan error on docker

### ISSUE THREAD

**Issue by luismanson** [firefly-iii/firefly-iii#2421]
Hello, I'm using a composer file (see bellow) bundled in HomelabOS to run Firefly, 
But im unable to make it run. This is what the log has near the error:

```
firefly_iii_app_1  | Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
firefly_iii_app_1  | Discover packages...
firefly_iii_app_1  |
firefly_iii_app_1  | In ServiceProvider.php line 236:
firefly_iii_app_1  |
firefly_iii_app_1  |   Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
firefly_iii_app_1  |
firefly_iii_app_1  | Run various artisan commands...
firefly_iii_app_1  | In ServiceProvider.php line 236:

```

Also had problems running the commands manually:
```
root@645469115a44:/var/www/firefly-iii# composer dump-autoload
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 4938 classes
root@645469115a44:/var/www/firefly-iii# php artisan package:discover

In ServiceProvider.php line 236:

  Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': The only supported ciphers are AES-128
  -CBC and AES-256-CBC with the correct key lengths.

```

The original composer file did not work, I've fixe it renaming the variables 
 according to #2407. I saw no .env or .local, coping env.example, didn't make help either.

Reference file: https://gitlab.com/NickBusey/HomelabOS/blob/dev/roles/firefly_iii/templates/docker-compose.firefly_iii.yml.j2

Relevant part of the generated composer file:
```
    environment:
      - DB_HOST=firefly_iii_db
      - DB_NAME=firefly_db
      - DB_USER=firefly_db
      - DB_PASSWORD=86808675205100019279
      - APP_KEY=975556911235702981524738131XXXX
      - APP_ENV=local
      - APP_URL=https://money.CloudPriv.luisd.xyz
      - TZ=America/Argentina/Buenos_Aires
      - ServerName=money.CloudPriv.luisd.xyz
    image: jc5x/firefly-iii

```

**Comment by JC5** [comment]
The correct length for the app key is 32 characters, not 31. Is your key of the correct length?

**Comment by luismanson** [comment]
> The correct length for the app key is 32 characters, not 31. Is your key of the correct length?

Yes, I've verified and its 32 chars long, (i had edited it wrong here)

**Comment by JC5** [comment]
Please double check the DB variables, and tell me what happens.

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD=secret_firefly_password
```

See DB_NAME and DB_USER in your file

**Comment by JC5** [comment]
Can you share the following info with me?

```
php -v
```

And
```
php -i > info.txt
```

Info.txt may contain system info so drop it in my email.

**Comment by luismanson** [comment]
I've mailed you a pastebin link with the requested information
```
luis@CloudPriv:~$ sudo docker exec -it 589ed6e08217 php -v
[sudo] password for luis: 
PHP 7.2.21 (cli) (built: Aug  2 2019 06:45:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.21, Copyright (c) 1999-2018, by Zend Technologies

```
MySQL is runing,login works with the same data posted above, the database is empty.

**Comment by luismanson** [comment]
> The correct length for the app key is 32 characters, not 31. Is your key of the correct length?

I've finally spotted the error. I apologize.

**Comment by JC5** [comment]
Not a problem, I'm glad it's fixed! :+1:
