### ISSUE TITLE
Autocomplete + tab key

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2424]
I'm not sure if It's a bug or a feature ;-)

When I create a new transaction, I can't press tab to autocomplete only enter works.

**Comment by JC5** [comment]
I'll have to check the library I use. For now, I'll classify it as a bug.

**Comment by LipuFei** [comment]
Hi, I also found that the tags field seems to have the same issue. Although it sometimes shows auto-complete entries in the tags field, it doesn't seem to show a full list.

**Comment by JC5** [comment]
The list is never full, the search is limited.

The tab is not picked up by the library, so you (and I) will have to learn to live with it.
