### ISSUE TITLE
Hit enter in transaction creates a split by default

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2425]
Shouldn't enter submit the transaction by default instead of create a split?

**Comment by lucavallerini** [comment]
And if you hit enter a second time, the split is removed.

**Comment by jlauwers** [comment]
> And if you hit enter a second time, the split is removed.

I'd even say that the whole form is reset.

**Comment by JC5** [comment]
It should yes. I'll pick it up as a bug.

**Comment by JC5** [comment]
Will be fixed in the next release.
