### ISSUE TITLE
docker-compose config env db host mismatch

### ISSUE THREAD

**Issue by jakesmolka** [firefly-iii/firefly-iii#2426]
**Bug description**
I am running Firefly III version 4.8.0.1 (docker jc5x/firefly-iii:develop), and my problem is:

Given the description from [your docker documentation](https://firefly-iii.readthedocs.io/en/latest/installation/docker.html#docker-hub-with-automatic-updates-via-docker-compose), which links to [docker-compose.yml](https://raw.githubusercontent.com/firefly-iii/firefly-iii/master/docker-compose.yml) and [this .env](https://raw.githubusercontent.com/firefly-iii/firefly-iii/master/docker-variables.txt) I had problems with the docker internal connection:

Several errors like the following appeared 

```
firefly_iii_app_1  | In Connection.php line 664:
firefly_iii_app_1  |                                                                                
firefly_iii_app_1  |   SQLSTATE[08006] [7] could not connect to server: Connection refused          
firefly_iii_app_1  |    Is the server running on host "127.0.0.1" and accepting                     
firefly_iii_app_1  |    TCP/IP connections on port 5432? (SQL: select * from information_schema.ta  
firefly_iii_app_1  |   bles where table_schema = public and table_name = migrations and table_type  
firefly_iii_app_1  |    = 'BASE TABLE')     
```

So I had to modify the following `.env` entry to make it work out of the box:

`DB_HOST=127.0.0.1` to `DB_HOST=firefly_iii_db`

I don't know if this `.env` is also linked in different contexts and therefore needs to stay with `127.0.0.1` but if not I think changing it to the correct value would help new users to get it running.

**Steps to reproduce**
Setup the docker-compose setup as described in the documentation and run `docker-compose up`

**Expected behavior**
Working out of the box, since it is an official example.

Another question I'm not sure of: The documentation states also that the initialization of the DB is necessary after making the general docker-compose setup run. But taking a look at the docker logs, they suggest the artisan commands are run by the app on its own. So should this paragraph be removed from the docs?

Thanks for your work!

**Comment by JC5** [comment]
I'll change the documentation, since the file is used in other places as well, AND I've added an instruction in the file itself. Thanks for letting me know!
