### ISSUE TITLE
Transaction Page: Source and Destination Account Entry Box - Auto-complete Dialog

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2427]
**Bug description**
I am running Firefly III version 4.8.0.1.

I created several accounts named "test" or similar, to debug an old issue.  After the bug was fixed, I deleted the accounts.  Since 4.8.0, these accounts are now appearing in the "Source Account" and "Destination Account" auto-complete boxes.

In addition, "Initial Balance Account of [NAME]" appears in the same auto-complete dialog for all accounts.

I think these should be excluded from the displayed options.

**Comment by JC5** [comment]
Yes, they are cached by your browser in the Local Storage. There's not much I can do I'm afraid.

**Comment by hamfactorial** [comment]
Are you sure?  I opened a private browsing window on another computer, but I still see the accounts.  I'm not talking about the "auto-fill" feature that Chrome and Firefox offer, but the dropdown menu native to Firefly. 

This is the same place where the "Initial Balance Account [...]" entries appear, and I've never entered that value by hand in a transaction entry page.

![2019-08-14_105852](https://user-images.githubusercontent.com/39804831/63044660-8867ad80-be83-11e9-80cc-445069ca38cb.png)

**Comment by JC5** [comment]
Ah yes, now I see. These entries will disappear in 4.8.0.2. :)

**Comment by hamfactorial** [comment]
Thank you sir!
