### ISSUE TITLE
Report issues

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2428]
Some stuff are still wrong in the reports but some stuff are fixed in #2418 so I made a new issue with what's left.

In /reports/default/allAssetAccounts/currentYearStart/currentYearEnd

- Both top graphs are inverted (income is negative and expense is positive)

- In the expenses list, total by account is only taking the last month even if the whole year is selected. (same for the sum and out in "Income vs. expenses"

- In Budgets; It shows 0€ for month that I have data for

- In Categories (Expenses); It shows 0€ for month that I have data for

- In Categories (Revenue / income); It shows 0€ for month that I have data for

**Comment by JC5** [comment]
Thanks. I know the root cause. I am going over each box to fix them, and make sure they're multi-currency as well.

**Comment by JC5** [comment]
* Chart is now fixed.
* Sums are also fixed.
* Fixed.
* Fixed.
* Fixed.

Build is running, code is in `develop`.

**Comment by jlauwers** [comment]
Perfect ! Thanks 😁
