### ISSUE TITLE
Cannot create recurring transaction

### ISSUE THREAD

**Issue by tgkenney** [firefly-iii/firefly-iii#2431]
**Bug description**
I am running Firefly III version 4.0.8.1 (docker container), and my problem is:

I cannot create a recurring transaction.  After filling out the form and hitting store, I get the following error and the transaction is not stored.

![image](https://user-images.githubusercontent.com/48830958/63138374-484e1b00-bfa8-11e9-85b7-066884f381db.png)

**Steps to reproduce**

Create a new recurring transaction, fill out the form, and hit store

**Expected behavior**

The transaction should be stored

**Extra info**

The error might have something to do with the form itself.  In the screenshot below, you can see both source and destination accounts are listed twice, and the options in each drop-down don't really seem to match what should be there.
![image](https://user-images.githubusercontent.com/48830958/63138339-1d63c700-bfa8-11e9-9986-cc878ace64c9.png)

The logs from the docker container seem to indicate it is being POST-ed but nothing appears on that page or in the database
`10.30.0.4 - - [16/Aug/2019:01:58:21 +0000] "POST /recurring/store HTTP/1.0" 500 4651 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"`

**Comment by JC5** [comment]
This is related to #2414 and will be fixed in the next release.
