### ISSUE TITLE
Defaults to Euro on new, and edit transaction 

### ISSUE THREAD

**Issue by s1mpleman** [firefly-iii/firefly-iii#2432]
**Bug description**
I am running Firefly III version  4.8.0.1, and my problem is:

Creating new and editing old transcations default to Euro, when in the settings it's set to Great British Pounds as default and Euro is active. 
![image](https://user-images.githubusercontent.com/5730731/63142046-16f14180-bfe0-11e9-9f63-5e5afc0afa2f.png)

**Steps to reproduce**
Create a new transaction or Edit an old one. 
![image](https://user-images.githubusercontent.com/5730731/63142031-05a83500-bfe0-11e9-9830-5ea7c8a23a25.png)

**Expected behavior**
To have the box default to the Great British Pounds as set in settings. 

**Extra info**
I don't know if this is related soley to the update or not, whereas I didn't have this behaviour before I now have some oddity where I can't disable Euro's from the currency menu as I get an error saying it's still in use. 

**Bonus points**

**Comment by JC5** [comment]
The box is in EUR because the "foreign amount" would the in Euro. The normal amount will be stored in GBP. Just select one of your checking account in the "Source account" box and you'll see it update correctly.

**Comment by JC5** [comment]
I'll check out what happens with the foreign currencies.

**Comment by s1mpleman** [comment]
Ahhh! Thanks for the explanation man, was a little confusing that box but your right. The box doesn't change it pops up above with British Pounds. Cheers for the help :D

**Comment by JC5** [comment]
This should be fixed in the next release.

**Comment by s1mpleman** [comment]
Sweet as man thanks!
