### ISSUE TITLE
Editing the "Initial balance for X" transaction fails without saying why

### ISSUE THREAD

**Issue by jahabrewer** [firefly-iii/firefly-iii#2434]
**Bug description**
I am running Firefly III version 4.8.0.1, and my problem is:

I'm just starting to use firefly. I wanted to change the date on the initial transaction for an account and tried to do so by editing the transaction instead of editing the account. Editing the initial transaction failed, and I got the "Error! There was something wrong with your submission. Please check out the errors below." banner. There was no additional information below.

I opened up dev tools and saw that the request failed with response `{"message":"The given data was invalid.","errors":{"transactions.0.type":["The selected transactions.0.type is invalid."]}}`

**Steps to reproduce**
Try to edit the initial transaction of an account.

**Expected behavior**
It looks like when you want to modify the initial transaction (like, date or amount), you should do that by editing the account. I'm not suggesting that should change, just that attempting to edit the transaction should tell you why you can't edit it (or disable the edit button for it).

**Extra info**
Windows 10, Firefox 68.0.1

Debug information generated at 2019-08-16 13:41:57 America/Los_Angeles for Firefly III version **4.8.0.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.1 |
| FF API version | 0.10.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.21 |
| Display errors | Off |
| Session start | 2019-08-01 00:00:00 |
| Session end | 2019-08-31 23:59:59 |
| Session first | 2019-01-08 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

![image](https://user-images.githubusercontent.com/857884/63197223-12527a80-c02c-11e9-8633-647c65dd76a8.png)

**Comment by JC5** [comment]
This is something that I forgot to disable in 4.8.0. Thanks for letting me know :)

**Comment by JC5** [comment]
Will be fixed in the next release.
