### ISSUE TITLE
Question: Deprecated import routines

### ISSUE THREAD

**Issue by AndreiGavriliu** [firefly-iii/firefly-iii#2435]
Hi,

According to the 4.8.0 release notes, you are planning to remove the import routines: https://github.com/firefly-iii/firefly-iii/blob/master/changelog.md#deprecated

Will this include the CLI import funtions aswell? Should I start updating my scripts to import via the API?

If so, will I be able to bulk import multiple entries and trigger the imported transactions email?

Thanks again for your dedication!

**Comment by JC5** [comment]
Yes, but no worries yet. I will replace first, and deprecate later.

For the CSV import routine for example, I plan to build a dedicate Lumen app. That app would have some basic variables to set using the `.env` file (Firefly III location, API key), and feature both the import routine over the command line _and_ the web-interface. Just nothing else.

Once that's finished and working, I'll start removing the import routine from Firefly III.
