### ISSUE TITLE
 Known issues in 4.8.0.2

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#2436]
**Recap**
- Firefly III v4.8.0 has been released on August 9th. See also #2379
- Firefly III v4.8.0.1 has been released on August 12th. See also #2407
- Firefly III v4.8.0.2 has been released on August 17th. 

_This is a huge upgrade so I'm grateful for any problems you report here_ ❤️ 

**Known issues**
- The "new transaction"-form isn't translated.
- You can't drag and drop transactions.
- You can't clone transactions.
- Many command line options have been renamed.
- You'll have to set up 2FA again.
- The environment variable names have changed. Check out [this file](https://github.com/firefly-iii/firefly-iii/blob/master/.env.example) for the correct names. The most notable changes are:
    - The `FF_` prefix has been dropped from all variables.
    - `DB_USER` has become `DB_USERNAME`
    - `DB_NAME` has become `DB_DATABASE`
- Some more clarity on account types when you have more than one account of the same name (but of a different type)

**Will be fixed in the next release**
- #2438 Some balance issues when working with multiple currencies (a known issue)
- #2425 Transaction edit/create form is weird with the enter button
- #2424 auto complete tab doesn't work.
- #2441 Inconsistent character limit for currencies.
- #2443 500 error when submitting budgets
- #2446 Can't update current amount for piggy bank
- #2440 Errors when interacting with recurring transactions
- #2439 SQL error in API post new user
- Transaction report (after import, over email) is mostly empty
- Mass edit checkboxes doesn't work in a tag overview
- #2437 CPU issues when viewing accounts, probably run-away queries.
- #2432 Can't disable all currencies except one / can't disable EUR and switch to something else.
- Option to edit the budget is gone from edit transaction form.
- #2453 Search view things
- #2449 Can't add invoice date.
- #2448 Bad link in transaction overview
- #2447 Bad link in bill overview

**My issue is not on the list**
Reply here or open a new issue.

**Comment by 4oo4** [comment]
See #2437 

Also, I noticed that the command for `firefly:create-import` got renamed to `firefly:csv-import` (as well as a few switches that got changed too). I wasn't seeing that in the changelogs, did I miss that or is that documented elsewhere?

Cheers

**Comment by JC5** [comment]
No I completely forgot about that. It's mentioned in the documentation but nowhere else.

**Comment by 4oo4** [comment]
Another quick question, on the Edit Transaction screen I no longer seem to be able to manually mark that towards a budget? I think I last had that option before the 4.8 upgrade.

**Comment by JC5** [comment]
You should have it, still. I'll check it out.

**Comment by s1mpleman** [comment]
Are recurring transactions working still? mine don't seem to be firing anymore.

**Comment by lucavallerini** [comment]
> Are recurring transactions working still? mine don't seem to be firing anymore.

I raised the same issue in the previous version and it should be fixed now, at least on my tests they work correctly. Did you change the command to `firefly-iii:cron` (previously was `firefly:cron`)?

**Comment by s1mpleman** [comment]
No I run mine from outside the docker container with:
curl "http://0.0.0.0/cron/run/ae95f30b89b68edb001bd4b89b9d1fd1" 
I haven't had any notices of the background jobs not been run like I usually do. 
I've just checked and the one that was suppose to fire yesterday has fired today instead, or later last night. No drama, yes they are working :)

**Comment by MeRoBo** [comment]
exception fired during csv import
<pre>
root@firefly:/var/www/firefly-iii# tail -100 storage/logs/ff3-apache2handler-2019-08-20.log
[2019-08-20 08:52:36] local.DEBUG: Updating configuration...
[2019-08-20 08:52:36] local.DEBUG: Updating configuration...
[2019-08-20 08:52:36] local.DEBUG: Now in JobConfigurationController::index()
[2019-08-20 08:52:36] local.DEBUG: Now in JobConfigurationController::index() with job "DmE87g7koDk5" and status "has_prereq"
[2019-08-20 08:52:36] local.DEBUG: Going to create class "FireflyIII\Import\JobConfiguration\FileJobConfiguration"
[2019-08-20 08:52:36] local.DEBUG: Updating configuration...
[2019-08-20 08:52:36] local.ERROR: An exception has been thrown during the rendering of a template ("file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/03/23/032321420e11b8590f025a790659623f2cb04e31): failed to open stream: No such file or directory") in "/var/www/firefly-iii/resources/views/v1/import/file/configure-upload.twig" at line41. {"userId":1,"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/03/23/032321420e11b8590f025a790659623f2cb04e31): failed to open stream: No such file or directory\") in \"/var/www/firefly-iii/resources/views/v1/import/file/configure-upload.twig\" at line 41. at /var/www/firefly-iii/vendor/twig/twig/src/Template.php:230, ErrorException(code: 0): file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/03/23/032321420e11b8590f025a790659623f2cb04e31): failed to open stream: No such file or directory at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)
[stacktrace]
#0 /var/www/firefly-iii/storage/framework/views/twig/ed/ed7ee56822c2a67c5d35c9d4c265b368a6fe2ef5757409be5144e8b9f759f380.php(286): Twig\\Template->displayBlock('content', Array,Array)
#1 /var/www/firefly-iii/vendor/twig/twig/src/Template.php(455): __TwigTemplate_0120fb06768213d5ea80b516bef6e76dffd96690c3d8244a20aa228ffd56532a->doDisplay(Array, Array)
#2 /var/www/firefly-iii/vendor/twig/twig/src/Template.php(422): Twig\\Template->displayWithErrorHandling(Array, Array)
#3 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\\Template->display(Array, Array)
#4 /var/www/firefly-iii/storage/framework/views/twig/4d/4dfca511731948d4448f184b9c1f8126ae4faa40dfa5ddefa933d4a26f9f7fe1.php(38): TwigBridge\\Twig\\Template->display(Array, Array)
#5 /var/www/firefly-iii/vendor/twig/twig/src/Template.php(455): __TwigTemplate_de6421c2b084b29a6aa3a78f71fbd7ecf59683603333d2c90554181a6a1b19b6->doDisplay(Array, Array)
#6 /var/www/firefly-iii/vendor/twig/twig/src/Template.php(422): Twig\\Template->displayWithErrorHandling(Array, Array)
#7 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\\Template->display(Array, Array)
#8 /var/www/firefly-iii/vendor/twig/twig/src/Template.php(434): TwigBridge\\Twig\\Template->display(Array)
#9 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Twig.php(91): Twig\\Template->render(Array)
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(142): TwigBridge\\Engine\\Twig->get('/var/www/firefl...', Array)
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\\View\\View->getContents()
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\\View\\View->renderContents()
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#14 /var/www/firefly-iii/vendor/symfony/http-foundation/Response.php(202): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View))
#16 /var/www/firefly- </pre>

**Comment by MeRoBo** [comment]
I got template render exceptions but fixed it with the /flush route - maybe a flush is needed in the upgrade script?

**Comment by MeRoBo** [comment]
after upgrade, import csv and got duplicate transactions again.

**Comment by MeRoBo** [comment]
viewing transaction via tag, the select all checkbox fails to work.

**Comment by JC5** [comment]
@MeRoBo 

1. That is already there. If you see more errors, let me know.
2. Not entirely unexpected, but are they still a duplicate if you import twice? Please open an issue if so.
3. Thanks, will be fixed.

**Comment by zerojay** [comment]
I decided to start clean from scratch with a new user after deleting my original and updating to 4.8.0.2. When I am prompted to add my first bank account and to input my current balance for that account, there is a dropdown to set the currency type that is set to euros by default. I set it to Canadian dollar and put in my account balance. Upon going to the next screen, the Transactions page for the new account, it shows that the currency type is euros again instead of Canadian dollar as selected.

Also, the breadcrumb for the page is incorrect: 
Home > breadcrumbs.opening balance_list > Initial balance for "BMO"

I'm pretty sure "breadcrumbs.opening balance_list" should be replaced with something friendlier.

**Comment by spaetz** [comment]
I am pretty sure that the cron command changed, I was still running "php artisan firefly:cron" in my crontab. I now switched over to "php artisan firefly-iii:cron" and I always get the output 
`The recurring transaction cron job did not fire.
More feedback on the cron jobs can be found in the log files`

However, nothing is to be found in the log files, not even when I turn debug to true. How can I find out what is happening there?

**Comment by JC5** [comment]
I'll check it out, thanks.

**Comment by UhtredTheBold** [comment]
It might just be me but I've had a few occasions recently where I've entered transactions but the current balance for the account is not updated. If I go to edit settings of the account and click save, without making any changes, it gets updated.

It doesn't always happen though so maybe it's just me?

**Comment by JC5** [comment]
Good of you to mention it. It’s a cache thing. As I’m typing this I thought of a solution. 👍
