### ISSUE TITLE
API: SQL error on POST /api/v1/users

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [firefly-iii/firefly-iii#2439]
**Bug description**
I am running Firefly III version 7b813065da7eded19a70be2806dfcda4e3998647, and my problem is:

[Adding a new user with the API](https://api-docs.firefly-iii.org/#/users/storeUser) produces a 500 error with the following message:

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" (SQL: select count(*) as aggregate from "users" where "email" = dummy@example.com and "id" <> )
```

[Full error page with trace](https://geoffrey.frogeye.fr/files/GKG3AwwsjjvvQk7y/createUser.html)

**What works**

- Registering a new user manually
- [Updating a user](https://api-docs.firefly-iii.org/#/users/updateUser)

**Extra info**

Debug information generated at 2019-08-18 14:44:28 Europe/Paris for Firefly III version **4.8.0.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.2 |
| FF API version | 0.10.0 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.8 |
| Display errors | Off |
| Session start | 2019-08-01 00:00:00 |
| Session end | 2019-08-31 23:59:59 |
| Session first | 2015-05-27 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, bcmath, calendar, curl, exif, gd, gettext, iconv, imap, intl, ldap, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, soap, sockets, sqlite3, zip, apcu, igbinary, imagick, redis, Zend OPcache |

**Comment by JC5** [comment]
I think I fixed it, and two other things as well:

- Not able to remove a role (now possible by making the field an empty string)
- Not able to leave fields out without changing them to their default values.

**Comment by GeoffreyFrogeye** [comment]
Sadly, it doesn't seem to be fixed on my end :/

[New stacktrace](https://geoffrey.frogeye.fr/files/GKG3AwwsjjvvQk7y/createUsera86e956dbbb28767b7c1c7637d709b3b7b68afd9.html), *a priori* same trace, only some line numbers changed (btw tell me if you prefer to have it in JSON format).

**Comment by JC5** [comment]
Does it work on your end when you remove the comma after the word email, on this line?

https://github.com/firefly-iii/firefly-iii/blob/master/app/Api/V1/Requests/UserStoreRequest.php#L90

```
'email'        => 'required|email|unique:users,email',
```

**Comment by GeoffreyFrogeye** [comment]
It does!

**Comment by JC5** [comment]
That's gonna be the tiniest hotfix ever. :grin:

**Comment by GeoffreyFrogeye** [comment]
Can also confirm that 4b45c0d0a9546a7110c90fe99b94e65d0fcd9355 does it jobs, if this needed confirming.

That's obscure though, a validation string mishap causing an SQL error...
