### ISSUE TITLE
API: Server exception on PUT /api/v1/available_budgets/{id} 

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [firefly-iii/firefly-iii#2443]
**Bug description**
I am running Firefly III version 7b813065da7eded19a70be2806dfcda4e3998647, and my problem is:

[Editing an existing available budget with the API](https://api-docs.firefly-iii.org/#/available_budgets/updateAvailableBudget) produces a 500 error with the following message:

```
Undefined index: transaction_currency_id
```

[Full JSON output with trace](https://paste.frogeye.fr/?5c30f92bc93f48bf#7sPzHoALxt9S1PdLt/yZW0K9G9UmFdUeWFHvL6ZxJSk=)

**Debug info**

Debug information generated at 2019-08-18 14:44:28 Europe/Paris for Firefly III version **4.8.0.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.2 |
| FF API version | 0.10.0 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.8 |
| Display errors | Off |
| Session start | 2019-08-01 00:00:00 |
| Session end | 2019-08-31 23:59:59 |
| Session first | 2015-05-27 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, bcmath, calendar, curl, exif, gd, gettext, iconv, imap, intl, ldap, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, soap, sockets, sqlite3, zip, apcu, igbinary, imagick, redis, Zend OPcache |

**Comment by JC5** [comment]
Merged your changes :+1:
