### ISSUE TITLE
API: Consider using lists instead of dicts for repeatable things

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [firefly-iii/firefly-iii#2445]
**Description**

While most of the API is using lists for things that do not have a fixed size, some of them don't and use an object, such as (probably not exhaustive):

- [ValidationError](https://github.com/firefly-iii/api-docs-generator/blob/18f9c16ea83bac2a45216f757edd1a913cc88102/yaml/schemas/ValidationError.yaml#L11)
- [Bill's paid_dates](https://github.com/firefly-iii/api-docs-generator/blob/18f9c16ea83bac2a45216f757edd1a913cc88102/yaml/schemas/Bill.yaml#L93) (the spec says it's an array but the implementation says otherwise)
- [ObjectLink](https://github.com/firefly-iii/api-docs-generator/blob/18f9c16ea83bac2a45216f757edd1a913cc88102/yaml/schemas/ObjectLink.yaml#L4)
- Other kind of errors

**Solution**

I would suggest implementing all of those repeatable entities as a list (like [Transaction's transactions](https://github.com/firefly-iii/api-docs-generator/blob/18f9c16ea83bac2a45216f757edd1a913cc88102/yaml/schemas/Transaction.yaml#L34) for example), with the current key being inside the object that would be repeated.

**What are alternatives?**

We could let this as is, but consider this:

- The OpenAPI specification isn't really keen with this. This kind of details might prevent developers wanting to use the API to use an OpenAPI library to ease them the work.
- This would solve the problem that the API currently suffer of: empty objects are represented as an empty list in JSON (see the following example). I believe this is due to the fact that PHP consider an object and a list as almost the same thing: an array (but I'm no PHP expert), so this might not be an easy fix.

**Example of the empty object problem**

Here's an extract of a GET `/api/v1/bills/{id}` for a bill that have past paid dates:

```json
            "paid_dates": {
                "918": "2015-05-27",
                "992": "2017-05-05",
                "1002": "2017-06-03",
                "954": "2016-05-28",
                "1035": "2018-05-05"
            }
```

And the same thing for a bill that don't have any:

```json
            "paid_dates": []
```

Some languages interpret the two types of brackets very differently, which can be an issue.

**Additional context**

I acknowledge this breaks a non-negligible part of existing API implementation but seeing your plan of removing imports in favour of the API (which IMHO is a good idea by the way), this should probably be done sooner than later.

**Comment by JC5** [comment]
No that's a great idea, I'll pick it up. I want to have consistency and clarity in the API. Thanks for the feedback :)

**Comment by JC5** [comment]
For the bill paid_dates, could you check out the latest develop branch? It's undocumented still:

https://firefly.local/api/v1/bills/1?start=2019-08-01&end=2019-08-31

```json
{
    "data": {
        "type": "bills",
        "id": "1",
        "attributes": {
            "created_at": "2019-08-17T17:07:30+02:00",
            "updated_at": "2019-08-17T17:07:30+02:00",
            "currency_id": 1,
            "currency_code": "EUR",
            "currency_symbol": "€",
            "currency_decimal_places": 2,
            "name": "Rent",
            "amount_min": 795,
            "amount_max": 855,
            "date": "2015-01-01",
            "repeat_freq": "monthly",
            "skip": 0,
            "active": true,
            "notes": null,
            "next_expected_match": "2019-09-01",
            "pay_dates": [
                "2019-08-01"
            ],
            "paid_dates": [
                {
                    "transaction_group_id": 1,
                    "transaction_journal_id": 1,
                    "date": "2019-08-01"
                },
                {
                    "transaction_group_id": 2,
                    "transaction_journal_id": 4,
                    "date": "2019-08-01"
                }
            ]
        },
        "links": {
            "self": "https://firefly.local/api/v1/bills/1",
            "0": {
                "rel": "self",
                "uri": "/bills/1"
            }
        }
    }
}
```

**Comment by GeoffreyFrogeye** [comment]
Just checked, it works fine!

I let you close the issue as I see you prefer to close them when they're released rather than just implemented.

**Comment by JC5** [comment]
It's rare, but every now and then a user checks the existing issues and I hope they find these kinds of issues first :wink:

**Comment by JC5** [comment]
I can't easily fix the validation errors and object link representations, these are in line with https://jsonapi.org/. Others I can fix as we run into them, I'll keep an eye out for them in my code.

I'm going to mark this one as fixed. I want to bring new efforts to improve this to 4.8.1.
