### ISSUE TITLE
Account link points to wrong account

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2448]
Firefly 4.8.0.2 here. The transaction detail pages, e.g. /transactions/show/204
show the Metadata box on the right hand side, e.g.:

```
Meta information
Source account(s) | CashAccount1
Destination account(s) | Discounter1
```
Unfortunately both accounts are linked to the same account, so if I hover above the destination account and click, I will still get redirected to the account view of the source account. I think this worked differently in 4.7.17 if I remember correctly. Screenshot can be delivered if I was being unclear.

**Comment by JC5** [comment]
Thanks, I'll pick it up.

**Comment by JC5** [comment]
Fixed.
