### ISSUE TITLE
Invoice Date field missing in transaction entry

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2449]
4.8.0.2 here:
I have selected "Invoice date" in the Firefly preferences, however in the "enter transaction" page, there is no such field visible. It had worked with the interest date when I tried.

**Comment by JC5** [comment]
OK, I'll check what went wrong.

**Comment by JC5** [comment]
I changed some code and it seems to work now. Not sure why because it wasn't a significant change but that's one of the universe's mysteries I guess.
