### ISSUE TITLE
How to Password reset in heroku

### ISSUE THREAD

**Issue by kalyan4786** [firefly-iii/firefly-iii#2450]
I am running Firefly III version 4.7.17.3

**Description**
I created an instance of firefly III on heroku, i didn't configure the mail settings. I got many transactions recorded in the instance and now i forgot my password. So now i cant receive any password reset mail as i didn't configured it. I don't have direct access to database (postegre) and files on heroku either.

Please give me a solution for this. Thanks in advance.

**Extra info**
This is the debug information of my another instance running on heroku which was deployed at same time of creation of the instance in which i face problem of password now.

Debug information generated at 2019-08-19 15:04:04 UTC for Firefly III version **4.7.17.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17.3 |
| FF API version | 0.9.2 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.7 |
| Display errors | Off |
| Session start |  |
| Session end |  |
| Session first |  |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Linux; Android 9; POCO F1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Mobile Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, ldap, mbstring, Zend OPcache |

**Comment by spaetz** [comment]
If you do not have access to the files and to the database, I am not sure there is anything you can do. Essentially you would have to hack the instance (which hopefully is not possible).
But then I am not the developer of firefly-iii

**Comment by JC5** [comment]
By default, the email message will be in the log files.
