### ISSUE TITLE
[Feature] Prefill account information when possible (and sensible)

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2452]
When I am in an account view, e.g. /accounts/show/59 and I click the "+" button on the top right to create a new withdrawal or deposit, I would expect that the account in question is already prefilled in the transaction form. After all, I clicked it from the account view.

Similar in the Dashboard when I click the "Create transaction" which is IN THE BOX belonging to a specific account, I would also expect it to be prefilled. The additional complication here is of course that we do not know yet whether it is going to be a withdrawal or deposit, so that might require a bit more thinking before implementation.

**Comment by jlauwers** [comment]
> Similar in the Dashboard when I click the "Create transaction" which is IN THE BOX belonging to a specific account, I would also expect it to be prefilled. The additional complication here is of course that we do not know yet whether it is going to be a withdrawal or deposit, so that might require a bit more thinking before implementation.
Maybe put the account ... in both? And we will replace wichever is not relevant?

**Comment by spaetz** [comment]
> Maybe put the account ... in both? And we will replace wichever is not relevant?

mmh, not sure, that does not sound like a great shortcut then. However, we could have a "Create withdrawal" button by default which could with a drop down list be changed to "Create Deposit" and "Create Transfer" which would remember the last chosen state. But as I said, that is a tad more complicated, the "Create Withdrawal/deposit" button on the top right is already unambiguous...

**Comment by jlauwers** [comment]
I may be wrong, but I think it was the case before.

**Comment by JC5** [comment]
There was a similar feature but it's not coming back for the time being.
