### ISSUE TITLE
No global action button for search page

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2453]
In /search?search=foobar&go= we can see checkboxes.

- the top one doesn't check everything

- there is no global action button to edit multiple entries

**Comment by spaetz** [comment]
And while we are on that page, the presentation of:
"Firefly III found transaction(s) in 0.016992092132568 seconds. " is not quite optimal, there is no indication on how many transactions were found, and the seconds can certainly be rounded :-).

**Comment by JC5** [comment]
Thanks, I'll pick it up.

**Comment by JC5** [comment]
Will be fixed.

**Comment by jlauwers** [comment]
Works in dev.
Thanks! :-)
