### ISSUE TITLE
Entering an invalid date leads to weird error message

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2454]
4.8.0.2: Entering 31.04.2019 (an invalid date!!) as a transaction date leads to the mysterious error message:
"The transactions.0.date field is required."
I had to think twice before I noticed what had gone wrong. A better error message would be nice here.

**Comment by JC5** [comment]
I'll see what I can do.

**Comment by JC5** [comment]
If I do this in Firefox, the date isn't submitted with the form. The value isn't filled by my browser. That explains the error. I'll see what I can do about the user-friendliness of the errors but it isn't high on my list to be honest.
