### ISSUE TITLE
Rules to Bill connection error

### ISSUE THREAD

**Issue by rolandlovasz** [firefly-iii/firefly-iii#2456]
**Bug description**
I am running Firefly III version 4.8.0.2, and my problem is:

Rules to Bill connection error

**Steps to reproduce**
Go to bills, show one, Run rules ...

**Expected behavior**
Connect transactions to Bills by Rules

**Bonus points**
Change the following code to fix the problem:

BillRepository::linkCollectionToBill:
$journal = $transaction->transactionJournal; -> $journal = TransactionJournal::find($transaction['transaction_journal_id']);

**Comment by JC5** [comment]
Thanks, I'll look into it.

**Comment by JC5** [comment]
Fixed :+1:

**Comment by rolandlovasz** [comment]
Perfect, Thank you so much. I have an own fork, within I've made little development to show the actual balance as the real balance in the title of the page.
<img width="838" alt="Screenshot 2019-08-22 at 09 44 51" src="https://user-images.githubusercontent.com/13537729/63496101-8de77800-c4c1-11e9-8f39-11d55c83a53e.png">
