### ISSUE TITLE
Auto-completion for "Description" field on transaction form

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2457]
I am running Firefly III version 4.8.0.2

The previous version 4.7 would offer auto-completion suggestions for the "Description" field.  That feature was removed in 4.8.0.   Could it be added back?  It's very useful, especially when adding multiple transactions in series.

**Comment by JC5** [comment]
Yep, not sure what happened there.

**Comment by GaryQ** [comment]
Autocomplete also not working in Rules Actions for set source account and set desination account to entry fields. Other options seem OK. Haven't tested them all.
Seemed relevant to this thread... 
(new at this stuff so I hope this isn't considered "bug thread highjacking")  :)

**Comment by spaetz** [comment]
Autocomplete in the rules creation page works for me with source and.destination accounts in 4.8.0.2...

**Comment by JC5** [comment]
Description auto-complete should work in develop.

**Comment by JC5** [comment]
Rules autocomplete works for me as well.
