### ISSUE TITLE
cash account link

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2459]
When I create a withdraw with no destination account, it defaults to a "cash account".
Links to that cash account seems broken.

**Comment by JC5** [comment]
Thanks, that can be fixed.

**Comment by JC5** [comment]
Fixed in dev.

**Comment by jlauwers** [comment]
I still have the same issue. :(

**Comment by JC5** [comment]
Where is the link?

**Comment by jlauwers** [comment]
Link is in /accounts/show/xxx (source account)
