### ISSUE TITLE
Incorrect values in account balances in report

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#2460]
Issue: When generating a report some account balances don't match. 
Reproducing issue:
  - Create account with no opening balance and enter a transaction on any date except the first day of the month. Generate report:
<img width="529" alt="CaptureA" src="https://user-images.githubusercontent.com/3269694/63439076-07fcfb80-c3f3-11e9-9cc5-4a402aef5479.PNG">

ALL OK!

<img width="126" alt="Capture4" src="https://user-images.githubusercontent.com/3269694/63438962-d6843000-c3f2-11e9-80c5-0165ca207eca.PNG">

 - Enter a transaction on the 1st day of the month it was opened and you get:

<img width="117" alt="Capture3" src="https://user-images.githubusercontent.com/3269694/63439174-37136d00-c3f3-11e9-96f5-1c68d25ee8bc.PNG">

Wrong which causes the balances to be out of whack. 
Cause: FF Is taking the account balance from the first day of the month if there is no opening balance. When there is an actual opening balance all is in sync even with a transaction on the first. I Took a transaction and moved it from one account to the other and reproduced the same bug when there was no opening balance. Changed the 2 offfending transactions to the 2nd of january and as in image 1 report is as it should be and balances with the income/expenses results

**Comment by JC5** [comment]
I think I can fix this in the next release, thanks for letting me know.

**Comment by GaryQ** [comment]
Thanks! That was quick will test when I get home later.

**Comment by GaryQ** [comment]
Not my lucky day this doesn't fix my problem either still the same issues generating report

<img width="100" alt="CaptureX" src="https://user-images.githubusercontent.com/3269694/63472947-5b923800-c439-11e9-8309-502091b91180.PNG">
<img width="333" alt="CaptureY" src="https://user-images.githubusercontent.com/3269694/63472946-5b923800-c439-11e9-9d92-5bff47d37d0b.PNG">

**Comment by JC5** [comment]
OK, but you'll have to explain your case a bit more clearly then. Try starting a new administration with as little information in it as possible, and then reproduce the bug. That way I can more easily find the problem. Thx :)

**Comment by GaryQ** [comment]
NP. I'll do that today

**Comment by GaryQ** [comment]
Still same issue. Even reset all dates in MySQL to 2018/12/31 to see if it was the cause but no.

So here's the scenario:

Reinstalled dev this afternoon using composer from scratch and created new database

Created a few accounts: (Default asset and savings, cash and 1 Credit card)
These are a few opening balances 2019/01/01 before any transactions:
(all 3 reports are default /all accounts/20190101-20190131)

Notice 2nd line of report: Start $0.00 End $0.00 Balance $0.00

<img width="271" alt="CaptureAA" src="https://user-images.githubusercontent.com/3269694/63566719-cb84e900-c533-11e9-92d8-fa98b26b0fc0.PNG">

Then added an expense transaction: dated 2019/01/01
CreditCard -> $62.16 -> VPN Provider

Notice 2nd line of report : Start $-62.16 End $-62.16 Balance $0.00 (Wrong)

<img width="262" alt="CaptureBB" src="https://user-images.githubusercontent.com/3269694/63566720-cb84e900-c533-11e9-9b56-51c7beab2825.PNG">

Then change transaction date to 2019/01/02

Notice 2nd line of report now reflects the correct amounts : Start $0.00 End $-62.16 Balance $-62.16
(Correct)
<img width="279" alt="CaptureCC" src="https://user-images.githubusercontent.com/3269694/63566721-cb84e900-c533-11e9-8231-f81e2b54bd63.PNG">

**Comment by GaryQ** [comment]
Sheesh went through all that work today.... even messed up my database server by accident.

Thanks. That part is resolved!

**Comment by JC5** [comment]
OK, so far so good. I changed some things in the code, these are not yet available in 4.8.0.2.

3 accounts, 3 opening balances:

<img width="736" alt="Screenshot 2019-08-23 at 09 58 54" src="https://user-images.githubusercontent.com/5889984/63576540-abcddf00-c58c-11e9-9ab4-295fbfe0bf64.png">

If I create an expense on the 1st of the month, this is the result. I subtracted 10,- from Checking account.

<img width="733" alt="Screenshot 2019-08-23 at 10 00 03" src="https://user-images.githubusercontent.com/5889984/63576603-d1f37f00-c58c-11e9-80a0-3ef7238917f7.png">

Changing the date of the transaction to another date gives the same result, which I believe is correct. Do you agree?

When I remove the opening balance, this happens:

<img width="747" alt="Screenshot 2019-08-23 at 10 03 04" src="https://user-images.githubusercontent.com/5889984/63576794-3b738d80-c58d-11e9-98b8-2ec5ac7a014d.png">

When I put the opening balance (10) on the day before (july 31st) this happens:

<img width="744" alt="Screenshot 2019-08-23 at 10 04 08" src="https://user-images.githubusercontent.com/5889984/63576859-5e9e3d00-c58d-11e9-98a9-0e089bf28392.png">

If I edit it back to the 1st, the result is the same again.

<img width="739" alt="Screenshot 2019-08-23 at 10 05 04" src="https://user-images.githubusercontent.com/5889984/63576915-8392b000-c58d-11e9-835f-7ced3c8fe6dc.png">

**Comment by JC5** [comment]
Thanks for your efforts, I'm glad you made a clear example. I think I caught the problem, but let me know if I'm wrong.

**Comment by GaryQ** [comment]
Thanks, seems fixed  :)

<img width="271" alt="CaptureDDOK" src="https://user-images.githubusercontent.com/3269694/63609518-e0e22d80-c59c-11e9-9fc6-8c287b360f9a.PNG">

**Comment by JC5** [comment]
Glad to hear it. Thanks again for the help. :+1:
