### ISSUE TITLE
Allow "tag:XXX" searches

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2464]
Firefly 0.8.0.2 here. It is possible to search for e.g. "category:school", but it is not possible to search by tag, e.g. "tag:school". Indeed searching for that term gives me some weird search results that have neither the term "tag" nor the term "school" anywhere...

**Comment by JC5** [comment]
I thought that worked. I’ll check it out.

**Comment by spaetz** [comment]
If it is supposed to work, it should be mentioned in the "Help for this page" text where tag: is not mentioned at all. And as I said, I get weird search results trying out a "tag:test" search...

**Comment by JC5** [comment]
Not there yet, I'll put it on the map for 4.8.1

**Comment by JC5** [comment]
Will be supported in the next release.
