### ISSUE TITLE
Errors on transaction entering can lead to data loss.

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2465]
0.8.0.2 here:
When entering a transaction and having both `After storing, return here to create another one. Reset form after submission` checked, any error in the form will lead to an nearly empty page (without any transaction form), stating:
"Error! There was something wrong with your submission. Please check out the errors below. " at the same time, I get a green bar directly below, stating:
"Success! The transaction has been stored." (which is not true)

No errors are shown, and the previously entered data is lost.

To replicate, just try to enter some letters in the value field or leave the description field empty...

**Comment by JC5** [comment]
I'll check it out, thanks.

**Comment by JC5** [comment]
This will be fixed in the next release.
