### ISSUE TITLE
Allow to order recurring transactions by next due date

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2466]
Currently all repeating transactions are simply listed alphabetically by title. I have quite a few of them and it would be VERY helpful to:
1) be able to see the next occurence when the transaction will fire in this overview and
2) be able to sort the transactions in the order of their next occurence which will allow me to review the upcoming transactions.

I realize that this is nothing urgent but it would make it much more convenient to manage my recurrent transactions.

**Comment by JC5** [comment]
Well it sounds like a good idea to make that happen. Thx for the suggestion.

**Comment by JC5** [comment]
Will be in the next release.
