### ISSUE TITLE
Date ordering of "Bill view" flawed

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2467]
On the bills page, I have the opportunity to sort by date by clicking the "next expected date" column header. However, the resulting sort order is not by date. It goes like this:
```
May 20, 2019
May 15, 2019
May 7, 2019
May 1, 2019
August 2, 2019
February 14, 2020
```
So the sort order within the month is the opposite of what it should be.

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
I fixed it for the next release but it takes some effort from translators to fix it everywhere. The library doesn't sort on the data value but on the display value, so this might require separate parsing config from all translations.
