### ISSUE TITLE
Links from Transaction links configuration link to wrong transactions

### ISSUE THREAD

**Issue by rnck** [firefly-iii/firefly-iii#2470]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

Go to e.g. /admin/links/show/2 and clicking on a transaction brings me to a completely unrelated (and unlinked) transaction.

**Steps to reproduce**
Go to Options - Administration - Transaction links configuration.
Click any linked digit in column "Transaction links configuration".
Click a transaction.

**Expected behavior**
I expect to be redirected to the correct transaction.

Please let me know if you need more information.

**Comment by JC5** [comment]
No that's enough information, I think. Thanks, I'll pick it up.

**Comment by JC5** [comment]
Pushed  a fix, will be included in the next release.
