### ISSUE TITLE
Edit Transaction - Add Budget

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#2473]
4.8.0.3

STEPS:
Transaction entered no budget
1 - Edit Transaction: Add it to a Budget
2 - Save edit ->redirects to transaction and posts success message...
but does not update the transaction.

Also (aesthetic only) No Default or Placeholder in empty Budget field

**Comment by JC5** [comment]
Editing the budget works for me, although the placeholder could use some work indeed.
