### ISSUE TITLE
Import from Länsförsäkringar Bank PSD2

### ISSUE THREAD

**Issue by HakHal** [firefly-iii/firefly-iii#2474]
**Description**
Hello

A request about integration against a Swedish bank named "Länsförsäkringar". 
 
What would the possibilities be to hook into their API to import changes to Firefly? 
The also have a developers 
https://developer.bank.lansforsakringar.se/

From what i can understand they use "EU's PSD2 directive" for their API. 

I have only scraped the surface of what Firefly can do yet. And also my request might not make much sense but the "dictionary" is a bit rusty. 

Additional information. 
https://www.lansforsakringar.se/jamtland/privat/om-oss/kontakta-oss/sidfot/juridik--sakerhet/openbanking-sv/openbanking/

**Solution**
The solution would mean that it would be easier and faster to get expenses and income from the bank without using csv files. 

**What are alternatives?**
Slow way to manually export data from the bank into csv files. 

Edit: reminder to self, do this on computer and not phone.

**Comment by JC5** [comment]
Yes, this is on my roadmap. I won't implement API's into Firefly III, but I am working on apps that could do that.

**Comment by jkaberg** [comment]
@JC5 mind shareing more details? And will these tools integrate with Firefly somehow? Do you have an issue tracking this?
