### ISSUE TITLE
API: Consider unifying tags representation

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [firefly-iii/firefly-iii#2475]
**Description**

In the API, specifically for `Transaction` and `Recurrence`, tags should be provided as a comma-separated string of tags, but they are returned as an array of strings, with one tag per string.

The issue is that to update a `Transaction`, one needs to handle the tag fields separately. Not doing so would either result in an error or if some fallback logic is implemented, in tags like those: `['some'`, `'tags'`, `'here']`.

**Solution**

Either change the storing/updating process to use arrays instead of comma-separated strings, or make the fetching process use comma-separated strings instead of arrays.

I would go with the former, as:
- If modified, the tag list usually already is in some form of array
- It will allow using tags with commas in it, for [people wanting to watch the world burn :)](https://github.com/firefly-iii/firefly-iii/issues/901#issuecomment-334436401)

**Additional context**

I'll update the API spec of course :)

**Comment by JC5** [comment]
:+1: very good idea. I'll go for arrays on both ends.

**Comment by JC5** [comment]
Both recurrences and transactions now accept arrays for tags:

```
{
	"transactions": [
		{
			"type":"withdrawal",
			"amount":4,
			"description": "TestX",
			"tags": ["a","b,c","deFF"],
			"source_id": 1,
			"destination_id": 8,
			"date": "2019-01-01"
		}
		]
}
```
