### ISSUE TITLE
API: Sign consistency of transaction amount

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [firefly-iii/firefly-iii#2476]
**Description**

In the API, for `Transaction`, the amount of a withdrawal is negative when we retrieve it, but the API expects it to be positive when we submit it.

The issue is that to update a `Transaction`, one needs to handle the amount fields separately. Not doing so would result in the following error: `transactions.0.amount must be larger than zero.`.

**Solution**

Either make storing/updating a `Transaction` accept (only) negative values for withdrawals, or make the retrieval of withdrawals output a positive amount.

I would go with the latter, so we can have a consistent formula across all types of transactions:

```
source_balance -= transaction_amount
destination_balance += transaction_amount
```

**Comment by JC5** [comment]
:+1: good idea. This changed with the introduction of transaction groups and a new collector on Firefly III's end.

**Comment by JC5** [comment]
API should now push all transaction amounts as positive.
