### ISSUE TITLE
API: Updating Rules is not easy

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [firefly-iii/firefly-iii#2477]
**Description**

Updating `Rules` from the API is a bit of a burden right now, for various reasons.

Allow me to use an example. I have the following rule:

`GET /api/v1/rules/22`

```json
{
    "data": {
        "attributes": {
            "actions": [
                {
                    "active": true,
                    "created_at": "2019-08-24T11:54:35+02:00",
                    "id": 60,
                    "order": 1,
                    "stop_processing": false,
                    "type": "add_tag",
                    "updated_at": "2019-08-24T11:54:35+02:00",
                    "value": "test2"
                }
            ],
            "active": true,
            "created_at": "2019-08-24T11:54:35+02:00",
            "description": "",
            "order": 11,
            "rule_group_id": 2,
            "stop_processing": false,
            "strict": true,
            "title": "Test Rule",
            "triggers": [
                {
                    "active": true,
                    "created_at": "2019-08-24T11:54:35+02:00",
                    "id": 311,
                    "order": 1,
                    "stop_processing": false,
                    "type": "user_action",
                    "updated_at": "2019-08-24T11:54:35+02:00",
                    "value": "store-journal"
                },
                {
                    "active": true,
                    "created_at": "2019-08-24T11:54:35+02:00",
                    "id": 312,
                    "order": 1,
                    "stop_processing": false,
                    "type": "tag_is",
                    "updated_at": "2019-08-24T11:54:35+02:00",
                    "value": "test1"
                }
            ],
            "updated_at": "2019-08-24T11:54:35+02:00"
        },
        "id": "22",
        "links": {
            "0": {
                "rel": "self",
                "uri": "/rules/22"
            },
            "self": "https://firefly.local/api/v1/rules/22"
        },
        "type": "rules"
    }
}
```

Let's update it, without changing anything. By just taking the result of the transaction and removing fields that are not needed, we could send this to the API.

`POST /api/v1/rules/22`

```json
{
    "actions": [
        {
            "active": true,
            "stop_processing": false,
            "type": "add_tag",
            "value": "test2"
        }
    ],
    "active": true,
    "description": "",
    "rule_group_id": 2,
    "stop_processing": false,
    "strict": true,
    "title": "Test Rule",
    "triggers": [
        {
            "active": true,
            "stop_processing": false,
            "type": "user_action",
            "value": "store-journal"
        },
        {
            "active": true,
            "stop_processing": false,
            "type": "tag_is",
            "value": "test1"
        }
    ]
}
```

However, this will produce multiple errors:

- **title:** This name is already in use.
    This is a bug. Changing the name works fine
- **trigger**: The trigger field is required.
    It was not directly provided when fetching it. Using `['triggers'][0]['value']` as a value for it works.
- **triggers.0.value**: This value is invalid for the selected trigger.
    It doesn't seem to accept its own `user_action` rule (the value actually doesn't matter here). Removing `['triggers'][0]` before sending back works.

Not really a show-stopper, but updating a rule currently involves a lot of special handling.

**Solution**

For a start, `This name is already in use.` needs to be fixed. If it is of any help, [you already fixed](https://github.com/firefly-iii/firefly-iii/issues/2440#issuecomment-523966938) a [similar issue.](https://github.com/firefly-iii/firefly-iii/issues/2440#issuecomment-522326907) in a11f876c49926d13b06b042be527f27c30ea6cae for `Recurrence`.

Then, we can either drop `['triggers'][0]` (basically the `user_action` rule) from what's returned from the server and populate `trigger` instead; or we can drop `trigger` altogether and validate that the user populate`['triggers'][0]` with a correct `user_action` rule.

I think the former makes more sense, as I believe `user_action` is a special rule that must placed as the first trigger anyway, and that would ensure consistency with the GUI.

**Comment by JC5** [comment]
Yep, user action is a special one that should be excluded. I'll pick it up.

Laravel has a hard time distinguishing between submitted fields that are empty, null or missing so I need to think about it.

As a rule, anything that is missing in a PUT request should be left as is by Firefly III.

**Comment by GeoffreyFrogeye** [comment]
> As a rule, anything that is missing in a PUT request should be left as is by Firefly III.

Yes, it's kind of cumbersome to have to re-send the whole object to update just one field.

This is not really related, but I'm curious. Why did you choose to implement the whole API by hand, rather than using one of the [many JSON:API server libraries](https://jsonapi.org/implementations/#server-libraries-php)?

**Comment by JC5** [comment]
I barely researched them, to be honest, but I did look into it after a while. Most of them copy your models to output and leave it at that. Although it's hard to avoid I want to prevent the API being a copy of the database. Plus, most of my input and verification rules are pretty complex already and most libraries can handle only the basic stuff.

The library I use for output is listed btw, thephpleague/fractal.

Laravel for example has a "factory" pattern thing, for example, to be used in testing. It generates random objects. But those only work for plain objects with ZERO relations. If you try to build a Group with 3 Journals and 6 Transactions you might as well do it yourself (not to mention all the related objects).

**Comment by JC5** [comment]
A push to `develop`:

1. Rules will no longer list the "user-action" trigger
2. Rules will have a "moment" field that says either "update-journal" or "store-journal".

Docs not yet updated.

**Comment by JC5** [comment]
To be consistent, this field is now called "trigger".

**Comment by GeoffreyFrogeye** [comment]
Working on my side :+1:

**Comment by JC5** [comment]
You can submit empty rules, or leave out actions and triggers, and it'll work.

For my sanity, if you submit a trigger or an action, you must include all meta-data (at least the type and value).

**Comment by JC5** [comment]
Oh and you can submit the same title and it'll also work.

**Comment by GeoffreyFrogeye** [comment]
> For my sanity, if you submit a trigger or an action, you must include all meta-data (at least the type and value).

I'm not sure I completely understood, if I want to change the triggers (resp. actions), I need to include all the triggers (resp. actions) in the list, but if I don't want to update it I can leave out the whole field and will stays as it is?

> Oh and you can submit the same title and it'll also work.

Already tested :smile:

**Comment by JC5** [comment]
Indeed :). If you want to change a single trigger/action, I'll need all of the triggers/actions. It will delete all of them and then recreate them.

If you don't want to change anything, leave them out completely.

**Comment by JC5** [comment]
I think this one is fixed, right?

**Comment by GeoffreyFrogeye** [comment]
Yes, I believe you forgot to put the `fixed` tag.
