### ISSUE TITLE
Whoops, fatal error

### ISSUE THREAD

**Issue by daantrommel** [firefly-iii/firefly-iii#2478]
I'm trying to install firefly iii via docker-compose. I did this about a year ago without any problems, but now I get a fatal error in my browser. I used the docker-compose file from github. Anybody else encountered this problem? Can anyone share a working docker-compose file?

**Comment by JC5** [comment]
Can you share the error?

**Comment by daantrommel** [comment]
![image](https://user-images.githubusercontent.com/49483849/63638240-fb440600-c685-11e9-9cfd-ec673d97c02e.png)

                                             ,
  SQLSTATE[HY000] [2002] Connection refused  ,
                                             ,
,
,
In Connection.php line 664:,
                                                                               ,
  SQLSTATE[HY000] [2002] Connection refused (SQL: select `transaction_journal  ,
  s`.* from `transaction_journals` left join `transaction_types` on `transact  ,
  ion_types`.`id` = `transaction_journals`.`transaction_type_id` where `trans  ,
  action_journals`.`deleted_at` is null and `transaction_types`.`type` = Open  ,
  ing balance and `transaction_journals`.`deleted_at` is null)                 ,
                                                                               ,
,
In PDOConnection.php line 31:,
                                             ,
  SQLSTATE[HY000] [2002] Connection refused  ,
                                             ,
,
In PDOConnection.php line 27:,
                                             ,
  SQLSTATE[HY000] [2002] Connection refused  ,
                                             ,
,
,
In Connection.php line 664:,
                                                                               ,
  SQLSTATE[HY000] [2002] Connection refused (SQL: select distinct `budgets`.`  ,
  id`, `budgets`.`name`, `budgets`.`user_id`, `users`.`email` from `budgets`   ,
  left join `budget_transaction_journal` on `budgets`.`id` = `budget_transact  ,
  ion_journal`.`budget_id` left join `users` on `budgets`.`user_id` = `users`  ,
  .`id` where `budget_transaction_journal`.`budget_id` is null and `budgets`.  ,
  `deleted_at` is null and `budgets`.`deleted_at` is null)                     ,
                                                                               ,
,
In PDOConnection.php line 31:,
                                             ,
  SQLSTATE[HY000] [2002] Connection refused  ,
                                             ,
,
In PDOConnection.php line 27:,
                                             ,
  SQLSTATE[HY000] [2002] Connection refused  ,
                                             ,
,
,
In Connection.php line 664:,
                                                                               ,
  SQLSTATE[HY000] [2002] Connection refused (SQL: select `users`.* from `user  ,
  s` order by `id` desc)                                                       ,
                                                                               ,
,
In PDOConnection.php line 31:,
                                             ,
  SQLSTATE[HY000] [2002] Connection refused  ,
                                             ,
,
In PDOConnection.php line 27:,
                                             ,
  SQLSTATE[HY000] [2002] Connection refused  ,
                                             ,
,
Encryption keys generated successfully.,
,
In Connection.php line 664:,
                                                                               ,
  SQLSTATE[HY000] [2002] Connection refused (SQL: insert into `oauth_clients`  ,
   (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `passw  ,
  ord_client`, `revoked`, `updated_at`, `created_at`) values (?, Firefly III   ,
  Personal Access Client, 6AleMK0eLjYAIUoHxCkRUEDtMZZhTtTPPq92pb6C, http://lo  ,
  calhost, 1, 0, 0, 2019-08-24 13:43:37, 2019-08-24 13:43:37))                 ,
                                                                               ,
,
In PDOConnection.php line 31:,
                                             ,
  SQLSTATE[HY000] [2002] Connection refused  ,
                                             ,
,
In PDOConnection.php line 27:,
                                             ,
  SQLSTATE[HY000] [2002] Connection refused  ,
                                             ,
,
plication cache cleared!,
+------------------------------------------------------------------------------+,
|                                                                              |,
| Thank you for installing Firefly III, v4.8.0.3!                              |,
| This is a huge upgrade for Firefly III. Please expect bugs and errors, and   |,
| bear with me as I fix them. I tested a lot of things but pretty sure I       |,
| missed some. Thanks for understanding.                                       |,
|                                                                              |,
+------------------------------------------------------------------------------+,
Go!,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message,
[Sat Aug 24 13:43:37.845124 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.8 OpenSSL/1.1.1c configured -- resuming normal operations,
[Sat Aug 24 13:43:37.845162 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND',
192.168.1.10 - - [24/Aug/2019:13:43:38 +0000] "GET / HTTP/1.1" 500 2284 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36",
192.168.1.10 - - [24/Aug/2019:13:43:38 +0000] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3728 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36",
192.168.1.10 - - [24/Aug/2019:13:43:38 +0000] "GET /fonts/lato-100.woff HTTP/1.1" 404 3728 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36",

**Comment by JC5** [comment]
The Postgres container didn’t launch or was badly configured. Remove everything and try again.
