### ISSUE TITLE
Error on upgrade to 4.8.0.3

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#2480]
I just upgrade Firefly III from 4.7.17 to 4.8.0.3. I use composer for this. After update, I try to login, Firefly has update database, and I have error-message:

``An unknown error prevented Firefly III from executing the upgrade commands. Sorry. SQLSTATE[HY000]: General error: 1 too many SQL variables (SQL: select "transaction_journal_id" from "transactions" where "transactions"."id" in (55, 56, 85, 86, 135, 136, 155, 156, 165, 166, 167, 168, 169, 170, 385, 386, 433, 434, 443, 444, 459, 460, 471, 472, 617, 618, 675, 676, 685, 686, 695, 696, 699, 700, 709, 710, 717, 718, 721, 722, 731, 732, 733, 734, 745, 746, 747, 748, 757, 758, 767, 768, 769, 770, 771, 772, 775, 776, 777, 778, 779, 780, 781, 782, 787, 788, 793, 794, 811, 812, 819, 820, 823, 824, 827, 828, 829, 830, 835, 836, 837, 838, 839, 840, 841, 842, 861, 862, 863, 864, 865, 866, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 899, 900, 907, 908, 913, 914, 915, 916, 917, 918, 929, 930, 931, 932, 933, 934, 935, 936, 951, 952, 959, 960, 961, 962, 967, 968, 973, 974, 975, 976, 979, 980, 987, 988, 993, 994, 997, 998, 999, 1000, 1001, 1002, 1011, 1012, 1019, 1020, 1021, 1022, 1025, 1026, 1031, 1032, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1071, 1072, 1077, 1078, 1079, 1080, 1093, 1094, 1095, 1096, 1107, 1108, 1111, 1112, 1113, 1114, 1115, 1116, 1125, 1126, 1127, 1128, 1131, 1132, 1141, 1142, 1145, 1146, 1149, 1150, 1155, 1156, 1157, 1158, 1159, 1160, 1163, 1164, 1165, 1166, 1173, 1174, 1175, 1176, 1179, 1180, 1183, 1184, 1195, 1196, 1197, 1198, 1209, 1210, 1211, 1212, 1213, 1214, 1233, 1234, 1235, 1236, 1239, 1240, 1243, 1244, 1245, 1246, 1247, 1248, 1253, 1254, 1265, 1266, 1273, 1274, 1275, 1276, 1277, 1278, 1297, 1298, 1305, 1306, 1315, 1316, 1321, 1322, 1327, 1328, 1329, 1330, 1335, 1336, 1339, 1340, 1341, 1342, 1343, 1344, 1347, 1348, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1381, 1382, 1389, 1390, 1391, 1392, 1393, 1394, 1403, 1404, 1407, 1408, 1409, 1410, 1421, 1422, 1447, 1448, 1455, 1456, 1457, 1458, 1463, 1464, 1473, 1474, 1475, 1476, 1479, 1480, 1489, 1490, 1499, 1500, 1505, 1506, 1507, 1508, 1509, 1510, 1521, 1522, 1535, 1536, 1537, 1538, 1555, 1556, 1557, 1558, 1571, 1572, 1573, 1574, 1581, 1582, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1603, 1604, 1605, 1606, 1609, 1610, 1607, 1608, 1611, 1612, 1613, 1614, 1627, 1628, 1633, 1634, 1643, 1644, 1645, 1646, 1655, 1656, 1671, 1672, 1673, 1674, 1681, 1682, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1719, 1720, 1723, 1724, 1745, 1746, 1747, 1748, 1757, 1758, 1779, 1780, 1783, 1784, 1791, 1792, 1793, 1794, 1809, 1810, 1813, 1814, 1817, 1818, 1819, 1820, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1857, 1858, 1859, 1860, 1883, 1884, 1885, 1886, 1909, 1910, 1911, 1912, 1915, 1916, 1917, 1918, 1919, 1920, 1927, 1928, 1931, 1932, 1933, 1934, 1937, 1938, 1943, 1944, 1945, 1946, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1971, 1972, 1973, 1974, 1981, 1982, 1993, 1994, 1999, 2000, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2035, 2036, 2045, 2046, 2051, 2052, 2053, 2054, 2061, 2062, 2065, 2066, 2079, 2080, 2081, 2082, 2083, 2084, 2109, 2110, 2115, 2116, 2129, 2130, 2131, 2132, 2133, 2134, 2141, 2142, 2143, 2144, 2145, 2146, 2165, 2166, 2167, 2168, 2171, 2172, 2179, 2180, 2185, 2186, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2205, 2206, 2207, 2208, 2209, 2210, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2247, 2248, 2265, 2266, 2267, 2268, 2281, 2282, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2307, 2308, 2325, 2326, 2329, 2330, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2365, 2366, 2367, 2368, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2383, 2384, 2385, 2386, 2391, 2392, 2395, 2396, 2397, 2398, 2401, 2402, 2403, 2404, 2419, 2420, 2425, 2426, 2427, 2428, 2439, 2440, 2459, 2460, 2467, 2468, 2477, 2478, 2503, 2504, 2509, 2510, 2513, 2514, 2517, 2518, 2519, 2520, 2523, 2524, 2531, 2532, 2533, 2534, 2537, 2538, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2565, 2566, 2571, 2572, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592, 2595, 2596, 2597, 2598, 2599, 2600, 2603, 2604, 2613, 2614, 2619, 2620, 2621, 2622, 2625, 2626, 2629, 2630, 2631, 2632, 2635, 2636, 2641, 2642, 2647, 2648, 2657, 2658, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2671, 2672, 2675, 2676, 2677, 2678, 2685, 2686, 2687, 2688, 2691, 2692, 2693, 2694, 2695, 2696, 2701, 2702, 2703, 2704, 2709, 2710, 2725, 2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2739, 2740, 2741, 2742, 2751, 2752, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2773, 2774, 2803, 2804, 2805, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 2813, 2814, 2817, 2818, 2825, 2826, 2829, 2830, 2833, 2834, 2835, 2836, 2845, 2846, 2847, 2848, 2851, 2852, 2855, 2856, 2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2883, 2884, 2885, 2886, 2897, 2898, 2899, 2900, 2901, 2902, 2903, 2904, 2905, 2906, 2909, 2910, 2915, 2916, 2925, 2926, 2935, 2936, 2937, 2938, 2939, 2940, 2943, 2944, 2947, 2948, 2957, 2958, 2959, 2960, 2961, 2962, 2965, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2973, 2974, 2975, 2976, 2977, 2978, 2995, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3007, 3008, 3017, 3018, 3019, 3020, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3057, 3058, 3059, 3060, 3095, 3096, 3099, 3100, 3113, 3114, 3115, 3116, 3121, 3122, 3123, 3124, 3133, 3134, 3157, 3158, 3167, 3168, 3171, 3172, 3175, 3176, 3179, 3180, 3189, 3190, 3197, 3198, 3199, 3200, 3205, 3206, 3213, 3214, 3215, 3216, 3223, 3224, 3225, 3226, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239, 3240, 3241, 3242, 3247, 3248, 3257, 3258, 3259, 3260, 3265, 3266, 3267, 3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3293, 3294, 3295, 3296, 3299, 3300, 3305, 3306, 3307, 3308, 3309, 3310, 3313, 3314, 3319, 3320, 3325, 3326, 3337, 3338, 3341, 3342, 3347, 3348, 3351, 3352, 3357, 3358, 3363, 3364, 3365, 3366, 3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3385, 3386, 3387, 3388, 3389, 3390, 3391, 3392, 3405, 3406, 3407, 3408, 3409, 3410, 3427, 3428, 3441, 3442, 3443, 3444, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456, 3477, 3478, 3485, 3486, 3487, 3488, 3495, 3496, 3497, 3498, 3499, 3500, 3503, 3504, 3505, 3506, 3507, 3508, 3521, 3522, 3531, 3532, 3533, 3534, 3535, 3536, 3539, 3540, 3551, 3552, 3553, 3554, 3559, 3560, 3561, 3562, 3569, 3570, 3573, 3574, 3581, 3582, 3585, 3586, 3589, 3590, 3599, 3600, 3601, 3602, 3607, 3608, 3609, 3610, 3613, 3614, 3615, 3616, 3621, 3622, 3633, 3634, 3637, 3638, 3643, 3644, 3653, 3654, 3659, 3660, 3661, 3662, 3685, 3686, 3713, 3714, 3715, 3716, 3717, 3718, 3719, 3720, 3721, 3722, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3734, 3735, 3736, 3737, 3738, 3747, 3748, 3753, 3754, 3763, 3764, 3771, 3772, 3775, 3776, 3805, 3806, 3815, 3816, 3839, 3840, 3841, 3842, 3843, 3844, 3845, 3846, 3847, 3848, 3855, 3856, 3857, 3858, 3861, 3862, 3863, 3864, 3865, 3866, 3869, 3870, 3871, 3872, 3873, 3874, 3875, 3876, 3891, 3892, 3893, 3894, 3911, 3912, 3919, 3920, 3923, 3924, 3927, 3928, 3929, 3930, 3931, 3932, 3937, 3938, 3939, 3940, 3941, 3942, 3943, 3944, 3949, 3950, 3963, 3964, 3965, 3966, 3967, 3968, 3977, 3978, 3979, 3980, 3995, 3996, 3997, 3998, 4003, 4004, 4005, 4006, 4007, 4008, 4009, 4010, 4011, 4012, 4013, 4014, 4035, 4036, 4039, 4040, 4041, 4042, 4043, 4044, 4045, 4046, 4047, 4048, 4057, 4058, 4063, 4064, 4065, 4066, 4083, 4084, 4089, 4090, 4101, 4102, 4107, 4108, 4109, 4110, 4111, 4112, 4115, 4116, 4117, 4118, 4119, 4120, 4121, 4122, 4123, 4124, 4125, 4126, 4127, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4136, 4137, 4138, 4139, 4140, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4152, 4157, 4158, 4171, 4172, 4179, 4180, 4183, 4184, 4191, 4192, 4205, 4206, 4207, 4208, 4209, 4210, 4213, 4214, 4223, 4224, 4227, 4228, 4231, 4232, 4233, 4234, 4267, 4268, 4269, 4270, 4275, 4276, 4277, 4278, 4285, 4286, 4287, 4288, 4289, 4290, 4303, 4304, 4307, 4308, 4309, 4310, 4313, 4314, 4317, 4318, 4327, 4328, 4333, 4334, 4343, 4344, 4349, 4350, 4353, 4354, 4365, 4366, 4375, 4376, 4379, 4380, 4385, 4386, 4387, 4388, 4391, 4392, 4395, 4396, 4397, 4398, 4399, 4400, 4403, 4404, 4407, 4408, 4413, 4414, 4421, 4422, 4423, 4424, 4445, 4446, 4451, 4452, 4465, 4466, 4467, 4468, 4469, 4470, 4471, 4472, 4473, 4474, 4475, 4476, 4477, 4478, 4481, 4482, 4483, 4484, 4489, 4490, 4491, 4492, 4497, 4498, 4499, 4500, 4515, 4516, 4517, 4518, 4519, 4520, 4521, 4522, 4529, 4530, 4531, 4532, 4533, 4534, 4547, 4548, 4549, 4550, 4553, 4554, 4575, 4576, 4577, 4578, 4579, 4580, 4581, 4582, 4583, 4584, 4585, 4586, 4587, 4588, 4589, 4590, 4591, 4592, 4605, 4606, 4607, 4608, 4609, 4610, 4613, 4614, 4615, 4616, 4617, 4618, 4619, 4620, 4641, 4642, 4643, 4644, 4649, 4650, 4657, 4658, 4671, 4672, 4673, 4674, 4675, 4676, 4685, 4686, 4699, 4700, 4701, 4702, 4709, 4710, 4711, 4712, 4721, 4722, 4729, 4730, 4731, 4732, 4737, 4738, 4739, 4740, 4741, 4742, 4755, 4756, 4759, 4760, 4761, 4762, 4763, 4764, 4765, 4766, 4767, 4768, 4769, 4770, 4781, 4782, 4789, 4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797, 4798, 4799, 4800, 4801, 4802, 4803, 4804, 4805, 4806, 4807, 4808, 4809, 4810, 4811, 4812, 4823, 4824, 4825, 4826, 4829, 4830, 4831, 4832, 4847, 4848, 4849, 4850, 4851, 4852, 4853, 4854, 4869, 4870, 4871, 4872, 4873, 4874, 4877, 4878, 4899, 4900, 4901, 4902, 4903, 4904, 4905, 4906, 4907, 4908, 4911, 4912, 4913, 4914, 4919, 4920, 4927, 4928, 4935, 4936, 4941, 4942, 4943, 4944, 4945, 4946, 4949, 4950, 4951, 4952, 4953, 4954, 4967, 4968, 4975, 4976, 4987, 4988, 4997, 4998, 4999, 5000, 5001, 5002, 5017, 5018, 5019, 5020, 5037, 5038, 5045, 5046, 5051, 5052, 5053, 5054, 5057, 5058, 5059, 5060, 5061, 5062, 5069, 5070, 5071, 5072, 5075, 5076, 5077, 5078, 5081, 5082, 5083, 5084, 5085, 5086, 5089, 5090, 5093, 5094, 5099, 5100, 5101, 5102, 5125, 5126, 5131, 5132, 5133, 5134, 5137, 5138, 5139, 5140, 5147, 5148, 5149, 5150, 5151, 5152, 5153, 5154, 5155, 5156, 5157, 5158, 5159, 5160, 5165, 5166, 5167, 5168, 5171, 5172, 5177, 5178, 5185, 5186, 5207, 5208, 5215, 5216, 5217, 5218, 5219, 5220, 5221, 5222, 5223, 5224, 5225, 5226, 5247, 5248, 5249, 5250, 5251, 5252, 5269, 5270, 5273, 5274, 5277, 5278, 5279, 5280, 5281, 5282, 5283, 5284, 5285, 5286, 5307, 5308, 5309, 5310, 5313, 5314, 5323, 5324, 5331, 5332, 5333, 5334, 5335, 5336, 5339, 5340, 5341, 5342, 5355, 5356, 5361, 5362, 5363, 5364, 5371, 5372, 5381, 5382, 5385, 5386, 5389, 5390, 5399, 5400, 5401, 5402, 5403, 5404, 5405, 5406, 5407, 5408, 5415, 5416, 5417, 5418, 5419, 5420, 5425, 5426, 5429, 5430, 5431, 5432, 5439, 5440, 5441, 5442, 5443, 5444, 5445, 5446, 5447, 5448, 5453, 5454, 5455, 5456, 5457, 5458, 5459, 5460, 5469, 5470, 5471, 5472, 5473, 5474, 5479, 5480, 5483, 5484, 5489, 5490, 5491, 5492, 5499, 5500, 5503, 5504, 5505, 5506, 5507, 5508, 5509, 5510, 5517, 5518, 5519, 5520, 5521, 5522, 5523, 5524, 5529, 5530, 5533, 5534, 5535, 5536, 5541, 5542, 5543, 5544, 5563, 5564, 5567, 5568, 5569, 5570, 5571, 5572, 5573, 5574, 5593, 5594, 5607, 5608, 5611, 5612, 5613, 5614, 5615, 5616, 5617, 5618, 5619, 5620, 5621, 5622, 5623, 5624, 5627, 5628, 5629, 5630, 5631, 5632, 5633, 5634, 5635, 5636, 5641, 5642, 5643, 5644, 5645, 5646, 5647, 5648, 5649, 5650, 5655, 5656, 5657, 5658, 5659, 5660, 5661, 5662, 5663, 5664, 5667, 5668, 5669, 5670, 5671, 5672, 5679, 5680, 5681, 5682, 5695, 5696, 5699, 5700, 5703, 5704, 5707, 5708, 5709, 5710, 5713, 5714, 5719, 5720, 5721, 5722, 5723, 5724, 5727, 5728, 5731, 5732, 5733, 5734, 5735, 5736, 5737, 5738, 5747, 5748, 5749, 5750, 5751, 5752, 5763, 5764, 5773, 5774, 5775, 5776, 5777, 5778, 5787, 5788, 5791, 5792, 5797, 5798, 5799, 5800, 5805, 5806, 5809, 5810, 5811, 5812, 5813, 5814, 5815, 5816, 5817, 5818, 5819, 5820, 5823, 5824, 5835, 5836, 5837, 5838, 5839, 5840, 5843, 5844, 5845, 5846, 5847, 5848, 5849, 5850, 5851, 5852, 5853, 5854, 5867, 5868, 5871, 5872, 5873, 5874, 5883, 5884, 5895, 5896, 5919, 5920, 5925, 5926, 5927, 5928, 5929, 5930, 5933, 5934, 5935, 5936, 5937, 5938, 5939, 5940, 5941, 5942, 5943, 5944, 5947, 5948, 5949, 5950, 5951, 5952, 5953, 5954, 5955, 5956, 5957, 5958, 5959, 5960, 5971, 5972, 5977, 5978, 5979, 5980, 5981, 5982, 5983, 5984, 5985, 5986, 5987, 5988, 5989, 5990, 5991, 5992, 5993, 5994, 6003, 6004, 6005, 6006, 6011, 6012, 6013, 6014, 6015, 6016, 6017, 6018, 6019, 6020, 6023, 6024, 6027, 6028, 6031, 6032, 6033, 6034, 6049, 6050, 6051, 6052, 6053, 6054, 6055, 6056, 6059, 6060, 6079, 6080, 6083, 6084, 6087, 6088, 6101, 6102, 6113, 6114, 6117, 6118, 6119, 6120, 6125, 6126, 6129, 6130, 6137, 6138, 6161, 6162, 6171, 6172, 6173, 6174, 6177, 6178, 6179, 6180, 6181, 6182, 6183, 6184, 6185, 6186, 6187, 6188, 6191, 6192, 6195, 6196, 6201, 6202, 6203, 6204, 6219, 6220, 6225, 6226, 6227, 6228, 6233, 6234, 6235, 6236, 6237, 6238, 6239, 6240, 6241, 6242, 6243, 6244, 6245, 6246, 6249, 6250, 6269, 6270, 6271, 6272, 6275, 6276, 6283, 6284, 6289, 6290, 6291, 6292, 6293, 6294, 6297, 6298, 6299, 6300, 6301, 6302, 6313, 6314, 6315, 6316, 6317, 6318, 6321, 6322, 6323, 6324, 6325, 6326, 6329, 6330, 6349, 6350, 6351, 6352, 6353, 6354, 6359, 6360, 6365, 6366, 6367, 6368, 6369, 6370, 6373, 6374, 6379, 6380, 6387, 6388, 6389, 6390, 6391, 6392, 6401, 6402, 6403, 6404, 6415, 6416, 6417, 6418, 6421, 6422, 6439, 6440, 6441, 6442, 6443, 6444, 6445, 6446, 6447, 6448, 6453, 6454, 6455, 6456, 6457, 6458, 6477, 6478, 6479, 6480, 6493, 6494, 6495, 6496, 6505, 6506, 6507, 6508, 6513, 6514, 6515, 6516, 6523, 6524, 6527, 6528, 6531, 6532, 6535, 6536, 6537, 6538, 6541, 6542, 6545, 6546, 6551, 6552, 6553, 6554, 6555, 6556, 6583, 6584, 6589, 6590, 6603, 6604, 6607, 6608, 6613, 6614, 6621, 6622, 6623, 6624, 6625, 6626, 6629, 6630, 6635, 6636, 6639, 6640, 6649, 6650, 6651, 6652, 6653, 6654, 6655, 6656, 6659, 6660, 6669, 6670, 6675, 6676, 6677, 6678, 6679, 6680, 6681, 6682, 6683, 6684, 6699, 6700, 6711, 6712, 6729, 6730, 6731, 6732, 6733, 6734, 6737, 6738, 6739, 6740, 6741, 6742, 6749, 6750, 6751, 6752, 6753, 6754, 6755, 6756, 6757, 6758, 6761, 6762, 6763, 6764, 6765, 6766, 6767, 6768, 6771, 6772, 6773, 6774, 6775, 6776, 6781, 6782, 6783, 6784, 6785, 6786, 6787, 6788, 6789, 6790, 6795, 6796, 6797, 6798, 6801, 6802, 6803, 6804, 6809, 6810, 6811, 6812, 6817, 6818, 6819, 6820, 6831, 6832, 6835, 6836, 6837, 6838, 6839, 6840, 6841, 6842, 6843, 6844, 6845, 6846, 6847, 6848, 6849, 6850, 6851, 6852, 6857, 6858, 6859, 6860, 6861, 6862, 6863, 6864, 6865, 6866, 6869, 6870, 6871, 6872, 6875, 6876, 6877, 6878, 6883, 6884, 6887, 6888, 6903, 6904, 6909, 6910, 6913, 6914, 6915, 6916, 6917, 6918, 6927, 6928, 6929, 6930, 6931, 6932, 6935, 6936, 6937, 6938, 6939, 6940, 6943, 6944, 6947, 6948, 6951, 6952, 6963, 6964, 6965, 6966, 6967, 6968, 6969, 6970, 6973, 6974, 6975, 6976, 6979, 6980, 6981, 6982, 6991, 6992, 6995, 6996, 6997, 6998, 6999, 7000, 7009, 7010, 7011, 7012, 7015, 7016, 7017, 7018, 7019, 7020, 7049, 7050, 7067, 7068, 7077, 7078, 7085, 7086, 7087, 7088, 7089, 7090, 7093, 7094, 7103, 7104, 7105, 7106, 7119, 7120, 7125, 7126, 7135, 7136, 7143, 7144, 7151, 7152, 7153, 7154, 7155, 7156, 7157, 7158, 7159, 7160, 7171, 7172, 7181, 7182, 7185, 7186, 7193, 7194, 7195, 7196, 7197, 7198, 7199, 7200, 7209, 7210, 7219, 7220, 7221, 7222, 7231, 7232, 7243, 7244, 7247, 7248, 7251, 7252, 7265, 7266, 7281, 7282, 7283, 7284, 7287, 7288, 7297, 7298, 7301, 7302, 7303, 7304, 7305, 7306, 7307, 7308, 7315, 7316, 7317, 7318))

Please read the official documentation about this, and upgrade by hand.
``

**Comment by JC5** [comment]
Is there a stack trace in your log files? I'd like to know where the problem occurred exactly.

**Comment by Nik-vr** [comment]
My log-files:

[ff3-apache2handler-2019-08-24.log](https://github.com/firefly-iii/firefly-iii/files/3538092/ff3-apache2handler-2019-08-24.log)
[ff3-cli-2019-08-24.log](https://github.com/firefly-iii/firefly-iii/files/3538093/ff3-cli-2019-08-24.log)

**Comment by JC5** [comment]
I've pushed a fix that you could apply to your own code, if you want to. It involves replacing the code of two functions with the code of the fix.

Find [this line](https://github.com/firefly-iii/firefly-iii/blob/master/app/Console/Commands/Upgrade/BackToJournals.php#L155) in your code, and replace everything between `{` and `}` with the code between the brackets of [this code](https://github.com/firefly-iii/firefly-iii/blob/develop/app/Console/Commands/Upgrade/BackToJournals.php#L156).

Do the same with [this function](https://github.com/firefly-iii/firefly-iii/blob/master/app/Console/Commands/Upgrade/BackToJournals.php#L206) and [this replacement](https://github.com/firefly-iii/firefly-iii/blob/develop/app/Console/Commands/Upgrade/BackToJournals.php#L211).

**Comment by Nik-vr** [comment]
I replace code, login in my Firefly III installation, and got the same error message :(

[ff3-apache2handler-2019-08-25.log](https://github.com/firefly-iii/firefly-iii/files/3538211/ff3-apache2handler-2019-08-25.log)
[ff3-cli-2019-08-24.log](https://github.com/firefly-iii/firefly-iii/files/3538212/ff3-cli-2019-08-24.log)

A new log file (ff3-cli-2019-08-25) has not been created. In folder only ff3-cli-2019-08-24.

**Comment by JC5** [comment]
No worries, we can fix that one as well!

1. Replace [old function](https://github.com/firefly-iii/firefly-iii/blob/master/app/Console/Commands/Upgrade/BackToJournals.php#L84) with [new function](https://github.com/firefly-iii/firefly-iii/blob/develop/app/Console/Commands/Upgrade/BackToJournals.php#L85)
2. Replace [another old function](https://github.com/firefly-iii/firefly-iii/blob/master/app/Console/Commands/Upgrade/BackToJournals.php#L96) with [another new function](https://github.com/firefly-iii/firefly-iii/blob/develop/app/Console/Commands/Upgrade/BackToJournals.php#L105)

Let me know if it works :+1:

**Comment by Nik-vr** [comment]
Now the error message has changed a bit:

An unknown error prevented Firefly III from executing the upgrade commands. Sorry. SQLSTATE[HY000]: General error: 1 too many SQL variables (SQL: select * from "transaction_journals" where "id" in (27, 27, 34, [... there are many more id's... ] 3445, 3445) and "transaction_journals"."deleted_at" is null)

**Comment by JC5** [comment]
Did you replace both?

This is weird because that's all the code there is that's doing large replacements. I'll do some googling but I'm kind of lost, sorry about that.

**Comment by JC5** [comment]
Are you using SQLite?

**Comment by Nik-vr** [comment]
I replace both (getIdsForBudgets and  getIdsForCategories) functions. 

Yes, I use SQLite DB.

**Comment by JC5** [comment]
The fix limits the number of ID's to 50. There may be other commands where this is happening. So keep posting stack traces.

I can strongly recommend you to migrate to MySQL or Postgresql though.

**Comment by Nik-vr** [comment]
> I can strongly recommend you to migrate to MySQL

I would gladly switch to MySQL, but there is one problem. I use Firefly III on a shared hosting. And I can’t correctly update my Firefly installation on my server (on the server there is no way to use GIT, Composer, etc.). Now I am doing it simply: copy the database to the local server (where the Composer is), update the Firefly, and copy the updated Firefly along with the database back to the hosting. As soon as the opportunity arises to painlessly upgrade the Firefly with the MySQL database on a shared hosting, I will be happy to switch to MySQL. In the meantime, I have to use SQLite.

**Comment by JC5** [comment]
Could you also use the same routine with MySQL? You could use something like Vagrant or Virtualbox to maintain a Linux image with a MySQL database in it.

**Comment by JC5** [comment]
But it's tricky, I admit it.

**Comment by Nik-vr** [comment]
This is too complicated a procedure. I would not want to make so much effort to update one software.

Perhaps there is a way to somehow simplify the process of updating Firefly? At least so: download the full distribution kit of the new version, replace all the files on the server, run the update script.

**Comment by Nik-vr** [comment]
Now I try to update from my 4.7.17 to 4.8.1.1.  And I get in console new error message:

```
In Connection.php line 664:

  SQLSTATE[HY000]: General error: 1 too many SQL variables (SQL: select count(*) as aggrega
  te from "transaction_groups" where "deleted_at" is null and "id" not in (139, 140, 141, 1
  ..............here is many transactions id's..............
   125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138) and "transaction_g
  roups"."deleted_at" is null)

In PDOConnection.php line 63:

  SQLSTATE[HY000]: General error: 1 too many SQL variables
```

**Comment by JC5** [comment]
Could you extract the stack trace from the log files?

**Comment by Nik-vr** [comment]
Log attached:

[ff3-cli-2019-10-02.log](https://github.com/firefly-iii/firefly-iii/files/3681814/ff3-cli-2019-10-02.log)

**Comment by JC5** [comment]
I pushed a fix to the develop branch. If you run across other instances, please open a new ticket. It's easier for me to track :)
