### ISSUE TITLE
API: Wrong "indentation" when POSTing TransactionLink 

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [firefly-iii/firefly-iii#2485]
**Bug description**
I am running Firefly III version develop, and my problem is:

Creating a new TransactionLink returns data that don't have an `attribute` field, and what was supposed to be in the `attribute` field is in the `data` field instead.

See for yourself:

```json
{
    "data": {
        "id": 21,
        "created_at": "2019-08-25T15:41:49+02:00",
        "updated_at": "2019-08-25T15:41:49+02:00",
        "inward_id": 301,
        "outward_id": 1041,
        "notes": "Heh",
        "links": [
            {
                "rel": "self",
                "uri": "\/transaction_links\/21"
            }
        ]
    }
}
```

**What works**
Listing links is fine. (can't say about GETing a Link because there's no path for this)

**Comment by JC5** [comment]
That's a weird one. I'll check it out.

**Comment by JC5** [comment]
There is a path to get a single transaction link, just add the ID. Might be undocumented though, sorry about that.

As for the issue, it should now be fixed.

**Comment by GeoffreyFrogeye** [comment]
> There is a path to get a single transaction link, just add the ID. Might be undocumented though, sorry about that.

Oh, ok. Never thought of just trying :sweat_smile:. I'll add the documentation then.

**Comment by GeoffreyFrogeye** [comment]
Can confirm it to be working! I'll add the documentation for the GET call, once I'm done with https://github.com/firefly-iii/api-docs-generator/pull/23 (my commit history is very messed up and I don't want to worsen it).
