### ISSUE TITLE
Auto completion of Description field not reflected in stored transaction 

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2486]
I am running Firefly III version 4.8.0.3.

When I enter a new transaction and choose an auto completion option in the Description field, the stored transaction uses the partially-entered field instead of the full text from the drop down.

For example - enter a new transaction, start typing "Amaz" in the Description field, choose "Amazon" from the suggestions, and save.

View the transaction. It will have "Amaz" in the Description instead of "Amazon".

**Comment by JC5** [comment]
I think there was an issue opened about this not an hour ago. I’m on my phone so I can’t easily check.

**Comment by hamfactorial** [comment]
Ah, yes you're right. This is a duplicate of #2484.
