### ISSUE TITLE
HTTP 404 after deleting a tag on 4.8.0.3

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2488]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
The problem is extremely similar to what Github suggest (#2175 and #2159). Though it seems to have been fixed in 4.7 I just encountered it in 4.8.

**Steps to reproduce**

1. Navigate to the tags (in my case `https://<domain>/tags`)
2. Open a tag (in my case `https://<domain>/tags/show/12`)
3. Display all transaction for this tag (in my case `https://<domain>/tags/show/12/all`)
4. Delete the tag (in my case `https://<domain>/tags/delete/12`)
5. Redirect to all the transaction of the deleted tag, causing the 404 (in my case `https://<domain>/tags/show/12/all`)

![image](https://user-images.githubusercontent.com/1266495/63688816-ac72a980-c808-11e9-9b7f-fae354784d8f.png)

**Expected behavior**
I believe it should go back to the list of tags.

**Extra info**
Browser is  Chrome on Windows 10.
Firefly is running in a pretty standard Docker deployment with docker-compose.
I'm using the images `postgres:10` and `jc5x/firefly-iii:latest`. 
```
$ docker-compose images
   Container          Repository       Tag       Image Id      Size
--------------------------------------------------------------------
firefly            jc5x/firefly-iii   latest   85389bd5f1e7   636 MB
firefly-database   postgres           10       cf7301675e30   219 MB
```

**Bonus points**
The log is pretty straightforward:
```
firefly | 172.18.0.2 - - [26/Aug/2019:13:40:10 +0200] "GET /tags/show/12 HTTP/1.1" 200 7026 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
firefly | 172.18.0.2 - - [26/Aug/2019:13:40:29 +0200] "GET /tags/show/12/all HTTP/1.1" 200 6838 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
firefly | 172.18.0.2 - - [26/Aug/2019:13:40:41 +0200] "GET /tags/delete/12 HTTP/1.1" 200 6036 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
firefly | 172.18.0.2 - - [26/Aug/2019:13:40:45 +0200] "POST /tags/destroy/12 HTTP/1.1" 302 2005 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
firefly | 172.18.0.2 - - [26/Aug/2019:13:40:45 +0200] "GET /tags/show/12/all HTTP/1.1" 404 5087 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
```
I believe I'm properly running the latest image:
```
$ docker-compose exec app head changelog.md
# Change Log
All notable changes to this project will be documented in this file.
This project adheres to [Semantic Versioning](http://semver.org/).

## [4.8.0.3 (API 0.10.1)] - 2019-08-23

Fixes many other issues in the previous release.

### Added
- Autocomplete for transaction description.
```
Do not hesitate if you need any other logs or command output !

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
This will be fixed in the next release.
