### ISSUE TITLE
Docker image architecture issues for rPi

### ISSUE THREAD

**Issue by aTable** [firefly-iii/firefly-iii#2489]
**Bug description**
Using latest docker images do not work on rPi.
- `jc5x/firefly-iii:latest` (expected failure)
- `jc5x/firefly-iii:latest-arm` (unexpected failure)
- `jc5x/firefly-iii:develop-arm` (unexpected failure)

I couldn't find any more specific arm images e..g `jc5x/firefly-iii:latest-arm32v7`. I had this running a few months ago so this definitely worked. The pi itself is untouched since so I don't think there are external environment issues. Am I missing something or could there be an oopsie for pi users?

**Steps to reproduce**
* use the [docker-compose.yml](https://github.com/firefly-iii/firefly-iii/blob/master/docker-compose.yml) 
* use the [.env.example](https://github.com/firefly-iii/firefly-iii/blob/master/.env.example) 
* `docker-compose up`
![image](https://user-images.githubusercontent.com/2154448/63692698-9f2fdc00-c855-11e9-8e6d-49a17986a435.png)

**Expected behavior**
Expecting to not run into docker architecture issues. Expecting to have config problems from copy pasting

**Comment by JC5** [comment]
I pushed a fix for the `develop-arm` tag. Could you try it?

**Comment by aTable** [comment]
Thanks for the quick response! Looks like it's resolved and now to fix my configs

Cheers

![image](https://user-images.githubusercontent.com/2154448/63725521-f5c10880-c89d-11e9-8e2f-b0afac1a4314.png)
