### ISSUE TITLE
Submitting new transaction fails to create a new empty form

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2490]
4.8.0.3 here:
Adding a new transaction and checking both boxes:
 
- After storing, return here to create another one.
- Reset form after submission

I hit the "Submit" Button and the transaction is correctly recorded in the db. However, the next page shows the same transaction data and adds one more split than was previously visible in the form.

So, hitting "Submit" acts more, like "Submit, add a split and DO NOT Reset form after submission" :-)

UPDATE: When I uncheck the "Reset form after submission", no added split is shown in the subsequent page (and the form is not reset, so things behave as they should)

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
Will be fixed in the next release.
