### ISSUE TITLE
<TAB> in description in transaction form ends up in a weird place

### ISSUE THREAD

**Issue by spaetz** [firefly-iii/firefly-iii#2491]
Since 4.8.0.3 hitting <TAB> does not jump to the next field in the transaction form (previously it would jump into the source account field), it ends up in a weird place on the page, including "logout" and other places (which are not obvious but not in the transaction form).

**Comment by JC5** [comment]
Thanks, I'll see what's happening.

**Comment by ilvez** [comment]
Maybe should open new ticket about it, but another bug seems that clicking/pressing enter on suggested description from dropdown fills the input field, but later when submitting create/update, the description value stays half-filled (at the point where click/enter on selection was pressed).

If you want can open this to separate ticket.

**Comment by JC5** [comment]
@ilvez see #2484

**Comment by JC5** [comment]
Which browser are you using? It seems to jump around pretty normal for me. It could be that this was fixed through another issue already.

**Comment by spaetz** [comment]
Using Firefox (60 & 68) in with windows and Linux. Weird, will retest.

Am 27. August 2019 07:03:38 MESZ schrieb James Cole <notifications@github.com>:
>Which browser are you using? It seems to jump around pretty normal for
>me. It could be that this was fixed through another issue already.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/firefly-iii/firefly-iii/issues/2491#issuecomment-525138546

-- 
Sent from mobile device. Please excuse brevity and tpyos.

**Comment by JC5** [comment]
I haven't been able to find anything weird but keep me posted. The bot will close this issue in about 14 days, feel free to open a new one or reply if something comes up.
