### ISSUE TITLE
Required field errors are not cleared upon form submitting when "After storing, return here to create another one" is checked on 4.8.0.3

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2492]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
When I submitted the new transaction form I forgot to fill the `Description` field and triggered the message "`The description field is required.`".

![image](https://user-images.githubusercontent.com/1266495/63705307-24eb6180-c82d-11e9-9f8b-df9ae686bac9.png)

After fixing the issue and submitting the form again, the message was still appearing.

**Steps to reproduce**
1. Create a new transaction
2. Fill every required field properly **except** the `Description` field
3. Tick the `After storing, return here to create another one.` checkbox
4. Submit the form and trigger the message
5. Correct the mistake
6. Submit the form again and the error message will still be present

**Expected behavior**
I believe the error message should clear upon successful form submission, when a success message appears.

![image](https://user-images.githubusercontent.com/1266495/63705507-988d6e80-c82d-11e9-9f33-61f841a398aa.png)

Those two messages are contradictory.
Not sure if the `Reset form after submission` checkbox is suppose to take care of that.

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by spaetz** [comment]
Actually, is there a reason, the description is necessary at all? I have some rules that set the description based on source and destination accounts, but I cannot leave the description empty.

Also, sometimes there is no need for a descriptions, such as src:Checking dst:DiscounterA (there is no need to describe that I bought groceries there).

**Comment by JC5** [comment]
The description is required, yes. You could use rules to set a default description but the submission requires something, anything.

**Comment by JC5** [comment]
The issue will be fixed in the next release.
