### ISSUE TITLE
Cannot escape the Transaction Type once Firefly has auto-detected it on the new Transaction form

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2493]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
The title is a bit vague not to make it too long. Not sure if it is a bug per se but in terms of functionality it does feel like a regression.

When you are adding a new transaction, from what I understand the `Source account` and `Destination account` are detecting which type of transaction is being entered following those `(Source, Destination) -> Type` rules (not sure if it is exhaustive):
- `(Asset, Asset) -> Transfer`
- `(Asset, *) -> Withdrawal`
- `(*, Asset) -> Deposit`

When the Type is not yet determined, the auto-complete fields are suggesting anything that is registered in Firefly.
When the Type is determined, the auto-complete fields are limiting what each field will suggest.

There is no way to clear or change the transaction Type once it is set by Firefly. The only way I found is to refresh the web page.

This causes two usability issues:
- You cannot make a mistake in which account you select
-  If you are using `After storing, return here to create another one.` you are stuck in the same transaction Type. I usually use this mode to keep the date, which is useful when you are clearing a backlog of transactions from the same day.

In 4.7, there was a series of button to select the transaction Type in the form.

**Steps to reproduce**
1. Create a new transaction
2. Select one of your assets as `Source account`
3. Select one of your expanse accounts as `Destination account`
4. Firefly will display `You're creating a Withdrawal`
5. Try to change the `Destination account` to on of your assets to change the Type to a Transfer. The auto-completion returns nothing.

**Expected behavior**
There should be a way to clear or change the Transaction type from the form.

**Extra info**
No error logs in the browser JavaScript console besides a bunch of
```
Is a string.
selectedItem()
```

![image](https://user-images.githubusercontent.com/1266495/63707624-a42f6400-c832-11e9-81b3-dbcf3aede15d.png)

**Bonus points**
n/a

**Comment by JC5** [comment]
What about the trash icons next to the account names?

**Comment by gregoo** [comment]
Yes it does clear the Transaction type !
Thank you for the info.

It is not as intuitive as before but it does work (-:

**Comment by JC5** [comment]
I know, I'm not good enough with Vue yet to make it better. I'll pick this up as a "bug" to see if I can react to your way of working and make it more intuitive.

**Comment by gregoo** [comment]
One "keyboard-way" to keep it automatic could be detecting when someone insists on the field.
For instance if there is no result for the auto-completion and stuff is still typed, trigger the reset of the Type and display global suggestions again ?

**Comment by JC5** [comment]
I think I can do that. Try this in the next release.
