### ISSUE TITLE
Asset balance is missing from Source/Destination fields in new transaction form on 4.8.0.3

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2494]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
In Firefly 4.7, when you selected an asset from the drop down list for `Source` or `Destination`, there was the current balance of each asset directly in the list.

This was useful to track that I wasn't making any major typos by tracking the evolution of the account balance directly from the form.

**Steps to reproduce**
1. Type an asset name in the `Source` field
2. The suggestion doesn't display any balance

**Expected behavior**
The balance is displayed next to the asset name. For instance: `Savings (€1234)`

**Comment by JC5** [comment]
Yep, good idea.

**Comment by JC5** [comment]
The next version of Firefly III will feature this again.

**Comment by Kline-** [comment]
The balance in the drop down only reflects the current day balance. It doesn't take into account any pending/future transactions already added. This is different behavior from other pages such as the home screen, where the balance displayed reflects future transactions as well.
