### ISSUE TITLE
No indication that a transaction has been posted after the second one when using "After storing, return to create another one." on 4.8.0.3

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2495]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
When you tick the `After storing, return here to create another one.` checkbox, you stay on the form page and a green banner appears telling you that your transaction has been stored.

![image](https://user-images.githubusercontent.com/1266495/63710908-8e25a180-c83a-11e9-8d78-f0034a49a682.png)

When you post a second transaction, there is no visual information telling you anything was done.
Since the banner does not clear itself, this visual indication is not refreshed. And since the form is posted behind the scenes, nothing moves on the form page. You stay were you are in the page if you scrolled it, and your cursor stays in the last field you were editing if you posted the form with the `Return` key.

**Steps to reproduce**
1. Create a new transaction
2. Fill the form
3. Tick the `After storing, return here to create another one.` checkbox
4. Submit the form using the `Submit` button
5. The `Success!` banner should appear on top of the form. Check the transaction ID in the banner link.
6. Change some values in the form
7. Place your cursor in the `Internal reference` field
8. Press the `Enter` key. The form has been posted, however nothing seem to have changed on the page.
9. Check the link in the `Success` banner, the transaction ID should have changed.

**Expected behavior**
I would expect visual indicator that my transaction has been properly posted.

Also I would love for my cursor to go back to the top of the form, as I'm likely to change stuff in the form, that would prevent me from `Shift + Tab`'ing my way up to the top of the form. Also If my form has been scrolled down, I would expect the submission to scroll the page back up to the top of the form, where the cursor has been moved.

If people mash the `Enter` key believing the transaction has not been posted, they will post the same one multiple time without any indication.

**Suggestion**
For the visual indicator:
One way to do it without changing much of the form design would be to simply make the banner flash if it is already existing and already in the same state. Also displaying the transaction number in the banner rather than simply "The transaction" would help track if stuff happened.
This simple solution has a caveat. If the form is scrolled all the way down, since the form does not scroll up or move the cursor, the user may miss the flashing/change in the banner.

A more complete solution would be a floating modal notification that would display at the top of the page no matter where it is scrolled and that would auto clear itself after some time.

For the cursor:
Focusing the `Description` field and a `scrollTo` the cursor would be good.

**Extra info**
Using Chrome browser on Windows 10.
Screen resolution is 1920x1080 on a XPS13 11" screen, no zoom.

**Comment by JC5** [comment]
Yes that's pretty annoying, I know. Thanks for the expansive report, I'll pick it up.

**Comment by derekprovance** [comment]
Something as simple as Success! Transaction <id> has been stored would be nice or a decent work around until better UX can be designed.

**Comment by JC5** [comment]
Will be a bit better in the next release.
