### ISSUE TITLE
During migration to 4.8.0.3 sql error occurs

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2496]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

on the login screen I see:
 

> An unknown error prevented Firefly III from executing the upgrade commands. Sorry. SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'transaction_group_id' (SQL: alter table `transaction_journals` add `transaction_group_id` int unsigned null after `transaction_type_id`)

Looking at docker logs, I see:

> Migrating: 2019_03_22_183214_changes_for_v480
> 
> 
> In Connection.php line 664:
> 
>                                                                                
> 
>   SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'transac  
> 
>   tion_group_id' (SQL: alter table `transaction_journals` add `transaction_gr  
> 
>   oup_id` int unsigned null after `transaction_type_id`)                       
> 
>                                                                                
> 
> 
> In PDOStatement.php line 119:
> 
>                                                                                
> 
>   SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'transac  
> 
>   tion_group_id'                                                               
> 
>                                                                                
> 
> 
> In PDOStatement.php line 117:
> 
>                                                                                
> 
>   SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'transac  
> 
>   tion_group_id'                                                               
> 
>                                                                                
> 
> 
> Going to decrypt the database.

**Steps to reproduce**
Not sure....

**Expected behavior**
Migration done successfully 

**Extra info**
cant get to debug page

**Comment by JC5** [comment]
Reset your database to before you upgraded and run the commands again. For some reason they executed twice. Perhaps an earlier command broke.

I suggest you do this on the command line.

1. Reset database.
2. Upgrade Firefly III code
3. Run `php artisan migrate --seed`
4. Run `php artisan firefly-iii:upgrade`

**Comment by JC5** [comment]
Well that's a first for me too. Glad to hear it works :grin:
