### ISSUE TITLE
Posting the Transaction form from a Split field triggers the split deletion on 4.8.0.3

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2498]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
If you press the `Return` key from a field in a Split section of the form, it triggers the deletion of the split rather than not deleting everything that was entered.

Fresh form with 2 Splits:
![image](https://user-images.githubusercontent.com/1266495/63717147-dbf4d680-c847-11e9-9759-664244a98036.png)

Upon pressing the `Return` key:
![image](https://user-images.githubusercontent.com/1266495/63717191-f2029700-c847-11e9-91fa-ec662c2b6915.png)

**Steps to reproduce**
1. Create a new Transaction
2. Press the `Add another split` button
3. Focus the `Internal reference` field of the second split
4. Press the `Return` key and watch the split disappear

Steps are reproducible for any amount of splits by the way. It closes the focused one every time.

**Expected behavior**
The default behaviour is a design thing that I leave to the hands of the application designer, however deletion does not seem to be the expected behaviour.
Some ideas:
- Nothing
- Posting the form, like it would if the transaction wasn't split

**Extra info**
Browser is Chrome on Windows 10.

**Comment by JC5** [comment]
I think there is an issue about this already.

**Comment by gregoo** [comment]
Ah crap I didn't find it while searching

**Comment by JC5** [comment]
No that's a different one. I'll check it out.

**Comment by JC5** [comment]
This should also be fixed in the next release.
