### ISSUE TITLE
Transaction link `Transaction` auto-completion gives incoherent results on 4.8.0.3 (id vs transaction_group_id)

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2499]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
When I try to link two transaction using their IDs, and therefore inputting only the digits of the ID of the target transaction in the `Transaction` field, I get results not matching my query.
For instance, `41` returns `#62`, and to get `#41` I must input `20`.

(Bear with me here, I'm trying to understand the code 😄) From what I've understood of the code, what I'm trying to do is a correct workflow. This block triggers a search by ID if the search is numeric only: https://github.com/firefly-iii/firefly-iii/blob/f090a9534fb1c5fc9f0be0ac477dae393cf48b83/app/Http/Controllers/Json/AutoCompleteController.php#L198-L203

Here is transaction number 41 that I'm trying to link:
![image](https://user-images.githubusercontent.com/1266495/63721409-832a3b80-c851-11e9-96d7-4c9cc12b5902.png)

And here is transaction number 40 from which I'm trying to link:
![image](https://user-images.githubusercontent.com/1266495/63721512-b40a7080-c851-11e9-9196-f7c6b2f4f844.png)

When I'm typing `41` in the Link form, I get `#62: -` as an answer (the `description` is correct) which is the wrong ID:
![image](https://user-images.githubusercontent.com/1266495/63721588-d7cdb680-c851-11e9-84ba-221369d14fc1.png)

And obviously if I link using this ID, I'm getting the wrong transaction linked:
![image](https://user-images.githubusercontent.com/1266495/63721641-f03dd100-c851-11e9-9404-23723955e681.png)

To get the proper transaction linked, I must use `20` in the Link form:
![image](https://user-images.githubusercontent.com/1266495/63721708-1499ad80-c852-11e9-91a7-fb6eef85dad5.png)

From what I've gathered from the network traces of the browser, the `62` that I'm getting as an answer is from the `transaction_group_id` field, rather than the `id` field.
 
```json
[{
	"id": 41,  //<== the ID I searched
	"created_at": "2019-05-14 23:38:02",
	"updated_at": "2019-05-14 23:38:02",
	"deleted_at": null,
	"user_id": 1,
	"transaction_type_id": 1,
	"bill_id": null,
	"transaction_currency_id": 1,
	"description": "-",
	"date": "2005-01-03 00:00:00",
	"interest_date": null,
	"book_date": null,
	"process_date": null,
	"order": 0,
	"tag_count": 0,
	"completed": true,
	"transaction_group_id": 62, //<== the transaction group ID I'm getting
	"name": "#62: -"
}]
```

So it's a bit weird that it is using the Group ID to link an ID (not sure which are the differences here).

A bit of SQL-fu in the database helped me find that I had to input `20` to grab transaction `41`
```sql
firefly=# SELECT id, transaction_group_id FROM transaction_journals WHERE transaction_group_id='41';
 id | transaction_group_id
----+----------------------
 20 |                   41
(1 row)

firefly=# SELECT id, transaction_group_id FROM transaction_journals WHERE id='41';
 id | transaction_group_id
----+----------------------
 41 |                   62
(1 row)
```

**Steps to reproduce**
1. Create enough transactions to have some diversity in IDs
2. Open a transaction
3. Click the `Link transaction` button
4. Input only the digits of the ID of another transaction in the `Transaction` field and the auto-completion should give you a strange result

**Expected behavior**
I would expect the exact transaction corresponding to the ID to be returned if I'm using only digits.

**Extra info**
See above in the description.

**Comment by gregoo** [comment]
I'm seeing that `id` is used here to perform the search: https://github.com/firefly-iii/firefly-iii/blob/142a488ab3e469ef259220b33366c114f88ec269/app/Repositories/Journal/JournalRepository.php#L132-L135

And `transaction_group_id` is used here on the search results: https://github.com/firefly-iii/firefly-iii/blob/f090a9534fb1c5fc9f0be0ac477dae393cf48b83/app/Http/Controllers/Json/AutoCompleteController.php#L209-L212

Could this explain the inconsistency ?

**Comment by gregoo** [comment]
While I'm at it 😄,
when displaying in the transaction, the Link shows the correct IDs and clicking on the description brings me to the other transaction as expected:
![image](https://user-images.githubusercontent.com/1266495/63725180-ef10a200-c859-11e9-812b-c46ffb71943e.png)
(From `/transactions/show/41` the description links to `/transactions/show/40` and vice-versa)

However, when I'm looking at the same link from the Administration page (`/admin/links/show/2`), it links to the `transaction_group_id` fields and thus to the wrong transactions.
![image](https://user-images.githubusercontent.com/1266495/63725365-6f370780-c85a-11e9-8ca9-a183062cec8c.png)
(Inward links to `/transactions/show/20` and Outward links to `/transactions/show/19`, which is the content of the `journal_links` table
```sql
firefly=# SELECT id, transaction_group_id FROM transaction_journals WHERE transaction_group_id='41';
 id | transaction_group_id
----+----------------------
 20 |                   41
(1 row)

firefly=# SELECT * FROM journal_links WHERE source_id='20';
 id |     created_at      |     updated_at      | link_type_id | source_id | destination_id | comment
----+---------------------+---------------------+--------------+-----------+----------------+---------
  2 | 2019-08-26 22:21:53 | 2019-08-26 23:32:13 |            2 |        20 |             19 |
(1 row)```
)

**Comment by JC5** [comment]
See #2470

**Comment by JC5** [comment]
And yes, it searches for the wrong ID which is why you get borked results. Thanks for the expansive bug report guys, I was able to find the issue in 3 minutes flat. A fix will be waiting in the new release.
