### ISSUE TITLE
Error when trying to edit transactions

### ISSUE THREAD

**Issue by seandempsay** [firefly-iii/firefly-iii#2500]
Hello! I emailed you earlier today before I realized that adding this to Github would probably work better for you :)
So I just got this installed and I’m loving it so far, but I ran into a bit of a problem and I can’t find anyone else with the same issue/error. I’m new to this so maybe I’m doing something wrong but I’m getting an error when I try to edit/update any transaction. I can create transactions. I can delete them. But if I try to edit them, I receive an error. Looking into the logs I see this, and I’m thinking that this is the problem, “TransactionUpdateRequest::getOriginalType() must be of the type integer, string given.”

Maybe I’m doing something wrong and you can point me in the right direction? Or maybe I ran into a bug? I don’t know but would appreciate you looking in to this for me. The app is great, btw, thanks! Let me know if I can provide any more data to help you out.

[2019-08-27 03:31:41] local.ERROR: Exception is: {"class":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","errorMessage":"Argument 1 passed to FireflyIII\\Api\\V1\\Requests\\TransactionUpdateRequest::getOriginalType() must be of the type integer, string given, called in \/home\/bobu\/public_html\/Firefly\/app\/Validation\/TransactionValidation.php on line 244","time":"Tue, 27 Aug 2019 03:31:41 +0200","file":"\/home\/bobu\/public_html\/Firefly\/app\/Validation\/TransactionValidation.php","line":433,"code":0,"version":"4.8.0.3","url":"https:\/\/bob.us\/Firefly\/public\/api\/v1\/transactions\/1?_token=test","userAgent":"Mozilla\/5.0 (iPad; CPU OS 13_0 like Mac OS X) AppleWebKit\/605.1.15 (KHTML, like Gecko) FxiOS\/18.2b15817 Mobile\/15E148 Safari\/605.1.15","json":true}  
[2019-08-27 03:31:41] local.ERROR: Argument 1 passed to FireflyIII\Api\V1\Requests\TransactionUpdateRequest::getOriginalType() must be of the type integer, string given, called in /home/bobu/public_html/Firefly/app/Validation/TransactionValidation.php on line 244 {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to FireflyIII\\Api\\V1\\Requests\\TransactionUpdateRequest::getOriginalType() must be of the type integer, string given, called in /home/bobu/public_html/Firefly/app/Validation/TransactionValidation.php on line 244 at /home/bobu/public_html/Firefly/app/Validation/TransactionValidation.php:433)
[stacktrace]
#0 /home/bobu/public_html/Firefly/app/Validation/TransactionValidation.php(244): FireflyIII\\Api\\V1\\Requests\\TransactionUpdateRequest->getOriginalType('1')
firefly-iii/docs#1 /home/bobu/public_html/Firefly/app/Api/V1/Requests/TransactionUpdateRequest.php(246): FireflyIII\\Api\\V1\\Requests\\TransactionUpdateRequest->validateAccountInformationUpdate(Object(FireflyIII\\Validation\\FireflyValidator))
firefly-iii/docs#2 [internal function]: FireflyIII\\Api\\V1\\Requests\\TransactionUpdateRequest->FireflyIII\\Api\\V1\\Requests\\{closure}(Object(FireflyIII\\Validation\\FireflyValidator))
firefly-iii/docs#3 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(253): call_user_func_array(Object(Closure), Array)
firefly-iii/docs#4 [internal function]: Illuminate\\Validation\\Validator->Illuminate\\Validation\\{closure}()
firefly-iii/docs#5 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(289): call_user_func(Object(Closure))
firefly-iii/docs#6 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(302): Illuminate\\Validation\\Validator->passes()
firefly-iii/docs#7 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(25): Illuminate\\Validation\\Validator->fails()
firefly-iii/docs#8 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): Illuminate\\Foundation\\Http\\FormRequest->validateResolved()
firefly-iii/docs#9 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Container/Container.php(1084): Illuminate\\Foundation\\Providers\\FormRequestServiceProvider->Illuminate\\Foundation\\Providers\\{closure}(Object(FireflyIII\\Api\\V1\\Requests\\TransactionUpdateRequest), Object(Illuminate\\Foundation\\Application))
firefly-iii/docs#10 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Container/Container.php(1048): Illuminate\\Container\\Container->fireCallbackArray(Object(FireflyIII\\Api\\V1\\Requests\\TransactionUpdateRequest), Array)
firefly-iii/docs#11 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Container/Container.php(1033): Illuminate\\Container\\Container->fireAfterResolvingCallbacks('FireflyIII\\\\Api\\\\...', Object(FireflyIII\\Api\\V1\\Requests\\TransactionUpdateRequest))
firefly-iii/docs#12 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\\Container\\Container->fireResolvingCallbacks('FireflyIII\\\\Api\\\\...', Object(FireflyIII\\Api\\V1\\Requests\\TransactionUpdateRequest))
firefly-iii/docs#13 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve('FireflyIII\\\\Api\\\\...', Array)
firefly-iii/docs#14 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make('FireflyIII\\\\Api\\\\...', Array)
firefly-iii/docs#15 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(79): Illuminate\\Foundation\\Application->make('FireflyIII\\\\Api\\\\...')
firefly-iii/docs#16 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(46): Illuminate\\Routing\\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array)
firefly-iii/docs#17 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(27): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))
firefly-iii/docs#18 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(41): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(FireflyIII\\Api\\V1\\Controllers\\TransactionController), 'update')
firefly-iii/docs#19 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(FireflyIII\\Api\\V1\\Controllers\\TransactionController), 'update')
firefly-iii/docs#20 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
firefly-iii/docs#21 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
firefly-iii/docs#22 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#23 /home/bobu/public_html/Firefly/app/Api/V1/Controllers/TransactionController.php(88): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#24 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(145): FireflyIII\\Api\\V1\\Controllers\\TransactionController->FireflyIII\\Api\\V1\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
firefly-iii/docs#25 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#26 /home/bobu/public_html/Firefly/app/Http/Middleware/Binder.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#27 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Binder->handle(Object(Illuminate\\Http\\Request), Object(Closure))
firefly-iii/docs#28 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#29 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#30 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
firefly-iii/docs#31 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#32 /home/bobu/public_html/Firefly/app/Http/Middleware/Authenticate.php(73): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#33 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
firefly-iii/docs#34 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#35 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
firefly-iii/docs#36 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
firefly-iii/docs#37 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/bobu/public_html/Firefly/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/bobu/public_html/Firefly/app/Http/Middleware/SecureHeaders.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#62 /home/bobu/public_html/Firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#63 /home/bobu/public_html/Firefly/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#64 {main}
"}

**Comment by JC5** [comment]
I'll check it out, thanks for all the details.

**Comment by JC5** [comment]
It's a bug, I've pushed a fix for the next release. Congrats on getting issue #2500 :grin:
