### ISSUE TITLE
Description Auto-complete on New Transaction does not auto complete

### ISSUE THREAD

**Issue by derekprovance** [firefly-iii/firefly-iii#2502]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

Full text: "AirBNB is Alright"
When typing AirBNB in the description field, a pop down appears with "AirBNB is Alright". By clicking enter or selecting "AirBNB is Alright" the form appears to populate the remainder of the text. 

After viewing the new transaction later, however, only the text entered before the autocomplete is shown. In my case, "AirBNB" which is the point before I hit the enter key to autoselect "AirBNB is Alright"

**Steps to reproduce**
1. Open the create a new transaction screen
2. Start typing a description that exists already in the system
3. Use the auto complete feature instead of completely typing the description
4. View the transaction after creation

**Expected behavior**
When using the auto-complete and selecting "AirBNB is Alright", to see that description in the newly created transaction

**Extra info**
`Debug information generated at 2019-08-27 00:17:29 America/Chicago for Firefly III version **4.8.0.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.3 |
| FF API version | 0.10.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , errorlog |
| PHP version | 7.3.8-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-08-01 00:00:00 |
| Session end | 2019-08-31 23:59:59 |
| Session first | 2014-03-07 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |`

**Comment by JC5** [comment]
#2484

**Comment by derekprovance** [comment]
Ha! I thought I looked back far enough, my apologies. Kudos to that response time though

**Comment by JC5** [comment]
I'm working my way through the bugs and Thunderbird is open in the background :wink:
