### ISSUE TITLE
Firefly 4.8.0.3 can’t add transaction - no error displayed

### ISSUE THREAD

**Issue by shlnl** [firefly-iii/firefly-iii#2505]
I am running Firefly III version 4.8.0.3

**Description**
I’ve started using Firefly III yesterday, toying around with a Heroku installation before going all in on my own server. Now, I’ve imported a whole bunch of transactions via CSV file which all works perfectly. But adding a transaction fails a lot of the time but weirdly enough, not always...
When I start adding a transaction I fill in all the relevant fields and when I click “Submit” I get the red banner with the message “Error! There was something wrong with your submission. Please check out the errors below.” 
Sadly there are no error messages displayed. No matter what I change about the transaction, I can’t add it. This happens in Firefox, Microsoft Edge on Windows 10, Safari on Mac OS and Safari on iOS. 
I can add budgets, piggy banks, contracts, rules etc. And sometimes once I’ve done that, I can suddenly add a transaction, but I can’t understand why this is. Last night, I was able to add a whole bunch of transactions after trying for 30-45 minutes. And now, today I can’t anymore.

![IMG_0498](https://user-images.githubusercontent.com/16185038/63767884-13f32c80-c8cf-11e9-9524-c8964929b932.jpeg)

Now, I can totally understand if this is a Heroku Free issue... But is there a way to find out what I’m doing wrong? I must admit I’m getting a feel for the app already and will probably switch to self-hosting this weekend, but I just wanted to make sure that this isn’t a bug...

The only thing I can see in the logs is this Heroku error: 

heroku.ERROR: Key path "file:///app/storage/oauth-public.key" does not exist or is not readable {"exception":"[object] (LogicException(code: 0): Key path \"file:///app/storage/oauth-public.key\" does not exist or is not readable at /app/vendor/league/oauth2-server/src/CryptKey.php:48)

Regards,

SHLNL

**Comment by JC5** [comment]
It's something with the way Heroku runs its emphereal file system. It used to be so "just" the API doesn't work. But Firefly III is increasingly relying on its own API.

I have no solution yet.

**Comment by JC5** [comment]
Oh and this guy was slightly faster:

#2504
