### ISSUE TITLE
3 bugs in tag report in 4.8.0.3

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#2506]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problems are:
1) In the tag report, the sum of the expenses and revenue box is 0.
2) The transaction link in those lists are wrong.
3) Another thing that you can see in the screenshot are the 0-amount lines in the revenue box. This 2 transations are transfers, but I only included one account in the report. So 0 is not correct here, because as there is only one account involved in the report, it‘s only one part of the transfer and should therefore be an expense or income, but not 0. 0 would be only correct if both accounts are included in the report in my opinion.

**Steps to reproduce**
* Open Firefly
* Click Reports
* Choose Report type = Tag report
* Select a/some tag/s
* Click Submit
* Scroll down to "Expenses (top 10)" or "Revenue / income (top 10)". You will see a sum of 0 and if you click the link to a transaction you will get another transaction or a 404.

**Expected behavior**
1) Sum should be the sum of the expenses or revenue in the respective block.
2) The link should point to the correct transaction.
3) see bug description :)

**Bonus points**
- Add a screenshot: done

![Screenshot_2019-08-27_14-19-30](https://user-images.githubusercontent.com/24813122/63771573-b7e0d600-c8d7-11e9-92a2-eb653a79fda8.png)

**Comment by JC5** [comment]
Thanks, I'll check it out

**Comment by JC5** [comment]
The whole report has been given a make-over. I suggest you check out the [demo site](https://demo.firefly-iii.org/). The issues you reported have been fixed.
