### ISSUE TITLE
Category "delete" icon does not work

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2508]
I am running Firefly III version 4.8.0.3.

In the Transaction page, clicking the trash can icon next to "Category" will remove the category from the displayed field, but the tag will still be applied after clicking Update.

Deleting the tag using backspace / delete key works correctly.

**Comment by JC5** [comment]
I just noticed that today too, thanks for reporting. Manually clearing the data works just fine for now.

**Comment by JC5** [comment]
Will be fixed in the next release.
