### ISSUE TITLE
Description field length and UI control

### ISSUE THREAD

**Issue by renaudpaquaynsi** [firefly-iii/firefly-iii#2510]
**Bug description**
I am running Firefly III version 4.8.0.2, and my problem is:

I imported transactions from a CSV file (downloaded from my bank website) using the import module. One column in my CSV file contains text values that I mapped to the "Description" field.
The importation was a success.
The problem occurs when you want now to assign a category to some transactions that I imported previously.
I receive the following message : The transactions.0.description must be between 1 and 255 characters.

**Steps to reproduce**
You should import transactions from a file with the import function and map a column containing text longer than 255 characters to the "Description" field.
Then, you can go to your account, to see all the imported transactions. You select one transaction containing a description longer than 255 characters, and you edit it.
You change the category to something, and you click on the update button to get the error message.
![bug](https://user-images.githubusercontent.com/40366996/63874604-1b473280-c9c2-11e9-91bd-2772d5f15b3d.png)

**Expected behavior**
I expect to be able to update the category on transactions having a description longer than 255 characters.

**Extra info**
I guess because the field is VARCHAR 1024, there is no errors when importing values longer than 255 in length, but the use interface has some contraints to check for a maximum of 255 length preventing to update the record...

**Comment by JC5** [comment]
I’ll make sure the update routine cuts off at 255. Thanks for letting me know :)

**Comment by renaudpaquaynsi** [comment]
Nooo please don't do that :-) Keep the length to at least 1024 (or add another extra field like Secondary note or something similar).
I'm importing files from ING Belgium. 
these files contain three columns for a transaction: "Description", "Movement details" and "Message".
The "Description" column contains quite often more than 255 characters.
If you cut off at 255, it will truncate some informations that might be used in rules.

Would it be a problem to keep it to 1024 ?

**Comment by JC5** [comment]
Yes. UI mostly. I’ll see what I can do.

**Comment by JC5** [comment]
There is a fix for ING belgium that you can select when importing data. Otherwise, transaction descriptions will be cut off in the future.

**Comment by renaudpaquaynsi** [comment]
Great, but how did you deal with the UI then ? If I select the fix for Belgium, can I edit the transaction without the warning ?

**Comment by renaudpaquaynsi** [comment]
I still have an issue with the UI and my existing transactions. I cannot edit my existing transactions and set new categories....

**Comment by renaudpaquaynsi** [comment]
I'm using version 4.8.1.1 and I can't see any fix that can be selected for ING Belgium..neither in the UI nor in the INGBelgium.php specific import... What did you say you did exactly ?

**Comment by JC5** [comment]
Alright, so you still have a bunch of transactions where the description is too long for the field to handle, right? I've increased the limit for future releases but that may not work, and your transactions may still be too long.

I've included a command for the next release that will correct these transactions. Until then, you may have to fix them by hand.

- New imports will be cut of at 255.
- This limit will be 1000 in the new release.
- Old transactions will be fixed with a new upgrade command in the next release.
- Current old transactions must be fixed by hand.
