### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by intbl** [firefly-iii/firefly-iii#2511]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is: When I try to enter a reoccuring transactions, starting 15th of March 2020, I do get "Could not load repetition suggestions". 
When using the chrome debug console I do get a 500 error.
I therefore had a look into [ff3-fpm-fcgi-2019-08-28.log](https://github.com/firefly-iii/firefly-iii/files/3551890/ff3-fpm-fcgi-2019-08-28.log) and do see the following error:
[2019-08-28 18:00:03] local.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"userId":2,"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/firefly/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:75)
[stacktrace] [...]
Entering with starting date March 2019 would be fine.

**Steps to reproduce**
Entering a reocurring transanction starting in March 2020. 

**Expected behavior**
Able to input reocurring transactions starting March 2020

**Extra info**
I run firefly on a Debian Host, no Docker.
Debian Host is fully updated, so is PHP and nginx.
I run firefly in German.
I use nginx, ssl encyrpted.
MariaDB is in use.
My php locale are fine.

**Bonus points**
Full stacktrace attached.
Furthermore I noticed in the bills section, that March can't be shown fine as well (Should be März). Screenshot also attached. Might be related. Weird: Showing Umlauts in the bill section is not an issue (Jährlich  = yearly) is fine.
![2019-08-28_18-30-26](https://user-images.githubusercontent.com/54637523/63874650-34e87a00-c9c2-11e9-8ea3-d7e7f2f5e9eb.jpg)

Also: Awesome Job on this piece of software. Loving it.

**Comment by JC5** [comment]
Thanks!

Make sure you install the language packages in the UTF8 variants, and not any other.

**Comment by intbl** [comment]
Thanks, that's it, had also de_DE.ISO-8859-1 installed.
Will close this ticket.
Thanks for your swift response.
