### ISSUE TITLE
remove #} #} at the end of the convert to deposit page

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2512]
In /transactions/convert/deposit/foobar some chars are to be removed: 

> #} #}

![image](https://user-images.githubusercontent.com/1318140/63916121-0311fa80-ca38-11e9-99b8-c327ab03cf6f.png)

**Comment by JC5** [comment]
Oh nice find, those are Twig comment tags.

**Comment by jlauwers** [comment]
Working :)
