### ISSUE TITLE
Transaction history report

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2513]
It looks like that the transaction are ordered by date desc while it should be ordered by date asc.

Otherwise, "balance after" doesn't make sense since currently it starts from the end.

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
Will be fixed in the next release.

**Comment by jlauwers** [comment]
There is a small issue left due to this fix.
Looks like deposit are displayed as negative (but the amount before / after is good)

**Comment by JC5** [comment]
Just pushed something that should fix that.

**Comment by jlauwers** [comment]
Working :) Thanks!
