### ISSUE TITLE
Unable to disable Euro currency

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2515]
I am running Firefly III version 4.8.0.3.

Clicking the "disable" button on the Euro currency results in the error message "Error! Cannot disable Euro because it is used in asset accounts."

I have verified all of my asset accounts are set to USD ($).  All transactions are stored in USD.

I know that the Firefly DB contains records for previously-deleted accounts, could one of them been set to Euro?  If so, is there an easy way to purge it?

**Comment by JC5** [comment]
You can check out the `account_meta` table. Every entry where `currency_id` is `1` can be safely deleted (or set to another

**Comment by JC5** [comment]
The next release will properly delete account meta data, by the way.

**Comment by hamfactorial** [comment]
Excellent, I deleted two rows with currency_id=1 and now I can disable Euro without issue.

Thanks!
