### ISSUE TITLE
transaction with amount zero can be imported

### ISSUE THREAD

**Issue by renaudpaquaynsi** [firefly-iii/firefly-iii#2516]
**Bug description**
I am running Firefly III version 4.8.0.3 and my problem is:
I was able to import a CSV file containing a transaction having an amount of zero.
A value was mentionned in the file "0,00".
The importation process failed (I don't know why exactly)

After that, it was impossible to browse the "expense transaction" page or "transaction without category" page.
[ff3-apache2handler-2019-08-29.log](https://github.com/firefly-iii/firefly-iii/files/3557258/ff3-apache2handler-2019-08-29.log)

After removing manually the records from the "transaction_journals" and "transactions" tables, the problem disapeared.

**Steps to reproduce**
Don't know exactly how to reproduce the failing importation.

**Comment by JC5** [comment]
Thanks, that's fixed in the next release.
