### ISSUE TITLE
Dashboard balance tile refresh issue

### ISSUE THREAD

**Issue by renaudpaquaynsi** [firefly-iii/firefly-iii#2517]
**Bug description**
I am running Firefly III version 4.8.0.3 and my problem is:
From time to time, when browsing from different pages to the dashboard, the balance tile is not correctly refreshed and displays nothing.

**Steps to reproduce**
Browse to the dashboard, check that the balance tile is displaying some values.
Click on the "Tags" menu, wait for the Tag page to be displayed.
Click on the "Dashboard" menu (you come back to the previous page).
Repeat this operation to come back and forth from the tag page to the dashboard page.
You'll notice that from time to time, the balance tile is not correctly refreshed.

**Expected behavior**
The balance tile to be refreshed correctly everytime

**Bonus points**
![dashboard_before](https://user-images.githubusercontent.com/40366996/63975887-59228480-cab0-11e9-903f-9fffbc434703.png)
![dashboard_after](https://user-images.githubusercontent.com/40366996/63975896-60e22900-cab0-11e9-9dcb-5e1a2704d962.png)

**Comment by JC5** [comment]
In that case it may have given an error. Check you logs so I know what's going on.
