### ISSUE TITLE
Balance tile link to display the current period

### ISSUE THREAD

**Issue by renaudpaquaynsi** [firefly-iii/firefly-iii#2518]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

The balance tile link is not period aware.
When I click on the "Balance" link in the balance tile on the dashboard page, I get redirected to the the default financial report for the current month. It is confusing when viewing data for a perdiod different than the current month.
Indeed, the link is using the currentMonthStart/currentMonthEnd for the report, and completely disregard the current period.
For example, if my current period is 1st June to June 31, the balance tile displays the balance for June.
If I now click on the balance link (inside the tile), it will redirect me to the default financial report for 1st of August to August 31

**Steps to reproduce**
Explained in the bug description

**Expected behavior**
The "balance" link should be related the current period in order to match the current values beeing displayed in the balance tile.

**Bonus points**
Select period June
![balance_june_b](https://user-images.githubusercontent.com/40366996/63976586-f205cf80-cab1-11e9-843c-960511ce9023.png)
Click on Balance
![balance_june](https://user-images.githubusercontent.com/40366996/63976588-f29e6600-cab1-11e9-8432-9c2db4613bf4.png)
The report period is not related
![balance_june_link](https://user-images.githubusercontent.com/40366996/63976587-f29e6600-cab1-11e9-934c-8dbb30c35cdd.png)

**Comment by JC5** [comment]
Thanks, that should be an easy fix.
