### ISSUE TITLE
Add WebAuthn (Fido2) support

### ISSUE THREAD

**Issue by lleifermann** [firefly-iii/firefly-iii#2519]
Hi, i noticed that firefly already supports two factor authentication.
I really like the idea of using a security key as a second factor. Maybe this is something a future release could integrate?

**Comment by JC5** [comment]
Yes, and I believe it’s already on the roadmap.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947158
