### ISSUE TITLE
Toggle to hide balance and totals

### ISSUE THREAD

**Issue by Leosirth** [firefly-iii/firefly-iii#2520]
**Description**
I would like to have a toggle to hide the balance and totals from the upper bar and the graphs, the reason behind this is that usually I could open FireflyIII on a crowded environment (i.e. working open space) in order to enter a new transaction and this could lead others to see my balances.

**Solution**

A simple toggle that will replace hide and un-hide the totals

**What are alternatives?**

There are no alternatives on this right now.

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
No, sorry.

**Comment by Leosirth** [comment]
Well ok, can I just ask you why?

**Comment by marviins87** [comment]
+1 for this request. It wouldn't be that hard to implement. 
Just a toggle like the side and Add menus already have.

**Comment by JC5** [comment]
I’m not adding toggles for UI elements.

**Comment by Leosirth** [comment]
My Idea was to hide the totals (i.e. with hash) and not hiding the UI elements.

Something like:

![image](https://user-images.githubusercontent.com/800911/64082091-2c69a980-cd0a-11e9-8b1c-0f6541cd99cd.png)
