### ISSUE TITLE
Transaction Form - hide foreign currency fields if only one currency is enabled

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2521]
Please describe your feature request:

For installations with only one currency defined, I would like the currency dropdown and "foreign amount" input field hidden.  

This would streamline the form and prevent spurious "The selected transactions.0.foreign_currency_id is invalid" errors if the foreign amount field is used by mistake.

Thank you for considering!

**Comment by JC5** [comment]
Good idea :+1:

**Comment by JC5** [comment]
Will be done in next release.
