### ISSUE TITLE
Overspent Amount on Report

### ISSUE THREAD

**Issue by JakeLadson** [firefly-iii/firefly-iii#2522]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is: 
The overspent column on the default financial report is not showing an amount when overspent against the budgeted amount.
![image](https://user-images.githubusercontent.com/26978529/64056929-a3f9d600-cb5c-11e9-9935-c4ddc0299b97.png)

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
Found it, will be fixed in the next release.
