### ISSUE TITLE
In ServiceProvider.php line 236: Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': No application encryption key has been specified.

### ISSUE THREAD

**Issue by jzt308** [firefly-iii/firefly-iii#2523]
**Bug description**
I am running Firefly III version latest build from docker repo, and my problem is:

On startup I get the error: In ServiceProvider.php line 236: Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': No application encryption key has been specified.
This results in a white screen when accessing the Fireflyiii website.

**Steps to reproduce**
Run fireflyiii using docker-compose:
version: '3.1'
 
services:
 
 firefly-iii:
  image: jc5x/firefly-iii
  restart: unless-stopped
  volumes:
   - /DATA/app/firefly-iii/export:/var/www/firefly-iii/storage/export
   - /DATA/app/firefly-iii/upload:/var/www/firefly-iii/storage/upload
  ports:
   - 86:80/tcp
  environment:
   - FF_DB_HOST=dbfirefly-iii
   - FF_DB_NAME=dbfirefly
   - FF_DB_USER=firefly
   - FF_DB_PASSWORD=PASSWORDHERE
   - FF_APP_KEY=APPKEYHERE
   - FF_APP_ENV=local
   - FF_DB_CONNECTION=mysql
   - TZ=Europe/Amsterdam
   - APP_LOG_LEVEL=debug

**Expected behavior**
I used this docker-compose file for the previous version without problem.

**Extra info**

[Sat Aug 31 12:53:54.740214 2019] [php7:error] [pid 284] [client 10.255.0.2:63922] PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(785): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\C in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44

10.255.0.2 - - [31/Aug/2019:12:53:52 +0200] "GET / HTTP/1.1" 500 210 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by JC5** [comment]
#2436

Read the part about the environment variables and make sure you use the latest docker files from the repository.
