### ISSUE TITLE
Auto complete on transaction page

### ISSUE THREAD

**Issue by JakeLadson** [firefly-iii/firefly-iii#2524]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

When I am entering a transaction and click the auto complete term it completes in the input area but does not save the full term when I save the transaction. For example you enter "Fo" then click the suggested term of "Food" but when you save the transaction it only saves "Fo", not the full word. 

Hopefully that makes sense. Let me know if you need more information. 

Thank you for all the work that you do to keep Firefly up and running, you're the real hero!

**Comment by JC5** [comment]
Thanks :)

Please check the existing issues. This has been reported before.

**Comment by JakeLadson** [comment]
Awesome. I looked but didn't see it, must've missed it. 

Thanks!
