### ISSUE TITLE
Solid Pod for Storage?

### ISSUE THREAD

**Issue by tmciver** [firefly-iii/firefly-iii#2525]
Firefly-III is listed [here](https://github.com/solid/solid-apps) as a Solid application but I don't see anything about this in any Firefly documentation.  Is this app able to use a Solid Pod for storage?

**Comment by JC5** [comment]
I got to admit I never heard of it. So any implementation into Solid is done by somebody else. 

I’ll have to read into it.

**Comment by tmciver** [comment]
OK, I'm going to create an issue over at that project inquiring about this as well.

**Comment by tmciver** [comment]
It looks like Firefly was originally added to the list as a "wish".  I wouldn't mind attempting to add the capability to use Solid as a storage mechanism.  @JC5 would you mind pointing me in the right direction as to how one might add an alternative non-SQL storage mechanism?

**Comment by JC5** [comment]
Good question, @tmciver. I'll have to dive into it. Preferrably I would like to have something built-in, a library or a storage / SQL driver. I haven't found them yet.
