### ISSUE TITLE
Unable to unlink transaction from budget

### ISSUE THREAD

**Issue by Mikhail5555** [firefly-iii/firefly-iii#2526]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

Once you assign an Budget to an transaction, I am unable to change it back to the '(no budget)' option since this change gets ignored on update.

**Steps to reproduce**
1. Have at least 2 Budgets.
2. Update an transaction to one of them (Test1).
3. *Confirm the transaction is now assigned to Budget Test1*
4. Update the transaction again to Budget Test2.
5. *Confirm the transaction is now assigned to Budget Test2*
6. Update the transaction again to Budget (no budget).
7. *Transaction stays budget Test2*

**Expected behavior**
Transaction should have no budget assigned at step 7.

**Extra info**
Debug information generated at 2019-09-01 14:28:02 Europe/Berlin for Firefly III version **4.8.0.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.3 |
| FF API version | 0.10.1 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.8 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |
**Bonus points**

**Comment by JC5** [comment]
Thanks, nice find. This should also be fixed in the next release.

**Comment by Mikhail5555** [comment]
Thanks :)

**Comment by JC5** [comment]
Np. I'm leaving it open in case somebody else reports it.
