### ISSUE TITLE
Issues with the Description Input Field while creating or updating transactions

### ISSUE THREAD

**Issue by bernhardbauer** [firefly-iii/firefly-iii#2528]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

- When I am creating transactions which are similar to another transaction in the past, I am always using one of the suggested descriptions. If a user selects a suggested value, the description input field gets populated with the new value, but while saving or updating the transaction the original user input is used.
- Furthermore editing of the input value is really a pain if you want to add some text in the middle of the description. While trying to edit text the cursor always jumps to the end of the description

**Steps to reproduce**
*I have been able to reproduce the issue on demo.firefly-iii.org*
1.) Create a new transaction
2.) Start typing "Gro" in the description field
3.) Select suggested text "Doing groceries"
4.) After saving or updating the transaction the value "Gro" will be saved instead of the desired value "Doing groceries"

**Expected behavior**
The new suggested text should be used and saved as transaction description and the cursor position in the input field should not jump around while editing the description.

**Extra info**
**OS**: macOS 10.14
**Browser Version**: Safari 12.0

**Bonus points**
<img width="1023" alt="Screenshot 2019-09-01 at 16 51 04" src="https://user-images.githubusercontent.com/7264406/64078440-fe20a580-ccda-11e9-8e32-921d00ffee9d.png">

**Comment by JC5** [comment]
This has already been reported multiple times.
