### ISSUE TITLE
Show category in transaction overview

### ISSUE THREAD

**Issue by wessel145** [firefly-iii/firefly-iii#2529]
I am running Firefly III version 4.8.0.3

Since the new version the category is not made visible when viewing the transactions (expenses). I used this overview to bulk correct the categories, now I have to open each transaction to check the category. Is this something temporary? I cannot find a setting to bring back the category in the overview.

Thanks

**Comment by JC5** [comment]
Yes, this has been requested before. I’ll pick it up for the next release.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2389
