### ISSUE TITLE
After storing, return here to create another one - Not working correctly

### ISSUE THREAD

**Issue by plainlytbrown** [firefly-iii/firefly-iii#2530]
I'm currently running Firefly III version 4.8.0.3 on a Synology Nas through docker.

Each time I enter a new expense and check off the "After storing, return here to create another one" and check off the "Clear form after submission" it is splitting the expense. I would expect that it would take me back to the expense screen empty. It tried this same thing on the demo website and had the same issue. I'm using a Mac and Safari as my web browser. 

Thanks for this Awesome app btw!

**Comment by JC5** [comment]
Thanks :)

https://github.com/firefly-iii/firefly-iii/issues/2490
