### ISSUE TITLE
Sharing one or more accounts on different accounts

### ISSUE THREAD

**Issue by nloshka** [firefly-iii/firefly-iii#2531]
**Description**

**Solution**

**What are alternatives?**

**Additional context**

**Bonus points**

Is it possible to set up synchronization of one or several accounts for sharing between different accounts or do I need to make all the changes from one account?
We need as a family (husband, wife, brother, sister) to keep accounts separately in different accounts and create one or more general accounts so that all changes with these accounts are visible online to these users.
Perhaps it is already implemented somehow, but I can’t find how to organize it, if it is already, tell me how to configure it.
Thank.

**Comment by JC5** [comment]
Sorry no, the separation between users is very strict. You can't share data.

**Comment by nloshka** [comment]
It is unfortunate that there are no shared sharing options.
Maybe the crontab will get import export of one particular account?
Perhaps in the future you will implement such functions?
Thanks again.

**Comment by JC5** [comment]
Thanks nloshka,

Sorry, this will not be a feature. Sharing account and transaction details will not be possible.

**Comment by skuzzle** [comment]
I'm just going to hijack this ticket to discuss an idea to make working with different accounts easier. It would be a whole lot easier if switching between accounts were simpler. I use a second firefly account to manage our household expenses. As I'm mostly logged in with may main firefly user, I always have to switch users when entering a transaction for the household account. Switching users back and forth is pretty cumbersome:
1. Log out of current account
2. Enter user name/password of other account 
3. Open 2FA App to lookup 2FA code
4. Enter transactions etc.
5. Goto 1. to log in again with main account

Maybe it could be possible to switch firefly accounts without having to enter the credentials (only if both accounts mutually agree on this or something). I'm not sure though how many people actually use firefly with multiple, truely unrelated user accounts.

**Comment by nloshka** [comment]
If you export from the first account, say the “General” account and import into the second account of the same “General” account as well as export from the second account of the same “General” account and import into the first account of the same “General” account "
This will turn out to be slightly reminiscent of the synchronization of accounts.

You can place tasks in crontab and configure unloading every 5-10 minutes.

So is it possible to do?
