### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nloshka** [firefly-iii/firefly-iii#2533]
**Description**

**Solution**

**What are alternatives?**

**Additional context**

**Bonus points**

Now executing firefly:instructions update
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for updating to Firefly III, v4.8.0.3!                             |
| This is a huge upgrade for Firefly III. Please expect bugs and errors, and   |
| bear with me as I fix them. I tested a lot of things but pretty sure I       |
| missed some. Thanks for understanding.                                       |
|                                                                              |
+------------------------------------------------------------------------------+
When updating versions I get a red answer:

  Command "firefly:verify" is not defined.

  Did you mean one of these?
      firefly-iii:account-currencies
      firefly-iii:apply-rules
      firefly-iii:back-to-journals
      firefly-iii:bills-to-rules
      firefly-iii:bl-currency
      firefly-iii:cc-liabilities
      firefly-iii:correct-database
      firefly-iii:create-access-tokens
      firefly-iii:create-link-types
      firefly-iii:cron
      firefly-iii:csv-import
      firefly-iii:decrypt-all
      firefly-iii:delete-empty-groups
      firefly-iii:delete-empty-journals
      firefly-iii:delete-orphaned-transactions
      firefly-iii:delete-zero-amount
      firefly-iii:enable-currencies
      firefly-iii:fix-account-types
      firefly-iii:fix-ob-currencies
      firefly-iii:fix-piggies
      firefly-iii:fix-transfer-budgets
      firefly-iii:fix-uneven-amount
      firefly-iii:migrate-attachments
      firefly-iii:migrate-notes
      firefly-iii:migrate-to-groups
      firefly-iii:other-currencies
      firefly-iii:remove-bills
      firefly-iii:rename-account-meta
      firefly-iii:rename-meta-fields
      firefly-iii:report-empty-objects
      firefly-iii:report-integrity
      firefly-iii:report-sum
      firefly-iii:transaction-identifiers
      firefly-iii:transfer-currencies
      firefly-iii:upgrade-database
      firefly:instructions
      firefly:scan-attachments

What did I miss?
I would be grateful for your help.

**Comment by JC5** [comment]
Did it execute the command itself or did you put it in?

**Comment by nloshka** [comment]
Everything was done according to the instructions https://firefly-iii.readthedocs.io/en/latest/installation/upgrading.html

Go to the firefly-iii folder and run these commands:

git pull
rm -rf bootstrap/cache/*
rm -rf vendor/
composer install --no-scripts --no-dev
composer install --no-dev
php artisan migrate --seed
php artisan firefly-iii:decrypt-all
php artisan cache:clear
php artisan firefly-iii:upgrade-database
php artisan passport:install
php artisan cache:clear

**Comment by nloshka** [comment]
I'm sorry, apparently the old recommendations for updating
Just wrapped in a script for easy updating.
# cat fUpd.sh
#! / bin / bash

tar cvfj /var/www/buh/BackUp/firefly-iii.$(date +% Y-% m-% d) .tar.bz2 / var / www / buh / firefly-iii /

cd / var / www / buh / firefly-iii
#Go to the firefly-iii folder and run these commands:

git pull
rm -rf bootstrap / cache / *
rm -rf vendor /
composer install --no-scripts --no-dev
composer install --no-dev
php artisan migrate --seed
php artisan firefly: decrypt-all
php artisan cache: clear
php artisan firefly: upgrade-database
!!!#php artisan firefly: verify
php artisan passport: install
php artisan cache: clear
--------
Extra line in the update script: php artisan firefly: verify
I believe that checks are no longer needed?

**Comment by JC5** [comment]
Thanks for letting me know!

Yes, the `verify` command is included in `firefly-iii:upgrade-database`. You can use both `firefly-iii:upgrade-database` and `firefly:upgrade-database`

**Comment by nloshka** [comment]
Thank you, I corrected my script for easy updating. I will look at changes in your instructions in the future.
Sorry for the extra annoyance.

**Comment by JC5** [comment]
No worries!
