### ISSUE TITLE
Default currency don't chosen by default

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2535]
I am running Firefly III version 4.8.0.3 Firefly III, and my problem is:

**Bug description**
Default currency not default in withdrawal transaction

**Steps to reproduce**
1. Options - Currencies - I choosed EUR, USD, UAH.
2. Plus - New withdrawal - chosen currency is Euro, not UAH.
![image](https://user-images.githubusercontent.com/25054050/64159501-08f64a00-ce43-11e9-9720-78ee578a3179.png)

**Expected behavior**
Default currency always chosen by default in any transaction.

**Comment by JC5** [comment]
That's the foreign amount, as indicated by the text "foreign amount".

**Comment by JC5** [comment]
Just select accounts and the currency for the "Amount" will update automatically.

**Comment by optimistic5** [comment]
Thank you for your answer :slightly_smiling_face: 
No more questions.
