### ISSUE TITLE
Wrong language in Transaction Page

### ISSUE THREAD

**Issue by AndreasW79** [firefly-iii/firefly-iii#2540]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

Transaction Page is not (completely) in selected language (f.e. german).
Predefined Fields like 'Source Account (even if there is only one)' as in older versions 
are not prefilled. Is there a chance to prefill 'Destination Account' and other fields too (would make creating transactions with mobiles much better)?

**Steps to reproduce**
Create a new Transaction

**Expected behavior**
Prefilled fields and correct language as selected

**Extra info**
Debug information generated at 2019-09-04 15:41:35 Europe/Amsterdam for Firefly III version **4.8.0.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.3 |
| FF API version | 0.10.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.8 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2013-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**
![image](https://user-images.githubusercontent.com/5779166/64260463-33233700-cf2b-11e9-990d-dd95065f9b01.png)

**Comment by JC5** [comment]
Yes, this is a known issue.

**Comment by JC5** [comment]
It's mentioned in the release notes but it never got its own issue. No worries :)

**Comment by Nik-vr** [comment]
Should we expect a solution to this problem? Are there any serious obstacles?

**Comment by JC5** [comment]
Vue internationalisation is a tricky library. Please be patient.

**Comment by Nik-vr** [comment]
OK!
