### ISSUE TITLE
sum of bills 

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2543]
In /bills there is the sum of bills.
If you have bills on different repeats ( let's say 1 bills monthly and 1 yearly ), it's still the sum of all bills which doesn't mean much.

Example:
One yearly bill of 1000 in january
One monthly bill of 100.
Sum is 1100.

Maybe, show the sum of the bills payable this period? (1100 in January and 100 the other months)
Or the average by month for the whole year? (183.33)

**Comment by JC5** [comment]
I'm not yet sure but it's on the roadmap, yes. I think of something for the next release. I like the idea of the current period the best, to be honest. It introduces the least magic numbers and it gives you the details you want to know.

**Comment by JC5** [comment]
Should be improved next release.

**Comment by jlauwers** [comment]
Working :) thanks!
