### ISSUE TITLE
Income balance and transfers mixed

### ISSUE THREAD

**Issue by michael87** [firefly-iii/firefly-iii#2544]
Hi i am on version 4.8.0.3 and i was just curious how the internal system works related to transfers.

I was looking to the income vs expenses on the report: 
http://localhost:8088/reports/default/allAssetAccounts/currentYearStart/currentYearEnd

Surprisingly i was see more income then is in my income transactions. Then i was looking at the transfers + the income transactions and it is exactly matching. For me this looks a bit strange, because it is not a income, i only move money between my bank accounts. 

By example I transfer from my ING to my Bunq account. That is for me not an income, just move my money to my save account. 

How is can make it work, that it looks more realistic. The income, will be in my eyes, salary, and money transfers from external to me.

Hope someone can help me explain what i can do or change my mindset.

Thanks in advance!

**Comment by JC5** [comment]
Any money coming from an asset account not included in the report counts as "income". Any money going to an asset account not included in the report counts as expense.

This is done so you can see what the income / expense is for an account or set of accounts, separated from the rest. This is useful for when you're using Firefly III on shared accounts. If I only include the shared accounts in a report, my own transfers to the shared accounts count as income as well.

You'll notice that transfers aren't included at all when you're including both the receiving and the sending account of a transfer.

If you want to make sure that transfers aren't included make sure you include both accounts in the report.

Looking at the URL you're giving me, both accounts should be included in the report so these transfers should not be listed in the report as income or expense. But this could be a bug in the current release, I can't replicate it in the upcoming release.

If you could email me some screenshots (of the report itself and of the page /accounts/asset) i can dive into it. Feel free to censor data of course.
