### ISSUE TITLE
Tags still visible in transactions after deletion

### ISSUE THREAD

**Issue by marviins87** [firefly-iii/firefly-iii#2545]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is that tags are not detached from my transactions after deleting tags.

**Steps to reproduce**
1) Create a tag  (id 45, name testtest)
2) Edit a transaction and add testtest tag
3) check the tag (/tags/show/45) and open the corresponding transaction (transactions/show/12374)
4) Delete tag testtest (/tags/delete/45)  ("Gelukt! Tag "testtest" verwijderd") 
5) open transaction 12374 again (/transactions/show/12374)
6) Tag testtest is still attached to it and visible in the transaction.
7) check the tag (/tags/show/45), doesnt exists so redirect to tags page (/tags)

**expected behavior**
The tag shouldn't be visible in the transaction after deleting it.

**Extra info**
* In the DB the deleted_at column contains a timestamp so it's deleted in the DB.
* When i manually set the field back to NULL the tag is back and all transactions are visible like they should.

`Debug information generated at 2019-09-06 07:08:44 UTC for Firefly III version **4.8.0.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.3 |
| FF API version | 0.10.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.8 |
| Display errors | Off |
| Session start | 2019-08-07 00:00:00 |
| Session end | 2019-09-06 00:00:00 |
| Session first | 2012-12-14 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |
`

**Comment by JC5** [comment]
Nice find. This will be fixed in the next release.
