### ISSUE TITLE
Change import tags

### ISSUE THREAD

**Issue by marviins87** [firefly-iii/firefly-iii#2546]
**Description**
I would like Firefly III to use meaningful import tags. 
Currently it's like:  "Import with code '7eW3AefhqecO'"

**Solution**
Why not use something meaningful similar to: "Import from '2019-09-06 09:12:30'

**Comment by JC5** [comment]
The import routine is changing in the future. For the time being the tags will stay as they are, but in future iterations they may get an upgrade. :)

**Comment by JC5** [comment]
https://www.patreon.com/posts/30012174
