### ISSUE TITLE
Change Opening balance

### ISSUE THREAD

**Issue by filipe-silva** [firefly-iii/firefly-iii#2547]
Hi, so I created a asset account with a value as for the opening balance.
However I was gathering my transactions and decided to go further, since the begining, so before importing my file with the transactions, I changed the the opening balance to 0.
To my suprise after importing, the balance was completely wrong, after searching I saw the opening balance didn't update (I tried to change it like 7 times). 
So if it's by design ok, or maybe it's a bug... 

Still I need to fix the balance, so I thought to change the value in the database and set it to 0. Sadly it didn't work, didn't do anything at all actually.
Is it possible to fix the balance as of now?

**Comment by JC5** [comment]
That could be a bug, although I have trouble replicating it. If I edit the account and remove both the amount and the date they're gone without a problem.

Which version are you running?

**Comment by filipe-silva** [comment]
I'm currently running Version 4.8.0.3
Did the same as you and removed the date and amount, clicked update and it saved.
I decided to do some testing after removing.
1. Added amount and opening balance date
2. Clicked update
3. Went back to edit the account
4. Changed amount to 0
5. Clicked update
6. Amount didn't change

However, if you place any amount except 0, negative or positve, it saves that new amount. 
So it seems ok to me, since setting it to 0 or removing it's the same achieves the same. 
Maybe place a validation saying that you can't have an opening balance date and 0 amount?

**Comment by JC5** [comment]
Good point, it should do that. Not sure why it doesn't.

**Comment by JC5** [comment]
In the new release, if you set it to 0, it will also be reset.
