### ISSUE TITLE
Error on multi curenre transfers between account

### ISSUE THREAD

**Issue by heretic404** [firefly-iii/firefly-iii#2548]
**Bug description**
I am running Firefly III version 4.8.0.2, and my problem is system registering wrong transfer amount

**Steps to reproduce**

- Account A USD currency
- Account A UAH currency

1. Transfer Funds From B to A
2. Fill both Amount (25,502.40 UAH) Foreign Amount ($1000)  
3. Account A balance increased by $25,502.40 

**Expected behavior**
1. Transfer Funds From B to A
2. Fill both Amount (25,502.40 UAH) Foreign Amount ($1000)  
3. Account A balance increased by $1000

**Extra info**
```[2019-09-06 16:18:04] local.ERROR: Foreign currency is equal to normal currency (UAH)  ```

**Comment by heretic404** [comment]
`[2019-09-06 16:43:34] local.INFO: Store new transaction over API. {
"group_title":"",
"transactions":[{
	"type":"transfer",
	"date":"2019-09-06 00:00:00",
	"order":null,
	"currency_id":null,
	"currency_code":null,
	"foreign_currency_id":7,
	"foreign_currency_code":null,
	"amount":"25502.40",
	"foreign_amount":"1000",
	"description":"Description",
	"source_id":31,"source_name":"My Bank Name"",
	"destination_id":29,
	"destination_name":"My Bank 2",
	"budget_id":null,
	"budget_name":null,
	"category_id":null,
	"category_name":null,
	"bill_id":null,
	"bill_name":null,
	"piggy_bank_id":4,
	"piggy_bank_name":null,
	"reconciled":false,
	"notes":null,
	"tags":null,
	"internal_reference":null,
	"external_id":null,
	"original_source":"ff3-v4.8.0.2|api-v0.10.0",
	"recurrence_id":null,
	"bunq_payment_id":null,
	"sepa_cc":null,
	"sepa_ct_op":null,
	"sepa_ct_id":null,
	"sepa_db":null,
	"sepa_country":null,
	"sepa_ep":null,
	"sepa_ci":null,
	"sepa_batch_id":null,
	"interest_date":null,
	"book_date":null,
	"process_date":null,
	"due_date":null,
	"payment_date":null,
	"invoice_date":null
	}],
"user":1
} 
{"path":"POST:https://My.host/finances/api/v1/transactions","IP":"MYIP","user":"ME"}`

**Comment by JC5** [comment]
What types are accounts A and B? Are they both asset accounts?

**Comment by JC5** [comment]
OK, I think I know what the cause is, and I can fix it in the next release.

**Comment by heretic404** [comment]
> What types are accounts A and B? Are they both asset accounts?

Yes

I have updated to 4.8.0.3 and this has fixed issue, but I had to recreate all transactions.

**Comment by JC5** [comment]
Yes, sorry about that. These things are difficult to correct automatically.

**Comment by heretic404** [comment]
Nevertheless Thanks, it is great software. But a new currency exchange service is needed.
