### ISSUE TITLE
Clone transaction is not working

### ISSUE THREAD

**Issue by anamaria85** [firefly-iii/firefly-iii#2549]
Class FireflyIII\Http\Controllers\Transaction\CloneController does not exist
Firefly III version 4.8.0.3. 
I get this error after upgrading. Also exists on your demo version

**Comment by JC5** [comment]
That's correct. It's noted in the release notes and the change log as well.

**Comment by JC5** [comment]
Should be back in the new release.

**Comment by anamaria85** [comment]
Ok. thank you!

**Comment by Kakifrucht** [comment]
I'm still having this issue in v4.8.1, and I checked the master branch and the CloneController is nowhere to be found!

**Comment by JC5** [comment]
Check out the options on the bottom of the “edit” page.

**Comment by Kakifrucht** [comment]
Ah, was trying to use an old bookmark to clone, thanks!
