### ISSUE TITLE
"Reset form after submission" doesn't work

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2551]
**Bug description**
I am running Firefly III Docker version 4.8.0.3, and my problem is:
**Reset form after submission** doesn't work.

**Steps to reproduce**
1. Create new stuff - New withdrawal
2. Enter data, check two boxes in Submission block:
"After storing, return here to create another one"
"Reset form after submission"
![image](https://user-images.githubusercontent.com/25054050/64470903-02bde180-d153-11e9-89cd-c34d20608634.png)
3. Push button **Submit**
you will see than transaction was created successfully, but also split was created, and first split is from previous transaction.
![image](https://user-images.githubusercontent.com/25054050/64470916-3f89d880-d153-11e9-99d9-0629fbc62ef5.png)
This is the first bug :arrow_up: and just after I can reproduce another one.
4. Don't change anything in form above, go to Create new stuff - New withdrawal
5. Fill up form
![image](https://user-images.githubusercontent.com/25054050/64470934-91326300-d153-11e9-91b8-0792783fa2d9.png)
6. Push Submit button and I received this 
![image](https://user-images.githubusercontent.com/25054050/64470938-a4ddc980-d153-11e9-8aba-c4cf0cb53e2f.png)

**Expected behavior**
**Reset form after submission** works as expected.

**Extra info**
Debug information generated at 2019-09-07 09:42:17 Europe/Kiev for Firefly III version **4.8.0.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.3 |
| FF API version | 0.10.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.8 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2019-09-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2490
