### ISSUE TITLE
Search should't be case sensitive

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2552]
I am running Firefly III version 4.8.0.3

**Description**
In forms such as:
Source account
Destination account
Category

Search in this forms are case sensitive.
For example I have **Credit card**, so in order to search this I must type **Cr**, but not **cr**.
I think it would be more comfortable for user don't have case sensitive search.

![image](https://user-images.githubusercontent.com/25054050/64471136-c17b0100-d155-11e9-8966-4f1b9b1b8622.png)

**Comment by JC5** [comment]
The search is case sensitive because your database is. There isn’t much I can do about it. Sorry.

**Comment by optimistic5** [comment]
I use PostreSQL in my docker-compose. So if somebody can help me to disable case sensitive feature, it would be great. Thank you.

**Comment by jlauwers** [comment]
> I use PostreSQL in my docker-compose. So if somebody can help me to disable case sensitive feature, it would be great. Thank you.

I have the same issue and couldn't find a solution. I'm planning to migrate to mysql or mariaDB.

@JC5 I couldn't find a way to export firefly data (to re-import into anther DB).
Is the feature coming back?

**Comment by optimistic5** [comment]
@JC5 mysql do not case sensitive?
I think Firefly shouldn't have this feature because you can do it with simple export/import of DB.

**Comment by jlauwers** [comment]
> @jlauwers mysql do not case sensitive?

Mysql/mariaDB is case insensitive, yes.

**Comment by jlauwers** [comment]
From the docs: 

> Firefly III assumes that you’re using PostgreSQL, which a lot of people do.

Why is it assumed since it's the only DB to do case sensitve (from what I understand)

**Comment by JC5** [comment]
The Docker files use PostgreSQL. I can't do much about the case sensitivity. A port to MySQL is possible but I'm not sure how. The export functionality wouldn't have helped I'm afraid.

**Comment by arnvald** [comment]
Hi @JC5, would you be open to using `lower(search_term) = lower(value)` when searching accounts? I've used this in the past for matching email addresses in PostgreSQL and it worked well. If you find this solution ok, I'll be happy to make a pull request.

**Comment by JC5** [comment]
I'm sorry, but that isn't going to work I'm afraid. SQLite has only limited support for the command. I need it to be completely database agnostic. I'll keep an eye out for other solutions.

**Comment by arnvald** [comment]
Thank you for such a quick reply. I checked that the function exists in SQLite, but I had no idea that it's too limited. It's good to know!

**Comment by viharm** [comment]
I use _PostgreSQL_ as my database. The search is case-sensitive everywhere but not for categories in the optional information for recurring transactions.
![image](https://user-images.githubusercontent.com/2663937/71783838-6f9f9600-2fe4-11ea-98d3-5e239fb69267.png)

I am intrigued as to how this might be possible. And if it's possible here, then may be elsewhere too.

Any thought?
