### ISSUE TITLE
User seemingly can modify a grayed out field of a split transaction

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [firefly-iii/firefly-iii#2553]
**Bug description**
I am running Firefly III version f36b369d731a7a2d07e2a8fadf87cdfbe38a6e43, and my problem is:

When you edit a split transaction, the source (resp. destination) field for a withdrawal (resp. deposit) is not greyed out, and changing it won't be taked into account, despite being shown no error message / warning. This may possibly lead the user in error that the changes were correctly applied.

**Steps to reproduce**

Create a split transaction, here a withdrawal.

![2019-09-07-091942_1920x1080_scrot](https://user-images.githubusercontent.com/1685403/64471443-0c931500-d152-11e9-96c4-c378ff8194c3.png)

We can see that the source field is grayed out, as it shouldn't be different from the first one.

![2019-09-07-091950_1920x1080_scrot](https://user-images.githubusercontent.com/1685403/64471445-10bf3280-d152-11e9-8897-5edfd405b15c.png)

Save it, then open it again to edit it.

![2019-09-07-092035_1665x1052_scrot](https://user-images.githubusercontent.com/1685403/64471456-2e8c9780-d152-11e9-9d27-ee69d92738cc.png)

Here, the field is no longer grayed out. We can change it, and the suggestions also work.

![2019-09-07-092049_1669x1073_scrot](https://user-images.githubusercontent.com/1685403/64471462-3ea47700-d152-11e9-848c-ee6f45992bee.png)

Saving it will discard the source changes, without any warning or error.

![2019-09-07-092108_1675x459_scrot](https://user-images.githubusercontent.com/1685403/64471468-511eb080-d152-11e9-8e15-815260c12b08.png)

**Expected behavior**

The field being grayed out **and** an error message if the user tries to change the field instead of silently discarding it (for the API of course).

**Extra info**

I don't understand why this is a restriction in the first place. Paying for something with multiple sources (credit card, cash, check, meal vouchers... The screenshots I took gave an example) sounds like a reasonable use case, and I don't think it's really suited for linked transactions either.

**Comment by JC5** [comment]
There is no technical restriction but I want to keep this simple. In Firefly III, a withdrawal has one source and multiple destinations. A deposit has one destination with multiple sources. A transfer, even a split one, has one source and one destination.

I know there are plenty of use cases to be thought of where this isn't the case (you list some excellent ones) but supporting every edge case is explicitly not the goal of Firefly III. That's something that fits better with GNUCash.

I am aware that there are some cases where the proper fields are not greyed out. I'll pick it up as an enhancement and try to fix it for the next release.

My experience so far has been that only advanced users run into the problems you describe and they know where to find me.
