### ISSUE TITLE
"No error yet" for the same account in transaction

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2555]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

No error when choose the same account in Source/Destination account.

**Steps to reproduce**
1. Create new stuff - New withdrawal
2. Set Source account and Destination account the same
3. Submit and receive error: "No error yet" two times.
![image](https://user-images.githubusercontent.com/25054050/64472276-6ac8f380-d164-11e9-904a-c18c882d4be9.png)

**Expected behavior**
Error that says something like:
"You can't choose the same account for transaction"

**Comment by JC5** [comment]
Yes good one, I'll pick it up.

**Comment by JC5** [comment]
Fix is ready, will be included in the next release.
