### ISSUE TITLE
As a user I want to make some basic calculation in Amount field

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2556]
**Description**

I would like Firefly III to have ability to do some calculation in Amount field.
I just come back from market I did ten small purchases.
I don't want to split this purchases, I just want to add few values and submit the sum.
![image](https://user-images.githubusercontent.com/25054050/64474947-76c4ad80-d184-11e9-85ec-83050072f47a.png)

**Comment by JC5** [comment]
No, sorry.
