### ISSUE TITLE
Failed to open stream: Permission denied when installing Firefly for first time

### ISSUE THREAD

**Issue by nathanmerrill** [firefly-iii/firefly-iii#2558]
**Bug description**
I am attempting to install Firefly III version 4.8.0.3. I'm following [these instructions](https://docs.firefly-iii.org/en/latest/installation/server.html)

When I run `php artisan migrate:refresh --seed`, I get the following error: The stream or file "/var/www/firefly-iii/storage/logs/ff3-cli-2019-09-07.log" could not be opened: failed to open
  stream: Permission denied

I checked the permissions on the file, and it was owned by root.  I ran `sudo chown -R www-data:www-data` directly on the log file (as well as chmod), and that still didn't fix the problem. 

However, running `sudo php artisan migrate:refresh --seed` worked.  I'm unsure if this is a documentation problem or a code problem.  Should I be running artisan commands as root?

**Comment by JC5** [comment]
It's a permission problem.

Try running `sudo -u www-data php artisan migrate:refresh --seed`.

You can also add yourself to the www-data group to fix this.

**Comment by nathanmerrill** [comment]
Perfect, thanks!
