### ISSUE TITLE
Tag search does not support all tag characters

### ISSUE THREAD

**Issue by ilvez** [firefly-iii/firefly-iii#2560]
First of all, thank you for this massive release of 4.8.1 and (re-)adding tag search support! :+1: 

**Bug description**
I am running Firefly III version 4.8.1. I'm using some non-ASCII, but still legit UTF-8 characters in my tag names. Tags work fine everywhere else, but searching those tags does not work. 

**Steps to reproduce**
1. Create a tag `test-täg`
2. Add this tag to some transaction.
3. Search with `tag:test-täg`
4. No results found. You can see some incorrect output suggesting that some parsing has failed:
- "Firefly III is searching for transactions with all of these words in them: **äg**"
- Tag is **"test-t"**

**Expected behavior**
"test-täg" behaves normally in search.

**Extra info**
Debug information generated at 2019-09-08 09:42:39 Europe/Tallinn for Firefly III version **4.8.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.8-1 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2019-01-21 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | pgsql |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, intl, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Comment by JC5** [comment]
The regex is pretty basic, yep. I’ll pick it up for one of the next releases.

**Comment by JC5** [comment]
Tag search (and others) will support special characters in the next release.
