### ISSUE TITLE
Fatal Error trying to visit Tags-page

### ISSUE THREAD

**Issue by wtrftw** [firefly-iii/firefly-iii#2561]
I am running Firefly III version 4.8.1

**Description**
I updated fireflyiii from 4.8.0.2 to 4.8.1 just now and after restarting the Docker container the overall interface seems to be in working order. I can navigate most of the menu items and successfully create a new transaction. Except when I click the Tags link I get a page showing: "Whoops - There was a fatal error. Please check the log files."

I tried a bunch of things:
- Redownload the image.
- Fix the old PHP reference (in the environment) to include the new 7.3.9, along with the links.
- Clear/remove the old container.

Is there anything else I can do fix this?

**Extra info**
Running fireflyiii through Docker on Synology DS218+. Fairly new user to both Docker and fireflyiii, so there's a big chance at being a user error. fireflyiii 4.8.0.2 was running fine for a couple of weeks now.

Here's the output from the /debug page:

Debug information generated at 2019-09-08 11:43:06 UTC for Firefly III version **4.8.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2019-07-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
I know the cause. I apologize for the inconvenience. I’ll be pushing a hot fix later today.

**Comment by JC5** [comment]
If you want to, you can fix it by hand using this code:

https://github.com/firefly-iii/firefly-iii/commit/a2ddd0420aa5872750422b0463eecbb1e744d8bf

**Comment by fightforlife** [comment]
Thanks, this fixed it for me!

**Comment by cmantsch** [comment]
I also get this error trying to access the startpage after upgrading my docker installation to the latest version

**Comment by JC5** [comment]
That makes sense. The error is caused by a query error. I expect your database container is a MySQL or MariaDB container?

I am looking at the open bugs, and if there's nothing too urgent, I'll push an update today.
