### ISSUE TITLE
"Whoops: Fatal Error" when accessing tags page (/tags)

### ISSUE THREAD

**Issue by xlfpx** [firefly-iii/firefly-iii#2562]
Hi!

I'm experiencing a bug when accessing the /tags page. - all I get is the standard "Whoops
There was a fatal error. Please check the log files."-page.
I've looked around in the docs for ways to get good logs to report this issue, but unfortunately can't get to more than some server-request logs. I've enabled [debug-mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) but the /storage/logs folder remains empty. What am I doing wrong / what could I have done wrong during installation? 

I'm attaching the output of `docker container logs` ( [firefly_logs.txt](https://github.com/firefly-iii/firefly-iii/files/3587571/firefly_logs.txt) ) as well as my [docker-compose.yml.txt](https://github.com/firefly-iii/firefly-iii/files/3587572/docker-compose.yml.txt) and [_.env.txt](https://github.com/firefly-iii/firefly-iii/files/3587574/_.env.txt) configuration files.

I'm running
 - Firefly III Version 4.8.1
 - using Docker-Compose
 - with PHP v7.3.4-2
 - set up to use my locally running mysql-db
 - on my RaspberryPi4 (4GB RAM)

I really like this project and would love to contribute to it - at least by submitting proper bug-reports when I encounter any. Unfortunately in this case I'd need a little help getting to some useful logs ^^
I have no prior experience with Docker or PHP, so I didn't try to dig any further into the code to see where things could have gone wrong.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2561
