### ISSUE TITLE
2 destination fields when editing recurring transactions

### ISSUE THREAD

**Issue by Skaronator** [firefly-iii/firefly-iii#2563]
**Bug description**
I am running Firefly III version 4.8.1, and I see 2 destination fields when I try to *edit* a recurring transaction.

**Steps to reproduce**
Looks like it only happens when editing *transfer* transactions. Withdrawal seems to be fine.

**Expected behavior**
I guess it should only have a single destination field?

**Extra info**
Docker on Linux, Chrome on WIndows

**Bonus points**
![image](https://user-images.githubusercontent.com/2886913/64491603-a6e67c00-d26a-11e9-95f3-d8870af2bda4.png)

The outer Divs have the following ids:

- destination_id_holder
- withdrawal_destination_id_holder

**Comment by JC5** [comment]
Thanks, I'll check it out. There's a fix due for the /tags page which is giving some people problems, so I might include this one as well.
