### ISSUE TITLE
Multiple pages not working in search

### ISSUE THREAD

**Issue by marviins87** [firefly-iii/firefly-iii#2564]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is that i cannot change pages while searching.

**Steps to reproduce**
1) Enter a random search query and search transactions with it (/search?search=test&go=)
2) If you get more results than the configured Page length you are able to select pages.
3) choose e.g. page 2 (/?page=2)
4) /?page=2 just redirects to the homepage instead of 2nd page of results. 

**Expected behavior**
It should redirect to the 2nd page of search resultst.

**Extra info**
The issue also occurred before in 4.8.0.3

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
Should be fixed in the next release.
