### ISSUE TITLE
Can't delete an account.

### ISSUE THREAD

**Issue by woolmonkey** [firefly-iii/firefly-iii#2565]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
When deleteing an account I get a 404 page and the account doesn't get deleted.

**Steps to reproduce**

Go to accounts and delete the account.  Chose none or move to another account and get a 404 page.
**Expected behavior**

I would expect the account to be deleted.
**Extra info**

**Bonus points**

**Comment by JC5** [comment]
I never saw this problem in 4.8.0.3. Could you please share the content of the /debug page and upgrade to 4.8.1?

**Comment by woolmonkey** [comment]
Sorry it was my issue forgot I was trying an application firewall. After disabling everything works.
