### ISSUE TITLE
Impossible to unlink bill

### ISSUE THREAD

**Issue by fvezzoli** [firefly-iii/firefly-iii#2567]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
Impossible to un-link bill from transaction.

**Steps to reproduce**
1. Create new bill and rule
2. Run rule
3. Modify rule to remove some transaction
4. Re-run rule

**Expected behavior**
The transaction not match the rule keep the bill link. Is not possible to remove them also in transaction edit.

**Extra info**
Try this on Chrome, Opera and Firefox under linux.

**Bonus points**
Is the same issue as #1622

**Comment by JC5** [comment]
Thanks, this must have disappeared somewhere. I'll pick it up again

**Comment by JC5** [comment]
Will be fixed in the next release.
