### ISSUE TITLE
Ledger / hledger support

### ISSUE THREAD

**Issue by dsx** [firefly-iii/firefly-iii#2569]
**Description**
Would be nice to have import from / export to [ledger](https://www.ledger-cli.org) and/or [hledger](https://hledger.org).

**Comment by JC5** [comment]
Yes it would be. Feel free to build something.

**Comment by dsx** [comment]
@JC5 it is just an idea. Nobody needs to drop everything and run to implement it right away.

**Comment by JC5** [comment]
I know I know :)
