### ISSUE TITLE
Error in POST to attachment API

### ISSUE THREAD

**Issue by RobinWeitzel** [firefly-iii/firefly-iii#2571]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is:

Using the API, I can not POST new attachments (POST to /api/v1/attachments).
The error message claims that the selected model is invalid (even though it should be fine).

**Steps to reproduce**
You can test this out using the API site and connecting to the demo.
I attached a screenshot from the demo site but I get the same result using my own server.

![image](https://user-images.githubusercontent.com/12135433/64553225-48d49a00-d339-11e9-875f-6a30bbc40e71.png)

**Expected behavior**
A new attachment entry should be created.

**Extra info**
This worked before 4.8.

Thank you very much for looking into this :)

**Comment by JC5** [comment]
Indeed. Use "TransactionJournal". I'll update the docs.

**Comment by RobinWeitzel** [comment]
Ah, that does indeed fix it. 
Is it therefore no longer possible to attach an attachment to a whole transaction?

To elaborate: I upload my receipts to firefly. If my purchase could be split into multiple categories (i.e. buying groceries and also a new electric toothbrush in one purchase) I attached the receipt to the whole transaction (since the receipt shows the payment for both categories) and then split the transaction. 

I am asking because I'm interested in the "philosophy" behind this change. The docs don't explain what the attachment field is for and I always assumed it was for receipts. But if that is the case, wouldn't one attachment for a whole transaction make more sense (since you get a receipt for your whole transaction).

Sorry for the long question and thank you for your help and for elaborating!

**Comment by JC5** [comment]
No, sorry about that. It's all linked to individual transactions. I understand the use case but database limitations make it difficult to change this.

**Comment by RobinWeitzel** [comment]
No Problem, this works as well. Thank you for all your hard work :)
