### ISSUE TITLE
Get 404 after deletion (in some cases)

### ISSUE THREAD

**Issue by RobinWeitzel** [firefly-iii/firefly-iii#2572]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is:

In certain cases, after deleting an entry (i.e. transactions, accounts...) I am redirected to the no longer existing entry.

**Steps to reproduce**
On page where entries (i.e. transactions, accounts...) are listed, click on the "edit" button for an entry.
Go back (via the back button in the browser) and click "delete" -> You get a 404 because the redirect tries to get the no longer existing entry.

**Expected behavior**
It should redirect back to the list. Looks like on the back-event the page is ignored and Firefly still thinks I came from the edit page (and thus redirects me there).

**Extra info**
Screenshot:

![image](https://user-images.githubusercontent.com/12135433/64553957-b59c6400-d33a-11e9-8bd3-18cab3987e1b.png)

It's a very niche problem but I still wanted to mention it :)

**Comment by JC5** [comment]
Yes, and there is a fix for it, but apparently not all routes are covered.

If you could let me know exactly 

1) which from page you're deleting 
2) what kind of an object

I can dive into the issue.

**Comment by RobinWeitzel** [comment]
So far, I encountered the bug on the following pages:
* accounts/expense
* tags/show/<id>
* transactions/withdrawal

This makes me pretty confident that the bug will occur on all pages of similar structure (lists that offer an edit and a separate delete). Thus it does (seemingly) not depend on the kind of object.

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
I added a warning to the logs, so if it happens again you should be able to see it in your log files. I wasn't able to replicate anything but at least this way you'll have some log files to use to tell me what happened. Look for a notice like:

```
 production.WARNING: GracefulNotFoundHandler cannot handle route with name "transactions.edit"  
```
