### ISSUE TITLE
Can not update split transaction if an error was made

### ISSUE THREAD

**Issue by RobinWeitzel** [firefly-iii/firefly-iii#2573]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is:

If I split an existing transaction but make an error during data entry (which interrupts the update), the button remained disabled even after I fix the wrongfully entered data.

**Steps to reproduce**
Go to an existing transaction, click on split and leave the split transaction description empty. Click on "Update".

**Expected behavior**
It should still allow me to update once I entered a description.

**Extra info**
Screenshot:

![image](https://user-images.githubusercontent.com/12135433/64557181-5130d300-d341-11e9-839d-b9b7b5f66bd6.png)

In the above screenshot, I entered a description after the error message but the button is still disabled.

**Comment by RobinWeitzel** [comment]
Just found out, the same thing happens if I only upload an attachment. It seems that usually on update, the page is reloaded (which also enables the button again). However, if an error occurs or only an attachment is uploaded, this reload is not triggered.

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
This will be fixed in the next release.
