### ISSUE TITLE
Unable to change currency on transactions

### ISSUE THREAD

**Issue by Joshhua5** [firefly-iii/firefly-iii#2574]
I created an account in the default Euro and imported my transactions, these were created in Euro. after changing the account currency, the transactions are still in Euro.

There doesn't appear to be a UI element for changing the currency of the transaction.

**Comment by Joshhua5** [comment]
This includes changing the currency of a Expense account.

**Comment by JC5** [comment]
Yes, transactions have their own currency and changing the account won't update them. This is by design.

I'll make sure that the transaction's currency can be changed easily.

**Comment by JC5** [comment]
In a future version of Firefly III, changing the currency of a transaction can only be done by changing the account itself. Firefly III will then warn you that all transactions will be updated to the new currency.
