### ISSUE TITLE
Create Rule from existing transaction

### ISSUE THREAD

**Issue by Joshhua5** [firefly-iii/firefly-iii#2575]
Adding a feature to create a rule based off a existing transaction would improve the workflow during the initial setup period.

**Comment by JC5** [comment]
Not a bad idea, I'll think about it :)

**Comment by greenspray** [comment]
Isn't this just a simplified version of this issue https://github.com/firefly-iii/firefly-iii/issues/1806

The rule can be extracted via the steps mentioned in that issue.

**Comment by JC5** [comment]
This will be possible in an upcoming release, 5.1.0.

**Comment by JC5** [comment]
This issue will be closed, now that the first alpha of 5.1.0 is out. Keep an eye out on the release page. If something comes up, please open a new issue. Thanks!
