### ISSUE TITLE
Budget ordering not reflected on dashboard

### ISSUE THREAD

**Issue by rnck** [firefly-iii/firefly-iii#2576]
**Bug description**
I am running Firefly III version 4.8.1 (Docker), and my problem is:

Budget ordering doesn't get reflected on the dashboard.

**Steps to reproduce**
Reorder budgets on the budgets page. Go back to Dashboard. Ordering of budgets remains as is. 

**Expected behavior**
Same order of budgets on dashboard and budgets page.

Please let me know if you need more info!

**Comment by JC5** [comment]
Good one, I'll check it out and fix it.

**Comment by JC5** [comment]
The chart will reflect the ordering correctly, but keep in mind the chart is cached. Browse to /flush to see the results of reordering budgets.

**Comment by rnck** [comment]
Thank you. Can be closed.
