### ISSUE TITLE
Split transactions have same categories after upgrade to 4.8.x

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#2577]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is:
After upgrade from 4.7.17 to 4.8.1 all my split transactions have the same category. In 4.7.17 I had different categories per each split transaction.

**Steps to reproduce**
1. Create split transaction in pre 4.8.x version.
2. Assign different categories for each transaction.
3. Upgrade to 4.8.x version.

**Expected behavior**
After upgrade all categories for split transactions should be the same as before.

** Example reports for single category **
![obraz](https://user-images.githubusercontent.com/4746858/64599395-998bd780-d3b9-11e9-8867-88956b20093d.png)

**Comment by JC5** [comment]
Sorry about that, I thought I had this covered and tested. I'll do some debugging and fix the routine for the next release. It means you'll have to restore your database and upgrade again though.

**Comment by fengkaijia** [comment]
Can confirm this behavior.

BTW, is there any documented procedure to export everything happened since the migration so that we can import it later?

**Comment by skibbipl** [comment]
> Sorry about that, I thought I had this covered and tested. I'll do some debugging and fix the routine for the next release. It means you'll have to restore your database and upgrade again though.
No probs, I always do test upgrade on a database copy :)

**Comment by JC5** [comment]
@fengkaijia No, there isn't. Easiest would be to select everything with a `created_at` date or `updated_at` date after you upgraded but that's a recipe for inconsistencies.

**Comment by JC5** [comment]
I was able to fix this, and a local test confirms it. I will include it in the next release. Keep an eye on the results and let me know, so I'll be sure it all works as expected.
