### ISSUE TITLE
Budget time period lengths

### ISSUE THREAD

**Issue by hvidgaard** [firefly-iii/firefly-iii#2578]
**Description**

In budgeting there is often a need to have rolling budgets. For instance clothing, buying a new winter parka is more than a months budget, the children get new shoes biannually, my wife may need a new dress for a wedding, and I need new shirts every now and then. It's not possible to capture that in a monthly budget allocation.

It makes sense to say "with my economy, it's reasonable to set aside $200 monthly for clothing", and with a "rolling" budget money not spend this month is automatically added to next month.

It extends to quite a few variable budget posts:
* day trips
* car maintenance and tires (and hopefully a new car at some point)
* hobbies
* restaurant visits
* groceries (bulk buys happen infrequently, but shouldn't put you in negative if you've had a surplus in previous months). 

**Solution**

Budgets should be time defined for monthly, quarterly, biannually, yearly, or unrestricted, with the first four being the time period they span over, and the "unrestricted" will simply keep track of a monthly addition and expenses. Bonus if they can be rolling in the sense that the surplus is automatically added to the next budget allocation period (this would remove the need for an unrestricted period).

**What are alternatives?**

You can create "virtual" accounts and set up a recurring transaction, and withdraw from that. I think it's also possible to wrestle piggy banks into doing this too.

**Additional context**

It gives a clear view of how much can I use now, and if I want to buy, say a new piece of equipment for brewing, when will my hobby allocation reach the point where I can buy it. All within the reasonable monthly allocation for that budget, without the need to manually (ab)use double entry systems for it, or fiddling around with piggy banks for something you've already decided to mark for that specific purpose.

**Bonus points**

I am aware of the opinionated answer to previous suggestions for a rolling budget, but I've outlined some reasons why it makes sense to me, and in general - I know a lot of people share that view of budgeting. It really is the only thing I see missing from this and I promise to donate if I get to use this system our budging needs. I find the prospect of having my budgeting tool inside my own firewall very appealing :)

**Comment by JC5** [comment]
Thanks for the expansive request. I understand it, and it's on the roadmap for sure. Feel free to donate whenever you want. With or without a rolling budget feature.

**Comment by hvidgaard** [comment]
Sounds good. I'll see to getting this running locally when I get some spare time and see how it works out.

**Comment by schoeke** [comment]
I come from YNAB and have the same "issue". Piggy banks could be extended to do that in a few discrete steps.

- Make target amount optional (Maybe with a checkbox)
- Allow reoccuring virtual "transfers" from account to piggy banks
- Target date would get a checkbox "Automatically renew (as rolling budget)" or similar which would  transfer the piggy banks money amount to a new one with the same settings  and duration

This probably a lot of work as a whole but each point could be considered its own feature.

**Comment by JC5** [comment]
Nice. I have to say, I am not a big fan of YNAB’s zero based budgeting and it’s not something I’m going to replicate.

**Comment by JC5** [comment]
Hi guys,

Thanks for your patience. I'm replying to let you know that this feature will be a part of the next release of Firefly III, 5.2.0.

The [documentation](https://docs.firefly-iii.org/concepts/budgets#automatic-budgeting) is already up and running and the demo site features the updates as well. Keep in mind however that because the demo site resets very often, it won't actually "work".

Since this constitutes an API change and a new migration it will be some time before this is available in a general release. There will be an alpha and a beta version first, at least.

Up until then, you can use the `develop` tag on GitHub or Docker to try it out. 

Thanks again for the great idea and patience. Please send your feedback my way. I'm going to mark this ticket as fixed, and it will be closed when the first alpha is released.

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.

**Comment by sephrat** [comment]
Great feature that I didn't expect but I'm glad to see :-) 
A small feedback for now: I forgot to set the first dropdown list but it seems nothing is saved if it is set to "no automatic budget". I thought I set it all up but I have to do it again. Maybe hide the other fields while automatic budget is not set to prevent data loss?

**Comment by JC5** [comment]
Good idea, I've changed Firefly III to disable them when no option is selected.
