### ISSUE TITLE
Reconcilation transactions cannot be modified

### ISSUE THREAD

**Issue by wgml** [firefly-iii/firefly-iii#2580]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is:

Once created, reconcilation transactions cannot be modified or removed. Any action, such as edit, convert or delete results in redirect to specific account page and no action is performed. There is also no error message displayed.

**Steps to reproduce**
1. Reconcile account.
2. Attempt to remove the reconcilation transaction.

**Expected behavior**
I am able to remove transaction or convert it to other type.

**Extra info**
I'm running Firefly in docker container with mostly default configuration, modifying only secrets in env file.

`/debug`:

Debug information generated at 2019-09-10 22:02:47 Europe/Warsaw for Firefly III version **4.8.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2015-07-28 00:00:00 |
| Session end | 2019-09-10 00:00:00 |
| Session first | 2015-07-28 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
Thanks. This is correct, it's on a todo-list somewhere. I'll pick it up :)

**Comment by alphat5** [comment]
Hi,

I have the same issue. Do you have an ETA when it will be fixed @JC5  ?

Thanks,

**Comment by JC5** [comment]
This should work in the next release.
