### ISSUE TITLE
Issue on unpgrading to 4.8.1

### ISSUE THREAD

**Issue by silenx** [firefly-iii/firefly-iii#2583]
Hello,

this is the issue that i faced:

`
firefly@firefly:~$ composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated 4.8.1
Installing grumpydictator/firefly-iii (4.8.1)
  - Installing grumpydictator/firefly-iii (4.8.1): Downloading (100%)         
Created project in firefly-iii-updated
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php -r "if (!(getenv('DYNO'))===false){file_exists('.env') || copy('.deploy/heroku/.env.heroku', '.env');copy('.deploy/heroku/.locales', '.locales');}"
Loading composer repositories with package information
Installing dependencies from lock file

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  

`
I forgot:
before doing that, i installed php7.3 and all the module needed ( uninstalled 7.2 )

**Comment by JC5** [comment]
Mmmm, that error doesn't ring a bell, sorry about that. Do you have a stack trace?

**Comment by silenx** [comment]
How to get them?

**Comment by JC5** [comment]
Try running the command with `-v` or `-vv`. That should work.

**Comment by silenx** [comment]
`composer -vv create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated 4.8.1
Installing grumpydictator/firefly-iii (4.8.1)
  - Installing grumpydictator/firefly-iii (4.8.1): Loading from cache
 Extracting archiveCreated project in firefly-iii-updated
> post-root-package-install: @php -r "file_exists('.env') || copy('.env.example', '.env');"
> pre-install-cmd: @php -r "if (!(getenv('DYNO'))===false){file_exists('.env') || copy('.deploy/heroku/.env.heroku', '.env');copy('.deploy/heroku/.locales', '.locales');}"
Loading composer repositories with package information
Installing dependencies from lock file

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                           

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:286
 Composer\Util\ErrorHandler::handle() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 include() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 Composer\Autoload\includeFile() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:322
 Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
 spl_autoload_call() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php:75
 Composer\DependencyResolver\Solver->__construct() at phar:///usr/local/bin/composer/src/Composer/Installer.php:470
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:223
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:188
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:143
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:861
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:208
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:54
 require() at /usr/local/bin/composer:24

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
`

**Comment by JC5** [comment]
That's a composer error. Is there a newer version for composer maybe?

**Comment by silenx** [comment]
Yes, upgrading to composer 1.9 solve this.
Thank you
