### ISSUE TITLE
After creating a transfer I am redirect to a page with []

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2587]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is:

After creating a transfer I am redirect to a page with []

**Steps to reproduce**
Create a transfer

**Expected behavior**
Go to some system page (transaction itself or account)

**Extra info**
Safari

**Comment by JC5** [comment]
I added a fix that should prevent this from happening in the future.
