### ISSUE TITLE
Add Created Date on search option

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2589]
**Description**
I would love to search transactions that were created on specific date

**Solution**
None

**What are alternatives?**
Query the database to find those transactions

**Comment by JC5** [comment]
<img width="771" alt="Screenshot 2019-09-14 at 06 21 41" src="https://user-images.githubusercontent.com/5889984/64903395-fcca8200-d6b7-11e9-817f-0e79da34eb96.png">
