### ISSUE TITLE
Demo site crashes after login

### ISSUE THREAD

**Issue by ArcCha** [firefly-iii/firefly-iii#2591]
**Bug description**
I am able to log in to the demo site using `demo@firefly` and `firefly` pair. Then, I am redirected to a page that says:

```
Whoops
There was a fatal error. Please check the log files.
```

**Steps to reproduce**
Log in to the [demo site](https://demo.firefly-iii.org/login) using aforementioned credentials.

**Expected behavior**
I've expected to see the demo site itself, I should see some kind of dashboard with sample data and so on.

**Extra info**
Arch Linux, Chrome 76.0.3809.132.

By the way, current docs do not say anything about default credentials to the demo site. Also, link from the [main page of the project](firefly-iii.org) takes directly to the demo site. So it is kind of confusing when you want to see the demo, but you have no idea with what you should log in. I had to search old issues on github.

**Comment by ArcCha** [comment]
@JC5 Thank you for your swift response, really appreciate it!

**Comment by JC5** [comment]
I've been keeping an eye on it and it seems to be fixed.

**Comment by ArcCha** [comment]
@JC5 It seems that we have a similar problem again. I've just tried to log in into the demo instance in order to try to reproduce a possible bug. Installation & migrations ran, then the login form appeared, but once again without any information on how to log in. The credentials that I've used before do not work, login form just reloads.

**Comment by JC5** [comment]
Check. Thanks.
