### ISSUE TITLE
Budget graph not showing

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2593]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is:

The budget is not plotting the graph, just a blank graph.

**Steps to reproduce**
Open budget pages (one with transactions)

**Expected behavior**
See the plot of the graph

**Comment by iwalucas** [comment]
I was able to replicate it on DEMO:
https://demo.firefly-iii.org/budgets/show/6

but not sure its actually a bug....

I setup the budget in EURO, and only have USD transactions on it.... so in this case it doesnt show a graph

**Comment by JC5** [comment]
It's not a bug, but I've made the budget overview a bit more clear on what's going on.

In the mean time the demo site has reset itself but you can recreate it and see the improvements.
