### ISSUE TITLE
Add custom sorting of accounts

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#2595]
**Description**
Usually, you will want your cash and assets accounts to be up in the list in the dashboard, visible before the saving accounts. As of today, it seems that the last added account shows first. 

**Solution**
- solution 1: sort by account type (cash first, then asset, then savings, etc...), then by account name asc. Any account starting with `_` will be bumped at the top.
- solution 2: more elegant, but probably more work: let the user define a custom order as it is possible with the budget entries.

**What are alternatives?**
I tried renaming my accounts from `My Account` to `_My Account` hoping for a string based sorting but this does not work.

**Additional context**
It may also be a good feature to let the user decide to NOT show accounts in the dashboard (but still include them in the net worth).

**Bonus points**
I will think of a drawing for the next issue :)

**Comment by JC5** [comment]
Accounts should be sorted by whether they are active (inactive at the bottom) and then by name. I'm not going to add anything else, sorry about that.

I've been playing around on the demo site and it works just fine.

**Comment by chevdor** [comment]
Did you maybe change that in 4.8.1.1? I am running 4.8.1 and prepending `_` does *not* bring the account up. On the demo however, it does (which is cool):
![image](https://user-images.githubusercontent.com/738724/64873907-55633600-d64a-11e9-9c63-7a6332e9e52a.png)

I also noticed indeed that setting an account as inactive does help but I was not sure if there are other consequences in doing so.

**Comment by chevdor** [comment]
As workaround, I found that one can rename the accounts as:
- `1_ Some account`
- `2_ Another`
- `3_ ZAccount`
- `4_ AACount`

while maintaining the ordering.

**Comment by JC5** [comment]
Thanks, I see what you mean, I'll check it out.

**Comment by chevdor** [comment]
Btw, on the demo, I put `Savings Account` as inactive and it still shows up.
So if you have many accounts, that clutters the dashboard quite a lot and prevents to nicely see the `Bills` for instance.

![image](https://user-images.githubusercontent.com/738724/64874558-8abc5380-d64b-11e9-9e1e-dcad1f5cb0ba.png)

**Comment by chevdor** [comment]
Now that we have an ordering workaround, an easy win may be to:
- pack all accounts in a div
- limited in height
- with a visible scrollbar if needed

That would help better see those `Bills` and `Piggy banks` you added (this is also super cool btw).

**Comment by JC5** [comment]
Check your preferences to control what you see on the front page :)

**Comment by chevdor** [comment]
Ohhh! There we go.
That is the piece I was missing! I love this project more and more every
day!
