### ISSUE TITLE
Impossible to delete the last tag from a transaction

### ISSUE THREAD

**Issue by wangongtsen** [firefly-iii/firefly-iii#2596]
_Edit: This description is wrong, look at the third post._

**Bug description**
I am running Firefly III version 4.8.1, and my problem is:
It is impossible to delete tags from transactions that were created prior to 4.8.

**Steps to reproduce**
1. Edit a transaction that contains a tag and was created prior to version 4.8 and remove that tag.
2. Open the same transaction again and the tag is still there.

**Extra info**
I'm using docker and pgsql.
Removing tags from newly created transactions works as expected.

**Comment by JC5** [comment]
There is no difference between old transactions and new ones. I can delete tags in both old and new transactions. I can't seem to replicate this issue.

**Comment by wangongtsen** [comment]
I am sorry, I didn't narrow the issue down enough as it seems. When the transaction was created doesn't affect the outcome.

For me it is just not possible to delete the last tag for any given transaction.

Steps to reproduce:
1. Create transaction with tags a and b.
2. Edit transaction and remove tag b. (works as expected, only tag a is assigned)
3. Edit transaction and remove tag a. (tag a is still assigned)
4. Edit transaction and remove tag a and create tag c.  (works as expected, only tag c is assigned)
5. Edit transaction and remove tag c. (tag c is still assigned)

The first time I notice this behavior is right now after my update from 4.7.17.

**Comment by wangongtsen** [comment]
Unfortunately 4.8.1.1 doesn't fix it for me. Do you have any suggestions where to lock for hints what's causing this?

Yet deleting the tag itself from the tags page does remove it from the transaction.

**Comment by JC5** [comment]
You're right, I was mistaken. I was too quick to check if the problem was solved. I can replicate it now and I'm looking into it.

**Comment by JC5** [comment]
Alright the issue will be fixed in the next release.
