### ISSUE TITLE
Edit of transaction return wrong foreigh amount

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2598]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
when I edit transaction with foreign amount it displayed incorrect.
1. Create transfer from **UAH** (for example) to **USD**.
![image](https://user-images.githubusercontent.com/25054050/64908510-db928180-d709-11e9-8051-addaa58b9191.png)
2. Find this transaction in your transaction history and edit it.
You can see that foreign amount is **EUR**, this is **confusing**.
![image](https://user-images.githubusercontent.com/25054050/64908592-e3065a80-d70a-11e9-9922-b8ed102f7e8c.png)

**Comment by JC5** [comment]
Nice find. This will be fixed in the next release.
