### ISSUE TITLE
Adding funds to piggy bank works incorrect with transfers

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2599]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:
adding funds to piggy bank works incorrect with transfers

1. Create asset account in USD.
Opening balance 1000USD
![image](https://user-images.githubusercontent.com/25054050/64908594-ffa29280-d70a-11e9-9c28-93e64f46f4cb.png)

2. Create asset account in UAH (for example).
Opening balance 10000UAH
![image](https://user-images.githubusercontent.com/25054050/64908623-6b84fb00-d70b-11e9-8ff7-769b39e031e8.png)

3. Go to Money management - Piggy banks
Create new piggy bank. 
Save on USD account you just created. 
Target amount 2000$.
![image](https://user-images.githubusercontent.com/25054050/64908651-d46c7300-d70b-11e9-8990-44e2749911f1.png)
Store it.

4. Add money to your piggy bank
Add all 1000$
![image](https://user-images.githubusercontent.com/25054050/64908688-244b3a00-d70c-11e9-9c73-b4a0098b831d.png)

5. You can see that your piggy bank 50% full 
![image](https://user-images.githubusercontent.com/25054050/64908713-55c40580-d70c-11e9-887a-8fa61abe99eb.png)

6. Go to Transactions - Transfers.
Transfer all money from your UAH account to USD account.
1000 UAH is 403 USD
Add it to your piggy bank.
![image](https://user-images.githubusercontent.com/25054050/64908748-a3407280-d70c-11e9-9761-ae5b52b86bfb.png)

7. Go to your piggy bank
![image](https://user-images.githubusercontent.com/25054050/64908774-d97df200-d70c-11e9-9c7f-aa39ed92ec53.png)
You can see that piggy bank is full for 100%.
But we just add 403 usd to 1000 usd and target sum is 2000 usd.
**Sum is incorrect.**

**Comment by JC5** [comment]
Thanks, nice find. Good edge case. This will be fixed in the next release.
