### ISSUE TITLE
FinTs PSD2

### ISSUE THREAD

**Issue by Schikri** [firefly-iii/firefly-iii#2601]
I used to import via fints quite well with different banks.

Since this week my import does not work for any bank anymore. I suppose there is any other parameter needed beside of URL, Bankcode, Username and PIN.

Does anyone has an idea?

The errosr is: Request Failed: Unknown error. There is also nothing in the log files. I am using firefly version 4.7.17

**Comment by JC5** [comment]
I'll need some logs to see what's wrong I'm afraid. What makes you say it's PSD2 related?

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on Github, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by Schikri** [comment]
Here is my debug log:

[2019-09-15 17:46:11] local.DEBUG: Going to try to decrypt users currency preference.  
[2019-09-15 17:46:11] local.DEBUG: Could not decrypt "EUR". The payload is invalid.  
[2019-09-15 17:46:11] local.DEBUG: Now in postConfigure() {"job":"ijgjgYVGU4z4"} 
[2019-09-15 17:46:11] local.DEBUG: Going to create class "FireflyIII\Import\JobConfiguration\FinTSJobConfiguration"  
[2019-09-15 17:46:11] local.DEBUG: Updating configuration...  
[2019-09-15 17:46:12] local.DEBUG: Will NOT set previous URL to http://firefly-iii.idoleo.de/import/job/configuration/ijgjgYVGU4z4  
[2019-09-15 17:46:12] local.DEBUG: Now in JobConfigurationController::index()  
[2019-09-15 17:46:12] local.DEBUG: Now in JobConfigurationController::index() with job "ijgjgYVGU4z4" and status "has_prereq"  
[2019-09-15 17:46:12] local.DEBUG: Going to create class "FireflyIII\Import\JobConfiguration\FinTSJobConfiguration"  
[2019-09-15 17:46:13] local.DEBUG: Will set previous URL to http://firefly-iii.idoleo.de/import/job/configuration/ijgjgYVGU4z4  
[2019-09-15 17:46:13] local.DEBUG: viewRange is 1Y  
[2019-09-15 17:46:13] local.DEBUG: isCustom is false  
[2019-09-15 17:46:13] local.DEBUG: subtractPeriod: date is 2019-01-01, repeat frequency is 1Y and subtract is 1  
[2019-09-15 17:46:13] local.DEBUG: 1Y is in function map, execute subYears with argument 1  
[2019-09-15 17:46:13] local.DEBUG: subtractPeriod: resulting date is 2018-01-01  
[2019-09-15 17:46:13] local.DEBUG: Will NOT set previous URL to http://firefly-iii.idoleo.de/v1/jscript/variables?ext=.js&v=4.7.17

**Comment by Schikri** [comment]
Hi,

here is my debug log:

2019-09-15 17:46:11] local.DEBUG: Going to try to decrypt users currency preference.  
[2019-09-15 17:46:11] local.DEBUG: Could not decrypt "EUR". The payload is invalid.  
[2019-09-15 17:46:11] local.DEBUG: Now in postConfigure() {"job":"ijgjgYVGU4z4"} 
[2019-09-15 17:46:11] local.DEBUG: Going to create class "FireflyIII\Import\JobConfiguration\FinTSJobConfiguration"  
[2019-09-15 17:46:11] local.DEBUG: Updating configuration...  
[2019-09-15 17:46:12] local.DEBUG: Will NOT set previous URL to http://firefly-iii.xxxxxx.de/import/job/configuration/ijgjgYVGU4z4  
[2019-09-15 17:46:12] local.DEBUG: Now in JobConfigurationController::index()  
[2019-09-15 17:46:12] local.DEBUG: Now in JobConfigurationController::index() with job "ijgjgYVGU4z4" and status "has_prereq"  
[2019-09-15 17:46:12] local.DEBUG: Going to create class "FireflyIII\Import\JobConfiguration\FinTSJobConfiguration"  
[2019-09-15 17:46:13] local.DEBUG: Will set previous URL to http://firefly-iii.idoleo.de/import/job/configuration/ijgjgYVGU4z4  
[2019-09-15 17:46:13] local.DEBUG: viewRange is 1Y  
[2019-09-15 17:46:13] local.DEBUG: isCustom is false  
[2019-09-15 17:46:13] local.DEBUG: subtractPeriod: date is 2019-01-01, repeat frequency is 1Y and subtract is 1  
[2019-09-15 17:46:13] local.DEBUG: 1Y is in function map, execute subYears with argument 1  
[2019-09-15 17:46:13] local.DEBUG: subtractPeriod: resulting date is 2018-01-01  
[2019-09-15 17:46:13] local.DEBUG: Will NOT set previous URL to http://firefly-iii.xxxxxx.de/v1/jscript/variables?ext=.js&v=4.7.17

**Comment by JC5** [comment]
There are no errors in the debug log. As far as I can tell the import hasn't started yet. Without more I'm afraid there's not much I can do.

**Comment by Selfmade-RuLeZ** [comment]
I think it has something to do with the new TAN authentification. Since 14.09.19 you should verify you with your TAN App. Could you have a look at it and maybe implement it?

**Comment by JC5** [comment]
No. I have no FinTS enabled bank and there are no sandbox API's I can use.

**Comment by Selfmade-RuLeZ** [comment]
Ah I understand. I‘ll have a look to solve this problem when I‘ve learned php :D 
I think I found the issue, you can‘t connect via the FinTS dialog from this date, you have to communicate with the PSD2 API. 
Here‘s some information:
https://subsembly.com/apidoc/fints/index.html#important-client-registration-for-psd-2-compliance

**Comment by luqasn** [comment]
I am also affected by this. I first removed the try/catch around the `getSEPAAccounts` in order to get to the exception (no logger is injected in the FinTS part). Then I tried replacing `mschindler83/fints-hbci-php` with `nemiah/php-fints` and setting the new, required parameters `productName` and `productVersion` to values I blatantly stole from Hibiscus for testing (Firefly would need their own registered ID in order to fix this for real).

Unfortunately, I still get an error now:
`Request Failed: Die Nachricht enthält Fehler. (9050); Banking-Programm nicht PSD2-fähig, bitte aktualisieren. (9075); Dialog abgebrochen (9800); Ungültige Auftragsnachricht? (9340)`
This is saying "Your banking application does not support PSD2, please update."
I have no idea why it is saying that, I might need to get in contact with the people over at `nemiah/php-fints`.

**Comment by JC5** [comment]
I have a PSD2 registration already, so no worries there. The library must also support it and then I have to insert the ID into the code of Firefly III. I'll pick this up over the coming weeks. 

Like I mentioned before, I'm not aware of any FinTS sandboxes or test environments that I can use. Without them, I am reliant on the various FinTS libraries there are, combined with the error reports from friendly users like you guys.

Progress may be slow, but I'll keep you posted.

**Comment by luqasn** [comment]
I found https://github.com/nemiah/phpFinTS/issues/31 and indeed pinning the version using `composer require nemiah/php-fints dev-master` fixed the issue and I can now continue to the account selection screen! After cho0sing my account and continuing, I get a new error:
```Firefly III v4.8.1.1 ran into an error: Return value of FireflyIII\Transformers\TransactionGroupTransformer::getSourceTransaction() must be an instance of FireflyIII\Models\Transaction, null returned.

The error was of type "Symfony\Component\Debug\Exception\FatalThrowableError".

The error occured on/at: Mon, 16 Sep 2019 20:26:44 +0200.

This error occured in file "/var/www/firefly-iii/app/Transformers/TransactionGroupTransformer.php" on line 150 with code 0.```
But I don't think that has anything to do with FinTS anymore.

**Comment by SwapFaceL** [comment]
I can confirm that for me it does not work either anymore to import bank account statements via FIN TS. I am using this feature with an account of the DKB (Germany).

**Comment by Schikri** [comment]
Does anyone found a solution for this problem. I was able to get a product registration number. When I try to import, I permanently receive the following message: 

" Request Failed: Die Nachricht enthält Fehler. (9050); Starke Kundenauthentifizierung notwendig.", which means that the application requires a strong authentification which can be a two factor authentification. This feature is actually missing in firefly. Curiously my bank unlike ING Diba does not ask for two factor authentification when I login through browser.

I was able to find sth. on the web. I need to see if I can implement sth. like this and will report:

https://www.twilio.com/docs/authy/quickstart/two-factor-authentication-php-laravel

**Comment by r00tusrDE** [comment]
I tried to import from Sparkasse and got this error: "Warning! An error occurred while trying to connecting to your bank. Please make sure that all the data you entered is correct. Original error message: Request Failed: Unknown error". Is this because of this issue?
I didn't find any error message in the log files, even with debug enabled and log level on debug :/

**Comment by JC5** [comment]
Same problem, and there's nothing I can do at the moment. PSD2 is making it harder for Firefly III to connect, not easier.

**Comment by r00tusrDE** [comment]
No problem, I just wanted to know if the error is because of the PSD2 incompatibility or if my bank just gave me the wrong API-URL. I never used FinTS before.

**Comment by erdnussflips** [comment]
Maybe this Library could help: https://github.com/Teskon/PSD2PHP

**Comment by marvinwankersteen** [comment]
Same problem with a german Volksbank. I tried FinTS-URL `https://hbci11.fiducia.de/cgi-bin/hbciservlet`

**Comment by erdnussflips** [comment]
Future updates to the import routine: https://www.patreon.com/posts/30012174

**Comment by SwapFaceL** [comment]
@erdnussflips @JC5 are these new import routines are already in the code? 
Or does someone else has an easy fix for the problem already?! Did someone tried #2622 ???

**Comment by JC5** [comment]
It will be in the changelog when it's in the code.

**Comment by SwapFaceL** [comment]
Thanks for the fast reply, as soon as it's in I will donate you a beer ;)
and sorry for asking again, I just got used to the convenience of firefly and just miss using it...

**Comment by JC5** [comment]
Not to worry. Lots of things on my plate. Hope to get around to it soon :)

**Comment by darkphoenix** [comment]
Is this still alive? I feel like the bot is being a bit overly aggressive in closing unresolved issues...

**Comment by JC5** [comment]
This isn't particularly alive at the moment. I'm currently developing [separate import apps](https://www.patreon.com/posts/future-updates-30012174) and a FinTS importer is on that list as well.

All I need is a PSD2 compatible sandbox environment. There were none when I first implemented this feature and I had to rely on German users to test and debug the code. I'd like to avoid that next time.

**Comment by reharmsen** [comment]
> All I need is a PSD2 compatible sandbox environment. There were none when I first implemented this feature and I had to rely on German users to test and debug the code. I'd like to avoid that next time.

Rabobank (a Dutch bank) has a free sandbox you can sign up for via https://developer.rabobank.nl/

**Comment by JC5** [comment]
Unfortunately, they don’t have support for FinTS.

**Comment by brunopereira7** [comment]
I don't know the current status but regarding:

> All I need is a PSD2 compatible sandbox environment. There were none when I first implemented this feature and I had to rely on German users to test and debug the code. I'd like to avoid that next time.

SIBS API Market has a PSD2 complatible sandbox environment: https://www.sibsapimarket.com/

**Comment by besendorf** [comment]
At 36C3 there was a talk about PSD2 and its implications for end users. If I understood it correctly its not possible for firefly-iii or any other app to implement psd2 without having it running as a cloud provider. There is also an english and spanish translation. https://media.ccc.de/v/36c3-10717-was_hat_die_psd2_je_fur_uns_getan#l=eng
In the end I explicitly asked the speaker about if its possible to implement psd2 in firefly-iii (didnt mention the name though) and he said its not possible. 
I was under the impression that you was to implement it though. Am I missing something?
@JC5

**Comment by marcelbrueckner** [comment]
Although I didn't watch the talk, I don't think you need to run a cloud service. Otherwise, other famous banking clients like StarMoney, Banking4 or MoneyMoney wouldn't work either. @JC5 has to do include his registration number in Firefly III (see #2322 where you can also find a link to the German credit business' FAQ).
