### ISSUE TITLE
Implement Datepicker on Transactions page

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2602]
**Description**
I couldn't fin any related feature request like this, so here it is:

It would be good if Firefly III had a datepicker (like this one https://jqueryui.com/datepicker/) on its create/update transaction screen.
Since we currently cannot change how to input dates (yyyy-mm-dd), this could be helpful on picking dates.

**Solution**
Implement a datepicker JS functionality

**What are alternatives?**
None

**Comment by davidschlachter** [comment]
How would this be better than the current datepicker?

![2019-09-14-224815_2560x1440_scrot](https://user-images.githubusercontent.com/8271268/64915987-75d2e380-d763-11e9-9180-2e5c458a494b.png)

**Comment by JC5** [comment]
https://caniuse.com/#feat=input-datetime

**Comment by iwalucas** [comment]
Now thats weird... how come I can’t see it?

**Comment by iwalucas** [comment]
@JC5 thanks.... problem is in my browser!!! all this months I didnt know that, feels so stupid now..... tks
