### ISSUE TITLE
Add allCategories and allAccounts keywords for report URLs

### ISSUE THREAD

**Issue by davidschlachter** [firefly-iii/firefly-iii#2603]
**Description**

Currently firefly-iii supports special keywords in the URLs of reports in order to facilitate bookmarking, e.g. `currentMonthStart`, `currentYearStart`. However, similar keywords are not available for categories or accounts, which are all listed individually in report URLs (e.g. `5,28,11,1,3/`).

Currently I've been adding many new categories, and keywords in the URLs such as `allCategories` or `allAccounts` would make it easy to bookmark reports when these elements are changing.

**Solution**
For accounts and categories in reports, add new URL 'magic words' `allCategories` and `allAccounts`.

**What are alternatives?**
Manually select all categories and all accounts from the reports creation page each time the report is to be viewed.

**Comment by JC5** [comment]
Yeah that's a good idea.

**Comment by JC5** [comment]
Included the option to set `allTags`, `allCategories` and `allBudgets`.

The option to include all asset accounts already exists (`allAssetAccounts`) and is now [documented as well](http://docs.firefly-iii.org/en/latest/advanced/reports.html)
