### ISSUE TITLE
Consider releasing under to AGPL instead of GPL

### ISSUE THREAD

**Issue by nxxxse** [firefly-iii/firefly-iii#2607]
**Description**

Currently the GPL is used which has the application service provider loophole.

**Solution**

 Have you considered the AGPL?

https://en.wikipedia.org/wiki/Affero_General_Public_License
https://stackoverflow.com/questions/2127246/difference-between-affero-gpl-and-gplv3

**Comment by JC5** [comment]
No, not really. I understand the loophole though.

**Comment by nxxxse** [comment]
@JC5 Could my maybe leave this issue open and consider it in a relaxed minute? I think this small detail is important for Firefly III to ensure users freedoms and to avoid that the next random company grabs the code base, and makes a closed business out of it. With the GPL, they could do this no issue.

**Comment by JC5** [comment]
The fact that the issue is closed doesn't mean I stopped thinking about it :)

**Comment by JC5** [comment]
I'm not sure if GitHub alerts you but please check out the commits above my reply on GitHub :)

**Comment by nxxxse** [comment]
Hey @JC5 

Thanks very much for considering and already changing :smiley:  I am not a lawyer and I was not sure about license compatibility and the need to ask contributors for their approval to this license change but with `GPL-3.0-or-later` to `AGPL-3.0-or-later` this seems not to be the case. The licenses are very similar 
(https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility) and my understanding is that you can just start releasing under the AGPL-3.0-or-later from now on. Old releases remain GPL-3.0-or-later obviously. But the longer you improve the AGPL project now, the more unfeasible it will get to take the  old GPL code and start a closed business out of it.

A note on the copyright note. You now use:

```
Copyright (c) 2019 thegrumpydictator@gmail.com
```

I think it is more common (also suggested here in https://www.gnu.org/licenses/gpl-howto.en.html, section The copyright notice), that you list the years or give a range of releases. Considering your releases (I looked at git tags), this would be appropriate:


```
Copyright (c) 2014-2019 thegrumpydictator@gmail.com
```

It also matches the majority of Firefly III more closely ;-)

Also, some more hints:

- [ ] Update the license identifier also in `composer.json`
- [ ] Include a note in the webinterface. Example from Nextcloud: "Developed by the Nextcloud community, the source code is licensed under the [AGPL](https://www.gnu.org/licenses/agpl-3.0.html)." This note is included in Nextcloud in the settings page.
    Maybe even be more precise than Nextcloud and use something like: "Developed by James Cole, the source code is licensed under the [AGPL-3.0-or-later](https://www.gnu.org/licenses/agpl-3.0.html)."

**Comment by JC5** [comment]
Thanks for the suggestions, I’ll pick it up!
