### ISSUE TITLE
Summary API output

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2609]
My users are running  4.8.1 and 4.8.0.3. I have questions regarding the output of summary API. From the [API docs](https://api-docs.firefly-iii.org/#/summary/getBasicSummary), I have an abundant of information returned,  however my users do not have `left-to-spend-in-CURRENCY_VALUE`.  This https://github.com/emansih/FireflyMobile/issues/58#issuecomment-531345205  and https://github.com/emansih/FireflyMobile/issues/64#issuecomment-530252462 . 

`An array of sums. It depends on the user what you can expect to get back, so please check out the documentation and try this out on the demo site.`

May I know the settings to change to get which keys are being returned?

**Comment by emansih** [comment]
I have to add that `left-to-spend-in-CURRENCY_VALUE` is returned in my personal instance

**Comment by JC5** [comment]
I see what you mean. I'm running into some deprecated code and I can't / won't give you an answer without doing some refactoring and getting this running properly again. 

The result of that key should be the total (available) amount you've set on the "budgets" page, minus the money already spent in budgets.

**Comment by JC5** [comment]
If the user has no available budget amount set, this key will not appear.

**Comment by JC5** [comment]
The "left-to-spend-XXX" array will appear whenever you have spent money in that period, like you see in the example below:

```
    "left-to-spend-in-GBP": {
        "key": "left-to-spend-in-GBP",
        "title": "Left to spend (£)",
        "monetary_value": -12.17,
        "currency_id": 3,
        "currency_code": "GBP",
        "currency_symbol": "£",
        "currency_decimal_places": 2,
        "value_parsed": "£-12.17",
        "local_icon": "money",
        "sub_title": "Left to spend per day: £0.00"
    },
```

If you have budgeted money in this period using the "available budget" option on the /budgets page or the API, you can make this amount positive:

```
    "left-to-spend-in-EUR": {
        "key": "left-to-spend-in-EUR",
        "title": "Left to spend (€)",
        "monetary_value": 1275.53,
        "currency_id": 1,
        "currency_code": "EUR",
        "currency_symbol": "€",
        "currency_decimal_places": 2,
        "value_parsed": "€1,275.53",
        "local_icon": "money",
        "sub_title": "Left to spend per day: €127.55"
    },
```

**Comment by JC5** [comment]
This latter method will only work when your "available budget" start and end date matches the request start and end exactly.

/api/v1/summary/basic?start=20190901&end=20190930

<img width="945" alt="Screenshot 2019-09-20 at 16 36 13" src="https://user-images.githubusercontent.com/5889984/65335471-c794c700-dbc4-11e9-856d-a88886d227ea.png">
