### ISSUE TITLE
Allow choice to import duplicate transactions

### ISSUE THREAD

**Issue by rafny** [firefly-iii/firefly-iii#2611]
**Description**
I know that by default you can't import previously imported transactions, but I recently purchased 2 plane tickets, and they were charged to my credit card individually. So I have 2 transactions with the same date, price, description and one of them were not imported due to it looking like a duplicate.

**Solution**
When importing, if the current CSV has a duplicate, FF can ask if the user would like to import the duplicate or ignore.

**What are alternatives?**
After the import, compare FF with the CSV, identify the missing transaction and added it manually.

**Comment by JC5** [comment]
Firefly III won't support that. I am working on a new import routine that will.

**Comment by JC5** [comment]
https://www.patreon.com/posts/30012174
