### ISSUE TITLE
Can't login after migrating to different server. Refused to send form data; Content Security Policy

### ISSUE THREAD

**Issue by calgara12** [firefly-iii/firefly-iii#2614]
I am running Firefly III version 4.8.1.1

**Description**
Hey,

I just migrated my firefly version to a different server. Now i can finally access it in the web interface, but i can't login.

My login request doesn't seem to be even sent to the server. The logs don't show anything. The console of my browser shows:

```
Refused to send form data to 'http://firefly.mydomain.com/login' because it violates the following Content Security Policy directive: "form-action 'self'".

Mixed Content: The page at 'https://firefly.mydomain.com/login' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://firefly.mydomain.com/login'. This endpoint should be made available over a secure connection.
```

Unfortunately i don't really know what to do with this message. It appears to have something to do with https. But im not sure how to fix this. I user traefik + letsencrypt for my certificate, not sure why the login targets a non https url.

I am running Ubuntu 16.04 with the newest firefly version installed.

I would really appreciate any suggestion on how to fix this.
Thanks!

**Extra info**
OS: Ubuntu 16.04
Browsers i tried: Brave, Chrome

**Comment by JC5** [comment]
Your reverse proxy is incorrectly configured.

**Comment by JC5** [comment]
Sorry, I pressed "Comment" to quickly. Check out old issues about traefik to make sure your configuration is correct.

**Comment by calgara12** [comment]
Thanks you pointed me in the right direction.

The problem was that TRUSTED_PROXIES was not set to **
