### ISSUE TITLE
syntax error, unexpected ')' after migration to 4.8.1.1

### ISSUE THREAD

**Issue by renaudpaquaynsi** [firefly-iii/firefly-iii#2615]
**Bug description**
I am running Firefly III version 4.8.0.3 and I upgraded to version 4.8.1.1 and my problem is:
Once I start the Firefly website, I get the following error message ;

syntax error, unexpected ')'

When I checked in the log file, I followed the error and compared the previous version with the latest one. There's one difference that can explain the error...

**Steps to reproduce**
No steps to reproduce...

**Expected behavior**
The website to work

**Extra info**
[ff3-apache2handler-2019-09-17.log](https://github.com/firefly-iii/firefly-iii/files/3623209/ff3-apache2handler-2019-09-17.log)

**Bonus points**
![bug](https://user-images.githubusercontent.com/40366996/65075591-866b9f80-d997-11e9-9bab-2e21f1538130.png)

**Comment by JC5** [comment]
That version of Firefly III requires PHP7.3

**Comment by renaudpaquaynsi** [comment]
Indeed, I was sloppy, sorry for inconvenience. It now works correctly.
