### ISSUE TITLE
Personal Access Token invalidated

### ISSUE THREAD

**Issue by Leosirth** [firefly-iii/firefly-iii#2616]
Hi,

I am running Firefly III version 4.8.1.1

**Description**
I have a Personal Access Token used for some API integration and have noticed that every time I restart the Firefly container the token is not working anymore getting a 302 http response and the following body:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=https://firefly.example.com/login" />

        <title>Redirecting to https://firefly.example.com/login</title>
    </head>
    <body>
        Redirecting to <a href="https://firefly.example.com/login">https://firefly.example.com/login</a>.
    </body>
</html>
```

Creating a new token makes everything working again.

Is this behavior intended?
I mean: is expected that the token gets invalidated on container restart/re-creation?

Thanks and regards,

**Comment by JC5** [comment]
I'll have to check. I'm not sure where Laravel stores them.

**Comment by JC5** [comment]
OK so the keys get deleted whenever the Docker instance restarts, due the the place they get stored. I've written a small routine that should save them and restore them whenever the instance restarts. That should solve the problem.

I've been testing it and it seems to work. In the next version Firefly III will keep the underlying OAuth keys and restore them, so your access tokens will keep working.
