### ISSUE TITLE
Quick category assignment in All transaction without category page

### ISSUE THREAD

**Issue by renaudpaquaynsi** [firefly-iii/firefly-iii#2617]
**Description**
It would be more convenient to have a way to assign quickly a category to a transaction that is missing one.

My way of using Firefly for making my budget is to assign a category to each transaction. Not any transaction should have an empty category.

In order to check that, I use the "All transactions without a category" page.
From that page, I would like to assign categories to my transactions

There's now a functionality that allows me to assign categories in bulk, which is great.
But unfortunately, in order to assign different categories to multiple transactions, I have to do it individually, and the actions for doing it are quite long making it exhaustive when you have a lot of transactions (like importing one month of transactions)

**Solution**
One special field in the grid that would allow to directly assign a category to this transaction.
That's pretty much the goal of the "All transactions without a category" right ?

**What are alternatives?**
Currently I need to click on one transaction to view the transaction detail, click on the edit button to enter edit, choose my category, click on save, then go back to the "All transactions without category page" by going to the menu or click twice on the back button.

All these steps must be done for each transactions I want to update

**Comment by JC5** [comment]
I'll think about something that could work.

**Comment by ante316** [comment]
Same use case here. I found firefly yesterday after I've been looking for something to self host.
I want to categorize everything to easily see and drill down to what my family have spent most money on during a month.

It requires so many clicks to even to bulk edits since it ends up being many many bulk edits on certain subsets each time.

Just being able to do it from the transactions-list in bulk without having to go to a new page etc would be so very appreciated!

**Comment by dlip** [comment]
Yes, this is the first thing i tried to do. Seems like an easy enhancement

**Comment by JC5** [comment]
You can use the mass-editor to do this. Use whichever page you like (the search, transactions without a category, etc) and select transactions:

<img width="1107" alt="Screenshot 2020-02-02 at 20 22 04" src="https://user-images.githubusercontent.com/5889984/73613826-58f35b80-45f1-11ea-97e2-4baed47ef2f6.png">

<img width="375" alt="Screenshot 2020-02-02 at 20 22 15" src="https://user-images.githubusercontent.com/5889984/73613828-5db80f80-45f1-11ea-814b-bbef71f369c9.png">

Then, change the categories to your liking:

<img width="1364" alt="Screenshot 2020-02-02 at 20 22 49" src="https://user-images.githubusercontent.com/5889984/73613833-6ad4fe80-45f1-11ea-8868-f82490535ce7.png">

A change to do this from the transactions list is something I want to do when I build a new layout from scratch, and that isn't starting soon I'm afraid.

**Comment by JC5** [comment]
This issue will be closed, now that the first alpha of 5.1.0 is out. Keep an eye out on the release page. If something comes up, please open a new issue. Thanks!
