### ISSUE TITLE
Pagination buttons also on page footer

### ISSUE THREAD

**Issue by renaudpaquaynsi** [firefly-iii/firefly-iii#2618]
**Description**

When I have a lot of transactions in a grid, (for example in the "All transactions without a category" page, I need to use the pagination buttons (1,2,3,4,...) to switch from one page to another page in order to go through all my transactions.
When I'm done scrolling the grid to the end of the current page, I would like to go to the next page.
Unfortunately, the pagination buttons are located at the top of the page. I have then to scroll up to the top of the page to be able to go to the next page by clicking on the next page in the pagination control.

**Solution**
Add also the pagination control in the bottom of the page (or the grid)

**What are alternatives?**
Hit CTRL+Home as shortcut

**Comment by JC5** [comment]
Good one, will do.

**Comment by JC5** [comment]
Fixed in the next release.
