### ISSUE TITLE
Add action to do basic string removal

### ISSUE THREAD

**Issue by somasis** [firefly-iii/firefly-iii#2619]
**Description**
My bank adds a lot of crap to the beginning of transaction names- things like "Merchant Payment - ", "Debit Card Purchase At ". It'd be nice for the sake of less redundancy if I could make a rule to get rid of these strings in all my transactions.

Matching the strings isn't a problem, since it's always at the beginning of the description, but I have no way to actually remove the string from the beginning. There's no need for regular expressions or anything. Just fixed string removal.

**Solution**
A "Remove from start of description" action.

**What are alternatives?**
None that I know of, other than some sort of offloading to a script. But having a rule would be really nice.

**Bonus points**
This software looks really interesting to me, and I'm really hoping I can get into it and make it a part of my life. Budgeting's always been a bit difficult for me to keep track of in my head. Thanks for your work, and I hope you have a good day!

**Comment by JC5** [comment]
I'll think about it but I'm inclined to keep the number of rules actions to a minimum. I'll get back to you.

**Comment by JC5** [comment]
Fixed.

**Comment by JC5** [comment]
Sorry, wrong issue.
