### ISSUE TITLE
Order by next expected match is wrong in french but ok in english

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2620]
In /bills, 
the order by "next expected match" is wrong in french but ok in english.

Maybe because of date format?
It looks like it's ordered by year, day, month. 

See screenshot below.

![image](https://user-images.githubusercontent.com/1318140/65125664-16d8cd00-d9f6-11e9-8379-417e53f0bd7a.png)
![image](https://user-images.githubusercontent.com/1318140/65125720-2fe17e00-d9f6-11e9-977f-21ccd95008d9.png)

**Comment by JC5** [comment]
Yes, it means the date format hasn't been translated properly yet. [This string is the culprit](https://crowdin.com/translate/firefly-iii/141/en-fr#9450).

**Comment by jlauwers** [comment]
Edited on crowdin.

**Comment by jlauwers** [comment]
I see in other languages the format D MMM YYYY (italian, dutch,...)
Should it be the same for french? Or should it be D MMMM YYYY as I wrote in crowdin?
The month is fully written so as https://devhints.io/moment#formatting says it's MMMM right?

**Comment by JC5** [comment]
It should be the same format as "29 septembre 2019". Those two have to match. I think what you submitted is correct.

**Comment by jlauwers** [comment]
When is the data from devhints merged? Next release?
I'm not used not having the merge in a couple minutes lol (since I use develop ^^)

**Comment by JC5** [comment]
I have to pull from Crowdin and merge. You’ll see it when it happens :(
