### ISSUE TITLE
No translation in the new transaction form

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2621]
In /transactions/create/withdrawal;
Everything is in english but I see (old) translation in https://crowdin.com/translate/firefly-iii/all/en-fr#q=Add+another+split

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2540

**Comment by jlauwers** [comment]
ooops sorry :p

**Comment by JC5** [comment]
No worries :)
