### ISSUE TITLE
budget already spent between x and x

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2623]
In /budgets,

> Already spent between September 1, 2019 and September 1, 2019 

should be

> Already spent between September 1, 2019 and September 30, 2019

**Comment by JC5** [comment]
Nice find, I'll pick it up.

**Comment by jlauwers** [comment]
Is it normal that the total spent in /budget doesn't count the expenses without budget?

**Comment by JC5** [comment]
Yes :)

**Comment by JC5** [comment]
Fixed.
