### ISSUE TITLE
Set budget refresh load wrong page

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2624]
In /budget,

If you use the buttons to change the budget period and then update the total budget amount, you get redirected to /budget and not /budget/what_ever_period_was_selected

**Comment by JC5** [comment]
Thanks, I'll pick it up.

**Comment by JC5** [comment]
Sorry, this works for me. I'm going to assume this isn't part of a release yet.

**Comment by jlauwers** [comment]
Managed to do it on https://demo.firefly-iii.org.

https://demo.firefly-iii.org/budgets/2019-12-01/2019-12-31
--> set budget to 100
redirected to https://demo.firefly-iii.org/budgets/2019-12-01/2019-12-31 (normal)
--> set budget to 200
redirected to https://demo.firefly-iii.org/budgets

**Comment by JC5** [comment]
Second time around, nice. I'll pick it up.

**Comment by JC5** [comment]
Done.
