### ISSUE TITLE
revenue and expense

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2625]
in /accounts/revenue: current balance is negative
in /accounts/expense: current balance is positive

It should be the other way arround.

**Comment by JC5** [comment]
From the help texts:

> There's something weird with expense accounts. Even though you pay into expense accounts, they tend to have a positive balance. Likewise, revenue accounts have a negative balance. At first glance this should be reversed. But remember that when you pay McDonalds, they earn money. Likewise, when your employer pays you, they lose money. For you personally it's the exact opposite but this list is from their perspective. A store makes money off you, an employer loses money to you.

^^

**Comment by jlauwers** [comment]
Dang... what's worst it that I knew that...
