### ISSUE TITLE
Budget values displayed with precision in excess of digits in currency

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2626]
I am running Firefly III version 4.8.1.1

The budget values are displayed with trailing zeroes in excess of the digits defined in the currency (USD in my case). 

![2019-09-18_112301](https://user-images.githubusercontent.com/39804831/65174948-bef69200-da06-11e9-89bd-48fa95362ea5.png)

**Comment by JC5** [comment]
Thanks, I’ll check it out.

**Comment by JC5** [comment]
This will be fixed in the next release.
