### ISSUE TITLE
Initialize the database not working

### ISSUE THREAD

**Issue by natrius** [firefly-iii/firefly-iii#2628]
So, finally i want to try it but i can't install it properly, seems like i'm doing something wrong.

I am running Firefly III version 4.8.1.1

**Description**

`php artisan migrate:refresh --seed`

`In StreamHandler.php line 108: The stream or file "/var/www/firefly-iii/storage/logs/ff3-cli-2019-09-19.log" could not be opened: failed to open stream: Permission denied`

`sudo php artisan migrate:refresh --seed`

```In Connection.php line 664:                                                                                                                          could not find driver (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE')```

**Extra info**
 

If you need mor info, just tell me.

**Comment by lguima** [comment]
> In StreamHandler.php line 108: The stream or file "/var/www/firefly-iii/storage/logs/ff3-cli-2019-09-19.log" could not be opened: failed to open stream: Permission denied

It seems the [missing permission](https://firefly-iii.readthedocs.io/en/latest/installation/server.html#main-command) for `storage` folder.

**Comment by JC5** [comment]
Yes, that's probably the cause.

**Comment by natrius** [comment]
1. `cd /var/www/`
2. `composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.8.1.1`
3. `sudo chown -R www-data:www-data firefly-iii` Without any output what usally means "ok"
4. `sudo chmod -R 775 firefly-iii/storage` Without any output what usally means "ok"
5. `cd firefly-iii`
6. `php artisan migrate:refresh --seed` results in `In StreamHandler.php line 108: The stream or file "/var/www/firefly-iii/storage/logs/ff3-cli-2019-09-20.log" could not be opened: failed to open stream: Permission denied`
7. `sudo php artisan migrate:refresh --seed` results in `In Connection.php line 664: could not find driver (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE')`

I did not even try the rest. 
`php artisan firefly-iii:upgrade-database`
`php artisan passport:install`

Sooo, where is my error? :/

**Comment by JC5** [comment]
Try `sudo -u www-data php artisan migrate:refresh --seed`

**Comment by natrius** [comment]
Results `In StreamHandler.php line 108: The stream or file "/var/www/firefly-iii/storage/logs/ff3-cli-2019-09-20.log" could not be opened: failed to open stream: Permission denied`

I don't know, it seems i'm missing something crucial here :/

**Comment by JC5** [comment]
If the file exists already, make sure you delete it.

**Comment by natrius** [comment]
Okay, 2 files were present, i deleted both and then did `sudo -u www-data php artisan migrate:refresh --seed` again. The result is now `In Connection.php line 664: could not find driver (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE')` 

I created a database and i put the user and the password in the `.env` file. The `fireflyiii` users exists and has got all the privileges in mysql. Double-checked.

**Comment by JC5** [comment]
Glad to help :)

Let's see, it seems that MySQL support in your PHP installation is limited or missing (assuming you use MySQL). Have you installed `php7.3-mysql`?

**Comment by natrius** [comment]
It was not installed actually (guess i had an older version). I installed it now, restarted my device and i'm getting the same error. I'm using MariaDB. What i did not copy until now are the following 2 errors (sorry, did not thought about it).

`In PDOConnection.php line 31: could not find driver`

and 

`In PDOConnection.php line 27: could not find driver`

**Comment by JC5** [comment]
It's the same error as before.

`Connection.php line 664: could not find driver (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE')`

**Comment by natrius** [comment]
Not quite sure if that was a question? If so, yes, it was the same error.

**Comment by JC5** [comment]
Your PHP installation is incapable of talking to MariaDB. I hoped installing the package would work. But that’s the root cause. Maybe google has more tips?

**Comment by natrius** [comment]
It seems i completely missed i had to change DB_CONNECTION and probably DB_PORT. You may should add MariaDB as well? I found some ports. Probably there is something wrong as well?

```
# Database credentials. Make sure the database exists. I recommend a dedicated user for Firefly III
# For other database types, please see the FAQ: http://firefly-iii.readthedocs.io/en/latest/support/faq.html
#original DB_CONNECTION=pgsql
DB_CONNECTION=mysql
DB_HOST=firefly_iii_db
#original DB_PORT=5432
DB_PORT=3306
DB_DATABASE=<database_name>
DB_USERNAME=<databank_username>
DB_PASSWORD=<password>
```

**Comment by natrius** [comment]
Okay, changed the following, now it seems working. Reading everything helps. 

```
#original DB_CONNECTION=pgsql
DB_CONNECTION=mysql
#original DB_HOST=firefly_iii_db
DB_HOST=localhost
DB_PORT=3306
```
