### ISSUE TITLE
Add option to create a custom dashboard and charts

### ISSUE THREAD

**Issue by baruchiro** [firefly-iii/firefly-iii#2631]
From #2630 

**Description**
Add option to create a custom dashboard and charts.

**Solution**
I'm new, and I don't know how the system works, but the properties of the graph are 2 fields: the x-axis column and the y-axis column.
So maybe you can save it to the database, and load that graph.

**What are alternatives?**
Nowadays, when you get into the software you get a view of your accounts, but the permanent look may not be right for you, and you want to keep track of other things.

**Comment by JC5** [comment]
Sorry, but like I said, the dashboard is static. I'm not going to add the ability to customize it in the near future.

**Comment by baruchiro** [comment]
But if the design is not complicated, it might be possible to set it up
here, in case one of the contributors (me?) Wants to develop it.

**Comment by JC5** [comment]
That's not really the point. The goal of developing Firefly III isn't to add more features. I prefer sensible defaults over options only power users will use.
