### ISSUE TITLE
Budgets are not sortered alphabetically in the transaction form

### ISSUE THREAD

**Issue by versvs** [firefly-iii/firefly-iii#2633]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

When trying to add a new transaction, the Budget select element shows an non-alphabetically sortered list of budgets, whereas in 4.7.* it has always shown them in alphabetic order (what made it really easier to spot the one you were looking for).

**Steps to reproduce**

Click in the New transaction, go to the Budget field and open it to see that the elements are not in alphabetical order.

**Expected behavior**

An alphabetically sortered list of budgets is shown instead.

**Extra info**

In 4.7 it worked with alphabetical order and it was better from a UI/UX point of view.

**Bonus points**

Reproduced in the Demo site:

![imagen](https://user-images.githubusercontent.com/11803/65362367-64785400-dc07-11e9-925c-8fdca230e729.png)

**Comment by JC5** [comment]
Nice find. I've fixed it so they'll follow the order as defined on the /budgets page.
