### ISSUE TITLE
All transaction shows the same form and the filter isn't discriminating accounts per type of transaction

### ISSUE THREAD

**Issue by versvs** [firefly-iii/firefly-iii#2634]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

Whether you click the add withdrawal, add deposit or add transfer button, you land to the same form whose fields are not filtering out accounts not needed and is mixing them all during selection.

**Steps to reproduce**
1. Click "Add Withdrawal"
2. Try to search for an Asset account and see how the revenue accounts also appear among the filtered values. (Revenue account is not applicable for a Withdrawal.)
3. Try to search for Expense account and see how the filtered values show both expense and asset account. (Asset is not applicable for a Withdrawal.)

**Expected behavior**

The selection in type of transaction helps you get a form that's going to filter accounts using only the applicable type of accounts so that Withdrawal, Transfer, and Deposit all have a purpose and the UI helps the user get the value added without confussion.

This interface was clearer in 4.7, even if it seems to be faster now... the loss in clarity is large.

**Extra info**
Firefox 69 and the latest Chrome.

**Bonus points**
1st screenshot: source account for a withdrawal shows a revenue account (not applicable for this kind of transaction).

![source-account-shows-revenue-account](https://user-images.githubusercontent.com/11803/65362849-4d3a6600-dc09-11e9-9209-afdac3f6e5b6.png)

2nd screenshot: destination account for a withdrawal shows an asset account, not applicable for this kind of transaction.

![dest-account-shows-asset-account](https://user-images.githubusercontent.com/11803/65362847-4ca1cf80-dc09-11e9-9e54-9d588eadb7a1.png)

**Comment by JC5** [comment]
Yes, I'm aware of it. I built it like this on purpose. I'll see if I can add some extra filtering depending on what you want to do.

**Comment by versvs** [comment]
Thanks! The whole refactor to use the API and so on is in fact a nice work, and the form feels faster, but the fields feel confuse now :)

**Comment by JC5** [comment]
Yep, I know. I hope to make it clear that whatever you fill in, "it works", but that doesn't make it easier to use.
