### ISSUE TITLE
API: working with attachments (missing endpoints)

### ISSUE THREAD

**Issue by michael-v2vlc** [firefly-iii/firefly-iii#2636]
I am running Firefly III version 4.8.1.1 (should be latest at the moment).

**Description**
It's not clear to me, how to work with attachments using API.

There are /api/v1/attachments* endpoints that provide support for managing attachment objects themselves (and their data), but there are no endpoints for adding/removing attachment to/from transaction/bill/etc. (at least in OpenAPI schema). There are only endpoints for listing attachments of a particular transaction and bill.

I don't see any cards in roadmap nor opened issues regarding this - is this planned at all?

**Comment by JC5** [comment]
What's your question?

https://api-docs.firefly-iii.org/#/attachments/storeAttachment

https://api-docs.firefly-iii.org/#/attachments/uploadAttachment

**Comment by michael-v2vlc** [comment]
Apologies, I missed the model and model_id properties in the model. It works correctly (i.e. I can create attachment for transaction and upload/download data for it).

However, I'd like to provide you with some feedback (hopefully you won't get offended). I, personally, would expect endpoints in REST API for this particular scenarios to look like this:

GET /api/v1/transactions/{id}/attachments (returns all attachments for specified transaction)
POST /api/v1/transactions/{id}/attachments (creates new attachment for specified transaction)
GET /api/v1/transactions/{id}/attachments/{id} (returns specific attachment from specific transaction, if it does not exist, return 404)
POST /api/v1/transactions/{id}/attachments/{id}/upload (upload data for specific attachment, if does not exist, return 404)
GET /api/v1/transactions/{id}/attachments/{id}/download (download data for specific attachment, if does not exist, return 404)

I understand that this would create lots of endpoints, when it can be solved like you did (single set of endpoints), but it would be more intuitive (at least for some people).

One other option that comes to mind, is to keep only this endpoint:

POST /api/v1/transactions/{id}/attachments (creates new attachment for specified transaction)

and use currently present endpoints for managing attachment and data (i.e. /api/v1/attachments).

That way it wouldn't be necessary to use "magic" property "model".

**Comment by JC5** [comment]
Fair point, I'll see what I can do.
