### ISSUE TITLE
API: transfer transaction with piggy bank does produce any events

### ISSUE THREAD

**Issue by michael-v2vlc** [firefly-iii/firefly-iii#2637]
**Bug description**
I am running Firefly III version x.x.x, and my problem is:

When I create transfer transaction with piggy bank reference, API does not return any piggy bank events, as described by @JC5 here in #1931.

It is possible to retrieve piggy bank events from opposite side - i.e. from piggy bank side.

**Steps to reproduce**

1. Create piggy bank
2. Add transfer transaction to piggy bank's savings account + set piggy bank
3. Call endpoint /api/v1/transactions/{id}/piggy_bank_events with proper transaction ID

**Expected behavior**
Any sort of information about these "piggy bank events".

**Question**
Is this API endpoint even implemented? A quick look into TransactionController.php shows that it should be implemented, but honestly I have no idea:

https://github.com/firefly-iii/firefly-iii/blob/master/app/Api/V1/Controllers/TransactionController.php#L197

**Comment by JC5** [comment]
I'll check it out. The API endpoint is implemented.

**Comment by JC5** [comment]
I tested this, and it seems to work.

- Got the events from a new piggy bank. Surprisingly, zero hits.
- Made a transfer to the account the piggy bank is linked to using the form.
- Event shows up.

Keep in mind the correct URL ends with `/events`. Not `/piggy_bank_events`.

https://api-docs.firefly-iii.org/#/piggy_banks/listEventByPiggyBank

**Comment by michael-v2vlc** [comment]
The issue is with listing piggy bank events related to transaction, so it should be this endpoint:

https://api-docs.firefly-iii.org/#/transactions/listEventByTransaction

/api/v1/transactions/{id}/piggy_bank_events

As I said in the first comment, the endpoint you mention works fine.

You can test it on demo site (until it gets reset or deleted):

Transaction ID: 412 (Savings for camera)
Piggy bank ID: 1 (New camera)

https://demo.firefly-iii.org/api/v1/transactions/412/piggy_bank_events?page=1

Result is this:
```
{
  "data": []
}
```

while calling the endpoint for piggy bank returns this:

https://demo.firefly-iii.org/api/v1/piggy_banks/1/events?page=1

```
{
  "data": [
    {
      "type": "piggy_bank_events",
      "id": "3",
      "attributes": {
        "created_at": "2019-09-24T13:08:36+02:00",
        "updated_at": "2019-09-24T13:08:36+02:00",
        "amount": 265,
        "currency_id": 1,
        "currency_code": "EUR",
        "currency_symbol": "€",
        "currency_decimal_places": 2,
        "transaction_journal_id": 417,
        "transaction_group_id": 412
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "/piggy_bank_events/3"
        },
        "self": "https://demo.firefly-iii.org/api/v1/piggy_bank_events/3"
      }
    },
    {
      "type": "piggy_bank_events",
      "id": "1",
      "attributes": {
        "created_at": "2019-09-24T14:00:57+02:00",
        "updated_at": "2019-09-24T14:00:57+02:00",
        "amount": 123,
        "currency_id": 1,
        "currency_code": "EUR",
        "currency_symbol": "€",
        "currency_decimal_places": 2,
        "transaction_journal_id": 1,
        "transaction_group_id": 1
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "/piggy_bank_events/1"
        },
        "self": "https://demo.firefly-iii.org/api/v1/piggy_bank_events/1"
      }
    }
  ],
  "meta": {
    "pagination": {
      "total": 2,
      "count": 2,
      "per_page": 50,
      "current_page": 1,
      "total_pages": 1
    }
  },
  "links": {
    "self": "https://demo.firefly-iii.org/api/v1/piggy_banks/1/events?&page=1",
    "first": "https://demo.firefly-iii.org/api/v1/piggy_banks/1/events?&page=1",
    "last": "https://demo.firefly-iii.org/api/v1/piggy_banks/1/events?&page=1"
  }
}
```

**Comment by JC5** [comment]
Fixed.
