### ISSUE TITLE
Wrong resources paths with apache2 reverse proxy

### ISSUE THREAD

**Issue by Swalkyn** [firefly-iii/firefly-iii#2641]
Hi !

I am trying to install Firefly III on my server (Ubuntu 18.04, Apache/2.4.29). I am using version 4.8.0.3 (latest release that supports php7.2). There is another website being served by the machine, so I am using Apache's virtual hosts (which means there is a reverse proxy, if I am not mistaken). This other website is working as intended.

The issue I have is that css and javascript don't work when trying to log into my Firefly III instance. This is because resources files do not have the right href, but a local one.
![firefox-inspector](https://user-images.githubusercontent.com/20524908/65389236-2dfc1f80-dd54-11e9-8be6-1a951ec3c8c2.png)

I've read [issue #882](https://github.com/firefly-iii/firefly-iii/issues/882), which describes the same problem, and also linked issues. However, the proposed solution does not work for me.

A few of the relevant sections in config files:

_.env_
```
...
# APP_URL and TRUSTED_PROXIES are useful when using Docker and/or a reverse proxy.
APP_URL=https://my.domain.com
TRUSTED_PROXIES=**
...
```
_Apache virtual host config file_
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerAdmin admin@my.domain.com
        DocumentRoot /var/www/firefly-iii/public/
        ServerName my.domain.com

	ErrorLog /var/log/apache2/hosts/fireflyiii-error.log
        CustomLog /var/log/apache2/hosts/fireflyiii-access.log combined

	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLCertificateFile /etc/letsencrypt/live/...
	SSLCertificateKeyFile /etc/letsencrypt/live/...
</VirtualHost>
</IfModule>
```
Feel free to ask for anything I did not include. Any help is appreciated!

I have to say that this is the first time I try to make such a setup work. I already apologize, since there's a very high likelihood that me being incompetent is the source of the problem.

I'm looking forward to using Firefly III. The demo was really convincing!

**Comment by Swalkyn** [comment]
After investigating the logs, it effectively turns out that my browser is requesting /index.php/v1/...
_access.log_
```
...
my ip - - [24/Sep/2019:18:49:20 +0000] "GET /index.php/v1/lib/fa/css/font-awesome.min.css?v=4.8.0.3 HTTP/1.1" 404 3931 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
my ip- - [24/Sep/2019:18:49:20 +0000] "GET /index.php/v1/css/firefly.css?v=4.8.0.3 HTTP/1.1" 404 3931 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
my ip - - [24/Sep/2019:18:49:20 +0000] "GET /index.php/v1/css/daterangepicker.css?v=4.8.0.3 HTTP/1.1" 404 3931 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
my ip - - [24/Sep/2019:18:49:20 +0000] "GET /index.php/v1/js/app.js?v=4.8.0.3 HTTP/1.1" 404 3931 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
...
```
And obviously the server returns a 404. I don't know what is not correctly configured causing this to happen. Firefly III's _.env_ seems good. Apache then?

**Comment by JC5** [comment]
Is the rewrite module enabled?

**Comment by Swalkyn** [comment]
Yes it is. I have not added any rewrite rule. Should I ?

**Comment by JC5** [comment]
No, the .htaccess file already has them.

**Comment by Swalkyn** [comment]
Ok so I made sure I have no custom rewrite rules in any of the .htaccess files, apache2.conf and firefly vhost config files. At the moment, two different scenarios occur:
1. if I try accessing with 'my.domain.com' -> I get a 404
2. if I try accessing with 'my.domain.com/index.php' -> I get the welcome page, but only the html loads (see the screenshot in my first comment)

I believe that the first method should be the one working, since Apache is supposed to serve index.php even when its not specified in the url. I have the dir module enabled, and this my dir.conf
```
<IfModule mod_dir.c>
        DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm
</IfModule>
```
Any idea why this does not work?

**Comment by JC5** [comment]
No I'm sorry, I really don't know enough about Apache.

**Comment by Swalkyn** [comment]
I got it, I had `AllowOverride` set to None for firefly's directory, which meant Apache was not using .htaccess. It should be fixed now, and even if it's not, I don't want to bother you with something that is clearly not Firefly III's fault. Thank you for your time, very much appreciated !
