### ISSUE TITLE
[ING] Remove name from description

### ISSUE THREAD

**Issue by rubenverhoef** [firefly-iii/firefly-iii#2642]
**Description**
I would like to have the `Naam: xxxx` to be removed from the description field for a ING  `csv` import. This because this data is already at column `2`.
I see the `IBAN:` is already removed which is nice because that is also already in a column.
With the `Naam:` being removed it should map my duplicates from different accounts, see #1863

So my second question is, does the import check for duplicates before or after the special ING "fix"?

**Comment by JC5** [comment]
That may happen if somebody can write it, in the new CSV import routine for Firefly III. You can read about this on [Patreon](https://www.patreon.com/posts/30012174). To answer your question: Firefly III will check for duplicates after the ING fix.

**Comment by rubenverhoef** [comment]
Okay, when the new importer is there i have a look to add this. 

I looked at this code and it should be removed:
https://github.com/firefly-iii/firefly-iii/blob/d550a626e90e6307603d12fa36241fbc98bf0be3/app/Import/Specifics/IngDescription.php#L74-L86
I looked further and the problem is that some of my entries are not having the `Omschrijving`:
https://github.com/firefly-iii/firefly-iii/blob/d550a626e90e6307603d12fa36241fbc98bf0be3/app/Import/Specifics/IngDescription.php#L118

So when the entry has no `Omschrijving` the `Naam:` entry will not be removed.

I will look if i can fix this issue and create a pull request, or do you have a quick fix for this?

**Comment by JC5** [comment]
If you do, please do so on this file:

https://github.com/JC5/firefly-iii-csv-importer/blob/master/app/Services/CSV/Specifics/IngDescription.php

And send me some example lines over mail so I can check if it works as expected.

**Comment by rubenverhoef** [comment]
I'm working on it and it goes fine, few questions about the current method:

what does this function do?:
https://github.com/firefly-iii/firefly-iii/blob/d550a626e90e6307603d12fa36241fbc98bf0be3/app/Import/Specifics/IngDescription.php#L124-L130
Do you have an example and i think it is not working for every situation because my savings acount is named `Bonusrenterekening`

What i now have:
* Remove `Naam` entry from description (doesn't matter what is behind or before it)
* Remove `Omschrijving:` but not the value of it. So only the text `Omschrijving`.
* copy `Valutadatum` to own column so we can use it as a FireFly iii parameter and it makes the "omschrijving" much cleaner.

What i will make:
* copy the value `Datum/tijd` from description to date entry so when the time is present we can use it in FireFly iii.

What do you think?

**Comment by JC5** [comment]
If @tomwerf is still active on GitHub he can answer that question maybe.

**Comment by tomwerf** [comment]
I'm still alive!

I didn't write the `copyDescriptionToOpposite()` function.
It is added for issue https://github.com/firefly-iii/firefly-iii/issues/1015
It looks like the function is not working correct.

The value in the `Mededelingen` column for Oranje rekeningen has the format:

-   'Naar Oranje rekening {nr} {description} Valutadatum: {date}'

So it is copying more than only the {nr} to the "tegenrekening"

I have also an Groei groter rekening. This one has the format:

-   'Naar Groei groter rekening {nr} {description} Valutadatum: {date}'

I guess the Bonusrenterekening has the same format?

Maybe you can extract only the {nr} from the description and put it in `row[3]`
Than you can catch all the saving account types.

The 4 proposals looks good to me!

**Comment by rubenverhoef** [comment]
I'm working on it slowly (when i have time) see : https://github.com/rubenverhoef/firefly-iii/commits/CSV-ING

I have one other question: In which format has the `Valutadatum` needs to be. I want to import it as `Datum Verwerking` or any other date entry i can set it to when importing the `CSV`. But when importing the date is not displayed on the transaction entry. Also when i edit the transaction i cannot enter a `Verwerkingsdatum` myself. So what are these entries do in the import process?
