### ISSUE TITLE
Tutorial for setting up HTTPS with Docker on Windows?

### ISSUE THREAD

**Issue by lotsoffood** [firefly-iii/firefly-iii#2646]
I have Firefly III running via the official Docker container on a Windows 10 box. I'd like to utilize the YNAB import function, but need Firefly III running under a reverse proxy for `https` support.

Does anyone have a good tutorial for setting this up on Windows 10 with Docker?

**Comment by Joshhua5** [comment]
I had success using Caddy as a reverse proxy and so have others.

https://github.com/firefly-iii/firefly-iii/issues/1632

**Comment by optimistic5** [comment]
You can try jwilder
https://gist.github.com/optimistic5/ca5a4a8593dcdb7360f712d37a0cc657
