### ISSUE TITLE
Category without transactions fails to show

### ISSUE THREAD

**Issue by ilvez** [firefly-iii/firefly-iii#2647]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

When you have empty category (create a new one or remove specific category from all transactions), `/categories/show/[category_id]` category fails to show.

**Steps to reproduce**
1. Create new category.
2. Click on category name in category list to view category.
3. Get error:
```
SQLSTATE[22008]: Datetime field overflow: 7 ERROR: date/time field value out of range: "0000-01-01 00:00:00" (SQL: select "transaction_groups"."id" as "transaction_group_id", "transaction_groups"."user_id" as "user_id", "transaction_groups"."created_at" as "created_at", "transaction_groups"."updated_at" as "updated_at", "transaction_groups"."title" as "transaction_group_title", "transaction_journals"."id" as "transaction_journal_id", "transaction_journals"."transaction_type_id", "transaction_journals"."description", "transaction_journals"."date", "transaction_journals"."order", "transaction_types"."type" as "transaction_type_type", "source"."id" as "source_transaction_id", "source"."account_id" as "source_account_id", "source"."reconciled", "source"."amount" as "amount", "source"."transaction_currency_id" as "currency_id", "currency"."code" as "currency_code", "currency"."name" as "currency_name", "currency"."symbol" as "currency_symbol", "currency"."decimal_places" as "currency_decimal_places", "source"."foreign_amount" as "foreign_amount", "source"."foreign_currency_id" as "foreign_currency_id", "foreign_currency"."code" as "foreign_currency_code", "foreign_currency"."name" as "foreign_currency_name", "foreign_currency"."symbol" as "foreign_currency_symbol", "foreign_currency"."decimal_places" as "foreign_currency_decimal_places", "destination"."account_id" as "destination_account_id", "categories"."id" as "category_id", "categories"."name" as "category_name" from "transaction_journals" left join "transaction_groups" on "transaction_journals"."transaction_group_id" = "transaction_groups"."id" left join "transactions" as "source" on "source"."transaction_journal_id" = "transaction_journals"."id" and "source"."amount" < 0 left join "transactions" as "destination" on "destination"."transaction_journal_id" = "transaction_journals"."id" and "destination"."amount" > 0 left join "transaction_types" on "transaction_types"."id" = "transaction_journals"."transaction_type_id" left join "transaction_currencies" as "currency" on "currency"."id" = "source"."transaction_currency_id" left join "transaction_currencies" as "foreign_currency" on "foreign_currency"."id" = "source"."foreign_currency_id" left join "category_transaction_journal" on "category_transaction_journal"."transaction_journal_id" = "transaction_journals"."id" left join "categories" on "category_transaction_journal"."category_id" = "categories"."id" where "transaction_journals"."user_id" = 1 and "transaction_journals"."user_id" is not null and "transaction_groups"."deleted_at" is null and "transaction_journals"."deleted_at" is null and "source"."deleted_at" is null and "destination"."deleted_at" is null and "categories"."id" = 22 and "transaction_journals"."date" >= 0000-01-01 00:00:00 and "transaction_journals"."date" <= 2019-09-30 23:59:59 and "transaction_types"."type" in (Deposit) and "transaction_journals"."deleted_at" is null order by "transaction_journals"."date" desc, "transaction_journals"."order" asc, "transaction_journals"."id" desc, "transaction_journals"."description" desc, "source"."amount" desc)
```

**Extra info**
I could reproduce it every time. Edit view is rendered correctly.

**Comment by JC5** [comment]
Could you share the table from the /debug page?

**Comment by ilvez** [comment]
Debug information generated at 2019-09-23 09:36:17 Europe/Tallinn for Firefly III version **4.8.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9-1 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2019-01-21 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | pgsql |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, intl, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Comment by JC5** [comment]
I need a bit more info I'm afraid. Could you enable debug mode and show me the stacktrace?

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on Github, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by ilvez** [comment]
I cleared up all other logs and just refreshed the `/categories/show/22` that reproduces the issue. Logs: [ff3-fpm-fcgi-2019-09-23.log](https://github.com/firefly-iii/firefly-iii/files/3643555/ff3-fpm-fcgi-2019-09-23.log)

**Comment by JC5** [comment]
I pushed a fix. If possible, can you apply it manually to see if it works?

**Comment by ilvez** [comment]
Yep. Seems working. Doesn't crash and output makes sense as well.

**Comment by ilvez** [comment]
Next time, I'll fix it myself. Haven't done PHP, but fix makes sense.
