### ISSUE TITLE
Installation problem  UnexpectedValueException

### ISSUE THREAD

**Issue by a491765** [firefly-iii/firefly-iii#2648]
I am running Firefly III version 4.8.1.1

**Description*
I have an error occured after installing firefly.
When i go to localhost/firefly-iii i have this page 

The stream or file "/var/www/html/firefly-iii/storage/logs/ff3-apache2handler-2019-09-23.log" could not be opened: failed to open stream: Permission denied
in StreamHandler.php line 108

Everything goes well during the installation, i change the .env to
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD= "my database user psswd"

No problem at all until charging localhost/firefly-iii
Can you please help me to deal with this error ?
I give you the log file
[ff3-cli-2019-09-23.log](https://github.com/firefly-iii/firefly-iii/files/3641913/ff3-cli-2019-09-23.log)

**Extra info**
Debian Buster / PHP 7.3.9 / MariaDB mysql

**Comment by a491765** [comment]
I try to reinstall it from the ground... 
Now i have this page...
What damn is that ?

. */ /** * Laravel - A PHP Framework For Web Artisans * * @package Laravel * @author Taylor Otwell */ define('LARAVEL_START', microtime(true)); /* |-------------------------------------------------------------------------- | Register The Auto Loader |-------------------------------------------------------------------------- | | Composer provides a convenient, automatically generated class loader for | our application. We just need to utilize it! We'll simply require it | into the script here so that we don't have to worry about manual | loading any of our classes later on. It feels great to relax. | */ require __DIR__ . '/../vendor/autoload.php'; /* |-------------------------------------------------------------------------- | Turn On The Lights |-------------------------------------------------------------------------- | | We need to illuminate PHP development, so let us turn on the lights. | This bootstraps the framework and gets it ready for use, then it | will load up this application so that we can run it and send | the responses back to the browser and delight our users. | */ /** @noinspection UsingInclusionOnceReturnValueInspection */ $app = require_once __DIR__ . '/../bootstrap/app.php'; /* |-------------------------------------------------------------------------- | Run The Application |-------------------------------------------------------------------------- | | Once we have the application, we can handle the incoming request | through the kernel, and send the associated response back to | the client's browser allowing them to enjoy the creative | and wonderful application we have prepared for them. | */ $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class); $response = $kernel->handle( $request = Illuminate\Http\Request::capture() ); $response->send(); $kernel->terminate($request, $response);

**Comment by JC5** [comment]
Easy on the language there please.

1. `failed to open stream: Permission denied` means that the access rights to the directory where you installed Firefly III are bad. Check out issue #2628
2. This means you haven't enabled the PHP extension in Apache or whatever you use and your browser shows you the raw code.

**Comment by a491765** [comment]
Well thanks you for your response.

1. I tried to give permission like in issue #2628 but this make /localhost/firefly-iii no more accessible. I will go back to this error when repair my apache.

2. I don't understand why now my php extension isn't enable...

**Comment by a491765** [comment]
Hello,
1/ So i correct my LAMP problem.
2/ I follow your link and give the rights
sudo chown -R www-data:www-data firefly-iii*
chmod -R 775 /var/www/html/firefly-iii/storage

Now i have that :

404 Not Found
The requested URL /firefly-iii/public/login was not found on this server.
Apache/2.4.38 (Debian) Server at localhost Port 80

**Comment by JC5** [comment]
Make sure mod_rewrite is enabled.

**Comment by a491765** [comment]
***@***:/var/www/html/firefly-iii# sudo a2enmod rewrite
Module rewrite already enabled

**Comment by a491765** [comment]
Ok i solve my accessibility problem by adding

# your firefly-iii public directory
	<Directory /var/www/firefly-iii/public>
        	Options Indexes FollowSymLinks
        	AllowOverride All
        	Require all granted
	</Directory>

To the apache2.conf as suggested in a post.
I had access to the login page, created a user, password and e-mail.
Now i have this page :


Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:
file_put_contents(/var/www/html/firefly-iii/storage/framework/cache/data/82/84/8284cdad9236abeb1a9f1ee6f1842389f7120efd): failed to open stream: No such file or directory

Any idea ?
Thanks.

**Comment by a491765** [comment]
ok solved by done again 
sudo chown -R www-data:www-data /var/www/html/firefly-iii
