### ISSUE TITLE
UI :: Titles in reports page overwrite each other

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2649]
**Bug description**
I am running Firefly III version 4.8.1.1.
I have 14' screen.
In Russian language (and probably in other languages) in reports page, name of title overwrite each other.
![image](https://user-images.githubusercontent.com/25054050/65449996-d8537000-de44-11e9-83d1-827c20a95719.png)

Actually this titles are duplicate each other, and I don't really understand why it is.
And also in English it is almost overwrite each other too.
![image](https://user-images.githubusercontent.com/25054050/65450053-f91bc580-de44-11e9-9f27-4ac6251b1334.png)

My proposal:
Display the title only one time.

**Comment by JC5** [comment]
Yeah it happens with really long titles. I'm not too concerned.
