### ISSUE TITLE
Reset form after submission doesn't clear source account field

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2651]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:
Checkbox **Reset form after submission** doesn't clear **Source account** field

**Steps to reproduce**
1. Create new withdrawal
Check the boxes **After storing, return here to create another one** and **Reset form after submission** 
Click **Submit**.
![image](https://user-images.githubusercontent.com/25054050/65450665-56644680-de46-11e9-8696-a485f1af5bcd.png)

2. You can see that **Source account** is not empty.
![image](https://user-images.githubusercontent.com/25054050/65450721-7431ab80-de46-11e9-8f56-6f8d200a28e0.png)

It can look like a feature (the last account is chosen).
But if you submit this withdrawal it will fail:
![image](https://user-images.githubusercontent.com/25054050/65450765-8f9cb680-de46-11e9-9611-b32e54672071.png)

**Expected behavior**
Source account field should be clean after submit withdrawal with **Reset form after submission** checkbox.

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by pc-zookeeper** [comment]
I'm seeing that the destination account also does not clear on version 4.8.1.4.

**Comment by JC5** [comment]
If that was fixed the issue would be closed.

**Comment by pc-zookeeper** [comment]
Understood.  OP stated this was an issue with the Source Account field in v4.8.1.1 and per the screen captures provided, the Destination Account field did not contain this issue.  I'm simply adding that a similar issue now also exists with the Destination Account in v4.8.1.4.

**Comment by JC5** [comment]
Yes, unfortunately both fields suffer from this issue. I hope to get it fixed asap :)

**Comment by JC5** [comment]
Thanks for your patience all. This should be fixed in the next release.
