### ISSUE TITLE
How to get correct spent amount in chart operations data?

### ISSUE THREAD

**Issue by shjryan** [firefly-iii/firefly-iii#2652]
I am running Firefly III version 4.8.1.1

**Description**

I just tried installing the dockerized application on Windows 10 Pro, and I am having issues understanding the first chart that shows up in the *Default financial report*.  Everything else on the page looks correct including the Income vs. expenses table, but the chart is displaying a wrong spent amount by ~17 times more.  

**Extra info**
 
Windows 10 Pro
Chrome & Firefox
Debug information generated at 2019-09-23 18:57:43 America/Vancouver for Firefly III version **4.8.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2019-09-10 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

Tried to replicate on the demo site, but as the demo site already contains transactions, and the chart is displaying correctly, it's a bit hard for me to replicate it on the demo site...

**Comment by JC5** [comment]
I can't replicate this issue. Do you include all your asset accounts in the view, or just a selection? Can you trigger this issue with just a test account and a limited set of transactions?

**Comment by shjryan** [comment]
I included all my asset accounts (4) in the view, and I accessed the page via clicking the Net Wealth CTA button in the Dashboard view. 

When I get back to my desktop tonight, I will test to see with account selection combinations, and report back. 

Range did not matter when I tested it with the reports -> custom range with all accounts.

**Comment by JC5** [comment]
Thanks. The more details I have the better.

**Comment by shjryan** [comment]
1. Set an opening balance of account to any amount on any date.
2. Run reports, then the same amount will be counted towards **Spent (currency symbol)** for the month opening balance was entered.

I can live with this by setting the opening balance's date eons ago.  However, the opening balance amount shouldn't be counted towards spent figure, should it?

**Comment by JC5** [comment]
It's a transaction, so it counts. Does it solve the issue you have with the charts?

**Comment by shjryan** [comment]
How does transaction that adds balance to an account count as spent?  Do you have a link about this algorithm so that I can understand the financial philosophy behind it? Thanks!

**Comment by JC5** [comment]
Anything counts. It's pretty basic math. Either you make sure that an accounts starts at zero, or you create the opening balance a month before. There's not much behind it.

**Comment by shjryan** [comment]
I am assuming that this spent figure is a “cash” spent figure then. Am I on the right track?

**Comment by JC5** [comment]
I think so, yes. Not sure what you mean with a "cash" spent figure.
