### ISSUE TITLE
Tag and breadcrumbs overlapping

### ISSUE THREAD

**Issue by tribly** [firefly-iii/firefly-iii#2653]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

When you're looking at e.g. https://domain.com/tags/show/2/all the tag name and breadcrumbs overlap on smaller screens.
![eCz3FKUn3](https://user-images.githubusercontent.com/3883400/65506689-72123000-decc-11e9-8967-7e778ecfb1b3.png)

**Steps to reproduce**
Click on a tag, then on `Show all transactions without grouping them by date. `

**Expected behavior**
Should not overlap like in the normal view.

**Extra info**
OS: Arch Linux
Browser: Firefox 69.0.1

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2649
