### ISSUE TITLE
Docker: Dockerfile for base image for jc5x/firefly-iii nowhere to be found

### ISSUE THREAD

**Issue by michael-v2vlc** [firefly-iii/firefly-iii#2655]
I can't seem to find Dockerfile for image jc5x/firefly-iii-base-image anywhere. It's not in the repository and Docker Hub does not list source repository for this image (unlike jc5x/firefly-iii).

Build script does not build this image:

https://github.com/firefly-iii/firefly-iii/blob/master/.deploy/docker/build-amd64.sh

Is this image built in some other way? If so, I believe it would be great for the project to provide some transparency into what this image contains. Otherwise it's just one big (173.37 MB) black box blob.

Dockerfile for arm64 does give some insight into how this base image might be built, but it's just a speculation at this point.

https://github.com/firefly-iii/firefly-iii/blob/master/Dockerfile.arm64

**Comment by JC5** [comment]
https://github.com/JC5/firefly-iii-base-image

**Comment by michael-v2vlc** [comment]
Apologies, I have not noticed this.

Could it be possible to at least update page on Docker Hub to include link to this repository (just like the main image jc5x/firefly-iii). Thanks a lot?

**Comment by JC5** [comment]
Thanks. I've done so. The Dockerfiles will include a comment linking to the GitHub repository as well.
