### ISSUE TITLE
API: /api/v1/attachments/{id} returns 404 for OPTIONS (Swagger)

### ISSUE THREAD

**Issue by michael-v2vlc** [firefly-iii/firefly-iii#2656]
As the title says, it's not possible to call endpoint /api/v1/attachments/{id} from Swagger (or browser app), because OPTIONS returns 404.

Calling this endpoint directly returns expected data.

Demo site:

https://demo.firefly-iii.org/api/v1/attachment/3

**Comment by JC5** [comment]
I'll check it out. I'm not even sure any API endpoint supports OPTIONS.

**Comment by JC5** [comment]
I'm not getting a 404 on that URL. Keep in mind that the URL you just posted is bad anyway.

This is the correct end point URL: https://demo.firefly-iii.org/api/v1/attachments/3

**Comment by michael-v2vlc** [comment]
Apologies, you're right. However then the Swagger schema is wrong:

![firefly-iii-api-inconsistency](https://user-images.githubusercontent.com/49870784/65766917-df67d000-e11b-11e9-8585-fb7e6e499a9b.png)

**Comment by JC5** [comment]
Ah that's a dumb mistake on my part. Apologies. Consider it fixed.
