### ISSUE TITLE
Recurring transactions wrong

### ISSUE THREAD

**Issue by woolmonkey** [firefly-iii/firefly-iii#2658]
So I have had recurring transactions set up for awhile and now the dates are wrong.  I have one that should have gone off on Monday but it is planning to go off on the 25th.  The odd thing is when you look at the calendar for when they should go off that is correct. Just the expected transfers is wrong and it didn't actually occur when it was supposed to show it is wrong.

**Comment by JC5** [comment]
I’m not sure I get what the problem is. 

- it should have fired but it didn’t. 
- it shows the wrong date somewhere

Could you share

- a screenshot with all of the details of the recurring transaction. 
- a screenshot of any wrongly calculated dates and the date you took the screenshot

**Comment by woolmonkey** [comment]
Both it should have fired on Monday but it fired on Wednesday.  And it shows wrong dates it fired on the dates that next due show.  This was running fine on previous versions.
![image](https://user-images.githubusercontent.com/2517303/65600316-25c30080-df5d-11e9-9c60-1e0217cc2c4d.png)
![image](https://user-images.githubusercontent.com/2517303/65600461-602c9d80-df5d-11e9-9c9d-1b26e3eeb4a0.png)
![image](https://user-images.githubusercontent.com/2517303/65600370-3d9a8480-df5d-11e9-94b8-3491040e2390.png)
These are for the last two.  They are both daily transactions that skip 13 days so they fire once every two weeks.  The are fireing on the next due date which is wrong and doesn't even show up on the show expected results page.

**Comment by JC5** [comment]
Could you share a screenshot of the entire recurring transaction please?

**Comment by woolmonkey** [comment]
I'm assuming the rules
![image](https://user-images.githubusercontent.com/2517303/65600821-1f815400-df5e-11e9-8a73-f22e366392cf.png)

**Comment by JC5** [comment]
Thanks, I'll see what I can find.

**Comment by JC5** [comment]
Btw what's wrong with using "every week on Tuesday" and then skipping a week?

**Comment by JC5** [comment]
Fixed.

**Comment by woolmonkey** [comment]
Nothing I think I set it up before that was an option.
