### ISSUE TITLE
Return of clone transaction action in Actions menu

### ISSUE THREAD

**Issue by aclex** [firefly-iii/firefly-iii#2659]
Now that transaction cloning is brightly returned in 4.8.1 thanks in #2549, I initially expected to use my lovely Clone item in Actions menu of the transaction string, but it suddenly disappeared :)

I saw in #2549 the new scenario for cloning, but, if it's ever possible, could you please bring those Actions menu item for cloning back? It was really handy and natural scenario for me, as I basically look at the list of already entered transactions to find, what I should enter or clone now (have to enter them manually from my bank account). I hope, it would be fine to have two usage scenarios for the same action.

**Comment by JC5** [comment]
Sorry, but the reason I removed it was because that route isn't viable anymore. Sorry.

**Comment by aclex** [comment]
@JC5 ah, OK, I see. Just thought it was just forgotten or removed due to lack of popularity of this use case. No problem, will get used to the new scenario for this. Thank you very much for your work!
