### ISSUE TITLE
Transaction message / piggy bank amount / account search

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#2660]
I am running Firefly III version 4.8.1.1, and my problem is:

I was used to use these 3 things in 4.7.X version that were working fine but they seem to be gone since 4.8.X release.

- When creating a new transaction if you tick the box "After storing, return here to create another one." the message appearing to tell you the transaction has been save is something like "Success! Transaction #17319 has been stored."
In previous releases it was showing the transaction description field. This is still the case in fact if you don't tick the box to return to the form... Would be nice to correct this :) (I'm used to visually check the transaction I entered is correctly stored)

- While creating a transfer transaction I select the piggy bank I want to use. In the selection I only see the names of the piggy banks I have. Previously we also had the remaining amount on each piggy listed between ( ). Would be nice to have it back too :)

- Last one the search field for the account. Previously it was super handy as you could enter some letters of each word (when is was a multiple word account name) and it was finding it super fast. Now if I use the same trick it does not find anything. Also moving in the proposed list with the arrows sometimes move my cursor to the beggining of the field (before my text) and search is going crazy (showing something related to a wildcard I suppose). Would be nice to fix the search as the previous was of working was perfect (don't know if it's due to a bug...)

**Steps to reproduce**
I think each case is self explanatory :)

Thanks a lot again for your super tool!

Side question: is it normal when I delete one transaction that was linked to a piggy bank, the piggy journal entry is not removed? Also I can't manually remove it...

**Comment by JC5** [comment]
Thanks for all the suggestions.

* I had some troubles collecting the title so I didn't bother. I'll pick it up.
* Good one, will do.
* It's a new library, the old one worked well but was otherwise crap. I'll see what I can do.
* The events remain (history). The money is still in the piggy bank, even when you delete the transaction.

**Comment by MacPaille** [comment]
As usual super fast feedback. Thanks!

**Comment by JC5** [comment]
* Fixed
* Fixed
* Fixed, although I can't do much about the mouse jump.

**Comment by MacPaille** [comment]
Super cool, will check once I use that release. Thanks a lot!
