### ISSUE TITLE
Can't add funds to piggy bank

### ISSUE THREAD

**Issue by irl** [firefly-iii/firefly-iii#2662]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

I am trying to add to a piggy bank but it tells me it can't do it.

**Steps to reproduce**

1. Create a piggy bank
1. Try to add any positive amount to it

Interestingly, adding negative amounts works, and you can bring the amount back to zero but not above zero.

There is enough left to save to cover the amount I am trying to add.

**Expected behavior**

The amount added to the piggy bank with totals updating

**Extra info**

Debug information generated at 2019-09-27 18:01:34 Europe/London for Firefly III version **4.8.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9-1 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2019-06-28 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | sqlite |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**

```
[2019-09-27 17:59:32] local.ERROR: Cannot add 1000 because canAddAmount returned false.  
```

**Comment by JC5** [comment]
I assume the account you created the piggy bank for has enough funds?

I’ll check out what happens with negative amounts.

**Comment by JC5** [comment]
I just checked this and with SQLite it works perfectly well. Let me know what the account balance is, because I suspect that's the issue.

**Comment by irl** [comment]
Yes it does have enough funds. All the numbers look right, but then the check fails.

**Comment by JC5** [comment]
Weird. The check is pretty basic. I added some debug information. If you can, replace the code as you see it in the commit above. That should tell you what's going on exactly. Otherwise, you'll have to wait for the next release to see what's going on.

**Comment by Mindar** [comment]
I'm having the same problem. What's the easiest way to add the debug output to my dockerized firefly installation?

**Comment by JC5** [comment]
Run Firefly III from the `develop` branch.

**Comment by JC5** [comment]
So in the case of Docker, `jc5x/firefly-iii:develop`

**Comment by Mindar** [comment]
I'm not able to reproduce the issue with the `develop` version.

**Comment by JC5** [comment]
That's good to hear!

**Comment by jakguru** [comment]
I am having the same issue with version 4.8.1.8

**Steps to reproduce**

* Have funds in checking account (in this case, over $20k USD)
* Create piggy bank
* Attempt to add funds to piggy bank (in this case, $6k USD)

**Extra info**

Debug information generated at 2019-11-02 11:27:35 Etc/UTC for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | production |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.11-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-10-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, ldap, exif, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, Zend OPcache |

**Bonus points**

```
[2019-11-02 11:22:11] production.DEBUG: Left on account: 0.000000000000  
[2019-11-02 11:22:11] production.DEBUG: Saved so far: 0.000000000000  
[2019-11-02 11:22:11] production.DEBUG: Left to save: 6000.000000000000  
[2019-11-02 11:22:11] production.DEBUG: Maximum amount: 0  
[2019-11-02 11:22:11] production.DEBUG: Compare <= 0? 1, so false  
[2019-11-02 11:22:11] production.ERROR: Cannot add 6000 because canAddAmount returned false.  
```

**Comment by JC5** [comment]
Please open a new issue.
