### ISSUE TITLE
syntax error, unexpected ')' - no file, no logs.

### ISSUE THREAD

**Issue by Atherz97** [firefly-iii/firefly-iii#2663]
I am running Firefly III version x.x.x

**Description**
I went through installing Firefly according to the instructions [here](https://firefly-iii.readthedocs.io/en/latest/installation/server.html), and had some issues earlier [getting the artisan to set up the database](https://stackoverflow.com/questions/58139157/attempting-to-install-fireflyiii-pdo-exceptions?noredirect=1#comment102665271_58139157). 

I was a dummy and didn't see the environment variable set to pgsql instead of mysql, ok. The artisan scripts complete correctly. I then had some problem viewing the page, including the folder not showing in the index directory, which basically involved tidying permissions and rebooting the server, ok. The folder is now owned by root:root and everything in it by www-data:www-data.

Well, now I have the database set up and the files are accessible from the browser. So I get this error:

![image](https://user-images.githubusercontent.com/23059413/65809088-a2292f80-e167-11e9-9faa-b34964e05c65.png)

Enabling PHP to output errors to /var/log/php_errors.log, there is no syntax related error (or ERROR anything) in the logs. There's also nothing in /var/log/apache2 with the syntax error. I search all the logs with grep and the only "syntax '(' expected" message that appears is the log from me searching for the statement five minutes ago. Inspect console? Empty.

Where is this elusive file and error?

php 7.2.9 raspbian 10

**Comment by JC5** [comment]
You need PHP 7.3 to run Firefly III.

**Comment by Atherz97** [comment]
Okay,

Well I installed 7.3 and all the modules needed, re-ran the artisan scripts to migrate the db and on the public/index.php landing page I now get:

```
Not Found
The requested URL /finance/public/login was not found on this server.
```

**Comment by Atherz97** [comment]
[Resolved via FAQ](https://firefly-iii.readthedocs.io/en/latest/support/faq.html#faqselfhosted)
