### ISSUE TITLE
Removing security warning when Firefly exists in a subdirectory.

### ISSUE THREAD

**Issue by Atherz97** [firefly-iii/firefly-iii#2664]
My web server is structured so that Firefly operates in the /finance directory, and I have a forum in the /forum directory.

Due to the nature of the server I cannot shift the /finance/ directory of my Firefly installation up a level to satisfy the security warning for having /finance/ accessible to the public.

```
Danger! This directory should not be open to the public!

/public/ should be the document root of your web server.
```

(So /finance/public/ is the location of the dashboard, charts, etc.)

```
Installation  ./finance/
Landing       ./
Firefly App   ./finance/public
Forum         ./forum
```

Of course, I followed the FAQ and placed the .htaccess file in /finance/storage with:
```
Options All -Indexes
Deny from all
```

However the warning remains. I also want to keep the root index / open for a landing portal to the finance and forum page.

So I moved the firefly install to ../firefly-iii/ outside of the html scope, and moved the public folder back over to /finance/, hoping that the php files will still know where to look for the webapp data.

```
Installation  ../firefly-iii/
Landing       ./
Firefly App   ./finance/
Forum         ./forum/
```

But now I get the security error, which redirects to /finance/public that doesn't exist (since it shouldn't need to), but still presents the error in some kind of infinite redirect.

How can I preserve this second directory structure?

**Comment by JC5** [comment]
You can't. You can't just drag files around and make them work by magic.

If you run Firefly III from /finance/public everything under /finance could be publicly accessible, which includes session data, uploads and other stuff. 

You could try something with Apache's Alias command but I have no idea how it works.

**Comment by Atherz97** [comment]
Hmm, okay. I used a .htaccess file to deny all from /finance, and allow /finance/public. It'll work for now
