### ISSUE TITLE
Unrecoverable error trying to import csv data

### ISSUE THREAD

**Issue by risimmons** [firefly-iii/firefly-iii#2665]
I have just installed firefly-iii 4.8.1.1 on a Raspberry-pi 3.  I'm using mariadb database, php7.3 and nginx.  I set up a bank account and then attempted to import transactions since the start of 2018 from a csv file using a custom import.  This showed a progress bar indicating "running rules" or similar, and was taking ages, so I left it overnight.  In the morning it appeared to be in the same state.  On refreshing the page I re-logged in, and was greeted with this message;

> 
> Whoops! An error occurred.
> 
> Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> 
> file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/22/6f/226fc0c0c0ba0ac951d927e31c2c6280525b7615): failed to open stream: No such file or directory
> 
> More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.
> 
> If you cannot find the cause of this error or when you need some help, please open a ticket on GitHub.

I have no idea how to recover from this error.  I don't mind deleting things and starting again, but I don't really want to have to fully reinstall.  It isn't clear to me what I should delete to get up and running again, since I can't access anything currently.

**Comment by JC5** [comment]
This is a permission error. Try to make sure that the Firefly III directory is owned entirely by the `www-data` user, by running (for example)

```bash
sudo chown -R www-data:www-data /var/www/firefly-iii
```

Then, try again.

**Comment by risimmons** [comment]
Hah, right thanks.  I was sure I'd already tried that, but did it just now and all worked well, and the import had succeeded.  Maybe needs to be a suggestion on the error page or the FAQ or something.
