### ISSUE TITLE
How can I get redirects and so on to go to https rather than http

### ISSUE THREAD

**Issue by nicklan** [firefly-iii/firefly-iii#2666]
I am running Firefly III version 4.8.1.1

**Description**
I've set up firefly on a server when I can't bind port 80 for myself.  It's kinda working, but many things redirect/load to `http` instead of `https`. For example:

```
$  curl  -k https://[server]:[port]
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=http://[server]:[port]/login" />

        <title>Redirecting to http://[server]:[port]/login</title>
    </head>
    <body>
        Redirecting to <a href="http://[server]:[port]/login">http://[server]:[port]/login</a>.
    </body>
</html>
```

Is there a way to tell firefly that it should always send me to https and http?

**Extra info**
browser: firefox
Os: linux

**Bonus points**

**Comment by JC5** [comment]
If this happens, Firefly III (or rather, the underlying webserver) doesn't know you're expecting it to run on https. This happens often when you're using reverse proxies.

What web server is Firefly III running on?

**Comment by nicklan** [comment]
Thanks for the reply.  I'm just using straight nginx.  I modified the config from the CentOS install guide [here](https://old.reddit.com/r/FireflyIII/comments/825n4l/centos_7_nginx_installation_guide/) to have it run via ssl instead.  

My server config block is:
```
  server {
    listen       [port] ssl;
    root         /home/[user]/firefly/firefly-iii/public;
    ssl_certificate     ssl/nginx.crt;
    ssl_certificate_key ssl/nginx.key;
    server_name [server];

        location ~ \.php$ {
              try_files $uri =404;
              fastcgi_pass unix:[path/to/fpm.socket];
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
        }

        index index.php index.htm index.html;
        
        location / {
          try_files $uri $uri/ /index.php?$query_string;
          autoindex on;
          sendfile off;
        }
        
        error_page 404 /404.html;
            location = /40x.html {
        }
        
        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
```

so no proxies or anything, but it's certainly very possible I've configured something wrong here :)

**Comment by JC5** [comment]
Where is the `ssl on;` statement, to actually enable SSL? See the example below.

```
    ssl on;
    ssl_session_timeout 1d;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_ciphers 'LIST OF YOUR CHOSEN CIPHER SUITES HERE';
    ssl_protocols TLSv1.2;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_certificate /etc/letsencrypt/live/sub.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sub.domain.com/privkey.pem;
```

**Comment by nicklan** [comment]
Ahh, so I did have that in my config, but your suggestion made me review it all more carefully.  Turns out I was missing:
```
fastcgi_param   HTTPS             $https;
```

in my `fastcgi_params` file.

Once I added that it seems to be working.

Thanks, and feel free to close.
