### ISSUE TITLE
Readd export function

### ISSUE THREAD

**Issue by nxxxse** [firefly-iii/firefly-iii#2667]
**Description**

The export function has been removed in https://github.com/firefly-iii/firefly-iii/blob/master/changelog.md#480-api-0100---2019-08-09. I think any finance tool should also have an export option. Are there already plans to re-add this?

**Solution**

Readd export function.

**What are alternatives?**

* Some self written converter from SQL.
* Downgrade to 4.7.17.6.

**Comment by JC5** [comment]
Yes there are plans to add this again. I’ll keep the issue open to track the state.

**Comment by JC5** [comment]
A new export function will be available in the next release.

https://docs.firefly-iii.org/exporting-data/export

**Comment by JC5** [comment]
Fixed in the latest beta.
