### ISSUE TITLE
unable to get a login page

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#2668]
I am running Firefly III version x.x.x

**Description**
I was running succesfully version 4.7.x and tried to install version 4.8.1 or 4.8.1.1 using this steps
docker-compose stop firefly_iii_app
docker-compose rm
docker-compose pull firefly_iii_app
docker-compose -f docker-compose.yml up -d

I got no errors as far as I can remember.

In Kitematic I restarted the 2 containers and the status shows that they are both up and running

In firefox I launch the webpage http://localhost:8081/login and normally I get the login page but now the page stays blanck without a errormessage. It seems that it is unable to reach this login page?

**Bonus points**

-->

**Comment by JC5** [comment]
Use “docker logs -f container” to see what’s happening. 

Did you update the environmental variables? Checkout the docs, the names have changed.

**Comment by bartmaniac** [comment]
Ok I copied the content of the latest docker-compose.yml file into the one on my system and got an error while executing 'docker-compose stop firefly_iii_app'
ERROR: Couldn't find env file:  
I CD'ed into the directory where the yml file is

**Comment by JC5** [comment]
http://docs.firefly-iii.org/en/latest/installation/docker.html

**Comment by bartmaniac** [comment]
I installed the .env file and after running the command docker container logs -f <containerID> I get this

Application cache cleared!
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v4.8.1.1!                              |
| This version of Firefly III requires PHP7.3.                                 |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
[Wed Oct 02 00:56:06.523755 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.9 OpenSSL/1.1.1c configured -- resuming normal operations
[Wed Oct 02 00:56:06.524103 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.19.0.1 - - [02/Oct/2019:09:01:29 +0200] "GET / HTTP/1.0" 500 2277 "-" "-"
172.19.0.1 - - [03/Oct/2019:17:16:21 +0200] "GET / HTTP/1.1" 500 2279 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
172.19.0.1 - - [04/Oct/2019:23:53:37 +0200] "GET / HTTP/1.1" 500 2279 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

running docker ps in terminal is only showing 1 container 
e93770f9a0b3        jc5x/firefly-iii:latest   ".deploy/docker/entr…"   3 days ago          Up 3 days           0.0.0.0:80->80/tcp   documents_firefly_iii_app_1

In kitematic the logs of the documents_firefly_iii_db_1 container is showing

2019-10-05 01:17:03.605 UTC [1] FATAL:  database files are incompatible with server
2019-10-05 01:17:03.605 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 10.5 (Debian 10.5-2.pgdg90+1).

**Comment by JC5** [comment]
In your docker-compose file, change `image: "postgres:10"` to `image: "postgres:11"`

**Comment by bartmaniac** [comment]
after changing postgrest:10 to postgres:11 I get this

Application cache cleared!
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v4.8.1.1!                              |
| This version of Firefly III requires PHP7.3.                                 |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message
[Sat Oct 05 10:17:42.396784 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.9 OpenSSL/1.1.1c configured -- resuming normal operations
[Sat Oct 05 10:17:42.396862 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Sat Oct 05 10:19:49.251110 2019] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
Now in entrypoint.sh for Firefly III
Making directories...
Touch DB file (if SQLlite)...
Run chown on /var/www/firefly-iii/storage...
Run chmod on /var/www/firefly-iii/storage...
Remove log file...
Dump auto load...
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 4983 classes
Discover packages...
Discovered Package: adldap2/adldap2-laravel
Discovered Package: danhunsaker/laravel-flysystem-others
Discovered Package: davejamesmiller/laravel-breadcrumbs
Discovered Package: fideloper/proxy
Discovered Package: laravel/passport
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rcrowe/twigbridge
Package manifest generated successfully.
Run various artisan commands...
wait-for-it.sh: waiting 15 seconds for firefly_iii_db:5432
wait-for-it.sh: firefly_iii_db:5432 is available after 0 seconds
db is up. Time to execute artisan commands
Application cache cleared!

In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select * from information_schema.tables where table_schema = publi  
  c and table_name = migrations and table_type = 'BASE TABLE')                 
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

Going to decrypt the database.

In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = is  
  _decrypted_accounts and "configuration"."deleted_at" is null limit 1)        
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_transaction_identifier and "configuration"."deleted_at" is null limit 1)   
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_migrated_to_groups and "configuration"."deleted_at" is null limit 1)       
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_account_currencies and "configuration"."deleted_at" is null limit 1)       
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_transfer_currencies and "configuration"."deleted_at" is null limit 1)      
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_other_currencies and "configuration"."deleted_at" is null limit 1)         
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_migrate_notes and "configuration"."deleted_at" is null limit 1)            
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_migrate_attachments and "configuration"."deleted_at" is null limit 1)      
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_bills_to_rules and "configuration"."deleted_at" is null limit 1)           
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_bl_currency and "configuration"."deleted_at" is null limit 1)              
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_cc_liabilities and "configuration"."deleted_at" is null limit 1)           
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_migrated_to_groups and "configuration"."deleted_at" is null limit 1)       
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  0_rename_account_meta and "configuration"."deleted_at" is null limit 1)      
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "id", "name", "data" from "configuration" where "name" = 48  
  1_migrate_recurrence_meta and "configuration"."deleted_at" is null limit 1)  
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select * from "piggy_bank_events")                                  
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select * from "link_types" where "name" = Related and "link_types"  
  ."deleted_at" is null limit 1)                                               
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "users".* from "users" order by "id" desc)                   
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select * from "transaction_types" where "type" = Withdrawal and "t  
  ransaction_types"."deleted_at" is null limit 1)                              
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "data" from "account_meta" where "name" = currency_id group  
   by "data")                                                                  
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select distinct "transaction_journals".* from "transaction_journal  
  s" left join "transaction_types" on "transaction_types"."id" = "transaction  
  _journals"."transaction_type_id" left join "budget_transaction_journal" on   
  "transaction_journals"."id" = "budget_transaction_journal"."transaction_jou  
  rnal_id" where "transaction_types"."type" not in (Withdrawal) and "budget_t  
  ransaction_journal"."budget_id" is not null and "transaction_journals"."del  
  eted_at" is null)                                                            
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "transaction_journal_id", SUM(amount) AS the_sum from "tran  
  sactions" where "deleted_at" is null group by "transaction_journal_id")      
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "transaction_journal_id" from "transactions" where "amount"  
   = 0 and "transactions"."deleted_at" is null)                                
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "transaction_journals"."id" as "journal_id", "transactions"  
  ."id" as "transaction_id" from "transactions" left join "transaction_journa  
  ls" on "transactions"."transaction_journal_id" = "transaction_journals"."id  
  " where "transaction_journals"."deleted_at" is not null and "transactions".  
  "deleted_at" is null and "transactions"."id" is not null and "transactions"  
  ."deleted_at" is null)                                                       
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select COUNT(transactions.transaction_journal_id) as the_count, "t  
  ransaction_journal_id" from "transactions" where "deleted_at" is null and "  
  transactions"."deleted_at" is null group by "transactions"."transaction_jou  
  rnal_id")                                                                    
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "transaction_group_id" from "transaction_journals" where "t  
  ransaction_journals"."deleted_at" is null)                                   
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select * from "transaction_journals" where "transaction_journals".  
  "deleted_at" is null)                                                        
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: update "journal_meta" set "name" = original_source where "name" =   
  original-source)                                                             
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "transaction_journals".* from "transaction_journals" left j  
  oin "transaction_types" on "transaction_types"."id" = "transaction_journals  
  "."transaction_type_id" where "transaction_journals"."deleted_at" is null a  
  nd "transaction_types"."type" = Opening balance and "transaction_journals".  
  "deleted_at" is null)                                                        
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select distinct "budgets"."id", "budgets"."name", "budgets"."user_  
  id", "users"."email" from "budgets" left join "budget_transaction_journal"   
  on "budgets"."id" = "budget_transaction_journal"."budget_id" left join "use  
  rs" on "budgets"."user_id" = "users"."id" where "budget_transaction_journal  
  "."budget_id" is null and "budgets"."deleted_at" is null and "budgets"."del  
  eted_at" is null)                                                            
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               


In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: select "users".* from "users" order by "id" desc)                   
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

Encryption keys already exist. Use the --force option to overwrite them.

In Connection.php line 664:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y" (SQL: insert into "oauth_clients" ("user_id", "name", "secret", "redirec  
  t", "personal_access_client", "password_client", "revoked", "updated_at", "  
  created_at") values (?, FireflyIII Personal Access Client, OmZClb3OTBHLWjj8  
  SINHlEZbwcIaU2p0dvHIW8k6, http://localhost, 1, 0, 0, 2019-10-05 10:20:17, 2  
  019-10-05 10:20:17) returning "id")                                          
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[08006] [7] FATAL:  password authentication failed for user "firefl  
  y"                                                                           
                                                                               

Application cache cleared!
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v4.8.1.1!                              |
| This version of Firefly III requires PHP7.3.                                 |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
[Sat Oct 05 10:20:17.938464 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.9 OpenSSL/1.1.1c configured -- resuming normal operations
[Sat Oct 05 10:20:17.938703 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

**Comment by JC5** [comment]
Sorry I completely forgot about this one. Not really sure what the cause is. Password failures are usually caused by a mismatch in env vars between two instances (FF3 and the DB).
