### ISSUE TITLE
Autocomplete value not used in transaction

### ISSUE THREAD

**Issue by dlvandenberg** [firefly-iii/firefly-iii#2671]
**Bug description**
When creating a transaction, when a description value is entered via auto-completion, the value is not saved.

Debug information generated at 2019-10-01 08:12:07 Europe/Amsterdam for Firefly III version **4.8.0.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.3 |
| FF API version | 0.10.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.20 |
| Display errors | Off |
| Session start | 2019-09-20 00:00:00 |
| Session end | 2019-10-20 00:00:00 |
| Session first | 2018-10-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite, sqlsrv |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 |
| Loaded extensions | Core, date, libxml, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, bz2, calendar, curl, dba, exif, ftp, gd, gettext, gmp, iconv, imap, intl, ldap, mailparse, mysqli, openssl, pdo_dblib, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, shmop, soap, sockets, sqlite3, ssh2, sysvmsg, sysvsem, sysvshm, wddx, xmlrpc, xsl, zip, Zend OPcache |

**Steps to reproduce**
1. Create a transaction
2. Type in the first few characters of a often used description (to trigger autocompletion), e.g. 'Groc' for 'Groceries
3. When suggested, click the autocompletion value 'Groceries'
4. Description should read: 'Groceries'
5. Fill in required fields and saved
6. Transaction is saved with 'Groc' instead of 'Groceries' as its description.

**Expected behavior**
Autocompleted value should be saved.

**Screenshots**
1. 
<img width="325" alt="Screenshot 2019-10-01 at 08 23 15" src="https://user-images.githubusercontent.com/15652758/65938987-d5e4ad80-e424-11e9-9ff1-c7d5ebcb4326.png">
2. 
<img width="812" alt="Screenshot 2019-10-01 at 08 25 05" src="https://user-images.githubusercontent.com/15652758/65939045-062c4c00-e425-11e9-8b89-8f49c4ce196b.png">
3.
<img width="308" alt="Screenshot 2019-10-01 at 08 23 45" src="https://user-images.githubusercontent.com/15652758/65938995-dbda8e80-e424-11e9-9098-d39a6f389cc9.png">
4.
<img width="558" alt="Screenshot 2019-10-01 at 08 23 54" src="https://user-images.githubusercontent.com/15652758/65939002-e006ac00-e424-11e9-99b0-d86016010ba5.png">

**Comment by JC5** [comment]
Please upgrade to the latest version.

**Comment by dlvandenberg** [comment]
Ah, I assumed I had the latest installed, but I still had php 7.2 so I was stuck at 4.8.0.3.
Updated to PHP 7.3 and 4.8.4.1 and it now works again.
