### ISSUE TITLE
New Asset Transaction from Dashboard

### ISSUE THREAD

**Issue by Leosirth** [firefly-iii/firefly-iii#2672]
**Bug description**
In the dashboard page there is the asset list to the right with a "Create new transaction" button for each asset.

Clicking on one of this shouldn't it auto-fill i.e. the source account based on the asset for which the button has been clicked?
Otherwise it's a useless repetition to have the "Create new transaction" repeated for every asset.

Maybe the button can be splitted in "Create new Withdrawal" and "Create new Deposit" and auto-fill the Source or Destination account accordingly.

What is your thoughts?
Thanks and regards,

**Comment by JC5** [comment]
Both used to be the case. I'll mark it as an enhancement.

**Comment by JC5** [comment]
This will work again in the next release.
