### ISSUE TITLE
Redundant introductory tutorial step on New withdrawal screen

### ISSUE THREAD

**Issue by jpelgrom** [firefly-iii/firefly-iii#2677]
Using Firefly III version 4.8.1.1 with the defaults after a new setup, the introductory tutorial on the new withdrawal screen includes a step for foreign currency for which there is no longer a field by default. This results in the box being shown in the middle of the screen with no fields highlighted.

![image](https://user-images.githubusercontent.com/8148535/65994905-a66d8980-e494-11e9-81db-484cd8291dd6.png)

**Steps to reproduce**
1. Setup a new Firefly III instance.
2. After arriving at the dashboard, click "Create new withdrawal" on any of the accounts shown on the right.
3. Click through to tutorial step 3.

**Expected behavior**
I think it'd be best to remove this step for now. It would be nice if it was shown again the first time this option becomes available, but I'm not sure how easy that is to implement.

**Comment by JC5** [comment]
Ah yes, nice. I'll pick it up.

**Comment by JC5** [comment]
Will be fixed in the next release.
