### ISSUE TITLE
Unable to add/edit foreign currency in a transaction [v4.8.1.1]

### ISSUE THREAD

**Issue by cenci0** [firefly-iii/firefly-iii#2679]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

I cannot add or edit transactions in foreign currencies (and yes, I enabled foreign currencies in the *Currencies* settings page).

**Steps to reproduce**
Add/Edit a transaction

**Expected behavior**
Shows the option to edit the foreign amount of the transaction (ex. USD if the account is in EUR)

**Extra info**
Running in Docker using docker-compose, upgraded from v4.7 (cannot remember the exact version, sorry)

**Bonus points**
![Transaction Details](https://user-images.githubusercontent.com/6401170/66038751-4a961580-e513-11e9-9caf-29eb25dfbb87.png)
![Transaction Edit](https://user-images.githubusercontent.com/6401170/66038753-4d910600-e513-11e9-95de-7be69b2c3250.png)

**Comment by JC5** [comment]
What happens after you browse to /flush? Maybe it's a cache issue.

**Comment by cenci0** [comment]
Nope, not a cache issue apparently, browsing to `/flush` doesn't change anything.
Even after a container restart the problem persists.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2574

**Comment by cenci0** [comment]
Mhm, I saw that issue but he was talking about the currency related to another field, the *Amount* one.
My bad, I thought that was referred only to the *Amount*, not the *Foreign Amount* too and the multi-currency support...

![screen](https://user-images.githubusercontent.com/25054050/64159501-08f64a00-ce43-11e9-9720-78ee578a3179.png)
I had seen this screenshot in another issue and I thought one could create new transactions specifying a foreign amount like in the older version, must be a regression introduced with this version then.

I'll wait for this feature to be enabled again, thanks.

**Comment by JC5** [comment]
This is still possible. I don't have this problem. I have three currencies enabled and the field is right there. How many currencies do you have enabled?

**Comment by cenci0** [comment]
I have five enabled right now (CHF, EUR, GBP, JPY, USD).

I'll try to debug with the help of the logs a little bit deeper.

**Comment by JC5** [comment]
Sorry, I completely forgot about this.

I'll try to replicate your issue. I'm also using Vue. To enable debug mode, you could build the packages yourself using something like yarn or npm.

**Comment by cedricpim** [comment]
Hi @JC5,

I find the same problem. I can only define the foreign when it is a transfer (from Asset account to another Asset account).

When it is an expense or withdraw, I don't see the field for Foreign Amount. I saw this issue and the screenshots you put: https://github.com/firefly-iii/firefly-iii/issues/2155#issuecomment-470803110

The version 4.8.1.4 seems a bit different, because I cannot pick Withdrawal/Deposit/Transfer, the system seems to be smarter and just infer it. But, "Native Amount" doesn't show up.

**Comment by cenci0** [comment]
Okay, quick update.

I haven't touched anything on my main instance, neither the docker image nor the DB (not even a flush, as I was playing with another instance), but it now shows me the option to select a foreign currency as I click on the _Create new transaction_ button in the homepage. Still on v4.8.1.4.

However, as soon as I choose an account from the dropdown (either the _Source account_ or the _Destination account), no matter which of the existing ones, the option disappears and it blocks the currency to **Euro**. If I type a new account name, this problem doesn't present itself.
I think this is caused by the fact that either _EUR_ is my main currency or that in that account there are only transactions in _EUR_ so the app has set the "currency property" of that account and it doesn't let me add transactions in a different currency.
I took a small recording of this, tomorrow I'll convert it to a GIF and upload it here if I can.

-----

On a small side note, sometimes after a refresh (good ol' F5) the first option in the dropdown menu is `(none)`, but it doesn't happen always.
![none](https://user-images.githubusercontent.com/6401170/67434884-54c7a300-f5eb-11e9-94cb-92a4aa7618d3.PNG)

**Comment by JC5** [comment]
I would prefer it if you would stop giving updates in closed issues, but I can tell you that changing the **base** currency for a transaction is not going to be possible. It'll be the currency of the asset account and nothing else.

**Comment by cenci0** [comment]
Sure. I mean, I don't care anymore since my problem fixed itself and I hope with time it does the same for @cedricpim and whoever else might have had it. I just thought it might have helped you have better insight of what could have happened.

By the way, you closed the issue flagging it as a "question" relating it with another issue when it wasn't a question, it sure wasn't resolved and wasn't related to the other issue at all. I just hoped you'd realize it sometime and reopen it fixing the label since I can't do it myself (rightly so, of course).

Thanks again for the app and the continuous time you are putting into its development.

**Comment by JC5** [comment]
Good point, thanks for telling me. I might open another issue altogether for this :)
