### ISSUE TITLE
After upgrading to 4.8.1.1, all transactions disappeared.

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#2680]
I just update my Firefly III from 4.7.17 to 4.8.1.1 (with errors https://github.com/firefly-iii/firefly-iii/issues/2480, but all it's has fixed by JC5). The last update attempt went smoothly.
But after update I have not transactions in my Firefly database. In reports also nothing.

The screenshots show two copies of Firefly with the same database. One before update (all data is in place). Friend after update (all transactions were gone).

Account balance transferred correctly. Changing the balance on the charts is also correct (over the past months everything is also correct, I watched).

![11](https://user-images.githubusercontent.com/520760/66065334-d62d9780-e54f-11e9-9be1-161c47a583bb.jpg)
![222](https://user-images.githubusercontent.com/520760/66065335-d6c62e00-e54f-11e9-828a-cf14f5981d8a.jpg)

Log files attached.

[ff3-apache2handler-2019-10-02.log](https://github.com/firefly-iii/firefly-iii/files/3682354/ff3-apache2handler-2019-10-02.log)
[ff3-audit-2019-10-02.log](https://github.com/firefly-iii/firefly-iii/files/3682355/ff3-audit-2019-10-02.log)
[ff3-cli-2019-10-02.log](https://github.com/firefly-iii/firefly-iii/files/3682356/ff3-cli-2019-10-02.log)

**Comment by Nik-vr** [comment]
I see database in SQLite Viewer - records of transactions in the database are available. But Firefly doesn't see them.

**Comment by JC5** [comment]
Are the values for "deleted_at" filled in?

**Comment by Nik-vr** [comment]
Where exactly to look for this field?

**Comment by JC5** [comment]
Is there a date in the field, for example in the table transaction_journals or transaction_groups?

**Comment by Nik-vr** [comment]
No, this field is empty in all tables (only a few old records have it filled).

![222](https://user-images.githubusercontent.com/520760/66071389-bb612000-e55b-11e9-8f58-efe120da7029.jpg)

**Comment by JC5** [comment]
OK, that's good at least. Does the same apply to the table "transaction_groups"?

**Comment by jlauwers** [comment]
Same issue.
New transaction are displayed.

**Comment by jlauwers** [comment]
Might be related to https://github.com/firefly-iii/firefly-iii/commit/05bee579322331ab0a081aba619cc048b64ee552 ?

**Comment by jlauwers** [comment]
> OK, that's good at least. Does the same apply to the table "transaction_groups"?

Look's like it's the issue.

```
id  |     created_at      |     updated_at      |     deleted_at      | user_id |    title                                                                                                                        
-----+---------------------+---------------------+---------------------+---------+-------------                                                                                                                    
   3 | 2019-08-10 19:46:15 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
   4 | 2019-08-10 19:46:15 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 136 | 2019-08-10 19:46:17 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 137 | 2019-08-10 19:46:17 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 408 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 409 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 410 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 411 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 412 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 413 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 414 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 415 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 416 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 417 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 418 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 419 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 420 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 421 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 422 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |                                                                                                                                 
 423 | 2019-08-10 19:46:21 | 2019-10-02 18:32:55 | 2019-10-02 18:32:55 |       1 |       
```

**Comment by jlauwers** [comment]
```
firefly=# update transaction_groups set deleted_at = NULL where deleted_at = '2019-10-02 18:32:55';                                                                                                                
UPDATE 950
```

Got my transaction back.

**Comment by JC5** [comment]
That could also be a cache thing. I'll need to do some research why they disappeared in the first place.

**Comment by jlauwers** [comment]
Any way to clear the cache?

**Comment by jlauwers** [comment]
Updated from 4.8.1 to 4.8.1.1.
Transaction disapeared again but now I know how to get them back.

**Comment by Nik-vr** [comment]
> Any way to clear the cache?

No, clearing the cache didn't help me.

**Comment by Nik-vr** [comment]
> Does the same apply to the table "transaction_groups"?

In this table the field is filled.

![11](https://user-images.githubusercontent.com/520760/66145814-3dad1b00-e614-11e9-85c2-3cca50c6e68f.jpg)

**Comment by JC5** [comment]
OK, looking at the issue you reported earlier, I suspect the large batch of transactions broke SQLite. This in turn made Firefly III think there were no transactions.

You can reset the database by restoring an old copy, or by running this query:

```sql
update transaction_groups set deleted_at = null;
```

But please make sure you backup your database for this query as well. 

If it's possible for you, try to upgrade again with the `develop` branch or wait for the next version of Firefly III, in which this should be fixed.

**Comment by jlauwers** [comment]
I'm not using sqlite so I don't think that's the issu.

**Comment by JC5** [comment]
Alright, then I'll have to do some digging. Do you have backups from way before you started the upgrade?

**Comment by jlauwers** [comment]
I do not. But I managed to reproduce with my DB by going back to 4.8.1 and
upgrading again.

I'll see if I can give you something tomorrow.

**Comment by JC5** [comment]
This is fixed in the next release.

**Comment by Nik-vr** [comment]
I updated again from version 4.7.17 to 4.8.1.4. Now everything is working correctly. Thank you!

**Comment by JC5** [comment]
Glad to hear it! :+1:
