### ISSUE TITLE
Budget amounts display with many decimal places

### ISSUE THREAD

**Issue by calvin-n-hobbes** [firefly-iii/firefly-iii#2681]
After updating to **Firefly III v4.8.1.1**, I noticed that the Budgets section displays non-zero amounts with a large number of decimal places (padded with zeroes). I don't remember seeing this before I upgraded (I think I was previously on 4.8.0.3), so am wondering if this is expected behavior in later versions?

<img width="821" alt="Screen Shot 2019-10-02 at 3 46 29 PM" src="https://user-images.githubusercontent.com/5327981/66087682-4119a700-e52d-11e9-8f04-442a05055f80.png">

I am running Firefly III through Docker on my Synology NAS, and I use USD as my one and only currency with 2 decimal places in the currency's settings. The other curious thing is that even though I only have one currency enabled, the zero budgets still expose the option to set the budget in another currency, while the non-zero budgets do not.

I also looked at the [budgets section on the demo site](https://demo.firefly-iii.org/budgets) where it uses EUR currency (and 2 decimal places), but it shows **zero** decimal places for round numbers.

<img width="821" alt="Screen Shot 2019-10-02 at 3 46 29 PM" src="https://user-images.githubusercontent.com/5327981/66088222-33fdb780-e52f-11e9-8429-3eaefb9b43c4.png">

For reference, this is the debug info from my instances of Firefly:

Debug information generated at 2019-10-02 16:11:05 America/Los_Angeles for Firefly III version **4.8.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-10-01 00:00:00 |
| Session end | 2019-10-31 00:00:00 |
| Session first | 2017-05-26 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2626
