### ISSUE TITLE
Transfer between asset account and cash wallet displays incorrectly on dashboard

### ISSUE THREAD

**Issue by homonnay** [firefly-iii/firefly-iii#2682]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

I created a transfer from one of my default asset accounts to a cash wallet account (yesterday i picked up cash from an ATM), and on the dashboard both accounts now have a transaction of positive amount of money. The amount of money on the accounts themselves are correct, so i think only the display is bugged. I could reproduce the bug on the same user account with different asset and cash accounts.

**Steps to reproduce**
Create a transfer from an asset account to a cash wallet account.

**Expected behavior**
On the dashboard, both accounts should have a transaction of positive amount.

**Extra info**
Windows 10, Google Chrome

Debug information generated at 2019-10-03 14:19:03 Europe/Budapest for Firefly III version **4.8.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-10-01 00:00:00 |
| Session end | 2019-10-31 23:59:59 |
| Session first | 2019-09-30 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 3 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

**Comment by JC5** [comment]
Thanks, I'll pick it up.

**Comment by JC5** [comment]
Sorry, since it's a transfer I don't always know, from the context which account is receiving and which one is sending. I can't fix this.
