### ISSUE TITLE
Linking a transaction twice redirects to the wrong transaction

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2683]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:
When you try to link two transaction together twice, you get an error message.
The problem is that the error message does not redirect to the correct transaction (I suspect it's a id vs group id thing)

**Steps to reproduce**

1. Go to a transaction already link to another (in my case `[...]transactions/show/40`, already linked to transaction `41`)
2. Link it once again with transaction `41`
3. The correct message appears however it redirects me to `[...]transactions/show/20`

**Expected behavior**

I believe it should redirect to transaction `40`.

**Extra info**

**Bonus points**

**Comment by gregoo** [comment]
That's the JSON response when I'm typing `40` in the transaction field of the link form (`[...]/json/transaction-journals/with-id?search=41`).
The transaction id is indeed `20` and its transaction group is `41`.
```
bill_id: null
book_date: null
completed: true
created_at: "2019-05-12 19:33:51"
date: "2004-02-16 00:00:00"
deleted_at: null
description: "-"
id: 20
interest_date: null
name: "#41: -"
order: 0
process_date: null
tag_count: 0
transaction_currency_id: 1
transaction_group_id: 41
transaction_type_id: 2
updated_at: "2019-05-12 19:33:51"
user_id: 1
```
So not only did it not go back to a transaction ID that was related to my link, it went back to the ID of the destination rather than the source.

**Comment by JC5** [comment]
Thanks, I'll pick it up.
