### ISSUE TITLE
Mobile UI enhancement. Plus button and menu

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2685]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

On mobile device I click **+** then I want open left menu and use it, but I can't.
After opening left menu - right menu do not disappear. 
It is not convenient.

![image](https://user-images.githubusercontent.com/25054050/66188223-6b837580-e68f-11e9-85c9-35b660bd59d4.png)

**Steps to reproduce**
1. Click **+** on the right.
2. Click menu button on the left.
3.You can't use left menu.

**Expected behavior**
Right menu should disappear after opening left menu.

**Comment by JC5** [comment]
It's part of the layout I'm afraid, and not something I can fix.
