### ISSUE TITLE
Brave ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by alphat5** [firefly-iii/firefly-iii#2686]
I am running Firefly III version 4.8.1.1

**Description**
Hey everyone, I'm not so good with using docker and so I'm running with the error ERR_CONNECTION_REFUSED when I go to the IP:PORT URL. But I can access my other containers without any issue...

For the installation of the container, I used the docker-compose way. After looking to the logs with `docker container logs -f <containerID>`, everything looks ok, I don't see errors.
I tried to disable ufw, still having the issue.

Does someone maybe have an idea how I can solve this?

**Extra info**
Browser: Brave Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
Firefly container port : 85:85
VPS  OS: Debian 9.11
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfca03
 Built:             Thu Aug 29 05:29:49 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfca03
  Built:            Thu Aug 29 05:28:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by JC5** [comment]
Could you share the command you use to start the container?

**Comment by alphat5** [comment]
> Could you share the command you use to start the container?
Hi JC5, thanks for your reply, here is the command I used :  
`docker-compose -f docker-compose.yml up -d`

**Comment by alphat5** [comment]
Problem solved, I just made a mistake in the port mapping.

In docker-compose.yml
`ports:                                                                                                                                                                                                                 - "85:85"
`
should be : 
`ports:                                                                                                                                                                                                                  - "85:80"`
