### ISSUE TITLE
Available budget showing total for all user accounts

### ISSUE THREAD

**Issue by Mercianix** [firefly-iii/firefly-iii#2687]
Hi, I am running Firefly III version 4.8.1.1 and I have two users on my installation. When entering the budgeted monthly amounts for either user, the total displayed is the sum total of the budgeted amounts for both users instead of the amount for the user currently in use.

![image](https://user-images.githubusercontent.com/55740333/66227534-3ef24c80-e6d5-11e9-8efc-677f25950719.png)

**Steps to reproduce**
1. Add a budget under a user account and populate with a value.
2. Create a second user account, add a budget and populate with any value.
3. View budgets under any user and total available shows sum of both budgets.

**Expected behaviour**
Total available budget should be for that user account only, not the total including other users. For the above screenshot, I expect to see £1,650 budgeted as that is the actual amount for that user.

**Additional**
The budget_limits table does not contain user_id and I believe it either could do, or the query could just join to budgets on the active user_id to filter?

Let me know if you need any additional information!

**Comment by JC5** [comment]
Nice find. That's sloppy. A fix will go out asap.
