### ISSUE TITLE
Balance tile not workflow-efficient

### ISSUE THREAD

**Issue by CryoByte33** [firefly-iii/firefly-iii#2688]
**Please let me know if I should provide more data or if I'm being stupid somehow!**
I am running Firefly III version 4.8.1.1

**Description**
The balance tile doesn't show current "real" balance unless you started with $0 at the beginning of the month. Is this intentional? It's pretty annoying not being able to see "Bills to Pay" (due to #2115) and your current actual balance at the same time. This seems to be related to #1676 where you say that it's designed to show the current month's income/expense ratio, but it makes bill planning very difficult as I don't know what I should pay in which pay period. (bi-weekly pay period, so very annoying to plan around).

Normal month range:
![Screenshot from 2019-10-04 13-49-37](https://user-images.githubusercontent.com/11524686/66228613-dc398a80-e6ad-11e9-8780-074e20ec33e8.png)

Everything range:
![Screenshot from 2019-10-04 13-50-23](https://user-images.githubusercontent.com/11524686/66228640-efe4f100-e6ad-11e9-887b-f52c3b46cc5d.png)

**Extra info**
Debug information generated at 2019-10-04 13:48:30 America/New_York for Firefly III version **4.8.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.10 |
| Display errors | Off |
| Session start | 2019-10-01 00:00:00 |
| Session end | 2019-10-31 00:00:00 |
| Session first | 2019-09-20 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, zip, Zend OPcache |

**Comment by JC5** [comment]
> The balance tile doesn't show current "real" balance unless you started with $0 at the beginning of the month. Is this intentional? 

Yes. The balance tile shows you income + expense for the current month. That's what it's for.
