### ISSUE TITLE
Rule triggers "Amount .." can't manage positive or negative amounts

### ISSUE THREAD

**Issue by porelli** [firefly-iii/firefly-iii#2690]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

ING Australia puts in the statements the very same description both for incoming and outgoing transfer to/from the saving account. The only practical way would be use a rule to identify if the amount is positive or negative.
However, it seems like the rules about amount are treating the value as absolute so "Amount is more than.. 0" always apply, both for credit and debit.

**Steps to reproduce**
- create a rule that matches "Amount is more than.. 0" and assign a tag "this transaction is credit"
- import a statement that contains both credit and debits
- all the transactions will be tagged

**Expected behavior**
- only the credit transactions should be tagged

**Extra info**
- I see the value in having an absolute evaluation of the amount, maybe it would be helpful having an additional trigger to specify if the amount is negative/debit or positive/credit

**Comment by JC5** [comment]
There's not much I can do about this unfortunately. The rule isn't designed to manage absolute amounts, and from the context it won't always be able to tell if you want the rule to trigger on positive or negative amounts. 

Do you have some example lines from your CSV to show me what you want exactly?

**Comment by porelli** [comment]
For example I got these two lines in my saving account:
```
Date | Account | Description | Credit | Debit
30/9/19 | 111111111 | Savings - Internal Transfer - Receipt 123456 Savings Maximiser 222222222 | 500 |  
30/9/19 | 111111111 | Savings - Internal Transfer - Receipt 654321 Savings Maximiser 222222222 |   | -100
```
and these two in my transaction account:
```
Date | Account | Description | Credit | Debit
30/9/19 | 222222222 | Savings - Receipt 123456 - To Orange Everyday |   | -500
30/9/19 | 222222222 | savings - Receipt 654321 - From Orange Everyday | 100 |  
```

In the first case I need to transform the transaction to a transfer from 222222222 to 111111111
In the second case I need to transform the transaction to a transfer from 111111111 to 222222222

If I understand correctly, I always have to change the transactions to transfers using the origin transaction rather than the destination. The second case works perfectly and it matches the debit transaction on the account 111111111.
However it matches also the first line and creates inconsistency.

I tried a similar approach starting from the destination transaction, creating a rule that matches "To/From Orange Everyday" and changes to transfer and then changes the origin account but it doesn't work.

**Comment by JC5** [comment]
Wow that's terrible practice by your bank. I'm not sure there's much I can do from Firefly III. You'll really need to run some pre-processing to manage those lines.

**Comment by porelli** [comment]
I created a set of regular expressions and a new bank-specific class to fix all the problems with the ING Australia statement. It creates matching and consistent descriptions between the saving and transactions accounts so I can create proper rules.

I modified my old rules to match the new descriptions, I can now match all the transactions that I want to move as transfers properly.

However, all the transfers are duplicated on the destination side. I made the change to have 100% the same description in both source and destination transactions but it still doesn't work:
(This is the transactions account)
<img width="1166" alt="Screen Shot 2019-10-07 at 14 14 01" src="https://user-images.githubusercontent.com/212605/66282890-f58c4200-e90c-11e9-99cf-2732f6f8cad8.png">
The first line is created automatically from the rule that matches the transaction in the saving account and shows the incoming transfer.
The second is the actual incoming transaction from the statement (after massaging) that doesn't get de-duplicated.
Of course, the receipt number of the two transactions matches.

**Comment by JC5** [comment]
Sorry, I completely forgot about this. 

> Ideally, the incoming transaction (1) should match automatically the the transaction changed as transfer (2). 

I'll see what I can do. This makes the import routine a lot more complex. But it should be possible indeed.
