### ISSUE TITLE
Liabilities as Destination Accounts in recurring Transactions

### ISSUE THREAD

**Issue by woolmonkey** [firefly-iii/firefly-iii#2691]
**Bug description**
I am running Firefly III version x.x.x, and my problem is:4.1.8.4
I am trying to upgrade my recurring Transactions and it won't let me select a liability account for a destination account.

**Steps to reproduce**
 Select a liability account for a destination in a recurring transaction.  Seems to only happen when the transaction is a transfer.

**Extra info**

**Bonus points**

![image](https://user-images.githubusercontent.com/2517303/66250787-6280bb80-e704-11e9-9915-a6353540321f.png)

**Comment by JC5** [comment]
Transactions to or from a liability are no longer transfers. Check out this overview:

https://www.patreon.com/posts/26635121

**Comment by woolmonkey** [comment]
Ok.  It's odd that the old one works till I try to edit it.

**Comment by woolmonkey** [comment]
Ok a new issue when I edited the reoccurring transaction I got a 404 page now when I go back and try to edit it I get undefined offset 0.
![image](https://user-images.githubusercontent.com/2517303/66254559-0da96900-e735-11e9-8b95-6bcf5cf5a544.png)

**Comment by woolmonkey** [comment]
Ok rolled back VM and did it in stages. Switching from transfer to withdrawal saved then from daily to weekly and it worked fine.

**Comment by JC5** [comment]
I'll make sure that future upgrade routines correct these recurring transactions.

**Comment by JC5** [comment]
This fix will be included in new releases.

**Comment by JC5** [comment]
Fixed in the latest beta.
