### ISSUE TITLE
Inconvenient form for creating a new transaction.

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#2692]
In version 4.8. the form of creating a new transaction is very inconvenient and illogical. For example, when I create a new deposit, I see the destination account field in the form. This is confusing! I also see a field for indicating the amount in foreign currency when my default currency is selected.
It would be more logical to hide fields that the user does not need at the moment.
Now it turns out that the forms of deposit, expense and transfer look the same, although from the point of view of logic they should fulfill different functions.

![11](https://user-images.githubusercontent.com/520760/66251022-6425a000-e753-11e9-9edf-232e888bcac8.jpg)
![22](https://user-images.githubusercontent.com/520760/66251023-64be3680-e753-11e9-9b00-b3b821e5af99.jpg)

**Comment by Nik-vr** [comment]
For transfers, the field "destination account" must be shown.
The field "amount in foreign currency" is shown only if a currency other than the default currency is selected. Moreover, in this situation, you can hide the usual field "sum", because usually it makes no sense to store both amounts.

**Comment by JC5** [comment]
Thanks for the feedback. I could give the fields other labels, that's a good idea.

Keep in mind that when the form loads I don't know what the user will do. It's a flexible form, it could go in any direction.

I'm not sure why you remove one of the accounts on the deposit form? It needs both the source and the destination.

**Comment by Nik-vr** [comment]
In older versions of Firefly, when choosing different items from the menu (create a deposit, create an expense, create a transfer), slightly different forms were opened (the set of available fields changed). And there were “tabs” for choosing the type of transaction right on the form. Now the same form is opened, with a single set of fields. It has become less convenient.

If, from a technical point of view, the form has changed a lot, it may be worth monitoring how it is called (the URL in the browser is different for deposits, expenses and transfers), and change the set of fields to a more suitable one for this situation.

Why when creating a deposit source account? I get some income from outside, I write it in Firefly. At the same time, I indicate the amount, destination account, category, date, budget and tags. It's all.

**Comment by JC5** [comment]
Yes, I understand what you mean.

For deposits, I also note the source: my job, a friend, another company, etc.

**Comment by Skrallexxx** [comment]
Out of personal preference, I also like the older version of the transaction creation forms. Just updated to 4.8.1 today, was previously on an older version for a long time, so it might just be that I'm not used to it. But my grievances so far are the following:

- The new form is less clear as to whats happening. The visuals don't emphasise the different accounts as much, so I find it a bit busier. 
- When you select 'After storing, return here to create another one' and 'Reset form after submission', the accounts field stick. In addition, they show an incorrect value, and even if the shown accounts are the same ones you want to use for the next transaction, you get an error when trying to submit the transaction.
- Some of my actual accounts get sorted below friends and family, meaning I have to search to select one of my actual accounts (ie. in the Source account drop-down). This makes it a bit more tedious.

I much preferred the layout such as shown [in this image from the docs](https://firefly-iii.org/static/docs/4.7.5.1/transaction-mandatory.png). I feel that I have to double check every field with the new form, slowing me down.

I don't mean this to sound too harsh. I love the work you've been doing and hope you keep it up! Interface design can be very subjective so it's also possible everybody else loves the new layout.

**Comment by JC5** [comment]
1. It is, yes. I'm trying to improve the form. The previous one simply wasn't maintainable anymore and resulted in a lot of double code.
2. Yes, this is a known bug.
3. I'm not entirely sure what you mean and I would appreciate a screenshot.

I'm using Firefly III as well and I know it's not perfect yet. Bear with me :)

**Comment by Nik-vr** [comment]
> I'm not entirely sure what you mean and I would appreciate a screenshot.

I think it means that not all accounts in the drop-down list are visible in the new form. And the principle of the selection of accounts that are displayed is incomprehensible. Previously, bills were displayed all in alphabetical order. I specifically added to some accounts the symbol "_" at the beginning of the name so that they are higher in the list (I use them more often than others). Now it does not work. And to select the right account you have to write its name manually.

**Comment by Nik-vr** [comment]
Another important note on the form of a new transaction. The "add split" button is located above the "Save transaction" button. And on the small monitor you can see only "Add split"! And very often you press this button, and then you have to delete the empty split. Very uncomfortable!

And one more problem. Previously, if you forgot to fill out any field on the form and clicked on the "Save Transaction" button, an error message was displayed. Now, with such an error, the Save Transaction button becomes inactive, but the error message does not appear. You have to reload the page and re-enter all the data.

**Comment by Nik-vr** [comment]
Yes, and one more thing. When you enter the name of the account, category or label, a search is performed and a drop-down list is formed. Previously, the search was not case sensitive. Now you must be case sensitive. My account names are written with the first capital letter, and now I have to enter them in the field with a capital letter.

**Comment by Skrallexxx** [comment]
See this screenshot for what I mean about account sorting. Note that I have another Credit card account that doesn't even show up in the list here, so I have to search for it every time. Previously when creating a withdrawal, this wouldn't happen, it would only show my actual accounts.

![Firefly III Account Sorting](https://user-images.githubusercontent.com/4609632/66691231-57f79080-ecc7-11e9-9549-503040179efa.png)

Is there a reason the old approach of having different tabs for Withdrawal, Deposit and Transfer had to go away? You mention code duplication, which I understand can be frustrating. Maybe there's a good middle ground that can be achieved. 

I really do love Firefly and I've been using it religiously since April, so I'm just trying to pitch in and help where I can. I've even setup some accounts for some of my friends who use it through my self-hosted instance also, it's honestly been great.

**Comment by adamxp12** [comment]
Just updated and wanted to chime in with my thoughts. 

Sure code deduplication is nice but it has ruined the UX. no longer is the a dedicated button for withdraw, deposit and transfer per account but the "create transaction" button no longer auto selects the account when you click it making it pointless having a create button for each account on the dashboard if I have to manually select both the source and destination account every time I make a withdrawal or deposit.

the UI is very complicated compared to the old one. I regret upgrading now. been using this program for about a year now and its been awesome used to be religious in adding stuff to it even via mobile now its inconvenient to do the standard taks

Personally I would want the option to go back to the old UI it was much simpler in my opinion having the 3 transaction types separated into their own page. I understand the code might be harder but surely the UX is more important? if the UX is rubbish then users will stop using it simple as.

I am seriously considering downgrading back to 4.7.x (if thats even possible) or whatever version didnt have this change as this is driving me crazy

**Comment by JC5** [comment]
Thanks for your feedback. I'm aware of the issues, and I'm hoping to improve the form as I continue to develop it. The useless button you mention is a known issue and I hope to have an improvement for it soon.

**Comment by JC5** [comment]
I've resolved most issues. The separate tabs aren't coming back I'm afraid. Once 5.1.1 is released this issue will be closed, and I would appreciate it if you'd open new issues for other pressing concerns.
