### ISSUE TITLE
My docker images are auto-updated, and 4.8.1.2 wiped all my transactions, any way I can recover my data?

### ISSUE THREAD

**Issue by vjFaLk** [firefly-iii/firefly-iii#2693]
I am running Firefly III version 4.8.1.4

Well, this sucks, but this one's on me. Any way I can possibly recover the data? I don't have any backups either (forgot to add firefly to my automated backups)

**Comment by JC5** [comment]
Well I have to congratulate you. You're the only one who managed to grab 4.8.1.2 in the 26 minutes it was online.

But you can restore easily, yes. In your database container, run the following query:

```sql
update transaction_groups set deleted_at = null
```

**Comment by vjFaLk** [comment]
Actually. I think I might just be dumb. I was looking at October and I haven't made an entry so far in October. I just read the release notes and assumed that my transactions got wiped, but really, my date filter was making me think that. 

I'm going to close this and pretend that this never happened.

**Comment by JC5** [comment]
Haha no worries, the bug was also a dumb one. Glad nobody got affected (so far ... 😅 )
