### ISSUE TITLE
Archive Accounts

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#2694]
Recently faced with such a situation. I had a deposit in the bank ("piggy bank"). It was sometimes replenished from my other accounts. All these transactions were recorded in Firefly. Then the deposit was closed, the money from it was withdrawn to a regular bank account. There was an account in Firefly, which now stores the history of my contribution and transactions on it. But in fact, this account is no longer needed. Yes, I made it hidden, but it still appears on the My Accounts page. At the moment I have 4 unnecessary old accounts on the My Accounts page.
If I delete such an account completely (and I tried to do it!), Then all transactions related to it are deleted and the balance on the linked accounts is incorrectly changed (from which money was transferred to the deposit, or to which money was transferred from the deposit). I had to restore the data from the backup after such a deletion.

It would be convenient to make a note “archived” for such old accounts so that they would not appear on the My Accounts page, but the transactions associated with it would be stored in the database. You can, for example, display these "archived" accounts on a separate page.

**Comment by JC5** [comment]
That's a good idea, I'll see what I can do.
