### ISSUE TITLE
Can't find .env file

### ISSUE THREAD

**Issue by GTP95** [firefly-iii/firefly-iii#2696]
I am (not yet) running Firefly III version 4.8.1.4

**Description**

I'm trying to install Firefly III 4.8.1.4 on a self-hosted server following the documentation, but arrived at the "Configuration" step described here https://docs.firefly-iii.org/en/latest/installation/server.html it says that I will find a .env file in the firefly-iii directory, but I can't find any. I also have problems initializing the database, but maybe solving this also solves the problems with the database. 
Thanks for your help
**Extra info**
The server is a SBC running Debian 10.

**Bonus points**

**Comment by JC5** [comment]
The following command:

```bash
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii <latest>
```

Which is listed [here](http://docs.firefly-iii.org/en/latest/installation/server.html#main-command) results in a `firefly-iii` directory that includes the `.env` file:

```bash
> @php artisan firefly:instructions install
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v4.8.1.4!                              |
| This version of Firefly III requires PHP7.3.                                 |
|                                                                              |
+------------------------------------------------------------------------------+
> @php artisan key:generate
Application key set successfully.
vagrant@ubuntu-bionic:/sites/temp$ cd firefly-iii
vagrant@ubuntu-bionic:/sites/temp/firefly-iii$ ls -lah .env*
-rwxrwxr-x 1 vagrant www-data 6.0K Oct  5 13:39 .env
-rwxrwxr-x 1 vagrant www-data 6.0K Oct  5 04:59 .env.example
```

If the file isn't there nothing works. You can create it manually by running the following commands:

```bash
cd firefly-iii
cp .env.example .env
composer install --no-dev --prefer-dist --no-scripts
php artisan key:generate
```

You can then start editing your `.env` file and complete the installation.

**Comment by GTP95** [comment]
Sorry my bad, I've later realized that the .env file referenced in the docs is a hidden file called env and not a file with the .env extension.
