### ISSUE TITLE
How to manage interest on savings account?

### ISSUE THREAD

**Issue by Moc** [firefly-iii/firefly-iii#2697]
I am running Firefly III version 4.8.1.5

**Description**
I imported all my bank transactions (CSV, ING Bank) from 01-01-2019 to date and all is working well. My savings account balance is slightly off however, because the interest (yes, the very small percentage that we still get :p) is not added. In my case, I have the "Bonusrente rekening" which means two additional transactions, or deposits actually, (base interest + bonus interest) took place on my savings account. 

My question: what is the best way to keep track of this? It is not included in the CSV because it is not a transaction from one account to another. 

There are also costs for having a bank account at ING (and also for additional accounts, mobile payments, etc.). I have created an Expense account for it. Do you recommend adding a transaction from this expense account to the savings account? 

**Extra info**
Don't think it's relevant here, but please let me know if you need it! 

**Bonus points**
Sorry.. not this time 😄 
Thanks a lot for this software by the way, it is perfect for what I need and very easy to use! 👍

**Comment by JC5** [comment]
I'm surprised that your bank doesn't add transactions for interest and costs. I know other banks do this. After all, they *are* transactions: from the bank to you and vice versa.

And yes, I suggest you create withdrawals and deposits yourself.

**Comment by JC5** [comment]
Also, you're very welcome :+1:

**Comment by Moc** [comment]
> I'm surprised that your bank doesn't add transactions for interest and costs. I know other banks do this. After all, they _are_ transactions: from the bank to you and vice versa.
> 
> And yes, I suggest you create withdrawals and deposits yourself.

Sorry I might have made it confusing:
- The bank costs (costs for having the bank account and optional extra options such as mobile payments) are added as a transaction. This is because there is an actual transaction from my 'Default asset account' (betaalrekening) to ING. These transactions are also included in the CSV. 

- The interest is added directly to my savings account by ING. There is no transaction from my 'default asset account' (betaalrekening) to the savings account. The transaction is therefore not included in the CSV. 

Anyway, I'll manually add it is a transaction.
