### ISSUE TITLE
include_net_worth always true when creating account "Rest-API"

### ISSUE THREAD

**Issue by justin2108** [firefly-iii/firefly-iii#2698]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:
when creating a account trough the rest-api the include_net_worth returns always true.
no matter what you put in the payload.

`payload = {"name": name, "type": "revenue",  "iban": IBAN, "include_net_worth": 0}`

**Steps to reproduce**
in python 3.7x with library requests
`
header = {"Authorization": auth_token,
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',}
payload = {"name": name, "type": "revenue",  "iban": IBAN, "include_net_worth": 0}
response = requests.post(base_url+"/api/v1/accounts", data=json.dumps(payload), headers=header)
`
or
`
payload = {"name": name, "type": "revenue",  "iban": IBAN, "include_net_worth": false}
response = requests.post(base_url+"/api/v1/accounts", data=json.dumps(payload), headers=header)
`

i run it in a docker container, i don't know why it says false

Debug information generated at 2019-10-06 01:36:32 Europe/Amsterdam for Firefly III version **4.8.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2018-01-01 00:00:00 |
| Session end | 2018-01-31 00:00:00 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
Nice find. This will be fixed in the next release.
