### ISSUE TITLE
(asset) account balance not updating

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#2699]
**Bug description**
I am running Firefly III version 4.8.1.4, and my problem is:
The account balance in the asset account view doesn't update (https://demo.firefly-iii.org/accounts/asset) if you check the two options above the `Update transaction` button.

**Steps to reproduce**
1. Create an asset account
2. Add a deposit
3. Open the details page of the deposit
4. Click on `edit`
5. Check the two boxes (`After updating, return here to continue editing.` and `Store as a new transaction instead of updating.`)
6. Click on `Update transaction`
7. Check the asset account view. The last deposit isn't added to the balance.
8. Edit the created deposit again and click on `Update transaction`. (don't change anything)
9. Check the asset account view. The account balance will be updated now.

**Extra info**
Tested on demo page.

**Comment by JC5** [comment]
It isn't, no. The result of that equation is cached by your web browser until a few reloads. There's not much I can do. The library that I use has some cache optimizations. I could disable it but that would come at the cost of slower response times.

**Comment by nicoschreiner** [comment]
As always. Very fast response from you. Thank you :smile: 

But as far as I can tell it isn't a browser caching problem. I tried to clear the cache and the balance is still not updated. Even if I do my steps as described above (except stell 8 and 9) and go to a different browser, the balance still isn't updated.

Check the demo page now. What balance is shown for you for the account "Test (not updating)"?
For me it's 1,00 but it should be 2,00 (if you check the transactions)

**Comment by JC5** [comment]
Oh very good, then it's Firefly III's internal cache. I pushed a fix.

**Comment by nicoschreiner** [comment]
Thanks. It's incredible how fast you fix stuff :D

**Comment by nicoschreiner** [comment]
@JC5 Would you like to change the labels of this issue to `bug` and `fixed`? Just to have it right :smiley:

**Comment by JC5** [comment]
There we go :grin:

**Comment by nicoschreiner** [comment]
Thanks! :D
