### ISSUE TITLE
Error displayed when creating a new transaction.

### ISSUE THREAD

**Issue by pedrom34** [firefly-iii/firefly-iii#2700]
**Bug description**
I am running Firefly III version 4.8.1.4, and my problem is that there's an error message when creating a new transaction.

**Steps to reproduce**
Create a new transaction, there's an error message saying that something was wrong with the submission. The transaction is created though. Modifying the transaction doesn't produce any error.

**Extra info**
User agent: Mozilla/5.0 (Windows NT 10.0; rv:69.0.2) Gecko/20100101 Firefox/69.0.2
Firefly is running on a OdroidC2 machine, with dietpi distribution, with PHP7.3, Apache server.
I don't remember the versions of apache and dietpi, but I can update this issue with the right infos if needed.

**Bonus points**
![2019-10-07 12_12_47-Créer une nouvelle opération » Opérations » Firefly III](https://user-images.githubusercontent.com/21216829/66303703-1c398100-e8eb-11e9-942d-197899abc634.png)

**Comment by JC5** [comment]
If you open your browser's console and submit the transaction again, you should be able to see the request that Firefly III makes and the response it gets back.

The user interface has difficulty showing errors not related to visible fields. In the console all errors can be seen.

**Comment by pedrom34** [comment]
Umpf. Thanks, it's an access rights issue.

I fixed it. Sorry about that.
