### ISSUE TITLE
Show budget and contract for transactions on the tag details page

### ISSUE THREAD

**Issue by tjedrowald** [firefly-iii/firefly-iii#2702]
**Description**
In previous versions of Firefly (4.7.17.6 and earlier) the tag details page (/tags/show/id) also showed the budget and the contract for a transaction. Could this be implemented again?

After importing transactions I always look a the details page of the import tag to review the import. The main purpose of this review is to see if the rules for categories, budgets and contracts are applied correctly. 

**Solution**
Also show the budget and contract for transactions on the tag details page.

**What are alternatives?**
Use the build in audit report (which is what I currently do).

**Comment by JC5** [comment]
I'll see what I can do to expand the details on each view.

**Comment by JC5** [comment]
I can't show the contract, but I can show the budget and category.

**Comment by tjedrowald** [comment]
That's already a big improvement for my workflow! Thnx for the fix :)
