### ISSUE TITLE
Cannot edit existing transactions

### ISSUE THREAD

**Issue by pard68** [firefly-iii/firefly-iii#2703]
**Bug description**
I am running Firefly III version 4.8.1.1 and my problem is:

Whenever I attempt to edit a transaction I get a "Whoops, looks like something went wrong." page. It doesn't appear to matter if the transaction is imported from a csv or created in Firefly III. Transactions can also be updated via rules. I created a rule and applied it to an imported transaction which could not be edited and it worked like a charm.

**Steps to reproduce**
1. Create transaction
1. Accounts > Asset Accounts > Select an Account (Savings, Checking, Credit have all been tried)
1. Select a transaction
1. Select  "Edit"
1. Select any combination of
> After updating, return here to continue editing.
> Store as a new transaction instead of updating. 
1. Get a "Whoops" page instead of the ability to edit the transaction

**Extra info**
Client is running:
 - Archlinux, 5.3.1-arch1-1-ARCH
 - Firefox 69.0.1

Server is running:
Debug information generated at 2019-10-08 18:54:45 UTC for Firefly III version **4.8.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.1 |
| FF API version | 0.10.2 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-10-01 00:00:00 |
| Session end | 2019-10-31 23:59:59 |
| Session first | 2019-09-23 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, ldap, mbstring, Zend OPcache |

**Comment by JC5** [comment]
I'll need some more info than the generic error message.

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on Github, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by pard68** [comment]
I suspect this is more an issue with Heroku than Firefly iii. I also cannot get the dyno to accept my change to `.env`. Do you know of any means of getting debugging on in the Heroku app?

**Comment by JC5** [comment]
No, I don't. All I know is Heroku uses an "ephemeral" file system so any changes to the .env file get lost when it goes to sleep.

**Comment by pard68** [comment]
We can close this. Got around to installing this on my server and it works fine, same version even. Must be something to do with Heroku... /shurg

**Comment by JC5** [comment]
Weird. Glad to hear it's fixed!
