### ISSUE TITLE
Installation with docker compose: No such file or directory

### ISSUE THREAD

**Issue by tannn** [firefly-iii/firefly-iii#2704]
Hi, I read the other issues and found that this was a common problem, yet for some reason the recommendations didn't work for me. I followed the instructions for installing with [docker compose](https://firefly-iii.readthedocs.io/en/latest/installation/docker.html#docker-hub-with-automatic-updates-via-docker-compose). 

The errors:
```
SQLSTATE[HY000] [2002] No such file or directory
SQLSTATE[HY000] [2002] No such file or directory (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)
```
My .env file: [here](https://pastebin.com/tiBRRPFJ)
My yml file: [here](https://pastebin.com/HSUD41wx)

From other issues I've read, a common cause for this problem seems to be the connection from firefly to the database. Since I'm using the bridge and creating a network, and I don't see how that can be the problem here. Any suggestions?

Thanks

**Comment by JC5** [comment]
Not really. Does it work if you run a "vanilla" yml file and .env file with postgres?

**Comment by optimistic5** [comment]
@tannn 
Try to use postgres instead.
Please, check my envs [here](https://gist.github.com/optimistic5/ca5a4a8593dcdb7360f712d37a0cc657).

**Comment by tannn** [comment]
Thanks @optimistic5 that worked. 

If I figure out what caused that error with my installation I'll update this.
