### ISSUE TITLE
only text on first login

### ISSUE THREAD

**Issue by sriptorium** [firefly-iii/firefly-iii#2706]
I am running Firefly III version 4.8.1.4

**Description**
On a fresh install, all localhost, can't reach first login page.
Install procedure was succesfull.
Apache directory is at /var/www/firefly-iii/public/
No specific error-related entry found in log

But on first login only getting a text output that reads :
. */ /** * Laravel - A PHP Framework For Web Artisans * * @package Laravel * @author Taylor Otwell */ define('LARAVEL_START', microtime(true)); /* |-------------------------------------------------------------------------- | Register The Auto Loader |-------------------------------------------------------------------------- | | Composer provides a convenient, automatically generated class loader for | our application. We just need to utilize it! We'll simply require it | into the script here so that we don't have to worry about manual | loading any of our classes later on. It feels great to relax. | */ require __DIR__ . '/../vendor/autoload.php'; /* |-------------------------------------------------------------------------- | Turn On The Lights |-------------------------------------------------------------------------- | | We need to illuminate PHP development, so let us turn on the lights. | This bootstraps the framework and gets it ready for use, then it | will load up this application so that we can run it and send | the responses back to the browser and delight our users. | */ /** @noinspection UsingInclusionOnceReturnValueInspection */ $app = require_once __DIR__ . '/../bootstrap/app.php'; /* |-------------------------------------------------------------------------- | Run The Application |-------------------------------------------------------------------------- | | Once we have the application, we can handle the incoming request | through the kernel, and send the associated response back to | the client's browser allowing them to enjoy the creative | and wonderful application we have prepared for them. | */ $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class); $response = $kernel->handle( $request = Illuminate\Http\Request::capture() ); $response->send(); $kernel->terminate($request, $response); 

**Extra info**
Ubuntu 19.0.4
Apache2
Mysql
Php7.3 + all required modules from install instructions

**Bonus points**
Screenshot using Firefox 69.0.2 on mac 10.14.6
<img width="1440" alt="Capture d’écran 2019-10-09 à 15 08 54" src="https://user-images.githubusercontent.com/55504376/66484628-9b73b400-eaa7-11e9-9eda-3fe4edffbf67.png">

**Comment by JC5** [comment]
Your Apache is not configured to handle PHP files.

**Comment by sriptorium** [comment]
omg. many thanks. (facepalm)
ran 
`sudo a2enmod php7.3`
and was good to go...
