### ISSUE TITLE
Missing documentation about IS_DOCKER=true

### ISSUE THREAD

**Issue by danger89** [firefly-iii/firefly-iii#2708]
I am (trying) to run Firefly III version latest docker image.

**Description**

While reading the docker manual:
https://firefly-iii.readthedocs.io/en/latest/installation/docker.html#docker-hub-with-automatic-updates-via-docker-compose

I think I should change the `.env` from false to true:

```sh
IS_DOCKER=true
```

However, this manual change is not documented..?

**Extra info**
Debian Linux

![Screenshot_2019-10-10_01-36-12](https://user-images.githubusercontent.com/628926/66528011-a148b400-eafe-11e9-92dc-e60561d0bffa.png)

**Comment by JC5** [comment]
The `IS_DOCKER` variable is only used on the /debug page, and was relevant way back when the Docker image had its own example `.env` file. It's no longer useful so I'll remove it from the `.env.example` file and the /debug page.

**Comment by danger89** [comment]
Thanks for clearing this up, I appreciate it.

**Comment by danger89** [comment]
Fixed: https://github.com/firefly-iii/firefly-iii/commit/22f63fd9515d9f754b54712042db5770c805a9b9
