### ISSUE TITLE
Fresh install on Ubuntu 18.04 server does not work

### ISSUE THREAD

**Issue by sykesd** [firefly-iii/firefly-iii#2712]
I am trying to install Firefly III version 4.7.17.6 on a freshly installed Ubuntu 18.04 server.

**Description**
I installed Firefly III (several times) using a combination of [this](https://old.reddit.com/r/FireflyIII/comments/8thxuu/fireflyiii_on_ubuntu_server_1604lts_nginx_php72/) and [this](https://gist.github.com/philthynz/ec04833a8e39c7f7d1b0d33cb4197a95), as linked to from the main documentation page.

My intention is that this will be a local-only installation, so I did not follow all of the instructions to secure the server. I only configured HTTP access under nginx.

I have two problems, possibly unrelated.

### 1. Visiting http://192.168.0.10/index.php redirects me to http://192.168.0.10/index.php/install

The contents of the page are:
```
FireflyIII
installation and upgrade.

Please wait...

Waiting to restart...
```

and it just sits there with nothing happening.

Checking `/var/www/html/firefly-iii/storage/logs` shows me a `ff3-fpm-fcgi-....` log file, which contains several messages of the form:

```
[date time] local.WARNING: The current configured version (1) is older than the required version (10). Redirect to migrate routine.
```

There were no installation errors that I could see, and the database installation commands all seemed to succeed correctly. `sudo php artisan firefly:verify` reports success.

What am I doing wrong?

### 2. Visiting http://192.168.0.10 only shows me the generic nginx welcome page. 
    
To get anything else I need to explicitly enter http://192.168.0.10/index.php

I would have expected the combination of  `root /var/www/html/firefly-iii/public;` and `index index.php index.html index.htm index.nginx-debian.html;` in the nginx configuration would make the first URL work, which is also what both installation guides led me to believe would happen.

**Extra info**
Ubuntu 18.04 server running in a virtual machine.

Accessing site using Firefox 69.0.1 from Windows 10

The site does not work so I cannot access the `/debug` page.

**Bonus points**
![image](https://user-images.githubusercontent.com/1282090/66537972-2d45f480-eb6e-11e9-889d-f4c8c0eb4042.png)

This appears to be very similar to #2229 which is closed but contained no information on whether or not it was resolved.

**Comment by JC5** [comment]
What's your exact nginx config for this site? I'm curious to see how php is configured.

**Comment by sykesd** [comment]
The complete `/etc/nginx/sites-available/default` file is:

```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /var/www/html/firefly-iii/public;
 
  index index.php index.html index.htm index.nginx-debian.html;
  server_name _;

  location / {
    try_files $uri $uri/ /index.php?query_string;
    autoindex on;
    sendfile off;
  }

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php7.2-fpm.sock;
  } 

  location ~ /\.ht {
   deny all; 
  } 
} 
```

**Comment by JC5** [comment]
What's in this file, exacty?

include snippets/fastcgi-php.conf;

Here are my files:

```
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
                add_header Access-Control-Allow-Origin "*" always;
                add_header Access-Control-Allow-Methods "GET, PUT, POST, DELETE, OPTIONS" always;
                add_header Access-Control-Allow-Headers "Content-Type, api_key, Authorization" always;
        }
```
Fast CGI
```
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
```

**Comment by JC5** [comment]
I see now you're referring to PHP 7.2. That won't work regardless of your configuration.

**Comment by JC5** [comment]
Sorry I just noticed you’re installing an old version. So that shouldn’t matter.

**Comment by sykesd** [comment]
Yes, I specifically chose this version because all of the guides I could find on installing this used 7.2 and 7.3 is not available in the main Ubuntu repository.

But even so, my main problem is the one where it redirects to the `/install` URL and complains about something being the wrong version.

Maybe it is time to try one of the Docker containers, but I have even less Docker experience than I have Linux/PHP experience :-(.
