### ISSUE TITLE
created_on search doesnt work

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2713]
**Bug description**
I am running Firefly III version 4.8.1.4, and my problem is:

The created_on doesnt seem to be working

**Steps to reproduce**
search for created_on:2019-10-10 returns nothing, and I had just created a transaction
https://demo.firefly-iii.org/search?search=created_on%3A2019-10-10

**Comment by JC5** [comment]
I’ll check it out, thanks.
