### ISSUE TITLE
Ability to see "first start page-walkthroughs" again

### ISSUE THREAD

**Issue by houlahaj** [firefly-iii/firefly-iii#2716]
**Description**
I would like there to be an option to see the initial tutorials again. As an overly eager user on a mobile device I noticed the first-start walkthroughs were more geared for the desktop and not the mobile and so skipped through them thinking it wasn't necessary to read. Now I kinda wish I could revisit them but can't find a way to reset the "already seen" flags.

Apologies if this is already possible and I am just too silly to find how to do it!

**Comment by JC5** [comment]
Check out the (?) button at the top right :)

**Comment by JC5** [comment]
I’ll check it out, thanks for reporting the issue :)

**Comment by JC5** [comment]
Will be fixed in the next release.
