### ISSUE TITLE
Consolidated Currency on Budget 

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2718]
**Description**
So I was reading the #1350 because of a unique situation I am in currently.

I have a budget with 3 currencies: BRL, EUR and USD.
Lets say I budget for 1000 EUR/month, so I would have around 4500 BRL, 1100 USD and 1000 EUR.

The current way the budget works is that it sets a limit per currency, which makes sense, but I have to manually multiply the amounts and consolidate into one main currency (usually BRL), so I dont get off track.

My suggestion would be, if possible, to add a CONSOLIDATED currency SUM on the budget page, so it shows this total.

Problem I see (and of course you have talked about it) is that there is no currency conversion, but maybe there could be a place to define the conversion rate manually and just go with it (usually I change those rates every couple months for USD and every month for BRL).

Anyway, just a thought that could save me a few minutes everyday.

**Solution**
Sum all budget into one consolidated currency pre-defined on the budget page.

**What are alternatives?**
Manually converting and summing

**Comment by JC5** [comment]
I'll see what's possible but I'm not a fan, even while using multiple currencies myself. Between bank's conversion rates and transfer fees it's difficult to get an accurate number.
