### ISSUE TITLE
An unknown error during the instalation

### ISSUE THREAD

**Issue by jakubmilkowski** [firefly-iii/firefly-iii#2720]
**Bug description**
I am running Firefly III version 4.8.1.4, and my problem is:

Error message during the installation on Heroku deployed Firefly III (I copied database from 4.8.1.1 version
![2019-10-10_14-38-37](https://user-images.githubusercontent.com/11717602/66636202-fc6acb80-ec10-11e9-8c77-480096c89338.png)
)

**Steps to reproduce**
Perform fresh install on Heroku

**Extra info**
Browser info:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Bonus points**

**Comment by JC5** [comment]
Do you have some logging from your instance? 

I know Heroku can be tricky to install.

**Comment by JC5** [comment]
Weird. Let me know how it goes. The bot will auto-close this, so let's leave it here and use it for feedback if you need it.

**Comment by jakubmilkowski** [comment]
Sadly after a couple days when I tried to create a new transaction, I've ended up with the same errors like here [2504](https://github.com/firefly-iii/firefly-iii/issues/2504) and here [2654](https://github.com/firefly-iii/firefly-iii/issues/2654)

**Comment by JC5** [comment]
There's not much I can do for Heroku I'm afraid. It has an ephemeral file system and removed the keys required for Firefly III to operate. I haven't found out how to prevent this from happening.
