### ISSUE TITLE
Filter feature (category) transactions

### ISSUE THREAD

**Issue by danger89** [firefly-iii/firefly-iii#2725]
**Description**

- As a user I would like to press on the category in the account->show page. And filter only by the selected category, meaning only show the transactions of that category.

- As a user I would like to be able to filter on other columns as well.

- As a user I would like to reset this filter option, so I will see all the transactions again on the Accounts Show page.

Related URLs: 
https://yourdomain.com/accounts/show/<id>
https://yourdomain.com/transactions/<withdrawal/desposit/transfers>

**Solutions**

-  Make the category chart clickable and trigger the filter on category

- Create a filter feature above the Tranaction table

**What are alternatives?**

Nice filtering/grouping/sorting feature above the transaction table.

**Additional context**
![image](https://user-images.githubusercontent.com/628926/66670240-948ca300-ec59-11e9-89a7-3970b4c3a208.png)

I hope you find such feature also useful.

Regards,
Melroy

**Comment by JC5** [comment]
Yes, but not in the current layout.

**Comment by danger89** [comment]
It's not a question, it's a feature request.
