### ISSUE TITLE
Missing the category chart on transactions

### ISSUE THREAD

**Issue by danger89** [firefly-iii/firefly-iii#2726]
**Description**

- As a user you also want to see the same chart(s), like the category chart, on the transactions pages.

Related URLs:
https://yourdomain.com/transactions/<withdrawal/desposit/transfers>

**Solution**

- Add the same kind of charts to the transaction page.

**Additional context**

Before:
![image](https://user-images.githubusercontent.com/628926/66670666-9acf4f00-ec5a-11e9-8b5d-14f949d22421.png)

After (impressing drawing):

![image](https://user-images.githubusercontent.com/628926/66670839-fe597c80-ec5a-11e9-99b8-2e2579e36706.png)

You like the idea?

Regards,
Melroy

**Comment by JC5** [comment]
Yep, I'll see if it's feasible to make them.

**Comment by danger89** [comment]
That would be awesome!

**Comment by JC5** [comment]
The charts you've requested will be available in the next release of Firefly III :)

You can check it out on the [demo site](https://demo.firefly-iii.org/).

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.
