### ISSUE TITLE
Attachment preview not working in Chromium

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#2727]
**Bug description**
I am running Firefly III version 4.8.1.4, and my problem is:
The attachment preview isn't working in Chromium (it is working in Firefox).

**Steps to reproduce**
1. Upload an attachment to a transaction
2. Click on the attachment (not downloading) to show the preview
3. Get a broken PDF preview

### Error in Chromium
Version: Version 77.0.3865.90 (Official Build) Built on Ubuntu , running on neon 18.04 (64-bit)
![image](https://user-images.githubusercontent.com/31184224/66683388-9ebd9a00-ec77-11e9-9a36-316d3d661222.png)
[Developer-Console Log](https://github.com/firefly-iii/firefly-iii/files/3719560/demo.firefly-iii.org-1570826696883-chromium.log)

### Error in Google Chrome (partly working - PDF not filling whole page)
Version: Version 77.0.3865.90 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/31184224/66683690-5f437d80-ec78-11e9-9224-12cbc7e76274.png)
[Developer-Console Log](https://github.com/firefly-iii/firefly-iii/files/3719562/demo.firefly-iii.org-1570826830645-chrome.log)

**Comment by JC5** [comment]
I see it. Stay tuned.

**Comment by JC5** [comment]
Will be fixed in the next release.

**Comment by nicoschreiner** [comment]
Thank you!
