### ISSUE TITLE
A lot of references to the standard currency in reports

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#2728]
I am running Firefly III version 4.8.1.4

In the standard financial report, the list with amounts by category became very large due to the display of the currency for each category. I think there is no need to display the default currency in this list. In general, I have only 1 currency, and I have to see its name in this list more than 10 times. Why is this?

![22](https://user-images.githubusercontent.com/520760/66697397-f2fb6500-ecdd-11e9-9dd9-8b5bed0a36c3.jpg)

**Comment by JC5** [comment]
Yeah I think that can be improved. Stay tuned.
