### ISSUE TITLE
Docker: Failure to load after container update (Twig extension)

### ISSUE THREAD

**Issue by Johnpojohn** [firefly-iii/firefly-iii#2730]
I'm running the latest version of the docker container. After updating, I am unable to access the application (HTTP Error 500). The log shows the following error numerous time while booting:

In ServiceProvider.php line 236:

Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': No application encryption key has been specified.

What am I doing wrong? 
Thanks for your help!

**Comment by JC5** [comment]
I suspect you're using environment variables that start with `FF_`? 

Use only the names you see in [this file](https://github.com/firefly-iii/firefly-iii/blob/master/.env.example) and replace your environment variables as fit.

**Comment by Johnpojohn** [comment]
yup, I renamed all FF variables according to the document and everything works again. Thanks so much!

I guessed the environment variables were changed at some point?

**Comment by JC5** [comment]
Yep. They match the env file (as you can see) for better consistency. :)
