### ISSUE TITLE
How to migrate from sandstorm to a self hosted firefly instance

### ISSUE THREAD

**Issue by n-serrette** [firefly-iii/firefly-iii#2732]
I am running Firefly III version on sandstorm oasis, the service will be shutdown by the end of years. 
I would like to know if their is a way to extract the data from a sandstorm backup and migrate them to a self hosted firefly instance.

 Thanks for your help!

**Comment by JC5** [comment]
Good question. If there's a way to access the underlying database you're good to go. But otherwise it's going to be tricky I'm afraid. I'm not sure how Sandstorm does that.

Isn't it still possible to run a Sandstorm host on your own machine? Couldn't you migrate that?

**Comment by TheAntimist** [comment]
@JC5 Would it possible in such a scenario to export the db from the UI?

**Comment by JC5** [comment]
No. An export routine is on my list https://github.com/firefly-iii/firefly-iii/issues/2667, but it will not be possible to export the entire DB over the UI.
