### ISSUE TITLE
Data export to other instance

### ISSUE THREAD

**Issue by sriptorium** [firefly-iii/firefly-iii#2733]
I am running Firefly III version 4.8.1.4

**Description**
Question regarding export of data between two instances

First and foremost, I'll take this opportunity to congratulate you sincerely on your work and continued efforts in developping firefly. This is a truely outstanding and extremely promising software, and I want to wish you all the best for the years to come in what I hope will be a rich adventure.

That said.
I have been fiddling with firefly in an unbuntu virtuabox for about two weeks, for personnal evaluation of its possibilities. 
All this time, I have been questioning myself about the future of the data that I provide into firefly.
Should I decide to move it to a production server for actual use, will the data in my vm be lost forever ? Or is there a proper export/migration process ?
Of course the question also stands for a future production instance. What are the possibilities to export all financial data out of the instance, to, for example, a csv, a pdf, API, etc... ?

Best regards,

**Comment by JC5** [comment]
An export routine was featured in the past but is currently not operational. See also https://github.com/firefly-iii/firefly-iii/issues/2667

If you want to migrate to another host, backup or migrate the data I suggest you use the native database tools you have at your disposal for PostgreSQL, MySQL or SQLite.

**Comment by JC5** [comment]
Whoops, pressed "Comment" a bit fast. Let me expand:

The export routine should be used (when its there) if you want to migrate to another tool. It will feature all the meta-data of your transactions but may not contain enough information to fully restore Firefly III itself.

If you want to migrate or backup the data, it's always better to use native tools, so I'm not going to build something to support that particular route.

Thanks for the compliments :)

**Comment by sriptorium** [comment]
Thanks for your answer !

I agree with you and understand the available export possibilities from the database.

While I see as quite obvious the time consuming investment to implement such export/backup functionality, I beleive this would highly boost the trust level from a user.

For the user to know that he may swiftly and at any time, backup/export his data directly, allowing him, if he so desires, to definitely close/shtudown an instance with no loss of data, would no doubt provide him with a very high and confortable level of trust in his instance.

Best and kind regards,

**Comment by JC5** [comment]
Exactly, otherwise it wouldn't even be on my list to restore :)
