### ISSUE TITLE
Make copy to clipboard button in PAT page

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2734]
**Description**
I'm creating Personal Access Token from smartphone.
It is very incontinent to copy this PAT into clipboard, because it is impossible to scroll down the page. 

- I would like Firefly III to have copy button in Personal Access Token page

**Solution**
Make some copy to clipboard button on this page
![image](https://user-images.githubusercontent.com/25054050/66732285-f6b8f400-ee63-11e9-97ef-e72b550c6c12.png)

**What are alternatives?**
Copy **all** the text from the page. Insert it in some note app, copy only PAT.

**Comment by JC5** [comment]
Good idea. I'll see what I can do.

**Comment by JC5** [comment]
I've been working on a proper fix but for now, the token will be presented in a textarea. It's not ideal but reliable copy/paste code is hard to find.
