### ISSUE TITLE
CSV Import support Multi-line header

### ISSUE THREAD

**Issue by obbardc** [firefly-iii/firefly-iii#2735]
**Description**
CSV files may have multiple lines of headers.

**Solution**
Allow multiple lines of headers to be ignored in the importer.
There would need to be a new key in the importer JSON file as well as in the web interface?

**What are alternatives?**
For now it is no problem to delete the extra lines before importing.

**Additional context**
Here is an example multiline CSV header from Nationwide in the UK.
```
"Account Name:","Personal ********"
"Account Balance:","£0.00"
"Available Balance: ","£0.00"

"Date","Transaction type","Description","Paid out","Paid in","Balance"
... the rest of the CSV content ...
```

**Bonus points**

**Comment by JC5** [comment]
No, sorry about that. They usually fail anyway because there is no amount in such a line. But they're adding extra headers in a file that is supposed to be machine-readable and I'm not going to accommodate that.

**Comment by obbardc** [comment]
Sure, I understand the reasoning behind this.
