### ISSUE TITLE
How to link Redis to Firefly in docker Synology

### ISSUE THREAD

**Issue by BobWs** [firefly-iii/firefly-iii#2736]
Hi,
How do I link Redis to Firefly in docker? I saw somewhere in code that FireFly supports Redis so I was wondering how to Link the two containers together.

**Comment by JC5** [comment]
You could try to set the following environment variables. 

```
CACHE_DRIVER=redis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
``` 

And see what happens :)

**Comment by BobWs** [comment]
I’m getting a error page see screenshot 

![08969C26-E5F1-4141-8B44-46EA7BE96007](https://user-images.githubusercontent.com/5485820/66862299-ece0df00-ef90-11e9-9da2-43bad33cbc8b.jpeg)

**Comment by JC5** [comment]
Yes that’s definitely an error.

https://laravel.com/docs/6.x/redis

**Comment by JC5** [comment]
But in all seriousness. You could try to install the associated package with this command, but you'll have to set it up every time you upgrade Firefly III

`docker exec -it <container> composer require predis/predis`

**Comment by BobWs** [comment]
That's a lot of fuss to have redis work. Maybe I should skip it!?

**Comment by JC5** [comment]
I will push some changes to the next release of Firefly III that should make it easier to use Redis with Firefly III.

**Comment by BobWs** [comment]
Okay thanks will give it a try
