### ISSUE TITLE
Import CSV fail everytime when importing from MoneyWiz 3

### ISSUE THREAD

**Issue by BobWs** [firefly-iii/firefly-iii#2737]
Hi,
I'm using MoneyWiz 3 (MacOS) at the moment as my financial manager, but I would like to try your software. I've installed it on docker Synology, so far so good!

But when I export my bank-records from MoneyWiz as a CSV file and try to import these into Firefly I keep getting an error that something went wrong with the import, check the log for more info. There is nothing in the logfile.

Any Idea how to solve this?

Thanks!

**Comment by dealanis** [comment]
Hey, for what is worth I migrated from MoneyWiz too. The issues that I had where all related to how the CSV is generated. I manually changed some stuff and had to try and rollback imports until the format was good enough. I remember something about the non-breaking space (nbsp) that monewiz use for spaces on the CSV. For my control, I made years/month CSVs moving from the source and simplifying categories and payees.

Maybe try creating a CSV only with one transaction and see if really the source file is the issue. This was my case. At the end I successfully migrated almost 5 years of data.

**Comment by BobWs** [comment]
> Hey, for what is worth I migrated from MoneyWiz too. The issues that I had were all related to how the CSV is generated. I manually changed some stuff and had to try and rollback imports until the format was good enough. I remember something about the non-breaking space (nbsp) that monewiz use for spaces on the CSV. For my control, I made years/month CSVs moving from the source and simplifying categories and payees.
> 
> Maybe try creating a CSV only with one transaction and see if really the source file is the issue. This was my case. At the end I successfully migrated almost 5 years of data.

Hey, thanks for sharing I will give it a try. I have almost 20 years of data in MoneyWiz so that is a lot of data to process 😏

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by BobWs** [comment]
I Think I figured it out. I need to tweak the exported file from MoneyWiz a bit, remove the not needed info and than the import works without error. Tested it with a small account and that went okay. Going to prep a larger account and look how that goes.

Will report back.

Thanks for now! ;-)

**Comment by BobWs** [comment]
Problem solved! Tweaked the exported CSV file from MoneyWiz and then imported it into Firefly, everything went smooth. 🤑
