### ISSUE TITLE
Blank page after installing on Windows

### ISSUE THREAD

**Issue by LURU85** [firefly-iii/firefly-iii#2738]
I am running Firefly III version 4.8.1.4

**Description**
I'm trying to install firefly using WAMP on windows 10. Installation went pretty good, but when I tried to open firefly (http://localhost/firefly-iii-4.8.1.4/public/) i got a blank page, see screenshot.
![screenshot1](https://user-images.githubusercontent.com/56607441/66861777-eb62e700-ef8f-11e9-9677-d1ad4f612ef9.PNG)
My log file:
[ff3-apache2handler-2019-10-15.log](https://github.com/firefly-iii/firefly-iii/files/3731018/ff3-apache2handler-2019-10-15.log)

Could you please help?

**Extra info**
Windows 10
WAMPserver 3.1.9
Apache 2.4.39
PHP 7.3.5 (during installing PHP 7.2.35 was running, so could that be the issue?)

**Comment by JC5** [comment]
The error tells me that your Apache is configured for PHP7.2

**Comment by LURU85** [comment]
Thanks! It works now
