### ISSUE TITLE
Match Transactions on Different Days

### ISSUE THREAD

**Issue by rafny** [firefly-iii/firefly-iii#2739]
I am running Firefly III version 4.8.1.1

I'm noticing that when I schedule a credit card payment, the CC company posts the payment transaction immediately, but my bank posts the withdraw transaction a few days later when the payment is made.

So now after importing, I have 1 payment from CC -> Bank, but 2 transactions double counting the payment since it's occurring on different dates.

Right now I would have to delete the additional transaction in order to get correct balances. Is there a way that during the import, it can ask to associate 2 transfers of the same amount +/- 3 days from each other as the same transaction?

**Comment by JC5** [comment]
No there isn't, sorry.
