### ISSUE TITLE
Case insensitive transaction form

### ISSUE THREAD

**Issue by houlahaj** [firefly-iii/firefly-iii#2742]
**Description**

I would find it great if the transaction form fields, such as source/destination account etc, were case insensitive in their search. Especially on mobile devices, where the first letter is often autocapitalised and the second lowercase -- this can be a hassle when your account is not found because of differences in capitalisation.

**Solution**

Match account names, categories etc in a case insensitive way.

**What are alternatives?**

Manually paying attention to getting the capitalisation of every letter correct. Not so fun.

**Comment by JC5** [comment]
This is database dependent and Postgres is case sensitive.

**Comment by stickperson** [comment]
@JC5 not sure if I should comment here or open another issue, but Postgres offers case insensitive search. For example, if I change the `LIKE` to `ILIKE` in [this line](https://github.com/firefly-iii/firefly-iii/blob/master/app/Helpers/Collector/GroupCollector.php#L630) then I get case insensitive search for transaction descriptions.

**Comment by JC5** [comment]
Thanks @stickperson. I'm aware of the featur, but unfortunately that only works for postgres, and I need the SQL code to be universally compliant.

**Comment by stickperson** [comment]
@JC5 got it, that's what I figured. I'm not familiar with PHP and wasn't sure if there was a way to determine the database in that area of the code and conditionally use different syntax. Writing other abstraction layers (similar to how the Django does it) for different database backends is a whole other problem.
