### ISSUE TITLE
Show sum of all expenses in Category View

### ISSUE THREAD

**Issue by da4id** [firefly-iii/firefly-iii#2745]
When you go to menu -> Categorys and select a Category
There you can see a with the Title Chart for all transactions for category "Car" between October 1, 2019 and October 31, 2019  and another Chart for all transactions for category "Car".

It would be a nice feature to see the sum of all transaction. It would also be nice to select the timespan. 
This would be a nice feature to see "how much i spend the last year for xy" or "how much i spend for my car since i bought it".

**Comment by JC5** [comment]
You mean the date range in the top right corner, or perhaps the category report?

**Comment by JC5** [comment]
On the left of each category view, you can see the sum for the category per period. This is the period as set in your preferences. If you want more or other details, you'll have to visit the category report.

**Comment by da4id** [comment]
I found what i searched in the Category Report.
