### ISSUE TITLE
Reoccuring transactions not updating acounts 

### ISSUE THREAD

**Issue by woolmonkey** [firefly-iii/firefly-iii#2746]
So when a reoccuring transation happens the accounts page current balance doesn't get updated.  The dashboard graph gets updated the transaction is in the account but it only updates the account current balance when either another transaction is added or if you edit the transaction and save.
Running 4.8.1.4

**Comment by JC5** [comment]
Which balance are you talking about exactly? It's displayed in many places.

**Comment by Tras2** [comment]
Hi,

I've only recently started using your application and I think i've got the same problem as the OP.

I have several recurring transactions, and like the OP, they are working in that the transactions get created.  However, the dashboard graphs do not update and the balances shown when hovering over the graph lines show the old (pre-recurring transaction) balance.

The workaround "fix" is that as soon as any new/edited manually created transaction goes into the system, the graphs and balances on the graphs are updated to be what they should be

Hope this helps

Stuart

**Comment by JC5** [comment]
Thanks. You can browse to /flush in the meantime to manually clear your cache.

**Comment by Tras2** [comment]
Thanks

Is that from the browser (i.e. is it just a local browser cache issue), or could it be added to my Cron job which calls the recurring transaction URL (i.e. it's a backend caching issue)?
