### ISSUE TITLE
Can I manage my investment? Like stock. etf?

### ISSUE THREAD

**Issue by kamanwu** [firefly-iii/firefly-iii#2750]
Just want to know if  I can manage my investment? Like stock. etf?

**Comment by JC5** [comment]
https://docs.firefly-iii.org/support/features

Firefly III will not support stock accounts, investment tracking, real estate or other features besides basic personal finances. If you're looking for something like that, please check out GNUCash.

**Comment by kamanwu** [comment]
Thanks for the reply.   I am using GNUCash now.   
I only can access my GNUCash  data when I am home.  If this works, I will setup my own server so that I can access my data remotely.
