### ISSUE TITLE
All links to docs are failing

### ISSUE THREAD

**Issue by Aphris-Karu** [firefly-iii/firefly-iii#2751]
**Bug description**
I am running Firefly III version x.x.x, and my problem is:
None yet.

All the links to the documentation ether go to an auto generated empty page or return a 404 error.

**Comment by rnsc** [comment]
Looks like the "latest" documentation doesn't work.
When selecting "stable" you get something that works: https://docs.firefly-iii.org

**Comment by JC5** [comment]
I've moved to a new render engine for the Firefly III documentation. This causes old URL's to fail.

Go to the link @rnsc points out to find the page you were looking for.
