### ISSUE TITLE
API: attachment API returns only TransactionJournalId

### ISSUE THREAD

**Issue by michael-v2vlc** [firefly-iii/firefly-iii#2752]
I am running Firefly III version 4.8.1.4

**Description**
Endpoints for attachments return only TransactionJournalId. With this ID, I am not able to find original transaction (endpoint /api/v1/transactions/{id} works only with transaction group ID).

/api/v1/attachments/
/api/v1/attachments/{id}

```
{
  "data": {
    "type": "attachments",
    "id": "1",
    "attributes": {
      "created_at": "2019-10-20T14:00:28+02:00",
      "updated_at": "2019-10-20T14:00:28+02:00",
      "attachable_id": 1,
      "attachable_type": "TransactionJournal",
      "md5": "d5cfead94f5350c12c322b5b664544c1",
      "filename": "empty-file.txt",
      "download_uri": "https://demo.firefly-iii.org/api/v1/attachments/1/download",
      "upload_uri": "https://demo.firefly-iii.org/api/v1/attachments/1/upload",
      "title": "Empty file (title)",
      "notes": null,
      "mime": "text/plain",
      "size": 0
    },
    "links": {
      "0": {
        "rel": "self",
        "uri": "/attachment/1"
      },
      "self": "https://demo.firefly-iii.org/api/v1/attachments/1"
    }
  }
}
```

Since API for attachments is generic (attachments can be added to bill and import job (whatever that is)), it might be difficult to fix this issue without breaking this aspect of the API.

**Comment by JC5** [comment]
That's true, and unfortunately I can't fix this. But a new endpoint in the next release will allow you to request a transaction by one of its journals: `api/v1/journals/x`.

Will go live, with documentation in the next release.
