### ISSUE TITLE
API: downloading attachment without data returns 500

### ISSUE THREAD

**Issue by michael-v2vlc** [firefly-iii/firefly-iii#2753]
**Bug description**
I am running Firefly III version 4.8.1.4 (demo site), and my problem is:

Attempting to download attachment data results in 500 response, when the attachment does not have any data uploaded (or the file uploaded was empty, i.e. 0 bytes).

After proper data (i.e. non-zero size) is uploaded for the attachment, download works fine.

**Steps to reproduce**
Call endpoint to download attachment data:

Currently it's possible to use attachment with ID 3 to reproduce the issue:
/api/v1/attachments/3/download

On "default" demo DB it is attachment 3:
/api/v1/attachments/2/download

**Extra info**
I don't think any extra info should be necessary, but I'll throw in screenshot from Swagger UI:
![api](https://user-images.githubusercontent.com/49870784/67159718-1fdff580-f338-11e9-9d58-87d97400757f.jpg)

**Comment by JC5** [comment]
Thanks for letting me know. I've blocked the ability to upload empty files. There's not much in the way of error reporting yet but it'll give a 422 instead of a 200. Downloading and listing of these files will also throw an error in the next release.
