### ISSUE TITLE
Error when linking Firefly to Memcached

### ISSUE THREAD

**Issue by BobWs** [firefly-iii/firefly-iii#2754]
Hi, I"m getting this error message when trying to link Firefly with Memcached

`Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': Memcached::addServer() expects parameter 2 to be int, string given`

`(1/1) InvalidArgumentException`
`Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': Memcached::addServer() expects parameter 2 to be int, string given`
`in ServiceProvider.php line 236`
`at ServiceProvider->TwigBridge\{closure}(object(Application), array())`
`in Container.php line 785`
`at Container->build(object(Closure))`
`in Container.php line 667`
`at Container->resolve('twig', array())`
`in Container.php line 615`
`at Container->make('twig', array())`
`in Application.php line 767`
`at Application->make('twig')`
`in Container.php line 1227`
`at Container->offsetGet('twig')`
`in Facade.php line 176`
`at Facade::resolveFacadeInstance('twig')`
`in Facade.php line 144`
`at Facade::getFacadeRoot()`
`in Facade.php line 233`
`at Facade::__callStatic('addExtension', array(object(Functions)))`
`in FireflyServiceProvider.php line 92`
`at FireflyServiceProvider->boot()`
`at call_user_func_array(array(object(FireflyServiceProvider), 'boot'), array())`
`in BoundMethod.php line 32`
`at BoundMethod::Illuminate\Container\{closure}()`
`in BoundMethod.php line 90`
`at BoundMethod::callBoundMethod(object(Application), array(object(FireflyServiceProvider), 'boot'), object(Closure))`
`in BoundMethod.php line 34`
`at BoundMethod::call(object(Application), array(object(FireflyServiceProvider), 'boot'), array(), null)`
`in Container.php line 576`
`at Container->call(array(object(FireflyServiceProvider), 'boot'))`
`in Application.php line 827`
`at Application->bootProvider(object(FireflyServiceProvider))`
`in Application.php line 810`
`at Application->Illuminate\Foundation\{closure}(object(FireflyServiceProvider), 31)`
`at array_walk(array(object(EventServiceProvider), object(LogServiceProvider), object(RoutingServiceProvider), object(AuthServiceProvider), object(CookieServiceProvider), object(DatabaseServiceProvider), object(EncryptionServiceProvider), object(FilesystemServiceProvider), object(FormRequestServiceProvider), object(FoundationServiceProvider), object(NotificationServiceProvider), object(PaginationServiceProvider), object(ViewServiceProvider), object(AdldapAuthServiceProvider), object(FlysystemOtherServiceProvider), object(TrustedProxyServiceProvider), object(PassportServiceProvider), object(ServiceProvider), object(ServiceProvider), object(ServiceProvider), object(SessionServiceProvider), object(AppServiceProvider), object(AuthServiceProvider), object(EventServiceProvider), object(RouteServiceProvider), object(AccountServiceProvider), object(AttachmentServiceProvider), object(BillServiceProvider), object(BudgetServiceProvider), object(CategoryServiceProvider), object(CurrencyServiceProvider), object(FireflyServiceProvider), object(JournalServiceProvider), object(PiggyBankServiceProvider), object(RuleServiceProvider), object(RuleGroupServiceProvider), object(SearchServiceProvider), object(TagServiceProvider), object(AdminServiceProvider), object(RecurringServiceProvider), object(ImportServiceProvider), object(ValidationServiceProvider), object(TranslationServiceProvider), object(CacheServiceProvider), object(HashServiceProvider)), object(Closure))`
`in Application.php line 811`
`at Application->boot()`
`in BootProviders.php line 17`
`at BootProviders->bootstrap(object(Application))`
`in Application.php line 210`
`at Application->bootstrapWith(array('Illuminate\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'Illuminate\\Foundation\\Bootstrap\\LoadConfiguration', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))`
`in Kernel.php line 162`
`at Kernel->bootstrap()`
`in Kernel.php line 146`
`at Kernel->sendRequestThroughRouter(object(Request))`
`in Kernel.php line 116`
`at Kernel->handle(object(Request))`
`in index.php line 76`

I have at this to the environment in Docker Firefly:
`SESSION_DRIVER=memcached`
`CACHE_DRIVER=memcached`
`CACHE_PORT=11211`

Any idea what I'm doing wrong?

**Comment by JC5** [comment]
All I can do is push a fix that will *probably* fix this in the next version.

**Comment by BobWs** [comment]
Okay thanks! I'll wait for the next version.
