### ISSUE TITLE
Inactive Rule being applied

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2755]
**Bug description**
I am running Firefly III version 4.8.1.4, and my problem is:

I have inactivated some rules that apply a budget, but they are still applied to my transactions.

**Steps to reproduce**
Create a budget
Create a rule that applies that budget (on update)
Create a transaction (blank budget)
Update the transaction (blank budget, change the amount)
See your budget on transaction
Inactivate your rule
Update the transaction - altering it to something else
Old budget is applied back

**Comment by JC5** [comment]
Nice find, that's a bug. Will be fixed in the next release.
