### ISSUE TITLE
Search is not working after upgrade to 4.8.1.5

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2756]
**Bug description**
I am running Firefly III version 4.8.1.5, and my problem is:

when I click on search, it gives me this message:

`array(0) { }`

**Steps to reproduce**
click search link (search?search=)

**Comment by JC5** [comment]
Thanks! Must have forgotten a debug statement. Sorry about that. A bit sloppy.

A fix is in the `develop` branch and if nothing else pops up will go live before the weekend.
