### ISSUE TITLE
artisan route list throws an error

### ISSUE THREAD

**Issue by lguima** [firefly-iii/firefly-iii#2758]
**Bug description**
I am running Firefly III version 4.8.1.5, and my problem is:

Running `php artisan route:list` inside the container throws an error:

> In Container.php line 788:
> Class FireflyIII\Http\Controllers\Transaction\CloneController does not exist

**Steps to reproduce**
Run the command inside the container.

**Comment by JC5** [comment]
It's because the route configuration contains routes no longer used. I'll remove them.
