### ISSUE TITLE
Header a bit  of a mess on Accountspage (See screenshots)

### ISSUE THREAD

**Issue by BobWs** [firefly-iii/firefly-iii#2760]
**Bug description**
I am running Firefly III version 4.8.1.4 , and my problem is:

Hi,
On the Accountspage when selecting an Expenses account for details I see this (see screens):
This is what I see on my browsers (safari/FireFox/Waterfox, Windows and Mac)

![Accounts-Firefly III-browser](https://user-images.githubusercontent.com/5485820/67286824-581f3980-f4da-11e9-8abf-be6cbf25099f.png)

This is what I see on my tablet (IOS):
![Accounts-Firefly III-ipad](https://user-images.githubusercontent.com/5485820/67286723-302fd600-f4da-11e9-8f8c-10fa9baf94cc.jpg)

And this is what I see on my phone (ios):
![Accounts-Firefly III](https://user-images.githubusercontent.com/5485820/67286776-450c6980-f4da-11e9-9d0d-7d1ba93fa7e1.png)

As you can see on my phone everything shows up good and readable.
Is it possible  to fix this So it is all over readable on tablet and browser?

Thanks!

**Comment by GaryQ** [comment]
I wouldn't count on it being fixed unfortunately. Issue was raised at least twice. Response is in this issue thread
https://github.com/firefly-iii/firefly-iii/issues/2649#

After reading the response I simply modified the page to relocated and renamed the breadcrumb class into a separate box below it and added css code to end of his css file to resolve the issue. Haven't tried it on any other devices other than PC. Some people are older (hint me) and even on a 55" screen need text a bit bigger and too much overlaps too often his way.

Making some other mods and writing an app to automate the changes from version to version. 

![Annotation 2019-10-22 104054](https://user-images.githubusercontent.com/3269694/67303883-ade2ea00-f4b8-11e9-9952-2c5c2c17f553.JPG)

**Comment by JC5** [comment]
I'll see what I can do to make it look better.
