### ISSUE TITLE
Add the ability to change categories from within the Expense/Revenue accounts page/list

### ISSUE THREAD

**Issue by BobWs** [firefly-iii/firefly-iii#2761]
Hi,
If I may make a suggestion, it would be nice if you could have a checkbox in the Expense and Revenue accounts to create or change the categories. For example, it would be more efficient to change bulk categories. 

Now you have to first click on an "Expense/Revenue account" and then again on "show all transactions without grouping by date". Only then do you have the possibility to change or create categories.

From within the Expense/Revenue accounts page you would be able to tick multiple accounts that have the same category and then immediately change them. This would save a lot of time if you have a lot of accounts you want to categorize.

Thanks for your great work!

**Comment by JC5** [comment]
Similar suggestions have been made in the past, and I'm still looking for the best way to do this. I'm going to close this issue in favor of #2617.

In the mean time, play around with rules. With the correct trigger you can quickly correct all of your transactions.

**Comment by BobWs** [comment]
I have tried to do that with rules and triggers but than I keep getting a message that nothing matches the latest 200 transactions. So the problem with rules is that it isn’t looking further in time than the last 200 transactions.

**Comment by JC5** [comment]
It only goes back 200 transactions when you run it as a test. So when the rule is tested, it only checks the top 200 transactions.

When you fire it for real, it will hit all of your transactions.
