### ISSUE TITLE
Add the option to go directly to a certain letter of the alphabet in the accounts list.

### ISSUE THREAD

**Issue by BobWs** [firefly-iii/firefly-iii#2762]
Hi, 
It would be nice if you have the possibility to go directly to a specific account in the Revenue/Expense accounts list, by being able to click on a letter of the alphabet at the top of the page. (See screenprint)

![Screen Shot 2019-10-22 at 15 19 42](https://user-images.githubusercontent.com/5485820/67290649-b4855780-f4e0-11e9-8bd9-b82b82fb003f.png)

Thanks for your great work!

**Comment by pc-zookeeper** [comment]
+1 for this.  I was actually thinking of submitting this suggestion myself.

I have some expense account names that start with a number, so something like "# A B C ..." would be nice.

**Comment by JC5** [comment]
I'm not a fan to be honest. It would make the header crowded and messy. I was thinking of adding some kind of a search option as suggested in #1268.

**Comment by pc-zookeeper** [comment]
What if the alphabetized pagination replaced the currently existing numbered pagination to keep the look cleaner?
