### ISSUE TITLE
How do I know if the Memcached is working?

### ISSUE THREAD

**Issue by BobWs** [firefly-iii/firefly-iii#2763]
Hi,
How do I know if the Memcached is working?
I have added this to my docker env:

SESSION_DRIVER=memcached
CACHE_DRIVER=memcached
MEMCACHED_PORT=11211
MEMCACHED_HOST=memcached

I didn't get the error as #2754 and I could login normal, but I don't see anything in the logs about memcached nor any activity in the logs of Memcached?

**Comment by JC5** [comment]
Good question. It depends on your system. Are you using Docker? I don't think it comes with the memcached package to be honest, I'll check it out.

**Comment by BobWs** [comment]
Yes I’m using Docker.

I have run some test’s to see if it is working, so when I turn off the memcached container and try to login I get an error page 419. After turning on the memcached container again I can login and everything works normal. So I guess the memcached is working somehow...

**Comment by JC5** [comment]
That's weird :grin:

Give me to to dive into the problem, I hope to get back to you soon.

**Comment by BobWs** [comment]
Okay

**Comment by JC5** [comment]
There's not much for me to fix here. Memcached support is present and it *should* work. I can't tell you much more at the moment, sorry about that.
