### ISSUE TITLE
Liability Accounts in the Overview

### ISSUE THREAD

**Issue by TechRabb1t** [firefly-iii/firefly-iii#2768]
I am running Firefly III version 4.8.1.4

Hello,
quick question, shouldn't the Liability Accounts be visible on "Your Accounts" or wherever the Account balances are shown, for example in the Net Worth shortcut etc.?

Thanks in advance and kind regards

**Comment by JC5** [comment]
Good question. At the moment, the report that link goes to can't really handle them. You can safely include them in the URL like so:

https://demo.firefly-iii.org/reports/default/1,5,39/20190101/20191231

You replace the "allAssetAccounts" with individual accounts. In this example, 39 is the liability. If you follow the link you'll see it works.

However, the liability's transactions won't be included in the report. That's an enhancement that's still necessary. I'll write it down.

**Comment by TechRabb1t** [comment]
Thanks for your reply and the temporary workaround, much obliged.
It might be a nice addition to have something like a Liability Report which only shows the liability accounts with their starting value/transactions and some nice graphs. I know a lot of people who struggle with their different loans, debts etc. and it motivates them to see the declining overall debt.

But obviously that would just be QoL and I bet there are bigger issues who need to be done :)

**Comment by JC5** [comment]
This will be fixed in the next release.
