### ISSUE TITLE
Foreign Currency Field in Transaction

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#2769]
Firefly III version 4.8.1.6

I thought this issues was resolved?
I have 2 Currencies. All others deleted. 
Only 1 currency Default and enabled CAD. 
No transactions entered. 
Yet the new transaction form always spots a foreign currency field with a select box (Only C$ available)

![currency](https://user-images.githubusercontent.com/3269694/67612822-ee1dc300-f76b-11e9-82e2-79f7db22ca6e.JPG)

![transaction](https://user-images.githubusercontent.com/3269694/67612823-f83fc180-f76b-11e9-8bbc-6fb525ee2896.jpg)

**Comment by JC5** [comment]
Indeed, I'll check it out.

**Comment by JC5** [comment]
Should be fixed, check out the demo site.
