### ISSUE TITLE
Piggy bank linked to a recurring transaction transfer is not updated

### ISSUE THREAD

**Issue by p4PpS** [firefly-iii/firefly-iii#2771]
**Bug description**
I am running Firefly III version 4.8.1.6, and my problem is:

The amount of associated piggy bank will not be updated after the recurring transaction is triggered.

**Steps to reproduce**
1. Create a recurring transaction (type: transfer) and select a piggy bank
2. Wait for cron

**Extra info**
Tested with your docker-compose.yml example.
Table recurrences_meta stays empty, maybe this is an indicator?

**Comment by JC5** [comment]
Thanks, this is a bug, I'll check it out :)

**Comment by JC5** [comment]
If there is an entry in table `rt_meta` for the piggy bank you selected, this will work in the next release of Firefly III.
