### ISSUE TITLE
"Undefined index: error_if_duplicate_hash" on command line import

### ISSUE THREAD

**Issue by cirilloblu** [firefly-iii/firefly-iii#2773]
**Bug description**
I am running Firefly III version 4.8.1.7
the docker version tag: latest
docker hub digest version: 3e9dc7b40ec6

**and my problem is:**

When try to import data with 

`docker exec money_firefly_iii_app_1 php artisan firefly:csv-import #{file}.csv import-configuration.json --token TOKEN`

it crash with:

```
The import routine has started. The process is not visible. Please wait.
Import has finished. Please wait for storage of data.
The import routine crashed: Undefined index: error_if_duplicate_hash
```

**Extra info**
- docker on amd64
- Worked before the update

**Comment by xyrob** [comment]
I am experiencing the same issue when importing from the web interface as well after updating.
Digest: sha256:3155fcda01df15d78cd880ecf3a6fb0a225f677ea277db99777cbd7ec2eb7967
Version: 4.8.1.7

"Job could not be started or crashed: The import storage routine crashed: Undefined index: error_if_duplicate_hash"

**Comment by JC5** [comment]
Noted, and this will be fixed in the next release. Thanks for letting me know.

For the time being, you can switch to the `develop` tag.
