### ISSUE TITLE
Update transaction does not add port to url

### ISSUE THREAD

**Issue by eraelpeha** [firefly-iii/firefly-iii#2774]
**Bug description**
I am running Firefly III version 4.8.1.7, and my problem is:

I've got a docker installation with firefly, running it on port 8089. If I edit a single transaction and hit the update transaction button, the page redirects me to the 404 page of my other application that's using port 80. It looks like the port 8089 in the url is missing.

**Steps to reproduce**
Run firefly-iii on a different port than 80.
Edit a single transaction, hit the update transaction button

**Extra info**
firefly-iii in a docker environment on port 8089 and another application that is using port 80.

**Comment by JC5** [comment]
I pushed a possible fix to the "develop" tag on Docker. As [soon as it's done building](https://travis-ci.com/firefly-iii/firefly-iii/builds/133672047) could you try this tag to see if it works?

**Comment by eraelpeha** [comment]
> I pushed a possible fix to the "develop" tag on Docker. As [soon as it's done building](https://travis-ci.com/firefly-iii/firefly-iii/builds/133672047) could you try this tag to see if it works?

Just tested it and it works like a charm!
