### ISSUE TITLE
Net worth

### ISSUE THREAD

**Issue by planck0** [firefly-iii/firefly-iii#2775]
On my dashboard I see a figure representing net worth on the top right, as asset accounts minus liabilities. However, if I click on the 'net worth' link, I get the default report which a bit down includes a graph which is also is named "net worth" but only adds up asset accounts and doesn't subtract liabilities. 

I am actually interested in both, a graph for the combined asset accounts, and a graph for the combined asset account minus liabilities. Can I somehow get both graphs on one screen? I would love to see both graphs on my dashboard, because they are the main things I am interested in (the trends of both graphs, mostly).

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2768
