### ISSUE TITLE
Relative and absolute scaling

### ISSUE THREAD

**Issue by planck0** [firefly-iii/firefly-iii#2776]
Currently, my graph for liabilities contains my mortgage. This is a large number. If I look at the graph it looks mostly like a straight line, because my monthly repayments are quite small compared to the absolute number. Even though the absolute graph (starting from 0) is interesting in itself, I would also be able to see the graph where the max and min value on the scale are not much greater than the max and values in that period. 

- I would like Firefly III to do add the option to switch from absolute to relative scales in linegraphs.

**What are alternatives?**
Add a preference for absolute and relative scales in preferences.

**Comment by JC5** [comment]
I'll see what I can do.

**Comment by JC5** [comment]
I can only fix this for the `/accounts/show/*` overview at the moment, but let me know where else this might be useful so I can consider it.
