### ISSUE TITLE
Being redirected to HTTPS when adding the transactions

### ISSUE THREAD

**Issue by kaosmonk** [firefly-iii/firefly-iii#2777]
Info on my installation:

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-10-01 00:00:00 |
| Session end | 2019-10-31 23:59:59 |
| Session first | 2019-09-23 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Description**
I am running the Docker container with the tag latest and 10 days ago things started acting strangely. I am running no proxy in front of my Firefly but accessing it via IP address of a box container runs on: http://10.10.10.10:9000 (HTTP port inside a container is bound to 9000 on the host box). Two things I have noticed:
- It sometimes triggers the install procedures when I access it via the above URL (I clearly see 302 HTTP code in the logs that redirects me to `http://10.10.10.10:9000/install`)
- When I try to add a new transaction and submit it, it redirects me to: https://10.10.10.10 which then throws an error since there's no HTTPS configured and port 9000 is missing. Transactions is saved nevertheless since it's enough to hit `back` in my browser to verify the transaction is there.

I see no clues in Apache or app logs whatsoever to why it redirects me to HTTPS when config hasn't been changed ever since I got it up and running months ago.

**Extra info**
I also see this when I visit `/debug` but am not sure of the message there is current or not:
```
Truncated from this point <----|[2019-10-27 09:34:45] local.WARNING: The current configured Firefly III version (4.8.1.6) is older than the required version (4.8.1.8). Redirect to migrate routine.  
[2019-10-27 09:34:45] local.WARNING: Database entry exists. Update to latest version (11)  

```

Any hints how to troubleshoot it further?

Cheers!

**Comment by JC5** [comment]
For the second one: https://github.com/firefly-iii/firefly-iii/issues/2774

The first one I'll have to do some digging.
