### ISSUE TITLE
Seeing "Fatal Error" after restoring local database on Heroku

### ISSUE THREAD

**Issue by stickperson** [firefly-iii/firefly-iii#2778]
I am running Firefly III version 4.8.1.8

**Description**
I was running Firefly locally using Docker and then read that I could use Heroku. Since I already had some data, I thought it would be nice to back up the database in the docker volume and restore that on Heroku. I made sure to update my docker image to `4.8.1.8` as well before making the database dump. Here are the commands I ran:

- Created dump. `docker exec firefly_firefly_iii_db_1 pg_dump -Fc --no-acl --no-owner -h localhost -U firefly firefly > mydump.db` from [the heroku docs](https://devcenter.heroku.com/articles/heroku-postgres-import-export#create-dump-file)
- Restored dump: `heroku pg:backups:restore '<SIGNED URL>' DATABASE_URL`

When I tried to restore the dump I got the following message:

```
Restoring... !
 ▸    An error occurred and the backup did not finish.
 ▸
 ▸    pg_restore: creating FK CONSTRAINT "public.transactions transactions_transaction_journal_id_foreign"
 ▸    WARNING: errors ignored on restore: 197
 ▸    pg_restore finished with errors
 ▸    waiting for download to complete
 ▸    download finished successfully
 ▸
 ▸    Run heroku pg:backups:info r007 for more details.
```

I ran that command and got the [following logs](https://gist.github.com/stickperson/502f75168cce47afec103c270917015c) but everything looks normal to me.

After trying to access the site I see the message `There was a fatal error. Please check the log files.`. [Here](https://gist.github.com/stickperson/8124860adef963823471b2df4f98a8eb) are a bunch of logs. Lots of messages about `Command... will not execute`. There's also a weird one `heroku.ERROR: The MAC is invalid. {"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The MAC is
invalid. at /app/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:199)`

**Extra info**
Let me know if you need any more information. Thanks!

**Comment by stickperson** [comment]
Ok I was being dumb. I didn't update `APP_KEY` when I initially created my container. If I kill/remove the containers now, set the `APP_KEY` to the one provided by Heroku and start the containers, I see the same `The MAC is invalid.` error locally. Is there any way around this?

**Comment by JC5** [comment]
All I can think of is that it's cache related. Or perhaps data in the preferences table. As you point out, nothing should be encrypted.
