### ISSUE TITLE
Bug? Deleted budget counts towards total budgeted

### ISSUE THREAD

**Issue by rnck** [firefly-iii/firefly-iii#2780]
I am running Firefly III version 4.8.1.8, and my problem is:

Budgeted amount of deleted budget still counts towards total budgeted.

**Steps to reproduce**
Create a new budget, set amount to 1000, total budgeted will increase by 1000, delete budget. Total budgeted stays at x + 1000.

** Expected beahavior**
Total budgeted will be without the amount of the deleted budget.

Is there at least a way to fix this by hand? On the other hand I think manipulating the database may not be a good idea.

Screenshots from demo site:
Test budget set to 1000:
![test budget set to 1000](https://user-images.githubusercontent.com/165663/67716538-4e12a480-f9cc-11e9-8ffc-4d2df3fc20a4.jpg)

After deletion of budget "test" total is still 1000 although there are no budgets anymore:
![after deletion](https://user-images.githubusercontent.com/165663/67716579-64b8fb80-f9cc-11e9-86c3-85afb5938bc7.jpg)

**Comment by rnck** [comment]
Well, I undeleted some budgets by updating the database (deleted_at = NULL). After that I set the budget for current month to zero. All fine now.

Apparently it should be better to set a budget to inactive, when it is not needed anymore.

**Comment by JC5** [comment]
No, deleting the budget should delete the amounts as well. Or at least, exclude them. Thanks for letting me know

**Comment by JC5** [comment]
Will be fixed in the next release.
