### ISSUE TITLE
[F-R] Add `DB_Socket` to overall config.  

### ISSUE THREAD

**Issue by Herve-M** [firefly-iii/firefly-iii#2781]
Hello,

**Description**
It would be cool if the `DB_Socket` setting is acessible and usable, in case of the setup with Docket but (metal bar) database, sharing a socket is the easiest and maybe secure as sharing all local port. 

**Solution**
Seem that mostly everything is settup [here](https://github.com/firefly-iii/firefly-iii/blob/f4b9f81e7149cdafa951b0c9251cdfb7506f2177/config/database.php#L58) but it miss the config. test as: if DB_Socket is set, not need of DB_Host + DB_Hostname.

**Additional context**
For Docker context, with a local DB, it make it easier to setup.
For normal setup, access through a socket could me more easy to secure on the system. 

Thanks,
Hervé-M

**Comment by JC5** [comment]
As far as I can tell from Laravel's code, it's enough to set DB_SOCKET and leave DB_HOST empty. Did you try that already?
