### ISSUE TITLE
Income vs expenses chart under Reports gives 500 error

### ISSUE THREAD

**Issue by Syakyr** [firefly-iii/firefly-iii#2783]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is:

Having no chart being produced at the income vs expenses section when I generate a report.

**Steps to reproduce**
1. Go to the Reports tab.
2. Key in date range (2018 Jan 1 - 2019 Dec 31 for my case) and select all accounts available to generate the report. Report type is Default Financial Report.
3. Click Submit under View Report section.

**Extra info**
Debug information generated at 2019-10-29 16:56:25 Asia/Singapore for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.11-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-10-01 00:00:00 |
| Session end | 2019-12-31 00:00:00 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | sqlite |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**
You will get this under the Income & Expenses section.
![Screenshot from 2019-10-29 17-00-32](https://user-images.githubusercontent.com/23415399/67752611-3e4b9c80-fa6e-11e9-8d09-655a55463ef9.png)

When I inspect the page I get this 500 error:
![Screenshot from 2019-10-29 17-04-17](https://user-images.githubusercontent.com/23415399/67752627-44417d80-fa6e-11e9-96e6-3dd9c5a1d3a5.png)

Clicked the site I'm supposed to receive and I get this error message:
![Screenshot from 2019-10-29 17-04-32](https://user-images.githubusercontent.com/23415399/67752640-47d50480-fa6e-11e9-97f1-e76e5cd29ab4.png)

**Comment by JC5** [comment]
Try to avoid using SQLite. I've fixed this one but you might run into other issues down the line.

**Comment by Syakyr** [comment]
Thanks for the fix! Will pull it soon.

I think these bugs are somewhat minor, and I could contribute to making sqlite integrated a little better for firefly, so I'm continuing to use sqlite as my database driver.

I think for an app like firefly that focuses on mainly single-user experience, to use sqlite as the main database driver is good, making the app self-contained.

**Comment by JC5** [comment]
There is a root problem that is difficult to fix. All integers are cast to strings. Not sure what the cause is. But whenever I use database values directly, it breaks with SQLite.
