### ISSUE TITLE
Error after upgrading docker container

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#2788]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is:

For quite some time already each time I upgrade my firefly docker instance at first page load I get the Firefly installation and upgrade which execute commands.
And each time it get stuck showing "Just executed firefly-iii:delete-empty-groups..." then shows "Command failed! See log files :("

If I remove the /install from my URL I get my regular page and I can work on firefly...
I checked my container logs but I have nothing special, so really difficult to know what is going wrong to help debug...

**Steps to reproduce**
Looks it's maybe linked to my own setup as I don't see anyone else reporting this...
How can I help^provide more info?

**Extra info**
I'm running Firefly on a docker running in a Synology NAS.

**Comment by JC5** [comment]
Tricky. I know the Docker's logs aren't properly pushed to the stdout, making it difficult to debug.

I'll keep this open as a bug and work on that so we can debug this together.

**Comment by MacPaille** [comment]
If there is a way to provide you more debug information please share :)

**Comment by JC5** [comment]
There isn't yet, but I hope to change the docker image so this is the case.

As for your question. A few more commands:

https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/System/InstallController.php#L100

**Comment by JC5** [comment]
The `develop` branch now has more expansive error reporting. If you launch your Docker container with the following environment variables, you should see some reporting in the "fix-account-types" command that seems to be giving you troubles.

`-e LOG_CHANNEL=docker_out APP_LOG_LEVEL=debug`

Wait for [this page](https://travis-ci.com/firefly-iii/firefly-iii/builds/134658957) to be green then you should be able to use the `jc5x/firefly-iii:develop` tag with these enhancements.

**Comment by MacPaille** [comment]
I would like to avoid using the apha versions :) so I already set the 2 environment variables and will provide you more input once that release comes to stable :)

Anyway it's not a blocking bug for me as reloading the page without the /install works.

**Comment by MacPaille** [comment]
Small update to avoid closing.

**Comment by MacPaille** [comment]
Just updated to 4.8.2 and the install page does not appear anymore :)

**Comment by JC5** [comment]
Glad to hear it!
