### ISSUE TITLE
Show future transactions

### ISSUE THREAD

**Issue by erdnussflips** [firefly-iii/firefly-iii#2789]
**Description**
- I would like Firefly III can show future recurring transactions in the graphs and transaction tables

**Solution**
- Show future recurring transactions.
- They should be greyed out until they are executed by firefly's cronjob

**What are alternatives?**
- I'm not aware of an alternative.

**Additional context**
none

**Bonus points**
none

**Comment by JC5** [comment]
No. When they're not created yet I can't show them.

**Comment by Zamana** [comment]
I would like to have this feature too.

As an alternative, is it possible to turn "bills" into "recurring" transactions, but with changeable values each month?

The main target is avoid the need to record/write every bill every month...

Thanks.
Regards.
