### ISSUE TITLE
Inconsistent behaviour with decimals in the transaction form

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2790]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is:
I'm using Firefly via the official Docker image, and running it under the french locale.
I'm using EUR as my default currency, with 2 decimals.
I'm using Chrome.

When adding a withdrawal
1. Without selecting any account, the "Amount" field is not restricted to any formatting
2. However the "Foreign amount" field is auto-formatted using the browser locale settings, which causes some strange behaviour.
  a. In french, the decimal separator is the comma, which is *very impractical* when you are used to use a dot for decimals. When using the comma, everything works as expected, however when you use a dot, it resets the filed to 0.
![2019-11-01-firefly-iii-decimals-01](https://user-images.githubusercontent.com/1266495/68023131-ac7aa400-fca6-11e9-9a87-f5f9a206eb8c.gif)
  b. The amount of decimals configured in the currency is not enforced
![2019-11-01-firefly-iii-decimals-04](https://user-images.githubusercontent.com/1266495/68023858-c321fa80-fca8-11e9-9ce1-16cd2fd071a9.gif)
3. When selecting a source account, I'm assuming that it knows which currency is used, but the "Amount" field remains free form
![2019-11-01-firefly-iii-decimals-02](https://user-images.githubusercontent.com/1266495/68023532-a9cc7e80-fca7-11e9-96c8-ddb8509445b4.gif)
4. When selecting a source and destination account, the "Amount" field remains free form (see 3.)
5. When selecting a source and destination account in the same currency, the "Foreign amount" field behaves like 2.
![2019-11-01-firefly-iii-decimals-03](https://user-images.githubusercontent.com/1266495/68023807-9ec61e00-fca8-11e9-926f-7a448bcb4c8d.gif)
6. When selecting a source and destination account in a different currency, the "Foreign amount" field behaves like 2.
![2019-11-01-firefly-iii-decimals-05](https://user-images.githubusercontent.com/1266495/68024039-42173300-fca9-11e9-9d8c-62a678d7ea72.gif)
7. When editing an already existing transaction or split transaction
  a. The currency is not displayed
  b. The number of decimals is not matching the transaction currency
  c. Clicking on the digits place the cursor in a shifted position compared to where I clicked
  d. Using the arrows will enforce the number of decimals
  e. ...but you can still add some more afterwards
  f. Using a dot won't reset the field to 0
  g. ...however using the arrow after will catch the invalid number format, reset to 0 and increment it
![2019-11-01-firefly-iii-decimals-06](https://user-images.githubusercontent.com/1266495/68024252-d7b2c280-fca9-11e9-8ba3-3d08b73d8f47.gif)

**Steps to reproduce**
2. a. Press the dot key when using a locale expecting comma as the decimal separator
7. c. Create a transaction, edit it, click on the amount with lots of decimals, the cursor won't match your click
7. d. Create a transaction, edit it, click the up arrow
7. e. Same as d. but type some stuff after it resetted to 2 decimals
7. g. Use a completely wrong format in the field and press the arrow

**Extra info**

Debug information generated at 2019-11-01 13:22:06 Europe/Paris for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2003-04-24 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**
Looks similar to #2626 but for transaction forms.
Also it seems that the translation for `firefly.split_transaction_title_help` is missing when editing a split transaction.
![image](https://user-images.githubusercontent.com/1266495/68024636-f2396b80-fcaa-11e9-9c07-652a3fe5ffd1.png)

**Comment by JC5** [comment]
Thanks for the expansive bug report!

1. The input is of type "number" with any step, and that's all the format limiting I'm prepared to do. It depends on your browser what that will entail.
2. I see what you mean. I'm not sure what the cause is. Pressing "a" for example clears the form. Thats _not_ intended behavior. I'll look into it.
3. Yes. That won't change. Feel free to submit more decimals.
4. Yes. That won't change. Feel free to submit more decimals.
5. I don't know what you mean by this. Could you explain?
6. Same. 

Regarding point 7.

a. I'll make sure the currency is visible in the future.
b. Yes, numbers like "23.00" may display "23". That depends on the number that's stored in the database and your browser, and .10 and .00 will not always be displayed with the right number of decimals.
c-g. All this behavior comes from the inconsistent behavior of the currency field. I'll work on it.

Thanks!

**Comment by gregoo** [comment]
Hello, thanks for looking at all this.
Basically from 2 to 6 I was just testing if some specific behaviour was already implemented in terms of currency checks in the form depending on the Source and Destination selected.
So I tested
- Empty field
- Only Source
- Source & Destination in the same currency (EUR -> EUR)
- Source & Destination in a different currency (EUR -> USD)

(-:

**Comment by JC5** [comment]
I've pushed some changes to the form. It should be more consistent now. Check out the demo site (make sure to clear your cache).

**Comment by gregoo** [comment]
I've checked the demo website but it seems like the changes are not propagated yet. It's displaying the same behaviour as before, and also some with some strange tooltips (https://demo.firefly-iii.org/transactions/edit/3)

![image](https://user-images.githubusercontent.com/1266495/68543486-f86ccd80-03b7-11ea-873b-f97276fc79d3.png)

**Comment by JC5** [comment]
I'll check it out. But like I said before, the multi-decimal thing will not be fixed.

**Comment by gregoo** [comment]
Got it.
If I'm tired of Chrome being smart about that, I'll switch over to Firefox. I don't have this wonky behaviour there (-: . So yeah in the end it's the browser that needs fixing not your code.

![image](https://user-images.githubusercontent.com/1266495/68543735-7f6f7500-03bb-11ea-8a68-61fb0dfd5d8b.png)
