### ISSUE TITLE
Keep getting an error when importing data into Firefly

### ISSUE THREAD

**Issue by BobWs** [firefly-iii/firefly-iii#2792]
I am running Firefly III version 4.8.1.8

Hi,
I'm keep getting an error when importing into FireFly (see sreenprint)

![Screen Shot 2019-11-04 at 16 02 21](https://user-images.githubusercontent.com/5485820/68131449-61b69180-ff1d-11e9-99c8-abbf97ef55f0.png)

Any idea how to solve this?

**Comment by JC5** [comment]
Thanks. Not sure what the cause is, I'll do some debugging.

**Comment by JC5** [comment]
Is there anything in your logs? I can't seem to replicate this.
