### ISSUE TITLE
First alpha release is live.

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#2794]
As suggested by @GaryQ in #2719 Firefly III is moving to a system where there is a separation between different Firefly III versions. There will be a stable, beta and alpha "channel".

Stable versions are guaranteed to work and have the least amount of bugs. BETA versions may have new features that won't work as well as you'd expect them to. ALPHA versions will contain the newest features, but may also contain code that breaks or crashes.

To 'celebrate' this change I've just released a page where you can see which version is the latest version for each channel: **[version.firefly-iii.org](https://version.firefly-iii.org/)**.

Here you can see that the latest stable and beta releases are the same, but also that a new **alpha** version has just been released: **4.8.2-alpha.1**.

This new alpha version is capable of doing update checks on a specific channel, allowing you to choose which channel you would like to get your updates from:

<img width="570" alt="Screenshot 2019-11-05 at 17 52 26" src="https://user-images.githubusercontent.com/5889984/68228068-ae1cd280-ffec-11e9-9fc2-a071b4efa339.png">

This will be reflected in the version number, of course:

<img width="220" alt="Screenshot 2019-11-05 at 17 52 06" src="https://user-images.githubusercontent.com/5889984/68228083-b412b380-ffec-11e9-8dae-2405d81215a2.png">

If you are on any version of Firefly III **<= 4.8.1.8** you may receive a notification about this new alpha version. Those versions of Firefly III won't be able to differentiate between the three channels.

If you just got an alert about a new version, feel free to ignore it. Your Firefly III installation will continue to alert you about new alpha and beta versions, because it won't be able to see the difference. Feel free to ignore the updates. I apologize beforehand for the "version spam".

For everybody else, whether or not you are on an alpha or beta channel affects the number of issues you may encounter. Always mention this when you submit a new ticket.

Thanks!

**Comment by hamfactorial** [comment]
Great idea!  I'm looking forward to trying out the three flavors and seeing which edge I'd like to live on.

Are there API or database schema changes that might prevent an :alpha installation from moving back to a :beta or :stable?  Is there a field in the version number that's API/schema-locked?  For example 4.8.X is compatible across releases, but 4.X isn't.

**Comment by GaryQ** [comment]
That’s a great question!
According to semver..

1. There’s a dot too many lol
2.   1.0.x should be bug stomping only
3.   1.x.0 should not have any breaking changes. 
4   x.0.0 is where any breaking changes should reside. Database schéma changes ii would consider a breaking change.

Of course that is a guideline only but when it’s followed it’s easy to know what to expect.

As for where on the Clive to live: Stable.
You should clone your DB and play close to the edge with beta and right on the edge with alpha. If you fall it don’t hurt your original data

Just my C$ 0.02 as usual

**Comment by JC5** [comment]
Where’s the dot too many? The site shows “ 1.0.0-alpha.1” as a correct example.

**Comment by GaryQ** [comment]
Sorry, my bad was referring to previous versions. 4.8.1.8 that’s one too many.

Keep up the good work
