### ISSUE TITLE
After switch to Chinese it keeps alerting me the server lacks necessary kits 

### ISSUE THREAD

**Issue by FanyangMengDev** [firefly-iii/firefly-iii#2798]
**Bug description**
I am running Firefly III version 4.8.2-alpha.1 and my problem is:
After I switch the language to Chinese, it keeps alerting me that the server lacks the neccessary kits, so I open the link in the blue box I found that you tell us in the doc that we should install language pack 
So I install zh_CN base and change it to it.(Which I really do not want to because sometimes it will cause some problems)
But after I do that and restart the Nginx, it still alerts me this. Why this would happen?

And the month also displays in English.

And I really do not know that why there is a sentence just next to the 'Firefly III' which is '吃饱没'. What the hell is that? That means 'Have you eat enough food?' or 'Are you full'? We do not say hello like this in China, this translation is really stupid and foolish. Please change it in the release.

What's more, the SMTP cannot works well. I have already configure it in the .env file but nothing I have received.

I would like to donate to you but this Chinese translation and wrong displaying makes me feel so bad. If it can be solve I would like to donate.

**Steps to reproduce**
Just switch to Chinese after installed
I change the display of Chinese yuan from '元' to '￥' because this is the 'yuan' 's symbol, not yen

Even if using '元', it should display after the number because in China we do not display currencies by putting '元' in front of the number

**Extra info**
Ubuntu 18.04 LTS 
Debug information generated at 2019-11-06 11:26:23 Asia/Shanghai for Firefly III version **4.8.2-alpha.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2-alpha.1 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , docker_out |
| PHP version | 7.3.11 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-11-06 04:35:37 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.90 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, sodium, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, cgi-fcgi, zip, fileinfo, apcu, imagick, exif, imap, pgsql, pdo_pgsql, ldap, Zend OPcache |

**Bonus points**
![Screenshot_2019-11-06-11-20-13-325_com android chrome](https://user-images.githubusercontent.com/53750381/68265577-73b44380-0087-11ea-9873-563892d65dda.jpg)

**Comment by JC5** [comment]
> After I switch the language to Chinese, it keeps alerting me that the server lacks the neccessary kits, so I open the link in the blue box I found that you tell us in the doc that we should install language pack
So I install zh_CN base and change it to it.(Which I really do not want to because sometimes it will cause some problems)
> But after I do that and restart the Nginx, it still alerts me this. Why this would happen?

> And the month also displays in English.

Please restart your PHP service as well, if you run FPM.

> And I really do not know that why there is a sentence just next to the 'Firefly III' which is '吃饱没'. What the hell is that? That means 'Have you eat enough food?' or 'Are you full'? We do not say hello like this in China, this translation is really stupid and foolish. Please change it in the release. 

I would appreciate any feedback on the translations [on Crowdin](https://crowdin.com/project/firefly-iii) where you can suggest better translations.

> What's more, the SMTP cannot works well. I have already configure it in the .env file but nothing I have received.

Is there an error in your logs maybe? Can you share it?

> I would like to donate to you but this Chinese translation and wrong displaying makes me feel so bad. If it can be solve I would like to donate.

I consider donation threatening very rude. Either you donate or you don't. But don't ask me to jump up and down for you. I don't do this for your money!

**Comment by FanyangMengDev** [comment]
First, my apology that I made you feel that is a donation threatening. Actually it is not. Every time I meet a good project I will donate, I just told a truth, not a threatening. This point need to be clear clarified.

Second, could you please tell me where can I find the SMTP error log? I would like to forward it to you.

Third. The blue box alert disappear after I restart php, I remember that in the doc file you said we need to restart nginx, I think you could make a correction.

Thank you so much.

**Comment by JC5** [comment]
Thanks. I've updated the wiki page. You can find any error logs in `storage/logs`.

**Comment by FanyangMengDev** [comment]
Hi my friend,
After tested for many times, I found where the problem is.
Now smtp works well, and thank you for you support!
I will report my translation as soon as possible.
I hope this project will be better and better in the future.
Thanks again!

**Comment by FanyangMengDev** [comment]
Just one more question, I search for a long time and I cannot find out where is "吃饱没？".
Could you please tell me where is this string in the file path?
Thank you so much !

**Comment by FanyangMengDev** [comment]
Found.
/resources/lang/zh_CN/firefly.php       welcome_back means “欢迎回来” not “吃饱没？”, I found thsi on Crowdin is display as "What's playing". I mean, what is that, wide of the mark！ This thing cannot be corrected on Crowdin. Please have a look. Thanks!
![Crowdin](https://user-images.githubusercontent.com/53750381/68274189-660cb700-00a3-11ea-82bf-979b8ce533bb.PNG)

**Comment by JC5** [comment]
"What's playing?" is an informal way of saying "what's up? How are you? What's going on?"
