### ISSUE TITLE
Webpage CSS not loading on Self Hosted Apache Web Server

### ISSUE THREAD

**Issue by gustavoholst** [firefly-iii/firefly-iii#2799]
I am running Firefly III version 4.8.1.8

**Description**
I am running Raspbian Buster on a Pi 3B+ with Apache2, MySQL, and PHP7.3 installed. As far as I know, all necessary PHP modules are installed. When I load the firefly-iii web interface, the site is rendered but without any styling ([see here](https://imgur.com/MmTomxR)). I have run into the same problem with both Apache2 and lighttpd. Any thoughts on things to look into? Thanks!

**Comment by JC5** [comment]
In the source of the page, what's the URL of the CSS file? If you can find out why it's giving a 404 you'll have the root cause.

**Comment by gustavoholst** [comment]
Figured out what is happening. 

When I navigate to /firefly-iii/public in the browser, I get a 404 error. When I visit /firefly-iii/public/index.php, the webpage loads, but it then looks for the .css files in /firefly-iii/public/index.php/v1/...

This makes sense because the index.php file looks for the css documents in /v1/...

So, I think I need to get my web server to load index.php when I navigate to /public/. Got a quick recommendation for how to do that?

**Comment by JC5** [comment]
Not really sorry, but the action you'll need to take is make sure that the web root for Apache is set to /public/ and make sure that the rewrite module is on.

**Comment by gustavoholst** [comment]
That was the problem I think. Had trouble getting rewrite to work, and then apache was set to give a 404 page when the url wasn't a file rather than to try rendering the .php file. Got it working. 

Thank you for your help! You got me to realize why it wasn't serving the .css. 😄
