### ISSUE TITLE
Make the decision "description" OR "Expense Accounts"

### ISSUE THREAD

**Issue by natrius** [firefly-iii/firefly-iii#2801]
**Description**

I am running Firefly III version 4.8.1.1, and my problem is:

Make the description optional. Most of the time i just care about store or "expense accounts" so i can see the flow. The description on the other hand is just a addon that i need sometimes when i make specific things. 

I got hint, that its a fireflyiii thing from here https://github.com/emansih/FireflyMobile/issues/72

**Solution**

Make "Description" OR "Destination account" neccessary.

**What are alternatives?**

I don't know any right now.

Thanks for making all this possible! :)

**Comment by natrius** [comment]
Ah, damn, i found https://github.com/firefly-iii/firefly-iii/issues/1703 this right after posting. I still think its a difference, but will check your suggestion in the other thread as well.

**Comment by JC5** [comment]
Not to worry, but keep in mind that the description won't be made optional.

**Comment by gavinr** [comment]
I too would prefer "Description" to be optional. Is there a technical reason why it is required? Perhaps that could be made a setting?

**Comment by natrius** [comment]
Okay, so i'm using it now more and more and i like it so far, but i don't understand the need for the description field. I understand the "rules" you mentioned in the other post and i think its amazing what is possible to do. 

But i don't understand why description is necessary and destination account is optional - in my view this should be reverse. Because all the money-flow is possible to see with the destination accounts (expense accounts) and not with the description. Right now i just copy&paste the expense account in there. I might add some rules later so some things will get automated (like you did, some shortcuts for some things). 

Its your babie and if you won't change it, okay, but i don't understand that decision :)

**Comment by gavinr** [comment]
Is there a technical reason why description is required? Perhaps that could be made an Option/Preference?

**Comment by natrius** [comment]
I don't want it to marked stale or closed. So yesterday i had my first thing where i really "needed" the description, the site was "Rockhouse" and the description would be "Dome of Rock". But i don't 'need' the description here but on the other side the site or the Destination account is really whats interesting to analyse further. Same for groceries, destination account is the shop ( "Albert Heijn" in your example" and the description would be the details, for example "christmas", or "Halloween party" or "Birthday party" in case i want to investigate further why the spendings in one particular month were more than in others.

**Comment by JC5** [comment]
It’s not going to change.
