### ISSUE TITLE
API documentation - disable currency wrong parameter type

### ISSUE THREAD

**Issue by palladionIT** [firefly-iii/firefly-iii#2802]
Hey there,

I am working on a small project that will allow people to switch from another app to firefly. While working on my data transfer script I encountered a small mistake in the API documentation. 
Under [currency disable](https://api-docs.firefly-iii.org/#/currencies/disableCurrency) the parameter type is 'integer' which of course should be string like with currency enable.

I do not provide more details because this should be descriptive enough easily fixable. And thanks for this awesome project! I am really happy to be able to host such a service myself!

**Comment by JC5** [comment]
Thanks for letting me know. Feel free to submit a PR:

https://github.com/firefly-iii/api-docs-generator/blob/master/yaml/paths/currencies.yaml#L87

**Comment by palladionIT** [comment]
I have never created a PR, I will make one as soon as I find the time. Thanks!
