### ISSUE TITLE
Not happenings on convert withdrawal to deposit

### ISSUE THREAD

**Issue by welbert** [firefly-iii/firefly-iii#2803]
**Bug description**
When i try convert transaction to deposit, not happenings after convert

**Steps to reproduce**
1. Open https://demo.firefly-iii.org
2. Click any withdrawal (https://demo.firefly-iii.org/transactions/show/2)
3. Click "Convert to a deposit"
4. Confirm on "Convert withdrawal"

PS: It happenings in demo currently

**Extra info**
Debug information generated at 2019-11-06 23:48:04 Europe/Amsterdam for Firefly III version **4.8.2-alpha.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2-alpha.1 |
| FF API version | 0.10.5 |
| App environment | production |
| App debug mode | false |
| App cache driver | memcached |
| App logging | , daily |
| PHP version | 7.3.11-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-11-06 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | true |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imap, intl, json, ldap, exif, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, yaml, zip, memcached, Zend OPcache, xdebug |

**Bonus points**
![image](https://user-images.githubusercontent.com/7155838/68344941-f7455300-00ce-11ea-8323-b58c700b214b.png)

![image](https://user-images.githubusercontent.com/7155838/68345103-54d99f80-00cf-11ea-9d07-8f5f7c1d5a5d.png)

-->

**Comment by JC5** [comment]
I just tried it and it works perfectly.

**Comment by welbert** [comment]
Nevermind, i cant reproduce it anymore, can be close this issue.

**Comment by JC5** [comment]
OK, let me know if other problems pop up1!
