### ISSUE TITLE
When update transaction, got 404 on return action

### ISSUE THREAD

**Issue by welbert** [firefly-iii/firefly-iii#2804]
**Bug description**
My firefly isn't installed on root, like, https://welbert.com/financa, when i update the transaction, i got 404 because url is like https://welbert.com//financa/transactions/show/873?transaction_group_id=873&message=updated (With 2 "/" on .com//financa), but transaction is updated normally

**Steps to reproduce**
1. Install firefly on root folder child of webserver
2. Select any transaction
3. Click to update this transaction
4. Confirm edit

**Extra info**
Debug information generated at 2019-11-06 20:08:38 America/Bahia for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.4-2 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2017-03-18 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**
![image](https://user-images.githubusercontent.com/7155838/68345798-088f5f00-00d1-11ea-9de6-554ebb9c421b.png)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2774

Same roof cause. Fix is on the way.
