### ISSUE TITLE
[Question] Can be create transaction on liability without destination account?

### ISSUE THREAD

**Issue by welbert** [firefly-iii/firefly-iii#2805]
When i try to create transaction on liability without destination account, shows this message below
![image](https://user-images.githubusercontent.com/7155838/68346450-e8609f80-00d2-11ea-9a6c-261782fb0352.png)

but otherwise works and automatically associates with "Cash Account"

![image](https://user-images.githubusercontent.com/7155838/68346560-32e21c00-00d3-11ea-9a59-8cf119bbe9ed.png)

It's happenings on https://demo.firefly-iii.org

**Comment by JC5** [comment]
It's very weird that you want to take a cash withdrawal out of a liability directly. But in the next release of Firefly III, this will be possible.
