### ISSUE TITLE
Skip 1 month does not work

### ISSUE THREAD

**Issue by diegombeltran** [firefly-iii/firefly-iii#2806]
**Bug description**
I am running Firefly III version 4.8.2-alpha.2, and my problem is:

Skip 1 month (to generate a bimonthly bill) does not work. If I set the bill to be paid on October 30 and then make it monthly with "skip" value set to 1, it shows as pendant (to be paid on November 30). If I change the skip value to 2, it shows 30 January. December is skipped in any case.

**Extra info**
Raspbian on Raspberry Pi, Docker container and Firefox 70 client.
Debug information generated at 2019-11-07 11:55:49 Europe/Madrid for Firefly III version **4.8.2-alpha.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2-alpha.2 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , docker_out |
| PHP version | 7.3.11 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 00:00:00 |
| Session first | 2019-10-21 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**
Skip value 1
![imagen](https://user-images.githubusercontent.com/7081281/68383476-06bbaf00-0156-11ea-9203-cc9127815f33.png)

Skip value 2
![imagen](https://user-images.githubusercontent.com/7081281/68383630-4da9a480-0156-11ea-8516-4d7392c9cd76.png)

**Comment by JC5** [comment]
Thanks, I'll check it out. Some times end-of-month skips can be tricky.

**Comment by diegombeltran** [comment]
Thank you for your work, JC5. Let me know if I can assist you with something.

**Comment by JC5** [comment]
Will be fixed in the next release. When this issue is auto-closed, I invite you to test it.

**Comment by diegombeltran** [comment]
Next alpha? Thank you very much @JC5 , I'll tell you then.
