### ISSUE TITLE
Creating Cash Account Through API results in Error 422

### ISSUE THREAD

**Issue by palladionIT** [firefly-iii/firefly-iii#2809]
**Bug description**
I am running Firefly III version 4.8.1.1, and my problem is:

When I want to create a cash account through the API I always get error 422. When I try to create an account on the test instance through the API documentation/tester I have the same error. According to the model description the request should be fine but it results in the error.

**Steps to reproduce**
POST request body:
```
{
  "name": "totallyimpossiblename",
  "type": "cash",
  "notes": "Some example notes"
}
```

Results in:
```
{
  "message": "The given data was invalid.",
  "errors": {
    "name": [
      "This account name is already in use."
    ]
  }
}
```

Is there a mistake on my part or is there a problem with the API?

**Comment by JC5** [comment]
No, there is only one cash account in the system and it is generated automatically. Do you perhaps mean to create a asset account with the cashWallet type?

**Comment by palladionIT** [comment]
I see, well then disregard this bug. Is there any information about this design choice somewhere? I could not find it in the documentation.  I guess then this bug can be closed.

**Comment by JC5** [comment]
I'll make sure to update the API documentation. I never thought to do so, you're the first to try this :)
