### ISSUE TITLE
Budged is overspent, but it doesn't

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2810]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is:
Budged is overspent, but it doesn't

Screenshot from my budget page
![image](https://user-images.githubusercontent.com/25054050/68504070-ecc0c000-026c-11ea-9237-06e23d07a05e.png)
My budget for November is 25000 UAH
I spend 6360 UAH, and it looks like true.

Screenshot from Reports
![image](https://user-images.githubusercontent.com/25054050/68504127-095cf800-026d-11ea-927e-9b8e1102a0b8.png)
As you can see ₴18,640.00 left in budget

Budget page
![image](https://user-images.githubusercontent.com/25054050/68504372-7d979b80-026d-11ea-8e49-4567c6cb7ea2.png)

I don't have any expenses not in budget
![image](https://user-images.githubusercontent.com/25054050/68504430-9f911e00-026d-11ea-9f4b-34930e6d9b76.png)

**But on the main page I have 6360 UAH OVERSPENT, it should be 18640 UAH LEFT**
![image](https://user-images.githubusercontent.com/25054050/68504313-5771fb80-026d-11ea-98e9-34eefca477d4.png)

Debug information generated at 2019-11-08 21:20:58 Europe/Kiev for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-10-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
You haven't set the total amount.

**Comment by optimistic5** [comment]
Thank you for your quick answer.

Where I have to set this amount?

![image](https://user-images.githubusercontent.com/25054050/68505423-d7996080-026f-11ea-84f2-77f985c5935f.png)
Does this mean I already set it?

**Comment by JC5** [comment]
Pencil button to the far right.

**Comment by optimistic5** [comment]
It works, thank you!

**Comment by JC5** [comment]
Glad to hear it. Am on my phone so had to be short. Sorry about that :)
