### ISSUE TITLE
Tag description: Text area is empty in edit view

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2811]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is: When editing a tag which has text in the description field, the description-textarea won't show the content.

**Steps to reproduce**
Go to a tag with a description an click on the edit-button.

**Extra info**
Win10, Google Chrome 78.0.3904.97

**Comment by JC5** [comment]
Indeed, nice find. Will be fixed in the next release.

**Comment by nepomuc** [comment]
Nice, thanks a lot for the great work!
