### ISSUE TITLE
Delete tag: Leads to 404

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2812]
**Bug description**
After deleting a tag the system wants to get me back to the tag's edit page, which produces a 404 error.

**Steps to reproduce**
Delete a tag.

**Extra info**
Win10, Google Chrome 78.0.3904.97

**Comment by JC5** [comment]
Indeed, that case was not covered and could happen. Will be fixed in the next release.

**Comment by nepomuc** [comment]
Awesome! Thanks a lot!
