### ISSUE TITLE
Revenue view: file_put_contents error

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2813]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is: Calling https://myfirefly-iii.example.com:1234/accounts/revenue causes error. (See screenshot.)

**Steps to reproduce**
Just call https://nepomuc.no-ip.org:64443/accounts/revenue

**Extra info**
Win10, Google Chrome 78.0.3904.97

**Bonus points**
![image](https://user-images.githubusercontent.com/864660/68529452-41148000-02ff-11ea-8f42-bac0da3450d8.png)

**Comment by nepomuc** [comment]
Called `sudo php artisan cache:clear`and this seemed to solve the error. But why did it occur in the first place?

**Comment by JC5** [comment]
It may happen when you run artisan commands in your docker container without using `-u www-data`.

**Comment by nepomuc** [comment]
Thanks for the quick response. I don't use docker, but I ran artisan with root yesterday..maybe that could have caused the problem?

**Comment by JC5** [comment]
Yep, that's probably the cause.

**Comment by nepomuc** [comment]
👍
