### ISSUE TITLE
Time range selection "all": Diagrams & lists should select the earliest date in db and not just start at 0.

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2814]
**Description**

I would like to see Firefly III do the following when time range it set to "all": Diagrams & lists should select the earliest date in db and not just start at 0. This decreases the processing load for the browser when drawing tables and diagrams.
The time range selection already show it correctly. When selection "All" it shows the earliest and most recent date of all entries, but the graph draws from 0 to 2019. (Same with tables.)

<img width="1154" alt="Bildschirmfoto 2019-11-09 um 15 09 57" src="https://user-images.githubusercontent.com/864660/68529890-6efbc380-0303-11ea-8a44-eef322ddf424.png">

**Comment by JC5** [comment]
Firefly III already does this. It will start at the earliest entry in your database. The only conclusion is that your data is bad.

**Comment by nepomuc** [comment]
I just reviewed my csv and you were right. My spreadsheet program cut the year-part of the date down to "18" instead of leaving it "2019". Those "intelligent" programs.. :D

Thanks for your support!

**Comment by nepomuc** [comment]
So now it would be awesome to be able to rollback the last import. Is there a dedicated rollback-functionality somewhere or am I supposed to just delete all transactions related to the last upload's tag?

**Comment by JC5** [comment]
You should delete them, preferrably from the database directly. You can use the tag to select the transactions.

**Comment by nepomuc** [comment]
Directly from the database seems pretty risky to me, since there are links between the "transactions"- and the "transaction_journal"-table. Maybe there are even more links like that? So can you give me some advice on how to securely delete the false transactions completely?

**Comment by JC5** [comment]
Delete the entries from the `transaction_journals` table. The rest will follow. Make a backup just in case.

**Comment by nepomuc** [comment]
"The rest will follow" means the system will clean up the leftover, unnecessary data itself?

**Comment by JC5** [comment]
Yes. Indexes in your databases will remove other entries and the empty transaction groups will be cleared up when you upgrade next.
