### ISSUE TITLE
I would like to merge accounts

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2815]
**Description**

When importing data I sometimes need to merge accounts afterwards.

It would be awesome to select multiple accounts of one type (e.g. expense accounts) and click a "Merge it, baby!" button (naming open for discussion :) ).

Also I think asking the user for the final name of the now unified account would also be useful, since the need for merging several accounts probably comes from a situation of having several names probably not really good names for one and the same thing/account.

**Comment by JC5** [comment]
How did you import the data, exactly?

**Comment by nepomuc** [comment]
I used the built in import.

Just found https://github.com/firefly-iii/firefly-iii/issues/1359 . When attempting to delete a expense account the system tells me that it will also delete the transactions though.

**Comment by JC5** [comment]
I assume you've imported CSV files?

Use the mapping function to link all the variations of expense account names to one single expense account.

**Comment by nepomuc** [comment]
Correct, I imported a CSV file. Don't you think that it would be useful to be able to link/merge account variations afterwards, too?

**Comment by JC5** [comment]
It's a use case driven by the learning curve of the CSV importer, which makes it a repeated effort to correct your import. I'd rather that users pick up on the usefulness of mapping accounts.

**Comment by nepomuc** [comment]
Sorry, I have to ask again. The CSV importer is trying to correct every csv data by suggesting to link/merge fields. That's nice. But since I installed Firefly III yesterday, there have been several cases when I needed to link/merge accounts after an import. For example: You have several transactions in the csv which are related to the same shop, but there are misspellings or different names for it in the different rows, because the original Excel spreadsheet was edited manually and in a messy way. There's no expense account for this shop in the system yet, so the import will generate several expense account entries for the same shop. In this case and some other cases it would be very useful to be able to merge accounts afterwards.
I hope that's an understandable description.

**Comment by JC5** [comment]
I know what you mean of course, but I'm sorry. Other priorities won't make this something I can offer on a short term.

https://docs.firefly-iii.org/importing-data/csv#best-practices

**Comment by nepomuc** [comment]
Sure, I understand that. I'll correct the data manually now and maybe other users also want to see this feature being implemented and vote for it 👍 

Thanks for the excellent work!

**Comment by Moc** [comment]
@nepomuc I think mapping the accounts functionality during import is exactly what you need. So you prevent the creation of numerous accounts which essentially are the same store

**Comment by nepomuc** [comment]
Thanks for the advice and the information. I totally agree with you that it would work if the user (in thias case myself) knew that he had to create the entries beforehand. But: He or she doesn't.
Let's look at it from a simple user's perspective, who wants to be able to use every app intuitively, led by the app itself rather than by instructions from documentation.
So maybe we can agree on the fact that what you said is true, but also see that the UX for this case could be improved a lot in various ways. As a simple first step it could be an information text and later an implementation of the ability to create new entries in the same view as where the linking happens. What do you guys think about that?

**Comment by Moc** [comment]
Sure, I do agree this could be made more user friendly (e.g. also recognizing the filled in IBANs and making suggestions for likely matching accounts). 

I think this may be part of a longer term roadmap for the whole import area, which if I remember correctly, is to be 'detached' from core so to speak, and the functionality will be made available in separate applications making it easier to maintain Firefly, and also to further enhance user experience with things discussed in this issue :) 

https://www.patreon.com/posts/future-updates-30012174
