### ISSUE TITLE
Editing a transaction using custom port: 404 error

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2816]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is: When editing a transaction I get redirected to a URI which is missing the port number and also has a double slash after the domain, which finally ends up in showing me a 404 error page.

That's the URI the system wants to redirect me to: https://firefly-iii.example.com//accounts/show/123?transaction_group_id=123&message=updated

**Steps to reproduce**
Go to a transaction and edit it. In my case the URL ist structured like so: https://firefly-iii.example.com:1234/transactions/edit/123
I suppose this has to do with the custom port number.

**Extra info**
Win10, Google Chrome 78.0.3904.97

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2774
