### ISSUE TITLE
Encoding error for special characters despite UTF-8

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2817]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is: Despite telling the browser in <head> that the page it UTF-8 encoded German umlauts for example aren't encoded correctly. (See screenshot.)

**Steps to reproduce**
Switch the language of the Firefly III system to German.

**Extra info**
Win10, Google Chrome 78.0.3904.97

![image](https://user-images.githubusercontent.com/864660/68532521-741a3c00-031e-11ea-8557-16edcd8ed31f.png)

**Comment by JC5** [comment]
You system prefers "de_DE" over "de_DE.utf8". You can force the issue by checking which german locales you have installed and removing those which aren't UTF-8.

**Comment by nepomuc** [comment]
Thanks for your response. I have the following configuration in terms of locales:

```
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

It's also defined in /etc/default/locale and in /etc/locale.gen it's the only activated locale.
I have to admit I don't know a lot about working with locales yet. So maybe I'm missing something..?

**Comment by nepomuc** [comment]
After clearing the cache (`php artisan cache:clear`) it finally works.

**Comment by JC5** [comment]
In a future release, I'll try to force UTF-8 when users select German.

**Comment by nepomuc** [comment]
Thanks! Maybe that's a good idea in general? Thinking of other languages with special characters.

**Comment by JC5** [comment]
Most languages have this fix already, and the problem is relatively rare. It has to do with the way the app is configured to look for locales.

**Comment by nepomuc** [comment]
:)👍
