### ISSUE TITLE
Chart at home page doesn't load

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2818]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is: I can't see the chart on the home page. Server responds with error 500.
Charts on other pages like a report work fine.

**Steps to reproduce**
It's right on the home page of my Firefly III. I don't have these issues on https://demo.firefly-iii.org/ .

**Extra info**
Win10, Google Chrome 78.0.3904.97

**Comment by JC5** [comment]
I’ll need some debug logs to tell you what’s up

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by nepomuc** [comment]
Thanks for your response. I cleared the cache (`php artisan cache:clear`) and now the chart gets drawn correctly. I wonder what has originally caused the 500 error.

If only have the following log files. Which one's the correct one I have to search through?
![image](https://user-images.githubusercontent.com/864660/68533552-72ef0c00-032a-11ea-80eb-9e309ee003f1.png)

**Comment by JC5** [comment]
apache2handler should contain the logs of your web server.

**Comment by nepomuc** [comment]
I can see a lot of `[2019-11-09 19:27:39] local.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:75)`

Maybe that's what caused the problem?

**Comment by JC5** [comment]
Mmm, that could be the locale problem coming back again. Sorry about that. If you want you can hack your system to make sure it doesn't happen again. It won't be much work, give me a moment to show you what to do.

**Comment by JC5** [comment]
This is the fix you can do by hand for the time being.

https://github.com/firefly-iii/firefly-iii/commit/3c25148f3f669217ed8dbe076810b61b71a41ea8#diff-50d248b0549c856ee1edf4fb4ddd7ef3L27

**Comment by nepomuc** [comment]
Thanks for the support! For now it seems to work, since I completely changes the server's locale settings to de_DE.UTF-8. But a fix coming from Firefly III itself would be a lot better from a admin's perspective.

**Comment by nepomuc** [comment]
There's a fix. Closing this issue.

> This is the fix you can do by hand for the time being.
> 
> [3c25148#diff-50d248b0549c856ee1edf4fb4ddd7ef3L27](https://github.com/firefly-iii/firefly-iii/commit/3c25148f3f669217ed8dbe076810b61b71a41ea8#diff-50d248b0549c856ee1edf4fb4ddd7ef3L27)
