### ISSUE TITLE
Huge withdrawal chart but not money spent

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2819]
I am running Firefly III version 4.8.1.8 and get a weird graph in the reports section. I only set up my asset accounts and this huge "withdrawal" seems to come fron an initial balance. Why is that shown like if I spent a lot of money, while this seems to be just a technical work-around to be able to get initial money into a asset account?

**Extra info**
Win10, Google Chrome 78.0.3904.97

<img width="1153" alt="Bildschirmfoto 2019-11-09 um 20 00 14" src="https://user-images.githubusercontent.com/864660/68533663-c2820780-032b-11ea-8fad-e4001a3d2ca5.png">

**Comment by JC5** [comment]
Technically, the initial balance is an expense like any other, and no chart will ignore it. They don't care about the type of transaction, they just see money flowing in.

If this annoys you, move the initial balance back to a month or year before the period starts you're interested in: if you want to see 2018 set the initial balance to 2017.

That way, the money will have been there already and the reports will ignore it.

**Comment by JC5** [comment]
(of course, money flowing out could also be the case)

**Comment by nepomuc** [comment]
Thanks for the explanation. Would it be a lot of effort to implement a way to setup the initial balances without having to save a transaction for it? That would feel a little cleaner, wouldn't it?

**Comment by JC5** [comment]
No, the idea is that everything is a transaction. Randomly adding money to accounts makes it complicated. If you add all the transactions in your database together, you end up with 0. That's double-entry bookkeeping.

**Comment by nepomuc** [comment]
I understand and it makes sense to have a transaction for everything. I just saw that there's a special transaction type for these opening balance transactions in the transaction_types table. Since these "transactions" are not really relevant for the user and his reports, in my opinion it would make sense to exclude them from the reports in order to avoid confusion. What do you think?

**Comment by JC5** [comment]
I'm not going to change this behavior.

**Comment by nepomuc** [comment]
Are you open to pull requests in this case?

**Comment by JC5** [comment]
Sorry, no.
