### ISSUE TITLE
Budget chart may wrongfully show overspent part

### ISSUE THREAD

**Issue by Dettorer** [firefly-iii/firefly-iii#2820]
I am running Firefly III version 4.8.1.8

**Description**

One of my budget for the current month still has some some money left to be spent in it (this is confirmed by the sum of transaction in that budget for this month and the `/budgets` page), but on the home page, the chart for that budget shows an orange part indicating an overspent amount.

**Extra info**

Debug information generated at 2019-11-09 23:47:33 Europe/Paris for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-08-12 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

The budget's chart:
![budget chart, wrongly overspent](https://dettorer.net/screenshots/screen-23-38-16.png)

The budget's information on the `/budgets` page:
![budget info, correct](https://dettorer.net/screenshots/screen-23-38-47.png)

The complete list of transaction on that budget for the current month:
![budget transactions](https://dettorer.net/screenshots/screen-23-39-47.png)

**Comment by JC5** [comment]
Thanks, it looks like a bug indeed. I'll check it out.

**Comment by JC5** [comment]
Could you browse to `/flush`? Does the problem still exist then?

**Comment by Dettorer** [comment]
Thank you for your answer. Yes I tried browsing `/flush` and also triggering artisan's `cache:clear`, the problem is still there.

Another information that may be useful, every transaction in that budget have the category "Alimentaire", and every transaction from that category either goes to the budget called "Alimentaire" or to the one I showed screenshots of, "Alimentaire tickets restaurant", depending on which card I paid with. But then again, the total amount showed in chart doesn't seem to be the total amount spent in the *category* "Alimentaire", it's higher than that.

**Comment by JC5** [comment]
What's the date range on the frontpage?

**Comment by Dettorer** [comment]
It's from November 1st to November 30.

**Comment by JC5** [comment]
They're the same, right? I'll do some deep diving.

**Comment by Dettorer** [comment]
Sorry I didn't see the other part of your question, yes they're the same.

**Comment by JC5** [comment]
I pushed a fix for this for the next release.

**Comment by Dettorer** [comment]
Thanks a lot! Your support for that project is awesome.
