### ISSUE TITLE
Already consulted chart of account transaction does not refresh after adding transaction to said account

### ISSUE THREAD

**Issue by gregoo** [firefly-iii/firefly-iii#2821]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is: basically the chart showing the balance evolution of an account **for a range** does not refresh if I consulted it **prior** to adding transactions.
It happens for the whole range (no transaction when viewing it first) or partially (some transactions already present when viewing it first)

The symptom is the balance flat-lining:
![image](https://user-images.githubusercontent.com/1266495/68543168-cf4a3e00-03b3-11ea-99a6-9661f6a39fcf.png)
(Euro values and account name are hidden on purpose)

**Steps to reproduce**

1. Consult the transactions in a range of an account you have never checked before (in my case, https://firefly/accounts/show/1/2015-07-28/2015-09-01)
2. Add transactions in said range
3. Refresh the transaction page, the chart is the same as step 1.
(4. If you change the range to something never seen before, it will properly display, for instance, https://firefly/accounts/show/1/2015-07-28/2015-09-02
![image](https://user-images.githubusercontent.com/1266495/68543248-efc6c800-03b4-11ea-8896-31f554821241.png)
)

**Extra info**

Debug information generated at 2019-11-10 12:37:47 Europe/Paris for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2003-04-24 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

- The chart API get returns seemingly cached values
```
curl 'https://firefly/chart/account/period/1/2015-07-28/2015-09-01'
{
    "count": 1,
    "labels": [
        "28 juillet 2015",
        "29 juillet 2015",
        "30 juillet 2015",
        "31 juillet 2015",
        " 1 août 2015",
        " 2 août 2015",
        " 3 août 2015",
        " 4 août 2015",
        " 5 août 2015",
        " 6 août 2015",
        " 7 août 2015",
        " 8 août 2015",
        " 9 août 2015",
        "10 août 2015",
        "11 août 2015",
        "12 août 2015",
        "13 août 2015",
        "14 août 2015",
        "15 août 2015",
        "16 août 2015",
        "17 août 2015",
        "18 août 2015",
        "19 août 2015",
        "20 août 2015",
        "21 août 2015",
        "22 août 2015",
        "23 août 2015",
        "24 août 2015",
        "25 août 2015",
        "26 août 2015",
        "27 août 2015",
        "28 août 2015",
        "29 août 2015",
        "30 août 2015",
        "31 août 2015",
        " 1 septembre 2015",
        " 2 septembre 2015"
    ],
    "datasets": [
        {
            "label": "<redacted>",
            "data": [
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12,
                --6.12
            ]
        }
    ]
}
```
It's definitely not the browser caching. Flushing the browser cache and force reloading yields the same result.
- When changing the range, we get some variation in the values according to the stored transactions:
```
curl 'https://finance.gregauriz.net/chart/account/period/1/2015-07-28/2015-09-02'
{
    "count": 1,
    "labels": [
        "28 juillet 2015",
        "29 juillet 2015",
        "30 juillet 2015",
        "31 juillet 2015",
        " 1 août 2015",
        " 2 août 2015",
        " 3 août 2015",
        " 4 août 2015",
        " 5 août 2015",
        " 6 août 2015",
        " 7 août 2015",
        " 8 août 2015",
        " 9 août 2015",
        "10 août 2015",
        "11 août 2015",
        "12 août 2015",
        "13 août 2015",
        "14 août 2015",
        "15 août 2015",
        "16 août 2015",
        "17 août 2015",
        "18 août 2015",
        "19 août 2015",
        "20 août 2015",
        "21 août 2015",
        "22 août 2015",
        "23 août 2015",
        "24 août 2015",
        "25 août 2015",
        "26 août 2015",
        "27 août 2015",
        "28 août 2015",
        "29 août 2015",
        "30 août 2015",
        "31 août 2015",
        " 1 septembre 2015",
        " 2 septembre 2015",
        " 3 septembre 2015"
    ],
    "datasets": [
        {
            "label": "<redacted>",
            "data": [
                --6.12,
                --6.12,
                --7.62,
                --9.37,
                --9.37,
                --4.27,
                --6.43,
                --6.43,
                --5.16,
                --0.34,
                --0.34,
                --2.35,
                --2.35,
                --9.14,
                --6.65,
                --6.65,
                --6.65,
                --2.66,
                --3.14,
                --3.14,
                --3.95,
                --4.95,
                --8.37,
                --8.37,
                --8.37,
                --1.57,
                --1.57,
                --5.58,
                --0.58,
                --0.58,
                --6.58,
                --6.58,
                --6.58,
                --6.58,
                --6.58,
                --6.58,
                --6.58,
                --6.58
            ]
        }
    ]
}
```
- When using the `/flush` URL suggested in #2820, and using the initial range, the chart is refreshed
![image](https://user-images.githubusercontent.com/1266495/68543356-47b1fe80-03b6-11ea-883a-1316d36fa573.png)
```
curl 'https://firefly/chart/account/period/1/2015-07-28/2015-09-01'
{
    "count": 1,
    "labels": [
        "28 juillet 2015",
        "29 juillet 2015",
        "30 juillet 2015",
        "31 juillet 2015",
        " 1 août 2015",
        " 2 août 2015",
        " 3 août 2015",
        " 4 août 2015",
        " 5 août 2015",
        " 6 août 2015",
        " 7 août 2015",
        " 8 août 2015",
        " 9 août 2015",
        "10 août 2015",
        "11 août 2015",
        "12 août 2015",
        "13 août 2015",
        "14 août 2015",
        "15 août 2015",
        "16 août 2015",
        "17 août 2015",
        "18 août 2015",
        "19 août 2015",
        "20 août 2015",
        "21 août 2015",
        "22 août 2015",
        "23 août 2015",
        "24 août 2015",
        "25 août 2015",
        "26 août 2015",
        "27 août 2015",
        "28 août 2015",
        "29 août 2015",
        "30 août 2015",
        "31 août 2015",
        " 1 septembre 2015",
        " 2 septembre 2015"
    ],
    "datasets": [
        {
            "label": "<redacted>",
            "data": [
                --6.12,
                --6.12,
                --7.62,
                --9.37,
                --9.37,
                --4.27,
                --6.43,
                --6.43,
                --5.16,
                --0.34,
                --0.34,
                --2.35,
                --2.35,
                --9.14,
                --6.65,
                --6.65,
                --6.65,
                --2.66,
                --3.14,
                --3.14,
                --3.95,
                --4.95,
                --8.37,
                --8.37,
                --8.37,
                --1.57,
                --1.57,
                --5.58,
                --0.58,
                --0.58,
                --6.58,
                --6.58,
                --6.58,
                --6.58,
                --6.58,
                --6.58,
                --6.58
            ]
        }
    ]
}
```

**Comment by JC5** [comment]
Yes. That’s the point of a cache. There’s not much that I can do, save for making the routine of emptying the cache so aggressively it would be pointless to have it in the first place. 

You’ll have to learn to live with the occasional delayed chart. Most pages that do a “write” action will clear the cache but it depends on your own system as much as my code whether or not it will happen.

**Comment by gregoo** [comment]
That's fine with me (-: .
Is there a way to expose the cache refresh timer (or is it already and I've missed it) ?

**Comment by JC5** [comment]
There's no timer, it's event based. Opening the new transaction form for example, should already trigger it.

**Comment by gregoo** [comment]
Got it, thanks for the info. I'm closing this one (-:
