### ISSUE TITLE
Can't edit transaction of type "Opening balance"

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2822]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is: Tried to edit the initial transaction (because of https://github.com/firefly-iii/firefly-iii/issues/2819#issuecomment-552127816) for filling up my bank account and when clicking on the edit-button it get redirected back to the asset account page.

**Steps to reproduce**
Try to edit the initial transaction which sets the initial value of an asset account.

**Extra info**
Win10, Google Chrome 78.0.3904.97

**Comment by Dettorer** [comment]
In the meantime, you should be able to change the opening balance by editing the account itself.

**Comment by JC5** [comment]
That's the solution.

**Comment by nepomuc** [comment]
> In the meantime, you should be able to change the opening balance by editing the account itself.

Done, thanks!
