### ISSUE TITLE
Option to "stop asking for IBAN number"

### ISSUE THREAD

**Issue by revi** [firefly-iii/firefly-iii#2823]
I am running Firefly III version 4.8.2-alpha.2 (installed via Heroku)

**Description**
IBAN is not a thing outside certain countries (currently [69](https://en.wikipedia.org/wiki/International_Bank_Account_Number) out of about 200 countries): For those people living in (at least) 131 countries, a reminder to "add IBAN number" when trying to add an account is mere 'annoying bug'. It should ideally just ask only once or have a "NO IBAN" nuke button.

**Extra info** 

**Bonus points**

**Comment by JC5** [comment]
It asks just once. The help popups should only appear once. Is this not the case?
