### ISSUE TITLE
Respect ISO 8601

### ISSUE THREAD

**Issue by revi** [firefly-iii/firefly-iii#2824]
**Description**
Some parts of the world commonly use YYYY-MM-DD, another part uses MM-DD-YYYY, and the other part uses DD-MM-YYYY. It is confusing when you have no option to select them.

**Solution**
Add the option to select how dates are formed, and add [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) as an option. (I don't much care about any defaults as long as ISO 8601 is there in the option)

**What are alternatives?**

I dunno...

**Additional context**

[Date and time representation by country - Wikipedia](https://en.wikipedia.org/wiki/Date_and_time_representation_by_country) - this is crazy enough, though.

**Comment by JC5** [comment]
Which dates do you mean, exactly? Could you provide a screenshot?

**Comment by revi** [comment]
Do you see the "start date"/ "Opening date"? 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/7630875/68546549-c0e33d00-041a-11ea-9f08-60c9e617f8db.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/7630875/68546560-f4be6280-041a-11ea-81b1-47c775ad4aee.png">

**Comment by JC5** [comment]
Those are set by your browser. There's not much I can do. It's a date field, and when you set Firefly III to English, that's what you get.

**Comment by revi** [comment]
Also something like transactions as well.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/7630875/68546588-30592c80-041b-11ea-9c9e-206d0d09d3ce.png">

**Comment by revi** [comment]
I guess that's WONTFIX, thanks anyway.

**Comment by JC5** [comment]
Feel free to open a PR with your browser.

**Comment by revi** [comment]
While I believe you can display the dates with something like custom calendars and display correct ISO dates irrespective of what browser default says, it's your decision and (since I am not really a developer) I am not going to argue more on this / file any PR. :P
