### ISSUE TITLE
"Whoops: Fatal error" with clean native docker-compose

### ISSUE THREAD

**Issue by norx00** [firefly-iii/firefly-iii#2825]
Hi,

I am running Firefly III version 4.8.1.8, PHP 7.3.9 (for the first time)

**Description**
Following the docker-compose installation from the documentation the logs appear to show a successful deployment and run, but all I get is a "Whoops: Fatal error, please check the logs". Unfortunately, the logs aren't conclusive to me.

I don't see any errors and both firefly_db and firefly_app are up and healthy.

**Extra info**
I did not .env nor docker-compose.yaml
Mac OS 10.15, See attached the log
[firefly_log.TXT](https://github.com/firefly-iii/firefly-iii/files/3828887/firefly_log.TXT)

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by JC5** [comment]
Enable debug mode so Firefly III shows you the error.

**Comment by Maxiride** [comment]
Same issue here.
Firefly deployed using docker-compose. I've sent you an email with all the details and the configuration used.

Right here I can tell you that in the `storage/logs` folder only `laravel.log` was present and no other log like `ff3-fpm-fcgi-*.log`.

Visiting `/flush` didn't had any effect.

In the email I've sent I've attached:

- the laravel.log
- the docker logs both of the app and db containers
- the docker-compose and .env I've used for deployment.

**Comment by JC5** [comment]
No problem. I was about to say the same. Glad to hear it's fixed!

**Comment by norx00** [comment]
It seems to be a Mac OS specific problem. I ran the exact same configuration on my Linux machine and everything works out fine.

On my mac, when enabling debug mode I get the attached output. There seems to be a workaround, see, e.g., https://stackoverflow.com/questions/48619445/permission-denied-error-using-laravel-docker but as someone not particularly familiar with Docker I am not sure how and if I could apply it successfully to this container.
![Screenshot_2019-11-13 Screenshot](https://user-images.githubusercontent.com/52069270/68794235-f4a6a880-064e-11ea-9f3e-657272b52c28.png)

**Comment by Maxiride** [comment]
> It seems to be a Mac OS specific problem. I ran the exact same configuration on my Linux machine and everything works out fine.

I had this issue on a Raspberry Pi 3 B+ running Hypriot OS (a port of Raspbian which is ubuntu\debian based), furthermore, Docker runs (by default) a linux kernel under the hood so it has nothing to do with the host OS imho.

Anyway @norx00 I suggest you take a look at [my reply](https://github.com/firefly-iii/firefly-iii/issues/2825#issuecomment-552640685) where the issue has been solved by changing the `LOG_CHANNEL=docker_out` setting in `.env` to `LOG_CHANNEL=stdout`.

Have you tried to change this ☝🏻 setting and retry the deploy?

**Comment by norx00** [comment]
No I had overlooked that but this was the solution. Thanks alot!
