### ISSUE TITLE
Recurring Transactions don't have the specified tags

### ISSUE THREAD

**Issue by frequentsailor** [firefly-iii/firefly-iii#2826]
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is:

When creating a recurring transaction I specified ~~keywords~~ tags for the transaction. The transaction itself is created just fine at the specified date, but it doesn't have the ~~keyword~~ tag.

**Steps to reproduce**
1. Create a recurring transaction with a ~~keyword~~ tag.
2. After it has been created check the transaction for the ~~keyword~~ tag.

**Extra info**
Debug information generated at 2019-11-12 05:41:11 UTC for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-11-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
I’m assuming you mean tags? I’ll check it out, it could be a bug :)

**Comment by frequentsailor** [comment]
Yes, of course. My bad. Got a little confused with the German translation. Thanks for the quick reply and looking into it!

**Comment by JC5** [comment]
Should be fixed in the next release.

**Comment by frequentsailor** [comment]
Awesome. Thank you for the quick fix!
