### ISSUE TITLE
Whoops! An error occurred.

### ISSUE THREAD

**Issue by meetmsajid** [firefly-iii/firefly-iii#2827]
Facing Below issue.
![Capture](https://user-images.githubusercontent.com/57697172/68733041-e88afe80-05ee-11ea-9f5f-951213708960.PNG)

Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

file_put_contents(/home/izezocom/public_html/firefly/storage/framework/cache/data/79/42/7942698bef726131c5478e8a9c79d865c6c9ad9a): failed to open stream: Permission denied

More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.

If you cannot find the cause of this error or when you need some help, please open a ticket on GitHub.

**Extra info**
 

**Bonus points**

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues?utf8=%E2%9C%93&q=is%3Aissue+cache+permission+denied
