### ISSUE TITLE
Better Attachments Manager 

### ISSUE THREAD

**Issue by tayoufabrice** [firefly-iii/firefly-iii#2828]
**Description**

Hi, I would like Firefly III to manage files like pictures or PDF.

**Solution**
As we could have the necessity to save "memo" or "docs" out of transactions or bill. For example a statement or a doc of an account.

**What are alternatives?**
I'm developing a small financial tool and I need to associate pictures to items and docs ... I was willing to implement via Firebase storage but this sound like a bad practice.

**Thanks**

You did a really great job till now. Thanks very much.

Fabrice.

**Comment by JC5** [comment]
I don't understand the question exactly. Are you missing the ability to attach files, or is there something you'd like to do with the attached files?

**Comment by tayoufabrice** [comment]
Currently I stuck because the attachments MUST absolutely refer to a **model**. But in my case the attachment can be associated to a **tag** or a **category**.

What I exactly need is to be able to set and get attachments without `model.id` constraint.

**Comment by JC5** [comment]
Ah, I get it. I'll think about it. It requires attachment management in the user interface as well.

**Comment by tayoufabrice** [comment]
Thanks, you could think about changing the label ?!

Thanks once more for this work you did so far.

**Comment by JC5** [comment]
Improvements that are necessary:

- API changes as suggested in #2636 by @michael-v2vlc which is still on my list despite being closed.
- Add user interfaces.

This would mean broader support for attachments would be API first.

**Comment by tayoufabrice** [comment]
It's a good idea to first implement the API, the user interface would need more resources, translations and some designs ...

**Comment by JC5** [comment]
In the new release, attachments will be available for accounts, bills, budgets, categories, piggy banks and tags.

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.
