### ISSUE TITLE
Firefly css blocked

### ISSUE THREAD

**Issue by The-Inamati** [firefly-iii/firefly-iii#2829]
I am running Firefly III version 4.8.1.8 in Ubuntu 18.04 LTS behind HaProxy

**Description**
I just installed the latest version of Firefly and the app appears unformatted in all browsers.
No errors are logged anywhere. In the console of the browser I get the following error:

`Refused to apply style from 'https://firefly.domain.tld/index.php/v1/lib/bs/css/bootstrap.min.css?v=4.8.1.8' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Can you help?

**Comment by JC5** [comment]
Your proxy or web server doesn’t give css files the right mime type. It’s a config issue I’m afraid.
