### ISSUE TITLE
Duplicate transactions are not detected at creation using the API

### ISSUE THREAD

**Issue by a1ex4** [firefly-iii/firefly-iii#2830]
**Bug description**
I am running Firefly III version 4.8.2-alpha.3, API version 0.10.5 and my problem is that identical transaction are not considered duplicates. I'm using Python to send POST requests and store new transactions.
I see that you recently pushed a commit to handle duplicates on the API, maybe I'm missing something ?
I'm using the API to create transactions with a very limited amount of known fields, I'm assuming that automatically created fields from the first request will be the ones that differ, but I'm not sure how it is supposed to behave then (I know that you aren't a fan of automated importation 😛).

**Steps to reproduce**
In the API sandbox (https://api-docs.firefly-iii.org/#/transactions/storeTransaction), edit the data to be :

```
{
  "transactions": [
    {
      "process_date": "2019-11-12",
      "amount": 1.5,
      "type": "withdrawal",
      "notes": "duplicate",
      "description": "duplicate",
      "date": "2019-11-09",
      "payment_date": "2019-11-09",
      "destination_name": "duplicate",
      "source_id": 1
    }
  ]
}
```
and send twice. Both transactions are created on the demo website. To me it seems that there is enough fields for the transaction to be considered identical.

**Extra info**
The issue was present with Firefly version 4.8.1.8, I decided to try out alpha to see if it was any different

Thanks again for all your hard work, Firefly has always been part of my favorites open source project ! 👍

**Comment by JC5** [comment]
This is entirely by design. If you want to submit identical transactions, go for it. The API won't stop you. If you submit the transaction below however, Firefly III *will* start complaining. This is not yet documented, because it's not yet live.

```
{
  "error_if_duplicate_hash": true,
  "transactions": [
    {
      "process_date": "2019-11-12",
      "amount": 1.5,
      "type": "withdrawal",
      "notes": "duplicate",
      "description": "duplicate",
      "date": "2019-11-09",
      "payment_date": "2019-11-09",
      "destination_name": "duplicate",
      "source_id": 1
    }
  ]
}
```

**Comment by a1ex4** [comment]
Thanks for the clarification, I should have investigated more on this new feature.
This is obviously the best behavior for the API, can’t wait to see what you have in store for the next releases !
