### ISSUE TITLE
Firefly-iii redirects to // instead of / after editing.

### ISSUE THREAD

**Issue by math625f** [firefly-iii/firefly-iii#2831]
I am running Firefly III version 4.8.1.8

**Description**
I'm certain this is a issue caused by the way I've configured Firefly-iii, but I can't figure out where my error is.
My setup is run on apache2 server, where I'm using a symlink to point my /budget folder in the  html folder in my setup, to the public folder used by Firefly-iii. Firefly-iii is working perfectly, thanks again for creating this by the way, except for one issue I'm having. Whenever I edit transactions, rules, or anything it seems like - I'm redirected to //budget/.../, instead of //budget/.../. Removing the extra / takes me to the correct page of course, which is what I've been doing so far. 
I'm unable to replicate the issue on the demo site, which is why I'm certain the problem is on my end.

**Extra info**
Debug information generated at 2019-11-15 12:23:21 Europe/Copenhagen for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.11-1+0\~20191026.48+debian8\~1.gbpf71ca0 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-11-06 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.36 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**
![image](https://user-images.githubusercontent.com/22494364/68940441-698af700-07a3-11ea-91f6-767d172b3959.png)

**Comment by math625f** [comment]
Also I'm unsure if I'm looking for the error in the logs at the correct location - my initial thought that the error could be found in the /storage/logs audit logs, but as far as I can see, there are no mentions of the error - in fact there are no mentions of me editing e.g. the transaction at all.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2774
