### ISSUE TITLE
Rule: Convert to withdrawal requires value?

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2832]
I am running Firefly III version 4.8.1.8

**Description**
I want to create a rule which turns a transaction into a withdrawal as soon as it has a specific tag.
Why does the field require a value?
![image](https://user-images.githubusercontent.com/864660/69005233-4f762380-091f-11ea-9b60-b88e9f7bbf77.png)

**Comment by JC5** [comment]
You're right, that's a bug. I've pushed a fix that should restore Firefly III to the correct behavior.

**Comment by nepomuc** [comment]
Thanks! Quick question: Is it already possible to get a version with your bugfix via Composer? If not: Is there any documentation on how to get the latest code running?

**Comment by JC5** [comment]
Not yet I'm afraid. I hope to push out a new alpha tomorrow that should include it.

**Comment by nepomuc** [comment]
That would be great, thanks! If I wanted to get the latest code from the repo running I could clone it, run `composer install`, move the `.env` and will be fine again?

**Comment by JC5** [comment]
Yes, that would be the best way to do it.

**Comment by JC5** [comment]
You could also run `composer update`. Small risk that packages are incompatible but it will run all verification commands as well.

**Comment by nepomuc** [comment]
Okay, thanks!
