### ISSUE TITLE
Clicking on an external link in help should open new tab

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2833]
For example @https://firefly.example.com/rules/edit/123 when clicking on the help-icon it tells me to go to the documentation. I would like to see the link in the screenshot to open a new tab for a better UX in case the user has unsaved changes. Also it's pretty common to open external URIs in a new tab.
![image](https://user-images.githubusercontent.com/864660/69005263-f6f35600-091f-11ea-99bc-45cdaf59ae20.png)

**Comment by JC5** [comment]
You can control this behavior yourself by using the Shift or Control button.

**Comment by nepomuc** [comment]
Sure, but don't you agree on the common behaviour that external links are usually opening a new tab?

**Comment by JC5** [comment]
No. I dislike it when websites tell me when to open new windows or new tabs. Common behavior or not.

**Comment by nepomuc** [comment]
Well, someone else could argue the other way around and say "I don't like it when websites diverge from common behaviour.". Building good software should never be solely about our personal preferences. I'm pretty sure, that we can agree on that. So let's rest that argument for a second.

When a user edits a tag, has already made some changes and then clicks on the external link, all his unsaved changes get lost. So I would like to see Firefly III

```
window.onbeforeunload = function(){
  return 'Are you sure you want to leave?';
};
```

as soon as the user attempts to leave the page. Otherwise it's a pretty bad and annoying user experience, when you just wanted to get some help and instead end up with losing data.

**Comment by JC5** [comment]
I'll see what I can do. Thanks for the suggestion :)

**Comment by nepomuc** [comment]
Yay, thanks! :)
