### ISSUE TITLE
Autoconvert encoding of CSVs to UTF-8

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2834]
I don't know why but all my banks seem to export CSVs with an invalid UTF-8 encoding. Is it possible to implement a process which re-encodes those non-UTF-8 files automatically?

**Comment by JC5** [comment]
I've looked into this before but it's difficult to detect the encoding of a file without relying on a bunch of extra packages and tools. After some research earlier I noticed I was unable to fix this in a satisfactory manner. I'm afraid you must do the conversion yourself.

**Comment by nepomuc** [comment]
Too bad, but understandable. To be honest it's the banks responsibility to generate a properly encoded file anyway. On the other hand for a normal user changing the encoding by himself would probably be too difficult.
And using things like mb_detect_encoding and mb_convert_encoding doesn't work properly, right?

**Comment by JC5** [comment]
Exactly. They work up to a point where they will mess up international characters and data in unpredictable ways.

**Comment by nepomuc** [comment]
Do you know whether there's a list of known issues regarding those two functions in terms of their "unpredictable ways"?

**Comment by JC5** [comment]
The problem is more universal: encodings are a mess. I can reliably go from Windows to UTF8 for example but if it's anything else it gets tricky. I'll have to check what there is to find in terms of known issues, but generally speaking: if I let users do it themselves the error rate goes way down.

**Comment by nepomuc** [comment]
I understand. Maybe a good compromise would be to offer the functionality with a disclaimer that it could mess up the data and give the user the chance to review the re-enconded CSV before it gets processed. He/She has to check it manually but doesn't have to know the technical steps to for the re-encoding itself. The users who are able to re-encode the file themselves could still do that.
