### ISSUE TITLE
CSV-import: No minus-sign but "H" and "S" for deposit and withdrawal

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2835]
One of my banks doesn't mark a transaction as a deposit or a withdrawal by prepending a minus-sign in front of the amount, but has a dedicated column with the values "S" for a withdrawal and "H" for a deposit. I tried create a rule (#2832) which looks for a tag "S" or "H" which will be appended to each transaction when importing the CSV. But that's a pretty cheap workaround. Do you have any suggestions or even a proper solution for handling this banks weird behaviour?

**Comment by JC5** [comment]
You could use the "amount" and "amount (negated)" column types, maybe? One for the S, and one for the H columns.

**Comment by nepomuc** [comment]
Unfortunately it's the same column and it's value is either "H" or "S".

**Comment by JC5** [comment]
Could you share some examples?

**Comment by nepomuc** [comment]
So, that's how two the column structure looks like:

```
"01.10.2019";"01.10.2019";"John Doe";"John Doe";;"IBAN123456123456";;"BIC123456";"LABEL-WHATEVER";;"EUR";"1.337,00";"H"
"01.10.2019";"01.10.2019";"John Doe";"John Doe";;"IBAN123456123456";;"BIC123456";"LABEL-WHATEVER";;"EUR";"13,37";"S"
```

The first row is a deposit and the second one is a withdrawal.

**Comment by JC5** [comment]
OK, so what do H and S stand for, exactly?

**Comment by nepomuc** [comment]
"H" stands for the German word "Haben" which in this context means "credit". So "H" stands for money coming in.
"S" stands for "Soll" which this context means "debit". So "S" stands for money going out.

**Comment by JC5** [comment]
I've pushed a fix for the "generic debit/credit indicator" which you should use on that column. That should correct the amount and fix the import.

**Comment by nepomuc** [comment]
Awesome, thanks!
