### ISSUE TITLE
Browser navigation & cache: Trying to remove transaction > Redirected to home.

### ISSUE THREAD

**Issue by nepomuc** [firefly-iii/firefly-iii#2836]
I just deleted a bunch of transactions linked to a specific tag. So I was in a view like https://firefly.example.com/tags/show/123/all . I selected all transactions and deleted them. Afterwards I didn't get redirected back to the tag, but to the profile of a transaction. So I navigated back to the tag by using the browser's back button. In this case the browser (Chrome) tends to load data from the cache and showed me old items which had already been deleted. I tried to delete them again, since I thought it didn't work the first time. Then I got redirected to the home page without any error.
From a user's perspective I would like to see an error message, if he wants to delete a transaction that's not in the database. But also I would prefer to be redirected back to the tag or generally speaking: the place where I came from.

**Comment by JC5** [comment]
If your browser serves you previously cached content, there's not much control I have over what to show you. Did you get redirected home after you submitted the deletion of an already deleted item?

As for getting referred back to the place you came from: several improvements have been made in recent (alpha) releases.

**Comment by nepomuc** [comment]
Chrome does that in case you're using the back-button. I don't know the details of this dynamic, but if you got back to the url by pasting it into the address bar and hit enter the browser would to a real reload of the page.

> Did you get redirected home after you submitted the deletion of an already deleted item?

Yes.

> As for getting referred back to the place you came from: several improvements have been made in recent (alpha) releases.

Sounds great! Can you tell me when the next stable release is going to come out?

**Comment by JC5** [comment]
OK. There's not much I can do unfortunately about that redirect. I hope to release the next stable release end of next week.

**Comment by nepomuc** [comment]
I guess as long as the user gets redirected to the correct page he won't use the browser's back-button.
Speaking of that weird browser caching behaviour when using the back button...it seems to be a known issue which can be addressed by using special header parameters: https://stackoverflow.com/questions/10096671/chrome-back-button-only-giving-cached-version-of-initial-page-without-any-ajax

**Comment by JC5** [comment]
Thanks, I'll look into it :)

**Comment by nepomuc** [comment]
You're very welcome :)
