### ISSUE TITLE
How to properly spend the funds of a piggy bank

### ISSUE THREAD

**Issue by souldessin** [firefly-iii/firefly-iii#2837]
I am running Firefly III version 4.8.1.8 on Docker and wanted to know if there was a proper way to note that a piggy bank was spent. The only way that I can see, is to remove the money from the piggy bank, close/delete the piggy bank, transfer the money to a spending account, and then log the transaction as spent.

There wouldn't be any way that it can just be transferred and closed/spent in the transaction? I could very well be missing it.

Thanks for the help.

**Comment by JC5** [comment]
No, there isn't. Clearing out the piggy bank and then spending the money is the suggested way to do this.

**Comment by souldessin** [comment]
Thanks for help.
