### ISSUE TITLE
Automatic import from multiple banks with spectre

### ISSUE THREAD

**Issue by schattenkrieger** [firefly-iii/firefly-iii#2838]
I am right now taking my first steps with this project. 
It looks like it is missing a lot of things to be a viable replacement for ynab, but it look promising to keep an overview over multiple accounts and banks to simplify entry in ynab.
i am having 7 different accounts with 3 different banks that i want to keep up to date, setting them up via spectre worked right out of the box, but i seem to be unable to get them updating automatically.
i allways have to select import -> spectre -> "the bank" -> which account goes where for every single bank. for setting it up that is fine, but apperantly i have to do that every time i want to update the transactions. am i missing someting, or is that the way it is supposed to be?

**Comment by JC5** [comment]
At the moment, that's the way it's supposed to be. [Spectre isn't really meant for tools like Firefly III](https://docs.firefly-iii.org/importing-data/spectre). If you're looking for full automation, you might be better of with YNAB.

I'm working on [new tools to improve automation](https://www.patreon.com/posts/future-updates-30012174) but generally speaking, updating by hand always works best.
