### ISSUE TITLE
If not checked "After updating, return here to continue editing." its giving 404 Error

### ISSUE THREAD

**Issue by kingdomvision** [firefly-iii/firefly-iii#2839]
Hello,

I have just installed latest version through siteground softaculous and all is working fine however in any page If I don't check on After updating, return here to continue editing.

Screenshot
https://tinyurl.com/wf6abwc

Its giving 404 error

https://tinyurl.com/wfkxkkb

I actually figured out that url has two (//) after domain but I have done a lot of work and can't reinstall now.

Please let me know if its fixable.

Regards

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2774
