### ISSUE TITLE
Crash when creating report

### ISSUE THREAD

**Issue by erdmenchen** [firefly-iii/firefly-iii#2842]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is: Crash when creating report

**Steps to reproduce**
Nothing special, just a fresh setup to play around.
I wanted to create a report and just clicked "transaction history - complete history" (from the quick panel).
Firefly crashes with the error below:
`Argument 1 passed to FireflyIII\Repositories\Journal\JournalRepository::getMetaDateById() must be of the type integer, string given, called in /volume1/web/firefly-src/app/Generator/Report/Audit/MonthReportGenerator.php on line 241`
The error also occures on other 

**Extra info**
PHP 7.2
DB: Sqlite

**Bonus points**
Stacktrace (truncated / should be enough):
`#0 /web/firefly-src/app/Generator/Report/Audit/MonthReportGenerator.php(241): FireflyIII\Repositories\Journal\JournalRepository->getMetaDateById('2', 'interest_date')
#1 /web/firefly-src/app/Generator/Report/Audit/MonthReportGenerator.php(67): FireflyIII\Generator\Report\Audit\MonthReportGenerator->getAuditReport(Object(FireflyIII\Models\Account), Object(Carbon\Carbon))
#2 /web/firefly-src/app/Http/Controllers/ReportController.php(138): FireflyIII\Generator\Report\Audit\MonthReportGenerator->generate()
#3 [internal function]: FireflyIII\Http\Controllers\ReportController->auditReport(Object(Illuminate\Database\Eloquent\Collection), Object(Carbon\Carbon), Object(Carbon\Carbon))`

**Comment by JC5** [comment]
Yes, this may happen when using SQLite and especially in old versions. Most of these issues are fixed in newer releases. If you upgrade to PHP 7.3 you should be able to install the latest version.

**Comment by erdmenchen** [comment]
You are right, I had PHP version 7.2 active and this was the version. that composer installed.
After switching to PHP 7.3 I was able to install the latest stable firefly version 4.8.1.8.

The bug was not reproducible in the latest stable version. Thank you very much for your help!

Keep the good work up!
