### ISSUE TITLE
Initial balance is negative but display as positive.

### ISSUE THREAD

**Issue by FanyangMengDev** [firefly-iii/firefly-iii#2843]
**Bug description**
I am running Firefly III version 4.8.2-alpha.5, and my problem is:
When I input the credit card balance as negative first. In the homepage it display as positive.
See the picture in the following:
![bug](https://user-images.githubusercontent.com/53750381/69127682-b04f5880-0ae5-11ea-936f-9c320e2432b5.PNG)

**Steps to reproduce**

Create an account and input the initial balance as negative. Then you can see it in the homepage display as positive.

**Extra info**

All platform. Chorme.

**Comment by JC5** [comment]
Thanks, I guess this is a bug! I'll fix it ASAP. Thanks for letting me know :)

**Comment by FanyangMengDev** [comment]
Thank you so much for your hard working. You are always such brilliant!

**Comment by JC5** [comment]
Thanks, that's a nice compliment :+1:

This issue will be resolved in the next release.
