### ISSUE TITLE
Cache Permission denied problem

### ISSUE THREAD

**Issue by Schikri** [firefly-iii/firefly-iii#2844]
**Bug description**
I am running Firefly III version 4.7.13, and my problem is:

Sometimes firefly creates cache file for the user "root", though webserver is running on a different user. For this reason I get "failed open file errors" due to missing user priveleges.

What I don't understand is why sometimes it creates cache files for the webhosting user and sometimes for the user root.

**Comment by JC5** [comment]
It happens when you run commands from the command line, ie "php artisan [..]".

https://github.com/firefly-iii/firefly-iii/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+permission+denied

**Comment by Schikri** [comment]
Is there any cron running artisan periodically?

**Comment by JC5** [comment]
Yes, but not by default:

https://docs.firefly-iii.org/advanced-installation/cron

**Comment by Kwbmm** [comment]
Is the solution to clear the cache the official way to fix the problem? https://github.com/firefly-iii/firefly-iii/issues/2782#issuecomment-548841525

If so, it should be specified in the documentation: https://docs.firefly-iii.org/advanced-installation/cron#call-the-cron-job-from-outside-the-docker-container

**Comment by JC5** [comment]
Good point, I'll pick it up.
