### ISSUE TITLE
Progressive web app support?

### ISSUE THREAD

**Issue by LuisFlores3** [firefly-iii/firefly-iii#2845]
**Description**
I would love to be able to install a PWA for FireFly on my phone. 

**Solution**
This would allow the app to work offline and while on the go. We can add transaction and the like as they happen, perhaps even take a pic of a receipt and upload it right then and there. 

**What are alternatives?**
There is an (i assume) un-official app, but it seems to be a read-only app, as i couldn't find a way to add a transaction. Even if the app worked the way i would like, this would be the full FireFly application, without a separate code base or relying on a 3rd party, closed sourced application that i'm not self-hosting. 

**Additional context**
Some resources on PWAs:
[simple google tutorial on Service workers and Offline functionality](https://codelabs.developers.google.com/codelabs/offline/#0)
[A Median post about PWAs and Laravel](https://medium.com/@IO_/https-medium-com-io-building-progressive-web-apps-with-laravel-57f6bfa3ddb1)

**Bonus points**

Thank you so much for this app, i am just getting started with it, but it seems to be exactly what i have been looking for!

**Comment by JC5** [comment]
Yes, that would be an amazing thing to build. It requires Firefly III to be built again from the ground up though, especially the user interface. Which is on my list, but not any time soon.

There are offline mobile apps that work perfectly well already. I'm pretty sure [this app](https://github.com/mconway/firefly-app) isn't read only.

**Comment by LuisFlores3** [comment]
Thanks for the pointer to the app. I'll have to give it a look.
Yeah, definitely didn't think it would be a total refactor of the app, I can totally make due with the either the mobile interface or maybe the mobile app.

Thanks for all you do!
