### ISSUE TITLE
Remember computer for 2FA

### ISSUE THREAD

**Issue by pedrom34** [firefly-iii/firefly-iii#2846]
Hello James,

Can we please have an option to remember the 2FA for trusted devices?
I love the 2FA, but it's kind of annoying to enter the code every time I connect to firefly on my computer.

Thanks!

**Comment by JC5** [comment]
Yes, absolutely. It happens when your session gets restored. I'm not sure why it won't take the 2FA data. I'll write it up as a bug and get on it.

**Comment by pedrom34** [comment]
You're the best James.

**Comment by JC5** [comment]
This is something I can't easily fix, unfortunately. Checking if the 2FA verification is still valid is a core part of [the library](https://github.com/antonioribeiro/google2fa-laravel) I use and it isn't stored in a cookie: it's stored in the session. That means I can't just "hack" it to check a cookie too, it has to come from the original library.

I've been looking at the issues and PR's concerning this feature and [the developer seems to think](https://github.com/antonioribeiro/google2fa-laravel/issues/43) it all works as it should. I hope to get his feedback soon.

**Comment by JC5** [comment]
OK so the next version of Firefly III will use a slightly different version of the 2FA library that will store the token in a table for 180 days or something so the 2FA session gets remembered. When I release the next alpha, probably this weekend, I invite you to check it out.

**Comment by pedrom34** [comment]
:+1: yoohoo!

**Comment by pedrom34** [comment]
I just tested the latest alpha, it's working great. Thanks a lot James :smile: 

I'll make a donation right away :+1:

**Comment by JC5** [comment]
Thanks man, I appreciate it!

For my peace of mind though: do you have a table called `2fa_tokens`?

**Comment by pedrom34** [comment]
Yes, I have. With the 2 tokens I created by logging in on 2 different browsers. The expiration date is set 180 days after my first login.

I'll tell you if I encounter any bug, but so far, no issue at all.

**Comment by JC5** [comment]
:+1: Thanks again!

**Comment by halilim** [comment]
Huge thanks for fixing it! Seems to be holding up. FWIW and not sure if this is about my instance (Docker on a Dokku) - it didn't start the upgrade procedure automatically this time. I did it manually, including the migrations.

**Comment by JC5** [comment]
I’ll try to replicate that, thanks for letting me know.

**Comment by AlexKalopsia** [comment]
2FA seems to work fine now, thank you!
