### ISSUE TITLE
A feature idea about Firefly and a translation issue

### ISSUE THREAD

**Issue by FanyangMengDev** [firefly-iii/firefly-iii#2847]
**Description**
Hi there,
This is an excellent project and after I use it for a while, I have an idea about one feature.

**Transaction support addition, subtraction, multiplication and division**

I used lots of finacial applications before, and I found that many of them have a feature which **allows user can use mathematical expression when they add or edit some transactions.** 

To be honest, this feature is really practical. I would like to give you an example of my daily life. 

I am a student now and everyday I need to take subway for lots of times every day. You know, in Firefly, combine each small expense which has the same name into one transaction make it more suitable for watching, but every time when I do this, **I have to calculate the result first and then input it. Sometimes it can be a problems because it involves a lot of decimal calculations.** 

So I really hope that you can add this function to Firefly which will definately enhance users expericence as the same time.

**Comment by FanyangMengDev** [comment]
I just becomed a sponser to you and this project. As a student I do not have so much money, but I really wanna support your work. I hope you can make it better and better. Thank you for your hard working!

**Comment by FanyangMengDev** [comment]
Oh, I suddenly remembered that there is a bug when using Chinese translations. 

When I **switch to Chinese** and choose to **add a transaction**, **the page will still display in English**. I search for the translation files in /resource/lang/zh_CN and I cannot find where is it. Would you please help to check that? 

I have already restarted php for many times and nothing changed. If this can be fixed that will be so much appreciated!

Here is the screenshot in the following:
![translation bug](https://user-images.githubusercontent.com/53750381/69320749-bcb9e980-0c7c-11ea-883e-fe8c7f21e56f.PNG)

Thank you in advance!

**Comment by JC5** [comment]
Thanks for the suggestions, and I'm glad you have donated. Thank you!

For the mathematics part, this is not something I will feature in the current release of Firefly III. It requires significant changes and I'm currently focussing on other features. I can only suggest you use the calculator in your OS.

For the translations: I believe that this has improved in the latest [test version](https://demo.firefly-iii.org/transactions/create/withdrawal) which I invite you to try online. I believe the translations are pretty good already, You can [suggest fixes](https://crowdin.com/project/firefly-iii) if you wish to.

**Comment by FanyangMengDev** [comment]
Hi there,
Actually I am using 4.8.2-alpha.5, It is the latest version. And this tranlastion problems happens. I am as confusing as you. Would you please have a check on it?

**Comment by FanyangMengDev** [comment]
Here is the debug details from Firefly which I think it might can help.
Debug information generated at 2019-11-21 17:55:35 Asia/Shanghai for Firefly III version **4.8.2-alpha.5**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2-alpha.5 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , docker_out |
| PHP version | 7.3.11 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-11-16 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, sodium, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, cgi-fcgi, zip, fileinfo, apcu, imagick, exif, imap, pgsql, pdo_pgsql, ldap, SourceGuardian, Zend OPcache |

**Comment by FanyangMengDev** [comment]
You can have a try on demo site. I think this problem will happen again. Thank you.

**Comment by FanyangMengDev** [comment]
Sorry, accidently closed issue with wrong click, Reopened it again,

**Comment by JC5** [comment]
No problems, thanks for confirming that this problem is also present in the latest alpha version. I will check it out.

**Comment by JC5** [comment]
I found the reason why not everything is in Chinese (Simplified): not all the text has been translated yet. This is not something I can fix myself. I could use your input at [Crowdin](https://crowdin.com/project/firefly-iii) to make the translations more complete.

**Comment by FanyangMengDev** [comment]
Hi there, I found the translation of that is already in the /resource/lang/zh_CN/firefly.php
the translations of it are all correct. I really do not know where should I help to translate.
Could you please have a check again and tell me where should I translate on Corwdin?
Thank you so much.
BTW I have already upgrade to alpha.6, Thank you for your hard working which solve the initial balance bug.

**Comment by JC5** [comment]
Here are the sentences that still require translation:

https://crowdin.com/translate/firefly-iii/142/en-zhcn

For the transaction form specifically, these strings are in need of translation:

* https://crowdin.com/translate/firefly-iii/142/en-zhcn#q=errors_submission
* https://crowdin.com/translate/firefly-iii/142/en-zhcn#q=submission
* https://crowdin.com/translate/firefly-iii/142/en-zhcn#q=create_another
* https://crowdin.com/translate/firefly-iii/142/en-zhcn#q=reset_after
* https://crowdin.com/translate/firefly-iii/142/en-zhcn#q=update_transaction
* https://crowdin.com/translate/firefly-iii/142/en-zhcn#q=after_update_create_another
* https://crowdin.com/translate/firefly-iii/142/en-zhcn#q=store_as_new
* https://crowdin.com/translate/firefly-iii/142/en-zhcn#q=no_piggy_bank
* https://crowdin.com/translate/firefly-iii/142/en-zhcn#q=split_transaction_title_help

**Comment by FanyangMengDev** [comment]
Done. I use my spare time to translate them and now all of them have been translated into the right word. Please release a new version which contains them. Thank you so much!

**Comment by FanyangMengDev** [comment]
Hi there, please give me some feedback if you have received my message. I still keep waiting for your answer now. Thank you so much.

**Comment by JC5** [comment]
I have, not to worry. The new release will include your translations.

**Comment by FanyangMengDev** [comment]
Hi there,
After upgraded to 4.8.2-beta.2, I found that creat new transaction page still displays like what it did as before. Could you please have a check on it? 
I received an email from Crowdin this morning which told me that there are 6 new strings need to be translated but all of them do not have any connections to this problem.
I can make sure that I have traslated all the strings you gave to me. Maybe the strings on transaction page have not be involved in them?

**Comment by FanyangMengDev** [comment]
I have cleared browser's cache for many times.
Please have a look in the following
![Screenshot_2019-11-26-08-22-33-230_com android chrome](https://user-images.githubusercontent.com/53750381/69589530-4ffd7100-1027-11ea-97db-084ccbafc07d.jpg)

**Comment by JC5** [comment]
I see what you mean. I’ll check it out. Not sure why this is happening.

**Comment by JC5** [comment]
Will be fixed in the final release.

<img width="1172" alt="Screenshot 2019-11-26 at 06 33 39" src="https://user-images.githubusercontent.com/5889984/69602123-5fbc8b80-100e-11ea-9a8d-b614fee66631.png">

**Comment by FanyangMengDev** [comment]
Thank you so much for your efficient working!
