### ISSUE TITLE
Firefly III behind NGINX Proxy

### ISSUE THREAD

**Issue by darkcloud784** [firefly-iii/firefly-iii#2848]
I am running Firefly III version 4.8.2-alpha.5

**Description**
Trying to run a barebones Ubuntu 16.04 Firefly install behind a reverse proxy but keep getting 404 by firefly.

**Extra info**
OS: Ubuntu 16.04
Reverse Proxy: NGINX
NGINX Location Config:

```
location /firefly {
        proxy_pass http://192.168.86.25;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }

```

**Bonus points**
![firefly](https://user-images.githubusercontent.com/989990/69391512-acb00300-0c98-11ea-810d-0839dba8af83.PNG)

**Comment by andrewlytvyn** [comment]
Maybe location must be /firefly/public

**Comment by darkcloud784** [comment]
> Maybe location must be /firefly/public?

Unsure why this would be the case as nothing points to /public in the url of the firefly server nor the proxy.

**Comment by JC5** [comment]
There are some old issues about nginx if you look for them. Any hints there perhaps?

**Comment by 4oo4** [comment]
@darkcloud784 So looks like you're running it on a subdirectory instead of a subdomain? Also what is your back end server that it's proxying to, and the config for that? Finally, it looks like you installed via the release packages, rather than git, since you say that you don't have a /public folder?

**Comment by gimiki** [comment]
Hi @darkcloud784,
try with that below. For info my instance is in a docker container.



```
location /firefly {
            proxy_pass          http://192.168.86.25/;            
            # Request uncompressed files from upstream server to allow manipulation
            # of response body
            proxy_set_header Accept-Encoding "";

            # Rewrite redirects, such as / to /login and /logout
            # No trailing slash - including it works for login, but (at least) not logout.
            # Also means we can't use `proxy_redirect default;`
            proxy_redirect $scheme://$host /finance;

            # Setting proper X-Forwarded headers, in combination TRUSTED_PROXIES
            # env variable, lets Laraval create URLs based on proxied address rather
            # than server name.
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;

            # Add the folder name to links/asset URLs in the response body
            sub_filter $scheme://$host http://$host/firefly;
            sub_filter_once off;
```

**Comment by darkcloud784** [comment]
> @darkcloud784 So looks like you're running it on a subdirectory instead of a subdomain? Also what is your back end server that it's proxying to, and the config for that? Finally, it looks like you installed via the release packages, rather than git, since you say that you don't have a /public folder?
> 
> Thought of one more thing, do you still get an error when you try to load it directly from http://192.168.86.25?

I installed firefly according to the official documentation. The server endpoint is exactly as it is in the said documentation. I have no issues going to my internal domain associated with firefly or directly from the IP. Only from my reverse proxy. I never said I didn't have a /public folder inside firefly, only that it shouldn't require my reverse proxy to point to this as its the webserver on the firefly side that serves up the content which is already working and pointing to the appropriate files (as stated above and in the official documentation).

> There are some old issues about nginx if you look for them. Any hints there perhaps?
I did and most of them revolved around trusted proxy configurations but even when I open this up to ** it doesn't work 

> Hi @darkcloud784,
> try with that below. For info my instance is in a docker container.
> 
> ```
> location /firefly {
>             proxy_pass          http://192.168.86.25/;            
>             # Request uncompressed files from upstream server to allow manipulation
>             # of response body
>             proxy_set_header Accept-Encoding "";
> 
>             # Rewrite redirects, such as / to /login and /logout
>             # No trailing slash - including it works for login, but (at least) not logout.
>             # Also means we can't use `proxy_redirect default;`
>             proxy_redirect $scheme://$host /finance;
> 
>             # Setting proper X-Forwarded headers, in combination TRUSTED_PROXIES
>             # env variable, lets Laraval create URLs based on proxied address rather
>             # than server name.
>             proxy_set_header X-Forwarded-For $remote_addr;
>             proxy_set_header X-Forwarded-Host $host;
>             proxy_set_header X-Forwarded-Proto $scheme;
>             proxy_set_header X-Forwarded-Port $server_port;
> 
>             # Add the folder name to links/asset URLs in the response body
>             sub_filter $scheme://$host http://$host/firefly;
>             sub_filter_once off;
> ```

I'll give this a try and will report back.

**Comment by MansoorMajeed** [comment]
This is my full nginx.conf, works great. (I have Nginx + php-fpm running on a VM - no docker)


```
server {
        listen       80;
        server_name  firefly.domain.com;
        rewrite ^ https://$http_host$request_uri? permanent;    # force redirect http to https
        server_tokens off;
    }
server {
    listen 443 http2;
    listen [::]:443 http2;
        ssl on;
        ssl_certificate /etc/letsencrypt/live/firefly.domain.com/fullchain.pem;        # path to your fullchain.pem
        ssl_certificate_key /etc/letsencrypt/live/firefly.domain.com/privkey.pem;    # path to your privkey.pem
        server_name firefly.domain.com;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:5m;

        # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
        ssl_dhparam /etc/nginx/dhparam.pem;

        # secure settings (A+ at SSL Labs ssltest at time of writing)
        # see https://wiki.mozilla.org/Security/Server_Side_TLS#Nginx
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-SEED-SHA:DHE-RSA-CAMELLIA128-SHA:HIGH:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS';
        ssl_prefer_server_ciphers on;

        proxy_set_header X-Forwarded-For $remote_addr;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        server_tokens off;

        root /opt/firefly-iii/public;

    # Add index.php to the list if you are using PHP
        client_max_body_size 300M;
        index index.html index.htm index.php;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
        location ~ \.php$ {
              try_files $uri =404;
              fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;

        }

        index index.php index.htm index.html;

        location / {
          try_files $uri $uri/ /index.php?$query_string;
          autoindex on;
          sendfile off;
        }
    }
```

**Comment by darkcloud784** [comment]
> Hi @darkcloud784,
> try with that below. For info my instance is in a docker container.
> 
> ```
> location /firefly {
>             proxy_pass          http://192.168.86.25/;            
>             # Request uncompressed files from upstream server to allow manipulation
>             # of response body
>             proxy_set_header Accept-Encoding "";
> 
>             # Rewrite redirects, such as / to /login and /logout
>             # No trailing slash - including it works for login, but (at least) not logout.
>             # Also means we can't use `proxy_redirect default;`
>             proxy_redirect $scheme://$host /finance;
> 
>             # Setting proper X-Forwarded headers, in combination TRUSTED_PROXIES
>             # env variable, lets Laraval create URLs based on proxied address rather
>             # than server name.
>             proxy_set_header X-Forwarded-For $remote_addr;
>             proxy_set_header X-Forwarded-Host $host;
>             proxy_set_header X-Forwarded-Proto $scheme;
>             proxy_set_header X-Forwarded-Port $server_port;
> 
>             # Add the folder name to links/asset URLs in the response body
>             sub_filter $scheme://$host http://$host/firefly;
>             sub_filter_once off;
> ```

Unfortunately this is not working.



> This is my full nginx.conf, works great. (I have Nginx + php-fpm running on a VM - no docker)
> 
> ```
> server {
>         listen       80;
>         server_name  firefly.domain.com;
>         rewrite ^ https://$http_host$request_uri? permanent;    # force redirect http to https
>         server_tokens off;
>     }
> server {
>     listen 443 http2;
>     listen [::]:443 http2;
>         ssl on;
>         ssl_certificate /etc/letsencrypt/live/firefly.domain.com/fullchain.pem;        # path to your fullchain.pem
>         ssl_certificate_key /etc/letsencrypt/live/firefly.domain.com/privkey.pem;    # path to your privkey.pem
>         server_name firefly.domain.com;
>         ssl_session_timeout 5m;
>         ssl_session_cache shared:SSL:5m;
> 
>         # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
>         ssl_dhparam /etc/nginx/dhparam.pem;
> 
>         # secure settings (A+ at SSL Labs ssltest at time of writing)
>         # see https://wiki.mozilla.org/Security/Server_Side_TLS#Nginx
>         ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>         ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-SEED-SHA:DHE-RSA-CAMELLIA128-SHA:HIGH:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS';
>         ssl_prefer_server_ciphers on;
> 
>         proxy_set_header X-Forwarded-For $remote_addr;
> 
>         add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
>         server_tokens off;
> 
>         root /opt/firefly-iii/public;
> 
>     # Add index.php to the list if you are using PHP
>         client_max_body_size 300M;
>         index index.html index.htm index.php;
> 
>         # Load configuration files for the default server block.
>         include /etc/nginx/default.d/*.conf;
>         location ~ \.php$ {
>               try_files $uri =404;
>               fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
>               fastcgi_index index.php;
>               fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>               include fastcgi_params;
> 
>         }
> 
>         index index.php index.htm index.html;
> 
>         location / {
>           try_files $uri $uri/ /index.php?$query_string;
>           autoindex on;
>           sendfile off;
>         }
>     }
> ```

This doesn't seem to be for a proxy which is what I'm looking for, my firefly webserver works fine its the proxy that doesn't seem to be working for some reason.
