### ISSUE TITLE
How to make the balance of transactions

### ISSUE THREAD

**Issue by MrSamuel137** [firefly-iii/firefly-iii#2849]
I am running Firefly III 4.7.17.3

**Description**
How to make the balance of transactions on **accounts/show** controller.

**Extra info**
I wanna make like MS Money and adding a aditional column on transactions list

![img1](https://user-images.githubusercontent.com/12252200/69422843-807d9c00-0d03-11ea-978e-4158ed770984.png)

**Comment by JC5** [comment]
That's not currently a feature, sorry about that.

**Comment by MrSamuel137** [comment]
How can i sum the value of a transaction? 
Because the type is string...
How i convert to numeric type without losing precision?

**Comment by JC5** [comment]
What are you trying to do exactly? Are you coding something (in Firefly III?)

**Comment by MrSamuel137** [comment]
Yes, but a need some help for resolving with a elegant way
