### ISSUE TITLE
Estonian translation

### ISSUE THREAD

**Issue by andrewlytvyn** [firefly-iii/firefly-iii#2850]
**Description**
- Firefly III doesn't translated to Estonian language

**Solution**
Allow me to translate on crowdin.com to Estonian

**Comment by JC5** [comment]
I’ll enable the language in a moment. What’s “Estonian” in Estonian? As in “the Estonian language”. I need it for the user interface.

**Comment by 4oo4** [comment]
eesti keel?

https://en.wikipedia.org/wiki/Estonian_language

**Comment by JC5** [comment]
I wanna be sure :)

**Comment by JC5** [comment]
Thanks for opening the issue btw. I see that Crowdin no longer warns me of new messages on the Crowdin platform.
