### ISSUE TITLE
"Chart of all transactions for Budget" does not populate past the 1st of the Month

### ISSUE THREAD

**Issue by LuisFlores3** [firefly-iii/firefly-iii#2851]
**Bug description**
I am running Firefly III version 4.8.2-beta.1 (it also occurred in 4.8.1.8, but i updated to the beta to see if it had been fixed), and my problem is:

It seems that on the budget overview pages (https://host/budgets/show/#), the "Chart of all transactions for budget X" charts are limited to showing only the 1st of the month. The rest of the page shows all the correct transactions, and the pie charts seem to be correct as well. 

**Steps to reproduce**
Visit any budget overview page (https://host/budgets/show/#)

**Extra info**
Debug information generated at 2019-11-22 11:46:34 America/NEW_YORK for Firefly III version **4.8.2-beta.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2-beta.1 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , docker_out |
| PHP version | 7.3.11 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-09-23 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**
![chart of all transactions](https://user-images.githubusercontent.com/1699801/69444172-ce070280-0d1d-11ea-97f2-4648ae99ddbd.png)

**Comment by JC5** [comment]
Yeah you're right! I'll rewrite the chart. Thanks for letting me know :)

**Comment by JC5** [comment]
Fixed in the next release.
