### ISSUE TITLE
Account name alias

### ISSUE THREAD

**Issue by revi** [firefly-iii/firefly-iii#2854]
**Description**

When I am paying things like (for example) Youtube Premium, Google Cloud Platform, and G Suite, it shows up as 'Youtube Premium', 'Google Cloud', and 'Google * G Suite' on my statements but I know I'm just paying one single company (Google), and I want to list all of them as single expense account.

**Solution**

Make it possible to store aliases, so typing other name can be (normalized? converted?) to the other 'correct' name.

**What are alternatives?**

I could create 3 expense accounts for those 3 uses.

**Additional context**

I also sometimes find that the card statement name and their [trade names](https://en.wikipedia.org/wiki/Trade_name) differs (sometimes as in: not that often or recurrent to make it recurring, but not just one-time)

**Bonus points**
I did my best not to create a duplicate issue (by searching) but please merge it with other task if there's same concept without using the word alias.

**Comment by JC5** [comment]
How do you import your data? CSV? Spectre? Something else?

**Comment by revi** [comment]
I mostly do it by hand, relying on autocomplete. My bank/card do not let me export CSV or otherwise firefly-acceptable format (they have an so-called 'OpenAPI' but you need to get a custom contracts involving $$$ so that's not an option), so I just compare what my system shows me and type it.

**Comment by JC5** [comment]
OK, so you could also choose to store everything under "Google" right? That's what I do. Why don't you edit the transactions so they all fall under "Google", delete the other expense accounts, and you're done.

**Comment by revi** [comment]
That is what I am currently doing, of course, but what I want is that when I type the incorrect name (ie. "Youtube Premium"), system would autocorrect me it as "Google". That is what I am requesting.

**Comment by JC5** [comment]
Ah I get it. Sorry, that's not going to be a feature.

**Comment by revi** [comment]
D'oh. Ok.

**Comment by marcelbrueckner** [comment]
> Ah I get it. Sorry, that's not going to be a feature.

Too bad. Would be interested in that feature as well as, for example, Amazon is appearing with different names on my statements, depending on whether I bought from Marketplace, directly from Amazon and how I paid it (direct debit vs. credit card payment).
