### ISSUE TITLE
404 because Extra slashes when updating expense

### ISSUE THREAD

**Issue by dkotama** [firefly-iii/firefly-iii#2855]
**Bug description**
I am running Firefly III version 4.8.1.8 , and my problem is:

When updating transaction its returning 404 because of extra slashes before /public path
![Screen Shot 2019-11-24 at 12 16 43](https://user-images.githubusercontent.com/5332757/69489578-33d9c280-0eb5-11ea-8429-8c9b5eb94368.png)

**Steps to reproduce**
Click action edit on expense tabs

**Extra info**
- Google chrome
- Installed from softaculous via cpanel

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2774
