### ISSUE TITLE
Text in "change transaction type" view is not localized

### ISSUE THREAD

**Issue by erdmenchen** [firefly-iii/firefly-iii#2857]
**Bug description**
In the demo instance (4.8.2-alpha6), when you switch the language to another than english (e.g. german), there are some places, where text is shown, that is not localized, because it is hard coded:

When changing the type of a transaction, the table header and description text is not german:

**Steps to reproduce**
English text is shown in non-english localization, because text is hardcoded in UI.

**Extra info**
Issue found in the latest version on the demo site.

**Bonus points**
![image](https://user-images.githubusercontent.com/6791096/69502445-a24b6e80-0f0f-11ea-84f8-891bc585283d.png)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2847

**Comment by erdmenchen** [comment]
#2847 is about incomplete language ressources.
This issue however is about hard coded text... so why the reference and why close?

See source code:
https://github.com/firefly-iii/firefly-iii/blob/4551dfe0e542f1dde433b0fb1664a2471bb7429c/resources/views/v1/transactions/convert.twig#L22

**Comment by JC5** [comment]
Sorry, I was to quick in my reply. I'll check it out.

**Comment by JC5** [comment]
This is fixed in the current beta, and translations will probably be included in the next release.

**Comment by erdmenchen** [comment]
Awesome!
Looking forward to test the latest version. Thank you very much!
