### ISSUE TITLE
Web Vpn

### ISSUE THREAD

**Issue by plainlytbrown** [firefly-iii/firefly-iii#2858]
I am Runing Firefly 4.8.1.8 via Synology NAS using docker

I also have a Synology RT2600 router that I use as a Web Vpn and SSL Vpn that I use on my mobile devices. 

When I connect my mobile devices to the Vpn I can easily access all of Firefly-iii, but when I connect to my Web Vpn, I am able to pull up the login page, but once I enter my credentials it will not redirect me to the application.

I'm not sure if you will need more information, because I'm not sure what more info you will want. I have just enough knowledge to make everything work but it feels like a house of cards ready to fall at anytime! 

As always Thanks so much for the help!

**Comment by JC5** [comment]
Sorry mate, I hoped anybody else would know. I have to admit I don't know what could be the problem :(
