### ISSUE TITLE
HTTP ERROR 500 after install

### ISSUE THREAD

**Issue by mingyech** [firefly-iii/firefly-iii#2859]
Hi, I'm trying to install firefly iii on my vps. I'm running centos 7.6, apache, mariadb, and php 7.3. I followed all the steps on the docs(https://docs.firefly-iii.org/installation/self_hosted). However I'm getting a http error 500 after installing. There is nothing in firefly-iii/logs/. I'm getting this error in my apache error log:
`[php7:error] [pid 17656] [client 173.245.52.133:53604] PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache directory (/var/www/expense.mingye.ch/firefly-iii/storage/framework/views/twig/be). in /var/www/expense.mingye.ch/firefly-iii/vendor/twig/twig/src/Cache/FilesystemCache.php:57\nStack trace:\n#0 /var/www/expense.mingye.ch/firefly-iii/vendor/twig/twig/src/Environment.php(487): Twig\\Cache\\FilesystemCache->write('/var/www/expens...', '<?php\\n\\nuse Twig...')\n#1 /var/www/expense.mingye.ch/firefly-iii/vendor/twig/twig/src/Environment.php(445): Twig\\Environment->loadClass('__TwigTemplate_...', '/var/www/expens...', NULL)\n#2 /var/www/expense.mingye.ch/firefly-iii/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig\\Environment->loadTemplate('/var/www/expens...', NULL)\n#3 /var/www/expense.mingye.ch/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('/var/www/expens...')\n#4 /var/www/expense.mingye.ch/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Twig.php(91): TwigBridge\\Engine\\Compiler->load('/var/www/expens...')\n#5 /var/ww in /var/www/expense.mingye.ch/firefly-iii/vendor/twig/twig/src/Cache/FilesystemCache.php on line 57`

I had run `chown apache:apache firefly-iii/ -R` and `chmod 775 firefly-iii/storage -R`, however the problem persists. 

I have tried to run version 4.8.1.8 and 4.8.2-beta.2, both runs with the same issue. 

here is my .env(https://pastebin.com/Y1GFAbhX) and apache config(https://pastebin.com/503knRfq)

Any help or suggestion is appreciated, Thanks.

**Comment by JC5** [comment]
The error is in the logs: “ Unable to create the cache directory”

Make sure that the user running Apache (usually www-data) has write access to the storage directory.

**Comment by mingyech** [comment]
Thanks for the response. On centos the default user running apache is "apache", which is currently the owner of the whole firefly-iii folder. It looks to me like the permissions are correct:

> [root@private1 views]# ls -al
total 4
drwxrwxr-x. 3 apache apache 34 Nov 25 17:44 .
drwxrwxr-x. 6 apache apache 81 Nov 25 17:44 ..
-rwxrwxr-x. 1 apache apache 18 Nov 25 17:44 .gitignore
drwxrwxr-x. 2 apache apache 24 Nov 25 17:44 v1
[root@private1 views]# pwd
/var/www/expense.mingye.ch/firefly-iii/storage/framework/views

Any ideas?

**Comment by mingyech** [comment]
Any suggestions please?

**Comment by JC5** [comment]
None really. If the `apache` user has write access to `/var/www/expense.mingye.ch/firefly-iii/storage` it should work.

**Comment by mingyech** [comment]
Hmm okay. I'll close it for now and reopen it if I figure it out.
