### ISSUE TITLE
Wrong owner of storage folder

### ISSUE THREAD

**Issue by SimonHaas** [firefly-iii/firefly-iii#2860]
Hi,

I am running Firefly III version 4.8.1.8, and my problem is:

While trying to setup firefly iii with docker-compose I ran into an issue which I managed to solve after a while. 

The logs were alright but when browsing to the domain I always got an 500 error with the 'fatal error page'. It was because the owner of the storage folder was not set to www-data by the entrypoint.sh script. I then did it by hand with 'sudo chown -R www-data:www-data ./firefly_iii'

This might not be a bug and just happend because the way I set it up (my volumes), but it would be nice to support this method, too.

My docker-compose.yml
`
version: "3.6"
services:
    traefik:
      hostname: traefik
      image: traefik:v1.7.16
      container_name: traefik
      restart: always
      domainname: simon-haas.eu
      networks:
        - default
        - traefik_proxy
      ports:
        - "80:80"
        - "443:443"
        - "8081:8080"
      labels:
        - "traefik.enable=true"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.simon-haas.eu"  
        - "traefik.port=8080"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.SSLHost=simon-haas.eu"
        - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.frontend.headers.frameDeny=true"
        # - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /home/pi/hdd/docker/traefik:/etc/traefik
        - /home/pi/hdd/docker/shared:/shared
        - /home/pi/fullchain.pem:/cert.pem
        - /home/pi/privkey.pem:/privkey.pem

    firefly_iii_app: 
      image: jc5x/firefly-iii:latest
      depends_on:
        - firefly_iii_db
      volumes:
        - ./firefly_iii/export:/var/www/firefly-iii/storage/export
        - ./firefly_iii/upload:/var/www/firefly-iii/storage/upload
        - ./firefly_iii/logs:/var/www/firefly-iii/storage/logs
      labels:
        - "traefik.backend=firefly"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:firefly.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=80"
      env_file: .env_firefly_iii

    firefly_iii_db: 
      image: "postgres:10"
      environment:
        - POSTGRES_PASSWORD=secret_firefly_password
        - POSTGRES_USER=firefly
      volumes: 
        - ./firefly_iii_db:/var/lib/postgresql/data

and other services

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
`

Debug information generated at 2019-11-26 18:00:55 Europe/Berlin for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , docker_out |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.121 Safari/537.36 Vivaldi/2.8.1664.44 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
Thanks for the pointer. I’ll update the entrypoint script to make sure this works as expected :)

**Comment by JC5** [comment]
I put it as the single last line in the entry point script, that should fix this.
