### ISSUE TITLE
Bad redirect after submitting a new transaction

### ISSUE THREAD

**Issue by th3error** [firefly-iii/firefly-iii#2861]
I am running Firefly III version 4.8.1.8

**Description**
Attempting to add a new transaction redirects me to a 404 page. It only started happening after I upgraded to the mentioned version above. Also, after going back the transaction does get added.

**Extra info**
Installation on CentOS 7.7. I don't know how to get the results of the /debug file in my installation. 

![78449448_2410254955959480_5878645896949792768_n](https://user-images.githubusercontent.com/31558868/69683629-2ba0a380-10be-11ea-807d-2bc511e5607b.png)

**Comment by JC5** [comment]
#2774
