### ISSUE TITLE
Wrong text on initial setup

### ISSUE THREAD

**Issue by WatskeBart** [firefly-iii/firefly-iii#2864]
When setting up your bank and amount etc, a typo is shown when running the Firefly in Dutch.

![image](https://user-images.githubusercontent.com/471361/69736665-46612f80-1133-11ea-98f1-b0e79565de27.png)

It says press **Opslaan**, but it shows **Invoeren**

This happens when you set the language to Dutch first and then complete the initial setup.

**Comment by JC5** [comment]
Feel free to submit a change on Crowdin :)

https://crowdin.com/project/firefly-iii

**Comment by WatskeBart** [comment]
Change firefly.php from **Opslaan** to **Invoeren** on Crowdin, so that the text matches the button.
