### ISSUE TITLE
my domain specified in env but doesn't work

### ISSUE THREAD

**Issue by Spinorog** [firefly-iii/firefly-iii#2865]
I am running Firefly III latest docker, tried develop tag

**Description**
installed without domain, later decided to add domain. To make it easier specified the domain in docker run command as

- e APP_URL=my.domain.com \

When I visit it i get login page "my.domain.com/login". When i enter credentials and press "Sign in" nothing happens. And Forget Password link has this URL: "http://localhost:8888/password/reset". When I go to 192.X.X.X:8888 everything is fine.

**Comment by JC5** [comment]
This isn't a Firefly III configuration issue, but a reverse-proxy configuration issue. What are you using as a proxy server?

**Comment by Spinorog** [comment]
Alright. Forgot two magical lines in nginx config:
```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
```
Sorry for my stupidity and thank you.

**Comment by JC5** [comment]
Not a problem!
