### ISSUE TITLE
Mixed transaction types for split transactions

### ISSUE THREAD

**Issue by myllaeri** [firefly-iii/firefly-iii#2866]
An account in my firefly-III installation represents the liability relationship between me and my partner.
Positive balance means she owes me money and vice versa.

I would like the account balance to be included in the net assets.

If I create the account as a liability account then I can create split transactions (with a split from source to expense account and one from source to liability account), the account balance is also correctly included in the dashboard under Net Worth.
However, the default financial report does not show the liability accounts.

Furthermore, expenses from the liability account to an expense account are not displayed in budget reports.

If I create the account as an asset account, I cannot create split transactions because Transfers, Incomes and Expense cannot be together in a split transaction.

I wish there could be split-transactions of different types (expense, transfer, income) in a single transaction.

**Comment by JC5** [comment]
Hi,

Use an asset account to represent this amount. That would include them in your reports. I'm working on a way to include liability accounts in reports, but it will never be the same as asset accounts. And keep in mind that split transactions will always be of a single type.
