### ISSUE TITLE
Liability account missing under accounts

### ISSUE THREAD

**Issue by MansoorMajeed** [firefly-iii/firefly-iii#2867]
I am running Firefly III version 4.7.4

**Description**
"Liabilities" is missing from the "Accounts" drop down. I can see that it is present in the demo site.

<img width="223" alt="Screenshot 2019-11-29 at 12 30 15 PM" src="https://user-images.githubusercontent.com/12676196/69850056-65cb9a00-12a4-11ea-8ef7-53473031e07e.png">

**Comment by JC5** [comment]
I don’t think that version supports liability accounts. 4.7.4 is pretty old.

**Comment by MansoorMajeed** [comment]
@JC5 You're right..:) I was following instructions and didn't realize that composer installed an older version. Now I am trying 4.8.2
```
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated 4.8.2                                                                                           
 
 [InvalidArgumentException]
  Could not find package grumpydictator/firefly-iii with version 4.8.2 in a version installable using your PHP version 7.2.24.
```

Does the latest version require php 7.3?

**Comment by JC5** [comment]
Yes, it does.

**Comment by MansoorMajeed** [comment]
You the man! :) Upgraded it and I can see the Liability accounts.
Thanks a lot for this wonderful application
