### ISSUE TITLE
Bills : Next expected match

### ISSUE THREAD

**Issue by Gus19** [firefly-iii/firefly-iii#2868]
I am running Firefly III version 4.8.1.8

**Description**
I create a new bill with :
- Date : 2019-11-25
- Repeats : every half year

It's ok, the next expected match is on : November 25, 2019
Then I create a expense with the current date, the rule connected the expense and the bill correctly.

Now, I'm expecting to find May 25, 2020 on the next expected match, but it's November 25, 2020.

Can you tell me why ?

Thanks !

**Comment by JC5** [comment]
I see what you mean. It's a bug. I'll mark it as one and I hope to have it fixed in the next release.

**Comment by JC5** [comment]
Although, come to think of it. "November 25, **2019**" is the bug. Not the 2020 one.

A bill starts on 25 nov 2019 and repeats every 6 months.

- On 25 nov and before, expected date must be 25 nov 2019
- After 25 nov, apparantly no transaction is coming, date must be 25 may 2020

**Comment by Gus19** [comment]
Ah ! I get it, it's handle by period.

So, for manage a process like this : 
1. I receive a bill every 21th
2. I am automatically charged 3 days later

In this configuration, I need to choose the 24th on bills date and not the 21th.
That's right ?

**Comment by JC5** [comment]
Exactly. I usually use the 1st of the month, regardless of the actual payment date.

**Comment by Gus19** [comment]
Ok ok thank you :)

**Comment by JC5** [comment]
OK, so I took another look at the code, and there's not much for me to fix. I did add some debug logging so if you run into issues next time, we can check it out.
