### ISSUE TITLE
Recurring transactions doesn't work after 1month of usage

### ISSUE THREAD

**Issue by alphat5** [firefly-iii/firefly-iii#2869]
I am running Firefly III version 4.8.2

**Description**
I have 4 recurring transactions set-up which should add 4 bank transfers. But the issue is, they don't work and I'm not seeing them in the overview of the concerned bank account in FFIII.

I still have this message at the top: 
`It seems the cron job that is necessary to support recurring transactions has never run. This is of course normal when you have just installed Firefly III, but this should be something to set up as soon as possible. Please check out the help-pages using the (?)-icon in the top right corner of the page.`

**Extra info**
OS: Debian 9 running on a VPS by OVH
Browser: Brave & Chrome
Running the service with Docker (compose)

If you need any other information, please ask. 
Thanks in advance,
Best,

**Comment by JC5** [comment]
https://docs.firefly-iii.org/advanced-installation/cron

**Comment by alphat5** [comment]
> https://docs.firefly-iii.org/advanced-installation/cron

Stupid I am. didn't see this...

So if I understand correctly, because I'm running it with docker-compose. I just need to add this in the docker-compose.yml right? 

`cron:
  image: alpine
  command: sh -c "echo \"0 3 * * * wget https://<Firefly III URL>/cron/run/<TOKEN>\" | crontab - && crond -f -L /dev/stdout"`

**Comment by JC5** [comment]
Yes, that should do it.

**Comment by alphat5** [comment]
> Yes, that should do it.

Thanks man! 
Have a nice weekend!

**Comment by JC5** [comment]
:+1:
