### ISSUE TITLE
"Initial Balance for <account>" not editable

### ISSUE THREAD

**Issue by Crotha** [firefly-iii/firefly-iii#2871]
**Bug description**
I am running Firefly III version 4.8.1.8 and my problem is:

Editing the "Initial Balance for <account>" seemingly just reloads the page.

**Steps to reproduce**
Click here:
![grafik](https://user-images.githubusercontent.com/47434645/69904800-669b2380-13ab-11ea-82ad-8c8b82d29d6c.png)

**Extra info**
Debug information generated at 2019-11-30 19:56:04 Europe/Vienna for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.5 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 23:59:59 |
| Session first | 2019-11-30 00:00:00 |
| Error reporting | ALL errors |
| Host | WINNT |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | 'English_United States.1252' |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0 |
| Loaded extensions | Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, wddx, xmlreader, xmlwriter, apache2handler, openssl, curl, com_dotnet, fileinfo, gd, gettext, gmp, intl, imap, ldap, mbstring, exif, mysqli, Phar, pdo_mysql, pdo_sqlite, soap, sockets, sqlite3, xmlrpc, xsl, Zend OPcache, xdebug |

**Bonus points**
Drawing of me sitting in front of a computer after long hours of trying to get Firefly-III to run:
![grafik](https://user-images.githubusercontent.com/47434645/69904830-fe007680-13ab-11ea-91a7-3c736c451282.png)

(I am a noob in this regards and startet with a Windows-PC and no clue.
I am rather sure it's a bug, though, because I can replicate it on the demo-page)

**Comment by JC5** [comment]
Ten points for the drawing! 👍😁

To edit the opening balance of an account however, edit the account itself. 

As an enhancement, I’ll make sure that there will be a message explaining that.

**Comment by Crotha** [comment]
Oh!    
I never thought of that. That works flawlessly.  

Thank you. I basically deleted and recreated the account (I was, after all, just opening it and mistyped the opening balance).
Thank you for the fast answer :)
