### ISSUE TITLE
404-error when creating or updating transactions

### ISSUE THREAD

**Issue by Crotha** [firefly-iii/firefly-iii#2872]
I am running Firefly III version 4.8.1.8.:

When editing transactions, after clicking on "Update transaction" I get a 404-error.  
The transaction IS updated, so the bug is not prohibiting the editing. 

The error reads as follows:
![grafik](https://user-images.githubusercontent.com/47434645/69904903-28066880-13ad-11ea-91ce-d7359f43b4c0.png)

I am also getting it when creating a transaction:   
![grafik](https://user-images.githubusercontent.com/47434645/69904933-c1357f00-13ad-11ea-8add-d6b4be31f183.png)

**Extra info**
I just opened another ticket for a bug I can reproduce on the demo. This one I can't reproduce in the demo.
I am not entirely sure what went wrong here. It seems to be only with transactions - no matter which kind - both when creating or editing.
It is mainly an annoyance, tbh, as whatever I intented to do is done - but I'd like to know, if possible, where I went wrong here.
Thank you!

**Comment by JC5** [comment]
This is the same bug as #2774, and it should be fixed in the new release. Could you try to upgrade to see if that fixes the issue?

**Comment by Crotha** [comment]
I just updated (thank you for the documentation! would've worked like a charm wouldn't I have a stupid mistake in the very beginning)! 
I am sorry, I completely missed that there was an update just two days ago.   

Works with no problems now, thank you for the really fast answer! 
  
As I am already here, one other small thing that is probably not related but also not really that important:   
The help page (the small question mark at the top) only ever tells me, that there is no help-page in my language available. 
![grafik](https://user-images.githubusercontent.com/47434645/69905234-f7283280-13b0-11ea-9021-9c11676ba251.png)

Which language-locale is pulled here? While Firefox should prefer and use [en], Windows is using the locale [EN-AT].    
Might this be the problem?

**Comment by JC5** [comment]
Mmmmm 🤔

I have to dig deeper. I hope to tell you tomorrow or next week :)

**Comment by Crotha** [comment]
To add to this, because I played for bit: 
Changing the language in Firefly doesn't change the help text thingy, as well as changing the firefox language settings.  
But, and that is interesting imo:   
When I change it in firefly to German, it says (in german, obviously) "the helptext is not yet available **in german**" while when I have firefly in english, it says "the helptext is not yet available **in your language** .    
Maybe some locale is not correctly detected there?    

I assume this is less of a problem for those who are not self-hosting on a wampserver installed on their windows-machine :D     

If you need anything else, I'm happy to supply as best as possible.
Shall I open a separate ticket (or edit the title) or something, just for tracking purposes?

**Comment by JC5** [comment]
The instructions for translation are specifically to translate "your language" in your language, ie. change it to English, Dutch, German, etc.

If you get a help page when you click on the (?) icon depends on the language you've set in Firefly III. The browser doesn't come into it. However, Firefly III has to connect to GitHub for the latest translations.

Which page are you trying to see the help pages for?

**Comment by Crotha** [comment]
It happens on all pages.   
Hm...maybe it just can't connect to GitHub? I have to look into that.

**Comment by JC5** [comment]
That could be the case. Check out the demo site to see what should happen.
