### ISSUE TITLE
This account name is already in use

### ISSUE THREAD

**Issue by stephenkjones** [firefly-iii/firefly-iii#2873]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is if you delete an account and all of the transactions you cannot add an account with that same name later on. 

**Steps to reproduce**
Create an account and add transactions. Delete the account and transactions. Try to add an account with the exact same name and you get the error, "This account name is already in use."

**Extra info**
Self-hosted in Docker on unRAID

**Bonus points**
Screenshot attached.
<img width="1521" alt="Screen Shot 2019-11-30 at 7 18 34 PM" src="https://user-images.githubusercontent.com/58376803/69907647-59c80100-13a6-11ea-9fae-a96159930e6e.png">

**Comment by JC5** [comment]
I can't replicate this. I just removed an asset account and created it and it works like a charm. Could you share the content of /debug?
