### ISSUE TITLE
Bug when editing Transaction

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2874]
Hi James, 

I am running 4.8.2

Found a bug when editing transactions in the web ui. Create a new account `Test account`. Edit expenses. Change source account to `Test account`. Click update transactions. The web browser will show a bunch of json.

Example:  https://demo.firefly-iii.org/json/accounts?transaction_group_id=406&message=updated

**Comment by emansih** [comment]
I can't seem to replicate the bug anymore

**Comment by JC5** [comment]
It's a tricky bug. I know it happens. I hoped I fixed it but every now and then it pops up again. I'll take another look at the code.

**Comment by JC5** [comment]
I think I introduced a very silly bug, and it should be fixed in the next release. Thanks for bringing it to my attention! :+1:
