### ISSUE TITLE
Bulk transaction editing: changing destination account

### ISSUE THREAD

**Issue by raoulvdberge** [firefly-iii/firefly-iii#2875]
**Description**
When selecting multiple (expense) transactions and modifying them, it would be cool if I were able to change the destination account of all those transactions.

Currently, the bulk editing only supports changing category, tag and budget.

This is very useful when during importing the bank didn't supply the destination account number in the CSV.

Changing the source account in bulk would be probably helpful too.

**Solution**
When selecting multiple (expense) transactions and modifying them, having an option to change the destination account.

**What are alternatives?**
The only alternative that I know of is going over each transaction one by one and changing the destination account manually.

**Additional context**
I'm not super familiar yet with Firefly or the expense accounts functionality, so if this feature request is out of place or not logical, please let me know.

**Bonus points**
None.

**Comment by JC5** [comment]
I'll think about it. It's not something that happens all to often for most people
