### ISSUE TITLE
Extra trailing zeros in amount field when editing transaction

### ISSUE THREAD

**Issue by michaeljandrews** [firefly-iii/firefly-iii#2876]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

The Amount field in the Edit Transaction form does not seem to respect the Number of Decimals set in the Currency settings in Options. I am using USD as the default currency and many trailing zeros are appearing in the amount field when editing a transaction.

**Steps to reproduce**
Edit any transaction

**Extra info**
<img width="1209" alt="Screen Shot 2019-12-02 at 7 08 00 PM" src="https://user-images.githubusercontent.com/58296371/70005392-76477300-1537-11ea-9f7e-17df30259636.png">

**Comment by JC5** [comment]
What DB are you using?

**Comment by michaeljandrews** [comment]
I'm running MariaDB 10.1.38 on a Raspberry Pi 3b+ with Stretch lite.

**Comment by JC5** [comment]
Thanks. Which browser is this? Chrome, by any chance?

**Comment by michaeljandrews** [comment]
Yes, Chrome on Ma. I also tested on Safari on Mac and iOS, Edge and Chrome on Windows 10 and got the same results. Also seeing it on the demo site.
<img width="976" alt="Screen Shot 2019-12-03 at 5 28 29 PM" src="https://user-images.githubusercontent.com/58296371/70095350-83756800-15f2-11ea-8f4d-04f7881e8a27.png">

**Comment by JC5** [comment]
Ah I see it. Firefox renders the numbers correctly. I'll mark it as a bug and see where the difference comes from.

**Comment by JC5** [comment]
This also fixes an issue another user had but for the life of me I can't remember who. Well, it's fixed too! :+1:

**Comment by gregoo** [comment]
> This also fixes an issue another user had but for the life of me I can't remember who. Well, it's fixed too!

#2790 😁?
