### ISSUE TITLE
double records

### ISSUE THREAD

**Issue by filoor** [firefly-iii/firefly-iii#2877]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

I having issues with transactions between my own accounts.

If you see IMG1 that's my import .csv ("I deed change the names of the accounts for now")
IMG1:
![image](https://user-images.githubusercontent.com/3647638/70035489-358d3f80-15b3-11ea-92ad-7e2b6c6c23a6.png)

But if you look to Firefly "IMG2" it will show 2 transactions to "Account A"
IMG2:
![image](https://user-images.githubusercontent.com/3647638/70035322-ee06b380-15b2-11ea-90fb-9498f8897a90.png)

Could it be becouse the description is empty of the transaction?

 did open this issue before #1833

**Comment by JC5** [comment]
I'll need to know a bit more to be sure of the cause.

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by JC5** [comment]
Try to import the two lines again. If you can, send them to me. Feel free to censor stuff but make sure you censor equally in both lines. Include the config you've used. I'll see if I can replicate the issue.

**Comment by filoor** [comment]
@JC5 Thank you ,

Im not able to import the lines it will say that it already exist.
I can see that the dublle import was in import  TAG "YSXOwsLKLgc7". "IMG1"
in which tables should i remove the rows from this import so i can re create it again and have the logs this time

IMG1:
![image](https://user-images.githubusercontent.com/3647638/70141297-0ea83980-1697-11ea-8722-085983103144.png)

**Comment by filoor** [comment]
I have deleted the records from "finanace.transaction_journals" and "finanace.transactions"
And it did now not import it double.

I will delete later today all my transactions and do a new import and see what happens.

**Comment by filoor** [comment]
I found some import conflicts.
1:
In the Rabo csv the if you transfer money to your second account it will add
"Afschrijving" for account A
and
"bijschrijving" for account B
to the description
"IMG1":
![image](https://user-images.githubusercontent.com/3647638/70234088-239ccf80-1760-11ea-801f-0cefc60eea02.png)


SO what i did in the CSV before import is to remove booth from the description

2:
in img2 i did a payment but the machine did not give my product so it did pay it back,
and i did the payment again and now it has the same values 2 so firefly thinks that the payment is a double row.
img2:
![image](https://user-images.githubusercontent.com/3647638/70233963-e46e7e80-175f-11ea-924a-306194448937.png)



3:
For img3 i did 2 transactions with the same amount to my other account and it also sees it as double transaction.
img1:
![image](https://user-images.githubusercontent.com/3647638/70234132-3ca58080-1760-11ea-8673-65e52f67e256.png)



Is it maybe possible to show the double lines when you import and select which lines to ignore?

**Comment by JC5** [comment]
Not yet, bot.

**Comment by JC5** [comment]
Thanks for waiting.

Regarding point 1, Firefly III can only merge the transactions as one when the descriptions and everything are exactly the same. This used to be the case for Rabobank, but no longer it seems.

Regarding 2 and 3, if you include the "volgnummer" in your import, for example by using the "external identifier", Firefly III should no longer consider them duplicates.

**Comment by Kramins** [comment]
I am also having the same issue with duplicate records not being imported. My bank doesn't add enough details to the csv and firefly detects them as duplicate transactions.

**Comment by JC5** [comment]
That’s not something I can help you with. Use excel or a similar tool to add something unique to each row, like a number.
