### ISSUE TITLE
All operations shown even when selecting a time period 

### ISSUE THREAD

**Issue by kczav** [firefly-iii/firefly-iii#2878]
I am running Firefly III version 4.8.2

**Description**
When selecting a budget, you can see operations related to this budget for all times even when selecting only a time period. 
I would expect to see only operations from the selected time period.

**Extra info**
 
Debug information generated at 2019-12-03 19:23:43 Europe/Paris for Firefly III version **4.8.2**.
| Variable | Content |
| --- | --- |
| FF version | 4.8.2 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.12 |
| Display errors | Off |
| Session start | 2019-11-01 00:00:00 |
| Session end | 2019-11-30 00:00:00 |
| Session first | 2019-09-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, zip, Zend OPcache |

**Bonus points**

The 2 following screenshots are from the same page.

This screenshot shows the selected period (November only):
![date](https://user-images.githubusercontent.com/11700864/70077865-eae6e400-1601-11ea-8c87-3ef18bc6cca3.png)
This screenshot shows the operations displayed down below on the page (Nov - Oct - Sept):
![time_period](https://user-images.githubusercontent.com/11700864/70077948-19fd5580-1602-11ea-9cd1-ca2ee2b99e30.png)

**Comment by JC5** [comment]
That can be fixed. An easier way to manage past periods in your budgets would be to set limits for each time period you want to see (ie. monthly).

**Comment by kczav** [comment]
Thanks James for the quick answer.
If by setting the limits for each time period I want to see you are
refering to the "Options -> Preferences -> Layout -> One Month", it is
already set like this.
If it is not what you meant, could you just elaborate on your advice a tiny
bit more :-)

Cheers
Xavier

**Comment by JC5** [comment]
Just set a budget for each month (under /budgets)

**Comment by kczav** [comment]
Hi James.
I looked at the fixed you made and noticed what seems to be a typo:
I think
`        // use session range:`
`       $start = session('start');`
`      $end = session('start');`
should be
`       // use session range:`
`        $start = session('start');`
`        $end = session('end');`

Regards,

**Comment by JC5** [comment]
Oh nice, thanks, I'll pick it up!
