### ISSUE TITLE
403 Forbidden You don't have permission to access

### ISSUE THREAD

**Issue by mversteegh** [firefly-iii/firefly-iii#2879]
I am running Firefly III version 4.8.2

**Description**
I'm trying to generate a report, for example based on tags. If I submit the query I get the message that I don't have permission to access /public/reports/tag/78/19,32,43,31,37,46,33,9,27,42,25,24,8,4,2,44,5,3,7,6,45,48,17,47,20,21,28,35,38,41,39,34,30,40,29,16,23,36,22,13,15,12,11/20191101/20191130 on this server.

**Extra info**
Firefly runs a shared hosting (Versio). If more info needed, let me know and I'll collect it.

**Comment by JC5** [comment]
It looks like the URL is too long for your web server to handle. There's not much I can do about that.

**Comment by Moc** [comment]
Check the apache error log (through your hosting control panel). It may provide more clues, perhaps some form of server configuration/security rule is triggered.
