### ISSUE TITLE
Error: "A group title is mandatory when there is more than one transaction."

### ISSUE THREAD

**Issue by vlcty** [firefly-iii/firefly-iii#2881]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

When you forget to enter a description for a split withdrawl you are prompted with an error message. That's okay. But after clearing the error by entering a description, the submit button is still disabled.

**Steps to reproduce**

* Create a new withdrawl
* Click on "Add another split"
* Don't fill out the upper text box for "Description of the split transaction"
* Fill in values for both splits
* Click on "Submit"
* The error message "A group title is mandatory when there is more than one transaction." will appear near the text box
![Bildschirmfoto 2019-12-07 um 16 06 52](https://user-images.githubusercontent.com/5420564/70376667-af9f2a80-190b-11ea-85c5-18b0f2ca4ba8.png)
* Fill in a value for it
* You can't click on submit again. You have to reload the page.

**Comment by vlcty** [comment]
Short addition: It's probably an easy fix. If you remove the disabled attribute from the button you can submit it again without any problems.

**Comment by JC5** [comment]
I see what you mean. For some reason, it only happens what that error is the *only* error. I'll pick it up.

**Comment by JC5** [comment]
This will be fixed in the next release.
