### ISSUE TITLE
Budget page - Sum 

### ISSUE THREAD

**Issue by 4oo4** [firefly-iii/firefly-iii#2882]
I know I've seen discussion before about why the budgeted amount needs to be entered manually by the user, versus Firefly just auto-summing the amounts entered in each budget category and automatically setting that as the budgeted amount.

I'm not asking Firefly to do that, but rather to still sum what's been entered in each category, and then only suggest that amount to the user for setting the actual budgeted amount (perhaps at the top or bottom of the table of budget categories?).

Currently, I have to manually add up those amounts and that's error prone for me while typing them all in to a calculator. I totally get why the user must set the budgeted amount for each time frame, but having Firefly at least pre-calculate that sum for me would make things much more convenient and make setting budgets each month that much easier. 

Cheers

**Comment by JC5** [comment]
I always do it the other way around: I know the full amount and I divide it over the budgets. But a sum wouldn't be bad, I'll write it down as a feature.

**Comment by JC5** [comment]
The sum is listed here:

<img width="442" alt="Screen Shot 2020-01-24 at 21 34 30" src="https://user-images.githubusercontent.com/5889984/73102054-f3181d00-3ee8-11ea-859a-a1bce1e9467f.png">

Left top on the /budgets page.

**Comment by JC5** [comment]
This issue will be closed, now that the first alpha of 5.1.0 is out. Keep an eye out on the release page. If something comes up, please open a new issue. Thanks!
