### ISSUE TITLE
Account not showing on Dashboard

### ISSUE THREAD

**Issue by tgkenney** [firefly-iii/firefly-iii#2883]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

I have an asset account created and with transactions.  The account is "active" but it is not showing up on the front page of Firefly III.  

**Steps to reproduce**

Not really sure, I have 7 total accounts, but I created a new account as a test and that one shows on the dashboard fine.  I have also tried marking the account as Inactive and then back to active with no luck

I am able to select the account just fine when creating transactions, and any links to the account on transaction pages, etc lead to the account fine.  It's just the dashboard not showing it

**Extra info**

Debug information generated at 2019-12-08 19:22:42 UTC for Firefly III version **4.8.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.12 |
| Display errors | Off |
| Session start | 2019-12-01 00:00:00 |
| Session end | 2019-12-31 23:59:59 |
| Session first | 2016-02-05 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
Make sure you also select it under Preferences.

**Comment by tgkenney** [comment]
I must just be an idiot, didn't realize there was a toggle there.  That fixed it, thanks!
