### ISSUE TITLE
Importing with Spectre and duplication

### ISSUE THREAD

**Issue by chrispazz** [firefly-iii/firefly-iii#2884]
Version 4.8.2

I need to know if using Rules on imported transaction could broke the detection of duplicated transaction. I discovered that re-importing the same transactions can generate duplicates if you change some attributes with rules.

**Comment by chrispazz** [comment]
Correction: almost every import with Spectre (with various banks) generate duplicates.

**Comment by JC5** [comment]
Thanks for letting me know. I can do a deep-dive but I have only access to the test portal of Spectre. I'll need debug info to see what's causing the duplicates in your case.

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by JC5** [comment]
Using my test connection to Spectre, I wasn't able to import duplicated transactions.

**Comment by chrispazz** [comment]
After first duplications, it seems not to work correctly.
I think that changing transaction to trasnfers using rules could be the problem. I will try again and let you know.

Thank you

**Comment by JC5** [comment]
That won’t be the case. Rules are applied after transactions are created, and the duplication check will be executed before that.
