### ISSUE TITLE
Progressive Slowing Down of the App due to exponential increase of DB size

### ISSUE THREAD

**Issue by mbacicc** [firefly-iii/firefly-iii#2887]
I am running Firefly III version 4.8.2 (updated just this morning from 4.8.1.8), and my problem is:
I noticed a progressive slowing down of the system after upgrading from version 4.7.16 to 4.8.1.8 and 4.8.2.
The issue was already existing before upgrade from 4.8.1.8 to 4.8.2.
I use an external software which syncs transactions from an external custom software to Firefly III through APIs every 10 minutes, in particular using the PUT transaction endpoint.
I was trying to optimize MySQL by increasing cache size and try to play with indexes when I noticed that the PUT operation in the new API version keeps the old transaction and transaction_journal, and creates a new record in the DB tables.
This behavior increased consistently the size of transactions and transaction_journals tables to 1.2M and 600 k rows respectively, causing a extremely slow loading of the pages of the web app.
This behavior was not happening in FF 4.7.1.6 in past.

![image](https://user-images.githubusercontent.com/46646960/70636566-0d967f80-1c36-11ea-81da-734b0acaab8c.png)
![image](https://user-images.githubusercontent.com/46646960/70636747-55b5a200-1c36-11ea-9417-ad456347b5dd.png)

Is it a wanted behavior? Can I safely delete all the records where deleted_at field is not null to have a working interface?

Thank you for your work!

**Comment by JC5** [comment]
Thanks for opening the issue. This shouldn't happen of course but it's a result of updating transactions every 10 minutes, presumably even when there are no changes to be recorded. The database is responsible for making sure that data-access is prompt, and I was under the impression that MySQL could handle way more than 1.2M rows. Then again, these are pretty complex JOIN's.

You can safely delete everything where `deleted_at` is not null. 

If anything, this behavior should stop now you've migrated and upgraded to 4.8.2

**Comment by mbacicc** [comment]
Thank you James for your prompt answer.
I know it's due to my use of the API in a super - simplified way, as you imagined I don't check if there is difference, i keep the transaction ID and do a PUT on top of it, even if data don't change.
I just wanted to let you know that I was doing the same on FF 4.7, and it was not creating any duplicate row, just rewriting the original transaction id (from what I can understand), but in both 4.8.1.8 and 4.8.2 it is behaving like in the previous screenshots.
I did the delete you suggested by running :
DELETE FROM firefly.transactions where deleted_at is not null;
DELETE FROM firefly.transaction_journals where deleted_at is not null;
it took around 10 minutes for the first query, 4 minutes for the second on a VM with 8 vCPUs E5645 @ 2.40GHz and 8 GB of ram, OS Ubuntu 18.04.3 LTS. Of course the deleted_at field is not indexed, that's why it was so slow to do the delete.
Now page loading is fast. Do you think it will be modified the API PUT endpoint to prevent duplication of rows in future, or I should change the sync process by updating only on change?

**Comment by JC5** [comment]
> Do you think it will be modified the API PUT endpoint to prevent duplication of rows in future, or I should change the sync process by updating only on change?

This is already happening. I just tried it on my local instance. If I PUT an existing transaction with or without changes to the transaction, the existing transactions are updated. No new ones are created.

**Comment by mbacicc** [comment]
Unfortunately I'm still noticing the same behavior.
I prepared two screenshots related to the same transaction group (1076) after one PUT.
This is the transaction_journal table:
![journal](https://user-images.githubusercontent.com/46646960/70642106-f740f180-1c3e-11ea-9cd5-5212f865d27a.PNG)
And this for transactions table:
![transactions](https://user-images.githubusercontent.com/46646960/70642206-1b9cce00-1c3f-11ea-9e0f-877edf9bdb2c.PNG)
where i selected the records linked to the previous group.

I do the PUT with Python 3 with the following code:
```
    transaction = []
    transactions.append(
                        {
                            "transaction_journal_id": 0, 
                            "type": "withdrawal",
                            "date": date.strftime("%Y-%m-%dT%H:%M:%S"),
                            "payment_date": date.strftime("%Y-%m-%dT%H:%M:%S"),
                            "invoice_date": date.strftime("%Y-%m-%dT%H:%M:%S"),
                            "amount": xxxx,
                            "description": "desc",
                            "category_id": yyy,
                            "source_id": zzz,
                            "destination_id": ttt,
                            "internal_reference": "",
                            "notes": "",
                            "reconciled": "false",
                            "tags": tags
                        }
                    )


... multiple splits in the same group, up to 3 transactions ...


    trans_group = {
                    "type": "withdrawal",
                    "description": "desc",
                    "group_title": "desc",
                    "date": date.strftime("%Y-%m-%dT%H:%M:%S"),
                    "payment_date": date.strftime("%Y-%m-%dT%H:%M:%S"),
                    "invoice_date": date.strftime("%Y-%m-%dT%H:%M:%S"),
                    "internal_reference": "code",
                    "notes": "note",
                    "transactions": transactions,
                    "tags": tags
                }

    url = "http://" + sfc_common.firefly_host + "/api/v1/transactions/" + str(transaction_id)
    headers = {'Content-type': 'application/json; charset=UTF-8',
                'Accept': 'application/json; charset=UTF-8',
                'Authorization': 'Bearer ' + firefly_access_token}
    try:
        ff_data = json.dumps(trans_group)
        response = requests.put(url, data=ff_data, headers=headers)
        operation_result_object=json.loads(response.content)
        return operation_result_object
    except:
        return None
```


Could it be "transaction_journal_id": 0 ? If I don't put it, the API would deny the operation.
On FF 4.7, I was saving the ID of each split, here I thought it would be enough to store the main transaction ID, since it seemed working from the interface, but it was in fact increasing the number of floating deleted transactions in the DB.

Thank you for your help!

**Comment by JC5** [comment]
Yes, it's the `transaction_journal_id: 0`. That causes Firefly III to recreate everything. If you can submit the original ones with each transaction, Firefly III will update the original ones instead of recreating each entry.

**Comment by mbacicc** [comment]
Yes, I'll try that tomorrow. It seemed working, that's way I didn't add the effort to store each single transaction id, but only the group.
I'll let you know how it goes.
