### ISSUE TITLE
Yearly bills

### ISSUE THREAD

**Issue by chrispazz** [firefly-iii/firefly-iii#2888]
I always track my yearly bills but I would like to track the pro-quota every month so to reach the correct amount when the bill is issued to me.
It is the typical way with envelope budgeting.

Which is the best way to achieve this in Firefly? Budgets, piggy banks or bills?

**Comment by JC5** [comment]
I do this myself using piggy banks. It’s not ideal but I haven’t had the time to build a proper solution.

**Comment by chrispazz** [comment]
I think it is ok with Piggy Banks.
The easy way to handle this cases could be to link a Piggy bank to a specific Bill where the Bill amount of each month is determined by the "Suggested per month" value of the Piggy bank.

It should work good... :)
