### ISSUE TITLE
Saving Account, real or virtual

### ISSUE THREAD

**Issue by chrispazz** [firefly-iii/firefly-iii#2891]
Hello! Still trying to use Firefly instead of ynab... :)

Currently I have only real accounts that I sync with Spectre.
When speaking about saving (and Piggy banks), it is better to use a real account for saving pourpose (I mean a real separated account to be synced with spectre too) or using a virtual saving account is ok (opening it only in Firefly)?

I could use the virtual way by manually entering transfers to it to store my "savings" and "budgeted amounts" for future expenses but in this way I loose the control on the real account balance....

Which is the best way? I would like to be sure about how my real accounts balances are allocated for real recurring expenses other than future forecasted expenses...

Thank you

**Comment by JC5** [comment]
Glad to hear it!

I tend to make Firefly III a copy of my accounts, so no virtual or fake ones. But for Firefly III itself it doesn't really matter: it's all about what you prefer to do. The advantage of following your bank account(s) is that you're always sure it works as expected.
