### ISSUE TITLE
Carry over budget figures from one month to the next month

### ISSUE THREAD

**Issue by kczav** [firefly-iii/firefly-iii#2892]
**Description**
Hello,

(I hope this was never discussed before, I couldn't find anything related to this anywhere.)
Is there a way to carry over budget figures from one month to the next month?
This way, I could just adjust some budget for the current month without having to refill all of them.
Quite often, they do not change from one month to the other.

Thanks a lot for this amazing software.
K.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2578
