### ISSUE TITLE
Installing in a FreeNAS Jail: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by DamageIncorporated** [firefly-iii/firefly-iii#2893]
I am running Firefly III version 4.8.2

**Description**
I'm trying to install Firefly inside an iocage-jail on FreeNAS by this [how-to](https://forum.freenas-community.org/t/firefly-iii-personal-finance-manager-in-a-jail/).

I have to admit that I barely understand this stuff, but most of the how-to where semi-understandable to me That's okay for me as I'm running this in a jail that's only accessible from the LAN and if i really mess up i can just destroy the jail and move on :-)

Everything seemed to work until I had to initialise (?) the database with the command
`sudo -u www php artisan migrate:refresh --seed`

The result:
`In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
  chema.tables where table_schema = firefly and table_name = migrations and t  
  able_type = 'BASE TABLE')                                                    
                                                                               

In PDOConnection.php line 31:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 27:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             
`

I've tripple checked database credentials and did also read Issue #1484 to shed some light on my problem. I also tried to juggle with configuration values (and reverted them to default afterwards) but the error messages didn't change.. At least I also didn't blow up the whole thing yet :-)

**Comment by JC5** [comment]
Can you ping the database from the Firefly III image?

**Comment by DamageIncorporated** [comment]
You mean the networking command "ping"?

In my case firefly and the database exist in the same jail and should be able to talk to each other "locally". When I juggled with configuration values I tried to use 127.0.0.1, localhost and the external address (don't know if the latter made any sense) just to guess, but the error stayed the same.

I'll take a short break now before I re-check the configuration later, maybe I just don't see the wood for the trees :-)

**Comment by JC5** [comment]
Yes, exactly. Although "connection refused" could also be an indicator of the SQL server actively refusing the connection. So the system works, but maybe the DB is not listening on the right IP or something.

**Comment by DamageIncorporated** [comment]
Hey,

I've found a hint in reply 16 of [this completely unrelated stackoverflow thread](https://stackoverflow.com/questions/35394230/sqlstatehy000-2002-connection-refused-within-laravel-homestead):

I'll try to document that here for the next poor person to run into a similar problem:

The last change I made to the .env file was setting `DB_HOST=localhost` which had been `DB_HOST=firefly` (which is actually the hostname of said Jail or container in FreeBSD).

I don't know if that fixed it because I believe that the changes i made (and sometimes reverted) before were never applied because I didn't run `php artisan config:cache` after saving the .env file.

This time I did it and voila...success:

`root@firefly:/usr/local/www/firefly-iii # php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
root@firefly:/usr/local/www/firefly-iii # sudo -u www php artisan migrate:refresh --seed
Migration table not found.
Migration table created successfully.
Migrating: 2016_06_16_000000_create_support_tables
Migrated:  2016_06_16_000000_create_support_tables (2.69 seconds)
Migrating: 2016_06_16_000001_create_users_table
Migrated:  2016_06_16_000001_create_users_table (0.11 seconds)
Migrating: 2016_06_16_000002_create_main_tables
Migrated:  2016_06_16_000002_create_main_tables (23.68 seconds)
Migrating: 2016_08_25_091522_changes_for_3101
Migrated:  2016_08_25_091522_changes_for_3101 (0.01 seconds)
Migrating: 2016_09_12_121359_fix_nullables
Migrated:  2016_09_12_121359_fix_nullables (0.06 seconds)
Migrating: 2016_10_09_150037_expand_transactions_table
Migrated:  2016_10_09_150037_expand_transactions_table (0.02 seconds)
Migrating: 2016_10_22_075804_changes_for_v410
Migrated:  2016_10_22_075804_changes_for_v410 (0.16 seconds)
Migrating: 2016_11_24_210552_changes_for_v420
Migrated:  2016_11_24_210552_changes_for_v420 (0.02 seconds)
Migrating: 2016_12_22_150431_changes_for_v430
Migrated:  2016_12_22_150431_changes_for_v430 (1.57 seconds)
Migrating: 2016_12_28_203205_changes_for_v431
Migrated:  2016_12_28_203205_changes_for_v431 (1.04 seconds)
Migrating: 2017_04_13_163623_changes_for_v440
Migrated:  2017_04_13_163623_changes_for_v440 (1.92 seconds)
Migrating: 2017_06_02_105232_changes_for_v450
Migrated:  2017_06_02_105232_changes_for_v450 (1.75 seconds)
Migrating: 2017_08_20_062014_changes_for_v470
Migrated:  2017_08_20_062014_changes_for_v470 (1.55 seconds)
Migrating: 2017_11_04_170844_changes_for_v470a
Migrated:  2017_11_04_170844_changes_for_v470a (0.28 seconds)
Migrating: 2018_01_01_000001_create_oauth_auth_codes_table
Migrated:  2018_01_01_000001_create_oauth_auth_codes_table (0.41 seconds)
Migrating: 2018_01_01_000002_create_oauth_access_tokens_table
Migrated:  2018_01_01_000002_create_oauth_access_tokens_table (0.47 seconds)
Migrating: 2018_01_01_000003_create_oauth_refresh_tokens_table
Migrated:  2018_01_01_000003_create_oauth_refresh_tokens_table (0.41 seconds)
Migrating: 2018_01_01_000004_create_oauth_clients_table
Migrated:  2018_01_01_000004_create_oauth_clients_table (0.22 seconds)
Migrating: 2018_01_01_000005_create_oauth_personal_access_clients_table
Migrated:  2018_01_01_000005_create_oauth_personal_access_clients_table (0.28 seconds)
Migrating: 2018_03_19_141348_changes_for_v472
Migrated:  2018_03_19_141348_changes_for_v472 (0.25 seconds)
Migrating: 2018_04_07_210913_changes_for_v473
Migrated:  2018_04_07_210913_changes_for_v473 (1.57 seconds)
Migrating: 2018_04_29_174524_changes_for_v474
Migrated:  2018_04_29_174524_changes_for_v474 (0.68 seconds)
Migrating: 2018_06_08_200526_changes_for_v475
Migrated:  2018_06_08_200526_changes_for_v475 (5.52 seconds)
Migrating: 2018_09_05_195147_changes_for_v477
Migrated:  2018_09_05_195147_changes_for_v477 (0.59 seconds)
Migrating: 2018_11_06_172532_changes_for_v479
Migrated:  2018_11_06_172532_changes_for_v479 (0.23 seconds)
Migrating: 2019_01_28_193833_changes_for_v4710
Migrated:  2019_01_28_193833_changes_for_v4710 (2.48 seconds)
Migrating: 2019_02_05_055516_changes_for_v4711
Migrated:  2019_02_05_055516_changes_for_v4711 (0.72 seconds)
Migrating: 2019_02_11_170529_changes_for_v4712
Migrated:  2019_02_11_170529_changes_for_v4712 (0.01 seconds)
Migrating: 2019_03_11_223700_fix_ldap_configuration
Migrated:  2019_03_11_223700_fix_ldap_configuration (0.28 seconds)
Migrating: 2019_03_22_183214_changes_for_v480
Migrated:  2019_03_22_183214_changes_for_v480 (1.12 seconds)
Seeding: AccountTypeSeeder
Seeding: TransactionCurrencySeeder
Seeding: TransactionTypeSeeder
Seeding: PermissionSeeder
Seeding: LinkTypeSeeder
Seeding: ConfigSeeder
[2019-12-17 09:31:56] local.WARNING: No database version entry is present. Database is assumed to be OLD (version 1).  
Database seeding completed successfully.
`

**Comment by DamageIncorporated** [comment]
Maybe the command `php artisan config:cache` could be also added to your documentation just for safety?

That would to make sure configuration changes are actually read after changing the .env file more than once due to user error, regardless if one uses a Jail or a Docker container.

**Comment by JC5** [comment]
Yes, and it should be added to the entrypoint script as well. Thanks for pointing out the solution!

**Comment by JC5** [comment]
This will be fixed in the next release.
