### ISSUE TITLE
Form action has port 80 in url

### ISSUE THREAD

**Issue by adrianviegas** [firefly-iii/firefly-iii#2894]
I am running Firefly III version 4.8.2

**Description**
I am running firefly on docker along with nginx. The login page loads fine with all the resources over https, however I am not able to login as all the urls include port 80 in them.
 
> `<form action="https://mydomain:80/login" method="post">`
> `<a href="https://mydomain:80/password/reset">I forgot my password</a>`

This causes chrome to deny the request giving this error

>`Refused to set the document's base URI to 'https://mydomain:80/' because it violates the following Content Security Policy directive: "base-uri 'self'".`

I have this already set in my .env file
>APP_URL=https://mydomain
>TRUSTED_PROXIES=**

This is my nginx conf file 

> upstream mydomain {
                                ## Can be connected with "nginx-proxy" network
                        # firefly-iii_firefly_iii_app_1
                        server 172.22.0.5:80;
}
server {
        server_name mydomain;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://mydomain;
        }
}

**Comment by JC5** [comment]
There are some examples of nginx configurations in older issues, if you search for them. That could be the culprit.
