### ISSUE TITLE
Uncaught Error: Call to undefined function bcscale()

### ISSUE THREAD

**Issue by JamesHawkinss** [firefly-iii/firefly-iii#2896]
Although php7.3-bcmath is installed on my system, it's not happy.

All the people who have reported this in the past have just failed to install the bcmath PHP extension, but it's definitely installed.

**Comment by TechRabb1t** [comment]
Is it installed and enabled? If you are using apache2 you need to enable the module for example.
If you are using Debian based OS use apache2ctl -M, if its CentOS go with httpd -M

**Comment by JamesHawkinss** [comment]
Thanks for the quick response. I'm on Ubuntu and used `phpenmod bcmath` and then reloaded Apache. Problem persists.

**Comment by JC5** [comment]
Is bcmath listed in phpinfo();?

```php
<?php
phpinfo();
```

<img width="955" alt="Screenshot 2019-12-16 at 20 18 00" src="https://user-images.githubusercontent.com/5889984/70935761-d7437080-2038-11ea-9b37-8d66ce392e45.png">

**Comment by JamesHawkinss** [comment]
It's listed in "Additional .ini files parsed" but not anywhere else.

**Comment by JamesHawkinss** [comment]
But executing `php -m | grep bcmath` returns `bcmath` which is supposed to mean that the extension is installed?

**Comment by JC5** [comment]
What's the content of the ini file? Is the file there present on your system?
