### ISSUE TITLE
Bank transaction file has an extra line before headers

### ISSUE THREAD

**Issue by bas-rik** [firefly-iii/firefly-iii#2897]
Sorry for my english.
But i'm trying to import my KNAB transactions. It will work when i remove the first line.
Can i edit my config so it will automaticly work?

![image](https://user-images.githubusercontent.com/58956991/70943434-2bf2e580-2051-11ea-992e-c1f77324ecbf.png)

my condig file:
 `{
    "file-type": "csv",
    "date-format": "d-m-Y",
    "has-headers": true,
    "delimiter": ";",
    "apply-rules": true,
    "specifics": [],
    "import-account": 1,
    "column-count": 16,
    "column-roles": [
        "account-iban",
        "date-transaction",
        "currency-code",
        "generic-debit-credit",
        "amount",
        "opposing-iban",
        "opposing-name",
        "_ignore",
        "internal-reference",
        "description",
        "_ignore",
        "_ignore",
        "_ignore",
        "_ignore",
        "_ignore",
        "_ignore"
    ],
    "column-do-mapping": [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "column-mapping-config": [
        {
            "NLxxKNABxxxxxxxxx": 31
        }
    ]
}`

**Comment by JC5** [comment]
No, I'm afraid not. Its up to KNAB to provide valid CSV files and this isn't one.

**Comment by Mindar** [comment]
I would like to add that I have the same issue with csv exports from my bank. An option to ignore/remove the first x lines from the csv file would be much appreciated.
