### ISSUE TITLE
Not a question but a Thank You

### ISSUE THREAD

**Issue by DocCyblade** [firefly-iii/firefly-iii#2898]
I am running Firefly III version 4.8.2

**Description**
A BIG THANK YOU!

I want to publicly thank you for your work on this app!. I setup a private instance in my in house ProxMox server using a Turnkey Linux LAPP as a base. It was pretty easy to setup. I setup a demo site for my wife and I to play around with to kick the tires so to speak. I also setup a production instance that we will start using start of the new year. 

Love the fact this is open source and PHP based. I have dabbled in PHP so it will make maintenance and hacking/helping with features easier. If you need a beta tester I'm game :-) I love to support open source software with my time, and money where I can. So don't be surprised if you may see a pull request some day with a feature or a bug fix.

Also If your ok with it I would like to create an install script over at [Turnkey Linux](https://www.turnkeylinux.org) so when they release v16 we can get this awesome app in a easy turnkey solution! I am one of the part time app dev/builders over there and I try to make sure any open source software I use personally has a Turnkey Linux app in the Library.

Anyway thank you for your work and I will be dropping by Patreon later this month to drop a little support your way.

**Comment by JC5** [comment]
You'r very very welcome! I enjoy tinkering with Firefly III and I enjoy compliments even more. You're always free to make suggestions. Beta testers are always welcome, I hope to release a new alpha this weekend in fact. :)

I look forward to a Turnkey script, to make it easier for users to install Firefly III. Thanks again!

**Comment by emansih** [comment]
not a question but has a question label

**Comment by JC5** [comment]
Here you go :wink:

**Comment by JC5** [comment]
There's for your thanks. The bot intervenes! :grin:

Can I leave it to him to close the issue, in due time?

**Comment by AlexKalopsia** [comment]
Writing here so that the bot doesn't get rid of the positive vibes! Thanks for Firefly! <3

**Comment by kczav** [comment]
I do thank you very much as well for this superb application. :-)

**Comment by 4oo4** [comment]
Thanks for everything!
