### ISSUE TITLE
Ability to duplicate a transaction including splits

### ISSUE THREAD

**Issue by scottharney** [firefly-iii/firefly-iii#2899]
**duplicate transacation capability**

I would like to be able to select a transaction and duplicate it, creating a new transaction with all splits intact.  It could copy and prefill the form with dates or just copy it in one go.  Today you can select to "Edit" or "Delete". .

**Solution**
While recurring transactions are nice, it can be helpful to simply copy transacations, particularly complex ones with many splits 

**What are alternatives?**

I haven't dived in deeply to recurring transactions yet which partially solves this. but not all transactions you'd want to copy/update are necessarily recurring. 

Thanks for considering!

**Comment by JC5** [comment]
When you edit a transaction, check “save as new” and it will copy the transaction, splits and all.
