### ISSUE TITLE
Serverless deployment 

### ISSUE THREAD

**Issue by TMiguelT** [firefly-iii/firefly-iii#2900]
**Description**
Supporting serverless deployment means hosting Firefly will only cost money per request, not a fixed fee. For example, [AWS Lambda](https://aws.amazon.com/lambda/) in the US costs $0.20 per 1M requests, which is likely enough for a year's worth of use for a single person. Compare this to EC2 which would cost $4.50 per month of use with the smallest possible instance size.

**Solution**
The way I see it, Serverless functionality could be added incrementally:
* First, it would have to be integrated into the relevant serverless framework, which might be [bref](https://bref.sh/) (simpler, but only works on AWS), or possibly [serverless](https://serverless.com/) (which works on anything I believe). At this point users could manually upload the application bundle to AWS for deployment
* Next, Firefly could be uploaded to the [Serverless Application Repository on AWS](https://aws.amazon.com/serverless/serverlessrepo/), which would allow for one-click installation. This would involve writing a CloudFormation template that describes the AWS services needed for deployment. In the case of Firefly, it would probably be the application itself, an [Aurora Serverless](https://aws.amazon.com/rds/aurora/serverless/) instance (a serverless SQL database, which also only costs on-demand), and probably some setup involving [Cognito](https://aws.amazon.com/cognito/), the authentication service. This might entail OAuth using a social login etc.

**What are alternatives?**
* Other cloud services exist, some of which are free for low usage, like Heroku. However I doubt any are as consistently cheap at all usage levels as AWS Lambda
* Different serverless frameworks could be used, as discussed above

**Comment by JC5** [comment]
Isn’t deploying a complex and stateful application like Firefly III the exact opposite of what serverless deployments are for? You have to keep track of sessions, databases and file storage, and to do that in a Lambda seems a bit over the top. 

Firefly III supports k8n which is already a stretch given the nature of the app as it exists today. 

If you want Firefly III to go to a micro-service architecture the first thing you have to do is rewrite the entire application into stateless components that can talk to an abstract storage backend.  

Right now, Firefly III is a huge (especially when looking at something like this) monolith that is in no shape or form ready for a Lambda deployment. 

My personal Firefly III installation is in Docker Swarm, running on 4 nodes with a redis cache backend and a MariaDB database. And that’s about the useful limit of what you can do with Firefly III at the moment. 

I’m not against this, don’t get me wrong, but Firefly III just isn’t designed for something like this.

**Comment by TMiguelT** [comment]
> Isn’t deploying a complex and stateful application like Firefly III the exact opposite of what serverless deployments are for?

I'd say this is a bit of a misconception about serverless. You still have an application and a database, they're just turned off when they're not being used. Serverless doesn't require a micro-service architecture either (although it does benefit from that), which is why you have tools like [Zappa](https://github.com/Miserlou/Zappa) that can directly convert a monolithic Django or Flask app into a serverless "function" without requiring a rewrite.

I gather that Firefly is written using Laravel, and it doesn't seem altogether difficult to [port using bref](https://bref.sh/docs/frameworks/laravel.html).

File storage is more tricky. AWS lets you write to S3 from a Lambda which from an AWS perspective is exactly what you'd want to do. However, if local file storage is core to the application (not just used for caching etc) then it would require another code path for uploading to S3 instead of storing it locally, but that wouldn't be outrageous. Out of interest, since you have a Heroku deployment option, how do you deal with file storage there, if the app gets powered down?

**Comment by JC5** [comment]
That doesn't really negate the rest of my points. The fact that you *can* convert any application to a serverless Lambda doesn't mean that you *should*. And running about a million lines of code + all of the dependencies in a lambda feels really counter-intuitive. 

Heroku is basically running customized docker containers. You can give it persistent storage and a DB.

Feel free to spend some time on it, but I'd rather rewrite Firefly III to better match what Lambda's are for. From an architectural perspective I believe it's a terrible idea.

**Comment by TMiguelT** [comment]
The *should* comes from the very compelling argument that Lambda is unbelievably cheap. It's not an architectural argument at all. Do you not think it would be nice to say "Here, you can deploy Firefly on your own private cloud for 20 cents a year. You just create an Amazon account and click this button"?

**Comment by Lawri-van-Buel** [comment]
For something that handles finance, I would not call AWS secure. You simply do not have any knowledge or proof that amazon can not mess with your data. Couple that with the knowledge about leaks and breaches coming out of the AWS clouds and I would not recommend anyone without a descent lawyer staff to use AWS for fin tech or personal finance. 

It’s just not the right type of fit. 

As for cost, this app can run quite happily on a raspberry pi in your home, that’s way more cost effective than a AWS serverless ever can be. (Unless your needs are allready more than a single pi can handle... so you just make a cluster of them)


The old saying “There is no cloud, just other people’s computers.” Seem to apply here, and for sensitive information that is personal finance I would not trust just someone’s computer to handle it correctly, safely and securely.

**Comment by TMiguelT** [comment]
You may not feel comfortable using the cloud, which is understandable, but it's not an argument for making it harder to use for those who are. AWS is the most popular commercial cloud for a reason. If Netflix, NASA, Slack, Airbnb etc are comfortable using AWS I don't think it's worth worrying about security of your tiny application. Firefly already supports a number of smaller commercial clouds, so hindering cloud deployment is a moot point anyway.

Comparing cloud to a Raspberry Pi is also unhelpful. Providing a Severless Repository for Firefly would allow users to install it by clicking one button, for free, immediately, in their browser. Buying a Raspberry Pi, shipping it, installing Firefly onto it, ensuring constant internet and power supply would cost significantly more, require vastly more technical skills, and take a much longer time before it can be used. I believe it's worth considering the average user rather than yourself when making decisions about software.

**Comment by Lawri-van-Buel** [comment]
I am considering the average user, the one that has neither the skill nor the knowhow how to safeguard there data in a serverless environment. All of your examples have dedicated teams that safeguard it for them as well as SLA’s and contracts to further make Amazon safeguard there specific instances. 

And putting effort into making the application support a mechanism that it should not use Without additional safeguards is a waste of developer effort in my opinion. 

Also. And I quote the documentation here:

> This application is for people who want to track their finances, keep an eye on their money without having to upload their financial records to the cloud. You're a bit tech-savvy, you like open source software and you don't mind tinkering with (self-hosted) servers.
> Possibly, you're always short on money even though in theory, you make enough money to get by.

So how does a single click install on a cloud instance help to further firefly’s goals of being a self hosted solution for people to do there personal finance with?

You are not talking about people using a cloud instance for there stuff. Your talking about Redis ging the application to use cloud specific elements. This is a line we should always question if we should cross it. And I believe we should NOT cross it with firefly. If you feel we should could you give some reasons as to why we should cross that barrier. (Just saying we could make a one click deploy is not really saying anything, this is doable with many techniques like “Ansible, Docker, vagrant, LXC, puppet, chef, etc.” I would even be willing to make an ansible role for it if it does not exist.

**Comment by TMiguelT** [comment]
> I am considering the average user, the one that has neither the skill nor the knowhow how to safeguard there data in a serverless environment

That's the beauty of CloudFormation. The entire cloud stack, including firewall, access policies etc is code, so can be open sourced, iterated upon, and published for the user to install. They would not need security expertise for this reason.

> So how does a single click install on a cloud instance help to further firefly’s goals of being a self hosted solution for people to do there personal finance with?

The advantage of Firefly is that it has the flexibility to be deployed anywhere, to suit the needs of any user. Providing a serverless option would not impact the users who want to tinker with a server or host it locally. What it will do is add an additional streamlined installation for users who *don't* want that. It would retain all the advantages of open source, including your trust in the software, full visibility over what you're actually running, and the ability to contribute your own improvements. Using the cloud doesn't change any of that. 

And again, [Firefly already supports 3rd party clouds](https://docs.firefly-iii.org/installation/third_parties). What's motivating me is this line:

>  Keep in mind do that there's no such thing as a "free lunch", and these options are either paid or severly limited (is very slow or can't handle many transactions).

This proposal is my attempt to address this disclaimer.

**Comment by JC5** [comment]
I've been playing around with Firefly III and Lambda functions a bit this afternoon. It's far from a one-click solution and I fear Firefly III is far from optimized to be run as a Lambda function. But like you say, it's all open source, and I invite you to adapt Firefly III into a Lambda function. Ironically in the background a lambda function is just a docker container with extra steps.

> Do you not think it would be nice to say "Here, you can deploy Firefly on a secure cloud. It will cost nothing. You just create an Amazon account and click this button"?

Yes, that would be nice. I expect a Lambda function won't be able to handle some of the resource-intensive operations Firefly III has but like I said, feel free to explore it. I don't believe in running Firefly III in a single Lambda function, but that could be my mistake too.

One thing is important here. When it comes to 'the average user' and supporting them, please keep in mind that I only consider one user when developing Firefly III: myself. Part of the success of Firefly III is not giving a single crap what users actually want because most users, even those of Firefly III, are morons.

Sorry guys, but it's true. Of course that makes me a moron as well because I use my own tool and the reason is: we users only look at what we want and nothing else. I've had the most insane feature requests and if I'd honored them all Firefly III would be a clusterfuck. 

So when it comes to new paths for deployment, new features and new possibilities I am conservative by nature and I'll consider stuff if I think _I_ would use it. If that's not the case, it's probably not going to happen. For a Lambda deployment, the following considerations have to be made.

* Each new deployment type requires its own meta files, code adjustments and if-statements. Already the repository is cluttered with YAML files, XML configurations and Firefly III has at least 3 different types of middleware that cut in only when deployed in Sandstorm or Heroku (which is a tiny part of my userbase). So whatever fancy new one-click button you're thinking of, I'll consider it if you can do it without code changes.
* Not to mention all the extra packages that *everybody* needs to download.
* I have to support each deployment type into eternity, and that includes import/export of data. Already I have a lot of angry Sandstorm users because the service is slowly but surely closing, and they want to leave. 
* I have to test each deployment method.

Of course all of these problems can be overcome but it's a hassle. I'd much rather make sure that Firefly III is simple enough and easy enough that it can be deployed anywhere. And that means that the focus of me should be in different areas entirely.

* Remove dead code, remove test routines, remove less used features, remove one-off packages.
* Upgrade libraries and packages to stay ahead of the curve
* Split the application: frontend/backend. Featurewise. Deployment wise.

Once I do that, deploying Firefly III in a Lambda function, Azure function or some other serverless system becomes natural to do, because it *fits*.

**Comment by TMiguelT** [comment]
Thanks for the reply. Is it possible to share the work you've done via a branch? That might save me some time.

**Comment by GaryQ** [comment]
Sorry for being late to the party... not sure I would have risked commenting at that time anyway!  8-) 

> Thanks for the reply. Is it possible to share the work you've done via a branch? That might save me some time.

@TMiguelT ,
That's what open source is all about: Fork the repository and go for it.
 Make your own mods/adaptation/revisions. And if you manage to get something going let James know. He'll be proud his work is used in a spinoff, etc.

Personally I think FFIII 's repo and downloads are already way too cluttered with the "all-in one" mega sized, different deployment "keep everyone happy" structure. 

@JC5 … Them the rewards of dictator in chief ;)

1 - Kudos on the new strict semantic versioning route with 5.0.0. And the commits are way easier to follow. Good job!

2 - I Was going to make some other suggestions like maybe (just maybe, but I won't) like "maybe" get 5.0.0 stable and then potentially take some time off adding new this and thats and get the broom out and clean up the repo. Get anything and everything no longer active out. I'd also (don't get mad) suggest the possibility of following the common practice of keeping copyright notices to a strict minimum with a link to the license. The copyright overhead seems a little excessive. And why is there V1 and V2 folders in the installs when only V1 seems to be used? Ok enough of the stuff I won't suggest LOL 

BTW Just as in my previous suggestions (but that I'm not suggesting) they are only suggestions, Not demands or even requests.  But I can guarantee that cleaning out the repo will make your job and anyone wanting to help out sooooo much easier.

**Comment by JC5** [comment]
1. Thanks. Trying hard :)
2. Meh. The copyright notices are all auto-generated and collapse automatically, so I don't really mind. But yes, there's a lot of stuff already *in* the repository that can slowly be cleared out.
