### ISSUE TITLE
Rules don't appear to run on Liability accounts when manually running

### ISSUE THREAD

**Issue by MattSidney** [firefly-iii/firefly-iii#2901]
I am running Firefly III version 4.8.2

**Description**
It appears that when attempting to "apply rule" manually that my liability accounts are not presented as an option to select. If I just leave the selections as all it still does not appear to run the rule against the liability accounts. 

When performing the "see matching transactions" action it does however show the matching transactions. 

transactions found:
![image](https://user-images.githubusercontent.com/45581528/71126518-44275800-223d-11ea-8049-843e00205e81.png)
liability account not shown:
![image](https://user-images.githubusercontent.com/45581528/71126658-8a7cb700-223d-11ea-9f62-33f202ae987b.png)

**Comment by JC5** [comment]
Ah I see it, thanks.

**Comment by JC5** [comment]
This will be fixed in the next release.
