### ISSUE TITLE
credit card payments double when selecting transfer

### ISSUE THREAD

**Issue by MattSidney** [firefly-iii/firefly-iii#2902]
I am running Firefly III version 4.8.2

**Description**
Not sure if this is occurring because I am utilizing the transfer for credit card payments when I shouldn't be. 

Currently I pull data from my bank. This includes both the account I use to pay my credit card and my credit card. The payment account shows a withdrawal of money. The credit card account shows a deposit. I thought the right way to manage this was to confirm both to a transfer as the money has already been "spent" by the credit card account; however this appears to have the payment account show two withdrawals and the credit card to show two deposits which messes with the balance. 

What is the intended way to track credit card payments? 
Should I be deleting one of the transactions (ideally would like to avoid this as it means extra processing during automatic import)? 
Should I be leaving them as deposits and withdrawals? 

Thanks in advance.

**Comment by JC5** [comment]
Make sure you store the credit card account as an asset account and not as a liability. Then, when both accounts are matched during the import (either recognized by name or account number) Firefly III will store the transaction as a transfer.

**Comment by MattSidney** [comment]
Interesting, is there any other requirements? That is how I have it setup now (credit card is an asset account - credit card type)

Does it matter if the dates don't match? (They can be delayed) 
Does it matter if the description doesn't match? (They are different in each account) 
All that really matches is the value. I did manually tag them as transfer but they still don't seem to 'cancel out'

**Comment by JC5** [comment]
For Firefly III to create a transfer, it's enough to match both accounts to an asset account. So I expect that in both transactions, either of the accounts isn't an asset account, is that true?

**Comment by MattSidney** [comment]
Maybe it is working as it should and my expectations are off. 
Here are the two accounts: 
![image](https://user-images.githubusercontent.com/45581528/71165797-969c5f00-22a5-11ea-8914-fb1b88d2bc84.png)
Then the two transactions (which I have manually tagged as transfers: 
![image](https://user-images.githubusercontent.com/45581528/71165921-c9deee00-22a5-11ea-809e-2bb359e87f2b.png)
However if I look at my 'Main' account I have two transactions and same for the credit card. 
I assumed that these would "link" in such a way that they would not effect balance in the way they do. However instead it seems that they are doubling up instead. (transferred away and transferred in is equal to double - adding the two).

**Comment by MattSidney** [comment]
@JC5 is this the expected functionality?

**Comment by JC5** [comment]
Sorry, I forgot to reply. But yes: they're transfers which is correct, but since the descriptions are different on both Firefly III isn't able to merge them. You'll have to manually delete one.

**Comment by MattSidney** [comment]
Do you think it would be possible to look into matching based on not just the text? 
Perhaps a combination of dollar amount and maybe a flexible date range (+/-Xdays). 
Orr, could it perhaps be linked with the "Link Transaction" feature (which I understand may not be up and running yet). 
It would be nice to long term have it rule based if not automatic.
