### ISSUE TITLE
Import from csv option doesn't allow selection of Liability account

### ISSUE THREAD

**Issue by MattSidney** [firefly-iii/firefly-iii#2903]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

When importing csv (without account column) I am unable to select my liability account as the default account. 
This means I cannot import a csv containing mortgage transactions. 

**Steps to reproduce**
import file. 
select account dropdown, liability account not shown. 

Attempted to repro on demo but doesn't appear to allow for testing csv import.

**Comment by JC5** [comment]
As per [this post on Patreon](https://www.patreon.com/posts/30012174), I'm not going to make any improvements to the current import routines. I'll move your issue to the proper repository for safe-keeping but I believe this is already fixed in the new import routine.

**Comment by JC5** [comment]
.. which I can't, because it's not under /firefly-iii/. Oh well, know that I'll be fixing it, just not in Firefly III itself :)

**Comment by MattSidney** [comment]
Thanks for the info @JC5 
I realize you are not planning changes to the current firefly importer but just for my information; would it be a similar change as you made here: https://github.com/firefly-iii/firefly-iii/commit/6ad2021739dacbd32aaa853485c733735fcea851 for https://github.com/firefly-iii/firefly-iii/issues/2901 ?

**Comment by JC5** [comment]
Unfortunately not.
