### ISSUE TITLE
Whoops There was a fatal error. Please check the log files. (Installing on godaddy Linux Hosting)

### ISSUE THREAD

**Issue by jaiprakashxsingh** [firefly-iii/firefly-iii#2905]
[ev.txt](https://github.com/firefly-iii/firefly-iii/files/3986842/ev.txt)
In installed Firefly III 4.8.2 using the SSH -> composer commands on Godaddy Shared Linux Hosting account.
Installation was successful. 
Thank you for installing Firefly III, v4.8.2!

I created mysql databases on local host.
Changed the .env file as attached. 

I created a subdomain http://budget.hostwithjp.com and pointed the folder to root/public_html/Firefly-iii/public

When i load the webpage, I get a message 
Whoops
There was a fatal error. Please check the log files.
Now, I dont know where the log files are and what the problem is. 
I did some research as well.. My env file has log channel as stdout, I dont see any log files in the Firefly-iii/storage/logs folder

Also, there are two folder V1 and V2 in the Firefly-iii/public folder, why?
please help.

**Comment by JC5** [comment]
Change the .env file to say `APP_DEBUG=true` and you'll see the error in your browser :)

**Comment by jaiprakashxsingh** [comment]
Thank You, i can see the error now on the webpage. There are majorly 3 errors.
(3/3) QueryException
could not find driver (SQL: select "id", "name", "data" from "configuration" where "name" = is_demo_site and "configuration"."deleted_at" is null limit 1)

in Connection.php line 664
--
at Connection->runQueryCallback('select "id", "name", "data" from "configuration" where "name" = ? and "configuration"."deleted_at" is null limit 1', array('is_demo_site'), object(Closure))in Connection.php line 624


(2/3) PDOExceptioncould not find driver
--
in PDOConnection.php line 31
at PDOConnection->__construct('pgsql:host=localhost;dbname=firefly_iii_db;port=5432;sslmode=prefer', 'firefly_jp', 'firefly_firefly', array(0, 2, 0, false))in Connector.php line 67



(1/3) PDOExceptioncould not find driver
--
in PDOConnection.php line 27
at PDO->__construct('pgsql:host=localhost;dbname=firefly_iii_db;port=5432;sslmode=prefer', 'firefly_jp', 'firefly_firefly', array(0, 2, 0, false))in PDOConnection.php line 27

**Comment by JC5** [comment]
Are you using MySQL or Postgres?

Make sure that you correctly set `DB_CONNECTION=mysql` or `DB_CONNECTION=pgsql`.

**Comment by jaiprakashxsingh** [comment]
I think database connection is successful. used mysql instead of pgsql. But i get another error related to "Table View".. for which i will refer other threads.

**Comment by jaiprakashxsingh** [comment]
Any hint on solving the following please?
(1/3) PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'firefly_iii_db.configuration' doesn't exist

(2/3) PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'firefly_iii_db.configuration' doesn't exist


(3/3) QueryExceptionSQLSTATE[42S02]: Base table or view not found: 1146 Table 'firefly_iii_db.configuration' doesn't exist (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)
--

**Comment by JC5** [comment]
You haven't installed the tables yet. Did you following the installation documentation?

https://docs.firefly-iii.org/installation/self_hosted

**Comment by jaiprakashxsingh** [comment]
Yes... Yahooo... I just did. Thank You very much Mr. JC5
It works.
