### ISSUE TITLE
Tranlation issue on transaction page

### ISSUE THREAD

**Issue by FanyangMengDev** [firefly-iii/firefly-iii#2906]
**Bug description**

Dear JC5,

I am running Firefly III version 4.8.3-alpha.1, and my problem is:
The translation of Chinese Simplified **on transaction page** has some mistakes. And I have already **correctted them both on Crowdin and local files**. But after did that, **the transaction page's wrong translation does not change at all.** 

To be honest, this issue actually happenes on every version. I just report it today.

It makes me wonder that if the transaction page actually use the local translation files. Maybe the transaction page use the translation only via Crowdin?

I have this thought because I used to change the homepage welcome words "What's playing" to "今天理财了吗?" in local file, and it changes immediately on the homepage. But when I change the translation of "submit" from "送出" to "提交" on transaction page, it does not work.

Anyway, I have already add my traslation to Crowdin. Which is more official to the older translation.

Just wanna ask that why change the local translation file does not work to transaction page.

**Steps to reproduce**
1. Change to Chinese Simplified
2. Change the translation file locally, which locate in /resources/lang/zh_CN/firefly.php
change the translation of "submit" from "送出" to "提交"
![change](https://user-images.githubusercontent.com/53750381/71238918-3ad2e400-2340-11ea-9f32-bc373af9fd6c.PNG)

3. It not works at all.
![notwork](https://user-images.githubusercontent.com/53750381/71238993-6ce44600-2340-11ea-942e-ead67d8f7d9c.PNG)

**Extra info**

Ubuntu 18.04 LTS
Chrome latest verison
Debug information generated at 2019-12-20 15:50:35 Asia/Shanghai for Firefly III version **4.8.3-alpha.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.3-alpha.1 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , docker_out |
| PHP version | 7.3.12 |
| Display errors | Off |
| Session start | 2019-12-01 00:00:00 |
| Session end | 2019-12-31 23:59:59 |
| Session first | 2019-11-16 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, sodium, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, cgi-fcgi, zip, fileinfo, imagick, imap, exif, ldap |

**Comment by JC5** [comment]
The translations in the Javascript file are part of an optimized JS file and are not being read from those PHP files. They update whenever a new release is made. I can do a double check on the contents of them, but the JS files will not update when you update your local files.

**Comment by FanyangMengDev** [comment]
Thank you for your reply. I see now. Hoping next time my translation will be added

**Comment by FanyangMengDev** [comment]
I have already used 5.0.0-alpha.1 and I saw that you have corrected this issue on this new version. Thank you for your hard working! I will keep contributing to the translation of Firefly III on Crowdin.
