### ISSUE TITLE
Future Financial Outlook - Reports 

### ISSUE THREAD

**Issue by jaiprakashxsingh** [firefly-iii/firefly-iii#2908]
Please develop this feature in next release.

I have a lot of expense and income transactions setup as recurring transactions in future.
About 10 bills setup on a periodic basis.

I would like to run a report to generate a cash flow statement for upcoming financial year. That would help me ascertain my financial position.

**Comment by JC5** [comment]
Firefly III won't support the ability to predict expenses, give you a look into the future or do financial planning. The present is hard enough to manage at the moment.

https://docs.firefly-iii.org/support/features
