### ISSUE TITLE
Upgrade from 4.7.17 to 4.8.3-alpha.1 broke budgets

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#2909]
I made new attempt to upgrade my rather old firefly to new version. Followed upgrade from Git procedure - no significant errors in logs. Firefly is up & running but my budgets are broken. Here is screenshot from old version:
![obraz](https://user-images.githubusercontent.com/4746858/71256617-921d8800-2331-11ea-808c-0d7bdca65fd2.png)
and from new:
![obraz](https://user-images.githubusercontent.com/4746858/71256645-aa8da280-2331-11ea-9a4d-7a6a6a7aeb47.png)
Clicking on the budget I get following error:
```
Argument 2 passed to FireflyIII\Support\Twig\AmountFormat::FireflyIII\Support\Twig\{closure}() must be of the type string, null given, called in /var/www/firefly-dev/storage/framework/views/twig/91/91a35e011e488f9b8a744847700260db1c4733198c2e5247ce08ebf3a59a988b.php on line 308 
```

**Comment by JC5** [comment]
I'll need to see the content of that file: `/var/www/firefly-dev/storage/framework/views/twig/91/91a35e011e488f9b8a744847700260db1c4733198c2e5247ce08ebf3a59a988b.php`.

Preferably over email, it'll contain private data. Also interesting: some lines from the tables `budget_limits` and `budgets`.

Let's see what's going on.

**Comment by skibbipl** [comment]
Problem under investigation.

**Comment by skibbipl** [comment]
@JC5 Do you need more debug info on that?

**Comment by JC5** [comment]
No, I just haven't found the time to set it all up. Let me do that this morning to see what could be the problem.

**Comment by JC5** [comment]
Mmmm. My initial upgrade went well. After installing 4.7.17 and creating a few test transactions I updated to 4.8.3-alpha.1. This seems to work just fine.

Even setting the transaction_currency_id to null didn't work. Work in progress..
