### ISSUE TITLE
Importing CSV with a date/time (ISO 8601) field (Monzo)

### ISSUE THREAD

**Issue by deanpcmad** [firefly-iii/firefly-iii#2910]
I am running Firefly III version 4.8.2

**Description**
I've just started using Firefly and I'm trying to import transactions from my Monzo bank account. Their CSV export has a `created` column like so: `2019-12-02T07:31:15Z`

I've tried a number of ways to set this when importing:

- Y-m-d
- Y-m-dTH:i:sZ

But I just can't get it to work properly. It just keeps setting the date as the date when uploaded.

Any ideas?

**Comment by JC5** [comment]
Try the following: `Y-m-d\TH:i:sZ`.

**Comment by deanpcmad** [comment]
Excellent, that works. Thanks! 👍
