### ISSUE TITLE
API - Update (PUT) Transactions error

### ISSUE THREAD

**Issue by Tunsworthy** [firefly-iii/firefly-iii#2911]
Hi, 

I've been trying to use the API to update transactions but haven't had success. I'm sure I've missed something pretty obvious but just need some help. 

I've been able to Get, Delete, and Push transactions but get an error anytime I try to update an existing one.

I'm using Postman to do this and have tried sending JSON and x-www-form-urlencoded, my instance is currently hosted on Heroku running 4.8.2.

Any help would be appreciated 

<img width="830" alt="Screen Shot 2019-12-22 at 2 06 11 pm" src="https://user-images.githubusercontent.com/2962/71316544-fe7cc080-24c4-11ea-8998-8120ad012e40.png">

<img width="942" alt="Screen Shot 2019-12-22 at 2 06 22 pm" src="https://user-images.githubusercontent.com/2962/71316546-0e94a000-24c5-11ea-869d-b3e31d487cbb.png">

<img width="756" alt="Screen Shot 2019-12-22 at 2 06 29 pm" src="https://user-images.githubusercontent.com/2962/71316547-12c0bd80-24c5-11ea-804b-f80185f9f68e.png">

**Comment by JC5** [comment]
First off, you can submit either the ID or name, there's no need to do both. The ID will overrule the name.

Can you tell me the following things?

- The type of transaction you're trying to edit.
- What kind of an account 58 is.
- What kind of an account 5 is.

I suspect you're using the wrong account types for the kind of transaction you're updating.

**Comment by Tunsworthy** [comment]
Thanks for the quick reply.

I get the same error if I only send the ID or name.

Transaction is a Withdrawal
58 is a Shared asset account
5 is cash

I created this transaction with the API but can't seem to edit it (I've tried on a few other transaction also and get the same issue... I assume I'm just missing something).

**Comment by JC5** [comment]
I can't replicate this exact error. First, I create a cash transaction (account 39 is my cash account, as you can see below).

```json
{
    "data": {
        "type": "transactions",
        "id": "600",
        "attributes": {
            "created_at": "2019-12-22T06:48:58+01:00",
            "updated_at": "2019-12-22T06:48:58+01:00",
            "user": 1,
            "group_title": null,
            "transactions": [
                {
                    "user": 1,
                    "transaction_journal_id": 605,
                    "type": "withdrawal",
                    "date": "2019-12-22T00:00:00+01:00",
                    "order": 0,
                    "currency_id": 1,
                    "amount": "456.000000000000",
                    "description": "Test to cash",
                    "source_id": 1,
                    "source_name": "Checking Account",
                    "source_iban": "NL11XOLA6707795988",
                    "source_type": "Asset account",
                    "destination_id": 39,
                    "destination_name": "Cash account",
                    "destination_iban": null,
                    "destination_type": "Cash account",
                }
            ]
        },
        "links": {
            "self": "https://firefly.local/api/v1/transactions/600",
            "0": {
                "rel": "self",
                "uri": "/transactions/600"
            }
        }
    }
}
```

I can update it using the data below. 

1. New asset account (source)
2. New description
3. New amount

```json
{
	"transactions": [
		{
			"amount": 123,
			"source_id": 2,
			"destination_id": 39,
			"description": "updated description"
		}
	]
}
```

The result is visible immediately:

<img width="660" alt="Screenshot 2019-12-22 at 07 00 55" src="https://user-images.githubusercontent.com/5889984/71317899-7aa0e500-2480-11ea-8a81-e1ea8da07757.png">

**Comment by Tunsworthy** [comment]
Thanks for doing some testing.. I've copied your json and managed to get myself a different issue.
Sorry to be a Pain could you post your Postman settings? (I feel this is where I've gone wrong)

<img width="663" alt="Screen Shot 2019-12-22 at 8 34 47 pm" src="https://user-images.githubusercontent.com/2962/71320087-b9738100-24fa-11ea-8444-ef1fd8d17ccc.png">

<img width="716" alt="Screen Shot 2019-12-22 at 8 35 10 pm" src="https://user-images.githubusercontent.com/2962/71320089-bd070800-24fa-11ea-8f70-27034f5ac2cd.png">

**Comment by JC5** [comment]
That’s weird. The error indicates there was no valid data at all. Try it without the “content type” header.

**Comment by Tunsworthy** [comment]
So... I've tried with or without the content type.. I've changed the content type. 
I thought maybe it was a strange Heroku issue so I've spun up a local version in Docker on my laptop but managed to get the same issue.

Like you I'm able to create a new transaction fine, but I just can't edit.
Here is the postman config I am using... 
https://www.getpostman.com/collections/b28c35cdfcb180c53f04

I've even tried using fetch via nodejs but receive an error.

**Comment by Tunsworthy** [comment]
I've managed to resolve this, it seems that type is required in the Put request.

{
	"transactions": [
		{
			"type":"withdrawal",
			"amount": 22,
			"source_id": 1,
			"destination_id": 5,
			"description": "test12"
		}
	]
}

<img width="1037" alt="Screen Shot 2019-12-24 at 2 38 56 pm" src="https://user-images.githubusercontent.com/2962/71392234-7bda3980-265b-11ea-8c9d-f4bfb2f0b32d.png">

<img width="687" alt="Screen Shot 2019-12-24 at 2 39 06 pm" src="https://user-images.githubusercontent.com/2962/71392242-81d01a80-265b-11ea-8314-a9bc8813984a.png">

**Comment by JC5** [comment]
That’s weird. I can’t remember changing that recently.
