### ISSUE TITLE
When saving a Bill, it redirects to /debug

### ISSUE THREAD

**Issue by eudora-fabia** [firefly-iii/firefly-iii#2912]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

When saving a Bill, it redirects to /debug

**Steps to reproduce**
I can't replicate it now, however, here's the way I was able to reproduce the prob

https://drive.google.com/file/d/1KBpj4bd5iFW65Q_nl5IYLUQ9ztrX4J2D/view?usp=sharing

**Extra info**
Debug information generated at 2019-12-22 12:43:32 Asia/Manila for Firefly III version **4.8.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2 |
| FF API version | 0.10.5 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.10 |
| Display errors | Off |
| Session start | 2019-12-01 00:00:00 |
| Session end | 2019-12-31 23:59:59 |
| Session first | 2019-12-19 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | litespeed |
| UserID | 3 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, litespeed, bcmath, dom, fileinfo, gd, imagick, imap, intl, json, exif, mysqlnd, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, soap, sockets, tidy, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, ldap, Zend OPcache |

**Comment by JC5** [comment]
Thanks for letting me know. It shouldn't happen anymore in future releases, I'll push a fix for it.
