### ISSUE TITLE
Calendar 

### ISSUE THREAD

**Issue by ashkakrist** [firefly-iii/firefly-iii#2913]
Hi!

I just read the post where another user made a request for insight in future financial outlook. I am afraid I have a bit of a similar question, BUT I hope my request is more basic/simpler. 

I would like to have a calendar which shows when future transactions are scheduled. So there is no need for calculations, but I will be able to see upcoming expenses and I would know if I should start freaking out or can chill on basis of the current balance of my bank account. 

Cheers!

Edit: (I realise categories also give a preview of reoccurring expenses, but not payday for example.)

**Comment by JC5** [comment]
There is a calendar for recurring transactions, other calendars won’t be included I’m afraid.
