### ISSUE TITLE
Update check error even when automatic update checking is disabled

### ISSUE THREAD

**Issue by barkap** [firefly-iii/firefly-iii#2919]
I have automatic update checking set to off, however occasionally first page loads very slow and I get error on the page (An error occurred while checking for updates. Please view the log files). 

Firefly III version 4.8.2

---

**Error:**
![Screenshot_2019-12-27 What's playing » Firefly III](https://user-images.githubusercontent.com/1485739/71505706-e622f200-2886-11ea-841b-fa43b0c0a743.png)

---

**Automatic update settings switched off:**
![Screenshot_2019-12-27 Check for updates » Administration » Firefly III](https://user-images.githubusercontent.com/1485739/71505710-e9b67900-2886-11ea-9a57-145783371932.png)

**Comment by JC5** [comment]
Whoops. Not sure when I lost that code, but the check will now respect your preferences. Sorry about that.

**Comment by JC5** [comment]
Fixed in the latest beta.
