### ISSUE TITLE
Bills little improvement.

### ISSUE THREAD

**Issue by Doduf57** [firefly-iii/firefly-iii#2921]
Feature request:

I have some Bills every two months. The repeat option need more flexibility.
Can you change your models in order to do it? Thanks, Firefly is very helpful.

<img width="588" alt="Screenshot 2019-12-27 at 14 48 51" src="https://user-images.githubusercontent.com/14351464/71519494-07e89d00-28b8-11ea-9cfe-a8dcf42a2af7.png">

**Comment by JC5** [comment]
Thanks for the compliment. Set "skip" to 1 for a bi-monthly bill.

**Comment by Doduf57** [comment]
Thanks for your help, now is working as expected.
