### ISSUE TITLE
Edit Transaction Form displays number value with excessive digits

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2922]
I am running Firefly III version 4.8.2.

I've attached a screen clip of the "Edit Transaction" form.

![2019-12-27_093539](https://user-images.githubusercontent.com/39804831/71526596-816a9600-288c-11ea-9e3c-425c979a2f83.png)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2876
