### ISSUE TITLE
Reconciliation query hangs if using invalid dates

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#2923]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is that reconciliation queries hang forever when using an invalid date such as 31.11.XXXX

**Steps to reproduce**
Do a reconciliation for a month with 30 days, use any start date, use 31 as end date.

**Comment by JC5** [comment]
There’s not much I can do about that.

**Comment by chevdor** [comment]
How about checking in the backend for invalid dates and bring them back to a valid date when invalid instead of returning a 500 error ?

At least, the FE should throw an error when the 500 error comes back from the BE and not suggest to the user thru the UI that it is "working on the query".
