### ISSUE TITLE
Apply rule option doesn't work when rule trigger is "when a transaction is updated"

### ISSUE THREAD

**Issue by doctorboyMP** [firefly-iii/firefly-iii#2924]
**Bug description**

Not 100% sure if it is a bug or expected behaviour, but after creating a rule with trigger defined as "when a transaction is updated", even if I see matching transactions and I click apply, no actions are performed. If I change the trigger of the rule to "when a transaction is created" and I click apply, all the actions are performed.
I've checked in demo site and I was able to replicate this behaviour.

**Steps to reproduce**

Create a new rule with trigger defined as "when a transaction is updated"
Check if exists some matching transactions
Click apply and check if the actions were performed

**Extra info**
Firefly III version 4.8.2
Docker environment
Chrome

**Comment by JC5** [comment]
Nice find, that's a bug. I pushed a fix for the next release.
