### ISSUE TITLE
Request: Add OpenAPI spec to repository

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#2925]
It would be helpful to keep the openapi spec in this repository - this would allow for contributions (0.10.4 has a couple of minor validation issues) and would allow for easier creation of generated API clients.

**Comment by JC5** [comment]
No. Let me know what the issues are though.

**Comment by GeorgeHahn** [comment]
A couple of minor issues:
- Some `int32` values are specified with type `number`. This causes validation errors; the correct type is `integer`.
- A `PiggyBankEventRead` schema is referenced but does not exist. Should this be `PiggyBankRead`?
- Many nullable values are not marked as such, causing API errors when using a generated client. I am fixing these in my copy as I hit them.
- Some large enums are duplicated multiple times. It may be desirable to extract them into separate components.

Here's a diff of my changes against `firefly-iii-0.10.4.yaml`: [diff](https://github.com/firefly-iii/firefly-iii/files/4007452/diff.txt)

This includes some changes that you probably don't want but were necessary to generate a functional client. I removed the capitalization variants of some enum values & renamed `Tag` to `TagModel`.

**Comment by JC5** [comment]
Thanks! Could you share the original changed file as well? I'll see what I can fix. :+1:

The YAML is split in separated files in [this repos](https://github.com/firefly-iii/api-docs-generator), check it out!

Feel free to open new issues for stuff you run into!

**Comment by JC5** [comment]
Oh and a pointer for int32 would be appreciated. In [this document](https://swagger.io/docs/specification/describing-parameters/) it's mentioned as valid.

**Comment by GeorgeHahn** [comment]
This document is helpful for number types: [Data Types](https://swagger.io/docs/specification/data-models/data-types/#numbers). The `int32` format is supported, but only on `integer` types, not `number` types.

Thanks for the repo link, I had not seen that! I'll look into running openapi-generator against those files, though my current client is working well enough for my needs.

Here's my complete modified yaml: [firefly-iii-0.10.4.yaml](https://github.com/firefly-iii/firefly-iii/files/4007840/firefly-iii-0.10.4.yaml.txt).

**Comment by JC5** [comment]
Thanks, that helps. I've fixed them. Spotted only two of them though, I hope I didn't miss any. I'll pick up your YAML file in a bit, thanks for sharing!

**Comment by GeorgeHahn** [comment]
Thank you! I only saw those two as well.

**Comment by JC5** [comment]
I processed your suggestions. Thanks, I appreciate it. I'm guessing @GeoffreyFrogeye and @emansih are interested in the changes as well.
