### ISSUE TITLE
TrueLayer import

### ISSUE THREAD

**Issue by drcobra** [firefly-iii/firefly-iii#2927]
Hi all,
I signed up for a Salt Edge account for the testing environment, that gives free access to 100 real bank connections but for 90 days 😞 

In the other hand [TrueLayer](https://truelayer.com) seems the testing account doesn't have any day restrictions.
Have you considered to create an import function for the TrueLayer?

**Comment by JC5** [comment]
That must be new then. But no, and I’m not going to in the near future. I just don’t have the time. Feel free to build something though, the api is really accessible these days :)
