### ISSUE TITLE
csv import | book-date

### ISSUE THREAD

**Issue by MakiG0** [firefly-iii/firefly-iii#2929]
**Description:**
I import a csv file, but the book date will not be imported.
I setup the import configuration file (imo) correctly. The book date column is linked with the date-book column of firefly.
I tested with all date fields in firefly, only the date field works well.

Did i make a mistake in the setup or is it something else?

**Extra info**
Firefly III version 4.8.2
Docker environment
firefox

Thanks in advance ;-)

**Comment by JC5** [comment]
Could you share one or two (anonimized) lines and your configuration file?

**Comment by MakiG0** [comment]
Yes, of course.

**test line with header:**
Buchung;Valuta;Auftraggeber/Empfänger;Buchungstext;Verwendungszweck;Betrag;Währung
18.06.2018;20.06.2018;Supermarket;Test8;Test;-19,5;EUR

**Mapping in firefly**
![test](https://user-images.githubusercontent.com/49974203/71562961-5d73a400-2a88-11ea-9cbe-a72959a0c3f2.jpg)

**import result of transaction:**
![image](https://user-images.githubusercontent.com/49974203/71562977-a7f52080-2a88-11ea-9ff1-d27cbea816a4.png)

**Comment by JC5** [comment]
I see what you mean. It'll be fixed in the new [CSV importer](https://github.com/firefly-iii/csv-importer).

**Comment by MakiG0** [comment]
Thanks a lot!
The new csv importer will be a separated tool or integrated in firefly?
How can i test the csv importer?

**Comment by JC5** [comment]
https://github.com/firefly-iii/csv-importer

I'm currently in the progress of documenting everything.

**Comment by MakiG0** [comment]
Perfect. I'll wait till docker documentation is online and give you some feedback ;-)
Thanks a lot for this great tool!!!
