### ISSUE TITLE
Add labels to new/edit transaction forms

### ISSUE THREAD

**Issue by alekstrust** [firefly-iii/firefly-iii#2930]
**Description**
When you are in the transaction form, if the form controls have already been filled, you are not able to know what kind of information you are facing. The page has poor readability that can lead to enter wrong information.

**Solution**
Add proper labels before each form control.

**Additional context**
Right now I'm using v4.7.5 and it has a large form separated by panels. I see the version 5 has a smaller form, but it looks like confusing.

**Bonus points**
See the next image on version 5:

![screenshot 2019-12-29 a la(s) 6 55 24 p  m](https://user-images.githubusercontent.com/4238486/71564400-a702c580-2a6d-11ea-8691-9e3c85b2af03.jpg)

Users are not be able to know what kind of information the first column contains.

Compared to the older one:

![screenshot 2019-12-29 a la(s) 7 05 59 p  m](https://user-images.githubusercontent.com/4238486/71564442-5475d900-2a6e-11ea-8415-dcfb147a6d6a.jpg)

Even if you have all the fields with the same information, you know what it is.

**Comment by JC5** [comment]
That's an excellent idea. I'm going to merge this one with #2692 because that issue contains some more ideas.
