### ISSUE TITLE
Auto reassign money in budgets

### ISSUE THREAD

**Issue by pedrom34** [firefly-iii/firefly-iii#2931]
**Description**
On the first day of the month I define budgets. But, by the end of the month, I sometimes used more money than I thought on one budget and less on another budget. I then have to reassign money to equilibrate budgets. And sometimes, it's a PITA. So I thought...

**Solution**
... can we have some sort of button which takes money from positive budgets and gives it to negative budgets automatically?

**Comment by JC5** [comment]
No, that part of Firefly III won't be automated. That's on purpose.

**Comment by pedrom34** [comment]
OK, I understand.
