### ISSUE TITLE
Account totals on account screen

### ISSUE THREAD

**Issue by viharm** [firefly-iii/firefly-iii#2933]
**Description**

_Firefly III_ has individual summary screens for each account. However there is no clear visibility of account balance. 

Moreover, there is also no visibility of reconciled balance.

**Solution**

I suggest adding tiles on the account screen with the following:
- Current balance based on transactions added to _Firefly III_
- Reconciled balance based on transactions reconciled with the bank statement (this will allow a quick view to understand the amount not yet reconciled, but will also indicate that no reconciliations to be done until the bank statement updates).

**What are alternatives?**

Currently there are two alternatives for account balance
- Hover over today's date in the chart (account screen and dashboard).
- Default financial report (which is also not a quick task).

**Additional context**

Simple and quick view of account balances can be a time-saving feature.

As reconciliation is a time-consuming activity of comparing transactions between _Firefly III_ and the bank statement, a simple view of reconciled balance will tell the user the scale of reconciliation required; Or if it is the same, then not required.

**Extra info**

- _Firefly III_ version: 4.8.2
- Deployment: Docker
- OS: _OpenMediaVault_ 4.1.30-1 based on _Debian GNU/Linux_ 9.11 (_stretch_) using _Linux_ 4.19.0-0.bpo.6-amd64
- Database:  _PostgreSQL_ 9.6.15

**Comment by JC5** [comment]
I'll see what I can do to add the current balance. That deserves a spot. But I'm not going to do something with the "reconciliation balance", sorry about that
