### ISSUE TITLE
Cannot convert transaction to another type and cannot check the debug page

### ISSUE THREAD

**Issue by FanyangMengDev** [firefly-iii/firefly-iii#2934]
**Bug description**
I am running Firefly III version 5.0.0-alpha.1, and my problem is: I cannot convert transaction to another type and cannot check the debug page.
It displays as the following:
![Screenshot_2019-12-31-10-44-10-723_com android chrome](https://user-images.githubusercontent.com/53750381/71608219-86945180-2bba-11ea-9b62-45a716c03986.jpg)
![Screenshot_2019-12-31-10-41-32-773_com android chrome](https://user-images.githubusercontent.com/53750381/71608225-88f6ab80-2bba-11ea-82f4-9f532f8378a6.jpg)

**Steps to reproduce**

Just install the newest version and this problem happens.

**Extra info**

Ubuntu 18.04 LTS
PHP 7.3.13
Cannot report the debug page cause I cannot open it.

**Comment by meetmsajid** [comment]
the same issue on my side also.

**Comment by JC5** [comment]
Thanks. Both issues will be fixed in the next alpha. Keep in mind that this will happen more often when you're running test versions like the alpha and beta releases.

**Comment by FanyangMengDev** [comment]
Not a problem. As a sponsor of you I am glad to use alpha or beta version, find the bug and report to you and make the Firefly better. :)

**Comment by JC5** [comment]
Glad to hear it! I hope to push the next alpha today :)

**Comment by FanyangMengDev** [comment]
Thank you for your hard working again ! This sentence cannot express my appreciation to you no matter how many times I say it :)
And happy new year my friend!
