### ISSUE TITLE
[Question] Secondary Asset Account

### ISSUE THREAD

**Issue by p-rintz** [firefly-iii/firefly-iii#2935]
Hello,

thank you for the great software you made. I am currently starting to use Firefly, but I have a question regarding a savings account that I created. (Called "Savings Account")

So the savings account is an Asset Account. Which makes sense.
When I associate various transactions (for example me putting money into the Savings Account or taking it out) with "Savings Account.", it will associate the transactions, not with the asset account, but with either a expense or revenue account, which is generally fine with me, but the transactions do not show up at all in the asset account. (like they do for example in my normal banking account)

What am I doing wrong here?

Thank you for your help.

PS: I have the same problem with my Cash Wallet, actually. All my "withdrawals" do not appear in the asset account, but only in the expense account. (Both called "Cash Wallet")

**Comment by JC5** [comment]
Make sure you select the correct account from the drop-down with a click or with <kbd>Enter</kbd>. In the mean time, I'll make sure form prioritizes the correct accounts.

**Comment by p-rintz** [comment]
Thanks for the answer.
I tried renaming the Assets Account, so I would be sure that I have the correct Account selected in the Destination Account column, but it doesnt actually show in the dropdown menu when I go to edit a transaction.

It only shows the Expense Account that is the wrong destination account.
Is there something else that needs to be configured first before I can select the assets account in a transaction as a destination?

**Comment by JC5** [comment]
Editing won't work. Now that it's a withdrawal, it won't change types that easily. Use one of the convert buttons from the transaction view (`/transactions/show/xx`).

The drop down should list your accounts like so: 

<img width="417" alt="Screenshot 2019-12-31 at 14 19 42" src="https://user-images.githubusercontent.com/5889984/71622827-5eafe880-2bd0-11ea-8d34-82448f0d1313.png">


If this is not the case for new accounts, clear your browser cache. You can try this on the demo site: https://demo.firefly-iii.org/transactions/create/withdrawal

**Comment by p-rintz** [comment]
No, that works. Thanks. I didnt know that it needed to be a different type of transaction, since they were automatically made withdrawals when I imported my bank statements. 

Again, thank you.

**Comment by JC5** [comment]
In that case, make sure you map the accounts in your file to the correct asset accounts in Firefly III, and this will happen automatically.

**Comment by p-rintz** [comment]
Sadly, thats not really possible, as the bank statement is rather limited. Its basically only got date, amount and a notes field where everything else is crammed into.

Im currently writing rules for it that should help though. Thanks

**Comment by JC5** [comment]
Thanks, appreciate the compliment!
