### ISSUE TITLE
Expenses pie chart shows does not show previous months in Budget page despite the correct range being set

### ISSUE THREAD

**Issue by MaxBayly** [firefly-iii/firefly-iii#2937]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

Upon viewing a particular budget (in my case it's called Monthly Spending), the main bar chart correctly shows expenditure, however the pie charts below are blank ("There is not enough information (yet) to generate this chart."). 

It seems that the pie charts are trying to generate from the current period despite a different period being set (see screenshot)

These pie charts were working correctly and displayed information for December until the turn of the new month.

**Steps to reproduce**
Change the period in the top right drop down and view the chosen budget's page

**Extra info**

Browser: Chrome (macOS)
Debug:
`Debug information generated at 2020-01-01 06:57:45 Europe/Amsterdam for Firefly III version **4.8.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.12 |
| Display errors | Off |
| Session start | 2019-12-01 00:00:00 |
| Session end | 2019-12-31 00:00:00 |
| Session first | 2019-11-27 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |`

**Bonus points**
<img width="1449" alt="Screen Shot 2020-01-01 at 4 50 24 pm" src="https://user-images.githubusercontent.com/9945607/71638583-e4f32a00-2cb7-11ea-8d9f-da48f5119076.png">

**Comment by JC5** [comment]
Nice find. This is a bug and it should be fixed in the next release.
