### ISSUE TITLE
Show the correct balance of expense accounts

### ISSUE THREAD

**Issue by cedricpim** [firefly-iii/firefly-iii#2938]
**Bug description**
I am running Firefly III version 5.0.0-alpha.1, and my problem is that the expense accounts (and maybe revenue) do not show the proper balance nor the proper value in the graph when there are multiple currencies. However, everything seems to be shown correctly in the dashboard. A couple of attachments follow:

Dashboard:
![image](https://user-images.githubusercontent.com/1127158/71644960-e1b46a00-2cc8-11ea-955a-16b9fb19426d.png)

Expense account:

![image](https://user-images.githubusercontent.com/1127158/71644969-f3960d00-2cc8-11ea-9b4f-293bb8153d5d.png)

![image](https://user-images.githubusercontent.com/1127158/71644975-fdb80b80-2cc8-11ea-8e57-5115a90f4233.png)

**Steps to reproduce**

1. Create a new user account.
2. Create a new asset account in euro.
3. Create a new asset account in another currency.
4. Book a transaction for an expense account AAA, from the euro account, with the value of 10.
5. Book a transaction for an expense account AAA, from the other currency account, with the value of 20.
6. Check that the expense account does not show the whole value.

Potential Solution: Allow a setting option where the user can choose between converting everything to the default currency or showing the balances in each currency (like it is done in dashboard). Having an option in settings seems cool but it is probably too much work so it might be more reasonable to just do what is done in the dashboard.

Note: Didn't want to lose the opportunity to congratulate you on the great work you are doing with this :clap:

**Comment by JC5** [comment]
Thanks for the compliments! Yes, this is a known issue. I'll put in some work to make the charts work with multiple currencies, but otherwise the balances of expense and revenue accounts are not something I want to focus on: I don't care that they aren't displayed correctly, as long as the asset accounts are correct/

**Comment by JC5** [comment]
For clarity's sake, the balance in the lists will remain as is. However, the chart on the /accounts/show/x page will be multi-currency.

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.
