### ISSUE TITLE
Find transactions without budget

### ISSUE THREAD

**Issue by Vringe** [firefly-iii/firefly-iii#2940]
I am running Firefly III version 4.8.2

**Description**
Is there a way to show all transactions that have **not** a budget assigned? The only way I know is by going to the financial reports page and showing the budget column. Unfortunately the column cannot be sorted so it's a bit hard to find.

Is there a page I have missed?

**Comment by JC5** [comment]
Yes, bottom of the page: `/budgets`:

<img width="970" alt="Screenshot 2020-01-02 at 06 21 00" src="https://user-images.githubusercontent.com/5889984/71652759-ae50fa00-2d1f-11ea-986e-9aa7f6f2e556.png">

**Comment by Vringe** [comment]
Oh, my fault. That's what I was searching for. Thank you!
