### ISSUE TITLE
html entities not decoded on transaction edit page

### ISSUE THREAD

**Issue by Vringe** [firefly-iii/firefly-iii#2941]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

HTML entities inside the notes field of a transaction are not displayed correctly when editing the transaction.

**Steps to reproduce**
- Add a note to a transaction with html entities (e.g. `&` character)
- Edit the transaction again ->  `&amp;` is shown instead of `&`

**Extra info**
Debug information generated at 2020-01-02 00:43:17 Europe/Zurich for Firefly III version **4.8.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.11-1\~deb10u1 |
| Display errors | Off |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2020-01-31 23:59:59 |
| Session first | 2019-01-16 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache |

**Comment by JC5** [comment]
Yes, this happens. I'll make some effort to get rid of it. Unfortunately, over time notes have been stored with *and* without their html entities encoded, so I have to play it safe. But it shouldn't be hard to make some kind of an "detection" routine.

Thanks for letting me know, I'll pick it up.

**Comment by JC5** [comment]
Should be fixed in the next release.
