### ISSUE TITLE
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#2942]
Just an FYI but you're most likely alrady aware of it...
Doing a clean install to see what's going on with my little chart bug via command :
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 5.0.0-alpha.2

I get the warning as posted in the title from composer.

**Comment by JC5** [comment]
I saw it, yes. It's another package's dependency. I haven't searched yet which one.

**Comment by GaryQ** [comment]
at least 3 as far as I can see...

\laravel\passport
\league\oauth2-server
\symfony\psr-http-message-bridge\

**Comment by JC5** [comment]
Oh great, well at least these are pretty major libraries so I hope they'll transition soon.

**Comment by GaryQ** [comment]
Yeah, hope is a big word LOL
BTW sent you an email to thegrumpydictator@gmail.com just curious if it got through or not (no hurry to reply to it just curious if it got through or not)

**Comment by JC5** [comment]
Haha yeah that's true. I just replied a minute ago :grin:

**Comment by GaryQ** [comment]
Too funny i got the popup as soon as I het send to the question

**Comment by hstoellinger** [comment]
Hello,
Same here! Installing drupal/token:^1.6. What's the deal?

**Comment by Lawri-van-Buel** [comment]
@hstoellinger do you got by any chance a drupal installation on your system? Otherwise I fail to see why you would need the drupal token module...

**Comment by hstoellinger** [comment]
Naturally I have a Drupal installation on my system, actually 3 of them (testing, development, copy of production system on server (https://www.rainer-regimentsmuseum-salzburg.at)

**Comment by hstoellinger** [comment]
By the way, the production system is at version 8.7.10, while - on the local system where I just installed the latest version of token module - I am at 8.8.1. The install of THAT version actually also wasn't a totally smooth affair... (scaffolding files, etc.)

**Comment by hstoellinger** [comment]
here I am again... The messages I got when installing the latest token module were the following:
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.

**Comment by GaryQ** [comment]
https://www.zend.com/blog/what-status-zend-framework-transition-laminas

everything zendframework is being transitioned to laminas open source project. There's a lot of projects going to be popping up these messages as zend is to php like .css is to html LOL

**Comment by JC5** [comment]
This issue is the first that pops up when you Google for the problem. That explains it.

**People**: I can't help you with this issue. One of your dependencies or your own code is depending on a deprecated package. Find the offending package and ask them to replace it.

**Comment by GaryQ** [comment]
That's why I've been having so much trouble deciding to write a Windows app, continue with Excel or use Firefly III... everything depends on something that depends on something else here's the composer show -t results on Firefly:

omposer show -t
adldap2/adldap2-laravel v6.0.8 LDAP Authentication & Management for Laravel.
├──adldap2/adldap2 ^10.1
│  ├──ext-json *
│  ├──ext-ldap *
│  ├──illuminate/contracts ~5.0|~6.0
│  ├──php >=7.0
│  ├──psr/log ~1.0
│  │  └──php >=5.3.0
│  ├──psr/simple-cache ~1.0
│  │  └──php >=5.3.0
│  └──tightenco/collect ~5.0|~6.0
│     ├──php ^7.1.3
│     └──symfony/var-dumper ^3.4 || ^4.0 || ^5.0
│        ├──php ^7.1.3
│        ├──symfony/polyfill-mbstring ~1.0
│        │  └──php >=5.3.3
│        └──symfony/polyfill-php72 ~1.5
│           └──php >=5.3.3
├──illuminate/support ~5.5|~6.0
└──php >=7.1
bacon/bacon-qr-code 1.0.3 BaconQrCode is a QR code generator for PHP.
├──ext-iconv *
└──php ^5.4|^7.0
bunq/sdk_php dev-master bunq PHP SDK
├──ext-curl *
├──ext-json *
├──ext-mbstring *
├──guzzlehttp/guzzle ~6
│  ├──ext-json *
│  ├──guzzlehttp/promises ^1.0
│  │  └──php >=5.5.0
│  ├──guzzlehttp/psr7 ^1.6.1
│  │  ├──php >=5.4.0
│  │  ├──psr/http-message ~1.0
│  │  │  └──php >=5.3.0
│  │  └──ralouphie/getallheaders ^2.0.5 || ^3.0.0
│  │     └──php >=5.6
│  └──php >=5.5
└──php ^7.0.13
davejamesmiller/laravel-breadcrumbs 5.3.2 A simple Laravel-style way to create breadcrumbs.
├──facade/ignition-contracts ^1.0
│  └──php ^7.1
├──illuminate/support >=5.6
├──illuminate/view >=5.6
└──php >=7.1.3
doctrine/dbal v2.10.0 Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
├──doctrine/cache ^1.0
│  └──php ~7.1
├──doctrine/event-manager ^1.0
│  └──php ^7.1
├──ext-pdo *
└──php ^7.2
fideloper/proxy 4.2.2 Set trusted proxies for Laravel
├──illuminate/contracts ^5.0|^6.0|^7.0
└──php >=5.4.0
jc5/google2fa-laravel 2.0.4 A One Time Password Authentication package, compatible with Google Authenticator.
├──laravel/framework >=5.4.36
│  ├──doctrine/inflector ^1.1
│  │  └──php ^7.1
│  ├──dragonmantank/cron-expression ^2.0
│  │  └──php ^7.0
│  ├──egulias/email-validator ^2.1.10
│  │  ├──doctrine/lexer ^1.0.1
│  │  │  └──php ^7.2
│  │  └──php >=5.5
│  ├──erusev/parsedown ^1.7
│  │  ├──ext-mbstring *
│  │  └──php >=5.3.0
│  ├──ext-json *
│  ├──ext-mbstring *
│  ├──ext-openssl *
│  ├──league/flysystem ^1.0.8
│  │  ├──ext-fileinfo *
│  │  └──php >=5.5.9
│  ├──monolog/monolog ^1.12|^2.0
│  │  ├──php ^7.2
│  │  └──psr/log ^1.0.1
│  │     └──php >=5.3.0
│  ├──nesbot/carbon ^2.0
│  │  ├──ext-json *
│  │  ├──php ^7.1.8 || ^8.0
│  │  └──symfony/translation ^3.4 || ^4.0 || ^5.0
│  │     ├──php ^7.1.3
│  │     ├──symfony/polyfill-mbstring ~1.0
│  │     │  └──php >=5.3.3
│  │     └──symfony/translation-contracts ^1.1.6|^2
│  │        └──php ^7.2.5
│  ├──opis/closure ^3.1
│  │  └──php ^5.4 || ^7.0
│  ├──php ^7.2
│  ├──psr/container ^1.0
│  │  └──php >=5.3.0
│  ├──psr/simple-cache ^1.0
│  │  └──php >=5.3.0
│  ├──ramsey/uuid ^3.7
│  │  ├──ext-json *
│  │  ├──paragonie/random_compat ^1 | ^2 | 9.99.99
│  │  │  └──php ^7
│  │  ├──php ^5.4 | ^7 | ^8
│  │  └──symfony/polyfill-ctype ^1.8
│  │     └──php >=5.3.3
│  ├──swiftmailer/swiftmailer ^6.0
│  │  ├──egulias/email-validator ~2.0
│  │  │  ├──doctrine/lexer ^1.0.1
│  │  │  │  └──php ^7.2
│  │  │  └──php >=5.5
│  │  ├──php >=7.0.0
│  │  ├──symfony/polyfill-iconv ^1.0
│  │  │  └──php >=5.3.3
│  │  ├──symfony/polyfill-intl-idn ^1.10
│  │  │  ├──php >=5.3.3
│  │  │  ├──symfony/polyfill-mbstring ^1.3
│  │  │  │  └──php >=5.3.3
│  │  │  └──symfony/polyfill-php72 ^1.9
│  │  │     └──php >=5.3.3
│  │  └──symfony/polyfill-mbstring ^1.0
│  │     └──php >=5.3.3
│  ├──symfony/console ^4.3.4
│  │  ├──php ^7.1.3
│  │  ├──symfony/polyfill-mbstring ~1.0
│  │  │  └──php >=5.3.3
│  │  ├──symfony/polyfill-php73 ^1.8
│  │  │  └──php >=5.3.3
│  │  └──symfony/service-contracts ^1.1|^2
│  │     ├──php ^7.2.5
│  │     └──psr/container ^1.0
│  │        └──php >=5.3.0
│  ├──symfony/debug ^4.3.4
│  │  ├──php ^7.1.3
│  │  └──psr/log ~1.0
│  │     └──php >=5.3.0
│  ├──symfony/finder ^4.3.4
│  │  └──php ^7.1.3
│  ├──symfony/http-foundation ^4.3.4
│  │  ├──php ^7.1.3
│  │  ├──symfony/mime ^4.3|^5.0
│  │  │  ├──php ^7.2.5
│  │  │  ├──symfony/polyfill-intl-idn ^1.10
│  │  │  │  ├──php >=5.3.3
│  │  │  │  ├──symfony/polyfill-mbstring ^1.3
│  │  │  │  │  └──php >=5.3.3
│  │  │  │  └──symfony/polyfill-php72 ^1.9
│  │  │  │     └──php >=5.3.3
│  │  │  └──symfony/polyfill-mbstring ^1.0
│  │  │     └──php >=5.3.3
│  │  └──symfony/polyfill-mbstring ~1.1
│  │     └──php >=5.3.3
│  ├──symfony/http-kernel ^4.3.4
│  │  ├──php ^7.1.3
│  │  ├──psr/log ~1.0
│  │  │  └──php >=5.3.0
│  │  ├──symfony/error-handler ^4.4
│  │  │  ├──php ^7.1.3
│  │  │  ├──psr/log ~1.0
│  │  │  │  └──php >=5.3.0
│  │  │  ├──symfony/debug ^4.4
│  │  │  │  ├──php ^7.1.3
│  │  │  │  └──psr/log ~1.0
│  │  │  │     └──php >=5.3.0
│  │  │  └──symfony/var-dumper ^4.4|^5.0
│  │  │     ├──php ^7.1.3
│  │  │     ├──symfony/polyfill-mbstring ~1.0
│  │  │     │  └──php >=5.3.3
│  │  │     └──symfony/polyfill-php72 ~1.5
│  │  │        └──php >=5.3.3
│  │  ├──symfony/event-dispatcher ^4.4
│  │  │  ├──php ^7.1.3
│  │  │  └──symfony/event-dispatcher-contracts ^1.1
│  │  │     └──php ^7.1.3
│  │  ├──symfony/http-foundation ^4.4|^5.0
│  │  │  ├──php ^7.1.3
│  │  │  ├──symfony/mime ^4.3|^5.0
│  │  │  │  ├──php ^7.2.5
│  │  │  │  ├──symfony/polyfill-intl-idn ^1.10
│  │  │  │  │  ├──php >=5.3.3
│  │  │  │  │  ├──symfony/polyfill-mbstring ^1.3
│  │  │  │  │  │  └──php >=5.3.3
│  │  │  │  │  └──symfony/polyfill-php72 ^1.9
│  │  │  │  │     └──php >=5.3.3
│  │  │  │  └──symfony/polyfill-mbstring ^1.0
│  │  │  │     └──php >=5.3.3
│  │  │  └──symfony/polyfill-mbstring ~1.1
│  │  │     └──php >=5.3.3
│  │  ├──symfony/polyfill-ctype ^1.8
│  │  │  └──php >=5.3.3
│  │  └──symfony/polyfill-php73 ^1.9
│  │     └──php >=5.3.3
│  ├──symfony/process ^4.3.4
│  │  └──php ^7.1.3
│  ├──symfony/routing ^4.3.4
│  │  └──php ^7.1.3
│  ├──symfony/var-dumper ^4.3.4
│  │  ├──php ^7.1.3
│  │  ├──symfony/polyfill-mbstring ~1.0
│  │  │  └──php >=5.3.3
│  │  └──symfony/polyfill-php72 ~1.5
│  │     └──php >=5.3.3
│  ├──tijsverkoyen/css-to-inline-styles ^2.2.1
│  │  ├──ext-dom *
│  │  ├──ext-libxml *
│  │  ├──php ^5.5 || ^7.0
│  │  └──symfony/css-selector ^2.7 || ^3.0 || ^4.0 || ^5.0
│  │     └──php ^7.2.5
│  └──vlucas/phpdotenv ^3.3
│     ├──php ^5.4 || ^7.0
│     ├──phpoption/phpoption ^1.5
│     │  └──php ^5.5.9 || ^7.0
│     └──symfony/polyfill-ctype ^1.9
│        └──php >=5.3.3
├──php >=7.3
└──pragmarx/google2fa-qrcode ^1.0
   ├──bacon/bacon-qr-code ~1.0|~2.0
   │  ├──ext-iconv *
   │  └──php ^5.4|^7.0
   ├──php >=5.4
   └──pragmarx/google2fa >=4.0
      ├──paragonie/constant_time_encoding ~1.0|~2.0
      │  └──php ^7|^8
      ├──paragonie/random_compat >=1
      │  └──php ^7
      ├──php >=5.4
      └──symfony/polyfill-php56 ~1.2
         ├──php >=5.3.3
         └──symfony/polyfill-util ~1.0
            └──php >=5.3.3
laravel/framework v6.9.0 The Laravel Framework.
├──doctrine/inflector ^1.1
│  └──php ^7.1
├──dragonmantank/cron-expression ^2.0
│  └──php ^7.0
├──egulias/email-validator ^2.1.10
│  ├──doctrine/lexer ^1.0.1
│  │  └──php ^7.2
│  └──php >=5.5
├──erusev/parsedown ^1.7
│  ├──ext-mbstring *
│  └──php >=5.3.0
├──ext-json *
├──ext-mbstring *
├──ext-openssl *
├──league/flysystem ^1.0.8
│  ├──ext-fileinfo *
│  └──php >=5.5.9
├──monolog/monolog ^1.12|^2.0
│  ├──php ^7.2
│  └──psr/log ^1.0.1
│     └──php >=5.3.0
├──nesbot/carbon ^2.0
│  ├──ext-json *
│  ├──php ^7.1.8 || ^8.0
│  └──symfony/translation ^3.4 || ^4.0 || ^5.0
│     ├──php ^7.1.3
│     ├──symfony/polyfill-mbstring ~1.0
│     │  └──php >=5.3.3
│     └──symfony/translation-contracts ^1.1.6|^2
│        └──php ^7.2.5
├──opis/closure ^3.1
│  └──php ^5.4 || ^7.0
├──php ^7.2
├──psr/container ^1.0
│  └──php >=5.3.0
├──psr/simple-cache ^1.0
│  └──php >=5.3.0
├──ramsey/uuid ^3.7
│  ├──ext-json *
│  ├──paragonie/random_compat ^1 | ^2 | 9.99.99
│  │  └──php ^7
│  ├──php ^5.4 | ^7 | ^8
│  └──symfony/polyfill-ctype ^1.8
│     └──php >=5.3.3
├──swiftmailer/swiftmailer ^6.0
│  ├──egulias/email-validator ~2.0
│  │  ├──doctrine/lexer ^1.0.1
│  │  │  └──php ^7.2
│  │  └──php >=5.5
│  ├──php >=7.0.0
│  ├──symfony/polyfill-iconv ^1.0
│  │  └──php >=5.3.3
│  ├──symfony/polyfill-intl-idn ^1.10
│  │  ├──php >=5.3.3
│  │  ├──symfony/polyfill-mbstring ^1.3
│  │  │  └──php >=5.3.3
│  │  └──symfony/polyfill-php72 ^1.9
│  │     └──php >=5.3.3
│  └──symfony/polyfill-mbstring ^1.0
│     └──php >=5.3.3
├──symfony/console ^4.3.4
│  ├──php ^7.1.3
│  ├──symfony/polyfill-mbstring ~1.0
│  │  └──php >=5.3.3
│  ├──symfony/polyfill-php73 ^1.8
│  │  └──php >=5.3.3
│  └──symfony/service-contracts ^1.1|^2
│     ├──php ^7.2.5
│     └──psr/container ^1.0
│        └──php >=5.3.0
├──symfony/debug ^4.3.4
│  ├──php ^7.1.3
│  └──psr/log ~1.0
│     └──php >=5.3.0
├──symfony/finder ^4.3.4
│  └──php ^7.1.3
├──symfony/http-foundation ^4.3.4
│  ├──php ^7.1.3
│  ├──symfony/mime ^4.3|^5.0
│  │  ├──php ^7.2.5
│  │  ├──symfony/polyfill-intl-idn ^1.10
│  │  │  ├──php >=5.3.3
│  │  │  ├──symfony/polyfill-mbstring ^1.3
│  │  │  │  └──php >=5.3.3
│  │  │  └──symfony/polyfill-php72 ^1.9
│  │  │     └──php >=5.3.3
│  │  └──symfony/polyfill-mbstring ^1.0
│  │     └──php >=5.3.3
│  └──symfony/polyfill-mbstring ~1.1
│     └──php >=5.3.3
├──symfony/http-kernel ^4.3.4
│  ├──php ^7.1.3
│  ├──psr/log ~1.0
│  │  └──php >=5.3.0
│  ├──symfony/error-handler ^4.4
│  │  ├──php ^7.1.3
│  │  ├──psr/log ~1.0
│  │  │  └──php >=5.3.0
│  │  ├──symfony/debug ^4.4
│  │  │  ├──php ^7.1.3
│  │  │  └──psr/log ~1.0
│  │  │     └──php >=5.3.0
│  │  └──symfony/var-dumper ^4.4|^5.0
│  │     ├──php ^7.1.3
│  │     ├──symfony/polyfill-mbstring ~1.0
│  │     │  └──php >=5.3.3
│  │     └──symfony/polyfill-php72 ~1.5
│  │        └──php >=5.3.3
│  ├──symfony/event-dispatcher ^4.4
│  │  ├──php ^7.1.3
│  │  └──symfony/event-dispatcher-contracts ^1.1
│  │     └──php ^7.1.3
│  ├──symfony/http-foundation ^4.4|^5.0
│  │  ├──php ^7.1.3
│  │  ├──symfony/mime ^4.3|^5.0
│  │  │  ├──php ^7.2.5
│  │  │  ├──symfony/polyfill-intl-idn ^1.10
│  │  │  │  ├──php >=5.3.3
│  │  │  │  ├──symfony/polyfill-mbstring ^1.3
│  │  │  │  │  └──php >=5.3.3
│  │  │  │  └──symfony/polyfill-php72 ^1.9
│  │  │  │     └──php >=5.3.3
│  │  │  └──symfony/polyfill-mbstring ^1.0
│  │  │     └──php >=5.3.3
│  │  └──symfony/polyfill-mbstring ~1.1
│  │     └──php >=5.3.3
│  ├──symfony/polyfill-ctype ^1.8
│  │  └──php >=5.3.3
│  └──symfony/polyfill-php73 ^1.9
│     └──php >=5.3.3
├──symfony/process ^4.3.4
│  └──php ^7.1.3
├──symfony/routing ^4.3.4
│  └──php ^7.1.3
├──symfony/var-dumper ^4.3.4
│  ├──php ^7.1.3
│  ├──symfony/polyfill-mbstring ~1.0
│  │  └──php >=5.3.3
│  └──symfony/polyfill-php72 ~1.5
│     └──php >=5.3.3
├──tijsverkoyen/css-to-inline-styles ^2.2.1
│  ├──ext-dom *
│  ├──ext-libxml *
│  ├──php ^5.5 || ^7.0
│  └──symfony/css-selector ^2.7 || ^3.0 || ^4.0 || ^5.0
│     └──php ^7.2.5
└──vlucas/phpdotenv ^3.3
   ├──php ^5.4 || ^7.0
   ├──phpoption/phpoption ^1.5
   │  └──php ^5.5.9 || ^7.0
   └──symfony/polyfill-ctype ^1.9
      └──php >=5.3.3
laravel/passport v8.1.0 Laravel Passport provides OAuth2 server support to Laravel.
├──ext-json *
├──firebase/php-jwt ^3.0|^4.0|^5.0
│  └──php >=5.3.0
├──guzzlehttp/guzzle ^6.0
│  ├──ext-json *
│  ├──guzzlehttp/promises ^1.0
│  │  └──php >=5.5.0
│  ├──guzzlehttp/psr7 ^1.6.1
│  │  ├──php >=5.4.0
│  │  ├──psr/http-message ~1.0
│  │  │  └──php >=5.3.0
│  │  └──ralouphie/getallheaders ^2.0.5 || ^3.0.0
│  │     └──php >=5.6
│  └──php >=5.5
├──illuminate/auth ^6.0|^7.0
├──illuminate/console ^6.0|^7.0
├──illuminate/container ^6.0|^7.0
├──illuminate/contracts ^6.0|^7.0
├──illuminate/cookie ^6.0|^7.0
├──illuminate/database ^6.0|^7.0
├──illuminate/encryption ^6.0|^7.0
├──illuminate/http ^6.0|^7.0
├──illuminate/support ^6.0|^7.0
├──league/oauth2-server ^8.0
│  ├──defuse/php-encryption ^2.2.1
│  │  ├──ext-openssl *
│  │  ├──paragonie/random_compat >= 2
│  │  │  └──php ^7
│  │  └──php >=5.4.0
│  ├──ext-json *
│  ├──ext-openssl *
│  ├──lcobucci/jwt ^3.3.1
│  │  ├──ext-mbstring *
│  │  ├──ext-openssl *
│  │  └──php ^5.6 || ^7.0
│  ├──league/event ^2.2
│  │  └──php >=5.4.0
│  ├──php >=7.1.0
│  └──psr/http-message ^1.0.1
│     └──php >=5.3.0
├──php ^7.2
├──phpseclib/phpseclib ^2.0
│  └──php >=5.3.3
├──symfony/psr-http-message-bridge ^1.0
│  ├──php ^7.1
│  ├──psr/http-message ^1.0
│  │  └──php >=5.3.0
│  └──symfony/http-foundation ^4.4 || ^5.0
│     ├──php ^7.1.3
│     ├──symfony/mime ^4.3|^5.0
│     │  ├──php ^7.2.5
│     │  ├──symfony/polyfill-intl-idn ^1.10
│     │  │  ├──php >=5.3.3
│     │  │  ├──symfony/polyfill-mbstring ^1.3
│     │  │  │  └──php >=5.3.3
│     │  │  └──symfony/polyfill-php72 ^1.9
│     │  │     └──php >=5.3.3
│     │  └──symfony/polyfill-mbstring ^1.0
│     │     └──php >=5.3.3
│     └──symfony/polyfill-mbstring ~1.1
│        └──php >=5.3.3
└──zendframework/zend-diactoros ^2.0
   ├──php ^7.1
   ├──psr/http-factory ^1.0
   │  ├──php >=7.0.0
   │  └──psr/http-message ^1.0
   │     └──php >=5.3.0
   └──psr/http-message ^1.0
      └──php >=5.3.0
laravelcollective/html v6.0.3 HTML and Form Builders for the Laravel Framework
├──illuminate/http ^6.0
├──illuminate/routing ^6.0
├──illuminate/session ^6.0
├──illuminate/support ^6.0
├──illuminate/view ^6.0
└──php >=7.2
league/commonmark 1.1.2 PHP Markdown parser based on the CommonMark spec
├──ext-mbstring *
└──php ^7.1
league/csv 9.5.0 Csv data manipulation made easy in PHP
├──ext-dom *
├──ext-json *
├──ext-mbstring *
└──php >=7.0.10
league/flysystem-replicate-adapter 1.0.1 Flysystem adapter for Replica's
├──league/flysystem ~1.0
│  ├──ext-fileinfo *
│  └──php >=5.5.9
└──php >=5.4.0
league/flysystem-sftp 1.0.22 Flysystem adapter for SFTP
├──league/flysystem ~1.0
│  ├──ext-fileinfo *
│  └──php >=5.5.9
├──php >=5.6.0
└──phpseclib/phpseclib ~2.0
   └──php >=5.3.3
league/fractal 0.18.0 Handle the output of complex data structures ready for API output.
└──php >=5.4
litipk/flysystem-fallback-adapter 0.1.3 Flysystem adapter for fallback filesystems
├──league/flysystem ~1.0
│  ├──ext-fileinfo *
│  └──php >=5.5.9
└──php >=5.4.0
mschindler83/fints-hbci-php 1.0.4 PHP Library for the protocols fints and hbci
├──php >=5.3.2
└──psr/log ~1.0
   └──php >=5.3.0
pragmarx/google2fa v7.0.0 A One Time Password Authentication package, compatible with Google Authenticator.
├──paragonie/constant_time_encoding ~1.0|~2.0
│  └──php ^7|^8
├──paragonie/random_compat >=1
│  └──php ^7
├──php >=5.4
└──symfony/polyfill-php56 ~1.2
   ├──php >=5.3.3
   └──symfony/polyfill-util ~1.0
      └──php >=5.3.3
pragmarx/recovery v0.1.0 Create recovery codes for two factor auth
├──php ~7.0
└──pragmarx/random ~0.1
   └──php >=7.0
predis/predis v1.1.1 Flexible and feature-complete Redis client for PHP and HHVM
└──php >=5.3.9
rcrowe/twigbridge v0.11.2 Adds the power of Twig to Laravel
├──illuminate/support ^5.5|^6
├──illuminate/view ^5.5|^6
├──php >=7.1
└──twig/twig ~2.0
   ├──php ^7.0
   ├──symfony/polyfill-ctype ^1.8
   │  └──php >=5.3.3
   └──symfony/polyfill-mbstring ^1.3
      └──php >=5.3.3

**Comment by hstoellinger** [comment]
Thanks a lot! I will have a look. Since I haven't yet written any custom Drupal modules for my system, it's going to be some dependency on a package that some core or contrib package depends on... (lovely!)

**Comment by hstoellinger** [comment]
Hello again,
I can see that Drupal uses the Zendframework extensively. There are LOADS of entries in the output of composer show -t. Again, since I have not written any custom code as yet (except for learning purposes!), I will probably just wait till the Drupal core/contrib-modules devs look after the issue...

**Comment by GaryQ** [comment]
I don't think it's anything to worry about even the warnings in the current deploymenets. They are just switching to a new open source deployment under a new project name and structure.

**Comment by hstoellinger** [comment]
Good Morning (at least - here!, don't know where you "hang out")...
Thanks. I had a quick look at Laminas...

**Comment by GaryQ** [comment]
> Good Morning (at least - here!, don't know where you "hang out")...

You're welcome. Hope it removed any stress about the warning messages. I'm guessing projects will adjust anytime between now and never LOL

My Answer would probably be: I hang out Far away to the west Across that big pond, North of "Trump Lamd" where my response would be Good morning to you too as of right now since my clock just hit 6:00 AM. :)

**Comment by JC5** [comment]
The package has been removed from Firefly III's dependencies so I'm considering this one fixed.
