### ISSUE TITLE
.env Database default changes? 

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#2943]
Still on 5.0.0 Alpha 2 install phase....

Was editing the .env and was surprised to notice the default DB config was no longer MySQL but now Postgres. Intentional or accidental?

**Comment by JC5** [comment]
No it has been pgsql for quite some time now. It changed in 4.8.1, when I unified all `.env.*` files into one `.env.example` file. You can now download the docker compose file, the .env.example file and start Firefly III using Docker compose without changing anything.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/commit/7cee183f1c95cb7854113097fc7291dc4d858146

**Comment by GaryQ** [comment]
Oh my, then I've been using MySQL and a "very old" config file. I'm assuming Its Ok if I just replaced the pg stuff with the MySQL config? I'm not running it in a container. Just local Apache2.4

**Comment by JC5** [comment]
That's not a problem. New environment variables always get a sensible default.
