### ISSUE TITLE
Install without ldap

### ISSUE THREAD

**Issue by sitenzo** [firefly-iii/firefly-iii#2944]
I am running Firefly III version 4.8.2

**Description**
Is there a way to install Firefly without ldap support.
My hosting provider is not supporting the ldap-ext

**Bonus points**
![tempsnip](https://user-images.githubusercontent.com/52133032/71673048-fb60ba80-2d77-11ea-802f-db306cb975aa.png)

**Comment by JC5** [comment]
1. Clone the GitHub repository.
2. If you don't want to run the alpha, also run `git checkout tags/4.8.2 -b master`. You may need to Google the exact command.
3. Edit composer.json and remove the line that says `"adldap2/adldap2-laravel": "6.*",`.
4. Run `composer install --no-dev`.

**Comment by sitenzo** [comment]
Thanks, that works for me 👍
