### ISSUE TITLE
Budget field has no description/placeholder when editing a transaction

### ISSUE THREAD

**Issue by ThinkPadNL** [firefly-iii/firefly-iii#2945]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is that when you edit a transaction, the description/placeholder is empty. This just shows you an initial empty dropdown. By clicking it i see values that i recognize as my budgets, but this might be confusing for new users.

Also the amount of decimal places is a bit overkill which makes it look ugly. But this might have a reason, if you use cryptocoins?
![image](https://user-images.githubusercontent.com/12446338/71693252-4694c080-2dac-11ea-813f-dcc51d3d6622.png)

**Comment by JC5** [comment]
Yes, nice find. The decimal thing should be fixed already in the next release.

**Comment by JC5** [comment]
Will be fixed in the next release.
