### ISSUE TITLE
What are the actual permissions?

### ISSUE THREAD

**Issue by negativzeroe** [firefly-iii/firefly-iii#2947]
I cannot get this to even start, web page says whoops there is a fatal error, logs say database connection refused, database says permission denied in database folder. I've run chown and tried running the containers with PUID=1000 PGID=1000 to no avail. These are the run commands, please tell me where I'm being an idiot. I've tried the name for the database container under db host as well as the IP.
Note, net=local is for reverse proxy.

    docker run -d \
    --name=fireflydb \
    --net=local \
    -p 5433:5432 \
    -e POSTGRES_PASSWORD=firefly \
    -e POSTGRES_USER=firefly \
    -v /home/administrator/apps/firefly/database:/var/lib/postgresql/data \
    postgres:12

    docker run -d \
    --net=local \
    --name=firefly \
    --link=fireflydb \
    -e DB_HOST=10.1.0.222 \
    -e DB_DATABASE=firefly \
    -e DB_USERNAME=firefly \
    -e DB_PORT=5433 \
    -e DB_PASSWORD=firefly \
    -e APP_KEY=[my 32 char key] \
    -p 8087:80 \
    -v /home/administrator/apps/firefly/export:/var/www/firefly-iii/storage/export \
    -v /home/administrator/apps/firefly/upload:/var/www/firefly-iii/storage/upload \
    jc5x/firefly-iii:latest

**Comment by JC5** [comment]
Try running it with debug mode. Use APP_DEBUG=true and APP_LOG_LEVEL=debug.

**Comment by JC5** [comment]
Oh and since the DB and FF3 are both on local, shouldn’t the port be 5432?

**Comment by negativzeroe** [comment]
I have another database using that port, unless it's a case of it sees the internal port instead of external? Logs:
```
    Now in entrypoint.sh for Firefly III
    Making directories...
    Touch DB file (if SQLlite)...
    Run chown on /var/www/firefly-iii/storage...
    Run chmod on /var/www/firefly-iii/storage...
    Remove log file...
    Dump auto load...
    Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
    Generated optimized autoload files containing 5053 classes
    Discover packages...
    Discovered Package: adldap2/adldap2-laravel
    Discovered Package: danhunsaker/laravel-flysystem-others
    Discovered Package: davejamesmiller/laravel-breadcrumbs
    Discovered Package: fideloper/proxy
    Discovered Package: laravel/passport
    Discovered Package: laravelcollective/html
    Discovered Package: nesbot/carbon
    Discovered Package: pragmarx/google2fa-laravel
    Discovered Package: rcrowe/twigbridge
    Package manifest generated successfully.
    Run various artisan commands...
    wait-for-it.sh: waiting 15 seconds for 10.1.0.222:5433
    wait-for-it.sh: 10.1.0.222:5433 is available after 0 seconds
    db is up. Time to execute artisan commands
    Application cache cleared!
    This command currently applies to MySQL connections only.
    Error when connecting to DB: SQLSTATE[HY000] [2002] Connection refused
    Now in entrypoint.sh for Firefly III
    Making directories...
    Touch DB file (if SQLlite)...
    Run chown on /var/www/firefly-iii/storage...
    Run chmod on /var/www/firefly-iii/storage...
    Remove log file...
    Dump auto load...
    Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
    Generated optimized autoload files containing 5053 classes
    Discover packages...
    Discovered Package: adldap2/adldap2-laravel
    Discovered Package: danhunsaker/laravel-flysystem-others
    Discovered Package: davejamesmiller/laravel-breadcrumbs
    Discovered Package: fideloper/proxy
    Discovered Package: laravel/passport
    Discovered Package: laravelcollective/html
    Discovered Package: nesbot/carbon
    Discovered Package: pragmarx/google2fa-laravel
    Discovered Package: rcrowe/twigbridge
    Package manifest generated successfully.
    Run various artisan commands...
    wait-for-it.sh: waiting 15 seconds for 10.1.0.222:5433
    wait-for-it.sh: 10.1.0.222:5433 is available after 0 seconds
    db is up. Time to execute artisan commands
    Application cache cleared!
    This command currently applies to MySQL connections only.
    Error when connecting to DB: SQLSTATE[HY000] [2002] Connection refused

```

**Comment by JC5** [comment]
No 5433 is is correct, the wait-fo-it script would have complained otherwise. But the “connection refused” error isn’t something I can remedy. 

Is it necessary to give both machines the same network, *and* link them? Wouldn’t just one of them be enough?

**Comment by negativzeroe** [comment]
Removed the link, this is the log from the database,  but every time I restart the containers it nukes the chown I did before. 

```
2020-01-03 16:43:29.353 UTC [29] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Permission denied
2020-01-03 16:43:29.363 UTC [29] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Permission denied
2020-01-03 16:43:29.373 UTC [29] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Permission denied
2020-01-03 16:43:29.383 UTC [29] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Permission denied
2020-01-03 16:43:29.393 UTC [29] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Permission denied
2020-01-03 16:43:29.403 UTC [29] LOG:  using stale statistics instead of current ones because stats collector is not responding
2020-01-03 16:43:29.403 UTC [29] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Permission denied
2020-01-03 16:43:30.736 UTC [1] LOG:  could not open file "postmaster.pid": Permission denied; continuing anyway
2020-01-03 16:43:30.736 UTC [45] LOG:  incomplete startup packet
```

**Comment by negativzeroe** [comment]
Should I be running them as root? I'm just running as admin right now.

**Comment by JC5** [comment]
No that doesn't really matter. But those database container error's I've never seen before. I don't think I can help you with those. Maybe it's something in the volume mapping?

**Comment by c0dewhacker** [comment]
@negativzeroe I had a similar issue, try explicitly setting DB_CONNECTION=pgsql in your environment variables then start the container.

**Comment by negativzeroe** [comment]
That was it @c0dewhacker thanks!

**Comment by KillahB33** [comment]
I am having this issue and already had the connection set as pgsql so that's not it for me.

**Comment by JC5** [comment]
Please open a new issue.
