### ISSUE TITLE
API does not accept Opening-balance transaction type

### ISSUE THREAD

**Issue by batkaevruslan** [firefly-iii/firefly-iii#2948]
**Bug description**
I am running Firefly III version 4.8.2 (api version 0.10.5) and my problem is:
I can not add transaction with type Opening-balance using api. Api docs state that I should pass "opening-balance" as enum value, but in this case I get error "Firefly III cannot validate the account information you submitted." in response. 
I can see in logs of my container:

> [2020-01-03 23:37:01] local.ERROR: AccountValidator::validateSource cannot handle "Opening-balance", so it will always return false.

If I send "opening balance" as type value, I get error:
"The selected transactions.0.type is invalid."

**Steps to reproduce**
Post new transaction
`{
	"transactions":[
	{
                        "type": "opening-balance",
                        "date": "2020-01-03T00:00:00+03:00",
                        "amount": "100.000000000000",
                        "description": "Initial balance for \"TestAccount2\"",
                        "source_type": "Initial balance account",
                        "destination_name": "TestAccount2",
                        "destination_type": "Asset account"
                    }
                    ]}`

**Extra info**

**Bonus points**

**Comment by JC5** [comment]
I'll update the documentation. To create an opening balance, update the account in question.

**Comment by batkaevruslan** [comment]
@JC5 thank you
