### ISSUE TITLE
Import Transactions / "Row # could not be imported. It already exists."

### ISSUE THREAD

**Issue by sadreck** [firefly-iii/firefly-iii#2952]
Hello,

First things first, this looks like an amazing piece of work, kudos!

I am running Firefly III version 4.8.2 and was importing all my bank's historic transactions when I noticed the following issue.

**Description**

Transactions that happen on the same day, same description, and have the same cost are marked as duplicate. For example, if I buy something that costs £10 in the morning and £10 in the evening from the same shop, the second transaction will be marked as duplicate:

> Row #XXX ("SHOP_DESCRIPTION") could not be imported. It already exists.

I understand that there has to be a way to identify unique transactions, but is there a way to bypass this? For example something like:

* Have a checkbox to enable the import of "duplicate" (but not really) records. Or
* Be able to define an extra column as the multiple-unique-index, like the balance field.

> Transaction Date,Transaction Type,Sort Code,Account Number,Transaction Description,Debit Amount,Credit Amount,Balance
01/01/2019,DEB,'00-00-00,12345678,SUPERMARKET,10.00,,1000.00
01/01/2019,DEB,'00-00-00,12345678,SUPERMARKET,10.00,,990.00

**Edit**: I've read https://docs.firefly-iii.org/support/faq#why-cant-i-import-duplicate-transactions but would it be safe to set the "Balance" as the External-ID? As the same balance may appear in the future?

**Comment by JC5** [comment]
Thanks for the compliments! This has been discussed quite often and isn’t going to change in the current version of Firefly III. 

A future, separate release of a new CSV importer tool for Firefly III will allow you to import duplicates like these. You can find the repository under the firefly-iii namespace on GitHub. I’m on my phone so I can’t share it for you. 

As it is please understand that when Firefly III can’t tell the difference between lines it’s not going to import duplicate lines.

**Comment by JC5** [comment]
Oh and yes that would probably work

**Comment by sadreck** [comment]
Thanks for such a quick response!

I did read quite a lot of issues here about the duplicate records but thought to ask anyway in case I missed something. I haven't tried setting the balance as the external ID, as I used the following to add an MD5 hash of each row as a new column, and use that as an External ID.

**One Liner**
`c=0; while read -r line; do ((c++)); if [ "$c" -gt 1 ]; then hash=$(echo -n "$line" | md5sum | awk -F' ' '{ print $1 }'); else hash="Hash"; fi; echo "$line,$hash" >> 2019.new.csv; done < 2019.csv`

**Expanded**
```
c=0
while read -r line;
do
  ((c++))
  if [ "$c" -gt 1 ]; then
    hash=$(echo -n "$line" | md5sum | awk -F' ' '{ print $1 }')
  else
    hash="Hash" # This is for the header.
  fi
  echo "$line,$hash" >> 2019.new.csv
done < 2019.csv
```

This results in the following which does the trick just fine.

```
Transaction Date,Transaction Type,Sort Code,Account Number,Transaction Description,Debit Amount,Credit Amount,Balance,Hash
01/01/2019,DEB,'00-00-00,12345678,SUPERMARKET,10.00,,1000.00,MD5_HASH_OF_ALL_OTHER_FIELDS
01/01/2019,DEB,'00-00-00,12345678,SUPERMARKET,10.00,,990.00,MD5_HASH_OF_ALL_OTHER_FIELDS
```

**Comment by JC5** [comment]
:+1:
