### ISSUE TITLE
What are the database container options?

### ISSUE THREAD

**Issue by daFreeMan** [firefly-iii/firefly-iii#2954]
I am looking at installing Firefly III in a docker.

**Description**
The documentation indicates that to do so, I need a PostgreSQL or MySQL container in which I'll create a database for Firefly III. I've currently got a mariaDB container running, can I use that or are PostreSQL and MySQL the only supported options? 

If I can use mariaDB, do I set the environment variable to `DB_CONNECTION=mariaDB` or is there some other magic string necessary?

Is there a specific database name required/suggested, or do I simply pass whatever name I chose in the `DB_DATABASE=` parameter. 

**Extra info**

**Bonus points**

**Comment by AlexKalopsia** [comment]
Hi,

I have Firefly III currently setup on Docker+MariaDB and reverse proxy. `DB_CONNECTION` should be set to mysql, and the db name is whatever you picked according to your own conventions. 

My current setup:

*Docker Container*

```
docker run -d \
--name=firefly \
-v /volume1/docker/firefly/export:/var/www/firefly-iii/storage/export \
-v /volume1/docker/firefly/upload:/var/www/firefly-iii/storage/upload \
-p 10080:80 \
-e APP_KEY=32charactersstring\
-e DB_HOST=nasip \
-e DB_CONNECTION=mysql \
-e DB_PORT=5432 \
-e DB_DATABASE=dbname\
-e DB_USERNAME=dbusername\
-e DB_PASSWORD=dbpsw\
-e APP_URL=https://firefly.mydomain.com \
-e TRUSTED_PROXIES=** \
jc5x/firefly-iii:latest
```

*nginx config:*

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name firefly.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 128M;
   
    location / {
        include /config/nginx/proxy.conf;
        proxy_cache_bypass                      $http_upgrade;
        proxy_pass http://192.168.1.200:10080;
    }
}
```

**Comment by daFreeMan** [comment]
Thanks for the quick reply, @AlexKalopsia!

Fired it up and working like a charm.

**Comment by AlexKalopsia** [comment]
> 
> 
> Thanks for the quick reply, @AlexKalopsia!
> 
> Fired it up and working like a charm.

Glad it worked out!
