### ISSUE TITLE
Dashboard grid customization

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#2955]
**Description**
I have an ultrawide screen (3440x1440) and the Dashboard becomes almost impossible to navigate because it's split in `col-lg-8` and `col-lg-4`. 

You can see the result here:
https://imgur.com/a/3tKdmkj

I have a super long series of `col-lg-8` one under the other. 
I know that customizing the dashboard could easily go of hand in terms of scope, but it would be nice to be able to at least define the grid size, make sure that other graphs go under the `col-lg-4` account list.

Options could be:
- Allow to use graphs like cards that you can drag around a grid (sounds like tons of work)
- Just define the number of column you want on the dashboard
- Allow to hide graphs you don't care about

**Solution**
Allowing customization would allow to have a much better overview of the graphs and how the different datasets relate to each other. 

**What are alternatives?**
Wallet by CudgetBakers: https://imgur.com/a/OTm1gYR

**Additional context**
I tried 2560x1440 but even in that case there is a ton of wasted space

**Bonus points**
Here's a quick mockup
https://imgur.com/a/JkSyS73
In case taking the fullwidth is too much of a headache, it would still help to go with something like `col-lg-6 offset-lg-3`

**Comment by JC5** [comment]
Sorry, I’m not going to add dashboard customization. It’s too big of a hassle for little gain.

**Comment by AlexKalopsia** [comment]
I thought so. I feel like centering the content rather than stretching to full width would still help a great deal. I could look into it myself but I'm not sure where the styling is built
