### ISSUE TITLE
Reconciliation start date is allowed to be after end date

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#2956]
**Bug description**
I am running Firefly III version 4.8.2.

I noticed that the reconciliation interface allows a start date that takes place after the end date. The transactions shown are still between the two dates, but this seems undesirable. I did not check the output of the reconciliation calculation in this scenario.

**Comment by JC5** [comment]
Thanks for letting me know. Yes, this is possible. I've added some code to make sure that the dates are processed in the correct order. If you switch them around, by accident or on purpose, Firefly III will put them in the right order again.

**Comment by GeorgeHahn** [comment]
Good to know, thanks!
