### ISSUE TITLE
Add button to duplicate rules

### ISSUE THREAD

**Issue by ThinkPadNL** [firefly-iii/firefly-iii#2957]
Is it possible to create a button in the rules overview with which we can duplicate rules? 
It requires quite some clicking to setup a rule, this would save time as i need a few quite similar rules setup.

A good place for the duplicate button would be between the 'edit' pencil and the delete button.

**Comment by JC5** [comment]
What are you trying to accomplish, exactly? The button might not even be necessary.

**Comment by ThinkPadNL** [comment]
I have a few rules like:
**Trigger:**
- Description contains: "Albert Heijn xxxx"
- Description contains: "Albert Heijn xxxx"

**Action:**
- Set budget to 'Boodschappen'
- Set desitination account to 'Albert Heijn'

But i would also like to create this for Lidl, Aldi, Jumbo supermarkets. The rule is almost identical, but only the description and destination account differ. However when i have to create the rule from scratch, more clicking is needed than when copying an existing rule

Also al of my rule are based on 'Description contains' and have action 'Set budget to', so that is why i would like to have the ability to create a rule.

**Comment by JC5** [comment]
I thought it was something like that. Try the [non-strict](https://docs.firefly-iii.org/advanced-concepts/rules) option for your rules.

If you do that, any trigger will trigger the action. You could add all of the descriptions you want: if any of them are a match, the rule will trigger.

That's how I manage AH, Lidl, Coop, Dekamarkt, etc.

**Comment by ThinkPadNL** [comment]
I am already using the non-strict option to match multiple triggers indeed.
However a 'duplicate rule' button would still be nice.

Could you make a screenshot of the rule you use for supermarkets?

**Comment by JC5** [comment]
I never made a screenshot, but my rules aren't that exciting.

A button to duplicate rules will be featured in the new release, and can be tried on the [demo site](https://demo.firefly-iii.org/).

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.
