### ISSUE TITLE
Default Currency

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#2958]
Can we have an API to retrieve default currency? Something like `/api/v1/currencies/default`. Thanks

**Comment by JC5** [comment]
https://api-docs.firefly-iii.org/#/preferences/getPreference

Is that an endpoint you can use? Although I like the idea of "default" being a replacement for whatever your default currency is.

**Comment by emansih** [comment]
I would prefer deprecating `getPreference` end point in favour of using currency endpoint to retrieve default.

**Comment by JC5** [comment]
Fair point, but before that the endpoint it'll have to be :wink:

**Comment by emansih** [comment]
Currently, `getPreference` endpoint doesn't give currency attributes. I suggest that if a new endpoint were to be made, the output should include currency attributes. This gives API consumers an easier time otherwise it would be another API call to get currency attributes.

**Comment by JC5** [comment]
`/api/v1/currencies/default` will work in the next release.
