### ISSUE TITLE
Autocomplete function on Description field does not save all text, only what was typed manually

### ISSUE THREAD

**Issue by victordariovera** [firefly-iii/firefly-iii#2959]
Hi

I noticed that autocomplete function on Description field does not save all text, only what was typed manually. For example, if I start typing "Coff" Fireflyiii recomends old entry called "Coffee at Starbucks", but when I press ENTER and give confirmation to autocomplete and then save, the description field only saves "Coff" and not the full autocompleted text.

I'm using Fireflyiii v.  4.8.0.3

**Comment by JC5** [comment]
That’s a known issue from an old version of Firefly III. I can only suggest you upgrade to the latest version.

**Comment by victordariovera** [comment]
Oh thanks!
