### ISSUE TITLE
Firefly not https, marked as not secure

### ISSUE THREAD

**Issue by staadecker** [firefly-iii/firefly-iii#2961]
I am running Firefly III version 4.8.2

**Description**
I notice that my URL is `http://` and when I try `https://` it says "The site can't be reached". This makes chrome display the following.

![image](https://user-images.githubusercontent.com/13053829/71794706-c622c980-3010-11ea-935d-037807f01bce.png)

How do I fix this? I'm kind of at lost with debugging my network setup. I'm running firefly in a docker container in a Linux Virtual Machine on my windows laptop. 

**Extra info**
Debug information generated at 2020-01-05 23:13:27 America/Toronto for Firefly III version **4.8.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.12 |
| Display errors | Off |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2020-01-31 23:59:59 |
| Session first | 2013-06-30 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
What you need / want is a reverse proxy to handle https for you. That’s how the demo site is managed too. The docker exposes over http and a nginx server in front of it wraps it up in https. 

There’s plenty of guides online on how to configure nginx to do this, and some issues in this repository as well with hints and tips.

**Comment by AlexKalopsia** [comment]
I would advise looking here: https://hub.docker.com/r/linuxserver/letsencrypt

**Comment by staadecker** [comment]
Seems like I need my own domain to do this... :(

**Comment by flopes89** [comment]
Considering

> I'm running firefly in a docker container in a Linux Virtual Machine on my windows laptop.

You don't really need https for this anyway.
