### ISSUE TITLE
Iframe on local network?

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#2962]
Hi, I use Home Assistant and it allows to embed pages within its web panel. I am assuming Firefly is currently blocking iframe for security reasons, but I am wondering if there is any way around it, perhaps allowing iframe on local network?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/blob/master/.env.example#L163

**Comment by AlexKalopsia** [comment]
If I have Firefly running in Docker and I create the .env file, can i only set `DISABLE_FRAME_HEADER` in it, and Firefly will use default values for all the others?

Or I guess I can just remove the container and restarting adding it as `-e` ?

**Comment by JC5** [comment]
Yes and yes :)
