### ISSUE TITLE
Category vs tags

### ISSUE THREAD

**Issue by flopes89** [firefly-iii/firefly-iii#2963]
I am running Firefly III version 4.8.2

**Description**

So I am just starting out with importing all my data from my various banks into firefly in order to classify them and to start building budgets.

However, I'm not quite sure how to go with categories or tags.

What is a category and what is a tag? The only discernable difference to me seems that you can have more than one tag on a transaction but only one category. Other than that, they seem virtually identical.

So then, you whould you ever use categories if they have all the same features as tags but have the problem that you can only have one of them per transaction?

I want to have a concept for classification before I go about running through the thousands of transactions only to see I had something misunderstood...

What am I missing here?

**Comment by ThinkPadNL** [comment]
Have you read https://docs.firefly-iii.org/concepts/categories and https://docs.firefly-iii.org/concepts/tags ?

An example i can think of for my own situation: i can have the category `supermarket` but if i am on vacation i can also visit a supermarket there. That transaction i could add the tag `holiday2020` to for example.

**Comment by flopes89** [comment]
I see, thanks for the links + your insight.

I will go a similar route for now. After all, firefly makes it quite easy to change this up later anyway :-)
