### ISSUE TITLE
Import not creating source accounts

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#2964]
**Bug description**
I am running Firefly III version 4.8.2. Whenever I do an Import, I map the Name column to the Asset Account.

The result is that all the transactions end up showing (no name) instead of the name of the person who transferred the money. 

**Steps to reproduce**

- Create csv with headers. 
- Import
- Map a Name column to Asset Account

**Bonus points**
My CSV looks like this:
https://imgur.com/a/Kn9nnij

Debug information generated at 2020-01-06 17:52:23 UTC for Firefly III version **4.8.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.12 |
| Display errors | Off |
| Session start | 2016-04-20 00:00:00 |
| Session end | 2020-01-06 00:00:00 |
| Session first | 2016-04-20 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
The import will never create asset accounts. I assume you map "James Cole" in your file to an existing asset account in your system? If it doesn't exist, Firefly III won't create it for you. It will fall back to the default asset account you selected during the import and the opposing account, either a revenue or an expense account, will be created or will become "no name".

**Comment by AlexKalopsia** [comment]
Wondering if this could be a feature request then. It was hours of work just editing all the entries, I think it would be super useful if Firefly could generate revenue/expense accounts from the csv file.

**Comment by JC5** [comment]
It can and it will. It just won't create asset accounts. Try linking the name to "opposing account"
