### ISSUE TITLE
Wrong balance on edited revenue account

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#2965]
**Bug description**
I am running Firefly III version 4.8.2, and I have a bunch of imported transactions that show as (no name) as Account source. If I manually edit the entries, then the newly assigned account
shows a balance of 0, despite the transition original details.

**Steps to reproduce**

I have tried my best to reproduce this on the demo website, but I literally cannot manage.

Imported csv

Transfer from: (no name)
To: My Account (Savings)
Amount: 10€

I edit the transaction, and I change the source from (no name) to James Cole
Now I go in the Revenue accounts list, and James Cole will show with Current Balance and Balance Difference set at 0€

**Bonus points**
Here you can see all the steps: https://imgur.com/a/CFpbzjH

**Extra info**
Debug information generated at 2020-01-06 17:52:23 UTC for Firefly III version **4.8.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.12 |
| Display errors | Off |
| Session start | 2016-04-20 00:00:00 |
| Session end | 2020-01-06 00:00:00 |
| Session first | 2016-04-20 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by AlexKalopsia** [comment]
Note that I have just tried first creating the Revenue account, then editing the transaction and assigning it to it, but the problem remains.

**Comment by JC5** [comment]
What does it show, after you browse to /flush? It could be a cache thing.

**Comment by AlexKalopsia** [comment]
Still the same, all my edited entries are all showing 0, 0

**Comment by JC5** [comment]
I see the problem. Had to look closer. The transactions you've created are in Euro's but your default currency is different. The chart will only show the balance in the default currency or the account's currency, if one is set.

**Comment by AlexKalopsia** [comment]
Oh wow, good catch! Wondering if this could be addressed in some way, but it does sound a bit complicated. Ie if I want to sort the biggest sources, but some big ones send money in Euros, then I can't really sort them in the list

**Comment by JC5** [comment]
No, and unfortunately this will remain tricky when dealing with multiple currencies.

**Comment by AlexKalopsia** [comment]
I can totally see that. If Firefly can do some calculation before showing the data (unless everything would be massively slowed down) perhaps it could be an idea to just define a custom change rate vs the default currency?
