### ISSUE TITLE
Description dropdown when editing a rule is unreadable

### ISSUE THREAD

**Issue by ThinkPadNL** [firefly-iii/firefly-iii#2966]
**Bug description**
I am running Firefly III version 4.8.2 and my problem is that when i create or edit a rule and change the description trigger field, it shows me a dropdown that seems to have values but is unreadable. Clicking a 'value' from that list gives me an empty field.

I tested it with multiple browsers (Chrome, Firefox) and the behaviour is consistent.

**Steps to reproduce**
- Create a rule/edit an existing rule that triggers on `Description contains`
- Change the field `Trigger on value`
- A dropdown will appear when you start typing as can be seen on the screenshot

Maybe the problem is related to my imported transactions?

![2020-01-06 21_31_56-Microsoft Edge](https://user-images.githubusercontent.com/12446338/71847339-ef089480-30cc-11ea-8c32-57ecd705f76d.jpg)

**Comment by JC5** [comment]
Could you share (privately if you want) the content of this URL?

https://firefly/json/transaction-journals/all

**Comment by ThinkPadNL** [comment]
Took me a while to strip out sensitive information, here it is: https://pastebin.com/riXDVhqU

**Comment by JC5** [comment]
Thanks. Feel free to delete the file again. It doesn't seem to contain any weird characters, unless you accidentally removed those too. Anything in your console (Ctrl Shift i) when you load the page?

The descriptions are long and messy but that shouldn't be an issue.

**Comment by ThinkPadNL** [comment]
I didn't spotted any weird characters. The only thing i did spot was the `\/` (backward & forward slash) in the description field.

This is in the console when i load the page /rules/edit/9
![2020-01-07 21_34_15-Microsoft Edge](https://user-images.githubusercontent.com/12446338/71927382-a1a42a00-3195-11ea-8e02-1a59d13eba5d.jpg)

**Comment by JC5** [comment]
Thanks for the pointer! Turns out it is a bug in the auto-complete generator. Should be fixed in the next release :+1:
