### ISSUE TITLE
Different RAM usage on two containers?

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#2967]
I have now two instances of Firefly running on my NAS, one for me and one for my partner. 

My account has tons of historical data, while my partner's is completely empty. 

I noticed that my Firefly container uses 176Mb of RAM, while my partner uses 107Mb. MariaDB uses an additional 290Mb of RAM. 

I am curious whether this is normal and if it is connected to the amount of data stored. If that is the case and for instance a lot of data is cached, is there a way to automatically flush other than perhaps setting a cronjob to reach the flush url?

**Comment by JC5** [comment]
You could use another cache backend like Redis (available in the next release) to control the cache.
