### ISSUE TITLE
Piggybank for undefined goal amount

### ISSUE THREAD

**Issue by M-Gregoire** [firefly-iii/firefly-iii#2968]
Hi,

I've been testing out Firefly III (4.8.2) for the past few days, and I have to say: thank you for making such a great open source project!

I have a question concerning budget and piggybanks and whether what I'm trying to do is possible in Firefly III. I'm trying to do something like a budget with the unused amount going over to the next month. I've looked at both issues which looked similar:
- https://github.com/firefly-iii/firefly-iii/issues/2140
- https://github.com/firefly-iii/firefly-iii/issues/246

As you advised, I've also been looking at Piggybank. However, I'm unsure of what would be best for the following scenario:

Let's say I earn 1000€/month. 
- I don't want to spend more than 200€ on food every month: this would be a budget.

- I want to save up money to buy a 300€ camera: this would be a piggybank (Btw, is it possible to automatically had xx€ on the piggybank at certain date? Couldn't find the option in Periodic operations)

- I want to save 200€ per month to buy something which will make me happy. This could be either a 200€ item at the end of the month or a 2400€ item at the end of the year or even a 4800€ item if I'm ready to wait for 2 years. Does Firefly III offer a functionality which could allow to do something like this ?

I hope this makes sense.

**Comment by JC5** [comment]
Firefly III works the other way around. It doesn't matter what you earn every month. What do you want to *spend* every month? If you want to spend 800 euro's every month, you should start your month with 800 euro's in your bank account and the budgets divided up. You can read about it [here](https://docs.firefly-iii.org/about-firefly-iii/grand-theory).

You can automatically make a transfer from your main checking account to your savings account using recurring transactions. Make sure you select "transfer" and also select the correct piggy bank.

**Comment by M-Gregoire** [comment]
I'm sorry for this late answer to a really quick one!

I've read you "Grand theory" and I now understand far better the idea behind Firefly. I get that if I want my budget to be 800 euro's every month, that should be the amount I have on my main account at the beginning of said month. 

However, let's say that in addition to those 800 euros, I want to save 100 euros per month for my vacations and 100 euros per month in case something bad happens to my car. The money I keep aside for my vacations and my car are in the same saving account but when buying my vacations, I don't wanna use the money I save for my car.

To do so, I wanted to create two piggybanks that would be incremented by 100 euros per month and that I would manually decrease whenever I buy myself some holidays or make some repair on my kind. However, as far as I understand, piggybanks are supposed to have a goal with a fixed amount of money, whereas I want to put aside money every month for my vacations independently of how much I already have. 

Is this kind of reasoning wrong in your "Grand Theory" or is there something I'm missing?

Thank you

**Comment by JC5** [comment]
This is entirely correct. Those 200 euro's would not be part of your budgets. Ideally, when you transfer your salary to your savings accounts, you update the piggy banks. You can do it automatically too, when you create recurring transactions.

**Comment by M-Gregoire** [comment]
Thanks again for this blazing fast answer.

Piggybank must have a goal amount and they can't hold more than this goal amount. Do this mean that in order to achieve what I want, I should put a absurdly high amount for this goal so it's never reached?

**Comment by JC5** [comment]
No worries. More or less a coincidence, I was on my pc anyway. 

What about setting it to 1000 and adding another 1000 every now and then? You’ll be able to see it crow. 

I saw your sponsorship btw, thank you very much!!

**Comment by M-Gregoire** [comment]
Thank you, I'll do what you suggested!

Thank you also for spending some of your free time improving Firefly and helping strangers ;)!
