### ISSUE TITLE
Manual execution of specific rule for imported transaction

### ISSUE THREAD

**Issue by Markus-** [firefly-iii/firefly-iii#2971]
I am running Firefly III version 4.8.2

**Description**
I import transactions of my bank using CSV-files. For most of my regular stuff I have rules, which 
 - clear the import category
 - clear all tags
 - link it to a bill
 - add tags
 - set category

This works for regular things. But now I have a transaction like "AMAZON XYZ". 
This can be anything from groceries to technical stuff to sth. else.

Is there a way to apply a rule to a single transaction without trigger / filter?
The idea is, that I create the rules with correct category / tags and then use it as kind of adhoc-rule for a single transaction.

Regards
Markus

**Comment by JC5** [comment]
I don't get it. You would edit the rule to match whatever Amazon brought you, then apply it to the single transaction?

Wouldn't it be easier to just edit the transaction?

**Comment by Markus-** [comment]
But the manual edit of the transaction is much more effort than apply the "adhoc" rule.

Easy example:
- Gas Station transaction -50€
- We have two cars.

Goal:
 - tag import_xyz cleared
 - tags car1 and gas added
 - category set to mobility
 - account set to target_account

If I have prepared rules (in this case two for each car) I just would have apply the specific rule to a transaction.

Regards
Markus

**Comment by JC5** [comment]
Yes but why not use correct triggers? This has nothing to do with your Amazon example.

**Comment by Markus-** [comment]
It does.

You have a transaction where you can't decide by the information given by the transaction itself what tags / category... to put.

Gas Station: Yes one of our cars got new fuel. But this can't be recognized by the description.
Amazon: Amazon got money from me. I can't trigger the correct rule automatically.

**Comment by JC5** [comment]
Ah, I see. 

No, that’s not what the rules are for. Sorry.

**Comment by Markus-** [comment]
Is there any other way to achieve this as easy as possible?

**Comment by JC5** [comment]
Im afraid not.

**Comment by JC5** [comment]
Im afraid not.

**Comment by Markus-** [comment]
Ok. Thanks
