### ISSUE TITLE
Syntax error and 404 after installation

### ISSUE THREAD

**Issue by jrobinson52** [firefly-iii/firefly-iii#2972]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

I receive an error message when trying to reach the login page after a clean installation:
```
Unfortunately, this error was not recoverable. Firefly III broke. The error is:
syntax error, unexpected ')'
```

**Steps to reproduce**
Install firefly III on ubuntu 18.04 with php7.3 and apache and access localhost/firefly-iii/public

**Extra info**
OS: Ubuntu 18.04
PHP: 7.3
Webserver: apache2
Trying to navigate to '/debug' gives a 404
By removing the commas before closing parenthesis on line 117 and 118 in app/Http/Controllers/Controller.php I am able to get past the error but I end up at a 404 page instead of the login page

**Stack Trace**
```
Error

This error occured in file /var/www/html/firefly-iii/app/Http/Controllers/Controller.php on line 58 with code 0.
Stack trace
#0 /var/www/html/firefly-iii/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/f...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('FireflyIII\\Http...')
#2 /var/www/html/firefly-iii/app/Http/Controllers/HomeController.php(42): spl_autoload_call('FireflyIII\\Http...')
#3 /var/www/html/firefly-iii/vendor/composer/ClassLoader.php(444): include('/var/www/html/f...')
#4 /var/www/html/firefly-iii/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/f...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('FireflyIII\\Http...')
#6 [internal function]: spl_autoload_call('FireflyIII\\Http...')
#7 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(788): ReflectionClass->__construct('FireflyIII\\Http...')
#8 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('FireflyIII\\Http...')
#9 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('FireflyIII\\Http...', Array)
#10 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make('FireflyIII\\Http...', Array)
#11 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(233): Illuminate\Foundation\Application->make('FireflyIII\\Http...')
#12 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(833): Illuminate\Routing\Route->getController()
#13 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(794): Illuminate\Routing\Route->controllerMiddleware()
#14 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Routing\Route->gatherMiddleware()
#15 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->gatherRouteMiddleware(Object(Illuminate\Routing\Route))
#16 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#17 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#18 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/html/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/html/firefly-iii/app/Http/Middleware/SecureHeaders.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\Http\Middleware\SecureHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#42 /var/www/html/firefly-iii/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#43 {main}
```

**Comment by jrobinson52** [comment]
**UPDATE**
I am able to resolve the 404 by editing my /etc/apache2/apache2.conf and changing
```
AllowOverride None
```
to 
```
AllowOverride All
```
for the /var/www directory

**Comment by JC5** [comment]
The error you're getting is because Apache is not configured correctly for PHP 7.3.

**Comment by jrobinson52** [comment]
What am I missing? The installation instructions don't mention how to configure apache

**Comment by JC5** [comment]
You can Google how to configure Apache for php 7.3

**Comment by jrobinson52** [comment]
Despite having installed everything correctly, I had to run `update-alternatives --set php /usr/bin/php7.3` as well as `a2dismod php7.2` and `a2enmod php7.3`
That seems to have resolved the issue.

**Comment by d0v1k** [comment]
I'm getting the same error after upgrading to latest version 5.0.0-beta.1..I'm using nginx as my webserver

This is the error:

`Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

syntax error, unexpected ')'

More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.

If you cannot find the cause of this error or when you need some help, please open a ticket on GitHub.`

**Comment by JC5** [comment]
Same cause, different solution. Are you using FPM?

**Comment by d0v1k** [comment]
> I'm getting the same error after upgrading to latest version 5.0.0-beta.1..I'm using nginx as my webserver
> 
> This is the error:
> 
> `Whoops! An error occurred.
> Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> 
> syntax error, unexpected ')'
> 
> More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.
> 
> If you cannot find the cause of this error or when you need some help, please open a ticket on GitHub.`

it works after upgrading to php 7.3.

**Comment by d0v1k** [comment]
> Same cause, different solution. Are you using FPM?

After upgrading to php 7.3 it's loading properly

**Comment by w111a** [comment]
I'm using Unraid 6.8.1 and after installing 5.0.0 (docker) I'm getting the same error. Everything was working well before on 4.8.2. Any fix for us Unraid/docker users?

**Comment by JC5** [comment]
The error happens when you're running PHP 7.2. The official docker images are 7.3.

**Comment by w111a** [comment]
Ok, thanks. I might have misunderstood the cause but I am still getting the "whoops, fatal error" page after the update. I can start my own issue if you would rather, but here is the log after trying to access the page twice. 
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Sat Jan 18 13:14:07.438925 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.13 OpenSSL/1.1.1d configured -- resuming normal operations
[Sat Jan 18 13:14:07.438959 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
10.253.0.2 - - [18/Jan/2020:14:00:12 -0600] "GET / HTTP/1.1" 500 1676 "http://192.168.1.100/Docker" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:00:13 -0600] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:00:13 -0600] "GET /fonts/lato-100.woff HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:01:59 -0600] "GET / HTTP/1.1" 500 1676 "http://192.168.1.100/Docker" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:01:59 -0600] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:01:59 -0600] "GET /fonts/lato-100.woff HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36`

**Comment by JC5** [comment]
Let’s open a new issue for this one. If you would do the honors. :)
