### ISSUE TITLE
Income taken into account in budget calculations?

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#2973]
This I guess it's more of a design question, perhaps you can help me understand what's the best way to handle this situation. 

Say I have 300euros groceries budget per month. 
Quite often I do groceries (ie 100 euros) and then my partner quickly sends me half of that amount. 

The problem here is that my budget left is 200 euros rather than 250. 

Now I think I understand that a budget - by principle - doesn't take into account money that you get back, but in this specific circumstance (which is our stanmdard of living) it's a bit hard to figure out what's the best way to handle the situation.

My current options are:
- Increase the budget of the amount my partner sent me (300 -> 350). Leads to a bunch of inconsistency I think
- Decrease my original spending transaction (sounds like a terrible idea)

How can I approach this situation and what do you suggest doing?

**Comment by JC5** [comment]
Firefly III doesn't do either, on purpose. It really is up to you. Personally, I increase the budget with a reasonable amount (doesn't have to be the exact 12.34 amount that I got back) and transfer the rest away to my savings account.

**Comment by AlexKalopsia** [comment]
Would it be completely out of discussion to allow to connect any form of transaction to a budget? What would be the drawbacks?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2190
https://github.com/firefly-iii/firefly-iii/issues/1599
https://github.com/firefly-iii/firefly-iii/issues/1448
https://github.com/firefly-iii/firefly-iii/issues/1163

**Comment by AlexKalopsia** [comment]
Yeah, I've read those and I totally get the "Income should never influence the budget", but it feels somehow different for refunds. Like, I literally spent 100 euros but got 50 ten minues later. 

Maybe allow specific categories/tags to be taken into account in budget, so that you could have a Refund type? 

I dunno, I see the problem though, thanks for the answer.

**Comment by AlexKalopsia** [comment]
As one last thing, I think that another difference in my case is that I deposit the savings immediately at the beginning of the month (cause I don't trust my spending habits :P) and then I keep track of the budgets with the amount left

**Comment by GaryQ** [comment]
If you're only doing YOUR accounting and you pay only half of that then just make a loan to your partner for the other half and budget half of what you spend after all you didn't spend 100 on groceries you spent 50. Right? How to set up <I lend you, you owe me and pay me later> accounts that's something @JC5  would be more aware of but if you're getting it back faster than you can enter it why bother even entering it?

**Comment by AlexKalopsia** [comment]
Well the main reasonis that I want Firefly transactions to correctly match my bank statements, and my bank statement will just say -100, +50

**Comment by dbuse** [comment]
Maybe a split transaction would do, e.g.:
- total transaction volume for groceries: 100€
- budget "groceries": 50€
- some virtual account tracking what your partner owes you: 50€
