### ISSUE TITLE
Error! Could not add €20.00 to "Piggy Bank". 

### ISSUE THREAD

**Issue by raviolican** [firefly-iii/firefly-iii#2974]
**Bug description**
I am running Firefly III version 5.0 Alpha 2, and my problem is:
I have created a Piggy bank with goal amout 5000 €. 
I want to add 200 Euro. 
When trying to add 200 Euro i get an error Error! Could not add €20.00 to "Notgroschen". 

**Steps to reproduce**
Create a new piggy bank and click the "+" symbol
![add](https://user-images.githubusercontent.com/20302303/71937573-0f0f8500-31ad-11ea-8ab0-52241b59f6aa.PNG)
enter 200 euro
error occurs

**Extra info**

**Bonus points**
Debug information generated at 2020-01-07 23:24:06 UTC for Firefly III version **5.0.0-alpha.2**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.0-alpha.2 |
| FF API version | 1.0.0 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.13 |
| Display errors | Off |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2020-01-31 23:59:59 |
| Session first | 2020-01-07 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, ldap, mbstring, Zend OPcache |

**Comment by JC5** [comment]
Do you have enough balance on the account to which the piggy bank is linked to add that amount?

**Comment by raviolican** [comment]
Yes

**Comment by raviolican** [comment]
Works today after relog, just tested-
