### ISSUE TITLE
Budget Dropdown on Transaction Form is Sorted in Reverse Alphabetical Order

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2976]
I am running Firefly III version 4.8.2

The budget dropdown has the entries sorted in reverse alphabetical order, which leads to strange behavior when I use the keyboard to pick a category.  

I enter information into the form and use TAB to move to the next field.  When I tab over to the budget dropdown, I type the first letter of the budget to select it.  If I type G, I expect "Gas" will be selected.  A second tap of G and "Groceries" should be selected.  With the entries reverse-sorted, the opposite happens.

**Comment by hamfactorial** [comment]
![2020-01-08_082318](https://user-images.githubusercontent.com/39804831/71996515-32f4ba00-31f1-11ea-8ab0-ce96fb869c00.png)

**Comment by JC5** [comment]
Thanks, I’ll check it out.

**Comment by JC5** [comment]
Yep, will be fixed in the next release. But keep in mind the budgets will follow the sorting of the /budgets page, and that doesn't have to be in alphabet.

**Comment by hamfactorial** [comment]
Cheers, thanks!
