### ISSUE TITLE
"Budgeted:" Amount on Budget Page does not update when budgets are adjusted

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#2977]
I am running Firefly III version 4.8.2

When I update a budget with a new value, the "Spent (per day)" and "Left (per day)" are updated, but the "Budgeted:" value remains at the original value.

It is correct after a page refresh, but it would be helpful to update the value in real-time to minimize over-budgeting.

**Comment by JC5** [comment]
I did hope nobody would notice until the next release :grin:.

Not in 5.0.0 but after, it's a complex one. Stay tuned.

**Comment by JC5** [comment]
In the next release of Firefly III, the bar will move :+1:

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.
