### ISSUE TITLE
Demo site - scripts not loading - See pic attached

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#2981]
A picture is worth 1000 words...
There's close to that many words in the pic LOL

<img width="945" alt="Capture" src="https://user-images.githubusercontent.com/3269694/72077403-d4950d80-32bc-11ea-9b72-bd066f32dc41.PNG">

**Comment by JC5** [comment]
Thanks for letting me know, I’ll pick it up.

**Comment by GaryQ** [comment]
Yes please, let me know when it's resolved so I can test something out on the demo site to know if my problem is on my end or in the code before posting another issue.

**Comment by JC5** [comment]
What's your browser and OS?

**Comment by GaryQ** [comment]
sorry... Windows 10 1909  Edge Browser.

**Comment by JC5** [comment]
Weird. Edge should support Content Security Policies. I don't have anything with Edge though, so I can't debug this. If you refresh the page, does it work now?

**Comment by GaryQ** [comment]
Edge does support CSP I think level 2 but there's a violation somewhere in the header and scripts. 

I just tried it  with IE 11 (really bad rendering ouch) It works but I think it's because it  just ignores the headers except it crashes on me trying to submit a transaction which BTW the form displays text budget but no entry field LOL Then when I try to submit the transaction it doesn't save it and redirects me into some foreign language. really weird....

Think it might have something to do with your google entry in the CSP because I got it to run locally from the dev branch before you merged. (But there be bugs and I can't confirm with the demo site)

**Comment by GaryQ** [comment]
I'll reinstall FF later to try the demo site

**Comment by JC5** [comment]
I get no validation errors from various CSP validators. Adding the URL should be no problem.

**Comment by GaryQ** [comment]
Well I just tried it on my iPhone and it works. Will start new thread with the bug I found to segregate issues. Will retry demo on another PC that has a clean install of Win 10 and Edge but only later

**Comment by GaryQ** [comment]
just noticed the commit in the dev branch... looking forward to testing it out on the demo

**Comment by JC5** [comment]
Found the issue. Demo site is updated. Ctrl-F5 should do it.

**Comment by JC5** [comment]
Can't believe CSP validators don't catch that.

**Comment by JC5** [comment]
Crap no that's not right. Back to the drawing board.

**Comment by GaryQ** [comment]
It's working I posted the last edit before. Cleared my cache after I saw you that you posted demo updated. CSP issue seems resolved

**Comment by JC5** [comment]
Glad to hear it! Found a lot of issues with Edge and CSP online. But they fixed those it seems.

**Comment by GaryQ** [comment]
Well ALMOST fixed down to only 4 lines regarding the CSP 

CSP14308: Failed parsing directive in Content-Security-Policy at 'script-src''.

CSP14301: Failed parsing Content-Security-Policy because -2147024809 - policy will be ignored.

CSP14308: Failed parsing directive in Content-Security-Policy at 'script-src''.

CSP14301: Failed parsing Content-Security-Policy because -2147024809 - policy will be ignored.

**Comment by JC5** [comment]
That should be corrected again. Sorry about that.

**Comment by GaryQ** [comment]
Sorry to be the bearer of bad new … did toy change something on the demo site when it refreshed becasue all these are back:
CSP14317: Ignoring 'unsafe-inline' for directive 'script-src' in Content-Security-Policy because nonce or hash value is specified.

CSP14309: Unknown directive 'manifest-src' in Content-Security-Policy - directive will be ignored.

CSP14317: Ignoring 'unsafe-inline' for directive 'script-src' in Content-Security-Policy because nonce or hash value is specified.

CSP14309: Unknown directive 'manifest-src' in Content-Security-Policy - directive will be ignored.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/lib/moment.min.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/ff/moment/en_US.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/jscript/variables?ext=.js&v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/app.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/lib/daterangepicker.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/lib/adminlte/js/adminlte.min.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/lib/accounting.min.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/ff/firefly.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/ff/help.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/lib/Chart.bundle.min.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/lib/chartjs-plugin-annotation.min.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/ff/charts.defaults.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/ff/charts.js?v=5.0.0-beta.1. Resource will be blocked.

CSP14312: Resource violated directive 'script-src 'nonce-I5jQigLQg+p46Uyvgf0qLg==' 'unsafe-inline' www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js' in Content-Security-Policy: https://demo.firefly-iii.org/v1/js/ff/index.js?v=5.0.0-beta.1. Resource will be blocked.

BHX19001: Request to https://www.googletagmanager.com/gtag/js?id=UA-58172398-4 is cancelled by extension EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62.

CSS3121: The media query -ms-viewport has been deprecated.

**Comment by JC5** [comment]
>  CSP14317: Ignoring 'unsafe-inline' for directive 'script-src' in Content-Security-Policy because nonce or hash value is specified.

As per the protocol, so not an issue. It's to provide backwards compatibility.

> CSP14309: Unknown directive 'manifest-src' in Content-Security-Policy - directive will be ignored.

Formally not yet a part of the standard, but it also shouldn't be a problem.

As for all the others, I am reading a lot of stuff about Edge being terrible with CSP headers and I can't debug this at the moment. I'll keep it open but I have no problems dropping support for Edge if it happens to me too.

**Comment by GaryQ** [comment]
No worries, They'll be dropping the old edge for the Chromium fork so that'll probably be a non issue soon since M$ will push their version of the ultimate harvesting tool down our throats soon enough. Time to try FireFox again.

**Comment by JC5** [comment]
I did some final changes a few minutes ago but that's all I can think of to patch this.

**Comment by GaryQ** [comment]
We can leave it open and aside for now and I'll also keep an eye out to see if I can find (more like stumble across) anything that could help. There's so much misinformation on the web to sift through it's insane

**Comment by JC5** [comment]
I'm going to spend my morning in VM's, it seems.

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

I'll update the [FAQ](https://docs.firefly-iii.org/support/faq) with the results.

**Comment by GaryQ** [comment]
Cool! Saves me being the edge debugger now :)

**Comment by JC5** [comment]
https://github.com/firefly-iii/docs/blob/master/new-docs/support/faq.md#im-running-internet-explorer-or-edge-and-nothing-works

Because the main documentation site isn't rendered yet.

**Comment by GaryQ** [comment]
Considering Troy Hunt's reputation which is not refuted anywhere... I stumbled upon this article by him: 

https://www.troyhunt.com/locking-down-your-website-scripts-with-csp-hashes-nonces-and-report-uri/

After reading it and understanding what the nonce means for one and the way Edge is wired the issue is easily fixed by adding the nonce to the CSP header and NOT attached to the script. Of course simplest way for me to understand what he meant was to go to His site (HIBP) and load up the CSP header. 

Here's the main important section of the CSP header I got: (expanded for `readability)
(Go have a read at the article ig you want and then a peek at his ressource requests and CSP headers)

```
default-src 
               'none';
script-src 
                'self' 
                'nonce-8XmXNOa9PEKDcHuKry1f' 
                         www.google-analytics.com 
                         www.google.com 
                         www.gstatic.com 
                         cdnjs.cloudflare.com
                         az416426.vo.msecnd.net 
                         js.stripe.com
                         ajax.cloudflare.com;
style-src 
                'self' 
                'unsafe-inline' 
                cdnjs.cloudflare.com;

```

**Comment by JC5** [comment]
> After reading it and understanding what the nonce means for one and the way Edge is wired the issue is easily fixed by adding the nonce to the CSP header and NOT attached to the script.

That's not what you should do, and it's not what he's doing. Insofar as I can see his scripts are the same as mine. He doesn't offer the backwards compatibility by offering 'unsafe-inline' though, and he didn't add the https part. I can try the latter but not the former.

**Comment by GaryQ** [comment]
I'm no expert and thiings were working ok before the new CSP changes and I understand why someone would need it. I do agree that eliminating inline scripts would be a better security feature for a future release. As usual,. Just trying to help. And, I honestly don't know why on this one since I can disable it (Oh yes, I remember now, it was for accessing the demo site so I could confirm a bug was reproducible there also) 

My database and web server are locked down to LAN access only. There's no way in hell I'm putting my financial info on a server open to the outside world so as far as I'm concerned CSP header isn't really a concern for me neither are inline scripts. Making sure there's no external requests trying to go out from my browser is my only real concern. But we all have different needs and wants. Some want a million features and I am slowly but surely working at trimming down many of them. I have no need for IBANs, foreign languages or currencies or maps and banking import APIs and the list goes on LOL but that's my problerm if I want to trim it down. Same with changing the date order of transactions to "ASC" Like my bank statement.  And I'm hoping that once 5.0.0 is stable I'll have finished my major mods and finally start transitioning from testing/learning/hacking to using it for real!. 

It's been frustrating at times trying to figure how things work but I don't think there's a better project for me to learn with since counting and keeping track of my pennies is an obsession, literally by need and pleasure. I could have written a Windows desktop app but I'm slowly transitioning all my stuff to web based so when I've had enough of MS I can use any OS.

Only thing I'd really love if it was "pre-cooked" is an "all transactions (in/out/transfer) combined and ordered by date "ASC" table" as I do in excel month by month. (That one is on my WISH or TODO list) 

Cheers Mate :)
