### ISSUE TITLE
Difference in monthly and yearly report

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2984]
There is a (huge) difference in my yearly and monthly report for January 2019.

![2020-01-10_11h42_43](https://user-images.githubusercontent.com/1318140/72153769-17cfa900-33af-11ea-8776-1e83352cb442.png)
![2020-01-10_11h42_51](https://user-images.githubusercontent.com/1318140/72153773-1900d600-33af-11ea-9437-cc1df69cb987.png)

Every other month seems to be ok.

Ps: I started using firefly last year so the database might be in a weird state due to me learning to use firefly...

Any idea how to fix this?

**Comment by JC5** [comment]
It could be that the opening balance that you've set skews the charts. Did you set an opening balance on your asset accounts?

**Comment by jlauwers** [comment]
Yeah, I have opening balance on my accounts. But shouldn't that tip the
balance in the positive rather than negative?

Le ven. 10 janv. 2020 à 17:14, James Cole <notifications@github.com> a
écrit :

**Comment by GaryQ** [comment]
Isn't this the same as the problem I had? Is your opening balance date Jan 1, 2019 by any chance?
If yes try editing all accounts with an opening balance to Dec, 31, 2018. Worked for me...

**Comment by GaryQ** [comment]
Here's what I mean : bank account created Jan 1, 2019 with opening balance same day

![snip2](https://user-images.githubusercontent.com/3269694/72198603-98b19380-33f5-11ea-9415-d0aff0be37e1.jpg)

changed opening balance to Dec 31, 2018 and .... tada....

![snip1](https://user-images.githubusercontent.com/3269694/72198599-820b3c80-33f5-11ea-9e17-a4328263a3b7.jpg)
