### ISSUE TITLE
Can't add new transactions

### ISSUE THREAD

**Issue by DopingAnt** [firefly-iii/firefly-iii#2986]
First of all I really like this software in combination with the app from emansih. I tried different alternatives as GNUCash and YNAB but this one stands out in functionality, design philosophy and transparency. 

Since I somehow broke Firefly III 2 time already (couldn't load my data / couldn't new one) I gave it a third try. Sadly now after adding all data off the past 4 months into my free heroku instance I suddenly can't add new ones.

**How to reproduce (somehow)**
1. Create a free heroku account and initialize a Firefly III instance
2. Set everything up - Currency Euro and Language German
3. Import data from a .csv-File from your bank
4. Add some data manually
... some days passed ...
5. Try to add a new transactions with all familiar accounts

**Expected behavior**

- Windows closes and the transaction is logged

**Actual behavior**

- an error message stops me from finishing this entry (see screenshot)
![image](https://user-images.githubusercontent.com/59561980/72203151-7b69dd00-3468-11ea-9af7-3860d4025751.png)

- The console tells me:

-  Error in transaction submission. app.js:1:440505

    submit https://a _[...]_ .herokuapp.com/v1/js/app.js?v=4.8.0.3:1

- Error: "Request failed with status code 500"

    exports https://a _[...]_ .herokuapp.com/v1/js/app.js?v=4.8.0.3:1
    exports https://a _[...]_ .herokuapp.com/v1/js/app.js?v=4.8.0.3:1
    onreadystatechange https://a _[...]_ .herokuapp.com/v1/js/app.js?v=4.8.0.3:1
app.js:1:440555
    submit https://a _[...]_ .herokuapp.com/v1/js/app.js?v=4.8.0.3:1

**Environment**

Firefly III 4.8.0.3 on Heroku Free Account (0 of 20 Connections, 2,898 of 10,000 Rows In compliance ,12.0 MB Data Size, 57 Tables)
Firefox 72.0.1 with all addons disabled for that page (Except YouTube Enhancer) on Windows 10.0.17763 Build 17763

**Comment by JC5** [comment]
It happens when the instance is stopped or falls asleep, the ephemeral storage deletes the key files you need.

There is no user interface command for this but if you have any kind of command line access, you could try this: `php artisan firefly-iii:restore-oauth-keys`.

**Comment by DopingAnt** [comment]
Hi James, thanks for the fast response.

Using the Heruko Console I recieved the following as a response

> [2020-01-12 10:06:46] heroku.ERROR: Command "firefly-iii:restore-oauth-keys" is not defined.
> 
> Did you mean one of these?
>     firefly-iii:account-currencies
>     firefly-iii:apply-rules
>     firefly-iii:back-to-journals
>     firefly-iii:bills-to-rules
>     firefly-iii:bl-currency
>     firefly-iii:cc-liabilities
>     firefly-iii:correct-database
>     firefly-iii:create-access-tokens
>     firefly-iii:create-link-types
>     firefly-iii:cron
>     firefly-iii:csv-import
>     firefly-iii:decrypt-all
>     firefly-iii:delete-empty-groups
>     firefly-iii:delete-empty-journals
>     firefly-iii:delete-orphaned-transactions
>     firefly-iii:delete-zero-amount
>     firefly-iii:enable-currencies
>     firefly-iii:fix-account-types
>     firefly-iii:fix-ob-currencies
>     firefly-iii:fix-piggies
>     firefly-iii:fix-transfer-budgets
>     firefly-iii:fix-uneven-amount
>     firefly-iii:migrate-attachments
>     firefly-iii:migrate-notes
>     firefly-iii:migrate-to-groups
>     firefly-iii:other-currencies
>     firefly-iii:remove-bills
>     firefly-iii:rename-account-meta
>     firefly-iii:rename-meta-fields
>     firefly-iii:report-empty-objects
>     firefly-iii:report-integrity
>     firefly-iii:report-sum
>     firefly-iii:transaction-identifiers
>     firefly-iii:transfer-currencies
>     firefly-iii:upgrade-database {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"firefly-iii:restore-oauth-keys\" is not defined.

May it be missing the command since my version is 4.8.0.3 not 4.8.2? I am not aware of a possibility to update my instance in Heroku.

**Comment by JC5** [comment]
Nor am I, I have to admit I'm not that versed in Heroku. But yes, you'd need a newer version. 

If it's possible, can you launch a new Heroku instance on the same DB? Make sure you have a backup, of course.
