### ISSUE TITLE
Cant create revenue account if expense account already exists

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#2987]
However, this should be possible. Reported by user, not yet researched.

**Comment by hoschi** [comment]
Is this fixed in v5 beta? I'm confused, because the issue is open but has label "fixed" :confused:

**Comment by JC5** [comment]
It's fixed but not yet released. Once the new release is out (beta or otherwise) the issue will be closed.

**Comment by hoschi** [comment]
Ok, thanks for the explanation 🙂

James Cole <notifications@github.com> schrieb am So., 12. Jan. 2020, 13:21:
