### ISSUE TITLE
Collect telemetry, opt-in to send them to me

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#2988]
I want to know what people do. See below for what I want to make.

- Opt-in, not opt-out (of course)
- No financial data (of course)
- A few options: do nothing (default), collect but don't send, collect and send.
- Optional button "send statistics"
- Button: "view statistics" download what will be sent.

What I want to know:

- Features used: which reports, which tools (bills, piggies, budgets).
- Advanced features: budget limits, budgeted amounts, rules, reports except default report, having both strict and non-strict rules, using command line arguments.
- Configuration: LDAP, edge-case config settings.

To collect:

- For all features (a list to be collected): Is a feature-page visited for the first time yes/no? Is a feature object (bill, rule) ever creates yes/no? For advanced features: same thing.
- Probably a key-value thing. Mostly true/false: 'has-visited-bills', 'has-created-bill', 'has-active-bills'.

In time perhaps, usage over a period of time: you configure rules once and never go back? Or are you tuning constantly? Is the audit report useful? Or once and never again.

I could use your input as well, let me know what you think. Let me repeat that everything is optional, opt-in, and as privacy-friendly as I can make it.

**Comment by emansih** [comment]
are you planning to use google analytics?

**Comment by emansih** [comment]
I propose that Matomo be used. maybe google analytics can be stripped out from the demo site too.

**Comment by JC5** [comment]
No, I wasn't planning on using GA. They collect way too much data. Maybe Matomo is overkill as well. I don't know if they offer the granularity I'm looking for. I don't need (the potential for) screen-interaction, I don't need (the potential for) form analytics.

I just want to know how many people, if any, use feature X. In the past, I've broken many features where *nobody* complained. That's what I'd like to know, nothing more.

For the demo site, I couldn't care less.

**Comment by iwalucas** [comment]
I think its very useful, so we (kindly including ourselves here) can focus our efforts.

**Comment by emansih** [comment]
Would that mean we will have 2 analytics engine in Firefly now?

**Comment by JC5** [comment]
Possible, yes. I want to be absolutely sure that a third party analytics engine doesn't collect financial content / page content. If that's the case and Matomo fits, it might replace GA on the demo site.

My own analytics requirements are very basic. I am also happy with a design pattern and a JSON file I design myself, to be uploaded once every month or something.

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live. No telemetry is present.
