### ISSUE TITLE
Can I split a withdrawal, so it uses two asset accounts?

### ISSUE THREAD

**Issue by Nijin22** [firefly-iii/firefly-iii#2989]
Hi,

I have the following use case: I'd like to pay for my lunch (9€) with both a lunch-coupon (6€) and cash (3€). I get a set of these lunch coupons every month from my employer, so I've set them up as their own asset account. The cash in my wallet is also a asset account.

Is it possible to split my withdrawal "buy lunch" so it uses both asset accounts as a "source" for the transaction? Right now it seems the second split's source account field gets disabled when I fill the first split's target account.

I am running Firefly III version 4.8.2

## Workaround
I can create a transfer to get the 6€ from my lunch-coupon account to the cash account and then immediately spend the 9€ from there. But it would look nicer if that happens in the same transaction :)

**Comment by GaryQ** [comment]
That would be a good option to add, 
Sometimes I pay part of a transaction with my credit card rewards and the rest with the card.

**Comment by JC5** [comment]
No, it won't be a possibility to do this. You could add the coupon as a deposit but rather, just subtract it from the original expense.

**Comment by Nijin22** [comment]
Alright, In that case I'll stick to adding a transfer beforehand! (Subtracting the amount of the coupon would mean that all my lunch and some groceries appear cheaper than the actually are.)

Thanks for the great software!
