### ISSUE TITLE
Bills - Fortnightly repeat option

### ISSUE THREAD

**Issue by c0dewhacker** [firefly-iii/firefly-iii#2991]
**Description**

If possible, i'd like the addition of an additional "repeats" time period of fortnightly.

Not much more to the request. :)

thanks! great application!

**Comment by JC5** [comment]
That's every two weeks right? Just select weekly, set it to skip 1.

**Comment by c0dewhacker** [comment]
Oh awesome. Perfect. Didn't see the skip option. Cheers.

Can close off this question
