### ISSUE TITLE
Adding bank Argenta (Belgium)

### ISSUE THREAD

**Issue by Juje** [firefly-iii/firefly-iii#2992]
**Question**
--
I'm not 100% sure where to post this but I would like to ask to add Argenta as a bank option for importing data into FireFly III.

**Bank information**
---
**Name:** Argenta
**Site:** https://www.argenta.be
**Export file:** XLSX but can be converted into CSV
**Mapping:**
```json
{
    "file-type": "csv",
    "date-format": "d-m-Y",
    "has-headers": true,
    "delimiter": ",",
    "apply-rules": true,
    "specifics": [],
    "import-account": 1,
    "column-count": 11,
    "column-roles": [
        "account-iban",
        "date-book",
        "date-invoice",
        "external-id",
        "description",
        "amount",
        "currency-code",
        "date-transaction",
        "opposing-iban",
        "opposing-name",
        "note"
    ],
    "column-do-mapping": [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
    ]
}
```
I used this to import into FireFly III and it worked like expected. But I wasn't sure though about the "Value date (Valutadatum)" so I added it to the `date-invoice` column.

If you have any questions then ask me :wink:.

Thanks in advance.

**Comment by JC5** [comment]
You can create a pull request in [this repository](http://github.com/firefly-iii/import-configurations) to add it :)

**Comment by Juje** [comment]
Ow apparently it was already added here:
https://github.com/firefly-iii/import-configurations/blob/master/be/argenta/default.json

But apparently he chose to ignore the external-id :thinking:.

**Comment by JC5** [comment]
You can also correct him of course :)

**Comment by Juje** [comment]
Pull request has been created so this issue can be closed.
