### ISSUE TITLE
How to resolve Missing-locale-packages on Heroku?

### ISSUE THREAD

**Issue by ckc** [firefly-iii/firefly-iii#2993]
I am running Firefly III version 5.0.0-beta.1.

**Description**
https://github.com/firefly-iii/help/wiki/Missing-locale-packages
The above mentioned commands cannot ran in the terminal of heroku
Is there any solution? Thanks

**Extra info**
 

**Bonus points**

- [ ] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files (see https://bit.ly/FF3-get-logs)
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Which language specifically?

**Comment by ckc** [comment]
> Which language specifically?

Chinese

And now wrongly to show decimal point 7993.11 to 799311

**Comment by JC5** [comment]
I can try to fix those in the new release, but support for Chinese in Heroku is patchy.

You can correct the currency yourself under the /currencies page. Future releases of Firefly III will include the change.

**Comment by ckc** [comment]
Yea, I changed the currency, I think is it two issue?
The another is amount decimal point, I set the initial amount is 7993.11 
![image](https://user-images.githubusercontent.com/4257872/72296933-c4eb3f80-3695-11ea-88ce-19d351df8441.png)

but it shows 799311
![image](https://user-images.githubusercontent.com/4257872/72297020-f19f5700-3695-11ea-99d9-ef6ab0d9bdf1.png)

Confirmed setting is correct

![image](https://user-images.githubusercontent.com/4257872/72297093-18f62400-3696-11ea-98e8-1a16bcbb78bb.png)


Thanks

**Comment by JC5** [comment]
That’s caused by the missing packages. In the past, Heroku didn’t support Chinese.
