### ISSUE TITLE
recurring transaction cron from host

### ISSUE THREAD

**Issue by cowbe0x004** [firefly-iii/firefly-iii#2995]
**Bug description**
I am running Firefly III version 4.8.2 inside docker, trying to set up cron from the docs. When I add this to the host crontab,

`0 3 * * * docker exec <container> sudo -u www-data /usr/local/bin/php /var/www/firefly-iii/artisan firefly-iii:cron`

I get error like this,

`Jan 12 14:55:01 HOST dockerd[434]: time="2020-01-12T14:55:01.960332680-05:00" level=error msg="Error running exec 9549b6492ce63927d93cc0080723725663aa0b573968cd8a7baa29f06080b075 in container: OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused \"exec: \\\"sudo\\\": executable file not found in $PATH\": unknown"`

There's no sudo from the docker image, I used "jc5x/firefly-iii:latest" in docker-compose. If I remove sudo -u www-data, the cron will finish without error. Is that going to cause problem if I don't sudo?

**Steps to reproduce**
Let crontab run.

**Comment by JC5** [comment]
It looks like I updated the docs too soon. But no matter, running it without sudo will only give you slight problems. It could be that you get cache errors down the line. Those can be fixed too of course but it’s something to remember.

**Comment by cowbe0x004** [comment]
Thank you. I will report back if there's any problem.
