### ISSUE TITLE
Number of imported transactions depends on import-tag?

### ISSUE THREAD

**Issue by Markus-** [firefly-iii/firefly-iii#2996]
I am running Firefly III version 4.8.2

**Description**
When I import transactions by using CSV-Import and use rules to modify them during imports it seems to be that if I remove the import tag the number of imported transactions depends on this flag.

I imported 28 transactions and removed the import tag on 19 of them. The shown number of imported transactions is 9 - despite the 19 transactions were imported correctly.

Works as designed?

Regards
Markus

**Comment by JC5** [comment]
Yes. The import routine simply counts the number of transactions under the tag. If a rule removes it, it's not going to be counted. Future import routines will count in a different manner, so this will stop to be an issue in the future :)

**Comment by Markus-** [comment]
Ah Ok. Thanks for the info.
