### ISSUE TITLE
Add categories column on tag's transactions page

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2997]
**Description**
I would like to see the categories on the TAG page. After I make a huge import, I need to know which transactions to update the category field.

**Solution**
Adding the categories will enable to see all the missing categories at once

**What are alternatives?**
Use the search feature to search for that particular tag, that will show the category column

**Comment by JC5** [comment]
Yes, I'll see if that can be added.

**Comment by JC5** [comment]
Category column is now present :)

**Comment by iwalucas** [comment]
@JC5 thanks!!!

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.
