### ISSUE TITLE
Front page category should include income

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#2999]
Currently it doesn’t.

**Comment by GaryQ** [comment]
Maybe the project maintainer will be in a good mood and do something about your request ????

**Comment by JC5** [comment]
Idk he’s a pretty grumpy dictator.

**Comment by JC5** [comment]
Chart will be present in the new release.

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.
