### ISSUE TITLE
Restart takes very long with high IO because of "chown/chmod storage"

### ISSUE THREAD

**Issue by kevinkk525** [firefly-iii/firefly-iii#3000]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

**Steps to reproduce**

Restart firefly
Watch the logs
Chown and Chmod firefly storage directory takes very long and causes 100% IOWait on drive. This is a very heavy load on the server on startup and seems unneccessary since the directory shouldn't change (and in my case is inside the docker container). Only the upload and export directories could have changed permissions since those are mounted to the container. Chown/chmod those would not take long.

**Extra info**

**Bonus points**

**Comment by JC5** [comment]
This has to do with an issue with several commands from the Laravel framework that supports Firefly III. When fired from the command line, or when using “docker exec” these commands get executed as root. This in turn breaks the cache (located in the storage directory) which in turn leads to “permission denied” errors. 

The current docker image doesn’t feature the sudo command. The new version’s image will. Once that’s in place the chown command may be removed or made optional.

**Comment by kevinkk525** [comment]
ok thanks. Looking forward to the new version.
