### ISSUE TITLE
Store import configurations files

### ISSUE THREAD

**Issue by ccantet** [firefly-iii/firefly-iii#3001]
**Description**
It will be nice to keep an history of previous import configurations files and suggest a list of these configuration files on the importation page.

**Solution**
Store in database configuration files defined during import.

**What are alternatives?**
Currently it's necessary to keep these files in local to reimport them later. 

**Additional context**
Nothing

**Bonus points**
I am a Laravel developer, I can develop it :+1:

**Comment by GaryQ** [comment]
I though import was being removed from the actual core and will/to be executed via another app through the API usage. So, creating and actual external import app/ addon etc would be a great place for a start to implement this

**Comment by JC5** [comment]
My personal preference for the new import routine is to make it as basic as possible. In the current version (which will become 1.0.0) this won't be possible. 

I want to avoid having to set up a database connection, making this tool independent from Firefly III itself. And as easy as possible. So perhaps a directory where import configurations can be stored, read and loaded by the CSV importer. That way you can store your import configs there, edit and update them using your own preferred tools and load them when you import files.

**Comment by GaryQ** [comment]
ah! izwat I tawt,  tanks 👍 

Now I can add my cc limits :)

**Comment by JC5** [comment]
Wrong issue I think :wink:

**Comment by ccantet** [comment]
Ok I did not see your post on patreon (https://www.patreon.com/posts/future-updates-30012174) which explain this futur change.

So I suppose it's better to wait a stable (beta at least) version of this new tool before to start to develop anything ? (like this feature)

**Comment by JC5** [comment]
The latest `develop` image is now capable of doing this. Instructions are here.

https://firefly-iii.gitbook.io/firefly-iii-csv-importer/importing-data/upload

Let me know if this works, I'll release the new version officially and mention it in the changelog.

**Comment by ccantet** [comment]
Hello, perfect !

But except if I did a mistake, it's not working for me. The input to select file configuration is never displayed, I think that the configuration file is never put in the store.

**Comment by JC5** [comment]
You'll have to put it there yourself. :)

**Comment by ccantet** [comment]
Ok, I see !

I think it coud be a good idea to give the possiblity to store this file after an import, like we have possibility to download it.

Anyway, it's working  for me.

**Comment by JC5** [comment]
Absolutely. Next version 👍
