### ISSUE TITLE
Virtual balance

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3002]
I looked on the demo site and could not find any info as to what the heck a virtual balance is and what kind of scenario would it be used in?
An actual example wold be much appreciated :)
TIA

**Comment by JC5** [comment]
https://github.com/firefly-iii/help/blob/master/en_US/accounts.create.md

**Comment by GaryQ** [comment]
ah! izwat I tawt, tanks 👍
Now I can add my cc limits :)

NOTE: I wonder how GITHUB managed to put this response into the wrong issue thread ;)
