### ISSUE TITLE
Transactions table is not responsive on mobile

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#3003]
![firefly-III_mobile_transactions](https://user-images.githubusercontent.com/226712/72442548-c9127c80-37bd-11ea-988a-75cfa35f4ee6.jpg)

(From https://demo.firefly-iii.org/transactions/withdrawal)

Version: Firefly III 5.0.0-beta.1

Some places I can see it:
* Account Detail > Transactions
* Transactions
* Search

(Not sure if this can be fixed by a `<div class="table-responsive">` [🔗](https://mdbootstrap.com/docs/jquery/tables/responsive/) :))

**Comment by JC5** [comment]
Thanks for the heads-up, i'll see what I can change to make the table look a bit better.

**Comment by erdmenchen** [comment]
Also the interaction buttons column is missing on the accounts sub list views...
E.g. you cannot reconcile an account on the responsive (mobile) view layout.

**Comment by JC5** [comment]
You can still do that from the account itself I believe. The tables will look better in the next release. :+1:

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.
