### ISSUE TITLE
Contracts table not calculating next occurrence

### ISSUE THREAD

**Issue by JeroenED** [firefly-iii/firefly-iii#3005]
Currently when viewing the bills table the field for next occurrence is showing the litteral value given during setup of the contract.
I am running Firefly III version 5.0.0B1 and my problem is: the next occurence and next expectation is not correct

**Steps to reproduce**
Having paid contracts for any period in view

**Extra info**
Browser: Chome mobile on tablet
Php:
```
$ php -v
PHP 7.3.12-1+ubuntu18.04.1+deb.sury.org+1
```
**Bonus points**
![Screenshot_20200117-000608_Chrome](https://user-images.githubusercontent.com/6833806/72570607-a9627d80-38bd-11ea-86d2-c00849545b56.jpg)

Don't tell my boss I wanted bonus points 😁

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2983

Secret bonus points it is then 😁
