### ISSUE TITLE
Cant login using LDAP and custom objectClass

### ISSUE THREAD

**Issue by tikoflano** [firefly-iii/firefly-iii#3008]
**Bug description**
I am running Firefly III version 4.8.2 on docker and my problem is:

Can't login using my LDAP credentials because the query that my OpenLDAP service gets is in the form:

`(&(objectClass=inetOrgPerson)(objectClass=person)(uid=*)(cn=[MYUSERNAME]))`

It assumes that my users have objectClass _inetOrgPerson_ and _person_ which is not always the case. Many times it is, so it is ok to have it as default values, but not ok to force it to be that way. In my case it is a custom objectClass called _hSuiteUser_.

**Possible solution**
The way most apps handle this is either (or both):

1. Allow the user to define the _filter_ used in the query. In this case this filter is hardcoded to _(&(objectClass=inetOrgPerson)(objectClass=person)(uid=*)(cn=%username))_. This filter must include a plcaehodler (_%username_ in this case) which will be replaced by the username.
2. Define a base DN from where start searching the users, something like _ou=users,dc=example,dc=com_

**Comment by tikoflano** [comment]
I realized that:

1. The library you are using needs the schema defined in a Class.  See: https://github.com/Adldap2/Adldap2-Laravel/issues/489 . Will be tricky, but possible, to add a custom class whick can override all values using environment variables.
2. There is also a way to use a custom query, but I'm not sure how to implement it here. See https://github.com/Adldap2/Adldap2/issues/42
3. The base DN was already covered by `ADLDAP_BASEDN`

I have created a custom schema, overriding just what I needed form OpenLDAP schema. My LDAP logs shows that the query is working:

`SRCH base="ou=Users,dc=tikoflano,dc=com" scope=2 deref=0 filter="(&(objectClass=hSuiteUser)(objectClass=top)(cn=*)(cn=demouser))"`
`SEARCH RESULT tag=101 err=0 nentries=1 text=`

But now, when it uses the _cn_ to authenticate it is ignoring the `ADLDAP_BASEDN` variable, here is what it shows on the logs:

`BIND dn="cn=demouser,dc=example,dc=com" method=12` ... note how the _ou=Users_ is missing

**Comment by JC5** [comment]
This is something you'll have to pick up with the LDAP library developer.

**Comment by tikoflano** [comment]
I had to do the following things in order to make it work (using Docker):

1. Create an Schema file extending the OpenLDAP one and overriding the functions needed and `chown` it to 33:33. Here is my schema:
```
<?php

namespace Adldap\Schemas;

use Adldap\Schemas\OpenLDAP;

class mySchema extends OpenLDAP
{
    /**
     * {@inheritdoc}
     */
    public function objectClassPerson()
    {
        return 'customclass';
    }

    /**
     * {@inheritdoc}
     */
    public function objectClassUser()
    {
        return 'customclass';
    }

    /**
     * {@inheritdoc}
     */
    public function objectCategoryPerson()
    {
        return 'top';
    }

    /**
     * {@inheritdoc}
     */
    public function userId()
    {
        return 'cn';
    }

}
```

2. Mount that file at `/var/www/firefly-iii/vendor/adldap2/adldap2/src/Schemas/mySchema.php`
3. Override the image entrypoint to replace the config file before calling the default entrypoint. Using `sed -i 's/=> $schema/=> \\Adldap\\Schemas\\mySchema::class/' /var/www/firefly-iii/config/ldap.php`
4. Set `ADLDAP_ACCOUNT_PREFIX=cn=` and `ADLDAP_ACCOUNT_SUFFIX=,ou=Users,dc=example,dc=com` in order to fix the bind call to the LDAP server.

Hope this helps you or anyone facing similar issues.
