### ISSUE TITLE
Sign in page does not display translation, still English even if it has been translated on Crowdin

### ISSUE THREAD

**Issue by FanyangMengDev** [firefly-iii/firefly-iii#3009]
**Bug description**
I am running Firefly III version 5.0.0, and my problem is:

I choose the Chiense Simplified to be the default language but it does not display on the sign in page.

This happens sice version 4 when I first use. At first I thought maybe you just did not set the translatioon on this page. But today when I finnaly wanna change it to Chinese by modifying /resource/lang/zh_CN/firefly.php , I saw that it has already been translated on both local file and Crowdin. Then I realize that this is a translation bug.

Please fix it. It will be so much appreciated.

**Steps to reproduce**
1. Change it to Chinese Simplified

2. Log out

3. See the log in page. Just still display in English.

**Extra info**

![doesnotdisplaytranslation](https://user-images.githubusercontent.com/53750381/72660586-c35da680-3a0a-11ea-9924-ddf707b87156.PNG)
![homepage](https://user-images.githubusercontent.com/53750381/72660594-dcfeee00-3a0a-11ea-9299-4306815e497b.PNG)

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
That page can't be translated, because you're not yet logged in. Sorry about that.

**Comment by FanyangMengDev** [comment]
Thank you for your fast response James.

I see now.

**Comment by FanyangMengDev** [comment]
Maybe you can make the log in page's language same as the Browser's language?

You just need to add some code to get the user agent

**Comment by FanyangMengDev** [comment]
hello?

**Comment by JC5** [comment]
I am not always here ;-). I have something in mind, should be ready for the next release

**Comment by FanyangMengDev** [comment]
Sounds great. Thank you for your reply~
Hoping to the next version

**Comment by JC5** [comment]
In a future version of Firefly III, I expect 5.1.0, you can set DEFAULT_LANGUAGE to "zh_CN" or "zh_TW" (not sure what you prefer).

This will make the login screen Chinese and new users will be offered this language first.

**Comment by FanyangMengDev** [comment]
That is really great!

Thank you for your hard working again!
