### ISSUE TITLE
Change deposit to transfer from loan account

### ISSUE THREAD

**Issue by eraelpeha** [firefly-iii/firefly-iii#3010]
**Current situation**
I am importing transactions for an asset account. There are some transactions, which is money from loans or mortgages. I tried to change the deposit transaction to a transfer, but I could not change the source-account to any loan, only to the default assets (like saving accounts).

**Solution**
Add loans to dropdown-list in change to transfer window.

**Question**
Or is this something that is not on the list because of some behaviours I don't have in my mind yet?

**Comment by JC5** [comment]
You would have to convert it into a withdrawal. The list of transaction types is currently only on Patreon, but I'll put it in the documentation as well: https://www.patreon.com/posts/updated-types-26635121

**Comment by JC5** [comment]
https://docs.firefly-iii.org/support/transaction_types
