### ISSUE TITLE
The Reconciliation page could be a little more forgiving 

### ISSUE THREAD

**Issue by Tavlor** [firefly-iii/firefly-iii#3011]
I love the reconcile feature - it helps me catch transactions I forgot to record. This happens at least a few times during my monthly statement review, and that usually means refreshing the page to see freshly-added transactions. I wish the reconcile page would refresh listed transactions without clearing my check marks or changing the ending balance. I'm envisioning a "refresh" button somewhere on the page.

**Comment by JC5** [comment]
That's gonna be tricky, but I'll see what I can do.

**Comment by GeorgeHahn** [comment]
I've had this issue as well - the checkboxes can be a chore when refreshing the page or tweaking the dates (also when I've visually checked transactions without clicking boxes as I went).

Maybe there's an option for this UI that would serve better than checkboxes? A checkbox style with a larger click area would make going through these a bit easier. Locally preserved state would be a really nice improvement on top of that. A check-all button may help in the meantime or for edge cases where the state has been cleared bu the transactions are known-good.

**Comment by daniva6** [comment]
I would love a "select all" button in the Reconciliation page.

**Comment by JC5** [comment]
I've added some improvements:

- Checkboxes will be remembered even if you change the date or refresh the page.
- There's a "check all" button top and bottom.

Should make things a lot easier.

**Comment by Tavlor** [comment]
I'm on 5.2.5 and I'm happy to report that my selected dates and account balances stuck around after a refresh. I tried the checkbox memory on the demo page and it works like a charm! Thanks!

**Comment by Tavlor** [comment]
Used the reconciliation feature again today - it's working perfectly!
