### ISSUE TITLE
Account view in dashboard should convert all currencies to the default one

### ISSUE THREAD

**Issue by Kwbmm** [firefly-iii/firefly-iii#3012]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is:

When dealing with multi-currency bank accounts, account view in the dashboard doesn't handle it quite well. In fact, everything is displayed in the default currency:
![2020-01-18-214311_424x311_scrot](https://user-images.githubusercontent.com/8115374/72670274-fc623f00-3a3b-11ea-94fa-d9553ab0437c.png)

The green line at the top is a bank account in a currency that is 8 times the default currency (used by the other 2 bank accounts - blue and orange). This basically make useless the view because it's quite hard to see the flow of blue and orange accounts.

**For example:** the orange account is the one with the highest number of transactions. Looks like nothing is happening.

**Solution:**
The chart should show each bank account in the default currency: accounts not in the default currency should have the amount converted

**Comment by JC5** [comment]
Thanks for the suggestion. This isn't something I'm going to fix. Currency conversions are always very inaccurate. You can remove the green account from the front page in your preferences to make the view more clear.
