### ISSUE TITLE
Creating bills and rules from transaction as template

### ISSUE THREAD

**Issue by h3po** [firefly-iii/firefly-iii#3013]
It would be useful to have a link next to transactions (e.g. in the expense account view) that opens the "New Bill" workflow and pre-fills the amounts and rule filters accordingly, e.g. with a "Destination account is..." filter matching the transaction. This would make it easy to create rules from imported bank statements to simplify future imports.
I've looked into adding it myself, but not being a web developer I can't wrap my head around this framework...

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2575
