### ISSUE TITLE
Unable to view login with 5.0.0 on Unraid

### ISSUE THREAD

**Issue by w111a** [firefly-iii/firefly-iii#3014]
**Bug description**
I am running Firefly III version 5.0.0 and my problem is:

I receive the message "Whoops There was a fatal error. Please check the log files." after updating to 5.0.0 and trying to access the login page. Before the update I was on 4.8.2 and everything was running well:

**Steps to reproduce**
Update FireflyIII from 4.8.2 to 5.0.0 on UnRaid 6.8.1 through Community Applications(docker)

Extra info
OS: UnRaid 6.8.1
PHP: 7.3( as stated in the logs, within docker)

Logs:
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Sat Jan 18 13:14:07.438925 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.13 OpenSSL/1.1.1d configured -- resuming normal operations
[Sat Jan 18 13:14:07.438959 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
10.253.0.2 - - [18/Jan/2020:14:00:12 -0600] "GET / HTTP/1.1" 500 1676 "http://192.168.1.100/Docker" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:00:13 -0600] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:00:13 -0600] "GET /fonts/lato-100.woff HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:01:59 -0600] "GET / HTTP/1.1" 500 1676 "http://192.168.1.100/Docker" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:01:59 -0600] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
10.253.0.2 - - [18/Jan/2020:14:01:59 -0600] "GET /fonts/lato-100.woff HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
192.168.1.5 - - [18/Jan/2020:15:49:50 -0600] "GET / HTTP/1.1" 500 1676 "http://192.168.1.100/Dashboard" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
192.168.1.5 - - [18/Jan/2020:15:49:50 -0600] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
192.168.1.5 - - [18/Jan/2020:15:49:50 -0600] "GET /fonts/lato-100.woff HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G950W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36"
192.168.1.11 - - [18/Jan/2020:16:21:29 -0600] "GET /favicon-16x16.png?v=3e8AboOwbd HTTP/1.1" 200 1659 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:31 -0600] "GET /chart/account/revenue HTTP/1.1" 200 2271 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:31 -0600] "GET /chart/bill/frontpage HTTP/1.1" 200 2265 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:31 -0600] "GET /chart/category/frontpage HTTP/1.1" 200 2271 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:31 -0600] "GET /chart/budget/frontpage HTTP/1.1" 200 2279 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:31 -0600] "GET /chart/account/frontpage HTTP/1.1" 200 2269 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:32 -0600] "GET /json/box/balance HTTP/1.1" 200 2272 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:31 -0600] "GET /chart/account/expense HTTP/1.1" 200 2261 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:32 -0600] "GET /json/box/bills HTTP/1.1" 200 2260 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:32 -0600] "GET /json/frontpage/piggy-banks HTTP/1.1" 200 2264 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:32 -0600] "GET /json/box/available HTTP/1.1" 200 2258 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:21:32 -0600] "GET /json/box/net-worth HTTP/1.1" 200 2264 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
127.0.0.1 - - [18/Jan/2020:16:21:38 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.13 OpenSSL/1.1.1d (internal dummy connection)"
127.0.0.1 - - [18/Jan/2020:16:21:39 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.13 OpenSSL/1.1.1d (internal dummy connection)"
127.0.0.1 - - [18/Jan/2020:16:21:40 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.13 OpenSSL/1.1.1d (internal dummy connection)"
192.168.1.11 - - [18/Jan/2020:16:22:32 -0600] "GET /v1/lib/fa/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77450 "http://192.168.1.100:5080/v1/lib/fa/css/font-awesome.min.css?v=4.8.2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:36 -0600] "GET / HTTP/1.1" 500 1676 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:36 -0600] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:36 -0600] "GET /fonts/lato-100.woff HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:39 -0600] "GET /bills HTTP/1.1" 200 3591 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:39 -0600] "GET /v1/lib/bs/css/bootstrap.min.css?v=5.0.0 HTTP/1.1" 200 20083 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:39 -0600] "GET /v1/lib/fa/css/font-awesome.min.css?v=5.0.0 HTTP/1.1" 200 7390 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:39 -0600] "GET /v1/lib/adminlte/css/skins/skin-blue-light.min.css?v=5.0.0 HTTP/1.1" 200 1139 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:39 -0600] "GET /v1/css/daterangepicker.css?v=5.0.0 HTTP/1.1" 200 2027 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:39 -0600] "GET /v1/lib/adminlte/css/AdminLTE.min.css?v=5.0.0 HTTP/1.1" 200 15341 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:39 -0600] "GET /v1/css/firefly.css?v=5.0.0 HTTP/1.1" 200 2270 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:39 -0600] "GET /v1/js/app.js?v=5.0.0 HTTP/1.1" 200 139976 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:22:39 -0600] "GET /v1/js/ff/guest.js?v=5.0.0 HTTP/1.1" 200 925 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
127.0.0.1 - - [18/Jan/2020:16:22:45 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.13 OpenSSL/1.1.1d (internal dummy connection)"
192.168.1.11 - - [18/Jan/2020:16:23:05 -0600] "POST /two-factor/submit HTTP/1.1" 500 1676 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:23:05 -0600] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3745 "http://192.168.1.100:5080/two-factor/submit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:23:05 -0600] "GET /fonts/lato-100.woff HTTP/1.1" 404 3745 "http://192.168.1.100:5080/two-factor/submit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:27:11 -0600] "GET / HTTP/1.1" 500 1676 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:27:11 -0600] "GET /fonts/lato-100.woff2 HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
192.168.1.11 - - [18/Jan/2020:16:27:11 -0600] "GET /fonts/lato-100.woff HTTP/1.1" 404 3745 "http://192.168.1.100:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"`

There were a number of tabs open from before the update that had FireflyIII open inside. I thought they were just from cache but looking at the logs maybe some of the requests were successful? I then refreshed the page and got the same "whoops" error.

![Screenshot](https://user-images.githubusercontent.com/6366424/72671594-67971b80-3a12-11ea-9f71-13cb757bec49.png)

**Comment by aronwk-aaron** [comment]
Having this problem on Firefly III V5.0.0 on Unraid 6.8.0


I would think that this is the root of the problem
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message 
```

**Comment by w111a** [comment]
Is there a docker variable for this or is the 'app url' supposed to take care or it?

**Comment by w111a** [comment]
https://unix.stackexchange.com/questions/155150/where-in-apache-2-do-you-set-the-servername-directive-globally

Seems to fix the issue with Debian but I'm not sure how to tackle it with docker.

**Comment by JC5** [comment]
I can guarantee you guys that's not the root issue. That error is standard in Apache when you run it without explicitly defining a domain name and is no problem.

Please enable [debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) so I can see what's going on. The logs you've shared so far only tell me that there's an error, not what it is.

**Comment by teppos** [comment]
I got the same error, but I got it to work. 
After I enabled debug mode I saw that Firefly couldn't create a log file under **/var/www/firefly-iii/storage/logs**
So I created a new path variable which mounts **var/www/firefly-iii/storage/logs** to **/mnt/user/appdata/firefly-iii/logs/**
![unraid-firefly-III-screenshot](https://user-images.githubusercontent.com/20203325/72682369-940f6e00-3acc-11ea-9e3f-baabe7b10007.png)

**Comment by JC5** [comment]
Thanks for the hint!

Something that may also work: environment variable `LOG_CHANNEL=stdout`

**Comment by aronwk-aaron** [comment]
adding `LOG_CHANNEL=stdout` fixed it for me

**Comment by w111a** [comment]
[ff3-cli-2020-01-19.log](https://github.com/firefly-iii/firefly-iii/files/4083919/ff3-cli-2020-01-19.log)

I have tried both of the above mentioned fixes but neither have worked for me. The log fix worked in the sense that I can now view my log. See attached. When trying to view the login page I am now getting the generic "unable to connect" error on Firefox. I'm not sure why it is suddenly now unable to connect to service.

**Comment by JC5** [comment]
There are no relevant error messages in the log file unfortunately. 

Please keep in mind that it can take a few minutes for the image to start, so be patient.

**Comment by w111a** [comment]
So.....got er fixed. In the template there was a duplicate "Container port" being added to the end of the template.( Duplicate of the third variable on the screenshot) that was not letting the docket command to run finish successfully. I had been deleting the newly added "container port" that was being added to the end of the template. This is when I had the conection issues. The image would run without the duplicate variable but I could not connect. I fixed it by deleting the first entry I had for "container port" instead of the newly created one at the end. Seems to have fixed my connection as all is now well. I'm not sure if this is something that could be changed for the docker image or not but the duplicate variable (and deleting the wrong one) was killing me. Thanks for all the help. Seems issue can now be closed

**Comment by JC5** [comment]
Duplicate variables will just be overwritten. But the latter overrules the first so if the second one is wrong the container breaks.
