### ISSUE TITLE
Swap min/max on chart and reverse direction

### ISSUE THREAD

**Issue by Vaelek** [firefly-iii/firefly-iii#3016]
When viewing the page for a bill, the chart shows the defined minimum and maximum on every single month, of course showing the exact same values. This makes it look very cluttered with information that is not really useful at all. Would be much better if the actual values were displayed as bars, and the thresholds were dashed lines. Additionally, it is very disorienting to have these charts oriented backwards. In the US, the latest date should be on the right side not the left side.

![image](https://user-images.githubusercontent.com/293765/72683317-f7cd7300-3a9b-11ea-909f-57bef27d0fe0.png)

**Comment by JC5** [comment]
Thanks for the suggestions. That chart is reversed indeed. Not sure what happened. I'll pick it up.
