### ISSUE TITLE
Bill autocomplete broken

### ISSUE THREAD

**Issue by Vaelek** [firefly-iii/firefly-iii#3019]
When creating a rule action to link to a bill, the autocomplete is broken. 
Watching the logs while typing into this field shows a 404 on all requests to `/json/bills?search=Search%20Term&uid=randomuid`

Using latest docker image

**Comment by JC5** [comment]
I see what you mean, that's a bug. Thanks for reporting!

**Comment by JC5** [comment]
Will be fixed in the next release.
