### ISSUE TITLE
set uid and gid container runs as

### ISSUE THREAD

**Issue by zombiehoffa** [firefly-iii/firefly-iii#3020]
It would be great if I could set the uid/gid that the container will run  as from the compose file/env variable file (as per how linuxserver does all their containers for example). This makes a world of difference for those of us not using docker volumes and getting persistence through mounting spots on our actual file system explicitly.

**Comment by JC5** [comment]
Yes, that's a great idea, I'll do some research.

**Comment by zombiehoffa** [comment]
Wow, that was extremely fast! I appreciate it!

**Comment by JC5** [comment]
You can use the following parameters when not using Docker:

```
-u="", --user="": Sets the username or UID used and optionally the groupname or GID for the specified command.

The followings examples are all valid:
--user=[ user | user:group | uid | uid:gid | user:gid | uid:group ]
```

Or in docker-compose, use the following parameters (same format):

```
user: postgresql
```

This is fairly recent. You can try it yourself.

**Comment by JC5** [comment]
New beta release is live, closed.
