### ISSUE TITLE
Error! Could not upload attachment: TypeError: e is undefined 

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#3021]
Hi. I am getting this error when:
1. Either editing an existing transaction to be cloned or creating a new transaction and
2. I check the after updating return here to continue editing
3. I have a file attached to the transaction
4. I hit update transaction
The transaction gets saved, the attachment is stored, but I get the error above.
Error! Could not upload attachment: TypeError: e is undefined .
I am on 5.0.0.

**Comment by JC5** [comment]
I see what you mean, that's a bug. I hope to be able to fix this in the next release.
