### ISSUE TITLE
Unable to edit destination account of tx in asset account to another asset account

### ISSUE THREAD

**Issue by Vaelek** [firefly-iii/firefly-iii#3022]
Using Firefly 5.0.0 in docker I am unable to link between asset accounts by rule. 
If I edit an individual transaction in an asset account, and type in the name of another asset account (it will not autofill), it appears to link correctly. But if I do this by a rule, it creates a new expense account of the same name and links it there.

**Comment by Vaelek** [comment]
This is not reliably repeatable as I just did another manually and it again created a new expense account.

**Comment by Vaelek** [comment]
Ok I have found that when setting the destination account, the above scenario happens. However if I go the other way and set the source account from the other transaction, it functions as I would expect.

**Comment by JC5** [comment]
That's correct behaviour. What you need is the "convert transaction to a transfer" action. In the field, fill in the asset account you want.

**Comment by oleksiiha** [comment]
I also cannot change destination of the withdrawal, but my case is that even if I want to change a withdrawal transaction to a transfer transaction, then I cannot use Liability account as the destination. And I can do it when I jest create a withdrawal or transfer.
