### ISSUE TITLE
Submit bottom does not work following entering a transaction and checking "After storing, return here to create another one."

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#3023]
After inserting a withdrawal transaction and checking the "After storing, return here to create another one." checkbox the Submit bottom does not work. 
I am on 5.0.0. checkied both in firefox and Chrome.

**Comment by JC5** [comment]
I can't replicate this on the demo site. Can you?

**Comment by lverissimo** [comment]
James,
I was not able to recriate the issue on the Demo site, as I am not able to add new transactions. I have just updated to 5.0.4 and realized the issue only happens if I have an attachement in the transaction I am trying to save, and continue to edit following submission. I will try tomorrow on the demo site again.
Regards,
Luis

**Comment by JC5** [comment]
Thanks, I'll dive into it.

**Comment by JC5** [comment]
Sorry, I did manage to look into this and I believe the issue will be fixed in the next release.

**Comment by JC5** [comment]
This issue will be closed, now that the first alpha of 5.1.0 is out. Keep an eye out on the release page. If something comes up, please open a new issue. Thanks!

**Comment by lverissimo** [comment]
Thank you James. I have tested the alpha version and it is working. Just one glitch, once the transaction gets cloned the attachment field is not reset. If the there was an attachment on the original transaction it will show in the new transaction. Thanks.

**Comment by JC5** [comment]
Thanks, I'll see if I can fix that.

**Comment by lverissimo** [comment]
Thank you. Thinking a little more about it would be better if you added the clean field icon/feature as you already have for other fields such as Category. I have added an enhancement request for that #3133 
Thanks
