### ISSUE TITLE
New tool: Plaid importer

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#3024]
I've created a Plaid importer for Firefly III. Would you consider adding this to the readme? The tool is available [here](https://gitlab.com/GeorgeHahn/firefly-plaid-connector).

This tool is primarily meant to be deployed in docker, though it can be run independently if built from source. The docker container is currently x64 only, but the tool should work on any architecture supported by dotnet core. I'll add CI builds for other architectures if requested.

**Comment by Vaelek** [comment]
That is amazing timing sir I was just reading of the API for making custom importers and was starting to think how I might hook this up with Plaid.

**Comment by JC5** [comment]
Thanks, I'll write it up for the next release!

**Comment by JC5** [comment]
You're mentioned in the new readme.

https://github.com/firefly-iii/firefly-iii/tree/develop

Documentation will follow :)

**Comment by JC5** [comment]
https://docs.firefly-iii.org/importing-data/others :+1:

**Comment by marcelbrueckner** [comment]
+1 👍 for using GitLab

**Comment by GeorgeHahn** [comment]
@JC5 There's a letter missing from my name, but otherwise that looks great!
