### ISSUE TITLE
Can this fit my use case?

### ISSUE THREAD

**Issue by Vaelek** [firefly-iii/firefly-iii#3025]
I have what seems to be a highly unique need that baffles me as to why that is. So before I get too deep into this, let me ask your opinion on how you might adapt to F3 in my shoes.

Originally I used Quicken for years. Having scheduled transactions and being able to fast forward on the calendar to see projected balances at any point in the future was amazing and I became dependent on that. When Quicken retired their desktop software, I tried about every financial package there is and none of them had what seemed such a basic feature.

Fast forward to today, and I've been using an Excel sheet for over a year now. For the sake of this I have 3 accounts. A checking account, a credit card only used for bills, and a credit card for all other expenses, both of which are generally paid off monthly. 

As I have it, my paychecks are all "scheduled" as well as all bills for the remainder of the year. So I can at a glance say that on this day in 2 months, if I meet my budget, I will have a balance of $xx.xx. My credit card payments are calculated from the running balance on the day they are scheduled for, and with each I also have a projected payment, that is the remainder of the balance from the amount I expect it to be. So for example if I have a $700 budget, and the current balance on the next due date is $400, then there will be a projected payment entry for $300. If the current balance reaches $700, the projected drops to 0. I delete the projected lines as they come to pass.

So essentially, what I require is the ability to see an arbitrary distance into the future. If my use case is already able to be accommodated, or if this is functionality you would consider adding, I would be both personally and monetarily appreciative. 

My sheet works, but especially now with the sudden availability of a Plaid importer, I'm really over typing everything in and I don't know when I'll have the time to automate it myself.

Some concepts in F3 are very odd compared to what I am used to, but in the several hours I've been tinkering with it, I see it has great potential, so kudos on all your work here and I hope this will fit my needs.

**Comment by Vaelek** [comment]
I would love to be shown how I'm wrong, but unfortunately I think I've toyed with it enough that I can confidently say that while this is a mighty fine tool, my search continues.

**Comment by GaryQ** [comment]
Yeah would be nice but income can't be budgeted as far as I'm aware. (Hope I'm wrong) Same scenario as you. Been using Excel for years. i started looking and nothing fits what I want out there. But the groundwork in Firefly-III is already laid out better than anything else so I started learning how it and Laravel etc work and rather than write a windows desktop app to do what I want I wrote an app to automate my mods to FF3. So for now it's hack away slowly at FF3 (a lot of pruning) and continue with Excel as I slowly mold JC's work for my needs.

**Comment by JC5** [comment]
Firefly III isn't (and won't) be designed to do future predictions. You could create transactions with a future date though, and most reports will happily include them. They're not really current-time dependent. But otherwise, it seems you're right.

**Comment by GaryQ** [comment]
> You could create transactions with a future date though, and most reports will happily include them. They're not really current-time dependent. But otherwise, it seems you're right.

:That's a great solution! Then I can simply add a "Forecasted" flag field or something to the transaction table
