### ISSUE TITLE
Weird budget chart behavior

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3026]
V 5.0.0

Win 10, Edge Broswer.

Range set Jan 1, 2019 to Dec 31, 2019
All transactions are after Jan 1 
**Budget chart has a 2018 WEEK 53**
Seems the amounts are the transactions from week 1 2019
We only have 52 weeks per year in Canada... 
Has the other side of the Atlantic decide to change to a 53 week year? :-)

![SNIP FF3](https://user-images.githubusercontent.com/3269694/72702089-0dcc4980-3b17-11ea-8dc3-baba2f173948.jpg)

**Comment by JC5** [comment]
Yes, that could happen. The problem is that the year isn't exactly 52 weeks long. So either it's week 0 2019 or week 53 2018.

* https://en.wikipedia.org/wiki/ISO_week_date

**Comment by GaryQ** [comment]
There goes proof I'm losing it. Never even crossed my mind. So much for numbers being my forté

**Comment by JC5** [comment]
Haha no worries. Technically speaking the chart is still wrong; I believe there is no week 53 in 2018. I'll do some deep diving.

**Comment by GaryQ** [comment]
On the wiki page (thanks for that link BTW) There was a box with a list of the 70 years with 2000 being a base year that would have 53 weeks. I didn't see 2018 listed but did see 2020 and at 02:30 in the middle of the night I wasn't going to try and do the math involved to figure out if 2018 was one of those years or not.

**Comment by GaryQ** [comment]
YEP, this one is actually a bug!

I did some researching and low and behold it was so simple...
Excel actually has a built in function called : =ISOWEEKNUM(date)
So I had a bit of fun testing it out.

- ISO weeks must have 7 whole days, start on a Monday and are numbered 1 to 53. 
- Just like leap years 53 has a few conditions to meet in order to be applicable.
- If a year has 53 weeks it will most likely also include days from the following year
- if it has 52 like 2018 some days in Dec can be in week 1 of the next year. 
- 2018 had 52 ISO weeks causing Dec 31, 2018 to be day 1 of week 1 of 2019
- 2020 has 53 ISO weeks so Jan 1,2,3 2021 Will be days 5,6,7 of week 53 of 2020

This definitely justifies continuing to base my personal accounting on a monthly/yearly cycle

<img width="229" alt="Capture" src="https://user-images.githubusercontent.com/3269694/72758499-99d28580-3b98-11ea-990f-60893a7ed002.PNG">

**Comment by JC5** [comment]
This is going to be interesting, considering that I use standard php code to render the week number. Not sure if I can fix it.

**Comment by JC5** [comment]
Found and fixed :+1:

**Comment by GaryQ** [comment]
Cool! 👍 👍  Can't wait to test it out. Maybe by tonight.

**Comment by GaryQ** [comment]
Fixes 2019 that's all the test data I have :)
