### ISSUE TITLE
Opening Balance date and charts (with little hack job fix)

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3027]
All versions from 4.8.?

Since I started testing FF3 I have been bugged by the fact (that I only found out lately) that if starting the year on Jan 1 need to set opening account balances to Dec 31 year before. This fixes some things but causes other issues.

All tests: range set to everything and also 2019/01/01 - 2019/12/31

EX:
Dec 31, opening Balance Jan 1 first transaction:
![SNIP5](https://user-images.githubusercontent.com/3269694/72702468-6b14ca80-3b18-11ea-9b5f-48fd3e9ae11a.jpg)

Jan 1, opening balance..

![SNIP3](https://user-images.githubusercontent.com/3269694/72702525-a0b9b380-3b18-11ea-8b47-4291396d75f2.jpg)

**Temp test fix:**
File: \app\Http\Controllers\Chart\ReportController.php

In     public function operations ,,,
AT LINE 171:        foreach ($journals as $journal) {
                            // ADDED TEST WRAPPING THE WHOLE INSIDE OF LOOP
			   // check if not opening balance before continuing to see if that works
			  if (TransactionType::OPENING_BALANCE != $journal['transaction_type_type']) 
			 {	
                          ….. (wrapped loop)
                         }

Results:
Opening Balances all Jan 1, 2019 

![SNIP1](https://user-images.githubusercontent.com/3269694/72703233-afa16580-3b1a-11ea-8b8e-1df96762e96e.jpg)

Which matches with 

![SNIP2](https://user-images.githubusercontent.com/3269694/72703342-f3946a80-3b1a-11ea-9507-055d3e8950db.jpg)

A more appropriate fix would probably be better but my PHP skills are rusty.  Resolves the problem for me though so eh....

**Comment by JC5** [comment]
Yep, that happens. I'll expand the FAQ / documentation.

**Comment by GaryQ** [comment]
Why not fix the issue instead? After all opening balances are normally reserved for startup any other new account after rolling is technically 0.00 start and a transaction income/expense/transfer to populate it. Unless I'm wrong? I'm fine with my little hack though.

**Comment by JC5** [comment]
It's not an issue. Opening balances are transactions too, and in reports they're part of the package. I realise this can be annoying but I'd rather not introduce more magic.

**Comment by GaryQ** [comment]
I'll summarize my final closing arguments your honor:

1.   The Chart states Income vs. Expenses by period.
1.a - Based on current code it is inaccurate in this scenario.

2.   The box Below States Income Vs. Expenses for the whole period
2.a  - Based on current code it is accurate in this scenario

3.  They both have a common heading "Income Vs. Expenses": (A chart By period and a totals box)
3.a - Mathematically the Sum of all Income per period in the chart should equal the total in box. Always.

I don't see the 'magic you are referring to. Logically it doesn't compute or add up (pun intended)
You do it in the  summary Income Vs. Expenses box. A transfer or an opening balance does not affect those numbers. Yet they do for the Income vs. Expenses chart. 

Therefore it is a bug yet you have the right, the power and the authority to fix it or ignore it.
And on that note, I rest my case your honor.  ;)

**Comment by JC5** [comment]
You're absolutely right. I dived into the issue and somewhere in the past this changed. Not entirely sure what happened, but probably something happened around the time I rewrote the transaction collector. The chart (and only the chart) doesn't filter on transaction types anymore.

I have no excuse except being stubborn. Thanks you for not stopping. A fix will be included in the next release.

**Comment by GaryQ** [comment]
Thanks for fixing this! Just glad to help. Going to go have a peek at the fix now :)

**Comment by GaryQ** [comment]
1. Nice fix...  just 1 line of code. (Wasn't that hard after all huh?)
2. The usual... patch, flush, yada, yada....
3. WORKING! ( "almost" as good as my temp fix. JK, LOL )
4. We can finally put this baby to sleep. 

You can mark it as fixed and close whenever you want.
