### ISSUE TITLE
How to enter returned item transactions

### ISSUE THREAD

**Issue by mcarlosro** [firefly-iii/firefly-iii#3029]
I am running Firefly III version 4.8.2

I have set all my accounts and credit cards. Now I create a transaction from my credit card X to store Y. After 1 week, I need to return whatever I bought. How can I enter a return transaction? I tried to set it in the same way as the original from Credit Card X to story Y with a negative amount but it is not allowed negative numbers.

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files (see https://bit.ly/FF3-get-logs)
- [X] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Create a deposit with source "Store Y" and destination "Credit card X".

**Comment by mcarlosro** [comment]
Thanks. I got it. Because of the combo box menu, I thought I could only use assets already created.
