### ISSUE TITLE
Missing files in Docker Image?

### ISSUE THREAD

**Issue by juliank32g** [firefly-iii/firefly-iii#3032]
I am running Firefly III version 5.0.0.

**Description**
(Please note I'm still learning and all this may be entirely wrong, any pointers are appreciated)

When I go to the homepage I get the "Whoops, there was a fatal error, please check log files" error. From the log it appears that there are two files missing:
/fonts/lato-100.woff2
/fonts/lato-100.woff

I've already tried deleting and pulling the docker container again but that didn't change anything about the situation.

**Extra info**
I'm running Firefly in a Docker on Unraid 6.8.1 and until as recently as yesterday everything seemed to work as expected.

[logs.txt](https://github.com/firefly-iii/firefly-iii/files/4087723/logs.txt)

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [X] I added log files (see https://bit.ly/FF3-get-logs)
- [ ] I was able to replicate the issue on the demo site.

**Comment by w111a** [comment]
I was having a similar issue with unraid 6.8.1 ( see my issue)
https://github.com/firefly-iii/firefly-iii/issues/3014

Turned out I was deleting a required variable ( container port) as it was being added as a duplicate in the template.

**Comment by JC5** [comment]
Duplicate variables will just be overwritten. But the latter overrules the first so if the second one is wrong the container breaks.

**Comment by juliank32g** [comment]
Thanks for your hints. I've noticed that I didn't enable debug mode properly for my last log file so I went back to the issue @w111a mentioned and setting LOG_CHANNEL=stdout fixed it for me,

Thanks everyone for your time.
