### ISSUE TITLE
Transaction form errors without "Source Account" filled, even though a Rule is in place to fill that info

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#3033]
I am running Firefly III version 5.0.0

Inspired by your recent website refresh, I wrote a rule to give myself a shorthand when entering my phone bill.  It defines everything except for the amount, so entering this should be easy -

1. Fill description
2. Fill amount
3. Store transaction (rule should fill in the rest)

![RPM Rule](https://user-images.githubusercontent.com/39804831/72760434-95549f80-3b8d-11ea-8ed8-f22d347fa6f5.png)

However, when I try to store the transaction Firefly gives me an error about the blank Source Account. 

![RPM Transaction](https://user-images.githubusercontent.com/39804831/72760439-98e82680-3b8d-11ea-9823-ba263160ddd2.png)

Am I doing this wrong, or is this a bug?

**Comment by GaryQ** [comment]
Yes, no. maybe...
The NO: you must enter a source account to add a transaction.

The Yes: the fact "Set Source Account to..." is an available option in the rules I'd consider it a bug. 

The Maybe?: Depends on If @JC5 says it's a feature or wants to do something about it

**Comment by JC5** [comment]
The rule engine won’t create transactions for you. It can only trigger on existing ones. So if you submit invalid information to Firefly III you’ll just trigger the validation rules that will report back. 

A short hand is a good idea but you’ll need to make a valid transaction for it to work.

**Comment by hamfactorial** [comment]
OK, thank you.  

My intention was to see how much manual entry the rule would let me skip, and it seems that Description + Source Account + Amount are the required minimums.

I tried entering the transaction again with an arbitrary incorrect Source Account and the rule triggered, changing the Source Account to the correct one I'd defined. 

I input roughly 20 automatically-billed transactions each month, and I know exactly which source/destination accounts those transactions will involve.  It's just the amount that changes, so a shorthand rule would save me time during entry.

**Comment by GaryQ** [comment]
I was thinking of maybe just creating a bogus account with just one letter or number like "1" not included in net worth and use that to quickly enter a transaction with a rule that sets the right account. since you said the rule changes to the right account.
