### ISSUE TITLE
Copy the value from one field to another in rules

### ISSUE THREAD

**Issue by soloam** [firefly-iii/firefly-iii#3040]
**Description**
- Allow in rules to copy the value from one field to another

**Solution**
- Allow the rule system to copy the content from one field to another, this will allow for example, modify the description of a transaction, but keep is content to later reference in another field, for example the external ID (this also is not possible to change in the rule system, I can add this here so that I don't need to open a new feature request for this) or in the note box.

**What are alternatives?**
- In the current system the only alternative is manual changing the fields in all transaction, that is very painful and not funcional!

**Bonus points**
- This could have a mapping in the rule system like:
ACTION: Copy Field Description
VALUE: \<new field name\>

**Comment by JC5** [comment]
See also https://github.com/firefly-iii/firefly-iii/issues/1862

Rules are designed to be simple. Their goal is to be accessible to do basic transaction maintenance and fixing. If you need more complicated stuff, you'll have to build something yourself using the API.
