### ISSUE TITLE
Don't show "Without a category" in dashboars or select what Category to show

### ISSUE THREAD

**Issue by soloam** [firefly-iii/firefly-iii#3043]
**Description**
The "Without a category" should not be displayed in the graph's of the dashboard, sometimes some category don't apply to a category, if there are a lot, the bars for the other category's are very small, because the amount of "Without a category" is a lot bigger.

**Solution**
The "Without a category" should not appear in the dashboard graph's or this should be a option. Another solution would be select the categories to show in the dashboards, similar to the accounts settings.

**Comment by JC5** [comment]
Sorry, this isn't going to change or become optional.

**Comment by soloam** [comment]
And are you open to a gitpull? I can try to see if I can find a solution and present a pull! Probably in the end will be out of my league! But I can try!

**Comment by JC5** [comment]
I don't want to add this as an option, so no. Feel free to experiment with your own copy of Firefly III of course, but I won't merge it.

**Comment by soloam** [comment]
Ok, thank you, case closed! 😀
