### ISSUE TITLE
Locales not working for En-Au

### ISSUE THREAD

**Issue by sheanstickle** [firefly-iii/firefly-iii#3044]
Hi, I've had a bit of a fiddle trying to correct the Locales for my area (Australia), but Firefly doesn't seem to be picking it up. I have experimented by changing my locale to En-US and no joy there either.

Is there something obvious I'm missing?

**Comment by sheanstickle** [comment]
Hi again, after spending some time with the software, I've noticed that initially it gives the message that it can't find the locale, and all amounts are showing with decimals etc. However, if you refresh the page, the message goes away and the decimal points appear.

Any thoughts?

**Comment by JC5** [comment]
Mmm, not really. Firefly III only supports en_US anyway. But if it works?

**Comment by moylanpd** [comment]
I'm having the same issue with es_ES

**Comment by JC5** [comment]
https://docs.firefly-iii.org/faq/self_hosted#decimal-points-are-missing-numbers-are-off
