### ISSUE TITLE
Linking Bill to Transfer to Liabilities Account Not Working 100%

### ISSUE THREAD

**Issue by soloam** [firefly-iii/firefly-iii#3045]
**Bug description**
I have all my credits, loans and mortgage set to Liability accounts. I use the rule system to move the money of the payments like a transfer to the account. I also have a bill setup to anticipate the total value of liabilities to that month. The problem is that the rule system is not linking the bill to the transfer 100% ok. I'll make a small resume.

- A Liability account receives every month the money from the main account
- I have a bill and a rule mapping it with the transfer
- If I run the rule in the rule menu (power button) the transfer and bill are not mapped
- If I click on the "See Matching Transactions" button in the rule menu, I can see my transferes mapped, but the run button does nothing.
- If I go to the bill menu and select the bill and inside click in the "Run rule again in all transaction" the rule runs and in this case it maps the bill with the transaction (transfer).
- In the bill menu I now can see the transactions that exists to that bill.
- If I enter in the transaction (transfer) the bill field is not displayed.

Conclusion:
The system works ok if the transaction is a withdraw, but if its a transfer it does not work as intended. The rule does not make the mapping  even running manually in the rules menu. But if I run it in the rule in the bill menu button, it links, displays in the bill menu, but in the transaction there is no bill mapping

**Steps to reproduce**
- Create Liability account
- Create Regular account
- Transfer money from Regular account to Liability account
- Create a Bill
- Create a Rule to Map the transaction you just created
- Run the rule manually (it should not make any link)
- Go to the bill menu, the bill should not show any link
- Enter the bill and click the run rules
- Go back to the bill menu, there should be the link displayed
- Enter the transaction there should be no link in the transaction to the bill

**Extra info**
- FreeBSD Jail (FreeNAS 11.2)
- Browser Chrome 78.0.3904.108
- Firefly III 5.0.0

**Comment by JC5** [comment]
Bills can only be linked to withdrawals. So if the transactions you make are transfers, that explains why the rule action won't be executed. However, transactions between asset accounts and liabilities are always withdrawals or deposits, so this should not be a problem.

Between which type of accounts are you moving money?

**Comment by soloam** [comment]
I'm making a transaction between "Asset accounts" and "Liabilities", If I make a withdrawals the transaction is not the same. I have to do two transactions, a withdrawals and a deposits? But in that case the destination account of the withdrawal will create a Expense accounts and the source account of the deposit will create a "Revenue accounts". the advantage of the transfer to liability is that it is done in only one transaction... the transfer is linked to the Asset account and the Liability account. This would make more scene.

This almost works, The rule triggered in the Bill menu makes the link between the the bill and the transfer, and the bill shows the the transfers in the bill menu... What does not work is the rule in the rule menu (is it different) and the transaction does not display the bill...

Thank You

**Comment by JC5** [comment]
If you make a transaction from an asset account to a liability account it's stored as a withdrawal:

<img width="641" alt="Screen Shot 2020-01-22 at 18 43 40" src="https://user-images.githubusercontent.com/5889984/73001570-96d6cf80-3dfa-11ea-9c76-1b035135add4.png">

If you create a new rule that triggers on something and makes it link to a bill:

<img width="809" alt="Screen Shot 2020-01-23 at 17 09 22" src="https://user-images.githubusercontent.com/5889984/73001768-de5d5b80-3dfa-11ea-8696-afb55461b7ee.png">

It works perfectly fine for me (see the Bill):

<img width="495" alt="Screen Shot 2020-01-23 at 17 09 51" src="https://user-images.githubusercontent.com/5889984/73001786-e6b59680-3dfa-11ea-9270-fdd85c298d9c.png">

**Comment by soloam** [comment]
Ok I found the problem... You are correct in this, but this shows a bug in the rule system look at this:

I upload a transaction to my asset account, for example via a file this creates a withdrawal from my account to (no name) 
![image](https://user-images.githubusercontent.com/11949987/73003345-66dcfb80-3dfd-11ea-95f0-83fb4faf4d78.png)

but I know that this is to pay my liability, so I create a rule to change the destination account:
![image](https://user-images.githubusercontent.com/11949987/73003598-caffbf80-3dfd-11ea-8218-f481187e98c6.png)

I should send the money to the liability account:

![image](https://user-images.githubusercontent.com/11949987/73003709-fa163100-3dfd-11ea-9437-25f58d1603f1.png)

But nothing:
![image](https://user-images.githubusercontent.com/11949987/73003757-0d290100-3dfe-11ea-9920-349a9c038f42.png)

If we look at the transaction:
![image](https://user-images.githubusercontent.com/11949987/73003889-46617100-3dfe-11ea-9ed0-f7ddac40487b.png)

We can see "Test Liability", but

![image](https://user-images.githubusercontent.com/11949987/73004124-b112ac80-3dfe-11ea-8a15-bb3232931c9b.png)

He created a "Expense accounts" and not of mapping to the existing Liability account.

Also you can see that in the rule creation he can map the liability account in the destination account field:

![image](https://user-images.githubusercontent.com/11949987/73004375-16669d80-3dff-11ea-94b1-0b247c6dfdd7.png)

Not being able to do this is what made mt change my liability payments to transfers. Because if I make in the rule "change the transaction to transfer" and put the name of the liability account, he is able to change to transfer and uses the correct account, not creating a new one.

Was I able to make it clear?

Thank you

**Comment by JC5** [comment]
I see what you mean. Let me check it out and get back to you.

**Comment by soloam** [comment]
Thank you for your time @JC5

**Comment by JC5** [comment]
Yep, you found a bug. I've fixed it, but I wasn't able to do so before release 5.0.1, sorry about that. The code is in the repository and should be included in any next release. If nothing else comes up, it should be end of next week.

**Comment by soloam** [comment]
Thank you @JC5

**Comment by soloam** [comment]
Hello @JC5 did you commited this to 5.0.1? I updated and it still haves the problem!

Thank You

**Comment by JC5** [comment]
Like I said, it's not yet fixed in 5.0.1.

**Comment by soloam** [comment]
Oh, sorry, I miss underfunded that!

Thank you!

**Comment by joke2k** [comment]
Hi, this problem is still here with 5.0.5?
I cannot repay a debt from my asset accounts yet.

**Comment by JC5** [comment]
The fix will go live with 5.1.0

**Comment by joke2k** [comment]
Good, I'm installing the beta right now. Thank you
