### ISSUE TITLE
Whoops! An error occurred. Unfortunately, this error was not recoverable. Firefly III broke. The error is:  syntax error, unexpected ')'

### ISSUE THREAD

**Issue by amrajon** [firefly-iii/firefly-iii#3046]
I am running Firefly III version 4.8.2.

**Description**

I have installed the Firefly III on December 25, 2019, via Softaculous. While I visit the site (domain) where I set it up, in the beginning, it is only showing the error like the following:

![image](https://user-images.githubusercontent.com/49575110/73015020-7ff4a500-3e1b-11ea-8c04-c750babe4a80.png)
I could not even see any page or anything.
**Extra info**
 
There is no log file in the File Manager as well.
**Bonus points**

- [ ] I have read the FAQ at https://bit.ly/FF3-FAQ
- [x] I added a screenshot
- [x] I added log files (see https://bit.ly/FF3-get-logs)
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
It seems you're not running PHP 7.3:

https://docs.firefly-iii.org/faq/installation#i-get-syntax-errors-or-other-problems-when-opening-firefly-iii
