### ISSUE TITLE
Class FireflyIII\Http\Requests\NewUserFormRequest does not exist

### ISSUE THREAD

**Issue by joshuaerda** [firefly-iii/firefly-iii#3047]
Self-hosted install, up and running. Get through new user signup and when I get to the Bank information, after clicking submit I get this error:

![firefly](https://user-images.githubusercontent.com/50249663/73021669-39845380-3de5-11ea-850c-b8eaae7f069c.png)

Did lots of googling, couldn't find anything too helpful.

**Comment by JC5** [comment]
Indeed, and it's serious enough to warrant a new release. Stay tuned for 5.0.1 on the [releases](https://github.com/firefly-iii/firefly-iii/releases) page.

**Comment by joshuaerda** [comment]
Thank you, I appreciate you and all your work!
