### ISSUE TITLE
Transaction Rule Triggers for Transaction Date

### ISSUE THREAD

**Issue by daniel-eder** [firefly-iii/firefly-iii#3049]
**Description**
Triggering Transaction Rules based on the date of the transactions. This can be used to e.g. Tag outdated transactions, or help with setting up an initial correct accounting based on an import via spectre or CSV when first setting up firefly, for example, avoid too-old transactions coming in via spectre.

**Solution**
Transaction Rule Triggers based on date: Less, Equal (Days, not time), More, similar to the amount rules.

**Additional context**
I created a simple "DateLess" rule, if desired I can add two more "more" and "exact" and create a pull request.

**Comment by JC5** [comment]
Mmmm, I like the idea but I'm not a fan of just "number of days". You'd want to trigger on solid dates too, and what about "today" and "last week". Plus, should we translate those and recognize "heute"?

Let me think about it.

**Comment by daniel-eder** [comment]
The wording was not great on that  it actually uses full dates, but ignores time (for now at least). Relative dates and shorthands for that would definitely be interesting too though!

**Comment by JC5** [comment]
Next release of Firefly III will have date triggers. They ignore the time of a transaction. You can read how they work [in the documentation](https://docs.firefly-iii.org/advanced-concepts/rules). 

The demo site already features this so you can test it if you want.

**Comment by carroarmato0** [comment]
Awesome, just when I realized I could use this :)
