### ISSUE TITLE
recurring transaction type drowdown is empty

### ISSUE THREAD

**Issue by bmml1** [firefly-iii/firefly-iii#3051]
I am running Firefly III version 5.0.0, and my problem is:

The recurring transaction type dropdown is empty and a recurring transaction can not be created. Other dropdown controls work as expected.

This request returns an empty json object
/recurring/suggest?date=2020-01-31&pre_select=

**Steps to reproduce**
Create a new recurring transaction

**Extra info**
Debug information generated at 2020-01-24 17:20:31 Europe/Amsterdam for Firefly III version **5.0.0**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.0 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.11-0ubuntu0.19.10.2 |
| Display errors | Off |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2020-01-31 23:59:59 |
| Session first | 2020-01-23 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache |

**Bonus points**

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
As is indicated below the date field: "Indicate the first expected recurrence. **This must be in the future.**"

**Comment by bmml1** [comment]
Hi! Thanks for the quick reply!!

How is this date not in the future?
YYYY-MM-DD 2020-01-31

this also returns an empty json object
/recurring/suggest?date=2022-05-05

**Comment by JC5** [comment]
Sorry, I must have misread it. If you open the link by hand, is there an error by any chance? I’ll have to do a deep dive later :)

**Comment by bmml1** [comment]
No, it returns a 200 HTTP Response.

**Comment by JC5** [comment]
Mmm, there's nothing special in the code that I can see. It works on the demo as well. Let me dig deeper. Could you clear your cache just in case?

```bash
php artisan cache:clear
```

**Comment by bmml1** [comment]
Application cache cleared but no effect. Are there any other dropdowns or other controls which do something similar to check if they act the same.

**Comment by JC5** [comment]
No, this is the only one.

**Comment by bmml1** [comment]
When entering the creating recurring transaction screen debug log prints:

[2020-01-24 22:10:15] local.DEBUG: Saving URL https://firefly.url.xx/recurring under key recurring.create.uri  
[2020-01-24 22:10:15] local.DEBUG: Searching for "Cash account" of type "Cash account"  
[2020-01-24 22:10:15] local.DEBUG: Searching for "Cash account" of type "Cash account"

**Comment by JC5** [comment]
Could you find in your installation, the following file? 

`app/Http/Controllers/Json/RecurrenceController.php`

Replace the content with the content of this link: https://raw.githubusercontent.com/firefly-iii/firefly-iii/f598c39c6e819f2623843c42c43a3c3d3a08fedf/app/Http/Controllers/Json/RecurrenceController.php

That should add some extra debug info for me to checkout.

**Comment by bmml1** [comment]
[2020-01-25 08:15:26] local.DEBUG: Searching for "Cash account" of type "Cash account"  
[2020-01-25 08:15:26] local.DEBUG: Searching for "Cash account" of type "Cash account"  
[2020-01-25 08:15:27] local.DEBUG: date = 2020-01-25T08:15:27+01:00, today = 2020-01-25T08:15:27+01:00. date > today? false  
[2020-01-25 08:15:27] local.DEBUG: past = true? false  
[2020-01-25 08:15:27] local.DEBUG: Dropdown is

**Comment by bmml1** [comment]
Anything else I can provide or test?

**Comment by JC5** [comment]
I expect the second one to display the following:

```
[2020-01-27 19:35:19] local.DEBUG: date = 2020-01-31T19:35:19+01:00, today = 2020-01-27T19:35:19+01:00. date > today? true  
[2020-01-27 19:35:19] local.DEBUG: past = true? false  
[2020-01-27 19:35:19] local.DEBUG: Will fill dropdown.  
[2020-01-27 19:35:19] local.DEBUG: Dropdown is {"daily":{"label":"Every day","selected":false},"weekly,5":{"label":"Every week on Friday","selected":false},"monthly,31":{"label":"Every month on the 31(st/nd/rd/th) day","selected":false},"ndom,5,5":{"label":"Every month on the 5(st/nd/rd/th) Friday","selected":false},"yearly,2020-01-31":{"label":"Every year on January 31","selected":false}} 

```

**Comment by bmml1** [comment]
Yes. Date gets lost on the way and somehow equals today. Can we log somewhere else?

**Comment by JC5** [comment]
This has another cause. Your try_uri config in nginx is bad. Let me look up the details tomorrow.

**Comment by bmml1** [comment]
Thank you, really nice find!
While installing the first time I set it up in a subfolder and tried all kind of different stuff but could not get it to work. So I had this still in location / block
`try_files $uri $uri/ /index.php?$is_args$args;` 
now I switched it to 
`try_files $uri $uri/ /index.php?$query_string;` 
It works now!
