### ISSUE TITLE
Cloning transactions is dangerous and not as quick as before

### ISSUE THREAD

**Issue by hoschi** [firefly-iii/firefly-iii#3052]
**Description**

At the moment it is very hard to clone a transaction to quickly create transactions which occur again and again but with different amount and no fixed schedule. 

One big point is that if you forget to tick the "store as new" checkbox on the edit screen, you would change an existing transaction which would be hard to get the correct values again to change it back IF you even recognize your mistake. 

The current workflow has also the problem that it doesn't automatically set the date to today. It can't modify the date, because "clone" has no route anymore and you don't want to change the date on the edit screen.

**Solution**

Create own route/action for "clone". One logic could be:
* duplicate the transaction right away and set override the date with "today".
* move user to the edit screen of this duplicated transaction

This would solve the problem of modifying a past transaction and also doesn't need to add another route beside "edit". If you "hit the wrong button" you can just delete this transaction.

**What are alternatives?**

I don't know :(

**Additional context**

Examples of such transactions are:
* Pizza delivery
* Gas for car

I usually sit down every weekend and create transactions for the past week. It really helps here for these kinds of transactions, to create them quickly, when the date is set to today. The day isn't right most of the time, but month and year have a high success rate of being kept as they are. Another benefit is that this kind of transactions doesn't change their source or destination account and description, so you have three fields you don't need to put the right data in.

**Bonus points**

**Comment by JC5** [comment]
Absolutely agree. I was thinking the same thing. I like your ideas. Stay tuned!

**Comment by JC5** [comment]
The clone button is back, and can be tried on the demo site.

The [transaction overview](https://demo.firefly-iii.org/transactions/show/362) shows an alert with info. If you use the button in the [transaction list drop down](https://demo.firefly-iii.org/transactions/withdrawal) it will just clone directly.

**Comment by hoschi** [comment]
I like it! :+1: 
Does it make sense to add the "transaction created" message, at least in the second case?
![image](https://user-images.githubusercontent.com/163128/74088387-5b90fd80-4a96-11ea-9370-17e2a38746fc.png)
