### ISSUE TITLE
Account Transaction Box Header suggestion

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3053]
Although cool this is misleading and confusing n a few points

![Snip1](https://user-images.githubusercontent.com/3269694/73128542-7cd1f400-3f96-11ea-8e73-bf258b46b11e.jpg)

In accounting (in North America at least)  ($147.50) is the equivalent to -$147.50 often preferred for negative numbers due to higher visibility. Then being next to Transactions and being viewed as a negative value it gives the impression that it is the sum om the transactions in the box bur the values is the balance. So is the transactions wrong or is the balance displayed in a potentially confusing spot?

**Comment by JC5** [comment]
I see the potential but I think the rusty accountants will just have to use their brains and draw the right conclusions.
