### ISSUE TITLE
Import from SaltEdge only contains last ~250 transactions

### ISSUE THREAD

**Issue by OmgImAlexis** [firefly-iii/firefly-iii#3055]
I am running Firefly III version 5.0.1

**Description**
After importing my two accounts via SaltEdge I noticed I'm only seeing around 250 transactions. Just looking in one of the accounts I have 1000+ showing for the last 12 months in my app.

**Comment by JC5** [comment]
Hi,

That's not something I can do much about I'm afraid. I download everything SaltEdge offers. There's a good chance they limit free accounts. I'll check out their FAQ just in case.

**Comment by OmgImAlexis** [comment]
Otherwise would there be a way I can import a csv and have it match up to the same transactions? I’m using ING Australia.

**Comment by JC5** [comment]
You won't be able to match them up exactly, I can only recommend you delete the old ones with the mass delete tool and import the CSV file.

**Comment by SuperSandro2000** [comment]
spam

**Comment by OmgImAlexis** [comment]
@SuperSandro2000 you didn't need to retag, I was just busy.

@JC5 is there no way for me to have them both? I was hoping I'd be able to at least have the csv for the older records and then the live update for the newer ones without needing to delete the duplicates.

**Comment by SuperSandro2000** [comment]
I am just fighting against stale bot :)

**Comment by JC5** [comment]
I'm sorry, there's no way to merge them.

**Comment by OmgImAlexis** [comment]
@JC5 any reason why? The records should be pretty easy to match up.

Can this be left open as a feature request then? Seems kinda odd not to support this as I’m sure other users will have similar issues.

**Comment by OmgImAlexis** [comment]
Why do you have stale lock issues? This is such an annoying this repos do. This is still an issue. Locking/closing it isn’t going to make it go away.

**Comment by JC5** [comment]
I'm not really sure what you want me to say. There is no merge functionality and I'm not going to build it, because I don't want to. There are very few users who have this problem and they fix it by deleting any double transactions. Thanks for your time.

**Comment by OmgImAlexis** [comment]
So this feature is essentially useless then? Rightio.

There isn't much point is having just the last x records.

**Comment by JC5** [comment]
Talk to Salt Edge. They changed their free service unfortunately.

**Comment by OmgImAlexis** [comment]
It's not that, it's the fact live + static sources are added as features yet there's no way to link them. I would have thought that'd be one of the first things to be added after live connections were.
