### ISSUE TITLE
Auth ErrorTypeError: Failed to fetch

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#3056]
There's a bug in the API playground. Can't get OAuth to work at all.
![failed_to_fetch](https://user-images.githubusercontent.com/5896415/73187015-ad16bf80-415b-11ea-825b-b6957b4606b0.png)

**Comment by emansih** [comment]
Looks related: https://github.com/firefly-iii/firefly-iii/issues/2928#issuecomment-569541784

**Comment by JC5** [comment]
Thanks, I'll check it out. Not sure what happened.

**Comment by JC5** [comment]
Fixed! Updated library sends out new header "x-requested-with", which the demo site refused. Thanks for the pointer.
