### ISSUE TITLE
Simplify entering split transactions

### ISSUE THREAD

**Issue by caseyhoward** [firefly-iii/firefly-iii#3057]
**Description**
This is somewhat related to #2692. Filling out the form for a split transaction is tedious and requires way more information than I care about.

1. Having to make up a name for the transaction seems unnecessary. For example, I like to keep track of how much I spend on food, alcohol, and coffee. If I go to the store to buy all three, what should the title be? I usually just make it the name of the destination account or a combination of the titles for the splits.

2. Similar to above, ~having to fill out~ the description for the transaction seems unnecessary in some cases when I'm using tags (or categories which I don't use anymore now that tags can be applied to splits). For example, with groceries I usually give it the tag "groceries" which also ends up being the description. 

3. ~Having to fill out the source and destination account for every split is tedious. Usually when I split a transaction the source/destination accounts are the same for all. It's because I want to track the types of items I buy.~ I just realized you don't have to fill out these fields.

4. The extra date fields and unnecessary noise. They are disabled and just show "mm/dd/yyyy" for new transactions and the date for saved transactions.

5. ~This is mentioned in the other issue, but the "Foreign amount" field is completely unnecessary for me.~ Just realized this is probably a bug. I have my accounts set to the correct currency and this sometimes happens and sometimes doesn't. I'll try to come up with a way to reproduce it and open a bug.

**Solution**
1. Default the title to either a combination of the split titles or the destination account name if it's the same for all. Or simply allow this description to be blank and generate it on the fly using the destination account name

2. If tags are entered and the description is blank, make the tags the description. Or similar to above, allow it to remain blank and allow the displaying of the generated title a UI concern. Actually, I just noticed you don't have to fill it out and it will just show "(empty description)". I would much rather not have to fill out the title for the entire transaction than the individual splits.

3. ~Default the source and destination accounts to the previous split when creating a new split.~ Show the defaults as pre-selected fields to avoid confusion.

4. Remove date fields after the first split or at least show the value in the splits on the new transactions form for consistency.

5. ~Make the "Foreign amount" an optional transaction field.~ 

Another idea to solve a lot of these issues is on the first split form give some of the fields (source account, destination account, budget, category, tags, etc.) a checkbox that allows the fields to be applied to all splits. Or the other way around and give the fields in the other splits a check box to use value from the first split.

** Other **
Btw, I'm a huge fan of the split transaction UI compared to what it was before. Awesome work. Also, if there is something you think I'm doing wrong with the way I use it please let me know. Thanks!

**Comment by JC5** [comment]
Those are great suggestions, thanks :)

**Comment by JC5** [comment]
1. If a split transaction has no title, it'll take on the title of the first split. Also, the split title input is now at the bottom, so you won't forget it and the page doesn't make that weird jump.
2. The description will always be mandatory, sorry about that.
3. Check.
4. Good idea, this is now the case.
5. Check

I like the idea of applying the data to all splits but it's tricky without overflowing the form. I'll think of something. 

Thanks for the compliments!

**Comment by JC5** [comment]
Closed, release 5.2.0-alpha.1 is live.
