### ISSUE TITLE
Make search case-insensitive by default

### ISSUE THREAD

**Issue by bandresen** [firefly-iii/firefly-iii#3058]
**Description**
I would like to request that the search for transactions is made case-insensitive by default

I feel it violates expectations that the search only does an exact match based on the case of the characters.

**What are alternatives?**
Maybe a flag that can be added to the search box to make it case insensitive if that is required by the user.

vim uses \c to make a search case insensitive and \C to make a search case sensitive.

**Comment by JC5** [comment]
Please use the search. It’s caused by postgresql being case sensitive and there’s not much I can do about it.
