### ISSUE TITLE
Add config setting "Ignore the first n rows"

### ISSUE THREAD

**Issue by M-arcus** [firefly-iii/firefly-iii#3059]
**Description**
My bank exports this format of CSV:

| Name | John Doe |  |  |  |
|-------------------|------------------|---------------------------|-----------|--------------|
| IBAN | AB12345667890 |  |  |  |
| Current Amount |  1337.42 |  |  |  |
|  |  |  |  |  |
| Starting Date | 01.01.2020 |  |  |  |
| End Date | 20.01.2020 |  |  |  |
|  |  |  |  |  |
| Your transactions |  |  |  |  |
| Date | Description | Account | Amount |  Current |
| 02.01.2020 | Pizza Delivery | Pizza Mario | -42.00 |  +1006778.81 |
| 01.01.2020 | Wage for January | ACME Financial Department |  +6820.81 |  +1006820.81 |

Firefly complains about the first 8 rows not being valid -> the import fails.

**Solution**
Add a setting as integer that if set, ignores the first n rows
Default this setting to zero, so it doesn't break other imports

**What are alternatives?**
Workaround: Open the file, remove the rows by hand, save then import (or cli command).

**Additional context**
Maybe a small hint about the possible interaction with the "Headers" setting.

**Bonus points**
- Make a drawing
I made a small mockup -> see yellow background
![image](https://user-images.githubusercontent.com/25648755/73361392-2a9a1700-42a5-11ea-8a04-fa840f7fb7e4.png)
- Donate money: 
5$ dollars have been donated ;)

**Comment by JC5** [comment]
I saw your donation, thank you!

As to the idea, I'm afraid I'm going to do a hard pass, sorry about that. CSV files that contain meta information like your file are against the whole idea of CSV files and I'm not going to encourage the practice of delivering terrible CSV files, something that way too many banks seem to do.

An easy way to do this on the command line is tail, where you use n+1 for the number of lines you want to cut. In your case, 9:

```bash
tail -n +9 file.csv > new-file.csv
```

**Comment by M-arcus** [comment]
I agree with your points on terrible banking software and not encouraging bad file-structures.  

My reason for this feature request is: I have been trying to get more people from family and friends to use Firefly. They are accustomed to being able to just import something without any file editing. The json config file for the different banks already makes this really easy.

But some are not able to complete the extra step of having to edit the csv-file without help.  Most of them don't know what a command line is, what exact rules a csv-file has or may not have Excel (or open source alternatives) installed on their devices, for example on a mobile phone.
So they are barred from importing by a problem that their bank is responsible for.
This feature would eliminate that final barrier.

**Comment by JC5** [comment]
I appreciate that, but please keep in mind I can't make it easy for everybody. The USP of services like Mint and YNAB is the import function, because they have plenty of development teams working fulltime on these import routines.

**Comment by M-arcus** [comment]
I offer develop this feature and add it as a PR.

**Comment by JC5** [comment]
I appreciate that, I really do. But this is a feature that I don't want to have in Firefly III. It's not about the effort or the development, I just don't want to add this. I believe my explanation was clear.

You're free to develop this of course and please do. That's the whole idea of open source software. I hope it helps you to convince your family to use the tool. But keep in mind I won't merge it back into Firefly III.
