### ISSUE TITLE
Abstract idea - mortgage

### ISSUE THREAD

**Issue by xzaz** [firefly-iii/firefly-iii#306]
I got this idea that is a abstract idea that a loan / mortgage. It can be used as a account; this mortgage can be linked to a bill for paying your monthly interest plus extras. 

So abstract; a new kind of account:
- Percentage of loan
- Start and end date
- Period payback (can be linked to bill?)
- Calculate extra payment; what will your monthly (or the selected period) be.

Let me know what you think of it.

**Comment by JC5** [comment]
I have had the plan already to include loans and debts as account types. I believe these account types already exist in the table ``account_types``, but they haven't been used anywhere yet.

It is a complex thing, a mortgage. Just like loans, debts, and currency exchange rates (see #305), it is not really impossible to calculate such things but rather it is impossible to calculate such things _exactly as your bank would_.

What I suggest to build is the following:

An account type should be added for debts, (student) loans and mortgages.

* These account types have a negative amount (the total loan)
* Can be set a percentage of rent (to be paid per period X). See bullet point 1 below.
* And possible an extra amount of money. See bullet point 1 below.
* Can generate some useful things such as (like you say) a bill to match.
* Payback calculator using fictional amount (if I pay X the loan is gone at date Y).
* Impact your total net worth
* But may be off set by the value of the house?

I will have to do some reading and thinking as to how to do this but I love the idea and will add it to the feature list for sure!

**Comment by FrodeMMeling** [comment]
Is there a way to administer loans in firefly?

**Comment by JC5** [comment]
Not yet. I'm not sure yet how to register them, if and how register rent, etc.

**Comment by FrodeMMeling** [comment]
Can be registered as regular account. Difference is that it has loan-metadata attached.
Interests are added each month, and a downpayment kan be registrered that support to be splitted

**Comment by JC5** [comment]
Yep. That's not the hard part.

"Loan metadata" and "interest" are bloody difficult. Not because a loan calculation is that hard but because each bank has their own little methods of calculating interest, adding it to the debt and registering it. 

Automatically doing these calculations (weekly, monthly, yearly) are hard to program and will probably be wrong half the time.

What I am thinking of now is to add loans as an "account" of sorts, one that you can create and send money to (the payments you've mentioned). Interest is another subject all together and will probably be something manual.

**Comment by FrodeMMeling** [comment]
Ok. In norway the rules are the same.  But to add support for it, I do not see a reason for the app to know everything. I just need an account, with a balance. Then each month I transfer a given amount of data from Bank account and this is splitted in 3 : downpayment, interest and a fixed fee. Down payment is balanced against the loan-account, the interest to a interest expence and fee to a fee-account. Or something like that.

**Comment by JC5** [comment]
Ah yes, that should be possible. At the moment, Firefly does not support "mixed" splitted transactions, where there are both positive and negative numbers. But that can always be changed. It's on the list!

**Comment by SimonHoenscheid** [comment]
@JC5 Thx for guiding me over to this issue. Fits my needs

**Comment by JC5** [comment]
Alright, a start for this feature will become available in the next release of Firefly III. You can play around with it on the demo site already.

* You can add liability accounts, of the types "loan", "debt", "credit card" and "mortgage", ~~stolen from~~ inspired by GNUCash
* You can make transactions from and away from these accounts.
* New is the ability to include or exclude these (or any) accounts from the net worth.

This is just basic functionality though. You can track debts, but that's it. I am thinking of expanding the `/accounts/show/x`-view so it'll be more useful for debts but nothing solid is implemented yet.

Unless you find any bugs or have found major issues, I will close this issue for the next release and I invite you to open new issues with features or things you might want to see! Likewise, I will add tickets if I think of anything useful to add.

Thanks,
James

@JoshuaLuckers @stefano-pogliani @moay @eivindr @xzaz @FrodeMMeling @SimonHoenscheid

**Comment by JC5** [comment]
And the new release is live :+1:
