### ISSUE TITLE
Problem after fresh install with /var/www

### ISSUE THREAD

**Issue by Smokerson** [firefly-iii/firefly-iii#3060]
I am running Firefly III version 5.0.1

I tried to install Firefly III in Ubuntu and im having a problem with page 404.

I have it installed in /var/www/firefly-iii, whenever i visit the site i  can see the default apache2 index page and firefly will simply show a 404 page.

If i change the DocumentRoot in 
/etc/apache2/sites-available000-default.conf to "/var/www/html" to "/var/www" then i can load Firefly III just fine. with the warning message for a few seconds then it will auto direct me to the login page and it works fine.

I have <Directory /var/www/> AllowOverride set to All, i also enabled mod rewrite.

With the DocumentRoot set to /var/www i can access Firefly using http://192.168.1.123/firefly-iii/public

**What i want is** to keep the DocumentRoot as /var/www/html as it is and still be able to access Firefly using http://192.168.1.123/firefly-iii/public

How can I do that?

Here is the setup and some extra info

OS: Ubuntu server 18.04.3
Browser: Firefox/Chrome
Webserver: Apache2, PHP7.3 and MySQL

**Comment by JC5** [comment]
Move Firefly III to /var/www/html.

**Comment by Smokerson** [comment]
But if i do that i get the warning message not to do that?

**Comment by JC5** [comment]
Well there's the problem. If you want to keep using /public, you also expose /storage which contains potentially sensitive info. I can only stress that you should change the document root, or create another domain / subdomain.

**Comment by Smokerson** [comment]
what would i point it to if i want it to be properly configured and secure?

**Comment by JC5** [comment]
Change the document root to `/var/www/firefly-iii/public`. Or read into virtual hosts, which is a way of configurating virtual (sub)domains. But that's something you'll need to Google :)

**Comment by Smokerson** [comment]
No worries. 

One last thing, if im only running Firefly III on a local server at home without any access from outside my network, there shouldnt be any risk if  /storage is exposed or not, right?

**Comment by JC5** [comment]
No there shouldn't be. Most people don't run Firefly III online.

**Comment by Smokerson** [comment]
Thanks for the info. It took me a couple of days to actually figure out why i keep getting error 404.

I'll mark this as closed.
