### ISSUE TITLE
Link to missing locale packages wrong

### ISSUE THREAD

**Issue by SuperSandro2000** [firefly-iii/firefly-iii#3061]
**Bug description**
I am running Firefly III version 5.0.1, and my problem is:

![image](https://user-images.githubusercontent.com/7258858/73397621-3bb64880-42e4-11ea-88e0-43382368110e.png)
links to https://github.com/firefly-iii/help/wiki/Missing-locale-packages

**Steps to reproduce**
Do not install the required packages

**Extra info**
Maybe it could point to https://docs.firefly-iii.org/faq/self_hosted#decimal-points-are-missing-numbers-are-off ?

**Bonus points**

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nice one, I fixed it!

**Comment by SuperSandro2000** [comment]
@JC5 I would prefer it if you would close fixed issues rather than let them stale and being closed by this spam bot.

**Comment by JC5** [comment]
I do, I just never marked this as a bug.
