### ISSUE TITLE
question: Release and master vs dev branch

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3065]
Is there any specific reason 5.0.3 release and master repo are 20 commits behind the dev branch?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3063

**Comment by GaryQ** [comment]
So other fixes like https://github.com/firefly-iii/firefly-iii/issues/3050 are not in 5.0.3?

**Comment by JC5** [comment]
No, sorry, I just applied the hotfix. I’ll pick up the rest at a later moment.

**Comment by GaryQ** [comment]
Thanks for clarifying. Last question:  is the dev branch pretty stable or do I have to cherry pick fixes?

**Comment by JC5** [comment]
The dev branch should be fine. I try not to submit half work.
