### ISSUE TITLE
Tags view broken 5.0.3

### ISSUE THREAD

**Issue by marviins87** [firefly-iii/firefly-iii#3066]
**Bug description**
I am running Firefly III version 5.0.3, and my problem is:

I didn't noticed it before so i'm not 100% sure if this is related to 5.0.3.
Some tags in my overview are broken. It's still a button and when i press them the corresponding tag page opens. So it's only the button. (see screenshots for example)

**Steps to reproduce**
- have a lot of tags
- open tags page.

**Extra info**
Debug information generated at 2020-01-30 16:02:15 UTC for Firefly III version **5.0.3**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.3 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.14 |
| Display errors | Off |
| Session start | 2012-12-14 00:00:00 |
| Session end | 2020-01-30 00:00:00 |
| Session first | 2012-12-14 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/
![screenshot](https://user-images.githubusercontent.com/31892758/73466628-6d7dec80-4382-11ea-88c9-790d45d2bbff.png)

**Comment by JC5** [comment]
I see what you mean, I'll dive into it :)

**Comment by JC5** [comment]
Like I mentioned in #3067, I pushed another overview that should also fix this one.

**Comment by marviins87** [comment]
Thanks a lot!

**Comment by JC5** [comment]
This issue will be closed, now that the first alpha of 5.1.0 is out. Keep an eye out on the release page. If something comes up, please open a new issue. Thanks!
