### ISSUE TITLE
improvement tags overview page

### ISSUE THREAD

**Issue by marviins87** [firefly-iii/firefly-iii#3067]
**Description**
I would like Firefly III to give a more cleaner tags overview page. The current tags aren't in alphabetical neither trending order and with all the different sizes (based on how often its used) it looks like a mess in my setup.

**Solution**
I'm loving the use of tags and i would like to see the tags page changed as follows:
- all tags the same size.
- naming like; tagname(how often)
- e.g. "Boodschappen (45x)"
- possibility to sort the tagslist on multiple values (alphabetical, how often, creation date)

**What are alternatives?**
Maybe it could be a configuration setting in the administration page to choose which one to use. The current style or my new style.

**Comment by JC5** [comment]
Thanks, those are great suggestions. It's not going to be optional, I'll see what I can pick up.

**Comment by JC5** [comment]
I've pushed some changes to the [demo site](https://demo.firefly-iii.org). Long tags will break the overview, that's not something I'm going to dive into all too deeply.

As it stands though, you might be better of using categories instead of tags (ie "Boodschappen").

**Comment by marviins87** [comment]
Wow, much better! 

Is it difficult to get a counter as part of the tag name?

e.g. "Boodschappen (615x)"

**Comment by JC5** [comment]
No, but that's not something I want to add. It's not a very useful metric.

**Comment by marviins87** [comment]
> 
> 
> No, but that's not something I want to add. It's not a very useful metric.

You're right. Thanks again!

**Comment by JC5** [comment]
This issue will be closed, now that the first alpha of 5.1.0 is out. Keep an eye out on the release page. If something comes up, please open a new issue. Thanks!
