### ISSUE TITLE
Sum of all bills for a specific month

### ISSUE THREAD

**Issue by schneekluth** [firefly-iii/firefly-iii#3068]
**Description**
It would be nice if you could show the sum of all bills for a specific month e.g. when you are planning your budget for the next month. Currently I have to navigate to the bill section and calculate them manually. 

**Solution**
It would be handy if you could integrate an option to only show the bills for a specific month and sum the up automatically.

**What are alternatives?**
Using a good ol' calculator.

**Comment by JC5** [comment]
There's a sum at the bottom of the bills page, and the teal top box also shows a sum. Are those what you're looking for? 

I'll mark this as an enhancement because the report page could use such a sum as well.

**Comment by schneekluth** [comment]
Not exactly. The bill page always shows the sum of all bills for the *current* period e.g. january. Let's say it is the end of January and I want to plan my budgets for february and I want to know which bills have to be payed in february and the sum of all bills in period february then there is no button or filter where I can filter for all bills in february.

**Comment by schneekluth** [comment]
> There's a sum at the bottom of the bills page, and the teal top box also shows a sum. Are those what you're looking for?

Sorry, you are totally right. The top box was the information I was looking for. But it still think it might be an enhancement to show this value in the bill section. Anyway, I'll close this issue.

**Comment by JC5** [comment]
Sum is now present.

**Comment by schneekluth** [comment]
Thank you!
