### ISSUE TITLE
Currency symbol preceding amount regardless of locale

### ISSUE THREAD

**Issue by kbancerz** [firefly-iii/firefly-iii#3070]
**Bug description**
I am running Firefly III version 5.0.0, and my problem is:

Changing language and locale does not affect the position of the currency symbol as it should:

![image](https://user-images.githubusercontent.com/9020152/73561254-f8311b00-4458-11ea-9c02-5f19498ecb28.png)

Even though Polish is set, the symbol precedes the amount, rather than succeed it.

**Steps to reproduce**
Change the language and go to the cockpit.

**Extra info**
I am not too proficient in PHP, but I was able to find out that most probably the issue is related to these lines: https://github.com/firefly-iii/firefly-iii/blob/e9ab11051f95be8cd30c39d457f66e476233afcd/app/Support/Amount.php#L139-L140

Type-aware comparison is used (===), but the values assigned in these lines, are integers (0 or 1), not booleans: https://github.com/firefly-iii/firefly-iii/blob/e9ab11051f95be8cd30c39d457f66e476233afcd/app/Support/Amount.php#L137-L138

The comparison of boolean to integer always evaluates to false, so currency symbols always precede the amount.

If I modify the assignment lines, locales seem to work as expected:

```
$precedes = $amount < 0 ? $info['n_cs_precedes'] === 1 : $info['p_cs_precedes'] === 1;
$separated = $amount < 0 ? $info['n_sep_by_space'] === 1 : $info['p_sep_by_space'] === 1;
```

![image](https://user-images.githubusercontent.com/9020152/73562089-adb09e00-445a-11ea-813f-e6d219c755c7.png)

I don't know if this is relevant, but I use the official Docker version (apache-debian) as my running environment.

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
That's strange. The documentation is pretty clear:

https://www.php.net/localeconv

>  TRUE if currency_symbol precedes a positive value, FALSE if it succeeds one 

I'll dive into it. Thanks for debugging!

**Comment by JC5** [comment]
I've pushed some fixes to the [demo site](https://demo.firefly-iii.org/), could you check it out?

**Comment by kbancerz** [comment]
Pulled the fix on my local env and it works like a charm :) Thanks!

![image](https://user-images.githubusercontent.com/9020152/73592442-bbb5fb80-44fa-11ea-8211-20ce01937d7e.png)

**Comment by SuperSandro2000** [comment]
Technically the currency sign position is depending on the currency type and not something else. 
Eg Dollar is always infront and Euro is always behind, everything else is not correct.
$10
10 €

**Comment by SuperSandro2000** [comment]
Strange... Locales are weird.
