### ISSUE TITLE
Question about the boxes at the top of the homescreen

### ISSUE THREAD

**Issue by pedrom34** [firefly-iii/firefly-iii#3071]
Hey James,

What is this red box at the top?
![image](https://user-images.githubusercontent.com/21216829/73579119-d8fab380-4481-11ea-9355-25e2a0efd2fb.png)
I mean, I understand what it is, but it never occurred so far that this box displays another thing than "too much spent". How is this balance calculated?

I am running Firefly III version 5.0.1

**Comment by JC5** [comment]
It's calculated from the amount you set in this top box on the /budgets page:

<img width="1341" alt="Screen Shot 2020-02-01 at 05 37 30" src="https://user-images.githubusercontent.com/5889984/73586945-fbf28b00-44b4-11ea-8db6-907cf2ce7f08.png">

I'll mark this as an enhancement to add something to the documentation and change the box in case you don't set this.

**Comment by pedrom34** [comment]
Oh!
I didn't even notice this field! 😅 Thanks!
