### ISSUE TITLE
How to book revocation

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#3072]
I am running Firefly III version 5.x.x

**Description**
I ordered a notebook but it got delivered damaged. I sent the product back and got the money. I now would like to book the returned money so my expense account "notebook shop" is not including the amount of money I payed for the product.

How to do?

If I use a deposit FF is automatically creating a new revenue account.
If I use a transaction im not able to select the expense account.

Thanks.

**Comment by JC5** [comment]
Create a deposit, and live with the fact that Firefly III will create a new revenue account.

**Comment by devfaz** [comment]
But this will not free my budget for things correctly.
I did not jet take a look into the code, but would it technically be possible to create a negative withdrawl?

**Comment by JC5** [comment]
The situation is slightly different but the answer is the same:

https://docs.firefly-iii.org/faq/financials#what-do-i-do-with-people-who-pay-me-back
