### ISSUE TITLE
Should a rule include all parts of a splitted transaction

### ISSUE THREAD

**Issue by Markus-** [firefly-iii/firefly-iii#3073]
I am running Firefly III version 5.0.4

**Description**
I have a transaction which I split into two.
I give each sub transaction different Tags.
For each of those Tags I have rules which fire when a transaction is changed.

The first sub transaction (the original one) is handled by the rule, the second is ignored.

If I search for matching transaction in the rules the second sub-transaction is listed.

Works as designed or do I miss something?

**Comment by JC5** [comment]
Do you have "stop processing" selected for the first rule? I'll have to test this but split transactions are treated just like other transactions, so it shouldn't matter.

**Comment by JC5** [comment]
A quick test shows that rules trigger on all splits, as I expected.

**Comment by Markus-** [comment]
I tried it again.
I didn't set "stop processing".

My Rule:
Trigger: If transaction is changed
Active: True
Strict Mode

Trigger: 
Tag = XY

Rule:
Remove Tag XY
Add Tag = AB
Set category = XYZ
Target Account = ZZZ

1. I create a Transaction with the Tag XY. The rule is not fired, because only "on change".
2. I change this transaction and split it into two. 1 change both amounts and put Tag XY on. Rule is just fired on the first part - not for the second.
3. I change any part on the second part. Rule ist fired after the change.

I have expected, the rule fires against both parts in the first place.

Bonus-Question: Do I have to create two rules if I want to handle imports (on creation) and changes (on change)?

**Comment by JC5** [comment]
Could you show me the debug logs when this happens?

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://docs.firefly-iii.org/contact/contact).

**Comment by JC5** [comment]
Thanks for emailing me the log files. I suspect you found a bug. Updating a split transaction where the second split doesn't exist confuses the rule activation. Stay tuned.

**Comment by Markus-** [comment]
Fine (not the bug itself). Thanks for your support. Will keep posting issues ;)

**Comment by JC5** [comment]
This will be fixed in the next release :+1:
