### ISSUE TITLE
Dashboard - Whoops There was a fatal error. Please check the log files.

### ISSUE THREAD

**Issue by JakeLadson** [firefly-iii/firefly-iii#3074]
Hello,

When trying to load the dashboard and login page I am getting "Whoops There was a fatal error. Please check the log files.". All other pages are loading correctly. I tried the alpha, beta, and official releases and am getting the same error on all 3. The logs don't seem to show any errors either. I am running a container on Unraid, if that helps at all. Here is the log entry when I load the dashboard: 

`[02/Feb/2020:09:13:36 -0600] "GET /fonts/lato-100.woff HTTP/1.1" 404 3745 "http://192.168.1.124:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"`

Thanks!!

**Comment by JC5** [comment]
Thanks for reporting. Try enabling debug mode: https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode

The log entry is just your browser loading a font.

**Comment by JakeLadson** [comment]
I am having this problem when I try and restart with the command.

![image](https://user-images.githubusercontent.com/26978529/73611428-65eb5d00-45a7-11ea-9103-4045e9a8538d.png)

**Comment by JC5** [comment]
I don't know how to restart a container with a different set of environment variables. You might have to recreate it.

**Comment by JakeLadson** [comment]
It looks like the -e was depreciated at some point. Do you know where the source files are located in unraid? I was trying to find them but I cant seem to locate them.

**Comment by JC5** [comment]
I have no idea.

**Comment by JakeLadson** [comment]
Well this is weird...

I changed the log path as here: https://github.com/firefly-iii/firefly-iii/issues/3014#issuecomment-576007731

> I got the same error, but I got it to work.
> After I enabled debug mode I saw that Firefly couldn't create a log file under **/var/www/firefly-iii/storage/logs**
> So I created a new path variable which mounts **var/www/firefly-iii/storage/logs** to **/mnt/user/appdata/firefly-iii/logs/**
> ![unraid-firefly-III-screenshot](https://user-images.githubusercontent.com/20203325/72682369-940f6e00-3acc-11ea-9e3f-baabe7b10007.png)

and now everything is working as expected.

Strange...

**Comment by 40foot** [comment]
I have the exact same "Whoops error" after updating from 5.0.1 to 5.0.4 under UNRAID 6.8.2 - using Community Applications. Adding the log variable didn't help me. Contacting James Cole didn't help either. Added the variable DB_CONNECTION=mysql changed nothing. I tried reverting from firefly-iii:latest to firefly-iii:5.0.1 but UNRAID won't let me (I don't really know how to do this). Now I'm stuck and all my work on my financial information is for Hugo (just a saying here...). Jake, can u help me? Despite db_connection=mysql in debug it shows: 
PDOException
SQLSTATE[08006] [7] received invalid response to SSL negotiation: J
in PDOConnection.php line 31
at   PDOConnection->__construct('pgsql:host
Why pgsql ?
If I ever get this to work again I will never ever update it again.

**Comment by JC5** [comment]
Perhaps DB_CONNECTION=mysql was not added in the right place?

**Comment by JakeLadson** [comment]
@40foot To go back to a previous version you need to put release then the version number. Like this: 

`firefly-iii:release-5.0.0`

I'm also not sure what "for Hugo" means.

**Comment by aronwk-aaron** [comment]
Adding DB_CONNECTION=mysql to my docker config fixed this.
Since I have my db running form a mariaDB container and not postgresql
