### ISSUE TITLE
Philosophy on budgets

### ISSUE THREAD

**Issue by funnym0nk3y** [firefly-iii/firefly-iii#3076]
I have a general question regarding the use and philosophy of budgets: 
According to the manual budgets can't be corrected by income, so they are an accumulation of outgoings. That's fine for easy cases like shopping groceries for yourself. 
But when I get a payback from friends, a discrepancy between the actual state of the bank account or budget and firefly will arise:
Either I edit the budget belated (which does not refelct the intended state) or my transactions will not match with what actually happened (like -100 for pizza with friends and +50 payback, but only -50 is registered). 
Also @JC5 stated, that automation for reoccuring budgets won't be a thing because it is not the right way of doing it. 

I know those topics were discussed quite often here, but unfortunately @JC5 never gave a extensive explanation how it is meant to be. 

If firefly doesn't reflect each and every transaction of my bank account and I have to keep things in my head like actually paid 100, but got 50 back and so on, what's the intention of using firefly. 

From my understanding a finance manager should only get real transactions as input. Budgets and fractions of saved income should be set in advance, and not be altered. Then the finance manager should boil down all available data and calculate some numbers one can use for further decisions like can I afford the more expensive cocoa or not. 

I really don't understand the value of budgets in firefly, therefor I politley ask you, @JC5, to elaborate your intentions, thoughts and philosophy on budgets in firefly and in general. 

funnym0nk3y

**Comment by JC5** [comment]
Hi,

You're putting a lot of things in your post, and I'm not sure if I have the answer to everything. But let's start with some things that I believe are misconceptions.

You *could* use Firefly III to reflect every single transaction exactly like your bank has it. It's entirely up to you. But that's not mandatory and whether you do that or not doesn't change the point of Firefly III. Firefly III is *not* meant to make financial decisions for you: YOU make the financial decisions. Firefly III can only present the data in some meaningful way. 

I'm not really sure what else to tell you when it comes to budgets, except what's in [the FAQ](https://docs.firefly-iii.org/faq/financials#what-do-i-do-with-people-who-pay-me-back) already. You should use what works for you, Firefly III isn't going to tell you what works best. Like I say in the FAQ, my personal preference is to change the expense. But again, this is up to you.

I believe that setting your budgets every month manually makes you aware of your expenses and how you wish to spend your money. Even when they're the same every month. If you're the least bit tech-savvy, you can use the API to automate this for you.

Let me know if this helps.

**Comment by funnym0nk3y** [comment]
Thanks for the fast answer!

> You could use Firefly III to reflect every single transaction exactly like your bank has it. It's entirely up to you. But that's not mandatory and whether you do that or not doesn't change the point of Firefly III. Firefly III is not meant to make financial decisions for you: YOU make the financial decisions. Firefly III can only present the data in some meaningful way.

Sure, but to make valid decisions in my opinion Firefly should allow us to base on the most accurate data (meaning each transaction). 


> I'm not really sure what else to tell you when it comes to budgets, except what's in the FAQ already. You should use what works for you, Firefly III isn't going to tell you what works best. Like I say in the FAQ, my personal preference is to change the expense. But again, this is up to you.

I understand both current options to handle that, but as several people proposed a option to include income to the calculation would work much better and as you wrote FireFly should not tell me how to do it, that would be my choice. You said there would not be such and option. Is it a) because you don't want it in Firefly at all or b) because you don't think it is useful and you don't want to spend time on it (but would be integrated via pull request)? 


>I believe that setting your budgets every month manually makes you aware of your expenses and how you wish to spend your money. Even when they're the same every month. If you're the least bit tech-savvy, you can use the API to automate this for you.

Kind of similar argumentation like above. Why do a seperate piece of software which adds complexity and not directly integrate it? People are not forced to use it and everyone who likes to do it manually still can. 

Please understand, that I'm not trying to offend you, but rather understand what the thoughts are regarding that topic.

**Comment by JC5** [comment]
That's quite alright of course. But this is something I'm not changing. It's not something I want in Firefly III.
