### ISSUE TITLE
Synology: PHP extension missing

### ISSUE THREAD

**Issue by Ethratian** [firefly-iii/firefly-iii#3077]
I tried to install firefly-iii on my Synology NAS.

When I try to execute the main command

**composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii <latest>**

(which I had to change to composer create-project grumpydictator/firefly-iii since the latest version on https://version.firefly-iii.org/ seems not to be right)

i receive the following code an errors:

Installing grumpydictator/firefly-iii (3.10.4)
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
  - Installing grumpydictator/firefly-iii (3.10.4): Loading from cache
Created project in /volume1/web/firefly-iii
> php -r "copy('.env.example', '.env');"
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
**Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nikic/php-parser v2.1.0 -> satisfiable by nikic/php-parser[v2.1.0].
    - nikic/php-parser v2.1.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
  Problem 2
    - Installation request for simplesoftwareio/simple-qrcode 1.3.3 -> satisfiable by simplesoftwareio/simple-qrcode[1.3.3].
    - simplesoftwareio/simple-qrcode 1.3.3 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 3
    - Installation request for phpunit/php-token-stream 1.4.8 -> satisfiable by phpunit/php-token-stream[1.4.8].
    - phpunit/php-token-stream 1.4.8 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
  Problem 4
    - nikic/php-parser v2.1.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - psy/psysh v0.7.2 requires nikic/php-parser ^1.2.1|~2.0 -> satisfiable by nikic/php-parser[v2.1.0].
    - Installation request for psy/psysh v0.7.2 -> satisfiable by psy/psysh[v0.7.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.**

Any suggestions?

**Comment by JC5** [comment]
> (which I had to change to composer create-project grumpydictator/firefly-iii since the latest version on https://version.firefly-iii.org/ seems not to be right)

I don't understand why your first response is to blame me. :(

You're being served **3.10.4**, a version from **[September 2016](https://github.com/firefly-iii/firefly-iii/releases/tag/3.10.4) probably because your Synology is running an ancient unsupported version of PHP.

So I can only suggest you upgrade your Synology and then try again.

**Comment by Ethratian** [comment]
Sorry JC5, I didn't intend to blame anybody, you the least - mea maxima culpa!

The command did not work at first and after trying to solve it for some time I found a comment in a forum that a user had used the shortened command line and then it worked. Therefore I did the same.

When I inserted the latest version (which is 5.0.4 according to the website) it didn't work either.

On my Synology I have installed PHP 5.6 (as far as I know Synology needs this version itself) and PHP 7.3.

**Comment by JC5** [comment]
I think you have to tell Synology to prefer PHP 7.3 over 5.6 when executing those commands. I'm not sure how that works though.

**Comment by Ethratian** [comment]
I got one step further by using the command

**composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 5.0.4 --ignore-platform-reqs**

which leads to

Installing grumpydictator/firefly-iii (5.0.4)
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
  - Installing grumpydictator/firefly-iii (5.0.4): Loading from cache
Created project in firefly-iii
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php -r "if (!(getenv('DYNO'))===false){file_exists('.env') || copy('.deploy/heroku/.env.heroku', '.env');copy('.deploy/heroku/.locales', '.locales');}"
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 87 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-ctype (v1.13.1): Loading from cache
  - Installing phpoption/phpoption (1.7.2): Loading from cache
  - Installing vlucas/phpdotenv (v3.6.0): Loading from cache
  - Installing symfony/css-selector (v5.0.3): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.2): Loading from cache
  - Installing symfony/polyfill-php72 (v1.13.1): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.13.1): Loading from cache
  - Installing symfony/var-dumper (v4.4.3): Loading from cache
  - Installing symfony/routing (v4.4.3): Loading from cache
  - Installing symfony/process (v4.4.3): Loading from cache
  - Installing symfony/polyfill-php73 (v1.13.1): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.13.1): Loading from cache
  - Installing symfony/mime (v5.0.3): Loading from cache
  - Installing symfony/http-foundation (v4.4.3): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.7): Loading from cache
  - Installing symfony/event-dispatcher (v4.4.3): Loading from cache
  - Installing psr/log (1.1.2): Loading from cache
  - Installing symfony/debug (v4.4.3): Loading from cache
  - Installing symfony/error-handler (v4.4.3): Loading from cache
  - Installing symfony/http-kernel (v4.4.3): Loading from cache
  - Installing symfony/finder (v4.4.3): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/service-contracts (v2.0.1): Loading from cache
  - Installing symfony/console (v4.4.3): Loading from cache
  - Installing symfony/polyfill-iconv (v1.13.1): Loading from cache
  - Installing doctrine/lexer (1.2.0): Loading from cache
  - Installing egulias/email-validator (2.1.15): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.3): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing ramsey/uuid (3.9.2): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing opis/closure (3.5.1): Loading from cache
  - Installing symfony/translation-contracts (v2.0.1): Loading from cache
  - Installing symfony/translation (v4.4.3): Loading from cache
  - Installing nesbot/carbon (2.29.1): Loading from cache
  - Installing monolog/monolog (2.0.2): Loading from cache
  - Installing league/flysystem (1.0.63): Loading from cache
  - Installing league/commonmark (1.2.2): Loading from cache
  - Installing league/commonmark-ext-table (v2.1.0): Loading from cache
  - Installing dragonmantank/cron-expression (v2.3.0): Loading from cache
  - Installing doctrine/inflector (1.3.1): Loading from cache
  - Installing laravel/framework (v6.12.0): Loading from cache
  - Installing tightenco/collect (v6.12.0): Loading from cache
  - Installing adldap2/adldap2 (v10.2.2): Loading from cache
  - Installing adldap2/adldap2-laravel (v6.0.8): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.5.2): Loading from cache
  - Installing bunq/sdk_php (dev-master 9f4ce9a): Loading from cache
  - Installing facade/ignition-contracts (1.0.0): Loading from cache
  - Installing davejamesmiller/laravel-breadcrumbs (5.3.2): Loading from cache
  - Installing doctrine/event-manager (1.1.0): Loading from cache
  - Installing doctrine/cache (1.10.0): Loading from cache
  - Installing doctrine/dbal (v2.10.1): Loading from cache
  - Installing fideloper/proxy (4.2.2): Loading from cache
  - Installing symfony/polyfill-util (v1.13.1): Loading from cache
  - Installing symfony/polyfill-php56 (v1.13.1): Loading from cache
  - Installing paragonie/constant_time_encoding (v2.3.0): Loading from cache
  - Installing pragmarx/google2fa (v7.0.0): Loading from cache
  - Installing bacon/bacon-qr-code (1.0.3): Loading from cache
  - Installing pragmarx/google2fa-qrcode (v1.0.3): Loading from cache
  - Installing jc5/google2fa-laravel (2.0.4): Loading from cache
  - Installing laminas/laminas-zendframework-bridge (1.0.1): Loading from cache
  - Installing symfony/psr-http-message-bridge (v1.3.0): Loading from cache
  - Installing phpseclib/phpseclib (2.0.23): Loading from cache
  - Installing league/event (2.2.0): Loading from cache
  - Installing lcobucci/jwt (3.3.1): Loading from cache
  - Installing defuse/php-encryption (v2.2.1): Loading from cache
  - Installing league/oauth2-server (8.0.0): Loading from cache
  - Installing psr/http-factory (1.0.1): Loading from cache
  - Installing laminas/laminas-diactoros (2.2.2): Loading from cache
  - Installing firebase/php-jwt (v5.0.0): Loading from cache
  - Installing laravel/passport (v8.2.0): Loading from cache
  - Installing laravelcollective/html (v6.0.3): Loading from cache
  - Installing league/csv (9.5.0): Loading from cache
  - Installing league/flysystem-replicate-adapter (1.0.1): Loading from cache
  - Installing league/flysystem-sftp (1.0.22): Loading from cache
  - Installing league/fractal (0.18.0): Loading from cache
  - Installing litipk/flysystem-fallback-adapter (0.1.3): Loading from cache
  - Installing mschindler83/fints-hbci-php (1.0.4): Loading from cache
  - Installing pragmarx/random (v0.2.2): Loading from cache
  - Installing pragmarx/recovery (v0.1.0): Loading from cache
  - Installing predis/predis (v1.1.1): Loading from cache
  - Installing twig/twig (v2.12.3): Loading from cache
  - Installing rcrowe/twigbridge (v0.11.2): Loading from cache
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /volume1/web/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Collection.php on line 103

Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /volume1/web/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Collection.php on line 103

As i understand it, there is an error in line 103 of the file Collection.php. Line 100-122 (line 123 is bold) within this file are

 public function median($key = null)
    {
        $values = (isset($key) ? $this->pluck($key) : $this)
            **->filter(function ($item) {**
                return ! is_null($item);
            })->sort()->values();

        $count = $values->count();

        if ($count === 0) {
            return;
        }

        $middle = (int) ($count / 2);

        if ($count % 2) {
            return $values->get($middle);
        }

        return (new static([
            $values->get($middle - 1), $values->get($middle),
        ]))->average();
    }

Any suggestions?

**Comment by JC5** [comment]
The commands are still executed under the PHP 5.x libraries. The code however, requires PHP7.x.
