### ISSUE TITLE
Better handling of reconciled transfer transactions

### ISSUE THREAD

**Issue by DocCyblade** [firefly-iii/firefly-iii#3078]
**Description**

Running v4.8.2

My wife and I (mostly my wife) has found an an issue. I told her it is the way it works but it does make it hard to reconcile an accounts.

Example:
She reconciled the credit card account. All is well! She moved to reconcile the checking account but alas the amounts on the screen does not match the checking account statement from the bank because the credit card payment (transfer) was marked as reconciled.

(Technically this is correct as it it cleared on one of the side it should have cleared on the other)

So here in the states of the America, we would mark a transaction in three ways, entered, cleared, and reconciled. Our work flow has always been to mark things as cleared once we know it was cleared the bank (looking on line or importing transactions). Then once we get the statement from the bank we reconcile the account and mark them as such.

**Solution**

I did not take a look under the hood at the transaction flags and how the reconcile feature handles them but if you could instead of marking the other side of the transaction as reconciled mark it has cleared. maybe even having the feature of marking transactions as cleared as well. Then when reconciling an account you could filter out by the reconciled flag and or cleared.

Or easier yet just don’t mark the other side as reconciled!

**What are alternatives?**

As a work around she does the following

- Just use a balance adjustment and remove it

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
> She moved to reconcile the checking account but alas the amounts on the screen does not match the checking account statement from the bank because the credit card payment (transfer) was marked as reconciled.

I don't get this part. If I reconcile a transfer in one account, it is indeed also reconciled in the other one but that doesn't give me problems.

**Comment by DocCyblade** [comment]
I’ll get my demo site up and see if I can get some screen shots of what we are seeing.
