### ISSUE TITLE
Add running version on page footer on mobile view

### ISSUE THREAD

**Issue by DocCyblade** [firefly-iii/firefly-iii#3079]
**Description**

 Show the version in mobile view. Seems to be cut off on phone views 

**Solution**

**What are alternatives?**

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
I like to keep the mobile layout as clean as possible. I'll see what I can do but no promises.

**Comment by SuperSandro2000** [comment]
If you scroll completely down then the version should be there on mobile.

**Comment by JC5** [comment]
Will be fixed in the next release.
