### ISSUE TITLE
Dashboard: Highlight hovered transaction in account summary graph

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#3081]
**Description**
It can be difficult to match transactions shown on the dashboard to the summary graph.

**Solution**
It would be nice if the hovered transaction were highlighted in the graph in some way.

**What are alternatives?**
Showing transaction dates could also help address this.

**Comment by JC5** [comment]
That's going to be tricky, matching event handlers from the chart to the list of transactions. No promises.

**Comment by JC5** [comment]
Sorry, this isn't something I'm going to add in the current layout. It adds too many events, triggers, lists, etc etc. And it's hard to do with overlapping dates and mixing accounts.
