### ISSUE TITLE
Create rule based on transaction button links to delete action

### ISSUE THREAD

**Issue by Tieno** [firefly-iii/firefly-iii#3082]
**Bug description**
Create rule based on transaction button links to delete action

Screenshot from https://demo.firefly-iii.org/

![image](https://user-images.githubusercontent.com/977414/73747275-66c2f100-4757-11ea-98db-59fab7fb3758.png)

**Comment by JC5** [comment]
Nice find. Luckily the demo site runs on the `develop`-branch. Fixed!
