### ISSUE TITLE
Sorting on category name does not work in default report

### ISSUE THREAD

**Issue by sboele** [firefly-iii/firefly-iii#3083]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is: Sorting on category name does not work in the default report.

![firefly_sort_bug](https://user-images.githubusercontent.com/1193437/73781838-4152d900-4791-11ea-97c9-223a27a471a5.JPG)

**Steps to reproduce**

Create a default report
Try to sort a-z or z-a on categories
It does not sort on category names, sorting on expenses/month or sum works

**Extra info**

Debug information generated at 2020-02-04 20:55:53 Europe/Amsterdam for Firefly III version **4.8.2**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.2 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.11-1\~deb10u1 |
| Display errors | Off |
| Session start | 2020-02-01 00:00:00 |
| Session end | 2020-02-29 23:59:59 |
| Session first | 2019-11-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, ps, readline, sass, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tideways, tokenizer, uploadprogress, wddx, xmlreader, xmlwriter, xsl, zip, ds, libsmbclient, Zend OPcache |

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for letting me know. Should be easy to fix.

**Comment by JC5** [comment]
This will be fixed in the next release.
