### ISSUE TITLE
Missing translation when adding a new transaction

### ISSUE THREAD

**Issue by sboele** [firefly-iii/firefly-iii#3084]
**Bug description**
I am running Firefly III version 4.8.2, and my problem is: There is a missing translation when adding a new transaction

**Steps to reproduce**

See screenshots, small issue
![firefly_missing_translation](https://user-images.githubusercontent.com/1193437/73783288-b8896c80-4793-11ea-8713-3e493a641281.png)
![firefly_missing_translation_2](https://user-images.githubusercontent.com/1193437/73783305-bfb07a80-4793-11ea-834d-0814fa29d2e9.JPG)

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
This will be fixed in the next release, although not all translations may be complete when the new release comes out.

**Comment by JC5** [comment]
This issue will be closed, now that the first alpha of 5.1.0 is out. Keep an eye out on the release page. If something comes up, please open a new issue. Thanks!
