### ISSUE TITLE
Create Transaction buttons from Account overview page

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#3085]
Quite often when I am checking my accounts I end up in the Asset Account overview page, where I have the big graph and the list of transactions. 

I am not sure if this is just me, but I would really really like if I had the Create New Expense, Create New Deposit, Create New Transfer directly from this page (which would in turn automatically populate the correct field to the current account in the following page. 

Many times I want to do this but then I have to go back in the transactions menu, which in turns changes page making me lose track of my overview. 

Mockup: https://imgur.com/a/ynV5so5

**Comment by JC5** [comment]
Adding info from context is on the list somewhere. I can’t find it. Until then, is the + button in the top right corner an alternative? 

Extra buttons can always be arranged of course :)

**Comment by AlexKalopsia** [comment]
Oh wow, since I've started using FireFly I've never realized there was a right sidebar :O I think that will do just fine for now, thank you! Can I then add as a suggestion to give an option to keep the right sidebar open in the preferences? I have lots of unused horizontal space right now
