### ISSUE TITLE
Help understanding how to use piggy banks

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#3086]
I'm having a bit of a hard time understanding how I am supposed to use piggy banks. I think biggest culprit of this is that I am not sure why the piggy bank is linked to my current amount of money in the account. 

Last week I moved 1000€ to my savings. I realized that I didn't update my piggy bank (which is 2020 Yearly Savings), and now I can't add that sum to the piggy bank anymore (since now I have less than 1000 in my checking). 

What's the "correct" workflow, and can I not add old data to the piggy bank now?

**Comment by JC5** [comment]
Does this page help?

https://docs.firefly-iii.org/advanced-concepts/piggies

**Comment by AlexKalopsia** [comment]
I think this helps yes, as in I should link the piggybank directly to my savings account, and then use that one as the source of the piggy bank rather than the checking one

**Comment by JC5** [comment]
Exactly :+1:
