### ISSUE TITLE
Getting error when trying to open expense account: ....failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by much-doge** [firefly-iii/firefly-iii#3087]
I am running Firefly III version 5.0.4

**Description**
I get this error when i tried to open my expense account:
> file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/22/8d/228d5e9bbaade1bfdc2ebe8a2dddcd3742bb5cfe): failed to open stream: No such file or directory 

**Extra info**
OS: Fedora 30
browser: firefox 72
 

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files (see https://bit.ly/FF3-get-logs)
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Was this FAQ entry of any help? https://docs.firefly-iii.org/faq/self_hosted#unable-to-write-to-cache-directory

Otherwise some tips  may be found here: https://github.com/firefly-iii/firefly-iii/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+file_put_contents

**Comment by much-doge** [comment]
Thanks... I created folder `8d` inside `storage/framework/cache/data/22` and it seems to fix the problem. 

I still not sure tho, the parent folder `22` was owned by root despite all the others having the right ownership, so I had to change the ownership to www-data
