### ISSUE TITLE
Spectre import no longer deduplicating

### ISSUE THREAD

**Issue by alexolivier** [firefly-iii/firefly-iii#3088]
**Bug description**
I am running Firefly III version 5.0.4, and my problem is:

When I import transaction via Spectre it is no longer detecting duplicates 

**Steps to reproduce**
- Setup a Spectre integration
- Import from a bank account
- Import again and the same transactions will be imported

Pre-this version it would detect the duplicates and not import them. Now I have hundreds of transactions to remove.

**Extra info**

Debug information generated at 2020-02-06 09:30:09 Europe/London for Firefly III version **5.0.4**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.4 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.14 |
| Display errors | Off |
| Session start | 2020-02-01 00:00:00 |
| Session end | 2020-02-29 00:00:00 |
| Session first | 2019-10-31 00:00:00 |a
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for reporting. If you compare two duplicates side by side, do you see any fields that are different?

**Comment by alexolivier** [comment]
In the UI they look exactly the same (date, amount, External ID, notes) - haven't checked in the DB though

**Comment by JC5** [comment]
OK. In that case, we need to dive deeper. Can you import from Spectre twice, and collect log files? I'm curious if you can match one transaction from both runs in the log files.

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://docs.firefly-iii.org/contact/contact).

**Comment by alexolivier** [comment]
Emailed!

**Comment by JC5** [comment]
Thanks. Three months ago, I don't think you recall which version you were been using?

**Comment by alexolivier** [comment]
Sorry I meant it has pulled 3 months worth of transaction in even though all except the last couple of days have been imported already but it didn't detect the dupes.

**Comment by JC5** [comment]
I see what you mean. Scanning through your code I see that the second one is apparently blocked, correctly, but the first one is stored. You don't happen to have logs for the original first entry, right? 

In any case, I've been working on a "debug view" for transactions. You can see it on the demo site by changing "show" into "debug":

1. https://demo.firefly-iii.org/transactions/show/110
2. https://demo.firefly-iii.org/transactions/debug/110

It's not much consolation for now, but I hope it will help to find the issue.

**Comment by JC5** [comment]
The debug view will be in place in the next release. Could you let me know, by the time its out, what the results are?

**Comment by alexolivier** [comment]
I've been digging a bit more. I've pulled out two duplicate transactions from the database. Notable here is that the reported `external_id` is the same but the hash it stores is different.

I can only assume the `import_hash_v2` is used to de-dupe? This would, therefore, mean Spectre is returning data in a different format?

```
id	created_at	updated_at	transaction_journal_id	name	data	hash	deleted_at
1650	2020-02-04 21:46:59	2020-02-04 21:46:59	1052	import_hash_v2	"89d1d7f6cf551b382a83976cdac47e495fbc6c50494f66a7f9e0f62d8aaff4b8"	4956025ff23f928e4b150e26154623af47fb056a4f78f6f0a1ab6299c662fc0a	NULL
1651	2020-02-04 21:46:59	2020-02-04 21:46:59	1052	external_id	"2248514296"	675e5fed8f5560b57193d1182b48f1a40789b6eb6b270b751f5c02506914733d	NULL
2634	2020-02-06 09:26:24	2020-02-06 09:26:24	1544	import_hash_v2	"cd8dc31d729f36f9a4fe43b830f809e8f8d813470478125d6d1a567faca32b1d"	0b0f53213077cf38632deb0b1e4b815dcf6eaac27ee74803be885f787143d013	NULL
2635	2020-02-06 09:26:24	2020-02-06 09:26:24	1544	external_id	"2248514296"	675e5fed8f5560b57193d1182b48f1a40789b6eb6b270b751f5c02506914733d	NULL
```

**Comment by JC5** [comment]
It seems so. The hash is based on all the fields stored before the transaction is saved. Some fields are excluded (like Firefly III's version). Once the new release has the "debug" view mentioned before, we can do some serious debugging.

**Comment by filipe-silva** [comment]
Hi, quick question, so I did the import (on 5.0.3) and it created duplicates as well.
But I did have some differences on the transactions, like the category and account source, does it always duplicate if one of those is different?
Also off-topic, but can we ignore spectre categories on import? It keeps creating them and I have my own

**Comment by JC5** [comment]
OK, let's see what the difference later on. And yes, if those are different then Firefly III will duplicate them. The import is everything-or-nothing, and this includes Spectre categories. You can remove them using rules though.

**Comment by filipe-silva** [comment]
Alright, thanks.
I did create a rule for removing the categories, but it created the categories nonetheless. I wanted to avoid that, I might create a custom import routine to avoid that. 
@JC5 would you be interested in having like a button on the spectre routine like "ignore categories"?

**Comment by alexolivier** [comment]
I think this query finds all the duplicated:

```sql
select transaction_journal_id from (
select 
created_at, 
data, 
transaction_journal_id,
ROW_NUMBER() OVER (
          PARTITION BY data 
          ORDER BY created_at asc) as rn
from journal_meta where name = 'external_id') a where a.rn > 1 order by transaction_journal_id desc
```

**Comment by alexolivier** [comment]
> Alright, thanks.
> I did create a rule for removing the categories, but it created the categories nonetheless. I wanted to avoid that, I might create a custom import routine to avoid that.
> @JC5 would you be interested in having like a button on the spectre routine like "ignore categories"?

Or an option to dedupe based on external_id

**Comment by alexolivier** [comment]
@JC5 how was this resolved out of interest? I'm still getting dupes even on latest build so maybe I need to change something?

**Comment by JC5** [comment]
No this should work in 5.1.0. But the newest release has a debug view that could show what the differences are (and possibly, other bugs):

Use the following URL on your own installation: 

1. `http://example.com/transactions/debug/298`
2. `http://example.com/transactions/debug/411`

Replace both ID's with a new duplicate and the original transaction.
