### ISSUE TITLE
New Docker install, permissions issue with log files

### ISSUE THREAD

**Issue by ndaringer** [firefly-iii/firefly-iii#3090]
I was getting the "Whoops. Fatal error" message after a fresh install from dockerhub.

Followed [this comment ](https://github.com/firefly-iii/firefly-iii/issues/1320#issuecomment-379272226)and now Firefly III seems to be working. 

running this from the docker console is what fixed it.
`chown -R www-data: /var/www/firefly-iii/storage/logs/ `

I do have that directory passed through as a persistent volume, if that makes a difference.

**Comment by JC5** [comment]
Thanks for letting me know. It shouldn't matter, but I've tweaked some commands in the entrypoint script for future pulls of the Docker image.
