### ISSUE TITLE
Transaction Import always todays date

### ISSUE THREAD

**Issue by asg-trifork** [firefly-iii/firefly-iii#3092]
**Bug description**
I am running Firefly III version 5.0.4, and my problem is:

When I try to import a CVS file from my bank (Nordjyske bank, Danish) the date of the transactions is always todays date(date of upload).
Everything else is working flawlessly, mapping of accounts, categories, etc.

**Steps to reproduce**
Login to Firefly UI.
Select Import and export > Import transactions.
Select Import File icon.
Choose CSV file (attached).
Choose Configuration file (attached).
Click Upload Files.
Click Continue.
Click Continue.
Once processing completes I select the new tag to view my imported data.

**Expected behaviour**
The date of the transactions should match the first column in the CSV-file, not the date I made the import.

**Extra info**
Firefly is running on docker, with the `docker-compose.yaml` and `.env` provided in the documentation. \
The host machine is running Ubuntu 18.04 LTS.

In the import config I have setup the date format as:\
`dd.mm.YYYY`

- Config file attached.
- Test CSV file attached.
- Screenshots of import setup
- Screenshots of imported transactions.

**Bonus points**

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**import config***
```{
    "file-type": "csv",
    "date-format": "dd.mm.YYYY",
    "has-headers": true,
    "delimiter": ";",
    "apply-rules": true,
    "specifics": [],
    "import-account": 1,
    "column-count": 13,
    "column-roles": [
        "date-transaction",
        "_ignore",
        "description",
        "_ignore",
        "amount",
        "external-id",
        "_ignore",
        "_ignore",
        "_ignore",
        "account-name",
        "_ignore",
        "tags-comma",
        "category-name"
    ],
    "column-do-mapping": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true
    ],
    "column-mapping-config": {
        "9": {
            "Dankort": 1
        },
        "12": {
            "Andet": 9,
            "Aviser, blade og b\ufffdger": 15,
            "Caf\ufffd, restaurant og bar": 10,
            "Dagligvarer": 7,
            "Film, musik, apps og software": 11,
            "H\ufffdr- og hudpleje": 17,
            "Ingen kategori": 1,
            "Kontanter": 12,
            "L\ufffdn, dagpenge og pension": 2,
            "Opsparing": 5,
            "Overf\ufffdrsel": 14,
            "Overf\ufffdrsel mellem egne konti": 4,
            "Take away og fast food": 3,
            "Tandl\ufffdge, l\ufffdge og medicin": 19,
            "Taxa og offentlig transport": 13,
            "Telefon, internet, streaming og TV": 16,
            "T\ufffdj, sko og accessories": 8,
            "Vedligeholdelse": 18,
            "V\ufffdrdipapirer": 6
        }
    }
}
```
**CSV file***
[Download](https://we.tl/t-fapAar3OYW)

![setup1](https://user-images.githubusercontent.com/39047394/74023311-a714b000-499f-11ea-9f62-07d5804d6d46.png)
![setup2](https://user-images.githubusercontent.com/39047394/74023314-abd96400-499f-11ea-8301-f3036e8345b9.png)
![transactions-result](https://user-images.githubusercontent.com/39047394/74023326-b3007200-499f-11ea-851e-fc039dc3e11a.png)

**Comment by JC5** [comment]
Thanks for the expanded issue report!

As described under the date field in your screenshot, please use [PHP's date format](https://www.php.net/manual/en/function.date.php) to format your date. In your case, I suspect `d.m.Y` should do the trick.

**Comment by asg-trifork** [comment]
It works! Can't believe I didn't catch that, read the PHP datetime format several times to make sure. Guess I'm too used to other languages formats...
Thanks for the help

**Comment by JC5** [comment]
No problem, glad to hear it works!
