### ISSUE TITLE
Dashboard graph and archived accounts

### ISSUE THREAD

**Issue by UhtredTheBold** [firefly-iii/firefly-iii#3093]
**Bug description**
I am running Firefly III version 5.0.1 and I've noticed that when I click 'everything' and review the dashboard graph it goes back to April 2017 and yet shows all accounts a zero until September 2017 when my transactions start.

This is because I have an account which has data going back to April 2017. This account is archived and so it is not shown on the dashboard graph, however it still affects the graph start date.

I hope I have explained this clearly.

**Steps to reproduce**
Create an account and enter a transaction from jan 1st 2015. Create a second account and create a transaction from jan 1st 2020. Archive the 1st account and review the dashboard graph being sure to click 'everything'. You should see the graph starts at 2015 but shows no active data until 2020.

**Extra info**
Debug information generated at 2020-02-07 11:20:05 UTC for Firefly III version **5.0.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.1 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.13 |
| Display errors | Off |
| Session start | 2017-04-05 00:00:00 |
| Session end | 2020-02-07 00:00:00 |
| Session first | 2017-04-05 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

Chrome/Windoes 10

**Bonus points**

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [ ] I have added a screenshot.
- [x ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by UhtredTheBold** [comment]
Sorry - an important point, this is for a liability not asset account

**Comment by JC5** [comment]
Yes. Everything means everything. It doesn't matter that the account isn't visible on the front page, because it also affects the budget and category charts.

Assuming you mean this "everything":

<img width="279" alt="Screen Shot 2020-02-08 at 06 14 48" src="https://user-images.githubusercontent.com/5889984/74079622-543c0680-4a3a-11ea-9cda-3b4b5023ed64.png">

**Comment by UhtredTheBold** [comment]
Yes that's the one. It is expected then :)
