### ISSUE TITLE
Porblem connecting to database

### ISSUE THREAD

**Issue by nunoadferreira** [firefly-iii/firefly-iii#3095]
Hi all,

I am trying to install the firefly in my VPS server, however, I am having troubles during the start-up. It seems firefly isn't able to connect to Postgres database.

Below I left my docker-compose file, .env file and container log. Please help me to solve the problem.
My files are an exactly copy of the example ones.

### Docker-compose file:
 ```
cat docker-compose.yml
---
networks:
  firefly_iii_net:
    driver: bridge
services:
  firefly_iii_app:
    image: jc5x/firefly-iii:latest
    depends_on:
      - firefly_iii_db
    networks:
      - firefly_iii_net
    ports:
      - "80:80"
    env_file: .env
    volumes:
      -
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      -
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db:
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=secret_firefly_password
      - POSTGRES_USER=firefly
    networks:
      - firefly_iii_net
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data
version: "3.2"
volumes:
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```
`

### :env file:
```
` cat .env
# You can leave this on "local". If you change it to production most console commands will ask for extra confirmation.
# Never set it to "testing".
APP_ENV=local

# Set to true if you want to see debug information in error screens.
APP_DEBUG=false

# This should be your email address.
# If you use Docker or similar, you can set this variable from a file by using SITE_OWNER_FILE
SITE_OWNER=mail@example.com

# The encryption key for your sessions. Keep this very secure.
# If you generate a new one existing data must be considered LOST.
# Change it to a string of exactly 32 chars or use something like `php artisan key:generate` to generate it.
# If you use Docker or similar, you can set this variable from a file by using APP_KEY_FILE
APP_KEY=SomeRandomStringOf32CharsExactly


# Change this value to your preferred time zone.
# Example: Europe/Amsterdam
TZ=Europe/Amsterdam

# This variable must match your installation's external address but keep in mind that
# it's only used on the command line as a fallback value.
APP_URL=http://localhost

# TRUSTED_PROXIES is a useful variable when using Docker and/or a reverse proxy.
# Set it to ** and reverse proxies work just fine.
TRUSTED_PROXIES=

# The log channel defines where your log entries go to.
# - Docker + versions <= 4.8.1.8 and before: use "stdout"
# - Docker + versions >  4.8.1.8: use "docker_out"
# - For everything else, use 'daily'

# Several other options exist. You can use 'single' for one big fat error log (not recommended).
# Also available are 'syslog', 'errorlog' and 'stdout' which will log to the system itself.
# A rotating log option is 'daily', creates 5 files that (surprise) rotate.
# Default setting 'stack' will log to 'daily' and to 'stdout' at the same time.
LOG_CHANNEL=stack

# Log level. You can set this from least severe to most severe:
# debug, info, notice, warning, error, critical, alert, emergency
# If you set it to debug your logs will grow large, and fast. If you set it to emergency probably
# nothing will get logged, ever.
APP_LOG_LEVEL=notice

# Database credentials. Make sure the database exists. I recommend a dedicated user for Firefly III
# For other database types, please see the FAQ: https://docs.firefly-iii.org/support/faq
# If you use Docker or similar, you can set these variables from a file by appending them with _FILE
DB_CONNECTION=pgsql
DB_HOST=firefly_iii_db
DB_PORT=5432
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD=secret_firefly_password

# PostgreSQL supports SSL. You can configure it here.
# If you use Docker or similar, you can set these variables from a file by appending them with _FILE
PGSQL_SSL_MODE=prefer
PGSQL_SSL_ROOT_CERT=null
PGSQL_SSL_CERT=null
PGSQL_SSL_KEY=null
PGSQL_SSL_CRL_FILE=null

# If you're looking for performance improvements, you could install memcached.
CACHE_DRIVER=file
SESSION_DRIVER=file

# If you set either of these to 'redis', you might want to update these settings too
# If you use Docker or similar, you can set REDIS_HOST_FILE, REDIS_PASSWORD_FILE or
# REDIS_PORT_FILE to set the value from a file instead of from an environment variable
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
REDIS_DB="0" # always use quotes
REDIS_CACHE_DB="1"

# Cookie settings. Should not be necessary to change these.
# If you use Docker or similar, you can set COOKIE_DOMAIN_FILE to set
# the value from a file instead of from an environment variable
COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false
```

### Logs

> firefly_iii_app_1  | 2020-02-07T22:31:19.535895860Z Now in entrypoint.sh for Firefly III
> firefly_iii_app_1  | 2020-02-07T22:31:19.535953213Z Entrypoint script version is 1.0.1
> firefly_iii_app_1  | 2020-02-07T22:31:19.535961591Z Now parsing _FILE variables.
> firefly_iii_app_1  | 2020-02-07T22:31:19.544522155Z done!
> firefly_iii_app_1  | 2020-02-07T22:31:19.544546557Z Making directories...
> firefly_iii_app_1  | 2020-02-07T22:31:19.727232186Z Touch DB file (if SQLite)...
> firefly_iii_app_1  | 2020-02-07T22:31:19.727262391Z Run chown on /var/www/firefly-iii/storage...
> firefly_iii_app_1  | 2020-02-07T22:31:19.832789993Z Run chmod on /var/www/firefly-iii/storage...
> firefly_iii_app_1  | 2020-02-07T22:31:19.835059893Z Remove log file...
> firefly_iii_app_1  | 2020-02-07T22:31:19.836737762Z Dump auto load...
> firefly_iii_db_1   | 2020-02-07T22:31:15.281681700Z The files belonging to this database system will be owned by user "postgres".
> firefly_iii_db_1   | 2020-02-07T22:31:15.281717775Z This user must also own the server process.
> firefly_iii_db_1   | 2020-02-07T22:31:15.281723057Z
> firefly_iii_db_1   | 2020-02-07T22:31:15.289577231Z The database cluster will be initialized with locale "en_US.utf8".
> firefly_iii_db_1   | 2020-02-07T22:31:15.289611525Z The default database encoding has accordingly been set to "UTF8".
> firefly_iii_db_1   | 2020-02-07T22:31:15.289616231Z The default text search configuration will be set to "english".
> firefly_iii_db_1   | 2020-02-07T22:31:15.289619554Z
> firefly_iii_db_1   | 2020-02-07T22:31:15.289622700Z Data page checksums are disabled.
> firefly_iii_db_1   | 2020-02-07T22:31:15.289625964Z
> firefly_iii_db_1   | 2020-02-07T22:31:15.289641020Z fixing permissions on existing directory /var/lib/postgresql/data ... ok
> firefly_iii_db_1   | 2020-02-07T22:31:15.289644228Z creating subdirectories ... ok
> firefly_iii_db_1   | 2020-02-07T22:31:15.389014162Z selecting default max_connections ... 100
> firefly_iii_db_1   | 2020-02-07T22:31:15.422053390Z selecting default shared_buffers ... 128MB
> firefly_iii_db_1   | 2020-02-07T22:31:15.467854885Z selecting default timezone ... Etc/UTC
> firefly_iii_db_1   | 2020-02-07T22:31:15.467878173Z selecting dynamic shared memory implementation ... posix
> firefly_iii_db_1   | 2020-02-07T22:31:15.471486491Z creating configuration files ... ok
> firefly_iii_db_1   | 2020-02-07T22:31:15.753624858Z running bootstrap script ... ok
> firefly_iii_db_1   | 2020-02-07T22:31:19.830938992Z performing post-bootstrap initialization ... ok
> firefly_iii_db_1   | 2020-02-07T22:31:19.927464136Z syncing data to disk ... ok
> firefly_iii_db_1   | 2020-02-07T22:31:19.927512271Z
> firefly_iii_db_1   | 2020-02-07T22:31:19.927524630Z WARNING: enabling "trust" authentication for local connections
> firefly_iii_db_1   | 2020-02-07T22:31:19.927528995Z You can change this by editing pg_hba.conf or using the option -A, or
> firefly_iii_db_1   | 2020-02-07T22:31:19.927532878Z --auth-local and --auth-host, the next time you run initdb.
> firefly_iii_db_1   | 2020-02-07T22:31:19.931135578Z
> firefly_iii_db_1   | 2020-02-07T22:31:19.931154722Z Success. You can now start the database server using:
> firefly_iii_db_1   | 2020-02-07T22:31:19.931159024Z
> firefly_iii_db_1   | 2020-02-07T22:31:19.931162643Z     pg_ctl -D /var/lib/postgresql/data -l logfile start
> firefly_iii_db_1   | 2020-02-07T22:31:19.931166428Z
> firefly_iii_db_1   | 2020-02-07T22:31:20.087128844Z waiting for server to start....2020-02-07 22:31:20.086 UTC [43] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> firefly_iii_db_1   | 2020-02-07T22:31:20.121697517Z 2020-02-07 22:31:20.121 UTC [44] LOG:  database system was shut down at 2020-02-07 22:31:19 UTC
> firefly_iii_db_1   | 2020-02-07T22:31:20.147292876Z 2020-02-07 22:31:20.145 UTC [43] LOG:  database system is ready to accept connections
> firefly_iii_db_1   | 2020-02-07T22:31:20.162260154Z  done
> firefly_iii_db_1   | 2020-02-07T22:31:20.162282015Z server started
> firefly_iii_db_1   | 2020-02-07T22:31:20.735900653Z CREATE DATABASE
> firefly_iii_db_1   | 2020-02-07T22:31:20.735923708Z
> firefly_iii_db_1   | 2020-02-07T22:31:20.740230261Z
> firefly_iii_db_1   | 2020-02-07T22:31:20.740244672Z /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
> firefly_iii_db_1   | 2020-02-07T22:31:20.740258123Z
> firefly_iii_db_1   | 2020-02-07T22:31:20.740261637Z waiting for server to shut down....2020-02-07 22:31:20.739 UTC [43] LOG:  received fast shutdown request
> firefly_iii_db_1   | 2020-02-07T22:31:20.746053473Z 2020-02-07 22:31:20.741 UTC [43] LOG:  aborting any active transactions
> firefly_iii_db_1   | 2020-02-07T22:31:20.746070469Z 2020-02-07 22:31:20.745 UTC [43] LOG:  worker process: logical replication launcher (PID 50) exited with exit code 1
> firefly_iii_db_1   | 2020-02-07T22:31:20.746074579Z 2020-02-07 22:31:20.745 UTC [45] LOG:  shutting down
> firefly_iii_db_1   | 2020-02-07T22:31:20.757781358Z 2020-02-07 22:31:20.756 UTC [43] LOG:  database system is shut down
> firefly_iii_db_1   | 2020-02-07T22:31:20.841610968Z  done
> firefly_iii_db_1   | 2020-02-07T22:31:20.841634464Z server stopped
> firefly_iii_db_1   | 2020-02-07T22:31:20.841638472Z
> firefly_iii_db_1   | 2020-02-07T22:31:20.841641812Z PostgreSQL init process complete; ready for start up.
> firefly_iii_db_1   | 2020-02-07T22:31:20.841650225Z
> firefly_iii_db_1   | 2020-02-07T22:31:20.889923097Z 2020-02-07 22:31:20.889 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> firefly_iii_db_1   | 2020-02-07T22:31:20.889943706Z 2020-02-07 22:31:20.889 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> firefly_iii_db_1   | 2020-02-07T22:31:20.892079960Z 2020-02-07 22:31:20.891 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> firefly_iii_db_1   | 2020-02-07T22:31:20.917169977Z 2020-02-07 22:31:20.916 UTC [61] LOG:  database system was shut down at 2020-02-07 22:31:20 UTC
> firefly_iii_db_1   | 2020-02-07T22:31:20.926304461Z 2020-02-07 22:31:20.922 UTC [1] LOG:  database system is ready to accept connections
> firefly_iii_app_1  | 2020-02-07T22:31:24.721147820Z Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump                                                          Generated optimized autoload files containing 5346 classes
> firefly_iii_app_1  | 2020-02-07T22:31:24.929307865Z Discover packages...
> firefly_iii_app_1  | 2020-02-07T22:31:25.359225738Z Discovered Package: adldap2/adldap2-laravel
> firefly_iii_app_1  | 2020-02-07T22:31:25.362395611Z Discovered Package: davejamesmiller/laravel-breadcrumbs
> firefly_iii_app_1  | 2020-02-07T22:31:25.362412078Z Discovered Package: fideloper/proxy
> firefly_iii_app_1  | 2020-02-07T22:31:25.362416203Z Discovered Package: jc5/google2fa-laravel
> firefly_iii_app_1  | 2020-02-07T22:31:25.362420004Z Discovered Package: laravel/passport
> firefly_iii_app_1  | 2020-02-07T22:31:25.362427439Z Discovered Package: laravelcollective/html
> firefly_iii_app_1  | 2020-02-07T22:31:25.362431276Z Discovered Package: nesbot/carbon
> firefly_iii_app_1  | 2020-02-07T22:31:25.362442941Z Discovered Package: rcrowe/twigbridge
> firefly_iii_app_1  | 2020-02-07T22:31:25.362446728Z Package manifest generated successfully.
> firefly_iii_app_1  | 2020-02-07T22:31:25.385854323Z Wait for the database.
> firefly_iii_app_1  | 2020-02-07T22:31:25.405988503Z wait-for-it.sh: waiting 60 seconds for firefly_iii_db:5432
> firefly_iii_app_1  | 2020-02-07T22:32:25.401968377Z wait-for-it.sh: timeout occurred after waiting 60 seconds for firefly_iii_db:5432
> firefly_iii_app_1  | 2020-02-07T22:32:25.405142398Z DB is up. Time to execute artisan commands.
> firefly_iii_app_1  | 2020-02-07T22:32:25.405165548Z Run various artisan commands...
> firefly_iii_app_1  | 2020-02-07T22:32:25.830257644Z Application cache cleared!
> firefly_iii_app_1  | 2020-02-07T22:32:25.839578687Z Running migration commands...
> firefly_iii_app_1  | 2020-02-07T22:32:26.058838666Z CreateDB does not apply to "pgsql", skipped.
> firefly_iii_app_1  | 2020-02-07T22:32:27.326768470Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.326800179Z In Connection.php line 669:
> firefly_iii_app_1  | 2020-02-07T22:32:27.326806254Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.326810369Z   SQLSTATE[08006] [7] could not connect to server: No route to host
> firefly_iii_app_1  | 2020-02-07T22:32:27.326814235Z     Is the server running on host "firefly_iii_db" (172.18.0.2) and accepting
> firefly_iii_app_1  | 2020-02-07T22:32:27.326826099Z     TCP/IP connections on port 5432? (SQL: select * from information_schema.ta
> firefly_iii_app_1  | 2020-02-07T22:32:27.326829995Z   bles where table_schema = public and table_name = migrations and table_type
> firefly_iii_app_1  | 2020-02-07T22:32:27.326833337Z    = 'BASE TABLE')
> firefly_iii_app_1  | 2020-02-07T22:32:27.326836762Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.326840117Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.326843255Z In PDOConnection.php line 31:
> firefly_iii_app_1  | 2020-02-07T22:32:27.326846505Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.326849967Z   SQLSTATE[08006] [7] could not connect to server: No route to host
> firefly_iii_app_1  | 2020-02-07T22:32:27.326853255Z     Is the server running on host "firefly_iii_db" (172.18.0.2) and accepting
> firefly_iii_app_1  | 2020-02-07T22:32:27.326856782Z     TCP/IP connections on port 5432?
> firefly_iii_app_1  | 2020-02-07T22:32:27.326860157Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.326863665Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.326866798Z In PDOConnection.php line 27:
> firefly_iii_app_1  | 2020-02-07T22:32:27.326870015Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.326873329Z   SQLSTATE[08006] [7] could not connect to server: No route to host
> firefly_iii_app_1  | 2020-02-07T22:32:27.326876757Z     Is the server running on host "firefly_iii_db" (172.18.0.2) and accepting
> firefly_iii_app_1  | 2020-02-07T22:32:27.326880229Z     TCP/IP connections on port 5432?
> firefly_iii_app_1  | 2020-02-07T22:32:27.326883759Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.326887616Z
> firefly_iii_app_1  | 2020-02-07T22:32:27.533664251Z Going to decrypt the database.
> firefly_iii_app_1  | 2020-02-07T22:32:28.581720960Z
> firefly_iii_app_1  | 2020-02-07T22:32:28.611789530Z In Connection.php line 669:
> firefly_iii_app_1  | 2020-02-07T22:32:28.611808767Z
> firefly_iii_app_1  | 2020-02-07T22:32:28.611813342Z   SQLSTATE[08006] [7] could not connect to server: No route to host
> firefly_iii_app_1  | 2020-02-07T22:32:28.611816916Z     Is the server running on host "firefly_iii_db" (172.18.0.2) and accepting
> firefly_iii_app_1  | 2020-02-07T22:32:28.611821279Z     TCP/IP connections on port 5432? (SQL: select "id", "name", "data" from "c
> firefly_iii_app_1  | 2020-02-07T22:32:28.611825361Z   onfiguration" where "name" = is_decrypted_accounts and "configuration"."del

**Comment by JC5** [comment]
>  firefly_iii_app_1 | 2020-02-07T22:32:25.401968377Z wait-for-it.sh: timeout occurred after waiting 60 seconds for firefly_iii_db:5432

>  firefly_iii_app_1 | 2020-02-07T22:32:28.611813342Z SQLSTATE[08006] [7] could not connect to server: No route to host

I see the problem. Your Firefly III container can't reach the DB container. But I don't know the solution, because as far as I can tell the docker files are correct.

**Comment by nunoadferreira** [comment]
Is there anything I can do to get a better diagnose of the problem? One thing I didn't mention was that I am running docker in a CentOS 8 machine.

**Comment by Agraphie** [comment]
I tried your config locally and it works just fine. You could check 
1) `docker network ls` to see if the network is there (probably is)
2) Remember the `NETWORK ID` (most left column)
3) `ip addr` and look for the bridge with the id from above (e.g. br-abcdefg123) and IP range. The IP range possibly overlaps with another (private) IP range in the network.

**Comment by SuperSandro2000** [comment]
Also you could install the ``ping`` command and try to ping the DB.

**Comment by nunoadferreira** [comment]
Hello,
I found the problem was related to the CentOS firewall. I solved the issue by running the following command:

```
firewall-cmd --permanent --zone=trusted --add-interface=docker0
firewall-cmd --permanent --zone=trusted --add-interface=br-42fc55dfd856
firewall-cmd --reload
service firewalld restart
```

Hope this helps other users

**Comment by SuperSandro2000** [comment]
>firewall-cmd --permanent --zone=trusted --add-interface=br-42fc55dfd856

This is problematic cause the id's could change in the future.

**Comment by nunoadferreira** [comment]
Yes that was the way I was able to fix right now. Then I'll dig more to search a more definitive solution.

**Comment by ihendriks** [comment]
I ran into this issue as well. You can give the network a fixed name.

In your docker-compose add the following:

```yaml
networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: "docker-firefly"
```

Obviously the name "docker-firefly" can be whatever you want. Just use that name in your firewalld config, e.g. `firewall-cmd --permanent --zone=trusted --add-interface=docker-firefly`

You do **not** have to restart the docker service. 

Make sure to reload firewalld with `firewall-cmd --reload` afterwards. You might have to restart the docker containers, not sure.

Would probably be useful to have a note in the docs about this, but it's a "normal" issue when running docker on centos/rhel (or with firewalld, I suppose).
