### ISSUE TITLE
Creating piggy bank gives an error

### ISSUE THREAD

**Issue by McOrion** [firefly-iii/firefly-iii#3099]
I am running Firefly III version 5.0.4.

**Description**
I'm running Firefly in Docker on my Raspberry Pi 3.
Last week I migrated my data from a MariaDB on my NAS to a PostgreSQL, also in a Docker on my Pi. The data migration was done by exporting and importing each table as CSV. After importing I updated the sequences. It was quite some work, but Firefly ran without issues, except 1: piggy banks.

I had created 1 piggy bank on my old db, but it had no transactions. But opening it on the new db gave an error. So I removed the piggy bank from the database. After that I was able to create a new piggy bank in the regular way. But, as soon as I choose the Piggy Bank option from the Money Management menu, the same error occurred. 

To try to fix the problem, I upgraded Firefly from 5.0.1 to 5.0.4 as described in the upgrade instructions. This didn't remove the error. Where should I look to get it fixed?
[Firefly error.txt](https://github.com/firefly-iii/firefly-iii/files/4174152/Firefly.error.txt)

**Extra info**
Debug information generated at 2020-02-08 12:47:02 Europe/Amsterdam for Firefly III version **5.0.4**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.4 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.14 |
| Display errors | Off |
| Session start | 2020-02-01 00:00:00 |
| Session end | 2020-02-29 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [x] I added log files (see https://bit.ly/FF3-get-logs)
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
I think this is caused, ultimately, because a piggy bank is linked to an account with no currency set.

I'll dive into it. :)

**Comment by JC5** [comment]
To fix this for now, run this command on the command line:

`docker exec -it <container> sudo -u www-data php artisan firefly-iii:account-currencies`

**Comment by McOrion** [comment]
Great to have a response this fast! The fix didn't remove the error, but it got me to the right place. The issue was indeed with the accounts. I have 4 accounts: default asset, savings, credit card and cash. And after my db migration apparently all 4 had some sort of default firefly_role_... So editing all 4 accounts and giving them the proper role solved the issue. Thanks for pointing out!
