### ISSUE TITLE
initial account balances not in correct currency?

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3101]
<deleted>

**Comment by 4e868df3** [comment]
Update- it seems like all "initial balance accounts" default to euro when listing accounts through the API, which seems like a bug.

**Comment by 4e868df3** [comment]
Update- steps to reproduce this:

- delete firefly data + start over
- skip the intro screen (filling out the initial checking/savings fields also seems to cause this issue)
- create a default checking account and a first savings account
- create a second savings account ("BOA- Savings" in my case)
- import transactions through the API (maybe not required?)
- observe the following matrix:

account | initial-balance account type in API | asset account type in API | asset account in UI | correct currency
------------ | ------------- |  ------------- |  ------------- |  -------------
1st checking account | yes | no | yes | no
1st savings account | no | no | yes | N/A
2nd savings account | yes | yes | yes | yes
2nd checking account | yes | no | yes | yes

**Comment by JC5** [comment]
Initial balance accounts are created when you give your asset accounts an opening balance. In these cases, the money doesn't magic itself into your account,

**Comment by JC5** [comment]
Whoops, too early.

Anyway, the money doesn't magic itself into your account, a special "initial balance account" is created where the money comes from (or goes to). The transaction associated with this is an "opening balance" transaction and can't be edited. To update it, you'll need to edit the original account's opening balance.

For that reason, it doesn't matter that the opening balance account has another currency. It's unused anyway and invisible to the user.
