### ISSUE TITLE
2FA failes a couple of times before letting me in

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#3102]
**Bug description**
I am running Firefly III version 5.0.4, and every time I need to login with 2FA, Firefly tells me the code is wrong for a couple of times before it lets me in. Note that after a couple of attempts it lets me in with the same exact code, not with a new one. 

**Extra info**
I use Authy to handle the code generation and never had any issue with other 2FA logins.

**Comment by JC5** [comment]
This happens most often when the time difference between the server and the client is very large. If you go to the `/debug` page, you can see what the server time is. Compare this with your device time.

**Comment by AlexKalopsia** [comment]
Uhm that makes sense. I noticed that my firefly container was 1 hour and 1 minute behind, and now after correcting the TZ I am 1 minute behind my pc time. I am wondering what is going on with that since they are all synced via the web :D

**Comment by SuperSandro2000** [comment]
Your container was probably in UTC time and you live in UTC+1.
Also that +1 min could be problematic if it drifts further. "FA checks like the last 2 and the next 2 codes to circumvent that but as it is a time based protocol it can cause problems. Also make sure your 2FA generating device/app is synced correctly.
You could probably increase the timespan it checks but that makes it less secure.
