### ISSUE TITLE
Budgets: Only annual periods

### ISSUE THREAD

**Issue by ajoaris** [firefly-iii/firefly-iii#3103]
I am running Firefly III version 5.0.3.

**Description**
I managed somehow to get a budget navigation through annual periods. Unfortunately, I couldn't find a way to go back to monthly periods. Several budgets were recorded for some months, but I can't find a way to create budgets for additional months. I can only add new budgets in other currencies, impossible to replicate/duplicate the original monthly periods.

**Extra info**
Running on self sever (PHP 7.4.3), with MySql.

**Bonus points**
- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
<img width="1807" alt="Screenshot 2020-02-09 at 12 06 56" src="https://user-images.githubusercontent.com/58373247/74100180-c42eb780-4b34-11ea-9001-c20abdfb5d8f.png">
<img width="1795" alt="Screenshot 2020-02-09 at 12 06 37" src="https://user-images.githubusercontent.com/58373247/74100181-c8f36b80-4b34-11ea-8b9a-251aa0a546aa.png">
<img width="1786" alt="Screenshot 2020-02-09 at 12 16 14" src="https://user-images.githubusercontent.com/58373247/74100299-00164c80-4b36-11ea-8d40-b84b7354a3ee.png">
<img width="1800" alt="Screenshot 2020-02-09 at 12 15 25" src="https://user-images.githubusercontent.com/58373247/74100300-01477980-4b36-11ea-9961-edede4ae6cda.png">
 Already through PayPal!

**Comment by JC5** [comment]
Check out your preferences, where you should find a date range that is set to "Yearly".

**Comment by ajoaris** [comment]
Thanks. In “Layout”. Besides graphs, it also makes it for budget periods
