### ISSUE TITLE
Account refresh via Firefly?

### ISSUE THREAD

**Issue by PiperMp3** [firefly-iii/firefly-iii#3106]
Hello,

Using Firefly with Saltedge.
Firefly can successfully connect to Saltedge and import transactions.

Now, with specific banks, some banks does not allow non-interactive connections. Ie, you need to input a "code" to contact it.

My bank is one of those.
Therefore Firefly only seems to be able to reimport the data SaltEdge holds, and Saltedge needs to be "reconnected" to refresh its data.
Contacted SaltEdge themselves and they state a "Refresh" needs to be performed, and not necessarily a reconnect because it is NOT a non interactive connection.

So my question is - FireFly itself, does not seem to allow this, and seems to be relying on Non-interactive Connections in SaltEdge.
This therefore makes my bank, albeit it can connect manually, very mute and non-working with Firefly.

Does anyone know if there is a way of getting Firefly to issue the "Refresh" with Interactive connections?
Firefly therefore asking for the code - handing this to Saltedge API, saltedge refreshes, and Firefly then pulls the refreshed data?

Cheers,

**Comment by JC5** [comment]
This is not possible in Firefly III I'm afraid. It's also not going to change in the foreseeable future.
