### ISSUE TITLE
Migration / backup / restore guide

### ISSUE THREAD

**Issue by oleksiiha** [firefly-iii/firefly-iii#3107]
I am running Firefly III version 5.0.0.

**Description**

After playing with Firefly for couple of weeks I managed to import and organise all my 3 years transaction history from Banktivity tool, with all tags, notes, mortgage payments, etc. That was quite a task, but I am satisfied with this tool and appreciate all the  work you put in it. I decided to stick with using Firefly instead of Banktivity, because it has feature parity and I can share login details with my spouse and manage transactions together.

My problem now is that I installed docker version on my windows machine and I want to migrate everything to a dedicated for this purpose Raspberry Pi. I am not the most advanced docker user and not really familiar with PgSQL and PHP being a full-time Frontend Dev. I tried the following:

1. I have the precise command that I used when installed Firefly on my source machine
2. I created same volumes on the destination machine, installed Pg and FF with Docker
3. Made backup on source machine with the method described in FF documentation [here](https://docs.firefly-iii.org/advanced-installation/backup)
4. Restored on destination machine with the same guide from FF docs

That didn't work, transactions did not appear in the new installation. I tried to re-install FF by deleting the Docker container/image and installing it on top of restored volumes - didn't work, still installation worked as a fresh one.

So I tried another method - dumping the Pg DB with `pg_dump` on source machine and restoring it on destination like this:

```
# source
docker exec firefly_iii_db  /usr/bin/pg_dump -U firefly firefly > backup.sql
# destnation
docker exec -i firefly_iii_db psql --username firefly firefly < backup.sql
```

On top of installed Pg and FF.
After this I was able to login with the same credentials that I have on source machine, but after login I see only Error page from FF, so I assume that didn't work.

Being not really this stack user I would appreciate any tips and directions on how to do backup/restore or machine migration routine. I found similar issue here on GH, with explanation that the right way is to use OS tools for that and not rely on export/import tools from FF and I understand that, the process is just not clear to me.

**Extra info**
Source machine: Latest Docker, Windows 10
Detination machine: Latest docker, latest Raspbian OS, Raspberry Pi 3

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [x] I added log files (see https://bit.ly/FF3-get-logs)
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
>  After this I was able to login with the same credentials that I have on source machine, but after login I see only Error page from FF, so I assume that didn't work.

Which error did you get?

**Comment by oleksiiha** [comment]
> Whoops
> There was a fatal error. Please check the log files.

Apparently it is time to go to log files. Sorry, but I didn't find how to do that. Access logs from `docker container log` don't have any errors, each request looks something like this
```
192.168.1.36 - - [10/Feb/2020:20:44:38 +0000] "GET /fonts/lato-100.woff HTTP/1.1" 404 3735 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
```

**Comment by oleksiiha** [comment]
Ok, I'm sorry, its on the plain site, here some DB errors from the logs:
```
In Connection.php line 669:

  SQLSTATE[08006] [7] FATAL:  the database system is in recovery mode (SQL: s
  elect distinct "transaction_journals".* from "transaction_journals" left jo
  in "transaction_types" on "transaction_types"."id" = "transaction_journals"
  ."transaction_type_id" left join "budget_transaction_journal" on "transacti
  on_journals"."id" = "budget_transaction_journal"."transaction_journal_id" w
  here "transaction_types"."type" not in (Withdrawal) and "budget_transaction
  _journal"."budget_id" is not null and "transaction_journals"."deleted_at" i
  s null)


In PDOConnection.php line 31:

  SQLSTATE[08006] [7] FATAL:  the database system is in recovery mode
```

**Comment by JC5** [comment]
Strange. It seems everything works well but the error you're getting is an internal postgres error. Are you able to reach the database, browse your data, etc. using PGAdmin?

**Comment by oleksiiha** [comment]
I did not try to fix that migration and now trying to use the migration that I used at first - using instructions from FF3 website. Eventually I understood that the APP_KEY was wrong on my destination machine.
So what I did now:

1. I stopped and removed both postgress and ff3 containers
2. I removed all volumes to start from scratch
3. I made fresh volumes backups on source machine
4. I created new volumes on destination machine
5. I installed with docker postgress and ff3, now for sure with correct ENV variables
6. Opened FF in the browser and checked logs that everything went fine
7. Restored volumes on destination machine
8. Went to `/flush` 

Now I am able to log in with my FF account but I see only two empty Asset Accounts and couple of categories, but no transactions, bills, rules. Also Asset accounts names are not the same as on source machine, it looks like a very old version of the db when I just installed FF for the first time almost a month ago

**Comment by JC5** [comment]
If you inspect the database with PGadmin, is it the old database as well?

**Comment by oleksiiha** [comment]
Alright, I think I figured it out. Problem was that on my source machine I had two users, one admin that I didn't use and second one is with all the transactions and so on. What helped me this time:

1. I did fresh install of PG and FF
2. Created two same users in the FF
3. Migrated data using `pg_dump / psql`

Now I see correct data in my second user on the destination machine. It seams that all problems I had are because users are not migrated with the db somehow.

Thank you for your time, hope this will help someone!

**Comment by JC5** [comment]
:+1: you're welcome!

**Comment by oleksiiha** [comment]
Sorry to bump it again, but it seams that categories and tags are present in the system, but all transactions don't have them set. So basically categories are there but all empty, same with tags. I will not update this issue again probably, but my migration is not over yet.

**Comment by JC5** [comment]
Try running the following command on the command line

`php artisan firefly-iii:back-to-journals`

**Comment by JC5** [comment]
And if that works, run the whole set:

```
firefly-iii:upgrade-database
```

**Comment by oleksiiha** [comment]
```
$ php artisan firefly-iii:back-to-journals
This command has already been executed.
$ php artisan firefly-iii:upgrade-database
```
Second command was executed with no errors (took around 2 minutes on raspberry pi), but with no effect. I still see empty categories and tags

**Comment by JC5** [comment]
Mmmm. Is there content in the following tables? budget_transaction and budget_transaction_journal. Could you try to clear the cache just in case? `php artisan cache:clear`

Also, try `php artisan firefly-iii:back-to-journals --force`

**Comment by oleksiiha** [comment]
It seams there is no content in those tables:
```
firefly=# SELECT * FROM budget_transaction;
 id | budget_id | transaction_id
----+-----------+----------------
(0 rows)

firefly=# SELECT * FROM budget_transaction_journal;
 id | budget_id | transaction_journal_id
----+-----------+------------------------
(0 rows)
```
Also, commands run successfully:
```
root@ce68fbca28f2:/var/www/firefly-iii# php artisan cache:clear
Application cache cleared!
root@ce68fbca28f2:/var/www/firefly-iii# php artisan firefly-iii:back-to-journals --force
Forcing the command.
Check 0 transaction journal(s) for budget info.
Check 0 transaction journal(s) for category info.
Updated category and budget info for all transaction journals in 0.09 seconds.
```
No effect it seams. Maybe my export command was wrong?

**Comment by JC5** [comment]
It seems so, I expect you did a comparison with the old database already?

**Comment by oleksiiha** [comment]
Not really, I did not succeed installing pgadmin with docker, so I just compared the transactions in the FF. One issue I know with my export is that it had somehow not utf-8 encoding and I converted dump manually to utf-8 before importing, otherwise import didn't work at all.

**Comment by JC5** [comment]
Is the data there in the old export file?

**Comment by oleksiiha** [comment]
Finally!
So correct algorythm to migrate all data for me was following:

1. Make db export with `pg_dump`, check that encoding is UTF-8
2. On destination machine install Postrgress first
3. Restore the db
4. Only after that install firefly, in that way all transactions and users and everything else will be migrated properly

My error was that I installed firefly before restoring the db.
Thank you again

**Comment by JC5** [comment]
Thanks for posting the solution :+1:

**Comment by FelikZ** [comment]
Copy-paste from my internal readme how to do backups:

## Backup

```bash
docker-compose up -d
source backup.sh
```

## Restore

```bash
docker-compose down -v && docker-compose up -d
source restore.sh ./bak/dump_22-02-2020_15_43_44-all-in.dump
```

**Comment by oleksiiha** [comment]
Nice, I did something similar in the end, also added backup.sh to cron and upload sql dump to s3 bucket in backup.sh
