### ISSUE TITLE
piggy banks- suggested monthly amount logic proposal

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3108]
The current implementation of "piggy bank suggested amount to save per month" changes daily. I propose a change to this logic to pin the value irregardless of today's day of the month. 

Because this is a monthly value, I think it would be least surprising to people if the amount was calculated monthly. I also think the calculation should not include the end date's month.

I would be happy to make the pull request. Is there interest in merging this feature?

**Comment by JC5** [comment]
That's weird. The code is supposed to do that already.

If you know the bug feel free to fix it!

https://github.com/firefly-iii/firefly-iii/blob/master/app/Repositories/PiggyBank/PiggyBankRepository.php#L474

**Comment by 4e868df3** [comment]
Attaching an example of the issue. Today is Feb 10th. It should say $15/mo.

**Comment by JC5** [comment]
August is the 8th month of the year and Februari is the 2nd. At most, it should say $17,50. And this will happen on or before the 8th of Februari. However, on the 9th and beyond, the date difference between those two dates is less than 6 months: it's 5 months and 30 days. Which is why it jumps to 21,00.

**Comment by 4e868df3** [comment]
Thanks. I am able to change the dates that I'm working with to get the behavior I was expecting.
![screenshot 1581466009](https://user-images.githubusercontent.com/50036670/74291125-1a485a00-4cf1-11ea-9113-c13bad837e72.jpg)
