### ISSUE TITLE
Add the ability to setup custom box on the DashBoard (like Net worth, Balance etc).

### ISSUE THREAD

**Issue by Kazer67** [firefly-iii/firefly-iii#3109]
**Description**
I would like Firefly III to allow me to setup a custom box on the dashboard like "Balance" where I can select specific account and it would display the sum of the money for those account.

**Solution**
This feature would allow more flexibility on the way other may managed their money. For example, in my country, the term "Balance" is usually used not for the expense of the month (in - out) but for the remaining money on the "credit card" account at the moment of view. Having the ability to use the current "Balance" view for a month + a custom box with the remaining of selected account would allow better tracking.

But the custom box could also be used for other purpose.

**What are alternatives?**
The alternatives right now is to only use credit card account for "Net Worth" box and not the "saving" account.

**Comment by JC5** [comment]
Assuming this is about a credit card that you repay each month, you might be able to set a virtual balance and use the box on the right where the transactions are listed too.

<img width="442" alt="Screenshot 2020-02-10 at 20 10 47" src="https://user-images.githubusercontent.com/5889984/74181360-10632000-4c39-11ea-8786-80dcd6bc7dda.png">

**Comment by Kazer67** [comment]
It's the reverse actually, the name doesn't exist in the account asset type so I use "Credit Card" for now, but those are not common where I live.
We use debit card attached to a specific account and it work the other way (instead of going negative and them paying back, you start positive and spend that). You get your salary and you can spend the money and you can't really go negative (in some bank you have the right to go negative for a little amount only).

That feature will allow people in country where debit card are common to see how many they can still spend before the next salary hit and before the card start rejecting transaction by lack of fund. So you now where you have like 200 € left in the middle of the month to be careful.

I can go to the specific account, but since I have two debit card with two different account, if I can have a custom box with the sum of the two would be very nice.

Also, it's for my case, but the custom box you can setup for the dashboard doesn't have to be limited to my use, having the ability to set a custom box with other rules could be useful for other people who want/need to customize thing that's common practice where they live.

**Comment by JC5** [comment]
That doesn't really change my point though. If you want to track the balance of a card, you can use that number, right?

**Comment by Kazer67** [comment]
For one card yes, but if you have 5 debit card, you'll have to do the sum of the five of you want to see the overall money you can spend every time.

**Comment by JC5** [comment]
I see what you mean. Sorry, but that's not something I want to add to Firefly III.

**Comment by Kazer67** [comment]
The example is just for my case, but the global idea was to add more customization on the dashboard to allow Firefly to fit more for different people with custom box that can display what you want (my example use the sum of "credit card" account, but you could setup other rules if you want).

**Comment by Aradiv** [comment]
I would also like more customization to allow to rearange the boxes at the dashboard.
Personally i would like to have the Budget Box at the Top of the column on the right and the transaction lists at an lower point. or even completly hidden at the dashboard

**Comment by Aradiv** [comment]
are there any plans to get more customization to the dashboard?

**Comment by JC5** [comment]
The dashboard is going to stay as it is right now.
