### ISSUE TITLE
Can't disable Euro because it is used in budget limits

### ISSUE THREAD

**Issue by mauirixxx** [firefly-iii/firefly-iii#3111]
**Bug description**
I am running Firefly III version 5.0.4, and my problem is:

I live in the USA and don't need the Euro currency enabled, but I can't disable it because it's being used even though I'm not using it.

**Steps to reproduce**
Click on Options -> Currencies -> Euro -> Disable check box. Then an error message stating "Error! Cannot disable Euro because it is used in budget limits"

Click on Budgets, and review the current budgets in place. All of them use the USD symbol $ as they should. Create a new budget, no option for currency, budget gets created with USD symbol $ as expected. Note - when deleting a budget, clicking on the confirmation button takes you to a 404 error page, but DOES destroy the budget as expected. Continuing on ....

Clicking on the little + symbol in "Budgeted" on an existing budget shows the Euro symbol, and there's no option to change it to a USD symbol $. See [image](https://i.imgur.com/8NBZPEm.png)

**Extra info**
CentOS 7 VM, Firefox 72 browser. Debug below:

Debug information generated at 2020-02-10 14:02:18 Pacific/Honolulu for Firefly III version **5.0.4**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.4 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.4.2 |
| Display errors | Off |
| Session start | 2020-02-01 00:00:00 |
| Session end | 2020-02-29 00:00:00 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.48 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, apcu, geoip, zip, mysql, Zend OPcache |

---
This debug output seems related to the 404 error on destroying a budget:
---
Truncated from this point <----|[2020-02-10 13:56:47] local.WARNING: GracefulNotFoundHandler cannot handle route with name "budgets.edit"  
[2020-02-10 13:56:57] local.WARNING: GracefulNotFoundHandler cannot handle route with name "budgets.destroy"  
[2020-02-10 13:57:00] local.ERROR: Could not parse date "destroy" for user #1: DateTime::__construct(): Failed to parse time string (destroy) at position 0 (d): The timezone could not be found in the database  
[2020-02-10 13:57:00] local.WARNING: GracefulNotFoundHandler cannot handle route with name "budgets.index" 

**Bonus points**
This bug seems similar to Issue [#2515](https://github.com/firefly-iii/firefly-iii/issues/2515)

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for the error log, I'll pick that one up for sure.

Did you set USD to your default currency already?

**Comment by JC5** [comment]
If this is the case, and the problem keeps popping up, you can go to your database directly and delete the entries in the `budget_limits` table that have `transaction_currency_id` = 1.

**Comment by mauirixxx** [comment]
Yes, I set USD to the default. After deleting all of the transaction_currency_id's that equaled 1 I was successfully able to disable the Euro. After doing so, the little + symbol went away, so now I can't "Set the budgeted amount for budget etc etc" - not that I ever have though.

Just wanted to bring that to your attention in case that wasn't the desired outcome.

**Comment by mauirixxx** [comment]
More budget madness:

Budgets that were previously filled in are now blank - I'm assuming this is because of the sql deletion - going back and re-adding the budgeted amount for transactions made last year via the text input box works as intended, but the little + symbol is there on empty fields.

If I use the + symbol to add in a budgeted amount, the amount goes in as desired AND I get the USD currency as my only selection, however, upon clicking on the "Set budgeted amount" save button, I get taken all the way back to this month and year instead of returning back to whatever month and year I was working on.

**Comment by mauirixxx** [comment]
> 
> 
> If this is the case, and the problem keeps popping up, you can go to your database directly and delete the entries in the `budget_limits` table that have `transaction_currency_id` = 1.

sorry for all the replies. After poking around the database after re-adding my old budgeted entries, instead of DELETING the transaction_currency_id = 1 rows, if I UPDATED them to match the USD id (7 it seems like) I think I could've disabled the Euro without having to re-add the deleted budget amounts.

Just leaving this here for anyone who runs into this in the future.

**Comment by JC5** [comment]
>  I get taken all the way back to this month and year instead of returning back to whatever month and year I was working on.

Thanks, I'll make sure that gets fixed.

**Comment by JC5** [comment]
The redirect will be fixed in the next release.

**Comment by JC5** [comment]
This issue will be closed, now that the first alpha of 5.1.0 is out. Keep an eye out on the release page. If something comes up, please open a new issue. Thanks!
