### ISSUE TITLE
Login form and assets load incorrectly with Nginx reverse proxy and SSL

### ISSUE THREAD

**Issue by ment4list** [firefly-iii/firefly-iii#3112]
I am running Firefly III version 5.0.4

Related to [1739](https://github.com/firefly-iii/firefly-iii/issues/1739) maybe?

**Description**

I am running Firefly via a container through a cloud host.
In order to set up SSL I followed the instructions from [this issue](https://github.com/firefly-iii/firefly-iii/issues/2600)

It seems to work fine. However, Firefly loads some resources incorrectly.

First off, when loading the site over HTTPS, the login form loads and _looks_ fine. But the form's `action` attribute points to the unsecured HTTP endpoint and thus can't be used on mobile. On desktop I can change it to HTTPS and log in.

Once logged in however, things really get weird.

Some assets are loaded via HTTP. Let's take the "moment.js" file for instance.

It's requested from `http://MYDOMAIN.TLD/v1/js/lib/moment.min.js?v=5.0.4` which fails because of a CSP policy. And then it's loaded over HTTPS. This is probably because of the `Strict-Transport-Security: max-age` policy in the response headers.

When I go to any sub page, "Transactions > Expenses" (URL "transactions/withdrawal") for example, all resources respond with 404 errors as it's trying the URL
`https://MYDOMAIN.TLD/transactions/v1/js/lib/moment.min.js?v=5.0.4` which does not exist
Why is the resource path prepended by "transactions"?

Not sure what it matters, but the `APP_URL` env var is set to `https://MYDOMAIN.TLD`

**I tried some things**

I added this into the `public/index.php` page while playing around with testing the API. The same problem persists even with this removed.

```php
// CSP
header("Content-Security-Policy: upgrade-insecure-requests");

// Access-Control headers are received during OPTIONS requests
header("Access-Control-Allow-Headers: Authorization, Content-Type,Accept, Origin");
header("Access-Control-Allow-Origin: *");

if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
    header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
    header("HTTP/1.1 200 OK");
    exit(0);
}
```

**Extra info**
Debug information generated at 2020-02-11 for Firefly III version **5.0.4**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.4 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.14 |
| Display errors | Off |
| Session start | 2020-02-01 00:00:00 |
| Session end | 2020-02-29 23:59:59 |
| Session first | 2019-09-18 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment]
Make sure your nginx reverse proxy config looks something like this:
```
	# Firefly III
        location / {

                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $host;
                client_max_body_size 64M;
                proxy_pass http://127.0.0.1:8002$uri$is_args$args;
		proxy_read_timeout 300s;
        }
```

**Comment by ment4list** [comment]
You are too quick, thanks! :)

I check the config and it is there by default.

If I add `proxy_pass http://127.0.0.1:8002$uri$is_args$args;`, all requests fail with 503.
I tried `proxy_pass http://myfirefly.host$uri$is_args$args;` which did not seem to do anything.

The below is already in the default conf for the [docker image I'm using](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion)
```
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $host;
```

For future reference, I changed the `/etc/nginx/conf.d/default.conf` in the `nginx-proxy` container.

**Comment by ment4list** [comment]
Not sure what changed but it is working now. Strange.

For future reference `/etc/nginx/conf.d/default.conf` looks like:

```
        location / {
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                client_max_body_size 64M;
                proxy_pass http://DOMAIN.TLD$uri$is_args$args;
                proxy_read_timeout 300s;
        }
}
```

**Comment by JC5** [comment]
:+1:
