### ISSUE TITLE
CLI import using csv-importer-docker

### ISSUE THREAD

**Issue by AndreiGavriliu** [firefly-iii/firefly-iii#3113]
I am running Firefly III version 5.0.4

**Description**
Hi, I am finally importing stuff to firefly-iii again, and was trying out your `csv-importer-docker` Docker build. I am now trying to use my old scripts which were importing csv files via the CLI:

`php artisan firefly-iii:csv-import $IMPORT_CSV config/accounts/$ACCOUNT.json --user=1 --token=$FIREFLY_III_IMPORT_TOKEN`

unfortunately the new build crashes:

`There are no commands defined in the "firefly-iii" namespace.`

I checked the documentation and some issues, but could not find anything relevant. Am I missing something or is it still under development?

Cheers,
Andrei

**Comment by JC5** [comment]
I don’t think I added them yet. It’s a few weeks since I worked on them. I think my last idea was to make you able to run the image, import data and then auto shutdown again.

**Comment by AndreiGavriliu** [comment]
That’s exactly what I am trying to do. Based on your image, I install some more packages (aqbanking-tools), import via cli and shutdown (cronjob)

Is there a plan to add them? Or should I find some
Workaround? Rest API?

**Comment by JC5** [comment]
No I plan to add it. But the command would something like the `docker run` command that you sometimes see in hello world tutorials.

**Comment by JC5** [comment]
I'll keep this one open as a feature to keep you up to date.

**Comment by SuperSandro2000** [comment]
Also if the docker container is already running we could use ``docker exec`` and pipe content into it with ``<``.

**Comment by JC5** [comment]
https://firefly-iii.gitbook.io/firefly-iii-csv-importer/installing-and-running/docker

Looking forward to your feedback.

**Comment by SuperSandro2000** [comment]
I think this line ``-e WEB_SERVER=false`` makes no real sense as a few lines under it the text writes that I want to start a web server.

**Comment by JC5** [comment]
Oh nicely spotted, I copy/pasted the wrong command.

**Comment by AndreiGavriliu** [comment]
Damn that was fast, I was in the middle of rewriting everything to import via RestAPI. I will see how it turns out and let you know. Just a side-question. Does this image also have the ability to send notification emails for import jobs as firefly-iii used to do when importing from the main app?

Thanks for considering this!

**Comment by JC5** [comment]
No, not yet. I don't know yet how I want to do that. But it's on the list!
