### ISSUE TITLE
Can't select a budget via arrow keys when creating a new transaction

### ISSUE THREAD

**Issue by mauirixxx** [firefly-iii/firefly-iii#3114]
**Bug description**
I am running Firefly III version v5.0.4, and my problem is:

I use my Tab and arrow keys to navigate Firefly when creating transactions, as it's faster (for me) than using a mouse. When using the mouse I can view all of my available budgets, but whenever I use the up or down arrow keys the budget disappears and then my only options are either "blank" (there's nothing listed) or "(none)".

[Also, (none) is listed twice](https://i.imgur.com/olnsKVN.png).

**Steps to reproduce**
Have budgets created. Create a new transaction. After entering a number in the "Amount" text entry box, press the "Tab" key to move to the "Budget" drop down list. Use up and down arrow keys. The Up key does nothing at all. The Down key cycles between a blank listing and (none).

Use the mouse to verify and select a budget.

**Extra info**
Tested in both Firefox v72.0.2 and MS Edge v80.0.361.50 (Chromium based). Strangely, the original MS Edge included with Windows 10 works just fine with regards to using the arrow keys.

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for the expansive report, I'll pick it up as a bug.

**Comment by JC5** [comment]
I've been able to fix the double budget, but I can't replicate the arrow-key thing. I've tested this in Chrome and Firefox (73) on a Mac. I don't have access to Edge unfortunately.
