### ISSUE TITLE
Docker install: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by fireshaper** [firefly-iii/firefly-iii#3116]
I am running Firefly III version 5.0.3

**Description**
I am trying to set up Firefly with Docker and at the end of the logs when I use "docker run" to start the container I get the following errors
``/var/www/localhost/htdocs/firefly/.deploy/docker/entrypoint.sh: line223: syntax error near unexpected token `('``
``/var/www/localhost/htdocs/firefly/.deploy/docker/entrypoint.sh: line223: `chmod -R 775 $FIREFLY_PATH/storage (again)'``

![firefly iii unexpected token](https://user-images.githubusercontent.com/10916477/74442592-c5ffc000-4e3f-11ea-96c9-ddbf7cb64a18.png)

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- [X] I added a screenshot
- [ ] I added log files (see https://bit.ly/FF3-get-logs)
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Could you tell a bit more about your installation process? The entrypoint script hasn't existed in ".deploy/docker/entrypoint.sh" long before 5.0.3 was released.

**Comment by fireshaper** [comment]
I'm running this on a Raspberry Pi Zero W so I used ThreadR-r's script here https://github.com/ThreadR-r/docker-firefly-iii-arm32v6-raspberry-pi

**Comment by JC5** [comment]
Since is running some `sed` commands I believe he is changing some commands in unexpected ways. Let me ping him:

https://github.com/ThreadR-r/docker-firefly-iii-arm32v6-raspberry-pi/blob/master/Dockerfile#L65

@ThreadR-r

**Comment by fireshaper** [comment]
I guess I probably should have brought this up on his fork. Sorry, I've been working on this for two days (mainly problems with the Pi Zero W architecture causing problems) and I'm a little frazzled, haha.

**Comment by JC5** [comment]
Haha no worries, I'm happy to help.

**Comment by fireshaper** [comment]
@ThreadR-r @lukasmrtvy

**Comment by ThreadR-r** [comment]
Hello, thanks you for reporting this issue, I didn't had the time to test the version.

I fixed the bug and uploaded the 5.0.5 (latest) docker image which I tried and work fine.

To anwser @JC5 's doubts about the `sed` command, it simply adapts entrypoint.sh script to nginx server.

Regards

**Comment by fireshaper** [comment]
Thanks! I'll give it another try.

**Comment by fireshaper** [comment]
@ThreadR-r Sorry I'm a little new to docker, but what would I run to re-grab your code? When I run the command in your README again it just tries with the same build I have.

**Comment by fireshaper** [comment]
That worked @ThreadR-r ! Thanks so much for looking into that.
