### ISSUE TITLE
Transactions import field - not sure what to set for "column data meaning"

### ISSUE THREAD

**Issue by SamuraiWaffle** [firefly-iii/firefly-iii#3117]
My bank lets me export my transaction history into a CSV format. However, looking at the import options, I can't determine how I should set the fields in the transaction importer. Can anyone point me in the right direction to determine how I should select the imported fields? Here is how the CSV column layout is:

Date of transaction
Description of transaction
Amount of transaction
Balance after transaction occurred
Balance before transaction occurred

I tried looking up more information on these imports, but couldn't find anything with a good description on how I should set the fields. Any help is greatly appreciated.

**Comment by JC5** [comment]
I think the best choices are:

* Date
* Description
* Amount
* (ignore)
* (ignore)
