### ISSUE TITLE
Creating New User Broke Firefly - Default Currency Issue

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#3118]
I am running Firefly III on docker (:stable tag).  I can't access my container currently, so not sure the exact version but it's updated nightly.

I disabled single user mode so I could create a new account, then logged out and created a new user from the login page.  Then I get the below error message and cannot access my instance anymore.

I have USD as my only currency, so perhaps the new user is defaulting to a non-existent currency.

Any idea how I can fix this one?

> Whoops! An error occurred.
> Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> 
> Return value of FireflyIII\Support\Amount::getDefaultCurrencyByUser() must be an instance of FireflyIII\Models\TransactionCurrency, null returned
> 
> More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.
> 
> If you cannot find the cause of this error or when you need some help, please open a ticket on GitHub.

**Comment by JC5** [comment]
I'll try to duplicate it. Did you happen to delete all currencies, except EUR?

**Comment by hamfactorial** [comment]
Basically yes, I restored a DB snapshot and I only see USD listed as a currency.

I tried re-adding an entry for Euro, but I got a message about a duplicate or a name already in use. 

If my tweaking has left things in an unhealthy state, I might be able to repair this by doing an export/import to a fresh instance.

**Comment by JC5** [comment]
Run this query, you should be fine again.

```sql
update transaction_currencies SET deleted_at = NULL WHERE code = 'EUR';
```
I'll make sure this gets caught by Firefly III.

**Comment by hamfactorial** [comment]
That fixed it, thanks!

I've logged in as the second user and now I have to ask a dumb question.  Does each user get their own accounts/budgets/etc?  It looks like a fresh install when I log into the second user. 

My aim was to give my wife a non-admin user to check the budgets that I've already created.

**Comment by JC5** [comment]
Yes, all users are strictly separated. You can't share an administration I'm afraid.
