### ISSUE TITLE
Docs - Reconciling accounts: screenshots broken

### ISSUE THREAD

**Issue by Azlond** [firefly-iii/firefly-iii#3121]
**Bug description**
[The screenshots section for reconciling accounts](https://docs.firefly-iii.org/advanced-concepts/reconcile) only displays broken images. All images point to a 404.

**Steps to reproduce**
Visit the link above.

**Extra info**

**Bonus points**

- [X] Nobody reported this bug before (I think? Couldn't find anything regarding this)
- [ ] I have added a stack trace from my log files.
- [X] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

![image](https://user-images.githubusercontent.com/13473851/74485062-2b909280-4eba-11ea-928e-d387a22c8162.png)

**Comment by JC5** [comment]
Thanks for letting me know, I wasn't aware of it! I'll pick it up as soon as possible.

**Comment by JC5** [comment]
Should be back up again.

**Comment by Azlond** [comment]
Looks great :+1:
