### ISSUE TITLE
[UX] Actions button on top of the lists

### ISSUE THREAD

**Issue by blandine** [firefly-iii/firefly-iii#3122]
**Description**
When changing multiple transactions, I need to scroll to reach the "actions" button at the bottom of the list.

**Solution**
I think it would be easier if, after selecting multiple transactions, the "actions" button appear at the top of the list too. (Having another one at the bottom is nice, so I would not remove it.)

**What are alternatives?**
It's already working well, it's just a ux improvement :)

**Additional context**

![image](https://user-images.githubusercontent.com/1214949/74519907-e484ba80-4f16-11ea-9527-b08f8c20b882.png)

**Bonus points**
I might do it on a pull request :)

**Comment by JC5** [comment]
Great idea :+1:

**Comment by JC5** [comment]
Fixed in the next release.
