### ISSUE TITLE
after the update does not work

### ISSUE THREAD

**Issue by nloshka** [firefly-iii/firefly-iii#3123]
after the update does not work, the graph is not displayed; you cannot add the expense of transfer or income.  how to fix what would work?  I’m writing from mobile, I can attach screenshots.  I ask for help, but it doesn’t work on my mobile.
![9CE625A1-4A90-47E6-BBBB-393EB3E29D8A](https://user-images.githubusercontent.com/12123175/74581399-17cf5400-4fc0-11ea-934f-f888aec61ad1.png)
![B5413047-CB8E-4720-A620-AA053DCF5179](https://user-images.githubusercontent.com/12123175/74581400-1aca4480-4fc0-11ea-8632-54dadc0c9a76.png)
![41CD6FDE-89FD-4E61-8016-4F492A53E15C](https://user-images.githubusercontent.com/12123175/74581401-1b62db00-4fc0-11ea-8cf7-28ace12b2b10.png)
![7909A312-F101-4F79-8C6D-FFF227266070](https://user-images.githubusercontent.com/12123175/74581402-1bfb7180-4fc0-11ea-84d4-8b556a9f9efe.png)

**Comment by JC5** [comment]
I'm sorry to hear it doesn't work but you're not giving me any relevant info.

**Comment by nloshka** [comment]
Debug information generated at 2020-02-17 12:02:12 Europe/Amsterdam for Firefly III version **5.1.0-alpha.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.1.0-alpha.1 |
| FF API version | 1.0.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.14 |
| Display errors | Off |
| Session start | 2020-02-01 00:00:00 |
| Session end | 2020-02-29 23:59:59 |
| Session first | 2018-12-08 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, apcu, posix, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apc, igbinary, imagick, inotify, msgpack, zip, Phar, memcached, redis, Zend OPcache |

**Comment by nloshka** [comment]
Earned.
I cleaned the safari browser on the iphone.
I apologize for the panic.
Everything works!
You can close the ticket.
