### ISSUE TITLE
Question: Can I use firefly with multiple accounts 

### ISSUE THREAD

**Issue by BobWs** [firefly-iii/firefly-iii#3124]
Hi,
I was wondering if I can use firefly with multiple accounts. Let’s say I would like to share it with my family. Give everyone an account so they can keep track of their own finances. Will this work? Is firefly built to support this? And how can I set this up. What is the best way to do this.

**Comment by JC5** [comment]
Yes , this is possible. Go to your administration and turn off “single user mode”. Firefly III will open up the registration form and users can create their own account. 

All data is strictly separated so they won’t be able to see each other’s administration. 

Under the same Administration button you, the owner, can do some basic user management.

**Comment by BobWs** [comment]
Thanks I will give it a try

**Comment by AlexKalopsia** [comment]
Oh wow, how did I miss this? I was running two separate containers :D
