### ISSUE TITLE
Withdrawal/Deposit vs Expense/Income

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#3125]
I am slightly confused about the terminology used by Firefly on the sidebar. I feel like New withdrawal or New deposit doesn't really match what I am trying to do. I am not withdrawing money really, I am just tracking an expense. Same thing with the deposit, I am not really depositing money, but someone else is generating an income. 

I don't know if this is just me, but I would find much more readable if the sidebar would use Expense/Income terminology.

**Comment by JC5** [comment]
I got similar feedback the other way around in the past. This is what it is I'm afraid.

**Comment by AlexKalopsia** [comment]
Well, my issue is mostly that elsewhere Firefly is just using Expense and Revenue, and only in the sidebar it mensions Withdrawals and Deposits. It just feels inconsistent :S
