### ISSUE TITLE
Display issues after cloning a transaction

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3127]
v5.1.0 Alpha,1
Win 10 Edge and Firefox. 
Local and reproduced on demo site

Bug:
weird behavior after cloning a transaction it will not appear in the list of transactions in some scenarios and appear in others. editing the cloned transaction makes it appear everywhere.

Range Feb 2020: Clone appears:

![snip1](https://user-images.githubusercontent.com/3269694/74658948-f81f6380-5158-11ea-9b8e-475cd28ce595.jpg)

Last 30 days: (I think all ranges except current month) Poof! Disappears. 
Shows up when selecting show everything.

![snip2](https://user-images.githubusercontent.com/3269694/74659072-403e8600-5159-11ea-9675-7750a6d1a8be.jpg)

**Comment by JC5** [comment]
Nice find. The cache refresh isn’t triggered. I’ll pick it up :)

**Comment by JC5** [comment]
Fix will go out in the next release.
