### ISSUE TITLE
Categorize Piggy-Banks

### ISSUE THREAD

**Issue by JanFeld** [firefly-iii/firefly-iii#3128]
**Description**
I'd like to categorize my piggy banks. I've got multiple piggy banks (around 20) and they belong to different categories. Some of them are more related to living and furniture, other ones belong to car and the rest are for hobby. I'm trying to get an overview how much money i have to save for the different categories to prioritize them better.

**Solution**
Add categories and sums of the belonging piggy-banks. Maybe a drag-and-drop display of the categories to see the piggy-banks grouped to them as well as the sum of all belonging piggy-banks in top of the group(s). 

**What are alternatives?**
Currently i'm just sorting piggy banks from top to bottom without grouping and i have to sum them up by myself. It would be possible to create new accounts as 'group' but that would not be adequate because they don't represent real accounts.

Best regards,
Jan

**Comment by JC5** [comment]
Not a bad idea! It's on the list :+1:

**Comment by JC5** [comment]
New release will feature this. Check out what it looks like on the demo site.

**Comment by JanFeld** [comment]
Looks great so far!

I've been just a little confused how to add a new group. Suspected it in the _Groups_ menu. 

Additonally a little suggestion, if you didn't plan that anyway. Maybe you can add an suggestions-dropdown like on account-names or similar for the groups in the piggiy-bank administration. Just to make things even more easy.

Nevertheless, this will help me a lot! Thanks for that!

**Comment by JC5** [comment]
The autocomplete is present but maybe it’s cached (and empty) 👍

**Comment by JC5** [comment]
Alright let's not reply from my phone that never works. I decided make it as transparent as possible, so empty groups are auto-deleted and the groups overview is just there to sort the groups: the edit/del buttons are a bonus.

The thing is, double sorting is pretty much impossible in JQuery UI. I *just* realized I could work with buttons too but its a lot less intuitive. So this is the alternative. For now! This is something that keeps improving.

And like I said, the "group" field should auto-complete :)

**Comment by JanFeld** [comment]
Well, let's not overcomplicate things then. As long as it works that's fine. When a new piggy-bank is created one will add a group anyway (if necessary). 

> And like I said, the "group" field should auto-complete :)

Checked again and it's fine. Maybe i had some typo or something similar .. I never said anything .. Forget about it! ;-)
