### ISSUE TITLE
Forwarded to error page after deletion of expense account

### ISSUE THREAD

**Issue by macGYves** [firefly-iii/firefly-iii#3130]
**Bug description**
I am running Firefly III version 5.0.5, and my problem is:

I get forwarded to a 404 error page after having deleted an (empty) expense account. 

**Steps to reproduce**
1. Open expense account
2. Click on "Show all transactions without grouping them by date."
3. Delete expense account
3.1. Click on dropdown toggle icon (the vertical "...")
3.2. Click on "Delete"
4. Confirm the deletion 

Then I get forwarded to this "404 error page":
![Firefly-iii - 404 error](https://user-images.githubusercontent.com/1998946/74685551-2b043e80-51cf-11ea-96bf-114cbb6112a1.png)

***Expected behaviour***
After the confirmation I'd have expected to be redirected to the place from where I've opened the expense account. 
In my case, that's the "expense account page". 

**misc**
I haven't tried to reproduce this on expense accounts containing one or more transactions.

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
Fix will be in the new release :)
