### ISSUE TITLE
Made a few fixes. 5.1.0 Alpha.1 as base.

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3132]
1 - This error was not noticeable in some browsers but a pain in the butt in edge for one. Any keypress will reset the Budget fields. Bypassable with single transactions by selecting budget last. Made split transactions literally impossible to enter a budget for more than one of the entries. Since at least 4.???
 
_[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. 
Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"_

2 - Since I was in the vue section learning as I go for hours on end... I fixed this little annoyance at the same time: Not too hard and added one for the budget since it was the only one that didn't seem to have a title. (before image)

![snip6](https://user-images.githubusercontent.com/3269694/74715297-cc03f100-51f1-11ea-88eb-a930985660b6.jpg)

3 - Since I was in the vue code. I did some early "spring cleaning" good size reduction + 1 extra file. I'm sure they could possibly even get smaller. Maybe a project for later on.

app.js (appears on all pages now - modified default layout accordingly)

![snip1](https://user-images.githubusercontent.com/3269694/74715833-f0ac9880-51f2-11ea-98fb-ef5d51c26180.jpg)

app_vue.js (new file) prefixes create, edit transactions and profile scripts on those pages only.
![snip2](https://user-images.githubusercontent.com/3269694/74715834-f1ddc580-51f2-11ea-9bcd-9d85515fcf0d.jpg)

Create...
![snip3](https://user-images.githubusercontent.com/3269694/74715835-f30ef280-51f2-11ea-96f1-8253a7ffba60.jpg)

Edit:
![snip4](https://user-images.githubusercontent.com/3269694/74715839-f3a78900-51f2-11ea-9fac-6afc90f2abf2.jpg)

Profile:
![snip5](https://user-images.githubusercontent.com/3269694/74715841-f3a78900-51f2-11ea-8ca8-1b9d8f5029e5.jpg)

Only problem I have is that I needed to create 4 sets of package.json and webpack.mix.js to build the dev and prod scripts or it would add extra stuff in all files when not wanted, needed or asked for. But I'm a newbie with vue and Laravel webmix. 

I rebuilt everything without Lodash in dev mode and no issues or errors for missing Lodash. Which is a good thing!

Needs a bit of cleaning out comments and test stuff in the components but should be good to go for a bigger test should you be interested.

Cheers,

**Comment by JC5** [comment]
Either submit a PR or send it to me directly, and I'll pick it up :+1:

**Comment by GaryQ** [comment]
Sent you an email. I can't figure out how to work the PR stuff … pathetic. At least I can find and sometimes fix bugs :D

**Comment by GaryQ** [comment]
Sent you a new email. Resolved the multi file build issue. Back to one package.json and wepack file!
