### ISSUE TITLE
add clean field feature to the Attachements field

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#3133]
**Description**
Please describe your feature request:
Similar to whats is available for other fiedls such as Category, it would be usefull to add the feature to clean the Attachements field, meaning remove files that were considered to be added. 

![imagem](https://user-images.githubusercontent.com/8387568/74731353-bb7a6780-523f-11ea-83f4-0400f7bb2d01.png)

**Comment by JC5** [comment]
Thanks, I'll pick it up!

**Comment by JC5** [comment]
Button will be present in the next release :)
