### ISSUE TITLE
Project questions by student group

### ISSUE THREAD

**Issue by eupn11** [firefly-iii/firefly-iii#3134]
Hi guys!

I am part of a group of students, and for a certain course (digital innovation) we want to learn about how a github project is coordinated. We are looking for two contributors in this project, who want to help us out. We have some short questions. We are willing to contribute to this project as well, by for example testing out.

**Comment by JC5** [comment]
You’re the fifth group from the Vrije Universiteit of Amsterdam to contact me. No worries, I’ll make sure my answers are unique so you won’t be accused of plagiarism 😉

Hit me up at james@firefly-iii.org.

**Comment by Lawri-van-Buel** [comment]
Just as a side note. It’s generally not smart to leave your email laying around on the Internet. 

And it’s not like James did not list a way to [contact](https://docs.firefly-iii.org/about-firefly-iii/introduction) him.
