### ISSUE TITLE
Changed liability type not saving

### ISSUE THREAD

**Issue by MadWalnut** [firefly-iii/firefly-iii#3135]
**Bug description**
Changing the type of a liability won't save. E.g. changing from loan to debt will not do anything, despite Firefly telling me it got updated. Changing other fields of the liability works.

**Steps to reproduce**
*Step 1:* create a liability (any type, in this case loan): ![Screenshot_1](https://user-images.githubusercontent.com/33835479/74764715-85120c00-5282-11ea-8910-9bb74e902b46.png)

*Step 2:* change the liability type to any other: ![Screenshot_2](https://user-images.githubusercontent.com/33835479/74764722-87746600-5282-11ea-93a7-e3cd82eee2df.png)

*Step 3:* save the changes and see that the type has not been changed: ![Screenshot_3](https://user-images.githubusercontent.com/33835479/74764727-8a6f5680-5282-11ea-9316-0e6f40994ed8.png)

**Extra info**
*Client:* Windows with Opera

Debug information generated at 2020-02-18 19:13:00 Europe/Amsterdam for Firefly III version **5.0.4**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.4 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , stack |
| PHP version | 7.3.11-1\~deb10u1 |
| Display errors | Off |
| Session start | 2020-02-01 00:00:00 |
| Session end | 2020-02-29 23:59:59 |
| Session first | 2020-02-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | cgi-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 OPR/65.0.3467.56 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, ldap, exif, memcache, mysqli, pdo_mysql, pdo_sqlite, apc, posix, pspell, readline, recode, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, Zend OPcache |

**Bonus points**
[YES] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks! That seems like a bug.

**Comment by JC5** [comment]
Fixed in the next release.
