### ISSUE TITLE
Implement an option to select "dd.mm.yyyy" as date format

### ISSUE THREAD

**Issue by schneekluth** [firefly-iii/firefly-iii#3136]
**Description**
As a person outside of the US it would be nice to change the date format in input fields from mm/dd/yyyy to dd.mm.yyyy as nobody in the EU uses the current provided format.

**Solution**
Provide an option in settings to switch date format e.g. from 02/28/2020 to 28.02.2020.

**Comment by JC5** [comment]
The date field is formatted by your browser, not by Firefly III.

**Comment by JC5** [comment]
Sorry, here's a longer answer: so your browser's locale determines how the date field is formatted. If you set your browser to en/US, it'll read 02/28/2020. If you set it to Dutch, it'll read 28-02-2020. German, 28.02.2020. Etc.

**Comment by schneekluth** [comment]
Thanks for your reply. I wasn't aware that my browser setting determines the formatting. I am indeed german but use all my computers with english system language. So I guess there is no solution for me than changing my language settings. Maybe you could tag this as future improvement? Or shall I close this issue?

**Comment by MadWalnut** [comment]
I've had the exact same issue. You could try setting your browser language to UK English, that worked for me with Opera. That should put the month in the correct place. Not sure though if other browsers have a similar language setting though, but I'd guess so.

**Comment by mauirixxx** [comment]
I wish everyone would just use 2020-02-28 across the globe....

**Comment by schneekluth** [comment]
> I've had the exact same issue. You could try setting your browser language to UK English, that worked for me with Opera. That should put the month in the correct place. Not sure though if other browsers have a similar language setting though, but I'd guess so.

Thanks, but it doesn't seem to work with Firefox. I'll close this issue.
