### ISSUE TITLE
Closing an asset account

### ISSUE THREAD

**Issue by ae-mo** [firefly-iii/firefly-iii#3139]
I am running Firefly III version 5.0.1.

**Description**
I have closed one of my asset accounts in real life, what's the best way to reflect this in Firefly?

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files (see https://bit.ly/FF3-get-logs)
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Good question! I've added it to the FAQ:

https://docs.firefly-iii.org/faq/financials#what-should-i-do-when-i-close-a-real-life-asset-account
