### ISSUE TITLE
Broken link to full description in welcome email

### ISSUE THREAD

**Issue by koenvervloesem** [firefly-iii/firefly-iii#3140]
**Bug description**
I am running Firefly III version 5.0.5, and my problem is: a broken link in the welcome email.

**Steps to reproduce**
Install and configure Firefly III, get a welcome email, click on the [full description](https://www.firefly-iii.org/description/) link, get a 404.

The link should probably be something like https://docs.firefly-iii.org/about-firefly-iii/introduction?

**Bonus points**

- [X] Nobody reported this bug before

There was a recent issue about [a typo](https://github.com/firefly-iii/firefly-iii/issues/3075) in the welcome email, but that person apparently didn't notice the broken link :-)

**Comment by JC5** [comment]
Nor did I, apparently. Thanks for noticing, I'll fix it!
