### ISSUE TITLE
deposit from API must be edited manually

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3141]
**Bug description**
I am running Firefly III version 5.0.5 and my problem is:

Adding a deposit through the API not always reflected in reports.

**Steps to reproduce**
Import paycheck deposit using the API. Run a default report, see that the deposit is present. Then import a second deposit. See that the deposit shows up in the transactions page of firefly, but refreshing the report does not update with the new deposit. By editing the transaction, and clicking save, it then appears in the reports correctly.

**Comment by Tieno** [comment]
I have a similar issue.

I create a transaction via the api, and then consult balance of the Account in the UI, it doesn't reflect this. Via the REST api I can see the updated balance.

I'm looking for a way to automate this so the balance and don't need to "update account" via UI to trigger a refresh.

**Comment by 4e868df3** [comment]
I think I was seeing the wrong account balance too at first. This time I left one alone an in 10 minutes or so it populated on its own. It seems like a cache or backend job that's not catching up right away. But it does right itself after a while. I've seen this happen in piggy banks too, where it will say X amount available for adding to piggy banks at the bottom of the page. Then when going to add to a piggy bank, the popup says I can add more than I actually am allowed to. Attempting to add the max amount the popup says I can generates a red banner error.

**Comment by JC5** [comment]
Thanks for reporting guys, but one at a time please.

For the transactions, I've added some extra cache-refreshing triggers to the API. This will be included in the next release. If you want to flush in the mean time, browse to `/flush` to clear your cache manually.

This should also fix the piggy banks because they may depend on the same cache.
