### ISSUE TITLE
add attachment icon at the end of description field when there is an attachement file in that entry

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#3142]
**Description**
It would be great to have the attachment icon added at the end of the description field as it use to be in version 4 that way it is easy to see which entries have attachements associated and which don't.

**Solution**
add attachement icon at the end of the description of an expense, transfer, deposit whenever that entry has an attachment

**What are alternatives?**
N/A

**Additional context**
It use to be present in version 4

**Bonus points**
![image](https://user-images.githubusercontent.com/8387568/75091368-43c07b80-5564-11ea-9a68-45a30d521595.png)

**Comment by JC5** [comment]
Yes, not sure where that went 🤔 

Thanks for letting me know!
