### ISSUE TITLE
Can't edit inital balance

### ISSUE THREAD

**Issue by SuperSandro2000** [firefly-iii/firefly-iii#3144]
**Bug description**
I am running Firefly III version 5.1.0-alpha.1 , and my problem is:

**Steps to reproduce**
Press edit on initial balance
be redirect to that account overview

**Extra info**

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Edit the account, not the transaction to change the initial balance.

**Comment by SuperSandro2000** [comment]
This is not intuitive and should redirect you to the right page.

**Comment by JC5** [comment]
It should be different in the next release :)

**Comment by SuperSandro2000** [comment]
Thanks
