### ISSUE TITLE
empty category view error

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3145]
5.1.0 Beta 1
Didn't notice this earlier.
Would have to redownload and install clean alpha.1 to see if it appeared since or before.
 
/chart/category/frontpage
result = []
console error : Unable to get property 'length' of undefined or null reference
Displays big and empty box on period with no entries. all other charts seem ok and display not enough info...

![image](https://user-images.githubusercontent.com/3269694/75111114-f1cb3480-55fb-11ea-8c83-5f7b151efcc3.png)

**Comment by JC5** [comment]
Nice find, should be fixed in the next release.

**Comment by GaryQ** [comment]
I regret to have to inform you that the fix broke it all. All charts now  not enough info including the account chart.

**Comment by JC5** [comment]
Whoops 😅

**Comment by GaryQ** [comment]
NOPE! Maybe best to leave it alone for today it's 7am and I'm done testing need some sleep LOL

You restored the accounts and fixed the original categories now working as expected so 👍 for that.
But  all the other charts now look like this when empty...

![Annotation 2020-02-22 220139](https://user-images.githubusercontent.com/3269694/75112409-3e693c80-5609-11ea-84c1-f71e3686d7d1.jpg)

**Comment by JC5** [comment]
You know the concept of time zones, right? Get some rest, I'll check out the edge cases.

**Comment by GaryQ** [comment]
Yes I do.. just with ADHD AND OCD it’s the concept of time in itself that my brain doesn’t understand. I see you posted another fix. Something to look forward to testing when I wake up later.

Cheers
