### ISSUE TITLE
Select accounts to show in graph - Customize dashboard

### ISSUE THREAD

**Issue by gelmistefano** [firefly-iii/firefly-iii#3147]
**Description**
It could be useful to customize the dashboard page. I would like to show in graph some accounts, and hide some other. For now is possible to hide some accounts, but this preference reflects on transaction and graph. I would like to decide is one account can be shown in graph and/or show the account's transactions in dashboard page.

**Possible Solution**
In preference page, allow to select which accounts are shown in main graph and which accounts must be shown in transactions sidebar in dashboard page.

Thanks for your work!
Regards,
S

**Comment by JC5** [comment]
Thanks for the compliments! Unfortunately, I'm not going to split this preference. Its' all or nothing.
