### ISSUE TITLE
Showing liabilities in category reports

### ISSUE THREAD

**Issue by marier-nico** [firefly-iii/firefly-iii#3149]
I am running Firefly III version 5.0.0.

**Description**
When creating reports for a given category, I'd like to be able to see the liabilities that were used to make transactions in those categories as well. For example, I have my credit card as a liability and I make sure to add a category to my transactions. When I make a report, I'd like to be able to include those transactions that were made with my credit card and not only my bank account.

I don't know if this is just a case that I should have created a credit card as an asset account, but somehow that doesn't feel right. I'm mainly wondering if this is my mistake of if it's a potential feature for the future!

Thanks for the amazing project :smile: 

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files (see https://bit.ly/FF3-get-logs)
- [x] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Although an asset account for a credit card is the easiest, this is something that's on my list to enable.

**Comment by marier-nico** [comment]
Yeah I suppose that's true, I just didn't really think of my credit card as an asset I guess :sweat_smile:

**Comment by JC5** [comment]
This also affects default reports, where liabilities are not shown. I'm pulling in #3155 with this one.

**Comment by JC5** [comment]
Should work in the new release. :+1:

**Comment by marier-nico** [comment]
Thanks for your work on this!
