### ISSUE TITLE
API auto complete end points

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#3150]
See title. Limited scope, limited search, so quick response.

**Comment by emansih** [comment]
Allow API consumers to decide the limit? Such as `/api/search?type=transaction&limit=10`

**Comment by JC5** [comment]
(notes to self)

1. A new controller to handle requests. Most auto complete code is already in [this file](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/Json/AutoCompleteController.php) so copy/paste away.
2. Needs routes in [api.php](https://github.com/firefly-iii/firefly-iii/blob/master/routes/api.php)
3. Needs [Swagger documentation](https://github.com/firefly-iii/api-docs-generator)

Also needs some time spent on consistent returns. Always return "title", "id".. something else? Formatted title? raw data?

**Comment by emansih** [comment]
How would auto complete work in this context? web sockets or plain HTTP GET?

**Comment by JC5** [comment]
I'm thinking plain GET but I know very little about web sockets. Would that be a better idea?

**Comment by emansih** [comment]
i'm not sure about resource usage. For GET, a poorly configured client would be sending quite a bit of network data back to backend. Imagine searching for each char updates, "Fancy Restaurant @ White House" contains 30 characters, a badly configured client would send 30 requests to the backend for suggestions.

**Comment by JC5** [comment]
Yeah that's true.

**Comment by JC5** [comment]
New autocomplete endpoints will be available in the new release. They will, consistently, return array in the following format that you can use in any auto-complete thing. All internal Firefly III autocomplete fields will now also use these endpoints.

```json
[
    {
        "id": 5,
        "name": "Object",
    }
]
```

This applies to ALL endpoints, regardless of the object. Some endpoints have extra fields.

- The endpoint for accounts exposes `name_with_balance` for asset accounts and liabilities, `type` for all accounts and `currency_*` for all accounts.
- A _separate_ endpoint for currencies exposes the currency `name` as `Euro (EUR)` instead of `Euro`.
- Both piggy bank endpoints (see below) expose currency information in `currency_*` fields.
- A separate piggy bank endpoint exposes `name_with_balance` next to `name` which includes balance info for the piggy bank (ie. `New couch ($300 / $500)`).
- Two transaction endpoints. They both expose both `description` and `name` (for consistency).
- The second one exposes both `name` and `description` as `#12: description`.
- The transaction type endpoint will always return US English transaction types.

The [API docs](https://api-docs.firefly-iii.org/) will be updated when the new release is out.

**Comment by JC5** [comment]
Will be fixed in the next release, closing now.

**Comment by psychowood** [comment]
For reference: #3748
