### ISSUE TITLE
Bulk Monthly Budget Setting

### ISSUE THREAD

**Issue by odin-bb** [firefly-iii/firefly-iii#3151]
Having to manually set the amount for each budget each month is extremely tedious. Is there a way to set the budgets once and have them replicate throughout the year?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/1819

**Comment by dugite-code** [comment]
@JC5 Would it be possible to at least show the budgeted amounts from the previous month next to the current budget?

This would make it easier to plan to reduce expenditure or match previous
