### ISSUE TITLE
Error when adding money to Piggy Bank

### ISSUE THREAD

**Issue by mark4409** [firefly-iii/firefly-iii#3152]
Hi, I've only had this up and running for a day but I'm encountering a problem when adding money to a newly created piggy bank.

I have created a current account and a savings account. The savings account has a balance of £40

I created a piggy bank for the savings account with a target of £300

Upon adding it, the information beneath shows correctly that £40 is available for piggy banks.

When I try and add £40 to the piggy bank, I get an error saying:

`Error! Could not add £40.00 to "Holiday".`

The log file is showing the following message each time I attempt:

`local.ERROR: Cannot add 40.00 because canAddAmount returned false.`

Am I doing something wrong here? 

I'm running v5.0.5 on PHP7.3-fpm and with Mariadb 10.4

**Comment by JC5** [comment]
It seems you’re doing things right. Is the piggy bank linked to the correct account? The one with 300 on it?

**Comment by mark4409** [comment]
OK, so I've gone back in this morning to try again so I can take a screenshot for you... except this time the process has worked perfectly despite me having made no changes since yesterday.  So something has obviously sorted itself out in the background.....

**Comment by mark4409** [comment]
![Screenshot_2020-02-26 Piggy banks » Firefly III](https://user-images.githubusercontent.com/38611328/75326452-9060cb00-5872-11ea-8208-c88e6163ae85.png)

For reference - this was the setup yesterday. As you can see, there's no reason why it should have errored whilst trying to add £40. I guess it's going to be a little difficult to troubleshoot now though!

**Comment by JC5** [comment]
That’s a tricky one indeed. Still, thanks for letting me know. Fuzzy problems like this can be caused by the internal cache routines. It’s on my list for a deep dive.
