### ISSUE TITLE
API Oauth2 with Client credentials

### ISSUE THREAD

**Issue by Ludo444** [firefly-iii/firefly-iii#3153]
I am trying this on demo instance of Firefly.

**Description**
I am trying to make custom transaction import in Python and have trouble with Client Credential Oauth2. Using the Python's `oauthlib` I am receiving token successfully however any subsequent API call comes back as `401 Unauthorized`. Not sure if I'm doing something wrong or there is an issue with it.

The testing in Swagger with web authentication works fine with second demo client, which uses web.

Here's the code I'm running:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

client_id = 1
client_secret = 'tfWoJQbmV88Fxej1ysoooFireflyIIIDemoToken'

client = BackendApplicationClient(client_id=client_id)
oauth = OAuth2Session(client=client)
firefly_token = oauth.fetch_token(token_url='https://demo.firefly-iii.org/oauth/token', client_id=client_id,
                                  client_secret=client_secret)

oauth = OAuth2Session(client_id, token=firefly_token)
headers = {'Content-Type': 'application/json', 'Accept': 'application/json'}
res = oauth.get('https://demo.firefly-iii.org/api/v1/transactions?page=1&start=2020-01-01&end=2020-02-29',
                headers=headers).json()
print(res)

```

One other thing I noticed is, that although I get a token, it doesn't appear in administration authorized apps section. Possibly it's not stored?

**Comment by JC5** [comment]
I don’t see you calling the authorize URL. Or did you not include it in your snippet?

You could also use the Personal Access Tokens if you don’t want or need user interaction. 

https://docs.firefly-iii.org/api/api

**Comment by Ludo444** [comment]
With Client Credentials the authorize endpoint is not used since the access token is returned directly, but I guess would explain why it's not working, if it's needed.

![image](https://user-images.githubusercontent.com/7080959/75384596-09016f00-58e7-11ea-89df-92e9b2fac9d2.png)

**Comment by JC5** [comment]
I’m not sure at the moment, I can’t check. I use the vanilla Laravel passport package. 

https://laravel.com/docs/6.x/passport

**Comment by Ludo444** [comment]
Thank's for mentioning personal access tokens, somehow missed that. That's sufficient for my needs.

But docs or profile page could mention that oauth2 is just for web flow.

**Comment by JC5** [comment]
I’ll pick that up, I appreciate the suggestion. There’s always a use case you don’t think about.
