### ISSUE TITLE
Default Financial Report Categories

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3155]
**Bug description**
I am running Firefly III version 5.0.5, and my problem is:

The default financial report, Category table, is not including all categories as rows. The `Sum (US Dollar)` row at the bottom of the Category table is very large and does not reflect a sum of all the categories immediately above this final row.

**Steps to reproduce**

Create default financial report for Feb 2020. View category table.
I created a transaction of category "arst" in demo site and was able to reproduce the bug.

**Extra info**
browser- firefox 73.0.1

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [ ] I have added a screenshot. **N/A Please see Demo Site**
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
See: https://github.com/firefly-iii/firefly-iii/issues/3149
