### ISSUE TITLE
Time Zone Codes?

### ISSUE THREAD

**Issue by WildToddMan** [firefly-iii/firefly-iii#3156]
I am running Firefly III version 5.0.5

I am in New York State in the US (Eastern Time Zone - UTC-5) How do I put this in the .env file?

I have tried it in many different formats and I always get an error or the site simply will not load. I have searched for a list of Time Zone Codes and I can't seem to find them for Firefly III.

**Extra info**
Unknown or bad timezone (NorthAmerica/NewYork)
I have tried: North America/New York, US/NewYork, US/NY, US/EST, UTC-5 and many more combinations and cities, states.

Please Help!

**Bonus points**

- [X ] I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by JC5** [comment]
Eastern Time should be “America/New_York”

**Comment by GaryQ** [comment]
Maybe adding a comment with the link in the docs and/or the .env file could be a good idea?

This wiki page is pretty complete... I assume?
Hehe  I just noticed that North Dakota has 3 levels and 3 different locations ie: America/North_Dakota/Center.

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by JC5** [comment]
That was my plan as well, thanks for the suggestion :)

**Comment by SuperSandro2000** [comment]
Did you already implement the suggestion?

**Comment by JC5** [comment]
That’s something that you can confirm yourself. The change is visible in the current version of the .env.example file. 

https://github.com/firefly-iii/firefly-iii/blob/master/.env.example#L28
