### ISSUE TITLE
Spectre import isn't merging deposit and withdrawal into transfer

### ISSUE THREAD

**Issue by mechanarchy** [firefly-iii/firefly-iii#3158]
I am running Firefly III version 5.0.5, with several asset accounts and the Spectre API. I'm finding that transfers between accounts in the same bank are not being detected as 'transfers' in Firefly; they're instead a 'withdrawal' from one (to the default `(no name)` account) and a 'deposit' into the other (from the `(no name)` account). Here's an edited screenshot from the Spectre import tag:

![image](https://user-images.githubusercontent.com/1166756/75604175-3558fd80-5b2a-11ea-895b-c639df275cc1.png)

Understandably there are two transaction records coming in from the API, but I would have thought there is some field that can be used to cross-reference the two records and produce one Firefly transfer from it. In looking at the account settings, I'm guessing the IBAN or BIC fields are usually used for this; however, _banks in Australia don't use IBANs_. Instead, each account is identified by a BSB number and account number. Ticket #2083 talks about supporting this, but it hasn't seen activity in a year. I've filled in the 'Account number' field on each of the accounts in Firefly with my bank account numbers, but I haven't put the BSBs in this box.

Is there something I've missed in my configuration? Is this something that's not supported? Any guidance would be appreciated.

**Comment by JC5** [comment]
That's not something I can really help, I'm afraid. Spectre isn't the most descriptive in their data and the import is mostly as is.

BSB numbers won't be added to Firefly III for the foreseeable future.

**Comment by mechanarchy** [comment]
Okay, no worries. Is there a way for me to see the raw Spectre import data? If there's some value set for IBAN in the incoming data stream I will try and update my accounts to match that.

On a semi-related note, the csv-importer repo doesn't have an issues tab, so I'll report it here:
the `jc5x/csv-importer:develop` docker image isn't starting correctly for me. I'm getting HTTP 500; turning `APP_DEBUG=true` says
> No application encryption key has been specified.

I suspect entrypoint.sh needs `php artisan key:generate`; I'm halfway through testing it though so I can't confirm this fixes the issue.

**Comment by JC5** [comment]
Thanks for the feedback and the edit. I’ll make sure it gets added to the default image.
