### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3159]
Hi,

I've just upgraded to 5.1.0-beta1. As I'm hunting down FR translation issues to fix them in Crowdin, I notice some strings are not available for translation:

1. Transaction link labels in /transactions/show/xxx although they are correctly translated when you create them in the dropdown list.
2. Footer: " Developed by James Cole, the source code is licensed under the AGPL-3.0-or-later. / You are running an BETA version. Be wary of bugs and issues."
3. Transaction type "withdrawal/deposit/transfer" that appears in the header of /transactions/show/xxx, just after the big "Transactions" title
4. Breadcrumb in /transactions/delete/xxx is not even labeled in English :-) breadcrumbs.delete_group
5. (not really a translation issue) String "Successfully deleted withdrawal ":description"" did not translation `:description` into the actual description, the placeholder remained.
6. Not tested yet in 5.1.0 but I remember that the email sent upon creation of a recurring transaction was sent in English, and I couldn't find the string in Crowdin for it.
7. When creating a reconciliation transaction, the label is correctly translated but the source account isn't translated ("<account> reconciliation").

I hope I was thorough enough in my descriptions, I didn't want to screenshot everything.

**Comment by JC5** [comment]
Thanks for letting me know. I'll pick it up. The footer is probably going to remain in English and the email messages too.

**Comment by sephrat** [comment]
Thanks.
I don't mind about the footer, but the email notification would be really nice to have.

**Comment by JC5** [comment]
1. Fixed
2. Partially fixed.
3. Fixed
4. Fixed
5. I can't replicate this. But in the French translations, I see ":name" instead of ":description". Check out firefly.deleted_withdrawal, firefly.deleted_deposit, firefly.deleted_transfer.
6. Won't fix.
7. Fixed.

Thanks again for reporting :)

**Comment by sephrat** [comment]
Thanks! I fixed the translations for 5.
I'm a bit sad for 6. but as I said to myself "maybe it's time to 'unrust' my PHP skills and contribute" and had a look at the code, I understood why that's not an easy fix. I'd rather not make a mess and leave it as is!

**Comment by sephrat** [comment]
As I had a look at how you translated the alpha/beta thing, can we not do something similar for email twigs?
