### ISSUE TITLE
Error 404 when deleting a reconciliation transaction

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3160]
I am running Firefly III version 5.1.0-beta.1, and my problem is:

After I delete a reconciliation transaction, I get redirected to /transactions/reconciliation which gives a 404 error.
The transaction is still successfully deleted though, it's not that big of an issue.

**Comment by JC5** [comment]
Thanks, I'll pick it up.

**Comment by JC5** [comment]
Will be fixed in the next release :+1:
