### ISSUE TITLE
When exporting all transactions from Firefly, all amounts are with minus sign  

### ISSUE THREAD

**Issue by kczav** [firefly-iii/firefly-iii#3161]
Firefly-iii vers. 5.0.1
Function: Import and export => Export data

When exporting all transactions from Firefly into a csv file, all amounts are with minus sign whether the transaction is a withdrawal or a deposit.
I would have expected amount for deposit to be a positive number

Cheers

**Comment by JC5** [comment]
It doesn't really matter. The source and destination account determine the flow of money. I can make them all positive?

**Comment by kczav** [comment]
No need. I thought that was a bug, but if the export behave the way it should, that's fine. I use the exported data against data from my actual accounts to make sure I do not miss or add already existing transactions before an import. This because I had same transactions added twice in previous import using previous version of ff. Well long story short, I can deal with it, no need to spend time on this. Thank you for your very good job.

**Comment by JC5** [comment]
:+1:
