### ISSUE TITLE
Deleting initial default rule creates a new default rule

### ISSUE THREAD

**Issue by johnwhelchel** [firefly-iii/firefly-iii#3162]
**Bug description**
I am running Firefly III version 5.0.0, and my problem is: When I delete the default rule that is marked safe to delete, it is recreated.

**Steps to reproduce**
1. Go to the "rules" tab.
2. Delete the rule
3. See that the rule still exists

When looking in the database, it looks like the first rule is deleted, but another is created.

**Extra info**
MacOS Mojave, Firefox browser

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/4014841/75633363-1c0b8c00-5bd2-11ea-8282-5cb983cf7f74.png">

**Comment by JC5** [comment]
Yes. By way of example, Firefly III will always create a rule if no rules exist.

**Comment by GaryQ** [comment]
Yep, that's one "rule' I figured out the hard way... have to create one before you delete that one.
The reason does make logical sense though.
