### ISSUE TITLE
Budgets page issue

### ISSUE THREAD

**Issue by Kyle9982** [firefly-iii/firefly-iii#3163]
**Bug description**
I am running Firefly III version 5.0.4 and my problem is:

The budgets page is broken, and with 100% not load do to a simple error
![image](https://user-images.githubusercontent.com/42327407/75636207-9f78ad80-5bd1-11ea-85f5-89d65b1dcc05.png)

**Comment by JC5** [comment]
It seems you’re not running PHP 7.3, which is why you’re getting this error.

**Comment by Kyle9982** [comment]
![image](https://user-images.githubusercontent.com/42327407/75708328-7873b780-5c75-11ea-96eb-aa3d923b9920.png)
I am indeed running 7.3, would it be a missing module???

------Modules--------
apc                                                                                                                                                                                                                                                      
apcu                                                                                                                                                                                                                                                     
calendar                                                                                                                                                                                                                                                 
Core                                                                                                                                                                                                                                                     
ctype                                                                                                                                                                                                                                                    
curl                                                                                                                                                                                                                                                     
date                                                                                                                                                                                                                                                     
dom                                                                                                                                                                                                                                                      
exif                                                                                                                                                                                                                                                     
fileinfo                                                                                                                                                                                                                                                 
filter                                                                                                                                                                                                                                                   
ftp                                                                                                                                                                                                                                                      
gd                                                                                                                                                                                                                                                       
gettext                                                                                                                                                                                                                                                  
hash                                                                                                                                                                                                                                                     
iconv                                                                                                                                                                                                                                                    
igbinary                                                                                                                                                                                                                                                 
imagick                                                                                                                                                                                                                                                  
json                                                                                                                                                                                                                                                     
ldap                                                                                                                                                                                                                                                     
libxml                                                                                                                                                                                                                                                   
mbstring                                                                                                                                                                                                                                                 
memcached                                                                                                                                                                                                                                                
msgpack                                                                                                                                                                                                                                                  
mysqli                                                                                                                                                                                                                                                   
mysqlnd                                                                                                                                                                                                                                                  
openssl                                                                                                                                                                                                                                                  
pcntl                                                                                                                                                                                                                                                    
pcre                                                                                                                                                                                                                                                     
PDO                                                                                                                                                                                                                                                      
pdo_mysql                                                                                                                                                                                                                                                
Phar                                                                                                                                                                                                                                                     
posix                                                                                                                                                                                                                                                    
readline                                                                                                                                                                                                                                                 
redis                                                                                                                                                                                                                                                    
Reflection                                                                                                                                                                                                                                               
session                                                                                                                                                                                                                                                  
shmop                                                                                                                                                                                                                                                    
SimpleXML                                                                                                                                                                                                                                                
sockets                                                                                                                                                                                                                                                  
sodium                                                                                                                                                                                                                                                   
SPL                                                                                                                                                                                                                                                      
standard                                                                                                                                                                                                                                                 
sysvmsg                                                                                                                                                                                                                                                  
sysvsem                                                                                                                                                                                                                                                  
sysvshm                                                                                                                                                                                                                                                  
tokenizer                                                                                                                                                                                                                                                
wddx                                                                                                                                                                                                                                                     
xml                                                                                                                                                                                                                                                      
xmlreader                                                                                                                                                                                                                                                
xmlwriter                                                                                                                                                                                                                                                
xsl                                                                                                                                                                                                                                                      
Zend OPcache                                                                                                                                                                                                                                             
zip                                                                                                                                                                                                                                                      
zlib

**Comment by JC5** [comment]
Are you sure your webserver is also using PHP 7.3?
