### ISSUE TITLE
Question: Can I track what I paid to a friend?

### ISSUE THREAD

**Issue by filipe-silva** [firefly-iii/firefly-iii#3165]
Hi everyone!

So I've racking my brain but can't seem to come up with a good way to track expenses on people.
In some ways it's easy, for example, I give X money to Y person, in this case I can just create a liability or in my case I create an expense account with the name of the person.

However this is the tricky scenario, let's say I go out to the bar Z and I spent 10€ in beer for my friends. In this case, I know I paid 10€ to bar Z so I make a transaction for that. But I also want to know that those 10€ I paid 5 to friend A and 5 to friend B.
But since I already have the transaction of 10€ to bar Z, how can I say that, that money was me paying something for my friends?

P.S. I can also pay you a beer if there's a solution xD

**Comment by GaryQ** [comment]
> P.S. I can also pay you a beer if there's a solution xD

^^^^ That's hilarious 👍 

The simple answer is to add the following formula in the  transaction notes field: 
(Bar + Friends + Beer) = (Great Time  - 10 Euros) = 1 single Transaction : D

**Comment by JC5** [comment]
Does this help? 

https://docs.firefly-iii.org/faq/financials#what-do-i-do-with-people-who-pay-me-back

**Comment by filipe-silva** [comment]
Thank you both!
The budget seems the way for me, I create one for friend X and associate the transaction.
If the same transaction has something that was for me as well, I create a split and (though it's the same account) one part goes to the budget.

P.S. @GaryQ 🍻
