### ISSUE TITLE
Nginx with HTTPS setup

### ISSUE THREAD

**Issue by oleksiiha** [firefly-iii/firefly-iii#3167]
I am running Firefly III version 5.0.5.

**Description**
I started to use reverse proxy (nginx) on a separate machine on my network and installed certificate to use with firefly. Everything went smoothly except graphs on the website now. They are requested with http and are not visible and site appears as not secure.

**Extra info**
 * Firefly installed with docker
 * Separate machine has nginx installed and certificate installed with let's encrypt

**Comment by JC5** [comment]
I have a similar setup. This is my nginx config:

```
# http
server {
        listen 80;
	listen [::]:80;
        server_name example.com;
        return 301 https://$host$request_uri;
}

# https
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;

	root /var/www/html;

	index index.html;

	server_name example.com;

	# Firefly III
        location / {
		#rewrite ^/geld(/.*)$ $1 break;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
				proxy_set_header Host $host;
                client_max_body_size 64M;
                proxy_pass http://127.0.0.1:8002$uri$is_args$args;
				proxy_read_timeout 300s;
        }

	ssl on;
	ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
	include /etc/letsencrypt/options-ssl-nginx.conf;
}
```

**Comment by oleksiiha** [comment]
I adjusted some fields in my config to match yours, but the result did not change
Here is my nginx config now:
```
server {
  listen 80;
  listen [::]:80;
  server_name firefly.thatsmyname.xyz;
  return 301 https://$host$request_uri;
}

server {
  server_name firefly.redbeard.xyz;
  set $upstream 192.168.1.216:80;
  location / {
    proxy_pass_header Authorization;
    proxy_pass http://$upstream$uri$is_args$args;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    client_max_body_size 64M;
    proxy_read_timeout 300s;
  }

  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  ssl on;
  ssl_certificate /etc/letsencrypt/live/firefly.thatsmyname.xyz/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/firefly.thatsmyname.xyz/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

```
But result is the same. Here how it looks:
![Screenshot 2020-03-04 at 11 13 31](https://user-images.githubusercontent.com/116974/75869043-4b580e00-5e09-11ea-8634-b45580e25b11.png)

**Comment by JC5** [comment]
So the URL is exactly right, except for the http / https part? And your reverse proxy is https?

You can try `proxy_set_header X-Forwarded-Proto https;`

**Comment by oleksiiha** [comment]
@JC5 Yes, I see that form action url contains http, and request is to http, it's not proxied. `proxy_set_header X-Forwarded-Proto https;` has no effect on this;

@Lawri-van-Buel Thank you for this config, but I think the problem is somewhere in proxying part, your config suggest that you are not proxying your requests to different machine.

**Comment by Lawri-van-Buel** [comment]
I am Proxying it to a different process same thing as to a different machine, I do the same for other products/ applications that do cross over machine barriers. (It’s just the proxy_pass line that is different In most cases and just having a catch all location instead of passing just the php files through a proxy)

**Comment by oleksiiha** [comment]
After playing around for several days I did not succeed with this. All the requests  that contain `http://` inside firefly app are not redirected to https with my proxy, and this is more about my ability to cook the nginx proxy probably. I reverted to using http.

**Comment by ilvez** [comment]
I'll just leave my configuration here. I use letsencrypt for certificates. XXX is my domain name:

```
server {
  root /var/www/firefly-iii/public/;

  index index.php;

  server_name XXX;

  location / {
    try_files $uri $uri/ /index.php?$query_string;
    autoindex on;
    sendfile off;
  }

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;

    fastcgi_pass unix:/run/php/php7.4-fpm.sock;
  }

  listen [::]:443 ssl ipv6only=on; # managed by Certbot
  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/XXX/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/XXX/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
  if ($host = XXX) {
      return 301 https://$host$request_uri;
  } # managed by Certbot

  listen 80 default_server;
  listen [::]:80 default_server;

  server_name XXX;
    return 404; # managed by Certbot
}
```

**Comment by xzfantom** [comment]
I know, issue is closed by bot, but...
> After playing around for several days I did not succeed with this. All the requests that contain `http://` inside firefly app are not redirected to https with my proxy, and this is more about my ability to cook the nginx proxy probably. I reverted to using http.

I had same issue. Changed nginx config back and forth, nothing helped. Finally wanted to edit .env file to enable debug and found there option for reverse proxy - TRUSTED_PROXIES=**, after restarting docker https works just fine.

**Comment by cauethenorio** [comment]
thanks a lot @xzfantom, you saved my day

**Comment by ADIX7** [comment]
To @xzfantom's answer: if you use docker-compose you also need to remove the container and do a docker-compose up after modifying the .env file. It took me 1 hour of debugging...

**Comment by MaxJa4** [comment]
I was struggling for 1-1.5 hrs with docker-compose too... it finally applied the changes (Trusted-Proxies as stated above) after a 'docker-compose down' and then 'docker-compose up --force-recreate -d' afterwards. Otherwise nothing helped. Thanks @ADIX7!
