### ISSUE TITLE
(Left to) Spend not calculated correctly when not viewing a single month

### ISSUE THREAD

**Issue by svenahrensnl** [firefly-iii/firefly-iii#3172]
**Bug description**
I am running Firefly III version 5.0.0 and my problem is:

When choosing a different period then one complete month, the amount (left to) spend is calculated wrong.

Left to spend:
https://i.imgur.com/5cP4O6r.png
https://i.imgur.com/S55ILQt.png
https://i.imgur.com/nSccIj6.png

**Steps to reproduce**
- Create budgets for at least 2 months;
- Have transactions linked to those budgets
(- Check if you aren't overspending;)
- Select a period other then a single month (last 30 days, custom range);
- The Left to Spend amount drops to a negative amount, even though there is still budget left

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nice find, this will be fixed in the next release. Keep in mind it's tricky to make this accurate, because it also depends on what you've configured in /budgets under "available amount".

**Comment by svenahrensnl** [comment]
Thanks for the quick fix!
