### ISSUE TITLE
Transaction information doesnt show amounts

### ISSUE THREAD

**Issue by Tuffert** [firefly-iii/firefly-iii#3173]
**Bug description**
I am running Firefly III version 5.1.0, and my problem is:

If you use any other language than english, the transaction.show-Route doesnt show amounts.
/resources/views/v1/transactions/show.twig compare the type with the english words (`if type == 'Withdrawal' or type == 'Deposit'`), but in this case `type` is translated into the users language.

**Steps to reproduce**
Change language in preferences and open an transaction.

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [ ] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Hah. That’s a silly bug. Nice find, I never even noticed. Will pick it up!
