### ISSUE TITLE
UnRaid - Firefly iii 5.1.0 Docker - Will Not Function

### ISSUE THREAD

**Issue by Nightmareish** [firefly-iii/firefly-iii#3174]
**Bug description**
I am running Firefly III version 5.1.0, latest docker image, and my problem is:
The webui returns 'Whoops there was a fatal error ... bla bla' no matter what I do.
Logs don't tell me anything helpful, either. This is the first time I'm trying to use this software.

**Steps to reproduce**
1. Create new Database in PostgreSQL 11 (official docker image) with the command
`CREATE DATABASE fireflydb`
2. Include proper params in docker template to connect to PostgreSQL instance and appropriate database
3. Ensure that all params in the docker template are correct
4. Run the docker.
5. It outputs this on FIRST RUN, and fails to let me in to the UI.

**Docker Template used (mostly defaults)**
https://imgur.com/dfi2CNO

**Log**
> Now parsing _FILE variables.
> done!
> Making directories...
> SQL connection data: (pw is hidden)
> DB_CONNECTION: ''
> DB_HOST: 'postgres'
> DB_PORT: '5432'
> DB_DATABASE: 'fireflydb'
> DB_USERNAME: 'postgres'
> Touch DB file (if SQLite)...
> Run chown on /mnt/cache/appdata/firefly-iii//storage...
> Run chmod on /mnt/cache/appdata/firefly-iii//storage...
> Remove log file...
> Dump auto load...
> Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> Generated optimized autoload files containing 5404 classes
> Discover packages...
> Discovered Package: adldap2/adldap2-laravel
> Discovered Package: davejamesmiller/laravel-breadcrumbs
> Discovered Package: fideloper/proxy
> Discovered Package: jc5/google2fa-laravel
> Discovered Package: laravel/passport
> Discovered Package: laravelcollective/html
> Discovered Package: nesbot/carbon
> Discovered Package: rcrowe/twigbridge
> Package manifest generated successfully.
> Wait for the database.
> wait-for-it.sh: waiting 60 seconds for postgres:5432
> wait-for-it.sh: postgres:5432 is available after 0 seconds
> DB is up. Time to execute artisan commands.
> Run various artisan commands...
> Application cache cleared!
> Running migration commands...
> CreateDB does not apply to "", skipped.
> CreateDB does not apply to "", skipped.
> Migration table created successfully.
> Migrating: 2016_06_16_000000_create_support_tables
> Migrated: 2016_06_16_000000_create_support_tables (0.3 seconds)
> Migrating: 2016_06_16_000001_create_users_table
> Migrated: 2016_06_16_000001_create_users_table (0.02 seconds)
> Migrating: 2016_06_16_000002_create_main_tables
> Migrated: 2016_06_16_000002_create_main_tables (0.75 seconds)
> Migrating: 2016_08_25_091522_changes_for_3101
> Migrated: 2016_08_25_091522_changes_for_3101 (0.03 seconds)
> Migrating: 2016_09_12_121359_fix_nullables
> Migrated: 2016_09_12_121359_fix_nullables (0.06 seconds)
> Migrating: 2016_10_09_150037_expand_transactions_table
> Migrated: 2016_10_09_150037_expand_transactions_table (0.01 seconds)
> Migrating: 2016_10_22_075804_changes_for_v410
> Migrated: 2016_10_22_075804_changes_for_v410 (0.04 seconds)
> Migrating: 2016_11_24_210552_changes_for_v420
> Migrated: 2016_11_24_210552_changes_for_v420 (0.01 seconds)
> Migrating: 2016_12_22_150431_changes_for_v430
> Migrated: 2016_12_22_150431_changes_for_v430 (0.03 seconds)
> Migrating: 2016_12_28_203205_changes_for_v431
> Migrated: 2016_12_28_203205_changes_for_v431 (0.05 seconds)
> Migrating: 2017_04_13_163623_changes_for_v440
> Migrated: 2017_04_13_163623_changes_for_v440 (0.05 seconds)
> Migrating: 2017_06_02_105232_changes_for_v450
> Migrated: 2017_06_02_105232_changes_for_v450 (0.01 seconds)
> Migrating: 2017_08_20_062014_changes_for_v470
> Migrated: 2017_08_20_062014_changes_for_v470 (0.1 seconds)
> Migrating: 2017_11_04_170844_changes_for_v470a
> Migrated: 2017_11_04_170844_changes_for_v470a (0.01 seconds)
> Migrating: 2018_01_01_000001_create_oauth_auth_codes_table
> Migrated: 2018_01_01_000001_create_oauth_auth_codes_table (0.03 seconds)
> Migrating: 2018_01_01_000002_create_oauth_access_tokens_table
> Migrated: 2018_01_01_000002_create_oauth_access_tokens_table (0.05 seconds)
> Migrating: 2018_01_01_000003_create_oauth_refresh_tokens_table
> Migrated: 2018_01_01_000003_create_oauth_refresh_tokens_table (0.02 seconds)
> Migrating: 2018_01_01_000004_create_oauth_clients_table
> Migrated: 2018_01_01_000004_create_oauth_clients_table (0.04 seconds)
> Migrating: 2018_01_01_000005_create_oauth_personal_access_clients_table
> Migrated: 2018_01_01_000005_create_oauth_personal_access_clients_table (0.02 seconds)
> Migrating: 2018_03_19_141348_changes_for_v472
> Migrated: 2018_03_19_141348_changes_for_v472 (0.02 seconds)
> Migrating: 2018_04_07_210913_changes_for_v473
> Migrated: 2018_04_07_210913_changes_for_v473 (0.02 seconds)
> Migrating: 2018_04_29_174524_changes_for_v474
> Migrated: 2018_04_29_174524_changes_for_v474 (0.02 seconds)
> Migrating: 2018_06_08_200526_changes_for_v475
> Migrated: 2018_06_08_200526_changes_for_v475 (0.19 seconds)
> Migrating: 2018_09_05_195147_changes_for_v477
> Migrated: 2018_09_05_195147_changes_for_v477 (0.01 seconds)
> Migrating: 2018_11_06_172532_changes_for_v479
> Migrated: 2018_11_06_172532_changes_for_v479 (0.01 seconds)
> Migrating: 2019_01_28_193833_changes_for_v4710
> Migrated: 2019_01_28_193833_changes_for_v4710 (0.08 seconds)
> Migrating: 2019_02_05_055516_changes_for_v4711
> Migrated: 2019_02_05_055516_changes_for_v4711 (0.06 seconds)
> Migrating: 2019_02_11_170529_changes_for_v4712
> Migrated: 2019_02_11_170529_changes_for_v4712 (0.02 seconds)
> Migrating: 2019_03_11_223700_fix_ldap_configuration
> Migrated: 2019_03_11_223700_fix_ldap_configuration (0.02 seconds)
> Migrating: 2019_03_22_183214_changes_for_v480
> Migrated: 2019_03_22_183214_changes_for_v480 (0.03 seconds)
> Migrating: 2019_11_30_000000_create_2fa_token_table
> Migrated: 2019_11_30_000000_create_2fa_token_table (0.04 seconds)
> Migrating: 2019_12_28_191351_make_locations_table
> Migrated: 2019_12_28_191351_make_locations_table (0.03 seconds)
> Seeding: AccountTypeSeeder
> Seeded: AccountTypeSeeder (0.13 seconds)
> Seeding: TransactionCurrencySeeder
> Seeded: TransactionCurrencySeeder (0.27 seconds)
> Seeding: TransactionTypeSeeder
> Seeded: TransactionTypeSeeder (0.07 seconds)
> Seeding: PermissionSeeder
> Seeded: PermissionSeeder (0.03 seconds)
> Seeding: LinkTypeSeeder
> Seeded: LinkTypeSeeder (0.05 seconds)
> Seeding: ConfigSeeder
> [2020-03-06 17:22:40] production.WARNING: No database version entry is present. Database is assumed to be OLD (version 1).
> 
> Seeded: ConfigSeeder (0.03 seconds)
> Database seeding completed successfully.
> Going to decrypt the database.
> Decrypted the data in table "accounts".
> Decrypted the data in table "attachments".
> Decrypted the data in table "bills".
> Decrypted the data in table "budgets".
> Decrypted the data in table "categories".
> Decrypted the data in table "piggy_banks".
> Decrypted the data in table "preferences".
> Decrypted the data in table "tags".
> Decrypted the data in table "transaction_journals".
> Decrypted the data in table "transactions".
> Decrypted the data in table "journal_links".
> Done!
> Running upgrade commands...
> All split journal transaction identifiers are correct.
> Verified and fixed transaction identifiers in 0.06 seconds.
> Found no split transaction journals. Nothing to do.
> Migrate split journals to groups in 0.05 seconds.
> No need to convert transaction journals.
> Migrate all journals to groups in 0 seconds.
> No journals to migrate to groups.
> All accounts are OK.
> Verified and fixed account currencies in 0.04 seconds.
> All transfers have correct currency information.
> Verified and fixed currency information for transfers in 0.05 seconds.
> Verified 0 transaction(s) and journal(s).
> Verified and fixed transaction currencies in 0.06 seconds.
> No notes to migrate.
> Migrated notes in 0.05 seconds.
> No notes to migrate.
> Migrated notes in 0.05 seconds.
> All attachments are OK.
> Migrated attachment notes in 0.06 seconds.
> All bills are OK.
> Verified and fixed bills in 0.05 seconds.
> All budget limits are correct.
> Verified budget limits in 0.04 seconds.
> No incorrectly stored credit card liabilities.
> Check 0 transaction journal(s) for budget info.
> Check 0 transaction journal(s) for category info.
> Updated category and budget info for all transaction journals in 0.05 seconds.
> All account meta is OK.
> Fixed account meta data in 0.06 seconds.
> No recurrence meta data migrated.
> Migrated recurrence meta data in 0.05 seconds.
> Running verification commands...
> All piggy bank events are correct.
> Verified the content of 0 piggy bank events in 0.02 seconds.
> All link types OK!
> Verified link types in 0.03 seconds
> All access tokens OK!
> Verify access tokens in 0.02 seconds.
> All link types OK!
> Verified link types in 0.03 seconds
> All access tokens OK!
> Verify access tokens in 0.02 seconds.
> All transaction journals have correct bill information.
> Verified bills / journals in 0.03 seconds
> 0 different currencies are currently in use.
> All currencies are correctly enabled or disabled.
> Verified currencies in 0.03 seconds.
> No invalid budget/journal entries.
> Verified budget/journals in 0.03 seconds.
> Amount integrity OK!
> Verified amount integrity in 0.02 seconds
> No zero-amount transaction journals.
> Verified zero-amount integrity in 0.02 seconds
> No orphaned transactions.
> No orphaned accounts.
> Verified orphans in 0.02 seconds
> No uneven transaction journals.
> No empty transaction journals.
> Verified empty journals in 0 seconds
> Verified empty groups in 0.02 seconds
> All account types are OK!
> Verifying account types took 0.03 seconds
> All meta fields are correct.
> Renamed meta fields in 0.02 seconds
> Going to verify 0 opening balance transactions.
> There was nothing to fix in the opening balance transactions.
> Verified all transaction group and journal title lengths in 0.02 seconds.
> Corrected recurring transactions 0.03 seconds.
> Running report commands...
> Report on empty objects finished in 0.04 seconds
> Report on total sum finished in 0.02 seconds
> Stored OAuth keys in database.
> Generating new OAuth keys...
> Encryption keys already exist. Use the --force option to overwrite them.
> [2020-03-06 17:22:51] production.INFO: OAuth client generated but no user associated.
> Personal access client created successfully.
> Client ID: 1
> Client secret: NaCMdSfCjHqq4Fjc3aUlGky0KWnzyWanlyApFeZ9
> [2020-03-06 17:22:51] production.INFO: OAuth client generated but no user associated.
> Password grant client created successfully.
> Client ID: 2
> Client secret: gSaPINOaa5JcRNLfLAmu4kj8JGdkDZzMuw7onUyl
> Encryption keys already exist. Use the --force option to overwrite them.
> [2020-03-06 17:22:51] production.INFO: OAuth client generated but no user associated.
> Personal access client created successfully.
> Client ID: 1
> Client secret: NaCMdSfCjHqq4Fjc3aUlGky0KWnzyWanlyApFeZ9
> [2020-03-06 17:22:51] production.INFO: OAuth client generated but no user associated.
> Password grant client created successfully.
> Client ID: 2
> Client secret: gSaPINOaa5JcRNLfLAmu4kj8JGdkDZzMuw7onUyl
> Updated version.
> 
> Application cache cleared!
> Configuration cache cleared!
> Configuration cached successfully!
> Run chown on /mnt/cache/appdata/firefly-iii//storage
> +------------------------------------------------------------------------------+
> | |
> | Thank you for installing Firefly III, v5.1.0! |
> | |
> | |
> +------------------------------------------------------------------------------+
> Go!
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.10. Set the 'ServerName' directive globally to suppress this message
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.10. Set the 'ServerName' directive globally to suppress this message
> [Fri Mar 06 17:22:52.668586 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.15 OpenSSL/1.1.1d configured -- resuming normal operations
> [Fri Mar 06 17:22:52.668643 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
> 192.168.1.207 - - [06/Mar/2020:17:23:05 -0500] "GET / HTTP/1.1" 500 1790 "http://192.168.1.xxx/Dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
> 192.168.1.207 - - [06/Mar/2020:17:23:05 -0500] "GET /v1/fonts/lato-100.woff2 HTTP/1.1" 304 182 "http://192.168.1.xxx:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
> 

**Bonus points**

- [X] Nobody reported this bug before
- [X] I have added a stack trace from my log files.

**Comment by Nightmareish** [comment]
Unraid's Community Applications docker template is totallllly broken. I eliminated some keys from the template and it works just fine. PEOPLE SUCK!

**Comment by Mattyfaz** [comment]
@Nightmareish can you share your firefly config in UnRaid? I am struggling to get it working as well.

**Comment by Nightmareish** [comment]
Certainly @Mattyfaz. I took a snippet of the template XML with my config that works great.
`  <Networking>
    <Mode>proxynet</Mode>
    <Publish>
      <Port>
        <HostPort>5080</HostPort>
        <ContainerPort>80</ContainerPort>
        <Protocol>tcp</Protocol>
      </Port>
    </Publish>
  </Networking>
  <Data>
    <Volume>
      <HostDir>/mnt/cache/appdata/firefly-iii/export/</HostDir>
      <ContainerDir>/var/www/firefly-iii/storage/export</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
    <Volume>
      <HostDir>/mnt/cache/appdata/firefly-iii/upload/</HostDir>
      <ContainerDir>/var/www/firefly-iii/storage/upload</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
  </Data>
  <Environment>
    <Variable>
      <Value></Value>
      <Name>APP_KEY</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value></Value>
      <Name>DB_HOST</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value></Value>
      <Name>DB_PORT</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value></Value>
      <Name>DB_DATABASE</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value></Value>
      <Name>DB_USERNAME</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value></Value>
      <Name>DB_PASSWORD</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value></Value>
      <Name>APP_URL</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value>**</Value>
      <Name>TRUSTED_PROXIES</Name>
      <Mode/>
    </Variable>
  </Environment>`

Also make sure to remove any TemplateURL that exists in the XML or Unraid might automatically add back in the bogus env vars. Happy accounting! :)

**Comment by Dreytac** [comment]
I just ran into this problem myself. The issue is the FIREFLY_PATH variable. It's pointing to the appdata folder which would be fine if the container actually copied Firefly into that directory to begin with.

I think you're getting the error because Firefly isn't where the template wants it to be. Deleting the FIREFLY_PATH variable and it worked fine for me.
