### ISSUE TITLE
existed categories/tags hint required when adding new Transactions

### ISSUE THREAD

**Issue by toyqiu** [firefly-iii/firefly-iii#3175]
- I would like Firefly III to show hints about existed categories/tags when adding new Transactions.
- I newly-created several categories and tags for my future  expenses ,in order to get my expenses sorted. But I find that when creat a new expense with category or tags,I have to remember the categories/tags that what I have created exactly.

**Comment by JC5** [comment]
I'm not sure if I understand what you mean. Tags and categories are auto-completed.

**Comment by toyqiu** [comment]
I gave it another try,it works.
not sure why it wasn't auto-completed or be shown.
sorry for bothering
