### ISSUE TITLE
Weird error mesage...

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3178]
Was sure I hit submit... oh well 

Noticed this weird error message create transaction (blank) 
Reproduced on demo site 
Click submit on create transaction without an amount. I just tested blank submit
pic is from demo site

![snip1](https://user-images.githubusercontent.com/3269694/76254716-f22e1700-621a-11ea-9f7f-bddeb8828e7c.jpg)

**Comment by JC5** [comment]
Yep. It’s coming directly from the API. I’m going to leave it for now, other issues include the work that needs to be done to fix this.

**Comment by SuperSandro2000** [comment]
bump
