### ISSUE TITLE
Finnish locale not properly configured in firefly image

### ISSUE THREAD

**Issue by BluePerfectOne** [firefly-iii/firefly-iii#3179]
**Bug description**
I am running Firefly III version 5.1.0 in Docker, and my problem is:

Selecting Finnish language will mess up the numeric values.

The Finnish locale is misconstructed in the /env/locale.gen -file.
Is "fi_FI.UTF-8" but should instead be "fi_FI.UTF-8 UTF-8"

**Steps to reproduce**
Select Finnish language and observe the issue.

Fix the text in /env/locale.gen and run "locale-gen" and the problem gets fixed.

**Extra info**
Debug information generated at 2020-03-10 01:44:48 Europe/Helsinki for Firefly III version **5.1.0**.

| Variable | Content |
| --- | --- |
| FF version | 5.1.0 |
| FF API version | 1.0.1 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| PHP version | 7.3.15 |
| Display errors | Off |
| Session start | 2020-03-01 00:00:00 |
| Session end | 2020-03-31 23:59:59 |
| Session first | 2019-12-05 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

- [X] Nobody reported this bug before
- [-] I have added a stack trace from my log files.
- [-] I have added a screenshot.
- [X] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nicely spotted, will be fixed in the image.

**Comment by JC5** [comment]
The 5.1.0 image has been rebuilt and the problem should be fixed.
