### ISSUE TITLE
How to reset twoFactor authentication ?

### ISSUE THREAD

**Issue by RicardoHS** [firefly-iii/firefly-iii#3180]
Following the instructions on #2228 does not work anymore. 

I have done:
Log into my docker that contains the database (postgres in my case)
> $ docker exect -it <container_id> bash

Log into the postgres shell (the database and user names can be found in the docker-compose file)
> $ psql <database_name> <user_name>

Exect this line to remove the twoFactor configuration
> $ delete from preferences where name like 'twoFactorAuth%'

Log into the app container and run to clear the cache
> $ php artisan cache:clear

But the app continue to request the two Factor

**Comment by JC5** [comment]
Indeed. Those instructions are out of date. I just realised that Firefly III itself also gives bad instructions. 

Open table `users` and set `mfa_secret` to `NULL` for the user for who you want to disable 2FA.

**Comment by RicardoHS** [comment]
so just to clarify for others, in the psql shell just run

> update users set mfa_secret = NULL;

**Comment by JC5** [comment]
That will reset it for everybody though. If you're a single user, no worries.
