### ISSUE TITLE
csv importer stalls out 

### ISSUE THREAD

**Issue by pressqu** [firefly-iii/firefly-iii#3181]
Using the latest csv importer I tried importing a csv file to a newly created bank account. 
After a few seconds I recieved a red error message telling me to consult the error logs. 

For some reason, the file I've selected did not upload and the importer starts running in an endless loop. 
<img width="1036" alt="" src="https://user-images.githubusercontent.com/1499842/76362218-8a5df600-6318-11ea-9d85-691726067be6.png">

**Comment by pressqu** [comment]
![debug log](https://user-images.githubusercontent.com/1499842/76361632-51715180-6317-11ea-8e2f-1eb04d11a106.png)

**Comment by JC5** [comment]
Could you show what the repetition is? I wonder what's happening exactly.

**Comment by pressqu** [comment]
I stoped after the 446 call. My csv file contains 96 lines. 
 
<img width="1036" alt="" src="https://user-images.githubusercontent.com/1499842/76389464-2f052580-6363-11ea-80de-af36474b6a8b.png">

**Comment by JC5** [comment]
OK so the job exists and the system can hold on to it but the job is never started. I'll improve the flow so that when the job errors out for some reason, it is stopped correctly.

Is there something in the beginning of your job that hints to an error. A stack trace perhaps?

**Comment by pressqu** [comment]
No, sadly not at all.

**Comment by pressqu** [comment]
yes, it does. I found a log with more errors. 
<img width="1440" alt="" src="https://user-images.githubusercontent.com/1499842/76412822-38ef4e80-638c-11ea-9d73-0ed7fa57053c.png">

**Comment by JC5** [comment]
Thanks. I'll try to debug.

**Comment by JC5** [comment]
OK, so the null pointer should be fixed in future releases but this also requires a new beta release for the CSV importer. Stay tuned.
