### ISSUE TITLE
CSV import failed and corrupted database

### ISSUE THREAD

**Issue by cosmincc** [firefly-iii/firefly-iii#3182]
**Bug description**
I am running Firefly III version 5.0.5, and my problem is: a CSV import failed and now visiting the asset account page for said import fails as well with:
An exception has been thrown during the rendering of a template ("Missing required parameters for [Route: accounts.show] [URI: accounts/show/{account}/{start_date?}/{end_date?}].").

I've re-run the import 2 times and as such there are 3 database entries which are causing the issue:
| id  |     created_at      |     updated_at      | transaction_journal_id | description |       amount       | identifier | transaction_currency_id |   foreign_amount   | foreign_currency_id 
|------|---------------------|---------------------|------------------------|-------------|--------------------|------------|-------------------------|--------------------|---------------------
| 4179 | 2020-03-08 22:43:56 | 2020-03-08 22:43:56 |                   2091 |             | -9998.000000000000 |          0 |                       7 |                    |                    
| 4178 | 2020-03-08 22:13:15 | 2020-03-08 22:13:15 |                   2090 |             | -9998.000000000000 |          0 |                       7 |                    |                    
| 4177 | 2020-03-08 20:23:40 | 2020-03-08 20:23:40 |                   2089 |             | -9998.000000000000 |          0 |                       7 |                    | 

This transaction was the first row in the CSV import so this or the next row could be the issue.

There are 2 parts to this issue:
- why did the corruption happen and how to prevent it?
- how to fix the database? would removing those transactions be enough?

**Steps to reproduce**
Import CSV file (https://pastebin.com/9ygj24Cp), visit account for imported file.

**Extra info**
Self hosted on Ubuntu with nginx web server and PostgreSQL db.
| Variable | Content |
| --- | --- |
| FF version | 5.0.5 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , stack |
| PHP version | 7.3.11-0ubuntu0.19.10.3 |
| Display errors | Off |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2020-03-31 00:00:00 |
| Session first | 2016-05-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | pgsql |
| Current driver | pgsql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Bonus points**

- [x] Nobody reported this bug before
- [x] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

CSV import stack trace: https://pastebin.com/WAdZYCB0
Asset account page render stack trace: https://pastebin.com/JBgxntcJ

Screenshot of import failure:
<img width="932" alt="firefly-iii import error" src="https://user-images.githubusercontent.com/22967286/76360327-0e19e180-631d-11ea-9a19-9787404f7e9a.png">

**Comment by JC5** [comment]
Thanks for the expansive bug report! I've added some extra validation for this particular problem in the next release, 5.1.1. That should stop it from happening. Somewhere Firefly III started using an empty string instead of a NULL value, and some databases don't like that.

As a result, Firefly III creates only one transaction instead of two. That imbalance corrupts the database.

**Comment by cosmincc** [comment]
I have experimented and managed to fix the issue by removing the partial transactions from the transaction_journals table (delete operation propagated). I tried again the import with only those 2 rows on the latest stable version (5.1.0) and it failed the same way. Trying to add the transaction manually failed the same way as well and I was able to replicate this on the demo site running 5.1.1:

```
SQLSTATE[HY000]: General error: 1366 Incorrect decimal value: '' for column 'foreign_amount' at row 1 (SQL: update `transactions` set `foreign_amount` = , `foreign_currency_id` = 3, `transactions`.`updated_at` = 2020-03-11 09:42:17 where `id` = 905)
```

<img width="946" alt="firefly demo add error" src="https://user-images.githubusercontent.com/22967286/76398517-4d781a80-637d-11ea-8cf1-b247843e6b85.png">

Ideally the whole transaction should be reverted if an error like this occurs, but instead an incomplete transaction (transfer) is created with an invalid link (https://demo.firefly-iii.org/transactions/show/0) and no destination account.

<img width="1170" alt="firefly partial transfer error" src="https://user-images.githubusercontent.com/22967286/76398572-67196200-637d-11ea-8888-a7465aeacb02.png">

To replicate the error create a transfer between 2 asset accounts with different currencies. The UI is also missing the foreign currency/amount input fields as can be seen in the screenshot above.

**Comment by JC5** [comment]
I see what you mean. I'll make sure the foreign currency selector returns. I've pulled my fixes into the demo site just now and apart from the missing foreign currency selector, it should no longer be possible to get this error.

Reverting the transaction should be happening and needs some further research. Thanks for pointing this out.

**Comment by JC5** [comment]
The foreign currency selector should behave as expected again (on the demo site). I've also made some other small improvements: https://demo.firefly-iii.org/transactions/create/withdrawal
