### ISSUE TITLE
Docker Environment: Support for swarm secrets

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#3183]
**Description**
When managing secrets with docker swarm, the secret text will be mounted as a file and not passed directly as a ENV var. It would be great if firefly supported reading secrets from a mounted file.

See also: https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images

Excerpt:
> Note: Docker secrets do not set environment variables directly. This was a conscious decision, because environment variables can unintentionally be leaked between containers (for instance, if you use --link).

**Comment by JC5** [comment]
Firefly III already supports this 😁 .

The [.env.example file](https://github.com/firefly-iii/firefly-iii/blob/master/.env.example) mentions which variables can be set using a secret. The [entrypoint.sh](https://github.com/firefly-iii/docker/blob/master/scripts/entrypoint.sh#L29) script lists them as well.

**Comment by skuzzle** [comment]
Oh cool thanks. Must have overlooked that because the info only occurred in the big plain text blocks. Sorry 4 that
