### ISSUE TITLE
German special characters not working

### ISSUE THREAD

**Issue by varioous** [firefly-iii/firefly-iii#3186]
**Bug description**
I am running Firefly III version 5.1.1 and use german language. The special characters "ü,ä,ö" are not working.

**Steps to reproduce**
Set language to german

**Bonus points**

- [ x] I have added a screenshot.

![image](https://user-images.githubusercontent.com/7273899/76681992-6fc99c80-65f8-11ea-9bad-535b74c3bc16.png)

**Comment by JC5** [comment]
Thanks for reporting. This is not caused by Firefly III. Check out the search and make sure you have the correct locale packages installed in UTF8.

**Comment by varioous** [comment]
Hi JC5,
can you please explain in more detail?
Thanks and kind regards

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2817
