### ISSUE TITLE
Custom Transaction Fields - Receipt Link

### ISSUE THREAD

**Issue by garrettdowd** [firefly-iii/firefly-iii#3187]
**Description**
My bank transaction exports include links to receipts that I upload through the bank's app. As far as I know, Firefly does not support custom fields/columns for transactions. I already use fields such as "Notes" for other information included in the bank exports. Therefore, there is no way to retain this receipt information in a way that is easily accessible.

**Solution**
Ideally, a user would be able to add their own custom fields for transactions. Another solution is to add a URL field as an "optional field" in the preferences. 

**What are alternatives?**
Appending the URL to the Notes field, which does not work well when other information is already populated there

**Bonus points**
User-defined fields for transactions. Banks are starting to include more metadata about transactions such as receipts, payment splits, transaction type, time of day, etc. Instead of trying to include all of these in the default application it makes sense to allow users to define additional categories so they can at least store/retain the information.

**Comment by JC5** [comment]
That's a good suggestion. I'll think about the best way to do this. I'm not a fan of user defined custom fields, that's a huge effort on my part for a barely used function. But an URL field could work just fine.

**Comment by JC5** [comment]
You can now try this on the [demo site](https://demo.firefly-iii.org) :+1:
