### ISSUE TITLE
CSV: CSV column --> multiple roles

### ISSUE THREAD

**Issue by chickenskitchen** [firefly-iii/firefly-iii#3189]
**Description**

My understanding is that: The new csv importer sets each csv column to only one role.

Example: csv column `description` can map to Firefly `description`, but then the same column can't be mapped to anything else.

This is an issue for me because:
* csv column `description` should be mapped to `description` role
* csv column `description` should also be mapped to `opposing account (name)` role

Similarly:
* Some entries in `category` should be mapped to `categories`
* Some entries in `category` should be mapped to `budgets`
and they should **not be mutually exclusive**.

**Solution**
Similar to what currently exists, but additional dropdown menus which allow a fixed max number of roles per csv column.

Or, add an `Add role` button for each csv column to allow variable number of roles per csv column.

**What are alternatives?**
There might be a workaround with the existing functionality by using rules (e.g. to copy destination account to the transaction description; or automatically adding categories/budget based on transaction destination account).

**Side question**
Are there any plans to add `tags` to transactions imported from `csv-importer`?

**Thanks and great work as always!**

**Comment by JC5** [comment]
Sorry, but this isn’t going to be a part of the CSV importer. If you want to use columns twice, you’ll have to copy them yourself first.

The other way around, when you select “notes” or “description” for multiple columns, the content will be appended. 

What do you mean with your final question?

**Comment by chickenskitchen** [comment]
> If you want to use columns twice, you’ll have to copy them yourself first.

That's fine. I can do it.

> What do you mean with your final question?

The old csv importer automatically added a tag to the imported transactions. I don't see this happening for the new csv importer but I could be missing something here.

**Comment by JC5** [comment]
Ah yes, no that doesn't happen. I'll write it down :+1:

**Comment by chickenskitchen** [comment]
Thank you!
