### ISSUE TITLE
Transaction Cost Field and Category

### ISSUE THREAD

**Issue by pwnstorm** [firefly-iii/firefly-iii#3191]
Great and handy tool. 
It would be great if a transaction cost field would be added in the transaction entry form. Also to have an inbuilt transaction category for just handling the same.

At the moment, I have to enter the Transaction cost as a different transaction

Regards

**Comment by JC5** [comment]
Hi, thanks for the compliments!

Transaction costs are also transactions. Most people who run into this issue, luckily don't run into it very often. What you can do is add the costs to a split, so your transaction has two splits: one for the transaction and the other one for the costs of the transaction. A category for the same can be created manually.
