### ISSUE TITLE
Link to bill doesn't seem to work with transfers

### ISSUE THREAD

**Issue by sebw** [firefly-iii/firefly-iii#3192]
Hi,

Thanks for the great app, I'm coming from MMEX and I'm very pleased with Firefly, it is much more visual.

I am running Firefly III version 5.1.1

I'm probably misusing the "bill" feature, which I find pretty neat.

So I have created a "Credit card" account for my VISA card.

When I purchase something I withdraw out of that account.

I wanted to make a "bill" for the reimbursement, as a reminder not to miss the payment. I reimburse the outstanding amount with a "transfer" from my bank account to the VISA account.

I created a rule that would link the transfer to the bill:

![image](https://user-images.githubusercontent.com/2285094/76758037-2197d300-6789-11ea-831d-7ec323cb3c4c.png)

With the rule above, the transfer is not linked to the bill BUT the description is changed, which tends to prove the rule triggered.

Other link to bills work just fine, because I assume those are withdrawals, not transfer.

Would that be a bug?

Apologies if that's been asked already! :) 

Thanks!

**Comment by JC5** [comment]
Glad to hear you like the tool!

I see what you want, but that's not possible unfortunately. Bills are to be linked to withdrawals exclusively. What I do myself is create a piggy bank to save up the money spent on the credit card, until it's time to pay the CC bill.

**Comment by sebw** [comment]
Thanks James. Out of curiosity, is it a technical issue that prevents from linking a transfer to a bill?
I like the original idea of piggy banks (saving up for a big expense) but I'll stick for now with my transfer and calendar reminders for paying my CC :-) I don't want to mess up my Firefly too much as I did when I started with MMEX :P 

Cheers,
Seb

**Comment by JC5** [comment]
No it’s a conceptual one. Bills are paid to somebody else so they can only be linked to withdrawals. Of course credit cards mess up this idea but in most cases the money has been paid already, in your administration it’s just being moved. You could however create a bill for any rent you may have to pay over the credit card bill.
