### ISSUE TITLE
Reconciliation is copied when cloning transactions

### ISSUE THREAD

**Issue by gtrubach** [firefly-iii/firefly-iii#3193]
**Bug description**
I am running Firefly III version 5.1.1, and my problem is:

Cloning transactions is a very nice feature to have. But I found that if clone reconciled transaction, new transaction will be also reconciled. I don’t think it should behave in such way.

Additionally for cloned transactions time is set to the actual time of cloning, but for new transactions time is always 00:00. 

**Steps to reproduce**
Clone any existing reconciled transaction.

**Extra info**
Ms Edge Chromium

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [ ] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Ah good idea, I’ll pick that up. And yes, the time is set when you clone a transaction.

**Comment by gtrubach** [comment]
Just a small note about time: when you open edit screen for cloned transaction and press update transaction (without editing anything) time will be set to 00:00.
