### ISSUE TITLE
Refund on credit card creates a new account for the payee

### ISSUE THREAD

**Issue by sebw** [firefly-iii/firefly-iii#3194]
Hi,

I am running Firefly III version 5.1.1

I have another (probably noob) question, again related to credit card accounts. My brain is probably still a bit in MMEX mindset :-) 

Let's say I purchase something on Amazon for 100 euros. I create a withdrawal transaction of 100 euros on my credit card account.

Let's say Amazon refund me part of the article, say 10 euros. I create a deposition transaction on my CC account.

This creates two Amazon accounts (expense with 100 euros balance and revenue with 10 euros balance).

In MMEX, there's no concept of expense or revenue account, but payees. 

With the two transactions above, the balance for the Amazon payee is 90 euros in MMEX.

Am I doing something wrong? 

Thanks!

**Comment by JC5** [comment]
As you say, this works slightly differently in Firefly III :)

https://docs.firefly-iii.org/concepts/accounts

**Comment by sebw** [comment]
"if you shop at the place you work at, you will have a revenue account called "Albert Heijn" from which your salary is drawn but also an expense account called "Albert Heijn" where you pay your groceries."

This makes sense if you work at Albert Heijn to have a revenue account as Albert Heijn, but if you get a refund on a purchase, this doesn't really make sense to count that as revenue, it should be considered as "cancellation of a withdraw" (for the sake of proper balancing).

I tried to make a "negative withdraw" but obviously, this is not accepted. Any chance to see get "refunds" implemented?

**Comment by JC5** [comment]
No. Either edit the original withdrawal, or accept the deposit.

**Comment by sebw** [comment]
Alright, thanks James :)
