### ISSUE TITLE
Increasing Attachment Size Limit

### ISSUE THREAD

**Issue by calgara12** [firefly-iii/firefly-iii#3199]
I am running Firefly III version 5.1.1

**Description**
Is it possible to increase the max size of attachments?  If so, how?

Thanks

**Comment by JC5** [comment]
That's possible yes, are you using the Docker image or something self-hosted?

**Comment by calgara12** [comment]
Thanks for your quick reply. I am running a docker image. Is there an environment variable i can set?

**Comment by JC5** [comment]
No. It's a combination of PHP and Apache config that can't be easily changed for the Docker image. It'll be a part of the next release.

**Comment by calgara12** [comment]
Thanks thats great. :)
