### ISSUE TITLE
Favorite accounts

### ISSUE THREAD

**Issue by ngalfas** [firefly-iii/firefly-iii#3200]
**Description**
While someone import a transaction on the form, it would be nice to have 1-2 accounts on top of the select list for asset, income or expense account lists.
If i have 10 asset accounts but i regularly shop with my CC, i would like to have CC first on the select list.
This is only helping in the accounts drop lists while importing data on the form.
Maybe it could help when selecting accounts for the reports. Favourites first.

**Solution**
The user should select favorite accounts on the accounts/asset, accounts/expense, accounts/revenue pages.
It would be a new icon similar to enable/disable.

**Comment by JC5** [comment]
I'll see what I can do, not a bad idea :).

**Comment by JC5** [comment]
You won't be able to set favorites but it'll be possible, in the next release, to sort accounts as you see fit. This allows you to put your favorite accounts on the top of each list. This sorting will work anywhere where accounts are used.
