### ISSUE TITLE
Bunq monetary account is unexpectedly of type "bunq\Model\Generated\Endpoint\MonetaryAccountJoint".

### ISSUE THREAD

**Issue by dannoow** [firefly-iii/firefly-iii#3201]
**Bug description**
I am running Firefly III version 5.1.1, and my problem is:
Bunq-importer (v1.0.0-beta.1) gives me an error: 

(1/1) ImportException
Bunq monetary account is unexpectedly of type "bunq\Model\Generated\Endpoint\MonetaryAccountJoint".

**Steps to reproduce**
When i click "start here" on the bunq-importer, and i've clicked continu on the configuration import page (cause it's the first time, so no config yet). I'm being redirected to /import/configure wich gives me an error: 

**Extra info**

This is a test enviroment, cause the bunq import is still in beta. so my main instance is still running 4.7.9.
And because of the beta i've made this ticket, cause i dont know wether this is a bug or a user error.

![image](https://user-images.githubusercontent.com/16100224/77236044-11ce2380-6bbb-11ea-803d-410129f04b88.png)

Debug information generated at 2020-03-21 21:22:56 Europe/Amsterdam for Firefly III version **5.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.1.1 |
| FF API version | 1.0.2 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.16-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2020-03-01 00:00:00 |
| Session end | 2020-03-31 23:59:59 |
| Session first | 2020-03-21 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Comment by JC5** [comment]
Thanks for letting me know. I have no joint account myself. I'll pick it up for the next release. :+1:

**Comment by JC5** [comment]
If you're using Docker, the `fireflyiii/bunq-importer:develop` tag should be updated when [this build](https://travis-ci.com/github/firefly-iii/bunq-importer-docker) has finished. I expect the issue to be gone, but please give me your feedback.

**Comment by dannoow** [comment]
Hi, thanks for the reply.
I have a selfhosted-server setup.

**Comment by JC5** [comment]
Alright. As you can see in the commit the change is not particularly complex. You can change the lines yourself if you’re a bit technical. Let me know, the fix is a bit of a gamble.

**Comment by dannoow** [comment]
Hi,

I was just updating my reply with that ;)

I've added the classes to the file, and i've got a working import!
