### ISSUE TITLE
Dashboard "Budgets and Spending" graph bar heights are incorrect

### ISSUE THREAD

**Issue by BluePerfectOne** [firefly-iii/firefly-iii#3202]
**Bug description**
I am running Firefly III version 5.1.0, and my problem is:

The graph bar height should be the total amount spent, not the total spent PLUS the budget overspending. Take this picture from demo site for example, if Groceries budget has been set to 100€, and spent sum is ~180€, the bar graph should likely not show ~280€. I believe this is a bug.
![image](https://user-images.githubusercontent.com/45281661/77302415-f74e9400-6cf9-11ea-93fa-c679a5305ddd.png)

Reference to https://github.com/firefly-iii/firefly-iii/issues/593 as the behaviour seems to have been faulty then and has been fixed perhaps already but is now again incorrect.

**Steps to reproduce**
Set budget, overspend and check the bargraph totals.

**Extra info**
Debug information generated at 2020-03-23 11:27:58 Europe/Helsinki for Firefly III version **5.1.0**.

| Variable | Content |
| --- | --- |
| FF version | 5.1.0 |
| FF API version | 1.0.1 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| PHP version | 7.3.15 |
| Display errors | Off |
| Session start | 2020-03-01 00:00:00 |
| Session end | 2020-03-31 23:59:59 |
| Session first | 2019-12-05 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/
- [x] I donated money (this is a joke :wink:)

**Comment by JC5** [comment]
Nice, I can’t believe I didn’t spot that before 😅

I pushed a fix which is live on the demo site. You can verify if you want 👍
