### ISSUE TITLE
shared accounts: is there any update?

### ISSUE THREAD

**Issue by inesreisx** [firefly-iii/firefly-iii#3205]
Hi James, awesome work and tool! 👍 Me and my partner just started using it today and found these two issues about [shared access](https://github.com/firefly-iii/firefly-iii/issues/1783) and [shared budgets](https://github.com/firefly-iii/firefly-iii/issues/1612); was just wondering if there was any update about it? Thanks in advance (:

**Comment by JC5** [comment]
Hi, thanks for the compliments!

There's no update I'm afraid. It won't be possible to share your administration over multiple users.
