### ISSUE TITLE
"Create rule based on transaction" pulls wrong transaction

### ISSUE THREAD

**Issue by MadWalnut** [firefly-iii/firefly-iii#3210]
**Bug description**
I am running Firefly III version 5.1.1, and my problem is:

When clicking on "create rule based on transaction" I get the expected window, but the fields are filled out with information from a completely different transaction. Say I import transaction A, B and C into a tag. When I want to create a rule based off transaction A, it fills in the blanks with the details from B. Clicking on B fills correctly. C then however randomly fills with another, completely unrelated transaction D. It seems pretty random. 
The ID in the URL is the same though as when clicking on "Edit". Edit works perfectly for all these entries. No idea why creating a new rule based on the same ID (at least according to URL) fetches the wrong transaction data.
I know thats not really much information to go bug hunting with, but maybe you can point me into the right direction what I could check next.

**Steps to reproduce**
Maybe this also works without importing or the use of tags, but thats how reproduced in 3 or 4 times. Because of the randomness I wasn't able to re-create it on the demo site or with manually created transactions.

1. Import a few transactions from CSV.
2. Click on the tag that was created by the importer.
3. Click on "create rule based on transaction" on all of the transactions, some of them will create incorrect rules.

**Screenshots**
I tried to capture the bug as good as possible without revealing too much information from my real transaction (didn't have any luck creating buggy fake-transactions). Just check out the amount as an example (of course the other fields are wrong as well, they are just blacked out). In the edit window the amount (and everything else) is correct. In the rule-creation-window it is not, although they are both called with the same ID in the URL.

![Screenshot_2](https://user-images.githubusercontent.com/33835479/77637405-94c2f580-6f90-11ea-9ebb-ecc5325bdedf.png)
![Screenshot_3](https://user-images.githubusercontent.com/33835479/77637402-942a5f00-6f90-11ea-8dc8-e1e8221f9c0d.png)
![Screenshot_4](https://user-images.githubusercontent.com/33835479/77637398-92f93200-6f90-11ea-868f-c42d914ae9f3.png)

**My guess**
Maybe this is a off-by-one error? I've seen this behavior on a few transactions now, and so far every simple time the wrong data pulled has been from the preceding transaction.
Data shown ID = Actual ID minus 1
So when I click create rule from ID 216, it gives me the data from ID 215. When I create a rule from 218, it gives me data from 217. 
I'm just not sure when Firefly runs into that off-by-one and when not. Sometimes it gets it correct, sometimes it gets ID minus 1.

**Extra info**
Debug information generated at 2020-03-26 11:11:07 Europe/Amsterdam for Firefly III version **5.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.1.1 |
| FF API version | 1.0.2 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.14-1\~deb10u1 |
| Display errors | Off |
| Session start | 2020-03-01 00:00:00 |
| Session end | 2020-03-31 23:59:59 |
| Session first | 2020-02-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | cgi-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36 OPR/67.0.3575.79 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, ldap, exif, memcache, mysqli, pdo_mysql, pdo_sqlite, apc, posix, pspell, readline, recode, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, Zend OPcache |

**Comment by MadWalnut** [comment]
Found another interesting thing that supports my guess:
![Screenshot_7](https://user-images.githubusercontent.com/33835479/77638987-fb491300-6f92-11ea-8bb9-19a95a8e64fe.png)
Creating the rule from the detailed transaction information works! It calls a different ID though (compare URL bar at top with link destination at the bottom). Also off-by-one (not sure if intended). 

As soon as I go back to the list and try to create the rule via the dropdown, it calls 216 and therefore the wrong rule creation.

Maybe this helps.

**Comment by JC5** [comment]
It helps, absolutely. Thanks for the expansive bug report. For now, use the button from the detailed view. That will make sure the rule gets filled in correctly. For a fix, you'll have to wait for 5.2.0.

The root cause is caused by the fact that Firefly III uses different ID's for different parts of the transaction, and the button in the lists is referring to the wrong ID.

If you're a bit technical, you can apply the fix yourself so you don't have to wait for the new release. Check out my commit below this reply.

**Comment by MadWalnut** [comment]
Thank you for that super fast fix! I'll just wait for 5.2.0, not a big deal at all :)
