### ISSUE TITLE
Cant edit existing transactions

### ISSUE THREAD

**Issue by Tuffert** [firefly-iii/firefly-iii#3211]
**Bug description**
I am running Firefly III version 5.2.0-alpha.1 and my problem is:
If I want to edit an transaction, I got the error:
The POST method is not supported for this route. Supported methods: GET, HEAD.

**Steps to reproduce**
1. Open any transaction
2. Click "Edit"
3. Click "Update transaction"

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files.
- [ ] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
I see what you mean, me too. I'll check it out.

**Comment by JC5** [comment]
Thanks for letting me know. Will be fixed in the next release!
