### ISSUE TITLE
Display totals on budgets page

### ISSUE THREAD

**Issue by FelikZ** [firefly-iii/firefly-iii#3213]
**Description**

I would like Firefly III to display totals on "Budgets" place.

**Solution**

On bottom of budget page (page example: http://localhost/budgets/2020-02-01/2020-02-29) add an extra row with totals for **spent** and **left** to spend.

**What are alternatives?**

Dashboard widget for budgets displays "Left to spend".
How much being spent within all budgets is not available yet.

**Additional context**

![image](https://user-images.githubusercontent.com/1080269/77756711-000fd480-7030-11ea-84f4-43e4d8416f55.png)

**Comment by JC5** [comment]
Good idea, it's on the list!

**Comment by JC5** [comment]
Will be part of the next release and is visible on [the demo site](https://demo.firefly-iii.org/budgets).
