### ISSUE TITLE
[2FA] Sharing acount, use multiple 2FA configurations

### ISSUE THREAD

**Issue by rubenverhoef** [firefly-iii/firefly-iii#3214]
**Description**
I'm sharing one account with all our information with my wife. We want to enable 2FA but i can only setup one phone. I would like to see the possibility to have multiple 2FA configurations for one profile.

**What are alternatives?**
Using multiple personal accounts and be able to share data between profiles.

**Comment by JC5** [comment]
You could copy down the secret that is shown when you set up 2FA. You can enter the secret in any 2FA application.

**Comment by rubenverhoef** [comment]
Works great! I just scanned the QR code on both phones and after that inserted the code to confirm in firefly-iii. Thanks
