### ISSUE TITLE
Enable SSO

### ISSUE THREAD

**Issue by bpatath** [firefly-iii/firefly-iii#3215]
**Bug description**
Although single sign-on (SSO) is supported by Adldap, it is not enabled in Firefly III.
In theory, adding the `WindowsAuthenticator` middleware is sufficient.

In practice, it didn't work out-of-the-box due to invalid config files. The three changes needed were:

- `ldap_auth.identifiers.windows.discovery` -> `ldap_auth.identifiers.windows.locate_users_by`
- `ldap_auth.identifiers.windows.key` -> `ldap_auth.identifiers.windows.server_key`
- `ldap.connections.default.schema` -> `ldap.connections.default.settings.schema`

Thus, it seems the config files are outdated. I have not checked but there may be other changes...
Is there any reason for this ?

If not, I can do a PR with updated config files (for ldap only) and the SSO middleware if that's ok with you ?

**Comment by JC5** [comment]
There's no specific reason, although I'm not a big fan of adding yet another layer of middleware. This feature is very, very rarely used (maybe 1 or 2 users out of thousands). Let me do some research into the latest version of the package and get back to you.

**Comment by bpatath** [comment]
I can totally understand that. Maybe we could introduce a new environment variable to toggle the addition of the middleware ? It would be disabled by default, but would allow enabling it easily for interested users.
