### ISSUE TITLE
Project's own hosted service

### ISSUE THREAD

**Issue by mightyiam** [firefly-iii/firefly-iii#3216]
**Description**

Hi and thank you for Firefly III.

Even though I am a web developer myself, I would not like to deploy Firefly III myself.

**Solution**

I would like a professional deployment available to me, and after a free trial period I am likely to pay a good amount for a subscription.

**What are alternatives?**

https://docs.firefly-iii.org/installation/docker
https://docs.firefly-iii.org/installation/k8n
https://docs.firefly-iii.org/installation/self_hosted
https://docs.firefly-iii.org/installation/third_parties

**Comment by JC5** [comment]
Hi, you're very welcome :grin:

This is pretty counter-intuitive to why I built Firefly III, but thanks to the beauty of free open source software, anybody can do this. The license of Firefly III permits anybody to make money using, hosting or selling services based on Firefly III, provided that they make the changes required to host Firefly III open source as well. And I know those are necessary. 😬 

For now, I'm not going to do this myself. I don't even trust myself to secure my own financial records, let alone those of other people 😅 .

**Comment by bialad** [comment]
I have a web business, and could actually set this up if there's an interest from the community.

**Comment by mightyiam** [comment]
I have yet to find any other multiple currency envelope system budgeting app.
