### ISSUE TITLE
Whoops 5.1.1 import error

### ISSUE THREAD

**Issue by justin2108** [firefly-iii/firefly-iii#3219]
**Bug description**
I am running Firefly III version 5.1.1, and my problem is:

crash during import

**Steps to reproduce**
have a csv with a header. import transactions

**Bonus points**
[stacktrace.txt](https://github.com/firefly-iii/firefly-iii/files/4402443/stacktrace.txt)

**Comment by JC5** [comment]
Thanks for the excellent description. I'll verify that the fix necessary for this will be part of the [CSV importer](https://github.com/firefly-iii/csv-importer).

**Comment by JC5** [comment]
New beta release is live, closed.
