### ISSUE TITLE
Firefly III on k3s under nginx ingress in a subpath

### ISSUE THREAD

**Issue by JesusMtnez** [firefly-iii/firefly-iii#3221]
I am running Firefly III version 5.1.1

**Description**
I am trying to expose firefly iii through a nginx ingress in k3s under `/firefly` subpath, but I have tried many possibilities, but every time I access `<domain.com>/firefly`, it redirects to `<domain.com>/login`, which is not `<domain.com>/firefly/login`. 

I have also set:
```
APP_URL=<domain.com>/firefly
TRUSTED_PROXIES=**
```

But no luck. I saw other issues related, but could not find any solution. https://github.com/firefly-iii/firefly-iii/issues/2279#issuecomment-494639088

Any idea how could I debug more? The redirection url in the login page is to `<domain.com>` instead of `<domain.com>/firefly`.

**Extra info**

Right now I got it working avoiding the sub-path, but it is just a workaround.

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files (see https://bit.ly/FF3-get-logs)
- [ ] I was able to replicate the issue on the demo site.

**Comment by JesusMtnez** [comment]
Any idea / progress on how to use subdomains with firefly?

**Comment by JC5** [comment]
Under a sub-path, no, sorry about that.
