### ISSUE TITLE
Reccuring Transaction with fixed date but variable amount of money

### ISSUE THREAD

**Issue by schneekluth** [firefly-iii/firefly-iii#3222]
**Description**
The title might sound a bit confusing but here's the requested feature in short:
I have a giro account which is linked to a corresponding credit card. The credit card is being charged for a whole month and every 1st of a new month the debt on the credit card is charged on the giro card. In short it is a recurring transaction every new month but the amount of money is variable.

Whenever I pay with the credit card I make a new transaction in firefly so the amount of money is always negative for a whole month. Every 1st of the month I do a manual transaction from my giro to the credit card account so that the sum equals 0.

**Solution**
Provide the ability to automatically zero the negative sum from the credit card in the recurring transactions.

**Comment by JC5** [comment]
Thanks for the suggestion! I understand what you want to do, but that's way too complicated to arrange from a recurring transaction. If you want, with the API you could write a pretty basic script to do this every month on the 1st. But it's not something I can make part of Firefly III.

**Comment by schneekluth** [comment]
Thank you for your reply. Will try the script approach. Keep up the good work!
