### ISSUE TITLE
Certificate for firefly-iii.org ran out on March 30th 2020

### ISSUE THREAD

**Issue by bnw** [firefly-iii/firefly-iii#3223]

**Comment by JC5** [comment]
Whoops. Thanks. That's pretty embarrassing.

**Comment by JC5** [comment]
Should be back up, can you verify?

**Comment by bnw** [comment]
Works for me :)
Awesome response time, thank you :D

**Comment by JC5** [comment]
I was working on the new beta so right here when you posted 😁
