### ISSUE TITLE
Budgets chart: bar isn't displayed if nothing is spent yet

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3224]
**Bug description**
I am running Firefly III version 5.2.0-alpha.1, and my problem is:

At the beginning of a period my budgets chart is empty even though I set budget information. It seems that the bar isn't displayed if no transaction is linked to the budget yet. 
I expected to see "Spent in budget: 0, Left to spend: <budget amount>". 

**Steps to reproduce**
You can see on https://demo.firefly-iii.org/ that only 2 of the 4 budgets are displayed.
![image](https://user-images.githubusercontent.com/34862846/78164351-eb757700-7449-11ea-9cde-77f96c9060ba.png)
![image](https://user-images.githubusercontent.com/34862846/78164369-f29c8500-7449-11ea-977a-0c5f3fec46d0.png)

**Comment by JC5** [comment]
Indeed, it only starts showing information if there's something to see.

**Comment by sephrat** [comment]
Isn't "I still haven't spent a single dollar for this budget this month" something worth to see? 
I actually just noticed I didn't spend anything on my "going out" budget last month (guess why...). That is a valuable info but it was hidden behind budgets settings, which is a page I only go to on the first day of the month.

To be honest I thought it was a recent regression but I'm probably wrong. Consider this a feature request then. :-)
