### ISSUE TITLE
DB_HOST in .env.example not updated with latest docker compose

### ISSUE THREAD

**Issue by haltode** [firefly-iii/firefly-iii#3226]
**Bug description**
I am running Firefly III version 5.1.1.

This [commit](https://github.com/firefly-iii/docker/commit/1b6e75f39a4da4ff28c8c1538438bac01741e4db) from the docker repository removed underscores from services name, however the `.env.example` in the firefly-iii repository was not updated (`DB_HOST` variable). Since both the `.env.example` and `docker-compose.yml` files are used in the official documentation (docker compose setup) it would be important to keep them up to date.

A simple fix is to change the `DB_HOST` default value to `fireflyiiidb`.

**Steps to reproduce**

Currently, the docker compose default setup fails to connect with errors such as:

```
could not translate host name "firefly_iii_db" to address: No address associated with hostname
```

---

Thank you for all this great work!

**Comment by JC5** [comment]
Good find, thanks! I've updated the Docker example .env file. The Firefly III .env.example file will follow with the next release. I was already working on it, so it shouldn't be long.

**Comment by JC5** [comment]
New beta release was planned and is now live. This also fixes the docker compose file in the main repository.
