### ISSUE TITLE
Add SSL config for MySQL and LDAP

### ISSUE THREAD

**Issue by bpatath** [firefly-iii/firefly-iii#3227]
**Description**
I need to use SSL/TLS to connect to the Mysql database. This is supported by Laravel using the `options` key in the database definition and standard PDO options:

```php
'mysql' => [
    ...,
    'sslmode' => 'prefer',
    'options'   => array(
        PDO::MYSQL_ATTR_SSL_CAPATH => '/.../certs/',
        PDO::MYSQL_ATTR_SSL_CA     => '/.../ca-cert.pem',
        PDO::MYSQL_ATTR_SSL_CERT   => '/.../cert.pem',
        PDO::MYSQL_ATTR_SSL_KEY    => '/.../key.pem',
        PDO::MYSQL_ATTR_SSL_CIPHER => 'TLSv1.2 TLSv1.3',
        PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => true,
    ),
];
```

The full list is documented [here](https://www.php.net/manual/fr/ref.pdo-mysql.php#pdo-mysql.constants), but these are the most commonly available on SSL/TLS compatible softwares.

Likewise, Adldap supports additional SSL/TLS options through the 'custom_options' key in the settings configuration:

```php
'settings' => [
    ...,
    'use_tls' = true,
    'custom_options' => array(
        LDAP_OPT_X_TLS_CACERTDIR    => '/.../certs/',
        LDAP_OPT_X_TLS_CACERTFILE   => '/.../ca-cert.pem',
        LDAP_OPT_X_TLS_CERTFILE     => '/.../cert.pem',
        LDAP_OPT_X_TLS_KEYFILE      => '/.../key.pem',
        LDAP_OPT_X_TLS_CIPHER_SUITE => 'TLSv1.2 TLSv1.3',
        LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_HARD,
    ),
];
```

The full list of options is available [here](https://www.php.net/ldap_set_option)

**Solution**
Add environment variables for each of these options, and generate corresponding arrays in `config/database.php` and `config/ldap.php`. I'm willing to do a PR.

**Comment by JC5** [comment]
Thanks, I'll pick it up.
