### ISSUE TITLE
Updating transactions causes MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by ilvez** [firefly-iii/firefly-iii#3228]
**Bug description**
I am running Firefly III version 5.2.0-alpha.1, and my problem is:

Probably you already have discovered this by yourself, but better safe than sorry: updating existing transaction causes MethodNotAllowedHttpException.

**Steps to reproduce**
1. Start editing any transaction
2. Click "Update Transaction"
3. Error appears & transaction is not changed.

**Extra info**
| Variable | Content |
| --- | --- |
| FF version | 5.2.0-alpha.1 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, daily |
| PHP version | 7.4.3 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 23:59:59 |
| Session first | 2019-01-21 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | pgsql |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

Traceroute (since no log was created, a screenshot)
![image](https://user-images.githubusercontent.com/1476689/78201561-957cef80-749a-11ea-8059-76a68ffe3d9f.png)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3211

**Comment by ilvez** [comment]
:man_facepalming: took a look at existing, but early morning pattern matching was faulty. Good to hear it's taken care of.
