### ISSUE TITLE
Automatic create new asset account when import

### ISSUE THREAD

**Issue by bramboe** [firefly-iii/firefly-iii#3229]
**Description**

- When creating a new FireFly account, it would be great if the user could start importing its accounts as one of its first actions during the setup. (Using any form of available import solution: CSV, bunq, etc)
This way asset accounts will be created automatically, preferably after verification. 

I think this could be useful because, with online banks, users will have more than one account.

What do you think?

**Comment by JC5** [comment]
Nah. Firefly III comes first. The product doesn't exist by the grace of an import tool, it's a mature product in its own right. As such, I want Firefly III to present itself as the "source" for your finances.

I understand the ease of use that would present itself when the import does everything for you, but I want people to realise what they're doing. If Firefly III creates and imports all of your bank details the app is just a carbon copy of your bank records with fancier charts. And that's not why I made the tool.

Of course it's up to anybody to create an import tool that does this. After all, that's open source for you. But part of the mission I chose for myself when I started opening up Firefly III is that it's an *opinionated* tool. In many ways Firefly III isn't flexible. And I like it that way.

I hope that when users are forced to do something themselves, they're more involved in the tool and the usage. It's the same reason why I haven't build a ready-made 5-minute Wordpress install process. As they say in Dutch, "zonder wrijving geen glans". :wink:
