### ISSUE TITLE
Balance Incorrect When Starting Month with Positive Asset Balance

### ISSUE THREAD

**Issue by fictitiousexistence** [firefly-iii/firefly-iii#3231]
**Bug description**
I am running Firefly III version 5.1.1, and my problem is:

The balance total appears incorrect when starting month with positive asset account balances. 

**Steps to reproduce**

If you start a new month with a balance in an asset account like below:
![image](https://user-images.githubusercontent.com/20089581/78417033-0e478d00-75fc-11ea-9b6d-ff2b445c6f64.png)

The balance appears to not be calculated properly. In the picture above I am in the current month of April with no new transactions at all. In March I have one Revenue transaction of 126 hence the current balance in April of 126. 

If I start April with $126 in my bank account, I would consider my balance to be $126. However the balance shows as 0. 
![image](https://user-images.githubusercontent.com/20089581/78417062-5d8dbd80-75fc-11ea-925f-13242bdbe9e2.png)

The balance looks to be calculated by subtracting the beginning of the months total from the ends total. However, since they are both the same, the balance is 0. I was thinking the balance would be the total amount at the start of the month minus all withdrawal transactions. 

If I create a new transaction for 26.00, I would think the balance would be $100. However, the balance is -$26 due to the beginning balance of 126 being subtracted by the end amount. 100 -126 =-26

![image](https://user-images.githubusercontent.com/20089581/78417150-5d41f200-75fd-11ea-8efe-71ef27a20245.png)

The balance seems to work correctly if there is no balance already in an asset account.

Am I not utilizing the balance total properly? 

Screenshots are an example using the demo site.
**Extra info**

**Bonus points**

- [ x] I have added a screenshot.
- [ x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Hi, thanks for an excellent question. 

The balance is the income of this month vs the expense of this month. So no matter what your start balance is, on day 1 the balance is zero because nothing came in and nothing went out.

**Comment by GaryQ** [comment]
Suggestion: Maybe something more descriptive to actual box value might be a positive change like "Income / Expenses" … "Income Vs Expenses" or anything along the lines of "In vs Out" Balance seems a little vague.

Just my 2 cents Canadian so not worth much in the exchange rates lately.
P.S. Hope you all are safe and healthy wherever you are.
