### ISSUE TITLE
Export: Tags-field is empty for all transactions

### ISSUE THREAD

**Issue by phwitti** [firefly-iii/firefly-iii#3234]
I am running Firefly III version 5.1.0.

**Description**
Export by UI-Button (therefore no additional export-configurations).

**Extra info**
docker installation on Ubuntu 18.04.4 LTS

Debug information generated at 2020-04-04 20:08:16 UTC for Firefly III version **5.1.0**.

| Variable | Content |
| --- | --- |
| FF version | 5.1.0 |
| FF API version | 1.0.1 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| PHP version | 7.3.15 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 23:59:59 |
| Session first | 2020-03-11 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 OPR/67.0.3575.115 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files 
- [x] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Nice find! Will be fixed in the next release.

**Comment by phwitti** [comment]
Sweet :) -- thanks for your great work!
