### ISSUE TITLE
firefly importer Unique transactions option

### ISSUE THREAD

**Issue by MakiG0** [firefly-iii/firefly-iii#3235]
I am running Firefly III version 5.1.1. and firefly importer version v1.0.0-beta.2

**Description**
I check the option "Do not import already existing transactions". Nevertheless, duplicate transactions are created in firefly.
I have checked my settings several times and could not find any errors. I tried the import several times.
Maybe it's a bug and this request helps you to improve.

Great Job your tool anyway ;-)

**Extra info**
 

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [x] I added a screenshot
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

![2020-04-04_22h33_42](https://user-images.githubusercontent.com/49974203/78460986-de64bc00-76c5-11ea-8d2d-9a943a334ff6.png)

**Comment by JC5** [comment]
Thanks for reporting! I'll check it out.

It depends a bit on what kind of duplicates. Are they duplicates compared to a similar run in the same tool, or do you see duplicates compared to when you imported with Firefly III itself?

**Comment by MakiG0** [comment]
I have tested the following:

**Import with firefly importer**
1. import data with firefly importer (data not exists in firefly iii)
2. import exact the same data with firefly importer
---> Duplicate entries

**Import with firefly iii itself and firefly importer**
1. Import data with firefly iii itself
2. Import exact the same data with firefly importer (and the set the option "do not import already existing transactions")
---> Duplicate entries

Hope it helps you...

**Comment by JC5** [comment]
Importing between Firefly III itself and the CSV importer could generate duplicates I'm afraid.

Doing this twice using the CSV importer gives me nothing. Please show me some log files with two imports in a row.

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://docs.firefly-iii.org/contact/contact).

**Comment by tscs37** [comment]
Hi,

I've experienced this problem multiple times using both FinTS import and Spectre, the last 90 days of transactions are imported twice whenever I run an import, which of course requires quite a bit of cleanup. However, sporadically, F3 will detect the duplicates and not import everything twice.

The data of the transactions does not differ except in the import key (some older transactions imported from FinTS use a different format in their notes than newer ones from Spectre, but Spectre TX are also affected) and of course the reconciliation tag on transactions.

**Comment by JC5** [comment]
Thanks for letting me know. I already got some log files. For both of you, try comparing two duplicate transactions, like so:

1. https://demo.firefly-iii.org/transactions/show/388
2. https://demo.firefly-iii.org/transactions/show/108

Change the word "show" to "debug":

1. https://demo.firefly-iii.org/transactions/debug/388
2. https://demo.firefly-iii.org/transactions/debug/108

Let me know the differences. Of course you do this in your own installation.

**Comment by MakiG0** [comment]
i have compared two imports and found 2 difference, lets call one file A and the other B.
**File A** has a section called "meta" with following values: 
id, created_at, updated_at, transaction_journal_id, name, data, hash, deleted_at. File B has this section but with NO values.
**File B** has a section called "tags" with following values:  
id, created_at, updated_at, deleted_at, user_id, tag, tagMode, date, description, "pivot": {"transaction_journal_id","tag_id"}. File A has this section but with NO values.
I have not included these values for the sake of clarity. If you need her, just let me know. Hope this is what you want ;-)

**Comment by JC5** [comment]
I think it would be helpful if you would email me the originals. :)

**Comment by MakiG0** [comment]
send you an email ;-)

**Comment by JC5** [comment]
Haven't seen it yet I'm afraid.

**Comment by JC5** [comment]
Sorry, I got them. App didn't refresh.

**Comment by JC5** [comment]
Thanks for sending me the files. I'm afraid it's not something I can help. There are tiny differences between the old and new CSV importer I was unable to iron out. So this problem can't be fixed: imports you may have done using the *old* importer may be imported again with the *new* importer.

All I can do is warn other users of the same effect. Sorry about this.

**Comment by tscs37** [comment]
I've managed to reproduce it on the Spectre importer again; last 3 months of transactions have been duplicated. External ID matches between the two transactions. I will send you an email with the two debug JSON files.

**Comment by JC5** [comment]
Thanks, I see it. I'll push a fix for the next release.

**Comment by MakiG0** [comment]
thanks for your help ;-)

**Comment by tscs37** [comment]
Maybe a small suggestion; it would help cleaning up mishaps if the importer had an option to specify a time range for Spectre (or other import types) so that potential damage can be limited and that would also help reduce the number of transactions that had to be actually processed.

Thank you very much for you help though :+1:

**Comment by JC5** [comment]
There is a new Spectre importer on its way that includes improvements like that :)
