### ISSUE TITLE
Select bill when creating an expense

### ISSUE THREAD

**Issue by stickperson** [firefly-iii/firefly-iii#3238]
**Description**
I'd like to be able to select which bill to link a transaction to when creating it, similar to how I can select a budget. I know you can create a rule, but I often forget how all my rules are configured (did I use "phone bill" or "Verizon" as the trigger?).

**Solution**
Have a "bill" dropdown list on the transaction page similar to "category."

**What are alternatives?**
Current state (rules)

**Additional context**
I know there's some logic that determines which month a bill is paid in. For example, if you expect a bill to be paid on the 30th of the month but it's paid on the 1st of the following month it's credited correctly. I'm unsure how that would work if explicitly selecting the bill.

**Bonus points**
I can try the implementation if you feel this is a good feature to ad :)

**Comment by JC5** [comment]
I'll think about it. I don't want to overburden the form. I see the issue though. Stay tuned.

**Comment by JC5** [comment]
Will be present in the next release.
