### ISSUE TITLE
Add a index in the title of recurring transactions

### ISSUE THREAD

**Issue by carmolim** [firefly-iii/firefly-iii#3240]
Hello, I have a suggestion to recurring transactions with a specified end.

The suggestion is to automatically append a index in the title of the transaction, counting the already created transactions an the total repetitions, something like (1/6) = first transaction of 6. 

Using this index will be easier to know how many future payments I’ll have to make just looking at the transactions list.

Thanks!

**Comment by JC5** [comment]
Yes, that's a good idea. Not in the title though, possibly in the meta data. That gives some flexibility. I've written it down.

**Comment by carmolim** [comment]
Awesome, in the meta data is a better idea. Thanks!

**Comment by JC5** [comment]
Will be part of the new release!

<img width="471" alt="Screenshot 2020-07-26 at 07 50 24" src="https://user-images.githubusercontent.com/5889984/88472672-fe361f00-cf04-11ea-874f-218a3a28dd24.png">

<img width="421" alt="Screenshot 2020-07-26 at 07 50 05" src="https://user-images.githubusercontent.com/5889984/88472673-ff674c00-cf04-11ea-9d77-f143471cdfff.png">
