### ISSUE TITLE
Spectre API: "Pending" transactions not imported

### ISSUE THREAD

**Issue by sgofferj** [firefly-iii/firefly-iii#3241]
I am running Firefly III version 5.1.1 Docker

**Description**
I am importing data through the Spectre API, among other from N26. I have noticed that it doesn't import the latest few transactions and I have been spending a few hours trying to debug and to figure out why (I am a newbie to financial IT stuff) until I finally noticed that the "missing" transactions have the status "pending" in the Spectre API. I don't really know what "pending" means here. According to the N26 App, the transactions are booked and I also have access to money that came in. Is there a possibility to tell FF3 to import "pending" transactions?

**Extra info**
```
Debug information generated at 2020-04-07 20:35:08 Europe/Helsinki for Firefly III version **5.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.1.1 |
| FF API version | 1.0.2 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.16 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 00:00:00 |
| Session first | 2020-02-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |
```

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
There isn't, no. Sorry about that.
