### ISSUE TITLE
Add tag to imported data

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#3243]
The CSV importer doesn't do this. Problem is that it makes the transactions unique again so it breaks the unique transactions detector. But it could also be done *after* successful storage.

**Comment by filoor** [comment]
I would also love to she this one back in the importer

**Comment by aelsenaar** [comment]
Relied on this feature a lot when the importer was part of Firefly III application. It would be great to have it back in the importer.

**Comment by JC5** [comment]
New version of the CSV importer will have this. Should be released today or tomorrow.

**Comment by aelsenaar** [comment]
Great, thanks!
