### ISSUE TITLE
csv import - Partial account match results in wrong account being imported

### ISSUE THREAD

**Issue by msti** [firefly-iii/firefly-iii#3244]
Hi,

I don't think this is a code bug really, it is more of an edge case logic issue, related with this PR  https://github.com/firefly-iii/csv-importer/pull/3

**Bug description**

I am running Firefly III csv-import dev version, and my problem is:

When importing transactions, it is possible that the destination account of an imported transaction may not match the destination account in the csv. This can happen when the imported account only partially matches one or more accounts in firefly. In such cases, the first occurence of the partially matched accounts is used instead of creating a new account.

**Steps to reproduce**

1. Create an destination account in firefly with name: `COFFEE AND CREAM`
1. Import a csv with a transaction having a destination account: `COFFEE`. Make sure there is not a `COFFEE` account already.
1. Check the firefly transaction imported. It will have the `COFFEE AND CREAM` destination account instead of the `COFFEE`.

**Extra info**
This can be very easily by letting responsible method return `null`. Let me know if you want me to send a PR.

Thanks,
M.

**Comment by JC5** [comment]
Yep, confirmed. Feel free to create a PR!

**Comment by JC5** [comment]
If you don't mind I'm going to push this myself. I want the 1.0.0 out + the new Firefly III this weekend.
