### ISSUE TITLE
Comma as decimal separator for Piggy Banks

### ISSUE THREAD

**Issue by Crotha** [firefly-iii/firefly-iii#3245]
**Bug description**
I am running Firefly III version 5.2.0-beta.1 and my problem is:
When adding/removing money from the piggy bank, I can't use the comma as a decimal separator (which is standard in my language format), but have to use the dot.
The problem previously was also in transactions, but solved with the 5.2.0 alpha (I think).
BUT: I don't get any error message, it just isn't counted.     
The page reloads without any changes done.     

**Steps to reproduce**
Using a comma as a separator in the piggy bank, save.

**Bonus points**
I didn't do anything except searching for the comma separator, but only found the transaction-issue.   So, no bonus points for me.

**Comment by JC5** [comment]
Which browser are you using, and which language is Firefly III set to? This works just fine in Firefox and Chrome.

**Comment by Crotha** [comment]
Huh, interesting.

Firefox v74.0.1 (64 bit)
And Firefly-III is in english, my Windows uses EN-AT, my keyboard is german.
(I use Firefly-III in english, because I really don't like the german translation. Well, the translation is okay, the german words are just...long and silly.)

**Comment by Crotha** [comment]
Sorry for the double-post: 
I just tested it on the demo-page, same problem there and made a very bad screenshot-collection:
![Untitled](https://user-images.githubusercontent.com/47434645/78809480-4a496c00-79c7-11ea-9861-2af409bc2b71.png)

**Comment by JC5** [comment]
I see.

Unfortunately, if you use Firefly III in English, your browser will follow the en_US locale which uses dots.

**Comment by Crotha** [comment]
It does work in the transactions perfectly, that's why I thought it might be a bug.

I can live with it, tbh, it is only on the piggy-bank subpage. I just found it strange, tbh, to it being a problem only there.

**Comment by JC5** [comment]
That’s a lucky break then. That form has a bug that stops it from working if you use commas. Guess it works the other way around as well.

**Comment by Crotha** [comment]
I'm sorry, do you mean it was a lucky break to catch that as there is a bug in the piggy bank form?
Or that the comma works in the transactions?

If the commas working in the transactions is a bug, I hope you'll never fix it ;)
