### ISSUE TITLE
DB record exist but no on GUI

### ISSUE THREAD

**Issue by ckc** [firefly-iii/firefly-iii#3247]
**Bug description**
I am running Firefly III version 5.1.1, and my problem is:
like title mentioned

**Steps to reproduce**

Normal to add currency, some changed from existing currency
**Extra info**

**Bonus points**

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

![image](https://user-images.githubusercontent.com/4257872/78859354-a660ce80-7a61-11ea-8510-6681aed9b049.png)
parse the problem param to URL
![image](https://user-images.githubusercontent.com/4257872/78859391-bd072580-7a61-11ea-999c-b1fde01a2128.png)
In the DB
![image](https://user-images.githubusercontent.com/4257872/78859420-da3bf400-7a61-11ea-8186-65f6aaf42b2a.png)
GUI

**Comment by JC5** [comment]
In the database the field “deleted_at” is filled in which means you deleted the currency. Set the value to NULL to make it reappear.

**Comment by ckc** [comment]
It's ok now
Thanks your quick reply :)
