### ISSUE TITLE
Spectre API: Problem with recognizing existing transactions

### ISSUE THREAD

**Issue by sgofferj** [firefly-iii/firefly-iii#3248]
I am running Firefly III version 5.1.1 Docker

**Description**
I'm running F3 for a couple of days now and set up the Spectre API. Today when running the import from N26 via Spectre, F3 did not recognize existing transactions and imported all transactions again. This already happened once 2 days ago. On the import yesterday, existing transactions were recognized. So far, the problem only occurred with N26. At this point, there are no debug logs. I will enable debug mode now, though, in case the problem pops up again.

**Extra info**
```
Debug information generated at 2020-04-09 08:04:55 Europe/Helsinki for Firefly III version **5.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.1.1 |
| FF API version | 1.0.2 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.16 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 00:00:00 |
| Session first | 2020-02-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |
```

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Thanks for letting me know. 

When you see a duplicate, don’t delete it yet. Open both transactions in separate tabs in your browser and change the word “show” to “debug” in the url. Send me the results. That will show me exactly where the differences are. 

Since it’s private info it’s best to do this over email.

**Comment by sgofferj** [comment]
I deleted the doubles already but as this occured already twice, I expect it to happen again. I will follow the instructions then.

**Comment by sgofferj** [comment]
Happened again. Saved all JSONs and emailed a download link to the email address mentioned in the Contact section of Readme.md.

**Comment by JC5** [comment]
Thanks. Feel free to remove them. I'll push a fix for the next release of Firefly III. It should solve the issue, but keep in mind that you may run into other duplicates before the fix "works".

**Comment by sgofferj** [comment]
Awesome!
