### ISSUE TITLE
Box with dynamic sum based on the selected items

### ISSUE THREAD

**Issue by carmolim** [firefly-iii/firefly-iii#3249]
**Description**
In the transactions page create a new box bellow the months' partial sums, with a dynamic sum based on the checked transactions.

Also apply the hover style to the checked lines.

**Bonus points**
<img width="384" alt="Screen Shot 2020-04-09 at 11 02 41" src="https://user-images.githubusercontent.com/2863161/78903723-f0da4f00-7a51-11ea-96d3-fa0f67784c1d.png">

**Comment by JC5** [comment]
Thanks for the suggestion. I like the idea but maybe in a future release. In the current view, it feels too messy.
