### ISSUE TITLE
Is the Dockerfile from jc5x/firefly-iii outdated in Docker Hub?

### ISSUE THREAD

**Issue by lguima** [firefly-iii/firefly-iii#3250]
I am running Firefly III version 5.1.0.

### **Description**
**Firefly III 5.1.0** requires the **PHP 7.3.0** or greater, right?

But the [**Dockerfile**](https://hub.docker.com/r/jc5x/firefly-iii/dockerfile) from [**jc5x/firefly-iii**](https://hub.docker.com/r/jc5x/firefly-iii) in Docker Hub is using the **PHP 7.2**.

Is it outaded? If yes, where can I find the latest one?

I also notice the link to the **official documentation** is broken in the [**Overview** tab](https://hub.docker.com/r/jc5x/firefly-iii) in Docker Hub.

**Comment by JC5** [comment]
That's a very old Dockerfile. I think it was placed there by Docker the last time I used them to build the image. These days Travis CI does the building and the Docker images can be found here: https://github.com/firefly-iii/docker

I'll update the readme over at Docker Hub, thanks for noticing!

**Comment by lguima** [comment]
Got it, thank you!
