### ISSUE TITLE
Budgets are reverse-sorted by name every other month

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#3251]
I am running Firefly III version 5.2.0 on docker.  

I was experimenting with the new auto-budget feature.  Nice add, by the way!

I noticed that when I go to May (next month), the budgets are sorted alphabetically (A-Z).  In June, the budget are reverse-alphabetically sorted (Z-A).

This behavior continues through the rest of the year, and I'm not utilizing column sorting.

![May Budget](https://user-images.githubusercontent.com/39804831/79007600-555be380-7b10-11ea-86f8-7443c510452d.png)

![June Budget](https://user-images.githubusercontent.com/39804831/79007597-542ab680-7b10-11ea-86c6-880af6d9e086.png)

**Comment by JC5** [comment]
Hah that’s an amazing bug. That’s one to print and frame 😁

It could be a cache issue but I’ll check the source. I guess one of the queries is sorting the other way around.

**Comment by JC5** [comment]
This is very weird. The collection sorts randomly when you loop over it. I'll dive into it.

**Comment by zeitwidrig** [comment]
A simple reload also reverses the order btw.

**Comment by hamfactorial** [comment]
Perhaps related, I noticed that #2976 is happening again when I enter transactions on mobile.

**Comment by JC5** [comment]
This was caused by an inconsistency in the budget ordering code. I fixed it. Your budgets may appear in a reverse order when loading them in the next update. Sorry about that.
