### ISSUE TITLE
csv-importer ignores X-Forwarded-Headers

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#3252]
**Description**

Im running firefly-ii behind a reverse proxy. Its quite hard to get the import done correctly without correct handling of X-Forwarded-Headers.
It also would be great if there would be a way to configure a "prefix". Then I could reuse my Fireflly-III Domain and just use a subdir/location for csv-imports.

**Solution**
Implement X-Forward-Proto, X-Forwarded-Host, X-Forwarded-Port 

**What are alternatives?**
Allow overwrite/config of similiar settings in an config-file.

Thanks a lot!

**Comment by JC5** [comment]
Thanks for the suggestion. I've added the `TRUSTED_PROXIES` environment variable to the develop code. This should make the app trust your reverse proxy. Just set it to ** like Firefly III. I'll build a new image later tonight. 

For the /subdirectories, this is out of my scope to be honest. If you can make your reverse proxy properly forward everything and the path, it should work just fine. But I'm no expert.

**Comment by JC5** [comment]
Build 26 is running. https://travis-ci.com/github/firefly-iii/csv-importer-docker/builds

**Comment by devfaz** [comment]
Also works a expected. Thanks a lot!
