### ISSUE TITLE
csv-importer is just displaying empty mapping entries

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#3253]
**Bug description**
I am running Firefly III version 5.2.0, with csv-imports from docker (:devel).

If I upload my csv and config (also tried from scratch without success) everything seems to work as expected until i get into the "mapping"-page.

There are not dropdowns or any other selection possibilities shown.

**Steps to reproduce**
Just start your :devel-container
Import the attached csv (remove the .txt, had to add it)
Try to map the "remoteName" => "Opposing Account Name"-Field
You will see the attached screen(shot)

**Extra info**
Tried with Firefox & Chromium in PrivateMode and disabled all Modules (NoScript,Adblock,...) nothing helped.

- [X] I have added a screenshot.
- [X] I was able to replicate it on the demo site https://demo.firefly-iii.org/
- [X] I donated money (this is a joke :wink:)-->

[Bildschirmfoto_2020-04-10_20-11-00](https://user-images.githubusercontent.com/4060372/79012790-6dab1d00-7b67-11ea-938f-d0049058d22c.png)
[import-giro.csv.txt](https://github.com/firefly-iii/firefly-iii/files/4462820/import-giro.csv.txt)

**Comment by JC5** [comment]
Confirmed. Let me look for the cause.

**Comment by JC5** [comment]
Fixed in develop, I'll let you know when the docker image rebuilds.

**Comment by JC5** [comment]
And thank you for reporting and donating! :+1:

**Comment by JC5** [comment]
Build 26 is running. https://travis-ci.com/github/firefly-iii/csv-importer-docker/builds

**Comment by devfaz** [comment]
Works! Thanks a lot!
