### ISSUE TITLE
CSV import fails with an error message on the amount using files from ING Bank

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#3254]
**Bug description**
I am running Firefly III version  5.2.1, and my problem is:

I'm trying to run an import with the new CSV importing from my bank in the Netherlands (ING bank). However the import never completes and i saw the following error message at the final transaction during the import run. 

The error message is as follows:
```
[2020-04-11 12:06:29] local.ERROR: bcmul() expects parameter 2 to be string, int given {"exception":"[object] (TypeError(code: 0): bc
mul() expects parameter 2 to be string, int given at /var/www/ff3-import.internal.com/app/Services/Import/Task/Amount.p
hp:57)
```

The snippet of the final transaction is as follows:
 
```
[2020-04-11 12:06:29] local.DEBUG: Almost final transaction {"group_title":null,"error_if_duplicate_hash":true,"transactions":[{"type
":"withdrawal","date":"0622-07-20","currency_id":null,"currency_code":null,"amount":"1.19","amount_modifier":-1,"description":"READACTED_ACCOUNT NLD Pasvolgnr: 900 20-06-2019 12:40 Transactie: L3A9V0 Term: VBY3YC","source_id":null,"source_name":null,"destina
tion_id":null,"destination_name":"READACTED_ACCOUNT","tags_comma":[],"tags_space":[],"amount_debit":null,"amount_credit":
null,"amount_negated":null,"source_iban":"READACTED_IBAN","destination_iban":"","original_source":"jc5-csv-import-v1.0.1"}]} 
```

I can provide the full stack trace and a example file if need be. 
Thank you for the good work :) 
**Steps to reproduce**
* Import a csv file from ING Bank  with the following config: [import_config](https://github.com/firefly-iii/firefly-iii/files/4464589/import_config_2020-04-11.json.txt)
* Check the logs on warnings 

**Extra info**

Debug information generated at 2020-04-11 14:16:46 Europe/Amsterdam for Firefly III version **5.2.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.1 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, daily |
| PHP version | 7.3.16 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 6 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, igbinary, imagick, smbclient, zip, mysql, redis, libsmbclient, Zend OPcache |

**Bonus points**

- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
I've pushed a fix, together with build 27: https://travis-ci.com/github/firefly-iii/csv-importer-docker

Let me know if that helps!

**Comment by leander091** [comment]
Wow that is a quick response ! Thank you. 

i am going to check it out, but i am not using docker right now. So i have to find a way to clone the develop branch with composer. 

I will keep you posted!

**Comment by JC5** [comment]
Sure thing! I knew I would miss things for the CSV importers big release so I'm being alert.

Let me push another fix because I noticed an error. You can pick it up yourself or wait for 1.0.2. The weather is very nice so I'm going outside in a minute 😁 .

I hope to push 1.0.2 tonight anyway so if you don't want to, there's no need to move to the develop branch.

**Comment by leander091** [comment]
I hope you had a great time in the sunny weather . :)

I have tested the fixes of the development version and i have not seen the error again. 
Thanks :)

I saw some other strange things with the import so i am going to open some separate issues.
