### ISSUE TITLE
LDAP + email

### ISSUE THREAD

**Issue by derritter88** [firefly-iii/firefly-iii#3255]
**Description**
Currently Firefly III uses the username via AD-LDAP as email.
Unfortunately mostly usernames != email addresses and therefore no email can be used.

**Solution**
Username for login and email should be treated separately. 

**What are alternatives?**
Have a look at Nextcloud which I am using for a couple of years.
You can setup AD LDAP for login with the regular username + a separate email.

**Comment by JC5** [comment]
What's your question exactly? Because as far as I know, all relevant fields and inputs, despite being called "email" still work perfectly well.

**Comment by derritter88** [comment]
I have just installed Firefly - to be honest I am not sure if Firefly would send out any email.
If Firefly would send out something like a reminder "Monthly payment for xxx will be soon." then it would be great to have this email.

If email is just for login and Firefly would not send out any email then my request makes no sense :-)

**Comment by JC5** [comment]
Firefly III can send out emails, but won't do so when using LDAP. :)

**Comment by derritter88** [comment]
Okay so it would be a nice feature if LDAP users can also get emails (if username & emails are separate values).

**Comment by JC5** [comment]
Maybe in a future release. The LDAP code needs an upgrade anyway.

**Comment by derritter88** [comment]
Great - I am looking forward to it! 👍

**Comment by derritter88** [comment]
could you change the label to feature request or something similar so that it won't be auto closed.

**Comment by JC5** [comment]
It’s already on my list.

**Comment by derritter88** [comment]
okay
