### ISSUE TITLE
CSV Importer uses http instead of https behind reverse-proxy

### ISSUE THREAD

**Issue by justyns** [firefly-iii/firefly-iii#3256]
**Bug description**
I am running Firefly III version 5.2.1 (and csv-importer 1.0.1), and my problem is:

When loading the csv-importer webapp at https://firefly-csv.k8s.mydomain.tld the main page sort of loads, but does not load any css/js due to a bunch of "Blocked loading mixed active content" errors:

```
Blocked loading mixed active content “http://firefly-csv.k8s.mydomain.tld/css/bootstrap.min.css”
firefly-csv.k8s.mydomain.tld
Blocked loading mixed active content “http://firefly-csv.k8s.mydomain.tld/js/jquery-3.4.1.min.js”
firefly-csv.k8s.mydomain.tld
Blocked loading mixed active content “http://firefly-csv.k8s.mydomain.tld/js/popper.min.js”
firefly-csv.k8s.mydomain.tld
Blocked loading mixed active content “http://firefly-csv.k8s.mydomain.tld/js/bootstrap.min.js”
firefly-csv.k8s.mydomain.tld
Blocked loading mixed active content “http://firefly-csv.k8s.mydomain.tld/css/bootstrap.min.css”
firefly-csv.k8s.mydomain.tld
Blocked loading mixed active content “http://firefly-csv.k8s.mydomain.tld/js/jquery-3.4.1.min.js”
firefly-csv.k8s.mydomain.tld
Loading failed for the <script> with source “http://firefly-csv.k8s.mydomain.tld/js/jquery-3.4.1.min.js”. firefly-csv.k8s.mydomain.tld:49:1
Blocked loading mixed active content “http://firefly-csv.k8s.mydomain.tld/js/popper.min.js”
firefly-csv.k8s.mydomain.tld
Loading failed for the <script> with source “http://firefly-csv.k8s.mydomain.tld/js/popper.min.js”. firefly-csv.k8s.mydomain.tld:50:1
Blocked loading mixed active content “http://firefly-csv.k8s.mydomain.tld/js/bootstrap.min.js”
firefly-csv.k8s.mydomain.tld
Loading failed for the <script> with source “http://firefly-csv.k8s.mydomain.tld/js/bootstrap.min.js”. firefly-csv.k8s.mydomain.tld:51:1
ReferenceError: $ is not defined
firefly-csv.k8s.mydomain.tld:56:9
```

**Steps to reproduce**

1. Deploy csv-importer in kubernetes
2. Create kubernetes ingress that uses TLS

**Extra info**

The source of the index page contains:

``` html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="http://firefly-csv.k8s.mydomain.tld">
```

I am assuming the problem is because that `base href` uses http instead of https.  I am not sure how to change that though.  I tried setting the env variable `APP_URL` but that did not affect it, and I did not see any other config options related to using TLS.

The csv-importer itself is using http, but it's behind a reverse proxy which exposes https to the end-user.   

Browser -> nginx-ingress (443/https) -> csv-importer pods (80/http)

Is there a way to tell it to use https in the url even though it's technically being accessed via http?

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Yes, use the same configuration you're using for Firefly III. Nginx should forward the correct info like so:

```
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $host;
```

In the CSV importer, set the TRUSTED_PROXIES environment variable to `**`. This is undocumented, I'll pick this up right now.

**Comment by justyns** [comment]
Thanks for the quick response @JC5! I added `TRUSTED_PROXIES="**"` and can confirm it fixed my problem.

**Comment by Ludo444** [comment]
Today I migrated Firefly to 5.2 and setup CSV Importer. Experiencing this issue also after I added `-e TRUSTED_PROXIES=**` to my docker run command.

**Comment by Ludo444** [comment]
Ok, nevermind, I pulled latest docker image and it seems to work now
