### ISSUE TITLE
CSV importer wrongly transforms the date in the created transactions. 

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#3257]
**Bug description**
I am running Firefly III version 5.2.1, and my problem is:

I tried to run an import with the latest version of the csv-import tool (develop branch). The import ran successfully but the resulted transactions had been created with an wrong date. 
As an example a transaction with a as date `20200101 `in the csv is stored as  `August 20, 102, @ 00:00:00 ` in Firefly-iii.
In the import configuration I had defined `dmY  ` according to the format in the csv.

**Steps to reproduce**
* Import a CSV file with as date format` dmY  `
* Check the resulted transactions in Firefly-iii

**Extra info**

Debug information generated at 2020-04-12 12:48:56 Europe/Amsterdam for Firefly III version **5.2.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.1 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, daily |
| PHP version | 7.3.16 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 23:59:59 |
| Session first | 0102-08-20 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 6 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, igbinary, imagick, smbclient, zip, mysql, redis, libsmbclient, Zend OPcache |

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Shouldn’t that be Ymd instead?

**Comment by leander091** [comment]
Hmm that could be the issue indeed. That could be an issue on my side.

I am going to run the import again with an corrected format.

**Comment by leander091** [comment]
That was indeed the issue. I have not looked enough to the date format.

**Comment by JC5** [comment]
Sure thing! Thanks for reporting your issues so diligently. I appreciate it a lot :)

**Comment by leander091** [comment]
Of course, I like this project and I hope that my bug reporting catches some of the issues before they arise by other people.
