### ISSUE TITLE
Issue with CSV-Importer after VM Server  crashed while importing 

### ISSUE THREAD

**Issue by jrmbdl** [firefly-iii/firefly-iii#3259]
**Bug description**
I am running Firefly III version 5.2.0-beta.1, and my problem is:
![image](https://user-images.githubusercontent.com/63568148/79084676-e508ba00-7ce9-11ea-912e-38e31f78d809.png)

have a PC Mastercard, downloaded csv of transactions
-uploaded csv with csv-importer v1.0.0-beta.3
-first import went wrong as it ignored the date and imported everything on the current date.
-renamed the asset account "PC Mastercard old" and attempted to re-import 
-created a new asset account, but this time the vm crashed while importing. (freenas related)

Now have the import tool stuck importing 13 transactions... I deleted all the job files out of csv-importer/storage/jobs... framework... etc... 

-ended up also deleting the backup "PC Mastercard old" thinking the engine might have issues with double transactions.
-checked mysql database
-compelted in-place update to filefly-iii via https://docs.firefly-iii.org/advanced-installation/upgrade virtual server method.
-in csv-importer the PC Mastercard OLD is still listed under accounts even though it is not in the gui of firefly-iii

-Also as a note i have changed my timeouts for nginx and php to 10 minutes
-This is a new install but all my rules, and other accounts are almost already done.. countless hours have been put in.
-Installed on Freenas 11.3 U2 using a VM with xubuntu 18.04 php 7.4/nginx/mysql

LOGS POSTED LINKED
https://www.dropbox.com/s/u06mb5qplq9c09g/ff3-fpm-fcgi-2020-04-12.log?dl=0
https://www.dropbox.com/s/tj8tqnqfy2esunx/ff3-audit-2020-04-12.log?dl=0
https://www.dropbox.com/s/ei2iaijfd6nx7bc/csv-import-2020-04-13.log?dl=0

**Steps to reproduce**
using csv-importer after a failed import attempt causing a issue processing imports

- [x] Nobody reported this bug before
- [x] I have added a stack trace from my log files 
- [X] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Try to browse to `/flush` to reset the importer. It should reset your session and go back to zero.

**Comment by jrmbdl** [comment]
same results

**Comment by jrmbdl** [comment]
https://www.dropbox.com/s/oldtoog6o8akthk/csv-import-2020-04-13%20NEW.log?dl=0

**Comment by JC5** [comment]
You found a bug in Firefly III, sorry about that. For now, disable your rules if you want to continue, or wait for 5.2.2. I hope to be able to release it end of the day.

**Comment by jrmbdl** [comment]
this happens regardless if rule is selected or not :(

**Comment by JC5** [comment]
Mmm. The error in your logs is specifically for a rule. I'm not sure what else it could be. Try visiting the importer in a private browser window, that should at least reset it.

**Comment by jrmbdl** [comment]
just updated to current releases new error during all imports now...
Line #412: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0")

**Comment by JC5** [comment]
OK. Are you sure that you have also assigned the amount role to a column? Seems a basic check but you never know.

If you did, show me some log files to see if there's a bug somewhere.

**Comment by jrmbdl** [comment]
i decided to delete everything because my last update to the newest versions of both the csv-importer and firefly-iii i couldn't get any of the imports to work.  So I cleared my database, deleted my two "sites" and used composer and reinstalled... all i have done is create the default accounts, created a PC Financial Mastercard downloaded a fresh csv file from pcfinancial, goto csv-importer and...
![image](https://user-images.githubusercontent.com/63568148/79184464-0be9ed80-7dc9-11ea-857c-bea165a72361.png)
![image](https://user-images.githubusercontent.com/63568148/79184486-202dea80-7dc9-11ea-9f6c-7354cfbceba6.png)
![image](https://user-images.githubusercontent.com/63568148/79184520-376cd800-7dc9-11ea-894c-0a763cf3b890.png)
![image](https://user-images.githubusercontent.com/63568148/79184557-553a3d00-7dc9-11ea-99d9-44f838453b94.png)
![image](https://user-images.githubusercontent.com/63568148/79184581-67b47680-7dc9-11ea-93ce-553e0344c11d.png)
![image](https://user-images.githubusercontent.com/63568148/79184603-7c910a00-7dc9-11ea-8608-9ab7aa449a27.png)
![image](https://user-images.githubusercontent.com/63568148/79184641-9df1f600-7dc9-11ea-8182-0103f44792ea.png)

Logs:
https://www.dropbox.com/sh/6dzfvj1vhx8vrgw/AAApKTtgShktNvjUuEJFnKora?dl=0

**Comment by JC5** [comment]
Thanks for the details. I’ll try to replicate the issue and get back to you!

**Comment by jrmbdl** [comment]
Debug information generated at 2020-04-13 21:08:19 America/Vancouver for Firefly III version **5.2.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.1 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, daily |
| PHP version | 7.4.4 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 23:59:59 |
| Session first | 2020-04-13 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Comment by jrmbdl** [comment]
Thank You

**Comment by jrmbdl** [comment]
OK just installed csv-importer 1.0.0 issue is not present something between 1.0.0. and 10.2

**Comment by JC5** [comment]
Thanks, these details are helpful. Stay tuned!

**Comment by JC5** [comment]
OK this will be fixed in upcoming release 1.0.3. I hope to release it in a few hours. Keep in mind that with this CSV file, all of your destination accounts will be empty, unfortunately. Try to assign destination accounts using rules.

I also suggest you change the date configuration to "m/d/Y" so the dates of your transactions will be parsed correctly.

Thanks again for the comprehensive debug report! :+1:
