### ISSUE TITLE
Tag deletion in French

### ISSUE THREAD

**Issue by Thieume** [firefly-iii/firefly-iii#3260]
**Bug description**
I am running Firefly III version 5.2.1 and my problem is:
Firefly is configured to use French.
After tag deletion the number of tags deleted is not displayed correctly 

**Steps to reproduce**
Delete one or more tags. See screenshot.

- [ ] I have added a screenshot.
![2020-04-13_11-07](https://user-images.githubusercontent.com/3884674/79108691-28f5d080-7d77-11ea-8d1b-f9dab9719f90.png)

**Comment by JC5** [comment]
Nice find. I've updated [the translation](https://crowdin.com/translate/firefly-iii/142/en-fr#10035) and it will be fixed in the next release :+1:
