### ISSUE TITLE
How to tell CSV Importer in inline mode to which account to import?

### ISSUE THREAD

**Issue by sgofferj** [firefly-iii/firefly-iii#3261]
I am running Firefly III version 5.2.1 Docker

**Description**
I have been tinkering with CSV importer in Docker and while the web interface works nicely, it's too many steps for my taste, so I tried the inline import option. Unfortunately, the CSV importer imported everything into the cash wallet instead of into the respective bank account. Have I missed an option how to choose the bank account or is there none?

My ultimate goal is to run a script which inotifywait:s for a new upload of a CSV file and runs the importer when a new file has been uploaded.

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Sorry, I see there is no page yet on how the import JSON file works. In any case, the entry you must edit is the default_account:

```
"default_account": 47,
```

Change it to the ID of an asset account to import into, and it will fall back on that account, *if and only if* the transaction itself has no other information. So keep an eye on the logging too (set `LOG_CHANNEL=stack` if it isn't already.

Let me know if this helps.

**Comment by sgofferj** [comment]
Yes, that worked perfectly! Thanks!
