### ISSUE TITLE
Tag report allows you to exclude tags from search results

### ISSUE THREAD

**Issue by hreysenbach** [firefly-iii/firefly-iii#3262]
**Description**

Is it possible to exclude tags from the tag report? For example: to filter all transactions which have the tag "foo" and from those exclude all of the transactions which also have a "bar" tag.

In my situation, we are using Firefly to split bills and so we are tagging each transaction with who paid for what but then sometimes we transfer the money immediately and so we are tagging those transactions with a "settled" tag and still marking who paid for it. So when it comes to final calculations we want all of the transactions with the payee but exclude the transactions with a "settled" tag.

**Comment by JC5** [comment]
I'm sorry no, the tag report is inclusive.

**Comment by hreysenbach** [comment]
Is it possible to add this? I'm not too sure how difficult it would be but I'd be more than happy to help

**Comment by JC5** [comment]
I'll think about it. I'm not a fan, to be honest. It's not the idea itself but it's a very narrow use case and I try to avoid features that have those.

**Comment by hreysenbach** [comment]
Fair enough :) I'm guessing that you don't work on them because your effort could be better spent on other features? If that is the case I can work on it and then submit a PR, would you then consider merging it in?

**Comment by JC5** [comment]
No that’s not it. I’m selective of the features I implement for the sake of the feature, not the time or the effort.

**Comment by hreysenbach** [comment]
Ah ok, well thank you for your time answering my questions and thank you for making a great program :) 
I'll come up with another way of doing it either through exporting the transactions or using the API
