### ISSUE TITLE
Initial Balance not showing on dashboard

### ISSUE THREAD

**Issue by twiclo** [firefly-iii/firefly-iii#3263]
**Bug description**
I am running Firefly III version 5.2.1, and my problem is:
Initial balances on accounts aren't showing in the dashboard

**Steps to reproduce**

Fresh install
Go through new user prompt
Add initial balance to savings and checking accounts
Look at dashboard and see no net worth
Add some money to your cash wallet
See that added as your only net worth

**Extra info**

![image](https://user-images.githubusercontent.com/25187100/79188579-a56eca80-7ddc-11ea-88e2-825e83ffe711.png)

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
It’s not supposed to. The balance in that box depicts your monthly spending and earning.

**Comment by twiclo** [comment]
Shouldn't viewing a time range of "everything" have my net worth show my actual net worth though?

**Comment by JC5** [comment]
No.

**Comment by JC5** [comment]
Wait sorry net worth. I’ll check it out.

**Comment by JC5** [comment]
OK this works fine for me, I haven't been able to reproduce this yet. Two questions, one instruction:

1. What dates are the initial balances?
2. Are the amounts positive or negative?
3. Browse to `/flush` on your installation to see if this fixes the issue.

**Comment by twiclo** [comment]
I don't recall it asking for dates when going through the /newuser set up. I set this up yesterday, the same day I submitted this issue

They're positive

/flush still shows a net worth of only $41, which is my cash wallet. It's the same as the first screenshot really

**Comment by twiclo** [comment]
I actually just noticed this. The cash wallet is in dollars while the other two accounts are in euros. I selected dollars as my default during set up and it's still selected as default in the settings

Attempting to disable euro gives the error that a transaction is still using it

**Comment by JC5** [comment]
I see it. You found a pretty insidious bug. I'll release Firefly III v5.2.2 tonight. It means you'll have to start over with Firefly III, unless there's already lots of data in your administration. If so, we can fix it.

If not, then it's easier to start over.

Thanks for reporting this. I thought this wasn't an issue but you discovered a bug in something I didn't test for. But it's fixed! :D

**Comment by twiclo** [comment]
No worries. I just set it up for the first time yesterday so this is the best time to start over. How do I get it to behave like fresh install again? Do I delete some table?

**Comment by JC5** [comment]
Remove everything from the following tables:

- accounts
- transactions
- transaction_journals
- transaction_groups

And you're good as new.

**Comment by twiclo** [comment]
Shouldn't my balance include my initial balances as well? I entered those within the time range I'm looking at. It currently is only showing my wallet balance (which wasn't an initial balance)

**Comment by JC5** [comment]
Nah that only skews everything.

**Comment by anthonyirwin82** [comment]
I just setup a new installation of firefly version 5.4.5 today and setup an asset account and the initial balance did not show up in the account balance. I had to set the initial balance to $0 and add a deposit transaction with a source account of Initial Balance to have the value show up in the balance on the dashboard.

**Comment by JC5** [comment]
That's a stupid move. The initial balance isn't supposed to show up in the balance box and you forcing it there with a deposit only skews your reports.

The initial balance is meant to be a starting point. Ground zero. If you have an opening balance of 1000 that doesn't mean that you made 1000 this month. It's the opening balance. It's just there. You made zero this month it just happens that you already had 1000.

This is not a bug. Opening balances are ignored in the balance box.
