### ISSUE TITLE
Allow reordering of accounts on the right of the dashboard

### ISSUE THREAD

**Issue by twiclo** [firefly-iii/firefly-iii#3267]
**Description**
Please add an option to the layout menu to adjust the order in which accounts on the right side bar of the home page are displayed

**What are alternatives?**
I would like to know the current logic for how this is organized. I think it's alphabetical

**Comment by JC5** [comment]
They're alphabetic, and this isn't going to change I'm afraid.

**Comment by twiclo** [comment]
Is it an issue of your time? I'd be happy to give it a whack

**Comment by JC5** [comment]
That's not it, thanks for the offer though.
