### ISSUE TITLE
CSV-Importer can't load asset files when using Nginx Alias

### ISSUE THREAD

**Issue by Erulezz** [firefly-iii/firefly-iii#3268]
**Bug description**
I am running Firefly III CSV importer v1.0.3, and my problem is:

The CSV-Importer is installed and reachable by domain . com/csv-importer and firefly itself just normally on / . The Nginx docroot for the domain has been changed to point to the public folder in the firefly-iii installation. The CSV-Importer tool is reachable by using a Nginx alias, to /csv-importer.

The CSV-Importer is accessible, but it fails to load the asset files because it points to the wrong location:

default.twig:

```<link rel="stylesheet" href="css/bootstrap.min.css">```
&
```
<script src="js/jquery-3.4.1.min.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
```

So when I access the tool on /csv-importer, it can't load the asset files because they point to:

```
domain . com/css/bootstrap.min.css
domain . com/js/jquery-3.4.1.min.js
```

They point to the Firefly (docroot) installation, and that of course results in a 404.

I fixed it by using the Laravel config asset_url option:

```
<script src="{{ config('app.asset_url') }}/js/jquery-3.4.1.min.js"></script>
<script src="{{ config('app.asset_url') }}/js/popper.min.js"></script>
<script src="{{ config('app.asset_url') }}/js/bootstrap.min.js"></script>
```

And by adding it to: resources/views/import/run/index.twig & adding the correct url to the .env file. Can this be added to set a fixed asset domain and fix these issues when using this configuration? 👍

**Comment by JC5** [comment]
Hardcoding the asset URL is not a sustainable solution and not something I'm going to add.

What's the value of <base href>?

**Comment by Erulezz** [comment]
base href has the correct url, domain . com/csv-importer.

This works even better: using the Laravel asset() helper to generate full and correct urls:

```
<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">

<script src="{{ asset('js/jquery-3.4.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
```

No configuration needed and works perfectly. 👍

**Comment by JC5** [comment]
But if the base href is correct loading the assets should be no problem.

**Comment by JC5** [comment]
Alright I've pushed some changes to the `develop` branch of the CSV importer (and updated the Docker image). Let me know if it works!

**Comment by Erulezz** [comment]
> But if the base href is correct loading the assets should be no problem.

Yes indeed but that's the weird thing; I triple checked everything, reinstalled to undo my changes and still it didn't work while the base href was correct (with /csv-importer) 😕 

But now with using the asset() helper (and using the full url to the asset) it always works 😄 I tried your changes and it works without issues. There is another file that needs to be updated:

`resources/views/import/run/index.twig`

Thanks for responding so quickly and for this great tool 👍

**Comment by JC5** [comment]
Nicely spotted I forgot that one indeed. I'll pick it up!

**Comment by JC5** [comment]
Also fixed, the docker image should update in a few minutes after this reply.

**Comment by tenitz** [comment]
@Erulezz Would you mind sharing your nginx config file for firefly? I tried to setup the CSV Importer to be reachable on a subfolder at my Nginx reverse proxy but I had no success so far.

**Comment by Erulezz** [comment]
> @Erulezz Would you mind sharing your nginx config file for firefly? I tried to setup the CSV Importer to be reachable on a subfolder at my Nginx reverse proxy but I had no success so far.

https://gist.github.com/Erulezz/477d35bf30024f2c6bd4708bf78ddda7

This is what I use on a DirectAdmin system, with the docroot pointing to the firefly /public folder
