### ISSUE TITLE
Product management / total cost of ownership

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#3269]
If Firefly III were to get new features, this would be it.

- The ability to add products to your administration: washing machines, cars, phones, etc.
- Ability to link expenses and income to this product, together with a(nother) type of category: initial costs, repairs, maintenance, insurance, life cycle costs, replacement, upgrade, etc.
- See https://en.wikipedia.org/wiki/Total_cost_of_ownership
- Ability to tell you how much you should save in order to replace it in 1/3/5 years / custom time.

I'm the proud owner of several failed hobbies and I wonder how much this nonsense has cost me over the years. Also curious to learn how much an appliance is actually setting me back. Etc.

Don't get your hopes up the list is long enough but this is on my mind. If you have feedback or comments, feel free to reply.

**Comment by AlexKalopsia** [comment]
Isn't this something you can easily do with tags?

**Comment by JC5** [comment]
Not a bad idea. Expand the report as well. Thanks :)

**Comment by JC5** [comment]
This isn't something I'm going to add to Firefly III itself. I'm experimenting with a little tool that can do this for you. It's based on tags, as you suggested @AlexKalopsia, and I'll throw it online one of these days.

Basically, my experiment collects tags that start with `product-SOMETHING` and collects expenses grouped by their tag, like `product-SOMETHING-initial-purchase` and `product-SOMETHING-food` and so on.

For each PRODUCT it finds it will collect the expenses and do some sums. For example, if you tag your car expenses like this:

* `product-car-initial-purchase`
* `product-car-gas`
* `product-car-payment`
* `product-car-repairs`
* `product-car-maintenance`

The tool will group "gas", "payment", "repairs" and "maintenance" expenses together and show you the costs per month and of course the total costs.

Since this is something anybody can throw together using the API, I'm putting it online as an example. I'll take no feature requests or improvement things, it's just whipped together for my own enjoyment but way too complicated to put in Firefly III right now. I will update this ticket once it's live.

<img width="1207" alt="products" src="https://user-images.githubusercontent.com/5889984/88453762-98408d80-ce59-11ea-9751-55cce341e42d.png">

Btw, "katten" means cats, so please forgive me the "practical" approach here; rest assured I love my cats very much 😸

**Comment by JC5** [comment]
https://github.com/JC5/product-manager
