### ISSUE TITLE
Average budget spending in reports is avarage per payment not per period

### ISSUE THREAD

**Issue by getvince** [firefly-iii/firefly-iii#3270]
When selecting a period longer than a month the report generated budget chart is listing the average per payment not per period. Seems to be a little mistake or is it intentional?

**Comment by JC5** [comment]
Good question. I'm not yet sure.

Could you be very specific which report type, which time period and which chart or table? There are a lot to choose from :)

**Comment by thevinced** [comment]
Sure! As far as I can see it seems to be a report with 3 or more month selected. Doesn't matter if I custom select a specific timeframe or if I select one of the multi month default reports (e.g. current year or all-time).

**Comment by JC5** [comment]
So the default financial report, right?

**Comment by thevinced** [comment]
Yes. Sorry didn't know that there are different report types. Neat!

**Comment by JC5** [comment]
But you're right, it's average per payment but it should be per period. Will be fixed :+1:

**Comment by JC5** [comment]
Will be fixed in the next release :+1:

**Comment by getvince** [comment]
Awesome that was fast. Thank you.
