### ISSUE TITLE
CSV Imported imports amount-credit and amount-debit both as amount-credit

### ISSUE THREAD

**Issue by Nixellion** [firefly-iii/firefly-iii#3271]
**Bug description**
I am running Firefly III version 5.2.2, and my problem is:

I'm trying to import CSV from my bank, and it uses amount-credit and amount-debit columns. But CSV importer imports everything as credit, and for some fields it says that "value can't be :more, original value 0.000000" (sorry did not save that line, I've been restarting this docker CSV importer a doznen times already while trying to tune values, I am not doing it again, it's just stupid system and approach that you can't go back, stop the process or just keep it running all the time).

Here's my importer config:

```
{
    "date": "d.m.y",
    "default_account": 1,
    "delimiter": "semicolon",
    "headers": true,
    "ignore_duplicate_lines": false,
    "ignore_duplicate_transactions": false,
    "rules": false,
    "skip_form": false,
    "specifics": [],
    "roles": [
        "_ignore",
        "account-number",
        "currency-code",
        "date_transaction",
        "internal_reference",
        "description",
        "amount_debit",
        "amount_credit",
        "_ignore"
    ],
    "do_mapping": {
        "2": true,
        "0": false,
        "1": false,
        "3": false,
        "4": false,
        "5": false,
        "6": false,
        "7": false,
        "8": false
    },
    "mapping": {
        "2": {
            "RUR": 18
        }
    },
    "version": 2
}
```

Example data:

```
name;11111111111111111111;RUR;16.04.20;REF;info;5000;0
name;11111111111111111111;RUR;16.04.20;REF;info;0;2339.7
```

**Steps to reproduce**
Import CSV with amount-debit and amount-credit as separate columns

**Extra info**
Overall I gotta say that the idea to use a separate docker image and separate tool working through API for import-export is kind of frustrating. A plug-in system for importers built-into the main system would be much better, IMO. Also just the fact that you need to spin the docker image up for each import and with no way to go back to fix some setting if you made a mistake along the way is just too punishing and time consuming.

**Comment by JC5** [comment]
Thanks for letting me know. The issue should be fixed in the latest develop build.

And yes, I'm aware of the changes and the disadvantages. For me, the advantages are bigger. The advantages to this approach are many. Docker users are no longer bound to the web interface (which tends to timeout). You can import remotely, hardening your Firefly III installation. Separate release tracks mean that issues will be fixed quicker and more easily (as you can see).

Plugins aren't going to happen I'm afraid, Wordpress got its reputation for a reason.

**Comment by Nixellion** [comment]
@JC5 Thank you for a quick fix. Is there a way I can remove all transactions without re-creating my user? Could not find it yet.

Ability to restart the import process or go back to make changes on previous page without the need to restart docker container would be great.

And how can I automate it? For example it would be great if I could just upload a new csv file to a folder, say weekly or even daily, and just run a single command to automatically process it and kill importer container?

As for plugins, I see, I guess this mostly comes from the fact it's written in PHP then? Or - I did not mean plugins like in Wordpress where end user can install them on a whim. I meant a plugin system for developers. I'm not sure if it's possible with PHP, but in Python projects, like HomeAssistant or numerous other projects I personally worked on, one can create a folder, and dynamically load libraries from it. So when contributor writes, for example, a new importer, it won't clash with the rest of your code, it will be a separate file in this folder that loads dynamically when program starts. This way it makes managing Pull Requests easy, as there is basically no need to merge anything.

**Comment by JC5** [comment]
Ah I see what you mean. If you go to `/flush` on the CSV container it resets everything.

**Comment by Nixellion** [comment]
@JC5 I pulled latest image ( `docker pull` right? ) and run it again, but it still treats everything as credit and throws this error:

```
Line #0: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #1: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #2: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #4: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #5: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #6: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #8: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #9: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #10: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #11: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #12: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #13: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #15: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #16: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #17: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #18: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #19: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #20: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #21: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #23: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #24: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #25: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #26: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #27: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #30: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #31: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #33: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #34: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #35: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #36: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000")
Line #37: transactions.0.amount: transactions.0.amount must be larger than ":more". (original value: "0.000000000000") 
```

**Comment by JC5** [comment]
Alright, share some example lines with me and send me your configuration.

**Comment by Nixellion** [comment]
@JC5 They are in my very first post. Here's the updated config:
```
{
    "date": "d.m.y",
    "default_account": 1,
    "delimiter": "semicolon",
    "headers": true,
    "ignore_duplicate_lines": false,
    "ignore_duplicate_transactions": false,
    "rules": false,
    "skip_form": false,
    "specifics": [],
    "roles": [
        "_ignore",
        "account-number",
        "currency-code",
        "date_transaction",
        "internal_reference",
        "description",
        "amount_debit",
        "amount_credit",
        "_ignore"
    ],
    "do_mapping": {
        "2": true,
        "0": false,
        "1": false,
        "3": false,
        "4": false,
        "5": false,
        "6": false,
        "7": false,
        "8": false
    },
    "mapping": {
        "2": {
            "RUR": 18
        }
    },
    "version": 2
}
```


Example data lines:

```
name;11111111111111111111;RUR;16.04.20;REF;info;5000;0
name;11111111111111111111;RUR;16.04.20;REF;info;0;2339.7
```

**Comment by JC5** [comment]
I pushed a new build to `develop`, could you check it out? There was a bug left.

**Comment by Nixellion** [comment]
@JC5 Seems to be working but I think it's doing it the wrong way, it's using debit column as money that I spend and credit as money that I earn, but I think it's the other way around?

**Comment by JC5** [comment]
Most banks do this in reverse. Credit column gives you money.

**Comment by Nixellion** [comment]
Okay, whatever, it's not an issue.
Thanks for fixing the main one :) I suppose this can be closed.
