### ISSUE TITLE
Official Firefly III Import Config file

### ISSUE THREAD

**Issue by 8bitgentleman** [firefly-iii/firefly-iii#3273]
I am running Firefly III version 5.2.2.

**Description**
Is there an official json config file for importing to firefly from a previous version of firefly? In version 5.1 I exported my data as a CSV and I am now trying to import it via the new CSV importer but am getting a little confused about what role each column should have. 

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by JC5** [comment]
There isn't one, but I'll create one.

**Comment by JC5** [comment]
https://github.com/firefly-iii/import-configurations/blob/master/firefly-iii/5.3.0.json

It will also work for the current version :)

**Comment by 8bitgentleman** [comment]
Thank you!
