### ISSUE TITLE
Docker Image - is the sudo comand missing?

### ISSUE THREAD

**Issue by meda84** [firefly-iii/firefly-iii#3274]
I am running Firefly III version 5.2.2 with the official Docker Image on a Synology NAS. The setup is installed with the Docker-App from Synology

**Description**
Since Version 5.1.x I have problems with the cronjob for the “Recurring transactions”. The cronjob don’t fire any more. The problem is still the same with the Container for v. 5.2.2. 

**Question**
Long story short: Is it possible, that in the Linux System of the actual Docker-Images there is no “sudo”command installed? 

**my way to a solution, that works for me**
*I’m not very familiar with terminal usage for Linux and Docker but with websearch I followed the track to the ground of the problem (at least for my setting). You may not need to read that if the Question is enough information for you ;) - but maybe it helps*

My Container is named "ff_firefly-iii" , I run the cronjob with the Synology TaskManager as a admin-user and that works fine for a long time till version 5.1.x.  Unfortunately the Task Manager don't give a failure message back. So I tryed to run the cronjob command on a terminal session 

>MYUSER@MYNAS:~$ sudo docker exec ff_firefly-iii sudo -u www-data /usr/local/bin/php /var/www/firefly-iii/artisan firefly-iii:cron
> OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"sudo\": executable file not found in $PATH": unknown

I “entered” in the container and figured out, that the sudo-program is missing
> MYUSER@MYNAS:~$ sudo docker exec -it ff_firefly-iii bash
> root@ff_firefly-iii:/var/www/firefly-iii# sudo ls
> bash: sudo: command not found

Based on another websearch I added the followed lines in the file  */etc/apt/sources.list*  
> deb http://deb.debian.org/debian stretch main
> deb-src http://deb.debian.org/debian stretch main

and afterwards i was able to install sudo with the usual commands
> root@ff_firefly-iii:/# apt-get update
> root@ff_firefly-iii:/# apt-get install sudo 

After that the cronjob command line worked fine again as well in the terminal as in the Synolgy-Taskmanager. and that leads me to my question above :)

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ *a long time ago ;)*
- [ ] I added a screenshot
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Thanks for the expansive report! Your problem should be solvable by using this format. As it turns out, there's no need to add sudo to the container. I just forgot to update the docs:

```
docker exec --user www-data <container> /usr/local/bin/php /var/www/firefly-iii/artisan firefly-iii:cron
```

**Comment by meda84** [comment]
Thank you for your quick response. I tried it out with a container set back with the actual image and it seems to work fine.
