### ISSUE TITLE
404 After New Install

### ISSUE THREAD

**Issue by rafny** [firefly-iii/firefly-iii#3276]
I just did a fresh Ubuntu Apache install on a Raspberrypi and am getting 404 errors.

- Installation is on a directory since I have other services and files on the same domain. Installation: sub.domain.com/firefly-iii
- /firefly-iii shows the warning page.
- /public redirects to /public/login, but results in 404
- MariaDB is set-up and populated with tables
- rewrite module is activated
- At this point did not make any .conf file changes. I plan to do an alias after it's working properly
- Running PHP 7.3.14-1 with all required extensions (per phpinfo)
- firefly-iii/public/.htaccess is default set-up
- SSL Let's Encrypt set-up
- Firefly logs don't show any issues, but can write since they show unrelated DB errors during installation
- Apache logs don't show errors, but access log shows 404: xxx.xxx.xxx.xxx - - [18/Apr/2020:22:21:22 -0400] "GET /firefly-iii/public/login HTTP/1.1" 404 1082 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0"

**Comment by JC5** [comment]
Setting up Firefly III in a subdirectory can be pretty tricky. Google for "laravel subdirectory apache" because I have no idea how to do it.

**Comment by rafny** [comment]
Yeh, that looks a bit more complicated than I was expecting.
I'll look into setting up Firefly-iii in it's own subdomain or port#. Any documentation on best practices for that?

**Comment by rafny** [comment]
In case anyone comes around looking for an example, here's what worked for me. After I get SSL running, I'll update the port #.

`<VirtualHost *:80>
ServerAdmin webmaster@localhost
DocumentRoot /var/www/firefly-iii/public
ServerName ff.DOMAIN.com

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

 <Directory /var/www/firefly-iii/public/>
        Options -Indexes +FollowSymlinks
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>`
