### ISSUE TITLE
Set language before onboarding begins

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#3278]
The current onboarding process starts in English, and only after setting some things up you can select the language for the next step (so the first screen is never translated). I think it would be better to have a first screen that only asks for the language, and then guide the player through the creation of the account and so on.

**Comment by JC5** [comment]
Meh. Too much effort for too little gain.

**Comment by AlexKalopsia** [comment]
If localization has to be taken seriously (ie you might have a user that does not understand English), I don't think that the gain is little, especially since this is an issue in the very first step of the onboarding procedure.

An alternative would be to move the language selection at the top of the first step (rather than halfway through) and potentially refresh the page on selection.

**Comment by JC5** [comment]
> (ie you might have a user that does not understand English)

If that's the case they never managed to install the tool. Sorry man, the localization is a convenience.

**Comment by AlexKalopsia** [comment]
That's not necessarily true, someone might have an installation and open the tool to multiple users, some of them not knowing the language. I rest my case, but I'm not gonna insist 👍
