### ISSUE TITLE
PSD2 support

### ISSUE THREAD

**Issue by jancoow** [firefly-iii/firefly-iii#3280]
With the recent changes in EU regulations, can and/or will there be support for PSD2 integration? It would be awesome to have real time sync with all major banks who support this, like Rabobank, ABN, ING and many more.

**Comment by JC5** [comment]
Unfortunately, there is no such thing as "PSD2 integration". And what integration there is, isn't really feasible for Firefly III.

Firstly, the PSD2 regulation only tells banks that they should open their API's to authorized third parties. These authorized third parties must be registered at national financial institutes like "De Nederlandse Bank" for the Netherlands. Such a registration is of course, impossible for Firefly III. Unless each user registers themselves separately at the DNB. Keep in mind that this process is expensive. To authorize yourself to each bank you will also need a EDIAS compliant PSD2 digital certificate which costs op to EUR 2000,- without tax. 

So even if Firefly III was a hosted service (it's not) it would cost a lot of time to get registered and get the right certificates. And even then, these banks have manual processes to allow new API customers and there's no guarantee we'd even make the cut, if it was possible.

The PSD2 doesn't tell banks *how* to open up their API's. Each bank has their own API with its own authenthication flow, API endpoints, data-formats and queries. Literally no bank has the same API. So even if we could register Firefly III at the DBN (we can't) and we could get a PSD2 compliant certificate (we can't), and get access to the API's (we won't) we would still have to develop separate applications for each single bank.

For applications and actual end users like Firefly III and the users that use it, the PSD2 regulation doesn't add any value at all, unfortunately.

**Comment by apollo13** [comment]
While it is true that PSD2 does not mandate a specific API to open, many European banks seem to go with the API spec published by the BerlinGroup (https://www.berlin-group.org/ -- their members don't look that bad: https://static.wixstatic.com/media/c2914b_842ebdfda6884b51b6cc221c22b02ed6~mv2.jpg ).

I am in contact with two banks and they are at least in the process (so they say) of opening up those APIs for Endusers (ie not FinTechs). In general that will mean that one would have to register their own firefly instance as OAuth client I guess. Give it a year or two and it actually might be possible to access your data via those APIs (maybe not to actually start a transaction but at least access your old transactions).
