### ISSUE TITLE
Newlines do not persist in notes fields

### ISSUE THREAD

**Issue by 7596ff** [firefly-iii/firefly-iii#3281]
**Bug description**
I am running Firefly III version 5.2.2, and my problem is that newlines are not persisting in markdown formatted fields, specifically the notes section of piggy banks. 

**Steps to reproduce**
Just put some multi-line text into a notes field, hit save, and then watch the newlines disappear.

**Extra info**
Browser: Firefox 75.0

**Bonus points**
- [ ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

Further research shows this issue: https://github.com/firefly-iii/firefly-iii/issues/335 It seems that this is a feature. However, the notes field display is huge so it does not make sense why newlines are being removed.

**Comment by lguima** [comment]
That already happen to me on other objects.

See #2629

**Comment by 7596ff** [comment]
Well I searched for markdown in open issues, but that one's auto closed. :(

**Comment by JC5** [comment]
```
to add a newline, finish a sentence with two spaces  
and continue on the next line

or give a double enter
```

https://www.markdownguide.org/basic-syntax/#line-breaks

**Comment by 7596ff** [comment]
I have tried this. And it simply trims all newlines and displays everything as one line. 

In the editor: ![in the editor](https://kylie.is-pretty.cool/AaaxNpS.png)

In the piggy bank information page: ![information](https://vivian.is-pretty.cool/7ju2NNK.png)

**Comment by JC5** [comment]
I see what you mean. Sorry about the confusion. This seams to happen specifically when updating piggy banks. I was testing on accounts where it seems to work perfectly.

I'll pick it up as a bug!

**Comment by JC5** [comment]
Fixed in the next release. The fix is above my reply and fairly easy to apply in the meantime, if you want.
