### ISSUE TITLE
Bunq importer does not process transfers between assets and liabilities

### ISSUE THREAD

**Issue by jacobkiers** [firefly-iii/firefly-iii#3282]
**Bug description**
Using the latest version of the bunq importer (using Docker), transactions between asset and liability accounts in Firefly III (v5.2.2) cannot be imported.

**Steps to reproduce**

* Add an Asset account with IBAN A
* Add a Liability account with IBAN B
* Run the bunq importer, which contains a transaction that moves money from A to B

**Extra info**
I have dug a little bit into the code, and found that in the `GenerateTransactions::getTransactionType()` method there is no type for an asset => liability transaction.

I've tried to manually add it. That works and the code then continues.
However, after that an error occurs saying that the account (I presume the liability account) cannot be found. At that point I gave up.

Without adding the transaction type, nothing is imported. After adding the type, all _other_ transactions are imported.

I gave up further debugging because using Docker it is very hard to modify the code and restarting the import process. Also, I was concerned that the code would re-import already imported transactions.

**Bonus points**

- [X] Nobody reported this bug before

**Comment by JC5** [comment]
I'll check it out, thanks for reporting the issue :+1:

**Comment by JC5** [comment]
I started a new build of the Docker image. Could you do a pull and let me know the difference?

**Comment by JC5** [comment]
https://travis-ci.com/github/firefly-iii/bunq-importer-docker/builds/158470350

**Comment by jacobkiers** [comment]
> I started a new build of the Docker image. Could you do a pull and let me know the difference?

I'd be happy to. Is it safe to reimport the same date range? As in that already-imported transactions will not be duplicated?

**Comment by jacobkiers** [comment]
Ah, I imported them anyway. This fixed the bug, thanks for the _very_ quick solution! Also: great work on duplicate detection!

Is there a reason to add these as expenses, instead of transfers (as I used to do)? I always think of these as transfers, because they do not influence my net worth directly. I'm not a bookkeeper thouth, so I might miss some nuance.

**Comment by jacobkiers** [comment]
Furthermore, I have two suggestions that might making debugging easier.

*Error on token request*

When starting, I first got a 500 error in the browser, due to connecting from a wrong IP address. The error log (on the CLI) showed this: `Error message: User credentials are incorrect. Incorrect API key or IP address.` when requesting the `/token` endpoint.

I suggest making that a nicer error, so a less-technical user may understand what is going on right from the browser error page. I'd be happy to create a new bug for that.

*Improved log message*

Also a suggestion to make debugging easier:

`[2020-04-21 19:32:12] production.INFO: Downloaded and parsed 1 transactions from bunq (from this account).`

I suggest adding the account name to this message, so it is easier to find out to which account this refers.

**Comment by JC5** [comment]
The error is sent directly from Bunq, and I'd rather present it as it is. I'll add it to the [help pages](https://firefly-iii.gitbook.io/firefly-iii-bunq-importer/errors-and-trouble-shooting/token_errors) however.

I will expand the message. Keep in mind that at that poin in the code, all I have is the bunq account ID, which is an internal identifier that may not really help you.

**Comment by jacobkiers** [comment]
> The error is sent directly from Bunq, and I'd rather present it as it is. I'll add it to the [help pages](https://firefly-iii.gitbook.io/firefly-iii-bunq-importer/errors-and-trouble-shooting/token_errors) however.
> 
> I will expand the message. Keep in mind that at that poin in the code, all I have is the bunq account ID, which is an internal identifier that may not really help you.

I am not _that_familiar with the code. I agree that an internal identifier of bunq is not very helpful. Adding something to the help pages is indeed also good solution.

Since the main issue is fixed in the latest development branch, I think that this can be closed now.

Thanks a lot for the quick fix!
