### ISSUE TITLE
Payments to liabilities are marked as expenses

### ISSUE THREAD

**Issue by marier-nico** [firefly-iii/firefly-iii#3283]
I am running Firefly III version 5.0.0

**Description**
I noticed today that for some reason, payments to liability accounts seem to show up as an expense for that account. This doesn't feel right, because it's actually money coming into the account. For example, say I have an AMEX credit card that's a liability and I buy coffee for 3$ this morning. When I pay back the 3$ on the card from my cheking account, the 3$ shows up as a negative on the AMEX account. This is mostly inconvenient because the "Expense by category" pie chart includes the payments done _to_ the card (which is _not_ an actual expense), so the chart isn't really representative of my real expenses.

![Screenshot of issue](https://imgur.com/YZERYMT.png)

Here's an image of me trying it on the demo instance running the latest version (5.2.2). You can even see on the right, it says "Spent 6 euro" when I really only spent 3. I think this might just be a UI thing, because the liability account _does_ show it's at 0$ after making the payment from the checking account, so it seems like the incoming transaction is treated as income somehow as well.

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [x] I added a screenshot
- [ ] I added log files
- [x] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Set up the credit card as an asset account, not a liability.

**Comment by marier-nico** [comment]
Yeah, I guess that would fix the issue. The problem I have with this is that you won't ever receive money on a credit card right? It's always used to borrow money, which makes it a bit like a loan in that sense! I suppose if you use it as an asset, it would mean that you assume that you own all the money you borrow from the card and will always transfer it back.

If that's not how how I should look at things, could you explain in a bit more detail so I can understand? :smile: 

Also, I finally found [this](https://docs.firefly-iii.org/concepts/accounts#credit-cards) section in the FAQ, which I missed when setting things up initially, sorry about that! Do you think it would be useful to describe a bit more why credit cards are assets and not liabilities on the FAQ? If so, and if you think I understand it, I could open a PR for this.

**Comment by JC5** [comment]
No worries, feel free to write something :)
