### ISSUE TITLE
Can't create multiple users

### ISSUE THREAD

**Issue by rgtzths** [firefly-iii/firefly-iii#3289]
If I try to create multiple users:

- Tried the api and I get this error
{'message': 'Internal Firefly III Exception. See log files.', 'exception': 'Symfony\\Component\\Debug
\\Exception\\FatalThrowableError'}
When sending the request:
{"email":  "user1@mail.com", "blocked": False, "blocked_code": "email_changed",  "role": "owner"}

- Tried to create by accessing the /register and I get an error screen

Am I doing something wrong?

**Comment by JC5** [comment]
Maybe you found this already, but:


https://docs.firefly-iii.org/faq/general#is-it-multi-user

**Comment by rgtzths** [comment]
Thanks, a bit of a dumb error, sorry.

**Comment by JC5** [comment]
No worries, I'm here to help!
