### ISSUE TITLE
CSV Importer - How to import a refund from credit card

### ISSUE THREAD

**Issue by klinger-ofir** [firefly-iii/firefly-iii#3290]
I am running Firefly III version 5.2.1 and csv importer 1.0.5.

**Description**
I tried to import a refund from credit card.
CSV importer swapped the source account (credit card) with the destination account (store), which caused Firefly to search the store in the assets accounts.
This, of course, caused the import to fail.

What did I do wrong?/How should a refund be imported?

**Extra info**
 

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Could you share some example lines and your configuration (over email if necessary)?

It's probably up to the CSV importer to detect the change and respond to it.

**Comment by pizzamon** [comment]
I think I'm running into the same issue. Here's a sample CSV:

```
Transaction Date,Post Date,Description,Category,Type,Amount,Name
04/22/2020,04/22/2020,Etsy.com,Shopping,Return,22.03,Etsy.com
04/21/2020,04/22/2020,Etsy.com,Shopping,Sale,-30.09,Etsy.com
04/12/2020,04/13/2020,DOORDASH CREDIT,Fees & Adjustments,Adjustment,6.20,DOORDASH CREDIT
04/12/2020,04/13/2020,DOORDASH A,Food & Drink,Sale,-33.46,DOORDASH A
```

Note that I am using the last column for the `Opposing Account (name)` role and mapping to an account. Firefly Version: 5.2.4 and CSV Importer Version: 1.0.6

**Comment by klinger-ofir** [comment]
Hi, here some example.

CSV:
```
date,bill_date,description,business,transaction_amount,original_currency,charge_amount,charge_currency,receipt_number,notes,source,category
16/04/2020,02/05/2020,Some refund from a shop,Shop name,-1238.0,₪,-1238.0,₪,6089782,REFUND,1234,Food
```

Import configuration:
```json
{
    "date": "d\/m\/Y",
    "default_account": 1,
    "delimiter": "comma",
    "headers": true,
    "ignore_duplicate_lines": true,
    "ignore_duplicate_transactions": true,
    "rules": true,
    "skip_form": false,
    "specifics": [],
    "roles": [
        "date_book",
        "date_transaction",
        "description",
        "opposing-name",
        "_ignore",
        "_ignore",
        "amount_negated",
        "_ignore",
        "_ignore",
        "note",
        "account-name",
        "category-name"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "version": 2
}
```

CSV Importer log file (of the import with the above):
[csv-import-2020-05-02.log](https://github.com/firefly-iii/firefly-iii/files/4568583/csv-import-2020-05-02.log)

**Comment by JC5** [comment]
This issue is fixed in the latest `develop` build. Here's what to expect:

You want to import transactions from *and* to Etsy. The opposing account names could be different, but you map both to "Etsy". In your logs, this is visible like this:

```
Now at column #5 (opposing-name), value "Etsy EXP"  
ColumnIndex is 4  
Value is 'Etsy EXP'  
Local mapping {"Etsy EXP":24,"Etsy REV":24} 
Role was "opposing-name", but because of mapping (mapped to #24), role becomes "opposing-id" 
```

What you see here is that I mapped both "Etsy EXP" and "Etsy REV" to an account with ID 24. In my case this happens to be a revenue account. But it could also be a expense account. Same effect.

So the CSV importer will show the same for the other transaction and continue. At some point it will look for account 24 at Firefly III itself.

```
Going to search account with ID "24"  
[a] Found revenue account #24 based on ID "24"  
Result of findById is not null, returning: {"id":24,"name":"Etsy","type":"revenue","iban":null,"number":null,"bic":null,"currency_code":"EUR"} 
Now in determineType("asset", "revenue")  
Check config for "transaction_types.account_to_transaction.asset.revenue" and found "". Returning "withdrawal"  
12.340000000000 is positive.  
Now in determineType("revenue", "asset")  
Check config for "transaction_types.account_to_transaction.revenue.asset" and found "deposit". Returning "deposit"
```
Since I mapped to account 24, and this particular transaction is a deposit, all is well with the world and the transaction will be imported as it should be.

However, I'm also trying to import a withdrawal with the same mapping. As you guys are. **This behavior right here should now be bug free**. This is what happens:

```
Going to search account with ID "24"  
[a] Found revenue account #24 based on ID "24"  
Result of findById is not null, returning: {"id":24,"name":"Etsy","type":"revenue","iban":null,"number":null,"bic":null,"currency_code":"EUR"} 
Now in determineType("asset", "revenue")  
Check config for "transaction_types.account_to_transaction.asset.revenue" and found "". Returning "withdrawal"  
local.WARNING: The found destination account is of type revenue but this is a withdrawal. Out of cheese error.  
local.DEBUG: CSV importer will submit name "Etsy" and IBAN "" and let Firefly III sort it out.  
```

If the CSV importer finds account 24 but concludes it's of the wrong type, it will simply drop the mapping and submit the name "Etsy" to Firefly III. Firefly III in return, will map it to the correct expense account or create a new one.

Let me know if you have questions or comments.

**Comment by klinger-ofir** [comment]
Hi, 

Running an import with CSV importer 1.0.6 results in an error when the account not exists:
```
[2020-05-03 21:17:29] local.ERROR: Submission error: 0 ["Could not find a valid source account when searching for ID \"\" or name \"Shop name\"."] 
[2020-05-03 21:17:29] local.DEBUG: Now in storeJobStatus(0T7s1lZsliMLSlHm): job_running  
[2020-05-03 21:17:29] local.DEBUG: Done with storing.  
[2020-05-03 21:17:29] local.ERROR: transactions.0.source_id: Could not find a valid source account when searching for ID "" or name "Shop name". (original value: "(not found)")  
[2020-05-03 21:17:29] local.ERROR: Submission error: 0 ["Could not find a valid source account when searching for ID \"\" or name \"Shop name\"."] 
[2020-05-03 21:17:29] local.DEBUG: Now in storeJobStatus(0T7s1lZsliMLSlHm): job_running  
[2020-05-03 21:17:29] local.DEBUG: Done with storing.  
[2020-05-03 21:17:29] local.ERROR: transactions.0.source_name: Could not find a valid source account when searching for ID "" or name "Shop name". (original value: "Shop name")  
```
Should it create the account automatically?

**Comment by JC5** [comment]
It should, yes, but both accounts do not exist in your system and that confuses Firefly III. Make sure that this is the case.

I pushed some improvements however, but your example will never work when both accounts do not exist.
