### ISSUE TITLE
Importing transactions through CSV importer doesn't match the assets accounts

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3291]
**Bug description**
I am running Firefly III version  5.2.3, and my problem is:

WHen I import transactions through CSV importer, the transactions get imported correctly. However, the IBAN numbers aren't matched correctly. E.g. I import the transactions for my savings account, and the opposing bank account is correct, it still creates an expense or revenue account with the IBAN number. So I have my checkings account in assets accounts AND in expense accounts.

If I later want to update my assets account (checking account), it says the IBAN number is already in use, despite it being the first account created.

As you can see in the screenshot, the expense account is created later than the assets account, yet I can't update the assets account.

<img width="1629" alt="Screen Shot 2020-04-23 at 20 36 11" src="https://user-images.githubusercontent.com/1221024/80136597-38102600-85a2-11ea-9ca0-70a1b81d14c5.png">
<img width="1631" alt="Screen Shot 2020-04-23 at 20 36 28" src="https://user-images.githubusercontent.com/1221024/80136610-3b0b1680-85a2-11ea-8dc8-3b8261d487c6.png">
<img width="1644" alt="Screen Shot 2020-04-23 at 20 36 37" src="https://user-images.githubusercontent.com/1221024/80136611-3ba3ad00-85a2-11ea-9630-4e5b63867b2b.png">

**Steps to reproduce**
See above, the rest needed is personal data.

**Extra info**
Debug log from the page contained nothing relevant.

**Bonus points**

- [ X ] Nobody reported this bug before (might be similar to #3237
- [ ] I have added a stack trace from my log files 
- [ X ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for letting me know. It looks like the CSV importer doesn't recognize the original accounts and "overrules" the creation of new accounts.

In your case, you import transactions between A and B. Account B is also an asset account. Nevertheless, the CSV importer creates a new expense/revenue account for B. Correct?

From your screenshots, I see that both the name and the IBAN are an exact match. Despite that, No recognition from Firefly III. Also correct?

**Comment by daften** [comment]
Yes, both correct.
I first tried it without the name match, just IBAN match. After that I deleted all transactions and re-imported a set after deleting the expense accounts and changing the asset account name, that still didn't give a name.

Ideally: it would match mainly on IBAN, since we can change bank account names on online banking, but old transactions wouldn't be updated. Also, depending on which transaction list you download (source or target account), the names seem to be different sometimes (renamed account vs original name of the account I think).

Thanks!

**Comment by JC5** [comment]
This is a technical discussion on my end, and I hope to struck the golden balance soon.

When I do a very strict search for account names and numbers, there are a lot of use cases where Firefly III matches the wrong account type: ie. it matches an expense account instead of a revenue acocunt and it blocks and breaks.

On the other hand, right now, by not searching at all for accounts, this happens. So stay tuned for some experimental fixes. 

If I have something I'll let you know. In all cases, keep in mind that if I change the code significantly to fix this, Firefly III may no longer detect duplicate transactions (due to slightly changed submission values). So don't test this with large batches.

**Comment by daften** [comment]
I'm still figuring out how everything works and I'll only import everything once I figured it out, so if you need somebody to test, let me know for sure.

I'm not a financial expert, but wouldn't checking for unique numbers like IBAN first make sense and if no match is found, continue the search. That number already has to be unique across all accounts it seems.

I tried to find the relevant code that matches accounts on inserting transactions through the API, but i'm not experienced with laravel and github's viewer isn't great for that. I might try to figure out how it works this weekend to see if I can make meaningful suggestions, but because of my inexperience with financial data, they might be stupid suggestions too, in which case, shoot it down :)

**Comment by JC5** [comment]
The new version of the importer will verify the IBAN with Firefly III.

**Comment by daften** [comment]
Awesome, thanks, can't wait to try it out :)
