### ISSUE TITLE
Add filters to the transactions pages

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3292]
**Description**
It would be very nice if there would be filters on the transactions pages. The ones shown from the menu and the ones that show everything.
This way, it should be possible to filter on e.g. the Destination account and bulk update e.g. imports that went wrong. Or filter out all transactions that go to a certain account and see an overview of that.

**Solution**
Adding filters for some fields to the transactions overview pages

E.g.
* Source account
* Destination account
* Transfer minimum/maximum (would need to see how you make the distinction between withdrawals and revenue)
* Description (wildcard search)

**What are alternatives?**
None that I know of

**Additional context**
/

**Bonus points**

**Comment by JC5** [comment]
For now, only the search can do that. Use the filters you can read about on the help page (like `to:account` or `before:2020-04-20`). 

Such filters are planned for a future, new layout.

**Comment by daften** [comment]
I missed that, my apologies, I'll try that to bulk update items, thank you.
