### ISSUE TITLE
Can't enter an asset account on an expense transaction as destination

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3293]
**Bug description**
I am running Firefly III version 5.2.3, and my problem is:
I can't update an expense transaction and use an asset account as destination, to convert the transaction to a transfer.

**Steps to reproduce**
Enter any transaction with an expense account as destination (or import transactions) and update them so they have an asset account as destination account.

**Extra info**
See screenshots:
<img width="765" alt="Screen Shot 2020-04-23 at 20 46 25" src="https://user-images.githubusercontent.com/1221024/80137437-912c8980-85a3-11ea-9886-43b82546fd96.png">
<img width="476" alt="Screen Shot 2020-04-23 at 20 46 39" src="https://user-images.githubusercontent.com/1221024/80137439-938ee380-85a3-11ea-9483-e9bb5fe3641b.png">

**Bonus points**

- [ X ] Nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ X ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
No, you can't. Use the buttons on the transaction screen (`/transactions/show/*`) to convert a transaction from one type to another:

<img width="640" alt="Screenshot 2020-04-24 at 06 23 14" src="https://user-images.githubusercontent.com/5889984/80174828-5c402700-85e3-11ea-967d-19cf73768f78.png">

**Comment by daften** [comment]
I can't believe I missed those buttons. I was only looking at the edit screen 🤦 

Thanks for the quick (and patient) reply!

**Comment by daften** [comment]
If possible, I would like to ask if there is something that can be changed.
When there are a lot of transactions that were imported wrong, it's impossible to change them from e.g. expense to transfer right now by using bulk edit. If that would be possible, that would help a lot, when something goes wrong related to e.g. #3291

**Comment by JC5** [comment]
No, sorry. It's a lot easier to fix the cause.
