### ISSUE TITLE
Where is the (i) icon on the Budget / "Update (expected) available amount " page

### ISSUE THREAD

**Issue by TheObserver6995** [firefly-iii/firefly-iii#3294]
I am running Firefly III version 5.2.2

**Description**
In the help (the ? icon), for the budgets page it says as following:

> First, set the amount that is available to you by clicking the pencil icon next to "Available in ~~~". By default, this is zero. **Click the (i) icon** to get an indication of what you could spend next month. In this example, I shall use 1000,-.

When clicking on the pencil icon, I *really* don't see an (i) icon anywhere. Could you tell me, where it is? :slightly_smiling_face: 

**Extra info**

Debug information generated at 2020-04-25 13:33:29 Europe/Berlin for Firefly III version **5.2.2**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.2 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, docker_out |
| PHP version | 7.3.16 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 23:59:59 |
| Session first | 2020-01-29 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [x] I added a screenshot (https://user-images.githubusercontent.com/33379902/80279829-78c98580-86ef-11ea-967d-6e93bc3b30c7.png)
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
I removed it. I'll update the documentation.

**Comment by TheObserver6995** [comment]
Thank you. May I ask why you removed it? It sounds like an usefull feature to me.

**Comment by JC5** [comment]
It's hard to get right and turns out nobody was using it.
