### ISSUE TITLE
Error and Success when transaction cannot be updated after successfull update

### ISSUE THREAD

**Issue by Transportman** [firefly-iii/firefly-iii#3296]
**Bug description**
I am running Firefly III version 5.2.3, and my problem is:
When editing a transaction twice in a row and having the second edit fail, both the Error! and Success! bars are shown at the top of the page.

**Steps to reproduce**
Edit a transaction and submit this (Success! is now shown)
Edit the transaction in such a way that it would generate an error (I did this by having both the Source and Destination not being an Asset account and checking the "Store as a new transaction" option)
Update the transaction (shows Error and Success)

![image](https://user-images.githubusercontent.com/47077527/80285916-8c451280-8728-11ea-8889-93754709a7d4.png)

**Extra info**
Debug information generated at 2020-04-25 17:11:45 UTC for Firefly III version **5.2.3**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.3 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| PHP version | 7.3.16 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 23:59:59 |
| Session first | 2018-12-31 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Bonus points**

- [x] Nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Indeed. I'm not going to fix it.
