### ISSUE TITLE
Add a rule trigger for the foreign currency of a transaction

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3297]
**Description**
At this moment you can enter the transaction currency. It seems I can only enter transactions in the default currency at the moment and then enter a foreign currency (which is fine).

But when I use the "Transaction currency is" filter for a rule, it filters not on the foreign currency, but on the main currency of the transaction, and I can't filter on the foreign currency.

**Solution**
Add filters about the foreign currency (currency and foreign amount)

**What are alternatives?**
/

**Additional context**
/

**Bonus points**
/

- Make a drawing
- Donate money (just kidding ;)
-->

**Comment by JC5** [comment]
I'll put it on the list :)
