### ISSUE TITLE
Bills reciept/Invoice 

### ISSUE THREAD

**Issue by kungfu71186** [firefly-iii/firefly-iii#3302]
**Description**
I was thinking it would be nice to see something for bills. A simple invoice system. 

**Solution**
Basically when you create a bill, be able to create an invoice. Nothing complicated for now, simply generate an invoice based off a template. This can be used as a receipt of some kind to say you paid someone and it generates a PDF. This could possibly be enhanced further later to add 3rd party solutions like docusign. Not looking for anything complicated, just something to print off a pdf invoice.

**What are alternatives?**
Quicken or really any accounting system

**Additional context**

**Bonus points**
I can't draw, so here is an ascii dog i copied from somewhere
```
   / \__
  (    @\___
  /         O
 /   (_____/
/_____/   U
```

**Comment by JC5** [comment]
Haha I like the dog =)

But no, sorry, this isn't going to happen. It's insanely complex, a product in its own right. It's outside of the scope of what I want to do with Firefly III.

**Comment by kungfu71186** [comment]
@JC5 Yeah no worries. I kinda figured. Thought I suggest it.
