### ISSUE TITLE
Default GPS location is automatically set when editing accounts and cannot be removed

### ISSUE THREAD

**Issue by jyundt** [firefly-iii/firefly-iii#3307]
**Bug description**
I am running Firefly III version `5.2.4`, and my problem is:

I'm unable to clear the GPS location set for accounts when a Mapbox API key is set. When editing an account, a default GPS location of `51.983333000000`,`5.916667000000` is automatically set and cannot be removed.

**Steps to reproduce**

- Define Mapbox API key (`MAPBOX_API_KEY`)
- Restart firefly-iii
- Edit existing account, make any non-location change, e.g. adding to "Notes" field
- Save changes
- Verify that a GPS location is now preset
- Re-edit account, click `Clear location` button
- Save changes
- Verify that a GPS location is still set

**Extra info**
I'm running this in kubernetes using the `5.2.4` container. ([Link to my firefly-iii k8s yaml](https://github.com/jyundt/ansible_playbooks/blob/master/wellesleynet/roles/k8s/files/firefly.yml) in case this is helpful.)

debug info:

Debug information generated at 2020-04-28 17:23:07 UTC for Firefly III version **5.2.4**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.4 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| PHP version | 7.3.16 |
| Display errors | Off |
| Session start | 2019-12-20 00:00:00 |
| Session end | 2020-04-28 00:00:00 |
| Session first | 2019-01-14 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36 |

**Bonus points**
- I searched and nobody reported this bug before
- I have added a ~screenshot~ [video of this behavior](https://drive.google.com/file/d/1_srf1uPkuRuBxIR4HfQHAK0AVGJecGCr/view?usp=sharing) (I wasn't sure of the best method to share this video because there is some sensitive account data. Lemme know if anyone else needs access to the screencast.)

**Comment by jyundt** [comment]
Bleh sorry, maybe this is working as expected. I just looked at [EditController.php](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/Account/EditController.php#L98-L100) and I guess setting the default location to `MAP_DEFAULT_LAT`, `MAP_DEFAULT_LONG` is expected behavior when a location is "not set".

**Comment by JC5** [comment]
It shouldn’t just set the location like that. I’ll pick it up as a bug. The idea is that you select a location yourself.

**Comment by jyundt** [comment]
Ah perfect, thank you for the quick response!

**Comment by JC5** [comment]
This should be fixed in the next release.
