### ISSUE TITLE
Add option to add more locales into Docker

### ISSUE THREAD

**Issue by xSMiNTx** [firefly-iii/firefly-iii#3308]
It would be great tro have an option to set locales with an environment variable in Docker

**Comment by JC5** [comment]
To which problem is this your proposed solution?

**Comment by xSMiNTx** [comment]
Sorry for not clarifying. 
If I set my "Locale settings" in Firefly to "German (Switzerland)" I get the error "Invalid server configuration: Firefly III is unable to format monetary amounts because your server is missing the required packages." 
It would be great to have an environment variable to make the Docker container generate additional locales.

**Comment by 101stArrow** [comment]
I am also getting a similar issue when changing my local to British English

**Comment by JC5** [comment]
I see what you mean. The locales can be useful when you run your own installation (ie. outside of Docker) but I can't include them all in the Docker build. If you want local formatting for numbers you'll have to install the required packages in your Docker container yourself or run an installation on bare metal.

**Comment by Nebucatnetzer** [comment]
I tried to install the locales with a custom Dockerfile.
While it got it working it didn't really change anything in the web interface.
The dates, etc. still looked American. On the demo page it seems to be the same.

**Comment by gimiki** [comment]
@Nebucatnetzer I guess the dates format depend on your browser language. I can successfully display dates in the format that I want changing the browser language.

**Comment by Nebucatnetzer** [comment]
Ah right I had it set to English US, with English Canada I'm getting ISO dates.
My bad :)
