### ISSUE TITLE
Running FireflyIII on Unraid, Budgets and Spending Report for April 2020 on Dashboard only showing for April 1 2020 

### ISSUE THREAD

**Issue by brianstephens347** [firefly-iii/firefly-iii#3309]
I am running Firefly III version  5.2.4

**Description**
Running FireflyIII on Unraid, and just finished getting April Finances into the system. I just got everything setup and noticed on Budgets and Spending Report for April 2020 on Dashboard only showing for April 1 2020. I have added some data to March and March seems to work fine. 

**Extra info**
Unraid, running FireflyIII from the Docker Template. 
Accessing using both LetsEncrypt and local IP address provide same result.

![April 2020 View](https://user-images.githubusercontent.com/37872531/80647382-60819f80-8a3c-11ea-9320-84fcff491126.PNG)

I was not able to replicate this on the demo site. 

I don't know if I borked something up during the setup or if its something I need to fix myself. Would appreciate guidance. 

**Bonus points**

- I added log files

**Comment by JC5** [comment]
If you see April first only, you've probably created a budget limit for that date specifically. Go to /budgets, and delete any such entries.

**Comment by brianstephens347** [comment]
I deleted and recreated the budgets. I do now know how I would have set a budget limit just for that period. Here is one of the budget screens. 

![Budget Utilities](https://user-images.githubusercontent.com/37872531/80711383-44264700-8abe-11ea-8a45-e0355cbbd66a.PNG)

When I click to view all transactions in a specific budget, it gives me all the correct data, but in the bottom right chart it is still only April 1, same as the dashboard chart.

![Budget Transactions](https://user-images.githubusercontent.com/37872531/80711805-f5c57800-8abe-11ea-8b73-b3ca9f347a0e.PNG)

**Comment by JC5** [comment]
Whats the /budgets page look like?

**Comment by brianstephens347** [comment]
Here it is

![Budget Page](https://user-images.githubusercontent.com/37872531/80713384-59e93b80-8ac1-11ea-9fd9-b9298f579d0b.PNG)

**Comment by JC5** [comment]
Thx. Sorry, I have no clue what's going on. I'll do some deep diving.

**Comment by brianstephens347** [comment]
This is still a problem when I go back to April, but May is working just fine.

**Comment by crakkhead** [comment]
I have the same issue with Firefly 5.2.5 running on a regular LAMP stack on a Raspberry Pi. After installation I added multiple budgets as well as transactions for May and I see exactly the same thing as @brianstephens347.
![budgets](https://user-images.githubusercontent.com/6554041/82604369-82da8900-9bb4-11ea-808e-3c7040decd6d.png)
![dashboard](https://user-images.githubusercontent.com/6554041/82604392-8a9a2d80-9bb4-11ea-93fc-5534b36f42e5.jpg)

**Comment by JC5** [comment]
Alright, could you both show me the results of this query please? It would help me show the possible problem:

```sql
SELECT id, budget_id, transaction_currency_id, start_date, end_date, amount FROM budget_limits
```

**Comment by crakkhead** [comment]
I've attached the results. There are only 2 budgets atm.
[budget_limits.txt](https://github.com/firefly-iii/firefly-iii/files/4666933/budget_limits.txt)

**Comment by JC5** [comment]
Thanks, I appreciate it. For now, I can only offer some debug code (to be included in 5.2.6). Once released, upgrade at your earliest convenience and let me know the results. From there, we can find the root cause.

**Comment by crakkhead** [comment]
After upgrading to 5.2.6 and turning on debug mode, I've created a new user, a budget and two expenses, one for today and one for May 1st. I see the same behaviour as previously described. Attached are the logs for the new user.
[ff3-apache2handler-2020-05-23.log](https://github.com/firefly-iii/firefly-iii/files/4672039/ff3-apache2handler-2020-05-23.log)
[ff3-audit-2020-05-23.log](https://github.com/firefly-iii/firefly-iii/files/4672040/ff3-audit-2020-05-23.log)

**Comment by JC5** [comment]
Did you set a budget limit (amount)? Because I'm not seeing it in the logs.

**Comment by crakkhead** [comment]
I did, it has budget id 4.
![budget_details](https://user-images.githubusercontent.com/6554041/82736895-3b2b3d00-9d2d-11ea-9cdd-a2d82356ad05.jpg)
![budgets](https://user-images.githubusercontent.com/6554041/82736896-3d8d9700-9d2d-11ea-9b68-63d68aaa93a2.jpg)
[budget_limits.txt](https://github.com/firefly-iii/firefly-iii/files/4672230/budget_limits.txt)

**Comment by JC5** [comment]
Did you enter the amount yourself on the page in the screenshot? That part isn’t visible in the logs unfortunately.

**Comment by crakkhead** [comment]
No, I've entered it while creating the budget.

**Comment by JC5** [comment]
Thanks! That was the missing link I was looking for; where the amount came from. 

I can't release 5.2.7 so soon after the previous release but rest assured it's fixed in the next release. @brianstephens347 thanks for your patience :)

**Comment by crakkhead** [comment]
Awesome! Thank you for fixing it so quickly.

**Comment by JC5** [comment]
In the mean time:

- Click on the arrow next to the amount
- Click Remove
- Set the amount by hand.

**Comment by crakkhead** [comment]
> In the mean time:
> 
>     * Click on the arrow next to the amount
> 
>     * Click Remove
> 
>     * Set the amount by hand.

That did the trick. I tried changing the amount, but didn't delete it first. Now budgets are displayed as attended.

**Comment by brianstephens347** [comment]
Going back and removing the budget amounts did the trick. Thanks for putting in the time to fix the issue.

**Comment by brianstephens347** [comment]
2
