### ISSUE TITLE
Total Budget

### ISSUE THREAD

**Issue by pbauerochse** [firefly-iii/firefly-iii#3311]
Hi there,

I'm not sure if this is already possible:

**Description**
Allow marking a budget as fixed, non-reoccurring budget.

We are currently building a house and have taken a loan from the bank to finance it. Each part of the construction was estimated beforehand, e.g. for the mason we estimated a budget of x, while for the roof we estimated a budget of y. These budgets are not granted each quarter / month but are fixed. Once the part of the construction has been finished, we can see, whether we were on track with our budget, or need to cut short on other parts.

Thanks in advance

**Comment by JC5** [comment]
You could use tags track this. That’s why I do with projects like this.
