### ISSUE TITLE
Show future transactions in the all transactions view

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3314]
**Description**
Some transactions from my bank get marked with a date in the future because they officially can only be carried out on the next banking day / workday. E.g. when creating this issue, I imported transactions via CSV-importer that have the date 04/05. But these transactions don't show up anywhere, not even the all transactions views. Is this a purposeful limitation atm?

To make it clear: these are not future recurring transactions in firefly itself. These are imported transactions from bank exports.

Next to that, as a sidenote,  I personally find it confusing that when you go to a previous month on e.g. the withdrawals screen, the navigation to other months between the current month and that month, are gone. E.g. you go to january, there' no way to go back to february or april besides going to withdrawals again and going to the correct month. Is this for a technical reason?

**Solution**
Have all the transactions show up on the all transactions screens.

**What are alternatives?**
No idea

**Additional context**
/

**Bonus points**

**Comment by JC5** [comment]
Thanks for the hint. I was under the impression they were visible in all views. You can see them under the account view, ie `/accounts/show/1/all`. I'll make sure that they're visible under the `/transactions/withdrawal/all` page as well.

As for the date navigation: it's not perfect I know. It's on my list :)

**Comment by daften** [comment]
Something else I've noticed with transactions in the future: when I'm on the assets account overview page, the balance is taking the future transactions into account (which seems to be correct). When on the transactions overview page for that account, the balance is ok. But when going to the all transactions page for that account, the balance only takes transactions until and including today into account, so not the future transactions.

**Comment by JC5** [comment]
I’ll pick it up:)
