### ISSUE TITLE
Unable to add attachment in Attachment API

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#3316]
Hello James, I am running Firefly III version 5.2.4 and I have an issue with storing an attachment in a Transaction. The endpoint in question is /api/v1/attachments
I'm unsure of 2 parameters, they are namely `attachable_type` and `attachable_id`. 

1. What are the valid values for `attachable_type`?
2. What is a valid value for `attachable_id` for transactions? Do I use a Journal ID? Do I use a Transaction ID? I tried both and it fails. 

```
{
  "message": "The given data was invalid.",
  "errors": {
    "attachable_id": [
      "The given ID seems invalid for this model."
    ]
  }
}
```

Thanks!

**Comment by JC5** [comment]
Use the journal ID, it should work like this:

https://api-docs.firefly-iii.org/#/attachments/storeAttachment

```
{
	"filename": "test.txt",
	"attachable_type": "TransactionJournal",
	"attachable_id": 1
}
```

After that, you still have to upload of course but this should work. Let me know!

**Comment by emansih** [comment]
Ah, it's TransactionJournal..... The documentation could be improved.

**Comment by JC5** [comment]
Indeed. I just noticed that the api docs were still a version behind. The new ones should be up on https://api-docs.firefly-iii.org/ 

Sorry about that!
