### ISSUE TITLE
csv-importer: does not automap IBANs to existing asset accounts

### ISSUE THREAD

**Issue by FelikZ** [firefly-iii/firefly-iii#3317]
**Bug description**
I am running Firefly III version 5.2.4, and my problem is:

When I am importing my ABN transactions using csv-importer 1.0.6 it does not map transactions to existing asset accounts based on IBAN match as it were behaviour during embedded csv importer prior v5.2.0

**Steps to reproduce**
1. Create multiple asset accounts with IBAN
2. Import CSV with AbnAmroDescription enabled and transactions between IBANs that include assets from 1)

**Expected:**
Transactions falls into existing asset accounts. Transaction type **transfer**.

**Actual:**
New **expense** accounts with **exactly the same name** as existing **asset** accounts created and transactions are belongs there. Transaction type **withdrawal**.

**Extra info**
During the import:
![Annotation 2020-05-01 120108](https://user-images.githubusercontent.com/1080269/80798527-e3be0500-8ba4-11ea-836f-6386ab54b1cc.png)
Imported as withdrawal, expected transfer:
![Annotation 2020-05-01 120108-2](https://user-images.githubusercontent.com/1080269/80798530-e4569b80-8ba4-11ea-8d48-5dfa2c912358.png)
Existing asset account:
![Annotation 2020-05-01 120108-3](https://user-images.githubusercontent.com/1080269/80798523-e28cd800-8ba4-11ea-96f8-fa1d250d3c3b.png)
New expense account created instead:
![Annotation 2020-05-01 120108-4](https://user-images.githubusercontent.com/1080269/80798524-e3256e80-8ba4-11ea-8306-45580568be48.png)

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.

**Comment by FelikZ** [comment]
Config:
```
{
    "date": "Ymd",
    "default_account": 1,
    "delimiter": "tab",
    "headers": false,
    "ignore_duplicate_lines": true,
    "ignore_duplicate_transactions": true,
    "rules": true,
    "skip_form": true,
    "specifics": [
        "AbnAmroDescription"
    ],
    "roles": [
        "account-number",
        "currency-code",
        "date_transaction",
        "_ignore",
        "_ignore",
        "_ignore",
        "amount",
        "description",
        "opposing-name",
        "opposing-iban",
        "note"
    ],
    "do_mapping": {
        "0": true,
        "1": true,
        "2": false,
        "3": false,
        "4": false,
        "5": false,
        "6": false,
        "7": false,
        "8": true,
        "9": true,
        "10": false
    },
    "mapping": [
        {
            "533533535": 5,
            "533533531": 1,
            "533533533": 3,
            "533533536": 6
        },
        {
            "EUR": 1
        }
    ],
    "version": 2
}
```
`note` is a special additional field I am generating besides the standard abn amro import.

**Comment by JC5** [comment]
Thanks for the expansive bug report. Like I said, I was under the impression I fixed this. No matter, it's on the list!

**Comment by JC5** [comment]
Automap is now present in the latest develop build.

**Comment by FelikZ** [comment]
Thank you!🔥
