### ISSUE TITLE
AutoBudget wouldnt be triggered by URL-Cronjob

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#3318]
**Bug description**
I am running Firefly III version 5.2.3 and my problem is: If I use the token based URL to trigger my cronjob, the autoBudget is not added.

Curl-Output:

> The recurring transaction cron job fired successfully.

If I instead use the CLI/PHP-call, the autoBudget is added and the output of the CMD looks like:
> The recurring transaction cron job fired successfully.
> The auto budget cron job fired successfully.

**Comment by JC5** [comment]
Thanks, that explains why my own auto budgets didn't trigger this morning. I still had to debug this :grin:
