### ISSUE TITLE
"Budgets and spending" have a permanent "overspent" zero

### ISSUE THREAD

**Issue by FelikZ** [firefly-iii/firefly-iii#3319]
**Bug description**
I am running Firefly III version 5.1.1, and my problem is:
I want to see how much I overspent on "Budgets and spending" graphs as an orange color, but this does not seem to work.

**Steps to reproduce**
1. Create a budget with a "0" expectations, to track specific expenses
2. Make a withdrawal transaction that falls into this budget
3. Go to dashboard and see that overspent is 0

**Extra info**
![Annotation 2020-05-01 144523](https://user-images.githubusercontent.com/1080269/80806498-2b4f8b80-8bbb-11ea-8d04-38b2c24b9759.png)
![Annotation 2020-05-01 144523-2](https://user-images.githubusercontent.com/1080269/80806503-2be82200-8bbb-11ea-90b6-80f47900eda3.png)

**Bonus points**

- I have added a screenshot.

**Comment by JC5** [comment]
Yes, this is by design. If there's no budget, there's no overspending. It's just spent. It's only overspent when there is a limit to overspend over.

But I see the `/budgets` page is inconsistent, and I'll check it out :+1:

**Comment by FelikZ** [comment]
@JC5 I've tried to put there 1eur budget - it shows 0 overspent as well

**Comment by JC5** [comment]
That's something I cant replicate. If I set a number, the overspent amount changes.

<img width="1037" alt="Screenshot 2020-05-01 at 15 38 14" src="https://user-images.githubusercontent.com/5889984/80809387-1d950880-8bb1-11ea-8e56-fb75c00416b0.png">

<img width="1149" alt="Screenshot 2020-05-01 at 15 38 51" src="https://user-images.githubusercontent.com/5889984/80809398-22f25300-8bb1-11ea-8ff5-762164802f97.png">

**Comment by FelikZ** [comment]
@JC5 anything I can try to help you? Here more screenshots with 1eur budget:
![an2](https://user-images.githubusercontent.com/1080269/80811164-9f8f2c80-8bc5-11ea-8869-d1387801392b.png)
![an1](https://user-images.githubusercontent.com/1080269/80811165-a027c300-8bc5-11ea-98be-3ed853f677ac.png)

Perhaps it is being fixed since 5.2.0?

**Comment by JC5** [comment]
That could be the case, yes.
