### ISSUE TITLE
[Feature Request] Confirmation for deletion of budgets/categories/tags

### ISSUE THREAD

**Issue by PsychoGame** [firefly-iii/firefly-iii#3320]
Dear developer,

Would it be possible to add a confirmation box before deletion of tags/budgets/categories commences?
I accidentily deleted all my categories when I was using Firefly-III on my mobile phone.
When scrolling I accidentily touched the delete categories link and all my categories were gone.
Luckily I just started with Firefly, so there weren't much transactions in it yet.

Greetings Jasper

**Comment by JC5** [comment]
Which link exactly? As far as I know they all have confirmation dialogs
