### ISSUE TITLE
piggy bank api: adding funds

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3321]
I am running Firefly III version 5.2.4

I want to add money to a piggy bank via the api Piggy bank has $100 in it. I do a put to /api/v1/piggy_banks/{id}. JSON of 

{"current_amount":200}

This sets the piggy bank to have $200, but it also says I added $200 to it in the piggy transaction table, which isn't true. I only added $100.

How can I add money to a piggy bank without messing up the transactions table?

**Comment by JC5** [comment]
You mean the table on the page of each piggy bank, right?

**Comment by JC5** [comment]
Never mind, found and fixed.
