### ISSUE TITLE
Pages and blocks icons outdated

### ISSUE THREAD

**Issue by lguima** [firefly-iii/firefly-iii#3322]
**Bug description**
I am running Firefly III version `develop`, and my problem is:

I worked on the menu reordering but totally forgot to update the icons around the site, on the top of the pages and on the blocks related.

I'm opening this issue to track until I or someone can fix.

**Steps to reproduce**
- Access a page that had the icon changed in sidebar menu and compare the changed icon with the one on the top of the page.
- Access a page that have a block related to the pages that had the icon changed and compare the changed icon with the one on the block.

**Comment by JC5** [comment]
No worries, I already fixed some of them, the rest will follow in due course. Since this is still the develop branch, no need to panic.

**Comment by lguima** [comment]
Got it, just in case you were planning a release.

**Comment by JC5** [comment]
Yes, but nothing major. I noticed that the Transactions overview page says "Accounts" instead of "Transactions" and nobody noticed (including me) for over 8 months. We're good :wink:
