### ISSUE TITLE
Question on updates

### ISSUE THREAD

**Issue by nloshka** [firefly-iii/firefly-iii#3324]
Debug information generated at 2020-05-02 07:16:52 Europe/Amsterdam for Firefly III version **5.2.3**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.3 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.3.17 |
| Display errors | Off |
| Session start | 2020-05-01 00:00:00 |
| Session end | 2020-05-31 23:59:59 |
| Session first | 2018-12-08 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, apcu, posix, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apc, igbinary, imagick, inotify, msgpack, zip, Phar, memcached, redis, Zend OPcache |

Errors occur during the upgrade process
update output is presented below

how critical are these errors?
Are the system getting the correct updates?
Thank you in advance for your response.
------------------

Updating c155019..e6442dd
error: Your local changes to the following files would be overwritten by merge:
	app/Support/Steam.php
Please, commit your changes or stash them before you can merge.
Aborting
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 88 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-ctype (v1.15.0): Loading from cache
  - Installing phpoption/phpoption (1.7.3): Loading from cache
  - Installing vlucas/phpdotenv (v3.6.3): Loading from cache
  - Installing symfony/css-selector (v5.0.7): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.2): Loading from cache
  - Installing symfony/polyfill-php72 (v1.15.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.15.0): Loading from cache
  - Installing symfony/var-dumper (v4.4.7): Loading from cache
  - Installing symfony/routing (v4.4.7): Loading from cache
  - Installing symfony/process (v4.4.7): Loading from cache
  - Installing symfony/polyfill-php73 (v1.15.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.15.0): Loading from cache
  - Installing symfony/mime (v5.0.7): Loading from cache
  - Installing symfony/http-foundation (v4.4.7): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.7): Loading from cache
  - Installing symfony/event-dispatcher (v4.4.7): Loading from cache
  - Installing psr/log (1.1.3): Loading from cache
  - Installing symfony/debug (v4.4.7): Loading from cache
  - Installing symfony/error-handler (v4.4.7): Loading from cache
  - Installing symfony/http-kernel (v4.4.7): Loading from cache
  - Installing symfony/finder (v4.4.7): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/service-contracts (v2.0.1): Loading from cache
  - Installing symfony/console (v4.4.7): Loading from cache
  - Installing symfony/polyfill-iconv (v1.15.0): Loading from cache
  - Installing doctrine/lexer (1.2.0): Loading from cache
  - Installing egulias/email-validator (2.1.17): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.3): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing ramsey/uuid (3.9.3): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing opis/closure (3.5.1): Loading from cache
  - Installing symfony/translation-contracts (v2.0.1): Loading from cache
  - Installing symfony/translation (v4.4.7): Loading from cache
  - Installing nesbot/carbon (2.32.2): Loading from cache
  - Installing monolog/monolog (2.0.2): Loading from cache
  - Installing league/flysystem (1.0.67): Loading from cache
  - Installing league/commonmark (1.4.1): Loading from cache
  - Installing dragonmantank/cron-expression (v2.3.0): Loading from cache
  - Installing doctrine/inflector (1.3.1): Loading from cache
  - Installing laravel/framework (v6.18.10): Loading from cache
  - Installing tightenco/collect (v7.6.1): Loading from cache
  - Installing adldap2/adldap2 (v10.2.3): Loading from cache
  - Installing adldap2/adldap2-laravel (v6.0.9): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.5.3): Loading from cache
  - Installing bunq/sdk_php (dev-master d97d2a7): Loading from cache
  - Installing facade/ignition-contracts (1.0.0): Loading from cache
  - Installing davejamesmiller/laravel-breadcrumbs (5.3.2): Loading from cache
  - Installing doctrine/event-manager (1.1.0): Loading from cache
  - Installing doctrine/cache (1.10.0): Loading from cache
  - Installing doctrine/dbal (2.10.2): Loading from cache
  - Installing fideloper/proxy (4.3.0): Loading from cache
  - Installing symfony/polyfill-util (v1.15.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.15.0): Loading from cache
  - Installing paragonie/constant_time_encoding (v2.3.0): Loading from cache
  - Installing pragmarx/google2fa (v7.0.0): Loading from cache
  - Installing bacon/bacon-qr-code (1.0.3): Loading from cache
  - Installing pragmarx/google2fa-qrcode (v1.0.3): Loading from cache
  - Installing jc5/google2fa-laravel (2.0.4): Loading from cache
  - Installing laminas/laminas-zendframework-bridge (1.0.3): Loading from cache
  - Installing symfony/psr-http-message-bridge (v2.0.0): Loading from cache
  - Installing phpseclib/phpseclib (2.0.27): Loading from cache
  - Installing psr/http-factory (1.0.1): Loading from cache
  - Installing php-http/message-factory (v1.0.2): Loading from cache
  - Installing nyholm/psr7 (1.2.1): Loading from cache
  - Installing league/event (2.2.0): Loading from cache
  - Installing lcobucci/jwt (3.3.1): Loading from cache
  - Installing defuse/php-encryption (v2.2.1): Loading from cache
  - Installing league/oauth2-server (8.0.0): Loading from cache
  - Installing laminas/laminas-diactoros (2.2.3): Loading from cache
  - Installing firebase/php-jwt (v5.2.0): Loading from cache
  - Installing laravel/passport (v8.4.4): Loading from cache
  - Installing laravelcollective/html (v6.1.0): Loading from cache
  - Installing league/csv (9.6.0): Loading from cache
  - Installing league/flysystem-replicate-adapter (1.0.1): Loading from cache
  - Installing league/flysystem-sftp (1.0.22): Loading from cache
  - Installing league/fractal (0.19.2): Loading from cache
  - Installing litipk/flysystem-fallback-adapter (0.1.3): Loading from cache
  - Installing mschindler83/fints-hbci-php (1.0.4): Loading from cache
  - Installing pragmarx/random (v0.2.2): Loading from cache
  - Installing pragmarx/recovery (v0.1.0): Loading from cache
  - Installing predis/predis (v1.1.1): Loading from cache
  - Installing twig/twig (v2.12.5): Loading from cache
  - Installing rcrowe/twigbridge (v0.11.3): Loading from cache
Package davejamesmiller/laravel-breadcrumbs is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Deprecation Notice: Class Fhp\DataElementGroups\KeyNameTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/KeyNameTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityDateTimeTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityDateTimeTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityIdentificationDetailsTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityIdentificationDetailsTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityProfileTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityProfileTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SignatureAlgorithmTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SignatureAlgorithmTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\BinTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/BinTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\DatTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/DatTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KikTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KikTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtiTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtiTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtvTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtvTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\Message\MessageTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/Message/MessageTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\ResponseTest\ResponseTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/ResponseTest/ResponseTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
12 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php -r "if (!(getenv('DYNO'))===false){file_exists('.env') || copy('.deploy/heroku/.env.heroku', '.env');copy('.deploy/heroku/.locales', '.locales');}"
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Package davejamesmiller/laravel-breadcrumbs is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Deprecation Notice: Class Fhp\DataElementGroups\KeyNameTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/KeyNameTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityDateTimeTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityDateTimeTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityIdentificationDetailsTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityIdentificationDetailsTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityProfileTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityProfileTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SignatureAlgorithmTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SignatureAlgorithmTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\BinTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/BinTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\DatTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/DatTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KikTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KikTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtiTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtiTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtvTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtvTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\Message\MessageTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/Message/MessageTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\ResponseTest\ResponseTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/ResponseTest/ResponseTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
12 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan firefly:instructions install
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v5.2.3!                                |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
Nothing to migrate.
Seeding: AccountTypeSeeder
Seeded:  AccountTypeSeeder (0.05 seconds)
Seeding: TransactionCurrencySeeder
Seeded:  TransactionCurrencySeeder (0.04 seconds)
Seeding: TransactionTypeSeeder
Seeded:  TransactionTypeSeeder (0.01 seconds)
Seeding: PermissionSeeder
Seeded:  PermissionSeeder (0.01 seconds)
Seeding: LinkTypeSeeder
Seeded:  LinkTypeSeeder (0.01 seconds)
Seeding: ConfigSeeder
Seeded:  ConfigSeeder (0.01 seconds)
Database seeding completed successfully.
Going to decrypt the database.
No decryption required for table "accounts".
No decryption required for table "attachments".
No decryption required for table "bills".
No decryption required for table "budgets".
No decryption required for table "categories".
No decryption required for table "piggy_banks".
No decryption required for table "preferences".
No decryption required for table "tags".
No decryption required for table "transaction_journals".
No decryption required for table "transactions".
No decryption required for table "journal_links".
Done!
Application cache cleared!
Now seeding the database...
Nothing to migrate.
Seeding: AccountTypeSeeder
Seeded:  AccountTypeSeeder (0.05 seconds)
Seeding: TransactionCurrencySeeder
Seeded:  TransactionCurrencySeeder (0.05 seconds)
Seeding: TransactionTypeSeeder
Seeded:  TransactionTypeSeeder (0.01 seconds)
Seeding: PermissionSeeder
Seeded:  PermissionSeeder (0 seconds)
Seeding: LinkTypeSeeder
Seeded:  LinkTypeSeeder (0.01 seconds)
Seeding: ConfigSeeder
Seeded:  ConfigSeeder (0.01 seconds)
Database seeding completed successfully.
Now decrypting the database (if necessary)...
Going to decrypt the database.
No decryption required for table "accounts".
No decryption required for table "attachments".
No decryption required for table "bills".
No decryption required for table "budgets".
No decryption required for table "categories".
No decryption required for table "piggy_banks".
No decryption required for table "preferences".
No decryption required for table "tags".
No decryption required for table "transaction_journals".
No decryption required for table "transactions".
No decryption required for table "journal_links".
Done!
Now installing OAuth2 keys...
Encryption keys already exist. Use the --force option to overwrite them.
Personal access client created successfully.
Client ID: 197
Client secret: ***
Password grant client created successfully.
Client ID: 198
Client secret: ***
Done!
Now executing firefly-iii:transaction-identifiers
This command has already been executed.
Now executing firefly-iii:migrate-to-groups
Database already seems to be migrated.
Now executing firefly-iii:account-currencies
This command has already been executed.
Now executing firefly-iii:transfer-currencies
This command has already been executed.
Now executing firefly-iii:other-currencies
This command has already been executed.
Now executing firefly-iii:migrate-notes
This command has already been executed.
Now executing firefly-iii:migrate-attachments
This command has already been executed.
Now executing firefly-iii:bills-to-rules
This command has already been executed.
Now executing firefly-iii:bl-currency
This command has already been executed.
Now executing firefly-iii:cc-liabilities
This command has already been executed.
Now executing firefly-iii:back-to-journals
This command has already been executed.
Now executing firefly-iii:rename-account-meta
This command has already been executed.
Now executing firefly-iii:migrate-recurrence-meta
This command has already been executed.
Now executing firefly-iii:migrate-tag-locations
This command has already been executed.
Now executing firefly-iii:fix-piggies
All piggy bank events are correct.
Verified the content of 2 piggy bank events in 0.01 seconds.
Now executing firefly-iii:create-link-types
All link types OK!
Verified link types in 0.01 seconds
Now executing firefly-iii:create-access-tokens
All access tokens OK!
Verify access tokens in 0.01 seconds.
Now executing firefly-iii:remove-bills
All transaction journals have correct bill information.
Verified bills / journals in 0 seconds
Now executing firefly-iii:enable-currencies
2 different currencies are currently in use.
All currencies are correctly enabled or disabled.
Verified currencies in 0.02 seconds.
Now executing firefly-iii:fix-transfer-budgets
No invalid budget/journal entries.
Verified budget/journals in 0 seconds.
Now executing firefly-iii:fix-uneven-amount
Amount integrity OK!
Verified amount integrity in 0.02 seconds
Now executing firefly-iii:delete-zero-amount
No zero-amount transaction journals.
Verified zero-amount integrity in 0.01 seconds
Now executing firefly-iii:delete-orphaned-transactions
No orphaned transactions.
No orphaned accounts.
Verified orphans in 0.01 seconds
Now executing firefly-iii:delete-empty-journals
No uneven transaction journals.
No empty transaction journals.
Verified empty journals in 0.01 seconds
Now executing firefly-iii:delete-empty-groups
Verified empty groups in 0.01 seconds
Now executing firefly-iii:fix-account-types
All account types are OK!
Verifying account types took 4.3 seconds
Now executing firefly-iii:rename-meta-fields
All meta fields are correct.
Renamed meta fields in 0.09 seconds
Now executing firefly-iii:fix-ob-currencies
Going to verify 3 opening balance transactions.
Corrected 3 opening balance transactions.
Now executing firefly-iii:fix-long-descriptions
Verified all transaction group and journal title lengths in 0.07 seconds.
Now executing firefly-iii:fix-recurring-transactions
Corrected recurring transactions 0.01 seconds.
Now executing firefly-iii:report-empty-objects
User #1 (***@***) has category #10 ("Такси Тимошин") which has no transaction journals.
User #1 (***@***) has category #18 ("Хз") which has no transaction journals.
User #1 (***@***) has category #38 ("Кредит Сбербанк") which has no transaction journals.
User #1 (***@***) has account #9 ("Левые") which has no transactions.
User #1 (***@***) has account #19 ("Транспорт") which has no transactions.
User #1 (***@***) has account #23 ("Кредиты и долги") which has no transactions.
User #1 (***@***) has account #24 ("ХЗ") which has no transactions.
User #1 (***@***) has account #26 ("Школа") which has no transactions.
User #1 (***@***) has account #27 ("Ремонт и содержание") which has no transactions.
User #2 (***@***) has account #66 ("1-Карта Сбербанк") which has no transactions.
User #2 (***@***) has account #67 ("сберегательный счёт в 1-Карта Сбербанк") which has no transactions.
User #2 (***@***) has account #68 ("Кошелёк с наличными") which has no transactions.
Report on empty objects finished in 0.01 seconds
Now executing firefly-iii:report-sum
Amount integrity OK for user #2
Amount integrity OK for user #1
Report on total sum finished in 0.02 seconds
Now executing firefly-iii:restore-oauth-keys
OAuth keys are OK
Now executing firefly:instructions update
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for updating to Firefly III, v5.2.3!                               |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
Encryption keys already exist. Use the --force option to overwrite them.
Personal access client created successfully.
Client ID: 199
Client secret: ***
Password grant client created successfully.
Client ID: 200
Client secret: ***
Application cache cleared!

**Comment by JC5** [comment]
Thanks for asking!

These errors are not a problem, and they won't compromise the security of your system. 

Some times packages (like this one) have a directory structure that's not according to the norm. Recently, composer started warning about this. The package is due to be removed anyway so the error will disappear in the near future.

Hope this helps!

**Comment by nloshka** [comment]
Thanks for the answer.
Let's hope that everything will be fine!
