### ISSUE TITLE
Change currencies in Expense/Revenue accounts

### ISSUE THREAD

**Issue by jonaszierer** [firefly-iii/firefly-iii#3325]
**Description**
Currently the interface does not allow to change the currency of a Expense/Revenue account. 

**Solution**
Should be the same as for asset accounts

**What are alternatives?**
I randomly found out that changing the default currency temporarily will change the currencies of newly created expense/revenue accounts. So it shouldn't be a problem to add that without chaning the default currency. It already works fine in the overview list

**Comment by JC5** [comment]
What would be the goal exactly, to change the currency of those accounts?

**Comment by jonaszierer** [comment]
thanks for the super quick reply!

In the list of expense accounts I have several accounts showing a balance of 0 because they have only transactions in a different currency. That's a bit confusing (and I assume fixing the currency would fix that..?)

**Comment by JC5** [comment]
I see what you mean, it's on my list to fix that. :)

**Comment by jonaszierer** [comment]
very cool, thanks!

**Comment by rainclear** [comment]
It seems that we still cannot set the currency of expense and revenue accounts.  My default currency is Canadian Dollar.  When I created new expense and revenue transactions, the source and destination accouts are created, but always shown Euro and the balances are always 0.

**Comment by rainclear** [comment]
Never mind.  I changed default currency to be C$ and recreated the transactions and now it is fine.
