### ISSUE TITLE
Do a rule-check when updating a transaction

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#3326]
I've set up an expense, and realized that Firefly didn't recognize it as a Bill. I investigated and turns out I misspelled the destination account, so I went ahead, edited the transaction to the correct name, saved, and Firefly still didn't set the transaction as a Bill. 

I ended up removing the transaction and re-creating it. It would be nice if when editing a transaction Firefly could do a "pass" on the rules and make sure they are triggered after editing is done.

**Comment by JC5** [comment]
You can create rules that trigger when updating a transaction.

**Comment by AlexKalopsia** [comment]
Cool, I missed that option! I am assuming that "when it is updated" includes the creation trigger?

**Comment by JC5** [comment]
No. It's either a trigger at the creation of a transaction, OR at the update of a transaction.
