### ISSUE TITLE
Add "last 3 months" preset

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#3327]
Quite often I am at the beginning of a new month and I just want to quickly check how my expenses went in the previous 3 months. I know I can use the custom range, but it feels to me that having a 3 months period would just be really convenient and some fairly common preset.

If I can extend the suggestion, Q1, Q2, Q3 and Q4 would also be very useful (at least more than the "Today" preset in my personal experience.

**Comment by JC5** [comment]
You could use reports to do this?

**Comment by AlexKalopsia** [comment]
Well, it's still extra step (plus even the report section doesn't really have any 3 months preset and I'd have to manually define the time period. 

To me it's mostly a matter of usability. Sometimes I just need the 3 months to have a quick overview of all my recent transaction, and for me 3 months is an ideal timeframe.

**Comment by AlexKalopsia** [comment]
Bumping this. I keep finding myself either having to create a 3 window frame manually, or ending up shortcutting to Everything, making everything much slower because of the amount of data pulled. To me it feels like it's pretty common to look at the previews few months (vs just one month in the past), so a general preset of current date -90 days would be really helpful
