### ISSUE TITLE
How to deal with a multi-user-setup and the new csv-importer?

### ISSUE THREAD

**Issue by MadWalnut** [firefly-iii/firefly-iii#3328]
Hi,

I just upgraded from 5.1.1 to 5.2.4 and therefore "lost" the inbuilt CSV importer. So I installed the csv-importer alongside my Firefly installation on my VPS. So now I have:

_firefly.domain.com/firefly-iii_   **and**   _firefly.domain.com/csv-importer_

In the .env file of the csv-importer I have to set a Personal Access Token. But this is linked to my profile / my Firefly account, right? 

So how can the other users on my Firefly-installation use the same csv-importer instance? Or is that not possible? If not, how do I provide the csv-importer for these users? They are not capable of installing it themselves on e.g. localhost.

Perhaps I am just missing a hint on how to correctly deploy the csv-importer to the server? 

Thanks in advance :)

**Comment by JC5** [comment]
The CSV importer is really a single user thing, I'm afraid. Each user will have to set up their own instance.

**Comment by MadWalnut** [comment]
Thanks for the clarification. Do you plan to reintroduce multi-user-support sometime in the future? And by any chance, there is no way to enable the old CSV importer in v5.2 and up, right?

**Comment by JC5** [comment]
No, I don't think so. The code for the old CSV importer is already gone for the most part, so I'm afraid not.

**Comment by MadWalnut** [comment]
Thanks.
