### ISSUE TITLE
Transaction timestamps not counted in month-end boundary

### ISSUE THREAD

**Issue by calvin-n-hobbes** [firefly-iii/firefly-iii#3330]
**Bug description**
I have been using the timestamp feature from Issue #2006 and noticed that if I have transactions on the last day of the month (with a time that's not 00:00), then when viewing the transactions by month, those transactions are missing. You can see the transactions when you click on "Show all transactions without grouping them by date."

For example, I created an expense transaction dated April 30, 2020 08:19,
<img width="632" alt="Screen Shot 2020-05-03 at 08 28 27" src="https://user-images.githubusercontent.com/5327981/80918223-c5791600-8d18-11ea-86e8-a1121c4ae363.png">
but it does not show up when I view the expenses for the month of April,
<img width="1150" alt="Screen Shot 2020-05-03 at 08 30 39" src="https://user-images.githubusercontent.com/5327981/80918252-db86d680-8d18-11ea-9c47-3bfe7c265b5d.png">

This also affects the Bills section. This particular transaction counts as a bill, but when I view the Bills, the system does not list it as a payment for this bill cycle.

I suspect the date boundaries don't extend to 23:59 of the last day?

**Extra info**
```
Debug information generated at 2020-05-03 08:24:08 America/Los_Angeles for Firefly III version **5.2.4**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.4 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.16 |
| Display errors | Off |
| Session start | 2020-05-01 00:00:00 |
| Session end | 2020-05-31 23:59:59 |
| Session first | 2017-05-26 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15 |
```

**Comment by JC5** [comment]
I see it, confirmed. Thanks for letting me know. I'll pick it up in the next release!

**Comment by calvin-n-hobbes** [comment]
Thanks for the quick turnaround!
