### ISSUE TITLE
CSV Importer - Import Identifier Tag

### ISSUE THREAD

**Issue by 4oo4** [firefly-iii/firefly-iii#3331]
**Description**
Just starting using the new CSV importer tool, and after updating my configs that's working great. However I did notice that the transactions no longer have an import identifier like they did before (I think it was "Imported with key"). ~~I know that a lot has changed under the hood for the import routine (so I don't think import keys are used anymore?), but was wondering if it's possible to have some kind of identifier to tag the transactions with?~~ Maybe an option that could be set in the config JSON file?

Basically I like to know what import job a particular transaction came from, this makes it extremely helpful to find offages/duplicates when importing transactions. In particular, sometimes a new import has overlapping transactions with an old one, to fix those it's super handy to have that identifier.

**Solution**
~~Auto-tag new transactions to identify what import batch they came from, perhaps with a timestamp or hash?~~ I can see now that there is a job identifier, so probably easiest to use that?

```
[2020-05-03 21:44:08] local.DEBUG: Now in storeJobStatus(7JC1PbOjRkbLdbq1): waiting_to_start  
[2020-05-03 21:44:08] local.DEBUG: Done with storing.  
[2020-05-03 21:44:08] local.DEBUG: Now in storeJobStatus(7JC1PbOjRkbLdbq1): waiting_to_start  
[2020-05-03 21:44:08] local.DEBUG: Done with storing. 
```

**What are alternatives?**
Not sure if there are alternatives to this already that I don't know about? I suppose it would be possible to do this with Rules but that seems tricky to configure.

Cheers

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3243
