### ISSUE TITLE
Why "Account number" column shows IBAN first?

### ISSUE THREAD

**Issue by Bubka** [firefly-iii/firefly-iii#3332]
Hi James and Contributors,

I am running Firefly III version 5.2.5.

**Description**
On the accounts index ( `/accounts/asset` ) the `Account number` column shows the IBAN code if this one is set, even if the account number is set, whereas the column is titled "Account **_number_**"

Steps to reproduce :
- Open the Edit form of an account
- Set the Account number field and save => The Account number is displayed as expected
- Edit the account again, add an IBAN (and let the Account number filled) then save => The IBAN is displayed in place of the Account number.

This is not a bug, this matches with the twig template :

```php
<td class="hidden-sm hidden-xs">{{ account.iban }}{% if account.iban == '' %}{{ accountGetMetaField(account, 'account_number') }}{% endif %}</td>
```

But this is not really an obvious behavior in my opinion because the column title is not adjust to reflect the data replacement. If IBAN is considered a more relevant data to be displayed first why not (this is not my perspective), but at least the column title should match the data.

What do you think ?

**Comment by JC5** [comment]
Indeed, it's not a bug. I prioritize the IBAN over the account number. Not sure what else to tell you. They're both account numbers, so the column matches the content.
