### ISSUE TITLE
[Feature request] Store the date of import in the date field of the tag

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#3333]
**Description**

Hello James, 

I've  tested your new releases of the importer and ff3 and saw that transaction tag is returned. Nice!
However the CSV importer does not store the date of the import in the Date field. The date is now only written to the name of the tag.

**Solution**
It is a minor concern but i would love to have the date also in it's appropriated field in the tag.

**Comment by JC5** [comment]
Good idea, I’ll see if I can fix that!

**Comment by JC5** [comment]
Turned out to be easy enough. New develop build of the CSV importer will add the date to the tag. Would appreciate your feedback if it works as expected.

**Comment by leander091** [comment]
Nice!, I've tested the latest develop build and it worked as expected
