### ISSUE TITLE
Import CSV : Not able to create a deposit

### ISSUE THREAD

**Issue by 8bitgentleman** [firefly-iii/firefly-iii#3334]
**Bug description**
I am running Firefly III version 5.2.2, and my problem is:

I am importing a CSV which was exported from a previous version of firefly iii into a fresh install of Firefly. Several errors are thrown, the importer silently changes deposits to withdraws, and the importer silently changes the source_account to an incorrect account. I have attached the config JSON file as well as an example CSV file.

Line by line in the CSV file the errors are as follows:
1. Comes in correctly as a withdraw, no error
2. Fails with errors
	* (2) transactions.0.destination_id: Source and destination are the same. (original value: "1940")
	* (2) transactions.0.destination_name: Source and destination are the same. (original value: "(not found)")
3. Comes in correctly as a transfer
4. Comes in incorrectly with no errors given. Problems include:
	* Transaction is changed to a withdraw
	* Transaction “source_type” is silently changed from Venmo to the default account (#1940)

**Steps to reproduce**
Import the attached CSV with the attached config file to a new install of firefly

**Extra info**
I have 2 asset accounts set up in Firefly iii named:

- Credit Card Account

- Checking Account

[import test files.zip](https://github.com/firefly-iii/firefly-iii/files/4577384/import.test.files.zip)

**Comment by JC5** [comment]
Alright, can you try the latest version of the `develop` branch for the CSV importer? 

- Had to create the "Credit Card Account" (I have a "Checking Account").
- Changed the default account from 1940 to 1. Remember this has to be an asset account.

```
Message in line #1: Created withdrawal <a target="_blank" href="http://firefly.local/transactions/show/230">#230 "Takeout"</a> (EUR 14.16)
Message in line #2: Created deposit <a target="_blank" href="http://firefly.local/transactions/show/231">#231 "Reinbursed Ticket"</a> (EUR 18)
Message in line #3: Created transfer <a target="_blank" href="http://firefly.local/transactions/show/232">#232 "Credit Card Payment"</a> (EUR 2927.06)
Message in line #4: Created deposit <a target="_blank" href="http://firefly.local/transactions/show/233">#233 "Wifi"</a> (EUR 25)
```

So for me, this imports correctly.

**Comment by 8bitgentleman** [comment]
Sorry for the slow reply, looks like your latest version of the `develop ` branch fixed it right up. Thanks!
