### ISSUE TITLE
Updating transactions resets time portion of timestamps

### ISSUE THREAD

**Issue by calvin-n-hobbes** [firefly-iii/firefly-iii#3338]
**Bug description**

I am running Firefly III version 5.2.5 and using transaction timestamps with a time portion (e.g., May 4, 2020 @ 18:00), but notice that whenever I update a transaction, Firefly resets the time portion to 00:00.

**Steps to reproduce**

1. Create a transaction with some non-00:00 timestamp (screenshot shows 19:35)<img width="631" alt="Screen Shot 2020-05-05 at 09 22 33" src="https://user-images.githubusercontent.com/5327981/81090943-5be13f00-8eb3-11ea-89f8-888a40ea1fc3.png">
1. Edit the transaction and click the "Update transaction" button
1. The timestamp gets reset to 00:00<img width="629" alt="Screen Shot 2020-05-05 at 09 22 55" src="https://user-images.githubusercontent.com/5327981/81091006-761b1d00-8eb3-11ea-9778-e52552553654.png">

**Extra info**

Debug information generated at 2020-05-05 09:29:29 America/Los_Angeles for Firefly III version **5.2.5**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.5 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.17 |
| Display errors | Off |
| Session start | 2020-05-01 00:00:00 |
| Session end | 2020-05-31 23:59:59 |
| Session first | 2017-05-26 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15 |

**Comment by JC5** [comment]
Indeed. This is not a bug. The time is displayed but that’s it.

**Comment by calvin-n-hobbes** [comment]
But in the underlying data store, is the time actually being overwritten? I can go back and update the time again on the same transaction, but just concerned that there's data loss, especially if you do a bulk update that resets multiple transactions' times without ability to restore them to the previous values.

**Comment by JC5** [comment]
It is, yes. 

The database supports time stamps and the UI displays them. But it’s all rather primitive (no time zones for example). I know the “store transaction” routine adds a time stamp. But that’s it. The rest of Firefly III will ignore it and reset it. 

I could do the same with the “store transaction” routine but I don’t care that much.

**Comment by calvin-n-hobbes** [comment]
Got it, thanks, I'd love to put in feature request for this if you ever want to entertain that idea in the future! (I don't know PHP, but if I ever pick it up, I'd submit a PR for this.)
