### ISSUE TITLE
Cannot mass delete reconciliation transactions

### ISSUE THREAD

**Issue by maksimkurb** [firefly-iii/firefly-iii#3339]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:
When I click `Delete` button on multiple reconciliation transactions in some account, it redirects me on the main page instead of showing confirmation page

**Steps to reproduce**
1. Create 2 reconciliation transactions for some account
1. On the account page click on checbox on these 2 reconciliation transactions
1. At the table header click `Actions` -> `Delete`
1. We are redirected to the main page, but expected to see confirmation window. Transactions are not deleted, of course.

**Screenshot**
![chrome_IJW1RoD8pf](https://user-images.githubusercontent.com/1351924/81103214-c92bb900-8f21-11ea-8845-ad1fd2e4bc7b.jpg)

**Logs**
[ff3-audit-2020-05-05.log.txt](https://github.com/firefly-iii/firefly-iii/files/4583012/ff3-audit-2020-05-05.log.txt)
[ff3-fpm-fcgi-2020-05-05.log.txt](https://github.com/firefly-iii/firefly-iii/files/4583013/ff3-fpm-fcgi-2020-05-05.log.txt)

**Comment by JC5** [comment]
Indeed. A fix is on the way, in the mean time you'll have to delete them one by one. Thanks for letting me know :)
