### ISSUE TITLE
[JS] Reconciliation page calculates difference incorrectly when operations has different currencies

### ISSUE THREAD

**Issue by maksimkurb** [firefly-iii/firefly-iii#3340]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:
If I add reconciliation transaction, then change account currency and after try to make reconciliation again with the time range that includes first reconciliation with a different currency, `Reconciliation options` will calculate difference incorrectly, summing one currency with another.

When you click `store reconciliation`, in popup difference is calculated correctly as expected, though.

**Steps to reproduce**
1. Create new account with a RUB currency.
1. Create reconciliation transaction with end balance `100RUB`. -100RUB reconciliation transaction will be created.
1. Switch account currency to EUR.
1. Create reconciliation transaction with end balance of `0.5EUR`. Check that previous -100RUB transaction date is between `start date` and `end date`.
1. On the right `Reconciliation options` box you will see that difference is -100.50EUR [100RUB + 0.5EUR] (summing apples with oranges)
1. Click `store reconciliation` button. In the popup you will see expected -0.5EUR transaction.

**Screenshots**
![chrome_a0yNTcjoib](https://user-images.githubusercontent.com/1351924/81104689-f24d4900-8f23-11ea-8ef2-a083911de1a0.jpg)
![chrome_YUytr0RSB7](https://user-images.githubusercontent.com/1351924/81104680-eeb9c200-8f23-11ea-923a-b72a701c3fca.jpg)

**Logs**
I don't think they are needed because this is a client-side bug, not server-side. This bug is reproducible on Firefly III demo site.

**Comment by JC5** [comment]
You know, multi-currency is nice but you're really stretching it dude, come on. What's your use case for changing the currency of an account?

**Comment by maksimkurb** [comment]
I've just found this behaviour while testing previous bug. I agree that this is a very specific use-case, but if it's allowed, I thought it would be nice if such bug will be at least in history of the project so if someones catch it and have a questions, they can at least found it here.
As an example, I have a bank which allows me to convert my deposit currency from mobile app. (Yes, I know, that I can just create second account and make a transaction from account A to B).

Feel free to close it.

**Comment by JC5** [comment]
I'll see what I can do :-)
