### ISSUE TITLE
menu and graph does not appear 

### ISSUE THREAD

**Issue by sultanbet89** [firefly-iii/firefly-iii#3341]
I am running Firefly III version 5.2.5
--

.

**Description**
menu and graph does not appear 

**Extra info**
The problem all starts suddenly, the accordion menu cannot be opened & after that all graph is gone
i use softaculous to install & update Firefly III 

![image](https://user-images.githubusercontent.com/64887179/81144936-5b25d700-8f9f-11ea-8309-78c137fe2f1d.png)

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot

- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Any error messages?

**Comment by sultanbet89** [comment]
> Any error messages?

no error messages

**Comment by JC5** [comment]
Then I can't help I'm afraid.

I need something from your console, or from your system logfiles. If parts of Firefly don't work, it will generate errors somewhere and I need those to see what's happening.

**Comment by sultanbet89** [comment]
I moved the hosting server (new install) and did manual data input to recover it
![image](https://user-images.githubusercontent.com/64887179/81165032-7ef71600-8fbb-11ea-983e-2db3f41b251b.png)
the  the upper right hand corner menu cannot be opened
![image](https://user-images.githubusercontent.com/64887179/81165160-c087c100-8fbb-11ea-9163-804ef069237a.png)
Left menu that has an accordion menu cannot be opened

what & where system logfiles  file is needed?, so I can send it
Please help me

**Comment by JC5** [comment]
Check out the console in your browser. Usually its Ctrl Shift i.

**Comment by sultanbet89** [comment]
![image](https://user-images.githubusercontent.com/64887179/81180660-8c20fe80-8fd5-11ea-874e-bfebd1cdcec9.png)

**Comment by JC5** [comment]
Your server doesn't support or include some security measures. Maybe they strip headers or something? I see a reference to "pagespeed" which isn't Firefly III code. Sorry, I can't help you.

**Comment by sultanbet89** [comment]
someone help me

**Comment by sultanbet89** [comment]
after being left and not opened for some time (1-2 hours) appear again as normal and then suddenly after one menu is selected. like this example:
when i open /public/piggy-banks
![image](https://user-images.githubusercontent.com/64887179/81199981-918a4300-8fed-11ea-8543-f851fade77e9.png)
after that  after that, everything is not open anymore
![image](https://user-images.githubusercontent.com/64887179/81200223-ddd58300-8fed-11ea-9375-b91de717af96.png)

**Comment by sultanbet89** [comment]
![image](https://user-images.githubusercontent.com/64887179/81201087-0f9b1980-8fef-11ea-87a5-1a3962f6266b.png)

**Comment by sultanbet89** [comment]
temporary solution: use https at the address
