### ISSUE TITLE
Cannot add attachments to accounts

### ISSUE THREAD

**Issue by AbrahamTewa** [firefly-iii/firefly-iii#3344]
**Bug description**
I am running Firefly III version 5.2.5.

When editing an account, we can add attachments. Adding an attachement seems to work: However, when displaying the account page, the following message is displayed: 

> This attachment could not be found.

![image](https://user-images.githubusercontent.com/4184985/81222213-3869e180-8fe4-11ea-863b-417c46580fdf.png)

Notice:
* Uploading attachements to transactions is working correctly
* The attachement is editable (the link `/attachments/edit/{id}` works
* The uploaded file is found in the `upload/` folder
* The file is viewable (the link `/attachments/view/{id}` works)

**Steps to reproduce**

* Edit an asset account
* Add a new attachment
* Save (no error message)
* Open the same asset account

In the attachment list, an error message is displayed : " This attachment could not be found. ".

**Extra info**
My environment:
* Windows 10
* docker / docker-compose
* Firefox 77 and Chrome 81

**Bonus points**
- I searched and nobody reported this bug before
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
indeed. Nice find! This should be fixed in the next release :)
