### ISSUE TITLE
CSV importer not grabbing delimiter from JSON

### ISSUE THREAD

**Issue by MadWalnut** [firefly-iii/firefly-iii#3345]
**Bug description**
I am running CSV importer version 1.0.7, and my problem is:
When using a configuration JSON where the delimiter is set to ";" the field is set to "," after clicking on upload.

**Steps to reproduce**
1. Upload a JSON configuration with delimiter set to ";"
2. Click on upload and see, that all values are correctly taken from the JSON, except for delimiter which is ","

I was able to reproduce it with these import configs: 
_import-configurations/be/argenta/default.json
import-configurations/de/dkb/csv-giro.json_

**Extra info**
Windows, Firefox, Docker Installation.

**Comment by JC5** [comment]
Nice find. I've pushed a fix to the develop branch and the Docker build should be updated in about 10 minutes. Let me know if it works :+1:

**Comment by MadWalnut** [comment]
It works! Thank you for the fast fix 🥇
