### ISSUE TITLE
CSV-importer: filter "Datum/tijd:" from ING NL descriptions

### ISSUE THREAD

**Issue by bramd** [firefly-iii/firefly-iii#3346]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:

When importing recent CSV files from ING (NL), it seems ING adds "Datum/tijd: dd-mm-yyyy hh:mm:ss" just before "Valutadatum: ...". The "Valutadatum" part is properly stripped by the importer, but the "Datum/tijd" part is not. It is not clear to me when this is or is not added exactly, it does not happen for all transactions.

Without stripping this, the description gets verbose and it causes issues matching transactions if you have two accounts, one with ING and one at another bank, since the descriptions mismatch. 

**Steps to reproduce**

1. Export a CSV file from ING
1. Import it in Firefly

**Extra info**
This is a bug in the CSV importer, but I didn't see issues on that repository.

**Comment by JC5** [comment]
There's a link in the readme of the CSV importer that says "report bug". It leads here. :)

Could you share (over email if necessary) some example lines? I don't use ING myself. Also polling @rubenverhoef who fixed the ING import last time :+1:

**Comment by rubenverhoef** [comment]
Recently i added the stripping of the `valutadatum` from the `mededelingen` column to an dedicated column. The `valutadatum` is always present and in my opinion most of the time useless information, so i moved it to an column to cleanup the `mededelingen`  column.

The value `Datum/Tijd` in the `mededelingen` column is not always present and gives some more information about the transaction. It is possible to also move that one to an other column, but i don't know if `hh:mm:ss:` format is supported for an date field.
And when we do that, it will create an other unnamed column. So it would be wise to have the ability to name the newly created columns so we know what kind of data it is.

I can make the stripping of `Datum/Tijd` into an dedicated column if this is desirable. To do so i first have to update mine installation to the `CSV-importer` structure.

@JC5 Can you say if the `dd-mm-yyyy hh:mm:ss:` format is supported for an date field, and how we can name the newly created columns?

**Comment by bramd** [comment]
I also wonder which date/time this is exactly. If it is just a more specific version of the valutadatum, we might just use this instead of valutadatum. I'll have to find some CSV lines for transactions with interesting valutadatums, such as in weekends and on holidays to see what the pattern is.

I only looked at the importer code and not at Firefly itself. So I'm not sure what flexibility there is for storing additional data with transactions. The datum/tijd is very useful information, but I don't like it in the description. If there are good facilities for storing additional transaction data, we might also look at descriptions for an "automatische incasso". These include usually some kind of description, but also the various codes such as machtiging ID, incasso ID etc. If we have good custom fields, it might be useful to strip such things from the description as well and save them in separate columns.

**Comment by rubenverhoef** [comment]
I think the `Datum/Tijd` value inside the `mededelingen` column is the exact time the transaction was made. The `valutadatum` is the date when the currency of the transaction is established. When you have an transaction from/to the same currency this is the same date.

I like the idea of putting more into additional custom fields, but for this we need to name the columns right so we know what kind of data is in the specific column.

**Comment by JC5** [comment]
[This method](https://github.com/firefly-iii/csv-importer/blob/master/app/Services/CSV/Specifics/IngDescription.php#L177) allows you to add custom headers if you want to. I think you could do something like this already:

```php
    /**
     * @inheritDoc
     */
    public function runOnHeaders(array $headers): array
    {
        $headers[9] = 'Valutadatum';
        return $headers;
    }
```

I just wrote some code that makes the CSV importer add time support, so you can convert the date of the transaction to something like "2020-05-09 12:34:56" and Firefly III would respect it.

I can play around if somebody shares some example lines.

**Comment by bramd** [comment]
> I can play around if somebody shares some example lines.

Here are just two lines I adapted from a real ING CSV file:

```
"Datum","Naam / Omschrijving","Rekening","Tegenrekening","Code","Af Bij","Bedrag (EUR)","MutatieSoort","Mededelingen"
"20200506","Test 1","NL00INGB0001234567","NL00INGB0002345678","GT","Bij","140,00","Online bankieren","Naam: Test 1 Omschrijving: Testtransactie 1 IBAN: NL00INGB0002345678 Datum/Tijd: 06-05-2020 00:26:49 Valutadatum: 06-05-2020"
"20200504","Test 2","NL00INGB0001234567","NL00RABO0123456789","OV","Bij","260,00","Overschrijving","Naam: Test 2 IBAN: NL00RABO0123456789 Datum/Tijd: 04-05-2020 23:15:35 Valutadatum: 04-05-2020"
```

* The IBAN of the downloaded account is NL00INGB0001234567
* The first line is a transaction with a description of "Testtransactie 1" between two ING accounts
* The second one is a transaction from a Rabobank account to the ING account, this transaction has an empty description

**Comment by JC5** [comment]
I committed some code that detects the time and puts it in a separate column.

**Comment by JC5** [comment]
I'm having some trouble with the account name / IBAN but that might be a bug.

**Comment by JC5** [comment]
Never mind, that was my mistake. I used the following import configuration.

```
{
    "date": "Ymd H:i:s",
    "default_account": 1,
    "delimiter": "comma",
    "headers": true,
    "ignore_duplicate_lines": true,
    "ignore_duplicate_transactions": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "specifics": [
        "IngDescription"
    ],
    "roles": [
        "date_process",
        "opposing-name",
        "account-iban",
        "opposing-iban",
        "_ignore",
        "ing-debit-credit",
        "amount",
        "tags-comma",
        "description",
        "date_interest",
        "date_transaction"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "version": 2
}
```
