### ISSUE TITLE
Add a quick link to reconcile account on home screen

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3348]
**Description**
With the new left-side menu (great addition!), reconciling is now one more click away from home screen: we now need to expand the "accounts" drill down menu to click on "Asset accounts" which has the "reconcile" button. This feature is for me one of the most important one of Firefly, I think it deserves better visibility.

**Solution**
Add a button to reconcile the account directly on the home screen, in the account panel.

**What are alternatives?**
3 clicks from home screen to reconcile screen.
Documentation (https://docs.firefly-iii.org/advanced-concepts/reconcile) says you can do it on the page of an individual asset account but I haven't found it.

**Additional context**
Here is a suggestion on where to place it:
![image](https://user-images.githubusercontent.com/34862846/81470493-4b9ace00-91eb-11ea-84aa-f7f91718193d.png)
IMHO, option 1 looks better but it makes more sense to place it near the amount you're about to reconcile (option 2).

**Comment by JC5** [comment]
I'm not a fan, but I understand what you want. Check out the [demo site](https://demo.firefly-iii.org/). What do you think?

**Comment by sephrat** [comment]
May I suggest "Actions" instead of "Options" if you implement it that way? Or maybe I'm not just not fluent enough in English :-) not a native speaker here, you choose.
It's a good idea, but I wonder if we won't miss that green "Create" button which definitely is the "go-to" button of Firefly III.

Let me try and merge our two ideas and amend my initial suggestion: add a new button to have a new drill down menu to reconcile and possibly other options like "edit" or "hide from home screen". Things you may do regularly ("edit" is not the best candidate... but reconcile is a good one) but not every time you open Firefly III like creating transactions.

Let me show off my Paint skills:
![image](https://user-images.githubusercontent.com/34862846/81477331-96cad600-9217-11ea-8c17-4c09523c07f5.png)
If you feel like me that the new "Options" is starting to fill up the screen, maybe change it for a gear icon or those 3 vertical dots we see on some Firefly III screens - that could fit nicely in the top right corner.

Or maybe something even more simple like:
![image](https://user-images.githubusercontent.com/34862846/81477662-291fa980-9219-11ea-824c-e0fde0d555bb.png)

**Comment by JC5** [comment]
Check out the demo site. What do you think?

**Comment by sephrat** [comment]
I like it! Handy and discreet. Thanks.
