### ISSUE TITLE
When importing through the API, account type is not taken into account

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3349]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:

The account look-up based on IBAN is working pretty well, but now I've noticed somewhere it fails. I have an expense account with an IBAN number, and it's an external account. When I try to import a CSV that contains that IBAN number as a source, so as a revenue account, it still tries to use the expense account, and the import fails.

I only tested it so far with internal accounts, and since those are transfers with asset accounts, they work as expected, but for "external" accounts (revenue/expense), I think there will need to be a check on the type of account being looked up too (e.g. as source only asset and revenue accounts)

**Steps to reproduce**
Have an account with IBAN number as expense account, DON'T have it as revenue account.
Try to import a transaction with that IBAN number as the source account.

**Extra info**

Output from CSV importer:
(3) transactions.0.source_id: Could not find a valid source account when searching for ID "249" or name "". (original value: "249")
(3) transactions.0.source_name: Could not find a valid source account when searching for ID "249" or name "". (original value: "(not found)")
(3) Internal error: Return value of App\Services\Import\Routine\APISubmitter::processTransaction() must be of the type array, object returned in file /var/www/html/app/Services/Import/Routine/APISubmitter.php:191

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by daften** [comment]
Just checked, manually creating the revenue account made the import succeed, but I'm not sure why. Maybe it gets the most recent account or something, but there's definitely a small bug there somewhere I think :)

**Comment by JC5** [comment]
Check out the logs. Is there an "out of cheese" notification? I'd like to see everything, your configuration and some example lines please.

Most importantly, do these new accounts only have an IBAN, and no other info?

**Comment by JC5** [comment]
Alright, I did some deep-diving, on the assumption that you're submitting IBAN's only as the source/destination of your import. When that's the case, the CSV importer will pick up the IBAN and use it as the name of the account. That way, Firefly III itself will create a new account (expense or revenue) that's called "NL90ABNA5251802137" (or whatever IBAN you use).

This small improvement should already change things in the right way. The docker build should be done in about 10 minutes.

**Comment by daften** [comment]
Hi,

I use IBAN and Bank account name for source/target identification. At least, I map those in the importer. I'll try the upgrade now by deleting the transaction and re-importing some stuff.

**Comment by daften** [comment]
I just tried it, with the revenue transaction and account deleted, and I get the same problem with csv-importer 1.0.7 and firefly 5.2.5 :(

**Comment by daften** [comment]
ALso for logs, which logs would you like to see, csv-importer, firefly-iii? debug enabled?

**Comment by JC5** [comment]
What would help, is a few example lines. Together with the config you're using. Drop them here or at james@firefly-iii.org. I can do some research then.

**Comment by daften** [comment]
I will drop the logs a bit later when I've got time to extract them properly and give all the information together. could take a day or 2 for this .I'll email them since they could contain data I don't want exposed for all the internet :)

**Comment by JC5** [comment]
No worries, take your time. I'm curious to see what's happening! Thanks for your help debugging this :)
