### ISSUE TITLE
When there are transactions in a foreign currency, the transactions graphs on top of the page are distorted

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3350]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:

I have some transactions in COP, my main currency is EUR. The conversion rate is about 4000 to 1. For this month I have some transactions in foreign currencies, one of which is in COP. Screenshot below, but the blue category is restaurant, the total of which is €30.93. Somehow, the total calculated is shown as COL$ (COP), and then €20.800. My house category is already at >€900 this month, yet that is the green small section.

I do not understand where the number 20800 comes from tbh (it's twice the single COP transaction, but there's no other correlation to numbers I can find). Since it uses COP numbers, it also distorts the graphs immensely.

With my limited understanding of the tool so far, all transactions should have the main currency filled out AFAIK, so why isn't that number used? Am I missing something?

The budgets and destination accounts charts have the same bug.

**Steps to reproduce**

I could not test this, but I think it can be reproduced easily: enter 2 transactions in an empty db. One in euro or dollar, and one with cop as the foreign currency. Make sure the numbers are different enough to make the distinction easily. And look at the graphs/charts on top of the currency page

**Extra info**
/

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
You mean the page like /transactions/withdrawal and the others, right?

Your screenshot seems to have been lost.

**Comment by daften** [comment]
Exactly.
And my bad, forgot to add it 🤦 

<img width="456" alt="Screen Shot 2020-05-10 at 18 29 16" src="https://user-images.githubusercontent.com/1221024/81506022-eed70a80-92f3-11ea-85c0-5c1f2e404b2b.png">

**Comment by JC5** [comment]
The double amount could happen if other transactions have foreign currency information. Is that the case?

I can't replicate the EUR sign, when I do this with different currencies it comes out OK.

When the amounts are this different, the distortion can't be helped.

**Comment by daften** [comment]
yes, I have the amount in euro as the main transaction amount (the asset account linked is in euro) and the amount is also entered in the foreign currency (I like my data to be complete).

Isn't there a way to use the main transaction amount, and not the foreign currency amount for this? Correct me if I'm wrong, but the main transaction amount needs to be in the currency of the asset account right, so why not use just that? What am I missing? :)

**Comment by JC5** [comment]
Check. You found a bug alright, some bad math when adding amounts in foreign amounts. But I see what you mean and the next release will be more sensible. Foreign amounts will be ignored when drawing the chart.

**Comment by daften** [comment]
I don't know many OS maintainers that are as quick with fixes as you are :O 

Thanks James!
