### ISSUE TITLE
Shared Accounts - Consideration of balance and transactions in reports/dashboard

### ISSUE THREAD

**Issue by Basta911** [firefly-iii/firefly-iii#3352]
Hello JC5 - First of all, thanks a lot for writing such a nice tool and making it available for the world! FireflyIII is the reason why I started to deal with XAMPP and aiming for running it on a Raspberry Pi :) Now I come to a feature request:

**Description**
Usually "Shared Accounts" are used to cover common expenses/revenues between multiple person.
Therefore, all expenses I track in this Account would be "overrepresented" in all reports and overviews. At the moment it seems that a "Shared Account" is nothing different than a normal "Asset Account".

**Solution**
Considering Expenses/Revenues on "Shared Accounts" only as a Share in Dashboard/Reports/Overviews by:
- Adding a share ratio for each "Shared Account"
- All reports where I select these Accounts to be considered also consider this "share Ratio" and devide the current balance as well as the expenses and revenues by this "Share Ratio".

**What are alternatives?**
Currently, the only alternative solution is to consider half of the ammount on the bills for every transaction of this account... Which is unhandy and with a high probability of errors.

**Additional context**
- For a two-person-household, the share ratio would be two, so all balances, expenses and revenues would be devided by 2, which means in my dashboard "my" share of the expenses would be 50%.
- For a flat community account of 5 people, the respective share ratio would be 5 and so on...
- As an alternative to the share ratio (which would represent the number of equivalent persons), also a percentage number could be chosen (2-Persons = 50%, 5 persons = 20%) which would offer to choose an unequal distribution (e.g. 2 persons = 40% for a 40/60% distribution).

**Bonus points**
Maybe a short list of where this share ratio should be considered:
- Dashboard view
- Reports (e.g. for Accounts or Categories) 
In the transaction view, it obviously makes sense to enter the actual value of the bill for easy tracking.

**Comment by JC5** [comment]
Hi, thanks for the compliments. What you're proposing is way too complex and isn't going to be added.

It shouldn't matter what part of the shared expenses is your. After all, once you transferred your part to the shared account that money is gone. That's the money you want to track. This already happens when you exclude the shared account from your report. Any money transferred to the shared account counts as an expense.

**Comment by Basta911** [comment]
Hi James,
awesome resposne time! :)

I partially agree with you, but I guess most people not only use software such as Firefly 3 to track their accounts balance ("how much"), but also to geet an overview of the expenditure categories ("for what"). And here my proposal is of some relevance. In most cases, multiple different expenses such as monthly rent, cable TV, Internet or common insurances are paid by this shared account. Although you are right, the money is "gone", there are different categories affected.
For the personal financial situation, I still would like to see "my share" of the expenses in the individual categories rather than just one big bunch.

Fort the account balance, you are absolutely right - I just do not consider the account. But for the category overview, it is highly relevant. 

If you see some value in this, I am more than happy to help with a more precise idea of how this could be implemented (without huge effort?)...
