### ISSUE TITLE
Reports: Default Financial Report: Sorting "Bills" table by "Expected on" performs an alphanumeric sort not a date sort

### ISSUE THREAD

**Issue by srpnor** [firefly-iii/firefly-iii#3354]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:

In the default financial report, if you sort the "Bills" table by clicking on the "Expected on" column header, the sort is alphanumeric by locale textual representation of a date rather than a date sort.  e.g.:

May 1, 2020
May 27, 2020    <--- This should come after May 3 really, but alphanumerically it comes before
May 3, 2020

**Steps to reproduce**
Run the default financial report on any account.  Go to the "Bills" table of the report and click on the "Expected on" header to sort the table.

**Extra info**
Client: Windows 10 64bit, Chrome Version 81.0.4044.138 (Official Build) (64-bit)
Server: Ubuntu 18.04.4 LTS Linux 4.15.0-96-generic x86_64, manual install

Debug page:
Debug information generated at 2020-05-12 17:30:39 Europe/London for Firefly III version **5.2.5**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.5 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.4.5 |
| Display errors | Off |
| Session start | 2020-05-01 00:00:00 |
| Session end | 2020-05-31 23:59:59 |
| Session first | 2020-04-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 |

**Comment by JC5** [comment]
That's a tricky one. You could have multiple date on which the bill is expected. I'll try to use the first one. :+1:

**Comment by JC5** [comment]
This will be fixed in the next release :+1:

**Comment by srpnor** [comment]
Fantastic speedy fix, thanks James. 👍
