### ISSUE TITLE
Dashboard with multiple currencies

### ISSUE THREAD

**Issue by ashomah** [firefly-iii/firefly-iii#3355]
I am running Firefly III version 5.2.3.

**Description**
Hi, I'm starting using Firefly, having accounts in different currencies. As some of these currencies value 10x the others (1000 HKD = 100 EUR, for instance), the Dashboard chart doesn't provide a relevant insight. Indeed, the lines of the accounts with high exchange rates are 'shrinking' the other lines, even if they represent an equivalent amount in base currency. Shouldn't we be to convert the amounts to the same currency, for reporting purpose? Thanks!

<img width="959" alt="image" src="https://user-images.githubusercontent.com/29456225/81728612-0a284e00-948b-11ea-8e58-6c103b6817d1.png">

**Comment by JC5** [comment]
Sorry, this is what it is.
