### ISSUE TITLE
Does the rule triggers applies to split transactions groups?

### ISSUE THREAD

**Issue by lguima** [firefly-iii/firefly-iii#3356]
I am running Firefly III version 5.2.5.

**Description**
Does the rule triggers applies to split transactions groups?

By "group" I mean the description and value that summarize the split transactions.

For example in Demo site, there is the split transaction "[Equally triple split withdrawal](https://demo.firefly-iii.org/transactions/show/1)".

None of the triggers related to the "Description" matches to the group description ("Equally triple split withdrawal").

Is that expected?

**Bonus points**
- I have read the FAQ at https://bit.ly/FF3-FAQ
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Like you noticed, rules will apply to the splits only. This is expected. In theory it's possible of course but it only makes things unnecessarily complicated.
