### ISSUE TITLE
Allow disabling a personal access token without deleting it

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3357]
Hi,
I'm currently running the csv-importer (1.0.7) with fireflyiii (5.2.5) inline with in the same docker-compose conf file.

This means that, whenever the stack get started the importer is freely available to the mapped port, which is not really a nice to have :) I did not find a way to prevent starting the importer, AFAIK.

Since I believe that adding web authentication in front of csv-importer is an overkill, would it be possible to gice the option to toggle a personal access token instead of forcing its deletion, thus allowing turning on/off the importer?

Something like this:
<img width="745" alt="Screenshot 2020-05-13 at 10 12 58" src="https://user-images.githubusercontent.com/115389/81788154-5f537680-9502-11ea-8ea0-0c1e74b4b855.png">

Thanks

**Comment by JC5** [comment]
The token management is a plugin for Laravel which unfortunately, does not support this. If you're using a reverse proxy you set this up in the config of the reverse proxy, perhaps?

**Comment by psychowood** [comment]
I was thinking about a separate table for the flags, that could be checked in VerifiesAccessToken.php 

Otherwise, if you can access/edit the token table, perhaps a disabled token could be moved to a separate table?

My php is more than rusty, but if you can direct me to the files I could try to draft a PR...

**Comment by JC5** [comment]
I'm sorry, but this is not something I want to build into Firefly III. You could separate the CSV importer from the docker-compose file you built, and give them the same network. That way, they won't start both at the same time but will still be able to reach eachother.

**Comment by psychowood** [comment]
I suppose it makes sense. :)

Thanks for the support!
