### ISSUE TITLE
There was a fatal error.  Please check the log files....

### ISSUE THREAD

**Issue by bigverm23** [firefly-iii/firefly-iii#3359]
attempting to install this via docker-compose, with Traefik as reverse-proxy:

mariadb:
    image: mariadb
    restart: always
    container_name: firefly_db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024 --innodb-rollback-on-timeout=ON --innodb-lock-wait-timeout=120
    volumes:
      - $USERDIR/docker/firefly_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: firefly
      MYSQL_PASSWORD: xxxxxxxxxxxx
      MYSQL_DATABASE: firefly
    networks:
      - t2_proxy

redis:
   redis:
    container_name: redis
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes
    networks:
      - t2_proxy
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: '65535'
    volumes:
      - $USERDIR/docker/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

firefly:
 firefly:
    container_name: firefly
    image: jc5x/firefly-iii:latest
    restart: always
    networks:
      - t2_proxy
    ports:
      - "8500:80"
    volumes:
      - $USERDIR/docker/firefly/export:/var/www/firefly-iii/storage/export
      - $USERDIR/docker/firefly/upload:/var/www/firefly-iii/storage/upload
    environment: # https://raw.githubusercontent.com/firefly-iii/firefly-iii/master/.env.example
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=$MYSQL_PASSWORD
      - APP_KEY=$FIREFLY_APP_KEY
      - APP_ENV=local
      - APP_LOG_LEVEL=info # debug, info, notice, warning, error, critical, alert, emergency
      - APP_URL=https://firefly.$DOMAINNAME
      - TRUSTED_PROXIES=**
      - SITE_OWNER=$MY_EMAIL
      - TZ=$TZ
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_DB="0"
      - REDIS_CACHE_DB="1"
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_FROM=$MY_EMAIL
      - MAIL_USERNAME=$SMTP_EMAIL
      - MAIL_PASSWORD=$SMTP_PASS
      - MAIL_ENCRYPTION=tls
      - CER_PROVIDER=ratesapi
      - SEND_TELEMETRY=false
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.firefly-rtr.entrypoints=https"
      - "traefik.http.routers.firefly-rtr.rule=Host(`firefly.$DOMAINNAME`)"
      - "traefik.http.routers.firefly-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.firefly-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.firefly-rtr.service=firefly-svc"
      - "traefik.http.services.firefly-svc.loadbalancer.server.port=80"

log error:
` local.ERROR: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select `id`, `name`, `data` from `configuration` where `name` = installation_id and `configuration`.`deleted_at` is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select `id`, `name`, `data` from `configuration` where `name` = installation_id and `configuration`.`deleted_at` is null limit 1) at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)`

**Comment by bigverm23** [comment]
more logs:

today at 5:43 PM In Connection.php line 669:
today at 5:43 PM
today at 5:43 PM SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o
today at 5:43 PM r service not known (SQL: select * from `configuration` where `name` = db_v
today at 5:43 PM ersion and `configuration`.`deleted_at` is null limit 1)
today at 5:43 PM
today at 5:43 PM
today at 5:43 PM In PDOConnection.php line 31:
today at 5:43 PM
today at 5:43 PM SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o
today at 5:43 PM r service not known
today at 5:43 PM
today at 5:43 PM
today at 5:43 PM In PDOConnection.php line 27:
today at 5:43 PM
today at 5:43 PM SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o
today at 5:43 PM r service not known
today at 5:43 PM
today at 5:43 PM
today at 5:43 PM In PDOConnection.php line 27:
today at 5:43 PM
today at 5:43 PM PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or s
today at 5:43 PM ervice not known
today at 5:43 PM
today at 5:43 PM
today at 5:43 PM Application cache cleared!
today at 5:43 PM Configuration cache cleared!
today at 5:43 PM Configuration cached successfully!
today at 5:43 PM Run chown on /var/www/firefly-iii/storage
today at 5:43 PM +------------------------------------------------------------------------------+
today at 5:43 PM |                                                                              |
today at 5:43 PM | Thank you for installing Firefly III, v5.2.5!                                |
today at 5:43 PM |                                                                              |
today at 5:43 PM |                                                                              |
today at 5:43 PM +------------------------------------------------------------------------------+
today at 5:43 PM Go!
today at 5:43 PM AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.5. Set the 'ServerName' directive globally to suppress this message
today at 5:43 PM AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.5. Set the 'ServerName' directive globally to suppress this message
today at 5:43 PM [Wed May 13 17:43:01.188765 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.17 OpenSSL/1.1.1d configured -- resuming normal operations
today at 5:43 PM [Wed May 13 17:43:01.188798 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

**Comment by JC5** [comment]
` - DB_HOST=mariadb`

This should probably be "firefly_db" because that's what you called your DB container.
