### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by xando3000** [firefly-iii/firefly-iii#3360]
**Bug description**
I am running Firefly III version 5.2.4, and my problem is:

file_put_contents(/var/www/vhosts/xxxxxxxxxx/httpdocs/firefly-iii/storage/framework/cache/data/03/2e/032e5f4ee4d42b9f046901810c27202d45043d2a)

![error firefly](https://user-images.githubusercontent.com/65373109/81994601-96b74580-961e-11ea-8cf7-d0a72a2c1e16.jpg)

**Steps to reproduce**
Menu-> Options-> Profile 

**Extra info**

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue+%22no+such+file+or+directory%22
