### ISSUE TITLE
Improved mobile experience (via basic PWA)

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3362]
Hey there! First off, I really love using Firefly III, on my desktop PC and on my phone as well.

However, there is one is issue with the design of the application when it comes to mobile friendlyness (at least to my mind): 

_Disclaimer:_ I am not very familiar with the project's architecture or PHP/web design in general. Therefore I can't estimate the effort the implementation of my request would require. However, I think it would be a great step towards improved mobile friendlyness! :smile:

**Description**

**Scenario**: I just **went to the supermarket** and want to **add the bill to my Firefly account**.

How will I do that? I open up Chrome, visit my Firefly instance (self hosted behind reverse proxy) and click this little plus icon in the upper right corner. Then I have to select "new expense" and fill in all the details, scroll to the bottom and click "submit". To my mind, that's a little uncomfortable and could be fixed. (**TL;DR: The mobile site is way too complicated to use and cosumes too much time to peform very basic tasks.**)

**Solution**

I already know that a **complete PWA support is not possible** (as discussed in #2845 ) without rewriting the whole project. However, how about **dropping the offline support** and only **implementing one or two extra pages exclusively for mobile users**?

I'm thinking about some kind of **"quick add button"** which you can **add to the home screen**. When accessed, a more mobile-friendly UI will open and **you can input your expenses directly**. 

This UI could be **accessed via "firefly.example.com/pwa"** (which would be defined as the `start url` of the app while the `scope` remains at / ) and you could access the standard UI by clicking a button in the title bar.

**What are alternatives?**

You could simply add a chrome link to your home screen. However, as **PWAs add more customizability** (splash screen, standalone mode, display a page that the website is offline, cache static resource via service worker, start urls and mobile-specific sites), they are a much more user-friendly solution.

Keep up the great work and thanks for such an amazing open-source finance manager!

Best wishes,
Niklas

**Comment by JC5** [comment]
Thanks for the suggestion! A new layout is actually still on my list some early attempts are already committed to another branch of Firefly III. It's difficult to make something that works for everybody.

Right now, I'm focussing on the API as the go-to for any new development. Firefly III has had a lot of duplicate code (just look at the CSV importer) which is something I want to get rid of. For example, there used to be 6 different ways to store a transaction:

1. The user interface
2. The API
3. The CSV importer
4. The bunq importer
5. The Spectre importer
6. The YNAB importer.

They would all have their own little quircks and bugs. Right now, this has been brought back to one method which is used by all: the API. So whatever you do, the API does the work. That saves me so much time and effort, it's insane.

In the same light, I don't want to add special forms for mobile devices or PWA's. It's got to be a single point of entry. That means it could be less optimal for mobile devices or it may work terribly on your tablet. That's a thing I can fix. But I'm not going to add a *second* form to fix something that's broken on the *first* form.

I'll pick it up as an improvement and see what I can do. But it's not going to be a second form I'm afraid.

**Comment by niklas2810** [comment]
Sound's great! I understand why you are not going to implement a separate form; maybe a cleanup of some parts of UI would already help 😄 Thanks for such amazing open source software!

**Comment by JC5** [comment]
A new layout is on my list. It should improve matters. I'll let the bot pick this one up.
