### ISSUE TITLE
Hardcoded text message - not translatable

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3363]
https://github.com/firefly-iii/firefly-iii/blob/4dea3a5f55d9b971d02db7260349bdac0148524a/resources/assets/js/components/transactions/CreateTransaction.vue#L478

I'd really like to fix this one myself. Give me the weekend to get my head around setting up an IDE for PHP. It's not the first time I've wanted to do it, maybe I won't procrastinate this time.

**Comment by JC5** [comment]
Sure thing, I won't touch a thing! 

Would you like me to give some pointers?

**Comment by sephrat** [comment]
I think I mostly need pointers as to how to build and test the project on Windows rather than on how to fix the issue. It's far out of Firefly III scope though, I'll make my own research this weekend. So far I've cloned the repo in Atom and supposedly fixed the issue. Now trying to test, but I need to find out how dependencies work. Bear with me!

**Comment by JC5** [comment]
I'm not sure how that would work 😅 . I use "yarn" on a Mac which uses node and all those other tools. Just not sure how that works on Windows.

**Comment by sephrat** [comment]
Thanks for pointing out yarn, that was the last tool missing for me to build the .js files from the .vue ones. 
Yay, I did it!

**Comment by JC5** [comment]
:+1: marking this as fixed.
