### ISSUE TITLE
CSV Importer (Docker): Pre-uploaded configuration files not showing in web

### ISSUE THREAD

**Issue by MadWalnut** [firefly-iii/firefly-iii#3364]
I updated to the new CSV importer v1.0.8 which supports pre-uploaded configuration files. I am trying to get this to work in my Windows Docker container. I use the [run-hosted.sh](https://github.com/firefly-iii/csv-importer-docker/blob/master/run-hosted.sh) script from the documentation. I modified it, so now my bottom part looks like this: 

```
docker run \
--rm \
-v C:/PATH/csv-importer-live:/configurations \
-e FIREFLY_III_ACCESS_TOKEN=$PERSONAL_ACCESS_TOKEN \
-e FIREFLY_III_URI=$FIREFLY_III_URI \
-e JSON_CONFIGURATION_DIR=/configurations \
-p 8081:80 \
fireflyiii/csv-importer:develop
```

I can see the JSON files from my mounted folder when I do:
```
docker exec -it CONTAINER-ID bash
ls /configurations/
```

So the mounting part should be working. I just don't see the option to select the files when I open the CSV importer in any browser:
![Screenshot_27](https://user-images.githubusercontent.com/33835479/82100571-3ac9eb00-970a-11ea-9e7a-e3b48d60078b.png)

What am I missing?

**Comment by JC5** [comment]
Mmm, not sure. This is exactly what I had in mind. When I test this locally, it works (on a Mac though).

I've added some debug code to the latest `develop` build. Could you check it out and let me know? It should say something like this when you refresh that page:

```
production.DEBUG: Going to check directory for config files: /configurations
production.DEBUG: List of files: [".DS_Store","000-commandline.txt","000-very-basic.csv", ....
```

Let me know!

**Comment by MadWalnut** [comment]
The debug text is not appearing for me. You mean the page I posted a screenshot above, right? Nothing appears when refreshing.
```
>> docker pull fireflyiii/csv-importer:develop
develop: Pulling from fireflyiii/csv-importer
Digest: sha256:69215830717f1ba4889e7ba40dd40b87d150ebdf31df5ffb6d01b8893925f97a
Status: Image is up to date for fireflyiii/csv-importer:develop
docker.io/fireflyiii/csv-importer:develop
```

**Comment by JC5** [comment]
I just pushed a new build, just in case. This is the last `develop` build:

https://hub.docker.com/repository/docker/fireflyiii/csv-importer/tags?page=1&name=develop

When I pull it, I get:

```
Digest: sha256:9000fd4b59fbf012b3e1c89afc396fe8c32ea3bef8be978669d81d510e1f9b9e
Status: Downloaded newer image for fireflyiii/csv-importer:develop
docker.io/fireflyiii/csv-importer:develop
```

This matches the SHA2 hash from [the build](https://travis-ci.com/github/firefly-iii/csv-importer-docker/jobs/333580570).

Created manifest list docker.io/fireflyiii/csv-importer:develop

```
sha256:9000fd4b59fbf012b3e1c89afc396fe8c32ea3bef8be978669d81d510e1f9b9e
Done managing version 'develop'. Will now exit.
```

**Comment by MadWalnut** [comment]
Weird, with that new build I'm getting the debug text although the first time Docker said it was up-to-date too (didn't check hash though). Anyway, this is my output:
```
[2020-05-16 18:45:02] production.DEBUG: Going to check directory for config files: C:/Program Files/Git/configurations
[2020-05-16 18:45:02] production.DEBUG: List of files:
```
No idea why it's trying to access _C:/Program Files/Git_. Can't think of anywhere where I would have specified that path. I do have git installed though. I guess it's weird seeing a Windows path here in first place when it should just be Unix style _/configurations/_.

Hope that makes more sense to you than me.

**Comment by JC5** [comment]
It doesn’t, sorry. I don’t use windows.
