### ISSUE TITLE
Additional attachments causes table view errors.

### ISSUE THREAD

**Issue by linkyone** [firefly-iii/firefly-iii#3367]
Firefly III version 5.2.5. Problem is when a second attachment is added to a transaction, the transaction table view shows an additional line and removes the `<a>` tag from the category name.

**Steps to reproduce**
- Create a transaction, attach two attachments or
- Create a transaction, add a single attachment, then edit and add another.

**Extra info**
Running on FreeBSD 12, Nginx, PHP74, Chrome 81.0.4044

**Bonus points**
- Searched through existing issues.
- Tried on the demo site - couldn't get a sample pdf file to upload.
- Here's what it looks like in my browser:
Multiple attachments:
![Screenshot_20200517_101817](https://user-images.githubusercontent.com/10637466/82135386-3c480000-983d-11ea-90d9-d2826880413b.png)
Single attachment:
![Screenshot_20200517_101845](https://user-images.githubusercontent.com/10637466/82135388-3d792d00-983d-11ea-980b-e4986b9694ed.png)

**Comment by JC5** [comment]
Nice find! I fixed this for the next release. Caused by a bad counter.
