### ISSUE TITLE
Transfer Hover Text says "Deposit"

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3368]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is: when you hover over the transfer icon, the text displayed is deposit instead of transfer. This is misleading, especially when you look at it from the source account.

**Steps to reproduce**
1. Find a transfer transaction on either the transfers screen or an account page.
2. Hover over the icon.

**Screenshot**
![Screenshot from 2020-05-17 12-32-52](https://user-images.githubusercontent.com/21091510/82154268-a27f5380-983a-11ea-9394-5a05c45c642e.png)
(The screenshot admittedly does not show the hover text)

**Bonus points**

I searched and nobody reported this bug before
I have added a screenshot.
I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for reporting. I’ll pick it up for the next release :)
