### ISSUE TITLE
Chart currency invalid values

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#3369]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:
I bought 3 items from one account in dollars ($). I put the local currency (PLN) I paid for. It seems on the chart the amount is calculated incorrectly. Also the last payment was done today and I don't see it on the chart.

**Steps to reproduce**
Register payment using foreign amount.

![obraz](https://user-images.githubusercontent.com/4746858/82158102-0844fd00-9886-11ea-8a9b-c00e5a2cf60f.png)
![obraz](https://user-images.githubusercontent.com/4746858/82158106-0c711a80-9886-11ea-94e2-7a9641fd62c0.png)

**Comment by JC5** [comment]
Mmm, in a basic test I can't reproduce this. The charts get updated just fine. I make an expense in EUR (20) + Canadian dollar (30).

- /transactions/withdrawal is correct, showing only the EUR amount in the pie charts.
- Asset account chart /accounts/show/x/all and /accounts/show/x are both correctly dropping 20 EUR.
- Expense account /accounts/show/x correctly shows 2 increases, on in EUR and one in CAD.

Basic question, try browsing to `/flush` to clear your cache.

**Comment by skibbipl** [comment]
Flushing cache was the first thing I did, but without luck. I'm puzzled why on charts I can see 2 lines? And to be more precise - the first two transactions from 2018 were registered in PLN only, as back it time there were no possibility to add foreign amount. I updated them yesterday.

**Comment by JC5** [comment]
Alright. Expense accounts have x lines, for all currencies involved. Asset accounts only have the one for their set currency.

Which charts am I looking at exactly?

**Comment by skibbipl** [comment]
`/accounts/show/XXX`

**Comment by JC5** [comment]
Alright, some more debugging shows no problems on my end. I've been playing around with some amount combinations but nothing so far.

- What's the currency of the asset account you pay from? USD, I presume?
- Your default currency is PLN?

And let's see if the transaction is somehow filled incorrectly in the DB. Try these queries:

`X` is to be replaced with the number from the URL for one the multi-currency transactions.

```sql
select id,transaction_group_id, transaction_currency_id from transaction_journals where transaction_group_id = X;
```

And this one:

```sql
select transactions.id, transactions.transaction_journal_id, transaction_journals.transaction_group_id,transactions.account_id, transactions.amount,
transactions.transaction_currency_id, transactions.foreign_amount, transactions.foreign_currency_id
  from transactions
left join transaction_journals ON transactions.transaction_journal_id= transaction_journals.id
where transaction_journals.transaction_group_id = X;

```

**Comment by skibbipl** [comment]
Ad.1: Source account is PLN
Ad.2: My default currency is PLN
```
id | transaction_group_id | transaction_currency_id
2792 | 2640 | 7
```
```
id | transaction_journal_id | transaction_group_id | account_id | amount | transaction_currency_id | foreign_amount | foreign_currency_id
6411 | 2792 | 2640 | 7 | -106.1000 | 7 | -24.990000000000 | 2
6412 | 2792 | 2640 | 261 | 106.1000 | 7 | 24.990000000000 | 2
```

**Comment by skibbipl** [comment]
I replicated the issue on demo site:
https://demo.firefly-iii.org/accounts/show/71

**Comment by JC5** [comment]
I see it. The US dollar is the default currency. That explains part of it.

**Comment by JC5** [comment]
Alright so here's what I think is happening. This applies to the expense account.

Expense accounts generally don't have a currency linked to them so the chart (on page /accounts/show/x) will use whatever currency is the user's default at that moment. In this example, it's the New Zealand dollar.

<img width="791" alt="Screenshot 2020-05-24 at 16 50 17" src="https://user-images.githubusercontent.com/5889984/82757126-ea1f5580-9dcd-11ea-8e6f-3a29c0335967.png">

If the transaction for the account don't match this currency, the chart's axes will display NZ$ while the hover box will display the currencies in the transactions, like so:

<img width="278" alt="Screenshot 2020-05-24 at 16 52 28" src="https://user-images.githubusercontent.com/5889984/82757169-34a0d200-9dce-11ea-92ec-8e2edb4f7d4c.png">

This is a side-effect of the ability for expense accounts to have transactions associated with them that are not in any currency relevant to them (ie. not the user's default, not the account's default, just all "foreign").

There's not much I can do I'm afraid. Focus on your asset accounts, those should at least be correct.
