### ISSUE TITLE
Rollover budget not working

### ISSUE THREAD

**Issue by carsonbird** [firefly-iii/firefly-iii#3370]
I can't seem to get the automatic rollover budget feature to work. On one of my budget items, I have it set to "add an amount every period". It doesn't seem to do this though. Every budget period (monthly, for me), it just resets the amount for that budget back to zero. I am running on Heroku. Let me know if you need more information, I'm happy to provide it.

**Comment by JC5** [comment]
Do you have the cronjob enabled? What are the log files?

**Comment by carsonbird** [comment]
Hey man! Thanks for the quick reply, that's awesome of you.

For the cronjob, I am having another server cURL the heroku instance every 3 hours... And now that I write that out, I realize that the issue could very well be the fact that the cURL likely fails because the Heroku app hibernates after 30 minutes of inactivity, so the cronjob call usually hits a hibernating server and never gets through. The server wakes up when the cronjob runs, but by that point, it's already failed. Maybe?

Which logs are you looking for?

**Comment by JC5** [comment]
If the cron works, I need no logs :)
