### ISSUE TITLE
How to use ratesapi currency rates in user interface?

### ISSUE THREAD

**Issue by dmigis** [firefly-iii/firefly-iii#3371]
I am running Firefly III version 5.2.5

**Description**
Hello everyone! Thanks for beatiful personal finances manager. It is quite useful, but I didn't understand one moment: as I understood, it is possible to fetch currency rates through ratesapi, but I didn't find out, how can I use this in user interface. Can you explain, how can I use this feature?
Thanks in beforehand

**Extra info**
Using Docker for Firefly deployment

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by JC5** [comment]
There is no part of the user interface that currently uses currency exchange rates.
