### ISSUE TITLE
Wrong help text for skips on bills?

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3373]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:

THe help text (with the question mark on top) shows: If you enter a number in the "skip" fields, the bill will be automatically skipped every X times; a bill that arrives every 3 months can be entered by filling in "3".

However, if you enter 3, it will skip every 3 months, so that's for a bill that arrives every 4 months. So I think either the help text needs to be updated so it says: enter 2 in skips. Or the logic needs to be changed somehow. But the logic seems ok if the word "Skips" is used.

**Steps to reproduce**
Enter a bill, enter start date the first of this month, monthly bill and enter 3 in the skips filled. The next bill will be in 4 months then.

**Extra info**

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nice find. I updated the documentation.
