### ISSUE TITLE
Multiple rule cloning does not update priority collrectly

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3376]
I am running Firefly III version 5.2.5, and while loading a bunch of new rules, I'm doing massive cloning to update only the different values between them.

I noticed that the cloned rules seems to copy the priority from the original one, without updating/recalculating the values.

It is a minor issue but when you try to reorder one of the new rules it causes a little bit of a mess in the complete list.

**Steps to reproduce**
Clone a rule multiple times:
- if it was the first or the last one, you'll see multiple rules with only the "up" or "down" button available
- change the title of some of the new rules (to be able to differentiate them instead of having the very same title)
- as soon as you try to reorder one of the new rules, the list get messed up (at least, it seems so)

I was able to replicate it on the demo site https://demo.firefly-iii.org/

Thanks
<img width="358" alt="Screenshot 2020-05-19 at 09 15 03" src="https://user-images.githubusercontent.com/115389/82296804-08dab200-99b2-11ea-8521-532825c7cac5.png">

**Comment by JC5** [comment]
Ah, nice. I completely forgot that. Will be fixed! :+1:
