### ISSUE TITLE
CSV Importer File size limit?

### ISSUE THREAD

**Issue by carroarmato0** [firefly-iii/firefly-iii#3377]
**Bug description**
I am running Firefly III version 5.2.5, csv-importer: 1.0.9 and my problem is:

When I upload a CSV file which is 3.8MB big I can't get passed the inital screen for inputing the CSV file and an optional Config file.

A red "1" appears under the File form.

In the logs nothing spectacular is happening:
```
[2020-05-20 20:30:20] production.DEBUG: Now at App\Http\Controllers\Import\StartController::index  
[2020-05-20 20:30:20] production.DEBUG: Going to check directory for config files: /var/www/html/storage/configurations  
[2020-05-20 20:30:20] production.DEBUG: List of files: [".gitignore"] 
192.168.50.130 - - [20/May/2020:20:30:20 +0000] "GET /import/start HTTP/1.1" 200 2200 "http://firefly-importer.lan/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
[2020-05-20 20:30:26] production.DEBUG: Now at App\Http\Controllers\Import\UploadController::upload  
192.168.50.130 - - [20/May/2020:20:30:26 +0000] "POST /import/upload HTTP/1.1" 302 1437 "http://firefly-importer.lan/import/start" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
[2020-05-20 20:30:26] production.DEBUG: Now at App\Http\Controllers\Import\StartController::index  
[2020-05-20 20:30:26] production.DEBUG: Going to check directory for config files: /var/www/html/storage/configurations  
[2020-05-20 20:30:26] production.DEBUG: List of files: [".gitignore"] 
192.168.50.130 - - [20/May/2020:20:30:26 +0000] "GET /import/start HTTP/1.1" 200 2231 "http://firefly-importer.lan/import/start" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
```

**Steps to reproduce**
Upload a valid CSV file which is bigger than 2.0 MB

**Comment by JC5** [comment]
Yes, thanks for letting me know! I knew there was a limit of 2MB, it's the default PHP setting. I didn't know it would just say "1".

I can fix this, even in the 1.0.9 Docker image, which I assume you're using. But keep in mind that processing large files is something that you should do over the command line instead. This prevents timeouts and other potential issues.

But enough of me; stay tuned for a fix.

**Comment by JC5** [comment]
1.0.9 and the develop branch are now rebuilding. Downloading the latest image should solve the issue.

**Comment by carroarmato0** [comment]
Thanks @JC5! Turns out that my whole financial life so far fits in a csv file of less than 4MB. I split the CSV file in 2 to do the initial import in Firefly, but thanks for the tip.

**Comment by carroarmato0** [comment]
@JC5 I have to deal with some stupidity in my CSV where the opposing IBAN account is in the description, but not filled in into the appropriate column, so will redo the import and try out the new version and let you know if the enhancement works.

**Comment by carroarmato0** [comment]
Works!
