### ISSUE TITLE
Credit Card Statement Dates

### ISSUE THREAD

**Issue by rafny** [firefly-iii/firefly-iii#3379]
**Considerations:**
- I have a credit card with regular monthly expenses (subscriptions, internet, cellphone, etc) that adds up to a fixed amount every month (pretend it is $250).
- I also use the card of ad hoc expenses like a coffee, grocery store, misc purchases that aren't reoccurring. These charges are on top of the $250 expected every month.
- I always pay my credit card statement balance in full, leaving any new transactions that came up after the statement close date to be paid in the next statement.
- In Firefly-III, I add each transaction manually to the CC account, and associate the reoccurring ones with a Budget and Bill
- At any given time, my CC Account balance in FF is a negative number that represents my current balance. Also the Bills and Budget are tracking current and upcoming transactions.

**Feature Request:**
Some way to show my full CC balance and the statement balance separately. So it may show a current balance of $530, but a statement due balance of $400. 
Perhaps this can be done by assigning statement dates to accounts (ie: statement closes on the 18th of every month). And these transactions can be grouped based on their date and source account statement date.
And after the statement date closes, it can auto generate a bill with that amount and account assigned due date.

Not sure if this is compatible with where FF is heading, but just wanted to throw out the idea.

**Comment by JC5** [comment]
I see what you mean. I usually just "wing it". I know how much it should be and I create a piggy bank with some extra just in case. Let me think about it.

**Comment by JC5** [comment]
There's not a really easy way to make this happen, I'm afraid. All I can suggest is that you assign your CC expenses a tag, like `18 October 2020`, and select the tag to see what's due.
