### ISSUE TITLE
[Question ] Handling of payment providers when importing transactions

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#3380]
I am running Firefly III version 5.2.5 and the csv-importer version 1.0.9

**Description**
I imported some transactions which have been handled by an payment provider such as Buckaroo or Adyen. This transaction created an expense account with the name of the payment provider and IBAN number.

This is of course logical but not really desired for my administration.  In this case I need the name of the real web shop as the name of an expense account instead.  In most cases is the name of the real shop mentioned at the start of the description 

I was thinking to create some rules to create separate expense accounts so I could prevent transaction from multiple web shops ending up in a general account held by the payment provider.

But maybe there is an better solutions to handle this?

Thanks in advance

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Most people use rules, and I know Dutch banks are working on improvements to show the destination webshop instead of the provider. Other than that, there's not much that can be done, I believe.
