### ISSUE TITLE
Sign of transfer from savings account

### ISSUE THREAD

**Issue by McOrion** [firefly-iii/firefly-iii#3382]
**Bug description**
I am running Firefly III version 5.2.5. and my problem is: 

When making a transfer, initiated from the checking account on the dashboard, from the savings account to the checking account, the sign of the transfer is positive (green), both on the checkings account as on the savings account. I expected a positive (green) sign on the checking account, as the money is added there, but I expected a negative (red) sign on the savings account, as the money is withdrawn from this account.

**Steps to reproduce**
On the dashboard, create new transfer from the checking account. 

**Extra info**
It's also working like this on the demo website. See transaction "withdraw money from savings" of $ 256,-

**Bonus points**

- I searched and nobody reported this bug before---YES
- I have added a stack trace from my log files---NO
- I have added a screenshot.---YES
![Knipsel](https://user-images.githubusercontent.com/59847229/82701627-d3afb780-9c70-11ea-8403-a9669fd65e11.PNG)

- I was able to replicate it on the demo site https://demo.firefly-iii.org/ ---YES

**Comment by JC5** [comment]
Indeed. This is on purpose. Transfers are blue and positive on both ends.

**Comment by McOrion** [comment]
At least it works as designed ;-)

Looking close to my screen, I agree with you on the blue color. Although I'm not aware of having difficulties seeing colors, I didn't noticed the blue color earlier. That would be OK for me, as it makes clear the transaction is a transfer.

On my personal savings account I'm only able to transfer money in and out from my checkings account. So all transactions have the blue color and have a positive sign. That makes it difficult to see which transaction adds to the account and which do not. It would be great to have a sign, but a workaround would mean adding some keyword in the description.

**Comment by JC5** [comment]
Sometimes you have to sacrifice stuff to solve it. I dumped the "grouped" view, making the code a lot simpler.

The view (.twig) is a lot more complex, granted, but this works fine. Fixed in the next release.

All credits to @sephrat for fixing the hard part!
