### ISSUE TITLE
Personal access token invalidated after docker restart

### ISSUE THREAD

**Issue by Nyxelio** [firefly-iii/firefly-iii#3386]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:

Personal access token (under Profile) seems to be invalidated across docker restart. On UI, token label is still visible, but docker csv importer fails on a Unauthorized. Deleting and replacing with a fresh token works, until next firefly container restart. 

Docker image: firefly-iii:develop

**Bonus points**
I saw a fix which restore OAuth keys, not sure this is related

**Comment by JC5** [comment]
Yes, I know. Unfortunately, this is an issue with the underlying framework. I have no fix yet.

**Comment by Nyxelio** [comment]
Oh okay, thanks for your help. And big thanks for F3, you did a great job !

**Comment by JC5** [comment]
I've been playing with this. As long as the DB is intact I don't have this problem, personally. 

The very first time the container starts, the logs should report this (`docker logs -f 0000`):

```
Generated and stored new keys.
```

After stopping / starting / removing the Firefly III container, the logs should say:

```
Restored OAuth keys from database.
```

And then the previously used Personal Access Token keeps working.

**Comment by krispek** [comment]
I have the same issue after upgrading Firefly. The logs report the following:
`Restored OAuth keys from database.`
`Generating new OAuth keys...`
`Encryption keys already exist. Use the --force option to overwrite them.`

Which forces me to update my Docker config.

**Comment by JC5** [comment]
So you manually ran the —force command?

**Comment by JC5** [comment]
Sorry, that was a short reply.

According to your logs, everything works as expected.

**Comment by krispek** [comment]
No, since I do not want to have them changed. Or should I, _because_ I don't want to have them changed?

**Comment by JC5** [comment]
No, it should be like this. This text: "Restored OAuth keys from database." indicates that the keys should have been restored correctly. 

You can test this using this command:
```
docker exec -it <container> cat /var/www/firefly-iii/storage/oauth-public.key
```
The result should be the same before and after a reboot.

**Comment by krispek** [comment]
OK, rebooting works indeed. :)

How about upgrading Firefly? This is where my key got invalidated.

**Comment by JC5** [comment]
Should also work, same code :)

**Comment by krispek** [comment]
Hmm, I upgraded this morning to the latest version and that did not work. Will check next time. :)
