### ISSUE TITLE
Email notifications cannot be translated

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3387]
I already reported this a few months ago in #3159 (item 6) and you said you wouldn't fix it.
Just wondering now the reason behind it? I thought it had to do with Twig templates not being easily translatable but I bumped into some twig files that are translatable.
Is it because it's too much work to do for little value to you (which I totally understand), or is there a technical issue behind it that I have overlooked?
In the former case, I'd like to give it a try if you don't mind. I'd start with the "Firefly III has created a new transaction" one. From what I see, for every email form I just need to change the related app/Mail/*.php file and the 2 associated twig files in firefly-iii/resources/views/v1/emails/, right? 
Are the -text.twig still used? I never saw an option to send plain text instead of HTML.

**Comment by JC5** [comment]
To answer your last question first: Firefly III includes both in all emails, so proper clients fall back to the text-only view.

Laravel changed somewhat in the meantime and they can be translated. Keep in mind though that emails are sent separately from the user's session. In other words, you can't be sure you can find the user and their preferred language easily, from the perspective of an email message. That's the reason their not translated.

And I don't want to spagetti the user management code to the email code. Unless this improved in Laravel in the meantime, but honestly I havent spent much time on it yet.

**Comment by sephrat** [comment]
How about we use default language for a start? Are there many Firefly III instances with users whose language differs from the default one? I can only think of people monetizing their Firefly III instance - is that a thing? And anyway if it were the case, those users would still have the login screen in the default language so they would already be used to it.

I'll play around with it and see what I come up with.

**Comment by JC5** [comment]
Yes, Firefly III features a lot of languages but most users don't change the environment variables to overrule the language for all users.
