### ISSUE TITLE
Typo in api docs?

### ISSUE THREAD

**Issue by bnw** [firefly-iii/firefly-iii#3389]
Hi, 
I think there is a small error in the api docs here: 
https://api-docs.firefly-iii.org/#/transactions/storeTransaction

If I understand it correctly, transactions.description should read
> Description of the transaction. Will only be used if **exactly one** split is submitted. 

instead of

> Description of the transaction. Will only be used if more than one split is submitted.

Maybe even add "Otherwise, group_title is used."?

Thanks :)

**Comment by JC5** [comment]
https://github.com/firefly-iii/api-docs-generator/blob/master/yaml/schemas/TransactionSplit.yaml#L48

I’ll pick it up tomorrow. Those descriptions aren’t perfect :)

**Comment by JC5** [comment]
Fixed!
