### ISSUE TITLE
Search for unique or External IDs?

### ISSUE THREAD

**Issue by clydefroggie** [firefly-iii/firefly-iii#3391]
As a new user of Firefly iii, I recently imported 2-months of transactions as test data to get familiar with the software. My compliments to the docs and Github pages, they are really helpful during this learning process - really well done!

From my understanding, "External ID" tag can be used to further prevent duplicates during import. For traceability reasons, can the External IDs also be used to search for particular transactions within Firefly?
Or is it possible to show the External IDs in the transaction overview table?

I can query for them in the database, but rather use the Firefly front-end if possible.

(I am running Firefly III version 5.2.5)

Many thanks in advance and keep up the good work!

**Comment by JC5** [comment]
Hey man, thanks for the compluments! This is a very good idea; currently they're not searchable. I'll have to build something to fix that but it won't be hard. They won't be visible in the list but using the search you should be able to find them pretty quickly.
