### ISSUE TITLE
Notes field not exported

### ISSUE THREAD

**Issue by gtothill** [firefly-iii/firefly-iii#3392]
I am running Firefly III version 5.2.5

**Description**
Notes field does not seem to be exported with other data. 

**Extra info**
No real error that I can see but I thought I would check that this is by design, simply because I have data in this field that would be helpful to have exported.

Lastly - thanks for great software. Its a great pleasure using it.

**Comment by JC5** [comment]
Indeed, I'll add them to the export!

**Comment by gtothill** [comment]
Sorry to have been slow to reply. Thanks for considering this - it would be helpful. Thanks again for the obvious passion you have for this and for such remarkable software.

**Comment by JC5** [comment]
Notes will be part of the export in the next release.
