### ISSUE TITLE
Unable to import to Liability account using CSV Importer

### ISSUE THREAD

**Issue by mukowman** [firefly-iii/firefly-iii#3396]
I am running Firefly III version 5.2.5.
I am running CSV Import version 1.0.9.

**Description**

When attempting to import a CSV using the new CSV importer tool I am unable to select my Liability accounts from the drop down box. I have a field within my CSV that has the account number (which matches my liability account number) but the imported transactions are associated with Cash Account. I have also tried to manually add the account ID to the import json file, but no difference.
I noticed this issue referenced with regards to the old import method, but nothing for the new one.
https://github.com/firefly-iii/firefly-iii/issues/2903

**Extra info**

| Variable | Content |
| --- | --- |
| FF version | 5.2.5 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| PHP version | 7.3.17 |
| Display errors | Off |
| Session start | 2011-12-16 00:00:00 |
| Session end | 2020-05-26 00:00:00 |
| Session first | 2011-12-16 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0 |

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ- Done
- I added a screenshot - NA
- I added log files - Will add log files if needed
- I was able to replicate the issue on the demo site. - NA

**Comment by JC5** [comment]
Yes that should be possible. I'll pick it up.

**Comment by JC5** [comment]
This is now fixed, version 1.0.12
