### ISSUE TITLE
Action Rule to delete transactions

### ISSUE THREAD

**Issue by mukowman** [firefly-iii/firefly-iii#3397]
**Description**
Currently FireFly doesn't have the ability to delete a transaction as an action from a rule.
In my situation I import a CSV from my asset account and then run a rule to convert the transaction to a transfer. I then run an import for my Home Loan account and will now have duplicate transactions, but with slightly different descriptions. Having the ability to specifically delete transactions I can trigger based on having a tag and being a credit in this account.

**Solution**
Add an action to delete a transaction within the rules

**What are alternatives?**
Currently I manually remove these lines from the CSV file.

**Comment by JC5** [comment]
Install the latest version and you're good to go.

https://github.com/firefly-iii/firefly-iii/releases/tag/5.2.6
