### ISSUE TITLE
Add a shortcut to /flush in administration

### ISSUE THREAD

**Issue by pedrom34** [firefly-iii/firefly-iii#3398]
Hey James,

It happens to me from time to time to have errors when accessing some pages, and it requires to clear php artisan cache to access it again.

I think it would be a good idea to add a link to /flush in the administration page.
Not a big improvment, not something I want really bad, but I suggest it anyway 😄

**Comment by JC5** [comment]
Sure thing, that's a good idea!

**Comment by JC5** [comment]
New release will have this button :+1:

**Comment by pedrom34** [comment]
😄  thanks
