### ISSUE TITLE
Database imported on new system, original user account not working

### ISSUE THREAD

**Issue by daprofessa19** [firefly-iii/firefly-iii#3401]
**Bug description**
I am running Firefly III version 5.0.5, and have imported the firefly database to a new machine. The import succeeded, and it looks like the tables have been created. But all of the data is associated to the original user account on the original machine. When I try to login with that account, I get "Error! These credentials do not match our records."

Using a secondary admin account (this account is coming from YunoHost SSO), I have reset the password for this account and gotten a success message. But even after password reset, I still get the same error message. 

**Steps to reproduce**

Import database to a new machine and try logging in with the user account used on the original machine.

**Extra info**

Debug information generated at 2020-05-26 14:51:55 UTC for Firefly III version **5.0.5**.

| Variable | Content |
| --- | --- |
| FF version | 5.0.5 |
| FF API version | 1.0.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , stack |
| PHP version | 7.3.16-1+0\~20200320.56+debian9\~1.gbp370a75 |
| Display errors | Off |
| Session start | 2020-05-01 00:00:00 |
| Session end | 2020-05-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

Hoping to get back up and running.

Thanks

**Comment by JC5** [comment]
Did you update or migrate the `APP_KEY` as well?

**Comment by daprofessa19** [comment]
> Did you update or migrate the `APP_KEY` as well?

No, I didn't do that explicitly. When I did the DB import, I reloaded the Firefly webpage and it very quickly ran through some operations. After this, I could actually see all my data, and I even imported new transactions.

But after some time, I think the session expired, and now I can't get past the authentication error.

**Comment by JC5** [comment]
Alright. Clear out your cookies and empty the cache just in case using "php artisan cache:clear".

Sorry for the generic response, just trying to rule out the obvious.

**Comment by Kenw00t** [comment]
I'm experiencing the same issue on 5.1.1 (using Docker compose). The backup section of the documentation should outline all necessary steps to do a proper restore from scratch.

**Comment by JC5** [comment]
What exactly are you missing?

**Comment by daprofessa19** [comment]
> Alright. Clear out your cookies and empty the cache just in case using "php artisan cache:clear".
> 
> Sorry for the generic response, just trying to rule out the obvious.

OK, I have done this, and it didn't solve the problem. I also checked my original installation, and the APP_KEY is just using the default string.

**Comment by daprofessa19** [comment]
Do you have other suggestions for me to try? I'm thinking the password hash is not matching, but I'm not sure why that would be the case, even after resetting the password.

**Comment by JC5** [comment]
All I can suggest is "try again just to be sure". This part of the code should be pretty foolproof, I don't know what's going on :(

**Comment by daprofessa19** [comment]
Could you link me to the full database restore procedure? I want to try again the process from the beginning.

**Comment by JC5** [comment]
All I have is the upgrade instructions.

https://docs.firefly-iii.org/advanced-installation/upgrade

**Comment by JC5** [comment]
Whoops
