### ISSUE TITLE
Auto install through Ampps

### ISSUE THREAD

**Issue by hayoken2000** [firefly-iii/firefly-iii#3402]
I am running Firefly III version 5.2.6

**Description**
I auto installed through Ampps and it is haveing the currency issue. Invalid server configuration:  Firefly III is unable to format monetary amounts because your server is missing the required packages. There are instructions how to do this.

I can't do the instructed because its on a windows server. Any ideas how to fix this?

**Comment by JC5** [comment]
You are limited to the locales that come with the languages installed, unfortunately.

**Comment by rosspro15** [comment]
I have the same thing, I see the locales installed under the resources folder.

**Comment by rosspro15** [comment]
I got it. Under the locale settings, you have to choose straight English, not English (United States).

**Comment by hayoken2000** [comment]
Is that within the program?

**Comment by rosspro15** [comment]
Yes, under options, preferences, locale settings

**Comment by hayoken2000** [comment]
Thanks that worked!
