### ISSUE TITLE
Support Rule Triggers based on transaction date

### ISSUE THREAD

**Issue by sa7mon** [firefly-iii/firefly-iii#3403]
**Description**

- I would like Firefly III to have the ability to create triggers based on transaction dates

**What are alternatives?**

- None

**Additional context**

I have 2 different monthly subscriptions that bill through Apple iTunes for the same amount. There is no way for me to tell these subscriptions apart except by the date - one bills on the 1st of the month and the other bills on the 10th. Both have an ACH description of "Apple.com/bill".

**Comment by JC5** [comment]
Upgrade to the latest version. 


https://github.com/firefly-iii/firefly-iii/releases/tag/5.2.6

**Comment by sa7mon** [comment]
@JC5 Thanks! My bad for not pulling the latest version before creating the issue.

I'm not able to figure out how to create a rule for "10th of the month" after consulting the docs. `start of this month` doesn't seem to work for the one on the 1st either.

**Comment by JC5** [comment]
You can't pick a specific day of the month. `start of this month` works fine on the demo site?

**Comment by JC5** [comment]
But before you ask. I'm working on something where you could pick the day of the month. In your case, the format would be `xxxx-xx-10`. Other combinations will also be possible.
