### ISSUE TITLE
CSV Importer with Source/Destination Accounts

### ISSUE THREAD

**Issue by rafny** [firefly-iii/firefly-iii#3406]
I have a CSV with columns for Source and Destination accounts that match what's in FF. Some Source accounts are Revenue accounts (paychecks) while some can be an Assets (checking account) whose Destination is another Asset (credit card). And of course an Asset paying an Expense too.

Is it possible to import this way, and if not, how can I account for one import with multiple accounts and transactions?

Example CSV where each account (Source or Destination) is in FF as an Asset, Expense, Revenue, or Liability.

Date | Source Account | Destination Account | Category | Amount
-- | -- | -- | -- | --
02/10/20 | Checking | Babysitter | Childcare | 100
01/08/20 | Checking | Credit Card | Credit Card Payment | 500
04/19/20 | Credit Card | Starbucks | Restaurant | 15
03/13/20 | Bank Fees & Interest Earnings | Checking | Interest | 1
02/14/20 | Employer | Checking | Paycheck | 1000
01/27/20 | Checking | CVS | Pharmacy | 50

**Comment by JC5** [comment]
This is pretty normal, and the importer can handle it just fine. You have to make sure the assets and liabilities exist and be sure that they are mapped. Otherwise, just go for it.
