### ISSUE TITLE
Total amount displayed is empty for opening balance

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3407]
Just bumped randomly into this one, reproduced on the demo site:
![image](https://user-images.githubusercontent.com/34862846/83167193-380ac500-a110-11ea-9fc0-b81009ed977d.png)

![image](https://user-images.githubusercontent.com/34862846/83167175-33dea780-a110-11ea-841d-42955645fff4.png)
It can be disturbing for new users trying to figure out their freshly installed Firefly III instance.

I'll pick it up.

**Comment by JC5** [comment]
I wouldn't say "disturbing" :wink:
