### ISSUE TITLE
Have currently reconciled balance float as you scroll down during reconciliation

### ISSUE THREAD

**Issue by srpnor** [firefly-iii/firefly-iii#3410]
**Description**

When reconciling an account you may need to scroll down the screen, at which point your reconciled balance (top right of screen) scrolls off the top.  It can be useful to keep an eye on this when reconciling as it helps you know when you've balanced correctly.

**Solution**
Make the "Reconciliation Options" area of the screen pinned to the top right of the browser window and float down the screen as you scroll, or otherwise provide a floating "Reconciled Balance so far" figure that moves with the scroll.

**What are alternatives?**
Scrolling back up and down the browser window to check the balance as you tick items off the reconciliation.  It works perfectly fine, it's just a pain.

**Additional context**
Suggest that this window "floats" down the screen as you scroll:

![image](https://user-images.githubusercontent.com/65242783/83243779-4996b000-a196-11ea-80e6-c089851169ce.png)

Thanks for considering!

**Comment by JC5** [comment]
I'll see what I can do!

**Comment by JC5** [comment]
Will be picked up in the new layout.
