### ISSUE TITLE
Default Budget Option

### ISSUE THREAD

**Issue by dicksonleong** [firefly-iii/firefly-iii#3411]
**Description**

It will be nice if we can set a budget to be "default" so that the budget is automatically selected by default (instead of "(none)") when adding new transaction. I think most people will have a "primary" budget (for me, i only have one) and want to keep track all the expenses under this budget, so this will save an extra click to select the budget every time when creating a new transaction.

**Comment by JC5** [comment]
No, I'm sorry, that's not going to be an option.

**Comment by dicksonleong** [comment]
Any reason for that?

**Comment by dugite-code** [comment]
@dicksonleong you can easily use a rule to achieve this.

Trigger: When transaction is created

Rule Triggers When: Has no budget

Rule will: Set budget to - Default budget

This way if you create a transaction without a budget it just drops it right into your default budget

**Comment by JC5** [comment]
Nice! 😅  I hadn't even thought of that.
