### ISSUE TITLE
Display the money you have in different account types

### ISSUE THREAD

**Issue by anamaria85** [firefly-iii/firefly-iii#3412]
**Description**
In transaction, in right sidebar, above {% include 'list.periods' %} I wrote something so you always see the money you have in different account types.

**Solution**
My code:
1. In views/v1/transactions/index.twig:
{# boxes with info #}
{% if periods|length > 0 %}
    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
        <div class="box box-default">
            {{ AccountForm.activeLongAccountListNoSelect('source_id', null, {label: trans('form.asset_source_account') })|raw }}
        </div>
        {% include 'list.periods' %}
    </div>
{% endif %}
2. in app\Support\Form\AccountForm i have this function:
public function activeLongAccountListNoSelect(string $name, $value = null, array $options = null): string
    {
        $types           = [AccountType::ASSET, AccountType::DEFAULT, AccountType::MORTGAGE, AccountType::DEBT, AccountType::CREDITCARD, AccountType::LOAN,];
        $liabilityTypes  = [AccountType::MORTGAGE, AccountType::DEBT, AccountType::CREDITCARD, AccountType::LOAN];
        $repository      = $this->getAccountRepository();
        $accountList     = $repository->getActiveAccountsByType($types);
        $defaultCurrency = app('amount')->getDefaultCurrency();
        $grouped         = [];
        $date            = $this->getDate();

        /** @var Account $account */
        foreach ($accountList as $account) {
            $balance  = app('steam')->balance($account, $date);
            $currency = $repository->getAccountCurrency($account) ?? $defaultCurrency;
            $role     = $repository->getMetaValue($account, 'account_role');

            if ('' === $role && !in_array($account->accountType->type, $liabilityTypes, true)) {
                $role = 'no_account_type';
            }

            if (in_array($account->accountType->type, $liabilityTypes, true)) {
                $role = sprintf('l_%s', $account->accountType->type);
            }

            $key                         = (string)trans(sprintf('firefly.opt_group_%s', $role));
            $formatted                   = app('amount')->formatAnything($currency, $balance, false);
            $grouped[$key][$account->id] = sprintf('%s (%s)', $account->name, $formatted);
        }
        $return = '';
        foreach ($grouped as $groupKey => $group) {
            $return .= '&nbsp &nbsp <b>'.$groupKey.'</b><ul>';
            foreach ($group as $key => $item) {
                $return .= '<li>'.$item.'</li>';
            }
            $return .= '</ul>';            
        }
        $return .= '';
        return $return;
    }

**Additional context**
I don't know if it's ok written, but it work fine and it's also helpful.

**Comment by JC5** [comment]
Do you have a screenshot of what it looks like?

**Comment by anamaria85** [comment]
Right sidebar
![screenshot-cash-flow ro-2020 06 01-14_31_54](https://user-images.githubusercontent.com/6409346/83405220-b61ee280-a414-11ea-83cd-f49bc9ad7527.png)

**Comment by JC5** [comment]
Ah nice. Well, if anyone wants to use it, feel free to hack your own installation!
