### ISSUE TITLE
Recover APP_KEY

### ISSUE THREAD

**Issue by Kwbmm** [firefly-iii/firefly-iii#3414]
I am running Firefly III version 5.2.5

**Description**
It's very easy. I made an incredible mistake. I lost the APP_KEY stored in my firefly env file used by docker. 
I have multiple backups of both Postgre DB and Firefly volumes.
Is there any chance to get my data back?

Might duplicate/be related to #3401

**Comment by Kwbmm** [comment]
Found it by digging into memory sectors with `grep -a -C 500 'known pattern' /dev/sda | tee /tmp/recover`.

Now, out of curiosity, is everything lost if APP_KEY gets lost?

**Comment by JC5** [comment]
Glad to hear you have it back! You would have lost your attachments if you lost the key, and you would have to reset your password. Other data would be safe.
