### ISSUE TITLE
Can't view the entirety of "Lost your two factor authentication?" page on mobile

### ISSUE THREAD

**Issue by jaylenw** [firefly-iii/firefly-iii#3415]
**Bug description**
I am running Firefly III version 5.2.4, and my problem is:

I am unable to view the entire "Lost your two factor authentication" page on mobile as I also can't horizontally scroll.

**Steps to reproduce**

1.) View the login page on your mobile phone or in `responsive mode` on your desktop browser. 
2.) Click on `I forgot my two-factor thing.`
3.) View the `Lost your two factor authentication?` page greeting you to take the next necessary steps.

**Extra info**

Debug information generated at 2020-05-29 17:46:38 America/Los_Angeles for Firefly III version **5.2.4**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.4 |
| FF API version | 1.1.0 |
| Installation ID | xxxxxxxxxxxxxxxx |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.16 |
| Display errors | Off |
| Session start | 2020-05-01 00:00:00 |
| Session end | 2020-05-31 23:59:59 |
| Session first | 2020-05-11 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- I have added a stack trace from my log files 
N/A, CSS issue
- [x] I have added a screenshot.

I have encountered this issue on my Google Pixel using Chrome and in the Responsive mode in the web browser on Firefox.

![Screenshot_20200517-123724](https://user-images.githubusercontent.com/6505395/83315806-453eb700-a1d7-11ea-8037-d28f6f3c9a09.png)

Below are two screenshots of the page in Firefox's responsive mode. I have also showed the CSS classes that are related to this.

`class="ff-error-page"`
![ff-error-page](https://user-images.githubusercontent.com/6505395/83315900-c138ff00-a1d7-11ea-83e6-19d5b56d817a.png)

`class="ff-error-box"`

![ff-error-box](https://user-images.githubusercontent.com/6505395/83315940-065d3100-a1d8-11ea-81dd-d68d28ab2018.png)

- I was able to replicate it on the demo site https://demo.firefly-iii.org/
N/A

Perhaps we can enable horizontal scroll or enable the text to adjust on the page width?

Thank you for all of your great work.

**Comment by JC5** [comment]
I'll pick it up. Btw, the installation ID is not a secret, or I wouldn't have included it on the debug page :)

**Comment by jaylenw** [comment]
Thank you @JC5 . And yes, I think when I went back to review my issue before posting, my instinct was to make sure I didn't post any sensitive information. Anything that looked like a secret token or key was a red flag lol, but you are right :).
