### ISSUE TITLE
Make search case-insensitive by default 2

### ISSUE THREAD

**Issue by MeikelLP** [firefly-iii/firefly-iii#3416]
**Description**

Equal to #3058 but sadly those conversations were locked so I needed to create a new issue :/

This is the most annyoing thing about firefly and I truely cannot understand why this is not fixed by now. The excuse 
> It’s caused by postgresql being case sensitive and there’s not much I can do about it.

is just pure fake news. This is the "feature" that slows me down the most.

**Solution**

You can implement case insensitivity safely in querys by doing:
```sql
UPPER(tableA.title) = UPPER(@myParam)
```

**What are alternatives?**
Not doing anything again.

**Comment by sephrat** [comment]
It's not as simple as you think. See https://github.com/firefly-iii/firefly-iii/issues/3230 for more technical details.
If you have a simple solution, pull requests are welcome.

**Comment by JC5** [comment]
I am already working on a switch to MySQL for the default Dockerfile. The documentation will refer to this as well.

You're more than welcome to switch the underlying database to MySQL yourself.

As mentioned by @sephrat, editing SQL queries to be database engine specific is out of the question.

**Comment by JC5** [comment]
See also #3378

**Comment by MeikelLP** [comment]
So after testing my theory with [SQL Fiddle](http://sqlfiddle.com) on a PostgreSQL database:

```sql
CREATE TABLE testificate (
  title varchar
);

INSERT INTO testificate (title) VALUES ('abc');
INSERT INTO testificate (title) VALUES ('Abc');
INSERT INTO testificate (title) VALUES ('DEF');
INSERT INTO testificate (title) VALUES ('abcefilb');
```

and querying

```sql
SELECT title FROM testificate WHERE UPPER(title) like '%' || UPPER('abc') || '%'; # 3 results
SELECT title FROM testificate WHERE title like '%' || 'abc' || '%'; # 2 results
```

does what I expect. MySQL will return 3 results on both queries because they are always case insensitive (?)

**Comment by JC5** [comment]
```sql
CREATE TABLE `testificate` (
  `title` varchar(128) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

```sql
INSERT INTO testificate (title) VALUES ('abc');
INSERT INTO testificate (title) VALUES ('Abc');
INSERT INTO testificate (title) VALUES ('DEF');
INSERT INTO testificate (title) VALUES ('abcefilb');
```

```sql
SELECT title FROM testificate WHERE UPPER(title) like '%ABC%'; # 3 results
SELECT title FROM testificate WHERE title like '%abc%'; # 3 results
```

**Comment by MeikelLP** [comment]
Exactly that's why I propose this change. So every result in the application is the same independent from the SQL server. Right now we get different results when using postgres than when using mysql. That's really annoying as a postgres user.

**Comment by JC5** [comment]
Yes, but keep in mind this would only work for Latin characters. A lot of non-Latin characters don't have a upper- or lowercase variant. I broke something in Russian before with a similar fix.

**Comment by MeikelLP** [comment]
so russian language does not support `UPPER` what is this sorcery?

**Comment by JC5** [comment]
Very annoying sorcery :grin:. Which is why PostgreSQL is technically speaking the better choice. :wink:

**Comment by MeikelLP** [comment]
I know postgres is better obviously :P I use only postgres for big applications.

So is there no way to user UPPER to make a postgres based app more pleasant?

**Comment by JC5** [comment]
Not that I have found, yet.

**Comment by MeikelLP** [comment]
It's weird that this does not work without issues in SQL because in German we have the `ß` which doesn't have an upper case character (upper case is usually displayed as `SS` (double s)).

This works fine on PostgreSQL & MySQL

```sql
CREATE TABLE testificate (
  title varchar(40)
);

INSERT INTO testificate (title) VALUES ('strasse');
INSERT INTO testificate (title) VALUES ('straße');
INSERT INTO testificate (title) VALUES ('Strasse');
INSERT INTO testificate (title) VALUES ('Straße');

SELECT title FROM testificate WHERE title like '%str%'; # 2 in p - 4 in my
SELECT title FROM testificate WHERE UPPER(title) like '%' || UPPER('str') || '%'; # 4 in p - 4 in my
```

Can you tell me what the exact issue was with these Russian characters?

**Comment by JC5** [comment]
I really don't remember, sorry. I'm not going to add UPPER() to all queries, just FYI.

**Comment by MeikelLP** [comment]
is this only an upper case issue? I mean if all Russian characters (for example) are lower case couldn't we go with that?
