### ISSUE TITLE
Cannot add funds to piggy bank

### ISSUE THREAD

**Issue by abctaylor** [firefly-iii/firefly-iii#3419]
**Bug description**
I am running Firefly III version 5.2.6, and my problem is that I'm unable to add funds to any piggy bank, whether the balance is greater than, or less than, the balance of the linked asset account.

**Steps to reproduce**
- Brand new fresh installation
- Create a bank account w/ the wizard, net positive balance (e.g. £10,000)
- Create a piggy bank ("RAM Upgrade 2021") (£600)
- Attempt to add

**Extra info**
Debug information generated at 2020-06-01 10:43:04 Europe/London for Firefly III version **5.2.6**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.6 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.18-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2020-06-01 00:00:00 |
| Session end | 2020-06-30 23:59:59 |
| Session first | 2020-06-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 |

**Bonus points**

This bug **has** been reported twice in Issue#2662 and Issue#2974 but there is no resolution that I can see in both
- I have added a screenshot
- I was **not** able to replicate this on the demo site

![image](https://user-images.githubusercontent.com/30197206/83397119-fec6a380-a3f4-11ea-8c48-b7de5055b1fd.png)

**Comment by JC5** [comment]
This is maybe a silly question but is the piggy bank linked to the correct account?

**Comment by abctaylor** [comment]
Hey James - yes I believe so.

NB: the wizard makes two asset accounts when you create a new Firefly III login (_Bank of Foo_ Default asset account and a savings account with the same name) - I deleted the savings account that had the £0 balance.

Below is the piggy bank config:

![image](https://user-images.githubusercontent.com/30197206/83397895-48fc5480-a3f6-11ea-9a9d-21729de30de1.png)

**Comment by abctaylor** [comment]
I made a brand new fresh login (without deleting the default savings account) and the issue persists

**Comment by sephrat** [comment]
What's the maximum amount displayed when you try to add money to your piggy bank?
![image](https://user-images.githubusercontent.com/34862846/83401520-376e7900-a405-11ea-84a4-645613d6de26.png)

Can you enable debug log, reproduce the error and post the log?
https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode

**Comment by abctaylor** [comment]
Hi @sephrat. The maximum amount I can add is the total value of the piggy bank (600 in this case).

Sorry to ask a basic question; I have changed the .env file. Now how do I paste the logs/stack traces you want?

![image](https://user-images.githubusercontent.com/30197206/83410481-6210ff80-a40e-11ea-8bf8-0b8b1e282e45.png)
![image](https://user-images.githubusercontent.com/30197206/83410517-6f2dee80-a40e-11ea-898e-93ba0ffe6331.png)

**Comment by abctaylor** [comment]
Trying to add £10 fails due to `canAddAmount` returning false - what might this be about?

![image](https://user-images.githubusercontent.com/30197206/83458889-3cf6ae00-a45b-11ea-9178-7c79699b6e03.png)

**Comment by JC5** [comment]
Do you have transactions for that account set in the future perhaps?

**Comment by abctaylor** [comment]
Afraid not. Also, this account has no transactions in at all, just an initial balance.

On 2 Jun 2020 4:58 am, James Cole <notifications@github.com> wrote:
EXTERNAL SENDER


Do you have transactions for that account set in the future perhaps?

**Comment by abctaylor** [comment]
I am not sure if some process/job runs after a given time that would affect this, but today the issue has lapsed
![image](https://user-images.githubusercontent.com/30197206/83510350-c098b500-a4c4-11ea-8b5b-b54539d3a487.png)

**Comment by JC5** [comment]
Magic! 

I saw some tiny time differences in the code. Different ways to come to the same conclusion. Was your initial balance set on the 1st of June?

**Comment by sephrat** [comment]
I can reproduce with a freshly created user. 
Create a user, set up initial balance with the "getting started" help, create a piggy bank, try to add money to the piggy bank and *error*.
Manually changing the initial balance date to the day before fixes it.

"Getting started" sets time on the initial balance transaction, maybe that has something to do with it?

**Comment by abctaylor** [comment]
Hi both - initial balance was created 1st June 2020 on the asset account.

**Comment by sephrat** [comment]
I see what's wrong in the code.

The first issue is that there's an inconsistency in the reference date used for balance check.

- The final check that gives an error takes the balance as of right now.
- The popup tells you balance as of D-day minus 1 second (01/06/2020 23:59:59 if I run it today). 

The second issue is that the current balance calculation considers the initial balance to be in a future date if it's dated as of today. So the final check says your balance is 0 and prevents you from saving to your piggy bank.

@JC5 I can try and fix it myself if you like.

**Comment by abctaylor** [comment]
Thanks @sephrat!

**Comment by JC5** [comment]
I'll pick it up @sephrat, I have some code ready.

**Comment by sephrat** [comment]
@JC5 from my tests you also need to fix balanceIgnoreVirtual to take time into account. Initial balance is timed but the query in balanceIgnoreVirtual ignores the time and considers initial balance in the future.
https://github.com/firefly-iii/firefly-iii/blob/b968ef416ac1d7d30a2e6dfbeec6cee70af9573a/app/Support/Steam.php#L126 
When I played around with the code it seemed to work with format 'Y-m-d H:i:s'.

**Comment by JC5** [comment]
Thanks. It worked with my fix already but this should be part of the code indeed.

I'm going to go with "23:59:59" instead of "H:i:s" to really force the end of the day.
