### ISSUE TITLE
Error with date format during import

### ISSUE THREAD

**Issue by faultoverload** [firefly-iii/firefly-iii#3422]
I am using the [FireflyIII Plaid Connector](https://gitlab.com/GeorgeHahn/firefly-plaid-connector) and encountering an error when importing transactions. 

I believe that the date format being pulled from by Bank/Plaid is not in an expected format. Can someone provide the valid date format or point me in the right direction if I am way off base here?

Date string pulled from plaid API : `5/31/2020 12:00:00 AM`

Error Message generated by FireflyIII API: `Unhandled exception. System.AggregateException: One or more errors occurred. (Error calling StoreTransaction: {"message":"The given data was invalid.","errors":{"type":["The type field is required."],"date":["The date field is required."]}})
 ---> FireflyIII.Client.ApiException: Error calling StoreTransaction: {"message":"The given data was invalid.","errors":{"type":["The type field is required."],"date":["The date field is required."]}}`

**Comment by JC5** [comment]
I didn't write the Plaid connector, so I can't give support in this repository. Please continue [in your own reddit thread](https://old.reddit.com/r/FireflyIII/comments/guxvaw/error_with_date_format_in_transaction_import/) or contact @GeorgeHahn directly.
