### ISSUE TITLE
Force import / overwrite

### ISSUE THREAD

**Issue by MrMEEE** [firefly-iii/firefly-iii#3423]
Hi

I had some problems with duplicated entries from my Spectre Imports (to which I found the problem), so I tried to delete all previous transactions.. but now I can't get Spectre to import all the old records again (nothing shows up).. 

Is there a way to do a force-import? 

Thanks

**Comment by JC5** [comment]
There isn't, I'm afraid. If you delete the deleted entries from the `transaction_journals` table however, it should be fine again.

**Comment by MrMEEE** [comment]
It worked.. thanks..
