### ISSUE TITLE
Fatal error when leaving budgeted amount blank

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3425]
If you click on "Set budgeted amount" leaving the amount blank, it gives a fatal error.
![image](https://user-images.githubusercontent.com/34862846/83667126-3a689580-a5ce-11ea-821d-0e3d1598d61c.png)

`"SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: budget_limits.amount (SQL: insert into "budget_limits" ("budget_id", "transaction_currency_id", "start_date", "end_date", "amount", "updated_at", "created_at") values (3, 7, 2020-06-01 00:00:00, 2020-06-30 00:00:00, ?, 2020-06-03 19:10:59, 2020-06-03 19:10:59))"`

Looks like there's no validation for that field.

**Comment by JC5** [comment]
Indeed, nice find. I committed a fix :)
