### ISSUE TITLE
Split transactions should be grouped and summed when reconciling

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3429]
**Description**
So when you reconcile an account with split transactions it currently lists each individual split and has you check off each individual split, but does not list the total amount for the transaction.
![Screenshot_20200604_073446](https://user-images.githubusercontent.com/21091510/83752565-bb5b7780-a636-11ea-83b1-76d9f866dbd6.png)
But when you are on other screens (like the account page or expenses page) it groups these transactions with the overall split description and the total amount of the transaction.
![Screenshot_20200604_073601](https://user-images.githubusercontent.com/21091510/83752789-1a20f100-a637-11ea-9c6d-fddeaa2475a7.png)
Splitting transactions is more for personal tracking and is not reflected on the statement you receive from your bank, so you must leave the reconciliation page or do math in order to reconcile the splits.

**Solution**
Have the overall split description listed on the reconciliation page like it is on other pages and allow users to check that box when reconciling.

**What are the alternatives**
Leave the site as it is, not reflecting real world statements and causing math or more tabs.

**Comment by sephrat** [comment]
I agree, I've had this on my mind for a moment. I don't believe there's a reason anybody would want to reconcile individual split transactions. 
I can try and propose a pull request if @JC5 gives the green light.

**Comment by JC5** [comment]
This depends entirely on your use case. I also know of people who make grouped transactions for shopping trips or related expenses. In those cases, it's easier if the splits are listed individually.

**Comment by sephrat** [comment]
I see. Maybe a kind of local "select all" checkbox on a master row then? The current option wouldn't disappear but you'd be able to check them all at once.

**Comment by death2cupbots** [comment]
Yeah let people check either way maybe? Like I can check them all of at once but someone else can go one at a time. I get that everyone has their own way of entering their transactions, but I thought we had tags for shopping trips or related expenses. I totally understand that people should be allowed to enter stuff in a way that's helpful for them, but we should also get the option to reconcile in a way that makes sense to us and fits the philosophy of the program.

**Comment by sephrat** [comment]
Here's a mockup of what I imagined:
![image](https://user-images.githubusercontent.com/34862846/83848232-ce8d4680-a70d-11ea-9adf-9407be5d0632.png)

It's ugly for now but you get the idea.
Checking the total row would check all related split transactions and vice-versa.

I'm just not sure how good the total row will render with foreign amounts.

@JC5 do you think it's worth investigating? I can take it.

**Comment by JC5** [comment]
I'm not a fan, to be honest. You got to weigh the cost of code complexity and maintainability versus the advantage. And this is a very narrow use case. You'll need several cases to maintain the checkboxes over a split, check/uncheck all, etc. And of course you'll need several loops to calculate sums and totals. 

So no, I'd rather leave it like this.

**Comment by M-Paladin** [comment]
Is it possible then to have an option to choose between seeing a 1-line split transaction or a multi-line one ?
When I pay my loan to bank, there's a 1-line operation grouping insurance and loan so when I reconcile, I reconcile both.
It's the same with my tenant who pays charges and rent in 1 operation but I split them in Firefly and I reconcile both.
I don't agree it's a narrow use case, many people have loan or tenant. But maybe they are not using Firefly.
Before I was using MoneyManagerEX (https://github.com/moneymanagerex/moneymanagerex). I moved to Firefly because of the lack of web interface and the pain in Linux and SMB mount. In MMex split transaction where really easy to use. I don't understand why it seems such a pain in Firefly.
