### ISSUE TITLE
Certificate error at docs.firefly-iii.org

### ISSUE THREAD

**Issue by crakkhead** [firefly-iii/firefly-iii#3431]
I can't navigate to [docs.firefly-iii.org](https://docs.firefly-iii.org) using Firefox 76. The certificate is configured for *.gitbooks.io domains, so the browser denies the connection.

**Comment by JC5** [comment]
I don't have this issue myself. Firefox Safari and Chrome. Are you on Windows?

Same question for @varioous

**Comment by JC5** [comment]
My Firefox 76 doesn't complain. Not sure what's happening.

<img width="855" alt="Screenshot 2020-06-04 at 17 28 32" src="https://user-images.githubusercontent.com/5889984/83776789-1eb9c980-a678-11ea-9b10-1320ab2dc0e5.png">

**Comment by sephrat** [comment]
At the time of posting I could reproduce the certificate issue but now it's gone. Maybe a temporary issue on the intermediate certificate?

**Comment by JC5** [comment]
Possibly. It's a CNAME record so it could be on Gitbook's side.

**Comment by crakkhead** [comment]
Can confirm, the problem seems fixed.
