### ISSUE TITLE
Possibility to filter the date by current month

### ISSUE THREAD

**Issue by dperezq** [firefly-iii/firefly-iii#3434]
**Description**
Right now Firefly allows multiple date filters, even a custom date filter, but does not allow to filter by the current month. Last 30 days does not means the same, due it is including also the previous month, and it is needed to modify the filter everyday with a custom one. This would be a perfect feature to see based on the day of the month all the expenses done and the budget foreseen.

**Solution**
Include in the date selector at the top, another option to set "Current month"

**What are alternatives?**
Manually you can set all the months the date range from day 1 to today.

![imagen](https://user-images.githubusercontent.com/7505361/83802504-2e9ed100-a6ab-11ea-9a8c-a38771ae0b2f.png)

**Comment by JC5** [comment]
I'm not sure what you mean. It defaults to the current month. Would you like a button back to the current period?

**Comment by dperezq** [comment]
Not really, right now you have the chance to select from different ranges. I want to display the current month details. For example, today it is 4th June, so it should display from 1st to 30th of June. I am not able to do this, I thought it was not possible or at least I cannot get it.

**Comment by JC5** [comment]
What you describe is default behavior. What did you change in your preferences?

**Comment by dperezq** [comment]
Get it, in the preferences>range view, you have to select one month and that's it. I had selected to one year...
