### ISSUE TITLE
Recurrent transactions from bills automatically

### ISSUE THREAD

**Issue by dperezq** [firefly-iii/firefly-iii#3435]
**Description**
When you create a bill, usually this always has the same due date for paying every month. It would be great to have an option to automatically from the bills create the recurrent transaction automatically. From the bill view, you have all the details needed for creating the recurrent transaction.

**Solution**
When create/edit a bill, it could be possible to create a current transaction from the same view with a checkbox. Could be added inside the card of "options" in bill view.

**What are alternatives?**
Creates the bill and then creates the recurrent transaction.

**Comment by JC5** [comment]
What about a button to create a recurring transaction from a single transaction? The bill has way to few details anyway.

**Comment by dperezq** [comment]
That could also fit the needs about not creating a recurrent transaction for each one. Mine was a proposition but I like yours too.

**Comment by JC5** [comment]
Button will be present in the next release.
