### ISSUE TITLE
Posibility to confirm recurrent transactions (not automatically created)

### ISSUE THREAD

**Issue by dperezq** [firefly-iii/firefly-iii#3436]
**Description**
When I create a recurrent transaction, those automatically are created the day that should be, as expected. However some of them are delayed some days due national bank holidays or whatever. For those cases you have to edit the transaction and could loss the track of them, if you have created multiple automatic transaction of them having to review all. This improvement could simplify the process.

**Solution**
When creating a recurrent transaction, enable an option to do it automatically or manually. In case manually option has been enabled, then in the recurrent transaction view where the left icons are, put a check icon to confirm the transaction and add it the current day.

**What are alternatives?**
Enter into an automatically created transaction and edit it.

**Comment by JC5** [comment]
No. A button to create a recurring transaction by hand is on my list though.
