### ISSUE TITLE
Add subcategories and icons for the categories

### ISSUE THREAD

**Issue by dperezq** [firefly-iii/firefly-iii#3438]
**Description**
I would like Firefly III to include categories and subcategories and the possibility to include for them different icons. This would improve the user experience of the application. For example for car category a car icon could be selected. An inside this category, I could add gas refill, maintenance, parking, fines, etc...

**Solution**
Some propositions to implement it:
- When you create or edit a category, inside the view, below the category name, it can be selected among different icons the category icon. This icon can be displayed in the transaction view and category view to identify the categories easily.
- Also from the main category view, at the right side of "New Category" a new button is added named "New Subcategory" and in the view, it will be selected the main category and the subcategory name.
- In the category view, the main categories will be displayed in bold and below the subcategories or a menu type added, for example a chevron with the main category and when you click the subcategories are displayed.
- In the transaction view, the dropdown should be modified to show the main category and the subcategories created. Bold and normal?

**What are alternatives?**
No possibility to do this.

**Comment by JC5** [comment]
Thanks for the suggestion! Firefly III will [not](https://docs.firefly-iii.org/support/features) be featuring sub-categories. 

Icons are also not going to be added.
