### ISSUE TITLE
Support for hosting under a subdirectory

### ISSUE THREAD

**Issue by nwl** [firefly-iii/firefly-iii#3439]
I am running Firefly III version jc5x/firefly-iii:latest using docker-compose.

I am hosting it under a subdirectory rather than top-level directory. The app seems to not support this based on any variable I can see in the .env file. Can you confirm?

**Comment by dugite-code** [comment]
My understanding is that subdirectories are not officially supported yet https://github.com/firefly-iii/firefly-iii/pull/2514

However some people appear to have it working https://github.com/firefly-iii/firefly-iii/issues/2848 I personally never have had much luck and ended up using a sub-domain instead.

**Comment by JC5** [comment]
Same here, basically. There are some hacks to make the nginx running in the Docker container believe it's running in a subdirectory but I refuse to implement them. There's got to be a more elegant way to do this. If a reverse proxy is worth its salt it should be capable of doing this without the container needing to change.

But as far as I can see the entire internet just changes the container and done.

**Comment by nwl** [comment]
I'll close this as a DUP of https://github.com/firefly-iii/firefly-iii/pull/2514

As comments in that issue state, most apps allow you to define the root URL in the config. Not sure if this the best way of doing it, but it is certainly the most common and importantly, the most admin friendly.
