### ISSUE TITLE
Possibly change Rearranging rules

### ISSUE THREAD

**Issue by dugite-code** [firefly-iii/firefly-iii#3440]
**Description**
This is a minor annoyance but when re-arranging rules that are in a big list (Give rule less/more priority) the page re-fresh causes you to loose your place.

**Solution**
As with the budgets it would be good to just click and drag rules into position.

**What are alternatives?**
Have some anchor tags on the groups or rules so when the page re-freshes you jump to the correct position?

**Comment by JC5** [comment]
I'll see what I can do!

**Comment by JC5** [comment]
Fixed in next release.
