### ISSUE TITLE
Budgets New Month Issue?

### ISSUE THREAD

**Issue by jayenicks** [firefly-iii/firefly-iii#3441]
I am running Firefly III version 5.2.6.

I'm a new user and have only used Firefly for a couple of week so I'm not sure if this is expected or not (amazing app, thanks your all your hard work!).  I am getting a "This amount applies from June 1, 2020 to June 1, 2020" message on several of my budgets, and it seems to be affecting the total in the already spent bar, it's showing I'm over budget event though I should be under.

Please let me know what extra info/data might be helpful to answer my question, thank you!

This month screenshot
![image](https://user-images.githubusercontent.com/32601491/83894335-c5ed3e00-a716-11ea-8162-9a9a06ccde0e.png)

Last month screenshot
![image](https://user-images.githubusercontent.com/32601491/83894584-1b294f80-a717-11ea-8472-416bbc05da66.png)

**Comment by sephrat** [comment]
Did you use the automatic feature to set your budget amounts? There's an option to set the budget for a day:
![image](https://user-images.githubusercontent.com/34862846/83895313-cf949700-a752-11ea-9e1b-6c2730acc6d4.png)
![image](https://user-images.githubusercontent.com/34862846/83895285-c5729880-a752-11ea-9e0b-42e6988eefdb.png)
Maybe you set an incorrect period.

Or possibly it has something to do with the view range you set in your preferences when you manually set your amounts:
![image](https://user-images.githubusercontent.com/34862846/83895423-f521a080-a752-11ea-8350-c2a50fbb632e.png)

I'd suggest you remove these 1st June amounts and make sure you're on a monthly view range before setting your budgets properly.

**Comment by jayenicks** [comment]
> Did you use the automatic feature to set your budget amounts? There's an option to set the budget for a day:
> ![image](https://user-images.githubusercontent.com/34862846/83895313-cf949700-a752-11ea-9e1b-6c2730acc6d4.png)
> ![image](https://user-images.githubusercontent.com/34862846/83895285-c5729880-a752-11ea-9e0b-42e6988eefdb.png)
> Maybe you set an incorrect period.
> 
> Or possibly it has something to do with the view range you set in your preferences when you manually set your amounts:
> ![image](https://user-images.githubusercontent.com/34862846/83895423-f521a080-a752-11ea-8350-c2a50fbb632e.png)
> 
> I'd suggest you remove these 1st June amounts and make sure you're on a monthly view range before setting your budgets properly.

That's what I thought at first, I expected I set the range wrong, but here are the settings on the $300 budget.
![image](https://user-images.githubusercontent.com/32601491/83896079-36955a00-a719-11ea-81a5-b1d15963b85e.png)

I just checked my layout, it is set to one month as well.

**Comment by JC5** [comment]
Yes, this is a known issue. New budgets created with the "auto budget" option turned on will do this. I can't find the related issue. 

Expect a fix in the next release. For now, use the dropdown arrow next to the wrong amount to remove it, and then set it again by hand. Fill in the now-empty box. That should fix the issue for now.

**Comment by jayenicks** [comment]
> Yes, this is a known issue. New budgets created with the "auto budget" option turned on will do this. I can't find the related issue.
> 
> Expect a fix in the next release. For now, use the dropdown arrow next to the wrong amount to remove it, and then set it again by hand. Fill in the now-empty box. That should fix the issue for now.

Yep, that fix worked for me. Thanks for the confirmation, I tried to see if it was a know issue but came up short.

Thanks again for your help!

**Comment by JC5** [comment]
See also #3309
