### ISSUE TITLE
Creating an expense account fails when the IBAN is in use 

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#3444]
**Bug description**
I am running Firefly III version 5.2.8 , and my problem is:

It is not possible to create an expense account when the assigned IBAN number is in use by an other Expense account.  
If I test this on the demo site you will see an error message that the IBAN already is in use. So maybe this check is broken in the latest version of FF3?

Is this behavior by design or is this an bug?

**Steps to reproduce**
1. Create an account with IBAN number.
2. Create an Second account with an different name and the same IBAN number. 
The application does not show an error in the log or in the GUI but the second account will not be created.

**Extra info**
Debug information generated at 2020-06-06 14:11:26 Europe/Amsterdam for Firefly III version **5.2.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.2.8 |
| Firefly III API | 1.1.0 |
| PHP | 7.4.6 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| Using docker? | false |
| Telemetry | true |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-06-01 00:00:00 |
| Session end | 2020-06-30 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| User ID | 6 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0 |

**Bonus points**

- I searched and nobody reported this bug before
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
The demo site is also on 5.2.8, and I see the error message. But yes, this is on purpose. 

You can create, with the same IBAN:

(an expense account AND a revenue account) OR (any asset account or liability)

So expense/revenue accounts can share an IBAN (once) but if you use that IBAN for an asset or liability, it's no longer possible to do so.

**Comment by leander091** [comment]
Alright, thanks for the explanation.
It looks like in that case the check is not working as expected on my system. I'am not seeing the error message on my system and FF3 redirects to the home page as  like the account is created successfully.

**Comment by JC5** [comment]
That's strange, first time I see that happening. Self-hosted right, nothing weird or exotic?

**Comment by leander091** [comment]
Yes, this is a self hosted system (vm based) not a docker system. 

I cannot recall i did something weird or exotic with my setup, I'm using PHP 7.4 at the moment.
