### ISSUE TITLE
CSV Import permissions error

### ISSUE THREAD

**Issue by achembarpu** [firefly-iii/firefly-iii#3447]
**Bug description**
I am running Firefly III version 5.2.7, and my problem is, CSV import appears to fail due to firefly server-side permission issues.

**Steps to reproduce**

- I'm running both firefly and the csv importer in docker.
- Both the containers have been setup exactly as given in the docker-compose.yml.
- The CSV detection & JSON configuration all seem to be valid.
- Once the job starts, after a few seconds, it fails with this error:

```
The job could not be started, or failed due to an error. Please check the log files. Sorry about this :(.

Error(s)
Line #0: Internal error: GuzzleException: Server error: GET http://fire.nas.home/api/v1/search/accounts?query=1&field=id&page=1 resulted in a 500 Internal Server Error response: {"message":"Internal Firefly III Exception: file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/ (truncated...) in file /var/www/html/app/Services/Import/Task/Accounts.php:213
```

**Extra info**

Firefly server-side error log:

```
[2020-06-07 16:02:03] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/1e\/2a\/1e2a4a281b423df6092190ed8c4cb3306d0924ad): failed to open stream: No such file or directory","time":"Sun, 07 Jun 2020 16:02:03 +0200","file":"\/var\/www\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Filesystem\/Filesystem.php","line":133,"code":0,"version":"5.2.7","url":"http:\/\/fire.nas.home\/api\/v1\/search\/accounts?field=id&page=1&query=1","userAgent":"GuzzleHttp\/6.5.4 curl\/7.64.0 PHP\/7.3.18","json":true}
```

I docker attach-ed to the container, and `/var/www/firefly-iii/storage/framework/cache/data/1e` is owned by `root:root` instead of `www-data:www-data` like all the dirs around it. Further the `2a` subdir as seen in the error message, does NOT exist.

![image](https://user-images.githubusercontent.com/7100147/83971106-b66a2280-a8d9-11ea-929d-ce3a04bc0263.png)

**Bonus points**

- I searched and it looks a lot like this old bug: https://github.com/firefly-iii/firefly-iii/issues/1235

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3446

It's happening often. I'm not yet sure about the cause. For now, check out the other issue.

**Comment by JC5** [comment]
I've just finished building the 5.2.8 Docker image again. If you can, remove the container, **also** remove the image and restart the container. Your host should re-download the image before starting Firefly III again. With a little luck this fixes the issue permanently.

You can verify that you have the latest version of the Docker image because the `/debug` page will report that you're running PHP 7.4 instead of 7.3.

**Comment by achembarpu** [comment]
That doesn't seem to fix it. I have a feeling it is due to the server running as root, and the ownership being assigned to www-data only before the server runs - or some such docker quirk.

I found a much easier solution, after spending all morning debugging this - switch to `memcached`.

**Comment by JC5** [comment]
Thanks. The weird thing is, Apache should be running as www-data. The search continues!

Thanks for the quick feedback!

**Comment by achembarpu** [comment]
IMHO, it might be worth putting in the README, especially for people using docker, where permissions get crazy/quirky and spinning up memcached/redis is way easier.
