### ISSUE TITLE
expense accounts graph is not rendered

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#3449]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:

Since upgrade to the latest version (before should be 5.2.2).
On the starting-page the "expense accounts"-graph is not rendered.

**Steps to reproduce**
Open my Firefly-III

**Extra info**
--
Debug-Log / StackTrace

https://pastebin.com/aXKGEcE1

--
**Bonus points**

**Comment by JC5** [comment]
Check out the other issues please

**Comment by devfaz** [comment]
```
root@6c90b0cafe5a:/var/www/firefly-iii/storage/framework/cache/data# cd 2
20/ 21/ 22/ 24/ 25/ 27/ 28/ 2b/ 2c/ 2d/ 2e/ 2f/ 

```

2a is missing in the filesystem. Any ideas?

**Comment by devfaz** [comment]
just for others: https://github.com/firefly-iii/firefly-iii/issues/3446

browse to /flush to clear your cache.

**Comment by devfaz** [comment]
@JC5  - FYI: sorry, but didnt help for very long.

* run /flush (many times)
* stopped my container
* removed my container
* removed the image
* downloaded the latest image (8d5a5a6597e2)
* restarted everything - still getting cache-errors
* doing /flush fixes the issue for some requests, but it happens again - just a matter of time.

**Comment by devfaz** [comment]
found further bug reports, so just ignore above..

it seems during container-startup the cache-folder is filled with directories and files owned by root, than later these files (mostly) get chowned to www-data.

I currently dont understand why (at all) root is used/required here, but I will try to debug this further.

**Comment by devfaz** [comment]
ok, so we need root (at least) to get the apache binded on port 80.
Seems like the php-calls work also as www-data (just changed the dockerfile to run entrypoint as www-data), but apache will fail to start, because it

* cant bind on port 80
* cant write to logfiles

I would change the default port from 80 to 8080 (>1024) so nonprivileged are allowed to bind to and chown/mod the logfiles to allow www-data to write (or redirect to stderr/stdout)

Another way would be to run entrypoint as www-data (so php is creating the files as www-data) and just use sudo to start the apache as root.

**Comment by devfaz** [comment]
I quickly (workaround style) implemented the second way.

```
root@srv:/srv/firefly-iii# docker exec -it firefly-iii_firefly_iii_app_1 bash
www-data@f8f97731592c:~/firefly-iii$ cd /var/www/
www-data@f8f97731592c:~$ ls
firefly-iii  html
www-data@f8f97731592c:~$ find . ! -uid 33
.

```

**Comment by devfaz** [comment]
=> sudo-workaround-merge-request:  https://github.com/firefly-iii/docker/pull/9

**Comment by devfaz** [comment]
==> reconfigured apache to use port 8080: https://github.com/firefly-iii/docker-base-image/pull/5

feel free to decide which "solution" you like more.
I think dropping root privileges at all - if possible - is always the better way.
If you want to use the second way, you also have to remove the "USER root" in entrypoint.sh
```

@@ -27,6 +27,4 @@ RUN curl -SL https://github.com/firefly-iii/firefly-iii/archive/$VERSION.tar.gz
 EXPOSE 80
 VOLUME $FIREFLY_PATH/storage/export $FIREFLY_PATH/storage/upload
 
-USER root
-
 ENTRYPOINT ["/entrypoint.sh"]

```

**Comment by devfaz** [comment]
@JC5 - above some (hopefully) fixes for the caching issue / access rights issues.

**Comment by JC5** [comment]
Thanks guys. I'd like to look for the root cause (badum tsj), which also includes removing root rights like you say.

I'll check out your PR's. Thanks for helping me search!
