### ISSUE TITLE
Translations in bills section missing

### ISSUE THREAD

**Issue by schneekluth** [firefly-iii/firefly-iii#3450]
**Bug description**
Since 5.2.7 some translations in the bills section are gone. This happens in the column of the next expected date for a bill. Instead of the correct translation you can see `components.not_or_not_yet` or `components.not_expected_period`.

**Extra info**
Im am running the docker image.

![bills](https://user-images.githubusercontent.com/5740913/83977191-e7a91980-a8fe-11ea-91a4-691f56ce3718.png)

**Comment by sephrat** [comment]
Same problem on demo site in English.
Can't find the problem yet.

**Comment by JC5** [comment]
Thanks for letting me know, I saw it as well. Will pick it up :)

**Comment by fabianonetto** [comment]
I just caught this one with the latest docker stable version

![image](https://user-images.githubusercontent.com/15900163/84513217-22aca380-ac97-11ea-9f64-8077e6a86e1d.png)

**Comment by JC5** [comment]
The next release isn’t out yet I’m afraid.

**Comment by fabianonetto** [comment]
Thanks @JC5 for a second I thought this had been released already. My bad. Any existing workaround? i.e. using a previous image version perhaps? Thanks

**Comment by JC5** [comment]
No I’m sorry, no fix exists yet.
