### ISSUE TITLE
Scroll back up when confirming transaction

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#3451]
Whenever I make one transaction I fill in all the form fields and i need to scroll a bit down to press the Submit button. 

My issue is that right now you get no direct feedback, since the green confirmation message appears at the very top (so I have to scroll back up to make sure the transaction was added correctly. 

One solution would be to force a scroll up when pressing the button, another could be to move the message down or add additional feedback next to the Submit button

**Comment by JC5** [comment]
I see what you mean. Scroling up is not an option, but some feedback at button level would work. It's on the list!

**Comment by JC5** [comment]
The error message / success message will now also appear below the submit button.
