### ISSUE TITLE
oauth client / personal access token half created when mailer is misconfigured

### ISSUE THREAD

**Issue by pbartyik** [firefly-iii/firefly-iii#3452]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:

When mailer is not working creating an OAuth client or a personal access token builds the client/token but it does not function and no related error message is given.

**Steps to reproduce**
Set mailer to smtp, provide an incorrect config (in my case it was incorrect port).
Create new OAuth client/Personal Access Token.
Window content is not fully populated, but client/token is created.
Using generated OAuth Client secret to authenticate does not work.

**Extra info**
Arch linux
Qutebrowser

qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.3
PyQt: 5.15.0

Sorry no debug page/trace available, fixing the mailer resolves this and I don't want to break it again :)

**Comment by JC5** [comment]
No worries, thanks for letting me know. It should be easy to debug. I'll check it out!

**Comment by JC5** [comment]
Mmmm, no issues so far. Breaking the mailer results in a valid Personal Access Token and client. Although since email is sent in sync with the request, this could take a while. 

I'll keep an eye on it. Thanks for letting me know!

**Comment by pbartyik** [comment]
No worries, thanks for checking it out!
