### ISSUE TITLE
Cache problems / file permissions / write errors

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#3456]
Many people are running into this issue. Especially on Docker. Things that may work:

- Browse to /flush to clear your cache.
- Execute command: `docker exec [container] php artisan cache:clear`
- Remove + recreate the container.

But the problem is persistent and annoying.

First of all: sorry about this. What you'r experiencing is an issue that's been bugging Firefly III for quite some time now. It was never this big. A solution is ready and will be part of Firefly III v 5.3.0. You will have to wait some time though before this version is released. I have some more changes to implement. What you must be aware of:

- The new release of Firefly III will require PHP 7.4. Docker users will notice their containers are already at 7.4 though.
- Firefly III will no longer be exposed at port 80, but port **8080**.

Feel free to reply to this thread with your questions and comments. I have no timeline yet for the new release. Stay tuned, and once again my apologies for the problems.

**Comment by lguima** [comment]
Clearing cache in Docker container worked for me, thanks!

**Comment by Tras2** [comment]
Hi,

I'm running on Docker and just wanted to say I came across this issue today and `/flush` worked for me

Thanks for the workaround - these things happen, it's still a great product :+1:

**Comment by damiantje99** [comment]
Just to let you know, flushing the docker also worked for me. I'm running it on a Unraid Server.

**Comment by Tras2** [comment]
> 
> 
> Just to let you know, flushing the docker also worked for me. I'm running it on a Unraid Server.
> 
> Also, maybe good to know, the problem started when I deleted a Revenue Account.

Hmn, now you mention it, I think I got the problem just after I'd marked a couple of asset accounts inactive.  May/may not be related

**Comment by lguima** [comment]
It has affected the chart in the dashboard as well. Resolved cleaning the cache.

**Comment by JC5** [comment]
Hi all!

I just released 5.3.0-alpha.1. This version should fix the problems you've been running into. The Docker tag is `develop` or `5.3.0-alpha.1`.

Since this is an alpha release, tread carefully:

- New database upgrades will make downgrading problematic. Get a backup of your DB and APP_KEY
- It now runs on port 8080, not port 80.

I would appreciate anybody's help to test this new version.

**Comment by Tras2** [comment]
Hi,

On `5.2.8` I had the cache error when attempting to edit a specific recurring transaction no matter how much `/flush` I did I still couldn't load the edit page.  

I've just pulled down `5.3.0-alpha.1` and did the same attempt to edit and it worked. To prove it, I restored my backup and went back to `5.2.8` and the cache error was there again.  Upgraded to `5.3.0-alpha.1` and it's working fine. 👍 

I've clicked around a bit and found no obvious issues elsewhere.  I'm happy to run on the `develop` tag until it goes to release, I'm usually amending something every couple of days and I'll post here if anything crops up between now and then.

If you need any logs or other diagnostic assistance I'm happy to help

**Comment by chrismast** [comment]
Had cache errors on the previous version when creating new accounts and also while uploading via CSV (see #3482). Just upgraded to the alpha and both seem to be fixed.
Only smaller issue I had was a quite long delay of the popup window showing the Account Key, but that might have just been my LXC.
Will report back if any other issues.

**Comment by r8z0r1** [comment]
Thanks for the very fast response and accurate diagnosis with resolution. Someone should be paying you for this...

**Comment by JC5** [comment]
Thank you! And they do! I’m actually very proud to be sponsored by a lot of kind people 😊

**Comment by r8z0r1** [comment]
I will certainly be making a donation.

**Comment by Tras2** [comment]
> 
> 
> Hi,
> 
> On `5.2.8` I had the cache error when attempting to edit a specific recurring transaction no matter how much `/flush` I did I still couldn't load the edit page.
> 
> I've just pulled down `5.3.0-alpha.1` and did the same attempt to edit and it worked. To prove it, I restored my backup and went back to `5.2.8` and the cache error was there again. Upgraded to `5.3.0-alpha.1` and it's working fine. +1
> 
> I've clicked around a bit and found no obvious issues elsewhere. I'm happy to run on the `develop` tag until it goes to release, I'm usually amending something every couple of days and I'll post here if anything crops up between now and then.
> 
> If you need any logs or other diagnostic assistance I'm happy to help

I'm just checking back in to say that I've not had any issues since moving to `5.3.0-alpha.1`.  I've noticed this morning that my auto-update script has moved my docker container to `5.3.0-alpha.2`, also no issues so far :grinning:

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/releases/tag/5.3.0-beta.2

Beta 2 should also work, of course. If nothing pops up, this will be the new release over the weekend. Thanks again for your patience!

**Comment by JC5** [comment]
I'm calling it! [Firefly III v5.3.0](https://github.com/firefly-iii/firefly-iii/releases/tag/5.3.0) is out now. If you run into problems, please open a *new* issue. Read the changelog, the port Firefly III runs on has moved from 80 to 8080 so change your `docker-compose.yml` if necessary
