### ISSUE TITLE
Content Security Policy (CSP) Issue

### ISSUE THREAD

**Issue by bugreporting** [firefly-iii/firefly-iii#3459]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is: the content security policy

**Steps to reproduce**
You can reproduce this issue on the demo website and having the network monitor open in Firefox

**Possible Fix**
When trying to track down the source I temporarily disabled the CSP to verify that is the cause (security.csp.enable = false) and when that allowed the scripts without issue I went further into the policy. 

The issue appears to be based on the policy `script-src 'unsafe-inline'` in [app/Http/Middleware/SecureHeaders.php#L56](https://github.com/firefly-iii/firefly-iii/blob/389ffa820f034308198e35835c28205a5828eecc/app/Http/Middleware/SecureHeaders.php#L56)

If you update the policy to `sprintf("script-src 'self' 'unsafe-inline' 'nonce-%1s' %2s", $nonce, $trackingScriptSrc),` it will allow the scripts to run the first time rather then subsequent requests.

**Demo Site and Docker Image**
![firefly-csp](https://user-images.githubusercontent.com/65435240/84312804-2d4a2a00-ab2b-11ea-8eb1-ba1a3a50cb0c.PNG)

**After updating the Policy**
![firefly-csp-1](https://user-images.githubusercontent.com/65435240/84313054-99c52900-ab2b-11ea-9d44-0eb5099919ca.PNG)

**Comment by JC5** [comment]
Yes, but that also seems to remove the point of having a nonce. I've noticed the issue as well, but this doesn't seem to be the solution.

**Comment by bugreporting** [comment]
I agree, and I did some further research into what the cause of this may be, and it turns out it is a firefox bug. 

An original report is here: [Bug 1591807](https://bugzilla.mozilla.org/show_bug.cgi?id=1591807)

A duplicate was here for nextcloud: [Bug 1590400](https://bugzilla.mozilla.org/show_bug.cgi?id=1590400) which had the following information: 
> Is the page actually broken? Or is it just reporting failures because we're not using the nonce for the preload check. See bug 1591807.

**Comment by JC5** [comment]
Thanks for the research! :D
