### ISSUE TITLE
Package davejamesmiller/laravel-breadcrumbs is abandoned

### ISSUE THREAD

**Issue by RussellAult** [firefly-iii/firefly-iii#3460]
I'm sure you've already noticed this, but on a fresh install of firefly-iii 5.2.8 I'm getting a composer warning that the package "davejamesmiller/laravel-breadcrumbs" is abandoned.

Thanks!

**Comment by JC5** [comment]
Yes, I'm aware.

**Comment by JC5** [comment]
For now, I'm going to keep the package. It works in Laravel 7. But it requires a switch so I'm actively looking for a replacement.
