### ISSUE TITLE
Apply inactive rule when explicitly executed

### ISSUE THREAD

**Issue by thburghout** [firefly-iii/firefly-iii#3461]
**Description**

Right now, when you have an inactive rule and the user decides to execute it manually, it will not execute the rule. This can be confusing as the user interface indicates that the rule was executed successfully, however the rule will not have had any effect.

I would like to propose that a Rule's "active" property only applies on automatic rule execution, and not the manual execution. So when executing a inactive rule manually, it will still apply the rule.

**Solution**
It would make Firefly even more intuitive to use!

**What are alternatives?**
Display a warning or error when trying to execute an inactive rule.

**Additional context**
It would be great if Firefly were to show the transactions it will mutate before actually mutating them. So the user can have a sanity check. This would add a screen between "Execute" and "Execute success". But this is probably significantly more work to implement :stuck_out_tongue: .

Thanks for this great program!

**Comment by JC5** [comment]
Hi, thanks for the suggestion. I'll make sure that the user interface stops you from executing an inactive rule. Inactive rules are *inactive*, there aren't going to be exceptions.

The sanity check is already possible on the page where you edit rules, and on the index. It will show just a limited set of transactions though.

Thanks for the compliments!

**Comment by thburghout** [comment]
> Hi, thanks for the suggestion. I'll make sure that the user interface stops you from executing an inactive rule. Inactive rules are inactive, there aren't going to be exceptions.

Understandable reasoning! Sounds good to me :+1: .

> The sanity check is already possible on the page where you edit rules, and on the index. It will show just a limited set of transactions though.

Yeah, exactly. The rule I was working with applied to quite old transactions, hence it didn't give me output.

Quick response! If something comes up again I'll create another issue. Keep up the good work :smile:
