### ISSUE TITLE
Transaction for adding money to a piggy bank throws an error and wont proceed.

### ISSUE THREAD

**Issue by rajasiman** [firefly-iii/firefly-iii#3462]
I am running Firefly III version 5.2.6.

**Description**

I wanted to update money in a piggy bank and therefore created a transfer for it.

- Source Account & Destination account are set to the same bank account.
- I select the piggy bank that I want to update from the dropdown that appears on the right.
- Proceed to save the transaction

![image](https://user-images.githubusercontent.com/5812541/84564958-088dc680-ad66-11ea-9179-8ebdcc06c6e7.png)

I also tried making a transaction/withdrawal with the same steps but I was shown the same error.

**Extra info**
 
Debug information generated at 2020-06-13 12:11:32 Europe/Berlin for Firefly III version **5.2.6**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.6 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.17 |
| Display errors | Off |
| Session start | 2020-06-01 00:00:00 |
| Session end | 2020-06-30 00:00:00 |
| Session first | 2020-06-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4166.0 Safari/537.36 |

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [x] I added a screenshot
- [ ] I added log files 
- [x] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
That's not how you add money to a piggy bank.

To add money to a piggy bank, simply press the [+] icon next to the 0% marker.

https://docs.firefly-iii.org/advanced-concepts/piggies
