### ISSUE TITLE
Mass delete expenses and revenue accounts

### ISSUE THREAD

**Issue by damiantje99** [firefly-iii/firefly-iii#3463]
I am running Firefly III version 5.2.8.

**Description**
I was wondering if there is a way to delete all the expenses and revenue accounts in one click, like the mass delete option for transactions.

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by JC5** [comment]
There isn't, no. The danger is that all the associated transactions would be deleted too. If you have a lot of them, you could remove them from the databse directly.
