### ISSUE TITLE
Show all transactions aggrupated in main dashboard or in new view

### ISSUE THREAD

**Issue by dperezq** [firefly-iii/firefly-iii#3465]
**Description**
- I would like Firefly III main dashboard or separate view to show all the transactions aggregated. It would be useful to show sortered by time the income, outcome and transferences done during the last period for all the origin accounts. Right now this is aggrupated by account, but you cannot take a look at all of them quickly. Even in the sidenav menu, when you click on transactions you also see those split by type of transaction (income, outcome, transfer).

This is useful when you have multiple accounts and use all of them in a daily basis.

**Solution**
Table in main dashboard with all the entries in the database. At the end is to aggrupate all the tables shown in the transaction type (income, outcome, transfer) into a single table.

Another solution instead of having this into the dashboard would be to create a new entry in the menu (Transaction option) and add a new view which aggregates all of them in a single table.

**What are alternatives?**
No alternatives. Just going through each option in the menu and take a look separately.

**Comment by JC5** [comment]
Could you use the audit report for this maybe?

**Comment by dperezq** [comment]
There is no option in the audit table to see all the transactions (in the same table). Right now there is a table for each bank account, so they are not aggregated.

Maybe it would be a good option to have here a way to do it, however I still see useful to have it in the main dashboard something similar.
