### ISSUE TITLE
Convering BTC -> PLN rounds the value

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#3466]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:
some time ago I exchanged some PLN to BTC in revolut. I've got some super small amount of bitcoins 0,00077506 BTC. Today I decided to convert back BTC to PLN so I made a transaction but it round the exchange amount of BTC to 0,0008.

**Steps to reproduce**
Create a transaction from BTC to other currency.

**Extra info**
![image](https://user-images.githubusercontent.com/4746858/84672426-d5dffb80-af28-11ea-8125-2ced85f6e343.png)
![image](https://user-images.githubusercontent.com/4746858/84672490-e85a3500-af28-11ea-9c32-2e15dd87c1e2.png)
Tried to reproduce on demo instance, but I was unable.

**Comment by JC5** [comment]
Mmm, not seeing this either. Something specific in the way you run Firefly III?

**Comment by skibbipl** [comment]
Nothing comes to my mind. Language is set to English and locale to Polish.

**Comment by JC5** [comment]
Let's do some hacking. Enter this code:

```php
echo bcscale();
exit;
```

Enter it right after the function definition [in the home controller](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/HomeController.php#L112).

It should say 12.

**Comment by skibbipl** [comment]
Confirmed, I got 12.

**Comment by JC5** [comment]
Crap. I hoped this would be the issue. I got nothing, but I'll do some deep diving.

**Comment by JC5** [comment]
What's the number of decimal places for the currency? 8 right? Could you verify?

**Comment by skibbipl** [comment]
Yes, it's set to 8. I was able to create the correct number on initial conversion.

**Comment by JC5** [comment]
Is it the display? Is the original transaction OK?

**Comment by skibbipl** [comment]
![image](https://user-images.githubusercontent.com/4746858/86464696-5af05080-bd30-11ea-82ca-6ad7c66f6675.png)

**Comment by JC5** [comment]
Mmmmm. `foreign_amount` has the correct number of decimals, but `amount` doesn't. What's the table description? Try `DESCRIBE transactions;`.

Both fields should be `decimal(22,12)`.

**Comment by skibbipl** [comment]
```
postgres=# \c firefly
You are now connected to database "firefly" as user "postgres".
firefly=# \d transactions
                                                Table "public.transactions"
         Column          |              Type              | Collation | Nullable |                 Default
-------------------------+--------------------------------+-----------+----------+------------------------------------------
 id                      | integer                        |           | not null | nextval('transactions_id_seq'::regclass)
 created_at              | timestamp(0) without time zone |           |          |
 updated_at              | timestamp(0) without time zone |           |          |
 deleted_at              | timestamp(0) without time zone |           |          |
 account_id              | integer                        |           | not null |
 transaction_journal_id  | integer                        |           | not null |
 description             | character varying(1024)        |           |          |
 amount                  | numeric(14,4)                  |           | not null |
 identifier              | smallint                       |           | not null | '0'::smallint
 transaction_currency_id | integer                        |           |          |
 foreign_amount          | numeric(22,12)                 |           |          |
 foreign_currency_id     | integer                        |           |          |
 reconciled              | boolean                        |           | not null | false
```

**Comment by JC5** [comment]
Yeps. I'm guessing this is from before Firefly III started to support other currencies; and the database migrations haven't always been.. ideal? 😅 

Make a database backup just in case, and edit the field to be numeric(22,12). Should solve the issue for future and current transactions. After editing them.

Sorry about all the efforts!

**Comment by skibbipl** [comment]
Yup, after altering the amount column transaction is correctly rounded.
