### ISSUE TITLE
'Saving plans left' - View similar to 'Bills to Pay' on Dashboard. 

### ISSUE THREAD

**Issue by JanFeld** [firefly-iii/firefly-iii#3468]
**Description**

I'd like to have view similar to the 'bills' option for 'saving plans'. I've got my own saving plans structured as recurring transactions using multiple accounts and piggy banks. I can see my bills and how much i have left to pay for this month. Something similar would really help me to see how much money i'm required to have left on my main-account to make sure i'm not spending more than i should to satisfy my saving plans.

Currently i have to calculate them by myself as well as i have to think about which saving plans are not served yet. Maybe this is a easy and simple starting point of an optional savings-plan management added to firefly (i'd love to see that!).

I've tried using 'bills' for this but it won't work due to the target account is a saving/asset-account. I couldn't get the rule triggered for linking a transfer to a bill (which is fully understandable and wouldn't make that much sense). Nevertheless an option like this would be amazing. Centralized financial management instead of multiple tools and documents (spreadsheets...).

**Solution**
Add option for 'savings plan' similar to 'bills' and show similar view on dashboard. 
Behaviour could be the same. Rules could be used to link transfers to 'savings plan' entry.

**What are alternatives?**
Remember every savings plans amount and date of transaction and calculate by yourself.

Thanks in advance.

Cheers,
Jan Feld

**Comment by JC5** [comment]
What I do myself is make sure that money intended to be saved never hits my main account to begin with. That's how Firefly III is built. If you budget what you need for bills and food and leave the rest in your savings account, you'll never have to worry about savings plans.

https://docs.firefly-iii.org/about-firefly-iii/personal-finances

**Comment by JanFeld** [comment]
Well from this point of view i'll understand that. My usual way is different.

Usually i'll try to have a base amount of money (e.g. 1000 €) on my main-account, which i don't want to fall below, to have access to just in case of emergency without any additional transactions. (Virtual Balance is great for this).

`Salary -> Main Account`
`Main-Account -> Expenses` over the month
`Main-Account -> Savings-Account X` savings plans with fixed date of transaction
`Main-Account -> Main-Savings-Account` amount on the `Main-Account` above that threshold.

I may *could* see the fixed-date savings like some way of bill so i have to make sure there is money available. But as mentioned above i couldn't manage to link a bill to a transfer. So with your described workflow i'd have to manage the bills like usual and additionally have to observe my budgets to not exceed an specific amount. 

Just to give you an idea of how i'm using firefly. Actually i don't want to change my system due to i'd like to manage things *as is* on real accounts (as far as i can). That way describes the situation best by now.

Nevertheless thanks for clarification!

Cheers,
Jan

**Comment by JanFeld** [comment]
Out of interest.. How do you handle your BIlls in your budget? Do you set the budget-amount to zero or do you just ignore your bills in your monthly budgets? Do you add the exact amount of your bills to the budget?

**Comment by JC5** [comment]
Ah yes. I have my emergency amount on a separate account. Not sure where you're from of course but transferring it to my main is pretty much instantaniously.

I use bills purely for things like rent and insurance. My "bills"-budget is about the sum of all my standard Bills plus a little extra. I'm pretty well aware of which bills will hit me although the quarterly and the yearly sometimes surprise me. I often have a piggy bank for those so I at least have the money. I just used "Backblaze (2020)" for example, because I forgot they charge me in June.

Bills are really meant for expenses which is why you can't link them. Technically speaking the money stays inside the house which is why this is. 

Thanks for clarifying how you use Firefly III. Always nice to hear!
