### ISSUE TITLE
Reconciliation range Parse error

### ISSUE THREAD

**Issue by PiotrStrozekWAT** [firefly-iii/firefly-iii#3469]
I am running Firefly III version 5.2.8.

**Description**
Hi, 
I'm using firefly-iii for more than a year now and since about a mouth when I try to reconcile account I have blank balance fields. 
Browser returned following errors:

The specified value "3711,11" cannot be parsed, or is out of range.
The specified value "3101,48" cannot be parsed, or is out of range.
Uncaught SyntaxError: Unexpected number

This problem shows up only when the balance decimals are different than ,00. 
Also when visiting transaction details the amount skips decimal value and displays ,00, however in dashboard or account details all values are displayed correctly.
Sometimes editing transaction also gives error: transaction.0.ammount must be larger than ":more" 

Firefly is installed on third parties hosting, so unfortunately there are some limitations in server settings. 

Things I did to find solution:
- tried my best in google
- checked on different browsers, desktop and mobile
- checked the locales -a command on server, and it returns long list including pl_PL which I'm currently using.
- fresh install firefly in latest version
- recreated .env file from scratch
- Checked different locales and language settings

Any idea what else I can check to find the reason? Might it be something wrong with database?
 
**Extra info**
Debug information generated at 2020-06-17 09:31:58 Europe/Warsaw for Firefly III version **5.2.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.2.8 |
| Firefly III API | 1.1.0 |
| PHP | 7.3.18 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| Using docker? | false |
| Telemetry | false |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | pl_PL |
| DB drivers | mysql, pgsql, sqlite, sqlsrv |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-06-01 00:00:00 |
| Session end | 2020-06-30 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | pl_PL |
| Attempt at "pl_PL.utf8" | 'pl_PL.utf8' |
| Attempt at "pl_PL.UTF-8" | 'pl_PL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.165 |

**Bonus points**
- I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by JC5** [comment]
I'm sorry, it's something I can't seem to replicate. If you look at the HTML source of the reconcile page, what does it say exactly?

```html
                            <td>
                                <div class="input-group">
                                    <span class="input-group-addon non-selectable-currency-symbol">€</span>
                                    <input type="number" value="4915.75" name="end_balance" class="form-control">
                                </div>
                            </td>
```

(search for "non-selectable-currency-symbol")

**Comment by PiotrStrozekWAT** [comment]
I know it is strange behavior...
The HTML looks like this:
```
<td>
  <div class="input-group">
    <span class="input-group-addon non-selectable-currency-symbol">zł</span>
    <input type="number" value="3101,48" name="end_balance" class="form-control">
  </div>
</td>
```
so basically it's look fine, but in form nothing is displayed. When I add amount by hand it redirect to dashboard.

![image](https://user-images.githubusercontent.com/38287831/84927359-01035000-b0cd-11ea-8006-b7aaf497c7af.png)

I'm not sure if this is relevant but few months ago I was migrating to other server, moving files and database, maybe something went wrong without me noticing it on time. 
Tomorrow I'll create fresh database with sample data, to check if the problem replicate on it.

**Comment by JC5** [comment]
That's very strange. That value specifically was generated by round(), which doesn't use localization.

**Comment by PiotrStrozekWAT** [comment]
So after creating new database with fresh installation of FFIII still balance fields are empty, and decimals are skipped in some of the views. 
I guess it must be something wrong with my host, I'll keep digging but so far no clue

**Comment by PiotrStrozekWAT** [comment]
I think I got something:  In HTML the number is given with comma (,) (3101,48), when I change it using browser editor to dot(.) (3101.48) the number appears in the field - value is displayed with comma (,). 
I checked database table "transactions" and amount value is stored correctly with dot.
Any idea why and where it is changed to comma?

**Comment by JC5** [comment]
Sorry I completely forgot about this issue. But this is a bug, and I'll pick it up as such. Stay tuned!

**Comment by PiotrStrozekWAT** [comment]
Updated the code and it worked like charm, thanks :)
