### ISSUE TITLE
Automated spectre import for known logins

### ISSUE THREAD

**Issue by lfuelling** [firefly-iii/firefly-iii#3470]
**Description**

I've noticed that Spectre logins are saved and saw issues like #1203, #1461 or #1882 that were closed without much information and there is nothing in the docs describing scheduled spectre imports.

**Solution**

Since the interactive login is persisted, it should be possible to add a command line job that imports from Spectre and only receives the id (or pk) of the known login.
This would allow for cron-triggered imports.

**What are alternatives?**

The only alternative that currently exists is to manually import every few days.

**Additional context**

I've read the "[personal finances](https://docs.firefly-iii.org/about-firefly-iii/personal-finances)" part of the docs and I disagree with the following statement:

> You can use the import function and you can use the recurring transactions, but it won't help you one bit.

The first time I gave Firefly III a try I entered all transactions manually from the information I had available from my bank. The main reason I've stopped using Firefly III back then was because the bank only let me see a limited number of transactions which resulted in stuff missing and data making no sense.
After getting the Spectre API to work I also saw that transactions contained more data than what I was able to see by using the tools provided by the bank.

While it's true that it's a good idea to enter transactions manually to get a better feel of things happening, I also think that more (and more complete) data is better if one had to choose between the two.

**Comment by JC5** [comment]
The separate Spectre importer, that works on the command line, supports this. It's still a bit alpha but it should work just fine:

https://github.com/firefly-iii/spectre-importer

**Comment by lfuelling** [comment]
Thanks for the link. 

I got it set up but unfortunately I get a certificate error (and can't create issues in the importer repo):
```
GuzzleException: cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

Is there any way I can let the self signed certificate pass?
