### ISSUE TITLE
Add credit/debt tracking

### ISSUE THREAD

**Issue by ilovelinux** [firefly-iii/firefly-iii#3473]
**Description**
I'd like Firefly III to gandle credit/debt tracking as a separate category.

**Solution**
It would allow more flexibility because not all credit/debts are periodical like bills (for example, when you make credit/debt with a friend) and it would be way easier to track their progress (like remaining moneys to close the credit/debt)

**What are alternatives?**
Actually they must be treat as income/bills.
When you make credits you have to mark it as outcome and every payment as income, vice versa when you make debts.

**Additional context**
Nothing.

**Bonus points**
 :100:

**Comment by JC5** [comment]
If the liabilities don’t fit your use case I’m afraid Firefly III can’t help you.

**Comment by jayenicks** [comment]
> **Description**
> I'd like Firefly III to handle credit/debt tracking as a separate category.
> 
> **Solution**
> It would allow more flexibility because not all credit/debts are periodical like bills (for example, when you make credit/debt with a friend) and it would be way easier to track their progress (like remaining moneys to close the credit/debt)

If I am understanding what you are describing I think making Liabilities for money borrowed/owed to friends would fulfill the same need. Liabilities can (currently) be set to either negative (money loaned) or positive (money owed).

![image](https://user-images.githubusercontent.com/32601491/85137608-14b2d180-b207-11ea-9b35-3904d512d795.png)

Does that fulfill the process you are describing in your request?
