### ISSUE TITLE
Renaming Revenue Account isn't changing name in rules

### ISSUE THREAD

**Issue by jgonsior** [firefly-iii/firefly-iii#3478]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:

If I rename a revenue account which is set as the source for some rules the name of the revenue account isn't changed in the rules as well.

**Steps to reproduce**
1. Create some rules, setting a revenue account as source
2. Rename revenue account
3. Rules are still using the old name 

**Extra info**
I'm running firefly-iii using docker.

**Bonus points**

- I searched and nobody reported this bug before
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2985
