### ISSUE TITLE
What is the mapping feature of CSV-importer made for?

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3480]
**Description**
I couldn't figure out reading docs and issues and testing out myself :-(

**Comment by JC5** [comment]
https://firefly-iii.gitbook.io/firefly-iii-csv-importer/importing-data/map

I thought this was pretty well written, even though I say so myself.

**Comment by totti4ever** [comment]
Wow, that does help a lot. And quite a shame I didn't find it.

Explanation: I was stuck on the JSON explanation, would you mind adding a link there?
```
do_mapping
Whether or not these columns should be mapped to data in your Firefly III installation.

mapping
The mapping. The value in brackets is what's found in the CSV file, the ID links to the account in your Firefly III installation.
```

**Comment by JC5** [comment]
I expanded the page, let me know if it helps! :+1:

https://firefly-iii.gitbook.io/firefly-iii-csv-importer/help/json

**Comment by totti4ever** [comment]
great, helps much from my point of view
