### ISSUE TITLE
Spectre only offering 3 months? 

### ISSUE THREAD

**Issue by dabeeeenster** [firefly-iii/firefly-iii#3481]
I am running Firefly III version Version 5.2.8

Applied for a test account and got this reply:

> Please note the testing environment gives free access to 100 real bank connections for 90 days.

is this normal?

**Comment by JC5** [comment]
Yeah pretty much.

https://docs.firefly-iii.org/importing-data/spectre#spectre-costs

**Comment by dabeeeenster** [comment]
So are people paying for this now? Or what do people do after 3 months?

**Comment by JC5** [comment]
Honestly I don't know. The Spectre API used to have a free API that supported 100 connections max. Which was more than enough for users of Firefly III.

Salt Edge was always willing to support Firefly III users but this has changed over the past few months. Some users may still have "test" access perpetually. But if they're cutting off new users after 90 days that's a bummer.

The pricing tiers start at 500$ per month; and I doubt people are dropping those kinds of amounts just for Spectre API access.

**Comment by dabeeeenster** [comment]
I wonder if they would be open to FF users sort of crowd-funding that amount?
