### ISSUE TITLE
CSV import - Line #0: Internal error: GuzzleException: Server error - 500 Internal Server Error

### ISSUE THREAD

**Issue by chrismast** [firefly-iii/firefly-iii#3482]
Hi,
I got firefly iii up and running via docker on one of my LXC containers incl. the telegram bot.
Wanted to import my YNAB4 data and used the guide to prep the file etc., which seems all to load fine into the CSV loader as it shows my earlier created accounts, budgets and categories as mapping selection fields.
When then running the import it ends with the following error message:

`Error(s)
Line #0: Internal error: GuzzleException: Server error: `GET 172.18.0.2/api/v1/search/accounts?query=Bus&field=name&page=1` resulted in a `500 Internal Server Error` response: {"message":"Internal Firefly III Exception: file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/ (truncated...) in file /var/www/html/app/Services/Import/Task/Accounts.php:312`

Above IP is my internal firefly docker container IP, whereas on my first import I had it showing my actual URL firefly.domain.net.
Token and URL are all set in the container's .env file (via bash into container).

Any suggestion on how to fix above?

**Comment by JC5** [comment]
#3456
