### ISSUE TITLE
Can't import csv file from Kbc (belgium)

### ISSUE THREAD

**Issue by roeleboel** [firefly-iii/firefly-iii#3483]
**Bug description**
On importing files from Kbc bank (belgium) the importer does not recognise the used newlines ('\r').

**Steps to reproduce**
- download a csv from kbc-bank
- try to import it (using ';' as seperator)
-> it will show all data as seperate columns

**Extra info**
docker version of the importer-tool (v1.0.12 at the moment - as of 2020-06-23)
I have checked the file with 'isutf8' from the debian package 'moreutils' to verfify the file is effectivly utf8-encoded, that tools says it is utf8.

**Bonus points**
I think this is because the csv-file is using only a single '\r' (0x0D in hex) as a linebreak.

My suspicion is confirmed by writing a little python program that reads each line, and writes it to another file (so no content is changed but the newlines), and that new file I can import fine.

When I compare these files with a hex-editor, the newlines stand out as different.

If you want a test-file, contact me privately please.

**Comment by JC5** [comment]
I'm sorry, this may not be something that I can fix. The fact that your bank delivers "\r" is also pretty weird to be honest. The libraries I'm using can't detect the \r.

**Comment by roeleboel** [comment]
Is it perhaps possible to add a 'bank specific option' on the configuration page?
Then when the 'kbc' is selected, you could first do a replace all \r by \r\n and continue on?

**Comment by JC5** [comment]
I don’t mind fixing some things but this is overkill. And the first bank I see doing this in 5+years. So no, I’m afraid this isn’t something I’m going to fix. Apart from the effort. This would be an optional extra step in between the upload and the configuration screen. 

Using the “\r” and nothing else? That doesn’t work on Windows or the Mac. Take it up with your bank. They’ll have to join the 21st century.

**Comment by roeleboel** [comment]
Seriously?
Claiming my bank is the problem when even Microsofts own notepad (and any software that matters) opens the file correctly and your software does not?
It is really not that difficult to figure out which software needs correcting...

**Comment by JC5** [comment]
Alright alright I’ll see what I can do. Still your bank’s fault. Christ. Talk about standards.
