### ISSUE TITLE
Polish locale settings not working

### ISSUE THREAD

**Issue by SignumPL** [firefly-iii/firefly-iii#3484]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:
When I change locale to polish, blue bar is displayed:
`Invalid server configuration: Firefly III is unable to format monetary amounts because your server is missing the required packages. `

I have installed polish locale. This is output from `locale -a`:
C
C.UTF-8
POSIX
en_US.utf8
pl_PL.utf8

In config.php of polish locale I have:
`'locale'                  => 'pl_PL.utf8, pl_PL.UTF-8',`

I rebooted system, still doesn't work.
In logs I can see error:
`[2020-06-23 22:32:49] local.ERROR: Could not set locale. The following array doesnt work:  ["pl.utf8","pl.UTF-8"]`

**Steps to reproduce**
1. Go to preferences
2. Change Locale Settings (NOT Language) to Polish

**Extra info**
OS: Raspbian Buster

**Bonus points**

- I searched and nobody reported this bug before
- Feature is disabled on demo site

**Comment by JC5** [comment]
Try "Polish (Polish)".

**Comment by SignumPL** [comment]
So I tried this:
`    'locale'                  => 'pl_PL.utf8, pl_PL.UTF-8, Polish (Polish)',`
and this:
`    'locale'                  => 'Polish (Polish)',`
Restarted nginx and php-fpm services, refreshed the page and still doesn't work. In logs:
`[2020-06-24 09:42:09] local.ERROR: Could not set locale. The following array doesnt work:  ["pl.utf8","pl.UTF-8"] `

Looks like firefly doesn't take into account locale config? Why is it looking for "pl.utf8","pl.UTF-8" despite in config I have 'pl_PL.utf8, pl_PL.UTF-8, Polish (Polish)'?

**Comment by JC5** [comment]
Don’t edit the files. Instead, from the dropdown in your preferences, select “polish (polish)”.

**Comment by SignumPL** [comment]
Damn. I didn't notice there are two "Polish" and "Polish (Poland)" options in the dropdown. It works, thanks :)

**Comment by JC5** [comment]
No worries. In the next release there will be just one choice.
