### ISSUE TITLE
[Bug] Net worth not showing

### ISSUE THREAD

**Issue by TMaddox** [firefly-iii/firefly-iii#3485]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:

My net worth isn't showing any more. It just stays like this:
![image](https://user-images.githubusercontent.com/20703314/85504271-f4f72100-b5eb-11ea-9c04-8fefe018245e.png)

**Steps to reproduce**
Log into firefly

**Extra info**
Windows 10, Firefox, Running firefly with docker and mariadb

**Comment by JC5** [comment]
Check out your logs. I'm pretty sure it's related to #3456

**Comment by TMaddox** [comment]
That will probably be it, I'll let you know once I upgraded to 5.3.0 (once a stable version is available), thanks!
