### ISSUE TITLE
Clicking on report graphs should show the transactions behind

### ISSUE THREAD

**Issue by pbartyik** [firefly-iii/firefly-iii#3486]
**Description**

First off, thanks for maintaining and developing FF III, extremely useful app.
I use tags to mark transactions I spend on my motorcycle and I'm reviewing the last year spending using the tag report.
When I find odd categories I don't remember setting (or no category) for transactions I'd like an easy way to find those transactions.

**Solution**

It'd be easier to just click on the category in the graph to get the transactions in that category.

**What are alternatives?**

Checking transactions based on amount to see what could add up to the sum of the category.

**Additional context**

This would be useful not only for categories but all other report graphs too.

**Bonus points**
![example1](https://user-images.githubusercontent.com/39059618/85523057-c5a1dd80-b606-11ea-9d8c-46f23cf0bf73.png)
Click on orange, see expenses within category represented by orange for the specific tag:)

**Edit**
I can see that report improvements are on the roadman, can this be included please?
https://github.com/firefly-iii/firefly-iii/projects/5#card-19947339

**Comment by JC5** [comment]
Good idea, I'll see what I can do. It depends on the library.

**Comment by bannisdale** [comment]
Came here to propose the same thing. :) Most graphs would be quite a bit more useful if they would be clickable. So when I go to expenses and see a big chunk of expenses being in a certain category (e.g. eating out), I might be interested in why the hell I spent so much money on it. ;-) Right now, I have to go to the sidebar, choose categories, then click the category in question. Same for tags, accounts etc.

**Comment by JC5** [comment]
Probably not going to happen, just FYI. I need to expand the charts with *a lot* of meta data to get the right identifiers or URL's in the right place. 

Let's take a bar chart for example, like the one on the frontpage. It's a single series, "spent in categories", with a lot of values: 100, 10, 14.32, etc. The labels are the categories: Shopping, Bills, Going out, etc. Together, they form the chart.

Either I have to add another array of meta data like category ID's or I have to do a complicated lookup (through the API) to get the right ID so I can forward the user. This adds a lot of complexity for a single click.

I'm already working on a new layout, so this idea can still go live. But right now, it's not going to happen.
