### ISSUE TITLE
Editable Personal Access Token

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#3488]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:

When creating a new personal access token, I am able to edit the text field. Subsequent creation of new personal access token will fail. Steps to reproduce: 

1. Go to `/profile` page
2. Click `Create new token`
3. Give a random name
4. Edit `Personal Access Token` field
5. Click `Create new token` again
6. Give a random name
7. Create

![image](https://user-images.githubusercontent.com/5896415/85657773-ca918a80-b6f5-11ea-9d10-7ec5b5a6440c.png)

**Comment by emansih** [comment]
Bug 2: There is no input validation when creating a new token which means I am able to create  the same name multiple times

**Comment by emansih** [comment]
This is a security flaw as I can no longer create tokens :(.

**Comment by emansih** [comment]
This is a security flaw as I cannot create Personal Access Token anymore :(

**Comment by JC5** [comment]
Thanks for the research. I think I can make it all a little more robust. Most of the code pipes directly into the Passport library of Laravel. As such, I'm not sure if I can fix the duplicate name thing although honestly I don't care much: the problem is mainly self-inflicted.

**Comment by JC5** [comment]
I made the field readonly. That basically solves the problem. The duplicate name thing however, I don't think I can fix it.
