### ISSUE TITLE
Account name not showing when created using JS code 

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#3489]
**Bug description**
I am running Firefly III version 5.3.0-alpha1 (on the demo site) and my problem is:

Account name is not shown 
![image](https://user-images.githubusercontent.com/5896415/85662584-68d41f00-b6fb-11ea-804d-cee81d129081.png)

Steps to reproduce:
1. Click on create new asset account
2. Use `<script>alert("firefly")</script>` as the account name
3. create account
4. click on account details `(/accounts/show/<id>)`

**Comment by JC5** [comment]
Thanks for letting me know. Unescaped JS code is blocked by the Content Security Policy header. So although it's a bug (the title should have been escaped), it's fairly harmless.
