### ISSUE TITLE
[5.3.0-alpha.1] Undefined offset: 0 in /piggy-banks

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3491]
**Bug description**
After switching from standard installation to Docker and upgrading to 5.3.0 I get this error in /piggy-banks:
 ```
local.ERROR: Undefined offset: 0 {"userId":2,"exception":"[object] (ErrorException(code: 0): Undefined offset: 0 at /var/www/firefly-iii/app/Http/Controllers/PiggyBank/IndexController.php:161)
[stacktrace]
#0 /var/www/firefly-iii/app/Http/Controllers/PiggyBank/IndexController.php(161): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/firefly-iii/app/Http/Controllers/PiggyBank/IndexController.php(120): FireflyIII\\Http\\Controllers\\PiggyBank\\IndexController->makeSums()
#2 [internal function]: FireflyIII\\Http\\Controllers\\PiggyBank\\IndexController->index()
```
I thought it'd be because of my backup strategy being messed up but it seems everything else works fine.
I'm sorry I don't have time to look at the code for the moment.
Can it be that for some reason my former piggy banks did not get assigned to a default group while migrating leading to $sums being empty?

**Comment by JC5** [comment]
It’s the latter. A fix is in the develop branch somewhere.

**Comment by JC5** [comment]
Alright long answer: not sure what I broke, but I think it happens when the (ungrouped) list in empty. I pushed a fix [here](https://github.com/firefly-iii/firefly-iii/commit/7617fe35104484fc4b1b56c0b6adb23bd7f64c89) but that's not part of alpha.1.

I think this weekend will feature beta.1 in which this issue shall be fixed :)

**Comment by JC5** [comment]
Beta 1 is out, and this should be fixed :)

**Comment by sephrat** [comment]
Confirmed fixed, thanks! FYI all the piggy banks in my database were marked as deleted. I guess that was unexpected. :-)
