### ISSUE TITLE
Spectre 'CustomerNotFound' error for wrong ID?

### ISSUE THREAD

**Issue by SniperAsh6** [firefly-iii/firefly-iii#3492]
I am running Firefly III version 5.2.8 on a Raspberry Pi 4

**Description**
I've got a clean install trying to use Firefly for the first time and have a Salt Edge account with test access. Trying to add Spectre I've added a new Service in the Salt Edge settings using the public key from Firefly. I've then pasted the App ID and Secret from the Salt Edge Service back into Firefly but then pressing the 'Import using Spectre' button nets me an error saying:
```
Fatal error

The import has suffered from an error it could not recover from. Apologies!

Job could not be started or crashed: The import routine crashed: Guzzle Exception: Client error: `GET https://www.saltedge.com/api/v4/logins/?from_id=0&customer_id=1023412352` resulted in a `404 Not Found` response: {"error_class":"CustomerNotFound","error_message":"Customer with id: '1023412352' was not found.","request":{"from_id":" (truncated...)

This (possibly very cryptic) error message is complemented by log files, which you can find on your hard drive, or in the Docker container where you run Firefly III from.
```

Having checked the log for the docker container there isn't really anything extra logged that I can see.

The customer ID from the error message does not match the ID of the customer created when the Service was added in Salt Edge. I can't work out where it's getting this value from or what else I'm missing so any help greatly appreciated.

**Extra info**
I've tried `delete from preferences where name LIKE 'spectre%';` in the DB as suggested in #2183 but it didn't make any difference. Noticing the customer ID is in the `spectre_customer` row I tried updating the customer ID in there to what's in the Salt Edge customers section but that didn't help either.

***Debug Info***
Debug information generated at 2020-06-27 01:20:32 Europe/London for Firefly III version **5.2.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.2.8 |
| Firefly III API | 1.1.0 |
| PHP | 7.4.6 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| Using docker? | true |
| Telemetry | false |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_GB |
| Default locale | equal |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-06-01 00:00:00 |
| Session end | 2020-06-30 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0 |

**Comment by JC5** [comment]
You could try to clear your cache by browsing to the `/flush` URL of your browser. But if that doesn't work, you'll have to switch over to the separate [Spectre importer](https://github.com/firefly-iii/spectre-importer).

**Comment by SniperAsh6** [comment]
Sorry, I should have added that after each thing I tried I did also visit `/flush`. I'll try the seperate importer and report back, thank you

**Comment by SniperAsh6** [comment]
So far running the Spectre Importer using the run-hosted script is resulting in being told the personal access token is invalid so I'm trying to see why it's unhappy. I know I've got the IP right and there's seemingly nothing wrong with the access token I've copied across - no spaces or anything else at the start or the end

**Comment by JC5** [comment]
Mmm. The personal access token is very long and starts with ey. Also no newlines?

**Comment by SniperAsh6** [comment]
I did get slightly further that the message about the personal access token is wrong, the real error is a timeout and it's because docker is creating the Spectre Importer container on a different subnet to the Firefly III ones

**Comment by SniperAsh6** [comment]
Creating the Spectre Importer container through Docker puts it on the 172.17.0.0/16 subnet

I'm using Firefly through docker-compose which seems to put everything on 172.18.0.0/16 and also increment each time the containers are brought down and back up again so next time they use 172.19.0.0/16 and so on

**Comment by SniperAsh6** [comment]
Any thoughts on how I might work around the above please @JC5?

**Comment by JC5** [comment]
For the customer not found error, try removing the customer at Spectre; all customers that are listed there. The Spectre importer will create a new one. For the subnet error, I'm not really sure. Does Docker have some documentation on it?

**Comment by SniperAsh6** [comment]
I've added the Spectre Importer to my docker-compose file and got slightly further because it now has the ability to communicate with the firefly container.

The error I now get with the importer is from `/import/spectre-connections` which is just a 500 server error. Looking at the container logs I see I'm pretty much back to where I started at the beginning:
`production.ERROR: CustomerNotFound: Customer with id: '2147483647' was not found. {"exception":"[object] (App\\Exceptions\\ImportException(code: 0): CustomerNotFound: Customer with id: '2147483647' was not found. at /var/www/html/app/Http/Controllers/Import/ConnectionController.php:123)
[stacktrace]`

The customer ID it seems to be looking for is int max so could it be that the Salt Edge Customer ID overflows what fits in an int?

**Comment by JC5** [comment]
Hah, that would be pretty amazing. I’ll do some research after the weekend to see what’s going on.

**Comment by SniperAsh6** [comment]
Nice one, thank you. If it helps my customer id on the salt edge platform is 18 digits so it seems more than a coincidence it's looking for the max signed int 32 value

Let me know if there's anything else I can offer that'll help. Once resolved I'll make my docker-compose file available to help others get this up and running

**Comment by SniperAsh6** [comment]
That's done the trick, thank you. I've just been able to create a connection and import into Firefly

**Comment by JC5** [comment]
Thanks for the feedback, it's much appreciated. For now, keep using develop, a new release should be out soon.

**Comment by SniperAsh6** [comment]
Will do, thanks. I'll make my docker-compose file available soon too, would it be useful to send a link your way?

**Comment by JC5** [comment]
Absolutely. I'll include it in the docs :+1:
