### ISSUE TITLE
firefly broke after selecting equal to language in local setting

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#3494]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:

I got this error after selecting the  first option (equal to language in the local setting

file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/1e/ec/1eec4963bab8b841ffb7fb1520b1e3d273657f1d): failed to open stream: No such file or directory 

**Steps to reproduce**

**Extra info**

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
I think this has to do with #3456.

I'm not making this easier for you, am I? All I can do is congratulate you for hanging on :D

**Comment by bartmaniac** [comment]
I deleted my 2 containers (I thougt I did) but after doing again the command docker-compose -f docker-compose.yml up -d 
i get the login screen but putting in my credentials gives me again 
Oeps! Er is een fout opgetreden.
Helaas was deze fout niet te herstellen :(. Firefly III is stuk. De fout is:

file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/1e/ec/1eec4963bab8b841ffb7fb1520b1e3d273657f1d): failed to open stream: No such file or directory

It seems that noyt everything was deleted because in the logs I can see an account name I set up previously.

**Comment by JC5** [comment]
Make sure you remove the associated volumes as well.

**Comment by bartmaniac** [comment]
ok I managed to get it installed by installing 5.3.0beta1. Now the problem is when I choose Nederlands (België) 123,78 is diplayed as 12378. When I switch to Nederlands (Nederland) it is displayed as 123,78. But 123.456,78 will be displayed as 123456,78. I read about instructions but don't understand them well


Ensure with dpkg-reconfigure locales that the language you want to use is installed, then reboot Apache or Nginx (webserver) and if necessary, PHP FPM.

do i have to enter the container (docker exec -it containerID /bin/bash ?

Truncated from this point <----|[2020-06-29 02:27:15] local.WARNING: No database version entry is present. Database is assumed to be OLD (version 1).  
[2020-06-29 02:29:41] local.ERROR: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
"  
[2020-06-29 02:35:32] local.ERROR: Could not set locale. The following array doesnt work:  ["nl_BE.utf8","nl_BE.UTF-8"]

**Comment by JC5** [comment]
Try the following:

```
 docker exec -it --user root [container] bash
```

Then, in the container:
```
echo "nl_BE.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
service apache2 reload
```

I'll update the documentation about this :)

**Comment by bartmaniac** [comment]
sorry for late reply. Thanks JC5 ! it works!
