### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by Agraphie** [firefly-iii/firefly-iii#3496]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:

I cannot upload "bigger" files as attachments. It works with smaller files (e.g. 68KB or 710KB), but not with 6 MB. Unfortunately, I don't get any error and according to the php.ini the file upload max size should be 64 MB.

**Steps to reproduce**
Try to upload a file with 6 MB.

**Extra info**
I could not reproduce it on the demo site as it doesn't allow file uploads it seems?

Any ideas? I checked the debug logs but did not see any error or hint.
[cli-log.txt](https://github.com/firefly-iii/firefly-iii/files/4842249/cli-log.txt)

**Comment by JC5** [comment]
It could be something in the webserver config. Max client body size or something?

**Comment by Agraphie** [comment]
Sorry I should have added that I'm using the docker config. So for Apache inside the docker image I didn't find `LimitRequestBody` (afaik that's the one to limit the size?).

As reverse proxy I'm using nginx and there is no limit set.

Strangely enough firefly is showing me that the transaction has an attachment (in the transactions overview), but once I click on the transaction no attachment is shown.

**Comment by Agraphie** [comment]
Just checked again and the default size for nginx requests is 1 MB. Who knew. Once I changed that it works. Thanks!

**Comment by JC5** [comment]
:+1:
