### ISSUE TITLE
csv import mapping results in 500 internal server error

### ISSUE THREAD

**Issue by Rickth64** [firefly-iii/firefly-iii#3499]
**Bug description**
I am running Firefly III version 5.2.8 with version 1.0.13 of the csv importer tool. Whenever I try to import a csv file from my bank, it results in a 500 server error, seemingly from firefly-iii itself. Previous attempts did succeed.

**Steps to reproduce**
- Go to the csv importer web interface
- Select 'start here'
- Import csv file and json config (rabobank)
- Leave defaults in place (from json config)
- Whenever it attempts to load the csv for the mapping page, the error shows

**Extra info**
- I have added a stack trace from my docker log files, see https://pastebin.com/SkRaM4C6

Debug information generated at 2020-06-30 08:46:34 Europe/Amsterdam for Firefly III version **5.2.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.2.8 |
| Firefly III API | 1.1.0 |
| PHP | 7.4.6 |
| Host | Linux (Docker) |

| System info | Value |
| --- | --- |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| Using docker? | true |
| Telemetry | false |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-06-01 00:00:00 |
| Session end | 2020-06-30 23:59:59 |
| Session first | 2014-01-01 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 |

**Comment by JC5** [comment]
See #3456.
