### ISSUE TITLE
CSV importer - Error 500

### ISSUE THREAD

**Issue by pedrom34** [firefly-iii/firefly-iii#3501]
**Bug description**
I am running Firefly III version 5.3.0-beta.1, csv-importer version 1.0.13, both on self-hosted server (no docker) and my problem is that when I go to http://192.168.0.11/csv-importer/public, I got an error 500:
`Argument 1 passed to GrumpyDictator\FFIIIApiSupport\Request\Request::setTimeOut() must be of the type float, string given, called in /var/www/csv-importer/app/Http/Controllers/TokenController.php on line 94`

My .env file looks like this:
FIREFLY_III_ACCESS_TOKEN=XXX
FIREFLY_III_URI=http://192.168.0.11:4321

(that 4321 port is my virtual server in apache for my firefly-iii instance).

I check the closed issues here, but nothing helps me to understand what I'm doing wrong?

Thanks!

**Comment by JC5** [comment]
I don't think you're doing anything wrong. This is an unexpected bug (my fault). I'll see if I can fix it on a short term. Sorry about this!

**Comment by pedrom34** [comment]
Don't be sorry James! You're offering a damn good piece of software to the world 😄 

If you need me to give you more info, don't hesitate.

**Comment by JC5** [comment]
I just pushed 1.0.14 that should have a fix! :+1:

**Comment by JC5** [comment]
Glad to hear it 😁
