### ISSUE TITLE
Missing icons?

### ISSUE THREAD

**Issue by logantalley** [firefly-iii/firefly-iii#3503]
Version: 4.7.1.3

For whatever reason, I get this result when running this as installed on my server under nginx:
https://i.imgur.com/nCX1Q1p.png

Any ideas?

Running on Ubuntu 18.04.

**Comment by JC5** [comment]
Firefly III v4.7.1.3 is over two years old. I suggest you upgrade to a more recent version.

**Comment by logantalley** [comment]
Yep, that did it. Thanks!
