### ISSUE TITLE
Trigger auto import on call to route

### ISSUE THREAD

**Issue by iamjackg** [firefly-iii/firefly-iii#3504]
**Description**
I would love for the CSV importer to expose an API route that will trigger the auto-import process from a specified folder.

When using the Docker setup, having to use the command line to trigger an auto-import job forces my automation scripts to run as root (or be in the docker group, which is effectively the same thing) in order to be able to talk to the Docker daemon.

Having an exposed route would instead allow me to:

- `scp` new files over to the mapped volume
- call an `/autoimport` route to trigger the same auto-loading behaviour that is accessible form the command line, optionally with some POST data to specify the folder

**Comment by JC5** [comment]
I'll think about it. I like the idea, but it needs authentication.

**Comment by JC5** [comment]
Then again, the CSV importer also has no auth.

**Comment by iamjackg** [comment]
Yeah, that was sort of my train of thought too. :smile:

**Comment by JC5** [comment]
Will be part of the new release. Only works when you're using the personal access token method, and it isn't documented yet. POST to `/autoimport` with an optional `directory` argument.

**Comment by iamjackg** [comment]
Awesome, thank you so much!

**Comment by iamjackg** [comment]
I finally got around to trying this today and it worked perfectly. Thank you very much!
