### ISSUE TITLE
Auto Budget topup every month

### ISSUE THREAD

**Issue by au007653** [firefly-iii/firefly-iii#3505]
I am running Firefly III version 5.2.6

**Description**
I have setup Budgets to "Add an amount every period". The period is Monthly however today on the first of the month it did not auto add amounts to all of my budgets.? What am I missing.

 I have the cron setup as /usr/local/bin/php /home/*******/public_html/firefly/artisan firefly-iii:cron  and it is set for 3am each day. I can see the cron is firing.

![AutoBudget](https://user-images.githubusercontent.com/67663659/86184542-c80cb600-bb77-11ea-9133-25338aa041a2.jpg)

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by dugite-code** [comment]
Have you [set up the cronjob?](https://docs.firefly-iii.org/advanced-installation/cron#cron-job-that-requests-a-page). Without something calling the cronjob firefly cannot run the recurring budget rules

**Comment by JC5** [comment]
Could you share some log entries?

You can force the cron job to fire again with the following command: `php artisan firefly:cron --force --date=2020-07-01`

**Comment by au007653** [comment]
> 
> 
> Could you share some log entries?
> 
> You can force the cron job to fire again with the following command: `php artisan firefly:cron --force --date=2020-07-01`

Hi JC5,
Where abouts can I find the Cron logs?? I looked in the Firefly folders but couldn't see any??

**Comment by au007653** [comment]
> 
> 
> Could you share some log entries?
> 
> You can force the cron job to fire again with the following command: `php artisan firefly:cron --force --date=2020-07-01`

JC5,
The cron email I receive say's :
The recurring transaction cron job fired successfully.
The auto budget cron job fired successfully.
More feedback on the cron jobs can be found in the log files.

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://docs.firefly-iii.org/contact/contact).
