### ISSUE TITLE
Tags not showing all transactions

### ISSUE THREAD

**Issue by kungfu71186** [firefly-iii/firefly-iii#3509]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:
I am using importer to import some transactions. It appears I made a boo boo and did the date wrong. So, the dates are actually in the future. It doesn't appear that I can get all the transactions with that label no matter the date, even if I do custom range. If I create a new transaction (not using importer) and set a date in the future, add a tag and select everything, that transaction shows up. Then when I go to the tag that I am having issues with, all the transactions now show up. 

It's like the query is being limited by today's date no matter what, unless I create a transaction manually.

**Steps to reproduce**
Use importer to import transactions with future dates. Go to the tag and show everything. 

I'm not sure how reproducible this is, but it happened to me a few times.

**Comment by JC5** [comment]
Nicely spotted. A fix will be present in the next release :+1:

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/releases/tag/5.3.0-beta.2
