### ISSUE TITLE
Add spaces to notes in rules

### ISSUE THREAD

**Issue by kungfu71186** [firefly-iii/firefly-iii#3510]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:
I am trying to add a newline and append some text to a note. Not sure if it's possible, but I was trying to add 2 white spaces in front. It appears the text gets trimmed and the spaces are removed.

**Steps to reproduce**
Create a rule of any kind. Create an action set to Append notes with... and in the action value add any number of spaces in front of it, plus text. Save or update the rule. Go back and edit the rule and the spaces are now removed.

I can see the value of trimming whitespace, but if using markdown and wanting to append or prepend text, it would be nice to allow whitespace. So not sure if bug or feature. Even allowing special text like \s for spaces would be fine.

**Comment by JC5** [comment]
For notes, that's going to be tricky. I'll see what I can do but the way rules work + notes, you're hitting the limits I'm afraid.

**Comment by JC5** [comment]
There's no way to do this neatly I'm afraid. Sorry.
