### ISSUE TITLE
Transaction link

### ISSUE THREAD

**Issue by kungfu71186** [firefly-iii/firefly-iii#3511]
**Description**
It doesn't seem like I can submit an issue for the csv-importer, so hopefully it's appropriate here.

Currently, when importing transactions using the csv importer, it outputs a message for all the transactions imported. It creates a link that will show that transaction. It looks like it appends the uri to the importer uri. Meaning if you are hosting firefly on localhost:8080 for example and the importer on localhost:8081, the link will look something like:

http://localhost:8081/{uri}/transactions/show/9999

where uri is the environment variable FIREFLY_III_URI. It would be nice to be able to fix the urls to point to a custom url, as the FIREFLY_III_URI may not be the same as the external name if using something like docker.

**Solution**
Add another Environment variable to override URL. Something like FIREFLY_III_EXTERNAL_URI and then set the url to be:
{FIREFLY_III_EXTERNAL_URI}/transactions/show/{transaction_id} instead. If not defined, then maybe both the URI and External URI will be the same.

**What are alternatives?**
Manually fix the url when opening the link

**Comment by JC5** [comment]
Not a bad idea. An optional extra setting somewhere. I’ll write it down as an enhancement and pick it up. 👍

**Comment by kungfu71186** [comment]
Just going over the code a bit to get more familiar. Wanted to expand a bit on this solution:

Update config
https://github.com/firefly-iii/csv-importer/blob/27d48ce0dc9d1e4c9c75a4832ce8bda80f93c974/config/csv_importer.php#L44
`'uri_external'                 => env('FIREFLY_III_URI_EXTERNAL', env('FIREFLY_III_URI')),`

Then i believe it's here, update the message:
https://github.com/firefly-iii/csv-importer/blob/5ed6e12e3873032b1a49150165fae1e344443af4/app/Services/Import/Routine/APISubmitter.php#L211
`$uri_external      = (string) config('csv_importer.uri_external');`

https://github.com/firefly-iii/csv-importer/blob/5ed6e12e3873032b1a49150165fae1e344443af4/app/Services/Import/Routine/APISubmitter.php#L263
`sprintf('%s/transactions/show/%d', $uri_external, $group->id),`

**Comment by JC5** [comment]
The new CSV importer (and all the others) will have this feature. Check out the [.env.example file](https://github.com/firefly-iii/csv-importer/blob/develop/.env.example#L23) in the develop branch for details.

I'll try and release this weekend.

**Comment by JC5** [comment]
All importers now have this.
