### ISSUE TITLE
Displaying budget details over a past period shows less data

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3513]
**Bug description**
https://demo.firefly-iii.org/budgets/show/1/ shows graphs.
https://demo.firefly-iii.org/budgets/show/1/13 shows no graph although there should be data to display. Also, source and destination accounts are not displayed in the list - probably related issues, although categories are displayed fine in the list but its graph is still missing.
![image](https://user-images.githubusercontent.com/34862846/86267070-70496b80-bbc6-11ea-8b93-dfcc28e49fa4.png)

I can pick it up when I'm less busy (hopefully later this month), just writing it down to keep track of it.

**Comment by JC5** [comment]
I might just pick this up earlier so I can put it into 5.3.0. Is that ok with you?

**Comment by sephrat** [comment]
No problem, to be honest I'd be happy to have it fixed quick. :-)

**Comment by JC5** [comment]
Appreciate it. I wonder what I messed up 🤔

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/releases/tag/5.3.0-beta.2
