### ISSUE TITLE
"No app.json located in the repo URL provided" on Heroku.

### ISSUE THREAD

**Issue by andrewkhardy** [firefly-iii/firefly-iii#3515]
**Bug description**
I am running Firefly III , and my problem is:

when I attempt to host on Heroku (https://elements.heroku.com/buttons/firefly-iii/firefly-iii) 

I received this error 
"No app.json located in the repo URL provided"

**Comment by JC5** [comment]
The file is right there, but the branch name has changed. Try this URL:

https://heroku.com/deploy?template=https://github.com/firefly-iii/firefly-iii/tree/main

**Comment by andrewkhardy** [comment]
built after this! Thanks for the quick response.
