### ISSUE TITLE
A few enhancement ideas

### ISSUE THREAD

**Issue by chrismast** [firefly-iii/firefly-iii#3517]
@JC5 , first of all, huge thanks for this tool. Works very well for me, coming from YNAB4 looking for an alternative as YNAB4 gets quite old and no idea how long the dropbox sync link will work.
After using Firefly III for about a month, had a few enhancement ideas, if they were already discussed/or they do not make sense in your grand plan, please disregard:

### 1. Adding transactions via the account overview page
 At the moment it is not possible to add transaction when viewing just one account. Adding this capability might be helpful when for instance doing reconciliation on account level and then being able to quickly add a transaction instead of going back to the transaction module.

### 1. Adding transaction via the reconciliation feature
This could be solved by 1a, whereas once in the reconciliation menu and going through transactions, it is not possible, without going back out, to add transactions. It happens though that you might not add all transactions all the time (i.e. credit card) and hence the reconciliation will have gaps. This results then in (1) recording all missing transactions on paper and (2) going back, entering them, then going back again to reconciliation.

### 2. Showing transactions when clicking on a chart
Think saw this requested before somewhere, but it would be great to see all transactions behind a bar chart when clicking it.

### 3. Remove "income" or "un-categorized spend" from the category dashboard chart
Once entering an income, i.e. salary, the category bar chart shows it either as "category name, i.e. salary" or "un-categorized". Due to the fact the salary is normally a lot higher (as it is one amount) compared to other spend shown, it will dwarf the other spend and make it hard to read. I would think monitoring spend on this chart is a lot more important than income (as this only happens once, bi-weekly, weekly). Removing this category/income from the chart would make the expenses readable.

### 4. Telegram bot addition
Know this is not your telegram bot, but thought I group it all in one and cross it over later.
But it would be good to also be able to enter the account in the telegram entry so that it is not only bound to one account defined. This will help with transactions automatically in the correct account that for instance vary in where they are charged from.

Again, if above does not make sense, please close and disregard. Hope it helps though!

**Comment by JC5** [comment]
Hi! Thanks for all of these suggestions:

1: Every page has a little + button in the top right corner. Does that help?
2: Yes. Not going to happen on the short term, and not in all charts. I haven't checked if the library supports it though.
3: Agreed. Lots of people requested it to be *added* but it makes the chart pointless.
4: Not my bot :wink:

**Comment by chrismast** [comment]
1: Yeah the plus helps I guess.
2: ok.
3: Not sure if I understand what you mean with "chart would be pointless".
4: Understood, just wanted to sum it up her and reference it over at his github ;-)
