### ISSUE TITLE
Issue running csv-importer from subdirectory

### ISSUE THREAD

**Issue by aman207** [firefly-iii/firefly-iii#3521]
I am running Firefly III CSV importer version 1.0.14, nginx version 1.18.0, php version 7.4.6

**Description**
I am getting 404 errors when I try to run the csv importer from a subdirectory ("csv" in this case). I can see from the network tab that it initially loads fine, tries to redirect to `...csv/token/validate`, and then returns a 404. It then goes to `...csv/token`, returns and shows a 404. Here's the .har if you wanted to see for yourself. [Attached](https://github.com/firefly-iii/firefly-iii/files/4870058/firefly.home.local_Archive.20-07-03.07-52-16.zip)

It appears that the 404 I see ([Image here](https://imgur.com/a/z9N38KR)) is loading assets from the main firefly instance. This is the first CSS that gets loaded `http://firefly.home.local/v1/lib/bs/css/bootstrap.min.css?v=`. There is no subdomain in this path.

I've tried playing around with the `ASSET_URL=` section of the .env but it doesn't seem to do anything

The only output to the csv-importer log file is this line: `[2020-07-03 08:16:59] local.DEBUG: Now at App\Http\Controllers\IndexController::index`  
There is no log output from the main firefly instance with debug logging enabled.

If I setup the csv importer to run from a subdomain, it works fine. I'm guessing its an issue with my configuration, but I can't figure out where the issue is. Any insight would be helpful.

**Extra info**

[My nginx config](https://gist.github.com/aman207/6148050ed72e46bf842b0d9c83dc6763)  
[My csv-importer .env](https://gist.github.com/aman207/ed946e282986ef71fe5f64507b973b76)  
[.har](https://github.com/firefly-iii/firefly-iii/files/4870058/firefly.home.local_Archive.20-07-03.07-52-16.zip)  
[One of the 404s](https://imgur.com/a/z9N38KR)

**Comment by JC5** [comment]
Hi! Thanks for opening the issue.

The 404 you're getting is a Firefly III 404 not one from the CSV importer. So something is messed up. Are you sharing host names between Firefly III and the CSV importer?

 I have no idea what a har file is I'm afraid

**Comment by aman207** [comment]
> 
> 
> Hi! Thanks for opening the issue.
> 
> The 404 you're getting is a Firefly III 404 not one from the CSV importer. So something is messed up. Are you sharing host names between Firefly III and the CSV importer?
> 
> I have no idea what a har file is I'm afraid

Thanks for the quick response.
Yes, I am sharing hostnames and trying to run CSV importer from a subdirectory. 

You can import the .har into your web browser (firefox in my case) and see the network trace. Go to Developer tools > Network tab > Gear icon > Import HAR.

**Comment by JC5** [comment]
Running them on the same hostname is kind of out of my league, and not really supported by the framework, as far as I know. Not sure what the best course of action is.

**Comment by aman207** [comment]
> 
> 
> Running them on the same hostname is kind of out of my league, and not really supported by the framework, as far as I know. Not sure what the best course of action is.

I see, no worries. I think the best course of action is to use a different hostname. It works fine with a different subdomain, but I wanted to use the same hostname/subdomain simply for aesthetics. 

Thanks anyways!

**Comment by aman207** [comment]
Aha! I'm stubborn so I kept trying, but its working now. 

This is the working nginx config. The secret was to use a named location block with a rewrite rule. 
https://gist.github.com/aman207/913e9b5e330c6bf04ba25e5dfd1d311f

This website has a great explanation for why this works. https://serversforhackers.com/c/nginx-php-in-subdirectory
