### ISSUE TITLE
Amounts multiplied by 100

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [firefly-iii/firefly-iii#3524]
I am running Firefly III version 5.2.8 and it started to display all values (expenses, assets accounts etc. as if they were multiplied by 100, e.g.: a 10 € expense becomes a 1000€ one.)
Now I wonder, why is it happening?
Thank you in advance, this software is great by the way!

Debug information generated at 2020-07-04 00:21:48 Europe/Amsterdam for Firefly III version **5.2.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.2.8 |
| Firefly III API | 1.1.0 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| Using docker? | false |
| Telemetry | false |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 2 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 |

**Comment by JC5** [comment]
It can happen when the right locale packages aren't installed. It seems that's OK though:

https://docs.firefly-iii.org/faq/self_hosted#decimal-points-are-missing-numbers-are-off

**Comment by gianmarcoodorizzi** [comment]
Thanks, another software I installed messed up with apache's envvars. I had to:

`## Uncomment the following line to use the system default locale instead:
. /etc/default/locale
`

Thank you again and keep up the good work!

**Comment by JC5** [comment]
You're welcome, and will do!
