### ISSUE TITLE
Installation not working with docker compose

### ISSUE THREAD

**Issue by tenklo** [firefly-iii/firefly-iii#3525]
I am running Firefly III version 5.3.0

**Description**
I followed the installation guide using docker compose. After completing the installation and trying to open firefly for the first time, I am welcomed by the whoops error page, Error being 
''Trying to get property 'data' of non-object''
''This error occured in file /var/www/firefly-iii/app/Http/Controllers/Controller.php on line 58 with code 0. ''

**Extra info**
I set up everything on a Raspberry Pi 4 4Gb running raspbian. Trying to open in Firefox on Arch. 
Also this is my first time trying firefly-iii, as well as the first time trying anything with docker.  

**docker-compose.yml**
''services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 8765:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=securepw
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    ports:
      - 3307:3306

volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:
''
**.env**
''
APP_DEBUG=true
SITE_OWNER=someemail
APP_KEY=securekey
DEFAULT_LANGUAGE=en_US
DEFAULT_LOCALE=equal
TZ=Europe/Amsterdam
TRUSTED_PROXIES=
LOG_CHANNEL=stack

APP_LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=fireflyiiidb
DB_PORT=3306
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD=securepw

MYSQL_USE_SSL=false
MYSQL_SSL_VERIFY_SERVER_CERT=true
MYSQL_SSL_CAPATH=/etc/ssl/certs/
MYSQL_SSL_CA=
MYSQL_SSL_CERT=
MYSQL_SSL_KEY=
MYSQL_SSL_CIPHER=

PGSQL_SSL_MODE=prefer
PGSQL_SSL_ROOT_CERT=null
PGSQL_SSL_CERT=null
PGSQL_SSL_KEY=null
PGSQL_SSL_CRL_FILE=null
''

Debug page: 
'' Stack trace
#0 /var/www/firefly-iii/app/Http/Controllers/Controller.php(58): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/firefly-iii/app/Http/Controllers/DebugController.php(56): FireflyIII\Http\Controllers\Controller->__construct()
#2 [internal function]: FireflyIII\Http\Controllers\DebugController->__construct()
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(845): ReflectionClass->newInstanceArgs()
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\Container\Container->build()
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve()
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Foundation\Application->resolve()
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make()
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(253): Illuminate\Foundation\Application->make()
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(970): Illuminate\Routing\Route->getController()
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(931): Illuminate\Routing\Route->controllerMiddleware()
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\Routing\Route->gatherMiddleware()
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->gatherRouteMiddleware()
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack()
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute()
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute()
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch()
#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#18 /var/www/firefly-iii/app/Http/Middleware/InstallationId.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\InstallationId->handle()
#20 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#30 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\SecureHeaders->handle()
#32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then()
#34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#35 /var/www/firefly-iii/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle()
#36 {main}
''

I really hope to get some advice, firefly-iii looks awesome and I'd love to try it out.

Edits: Formatting is hard

**Comment by JC5** [comment]
In your logs, especially those for Firefly III itself, you should see something pointing to the database. That might be an issue. Something like this?

```
fireflyiii_1    | Package manifest generated successfully.
fireflyiii_1    | Wait for the database.
fireflyiii_1    | wait-for-it.sh: waiting 60 seconds for fireflyiiidb:3306
fireflyiiidb_1  | [i] MySQL root Password: aa0quupaeceeF4eY
fireflyiiidb_1  | [i] Creating database: firefly
fireflyiiidb_1  | [i] with character set: 'utf8' and collation: 'utf8_general_ci'
fireflyiiidb_1  | [i] Creating user: firefly with password secret_firefly_password
fireflyiiidb_1  | 2020-07-04 10:22:59 0 [Note] /usr/bin/mysqld (mysqld 10.4.13-MariaDB) starting as process 73 ...
```

Something like this should definitely come up:

```
fireflyiii_1    | wait-for-it.sh: fireflyiiidb:3306 is available after 4 seconds
fireflyiii_1    | DB is up. Time to execute artisan commands.
fireflyiii_1    | Run various artisan commands...
fireflyiii_1    | Running migration commands...
fireflyiii_1    | Database "firefly" exists.
fireflyiii_1    | Migration table created successfully.
```

What are your results?

**Comment by tenklo** [comment]
Okay, the access for user firefly gets denied. I do understand correctly that all I have to look out for are identical passwords in the .yml and the .env file? 
```
Wait for the database.
DB is up. Time to execute artisan commands.
Run various artisan commands...
Running migration commands...
Error when connecting to DB: SQLSTATE[HY000] [1045] Access denied for user 'firefly'@'172.18.0.3' (using password: YES)
[2020-07-04 12:23:07] local.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'firefly'@'172.18.0.3' (using password: YES) (SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'firefly'@'172.18.0.3' (using password: YES) (SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE') at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
```

**Comment by JC5** [comment]
Especially `MYSQL_PASSWORD=securepw` and ` DB_PASSWORD=securepw` must be equal.

**Comment by tenklo** [comment]
They are equal, it does not work anyway...

**Comment by JC5** [comment]
Make sure you remove all volumes before you try again. The old password may be stored there.

**Comment by tenklo** [comment]
It works! 
Should have listened to the suggestions from the guide to use a dedicated directory..
Not sure how docker (compose) works but I supposed it also tried to use some of the files in my homedirectory somehow? 
After putting everything in a dedicated folder there were no errors and I'm greeted by the register page.
Thank you very much for your help

**Comment by JC5** [comment]
No problem, glad it works!
