### ISSUE TITLE
Multiple Questions regarding Security

### ISSUE THREAD

**Issue by 0thomas** [firefly-iii/firefly-iii#3526]
Hi there,

first off: I'm a long time lurker, a huge fan and am planning on deploying firefly to manage my own finances. Thanks for this amazing tool!

I know something about computers, can find my way around a Raspberry pi and get the basics of docker, I don't know much about network and network security except basic best practices for end users. Therefor 2 questions regarding the security of deploying Firefly:

1. If I deploy Firefly on an free AWS instance, assign a external IP and access Firefly through this IP, will some kind of my personal data be left out in the open? Since I have seen enough news of unencrypted databases from huge companies left out in the open, I am a bit hesitant. 

A few follow up questions regarding 1:
1.1. Is the database encrypted by default when deploying Firefly with Docker Compose?
1.2. Is the connection between me and Firefly on the AWS instance encrypted by default?
1.3. Can somebody connect to Firefly and bruteforce the password?
1.4. Can somebody find a key for the database somewhere in any Docker Env / Config files and could they be accessed from the internet?

2. I get and love the self hosted aspect of Firefly, but I feel safer using managed infrastructure from other providers. Would it be safer / easier for me to run a Raspberry Pi on my home network and connect it to the internet? Is the possible attack surface bigger when building it on my own at my home without advanced knowledge of networks and network security?

Thanks very much in advance for your answer,
Thomas

**Comment by JC5** [comment]
Those are some pretty good questions! I’m on my phone so I can’t really answer you right now. 

I was thinking of writing a big page in the documentation detailing your questions (and more). Would that be a good idea? Most questions have no straight answer but need some more background to answer right. Hence :)

Let me know! Very glad to hear you like the tool!

**Comment by 0thomas** [comment]
Yes, first I tried looking for just this page in the docs.

I'm not a great technical resource, but I know a bit about computers and would love to support you / anybody in compiling this page.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/about-firefly-iii/security
