### ISSUE TITLE
CSV importer maps data when checkbox unchecked

### ISSUE THREAD

**Issue by SerialVelocity** [firefly-iii/firefly-iii#3528]
**Bug description**
I am running Firefly III version 5.3.0, and my problem is:

When using the CSV importer (release-1.0.14), it is mapping the destination account name when the checkbox is unchecked.

I get errors such as `ONLINE` being mapped to my account that contains the word `ONLINE`.
And `Aqua` being remapped to `Aqua Card` (which then fails the import). Note that `Aqua` already exists and has transactions associated to it from the built-in CSV importer.

**Steps to reproduce**

One thing to note is that I used a json from the old built-in importer, but the v2 json that gets produced has the `map` field set to false.

**Extra info**

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Indeed, nicely spotted. I guess more opportunistic search behavior on the side of Firefly III enables this.

I will fix this in a new release of the importer. Thanks for reporting!

**Comment by JC5** [comment]
New release is out :+1:
