### ISSUE TITLE
CSV importer tries to map more than field then errors out

### ISSUE THREAD

**Issue by SerialVelocity** [firefly-iii/firefly-iii#3529]
**Bug description**
I am running Firefly III version 5.3.0 (with csv importer release-1.0.14), and my problem is:

When ticking the "map data" box for "opposing-account", the app also tries to make me map "category-name".

I tick one box:
<img width="898" alt="Screenshot 2020-07-04 at 17 33 03" src="https://user-images.githubusercontent.com/422338/86517021-6e2d1a00-be1d-11ea-83ea-5c3db284d059.png">

It then makes me fill in two:
<img width="938" alt="Screenshot 2020-07-04 at 17 41 12" src="https://user-images.githubusercontent.com/422338/86517045-a46a9980-be1d-11ea-8243-674501ce88bb.png">

And then errors with:
<img width="801" alt="Screenshot 2020-07-04 at 17 43 28" src="https://user-images.githubusercontent.com/422338/86517080-e693db00-be1d-11ea-9f66-ec279881b74b.png">

**Steps to reproduce**

**Extra info**

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nice find, confirmed! I'll release a new version later today.

For the error on the side of Firefly III itself, a fix is available as well, although I could not replicate it personally. I hope that this is fixed together with the CSV importer fix.

**Comment by SerialVelocity** [comment]
btw, thanks for including the full path to the bug ID in the commit! I noticed on some of your old commits it was a bit harder to navigate to the bug since something like `#3529` didn't work as it needed `firefly-iii/firefly-iii#3529`! 🥳

**Comment by JC5** [comment]
Yeah I keep forgetting that 😅
