### ISSUE TITLE
Issue upon fresh Firefly installation (Docker)

### ISSUE THREAD

**Issue by rpalmer0812** [firefly-iii/firefly-iii#3531]
I am running Firefly III version latest.

**Description**
using docker-compose v3, fresh install of fireflyiii and the attached mariadb. 

To be upfront, I am a beginner at docker and sql. I came across this project and thought it would be a good challenge to try set this one up and learn a few things along the way. My deepest apologies if this turns out to be something entirely simple. I truly have been at this one for a few nights and thought I would ask someone for assistance.

**Extra info**
 

I am on MacOS using Safari and when I try to access Firefly, it shows a webpage indicating the error is:

"Trying to get property 'data' of non-object"

My env.example and docker-compose files are as below:

**env.example**

DB_CONNECTION=pgsql
DB_HOST=fireflyiiidb
DB_PORT=3306
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD=firefly

MYSQL_USE_SSL=false
MYSQL_SSL_VERIFY_SERVER_CERT=true

MYSQL_SSL_CAPATH=/etc/ssl/certs/
MYSQL_SSL_CA=
MYSQL_SSL_CERT=
MYSQL_SSL_KEY=
MYSQL_SSL_CIPHER=

PGSQL_SSL_MODE=false
PGSQL_SSL_ROOT_CERT=null
PGSQL_SSL_CERT=null
PGSQL_SSL_KEY=null
PGSQL_SSL_CRL_FILE=null

**Docker-compose.yml**

version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:

   - firefly_iii_export:/var/www/firefly-iii/storage/export
   - firefly_iii_upload:/var/www/firefly-iii/storage/upload
     v_file: env.example
         ports:
   - 80:8080
     pends_on:
   - fireflyiiidb
     fireflyiiidb:
         image: yobasystems/alpine-mariadb:latest
         environment:
   - MYSQL_RANDOM_ROOT_PASSWORD=yes
   - MYSQL_USER=firefly
   - MYSQL_PASSWORD=firefly
   - MYSQL_DATABASE=firefly
     lumes:
   - firefly_iii_db:/var/lib/mysql

volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:

**These are the logs I can see below. There is a constant message about invalid SSLmode value user which I haven't had much progress after googling.**

docker container logs -f 30aea960b5c6

Now in entrypoint.sh for Firefly III

Entrypoint script version is 1.0.6 (2020-06-07)

Running as www-data.

Now parsing _FILE variables.

done!

Touch DB file (if SQLite)...

Dump auto load...

Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache

Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache

Generating optimized autoload files

\> Illuminate\Foundation\ComposerScripts::postAutoloadDump

Generated optimized autoload files containing 4911 classes

Discover packages...

Discovered Package: adldap2/adldap2-laravel

Discovered Package: davejamesmiller/laravel-breadcrumbs

Discovered Package: fideloper/proxy

Discovered Package: jc5/google2fa-laravel

Discovered Package: laravel/passport

Discovered Package: laravel/ui

Discovered Package: laravelcollective/html

Discovered Package: nesbot/carbon

Discovered Package: rcrowe/twigbridge

Package manifest generated successfully.

Wait for the database.

wait-for-it.sh: waiting 60 seconds for fireflyiiidb:3306

wait-for-it.sh: fireflyiiidb:3306 is available after 3 seconds

DB is up. Time to execute artisan commands.

Run various artisan commands...

Running migration commands...

CreateDB does not apply to "pgsql", skipped.

In Connection.php line 671:

​                                        

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'" (SQL: select *  

 from information_schema.tables where table_schema = public and table_name =  

  migrations and table_type = 'BASE TABLE')                  

​                                        

In PDOConnection.php line 31:

​                                

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'"  

​                                

In PDOConnection.php line 27:

​                                

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'"  

​                                

Going to decrypt the database.

In Connection.php line 671:

​                                        

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'" (SQL: select "i  

 d", "name" from "accounts")                          

​                                        

In PDOConnection.php line 31:

​                                

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'"  

​                                

In PDOConnection.php line 27:

​                                

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'"  

​                                

Running upgrade commands...

In Connection.php line 671:

​                                        

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'" (SQL: select *  

 from information_schema.tables where table_schema = public and table_name =  

  transaction_journals and table_type = 'BASE TABLE')             

​                                        

In PDOConnection.php line 31:

​                                

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'"  

​                                

In PDOConnection.php line 27:

​                                

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'"  

​                                

In Connection.php line 671:

​                                        

 SQLSTATE[08006] [7] invalid sslmode value: "user='firefly'" (SQL: select "t  

 ransaction_journals"."id" as "id", count(transactions.id) as transaction_co  

 unt from "transaction_journals" left join "transactions" on "transaction_jo  

 urnals"."id" = "transactions"."transaction_journal_id" where "transaction_j  

 ournals"."deleted_at" is null group by "transaction_journals"."id")      

​                                        
Updated version.
Application cache cleared!
Configuration cache cleared!
Configuration cached successfully!
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v5.3.0!                                |
| This version of Firefly III requires PHP7.4.                                 |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
[Sat Jul 04 19:35:04.791513 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.7 OpenSSL/1.1.1d configured -- resuming normal operations
[Sat Jul 04 19:35:04.791988 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.20.0.1 - - [04/Jul/2020:19:35:17 +0200] "GET / HTTP/1.1" 500 4597 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.20.0.1 - - [04/Jul/2020:19:35:18 +0200] "GET /v1/css/error.css?v= HTTP/1.1" 404 3715 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"

**Thank you for your time.**

**Comment by JC5** [comment]
No worries! It seems like a simple problem. I think changing `DB_CONNECTION=pgsql` to `DB_CONNECTION=mysql` will fix the issue you're running into.

**Comment by rpalmer0812** [comment]
> No worries! It seems like a simple problem. I think changing `DB_CONNECTION=pgsql` to `DB_CONNECTION=mysql` will fix the issue you're running into.

Thank you so much. That seems to have worked.

I am slightly confused though because in the env.example file, it says this:

# Use "pgsql" for PostgreSQL and MariaDB. Use "sqlite" for SQLite.
DB_CONNECTION=mysql

Since in the docker-compose file it is referring to this:

 fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest

Wouldn't that mean we are using mariadb and so the DB_CONNECTION should be pgsql?

**Comment by JC5** [comment]
I see the mistake. I’ll fix it ASAP!

**Comment by rpalmer0812** [comment]
Super, thank you so much for clearing it up so promptly. Really appreciated.
