### ISSUE TITLE
Spectre Importer: transactions.0.amount muss größer als „:more” sein

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3532]
**Bug description**
I am running Firefly III spectre importer v1.0.1

transactions with an amount of 0 lead to the error stated in the title (has to be greater than :more.

**Steps to reproduce**
I do have some of these when my bank wants to leave some message on the statement (new interest rates or so)

**Comment by JC5** [comment]
Ah yes, some validation errors don't fill in the placeholder. That's a bug, thanks for letting me know!

**Comment by totti4ever** [comment]
didn't happen again after the fix!

**Comment by JC5** [comment]
1.0.3 is building.
