### ISSUE TITLE
Spectre Importer: Doesn't add import tag

### ISSUE THREAD

**Issue by hecspc** [firefly-iii/firefly-iii#3534]
**Bug description**
I am running Firefly III version 5.3.0, and my problem is:

**Steps to reproduce**
Using the spectre importer and with the add tag checkbox checked it sucessfully import all the transaction but there is no added tag on the Firefly application.

**Extra info**
Using docker image for both application firefly-iii:latest and firefly-spectre:develop on a proxmox VM

Maybe worth to mention that the first time, the importer imported all the transactions, including those that were already importer with the previous spectre importer built-in. Due to there is no added tag, the only way to remove those duplicated transactions is manually one by one.

**Comment by JC5** [comment]
Indeed. The tag is added to the code! A new release will include this fix.
