### ISSUE TITLE
Spectre importer: Imported expense transactions have no decimals

### ISSUE THREAD

**Issue by hecspc** [firefly-iii/firefly-iii#3535]
**Bug description**
I am running Firefly III version 5.3.0, and my problem is:

**Steps to reproduce**
Using the new spectre importer, all the expenses transactions appears with no decimal on the importer logs. ~~on the firefly application but not in the log of the importer~~ . So a transaction logged in the imported as "created transaction 12.40"  becomes a transaction of 12.00 on the firefly app.

The revenue transactions are ok with the right decimal values so this is only affecting to the expenses.

**Extra info**
Docker images for both fireflyiii/spectre-importer:develop and jc5x/firefly-iii:latest  on a proxmox vm running ubuntu 18.04

**Comment by JC5** [comment]
I heard this from a few people before, but I haven't been able to replicate it myself. Could you collect some log files from your Spectre importer, possibly to my email (james@firefly-iii.org)?

I'm curious what's going wrong.

**Comment by hecspc** [comment]
I have sent you an email with the info for one of these truncated transactions.

I looks the truncation happens already on the importer since the log appears already with no decimal. I will edit my original comment to correct this.

**Comment by JC5** [comment]
Found it, thanks for sending me your log files! A new release will go out before the weekend.

**Comment by JC5** [comment]
1.0.2 is now live.
