### ISSUE TITLE
Default port changed to 8080 from 80 in Docker

### ISSUE THREAD

**Issue by alexolivier** [firefly-iii/firefly-iii#3537]
**Bug description**
I am running Firefly III version 5.3.0, and my problem is that Apache is now listening on 8080 rather than 80

**Steps to reproduce**
Run 5.3.0 docker image

**Comment by JC5** [comment]
As mentioned in the [changelog](https://github.com/firefly-iii/firefly-iii/blob/main/changelog.md) and the [release notes](https://github.com/firefly-iii/firefly-iii/releases/tag/5.3.0).
