### ISSUE TITLE
Firefly stopped working on my domain and uses internal IP, stating ServerName directive wasnt determined.

### ISSUE THREAD

**Issue by Joeharrison94** [firefly-iii/firefly-iii#3538]
I am running Firefly III version 5.3.0

**Description**
"AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.0.22. Set the 'ServerName' directive globally to suppress this message"

This is the output from my docker logs, this was working for over a month with no changes and not it stopped being accessible.

**Extra info**
Using docker compose and an env file with mariadb as the database.

**Comment by JC5** [comment]
Hi!

The server name error is not a problem. It's just because 10.0.0.22 doesn't resolve to a DNS name. As per the release notes, the latest image switched from port 80 to port 8080. Did you update your configuration accordingly?

**Comment by Joeharrison94** [comment]
@JC5 I have updated my config to use prot 8080 but it still isnt working here is my compose seciton for firefly 

  #Firefly Yaml
  fireflyiii:
    image: jc5x/firefly-iii:latest
    container_name: fireflyiii
    volumes:
      - $USERDIR/docker/firefly_iii/export:/var/www/firefly-iii/storage/export
      - $USERDIR/docker/firefly_iii/upload:/var/www/firefly-iii/storage/upload
    env_file: .fireflyiiienv
    ports:
      - "$FIREFLY_PORT:8080"
    depends_on:
      - fireflyiiidb
    networks:
      proxy_net:
        ipv4_address: 10.0.0.22     
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.fireflyiii-rtr.entrypoints=https"
      - "traefik.http.routers.fireflyiii-rtr.rule=Host(`firefly.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.fireflyiii-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.fireflyiii-rtr.service=fireflyiii-svc"
      - "traefik.http.services.fireflyiii-svc.loadbalancer.server.port=8080"

**Comment by Joeharrison94** [comment]
I repulled the image and it is working now thank you

**Comment by JC5** [comment]
:+1:
