### ISSUE TITLE
Spectre Importer stuck at job status waiting_to_start

### ISSUE THREAD

**Issue by c0ldplasma** [firefly-iii/firefly-iii#3540]
I am running Firefly III version 5.3.0. Spectre Importer 1.0.1. Both dockerized.

**Description**
I'm trying to import my bank accounts with spectre salt edge to my fireflyiii installation. After mapping my bank accounts (spectre) to my firefly accounts in the spectre importer web interface (the spectre importer successfully connects to salt edge and my firefly instance) i'm stuck at this screen:

![webinterface](https://user-images.githubusercontent.com/14879514/86845492-e14ac080-c0a9-11ea-8fc9-a2b823005c57.png)`

docker logs of the spectre importer:

![log](https://user-images.githubusercontent.com/14879514/86845709-31c21e00-c0aa-11ea-80c3-c9ac5b787ca6.png)
What i noticed here is that the spectre importer logs timestamp is 2 hours behind. May this prevent the job from starting? I set the TZ Environment variable in my docker-compose but it only affects the apache server, not the importer itself.

**Extra info**
Server: Everything is running in docker containers on a CentOS 7 host system.
Client: Chromium browser 83

Debug information generated at 2020-07-07 23:33:51 Europe/Berlin for Firefly III version **5.3.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.0 |
| Firefly III API | 1.2.0 |
| PHP | 7.4.7 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 8f02f3ce-4505-4e83-a17a-6496dc0a3921 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider | ldap  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 00:00:00 |
| Session first | 2020-04-01 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 |

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ YES
- I added a screenshot YES
- I added log files  YES
- I was able to replicate the issue on the demo site. NO

**Comment by JC5** [comment]
Hi! Thanks for submitting your issue.

The timestamp doesn't really make a difference, but I'll add some code to the Spectre importer to make sure the timezone is correct.

Looking at your logs, I see that the "start" method is called correctly. But I see no logs or errors coming from that direction. In your logs, I would expect at least "now at DownloadController::start" or something similar. You have no such entry?

**Comment by c0ldplasma** [comment]
Hi, thanks for your answer.

I have no "now at DownloadController::start" entry.

My compelte log:
[importer.log](https://github.com/firefly-iii/firefly-iii/files/4889526/importer.log)

**Comment by c0ldplasma** [comment]
I looked up what I get as response to that POST request in the browser console. I get a HTTP 419 error with this content: 
`{
    "message": "CSRF token mismatch."
}`

**Comment by c0ldplasma** [comment]
Headers of that request:
![419](https://user-images.githubusercontent.com/14879514/86901348-c8272b80-c10c-11ea-8f47-62bdc62a370a.png)

**Comment by JC5** [comment]
The source of any Spectre importer page has a token:

```html
    <meta name="csrf-token" content="dnPylWmCmd7mopgvqXmrPjKZ3yQWVALxWHcfm5ZK">
```

Is it present? Does it change every time you refresh?

**Comment by c0ldplasma** [comment]
It is present and it remains the same across all pages and even if I refresh the page.

**Comment by JC5** [comment]
Thanks. Sorry, I can't replicate any of this. Not really sure what's happening; the library used to make the call picks up that token and adds it to the request. I'll do some deed diving to see what's happening.

**Comment by c0ldplasma** [comment]
So I updated the Spectre Importer to v1.0.2 and now the import is starting and working. My guess would be that the spectre importer gave me already expired tokens because its time was 2h behind.

Thanks for helping and fixing it! :)

**Comment by JC5** [comment]
Glad to hear it works! :+1:
