### ISSUE TITLE
Quarterly option for periodic operations?

### ISSUE THREAD

**Issue by pedrom34** [firefly-iii/firefly-iii#3541]
Hey James,

Is it possible to add a quarterly option to the periodic operations? My bank charges me stuff every three months.

If not, no issue, I'll create 4 yearly operations.

Thanks!

**Comment by JC5** [comment]
Select "every month" and then set "Skip" to 2.

**Comment by pedrom34** [comment]
Damn. Thanks! :smile:

**Comment by JC5** [comment]
:+1: 😁
