### ISSUE TITLE
Error "failed to open stream: No such file or directory" when trying to add a credit card

### ISSUE THREAD

**Issue by bousquetfrederic** [firefly-iii/firefly-iii#3542]
**Bug description**
I am running Firefly III version 5.3.0, and my problem is:

This is a very new install of Firefly 5.3.0 on Centos 8, with SELinux context (I hope) properly setup. I succesfully created two savings accounts, but then I went to create a Credit Card account (with a negative opening balance), and got the error:

file_put_contents(/var/www/html/firefly-iii/storage/framework/cache/data/1e/6f/1e6f1e4682b0ca7884e5b1c91ee7fd6ba1ad094d): failed to open stream: No such file or directory

**Steps to reproduce**
Just created two savings accounts then a Credit Card account.

**Extra info**
This is a selfhosted instance on Centos 8. The cache directory is populated with a lot of files, but the one it is trying to access does not exist.

The debug page:
Debug information generated at 2020-07-09 20:12:19 Europe/Amsterdam for Firefly III version **5.3.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.0 |
| Firefly III API | 1.2.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | f51fbd04-9779-4fd5-9cae-6d8c5ae1b676 |
| Using docker? | false |
| Telemetry | true |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 23:59:59 |
| Session first | 2020-07-09 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.61 |

The log file shows this entry when I created the account:
[2020-07-09 20:10:35] local.INFO: Stored new account. {"name":"Amex","active":true,"account_type":"asset","account_type_id":0,"currency_id":1,"virtual_balance":"","iban":"","BIC":"","account_number":"","account_role":"ccAsset","opening_balance":"-495.84","opening_balance_date":"2020-07-09 00:00:00","cc_type":"","cc_monthly_payment_date":"","notes":"","interest":"","interest_period":"","include_net_worth":"1","store_location":false,"update_location":true,"longitude":null,"latitude":null,"zoom_level":null} {"path":"POST:https://xxxxxxxxxx/firefly/accounts/store","IP":"xxx.xxx.xxx.xxx","user":"xxxxxxxxxx@xxxxxx.xx"}

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files

**Comment by JC5** [comment]
Thanks for reporting. Please make doubly sure the storage directory is owned and writable for the user that runs the web server. Usually www-data.

**Comment by bousquetfrederic** [comment]
It is, yes:
drwxrwxr-x. 10 apache apache unconfined_u:object_r:httpd_sys_rw_content_t:s0   4096  9 juil. 13:29 storage

I did however something that maybe I wasn't supposed to. Since I ran into the problem I reported today on Reddit, I initially though I broke the software by mistake, and so I wanted to recreate an account. Since I couldn't delete my account due to the very bug I reported on Reddit, I deleted the database on mysql and redid the initialisation phase via the three "php assistant" lines. Hope that didn't break everything. I can try to reinstall everything maybe?

**Comment by JC5** [comment]
Mmm. Try clearing the cache using “php artisan cache:clear”. Then, do a new chown just in case. 

It’s always access rights with these kinds of errors.

**Comment by bousquetfrederic** [comment]
Ah, thanks, it seems to have worked ! I'll play a bit to see if I can break it, and if I can't, I'll close this issue.

**Comment by bousquetfrederic** [comment]
Ok, it seems to be working. Sorry and thanks!

**Comment by JC5** [comment]
No worries! If you break it again let me know 😅
