### ISSUE TITLE
Spectre Importer: using CONNECTION_TIMEOUT in env-file leads to error

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3544]
**Bug description**
I am running Firefly III spectre importer version dev@docker, and my problem is:

when the variable `CONNECTION_TIMEOUT` is set in the env file I run into an 500 server error on loading the import page; even if I set it to 50 (default seems to be pi). Commenting that line out helps!

**Comment by JC5** [comment]
Thanks for letting me know! What's the exact 500 error you run into?

**Comment by JC5** [comment]
Never mind! I think I found it. I juist built a new version of the `develop` tag. Could you verify the fix?

**Comment by totti4ever** [comment]
Works!

**Comment by JC5** [comment]
1.0.3 is building.
