### ISSUE TITLE
Heroku installation fails.

### ISSUE THREAD

**Issue by koyashi** [firefly-iii/firefly-iii#3545]
When trying to install Firefly-iii in Heroku I get this error:
**"An error was encountered when contacting the add-on partner to create heroku-postgresql:hobby-dev: Available versions are 9.6, 10, 11, 12 (the default is 12)"**

I've covered the encryption key because I'm not sure if I should be showing it.
I haven't changed anything from the default settings.

![heroku](https://user-images.githubusercontent.com/7952227/87208423-98dc0e80-c306-11ea-83c2-90cd3f87ac0f.jpg)

Thank you for the help.

Best regards.

**Comment by JC5** [comment]
Thanks for letting me know. I know the problem and I've fixed it.

You'll have to wait for the next version of Firefly III; I've updated the necessary meta-files, but they're not in the main branch yet.
