### ISSUE TITLE
Clean up database / delete transactions of an account

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3546]
**Description**
I would like to have the possibility to delete all transactions (of one account).
use-case is initial setup and calibration (test import, adapt mapping, re-import, ...)

I tried solving it by sql, but ran into minor issues and think the db wouldn't be consistent afterwards

**Solution**
a new button under administration "reset database", where I can select afterwards what is going to be resetted: singlce accounts, all tags, ...

**What are alternatives?**
reset database (drop) and recreate especially the accounts and categories (in my case)

**Comment by JC5** [comment]
I'll see what I can do! In the mean time, deleting everything from the following tables should reset everything without giving you problems with database consistency.

- budget_transaction
- budget_transaction_journal
- category_transaction
- category_transaction_journal
- transactions
- transaction_journals
- **transaction_groups**
- journal_links
- journal_meta
- tag_transaction_journal

However, if you start with the table in bold, most other tables will empty themselves without any consistency problems.

**Comment by totti4ever** [comment]
helps already a lot, thanks!

Would say, if it was up to me, there don't have to be any further supporting tools

**Comment by JC5** [comment]
This is present in 5.3.1.

**Comment by totti4ever** [comment]
Tested deleting all transaction - worked well. BUT I had to clear the cache, before the account overview showed all zeros. 

Maybe, you can add this by default after all deletions.

thanks anyways for the very (!) quick solutions and answers you are delivering!

**Comment by JC5** [comment]
I'll pick it up! Thanks for the compliments, it's much appreciated! :+1:
