### ISSUE TITLE
Add ability to ignore bank-side categories at spectre import

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3547]
**Description**
I just don't find those categories really helpful and put my rules on top anyway. What I achieved through mapping is to map those default categories to a new single category `todo`. Nevertheless better would be to ignore them completely on request during import.

**Solution**
I'd say a JSON parameter would be best.

Using a rule to remove categories on creation doesn't really work (there is no always rule anyway)

**Comment by JC5** [comment]
I'll see what I can do :)

**Comment by JC5** [comment]
This is present in the Spectre importer now.
