### ISSUE TITLE
token error with firefly importer v. 1.0.15

### ISSUE THREAD

**Issue by MakiG0** [firefly-iii/firefly-iii#3550]
I am running Firefly III version 5.3.0.

**Description**
i got following error message:
![grafik](https://user-images.githubusercontent.com/49974203/87225288-1ac24b00-c38c-11ea-9444-19a5b8438712.png)

I set the correct docker ip with the command from documentation: `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' CONTAINER`.
I have recreated the token 3 times or so, but nothing changes.
What am I doing wrong?
Do you need other informations?

**Comment by JC5** [comment]
There's a chance the two Docker containers are on different subnets, and they won't be able to reach eachother. You should read up on Docker's network settings.

**Comment by MakiG0** [comment]
just checked your assumption again, but both on the same subnet...
other ideas?

**Comment by JC5** [comment]
Nope, not really I'm afraid. You can see if they can ping one another?

**Comment by MakiG0** [comment]
just checked, both can ping each other...

**Comment by totti4ever** [comment]
I am also connecting via the internal docker network - but I have to use the port 8080 then!

**Comment by MakiG0** [comment]
The port 8080 and it runs ;-) thank you both ;-)
