### ISSUE TITLE
Rental Property Extension?

### ISSUE THREAD

**Issue by vic2r** [firefly-iii/firefly-iii#3552]
**Description**

Trying to convert my rental property excel spreadsheet into a database.   First I started coding my own and realized it's pretty involved and saw firefly-iii.  I love it.  Super slick, really nicely done.  Can handle all my transactions (about 1000/year) and all my rental income (wish was better these days!).

Anyway, new feature would be to add a "Property" concept.  This could be very simple, like tag in expense (what I'm using now), but it would be a drop down list of my properties so I wouldn't have to key in the property name (typos are a big problem in excel and one reason we have to move to something else).  Also, I would need to see the property name in the expense List.

This could be extended to the reporting section, which already does pretty much everything I need using the tags.  

That's it.  What do you think ???

Thanks for creating this.

**Solution**

**What are alternatives?**

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
I'm afraid not. Firefly III is meant for personal and non-business finances and not many of my users have rental properties to manage.

You could manage this with tags though: they have auto-complete so spelling errors are no longer a problem. Each expense or withdrawal would need to get tagged and you could use the tag report to get an overview.

Did you know by the way, that you can lock the content of an Excel cell to a specific list of values? If people make a typo Excel just won't accept the content.
