### ISSUE TITLE
Cashback

### ISSUE THREAD

**Issue by fabianski7** [firefly-iii/firefly-iii#3553]
I am running Firefly III version 5.2.0 (YunoHost)

**Description**
Lately it has been very common for shopping sites in my country to offer cashback for purchases but I couldn't find a simple way to do this in firefly.

Example 1: A $100 purchase gave me $5 cashback, so I need to register a $100 withdrawal and a $5 depository. But from what I understand, it is not possible to do this in a single transaction. Am I correct? Do I have to create a separate transaction for each of them (deposit and withdrawal)?

Example 2: The $5 cashback from the previous purchase is in one account and I will use that balance to supplement another purchase. So, if my purchase is $50, I will only have to pay $45. How will this be registered? I was unable to put a negative amount on one part of the transaction so that the final amount is $45.

Sorry if this got a little confusing but this is how most of my purchases need to be registered because creating two registers each time a transaction is made will double my work.

**Comment by JC5** [comment]
Yeah this is tricky. There isn't really a solution. Personally, I try to *avoid* registering the cashbacks and simply take the difference from the price. I added some text to the [documentation](https://docs.firefly-iii.org/faq/financials#what-do-i-do-with-cashback-actions), I hope that it helps :).

**Comment by fabianski7** [comment]
Thanks for the suggestion.
I was thinking of doing it that way too, it's simpler, but then I wouldn't have a record of how much money I got with the cashback (and I really need to do this).
