### ISSUE TITLE
Consistency on amounts through the API

### ISSUE THREAD

**Issue by forcaeluz** [firefly-iii/firefly-iii#3554]
**Description**
The API at the moment mixes strings and numbers to represent amounts. (In the transactions API the amount is a string, on the accounts API they are numbers.)

**Solution**
It would be nice if they are all numbers or strings (Preferably numbers I think). That would make the use of the API a little bit easier. If they are all strings, at least I know that I need to convert to float whenever I need the float value. Now it's a mix.

**What are alternatives?**

**Additional context**
I'm writing a custom import application in Rust. Now I need to convert string to float on half the structs I'm using, and not on the other half.

**Bonus points**

**Comment by JC5** [comment]
Yep, I noticed it as well. I'll pick it up for the next release. Amounts will always be strings. Floats are generally not a good idea when dealing with monetary amounts.

**Comment by forcaeluz** [comment]
With that reasoning in mind, wouldn't it make sense to also limit the number of decimal places (Based on the currency decimal places maybe?). The strings I get now in the transaction API looks like: "21.000000000000".

And thanks for all the work you put into Firefly III.

**Comment by JC5** [comment]
Hah, that’s exactly what I was working on 😁

**Comment by JC5** [comment]
Thanks for the compliments! I was working on 5.3.1, and this will be included in the upcoming release (should be today).

**Comment by forcaeluz** [comment]
Thanks! Too late to make a similar remark about "ids"? (The account ID comes as a string, the source and destination id's of transactions are numbers.) Or should I open another issue for it?

**Comment by JC5** [comment]
They should all be ID's, but this depends on your database as well. I can pick it up!

**Comment by JC5** [comment]
Errr, I mean integers, of course.

**Comment by JC5** [comment]
5.3.1 is out. If this is still an issue, please open a new ticket.
