### ISSUE TITLE
Transfers cannot be linked to bills

### ISSUE THREAD

**Issue by jokajak** [firefly-iii/firefly-iii#3555]
**Bug description**
I am running Firefly III version 5.2.6, and my problem is:

It appears that transfers cannot be linked to bills. Testing a rule against the transactions indicates they would be matched but running the rule against the transactions does not link them.

**Steps to reproduce**

1. Create an asset account as the source called Checking
2. Create an asset account as the destination called CreditCard
3. Create a bill for a credit card payment
4. Create a rule for credit card payment with rules:
  1. Source account: Checking
  2. Destination account: CreditCard
5. Create a transfer from Checking to CreditCard
6. ** Expected results**
  * Transaction is linked to bill
7. ** Actual results **
  * Transaction is not linked to bill

**Extra info**
Testing the rule indicates it should match. I am trying to model same-as-cash balances on credit cards and tracking the expenses to the credit card as other purchases are made. I would like to be able to track the credit card as an asset account with a negative balance and monitor as the balance approaches 0. I also love the Bills to Pay feature and want to track the credit card balance as a bill to pay since it is the same across promotional period.

Debug information generated at 2020-07-12 12:19:50 UTC for Firefly III version **5.2.6**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.6 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| PHP version | 7.3.17 |
| Display errors | Off |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 23:59:59 |
| Session first | 2020-04-05 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Bonus points**
[x] I searched and nobody reported this bug before
[x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by jokajak** [comment]
Nevermind, I found https://github.com/firefly-iii/firefly-iii/issues/3192

**Comment by jokajak** [comment]
Perhaps with the additional information you'll reconsider?

**Comment by JC5** [comment]
No, sorry, this isn't going to change.
