### ISSUE TITLE
5.3.1 - (Account) charts seem to be broken

### ISSUE THREAD

**Issue by chrismast** [firefly-iii/firefly-iii#3556]
He, just upgraded to 5.3.1 and wanted to report that it seems the account chart is broken. Leads to an error message:

`Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

The stream or file "/var/www/firefly-iii/storage/logs/ff3-cli-2020-07-13.log" could not be opened: failed to open stream: Permission denied

More information
Please collect more information in the storage/logs directory where you will find log files. If you're running Docker, use docker logs -f [container]. You can read more about collecting error information in the FAQ.

Get help on GitHub
You're more than welcome to open a new issue on GitHub.

Use the search!
Include the information from this debug page.
Tell us more than "it says Whoops!"
Include error logs (see above).
Tell us what you were doing.`

Live log shows:

`
fireflyiii_1  | IP - - [13/Jul/2020:12:31:45 +0700] "GET /v1/css/error.css?v=5.3.1 HTTP/1.1" 404 3734 "http://domain.domain.com/accounts/asset" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
`

Running in an LXC container, reverting to 5.3.0 solves it.

**Comment by JC5** [comment]
Cache errors are usually the result of permission issues. Browse to /flush to clear your cache or run "php artisan cache:clear" from the command line.

**Comment by chrismast** [comment]
ok, that solved it! Thanks!

**Comment by JC5** [comment]
:+1:

**Comment by chrismast** [comment]
Similar issue with revenue and expense account charts, data flush did not resolve it though.
I can see the following in the log if that helps:
`[2020-07-13 13:07:22] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/1e\/a7\/1ea7a49452290725eab32a30f284e7b9b82c6846): failed to open stream: No such file or directory","time":"Mon, 13 Jul 2020 13:07:22 +0700","file":"\/var\/www\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Filesystem\/Filesystem.php","line":135,"code":0,"version":"5.3.1","url":"http:\/\/domain.com\/chart\/account\/expense","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/83.0.4103.116 Safari\/537.36","json":true}
`

**Comment by JC5** [comment]
I see it. I'm rebuilding 5.3.1 today.

**Comment by JC5** [comment]
I rebuilt the 5.3.1 image due to a permission error. Please delete your current `latest` image for Firefly III itself and download it again. Let me know if it works. My apologies for the problem.

**Comment by JC5** [comment]
5.3.2 is out, and should fix this issue. For my administration, please open a new issue if problems persist.
