### ISSUE TITLE
Permission issues in Docker image 

### ISSUE THREAD

**Issue by muracz** [firefly-iii/firefly-iii#3557]
**Bug description**
I am running Firefly III version 5.3.1, and my problem is:
```
The stream or file "/var/www/firefly-iii/storage/logs/ff3-cli-2020-07-13.log" could not be opened: failed to open stream: Permission denied
```

**Steps to reproduce**
I first noticed this yesterday night after upgrade  on my K8S cluster . I thought that this may have something to do with my setup. 

So I just started a vanilla docker image:
```
docker run -d -p 80:8080 -e APP_KEY=[key] jc5x/firefly-iii:latest
```
After the startup I see the same result,  the first log file written by root:

```
root@52cf16f7a3ad:/var/www/firefly-iii/storage/logs# ls -ltrh
total 404K
-rw-r--r-- 1 root root 401K Jul 13 06:49 ff3-cli-2020-07-13.log
```

The logs later on are written by www-data as they should. 

**Bonus points**
There was a similar bug already reported - #3530

**Comment by Nutellaeis** [comment]
Same here. It worked this morning and happened just now after updating from 5.3.0 to 5.3.1

**Comment by JC5** [comment]
I see it. I'm rebuilding 5.3.1 today.

**Comment by JC5** [comment]
I rebuilt the 5.3.1 image due to a permission error. Please delete your current `latest` image for Firefly III itself and download it again. Let me know if it works. My apologies for the problem.

**Comment by Nutellaeis** [comment]
Looking good for me. No errors and the log is owned by www-data :+1:

**Comment by JC5** [comment]
Glad to hear it. I hope this was a temporary thing!

**Comment by muracz** [comment]
Looking good also for me. No issue after recreating the pod on K8s.

**Comment by JC5** [comment]
5.3.2 is out, and should fix this issue. For my administration, please open a new issue if problems persist.
