### ISSUE TITLE
Upgrade from 5.2.8 to 5.3.2 still fails (iocage)

### ISSUE THREAD

**Issue by ngalfas** [firefly-iii/firefly-iii#3561]
I have a FreeBSD iocage container installation for Firefly. 
I upgrade to newer versions once a month without problems so far.

I now run 5.2.8.
Tried this morning to upgrade to 5.3.1 and failed with error 500. Reported that earlier.
When i copied the 5.2.8 files over the 5.3.1 files, my installation was ok.

I now copied the 5.3.2 files over BUT STILL I GET ERROR 500 !!!

Final step: i copy once again the 5.2.8 files and my installation is ok...

**Comment by ngalfas** [comment]
oh i am on PHP 7.3.19   !!!

**Comment by JC5** [comment]
As per the release notes of version 5.3.0, Firefly III now requires PHP 7.4 minimum.
