### ISSUE TITLE
swap minimum/maximum amount series captions in bills chart hint

### ISSUE THREAD

**Issue by mindaugas-j** [firefly-iii/firefly-iii#3566]
**Bug description**
swap minimum/maximum amount series captions in bills chart hint

**Steps to reproduce**
navigate to: https://somehost/bills/show/4
hover on any bar of bills chart

![Bills](https://user-images.githubusercontent.com/42828488/87630371-a1d14380-c73d-11ea-9b67-2a08294f9b98.png)

![Rule](https://user-images.githubusercontent.com/42828488/87630458-d0e7b500-c73d-11ea-8295-f26babebc001.png)

**Extra info**

version 5.3.1

**Comment by JC5** [comment]
Nicely spotted, will be fixed!
