### ISSUE TITLE
Error on first run Firefly III 5.3.2

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#3567]
I just run updated Firefly III 5.3.2, and I have this message:

Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

Log-file:
[ff3-apache2handler-2020-07-16.log](https://github.com/firefly-iii/firefly-iii/files/4930519/ff3-apache2handler-2020-07-16.log)

**Comment by JC5** [comment]
Hi,

Please make sure you're running PHP 7.4

**Comment by Nik-vr** [comment]
I'm sorry. The problem was really in PHP7.3. After switching to PHP7.4 everything works correctly.
