### ISSUE TITLE
Exception when viewing Foreign Transaction

### ISSUE THREAD

**Issue by mrcowman** [firefly-iii/firefly-iii#3568]
Hi,

When I try to view any transaction with a foreign amount on it there is an exception thrown:
  number_format() expects parameter 1 to be float, string given

This is happening on existing foreign currency transactions.  I have Euros defined at 2dp for this transaction.  Edit and update work, but as soon as it goes into view it throws the exception.

Debug information generated at 2020-07-16 13:38:16 UTC for Firefly III version **5.3.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.2 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 4be8acf5-542b-48b6-ba85-4ecb6b7d22b2 |
| Using docker? | true |
| Telemetry | true |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 23:59:59 |
| Session first | 2011-10-19 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_GB |
[firefly-exception.csv.txt](https://github.com/firefly-iii/firefly-iii/files/4931819/firefly-exception.csv.txt)

**Comment by JC5** [comment]
Thanks for letting me know, I'll verify and fix it!
