### ISSUE TITLE
Spectre: Start imports by predefined config files through web UI

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3570]
Main aspect for me was automation, but apparently Spectre needs manual confirmation by TAN app for several (german) banks, so that I cannot just run the Spectre import via docker cmd line every 2 hours or so :-(

What I actually would need is the ability to upload my json file to a predefined folder on the server (like I can with csv mapping configurations) and then select (all of) those when opening the spectre web ui. That way I could go to the web ui, start the process (best would be that the last selection is saved in cookies to save clicks) and keep an eye on the TAN apps.

It should work out, to start the imports in parallel.

Workaround right now would be to ssh onto my server and run an bash file which call the several docker cmd lines...

Thanks!

**Comment by JC5** [comment]
I'll see what I can do. This needs to be useful for people without German banks as well 😉

**Comment by totti4ever** [comment]
How does it work for other banks then? I think PSD2 is and European thing.

How do others user the Spectre importer? Besides somebody can go the cronjob route, this FR should help absolutely everybody who uses Spectre. I cannot imagine, people want to manually upload their configs subsequently for all their accounts.

**Comment by JC5** [comment]
PSD2 just says "open up your API's" but it doesn't say how. Dutch banks are mostly incompatible with Spectre. Slightly related is the FAQ:

https://docs.firefly-iii.org/faq/general#will-firefly-iii-support-psd-2


What I just wanted to say is that whatever form this feature takes, it must be useful for everyone 😊

**Comment by totti4ever** [comment]
Interesting

Nevertheless, I'd reckon it is the most natural thing on earth to not find and upload a JSON file each time you want to update data and repeat the whole process for each bank one is using!

So I'd strongly say this helps everyone, who doesn't use fully automated imports by cronjob

**Comment by JC5** [comment]
Will be part of the next Spectre release. Keep in mind it will also rename the "URI" environment variables to "URL" but I'll put it in the release notes. Thx for an excellent suggestion.

**Comment by JC5** [comment]
New release is out.
