### ISSUE TITLE
Rule Actions not shown on mobile browser/device.

### ISSUE THREAD

**Issue by JanFeld** [firefly-iii/firefly-iii#3572]
**Bug description**
I am running Firefly III version 5.3.2, and my problem is:

When editing/creating a transaction rule on a mobile device (iPhone 8) the view for 'actions' (_Rule Will_) doesn't work correctly. The table is shown but the table content says _Could not render view._

When clicking _Add new action_ an additional _Could not render view._ will be added.

**Steps to reproduce**

Create/Edit a rule on a mobile phone and click _Add new action_ one or more times.

**Extra info**

Occured on iPhone 8 13.5.1, Mozilla Firefox.

**Bonus points**

Screenshot:
![750-1174-max](https://user-images.githubusercontent.com/22739965/87767706-555c3580-c81b-11ea-8aed-6bfd8c6fe98b.jpg)

Sadly i could not reproduce this on the demo site.

**Comment by JC5** [comment]
That kind of implies there's an issue with your local installation. Maybe something in the cache?

When views fail to render the log files should show you what's going on. Could you share some logs?

**Comment by JanFeld** [comment]
```
[2020-07-17 08:26:48] local.ERROR: Cannot render rules.partials.action: Unable to write in the cache directory (/var/www/firefly-iii/storage/framework/views/twig/4a).
```

Looks like there are some permission issues. It just happens every now and then. I didn't try this one before but after looking at the logs i tried. It's fine now. I'm not sure what happens here but i have to `chown -R` a few times a month. This was the first one which i didn't find. I'll check the logs more often.. Maybe it's related to the cronjobs for automated transactions..? It's possible that they'll run as `root` accidently and it creates some dirs/files which can't be altered by normal web user afterwards?

Likely just a new case of 'dumb user' here. Thanks anyway! I'll double check permissions and cronjobs.. 

Many thanks.

**Comment by JC5** [comment]
No worries; keep me posted!

**Comment by JanFeld** [comment]
It Looks like it's been the cronjob. Definitely a 'dumb user' thing. The cronjob was executed by the wrong user (`root`) instead of the web-user. Reading the documentation helps... ;-) 

Nevertheless thanks for your help.
