### ISSUE TITLE
Be able to set allowed proxies in YNAB importer

### ISSUE THREAD

**Issue by blinkiz** [firefly-iii/firefly-iii#3576]
I am running Firefly III YNAB importer v2.0.0

**Problem**
The YNAB importer does not work behind reverse proxy. My problem is that I get mixed http/https url because the html <head> `base_url` is wrong. To solve this I need to be able to set allowed proxies in `App\Http\Middleware\TrustProxies`.

**Feature request**
My feature request is to implement the configuration variable `TRUSTED_PROXIES` as you have in your main Firefly III software.

**Comment by JC5** [comment]
Fixed! Will be part of the new importer release. :+1:
