### ISSUE TITLE
Error 500 (from .htaccess): "Option All not allowed here"

### ISSUE THREAD

**Issue by marzman95** [firefly-iii/firefly-iii#3579]
**Bug description**
I am running Firefly III version 5.3.3 and my problem is: I get an Error 500 message reporting that "Option All is not allowed here" in the freshly installed .htaccess file.

**Steps to reproduce**
Install version 5.3.3 on php 7.4 on a server hosted with Virtualmin

**Extra info**
OS: Ubuntu 18.04 LTS, combined with Virtualmin 1.953
No debug-log provided, since I was not able to access firefly-iii itself.

**Comment by JC5** [comment]
You have to make sure that /public is the web root.

**Comment by marzman95** [comment]
Thank you for the reply. This indeed worked. Maybe add this to the installation FAQ or something?
