### ISSUE TITLE
Authentication via X-Auth-...

### ISSUE THREAD

**Issue by Ryonez** [firefly-iii/firefly-iii#3583]
**Description**

- I would like Firefly III to allow authentication via [Keycloak Gatekeeper](https://www.keycloak.org/docs/latest/securing_apps/#_keycloak_generic_adapter), similar to issue #3184 

**Solution**

Take a selected X-Auth- header, and use that to identify users. `X-Auth-Username` would be a good default.

**What are alternatives?**
REMOTE_HEADER exists, but would be fairly difficult to integrate into my server flow (Wouldn't even know where to start).

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
Could you share which software you're using?

**Comment by Ryonez** [comment]
Sorry, I did add have the info, but it was in the hidden section for the description. Pulled it out so it can be seen.

**Comment by JC5** [comment]
I'll see what I can do.

**Comment by Ryonez** [comment]
Cheers

**Comment by Ryonez** [comment]
Working with the gatekeeper guys on adding REMOTE_USER support, apparently there's a way to pass through a REMOTE_USER header. However, firefly is saying there's no such header. If you happen to know a way to check the headers on Firefly's side that'd be useful.

Issue is over here: https://github.com/louketo/louketo-proxy/issues/669

**Comment by JC5** [comment]
You'll have to do some hacking to see if it's working as expected.

https://github.com/firefly-iii/firefly-iii/blob/main/app/Support/Authentication/RemoteUserGuard.php#L72

Add this:

```
        var_dump(request()->server());
        var_dump(request()->headers);
        exit;
```

**Comment by Ryonez** [comment]
Alright, did some modification to the files, and got some very useful information from the server block.
There's a whole bunch of X-Auths passed through (but no REMOTE_HEADER, that the other issue is tracking).
The formation is: `HTTP_X_AUTH_XXX`

It looks like gatekeeper has the following default fields (I'm only marking the ones useful for using as an account identifier):

- `HTTP_X_AUTH_EMAIL`
- `HTTP_X_AUTH_USERID`
- `HTTP_X_AUTH_USERNAME`

It might be useful to set this up to allow a custom header to watch for.

**Comment by Ryonez** [comment]
Alright, I edited the `RemoteUserGuard.php` with this:

```php
		$userID = request()->server('HTTP_X_AUTH_USERNAME') ?? null;
        // var_dump(request()->server());
        // var_dump(request()->headers());
        // exit;
        if (null === $userID) {
            Log::debug('No user in HTTP_X_AUTH_USERNAME.');

            throw new FireflyException('The HTTP_X_AUTH_USERNAME header was unexpectedly empty.');
        }
```

This has made it functional for my use currently.

**Comment by JC5** [comment]
It's on my list for the next release.

**Comment by Ryonez** [comment]
Thank you.
