### ISSUE TITLE
Import-Spectre: Wait for account refresh

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3584]
You added an automated refresh of the accounts, see below. But that happens asynchronously, i.e. FF pulls the results immeadiately afterwards and still gets only the old transactions.
If one starts the import straight again, Spectre has finished update and also FF gets the new transactions.

No clue, if API allows to wait or check for the latest update?!
Otherwise I might just use an workaround, where I call the import twice :-)

> I call for an extra refresh in the code. But it's not guaranteed it will work. Spectre may block it.
_Originally posted by @JC5 in https://github.com/firefly-iii/firefly-iii/issues/3549#issuecomment-657970097_

**Comment by JC5** [comment]
Unfortunately not. The refresh is not only asynchronous, there's also no feedback mechanism on the refresh; I can't check if it's finished.

**Comment by totti4ever** [comment]
Okay, thanks for your quick reaction again!

One idea which would still help is to have an own command for update, e.g.
```
php artisan spectre:trigger_update
```
or
```
php artisan spectre:refresh
```

would help to keep the logs clean :-)
