### ISSUE TITLE
10+ categories not in default financial report

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3585]
**Bug description**
I am running Firefly III version 5.3.3 and my problem is:

Firefly default report in the month does not show all categories that were spent in the month

**Steps to reproduce**
More categories can be seen in the category report than in the default report. Creating 11 categories in the month leads default to only list 10 categories but the category report lists 11.

**Extra info**
Using firefox. I can replicate on demo site.

**Comment by JC5** [comment]
I'll do some research. It might be the cache? I can't replicate it on my personal installation, but I have to check the code to see what's happening.

**Comment by 4e868df3** [comment]
visiting /flush did not resolve it for me

**Comment by JC5** [comment]
Are there also expenses registered for the 11th category?

**Comment by JC5** [comment]
I'm having some trouble replicating this. Both the year and month report (slightly different views) work with 10+ reports. Could you elaborate on what you're trying to do exactly?

**Comment by 4e868df3** [comment]
I can replicate it in the demo site for you. As we are on different time zones can you suspend the auto refresh or if you will be here in 30 I can load it right now into the demo site?

**Comment by JC5** [comment]
Afraid not. Would screenshots work in the mean time? I’m not behind my pc for like an hour.

**Comment by 4e868df3** [comment]
Ok- I did this in the demo firefly site. See how there are more categories in one than the other, like car.

![expenses](https://user-images.githubusercontent.com/50036670/88206072-9466fe00-cc02-11ea-9520-412f730b6de4.png)

![defaultReport](https://user-images.githubusercontent.com/50036670/88206114-a6e13780-cc02-11ea-9130-84432866a6a4.png)

![categoryReport](https://user-images.githubusercontent.com/50036670/88206133-aba5eb80-cc02-11ea-8532-95f81a22a4f6.png)

**Comment by JC5** [comment]
Bingo, found it. There's a button missing that would normally expand the list. Not sure what happened. Will pick it up!

**Comment by 4e868df3** [comment]
Thanks :)
