### ISSUE TITLE
Allow/Disable Unneeded Features When Using External Identity Manager

### ISSUE THREAD

**Issue by Ryonez** [firefly-iii/firefly-iii#3586]
**Description**

Basically as the title says. When using an external identity manager (REMOTE_USER), there are some account features that don't make sense being available to the user.

- `2-step verification`: Is managed by identity manager
- `OAuth Clients`: Again, is managed by identity manager

**Solution**

When an external identity manager is selected, disable these features.

**What are alternatives?**

I know that these features would not be needed in my case, but could be useful in cases I'm not aware of. So instead we could have it so a env variable is passed to disable them instead (or enable them if the default above is accepted).

**Additional context**

I'm using [Keycloak Gatekeeper](https://www.keycloak.org/docs/latest/securing_apps/#_keycloak_generic_adapter) as an identity manager. The auth service used has it's own 2-factor authentication systems, and is an oauth service while having it's own connections to others.

**Bonus points**

**Comment by JC5** [comment]
Yes, on my list.
