### ISSUE TITLE
[CSV-importer] duplicate identification doesn't work after update

### ISSUE THREAD

**Issue by sgofferj** [firefly-iii/firefly-iii#3587]
I am running Firefly III version 5.3.3

**Description**
After a couple of months I updated the container for the CSV importer and now the duplicate recognition doesn't seem to work anymore. Everything from the CSV gets imported, no matter what. I also updated the FF3 container to the latest version but it didn't help. Has there been any breaking change that would require modifying the json file?

**Extra info**

Debug information generated at 2020-07-23 12:26:04 Europe/Helsinki for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 367a4cb5-6ee0-4b99-878f-7e680491af88 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | true |
| App cache driver | redis |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 |

**Comment by JC5** [comment]
The changelogs for each [release](https://github.com/firefly-iii/csv-importer/releases) mention possible breaking changes. However, for the root cause to be clear I'll need some more information.

Keep in mind that between versions, it could happen that the duplicate detection breaks. This is part of the release notes. It's always wise to import small batches.

Could you share your import JSON and one or two lines?

**Comment by sgofferj** [comment]
I ran the importer now through the web interface and it created a new V2 json file. With that, the import works without duplicates. Unfortunately, I deleted the CSV already. The json I used before was the N26 json from [here](https://github.com/firefly-iii/import-configurations/blob/main/de/n26/default.json). V1 jsons don't seem to have an `ignore_duplicate_transactions` directive and the V2 importer doesn't seem to ignore duplicate transactions with V1 jsons. That's at least my speculation.

In case it's of use, here is my now working N26 V2 json:
```
{                                                                                                                                   
    "date": "Y-m-d",                                                                                                                
    "delimiter": "comma",                                                                                                           
    "headers": true,                                                                                                                
    "ignore_duplicate_lines": true,                                                                                                 
    "ignore_duplicate_transactions": true,                                                                                          
    "rules": true,                                                                                                                  
    "skip_form": false,                                                                                                             
    "add_import_tag": true,                                                                                                         
    "specifics": [],                                                                                                                
    "roles": [                                                                                                                      
        "date_transaction",                                                                                                         
        "opposing-name",                                                                                                            
        "opposing-iban",                                                                                                            
        "tags-comma",                                                                                                               
        "description",                                                                                                              
        "category-name",                                                                                                            
        "amount",                                                                                                                   
        "amount_foreign",                                                                                                           
        "foreign-currency-code",
        "_ignore"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "version": 2
}
```

**Comment by JC5** [comment]
Thanks for debuggin this. I'll double check the code to see what's going on.

**Comment by sgofferj** [comment]
I'll close this as my V2 JSON fixes the issue for me.
