### ISSUE TITLE
please move api-support-classes repo to the firefly-iii organisation

### ISSUE THREAD

**Issue by SimonPe** [firefly-iii/firefly-iii#3588]
**Description**
reading trough some csv importer code I just spent 5~10 minutes looking for that repo (it doesn't help that `GrumpyDictator\FFIIIApiSupport` is completely different from `JC5/api-support-classes` or for that matter `firefly-iii/api-support-classes`)

**Solution**
Please move the repo to this organization, preferably also re-name the namespace of the classes to something more in line with it.

**Comment by JC5** [comment]
It's a tiny internal repo. I don't really care. A link to the source is right there:

https://packagist.org/packages/firefly-iii/api-support-classes

I'll write down but don't expect any priority on my changing this.
