### ISSUE TITLE
[CSV-importer Documentation] How to restart?

### ISSUE THREAD

**Issue by bannisdale** [firefly-iii/firefly-iii#3589]
I'm running the most recent version of csv-importer and firefly.

I used the importer for the first time today. Imported a single entry, worked beautifully. Went ahead with a whole csv full of data, crash: "The job could not be started, or failed due to an error. Please check the log files. Sorry about this :(."

I'll have a look into what exactly happened, but my main problem is: when I open the importer again, the initial prompt shows up again. After clicking on "Start here ->", I'm redirected to the error page again. So even if I fixed the problem in my csv, I wouldn't be able to restart the import again.

I kinda feel dumb to ask this here, but I haven't found something about how to reset/restart the importer in the documentation or here in the issues.

Thanks in advance for the help! :)

**Comment by JC5** [comment]
No problem! You can reset the importer by browsing to `/flush`. Let me put it in the documentation as well.

**Comment by bannisdale** [comment]
Thanks for the quick reply! :)

**Comment by JC5** [comment]
Done
