### ISSUE TITLE
Script to update firefly-iii to the latest version

### ISSUE THREAD

**Issue by pedrom34** [firefly-iii/firefly-iii#3590]
Hey,

I just created a simple bash script to update firefly-iii for my installation (LAMP stack, no docker):
https://gist.github.com/pedrom34/d1b8ab84e1e9ec7e8c6cbcc3cc51d663

Nothing fancy, just something I did for myself and that I wanted to share.

have a nice day 😄

**Comment by JC5** [comment]
Thanks for sharing! I added it to [the documentation](https://docs.firefly-iii.org/advanced-installation/upgrade#virtual-or-real-server).

This ticket will probably be closed by the bot, but your contribution is saved! :+1: :tada:
