### ISSUE TITLE
CSV importer throws "The transactions.0.amount must be greater than"

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3591]
Same as #3532 was for Spectre, same happens with the CSV importer.

I'd like to keep the 0€ transactions btw, there are usually information provided by the bank in the description

**Comment by JC5** [comment]
Sorry, zero amount transactions will always be dropped.

**Comment by totti4ever** [comment]
I can see your point, but I'd reckon it is still a bug (same as #3532), i.e. the exception should be caught instead of throwing an error. Or is this meant to throw an technical error like this?

**Comment by JC5** [comment]
It is, yes. Does the importer stop completely? Because that shouldn't happen.

**Comment by totti4ever** [comment]
Nope, it does not stop - so nothing fatal!
