### ISSUE TITLE
Enable Email Support For Users When an External Identity Manager is Used.

### ISSUE THREAD

**Issue by Ryonez** [firefly-iii/firefly-iii#3592]
**Description**

I'd like for firefly to be able to email users when an external identity manager is used. Currently it tries to use the username, which is not an email address in my system. If you try to set one under `/profile`, you get the following error message: `Error! This action is not available when Firefly III isn't responsible for user management or authentication handling.`

**Solution**

A env setting that tells firefly to look for a header to get a user's email address would work in my case.
In my case, the header is: `HTTP_X_AUTH_EMAIL`.

**What are alternatives?**

I don't have any currently

**Additional context**

**Bonus points**

If pulling it from a env variable, being able to look for a custom header would allow some flexibility for external identity managers

**Comment by JC5** [comment]
When your ID your users with their email address, this will work just fine. Otherwise, for now, you're just out of luck.

I can't read the email address from an environment variable because the email is sent asynchronously and there's no access to the environment variavbles.

I'll see what I can do.

**Comment by Ryonez** [comment]
> I can't read the email address from an environment variable because the email is sent asynchronously and there's no access to the environment variavbles.

I was meaning that the env variable will tell firefly what header to look for, and then it looks at that header for the email like it does for the username.

**Comment by JC5** [comment]
Like I said: the headers can't be read when the email is sent.

**Comment by Ryonez** [comment]
Can they not be saved into the account information? I know there's some info stored, as that's how I made the account an "owner".

**Comment by JC5** [comment]
This is now possible in the next release. Instructions will be in the .env.example file.
