### ISSUE TITLE
[csv-importer] fails if there is a "," in the account name field

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#3593]
**Bug description**
Im trying to import some csv-files generated by my bank. It seems like csv-importer is failing with 

```
Line #3:

    (2) transactions.0.source_id: Could not find a valid source account when searching for ID "15" or name "". (original value: "15")
    (2) transactions.0.source_name: Could not find a valid source account when searching for ID "15" or name "". (original value: "(not found)")

```
 if there is an "," in the "Oppossing account (name)" field.

**Steps to reproduce**
* Create a csv with "," in the Field you later use as "Oppossing account (name)"
* Try to import this csv

**Extra info**
Debug information generated at 2020-07-25 09:31:45 Europe/Berlin for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | fce7fec2-9884-4989-bc4f-f2b388aee2aa |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 23:59:59 |
| Session first | 2019-10-01 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Bonus points**
- I searched and nobody reported this bug before

**Comment by JC5** [comment]
Do you have some example lines? I bet those comma's aren't escaped.
