### ISSUE TITLE
Car expenses, kilometer and consumption

### ISSUE THREAD

**Issue by debegr92** [firefly-iii/firefly-iii#3594]
**Description**
Would be great to be able to add cars to Firefly and track refuels with liter and kilometers/miles.
Track consumption over time and calculate expenses for vehicle.

**Comment by JC5** [comment]
Nope, sorry. Out of scope for Firefly III.

**Comment by pbartyik** [comment]
you could use tags and notes to keep track of this, then export and do the math with an external tool that you create.
