### ISSUE TITLE
Swap Source and Destination account 

### ISSUE THREAD

**Issue by Xosten** [firefly-iii/firefly-iii#3595]
**Description**
Hi, I use Firefly for a quiet moment right now. And I have frequently incoming transactions to my main account that I forward to a secondary account. I was wondering if having the possibility to press a button to swap both source and destination account. In my context, for example, I will just press the button, destination account becomes source account and I just have to fill a new destination account. This helps to save some time by not writing again the account name. This is more a User Experience oriented feature I think.

Is this maybe an interesting feature that some other people could benefit from?

**What are alternatives?**
Currently, as far as I know, none? Maybe you can enlight me if an alternative exists

**Bonus points**
![image](https://user-images.githubusercontent.com/11696836/88455495-fe3b0e00-ce75-11ea-98c0-08f426865ac5.png)

Once the swap button pressed and filled the new destination account.
![image](https://user-images.githubusercontent.com/11696836/88455524-2d517f80-ce76-11ea-89de-ecb280031027.png)

**Comment by JC5** [comment]
Yeah I've had that a few times as well. I'll see what I can do.

**Comment by Xosten** [comment]
Hi JC5, Nice to read that I'm not the only one encountering that haha. Thanks for your consideration ☺.
Cheers,

**Comment by Xosten** [comment]
@JC5 Any updates about this enhancement?

**Comment by JC5** [comment]
This will be part of the new layout I'm building. That's quite an effort so there'll be no meaningful updates until I'm done I'm afraid.
