### ISSUE TITLE
Where did reorder transactions go?

### ISSUE THREAD

**Issue by crameth** [firefly-iii/firefly-iii#3599]
I am running Firefly III version 5.3.2.

Is it still possible to reorder transactions? Used to be possible in previous versions. Cannot find the button now.

Edit: Appreciate it greatly if anyone can point me to the last version with the create new transaction UI shown below:

![image](https://user-images.githubusercontent.com/2794843/88468283-c71b3a00-cf13-11ea-81b8-2be89e33bc20.png)

**Comment by JC5** [comment]
Hi!

It's still on my list to re-implement, and I'll keep this issue open to track the progress.

Do you have any particular problems with the current form?

**Comment by crameth** [comment]
Thanks, hope to see it back soon.

I keep creating new expenses instead of transfers on accident with the new form, led to a bit of confusion when reconciling my accounts + having to delete expense accounts whenever they are created recently.

I prefer the old form as there was a clear separation between transaction types and the UI did not have to guess which transaction I was trying to create.

I like the new split a lot more however.

**Comment by heyheyhello** [comment]
I just got hit by this too. I have autopay (preauth) credit card payments so I always end up putting them into Firefly late (in this case, 5 days later). Maybe the feature could go under bulk edit?

![image](https://user-images.githubusercontent.com/44614862/96528809-68c2d680-1238-11eb-935e-dc602202313c.png)

Even if the implementation is just to delete all bulk items and re-add them as new transactions in the preferred order. Not the best solution but it's what I'm about to do to get the right account balance :sweat_smile: 

Also thanks for all your hard work on this repo! It's a lovely project.

**Comment by heyheyhello** [comment]
Oh! To anyone who runs into this it's very easy to Ctrl+Click all the transactions in order to open as new tabs. Then check " _Store as a new transaction instead of updating. "_ and save each in order.

**Comment by JC5** [comment]
The option to reorder transactions will be added into the new layout. There'll be no meaningful update until then, so I'm closing this.
