### ISSUE TITLE
Instructions for moving from existing installation to docker

### ISSUE THREAD

**Issue by ForestBits** [firefly-iii/firefly-iii#3601]
I originally installed firefly by following the [self-hosted installation section](https://docs.firefly-iii.org/installation/self_hosted) of the documentation. I am now attempting to move the existing install into docker instead. My question is, are there existing instructions for moving an install from one place to another in general? For example, here are the steps I currently took:

- Update existing install to newest version
- Create new container for it via docker-compose, making use of the reference .yml and .env files
- Used mysqldump on the existing database to generate an import file
- Moved said import file to the mysql container via docker cp
- Entered the container (docker exec -it mysql_container_name /bin/bash), then connected to the database (mysql -u firefly_user -p)
- Dropped the newly made database, then recreated it.
- Ran the import script (source path_to_import.sql)
- Restarted the containers

This mostly works - at a high level, all I did was make sure the schema was the same on both ends, then replace the database entirely - but I am wondering if I missed a step. The new install seems to work fine, though I see in docker logs there is an exception relating to "The MAC is invalid" on startup, which makes me think I may have missed something. It is also my understanding that I may need to do something with APP_KEY, which I have not done.

To reiterate my original question: Is there an itemized list of data/config that must be moved/matched when moving an install from one installation type to another that I can reference?

**Comment by JC5** [comment]
This is looking pretty good. All I can think of is the backup routine, that lists what you need when you make a backup. This is essentially the first part of a move.

https://docs.firefly-iii.org/advanced-installation/backup

**Comment by ForestBits** [comment]
I realized my "The MAC is invalid" error was indeed related to APP_KEY. I just didn't set it to the same value as the original install, which apparently causes an issue and doesn't, on its own, generate a new key - probably to avoid some more permanent data loss on attachments (I had none anyway).

There was one other error I ran into with the reports screen, but I realized it actually happened after my upgrade, and before moving to docker, so I have created a separate issue #3636 to explore that problem.

I believe where that leaves us on this issue (assuming there aren't other errors I missed) is that you basically just need to copy the database and make sure all applicable settings in the .env file match - the latter was my problem.

If I wrote some more in-depth documentation for this, would you want to add it to the wiki? What I am picturing is a wiki page for moving from one install type to another in general. There would be a section describing the general process (similar to the backup section, but worded a bit more specifically for moving), and then there could be specific subsections covering specific use cases, starting with self-hosted->docker. I wouldn't expect that wiki page to cover every possible match -  it would still be reasonably general, since the copy step is separate from the movement step. That is, the instructions are basically "move from <whatever> to docker". I think this would be helpful for people newer to docker, such as myself.

**Comment by JC5** [comment]
Submit a PR to the [documentation repository](https://github.com/firefly-iii/docs) :+1:

**Comment by ForestBits** [comment]
I will do that.
