### ISSUE TITLE
Can't get transaction post to work

### ISSUE THREAD

**Issue by naterich2** [firefly-iii/firefly-iii#3617]
I am running Firefly III version 5.3.3

**Description**
I'm trying to create a transaction with a POST request to the `/api/v1/transactions` endpoint in python.  I keep getting an error both in python or when I translate it to a curl request.  My json body is as follows:
```
{
  "transactions": [
    {
      "type": "withdrawal",
      "date": "2020-07-28",
      "amount": "20.23",
      "description": "Groceries",
      "source_id": 9,
      "destination_id": 15,
    }
  ]
}
```
And I use the headers `Authorization: Bearer [PAT]`, `Accept: application/json`, `Content-Type: application/json`

I run firefly in docker, and what I see in the docker logs are the following:
```
2020-07-29T04:26:53.130733042Z 10.0.1.10 - - [29/Jul/2020:04:26:45 +0000] "POST /api/v1/transactions HTTP/1.1" 422 1223 "-" "python-requests/2.24.0"
2020-07-29T04:38:34.222487352Z 10.0.1.10 - - [29/Jul/2020:04:38:26 +0000] "POST /api/v1/transactions HTTP/1.1" 422 1167 "-" "curl/7.71.1"
```
I see nothing in the /debug logs.

What I get in response from the request is the following:
```
{"message":"The given data was invalid.","errors":{"transactions.0.description":["Need at least one transaction.","The description field is required."],"transactions.0.type":["Invalid transaction type."]}}
```

I can't figure out why this isn't working unless I'm missing something simple, it seems I'm following the schema correctly.  Any help would be greatly appreciated!

**Comment by JC5** [comment]
Hi! 

The comma after `"destination_id": 15,` makes your JSON invalid.

**Comment by naterich2** [comment]
Thank you for the quick response!  I apologize, that was actually an error from copying, I removed the destination_name field for privacy.  I did run the JSON through a validator, and it is valid:

```
{
  "transactions": [
    {
      "type": "withdrawal",
      "date": "2020-07-29",
      "amount": "20",
      "description": "Groceries",
      "source_id": 9,
      "source_name": "acct1",
      "destination_id": 15,
      "destination_name": "acct2"
    }
  ]
}
```
Here is the full JSON
```

**Comment by JC5** [comment]
It could be your request isn't recognized as JSON. Do you also send a "Content-Type" "application/json" header?

**Comment by naterich2** [comment]
That was it, thanks!

**Comment by bertbesser** [comment]
Hi,

I'm having a very similar problem.

Trying to 
```
curl -L --header "Authorization: Bearer `cat ffiii.pat`" --header 'Accept: application/json' --header "Content-Type: application/json" --request POST --data "`cat import.json`" 'http://my-host/api/v1/transactions'
```
where `ffiii.pat` and `import.json` contain, respectively, my PAT and
```
{
  "transactions": [
    {
      "type": "withdrawal",
      "date": "2016-12-28",
      "amount": "6.01",
      "description": "no comment",
      "category_name": "groceries",
      "source_id": 1,
      "destination_id": 7
    }
  ]
}
```
I get this answer;
```
{
  "message": "The given data was invalid.",
  "errors": {
    "transactions.0.description": [
      "Need at least one transaction.",
      "The description field is required."
    ],
    "transactions.0.type": [
      "Invalid transaction type."
    ]
  }
}

```
and the server logs show a `422` status code.

What am I missing?

Thanks a bunch!

**Comment by bertbesser** [comment]
@JC5 I hope it is alright that I reuse this issue, since it is _very_ related 😄

**Comment by JC5** [comment]
It's actually easier to open a new issue :+1:

**Comment by bertbesser** [comment]
Done in #4581
