### ISSUE TITLE
Related transaction

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#3623]
**Description**
I was thinking that something I would personally find really useful is a way to "relate transaction". This is especially useful when I handle and track refunds. 

**Solution**
The way I see it is that you could input the id of another transaction to relate them in some way, so that you have quick access to one another.

**Comment by sephrat** [comment]
Do you mean https://docs.firefly-iii.org/advanced-concepts/links?

**Comment by AlexKalopsia** [comment]
Wow, was completely unaware, awesome!

**Comment by AlexKalopsia** [comment]
I am actually now wondering why the (partially) is forced on the labels. Wouldn't it be better to make it an optional checkbox so that we can also track full refunds?

**Comment by JC5** [comment]
You can create your own relation that drops the word partially.
