### ISSUE TITLE
MAIL_DRIVER=sendmail being ignored and using SMTP instead

### ISSUE THREAD

**Issue by srpnor** [firefly-iii/firefly-iii#3625]
**Bug description**
I am running Firefly III version 5.3.3 and my problem is:

Setting

MAIL_DRIVER=sendmail

in .env appears to be ignored, and SMTP is used instead.  Further, when this happens, if any of the remaining MAIL_ settings are not explicitly set then defaults are used.

**Steps to reproduce**
Set MAIL_DRIVER=sendmail in .env and try to send a test email.  Instead SMTP will be used, using the configured values in MAIL_HOST and MAIL_PORT, or defaults if these are not set.  Setting these values to use my local SMTP server but leaving MAIL_DRIVER=sendmail, I see an SMTP connection to my server rather than a sendmail command line submission.

I have confirmed that my local sendmail command works correctly on the command line by hand.

**Extra info**
Debug information generated at 2020-07-30 12:11:03 Europe/London for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 0aba1557-3839-4173-9179-14cd3fe1705c |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 23:59:59 |
| Session first | 2020-04-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 |

**Comment by srpnor** [comment]
Just to add - from my point of view you can treat this as low priority as I can work around using SMTP submission to my local server instead.

**Comment by srpnor** [comment]
Ignore me - it's MAIL_MAILER I should be setting, not MAIL_DRIVER 

Oops.

**Comment by JC5** [comment]
It changed recently in the underlying framework, so I had to follow. Glad to see you got it fixed!
