### ISSUE TITLE
Add Small Business Accounting and Payroll to Firefly

### ISSUE THREAD

**Issue by rjain15** [firefly-iii/firefly-iii#3626]
**Description**

I would like Firefly III to do Small Business Accounting and Payroll

**Solution**
The MVP functionality could be every simple
- Ability to add Employees, and Employee Salaries (and other Perks), Number of Hours worked, and Rate per Hour (very similar to the basic Intuit)
- Ability to run payrolls, i.e. move money from Salary Bank Account to Employee (and ability to integrate with Square or Payment systems) 

**What are alternatives?**
I am a small business owner, and I am using Intuit (very unsatisfactory UX) and I have looked at other options like Gusto, most of them are very expensive. 

**Additional context**
![Quickbooks](https://quickbooks.intuit.com/cas/dam/IMAGE/A78dfQO1f/QBOP.png)

**Bonus points**

**Comment by JC5** [comment]
Nope. Firefly III is for personal finances.

**Comment by psychowood** [comment]
@rjain15 for the second point you can use named Expenses accounts for employees, then use the  export transactions function to automate/feed other systems.

**Comment by rjain15** [comment]
Closing this issue, as the suggested in the comments, it is out of scope for Firefly III
