### ISSUE TITLE
[CSV Importer] Timeout fetching accounts

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#3627]
**Bug description**
I am running Firefly III version 5.3.3 & CSV-importer 2.0.0, and my problem is:
After importing the csv file and defining all the role for the column I select the mapping tickbox for the opposing account then click on Submit. I get a 504 Gateway Time-out after 30 seconds.

While looking into the logs of my firefly container I see fetching the 19 pages of accounts takes more than the 30 seconds of timeout (it stops when being at page 12)

I suppose the page timeout has to be increase or manageable using an environment variable.

**Steps to reproduce**
Having enough account in your firefly instance to fill more than 12 pages and try to run the csv-importer with mapping on opposing account.

**Extra info**
I'm running both tools as containers on my Synology NAS.

**Bonus points**
Firefly logs with api calls
![image](https://user-images.githubusercontent.com/31923233/88972091-50849080-d2b5-11ea-8b3e-5d3296eaef64.png)

CSV Importer logs not showing anything related to the timeout as it looks it finishes the fetching of the data. Problem is that if I refresh the page it starts fetching the accounts again and is not using what has been done.
POST call at 20:41:11 and end of fetching data is at 20:41:57
![image](https://user-images.githubusercontent.com/31923233/88972624-22ec1700-d2b6-11ea-9b6b-3aaaa5746fb4.png)

I found this bug, maybe you need to apply the same change to the CSV-importer image?
https://github.com/firefly-iii/firefly-iii/issues/2096

**Comment by JC5** [comment]
Hah, 19 pages is a lot to handle, apparantly. 

The image already has a time-out of 600 seconds. A gateway timeout usually means the reverse proxy (aka Synology) stops after 30 seconds of waiting.

Having said that, I'll make sure that the code to pick up the accounts downloads larger chunks in one setting. That should already speed things up.

**Comment by MacPaille** [comment]
Thanks a lot for the feedback. Indeed as I was not using direct access with the IP but with the regular fqdn through my HAProxy the timeout was on that side :)
Problem solved I could import my transactions.

Now I have a suggestion for the mapping list but I'll create another record on this.

Thanks again!
