### ISSUE TITLE
Bill next expected match incorrect if paid early

### ISSUE THREAD

**Issue by pbartyik** [firefly-iii/firefly-iii#3629]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is:

When I set a bill to be paid on 10th of every month, and I pay it early (say on the 5th) the next expected match is not the next period, but still the 10th of current period.
The tick is there, that it is paid this period, but would be better to have the next expected date to be from the next period.

**Steps to reproduce**
Add bill to 10th.
Add transaction that matches bill rule on the 5th.

**Bonus points**
![20200731_12h20m38s_grim](https://user-images.githubusercontent.com/39059618/89026047-43ed5000-d328-11ea-8be4-a81d8a974ebe.png)

**Comment by JC5** [comment]
Indeed. This is working as designed. Firefly III won't assume the payment is for the next period, if it falls into the previous one.

**Comment by sephrat** [comment]
This has been puzzling me as well but I never gave it proper thoughts.
So you're supposed to pay your bills at least from the day you set on the bill? Why couldn't you pay it a few days before? That screenshot looks weird to me.

**Comment by JC5** [comment]
The date is used as a range indicator. From day X until the end of the period.

- 12 june to 12 july (monthly)
- 8 july (wednesday) to 15 july (wednesday)
- etc...

You pay your bill between those dates, that's the period it applies to. For both examples above, if you pay on 11 July, the next expected match is:

- 12 july, because the monthly period ends on 11 July.
- 15 july, because the weekly period ends on 15 July.

**Comment by sephrat** [comment]
Ah, I see. The date on the bill is not only the expected day, it also defines the beginning of the bill period. I thought it was linked to the calendar period (1st to 31st).
Thanks for the clarification.

**Comment by pbartyik** [comment]
yep, I assume the same as @sephrat . This is a bit counter intuitive, as if I set the bill date to the 1st of every month, on the 5th it says that I'm 5 days overdue. In this case shouldn't switch to overdue until the end of bill period?
