### ISSUE TITLE
Error in cron job auto-budgeting: trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by tryffel** [firefly-iii/firefly-iii#3630]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is error in cron job. See below.

I have configured three budgets, each one having auto-budgeting either set fixed amount monthly or add an amount monthly. I added auto-budgets first, and then some time after (weeks or months) I configured cron job. As I understand, cron job has never finished correctly and I'm getting this same error every night. I configured these budgets with some earlier version, I think 4.xx and cron job as well. I have removed all budgets once and re-added them, with no luck. Also budget amounts are not updated as they should.

**Steps to reproduce**
No idea.
Configure recurring budgets and configure cron job afterwards.

**Extra info**

Debug information generated at 2020-07-31 20:39:52 Europe/Helsinki for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 78d9cf82-a0ef-493b-9125-77261958a509 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | warning, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider | ldap  |
| Trusted proxies (.env) | 10.5.10.50 |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 23:59:59 |
| Session first | 2017-05-25 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | fi_FI |
| Attempt at "fi_FI.utf8" | 'fi_FI.utf8' |
| Attempt at "fi_FI.UTF-8" | 'fi_FI.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 |

 Firefly III v5.3.3 ran into an error: Trying to get property 'id' of non-object.

The error was of type "ErrorException".

The error occurred on/at: Fri, 31 Jul 2020 06:00:02 +0300.

This error occurred in file "/var/www/firefly-iii/app/Jobs/CreateAutoBudgetLimits.php" on line 210 with code 0.

There was no user logged in for this error or no user was detected. 
```
#0 /var/www/firefly-iii/app/Jobs/CreateAutoBudgetLimits.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/firefly-iii/app/Jobs/CreateAutoBudgetLimits.php(78): FireflyIII\Jobs\CreateAutoBudgetLimits->handleAutoBudget()
#2 /var/www/firefly-iii/app/Support/Cronjobs/AutoBudgetCronjob.php(87): FireflyIII\Jobs\CreateAutoBudgetLimits->handle()
#3 /var/www/firefly-iii/app/Support/Cronjobs/AutoBudgetCronjob.php(71): FireflyIII\Support\Cronjobs\AutoBudgetCronjob->fireAutoBudget()
#4 /var/www/firefly-iii/app/Console/Commands/Tools/Cron.php(129): FireflyIII\Support\Cronjobs\AutoBudgetCronjob->fire()
#5 /var/www/firefly-iii/app/Console/Commands/Tools/Cron.php(89): FireflyIII\Console\Commands\Tools\Cron->autoBudgetCronJob()
#6 [internal function]: FireflyIII\Console\Commands\Tools\Cron->handle()
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure()
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod()
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#13 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute()
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#15 /var/www/firefly-iii/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run()
#16 /var/www/firefly-iii/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/firefly-iii/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#20 /var/www/firefly-iii/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#21 {main} 
```

**Comment by JC5** [comment]
Thanks, that's a bug. I will fix it in the next release. Looks like an auto budget is associated with a deleted budget.
