### ISSUE TITLE
[CSV-Importer] missing german debit/credit-indicator

### ISSUE THREAD

**Issue by patago** [firefly-iii/firefly-iii#3631]
**Description**
The german indicator is missing in BankDebitCredit.php.
Debit is in german "Soll", short "S"

**Solution**
add ` 'S', // (DE). Short for "Soll"` file "app/Services/CSV/Converter/BankDebitCredit.php" after line 53

**example**
my local edit is:

> $negative = [
            'D', // Old style Rabobank (NL). Short for "Debit"
            'A', // New style Rabobank (NL). Short for "Af"
            'DR', // https://old.reddit.com/r/FireflyIII/comments/bn2edf/generic_debitcredit_indicator/
            'Af', // ING (NL).
            'Debet', // Triodos (NL)
            'Debit', // ING (EN), thx Quibus!
            **'S', // (DE). Short for "Soll"**
        ];

many thanks for your great work

edit: I found the solution already in  #2835

**Comment by JC5** [comment]
Already there. Will be included in the new release. 


https://github.com/firefly-iii/csv-importer/commit/33b8a1f56702ec7d898310acb4ea071c8642f8cc

No I don't know when it will be out.

**Comment by JC5** [comment]
New version is out 😉
