### ISSUE TITLE
Spectre Importer reports "AppsRestricted: Not available for apps." error message

### ISSUE THREAD

**Issue by VPsych** [firefly-iii/firefly-iii#3632]
I am running Firefly III version 5.3.3.

**Description**
I am running the Spectre importer and Firefly in Docker. Spectre generates the following error.

> Error :(
> The personal access token you added to the .env file is invalid. The error returned is: 
> AppsRestricted: Not available for apps. 
> This error can be a bit cryptic, and you can find common errors on this page in the documentation. Please refresh the page to validate your token again. 

**Extra info**
Debug information generated at 2020-07-31 20:56:27 America/New_York for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | c7075dd5-02f7-4881-bd38-4787c8845eaf |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start |  |
| Session end |  |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0 |

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ

Yes

- I added a screenshot

![ErrorMsg](https://user-images.githubusercontent.com/8846200/89090396-b2560080-d370-11ea-8b02-fc3781af7dad.PNG)

- I added log files 
No, but I can if needed.

- I was able to replicate the issue on the demo site.
How do I test the importer against the demo site?

Edit: If it helps, I have the CSV importer working, and I've tested changing the personal access token but Spectre results in the same error even after restarting both containers.

![Tokens](https://user-images.githubusercontent.com/8846200/89090494-4031eb80-d371-11ea-9459-84a79ad9a486.PNG)

**Comment by JC5** [comment]
Hi!

Make sure that you generate a **service key**, not an app key on the Spectre website. I've expanded the docs to make this clear.

**Comment by VPsych** [comment]
Thanks that fixed the problem.

**Comment by bafplus** [comment]
@JC5 where did you correct this in the doc? I followed the intructions but i onle seem to see reference to "App id/secret" instead of  "service keys" (ex. https://firefly-iii.gitbook.io/firefly-iii-spectre-importer/installing-and-running/configure#spectre-access-data). Hence i ran into this problem. maybe an idea to add this error and sollution to the Token Error page (https://firefly-iii.gitbook.io/firefly-iii-spectre-importer/errors-and-trouble-shooting/token_errors)?

**Comment by JC5** [comment]
It looks like the documentation isn't automatically selecting the "main" variant when you visit that page. I'll pick it up.

**Comment by JC5** [comment]
Fixed.
