### ISSUE TITLE
Can't connect to Redis - connection refused

### ISSUE THREAD

**Issue by AlexFullmoon** [firefly-iii/firefly-iii#3634]
I am running Firefly III version 5.3.3.

**Description**
FFIII can't connect to Redis, reports "Connection refused [tcp://172.17.0.1:6379]".
FFIII is in Docker (official image), Redis is on the host. I use the following env variables for that:

    REDIS_HOST=172.17.0.1  // container IP is 172.17.0.14, if that matters
    REDIS_PASSWORD=null //also tried leaving it blank
    REDIS_PORT=6379
    REDIS_DB="1"
    REDIS_CACHE_DB="2"
    CACHE_DRIVER=redis
    SESSION_DRIVER=redis

Redis set up without password (but with port binding to 127.0.0.1 and 172.17.0.1, so it's not in protected mode). 

[ffiii-docker-compose.yml.txt](https://github.com/firefly-iii/firefly-iii/files/5010323/ffiii-docker-compose.yml.txt)
[ffiii_docker.log](https://github.com/firefly-iii/firefly-iii/files/5010322/ffiii_docker.log)

Similar host config works for another Dockerized app (eLabFTW).

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [x] I added log files

**Comment by JC5** [comment]
Not sure. Can you ping the IP from the Firefly III image?

**Comment by AlexFullmoon** [comment]
I have MySQL on same host, as well, and can connect to it.
Oh, and docker image does not have ping installed, btw.

**Comment by JC5** [comment]
Then install it yourself.

```bash
docker exec --user=root -it <firefly iii container> bash

apt-get update
apt install iputils-ping
ping 127.0.0.1
```

**Comment by AlexFullmoon** [comment]
root@firefly-iii:/var/www/firefly-iii# ping 172.17.0.1
    PING 172.17.0.1 (172.17.0.1) 56(84) bytes of data.
    64 bytes from 172.17.0.1: icmp_seq=1 ttl=64 time=0.064 ms
    ...

**Comment by JC5** [comment]
Thanks. Sorry, in that case I have no clue. The redid code isn’t anything special. It’s all default Laravel stuff.

**Comment by AlexFullmoon** [comment]
Ok, I'll try digging that way, maybe I'll find anything.
