### ISSUE TITLE
Default Report Pages - Pre-Set Ranges Generate From Past Date After Upgrade

### ISSUE THREAD

**Issue by ForestBits** [firefly-iii/firefly-iii#3636]
**Bug description**

In preparation for converting from a self-hosted manual installation to a docker installation, I first upgraded my existing firefly instance to the newest release, 5.3.3. I didn't note, at the time, what the prior version I was on. It would have been roughly the newest version as of November 2019. I can restore a VM backup to find this, if needed.

To perform this upgrade, I followed the steps [on the wiki](https://docs.firefly-iii.org/advanced-installation/upgrade).

I have noticed one problem since doing this: If I navigate to the reports page (via clicking reports on the left sidebar - just the default, index page), it takes quite a while to load, because the Pre-Set Range dates ranges from 0020-Apr-03 to today. That is, there is a link for every month for every year since AD 20, which takes a while to render the HTML for.

I have been running it through a debugger trying to figure out where it pulls the start date from. So far I have found that, when rendering the default report (ReportController.php -> function index), the $start date passed to listOfMonths is 0020-Apr-03, which is the value in the Store under the key 'first'.

I haven't yet figured out what originally populates that key, but I replicated it by copying the MySQL database and the .env file (but nothing under storage) from the server to localhost and setting it up as a new install otherwise, so I suspect somehow there is an invalid value in the database somewhere.

**Steps to reproduce**

I have not yet attempted to reproduce this on a new installation without data - I suspect it wouldn't occur again, or not in the same way. My goal is to learn a bit more about where the session 'first' key is pulled from (the database, somewhere?), and once I have verified that, I can attempt to run the upgrade again and check values of such things before and after.

**Comment by JC5** [comment]
Easy. One of your transaction journals has the date "0020-xx-xx".

Just sort the table "transaction_journals" by date and fix it. Then, browse to /flush to clear your cache as per the documentation.

**Comment by ForestBits** [comment]
You were correct. In hindsight it seems pretty obvious. I had a single miskeyed transaction, and it was close enough to the date of the upgrade that I mistakenly assumed the problem was related. But it isn't upgraded related, just bad data entry. Thanks.
