### ISSUE TITLE
Refused to connect to 'http://firefly-domain/chart/account/frontpage' because it violates the following Content Security Policy directive: "connect-src 'self'"

### ISSUE THREAD

**Issue by julien-vu** [firefly-iii/firefly-iii#3637]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is:

After a fresh install, I got the following issues on all routes of the app :

~~- Refused to load the script 'https://firefly-domain/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'nonce-nb=='   ". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.~~ EDIT: from cloudflare, not relevant here

- Refused to connect to 'http://firefly-domain/chart/account/frontpage' because it violates the following Content Security Policy directive: "connect-src 'self'".

**Extra info**
For information : I run the app in a docker environment, behind a traefik and google oauth (thomseddon/traefik-forward-auth ),

The errors are only front related, no logs fomr the containers

Thanks

**Comment by JC5** [comment]
That cloudflare script is not mine. Not sure what spyware is injecting code into Firefly III.

**Comment by JC5** [comment]
Also the nonce is missing. So some piece in your setup seems to be messing with Firefly III.

**Comment by julien-vu** [comment]
Alright, I might have found the issue: 
Axios makes its calls in http for whatever reason even if the environment is https

**Comment by JC5** [comment]
Means that Traefik or somebody else isn't telling the Firefly III container about the https.
