### ISSUE TITLE
[CSV-importer] specific in config file ignored

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#3644]
Hello,
I have this in my config file
```   
...
 "specifics": [
        "IngBelgium"
    ],
...
```
The specific is not checked.

![image](https://user-images.githubusercontent.com/1318140/89171897-18fe3880-d582-11ea-91c7-67dae878168b.png)
![image](https://user-images.githubusercontent.com/1318140/89171926-24516400-d582-11ea-8336-26d1c12adbda.png)

Expected: 
![image](https://user-images.githubusercontent.com/1318140/89171972-33d0ad00-d582-11ea-9be0-4f2338ed0394.png)

**Comment by JC5** [comment]
Nice find, will be fixed in the next release.

**Comment by JC5** [comment]
New release is out, 2.0.2.
