### ISSUE TITLE
Firefly wrongly available on every subdomain not used by nginx

### ISSUE THREAD

**Issue by Rick1029** [firefly-iii/firefly-iii#3645]
I've got Firefly among several other websites running behind nginx on Ubuntu server 20.04. I installed it using composer (from the docs perspective, the self hosted method.) Recently I've realized that Firefly is accessible from any subdomain (including the one set for firefly) except the ones currently in use by nginx. The random subdomains that firefly serves on all behave the same as in the subdomain I allocated in the nginx configuration. My configuration is below;

```
server {
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    server_name firefly.example.com;

        root         /var/www/html/firefly-iii/public;
        index index.html index.htm index.php;

        location / {
                try_files $uri /index.php$is_args$args;
                autoindex on;
                sendfile off;
                auth_basic "Restricted Content - This incident will be reported.";
                auth_basic_user_file /etc/nginx/.htpasswd;

        }

        location ~ \.php$ {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_read_timeout 240;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        }
}
```
For example, I can access Firefly through `firefly.example.com`, `asdf.example.com`, `blahblahjibberish.example.com` etc... I cannot access it from subdomains in use by nginx. I have no idea why, my server configuration is mostly identical to every other configuration I use. Only port 80 and 443 are facing the internet. I have verified removing the config from `sites-enabled` stops firefly from being accessed from any subdomain - so I know nginx is definitely serving firefly, not anything else.

Any help would be greatly appreciated, thank you!

**Comment by JC5** [comment]
I can only imagine your default configuration returns the first site available, or it's configured to return Firefly III.

**Comment by sephrat** [comment]
Yeah I've seen it too. Something to do with Nginx defaulting to one server configuration (I think the first one in alphabetical order) if it can't find the proper one.

**Comment by Rick1029** [comment]
This was the issue sephrat, thanks. Nginx would default to the latest symlinked configuration I added to `sites-enabled.` I've added a block to my default configuration to return a 404 on all wildcards and that fixed it.

Sorry for opening an issue on something purely nginx related, stay safe!

**Comment by Lawri-van-Buel** [comment]
Nginx has a default server option to handle that use case. Else it will use the first server found in config (if you use virtual hosts, the first one in the Config. You can see what nginx has seen in config with the nginx -T option. 
It’s important to know how your webserver works (so adding this to the documentation would be smart)

**Comment by JC5** [comment]
I'm pretty sure this is already in nginx' documentation.

**Comment by JC5** [comment]
Delete the backup default config if present:

```
sudo rm /etc/nginx/conf.d/default.conf
```

Edit the default site config:

```
sudo nano /etc/nginx/sites-available/default.conf
```

Put in the following content:

```
server {
listen 80;
return 444;
}
```

This will make nginx kill the connection.
