### ISSUE TITLE
Add attachment through clipboard

### ISSUE THREAD

**Issue by klausmcm** [firefly-iii/firefly-iii#3648]
**Description**

I'd like to be able to add attachment to transactions by pasting images from the clipboard directly rather than having to save the image to file first.

**Solution**

More convenient method of attaching image attachments to transactions. Would be especially useful for transactions such as online transactions where a confirmation page is produced.

**What are alternatives?**

Save image to file first and upload the file as attachment to the transaction.

**Additional context**

 None

**Bonus points**

None

**Comment by JC5** [comment]
Not a bad idea, I'll see what I can do.

**Comment by klausmcm** [comment]
Thank you for considering. This is a plugin I use for redmine that has the desired behavior. Pasted images are automatically given some name - usually *picture* followed by some numbers. For example, *picture925-1.png*.

https://github.com/peclik/clipboard_image_paste

**Comment by JC5** [comment]
A basic implementation is now in place. Future improvements to this will be part of the new layout. I'm closing this one.

**Comment by klausmcm** [comment]
> A basic implementation is now in place. Future improvements to this will be part of the new layout. I'm closing this one.

Thank you. I look forward to trying this soon.
