### ISSUE TITLE
Syntax error, Firefly unable to start

### ISSUE THREAD

**Issue by jonny1995** [firefly-iii/firefly-iii#3649]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is:

	Syntax error, unexpected 'string' (T_STRING), expecting variable (T_VARIABLE)",
	"startLineNumber": 42,
	"startColumn": 5,
	"endLineNumber": 42,
	

in file /app/Http/Controllers/Controller.php

**Comment by JC5** [comment]
https://docs.firefly-iii.org/faq/self_hosted#i-get-syntax-errors-or-other-problems-when-opening-firefly-iii
