### ISSUE TITLE
[Rules] Spaces are trimmed in "Trigger on value" field

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3652]
Hi,
I'm trying to add some rules based on transaction descriptions, since my bank prepends a two characters code on every description, followed by a space.

So, I have 
`CO AMAZON PAYMENTS EUROPE S.C.A. AMAZON PAYMENTS EUROPE SCA - XXXXXXXXXXXXXXXX - SDD - ADD.DIRETTO SEPA` and I'm trying to create a rule in the form of 'Description starts with "CO "'. 

I then noticed that starting and ending spaces are always trimmed on save, and this could lead to a mismatch with transactions starting with the same two characters but without spaces. 

The same happens with "See matching transactions" button.

Is it the expected behaviour to trim spaces in the "trigger on value" field?

Thanks

PS.I tried updating the rule trigger manually in the db table, adding a space to trigger_value, and it seems to work as expected, and the space is persisted as long as I don't edit the rule again.

----
Debug information generated at 2020-08-04 23:23:38 Europe/Rome for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 3c9524c2-6757-4aec-8d85-5387234150a5 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | it_IT |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-08-01 00:00:00 |
| Session end | 2020-08-31 23:59:59 |
| Session first | 2008-02-08 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Comment by JC5** [comment]
I'll see what I can do. No promises though. 

https://github.com/firefly-iii/firefly-iii/issues/3510
