### ISSUE TITLE
Side-scrolling badges on mobile devices with narrow screens

### ISSUE THREAD

**Issue by marecabo** [firefly-iii/firefly-iii#3657]
**Description**

It would be great, if Firefly would also show the four badges on mobile devices with narrow screens. For me, they are the most informative elements of the UI when on the go.

This feature was already proposed two years ago in https://github.com/firefly-iii/firefly-iii/issues/1489. However, as discussed in that issue, showing them all (under each other) would take too much space of the screen.

**Solution**

Could these badges be placed in a row, through which the user could scroll horizontally? This would

- not waste too much space, 
- allow for large-enough font sizes and
- still resemble the desktop UI.

**What are alternatives?**

 - Switch to a device with a larger screen (inconvenient sometimes)
 - Rotate screen to landscape (Firefly stays locked in portrait?)

**Additional context** / **Bonus points**

I made a mock up to see how it would look. The icons could be optional to gain even more space.
<img src="https://user-images.githubusercontent.com/23156476/89425261-14c84b80-d739-11ea-8b8b-56dc42c45db1.png" data-canonical-src="https://user-images.githubusercontent.com/23156476/89425261-14c84b80-d739-11ea-8b8b-56dc42c45db1.png" width="500" />

Did you already thought about this option and - if not - would you like this way of presenting the badges?

**Comment by JC5** [comment]
I'll put it on the list; depends on the work on the new layout :)

**Comment by JC5** [comment]
I'm picking this up in the new layout. I'll close this one.
