### ISSUE TITLE
3rd party apps are missing in the documentation

### ISSUE THREAD

**Issue by PackElend** [firefly-iii/firefly-iii#3659]
**Description**

3rd party apps are missing in the documentation
https://github.com/mconway/firefly-app/
https://github.com/emansih/FireflyMobile

**Solution**
 add a section for 3rd party apps in the documentation 

**What are alternatives?**
finding apps by coincidence  

**Additional context**
nothing to add 

**Bonus points**
 I would not mind doing a PR against the documentation if welcome

**Comment by JC5** [comment]
Feel free! 👍

**Comment by JC5** [comment]
https://docs.firefly-iii.org/other-pages/3rdparty
