### ISSUE TITLE
Create new Users with register option disabled

### ISSUE THREAD

**Issue by da4id** [firefly-iii/firefly-iii#3660]
Hi, 
I have my private firefly instance running as docker image on my own server. Because this server is exposed to the internet i have disabled the register new user option. Now i want to add new users. So i have to enable this feature and disable it after the user has registered by himself. I think it would be better to send an invitation email to the person i want to add. Or at least an Add User Button in the all Users view.

**Comment by JC5** [comment]
Hi! Thanks for the suggestion. The feature will stay as it is though.

**Comment by kescherCode** [comment]
As a Nextcloud user, which has a user management feature that allows this, I believe this could be a useful feature indeed.
