### ISSUE TITLE
Add a search query field to in "Apply rule/rule group to a selection of your transactions"

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3661]
Recently I started using rules to bulk-edit transactions.

I know bulk-edit is not the main use for rules, but since firefly-iii is lacking a real bulk editor (besides few fields), maybe adding a  query field to restrict the search could speed up this use case, which I believe is not that rare.

For example: I have about 60 transactions I want to edit/clean up (missing dest. account, tag), distributed over a long period of time
- I create a rule based on one of the transactions, using actions to define what I want to change
- When I try to apply that rule, it is incredibly slow, probably because it must process all the triggers for every transaction in the specified period

Using the search, it finds most of them in seconds, together with a few other transactions I don't care about. If you could use that query to restrict the transactions to process, it would probably be REALLY incredibly fast in comparison.

Obviously the query would not override the rule triggers, only reduce the starting dataset.

Someting like this:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/115389/89476097-15d59900-d78a-11ea-9a3b-8985054dfc69.png">

Since I was mocking it up, I added as a bonus a button that would open a modal (or a new browser tab) and show the query results, don't hate me :)

I'm willing to give a try to a PR for this, if you think it could be incorporated (and if I manage to undestand how to setup a dev environment... nano in a docker container over a double ssh is not really the best way).

**Comment by JC5** [comment]
Adding a search to a rule which is in itself also a "search" is incredibly counterintuitive. You could also choose to use the command line to execute rules.

I'll pick it up as an enhancement to the rule engine, which indeed is pretty slow selecting the transactions to apply rules to.

**Comment by psychowood** [comment]
Do you have any reference to the CLI usage? I only seem to find things related to importing/exporting transactions. 

Thanks

**Comment by psychowood** [comment]
This could be connected with #3689, functionality-wise.

**Comment by JC5** [comment]
> When I try to apply that rule, it is incredibly slow, probably because it must process all the triggers for every transaction in the specified period

The new rule engine is insanely fast compared to the old one. I went from 1hr to 30 seconds in some tests. This should already greatly improve your experience. If you can, try running the latest `develop` image or `develop` code.

**Comment by JC5** [comment]
This page isn't live yet, but the new queries are now also documented and may help you:

https://docs.firefly-iii.org/concepts/search

**Comment by psychowood** [comment]
Yes I've noticed it today after updating to alpha3, really interesting stuff 🥇 
Regarding the rule engine, I don't have much time to keep a second copy with the develop branch these days... is it safe enough to use it as a daily driver? I don't mind errors every now and then, it's part of the game, I'm interested mainly in not losing the ability to go back to alpha (or stable) branch and the risk of losing data.

**Comment by JC5** [comment]
Should be no problem going back and forth, the DB changes aren't that big. Nothing backwards incompatible at any rate. The rule engine may fail when you're using non-strict rules with lots of "description contains" triggers. Those will create exotic conditions. But other than that I believe everything's safe enough.

**Comment by psychowood** [comment]
Thanks. I'm currently running alpha3+develop on two different ports, with the same DB.

Will let you know if I'll be able to play with rules (even if I'm currently out of transactions :) I updated most of them with scripts.
