### ISSUE TITLE
Running the linked rule from a bill does not execute all actions

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3662]
Hi,

Steps to reproduce:
1. Create a test transaction named "The House payment"
1. Have a Liability Account, tested with a Mortgage named "The House"
1. Create a new Bill "The House Mortgage" 
1. **Edit the automatically created rule**
    - edit the trigger in "Description Starts With" -> "The house"
    - adding the action "Set destination account" -> "The House"
1. Save
1. Run the rule from the Bill page using the button "Run rules again, on all transactions"
1. The transaction at 1. is linked correctly to the bill, **but without the correct destination account set**
1. Go to the Rules page, select "Apply rule "Rule for bill "The House - mortgage"" to a selection of your transactions" 
1. Wait (it takes a lot more than the button in the bill page)
1. Destination account is then set correctly

Transactions created **after** the rule is in place are updated as expected.

this was replicated in the demo site. I'm not sure if the demo site is automatically reset, but if not you can replicate with:

- this rule https://demo.firefly-iii.org/rules/edit/5
- on this bill https://demo.firefly-iii.org/bills/show/10
- for this transaction https://demo.firefly-iii.org/transactions/show/445

Using the Button "Run rules again" ( https://demo.firefly-iii.org/bills/rescan/10 ) does not update the destination account

**Comment by JC5** [comment]
That's as designed. I'll make sure the help text mentions it.
