### ISSUE TITLE
De-activated accounts do not appear anywhere

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#3664]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is:

I just de-activated 3 of my accounts and now they are gone from the Asset accounts list. Not really an issue but there is no other list with inactive accounts...
It means I can't access the transactions anymore from the account itself

**Steps to reproduce**
Deactivate an account and search for it :D

**Comment by sephrat** [comment]
There is a dedicated page to display inactive accounts:
![image](https://user-images.githubusercontent.com/34862846/89496325-74b30680-d7ba-11ea-87ff-99b4eae45378.png)

**Comment by MacPaille** [comment]
Indeed I did not saw that as the font is really small compared to the rest 👍 

Maybe adding some colors or bigger font size would help help find it :)

**Comment by JC5** [comment]
It's a bit of a hack, that page. I'll pick it up as an enhancement. :+1:

**Comment by MacPaille** [comment]
Thanks a lot!

**Comment by JC5** [comment]
I'm closing this. I'm building a new layout that will contain a better overview of inactive accounts.
