### ISSUE TITLE
Export running in background

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#3672]
**Description**
With my current firefly transaction database of 19k+ records running the export in the browser takes around 10 minutes (I had to increase my haproxy timeout to be able to get the file). As this DB will still grow in the future time will just increase more and more...

I know we can run the exporter in cli version but as I'm running my FF instance in a docker container on my Synology I don't have access to the console (I have but it crashes after some seconds and even sometimes it crashes the container itself).

**Solution**
As there is a /storage/export folder on the instance and it's requested to do its mapping to a static folder on the docker host it would be nice when we run the export to have an option to run it in background (run the cli command) to directly save the file in that export folder. So you don't expect the file to be downloaded from the browser you will have to check later on the disk.

More improvement would be a form to select each available option values (like account, date range etc...) of the exporter to run it in the cli in background.

And last one would be a listing of these exports in the export folder so in the end you can download the files from the browser 😅 

**What are alternatives?**
Do nothing and keep current system 😄 

**Additional context**
I don't know how much people have bigger databases and maybe it's just my synology that doesn't provide enough processing power to reply faster. But I think it would be a nice improvement anyway.

**Bonus points**
Can I get some for the feature of the year? 😺

**Comment by JC5** [comment]
Question: why do you use the export function to export your entire database so often?

**Comment by MacPaille** [comment]
Good question indeed. As I use the csv-importer now it won't happen (maybe to have a backup outside the DB) but as I was entering all my transactions manually I sometimes made mistakes. When looking at the current account balance I saw differences with what was on the account.

So I had to export the whole DB (again can't use cli so was not able to do only one account) to compare to my bank extracts to see where the mismatch is. Finally found everything and this should not happen anymore thanks to the csv-importer 😄

**Comment by JC5** [comment]
Ah yes. I usually do this with the user interface itself; not with the export.

But I made the export in the user interface simple because I want to push people to the command line. Doing this over the web is tricky, as you can see.

Calling something async from the web isn't possible I'm afraid; I could use something like `exec()` but it's a hack, and pretty unsafe.

What you could do is append the command with ` &`. That should make your Synology run the command in thhe background.

**Comment by MacPaille** [comment]
I totally understand that's fine I'll continue to use the complete export in the browser 👍
Hope I'll never hit another limit like memory etc...
