### ISSUE TITLE
Search results page size not impacted by Layout Preferences nor by .env variable 

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3673]
Hi,
I suppose this is by design because the .env file has the specific variable SEARCH_RESULT_LIMIT), but it is probably not clear when looking at the preferences page:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/115389/89712107-feb3c880-d98e-11ea-98f0-5ba751cf4afd.png">

Moreover, even changing the line in .env did not change the search results page size, tho:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/115389/89712313-5f8fd080-d990-11ea-8d56-49cc3a08cc16.png">

Always 50, both increasing and decreasing SEARCH_RESULT_LIMIT

<img width="356" alt="image" src="https://user-images.githubusercontent.com/115389/89712321-69b1cf00-d990-11ea-853e-7f71af74790b.png">

Docker shows the variable as correctly initialized (orrectly 10, that was another last try):

<img width="398" alt="image" src="https://user-images.githubusercontent.com/115389/89712458-39b6fb80-d991-11ea-85d7-bb125f5d8cbd.png">

I'm not sure which one should be the correct behaviour...

EDIT: Restarting in debug mode did not help showing the variables in the console. The only reference I found in logs is this one:

> [2020-08-08 16:12:44] local.DEBUG: Start of searchTransactions()  
> [2020-08-08 16:12:44] local.DEBUG: GroupCollector::startQuery  
> [2020-08-08 16:12:44] local.DEBUG: GroupCollector: The limit is now 50  
> [2020-08-08 16:12:44] local.DEBUG: GroupCollector: page is now 1  
> [2020-08-08 16:12:45] local.DEBUG: Will NOT set previous URL to http://dockervm:8081/search/search?page=1  
> [2020-08-08 16:12:49] local.DEBUG: Trying to set en_US.utf8  
> [2020-08-08 16:12:49] local.DEBUG: Trying to set en_US.UTF-8  
>

**Comment by JC5** [comment]
Nice find, the search limit isn't used as it should. Will be fixed in the next release :+1:

**Comment by JC5** [comment]
And as an FYI. The search used to be limited because it was insanely resource intensive. This is a lot less of a problem these days, so it's more of an historical thing. I've removed this variable from the preferences. So the number from your preferences will also apply to the search.
