### ISSUE TITLE
Cannot update transactions's currency

### ISSUE THREAD

**Issue by weimdall** [firefly-iii/firefly-iii#3675]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is:

New updated transactions on my account are in the wrong currency when switching source account that use a different currency.
Firefly throw an error :
```
...
[2020-08-08 14:07:03] local.ERROR: Foreign currency is equal to normal currency (CAD)  
[2020-08-08 14:07:35] local.ERROR: Foreign currency is equal to normal currency (CAD)  
...
```

In the following screenshot, the first transaction has been directly created in Euro.
The second transaction has been updated and moved from an asset account in CAD.
![2020-08-08-143849_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/89717507-3b7ac200-d985-11ea-9252-947738506e7d.png)

**Steps to reproduce**
1. Create an asset account in Dollar
2. Create a second asset account in Euro
2. Create a transaction in Dollar on the first asset account
3. Update this transaction : 
- Switch the source asset account to the Euro one -> JS will update the currency label
- Save
4. The currency has not been properly edited

**Extra info**
Debug information generated at 2020-08-08 14:31:21 America/Montreal for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-09-30 00:00:00 |
| Session first | 2018-08-16 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0 |

**Bonus points**
I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Indeed, that's a bug. Thanks!
