### ISSUE TITLE
source: (and destination:) search filters both source and destination field indistinctly

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3678]
Firefly III version **5.3.3** here.

I have an account named "Paypal", searching for either "source:paypal" or "destination:paypal" or both of them together leads to the same results:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/115389/89734840-de533f00-da5e-11ea-9d1b-647e101d3571.png">

Same behaviour on the [demo site](https://demo.firefly-iii.org/search?search=destination%3Achecking).

EDIT: I'm not sure if it is the correct point, but [Search.php](https://github.com/firefly-iii/firefly-iii/blob/bc5b2085b9540c916a925acc378e49b41f9054b8/app/Support/Search/Search.php#L213) does not seems to differentiate between source and destination modifier.

Btw: since it is not possible to search for an account using its full name (in case of special chars/spaces), would it be possibile to make it accept the numerical account id?

**Comment by JC5** [comment]
Yes, that's a bug. Nicely spotted. Clearly lazy programming on my side 😅 . Will be fixed in the next release.

**Comment by JC5** [comment]
Oh and re: your last point: I'm working on a more advanced version of the query parser, which means that the following should work: `source:"some account"`.
