### ISSUE TITLE
file_get_contents(/var/www/demo/resources/lang/cs_CZ/locales.json): failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3681]
**Bug description**
When you set language to cs_CZ, the preferences page is broken because locales.json does not exist.
No idea why that file does not exist in this language, it's present for every other language.
I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
I forgot to add it 😬. Will be fixed in the next release.
