### ISSUE TITLE
Missing Kubernetes Manifests

### ISSUE THREAD

**Issue by iMerica** [firefly-iii/firefly-iii#3685]
**Bug description**
Kube configs are missing

**Steps to reproduce**
- Visit Docs and navigate to [Kubernetes section](https://docs.firefly-iii.org/installation/k8n).
- Observe that is refers to `.deploy/kubernetes`
- Clone [repo](https://github.com/firefly-iii/firefly-iii) and ls `.deploy/` and observe it has no such files in master.

**Comment by JC5** [comment]
I'll update the docs: https://github.com/firefly-iii/kubernetes !

Thanks for letting me know.

**Comment by JC5** [comment]
Done! :+1:

https://docs.firefly-iii.org/installation/k8n
