### ISSUE TITLE
Help with setting apache proxy for docker

### ISSUE THREAD

**Issue by beather** [firefly-iii/firefly-iii#3686]
Hi,

Today I spend a lot of time trying to get work apache proxy for firefly docker instance.. I folowed this guide https://dzhy.dev/2019/04/06/Firefly-III-Setup-with-Docker-and-HTTPS/, installed docker, set it to run on localhost port 4040 as mentioned in guide, allowed TRUSTED_PROXIES=** \ and run docker... I could see that it's listening on port 4040

My apache conf:

```
<VirtualHost *:80>
	  
   ServerName domain
   
# Redirect any HTTP request to HTTPS
   RewriteEngine On
   RewriteCond %{HTTPS} off
   RewriteRule (.*) https://%{SERVER_NAME}/$1 [R,L]
	 
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin mail
    ServerName domain
    SSLEngine On

    # Certs
    SSLCertificateFile path
    SSLCertificateKeyFile path
    SSLCertificateChainFile path
    Include /etc/letsencrypt/options-ssl-apache.conf

    # ProxyPass
    SSLProxyEngine On
    ProxyRequests Off
    ProxyPass "/" "http://127.0.0.1:4040/" retry=1 acquire=3000 timeout=600 Keepalive=On
    ProxyPassReverse "/" "http://127.0.0.1:4040/"
   
    RequestHeader set X-Forwarded-Proto "https"

    

</VirtualHost>
```

But I'm still getting 502 Proxy error: Reason: Error reading from remote server

I'm kinda lost, maybe some advice from anyone running this setup?

Thanks !

**Comment by JC5** [comment]
The actual port is 8080.

On the page you followed the Firefly III docker image is *listening* at port 80 and *forwarded* to port 4040.

In your example, you wrongly configured Apache to listen at port 4040 AND forward to 4040. Makes no sense.

What you do is:

```
     ProxyPass "/" "http://127.0.0.1:8080/" retry=1 acquire=3000 timeout=600 Keepalive=On
    #ProxyPassReverse "/" "http://127.0.0.1:4040/"
```

**Comment by beather** [comment]
Hi JC5, thanks for fast response ! I overlooked this, however when I change as you suggest I started getting "503 Service Unavailable" 

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by JC5** [comment]
You can debug that by trying to connect to the docker image directly. For example, "curl http://127.0.0.1:8080" to see what happens.

**Comment by beather** [comment]
I checked and I'm still confused.. In docker ports I could see port 8080
```

docker container list
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS              PORTS                              NAMES
db0beae96f67        jc5x/firefly-iii:latest   "/entrypoint.sh"    2 hours ago         Up 4 seconds        8080/tcp, 127.0.0.1:4040->80/tcp   firefly-iii-c1
```
but in netstat I can see only port 4040 as listening, no 8080

`tcp        0      0 127.0.0.1:4040          0.0.0.0:*               LISTEN      489459/docker-proxy `

Also curl gives me this result:

```
curl http://127.0.0.1:4040
curl: (56) Recv failure: Connection reset by peer
curl http://127.0.0.1:8080
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
```
Also I tried to change firefly settings to listen on 8080 (-p 127.0.0.1:8080:80 \) and I'm getting with curl Connection reset by peer again.

**Comment by JC5** [comment]
Why not use the docker compose file?

**Comment by beather** [comment]
I already solved this. Problem was with understanding ports position in env setting, however I have other problem with DB now.. I will probably create separate issue for this to not mix it up.
