### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by wkjyeung** [firefly-iii/firefly-iii#3690]
I am running Firefly III version 5.3.3.

**Description**
I have deployed Firefly III version 5.3.3 on a LAMP stack, I found even though I entered the home page with https, all of the links I click next are with http, including the Login. I spent a couple of days searching and found people are also discussing the force https issue, most of the solutions are saying to use Nginx instead.

Since I can only use Apache, I finally came across in `app/Providers/AppServiceProvider.php`, there is a conifg to force https. I am not sure why this only enabled when the app is running in Heroku. I removed the condition and https works perfectly on my env. Can anyone explain?

```
        if ('heroku' === config('app.env')) {
            URL::forceScheme('https');
        }
```

**Extra info**
OS: Ubuntu 16.04
Broswer: Firefox 68
PHP: 7.4.9

**Comment by JC5** [comment]
How have you deployed Firefly III? If it's on a LAMP stack directly, it should pick up the HTTPS directly from your Apache config. 

When Apache is acting as a reverse proxy (using Docker for example), you must configure it to forward the correct protocol to the image.

**Comment by wkjyeung** [comment]
Deployed using Composer following the doc
`composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 5.3.3`

Could you give more details on how to configure the Apache without enabling `URL::forceScheme('https')`?

**Comment by JC5** [comment]
I don't know. There's nothing special. I assume you already have an ssl certificate and everything? A basic VirtualHost for Apache can be Googled pretty easily:

```
<VirtualHost *:443>
  ServerName www.foo.com
  DocumentRoot /var/www/www.foo.com/htdocs

  CustomLog /var/log/apache/www.foo.com-access.log combined
  ErrorLog /var/log/apache/www.foo.com-error.log

  # Example SSL configuration
  SSLEngine on
  SSLProtocol all -SSLv2
  SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5
  SSLCertificateFile "/var/www/www.foo.com/ssl/server.crt"
  SSLCertificateKeyFile "/var/www/www.foo.com/ssl/server.key"
</VirtualHost>
```
