### ISSUE TITLE
[Feature Request] Add Tags when "Edit Selected Individually"

### ISSUE THREAD

**Issue by dugite-code** [firefly-iii/firefly-iii#3691]
**Description**

I would like to be able to add tags when using the "Edit Selected Individually" Action in the Transactions menu much like the edit selected in bulk option.

**What are alternatives?**

Some way to assign multiple tags to transactions in a bulk overview

**Comment by JC5** [comment]
I'm not going to add this to the "Edit Selected Individually".

> Some way to assign multiple tags to transactions in a bulk overview

This is already possible.

**Comment by dugite-code** [comment]
Currently it's only possible to assign the same tags to multiple transactions, I was requesting a quick way of assigning multiple different tags to transactions in one overview.

I'll admit this is might be more of a result of how I use a script to automatically import transactions to firefly-iii and then I go back after the fact to classify them manually rather than manually adding the transactions

**Comment by JC5** [comment]
Ah ofcourse. But sorry no, it is what it is for now.

**Comment by JC5** [comment]
You could also use rules to further classify transactions.
