### ISSUE TITLE
Spectre-importer broken link back to firefly

### ISSUE THREAD

**Issue by cosmincc** [firefly-iii/firefly-iii#3692]
**Bug description**
I am running Spectre-Importer version 1.0.4, and my problem is:

Link back to the firefly account is broken.

**Steps to reproduce**
I get http://localhost/fireflyaccounts/show/1 (with `FIREFLY_III_URI=http://localhost/firefly` in .env)
Adding a slash to it (`FIREFLY_III_URI=http://localhost/firefly/`) give an error (presumably due to the double slash:
GuzzleException: Client error: `GET https://localhost/firefly//api/v1/accounts?type=asset&page=1` resulted in a `404 Not Found` response: {"message":"Resource not found","exception":"NotFoundHttpException"}
coming from: app/Http/Controllers/Import/ConfigurationController.php (line 79)

**The fix should be simple**
- ensure there is no trailing slash when reading the config.
- add a starting slash to any relative URIs in the templates like here: app/Http/Controllers/Import/ConfigurationController.php:84 -> should be `sprintf('%s/accounts/show/%d', ...)`

**Comment by JC5** [comment]
A double slash shouldn't be a problem, make sure you look into that. But I'll see what I can do to make this more robust.

**Comment by JC5** [comment]
New release will be here tomorrow.

**Comment by JC5** [comment]
1.0.5 is out!
