### ISSUE TITLE
[API] unable to store new user with curl

### ISSUE THREAD

**Issue by dugite-code** [firefly-iii/firefly-iii#3693]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is:

When attempting to store a new user via the API and curl I receive a undefined function exception.

I was curious to see if I could create a user with user registration disabled after reading issue #3660.  **Note:** I tried this with both user registration enabled and disabled.

**Steps to reproduce**

Post to the API using the endpoint `/api/v1/users` as outlined in the [API Docs](https://api-docs.firefly-iii.org/#/users/storeUser)

Curl command

```shell
curl -X POST "https://example.tld/api/v1/users" -H  "accept: application/json" -H  "Content-Type: application/json" -H "Authorization: Bearer **[MY Token Here**" -d "{\"email\":\"user@example.tld\",\"blocked\":false,\"blocked_code\":\"email_changed\"}"
```

Response

```shell
{"message":"Internal Firefly III Exception: Call to undefined function FireflyIII\\Repositories\\User\\str_random()","exception":"Error"}
```
**Extra info**
Firefly-III is installed via the official docker image.

**Comment by JC5** [comment]
Ah nice find, that's a bug. It will be fixed in the new release.

Having said that, yes, the API allows you to register users even when user registration is disabled.
