### ISSUE TITLE
Docker MY_SQL SSL error

### ISSUE THREAD

**Issue by DieterKoblenz** [firefly-iii/firefly-iii#3695]
**Bug description**
I am running Firefly III on docker using tag latest and my problem is:
`Could not poll the database: SQLSTATE[08006] [7] received invalid response to SSL negotiation: p (SQL: select "id", "name", "data" from "configuration" where "name" = is_demo_site and "configuration"."deleted_at" is null limit 1)`

**Extra info**
I am using a MariaDB which is accessible from provided .env arguments. I tried with and without MYSQL_USE_SSL. I want to use it without SSL.

**Bonus points**
```
docker run -d \
-v firefly_iii_export:/var/www/firefly-iii/storage/export \
-v firefly_iii_upload:/var/www/firefly-iii/storage/upload \
-p 9123:8080 \
-e APP_KEY=xxxx \
-e DB_HOST=192.168.1.4 \
-e DB_PORT=3306 \
-e DB_DATABASE=firefly \
-e DB_USERNAME=firefly \
-e DB_PASSWORD= xxxx \
-e MYSQL_USE_SSL=false \
-e DEFAULT_LANGUAGE=nl_NL \
jc5x/firefly-iii:latest
```

**Comment by JC5** [comment]
What error do you get when you run it like this?

```
docker run -d \
-v firefly_iii_export:/var/www/firefly-iii/storage/export \
-v firefly_iii_upload:/var/www/firefly-iii/storage/upload \
-p 9123:8080 \
-e APP_KEY=xxxx \
-e DB_HOST=192.168.1.4 \
-e DB_PORT=3306 \
-e DB_DATABASE=firefly \
-e DB_USERNAME=firefly \
-e DB_PASSWORD=xxxx \
-e DEFAULT_LANGUAGE=nl_NL \
jc5x/firefly-iii:latest
```

**Comment by DieterKoblenz** [comment]
`Could not poll the database: SQLSTATE[08006] [7] received invalid response to SSL negotiation: p (SQL: select "id", "name", "data" from "configuration" where "name" = is_demo_site and "configuration"."deleted_at" is null limit 1)`

**Comment by JC5** [comment]
Sorry, I can't replicate this locally. Forcing SSL without a valid config gives me this:

```
[2020-08-13 16:21:11] local.ERROR: SQLSTATE[HY000] [2006] MySQL server has gone away (SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2006): SQLSTATE[HY000] [2006] MySQL server has gone away (SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE') at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
```

In your error, I wonder where the extra `p` comes from?

**Comment by DieterKoblenz** [comment]
Can't figure it out, have tried several ways now. Could be possible that my mariadb docker instance is configured wrongly, but I don't have the skill to figure that out. 

I'll use sqlite as a workaround.

**Comment by JC5** [comment]
Mmmm keep me posted. But rather spin up a second database. It’s more resilient against crashes and stuff.

**Comment by livitup** [comment]
I'm running into the same problem - brand new mariadb install with the following command:

`docker run --name mariadb -v /var/snap/docker/data/mariadb_data:/var/lib.mysql -e MYSQL_ROOT_PASSWORD=xxxxx -d mariadb`

The mariadb is accessible from the mariadb container command prompt as well as the docker host command prompt:

` ~  mysql -u root -p -h 172.17.0.8
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 259
Server version: 5.5.5-10.5.5-MariaDB-1:10.5.5+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>`

Starting a firefly container with the following command:

` ~  docker run -d \
-p 8081:8080 --name fireflyiii -v firefly_iii_export:/var/www/firefly-iii/storage/export \
-v firefly_iii_upload:/var/www/firefly-iii/storage/upload \
-e APP_KEY=xxxxxxxxx \
-e DB_HOST=172.17.0.8 \
-e DB_PORT=3306 \
-e DB_DATABASE=fireflyiii \
-e DB_USERNAME=root \
-e DB_PASSWORD=xxxxxxx \
-e VIRTUAL_HOST=budget.home.ohnstad \
jc5x/firefly-iii:latest`

Results in the following error:

`local.ERROR: Could not poll the database: SQLSTATE[08006] [7] received invalid response to SSL negotiation: m (SQL: select "id", "name", "data" from "configuration" where "name" = is_demo_site and "configuration"."deleted_at" is null limit 1) {"exception":"[object] (FireflyIII\\Exceptions\\FireflyException(code: 0): Could not poll the database: SQLSTATE[08006] [7] received invalid response to SSL negotiation: m (SQL: select \"id\", \"name\", \"data\" from \"configuration\" where \"name\" = is_demo_site and \"configuration\".\"deleted_at\" is null limit 1) at /var/www/firefly-iii/app/Support/FireflyConfig.php:92)`

Note that I have the random 'm' in front of my SQL command... not the original reporter's 'p'.

Unsure if these are relevant, but there are several:

'local.INFO: Could not create or generate installation ID. Do not continue.'

log messages prior to the ERROR.

I'll try a few other things in the mean time, but happy to leave this busted pair of containers available for further testing.

**Comment by livitup** [comment]
New test on a fresh mysql container:

` local.ERROR: Could not poll the database: SQLSTATE[08006] [7] received invalid response to SSL negotiation: J (SQL: select "id", "name", "data" from "configuration" where "name" = is_demo_site and "configuration"."deleted_at" is null limit 1) {"exception":"[object] (FireflyIII\\Exceptions\\FireflyException(code: 0): Could not poll the database: SQLSTATE[08006] [7] received invalid response to SSL negotiation: J (SQL: select \"id\", \"name\", \"data\" from \"configuration\" where \"name\" = is_demo_site and \"configuration\".\"deleted_at\" is null limit 1) at /var/www/firefly-iii/app/Support/FireflyConfig.php:92)`

Note the 'J' this time in the error message...

Docker host is Debian 20.04.1 if it matters.

**Comment by livitup** [comment]
Even more info... I tried to run the seed commands from the standalone install via 'docker exec' and got the following:
```

In Connection.php line 671:

  SQLSTATE[08006] [7] received invalid response to SSL negotiation: J (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE')


In PDOConnection.php line 31:

  SQLSTATE[08006] [7] received invalid response to SSL negotiation: J


In PDOConnection.php line 27:

  SQLSTATE[08006] [7] received invalid response to SSL negotiation: J

```

**Comment by JC5** [comment]
Add the following environment variable:

```
-e DB_CONNECTION=mysql \
```

Error is on my side. Apologies.

**Comment by livitup** [comment]
You know, I should have thought to try that.  Thanks for the reply and the quick fix!
