### ISSUE TITLE
Spectre Import: Inactive connection, no accounts.

### ISSUE THREAD

**Issue by DieterKoblenz** [firefly-iii/firefly-iii#3697]
I am running Firefly III docker.

**Description**
I am trying to use the Spectre Importer. I've made keys, requested and received access and tried to make a connection which worked. Now when I use the importer, it does make a new connection. However the connection remains inactive, and no accounts are imported. 

**Extra info**

**Bonus points**
![image](https://user-images.githubusercontent.com/2961896/90168054-dec04280-dd9c-11ea-83be-c4c1e12303f2.png)

**Comment by JC5** [comment]
Not something I can fix I'm afraid. Dutch banks never work well in combination with Spectre.

**Comment by DieterKoblenz** [comment]
Alright, that's a shame. Thanks for the quick answer!!
