### ISSUE TITLE
Search suggestions: account/contextual search/sort results/filters/tag view

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3700]
Hi,
here we are with some other scattered suggestions on the search function.

1. Add an "account/account_id" filter to search for transactions having a single account as either source or destination (see point 2). Currently you can't search for both source and destination, AFAIK. 

2. Add a search bar in the single account page ( /accounts/show/XXX ) that search transactions having that account as either source or destination (simply add the "account" filter by default), or make global search done from account view inherit the current account (maybe using referer http header, or pre-setting the field when you are in /accounts/show/*).

3. Create two new custom filters sort_asc_by and sort_desc_by that take another filter key (amount, source, date, ...) as value, setting the order you want the results in. Bonus: adding a separate select tag to avoid multiple contextual sorts attributes

4. Adding some form fields to easen inserting filters to the query

<img width="880" alt="image" src="https://user-images.githubusercontent.com/115389/90266896-04108780-de55-11ea-9c78-e00de7eb614b.png">

5. Use tag-like view to group filters (the free-text search would be probably difficult to handle). Bonus: show description instead of filter key (e.g. "Source account" instead of "source:").

![image](https://user-images.githubusercontent.com/115389/90271982-f959f080-de5c-11ea-8c06-3ce985397425.png)

3,4 and 5 combined together:

![image](https://user-images.githubusercontent.com/115389/90271881-cfa0c980-de5c-11ea-8654-63d730465977.png)

I think I can provide a PR for 1,2, 4, maybe for 3 with a bit of trial and error, if you think these could be useful.

PS.(Un)related to point 2: the same behaviour could be inherited from the Report page, if you click on the left menu item when browsing an account page.

**Comment by JC5** [comment]
Hey, those are some pretty good ideas. Also, thanks for the support! 😁 

Let's see:

1) This is already possible. You can use `source/destination:` and `from/to:`. Search for either of those (like `account` isn't possible at the moment. I'll pick it up.
2) No. It just adds more magic behavior, or more buttons. It could be part of the introduction popups.
3) No. Not as flags. But I can see the need for sorting the results. I'll pick it up as an enhancement, to improve the collector that currently does the actual searching, to be able to sort on different things.
4 + 5) Yes, in the new layout, that would be useful!

**Comment by psychowood** [comment]
The support is well deserved :)

Another bit: is there a way to search for uncategorized transactions?

**Comment by JC5** [comment]
Thanks:) Quick mobile reply: check the top of the list of categories.

**Comment by psychowood** [comment]
Interesting, didn't notice that. A filter would be more useful, tho :P 

On a side note: is it expected to show Transfers too? I'm currently not categorizing transfers, I thought it was not useful and could mess up totals, am I wrong?

**Comment by JC5** [comment]
It doesn't mess up anything with me, although most of my transfers are categorized simply "money management"

**Comment by psychowood** [comment]
Right, I was considering that my transfers are mostly 1:1 with expenses because of my bank exports, so my idea was to use to add a link and use the same category of the expense.

**Comment by JC5** [comment]
This will be part of the new layout I'm building and is on my list.
