### ISSUE TITLE
OAuth settings missing

### ISSUE THREAD

**Issue by forcaeluz** [firefly-iii/firefly-iii#3701]
**Bug description**
I am running Firefly III version 5.4.0 alpha 1, and my problem is:
The settings for OAuth (Clients and personal access codes) seem to be missing from the "profile" page. Demo site has the same issue.

**Steps to reproduce**
Visit: https://demo.firefly-iii.org/profile

**Extra info**

**Bonus points**

**Comment by JC5** [comment]
Thx. Probably left some debug code up. I’ll check it out after the weekend.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/commit/ce3c1cccc3733b0a6b2801f1dcf1f1139981d519
