### ISSUE TITLE
CSV importer Fails on bad characters in CSV file

### ISSUE THREAD

**Issue by TheVetter** [firefly-iii/firefly-iii#3702]
**Bug description**
I am running Firefly III version 5.3.3 and CSV import tool v2.0.5,  and my problem is:
that the CSV importer tool fails to import my CSV file from my bank because of this line: (Note: I included the header for context)
```
"Date","Description","Comments","Check Number","Amount","Balance"
"02/12/2020","External Deposit Tax Commissioner  - NDSTTAXRFD  RMR*IV*x9496**88\","","","$88.00","$3,330.95"
```

When I change the line to:
```
"Date","Description","Comments","Check Number","Amount","Balance"
"02/12/2020","External Deposit Tax Commissioner  - NDSTTAXRFD","","","$88.00","$3,330.95"
```
I am able to import my CSV

Attached is my json file and stdout/stderr logs from the csvimport tool container. 
[logsandjson.zip](https://github.com/firefly-iii/firefly-iii/files/5079040/logsandjson.zip)

**Extra info**
both CSV import tool and Firefly are running in docker on Arch linux using firefox. 

**Bonus points**

![image](https://user-images.githubusercontent.com/19328786/90316001-58fbde80-dee5-11ea-8de0-7124e0f5132a.png)

**Comment by JC5** [comment]
A backslash just before a “ means it’s an escape character. It should be \”” instead of \”. 

Your bank is sending you invalid CSV files. This is not something I can fix I’m afraid.

**Comment by TheVetter** [comment]
I understand. I figured I'd share . 

What about working on a better error message to help identify issues with the csv file? 
like an error message the says: "error on line 243 invalid file format"

**Comment by JC5** [comment]
Not really sure. The library I use tries to solve the problems as best as it can. It “forwards” the errors to the Firefly III CSV importer to solve. It will almost never crash. 

This is nice but also problematic as you noticed. I can’t really predict what will happen with invalid CSV files. 

I’ll make sure to make the CSV importer more robust of course. But I’m also depending on libraries that can act very unpredictable.
