### ISSUE TITLE
Beta version considered "below minimum required version" for CSV Importer

### ISSUE THREAD

**Issue by Skrallexxx** [firefly-iii/firefly-iii#3703]
**Bug description**
I am running Firefly III version 5.3.0-beta.2, and my problem is:

When trying to use the CSV Importer, I get the following error:

```
Your Firefly III version 5.3.0-beta.2 is below the minimum required version 5.3.0 
```

It would seem the version check doesn't work with the beta versions. Is this intentional to prevent the importer being used in beta versions?

Since the CSV Importer project on GitHub doesn't allow issues to be created, I assume this is the right place to put this. 

**Steps to reproduce**

- Install Firefly III with Docker
- Install Firefly III CSV Importer with Docker
- Give CSV Importer the correct variables for URI, Access Token, etc. and start it
- Browse to CONTAINER_IP:81

**Extra info**

Debug information generated at 2020-08-16 17:36:44 Australia/Perth for Firefly III version **5.3.0-beta.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.0-beta.2 |
| Firefly III API | 1.2.0 |
| PHP | 7.4.7 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | ce8a15f2-ca91-48e2-9270-1061e47e5f0d |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start |  |
| Session end |  |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0 |

![image](https://user-images.githubusercontent.com/4609632/90331474-39e57580-dfe7-11ea-968a-767fb7e0ea0c.png)

**Comment by psychowood** [comment]
5.3.0-beta.2 is actually before 5.3.0...

**Comment by Skrallexxx** [comment]
> 
> 
> 5.3.0-beta.2 is actually before 5.3.0, so that's correct.

You are correct, and I am dumb. Thanks for the spot! 👍
