### ISSUE TITLE
Docker version stops itself whenever ssh window is resized

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#3708]
**Bug description**
I am running Firefly III version 5.3.3

**Steps to reproduce**
1. SSH to your server
2. Start docker version of the Firefly in the foreground (without `-d` switch)
3. Resize SSH window

**Expected behavior**
Size of the window should not affect Firefly

**Actual behavior**
`caught SIGWINCH, shutting down gracefully` is printed into console and Firefly is stoped.

**Comment by JC5** [comment]
What's your OS? This doesn't happen to me.

**Comment by JC5** [comment]
This could be the root cause.

https://github.com/docker-library/php/issues/887#issuecomment-530478852

**Comment by matejdro** [comment]
Linux, connecting from KDE Konsole.

From what I see, SIGWINCH signal is expected to be thrown since it signifies window resize: https://www.gnu.org/software/libc/manual/html_node/Miscellaneous-Signals.html . But it shouldn't cause the Firefly to stop.

**Comment by JC5** [comment]
Yes I know that. And for me, it doesn't. So whatever the cause, it's not the image. Ubuntu/Mac both have no problems with resizing the SSH session

**Comment by matejdro** [comment]
I found a way to reproduce it without the need for terminal that sends SIGWINCH signal:

1. Start the container normally
2. Run `docker top CONTAINER_NAME` to get the PID of the process
3. Run `kill -SIGWINCH [PID]`

**Comment by matejdro** [comment]
I think issue is still active

**Comment by matejdro** [comment]
Still not stale...

**Comment by JC5** [comment]
I’m not going to fix this. I use a standard Docker image and this is an upstream bug as far as I’m concerned.
