### ISSUE TITLE
API not accepting `start_date` and `end_date` on `/api/v1/budgets/[ID]`

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#3709]
Hello, me again with another question. I am running Firefly III version 5.3.3.

**Description**

I am attempting to get amount spent for a budget via API. Note that with budget 15 (you can see ID in the browser tooltip bottom left) I have spent 9.99€ between Aug 1 2020 and Aug 31 2020:

![image](https://user-images.githubusercontent.com/507922/90660131-cd1be680-e245-11ea-8359-508809e5a26a.png)

However, when I attempt to get that data from the API with query parameters (as described in the swagger):

```
GET /api/v1/budgets/15?start_date=2020-08-01&end_date=2020-08-31 HTTP/1.1
Host: my.firefly.instance
Accept: application/json
Authorization: Bearer [My Personal Token Here]
```

I only get back blank array on the spent:

```json
{
    "data": {
        "type": "budgets",
        "id": "15",
        "attributes": {
            "created_at": "2020-08-18T15:54:03+00:00",
            "updated_at": "2020-08-19T15:56:46+00:00",
            "active": true,
            "name": "Subscriptions",
            "auto_budget_type": "rollover",
            "auto_budget_period": "monthly",
            "auto_budget_currency_id": 1,
            "auto_budget_currency_code": "EUR",
            "auto_budget_amount": "34.49",
            "spent": []
        },
        "links": {
            "self": "https://my.firefly.instance/api/v1/budgets/15",
            "0": {
                "rel": "self",
                "uri": "/budgets/15"
            }
        }
    }
}
```
Any idea on what am I doing wrong?

Thanks.

**Comment by JC5** [comment]
Whoops. Didn't mean to close this. Use `start` and `end`. I updated the docs, they'll sync up with the next release.

**Comment by matejdro** [comment]
Thanks, it works now.

**Comment by matejdro** [comment]
I assume you will close this when swagger is updated?

**Comment by matejdro** [comment]
@JC5 what should we do with this issue?

**Comment by JC5** [comment]
It can be closed.
