### ISSUE TITLE
Description of the Split Transaction retained after resetting form

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3710]
If you enter a split transaction and return here to create a new one and reset the form, if you add a split to this new transaction, it still has the previous transaction's split title filled in.

I am running version 5.3.3

Expectation:
The split transaction's input field is empty.

Actual:
The split transaction description field still inherits the previous transaction's text.

Steps to reproduce:
1. Create a transaction with at least 1 split.
2. Enter something in the "Description of the split transaction" input field.
3. Check "After storing, return here to create a new one."
4. Check "Reset form after submission."
5. Click "Submit"
6. Add a split on the new transaction page (the first transaction does not need to be filled in.)
7. Look in the "Description of the split transaction" input field and see that it has not been reset.

Bonus Points:
I have searched the forum and not found a post about this.
I have tested this on the demo site and found the same result.

**Comment by JC5** [comment]
Thanks, I'll verify and fix it! :+1:
