### ISSUE TITLE
Bug in Updating Transaction API

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#3711]
**Bug description**
I am running Firefly III version 5.3.3 and my problem is: I am unable to update transaction's date and time

**Steps to reproduce**

```
curl --location --request PUT 'https://demo.firefly-iii.org/api/v1/transactions/11111?type=withdrawal&description=SomeDescriptionHere&date=2020-08-20T01:01:00+01:00&transactions[0]amount=111&transactions[0][destination_name]=SomeDestinationName&transactions[0][source_name]=SomeSourceName&transactions[0][currency_code]=EUR' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer xxxx'
```
I have tried the following date parameters:

- 2020-08-20
- 2020-08-20T01:01:00+01:00

Error message

```
{
    "message": "Internal Firefly III Exception: Could not parse '2020-08-20T01:01:00 01:00': DateTime::__construct(): Failed to parse time string (2020-08-20T01:01:00 01:00) at position 20 (0): Double time specification",
    "exception": "Carbon\\Exceptions\\InvalidFormatException"
}
```

**Comment by JC5** [comment]
Mmm, weird. Both should be valid. The demo uses "2020-08-20". I'll do some verification. I think the time zone is an issue, I see the + has been dropped.

```
{"transactions":[{"type":"withdrawal","date":"2020-08-20","amount":"12","description":"TeX","source_id":40,"source_name":"DUO Student loans","destination_id":null,"destination_name":"asas","category_name":"","interest_date":"","book_date":"","process_date":"","due_date":"","payment_date":"","invoice_date":"","internal_reference":"","notes":""}]}
```

**Comment by emansih** [comment]
I know that python escapes zone offset too. So 2020-01-01T01:01:01+01:00 will become 2020-01-01T01:01:01 01:00  . that is happening on my home assistant instance anyway.

**Comment by JC5** [comment]
I did some quick checks. Although the timezone is effectively dropped from the request (which will be fixed in the next release) submitting a time/date without a "+" sign is indeed broken. The + needs to be escaped maybe?

**Comment by emansih** [comment]
Thanks. I found the solution. I have to use entitiy encoding `%2B`

`2020-08-19T01:01:01+01:00` becomes `2020-08-19T01:01:01%2B01:00`

**Comment by JC5** [comment]
But with the correct formatting, it works for me (tm). It's part of the array though, [transactions][0][date] = "2020-01-01 12:12:12+03:00".

**Comment by emansih** [comment]
sorry my bad. it's my code

**Comment by JC5** [comment]
No worries, usually it's *my* code ;)
