### ISSUE TITLE
Rollover budget without adding any additional amount

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#3713]
**Description**
From what I see, Firefly currently has three budget modes:

1. Do not do anything (I have to set up budgets every month)
2. Set fixed number every month
3. Copy whatever budget was left from the previous month AND add some money to that amount

However, adding money with option 3 seems to be mandatory. If I want to only roll the money over, without adding anything, Firefly will not let me do that (it complains that "The amount must be more than zero").

**Solution**

Simple solution: Allow me to set "Auto-budget amount" in "Add an amount every period" auto-budget mode to `0`. That way I can set up my budget to auto-rollover, but not get any bigger over time. 

**What are alternatives?**

I don't see any, apart from manually doing this every month or writing custom script that copies my budget every month.

I guess close enough workaround is to add 0.01€ every month, but it is annoying.

**Comment by JC5** [comment]
In your use case, what happens when you run out of money? Is there a period of time that you allow yourself to spend the money in?

**Comment by matejdro** [comment]
I guess it is just a quirk of how I'm doing my personal budgeting.

I'm doing the rollover method where I'm contributing steady small amount of money over the year to every budget. For example, I might contribute 10€ per month to the "Clothing" budget. I don't buy 10€ of clothes every month, but on average I might spend 120€ on clothes over the whole year, so all of this adds up. 

However, this method is not exact, my jacket could tear tomorrow or the old jacket that I wanted to replace would prove more resilient and last couple of more months. That is why I tend to over-budget, contributing slightly higher amounts just in case (I believe it is better to have too much money in the budget than not enough). 

This method works pretty well on average, but sometimes I will overestimate the amount of money I need and I will end up with a sizable sum in a budget (or unexpected things happen. For example, pandemic completely broke my cinema budget). At that point I will cap the budget - I will stop all contributions to it and just wait for the expenses to catch up at which point I will resume contributing again. That means that until amount in this budget falls enough, it would only get rolled over without new contributions.

**Comment by JC5** [comment]
Such budgets may be better managed as piggy banks; and adjusted according to your expenses.

**Comment by matejdro** [comment]
From what I see, I cannot assign transactions to the Piggy Banks (they seem to be completely outside-the-system), while my Budgets are active and I'm constantly withdrawing from them with transactios.

**Comment by JC5** [comment]
Specifically for these rare expenses. Otherwise normal budgets should work fine.

**Comment by matejdro** [comment]
Would you be willing to accept a PR for this fix?

**Comment by JC5** [comment]
> In your use case, what happens when you run out of money?

The answer is no, for now. But I'm curious. If you run out, you expect Firefly III to do nothing? Just to stretch that amount until whenever?

That's not going to work by "adding 0". It should be something else. I'll think about it.

**Comment by matejdro** [comment]
Every month I'm reviewing my budgets and I'm updating the numbers well before they run out. So they can't run out.

**Comment by matejdro** [comment]
I expect Firefly to just stretch my budget until external force updates it. I'm aware that Firefly is not very well suited to my style of budgeting (you've made that clear) so I'm combining it with either some custom external tools and some manual labor.

**Comment by JC5** [comment]
I know. What I'm thinking about now is the external force. 

When you create a budget with roll-over it'll set the first amount for you. It's easy to make it stretch until zero. But then what? What's the trigger to start over? It has to be intuitive, no magic solutions, as little logic as possible on the side of Firefly III.

- Set a budget by hand on `/budgets` is an option but what if the user (accidentally) sets a weekly instead of monthly or vice versa? What to do? Suddenly there's a magic moment where Firefly III may not work as expected.
- Editing the budget to reset the "counter" is counterintuitive. Plus, what if you edit before the budget ran out? 

I like the idea sure, but apart from the n=1 kind of use case it needs something more.

**Comment by matejdro** [comment]
I'm not sure what the issue is with the n=1 use case. You just remove the if check. If anything, you are removing code and having less code to maintain. I'm thinking of this app as pretty power user-y (you have to install it manually on your own server), so I don't think it should protect people against themselves. It should be open to as many possibilities as it can.

> as little logic as possible on the side of Firefly III.

Well, my solution REDUCES logic on the side of Firefly III (less if checks) :wink:

**Comment by matejdro** [comment]
Huh, that is a weird behaviour from the stale bot. Shouldn't it only mark as stale if issue author does not reply, not the other way around?

**Comment by matejdro** [comment]
Still not stale...

**Comment by JC5** [comment]
I’m not going to change this given the questions that are still open.
