### ISSUE TITLE
Additional metadata for automatic linking transaction

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3719]
Since we already have external_id and internal_reference, I was wondering if it could be possible to add another metadata (ref_external_id ?) to keep track of relations, ideally something that could be used to automate link creation throught importing/scripting (or with rules, one day ;) ). 

Many banking systems already have that kind of attributes in place, for example paypal exports transaction_id and reference_txn_id that is used to follow the money (credit card -> paypal -> currency conversion -> seller)

This is ideally linked to #3717, since there is currently no way to export links between transactions, and the problem is that there's no way to save it in the system either, at least not without messing around with other fields (perhaps using external_id -> internal_reference as the two opposites of a relation).

An alternative, with lots of other implications, could be having a unique UUID generated when creating a transaction but kept when importing. This UUID could be used for soft-linking via the internal_reference.

**Comment by psychowood** [comment]
More or less related question: 
I want to migrate all the existing External IDs to Internal References, I was thinking of doing a forced update on journal_meta changing the name, as in

`UPDATE journal_meta set name = 'internal_reference' where name = 'external_id'`

I already double checked that internal_reference is not present for any transaction with external_id, am I risking to break something (hash calculation, serialized objects, something else)?

I don't like touching the DB but I'd like to avoid doing tens of thousands API calls if possible.

**Comment by JC5** [comment]
That should work just fine, you shouldn't break anything :)

**Comment by psychowood** [comment]
Question: I noticed journal_meta.data (and account_meta.data) values are always surrounded by double quotes. Is this expected? 

notes.text is not, for example, and I was wondering if there were some choices behind it (since it make joining data a little bit more difficult).

**Comment by JC5** [comment]
Because both could also contain arrays, they're stored as JSON.

**Comment by JC5** [comment]
This is like the other issue, and I'm collecting stuff for the new layout. I'm closing this one.
