### ISSUE TITLE
Firefly III CSV Import Tool (Multi User)

### ISSUE THREAD

**Issue by sitenzo** [firefly-iii/firefly-iii#3722]
I am running 

- Firefly III version : **5.3.3**
- Firefly III CSV Import Tool version : **2.0.5**

**Description**
Is it possible to use the importer for other users on the main firefly installation as well?
I now have one user, but someone else is also going to use my Firefly III installation.
Is it possible to use one installation of Firefly III CSV Import Tool to populate other users as well, now i can only import to the account of the personal access token in de .env?

**Extra info**
There is also no security on the Firefly III CSV Import Tool if you install it on a public domain.
It will be nice if this module is not separated but can be integrated in the main installation as extension instead of being a part of the core.

**Comment by JC5** [comment]
Hi!

The CSV importer is designed to be a single user tool. An request exists to make it multi-user. This is an ongoing effort but will take some time.

There is (and will be) no security on the CSV importer tool, although the new multi-user setup will make sure people have to login to Firefly III at least before they can use it.

The CSV importer was recently *extracted* from Firefly III, so it will certainly not be integrated again.

**Comment by JC5** [comment]
See also this old post announcing the change: https://www.patreon.com/posts/future-updates-30012174

**Comment by sitenzo** [comment]
Thanks for the response.
