### ISSUE TITLE
[5.4.0 alpha] Scrolling is required to access account "Actions" drilldown list

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3729]
**Bug description**
It's hard to describe so I hope the screenshot will be enough to understand:
![image](https://user-images.githubusercontent.com/34862846/91052473-ce705900-e621-11ea-93b3-f5f289ee5c14.png)
When clicking on the new "Actions" button, a scrollbar appears on the account list and you need to scroll to see the options.
Reproduced on the demo site with Chrome and Firefox.

**Comment by psychowood** [comment]
It's the same behaviour of v5.3.3

<img width="356" alt="image" src="https://user-images.githubusercontent.com/115389/91054413-0e384000-e624-11ea-9e85-92fd9478a7bd.png">

and the same on [adminlte](https://adminlte.io/themes/AdminLTE/pages/UI/buttons.html) demo page.

I'd say it's part of the components.

**Comment by sephrat** [comment]
Is that a different screen than /accounts/asset? I rolled back to 5.3.3 and that page is different due to the new sortable feature introduced by #3200.
See below screenshot from 5.3.3:
![image](https://user-images.githubusercontent.com/34862846/91055748-5dcb3b80-e625-11ea-90ba-56781ffee14e.png)
The actions used to be buttons in the first column but were replaced by the ability to sort the list.

Yeah I supposed it would be on adminLTE side, but I still feel like that is a regression on the UX, especially as I personally have only two asset accounts. I was hoping it could be magically fixed so that the drill down is displayed on top of the footer button.

**Comment by JC5** [comment]
Wasn't aware that the menu would be created inside the box. Not sure if it's something I can fix.

**Comment by psychowood** [comment]
@sephrat  My bad, I misread the description.
@JC5 strange enough, since it is vertical scrolling, it seems to be caused from the "overflow-x:auto" 

Forcing an overflow-x:visible on the table container seems to "solve" it, even if it is just a workaround:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/115389/91169487-c07d0f80-e6d7-11ea-9376-93a85027467e.png">

**Comment by JC5** [comment]
Nice debugging guys, should be fixed in the next alpha :+1:
