### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by berrabe** [firefly-iii/firefly-iii#3731]
**Bug description**
I am running Firefly III version 5.3.3 and my problem is:

- when I access firefly, sometimes it feels fast and sometimes very slow for loading web pages
- sometimes up to an error 504 gateway time out

Honestly, I don't know the exact cause, at first I thought it was using the nginx proxy from jwilder ... but after I looked deeper, it turned out that this was not the problem, when I accessed it using the IP address it was the same.

**Steps to reproduce**

  - docker stats shows quite high CPU usage
![poc1](https://user-images.githubusercontent.com/34432326/91175471-115a2b80-e70b-11ea-9420-52f8e908c6d6.png)

  - but simultaneously, firefly does not display any data
![poc2](https://user-images.githubusercontent.com/34432326/91175606-4797ab00-e70b-11ea-8089-e5c19d70145e.png)

  - sometimes after waiting a long time, the app will display the data, but sometimes it also ends in a 504 gateway timeout error
  - and to solve this problem, I have to restart the firefly instance apache web server

**Extra info**

- Client
  - latest version of firefox 79.0 (Linux Manjaro)
  - Linux Manjaro on core i7, 8 GB RAM
- Server
  - STB B860H, aarch64 @1.5 GHz - 4 Core
  - Docker version 19.03.13-beta2, build ff3fbc9
  - Docker Compose and .env file same as doc, except some credential, app key, etc
  - Jwilder nginx proxy

**Bonus points**

-  [+] I searched and nobody reported this bug before
-  [+] I have added a stack trace from my log files 
-  [+] I have added a screenshot.
- [-] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
It depends on the number of resources available to the docker image. Firefly III isn't a particularly lean application but your specs are fine. Not sure what the cause could be.

**Comment by psychowood** [comment]
Try increasing the upper memory limit (start with doubling to 200MB), I'd guess both the application and the db are swapping quite a lot with just 100MB.

In my installation the CPU is almost always below 1%, and these are the memory stats I see:

- Application container:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/115389/91198739-419acd80-e6fd-11ea-902e-ca56d8d12b1e.png">

- Database container:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/115389/91198761-4a8b9f00-e6fd-11ea-906f-366e8594c285.png">

**Comment by berrabe** [comment]
> It depends on the number of resources available to the docker image. Firefly III isn't a particularly lean application but your specs are fine. Not sure what the cause could be.

yes I agree, I think the graphics display is very good but on the other hand it is very heavy to render

- but my other question, will firefly slow down if you use a reverse proxy, especially with the HTTPS protocol?
because what I feel when accessing using an IP address will be faster than using a reverse proxy
I use a reverse proxy from [frederikbosch](https://github.com/frederikbosch/nginx-proxy.git) and also Cloudflare dns proxy
- @JC5 

___

> Try increasing the upper memory limit (start with doubling to 200MB), I'd guess both the application and the db are swapping quite a lot with just 100MB.
> 
> In my installation the CPU is almost always below 1%, and these are the memory stats I see:

I've added the RAM capacity to 150MB, and what i see, the ram used is not more than 100mb ... so i think it's not a ram problem, and also I set it not to use swap memory
and for the cpu, what I see is the cpu will go up when I start rendering a page that has a graphical display like a dashboard
@psychowood

**Comment by JC5** [comment]
It should make no difference if you use a reverse proxy. I know it doesn't make a difference for me. But all I have is a basic nginx proxy.

**Comment by niklas2810** [comment]
When I switched from nginx to traefik, I experienced a similar issue. Web pages itself still loaded very quickly, but API requests took very long to complete.

As a result, I had to wait up to 3s for the web page to fill with actual content (the basic box layout was instantly there, but the actual data was put in later). I upgraded Firefly III to Version 5.3.3. at the same time, so this might could be the root cause as well (I'll try to use an older version to test this thesis).

I'm not quite sure whether these two issues are related. If you have a clue what might be causing this behavior and think it's related to this issue, I'll be more than happy to provide required log files!

**Comment by niklas2810** [comment]
Okay, I have downgraded to 5.3.0 and still experienced these issues. You can find a diagram down below. Note: Both my server and PC internet connections are fast+stable and should not be the root cause of this issue. I've already tried this using a different hosting provider/network connection. RAM and CPU usage are far below the maximum capacity.

![image](https://user-images.githubusercontent.com/30748216/91267285-56b24380-e773-11ea-8860-a764f3bf28fe.png)

From my point of view, this might be an issue with the reverse proxy. Traefik seems to be slowing down the requests and this _might_ also be the case for @berrabe . If you need more details, please let me know!

**Comment by niklas2810** [comment]
PS: I know that in my case, many resources were cached. If a disable/delete the cache, the waterfall chart stays the same:

![image](https://user-images.githubusercontent.com/30748216/91268072-f02e2500-e774-11ea-8b3a-6a5b47e8fdf9.png)
![image](https://user-images.githubusercontent.com/30748216/91268099-fde3aa80-e774-11ea-88bb-bf34aa6c1486.png)

**Comment by berrabe** [comment]
your info is very good @niklas2810 

I haven't seen the performance on the network side yet, but I've tried several reverse proxies with different settings, and here are a few possibilities:
  - when using nginx reverse proxy with https, it feels very slow to load resources and call api, Note that it doesn't use any caching features, the diagram like this
    - CLIENT -----------------https----------------- REVERSE PROXY-----------------http-----------------UPSTREAM ( firefly )
  - but after I used a reverse proxy from cloudflare, it started to show which part was causing the problem,if you use the caching feature (dns proxy), it will make pages take too long to load
    - CLIENT -----------------https----------------- CLOUDFLARE caching on-----------------http/https-----------------UPSTREAM ( firefly )

So is this a problem with the compatibility of the reverse proxy caching feature? @JC5

**Comment by niklas2810** [comment]
> when using nginx reverse proxy with https, it feels very slow to load resources and call api, Note that it doesn't use any caching features, the diagram like this 

I didn't use any special caching features either, as @JC5 already stated a basic nginx reverse proxy should work just fine.

> but after I used a reverse proxy from cloudflare, it started to show which part was causing the problem,if you use the caching feature (dns proxy), it will make pages take too long to load

How does your caching configuration look like? @berrabe I used Cloudflare on my old nginx instance as well and it didn't cause any problems.

**Comment by berrabe** [comment]
1 how much time it takes to load the dashboard page on a basic nginx proxy? @JC5 @niklas2810 
2 just activate the dns proxy and change some settings in SSL and caching 
3 this is my performance web test :

- when accessing using the ip address, port 8080 - Local Network

<p align="center">
  <img src="https://user-images.githubusercontent.com/34432326/91273801-f7225b00-e7a7-11ea-92d1-4dbf2cf74130.png" />
</p>
    

  - when using nginx reverse proxy with https, Local Network

<p align="center">
  <img src="https://user-images.githubusercontent.com/34432326/91274113-6dbf5880-e7a8-11ea-9236-19117f8765c2.png" />
</p>

  
  - when using nginx reverse proxy with https, Internet
    - when doing caching, cloudflare takes up to 50+ seconds
<p align="center">
  <img src="https://user-images.githubusercontent.com/34432326/91274425-dc041b00-e7a8-11ea-9862-2663088c8f4e.png" />
</p>

is this normal finish time? @niklas2810

**Comment by sephrat** [comment]
Just my two cents: on my installation, it loads almost instantaneous:
![image](https://user-images.githubusercontent.com/34862846/91275339-50769400-e780-11ea-8671-6757424d877b.png)
Server is behind nginx with SSL and Firefly-III runs in Docker. Hardware is "not great, not terrible": recent NUC with i3 CPU. So unless you run Firefly-III on a potato there must be something wrong with your setup.

**Comment by niklas2810** [comment]
@JC5 Are you currently testing the demo site using cloudflare?

1. I hope you disabled caching for this @berrabe . Without cache it took ~5 seconds, with cache only up to 2 seconds. Using Cloudflare I was at about (3-4s) every time I loaded the page.
2. Hmmh, then there shouldn't be a problem there (except that it has to send the API requests to the server, but that shouldn't take too long).
3. These are the times for _first page load_ (=disabled cache).

Nginx: ~ 5s
Nginx+Cloudflare: ~3.5s
Traefik+Cloudflare: ~7.5s

**Comment by JC5** [comment]
A quick reply while @ work. Yes @niklas2810 I'm playing around with Cloudflare. I just enabled it now it doesn't do much yet.

For everybody: would it help to extend the logs with query times?

**Comment by niklas2810** [comment]
>For everybody: would it help to extend the logs with query times?

@JC5 This could be useful to figure out if the application itself is the bottleneck :smile: However, I still think that the reverse proxy configuration (@berrabe 's custom nginx proxy + traefik) are the root causes of this issue

![image](https://user-images.githubusercontent.com/30748216/91282545-c7fcf100-e789-11ea-9cb8-c199fa65add3.png)

In the logs I've seen that the requests arrive at the exact same time, which means that a slow database connection is at least not _impossible_. Nevertheless, it would still make no sense why a different reverse proxy would slow down the perfomance of the database/application.

**Comment by niklas2810** [comment]
I've found something which might be relevant as well:

![image](https://user-images.githubusercontent.com/30748216/91283221-97698700-e78a-11ea-9b40-412b3f936c2c.png)

Traefik needs _200ms_ to redirect the request to Firefly (`+0000`->`+0200`).  I'm not quite sure what the reason for this is, but this would cut down the response times by 50% in many cases. If we assume that the answer takes 200ms to be redirected as well, all API requests would be handled in <100ms and the reverse proxy would be the issue.

**Comment by JC5** [comment]
Not sure why I just realised this, but you could try the following, also in docker:

`docker exec -it [container] composer require barryvdh/laravel-debugbar`

Make sure to start the container with `APP_DEBUG=true`.

Should bring up all those details.

**Comment by berrabe** [comment]
> Just my two cents: on my installation, it loads almost instantaneous:
> ![image](https://user-images.githubusercontent.com/34862846/91275339-50769400-e780-11ea-8671-6757424d877b.png)
> Server is behind nginx with SSL and Firefly-III runs in Docker. Hardware is "not great, not terrible": recent NUC with i3 CPU. So unless you run Firefly-III on a potato there must be something wrong with your setup.

I've explained my server spec, and what I see, resource usage (cpu, mem, swap) doesn't exceed 100%, the maximum value is 400%, as well as ram and swap. so I thought, spec is not the main problem

___

  - caching is built to save bandwidth, speed up loading times, and help reduce server performance, I don't think caching should be turned off, because so far, all the websites I've tried have been helped by the caching features from cloudflare / other reverse proxies @niklas2810 
   - to be honest, I've never used apache as a web server, and I don't really understand how the firefly program works, because I don't really understand laravel or php, but what I see is from resource usage (docker), log files (nginx reverse proxy, firefly-iii), host system usage ... firefly doesn't use resources optimally ... maybe you can implement multithread / multiprocess so that all resources and api are called simultaneously? @JC5

**Comment by niklas2810** [comment]
> Should bring up all those details.

@JC5 Where exactly? I installed the debugger inside my container and set `APP_DEBUG=true`, but I can't see any additional lines when using `docker-compose logs -f` 😦 The [GitHub page](https://github.com/barryvdh/laravel-debugbar) mentions a bar, but I can neither find something like this.

I guess it's normal that composer can't cache stuff while running in a container? 

![image](https://user-images.githubusercontent.com/30748216/91324835-cd2a6200-e7c2-11ea-96b8-50e4f0b1c1ae.png)

**Comment by niklas2810** [comment]
> caching is built to save bandwidth, speed up loading times, and help reduce server performance, I don't think caching should be turned off, because so far, all the websites I've tried have been helped by the caching features from cloudflare / other reverse proxies

@berrabe I don't mean cloudflare caching, I mean your browser cache, you can find a checkbox in the developer tools window (Firefox: Upper right corner in the Network tab, Chrome: Preferences > Network > Disable Cache while DevTools is open)

**Comment by berrabe** [comment]
> > caching is built to save bandwidth, speed up loading times, and help reduce server performance, I don't think caching should be turned off, because so far, all the websites I've tried have been helped by the caching features from cloudflare / other reverse proxies
> 
> @berrabe I don't mean cloudflare caching, I mean your browser cache, you can find a checkbox in the developer tools window (Firefox: Upper right corner in the Network tab, Chrome: Preferences > Network > Disable Cache while DevTools is open) disable this to simulate a first page load, forcing your browser to request previously cached files (e.g. images/stylesheets).

___


  - yes I have done disabling caching during the testing process, and also always use private windows
![a](https://user-images.githubusercontent.com/34432326/91366690-a4d84d00-e82e-11ea-9cc8-d07e37afa61d.png)
