### ISSUE TITLE
Correct way to import multiline notes?

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3732]
CSV Importer v2.0.5, Firefly III v5.3.3

I'm trying to import a CSV with a multiline note and, while in the end I was able to avoid tecnhical errors```[1]```, I'm not sure this is the correct way.

From #3281 I undestand that I have to use double newlines or ending space to represent correctly notes

> ```
> to add a newline, finish a sentence with two spaces  
> and continue on the next line
> 
> or give a double enter
> ```
> 
> https://www.markdownguide.org/basic-syntax/#line-breaks

Could it make sense to add automagically a double space after each newline during the import process, at least for multiline fields?

When importing you usually have lots of data ready and you don't want to edit it manually. The same could apply for appending notes: each appended note should probably be on a new line instead of concatenating it.

```[1]```: Before realizing I could use an actual multiline-line in the CSV I tried adding \n and double spaces before finding the correct way... it could help adding a note on csv-importer docs.

**Comment by JC5** [comment]
> Could it make sense to add automagically a double space after each newline during the import process, at least for multiline fields?

No, I really try to avoid adding magic conversions like that. I saw your PR, nice. 

For now, hack away with a Python script or something. I want to avoid adding converters and fixers to the CSV importer because every bank has weird quircks that totally justify chacking the importer for.

**Comment by psychowood** [comment]
I don't find a problem adding some spaces to the CSV, I'll clean it up anyway before importing, the thing was making it clear how it works.

Hopefully the PR will prevent some issue.

**Comment by JC5** [comment]
Of course yes. Sorry, it was a long day. Thanks again for the PR :)
