### ISSUE TITLE
Suggestion: Review of the yearly summary boxes in the asset overview page

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3734]
Hi,
While I find the asset details page very useful, I've got some (unsolicited) suggestions.

Considering an account with some transfers in foreign currencies, the yearly recap (right column) is quite confusing. See this example:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/115389/91305175-f0e1ae00-e7aa-11ea-878a-420ea95d04a9.png">

Some thoughts:

- The main absent here is the yearly total, the one shown on top of the main chart. It could go either near the year, or as a last line
- "Transferred (away)" amounts are green, should be probably be red (or blue like in the transaction list)
- Foreign currencies are there but we know that the "real" currency for each account is just one. All the others are "just" indicators, imho they should not have the same value of the main currency amounts.

In the end, since we are talking about the same concepts, my suggestion is to make it closer to the transaction list view:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/115389/91311199-196da600-e7b3-11ea-81a2-dbcfdee399ee.png">

As a bonus point: since they don't really matter, the foreign currencies could be hidden by default completely, and shown only when clicking on a button/text (e.g. "show details" near the year, in the header).

![image](https://user-images.githubusercontent.com/115389/91312600-b5e47800-e7b4-11ea-83b0-22d446a0f498.png)
![image](https://user-images.githubusercontent.com/115389/91312538-a36a3e80-e7b4-11ea-905e-9ae23c70564c.png)

**Comment by JC5** [comment]
I'll pick it up for the new layout!

**Comment by JC5** [comment]
Like other issues related to the (new) layout, I'm closing this one to remove clutter.
