### ISSUE TITLE
DEVELOP: Failure to create rule from transaction

### ISSUE THREAD

**Issue by verticelo** [firefly-iii/firefly-iii#3737]
**Bug description**
I am running Firefly III version develop (https://hub.docker.com/layers/jc5x/firefly-iii/develop/images/sha256-a84d7949cff55e208a158c3cac4c89f643f95084b2df906398c6a50bc881edab?context=explore), and my problem is:

- When creating a rule from a revenue transaction it does not show an error message when I mess up

**Steps to reproduce**
- Have a transaction in Revenue
- Click it to "Create rule based on transaction"
- Set the action for the transaction to "Convert to transfer"
- Do not enter a value in Convert to transfer
- Press to create rule
- Page refreshes, no rule is created, no error is shown, the action is reset to "Add tag"

**Comment by JC5** [comment]
Check. It's correct that it doesn't "work" but the error doesn't show. Stay tuned.

**Comment by JC5** [comment]
Fixed :+1:

**Comment by verticelo** [comment]
Thanks. Great work! Confirmed working now.
