### ISSUE TITLE
Suggestion: More efficient workflow after import

### ISSUE THREAD

**Issue by verticelo** [firefly-iii/firefly-iii#3738]
**Description**

- I would like a quicker way to assign transactions to budgets and categories after a CSV import

- I am new to Firefly so my workflow might be messed up, so feel free to correct me

**Solution**
- On the transactions screen I would like to have a column Budget
- On the transactions screen I would like to have dropdowns for the Budget/Category column where I can select budgets / categories quickly, there should be at most 2 clicks to assign a category to a transaction and I shouldn't have to leave the view
- On the transactions screen I would like to be able to filter transactions based on if they are assigned/not assigned to a category so I can see only unassigned ones

**What are alternatives?**
Currently I click Action -> Edit -> Then press to set the marker in the Category field -> Then press the category

**Comment by verticelo** [comment]
This is a feature request.

Also, thank you for developing Firefly! Great product and I enjoy testing it now.

**Comment by psychowood** [comment]
You can already do most of what you want to achieve.

- Create a tag for that specific import-session (checkbox on CSV-importer options before importing)
- Navigate to the tag -> view the tag -> click on "Show all transactions without grouping them by date"
- Select all the transactions (top-right checkbox over the transactions table)
- Actions -> "Edit the transactions individually"

<img width="334" alt="image" src="https://user-images.githubusercontent.com/115389/91330005-25fcf900-e7c9-11ea-81b4-ebcc62a666c3.png">

- Edit Accounts/Categories/Budgets individually from the same page
- Save & Profit

**Comment by verticelo** [comment]
This is great! Thank you for the instructions. For my workflow there are still a few things that would improve the experience a lot.

- I would like to filter to see only transactions which does not have a category and/our budget set
  * I found that you can go to Class -> Categories and select "None" there
  * I found that you can go to Budget -> "None" there
  * Would be nice to have that filter on the transactions page directly
- On the transactions page, I would like to select a category/budget from a drop-down instead of typing in it in, it feels much quicker and I don't like having to select and open a different view. To me speed/easy of flow is essential.

**Comment by MacPaille** [comment]
You can also use rules to set your transactions with the values you want at transaction creation. That's what I'm doing with my imports and the more I update them the less I have to update them manually after import.
But for that you need to be able to identify your transactions in some way (which I suppose exist as you are doing it manually...)
