### ISSUE TITLE
"Source/Destination account missing" rule trigger

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3740]
**Description**

Firefly III already allows to specify lots of rule triggers. However, I couldn't find one which fits my use case: 

For every transaction which has no source or destination account specified, I wanted to add a custom tag. Tags obviously aren't a huge deal, but I realized that there was no trigger like "No source/destination account".

**Solution**

Add the rule triggers `Destination account missing` and `Source account missing` (or alternatively, "[...] account empty").

**What are alternatives?**

As the API names every empty account "Cash account" (regardless of the selected language), you can add the trigger `Source/Destination account name is... -> Cash account`. This feels like a workaround to me and could be solved in a better way by adding a custom rule for this use case.

**Comment by JC5** [comment]
It could be a trigger, sure. I'll pick it up!

**Comment by JC5** [comment]
Fixed, will be part of the new release. For a full list of triggers, see:

https://github.com/firefly-iii/firefly-iii/blob/develop/resources/lang/en_US/firefly.php#L411

**Comment by niklas2810** [comment]
Thank you so much! 🙌
