### ISSUE TITLE
Partial payments for repeating bills with 'target amounts' are shown as paid even if the transaction didn't match the target amount yet (no summing up of transactions to reach target). 

### ISSUE THREAD

**Issue by JanFeld** [firefly-iii/firefly-iii#3744]
I am running Firefly III version 5.3.3.

**Description**
I've got some kind of special problem regarding bills. I'm thinking of something like an open bill, which is occuring regularly, for example every month or 3 months or something like this. I'm paying for this bill (in a specific range, like every firefly-bill) more or less regularly but not the same amount everytime. 

When i'm trying to use standard-bill with this kind of concept and link some transactions with different amounts to it, the bill will be shown as _paid_ even though its target amount (minium value) has not been reached yet. It doesn't show as _open/to-pay_ so i'm slightly confused about it. I could think of it like a "negative-budget" which i'm trying to get back to zero-level but on a cyclic appearance with a 'target-range' of about 100 €. I don't really think it fits into the liabilities/liability accounts because i'd have to re-create or reset its value on a regular basis to keep it coming again and again as well as keep track in other ways to make sure it's paid for. To see the left-payments for this 'interval' would be great to have some overview of how much money i'd have left to pay this month to fulfill this bill too, without having to fulfill it instantly with one payment.

Is there a way to make something like _partial payments_ to a bill and show / keep track of difference to at least the minimum amount of this 'bill' without marking it as _paid_ with a single payment which is way below the actual bill-value?

When i've tried to utilize a standard-bill it would set the state to paid on every small transaction which doesn't reach the target value. This marks the bill _paid_ instead of summing up and additionally shows every transaction as small yellow bar on the analysis chart for this bill. 

A possible way would be to save the money to some kind of piggy-bank and pay it 'once' when the target amount hast been reached or create some kind of liability. Both ways wouldn't fit this kind of problem. It's more of a 'bill' which is treated in some _Pay what you want when you can as long as the amount is paid on day X._

It would be great to have some kind of 'periodic bills' which have some kind of an interval to the date of payment which can be summed up in multiple transaction to match the target-value before it will be reset for a new interval. 

The display on the dashboard-page could be some kind of 'monthly amount' depending on the time left. For example:

- Interval: 4 Months
- Amount: 7500 €
- First Occurance: April 30th

Display in Dashboard (if no payment has been done yet):
- January = 1875
- February = 2500
- March = 3750
- April = 7500 

If payments have been done and linked to this bill, it would influence the amount of the 'left-to-pay' value. For example:

- January = 1875 €
    - 2 Payments ( 500 / Payment)
    - -> 1000 € summed up (7500 - 1000 = 6500)
- February = 2166.66 € left (6500€ / 3 months left)
    - 3 Payments (722.22 / Payment)
    - -> 2166.66 € summed up (6500 - 2166.66  =  ~4334 €)
- March = 2167 € (4334 / 2 months left)
    -  No Payment
- April = 4334 € (last month of interval)
    - ... 

Something like this would allow to track some cyclic bills with no fix payments but variable ones and still treat them like bills and keep track of a (summing up if not paid) monthly cost on your dashboard without marking a bill as 'paid' even if it's not fully paid. 

Is there some way to do this i didn't see yet? Could this maybe fit in some kind of feature request to have this option in future versions ..? :-) 

Thanks for your suggestions/answers/help! 

Best regards,
Jan

**Comment by JC5** [comment]
This is really specific. Like really really specific. I see what you're trying to do though, but these are the kinds of complicated products that don't really fit Firefly III well.

Having said that: the minimum / maximum amounts that you can set on a bill are really for cosmetic purposes only, now that the rule engine is capable of handling transactions to see if they match a bill. It used to be so that the bill had its own search engine, the rules had their own search engine and the search had its own search engine. These are now merged, making these fields a little obsolete. However, the min/max amounts are still useful to show you how much money you can expect to pay every period.

You could change your rules in such a way that only the final payment gets linked to the bill. This won't really solve the problem that the final amount maybe way less than the actual full bill though.

What you're showing feels more like a debt rather than a bill. Although the rate at which you pay doesn't feel like regular debts, which are often very regular in the amount due each period. The schedule you show has a weird delta. 1875, 625, 1250, 3750. This could be a coincident of course, just an example, but it would be hard to keep track of.

I don't really see what could be an obvious way of keeping track of this. Summing up separate transactions until they trigger a bill feels a bit complex, to tell you the truth. Not sure what else it could a solution though, from Firefly III's point of view.

**Comment by JanFeld** [comment]
I fully get your point. Well, it seems like a 'liability' would be wrong semantically, but would fit it best (at least behavioural). Needs some more manual tracking and actions but that's not that bad either. Firefly helped me to remember almost everything (costs, savings, etc.) very well so i feel like manual management of something like this would help me to rembember this too. I think a little more mental arithmetic won't hurt me.

Nevertheless thanks for you viewpoint though. I think it's really specific, yes. Actually it is even more like some kind of debt but it's not that specific in single amounts or even that regular. It's an agreement to have the sum paid at Day X but not at once but in single steps. Pretty much what i've described above. This was just my idea/attempt of tracking this kind of 'bill/debt'. The display in the dashboard would be even more cosmetics for me too, as well as viewing this kind of agreement in the form of a bill. The weird delta is a result of the _I have more money to pay for this bill this month. I wont have that much money next month._ look  and/or additional payments / brokerage stuff going on in good months, which lead to a higher margin to pay in single steps. Similar to 'One-Time-Payments' when dealing with loans. The best way to do this is breaking down the target amount in uniformly distributed payments, i know. It's just me thinking to long about small things. 

When i'm thinking about this longer i agree with you more and more.. It's like really, really, _really_ specific, yes. 

I think this can be closed ..

**Comment by JC5** [comment]
Haha alright, I'll close it. Not sure how technical you are, but you could manage the extra meta-data and the view you have on these things via the API as well. Maybe create the necessary accounts and transactions, and rename the items in your view however you see fit. It fits in Firefly III, it's just the display that's missing.

I'll close this one. Let me know if you need anything.

**Comment by JanFeld** [comment]
Oh.. The API .. I completely forgot about that. Maybe i'll can do something about this..

But.. I still do not quite understand how bills are shown as paid even if their minimum amount has not been reached.. Isn't that kind of dangerous?

**Comment by JC5** [comment]
The minimum and maximum amounts used to be a tool to select which transactions are part of a bill. This is now handled by rules entirely. The amounts are cosmetic only. I still have to change the UI to reflect this (ie. "expected minimum" or something).
