### ISSUE TITLE
Artisan Request: Fill Auto-budget Amounts Ahead of Schedule

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#3753]
On the last weekend of each month, I review the budget for the coming month and set amounts.  I have many budgets that are configured with automatic values, which is a huge time saver - thanks for adding this!

I have a nightly task configured to run firefly-iii:cron, but I believe it will only apply auto-budget values when the system clock rolls over to a new month.  I wanted to review the budget last night (Aug 30), but none of the values for September were filled in yet.

Can you add a function to manually run the auto-budget cron?  It would save me time copy-pasting values between pages if I want to review budgets before the auto-budget cron job fires in the usual way.

Thanks!

**Comment by JC5** [comment]
You can run the cron command with `--date=YYYY-MM-DD`, but that will also apply to the other cron commands.

**Comment by JC5** [comment]
It won't however, recreate recurring transactions so you're pretty safe.

**Comment by hamfactorial** [comment]
Awesome, thanks!  I didn't realize artisan had a --help switch, which showed me the "--force" option.  Pairing that with "--date" does the trick.
