### ISSUE TITLE
Option to create all recurring transactions at the beginning of the month

### ISSUE THREAD

**Issue by tgkenney** [firefly-iii/firefly-iii#3754]
**Description**

At the beginning of the month I like to look at the future so I can plan out some of my transfers and payments.  It would be nice to have an option to create all recurring transactions for the month at the beginning of each month.  I know forecasting is explicitly off the roadmap, but I see this more as an option to just create transactions early rather than forecasting.
 
**Solution**

The CLI currently allows you to run the cron job with a --date flag so I believe this functionality could be leveraged.  I think a button on the recurring transactions page to create all transactions for the month.  In the API, there is also a recurring and cron endpoint.  Adding or modifying an existing endpoint to either pass in a date to run for or an 'all' days option would nice as this would allow for easy scripting

**What are alternatives?**

The CLI currently has the date option for cron, but this is clunky and doesn't easily allow for scripting this functionality

**Comment by JC5** [comment]
This will stay as it is. What you want to do falls outside of the use case but with some hacking it's perfectly possible. The fact that it's clunky isn't my problem I'm afraid.

**Comment by tgkenney** [comment]
That's fair, I just figured I would make the suggestion.  If I may ask a question, when using CLI to run cron with --date, does it need to be run for each day in the month, or if I run it for the last day of the month will it create the transactions for the whole month?
