### ISSUE TITLE
When making a report, you should be able to select all accounts in a group with one click

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3755]
So I went to run a report using just my 7 credit cards. I was hoping there'd be a way to select them all at once, but that doesn't seem to be the case. You can select all your accounts, but it'd be nice to be able to just select all your credit cards, default asset accounts, or savings accounts.

Possible solution:
Since you can already technically click the heading of the group (even though it apparently doesn't do anything, make clicking that select (or deselect) all items in that group.

**Comment by JC5** [comment]
Good idea, will be possible in the next release.
