### ISSUE TITLE
 Installation on hosting

### ISSUE THREAD

**Issue by polet123** [firefly-iii/firefly-iii#3757]
Hello I am from Russia. How can I install a hosting installation? Similar didn't work for me - https://github.com/firefly-iii/help/wiki/Configure-your-webserver-correctly

**Comment by niklas2810** [comment]
What exactly is your issue? If you want to know how to set up an installation, please  visit the [documentation](https://docs.firefly-iii.org/#how-can-i-use-it-or-run-it). You can install Firefly III on a [LAMP Stamp](https://docs.firefly-iii.org/installation/self_hosted), use the official [docker image](https://docs.firefly-iii.org/installation/docker) or use a [third-party provider](https://docs.firefly-iii.org/installation/third_parties). 

If an error occurred while installing Firefly III, please provide more details (e.g. logs,  screenshots)!

**Comment by polet123** [comment]
Thanks for the quick response. I'm trying to host -https: //cp.hts.ru/ HTTP Server Apache 2.2.x; MySQL 5 DBMS; I just throw the files into the root of the site and try to start the installation using the tvent.ru domain, but I see an error (I attach the screen).

  
>Среда, 2 сентября 2020, 19:04 +03:00 от Niklas Arndt <notifications@github.com>:
> 
> 
>What exactly is your issue? If you want to know how to set up an installation, please visit the  documentation . You can install Firefly III on a  LAMP Stamp , use the official  docker image or use a  third-party provider .
>If an error occurred while installing Firefly III, please provide more details (e.g. logs, screenshots)!
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by niklas2810** [comment]
I'm not quite sure what your message content means.

As far as I am concerned, it seems like hts.ru is a russian hosting provider. What's tvent.ru, is this your personal domain?

**Comment by polet123** [comment]
I use Google translate. tvent.ru and a personal domain on which I run the project. We presented that we have php version 7.2 but we need 7.4. We will try to change the version on the server and try again.
>
>Среда, 2 сентября 2020, 22:08 +03:00 от Niklas Arndt <notifications@github.com>:
> 
> 
>I'm not quite sure what your message content means.
>As far as I am concerned, it seems like hts.ru is a russian hosting provider. What's tvent.ru, is this your personal domain?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
С Уважением Тарас Сергеевич!

**Comment by polet123** [comment]
tvent.ru [Wed Sep 02 23:37:45 2020] [error] [pid 17068] sapi_apache2.c(349): [client 78.110.48.57:0] PHP Fatal error: require(): Failed opening required '/home/srv84208/perfex_crm/public/../vendor/autoload.php' (include_path='.:/opt/rh/php74/root/usr/share/pear:/opt/rh/php74/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/srv84208/perfex_crm/public/index.php on line 43

  
>Среда, 2 сентября 2020, 22:08 +03:00 от Niklas Arndt <notifications@github.com>:
> 
> 
>I'm not quite sure what your message content means.
>As far as I am concerned, it seems like hts.ru is a russian hosting provider. What's tvent.ru, is this your personal domain?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by JC5** [comment]
You also need to install the dependencies. If you have no terminal access this is impossible.

**Comment by polet123** [comment]
Hello! I was able to install but the problem came out. I changed the mail in the admin area, but the confirmation did not arrive in the mail. As a result, I cannot get into the admin panel. How can I regain access?
  
>Четверг, 3 сентября 2020, 7:38 +03:00 от James Cole <notifications@github.com>:
> 
> 
>You also need to install the dependencies. If you have no terminal access this is impossible.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by polet123** [comment]
I was able to do it! Thanks for the development, I plan to support you financially! My wish is to make an installation guide for hosting. I have suggestions I will write on github

  
>Четверг, 3 сентября 2020, 7:38 +03:00 от James Cole <notifications@github.com>:
> 
> 
>You also need to install the dependencies. If you have no terminal access this is impossible.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by JC5** [comment]
Glad to hear it! 👍

**Comment by polet123** [comment]
Hi, I hope I am not in the way if I write to the mail. I am facing a problem. I can't figure out where the translation files for the page are located - / transactions / create / withdrawal. I reviewed all all files in ru_RU but there is nothing there.

  
>Четверг, 3 сентября 2020, 18:36 +03:00 от James Cole <notifications@github.com>:
> 
> 
>Glad to hear it! 👍
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by JC5** [comment]
What is your question? Check out /resources/lang/ru_RU

**Comment by polet123** [comment]
I have read, I want to replace the word "budget" with "my budget". Which line is responsible for this? I can't find her ..
 
>Воскресенье, 6 сентября 2020, 22:35 +03:00 от James Cole <notifications@github.com>:
> 
> 
>What is your question? Check out /resources/lang/ru_RU
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by JC5** [comment]
https://crowdin.com/project/firefly-iii/ru#

**Comment by polet123** [comment]
Hi, do you understand what I am writing, can I try another language?
1 question.
I have a different problem. I found the language files and even made edits.
I'm trying to change the word but it stubbornly doesn't want to be translated. All changes I make in the folder - / resources / lang / ru_RU
I have marked on the photo the word I want to change
I marked the word that I want to change on the photo. I change it in firefly.php on line 445 and 446 'rule_trigger_budget_is_choice' => 'Budget =', 'rule_trigger_budget_is' => 'Budget = ": trigger_value"' But that doesn't help.
…
2 question.
I tried to do a crazy thing and deleted all the folders in the lang directory. As a result, the entire translation became English. Where are the translation files stored if I deleted everything from lang? This is rather strange and incomprehensible.
  
>Воскресенье, 6 сентября 2020, 23:56 +03:00 от James Cole <notifications@github.com>:
> 
> 
>https://crowdin.com/project/firefly-iii/ru#
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by JC5** [comment]
I see what you mean. The page "create transaction" is rendered before the release. So changing files has no effect. If you submit changes to Crowdin and the other translators agree the changes will be part of the new release.

**Comment by polet123** [comment]
Hello, thanks, but that's not it. I went through the files for a long time and finally found something. Here is /public/v1/js/create_transaction.js it is in this file that the form header changes. It would be convenient to edit it in a common language file.

  
>Понедельник, 7 сентября 2020, 17:04 +03:00 от James Cole <notifications@github.com>:
> 
> 
>I see what you mean. The page "create transaction" is rendered before the release. So changing files has no effect. If you submit changes to Crowdin and the other translators agree the changes will be part of the new release.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by JC5** [comment]
Yes that's the rendered file I mean.

**Comment by polet123** [comment]
Hey. I get an error when going to the / rules page. Logs attached, please help).
  
>Вторник, 8 сентября 2020, 8:08 +03:00 от James Cole <notifications@github.com>:
> 
> 
>Yes that's the rendered file I mean.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by ezitisitis** [comment]
I will allow myself to join this conversation.
Will write in both languages (EN+RU), to avoid missunderstandings.

@polet123 unfortunately log file was not attached, try to answer throught GitHub and attach log. 
Was there any data in the app? (If not, it would be easier to reinstall app)

@polet123 к большому сожалению лог файл не прикрепился, попробуйте отвечать через GitHub и приложите лог. Были ли какие либо данные уже введены в приложение? (Если нет, то разумнее будет сделать установку с нуля)

**Comment by polet123** [comment]
Hello — https://github.com/firefly-iii/firefly-iii/issues/3812

  
>Пятница, 18 сентября 2020, 18:03 +03:00 от Marks Bogdanovs <notifications@github.com>:
> 
> 
>I will allow myself to join this conversation.
>Will write in both languages (EN+RU), to avoid missunderstandings.
>@polet123 unfortunately log file was not attached, try to answer throught GitHub and attach log.
>Was there any data in the app? (If not, it would be easier to reinstall app)
>@polet123 к большому сожалению лог файл не прикрепился, попробуйте отвечать через GitHub и приложите лог. Были ли какие либо данные уже введены в приложение? (Если нет, то разумнее будет сделать установку с нуля)
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!
