### ISSUE TITLE
Budgets: Left (per day) column not properly calculated when using non monthly periods 

### ISSUE THREAD

**Issue by TonyDavid** [firefly-iii/firefly-iii#3759]
**Bug description**
I am running Firefly III version 5.3.3 

I've noticed the per day part in the Left (per day) colum of the budgets table is not properly calculated when using for instance weekly or daily fixed amount periods. 

The (per day) amount is calculated as if what is can be used in a month instead of the actual period. e.g. if you got 28$ left for a week, it should be 4$ per day (28$/7 days), instead firefly will show 1$ (28$/28 days).

Replicated on the demo site: [https://demo.firefly-iii.org/budgets](https://demo.firefly-iii.org/budgets) (tobacco and illegal stuff budgets)

Here's a screenshot with notes which probably will be more clear then what I've written here.

![bug_per_day](https://user-images.githubusercontent.com/3625328/92039704-cc22a300-ed75-11ea-823c-352b428d05b8.png)

ps: great program nonetheless 👍

**Comment by JC5** [comment]
I see it, thanks! I'll pick it up.

**Comment by JC5** [comment]
Fixed in the next release. Since the view you're looking at always calculates per [period], and the budgets may have a different period, the displayed amounts left make no sense. They're removed in the next release.

**Comment by JC5** [comment]
Closed because beta 1 is out.
