### ISSUE TITLE
Is there readonly account or readonly mode?

### ISSUE THREAD

**Issue by billypon** [firefly-iii/firefly-iii#3763]
I am running Firefly III version 5.3.3

**Description**
I want to use Firefly to manage family finance, is there any way to add a readonly account, or sign in with readonly mode, so that another one can view the financial data only.

**Extra info**

**Bonus points**
* I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by JC5** [comment]
I'm afraid not. One user = one administration.

**Comment by billypon** [comment]
So I think Firefly is suitable for personal financial manager, not family's. I need a financial manager, someone can manage the data, the others can only view it.

**Comment by billypon** [comment]
Share username/password can view the data, but can make misoperation also.

**Comment by JC5** [comment]
Yes that’s the reason I call it a “free and open source personal finance manager”.

**Comment by billypon** [comment]
Is there a plan to add this feature? Or could you give me some suggestions, I can try to do it myself

**Comment by JC5** [comment]
No. You'll have to rewrite the entire app. Every query is based on user ID's.

**Comment by billypon** [comment]
OK, thanks

**Comment by psychowood** [comment]
@JC5 would you consider some sort of read-only mode settable for example by environment variable?

This is not ideal of course, but it could be usable compromise:
- use the flag to completely disable any kind of write, system wise (APIs that change data would throw an error, maybe add some minor UI changes to disable/hide buttons)
- deploy a dedicated read-only instance that shares the same DB

**Comment by Extarys** [comment]
On the same note, I was thinking if you create a **user 2**, **user 1** then can give read/write access to **account 5**. It would require a permission table of some sort.

When a user log in, it would check against the permission table to display additional accounts. when **user 2** create a transaction for **account 5**, an additional column to identify which user made the transaction is required and would be populated when it is not the owner (user 1) who made the transaction.

I know it's more complicated than that. Just putting this here.
