### ISSUE TITLE
github actions service containers

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#3764]
**Description**
you can run database integrated tests using service containers. should be able to do as part of github actions

**Solution**
See example with jobs for mysql, postgres,and mssql https://github.com/lastlink/dotnet-ci-pipelines/blob/master/.github/workflows/dotnetcore.yml.

**Comment by JC5** [comment]
I'm pretty happy with my Travis setup and I'd like to limit my dependency on GitHub.

https://travis-ci.com/github/firefly-iii/firefly-iii
