### ISSUE TITLE
Autofill full details of a transaction when selecting from the suggestion box

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#3766]
Continuation of #2340 (I can't comment on that ticket since it was locked down).

Suggested alternative to this feature has been rules. However rules have two major drawbacks compared to full auto-fill:

1. Some fields (such as Source Account or Amount) must be filled manually, even if there is rule set for those since Firefly will not let me submit form without those
2. I still have to enter Rules for all transactions that I want to auto-fill. So rules are only feasible alternative for recurring transactions that repeat often enough that they are worth making rule for

I am prepared to make a Pull Request for that functionality if you accept (either description or speedkey version suggested by @iwalucas). I could also disable it by default and add config option to enable it, which solves the "new user" problem that you mentioned (although I personally don't see how is that feature problematic for new users).

**Comment by JC5** [comment]
Thanks for the offer, but I’m not going to make this a part of Firefly III. I don’t see the advantage of having this feature over the code base it’ll take to implement this and the associated maintenance costs.

**Comment by matejdro** [comment]
Well, if you rejected this then it does not make sense to have issue open and cluttering issue tracker. Closing down.
