### ISSUE TITLE
journal file attachments

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#3768]
**Bug description**
I am running Firefly III version v5.4.0-alpha.3!, and my problem is:
when attaching files to separate journals in a split transaction when **creating** a transaction the journal they get attached to isn't consistent.  It seems that they get attached to the last journal in the split and then the one after. e.g. I have 4 splits. I add a file to the first and one to the 3nd. when saved and viewing in the db and from the show page they are attached to the last 2 splits.

**Comment by JC5** [comment]
Indeed. At least one array is reversed when uploading attachments. Thanks for letting me know. Should be fixed in the next alpha!

**Comment by JC5** [comment]
Closed because beta 1 is out.
