### ISSUE TITLE
How to reset password ?

### ISSUE THREAD

**Issue by hong-duc** [firefly-iii/firefly-iii#3771]
I am running Firefly III version 5.3.3.

**Description**

I tried setup yahoo mail to send reset link but it return 554 email rejected. Is there another way to reset password ?

Thanks

**Comment by JC5** [comment]
The email message is also in your log files.

**Comment by hong-duc** [comment]
Oh I see.  I will check it

**Comment by hong-duc** [comment]
ah I changed MAIL_MAILER=log then I can see the email message. Thanks
