### ISSUE TITLE
Personal Access Tokens for remote-user-guard mode, and i18n

### ISSUE THREAD

**Issue by danjl1100** [firefly-iii/firefly-iii#3772]
**Description**

Two distinct (but related) items on the `/profile` page:  (using version 5.4.0-alpha.3)
1. The "Personal Access Tokens" menu is hidden when `AUTHENTICATION_GUARD=remote_user_guard`.  
    * See details below. All the OAuth, 2FA, session options make sense to hide, but I would think this should remain visible.
1. Internationalization is not working in some buttons/links [on `/profile` page on the demo site](https://demo.firefly-iii.org/profile), screenshots below. I'm seeing "Uždaryti" / "Ištrinti" instead of "Close" / "Delete". 

**Additional Context**

Current state (5.4.0-alpha.3)
``` text
   - Options
       - Change your email address   [AUTH=web only]
       - Change your password        [AUTH=web only]
       - Logout
       - Logout all other sessions   [AUTH=web only]
       - Delete account              [AUTH=web only]
   - Command line token
   - OAuth                           [AUTH=web only]
       - OAuth Clients               [AUTH=web only]
       - Personal Access Tokens      [AUTH=web only]
   - 2-step verification             [AUTH=web only]
   - Delete data from Firefly III
```

**Solution**
Proposed state, changes marked with **
``` text
   - Options
       - Change your email address   [AUTH=web only]
       - Change your password        [AUTH=web only]
       - Logout
       - Logout all other sessions   [AUTH=web only]
**     - Delete user account         **RENAMED. Consider making this ALWAYS VISIBLE?
** - Access Tokens                   **RENAMED.
       - Command line token
**     - Personal Access Tokens      **MOVED. ALWAYS VISIBLE.
   - OAuth                           [AUTH=web only]
       - OAuth Clients               [AUTH=web only]
   - 2-step verification             [AUTH=web only]
   - Delete data from Firefly III
```
* NOTE: **Personal Access Tokens** is the primary goal.  The note below is just "what if?"
    * `Delete (user) account` being visible for `remote_user_guard` could be a convenience feature for "starting over" a particular user.  This is meant to be similar to the steps taken by `AUTH=web` mode when user is deleted.  This is certainly more than just a cosmetic change, since it requires splitting the "delete all entries for user X" action from the "delete user X" action. `web` can do both parts, but `remote_user_guard` can only do the former.

**Bonus points**

Screenshots:
1. Personal Access Tokens not shown when configured as `AUTHENTICATION_GUARD=remote_user_guard`.
![firefly_visual_profile__remote-user-guard](https://user-images.githubusercontent.com/45136864/92333153-f364c300-f048-11ea-8fbe-d392a6140ca4.png)
1. DEMO SITE i18n quirks.   Seems to be in most of the `/profile` menus.
![firefly_visual_personal_token_DEMO_SITE_markup](https://user-images.githubusercontent.com/45136864/92333168-18593600-f049-11ea-9044-4e3229f018d3.png)
![firefly_visual_oauth_DEMO_SITE_markup](https://user-images.githubusercontent.com/45136864/92333169-1a22f980-f049-11ea-9f92-8f05789a7644.png)

**Comment by JC5** [comment]
Thx for letting me know. A quick reply from my home. The i18n quircks can certainly be fixed. Any and all authentication methods are handed over to the auth proxy and that includes personal access tokens.

**Comment by JC5** [comment]
The delete button will not be restored for remote with users. Not even to “start over”. Use the delete tab in your profile.
