### ISSUE TITLE
Add the ability to group certain transactions

### ISSUE THREAD

**Issue by JakeMHughes** [firefly-iii/firefly-iii#3773]
**Description**
I would like the ability to group certain transactions, basically I want a split transaction but with the ability to change destination account. 
An example use case: payroll transactions. Its not uncommon for people to have retirement accounts like 401K or Simple IRA so it would be nice to group them so you have net pay as well as the retirement account contribution under one transaction group

(to add to this, it would be nice to be able to add to a group a transaction thats Revenue Account -> Expense Account for taxes but this is probably just my personal opinion)

**Solution**
Allow the destination account to be modifiable in a split given certain transactions. Or create a split clone that just works slightly differently

**What are alternatives?**
Currently you have to do each transaction separately if they have different destination accounts

**Comment by JC5** [comment]
The current way of splitting transactions won't change.
