### ISSUE TITLE
Merge Account balances on Charts

### ISSUE THREAD

**Issue by dealanis** [firefly-iii/firefly-iii#3774]
**Description**
Currently the "Account balances" and "Your accounts" display all the respecting accounts separately on a same graph with different colors.

![image](https://user-images.githubusercontent.com/1350480/92335248-1009f680-f05b-11ea-912d-0c5a42574c91.png)

**Solution**
Add a toggle or admin option to change the view to a "consolidated" or "merged" one where all the balances currently showing on the graph sum up to display just a single line. This would simplify getting visual data form a report or dashboard with a glance.

![image](https://user-images.githubusercontent.com/1350480/92335337-c79f0880-f05b-11ea-8850-310b9009ea1f.png)

**What are alternatives?**
My current alternative is to increase default report period so it automatically changes to "income vs expense" graph and then use that visual data for analysis (more expenses than last month, increase on savings, etc)

**Additional context**
This could work as a "net worth" style visualization of the reported accounts or dashboard. When too many accounts are considered the graph quickly gets overcrowded and can't get any real value from it even with the help of the info balloons that show up when pointing with mouse over nodes.

**Bonus points**
I tried to search another request of this or something similar on the past without success.  Hope there is a viable way to achieve this or something similar.

I'm of the idea that seeing net worth or accounts behavior over time with a slope going up or down gets the message pretty clear of where things are heading.

As always, thanks for your great work and time!

**Comment by elmig** [comment]
It would be nice if appeared on the graph with a second axis scale so it doesn't take resolution on the individual accounts. Clicking on the icon "net worth" would be great to see the evolution.

**Comment by JC5** [comment]
I'll write it down and see what I can do :)

**Comment by JC5** [comment]
This will be part of the new layout.
