### ISSUE TITLE
CSV Importer shuts down on SIGWINCH

### ISSUE THREAD

**Issue by darnir** [firefly-iii/firefly-iii#3783]
**Bug description**

The problem is with the CSV Importer. However, the repository doesn't have issue reporting enabled, so I'm reporting it here.
CSV Importer: v2.1.1

The CSV Importer "gracefully shuts down" when it receives a SIGWINCH. 

**Steps to reproduce**

1. Start the docker container for the Importer in a shell.
2. Resize the shell

Resizing the shell sends a SIGWINCH signal to the process running in it. In this case, the CSV Importer. On receiving the signal, it decides to shutdown. There is no good reason for this behaviour.

**Extra info**
Running on Linux. Any version / distro / shell will cause this

**Bonus points**

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3708
