### ISSUE TITLE
How to see tags in all tables? Not only when we open a transaction.

### ISSUE THREAD

**Issue by spyesx** [firefly-iii/firefly-iii#3784]
I am running Firefly III version 5.1.1.

**Description**

I use tags in addition to categories quite a lot for each transactions. Unfortunately I can't find a way to add tags in all tables. I can see categories but to read tags I have to open each transaction.

![Screenshot 2020-09-08 at 16 10 32](https://user-images.githubusercontent.com/372514/92487780-0238aa80-f1ee-11ea-836b-da1a320842f3.png)

Is it normal or do I have a bug? If it's normal, I propose to add the option in the user profile. Tags are very useful but they loose their power if we can't see them.

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ: yes
- I added a screenshot: yes
- I added log files : Let me know if it's needed. I thought the screenshot is enough.
- I was able to replicate the issue on the demo site.: yes, [exemple available on the transactions' page](https://demo.firefly-iii.org/transactions/withdrawal)

**Comment by JC5** [comment]
Sorry, tags are not visible in the tables, because they'd be too crowded otherwise.

**Comment by JC5** [comment]
It's not going to be an option. Sorry, tags just don't have the priority in the UI. What you do is fine but it just doesn't fit.
