### ISSUE TITLE
Make the header bar stick to the top of the screen when scolling

### ISSUE THREAD

**Issue by matthiasstraka** [firefly-iii/firefly-iii#3787]
I often scroll down a long page and would like to have the main-header bar visible at all times plus reach sidebar controls without scrolling back to the top.

A simple fix would be to make the _.main-header_ class have 
```
position: fixed;
width: 100%;
```

ideally, the main-sidebar and control-sidebar should be fixed as well. This can be done with simple _position: fixed_ CSS attributes but this potentially causes problems on small screen where scrolling is needed.

**Comment by JC5** [comment]
Maybe in the new layout, thanks for the suggestion!

**Comment by JC5** [comment]
The new layout will have this :+1:
