### ISSUE TITLE
Heroku installation fails for v5.4.0-alpha.3.

### ISSUE THREAD

**Issue by iamayushjain** [firefly-iii/firefly-iii#3789]
When trying to install Firefly III version v5.4.0-alpha.3, app creation failed at Build App, with the message :
**"Here was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again."**

Nevertheless, the deployment is working smooth for the v5.3.3 version([Link](https://dashboard.heroku.com/new?template=https://github.com/firefly-iii/firefly-iii/tree/5.3.3))
Build Logs : [error_firefly.txt](https://github.com/firefly-iii/firefly-iii/files/5203302/error_firefly.txt)
 
<img width="1420" alt="Screenshot 2020-09-10 at 9 54 05 PM" src="https://user-images.githubusercontent.com/15954264/92762507-4bd0f300-f3b0-11ea-8e68-a3e4ffc69b57.png">

Thank you for the help.
Best regards.

**Comment by JC5** [comment]
Thanks, nice find. Should be fixed with the next (pre)release.

**Comment by JC5** [comment]
Closed because beta 1 is out.
