### ISSUE TITLE
available budget not displaying in ui

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#3790]
**Bug description**
When  setting avaiable budget, even though db has the data, it doesn't display in the ui and it also possible creates duplicates. Tested on 5.4.0-alpha.3. tried for week and month periods.

**Extra info**

Debug information generated at 2020-09-11 00:39:26 Europe/Amsterdam for Firefly III version **5.4.0-alpha.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.0-alpha.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.9 |
| Host | WINNT |

| System info | Value |
| --- | --- |
| Installation ID | 2afcd254-b42e-4a54-a025-5de914b4a240 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | cli-server |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | sqlite |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 23:59:59 |
| Session first | 2020-07-14 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en-US |
| Attempt at "en-US.utf8" | 'en-US.utf8' |
| Attempt at "en-US.UTF-8" | 'en-US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.44 |

**Comment by JC5** [comment]
I'm not entirely sure what you're running into. The "available budget" is the overarching amount you can set for each period on the top of the `/budgets` page.

>  it doesn't display in the ui 

Where doesn't it show, exactly? The available budget bar seems to work fine.

> and it also possible creates duplicates.

How, when, what makes you think it creates duplicates?

**Comment by lastlink** [comment]
Here's a picture. After updating the available budget, the amount stays at 0.

![avilablebudget](https://user-images.githubusercontent.com/6679425/92919373-5c0fbf00-f3fe-11ea-8d79-b8a7aff620c6.PNG)

**Comment by JC5** [comment]
Mmmm. Thx. I'm having a hard time replicating this (on the demo site). It looks like it's not being stored, possibly because of the duplicate like you indicated.

Is there anything in the logs?

**Comment by lastlink** [comment]
I had this same issue on a mac and windows machine using sqlite db. I did a fresh clone and spun it up and still saving as 0.

**Comment by JC5** [comment]
Ah SQLite, thanks for the headsup. I totally missed that in your debug info table 😅 .

Fixed in the next release.
