### ISSUE TITLE
Budget view page not working correctly

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3791]
v5.4.0-alpha.3, can't test on v5.3.3 .

- Simple budget, active, no autobudget
- No budget set
- Got a bunch (less than 5 per year) of transactions over the years 2008 through 2020

Things I noticed:
1. right shoulder with yearly recaps is missing, only two "show everything" links, all of them linking to the same page ( /budgets/show/X ) and it is not possible to navigate to previous periods even it there are transactions connected with the budget. The transactions table shows the current year.
2. Main view shows " Chart of all transactions for budget test budget" but the three "Expenses by " charts are showing only current year, the same way of the transactions table
3. Main chart is showing values shifted backward by one year

<img width="1795" alt="image" src="https://user-images.githubusercontent.com/115389/92821522-72505780-f3cb-11ea-8274-ee82a062238d.png">

Report view is correct:

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/115389/92821671-9ad85180-f3cb-11ea-959c-e631e8a5af81.png">

I suppose this behaviour is related to not having a budget set, maybe it is correct... I was expecting to be able to navigate in past periods, the same way it can be done with categories.

I was able to replicate it on the [demo site](https://demo.firefly-iii.org/budgets/show/6), by creating a new budget and cloning some transactions.

**Comment by JC5** [comment]
Thanks for letting me know, I'll dive into it. Not having budget limits does indeed limit the page.

**Comment by JC5** [comment]
1. Fixed.
2. Fixed.
3. Fixed!

**Comment by JC5** [comment]
Closed because beta 1 is out.
