### ISSUE TITLE
Cover reservations

### ISSUE THREAD

**Issue by matthijsvdr** [firefly-iii/firefly-iii#3792]
**Description**
So when paying using things like Apple Pay, my bank makes a Cover reservation (reserves the total amount on the card) but the actual payment is done later (This does not happen when using my card directly for example)

I would like to add these in firefly as soon as possible to manage budgets etc however the actual transaction date will be several days later than the payment date. Currently this means the following:

Add transaction -> wait for transaction to go though -> Go to firefly and find transaction -> Update transaction with new date

Currently I do not add these to firefly and wait for them to go though completely, however this makes budgeting harder and have to keep track of them.

**Solution**
Simplest solution: 
There could be a flag when creating the transaction that it is a cover reservation. This could then be shown inside the UI somewhere (maybe even just the transaction lists with a differed color and keep them on top until there marked as completed). So they are easy to find and update.

Better:
Add transaction without a date and mark them to be updated later. With a special and easy overview of all those that stil needs updating

Or some combination of both above

**Comment by JC5** [comment]
> I would like to add these in firefly as soon as possible to manage budgets etc

Edit the date when the transaction goes trhough. That's the solution. Your proposal is not from different what you do now except the date field is empty.

**Comment by matthijsvdr** [comment]
This is kind of true, however say there are 30 transactions and I have to find one between al of those based on the amount. 
So even just a checkbox that flags it as a cover reservation and a differed color in the view would help a lot

**Comment by death2cupbots** [comment]
A few thoughts:
1. Why do you need the date to match up with the withdrawal date? Wouldn't it be better for budgeting and category tracking to enter the transaction with the date you made it? This seems especially true when looking at the end of the month.
2. When I transfer money between banks, it withdraws from one account on one day and deposits into the other account on another day. This transaction can only have one date in Firefly so one of the accounts **must** have an incorrect date.
3. Couldn't you use a "cover charge" tag to accomplish this?
4. You could also change the dates while reconciling, as you're (potentially) going through the transactions individually then.

**Comment by matthijsvdr** [comment]
> 1. Why do you need the date to match up with the withdrawal date? Wouldn't it be better for budgeting and category tracking to enter the transaction with the date you made it? This seems especially true when looking at the end of the month.

There is already a field called payment date, that matches the payment date. And I like to keep the date the same as my online bank.
Why would you not like to keep them the same? if you ever want to look up something you don't be able to find it anymore because nothing matches.

> 2. When I transfer money between banks, it withdraws from one account on one day and deposits into the other account on another day. This transaction can only have one date in Firefly so one of the accounts **must** have an incorrect date.

Depending on how you look at it, limitation of the banking system or firefly. It annoys me but I cant get around it.

> 3. Couldn't you use a "cover charge" tag to accomplish this?

Tried it out, but search does not find the tag. It does not anywhere unless you open the transaction. 
Only way is Classification -> tags -> click tags -> overview


> 4. You could also change the dates while reconciling, as you're (potentially) going through the transactions individually then.

I'm not really reconciling, but just make sure they are correct after entering them --> Currently skip adding any cover reservation (meaning firefly on average a week behind of reality)
Also would prefer not have to update 70% of my transactions at the end of the month because this means sorting thought all transactions because dates change once the payment goes from cover to actual. And some faster than others, meaning the list in the bank is in a differed order then firefly. 



To add:
Not only the date might change, the amount can as well. 
This happens for example when filling the car with petrol where it asks what's the maximum amount you want? the actual amount is updated later.

**Comment by death2cupbots** [comment]
Yeah my firefly list is in a different order than my bank list. I honestly stopped really caring about the bank's order when I started using financial software (started with GNUcash). I look at the statement when I'm reconciling and then Firefly is my accurate view of my transactions. Bank descriptions tend to be really non-descriptive and unhelpful. I've got a credit card that can post up to 3 days after a transaction (even when it's not through Google Pay or Paypal).

Hmm...you could try adding a flag to the description? Like if you start it "COVER CHARGE --" or end it "-- COVER CHARGE" that'll come up just fine in the search. It also kind of has a more visual flair when you're just browsing. Or if you can use emoji, you could literally put a little flag in the description and search by that.

**Comment by JC5** [comment]
> Tried it out, but search does not find the tag.

In the new upcoming version, you can use `tag:test` or `tag:"some tag"`.

**Comment by matthijsvdr** [comment]
> > Tried it out, but search does not find the tag.
> 
> In the new upcoming version, you can use `tag:test` or `tag:"some tag"`.

Would work, but its not the most elegant solution. It requires people to remember to do it instead of setting it once and then its visible in the gui.
