### ISSUE TITLE
firefly-iii spectre importer / docs

### ISSUE THREAD

**Issue by PackElend** [firefly-iii/firefly-iii#3795]
**Bug description**
https://firefly-iii.gitbook.io/firefly-iii-spectre-importer/installing-and-running/docker
it is said that you need 
> the Spectre API App ID and secret. 

what makes you presume that you select _App_ in
![image](https://user-images.githubusercontent.com/3542031/93059191-a9936280-f670-11ea-9787-70f27b7ea732.png)
If you do so you get:

> Error :(
> The personal access token you added to the .env file is invalid. The error returned is:
> 
> AppsRestricted: Not available for apps.
> 
> This error can be a bit cryptic, and you can find common errors on this page in the documentation. Please refresh the page to validate your token again.

what is a bit misleading. 
Terminal output got me on the right path:

```
192.168.178.22 - - [14/Sep/2020:07:30:27 +0000] "GET /token/validate HTTP/1.1" 200 1197 "http://192.168.178.26:10005/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.44"
[2020-09-14 07:30:28] production.ERROR: TransferException: Client error: `GET https://www.saltedge.com/api/v5/customers` resulted in a `400 Bad Request` response:
{"error":{"class":"AppsRestricted","message":"Not available for apps.","documentation_url":"https://docs.saltedge.com/ac (truncated...)
```

>**"Not available for apps."**

made me try to chose _Service_ as type, what solved the issue.

**Solution**
Add the information, that the type _Service_ shall be selected when doing _New API Key_.

**Steps to reproduce**
do as described above 

**Extra info**
I noted that the new connections, created according to https://firefly-iii.gitbook.io/firefly-iii-spectre-importer/importing-data/select_connection create new connections in Saltedge / Spectre with 	_default_ff3_customer_ as _Customer identifier_. 
I added connections before I started the importer to check if it the connection can be added and having the ready when starting the app (what us useless).
May you want to add the information the connections are created dedicated to the _importer user_, regardless of what is pre-existing in  Saltedge / Spectre. 

**Bonus points**
nothing to say

**Comment by JC5** [comment]
Thanks for letting me know. Feel free to submit a PR to correct the text. This is useful information to add.

**Comment by JC5** [comment]
I forgot about this, but this is now fixed! :+1:
