### ISSUE TITLE
firefly-iii spectre importer - makes "Customer identifier" at Salt Edge configurable 

### ISSUE THREAD

**Issue by PackElend** [firefly-iii/firefly-iii#3796]
**Description**
I have two configurations of the Spectre Importer, each one has its own pair of App ID & Secret.
I presumed that connections are dedicated to API keys and not user.
I do have one configuration for demonstration purposes (using a demo firefly-iii docker image) and one for testing and production use. 
I don't want to see my accounts when I do a demonstration (or doing something to post in Reddit etc.) 

Moreover, I do have two PayPal accounts. This is historical as I need to separate currencies and this was the only possibility back then. 
Adding both accounts, both are named _PayPal (XO)_. I don't have a chance to rename than in Selt Edge. So the only chance I see is to use different _Customer identifier_ to differentiate.  

**Solution**
add the option have the docker run argument:
`-e SPECTRE_APP_CUSTOMER_IDENTIFIER=...`

**What are alternatives?**
getting confused :) 

**Additional context**
none 

**Bonus points**
none

**Comment by JC5** [comment]
Not a bad idea, I'll see what I can do.

**Comment by PackElend** [comment]
this is excellent news :) 

by the way, I have just noticed that I can add the same PayPal account twice. Salt Edge is not throwing an exception that these credentials are stored in an existing connection. That raises the possibility of doing wrong imports again.

**Comment by JC5** [comment]
That's on them I'm afraid.

**Comment by PackElend** [comment]
> That's on them I'm afraid.

that is clear, just mentioned another obstacle keep accounts clearly identifiable

**Comment by JC5** [comment]
This will be part of the next importer release :+1:

**Comment by JC5** [comment]
New release will be out tomorrow :+1:
