### ISSUE TITLE
Cosmetic issue in bills view

### ISSUE THREAD

**Issue by weimdall** [firefly-iii/firefly-iii#3797]
**Bug description**
Debug information generated at 2020-09-14 15:19:12 America/Montreal for Firefly III version **5.4.0-beta.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.0-beta.1 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.9 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 23:59:59 |
| Session first | 2018-08-16 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0 |

This is more a cosmetic issue :

![2020-09-14-152248_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/93130813-1292ce80-f6a1-11ea-98f2-1bf5e050f624.png)

In this screenshot, even though the bill has been paid in august, I still see "Expected 1 week from now".
A message like "Not paid yet" would be more accurate.

**Steps to reproduce**
- Set period to september
- Create a recurring bill
- Create a transaction for the bill in August

**Comment by JC5** [comment]
I'm not sure I get it. The text seems relevant for the current period, although "1 week" is stretching it.
