### ISSUE TITLE
Sql connections problem

### ISSUE THREAD

**Issue by ivanboytsov** [firefly-iii/firefly-iii#3799]
After installing Firefly-III on the new VPS and migrating data from old machine (imported Firefly database and moved all the content of /storage direcoty) I keep running into error time by time:
Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

SQLSTATE[HY000] [2002] No such file or directory ...

Database in on my localhost.

Debug information generated at 2020-09-15 21:00:06 Europe/Moscow for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 0f4ab6dc-e3fa-4e83-891c-fe0e316f4778 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-09-14 00:00:00 |
| Session end | 2020-09-20 00:00:00 |
| Session first | 1970-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 |
[exception.txt](https://github.com/firefly-iii/firefly-iii/files/5226877/exception.txt)
[fireflylog.txt](https://github.com/firefly-iii/firefly-iii/files/5226878/fireflylog.txt)

**Comment by ivanboytsov** [comment]
It is happening almost always when I open withdrawals page from 2 different devices under 1 account simultaneously. But I didn't observe this behaviour on my local server.

**Comment by JC5** [comment]
I'm not sure if this is something I can help with. It could be that the VPS server can't handle the load.

**Comment by ivanboytsov** [comment]
Could you provide instructions how to correctly migrate data from one server to another?

**Comment by ivanboytsov** [comment]
Probably it's too small of RAM. 512. With 1GB there is no sql connection problems.

**Comment by Ryonez** [comment]
@JC5 
I've just had this happen after an update myself.
![image](https://user-images.githubusercontent.com/16157130/93922452-0f18da80-fd66-11ea-8dfc-d9734909b234.png)

This wouldn't appear to be a db issue, it was functioning before, and I can still talk to the db myself via pgadmin. No other services that rely on the db have having issues either.
