### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by Agraphie** [firefly-iii/firefly-iii#3800]
Hi,

I am running Firefly III version 5.3.3. I'm just exploring the API for an app and was wondering about the `types` parameter. What's the difference between `revenue` and `Revenue Account` (same for all other types which stand as single but also as ` Account`). Sorry for opening an issue for this but I did not know where else to ask.

**Comment by emansih** [comment]
`revenue` and `Revenue account` is the same as both show the same response.

**Comment by Agraphie** [comment]
Thanks for the reply. I thought so too but when I trigger `/api/v1/accounts?types=assets` I get accounts with the type `expense` back. Same for `revenue`. Is that correct? Additionally, there seems to be a fallback that if a type canno be mapped/found just all accounts are returned?

**Comment by emansih** [comment]
> Additionally, there seems to be a fallback that if a type canno be mapped/found just all accounts are returned?

Yes, that is correct. https://github.com/firefly-iii/firefly-iii/blob/a553bfd142742ed6fcf82ec4a98dad66c3161b3d/app/Api/V1/Controllers/AccountController.php#L134

**Comment by psychowood** [comment]
> Thanks for the reply. I thought so too but when I trigger `/api/v1/accounts?types=assets` I get accounts with the type `expense` back. Same for `revenue`. Is that correct? 

It is correct because the parameter is _type_ without the final _s_, so it's like if you are calling it without filters.

**Comment by Agraphie** [comment]
Ah yes thanks. I just read 
> Optional filter on the account type(s) returned
and saw that the request on web goes to `/json/accounts?types=Asset account,Revenue account,Loan,Debt,Mortgage` that's why I somehow assumed the parameter for the API is also `types`.
