### ISSUE TITLE
CSV importer docker startup very slow due to chown on lots of files

### ISSUE THREAD

**Issue by dkomisar** [firefly-iii/firefly-iii#3801]
**Bug description**
I am running the latest docker container from dockerhub (2.1.1). When the CSV importer starts up it runs chown on the /var/www/html tree which contains a lot of files. This is taking multiple minutes every time the container restarts.

I have not tested building the container myself yet.

Maybe a bunch of unnecessary files were packaged by accident?

**Comment by JC5** [comment]
Yes, I know. It's been reported before and it's on my list to fix.

**Comment by dkomisar** [comment]
Sorry, didn't see any duplicates. I did get it working last night and there
were some other minor issues. The URL format has a typo and there might
have been one more thing. If you let me know what you think the correct fix
is for the chown issue, doesn't seem complicated so I can probably fix it
myself this weekend. I'm new to firefly and I don't know the php stack but
I know docker.

**Comment by JC5** [comment]
I'm rebuilding the Docker image, and this is on my list. What did you run into exactly?

**Comment by dkomisar** [comment]
You fixed it on Friday, thanks. It was the http:/X.X.X.X/ thing, tripped me
up for a bit before I saw it.

**Comment by JC5** [comment]
Yeah those files should be fixed as well, in the meantime. Thanks for the feedback!
