### ISSUE TITLE
Timezone database is corrupt during installation

### ISSUE THREAD

**Issue by ivanboytsov** [firefly-iii/firefly-iii#3802]
**Bug description**
I'm trying to install Firefly 5.3.3 on ubuntu 18.04 and on 
`php artisan migrate:refresh --seed`
I get
> PHP Fatal error:  date_default_timezone_get(): Timezone database is corrupt - this should *never* happen! in /var/www/firefly-iii/vendor/nesbot/carbon/src/Carbon/CarbonTimeZone.php on line 37
> PHP Fatal error:  DateTimeImmutable::__construct(): Timezone database is corrupt - this should *never* happen! in /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php on line 52

**Comment by JC5** [comment]
The timezone database isn’t part of Firefly III. Not sure what I can do.

**Comment by ivanboytsov** [comment]
Turns out is is due to new version of tzdata on ubuntu 18.04. It breaks even existing installation with the same error. Didn't find out how to restore it yet.

**Comment by ivanboytsov** [comment]
For info, it was tzdata=2018d-1
