### ISSUE TITLE
[Statistics] On chart when more than one month is displayed, add the average

### ISSUE THREAD

**Issue by Thieume** [firefly-iii/firefly-iii#3803]
**Description**
When displaying the statistics it is not possible to display the average of the period.
To be more clear : when displaying the budget chart with 3 months, I can have paid more things one month than another. I can be over or under budget. If I want to adapt my budget to an average, it would be nice to have on the charts a line representative of the average of my expenses.

The same idea can be seen with Tags for example.

**Solution**
In the charts add a line which displays the average of the period

![image](https://user-images.githubusercontent.com/3884674/93496422-79b5ba80-f90f-11ea-94e0-e8a79443bf67.png)

My idea directly linked to me is : at the end of a year with my budget "Motorbike" which was 100€ per month, what is the new average amount for next year if I want to do the same as the previous year ? If I wad over budget each month and the average is 110€, this average can give me ideas on my new budget.

**Comment by JC5** [comment]
You could also use the default report to see this, for any period you like.

**Comment by Thieume** [comment]
You're right. I hadn't seen that. Thanks
