### ISSUE TITLE
Feature: earned budgets

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#3806]
**Description**
should be able to make our deposits as part of our budget. Could make a budget limit negative that will 0 out when the deposits are matching. Also in the bar graph could have something similar to already spent, but already budgeted

**Comment by JC5** [comment]
Thanks for the suggestion. This has been discussed before and won't be a feature.  

https://docs.firefly-iii.org/faq/financials#what-do-i-do-with-people-who-pay-me-back

**Comment by voarsh2** [comment]
> Thanks for the suggestion. This has been discussed before and won't be a feature.
> 
> https://docs.firefly-iii.org/faq/financials#what-do-i-do-with-people-who-pay-me-back

Any reason why you don't want to do this?

**Comment by JC5** [comment]
Because it's a budget. A budget is meant for expenses. And budgets are pre-planned.

**Comment by lastlink** [comment]
Can't you pre plan your earnings as well? Maybe doing a negative amount in the budget. Some budgets I've seen the available should actually be 0 after savings from a previous month and paychecks and expenses balancing out.
