### ISSUE TITLE
Documentation unclear about personal access token usage

### ISSUE THREAD

**Issue by pztrn** [firefly-iii/firefly-iii#3807]
Looking at https://docs.firefly-iii.org/api/api#personal-access-token it is only clear how to create them, but not how to use.

I'm trying to write a simple chat bot for my family that will post current balance every morning to some chat. OAuth seems to be overkill as I just want to issue a request to one API endpoing. As I read in [CSV importer documentation](https://firefly-iii.gitbook.io/firefly-iii-csv-importer/installing-and-running/configure) I can use Personal Access Token (which should be easier that OAuth). But... How to use them?

**Comment by emansih** [comment]
In your API request header, you need 2 headers:

1. `Authorization: Bearer $PersonalAccessToken` 
2. `accept: application/json`

Here is an example using curl:

```
curl -X GET "https://demo.firefly-iii.org/api/v1/about" -H "accept: application/json" -H "Authorization: Bearer $PersonalAccessToken"
```

**Comment by pztrn** [comment]
Yes, I figured it out eventually.

This bugreport is about documentation being unclear about personal access tokens.

**Comment by JC5** [comment]
Personal access tokens are part of the OAuth standard and it's the only thing that's available for Firefly III. I decided not to repeat any OAuth2 documentation, info, guides, etc., in my own documentation.
