### ISSUE TITLE
Feature: Enter Saves Field

### ISSUE THREAD

**Issue by reteo** [firefly-iii/firefly-iii#3811]
**Description**
When I enter information into a field on Firefly III, I assume pressing [Enter] would simply save the field I'm typing in, or select the highlighted option in a drop-down menu.  However, in many cases (with the apparent exception of tagging), the [Enter] key instantly ignores the field I'm typing in, or the drop-down menu, and just presses the "Update" button for that page instead.

**Solution**
I would prefer to set things up so that the "Enter" key will simply store the current field's data, or select the highlighted entry in any drop-downs that are open.

**What are alternatives?**
At this time, the only alternative is to conscientiously use the mouse to click on the drop-down item, or click outside the field to save it.  For keyboardists, this can be a hassle.

**Comment by JC5** [comment]
This should work just fine. 

- Which version of Firefly III are you running?
- And which browser?
- Which form exactly?

**Comment by reteo** [comment]
Never mind; I forgot I was using an old version due to the inability to upgrade to PHP 7.4 (Nextcloud is incompatible).

**Comment by JC5** [comment]
No worries, thanks for opening a ticket. I appreciate it :)
