### ISSUE TITLE
Error "A non-numeric value encountered" when visiting the rule index page

### ISSUE THREAD

**Issue by polet123** [firefly-iii/firefly-iii#3812]
[111.zip](https://github.com/firefly-iii/firefly-iii/files/5252560/111.zip)

A lot of data has already been entered, I cannot install from scratch ..

**Comment by JC5** [comment]
- You don't need to ask for help in your title. We know that. It's not that people open issues here to talk about their day. 
- For other people to find the issue in the future, describe the problem clearly. Can you imagine if everybody did that? Try searching for a solution!

I edited your issue so this is more clear. Please do this yourself in the future.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3679

**Comment by polet123** [comment]
Sorry, this is my first time doing this
  
>Понедельник, 21 сентября 2020, 6:27 +03:00 от James Cole <notifications@github.com>:
> 
> 
>*  You don't need to ask for help in your title. We know that. It's not that people open issues here to talk about their day.
>*  For other people to find the issue in the future, describe the problem clearly. Can you imagine if everybody did that? Try searching for a solution!
>I edited your issue so this is more clear. Please do this yourself in the future.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!

**Comment by polet123** [comment]
Thank. It is difficult for me to search for answers to my question, as I translate my questions and try to find in the search. But nothing comes of it. I understand this is not mine or your mistake, we just live in different countries ..

  
>Понедельник, 21 сентября 2020, 6:28 +03:00 от James Cole <notifications@github.com>:
> 
> 
>#3679
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением Тарас Сергеевич!
