### ISSUE TITLE
Incorrect volume specified in 5.4.0

### ISSUE THREAD

**Issue by achembarpu** [firefly-iii/firefly-iii#3817]
Hi!

I just upgraded to 5.4.0 and noticed that the Release notes claim the Upload volume is `/var/www/public/storage/upload`, while the Dockerfile states `VOLUME [/var/www/html/storage/upload]`. Which is the correct one?

Thanks!

**Comment by JC5** [comment]
I’ll fix the release notes. Dockerfile is correct. Thanks for noticing!

**Comment by JC5** [comment]
Done and done. 5.4.1 will include it as well.

**Comment by JC5** [comment]
5.4.1 is here :+1:

**Comment by achembarpu** [comment]
Awesome, happy to help! 😄
