### ISSUE TITLE
rules not in UI

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3818]
Updated to firefly 5.4.0 and all of my rules have disappeared from the UI at /rules. All I can see now is:

>  Default rules
> All your rules not in a particular group.
> There are no rules in this group

I went into the database and confirmed that my rules table is still populated.

**Comment by 4e868df3** [comment]
If it helps, all the rule entries are in rule group id = 2.

**Comment by JC5** [comment]
Root cause is this issue. 5.4.1 is on the way. 

https://github.com/firefly-iii/firefly-iii/issues/3816

**Comment by 4e868df3** [comment]
amazing as always JC5
