### ISSUE TITLE
"settings" link doesn't use correct path (e.g. `domain.com/preferences` instead of `domain.com/firefly/preferences`

### ISSUE THREAD

**Issue by JanFeld** [firefly-iii/firefly-iii#3824]
**Bug description**
I am running Firefly III version 5.4.1, and my problem is:

After upgrading and checking out the new features i've noticed that the link to `settings` at the right side of the transaction information panel doesn't use the full path for my firefly installation. I've attached a screenshot of the link to make it easier for you to find.

The link should be (for my installation): 
`https://domain.com/firefly/preferences`
but is 
`https://domain.com/preferences`

**Steps to reproduce**

Create a transaction, click the link at the mentioned position.

![Bildschirmfoto 2020-09-22 um 10 05 27](https://user-images.githubusercontent.com/22739965/93858078-e1775700-fcbb-11ea-8e82-1fe8d894e682.png)

Best regards,
Jan

**Comment by JC5** [comment]
Ah yes, thanks. I'll see what I can do. The link is hard-coded in the translations probably. Will be fixed with the next release!
