### ISSUE TITLE
docker hub, arm tagged image is AMD64 architecture

### ISSUE THREAD

**Issue by StrikerExtreem** [firefly-iii/firefly-iii#3825]
I am running Firefly III version 5.4.1, and my problem is:

Change image version to 5.4.0 or 5.4.1 on an ARM based device, it will not start correctly

Using a raspberry pi with raspbian OS installed, and kubernetes 1.19.2

Came from 5.3.3 which works correctly

**Comment by JC5** [comment]
Thanks, I was made aware of the issue. I'm working on a fix!

**Comment by JC5** [comment]
Could you let me know if this tag is working as expected? `jc5x/firefly-iii:develop`

I'm specifically talking about `jc5x/firefly-iii:develop`.

DO NOT use `jc5x/firefly-iii:develop-*`.

**Comment by fprina** [comment]
I've started a brand new `jc5x/firefly-iii:develop ` environment on my PI3 and looks like it's started without issues

- docker-compose on raspbian OS

**Comment by JC5** [comment]
Glad to hear it. I'll continue the release and let you know when the latest image is fixed.

**Comment by JC5** [comment]
`docker pull jc5x/firefly-iii:latest` should work, it contains 5.4.1.

**Comment by fprina** [comment]
I've created a `docker pull jc5x/firefly-iii:latest` with my real data and as supposed it start flawless

Thanks

**Comment by StrikerExtreem** [comment]
Works, thank you.
Maybe look into csv-import too, last time i checked, it had the same issue. Meaning image being labeled wrongly.

BTW Nice docker hub cleanup 😄

**Comment by JC5** [comment]
Will do! And yes. Removed all of the old stuff 😁
