### ISSUE TITLE
Login button width too small for localized text

### ISSUE THREAD

**Issue by Ettemlevest** [firefly-iii/firefly-iii#3827]
**Bug description**
I am running Firefly III version 5.3.3 on Docker, and my problem is:
With Hungarian translation the login button is too narrow on wider screens. 

**Steps to reproduce**

Switch to Hungarian localization and go to the login page.

Problem present on Windows in Chrome v85.0.4183.121, Firefox v80.0.1, Edge v85.0.564.51. All languages that has the login text longer than 10 characters face the same issue.

![image](https://user-images.githubusercontent.com/1035942/93879867-cff27700-fcdc-11ea-9bc3-fc2de2d753b1.png)

![image](https://user-images.githubusercontent.com/1035942/93879826-bf420100-fcdc-11ea-9bfa-bc3f3b39ab7b.png)

**Extra info**

This is because of the button container is 4 column wide (`col-xs-4`) and before that the remember me container is 8 column wide (`col-xs-8`).

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.

**Comment by JC5** [comment]
Alright, thanks for letting me know. Should be an easy fix.
