### ISSUE TITLE
Error on /accounts/expense, cache/dada/... failed to open stream

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#3830]
When I go to /accounts/expense I have this error.

file_put_contents(/var/www/html/storage/framework/cache/data/1e/b3/1eb3fafb88e2711fb6b29131c904320cb562ae16): failed to open stream: No such file or directory

Erreur
Cette erreur est survenue dans le fichier "/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php" à la ligne 135 avec le code 0.

Stack trace
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(135): file_put_contents()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\Filesystem\Filesystem->put()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\Cache\FileStore->put()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\Cache\FileStore->forever()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(383): Illuminate\Cache\Repository->forever()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Cache\CacheManager->__call()
#7 /var/www/html/app/Support/CacheProperties.php(95): Illuminate\Support\Facades\Facade::__callStatic()
#8 /var/www/html/app/Support/Steam.php(95): FireflyIII\Support\CacheProperties->store()
#9 /var/www/html/app/Support/Steam.php(320): FireflyIII\Support\Steam->balance()
#10 /var/www/html/app/Http/Controllers/Account/IndexController.php(159): FireflyIII\Support\Steam->balancesByAccounts()
#11 [internal function]: FireflyIII\Http\Controllers\Account\IndexController->index()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/html/app/Http/Controllers/Account/IndexController.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\Http\Controllers\Account\IndexController->FireflyIII\Http\Controllers\Account\{closure}()
#20 /var/www/html/app/Http/Controllers/Controller.php(108): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}()
#22 /var/www/html/app/Http/Middleware/InterestingMessage.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\InterestingMessage->handle()
#24 /var/www/html/app/Http/Middleware/Binder.php(79): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\Binder->handle()
#26 /var/www/html/app/Http/Middleware/Range.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\Range->handle()
#28 /var/www/html/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): PragmaRX\Google2FALaravel\Middleware->handle()
#30 /var/www/html/app/Http/Middleware/Authenticate.php(74): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\Authenticate->handle()
#32 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#54 /var/www/html/app/Http/Middleware/InstallationId.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\InstallationId->handle()
#56 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#66 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\SecureHeaders->handle()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then()
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#71 /var/www/html/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle()
#72 {main}

Debug information generated at 2020-09-22 18:27:24 Europe/Brussels for Firefly III version **5.4.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.1 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 7d1b6763-6515-4f47-966c-9bb6d88f4795 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 23:59:59 |
| Session first | 2018-12-01 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 |

I tried to flush but with no success.
Do you know how I can fix this?

Thanks for you work!!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3829

If nothing works, destroy the container and recreate it. Let me know if it works!

**Comment by jlauwers** [comment]
I just did but with no luck.

**Comment by niklas2810** [comment]
Did you try to access `https://firefly.your-domain.com/flush`? This solved the issue for me and I had the exact same stacktrace :smile:

**Comment by jlauwers** [comment]
That's the first thing I did sadly.

Le mar. 22 sept. 2020 à 19:15, Niklas Arndt <notifications@github.com> a
écrit :

**Comment by niklas2810** [comment]
Oops, I didn't read your last two sentences properly... Sorry about that :(

**Comment by sephrat** [comment]
Same issue here. /flush did nothing, neither did stopping/removing the container. Just pulled the latest docker image and I'm still facing the issue.


```
file_put_contents(/var/www/html/storage/framework/cache/data/1e/ef/1eef2c0844c825d37a0ed9fcb8b399e1d31f7415): failed to open stream: No such file or directory. 
```


Something looks weird here:
```
ls -l /var/www/html/storage/framework/cache/data/
total 244
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 02
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 08
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 0a
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 0e
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 16
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 17
drwxrwxr-x 3 root     root     4096 Sep 23 08:31 1e
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 20
drwxr-xr-x 4 www-data www-data 4096 Sep 23 08:31 21
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 25
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 27
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 2e
drwxr-xr-x 3 www-data www-data 4096 Sep 23 08:31 32
```
That particular subfolder is owned by root instead of www-data. It's a consistent behaviour and same folder as OP.


Debug information generated at 2020-09-23 08:33:39 Europe/Paris for Firefly III version **5.4.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.1 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 1a3545fd-5d00-4cae-b310-196781cbf468 |
| Using docker? | true |
| Telemetry | true |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | fr_FR |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 23:59:59 |
| Session first | 2019-12-03 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0 |

**Comment by sephrat** [comment]
Changing ownership of that directory solved the issue. 
`docker-compose exec firefly-iii chown www-data:www-data /var/www/html/storage/framework/cache/data/1e -R`
/flush does not break it but recreating the container does.
Maybe a lead: upon container start up, 1e is the first and only subfolder in that directory (owned by root:root at that time).

**Comment by JC5** [comment]
I'm already rebuilding the base image, see [this commit](https://github.com/firefly-iii/docker-base-image/commit/64c7c7fd4f9dae14f6c0875c80b06303e0df11e8). Once done, I can run new 5.4.1 images.

I'll give a headsup when they're done.

**Comment by JC5** [comment]
@sephrat new 5.4.1 (`:latest`) should be there, let me know how/if it works. If you tail the log, expect this:

```
Now in entrypoint.sh for Firefly III
Entrypoint script version is 1.0.9 (2020-09-23)
```

**Comment by sephrat** [comment]
Yep, that worked. Thanks for the quick fix.

**Comment by jlauwers** [comment]
That worked! Thanks!
