### ISSUE TITLE
Permission error for /var/www/html/storage/upload

### ISSUE THREAD

**Issue by hamiltlr** [firefly-iii/firefly-iii#3833]
I am running Firefly III version 5.4.1 in Docker, image `jc5x/firefly-iii:latest`.

When trying to upload a file, I get:
```
 file_put_contents(/var/www/html/storage/upload/at-6.data): failed to open stream: Permission denied 
```

Going into the container, I can see that directory is owned by root. Changing the owner to www-data seems to fix the issue.

**Comment by JC5** [comment]
OK. I don't have enough to go on for a root cause.

**Comment by psychowood** [comment]
Do you have the upload folder as a docker data volume or mapped on fs outside of docker?

**Comment by hamiltlr** [comment]
I'm using a docker volume for the upload directory.

I think it's an issue with the docker image. Just doing the following shows that the directory is owned by root:

```
docker volume create firefly_iii_test
docker run -d -v firefly_iii_test:/var/www/html/storage/upload jc5x/firefly-iii:latest
docker exec -it xxxxxxx ls -l /var/www/html/storage/
  total 68
  drwxrwxr-x 1 www-data www-data 4096 Sep 21 17:52 app
  drwxrwxr-x 1 www-data www-data 4096 Sep 21 17:52 build
  drwxrwxr-x 1 www-data www-data 4096 Sep 21 17:52 database
  drwxrwxr-x 1 www-data www-data 4096 Sep 21 17:52 debugbar
  drwxrwxr-x 1 www-data www-data 4096 Sep 21 17:52 export
  drwxrwxr-x 1 www-data www-data 4096 Sep 21 17:52 framework
  drwxrwxr-x 1 www-data www-data 4096 Sep 23 22:15 logs
  -rwxrwxr-x 1 root     root     3296 Sep 23 22:15 oauth-private.key
  -rwxrwxr-x 1 root     root      812 Sep 23 22:15 oauth-public.key
  drwxrwxr-x 2 root     root     4096 Sep 18 05:15 upload
```

Also interesting is that I did the same above commands with the `develop` tag, and all the directories are owned by www-data.
