### ISSUE TITLE
Cron job documentation

### ISSUE THREAD

**Issue by andrej-g** [firefly-iii/firefly-iii#3834]
The Cron job documentation, at least for Docker, at https://docs.firefly-iii.org/advanced-installation/cron has old paths in the examples. `/var/www/firefly-iii` has changed to `/var/www/html`.

So instead of:
`0 3 * * * docker exec --user www-data <container> /usr/local/bin/php /var/www/firefly-iii/artisan firefly-iii:cron`

it should read
`0 3 * * * docker exec --user www-data <container> /usr/local/bin/php /var/www/html/artisan firefly-iii:cron`

**Comment by JC5** [comment]
Ah nice, thanks for noticing. Will you create a PR, or shall I go ahead?

**Comment by andrej-g** [comment]
No, you go ahead, thanks.
