### ISSUE TITLE
Custom report/ dashboard; tags in results

### ISSUE THREAD

**Issue by bastiiiii** [firefly-iii/firefly-iii#3836]
Hi,
how about to add a feature to create custom report forms?
Or do change the dashboard?
Would be very happy to have seperate charts for the different asset types.

Also I would like to change the charts from line to column and vice versa.

Haven't got time to look into the source code to implement it for myself and maybe it's not that hard to implement ;-)

Another suggestion would be to show the tags in the list of results for search, categories, transaction. Or maybe a checkbox to enable/disable such columns.
I'm migrating my custom made MS Access solution with sub categories. For the import I decided to pass the categories and sub categories via tags into firefly, now it would be great to see this in the result list, like in the block edit view.

Thanks and keep up the great work! I really like Firefly ;-)

**Comment by JC5** [comment]
Hey, glad to hear you like it. Most of these things have been suggested before and basically the answer is "no" for a variety of reasons. Things may change in the future of course, but what you see is what you get at the moment. 

I'm working on a new layout where there may be room for new fields. Extra options and customizations however will probably never happen. I'm a big fan of convention over configuration. It also helps me not having to maintain X versions of the same feature, knowing that only a relatively small amount of power users need the feature.

So there will probably never be a myriad of options to customize your dashboards and layouts, but once there's room for improvement, it'll be there.

**Comment by bastiiiii** [comment]
Hey,
thanks for the feedback.
Understood and this is fine for me. :)
