### ISSUE TITLE
Search/Rule engine is broken for various filters

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3840]
**Bug description**
I am running Firefly III version 5.4.1 (latest, demo site) and my problem is:

Using "Destination account is.."/"Source Account is.." as a rule trigger/search paramter does not work as expected, as well as some others. Some details are listed below.

**Steps to reproduce**

Every transaction is a valid result: https://demo.firefly-iii.org/search?search=destination_account_is%3A%22doesnotexist%22

Every transaction is a valid result:  https://demo.firefly-iii.org/search?search=destination_account_nr_is%3A%22doesnotexist%22

Internal error for: https://demo.firefly-iii.org/search?search=amount_more%3A21

Displays "Firefly III found 50 transactions in 0.005 seconds.", even though there are no results: https://demo.firefly-iii.org/search?search=doesnotexist

**Bonus points**

![image](https://user-images.githubusercontent.com/30748216/94041881-1c1be500-fdcb-11ea-90a4-ede7d2a59f7b.png)

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by psychowood** [comment]
Fyi, adding quotes to the amount value works: `amount_more:"5"`

**Comment by niklas2810** [comment]
> Fyi, adding quotes to the amount value works: `amount_more:"5"` 
> 

Okay, then this is a documentation issue: https://docs.firefly-iii.org/concepts/search#amount-of-the-transaction

However, this shouldn't throw an error/a more user-friendly error (e.g. breadcrumb).

**Comment by JC5** [comment]
Thanks for the expansive report!

- Yes. Non-existing accounts will trigger all transactions. This happens for all search queries where you input non-existing account details. Confusing but the current state of the art I'm afraid.
- The amount error will be fixed.
- I see what you mean. Fixed.

**Comment by JC5** [comment]
Account thing also fixed!

**Comment by niklas2810** [comment]
Thanks for the quick fix! 🙌🏼

**Comment by JC5** [comment]
No worries. Keep testing, I hope to release 5.4.2 tonight. After that, I'm away for about a week. So be quick 😉

**Comment by psychowood** [comment]
> Thanks for the expansive report!
>
> - Yes. Non-existing accounts will trigger all transactions. This happens for all search queries where you input non-existing account details. Confusing but the current state of the art I'm afraid.

**Comment by psychowood** [comment]
This may be related: I just noticed on the demo site that creating a transaction assigns the category _new-category_ and the tag _some,new,tag_ , but looking at the [rules](https://demo.firefly-iii.org/rules) there should not be anithing triggered

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/115389/94075726-04a92000-fdfc-11ea-9741-9c92ed914195.png">

[Editing the rule](https://demo.firefly-iii.org/rules/edit/2) shows it referring a not existing account:

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/115389/94075916-55207d80-fdfc-11ea-9315-a743a889d4cb.png">

**Comment by JC5** [comment]
Yes. That rule is invalid. I've pushed a fix to the data generator.
