### ISSUE TITLE
Translation for search filter is missing

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3842]
**Bug description**
I am running Firefly III version 5.4.2 (demo site) and my problem is:

https://demo.firefly-iii.org/search?search=destination_is_cash%3Atrue

(translation missing)

**Steps to reproduce**

Visit link

**Extra info**

![image](https://user-images.githubusercontent.com/30748216/94051926-9141e700-fdd8-11ea-9ee9-a6015c633d2b.png)

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nicely spotted. Also fixed "source_is_cash".

**Comment by niklas2810** [comment]
In rule triggers you always write `(cash) account`, wouldn't it be more consistent to write it on the search page as well instead of only `cash`? 😅

**Comment by niklas2810** [comment]
`source_is_cash` = `Source is (cash) account`
`destination_is_cash` = `Destinationis (cash) account`

**Comment by JC5** [comment]
Fair point, that would be more clear :+1:

**Comment by niklas2810** [comment]
Thanks! I've updated the translations for the German language (for 5.4.0+, these have been missing). When you build the new docker image/publish the next release, would it be possible for you to pull the update from crowdin before this? 😄 It's quite confusing to see the mixed-up language on my production instance 😅

**Comment by JC5** [comment]
Can do! :+1:

As your neighbor (NL) I feel I can make the joke about German pünktlichkeit? 😉  😅

**Comment by niklas2810** [comment]
Ugh, I guess you've got a point there 😅 😂 Thanks! 😃
