### ISSUE TITLE
How to filter for a cash account in a rule?

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3843]
**Bug description**
I am running Firefly III version 5.4.2, and my problem is: There is no clarification on how to use the new "Destination/Source account is (cash) account.

There has to be a trigger value, but neither `true` nor `1` is accepted. What kind of value is the user supposed to fill in here?

**Steps to reproduce**

1. Create a rule: https://demo.firefly-iii.org/rules/create/1
2. Select "Destination account is (cash) account
3. Fill in any value (I couldn't guess what to put in there)

**Bonus points**

- I searched and nobody reported this bug before
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Should jump to the "disabled" state. Forgot to update all cases in a JS file. Fixed!
