### ISSUE TITLE
Search filter has_no_category is broken

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3844]
**Bug description**
I am running Firefly III version 5.4.2 (demo site), and my problem is:

https://demo.firefly-iii.org/search?search=has_no_category%3A%22%22

Rule filter has_no_category is not working properly.

**Steps to reproduce**

Visit link

**Bonus points**

- I searched and nobody reported this bug before
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
https://demo.firefly-iii.org/search?search=has_no_category%3Atrue

**Comment by niklas2810** [comment]
Okay, then this is a bug. 

1. Create a new rule https://demo.firefly-iii.org/rules/create/1
2. Select `Has no category` as a trigger (it won't work).

Bug description: Firefly III defaults to "" instead of true

**Comment by JC5** [comment]
Ah yes, that's a bug. Nice. Fixed!
