### ISSUE TITLE
CSV importer - Too few arguments in file APISubmitter.php:235

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#3845]
Using CSV importer v2.2.0, I have this error:

The job could not be started, or failed due to an error. Please check the log files. Sorry about this :(.

Error(s)
Line #0:
(2) transactions.0.amount: Le champ transactions.0.amount doit être plus grand que 0. (original value: "0")
(2) Internal error: sprintf(): Too few arguments in file /var/www/html/app/Services/Import/Routine/APISubmitter.php:235

**Comment by JC5** [comment]
Nice find, fixed!

**Comment by JC5** [comment]
I'll see if I can push 2.2.1 tomorrow.
