### ISSUE TITLE
Date Range Picker contains vague wording

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3846]
**Issue description**
I am running Firefly III version 5.4.2, and my problem is:

If I pick a different date range in the upper right corner, there is no obvious setting to return to the default. Because of this, I used to always reset the date range manually and always wondered "why is there no way of doing this automatically?". Well, it turns out there is. To my mind, this option should be named `current month`, as the date range won't be set to the current day (what I always thought would be the case), but rather to the current month. 

It took some time for me to realize that `today` actually means `current month`, so I guess it would be more intuitive for new users if the name was changed.

If there's a reason why it's called `today`, please let me know! I simply wanted to point out that the wording confused me in that case and suggest a solution which is (at least from my perspective) more precise :smile: 

![image](https://user-images.githubusercontent.com/30748216/94059730-277b0a80-fde3-11ea-8389-1f848fdd70ed.png)

**Bonus points**

- I searched and nobody reported this before
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Sorry, you'll have to learn to live with this one.

**Comment by niklas2810** [comment]
Alright! ^^

**Comment by sephrat** [comment]
I must say I experienced the same trouble when getting my hands on Firefly III. Took me a while to figure out why the current month wouldn't be in that list and that "Today" was "Current month". 

At first I thought it was a default from the library but it seems it's Firefly-specific. 
https://github.com/firefly-iii/firefly-iii/blob/a553bfd142742ed6fcf82ec4a98dad66c3161b3d/app/Support/Http/Controllers/GetConfigurationData.php#L136
If I change firefly.today I get the following result (please forgive my poor attempt at displaying a fancy icon):
![image](https://user-images.githubusercontent.com/34862846/94930218-61749c80-04c6-11eb-8e46-ceeeb41677ff.png)



I would too believe that "Today" may not be the best wording choice, especially when it comes just before "Last seven days". I instinctively expect it to display only the transactions of the day, which is little to no use so I only tried it out of despair. How about "Now" or "Current period"? 

In case you definitely want to stick with "Today", could we at least assign the text to another string ID so we can translate it differently? You're more fluent than me in English to judge, but the translation for "Today" in French does sound a bit silly in this context.
