### ISSUE TITLE
Budgets: Budgeted/Spent/Available Amount - Available this Month not Settable / Bars Disappeared

### ISSUE THREAD

**Issue by JanFeld** [firefly-iii/firefly-iii#3847]
### Bug description
I am running Firefly III version _5.4.1_, and my problem is:

I can't set the available amount anymore, even though Firefly tells me, the amount has been set. After setting and receiving the success message, the amount is still _0.00 €_. The bars which show the available amount as well as the budgeted and spent amounts are not shown anymore. Maybe that's related to the new "Total Budgeted / Spent" feature which came with 5.4.1. 

It won't work on the demo site as well.

### Steps to reproduce
Setting the available amount on the budget page. 

Thanks for your continuous work!

Best regards,
Jan

**Comment by niklas2810** [comment]
I was able replicate this on the demo site https://demo.firefly-iii.org/budgets (5.4.2) as well. However, it works just fine on my personal instance (5.4.1), even though I can't quite tell what the difference between the demo and my instance is.

**Comment by JC5** [comment]
Sloppy programming by me. Should be fixed in the next release.
