### ISSUE TITLE
[Feature Req.] Transactions: Additional form element for linking to former transaction when creating a new one (for example for refunds).

### ISSUE THREAD

**Issue by JanFeld** [firefly-iii/firefly-iii#3849]
### Description
I'd like to have a possibility to link a transaction to another (former) transaction immediately when creating the new one. This would avoid extra steps for creating a link afterwards. Additionally this would help to link a 'refund' transaction to multiple split-transactions. Currently i have to link every split to the new refund-transaction manually using extra steps.

### Solution
Add a new (optional) form element similar to the _Link-Transaction Dialog_ on the _New Transaction_ page for each (split) transaction.
Could be a auto-fill form field using the name, maybe an additional dropdown for the link-type (_pays for, relates to, .._) defaulting to _relates to_ if link is set (otherwise _null_).

### What are alternatives
To link transactions it's required to select the transaction and link it manually using an extra page as well as the _Link-Transaction Dialog_.

### Additional context
Similar to this form/dialog:

![Bildschirmfoto 2020-09-23 um 22 16 19](https://user-images.githubusercontent.com/22739965/94064755-6d879c80-fdea-11ea-9528-82ed6b9622d5.png)

Best regards,
Jan

**Comment by JC5** [comment]
Possibly in the future. The form is overcrowded as it is. I like the idea!

**Comment by psychowood** [comment]
My 2 cents: add another checkbox in the bottom panel, that goes to the detail of the transaction and automatically open the modal to add a link.

<img width="455" alt="image" src="https://user-images.githubusercontent.com/115389/94169762-7d0cf100-fe8f-11ea-8d18-7d62b70ee1f8.png">

**Comment by JC5** [comment]
This will be part of the new layout and I'll keep track of previous suggestions separately.
