### ISSUE TITLE
Search preview does not work for boolean rule triggers

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3850]
**Bug description**
I am running Firefly III version 5.4.2 (demo site), and my problem is:

When clicking the "See matching transactions" button on the [rule page](https://demo.firefly-iii.org/rules), the default double quote `""` is not replaced with `true` for boolean triggers (e.g. `has_no_category` or `destination_is_cash`). The rule execution itself works as expected.

Link: https://demo.firefly-iii.org/rules/search/5

**Steps to reproduce**

Screenshot with rule setup (I have edited a transaction as well to receive a search result):
![image](https://user-images.githubusercontent.com/30748216/94105499-b286ef80-fe39-11ea-9c49-d810697a022b.png)

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Similar issue as the other one, but less urgent. Thanks for letting me know!
