### ISSUE TITLE
CSV Importer 2.2.0 - authentication error

### ISSUE THREAD

**Issue by 5833tP2** [firefly-iii/firefly-iii#3851]
I am running Firefly III version 5.4.1 and csv-importer 2.2.0 (both upgraded today).

**Description**
CSV Importer fails on launch with the following error:
```
Client error: `GET firefly-iii.home/api/v1/about` resulted in a `401 Unauthorized` response: {"message":"Unauthenticated","exception":"AuthenticationException"} 
```
**Extra info**
`.env` file is correctly copied from the previous version. Clicking `Reauthenticate` does not solve the problem.

**Comment by JC5** [comment]
Have you tried creating a new personal access token?

**Comment by 5833tP2** [comment]
New personal access token created and the previous error disappears. Good stuff.

I've generated a client id via the `oauth` tab of `firefly-iii` but get a `404` error when I submit this from `http://csv-importer.home/token`.

**Comment by 5833tP2** [comment]
I reinstalled `csv-importer` from scratch, then generated a new personal access token. All seems to be working now. Closing the issue. Thanks.
