### ISSUE TITLE
Layout: Breadcrumbs can overflow to cover page description

### ISSUE THREAD

**Issue by davidschlachter** [firefly-iii/firefly-iii#3856]
**Bug description**
I am running Firefly III version 5.4.2, and I have a cosmetic problem: the breadcrumbs and page descriptions can overlap / collide:

![Capture d’écran, le 2020-09-24 à 16 50 36](https://user-images.githubusercontent.com/8271268/94198981-1d5e1800-fe86-11ea-9176-dd01f718f2d7.png)

There's a range of window sizes where this will occur, but before these two items move to separate lines. I'm using Firefox 81, macOS, screen resolution 1440x900.

**Comment by JC5** [comment]
Yes. Especially for long titles. May be fixed in the new layout I'm working on. Otherwise I'm not too bothered.
