### ISSUE TITLE
Pagination not working correctly in accounts

### ISSUE THREAD

**Issue by Vilhjalmr26** [firefly-iii/firefly-iii#3858]
**Bug description**
I am running Firefly III version 5.4.2, and my problem is:

When looking at account transaction lists, no page control displays.  If I roll back to 5.3.3 it is fine.
Manually adding "?page=2" to the address correctly shows the second page of data, but still no controls.

**Steps to reproduce**
Login
From dashboard access Accounts->Asset Accounts
Select an account that has more than 1 page of transactions
No page buttons appear.

**Extra info**
Server is running on debian, client is running windows 10 with Firefox/Chrome (seen in both)
Installed/Using firefly through composer on self host, not docker

**Bonus points**
I was not able to see this on the demo site, but not sure what could be causing the issue.  
Attached screenshot shows difference in created code for my server, and the demo, in the pagination area.  

![left_mine_right_demo](https://user-images.githubusercontent.com/28853873/94319876-3a135200-ff51-11ea-99cc-526aa7bf1660.png)

**Comment by hakubo** [comment]
I can see the same issue.

**Comment by kairix-gh** [comment]
I also have this same issue, except it seems like pagination is broken site-wide, for example, I cannot page through expenses in a given month.

**Comment by Dainius14** [comment]
can confirm

**Comment by sephrat** [comment]
Found the root cause. PR on its way.

**Comment by JC5** [comment]
Indeed. Thanks, @sephrat.
