### ISSUE TITLE
Access all entries from OU

### ISSUE THREAD

**Issue by JacksonHub2** [firefly-iii/firefly-iii#3859]
I am running Firefly III version 5.4.1, running in docker, and enabled LDAP.

**Description**
My current config as follows:
```
ADLDAP_ACCOUNT_SUFFIX=",ou=group,dc=abc,dc=com"
ADLDAP_ACCOUNT_PREFIX="uid="
```
In LDAP directory, I created a new user under a new OU, let's say IT. 
When trying to login this account from FF, it failed.
After I change the firefly ACCOUNT_SUFFIX parameter to `",ou=IT,ou=group,dc=abc,dc=com"`, login success, but other users from root OU failed to login.

I'm wondering is there any ways to do a inherit directory access, so users from other OU could also use ff.

**Comment by JC5** [comment]
I don't know if this is possible, I'm using a library. As far as I know, it doesn't support the kind of `a` OR `b` search you'd require.

**Comment by JacksonHub2** [comment]
So this means by current we couldn't have a entry inherit from a specific OU? Is there ways to achieve this?

**Comment by JC5** [comment]
Not to my knowledge, no.
