### ISSUE TITLE
sonarqube analysis sonarcloud

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#3861]
**Description**
sonarqube gives good analysis of many language. sonarcloud is free for opensource. Would it be alright for me to do a github action that submits firefly for sonarqube analysis?

**Comment by JC5** [comment]
Firefly III is already being analyzed by Sonarcloud.

**Comment by JC5** [comment]
https://sonarcloud.io/dashboard?id=firefly-iii_firefly-iii

**Comment by lastlink** [comment]
Could we sonar cloud badges or linked added to the readme then?
