### ISSUE TITLE
Undocumented move from '/var/www/firefly-iii/storage/upload'  to '/var/www/html/storage/upload' ? 

### ISSUE THREAD

**Issue by phi-el** [firefly-iii/firefly-iii#3864]
I am running Firefly III version 5.4.2 on docker via portainer.

Yesterday i updated my firefly instance from 5.3.3 to 5.4.2. Today i was not able to download any attachment anymore. After digging into docker i found out that newly uploaded files are now located at '/var/www/html/storage/upload' instead of '/var/www/firefly-iii/storage/upload'. So causing any actions which remove the temporary working volume will result in data loss.

If this move is intended, please update the docs because the old path is still mentioned there.

**Comment by niklas2810** [comment]
This is documented in the changelog and the release info.

https://github.com/firefly-iii/firefly-iii/blob/main/changelog.md#540-api-140---2020-09-21

https://github.com/firefly-iii/firefly-iii/releases/tag/5.4.2

Nevertheless, it's true that the docs are not up-to-date yet: https://docs.firefly-iii.org/installation/docker#start-the-container

**Comment by JC5** [comment]
I'm not behind a pc until next week. For the docs, if you create a PR I can merge it.

**Comment by JC5** [comment]
Wait it worked. Docs are also updated. May take a moment to render. Thx for the signal!
