### ISSUE TITLE
Edit transactions during reconciliation

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#3870]
When reconciling, I often find that I entered wrong values for some transaction properties like the date or the amount. When I encounter such an entry, I always open the transaction in a new tab, fix the mistake and go on reconciling the remaining values. Then I restart the reconciliation process in order to check all the transactions that needed to be edited.

It would be great if Firefly III offered the possibility to edit a transaction's amount directly from the reconciliation view while simultaneously updating the remaining difference in the top right panel.

**Comment by sephrat** [comment]
Yeah I have the same tedious workflow, especially with recurrent transactions. It'd be great if we could do that on the same page without having to refresh the reconciliation page.
Not sure what exact changes to apply to the screen though. If you have an idea in mind, please share it.

**Comment by JC5** [comment]
I'll write it down as an enhancement and see what I can do. I recognize the use case although I rarely reconcile myself.

**Comment by JC5** [comment]
Will be part of the new layout.
