### ISSUE TITLE
"Initial Account Balance" Appearing in Destination Account

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#3871]
I am running Firefly III version 5.4.2.

Initial Balance entries, as well as a deleted account are appearing in the Destination Account auto-completion dropdown.  Please see the clip below.

This looks like a duplicate of #2427, so hopefully the fix can be easily re-applied.

![clip](https://user-images.githubusercontent.com/39804831/94457153-090d6a00-0169-11eb-86dc-c393368b2915.png)

**Comment by sephrat** [comment]
Confirmed. API call includes Initial balance account:
/api/v1/autocomplete/accounts?types=Asset%20account,Cash%20account,Debt,Expense%20account,Initial%20balance%20account,Loan,Reconciliation%20account,Mortgage
API path is set here: https://github.com/firefly-iii/firefly-iii/blob/3b56f4271e48a5e74fdbc4419eb750758beff0f9/resources/assets/js/components/transactions/AccountSelect.vue#L146-L149
Not sure if initial balance accounts are relevant in other cases. Let's wait for @JC5.

**Comment by JC5** [comment]
Yes. Technically correct but not very useful. I'll write it down. On the whole, I don't mind too much although it is confusing for (new) users.

**Comment by genofire** [comment]
This Problem happens again on my installation from git with Tag 5.5.8 ...

My workaround is to add in `app/Api/V1/Controllers/Autocomplete/AccountController.php` line 116:
```php
$types[] = AccountType::ASSET;
```

**Comment by JC5** [comment]
In layout v2?

**Comment by genofire** [comment]
what does `layout v2` mean?

---

Debug information generated at 2021-04-22 18:29:02 Europe/Berlin for Firefly III version **5.5.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.8 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 7944fba3-ecb7-4045-9b17-a64977540523 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-06-30 00:00:00 |
| Session first | 2015-12-31 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0 |

**Comment by JC5** [comment]
That's a "no" then ;). Thanks for letting me know this is still an issue.

**Comment by genofire** [comment]
Oh i have to update the `.env` - totally forgotten ... - in both v1 and v2 i got the same problem.

I believe it is a problem in the autocomplete api (there it is just v1 called) - same behavour see above.
