### ISSUE TITLE
the system does not automatically select the locale

### ISSUE THREAD

**Issue by nloshka** [firefly-iii/firefly-iii#3872]
Debug information generated at 2020-09-28 22:05:13 Europe/Amsterdam for Firefly III version **5.2.3**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.3 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.3.18 |
| Display errors | Off |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 23:59:59 |
| Session first | 2018-12-08 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, apcu, posix, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apc, igbinary, imagick, inotify, msgpack, zip, memcached, redis, Phar, Zend OPcache |
uname -a
Linux xxx.ru 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
php -v
PHP 7.3.18 (cli) (built: May 12 2020 08:04:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.18, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.18, Copyright (c) 1999-2018, by Zend Technologies
nginx -v
nginx version: nginx/1.16.1
After updating the system, it displays the message:
Bad server configuration: Firefly III cannot provide the correct format for monetary values because your server is missing the required packages. Follow the instructions explaining how to install them.

Although all settings are correct.
Where should I look and what needs to be corrected?

Also, pinning signs are not displayed in numbers.

**Comment by sephrat** [comment]
Latest version of Firefly III is 5.4.2 but your log shows 5.2.3. Can you try upgrading and see if it still happens?

**Comment by sephrat** [comment]
Also, check out the doc: https://docs.firefly-iii.org/faq/self_hosted#decimal-points-are-missing-numbers-are-off

**Comment by nloshka** [comment]
Just ran the update script:
cat fUpd.sh
#!/bin/bash
mysqldump -u root -h localhost -pxxx buh | gzip -9 > /var/www/xxx/BackUp/firefly-iii.$(date +%Y-%m-%d).buh.sql.gz
tar cvfj /var/www/xxx/BackUp/firefly-iii.$(date +%Y-%m-%d).tar.bz2  /var/www/xxx/firefly-iii/

cd /var/www/xxx/firefly-iii
#Go to the firefly-iii folder and run these commands:

git pull
rm -rf bootstrap/cache/*
rm -rf vendor/
composer install --no-scripts --no-dev
composer install --no-dev
php artisan migrate --seed
php artisan firefly-iii:decrypt-all
php artisan cache:clear
php artisan firefly-iii:upgrade-database
#php artisan firefly:verify
php artisan passport:install
php artisan cache:clear

**Comment by nloshka** [comment]
yum search language-pack
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.reconn.ru
 * epel: mirror.logol.ru
 * extras: mirror.reconn.ru
 * remi-php73: mirror.reconn.ru
 * updates: mirror.reconn.ru
Warning: No matches found for: language-pack
No matches found
unfortunately I’m not a debian or an apache
what you suggested I read but did not work.
I added the necessary lines in php.ini.

**Comment by sephrat** [comment]
Ah, maybe your git branch is still set on master instead of main? It changed recently. Maybe this breaks your script. Check the changelog before upgrading though, you need PHP 7.4 and I see you're running 7.3.
I'm not sure upgrading would fix it though, it's most likely linked to the missing package mentioned in the doc. I'm afraid I'm not familiar enough with that to help you, sorry.

**Comment by JC5** [comment]
Yum is part of red hat / centos right?

Google "centos install language pack" or something.

I can't do basic server support, sorry. I know nothing about centos
