### ISSUE TITLE
Rule values for destination/source account names/numbers are always invalid

### ISSUE THREAD

**Issue by SmokeySlim** [firefly-iii/firefly-iii#3873]
**Bug description**
I am running Firefly III version 5.4.2, and my problem is:

I cannot add or modify existing rules with triggers for 

destination account names: is/starts with/contains
source account names: is/starts with/contains
destination account number/ iban: is/starts with/contains/ends with
source account number/ iban: is/starts with/contains/ends with

No matter the value the error is always the same: "This value is invalid for the selected trigger.". However previewing via "See matching transactions" works.

It works without problem on the description field (and others as far as i've tested) though.

![afbeelding](https://user-images.githubusercontent.com/6567780/94541458-e7cf7b00-0247-11eb-8462-13fd1762c996.png)

**Steps to reproduce**
Create or edit a rule and set a trigger to one of the previously described attributes and fill in any value and save it.

**Extra info**
Debug information generated at 2020-09-29 11:33:36 Europe/Amsterdam for Firefly III version **5.4.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.2 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 49112060-c492-4bb9-8ba1-e8011fcc362c |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-09-28 00:00:00 |
| Session end | 2020-10-04 00:00:00 |
| Session first | 2020-09-26 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0 |

**Bonus points**

- I searched and nobody reported this bug before - yes
- I have added a stack trace from my log files - no
- I have added a screenshot. - yes
- I was able to replicate it on the demo site https://demo.firefly-iii.org/ - yes

**Comment by sephrat** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3853
