### ISSUE TITLE
Using "Foreign Amount" Field when calculating multi-currency budgets

### ISSUE THREAD

**Issue by NateSeymour** [firefly-iii/firefly-iii#3875]
**Description**

Let's say that I have 240 USD to spend a month on Education, and I create a budget, in USD, to manage said expenses. If I happen to spend some Euros on Education, I currently have to create a separate budget currency, and manually balance out the difference between Euros and USD between them.

**Solution**

I would like to, somehow, be able to use the "Foreign Amount" (USD) field on transactions that are in Euros to calculate the budget when it is only in USD.

For example:
I have a 14.75EUR transaction with a foreign amount of 16.00USD: my budget is subtracted by 16.00USD.

**What are alternatives?**

Manually add the amount of every EUR transaction to a new EUR budget, and subtract the foreign amount from the USD budget, as to "manually balance the budget."

**Additional context**

Firefly version: `5.4.2`

**Bonus points**

I'd be more than happy to work on the feature myself, if you don't have the time. However I would first like to discuss the implementation, how you would see it fitting in to the application, etc. first. I'm not sure what the best way to implement it would be. 

Thank you very much for making, and continuing to maintain `firefly`, it is a huge help to me!

Please don't hesitate to ask for clarification; I'm not sure if it's clear exactly what I'm trying to describe.

**Comment by JC5** [comment]
Yes, I understand what you mean and it's a very good idea. I'll write it down and pick it up.

**Comment by NateSeymour** [comment]
Thank you, I really appreciate it!

**Comment by JC5** [comment]
Should be part of the new release, seems to be working fine. If you're missing expenses or feel info is not there, let me know :+1:

**Comment by NateSeymour** [comment]
Thank you very much @JC5, I'm very impressed by how quickly you've implemented this and really appreciate your hard work on this project! :D
