### ISSUE TITLE
Allow forcing all application links to TLS

### ISSUE THREAD

**Issue by fluckx** [firefly-iii/firefly-iii#3876]
I am running Firefly III version 5.4.2

**Description**

I am trying to self-host this on a raspberry-pi ( containerized! ) and want it TLS-secured by default. I do this through the help of caddy, which reverse proxies to the running container and handles all certificate things for me. This runs fine, the only problem I have is that the application itself keeps referencing to HTTP urls rather than HTTPS URLS. I've tried to find an option somewhere so I can force it to generate https URLS instead. The consequence is that I cannot login because firefox is blocking it since it's insecure ( which makes sense ). I added in a screenshot.

Through this setup the firefly container is not aware that it's being served over HTTPS however.

Is there a way a flag I can use to make firefly:
- generate HTTPS links rather than http links? or..
- omit the host from the form URLs so it points to /login instead of http://<host>/login?

Note: I can bypass this by editing the html in-line with the firefox dev-tools and change the http > https or omit the protocol so it'll automatically use the same protocol/host it's currently on?

**Extra info**

I added to images where you can clearly see I'm running under HTTPS and the source showing that it's trying to send the request to the http URL on the login screen.

![Screenshot from 2020-09-30 16-04-54](https://user-images.githubusercontent.com/5868997/94697663-bda9b600-0338-11eb-9e13-dfbaf0a5ed0d.png)

![Screenshot from 2020-09-30 16-05-46](https://user-images.githubusercontent.com/5868997/94697671-bf737980-0338-11eb-8b30-bb6f059ed030.png)

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.2 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | fb19fc8b-0cdc-4826-a4be-1aaf6ed876d4 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0 |

**Comment by sephrat** [comment]
Check out this doc item: https://docs.firefly-iii.org/faq/other#i-cant-seem-to-get-https-working-with-caddy

**Comment by fluckx** [comment]
That resolved it! Sorry for missing this in the docs/FAQ. I had a look at the TLS encryption in the docs, but didn't go through the FAQ. I've used it for a while on my local machine without TLS and forgot about the env file.

Apologies and thanks for the help!
