### ISSUE TITLE
Inability to use recurring transactions due to missing 'type of repetition' selections

### ISSUE THREAD

**Issue by Tordarus** [firefly-iii/firefly-iii#3877]
I am running Firefly III version 5.4.2.

**Description**
I can't create any recurring transactions because the type of repetition input field is always completely empty.
The HTTP request responsible for retrieving the data seems to return 200 OK with an empty JSON array in the response body.
Because there is no error at all internally, the log files don't show anything as well.
I am using Firefly in German.

**Extra info**
The self-hosted server is a Raspberry Pi 3 Model B+ (Revision 1.3) with German locale.
I tried with multiple browsers on different platforms but it always stays the same, therefore I am relatively sure its a server-side problem.

Here is the output of the /debug page:
Debug information generated at 2020-09-30 16:51:39 Europe/Berlin for Firefly III version **5.4.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.2 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | fddc0eb0-d3ff-4d95-8381-0bb3d8821c92 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 23:59:59 |
| Session first | 2020-09-28 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Bonus points**
- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot (see below)
- I didn't add log files because there seems to be nothing related to this issue
- I was not able to replicate the issue on the demo site.

Screenshots:
![screenshot](https://user-images.githubusercontent.com/1444581/94702560-2ba4ac00-033e-11eb-9a44-3f7646a8cb6b.png)

**Comment by JC5** [comment]
This is usually a misconfiguration when your web server doesn't properly forward requests with a ? in them. There is no easy way to debug this although an easy check is this:

1. This is the URL you need: `http://YOURFIREFLY/recurring/suggest?date=2020-10-01&pre_select=`
2. The result must be like this:

```
{"daily":{"label":"T\u00e4glich","selected":false},"weekly,4":{"label":"W\u00f6chentlich am Donnerstag","selected":false},"monthly,1":{"label":"An jedem 1. Tag des Monats","selected":false},"ndom,1,4":{"label":"An jedem 1. Donnerstag","selected":false},"yearly,2020-10-01":{"label":"J\u00e4hrlich am oktober  1","selected":false}}
```

When it's not like this, find the following file: `/firefly-iii/app/Http/Controllers/Json/RecurrenceController.php`.

Go to line 150 and change it so it reads as follows:

```php
        var_dump($request->all());exit;
        $string      = $request->get('date') ?? date('Y-m-d');
```

When you visit the URL again, you should see this:

```
//firefly-iii/app/Http/Controllers/Json/RecurrenceController.php:150:
array (size=2)
  'date' => string '2020-10-01' (length=10)
  'pre_select' => null
```

If not, let me know.

**Comment by Tordarus** [comment]
Yes, this was the problem. Thank you :)
I've used a misconfigured nginx proxy. But now its working fine.
