### ISSUE TITLE
Cannot sort categories in a single month default report

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3878]
**Bug description**
I am running Firefly III version 5.4.2, and my problem is: You are not given the option to sort by category name or sum in a default report on a single month. I don't know if this is an intentional design choice. When you are doing multiple months, the sort is present. Almost every other section gives you the ability to sort in a single month.

![Screenshot from 2020-09-30 22-45-34](https://user-images.githubusercontent.com/21091510/94759766-cc12c480-036e-11eb-9538-7ad805fce0db.png)

**Steps to reproduce**
1. Make a default report based on a single month. (e.g. Sept 2020)
2. Go to the Categories section.
3. Try to sort by category name or sum and fail.

**Extra info**
Debug information generated at 2020-09-30 22:41:48 America/New_York for Firefly III version **5.4.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.2 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-09-06 00:00:00 |
| Session end | 2020-10-05 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 |

**Bonus points**
- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Indeed, will be fixed in the next release :+1:
