### ISSUE TITLE
No info box for no category items on default report

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3879]
**Bug description**
I am running Firefly III version 5.4.2, and my problem is: No info box appears when clicking the i button for (no category) in the categories section on the default report. The screen dims and a message saying "This is an unknown category. Apologies." appears in the top right corner.

![Screenshot from 2020-09-30 23-00-56](https://user-images.githubusercontent.com/21091510/94760558-da61e000-0370-11eb-8543-0fba0af4f0bd.png)

**Steps to reproduce**
1. Have or make a transaction with no category.
2. Make a default report based on the single month with that transaction. (e.g. Sept 2020)
3. Go to the Categories section.
4. Click the i button on the right side of the row for (no category).
5. The screen will dim but no box with transactions appears.

**Extra info**
Debug information generated at 2020-09-30 23:03:07 America/New_York for Firefly III version **5.4.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.2 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-09-06 00:00:00 |
| Session end | 2020-10-05 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nice, fixed :+1:
