### ISSUE TITLE
Unable to post new amount to piggy via api

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3880]
v 5.4.2

I am unable to update piggy banks since upgrading to 5.4. 

Sending a post to /api/v1/piggy_banks/50 used to work but now returns a 500 error.
`
SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference &quot;order&quot; is ambiguous
`

**Comment by JC5** [comment]
Crap. Stupid regression bugs. Will be fixed over the weekend :+1:
