### ISSUE TITLE
Editing a newly budgeted amount creates a new entry instead

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3881]
**Bug description**
I am running Firefly III version 5.4.2, and my problem is:

When I set a new amount for a budget and then change it again, when I refresh there are two entries on the same budget: the old one and the new one.
Reproduced on demo site.
![image](https://user-images.githubusercontent.com/34862846/94831175-b05dfb80-040c-11eb-831e-16355f4f861f.png)

**Steps to reproduce**
- Pick a budget with no amount yet
- Set a value, press Enter
- Change the value previously set
- F5

I can take a look at it tomorrow.

**Comment by JC5** [comment]
I see it. When you don't refresh the page in between setting a new budget. It keeps storing not updating.

**Comment by JC5** [comment]
Exactly. Right now it uses a separate route and that's something I'd like to get rid of anyway.

**Comment by JC5** [comment]
Fixed. Will pick up improvements in the next release.
