### ISSUE TITLE
Allow transactions to differentiate between booking and value date

### ISSUE THREAD

**Issue by funnym0nk3y** [firefly-iii/firefly-iii#3883]
I ran into a situation where the differentiation between booking and value date would be incredible helpful:

I live in a shared flat where we also get groceries and other things together. We track those expenses in an app like Splitwise. At the end of each month we pay our debts to each other. Now the problem in an example:

I want Firefly iii to replicate my bank accounts as close as possible. In June for instance I payed 150€ for shared expenses and the others owe me 20€ at the end of the month. The money arrives on my bank account in early July. If I create the transaction on the date the money arrives, the numbers for the bank account are valid, but the analysis for my expenses in June is off. If I book that transaction on the last day  of June, the expense analysis is correct, but the bank account numbers are off. 

Would be really nice if a solution to that could be implemented!

**Comment by JC5** [comment]
I know, but no. It is what it is. I can only suggest to store the transaction in June, since you know better than your bank what it's supposed to say.

**Comment by funnym0nk3y** [comment]
I just saw the possibility to add several dates when creating a transaction in the demo page. Do they have any further use in the calculations beside documentation?

**Comment by JC5** [comment]
Nope.
