### ISSUE TITLE
Deleting a previous split in a split transaction causes weird problems

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3884]
**Bug description**
I am running Firefly III version 5.4.2, and my problem is: When making a split transaction, if you have bills associated with the split and delete an earlier split, the splits will visually have the bill from the one that was above them. Also, in a 2 split transaction, if you delete the primary split, you lose the date and the source account. This happens with fresh transactions and edits.

Behold a split transaction:
![Screenshot from 2020-10-01 21-10-18](https://user-images.githubusercontent.com/21091510/94878517-a697c080-042b-11eb-84be-29a6dc9f80b5.png)
Notice how the first bill says "Weekly Bill" and the second one says "Quarterly Bill"

Now we delete the first split:
![Screenshot from 2020-10-01 21-11-27](https://user-images.githubusercontent.com/21091510/94878555-c29b6200-042b-11eb-996a-c077920a8987.png)
As you can see, the bill for Test #2 says "Weekly Bill" instead of previously saying "Quarterly Bill." You can also see the blank source account and date.

Here's the saved transaction:
![Screenshot from 2020-10-01 21-12-13](https://user-images.githubusercontent.com/21091510/94878696-202fae80-042c-11eb-831a-9f76132c6079.png)
Notice that the bill has reverted back to "Quarterly bill" showing that this is just a visual bug. I did have to fill the Source Account and Date back in though.

**Steps to reproduce**

1. Start creating or edit a transaction with at least 2 splits that have different bills attached to them.
2. Delete any split except the last one.
3. Look at any of the bills from splits that were below the one you deleted.
4. Notice they all appear to have inherited the bill that had been associated with the split above them.

**Extra info**
Debug information generated at 2020-10-01 21:27:26 America/New_York for Firefly III version **5.4.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.2 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for letting me know, I'll check it out! :+1:

**Comment by JC5** [comment]
> When making a split transaction, if you have bills associated with the split and delete an earlier split, the splits will visually have the bill from the one that was above them. 

Fixed.

> Also, in a 2 split transaction, if you delete the primary split, you lose the date and the source account. 

Fixed. This behavior remains in new transactions.

I pushed some fixes to the demo site. Could you see if this matches what you expect?

**Comment by death2cupbots** [comment]
Yes that matches my expectation. Thanks!

**Comment by vvrein** [comment]
I have the same issue, and can confirm that it is fixed in demo.firefly-iii.org

**Comment by JC5** [comment]
Glad to hear it, from both of you :tada:. I hope to push the new release this weekend.
