### ISSUE TITLE
Is there a way from the CLI to create a user?

### ISSUE THREAD

**Issue by smacz42** [firefly-iii/firefly-iii#3885]
I am running Firefly III version 5.2.8

## **Description**
I'm doing repeated testing installs via docker and would like to be able to create automated users.

### **Extra info**
This could be either via the `php` CLI or via the API (I don't think it can work without an initial user).

This is the only docs I can find: https://docs.firefly-iii.org/installation/self_hosted#registering-an-account
>Registering an account
>You cannot login yet. Click on "Register a new account" and fill in the form.
>
>Your first accounts
>You will be logged in automatically. Follow the instructions and you are done!

### Other Apps

For instance, Bookstack (a Laravel app) can use this:

```
      docker exec -i bookstack bash -c \"
        echo -e '
          \$user = Bookstack\Auth\User::where(\\\"email\\\", \\\"admin@admin.com\\\")->first();
          user->password = Hash::make(\\\"testpassword\\\");
          $user->save();'
        | php artisan tinker\"
```

However, that is with their default user (`admin@admin.com`), and I don't think that Firefly-III has a default user.

I guess the base ask is... "Is there a way from the CLI to create a user"?

**Comment by JC5** [comment]
There isn't. When testing myself I use a default sqlite DB I just copy around.

**Comment by JC5** [comment]
You did make me curious, anything I can help you with?

**Comment by smacz42** [comment]
I think at this point, my immediate option would be to scrape the web page to simulate a login.

Since I am deploying via docker, the other thing that I _could_ try is to set up a demo user, but I don't know if that user has the permissions to create new admin users, and the more I think about that, I'm pretty sure the demo user would not have those permissions.

Otherwise, If I had a wishlist, I would want to have an env var that I could set for the initial admin user/pass. Either that, or a [command](https://docs.firefly-iii.org/advanced-concepts/commandline#available-commands) that would be something like "create-admin".

**Comment by JC5** [comment]
I meant, with whatever you're trying to accomplish once you have the admin user you need.

**Comment by smacz42** [comment]
Haha, I love the placeholder function to deal with Laravel idiosyncrasies. In all seriousness, that's ridiculously cool that's implemented! I'll work on getting that tested ASAP.

I saw that it is in devel, is there any docker container for that branch, or do I have to work around that?

**Comment by JC5** [comment]
https://hub.docker.com/r/jc5x/firefly-iii/tags?page=1&name=develop

:+1:

**Comment by toyqiu** [comment]
so where may I find the CLI commands?

**Comment by JC5** [comment]
`php artisan` or `docker exec [container] php artisan`.

**Comment by toyqiu** [comment]
> `php artisan` or `docker exec [container] php artisan`.

thx
