### ISSUE TITLE
Removing bill from transaction does not work on the demo site

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#3887]
**Bug description**
On the demo site, I cannot remove a bill from a transaction.

**Steps to reproduce**
Check https://demo.firefly-iii.org/transactions/edit/439
set the bill to none and save. 
Bill is still linked to the transaction

**Extra info**
Chrome browser

**Bonus points**

- [X] I searched and nobody reported this bug before
- [X] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Good call, I think I know why. I'll pick it up, thanks!
