### ISSUE TITLE
Search account by notes field

### ISSUE THREAD

**Issue by ivanboytsov** [firefly-iii/firefly-iii#3888]
**Description**

Currently I am using notes in account to store custom fields in json format. And it is extremely hard to get specific account using values stored in notes via REST.

**Solution**

Add ability to search accounts through notes field.
**What are alternatives?**

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
What kind of fields/values are you storing in the notes field?

**Comment by ivanboytsov** [comment]
Cards numbers, cards ownership info, tax info for withdrawal and revenue accounts, names of accounts on different sources, mcc codes.
This all helps to automatically create transactions.

**Comment by JC5** [comment]
Sorry, it's not a feature. You'll have to hack something together yourself.

**Comment by ivanboytsov** [comment]
But why don't include notes to search options in API. For searching it would be convenient regardless type of information in the field.
