### ISSUE TITLE
[Cosmetics/Question] Budget Exceeded - Order of the Red and Orange Bars

### ISSUE THREAD

**Issue by JanFeld** [firefly-iii/firefly-iii#3893]
I am running Firefly III version 5.4.2

## Description
When i'm setting a budget available for a month and exceed the _available limit_ with the budgeted amount, i'll get a red and orange bar on the overview. I assume the orange bar is the available amount, the red bar is the amount exceeding the available amount. When changing the budget, the _red_ one appears at the end (right side) of the orange bar. After reloading or visting the page again, the read bar is at the left of the orange bar. Is this a bug or a feature or is it trying to express something special? To make it short: Is this intended behaviour? 

**Before reloading / When exceeding the available amount:**
![Before reloading](https://user-images.githubusercontent.com/22739965/94989454-372de800-0575-11eb-8649-eabae1eb0d4b.png)

**After reloading / revisiting the budget page:**
![After reloading](https://user-images.githubusercontent.com/22739965/94989452-36955180-0575-11eb-87d1-11f0c6cc60c5.png)

I tried on the demo page and it's pretty much the same.

Best regards,
Jan

**Comment by JC5** [comment]
That looks like a render bug, thanks. I'll tinker with it and see what I broke. The idea is that the orange amount is the available amount and red is what you spend too much. But that's clearly broken 😅

**Comment by JanFeld** [comment]
Oh.. My description is slightly different though.. I didn't see the actual color of the bar. I've just looked at the size of the bars. I just realised that the colors are flipped in the first one too. That's what screenshots are for. :smile:

Many Thanks!

**Comment by JC5** [comment]
Indeed 😁 . I fixed the bars. Red and orange are switched. It's live on the demo site if you want to check it out.
