### ISSUE TITLE
Change password minimum length 

### ISSUE THREAD

**Issue by UNICodehORN** [firefly-iii/firefly-iii#3895]
Hey :)

Thanks for this awesome piece of software. Just stumbled upon something:

- When registering a new user the password needs to have a length of 16. Where can I change this value?

Couldn't find something in the options, nor in the ``.env``, nor in the documentation. 
Thanks in advance for any help.

**Comment by JC5** [comment]
There isn't, I'm afraid. 16 characters is the minimum.

**Comment by my2817** [comment]
> There isn't, I'm afraid. 16 characters is the minimum.

but the demo website use "demo" as password,  why🤩

**Comment by waratte** [comment]
> > There isn't, I'm afraid. 16 characters is the minimum.
> 
> but the demo website use "demo" as password, why

Not directly helpful, but still useful: the password hash is just a bcrypt hash, I tried hashing my own password manually (using this site: https://bcrypt-generator.com) and swapping it in with the password I had in the database and it worked for logging in.
