### ISSUE TITLE
Configuration option to switch dashboard graph to be networth instead of individual accounts

### ISSUE THREAD

**Issue by cmaxwe** [firefly-iii/firefly-iii#3896]
Would be cool to be able to view net worth instead of the line graph with the individual account balances.

**Comment by JC5** [comment]
Meh. The point of the net worth is to show everything.

**Comment by cmaxwe** [comment]
True...but also when you have frequent transfers between accounts it is hard to get an understanding of your overall position by looking at the current graph.
