### ISSUE TITLE
Tags not saved with new transaction

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#3897]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:
If I create a new transaction and add a tag, the tag isn’t assigned to the transaction.
If I type a not existing tag into the tag field, the tag is created, but also not assigned to the transaction.
If I edit the transaction afterwards and add the tag, then the tag is saved correctly.
I think that the problem started about two weeks ago with the update to 5.4.0.

**Steps to reproduce**
Create a transaction with a tag.

**Extra info**
Doesn’t work with Firefox, IceCat and Chromium on Linux and MacOS. So I think it’s not client related :)

Debug page output:
Debug information generated at 2020-10-03 21:15:26 Europe/Vienna for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.10 |
| Host | Linux (Debian 10.6 with all updates) |

| System info | Value |
| --- | --- |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | production |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2008-06-08 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | de_AT |
| Attempt at "de_AT.utf8" | 'de_AT.utf8' |
| Attempt at "de_AT.UTF-8" | 'de_AT.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0 |

**Bonus points**
- I searched and nobody reported this bug before: Done, looked back until September 2019 for issues containing the word tag.
- I have added a stack trace from my log files: Done and attached ([debug_log.txt](https://github.com/firefly-iii/firefly-iii/files/5322258/debug_log.txt)); as you can see the tag is also in it.
- I have added a screenshot: Done
- I was able to replicate it on the demo site https://demo.firefly-iii.org/: Unsure. I was not able to replicate it in the afternoon. When I tried it in the evening it seemed that the demo site doesn’t work as expected.

![create_transaction](https://user-images.githubusercontent.com/24813122/95000751-cbbf3700-05c3-11eb-9942-6a0677fe6d28.jpg)
![resulting_transaction](https://user-images.githubusercontent.com/24813122/95000754-ccf06400-05c3-11eb-8e8b-cfacef4f2c3a.jpg)

**Comment by JC5** [comment]
Well thanks for reporting it five minutes after I released 5.4.3. Kidding, I'll check it out! 🙈

**Comment by JC5** [comment]
I just tried it locally and I can't reproduce it. The demo site should be working fine as well.

**Comment by xpfgsyb** [comment]
Thank you for looking into it. The demo instance does work again, yes. Yesterday evening I had the problem that the text completion in the text boxes didn't work and then got an error when I tried to save.

Uhm, even if it's no general problem, do you have any tips how I can fix or debug this for my instance? I thought I start with a look into the database and created a new transaction, but I'm still looking for where the link between the transaction and tag is saved. I only found the field tag_count in transaction_journals, but that counter is still 0 after a successful edit of the transaction, so I guess that's not the correct place to look for.


```
MariaDB [firefly]> select * from transactions where id=25164;
+-------+---------------------+---------------------+------------+------------+------------+------------------------+-------------+-------------------------+----------------+----------------+---------------------+------------+
| id    | created_at          | updated_at          | deleted_at | reconciled | account_id | transaction_journal_id | description | transaction_currency_id | amount         | foreign_amount | foreign_currency_id | identifier |
+-------+---------------------+---------------------+------------+------------+------------+------------------------+-------------+-------------------------+----------------+----------------+---------------------+------------+
| 25164 | 2020-10-04 09:38:13 | 2020-10-04 09:38:13 | NULL       |          0 |         76 |                  12582 | NULL        |                       1 | 5.000000000000 |           NULL |                NULL |          0 |
+-------+---------------------+---------------------+------------+------------+------------+------------------------+-------------+-------------------------+----------------+----------------+---------------------+------------+

MariaDB [firefly]> select * from transaction_journals where id=12582;
+-------+---------------------+---------------------+------------+---------+---------------------+----------------------+---------+-------------------------+-------------+---------------------+---------------+-----------+--------------+-------+-----------+-----------+-----------+
| id    | created_at          | updated_at          | deleted_at | user_id | transaction_type_id | transaction_group_id | bill_id | transaction_currency_id | description | date                | interest_date | book_date | process_date | order | tag_count | encrypted | completed |
+-------+---------------------+---------------------+------------+---------+---------------------+----------------------+---------+-------------------------+-------------+---------------------+---------------+-----------+--------------+-------+-----------+-----------+-----------+
| 12582 | 2020-10-04 09:38:13 | 2020-10-04 09:38:13 | NULL       |       1 |                   1 |                12459 |    NULL |                       1 | test        | 2020-10-04 00:00:00 | NULL          | NULL      | NULL         |     0 |         0 |         1 |         1 |
+-------+---------------------+---------------------+------------+---------+---------------------+----------------------+---------+-------------------------+-------------+---------------------+---------------+-----------+--------------+-------+-----------+-----------+-----------+
```

After the edit:
```
MariaDB [firefly]> select * from transactions where id=25164;
+-------+---------------------+---------------------+------------+------------+------------+------------------------+-------------+-------------------------+----------------+----------------+---------------------+------------+
| id    | created_at          | updated_at          | deleted_at | reconciled | account_id | transaction_journal_id | description | transaction_currency_id | amount         | foreign_amount | foreign_currency_id | identifier |
+-------+---------------------+---------------------+------------+------------+------------+------------------------+-------------+-------------------------+----------------+----------------+---------------------+------------+
| 25164 | 2020-10-04 09:38:13 | 2020-10-04 09:46:30 | NULL       |          0 |         76 |                  12582 | NULL        |                       1 | 5.000000000000 |           NULL |                NULL |          0 |
+-------+---------------------+---------------------+------------+------------+------------+------------------------+-------------+-------------------------+----------------+----------------+---------------------+------------+

MariaDB [firefly]> select * from transaction_journals where id=12582;
+-------+---------------------+---------------------+------------+---------+---------------------+----------------------+---------+-------------------------+-------------+---------------------+---------------+-----------+--------------+-------+-----------+-----------+-----------+
| id    | created_at          | updated_at          | deleted_at | user_id | transaction_type_id | transaction_group_id | bill_id | transaction_currency_id | description | date                | interest_date | book_date | process_date | order | tag_count | encrypted | completed |
+-------+---------------------+---------------------+------------+---------+---------------------+----------------------+---------+-------------------------+-------------+---------------------+---------------+-----------+--------------+-------+-----------+-----------+-----------+
| 12582 | 2020-10-04 09:38:13 | 2020-10-04 09:38:13 | NULL       |       1 |                   1 |                12459 |    NULL |                       1 | test        | 2020-10-04 00:00:00 | NULL          | NULL      | NULL         |     0 |         0 |         1 |         1 |
+-------+---------------------+---------------------+------------+---------+---------------------+----------------------+---------+-------------------------+-------------+---------------------+---------------+-----------+--------------+-------+-----------+-----------+-----------+
```

**Comment by JC5** [comment]
The field `tag_count` is no longer used. Future version of Firefly III will probably drop it. 

Not really sure what's going on. Are you on the develop branch by any chance? Make sure you pull the latest changes.

What you can do to see what the issue could be is use the browser developer console to see what is submitted to the API. Are tags a part of the POST to Firefly III?

**Comment by xpfgsyb** [comment]
No, I use only stables.
Yes, tags are part of the data sent to Firefly III:
```
{"transactions":[{"type":"withdrawal","date":"2020-10-04","amount":"3","description":"test","source_id":2,"source_name":"Bargeld","destination_id":76,"destination_name":"Billa","category_name":"Lebensmittel","interest_date":"","book_date":"","process_date":"","due_date":"","payment_date":"","invoice_date":"","internal_reference":"","notes":"","tags":["Fixkosten"]}]}
```

The tags are also in the debug log (see yesterdays log upload https://github.com/firefly-iii/firefly-iii/files/5322258/debug_log.txt), so they are not only in the request, but also received by Firefly III.

If I assume that the API writes the log line above, then the problem must be somewhere between "API received the data successfully" and "MySQL writes the data".
Does the demo server also run MySQL? If so, then we can reduce the problem to somewhere between "API sends SQL query" and "MySQL writes data". As the other parts of the transaction are written successfully it can't be a general fault of my MariaDB installation. Has the SQL query maybe changed since 5.3 and does now contain something that MariaDB 10.3.23 does not understand? Is the MySQL version on the demo server newer?

**Comment by JC5** [comment]
Alright. Is the tag deleted, by any chance? In the "tags" table, does it have a date for the `deleted_at` field?

The demo also runs MySQL. Nothing really changed since 5.3 to 5.4 but I can add some debug info, so we know what happens to the tags.

**Comment by xpfgsyb** [comment]
That would be great :)
No, deleted_at is NULL for the used tag(s).

**Comment by JC5** [comment]
Crap. It would have recreated the tag but who knows what it could have been. I'll see what I can add :)

**Comment by JC5** [comment]
Especially "now in storeTags()" is important because it'll tell you if the tags survived.

```
[2020-10-04 16:53:45] local.DEBUG: Now in storeTags() ["abc","testB"] 
[2020-10-04 16:53:45] local.DEBUG: Start of loop.  
[2020-10-04 16:53:45] local.DEBUG: Now at tag "abc"  
[2020-10-04 16:53:45] local.DEBUG: Now in TagFactory::findOrCreate("abc")  
[2020-10-04 16:53:45] local.DEBUG: Tag exists (#3), return it.  
[2020-10-04 16:53:45] local.DEBUG: Now at tag "testB"  
[2020-10-04 16:53:45] local.DEBUG: Now in TagFactory::findOrCreate("testB")  
[2020-10-04 16:53:45] local.DEBUG: Created new tag #5 ("testB")  
[2020-10-04 16:53:45] local.DEBUG: End of loop.  
[2020-10-04 16:53:45] local.DEBUG: Total nr. of tags: 2 ["abc","testB"] 
[2020-10-04 16:53:45] local.DEBUG: Done!  
```

Code is live in develop branch or the next version.

**Comment by xpfgsyb** [comment]
Thank you! During debugging I found the root cause in the debug log. The tag survived, but was removed by a disabled rule. Now you can reproduce it on the demo system :)

1. Create a rule like this:
![test_rule](https://user-images.githubusercontent.com/24813122/95021966-73943d80-0674-11eb-8530-0e9faca77651.jpg)

2. Disable the rule
3. Create a transaction with any tag

The disabled rule will remove all tags, even if the trigger tag is not part of the transaction.
I simply deleted the rule in my instance and the problem is gone. However, it seems that there is some type of a rule bug in 5.4.x.

**Comment by JC5** [comment]
Yep, that's the bug. #3900
