### ISSUE TITLE
Error 500 when renaming a group

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#3898]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:

When I tried to rename I group in the rules section I get this error when updating:

```
Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Method FireflyIII\Http\Requests\RuleGroupFormRequest::nlString does not exist.
```

Same issue when trying to rename a group from the groups section but with a different message:
```
Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Method FireflyIII\Http\Requests\ObjectGroupFormRequest::string does not exist.
```

**Steps to reproduce**
Rename an existing group in the rules or groups sections or create a new one then rename it.

**Extra info**
Running docker on my Synology NAS.

**Bonus points**

- I searched and nobody reported this bug before
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for letting me know. Sloppy programming on my side, apologies for this bug. Should be fixed in the next release! :+1:

**Comment by MacPaille** [comment]
Haha no harm done :) At least it did not break anything
