### ISSUE TITLE
error when trying to get access to container fireflyiiidb under docker windows 10

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#3899]
I am running Firefly III version 5.3.3.

**Description**

I receive the following error message when I want to access the following container: fireflyiiidb (under the command terminal of windows 10)

command: docker exec -it --user root 7b0aa1aa2201 bash

gives error: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \bash": executable file not found in $PATH": unknown

That is why I dare not take a backup of that image.

Access to the fireflyiii container succeeds without error(s)

Logging in on fireflyiii itself works normally and can see all my data.

**Extra info**
 

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
The fireflyiidb container doesn't contain the "bash" program. Bash is the actual program that creates a shell.

What you can try instead of `bash` is `sh`. I haven't seen a container without it.

**Comment by JC5** [comment]
So:

```
command: docker exec -it --user root 7b0aa1aa2201 sh
```

**Comment by bartmaniac** [comment]
That works! Thanks
