### ISSUE TITLE
Inactive rules still applied

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#3900]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:

I did some test on my own instance and then played a bit on the demo website. It seems even if you deactivate a rule it is still applied even if it should not.

**Steps to reproduce**
Create a rule with specific valued.
Clone it and place the clone after the original.
Change the value of the cloned rule and mark it inactive.
Create a transaction matching that rule and check the result

**Bonus points**
- I have added a screenshot from the demo website
![bug-inactive-rules](https://user-images.githubusercontent.com/31923233/95014119-02896180-0645-11eb-8b2d-2865b5879677.png)

- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Indeed, sorry about that. Should be fixed in the new release!
