### ISSUE TITLE
Rules not executed in order

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#3901]
I am running Firefly III version 5.4.3.

**Description**
While playing a log with the rules to auto populate a lot of values when using csv-importer I ended up finding the inactive rule bug but I also have another problem.

One of my current rule to set the category from the destination account name (using a mix of name contains, name starts with and name is) is not working. After a lot of testing it appears if I clone my rule and do not touch it (keep both original and the clone active) the rule is correctly applied. If I delete the clone and create again a transaction then it is not applied.

I did that 4 times in a row and same behavior each time. So it seems the cloned rule has something that is working with the new rules engine that the original one doesn't...

How can I provide you enough information to debut these rules? Looking into a database dump maybe?

**Comment by JC5** [comment]
Wow that's a creative issue, not gonna lie. Especially since the clone process is supposed to be exact, and the rules aren't really upgraded between versions; it's only how they're handled.

Let's see a DB dump for both. Hover over each rule (bad and good) to get their ID and execute the folllowing queries.

```sql
SELECT * from rules where id IN (1,2);
select * from rule_triggers where rule_id IN (1,2);
select * from rule_actions where rule_id IN (1,2);
```

Send it to me over email for privacy's sake an don't forget to mention which rule is supposed to work, and which one isn't. Much oblidged!

**Comment by MacPaille** [comment]
So I exported the 3 SQL statement and compared, everything is the same (except normal fields like IDs and created/updated date/times).

I noted in the commands output the é character is not showed at all (I have expense account names with é). Not sure if it's related to the locales used in my bash terminal in my docker or something else. Synology docker interface is really unstable and crashes after a few minutes.

I know the fix would be to simply clone all my rules and delete the previous ones but would be better to find the bug if there is one :)

**Comment by MacPaille** [comment]
OK I used MySQL Workbench and the é char appears so that's fine :)

**Comment by JC5** [comment]
Thanks for sending over the details. I have no clue why the rule behaves differently. I can;t reproduce it locally I'm afraid.

Try clearing your cache just in case by browsing to `/flush`. Who knows? :D

**Comment by MacPaille** [comment]
Clearing the cache does not help... If I don't have any other way to provide you more info I'll clone all my rules and delete the originals to make sure everything should work :)

Or do you think I can provide you anything else?

BTW: thanks a lot for the feature to run all the rules of a group! I had missed the trigger of a rule and modified all the transactions of a month :) Lucky for me I could easily re-apply all my rules

**Comment by JC5** [comment]
I have no idea what the cause is. Keep me posted of other weird quircks, it may lead to the answer.

Glad to hear it helps! :D

**Comment by MacPaille** [comment]
No problem. Cloned all the rules it seems to work better even if now I have 3 rules that have an issue (was already the same before the clone). I'll open a new ticket :)

**Comment by MacPaille** [comment]
I opened again as I think I found the explanation. While reading the complete debug log I see the parsing of the rules is done in numerical order of the rule IDs.

As we can use groups and put them in a specific order, also the rules inside each group you can select the order, I was under the impression that the parsing of these rules would be done in the order I choose from top to bottom.

So now I understand why cloning my rule was fixing the issue as its ID pushed it to the end of the list.

To be able to do what I wanted I needed one of the rules I put at the top to change the expense account to the correct value regarding the description, then only the category could be set by another rule...

So is it intended this sorting of rules is only cosmetic? Is it written somwhere?

**Comment by MacPaille** [comment]
I can confirm this is the issue. I imported 2 transactions having to use the principle I explained. Before doing it I cloned the rule of one of the 2. That one had its category set correctly.

**Comment by JC5** [comment]
Nicely spotted.I hadn't realized. The rules should be executed in the order you see on screen. I'll pick it up!

**Comment by MacPaille** [comment]
Glad I could help :) I was about to create another one when I realized this was the clue for this one!

**Comment by Prandur** [comment]
Maybe it would work better to split this into 2 screens. One like it is now with the separate Groups to have a nice overview and being able to separate rules into groups (if you have many of them) and a second one to order them for execution with another column representing the group number. 
The pro would be that you would still be able to organize them by lets say categories (one rule group for category y one for x and so on) but still being able to say that rule 34 of category "food" which is the 3rd rule group is supposed to be evaluated before rule 15 from category "entertainment" which is the 2nd rule group.
Con would definitely be that it adds extra complexity from the usage and the application point of view, but also more freedom to organize.

**Comment by MacPaille** [comment]
For me the current view i fine as you can move around the rules inside each group and move the groups up and down. So the order it already present in some way as it remembers it.
So the rule engine should use the same ordering technique to prepare the rules to be run.

Adding another screen will make things much more complex for people to use. Better to KISS
