### ISSUE TITLE
Rule values for target account id not accepted

### ISSUE THREAD

**Issue by Prandur** [firefly-iii/firefly-iii#3902]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:
Trying to enter a target account id results in finding the correct transactions when using the corresponding button, but the value isn't valid to be saved. Account number 30 in this case is the "land lord" on the demo site and has transactions to it which will be found.

**Steps to reproduce**
* Enter a Number in the destination account id field.

![image](https://user-images.githubusercontent.com/12172861/95015579-fb1a8600-064d-11eb-8201-dc5a75303761.png)

**Bonus points**

- ✅ I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- ✅ I have added a screenshot.
- ✅ I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by Prandur** [comment]
One additional question. What would be the correct value to enter if trying to convert a transaction to a transfer? There has been a ticket, where it's said to leave it empty, but that doesn't work apparently.
Screenshot is from demo.

![image](https://user-images.githubusercontent.com/12172861/95015767-1afe7980-064f-11eb-907c-9a82d9ef476b.png)

**Comment by JC5** [comment]
Thanks, that's a bug. Will be fixed in the next release.

In regards to your second question. As per [the documentation](https://docs.firefly-iii.org/advanced-concepts/rules#converting-to-another-transaction-type), what you must fill in is the name of an existing asset account. This applies specifically when converting to a transfer.

**Comment by Prandur** [comment]
Thank you for the rapid response.

**Comment by JC5** [comment]
Let's leave it open so other people see it as well.

**Comment by Prandur** [comment]
You're right sorry.
