### ISSUE TITLE
Executing rules manually fails

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#3903]
I am running Firefly III version 5.4.3.

**Description**
All my rules are working but 3 which end up with a message like

```
Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

[d]Not a recognised date format: "202"
```

The 2 other rules fail with almost the same message except the value is 20 instead of 202

```
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

[d]Not a recognised date format: "20"
```

**Extra info**
Docker running on Synology

**Bonus points**

See attached HTML file containing the exception in the container logs. I removed all the other parts which are not relevant.
Docker log export on Synology is done in the inverted chronological order, so start reading at the bottom of the file ;)
[rule-exception-logs.txt](https://github.com/firefly-iii/firefly-iii/files/5323585/rule-exception-logs.txt)

**Comment by JC5** [comment]
What rule trigger and what value exactly?

**Comment by MacPaille** [comment]
I ran 2 rules in debug mode, one working and the other one not. Please find attached the logs.
[rule-working.txt](https://github.com/firefly-iii/firefly-iii/files/5324179/rule-working.txt)
[rule-not-working.txt](https://github.com/firefly-iii/firefly-iii/files/5324180/rule-not-working.txt)

From what I can see it's something related to the date of the search that got messed in this part:
```
2020-10-04 19:17:09	stdout	[2020-10-04 21:17:09] local.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"[d]Not a recognised date format: \"2020-1\"","time":"Sun, 04 Oct 2020 21:17:09 +0200","file":"\/var\/www\/html\/app\/Support\/ParseDateString.php","line":97,"code":0,"version":"5.4.3","url":"https:\/\/firefly.goset.be\/rules\/execute\/178","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/85.0.4183.121 Safari\/537.36","json":true}  
2020-10-04 19:17:09	stdout	[2020-10-04 21:17:09] local.DEBUG: "date_before" is not an alias.  
2020-10-04 19:17:09	stdout	[2020-10-04 21:17:09] local.DEBUG: updateCollector(date_before, 2020-1)  
2020-10-04 19:17:09	stdout	[2020-10-04 21:17:09] local.DEBUG: Now handle Gdbots\QueryParser\Node\Field  
2020-10-04 19:17:09	stdout	[2020-10-04 21:17:09] local.DEBUG: Set "date_after" using collector with value "2020-10-04" (2020-10-04 - 2020-10-04)  
2020-10-04 19:17:09	stdout	[2020-10-04 21:17:09] local.DEBUG: "date_after" is not an alias.  
2020-10-04 19:17:09	stdout	[2020-10-04 21:17:09] local.DEBUG: updateCollector(date_after, 2020-10-04)  
2020-10-04 19:17:09	stdout	[2020-10-04 21:17:09] local.DEBUG: Now handle Gdbots\QueryParser\Node\Field  
```

For the working rules these updateCollector on the date do not appear...

I made sure to run the query on a date (today) which I don't have any transaction yet.

**Comment by JC5** [comment]
Thanks. What's the value you have for the "date before" trigger? Is it "2020-1"?

**Comment by MacPaille** [comment]
I had entered yesterday's date for both start and end date in the form. I also tried to select manually inside the calendar view to see if something was missing but no.
You can see at the start of the log the date is selected correctly as 2020-20-04

And for the working rule this updateCollector part does not appear for the start and end dates. Which is strange...

**Comment by JC5** [comment]
I'll pick it up as a bug and see what I can find.

**Comment by JC5** [comment]
All I can do for now is add some debugging, which I just did. I can't find where the value is changed.

**Comment by MacPaille** [comment]
OK I just found the bug after a bit more testing... The issue is coming from the selection of the account names. I use the same names for expense accounts and for revenue accounts. For example using the CSV importer some records don't have a name so the record has created "(no name)" value (in both expenses and revenues).

When I create the rule and I search destination account "(no name)" it shows me 2 values. If I select the wrong one (like the revenue where it's a withdrawal) it will result in the error I found here...

No clue why it's modifying the date field but it does 😄 

I don't know if that would be possible but maybe adding the account type title like you do on the CSV importer would solve the issue that we know which account to select... But as this field is automatically populated while we type it may be super difficult to do.

**Comment by JC5** [comment]
The autocomplete has some options but this is hopeful. Could you send me a few screenshots of what your rule looks like?

**Comment by MacPaille** [comment]
Here is the rule. I was talking about the destination account where I have 2 occurrences of (no name)

![image](https://user-images.githubusercontent.com/31923233/95946799-9994ad00-0ded-11eb-9eed-5a05fb2baeed.png)

**Comment by JC5** [comment]
Alright I did some checking. It doesn't matter which one you select, because the name is stored, not the ID. The list could be made unique to make it more user friendly but it doesn't matter.

In rule-working.txt, the rule trigger finds one account with name "(no name)". This makes sense because it will only search in destination accounts, and the revenue account "(no name)" can't be a destination. So it's already filtered out. You can see this in rule-not-working.txt as well.

```
local.DEBUG: Left with 1, set as setDestinationAccounts().  
local.DEBUG: Found 1 accounts, will filter.  
local.DEBUG: searchAccount((no name), 4, 2)  
```

However the date_before and date_after filters are added by the page to manually execute rules. Altough they're added correctly, they seem to get corrupted halfway. Not sure yet where.

```
local.DEBUG: "date_before" is not an alias.  
local.DEBUG: updateCollector(date_before, 2020-1)  
```

```
local.DEBUG: "date_after" is not an alias.  
local.DEBUG: updateCollector(date_after, 2020-10-04)  
```

The search continues..

**Comment by JC5** [comment]
Found the issue. Search string can't be longer than 255 chars. Underlying library breaks. Stay tuned.

**Comment by JC5** [comment]
Added a routine to submit queries to the engine in parts. See also

https://github.com/gdbots/query-parser-php/issues/19

**Comment by MacPaille** [comment]
Ho cool glad you were able to spot it! Seeing the issue looks it was a difficult one.

Thanks for the fix!
