### ISSUE TITLE
IBAN numbers wrongly mapped in the bunq importer

### ISSUE THREAD

**Issue by oswdr** [firefly-iii/firefly-iii#3904]
**Bug description**
I am running fireflyiii/bunq-importer:release-2.0.2.

During imports I am receiving the following error:
> Unknown combination: expense and asset in file /var/www/html/app/Services/Sync/GenerateTransactions.php:318

After research, I suspect this to happen because of the mapping of the IBAN in the [GenerateTransactions.php#L73-L101](https://github.com/firefly-iii/bunq-importer/blob/main/app/Services/Sync/GenerateTransactions.php#L73-L101) file. If an IBAN is in the system twice (both expense account and revenue account) one of both gets overriden in the collectTargetAccounts method. 

P.S. mapping the transactions by hand did not solve the problem for me, but I am not sure yet if that is an user error :-). The import log does not really state which transaction threw this error so that makes it harder to debug.

**Steps to reproduce**
1. Have a expense and revenue account with the same IBAN
2. Import and auto map a transaction. Either as revenue or expense -- depending on the order of accounts I suppose.

**Extra info**
Debug information generated at 2020-10-04 18:27:36 Europe/Amsterdam for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | ff114e95-b8f9-4d55-9cb8-7c81d3672e94 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2019-11-26 00:00:00 |
| User ID | 4 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 |

**Comment by JC5** [comment]
Thanks for letting me know. All I can do is add some more debug info. The importer should switch expense/asset around to make a valid combination but doesn't do so, for some reason.

**Comment by oswdr** [comment]
Thanks! Just cloned the repo...will let you know if I found any solution.

**Comment by JC5** [comment]
Pushed some debug info. :+1:

**Comment by JC5** [comment]
I pushed some debug info to the bunq importer, in the develop branch. I can't really solve this without your help. Bunq no longer offers API keys to free accounts and their prices are pretty steep.

**Comment by oswdr** [comment]
Thanks. I runned the program locally and somehow this did not reproduce the same importing errors. I'm running the importer in docker and somehow restarting the docker container on the server made the import run successfully at least once. Does this make any sense?

**Comment by JC5** [comment]
Not really no 😅. But glad it works that’s the point 😁
