### ISSUE TITLE
select update channel

### ISSUE THREAD

**Issue by nloshka** [firefly-iii/firefly-iii#3905]
Upgraded php to 7.4 old upgrade script does not work
How to choose a channel and update it?
For earlier grateful for the possible help provided

git pull
Your configuration specifies to merge with the ref 'master'
from the remote, but no such ref was fetched.

**Comment by JC5** [comment]
The master branch was renamed to "main". 

git checkout main

**Comment by nloshka** [comment]
Debug information generated at 2020-10-04 23:01:58 Europe/Amsterdam for Firefly III version **5.2.3**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.3 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.4.11 |
| Display errors | Off |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2018-12-08 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, xmlreader, apcu, igbinary, imagick, memcache, msgpack, zip, memcached, Zend OPcache |

**Comment by nloshka** [comment]
# git checkout main
error: Your local changes to the following files would be overwritten by checkout:
	app/Support/Steam.php
Please, commit your changes or stash them before you can switch branches.
Aborting

**Comment by JC5** [comment]
Since you set this up yourself, I'm going to assume you know how to checkout individual files.

**Comment by nloshka** [comment]
I don't quite understand which file you need to check?
I have not configured anything separately

**Comment by JC5** [comment]
Run "git checkout app/Support/Steam.php" and try again.

**Comment by JC5** [comment]
Then run

php artisan cache:clear
php artisan migrate --seed
php artisan firefly-iii:upgrade-database
php artisan passport:install
php artisan cache:clear

**Comment by nloshka** [comment]
# git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> main

**Comment by nloshka** [comment]
So in the end, how to properly update?

**Comment by nloshka** [comment]
# git remote -v
origin	https://github.com/firefly-iii/firefly-iii.git (fetch)
origin	https://github.com/firefly-iii/firefly-iii.git (push)

**Comment by nloshka** [comment]
# cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/firefly-iii/firefly-iii.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master

**Comment by nloshka** [comment]
Now executing firefly:instructions update
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for updating to Firefly III, v5.4.3!                               |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
# git branch --set-upstream-to=origin/main

# git pull
# php artisan cache:clear
# php artisan migrate --seed
# php artisan firefly-iii:upgrade-database
# php artisan passport:install
# php artisan cache:clear
