### ISSUE TITLE
error when trying to make backup

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#3907]
I am running Firefly III version 5.3.3

**Description**
I tried to make a backup of my data before upgrading to 5.4.X. I copied the commandline from the help page 
C:\Users\herba\Documents>docker run --rm -v "firefly_iii_db:/tmp" -v "$HOME/backups/firefly:/backup" ubuntu tar -czvf /backup/firefly_db.tar /tmp

This gave me: 
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
d72e567cc804: Pull complete
0f3630e5ff08: Pull complete
b6a83d81d1f4: Pull complete
Digest: sha256:bc2f7250f69267c9c6b66d7b6a81a54d3878bb85f1ebb5f951c896d13e6ba537
Status: Downloaded newer image for ubuntu:latest
docker: Error response from daemon: create $HOME/backups/firefly: "$HOME/backups/firefly" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Extra info**
Windows 10 build 19041
Docker Desktop community 2.3.0.4

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by niklas2810** [comment]
You can simply choose your own backup destination. As you can see in your command line output, the HOME variable does not seem to exist.

I think that the help page is mostly targeted to provide support for Linux-based systems, therefore I'm not quite sure whether this command works in the same way on Windows. You might have to change some paths on the host machine setup in order to do that.

Are you using docker compose? If that's the case, you can simply copy the folders on your host machine (export/upload folder from Firefly III + Database data). Obviously, you have to have a setup with local folders instead of docker volumes for this to work.

**Comment by JC5** [comment]
If you run a linux command on Windows you need to adapt it to be windows compatible:


> docker run --rm -v "firefly_iii_db:/tmp" -v "**$HOME/backups/firefly**:/backup" ubuntu tar -czvf /backup/firefly_db.tar /tmp

Should be something like:

`c:\backup` 

Or whatever you want.

**Comment by bartmaniac** [comment]
ok, so I did this command: 
C:\Users\herba>docker run --rm -v "firefly_iii_db:/tmp" -v "c:\Users\herba\:/backup" ubuntu tar -czvf /backup/firefly_db.tar /tmp
It created a tar file named firefly_db.tar in directory C:\Users\herba but this file is only 1kB, so I don't think all of my history is in there

**Comment by bartmaniac** [comment]
> You can simply choose your own backup destination. As you can see in your command line output, the HOME variable does not seem to exist.
> 
> I think that the help page is mostly targeted to provide support for Linux-based systems, therefore I'm not quite sure whether this command works in the same way on Windows. You might have to change some paths on the host machine setup in order to do that.
> 
> Are you using docker compose? If that's the case, you can simply copy the folders on your host machine (export/upload folder from Firefly III + Database data). Obviously, you have to have a setup with local folders instead of docker volumes for this to work.

Yes, I'm using docker compose in a windows 10 terminal. Problem is I can't seem to find the export/upload folder from Firefly III + Database data. Even with the show hidden files. I have a docker folder under ProgramData but here I only find 1 subfolder cli-plugins.

**Comment by JC5** [comment]
I assume you created `/backup/firefly_db.tar` using a previous command? That's a file that wouldn't just magically appear.

**Comment by bartmaniac** [comment]
the tar files was created after doing docker run --rm -v "firefly_iii_db:/tmp" -v "c:\Users\herba:/backup" ubuntu tar -czvf /backup/firefly_db.tar /tmp

**Comment by JC5** [comment]
All I can think of is that the firefly_iii_db volume is in use by the database. Maybe stop the DB before you run the command?

**Comment by bartmaniac** [comment]
Ok I tried it (stop the DB before running the command. It still creates this 1kB firefly_db.tar file in c:\users\herba\
It also puts out this kind of error

tar: Removing leading `/' from member names
/tmp/

**Comment by JC5** [comment]
Mmmm. That shouldn't really matter.

But I just realised. You're mapping your DB volume to a new image, only to zip it and send it back through another volume. Why not cut out the middle man?

Run the following command:

```
docker volume ls
```

In the list you should have a volume called `firefly_iii_db`. Or similar.

Then run:

```
docker volume inspect firefly_iii_db
```

Output should be something like this:

```
[
    {
        "CreatedAt": "2020-10-01T18:20:58Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "issue-3882",
            "com.docker.compose.version": "1.27.4",
            "com.docker.compose.volume": "firefly_iii_db"
        },
        "Mountpoint": "/var/lib/docker/volumes/issue-3882_firefly_iii_db/_data",
        "Name": "issue-3882_firefly_iii_db",
        "Options": null,
        "Scope": "local"
    }
]
```

All you need to do is go to the folder mentioned in Mountpoint and zip it somewhere safe.

**Comment by bartmaniac** [comment]
Soory, but I have no docker folder in var/lib??

**docker volume inspect firefly_iii_db** gives following

[
    {
        "CreatedAt": "2020-10-09T12:44:39Z",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/firefly_iii_db/_data",
        "Name": "firefly_iii_db",
        "Options": null,
        "Scope": "local"
    }
]

Why is it I don't have these 3 com.docker.compose lines? I have used (I thnik so) the docker compose way to set it up.

I go into the fireflyiiidb container (root access) and this is whet I get in var/lib

/var/lib # ls -al
total 28
drwxr-xr-x    1 root     root          4096 Jul 16 15:21 .
drwxr-xr-x    1 root     root          4096 May 29 14:20 ..
drwxr-xr-x    2 root     root          4096 May 29 14:20 apk
drwxr-xr-x    2 root     root          4096 May 29 14:20 misc
drwxr-sr-x    5 mysql    mysql         4096 Oct  9 12:54 mysql
drwxr-xr-x    2 root     root          4096 May 29 14:20 udhcpd

I hope something is not terribly wrong

**Comment by JC5** [comment]
[/var/lib/mysql](https://github.com/firefly-iii/docker/blob/main/docker-compose.yml#L21) is the directory you need so that looks good.

Check out the following dirs on your computer. You have Windows, right?

<img width="827" alt="Screenshot 2020-10-13 at 20 12 22" src="https://user-images.githubusercontent.com/5889984/95899174-b09cb600-0d7f-11eb-9509-35db2bdc1d3b.png">

**Comment by bartmaniac** [comment]
Yes I have Windows10
Ok I went into this ProgramData folder and there is just one folder inside named cli-plugins. Nothing else.


![image](https://user-images.githubusercontent.com/44246750/95925761-edd26980-0dba-11eb-9d73-f61fa56065fa.png)

**Comment by JC5** [comment]
Mmm, thanks. What tool is this?

The thing is, if you can find that folder on your own system, you're good. But I'm out of ideas.

**Comment by bartmaniac** [comment]
The screenshot is from the programm docker community edition for windows. I think 

Docker Desktop for Windows is Docker designed to run on Windows 10. It is a native Windows application that provides an easy-to-use development environment for building, shipping, and running dockerized apps. Docker Desktop for Windows uses Windows-native Hyper-V virtualization and networking and is the fastest and most reliable way to develop Docker apps on Windows. Docker Desktop for Windows supports running both Linux and Windows Docker containers.
