### ISSUE TITLE
"Foreign amount" is not visible for transfers between different currencies

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#3909]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:

**Steps to reproduce**
1. [New Transfer](https://demo.firefly-iii.org/transactions/create/transfer)
2. Source account: Any EUR
3. Destination account: Any GBP or USD

**Actual**
"Foreign amount" is not visible

**Expected**
"Foreign amount" is visible

JFYI, I believe a similar issue happened a while ago.

**Comment by JC5** [comment]
Thanks, I'll check it out!

**Comment by JC5** [comment]
Yes yes

**Comment by JC5** [comment]
Fixed in the next release. :+1:

**Comment by halilim** [comment]
Thanks!
