### ISSUE TITLE
spectre-importer import additional field

### ISSUE THREAD

**Issue by in2digital** [firefly-iii/firefly-iii#3910]
I am running Firefly III version 5.4.3 with spectre-importer 1.0.5

In the Salt Edge import my bank maps the transaction type in the description field, and then puts the actual transaction description in the Extra > Additional field. Example: https://imgur.com/a/Y6nIdur

The problem is Firefly-iii isn't able to display actual transaction description once imported as I'm not able to import the  Extra > Additional field.

As a workaround is it possible to also import the Additional field, and also map it to the description field in Firefly-iii?

**Comment by JC5** [comment]
Mmm, shouldn't be difficult. I'll see what I can do. I'm not sure what other organisations put into this field.

As an alternative, please also contact Salt Edge and see if they can move the description.

**Comment by JC5** [comment]
Will be part of the new Spectre release.

**Comment by JC5** [comment]
New release is out.
