### ISSUE TITLE
Possibly incorrect storage path in docker compose

### ISSUE THREAD

**Issue by slonoed** [firefly-iii/firefly-iii#3911]
**Bug description**
I am running Firefly III version 5.4.3 in Docker (by using compose), and my problem is:

This compose file https://github.com/firefly-iii/docker/blob/main/docker-compose.yml#L7
Has a line to bind volume
```
- firefly_iii_upload:/var/www/firefly-iii/storage/upload
```
However, when I run I see that directory `/var/www/html/` is used instead of `/var/www/firefly-iii` to store all data.

I see that environment variable `FIREFLY_III_PATH=/var/www/html` is defined here
https://github.com/firefly-iii/docker-base-image/blob/1ee1841055c23fa256aea73655c9263750910124/Dockerfile#L10

Is it a bug?

**Steps to reproduce**
`docker-compose up`
Attach to container and inspect file system

**Comment by JC5** [comment]
Thx! I updated the file.
