### ISSUE TITLE
Error creating personal access token

### ISSUE THREAD

**Issue by planck0** [firefly-iii/firefly-iii#3914]
I am running Firefly III version 5.4.3.

**Description**
I upgraded to 5.4.3 from 5.2. I want to use the external csv-importer. But when I try to create a personal access code in firefly, I get :

    Whoops! Something went wrong!

    Something went wrong. Please try again. 

I see nothing strange in the logs.

**Extra info**

Note that after an upgrade from Ubuntu 18.04 to 20.04, I had to reinstall php. I did a clean install, including all dependencies as mentioned in the docs.

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by JC5** [comment]
I'll need a bit more to know what's happening. Could you share the table from the /debug page?

**Comment by planck0** [comment]
Debug information generated at 2020-10-07 22:50:00 Europe/Amsterdam for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | a09e64a7-1f66-4917-ab7d-f7d6d1af3a6e |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2019-03-15 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0 |

And:

```
Truncated from this point <----|[2020-10-07 22:49:21] local.ERROR: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
"  

```

**Comment by JC5** [comment]
Alright since you're not using Docker, try the following on the command line

```
php artisan passport:install
php artisan firefly-iii:restore-oauth-keys
```

**Comment by planck0** [comment]
I get:

 % php artisan passport:install
Encryption keys already exist. Use the --force option to overwrite them.
Personal access client created successfully.
Client ID: 40
Client secret: <secret>
Password grant client created successfully.
Client ID: 41
Client secret: <secret>

 % php artisan firefly-iii:restore-oauth-keys
OAuth keys are OK

Should I use --force?

**Comment by JC5** [comment]
Alright. Force wouldn't make a difference.

Make sure you turn on [debug mode](https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode) and hopefully the logs will be more clear if you try again to generate a token.

Also, browse to /flush just in case to clear your cache.

**Comment by planck0** [comment]
I did a flush and turned on debug mode. But it doesn't seem to produce much:

Debug information generated at 2020-10-08 21:17:10 Europe/Amsterdam for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | a09e64a7-1f66-4917-ab7d-f7d6d1af3a6e |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2019-03-15 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0 |

```
Truncated from this point <----|[2020-10-08 21:16:49] local.DEBUG: ProfileController::__construct(). Login provider is "eloquent", authentication guard is "web"  
[2020-10-08 21:16:50] local.DEBUG: Will set previous URL to https://mydomain.com/firefly/profile  
[2020-10-08 21:16:50] local.DEBUG: Will NOT set previous URL to https://mydomain.com/firefly/v1/jscript/variables?ext=.js&v=5.4.3  
[2020-10-08 21:17:10] local.DEBUG: Trying to set en_US.utf8  
[2020-10-08 21:17:10] local.DEBUG: Trying to set en_US.UTF-8  

```

**Comment by JC5** [comment]
Mmm, I'm afraid I'm out of ideas here. The DB is also up to date. Sorry, you'll have to do tinkering.

**Comment by planck0** [comment]
No problem, thanks for your time! I have put back a backup of my VPS with version 5.1.0 and there token generation works fine. I tried a re-upgrade and again had the same issue. So it's in a change since then. 

I have no PHP and little Javascript experience, so I'll see what I can do to debug.

**Comment by JC5** [comment]
Did you upgrade the database as well? All I can think of is a table error somewhere.

```php artisan migrate```

**Comment by planck0** [comment]
I did that. Tried it again with no results.

However, I now notice in the debugger some 404s on the Profile page on oauth urls. E.g. when I push Create in the 'Create Token' dialog there is a http POST request to https://mydomain.com/oauth/personal-access-tokens, which failts with a 404. The URL should be https://mydomain.com/firefly/oauth/personal-access-tokens which does exist.

**Comment by JC5** [comment]
Ah, you're hosting in a subdirectory. I'm afraid I'm out of my depth then.

**Comment by planck0** [comment]
I found how to fix it. In firefly-iii/resources/assets/js/components/passport/PersonalAccessTokens.vue there are the following lines:
```
      axios.get('/oauth/personal-access-tokens')
      axios.get('/oauth/scopes')
      axios.post('/oauth/personal-access-tokens', this.form)
      axios.delete('/oauth/personal-access-tokens/' + token.id)
```

You fix it by changing that to:

```
      axios.get('./oauth/personal-access-tokens')
      axios.get('./oauth/scopes')
      axios.post('./oauth/personal-access-tokens', this.form)
      axios.delete('./oauth/personal-access-tokens/' + token.id)
```

Do you want me to do a pull request? I have never done so, so I will have to figure out how that works first so that might take some time.

**Comment by JC5** [comment]
Nice find! I can pick it up, it'll allow me to test it on root domains too. It will be implemented in the next release :+1:

**Comment by bittiez** [comment]
Just a heads up, I am having this exact same issue, however the fix [above ](https://github.com/firefly-iii/firefly-iii/issues/3914#issuecomment-706710037) did not work for me. As far as it being installed in a sub directory I actually failed multiple attempts of installing this on a self hosted server, and docker, so I ended up going with an easy softaculous install which defaulted to /public/ sub dir, I wish it gave me the option to not do that, oh well.

**Comment by my2817** [comment]
ll.

I

>  As far as it being installed in a sub directory

so I chang DocumentRoot to firefly-iii/public, it works for me!

**Comment by planck0** [comment]
> 
> 
> Just a heads up, I am having this exact same issue, however the fix [above ](https://github.com/firefly-iii/firefly-iii/issues/3914#issuecomment-706710037) did not work for me. As far as it being installed in a sub directory I actually failed multiple attempts of installing this on a self hosted server, and docker, so I ended up going with an easy softaculous install which defaulted to /public/ sub dir, I wish it gave me the option to not do that, oh well.

Note that to make it work in a local installation you'll also have to edit public/v1/js/profile.js and change all occurrences of "/oauth by "./oauth. I guessed that that file is generated from the other source files (but maybe wrong). I also found some occurrences of the missing dot in some other files in resources/assets/js/components/passport/ and vendor/laravel/passport/resources/js/components/PersonalAccessTokens.vue  I searched for occurrences of oauth and personal-access-tokens.

I do not completely understand the workings of the vue and laravel frameworks yet to get how all these things work together and create the application I see in the browser. But I got it working for me. Hopefully that helps.

**Comment by my2817** [comment]
> esources/assets/js/components/passport/ and vendor/laravel/passport/resources/js/components/PersonalAccessTokens.vue

Thanks a lot, it works for me

**Comment by JC5** [comment]
Thanks guys, should be part of the next release :+1:

**Comment by Compizfox** [comment]
I think I'm still suffering from this issue...

I just installed Firefly III and I'm running it in a subdirectory (i.e. my Apache config is `Alias /firefly /var/www/firefly-iii/public`).

I'm trying to create a personal access token for the Spectre importer. However, when I click on "Create new token", and then fill in a name and click "Create", nothing happens. If I click "Close", I can then see a empty entry (it has no name, but I can delete it).

My browser's JS console shows the following error:

```
Uncaught (in promise) TypeError: can't access property "data", t.response is undefined
    store https://example.org/firefly/v1/js/profile.js?v=5.5.10:1
    promise callback*store https://example.org/firefly/v1/js/profile.js?v=5.5.10:1
    VueJS 53
    <anonymous> https://example.org/firefly/v1/js/profile.js?v=5.5.10:1
    <anonymous> https://example.org/firefly/v1/js/profile.js?v=5.5.10:1
    <anonymous> https://example.org/firefly/v1/js/profile.js?v=5.5.10:1
profile.js:1:171571
```

**Comment by JC5** [comment]
Feel free to open a new issue. It should take less than a second to generate a token.
