### ISSUE TITLE
OAUTH / personal access token not useable with ldap?

### ISSUE THREAD

**Issue by mic05** [firefly-iii/firefly-iii#3915]
I am running Firefly III version 5.4.3.

**Description**
On profile page, menu item OAuth is missing, therefore no personal access token can be generated. Has this something to do with ldap enabled? How can I use the api with an user from ldap?
![2020-10-07 19_08_28-](https://user-images.githubusercontent.com/72517528/95364018-91f67500-08d0-11eb-8fc0-fec0a4cc8638.png)

Thanks in advance!

**Extra info**
Debug information generated at 2020-10-07 19:06:57 Europe/Berlin for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 7fb347e5-02c1-482b-9c2d-0f3f0804e51c |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | ldap  |
| Trusted proxies (.env) | 10.11.11.10 |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2019-11-04 00:00:00 |
| User ID | 2 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 |

**Comment by JC5** [comment]
At the moment, you can't. I'll pick it up for another release.

**Comment by rikmendes** [comment]
+1 for getting this to work for ldap users :+1:
