### ISSUE TITLE
Context based limit for autofill results

### ISSUE THREAD

**Issue by Prandur** [firefly-iii/firefly-iii#3917]
**Description**
It would be nice if Firefly III would limit the results when clicking in the source/target account box. As of right now, the dropdown when creating a withdrawal or incoming transactions shows all possible accounts. 
It would be a nice, but small, quality of life improvement if this would be limited to the relevant accounts as it would enhance the flow of adding manual transactions.

**Solution**
For a new withdrawal transaction limit the results for the source account to the asset accounts, for deposit transactions limit the results for the target account to the asset accounts and for transfers limit both of them to the asset accounts.
Maybe, with advanced logic, just limit them as described when clicking in the field for easy access but providing the whole autofill results when starting to type in the respective field.

**Comment by JC5** [comment]
The form is the same for each type of transaction. The auto-complete will adapt however once you start selecting accounts. If you select an asset account as a source, the destination account field will already be limited. Likewise, if you select a destination account first, the source account field will also be limited.

**Comment by Prandur** [comment]
Yeah the thought was to eliminate to type into one field. 
Apparently, when you click for an withdrawel into the source account field, it's sorted [0-9] before [aZ] but starting with the expense Accounts. It would already achieve my suggestion to start with the asset accounts. 
If done so, and naming the asset account like (01 Giro, 02 Credit etc) you could just click on the asset account eliminating the need to type to access your asset accounts. This would make the application also more comfortable to use on mobile as typing there is less user friendly as on pc.

**Comment by JC5** [comment]
Good idea, I'll see what I can do for the next release.
