### ISSUE TITLE
Blank website (Getting PHP fatal error.)

### ISSUE THREAD

**Issue by kwm1800** [firefly-iii/firefly-iii#3919]
I have been using Firefly, using docker installation. Recently I realized I have not updated the installation for about 3 months so I decided to update. Now it seems something has gone wrong. All I see is blank page. From the log.

> 
> [2020-10-08 17:21:33] local.ERROR: The /var/www/html/bootstrap/cache directory must be present and writable. {"exception":"[object] (Exception(code: 0): The /var/www/html/bootstrap/cache directory must be present and writable. at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:177),
> 
> [2020-10-08 17:21:33] local.ERROR: Target class [view] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [view] does not exist. at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:811)
> 
> 
> [Thu Oct 08 17:21:33.385361 2020] [php7:error] [pid 98] [client 192.168.2.2:35138] PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:809\nStack trace:\n#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(809): ReflectionClass->__construct()\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1284): Illuminate\\Foundation\\Application->make()\n#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\\C in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 811

I have no clue, it should be writable since everything is within docker container. Any ideas?

**Comment by JC5** [comment]
Not sure. Depends a bit on the upgrade process. What if you drop the container + image and restart?

**Comment by kwm1800** [comment]
Yeah, I decided to just completely wipe out everything except database (of course). It seems portainer really does not completely clean the old settings despite I cleaned up env. I recreated the container via console and it is finally opening up.

Thank you for the quick help.
