### ISSUE TITLE
Account Balance being modified by past transactions unnecessarily 

### ISSUE THREAD

**Issue by ddouglas** [firefly-iii/firefly-iii#3921]
I am running Firefly III version 5.4.3.

**Description**
I maybe misunderstanding how this all works, but if I have an account start date of today for example and I create a transaction in the past, should the account balance be affected? It would make sense if the transaction was AFTER the start date. Based on the terminology in the UI, I'm assuming that the starting balance and start date is the balance that the account currently is. If a transaction is in the past or before that start date, then the balance has already been affected by that transaction, so it is being modified a second time in Firefly III

I want to keep track of those transactions but everytime i create them, I have to update the balance back to what it currently is according to my bank.

**Extra info**
`/debug`
Debug information generated at 2020-10-11 01:38:39 Europe/Amsterdam for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | a941ad8b-05b5-46f1-8d01-082efb15e7e3 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | America/New_York |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2020-10-08 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 |

**Bonus points**

- I have added a screenshot.
 - https://i.imgur.com/oui9ekN.png
- I was able to replicate it on the demo site https://demo.firefly-iii.org/
 - https://demo.firefly-iii.org/accounts/show/44

**Comment by JC5** [comment]
The opening balance is a transaction like any other transaction. If you set the opening balance of an account to 500,- on January 1st, the balance on December 31st was 0,-.

If you set a start balance make sure it's before any transactions you enter.

**Comment by ddouglas** [comment]
This makes it difficult to input historical transactions as one would have to do the math outside of firefly to know what the balance was on December 15th (using your example) if I wanted to input 20 transactions between then and Jan 1. Wouldn't it be better to subtract the transaction amount from the initial transaction instead of assuming that the account balance prior to the initial transaction was 0?

**Comment by JC5** [comment]
No, it wouldn't. Your example is different though. If you know your balance on December 15th and then add transactions between December 15th and January 1st nothing changes. This works fine. The balance you see on January 1st should match your expectations.

If you set your opening balance on December 15th to be 500,- and then start adding transactions on December 12th, your balance on December 15th will be different.

**Comment by ddouglas** [comment]
I'm sorry but this is confusing and I don't understand the logic. I tell
the system that on Jan 1 my balance is 500. Shouldn't the system assume
that all transactions that occur before Jan 1, whether they be present or
not, resulted in the account being 500 on Jan 1?

**Comment by JC5** [comment]
No, the opening balance isn't a calibration point like that. It's meant to use as the first transaction, the start of your administration.

**Comment by ddouglas** [comment]
Okay, that made it click. Firefly is treating this like it is literally a
new account, like at a bank, whereas there is no transaction history.

I'm curious if there is a particular reason you chose for it to function
like this or is this just how it is done in the accounting world?

**Comment by JC5** [comment]
Both. It's a function of double-entry bookkeeping. 

Any money in the system has to come from somewhere. Every transaction is money going from A to B. Even the opening balance is a transaction. A hidden account is created where the money comes from (or goes to).

This hidden account is kind of special and really just says "this is the start". The hidden account is a kind of magical account where money is created out of thin air.

**Comment by ddouglas** [comment]
Thanks for the answering the questions. Closing this issue now. Awesome program by the way.
