### ISSUE TITLE
Reverse proxy (caddy) problems with subpath

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3922]
I'm trying to setup firefly behind caddy.

My TRUSTED_PROXIES is already set to ** following the documentation. I also read #1632 but didn't really help (and is for caddy v1 while I'm on v2).

1. It is working when I map / directly to firefly:

```
route /* {
      reverse_proxy fireflyiii:8080
  }
``` 

https://caddy/ redirects to https://caddy/login, and everything works as expected.

2. If I try to add a subpath, I get a strange behaviour

```
  route /fireflyiii/* {
      reverse_proxy fireflyiii:8080
  }
```
https://caddy/fireflyiii/ redirects to http://caddy:8080/fireflyiii , losing https

3. Stripping the uri prefix is not useful

```
  route /fireflyiii/* {
      uri strip_prefix /fireflyiii
      reverse_proxy fireflyiii:8080
  }
```
https://caddy/fireflyiii/ redirects to https://caddy/login which is not mapped to fireflyiii.

[Laravel's community](https://laracasts.com/discuss/channels/servers/laravel-as-subdirectory-through-proxy) suggests setting `forceRootUrl` in the routes but I don't even know it it is the same Laravel version...

PS. APP_URL is set accordingly, to https://caddy/fireflyiii/ but afaik it should not be used while browsing.

Thanks

**Comment by psychowood** [comment]
Just for clarification: my question is not directly related to caddy. 

What I want to know is if it is possibile to run firefly on a subpath instead of the domain root, when using a reverse proxy.

**Comment by cimbi** [comment]
Same problem but with nginx reverse proxy. Any help appreciated.
