### ISSUE TITLE
Request to Expand Documentation on Liabilities

### ISSUE THREAD

**Issue by 3lpsy** [firefly-iii/firefly-iii#3923]
**Description**
This is pretty low priority but I'm confused on how to track debt/loans and how it affects the net worth value. It appears that money that you owe has to be entered as negative value when creating a debt? Otherwise, it gets added to your networth (unless negative). Is this right? I may not be thinking about this right. So you take out a loan, spend it on school, and then four years later you owe the bank 10k. How do you track this? As a -10K debt?

**Solution**
The documentation is already fantastic (thanks!). My main request would be to expand the Liabilities section.

**Comment by JC5** [comment]
Will do. The idea is that you enter the amount negative yes, and you work your way back to zero.

**Comment by JC5** [comment]
I pushed new text, thanks for suggesting an update!

https://docs.firefly-iii.org/concepts/accounts
