### ISSUE TITLE
How to backup self-hosted data?

### ISSUE THREAD

**Issue by 5833tP2** [firefly-iii/firefly-iii#3924]
I am running Firefly III version 5.4.2 self-hosted on a Pi 3.

**Description**
I want to backup my firefly data using [these instructions](https://docs.firefly-iii.org/advanced-installation/backup). My problem is that both `/var/www/firefly-iii/storage/` and `/var/www/firefly-iii/storage/database/` are empty!

Firefly is working fine and contains three years worth of transactions. Where is this stored if not in the above location?

**Comment by JC5** [comment]
It depends on how you set up your database. So, how did you set up your database? Share the output of the `/debug` page please.

**Comment by 5833tP2** [comment]
```
Debug information generated at 2020-10-11 11:13:54 Europe/London for Firefly III version **5.4.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.2 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 03a394ed-52e7-424e-881e-50d9cde66340 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2018-10-03 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0 |

```

**Comment by JC5** [comment]
... and what does that tell you?

**Comment by 5833tP2** [comment]
Actually, it tells me nothing. I do not know what I am looking for. Firefly has been a struggle for me to install and configure. My problem with backups is just the latest challenge.

**Comment by JC5** [comment]
So you have a MySQL database, which implies there's a MySQL container. Or maybe, a MariaDB container. Same thing really.

Something like this is what you need, I think. 

https://medium.com/@siriphonnot/backup-and-restore-a-mysql-database-from-a-running-docker-mysql-container-6c932907e21f

**Comment by 5833tP2** [comment]
Thanks for the link. I'm not running docker so know nothing about containers.

If it's a matter of backing up a MySQL database, then I can find out how to do that. I was confused by the firefly backup documentation which implies that files should be in `/storage` and `/storage/database`. My directories were empty and that's the reason I posted this question.

I'll do a DB backup and make sure I copy `.env` too.

Thanks for your reply and for pointing me in the right direction.

**Comment by gigino-ctrl** [comment]
@JC5 his "/debug" says "Using docker? | false" so @5833tP2, if I'm not wrong (I do it, and i restore it correctly without errors), you need to backup mysql database for most of the data (look at mysql dump) and in case restore it. "/storage" it's only for uploaded data/files if I remember well, I don't use them so for me the directory is empty.
