### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by kaunt** [firefly-iii/firefly-iii#3935]
**Bug description**
There is a typo in on-line documentation

**Steps to reproduce**
go to https://docs.firefly-iii.org/advanced-installation/locales#missing-translations-or-format-instructiosn
![2020_10_12_15_05_09_Locales_Firefly_III_Documentation](https://user-images.githubusercontent.com/37385302/95750050-dd2bd180-0c9c-11eb-9f27-bfc5da44c03f.jpg)
 and search for "instructions"

**Comment by JC5** [comment]
Nice, fixed!
