### ISSUE TITLE
Table sorting by clicking on column headers

### ISSUE THREAD

**Issue by bittiez** [firefly-iii/firefly-iii#3936]
**Description**
It would be really helpful to be able to sort any table by clicking on the column headers to sort asc or desc.

**Solution**
Add table sorting

**Comment by JC5** [comment]
What problem did you ran into that made you think of this solution?

**Comment by bittiez** [comment]
> What problem did you ran into that made you think of this solution?

I was on the bills page, and I wanted to see which bill is next due to come out, but as it is now I have to read each one to find the next bill if that makes sense

**Comment by JC5** [comment]
It does yes. I was asking specifically because many pages have these sortable tables already, and this is the easiest way to find out where you ran into this issue. Thanks!

**Comment by bittiez** [comment]
Oh okay, I didn’t realize some of them were already sortable, nice!

**Comment by JC5** [comment]
New layout will pick this up :+1:
