### ISSUE TITLE
Feature suggestion: Webhooks

### ISSUE THREAD

**Issue by sgofferj** [firefly-iii/firefly-iii#3937]
**Description**
FF3 currently has an API which an external application can call.
I'm suggesting to implement webhooks which are called **by** FF3 in an external application.

**Solution**
What I'm suggesting is that the user/admin can configure a number of webhooks for certain events. If such an event happens, FF3 would call a configured URI and POST a JSON object. The advantage of that is that the external application would always have the latest data without having to poll every x minutes.
Some things that come to mind straight away:
New transaction created - POST transaction data
Account balance changed - POST account data
(Regular) invoice paid - POST invoice data and list of invoices with status (paid/unpaid)
Failed login - POST login data used and source IP

**What are alternatives?**
Only alternative is to poll via the API.

**Comment by sgofferj** [comment]
Use cases:
For me personally, it's easy integration in my home automation. Always have current account balance on the dashboard without having to give the whole family my FF3 password. Having a notification if something weird happens, ...
Home automation is getting really popular nowadays.
Other possibilities would be e.g. displays (makers love building displays for everything...).

The main point is that webhooks are more current (as in providing the latest information right when it happens) and more efficient than polling the API. If you have multiple systems polling the API every 5 minutes, it's quickly summing up...
I personally also find it easier to wire up something that listens for a JSON POST.
And last but not least, it should be more secure because FF3 is initiating the communication so it's harder for the external app to do something bad to FF3.

**Comment by JC5** [comment]
I'll see what I can do. Don't expect anything soon though. Not sure how to go about this. I like the idea but webhooks, even when self-configured, that post financial data outside of the system aren't things I'm going to add lightly.

**Comment by sgofferj** [comment]
Yeah, I get your point. But in theory, it's still kinda safer because with webhooks, I could lock FF3 into it's own little subnet where only e.g. my desktop computer gets in while I could still get data out to "insecure" nets.
I could think of a few things that would make webhooks more secure... First of all, force https. If the webhook URL isn't https, fail with error.
How to go about it... The easiest way might be through the rules?

And another very specific use case...: Put the current account balance on the smart mirror beside the front door - just as a reminder :rofl:

**Comment by JC5** [comment]
Will be available in the next release. Docs are up, feedback is welcome.

https://docs.firefly-iii.org/firefly-iii/pages-and-features/webhooks/

**Comment by emansih** [comment]
The URL(https://api-docs.firefly.org/#/webhooks) under Header `Create or edit webhooks using the API` leads to a 404 page.

**Comment by JC5** [comment]
https://fireflyiiiapidocs.z6.web.core.windows.net/?urls.primaryName=1.5.0#/webhooks

Until the code is released #:+1:

**Comment by JC5** [comment]
Fixed in the latest beta, I'm closing this for consistency's sake.
