### ISSUE TITLE
Log file permissions error

### ISSUE THREAD

**Issue by coldwar7** [firefly-iii/firefly-iii#3938]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:
Every morning, I have an error screen that says "The stream or file "<File name here>" could not be opened in append mode: failed to open stream: Permission denied."

The <File name here> is always a cron job log file such as /var/www/html/storage/logs/ff3-cli-2020-10-14.log

**Steps to reproduce**
Occurs every night. I believe it is related to the cron job.

**Extra info**
I run FF3 in a docker within unRAID. I have been calling my cron job using the User Scripts plugin for unRAID. The script is "docker exec -t Firefly-III /usr/local/bin/php /var/www/html/artisan firefly-iii:cron". This was working before when the artisan file was in the firefly-iii folder, but has had issues since it moved to the html folder.

Restarting the docker clears the error page and works again until the next night. This issue does not occur if I run my script manually. Only over night.
![2020-10-14 07_40_38-Firefly III 500 _(](https://user-images.githubusercontent.com/68624822/95985082-2477a680-0df2-11eb-857b-aa507a5ddd0f.png)

Debug information generated at 2020-10-14 07:47:45 America/New_York for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 97a2b338-f003-44a8-bb43-e9be6550f6c8 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2020-05-18 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0 |

**Comment by JC5** [comment]
This happens because this call is executed using root:

```
docker exec -t Firefly-III /usr/local/bin/php /var/www/html/artisan firefly-iii:cron
```

Subsequent tries to access log files are impossible because the root user claims access to the file.

Try the following command instead:

```
docker exec -t Firefly-III --user www-data /usr/local/bin/php /var/www/html/artisan firefly-iii:cron
```

**Comment by coldwar7** [comment]
Thank you for the help. I will put this in and see what result I have. This might be good to update on the documentation. Do you know why this would not have been a problem before the file moved to the html path?

**Comment by JC5** [comment]
I added it more extensively to the docs. This was already a problem before the move for some people, nothing much changed there.

**Comment by coldwar7** [comment]
So that solved the issue I was having before but it would seem that it created another issue as of Oct 22. I now get this error.

> OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"--user\": executable file not found in $PATH": unknown

**Comment by JC5** [comment]
What command do you use to run the Docker container?

**Comment by coldwar7** [comment]
I use unRAID. This is the command it uses. I put in place holders for security purposes.

>/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run --name='Firefly-III' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'DB_CONNECTION'='mysql' -e 'DB_HOST'='IP_ADDRESS' -e 'DB_PORT'='3306' -e 'DB_DATABASE'='fireflydb' -e 'DB_USERNAME'='DB_USER' -e 'DB_PASSWORD'='DB_PASSWORD' -e 'APP_KEY'='APP_KEY' -e 'TRUSTED_PROXIES'='**' -e 'MAIL_MAILER'='' -e 'MAIL_HOST'='' -e 'MAIL_PORT'='' -e 'MAIL_FROM'='' -e 'MAIL_USERNAME'='' -e 'MAIL_PASSWORD'='' -e 'MAIL_ENCRYPTION'='' -e 'APP_URL'='' -e 'SEND_ERROR_MESSAGE'='true' -p '5080:8080/tcp' -v '/mnt/user/Files/Firefly/Exports/':'/var/www/firefly-iii/storage/export ':'rw' -v '/mnt/user/Files/Firefly/Imports/':'/var/www/firefly-iii/storage/upload':'rw' 'jc5x/firefly-iii:latest'

**Comment by JC5** [comment]
Looks good, but make sure that you change /var/www/firefly-iii to /var/www/html

Delete the image you have right now to ensure a fresh copy, and try again.
