### ISSUE TITLE
FireflyIII 404 Not Found :(

### ISSUE THREAD

**Issue by sree324** [firefly-iii/firefly-iii#3939]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:

**Steps to reproduce**
Installed Firefly III on Ubuntu 18.4 with LAMP PHP 7.4 successfully vut when I try to access the site I get below error

FireflyIII 404 Not Found :(
404 — Firefly III cannot find this page.
The page you have requested does not exist. Please check that you have not entered the wrong URL. Did you make a typo perhaps?

If you were redirected to this page automatically, please accept my apologies. There is a mention of this error in your log files and I would be grateful if you sent me the error to me.

If you are sure this page should exist, please open a ticket on GitHub.

**Extra info**
Using Chrome to access the site, also do not see any errors in the Apache logs.

**Bonus points**

There are no errors in the Apache error log

Below are the log entries from access log
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /firefly-iii HTTP/1.1" 404 3753 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /v1/lib/fa/css/font-awesome.min.css?v= HTTP/1.1" 200 7391 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /v1/lib/adminlte/css/skins/skin-blue-light.min.css?v= HTTP/1.1" 200 1139 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/
537.36"
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /v1/lib/adminlte/css/AdminLTE.min.css?v= HTTP/1.1" 200 15341 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /v1/lib/bs/css/bootstrap.min.css?v= HTTP/1.1" 200 20083 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /v1/css/daterangepicker.css?v= HTTP/1.1" 200 2035 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /v1/css/gf-source.css HTTP/1.1" 200 766 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /v1/css/error.css?v= HTTP/1.1" 404 3753 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /v1/fonts/source-sans-pro-v13-greek_cyrillic-ext_vietnamese_greek-ext_latin-ext_cyrillic_latin-700.woff2 HTTP/1.1" 304 181 "http://192.168.1.206/v1/css/gf-source.css" "Mozilla/5.0 (Windo
ws NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET /v1/fonts/source-sans-pro-v13-greek_cyrillic-ext_vietnamese_greek-ext_latin-ext_cyrillic_latin-regular.woff2 HTTP/1.1" 304 181 "http://192.168.1.206/v1/css/gf-source.css" "Mozilla/5.0 (W
indows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
::1 - - [14/Oct/2020:06:59:01 -0500] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.29 (Ubuntu) (internal dummy connection)"
::1 - - [14/Oct/2020:06:59:02 -0500] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.29 (Ubuntu) (internal dummy connection)"
::1 - - [14/Oct/2020:06:59:03 -0500] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.29 (Ubuntu) (internal dummy connection)"
192.168.1.14 - - [14/Oct/2020:06:59:12 -0500] "GET /firefly-iii HTTP/1.1" 404 3748 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.1.14 - - [14/Oct/2020:06:59:12 -0500] "GET /v1/css/error.css?v= HTTP/1.1" 404 3747 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
It looks like your Apache isn't configured to the correct directory. Should be easy to fix.

**Comment by psychowood** [comment]
If you are getting the Firefly Error

<img width="410" alt="image" src="https://user-images.githubusercontent.com/115389/96259889-8553da00-0fbe-11eb-968e-e49d11144bad.png">

I suppose you are using a subpath:

> 192.168.1.14 - - [14/Oct/2020:06:58:54 -0500] "GET **/firefly-iii** HTTP/1.1" 404 3753 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

without stripping it in the forwarded request, and firefly looks for pages inside `/firefly-iii`

Afaik I noticed that firefly does not like being a subpath, this seems related to #3922 .

**Comment by sree324** [comment]
It is not a subpath, I have the firefly-iii folder under /var/www. Is it possible to get this error if we run composer as root?

**Comment by psychowood** [comment]
If it is not in a subpath then why are you doing a `GET /firefly-iii` and not a `GET /`

**Comment by planck0** [comment]
Default html folder for apache on Ubuntu 18.4 is /var/www/html not /var/www.

Probably better is to put this in your apache config, e.g. in /etc/apache2/sites-available/000-default.conf:

`Alias /firefly-iii "/var/www/firefly-iii/public/"`

Whichever config file you choose, make sure you put a symbolic link to it in /etc/apache2/sites-enabled/

Hope that helps.

**Comment by sree324** [comment]
@psychowood Thanks for your suggestion, it works now. I was using the path suggested in the doc.
