### ISSUE TITLE
Grand Theory documentation link in emails are broken

### ISSUE THREAD

**Issue by Ettemlevest** [firefly-iii/firefly-iii#3940]
**Bug description**
I am running Firefly III version 5.4.3 on Docker, and my problem is:

Just found that the link used in the below translation string is broken. I saw it is used in `registered-html.twig` template so this can be a problem for newly registered users.

`emails.php`
"If you haven't already, please read the <a style="color:#337ab7" href="https://docs.firefly-iii.org/about-firefly-iii/grand-theory">grand theory</a>."

**Steps to reproduce**
Getting a 404 error for the link: https://docs.firefly-iii.org/about-firefly-iii/grand-theory

**Comment by JC5** [comment]
Oh thanks, will fix!
