### ISSUE TITLE
Reduce Pie Chart Prominence and/or Usage

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3943]
As I use firefly-iii, I find that I see a lot of pie charts on various pages. I'm not totally against pie charts, however, I find that they more often than not are getting in the way of the data I am trying to access.

Pie charts are especially used in personal finance applications. Unfortunately, pie charts communicate information poorly. This is a well documented phenomena.

    https://www.geckoboard.com/blog/pie-charts/
    https://www.businessinsider.com/pie-charts-are-the-worst-2013-6
    https://scc.ms.unimelb.edu.au/resources-list/data-visualisation-and-exploration/no_pie-charts
    https://uxplanet.org/the-five-stages-of-grief-over-the-death-of-pie-charts-effb54894fee

There are some who defend pie charts. But mostly, I don't see the majority defending them out there.

    https://medium.com/@clmentviguier/the-hate-of-pie-charts-harms-good-data-visualization-cc7cfed243b6

Some places that I see pie charts in firefly-iii:

- Top of "All expenses" ledger
- revenue ledger
- expense account page

A couple examples of the way that charts (not just pie) get in the way of my firefly-iii experience:

1. I want to look at the ledger, but three pie charts consume half of the screen and I have to scroll down on each visit to page to get to the meat of the information I need to see.
2. Because pie charts are placed at the top of a page, the experience is especially bad on mobile. Viewing transactions requires scrolling several times before a ledger line can be viewed.

A simple change could be to move charts to the bottom of a page. A more advanced change could be to make a configuration option.

Personally, after using firefly-iii for a while, I now find that the pie charts in firefly-iii do not contribute to my experience in the app. If you would forgive me of taking liberty with an analogy-- they are in the same shape as an ad box on the web which does not help their utility. I find I am often scrolling past them.

I do like using the charts in the reporting pages.

I would be curious to see if others share my experience, and if folks have other ideas for improving the UI as well.

**Comment by JC5** [comment]
Yes. That page is due for an update. It's slow an doesn't give the right info. Pie charts seemed like a good idea at the time. I'll pick it up for the new layout, and mark this as an enhancement to remind myself.

**Comment by JC5** [comment]
It's on the roadmap. I'm closing this to reduce clutter.
