### ISSUE TITLE
Dashboard - Your Accounts - Graph

### ISSUE THREAD

**Issue by gigino-ctrl** [firefly-iii/firefly-iii#3944]
**Description**

Using the dashboard with 6 accounts I am noticing that I find it difficult to distinguish the accounts immediately.
It would be very useful to have a legend under the chart where the accounts are associated with the color without having to hover over them with mouse.
Another possibility could be to put a label on the chart but I think it would be more difficult to manage and I don't know if the library allows it.

**Comment by JC5** [comment]
I can only suggest you select a few less in your preferences.

**Comment by bastiiiii** [comment]
I´m in the same boot..
The legend in the top can be added by manipulation of the chart options in public/v1/js/ff/charts.js:
https://github.com/bastiiiii/firefly-iii/commit/6db45b8a5e56b4b2db1b35c2519381ab4b6138c3#diff-103496867710c261753fab401c1b877c362142b6f8a735fc1bb4146fb53717b2
