### ISSUE TITLE
firefly-csv - Docker - Import error  "There are no commands defined in the "csv" namespace."

### ISSUE THREAD

**Issue by bartekd123** [firefly-iii/firefly-iii#3945]
**Bug description**
I am running Firefly III version 5.4.3 (Docker), Firefly III CSV Import Tool is version 2.2.1  and my problem is:

When running the below command, I receive the error "There are no commands defined in the "csv" namespace."
 - when using the same config file and the same CSV file, it works using the UI
 - I tried both the import and the autoimport and both produce a similar error
**Steps to reproduce**
1.) Create the CSV file in upload directory and config file in configuration directory
2.) Run the below command
docker exec -it fireflycsv php artisan csv:import 01-tangerineMC.csv 01-tangerineMC.json
3.) Error is shown

**Stack Trace:**
```
# docker exec -it fireflycsv php artisan csv:import 01-tangerineMC.csv 01-tangerineMC.json
[2020-10-16 01:45:02] production.ERROR: There are no commands defined in the "csv" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"csv\" namespace. at /var/www/html/vendor/symfony/console/Application.php:581)
[stacktrace]
#0 /var/www/html/vendor/symfony/console/Application.php(632): Symfony\\Component\\Console\\Application->findNamespace()
#1 /var/www/html/vendor/symfony/console/Application.php(230): Symfony\\Component\\Console\\Application->find()
#2 /var/www/html/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#5 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#6 {main}
"} 
           
  There are no commands defined in the "csv" namespace. 
``` 
                                                         

Example CSV File:
```
Transaction date,Transaction,Name,Memo,Amount
10/7/2020,CREDIT,PAYMENT - THANK YOU,,9.99

```

Config File:
```
{
    "date": "m\/d\/Y",
    "default_account": 5,
    "delimiter": "comma",
    "headers": true,
    "ignore_duplicate_lines": true,
    "ignore_duplicate_transactions": true,
    "rules": true,
    "skip_form": true,
    "add_import_tag": true,
    "specifics": [],
    "roles": [
        "date_transaction",
        "_ignore",
        "description",
        "note",
        "amount"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "version": 2
}
```

**Comment by JC5** [comment]
https://github.com/firefly-iii/csv-importer/releases/tag/2.2.0

**Comment by bartekd123** [comment]
Sorry forgot to include that Firefly III CSV Import Tool is version 2.2.1. Ill update the first post

**Comment by JC5** [comment]
From that link:

- ⚠️ The import commands now start with `importer:` instead of `csv:`

**Comment by bartekd123** [comment]
Ah, you are right. Thanks, I was going off the documentation on the site, and didn't realize it changed. 

Now (not sure if it can be covered under this issue), but I get the error "The importer can't import: CSV file "01-tangerineMC.csv" does not exist or could not be read."

Any ideas? I have tried having the config in the configurations directory and the csv in either the upload directory or configurations directory, and it still doesn't see it.

**Comment by JC5** [comment]
I just realized the documentation still mentioned the old command, sorry about that. I'll have to dive in your issue later today, stay tuned!

**Comment by bartekd123** [comment]
Awesome, thanks JC5!
If it helps, this is where I saw it:
https://firefly-iii.gitbook.io/firefly-iii-csv-importer/importing-data/command_line

**Comment by JC5** [comment]
For the error, make sure you submit the entire path just in case. So `importer:importer /full/path/to/file`

**Comment by bartekd123** [comment]
Great, thanks for your help. That worked for me. For anyone else reading this, this was the command I used
docker exec -it fireflycsv php artisan importer:import /var/www/html/storage/upload/01.CSV /configurations/01.json

It doesn't matter for me, since the command above works, but the auto-import doesn't work since the paths need to be specified. Gives the error "  scandir() expects parameter 1 to be a valid path, bool given "

But I am good, so can close the request. Thanks JC5 for your help again!
