### ISSUE TITLE
Add time to transaction dates (optional?)

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3946]
Hi,
I noticed that the transaction detail already shows the time too

![image](https://user-images.githubusercontent.com/115389/96024868-a39dc680-0e54-11eb-8327-725669553934.png)

Would you consider extending the date widgets to a datetime one, to allow inputing the time if needed?

**Comment by JC5** [comment]
I removed it for the time being because it felt crowded. The form is pretty crowded. I'll think of something.

**Comment by psychowood** [comment]
I was thinking it could be a useful since the data is already there, but probably is not something reeeally needed.

I agree with you about the form, that's why I was thinking about changing the widget instead of adding a new field.

[AdminLTE](https://adminlte.io/themes/AdminLTE/pages/forms/advanced.html) should have something, if you are aready using it:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/115389/96254861-4cb00280-0fb6-11eb-8942-5aef8d658231.png">

**Comment by JC5** [comment]
It's on the list for the new layout.
