### ISSUE TITLE
Better consistency for split transaction description

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3947]
**Description**
I have trouble establishing a naming convention for my split transactions, especially when it comes to splitting my share from people I advance money to. I do so to only consume my budget and assign categories on my share.
On the home page, the global description is repeated for each split transaction:
![image](https://user-images.githubusercontent.com/34862846/96239438-fd5ed780-0f9f-11eb-9095-94465ea062e0.png)

However when I look up for a split transaction when creating links, I only have the split description:
![image](https://user-images.githubusercontent.com/34862846/96239470-094a9980-0fa0-11eb-8430-e50b3539e388.png)
Searching for "Holidays" doesn't work. Needless to say that after a few months, searching for "Share" is tedious.

I used to repeat the global description in the individual split descriptions but that renders badly on the home page. It makes the global description an annoying mandatory field. 

**Solution**
Ideally I would like the global description to be displayed (and searchable) along with the split description. 

**What are alternatives?**
I could still populated the global description with a dummy value ("Split") and only use the split description:
![image](https://user-images.githubusercontent.com/34862846/96240449-35b2e580-0fa1-11eb-96e1-839d5733bbf3.png)

**Comment by sephrat** [comment]
Forgot to mention the link screen is not a lone wolf: the global description is not displayed either in /search when only one transaction fits the criteria.
Searching for "Timmy":
![image](https://user-images.githubusercontent.com/34862846/96243798-89273280-0fa5-11eb-8af2-82eb50d3ec7d.png)
Searching for "share":
![image](https://user-images.githubusercontent.com/34862846/96243824-904e4080-0fa5-11eb-8b66-4abd4c70c7df.png)

I don't use this feature that much but might be worth mentioning if you consider overhauling the behaviour.

**Comment by JC5** [comment]
Nice one. Shouldn't be difficult to do better. In fact, that search box could easily use the search function and everything.

**Comment by JC5** [comment]
I'm picking this up as part of the efforts for the new layout. Closing this one to clean up.
