### ISSUE TITLE
Allow user to pick a different transaction in the "link" popup

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3948]
**Description**
When linking a transaction to another transaction, it's sometimes hard to find *the* transaction you're looking for, mostly because you can only search by name. It's only once you pick the transaction that you can check the details through the URL (which you have to open in a new tab)
![image](https://user-images.githubusercontent.com/34862846/96241770-e8377800-0fa2-11eb-9b2a-dbb2c0d018c6.png)
If you made a mistake, you can only close the popup and search again (and select the appropriate link type again).

**Solution**
Be able to unpick the transaction and chose again.
![image](https://user-images.githubusercontent.com/34862846/96242088-5a0fc180-0fa3-11eb-9deb-a4d642b8e1ff.png)
Maybe it's an idea to keep the previous search terms as well.

**What are alternatives?**
Exit the popup and start again.

**Comment by JC5** [comment]
It needs an overhaul yes. A reminder :+1:

**Comment by JC5** [comment]
Will be part of the new layout and is on my list.
