### ISSUE TITLE
Associate Transfer with bills

### ISSUE THREAD

**Issue by filipe-silva** [firefly-iii/firefly-iii#3949]
Hi, so I have a bill for rent, and it so happens that the account that receives the rent is in my firefly, but as I was trying to link the bill there was no bill option!

I'm guessing it was by design, since an income and bill doesn't make sense but maybe for transfers it can be available on preferences?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3555

**Comment by filipe-silva** [comment]
Followed the breadcrumbs:
https://github.com/firefly-iii/firefly-iii/issues/3192#issuecomment-599881851
Makes sense to me, thanks!
