### ISSUE TITLE
can't import correctly the amountif if is splited in two parts.

### ISSUE THREAD

**Issue by tioannidis** [firefly-iii/firefly-iii#3951]
I am running Firefly III version v2.2.1.@Docker 

**Description**
My Bank(commerzbank) split the value in two parts in the csv file.
How I can import both Colums together in the amount Column?
example:
![csv](https://user-images.githubusercontent.com/1592909/96347969-bf4bdb80-10a5-11eb-9c68-1c3d9d669927.png)
![importer](https://user-images.githubusercontent.com/1592909/96348015-1baefb00-10a6-11eb-8084-00fc0e9dfcf7.png)

**Output*
![importer2](https://user-images.githubusercontent.com/1592909/96348106-83fddc80-10a6-11eb-9a41-a3abb8a2a046.png)

**In the firefly App**
![firefly](https://user-images.githubusercontent.com/1592909/96348112-8a8c5400-10a6-11eb-9fd7-d68e35dc881e.png)

yes- I have read the FAQ at https://bit.ly/FF3-FAQ
yes- I added a screenshot
no- I added log files 
no - I was able to replicate the issue on the demo site.

Best Regards,
Theo

**Comment by JC5** [comment]
Lol what the heck is wrong with your bank. No, you can’t import this. You have to merge the fields manually before you import this file.

**Comment by tioannidis** [comment]
it's a good question :-)
yes I have to live with it or change the bank...
thx for your answer.
