### ISSUE TITLE
Renaming Categories does not update categories on recurring transactions

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3953]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is: Renaming a category does not update the category on recurring transactions. When you load the recurring transactions page, it recreates the old category. If you rename a category it does update on transactions (obviously) and also on rules.

**Steps to reproduce**
1. Have a category that is associated with 1 or more recurring transactions.
2. Rename the category.
3. Notice that the previous category has been replaced with the renamed category.
4. Go to the Recurring Transactions page.
5. Go back to the Categories page.
6. Notice that the previous category has been recreated with no matching transactions and the renamed category is still present as well.
7. Go back to any matching recurring transaction and notice that the category is not renamed.

**Extra info**

Debug information generated at 2020-10-17 22:29:04 America/New_York for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 |

Possibly very relevant:
```
Truncated from this point <----|[2020-10-17 13:00:32] local.ERROR: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
"  
[2020-10-17 22:11:01] local.WARNING: GracefulNotFoundHandler cannot handle route with name "recurring.edit"  

```

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot. (not really screenshotable)
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nice find, I'll pick it up!
