### ISSUE TITLE
Upgraded to Latest Stable asking for 2FA

### ISSUE THREAD

**Issue by r8z0r1** [firefly-iii/firefly-iii#3956]
Hi, I have just upgraded to the latest stable release of FireFly-iii and I am being asked for 2FA, which I did not have configured previously. Please can you advise on how to disable this.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/faq/other#i-lost-my-2fa-token-generator-or-2fa-has-stopped-working

**Comment by r8z0r1** [comment]
Cheers James, I've managed to change the field to null in the DB which
restored access, I will now setup 2FA. Thanks for the rapid response as
usual.

**Comment by JC5** [comment]
No worries, happy to help. No clue why the field wasn't null after the upgrade though, sorry about that.

**Comment by r8z0r1** [comment]
Hi sorry James, since upgrading I am now getting this error when trying to
access one of my asset accounts, any thoughts?:

Whoops! An error occurred.

Unfortunately, this error was not recoverable :(. Firefly III broke. The
error is:

Argument 1 passed to
FireflyIII\Support\Twig\General::FireflyIII\Support\Twig\{closure}() must
be of the type string, null given, called in
/var/www/html/storage/framework/views/twig/b5/b5ef5638fbf6f70d1571b970262ba33341c1e1f9bb75aca14fdde1b704f6c6e8.php
on line 245

**Comment by JC5** [comment]
No clue. Next time you get that error, send me that file over email. I can use it to narrow down the problem.

**Comment by r8z0r1** [comment]
Thanks James, here is the file.

**Comment by JC5** [comment]
Sorry, I can’t see attachments when you reply to GitHub tickets. Please send it to james@firefly-iii.org
