### ISSUE TITLE
Transaction filtering and searching

### ISSUE THREAD

**Issue by jens108** [firefly-iii/firefly-iii#3966]
**Description**
Hi there! I'd like to be able to filter and search for specific transactions. Right now, when I use the search function nothing ever turns up. 
It would be great to be able to filter the transaction list by category, "uncategorized", and by receiver. Sorting functions would be great as well!

**Solution**
A small button at the top of all lists to add a filter, and clicking on table headers to sort by that column alphabetically.

**What are alternatives?**
The search function (not working for me) or clicking on the categories to go to that page, which will have a filtered list at the bottom. But that workflow can be improved!

**Additional context**
I just added about 500 expenses via Mt540 import and would like to categorize them etc., for that I am using rules (which are awesome!) but sorting functions would make the process a lot easier to find the transactions that are not caught by my rules.

Loving Firefly-III!

**Comment by sephrat** [comment]
> Right now, when I use the search function nothing ever turns up.

What is your query?
has_no_category:true works fine for me: https://demo.firefly-iii.org/search?search=has_no_category%3Atrue
https://docs.firefly-iii.org/concepts/search#transaction-properties
It's true though that you can't sort results on the search page.

**Comment by jens108** [comment]
> Right now, when I use the search function nothing ever turns up.
I am searching for "Luisa" to see all the payments I sent to her. There are 6 in the database, but the search results are zero.

has_no_category:true works!

**Comment by sephrat** [comment]
Have a look at that help page I linked in my previous post. You need to use something like destination_account_is:Luisa.

**Comment by sephrat** [comment]
So a query along the lines of the following should suit you:
`has_no_category:true destination_account_is:Luisa`

**Comment by jens108** [comment]
Cool, thanks! That cleared up searching for me. Still hoping for filtering and sorting of the tables 👍

**Comment by JC5** [comment]
Not in the near future I'm afraid, but I'm working on a new layout that should make it possible.
