### ISSUE TITLE
Recurring transactions, subscriptions, rent, overview

### ISSUE THREAD

**Issue by jens108** [firefly-iii/firefly-iii#3967]
**Description**
Hi there! Loving firefly-iii. I'd like to keep an overview of my recurring transactions (rent, Netflix, ...) and see how much I am spending on a regular basis. Note that this is not currently covered by the recurring transactions functionality because I don't want to automatically generate transactions from these (as I am importing my bank data, and that would result in doubles).

**Solution**
Adding a list of transactions that are recurring, and show some analysis for these (total recurring expenses, ...). These could also factor into the financial overviews for future months so I can plan ahead my cashflow.

**What are alternatives?**
Recurring transactions that are turned to inactive kind of replicate this in their list, but the list is not made for that and works differently.

**Additional context**
Seeing how subscriptions and interest affect future months would be awesome for cashflow planning. Plus I could evaluate if I really should go and get Disney+ or buy that new TV with monthly interest rates. Planning my monthly "burn rate".

My current excel list for this (I changed some numbers for privacy)
![image](https://user-images.githubusercontent.com/11771169/96435139-e91c1400-1205-11eb-8b8e-524c2d89cdd5.png)

Projected bank balance (red line = today)
![image](https://user-images.githubusercontent.com/11771169/96433816-94789900-1205-11eb-82f0-9c6fd035af86.png)

**Comment by sephrat** [comment]
Sounds a lot like https://docs.firefly-iii.org/advanced-concepts/bills
Have you given it a try?

**Comment by jens108** [comment]
True, that's it! Thank you!
