### ISSUE TITLE
Clearing the "group" field of a bill does not remove the group

### ISSUE THREAD

**Issue by jens108** [firefly-iii/firefly-iii#3968]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:
I created a lot of bills and tried grouping them, so I added a text into the "Group" field when editing a bill. Then I wanted to remove the group again, by clearing the text field. When I hit save, nothing changes.

**Steps to reproduce**
Create bill, add group
Save
Open bill, clear group
Save

**Comment by jens108** [comment]
Also: it would be cool to have a sum of all bills per month even when the are grouped. Right now I tried grouping them, and then it only shows the sum per group. I am mostly interested in the total sum of bills per month, which is why I am deleting the groups again.

**Comment by JC5** [comment]
Thanks for letting me know. I'll check it out and fix it.

**Comment by JC5** [comment]
Should be fixed, demo site has the relevant code already. Will be part of the next release. Thanks again!

**Comment by jens108** [comment]
Checked it out on the demo site, works great! Awesome!

**Comment by JC5** [comment]
No worries. Let's leave this one open until the release is out. In case other people run into the same issue.
