### ISSUE TITLE
Transactions: additional field for tax %

### ISSUE THREAD

**Issue by jens108** [firefly-iii/firefly-iii#3971]
**Description**
Hi there, loving firefly-iii! I noticed that there are optional fields for transactions etc that can be turned on/off. I was wondering why there isn't a field for tax %, as this would be a minor addition (one more optional field) but would be very interesting for some analysis, even for personal finances.

**Solution**
Add an optional field for tax % to transactions. This would suffice to calculate the VAT (or local equivalent) in combination with the transaction total

**What are alternatives?**
I could use one of the existing fields and just relabel it, but none of them have a float or integer value; they are dates or text fields.

**Additional context**
I am using firefly-iii for my small business (sorry!). My taxes are all done by a tax advisor, so firefly-iii is enough for me because I just need to keep an overview where the money goes, while the tax guy does the taxes separately. This field would allow me to program some external tools through the API that calculate some interesting stuff.

**Comment by JC5** [comment]
You could add the tax rate as tag maybe? It's not perfect but it should work well enough.
