### ISSUE TITLE
Question about Credit Card

### ISSUE THREAD

**Issue by Tatamethues** [firefly-iii/firefly-iii#3972]
First, thanks for the awesome project.
After I read some docs, I'm still confusing about it.
Supposing the CC has limit of 1000, What numbers should I put into opening balance and virtual balance? And each time I payback the money should create a transaction from other account to cc account?

**Comment by JC5** [comment]
I think the easiest way to do this would be as follows:

* Add a virtual balance of 1000. That way, when you're out of money, it's actually at zero.
* Create expenses as you usually would, from CreditCard > Store
* When you pay pack, create a transfer from AssetAccount > CreditCard

**Comment by Tatamethues** [comment]
In this way, the virtual balance goes to the account balance in report, so is there a way to find out how much assets do I have? Since if there are more credit cards, I need to calculate it by myself.
Also, is there a bug that numbers(balance, net worth) are not updated on time?

**Comment by JC5** [comment]
Yes. And no, in that case you shouldn't set a virtual balance. Just let it go from 0 to -1000. 

I'm not aware of any bug by that description, do you have more details?
