### ISSUE TITLE
Redirected to non-existing page after deleting attachment

### ISSUE THREAD

**Issue by jens108** [firefly-iii/firefly-iii#3973]
**Bug description**
Hi there, loving firefly-iii! I am running Firefly III version 5.4.3, and my problem is:

- after deleting an attachment from a transaction, I am redirected to the old attachment page which no longer exists, resulting in error 404
- the transaction list still shows the "attachment icon" before the transaction. (this might also be my fault because I am messing with the API, creating some attachments that have no files... but should those cause the icon to appear?)

**Comment by JC5** [comment]
Nice, found and fixed. :+1:
