### ISSUE TITLE
Inactive asset accounts are being displayed on the dashboard

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3974]
**Bug description**
I am running Firefly III version 5.4.3 (demo site) and my problem is:

I‘m not quite sure whether this is a bug or expected behaviour. To my mind its a little odd that inactive accounts are displayed on the graph as well as in the account list on the index page.

I‘d expect the aacount to be still displayable in the checkings account submenu, but not show up on the dashboard (as the account is most probably not in use anymore).

If the current behaviour is actually intended, please regard my issue as a feature request 😄 

**Steps to reproduce**

1. edit an asset account https://demo.firefly-iii.org/accounts/asset
2. go back to the dashboard -> it will show up as a graph + a recent booking overview will appear.

**Bonus points**

- I searched and nobody reported this bug before
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Yeah that's a good idea, fixed. :+1:

**Comment by niklas2810** [comment]
Thanks! I wasn't able to test this on the demo site yet, isn't it running the latest version from the dev branch? 😅

**Comment by JC5** [comment]
It should automatically pull every 24hrs :)

**Comment by niklas2810** [comment]
I've tried this again now, but it doesn't work yet, neither on the demo site nor on my private testing instance (latest `develop` docker image) 😅 Are you sure that the feature is working as expected?

**Comment by JC5** [comment]
Not really sure. The code is simple enough. I've added another check. It looks like the demo site caches the value, and demo user can't reset it.

**Comment by niklas2810** [comment]
Have you tested this on a private instance? At least for me, it still doesn't work 😅 I've made sure that I'm running the latest dev image + have deactivated the asset account.

**Comment by JC5** [comment]
No it doesn't, crap. Let's add some debug, and see why my perfect code doesn't work. Stay tuned.

**Comment by JC5** [comment]
It disappears in the DB and when you clear the cache. So the code isn't entirely terrible. Not sure what's happening on your end.

**Comment by niklas2810** [comment]
Huh, flushing the cache (`/flush `) did at least do _something_. The account is now gone at `/accounts/asset`. However, it still shows up on the dashboard (graph + account list with recent transactions). Is this how it's supposed to work?

**Comment by JC5** [comment]
No. It should be removed from both. There’s some debug code to confirm.

**Comment by niklas2810** [comment]
I couldn't find anything in the docker logs, what exactly do you mean? I'll be more than happy to provide you with some info from my instance.

**Comment by JC5** [comment]
For some reason, `Cache::forget()` is unreliable. I pushed some updates, I hope they work.

**Comment by niklas2810** [comment]
Thanks, I'll check it out once the docker image was updated! 😁

**Comment by niklas2810** [comment]
Alright, I've pulled the update, recreated all containers, flushed the cache and the account still appears on the dashboard (gone from `/accounts/asset`).

This might be irrelevant, but the graph always changes color when I switch the account from active to inactive (or the other way around). It's yellow in inactive mode and green when set to active. I guess that the color is generated based on some account configuration values?

In case you want logs or DB info to identify what's going on, please let me know.

The account order gets switched, too.

When Savings account is set to active:
![image](https://user-images.githubusercontent.com/30748216/97077415-ca41c700-15e3-11eb-8b6b-a853dbbf0c6f.jpeg)

Inactive:
![image](https://user-images.githubusercontent.com/30748216/97077440-f78e7500-15e3-11eb-96ef-9663bd931e99.jpeg)

**Comment by JC5** [comment]
Sorry, I'm out of ideas.

**Comment by niklas2810** [comment]
I just stumbled across something which might be relevant for this issue: When I set the account to inactive, I thought that the checkbox in Options > Preferences > Home Screen > `account name` would be automatically turned off.

However, I noticed that the checkbox for the corresponding account is still activated, even if I mark the account as inactive. When I turn the check off, the disabled account now obviously doesn't appear on the dashboard anymore. Are these two checks (inactive and custom preference) merged internally when generating the home screen layout/graph?

**Comment by JC5** [comment]
No it's a basic cache, but I haven't found out why Firefly III ignores it.
