### ISSUE TITLE
Make autocomplete API case-insensitive

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3976]
**Description**

Sometimes, I really like to use my mobile device to enter a new expense, e.g. when paying with cash and not my credit card. However, I often have a hard time when trying to enter a destination account (example: "ama" does not show a suggestion for "Amazon") because I forgot the upper case letter and therefore, autocomplete does not work.

**Solution**

Make the results case-insensitive, or put case-insensitive results at the end of the list.

**What are alternatives?**

Well, trying to remember to press the the shift key before I start typing (which I _always_ forget tbh 😅)

**Comment by JC5** [comment]
https://docs.firefly-iii.org/faq/other#auto-complete-is-case-sensitive

**Comment by niklas2810** [comment]
Oops, sorry about that :(

**Comment by JC5** [comment]
No worries, you can't know everything 😁
