### ISSUE TITLE
Cannot switch pages when searching for transactions

### ISSUE THREAD

**Issue by jens108** [firefly-iii/firefly-iii#3977]
**Bug description**
Hi there, loving firefly-iii! I am running Firefly III version 5.4.3, and my problem is:

- when I search for transactions (my current query is has_no_category:true), I cannot switch to another page. It always displays page 1. The url updates and has "&page=3" in it, but the list only displays page 1.

**Comment by JC5** [comment]
I can't seem to replicate this. The demo site seems to switch just fine. 

https://demo.firefly-iii.org/search?search=has_no_budget%3Atrue&page=2

Unfortunately the demo site doesn't have enough details to check `has_no_category`.

Does `has_no_budget` display the same behavior?

**Comment by jens108** [comment]
> Does has_no_budget display the same behavior?
Yes, I can't switch to other pages for that query as well. It works on the demo page. Weird! How could we go about finding the cause for this?

**Comment by JC5** [comment]
Is the search query empty when you use this URL format?

```
/search?page=2&search=has_no_budget%3Atrue
```

**Comment by jens108** [comment]
The URL seems to be okay (see below). Just the display is stuck on page 1. I tried looking at the docker logs, but nothing turns up. How else could I help find the cause for this?

> /search?search=has_no_budget%3Atrue&page=6

**Comment by JC5** [comment]
Not really sure. I was hoping it would be an issue with the ampersand. There have been cases where everything after the ? wasn't forwarded to PHP because of a bad Apache config. Otherwise it's difficult to debug I'm afraid. 

I'll play around with the page parameter, there might be something else going on.
