### ISSUE TITLE
Budget View No Longer Group By Period

### ISSUE THREAD

**Issue by dicksonleong** [firefly-iii/firefly-iii#3978]
Since upgraded Firefly III to version 5.4.3, the budget page no longer grouped by period (monthly), instead it will directly show "everything". Is this an intended changes, or i missed out some configuration? And yes, i double checked my Preferences > Layout > view range, One month is selected.

Tried with the [demo site](https://demo.firefly-iii.org/budgets/show/1), the same thing happens too.

**Comment by JC5** [comment]
It's probably a bug, I'll check it out. It seems the budget limit is no longer part of the URL. Thanks for letting me know!
