### ISSUE TITLE
Can't access newly created tags

### ISSUE THREAD

**Issue by carmolim** [firefly-iii/firefly-iii#3980]
**Bug description**
When I click on a tag that recently created using the Transaction form tag I'm getting this error:

```Argument 2 passed to FireflyIII\Support\Twig\AmountFormat::FireflyIII\Support\Twig\{closure}() must be of the type string, null given, called in /var/www/firefly/storage/framework/views/twig/0a/0afe1e30c1d72f63be26cda9d791c86cd00c9bd17b45d1d63cb0fbead84f335e.php on line 193```

The tags I create on the Tas page and the tags that I created before on the Transactions form are working ok.

**Steps to reproduce**
Go to Classification > Tags > Click on the newly created tag

**Extra info**

I'm running it inside a Home Assistant installation and I don't know how to access the logs.

Debug information generated at 2020-10-22 12:44:09 America/Sao_Paulo for Firefly III version **5.4.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.1 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 79aeb37d-7aa1-4230-bad0-fbf654f3109c |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

**Bonus points**
<img width="963" alt="Screen Shot 2020-10-22 at 12 52 07" src="https://user-images.githubusercontent.com/2863161/96898563-3dbdca00-1466-11eb-8b01-48c4a24d8feb.png">

**Comment by carmolim** [comment]
**UPDATE**

When I create a new tag on the Tags page I can enter the tag, but when I click on Show all transactions without grouping them by date. I get the same error.

**Comment by JC5** [comment]
This was already fixed, please upgrade.

https://github.com/firefly-iii/firefly-iii/issues/3839

**Comment by carmolim** [comment]
Sorry, I didn't find this reference. Since I'm stuck with the HomeAssistant available version there's nothing I can do right now.

Thanks for the fast reply!
