### ISSUE TITLE
Budget's currency not saved

### ISSUE THREAD

**Issue by weimdall** [firefly-iii/firefly-iii#3981]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:
I cannot create a budget limit for another currency than the default one

**Steps to reproduce**
1- Create budget
2- Assign an amount for the current period with a special currency (not the default one)
![2020-10-22-135407_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/96911503-eb34db80-146e-11eb-8c57-f56a98935101.png)
![2020-10-22-135426_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/96911509-ed973580-146e-11eb-879d-2a49993eb286.png)

3- Bug: Currency of new budget-limit is default
![2020-10-22-135436_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/96911513-eff98f80-146e-11eb-8fdf-0c776e88e5e5.png)

**Extra info**
Debug information generated at 2020-10-22 13:47:58 America/Montreal for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0 |

**Bonus points**
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nice find, fixed in the next release :+1:
