### ISSUE TITLE
Bi-Weekly (Fortnight) Budget

### ISSUE THREAD

**Issue by GeekDoc** [firefly-iii/firefly-iii#3982]
An "every two weeks" option for budgets would make Firefly III work perfectly for me.  Many have a payday every two weeks, like myself.  This means that, twice a year, I have three paydays in a month.

I budget things like "electricity" and "mortgage" monthly, because that's how they are billed.  Twice a year, I have a paycheck that I do not have to set aside anything for these budget items.

However, budgets like "groceries" and "fuel" have to be allotted to from every paycheck.  These are budgets that are consumed at the same rate, no matter the length of the month.  These I hold out of every paycheck.  

I could probably work around not having this option by halving my 2 week budget to a weekly budget, but many of my 2 week budgets are used up in single purchases.  I usually purchase groceries to (mostly) last 2 weeks, and I fill my fuel tank once in 2 weeks, for example.  Halving the budget to weekly wouldn't work in these cases.

FIrefly III works great for tracking my accounts.  I think this option would probably help many users customize and use the budgets feature.

**Comment by JC5** [comment]
There won't be a biweekly budget option. 

https://docs.firefly-iii.org/about-firefly-iii/personal-finances#the-general-idea

**Comment by GeekDoc** [comment]
Thanks for the reply.  I missed that "general idea" part and dove right in.  Good to have a solid plan to work around.
I'll try to find something else that works for me.  Or, maybe I'll give your method a try.  It sounds pretty solid.
Thanks again.

**Comment by derekpurdy** [comment]
I'd just like to leave a comment, that mortgage payments are paid bi-weekly as well as paycheque. Over time this definitely messes up values trying to use weekly instead.
