### ISSUE TITLE
Help page not available

### ISSUE THREAD

**Issue by jens108** [firefly-iii/firefly-iii#3983]
**Bug description**
Hi there, loving firefly-iii! I am running Firefly III version 5.4.3, and my problem is:

When I hit the ? button at the top of the page for help, I am redirected to https://firefly-iii.readthedocs.io/
That page does not exist. Is there another link?

**Additional context**
I was trying to find out how I can look for transactions with a specific tag. Is there a way? Or maybe a help page that lists all the search options/queries? :-)

**Comment by JC5** [comment]
https://docs.firefly-iii.org/concepts/search

You can use `tag_is:query`.

What language are you using Firefly III in?

**Comment by JC5** [comment]
Replaced some old links.

**Comment by jens108** [comment]
> What language are you using Firefly III in?

German. Thanks for the new links!
