### ISSUE TITLE
Search Operator: attachment name and attachment content (e.g. PDF OCR)

### ISSUE THREAD

**Issue by C0nsultant** [firefly-iii/firefly-iii#3984]
**Description**
After over a year of using FireflyIII, I've recently developed the habit of attaching OCR'd receipts, invoices or other records of purchase to transactions. It would be really nice if there was a way to search for transactions based on keywords in these attachments. 

**Solution**
A mechanism to get text from OCR'd documents, probably only `.pdf`s apply here. 
First active php project that does this I've found is [spatie/pdf-to-text](https://github.com/spatie/pdf-to-text).

Maybe a new `content` model attribute for attachments, so as to not clobber `notes`.
This field should be automatically populated when uploading an attachment.
Alternatively, all attachments could be searched on every relevant query, but this will have a significant performance impact.

Two search operators:
- `attachment_name_[starts|ends|is|contains]:query` to search by the stored attachment file name
- `attachment_[contains|is]:query` to search by the actual text-content of the attachment

**What are alternatives?**
There is `has_attachments:true` which can help narrow down the search faster. But if you only remember details about a transaction that are only present in the attachment, finding the right one still requires a manual transaction-by-transaction approach.

Copying the OCR contents to the attachment notes manually could be a solution, but time-consuming and error-prone.
Also, `notes_contain:query` currently does not search attachment notes.

**Additional context**
I'm not suggesting to implement OCR here (though that would surely benefit some).
Getting OCR right is not trivial and probably out of scope for the project.

**Comment by JC5** [comment]
I like the idea of allowing the notes of attachments to be searchable. The rest is overkill I'm afraid. A tool like Paperless would be right for this.

**Comment by muppie** [comment]
I’m not sure if a continuing on this issue is the best way but would it be possible to implement a way to attach documentation to a withdrawl or charge instead of uploading? I have all my recepits and invoices in Paperless-ng and would like to keep them there, while also attaching them to a charge.

**Comment by JC5** [comment]
There is a URL field you can use. Check out your preferences.

**Comment by muppie** [comment]
Oh, thanks! Sorry for hijacking and the extra work!
