### ISSUE TITLE
SQL error: column "foreign_currency_id" does not exist

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#3985]
**Bug description**
I am running Firefly III version 5.4.3 (develop) on a fresh instance (no old database data). This error does not occur on my production instance.

This error is non-fatal, therefore the application works as expected. However, a Firefly III error outside of the database is thrown, which I consider to be unexpected.

You can find the stacktrace here: https://gist.github.com/niklas2810/8de4ca6c5849aea4758ee43296259f02 The issue seems to be about this line: https://github.com/firefly-iii/firefly-iii/blob/ff85654cb9c4b437c13a8f4838face8eed0cd10a/app/Console/Commands/Correction/EnableCurrencies.php#L72-L74

Please let me know if you need further details. I'm not quite sure whether this is something that needs to be fixed, I simply wanted to tell you that this error exists 😄 

**Steps to reproduce**

Set up a fresh instance of Firefly 5.4.3 (tested on Docker+postgres).

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files

**Comment by JC5** [comment]
Nice, found and fixed.
