### ISSUE TITLE
"Left to spend" not updated ?

### ISSUE THREAD

**Issue by weimdall** [firefly-iii/firefly-iii#3986]
**Bug description**
(Minor bug)
I am running Firefly III version 5.4.3, and my problem is:

When I change the total budget available for the current period, the green rectangle (Left to spend) on the dashboard is not updated immediately (takes few minutes ?).

**Steps to reproduce**
- Edit total available budget for the current period
- Check on the dashboard what is left to spend
-> The amount has not been updated (yet)

**Bonus points**
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Sometimes values are cached for performance reasons. If you wish to expedite the process, browse to `/flush` to clear it.

**Comment by weimdall** [comment]
Shouldn't this flush be called internally when the budgeted value change ?

It could be confusing for new comers, I started to have doubt about the meaning of that value since whatever the budgeted value was, nothing changed.

**Comment by JC5** [comment]
The cache is flushed. I noticed recently that not all systems do a proper flush. There's not much I can do.
