### ISSUE TITLE
Problem with budget that applies for several periods

### ISSUE THREAD

**Issue by weimdall** [firefly-iii/firefly-iii#3987]
I am running Firefly III version 5.4.3.

**Description**
I am using the "Auto-budget" feature, and encountered a minor issue with a "Yearly" budget.
On the "Budget" page, the "Budgeted" value is the sum of all the listed budgets for the current period.
But, this value doesn't reflect the budget for the current period if one of the budget is for a larger period.

Like, for instance if I have a budget "Fixed Cost" of 10.000€ that applies for the whole year, then 10.000€ will be added to the "budgeted" amount for each period.

I cannot reproduce that behavior on the demo website since this mechanism relies on cron jobs triggered at specific time, so here is a screenshot from my firefly instance :
![2020-10-23-170928_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/97055604-23aee500-1555-11eb-9350-3ba1b1af5e4c.png)

The full value "x5" has been added to the total "Budgeted", even though it's a budget for the whole year.

In my screenshot, x5 (budget for the year) could be divided by the number of period in a year (here 12) and then be added to the budgeted amount of the current period .. but that sound clumsy since the budget will not be spent regularly across the periods.

Sooo, I don't have a good answer to that problem, it's not a big thing, but if you or someone else have an idea that could give a more accurate budgeted amount in this situation ?

**Comment by JC5** [comment]
Nope. Dividing by 12 or the number of days or whatever is clumsy indeed. This is an edge case I can't really solve in the current layout.

**Comment by weimdall** [comment]
Well, I am enlightening this issue because I feel like the current behavior is even worst than a division.
I would prefer to choose which budget is considered in that sum ?

But sure, as I said it's a minor incoherence, no big deal.
You thought about a possible solution for your next interface you are developing ?
