### ISSUE TITLE
Indian number system

### ISSUE THREAD

**Issue by theneelrana** [firefly-iii/firefly-iii#3988]
**Bug description**
Not sure if bug report or feature request.

I'm running firefly with INR as the default currency, and the Indian number system is not reflected in the Interface. Would be great if it was possible to implement.

More info from Wikipedia -
*The Indian numbering system uses separators differently from the international norm. Instead of grouping digits by threes as in the international system, the Indian numbering system groups the rightmost three digits together (until the hundreds place), and thereafter groups by sets of two digits.[2] One trillion would thus be written as 10,00,00,00,00,000 or 10 kharab (or one lakh crore).*
https://en.wikipedia.org/wiki/Indian_numbering_system

Specifically I'm talking about the number of digits between the commas in the firefly interface.

Obviously it's not a make or break issue, it would be like polish on an already great app ;)

Debug information generated at 2020-10-24 23:39:02 Asia/Kolkata for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b7390589-95a4-45b0-b2a5-342cbad900bd |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_IN |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 00:00:00 |
| Session first | 2020-10-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0 |

**Thanks for your work on firefly, I am absolutely loving it in my short time with it. I would love to be able to donate to you soon for your work mate. :)**

**Comment by JC5** [comment]
This is already possible, but *not* in the default Docker image. To reduce its size, en_IN is not included. To add it, you could run the following command.

```
docker exec -it [container] echo "en_IN.UTF-8 UTF-8" >> /etc/locale.gen && /usr/sbin/locale-gen
docker [container] restart
```

Then, it should work as expected.

<img width="547" alt="Screenshot 2020-10-24 at 20 34 00" src="https://user-images.githubusercontent.com/5889984/97091027-3c3bff80-1628-11eb-84bd-d31b3c13a0b1.png">

**Comment by theneelrana** [comment]
Tried that now, but doesn't seem to work.. Updated firefly to the latest version and then re-tried, still no luck. Not sure if I'm missing something. Any suggestions?

![image](https://user-images.githubusercontent.com/51183934/97093384-0ff4a300-1669-11eb-85ee-dc48af887855.png)

![image](https://user-images.githubusercontent.com/51183934/97093438-9a3d0700-1669-11eb-9368-7fdc8e2eda91.png)

Debug information generated at 2020-10-25 02:27:37 Asia/Kolkata for Firefly III version **5.4.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.4 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b7390589-95a4-45b0-b2a5-342cbad900bd |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_IN |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 00:00:00 |
| Session first | 2020-10-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0 |

**Comment by JC5** [comment]
I’m afraid you’re out of luck then. Sorry about that.

**Comment by theneelrana** [comment]
No worries, Thanks for your reply, at least I know it's possible now, so i'll play around with the setup when I can.
