### ISSUE TITLE
for new entries the category and destination account fields data is discarded and overwritten 

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#3989]
Debug information generated at 2020-10-24 19:26:08 UTC for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 74190c2e-16a6-4452-9a79-4f989862dc35 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2014-03-20 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 |

I have noticed since I upgraded that whenever I create a new entry, either a transfer or a withdrawl, the category entries in both cases and the destination account in case of withdrawls, despite what I enter after saving the information is always overwritten with a specific category and a specific destination account. 

If I clone a transaction this does not occur.

**Comment by JC5** [comment]
This could be caused by inactive rules that are executed inadvertently. Could you upgrade to 5.4.4 and let me know if it still occurs?

**Comment by lverissimo** [comment]
@JC5 ok. I am upgrading to 5.4.4.

I get this message, and I am not sure if I should force or not. Can you help? I also got this message when upgrading to 5.4.3

[root@xxx firefly-iii-updated] # php artisan passport:install
**Encryption keys already exist. Use the --force option to overwrite them.**
Personal access client created successfully.
Client ID: 38
Client secret: Lo5uHRPQBdSJcZHdkntAuq3IPJcnyKEm1Dx36Z6m
Password grant client created successfully.
Client ID: 39
Client secret: b1NgWQmDqioixAYuGCUv5YYrvow8NAtke48F8zgI

**Comment by lverissimo** [comment]
@JC5 I ended up forcing new encryption keys. Completed the upgrade with sucess. I am not experiencing the same issue in 5.4.4. 
Thank you so much for your support. I will proceed to close the issue.

**Comment by JC5** [comment]
Thanks, glad to see it works! Next time, no worries about the encryption keys. I can't remove the message unfortunately but you don't need to recreate them.w
