### ISSUE TITLE
Expense Account graph is weird

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3992]
**Bug description**
I am running Firefly III version 5.4.4, and my problem is: The date graph on an expense account with foreign transactions has strange behaviors.
I was looking at transactions for an expense account that had one transaction with both USD and Euro pricing and when I looked at the date graph, it seems to be only looking for Euro transactions even though it's clearly a USD graph and I have other USD transactions before and after the transaction in question:
![image](https://user-images.githubusercontent.com/21091510/97129413-40921680-1715-11eb-8687-052c2302bc72.png)
Also, the US pricing on there is wrong.

When I went to see if I could replicate on the demo site, I ran into a different problem instead. Even though the demo site is set up to default to Euros, the graph is displaying USD:
![image](https://user-images.githubusercontent.com/21091510/97129568-936bce00-1715-11eb-9a07-70e7f96ae63c.png)
Even though there are other Euro transactions listed:
![image](https://user-images.githubusercontent.com/21091510/97129594-a4b4da80-1715-11eb-98bc-2cd040d557c1.png)

Also, when you have a transaction with 2 currencies, the month view gets kinda messed up. First, the two lines split:
![image](https://user-images.githubusercontent.com/21091510/97129773-1db43200-1716-11eb-8be0-cb7a57c2c92e.png)

Then they come back together (wrongly at $0):
![image](https://user-images.githubusercontent.com/21091510/97130041-b77bdf00-1716-11eb-9997-92f45cc5565d.png)

Then they go up by 2 different amounts:
![image](https://user-images.githubusercontent.com/21091510/97130143-edb95e80-1716-11eb-8cd0-d4984dc9f837.png)

Then they strangely come back together again:
![image](https://user-images.githubusercontent.com/21091510/97130198-16d9ef00-1717-11eb-950e-c245bb431b83.png)

So I could not replicate my initial problem, but I think that might be because the demo graph is stuck on USD for some strange reason.

**Steps to reproduce**

1. Have a USD based firefly system (I guess)
2. Have an account with multiple transactions (at least one of which has both USD and another currency)
3. Go to the account overview for the account in question.
4. Set your time frame to "Everything"
5. See if your chart gets stuck.

**Extra info**

Debug information generated at 2020-10-25 23:12:14 America/New_York for Firefly III version **5.4.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.4 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/ (I replicated a bug, but not the first one).

**Comment by JC5** [comment]
Thanks for letting me know. I found an issue that could explain the jump back to zero, but I'm not really sure if everything you describe here is a bug.

> I was looking at transactions for an expense account that had one transaction with both USD and Euro pricing and when I looked at the date graph, it seems to be only looking for Euro transactions even though it's clearly a USD graph and I have other USD transactions before and after the transaction in question:

In your screenshot I see the same amount for Kickstarter in EUR and USD. I don't know what it's supposed to say and why this should be the case.

> Also, the US pricing on there is wrong.

I can't tell if this is true from the data you're showing. When I create a single transaction with EUR/USD amounts (the same amounts) I get the chart you see. When I change the amounts the chart updates accordingly. 

> When I went to see if I could replicate on the demo site, I ran into a different problem instead. Even though the demo site is set up to default to Euros, the graph is displaying USD:

I can't replicate this. The chart remains in EUR even when the expense account only has GBP transactions. But remember, plenty of people mess around with the demo site. It's true though that the title balance (in brackets) will remain at zero EUR if the account only has GBP transactions, because the balance in brackets is always displayed in the main currency.

<img width="1330" alt="Screenshot 2020-10-26 at 06 30 20" src="https://user-images.githubusercontent.com/5889984/97136914-5bcc4880-174c-11eb-8114-7ecef44f8cb8.png">

> Also, when you have a transaction with 2 currencies, the month view gets kinda messed up. First, the two lines split:

Both currencies are shown, and if the amounts are different, the line splits. 

> Then they come back together (wrongly at $0):

Indeed. That one I can replicate, and it'll be fixed in the next release.

> Then they go up by 2 different amounts:

This makes sense from your own screenshots, but the amounts should be different, I think.

> Then they strangely come back together again:

Same bug, and will be fixed!

**Comment by death2cupbots** [comment]
I'm wondering if that caught my original issue too.

Here's my site's graph and data:
![Screenshot_20201026_074724](https://user-images.githubusercontent.com/21091510/97169207-10239a00-1760-11eb-9b06-780246f7dac5.png)
![Screenshot_20201026_074908](https://user-images.githubusercontent.com/21091510/97169270-26315a80-1760-11eb-89a3-16678b4ec2d9.png)

And here's the demo site:
![image](https://user-images.githubusercontent.com/21091510/97169580-aa83dd80-1760-11eb-9dc9-ef0d4d1990d2.png)
![Screenshot_20201026_074846](https://user-images.githubusercontent.com/21091510/97169334-482add00-1760-11eb-832b-2b68d081a4fe.png)

Both of those were entered this morning in the same order this morning. The only difference is the base currency but that _shouldn't_ matter.

**Comment by JC5** [comment]
I think so. The original issue mixed up currencies when calculating the balance. That seems to be fixed.
