### ISSUE TITLE
Demo Site not suggesting accounts or categories

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#3993]
**Bug description**
The demo site is running Firefly III version 5.4.4 (presumably), and its problem is:
When I was testing my previous issue, I went to enter a transaction. I found that the drop down did not appear for soure or destination accounts or for categories, as you can see here:
![image](https://user-images.githubusercontent.com/21091510/97130963-4689f680-1719-11eb-978b-02c23c764afe.png)
This does not occur on my firefly running 5.4.4.
Suggestions do appear when creating rules.

**Steps to reproduce**

1. Go to https://demo.firefly-iii.org/ and login.
2. Enter the form to create a transaction.
3. Click on the Source Account, Destination Account, or Category field.
4. Notice the drop down does not appear.
5. Start typing a name.
6. Notice that there are no suggestions.

**Extra info**

I tested this on Firefox and Brave on both Windows and Manjaro Gnome Linux. I cannot access the debug page.

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/ (only exists on demo site)

It's possible you'll have already noticed this or fixed it before seeing my note. Just wanted to make sure you were aware.

**Comment by JC5** [comment]
Thanks, I wasn't aware. It works again :+1:
