### ISSUE TITLE
500 errors while posting transaction

### ISSUE THREAD

**Issue by codeplexnl** [firefly-iii/firefly-iii#3998]
I was getting 500 errors while calling the post for transactions using the CSV importer.

I traced it back to an attribute that i do not set trying to be referenced.

https://github.com/firefly-iii/firefly-iii/blob/ca3e4e978d1ab1af759b51ac2f840a7cfb7c422a/app/Transformers/TransactionGroupTransformer.php#L566
I found that in the method there is a null check for `$object[$key]`  however if it is not null then return `return $object['interest_date']->toAtomString();`

I think this should be 
`return $object[$key]->toAtomString();`

**Comment by JC5** [comment]
Same as this one. https://github.com/firefly-iii/firefly-iii/issues/3991

I hope to post a new release soon.

**Comment by codeplexnl** [comment]
Ow sorry in my search i did not find this.

**Comment by JC5** [comment]
No worries, different aspect of the same issue.
