### ISSUE TITLE
Error creating Personal Access Token 

### ISSUE THREAD

**Issue by rchampagneca** [firefly-iii/firefly-iii#3999]
**Bug description**
Firefly version: 5.4.4
Self-Hosted: Ubuntu 16.04.2

**Steps to reproduce**
I get the following error message when I try to create a new Personal Access Token :

![Capture d’écran 2020-10-26 à 16 13 42](https://user-images.githubusercontent.com/14007348/97223529-4552db00-17a6-11eb-8508-52761b5c3726.png)

**Logs**
```
[2020-10-26 15:59:05] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/22\/50\/22502b3b465e77a5ed890b61bd2c08ea5f217b15): failed to open st$
[2020-10-26 15:59:05] local.ERROR: file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/22/50/22502b3b465e77a5ed890b61bd2c08ea5f217b15): failed to open stream: No such file or directory {"userId":1,"exception":"[object] $
[stacktrace]
```

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue+failed+to+open+stream

**Comment by rchampagneca** [comment]
### Debug information ###
Debug information generated at 2020-10-27 14:36:28 America/Toronto for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 0b3461b7-b641-4cf9-8294-f82302079881 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | fr_CA |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 |

## Bug Description ###

Tried flushing cache but the problem persists.
