### ISSUE TITLE
Bugs on budget graph (Dashboard)

### ISSUE THREAD

**Issue by weimdall** [firefly-iii/firefly-iii#4000]
Hello, it's me again !
I am proud to create the ticket number #4000 :smiley: 

Sorry, I am creating a lot of ticket, but it's because I like this project :>
I am currently doing a PhD, and firefly helps me to keep an eye on my accounts (since  2017).

The bug I find are usually related to issues with default currency vs foreign currency because I live in a foreign county : I have accounts in euro and dollars, budgets in euro and dollars, etc ..
So, I feel like I am the tester of these features ;)

**Bug description**
I am running Firefly III version 5.4.4, and my problem is:
The budget's graph on the dashboard has two bugs while using multi-devise transaction.
1. The tooltip always shows the default devise symbol in the budget graph.
2. When transactions have amount in a currency and a foreign currency, the graph is buggy.

**Steps to reproduce**
On the **demo website**, I did the following action :

1. Create a GBP transaction in "Checking account in GBP" for budget "Car" :
![2020-10-27-120138_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/97329615-9e297e80-184d-11eb-97ce-ef3a018e3ddb.png)

2. (FYI) The Car budget looks like this : 
![2020-10-27-120201_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/97329870-e8aafb00-184d-11eb-838a-1eba569db586.png)

3. **First bug** The graph on the dashboard shows the wrong currency in the tooltip (it is displaying € instead of £) :
![2020-10-27-115936_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/97330012-16903f80-184e-11eb-8ed1-db1e6581acf3.png)

4. Add a foreign currency to the previously created transaction :
![2020-10-27-120258_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/97330201-51927300-184e-11eb-871b-97f982a61202.png)

5. **Second bug** The bar for the € part of the budget "Car" is picking the amount available in £ now :
![2020-10-27-120408_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/97330238-5e16cb80-184e-11eb-9227-8224fecf5e58.png)

**Comment by JC5** [comment]
Congrats on snatching up ticket 4000! 

1. Can't fix the bars, unfortunately. The library does allow for custom currency symbols but for bar charts it's impossible to include them in the JSON. Sorry about that.
2. Nice find. Fixed.

The fix should be live on the demo site. :+1:
