### ISSUE TITLE
Encoding issues with auto-completion suggestions

### ISSUE THREAD

**Issue by marcelbrueckner** [firefly-iii/firefly-iii#4001]
**Bug description**
I am running Firefly III version 5.4.4, and my problem is:

I've created some categories with a greater-than sign (`>`) in its name to workaround the lack of subcategories in Firefly III. When accepting a category suggestion, the greater-than sign gets replaced by its corresponding HTML entity `&gt;`.

Same applies for some other special characters. Couldn't reproduce this behaviour for e.g. Tags or Accounts.

However, account names with special characters are *sometimes* displayed HTML encoded in the suggestion list, but taken over into account field just fine.

**Steps to reproduce (Category)**

1. Create a category with special characters in its name
2. Create a new withdrawal, start typing the category name and accept the autocompletion suggestion
    ![grafik](https://user-images.githubusercontent.com/3597890/97360660-c7262f80-189e-11eb-8a01-1c75fa6ad7e6.png)

3. *See the special characters replaced with HTML entities*
    ![grafik](https://user-images.githubusercontent.com/3597890/97360686-cb524d00-189e-11eb-951a-225ea0bf8fd1.png)
    ![grafik](https://user-images.githubusercontent.com/3597890/97360693-cdb4a700-189e-11eb-9acf-2d8059cc44fb.png)

**Steps to reproduce (Account)**

1. Create an expense account with special characters in its name
2. Create a new withdrawal, click into the destination field and wait until the list of suggestions pop up
3. *Notice the HTML-encoded account name*
    ![grafik](https://user-images.githubusercontent.com/3597890/97362201-f2aa1980-18a0-11eb-96cb-4fc2b81e64f5.png)

4. Start typing the account's name and notice the suggested account gets displayed properly
    ![grafik](https://user-images.githubusercontent.com/3597890/97362233-fdfd4500-18a0-11eb-8994-440d33ed9a00.png)

4. Accept the suggestion and see how the account is taken over just fine
    ![grafik](https://user-images.githubusercontent.com/3597890/97362403-3ef55980-18a1-11eb-85bc-6fcab91cfda2.png)

**Workaround**

Don't accept auto-completion suggestion but type the exact category name manually (or implement subcategories in Firefly III 😉)

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by death2cupbots** [comment]
A better workaround (maybe) would be to use a different symbol. I personally use a :, like Account:Subaccount, because that's the way they're formatted in GnuCash.

**Comment by JC5** [comment]
#3990

**Comment by marcelbrueckner** [comment]
Shouldn't it work on the demo page already if it's fixed in develop?

**Comment by JC5** [comment]
Sorry, this is a slightly different issue.

**Comment by JC5** [comment]
This is something in the underlying typeahead library. I'm not sure what the fix should be. Stay tuned.

**Comment by JC5** [comment]
Fixed in next release.
