### ISSUE TITLE
Add description to categories

### ISSUE THREAD

**Issue by marcelbrueckner** [firefly-iii/firefly-iii#4002]
**Description**

I would like Firefly III to have a description/notes field for categories like it's already implemented for tags, accounts, piggy banks etc.

**Solution**

* Being able to add a description/note would add more clarity to a otherwise single-worded category name
* It would help to decide which kind of transactions should be assigned to this category
* Description text could be used for auto-completion suggestions
* Description could be displayed in reports to give more context

**What are alternatives?**
None

**Additional context**
That's what I'm looking for 😅 

**Bonus points**

**Comment by JC5** [comment]
Good idea. The notes field has been added to the category object, although it's not displayed anywhere (yet).  I'll keep this open and think of nice places to put the notes.

**Comment by marcelbrueckner** [comment]
Thanks for considering it. I have already noticed the notes text box in v5.4.5 and just want to point out the following:

* Notes field available when creating a category, but not when editing or viewing
* Notes are returned by the API (`{{ base_url }}/api/v1/categories`), but ignored when POSTing a new category like so (returned JSON object contains `null` for the notes fields)
    ```json
    {
        "name": "Category name",
        "notes": "An extensive description of the category"
    }
    ```

**Comment by JC5** [comment]
I know.

**Comment by JC5** [comment]
I've fixed the API so this should work as expected in the next release. I've put a feature freeze on the new layout so I can focus on the new layout I'm building right now. I expect that in that layout, the notes (now invisible), will get a nice spot.
