### ISSUE TITLE
Impossible to set foreign currency for auto-budget

### ISSUE THREAD

**Issue by weimdall** [firefly-iii/firefly-iii#4003]
**Bug description**
I am running Firefly III version 5.4.4 and my problem is:
When I create a auto budget with a foreign currency, the default one is set instead.

This issue is similar to #3981, but for auto-budget.

**Steps to reproduce**
(Tested on demo website)

Create a new budget with a auto budget in a different currency than the default :
![2020-10-27-192544_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/97372713-a6ec7580-188a-11eb-80b9-2353bc8e7f9d.png)

BUG: Budget has been set with the wrong device
![2020-10-27-192554_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/97372715-a8b63900-188a-11eb-9966-2843851c57fd.png)

**Comment by JC5** [comment]
Nice find, fixed :+1:
