### ISSUE TITLE
Guzzle: cURL error 28: Resolving timed out

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#4004]
**Bug description**
I am running Firefly III version 5.4.5, and my problem is:

Getting this message in the logs and on the dashboard:
`Error! Guzzle: cURL error 28: Resolving timed out after 3141 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://version.firefly-iii.org/index.json`

**Steps to reproduce**
Just run 5.4.5 I suppose? 😄 

**Extra info**
Running docker container on a Synology

**Bonus points**
- I searched and nobody reported this bug before

**Comment by JC5** [comment]
Since the resolving timed out and not the connection, I suspect DNS issues. The site is up and running.

**Comment by MacPaille** [comment]
Now the error is gone. One thing I noticed yesterday when I opened it is the https://version.firefly-iii.org/index.json was still containing version 5.4.4 in this section:

```
"firefly_iii": {
        "stable": {
            "version": "5.4.5",
            "date": "2020-10-28",
            "title": null,
            "description": null,
            "from_github": true,
            "link": "https:\/\/github.com\/firefly-iii\/firefly-iii\/releases\/tag\/5.4.5",
            "is_stable": true,
            "is_beta": null,
            "is_alpha": null
        },
        "beta": {
            "version": "5.4.5",
            "date": "2020-10-28",
            "title": null,
            "description": null,
            "from_github": true,
            "link": "https:\/\/github.com\/firefly-iii\/firefly-iii\/releases\/tag\/5.4.5",
            "is_stable": true,
            "is_beta": null,
            "is_alpha": null
        },
        "alpha": {
            "version": "5.4.5",
            "date": "2020-10-28",
            "title": null,
            "description": null,
            "from_github": true,
            "link": "https:\/\/github.com\/firefly-iii\/firefly-iii\/releases\/tag\/5.4.5",
            "is_stable": true,
            "is_beta": null,
            "is_alpha": null
        }
```

A DNS or network timeout would have been seen after 30 seconds, not 3.141 seconds... As now your file contains 5.4.5 seems he is happy 😄  That's my best guess on what happened.

Don't know if you want to still check something, otherwise you can close the ticket.

**Comment by JC5** [comment]
I think there’s a timeout for both of 3.1 seconds. I’d have to check. But no matter, it’s fixed! I’ll pick up some improvements along the way. That page will probably end up in a static bucket somewhere. It doesn’t need that many updates.
