### ISSUE TITLE
New transactions categories have special characters show up as html encoded

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#4005]
**Bug description**
I am running Firefly III version 5.4.5, and my problem is:
I see that new transactions where I add a category (all the old ones already had categories) have e.g. > encoded:
<img width="106" alt="Screen Shot 2020-10-28 at 22 54 10" src="https://user-images.githubusercontent.com/1221024/97500878-ac23f000-1970-11eb-94c7-9f73a01afaae.png">

The top one is new, the bottom one is an old one

It only seems to happen when the category is updated through the UI.

**Steps to reproduce**

No idea, the only thing that changed is my firefly version. I changed from postgres to mariadb with a conversion, but I have already entered transactions and then it worked fine. It seems to have changed it 5.4.3 or 5.4.5

**Extra info**

Official docker image.

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by daften** [comment]
Update, the problem seems to be in loading the category in the edit/create screen, it's loaded there with the wrong character set now, and because it looks different with the encoded character, it creates a new category.

**Comment by daften** [comment]
A json response when starting to find a category looks fine:
```
[{"id":7,"name":"Mobility > Parking"},{"id":87,"name":"Mobility > Car"},{"id":88,"name":"Mobility > Carwash"},{"id":89,"name":"Mobility > Car maintenance"},{"id":90,"name":"Mobility > Cycling"},{"id":91,"name":"Mobility > Gas and fuel"},{"id":93,"name":"Mobility > Public transport"},{"id":94,"name":"Mobility > Shared mobility"},{"id":95,"name":"Mobility > Taxi"},{"id":96,"name":"Mobility > Mobility (other)"}]
```

Everything looks fine in the dropdown, but goes wrong when inserted in the actual textfield:
<img width="215" alt="Screen Shot 2020-10-28 at 23 13 07" src="https://user-images.githubusercontent.com/1221024/97502313-2fdedc00-1973-11eb-9baf-c991c6c80646.png">

This is gonna be a javascript issue, isn't it? :(

**Comment by daften** [comment]
Maybe this escapeHtml caused it? https://github.com/firefly-iii/firefly-iii/commit/e6c0bbf082c64ed7a2794930baf0861e1199d1fd#diff-d860ab5c1e102adaabeb0a5f1de1f25133b655d4318fbc3ca4eaca271beba109R103

**Comment by JC5** [comment]
Thx, I'll check it out.

**Comment by JC5** [comment]
A fix is live on the demo site. When it works for you as expected, please switch to the develop image or branch until the new release is live.

**Comment by daften** [comment]
@JC5 Tested on the demo site, and it looks good there. I'll see this weekend if I wait or update depending on how much I feel like categorizing my finances, unless you'd like me to try it out like that too.

**Comment by JC5** [comment]
It's fixed, hope to push the new release this weekend. Classic overcompensating: escape twice to fix another issue.
