### ISSUE TITLE
Error message states issues are "below" when they are above

### ISSUE THREAD

**Issue by andyshilton** [firefly-iii/firefly-iii#4006]
**Bug description**
I am running Firefly III version 5.4.4, and my problem is:
When submitting a withdrawal/deposit/transfer, if there is an error, the message states ot "Please check out the errors below". This correctly appears in a bar at the top, but it also appears under the Submit button. The problem is, I couldn't see the message bar at the top when I submitted so I only saw the one below the Submit button, and it is incorrect. The error is actually highlighted in red above, not below.

Sorry, not a big bug, but thought I'd make you aware.

**Steps to reproduce**

Submit a withdrawal/deposit/transfer that has an error (eg missing required fields, or a source account that doesn't exist). Notice the error message under the Submit button.

**Extra info**

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
![image](https://user-images.githubusercontent.com/16556349/97506959-15593280-1974-11eb-8f93-831a745b4be1.png)

![image](https://user-images.githubusercontent.com/16556349/97506990-243fe500-1974-11eb-937d-611951198c05.png)

- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
I'll make sure the text points in the right direction. :+1:

**Comment by andyshilton** [comment]
Thanks as always @JC5 Love FireFly so happy to help :)
