### ISSUE TITLE
Rule Success Box should list number of transactions affected

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4007]
**Description**

When you run a rule for old transactions, all you get is a text box that says "Success! Rule "_your rule here_" has been applied to your selection." 
![image](https://user-images.githubusercontent.com/21091510/97517293-4e40d980-196b-11eb-8900-a805263656f7.png)
This will come up even if your rule changed 0 transactions. It would be great if it would give you a count of how many transactions it had changed or at the very least tell you it hadn't changed any.

**Solution**

_(this should really say how would users benefit from this feature being added to Firefly III)_
Users would be able to know that their rule running had done something (or nothing) right after they had run the rule.

**What are alternatives?**

Right now you could manually run a search or hunt down transactions you think may have been changed to see if they were changed.
You can also presearch by clicking the beaker(?) icon. This will show you all matching transactions, though, not just the ones that would be changed.

**Additional context**

**Bonus points**
![Screenshot from 2020-10-28 22-17-48](https://user-images.githubusercontent.com/21091510/97517756-2e5de580-196c-11eb-9f48-1ac381921749.png)

**Comment by JC5** [comment]
I'll see what I can do, but not a lot probably. Even when a transaction is found, there's no guarantee the rule will *change* anything. Tying all of that together will give me a whole lot of spagetti code.

**Comment by JC5** [comment]
New release will report this!
