### ISSUE TITLE
CSV importer get "Request header too large"

### ISSUE THREAD

**Issue by shizunge** [firefly-iii/firefly-iii#4008]
I am running Firefly III CSV importer version 2.2.2 via docker, behind Traefik & Authelia

**Description**
Running Firefly III CSV importer version 2.2.2 via docker, behind Traefik & Authelia
Got error "Request header too large"

**Extra info**
Try to run the same setup on local machine: 
Modifying hosts to point example.com to 127.0.0.1
And there is no problem.
Then put the same setup to my VPS, tried to visit the CSV importer via the internet, got the error "Request header too large".

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by beloso** [comment]
I am having the same issue, how did you solve it @shizunge ?

**Comment by shizunge** [comment]
You may say it is not firefly's problem.
I used Authelia as my authentication proxy, the default read_buffer_size
and write_buffer_size is 4096, which seems too small for firefly. Changing
the Authelia's setting solved the problem.

**Comment by beloso** [comment]
Thank you!!
