### ISSUE TITLE
Bills are not taking into account the transfers

### ISSUE THREAD

**Issue by dperezq** [firefly-iii/firefly-iii#4009]
**Bug description**
I am running Firefly III version 5.4.5, and my problem is that the bills associated to a rule are not trigerred when found a transfer, just with the withdrawls. I have tried to put a condition also transfer, but does not work neither.

**Steps to reproduce**
Create new bill with some conditions.
![image](https://user-images.githubusercontent.com/7505361/97544528-08ffc480-19ca-11eb-9554-ff2941cdf2ea.png)

Then, create a rule, which will trigger the bill.
![image](https://user-images.githubusercontent.com/7505361/97544587-2339a280-19ca-11eb-8fd5-fafc8f5a93c3.png)

After that, create a transaction that matches with the bill/rules conditions.
![image](https://user-images.githubusercontent.com/7505361/97544664-38163600-19ca-11eb-8a60-00d6e200efe9.png)

Last step, go to the bill, click on "Run rules agin" and does not appear this transaction, however when click on "See matching conditions" in rules, there it is.
![image](https://user-images.githubusercontent.com/7505361/97544822-6eec4c00-19ca-11eb-8ee5-60a73f5d4856.png)
![image](https://user-images.githubusercontent.com/7505361/97544754-5845f500-19ca-11eb-8ad2-7ccfa2d9110b.png)
![image](https://user-images.githubusercontent.com/7505361/97544728-4d8b6000-19ca-11eb-9c1e-4cbb4c6f7801.png)

**Extra info**
I have tested this also in the demo site and the issue is there too.

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Bills can only be linked to withdrawals. 

https://docs.firefly-iii.org/advanced-concepts/bills
