### ISSUE TITLE
Can't create account through API that has been deleted before

### ISSUE THREAD

**Issue by jens108** [firefly-iii/firefly-iii#4014]
**Bug description**
Hi there, loving firefly-iii. I am running Firefly III version 5.4.3, and my problem is:

I have deleted a bunch of accounts (all) through the red buttons in the Firefly-iii frontend. Now I want to import some transactions with a custom-written CSV importer, but account creation for all these transaction fails because "The account name is already in use".
In the database, all the old accounts are still there but have a deleted_at value set.
I deleted all these entries and now import is fine. But maybe you should check for that value when checking if an account name already exists?

**Comment by JC5** [comment]
I'll need some more details. At first glance the check for deleted accounts seems to be fine. As you say, deleted accounts should not count when submitting data.

What is the request you submit exactly and what response are you getting?

**Comment by jens108** [comment]
Hey there, I looked into this and it seems my request was sent twice :-) Sorry about the trouble!

**Comment by JC5** [comment]
Haha no worries. Glad to hear my code is ok! 😅
