### ISSUE TITLE
Cron job fails

### ISSUE THREAD

**Issue by 5833tP2** [firefly-iii/firefly-iii#4016]
I am running Firefly III version 5.4.2 on a RaspPi 3, self-hosted and not using Docker. I cannot get cron working.

**Description**
My problem is very similar to [this issue](https://github.com/firefly-iii/firefly-iii/issues/3938) where the log file is locked by root. (I ran the job from the command line to see if I could find the error and it indicated that the log file was locked by root.) The suggested solution is to use `sudo crontab -u www-data -e` but this does not solve the problem for me. The cron job does not run and I do not know why. (I have other cron jobs running successfully on the server, so it's not a syntax or other n00b error.)

I cannot see anything useful in the log file. I only have '`ff3-audit-2020-11-01.log` (today's date) and all that seems to record is login attempts. No mention of cron job failure.

I am stuck and do not know what to do next. 

Thanks for your help.

**Comment by JC5** [comment]
If the log file is locked by root, you can delete it and then run the cron job.

Setting up the cronjob under www-data should work but use this command `sudo -u www-data crontab -e` (the other way around).

If it keeps you can also set up the cron job as a curl command, see the docs.

**Comment by 5833tP2** [comment]
Thanks for the revised crontab syntax.

`sudo -u www-data crontab -e` gives me a new error:

```
touch: cannot touch '/var/www/.selected_editor': Permission denied
Unable to create directory /var/www/.local/share/nano/: No such file or directory
It is required for saving/loading search history or cursor positions.
```
I can ignore this and edit crontab as usual, but it still fails to run at the appointed time.

Where should the locked log file be? I can only see audit logs in the `/storage` directory and none are owned by root and none appear to be relevant to this cron issue. I feel like I am looking in the wrong place for this locked log file. If I cannot find it then I cannot delete it.

**Comment by JC5** [comment]
The error isn't a problem indeed. Assuming you mean `storage/logs`, this is where the log files should be.

But if this doesn't work use the curl method.

**Comment by 5833tP2** [comment]
There were no relevant log files in `storage/logs` (just audit logs with no lines relevant to cron).

The curl method worked fine. I've now got repeating transactions working as they should (punches air!).

Thanks for your help.
