### ISSUE TITLE
Rules broken since they become case-sensitive

### ISSUE THREAD

**Issue by FelikZ** [firefly-iii/firefly-iii#4018]
**Bug description**
I am running Firefly III version 5.4.5, and my problem is:

My rules do not match transactions since they were expected to match transaction based on description or account name case-insensitive.

**Steps to reproduce**
1. Create transactions for account names Albert Heijn and ALBERT HEIJN.
2. Create a rule "Destination account name contains" "ALBERT HEIJN"

It will match 1.
Expected 2 (it was working before, and broken at some point, perhaps with 5.4* version)

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.

![image](https://user-images.githubusercontent.com/1080269/97809483-72533200-1c6d-11eb-9d83-c5e9e8786409.png)
![image](https://user-images.githubusercontent.com/1080269/97809528-a169a380-1c6d-11eb-94dc-805cb1784262.png)

**Comment by JC5** [comment]
If you're using PostgreSQL, there's nothing I can do. The search is done by the database and since PostgreSQL is case senstiive... the rules are too.

**Comment by FelikZ** [comment]
;-(
