### ISSUE TITLE
Rules: Set source/destination by id (and not only by name)

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#4024]
**Description**
I am using some dummy asset accounts to properly manage my internal transfers. I set them to inactive in order to hide them from the UI. Everything is finde, just that I cannot set them as destination or source in the rules:
* setting ID is not possible
* setting by name leads to a new account

**Solution**
Either look for account names also in inactive accounts or add rule actions by id

**What are alternatives?**
Have them enabled

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
I'm curious about your use case and your use of inactive accounts to hide stuff. I'm not going to add the ability to use inactive accounts in rules.

What are you trying to do?

**Comment by totti4ever** [comment]
Hey, I changed my opinion on inactive accounts and made them active. It is a bit messy when listing the asset accounts, but that's okay as I guess I'll stop going there once everything is setup.

What am I doing? Let's take two asset accounts, one checking account (`C`), one saving account (`S`) - both are fed through CSV import from their corresponding bank websites.
No, when I transfer money from `C` to `A`, I will have two transactions in firefly with to reconciliation options:
1. Automatic recognition of duplicates and one is rejected, the other points from `C` to `S`  
I tested this but didn't like three things
	1. I might miss out on information which is in the rejected transaction. Might be some bank specific data or so)
	2. From time to time it is not that easy for firefly to automatically recognize these duplicates, when bank statements e.g. don't state the source IBAN. Then I would have these amounts doubled in one account
	3. I would have no chance to check whether my accounts run out of sync with the original bank accounts, e.g. in case of rejected transactions from one bank

2. So what I did is create asset accounts for each transfer type, in our case `transfer: C <--> S`  
I can import both original transactions, where both are booking against the new asset account:
	* `C` --> `transfer: C <--> S`
	* `transfer: C <--> S` --> `C`

	I'm quite happy with this solution as this mirrors more or less the representation on bank side and I can use rules quite easily, most of the times the mapping function of the CSV importer is enough. This way I can even easily see whether transactions are missing, when one of the transfer accounts is uneven. But well, most of the time I just don't wanna see those accounts and there wanted to hide them :-)

keep up the great work!

**Comment by JC5** [comment]
I see what you mean. Glad to see it works! And thanks for the compliments! :+1:
