### ISSUE TITLE
Demo website is down

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#4027]
Not sure if you're aware of it, but demo website https://demo.firefly-iii.org/ gives a 500 error
Trait 'Illuminate\Database\Eloquent\Factories\HasFactory' not found 
I guess it's due to your latest commit missing this new class.

**Comment by JC5** [comment]
Thanks, back up!

**Comment by ngalfas** [comment]
This is the same point i am right now trying to update to 5.4.6 
Usually i just overwrite the .zip release over the old version and see the upgrade process from the login page...
I think i have to rebuild with composer...
