### ISSUE TITLE
In the default report, bills paid prior to their expected date are "Not charged"

### ISSUE THREAD

**Issue by a1ex4** [firefly-iii/firefly-iii#4028]
**Bug description**
I am running Firefly III version 5.4.5, and my problem is that bills that were paid before their expected date shows up as _Not charged (yet)_ on the default monthly report.

It is considered paid everywhere else within Firefly, but not in the report.

**Steps to reproduce**
* Create a new bill
* Create a transaction associated with the bill but paid at an anterior date than the expected one
* Check the default monthly report, the bill is _Not charged (yet)_

**Bonus points**
- I was able to replicate it on the demo site https://demo.firefly-iii.org/ 

Link to the bill, expected the 5th but paid on the 2nd : https://demo.firefly-iii.org/bills/show/10

The report: https://demo.firefly-iii.org/reports/default/allAssetAccounts/20201101/20201130

Thanks ! 🙂

**Comment by JC5** [comment]
This is how it works. The expected date marks of the period in which the bill is expected to be paid. If you set a monthly bill to the 10th, the period will run from the 10-nov to 10-dec. If your report is for November, a bill paid on November 3rd doesn't count.

**Comment by a1ex4** [comment]
Ah, I see. Indeed that makes so much more sense for non monthly bills, thanks!
