### ISSUE TITLE
CSV importer: Errors are not prettified

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#4029]
Hello,

The errors are not (no longer?) prettified when importing a CSV.

    Error(s)
    Line #0: Submission HTTP error: Client error: `POST http://firefly_pro:8080/api/v1/transactions` resulted in a `422 Unprocessable Entity` response: {"message":"The given data was invalid.","errors":{"transactions.0.description":["Duplicate of transaction #6726."]}}

I think it should be more readable.

**Comment by JC5** [comment]
Indeed. The error has changed or it's not properly caught anymore. I'll pick it up!

**Comment by JC5** [comment]
Will be fixed in the next release :+1:

**Comment by JC5** [comment]
2.2.3 is out!
