### ISSUE TITLE
Feature: Replace sql migrations tool

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#4030]
**Description**
While the **up** and **down** migrations are cool, I've been finding that enterprises may be using tools that auto give schema migration differences such as sql server tools for visual studio (MS sql server). A solution for sqlite, mysql, and postgres could be [sqitch](https://github.com/sqitchers/sqitch).

## advantages
* won't need manual changes for mismatching schema
* let the tool manage differences for each
* could do db specific framework testing such as tSQLT(ms sql server) and MyTap(mysql), (not really using any procedures now)
* may be easier to maintain
* won't need to worry about down migrations anymore and won't need revert sql scripts

## cons
* work to get setup
* will need to maintain create sql statements for each db **provider**
* need to update pipeline to use different db provider migration tool for integrated testing

@JC5 what are you thoughts on replacing it?

**Comment by JC5** [comment]
Mmm, this is a pretty fancy tool, but it feels like massive overkill for Firefly III. If I had daily tickets from people struggling with DB migrations maybe, but things have been running pretty smoothly for a few years now. The advantages aren't that big for Firefly III or rather, I don't suffer from the downsides as much as they suggest I could.

Just using up & down migrations is more than enough for our purposes. For Firefly III, the only thing I'm currently considering is the new feature to [squash migrations](https://laravel.com/docs/8.x/migrations#squashing-migrations).
