### ISSUE TITLE
Slash converts to &#x2F; when using a category in transaction

### ISSUE THREAD

**Issue by Crotha** [firefly-iii/firefly-iii#4032]
**Bug description**
I am running Firefly III version 5.4.5, and my problem is that the "/" (slash) in Category names automatically reverts to "&#x2F;" in new transactions, which unfortunately creates a new category that uses that string instead of the slash in the name.

Pre-Click: 
![image](https://user-images.githubusercontent.com/47434645/98099853-60050e00-1e90-11eb-9909-beae93f212a6.png)
After choosing the category:   
![image](https://user-images.githubusercontent.com/47434645/98099886-698e7600-1e90-11eb-94da-4648d6aa4206.png)

This also creates a new category that is now namen "Education & #x2F; Office" in which the transaction is put.    
(PS: "& #x2F;" (without the space) automatically converts to "/" in github -_-)       

**Steps to reproduce**
I assume the language setting is a problem here, these are mine:     
![image](https://user-images.githubusercontent.com/47434645/98099983-87f47180-1e90-11eb-915a-27d57edf52a9.png)

**Bonus points**
- Search didn't bring it up.      
- CAN'T (!) replicate it on demo-site, so I assume it is - once again - a language issue.    

I also want to add that this is not really in any way a priority issue - I can replace the slashes with a dash, for example. 
I tried a few different, common symbols and for now only the slash is replaced.       
Thank you for Firefly-III.

Edit: One other, rather funny thing:    
I just noticed this only happens when I _click_ on the popup. I can type in the "/" and it gets sorted in the correct category with no problem.     
Hope this helps. Though I think reproducing may be hard? :/

**Comment by sephrat** [comment]
#4005

**Comment by Crotha** [comment]
ah damn it, bad at searching.   
Thank you very much! I'll close it immediately, as it is already fixed it seems.
