### ISSUE TITLE
Dropdown suggestions have special characters replaced with HTML escape code

### ISSUE THREAD

**Issue by hamfactorial** [firefly-iii/firefly-iii#4035]
I am running Firefly III version 5.4.5.

On the New Withdrawal entry page, after selecting a dropdown suggestion with a special character, the special character is replaced in the entry field.  The special character can be edited afterwards and saved, so I assume the bug is only in the function that copies the text into the HTML form.

![before](https://user-images.githubusercontent.com/39804831/98137791-3d1a3000-1e77-11eb-85ec-942ecdcb43bf.png)
![after](https://user-images.githubusercontent.com/39804831/98137804-40adb700-1e77-11eb-9ed8-24adb6fd37dc.png)

**Comment by JC5** [comment]
#4011 et al
