### ISSUE TITLE
Inserting old transactions

### ISSUE THREAD

**Issue by eathanc6** [firefly-iii/firefly-iii#4037]
I am running Firefly III version 5.4.5.

**Description**
This is the first time I am using Firefly III and I'd like to ask if what I am trying to do is possible.
I've created my bank account, added my current balance and all and now I'm trying to add previous transactions.
The thing is it decreases my balance although I thought it would adjust since these are old transactions..

Is what I am trying to do possible?

Thanks!

**Comment by JC5** [comment]
#3921
