### ISSUE TITLE
Overwrite LDAP filter / use other objectClass

### ISSUE THREAD

**Issue by idolux** [firefly-iii/firefly-iii#4038]
I am running Firefly III version 5.4.5

**Description**
I tried to connect Firefly with LDAP. The connection itself works fine but the hardcoded LDAP filter creates issues on my setup.
If I login with the user "test" Firefly does the following ldapsearch:
`filter="(&(objectClass=inetOrgPerson)(objectClass=person)(uid=*)(uid=test))"`

I do not have any inetOrgPerson objectClass. I use posixAccount instead. On GitHub I found the undocumented option `ADLDAP_AUTH_FILTER` which sadly does not overwrite the filter but expands and connects it with an `&`.

`filter="(&(&(objectClass=posixAccount)(uid=*))(objectClass=inetOrgPerson)(objectClass=person)(uid=*)(uid=test))"`

Therefore the login is not possible.

**Comment by JC5** [comment]
Sorry. Not much I can do about that.

**Comment by idolux** [comment]
I think `filter` should be completely free to change. So maybe this issue can be tracked as feature request?

**Comment by JC5** [comment]
The library I use isn't accepting feature requests anymore. But I've put it on my list to upgrade to its successor. Then I can look at this request, if it's not natively supported.
