### ISSUE TITLE
Retrieve password on docker?

### ISSUE THREAD

**Issue by wouterverduin** [firefly-iii/firefly-iii#4039]
I am running Firefly III version:  Latest docker image

**Description**
Couple of weeks ago I setup my FF and imported everything. Today trying to append the latest transactions at logging in my passwordmanager had the wrong password; saved it wrong or the password changed. 

Is there any way to retrieve the password? Needless to say I have full access to my machine and the docker install.

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ -> question not covered
- I added a screenshot -> no use
- I added log files  Doesnt show the password ;)
- I was able to replicate the issue on the demo site. -> not possible

**Comment by JC5** [comment]
If you use the reset password function, the email Firefly III will send out should appear in your log files. Use `docker logs -f [container]` to see them.

**Comment by wouterverduin** [comment]
Thanks James!

Tried this but doesnt show the link.

These are the two lines that appear:
`192.168.1.103 - - [08/Nov/2020:08:19:38 +0100] "POST /password/email HTTP/1.1" 302 2254 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
192.168.1.103 - - [08/Nov/2020:08:19:38 +0100] "GET /password/reset HTTP/1.1" 200 2977 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
`

Wrong verbosity? Anyway to adjust that?

Thanks in advance again1

**Comment by JC5** [comment]
Make sure `MAIL_LOG_CHANNEL` is set to `stack`. Set `MAIL_MAILER` to `log` and verify that `APP_LOG_LEVEL` is set to `debug`. That should make it appear.

**Comment by wouterverduin** [comment]
Thanks this solved it! You're my hero!

Small tip to others running into this: For some reason restarting the container didn't work for me. I had to recreate the firefly container after deleting it and then it showed up in the logs as suggested.
