### ISSUE TITLE
My pain points when using firefly (coming from Money Money on macOS)

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#4040]
Hey, at first I have to say that firefly-iii is an awesome piece of software with absolutely having the capability to fully replace the check and analysis part of a software like MM.

Still, I have bumped again a few things which kind of block not only my productive usage but also stopped me from introducing FF to my wife for having a look at our finances.

1. Repayments  
I know this has been discussed a lot of times, but I still cannot believe that this won't be a feature in firefly! Living in a modern world where I import all the transactions directly from my bank (thanks for the Spectre and finTS importers!) and where it is absolutely normal for many people to have items returned which they have bought online, I would say it is a MUST to be able to see those refunds flow back into budgets and so on. Having to do some manual corrections to transactions, which then also means I am out of sync with the transactions in my bank account is just no way in my opinion. Especially having the impression it is rather a ideology than about the technical effort.  
From my point of view I just want to know how much money I spent in a net view on shopping, on docters (after refund of insurance), etc etc - I don't care too much how much I initially spent or would expect that information as a detailed view using some revenue/expense filter 

2. Search  
For me it doesn't really work to just enter something into the search bar, hit enter and get some proper results as I am used to from Google and co. Also I havn't found a way for OR-searches. But still, my main point is that it would help a lot to either change the search engine to make a broader search or to introduce some auto suggestion help for all the dimensions one can use like _destination_account_contains:_. I mean, for myself I could imagine to cope with the current system after some months of usage - but regarding a WAF I cannot imagine. My wife would enter some keyword and wouldn't want to think about whether it is technically a destination or source account or it is in the description or a budget...

3. Concept of bills vs budgets vs categories vs tags  
Here I think some minor tweaks would be already helpful and I understood that you are open for ideas, so not a big thing.

4. Improve budgets  
Having a great view on the past in the budget corner, I would love to the the budget line there as well - kind of the same way I see it in a monthly view. You know, I am mainly trying to use firefly to get an impression how the past went, how narrow or good the budgets are and so on. I don't have a look at the current month so much. Maybe this is a major difference in usage?

5. Better slicing past periods  
Coming from the last point, I would love to have more options slicing the past periods in quarters and years, where right now I can select last 30 days and last 7 days

So, please don't get me wrong: I absolutely appreciate the work done on firefly and was absolutely surprised finding a self-hosted budget analysing application with this depth of details! I just have the impression that it is more focused on a daily usage compared to a rather monthly or weekly usage with automatic import of transaction of several accounts in order to grasp a view on the budgets and so on. And I think there is way to combine those approaches and I think it is not long. And I expect are more people like me out there who right now have some problems adapting firefly to their needed use case.

I hope this type of discussion is fine - cheers!

**Comment by JC5** [comment]
1. Has been discussed quite a few times now. Thanks for your insight. I really haven't found a good solution yet 
2. I'll see what I can do to expand the search.
3. I'm also looking to add improvements here.
4. I use several google sheets to improve my own budget overviews, so yes, this needs work.
5. Not a bad idea. I have some things in mind.

Thanks for the feedback and no worries, it's always appreciated. 😁

**Comment by totti4ever** [comment]
Hey, thanks for you answer!

Would it make sense to have a new issue per bullet to gather ideas and have your feedback on them? I would have some detailed ideas to share I think.

Regarding the first bullet: Great to hear, you are apparently open for finding a good way, too, if I understand you correctly? I'd love to help with ideas here as well, just have to understand the actual problem with it. I found a couple of issues where this was brought up:
- [FAQ](https://docs.firefly-iii.org/faq/financials)
- #4017 
- #3072 
- #1599
- #162

In a nutshell the suggested ideas for my use case (refund for online shopping or refund of health insurance) would be to
* increase the budget 
* edit the expense (cut it down)
* remove the expense from the budget

All of them do of course work - BUT do require manual work for every single refund, including finding the original position and having some complexity when the refund is only a part of expense.

I haven't really understand the downside of allowing revenues to be considered in budgets! It would be easy enough to just not assign them to a budget if you like it the other way. To make it clear, it could be even an option on budgets to allow revenues (I'm not talking about budgeting income or so!).
What I do understand is the point that you brought up in one of those issues, mentioning that those refunds could come in another period (i.e. next month) and therefore kind of relieve next month's budget and not help with last month's. So a better solution, budget-wise, would of course be to book the refund against the original expense...BUT (and here comes my main point) I want to have as little work as possible, i.e. automate as much as possible with finTS import and rules) and still get the best insights possible.
So what did I do so far? I just had a look on a rolling 12-month period for budgets which are prone to refunds and got quite a good impression on what we spent.

So, what I'm hoping for is that you bring up your long-time grown concerns and we find a solution, maybe at the same time bringing together the budgets and categories anyway :-)


P.S.: It would also just increase the WAF by trillions, because my wife would never accept a budgeting tool where her online shopping expenses are considered, but the refunds not. Of course, it would help environment if it was ;-)
P.S.: Just to emphasize the importance for me, the amazon expenses and revenues
<img src="https://user-images.githubusercontent.com/49901208/98458202-5f20f480-218e-11eb-92c9-af6d9ffaccd7.png" height=150 />

**Comment by JC5** [comment]
> To make it clear, it could be even an option on budgets to allow revenues (I'm not talking about budgeting income or so!).

It's the principle of the thing. Budgets are to manage expenses. Adding deposits to budgets doesn't solve the problem and doesn't make the issue clearer for new users.

> maybe at the same time bringing together the budgets and categories anyway :-)

lol no

**Comment by totti4ever** [comment]
I don't want to find the meaning of budgets in general, whether it should be a net view or not. I am just 100% sure that there are quite a few people, wo are interested in having a net view on certain groups of their transactions. I don't care whether that is called budgeting or something else.
But also for categories I didn't find a net view, which would help (although I would miss the target line then, which would make it kind of a budget).

And I just don't see the problem it would bring to people who want to use budgets the way you use it and not even the complexity for new users:
* you don't have to assign revenues to budgets and as long as you don't do that you wouldn't recognize a difference to the way you use them today, would you?
* new users have quite a few things to understand to become familiar with such a budgeting tool and I highly doubt they would fail because they accidentally assigned a revenue to a budget and don't understand what's happening then
	* and if this is the problem: just add an option to budgets to allow revenues/deposits and make no the default?!

I mean, firefly allows transactions with destination "personal drug dealer" although you might oppose such expenses in principle. **I still don't see the downside** while I see a big help for more people than just me (personally I think it'd be more than 50% of people who set up budgets in ff, but that doesn't matter).

To make it clear...it's your piece of work, so your decision. I would just be glad to kind of understand why this would somehow interfere with today's usage by other people!

**Comment by JC5** [comment]
There's no need to argue your case further, I understand it. Any solution to this problem is a lot of work. I hope you appriciate I'm not going to rush one way or another.

**Comment by totti4ever** [comment]
Okay, as I said it is your decision. Would have been easier to understand if one knew where the major part of the work would be.

So, after understanding that I won't be able to use budgets for my personal use case,
will there be any net view in the software or don't you see any net analysis, where expenses are netted against deposits) at all (couldn't find any so far, neither in budgets as discussed nor in categories)?

**Comment by totti4ever** [comment]
Sorry to bother every reader, but I'm just curious whether I missed it somewhere or there is just no way to see any netted sums besides the deltas on the asset account overview?

**Comment by JC5** [comment]
Could you use the reports under /reports?

**Comment by totti4ever** [comment]
Okay, I had a look on all of them and I think, the _category_ report should suit my needs if I do without budgets (which is kind of sad, see above :-) ). It's a pity though that the time series graph again doesn't provide a netted view. 

Isn't this something you could generally introduce to graphs where there are revenues and expenses shown already today to offer an option to show a netted bar instead?

**Comment by JC5** [comment]
Yes, it's something I'm looking at in the new layout.

**Comment by totti4ever** [comment]
Okay, I'm still having no clue why it is such a strange thing to have income considered in budgets, I understand that it won't be part of this software, but having the chance to have a view on netted sums by category would also help a bit.

Thanks for the discussion. I'm closing this as there is new point accepted
