### ISSUE TITLE
Error after upgrade to 5.4.5

### ISSUE THREAD

**Issue by Chouille** [firefly-iii/firefly-iii#4041]
**Bug description**
I am running Firefly III version 5.4.5, and my problem is:
Error on connect ; syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

After upgrade to version 5.4.5, i followed the composer instructions in the documentation.

**Steps to reproduce**

**Extra info**

Ubuntu Linux 18.04.3

In log file : 

[2020-11-07 17:43:14] local.ERROR: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at /var/www/firefly-iii/app/Http/Controllers/Controller.php:42)
[stacktrace]
#0 /var/www/firefly-iii/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/www/firefl...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('FireflyIII\\\\Http...')
#2 /var/www/firefly-iii/app/Http/Controllers/DebugController.php(45): spl_autoload_call('FireflyIII\\\\Http...')
#3 /var/www/firefly-iii/vendor/composer/ClassLoader.php(444): include('/var/www/firefl...')
#4 /var/www/firefly-iii/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/www/firefl...')
#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('FireflyIII\\\\Http...')
#6 [internal function]: spl_autoload_call('FireflyIII\\\\Http...')
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(809): ReflectionClass->__construct('FireflyIII\\\\Http...')
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build('FireflyIII\\\\Http...')
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('FireflyIII\\\\Http...', Array, true)
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('FireflyIII\\\\Http...', Array)
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('FireflyIII\\\\Http...', Array)
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(253): Illuminate\\Foundation\\Application->make('FireflyIII\\\\Http...')
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(970): Illuminate\\Routing\\Route->getController()
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(931): Illuminate\\Routing\\Route->controllerMiddleware()
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\\Routing\\Route->gatherMiddleware()
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/firefly-iii/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#39 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#40 {main}
"}

**Comment by JC5** [comment]
It looks like you're not running PHP 7.4, which is the minimum version required for Firefly III v5.4.5

**Comment by Chouille** [comment]
Thanks for your reply.
I running 
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )

**Comment by JC5** [comment]
Sometimes Apache is still using older libraries. Could you verify?

**Comment by Chouille** [comment]
Thanks JC5, i solved my issue. I have many php version in my server.
I followed this article (in french, sorry) in order to configure a specific php version by site on apache
.
https://www.digitalocean.com/community/tutorials/how-to-run-multiple-php-versions-on-one-server-using-apache-and-php-fpm-on-ubuntu-18-04-fr
