### ISSUE TITLE
Rules cannot be dragged between groups

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4042]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:
Rules cannot be dragged into a new group (or out of a group in general). This applies to rules not currently in groups and rules that currently are. The behavior does exist for bills, which is why I am confused. Instead of going into the new rule group they just end up at the bottom of the list.

**Steps to reproduce**

1. Have at least 1 rule and 1 group that the rule is not in.
2. Try to drag the rule into the group and find that it does not work.

**Extra info**

Debug information generated at 2020-11-07 21:59:44 America/New_York for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-11-30 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot. (Sorry)
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Indeed, you can't. Not sure if it's a bug or just not a target for a droppable. I'll check it out :+1:

**Comment by JC5** [comment]
I'm closing this and tracking this elsewhere so it can be part of the efforts for the new layout.
