### ISSUE TITLE
What does "what's playing?" mean?

### ISSUE THREAD

**Issue by somasis** [firefly-iii/firefly-iii#4043]
This is a pointless question, but I was wondering, what does "what's playing" actually mean? It doesn't really make sense to me in the context of the dashboard, so I was wondering if there's some sort of inside joke or some other meaning to it.

**Comment by JC5** [comment]
It’s just like “what’s going on?”

**Comment by somasis** [comment]
Huh. Is that regional at all? I've never heard of that (coming from a US perspective) I guess.
