### ISSUE TITLE
Error messages not fixed in EN-GB

### ISSUE THREAD

**Issue by andyshilton** [firefly-iii/firefly-iii#4044]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:
The issue https://github.com/firefly-iii/firefly-iii/issues/4006 does not appear to be working.
I originally thought it was to do with fix only being applied to EN_US, however I've tested it on the demo site and found that it doesn't matter if I pick EN_US, or EN_GB in the preferences, it still say "....errors below".

**Steps to reproduce**

![image](https://user-images.githubusercontent.com/16556349/98465807-74fcdc80-21c3-11eb-9984-26c90645ac21.png)
![image](https://user-images.githubusercontent.com/16556349/98465815-85ad5280-21c3-11eb-9cf1-5582015d6f65.png)

![image](https://user-images.githubusercontent.com/16556349/98465899-0d935c80-21c4-11eb-89d4-d64139851f06.png)
![image](https://user-images.githubusercontent.com/16556349/98465911-1f74ff80-21c4-11eb-8538-953fc33af3a4.png)

**Comment by JC5** [comment]
I probably forgot to generate the correct JS files. The translations are in place, the frontend never picket them up. It'll be part of the next release for sure.

**Comment by andyshilton** [comment]
Thanks @JC5  I did wonder if it was something simple like that.
