### ISSUE TITLE
Error message for "Amount Missing" doesn't have a look up value

### ISSUE THREAD

**Issue by andyshilton** [firefly-iii/firefly-iii#4045]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:
If you forget to enter an amount when creating a withdrawal, when you click submit, the error message does not have a value to look up so instead it displays "transactions.0.amount"

**Steps to reproduce**

- Create a withdrawl
- do not enter an Amount
- click submit
- notice the error message
**Extra info**

I have tested this in EN_GB and Czech (to test if it's a language issue) and it appears on both.

![image](https://user-images.githubusercontent.com/16556349/98466127-70392800-21c5-11eb-8088-f026d2b4c900.png)
![image](https://user-images.githubusercontent.com/16556349/98466114-5ac3fe00-21c5-11eb-9565-f372aaebc383.png)

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
That's the correct value. Part of the joys of Laravel.

**Comment by andyshilton** [comment]
It is the correct value? I would have expected it to use the field name. Eg "The Amount field is required" or "Betrag Feld muss ausgefult sein" and "Amount" and "Betrag" are the displayed field names?

**Comment by JC5** [comment]
I know what you mean. I'll do some digging. It used to be so that Laravel supported the replacement of "amount_field" to something user friendly like "the amount".

In this case however it's "transactions.*.amount" where the asterisk can be anything from 0 to 100. Laravel never supported a replacement for such a field. Which is why you see "transactions.0.amount". This might be changed but don't hold your breath.

**Comment by andyshilton** [comment]
Ah OK. I understand what you mean. So, could it potentially not have the amount (the *) in it so it could just be a replaceable string so it could point out the field, not the value?

**Comment by JC5** [comment]
Exactly. But as it turns out, it's no longer unsupported. Will be fixed in the next release. Thanks for pushing me in the right direction.
