### ISSUE TITLE
Add  tag

### ISSUE THREAD

**Issue by siccovansas** [firefly-iii/firefly-iii#4048]
**Description**
In bulk edit mode you can easily add tags to multiple transactions. This isn't possible using the list edit mode. I often want to edit tags and categories, but can't do this on a bulk basis so using the list mode for this would be perfect!

**Solution**
Add a tag column to the mass/list edit mode

**What are alternatives?**
Manually open each individual transaction to easily add categories and tags

**Comment by JC5** [comment]
Sorry, this is not going to change.
