### ISSUE TITLE
Unable to browse CSV-Import tool

### ISSUE THREAD

**Issue by Chouille** [firefly-iii/firefly-iii#4051]
I am running Firefly III version 5.4.5.

**Description**
Problem with CSV Importer.
I following self hosted instructions. When i try to browse the tool, i have a 403 Forbidden page.

In the apache vhost log file ; 

`Cannot serve directory /var/www/csv-importer/: No matching DirectoryIndex (index.php,index.html,index.cgi,index.pl,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
`

**Extra info**

My vhost config is : 

`<VirtualHost *:80>

	ServerName csvimport.xxxx.xxx
	DocumentRoot "/var/www/csv-importer"

	<FilesMatch \.php$>
      	# For Apache version 2.4.10 and above, use SetHandler to run PHP as a fastCGI process server
      	SetHandler "proxy:unix:/run/php/php7.4-fpm.sock|fcgi://localhost"
    	</FilesMatch>

	<Directory "/var/www/csv-importer">
		allow from all
		Options None
		AllowOverride All
		Require all granted
	</Directory>

	#Logging Management
	ErrorLog /var/log/apache2/error.csvimport.log
	CustomLog /var/log/apache2/access.csvimport.log combined

</VirtualHost>
`

**Comment by JC5** [comment]
Directory should be csv-importer/public

**Comment by Chouille** [comment]
Many thanks, it works ! :)
