### ISSUE TITLE
Firefly III docker setup

### ISSUE THREAD

**Issue by Rhino4293** [firefly-iii/firefly-iii#4052]
I am trying to set up Firefly to be accessible outside my home. I have a nginx proxy set up on another VM and firefly is running in a docker container.  I am able to access Firefly via the IP address with no issues and I can get to the login screen of firefly via the URL but it wont let me log in. If I click on I forgot password it tries going to the IP address instead. 

in the .env I have `TRUSTED_PROXIES=**`
In my Nginx Proxy conf for this subdomain:
```
server{
        server_name budget.domain.com;
        location /{
             proxy_pass http://192.168.2.212:8070/;
             proxy_set_header X-Forwarded-Proto $scheme;
        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/budget.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/budget.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
```

Am I missing something?

**Comment by Rhino4293** [comment]
I update my proxy config to:

```
        location /{
             proxy_pass http://192.168.2.212:8070/;
             proxy_set_header X-Forwarded-Proto $scheme;
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $remote_addr;
             proxy_set_header Host $host;
}
```
and it seems to be working now

**Comment by JC5** [comment]
Glad to hear it works now! :+1:
