### ISSUE TITLE
(Some) attachments have disappeared

### ISSUE THREAD

**Issue by EmilyMaryon** [firefly-iii/firefly-iii#4053]
I am running Firefly III version 5.4.6.

**Description**
Some (but not all) of my attachments seem to have disappeared from the file system, resulting in a not found error from firefly. I'm not entirely sure if this is something to do with my setup/something I've done wrong, though I cannot possibly think what that could have been, or a bug with the newest version, but any help would be appreciated! Regardless, thanks again for the great bit of software!

EDIT: To clarify, this is running in a docker container with a mounted volume, and I've never seen that kind of behaviour before from any of my other apps.

**Extra info**
 

Debug information generated at 2020-11-09 19:41:45 Europe/London for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 2d17b3d7-5dee-4f6b-98e1-55ef7b5354c9 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_GB |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-11-01 00:00:00 |
| Session end | 2020-11-30 23:59:59 |
| Session first | 2020-07-25 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0 |

```
Nov 9 19:34:46 2ef99c70912f firefly local.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"Could not find the indicated attachment. The file is no longer there.","time":"Mon, 09 Nov 2020 19:34:46 +0000","file":"\/var\/www\/html\/app\/Http\/Controllers\/AttachmentController.php","line":244,"code":0,"version":"5.4.6","url":"FIREFLYDOMAIN\/attachments\/view\/17","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:82.0) Gecko\/20100101 Firefox\/82.0","json":true}  
Nov 9 19:34:46 2ef99c70912f firefly local.ERROR: Could not find the indicated attachment. The file is no longer there. {"userId":1,"exception":"[object] (FireflyIII\\Exceptions\\FireflyException(code: 0): Could not find the indicated attachment. The file is no longer there. at /var/www/html/app/Http/Controllers/AttachmentController.php:244)
```
![Screenshot_2020-11-09_19-51-26](https://user-images.githubusercontent.com/29664150/98589465-37807800-22c5-11eb-8543-cba42a73205f.png)

**Comment by JC5** [comment]
Nothing has changed to the attachment handling code in many moons. Whatever changed, it's not Firefly III I'm afraid. Could it be that the file is still there but just not accessible?

**Comment by krisshurley** [comment]
I have exactly the same problem. But seems to apply to all my attachments after the last firefly upgrade

**Comment by JC5** [comment]
1. From which version to which version did you upgrade?
2. Are the files physically gone?

**Comment by EmilyMaryon** [comment]
In my case it was 4.5.5 to 4.5.6, and yes the files did physically disappear. Many thanks, partly glad to know it wasn't just something wrong with my machine/setup.

**Comment by JC5** [comment]
I have no clue what could have happened.

**Comment by JC5** [comment]
With Firefly III's user base as it is today this is either a very exotic bug or a user mistake.

I need more info. I assume you have backups? That would make repeating the process a good way to find out what happened.
