### ISSUE TITLE
Budget report is crashing

### ISSUE THREAD

**Issue by lguima** [firefly-iii/firefly-iii#4055]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

When I try to get a **Budget report** an exception is thrown.

**Steps to reproduce**
- Access the reports (`/reports`) page
- Select the Report type "Budget report"
- Select some accounts (more than one) for Included accounts
- Select the September 2020 month (2020-09-01 - 2020-09-30)
- Select some budgets (more than one) for Extra options
- Submit the report

**Extra info**
![firefly-budget](https://user-images.githubusercontent.com/1562097/98878929-0047cd80-2463-11eb-8936-a8888a1aee68.PNG)

![firefly-budget-exception](https://user-images.githubusercontent.com/1562097/98879485-6c770100-2464-11eb-89ff-a21b0b0a4ba0.PNG)

Debug information generated at 2020-11-11 21:15:54 America/Sao_Paulo for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | a8acc75e-9fb8-4049-b9d5-eba02610014f |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-11-01 00:00:00 |
| Session end | 2020-11-30 00:00:00 |
| Session first | 2018-06-11 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36 |

```
TypeError

Typed property FireflyIII\Generator\Report\Budget\MonthReportGenerator::$expenses must be array, Illuminate\Support\Collection used
```

**Bonus points**
- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for reporting!

**Comment by totti4ever** [comment]
That fix works, tested on docker@develop
