### ISSUE TITLE
Transfer between 2 accounts shows as 2 transfers

### ISSUE THREAD

**Issue by bartekd123** [firefly-iii/firefly-iii#4057]
I am running Firefly III version 5.4.6.

**Description**
I have 2 accounts that I do a transfer between. I use csv importer to import those, and based on the notes (which shows account number) I change it to a transfer, and set the destination/source account. Because the transfer appears twice (since I am importing both accounts), it is doubling the transfers for the account. 

Is there a workaround that I can do so the 2 transfers are merged, or duplicates are ignored based on value and date alone?

**Extra info**
example of the transactions:

Account 1 (account number 2345):
Date,Transaction,Name,Memo,Amount
11/11/2020,CREDIT,Recurring Internet Deposit from ,SPOINT From 1234,50

Account 2 (account number 1234):
Date,Transaction,Name,Memo,Amount
11/11/2020,DEBIT,Recurring Internet Withdrawal to,SPOINT To 2345,-50

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/16650162/99020052-bbd43480-252b-11eb-85ca-96668e7cdbae.png">

**Comment by JC5** [comment]
You'll have to make sure the descriptions are the same, and then maybe the duplicate detector will pick it up.

**Comment by bartekd123** [comment]
Thanks James. I tried that. Changed my rules to set the description the same. I even tried making the rule delete the notes just in case that was contributing to it. I deleted the transfers and re-added them using csv import.

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/16650162/99082604-5ff0c680-2592-11eb-9857-eb2a11626662.png">


Any other ideas? I can maybe create the rule to delete one or the other, but I want to avoid that just in case there are any misses.

**Comment by JC5** [comment]
It's about the original content I'm afraid. Rules that change the transaction afterwards don't count. You'll have to set up something to change the transaction content before it's submitted to Firefly III.

**Comment by bartekd123** [comment]
Thanks again @JC5  
I don't want to play with the CSV file before injecting it using CSV uploader. Ill just create rules to delete the transactions for either transfer in or transfer out. This question can be closed. Thanks for your help!

**Comment by JC5** [comment]
No worries! If anything comes up, you know where to find me :+1:
