### ISSUE TITLE
fr: mark piggy banks as inactive

### ISSUE THREAD

**Issue by 7596ff** [firefly-iii/firefly-iii#4058]
I would like Firefly to display piggy banks as inactive, and to disclude them from gross piggy bank statistics at the bottom of the overview page. Currently, I have my inactive banks in a seperate category, but this does not disclude them from counts.

**Comment by JC5** [comment]
So you have piggy banks on inactive accounts, and you want the piggy banks removed from the overview?

**Comment by 7596ff** [comment]
No. I have piggy banks on active accounts. When I've saved enough for the item the piggy bank is for, I want to drain it, mark it as inactive while keeping the savings data and having it no longer count against the "left to save" and "total" amounts.

**Comment by JC5** [comment]
Sorry, this is not going to change.

**Comment by 7596ff** [comment]
That's a strange stance to take because other items in this application have inactive statuses, like accounts, budgets... It seems like a missing or incomplete feature to have a piggy bank be always active, and when their purpose has been served, it is strange that the only option is to delete the bank and lose data. I ask that you elaborate on why this is a wontfix.

**Comment by JC5** [comment]
Their purpose is to be there until the money is spent. Being active or inactive is pointless. There’s no functional difference. The piggy bank being full or not is enough.

**Comment by 7596ff** [comment]
But there is a difference! The real-life piggy bank has a linear progression. Money is deposited over time to save up for a good or service. Once the money is saved, it is spent, and therefore removed from the piggy bank. It no longer represents the item that was being saved up for. 

Firefly's piggy banks do not follow this linear progression: Money is deposited, data is displayed to show how much money is left to deposit, a suggested amount per month to deposit, and a sum of all the piggy banks and their difference. Once the bank is full, the money in it is spent (removed). However, the still active bank tells the user that it must be filled up again! This makes no sense. If banks were able to be deactivated, they would better fit the real life object and rationale that they are supposed to represent.

**Comment by JC5** [comment]
So you delete the piggy bank.

**Comment by 7596ff** [comment]
Thus deleting all the data the bank contains, the log of additions and subtractions from the bank, the purchase linked to it. It makes no sense to tell people to intentionally destroy data.

**Comment by somasis** [comment]
I'm inclined to agree, deleting the piggy bank when filled feels counter intuitive. Though, maybe it might make more sense to designate them *complete* rather than *inactive*?

**Comment by 7596ff** [comment]
With more thought, is your intention to leave the bank full after the money is spent? This seems nice aesthetically, but it does not play nice with the "Left for piggy banks" number. I have got around this by changing the saving account to an account with no money in it.
