### ISSUE TITLE
Transfers between asset account and saving account always seem positive

### ISSUE THREAD

**Issue by gerbenvandijk** [firefly-iii/firefly-iii#4071]
I am running Firefly III version 5.4.6, and I ran into some issues with rules and savings accounts.

I am using the ING bank. These banks do support CSV export and this is working great, but savings accounts are done a bit different than normal. The deposits and withdrawals from there are only recognisable by a number in the description field.

So to be able to see my savings in Firefly III too, I tried to created two rules:

- One that checks outgoing transfers for a certain account number, and then changes it to a deposit from the savings account
- One that checks for incoming transfers for a certain account number, and then changes it to a withdrawal to that savings account

<img width="963" alt="Screenshot 2020-11-18 at 19 57 55" src="https://user-images.githubusercontent.com/1520354/99575859-81f6a880-29d9-11eb-83d2-29f716f8023e.png">

These rules did not have the desired result (they did nothing at all it seemed). I believe that might be because the transactions were deposits and transfers already(?).

So i changed them to instead set the destination and sources accounts instead. Even though the input field matched the name of my savings account; the transfers were not moved to that account, but instead ended up in new expenses and revenue accounts with the same label as my savings account.

<img width="1390" alt="Screenshot 2020-11-18 at 20 12 40" src="https://user-images.githubusercontent.com/1520354/99576601-7ce62900-29da-11eb-84b9-fd42131f35f0.png">
<img width="1135" alt="Screenshot 2020-11-18 at 20 12 07" src="https://user-images.githubusercontent.com/1520354/99576635-88d1eb00-29da-11eb-89b6-20e0b85c55cb.png">

Then I changed these rules to a transfer to that savings account. That did give the desired result. But now in the overview of that savings account; there is no indication if the transfer was positive or negative. The calculations of the totals are correct though.

<img width="958" alt="Screenshot 2020-11-18 at 19 58 26" src="https://user-images.githubusercontent.com/1520354/99575920-9dfa4a00-29d9-11eb-80c7-60a76911d6b2.png">
<img width="958" alt="Screenshot 2020-11-18 at 19 58 26" src="https://user-images.githubusercontent.com/1520354/99576352-2678ea80-29da-11eb-89ea-125057c39507.png">

Am I not understanding how to work with rules and savings accounts, or did I stumble into some bugs? I'm happy to help out with debugging and fixing the issue.

**Extra info**
All my client info: http://supportdetails.net/B8VBY7BX
Output from /debug page:

Debug information generated at 2020-11-18 20:14:45 Europe/Amsterdam for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 532e3b90-05f2-4faa-a8ce-6c3eea26470d |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-11-01 00:00:00 |
| Session end | 2020-11-30 00:00:00 |
| Session first | 2020-10-20 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 |

- [x] - I searched and nobody reported this bug before
- [ ] - I have added a stack trace from my log files
- [x] - I have added a screenshot.
- [ ] - I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Hi! Thanks for a very expansive bug report. I know that importing CSV files can be difficult so congrats on the success of your efforts 😁 

What you see in the lists is as expected, and it's not a "bug" per se. It's on my list to make sure the display of transfers is correct for the view you're in. Like in your example, you want the view to show plus or minus correctly.

However, the code that handles the list of transactions currently isn't aware that it's being used on an account page: it's not taken into the context. This is great for preventing spaghetti code but bad for usability.

You will see that transfers are *always* shown as a positive amount. It's something I hope to fix in the new layout.

**Comment by gerbenvandijk** [comment]
@JC5 thanks for the insanely fast reply! Related to this; it also seems that because of this missing context, I can also not use these amounts in piggy bank related rules (which would be the next step for me as the saving accounts on ING can be split up into actual piggy banks). Is this correct or is there another way to do this?

**Comment by JC5** [comment]
That could be an actual bug, let me check it out. It should be possible to add an action that triggers on a piggy bank, even though the action may fail later on.

**Comment by JC5** [comment]
I can't replicate that. I assume the piggy bank exists?

**Comment by gerbenvandijk** [comment]
Yes the piggy bank exists, I will try it with a clean install tomorrow as with this one i've been importing and clearing data a lot.

It seems related to `app/Validation/FireflyValidator.php:295`, when I simply `return true;` this validation message disappears, but the rule still doesn't work as I expected.

It seems like the field is meant to have a number, where I expected it to add or subtract the amount of that transaction to that specific piggy bank. Could you clarify?

**Comment by JC5** [comment]
The field requires a piggy bank name. This will only work when:

- the transaction is a transfer
- the piggy bank exists as a piggy bank (not as an asset account or savings account)
- the piggy bank is related to the source or destination of the transfer.

In the mean time, I'll do some experiments to see what happens when you convert transactions.

**Comment by gerbenvandijk** [comment]
The transfers in question meet all the requirements, but were converted. Also I did make a new transaction manually that matched the rule criteria; but also in that case the rule would not let me save.

So I set `app/Validation/FireflyValidator.php:295` to `return true`, simply to be able to save the rule and debug this further. Without doing that, I was not able to save and always see `This value is invalid for the selected action`, regardless if the rule matched only imported or only manually created transfer transactions, or a mix of both. This even happens when there are no transactions whatsoever in the system yet (after clearing all data).

With this change it indeed would let me save the rule, but when I run it, the converted transfer transactions did not get processed accordingly; and also the manually created transfer transactions were not processed. So at this point the problem seemed to be in the saving of the rule, not the actual processing of it. There seems to be no difference between manually created and converted transfer transactions.

When digging in and tinkering, I realised that the balance of the connected saving account also matters. In my case I had the opening balance set to 0. Which was correct (I move money in and out of that piggy bank regularly). In my scenario; sth like this happened and I wanted my piggy bank to reflect that:

- opening balance 0 on the savings
- transferred 50 from personal to savings
- transferred 50 from savings to personal
- end result 0 again on the savings

When I then did set an opening balance of €1000 to the savings account; the saving of the rule still did not work. But when I then changed `app/Validation/FireflyValidator.php:295` to `return true`, saved the rule, reverted the code change and then ran the rules again, something happened but I got some rather unexpected results:

**The transactions that match the rule:**
<img width="1792" alt="Screenshot 2020-11-19 at 11 05 56" src="https://user-images.githubusercontent.com/1520354/99651994-924d6880-2a57-11eb-9ed5-2d2419afc186.png">

**The result on the piggy bank:**
<img width="1792" alt="Screenshot 2020-11-19 at 11 01 28" src="https://user-images.githubusercontent.com/1520354/99652041-9da09400-2a57-11eb-8a10-961a681c0651.png">

As you can see, the transaction from the 13th is missing on the piggy bank even though it matches the rules, and the grey lines in the piggy bank are ghost lines and they should not be there.

**Some relevant logs:**
```
[2020-11-19 10:58:52] local.WARNING: Amount left is zero, stop.  
[2020-11-19 10:58:52] local.WARNING: Cannot add 100.000000000000 to piggy bank.  
[2020-11-19 10:58:52] local.WARNING: Amount left is zero, stop.  
[2020-11-19 10:58:52] local.WARNING: Cannot add 50.000000000000 to piggy bank.  
[2020-11-19 10:58:52] local.WARNING: Cannot add 50.000000000000 to piggy bank.  
[2020-11-19 11:00:24] local.WARNING: Amount left is zero, stop.  
```

Summarising, I seem to be having issues with both getting piggy bank rules to save, and with the initial balance on the savings account that is connected to them. I could be completely wrong and miss something basic here, would love to get to the bottom of this :smiley:

This is all on a clean database. If it would help, we could setup a screen share so you can look at my environment in detail.

Another thing that I realised, is that right now it is not possible to set an opening balance on a piggy bank. Is this something you would consider adding?

**Comment by gerbenvandijk** [comment]
Btw; I'm getting the exact same results on the [demo site](https://demo.firefly-iii.org/rules/create/):

<img width="1677" alt="Screenshot 2020-11-19 at 16 13 10" src="https://user-images.githubusercontent.com/1520354/99684885-3cda8100-2a82-11eb-890f-830b3de37d4e.png">

**Comment by JC5** [comment]
I pushed a fix for the piggy banks. My bad, old code. It should respond properly on names again. I'll check out what happens when withdrawals are turned to transfers, and then trigger a piggy bank action.

> Another thing that I realised, is that right now it is not possible to set an opening balance on a piggy bank. Is this something you would consider adding?

Nah. Just set it after you create it.

> Also; why do the fields work with names; rather than ID's? Isn't that complicating things a lot?

Sure, but it's a lot more user friendly to use names.

**Comment by JC5** [comment]
Oh, and I see that the code would create two events. Also fixed!

**Comment by gerbenqikker** [comment]
> > Also; why do the fields work with names; rather than ID's? Isn't that complicating things a lot?

> Sure, but it's a lot more user friendly to use names.

100% agree, but isn't it better to show the names in the UI, but store the type of account (piggy bank, savings, expenses etc) and the account ID in the database? This way you are always 100% sure that when a user wants so save to "piggy_bank" with ID "2", that happens rather than saving to account with the name "clothes" since this one might exists as both an expense and piggy bank?
> I pushed a fix for the piggy banks. My bad, old code. It should respond properly on names again. I'll check out what happens when withdrawals are turned to transfers, and then trigger a piggy bank action.

Thanks so much! I'll switch to the dev branch over the weekend and let you know the results. 👍 

> Nah. Just set it after you create it.

Thanks!

**Comment by gerbenvandijk** [comment]
> I pushed a fix for the piggy banks. My bad, old code. It should respond properly on names again. I'll check out what happens when withdrawals are turned to transfers, and then trigger a piggy bank action.

Thanks so much! I'll switch to the dev branch over the weekend and let you know the results. 👍 

> Nah. Just set it after you create it.

Thanks!

> > Also; why do the fields work with names; rather than ID's? Isn't that complicating things a lot?

> Sure, but it's a lot more user friendly to use names.

100% agree, but isn't it better to show the names in the UI, but store the type of account (piggy bank, savings, expenses etc) and the account ID in the database? This way you are always 100% sure that when a user wants so save to "piggy_bank" with ID "2", that happens rather than saving to account with the name "clothes" since this one might exists as both an expense and piggy bank?

**Comment by JC5** [comment]
> This way you are always 100% sure that when a user wants so save to "piggy_bank" with ID "2", that happens rather than saving to account with the name "clothes" since this one might exists as both an expense and piggy bank?

In this case, no. The rest of the DB is filled with references to ID's, but actions and triggers are stored text based. Of course each trigger and action is linked to a rule by ID, but the `type` and the `value` are text. For the type, this makes sense. Actions like "set_budget" and "add_tag" can be stored as text and don't need their own table. It would be [proper normalization](https://en.wikipedia.org/wiki/Database_normalization#Normal_forms) to do so but there are limits.

For the action value, I choose to do this using text. For example, `add_tag` could be accompanied by the text `TagX`. Even if the tag doesn't exist or is deleted, this will just happen. In the case of piggy banks, this is also what happens, although the piggy bank will *not* be recreated if it's missing.

For accounts (when using the action `convert_to_x`) the ID of the account is less than ideal because it could be that either the expense, revenue or asset account is required, depending on the context. Furthermore, in some cases the account can be created when it doesn't exist.

> the name "clothes" since this one might exists as both an expense and piggy bank?

The action type will always tell Firefly III what to look for.
