### ISSUE TITLE
How to keep track of outgoing loans?

### ISSUE THREAD

**Issue by Thomas14** [firefly-iii/firefly-iii#4072]
I am running Firefly III version 5.4.6.

**Description**
_First of all I would just like to say, thank you for creating and maintaining Firefly III! It has really changed my way of thinking about money for the better and I absolutely love using it._

Imagine that I have just borrowed €100 to a friend. My friend repays me in several installments. In order to keep track of the loan I create a liability with a negative opening balance (as suggested by the official documentation). How do I transfer money to this liability each time my friend pays me?

I have tried to simply create a standard deposit transaction as the money enters my checking account, and then create a secondary transaction with the source left blank (cash) and the target destination set to the liability. Then link these two transactions together to help keep track. The problem with this approach is that the secondary transaction is considered an additional income by Firefly III and thus will be listed on my income statement as such.

I also cannot set the target destination to the liability as that is not where the actual money went; it went into my checking account so that's where it should be in Firefly as well.

Is there something like a standardized way to keep track of this or perhaps a better approach I could try?

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by JC5** [comment]
Right now, this is a gap in Firefly III. You'd want the loan's opening balance to lower (or raise, depending on your perspective) when your friend deposits money into the loan. Right now, this isn't the case yet. But on my list to fix!

**Comment by pkwalker00** [comment]
One way to track the loan is as an asset.
-Create an asset account called "Name of Borrower - Loan"
-Transfer the money from your checking/savings/wallet account from where you lent the money to the asset account. (i.e. 100 from checking to "Name of Borrower - Loan")
- When you receive a payment from your friend, transfer the amount of their payment from the asset account back to your checking/savings/wallet account
-When you are fully repaid the balance of the "Name of Borrower - Loan" account will be zero.

In this way, you can track the remaining loan balance.  If for some reason your friend skips out on paying you back, then you would transfer the remaining balance to an expense account called "bad loans" or "bad friends" or whatever makes sense to you.

**Comment by azzamsa** [comment]
My way of tracking loans and debt. I don't know if this is the correct way. 

Types of liability account:
- *debt*: I get money **from** john and I should pay him back.
- *loan*: I give money **to** john and he should pay me back.

**debt**
1. Create a liability account, named john. with a *debt* type. and 0 as the initial balance
2. Create a transaction from `liability/john` to `asset/wallet`. Now I have an amount in my `asset/wallet` to make the next purchase of goods. `liability/john` becomes -$10, and `asset/wallet` +$10
3. (If I make payments to John) Create a transaction from `asset/wallet` to `liability/john`. Now `liability/john` becomes $0 again.

**loan**
1. Create a liability account, named john. with a *loan* type. and 0 as the initial balance
2. Create a transaction from `asset/wallet` to `liability/john`. `liability/john` becomes +$10, and `asset/wallet` -$10
3. (If john makes a payment) Create a transaction from `liability/john` to `asset/wallet`. Now `liability/john` becomes $0 again.

---

Inspired by https://github.com/firefly-iii/firefly-iii/issues/2351#issuecomment-515033569, @JC5 doesn't comment on this. So I assume that way is acceptable.

Similar issue:
- https://github.com/firefly-iii/firefly-iii/issues/2351
- https://github.com/firefly-iii/firefly-iii/issues/3473
- https://github.com/firefly-iii/firefly-iii/issues/631
- https://github.com/firefly-iii/firefly-iii/issues/1907

**Comment by JC5** [comment]
Very cool! I'll spend some time on it tonight. This is very useful input for the changes I want to make. Nice work, and thanks for sharing :+1:

**Comment by JC5** [comment]
Fixed in the new release.
