### ISSUE TITLE
Unraid Docker "This site can’t be reached"

### ISSUE THREAD

**Issue by JakeLadson** [firefly-iii/firefly-iii#4073]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

When trying to access the site I am getting site can't be reached error.

![image](https://user-images.githubusercontent.com/26978529/99677120-f9aaee80-2a3e-11eb-992f-b289842c6ee0.png)

**Steps to reproduce**
The install I have was an old version, 4.something, and today I had to update to a newer version. I tried with a fresh install and am getting the same issue. 

**Extra info**
Running on docker in Unraid. Searched high and low and could not find anything. There are no new logs from the last couple of days. 
Here are my container variables:
![image](https://user-images.githubusercontent.com/26978529/99677621-86ee4300-2a3f-11eb-878c-d33643c80989.png)

**Comment by JC5** [comment]
Firefly III runs on port 8080, not port 80. I'm not sure which template you're using but it's out of date. The export share is also no longer used.

**Comment by JakeLadson** [comment]
Fewwww! Alright, it's back. I downloaded the new container and it worked this time. I think there were some issues with the docker config on unraid but now it's good to go. I was using the old official template.
