### ISSUE TITLE
Internal Server Error after installation

### ISSUE THREAD

**Issue by 3isenHeiM** [firefly-iii/firefly-iii#4074]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is: **Internal Server Error after installation**

I can't get any web page.

I'm installing it on a shared hosting, meaning I've not access to the `apache.conf` file.
I have no error during installation and everything looks smooth.
However, when I navigate to the page, I have this HTTP error :
```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at postmaster@XXX to inform them of the time this error occurred,  and the actions you performed just before this error.
More information about this error may be available in the server error log.
```

Browsing to the server error logs revealed this (filtered with identical entries) : 
```
[Thu Nov 19 17:15:30 2020] [error] [client X.X.X.X] [host XXXX] AH02429: Response header name '[2020-11-19 17' contains invalid characters, aborting request
```
I've read that this error comes from a space in a header parameter (the value `[2020-11-19 17` containing the timestamp), making the server refuse to give the response (more info https://serverfault.com/a/853150 ).
I've search the repo to find the exact line where the timestamp gets appended to the header response, but I haven't found it.
I suspect that this is taken in charge by the dependencies (artisan or laravel)...

**Steps to reproduce**
Install the latest version on a shared hosting (without access to `apache.conf`)

**Extra info**

| Scope | Version |
| --- | --- |
| PHP | 7.4.8 |
| Host | Linux |

I cannot get other value since I can't even browse to any page.

**Comment by 3isenHeiM** [comment]
I've got the same error when installing the csv-importer tool.
Where can I raise the issue ? It's not possible on the project's repo :/

**Comment by JC5** [comment]
Like it says in the repository description of the CSV importer, this is the place for CSV importer questions as well. 

> I've search the repo to find the exact line where the timestamp gets appended to the header response, but I haven't found it.
I suspect that this is taken in charge by the dependencies (artisan or laravel)...

Firefly III doesn't add the time stamp to headers at all, as far as I'm aware. The default Docker image also uses Apache without any problems. This makes me believe the problem maybe elsewhere. 

How did you install the dependencies on shared hosting?

Could you enable debug mode? How to do this is described in the documentation. See the link below. It should give you more information on the error. 

https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode

**Comment by 3isenHeiM** [comment]
The PHP dependencies are installed by the provider itself since it's a shared hosting space.
I had also to remove the dependency of `adldap2` since it's not offered by the provider (as explained here : https://github.com/firefly-iii/firefly-iii/issues/2944#issuecomment-570231733 thanks !)

I will enable the debug mode and check if I can get more info.

However, by downgrading to version `5.3.3` I haven't got any problem.

**Comment by 3isenHeiM** [comment]
Debug mode enabled.
Audit log in `/storage/logs` : 
```
[2020-11-20T11:33:13.746035+01:00] local.INFO: AUDIT: Show login form (1.1). (X.X.X.X -> GET:https://<URL>/login) [] []
```
This is when I try to have the homepage.

The webserver error logs show the same error : 
```
[Fri Nov 20 11:33:14 2020] [error] [client X.X.X.X] [host <URL>] AH02429: Response header name '[2020-11-20T11' contains invalid characters, aborting request
```

**Comment by JC5** [comment]
That means that Firefly III was at least successful in generating the login page; ie. it "works". 

Change the value of `.env` value `LOG_CHANNEL` to `daily`, see if that helps.

**Comment by 3isenHeiM** [comment]
Still the same behavior.

**Comment by JC5** [comment]
Then I don't know. The format of the header suggests that Apache is trying to output log content as header content. A typical log line (as demonstrated by you) looks like this:

```
[2020-11-20T11:33:13.746035+01:00] local.INFO: AUDIT: Show login form (1.1). (X.X.X.X -> GET:https://<URL>/login) [] []
```

Which coincides with Apache's error here.

It looks like Apache is pushing content from stdout to the browser, or is at least trying to parse it as content. That's a config error on your end I'm afraid. On my side, I've added some settings that can disable log-output to stdout for both audit and normal logging (this isn't possible for audit logs right now).

A manual fix is in logging.php. On [this line](https://github.com/firefly-iii/firefly-iii/blob/main/config/logging.php#L95) change "info" to "emergency".

**Comment by 3isenHeiM** [comment]
Changing [this line](https://github.com/firefly-iii/firefly-iii/blob/main/config/logging.php#L95) like you proposed solved the issue : 
```
   'stdout_daily'     => [
     'driver' => 'single',
     'path'   => 'php://stdout',
     'tap'    => [AuditLogger::class],
-    'level'  => 'info',
+    'level'  => 'emergency',
   ],
```
Thanks for the fix !
