### ISSUE TITLE
Problem with LDAP

### ISSUE THREAD

**Issue by Typhonragewind** [firefly-iii/firefly-iii#4075]
**Bug description**
I am running Firefly III version 5.4.6 in a docker container, and my problem is:

I've successfully configured Firefly to connect to my LDAP (OpenLDAP) instance and was able to login with my account without problem. However, if i try any other account in the LDAP system I get this error:
![Screenshot 2020-11-20 130355](https://user-images.githubusercontent.com/7875917/99846629-a041dd00-2b6e-11eb-8473-dcff3d455b76.png)

This seems to be connected to the mail field in LDAP that is not being correctly imported into the database. However, every account tested had the mail field correctly setup with a valid email.

**Steps to reproduce**
I don't know how to reproduce this outside my system since my LDAP has nothing special.

**Extra info**
Some logs:
https://pastebin.com/wn3Bnqij

**Bonus points**

- I searched and nobody reported this bug before - To the best of my ability
- I have added a stack trace from my log files  Yes
- I have added a screenshot. -> Yes

**Comment by JC5** [comment]
Could you share your LDAP related config variables?

**Comment by Typhonragewind** [comment]
> 
> 
> Could you share your LDAP related config variables?

Of course, here it is (minus sensitive info):
```
        # LDAP connection configuration
        # OpenLDAP, FreeIPA or ActiveDirectory
        # # If you use Docker or similar, you can set this variable from a file by appending it with _FILE
        - ADLDAP_CONNECTION_SCHEME=OpenLDAP
        - ADLDAP_AUTO_CONNECT=true

        # LDAP connection settings
        # You can set the following variables from a file by appending them with _FILE:
        # ADLDAP_CONTROLLERS, ADLDAP_PORT, ADLDAP_BASEDN
        - ADLDAP_CONTROLLERS=192.168.1.xx
        - ADLDAP_PORT=389
        - ADLDAP_TIMEOUT=5
        - ADLDAP_BASEDN="cn=Users,dc=my,dc=ldap,dc=com"
        - ADLDAP_FOLLOW_REFFERALS=true

        # You can set the following variables from a file by appending them with _FILE:
        - ADLDAP_ADMIN_USERNAME=cn=admin,dc=ldap,dc=atiesh,dc=space
        - ADLDAP_ADMIN_PASSWORD=mypassword

        # You can set the following variables from a file by appending them with _FILE:
        - ADLDAP_ACCOUNT_PREFIX=cn=
        - ADLDAP_ACCOUNT_SUFFIX=,cn=Users,dc=my,dc=ldap,dc=com

        # LDAP authentication settings.
        - ADLDAP_PASSWORD_SYNC=false
        - ADLDAP_LOGIN_FALLBACK=false

        - ADLDAP_DISCOVER_FIELD=cn
        - ADLDAP_AUTH_FIELD=cn

        # field to sync as local username.
        # You can set the following variable from a file by appending it with _FILE:
        - ADLDAP_SYNC_FIELD=displayName
```

**Comment by JC5** [comment]
Mmm. I assume that `displayName` is a valid field with content etc.?

**Comment by Typhonragewind** [comment]
> 
> 
> Mmm. I assume that `displayName` is a valid field with content etc.?

I thought so, but i double checked and now i feel like an idiot.

I changed the displayName to something else and now it seems to work fine for all accounts.
The email thing in the sql error did throw me off balance.

Thank you so much for the help and patience!

**Comment by JC5** [comment]
No worries, glad to hear it works!
