### ISSUE TITLE
Can't open webpage of Bunq Importer via Docker image

### ISSUE THREAD

**Issue by jeffreytigch** [firefly-iii/firefly-iii#4077]
I am trying to use the bunq importer by using the run-hosted.sh file locally. It seems to go fine, but when I try to open the page (on localhost:8082), Chrome responds with "ERR_EMPTY_RESPONSE". I don't see any access or error log entries when trying to connect. This is the only information I get while running the container:

```
Now in entrypoint.sh (v1.3) for the Firefly III Bunq importer.
Please wait for the container to start...
Firefly III bunq importer v2.0.3
PHP: cli 7.4.12 Linux
Will now run Apache web server:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Sat Nov 21 12:04:52.377256 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Sat Nov 21 12:04:52.377346 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

I feel like it should work and this is an issue on my side, but I tried different ports, versions and env's to see if anything changes (spoiler: it doesn't). I couldn't test out 2.0.2, because it's gone from Docker Hub.

Am I getting crazy, or does someone has an idea or suggestion what's going on?

**Comment by JC5** [comment]
What's your configuration look like?

**Comment by jeffreytigch** [comment]
I am using Docker (Desktop, 2.5.0.1) on Mac (10.15.7). Firefly III does work fine (with the docker-compose file). Does that give you enough info, or do you need more specifics?

**Comment by JC5** [comment]
I think the configuration you're using is set to the wrong port. If you have it configured to `8082:80`, change it to `8082:8080`.

**Comment by jeffreytigch** [comment]
Yes, thanks! That's it. I wanted to return the favour of helping out by fixing it in the docs, but it seems you've already done it. :) 

Have a good weekend!

**Comment by JC5** [comment]
Yeah I forgot to update the docs, sorry about that. Glad to see it works!
