### ISSUE TITLE
Spectre - What data should Spectre return?

### ISSUE THREAD

**Issue by bafplus** [firefly-iii/firefly-iii#4078]
I have succesfully installed the Spectre importer.
But the date returned from Spectre is quite "simplistic" and before i contact Spectre i would like to know if this is normal or not.
The only info i get returned from Spectre is (taken from downloads folder):

- (Spectre)account number
- Date
- Currency
- Amount
- Description

So in short the very basic.
There is no oposing data available so you cant "connect" transactions in Firefly because that data is simply not available.
Should Spectre return more data like oposing acount number and name for example?
Should i contact Spectre to see if they can pull more data from my bank or is this just how Spectre works?

**Comment by JC5** [comment]
It totally depends on Spectre I'm afraid. What they return from each bank is very different. More banks suffer this problem. In your case, it might be that this is just how Spectre works.

**Comment by bafplus** [comment]
Thanks @JC5 , I will contact Spectre in that case then. If Spectre pulls more data should that work right away or are changes to the Spectre Importer needed to accomodate that extra data?

**Comment by JC5** [comment]
It should work out of the box.
