### ISSUE TITLE
Cannot set opening balance to 0

### ISSUE THREAD

**Issue by SignumPL** [firefly-iii/firefly-iii#4079]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

When I set opening balance for an asset account to zero and click Save, then success message is displayed, but opening balance is not updated.

**Steps to reproduce**

1. Edit asset account
2. Change opening balance to 0
3. Click save

**Extra info**
Debug information generated at 2020-11-22 10:02:11 Europe/Warsaw for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 000c1de6-bdcd-477b-a2e3-0ac9ce87f4df |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-11-01 00:00:00 |
| Session end | 2020-11-30 23:59:59 |
| Session first | 2016-05-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | pl_PL |
| Attempt at "pl_PL.utf8" | 'pl_PL.utf8' |
| Attempt at "pl_PL.UTF-8" | 'pl_PL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0 |

**Bonus points**

- I searched and nobody reported this bug before
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thx for letting me know! If you clear the date as well, it should work for now as a workaround.

**Comment by SignumPL** [comment]
It doesn't allow me to clear the date, I get the error: `The opening balance date field is required when opening balance is present.`

**Comment by SignumPL** [comment]
Clearing both fields worked, thanks.
