### ISSUE TITLE
[csv-import] Where to store the "Pre-made configuration file" ?

### ISSUE THREAD

**Issue by 3isenHeiM** [firefly-iii/firefly-iii#4086]
I am running CSV-import version v2.0.0.

**Description**
In the **Import routine** page there is a field where you can select a "Pre-made configuration file".
I guess it's a json file relative to the bank CSV parsing scheme.

I'd like to store this on the server, but I can't find the folder in which to put it.

Additional question : how to integrate these schemes : https://github.com/firefly-iii/import-configurations ?

**Comment by JC5** [comment]
Good question. This isn't properly documented, but you can do either of two things:

- Store the files in `storage/configurations`
- Mount the `/var/www/html/storage/configurations` directory in Docker somewhere local, and store them.
- Change the `JSON_CONFIGURATION_DIR` to any custom directory (mount it if you want to), and place them there.

I'll make sure this will be part of the docs.

**Comment by 3isenHeiM** [comment]
Yep indeed, adding the json file to `storage/configurations` (on a shared hosting space) did it.

Thanks for the quick support !

**Comment by JC5** [comment]
Docs are updated :+1:
