### ISSUE TITLE
Trying to setup recurring transaction for mortgage payment...

### ISSUE THREAD

**Issue by whitwhittle** [firefly-iii/firefly-iii#4087]
I am running Firefly III version x.x.x.

I've gotten Firefly up and running in a Docker container, and have started setting up accounts.  I've setup a Liability for the Mortgage, and have an account where the money is automatically transfered (its at same bank) setup as well..

When I attempt to setup the transfer, I get an error message that I can't use the selected account (Mortgage account) as the destination account...  Wondering what i'm missing, or if this is a bug..

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot

![image](https://user-images.githubusercontent.com/27792008/100106857-a960d180-2e2e-11eb-97e3-d212c4689bb7.png)

**Comment by JC5** [comment]
Select withdrawal as the transaction type, that should work.
