### ISSUE TITLE
"(no description)" transaction group title from YNAB import

### ISSUE THREAD

**Issue by Kurokha** [firefly-iii/firefly-iii#4088]
**Bug description**
I am running Firefly III version 5.4.6 and imported transactions from YNAB with the importer version 2.0.3. This had the title of every transaction group set to "(no description)", which resulted in every transaction being labeled as "(no description):transaction description here" on the front page:

![grafik](https://user-images.githubusercontent.com/74882969/100134117-ffae2e80-2e87-11eb-9410-b274cadde398.png)
Transaction descriptions are chopped off for discretion, the (empty discriptions) are correct since they did not have a description in YNAB and have not been updated so far. The first transaction was manually entered directly in Firefly. In that case the group title is set to NULL instead, which then is not shown in the frontend.

There is no way to properly fix this in the frontend. I could have edited every transaction, added a split, entered a transaction group title, saved and then deleted the extra split. In the end I just edited the table directly:
`UPDATE transaction_groups SET title = NULL WHERE title = '(no description)';`

I'd expect the YNAB importer to set the group titles accordingly or have Firefly treat a "(no description)" title the same way as a NULL title and not show it in the frontend.

**Steps to reproduce**
Import a transaction from YNAB that is not a split transaction.

**Comment by JC5** [comment]
Thanks, nice find. I've pushed a fix to the "develop" branch and the "develop" Docker image for the YNAB import, which is now queued to be built. I believe that will solve the issue.

If you could verify this for me, I'd be much oblidged.

**Comment by Kurokha** [comment]
Can confirm. The YNAB import doesn't create group titles for single transactions anymore.
