### ISSUE TITLE
[csv-import] cURL error 7: Failed to connect on port 443: Connection refused

### ISSUE THREAD

**Issue by 3isenHeiM** [firefly-iii/firefly-iii#4089]
**Bug description**
I am running Firefly III version 5.4.6 and CSV-import version 2.0.0 and my problem is :

When trying to import a CSV file, the registration to the FF instance is OK, and when the import tool starts, it fails after some time.

The error message is the following : 
```
Line #0: Internal error: GuzzleException:
   cURL error 7: Failed to connect to <FIREFLY> port 443:
   Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
   in file <CSV-import>/app/Services/Import/Task/Accounts.php:257
```
I can curl from a terminal to <FIREFLY>:443 without problem.
Moreover, I've seen the following lines in the logs : 
```
[2020-11-25 08:52:49] local.DEBUG: Going to search account with IBAN "XXXXX"  
[2020-11-25 08:52:50] local.DEBUG: [a] Found asset account #1 based on IBAN "XXXXX"  
[2020-11-25 08:52:50] local.DEBUG: Result of findByIBAN is not null, returning: 
```
So this indicates that the **CSV-importer can properly talk with the API** (at least fecthing the IBAN), so the comm is alright.

Since my instance runs on a shared hosting space, is there a mean to log all API requests made by the CSV-importer ?
I'm searching through the provider logs, but I can't see them.

**Steps to reproduce**
Try to import a CSV

**Extra info**
Both Firefly and CSV-import are in separate subdomains on the same shared hosting space.
But since the token is properly registered, I believe that the communication between the importer and firefly doesn't pose any problems.

Here is the error returned : 
![Screenshot from 2020-11-25 10-20-00](https://user-images.githubusercontent.com/26417172/100207507-f49ae300-2f07-11eb-8190-71fecc788333.png)

**Comment by JC5** [comment]
Mmmm no clue. The logs for the importer should be in storage/logs

The intermittent failure points to something on your end. Is there anything in the logs, those from Firefly III or your web server?

**Comment by JC5** [comment]
Sorry, you said there were no logs. Tricky :(
