### ISSUE TITLE
Parse and display spaces in IBAN

### ISSUE THREAD

**Issue by 3isenHeiM** [firefly-iii/firefly-iii#4090]
**Description**
For increased readability, the IBAN could be parsed and spaces should be added when displaying them.
The syntax of an IBAN field is known and respected, so parsing it would be convenient.

I haven't test, but let's see I create an account, and in the IBAN field I leave the spaces (so the IBAN is BExx xxxx xxxx xxxx).
Then, when importing data, the field contains the IBAN, without spaces (BExxxxxxxxxxxxxx).

**Will these be matched ?**

Maybe for storing in the DB it's preferable to remove the space, but in the interface it's a nice feature.

Thanks again for the awesome support !

**Comment by JC5** [comment]
I'll pick it up for the next layout for sure :+1:

**Comment by 3isenHeiM** [comment]
And regarding the matching ? Will it be done (as we are speaking) even if one of them has spaces ?

**Comment by JC5** [comment]
Haha you even made it bold. But yes it’ll match :)

**Comment by JC5** [comment]
As with other issues, I'm tracking this eslewhere and cleaning up.
