### ISSUE TITLE
Graph on dashboard ineligible

### ISSUE THREAD

**Issue by jpldcarvalho** [firefly-iii/firefly-iii#4091]
I am running Firefly III version 5.4.6 on docker (official image).

**Description**
The graph in the initial dashboard is ineligible.

**Extra info**
I don't think OS is relevant since it's running on docker, I am using Brave browser to access the page. If I use Firefox or Chrome, it works just fine. The demo website also works in the Brave browser.

**Screenshot**
![image](https://user-images.githubusercontent.com/5263301/100338666-ca612800-2fd0-11eb-834b-5f9418557012.png)

**Debug page**

Debug information generated at 2020-11-26 11:08:48 Europe/Amsterdam for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | e8f1f006-9459-4ff5-8308-d534f3862d18 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-11-01 00:00:00 |
| Session end | 2020-11-30 23:59:59 |
| Session first | 2020-11-08 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 |

**Thank you very much for this awesome project!**

**Comment by JC5** [comment]
Sorry man, no clue. Is there anything auto-blocked in Brave? All libraries are local but you never know.

**Comment by jpldcarvalho** [comment]
Yes. It is blocking a fingerprinting attempt. Which is strange, since it works fine on the demo.
Anyway, if you reconfigure the shield, it will solve the problem.
Thank you!
