### ISSUE TITLE
Creation of tokens to access API

### ISSUE THREAD

**Issue by bsiebens** [firefly-iii/firefly-iii#4092]
I am running Firefly III version 5.4.6.

**Description**
I'm running Firefly III using docker behind a Traefik reverse proxy with forward authentication enabled:

`AUTHENTICATION_GUARD = 'remote_user_guard" / TRUSTED_PROXIES = "**" / AUTHENTICATION_GUARD_HEADER = "HTTP_X_FORWARDED_USER" / APP_URL = "https://firefly.domain.org"`

I can log in fine when visiting the URL as defined above. I also have the reverse proxy allow "https://api-firefly.domain.org" but with some IP whitelisting to only allow access from within my network and to pass that traffic through the forward authentication.

When I want to access the API I keep running into a login screen from Firefly itself, and as per the docs I tried creating a personal access token, but there is no option on my profile to create any of these (or an oath2 token for that matter).

<img width="1805" alt="Screenshot 2020-11-26 at 12 01 24" src="https://user-images.githubusercontent.com/20867475/100343281-73168400-2fdf-11eb-97dd-0550d2576325.png">

**Extra info**
Debug information generated at 2020-11-26 12:04:05 Europe/Brussels for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 5e284153-dcee-4282-9ca0-ae49022eec88 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-11-01 00:00:00 |
| Session end | 2020-11-30 23:59:59 |
| Session first | 2020-11-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15 |

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [x] I added a screenshot
- [x] I added log files 
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
At the moment this isn't possible. You'll never be able to create access tokens when you're deferring authentication management to a third party. 

The remote user guard (authelia?) must handle the authentication of calls to /api/v1. This could be a token, or a fingerprint or whatever. Firefly III will pick it up from there using the same remote user header as the normal Firefly III calls.

Disclaimer: I haven't tested this yet.

**Comment by JC5** [comment]
In the next release it will be possible to create tokens again when using a tool like Authelia. However, you must bypass authentication for the API paths so the tokens can actually be used. Otherwise, your authentication tool will intercept all calls.

Example config:

```
    - domain: example.com
      subject:
        - "group:fireflyiii"
      policy: one_factor
    - domain: example.com
      resources:
      - "^/api/v1/.*$"
      policy: bypass
```

**Comment by bsiebens** [comment]
Great!
