### ISSUE TITLE
Can't add rule with date triggers

### ISSUE THREAD

**Issue by jens108** [firefly-iii/firefly-iii#4093]
Hi there, loving firefly! I am running Firefly III version 5.4.3

I am trying to add a trigger to a rule that contains a date. However, I can't seem to get it to work, dates don't parse. I tried switching the language of firefly, also checked the locale settings of my browser. I tried various renderings:

01.10.2019
10.01.2019
01/10/2019
01-10-2019
2019-10-01
01 October 2019
October 01 2019
01 Oktober 2019
Oktober 01 2019
01. Oktober 2019

None of these seem to work, I always get an error that the data is invalid. In other places, firefly renders dates in the format of "01. Oktober 2019", which also doesn't work. Any idea how I can use dates in my automation rules?

![image](https://user-images.githubusercontent.com/11771169/100463467-2ceb1e80-30cc-11eb-9736-6abf58ccbe26.png)

**Comment by JC5** [comment]
https://docs.firefly-iii.org/advanced-concepts/rules

**Comment by jens108** [comment]
Thanks for the fast reply! The date 2019-10-01 doesn't work as well, but the link you posted suggests YYYY-MM-DD. What am I doing wrong?

![image](https://user-images.githubusercontent.com/11771169/100466422-2f03ac00-30d1-11eb-9cf5-9d15596cf7be.png)

**Comment by JC5** [comment]
Sorry, I missed that. Could you upgrade to the latest version just in case. We did have some issues with rule management earlier.

**Comment by jens108** [comment]
The update fixed it, thank you!
