### ISSUE TITLE
FR - CSV Auto-import look for files with extension CSV as well as csv

### ISSUE THREAD

**Issue by bartekd123** [firefly-iii/firefly-iii#4094]
**Description**
Minor FR request, when you are doing other improvements to csv import. My bank for some reason exports the transactions with a capital CSV as the extension. Because of this, I have to manually rename the file before using auto-import.

**Solution**
When using auto-import, can it look for files with .CSV extension as well? If I rename those to have an extension of .csv, they work

**What are alternatives?**
Manually renaming the file to .csv before running the import.

Thanks again for making firefly, it has been great to manage my accounts.

**Comment by JC5** [comment]
I didn't even know it wouldn't check that. Thanks for letting me know :D

**Comment by bartekd123** [comment]
No problem. Its one of those things that isn't a big deal at all, so if it is too much work, don't worry about it. But wanted to let you know. :)

**Comment by JC5** [comment]
Will be fixed in the next release :+1:
