### ISSUE TITLE
Database issue on installation

### ISSUE THREAD

**Issue by TheRealMephisto** [firefly-iii/firefly-iii#4095]
I tried installing Firefly III using the latest docker image, docker run command like in the installation help page.

Mariadb database is set up and user has all rights on the database.
When I run the container and navigate to the page in my browser, this is what I see:

FireflyIII
Whoops! An error occurred.

Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Could not poll the database: SQLSTATE[HY000] [2002] Connection refused (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)
More information

Please collect more information in the storage/logs directory where you will find log files. If you're running Docker, use docker logs -f [container]. You can read more about collecting error information in the FAQ.
Get help on GitHub

You're more than welcome to open a new issue on GitHub.

    Use the search!
    Include the information from this debug page.
    Tell us more than "it says Whoops!"
    Include error logs (see above).
    Tell us what you were doing.

I checked the FAQ and googled the error message, but only ended up on pages which I can't read: https://gathering.tweakers.net/forum/list_messages/1886887/5

Anybody here with a hint on how to solve that problem?

**Comment by erwinkloosterboer** [comment]
It looks like the docker container firefly is running on, is not able to access your database. You said that you installed firefly by executing the docker run commando's so i'm assuming you are not using docker-compose. 
How is mariadb installed? Another separate docker run cmd? Did you link the containers by adding them to the same docker network?

**Comment by TheRealMephisto** [comment]
Mariadb is not installed using docker, it was installed using "apt-get". As host I tried "localhost" as well as "127.0.0.1".

**Comment by JC5** [comment]
Neither will work when you're using Docker. Both refer to Firefly III itself (it's a matter of perspective).

You need something like this to set the correct IP for the maria DB on the host where Docker is.

https://nickjanetakis.com/blog/docker-tip-65-get-your-docker-hosts-ip-address-from-in-a-container

**Comment by TheRealMephisto** [comment]
Sounds reasonable. I tried it with both suggestions from the link you shared and still get the same error page, though

**Comment by erwinkloosterboer** [comment]
if you don't mind having the firefly port mounted directly to the host, you can add the argument `--net=host` to the docker run command. You should then be able to connect to `127.0.0.1:3306`

**Comment by TheRealMephisto** [comment]
So, like this?

docker run -d -v firefly_iii_upload:/var/www/html/storage/upload -p 81:8080 \
-e APP_KEY=MYKEY \
-e DB_HOST=HOSTIP \
-e DB_PORT=3306 \
-e DB_CONNECTION=mysql \
-e DB_DATABASE=MYDB \
-e DB_USERNAME=MYDBUSER \
-e DB_PASSWORD=MYDBPW jc5x/firefly-iii:latest --net=host

**Comment by erwinkloosterboer** [comment]
Almost, the `--net=host` argument is now passed as an argument in the docker container instead of an argument in the docker run cmd itself.

Also, the `-p` argument, routing the host's port 81 to container port 8080, will not work as the network will be mounted on the host, allowing you to connect to firefly on your host via http://localhost:8080


```
docker run -d -v firefly_iii_upload:/var/www/html/storage/upload
--net=host
-e APP_KEY=MYKEY
-e DB_HOST=HOSTIP
-e DB_PORT=3306
-e DB_CONNECTION=mysql
-e DB_DATABASE=MYDB
-e DB_USERNAME=MYDBUSER
-e DB_PASSWORD=MYDBPW jc5x/firefly-iii:latest
```

**Comment by 0xERR0R** [comment]
You can also use `host.docker.internal` as host name to access the host machine from a docker container, there is no need to use host network mode. See https://docs.docker.com/docker-for-windows/networking/#known-limitations-use-cases-and-workarounds for more details.

**Comment by TheRealMephisto** [comment]
@0xERR0R  would this also work on a linux machine?

**Comment by 0xERR0R** [comment]
I didn't try this, but I found a merged PR (host.docker.internal). You can also try to use `172.17.0.1` as host IP address

**Comment by TheRealMephisto** [comment]
Sadly did not get it to work on my machine :/ Tried installing it directly, that worked for me. But it still seemed unstable... Maybe will try again next year :)
