### ISSUE TITLE
Duplicate Transactions created thru Plaid Import despite matching data

### ISSUE THREAD

**Issue by JackPala** [firefly-iii/firefly-iii#4096]
I am running Firefly III version 5.4.6

**Description**
Plaid Importer has a bug in which certain banks can only import transactions once, resulting in the Database needing to be deleted to rerun the import, to fix this I created a crontab operation that removes the Plaid-Importer Sqlite DB file in the config directory, this works and results in the new transactions being imported. 

The issue that I'm having, is that although the CSV import method works well at detecting the duplicates, the Plaid Import may potentially be bypassing the duplicate detection? I'm not certain. I'm fairly new to PHP.

**Extra info**
The Duplicate Transactions have the same dates, same amounts, same tags, same external IDs, they appear to be completely identical, however because the database that the plaid importer uses to reference previously imported transactions has to be deleted in order for the import to run properly on its end, it seems to be able to create the duplicate transactions despite the information being identically. 

Is there a way to create a rule that just deletes the duplicate transaction if the external ID is the same as an existing transaction? It appears that would solve it and allow the Plaid Importer to work.

**Comment by JackPala** [comment]
Additionally, is there a way to make the API import behave like the CSV import where duplicates are not imported or deleted upon import?

**Comment by JC5** [comment]
I don't create or maintain the Plaid importer, so there's not much I can do about it.

How to make the API work like the CSV importer [is documented](https://api-docs.firefly-iii.org/#/transactions/storeTransaction). Add `error_if_duplicate_hash: true` to the array should fix it.

**Comment by JackPala** [comment]
Doing that seems to break importation in my instance all together, but I might also be using that addition to the array wrong (I'm very much a novice).

Is there a way to use rule-type handling of duplicates? Such as deleting new transactions upon successful import if the external ID already exists?

**Comment by JC5** [comment]
Can you show me what you tried to do?

**Comment by JackPala** [comment]
GNU nano 3.2                                                                                           firefly-plaid-connector.runtimeconfig.json                                                                                                      

{
  "runtimeOptions": {
    error_if_duplicate_hash: true,
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    }
  }

**Comment by JC5** [comment]
The JSON config I mention, `error_if_duplicate_hash: true`, must be part of the submissions to Firefly III. It's not something that belongs into the plaid configuration.
