### ISSUE TITLE
Search reports "Firefly III found 50 transactions in x.xxx seconds" even when it only finds one.

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4098]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is: When you run a search it firefly III it numbers the results in one of three ways:
1) "Firefly III found 0 transactions..."
2) "Firefly III found 50 transactions..."
![image](https://user-images.githubusercontent.com/21091510/100530287-1e7d2f80-31be-11eb-83e8-b5adca5d2467.png)
3) "Firefly III found more than 50 transactions..."

Could you please make it so that either it gives you the total number of transactions or says something like "50 or fewer." The wording is misleading otherwise.

**Steps to reproduce**

1) Have a group of 1-49 transactions that when you search, will only pull up those transactions.
2) Run a search that pulls up that group of transactions.
3) Notice the text.

**Extra info**

Debug information generated at 2020-11-28 21:15:59 America/New_York for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-11-01 00:00:00 |
| Session end | 2020-11-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks, fixed!
