### ISSUE TITLE
Broken function call in CSV-importer creates crash when trying to generate a token

### ISSUE THREAD

**Issue by Megamannen** [firefly-iii/firefly-iii#4100]
**Bug description**
I am running Firefly III version 5.4.6 and Firefly III csv-import version 2.2.4, and my problem is:

Issue in CSV-importer
Invalid method call in TokenController.php

**Steps to reproduce**
Try to generate a oath token in CSV importer

**Extra info**
This function uses an older parameter call list

https://github.com/firefly-iii/csv-importer/blob/f301db77253e00fadba2674c812573b8a021f1ed/app/Http/Controllers/TokenController.php#L133

Missing tokenUrl parameter before clientId
`return $this->redirectForPermission($request, $baseURL, $data['client_id']);`

Caused by this fix: https://github.com/firefly-iii/csv-importer/commit/eceb535d91c88485277008443009d05f256b1885

**Comment by JC5** [comment]
Nice, fixed in 2.3.1

**Comment by Megamannen** [comment]
Wow, that was speedy, is the docker image built and published automatically?
