### ISSUE TITLE
Help installing CSV-importer

### ISSUE THREAD

**Issue by Engr-AllanG** [firefly-iii/firefly-iii#4101]
Hello!. First, thank you very much for your application. I look forward to using it
I am running Firefly III version 5.4.6 and CSV-importer 2.2.4

**Description**
I have been trying to get csv-importer to work with Firefly III, and cannot get past a 500 internal service error when connecting with a client ID. 

- I am running ubuntu 20.04 containers via Proxmox 6.2-15
- Firefly is installed in a container with static IP 192.168.1.128 
- CSV-importer is installed in another container I duplicated from the firefly container. It has a static IP of 192.168.1.130.
- Both are using nginx

I can successfully log into firefly and everything seems to work fine. I can successfully connect to csv-importer as well, but when I put in a client ID and try and connect it goes to a grey 500 internal error.

At one point I had both CSV and firefly in the same container, and I used a local DNS server to map "csv.glover.home" and "firefly.glover.home" to 192.168.1.128, and used two server blocks in nginx. It worked as well as the current setup, with the 500 internal service error. 

Currently, I am not using the vanity url. As noted below, my power went out and waiting for power. I will add logs and setup screeshots

I created my own installation guide as I went because I had some trouble getting firefly to work the first time. I pasted by installation guide below in case it sheds light on the installation error. Once this is all ironed out, you could put the guide I wrote into the wiki if it might be useful for others

**Extra info**
Logs are in subsequent comments. Here is the server error
![image](https://user-images.githubusercontent.com/3161759/100549857-6f2a7200-322a-11eb-8f26-eda13183b015.png)

**Ubuntu Installation I used**
I followed [this ](https://computingforgeeks.com/setup-firefly-personal-finance-manager-on-ubuntu/)tutorial. It has a link to this tutorial for installing mariaDB. I copied all command into this note page, so follow the notes below and it should get it up and running! This will take about 1.5 hrs.

(Here is a link to the firefly-iii website installation instructions. I followed them the first time and had problems with apache and getting the webserver to work. To start, at least read through them once then follow the tutorial linked to above)

Container

First, create a 20.04 privileged container with 1 core,  1024 mb ram, and default 8GB hard disk space

Installation Instructions

apt update
apt upgrade
apt install nginx curl -y
apt install software-properties-common
#add-apt-repository ppa:ondrej/php
#apt update
apt install -y php7.4 php7.4-{cli,zip,gd,fpm,json,common,mysql,zip,mbstring,curl,xml,bcmath,imap,ldap,intl}

Check to see if its running
 php -v and systemctl status php7.4-fpm

Adjust some php settings
nano /etc/php/7.4/fpm/php.ini

use ctrl-w to search for and change or enable the following lines of code

memory_limit = 512M

[Date]
date.timezone = America/Los_Angeles

stop apache

systemctl stop apache2
systemctl disable apache2

backup nginx file

cd /etc/nginx/sites-enabled/
mv default{,.bak}

create firefly.conf in sites-enabled folder and then paste in the config below

nano /etc/nginx/sites-enabled/firefly.conf

```
server {
        listen       80 default_server;
        listen       [::]:80 default_server;
         #server_name  example.com;
        root         /var/www/html/firefly-iii/public;
        index index.html index.htm index.php;

        location / {
                try_files $uri /index.php$is_args$args;
        }

        location ~ \.php$ {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_read_timeout 240;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        }
    }

```
restart

systemctl restart nginx php7.4-fpm

If you get an error due to duplicate web servers, you need to remove the symbolic link in sites-available (ls -l) and then rm the link

Install mariaDB

apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
add-apt-repository 'deb [arch=amd64] http://mariadb.mirror.globo.tech/repo/10.5/ubuntu focal main'
apt update
apt install mariadb-server mariadb-client
mysql_secure_installation

test installation

mysql -u root -p

in the mysql shell, check version with the command in bold (yellow)

MariaDB [(none)]> SELECT VERSION();

while still inside the mariaDB shell:

CREATE DATABASE firefly_db;
CREATE USER 'fireflyuser'@'localhost' IDENTIFIED BY 'mypassword';
GRANT ALL PRIVILEGES ON firefly_db. * TO 'fireflyuser'@'localhost';
FLUSH PRIVILEGES;
exit;

cd ~
curl -sS https://getcomposer.org/installer -o composer-setup.php
sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer

test

composer -V

install firefly - change the version number in the command below to whatever the latest is

cd /var/www/html/
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 5.4.6

cd /var/www/html/firefly-iii
php artisan migrate:refresh --seed
php artisan firefly-iii:upgrade-database
php artisan passport:install

Make sure we have the right locale enabled (currency and language?) 

First check to see what is enabled. We want (en_US.utf8, en_US.UTF-8)

locale -a

nano /etc/locale.gen and uncomment the line en_US.utf8, en_US.UTF-8 

locale-gen
systemctl restart nginx php7.4-fpm

**Bonus points**

- I have read the FAQ  - **yes and have spent a few days googling, browsing reddit, and reading through issues here on git hub**
- I added a screenshot - **will add when power comes back on**
- I added log files  **will add when power comes back on**
- I was able to replicate the issue on the demo site. **no**
  **haha, I will contribute if I end up using firefly (very likely). No empty promises! I am willing and able to contribute month support to open source projects I have running**

**Comment by Engr-AllanG** [comment]
My issue is very similar to [this ](https://github.com/firefly-iii/firefly-iii/issues/3975)issue

**Comment by Engr-AllanG** [comment]
My Oath client ID is 10, and redirect URL is http://192.168.1.130/callback

**my CSV nginx config is:**

```
server {
        listen       80 default_server;
        listen       [::]:80 default_server;
       # server_name  firefly.glover.home;
        root         /var/www/html/csv-importer/public;
        index index.html index.htm index.php;

        location / {
                try_files $uri /index.php$is_args$args;
                autoindex on;
                sendfile off;
       }

        location ~ \.php$ {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_read_timeout 240;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        }
```

**My firefly nginx config is:**
```
server {
        listen       80 default_server;
        listen       [::]:80 default_server;
       # server_name  firefly.glover.home;
        root         /var/www/html/firefly-iii/public;
        index index.html index.htm index.php;

        location / {
                try_files $uri /index.php$is_args$args;
                autoindex on;
                sendfile off;
       }

        location ~ \.php$ {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_read_timeout 240;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        }
```


**I think the relevent csv-importer .env config is:**
`FIREFLY_III_URI=http://192.168.1.128`
vanity URL I left blank. I have tried quite a few combinations, all with the same result or didn't work at all

*csv log*
`[2020-11-29 09:55:42] local.DEBUG: Submitted data:  {"client_id":"10"}
[2020-11-29 09:55:42] local.ERROR: Argument 3 passed to App\Http\Controllers\TokenController::redirectForPermission() must be of the type string, int given, called in>
[stacktrace]
#0 /var/www/html/csv-importer/app/Http/Controllers/TokenController.php(133): App\\Http\\Controllers\\TokenController->redirectForPermission()
#1 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\TokenController->submitClientId()
#2 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#3 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(255): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#5 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\\Routing\\Route->run()
#6 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipel>
#8 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#9 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\>
#10 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#11 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pip>
#12 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#13 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\>
#14 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleS>
#15 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#16 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminat>
#17 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#18 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\>
#19 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#20 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack()
#23 /var/www/html/csv-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute()
`

**Comment by JC5** [comment]
Could you grab CSV importer version 2.3.1 please? That should fix that error.

**Comment by Engr-AllanG** [comment]
I will try that when I get back home! 

⁣-Allan

**Comment by Engr-AllanG** [comment]
@JC5 I just updated to 2.3.1 and got past the 500 server error! Thank you.
I now have a 502 bad gateway after the 'authorize' dialog, so something must be wrong with my nginx config. I'll likely not get back to debugging this for a few days. I'll report back when I get back to it.

Thanks!

**Comment by Engr-AllanG** [comment]
I checked my nginx logs and found I was getting the error
`upstream sent too big header while reading response header from upstream`

I solved it by adjust the buffers via a google search. My nginx config now looks like:
```
server {
        listen       80 default_server;
        listen       [::]:80 default_server;
       # server_name  _;
        root         /var/www/html/updated-csv-importer/public;
        index index.html index.htm index.php;

        location / {
                try_files $uri /index.php$is_args$args;
                proxy_buffer_size          128k;
                proxy_buffers              4 256k;
                proxy_busy_buffers_size    256k;
                autoindex on;
                sendfile off;
       }

        location ~ \.php$ {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_read_timeout 240;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+.php)(/.+)$;

        fastcgi_buffers 16 32k;
        fastcgi_buffer_size 64k;
        fastcgi_busy_buffers_size 64k;
        }

    }
```

**Comment by Engr-AllanG** [comment]
@JC5 would you like me to send you my ubuntu install instructions with nginx configs and everything (reformatted where needed from what I posted in my first comment)? Maybe it could help someone else

**Comment by JC5** [comment]
If you put it in a Gist on [gist.github.com](https://gist.github.com) I can link to it in the docs :+1:

**Comment by Engr-AllanG** [comment]
I've never used gist before. How is this?
https://gist.github.com/Engr-AllanG/34e77a08e1482284763fff429cdd92fa
https://gist.github.com/Engr-AllanG/e87f827092e3a6b876b912cd897428ae
-Allan

**Comment by JC5** [comment]
Looks great. Make sure its a ".md" file and not secret 😁

**Comment by Engr-AllanG** [comment]
@JC5 Ok try it now - Public and and .md.
Now I understand why it wasn't being formatted haha.

**Comment by JC5** [comment]
Thanks, both are part of the docs now!
