### ISSUE TITLE
Autocomplete Piggy Bank

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4105]
Hello James, there are autocomplete API for almost everything except piggy bank. Can we have it please? Thanks!

**Comment by JC5** [comment]
:+1:

**Comment by JC5** [comment]
Wait, this is already in place lol. 

Documentation is updated.

**Comment by emansih** [comment]
Hi. Swagger says that the YAML is valid even though it isn't. I assume you have not updated the YAML on your [server](https://api-docs.firefly-iii.org/firefly-iii-1.4.0.yaml) as I could not find the duplicate mapping in the source code. 


![image](https://user-images.githubusercontent.com/5896415/102049895-df91df80-3e35-11eb-97f0-57ae02fcd5c6.png)

**Comment by emansih** [comment]
I noticed that I am not supposed to do a PR on the YAML repo. Here is the offending lines https://github.com/firefly-iii/api-docs/blob/main/firefly-iii-1.4.0.yaml#L5719-L5757

**Comment by JC5** [comment]
I saw it yesterday, I'll push the fix asap.

**Comment by JC5** [comment]
Should be online again!

**Comment by emansih** [comment]
Thanks James
