### ISSUE TITLE
CSV import: configuration for amount number format

### ISSUE THREAD

**Issue by 0xERR0R** [firefly-iii/firefly-iii#4106]
**Description**
My bank exports transactions with localized (Germany) amount: e.g. 4.711,98 €
Firefly use "." as decimal character. Amount of 10,00 € (ten EUR) will be imported as 1000.
It would be nice, if user can configure the decimal separator and grouping character

**Solution**
2 new configuration parameters: decimal separator (default '.') and grouping character (default ',')
Firefly should remove grouping character and use configured decimal separator for parsing.

**Additional context**
In Europe ',' is used as decimal separator. In Germany "." is common used as grouping character: 1.000.000,00. In Switzerland, "'" is used as grouping character: 1'000'000,00

**Comment by JC5** [comment]
The CSV importer is perfectly capable of importing such amounts. I just tried a few transactions, and I've had no problems.

Here are some logs to illustrate what happens under the hood.

```
local.DEBUG: Now at column 3/4  
local.DEBUG: Now at column #3 (amount), value "4.711,98 €"  
local.DEBUG: ColumnIndex is 2  
local.DEBUG: Value is '4.711,98 €'  

local.DEBUG: getParsedValue will run Amount  
local.DEBUG: Created converter class Amount  
local.DEBUG: Start with amount "4.711,98 €"  
local.DEBUG: Stripped "4.711,98" away to "4.711,98"  
local.DEBUG: Decimal character in "4.711,98" seems to be a comma.  
local.DEBUG: Converted amount from "4.711,98 €" to "4711.98".  
local.DEBUG: Final NUMERIC value is: "4711.98"  
local.DEBUG: Stored column #3 with value "4711.98" and role "amount" in field "amount"  
```

If you could share your log files, I can see what happens.

**Comment by 0xERR0R** [comment]
Did you try with "10,00"?
I'll test it again today and post my logs.

**Comment by JC5** [comment]
Same results.

**Comment by 0xERR0R** [comment]
I just tried with following file:

```
Date;col1;col2;amount
10.11.2020;dummy;dummy;10,00 EUR
```

And simple configuration (date as Date, col1 as Description, amount as amount): result amount is 1000

It works with "10,00 €"

Log entries:

```
importer_1      | [2020-12-01 13:42:05] production.DEBUG: getParsedValue will run Amount
importer_1      | [2020-12-01 13:42:05] production.DEBUG: Created converter class Amount
importer_1      | [2020-12-01 13:42:05] production.DEBUG: Start with amount "10,00 EUR"
importer_1      | [2020-12-01 13:42:05] production.DEBUG: Stripped "10,00 EUR" away to "10,00 "
importer_1      | [2020-12-01 13:42:05] production.DEBUG: Decimal is still NULL, probably number with >2 decimals. Search for a dot.
importer_1      | [2020-12-01 13:42:05] production.DEBUG: No decimal character found. Converted amount from "10,00 EUR" to "1000".
importer_1      | [2020-12-01 13:42:05] production.DEBUG: Final NUMERIC value is: "1000"
importer_1      | [2020-12-01 13:42:05] production.DEBUG: Stored column #3 with value "1000" and role "amount" in field "amount"
```

**Comment by JC5** [comment]
Ah I see it, there's an extra space. Which bank is this?

**Comment by JC5** [comment]
OK this is fixed in the `develop` branch and in the `develop` image of the CSV importer. I'd appreciate it if you could test this for me.

**Comment by 0xERR0R** [comment]
Wow, that was fast. Thank you!

**Comment by 0xERR0R** [comment]
Just tested it with the real data -> works like a charm! Great job and thank you for this great tool!
