### ISSUE TITLE
Show only first 10 doesn't work

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#4107]
Hello,

In a default report, first click to display more than 10 records.
Then click show only 10 firsts... and nothing.

**Comment by JC5** [comment]
Which version?

**Comment by jlauwers** [comment]
Oops forgot to say that I'm using the last docker version.

**Comment by JC5** [comment]
Alright, which report and which type of block specifically? A quick check shows me they seem to work fine.

**Comment by jlauwers** [comment]
I tried default report with every account:

- monthly (2020-11-01 - 2020-11-30) 
- yearly report 2020

Income/expense/categories have the issue.

Tried with brave browser, chrome, firefox.

**Comment by JC5** [comment]
Thx. I can't replicate this. My own installation is on `develop` but I haven't touched those files in ages. All lists work fine for me in Firefox.
