### ISSUE TITLE
No more grouping in piggy banks dropdown

### ISSUE THREAD

**Issue by MarinBernard** [firefly-iii/firefly-iii#4109]
**Bug description**
I am running Firefly III version 5.4.6. I have created a few Piggy banks in 4 groups. After I renamed those groups, they're no longer displayed in the dropdown list of the transaction form.

**Steps to reproduce**
- Create a few piggy banks
- Add them to a few groups
- Rename the groups (via Classification > Groups)
- Try to create a new transfer: the piggy banks groups are no longer shown in the dropdown list

![screenshot](https://user-images.githubusercontent.com/12986051/100776256-9dfc4000-3404-11eb-8aaa-0cf8466bca51.jpg)

Note: I'm unable to restore the grouping so far, and thus cannot reproduce the issue. As a consequence, I'm not 100% sure that the renaming was the cause of the problem.

**Extra info**
````
Debug information generated at 2020-12-01 18:32:48 Europe/Paris for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 8c4f8dc0-212f-4be8-9972-d8e2d3359230 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | fr_FR |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | pgsql, sqlite |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-12-31 00:00:00 |
| Session first | 2020-02-11 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 |
````

**Bonus points**

- I searched and nobody reported this bug before: **yes**
- I have added a screenshot: **yes**
- I was able to replicate it on the demo site https://demo.firefly-iii.org/: **yes**

**Comment by JC5** [comment]
Indeed. The list doesn't use groups. A fix will be part of the new layout.

**Comment by MarinBernard** [comment]
My mistake: I confused the form for automatic transactions (which displays grouped piggy banks) with the one for transfers (which doesn't). Sorry for the noise!
