### ISSUE TITLE
Potential dark mode AdminLTE

### ISSUE THREAD

**Issue by andyshilton** [firefly-iii/firefly-iii#4110]
@JC5  I was having a look through the cards in the new project and saw you were looking for a dark mode of AdminLTE. I had this bookmarked from another project and didn't know if it would be helpful or not so I thought I'd share in case it is. Please close if not, just thought I'd help if I could :)

https://github.com/firefly-iii/firefly-iii/projects/6#card-50278947

https://github.com/anvyst/adminlte-skin-midnight

**Comment by JC5** [comment]
Thanks, I'll write it down!
