### ISSUE TITLE
Deleting a category after navigating back 2 times results in 404

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#4112]
Firefly III version 5.4.6 using Chrome 87.0.4280.67 / macOS 10.15.7 on the demo site. I think I've seen some variations of this, the "previous URL" being invalid after an action.

**Steps to reproduce**
1. Open Classification > Categories
2. Click on a category
3. Click "Show all transactions without grouping them by date."
4. Navigate back 2 times, ending up in the category list
5. Delete the category in step 2

**Actual**
Redirects to `/categories/show/<id>/all`, displaying the 404 page since the category is now gone

**Expected**
Probably the category list.

**Comment by JC5** [comment]
Nice, that's a bug.
