### ISSUE TITLE
Piggy Bank API Deletes Some Piggy Metadata

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#4113]
Version 5.4.6. Putting data to a piggy bank causes unexpected behavior. Steps to reproduce:

1. Create empty piggy bank. Assign start and end dates.Assign a group.
2. PUT to /api/v1/piggy_banks/{id}       {"current_amount":1}
3. Refresh firefly piggy bank page.
4. Observe that the piggy bank no longer has a group, and the piggy's end date has been reset.

**Comment by JC5** [comment]
Thanks, that shouldn't happen. Keep me posted if you see more things like this.

**Comment by 4e868df3** [comment]
Do you know if a new release is coming soon or would you recommend switching to the master branch to grab this patch?
