### ISSUE TITLE
Bunq importer

### ISSUE THREAD

**Issue by bartmaniac** [firefly-iii/firefly-iii#4117]
I am running Firefly III version5.4.6

**Description**

When opening the bunq importer v2.1.0 I get my different bunq accounts and as you can see only the first 5 accounts (those with the green text) are linked to the correct asset account in Firefly-iii although all of my bunq accounts are created in firefly-iii. Is there an explanation why all the other accounts are set to be imported to bunq Abonnementen? And do  have to change this each time?

**Extra info**
 

**Bonus points**

![Knipsel](https://user-images.githubusercontent.com/44246750/100946611-0da52480-3504-11eb-9f92-c4eddf24a042.PNG)

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
They will be set automatically when the IBAN's match.
