### ISSUE TITLE
Dashboard budget graph does not update

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4118]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

When I change the budgeted amount for a preexisting budget with existing transactions, that change is not reflected in the budget graph unless you log out and log back in.

I was going to try to do some pictures, but the demo site is super inconsistent with demonstrating this. I think it refreshes whenever someone else logs in. The behavior is definitely still there, though.

**Steps to reproduce**

1. Have a budget that has transactions already matched to it (so it shows up on your dashboard).
2. Go to the Budgets page.
3. Change the amount you've allotted to the budget from step 1.
4. Go back to the dashboard.
5. See that the budget graph has not changed.
6. Log out and log back in.
7. See that the budget graph has changed.

**Extra info**

Debug information generated at 2020-12-02 20:11:42 America/New_York for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 |

**Bonus points**

- [x] - I searched and nobody reported this bug before
- [ ] - I have added a stack trace from my log files 
- [ ] - I have added a screenshot.
- [x] - I was able to replicate it on the demo site https://demo.firefly-iii.org/ (kind of - I think the graph resets whenever somebody logs in to the site)

**Comment by JC5** [comment]
It could be a cache thing. Does it work when you browse to `/flush`?

**Comment by death2cupbots** [comment]
Clearing the cache does reset the graph and _occasionally_ it adjusts when I change it once, but other times I have to flush it every time I want it to change.

**Comment by JC5** [comment]
Alright. I'm not going to fix this, sorry. The new layout has a different cache mechanism and I'm expecting that will solve these issues.

**Comment by death2cupbots** [comment]
Ok that's fine. It's not a huge deal for me because I (usually) get my budgeting right the first time and set it up before the start of the month. It's been a little hectic the past couple of weeks so I didn't start on it until Tuesday, so that's probably the only reason I noticed it.

**Comment by JC5** [comment]
:+1:
