### ISSUE TITLE
CSV importer ignores configuration JSON

### ISSUE THREAD

**Issue by fl2ma** [firefly-iii/firefly-iii#4119]
**Bug description**
I am running Firefly III in docker on jc5x/firefly-iii:latest in combination with the CSV importer (fireflyiii/csv-importer:latest). This is a new installation that I'm configuring for the first time.

Managed to set up both firefly and the importer successfully, communication between the containers works. 

The CSV importer ignores the configuration JSON file (e.g. header, separator, etc.)

**Steps to reproduce**

- Open CSV importer Web UI
- select one of the previously uploaded JSON files
- select a CSV file
- click "Upload"
-> JSON config is ignored; when proceeding with the import this leads to an error

**Extra info**
Docker on Ubuntu 20.04 host, Firefox/83.0 

**Bonus points**
fireflyiiicsv_1  | [2020-12-03 15:52:27] production.DEBUG: User selected a config file from the store.  
fireflyiiicsv_1  | [2020-12-03 15:52:27] production.DEBUG: Now in ConfigFileProcessor::convertConfigFile  
fireflyiiicsv_1  | [2020-12-03 15:52:27] production.ERROR: Syntax error  
fireflyiiicsv_1  | 172.18.0.1 - - [03/Dec/2020:14:52:27 +0000] "POST /import/upload HTTP/1.1" 302 1529 "http://localhost:8081/import/start" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"

**Comment by JC5** [comment]
Could you run your JSON file through [jsonlint.com](https://jsonlint.com) and verify that it's correct?

**Comment by fl2ma** [comment]
You got me there, made a mistake when downloading the file from github.
A correct JSON leads to correct options in the second screen (separators, columns, etc.)

Thanks for the fast reaction and sorry for not checking that in advance.
