### ISSUE TITLE
I can not enable 2FA for user accounts within Firefly III

### ISSUE THREAD

**Issue by robpedersendev** [firefly-iii/firefly-iii#4120]
I am running Firefly III version 5.4.6

**Description**
Within the Firefly III preferences screen, there is no option to set up or force all users using this to use 2FA. I installed this using Cloudron and a VPS

![image](https://user-images.githubusercontent.com/40696979/101065168-102e6b00-3552-11eb-897c-807a09a4f617.png)

**Extra info**
 

Debug information generated at 2020-12-03 17:43:08 Europe/Amsterdam for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 83d86322-900c-4c2c-a22d-2de0af37236f |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite, sqlsrv |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | ldap  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2020-12-02 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0 |

**Bonus points**

X I have read the FAQ at https://bit.ly/FF3-FAQ
X I added a screenshot
X I added log files 
X I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Nope, there isn't.

**Comment by JC5** [comment]
Whoops, that was too fast. When you use an external identity provider, 2FA is disabled. It doesn't have to be, I'll check it out :+1:

**Comment by JC5** [comment]
You won't be able to enforce it for all users, or make it mandatory for them to use it.

**Comment by robpedersendev** [comment]
> 
> 
> Whoops, that was too fast. When you use an external identity provider, 2FA is disabled. It doesn't have to be, I'll check it out 👍

OK, cool. Thank you. 

> 
> 
> You won't be able to enforce it for all users, or make it mandatory for them to use it.

Darn, is there any way to change this? 

Maybe I just need to look into enforcing 2fa through cloudron

**Comment by JC5** [comment]
> Darn, is there any way to change this?

Not really, or at least it needs a lot of work. I'll need to build a flow for new users to scan the code and allow 2FA etc. It's a lot of work, and I'm focusing on the new layout atm. 

I use Authelia myself these days, might be something to look into.

**Comment by robpedersendev** [comment]
> Authelia

Wow! Thats a neat service!
