### ISSUE TITLE
Erroneous message when changing currencies

### ISSUE THREAD

**Issue by robpedersendev** [firefly-iii/firefly-iii#4121]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is: Erroneous message for non-admin users when they update their currencies
![image](https://user-images.githubusercontent.com/40696979/101065565-8a5eef80-3552-11eb-86c6-314f98cb94a8.png)

**Steps to reproduce**

Under Options/Currencies, I have the test account select a curreny and mark as default. The page loads, the currency is set, but I get the message "Message: Please ask mail@example.com to add, remove or edit currencies." in a blue box at the top of the screen.

**Extra info**

Windows 10
Firefox
Debug information generated at 2020-12-03 18:33:34 Europe/Amsterdam for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 83d86322-900c-4c2c-a22d-2de0af37236f |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite, sqlsrv |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | ldap  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 3 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0 |

**Bonus points**

X I searched and nobody reported this bug before
X I have added a stack trace from my log files 
X I have added a screenshot.
X I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
The message is designed to be there. You need to be admin to add, remove or edit currencies. I'll make it more clear in the new layout :+1:

The email address on display can be set in [your environment variables](https://github.com/firefly-iii/firefly-iii/blob/main/.env.example#L8).

**Comment by robpedersendev** [comment]
Even when you change your default currency?

**Comment by robpedersendev** [comment]
> 
> 
> The message is designed to be there. You need to be admin to add, remove or edit currencies. I'll make it more clear in the new layout 👍
> 
> The email address on display can be set in [your environment variables](https://github.com/firefly-iii/firefly-iii/blob/main/.env.example#L8).

Thank you for this, this solved it

**Comment by JC5** [comment]
> Even when you change your default currency?

Yes, but the user experience is pretty bad so it deserves a better format in the new layout.

**Comment by robpedersendev** [comment]
Understood, ok. This can be closed if that is better for you.

Thanks for the quick reply
