### ISSUE TITLE
How do I remove a reconciliation account?

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4122]
I am running Firefly III version 5.4.6.

**Description**

So today I started to enter my credit card payments and I noticed that as I started to enter one of my accounts in to the destination account field, it suggested a reconciliation account as well. This is really confusing to me as I don't think I've ever needed to make a reconciliation account and I'm pretty sure it wasn't there last month.

The real issue is, I have no way to diagnose this. I cannot get the reconciliation account to come up in a search even after I've made a test transaction and I cannot find it through browsing my account history.

This is the only account that has a reconciliation account associated with it.

Is there any way I can get it to stop  coming up on my suggested accounts list?

**Extra info**
 
Debug information generated at 2020-12-04 07:56:17 America/New_York for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.98 Safari/537.36 |

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
They shouldn’t pop-up when selecting accounts. I’ll pick it up.
