### ISSUE TITLE
Duplicated transactions imported using firefly-csv-importer

### ISSUE THREAD

**Issue by VictorAtPL** [firefly-iii/firefly-iii#4124]
Hello,

Thank you for developing this app.

**Bug description**

I am running Firefly III version 5.4.6 and Firefly CSV Importer version 2.3.1. I try to import following the same CSV row twice. I expect that the second time there should be error about duplicate thrown. I troubleshooted this problem and these are my findings:

For the first and second time another json requests are sent to Firefly /transaction API PUT method.
1.
```
{
  "group_title": null,
  "error_if_duplicate_hash": true,
  "transactions": [
    {
      "type": "withdrawal",
      "date": "2020-11-05 00:00:00",
      "currency_id": null,
      "currency_code": "PLN",
      "amount": "30.000000000000",
      "description": "HIDDEN",
      "source_id": 53,
      "source_name": null,
      "destination_id": null,
      "destination_name": 20,
      "invoice_date": "2020-11-05 00:00:00",
      "external_id": "20/11/05/8513/1",
      "notes": "",
      "destination_iban": "HIDDEN",
      "original_source": "jc5-csv-import-v2.3.1",
      "tags": [
        "Przelewy wychodzace"
      ],
      "source_iban": null,
      "source_number": null,
      "source_bic": null,
      "destination_number": null,
      "destination_bic": null
    }
  ]
}
```

2. 
```
{
  "group_title": null,
  "error_if_duplicate_hash": true,
  "transactions": [
    {
      "type": "withdrawal",
      "date": "2020-11-05 00:00:00",
      "currency_id": null,
      "currency_code": "PLN",
      "amount": "30.000000000000",
      "description": "HIDDEN",
      "source_id": 53,
      "source_name": null,
      "destination_id": 54,
      "destination_name": null,
      "invoice_date": "2020-11-05 00:00:00",
      "external_id": "20/11/05/8513/1",
      "notes": "",
      "destination_iban": null,
      "original_source": "jc5-csv-import-v2.3.1",
      "tags": [
        "Przelewy wychodzace"
      ],
      "source_iban": null,
      "source_number": null,
      "source_bic": null,
      "destination_number": null,
      "destination_bic": null
    }
  ]
}
```

We can see the differences in `destination_id`, `destination_iban` and `destination_name` fields. In my scenario, the first import creates an account, and in the second request the created account is found and is used in the latter request.

This is physically one transaction, but in both imports it treated as new, because of this change in `destination_id` and `destination_name`.
The request is sent to Firefly and in function `createJournal` of `TransactionJournalFactory` there is hash generated from the row which is sent in request. If there is already calculated hash stored in some database, then `DuplicateTransactionException` is thrown.

I think this mechanism should be reimplemented.
`$row['import_hash_v2'] = $this->hashArray($row);`
As we can see one physical transaction can be treated as two different, if we import them in different scenarios (when destination account exists, and when not).

My idea is to refactor `errorIfDuplicate` that if `external_id` is present in `$row`, then it should look for it if it's already stored in database. But it will work only for my case. Do you have any other ideas how this code should be refactored so others could also benefit?

Best,
Piotr

**Extra info**
Debug information generated at 2020-12-05 17:18:11 Europe/Amsterdam for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | d8593159-b2eb-4639-8024-eba522f547e7 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 2 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 |

**Bonus points**
- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Hi,

Yes, this is an unfortunate side-effect of the duplicate detector as it is right now. If it helps though, it'll be just one duplicated transaction that will be created. After the mapping (I assume you map data, otherwise the JSON wouldn't change) finds the account created by the previous transaction, the duplicate detector will keep picking up the correct data and no longer fail.

Improvements are on my list but a blatant search for the external identifier isn't going to solve this. If anything, it'll be the CSV importer, not Firefly III itself, searching for specific transactions before it decides to submit one.

**Comment by VictorAtPL** [comment]
Hello,

Thank you for your reply.
Good to hear the improvement is on your list. I decided to develop this "externalId" checker by myself and I published it in my fork: https://github.com/firefly-iii/csv-importer/compare/develop...VictorAtPL:feature/deduplication

I hope you will be able to reuse some of this code when you start working on the improvement of duplicate detection mechanism.

**Comment by JC5** [comment]
Nice. Would it be an idea to use the search endpoint?

```
/api/v1/search/transactions?query=external_id:test
```
