### ISSUE TITLE
Standard system

### ISSUE THREAD

**Issue by mathewderric** [firefly-iii/firefly-iii#4126]
I am running Firefly III version x.x.x.

**Description**

**Extra info**
 

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

hi team, being an indian user who tried your app needs your attention on some issue like 
1) inside revennue accounts its still not compatible enough to use with indian bank (swift account no ,isfe code etc ) .....atleast manually input money option(instead of auto fetching )   will be temperorily relief ...
2) fixed deposit account can also be added which is a revenue generation  with % per month or year..option and maturity date will be help

**Comment by JC5** [comment]
1. I don't know what you want me to do.
2. Same.

**Comment by mathewderric** [comment]
![image](https://user-images.githubusercontent.com/6594224/101287461-65020800-3816-11eb-9dca-c096e7cab6e3.png)
the market one can be made manual input ..as of now its auto fetching from bank as i understand and since indian bank accounts are not supportable since we use different system instead of bic & iban ...so if you can make manual entry possible like in asset account as shown below ill be good ...
![image](https://user-images.githubusercontent.com/6594224/101287548-dd68c900-3816-11eb-9dcc-f6f684451797.png)
like the marked one

**Comment by JC5** [comment]
It doesn't work like that. Revenue accounts are the accounts that pay you. Their balance is calculated by the transactions you create.

I have no idea what "the market one" means to you. The idea is that you create transactions from A to B etc. The expense and revenue accounts are created automatically if necessary (ie. shops, or your boss).

https://docs.firefly-iii.org/

**Comment by mathewderric** [comment]
i was trying to say  fixed deposit made in bank is also a revennue generator..it gives out a revenue from deposites as interest by month or year.ect...is tehre any way to incorporate fixed deposit type somewhere...i wont say to add in revennue itself somewhere its fit according to you . REF : https://www.icicibank.com/calculator/fd-calculator.page

**Comment by JC5** [comment]
No sorry, revenue you must add yourself.
