### ISSUE TITLE
file_put_contents(/var/www/firefly-iii/...): failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by masscream** [firefly-iii/firefly-iii#4132]
Hello, I'm using Firefly 5.4.6 and experiencing strange error. I've added several Expense accounts via transactions (so they were created automatically) and now when I click on the Expense Accounts section, it always throws this error. (pasted from logfile)

```
[2020-12-07 21:52:20] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/22\/97\/22972741243d41bcc2a7b084b970ab4c35446238): failed to open stream$
[2020-12-07 21:52:20] local.ERROR: file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/22/97/22972741243d41bcc2a7b084b970ab4c35446238): failed to open stream: No such file or directory {"userId":1,"exception":"[object] (Err$
[stacktrace]
```

However, I'm accessing FF also from the Android App Firefly III Mobile and there seems to be the section OK. Just from the browser I can't access it. Thanks.

**Comment by masscream** [comment]
Debug information generated at 2020-12-07 22:11:04 Europe/Prague for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 62f73c75-4ba7-478e-ae05-0f388c4fdb55 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2020-12-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | cs_CZ |
| Attempt at "cs_CZ.utf8" | 'cs_CZ.utf8' |
| Attempt at "cs_CZ.UTF-8" | 'cs_CZ.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Comment by JC5** [comment]
Clear your cache by browsing to `/flush`.

**Comment by masscream** [comment]
Works like a charm! Thank you.
