### ISSUE TITLE
"This value is invalid for the selected action." when creating rule action for piggy banks

### ISSUE THREAD

**Issue by sicco92** [firefly-iii/firefly-iii#4133]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

When creating a rule, I am unable to submit a valid piggy bank name when using the action 'Add/remove transaction amount in piggy bank..'. When I click 'Store new rule' I get an error saying 'This value is invalid for the selected action' even when I use an autocompleted piggy bank name. I am however able to store numbers, which shouldn't be possible. I am using the docker image accompanied by a mariadb container to store everything. I've already checked the database and the names are properly stored there. I also checked with a clean firefly/mariadb docker-combo both on Linux and Windows, and I get the same result every time.

I checked the demo site and there it's the opposite behaviour from what I have:

My site: unable to use names, but able to use numbers,
Demo site: unable to use numbers, but able to use names (which is expected)

**Steps to reproduce**
1. Create or have a piggy bank
2. Create a new rule with an 'Add/remove transaction amount in piggy bank..' action
3. Enter a valid piggy bank name in the value field and press 'Store new rule'

![image](https://user-images.githubusercontent.com/14315456/101405985-2aad6f00-38d9-11eb-93b6-a22540bfce3c.png)

Bonus: I am able to enter numbers in the value field:
![image](https://user-images.githubusercontent.com/14315456/101406952-7280c600-38da-11eb-93c1-ff413d0793c7.png)

**Extra info**
OS: Unraid and Windows 10 (both via Docker)
Browser: Edge Chromium 87.0.664.47 and Chrome 87.0.4280.88

Debug information generated at 2020-12-07 22:12:46 Europe/Berlin for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | a7fc089b-cf8f-44ac-ae7c-872a13eb7ad7 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.47 |

**Bonus points**

X I searched and nobody reported this bug before
X I have added a stack trace from my log files 
X I have added a screenshot.
O I was able to replicate it on the demo site https://demo.firefly-iii.org/ (I got the opposite results)

**Comment by JC5** [comment]
Thanks for reporting. I'm aware this is happening and it's fixed already on the demo site. The fix will be included in the new release.

**Comment by sicco92** [comment]
Thank you! I'll await the new release then!

**Comment by JC5** [comment]
Fixed in the latest beta, I'm closing this for consistency's sake.
