### ISSUE TITLE
Question about CSV-Import not sending mails

### ISSUE THREAD

**Issue by AndreiGavriliu** [firefly-iii/firefly-iii#4134]
I am running Firefly III version 5.4.6 and CSV-importer (the latest I guess)

**Description**
I am running cronjobs which import to my FF3 instance and everything works fine, except the import result mail. According to https://github.com/firefly-iii/firefly-iii/issues/3242 this should work, right?

I checked the logs but there are no entries regarding mails.

**Extra info**
here are some details from my `.env` file:

```
ENABLE_MAIL_REPORT=true
MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_ENCRYPTION=ssl
MAIL_USERNAME=[REDACTED]
MAIL_PASSWORD=[REDACTED]
MAIL_FROM_ADDRESS=[REDACTED]
```

Did I miss anything?

Cheers,
Andrei

**Comment by JC5** [comment]
Looks like mails are only triggered from the UI. I'll pick it up.

**Comment by AndreiGavriliu** [comment]
Thanks!

**Comment by JC5** [comment]
I pushed an update to the develop branch. The develop build is also building.
