### ISSUE TITLE
Error after upgrade: "SQLSTATE[42703]: Undefined column: 7 ERROR: column accounts.order does not exist"

### ISSUE THREAD

**Issue by werdck** [firefly-iii/firefly-iii#4135]
I get an error after the upgrade from 5.3.2 to latest (5.4.6).
Postgres had to be retained at version 12, which I defined in my `docker-compose.yml` some time ago already.
Debug page info attached.

Debug information generated at 2020-12-08 19:56:49 Europe/Berlin for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | c926e9f2-33cc-4f11-9cc8-f0813bdeaf5c |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2020-03-05 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0 |

The last time this happened I was able to upgrade step-by-step (one version at a time), this time this isn't possible anymore, because the oldest tag on docker hub is `version-5.4.5`, while I'd need `version-5.4.0`.

**Comment by JC5** [comment]
php artisan migrate

Should do the trick.

**Comment by werdck** [comment]
Thank you very much for the support, it worked!
