### ISSUE TITLE
Attach transfer to bill

### ISSUE THREAD

**Issue by MateEke** [firefly-iii/firefly-iii#4136]
**Description**
Hi!

I have a saving account, and I have to transfer a fixed amount of money to it every month to get benefits [(Hungarian LTP).](https://hu.wikipedia.org/wiki/Lak%C3%A1s-takar%C3%A9kp%C3%A9nzt%C3%A1r) From my point of view this monthly transfer works like a bill which I must pay. Now Firefly can't attach a transfer to a bill, however there aren't any technical obstacle.

**Solution**
Make it possible to attach transfer to a bill.

**What are alternatives?**
1. don't use bills for this type of transactions - the catch: it's good to see that I still have something to pay for in the current month

2. make a withdrawal to (cash account) and make a deposit from (cash account) - the catch: needs extra transaction and messes up sums of deposits and withdrawals

**Additional context**
My current solution:
![image](https://user-images.githubusercontent.com/11072174/101610178-2c298500-3a08-11eb-9bcf-e6dbf27c49e8.png)

**Comment by JC5** [comment]
Sorry, this isn't going to change.
