### ISSUE TITLE
Unable to update categories

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4137]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

I am unable to update category via API. Steps to replicate

```
curl -X PUT "https://demo.firefly-iii.org/api/v1/categories/7" -H "accept: application/json" -H "Authorization: Bearer xxxxxxx" -H "Content-Type: application/json" -d "{\"name\":\"Not Bills\"}"
```

**Comment by JC5** [comment]
Weird. Works for me on the demo site? Check out category nr. 7

**Comment by emansih** [comment]
My bad. I was calling GET instead of PUT in my code
