### ISSUE TITLE
Improve performance of pagination

### ISSUE THREAD

**Issue by cedricpim** [firefly-iii/firefly-iii#4138]
I am running Firefly III version 5.3.3.

**Description**
I have been using mostly the API and recently got some issues with memory (fixed them by increasing the memory on `php.ini`: `memory_limit` config). The endpoint I am mostly using is: `/api/v1/transactions?page=1&type=all`. 

I was taking a look at the code (I never programmed on PHP, so take this with a grain of salt), and if I saw it correctly here: https://github.com/firefly-iii/firefly-iii/blob/6ecbc5e0136ca6b497df3efda6aa85a428effdbf/app/Helpers/Collector/GroupCollector.php#L166, the code pulls all the transactions into an array and then slices that array based on the page. 

My question is if it wouldn't be better to move the pagination to the database to make it more scalable, memory-wise? Maybe something like: https://laravel.com/docs/8.x/pagination.

Thank you for the project :bow:

**Extra info**
Debug information generated at 2020-12-11 01:09:09 Europe/Amsterdam for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | a3b8328b-0b52-48b0-a2bf-04f58bc9056d |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | pgsql |
| Current driver | pgsql |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2017-10-26 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Comment by JC5** [comment]
I see it. Wow. I don't know where my head was when I built it like that 😁 .

I'll pick it up for the next release.

**Comment by JC5** [comment]
Oh but make sure you upgrade to a recent version plz. I remember that this way of working has to do with pagination as well. I'll check how I can optimize.

**Comment by JC5** [comment]
Yeah this is about pagination. The pagination from Laravel basically executes the query twice. That can help but is a trade-off for time.

**Comment by JC5** [comment]
Alright some research time later. Yes, this happens, and no it can't be avoided really. There are two sustainable options.

- You execute the query twice. Once to do  count and twice to get the result.
- You execute the query once and count, then split.

Firefly III currently does the second one. Reason being, these queries are large and complex. Especially when adding search queries and date ranges and stuff.

I'll pick it up as an enhancement to see if I can predict when option 1 or option 2 is the best bet.

**Comment by cedricpim** [comment]
Thanks for taking a look at it so quickly. Indeed, it is not an easy decision.

I started investigating it because I don't even have that many records (just a couple of thousand) and since I got issues with memory, I decided to see why that was happening :)

**Comment by JC5** [comment]
The API is picking this up and that will improve matters in the future, since the new layout is underway where this is handled better.
