### ISSUE TITLE
Unclear action account for deposit to transfer rule.

### ISSUE THREAD

**Issue by falcon397** [firefly-iii/firefly-iii#4141]
I am running Firefly III version 5.4.6.

**Description**
I am attempting to create an automated rule that targets a deposit from one asset account into another and converts the transaction to a transfer.  Your documentation is a bit unclear on what is the action value.  The documentation is as follows:

"""
From a deposit to a transfer
The money will be moved into from the original asset account, from another asset account. The "action value" you must provide must be the name of a valid asset account. If it does not exist, the action will fail.

If you leave the action value empty, the action will fail.
"""

Is the "action value" targeting the source or destination asset account for the transaction?  Also, I'm not trying to be that guy but the grammar is part of the issue.  You say "The money will be moved into from the original asset account, from another asset account", which seems vague, if you could clarify it would be helpful.  Which field of the transaction am I updating with the "action value"?

I was going to just test this out, but a quick update to the documentation would also solve this issue.

The page for reference:
https://docs.firefly-iii.org/advanced-concepts/rules#converting-to-another-transaction-type

**Comment by JC5** [comment]
Hi!

Feel free to comment on the grammar 😁. My personal guess is the sentence was copy/pasted from the previous description. I'm lazy like that.

The idea is that a deposit converted to a transfer will have the revenue account replaced with an asset account. So the sentence should read:

> The money will be moved into the original asset account, from a new asset account. 

Aka: if you had a deposit from "Boss Inc" to "Checking Account", the action value would have to indicate the other asset account, so the transfer would be from "Some Asset Account" to "Checking Account".

Makes sense?

**Comment by falcon397** [comment]
That makes sense, thank you for the clarification, that is what I needed to know.
