### ISSUE TITLE
Bug: send log emails

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#4144]
**Bug description**
I am running Firefly III version 5.4.0, and my problem is:
Trying to send log emails and not able see them in the log

```.env
MAIL_MAILER=log
MAIL_HOST=null
MAIL_PORT=2525
MAIL_FROM=xxx@gmail.com
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

**Steps to reproduce**

* Open admin page and click send test email.
* checked `storage\logs\ff3-audit-2020-12-12.log` and unable to locate any info on the log email

**Comment by JC5** [comment]
There should be a second log file. What's the log settings like?

```
LOG_CHANNEL=stack
APP_LOG_LEVEL=notice
```

**Comment by lastlink** [comment]
LOG_CHANNEL=stack

# Log level. You can set this from least severe to most severe:
# debug, info, notice, warning, error, critical, alert, emergency
# If you set it to debug your logs will grow large, and fast. If you set it to emergency probably
# nothing will get logged, ever.
APP_LOG_LEVEL=notice

**Comment by JC5** [comment]
Set it to `debug`, it should appear. I'll append the `.env.example` file and the docs.
