### ISSUE TITLE
Multi account piggy banks

### ISSUE THREAD

**Issue by Nixellion** [firefly-iii/firefly-iii#4160]
Hi! 

I have my money split into multiple accounts and different banks, as is, I'm sure, good practice. Not keeping everything in one can so to speak. And there are a ton of other reasons for this.

But I'd like to create a piggy bank and be able to top it up from different accounts. I've seen a few issues regarding this, and some work done by other contributors, but was it ever implemented in any way?

If not, what would be the recommended way to approach this? Otherwise if you have a piggy bank attached to just one account which has like 20% of your savings it's not very helpful or informative.

**Comment by JC5** [comment]
Hi!

There is no other way at the moment, I'm afraid. The implementations I've seen so far weren't of a quality I'd like to see for Firefly III. The database scheme needs serious changes to implement something like this which just isn't timely at the moment. Other things will have to go first.

So for now, a 20% piggy bank is the way to go.

**Comment by Nixellion** [comment]
A shame. 20% piggy bank does not work when you're gathering on something big enough to span across all savings. Like a house, apartment, car, etc.

Will try to juggle multiple piggy banks then I suppose, one per account. At least it shows totals, which is handy. Hopefully this feature will come in the future.
