### ISSUE TITLE
Bug: stop processing does not stop other rules in rule group

### ISSUE THREAD

**Issue by TimTimmerman** [firefly-iii/firefly-iii#4162]
I am running the latest stable (5.4.6). 

I want to structure my rules more, with the goal of having specific rules per asset account. 

I have asset accounts A, B and C. The way I figured to do this is to have:

- a rule group per asset account (A/B/C) and 
- one "overall rule" per rule group, that acts as a gatekeeper. 

For example, the "overall rule" in rule group A is that the very first rule in the rule group is as follows:
- when the source account name equals B or when it equals C 
- then append notes with A
- strict unchecked and stop processing checked

After this rule I would create other rules, that should in my understanding only trigger when the first "overall rule" had not been triggered (which would be the case when the source account is A). For asset accounts B and C I made a similar setup.

For example, I have a rule that will set the category and description to "groceries" based on destination account (non-strict), but adds a different tag depending on the asset account the transaction was made from. 

However, when creating a new transaction (source account B, destination account one of the groceries stores), the following happens:
1. "overall rule" of group A triggers
2. specific groceries rule of group A triggers
3. specific groceries rule of group B triggers

The behaviour I would expect as that number (2) above should not trigger, as the overall rule of group A had already been triggered with the "stop processing" box checked. 

Any ideas are much appreciated. Also other approaches to making rules for specific accounts are appreciated, but keep in mind that for each rule including a "source account equals A/B/C" will not work, because not all my rules are in strict-mode (and I don't want separate rules for each grocery store for example).

Thanks

**Comment by JC5** [comment]
Thanks for the expansive bug report. I'll do some deep diving and see what I can find!

**Comment by JC5** [comment]
It's a bug. It's a little annoying to have to set up negative rules but it matches the property name. In the future, it might be a good idea to reverse the idea: `continue_only_on_trigger`. That makes more sense, negative names are confusing.

But like I said. It's a bug. You can switch to the `develop` branch where a fix is present. The Docker image is currently building :+1:

**Comment by TimTimmerman** [comment]
Awesome, thanks for checking and fixing it so quickly!
