### ISSUE TITLE
bills vs recurring transactions

### ISSUE THREAD

**Issue by WhiteTiger-IT** [firefly-iii/firefly-iii#4163]
I am running Firefly III last version.
I don't understand the difference between bills and recurring transactions.

**Comment by niklas2810** [comment]
Recurring transaction: Creates a transaction automatically.

Bill: Is used to track payments, which can either be added manually or based on a rule. Moreover, it's possible to track the bill amount over time and the next expected date of payment.

For more details, follow these links:

Recurring Transactions: https://docs.firefly-iii.org/advanced-concepts/recurring

Bills: https://docs.firefly-iii.org/advanced-concepts/bills

I've found the Documentation to be quite good, I hope it helps you with understanding the key concepts of Firefly III :)

**Comment by WhiteTiger-IT** [comment]
I've already read the documentation, but didn't understand the difference between the two
