### ISSUE TITLE
Change folder

### ISSUE THREAD

**Issue by WhiteTiger-IT** [firefly-iii/firefly-iii#4164]
I am running Firefly III version 5.4.6.

**Description**
I want to call Firefly directly from the subdomain, for example cash.mydomain.tld.
If I run composer in the root it creates a firefly-iii folder.
Do I have a way to create the files directly in the root or can I simply move the files?

**Comment by JC5** [comment]
I assume you use some kind of shared hosting, referring to the "public_html" folder from your other ticket?

You can move all the files but if you can't change the "public_html" to "public" it won't work I'm afraid.

**Comment by WhiteTiger-IT** [comment]
No, it's my Apache server and the virtual server is associated with mydomain.tld / public_html.
I still tried to install it and leave the firefly-iii folder, but then I still encountered a fatal error (I opened another issue)

**Comment by JC5** [comment]
In that case, just change the virtual server's root to `firefly-iii/public`

**Comment by WhiteTiger-IT** [comment]
Many thanks
