### ISSUE TITLE
Internal Reference Attribute in Transaction

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4166]
Hi! I have some questions. 

What is internal reference referencing in Firefly III? ~~I would like to abuse it in my mobile app.~~ Would users be able to read / write on that attribute? Thanks.

**Comment by JC5** [comment]
It's a field like all the others. Users can read and write to this field. It's not hidden.

Do you need fields like that? Because API only fields can be arranged. It's not something you can ultimately *trust* but it could get you far enough.

**Comment by emansih** [comment]
I am using the attribute as a temporary(3 - 5 seconds) immutable reference since an attachment cannot be uploaded together with the transaction.

**Comment by JC5** [comment]
:+1: that should work fine.
