### ISSUE TITLE
Not found at Login

### ISSUE THREAD

**Issue by WhiteTiger-IT** [firefly-iii/firefly-iii#4168]
I am running Firefly III version 5.4.6

**Description**
When I call **http: //cash.mydomain.tld**
I get **http: //cash.mydomain.tld/login** with not found.

**Extra info**
Server Debian 10
PC Win 10 with Chrome, Firefox and Opera, both in private surf.

I have read FAQs and other posts related to this error.
The references to the DB and the user credentials are correct.

In storage I created .htaccess with:
```
Options All -Indexes
Deny from all
```

In cash.mydomain.tld.conf there is
```
<VirtualHost *: 80>
     DocumentRoot "/var/www/html/cash.mydomain.tld/public_html/firefly-iii/public"
     ServerName cash.mydomain.tld
     <Directory "/var/www/html/cash.mydomain.tld/public_html/firefly-iii/public">
         allow from all
         Options None
         Require all granted
     </Directory>
     ServerAlias * .cash.mydomain.tld
</VirtualHost>
```

in apache2.conf I changed **AllowOverride None** with **AllowOverride All**
I enabled debug, but then there are no log files in **storage/logs**

**Bonus points**

- I have read the FAQ at https://docs.firefly-iii.org/faq/self_hosted
- I added log files
There are no log files

**Comment by JC5** [comment]
- OK, I assume you changed it to `AllowOverride All`?
- Is mod rewrite enabled? `sudo a2enmod rewrite` then restart Apache.

**Comment by WhiteTiger-IT** [comment]
Apologizes. I misspelled and corrected.
in apache2.conf I changed AllowOverride None with AllowOverride All

The mod rewrite is active, I had checked and obviously Apache was restarted.

I had this problem installing Firefly from Softaculous on an Internet VPS.
I've tried installing it directly on my local server, but I'm in the same situation.

**Comment by JC5** [comment]
No worries. Is the Apache configuration from the Docker image something you can use?

https://github.com/firefly-iii/docker-base-image/blob/main/apache/apache2-site.conf

It's pretty basic so probably not. 

If Firefly III shows no log files, the request never makes it to `public/index.php`. Is there anything in the Apache logs?

**Comment by WhiteTiger-IT** [comment]
In apache I have enabled the logs on the debug value on a dedicated file and this is its content for a simple URL refresh.
I am not an expert, but I see no errors except the last line

```
[Sun Dec 20 16:13:23.954660 2020] [authz_core:debug] [pid 10405:tid 140255814465280] mod_authz_core.c(820): [client 192.168.201.201:63731] AH01626: authorization result of Require all granted: granted
[Sun Dec 20 16:13:23.954762 2020] [authz_core:debug] [pid 10405:tid 140255814465280] mod_authz_core.c(820): [client 192.168.201.201:63731] AH01626: authorization result of <RequireAny>: granted
[Sun Dec 20 16:13:23.955062 2020] [core:info] [pid 10405:tid 140255814465280] [client 192.168.201.201:63731] AH00128: File does not exist: /var/www/html/cash.mydomain.tld/public_html/firefly-iii/public/login
[Sun Dec 20 16:14:41.746433 2020] [authz_core:debug] [pid 10405:tid 140255822857984] mod_authz_core.c(820): [client 192.168.201.201:63790] AH01626: authorization result of Require all granted: granted
[Sun Dec 20 16:14:41.746507 2020] [authz_core:debug] [pid 10405:tid 140255822857984] mod_authz_core.c(820): [client 192.168.201.201:63790] AH01626: authorization result of <RequireAny>: granted
[Sun Dec 20 16:14:41.746693 2020] [authz_core:debug] [pid 10405:tid 140255822857984] mod_authz_core.c(820): [client 192.168.201.201:63790] AH01626: authorization result of Require all granted: granted
[Sun Dec 20 16:14:41.746711 2020] [authz_core:debug] [pid 10405:tid 140255822857984] mod_authz_core.c(820): [client 192.168.201.201:63790] AH01626: authorization result of <RequireAny>: granted
[Sun Dec 20 16:14:41.746776 2020] [proxy:debug] [pid 10405:tid 140255822857984] mod_proxy.c(1249): [client 192.168.201.201:63790] AH01143: Running scheme unix handler (attempt 0)
[Sun Dec 20 16:14:41.746803 2020] [proxy_fcgi:debug] [pid 10405:tid 140255822857984] mod_proxy_fcgi.c(1021): [client 192.168.201.201:63790] AH01076: url: fcgi://localhost/var/www/html/cash.mydomain.tld/public_html/firefly-iii/public/index.php proxyname: (null) proxyport: 0
[Sun Dec 20 16:14:41.746829 2020] [proxy_fcgi:debug] [pid 10405:tid 140255822857984] mod_proxy_fcgi.c(1028): [client 192.168.201.201:63790] AH01078: serving URL fcgi://localhost/var/www/html/cash.mydomain.tld/public_html/firefly-iii/public/index.php
[Sun Dec 20 16:14:41.746859 2020] [proxy:debug] [pid 10405:tid 140255822857984] proxy_util.c(2316): AH00942: FCGI: has acquired connection for (*)
[Sun Dec 20 16:14:41.746883 2020] [proxy:debug] [pid 10405:tid 140255822857984] proxy_util.c(2369): [client 192.168.201.201:63790] AH00944: connecting fcgi://localhost/var/www/html/cash.mydomain.tld/public_html/firefly-iii/public/index.php to localhost:8000
[Sun Dec 20 16:14:41.746897 2020] [proxy:debug] [pid 10405:tid 140255822857984] proxy_util.c(2406): [client 192.168.201.201:63790] AH02545: fcgi: has determined UDS as /run/php/php7.4-fpm.sock
[Sun Dec 20 16:14:41.747129 2020] [proxy:debug] [pid 10405:tid 140255822857984] proxy_util.c(2578): [client 192.168.201.201:63790] AH00947: connected /var/www/html/cash.mydomain.tld/public_html/firefly-iii/public/index.php to httpd-UDS:0
[Sun Dec 20 16:14:41.747190 2020] [proxy:debug] [pid 10405:tid 140255822857984] proxy_util.c(2949): AH02823: FCGI: connection established with Unix domain socket /run/php/php7.4-fpm.sock (*)
[Sun Dec 20 16:14:41.852563 2020] [proxy:debug] [pid 10405:tid 140255822857984] proxy_util.c(2331): AH00943: FCGI: has released connection for (*)
[Sun Dec 20 16:14:41.860185 2020] [authz_core:debug] [pid 10405:tid 140255797679872] mod_authz_core.c(820): [client 192.168.201.201:63790] AH01626: authorization result of Require all granted: granted
[Sun Dec 20 16:14:41.860259 2020] [authz_core:debug] [pid 10405:tid 140255797679872] mod_authz_core.c(820): [client 192.168.201.201:63790] AH01626: authorization result of <RequireAny>: granted
[Sun Dec 20 16:14:41.860411 2020] [core:info] [pid 10405:tid 140255797679872] [client 192.168.201.201:63790] AH00128: File does not exist: /var/www/html/cash.mydomain.tld/public_html/firefly-iii/public/login
```

**Comment by JC5** [comment]
Neither do I. But the `/login` 404 should have triggered mod rewrite. Strange :/

**Comment by WhiteTiger-IT** [comment]
a2enmod rewrite
Module rewrite already enabled

**Comment by WhiteTiger-IT** [comment]
I don't know if it helps or if it was useless, but I created the public / test.php file with this code 
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Bolt htaccess tester.</title>
    <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
    <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body id="home">
<?php

#htaccess tester, version 1.0

echo "<h1>Bolt Apache <tt>.htaccess</tt> tester.</h1>";

if (strpos($_SERVER['REQUEST_URI'], 'htaccess_tester.php') === false) {

    echo "<p><tt>mod_rewrite</tt> is working! You used the path <tt>" . $_SERVER['REQUEST_URI'] . "</tt> to request this page.</p>";

} elseif (is_readable(__DIR__.'/.htaccess') ) {

    echo "<p>The file .htaccess exists and is readable to the webserver. These are its contents: </p>\n<textarea style='width: 700px; height: 200px;'>";
    echo file_get_contents(__DIR__.'/.htaccess');
    echo "</textarea>";

} else {

    echo "<p><strong>Error:</strong> The file .htaccess does not exist or it is not readable to the webserver. <br><br>Retieve a new version of the file here, and place it in your webroot. Make sure it is readable to the webserver.</p>";
    die();

}

// echo "<h1>PHPinfo</h1>";

// echo "<p>Below you'll find the specifics of your PHP installation, for debugging purposes.</p>";

// phpinfo();
?>
</body>
</html>

```
and I got this result
```
Bolt Apache .htaccess tester.
mod_rewrite is working! You used the path /test.php to request this page.
```

**Comment by JC5** [comment]
I really don't know enough about Apache, sorry about that.

**Comment by WhiteTiger-IT** [comment]
FireFly is Apache centric and there are .htaccess all over the place.
Only those who are part of the development team can understand what the problem is or at least give indications for debugging.
I just don't know what to do.

**Comment by JC5** [comment]
Firefly III is "Apache-centric" because it's easy to manipulate server settings from `.htaccess` files. You'll find them in all directories to make sure directory listings are disabled, for example.

I gave you all the indications I know.

**Comment by WhiteTiger-IT** [comment]
I don't understand what other rewrites can interfere with FireFly.
On the other hand the test file I posted in the previous messages shows that in the firefly-III/public folder the rewrite works.

Also, I have installed FireFly using Softaculous on two different VPS in Debian or Ubuntu with Plesk running Nginx & Apache.
Also on these it does not go beyond the Login Not Found.

So I just don't know what to check without your directions or suggestions.

**Comment by JC5** [comment]
The rewrite module is necessary to manage the URL's. There's no specific need to put Firefly III online, and I run my own instance offline (locally). Perhaps you could try the Docker installation? That might work.

**Comment by WhiteTiger-IT** [comment]
I don't want to comment on your development model. I simply observe:
* the Apache log does not report errors;
* FireFly doesn't even generate log files;
* only a white screen appears with an error;
* the page relates to a virtual "folder" (/login) and therefore does not exist.

Under these conditions it is impossible to understand what is wrong.
If there is no indication from you, there are two things left to do: close the ticket and uninstall Firefly.
Thanks anyway.

**Comment by JC5** [comment]
Could you verify if your Apache user has write access to `storage/logs`? That might not fix the issue but at least show some info. If Firefly III doesn't generate logs, it doesn't have the correct permissions to store them. It seems the rewrite works, otherwise you'd be stuck on the index. Let me know.
