### ISSUE TITLE
Sorting by Date on Category Report sorts alphabetically

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4169]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:
When you run a category report and try to sort your expenses by date, it sorts the months alphabetically even though it claims to be sorting "Jan...dec" or "Dec...jan".

Jan-Dec:
![image](https://user-images.githubusercontent.com/21091510/102723913-94fee000-42d9-11eb-983d-76582d250f72.png)
Dec-Jan
![image](https://user-images.githubusercontent.com/21091510/102723973-06d72980-42da-11eb-950c-65cd2b52d3ae.png)

**Steps to reproduce**

1. Run a category report any 1 or more categories across several months.
2. Scroll down to the "Expenses (top 10) box.
3. Try to sort by date.
4. Notice that instead of sorting by date, the dates are sorted alphabetically.

**Extra info**

Debug information generated at 2020-12-20 15:41:52 America/New_York for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2020-12-31 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ]  I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Well spotted. Will be fixed in the next release :+1:
