### ISSUE TITLE
Newly added expense accounts are not ordered by alphabet

### ISSUE THREAD

**Issue by 3ssen** [firefly-iii/firefly-iii#4174]
After migrating to version 5.4.6 the newly added expense accounts are not in the alphabetic order in de /accounts/expense overview.

My complete list is now:
A-Z new accounts
followed by 
A-Z old accounts

Is there an other easy way to sort these pages?

![image](https://user-images.githubusercontent.com/2758036/102764480-7ea96080-437b-11eb-87f9-b9e9d2e96c06.png)

**Comment by JC5** [comment]
Not yet. They can be sorted by hand. I'll improve this in the new layout for sure.

**Comment by beanaroo** [comment]
In the mean time, I was able to re-order the accounts using the following query (PostgreSQL):

```pgsql
-- Reorder Accounts alphabetically per user per account type
UPDATE accounts acc
SET "order" = sub.rn
FROM (
         SELECT id,
                row_number() OVER (
                    PARTITION BY user_id, account_type_id
                    ORDER BY name, id
                    ) AS rn
         FROM accounts
     ) sub
WHERE acc.id = sub.id;
```

I'm not sure if this is correct, but it has the desired effect.
