### ISSUE TITLE
dashboard warning is missing 1 day

### ISSUE THREAD

**Issue by 3ssen** [firefly-iii/firefly-iii#4175]
When changing the date-range to a whole year on the dashboard, the warning is missing one day.

i.e. 2010 has 365 days.

![image](https://user-images.githubusercontent.com/2758036/102787990-381b2c80-43a2-11eb-83e6-e379f4bbded7.png)

version 5.4.6

**Comment by JC5** [comment]
Thanks for the headsup. I'll change the calculation! I think it counts days in between or something. :+1:

**Comment by 3ssen** [comment]
you're welcome. Keep up the good work!
