### ISSUE TITLE
Firefly 5.4.6 fails to start with gnueabihf error

### ISSUE THREAD

**Issue by StrikerExtreem** [firefly-iii/firefly-iii#4176]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

Firefly does not start in my raspberry pi kubernetes 1.19.x "cluster". It gives the following error during starting:
php: error while loading shared libraries: /usr/lib/arm-linux-gnueabihf/libicudata.so.63: Unable to run arch-specific checks, when Running migration commands..
Running upgrade commands...
Running verification commands...
etc.

**Steps to reproduce**
just start the kubernetes pod.

**Extra info**
raspberry is has raspbian installed with linux kernet 5.4.79-v7+. 

**Bonus points**
There was a developer image that did work, but that was the last one which had arm/v7 arch in the image manifest. After that was removed, i do not have a fallback anymore. At the time of writing, both base image and firefly develop image only are amd64 arch.

**Comment by JC5** [comment]
Thanks for letting me know. You'll have to build the images locally for the time being, I'm having some trouble getting my build machine up and running. Hence the missing images.

1. [Base image](https://github.com/firefly-iii/docker-base-image/blob/main/Dockerfile). Can be built with `docker build . -t firefly-iii-base-image
2. [Firefly III image](https://github.com/firefly-iii/docker/blob/main/Dockerfile). Edit it so it references the base image from the previous step, then build `VERSION=5.4.6 docker build . -t firefly-iii`.

I hope to get everything up and running soon.

**Comment by JC5** [comment]
I pushed new images for 5.4.6 and develop. Let me know if they work.

**Comment by StrikerExtreem** [comment]
Working again, thanks a lot.
