### ISSUE TITLE
Tag field when editing bulk transactions individually

### ISSUE THREAD

**Issue by Daedren** [firefly-iii/firefly-iii#4177]
**Description**

I would like for the "editing transactions individually" page (which currently lets you edit the description, amount, date, from, to, category and budget) to have a field for tags as well. Right now you'd need to go to the individual transaction's page to add a tag to it.

Firefly III is far more than just a little book about expenses, and for me these extra metadata fields are really where it all comes together, easy access to them is a very nice to have. Of course, this is all pertaining to my use case, and I understand it doesn't fit everyone.

**What are alternatives?**

As space is a problem, perhaps a setting to let us choose which fields to show in the page. For example, as I import my transactions using the CSV-Importer, I never have issues with dates and amounts, but I'm missing the metadata which they don't have (categories, tags, etc) and not all of it can be automated through rules.

**Comment by JC5** [comment]
Maybe in the new layout. For now, no room I'm afraid.
