### ISSUE TITLE
CSV import - how to get it working for a loan account import

### ISSUE THREAD

**Issue by Hg87ha4qQ15bb** [firefly-iii/firefly-iii#4182]
I am running Firefly III version 5.4.6
Firefly III CSV Import Tool v2.3.1

**Description**
I am trying to import a CSV import from a loan account (real estate credit) with this types of content lines:
- initial withdrawals wich are the payments for the property
- monthly payments of interest
- monthly transactions which withdraw money from current account to the loan account lowering the debt

The first two types are working as expected but the third type is not: I think it should be a transfer from the current account to the loand account decreasing the debt (but might be wrong).

format of the non-working lines: date; description; IBAN current account; IBAN loan account; amount (positive in this case)

I am importing it to the loan account as "Default import account"

I am not sure what the "role" for the IBANs has to be and tried several variants including using only one of them...

Question: How is it meant to work for my use case?

Thanks :+1: 

**Extra info**

running all on linux in docker

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ YES
- I added a screenshot NO
- I added log files  NO
- I was able to replicate the issue on the demo site. NO

**Comment by JC5** [comment]
> I think it should be a transfer from the current account to the loand account decreasing the debt 

These should be withdrawals from the current account to the loan.

Are the transactions created at all?

**Comment by Hg87ha4qQ15bb** [comment]
In general I am able to have transactions created but it depends...


An example  based on my real import csv file:
`
30.08.2018;Zahlung Besitzer;DE-loan;;-18500,20
30.09.2018;Zinsen;DE-loan;;-129,17
24.12.2019;Überweisungsgutschrift;DE-giro;DE-loan;2100,00
30.12.2019;Zinsen;DE-loan;;-207,54
30.12.2019;Lastschrifteinzug;DE-giro;DE-loan;1012,34
`

rows:
- 1st line is a payment for the property => works as expected
- 2nd and 4th payment of interest to the bank => works as expected
- 3rd and 5th are transactions paying back money from savings (aka "giro") to the loan account => not really

columns:
- 1: date (role: date_transaction)
- 2: description
- 3: source IBAN (anonymized)
- 4: target IBAN  (anonymized)
- 5: amount

I am importing it to the DE-loan account as "Default import account".

When I ignore the IBAN columns 3 and 4 I get an error "transactions.0.source_id" with "Um fortzufahren, benötigen Sie eine gültige Quellkontenkennung und/oder einen gültigen Quellkontonamen." for the lines 3 and 5.

When I try to use the IBAN columns the direction of the payment is wrong: it appears as withdrawing money from DE-loan to DE-giro although it is the opposite direction.

I tried roles asset account IBAN and opposing account IBAN as roles for columns 3 and 4.

**Comment by Hg87ha4qQ15bb** [comment]
I finally managed to get it working: 

- All payments to the loan account with IBANs DE-giro; DE-loan in columns 3 and 4
  - all other lines have empty columns 3 and 4
- Negated the amount for those payments (now all amounts in the csv are negative which feels a little bit strange)

Import config:
```json
{
    "date": "d.m.Y",
    "default_account": 5,
    "delimiter": "semicolon",
    "headers": false,
    "ignore_duplicate_lines": true,
    "ignore_duplicate_transactions": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "specifics": [],
    "roles": [
        "date_transaction",
        "description",
        "account-iban",
        "opposing-iban",
        "amount"
    ],
    "do_mapping": {
        "2": true,
        "3": true,
        "0": false,
        "1": false,
        "4": false
    },
    "mapping": {
        "2": {
            "DE-giro": 4,
            "DE-loan": 5
        },
        "3": {
            "DE-loan": 5
        }
    },
    "version": 2
}
```

**Comment by JC5** [comment]
Cool, I'm glad to hear it! If you want, create a PR here: https://github.com/firefly-iii/import-configurations/

Other people can use the file to import their own files. :+1:
