### ISSUE TITLE
CSV importer using self signed certificate

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#4183]
I am using my own root certificate authority to sign certificates for apps on my local network.
Therefore I have to install the root certificate to my browsers.
I would like to make that work for the csv importer as well

**Solution**
A. An option to disable the SSL verification check that Guzzle does when connecting to the firefly instance
OR
B. An option to load my root certificate into the docker container of the importer, and let Guzzle use it, so it can validate the SSL chain.

**What are alternatives?**
Using HTTP for firefly :-(

**Comment by JC5** [comment]
Or C., use the provided options:

https://github.com/firefly-iii/csv-importer/blob/main/.env.example#L51

**Comment by zjean** [comment]
Thanks!! Will check it out.
Happy holidays!

**Comment by JC5** [comment]
Can do, same!

**Comment by zjean** [comment]
It looks like the TokenController::callback method did not use the TLS_VERIFY_SECURITY setting in its request. I added a PR for that.

**Comment by JC5** [comment]
I saw it, will pick it up. 👍🏻
