### ISSUE TITLE
Error Adding New Transaction Link

### ISSUE THREAD

**Issue by Boofola** [firefly-iii/firefly-iii#4186]
**Bug description**
I am running Firefly III version 5.4.6 and my problem is:

_Method_ FireflyIII\Http\Requests\LinkTypeFormRequest::string does not exist._

To see all Error Logs and The Error Page go to:

[https://policies.boofola.com/FireFlyError/](https://policies.boofola.com/FireFlyError/)

**Steps to reproduce**
Administration -> Transaction links configuration -> Create new link -> Store new link type -> then error message.

**Extra info**
I am running Windows 10 with all current updates and packs. I have tried this on Chrome, Firefox, Opera, and Edge, with all current updates with the same results.

**_Debug information generated at 2020-12-26 12:52:42 America/New_York for Firefly III version **5.4.6**._**

**Bonus points**
- I searched and nobody reported this bug before, or at least not with the same wording as my search.

- I have added a stack trace from my log files <[https://policies.boofola.com/FireFlyError/](https://policies.boofola.com/FireFlyError/)>
- I have added a screenshot in the folder on my server.

Of course! How much do you want?

**Comment by JC5** [comment]
Thanks for letting me know! It's probably a bug and I'll pick it up :+1:

**Comment by Boofola** [comment]
Cron <bigman69@server> curl https://mybooks.toddstratton.com/cron/ru
n/7b***09ed017****9e3954b1***5bd4e

That is the subject of the email. I have replaced a few of the digits in
the code for security reasons.

*Todd Stratton*
Owner & Founder

direct : (570) 284-6940
fax : (570) 917-0234
email : todds@boofola.xyz
website : boofolallc.com
<https://linkedin.com/company/boofola/>  <https://twitter.com/BoofolLlc>
<https://facebook.com/myboofola>  <https://instagram.com/myboofola>
<https://pinterest.com/myboofola>
<https://youtube.com/channel/UCBkMbMW82xWkX0eFJT8zM4w>


*Boofola LLC Does Not Just Accept Differences - We Celebrate Them, We
Support Them, And We Thrive On Them!*

** Please note that this email address is not monitored 24/7. If your
matter requires prompt attention, please call our offices during business
hours.*
