### ISSUE TITLE
Cron - The requested URL was not found on this server.

### ISSUE THREAD

**Issue by Boofola** [firefly-iii/firefly-iii#4187]
I am running Firefly III version 5.4.6

**Description**
While running the Cron Job, I get the message as follows:

**<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>**

I am using the file Cron with the following command:

curl https://mybooks.*****.com/cron/run/7***

The *** are representative of the real numbers and letters, just add more to it.

**Extra info**
This is an install from cPanel using Softloucous on a VPS hosted on A2Hosting. Running Apache and Unix/Nginx.

This is a fresh install, I am just starting to setup all of the features and settings.

I do have recurring transactions hence the need for Cron.

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ - YES, with no help for this issue.
- I added a screenshot, No, the contents of the email received are above.

**Comment by JC5** [comment]
Mmm, not a clue. The URL is correct, `/cron/run/*`.

I assume the CLI token you filled in are an exact copy/paste from the CLI token in your profile?

**Comment by Boofola** [comment]
Yes, I have, the token was directly copied and pasted directly into the
Cron.


*Todd Stratton*
Owner & Founder

direct : (570) 284-6940
fax : (570) 917-0234
email : todds@boofola.xyz
website : boofolallc.com
<https://linkedin.com/company/boofola/>  <https://twitter.com/BoofolLlc>
<https://facebook.com/myboofola>  <https://instagram.com/myboofola>
<https://pinterest.com/myboofola>
<https://youtube.com/channel/UCBkMbMW82xWkX0eFJT8zM4w>


*Boofola LLC Does Not Just Accept Differences - We Celebrate Them, We
Support Them, And We Thrive On Them!*

** Please note that this email address is not monitored 24/7. If your
matter requires prompt attention, please call our offices during business
hours.*

**Comment by JC5** [comment]
What happens when you manually visit the cron URL? Also a 404?

I'm kind of out of ideas pretty quickly. I don't really know much about your server.

**Comment by Boofola** [comment]
Yes, I still get a 404 error message.

What else would you like to know?


*Todd Stratton*
Owner & Founder

direct : (570) 284-6940
fax : (570) 917-0234
email : todds@boofola.xyz
website : boofolallc.com
<https://linkedin.com/company/boofola/>  <https://twitter.com/BoofolLlc>
<https://facebook.com/myboofola>  <https://instagram.com/myboofola>
<https://pinterest.com/myboofola>
<https://youtube.com/channel/UCBkMbMW82xWkX0eFJT8zM4w>


*Boofola LLC Does Not Just Accept Differences - We Celebrate Them, We
Support Them, And We Thrive On Them!*

** Please note that this email address is not monitored 24/7. If your
matter requires prompt attention, please call our offices during business
hours.*

**Comment by JC5** [comment]
What's the URL of the profile page? Is it `/profile`? Or is it something like `/public/profile` or /index.php/profile`?

That's my last idea.

**Comment by Boofola** [comment]
https://mybooks.toddstratton.com/public/profile

That is the URL that comes up in the address bar.

Thank you VERY MUCH for your help with this!


*Todd Stratton*
Owner & Founder

direct : (570) 284-6940
fax : (570) 917-0234
email : todds@boofola.xyz
website : boofolallc.com
<https://linkedin.com/company/boofola/>  <https://twitter.com/BoofolLlc>
<https://facebook.com/myboofola>  <https://instagram.com/myboofola>
<https://pinterest.com/myboofola>
<https://youtube.com/channel/UCBkMbMW82xWkX0eFJT8zM4w>


*Boofola LLC Does Not Just Accept Differences - We Celebrate Them, We
Support Them, And We Thrive On Them!*

** Please note that this email address is not monitored 24/7. If your
matter requires prompt attention, please call our offices during business
hours.*

**Comment by JC5** [comment]
No problem, glad to see it works!

**Comment by Boofola** [comment]
No, still not working. I regenerated the key with no positive results.

If I do a search in my cPanel File Manager for corn, I don't get anything.
I did that after I was sure that my mind was gone from searching too hard.
Is this the way that it should be?


*Todd Stratton*
Owner & Founder

direct : (570) 284-6940
fax : (570) 917-0234
email : todds@boofola.xyz
website : boofolallc.com
<https://linkedin.com/company/boofola/>  <https://twitter.com/BoofolLlc>
<https://facebook.com/myboofola>  <https://instagram.com/myboofola>
<https://pinterest.com/myboofola>
<https://youtube.com/channel/UCBkMbMW82xWkX0eFJT8zM4w>


*Boofola LLC Does Not Just Accept Differences - We Celebrate Them, We
Support Them, And We Thrive On Them!*

** Please note that this email address is not monitored 24/7. If your
matter requires prompt attention, please call our offices during business
hours.*

**Comment by JC5** [comment]
If https://example.com/public/cron/run/CODE doesn't work then I'm out of ideas, unfortunately.

**Comment by Boofola** [comment]
Okay, so this time when I tried running it with */public/* it then ran
successfully.

In conclusion, public needs to be added, and a new key/token must be
generated. When I tried running this with the public added before it still
failed. You just never know with some of this anymore.

Thank you very much for your help!

*Todd Stratton*
Owner & Founder

direct : (570) 284-6940
fax : (570) 917-0234
email : todds@boofola.xyz
website : boofolallc.com
<https://linkedin.com/company/boofola/>  <https://twitter.com/BoofolLlc>
<https://facebook.com/myboofola>  <https://instagram.com/myboofola>
<https://pinterest.com/myboofola>
<https://youtube.com/channel/UCBkMbMW82xWkX0eFJT8zM4w>


*Boofola LLC Does Not Just Accept Differences - We Celebrate Them, We
Support Them, And We Thrive On Them!*

** Please note that this email address is not monitored 24/7. If your
matter requires prompt attention, please call our offices during business
hours.*

**Comment by Boofola** [comment]
Can I ask for your help with one more thing?

When I run the Cron, I get a "successful" on all but "The telemetry cron
job did not fire."

Is that a problem?

*Todd Stratton*
Owner & Founder

direct : (570) 284-6940
fax : (570) 917-0234
email : todds@boofola.xyz
website : boofolallc.com
<https://linkedin.com/company/boofola/>  <https://twitter.com/BoofolLlc>
<https://facebook.com/myboofola>  <https://instagram.com/myboofola>
<https://pinterest.com/myboofola>
<https://youtube.com/channel/UCBkMbMW82xWkX0eFJT8zM4w>


*Boofola LLC Does Not Just Accept Differences - We Celebrate Them, We
Support Them, And We Thrive On Them!*

** Please note that this email address is not monitored 24/7. If your
matter requires prompt attention, please call our offices during business
hours.*

**Comment by JC5** [comment]
Nope, not a problem :+1:.

There are currently three jobs, and the telemetry job (it's opt-in btw) will only fire once a week. Since telemetry is disabled by default, it'll never fire.

**Comment by Boofola** [comment]
Awesome, thank you so much for all of your help with this issue!


*Todd Stratton*
Owner & Founder

direct : (570) 284-6940
fax : (570) 917-0234
email : todds@boofola.xyz
website : boofolallc.com
<https://linkedin.com/company/boofola/>  <https://twitter.com/BoofolLlc>
<https://facebook.com/myboofola>  <https://instagram.com/myboofola>
<https://pinterest.com/myboofola>
<https://youtube.com/channel/UCBkMbMW82xWkX0eFJT8zM4w>


*Boofola LLC Does Not Just Accept Differences - We Celebrate Them, We
Support Them, And We Thrive On Them!*

** Please note that this email address is not monitored 24/7. If your
matter requires prompt attention, please call our offices during business
hours.*
