### ISSUE TITLE
Performance issues regarding PAT and OAuth Generation 

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#4188]
**Bug description**
I am running Firefly III version 5.4.6 (Docker), and my problem is:
When generating a new Personal Access Token on `/profile`, it sometimes takes up to 10 seconds until the token is being displayed.

This might be frustrating as-is, however the server creates multiple tokens as well when clicking the button multiple times (and there is no way of knowing which pop-up refers to which PAT called "test" 😢 ).

I don't think that there is so much lag between Firefly III and the database, all other sites run smoothly and the delay remains the same after creating one immediatly afterwards (pretty stable around 8-9s).

**Steps to reproduce**

I'm not quite sure what's causing the issue. Any ideas from your side?

**Extra info**

I'm using the Docker Version + Postgres, running on Debian behind a Traefik proxy. Tested on different devices and browsers (Firefox/Chrome/Edge, Windows 10/iOS/Android).

Full debug info: https://hastebin.com/raw/lireteceju

**Bonus points**

![image](https://user-images.githubusercontent.com/30748216/103160114-76b14c80-47d1-11eb-996e-6948aef4189d.png)

- I searched and nobody reported this bug before
- I have added a screenshot.
- I was **not** able to replicate it on the demo site https://demo.firefly-iii.org/ (it runs just fine there)

**Comment by niklas2810** [comment]
Oh, and a quick side note: The text of the `create` button doesn't seem to be part of the translation files (it's always written in English) ^^

**Comment by niklas2810** [comment]
Side note No. 2: The issue applies to OAuth logins as well, not quite sure why I didn't notice that one yet.

![image](https://user-images.githubusercontent.com/30748216/103160348-212a6f00-47d4-11eb-8b43-1c2c199a19ff.png)

**Comment by emansih** [comment]
I had some issues using OAUTH and I can never replicate it reliably. When clicking on login during OAUTH, the page will show a loading progress bar for a couple of seconds and nothing happens after that. Clicking on the login button again will throw a HTTP 419 Page Expired. Refreshing the page will show Firefly III's dashboard. I will have to restart the OAUTH flow again before the token appears in the URL bar.

**Comment by JC5** [comment]
Mmmm. Thanks for letting me know. Most OAuth things are handled by PHP's openSSL library, which in turn uses the system's openssl things.

The PAT for example, consists of 3 parts, split by a `.` dot. All 3 parts can be base64 decoded but only the last part is gibberish: the signature.

I'll see if I can extract the commands to generate a PAT. I have to ask if you execute them manually to see who/what is lagging exactly.

**Comment by JC5** [comment]
The slow response might be a lack of good random data but this is just guesswork.

**Comment by niklas2810** [comment]
Is there a way to generate a PAT in the console? I could try to execute the command inside the Docker container to check if that's the issue.

**Comment by JC5** [comment]
Yes: `docker exec <container> php artisan passport:client --personal --name=testCLI`

**Comment by niklas2810** [comment]
Hmmh, that's odd. This command itself only takes ~1s to generate a token.

**Comment by JC5** [comment]
I spent some time on this but I was entirely unable to find a solid root cause for this. :(

**Comment by niklas2810** [comment]
No worries, this isn't much of an issue anyways 😄 Just something odd that I noticed while using Firefly III. Are you planning to create some kind of "Loading.." animation/text in the new layout (/disabling the button while waiting for a response)? I guess that a hint that it's currently working on it would've stopped me from pressing the button multiple times. And if you aren't, I guess this isn't much of a problem either - just a tiny suggestion ^^

**Comment by JC5** [comment]
It's on the list for the next release :+1:
