### ISSUE TITLE
Credit Cards in Firefly III treated as assets, not liabilities

### ISSUE THREAD

**Issue by Akaito** [firefly-iii/firefly-iii#4193]
I am running Firefly III version 5.4.6.

**Description**
I want to track a credit card in Firefly III.  Unfortunately, Firefly III treats credit cards as assets.  There's no option to change this behavior.  Any balance present on a credit card is not an asset, it's a liability.  It's not money you have, it's money you owe.  A credit card's max balance is also not an asset, just a max amount you can be borrowing at once.

**Extra info**
See treatment of credit cards in YNAB Classic, GNU Cash, I _think_ the US/EU reporting standards that GNU Cash and others are based on, etc.

Firefly III's FAQ has this to say:
> Note: Credit cards are not liabilities. You should use them as if they weren't a way to borrow money, but rather a way to use money that you have stored elsewhere (and that you will move to this account later).

It's true that credit cards should _ideally_ not be used to spend money you don't have.  However, in no way does an ideal use of borrowed money make that money an asset.

A credit card can never be a _boon_ to a person.  They can never liquidate it or otherwise use it as an asset.  Any interaction with a credit card incurs a financial burden.  Borrowed money that's owed in the future.  That's exactly what a liability is.  Whether or not that money also exists in a true asset account is irrelevant to accounting categories.

The possible impact on a person does not change categorization.  A car being an antique that gains value, or a commuter junker that loses value, doesn't change whether we-- in financial terms-- call it an asset or a liability.  Both cars are assets; things of some positive value at a point in time that can be liquidated for dollars.  Unlike credit cards, which only ever represent money owed.

If these reasons to fix the categorization of credit cards is unmoving, then at the least, I'd want to have the option to choose "credit card" as the account type for liability accounts, in addition to the existing choice for asset accounts.

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files  (N/A)
- [x] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
It's the way it is in Firefly III. You can add a credit card as a liability under liabilities if you want, but you have to do some magic calling it a "debt". Otherwise, nothing will be changed in the code.

**Comment by reivilibre** [comment]
I have to admit I am a bit confused about this one as well.

My first thought was: How about using it as an asset account with initial balance of 0? When you spend money on it, you're left with a negative balance (a debt?), which much resembles the 'overdraft' that your current account may have.

But then this seems to very much resembles the 'Liabilities' feature which I have only just played with now — however liabilities don't appear prominently on the front page or have easy buttons to create withdrawals.

Are there any downsides I didn't notice, of making a credit card an 'asset' with 0 initial balance and having everything be a negative balance thereafter (until it's paid back)?

**Comment by Akaito** [comment]
> 
> 
> I have to admit I am a bit confused about this one as well.
> 
> My first thought was: How about using it as an asset account with initial balance of 0? When you spend money on it, you're left with a negative balance (a debt?), which much resembles the 'overdraft' that your current account may have.
> 
> But then this seems to very much resembles the 'Liabilities' feature which I have only just played with now — however liabilities don't appear prominently on the front page or have easy buttons to create withdrawals.
> 
> Are there any downsides I didn't notice, of making a credit card an 'asset' with 0 initial balance and having everything be a negative balance thereafter (until it's paid back)?

I ran into these same problems.  I made a credit card account in the Liabilities category, gave it a type of "Debt", and then it doesn't show up on the main page.  I didn't find an option to change that.  So then I don't have easy tracking of credit card expenditures.  But, like you said, if credit cards are going to be treated as a special case liability by being put under the "Assets" category, why are we even using the classic Assets/Liabilities/Expenses/Revenue accounting categories?

I also tried adding a mortgage to Firefly III.  Used its built-in Mortgage type on a new Liability account.  Classically, a positive value in a Liability is money you owe.  With some software having options to flip the display (but not underlying value), for people who want those positive values to look negative.  Unfortunately, when I used Firefly III to track a mortgage, its positive value was _added to my net worth_.

It's at that point I realized Firefly III isn't for me.  Maybe when it has options to use accounts that behave in the way they do in other software, that match the classic definitions in accounting.  I want to like Firefly III; free, open-source, decent Web-based client with graphs, and plenty of categorizing/tagging features.  But I'm not going to bend over backwards redefining the way accounting works in order to use it.

**Comment by JC5** [comment]
This software is under constant development. Please keep the feedback coming, I appreciate it. :+1:

**Comment by beanaroo** [comment]
I was also having some trouble understanding how to use Firefly to manage Credit Cards. The software and documentation overall is fantastic! This area took a bit of discovery.

From what I can tell, in order to have:

- Credit Card accounts display on the dashboard
- Not adversely affect net worth
- Work with transfers from checking/savings accounts (repayments)

One has to set up an asset account (Credit Card Role) and treat it as an overdraft account (negated).

Something useful I didn't pick up until re-reading the help dialog when editing the account, is the affect of Virtual Balance.

>If you are creating a credit card account, enter the limit of your credit card (for example $1000,-). Firefly III will correctly display how far your limit is stretched.

This seems helpful but requires you to remember the limit for each card to be able to tell if it's paid off for the month. Especially when glancing at the graph on the dashboard.

Having Credit Cards as Asset Accounts still feels rather unnatural and needs a bit of tweaking to be manageable. Maybe having them as first-class Liabilities would enable a richer experience (I noticed the unused card repayment options) but I'm still new to the project so that may not be accurate or feasible.

Thanks for everything you've done so far, @JC5!

**Comment by reivilibre** [comment]
Is this resolved? I feel like the comment above suggests it could use documentation changes even if no functional changes.
(Unless I missed some changes?)

**Comment by JC5** [comment]
It's on my list to update the docs to reflect the feedback I got :+1:. I was just cleaning up for the migration to Discussions.

**Comment by reivilibre** [comment]
Fab, thanks! :)
