### ISSUE TITLE
Use key combination to navigate through transactions

### ISSUE THREAD

**Issue by SamBouwer** [firefly-iii/firefly-iii#4194]
**Description**

- I would like Firefly III to allow a user to navigate to the previous or next transaction when a transaction is being shown.
- This would make reviewing transactions easier

**Solution**

- Use (for example) alt + left arrow to navigate to the previous transaction 
- Use (for example) alt + right arrow to navigate to the next transaction

This could (maybe) be achieved by navigating to the current id +1 or -1, but I'm not sure how can be checked whether the transaction id exists. 

**What are alternatives?**
- Show buttons/icons in the window when a transaction is displayed to navigate between transactions.

**Additional context**
- none that I can think of

**Comment by JC5** [comment]
Good idea. I'm writing this down for the new layout :+1:
