### ISSUE TITLE
api/v1/about/user Internal Firefly III Exception

### ISSUE THREAD

**Issue by stratoss** [firefly-iii/firefly-iii#4195]
I'm checking out the API of FireFly III. After I've authorized myself with the demo credentials and executed the curl code generated from [this link](https://api-docs.firefly-iii.org/#/about/getCurrentUser) I've hit that exception.

**Steps to reproduce**
` curl -X GET "https://demo.firefly-iii.org/api/v1/about/user" -H  "accept: application/json" -H  "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNDJhZTZmMzliODg4YzdlYzAzZWM2NjUyODYwNGRiNGE0YjhiNGQ4MGY4OGViMzEwM2U5NmVhZDJkNjM4NmI0ZjY4MTgzYzEwYjkzOTc3OGQiLCJpYXQiOjE2MDkyNTk5ODEsIm5iZiI6MTYwOTI1OTk4MSwiZXhwIjoxNjEwNDY5NTgwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.XQs6jL9hB8eLwMZgCIc1QAWOB-GHkFX0dY_ZUPyjm-1X5H1Nu3ImnSa9vLYqmlbsIr_2QUr-TBAlJeIUxhct0CutWGzyyBnq7FCYFTtae0DorL2WSWe-QBAbJ-O6TFqMbTFDpXp8Gt0z6CWaeqTfmqiQJbxwEDF4RBKpOFS8zS8PSIALIxbmvEBzDsQttPfnySpSgQtlYDh0xS8Aab3VSmu2FN06BuZoBAX4wFeXhaLrmH6J8Ag5YD2E0YZGlz2lbzcH2RGcp_M5to9Pr__5ptlbxPdzKU1GgV2M8RxkECKKvbZJuYXtC8aGvjrpawnJdYoNR0MnJmMUSFn5hGSYO6gL3_PwGW8whPITy7yl19kFh8Q3G4fqNNVHVbDPJ0MNkeK5YVOuwLPtXXZSLLpQB0IiRWBze3nL5tsgtDGsf87wmFQUetKf-kDQdtoAY76Nt92GQhuRWj4hxd60rWvFwsXwnQMrbUjABxABfTQG2na780Wb9CvOXlAiVip6KDuGd9fCYbs70mo7N2gHMiR0Ql5guqLFM87OcS4sYHGdh8JS77A9LK1Tg5iDGuTvVa2SQNCe6cxK8akwVeNGcpTQd2_J5mPCV_YVqd0LgaTSP4ArrZ0aH-_NIaUEezFlSIdY5WSYzPWYI5ULLWvciqhJuMnT6FGEAFXq9m9WY6c9F7I"
`

Output returned: `{"message":"Internal Firefly III Exception: Call to a member function getRoleByUser() on null","exception":"Error"}`

**Comment by JC5** [comment]
Nice find, I guess that's a bug. Will be picked up!
