### ISSUE TITLE
PUT api/v1/accounts/{id} - Internal Firefly III Exception

### ISSUE THREAD

**Issue by stratoss** [firefly-iii/firefly-iii#4196]
**Bug description**
When trying to update a transaction via API I get the following error:
`Internal Firefly III Exception: Return value of FireflyIII\Support\Preferences::getForUser() must be an instance of FireflyIII\Models\Preference or null, string returned`

Full error from the logs: `Return value of FireflyIII\Support\Preferences::getForUser() must be an instance of FireflyIII\Models\Preference or null, string returned {"userId":1,"exception":"[object] (TypeError(code: 0): Return value of FireflyIII\\Support\\Preferences::getForUser() must be an instance of FireflyIII\\Models\\Preference or null, string returned at /var/www/firefly-iii/app/Support/Preferences.php:156`

**Steps to reproduce**
`curl -X PUT "https://demo.firefly-iii.org/api/v1/accounts/1" -H  "accept: application/json" -H  "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiMDhjZGUxNDIxY2FlNTc0Nzg3NmJhOWFkZjU5NTg5MTgwMzAwOGM2OTU2ZTMxMzI3OTg2MmMyMmEzNjViZWExYTk0ZjY4YjFiN2QzMjZkNmMiLCJpYXQiOjE2MDkzMDYxNTYsIm5iZiI6MTYwOTMwNjE1NiwiZXhwIjoxNjEwNTE1NzU1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.jSK7c0_t_4ZKM5tGeZnrRM7Bsh9i3JB1W_bEnXVOHla9XAf5kIyQWl2F1Ow44Vh83QfNsgBVgkfbF0nR1BXFOuZqAR2gXtXtJXjpWeYIeOpBd5bTTaoffo_ESWYa9O9-APlMhyCm0LyTp4l6Go8PUNARcnCfJ8StTzzkP3DUbcB_0tZgFFyMbqKyaec-wMV5aihmGSMeVylajWiuJaFyG-zBF4YM2vaZTKbG1oTNibxQEQEw_fSHU6AM4ghpZcrmSwViISezziwGm6mpO-U5OI8KgOHk5RvGhdwAwAnd2BuRSuSvSS7N4H2ctVyep6jErbeq5_DJlRQT4A1Z6p0DJPok1B_BT0xvV9yMzS7s2kcIwWKBlEnt1G1Kz6HIy-UGGRLBpU4DzD8JgZcMEk6kq4l6FqUHJnKMToAfZRpAW0H9FSoZqPR7Vr765n4tpIFIB1qdftoJg4tUNY0-XQKzQ4sq0vMdMwYRP_KnkIXPqjh5g1Zf9fexsl62g4ezzIYbMIujmpNWjzNLPLpWzbQuftSmHtpbndL0gJEX-ytYQXnozTEcFYqi1YEM2mbNZubzmj2avb7_cIGbfHCyvB9fUOeiYJtIdkujK3z1LWwBlblASAaJAH0csFA1PLEP74iuy7ofACdMlyFf7SndoPzQfGXAw5A1yIDtP4BDEQQJApI" -H  "Content-Type: application/json" -d "{\"name\":\"My checking account\",\"type\":\"asset\",\"iban\":\"GB98MIDL07009312345678\",\"bic\":\"BOFAUS3N\",\"account_number\":\"7009312345678\",\"opening_balance\":\"-1012.12\",\"opening_balance_date\":\"2018-09-17\",\"virtual_balance\":\"123.45\",\"currency_id\":12,\"currency_code\":\"EUR\",\"active\":false,\"order\":false,\"include_net_worth\":true,\"account_role\":\"defaultAsset\",\"credit_card_type\":\"monthlyFull\",\"monthly_payment_date\":\"2018-09-17\",\"liability_type\":\"loan\",\"liability_amount\":\"123.45\",\"liability_start_date\":\"2017-09-17\",\"interest\":\"5.3\",\"interest_period\":\"monthly\",\"notes\":\"Some example notes\"}"`

**Comment by JC5** [comment]
Can't replicate this unfortunately. I'll do some research.

**Comment by stratoss** [comment]
I'm attaching some more info from my machine. Hopefully it helps. The strange thing is that the error triggers only every 2nd or 3rd time when doing ~ 2 requests/second to that endpoint.

> 'version' => string '5.4.6' (length=5)
      'api_version' => string '1.4.0' (length=5)
      'php_version' => string '7.4.11' (length=6)
      'os' => string 'Linux' (length=5)
      'driver' => string 'mysql' (length=5)
