### ISSUE TITLE
Automatically set (expected) available amount for budgets

### ISSUE THREAD

**Issue by SamBouwer** [firefly-iii/firefly-iii#4198]
**Description**

- At the moment Firefly III only allows a user to set an (expected) available amount of money as a maximum for the budgets feature.
- It would be great it this could be set dynamically. 

**Solution**

Provide three options to set the available amount:

1. Set amount manually (currently the only option)
2. Let Firefly calculate what is expected as available amount based in previous month's income (useful for people with a steady and consistent income) 

**What are alternatives?**

3. Let the user select a(n existing) tag to determine which transactions from last month to use to calculate the available amount (useful for people with flexible/fluctuating income) 

**Additional context**

- This would hopeful help people to setup budgets a little bit easier. 

**Bonus points**

- Screenprint of the window where the suggested option could be added:

![Screenshot_20201230_075542_com microsoft emmx~2](https://user-images.githubusercontent.com/6918900/103338720-94a3d900-4a7f-11eb-8669-fb05bd41c924.jpg)

**Comment by JC5** [comment]
There used to be a function like this, but unfortunately zero people used it. It's a lot of work to build something reliably, so I decided to remove all the code and focus on other stuff.

I'll think of something like the budgets (auto-budget). I like the idea but I have to admin it's not at the top of my list.

**Comment by Tavlor** [comment]
Could it just be an option to copy forward the amounts from last month?

**Comment by JC5** [comment]
That's one of the many happy flows that will need to built, yes.

**Comment by dodger777** [comment]
> That's one of the many happy flows that will need to built, yes.

It could be perfect if you can add a rule to modify the available amount to budget like the piggy bank. :)

**Comment by JC5** [comment]
In the next release, I will make the "available amount" auto-calculated from the budgets you set. Since those can now be set automatically, the available amount setting makes less and less sense, and it only confuses people.

Based on your preferred view (ie weekly/monthly/yearly) Firefly III will auto update the available amount (multi currency) based on changes in budgets that fit the view (ie also weekly/monthly/yearly). The API will lose the ability to update them but you can still view them.

**Comment by SamBouwer** [comment]
That's awesome! Thanks!

**Comment by JC5** [comment]
Closed 'cause fixed.
