### ISSUE TITLE
Unable to update tags using API

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4199]
**Bug description**
I am running Firefly III version  5.4.6, and my problem is: I am unable to update tags from the API. Updating tags via the web interface works though. 

**Steps to reproduce**
1. Create tag
```
curl -X POST "https://demo.firefly-iii.org/api/v1/tags" -H "accept: application/json" -H "Authorization: Bearer xxxx" -H "Content-Type: application/json" -d "{\"tag\":\"some tag\",\"date\":\"2018-09-17\",\"description\":\"Some description\",\"latitude\":37.276675,\"longitude\":-115.798936,\"zoom_level\":6}"
```

2. Update tag

```
curl -X PUT "https://demo.firefly-iii.org/api/v1/tags/2" -H "accept: application/json" -H "Authorization: Bearer xxxxx" -H "Content-Type: application/json" -d "{\"tag\":\"some tag\",\"date\":\"2018-09-17\",\"description\":\"Some description\",\"latitude\":38.8977,\"longitude\":77.0365,\"zoom_level\":6}"
```

This is tested on my personal instance since the API playground isn't working for me.

**Comment by JC5** [comment]
Nice find. It breaks on the location, I'm working on a fix. I'll verify with the API playground and fix if necessary. Sometimes people delete the required API key.
