### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by ximex** [firefly-iii/firefly-iii#420]
Use OpenStreetMap with leaflet as map instead of google maps.
https://www.openstreetmap.org/
http://leafletjs.com/

**Comment by JC5** [comment]
The tag location is a pretty useless gimmick at the moment. It's an idea to switch to another map, but I might drop the tag location completely.

In the future, if any location function is used more extensively, I'll think about it :)

**Comment by JC5** [comment]
The first version of openstreetmap instead of Google Maps is live, with a mapbox.com layer. You can check it out on the [demo site](https://firefly-iii.nder.be/tags/edit/4).
