### ISSUE TITLE
Rules applied on (a lot of) existing transactions - Unrecoverable error

### ISSUE THREAD

**Issue by ajoaris** [firefly-iii/firefly-iii#4200]
**Bug description**
I am running Firefly III version x.x.x, and my problem is:
Created a new rule, trigger on a multiple string description. Transaction well selected when creating it. Applying it on existing transactions produced an unrecoverable error.

Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Argument 1 passed to FireflyIII\Factory\CategoryFactory::setUser() must be an instance of FireflyIII\User, null given, called in /var/www/html/app/TransactionRules/Actions/SetCategory.php on line 58

**Steps to reproduce**
As described above.

**Extra info**

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 

|Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2019-09-25 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15 |

**Comment by JC5** [comment]
Could you extract a stacktrace from your logs please? I'm curious to learn where this code is called.

**Comment by JC5** [comment]
Wait never mind, I can't read. Will be fixed in the next release but it's a symptom of underlying problems so I'm curious what will happen in the future.

**Comment by JC5** [comment]
Fixed in the latest beta, I'm closing this for consistency's sake.
