### ISSUE TITLE
Developed an package for fast Firefly III API utilization

### ISSUE THREAD

**Issue by stratoss** [firefly-iii/firefly-iii#4203]
Hello,

I have developed [a package](https://github.com/StanSoftBG/oauth2-firefly-iii) which utilizes the About, Accounts, Tags and Transactions API endpoints for a small personal project I'm doing at the moment.

If there is interest, I can extend the package to cover the rest of the API as well.

**Comment by JC5** [comment]
Cool! Yes please, if only so I can find inconsistencies and errors in the API 😁

**Comment by stratoss** [comment]
Just released a new version utilizing all available APIs. Couple of notes:
In the attachment upload endpoint I've sent a png file but got an error 'Mime type application/octet-stream is not allowed for API file upload.' at the Firefly instance logs. Also, application/json 'accept' header were sent, but html error returned.

If you find the package useful , maybe we can point somewhere in the documentation that it exists.

**Comment by JC5** [comment]
Absolutely! Updating the docs as we speak.

**Comment by nativeit** [comment]
Is this why the API docs seem to be missing just now?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4211
