### ISSUE TITLE
Make PWA manifest file use cookies

### ISSUE THREAD

**Issue by gtrubach** [firefly-iii/firefly-iii#4204]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is: when running Firefly under web_guard (Authelia) requests to PWA manifest file (manifest.webmanifest) are redirected to guard since request does not contain session cookie.

This causes incorrect PWA installation since manifest file is empty.

**Steps to reproduce**
1. Configure Firefly to use auth proxy
2. Open Firefly in browser in incognito window (to avoid cache).
3. Do authentication.
4. Go to dev tools -> Network and observe that manifest request response is 302 with the redirect to guard.

**Bonus points**
It's possible to fix it if `crossorigin="use-credentials"` will be set on manifest link in HTML - https://web.dev/add-manifest/#link-manifest

- I searched and nobody reported this bug before

**Comment by JC5** [comment]
I believe the tag you indicate here make the request **with** credentials rather than without.

If you want to make sure the web manifest is accessible outside of Authelia's authentication, use the following config (in Authelia itself):

```
    - domain: example.com
      resources:
      - "^/cron/.*$"
      - "^/manifest.webmanifest$"
      policy: bypass
```

**Comment by gtrubach** [comment]
Yes, this will work. With that tag it will just pass the session cookie to the guard and it won't redirect.

But if that tag was not set on purpose it's possible to workaround on guard side.

Anyway, thanks.

**Comment by JC5** [comment]
I'm not sure what you mean.

**Comment by gtrubach** [comment]
Auth proxy works in this way: when request does not have session cookie set it's not authenticated. When it's set and it's valid - request is authenticated.

All requests made to the app when using auth proxy have that session cookie set (authelia_session cookie for Authelia). This cookie is validated on each request by auth proxy.

That works this way for everything but manifest file. You wrote right - we can change it in auth proxy config. But another way to fix it is to make Firefly set that session cookie for manifest file request. That tag (cross-origin) just ensures that when manifest request will be made it will set the session cookie. With this there is no need to configure auth proxy to bypass manifest request.

**Comment by JC5** [comment]
Ah I see. I thought what you wanted to fix was to make the file publicly available, regardless of the user's authentication. Because that way, just like for example the favicons, the "add to homescreen" button would work better as well.

**Comment by gtrubach** [comment]
Language is a difficult thing. Sorry for that:)
