### ISSUE TITLE
System checks the acc. no. uniqueness across the Revenue and Expenses categories

### ISSUE THREAD

**Issue by masscream** [firefly-iii/firefly-iii#4205]
**Bug description**
I am running Firefly III version 5.4.6. And the system checks the account number uniqueness across the Revenue and Expenses categories.

**Steps to reproduce**
Create Expense and Revenue account with the same acc. number

**Extra info**
Debug information generated at 2021-01-02 11:03:00 Europe/Prague for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 62f73c75-4ba7-478e-ae05-0f388c4fdb55 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-01-31 23:59:59 |
| Session first | 2020-12-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | cs_CZ |
| Attempt at "cs_CZ.utf8" | 'cs_CZ.utf8' |
| Attempt at "cs_CZ.UTF-8" | 'cs_CZ.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Bonus points**
I believe it's just a small imperfection. Having accounts separated in Expense / Revenue categories isn't really bad idea, but there are also accounts which may fall in both categories and therefore there is a question if it is really necessary? Because then I need to deal with them as with 2 separate accounts. Of course I can just omit the account number in one of them and the trouble is gone but depends how the app is really supposed to work (from the author's and client's point of view). Anyway great project!

![Screenshot_2021-01-02_10-41-08_](https://user-images.githubusercontent.com/11753248/103455195-46930d80-4ceb-11eb-93ef-db826f3376d2.png)

**Comment by JC5** [comment]
I see what you mean. This already works as expected whe you use IBAN's. I'll make sure it also works like this for account numbers.

**Comment by masscream** [comment]
Thank you :+1:

**Comment by JC5** [comment]
This will be fixed in the new layout. The API responds correctly. The rules are detailed [in the documentation](https://docs.firefly-iii.org/firefly-iii/concepts/accounts/).

I'm going to close it, but the results of the fix won't be visible for some time I'm afraid.
