### ISSUE TITLE
Auto-budget amount does not work.

### ISSUE THREAD

**Issue by masscream** [firefly-iii/firefly-iii#4206]
**Bug description**
I am running Firefly III version 5.4.6. Auto-budget amount does not work.

**Steps to reproduce**
Create a month budget "Set fixed amount every period", looks like it generates the auto amount only for the month, it was created.

**Extra info**
Debug information generated at 2021-01-02 11:03:00 Europe/Prague for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 62f73c75-4ba7-478e-ae05-0f388c4fdb55 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-01-31 23:59:59 |
| Session first | 2020-12-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | cs_CZ |
| Attempt at "cs_CZ.utf8" | 'cs_CZ.utf8' |
| Attempt at "cs_CZ.UTF-8" | 'cs_CZ.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Bonus points**
I was struggling with the app, cause it displays the same amount in the Spent and Left Column. Then I realized, that there was not any Budgeted amount, but it has been defined when I created it. For the month I created the budget, the budgeted amount was there.

![Screenshot_2021-01-02_10-39-54_](https://user-images.githubusercontent.com/11753248/103456618-26b61680-4cf8-11eb-8d7f-bf0de3b3b0fd.png)

![Screenshot_2021-01-02_12-36-28_](https://user-images.githubusercontent.com/11753248/103456622-3170ab80-4cf8-11eb-91d9-31a69e92ebe3.png)

**Comment by JC5** [comment]
Is the [cron job](https://docs.firefly-iii.org/advanced-installation/cron) running correctly?

**Comment by masscream** [comment]
It looks like I haven't installed one. I put this below to my cron and hope the budgets will be refreshing now. Thanks.

`0 0 * * * /usr/bin/php /var/www/firefly-iii firefly-iii:cron`
