### ISSUE TITLE
Trigger "Recurring transactions" manually

### ISSUE THREAD

**Issue by idolux** [firefly-iii/firefly-iii#4208]
**Description**
If FF3 is down during maintenance or whatever happens the cronjob does not run and recurring transactions do not happen. It would be nice to be able to trigger "Recurring transactions" manually with a button

**Solution**
Add a button to trigger recurring transactions

**What are alternatives?**
All recurring transactions have to be added manually.

Another alternative solution would be to implement some kind of transaction templates which can be used to pay bills.

**Comment by JC5** [comment]
You can force the cronjob to run on arbitrary dates. Use `--force --date=YYYY-MM-DD`.

Otherwise, just clone any previous transaction.

**Comment by idolux** [comment]
That's a nice workaround, thanks.

**Comment by virgil9306** [comment]
Hi @JC5 

Is there a possibility to add such a button in the UI? Paying bills early when possible is a practice many people (aka "paying yourself first") have so this could be useful without having to dig into the terminal
