### ISSUE TITLE
Problem reaching https://csv-docs.firefly-iii.org

### ISSUE THREAD

**Issue by moguls753** [firefly-iii/firefly-iii#4209]
I was searching for the csv documentation, but can not reach the site https://csv-docs.firefly-iii.org due to security problems.
Error Code: SSL_ERROR_BAD_CERT_DOMAIN. Neither firefox nor chromium let me connect.

**Comment by JC5** [comment]
Thanks for letting me know. I'm migrating the documentation. It should be up and running again soon. Links may give 404, and I'm about to release a new version to fix that.

**Comment by moguls753** [comment]
Thanks for the quick reply and happy new year!

**Comment by moguls753** [comment]
Now its working again, thx.
