### ISSUE TITLE
Can't read documentation for installation. Status 404

### ISSUE THREAD

**Issue by Hertex** [firefly-iii/firefly-iii#4211]
If I try to open the documentation pages to see how I can install the software (e.g. for [docker](https://docs.firefly-iii.org/installation/docker/)) I always get a 404 status.

**Comment by nativeit** [comment]
API docs are 404 as well.

**Comment by JC5** [comment]
Yes, all documentation links are currently giving 404's. I'm aware of the issue and updating the links as we speak. Thanks for letting me know!
