### ISSUE TITLE
Error running budget report

### ISSUE THREAD

**Issue by meeb** [firefly-iii/firefly-iii#4212]
**Bug description**

Running "latest" container image tagged as `jc5x/firefly-iii:latest` which is `5.4.6`.

When running a budget report and selecting "all accounts" and a few budgets an error is generated:

`Typed property FireflyIII\Generator\Report\Budget\MonthReportGenerator::$expenses must be array, Illuminate\Support\Collection used`

**Steps to reproduce**

1) Go to reports -> Budgets
2) Select budget report, current month, all accounts, some budgets
3) Click submit

**Extra info**

FireFox 84 on Linux.

**Bonus points**

- I can't see this as an existing open issue
- [Debug info and stack trace](https://github.com/firefly-iii/firefly-iii/files/5761136/ffst.txt)
- No screenshot, it's just the default error page
- I was NOT able to replicate this on the demo site. Demo site budget reports work as expected with no errors, however, still opening an issue as it could still be an unpatched bug

If this is a duplicate issue or already fixed in the 5.5 alpha release the demo site is running feel free to ignore it.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4055

**Comment by meeb** [comment]
Ah, sorry, must have missed that when scanning the issues.
