### ISSUE TITLE
Migrating database

### ISSUE THREAD

**Issue by unintended-consequences** [firefly-iii/firefly-iii#4213]
I have an existing fireflyiii setup on a host via docker-compose with the db being postgres:10-alpine

The host just died so i'm recreating the containers. I notice the documentation now recommends:

yobasystems/alpine-mariadb:latest

is it worth me transferring over or should I keep using postgres?

**Comment by JC5** [comment]
Postgres should work fine. There is no need to migrate. Postgres is case sensitive so some searches may be more difficult. For example: "FLO" will not return "flower".

Barring this, postgres is a faster and better DB than MariaDB, so I suggest you keep Postgres :)
