### ISSUE TITLE
Cloning transaction sets the date to todays date

### ISSUE THREAD

**Issue by verticelo** [firefly-iii/firefly-iii#4214]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:
When I clone a transaction it sets the date of the transaction to todays date instead of the original date of the transaction.

**Steps to reproduce**
Clone a transaction and observe the date.

**Extra info**
The benefit of having the original date is whenever I import transactions I always get false positives on duplicate transactions and they are deleted. For example, some companies charge my card several times a day for the exact amount and they are detected as duplicates when they really are not.

One suggestion on the CSV importer would be to look at the the "External ID / Internal reference" that might be present from the bank. If it differs it shouldn't be classed as a duplicate.

Thanks for the great work on Firefly!

**Comment by JC5** [comment]
Hi,

Yes, the clone function sets the date to today, this is on purpose. 

> One suggestion on the CSV importer would be to look at the the "External ID / Internal reference" that might be present from the bank. If it differs it shouldn't be classed as a duplicate.

When you select it during the import, and store it in one of the meta fields, like internal reference, external ID or the notes, it will correctly recognize transactions.

**Comment by verticelo** [comment]
Hi JC5, my bad, thank you for the explanation. It seems that my bank sets the same external ID for some transactions even though they are not the same. Based on the CSV data there is not way of detecting a difference then and that is why the duplicate check fails.

Thanks for making Firefly! Great software!

**Comment by JC5** [comment]
:+1:
