### ISSUE TITLE
Unable to start import on csv-importer version-2.3.2

### ISSUE THREAD

**Issue by erwinkloosterboer** [firefly-iii/firefly-iii#4215]
**Bug description**
I am running FireflyIII csv importer on docker with tag version-2.3.2
Issue appeared after upgrading from version-2.3.1

The screen where you are supposed to start the import job stays mostly blank. Only the headers and the text `If the importer seems stuck, you can reset it.` appears.
A javascript ReferenceError was thrown (see extra info)

**Steps to reproduce**
- Start import job (tested with tab delimited (ABN) and csv (ING) statements
- go through mapping steps and press submit

**Extra info**

Tested on Safari (14.0.2) and Firefox (84.0.1).
```
ReferenceError: ImportStatus is not defined
    render https://example.com/js/app.js?version=2.3.2:2
    _render https://example.com/js/app.js?version=2.3.2:2
    r https://example.com/js/app.js?version=2.3.2:2
    get https://example.com/js/app.js?version=2.3.2:2
    cn https://example.com/js/app.js?version=2.3.2:2
    mount https://example.com/js/app.js?version=2.3.2:2
    $mount https://example.com/js/app.js?version=2.3.2:2
    _init https://example.com/js/app.js?version=2.3.2:2
    bn https://example.com/js/app.js?version=2.3.2:2
    99 https://example.com/js/app.js?version=2.3.2:2
    n https://example.com/js/app.js?version=2.3.2:2
    a https://example.com/js/app.js?version=2.3.2:2
    x https://example.com/js/app.js?version=2.3.2:2
    <anonymous> https://example.com/js/app.js?version=2.3.2:2
    <anonymous> https://example.com/js/app.js?version=2.3.2:2
app.js:2:277433
```

**Bonus points**

- I searched and nobody reported this bug before ✓
- I have added a stack trace from my log files ✓
- I have added a screenshot. 
![ratherEmpty](https://user-images.githubusercontent.com/1713774/103482930-aa94ff00-4ddb-11eb-95a4-f531b6aa4834.png)

**Comment by ilakast** [comment]
Have the exact same issue - thanks for raising this

**Comment by JC5** [comment]
I see it, thanks guys. Expect 2.3.3 soon.

**Comment by JC5** [comment]
2.3.3 is out!

**Comment by ilakast** [comment]
2.3.3 works a treat. Thanks!
