### ISSUE TITLE
API tags/tag-cloud 

### ISSUE THREAD

**Issue by stratoss** [firefly-iii/firefly-iii#4220]
**Bug description**
API endpoint `/api/v1/tag-cloud` returns `Internal Firefly III Exception: Method FireflyIII\Api\V1\Controllers\TagController::cloud does not exist.` instead of the tag cloud.

**Comment by JC5** [comment]
Thanks, I'll pick it up :+1:

**Comment by JC5** [comment]
Sorry, I've decided to drop this endpoint.
