### ISSUE TITLE
SPENT Per day

### ISSUE THREAD

**Issue by Marco1097** [firefly-iii/firefly-iii#4224]
I am running Firefly III version 5.4.6

**Description**
I have no budget and i get -1.00€ per day
![immagine](https://user-images.githubusercontent.com/23193188/103561394-b951e380-4eb9-11eb-932c-8f43f3e47c66.png)
What should the quantity indicate in "per day"?

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot

**Comment by Marco1097** [comment]
Ok, it has probably been fixed #4207

**Comment by niklas2810** [comment]
Yes, this has just been fixed in the PR you referenced :)

**Comment by JC5** [comment]
Fixed in the latest beta, I'm closing this for consistency's sake.
