### ISSUE TITLE
CSV Importer always hangs with no errors and nearly blank pages

### ISSUE THREAD

**Issue by bpgerber** [firefly-iii/firefly-iii#4225]
I am running Firefly III version 5.4.6

CSVimporter: v2.3.2

**Description**

I went through the entire process of csvimporter with the accounts that I have created in base Firefly (there are no checking account options or credit card options for asset accounts like in the documentation, but that's another issue). I am trying to import transactions for an IRA certificate account, a savings account, a credit card account, a checking account, etc... The access token said it was accepted as well as my site URL.

The CSV is in UTF-8 and doesn't fall into any categories on the FAQ. This is the format of my bank and my assignments:

Account Name | Processed Date | Description | Check Number | Credit/Debit | Amount
-- | -- | -- | -- | -- | --
ignore (custom name in FF3) | Transaction Processed Date | Description (Map data) | Notes | Generic Bank Credit or Debit | Amount

A typical description with be like this: 

`WITHDRAWAL ONLINE BANKING TRANSFER TO LOAN 8000`

or 

`WITHDRAWAL ACH CAPITAL ONE TYPE: MOBILE PMT ID: <IDNUM> CO: CAPITAL ONE ENTRY CLASS CODE: WEB`

Then I hit submit, the map data screen comes up completely blank, with only a submit option as [seen here](https://i.imgur.com/CqJXAdD.png). If I choose to submit, the import screen appears and nothing happens

**Import the data
Connect to Firefly III and store your data

If the importer seems stuck, you can reset it.**

It will hang on this page forever with no change to firefly base if I re-enter it, or have it up the whole time.

Here are the logs grabbed from Dozzle:

today at 8:05 PM  [2021-01-05 03:05:47] production.DEBUG: Constructed ImportRoutineManager  
today at 8:05 PM  [2021-01-05 03:05:47] production.DEBUG: Going to generate identifier.  
today at 8:05 PM  [2021-01-05 03:05:47] production.DEBUG: Attempt #1 results in "IBI5Cs7K394ehK7P"  
today at 8:05 PM  [2021-01-05 03:05:47] production.INFO: Job identifier is "IBI5Cs7K394ehK7P"  
today at 8:05 PM  [2021-01-05 03:05:47] production.DEBUG: Now in startOrFindJob(IBI5Cs7K394ehK7P)  
today at 8:05 PM  [2021-01-05 03:05:47] production.DEBUG: Try to see if file exists for job IBI5Cs7K394ehK7P.  
today at 8:05 PM  [2021-01-05 03:05:47] production.DEBUG: File does not exist or error, create a new one.  
today at 8:05 PM  [2021-01-05 03:05:47] production.DEBUG: Return status. {"status":"waiting_to_start","errors":[],"warnings":[],"messages":[]} 
today at 8:05 PM  [2021-01-05 03:05:47] production.DEBUG: Import routine manager identifier is "IBI5Cs7K394ehK7P"  
today at 8:05 PM  [2021-01-05 03:05:47] production.DEBUG: Stored "IBI5Cs7K394ehK7P" under "import_job_id"  
today at 8:05 PM  192.168.90.2 - - [05/Jan/2021:02:05:47 +0000] "GET /import/run HTTP/1.1" 200 1864 "<WEBSITE>" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
today at 8:10 PM  192.168.90.2 - - [05/Jan/2021:02:10:54 +0000] "GET /import/roles%22 HTTP/1.1" 404 6803 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
today at 8:11 PM  192.168.90.2 - - [05/Jan/2021:02:11:03 +0000] "GET /import/roles HTTP/1.1" 302 1533 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
today at 8:11 PM  192.168.90.2 - - [05/Jan/2021:02:11:03 +0000] "GET /import/mapping HTTP/1.1" 302 1513 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
today at 8:11 PM  [2021-01-05 03:11:04] production.DEBUG: Constructed ImportRoutineManager  
today at 8:11 PM  [2021-01-05 03:11:04] production.DEBUG: Now in startOrFindJob(IBI5Cs7K394ehK7P)  
today at 8:11 PM  [2021-01-05 03:11:04] production.DEBUG: Try to see if file exists for job IBI5Cs7K394ehK7P.  
today at 8:11 PM  [2021-01-05 03:11:04] production.DEBUG: Status file exists for job IBI5Cs7K394ehK7P.  
today at 8:11 PM  [2021-01-05 03:11:04] production.DEBUG: Import routine manager identifier is "IBI5Cs7K394ehK7P"  
today at 8:11 PM  [2021-01-05 03:11:04] production.DEBUG: Stored "IBI5Cs7K394ehK7P" under "import_job_id"  
today at 8:11 PM  192.168.90.2 - - [05/Jan/2021:02:11:04 +0000] "GET /import/run HTTP/1.1" 200 1864 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
today at 8:11 PM  [2021-01-05 03:11:14] production.DEBUG: Constructed ImportRoutineManager  
today at 8:11 PM  [2021-01-05 03:11:14] production.DEBUG: Now in startOrFindJob(IBI5Cs7K394ehK7P)  
today at 8:11 PM  [2021-01-05 03:11:14] production.DEBUG: Try to see if file exists for job IBI5Cs7K394ehK7P.  
today at 8:11 PM  [2021-01-05 03:11:14] production.DEBUG: Status file exists for job IBI5Cs7K394ehK7P.  
today at 8:11 PM  [2021-01-05 03:11:14] production.DEBUG: Import routine manager identifier is "IBI5Cs7K394ehK7P"  
today at 8:11 PM  [2021-01-05 03:11:14] production.DEBUG: Stored "IBI5Cs7K394ehK7P" under "import_job_id"  
today at 8:11 PM  192.168.90.2 - - [05/Jan/2021:02:11:14 +0000] "GET /import/run HTTP/1.1" 200 1864 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"

**Extra info**

Using firefox to access a docker self-hosted setup through a reverse proxy no-auth chain and ad blockers turned off.

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I haven't tried the demo site yet

**Comment by JC5** [comment]
Upgrade to 2.3.3. That should fix the issue 👍🏻

**Comment by bpgerber** [comment]
That did fix the import question. There is still no mapping.

In the "description" column, there is:

- the name of the merchant
- withdraw/deposit (duplicate of credit/debit column for some reason)
- "Data" (payment, bill pay, rent, etc...)

Is mapping this not supported? I'm a bit confused what can be mapped.

**Comment by JC5** [comment]
You can't map stuff inside columns unfortunately. You should create rules in Firefly III itself to do the fine-tuning in that case.

**Comment by bpgerber** [comment]
Perfect, thanks!
