### ISSUE TITLE
Spectre importer missing vue component

### ISSUE THREAD

**Issue by alexolivier** [firefly-iii/firefly-iii#4227]
**Bug description**
I am running Firefly III Spectre importer  version 2.1.1, and my problem is it is throwing a JS error about a missing Vue component when importing:

![image](https://user-images.githubusercontent.com/1760534/103629666-87cc2d00-4f38-11eb-9e17-767774f2281e.png)

**Steps to reproduce**
- Create an import job
- Submit it
- Open a console on loading page

**Extra info**
- OSX, Edge

**Comment by JC5** [comment]
Check out 2.1.2, where this should be fixed :+1:

**Comment by alexolivier** [comment]
Can you publish the docker image please? 

Can't see it here. I'm currently using :latest

https://hub.docker.com/r/fireflyiii/spectre-importer/tags?page=1&ordering=last_updated

**Comment by JC5** [comment]
I see the built failed but reported green. Stay tuned

**Comment by alexolivier** [comment]
Working now! Thank you :)
