### ISSUE TITLE
[CSV Importer] Broken links in documentation

### ISSUE THREAD

**Issue by SamBouwer** [firefly-iii/firefly-iii#4230]
Most links on the CSV Importer introduction page on the Firefly III documentation site are broken. It seems that the /csv part in the URLs are missing. On other pages, the links seem correct.

For example, when you browse to https://docs.firefly-iii.org/csv, the "Install and Running" > "Configuration" link in the menu on the left point to https://docs.firefly-iii.org/install/configure/ which returns a 404. If you edit the URL to https://docs.firefly-iii.org/csv/install/configure/, you land on the right page.

If you are on a page below https://docs.firefly-iii.org/csv/ already, for example https://docs.firefly-iii.org/csv/install/docker/, all links work fine.

**Comment by JC5** [comment]
I noticed, yep. Not sure yet what's happening, the local render seems fine. I'll patch it up!

**Comment by JC5** [comment]
And now it seems to be fine. It may be a CDN / cache issue

**Comment by JC5** [comment]
Root cause is that Azure static pages doesn't redirect https://docs.firefly-iii.org/csv to https://docs.firefly-iii.org/csv/. I added a fix. Once the various CDN's and caches are up to date, the problem should be gone.

**Comment by SamBouwer** [comment]
Seems to have fixed it! Thanks! :)
