### ISSUE TITLE
Reconciling transaction: allow deleting/merging

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#4232]
First of all, Happy new Year :)

**Description**

My workflow, even if I know it is not 100% firefly-iii compliant, is:
1. Insert "human" transactions in firefly-iii, with tags/category/budget/...
1. Create automatic/recurrent transactions as reminders
1. Periodically, import transaction from bank exports, to get everything I missed and add technical fields like Transaction ID, Order number, and so on
1. Manually join/remove duplicates (manual/recurring+bank transactions) keeping the most info I can

The last point is the most time consuming of the whole flow, I usually end up deleting the manual transaction, copying description/category/tags.

Btw I don't usually use the reconcile view, I just follow the transactions list using batch editing.

**Solution**

Imho the reconcile view could be more useful with:
- grouping similar transactions together (using date+amount), perhaps recycling the split transaction view
- an additional checkbox to mark a transaction as slave, to be deleted, if and only if there is more than one transaction in the group

Since the bank transaction has usually more data (transaction id, specific time/date, currency data, and so on), the "CSV Import" tag could be used to identify the master transaction (the imported one) and it could merge with the slave one, deleting the latter.

**What are alternatives?**

It is not quite the same, but perhaps a facility in the edit view to specify a transaction to merge with the edited one (deleting/flagging the merged one) could be easier to implement. It could be reused the "transaction" field in the "Add Link" modal: select a transaction, merge data (maybe showing what is being copied), delete the slave transaction when saving the master one.

Either that, or keep doing it manually :)

**Comment by JC5** [comment]
This is something I'll pick up in the new layout :+1:
