### ISSUE TITLE
CSV importer seems to truncate description at 32 char

### ISSUE THREAD

**Issue by nvanheuverzwijn** [firefly-iii/firefly-iii#4233]
I am running Firefly III version latest docker which would be 5.4.6.

**Description**
When importing CSV file with csv importer, it seems that the description field truncates at 32 character. Is it something that is happening on your end ?

**Extra info**
Debug information generated at 2021-01-05 22:50:55 America/Toronto for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | ef93f5b2-2c1c-4eaa-8c48-aeafaf01b74e |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-01-31 23:59:59 |
| Session first | 2020-01-02 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 |

**Comment by JC5** [comment]
It may depend on your DB but it cuts of at 1000 characters. I believe the field in the DB is around 256 chars for most people.

<img width="698" alt="Screenshot 2021-01-06 at 06 26 48" src="https://user-images.githubusercontent.com/5889984/103732707-d680d200-4fdf-11eb-8a65-488a67c85bb7.png">

**Comment by nvanheuverzwijn** [comment]
@JC5 Hey, I just realized my CSV files are corrupted :| So sorry for bothering you. Thanks for the answer and the great software. Hope I can contribute soon. Thanks!

**Comment by JC5** [comment]
No worries, hope you can get the files fixed :+1:
