### ISSUE TITLE
csv-importer preprocessing for weird files

### ISSUE THREAD

**Issue by Akuma737** [firefly-iii/firefly-iii#4234]
I am running Firefly III version 5.4.6
**Description**
I'm currently trying to import a full transaction csv from paypal through the csv importer. But I can't find any convenient way to map the csv into firefly.
Especialy for foreign money transactions the "real" transaction consists of 3 lines:
* transaction in foreign currency
* negative value in regular currency
* positive value in foreign currency
to make a usefull transaction for firefly I thought about parsing the csv into some kind of parser to condense these multi lines to one line like:
`"Date","Time","TimeZone","Name","Type","Status","Currency","Amount","Receipt ID","Balance"`
`"30/01/2014","20:16:34","CET","","General Currency Conversion","Completed","EUR","-0,77","","0,00"`
`"30/01/2014","20:16:34","CET","","General Currency Conversion","Completed","USD","1,00","","1,00"`
`"30/01/2014","20:16:34","CET","payment to company xy","Express Checkout Payment","Completed","USD","-1,00","","0,00"`
to
`"Timestamp","Name","Type","Receipt ID","Currency","Amount","ForeignCurrency","ForeignAmount"`
`"30/01/2014 20:16:34 CET","payment to company xy","Express Checkout Payment","","EUR","-0,77","USD","-1,00"`

How would be the best way to go about something like that.
* From what i understand the intended way for something like that would be to write a custom "specifics php".
* My standard tactic would be to add some kind of regex preprozessor to the csv import.

so to clarify my question is the intended way for such a case to write a custom "specifics php"?
and if so could we add some kind of regex preprocessor so it could be defined in the import json?(i'd be willing to do that task if you could point me in the right direction where the best place would be to add such code)

**Bonus points**

- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by Akuma737** [comment]
After more digging into the specifics class it looks like only single line edits are possible so implementing a multi line parser as a specifics would probably not work...
Considering that I think the only possible way would be to implement some new preparser funktion.
Is that something you would consider allowing in the csv importer or is that something you would prefer not to get added(since it could make the importer more complex while only giving flexibility for very wierd edge cases)

**Comment by Akuma737** [comment]
The more I think about it the preparser would have to be between the upload and the config for mapping so the mapping config can still be done with the preparsed csv.
So there would have to be a 4th field added on the initial upload form to add a custom regex for preparsing in case there is no json uploaded and that string would have to be kept in memory somewhere till the end of the config step to add it to the full json you can download at the end and in case there is a json added it would have to fetch the regex if there is one preparse file and go to configuration steps with result of that file.

**Comment by JC5** [comment]
Thanks for the feedback, I appreciate it. As for the "specifics", these will be removed in a future version of the CSV importer.

Just like you correctly conclude, adding solutions like regex parsers, little code bits and other solutions are a never ending game. Eventually the CSV importer will become 90% custom parser, 10% actual code. Something I'd like to prevent, as you can image.

I haven't found a sustainable solution to this problem. Plug-ins come to mind, but those turned Wordpress into a backdoor with a weblog attached to it. Plugins are also fragile, and may need extended work whenever the importer changes. 

Luckily, as many users are there are, most special exceptions are just one or two users, giving me less pressure to put something into the importer. But it still requires... something I guess.

**Comment by Akuma737** [comment]
Like you allready said the inevitable thing is it turning into a 90% custom parser.
Thats why im suggesting a custom regex preparser because a regex preparser in combo with a configurable csv parser(like the one that allready excists) should make every case possible without letting users injekt foreign code into the project.(regex should probably be prevalidated for extra security)

**Comment by Akuma737** [comment]
so to bring the question to a point would you accept a pull request to add a regex preparser to the first step of the importer or do i have to find another way?

**Comment by JC5** [comment]
No, you'll have to find another way.
