### ISSUE TITLE
Info popup in Expenses of standard financial report does not apply report's account filter

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#4235]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

The info popup of the expenses (top 10) in the standard financial report, does not take the account filter of the report into account.
The column in the table in the report does.

**Steps to reproduce**
Load the financial report, with a subset of accounts selected.
Make sure you have expenses in that period, from an account that is not in the selection.
In the Expenses list, the destination account is shown, the total amount of that destination account seems correct, but the info popup shows expenses from accounts that are not part of the selection of the report and the info popup has a different total.

**Comment by JC5** [comment]
Cool, I'll check it out :+1:
