### ISSUE TITLE
recurring transactions help page 404

### ISSUE THREAD

**Issue by Akuma737** [firefly-iii/firefly-iii#4236]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

on the "recurring transactions" page the "help for this page" has the link "https://docs.firefly-iii.org/advanced-installation/cron" instead of "https://docs.firefly-iii.org/firefly-iii/advanced-installation/cron/" under 
"Cron job 
In order to actually create the transactions automatically, you need to set up a cron job. You can read about that on the **page in the official documentation about cron jobs**."

**Steps to reproduce**
go to automation -> recurring transactions -> "help button" -> page in the official documentation about cron jobs

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Fixed :+1:
