### ISSUE TITLE
Quick or bulk add category to imported transactions

### ISSUE THREAD

**Issue by mrwolf78** [firefly-iii/firefly-iii#4238]
I'm new to Firefly, and I've imported a year of transactions, all looking good. For the common and repeating transactions (rent, groceries, salary etc) I've added rules to categorize them, and this works fine. Loving this tool so far.

Is there a quick way to quickly categorize remaining transactions from a list view or something? I have quite a lot of one-off transactions that I'd like to quickly categorize (one time visit to restaurant X, one time purchase from webshop Y etc). There must be a way, I just can't find it ;)

What I'm doing right now is:
- create a search for uncategorized transactions
- Open the top one
- Click actions
- Click edit
- Change category
- Save
- Go back to the search screen and do the next

It's quite cumbersome, and I have a few 100 transactions to go through, so any help is appreciated!

If this is the only way, I'm thinking of deleting all transactions, and add categories manually to the csv-import as a workaround.

**Comment by sephrat** [comment]
You can search with keyword "has_no_category:true" in the top left corner, then select all found transactions and click 'Edit". You should be able to mass type categories for each transaction.
https://demo.firefly-iii.org/search?search=has_no_category%3Atrue
![image](https://user-images.githubusercontent.com/34862846/103872571-e62b1400-50ce-11eb-9d5f-4c351c48dcd4.png)

**Comment by mrwolf78** [comment]
Yes, that's what I searched for, thanks! I was only using 'bulk edit', and totally skipped 'edit' from the search results...
