### ISSUE TITLE
[Question] Docker database location

### ISSUE THREAD

**Issue by CodaAmok** [firefly-iii/firefly-iii#424]
Hello

I like to use data containers where possible, do you know where in the ufs of the container the db is? So, say, if a new version was released or I destroyed the container, I could hotswap the database container and restore from where I left off.

Cheers, coda

**Comment by JC5** [comment]
@schoentoon or @Blackclaws may be able to answer this one.

**Comment by schoentoon** [comment]
Including the description somewhere I gave in the original pull request https://github.com/JC5/firefly-iii/pull/364 is probably a good idea.

**Comment by Blackclaws** [comment]
In my dockerfile I created the database in a second container where you can determine where to mount the db location.

**Comment by Blackclaws** [comment]
@schoentoon Since I also created a dockerfile which is slightly different should we merge them somehow or ship both?

**Comment by schoentoon** [comment]
I currently run the on an image with the current dockerfile. And I do run the database in a second container (the stock mysql image). So yes, we can probably somehow merge them together @Blackclaws

**Comment by JC5** [comment]
I would suggest a pull request on the current one, and maybe a small readme?
