### ISSUE TITLE
API tags/deleteTag not finding tag

### ISSUE THREAD

**Issue by stratoss** [firefly-iii/firefly-iii#4240]
**Bug description**
Unable to delete certain tags

**Steps to reproduce**
We're able to create and update the following tag for example: 'Хранителни Стоки > Яйца'. However, when trying to delete it by name the TagOrId binder logs 'tag not found.'

**Comment by JC5** [comment]
I need a bit more details than this. Creating, updating and deleting a tag labelled "Хранителни Стоки > Яйца" works fine for me.

**Comment by stratoss** [comment]
I've just ran the following code against the demo API (demo.firefly-iii.org) using client ID = 4

> $test = $provider->storeTag($_SESSION['token'], ['tag' => 'Хранителни Стоки > Яйца']);
		echo 'Storing tag...';
		print_r($test);
		$test = $provider->updateTag($_SESSION['token'], 'Хранителни Стоки > Яйца', ['tag' => 'Хранителни Стоки > Яйца2']);
		echo 'Updating tag...';
		print_r($test);
		$test = $provider->deleteTag($_SESSION['token'], 'Хранителни Стоки > Яйца2');
		echo 'Deleting tag...';
		print_r($test);


The result is:

> Storing tag...Array
   ...
                        [created_at] => 2021-01-08T07:06:18+01:00
                        [updated_at] => 2021-01-08T07:06:18+01:00
                        [tag] => Хранителни Стоки > Яйца
                        [date] => 
                    [description] => 
                    [longitude] => 
                    [latitude] => 
                    [zoom_level] => 

    Updating tag...
    ...
                    [created_at] => 2021-01-08T07:06:18+01:00
                    [updated_at] => 2021-01-08T07:06:18+01:00
                    [tag] => Хранителни Стоки > Яйца2
                    [date] => 
                    [description] => 
                    [longitude] => 
                    [latitude] => 
                    [zoom_level] => 
    Invalid response received from Authorization Server. Expected JSON.


The error when trying to delete the tag is because the API returns an empty string as response. In my FireflyIII instance the following log appears when testing: 'TagOrId: tag not found.'

Hopefully that helps.

**Comment by JC5** [comment]
Is the response code 204 no content? Or is the response code 404?
