### ISSUE TITLE
Tag report chart 'Expenses per destination account' is broken

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#4241]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is: a chart on the tag report is broken.
![image](https://user-images.githubusercontent.com/34862846/103988783-f5719680-518e-11eb-8f06-236d91041959.png)
Happens on my 5.4.6 installation and on demo website.
https://demo.firefly-iii.org/chart/tag/dest/expense/41,6,1,5,4,40,2,3,42/71/20210101/20210131 gives a 500 error
"Internal Firefly III Exception: Target class [FireflyIII\\Http\\Controllers\\Chart\\tagReportController] does not exist."

**Comment by JC5** [comment]
Thx, I'll check it out. Not sure what's happening.

**Comment by sephrat** [comment]
Ah I think I see it. the T in tag should be uppercase like in above and below statements.
https://github.com/firefly-iii/firefly-iii/blob/f42bd19c1c59fa9af22c2bf3e1cb4a2c585a84bb/routes/web.php#L461

**Comment by JC5** [comment]
Fixed, will be part of the new release!
