### ISSUE TITLE
Bug when adding transaction

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4242]
Hi. I'm not sure if this is a bug in demo or alpha version of Firefly III. When adding a new transaction via the API and web interface, the error occurs

```
Error! Internal Firefly III Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'demo.webhooks' doesn't exist (SQL: select `webhooks`.* from `webhooks` where `webhooks`.`user_id` = 1 and `webhooks`.`user_id` is not null and `active` = 1 and `trigger` = 100 and `webhooks`.`deleted_at` is null)
```

![image](https://user-images.githubusercontent.com/5896415/104006120-2dfa8a00-51fa-11eb-97ef-ddfc46695132.png)

**Comment by JC5** [comment]
Thanks, that's a bug in the demo. I'll double check what the script currently is :+1:

**Comment by JC5** [comment]
Fixed :+1:
