### ISSUE TITLE
Add an expense based on a rule

### ISSUE THREAD

**Issue by timohzbs** [firefly-iii/firefly-iii#4244]
**Description**

Please describe your feature request:

- I have my main bank account and a Revolut credit card. If I want to add money to Revolut I can use Klarna Sofort as payment type instantly transfer money to the credit card. There is a small 1,5€ fee on every transaction.

- In Firefly (which is awesome) I added both accounts. If I want to transfer 20€ to Revolut, I will have to pay 21,5€ for it.

**Solution**
- Adding a rule that automatically detects this specific transfer and creates an expense of 1,5€

**What are alternatives?**
- Do it manually

**Additional context**
♥️

**Bonus points**
Earn bonus points by:
- Donate money (just kidding ;)
 ✌🏼will do it, I promise!

**Comment by JC5** [comment]
Sorry, the rule engine won't be able to create transactions by itself. Is the fee not listed as a transaction as well?

**Comment by timohzbs** [comment]
Okay, that would be really great to have this kind of function.

unfortunately not, I transfer 20€ to the cost of 21,5€. The amount will be always 1,5€ less then I choose to transfer.

**Comment by timohzbs** [comment]
Currently not possible.
