### ISSUE TITLE
Change password behavior and other settings

### ISSUE THREAD

**Issue by Chaoschaot232** [firefly-iii/firefly-iii#4245]
Like stated, I have a big problem with the hardcoded password setting also I can not find the main administrativ settings only the user ones.

Where can I find the main administrative settings to change e. g. the password behavior or the user management page?
Smth. should exists there to have only one real administrative account and use normale non-admin accounts.

Would be nice to get that information, tahnks :)

**Comment by Chaoschaot232** [comment]
I referenz #3895 to this issue because each modern software has a stable ACP, means Administrative Control Panel like Gitlab it has to manage all users and there roles or to change the min. password length or what has to be in a password and so on.

This is nothing to be hardcoded or to be hidden. It has to be available for individual change. I hope you can understand this.

**Comment by JC5** [comment]
Please don't lecture me on what software should or shouldn't have. Your tone feels condescending. Thank you.

The first user to register themselves will get admin rights automatically. The easiest way to check this is by browsing to `/admin`. If this link doesn't work, please verify in the database that the `roles` table has two entries, owner and demo. 

The `role_user` should have at least one entry. The `user_id` should be your user ID, which you can see under `/profile`. The role_id should be the id of the row where `name` = `owner` in the `roles` table. If it's missing it's easy to add it yourself. That should enable the admin pages under `/admin`.

If you feel the 16-char length of the password doesn't work for you, you can setup [LDAP](https://docs.firefly-iii.org/firefly-iii/advanced-installation/authentication/#ldap) yourself and configure that to be more lenient. There will be no option in Firefly III to change the password requirements.
