### ISSUE TITLE
CSV Importer: Handle stray delimiters

### ISSUE THREAD

**Issue by anoma** [firefly-iii/firefly-iii#4246]
Reporting when Firefly III CSV Import Tool, v2.3.3 was latest

My banks csv exports are pretty bad. My main issue is that they for some strange reason prepend a random `'` character to _some_ text fields.

```

Date, Type, Description, Value, Balance, Account Name, Account Number

08/01/2021,POS,"'Sid",-10.00,1234.56,"'Joint Account","'112233-44556677",
05/01/2021,POS,"'Nancy",-10.00,1224.56,"'Joint Account","'112233-44556677",
06/01/2021,POS,"'Jane",-10.00,1234.56,"'Joint Account","'112233-44556677",
```

This is a redacted real export with fake data but _real_ in all the ways that matter.

Notice `'Sid` and not `Sid` and also `"'112233-44556677"` and not `"112233-44556677"`.

Just to make it extra annoying notice `POS` is a value in the Type text filed but doesn't have this issue.

This feels like quite an edge case but equally I have zero chance of the bank fixing this at my request. I can obviously do some sanitisation after export but before import but if there was any way to cater for this natively it would be well received.

**Comment by JC5** [comment]
It feels like something they'd do to facilitate Excel, which is ironic since Excel will handle this perfectly fine when importing CSV files. It's not something I can catch in the CSV importer, I'm afraid.

**Comment by anoma** [comment]
Thanks for taking the time to respond. I will close this ticket down but later tag whatever standalone solution I come up with in case anyone falls on a similar issue.

Thanks again for both this and the project. It really does benefit real people in real ways.

**Comment by anoma** [comment]
For posterity, this is the simplest and most reliable method I could think of to pre-process a statement for cleaner import into Firefly-iii replacing `,"'` with `,"`

`perl -pi.bak -e "s/,\"'/,\"/g" test.csv`

The original will be altered but a backup made. If anyone does try this please also make a manual backup first so there is no risk of losing data.
