### ISSUE TITLE
CSV Importer Webside not correctly written

### ISSUE THREAD

**Issue by Chaoschaot232** [firefly-iii/firefly-iii#4259]
To import my transactions I installed your importer but getting these errors in Chrome:

![image](https://user-images.githubusercontent.com/1703441/104150351-f5190b80-53d9-11eb-989f-4b1879321d89.png)

This means, that http is hard coded which is not a coding standart today. Normaly you do not use http(s) at the beginning, only the url without the protocol so that the url request gets handled by the server itself.

Would be nice if you could change this. For now, I must do this on my own.

**Comment by JC5** [comment]
No it's not. It's a configuration error in your reverse proxy.
