### ISSUE TITLE
Create a budget from a category

### ISSUE THREAD

**Issue by ClementNerma** [firefly-iii/firefly-iii#4260]
Hi there!

First of all thanks for making this amazing software, I've been using Firefly for a bit and I'm really enjoying it! So much nicer than my previous basic spreadsheet.

Now I have a question about budgetization. I always categorize all my operations, and I'd like to make a budget for e.g. food and taxes that would be filled from categories.

Which means "auto-"assigning a budget from the category, instead of manually selecting both the category and the budget from the dropdown each time.

Also, I'd like to know if there was a setting I hadn't seen to _enforce_ categorization? I'd like to be sure I didn't forget to categorize something, without checking by themselves regurarly in the app.

Thanks in advance!

**Comment by JC5** [comment]
👍

You could do both with rules. Use the trigger "has category" or "has category" and add the necessary actions.

**Comment by ClementNerma** [comment]
Wow thanks for the quick answer!

I didn't see that part in the UI, thanks!

I don't see any rule that can prevent an operation from being created if rules don't match though, it seems the best I can do is prefix the operation's name by something like `[ CATEGORY IS MISSING ]` to catch my eye.

Is it possible to prevent the operation from being created instead?

**Comment by JC5** [comment]
No problem!

No, you can't force a block. Best you can do is set a standard category. But be sure to check out this list of transactions: https://demo.firefly-iii.org/categories/list/no-category

Your own installation has the same page. Hope this helps!

**Comment by ClementNerma** [comment]
Ok, thanks for your help!
