### ISSUE TITLE
Budget saving

### ISSUE THREAD

**Issue by ClementNerma** [firefly-iii/firefly-iii#4261]
**Description**
Currently, budgets are only meant to track how much money was _spent_ and to quickly check if we spend more or less than what we've budgeted.

What would be nice would be to also have budgets for savings. For instance, let's say I plan to save $200 each month. I'd like to make a budget from that, which ensures I indeed save $200 by transferring it to a specific bank account.

I don't know if this would be hard to make, but the current budget system isn't adapted for this task.

**Solution**
Have a budget option with a target sum which starts from zero and fills up when transferring money to the bank account registered in the budget.

Tell me if that seems relevant or not :)

**Comment by wjbridge** [comment]
What about the [piggy bank](https://docs.firefly-iii.org/firefly-iii/advanced-concepts/piggies/) feature? Does that solve your problem?

**Comment by ClementNerma** [comment]
> What about the [piggy bank](https://docs.firefly-iii.org/firefly-iii/advanced-concepts/piggies/) feature? Does that solve your problem?

Ah, I forgot to mention it. The piggy banks aren't really well-suited for this type of operation because it'd need to be re-created every month, which is less than ideal.

**Comment by JC5** [comment]
Instead of saving money, save everything, and put back what you need.

https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/personal-finances/

**Comment by ClementNerma** [comment]
That's a whole different process than just indicating how much has been put aside from a bank account for instance.

The money management process described in the document you linked to is a choice, and personnally I don't agree with this method (not to say it's a bad one at all, just that I prefer to have a simple budget like I described in my initial comment, and I think it's a simpler option for most people).
