### ISSUE TITLE
[CSV importer] Add and pre-select empty "Default import account"

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#4262]
**Description**
Premise: my bank does not add in the CSV export a field to identify the From Account.

It happened to me more than once that while importing a CSV with a pre-made configuration file I forgot to look at the Default Import Account value and everything was imported in the Amazon account (since it is the first one alphabetically).

Since it is basically the only variable field when importing a template from a configuration file, imho it is easy to overlook.

**Solution**
Add a pre-selected empty option that blocks the submit if an account is not explicitly selected.

**What are alternatives?**
Triple checks before importing? :)

**Bonus points**
I can provide a PR if needed, even if it is probably easier to add

`<option label=""></option>`

in [this](https://github.com/firefly-iii/csv-importer/blob/5ee9278a9d46cfe81b5492f2702049d876e2883e/resources/views/import/configuration/index.twig#L90) file.

Thanks

**Comment by JC5** [comment]
No, sorry. 

The selected value for the checking account is also present in the config value. I'm not sure what you mean?
