### ISSUE TITLE
Can't create a deposit

### ISSUE THREAD

**Issue by ClementNerma** [firefly-iii/firefly-iii#4263]
**Bug description**
I am running Firefly III v5.4.6 (currently latest stable), and I don't know if I'm just dumb but I can't seem to make a deposit in the interface.

I get *exactly* the same screens when creating a deposit than the one I get for a withdrawal. The free form fields and non-free ones are the same as well. Here is a screenshot:

https://user-images.githubusercontent.com/9782521/104250537-14fa0f00-546e-11eb-94c1-07f35db1522b.png
https://user-images.githubusercontent.com/9782521/104250550-1c211d00-546e-11eb-80cb-f38d47719be5.png

The source accounts I can select and the destination ones are exactly the same for a withdrawal and a deposit, meaning I can't actually make a deposit. When I make the deposit and select the actually target one as the "source account" and specify an amount, after creation the operation goes right into the "withdrawals" section and the "deposit" one remains empty.

This seems like a bug that cannot have been missed during testing, but I can't figure _how_ to make this work correctly.

**Steps to reproduce**
Create a withdrawal or a deposit.

**Extra info**
Windows 10 20H2, Chrome v87, no error nor warning in the console, fresh installation.

Thanks in advance for your help !

**Comment by JC5** [comment]
Indeed, the forms are the same. 

Why don't you type in a new source account and then select a destination? Or just type the destination? The source field and destination fields are free format for a reason.

Except for asset accounts (and loans), any account you type in that doesn't exist gets created.

**Comment by ClementNerma** [comment]
The source field isn't free format, and the doc indicates only the revenue (source) account should be:

```
Deposits have free-format field for the "revenue account". This works in the same way as withdrawals do.
```

What I'd like to do is, assuming i have a bank account `A` for instance, is to make a for instance +50$ deposit from by company's account (which would be created during the operation like for an expense account). Which means I'd select the `A` account from the dropdown done.

> Why don't you type in a new source account and then select a destination? Or just type the destination? The source field and destination fields are free format for a reason.

Because the source field isn't free format, I can only select one of my existing active accounts. And when I fill an amount (which must be positive), Firefly considers it a withdrawal instead of a deposit, which means I can't make a deposit.

**Comment by ClementNerma** [comment]
Ok so after trying a new time, it seems to work now. What was confusing me was that:

1. The source form only indicates my existing _active_ accounts, which I don't understand as a deposit cannot be made _from_ one of my accounts, else that would either be a transfer or a withdrawal ;
2. The destination account shows up when I starts typing its name but by default it only lists my _expense_ accounts, which shouldn't cause it doesn't make sense to make a deposit to an _expense_ account ;
3. For a reason I don't know (maybe a bug in my browser) the last time I tried I couldn't write the name of a source account which wasn't in the list as the input field was always resetting itself.

**Comment by JC5** [comment]
1) The source field will automatically suggest your asset accounts + revenue accounts. Unless you type in something entirely new, which is totally possible, because it's a free form field. The source field is context sensitive however, see below.

<img width="327" alt="Screenshot 2021-01-12 at 09 59 47" src="https://user-images.githubusercontent.com/5889984/104292274-8b216480-54b4-11eb-9fec-cdc913502ef7.png">

2) By default, the destination field will list asset accounts + expense accounts. This field is context-sensitive too. It's also free form.

3) Not sure what happened there, sorry.

Context sensitive means that IF you select a revenue account in the source field, the destination field is limited to asset accounts (expense accounts disappear).

**Comment by ClementNerma** [comment]
Okay I understand better now, but I what I don't quite grasp is why the asset accounts are shown in the source field and the expense accounts in the destination field, although it isn't logical to make a deposit _from_ an asset account and/or _to_ an expense account?

**Comment by JC5** [comment]
Expense accounts are where you spend money, so they can only be the destination. Revenue accounts give you money, so they can only be the source.

**Comment by ClementNerma** [comment]
In the case of a withdrawal, yes. But in the case of a deposit, the expense account should not be selectable the destination nor the revenue account as the source.

**Comment by JC5** [comment]
No, in the case of both. The form is the same for any type of transaction: the source + destination account determine the transaction type, not vice versa.

**Comment by ClementNerma** [comment]
> No, in the case of both. The form is the same for any type of transaction: the source + destination account determine the transaction type, not vice versa.

Ok but the doc says:

> Withdrawals have a free-format field for the "expense account" which you can fill in freely.
> Deposits have free-format field for the "revenue account". This works in the same way as withdrawals do.

Which implicitly supposes that withdrawals don't have a free "revenue account" field and deposits don't have a free "expense account" field.

Plus, I still don't think it makes sense to be able to select a revenue accout as the _source_ of a deposit ; a deposit cannot be made _from_ one of our bank accounts, only _to_ it, right?

**Comment by JC5** [comment]
I'll pick up the docs. I may have written them towards the old forms, in which just one account was "free form".

**Comment by death2cupbots** [comment]
> Plus, I still don't think it makes sense to be able to select a revenue accout as the _source_ of a deposit ; a deposit cannot be made _from_ one of our bank accounts, only _to_ it, right?

The form sets what it is based on the accounts you are using. So if you go to "New Deposit" and type in a revenue account, like your employer, and an asset account, like your checking account, the form will say "You're creating a deposit" and update with the right fields for a deposit. But if you instead type in 2 different asset accounts as the source and destination, the form will then say "You're creating a transfer" and display the right fields for a transfer.

**Comment by ClementNerma** [comment]
> > Plus, I still don't think it makes sense to be able to select a revenue accout as the _source_ of a deposit ; a deposit cannot be made _from_ one of our bank accounts, only _to_ it, right?
> 
> The form sets what it is based on the accounts you are using. So if you go to "New Deposit" and type in a revenue account, like your employer, and an asset account, like your checking account, the form will say "You're creating a deposit" and update with the right fields for a deposit. But if you instead type in 2 different asset accounts as the source and destination, the form will then say "You're creating a transfer" and display the right fields for a transfer.

So you're telling that the form isn't tailored specifically for the operation we asked to create, but for all types of operations, and adapt itselves depending on the accounts selected in the fields?

Still, that doesn't make sense to _not_ display the bank accounts in the target account autocomplete when nothing is input. They are only displayed in the _source_ account field.

**Comment by ClementNerma** [comment]
Ok so I just re-tested and it seems that, if I select a revenue account as the source _first_, then the autocomplete's results change for the _destination_ account, which is indeed the expected behaviour.

The problems seems to be caused by me not understanding I had to fill in the destination account first (I usually start by specifying the target naturally), so it may be interesting to just a put a line on this in the docs in case other people have the same problem.

So this issue is finally solved, thanks a lot for your help :D !

**Comment by JC5** [comment]
I'll do that for sure. I already made it a bit more clear, so thanks for the feedback! :+1:
