### ISSUE TITLE
OAuth tokens when using remote_user_guard

### ISSUE THREAD

**Issue by hakoerber** [firefly-iii/firefly-iii#4264]
Hello!

I have a potentially weird question about authentication.

I am using `AUTHENTICATION_GUARD=remote_user_guard` for the web login behind an authenticating reverse proxy that sets the relevant headers. This works well. But I want to have the API authenticated via OAuth bearer tokens.

So, I have `/api/` path proxied directly to firefly-iii, making sure to strip any guard header. Even though no access tokens can be configured via GUI, the existing tokens (before I switched to `remote_user_guard`) are still available and work.

Now when I want to manage access tokens, I have to temporarily disable `remote_user_guard` to make the changes.

1. Is this setup a good idea at all?
2. Would it make sense to add an option to make the token configuration visible, even when using `remote_user_guard`?

Thank you!

Relates to #3772

**Comment by JC5** [comment]
I can't find the ticket but I believe this is already on the list for the next release.

**Comment by hakoerber** [comment]
Ok, I'll wait for the new release then. Is it ok to leave the issue open until then?

**Comment by JC5** [comment]
Fixed in the latest beta, I'm closing this for consistency's sake.
