### ISSUE TITLE
Add helm chart

### ISSUE THREAD

**Issue by koeberlue** [firefly-iii/firefly-iii#4266]
**Description**

I would like to install Firefly III on Kubernetes using [`helm`](https://helm.sh)

**Solution**

Create a valid helm chart in the [kubernetes repository](https://github.com/firefly-iii/kubernetes). Also publish it to [artifacthub](https://artifacthub.io)

**What are alternatives?**

There already is a helm chart for Firefly III on Artifacthub: https://artifacthub.io/packages/helm/halkeye/firefly-iii maintained by @halkeye. It is _kind of_ up to date, but it does not come with a database. Maybe he will also be interested in an official helm chart?

You could also use the installation method described in the [documentation](https://docs.firefly-iii.org/firefly-iii/installation/k8n/), but it has some downsides, especially because you have to remind yourself to always pull the latest version.

**Additional context**

If there was an official helm chart available, people could install Firefly III easily on any of the cloud providers (aws, gke etc., all having a free tier) or on a self hosted kubernetes cluster.

**Comment by JC5** [comment]
Sounds cool! I wouldn't know where to begin though and I could use some pointers. But yes, this is a great idea :+1:

**Comment by koeberlue** [comment]
There is a pretty in-depth tutorial on helm.sh: https://helm.sh/docs/topics/charts/

You would probably want to start by calling [`helm create firefly-iii`](https://helm.sh/docs/helm/helm_create/#helm) which will create the basic directory and file structure which you could then start to customize.

For local testing you can use [minkube](https://minikube.sigs.k8s.io/docs/start/), to start a local kubernetes cluster for developing.

I might be able to come up with a pull request, but this might take me some weeks or so, because I currently don't have much "github time"

**Comment by halkeye** [comment]
None of my charts embed a database. I personally use a central one to make backups easier.

As for contributing. Your more than welcome to take my chart, its a little out of date of best practices (https://github.com/halkeye/helm-chart-starter has my updated template), but does work. I don't use firefly anymore, decided I wasn't interested in tracking everything so don't run things anymore.

**Comment by Pyrrha** [comment]
Hello,

I'll check during my free time how to create a helm chart to see how I can help with that.

Also interested in this stuff, I'll help you informed @JC5 & @koeberlue.

Regards.

**Comment by JC5** [comment]
https://github.com/firefly-iii/kubernetes/tree/main/helm
