### ISSUE TITLE
Add "Groups" style visual separation for budgets

### ISSUE THREAD

**Issue by ImmortalScientist** [firefly-iii/firefly-iii#4267]
**Description**
It would be great if Budgets could be organised into visual groups, in the same or very similar way to how Bills can be grouped for organisation! 

**Solution**
Better usability for budgets. At the moment, it's a monolithic list - If the user has budgets that they would like to group together and collapse for visual clarity, there's no way to do that. 

I'm not suggesting any changes to the functionality of budgets - Coming from YNAB they're different and I accept (and am getting used to that, may even come to like them eventually :P) - but YNAB did allow for budget items to be organised with visible sub-totals. I really like how Bills are organised under groups, and if implementation was down to me, I'd try and lift that directly into Budgets.

**Bonus points**
I was going to make a graphic - but I realised I was just making my "Budgets" page look like my organised "Bills" page instead but with the same spacing as it is in Budgets. 

Anyway - Have been adjusting to (and honestly liking it a lot) Firefly III for less than a month and I'm pretty sure that I'll stick with it for a good time to come! Thanks for making such a great bit of software.

**Comment by JC5** [comment]
I was planning this already, so this is a great idea! I like this groups thing and I'll extend it to more pages for sure. It'll be a part of the new layout so don't hold your breath. But know it's in the works. 👍🏻

**Comment by ImmortalScientist** [comment]
Thanks!

**Comment by Guernik** [comment]
This would be really something.
Congratulations on the awesome piece of software btw
