### ISSUE TITLE
Excluding certain revenue accounts from reporting (another way to deal with refunds)

### ISSUE THREAD

**Issue by zarko-a** [firefly-iii/firefly-iii#4268]
**Description**
 
 I know a topic of refunds has been discussed previously and that there are no plans for a full support of them. However, I was wondering if you'd be interested in implementing sort of a in-between solution. 

I don't disagree with your stance that refund is a deposit, however, I find it very counter productive to consider it revenue/income in the context of "income vs expense" reports.

The solution that I was thinking about shouldn't change the core of Firefly III workflow. It would just add a way to filter out "refund" transactions in reporting.

**Solution**

The idea consists of the following:

1. Introduce a "Refund" property for deposit transactions (e.g. checkbox in UI). On the backend, this could be simple true/false column.
2. In the reporting section have an "Extra option" to substract sum of all "Refund" transactions from sum of all expenses in a given time period.
3. In the reporting section have an "Extra option" to exclude certain revenue accounts from sum of all income, or use the same property mentioned in # 2 to reduce the income by the same amount.

Bonus: Support for "refund" property to be set by rules. I would assume that for most people working on a fixed salary, any amount lower than their regular monthly salary is a refund.

This approach would provide automatic canceling out of expense/refund in reporting, instead of manually going in and removing or editing the original transaction. This effectively "filters out" partial refunds too, providing a clearer picture of one's expenses and income. 

For example:
- Add salary revenue of $2000
- Add an expense of $1000
- Add revenue marked as "Refund" of $500

Currently, "income vs expense" report would show expenses of $1000 and income of $2500 which is not technically correct.
With the proposed approach, excluding transactions marked as refund from income reporting and substracting the amount from expenses, we get more realistic representation.

**What are alternatives?**
Manually editing or removing the original expense. This is not only extra effort each time you have a refund, but also creates a discrepancy between CSV bank statements and Firefly, which in turn renders "Do not import already existing transactions." feature useless.

**Additional context**
With Covid and a lot of things being cancelled (airfares, concerts, etc) we are probably all seeing a larger amounts of refunds which skew income reporting. 

**Bonus points**
Thank for making Firefly! It's a great piece of software.

**Comment by JC5** [comment]
Thanks! I already have something in mind to deal with refunds, and I hope to make it part of the new release.
