### ISSUE TITLE
Using APP_KEY_FILE

### ISSUE THREAD

**Issue by doppioandante** [firefly-iii/firefly-iii#4272]
Hello, I'm using firefly v.5.4.6 with docker.
I wanted to try out the "APP_KEY_FILE" feature which is advertised in the default env file; setting this variable instead of APP_KEY doesn't seem to work, and I can't find any reference of this env variable being used in the code. Maybe this is old info or it was never implemented?

**Comment by niklas2810** [comment]
The string is only present in the env examples - you are right, seems do be a redundancy :) 

![image](https://user-images.githubusercontent.com/30748216/104763136-bf6f7c00-5765-11eb-8c69-6317898cf5cf.jpeg)

**Comment by JC5** [comment]
It's not a redundancy, it's used explicitely in the Docker image, [right here](https://github.com/firefly-iii/docker/blob/main/entrypoint.sh#L8). You can set the variable and point it to a file. The Docker image will set APP_KEY to whatever the content of APP_KEY_FILE is.

**Comment by doppioandante** [comment]
Thank you, I understand now that it didn't work because the file must be somehow accessible from inside docker of course...
I opted for the simpler `-e APT_KET=$(cat filename)`
