### ISSUE TITLE
Allocate funds in account for bills

### ISSUE THREAD

**Issue by spoulson** [firefly-iii/firefly-iii#4273]
I am running Firefly III version 5.4.6.

**Description**

I get paid every 2 weeks, but I pay bills bimonthly.  So, I would just transfer my paycheck to savings on pay day to prevent accidental spending.  Then, on bill day I transfer it back.  Following this same organization pattern, I've created umpteen additional savings accounts to categorize my funds for several bills that I have to save up for.

I recently switched to a new bank and the multiple savings accounts are frowned upon.  So, I need something like Firefly to organize within a single checking account.  So, I created budgets and bills in Firefly.  I also categorized the initial deposit split into a bunch of categories that I used to have multiple savings accounts for.  e.g. Car payment, HOA dues, etc.

What I expected to be able to do is transfer funds between categories.  For example, I have some funds in the "Paycheck escrow" category and I need to use that to pay several bills.  When I'm done paying, I will expect to have some leftover in the Paycheck escrow category.  I could choose to reallocate that leftover portion to a savings category or whatever.  But, I don't see a way to recategorize funds.  Once the funds are categorized, it seems you can't deduct from it.  I'm getting the feeling that categories aren't the appropriate tool.

I've read the docs site and it doesn't cover this concept.  Is there a best practice recommendation?

**Extra info**
 

UPDATE: To clarify, I want the ability to track accumulation of allocated funds by category.  For example, my car payment is just a bit much to pay from a single paycheck, so I put away half on the 15th, then pay the full payment on the 1st.

Scenario:
* Paycheck deposits on 12/4/2020, I categorize as "Paycheck escrow".
* On 12/15/2020, I do my mid-month finances.  I reallocate $300 from "Paycheck escrow" to "Car payment", a half of the monthly payment.
* On 1/1/2021, I do my monthly finances.  I reallocate another $300 from "Paycheck escrow" to "Car payment".  I now have a full car payment allocated.
* I then pay the $600 car payment from the "Car payment" category.
* "Car payment" category now has $0 allocated.

Then, at any time I can use reporting or some other view that shows current totals by category so I can see at a glance if I have enough saved for upcoming bills.

If category isn't the right tool, what should I be using?

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
You could use piggy banks to do this.

**Comment by spoulson** [comment]
@JC5, I don't know how I missed this feature!  Ok, so I setup piggy banks for each "category".  I like the piggy bank reporting on the dashboard, too.

However, there doesn't seem to be any safeguard from overspending.  My assumption is money allocated in the piggy bank is unspendable for withdrawls.  The account summary still shows full balance amount with no indication that a large portion was allocated to piggy banks.  Also, I don't see a way to track piggy bank transactions.

I read over the docs on this and it doesn't say it does any of these things.  This may still not be the tool I had in mind.  Am I missing something?

**Comment by JC5** [comment]
No problem. I have to take it upon myself to clarify the docs!

But no, this doesn't exist. Personally I use a separate savings account for this stuff. But contrary to YNAB for example, this isn't forced in any way. I try to avoid magic like that.

**Comment by spoulson** [comment]
@JC5, could I place a feature request for "virtual accounts" that operate like piggy banks but require transferring in or out to use the funds?

**Comment by spoulson** [comment]
Or, I guess I could just create additional accounts in Firefly and I just know that they are linked to the same real bank account.
