### ISSUE TITLE
Go to the budget's page by clicking on it on the chart

### ISSUE THREAD

**Issue by ClementNerma** [firefly-iii/firefly-iii#4287]
A feature I used to use in other software and I think would be very convenient in Firefly would be to filter the transactions per budget when clicking on it from the chart.

For instance, if I click on this:

![image](https://user-images.githubusercontent.com/9782521/104944031-e670bc80-59b6-11eb-9a16-0eee00983aba.png)

The transactions below would be filtered to only show the ones related to that budget. That would also apply to the chart for categories and destination accounts, too.

I don't know how much this is doable given the fact that the application is pretty static on its frontend part. If it'd be easier to implement, another solution could to redirect to the budget's page instead (`/budgets/show/xxx/xxx`):

![image](https://user-images.githubusercontent.com/9782521/104944078-f4bed880-59b6-11eb-90c7-a77f3fd17aa9.png)

What do you think of this?

**Comment by JC5** [comment]
#3486

**Comment by ClementNerma** [comment]
Oh I didn't see this issue while I was searching. Thanks 👍
