### ISSUE TITLE
CSV Importer: Help understanding Dates

### ISSUE THREAD

**Issue by anoma** [firefly-iii/firefly-iii#4289]
The project documentation is excellent and honestly a joy to read but I am struggling to get my head around the differences between all the date fields.

For example:

https://docs.firefly-iii.org/csv/usage/roles/

Lists the primary date field as:

- Date - This sets the main date of the transaction.

but also some more advanced date options of:

https://docs.firefly-iii.org/csv/usage/roles/#meta-date-fields

-   Interest calculation date
-   Transaction booking date
-   Transaction process date
-   Transaction due date
-   Transaction payment date
-   Transaction invoice date

Is there further documentation on this and if not could we work together in this ticket to flesh out some brief introduction wording and examples for each of these date fields with a view to updating the docs or adding a FAQ item?

**Comment by JC5** [comment]
Glad to hear the documentation works well for you! I see the description isn't that extensive. Shall I update some things in this file?

https://github.com/firefly-iii/docs/blob/main/docs/docs/csv/usage/roles.md

It won't be updated online immediately so we have the time to fine tune text if you necessary.

**Comment by anoma** [comment]
If these changes are easy that would be great.

Likely a simple one liner for each would be enough. I have an idea what most of them mean but googling to make sure enters you in the wonderful world of global finance discussions where it seems that the mantra is "why use one word when 100 will do"

**Comment by JC5** [comment]
Doesn't have to be more complicated than that! I updated the text a bit, let me know.

**Comment by anoma** [comment]
This really does help. I am in the exact position that `Some users import these dates to make sure the data isn't lost`.

Can I just do a quick sanity check.

In my csv I have a date field which is the date the actual transaction occurred in my account/statement. I apply this to the main Firefly-iii date field.

I however have another sporadic date which is shown as part of the description field which appears to be the date the actual purchases occurred e.g the earlier date when I was in a shop and purchased the goods.

I have a process to extract this date to a new field ready for Firefly-ii import but I am unsure what date field would be the best fit. Is there an obvious choice and if so would the docs benefit from showing this as an example (assume this must be a quite common scenario)

**Comment by JC5** [comment]
Thanks, that helps. How's the text now? I updated the text under "Date" and under "Meta date fields".

**Comment by anoma** [comment]
Thanks again for this and I apologize that this ticket is becoming quite specific to my setup.

Whilst the new words don't answer my questions directly e.g. what is a booking date or a process date etc I does give me enough information to decide what I need to do, so a big thank you for these changes.

A few comments for consideration:

- It is probably worth adding some words on date consistency as now that I look, whilst I do have multiple dates for this banks csv format, only one of them is consistent essentially negating the choice of which to use

- It may also be worth mentioning reconciliation. I can imagine a scenario where if you are reconciling against a physical statement or an app that hides descriptions and you  also follow the advice of using `the date closest to the actual transaction` it may make the daily values quite a bit different.

It also now occurs to me that a lot of my questions are related to what would be best described as "import anxiety" i.e. the fear that once I import I loose the ability to go back and add omissions later.

There are two areas here:

- fields I choose not to import as Firefly-iii does not currently have a natural bedfellow
- free form fields that sometimes contain useful info but not always e.g. a description field that sometime shows the joint account card number used, vendor store city, vendor post code, store ID, transaction date etc

If there was an option to save skipped data/fields to a rolled-up "leftovers" field it opens the door to coming back to this later. How we actually come back to it could be decided in the future but I am sure you would have some clever ideas.

Dealing with extracting data from an already imported Description text field is trickier e.g. my bank has a `card transaction date store city` format used sometimes and a `store id post code` alternate format. This makes me think maybe we dont save skipped data/fields to a rolled-up "leftovers" but rather the entire raw record. 

This opens the door to quite a few future options for a relatively low storage and complexity cost.

**Comment by JC5** [comment]
You can always store stuff in the notes field. I understand what you mean though and I can address it in the documentation as well.

**Comment by anoma** [comment]
Thanks again for your time. I have enough info to solve the problems that inspired this ticket now but I will leave it open for a short while just in case you would like any other feedback on documents from the perspective of a new committed user.

Otherwise feel free to close immediately.

Please consider "import anxiety" at any future opportune design moments. I am sure I am not alone in this "condition" after the quite frankly ridiculous effort it took me to claw the raw data from my financial institutions it feels weird not to give every bit of a permanent home (even if it isnt actually all needed :).
