### ISSUE TITLE
Budgets overview shows wrong "Left (per day)"

### ISSUE THREAD

**Issue by brunovh** [firefly-iii/firefly-iii#4290]
**Bug description**
I am running Firefly III version  5.4.4, and my problem is:
Budgets overview shows wrong "Left (per day)"

**Steps to reproduce**
Create new budget with Auto-budget "Set a fixed amount every period", with any auto-budget amount and set period to "Yearly", then set budget of any transaction to that budget. Left per day will always show same as Spent per day.

**Extra info**
Debug information generated at 2021-01-19 16:44:08 Europe/London for Firefly III version **5.4.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.4 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | ff04a877-6a20-475f-a397-e62629640ca2 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-01-31 23:59:59 |
| Session first | 2019-01-21 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 |

- I have added a screenshot. - YES
- I was able to replicate it on the demo site https://demo.firefly-iii.org/  - YES
![image](https://user-images.githubusercontent.com/35847274/105065631-f9969180-5a75-11eb-8cb6-5a4298511b26.png)

**Comment by JC5** [comment]
Yes, it will. When the period of the budget and the view period don't mach, the left per day amount won't be updated.

**Comment by brunovh** [comment]
It makes sense that "Left **per day**" does not update. My concern is a different one. Let's take the example of the screenshot:

If I budget £1000 and spend £580, I would expect the "Left (per day)" column to show the difference, i.e. £420 (without the per day amount), just to have a quick overview of how much is left in the budget.

Or if you say you don't want to show the remaining amount because the periods do not match, maybe "Left (per day)" column should just show empty fields instead of making it look like I overspent the exact same amount that I actually had budgeted.

**Comment by JC5** [comment]
Thanks, I see what you mean. I'll pick it up for the new layout.
