### ISSUE TITLE
Some duplicate transactions after same file re-import

### ISSUE THREAD

**Issue by AndreiGavriliu** [firefly-iii/firefly-iii#4293]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

I have a cronjob that runs 3 times per day (`10 6,12,18 * * *`). It connects to the bank, downloads the transactions of "yesterday" and "today", converts them into csv's and imports them using the firefly-iii csv-importer `v2.3.3`. Sometimes, some transactions are re-imported even if they already exist. The idea is to always try to import yesterday's transactions (in case the bank has an issue or if there are any connectivity problems. If everything runs smoothly, the duplicate-detector should be able to manage this, however, *sometimes* it fails, and just for 1-2 transactions, not all of those in the import files

I checked the report emails and the import files

Today, there were only 2 transactions to import:
```
$ diff import-2021-01-21-06-00.csv import-2021-01-21-12-00.csv
$
```

```
Result of your import on 2021-01-21 @ 06:00:07
Errors
Warnings
Messages
Line #0: Created withdrawal #4784 "[REDACTED.1]" (EUR 26.49)
Line #1: Created withdrawal #4785 "[REDACTED.2]" (EUR 30.12)

Result of your import on 2021-01-21 @ 12:00:07
Errors
Line #1: transactions.0.description: Duplicate of transaction #4785. (original value: "[REDACTED.2]")
Warnings
Messages
Line #0: Created withdrawal #4786 "[REDACTED.1]" (EUR 26.49)
```

**Steps to reproduce**
not always reproducible

**Extra info**
No docker install, plain Apache2 on Ubuntu Server. The transactions are not managed by any rules/bills etc

**Bonus points**
Debug information generated at 2021-01-21 12:44:16 Europe/Berlin for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.14 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 7c3ba7a7-37c2-41d9-a43c-eaf55cf4e139 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | cgi-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-01-31 23:59:59 |
| Session first | 2015-08-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0 |

**Comment by JC5** [comment]
What's the diff between the two transactions in Firefly III? 

- https://demo.firefly-iii.org/transactions/debug/123
- https://demo.firefly-iii.org/transactions/debug/456

I'm curious what's going on exactly.

**Comment by AndreiGavriliu** [comment]
Nice feature!

```
$ diff 4784.json 4786.json
2,4c2,4
<     "id": 4784,
<     "created_at": "2021-01-21T05:00:06.000000Z",
<     "updated_at": "2021-01-21T05:00:06.000000Z",
---
>     "id": 4786,
>     "created_at": "2021-01-21T11:00:06.000000Z",
>     "updated_at": "2021-01-21T11:00:06.000000Z",
10,12c10,12
<             "id": 6465,
<             "created_at": "2021-01-21T05:00:05.000000Z",
<             "updated_at": "2021-01-21T05:00:06.000000Z",
---
>             "id": 6467,
>             "created_at": "2021-01-21T11:00:06.000000Z",
>             "updated_at": "2021-01-21T11:00:06.000000Z",
16c16
<             "transaction_group_id": 4784,
---
>             "transaction_group_id": 4786,
29,31c29,31
<                     "id": 13021,
<                     "created_at": "2021-01-21T05:00:06.000000Z",
<                     "updated_at": "2021-01-21T05:00:06.000000Z",
---
>                     "id": 13025,
>                     "created_at": "2021-01-21T11:00:06.000000Z",
>                     "updated_at": "2021-01-21T11:00:06.000000Z",
35c35
<                     "transaction_journal_id": 6465,
---
>                     "transaction_journal_id": 6467,
59,61c59,61
<                     "id": 13022,
<                     "created_at": "2021-01-21T05:00:06.000000Z",
<                     "updated_at": "2021-01-21T05:00:06.000000Z",
---
>                     "id": 13026,
>                     "created_at": "2021-01-21T11:00:06.000000Z",
>                     "updated_at": "2021-01-21T11:00:06.000000Z",
65c65
<                     "transaction_journal_id": 6465,
---
>                     "transaction_journal_id": 6467,
91,94c91,94
<                     "id": 15001,
<                     "created_at": "2021-01-21T05:00:06.000000Z",
<                     "updated_at": "2021-01-21T05:00:06.000000Z",
<                     "transaction_journal_id": 6465,
---
>                     "id": 15005,
>                     "created_at": "2021-01-21T11:00:06.000000Z",
>                     "updated_at": "2021-01-21T11:00:06.000000Z",
>                     "transaction_journal_id": 6467,
96,97c96,97
<                     "data": "adc9afc0dd3c3232d64c19f327288d94a60a5d2e84da11d03f52f06d6de09b01",
<                     "hash": "df34f299a9f782aba75da08087ed428e821ac15d1808a9066120f0e11db0632a",
---
>                     "data": "85d8870b68d508f24a53a08aa6a1b7fd11f138b79d6239595e2c0f4341dc15b8",
>                     "hash": "f712dbf046321d09c5072d0f9710ee9b892372540ecedcfccc7bc06e4090d6dc",
101,104c101,104
<                     "id": 15002,
<                     "created_at": "2021-01-21T05:00:06.000000Z",
<                     "updated_at": "2021-01-21T05:00:06.000000Z",
<                     "transaction_journal_id": 6465,
---
>                     "id": 15006,
>                     "created_at": "2021-01-21T11:00:06.000000Z",
>                     "updated_at": "2021-01-21T11:00:06.000000Z",
>                     "transaction_journal_id": 6467,
```

if it helps, I could send you the files. It's just a KFC order :) - I was hungry

**Comment by JC5** [comment]
Haha nice!

All I can think of right now is that the destination account was new in the first transaction, and existed for the second transaction. Was it your first visit to this particular KFC?

I have to do some debugging later because I can't remember if the CSV importer will automatically switch from `destination_name` to `destination_id` if the account is found the second time around.

**Comment by AndreiGavriliu** [comment]
yes, it's the first time. But now that you mention it, I believe every time it happened, it was the first visit... cannot be sure, and I deleted the old ones

**Comment by JC5** [comment]
Alright, I'll keep you in the loop.

**Comment by JC5** [comment]
I added some text [to the docs](https://docs.firefly-iii.org/csv/errors/duplicate_transactions/) for the time being.

**Comment by JC5** [comment]
My original idea doesn't seem to be the cause. I'm curious if you can keep track of any logs you have when this happens again. The CSV importer should [report](https://github.com/firefly-iii/csv-importer/commit/14e9ebb16d6ad49b76c14d6a2882dd53ec18de28#diff-cf1baee440c87559534afb281518ce06cfe11cd1c8ad448364fc6b947b6b54a0R325) that it's ignoring accounts it found.

**Comment by AndreiGavriliu** [comment]
I do have another example. I also saved the entire importer log file from that day. But, as it contains private information, I'd prefer not to post it on GitHub. Can I send you an email or something?

**Comment by JC5** [comment]
Sure thing. Drop it at james@firefly-iii.org. I’ll trash it when I’m done.

**Comment by JC5** [comment]
Thanks for the files. I see the issue. A new expense account is created based on the IBAN you submit. This is found next time around so the original issue is true again (except for IBAN except for name):

1. Can't find, so use {destination_iban: AB123}
2. Found! Use {destination_id: 123}

I'll pick it up!

**Comment by JC5** [comment]
In your logs, expect the following when this happens again:

```
local.DEBUG: [a] Found expense account #54 based on IBAN "NL26ABNA6038321969"
local.DEBUG: [a] CSV importer will pretend not to have found anything. Firefly III must handle the IBAN.
```

The first sentence can already be found, also in the example you sent me. But the second line is new. I believe this will fix the issue in future imports. 👍🏻

**Comment by JC5** [comment]
New release will be out over the weekend.

**Comment by JC5** [comment]
2.4.0 is out.
