### ISSUE TITLE
Unmark transactions as reconciled

### ISSUE THREAD

**Issue by duviful** [firefly-iii/firefly-iii#4296]
I am running Firefly III version 5.4.6.

**Description**
I think I have duplicated some old transactions and now I have discrepancies in firefly (balance is less than real account).
My habit is to manually insert transaction and use quarterly papers from the bank to reconcile. the last 3 quarters were fine, so this mistake date back to past years. 
I tried to use the search for them, but I can't get any clue.

My best idea was to unmark transaction, quarter by quarter, and reconcile again. this will be easy to identify since firefly provides a good reconcile tool.

I didn't find a way to **unmark transactions as reconciled**, not in bulk edit, nor in reconciling tool itself.

is this action available already or planned?

there are some other ways I'm missing to identify the wrong transactions?

Thanks

**Comment by JC5** [comment]
There isn't one, at the moment. But you could use the audit report to see if you can find the discrepancy?

**Comment by duviful** [comment]
Hello. Using the Audit report, I was able to track down discrepancies. Thank you for pointing me in the right direction.
Firefly is truly amazing. Many thanks JC!
