### ISSUE TITLE
Firefly III CSV Import Tool skips second tag role column import

### ISSUE THREAD

**Issue by anoma** [firefly-iii/firefly-iii#4298]
**Bug description**
I am running Firefly III version Version 5.4.6 Firefly III CSV Import Tool v2.3.4

Firefly III © James Cole, AGPL-3.0-or-later. , and my problem is:

The Firefly III CSV Import Tool allows more than one `Column` to be set to a `Role` type `Tags (comma separated)` and will proceed without error however only the first column will be imported.

**Steps to reproduce**

Import any csv and set any two `Column` to `Role` type `Tags (comma separated)` and import. Only the first `Column` will be imported.

As sanity check: repeat using only the second column as single tag import and it will complete (proving the content is OK)

**Extra info**

For context my csv has two Type fields one of which is the format of sale (e.g. charge, POS etc) and the other is a sub category e.g. Train sub category of main category Travel.

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
It does yes, I'll pick it up for a future release.

**Comment by JC5** [comment]
Fix is live in the `develop` tag. Release will probably be next weekend.

- https://hub.docker.com/layers/fireflyiii/csv-importer/develop/images/sha256-56d51bca841b63036a64910573aa8cb0fb3a79a49a2d66a2f64090037882da5d?context=explore
- https://github.com/firefly-iii/csv-importer/tree/develop

**Comment by JC5** [comment]
2.4.0 is out.

**Comment by anoma** [comment]
Thanks for the very prompt fix.

I can confirm it worked here flawlessly using `Firefly III version Version 5.4.6` and  `Firefly III CSV Import Tool v2.4.0`
