### ISSUE TITLE
Paypal importer

### ISSUE THREAD

**Issue by Pyrrha** [firefly-iii/firefly-iii#4306]
Hello,

**Description**

Adding PayPal integration through their API.

**Solution**

A handler to another type of account, that can be feed by another importer.

**Additional context**

I saw a PayPal developer portail 🤷‍♂️

**Bonus points**

I'll be happy 😃

**Comment by JC5** [comment]
Feel free to build one 😁. With the API in place, I'm not focussing on new importers right now.

**Comment by Pyrrha** [comment]
Nice I didn't see the API!

I'll keep you informed here for deployment progress. I'll need it for personnal use and an association I'm working it is also interested by this type of import.
