### ISSUE TITLE
"I'm a teapot" HTTP 418 when trying to add attachment to transaction

### ISSUE THREAD

**Issue by ChrisCarini** [firefly-iii/firefly-iii#4331]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is that I am getting "I'm a teapot" HTTP 418 when trying to add attachment to transaction.

**Steps to reproduce**
I edit a transaction, upload a pdf file, click update, and get the below banner, displayed for a *very* brief period of time, and then the page redirects saying the transaction was updated successfully (the pdf is not attached to the transaction, but any other updates are).

![Screen Shot 2021-01-31 at 15 24 47](https://user-images.githubusercontent.com/6374067/106401355-875c7000-63d8-11eb-8790-fcc9c1a00fcd.png)

**Extra info**
```
OS: OSX version 10.15.7
Chrome Version: Version 88.0.4324.96 (Official Build) (x86_64)
```
**`/debug` Output:**
Debug information generated at 2021-01-31 15:22:31 America/Los_Angeles for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.14 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | <REDACTED - Let me know if this is required; I'd rather not post publicly.> |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | production |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | cgi-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-01-31 23:59:59 |
| Session first | 2018-12-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files (***I think the log files may have been truncated too much, as nothing talks about an attachment***) 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/  (***Demo site does not appear to allow attachments.***)

**Comment by JC5** [comment]
There's no 418 code sent out by Firefly III anywhere near that piece of code. There's one line in a piece of code controlling recurring transactions, but it's an "unreachable" line so it can't be sent out anyway.

I'm curious to see more logs on this.

**Comment by JC5** [comment]
Also, please upgrade to the latest version.
