### ISSUE TITLE
CSV importer: cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by TruffelNL** [firefly-iii/firefly-iii#4333]
I am running Firefly III version 5.4.6.

**Description**
I installed Firefly and the importer in separate Docker containers on their own network. I can get a token from Firefly but when I get to the next step (after I'm authenticated), I get the error `cURL error 6: Could not resolve host: firefly.my.domain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://firefly.my.domain/api/v1/about`. The address shown is the external address for Firefly (resolved by a LAN DNS server), so it's no wonder it cannot connect/resolve. But I thought the importer would use the `FIREFLY_III_URL` set in the .env file. It seems to be using the `VANITY_URL` which is not the one it needs to use. How can I get it to use the correct URL or what am I doing wrong?

**Extra info**
.env file:

```
FIREFLY_III_CLIENT_ID=
FIREFLY_III_URL=http://firefly_iii:8080
VANITY_URL=https://firefly.my.domain
TRUSTED_PROXIES=**
```

**Bonus points**
- I have read the FAQ at https://bit.ly/FF3-FAQ
- I'll donate money when I'm smart enough to get it working

**Comment by JC5** [comment]
It should indeed. Which version of the CSV importer?

**Comment by TruffelNL** [comment]
Yes, it makes more sense to post that version instead of the Firefly one, sorry. The importer is v2.4.0.

**Comment by JC5** [comment]
Thanks. Found the issue, stay tuned.

**Comment by JC5** [comment]
Could you run the `develop` tag of the CSV importer instead of `latest`? I pushed and built a possible fix. I'm curious to see if it works. Click "Reauthenticate" a few times to clear your cookies, but your config can stay the same.

**Comment by TruffelNL** [comment]
Yes my kind sir, that did the trick. It's now asking for a csv file. Thank you for the great support!

**Comment by JC5** [comment]
2.5.0 is out. :+1:
