### ISSUE TITLE
Proportional multi-currency home view

### ISSUE THREAD

**Issue by ruihildt** [firefly-iii/firefly-iii#4335]
**Description**
I would like to be able to see an approximate worth of my accounts value.
Right now I have an account in SEK and in EUR with my default currency being in SEK.

If I look at my homepage, I have my account in EUR that is mapped on the SEK scale, but according ot the number, not the value.

As 1 EUR is worth 10 SEK, you can imagine the superposed graph are not indicative of anything. (See additional context below)

**Solution**
I would suggest to have the possibility to have a rough conversion of extra currencies of the account to the default currency value.
It doesn't need to be perfect and updated to the daily rates (though it would be nice).

I can imagine the conversion ratio could be inputted in all currencies based on the default one.

**What are alternatives?**
We could also have two separate graphs on the homepage, one per currency.
Another one would be to keep things as they are.

**Additional context**
![image](https://user-images.githubusercontent.com/13787166/106521879-31262480-64df-11eb-89c5-38735bc9d241.png)
The blue line at the bottom would actually reach the first grey line if it was converted to the same currency as the green line!

**Bonus points**
Automatically updating currencies based on current market rates.

Thanks a lot for your time and effort. :)

**Comment by JC5** [comment]
Sorry, this won't change.

https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/#automated-currency-conversion-so-everything-is-in-euros-or-dollars

**Comment by ruihildt** [comment]
@JC5 What about a way to alternate between multiple views per currency or showing two different graphs?

**Comment by Horatio2084** [comment]
What about a second Y-Axis for the other currencies? This could make the Charts readable for € and BTC in the same Chart.

**Comment by JC5** [comment]
I have some things like this on my list yes :+1:
