### ISSUE TITLE
Discrepancy in "Next due" dates

### ISSUE THREAD

**Issue by therealklanni** [firefly-iii/firefly-iii#4338]
**Bug description**
I am running Firefly III version **5.4.6**, and my problem is:

Discrepancy between `Click here for a calendar that shows you when the transaction would repeat.` preview of **Next due** dates and **Next due** dates displayed on `Recurring transactions` overview. See screenshots.

![img1](https://i.imgur.com/WYnytHz.png)
![img2](https://i.imgur.com/cv9Uby0.png)

**Steps to reproduce**

1. Create a new recurring transaction and 
2. select any **First date**, 
3. set **Type of repetition** to `Every week ...`, 
4. and set **Skip** to `1`
5. view calendar
6. save and return to **Recurring transactions** overview
7. see discrepancy

**Extra info**

- macOS 10.15.7 (19H114)
- Firefox Developer Edition (latest)

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.14 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 67221379-89bb-4396-a167-a52ee0e6b6e4 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-03-31 00:00:00 |
| Session first | 2021-01-15 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0 |

**Bonus points**

- [x] I searched and ~~nobody reported this bug before~~ I saw similar issues, but they were closed
- [x] ~~I have added a stack trace from my log files~~ Stack trace not necessary
- [x] I have added a screenshot.
- [x] ~~I was able to replicate it on the demo site https://demo.firefly-iii.org/~~ This [page doesn't work](https://demo.firefly-iii.org/recurring/create) on the demo

**Comment by therealklanni** [comment]
Also note that I had a recurring transaction set that never got created on the date it said it would execute, so I'm unsure which dates (calendar vs "next due" list) it's actually going by or if there was some other issue that prevented the creation.

**Comment by JC5** [comment]
It will go for the dates you see on the index (the calendar was bad), and it's a tricky bug I've fixed in the next release. Thanks for letting me know!
