### ISSUE TITLE
Separate LDAP attribute for user email

### ISSUE THREAD

**Issue by BWohlbrecht** [firefly-iii/firefly-iii#4370]
**Description**
Currently when using LDAP authentication there is no (documented) way to specify a separate attribute for the user's email address. I presume the ADLDAP_AUTH_FIELD is assumed to be the user's email address. This forces login using the email address as the principal, otherwise email notifications are broken.

**Solution**
Add a separate configuration option ADLDAP_EMAIL_FIELD specifying the LDAP attribute of the user's email address.

**What are alternatives?**
Allow administrators to edit a user's email address independently from LDAP. This split's the storage of user data between LDAP and the regular database and should be avoided.

**Comment by JC5** [comment]
Yes, I'll put it in the list! :+1:

**Comment by JC5** [comment]
The principal name you use to login, and the email address are separated. You can use "james" to login and it will save the email address locally.

**Comment by BWohlbrecht** [comment]
Thanks. If I understand you correctly, it won't be possible to fetch a user's email from LDAP?

**Comment by JC5** [comment]
That’s exactly what it will do.
