### ISSUE TITLE
Wrong box highlighted on transaction creation error

### ISSUE THREAD

**Issue by saintman23** [firefly-iii/firefly-iii#4372]
**Bug description**
I am running Firefly III version 5.4.6 stable (Demo site with 5.5.0b1 same error), and my problem is:

On creating income transaction with missing(wrong) Destination account FFIII gives error: "Invalid account information." and highlights Source account box instead of Destination account.

**Steps to reproduce**
Create income transaction with wrong/missing destination account

![изображение](https://user-images.githubusercontent.com/11691558/107221441-b43a0400-6a24-11eb-98ae-27138f87ef6b.png)

**Comment by JC5** [comment]
Thanks. Since this is a layout specific issue I’m not going to fix this in the current layout. I’ll pick it up for the new layout 👍
