### ISSUE TITLE
Why dashboard instance glare widget not working in mobile view?

### ISSUE THREAD

**Issue by faizalsb** [firefly-iii/firefly-iii#4376]
I am running Firefly III version 5.4.6

**Description**
Instant glare widget ("Balance", "bills to pay", "spent" and "net worth")
not appear if browser turn to mobile view.

**Extra info**
 

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
That's correct. They're hidden om small screens to save space.
