### ISSUE TITLE
Support HTTPS for importers

### ISSUE THREAD

**Issue by zifeo** [firefly-iii/firefly-iii#4388]
**Description**

Currently, the CSV importer cannot be used with HTTPS as static files (JS/CSS) are served through HTTP. (mixed content). Some redirections (oath workflow?) might also be affected.

**Solution**

Change `href="http://` by `href="//` and similar tricks.

**What are alternatives?**

None secured (stick with HTTP).

**Comment by JC5** [comment]
The CSV importer supports https. You have to configure your reverse proxy correctly.
