### ISSUE TITLE
Bug when adding budget via API

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4394]
**Bug description**
I am running Firefly III version 5.4.6 and demo site, and my problem is:

When adding a new budget via the API, the error occurs
```
{
  "message": "Internal Firefly III Exception: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `fireflyiii`.`auto_budgets`.`auto_budget_type` at row 1 (SQL: insert into `auto_budgets` (`budget_id`, `transaction_currency_id`, `auto_budget_type`, `amount`, `period`, `updated_at`, `created_at`) values (1, 1, , , , 2021-02-15 14:35:25, 2021-02-15 14:35:25))",
  "exception": "Illuminate\\Database\\QueryException"
}
```

The budget is added though

**Steps to reproduce**

curl -X POST "https://demo.firefly-iii.org/api/v1/budgets" -H "accept: application/json" -H "Authorization: Bearer xxxx" -H "Content-Type: application/json" -d "{\"name\":\"budget\"}"

**Comment by emansih** [comment]
The docs has some issues. (https://api-docs.firefly-iii.org/#/budgets/storeBudget)

```
"auto_budget_period": "EUR"
```
It should be time period not currency

```
  "auto_budget_type": "reset",
```
What are the valid parameters for `auto_budget_type` ?

**Comment by JC5** [comment]
The valid types are `reset`, `rollover` and `none`. I fixed the issue you mentioned, that's some grade-A sloppy programming on my part. Sorry!
