### ISSUE TITLE
After updating, knocks out an error during write-off operations

### ISSUE THREAD

**Issue by nloshka** [firefly-iii/firefly-iii#4402]
Debug information generated at 2021-02-16 14:08:28 Europe/Amsterdam for Firefly III version **5.5.0-beta.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.0-beta.1 |
| Firefly III API | 1.5.0 |
| PHP | 7.4.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 28629bf3-d0fb-404b-a873-af978b1c355d |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-02-01 00:00:00 |
| Session end | 2021-02-28 23:59:59 |
| Session first | 2018-12-08 00:00:00 |
| User ID | 1 |
| User language | ru_RU |
| User locale | ru_RU |
| Attempt at "ru_RU.utf8" | 'ru_RU.utf8' |
| Attempt at "ru_RU.UTF-8" | 'ru_RU.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 |
How do I resolve the error?
Mistake:Internal Firefly III Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'buh.webhook_messages' doesn't exist (SQL: select `webhook_messages`.* from `webhook_messages` where `webhook_messages`.`sent` = 0 and `webhook_messages`.`errored` = 0)

**Comment by JC5** [comment]
Make sure you run the migrations after updating.

**Comment by nloshka** [comment]
how to do migration? what commands do you need to execute? Thank.

**Comment by sephrat** [comment]
https://docs.firefly-iii.org/firefly-iii/advanced-installation/upgrade/

**Comment by nloshka** [comment]
# php artisan firefly-iii:upgrade-database
Now seeding the database...

In Connection.php line 678:
                                                                                                                                    
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'failed_jobs' already exists (SQL: create table `failed_jobs` (`i  
  d` bigint unsigned not null auto_increment primary key, `uuid` varchar(191) not null, `connection` text not null, `queue` text n  
  ot null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) d  
  efault character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)                                                        
                                                                                                                                    

In Connection.php line 471:
                                                                                               
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'failed_jobs' already exists

**Comment by nloshka** [comment]
# php artisan migrate --seed
Migrating: 2020_11_12_070604_changes_for_v550

In Connection.php line 678:
                                                                                                                                    
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'failed_jobs' already exists (SQL: create table `failed_jobs` (`i  
  d` bigint unsigned not null auto_increment primary key, `uuid` varchar(191) not null, `connection` text not null, `queue` text n  
  ot null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) d  
  efault character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)                                                        
                                                                                                                                    

In Connection.php line 471:
                                                                                               
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'failed_jobs' already exists
