### ISSUE TITLE
IDs returned as strings instead of integer as specified

### ISSUE THREAD

**Issue by S7evinK** [firefly-iii/firefly-iii#4411]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is: 
IDs for entities (tested with `/v1/accounts`, `/v1/bills`, `/v1/transactions`) are returned as string, while the Swagger documentation says it should be an integer. 
#2953 seems to have been the same.

Using `/v1/autocomplete` the entities come back as expected with the ID being an integer.

**Steps to reproduce**
- Create a go client using openapitools/openapi-generator-cli
- Request accounts/transactions/..

**Extra info**
| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.14 |
| Database | postgres |

**Comment by JC5** [comment]
I can't replicate this, but I'm on a MySQL database. I'll make sure that the response is always cast to an integer.

**Comment by S7evinK** [comment]
Seems that all endpoints return strings when using postgres:
```bash
for backend in "transactions" "attachments" "available_budgets" "budgets" "categories" "currencies" "link_types" "piggy_banks" "recurrences" "rules" "rule_groups" "tags" "users" "accounts" "bills"; do 
  echo "Testing /api/v1/${backend}"; 
  curl -s --header "Authorization: Bearer $TOKEN" "http://localhost:8080/api/v1/${backend}" | jq '.data[0].id'; 
done
```

```
Testing /api/v1/transactions
"1880"
Testing /api/v1/attachments
"14"
Testing /api/v1/available_budgets
"1"
Testing /api/v1/budgets
"4"
Testing /api/v1/categories
"24"
Testing /api/v1/currencies
"11"
Testing /api/v1/link_types
"3"
Testing /api/v1/piggy_banks
"2"
Testing /api/v1/recurrences
"5"
Testing /api/v1/rules
"17"
Testing /api/v1/rule_groups
"2"
Testing /api/v1/tags
"18"
Testing /api/v1/users
"3"
Testing /api/v1/accounts
"180"
Testing /api/v1/bills
"12"
```

**Comment by JC5** [comment]
There's a cast to int in literally all of these and you're the first to notice this. I don't understand it and I'll check it out.

https://github.com/firefly-iii/firefly-iii/blob/main/app/Transformers/BudgetTransformer.php#L92

**Comment by S7evinK** [comment]
I've just downloaded the [docker-compose.yml](https://raw.githubusercontent.com/firefly-iii/docker/main/docker-compose.yml) file incl. the example [.env](https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.env.example) and can reproduce it there, even with mysql.

```json
{
  "type": "currencies",
  "id": "11",
  "attributes": {
    "created_at": "2021-02-19T14:50:55+01:00",
    "updated_at": "2021-02-19T14:50:55+01:00",
    "default": false,
    "enabled": false,
    "name": "Australian dollar",
    "code": "AUD",
    "symbol": "A$",
    "decimal_places": 2
  },
  "links": {
    "self": "http://localhost:8080/api/v1/currencies/11",
    "0": {
      "rel": "self",
      "uri": "/currencies/11"
    }
  }
}
```

**Comment by JC5** [comment]
Mmmm. Maybe an upgraded library? I see it too. Thanks for the debugging!

**Comment by JC5** [comment]
It appears the docs are wrong.

https://github.com/thephpleague/fractal/issues/464

I will update them.

**Comment by S7evinK** [comment]
The client generator didn't complain about anything and, after some small fixes (related to the generator), my tests are working.

Thanks for the fast fix! Awesome work btw. :)
