### ISSUE TITLE
When running cronjob - Error On function transactionJournals

### ISSUE THREAD

**Issue by bartekd123** [firefly-iii/firefly-iii#4412]
**Bug description**
I am running Firefly III version 5.5.0 beta 1, and my problem is:

When I am running my daily cronjob it is failing today. It’s the day of a transfer to a piggy bank so that could be the cause. It ran yesterday without issue. I am using firefly in docker. 

**Steps to reproduce**
It could be the result of the following:
 - created a recurring transfer, and link it to a piggy bank

**Extra info**
`[2021-02-19 09:00:02] local.INFO: It has been 1 day since the recurring transactions cron-job has fired. It will fire now!  
[2021-02-19 09:00:02] local.INFO: Will now fire recurring cron job task for date "2021-02-19".  
[2021-02-19 09:00:04] local.INFO: Recurrence #14 is set to run on 2021-02-28, and today's date is 2021-02-19. Skipped.  
[2021-02-19 09:00:04] local.INFO: Recurrence #13 is set to run on 2021-02-28, and today's date is 2021-02-19. Skipped.  
[2021-02-19 09:00:05] local.INFO: Created new transaction group #8348  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.INFO: Ignore search operator "user_action"  
[2021-02-19 09:00:05] local.ERROR: Call to a member function transactionJournals() on null {"exception":"[object] (Error(code: 0): Call to a member function transactionJournals() on null at /var/www/html/app/Repositories/Journal/JournalRepository.php:101)
[stacktrace]
#0 /var/www/html/app/TransactionRules/Engine/SearchRuleEngine.php(524): FireflyIII\\Repositories\\Journal\\JournalRepository->findNull()
#1 /var/www/html/app/TransactionRules/Engine/SearchRuleEngine.php(353): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->setDateFromJournalTrigger()
#2 /var/www/html/app/TransactionRules/Engine/SearchRuleEngine.php(286): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->findStrictRule()
#3 /var/www/html/app/TransactionRules/Engine/SearchRuleEngine.php(180): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->fireStrictRule()
#4 /var/www/html/app/TransactionRules/Engine/SearchRuleEngine.php(491): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->fireRule()
#5 /var/www/html/app/TransactionRules/Engine/SearchRuleEngine.php(129): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->fireGroup()
#6 /var/www/html/app/Handlers/Events/StoredGroupEventHandler.php(79): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->fire()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(412): FireflyIII\\Handlers\\Events\\StoredGroupEventHandler->processRules()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(237): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(432): Illuminate\\Events\\Dispatcher->dispatch()
#10 /var/www/html/app/Jobs/CreateRecurringTransactions.php(298): event()
#11 /var/www/html/app/Jobs/CreateRecurringTransactions.php(321): FireflyIII\\Jobs\\CreateRecurringTransactions->handleOccurrence()
#12 /var/www/html/app/Jobs/CreateRecurringTransactions.php(360): FireflyIII\\Jobs\\CreateRecurringTransactions->handleOccurrences()
#13 /var/www/html/app/Jobs/CreateRecurringTransactions.php(114): FireflyIII\\Jobs\\CreateRecurringTransactions->handleRepetitions()
#14 /var/www/html/app/Support/Cronjobs/RecurringCronjob.php(87): FireflyIII\\Jobs\\CreateRecurringTransactions->handle()
#15 /var/www/html/app/Support/Cronjobs/RecurringCronjob.php(70): FireflyIII\\Support\\Cronjobs\\RecurringCronjob->fireRecurring()
#16 /var/www/html/app/Console/Commands/Tools/Cron.php(157): FireflyIII\\Support\\Cronjobs\\RecurringCronjob->fire()
#17 /var/www/html/app/Console/Commands/Tools/Cron.php(79): FireflyIII\\Console\\Commands\\Tools\\Cron->recurringCronJob()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Tools\\Cron->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#24 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#27 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#31 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}
"} 

In JournalRepository.php line 101:

 Call to a member function transactionJournals() on null  
`

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nice find, I'll dive into it!

**Comment by bartekd123** [comment]
Thanks James. Let me know if I can test anything, or provide any more info.

**Comment by bartekd123** [comment]
Thanks for the fix. I added the line "$repository->setUser($this->user);" like in your fix, and re-ran my cronjob and it worked for me.

**Comment by JC5** [comment]
Cool! Thanks for testing it!
