### ISSUE TITLE
Show full account path on hover

### ISSUE THREAD

**Issue by azzamsa** [firefly-iii/firefly-iii#4415]
**Description**

I would like firefly III to show full account path on hover. 

![image](https://user-images.githubusercontent.com/17734314/108620630-f2d9b080-745f-11eb-8225-a3f5d7b8248e.png)

Hovering these account will show us `asset/FOO` or `expenses/FOO` or `liability/FOO`.

I have multiple accounts in asset, liability, and expenses with the same name.

**Solution**

Firefly III should show such a tool-tip when hovering those account with mouse cursor.

**What are alternatives?**

Adding prefix to these accounts, such `foo-asset`, `foo-expenses`, and `foo-liability`

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
Not a bad idea! I'll put it on the list for the new release.

**Comment by azzamsa** [comment]
This is indeed an active issue.

**Comment by JC5** [comment]
It's ok, I wrote it down.

**Comment by azzamsa** [comment]
Sorry, but how do I track if this issue was resolved. I tried the latest demo version (5.5.10) and it is still not implemented. Should we reopen this issue?

![image](https://user-images.githubusercontent.com/17734314/117213225-8860cb80-ae25-11eb-858c-77abadaf9dcc.png)
