### ISSUE TITLE
Feature: Add option to export reports to CSV

### ISSUE THREAD

**Issue by klejejs** [firefly-iii/firefly-iii#4430]
**Description**

It would be nice to have a button to export currently open report to CSV file and download it.

**Solution**

There is an option to export and currently open report to a CSV file and download it.

**What are alternatives?**

I have tried to copy-paste the table into excel and it kind of works, but a simple export button would be wonderful.

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
Which report where you thinking about exactly?

**Comment by klejejs** [comment]
I was thinking about "Transaction history overview".

**Comment by JC5** [comment]
You can export what you need under /export, I'll see if I can add a separate export button in the new layout I'm currently building :+1:

**Comment by klejejs** [comment]
The only problem with `/export` is that it exports everything. Maybe my idea about report export was wrong, and it would simply be better to have an option in `/export` to, for example, export by time range or by account.

**Comment by JC5** [comment]
As it says, you can use the command line to do so. I'm not going to build a UI for that.
