### ISSUE TITLE
Bug when adding piggy bank with group

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4435]
**Bug description**
I am running Firefly III version 5.5.0-beta.1(demo) , and my problem is:

When adding a piggy bank with group parameter, an exception is thrown. 

```
{
  "message": "Internal Firefly III Exception: 400005: Could not store new piggy bank.",
  "exception": "FireflyIII\\Exceptions\\FireflyException"
}
```

On Firefly III v5.4.6,
The piggy bank is stored but `object_group_title` is always `null`

**Steps to reproduce**
curl -X POST "https://demo.firefly-iii.org/api/v1/api/v1/piggy_banks" -H "accept: application/json" -H "Authorization: Bearer xxxx" -H "Content-Type: application/json" -d "{\"name\":\"Piggy bank bug\",\"account_id\":1,\"target_amount\":\"111\",\"object_group_title\":\"A group title\"}"

**Comment by JC5** [comment]
I get the same problem, but without the internal exception. I'll dive into it.

**Comment by JC5** [comment]
Fixed in the next release.
