### ISSUE TITLE
Failed to reconcile asset account - bcmath function argument is not well-formed

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#4439]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

I tried to reconcile my account, but could not complete the reconciliation. I received the following report via mail:

`bcsub(): bcmath function argument is not well-formed.`

You can find the complete stacktrace in this [Gist](https://gist.github.com/niklas2810/930e7458ca3abac2d76385d7487ac006)!

**Steps to reproduce**

I couldn't reproduce this on the demo site, but maybe you can figure out what happened from the stack trace 😄 

**Extra info**

If you need more info, please let me know. I could forward the mail containing the error to you if it could help with analyzing the problem. Clicking the link provided there produces the same exception again, so I can at least reproduce it on my own instance.

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files

**Comment by JC5** [comment]
Thanks for letting me know. I can't really tell from the stack trace unfortunately. It feels like a JS error somewhere.

This page is due for a refresh in the new layout. I fear you'll have to live with this for the time being.

**Comment by niklas2810** [comment]
No worries! I reloaded the page + adjusted the time span a bit and everything worked just fine again afterwards.
