### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by ClementNerma** [firefly-iii/firefly-iii#4442]
Hi,

I'm currently using Firefly III (v5.4.6), and from times to times when starting the Docker container I'll get empty responses from `localhost:7000` (no error, the response is simply completely empty).

The container's logs shows the repeated error:

```
PHP Fatal error: Uncaught ReflectionException: Class config does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:809

Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(809): ReflectionClass->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Foundation\Application->make()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(275): app()
#7 /var/ww in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 811
PHP Fatal error: Uncaught ReflectionException: Class config does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:809
```

I'm using Docker-Compose like shown in [another issue](https://github.com/firefly-iii/firefly-iii/issues/4270#issue-786840669).

Recreating the containers with `docker-compose up --force-recreated -d` seems to solve the problem (at least the 2 times I've had it).

Any idea on what's causing this?

**Comment by JC5** [comment]
Sometimes this is caused by bad config variables, often the APP_KEY. But sorry, what's happening is anyone's guess. I've had this in the past myself and I was never able to solve it without resetting one thing or another.

**Comment by ClementNerma** [comment]
Ok so at least I'm not the only one with this error.

I'll try to debug this a bit the next time I have this error ;)
