### ISSUE TITLE
Ability to flag transactions for future reference

### ISSUE THREAD

**Issue by sManWorks** [firefly-iii/firefly-iii#4445]
**Description**
When viewing transactions when a transaction is disputed or missing or incorrect on the bank/retailer end, you may want to come back to that transaction on a later date. With enough transactions stored on firefly, it can become difficult to find the transaction on a later date.

**Solution**
- Add an optional field called 'Flagged' for transactions. 
- Enable a quick action in the "Actions' button dropdown for transactions to toggle Flagged field
- Add ability to see flagged transactions by using either a flagged 

**What are alternatives?**
Tags field can be used that would separate out the transactions but it doesn't allow for highlighting when viewing table

**Comment by JC5** [comment]
Sorry, I'm not going to add it. I never saw the added value, I was always able to find the transaction in question just fine.
