### ISSUE TITLE
Bill "Paid this period" for today is "Expected 1 second ago"

### ISSUE THREAD

**Issue by AndreiGavriliu** [firefly-iii/firefly-iii#4460]
**Description**
Hi, I'm running FF5.4.6 and while checking my bill status, noticed that those expected today are `Expected 1 second ago`. While this is technically true, the description could be improved:

**Solution**
* Change `Expected 1 second ago` to `Expected today`
* Change `Expected 1 day from now` to `Expected tomorrow`

**Bonus points**
> - Make a drawing

Sorry, not very good ad drawing :)

**Comment by JC5** [comment]
Thanks for letting me know. I'll pick it up for the new layout :+1:

**Comment by AndreiGavriliu** [comment]
There's a new layout? Any branch in particular I could clone to check it out and do some bug-hunting?

**Comment by JC5** [comment]
It's one giant bug lol. But check out develop or the beta and set `FIREFLY_III_LAYOUT=v2` and it will show you v2 whenever possible.
