### ISSUE TITLE
Identifier based csv import ignored

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#4465]
**Bug description**
I am running Firefly III version 5.4.6 and csv-import 2.5.0, and my problem is:

Im trying to use the "identifier based" deduplication functions, but my transactions get imported twice.

**Steps to reproduce**
* import the following csv

https://pastebin.com/geC1aVyE

here my config:

https://pastebin.com/iftZDZuN

* import the csv again
* every transaction got imported twice
* already tried with different "Unique column type" - didnt change anything.

**Bonus points**

- I searched and nobody reported this bug before
- I was able to replicate it on the demo site https://demo.firefly-iii.org/ (does demo has a csv-import?)
- I donated money ;)

**Comment by JC5** [comment]
I'm sorry, I can't replicate this. 

<img width="1141" alt="double" src="https://user-images.githubusercontent.com/5889984/109777347-88610700-7bfb-11eb-862a-a03175bfe561.png">

In your config file there is a bracket missing `}`. Final character. Is this a copy/paste error or something else?
