### ISSUE TITLE
Inconsistency in /api/v1/budgets

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4482]
**Description**
I am using the demo website.  There is inconsistency in the budget endpoint for `auto_budget_currency_id` attribute. I'm not sure if this is a bug or it is working as intended. 

```
"auto_budget_type": null,
"auto_budget_period": null,
"auto_budget_currency_id": "",  <-- empty string but others are null
"auto_budget_currency_code": null,
"auto_budget_amount": null
```

I feel that `auto_budget_currency_id` should return `null` instead of an empty string so that it will be consistent throughout the API.

**Comment by JC5** [comment]
Indeed, that would be correct. I'm currently pouring over the API for the next beta and there are plenty of "features" like this one. Thanks for reporting :+1:

**Comment by JC5** [comment]
Fixed in the latest beta.
