### ISSUE TITLE
Locale not working in transaction creation

### ISSUE THREAD

**Issue by bannisdale** [firefly-iii/firefly-iii#4498]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is: I have chosen the language English but locale is German (Germany). Therefore, dates and amounts are correctly displayed as

"12.03.2021 - 99,99 €".

However, when I create or edit a transaction, it looks like this:

![image](https://user-images.githubusercontent.com/42511384/110950723-79d5c680-8344-11eb-81f7-e2f02d25214c.png)

**Steps to reproduce**

- create a transaction
- try to enter an amount based on the German locale (with , as delimiter) OR look at the date order

**Extra info**
This is by far not a big issue, but an inconsistency that sometimes bugs me a bit. :D

**Comment by JC5** [comment]
Is your browser or OS set to English, by any chance?
