### ISSUE TITLE
Using the CSV importer with proxy authentication

### ISSUE THREAD

**Issue by jbergler** [firefly-iii/firefly-iii#4501]
Hi James - thanks for all the work that goes into this project!

I've deployed with Docker + Authelia. So far so good, the Remote-User header gets parsed.
But that's where I seem to get stuck, it seems that the web app disables anything related to oauth + personal access tokens with this mode enabled, which makes sense - does this mean that this mode is also not compatible with the importing tools that rely on the api?

**Comment by JC5** [comment]
It will be in the new release, but keep in mind you must then exclude the API path from Authelia.
