### ISSUE TITLE
Split transaction 

### ISSUE THREAD

**Issue by M-Paladin** [firefly-iii/firefly-iii#4508]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

1st problem :
Split transaction cannot be moved above or below another transaction in the show account screen
![image](https://user-images.githubusercontent.com/49365410/111073084-a4a75280-84dd-11eb-98e1-cfbde6c68a98.png)
Normal transaction can be moved below and above split transaction by the way

2nd problem
Also I can move a part of a transaction into another
![image](https://user-images.githubusercontent.com/49365410/111073130-d1f40080-84dd-11eb-9c94-b070345702b4.png)
I can also move a normal transaction into a split transaction

After refreshing the screen, everything come back in original place without any change, it seems purely visual

**Steps to reproduce**
See above

**Extra info**
Debug information generated at 2021-03-14 16:45:52 Europe/Paris for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.15 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 049cfdc3-2852-4694-8580-cb86fa4bc87d |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2012-01-01 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0 |

**Comment by JC5** [comment]
Thanks for letting me know. I'm not going to fix this as I'm working on a new layout (where this will work again).
