### ISSUE TITLE
Suggestion: Pending Income

### ISSUE THREAD

**Issue by Mrcrypt** [firefly-iii/firefly-iii#451]
It would be cool if you create pending Income tab. 
For example I write an invoice to someone, but it takes some time until the money is on my Bank. 
So I want to see who has to pay my bills, because it takes weeks until they pay. When they pay I click accept and the transaction is added to my account. 

Firefly is awesome for my personal use, with that function I could manage my business Finances as well.

**Comment by JC5** [comment]
There have been a lot of ideas for "financial planning". The ability to schedule transactions, to plan expenses and deposits, and to be able to predict what is going to happen in the future.

This idea fits financial planning as well: you would be able to predict your incomes by keeping a list somewhere.

I feel that such a list would be part of a larger system that manages your invoices. The ability to create, manage and send invoices is something typical of a business finance system, as you mention. And being able just to see which invoices have yet to be paid seems to be "double administration": your business financial software should already keep track of this.

As far as Firefly is concerned, such transactions could be part of "planned expenses" or rather "planned income" as another issue has suggested. 

It's not going to happen in the near future. Currently I'm focussing on the import/export and the ability to see what happened (past tense) using reports and charts. The extrapolation to the future is something that needs to be done manually, and that includes invoice management.

**Comment by Mrcrypt** [comment]
Okay if I find some spare time I'll fix some bugs and make pull requests
