### ISSUE TITLE
Moving visually transaction in show account screen

### ISSUE THREAD

**Issue by M-Paladin** [firefly-iii/firefly-iii#4511]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

In the show account screen, normal transaction can be moved below and above another transaction existing the same day but the move isn't saved after changing to previous or next page or refresh screen

PS : impossible to move transaction in reconcile screen but maybe in the new layout ?

**Steps to reproduce**
Move a transaction of the same day above or below another, hit previous or next and come back to original page or refresh screen (F5) and move is lost.

**Extra info**
Debug information generated at 2021-03-15 20:37:17 Europe/Paris for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.15 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 049cfdc3-2852-4694-8580-cb86fa4bc87d |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2012-01-01 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0 |

**Comment by JC5** [comment]
#4311
