### ISSUE TITLE
Ability to set Currency Equivalences for graphs

### ISSUE THREAD

**Issue by LuminousPath** [firefly-iii/firefly-iii#4515]
**Description**
I currently run firefly to manage my accounts in USD and Japanese Yen and I noticed that because of the amount discrepancies (in general 100 yen is around 1.00 USD) the graphs on the dashboard are nearly useless (my japanese yen balances always squash the USD balances to where they can't be seen.

I realize that having an FTX number isn't exactly a good idea for the long run (you'd have to constantly update this) At least for pie graph/line graph dispays it would be nice to have some kind of equivalency setting available to that these aren't useless.

**Solution**
Some kind of option in currency preferences that sets the display levels in graphs to some division of the actual value would be extremely useful.

(i.e. setting a currency division to 100 would make all the graphs display lines at 1/100 the scale of the value of the currency)

that or a setting for the default currency equivalent would be useful as well.

**What are alternatives?**
Currently the only real alternative is to remove all but one currency from screens like the dashboard, but that doesn't really help on screens like categories, etc.

**Additional context**
![image](https://user-images.githubusercontent.com/374740/111729297-14d52000-88b2-11eb-99d6-68d247c2e779.png)
(The blue is my Yen amounts, but all of the slices are, in actuality, around the same amount of value)

![image](https://user-images.githubusercontent.com/374740/111729523-9af16680-88b2-11eb-9f8a-2be71e2df7e5.png)
(Again, the lines at the bottom are USD while the yellow line is a JPY account)

**Bonus points**
Potentially:
![image](https://user-images.githubusercontent.com/374740/111729817-4a2e3d80-88b3-11eb-973a-3df6cb1b36e2.png)
(with JPY as the default currency)
![image](https://user-images.githubusercontent.com/374740/111729953-9c6f5e80-88b3-11eb-9933-8d3a8a83325f.png)
(with USD set as a 100th of the value of the default currency)

**Comment by JC5** [comment]
This has been suggested before and a solution is in the works.
