### ISSUE TITLE
Public CSV Importer shows 404 if URL is entered

### ISSUE THREAD

**Issue by DopingAnt** [firefly-iii/firefly-iii#4516]
Using https://csv-importer.firefly-iii.org/token brings up the UI as always but when I enter my URL or even the demo URL (https://demo.firefly-iii.org/login) and enter a random client ID the screen only shows 404 NOT FOUND.

I tried the current Firefox 86.0.1  and Chromium 87.0.4251.0. My instance is running Firefly-III Version 5.4.6 on YunoHost.

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
Should work again!
