### ISSUE TITLE
icons / thumbnails not shown 

### ISSUE THREAD

**Issue by MaxMapo** [firefly-iii/firefly-iii#4519]
I am running Firefly III version 5.5.0-beta.3 FIREFLY_III_LAYOUT=v2

**Description**
![image](https://user-images.githubusercontent.com/81110037/111917400-13f1e900-8a80-11eb-9f56-ef5dd58dfd13.png)

**Extra info**
 

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
I can't replicate this. Are there errors in your browser console?

**Comment by MaxMapo** [comment]
thanks for the reply. I solved by copying the font folder in the html root, because I saw that they are required without going through /firefly-iii/public but directly from my-site/fonts/vendor/@fortawesome/fontawesome-free/

**Comment by JC5** [comment]
Ah, so you are running Firefly III at https://example.com/something/public/?

There's a few reasons you shouldn't do that, and this is one of them.

**Comment by MaxMapo** [comment]
yes, my url is https://example.com/firefly-iii/public/, could you give me the link to the correct configuration? thanks

**Comment by JC5** [comment]
I don't have one, but if you're running Apache please google "apache change webroot".

**Comment by erdmenchen** [comment]
Same issue here.
After upgrading from 5.4.6 to 5.5.7, the icons are missing in layout v2.

I am running firefly on a NAS in a subdirectory of the web root folder.
A symlink is pointing to the public folder, so "/" is not the public folder.
https://example.com/firefly points to the public folder.

I think the problem is, that the fonts are imported from the servers root directory and not relative from the public folder...
It used to work in v1 layout. What changed?

**Comment by JC5** [comment]
What, apart from the entire layout?

**Comment by erdmenchen** [comment]
Maybe this can help: https://github.com/JeffreyWay/laravel-mix/issues/1292

And here is maybe a solution: https://github.com/JeffreyWay/laravel-mix/issues/474#issuecomment-520190140

**Comment by JC5** [comment]
Great! Fixed in the next release! :+1:

**Comment by erdmenchen** [comment]
You are awesome! Thank you so much for your work!

I'm looking forward to the next release and will test it as soon as possible.

**Comment by erdmenchen** [comment]
Works perfectly. Thank you!
