### ISSUE TITLE
"Show only top 10" link on Default Financial Report does nothing

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4521]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

When looking at a month in the default financial report, the "Revenue / income," "Expenses," "Categories" and possibly "Budgets" boxes default to only showing the top 10. These can be expanded to the full list with the "Show entire list" link at the bottom of each box. Once expanded, a link appears on the bottom that says "Show only top 10." This does not do anything.

**Steps to reproduce**

1. Have a month or set of months with transactions from 10+ Revenue / income accounts, Expense accounts. and/or categories.
(note: all categories are already shown by default when doing 3+ months)
2. Expand one of the boxes by clicking the "Show entire list link"
3. Click the "Show only top 10" link in the same box.
4. See that it does not work.

**Extra info**

Debug information generated at 2021-03-21 16:59:03 America/New_York for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.16 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-03-01 00:00:00 |
| Session end | 2021-03-31 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks. I remember a similar issue with those lists a few months ago. I'm not going to fix it.
