### ISSUE TITLE
Kubernetes install isn't working

### ISSUE THREAD

**Issue by ea-p** [firefly-iii/firefly-iii#4522]
**Bug description**
I am trying to install Firefly III with kubernetes with the kubernetes installer from https://github.com/ea-p/kubernetes, and my problem is:

I managed to get a reverse proxy with apache going to access the service, but the best result I can get is a 

SQLSTATE[HY000] [2002] No route to host (SQL: select * from information_schema.tables where table_schema = fireflyiii and table_name = migrations and table_type = 'BASE TABLE')

**Steps to reproduce**
Clone https://github.com/ea-p/kubernetes,  and run  -  kubectl apply -k ./ 
Cloning https://github.com/firefly-iii/kubernetes the pods don't even fire up. They keep pending because they can't pull a PVC

The same error appears if i /bin/bash into the firefly-iii pod and try to execute:
php artisan migrate:refresh --seed

I haven't redone it now, but I recall getting the same error if I try to do this with docker and a databse in docker so I think this might be some kind of networking issue.
 
[logs.log](https://github.com/firefly-iii/firefly-iii/files/6177986/logs.log)

**Extra info**
Screenshot:
![Untitled](https://user-images.githubusercontent.com/19634656/111925463-a65eb080-8ab1-11eb-9e55-4080d88913db.png)

OS: Centos 8.3

kubectl version output: 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Bonus points**
- [x]  I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files  Going to activate debug level tomorrow, it's a tad bit more complicated with k8s.
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/ - Installation issue, don't think this can be replicated on the demo site.

**Comment by JC5** [comment]
I know nothing of kubernetes, I just provide the files.
