### ISSUE TITLE
RSA not found

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#4524]
Hello, I am getting an error when navigating to /profile in my browser.

```
 /var/www/firefly-iii/app/Support/Http/Controllers/CreateStuff.php 
...
Class 'phpseclib\Crypt\RSA' not found
```

I am using the latest commit on main (e64653eaff33ec36dd07f77491728684b67ad782).

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4520
