### ISSUE TITLE
When executing a rule manually, default the date range to the current month

### ISSUE THREAD

**Issue by srpnor** [firefly-iii/firefly-iii#4527]
Just a simple suggestion - given the dire warnings about how running a rule across a lot of transactions can *really* muck things up, why not default the date range to the start of the current month - present day, rather than at the moment it seems to be from the date of the very first transaction to the present day?  Of course the end user can always change it if they want, but it means you start from a presumption of only wanting to affect the most recent transactions, and limits both the scope and processing time.  (I certainly find I create new rules in response to recent transactions, so it's rare I'd ever want to run a new rule against all historic transactions - possibly this is true for most people?)

**Comment by JC5** [comment]
Thanks for the suggestion. The original use case for the form is *because* people wanted to have their rule(s) applies to all of their transactions. But I'll take it under consideration for the new layout. In the current layout, it's not going to be changed.
