### ISSUE TITLE
Drafts feature

### ISSUE THREAD

**Issue by uargb** [firefly-iii/firefly-iii#4530]
# Transaction drafts

Eg. 1: I am now sitting and filling out transactions. I know that there is a payment to be made tomorrow. I would like to create a "draft" now, and approve it tomorrow.

Eg. 2: I have a bank card. I get a transactions by the API. I want this bank-transactions to arrive in drafts, where I would add additional information to them before turning into a f3-transaction.

Is this feature planned for development? I wish to make pull request with it if not)

**Comment by JC5** [comment]
No, I'm not really interested in adding draft transactions.
