### ISSUE TITLE
Reverse proxy has trouble if not at root level

### ISSUE THREAD

**Issue by lpyparmentier** [firefly-iii/firefly-iii#4532]
**Bug description**
I am running Firefly III version jc5x/firefly-iii:version-5.4.4 , and my problem is:

Similar as #2848 or #4467. Firefly run under a container, which is cool to host on arm board at home, however if the reverse proxy is not set-up as  root location (`location /`), something goes wrong with the redirection. 

Why it matters ? the benefit of arm board with container is to have multiple services on the same board for self-hosting stuff. It kills all the benefit here. If other services bring the same issues, I can't deal with multiple services on the same host. I have to change the code for each project and build dedicated image. I'm saying that because based on past issues it's always closed and considered as isolated case or not a problem related with firefly which in fact is. 

**Steps to reproduce**
run jc5x/firefly-iii:version-5.4.4 container and set-up a reverse proxy with location /firefly 

Some propose a hack like in #4243, if i have to hack each project it becomes a waste of time... Can't do that for each of the services I host at home :)

EDIT: also tried https://github.com/firefly-iii/firefly-iii/issues/1869#issuecomment-450594411, got `FireflyIII 404 Not Found :(`.

**Comment by JC5** [comment]
It's not a problem with Firefly III, and I will close this ticket just the same. You have three options.

1. Use subdomains if you want to host multiple services on one host.
2. Find a reverse proxy that will not just change `host:port` but `host:port/path`.
3. Build a Docker image in which the webserver believes it's being served at `/whatever` so it matches up with your reverse proxy config.

The Firefly III Docker image has a built in Apache that assumes it's at `/`. Reverse proxy's can't change that so if you start aliassing stuff to `/firefly-iii` they will forward the `/firefly-iii` part to Firefly III who will then give a 404.

I built the Docker image for the `/` use case and it services 99% of people using Firefly III. If you have to hack every project to get it your way maybe this isn't my problem.
