### ISSUE TITLE
Avoiding webhook loops

### ISSUE THREAD

**Issue by jacopo-j** [firefly-iii/firefly-iii#4541]
Hello, I see that Firefly 5.5.1 introduces webhooks, which are a very welcome feature. 

It looks like at the moment there is no possibility of preventing webhooks from being triggered when creating/updating/deleting a specific transaction, neither from the UI nor from the API. This might be problematic for situations like this:

- A transaction is created
- A webhook is triggered and runs a script
- The script creates an additional transaction using Firefly's API
- The creation of this additional transaction triggers the execution of the webhook, over and over again

It would be useful to have an API option for the `transactions` endpoint that prevents webhooks from being triggered, in a similar fashion to how `apply_rules` works.

**Comment by JC5** [comment]
Not a bad idea, I'll write it down :+1:
