### ISSUE TITLE
SQLSTATE Duplicate column

### ISSUE THREAD

**Issue by steakhutzeee** [firefly-iii/firefly-iii#4549]
I am running Firefly III version 5.5.1.

**Description**

Hi,
actually i see some errors in my logs about duplicate columns, don't know if these show up after latest update but never saw them before.

`[2021-03-28 12:43:09] local.ERROR: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name "budget_limit_id" (SQL: alter table "budget_transaction_journal" add "budget_limit_id" int unsigned null after "budget_id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S21): SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name "budget_limit_id" (SQL: alter table "budget_transaction_journal" add "budget_limit_id" int unsigned null after "budget_id") at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678)`

`[previous exception] [object] (PDOException(code: 42S21): SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'budget_limit_id' at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:471)`

```
    today at 12:43  In Connection.php line 678:
    today at 12:43                                                                                 
    today at 12:43    SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'budget_  
    today at 12:43    limit_id' (SQL: alter table `budget_transaction_journal` add `budget_limit_  
    today at 12:43    id` int unsigned null after `budget_id`)                                     
    today at 12:43                                                                                 
    today at 12:43  
    today at 12:43  In Connection.php line 471:
    today at 12:43                                                                                 
    today at 12:43    SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'budget_  
    today at 12:43    limit_id' 
```

Debug information generated at 2021-03-28 22:42:54 Europe/Rome for Firefly III version **5.5.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.1 |
| Firefly III API | 1.5.0 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | da25608d-8526-4fc7-92f1-93ac99fccdfa |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | it_IT |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-03-01 00:00:00 |
| Session end | 2021-03-31 23:59:59 |
| Session first | 2021-02-01 00:00:00 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Comment by JC5** [comment]
I have no been able to replicate this myself.

https://github.com/firefly-iii/firefly-iii/discussions/4545
