### ISSUE TITLE
Asset account not aware of deposit

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#4555]
I am running Firefly III version 5.51, and my problem is:

I am creating deposits in one of my account, and for some reason these are not being shown in the graph as well as in the balance of the relative period. This initially started when I converted an existing payment into a transfer (so that instead of the money going fom A -> X, it would go A -> B -> X)

**Steps to reproduce**
- Take an old payment from Asset Account A to StoreX
- Transform old payment into transfer from Asset Account A to Asset Account B
- This already shows the issue, with Asset Account B not noticing the deposit

Do note that the deposit IS shown in the list of the transfers, but the total amount is just wrong (see image)

I have tried removing the transfer and doing it from the beginning, and the issue persists.

I currently cannot reproduce this on the demo website. 

**Extra info**
Image: https://imgur.com/a/1Y0ui9D
Debug information generated at 2021-03-29 10:15:10 Europe/Stockholm for Firefly III version **5.5.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.1 |
| Firefly III API | 1.5.0 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 5d944787-b68d-4379-b252-fe43600e9986 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-12-31 00:00:00 |
| Session first | 2015-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0 |

**Comment by AlexKalopsia** [comment]
Ok, I have found out the issue, in that the account is in € and the deposit was in kr with no foreign value assigned. 

I am guessing this is somewhat expected behavior, but it feels like Firefly should somehow show a warning of some sort!

**Comment by JC5** [comment]
Thanks for letting me know. I'll see what I can do about the warning: especially when converting transactions it's not always obvious what the end result will be. Nevertheless, I agree that it's unclear at the moment.

**Comment by JC5** [comment]
This will be fixed in the new layout.
