### ISSUE TITLE
Auto-calculate from total when splitting expense

### ISSUE THREAD

**Issue by SamBouwer** [firefly-iii/firefly-iii#4556]
**Description**

When splitting an expense, the user must calculate the correct amounts themselves. If the user makes a calculation error, the total of the transaction changes. A "workflow" to split a transaction could prevent this.

**Solution**

When a user hits the "Add another split" button, the page is separated into two sections:

1. Top section with information that is applicable to the whole transaction that will be split
    * Currently
      * Description of the split transaction
    * To be added:
      * Source account (read only as it cannot be changed if I understand the documentation correctly)
      * Total amount (which is initially based on the original amount of the whole transaction, but can be overridden by the user, see below)
      * Date (it would not make sense to me to have a different date for the splits, as the transaction was made on a single moment, otherwise it would have been a separate transaction and splitting would not be needed in the first place :) )
      * Payment date (for the same reason)
2. Middle section with multiple splits (preferably organized horizontally for easy comparison but can be vertically shown on smaller screens). For every split, the fields that should be shown:
    * Description (initially empty, as this should be provided by the user)
    * Destination account (can be edited if I understand the documentation correctly)
    * Amount (when the first split is added, the amount can be empty by default, but upon the second split the remaining amount can be calculated and filled in automatically: original amount - sum of any existing splits. A warning should be presented when the sum of the splits does not match the original amount)
    * Foreign amount
    * Budget
    * Category
    * Tags (not sure if this is or should be linked to the splits only or whether the original transaction can have its own tags)
    * Bill
    * Notes

**What are alternatives?**

Leave the current setup as it is. Honestly, it works fine, but I think it can be improved.

**Additional context**

The same can be applied to Income and Transfers but with different rules to what is set to read only and what fields can be edited.

**Bonus points**

I've checked the documentation on splitting transactions here prior to logging this feature request: https://docs.firefly-iii.org/firefly-iii/concepts/transactions/#split-transactions

**Comment by JC5** [comment]
Thanks for the suggestion! I'm working on a new form in the new layout. I'll try to implement your suggestions, I like them.

**Comment by TWART016** [comment]
Is there something new for this feature?

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/6304
