### ISSUE TITLE
Choose visible columns in expenses overview

### ISSUE THREAD

**Issue by SamBouwer** [firefly-iii/firefly-iii#4558]
**Description**

It would be great if you could choose the columns to be visible in the Expenses overview (https://[url]/transactions/withdrawal). For example, I'm more interested in the Budget linked to a transaction than to the Category linked to a transaction

![image](https://user-images.githubusercontent.com/6918900/112889111-817fc400-90d5-11eb-9fbc-a5e2e1a15288.png)

**Solution**

Allow the user to choose the columns to hide or display, like source/destination account, category, budget, tags, and (maybe0 keep some columns fixed./always visisble like description, amount, and date.

**Bonus points**

Allow the user to fully customize the overview as if it was an Excel sheet: set columns to be visible or hidden, change column order, sort and filter the overview. I would of course understand if that is not the aim of the Expenses overview!

**Comment by JC5** [comment]
Sorry no, this will not be optional.
