### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long.

### ISSUE THREAD

**Issue by GaneshKandu** [firefly-iii/firefly-iii#4563]
**Bug description**

I am running Firefly III version 5.5.1, and my problem is:

```
In Connection.php line 678:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 767 bytes (SQL: alter table `webhooks` add uniqu
  e `webhooks_user_id_title_unique`(`user_id`, `title`))


In Connection.php line 471:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 767 bytes
```

Getting this issue on ``php artisan migrate:refresh --seed`` command.

**Steps to reproduce**

[https://docs.firefly-iii.org/firefly-iii/installation/self_hosted/#installing-firefly-iii](https://docs.firefly-iii.org/firefly-iii/installation/self_hosted/#installing-firefly-iii)

**Extra info**

|  | version| 
| -------- | -----  | 
| FireFox | 88.0b3 (64-bit) | 
| MySQL | 5.5.62 | 
| PHP | 7.4.11 | 
| PHP | Centos 6 ( Linux webuzo.web 2.6.32-754.el6.x86_64 \#1 SMP Tue Jun 19 21:26:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux ) |

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/discussions/4543
