### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by starkyller** [firefly-iii/firefly-iii#4567]
**Bug description**
I am running Firefly III version 5.5.1, and since I have made sure that the translations for Portuguese are at 100% there seams to be some missing sentences for translation in the alert div.

**Steps to reproduce**

Go to the preferences and change  the language.

![imagem](https://user-images.githubusercontent.com/15750437/113044365-73917800-9195-11eb-8b9d-c81901dd6b06.png)

I'm assuming the problems is at:
app/Http/Controllers/PreferencesController.php  line 187

**Comment by JC5** [comment]
This is untranslated on purpose.
