### ISSUE TITLE
Reports: All time, all accounts gives: Could not render report view: View [reports.default.multi-year] not found.

### ISSUE THREAD

**Issue by MaxBayly** [firefly-iii/firefly-iii#4568]
**Bug description**
I am running Firefly III version 5.5.1, and my problem is:

Selecting the "default financial report" for the range "all time, all accounts" displays the error "Could not render report view: View [reports.default.multi-year] not found."

**Steps to reproduce**
Simply click the "All-time, all accounts" link under the "Default financial report" heading.
**Extra info**
Browser: Chrome
Host OS: Debian (Firefly is dockerised)
Browser OS: macOS

The rendered URL is as follows:
`https://my.domain.tld/reports/default/34,10,18,8,32,5,58,59,1,12,61,42,41,54,53/20191127/currentMonthEnd`

The problem is NOT present on the demo site

Debug info:

Debug information generated at 2021-03-31 02:02:57 Europe/Amsterdam for Firefly III version **5.5.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.1 |
| Firefly III API | 1.5.0 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 346f6dac-ce23-48b3-b885-71753dc408bd |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2019-11-28 00:00:00 |
| Session end | 2021-03-31 00:00:00 |
| Session first | 2019-11-27 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36 |

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4548

**Comment by MaxBayly** [comment]
Apologies, didn't realise this was related
