### ISSUE TITLE
Rule Engine bug: linking a deposit to a bill 

### ISSUE THREAD

**Issue by cooperonie** [firefly-iii/firefly-iii#4569]
**Bug description**
I am running Firefly III version 5.5.1, and i found the following bug:

I was making a rule with action "Link to a bill" and a trigger that'd point to an incoming (+xx€) ​payement.
This made tireflyiii spit out error "500" several times while i thought the issue was my trigger.. then i realized it's probably due to linking an incoming payement to a bill..

It works fine now that i removed the "link  to a bill" action, maybe implement an proper error message?

**Comment by JC5** [comment]
Trying this myself, I only get the (expected) error in my logs. No 500, I'm afraid.

> [2021-03-31 17:21:17] local.ERROR: RuleAction LinkToBill could not set the bill of journal #226 to bill "Rent": no such bill found or not a withdrawal.  

Applying the rule manually also seems to work:

<img width="551" alt="Screenshot 2021-03-31 at 17 23 01" src="https://user-images.githubusercontent.com/5889984/113169319-02a19d00-9235-11eb-91e0-537664a1165f.png">

Let me know! :+1:
