### ISSUE TITLE
Everything on the V2 dashboard is off by 1 day

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4571]
**Bug description**
I am running Firefly III version 5.5.1 (layout v2) and my problem is:

Everything on the V2 layout is listed one day earlier than it should be.

Here's my date range:
![image](https://user-images.githubusercontent.com/21091510/113196296-53af9200-9231-11eb-8464-47fb26a0c5ef.png)

I'll start small and super obvious:
Here's a bill:
![image](https://user-images.githubusercontent.com/21091510/113194151-cd924c00-922e-11eb-923f-64c3cf65034c.png)
You can see that the next expected match is March 15, 2021.
Here's the same exact bill on the v2 dashboard:
![image](https://user-images.githubusercontent.com/21091510/113194255-edc20b00-922e-11eb-80b4-18ad0c381770.png)
You can see here that the next expected match is March 14, 2021.

Here's a test transaction in process:
![image](https://user-images.githubusercontent.com/21091510/113194689-645f0880-922f-11eb-9b0b-5096d2cfbee3.png)

Here it is after I made it (also a day earlier for some reason?):
![image](https://user-images.githubusercontent.com/21091510/113194847-907a8980-922f-11eb-9be9-3a6659ce9d32.png)

And here it is a day earlier that that on the dashboard:
![image](https://user-images.githubusercontent.com/21091510/113194924-ab4cfe00-922f-11eb-9dbf-17109373d863.png)

So apparently if you make your transaction for any day earlier than today, it sets it back a day earlier than that. Do you want a different bug report for that?

The asset account graph starts February 28 instead of March 1 (that might be intentional?)
![image](https://user-images.githubusercontent.com/21091510/113195494-565db780-9230-11eb-8f68-b5b14f4fefbe.png)

The range on the custom timed budgets is also off by a day on both ends:
![image](https://user-images.githubusercontent.com/21091510/113195695-8e64fa80-9230-11eb-8dac-039a29b13d47.png)

**Steps to reproduce**

1. Be on the V2 layout
2. Have bills or budgets
3. Look at the dates

**Extra info**

Debug information generated at 2021-03-31 14:53:21 America/New_York for Firefly III version **5.5.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.1 |
| Firefly III API | 1.5.0 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-03-01 00:00:00 |
| Session end | 2021-03-31 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before (I thought I saw a report like this but I couldn't find it.
- [ ] I have added a stack trace from my log files 
- [x] - I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/ (Demo site is v1)

**Comment by JC5** [comment]
I know it happens when you're using Firefox, because the dates are often formatted as UTC in Firefox. I'll check it out!

**Comment by JC5** [comment]
Oh and that may also explain why the next/previous is off. It takes the date, turns it into a Javascript date object, which is UTC, which is then a day earlier becayse NY is at -6 or something.

**Comment by JC5** [comment]
Yep that's it. Every date jumps back X hours. I'll see what I can do.

**Comment by JC5** [comment]
This will be fixed in 5.5.2 :+1:

**Comment by death2cupbots** [comment]
Ok the dashboard looks good now, but I'm still having my transactions jump back a day. This only happens if you type anything in the date box. If I leave it set to today, it posts with the correct date. If I change the date box _at all_ even if you just type over it with the current date, it posts back a day. Changing the time box has no effect on the date. The time of the transaction does not matter. This is not happening in V1, and transactions made in V1 stay the correct date when shifting to V2.
