### ISSUE TITLE
404 Not Found when you try to reconcile accounts on V2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4572]
**Bug description**
I am running Firefly III version 5.5.1, and my problem is:

If I try to reconcile an asset account on layout v2 it brings me to a 404 Not Found page.

This does not happen when I switch back to v1 or on the demo page.

The URL it brings me to is [my domain]/accounts/reconcile/[n] where [n] is the id of the account. If I manually append /index to the end of the URL it does work.

EDIT: Oh there was a message in the log: `[2021-03-31 15:16:42] local.WARNING: GracefulNotFoundHandler cannot handle route with name "accounts.reconcile"`

**Steps to reproduce**

1. Be on Layout V2
2. Have or make an asset account
3. Go to the asset accounts page
4. Click on the actions drop down menu on any asset account
5. Click "Reconcile this account
6. See the 404 | Not Found message

**Extra info**

Debug information generated at 2021-03-31 15:12:35 America/New_York for Firefly III version **5.5.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.1 |
| Firefly III API | 1.5.0 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-03-01 00:00:00 |
| Session end | 2021-03-31 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files  (nothing in the logs)
- [ ] I have added a screenshot. (I think you know what the 404 site looks like)
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/ (Demo site is not v2)

**Comment by JC5** [comment]
Thanks, will be fixed in 5.5.2 :+1:
