### ISSUE TITLE
Cannot Access Administration in v2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4576]
**Bug description**
I am running Firefly III version 5.5.1 (layout v2), and my problem is:

When I try to go to my administration settings, I get a page that says:
![image](https://user-images.githubusercontent.com/21091510/113314215-1226f180-92da-11eb-8cc0-b6ce7282d3f3.png)
The page does work in v1, and the URL it brings you to is the same in both versions. Other settings just bring you to the v1 layout. The webhooks link also doesn't do anything (but that's probably intentional).

**Steps to reproduce**

1. Be on v2 layout
2. Go to the administrator settings
3. See the message

**Extra info**

Debug information generated at 2021-04-01 11:05:11 America/New_York for Firefly III version **5.5.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.1 |
| Firefly III API | 1.5.0 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-03-01 00:00:00 |
| Session end | 2021-03-31 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/ (some day I'll be able to test these things on the demo site)

**Comment by JC5** [comment]
Thanks, I knew about it. There was a comment from a new user earlier in a closed ticket, it should be fixed in 5.5.2.

**Comment by JC5** [comment]
5.5.2 is released.
