### ISSUE TITLE
Editing Time on transactions in V2 is strange

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4578]
**Bug description**
I am running Firefly III version 5.5.1 (v2), and my problem is:

I'm sure it's still a work in progress and I'm not actually supposed to edit the time yet, but when you do go to edit the time, the box completely breaks down:
![Fireflyiiitime](https://user-images.githubusercontent.com/21091510/113346791-4f06de80-9302-11eb-9737-311cfd61ca8c.gif)
No matter what I try to do, I cannot put in a new time in that box.

I've tried entering it out by hand and scrolling through the numbers with the arrow keys. If I try to put seconds in, nothing happens. If I try to do AM/PM, the box clears out.

EDIT: It seems to work if you lead with any number other than 0 in the seconds slot:
![Fireflyiiitime2](https://user-images.githubusercontent.com/21091510/113355642-17526380-930f-11eb-8860-186859c161b5.gif)

There is no way to restore the time box aside from restarting the whole transaction. So if we're not actually supposed to be able to edit the time box yet, could you make it so we cannot edit the box?

EDIT: It does work when you click on the clock and go through that menu to set the time:
![Fireflyiiitime3](https://user-images.githubusercontent.com/21091510/113355897-7617dd00-930f-11eb-83a7-10161da73740.gif)
You cannot get the seconds back once you set them to 0 though.

Also, this date:
![image](https://user-images.githubusercontent.com/21091510/113347184-cd638080-9302-11eb-91a5-28b8b075d835.png)
which is normally a valid input is not ISO 8601.

**Steps to reproduce**

1. Be in Layout V2
2. Create a transaction
3. Try to change the time
4. Fail at completing the box

**Extra info**

Debug information generated at 2021-04-01 15:58:25 America/New_York for Firefly III version **5.5.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.1 |
| Firefly III API | 1.5.0 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot. (Please appreciate that I downloaded a gif making program just for this)
- [ ] ~~I was able to replicate it on the demo site https://demo.firefly-iii.org/~~

**Comment by JC5** [comment]
Weird. It works fine for me. The dropdowns, the buttons, it all works. Chrome on a Mac. I see some issues in the edit screen but that's not a part of 5.5.1 yet. 

I'll see what I can find!

**Comment by JC5** [comment]
Made some changes, works for me ™️  in Chrome.

**Comment by JC5** [comment]
5.5.2 is released.

**Comment by death2cupbots** [comment]
Ok time editing seems to be working on new transactions. If I go to edit the time on an existing transaction, the minutes only let you add a second number if you double tap the first number. So if you want "5:47," you would have to type 5 : 4 4 7
![fireflyiiitime6](https://user-images.githubusercontent.com/21091510/113478121-d3697680-9454-11eb-9702-7091c0d7dc29.gif)

**Comment by JC5** [comment]
Hah, that's weird. It's also weird that Chrome doesn't offer to change the seconds. I can't replicate this in Chrome btw. Which browser are you using exactly?

**Comment by death2cupbots** [comment]
I'm using Brave 1.22.71 on Manjaro Linux. I'll bop over to Windows at some point today to see if I can replicate it in Chrome.

**Comment by JC5** [comment]
Stranger and stranger. Let me work on it the next few days. I was hoping for a quick fix but alas.

I also realised Safari doesn't even support time so I have more work to do :D

**Comment by JC5** [comment]
Removed lots of code, but couldn't fully test this. Let me know!

**Comment by death2cupbots** [comment]
Hey this seems to be working totally fine on 5.5.7. Thanks! Also, glad to see you dropped the seconds field on the time!
