### ISSUE TITLE
Docker/Synology : Unable to access the homepage 

### ISSUE THREAD

**Issue by Creepymulder** [firefly-iii/firefly-iii#4580]
Hi,

I'm using the last version (5.5.1)

I followed to the letter the following tutorial : https://www.synoforum.com/resources/firefly-iii-self-hosted-manager-for-your-personal-finances.20/

After starting the container, I'm unable to access the homepage. The browser is sending me a "Connection has been reset". From what I can gather, everything went fine, and the database has been populated. The container port is 80 and I've set up the local port to 8020.

I can't see anything special on the logs and I've double checked everything twice.

Any idea what I would be missing ? I have other containers working fine.

Thanks !

**Comment by Creepymulder** [comment]
Hmm, it's getting interesting. I'm trying to access the Terminal from Docker, the container shut down and I'm getting a "caught SIGWINCH, shutting down gracefully" message.

**Comment by JC5** [comment]
- Firefly III runs at port 8080, not port 80.
- [SIGWINCH shutdowns are sometimes reported](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue+SIGWINCH), but its not something I can fix.

**Comment by Creepymulder** [comment]
Hi,

Ho, thanks, it's working now. Thanks a lot <3.
