### ISSUE TITLE
Cannot post new transaction due to 422 status code

### ISSUE THREAD

**Issue by bertbesser** [firefly-iii/firefly-iii#4581]
I am running Firefly III version 5.4.6

**Description**
Hi,

I'm trying to

```
curl -L --header "Authorization: Bearer `cat ffiii.pat`" --header 'Accept: application/json' --header "Content-Type: application/json" --request POST --data "`cat import.json`" 'http://my-host/api/v1/transactions'
```

where `ffiii.pat` and `import.json` contain, respectively, my PAT and

```
{
  "transactions": [
    {
      "type": "withdrawal",
      "date": "2016-12-28",
      "amount": "6.01",
      "description": "no comment",
      "category_name": "groceries",
      "source_id": 1,
      "destination_id": 7
    }
  ]
}
```

I get this answer;

```
{
  "message": "The given data was invalid.",
  "errors": {
    "transactions.0.description": [
      "Need at least one transaction.",
      "The description field is required."
    ],
    "transactions.0.type": [
      "Invalid transaction type."
    ]
  }
}
```

and the server logs show a `422` status code.

What am I missing?

Thanks a bunch!

**Extra info**
 
the about API endpoint shows version 1.4.0

**Comment by JC5** [comment]
What's the output of `echo [your command]`?

When I run your code it works. 

<img width="690" alt="Screenshot 2021-04-02 at 19 20 35" src="https://user-images.githubusercontent.com/5889984/113438270-c3f81800-93d7-11eb-8077-b33be235029d.png">

**Comment by bertbesser** [comment]
🤔 
```
echo curl -L --header "Authorization: Bearer `cat ffiii.pat`" --header 'Accept: application/json' --header "Content-Type: application/json" --request POST --data "`cat import.json`" 'http://ausgaben.ughbough.de/api/v1/transactions'
curl -L --header Authorization: Bearer ey... --header Accept: application/json --header Content-Type: application/json --request POST --data {
  "transactions": [
    {
      "type": "withdrawal",
      "date": "2016-12-28T12:00:00+01:00",
      "amount": "6.01",
      "description": "kein Kommentar",
      "category_name": "Lebensmittel/Drogerie",
      "source_id": 1,
      "destination_id": 7
    }
  ]
} http://ausgaben.ughbough.de/api/v1/transactions
```

**Comment by JC5** [comment]
> are there some hidden API configurations (such as denying write requests or similar) that i might miss?

Nope. And they wouldn't result in a 422 in any case. I'm working on something else atm, I'll do some digging later.

**Comment by bertbesser** [comment]
No rush. I'll fiddle with adding transactions in the coming days. Will report back. Happy easter!

**Comment by JC5** [comment]
I've been playing around with Postman. The JSON content at least is correct. Since the expand seems to work fine I'm not sure what the issue could be. All I can suggest is backup, upgrade, and try again.
