### ISSUE TITLE
Inactive Budgets still show up on V2 dashboard (and get reactivated?)

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4582]
**Bug description**
I am running Firefly III version 5.5.1 (layout v2), and my problem is:

If you have an inactive budget that had an auto-budget set to "Set a fixed amount every period" it still shows up on the v2 dashboard under monthly budgets or custom timed budgets. It looks like it's also been kind of reactivated? You can see it definitely didn't trigger in March (on 5.4.6) but it did trigger in April (on 5.5.1):
![image](https://user-images.githubusercontent.com/21091510/113440898-49210400-93bb-11eb-8b19-9c26a3e11ea1.png)
It definitely was and still is listed as inactive.

Also see that my perfectly set budget has gone over:
![image](https://user-images.githubusercontent.com/21091510/113441192-dbc1a300-93bb-11eb-9f5d-f32f661eebe0.png)

I don't think there's a way for me to test this on the demo site.

EDIT: If you can't replicate this immediately, I did set up 2 test inactive budgets on my site. One that sets a fixed amount every period and one that adds an amount every period. These are set to run daily, but they are inactive. I can let you know if they fire overnight in the morning but they do show up on the main page even when inactive.

On main page:
![image](https://user-images.githubusercontent.com/21091510/113465308-10a41900-9401-11eb-9089-f8e22154ea4b.png)

Definitely not active:
![image](https://user-images.githubusercontent.com/21091510/113465325-24e81600-9401-11eb-9b51-48369cea91fa.png)
![image](https://user-images.githubusercontent.com/21091510/113465330-33363200-9401-11eb-8b6a-4239b6cb60dd.png)

**Steps to reproduce**

1. Have a preexisting inactive budget that was set to refill monthly.
2. Be on layout v2? (for at least part of this)
3. Look at the budget section of the dashboard and see your inactive budget has money assigned to it.
4. Click on the budget name
5. Confirm that there is money assigned to it for the month
6. Go to your budget overview
7. See that extra money has been assigned to your budget.

Alternatively:
1. Make a new daily "set to a fixed amount every period" budget.
2. Edit the budget and make it inactive.
3. Go back to the dashboard and see that the inactive budget is listed in the custom timed budgets section.
4. [Still testing] Wait for your cron job to fire.
5. See that it has been created again, even though it is inactive.

**Extra info**

Debug information generated at 2021-04-02 14:01:30 America/New_York for Firefly III version **5.5.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.1 |
| Firefly III API | 1.5.0 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

Possibly related to #4570 or #4562

**Comment by JC5** [comment]
Thanks for letting me know. The code for the cron job is the same in 5.4.6 as it is in 5.5.1. Both ignore the fact that the budget may be inactive. This will be fixed in 5.5.2. 

The dashboard in 5.5.2 will skip over inactive budgets as well.

**Comment by JC5** [comment]
5.5.2 is released.
