### ISSUE TITLE
Rolling periods

### ISSUE THREAD

**Issue by GenericIdenticon** [firefly-iii/firefly-iii#4583]
**Description**
Firefly currently resets all charts, lists, budgets, categories, etc at the start of each period.
It would be nice to have an option that doesn't hard-reset every period, but instead shows all information from the last X days.

Having all history disappear from the dashboard each month/quarter/year is very disorienting, and the empty graph that the dashboard shows near the start of each month is a unappealing and wasteful.

**Solution**
Support for a rolling history timeframe, and a flag in settings that enables it.

**What are alternatives?**
None.

**Comment by JC5** [comment]
Feel free to use the "last 30 days" setting, but otherwise it's not going to change.
