### ISSUE TITLE
Unable to add money to Piggy Bank

### ISSUE THREAD

**Issue by gbengaadara** [firefly-iii/firefly-iii#4585]
First of all, let me say a big thank you for making this awesome app available for use absolutely free. I started using Firefly iii in January and since then I have been loving the insights it provides for my financial health.

Also apologies in advance if this is not the right place to ask this but I have not found any other forum with my search. I am running Firefly III version 5.4.6 and discovered recently that I cannot add any amount more than 0.50 to my piggy banks. I have tried creating a new piggy bank but still the same issue. All Piggy banks have left to save far more than $0.50

Is this a known bug with this version? Any advise on how this may be resolved?

Thanks in advance for any help / pointers

![image](https://user-images.githubusercontent.com/1833096/113471151-650ebf00-9428-11eb-9ab1-a120abfa9ce0.png)

**Comment by JC5** [comment]
I haven't seen this before. Is there enough money on the account to even add to the piggy banks?

**Comment by gbengaadara** [comment]
Alright, so your question prompted me to change my order of doing things. I was trying to adjust 2 piggy banks. Increase one by x amount and decrease the other by x amount. I was attempting the increase first. Once I decreased one bank, I was able to increase the other.

Thank you @JC5 once again
