### ISSUE TITLE
Allow customisation of upload and export storage directories 

### ISSUE THREAD

**Issue by savyajha** [firefly-iii/firefly-iii#4587]
**Description**

Every time I upgrade firefly, I have to shift `storage/{upload,export}` to the new location along with `.env`. If possible, I wish to stop doing this.

**Solution**

Put in environment variables such as `UPLOAD_PATH` and `EXPORT_PATH` in `.env` which are then sourced by `config/filesystems.php`. Something of the sort:

```
'upload'   => [
            'driver' => 'local',
            'root' => env('UPLOAD_PATH', storage_path('upload')),
        ],
```
Where `UPLOAD_PATH` is an absolute path.

**What are alternatives?**

None

**Additional context**

N/A

**Bonus points**

Sorry I'm too untalented and poor for either at the moment. :P

**Comment by JC5** [comment]
Why not use a symlink?

**Comment by savyajha** [comment]
It'll have to be recreated at every upgrade. I mean, I _can_ do that, don't get me wrong, but if I can persuade you to add an option in the `.env` file that would just be much cleaner. :)

**Comment by JC5** [comment]
Nope, sorry.

**Comment by savyajha** [comment]
No worries. Thanks for taking the time to reply.
