### ISSUE TITLE
Various v2 Layout problems

### ISSUE THREAD

**Issue by gthbusrr** [firefly-iii/firefly-iii#4588]
**Bug description**
I am running Firefly III version 5.5.2, and my problem is:

1. On the dashboard page, "categories" card included transactions from 31 March 2021 while the range was set to 01 April - 30 April
2. On the dashboard page, there are some empty accounts with balance "not a number (NaN) <img width="1017" alt="Screenshot 2021-04-03 at 23 03 55" src="https://user-images.githubusercontent.com/77537216/113482325-d2087000-948d-11eb-9f7c-9b2c8b86d24c.png">
3. While creating a split transaction, I wasn't allowed to select destination accounts for each transaction.
<img width="2989" alt="Screenshot 2021-04-03 at 19 04 18" src="https://user-images.githubusercontent.com/77537216/113482380-0ed46700-948e-11eb-8004-a031b4c500d8.png">
4. The timezone was in UTC for creating transactions, others is in my local timezone.
5. Question: I'm moving, will the changing of timezone be possible? I am on docker.
**Steps to reproduce**

**Extra info**

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by gthbusrr** [comment]
Thanks for your answer!

3. It's a withdraw, not a transfer... :(
Just a quick suggestion: 
Is it possible to add a timezone option in preference? So that all data in db shall be saved in UTC while showing the results to user in their timezone (-> tz($timezone))? Proposed step:- First allow user to set timezone in preference, then provide an option, like a button, for them to migrate all timestamps in db from their preset timezone to UTC.

Sorry for my poor english... I don't know laravel 8 (I use laravel 5.5 at work) so please forgive me for not contributing.

**Comment by JC5** [comment]
I'll check, thanks for letting me know!

**Comment by JC5** [comment]
In the next release, the accounts should work again. Changing the timezone won't be possible.

**Comment by gthbusrr** [comment]
The category calculation problem persists... :(

<img width="2979" alt="Screenshot 2021-04-04 at 12 07 32" src="https://user-images.githubusercontent.com/77537216/113498329-7ecd0680-94fb-11eb-95d7-3bf850be3047.png">
<img width="1250" alt="Screenshot 2021-04-04 at 12 07 57" src="https://user-images.githubusercontent.com/77537216/113498331-7ffe3380-94fb-11eb-87a6-2cc280cb1b31.png">

Also, it would be great if disabling an account will automatically remove it from home screen :) Thanks!!!

**Comment by JC5** [comment]
> Also, it would be great if disabling an account will automatically remove it from home screen :) Thanks!!!

Should already be the case, I'll check it out.

**Comment by JC5** [comment]
> The category calculation problem persists... :(

Can't replicate this. Set your time period again to verify.

**Comment by gthbusrr** [comment]
> > The category calculation problem persists... :(
> 
> Can't replicate this. Set your time period again to verify.

Dear Sir, I did tried, it still didn't work. And I just realised that the amount on the bar was correct while the (length?) of the bar isn't. Thanks
