### ISSUE TITLE
Cannot edit Source or Destination Accounts on transactions in Layout V2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4589]
**Bug description**
I am running Firefly III version 5.5.2 (v2), and my problem is:

If I go to edit a transaction and change either the source or the destination account, this change will not be reflected once you've hit save. Any other information you have entered will be saved though.

This only happens in Layout V2, so it does not happen on the demo site.

**Steps to reproduce**

1. Have a preexisting transaction
2. Edit the source or destination account on the transaction
3. Hit save
4. Click the link at the top of the page to open the transaction
5. See that the account has not changed.

**Extra info**

Debug information generated at 2021-04-03 12:39:36 America/New_York for Firefly III version **5.5.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.2 |
| Firefly III API | 1.5.1 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-03-01 00:00:00 |
| Session end | 2021-03-31 00:00:00 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by gthbusrr** [comment]
The category calculation problem persists... :(

<img width="2979" alt="Screenshot 2021-04-04 at 12 07 32" src="https://user-images.githubusercontent.com/77537216/113498329-7ecd0680-94fb-11eb-95d7-3bf850be3047.png">
<img width="1250" alt="Screenshot 2021-04-04 at 12 07 57" src="https://user-images.githubusercontent.com/77537216/113498331-7ffe3380-94fb-11eb-87a6-2cc280cb1b31.png">

Also, it would be great if disabling an account will automatically remove it from home screen :) Thanks!!!

**Comment by JC5** [comment]
Fixed in the next release :+1:
