### ISSUE TITLE
Recurring transaction : end of repeat

### ISSUE THREAD

**Issue by M-Paladin** [firefly-iii/firefly-iii#4593]
**Bug description**
I am running Firefly III version 5.5.3, and my problem is:
When I edit or create a recurring transaction whatever the layout version, the "end of repeat" is not saved
I choose for example a number of time to repeat
![image](https://user-images.githubusercontent.com/49365410/113503926-3c282000-9535-11eb-80f9-31298921aba7.png)

After saving, it's not saved in fact
![image](https://user-images.githubusercontent.com/49365410/113503933-4e09c300-9535-11eb-95e9-6bae954c5c9a.png)
even in database
![image](https://user-images.githubusercontent.com/49365410/113504097-2109e000-9536-11eb-98dc-92b03432f6ad.png)

It's the same problem if I choose an "end date" instead of "number of time"

**Steps to reproduce**

Create or edit a recurring transaction
Choose an "end of repeat" different from forever
Save
View in the list / edit again
Info has disappeared

**Extra info**

Debug information generated at 2021-04-04 11:12:34 Europe/Paris for Firefly III version **5.5.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.3 |
| Firefly III API | 1.5.1 |
| PHP | 7.4.15 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 049cfdc3-2852-4694-8580-cb86fa4bc87d |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | fr_FR |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2012-01-01 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0 |

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by M-Paladin** [comment]
Furthermore, if I manually set a value in the database for the field "repetitions", it appears in firefly.
If in Firefly I try ta change the value, after saving it is set to 0.

And for the date, if I manually set a date in the database for the field "repeat_until", it doesn't appear in firefly.
But when I edit the recurring transaction, repeat choice in selected but without the end date
![image](https://user-images.githubusercontent.com/49365410/113504547-2583c800-9539-11eb-9285-ae95631609ee.png)

**Comment by JC5** [comment]
Nicely spotted. It should be fixed in the next release :+1:

**Comment by M-Paladin** [comment]
Another thing that is strange if I set a date in repeat_until in database, here's what's happening
![image](https://user-images.githubusercontent.com/49365410/113582973-54796700-9629-11eb-8971-5531b0e48274.png)
It says "stopped to repeat in 2028" but it hasn't occurred yet !

**Comment by M-Paladin** [comment]
@JC5 
I have tested your commit
https://github.com/firefly-iii/firefly-iii/commit/d3502c56d3d4154a4f6e3e957c7fdc36aa1098ce

And now I have other problems that appeared
I can edit a recurring transaction with a "repeat until" date and it seems ok
But I can't edit a recurring transaction with "repeat forever" or "repeat a number of times"
If I try, I have an error 500 server error

In database, if I set "repeat_until" to a date, I can then edit the recurring transaction in firefly
Then, in the recurring screen,if I change to "repeat forever", I save, nothing is saved. Neither on screen nor in database.
Else, in the recurring screen, if I change to "repeat a number of times", I set a number, I save, it is saved. But once again, I can't edit because of error 500. In database, change is done.

**Comment by JC5** [comment]
> Another thing that is strange if I set a date in repeat_until in database, here's what's happening

I can't replicate this when setting the date through the UI.

>  But I can't edit a recurring transaction with "repeat forever" or "repeat a number of times"

I can't replicate this either. What is the 500 error?

**Comment by M-Paladin** [comment]
For the message "stop repeating", this is strange because my server has a good date so I don't know 
![image](https://user-images.githubusercontent.com/49365410/113829485-d8486600-9785-11eb-9051-0e8b3b027bd1.png)
What is compared to show this warning message ?
I can't reproduce it on demo so I wonder what is wrong.
What can I test or change ?

This is error 500 when I clic on modify recurring transaction
![image](https://user-images.githubusercontent.com/49365410/113828368-9834b380-9784-11eb-9ccf-54ddea8b1b53.png)
Maybe I should go back to initial 5.5.3 version and wait for a real release without recurring transaction working well for the moment

**Comment by JC5** [comment]
Get the error from the logs please.

**Comment by M-Paladin** [comment]
substr() expects parameter 1 to be string, null given
 in /var/www/html/firefly-iii/app/Http/Controllers/Recurring/EditController.php (line 144) 
  $array['repeat_until']            = substr($array['repeat_until'], 0, 10);
[ff3-fpm-fcgi-2021-04-07.log](https://github.com/firefly-iii/firefly-iii/files/6270326/ff3-fpm-fcgi-2021-04-07.log)

Oh my bad, I copied the line above and edited it but missed the "(string)" in the command
After changing it correctly, it works as expected.
Sorry about that.

**Comment by JC5** [comment]
No problem, glad to hear that fixes it!

**Comment by M-Paladin** [comment]
> 
> 
> Another thing that is strange if I set a date in repeat_until in database, here's what's happening
> ![image](https://user-images.githubusercontent.com/49365410/113582973-54796700-9629-11eb-8971-5531b0e48274.png)
> It says "stopped to repeat in 2028" but it hasn't occurred yet !

only this problem persists. Any clue to investigate ?

**Comment by M-Paladin** [comment]
Nice works perfectly.
Thanks.

I notice one thing.
In the main recurring screen, if a number of repetition is chosen, it appears on lines concerned ("repeat X times") but if an "end date" is chosen it doesn't appear so it's not possible to distinguish "forever recurring transaction" from "recurring transaction with end date"
