### ISSUE TITLE
Error mailer shouldn't send an email for NotFoundHttpException errors.

### ISSUE THREAD

**Issue by ruifung** [firefly-iii/firefly-iii#4596]
**Bug description**
I am running Firefly III version 5.5.3, and my problem is:

The error mailer sends a email whenever an invalid URL is accessed... be it due to API changes, or just accessing an invalid URL in the browser. It really shouldn't send emails for NotFoundHttpException... or probably any 4xx range HTTP status error really.

It's quite funny how it's sending an email for whats basically the built in route handling code for laravel.

![image](https://user-images.githubusercontent.com/1073945/113509723-bc787080-9589-11eb-8fd3-5aa99480466c.png)

**Steps to reproduce**
Access an invalid URL path in firefly.

**Extra info**
Not relevant

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.

**Comment by JC5** [comment]
Yep. I’m getting bombarded too on the demo site. Next release this will be fixed.

**Comment by ruifung** [comment]
Oof. That must be a _lot_ worse lol. Given that the demo site is... _public_.

**Comment by JC5** [comment]
Uhuh. But a fix is in the develop branch and it will ignore 404's.
