### ISSUE TITLE
Recurring transaction : notes

### ISSUE THREAD

**Issue by M-Paladin** [firefly-iii/firefly-iii#4597]
**Bug description**
I am running Firefly III version 5.5.3, and my problem is:

When I update a recurring transaction using API, I can update the field "notes" as indicated in the API Doc Schema
https://api-docs.firefly-iii.org/#/recurrences/updateRecurrence

After that If I want to change this note in Firefly recurring transaction screen it's impossible because there's no area to change it
![image](https://user-images.githubusercontent.com/49365410/113520535-07978100-9594-11eb-9139-de9e56bf3dc1.png)

But I know my update via API worked because in Database, table notes, my note is present
![image](https://user-images.githubusercontent.com/49365410/113520582-4fb6a380-9594-11eb-85d8-ddef8cb7edee.png)

Maybe same problem when creating a recurring transaction via API

**Steps to reproduce**

Update an existing transaction via API, field notes

**Extra info**

Debug information generated at 2021-04-04 22:26:26 Europe/Paris for Firefly III version **5.5.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.3 |
| Firefly III API | 1.5.1 |
| PHP | 7.4.15 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 049cfdc3-2852-4694-8580-cb86fa4bc87d |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | fr_FR |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2012-01-01 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0 |

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.

**Comment by JC5** [comment]
Thanks for letting me know. The current layout won't be updated any more. I'm working on the v2 layout. This won't be fixed.

**Comment by M-Paladin** [comment]
For the moment, I imagine the recurring transaction screen is not in v2 yet
Is it possible to indicate in the release changelog which screen evolved to v2 layout ?
