### ISSUE TITLE
Content-based deduplication with limited parameters for csv-importer

### ISSUE THREAD

**Issue by Syphdias** [firefly-iii/firefly-iii#4606]
**Description**
I have transactions from two accounts (_Asset_ + _Savings_). I exported it from Banking4 and it's about 5 years of transactions I'd rather not go through by hand. There are transfers between them. After creating both asset accounts with their respective IBANs and importing the _Asset_ account transactions via csv importer, I see transfers between them. Example:
* _Asset_: -100  (to _Savings_)
* _Savings_: +100 (from _Asset_)

Now I import the transactions from _Savings_ but it does not get deduplicated which leads to every transfer doubling. My first thought was, that the content-based deduplication didn't work for reverse direction. This doesn't seem to be the case because these imports work without duplication:
```
❯ tail -n +1 test1.csv test2.csv test.json
==> test1.csv <==
Date,Acc,rAcc,Amount
2021-04-05,685,686,100

==> test2.csv <==
Date,Acc,rAcc,Amount
2021-04-05,686,685,-100

==> test.json <==
{
    "date": "Y-m-d",
    "default_account": 468,
    "delimiter": "comma",
    "headers": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "specifics": [],
    "roles": [
        "date_transaction",
        "account-id",
        "opposing-id",
        "amount"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "duplicate_detection_method": "classic",
    "ignore_duplicate_lines": true,
    "ignore_duplicate_transactions": true,
    "unique_column_index": 0,
    "unique_column_type": "internal_reference",
    "version": 2
}
```

My conclusion: "content-based" means all (not ignored) fields are the same. Since the fields of the transfers are different for tags (maybe more) I assume this is the reason for no deduplication.

**Solution**
Deduplication only with selected values, e.g. the essentials like: Account, remoteAccount, Date, Amount

**What are alternatives?**
* I guess removing extra content would work but that would mean I am loosing details in the migration
* Removing duplicates by hand

**Additional context**
They don't have a common id I could use to deduplicate – for Banking4 it is just two very separate accounts.
Not importing _Savings_ is not an option because there are other transactions that are not just transfers the _Asset_ account

**Bonus points**
![image](https://user-images.githubusercontent.com/16988672/113613358-6a9b1d80-9651-11eb-842d-0b96e15af243.png)
(Have some love and money – it was not supposed to look angry/evil...)

**Comment by JC5** [comment]
> My conclusion: "content-based" means all (not ignored) fields are the same. Since the fields of the transfers are different for tags (maybe more) I assume this is the reason for no deduplication.

Yes.

>  Deduplication only with selected values, e.g. the essentials like: Account, remoteAccount, Date, Amount

No. It's all or nothing, and this will not be changed. Love the drawing though. :D

**Comment by Syphdias** [comment]
> > Deduplication only with selected values, e.g. the essentials like: Account, remoteAccount, Date, Amount
> 
> No. It's all or nothing, and this will not be changed. Love the drawing though. :D

I am aware that the example I provided is not a good default. I suppose this is also a no to an additional deduplication strategy "partial content-based"?

**Comment by JC5** [comment]
No. Don't think you're the first one to ask and please don't think I'm dismissing this out of hand. But it's a nightmare, it really is.

"Partial content-based" means all kinds of if/then/but/when/maybe statements to counter each possible combination the user may throw at the software. Do include X, but don't include Y. Include A only when B is there or not or maybe when I feel like it?

It also means that the CSV importer must have intimite knowledge (become stateful) about the entire CSV file. Not just the current row but also previous rows, future rows, all the exceptions. Because including or excluding content must also work when fields may be empty or may not be? Who knows?

The one solution I recommend for partial matching is a manual action where *you* generate the SHA2 hash for each row, based only on the content you wish to include. In pseudo-code: SHA2(source, destination, amount, date) = X. X is a hash that you use to do "identifier based deduplication".

**Comment by Syphdias** [comment]
> No. Don't think you're the first one to ask and please don't think I'm dismissing this out of hand. But it's a nightmare, it really is.

In my experience, issues are rarely dismissed out of hand. There is always a reason. So, no, I didn't think that. I was just not sure if it was a misunderstanding or a dismissal. 😜

> The one solution I recommend for partial matching is a manual action where _you_ generate the SHA2 hash for each row, based only on the content you wish to include. In pseudo-code: SHA2(source, destination, amount, date) = X. X is a hash that you use to do "identifier based deduplication".

Probably what I will do. I will need to keep in mind to normalize it to positive amounts in order to catch the reverse action.

Thanks for taking the time to explain, even if you did it already somewhere else and I missed it :smile:.
