### ISSUE TITLE
Rules that Set Source Account don't seem to work

### ISSUE THREAD

**Issue by quornian** [firefly-iii/firefly-iii#4607]
**Bug description**
I am running Firefly III version 5.5.3, and my problem is:

Any rule that sets the source account doesn't appear to do so.

**Steps to reproduce**

- Make a rule that sets the source account of one or more transactions
- Run it manually

I made a transaction on the demo site here (it should have "(cash)" as the source account currently):

https://demo.firefly-iii.org/transactions/show/443

This should be found by this rule:

https://demo.firefly-iii.org/rules/search/5

Executing that rule should set the source to "JobGiver Inc." but fails to do so (the above search shows "(cash)" still):

https://demo.firefly-iii.org/rules/select/5

**Extra info**

I think I found the cause, though my PHP is rusty.

This line appears to take the current `$journal` and replace it with a new object that doesn't have a "transaction_journal_id" of its own:

https://github.com/firefly-iii/firefly-iii/blob/5.5.3/app/TransactionRules/Actions/SetSourceAccount.php#L61

The returned object has "id" instead, so one option seems to be to use that in place of "transaction_journal_id" in the rest of the code, but this object is only used once, so another solution could be this:

```diff
diff --git a/app/TransactionRules/Actions/SetSourceAccount.php b/app/TransactionRules/Actions/SetSourceAccount.php
index c8711b4e1..a4fc2c8b0 100644
--- a/app/TransactionRules/Actions/SetSourceAccount.php
+++ b/app/TransactionRules/Actions/SetSourceAccount.php
@@ -57,8 +57,6 @@ class SetSourceAccount implements ActionInterface
     {
         $user = User::find($journal['user_id']);
         $type = $journal['transaction_type_type'];
-        /** @var TransactionJournal $journal */
-        $journal = TransactionJournal::find((int)$journal['transaction_journal_id']);
         /** @var AccountRepositoryInterface repository */
         $this->repository = app(AccountRepositoryInterface::class);
         $this->repository->setUser($user);
@@ -78,7 +76,10 @@ class SetSourceAccount implements ActionInterface
         // new source account must be different from the current destination:
         $destinationId = (int)$journal['destination_account_id'];
         /** @var Transaction $source */
-        $source = $journal->transactions()->where('amount', '>', 0)->first();
+        $source = TransactionJournal::find((int)$journal['transaction_journal_id'])
+          ->transactions()
+          ->where('amount', '>', 0)
+          ->first();
         if (null !== $source) {
             $destinationId = $source->account ? (int)$source->account->id : $destinationId;
         }
```

I've put that in place on my server now and it seems to do the trick.

**Bonus points**

- I searched and nobody reported this bug before: YES
- I have added a stack trace from my log files: NO ... but a possible patch.
- I have added a screenshot: NO
- I was able to replicate it on the demo site: YES

**Comment by JC5** [comment]
Nice work. I'll do some digging. I remember something similar from the "set destination account" routine. Stay tuned.

**Comment by JC5** [comment]
I pushed some fixes. If you switch to `develop` you can test them :+1:

**Comment by quornian** [comment]
Thanks for the quick fix!

I didn't switch the branch but I did copy the change to that file (since it looked to be independent) and that works well.

I did wonder if that
```
$source = $journal->transactions()->where('amount', '>', 0)->first();
```
was meant to be a
```
$destination = $object->transactions()->where('amount', '>', 0)->first();
```
so it's nice to see that in there too. I'm starting to wrap my head around it all a bit more looking at your fix.

Thanks again!
Ian
