### ISSUE TITLE
Automatic blank time field for new transactions to avoid manual intervention

### ISSUE THREAD

**Issue by steakhutzeee** [firefly-iii/firefly-iii#4608]
**Description**

Hi, with v1 i was used to just select the date for new transactions. With v2 i see the current time is automatically set when creating a new transaction. This is a little "strange", at least for me, because i add transactions at the end of the day usually and usually i do not remember/do not need the specific time for the transactions.

Basically i think that it's ok to use the actual time but only if the user is adding the transaction soon after the transaction is made in real life. Otherwise the user have to manually edit the time field every time anyway.

So actually i'm blanking the time to 00:00:00 manually for every new transactions.

**Solution**

Maybe could be useful to add some kind of checkbox to select the current time/real transaction time if user wants it, otherwise the time will be empty, like it was on v1.

**Comment by JC5** [comment]
I agree. People asked for the time field so I oblidged, but so far I only find it annoying. I'll think of something.

**Comment by JC5** [comment]
New layout is a bit more friendly in this regard.

**Comment by steakhutzeee** [comment]
> 
> 
> New layout is a bit more friendly in this regard.

Wonderful! Thanks!!
