### ISSUE TITLE
Entering transactions is less satisfying in V2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4609]
**Description**

In V1 going through transactions just using the keyboard was great! You could hit enter in most of the boxes and complete the transaction. That was great because you could pick a category, hit enter, and be done.

Now in V2 if you key down into the transaction list, you're stuck in there. You have to TAB out and back in to reset it or use the mouse to go back to the box. Or, just now in testing I guess you can also hit ESC, so that's probably fine. More upsetting, in order to complete the transaction, you have to hit enter on or click on the "Store transaction" button. That is:

- 4 tabs from tags
- 6 tabs from category
- 13 from the end of the date field (no category)
- 19 tabs from the last mandatory box (amount)

And that's on top of the tabs I have to hit to move between the top boxes I'm filling in.

Entering transactions with a keyboard used to just feel so satisfying. Now it's a whole lot of hitting the tab button.

**Solution**

Restore the functionality of the Enter button!

**What are alternatives?**

Make users adapt to using the mouse or hitting the tab button an awful lot. :cry:

**Comment by JC5** [comment]
I concur. The secret is that the form isn't even a form, which is why it doesn't work.

I have some more tricks up my sleeve I'll try to implement over the next few weeks. Thanks for sharing this :+1:

**Comment by JC5** [comment]
Put in some changes. Let me know if it works for you. :+1:
