### ISSUE TITLE
Broken Links in CSV Importer Docs

### ISSUE THREAD

**Issue by 1enn0** [firefly-iii/firefly-iii#4610]
**Bug description**
I am trying to get the CSV importer running using Docker. I followed the [Installing and running > Docker](https://docs.firefly-iii.org/csv/install/docker/) page and noticed that all links to the referenced `.sh` files are broken:
* https://raw.githubusercontent.com/firefly-iii/csv-importer-docker/main/run-hosted.sh
* https://raw.githubusercontent.com/firefly-iii/csv-importer-docker/main/run-client-id.sh
* https://raw.githubusercontent.com/firefly-iii/csv-importer-docker/main/run-empty.sh
* https://github.com/firefly-iii/csv-importer-docker/blob/main/run-inline.sh

Have these been moved to a different location (given that the `firefly-iii/csv-importer-docker` repo does not exist)?

Anyway, thanks for your awesome work on Firefly III! :+1:

**Comment by JC5** [comment]
Oh nice find. I'll fix the links :+1:

**Comment by JC5** [comment]
It'll be a while for the cache to pick up the changes, but the scripts can be found here:

- https://docs.firefly-iii.org/csv/install/scripts/run-hosted.sh.txt
- https://docs.firefly-iii.org/csv/install/scripts/run-client-id.sh.txt
- https://docs.firefly-iii.org/csv/install/scripts/run-empty.sh.txt
- https://docs.firefly-iii.org/csv/install/scripts/run-inline.sh.txt

**Comment by 1enn0** [comment]
Didn't ever think about scanning the `docs` repo for the files but makes perfect sense to have them there :) Thanks for the super quick fix!
