### ISSUE TITLE
Not all categories show up in the category box on v2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4611]
**Bug description**
I am running Firefly III version 5.5.3 v2, and my problem is:

I have a certain category that does not seem to show up in the categories box on the v2 dashboard. The category does not show up in any month I check. It does show up on the v1 dashboard.

The expense accounts associated with the category do show up in the expense accounts box.

**Steps to reproduce**

1. Be in  V2 dashboard
2. Have transactions in a period with different categories
3. See if one of those categories doesn't show up I guess?

**Extra info**

Debug information generated at 2021-04-06 08:39:18 America/New_York for Firefly III version **5.5.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.3 |
| Firefly III API | 1.5.1 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.98 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

Side note: Are we going to get a v2 testing site at some point? I would rather not take screenshots on my personal site.

**Comment by JC5** [comment]
I guess you have more than one page of categories? That would probably be the culprit, codewise.

And a test site, duly noted!

**Comment by death2cupbots** [comment]
Oh bingo! Anything on the second page was not showing up. And when I up my page limit to 100, everything does in fact show up.

**Comment by JC5** [comment]
Was already fixed in 5.5.7
