### ISSUE TITLE
[5.5.3] HTTP 500 error when using ldap authentication - user provider [ldap] is not defined.

### ISSUE THREAD

**Issue by hst-tutorials** [firefly-iii/firefly-iii#4612]
**Bug description**
I am running Firefly III version 5.5.3, and my problem is:
When using the ldap authentication provider, I get an HTTP 500 error. This issue was already reported in #4557 and should be fixed in version 5.5.3 (atleast in the docker image) but does not seem to work on a self hosted instance of Firefly III.

**Steps to reproduce**

1. Set the LOGIN_PROVIDER variable in the .env file to "ldap"
2. Access Firefly III with your browser
3. You get an HTTP 500 error

**Extra info**

Error message with debug mode enabled, including the stacktrace:
`InvalidArgumentException thrown with message "Authentication user provider [ldap] is not defined."`

```
Stacktrace:
#7 InvalidArgumentException in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php:42
#6 Illuminate\Auth\AuthManager:createUserProvider in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:123
#5 Illuminate\Auth\AuthManager:createSessionDriver in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:94
#4 Illuminate\Auth\AuthManager:resolve in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:68
#3 Illuminate\Auth\AuthManager:guard in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:332
#2 Illuminate\Auth\AuthManager:__call in /var/www/firefly-iii/app/Exceptions/Handler.php:143
#1 FireflyIII\Exceptions\Handler:report in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:88
#0 Illuminate\Foundation\Bootstrap\HandleExceptions:handleException in [internal]:0
```

If further information or log-files are required, please let me know

**Comment by JC5** [comment]
```
composer require adldap2/adldap2-laravel --no-install --no-scripts --no-plugins --no-progress
composer install --no-dev --no-scripts --no-plugins --no-progress
composer dump-autoload
```

The requirements are optional since just a few people use them. I'll update the docs!

**Comment by hst-tutorials** [comment]
Works like a charm, thank you very much. :)
