### ISSUE TITLE
Cannot View Inactive Accounts on V2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4614]
**Bug description**
I am running Firefly III version 5.5.3 (v2), and my problem is:

I cannot access the list of inactive accounts. There is no link at the bottom of the page and if I try to go to [mydomain]/inactive-accounts/asset it brings me to a page has the heading "Asset Accounts (inactive) but still shows the list of active accounts:
![image](https://user-images.githubusercontent.com/21091510/113802513-dbf9cf80-9728-11eb-8631-ea4c8c3782c5.png)

You can still access the individual inactive accounts though other means. Just not the list. I obviously understand you are probably still working on a good design for the access to this list, but it's just weird that you can't even pull it up with the URL.

**Steps to reproduce**

1. Be on V2
2. Have or make an inactive asset account (any account type should be the same though)
3. Go to your asset accounts list
4. see that there is no link to the inactive accounts
5. Enter the URL [your domain]/inactive-accounts/asset
6. See that you are still be presented with the active accounts list.

**Extra info**

Debug information generated at 2021-04-06 22:42:31 America/New_York for Firefly III version **5.5.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.3 |
| Firefly III API | 1.5.1 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-03-01 00:00:00 |
| Session end | 2021-03-31 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.98 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
It's now in the sidebar under the dragon button.

**Comment by death2cupbots** [comment]
OK I am seeing that now. Thanks!

**Comment by M-Paladin** [comment]
For the moment, when you choose to show both, there's no way to distinguish active ones from inactive ones
