### ISSUE TITLE
Securing apache installation

### ISSUE THREAD

**Issue by zynexiz** [firefly-iii/firefly-iii#4616]
I just did some tests on the instance using apache web server, and run it thru Mozilla Observatory. I got a score of 20, which is pretty bad (rated F). I tinkered a bit with .htaccess file in /public, and finally got a score of 105 (A+). To secure your installations you should modify .htaccess file in /public folder and add the following to it (code mainly from NextCloud .htaccess file with some additions). It don't seem to brake anything :)
```
<IfModule mod_headers.c>
  <IfModule mod_setenvif.c>
    <IfModule mod_fcgid.c>
       SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
       RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
    </IfModule>
    <IfModule mod_proxy_fcgi.c>
       SetEnvIfNoCase Authorization "(.+)" HTTP_AUTHORIZATION=$1
    </IfModule>
  </IfModule>

  <IfModule mod_env.c>
    # Add security and privacy related headers
    # Avoid doubled headers by unsetting headers in "onsuccess" table, then add headers to "always" table

    Header onsuccess unset Referrer-Policy
    Header always set Referrer-Policy "no-referrer"

    Header onsuccess unset X-Content-Type-Options
    Header always set X-Content-Type-Options "nosniff"

    Header onsuccess unset X-Download-Options
    Header always set X-Download-Options "noopen"

    Header onsuccess unset X-Frame-Options
    Header always set X-Frame-Options "deny"

    Header onsuccess unset X-Permitted-Cross-Domain-Policies
    Header always set X-Permitted-Cross-Domain-Policies "none"

    Header onsuccess unset X-Robots-Tag
    Header always set X-Robots-Tag "none"

    Header onsuccess unset X-XSS-Protection
    Header always set X-XSS-Protection "1; mode=block"

    Header onsuccess unset Set-Cookie
    Header always edit Set-Cookie (.*) "$1; HTTPOnly; Secure"

    SetEnv modHeadersAvailable true
  </IfModule>

  # Add cache control for static resources
  <FilesMatch "\.(css|js|svg|gif|woff2)$">
    Header set Cache-Control "max-age=592200"
  </FilesMatch>
</IfModule>
```

Think this should also be applied as standard from the start to make the installation more secure.

**Comment by JC5** [comment]
Good suggestions!

I'll go around and play with the `develop` branch and see what happens!

Do you know how these headers respond when you're behind a reverse proxy?

**Comment by zynexiz** [comment]
Not sure, don't use a reverse proxy for it. Although these lines can also be implemented inside the apache configuration for the virtual host. By implementing them inside the .htaccess there security is distributed with the installation itself and is not dependent of the knowledge of the user to secure the apache configuration itself.

**Comment by JC5** [comment]
It's now part of the base image :+1:

**Comment by zynexiz** [comment]
Sweet, you can test it with Mozilla Observatory to check the result :)

**Comment by zynexiz** [comment]
Btw, I think you can remove the authorization part at the top (if not done already), missed that it was already included in .htaccess.
