### ISSUE TITLE
Failed to upgrade to v5.5.3

### ISSUE THREAD

**Issue by zynexiz** [firefly-iii/firefly-iii#4619]
I am running Firefly III version 5.5.1, which working without issues (except known bugs) and was just trying to upgrade it to v5.5.3 as described in the documentation. Everything seems ok while going thru the upgrade process, but I just get served a very white blank page. Reverting back to v5.5.1 makes it run smooth again. Running stand alone version (LAMP).

If I try to run the web page using PHP directly (php -S 192.168.x.x:1234) is actually shows up and I can login, but not thru apache. All permissions is in order (user apache in my case), and the file permissions is the same as the old backup. Nothing is shown in the logs except "Database entry exists, upgrade to latest version (16)".

OS: CentOS 8 Stream
PHP Version: 7.4.16
Apache: Apache/2.4.37 (centos)

[EDIT] Found this in php logfiles thou...
```
[08-Apr-2021 12:34:57 Europe/Stockholm] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/firefly-iii/storage/framework/views/83e72ce95259313340af9c204361ba4ba6b8b543.php): failed to open stream: Permission denied in /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:185
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/f...', 185, Array)
#1 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(185): file_put_contents('/var/www/html/f...', '<?php $__env->s...', 0)
#2 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(160): Illuminate\Filesystem\Filesystem->put('/var/www/html/f...', '<?php $__env->s...')
#3 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(55): Illuminate\View\Compilers\BladeCompiler->compile('/var/www/html/f...')
#4 /var/www/html/firefly-iii/vendor/laravel/framework in /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 185
```

**Comment by JC5** [comment]
Search the documentation for "cache".

**Comment by zynexiz** [comment]
Think I have cleared the caches couple of times, and restarted Apache to. Think that's a part of the upgrade instructions.

**Comment by zynexiz** [comment]
Just tried to upgrade to v5.5.6, got the same problem. Followed the instructions [here](https://docs.firefly-iii.org/firefly-iii/installation/upgrade/) for section "Virtual or real server".

**Comment by zynexiz** [comment]
Finally! Found the issue, all the permissions and user was correct. But! I have selinux running, and when I temporarily disabled it, everything worked. Bit confused why it worked on the old version thou, but at least the main problem is found :)

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/faq/self_hosted/#i-run-selinux-and-i-dont-want-to-disable-it-now-what

😉

**Comment by zynexiz** [comment]
Yep, found that first time. Didn't think of it when I upgraded it (hence add a note to the upgrade instructions) :wink:
