### ISSUE TITLE
new expense accounts are missing the last character in v2 layout

### ISSUE THREAD

**Issue by 3ssen** [firefly-iii/firefly-iii#4620]
I'm using version 5.5.3.

When I make a new transaction to a new expense account the last character in the name is not stored in the v2 layout.

Schimmel Son Oost will become Schimmel Son Oos

Tested it on the old layout in the demo site and there it is working fine.

**Comment by JC5** [comment]
Nice find, I thought I fixed that 😅 . Stay tuned.
