### ISSUE TITLE
Pasting text into destination account does not create a new expense account in V2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4621]
**Bug description**
I am running Firefly III version 5.5.3 (v2), and my problem is:

If I go to create a new withdrawal and paste text into the destination account box, when I create the transaction, the expense account is listed as "(no name)"

This does not happen in v1

**Steps to reproduce**

1. Be in V2
2. Start creating a new transaction
3. Enter other details as normal, but paste text into the destination box.
4. Click "Store Transaction"
5. Look at the transaction details
6. See the destination is listed as (no name).

**Extra info**

Debug information generated at 2021-04-08 08:32:18 America/New_York for Firefly III version **5.5.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.3 |
| Firefly III API | 1.5.1 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.98 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Same root cause as https://github.com/firefly-iii/firefly-iii/issues/4620
