### ISSUE TITLE
Cannot see graphs on home page in 5.5.4

### ISSUE THREAD

**Issue by savyajha** [firefly-iii/firefly-iii#4622]
**Bug description**
I am running Firefly III version 5.5.4, and my problem is:

I cannot see the graphs in Layout v1 anymore.

<img width="1440" alt="Screenshot 2021-04-09 at 7 03 24 AM" src="https://user-images.githubusercontent.com/3996019/114116234-e7542300-9901-11eb-8d85-c65da576dab9.png">

Layout v2 is completely blank.

<img width="1440" alt="Screenshot 2021-04-09 at 7 05 58 AM" src="https://user-images.githubusercontent.com/3996019/114116298-0e125980-9902-11eb-989c-07d4914d1092.png">

**Steps to reproduce**
Upgrade to 5.5.4 and navigate to the home page.

**Extra info**

Firefly 5.5.4 running on a Debian testing server viewed on the latest Brave on macos.

Debug information generated at 2021-04-09 03:31:46 Europe/Berlin for Firefly III version **5.5.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.4 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.15 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 11790dd1-cebc-43a0-9035-8d916abdb9ac |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Berlin |
| Browser TZ | [BrowserTZ] |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, syslog |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | pgsql |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2020-03-26 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_IN |
| Attempt at "en_IN.utf8" | 'en_IN.utf8' |
| Attempt at "en_IN.UTF-8" | 'en_IN.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 |

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/ (Was not able to see Layout v2 in the demo site)

**Comment by death2cupbots** [comment]
I would like to add that nothing in the V2 dashboard is loading on 5.4.4 None of the menus open and the only links that work on the sidebar are the ones that go to V1 pages. Even if you try to go from the V1 section of the site back to a different page on V2 (like accounts or add a transaction) it brings you to the same blank page.

**Comment by JC5** [comment]
Can I get a screenshot of the console, please?

**Comment by JC5** [comment]
Never mind, I see it. Shouldn't have added an experimental CSP header. 5.5.5 is released!

Thanks for the quick ticket :+1:

**Comment by JC5** [comment]
OK not sure what happened there. On my local dev-server it works either way (in Chrome), but the demo site was broken. Something to look into.
