### ISSUE TITLE
Cannot Edit Transactions in V2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4623]
**Bug description**
I am running Firefly III version 5.5.6 (v2), and my problem is:

I cannot edit transactions in V2 in Brave. When I open a transaction and try to edit it, it brings me to a page that has the transactions heading, but the actual boxes with the transaction details do not appear. It does let me edit the transactions in Firefox.

**Steps to reproduce**

1. Be on version 5.5.6 and v2 on (probably) a chrome browser (but definitely brave)
2. Try to edit an existing transaction
3. See that the page does not load the elements.

**Extra info**

Debug information generated at 2021-04-09 01:10:18 America/New_York for Firefly III version **5.5.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.6 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.98 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Already noted down! :D 

https://github.com/firefly-iii/firefly-iii/issues/4618
