### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given | FireFly-III 5.5.6 

### ISSUE THREAD

**Issue by GaneshKandu** [firefly-iii/firefly-iii#4625]
**Bug description**

I am running Firefly III version 5.5.6 , and my problem is:

I am getting error mentioned in below image on MySQL 5.5 and MySQL 5.6

![2021-04-08](https://user-images.githubusercontent.com/12833130/114138761-ba1c6a80-992b-11eb-9418-74562c4bd877.png)

I am getting below error while install of FireFly-III 5.5.6 on MySQL 5.7

![image](https://user-images.githubusercontent.com/12833130/114139005-167f8a00-992c-11eb-8078-a9a79f94bd1b.png)

**Steps to reproduce**

Followed steps from [https://docs.firefly-iii.org/firefly-iii/installation/self_hosted/#main-command](https://docs.firefly-iii.org/firefly-iii/installation/self_hosted/#main-command)

Getting Error on ```Now you should be able to visit http://localhost/firefly-iii/ and see Firefly III.``` this while registering new user.

**Extra info**

|  | version| 
| -------- | -----  | 
| FireFox | 88.0b3 (64-bit) | 
| MySQL | 5.7.33 | 
| PHP | 7.4.15 | 
| PHP | Centos 6 ( Linux  3.10.0-1062.1.1.el7.x86_64\#1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |  

**Logs**

[ff3-audit-2021-04-09.log](https://github.com/firefly-iii/firefly-iii/files/6283708/ff3-audit-2021-04-09.log)
[ff3-cli-2021-04-09.log](https://github.com/firefly-iii/firefly-iii/files/6283709/ff3-cli-2021-04-09.log)
[ff3-apache2handler-2021-04-09.log](https://github.com/firefly-iii/firefly-iii/files/6283710/ff3-apache2handler-2021-04-09.log)

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
The MySQL error isn't something I can fix unfortunately. 

https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

But I will make sure that the nullpointer is fixed in the next release.

**Comment by 24788329** [comment]
I am also getting a similar error but with a slightly different message:

"array_key_exists(): Argument #2 ($array) must be of type array, null given"

Also with Firefly iii v5.5.6 setup via Docker. Container launches and I can connect but I see this error after creating a new user.

I'll try again with the next release.

**Comment by tmciver** [comment]
I too got the error that @24788329 got. I'm using Docker as well.

**Comment by olenchenko** [comment]
I had the same error with clean installation (FreeBSD 12.2, PostgreSQL12.6, PHP 7.4.16). I have changed line 145 in app/Support/Form/CurrencyForm.php to what it was before commit [38d0f0427f931b2184e0ed022383304808892786](https://github.com/firefly-iii/firefly-iii/commit/38d0f0427f931b2184e0ed022383304808892786) and I was able to log in and make initial configuration.

**Comment by JC5** [comment]
Thanks for letting me know. Do you also have the MySQL error?

**Comment by vlassakoudis** [comment]
Hello, I also have the same error as @24788329 on a new installation and when I create a first user. (Docker/ MySQL 8.0.23 / Firefly v5.5.6)

**Comment by tmciver** [comment]
@JC5 I did not have the MySQL error.

**Comment by 24788329** [comment]
> Thanks for letting me know. Do you also have the MySQL error?

I'm using the default docker-compose.yaml settings with MariaDB. I do not see the same SQLSTATE errors.

**Comment by Tarydium** [comment]
I'm having the same error: array_key_exists() expects parameter 2 to be array, null given
Ubuntu 20.02
MariaDB
Recently installed.

**Comment by JC5** [comment]
Thanks all. I hope to release 5.5.7 today which should fix this. I would be grateful if any of you can try Firefly III `develop` and see if the error happens there as well.

**Comment by 24788329** [comment]
Working now on 5.5.7.

The only change made was using `develop` in `docker-compose.yaml`. Firefly III now launches without the error. It's my first time giving it a try and I appreciate the responsive solution. Thanks

**Comment by earl761** [comment]
> 
> 
> Thanks all. I hope to release 5.5.7 today which should fix this. I would be grateful if any of you can try Firefly III `develop` and see if the error happens there as well.

I does thank you

**Comment by earl761** [comment]
> 
> 
> > Thanks all. I hope to release 5.5.7 today which should fix this. I would be grateful if any of you can try Firefly III `develop` and see if the error happens there as well.
> 
> I does thank you

it does thank you

**Comment by brainstorm** [comment]
@JC5 Can you push release 5.5.7 as a docker container in DockerHub, please?

**Comment by Tarydium** [comment]
Thank you for the quick response. when can we expect the update of the dev-main packagist package, to update via composer? and again, thank you!

**Comment by JC5** [comment]
Should already be there, it’s all automated. I don’t know how it works otherwise.

**Comment by Tarydium** [comment]
Well seems like it didnt update automatically the dev-main branch. i tested and the problem presists.
![cap](https://user-images.githubusercontent.com/6092823/114308195-4ae97680-9ae3-11eb-9e0f-1c239b0294d8.jpg)

**Comment by JC5** [comment]
Well that’s too bad then. I hope to release the next release soon.

**Comment by Tarydium** [comment]
No problem, i can wait. And thank you all again for the time and effort in this project.

**Comment by MDingas** [comment]
I too confirm that the develop release fixed this issue, and I also want to thank you for the commitment to the project!

**Comment by JC5** [comment]
5.5.7 is out, if anything breaks please open a new issue.

**Comment by GaneshKandu** [comment]
Working, Thanks @JC5  !
