### ISSUE TITLE
fa-paperclip in front of all transactions

### ISSUE THREAD

**Issue by MihataBG** [firefly-iii/firefly-iii#4628]
**Bug description**
I am running Firefly III version 5.5.6, and my problem is:
When check transaction list in front of all transactions has paperclip icon

**Steps to reproduce**
Go to Transactions -> Expenses

![image](https://user-images.githubusercontent.com/43669254/114187685-f1e9d900-9950-11eb-9361-a287b925d665.png)

**Comment by JC5** [comment]
Indeed! I guess I forgot how to count. I'll pick it up!
