### ISSUE TITLE
Some TLDs may not be accepted for registration 

### ISSUE THREAD

**Issue by ArthurMitchell42** [firefly-iii/firefly-iii#4629]
**Bug description**
I am running Firefly III version 5.5.3 and my problem is:

One first run I tried to register with an email address with the TLD .coffee
I got an error that the format of the address didn’t match RFQxxxx and from then on the web page returned an HTML Error 503

**Steps to reproduce**
On first run after installation try and register with an email address xxx@yyy.coffee

**Extra info**
Running a docker container on Synology DSM and accessing the web UI with the current Firefox 
The database is the native MariaDB10 app on DSM
It he app was dead, returning 503 until I shut it down and zapped the whole database. After that I reran the container which re-initialised the DB and I successfully registered with a .com email

**Comment by JC5** [comment]
I'm sorry, I was just able to register with xxx@yyy.coffee. I was even able to register myself using the [.invalid](https://en.wikipedia.org/wiki/.invalid) TLD.

I'll check what happens afer the error. Can you reproduce this, and show me some logs?

If it works now, please also share the output of the /debug page

**Comment by ArthurMitchell42** [comment]
Hi James, thanks for looking at this so quickly. As this was the first time I've brought a firefly system up there may have been some other factor like finger trouble. 
I created a new DB and container and re-tried this and it worked fine, I can't explain the first outcome.
Thanks,
Arthur

**Comment by JC5** [comment]
Weird! But glad to hear it works!
