### ISSUE TITLE
Comments on link transactions are not stored

### ISSUE THREAD

**Issue by DanielNetoP** [firefly-iii/firefly-iii#4632]
**Bug description**
I am running Firefly III version 5.5.3, and my problem is when creating a new transaction link with a comment, the comment is not saved anywhere, I've checked the `journal_links` table and the comment column is empty.

**Steps to reproduce**
Create a link transaction with a comment.

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for letting me know. I'm working on a new layout and I'll make sure it works in that.
