### ISSUE TITLE
csv import tag mapping

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#4634]
**Description**

I've noticed in the csv importer you have a role mapping for tag space and tag comma separated. However, the mapping option doesn't give you the choice to select the tag by id. Either this should allow you to map this or hide the map option.

**Comment by JC5** [comment]
Every field has a map option, it's not until the next screen you'll learn if it'll actually work. I'm not going to overcomplicate the CSV importer to fix that.

**Comment by lastlink** [comment]
It would just be nice if this was more intuitive.
