### ISSUE TITLE
Export cli command doesn't honour start date

### ISSUE THREAD

**Issue by urquilla** [firefly-iii/firefly-iii#4635]
**Description**
Exporting transactions via CLI won't honour received start or end dates.
For example, with:
`$ php artisan firefly-iii:export-data --start="2021-01-01" --end="2021-01-31" --export-transactions `

**Expected Result**
Only transactions from the date range are included in export.

**Actual Result**
All existing transactions are included. The start and end dates are ignored.

**Cause**
The problem appears to be in the `getDateParameter` function in file `Console/Commands/Export/ExportData.php`.

`getDateParameter` will initially parse the received dates as expected, but then it'll proceed to overwrite the results.

I suspect that condition in line 209 should be checking for` error === true `instead of false. Thus using the earliest date possible only as default when no valid date is present.
https://github.com/firefly-iii/firefly-iii/blob/26aad765ae66b38d37793c4562b75a0ba25c1dbe/app/Console/Commands/Export/ExportData.php#L209

Also, it may be the same for the 'end' date where under the current behaviour it'll always be set to EOD today.
https://github.com/firefly-iii/firefly-iii/blob/26aad765ae66b38d37793c4562b75a0ba25c1dbe/app/Console/Commands/Export/ExportData.php#L214

--
I can send a PR for this, just please let me know if my understanding is correct.

Thanks :)

**Comment by urquilla** [comment]
**Version info**

Firefly III version **5.5.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.6 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

**Comment by JC5** [comment]
Nice! I pushed a fix, also making sure the $end is always endofday.
