### ISSUE TITLE
Please Disable Browser Autofill on Transaction Fields

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4636]
**Description**

So on V2, if you have entered transactions into the form (at least in Brave (probably Chrome)), the browser will suggest those things for autofill (I think). This is particularly bad for asset accounts. If you pick (Bank X ($)) in the browser suggestions (not firefly iii suggestions), it won't get linked to an account and the form will fail.

**Solution**

Please disable the autofill suggestions, especially because your suggestion system works perfectly fine without it.

**What are alternatives?**

Users will have to constantly delete these suggestions to keep having an enjoyable experience.

**Additional context**

So I'm really not sure if this is happening on Firefox, because I only enter transactions in Brave.
![image](https://user-images.githubusercontent.com/21091510/114284810-80795b80-9a20-11eb-98af-8a6df41aaeaf.png)

**Bonus points**

**Comment by JC5** [comment]
Yep I saw it too. Very annoying.
