### ISSUE TITLE
HTTP 500 error 'Authentication user provider [ldap] is not defined', since docker version 5.5.0-beta.1

### ISSUE THREAD

**Issue by JacksonHub2** [firefly-iii/firefly-iii#4637]
**Bug description**
I am previous running Firefly with docker version 5.4.6, everything OK with LDAP. 

And by today I was trying to get the instance upgraded, but once it goes to version 5.5.6 (latest branch), it was the very likely the same issue as previous one [#4612](https://github.com/firefly-iii/firefly-iii/issues/4612) [#4557](https://github.com/firefly-iii/firefly-iii/issues/4557).

My stackstrace:

`InvalidArgumentException
InvalidArgumentException:
Authentication user provider [ldap] is not defined.

  at /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php:42
  at Illuminate\Auth\AuthManager->createUserProvider()
     (/var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:123)
  at Illuminate\Auth\AuthManager->createSessionDriver()
     (/var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:94)
  at Illuminate\Auth\AuthManager->resolve()
     (/var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:68)
  at Illuminate\Auth\AuthManager->guard()
     (/var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:332)
  at Illuminate\Auth\AuthManager->__call()
     (/var/www/html/app/Exceptions/Handler.php:150)
  at FireflyIII\Exceptions\Handler->report()
     (/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:88)
  at Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
 `

**Steps to reproduce**
After get several downgrade.. it seems, the issue coming here **since 5.5.0-beta.1**, the very next version after 5.4.6.

During the try-out, I haven't touch my LDAP settings, so it went to the application that might have problem.

**Comment by JC5** [comment]
Every Docker build after March 29 includes LDAP. This was the fix in #4557. Could you delete your local images and try again with 5.5.6?

I hope to release 5.5.7 later today so feel free to wait a bit.

**Comment by JacksonHub2** [comment]
Get all my firefly images deleted, pull the jc5x/firefly-iii:version-5.5.6 image then.
Issue still there, no sign of mitigating.. 
Would like keep waiting for new coming version to check whether fix.

**Comment by JC5** [comment]
Then I don’t know. The package is there.

**Comment by JacksonHub2** [comment]
Weird then, i think problem might exist in the coder differences between 5.4.6 and 5.5.0-beta.1..
Is there any info I might have offer to help you check?

**Comment by JC5** [comment]
Sorry, are you trying this with 5.4.6 or with a newer docker container?

**Comment by JacksonHub2** [comment]
I'm using 5.4.6, it's OK.
All newer version gets the same issue 'ldap is not defined'.

**Comment by JacksonHub2** [comment]
Also, get tested with the latest jc5x/firefly-iii:version-5.5.7, have the same issue:
![image](https://user-images.githubusercontent.com/71587680/114399902-012c8900-9bd4-11eb-81f9-4981b00f9602.png)

**Comment by JacksonHub2** [comment]
By the following I'm posting some docker log of the 5.4.6 version container, and also 5.5.7, hopes useful to check:

**5.5.7,** the not working one:

> Now in entrypoint.sh for Firefly III
Entrypoint script version is 1.0.13 (2021-02-11)
Running as 'root' in group 'root'.
Current working dir is '/var/www/html'
Now parsing _FILE variables.
done!
Touch DB file (if SQLite)...
Dump auto load...                                                                                                                                                   
  [Composer\Downloader\TransportException]                                                                                                         
  curl error 7 while downloading https://repo.packagist.org/packages.json: Failed to connect to repo.packagist.org port 443: Connection timed out  
                                                                                                                                                   require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
59 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 5254 classes
Discover packages...
Discovered Package: diglactic/laravel-breadcrumbs
Discovered Package: fideloper/proxy
Discovered Package: jc5/google2fa-laravel
Discovered Package: laravel/passport
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: rcrowe/twigbridge
Package manifest generated successfully.
Current working dir is '/var/www/html'
Wait for the database.
wait-for-it.sh: waiting 60 seconds for 127.0.0.1:5432
wait-for-it.sh: 127.0.0.1:5432 is available after 0 seconds
DB is up. Time to execute artisan commands.
Wait another 15 seconds in case the DB needs to boot.
Done waiting for the DB to boot.
Current working dir is '/var/www/html'
Run various artisan commands...
Running migration commands...
CreateDB does not apply to "pgsql", skipped.
Nothing to migrate.
Seeding: Database\Seeders\AccountTypeSeeder
Seeded:  Database\Seeders\AccountTypeSeeder (11.18ms)
Seeding: Database\Seeders\TransactionCurrencySeeder
Seeded:  Database\Seeders\TransactionCurrencySeeder (15.91ms)
Seeding: Database\Seeders\TransactionTypeSeeder
Seeded:  Database\Seeders\TransactionTypeSeeder (4.63ms)
Seeding: Database\Seeders\PermissionSeeder
Seeded:  Database\Seeders\PermissionSeeder (2.19ms)
Seeding: Database\Seeders\LinkTypeSeeder
Seeded:  Database\Seeders\LinkTypeSeeder (3.30ms)
Seeding: Database\Seeders\ConfigSeeder
[2021-04-12 18:18:57] local.WARNING: Database entry exists. Update to latest version (16)  
Seeded:  Database\Seeders\ConfigSeeder (26.29ms)
Database seeding completed successfully.
Going to decrypt the database.
No decryption required for table "accounts".
No decryption required for table "attachments".
No decryption required for table "bills".
No decryption required for table "budgets".
No decryption required for table "categories".
No decryption required for table "piggy_banks".
No decryption required for table "preferences".
No decryption required for table "tags".
No decryption required for table "transaction_journals".
No decryption required for table "transactions".
No decryption required for table "journal_links".
Done!
Current working dir is '/var/www/html'
Running upgrade commands...In CreatesUserProviders.php line 42:
Authentication user provider [ldap] is not defined.  

**5.4.6,** the OK one:

> Now in entrypoint.sh for Firefly III
Entrypoint script version is 1.0.12 (2020-12-16)
Running as 'root' in group 'root'.
Current working dir is '/var/www/html'
Now parsing _FILE variables.
done!
Touch DB file (if SQLite)...
Dump auto load...
Discover packages...
Current working dir is '/var/www/html'
Wait for the database.
wait-for-it.sh: waiting 60 seconds for 127.0.0.1:5432
wait-for-it.sh: 127.0.0.1:5432 is available after 0 seconds
DB is up. Time to execute artisan commands.
Current working dir is '/var/www/html'
Run various artisan commands...
Running migration commands...
CreateDB does not apply to "pgsql", skipped.
Nothing to migrate.
Seeding: Database\Seeders\AccountTypeSeeder
Seeded:  Database\Seeders\AccountTypeSeeder (15.03ms)
Seeding: Database\Seeders\TransactionCurrencySeeder
Seeded:  Database\Seeders\TransactionCurrencySeeder (19.93ms)
Seeding: Database\Seeders\TransactionTypeSeeder
Seeded:  Database\Seeders\TransactionTypeSeeder (3.59ms)
Seeding: Database\Seeders\PermissionSeeder
Seeded:  Database\Seeders\PermissionSeeder (2.22ms)
Seeding: Database\Seeders\LinkTypeSeeder
Seeded:  Database\Seeders\LinkTypeSeeder (22.57ms)
Seeding: Database\Seeders\ConfigSeeder
[2021-04-12 18:16:40] local.WARNING: Database entry exists. Update to latest version (15)

**Comment by JC5** [comment]
> [Composer\Downloader\TransportException]
curl error 7 while downloading https://repo.packagist.org/packages.json: Failed to connect to repo.packagist.org port 443: Connection timed out

I haven't put this in the documentation yet. I'll think about what's wise.

**Comment by JacksonHub2** [comment]
Waiting for any update here :)

**Comment by JC5** [comment]
I can do nothing else right now. The Docker container needs to download an extra package and if the site doesn't worked or is blocked, it won't fly. All I can do for a future release is make sure that this is optional, but the download is necessary in either case.

**Comment by JacksonHub2** [comment]
Is this possible to include this as some sort of dependency? for most of docker images, it's by default then, in design, workable for offline and no need of Internet contact.

**Comment by JC5** [comment]
No, not at the moment. The LDAP package requires `ext-ldap` (obviously) which is pretty rare for most installations. I can include `ext-ldap` in the Docker installation. If I require the LDAP package itself, every user of Firefly III would have to install `ext-ldap`, even when they don't need LDAP.

**Comment by JacksonHub2** [comment]
Nah, so sad.. Cut this feature doesn't make the image 'much slim'.If this means to make the application more 'extensible', then release the most simple image is the way. Or maybe consider a full-feature branch ?

**Comment by JC5** [comment]
I get complaints either way. If it's missing people complain. If it's in there people complain.
