### ISSUE TITLE
Category overview not showing the graph for one year

### ISSUE THREAD

**Issue by 3ssen** [firefly-iii/firefly-iii#4639]
**Bug description**
I am running Firefly III version 5.5.6
![categorie_fault](https://user-images.githubusercontent.com/2758036/114296609-95033580-9aac-11eb-9b6d-cf1d5e6e1940.png)
, and my problem is:

When showing the category overview for a specific year the left graph title shows the dates for that year but the labels are showing the current year and the next years.

**Steps to reproduce**
Look at the screenshot :-)

**Bonus points**
- I searched and nobody reported this bug before
- I have added a screenshot.
- On the demo site https://demo.firefly-iii.org/categories/show/6/2020-01-01/2020-12-31 the left graph has not enough data.
- I'm using v2 layout

**Comment by JC5** [comment]
Ah yes. I’ll pick it up when I rebuild this page in v2
