### ISSUE TITLE
After Installation Erorr 500

### ISSUE THREAD

**Issue by earl761** [firefly-iii/firefly-iii#4642]
I am running Firefly III version 5.5.6

**Description**
After installation and creating the user i get this error 500

 Whoops! An error occurred.

Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

array_key_exists() expects parameter 2 to be array, null given
More information

Please collect more information in the storage/logs directory where you will find log files. If you're running Docker, use docker logs -f [container]. You can read more about collecting error information in the FAQ.
Get help on GitHub

You're more than welcome to open a new issue on GitHub.

    Use the search!
    Include the information from this debug page.
    Tell us more than "it says Whoops!"
    Include error logs (see above).
    Tell us what you were doing.

**Extra info**
this is the debug information is 

Debug information generated at 2021-04-11 12:48:40 Europe/Amsterdam for Firefly III version **5.5.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.6 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.16 |
| Host | WINNT |

| System info | Value |
| --- | --- |
| Installation ID | c988eb60-f532-44cc-a12b-917ca2561810 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Amsterdam |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en-US |
| Attempt at "en-US.utf8" | 'en-US.utf8' |
| Attempt at "en-US.UTF-8" | 'en-US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0 |

What could be the issue here!
![Capture](https://user-images.githubusercontent.com/57943691/114301248-bc69fa80-9acc-11eb-8f46-02351d848beb.PNG)

**Comment by Genygo** [comment]
should be the same as #4625 ?

**Comment by JC5** [comment]
Yes
