### ISSUE TITLE
First day of the month ranges

### ISSUE THREAD

**Issue by andresponte** [firefly-iii/firefly-iii#4643]
**Description**
It would be nice if we could customize the first day of the month ranges.

**Solution**
Add a new setting for the first day of the month (X).

- When today range is selected, it should go from the previous X day to today.
- if X <=15, when month range is chosen, it should go from day X of selected month, to the day X-1 of next month.
- if X > 15, when month range is chosen, it should go from day X of previous month, to the day X-1 of selected month.

**What are alternatives?**
First day of the month could be taken form the fiscal year start date, available at Preferences->Fiscal year settings.

**Additional context**

![imagen](https://user-images.githubusercontent.com/69403695/114302897-1e256700-9ac3-11eb-8f0b-a3b10c149ccb.png)

![imagen](https://user-images.githubusercontent.com/69403695/114302964-72c8e200-9ac3-11eb-9ba2-173336a60c17.png)

**Additional feature**
It could be nice if we could configure the default range after login, currently the ~~"today"~~ "this month" range is selected by default.
Possible options:
- Today
- This month (currently selected)
- Last 7 days
- Last 30 days
- Last 2 months
- Last 3 months.
- This year.
- Last 365 days

**Comment by zynexiz** [comment]
I just thought about purposing something similar regarding the default range after login. Not sure what the range currently is set to, but it also include future transaction which can be somewhat confusing sometimes.

**Comment by andresponte** [comment]
> 
> 
> I just thought about purposing something similar regarding the default range after login. Not sure what the range currently is set to, but it also include future transaction which can be somewhat confusing sometimes.

That's right, the range is currently set to "this month", so it go from day 1 to the last day of current month. I updated the description.

**Comment by zynexiz** [comment]
Just a thought, why not add the option to completely customize the ranges to your own likings instead of having them "hard coded" in the application? That would be a nice feature :smile:

**Comment by JC5** [comment]
This will not change. It will always be first to last day of the month. 

https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/

**Comment by zynexiz** [comment]
> This will not change. It will always be first to last day of the month.
> 
> https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/

Fair enough, but maybe add a setting to select witch one to use as default when you login? I prefer to use last 30 days, and now I always need to change it after I logged in.

**Comment by andresponte** [comment]
> 
> 
> This will not change. It will always be first to last day of the month.
> 
> https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/

Hi JC5, and what's about the second feature? The possibility to configure the default range after login. Currently is set to current month (from day 1 to today), but it would be nice if we could set for instance "last 30 days", or maybe if it remember the last range we set in last session.

**Comment by andresponte** [comment]
> 
> 
> > This will not change. It will always be first to last day of the month.
> > https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/
> 
> Fair enough, but maybe add a setting to select witch one to use as default when you login? I prefer to use last 30 days, and now I always need to change it after I logged in.

We think the same at the same time XD

**Comment by JC5** [comment]
The new layout will be better at this. 👍
