### ISSUE TITLE
UK Sort Code

### ISSUE THREAD

**Issue by anoma** [firefly-iii/firefly-iii#4644]
**Description**

The UK the banking system has the concept of a `Sort Code` as described here

https://en.wikipedia.org/wiki/Sort_code

In simple terms every Account in the UK has an Account number and a Sort Code pair.

To the "man on the street" the sort code identifies the bank and branch their account is held at but more importantly it is required when doing domestic payments and transfers.

**Solution**
Add an optional Sort Code field

**What are alternatives?**
Currently I am using the Account number field to store both the Account number and the Sort Code concatenated but this is not ideal since it is munging the data.

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
I’m not going to add this, sorry.

**Comment by anoma** [comment]
Thanks for considering.
