### ISSUE TITLE
test Date format in csv importer

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#4645]
**Description**

Would like a modal popup in the import setup page of hte csv importer to test php date format. Should take a string (date input) and a date format and send a date response or error message if it fails completely.

* had https://github.com/firefly-iii/csv-importer/pull/121, but it seems directly building it in would be better.

**Comment by JC5** [comment]
Why a modal? There’s a little text box below the input. Give it a little emphasis if you want to but let’s not make it bigger than it needs to be.
