### ISSUE TITLE
Missing text entries for budget selection

### ISSUE THREAD

**Issue by zynexiz** [firefly-iii/firefly-iii#4646]
Inside recurring entries you have the drop down list containing your different budgets. The number of entries seems to match up, but the text in the list is missing (it's just white as shown in the screen shot). I checked the budget entries in other places, and the text is shown there (fx. when creating a new transaction). Looking at the HTML code confirmed that the text is actually missing from the select statement.

OS: CentOS 8 Stream
PHP Version: 7.4.16
Apache: Apache/2.4.37 (centos)
Firefly III: v5.5.6

`
<select class="form-control" id="ffInput_budget_id" name="budget_id"><option value="0">(none)</option><option value="2" selected="selected"><option value="5"><option value="1"><option value="9">`

![Screenshot_20210411_170113](https://user-images.githubusercontent.com/22789493/114309556-d95ff700-9ae7-11eb-9a81-36b5d926eb6c.png)

**Comment by JC5** [comment]
Which version?

**Comment by zynexiz** [comment]
Sorry, missed to attach that, updated the post :smile:

**Comment by zynexiz** [comment]
Confirmed fixed in v5.5.7 :+1:
