### ISSUE TITLE
Asociate a credit card account to an asset account.

### ISSUE THREAD

**Issue by andresponte** [firefly-iii/firefly-iii#4647]
**Description**
Associate a credit card account to an asset account.

**Solution**
Currently the "Credit card options" include the payment plan and date:
![imagen](https://user-images.githubusercontent.com/69403695/114310213-f1cd1300-9ae1-11eb-8b49-1a11613c6845.png)

It would be nice if we could also configure an asset account were the payments come from.  So it would be possible to:

- Have an automatic transaction from the associated asset account to the credit card on the pay day according to the payment plan.
- When a new deposit is created, the default "source account" can be automatically set to the associated asset account.

**Comment by JC5** [comment]
No, sorry, such a link is not going to be an option.

**Comment by corcom** [comment]
@JC5 can you elaborate on the reason why?

**Comment by JC5** [comment]
Too much work for too little gain.

**Comment by corcom** [comment]
Thats fair 😄
