### ISSUE TITLE
Long pages loading time

### ISSUE THREAD

**Issue by G4Zz0L1** [firefly-iii/firefly-iii#4649]
I am running Firefly III version 5.5.6 cloned from the github repo.

**Description**
I've imported 1k+ records with the csv importer, but in the transaction related pages the loading times are very long.
I've installed the dev dependencies on composer (and added `beyondcode/laravel-query-detector` package, very useful for query debugging purpouses on laravel).
With the debugbar I've found out the culprit, but I don't know what can be the cause of this.
The screenshots below comes from some of the pages with this high loading times.
In the `transactions/withdrawal` route the server returns 504 after some time, but I don't have any hard limit on execution time on this machine.
I've other laravel project running on this machine (but with smaller databases) and they run just fine.
Can I do something to check where this absurde loading times comes from?

**Extra info**

`accounts/show/{account}` route

![image](https://user-images.githubusercontent.com/13220636/114310413-fe099e00-9aea-11eb-82f8-db62c5be6018.png)
![image](https://user-images.githubusercontent.com/13220636/114310426-08c43300-9aeb-11eb-8689-fa9d772efea1.png)

`transaction/{what}` route on `deposit`

![image](https://user-images.githubusercontent.com/13220636/114310669-cea76100-9aeb-11eb-88f4-5217fe514700.png)

`categories/show/{category}`

![image](https://user-images.githubusercontent.com/13220636/114310921-de737500-9aec-11eb-9145-34f2f1f05bdf.png)

Debug information generated at 2021-04-11 17:18:08 Europe/Rome for Firefly III version **5.5.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.6 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | false |
| Telemetry | true |
| Layout | v1 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | it_IT |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2018-03-15 19:30:17 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4469.4 Safari/537.36 |

**Bonus points**

- :heavy_check_mark: I have read the FAQ at https://bit.ly/FF3-FAQ
- :heavy_check_mark: I added a screenshot
- :heavy_check_mark: I added log files 
- :x: I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Yep, those are big pages. I’m working on a new layout where these are optimized. Otherwise, I’m not going to do something about these queries right now. I appreciate the effort, thanks for diving into this.

**Comment by JC5** [comment]
I have to add though, these load times are absurd. My own installation is wel over 15K rows and loads in less than 5 seconds.

**Comment by G4Zz0L1** [comment]
Exactly, I think there's something strange about this.
If I'm the only one with this problem there must be something missing here.
Another thing I don't understand are the rules: I'm trying to create some rules to move transaction between origin accounts, but even with simple triggers (like description and destination account only) the `test rule` button returns empty.
I think there's something wrong, but the rows in the database are fine, and the import hasn't returned errors.
What can I do to test this out?

**Comment by JC5** [comment]
Try the search.

https://docs.firefly-iii.org/firefly-iii/pages-and-features/search/

Description should be something simply like `text here` or if you want `description_contains:"text here"` which amounts to the same thing.

**Comment by G4Zz0L1** [comment]
I've tried both with the same condition, one single word in the description.
The search is working (even with that crazy time), but the test rule button doesn't.
The locale it's in it_IT.

![image](https://user-images.githubusercontent.com/13220636/114361277-3c986a80-9b76-11eb-9c81-6b1ee2f5615d.png)

![image](https://user-images.githubusercontent.com/13220636/114361475-749fad80-9b76-11eb-94be-ffb4abe1dfbc.png)
