### ISSUE TITLE
Initial values for old liability accounts are not persisted

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#4650]
**Bug description**
I am running Firefly III version 5.5.7, and my problem is:

I have some old liabiliy accounts (created last year) for which it is not possible to persistently store the initial balance and date. When editing these accounts, the respective fields are empty. I need to insert a value in order to submit the edit page, but when I open the page again, these fields show up empty again.

With a newly created liability account everything works as expected. So I suppose that my accounts where created with a FF version that somehow set up these accounts inconsistently.

I checked the database and the only difference between the old an new liability account seems to be that the old ones have a non-null value for `virtual_balance`:

```
SELECT *
FROM `accounts`
WHERE `id` = '666' or `id`= '754'
```
![grafik](https://user-images.githubusercontent.com/317179/114350772-f3421e00-9b69-11eb-8322-0247c09a51b5.png)

Also I noted during my tests, that when you delete a liability account, FF redirects to the wrong URL (namely, to the removed account, leading to a 404 error)

**Comment by JC5** [comment]
What's the content of the transactions table, for account 666 or 754?

The initial balance is a transaction, and nothing has really changed in this regard. But I'm curious to see what's in your DB. Specifically, the transactions you find should have negative amounts.

**Comment by skuzzle** [comment]
Not sure whether you've seen it but I've sent you an email with some more details. For the old liability account there only exists deleted 'Opening balance' transactions (`deleted_at` column in the journal table is filled). I'm not sure whether this is a desired/consistent state?
My goal was to actually start with an initial balance of 0.00 € and to manually add transactions instead of defining an opening balance.

**Comment by JC5** [comment]
I saw it, yep. What you want isn't possible (yet) but I want to do this for the next big release.
