### ISSUE TITLE
Layout 2 Current period issue

### ISSUE THREAD

**Issue by klejejs** [firefly-iii/firefly-iii#4651]
I am running Firefly III version 5.5.7.

**Description**

I have set my period in settings to one month and in the settings, I see on the top bar that the period is indeed selected to April 1 - April 30. However, going back to V2 dashboard, the date range is January 1 to March 31. Clicking reset period button always sets this date range.
Is this a bug or am I missing something? I presumed that reset button should set the range to April 1 - April 30, no?

**Extra info**
 

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
That's probably a bug. Although v1/v2 shares the same preference, they use a slightly different method to calculate the current period. I'll pick it up. See also #4618

**Comment by klejejs** [comment]
Thank you!

**Comment by JC5** [comment]
I wasn't able to replicate this, but that could be me, or the issue has been fixed in the mean time. Make sure you clear your browser cache and local storage so any lingering settings are gone. I do see some issues in the date/period selection (it's stuck on "monthly".

**Comment by klejejs** [comment]
Using latest 5.5.8. The issue I reported seems to have disappeared. Thanks! I did notice another bug though - currently on Sunday, April 18 one week period for V1 is April 12 - April 18 (that is correct), but V2 shows the period for April 12 - April 25. This seems to be another bug. Do you want me to create another issue for that?

**Comment by JC5** [comment]
I'll check it out :+1:

**Comment by JC5** [comment]
Found and fixed, will be part of the next release.
