### ISSUE TITLE
Error 500 when submitting an empty string in the 2FA input field

### ISSUE THREAD

**Issue by rrikesh** [firefly-iii/firefly-iii#4652]
**Bug description**
I am running Firefly III version 5.5.7, and my problem is that I'm getting an error 500 if I submit an empty string in the 2FA box.

I looks like the function is expecting a string and isn't accepting when an empty string is passed through it.

![Screenshot 2021-04-12 at 14 36 31](https://user-images.githubusercontent.com/3250906/114381783-94e26300-9b9c-11eb-8131-58f3235a6871.png)
![Screenshot 2021-04-12 at 14 36 38](https://user-images.githubusercontent.com/3250906/114381797-97dd5380-9b9c-11eb-90d8-0657f88b2051.png)

**Steps to reproduce**
New install, register, and set up 2FA.

**Extra info**
Debug information generated at 2021-04-12 15:30:00 Indian/Mauritius for Firefly III version **5.5.7**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.7 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 32788f8d-c37a-4adb-a670-8ce0b4d9046b |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| System TZ | Indian/Mauritius |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start |  |
| Session end |  |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0 |

**Bonus points**

**Comment by JC5** [comment]
Ah nice find, I'll pick it up 👍

**Comment by rrikesh** [comment]
Thanks! By the way, is there a developer guideline doc? I only found docs for installation and usage.

**Comment by JC5** [comment]
Whoops.

**Comment by JC5** [comment]
No there's not. It's a standard Laravel application.
