### ISSUE TITLE
Cannot hit enter to submit transaction after selecting a suggested option (V2)

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4653]
**Bug description**
I am running Firefly III version 5.5.7 (v2), and my problem is:

When I fill out a new transaction and select a suggested option (the drop down that shows up when you start typing), the input shifts somewhere (I have no clue where) until you hit tab again if you select the option with your keyboard. This means you cannot hit enter to submit the form unless you tab out and back in. If you select the option with your mouse, the input goes back into the box and you can hit enter at that point.

In V1 you can select the transaction with your keyboard and have the input remain in the box in question.

This happens in Source Account, Destination Account, and Category (but not tags).

**Steps to reproduce**

1. Be in V2
2. Start creating a transaction
3. Select a suggested account or category with your keyboard
4. Try hitting enter to submit the form (it doesn't matter if it's fully filled out)
5. See that nothing happens
6. Tab to a different box and then Shift+Tab to the original box
7. Try hitting enter again and see that it does submit.

**Extra info**

Debug information generated at 2021-04-12 08:39:44 America/New_York for Firefly III version **5.5.7**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.7 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Giving back focus to the input means the dropdown will never close. It will reopen again. There is no elegant fix for this, sorry.
