### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4655]
Hello James, I notice a brand new [logo](https://github.com/firefly-iii/firefly-iii/blob/main/public/v2/images/firefly-iii-logo-new.png). I was wondering who made it and what license is it under? I am planning to ~steal it~ use it in my app.

**Comment by JC5** [comment]
It's made by Cherie Woo. She was recommended to me by a GitHub sponsor. On the whole I don't mind if you use it. 

I'll put something in the documentation on the logo. I think I'm going to steal reddit's brand guidelines.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/logo/

**Comment by emansih** [comment]
I'm not sure what happened. The SVG is cut off https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/logo/logo-flame.svg

**Comment by emansih** [comment]
This is what I see 
![image](https://user-images.githubusercontent.com/5896415/114640066-b06f7a00-9d12-11eb-9ae9-f7b4a774dee5.png)

**Comment by JC5** [comment]
I know but the whole figure is there I assure you.
