### ISSUE TITLE
Unable to see transaction list in V2 Homepage 

### ISSUE THREAD

**Issue by gelmistefano** [firefly-iii/firefly-iii#4656]
**Bug description**
I am running Firefly III version 5.5.7, and my problem is:

With V2 Layout i cannot see the transaction list. I receive a 404 when call /api/v1/preferences/frontpageAccounts

**Steps to reproduce**
1. Be in V2 dashboard
2. Login to V2 Homepage
3. See stuck loading on transaction section

**Screenshot**
![image](https://user-images.githubusercontent.com/6096879/114515807-0c67cf00-9c3d-11eb-8a85-fb5c8626c05c.png)

![image](https://user-images.githubusercontent.com/6096879/114515777-0671ee00-9c3d-11eb-90cc-b00ce779ca4d.png)

**Extra Info**
Debug information generated at 2021-04-13 09:40:01 Europe/Rome for Firefly III version **5.5.7**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.7 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 3ba8a841-fad9-4f54-aaee-efd2a7a8da77 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Rome |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2019-10-01 00:00:00 |
| User ID | 2 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
You never used the v1 layout?

**Comment by JC5** [comment]
Never mind, found and fixed :+1:
