### ISSUE TITLE
Default Transaction date is tomorrow's date (v2) 

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4660]
**Bug description**
I am running Firefly III version 5.5.7, and my problem is:

When you go to create a transaction in V2, the default date is ahead by one day. This is not the case in V1. I don't know if this is always the case or if it depends on the time of day.

**Steps to reproduce**

1. Be on V2
2. Go to enter a transaction
3. Look at the default date
4. See that it is tomorrow's date

**Extra info**

Debug information generated at 2021-04-13 21:08:48 America/New_York for Firefly III version **5.5.7**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.7 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.98 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Weird, hadn't noticed it yet. Could be a timezone thing. Do you have the warning under the chart on the dashboard?

**Comment by death2cupbots** [comment]
I do not see any warning under the chart on the dashboard? Would that be there all the time, or just after I create a transaction?
The date is correct now (8 AM), so it probably is a timezone issue. I'll let you know if I notice when the rollover happens.

**Comment by JC5** [comment]
No you wouldn't, no worries. Firefox tends to fall back to UTC and that gives a whole heap of problems. This is the warning.

![Screenshot 2021-04-14 at 14 11 24](https://user-images.githubusercontent.com/5889984/114708163-8de15f00-9d1a-11eb-8291-2c2983558977.png)

And yes, curious to hear when it jumps. I can test this with Chrome, thx.

**Comment by death2cupbots** [comment]
Definitely not seeing that warning under my chart. The date rolls over at 8 PM EDT, which is 12 AM UTC.

**Comment by JC5** [comment]
Found and fixed :+1:
