### ISSUE TITLE
Cannot add attachments when editing transactions (v2)

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4661]
**Bug description**
I am running Firefly III version 5.5.7 (v2), and my problem is:

I cannot add an attachment when editing a transaction in v2. I can add the attachment when creating a transaction in v2, and I can add one when editing in v1.

**Steps to reproduce**

1. Be in V2
2. Edit an existing transaction
3. Add an attachment to the transaction
4. Click 'Update attachment"
5. See that nothing happens

**Extra info**

Debug information generated at 2021-04-13 23:02:52 America/New_York for Firefly III version **5.5.7**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.7 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.98 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] - I have added a stack trace from my log files 
- [ ] - I have added a screenshot.
- [ ] - I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Yep, the entire code is still commented out 😅

**Comment by JC5** [comment]
Will be fixed in the next release :+1:
