### ISSUE TITLE
Inconsistent behaviour when converting expense to transfer concerning budgets

### ISSUE THREAD

**Issue by BWohlbrecht** [firefly-iii/firefly-iii#4663]
**Bug description**
Expenses which are assigned to a budget can be converted to a transfer, which effectively makes it possible to assign a transfer to a budget even though this is not possible when directly creating a transfer.

If this is done the entry on the /budgets page appears as if the transfer did not exist (no values changed), which would be correct, since the money was not spent but rather transferred to a different account. The /budgets/show/{id}/{id} page however treats the transfer as if it were an actual expense and shows the amount as missing. It is then also not possible to unassign the transfer from the budget since the necessary option is not present on the /transactions/edit/{id}.

**Possible solutions to make the application consistent**
1. Make it impossible to convert an expense to a transfer while it is assigned to a budget
2. Make it possible to assign transfers to a budget and handle it correctly in /budgets/show/{id}/{id} (not as if it were a transfer)
3. Unassign the expense from the budget when converting to a transfer (maybe show a warning dialogue)

**Comment by BWohlbrecht** [comment]
Now I'm confused.

After restarting Firefly3 the field to assign a transfer to a budget is present when creating a transfer via /transactions/create/transfers. However I'm certain the field to choose a budget was missing before, otherwise I wouldn't have tried to convert an expense in the first place. I am unable to reproduce the issue again.

Still, the option is missing on /transactions/edit/{id} which is also the case on the demo app.
This means when a transfer is assigned to a budget it is impossible to unassign it, without deleting the transfer.

**Comment by JC5** [comment]
Thanks for letting me know. :+1:

**Comment by JC5** [comment]
Will be fixed in the next release. Inconsistent transactions can be fixed using the command line. Please run the following command:

```
php artisan firefly-iii:fix-transfer-budgets
```

Or run:

```
docker exec -it [container] php artisan firefly-iii:fix-transfer-budgets
```

**Comment by BWohlbrecht** [comment]
Thanks. I'm wondering tho, what is the expected behaviour? Are transfers even meant to be assigned to budgets? Since the form option about budgets is missing when editing a transaction.

If they are not, then the form on /transactions/create/transfers should not provide the option to assign it to a budget and if they are, /transactions/edit/{id} needs to provide that option.

**Comment by JC5** [comment]
No, transfers should not have budgets. The necessary field will disappear (in the current layout) as soon as Firefly III realises you're making a transfer. In the next release, the field won't even be present.
