### ISSUE TITLE
Category list does not generate properly when editing transactions in V2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4665]
**Bug description**
I am running Firefly III version 5.5.7 (v2), and my problem is:

If you go to edit a transaction's category in V2, the category list only suggests the existing category of the transaction. When you delete the original category, the full list pops onto the screen for a second and then gets reduced to that one category. This does not happen on V1.

It does link to existing categories when you type them in and submit, it just doesn't suggest them.

**Steps to reproduce**

1. Be on the v2 layout
2. Have several different categories and at least one preexisting transaction that has a category
3. Edit a transaction with that already has a category
4. Delete the contents of the category field.
5. Notice that the full list appears on the screen for a second before being reduced to the category you just deleted
6. Start typing a different (already existing) category
7. Notice that nothing is suggested

**Extra info**

Debug information generated at 2021-04-15 20:35:11 America/New_York for Firefly III version **5.5.7**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.7 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

Update: I either forgot that I tested this in Firefox and it didn't work or I didn't bother to test in Firefox for some reason. It doesn't work in any browser.

**Comment by JC5** [comment]
Thx, I'll check!

**Comment by JC5** [comment]
Fixed :+1:
