### ISSUE TITLE
Reconciliation resulting in 404 error via v2 interface

### ISSUE THREAD

**Issue by chrismast** [firefly-iii/firefly-iii#4666]
Hi,
Running latest Firefly III version (as always) and found a small bug (maybe already reported, but did not see it):
While in the Accounts tab (v2 design), clicking on the dropdown and reconcile the reconcile page will not load.
When I change the URL towards the v1 design format, it loads without issue though:

v2 URL: https://firefly.christianreiners.net/accounts/reconcile/7
v1 URL: https://firefly.christianreiners.net/accounts/reconcile/7/index

Cheers!

**Comment by death2cupbots** [comment]
Are you running 5.5.7? I reported this in 5.5.1 (#4572). It's been working for me since 5.5.2.

**Comment by chrismast** [comment]
> Are you running 5.5.7? I reported this in 5.5.1 (#4572). It's been working for me since 5.5.2.

yes, just updated this morning to 5.5.7:

![image](https://user-images.githubusercontent.com/63285062/114966591-1e47ad00-9e9d-11eb-9519-f224bba46e49.png)

**Comment by JC5** [comment]
Make sure you clear your cache.

**Comment by chrismast** [comment]
> Make sure you clear your cache.

Thanks, that actually worked!
Tried it in a incognito window and I am not getting 404 error.
Will mark this issue as closed.
