### ISSUE TITLE
Credit Card Payment Scheduling / Bills

### ISSUE THREAD

**Issue by RegalMonkey** [firefly-iii/firefly-iii#4669]
I am running Firefly III version 5.5.7.

Hello, 

Just got a fresh install setup and was looking to mimic the functions I'm accustomed to from using KMyMoney. (https://kmymoney.org/) and have run into some issues with the credit cards. I get that they're considered an asset in here, which so long as one remembers to mark it as a negative balance initially works fine. However I'm having issues with the payment schedule setup.

![image](https://user-images.githubusercontent.com/82684917/115094868-bd43c780-9ee4-11eb-8c8d-501a1ef60883.png)

I see the field monthly payment date, but aside from it not showing any other options than full payment, it also doesn't seem to have any bearing on creating a 'bills' item. I do like to check up on each card when it would be due even if there's no balance just to make sure there's nothing on there.

On a related note, for the bills menu. It would be particularly handy to add a 'skip this instance' button to just bump it out by one interval for cases like the above where the payment would be $0 allowing for a check-and-go in a sense.

Any clarification needed, just ask.

Thanks.

**Comment by RegalMonkey** [comment]
Actually, thinking on it further even adding a link into the bills item to create a transaction based on predetermined parameters, from a given asset to a given expense would save a bunch of complication of having to write in rules to associate a transaction with a bill. 

Pressing an enter transaction button could just open the transaction menu with the expected from/to/amounts pre-populated to allow for editing and entry, then the interval is marked fulfilled. Granted I'm no coder but that seems a lot simpler than associating transactions backwards to the bill.

**Comment by JC5** [comment]
> I see the field monthly payment date, but aside from it not showing any other options than full payment, it also doesn't seem to have any bearing on creating a 'bills' item.

No. That's up to you. Firefly III won't provide it.

> On a related note, for the bills menu. It would be particularly handy to add a 'skip this instance' button to just bump it out by one interval for cases like the above where the payment would be $0 allowing for a check-and-go in a sense.

Bills aren't really meant for these things. Personally, I don't create bills for credit cards at all. The payments I make for a credit card are regular withdrawals and paying the balance of the credit card is a transfer.
