### ISSUE TITLE
When creating a split transaction, split description field is wrong of the final transaction entry

### ISSUE THREAD

**Issue by erdmenchen** [firefly-iii/firefly-iii#4680]
**Bug description**
I am running Firefly III version 5.5.7, and my problem is:
When creating a split transaction, the final transaction has the description of the first split instead of the split transaction field.

**Steps to reproduce**
* Create a new transaction
* Fill out the form (will be split #1)
* Add another split
* Fill out the split #2 form
* Fill out the split description field (at the bottom, near submit)
* Store the transaction
* New transaction has the description of split #1 instead of the split description

**Extra info**
Debug information generated at 2021-04-18 00:48:40 Europe/Berlin for Firefly III version **5.5.7**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.7 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.9 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | - |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Berlin |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite, sqlsrv |
| Current driver | sqlite |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-06-30 00:00:00 |
| Session first | 2013-10-31 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before

- [ ] I have added a stack trace from my log files 

- [ ] I have added a screenshot.

- [ ]  I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nice find, will be fixed in the next release.
