### ISSUE TITLE
CSV importer latest version

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#4681]
Hey,

Is it normal the latest CSV importer version 2.5.1 has only its own tag and is not tagged as latest?
Is it on purpose or just a miss?

Thanks!

**Comment by JC5** [comment]
It looks like the build failed and I never noticed. Should be fixed now, thanks for letting me know!

**Comment by MacPaille** [comment]
Indeed I can now download the latest docker image as 2.5.1 :) Thanks for the quick fix!
