### ISSUE TITLE
Ability to filter transactions using multiple tag filters with AND and OR

### ISSUE THREAD

**Issue by priyesh2609** [firefly-iii/firefly-iii#4682]
**Description**
Please describe your feature request:

- I wan't to have a report in such a way that I can filter transactions based on multiple tags. So, that search becomes a powerful search.
- All the current reports are made on expense and income (revenue). I am unable to find a way in which I can have a report on transfers.

**Solution**
Basically AND or OR on different entities

**What are alternatives?**
I can't seem to find one. If you could tell me, how can I do some smart filtering of transaction on conjunction of tags.

**Comment by JC5** [comment]
I'm not entirely sure what you want exactly. Would you elaborate?

Transfers are counted as expense or revenue iff the opposing account is removed from the report. So for example, if you have a report with asset accounts A and B, and all that you have is transfers between them, the final report would say "zero".

However, remove either A or B and the report will behave as if the transfers are expenses (or revenue).

But again: let me know what you want exactly.

**Comment by savyajha** [comment]
Not OP, but the request seems like a way to filter transactions using combinations of tags. For example, if I have 2 tags called "food" and "snacks" and I label everything I buy to eat with the tag "food" and snacks (such as crisps or coke) with the tag "snacks", there doesn't seem to be a way to filter transactions which are labelled with "food" but not with "snacks".

Or to give another example, say I label purchases using "amazon" and "deliveroo" depending on where I ordered them from, there isn't a way for me to see the transactions which are labelled either "amazon" or "deliveroo".

So in effect, continuing both these examples, it would be nice if I were to be able to filter using logical operators, such as `"amazon" OR "deliveroo"` or `"food" NOT "snacks"`

**Comment by JC5** [comment]
If that's the question the answer is short, that's not going to be a part of Firefly III.
