### ISSUE TITLE
Layout v2 - Reset form option on Enter Transaction

### ISSUE THREAD

**Issue by danjl1100** [firefly-iii/firefly-iii#4684]
**Bug description**
I am running Firefly III version 5.5.8, and my problem is:

On the Create New withdrawal/deposit/transfer page, the `Reset form after submission` checkbox **does not reset**:
* Source Account
* Destination Account
* Date

**Steps to reproduce**
1. Set `FIREFLY_III_LAYOUT=v2`
1. Start to create new withdrawal / deposit / transaction
1. Check "Reset form after submission"
1. Store transaction
1. New empty form has Source, Destination, and Date leftover from the previous entry.

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

---------------------

**Related question**
I often use both `After storing, return here to create another one` and `Reset form after submission` to log withdrawals / deposits / transfers from my online baking.
In Layout V1, it would auto-set the new transaction type based on the source and destination accounts, so I could use one page to enter all types of transactions.

Layout V2 currently limits to a single transaction type for each form  (`transactions/create/withdrawal` vs `transactions/create/deposit` vs `transactions/create/transfer`).

Is this change a design decision, or can I expect mixed-input transaction types later in V2?

**Comment by JC5** [comment]
I’ll make sure the form will reset properly in the future.

But the form will be back to a split form for each separate transaction type, like it used to be in the old days. 

It’s a hassle for me too but it saves a lot of code and is very newbie friendly.
