### ISSUE TITLE
Account graph on V2 dashboard only updates once when you change the date range

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4685]
**Bug description**
I am running Firefly III version 5.5.8 (v2), and my problem is:

With the fix for #4667 the account graph on the v2 dashboard now updates, but it will only do it one time. If you change the date range a second time, the graph no longer updates. Everything else on the page behaves normally. This happens on both Brave and Firefox.

**Steps to reproduce**

1. Be on the V2 dashboard
2. Change the date range
3. Notice that the account graph has indeed changed
4. Change the date range again
5. Notice that while everything else has updated, the account graph has not.

**Extra info**

Debug information generated at 2021-04-18 17:14:55 America/New_York for Firefly III version **5.5.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.8 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Yep, and I know why :(. Sloppy, thx for letting me know.
