### ISSUE TITLE
Multiple Addresses for Crypto Accounts (Assets/Revenue/Expenses/...)

### ISSUE THREAD

**Issue by financelurker** [firefly-iii/firefly-iii#4689]
**Description**
I would like Firefly III to better support the shift to a crypto economy for users who spend or earn their bucks vía crypto and want to keep this data next to their personal finance.

Coins you own are often distributed across multiple public addresses which in total represent one logical holding (private-keys on a ledger nano / trezor / ...). As for now there is just the notes field to put unstructured/complex information, the name field and more or less tags. All of those fields seem wrong to put this kind of information.

**Solution**
Make accounts to additionally contain a list of "addresses".  These must not be validated against any specific pattern for now. For the IBAN it's okay, but it breaks outside the SEPA system (or in crypto). For efficiency reasons this can be handled like a tag, but should act like an address.

**What are alternatives?**
Currently there is just the notes field that can carry unstructured/complex data. And probably the tags, that could carry public crypto addresses. But using both seems wrong, as they should stay usable to the user and not be cluttered with this additional data needed to handle.

**Additional context**
This is probably not an issue alone to asset accounts. Every account type should have that option for handling multiple addresses (exchanges often handle multiple addresses, your grocery store next door will have multiple addresses which will vary from purchase to purchase, ... you name it).

On the long run (for Firefly III to be able to be your personal finance tool far beyond FIAT money) this circumstance of multiple addresses should also be reflected on transactions too. This is not part of this feature request, it should just give you an impression in which direction and possibilities I'm thinking.

**Comment by JC5** [comment]
>  in total represent one logical holding

And this is what Firefly III aims to be. A logical holding. It's the reason the CSV importer supports "mapping". It goes against the idea of Firefly III to be an exect representation of your crypto holdings, with all the addresses and meta data that it would pertain. For that, you have the blockchain. Similar to your groceries example. If you want to save all of the possible (IBAN)  addresses your favorite super market uses, either create separate expense accounts for them or store the addresses in the CSV importer configuration.

If you use one logical asset account for your crypto you will have to do the mapping to all the possible addresses yourself. That's not something Firefly III can or will facilitate for you. I love meta data as much as the next guy, but this doesn't feel like a good addition to Firefly III.

**Comment by financelurker** [comment]
It all began with a thought "hey, accounts can store an address like an "IBAN" as account information, so conceptionally they also should store the public addresses of my crypto coins".

Okay, so we can agree that those multiple public addresses, representing one holding should also be reflected as one account within Firefly-III. That's good, because I don't want to implement against the bare nature of it (and it was the way I was thinking in the first place too).

See, the ledger is a good thing, freely accessible, publicly available and so on. But the reason I am managing my personal finance in Firefly in the first place is, to have all that information locally in one place without the need to always check on multiple accounts online (or being "blind" when having an internet outage, ...).

Okay.

> you will have to do the mapping to all the possible addresses yourself

That's what I'm going to do anyways. But I'm curious to where to put that information, as I want my Firefly-III sidecar services as stateless as possible, running with no "business data" in it's configuration (besides access tokens). And new accounts should only be added within Firefly-III and there should not be the necessity to clutter that configuration across two or multiple places. (I hope you can understand my way of thinking here)

What's your guess of the notes field? In my opinion it's not a pretty place to put this information at all, but I'll consider it as an alternative. What's the limitation in size or is there any? I've tried to look into the database migration scripts, but couldn't find any hint on that.

**Comment by JC5** [comment]
> And new accounts should only be added within Firefly-III and there should not be the necessity to clutter that configuration across two or multiple places. (I hope you can understand my way of thinking here)

I can, yes. If Firefly III would present a solution, it would need to be more universal, and I'll give it some thoughts.

> What's your guess of the notes field?

About 64K should fit just fine. That's the size of most DB's TEXT fields

**Comment by financelurker** [comment]
Okay, as I'm digging deeper into that hole, I realized it wouldn't make sense for now to insert every public crypto address into the account information as (what I've read, if anyone stumbles across this please feel free to correct me here) most wallets work with one major key (xpub) from where new addresses can be derived (see https://cryptoapis.io/blog/25-all-you-need-to-know-about-hd-wallets-xpub-ypub-and-zpub) - and there are countless of addresses that can be derived.

So, it just boils down to one key, the xPub key (or yPub, zPub, ...) from which all addresses can be derived from. And yeah, I'll give you that - the handling of public-keys and the derived addresses are a more complex change that probably should not happen within Firefly-III.

> If Firefly III would present a solution, it would need to be more universal

Well, I think it already is a super platform for that. The base concepts in crypto are more or less the same as with FIAT, with "just" some differences in the used data structures :)

**I'll close this issue for now** as the feature request (multiple addresses in one account) don't make any sense to me anymore.
For my need right now I'll use the notes field.

Thank you for your time - it helped a lot!
