### ISSUE TITLE
Unknow accounts [v2]

### ISSUE THREAD

**Issue by M4RC02U1F4A4** [firefly-iii/firefly-iii#4693]
**Bug description**
I am running Firefly III version 5.5.8, and my problem is:

I have 2 unknow accounts and I don't understand where they come from 

**Extra info**
![immagine](https://user-images.githubusercontent.com/23193188/115543996-576b8d00-a2a2-11eb-8e5d-1965d26b9613.png)

![immagine](https://user-images.githubusercontent.com/23193188/115544056-694d3000-a2a2-11eb-9386-d384ac790632.png)

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.

**Comment by JC5** [comment]
Thanks for letting me know. Check out your preferences, and save them again for good measure. Does that clear them?

**Comment by M4RC02U1F4A4** [comment]
Settings > Preferences > Save settings, seems to have solve the issue, thanks for you help

**Comment by JC5** [comment]
No problem, I'll make sure this won't happen in future releases.
