### ISSUE TITLE
Layout v2 white space 

### ISSUE THREAD

**Issue by M4RC02U1F4A4** [firefly-iii/firefly-iii#4695]
**Bug description**
I am running Firefly III version 5.5.8, and my problem is:

If there is no data there is a blank space under the summaries at the top

![immagine](https://user-images.githubusercontent.com/23193188/115601392-0f6a5b80-a2de-11eb-8c4c-9e332c212f12.png)

![immagine](https://user-images.githubusercontent.com/23193188/115601484-28730c80-a2de-11eb-8235-dc8413781a85.png)

**Comment by JC5** [comment]
I don't really care, but if you have a solution feel free to submit a PR 😉

**Comment by JC5** [comment]
But joking aside, thanks for letting me know. I was aware of the discrepencies but I was under the impression these fields will always be filled. Do you happen to have an empty DB?
