### ISSUE TITLE
How to run csv-importer behind TLS

### ISSUE THREAD

**Issue by EliRibble** [firefly-iii/firefly-iii#4696]
I am running Firefly III version 5.5.8.
I am running csv-importer version

**Description**
I'm attempting to use the web UI for csv-importer behind nginx as a reverse proxy. It doesn't allow regular http requests and redirects to https. The csv-importer UI makes various requests to assets (css, JS) that fail and critically attempts a request to `/token/validate` over http using XHR which fails. I couldn't find any information in the docs for csv-importer to tell it to create URLs with `https://` instead of `http://`. How should we do that?

**Extra info**
 

It looks like csv-importer uses Laravel. I was able to force `https` by modifying `/var/lib/http/app/Providers/RouteServiceProvider.php` and added the following:

```
  public function boot() {
    resolve(\Illuminate\Routing\UrlGenerator::class)->forceScheme('https');
  }
```

This seems pretty heavy-handed. I tried adding all of the following environment variables - none did what I want:

```
BASE_URL=https://importer.my.tld
CSV_IMPORTER_URL=https://importer.my.tld
ASSET_URL=https://importer.my.tld
APP_URL=https://importer.my.tld
FORCE_HTTPS=true
EXPECT_SECURE_URL=1
```

`ASSET_URL` *did* fix asset loading - just not the `/token/validate` request.

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
What's your reverse proxy config?

If you don't configure it correctly it won't work. If you do it right you don't need to change anything in the CSV importer.
