### ISSUE TITLE
API creating transaction, destination_number is being set to the name

### ISSUE THREAD

**Issue by bartekd123** [firefly-iii/firefly-iii#4697]
**Bug description**
I am running Firefly III version 5.5.8, and my problem is:

When running a api request to create a transaction (api/v1/transactions), for the value of destination_number, it looks like it now sets that as the name of the destination account. 

**Steps to reproduce**
1.) Do a API request against api/v1/transactions specifying a destination_number that matches an account in firefly
2.) Look in the transaction, and you will see the destination account have a name that reflects the number in step 1

**Extra info**
I have a iOS shortcut that creates this transaction. In the previous version, it set it as the correct account ID. Using the same shortcut, it now creates a new expense account with the name being the number

I was going to try to reproduce this using the demo site, but couldn't see how to use the swagger UI with the demo site. NOt sure if it is possible. Sorry!

**Comment by JC5** [comment]
Nice find, will be fixed in the next release :+1:

**Comment by ayvazjet** [comment]
**@**
