### ISSUE TITLE
Incorrect amount boxes and cosmetic issue in V2 Dashboard

### ISSUE THREAD

**Issue by gelmistefano** [firefly-iii/firefly-iii#4700]
**Bug description**
I am running Firefly III version 5.5.8, and my problem is:
In V2 Dashboard, the "Left to spend" box is incorrect. It reports the already spend amount and not the Left.
Also, the bill to pay (if all bills already payed)  does not show any value (same issue [#4695](https://github.com/firefly-iii/firefly-iii/issues/4695)) - Possible solution: display 0€ Value if no bill must be payed.

**Extra info**
Debug information generated at 2021-04-22 12:17:05 Europe/Rome for Firefly III version **5.5.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.8 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 3ba8a841-fad9-4f54-aaee-efd2a7a8da77 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Rome |
| Browser TZ | Europe/Rome |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2019-10-01 00:00:00 |
| User ID | 2 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36 |

**Screenshot**
Budget screenshot (Real amount masked)
![image](https://user-images.githubusercontent.com/6096879/115699595-10df6680-a366-11eb-880c-260fa990f284.png)

Dashboard V2 Screenshot (Real Value Masked - Note the minus symbol that indicate a negative value):
![image](https://user-images.githubusercontent.com/6096879/115699724-353b4300-a366-11eb-8166-b58f737f08dd.png)

Dashboard V1 Screenshot (Real Value masked - Positive value with a positive per day amount)
![image](https://user-images.githubusercontent.com/6096879/115700099-a1b64200-a366-11eb-8d90-75c9c473d98c.png)

In V1, the bill box was empty but does not create any misalignment. It's only a cosmetic bug but i think a solution with zero value can be easy to implement (even if it's not for me to judge)

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.

Thanks for your work!

**Comment by JC5** [comment]
See also https://github.com/firefly-iii/firefly-iii/issues/4695

**Comment by JC5** [comment]
> It reports the already spend amount and not the Left.

Have you set an available amount on the budgets page?

**Comment by gelmistefano** [comment]
Yes, I have.

**Comment by JC5** [comment]
Can't seem to replicate it, sorry.

**Comment by gelmistefano** [comment]
If you need other data I'm available  or if it's only an issue on my environment I'll try to recreate the budget.

**Comment by death2cupbots** [comment]
I replicated this issue on Brave on my desktop manjaro linux yesterday and I just replicated it on Firefox on my Pinebook Pro manjaro linux. It doesn't seem to be happening on Vivaldi on my Pinebook Pro. I'll do more testing on my desktop when I get home from work.

**Comment by JC5** [comment]
Thanks, I'm curious to see more. The code is basically the same as v1.

- If you set an "available budget", the "amount left" is that available budget minus whatever you spent *in a budget*.
- If you set no available budget or remove it, the amount will be whatever you spent *in a budget*

If you have no budget or spend money without a budget, it'll be empty. If you see a case where this is different, let me know.

**Comment by death2cupbots** [comment]
So on certain browsers, it still defaults to April 1-May 1 on the dashboard. You can see this on the account chart and in the bills, for example. If that's the case, I'm guessing you cannot calculate a left to spend, because the left to spend is locked into April 1-30.

I was experimenting and I set the dates to April 1-29. That fixed the account chart, but not the left to spend. When I changed it to April, it looks like it fixed everything so now Left to Spend reports correctly.

**Comment by JC5** [comment]
I'll make some calls. Looks like we're gonna have to cancel time zones.

**Comment by JC5** [comment]
I pushed some fixes to the develop branch. It's a bit of a guess whether it works, not gonna lie, but it looks like there's no date drifting anymore.

**Comment by stickperson** [comment]
Is the amount in "left to spend" related to #3986? I was going to create an issue (and offer my help) to bust the cache when budgets are updated but decided to search the backlog of issues first.
