### ISSUE TITLE
More fine grained options for rules

### ISSUE THREAD

**Issue by zynexiz** [firefly-iii/firefly-iii#4703]
If I haven't missed something obvious, there is only two ways to match triggers for rules; strict mode or promiscuous (match anything) mode. The strict mode is pretty straight forward, and all triggers must match for the rule to run. In promiscuous mode, any trigger will fire the rule. Match anything can probably be useful in some cases, but more often you want to have a more fine grained triggers for your rules.

Fx. I got two bills from my two electric companies (one for the lines them self and one for the usage). I want to create a bill that match both of these, thus having to create two bills, one for each because of the strict mode (two destination accounts in my case). A better way is to be able to apply AND or OR to the triggers them self, like if THIS _and_ THIS _or_ THAT. That would make the rules more powerful and you can match more than just one thing.

In promiscuous mode, my rule match more or less every transaction I had because of the big range for the cost amount.

**Comment by JC5** [comment]
Sorry, but no. The rules aren't meant as an all encompassing tool to manage all use cases. With the current featureset most users can do most things. If you need more complexity, you'll have to build something using the API.

**Comment by zynexiz** [comment]
OK, would be a nice addition though. Seems like the idea was already mentioned in #4682 to.
