### ISSUE TITLE
API Inconsistency

### ISSUE THREAD

**Issue by forcaeluz** [firefly-iii/firefly-iii#4706]
**Bug description**
I am running Firefly III version 5.5.8, and my problem is:
A small inconsistency in the API. For the accounts, it says that interest rate should be a string. But I'm getting the number 0. (My interest is 0, but still, I would expect to received "0".

**Steps to reproduce**

Just use the API to get a list of all the accounts, and check what the response is.

**Comment by JC5** [comment]
Nice find, thanks, I’ll pick it up!
