### ISSUE TITLE
Bill rules aren't applied anymore

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#4707]
**Bug description**
I am running Firefly III version 5.5.8., and my problem is that transactions aren't linked to bills anymore. It looks like that this behaviour started after my update from 5.5.7 to 5.5.8 yesterday.

**Steps to reproduce**
- Create a new transaction that matches a rule to trigger a connection to a bill
- Open bill, "run rule again on all transactons"
- New transaction is not linked. Moreover, all previously linked transactions are gone (not linked anymore)

This happens to all bills/ rules I have. Also when I open a rule for a bill that already has multiple linked transactions and I click "see matching transaction", no transactions are found.

**Extra info**
- I can still manually link a bill when I create/edit a transaction
- I am not 100% sure if a was running 5.5.7 or maybe 5.5.6 before
- Also I am not sure if this is really connected to an recent update. For example a transaction from yesterday (that was created by a recurring transaction before the update) was linked just fine while another transaction from the day before yesterday was not linked to the bill. In any case no transactions are matched by rules at the moment

**Bonus points**

- I searched and nobody reported this bug before

**Comment by JC5** [comment]
I can't seem to replicate this, at least not at first glance. A rule I just made that triggers a connection to a bill works as expected.

Is there anything in your logs ([enable debug mode](https://docs.firefly-iii.org/firefly-iii/faq/other/#how-do-i-enable-debug-mode)) that you can share?

**Comment by Styleflix** [comment]
Okay, I did some further testing. Actually the automatic connections for transactions to bills do work. I don't know what exactly happened when suddenly all connections where messed up but maybe that was up to me. For the specific tests I did before I opened this issue, of all rules I picked these two that actually had mistakes - no idea why I never recognized them. So in general everything works (sorry for the confusion).
Except one thing: When I open a rule for a bill that already has multiple linked transactions and I click "see matching transaction", no transactions are found (although they are shown under "Connected transactions" in the bill). That's no big problem but it seems to be not the way it should so I thought I mention it.

**Comment by JC5** [comment]
That's good to know and I'll do some checking. It could be that the rule in its current state, will no longer match old transactions.

**Comment by Styleflix** [comment]
> It could be that the rule in its current state, will no longer match old transactions

After some looks into it I don't think so actually. E.g. when I modify a rule so that it doesn't match anymore, then rerun the rule for all prevoiusly linked transactions to disappear, then modify the rule again and correct it, it still doesn't show transactions in the preview but finds transactions when I trigger the rule afterwards.

**Comment by JC5** [comment]
Alright, that depends a bit on the triggers and the changes. Could you show an example?

**Comment by Styleflix** [comment]
I am not sure how to show it the best. I just made some screenshots:

![Bills-1](https://user-images.githubusercontent.com/81714586/116306190-0e856e00-a7a5-11eb-9a4e-7fa3ed676632.PNG)
Thats the bill with the correctly connected transactions at the bottom. ^


![Rule-1](https://user-images.githubusercontent.com/81714586/116306192-0f1e0480-a7a5-11eb-829a-646c550f3bd4.PNG)
Thats the rule for it. ^


![Trigger-1](https://user-images.githubusercontent.com/81714586/116306193-0f1e0480-a7a5-11eb-902a-4da840aadf42.PNG)
That happens when I do a test for matchting transactions for that rule. ^


Btw. I just want to clearify that thats not a real problem for me. As long as the actual connections work (whats the case) it's fine for me. I only wanted to show it if it is some kind of bug or something.

**Comment by JC5** [comment]
Will be fixed in the new release, thanks for the clarification!

**Comment by Styleflix** [comment]
cool, thank you! :)
