### ISSUE TITLE
identifier-based detection method does not look for exactly same ID.

### ISSUE THREAD

**Issue by bpjobin** [firefly-iii/firefly-iii#4708]
**Bug description**
I am running Firefly III version 5.5.8, and my problem is:

I've imported two csv files using the identifier-based duplicate detection method. The first file had transactions with IDs from 1764 to 5112 and the second one 311-1176. On second import, CSV Importer tells me that transactions with these external_id already exist. For example, the transaction on line #2 complains that ID #312 already exists but links to a transaction that was imported with the first file and that has ID #4312. Same goes to the other transactions in this screenshot. Every external_id is found IN the current ID that I'm trying to import, but is not EQUAL TO it.

![Screen Shot 2021-04-25 at 9 00 31 AM](https://user-images.githubusercontent.com/46512567/115994372-b1bb6500-a5a4-11eb-908b-7a4713db5bfc.png)

![Screen Shot 2021-04-25 at 9 06 14 AM](https://user-images.githubusercontent.com/46512567/115994553-7d947400-a5a5-11eb-9a61-301b26e9e66c.png)

**Comment by JC5** [comment]
Ah nice find. I was under the impression the search for identifiers was exact. I'll pick it up for a future release :+1:
