### ISSUE TITLE
csv importer line count increments by 10

### ISSUE THREAD

**Issue by bpjobin** [firefly-iii/firefly-iii#4714]
**Bug description**
I am running Firefly III version 5.5.8, and my problem is:

It happened to me three times already, on different imports using rather large csv files (~ 1000 lines). During import process, the log will show line count being incremented by 10 as seen in these screenshots. It does not seem to happen with smaller files.

![Screen Shot 2021-04-23 at 4 05 19 PM](https://user-images.githubusercontent.com/46512567/116068407-3a470d80-a658-11eb-8a5d-47e8344b4fd7.png)
![Screen Shot 2021-04-26 at 6 26 32 AM](https://user-images.githubusercontent.com/46512567/116068563-5f3b8080-a658-11eb-8251-d4ea01267175.png)

**Comment by JC5** [comment]
Which version of the CSV importer are you running? And could you show me some example lines and configuration?

**Comment by bpjobin** [comment]
I'm running `VERSION=2.5.1`

I had one column that was used as mapping with opposing-number but removed it for privacy reasons. If you can't reproduce the bug without it I'll upload a new version with mapping.

Thank you

CSV example:
`
account number,account branhc id,id,mcc,description,payee,date,memo,sic,type,amount,balance
1234567890,,631,,DRUG STORE,Interac - Purchase - DRUG STORE,23/04/2016,DRUG STORE,,other,-25.32,412.11
1234567890,,632,,COFFEE SHOP,Interac - Purchase - COFFEE SHOP,24/04/2016,COFFEE SHOP,,other,-20.32,391.79
1234567890,,633,,Completed transfer from account 0987654321~ Internet Deposit,Internet Deposit from Bank,28/04/2016,Completed transfer from account 0987654321~ Internet Deposit,,credit,200,591.79
1234567890,,634,,FRENCH FRIES,Interac - Purchase - FRENCH FRIES,29/04/2016,FRENCH FRIES,,other,-23,568.79
1234567890,,635,,COFFEE SHOP,Interac - Purchase - COFFEE SHOP,30/04/2016,COFFEE SHOP,,other,-12.33,556.46
1234567890,,636,,ALCOOL,Interac - Purchase - ALCOOL,30/04/2016,ALCOOL,,other,-34.4,522.06
1234567890,,637,,CONVENIENCE STORE,Interac - Purchase - CONVENIENCE STORE,30/04/2016,CONVENIENCE STORE,,other,-22.62,499.44
1234567890,,638,,,Interest Paid,30/04/2016,,,other,0.03,499.47
1234567890,,639,,RESTAURANT,Interac - Purchase - RESTAURANT,01/05/2016,RESTAURANT,,other,-17.3,482.17
`

Config example:
`
{
    "date": "d\/m\/Y",
    "default_account": 10,
    "delimiter": "comma",
    "headers": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "specifics": [],
    "roles": [
        "account-number",
        "_ignore",
        "external-id",
        "_ignore",
        "_ignore",
        "description",
        "date_transaction",
        "opposing-number",
        "_ignore",
        "_ignore",
        "amount",
        "_ignore"
    ],
    "do_mapping": {
        "0": false,
        "1": false,
        "2": false,
        "3": false,
        "4": false,
        "5": false,
        "6": false,
        "7": false,
        "8": false,
        "9": false,
        "10": false,
        "11": false
    },
    "mapping": {},
    "duplicate_detection_method": "cell",
    "ignore_duplicate_lines": true,
    "ignore_duplicate_transactions": false,
    "unique_column_index": 2,
    "unique_column_type": "external-id",
    "version": 2
}
`

**Comment by JC5** [comment]
No need, I see what's happening. Thanks for letting me know.

**Comment by JC5** [comment]
Will be fixed in a next release of the CSV importer. Thanks again!
