### ISSUE TITLE
Layout V2 - Bills to pay looks weird when there are no bills

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#4715]
I am running Firefly III version 5.5.9, and my problem is:

**Steps to reproduce**
1. Enable new layout
2. Ensure you have no upcoming bills
3. Open dashboard:

![image](https://user-images.githubusercontent.com/507922/116070192-9af03d80-a68c-11eb-91d6-9904abef1561.png)

Presumably, this field should say something (maybe "No Bills") instead of being blank?

**Extra info**
Debug information generated at 2021-04-26 10:40:42 UTC for Firefly III version **5.5.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.9 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 1c789eff-ec96-4172-80d7-9ab04aabfda8 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ |  |
| Browser TZ | Europe/Ljubljana |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2017-12-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0 |

**Comment by JC5** [comment]
Thanks, I'll think of something :+1:
