### ISSUE TITLE
V2 Layout Box Column Headings Suggestions

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4717]
**Description**

So In the V2 layout right now, the Categories, Expense accounts, and Asset accounts boxes all have the same column headings: "Category" and "Spent"

![image](https://user-images.githubusercontent.com/21091510/116168217-f0017300-a6cf-11eb-9abd-564d44390c51.png)

The Category "Spent" heading is a little misleading because you've got both spent and earned bars in the same column.

The Expense and Asset accounts boxes should both have "Account" as the first heading, and not "Category"

The Asset accounts box should probably also have "Earned" instead of "Spent"

**Solution**

Change the column names to better describe their contents.

**What are alternatives?**

Leave the column names the same?

**Comment by JC5** [comment]
Ah yes nice :+1:
