### ISSUE TITLE
Layout v2: Deleting parts of a split transaction not possible

### ISSUE THREAD

**Issue by Kurokha** [firefly-iii/firefly-iii#4720]
**Bug description**
I am running Firefly III version 5.5.9 using the new layout, and my problem is:

After deleting one part of a split transaction the transaction can no longer saved. Further editing is not possible if it's a two-part split transaction.

**Steps to reproduce**
1. Create and save a split transaction. It doesn't matter if it's a deposit, withdrawal or transfer
2. Edit the transaction via the edit transaction button
3. Delete any one of the splits

When there are just two splits all the transaction data and input fields vanish, you're only left with the buttons to add another split or save the transaction. You can't switch to the other splits either. Trying the save transaction button does nothing except produce an error in the browser console:
`Uncaught (in promise) Error: Request failed with status code 422`

When there are more than two splits the page shifts to one of the remaining splits, allowing for further editing. But still, saving the transaction is not possible, this time the save button throws the following console error:
`TypeError: this.originalTransactions[0] is undefined`

![1](https://user-images.githubusercontent.com/74882969/116255138-445d2f00-a772-11eb-9755-84497f15e57c.PNG)

**Extra info**
Debug information generated at 2021-04-27 15:54:48 Europe/Berlin for Firefly III version **5.5.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.9 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 6dc483a0-c861-4b1c-a63c-54d9e87ccb55 |
| Using docker? | false |
| Telemetry | true |
| Layout | v2 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-04-30 23:59:59 |
| Session first | 2011-04-30 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0 |

**Bonus points**

- [X] I searched and nobody reported this bug before 
- [ ] I have added a stack trace from my log files 
- [X] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for letting me know, I'll pick it up :+1:
