### ISSUE TITLE
Error 500 while batch edit

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#4723]
**Bug description**

An exception has been thrown during the rendering of a template ("Missing required parameter for [Route: tags.show] [URI: tags/show/{tagOrId}/{start_date?}/{end_date?}] [Missing parameter: tagOrId].").

**Steps to reproduce**
here what I did:
- search for `amount:7.95` ( I guess any amount will do... just ensure it yields 30+ transactions
- check the tick to edit all
- select `bulk` => immediate failure
- select edit (each), do some change and submit => failure

**Extra info**
Debug information generated at 2021-04-29 09:20:05 Europe/Berlin for Firefly III version **5.5.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.5 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 737eec51-caeb-4e8b-a12f-1682af76c329 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Berlin |
| Browser TZ | [BrowserTZ] |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-07-01 00:00:00 |
| Session end | 2020-07-31 00:00:00 |
| Session first | 1999-12-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 |

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4664
