### ISSUE TITLE
Auto complete for query modifiers

### ISSUE THREAD

**Issue by bpjobin** [firefly-iii/firefly-iii#4726]
It would be nice to have auto complete on query modifiers the same way accounts fields in the edit transaction page get auto completed. Here's a mock-up:

![Untitled](https://user-images.githubusercontent.com/46512567/116633683-2c2f1080-a928-11eb-86ea-f92e957f5169.png)

Thank you

**Comment by JC5** [comment]
I've got this on my list for the next layout 👍
