### ISSUE TITLE
Standing orders only with future date?

### ISSUE THREAD

**Issue by Chaoschaot232** [firefly-iii/firefly-iii#4728]
Like requested, my problem in english :)

I want to add a Standing Order but not in the future because it must be possible to select every date for it, even if it's started in the past and my ones started in 01/09/2018 and not in 02/05/2021 so the form errors out which is incorrect behavior.

Normaly, any compareable software has this ability but it seems that there is a bug within firefly 3 which doesn't recognizes my given date correctly.

This needs to be fixed so that I can setup all my orders correctly but for now it is impossible todo this. And yes, I am a person which hates it to start a standing order or anything compareable besides it correct starting date. All entries must have there correct starting date and not any date later.

**Comment by JC5** [comment]
English please.

**Comment by Chaoschaot232** [comment]
> English please.

updates :)

**Comment by JC5** [comment]
Yeah I’ll pick it up in the new layout.
