### ISSUE TITLE
Import does create accounts with name/iban

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#473]
Hi,

I am using this import file and configuration:
[rabobank-default.txt](https://github.com/JC5/firefly-iii/files/658833/rabobank-default.txt)
[Test.txt](https://github.com/JC5/firefly-iii/files/658834/Test.txt)
Column roles:
![image](https://cloud.githubusercontent.com/assets/441924/21286699/39622974-c45b-11e6-9698-350145cf06bb.png)

The revenue/expense accounts used in this file do not exist
The asset account does (the IBAN matches).

I just use the default configuration and options, by clicking Next.
What happens is, that the revenue and expense accounts are created, but the IBAN is stored in the Name of the account, and not in the IBAN field, and the name is lost.
I would expect it to create the accounts with the correct name and IBAN set. That makes it possible to change the account names to something more friendly, and use the IBAN the next times to do the matching.
Am I doing something wrong?

**Comment by JC5** [comment]
Yes, this is a side effect of the current import routine. It is not aware of the row it's processing, just of the field it's currently processing. So whichever field is "first" is picked up on and the rest is ignored.

Making rules can mitigate this issue but the problem remains.

The next version of the importer will be aware of the entire row, and any field related to the opposing account (name, id, iban, etc) will be given to a single "converter" that will return the perfect opposing account, matching all fields and values.

That is however, quite a challenge. But it's on the list!

**Comment by zjean** [comment]
Hi,
thanks for your response.
An issue that I face, that's related to this (I think) is this:
Firefly does not recognize my savings account because it's name differs from the one in the csv. It just creates a new Expense account and stores the transaction as an expense.
Is there something I can do to help improving the importer?

**Comment by JC5** [comment]
You could create a rule that would update your transaction to point to a new (existing) account. 

As for the importer, it needs a pretty big rewrite to become "row aware". I'll see if I can write a Gist about the steps required to do so.

**Comment by JC5** [comment]
The new importer fixes this. It is row aware. Next release (4.6.0) will have this.
