### ISSUE TITLE
V2 - Second split transaction has todays date

### ISSUE THREAD

**Issue by krispek** [firefly-iii/firefly-iii#4730]
**Bug description**
I am running Firefly III version 5.5.10 (v2 layout), and my problem is that the second transaction in a split transaction is stored under todays date. 

**Steps to reproduce**
- create a transaction with a date that is earlier than today
- store it
- open it, and split the transaction
- store it
- check the expenditures list

I would expect it to use the date that has been given for the first part of the split.

**Extra info**
Debug information generated at 2021-05-01 14:35:12 Europe/Amsterdam for Firefly III version **5.5.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.10 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 8331e10d-8df9-4b11-98cd-c56eb4e96f15 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-05-01 00:00:00 |
| Session first | 2011-03-31 00:00:00 |
| User ID | 2 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15 |

DO NOT PUT ```BACKTICKS``` AROUND THE OUTPUT OF THE /debug PAGE

-->

**Bonus points**

- [x] I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- [x] I have added a screenshot.
![2021-05-01 14u39 Screenhot](https://user-images.githubusercontent.com/11836876/116782730-21d95780-aa8b-11eb-8f84-954de02ea5b6.png)
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Indeed yes, I’ll verify and fix!
