### ISSUE TITLE
Liabilities are not suggested in V2 withdrawals

### ISSUE THREAD

**Issue by krispek** [firefly-iii/firefly-iii#4731]
**Bug description**
I am running Firefly III version 5.5.10 (v2 layout), and my problem is that liabilities are not suggested in V2 withdrawals as the destination account. This works in v1. 

**Steps to reproduce**
- create a withdrawal
- start typing for the destination account

Expected: autosuggest suggests a liability account

Currently, it does not. However, with the correct spelling it works.

**Extra info**
Debug information generated at 2021-05-01 14:35:12 Europe/Amsterdam for Firefly III version **5.5.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.10 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 8331e10d-8df9-4b11-98cd-c56eb4e96f15 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-05-01 00:00:00 |
| Session first | 2011-03-31 00:00:00 |
| User ID | 2 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Sorry, in expenditures?

**Comment by krispek** [comment]
Sorry, is a withdrawal in this context. :)

**Comment by JC5** [comment]
Sorry, but this seems to work for me ™️ . I need to type it in but the liability appears just fine.

**Comment by JC5** [comment]
Well something is broken though thx for the pointer. Stay tuned!

**Comment by JC5** [comment]
Sorry, that was a false alarm. If you follow the transaction types, it should work as expected.

https://docs.firefly-iii.org/firefly-iii/support/transaction_types/

**Comment by krispek** [comment]
After some research in looking at the logs, I have the problem.My mortgage is called 'hypotheek'.

In V2 the query is: `GET /api/v1/autocomplete/accounts?types=Expense%20account&query=hypotheek`  This does not result in a suggestion.

In V1, the query is `GET /api/v1/autocomplete/accounts?types=Expense%20account,Cash%20account,Loan,Debt,Mortgage&query=hypotheek` This does result in a suggestion.

So I would say that the autosuggest query is wrong in V2.

**Comment by xzaz** [comment]
I have the same sort of problem. Since the update I cant select my 'hypotheek' any more. In the new transactions:
`/api/v1/autocomplete/accounts?types=Expense account&query=Hypotheek`

In old working transactions:
`/api/v1/autocomplete/accounts?types=Mortgage&query=Hypotheek`

**Comment by JC5** [comment]
Could you open a new ticket and clarify please?
