### ISSUE TITLE
Button 'See matching transactions' not working

### ISSUE THREAD

**Issue by aelsenaar** [firefly-iii/firefly-iii#4732]
**Bug description**
I am running Firefly III version 5.5.10 and my problem is:

In the page for editing a Rule the button 'See matching transactions' is not returning any results. (screenshot 1) When I use the same button (on the same rule) in the Rules overview page (screenshot 2) I get nine results. (screenshot 3)

Maybe this one is related to #4707?

I can also reproduce this problem on the demo site.

**Steps to reproduce**
Select a rule for update and use the 'See macthing transactions'. Then check the same rule on the 'Rules overview page'.

**Extra info**

**Bonus points**
Screenshot 1
![Screenshot_1](https://user-images.githubusercontent.com/16883460/116782779-6664f300-aa8b-11eb-94f1-d920b2dfda55.png)
Screenshot 2
![Screenshot_2](https://user-images.githubusercontent.com/16883460/116782780-6b29a700-aa8b-11eb-8def-622934c548bc.png)
Screenshot 3
![Screenshot_3](https://user-images.githubusercontent.com/16883460/116782783-6cf36a80-aa8b-11eb-9130-9d37076162f1.png)

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks, I’ll pick it up!

**Comment by JC5** [comment]
Will be fixed in the new release, thanks for the clarification!

**Comment by aelsenaar** [comment]
Thanks for the (very!) fast reponse and fix.
