### ISSUE TITLE
Layout v2: Deleting part 2/2 of a split transaction not possible

### ISSUE THREAD

**Issue by Kurokha** [firefly-iii/firefly-iii#4735]
**Bug description**
I am running Firefly III version 5.5.10, and my problem is:

#4720 is still not working correctly. While there are no more error messages, deleting part 2 of 2 in a split transaction doesn't work. If I delete the second part and hit the update transaction button, it takes me back to transaction overview but still keeps both parts. Only if I change something (name, amount, catergory...) on part 1 as well, part 2 gets finally deleted.
Deleting part 1 does work like a charm though, same as deleting parts from a transaction with > 2 splits.

**Steps to reproduce:**
1. Create and save a split transaction with 2 parts. It doesn't matter if it's a deposit, withdrawal or transfer
2. Edit the transaction via the edit transaction button
3. Delete part 2 without changing anything on part 1
4. Save

**Extra info**
Debug information generated at 2021-05-02 00:25:22 Europe/Berlin for Firefly III version **5.5.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.10 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 6dc483a0-c861-4b1c-a63c-54d9e87ccb55 |
| Using docker? | false |
| Telemetry | true |
| Layout | v2 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-05-01 00:00:00 |
| Session end | 2021-05-31 23:59:59 |
| Session first | 2011-04-30 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0 |

**Comment by JC5** [comment]
Thanks, I thought I tested this. I'll check it out!

**Comment by JC5** [comment]
I think I fixed this. Do you have the ability to run Firefly III on the `develop` tag on GitHub, or maybe the develop tag on Docker? It's `fireflyiii/core:develop`.

**Comment by Kurokha** [comment]
Yep, it seems to be fixed now. I can't find any more problems when playing around with split transactions.
