### ISSUE TITLE
Layout v2: "Reset to current period" resets the period to past month

### ISSUE THREAD

**Issue by Kurokha** [firefly-iii/firefly-iii#4736]
**Bug description**
I am running Firefly III version 5.5.10, and my problem is:

The button "Reset to current period" resets the selected period to 1st to 30th of April, even though it's already 2nd of May. I would expect it to take me to 1st to 31st of May by now. Server time is up to date.

**Steps to reproduce**
1. Select an arbitrary period that is not 1st to 30th of April in the draconic date selector
2. Hit "Reset to current period" in the draconic date selector
3. Get thrown back to 1st to 30th of April

**Extra info**
timedatectl output:
               Local time: So 2021-05-02 00:53:57 CEST
           Universal time: Sa 2021-05-01 22:53:57 UTC
                 RTC time: Sa 2021-05-01 22:53:58
                Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

Debug information generated at 2021-05-02 00:49:52 Europe/Berlin for Firefly III version **5.5.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.10 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 6dc483a0-c861-4b1c-a63c-54d9e87ccb55 |
| Using docker? | false |
| Telemetry | true |
| Layout | v2 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-05-01 00:00:00 |
| Session end | 2021-05-31 23:59:59 |
| Session first | 2011-04-30 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0 |

**Comment by JC5** [comment]
Yes, this is on my list. Thanks for reporting!

**Comment by rparree** [comment]
To add to this. With me, the "current period" is stuck on may 2021. It is November 2021 now. For months now it has been stuck on may.

tx.

**Comment by JC5** [comment]
Closed for v3. No worries, all tickets are in my bookmarks.
