### ISSUE TITLE
Click amount to add maximum amount to piggy bank

### ISSUE THREAD

**Issue by SamBouwer** [firefly-iii/firefly-iii#4737]
**Description**

// Disclaimer: I am lazy and want to be able to skip typing wherever and whenever possible ;)

When adding money to a piggy bank, I often add the maximum amount that is available due to the setup of my bank accounts and piggy banks. If would save me some typing and potentially making a typo if it would be possible to click on the amount that can be added to fill in the input field.

**Solution**

When you want to add money to a piggy bank, click the maximum available amount to fill that in the input field.

**What are alternatives?**

You could even skip filling in the field and add the clicked amount right away. Saves another click! This would require some kind of explanation in the UI though.

**Additional context**

A user would click the green text in the image below:

![image](https://user-images.githubusercontent.com/6918900/116810905-a3da8680-ab46-11eb-9279-7cc1ae114222.png)

**Comment by JC5** [comment]
I'll see if I can add that to the new layout :+1:
