### ISSUE TITLE
Input Field Focus Issue on V2 Layout

### ISSUE THREAD

**Issue by dicksonleong** [firefly-iii/firefly-iii#4738]
**Bug description**
I'm on 5.5.10 with V2 layout, and i experience some really annoying input focus issues, possibly caused by the auto complete drop down.

**Steps to reproduce**
1. Go to new withdrawal page
2. Key in something in the `description` field that can match a auto complete
3. Click on the auto complete
4. Click on the `source account` input (or just any other input)
5. The `description` field get focused

Also able to reproduce this on all input that have auto complete.

This is really annoying as i need to click twice the the other input after clicking on the auto complete to switch focus and start typing.

**Extra info**
(I hide my TZ for privacy reason)

Debug information generated at 2021-05-02 22:28:08 for Firefly III version **5.5.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.10 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | |
| Using docker? | true |
| Telemetry | true |
| Layout | v2 |
| System TZ | |
| Browser TZ | |
| App environment | production |
| App debug mode | false |
| App cache driver | redis |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-05-01 00:00:00 |
| Session end | 2021-05-31 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0 |

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4738
