### ISSUE TITLE
Liability type updates don't work

### ISSUE THREAD

**Issue by WhipeeDip** [firefly-iii/firefly-iii#4739]
**Bug description**
I am running Firefly III version 5.5.10 (although I believe I noticed this on 5.5.6 as well), and my problem is:

I am unable to update liability account types.

**Steps to reproduce**
1) Go to Accounts -> Liabilities 
2) Select any existing account -> Actions -> Edit
3) Liability type -> Something different from current type -> Update liability
4) Updated liability type is not reflected 

**Extra info**

Browser: Google Chrome 90.0.4430.93 Official Stable 64-bit
OS: Windows 10 x64 20H2 (19042.928)

Debug information generated at 2021-05-02 18:07:27 America/Phoenix for Firefly III version **5.5.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.10 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b9263db2-d717-405a-a7a8-f5a51eb96c5b |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | America/Phoenix |
| Browser TZ | America/Phoenix |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-05-01 00:00:00 |
| Session end | 2021-05-31 23:59:59 |
| Session first | 2020-08-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 |

**Bonus points**

- I searched and nobody reported this bug before
- I was able to replicate it on the demo site https://demo.firefly-iii.org/ (tried updating "DUO Student loans" to Debt and Mortgage and it was stuck as Loan)

**Comment by JC5** [comment]
Thanks, I'll check it out :+1:
