### ISSUE TITLE
Function like bills for incoming transactions

### ISSUE THREAD

**Issue by kruemelro** [firefly-iii/firefly-iii#4741]
Hi,

firstly i wan't to thank you for this great app. 

I use the bill feature a lot and find it really usefull to always know whats already paid, and what is left to pay this month. 
I miss exactly this feature the other way, to also know what salary is already there and what still has to come. I think this would be usefull for all users who have more than one salary transaction per month. 

What do you think about this?

**Comment by JC5** [comment]
I thought about it in the past but the way I set up Firefly III I decided it wouldn't fit. By budgeting beforehand for a month (or a custom period), it's not that relevant to know what comes in. It's money that should always be extra, and since you're planning for next month ultimately, what's important what you actually get, not what you may get. Hope, in this context, is postponed disappointment.

So no, it's not going to be a feature, sorry about that.

**Comment by kruemelro** [comment]
OK i've got your point. From a budgeting perspective i'm totaly with you. Also i understand you don't have a need for that feature.
I use the strategy "give every dollar a job" and not YNAB. Firefly nearly fullfills my needs, except i need to know what salary is outstanding. 

I will have a look at the code and try to use the bill as a template for my salary function. Maybe you have some hints for me where to get my hands on? If i'm successfull and you are interessted i could create a PR of this. Maybe with a setting in the user profile where the user could switch the 2 strategies. What do you think?

**Comment by JC5** [comment]
Check out app/Http/Controllers/Bill for some hints, you can copy almost the entire structure if you need it. But it's not something I'm going to merge into Firefly III, sorry.

**Comment by kruemelro** [comment]
For everyone who's interested, i found a solution without the need to code something:

- new account "virtual_salary"
- recurring job for every salary position for the 1st. day of each month to create a deposit on the "virtual salary" account
- create a rule for each salary postion to be converted into a transfer from the "virtual salary" account to your main account

So the whole salary which is expected is calculated into the networth. As soon as a salary arrives the money is transfered from the virtual account to the main account. After you got all your salary positions, the virtual account is 0.00

Firefly is really a great product. Thank you very much for you work @JC5
