### ISSUE TITLE
Report for transactions with no category

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#4742]
**Description**

I think this is kind of a minor request:
- Firefly III isn't able to create a category report for all transactions with no category

At first this sounds logical BUT I like to categorize and tag almost all of my transactions so that they are sorted and stored well. Although there are some transactions that don't really fit in any category - so I leave them out. Now it would be great to create a report for all transactions without any category assigned so that I see where that money went.
When I create a category report there is no option for it.

**Solution**
Adding a checkbox for "empty category" or "no category assigned" in "Select category(ies)" under "Extra options"

**What are alternatives?**
I did not figure out any alternative ways to show all transactions with no category assigned at the moment

**Bonus points**
I just modified the html code and took a screenshot of the demo site for what it could look like:

![category](https://user-images.githubusercontent.com/81714586/116912370-665e2200-ac48-11eb-8166-b41fa79a25e7.PNG)

**Comment by JC5** [comment]
Thanks for the idea, maybe in the new layout. 👍
