### ISSUE TITLE
Layout v2: Edit page for transfer transaction type has no foreign currency 

### ISSUE THREAD

**Issue by 7596ff** [firefly-iii/firefly-iii#4746]
**Bug description**
I am running Firefly III version 5.5.10, and my problem is: Editing a transfer transaction on v2 doesn't show a foreign transaction amount. 

**Steps to reproduce**
- Use the v2 layout
- Edit a transaction with a foreign currency specified
- Notice that it isn't displayed

**Extra info**
![screenshot](https://kylie.is-pretty.cool/9mgw1XE.png)

**Bonus points**
- I searched and nobody reported this bug before
- I have added a screenshot.

**Comment by JC5** [comment]
Never noticed that, thanks! I'll check it out.

**Comment by 7596ff** [comment]
so has this bug been fixed? or is the bot sweeping it under the rug

**Comment by JC5** [comment]
The bot is sweeping it up, I didn't notice :D

**Comment by JC5** [comment]
Fixed in the new release.
