### ISSUE TITLE
Several accounts in same bank

### ISSUE THREAD

**Issue by dperezq** [firefly-iii/firefly-iii#4747]
I would like to post an improvement idea which may be useful for some users and can be discussed if needed or not.

I have several bank accounts with deposits inside and the main account and it would be very useful to be possible to aggregate those account in a main account. 
Also, it can be useful for revolving accounts in where you can have some saving account.

I.e Santander bank and then inside main account, saving account and deposit. 

This could be done with a functionality similar to groups in where the actives account could be aggregated.

**Comment by JC5** [comment]
I was planning to expand the "groups" to more things so yes, this is on my list!
