### ISSUE TITLE
Belongings or assets view

### ISSUE THREAD

**Issue by dperezq** [firefly-iii/firefly-iii#4748]
**Description**
- I would like Firefly III to have a dedicated view for rhe belongings, similar to the passives view in where a list is displayed. The idea which I have in mind is to be able to put the price of purchasing and if it has some earning and being able to update the current value.

Just an example:
I bought a house for 200k a year ago and now it's rented for 1k month, so it can be created auto incoming transfers for that price. Also it could be possible to update manually the current price of market to see the evolution by updating the value to 230k and we can see how increase or decrease the value.

Another example, if I bought a car for 10k, that's appear in the table sum with the other belongings being able to update the current value of the car.

Also a sum of all the belongins will give you the money you got in properties out of the bank.

I know it's out of Firefly right now, but I think it would be a great feature for managing belongins. If someone know a way to use any current functionality for this, please let me know. Moneymanager ex has an assets view for this

**Comment by JC5** [comment]
No, sorry.
