### ISSUE TITLE
Unable to add money to a piggy bank

### ISSUE THREAD

**Issue by stratoss** [firefly-iii/firefly-iii#4751]
**Bug description**
I am running Firefly III version 5.5.10 (upgraded multiple times since Firefly 4.x) , and my problem is that I can not add money into a piggy bank. 

The error I'm getting is 'You have no money to put in this piggy bank.'
I can verify that the credit card associated with the piggy bank has enough money (the USD credit card for example in demo.firefly has USD 1000 available).

**Steps to reproduce**
1. Create new piggy bank
2. Assign it to a credit card (with virtual balance)
3. Try to add money

**Extra info**
Debug information generated at 2021-05-06 18:06:59 Europe/Sofia for Firefly III version **5.5.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.10 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | a79709bb-c5d2-4599-b5a0-e09aeb1a339a |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Sofia |
| Browser TZ | Europe/Sofia |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-05-01 00:00:00 |
| Session end | 2021-05-31 23:59:59 |
| Session first | 2020-06-29 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Comment by JC5** [comment]
It looks like you can't add virtual money to a piggy bank. I'm not sure if I should add that functionality though.
