### ISSUE TITLE
Tweaks for the new layout

### ISSUE THREAD

**Issue by stratoss** [firefly-iii/firefly-iii#4752]
**Description**
I've tested the new layout, and `Categories` , `Revenue Accounts` and `Expense Accounts`'s values aren't readable.
![example](https://i.ibb.co/XspRRht/Screenshot-2021-05-07-What-s-playing-Firefly-III.png)

**Solution**
When the background is green, maybe we need a black font-color and/or bold decoration.

**Comment by JC5** [comment]
It's pretty doable on my screen but the screenshot says enough really. I'll pick it up :+1:
