### ISSUE TITLE
Automation - rule - "When a transaction is updated" not working when UI is set to V2

### ISSUE THREAD

**Issue by bartekd123** [firefly-iii/firefly-iii#4755]
**Bug description**
I am running Firefly III version 5.5.10, and my problem is:
When using the v2 of the UI, when the transaction is updated, the automation for transaction updates is not running.

**Steps to reproduce**
 - Create a transaction
 - Create a rule with "When a transaction is updated"
 - update the transaction so it hits that rule, and compare V1 vs V2

**Extra info**
Its not only updating through the UI (browser), but on the backend as well. When I import transactions, I use CSV Importer, and have changes to the file based on rules. Previously those would also trigger my "updates" rules as well, but those aren't running there either.

I set my system to be V2, showed what docker logs displays when I updated the transaction. Reset it back to V1, and did the same, and show the difference below. I removed my token and hostname

 **v2 UI**
```
10.150.3.6 - - [07/May/2021:10:04:05 -0400] "GET /tags/show/507?transaction_group_id=13926&message=updated HTTP/1.1" 200 9821 "https://MyHostname/transactions/edit/13926" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.6 - - [07/May/2021:10:04:05 -0400] "GET /v1/jscript/variables?ext=.js&v=5.5.10 HTTP/1.1" 200 4969 "https://MyHostname/tags/show/507?transaction_group_id=13926&message=updated" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
```

 **v1 UI**
```
10.150.3.6 - - [07/May/2021:10:05:29 -0400] "GET /api/v1/autocomplete/transactions?query=MEAL%20KIT*%20GOODFOOD%20MAR HTTP/1.1" 200 1025 "https://MyHostname/transactions/edit/13926" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
[2021-05-07 14:05:32] local.INFO: Account info is valid, now update.  
[2021-05-07 14:05:32] local.INFO: Not enough info to update foreign currency info.  
[2021-05-07 14:05:32] local.INFO: Ignore search operator "user_action"  
10.150.3.6 - - [07/May/2021:10:05:31 -0400] "PUT /api/v1/transactions/13926?_token=abc123 HTTP/1.1" 200 2717 "https://MyHostname/transactions/edit/13926" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.6 - - [07/May/2021:10:05:32 -0400] "GET /tags/show/507?transaction_group_id=13926&message=updated HTTP/1.1" 200 9793 "https://MyHostname/transactions/edit/13926" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.6 - - [07/May/2021:10:05:32 -0400] "GET /v1/jscript/variables?ext=.js&v=5.5.10 HTTP/1.1" 200 4969 "https://MyHostname/tags/show/507?transaction_group_id=13926&message=updated" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"

```

**Comment by JC5** [comment]
That's weird because they use the same API endpoint. There's no difference there. But I'll investigate 😅

**Comment by bartekd123** [comment]
Thanks, it looks like /api/v1/autocomplete/transactions is not running when set to v2. The above 2 examples was right when I clicked "Update Transaction" in both UIs

**Comment by JC5** [comment]
So wait, does it work or doesn't it? :D

**Comment by bartekd123** [comment]
No, it doesn’t apply the rule for updates when a transaction is updated. When using v1 it does work as expected. I showed the 2 so you have an idea of what is happening. 

I am able to update the transaction in both v1 and v2. When I have it set to v2, the rules created as “ When a transaction is updated" do not apply.

**Comment by JC5** [comment]
I can't replicate this. A basic rule with a description trigger and a tag action works perfectly, both in v1 and v2.

**Comment by bartekd123** [comment]
I am able to reproduce it on my system, even re-created a rule, and recreated a transaction, so not sure if I am doing something not right. 

Is there a way you can switch the demo site to v2 temporarily so I can test on there and see if I see the same thing? I created an automation there, and its on v1, so it works.

**Comment by JC5** [comment]
Done!

**Comment by JC5** [comment]
Looks like it worked.

<img width="801" alt="Screenshot 2021-05-07 at 19 56 30" src="https://user-images.githubusercontent.com/5889984/117489836-9e71a780-af5d-11eb-8696-6154639ed08f.png">

**Comment by bartekd123** [comment]
Yup it’s working fine on yours. Maybe something else on my system.

**Comment by JC5** [comment]
Mmmm, that's tricky. Anything in particular in the logs perhaps? Is the rule not active perhaps?

**Comment by bartekd123** [comment]
Docker logs just show what I sent above. Rule is active. I do the following

- set to v1
- create rule (non strict, update, description contains “fireflyiii” set category “fireflyiii”
- create the transaction, description firefly (doesn’t match rule) > category not set as expected
- update transaction, set description to fireflyiii
- Category updated (since it’s on v1)
- change desc back to firefly and clear category (to prepare for v2 change)
- Set to v2 and restart docker container
- Update description to fireflyiii and save > see it didn’t update category (didn’t run rule)
- Set back to v1 and restarted docker
- Edit transaction and just save > it runs the rule as expected

Any way I can up the logging or see any other details on what it is doing to see what is different on my system?

**Comment by bartekd123** [comment]
I am playing around and see weird behavior, still testing. But is there any difference with how the "stop processing rules" checkbox behaves in v1 vs v2? Once I change it to a different category, and then update it again, it works. So I am thinking it is one of my rules that are set to stop processing, and it isn't processing the one I want. It should stop processing for that group only, and moves to the next group if I understand that checkbox, right?

**Comment by bartekd123** [comment]
So I don't think it is another rule that is overriding it, but the rules themselves not running on an update transaction sometimes. Can't quite put my finger on it. This is what I did to narrow it down.
 - For each rule group, I created one at the top that appends a different letter to the notes (i have 4 groups) for any new transactions (checked the stop processing so I know thats the only rule running for that group)
 - For each rule group, I created one at the top that appends a different letter to the notes (i have 4 groups) for any updates to transactions  (checked the stop processing so I know thats the only rule running for that group)

So for the first create, I can see it updating (the notes). When I pull up the transaction and edit it, and just hit save, I see the rules won't run (which I guess is expected since I am not modifying anything). But if I edit it, change something, the rule runs. Then subsequently if I open it again, edit and hit save (without making changes), it runs the rules.

I think the difference is, how it decides if something was changed. In the older versions, it looks like it allowed a rule change to count as a change.

I even tried creating a transaction the same way on the demo site (using my IOS shortcuts, so had to generate a token on that site). 

But I am still not able to reproduce it on the demo site, so probably something on the way I a doing it. I almost gave up, and will probably just end up changing my rules to be on create only. But thought I would get your thoughts on that (even though its not reproducible in demo).

**Comment by JC5** [comment]
I'll do some experiments with rule groups and update/change triggers. A rule changing the transaction will not trigger other rules, that's just asking for infinite loops. There are some cases where previous changes in a transaction aren't picked up in subsequent rules.

Could you share the details of the rules you use that don't work?

**Comment by bartekd123** [comment]
Thanks James. After you said that, I can see why you wouldn't want to have rules trigger other rules, and could cause a code loop where its updating the transactions and never reaches the end of the loop.

My example is, I have a rule that when a transaction is created a tag is added called new (that would be the update for the next one). I have another rule that when a transaction is updated, it triggers based on many description if it contains part of a restaurant, it sets it to the budget "takeout" and the category to "meal". 

I hope that helps. If it is just something happening in my system, don't spend too much time on it if you don't want to. If you need anything else, let me know.

**Comment by JC5** [comment]
Some experiments, for your reading pleasure. All rules are set to "on transaction update":

<img width="1029" alt="Screenshot 2021-05-09 at 08 03 30" src="https://user-images.githubusercontent.com/5889984/117562152-51402380-b08c-11eb-9409-93fbdb3f85ad.png">

Only the top rule fires, because the second rule will not match "has no tags".

Adding a third rule seems to work as expected. Nothing happens to new transactions, but once they're updated (manually!), it will do all the things (except tagB)

<img width="954" alt="Screenshot 2021-05-09 at 08 05 58" src="https://user-images.githubusercontent.com/5889984/117562211-b72cab00-b08c-11eb-99a1-88a1606dd5e6.png">

<img width="530" alt="Screenshot 2021-05-09 at 08 05 45" src="https://user-images.githubusercontent.com/5889984/117562217-bbf15f00-b08c-11eb-9975-f7818649b8f4.png">

Making a rule in between that forces the description to be "restaurant" will also trigger the budget/category rule, because the description has magically become "restaurant".

<img width="986" alt="Screenshot 2021-05-09 at 08 20 40" src="https://user-images.githubusercontent.com/5889984/117562477-b563e700-b08e-11eb-90d9-a7cac7d43519.png">

<img width="517" alt="Screenshot 2021-05-09 at 08 20 44" src="https://user-images.githubusercontent.com/5889984/117562478-b8f76e00-b08e-11eb-8ea0-9a247bcd9da2.png">

**Comment by bartekd123** [comment]
Thanks James. That all seems to work like it’s supposed to in your examples. I have mostly worked around my issue, so this bug can be closed out. 

One last question, if you see this. Is there any way to see if it’s an “update” or “create” rule from the list? Or have to go into each rule to see which it is?

**Comment by JC5** [comment]
Something for the new layout :+1:
