### ISSUE TITLE
more than 3 digit currency codes

### ISSUE THREAD

**Issue by JamborJan** [firefly-iii/firefly-iii#4759]
**Description**
The import extension [crypto-trades-firefly-iii](https://github.com/financelurker/crypto-trades-firefly-iii) allows to import transactions from Binance. Therefore it is required to add all currencies in firefly-iii. Right now firefly allows only 3 digit currency codes which are not enough for cryptocurrencies e.g. AAVE BETH COTI LINK IOTA etc.

**Solution**
It should be possible to have more than 3 digit currency codes. I'm not aware of any standard here. making it only 4 would also not be sufficient. There are things out there like OCEAN etc.

**What are alternatives?**
Firefly III and the extension are not usable for all currencies out there.

**Additional context**
N/A

**Bonus points**
N/A

**Comment by JC5** [comment]
ISO 4217.

**Comment by JamborJan** [comment]
Thanks for that hint. I guess that's rather for fiat currencies and not for cryptocurrencies, right? I don't see any of the cryptocurrencies which are in the default list of firefly-iii in ISO-4217 either. I did a quick check and as far as I can tell, there is no real standard for cryptocurrency symbols (aka codes).

**Comment by JC5** [comment]
I can extend the option to five or even seven letters, but it'll be a few versions before this will be implemented.

**Comment by JamborJan** [comment]
Thanks a lot @JC5. And thanks also for the great work you are doing. Much appreciated.
