### ISSUE TITLE
Add dot or underscrore in zeroes

### ISSUE THREAD

**Issue by azzamsa** [firefly-iii/firefly-iii#4770]
**Description**

![image](https://user-images.githubusercontent.com/17734314/118038521-69b88280-b399-11eb-9df7-ab5dc257645c.png)

I would like Firefly III to add a `dot` (`.`) or `underscore` (`_`), between zeroes.
So I don't need to count manually again. My currency has so many zeroes. 
I had to count the zero every time I make an input :(

**Solution**

Add a `dot` or `underscore` between zeroes while user typing the input.

![Peek 2021-05-13 03-10](https://user-images.githubusercontent.com/17734314/118038502-62917480-b399-11eb-9923-d52971155b51.gif)

**What are alternatives?**

Count manually.

**Bonus points**

Thanks a lot for Firefly III.

**Comment by JC5** [comment]
It's on the list!

**Comment by JC5** [comment]
This is now possible in the new layout, but will not be backported to the current layout.
