### ISSUE TITLE
Small Transactions API consistency issues

### ISSUE THREAD

**Issue by forcaeluz** [firefly-iii/firefly-iii#4771]
I am running Firefly III version 5.5.11, API 1.5.2.

**Description**
I'm playing around with the API (specifically the transactions API this time), and I found some inconsistencies I think:
- I think that if the number of decimal digits is 2, the amount should also have 2 decimal digits. But at the moment it has a lot.
- Most of the id's that point to another object (Like budget_id, bill_id, etc) are supposed to be integers in the documentation, but are strings. That is the case for at least: 

  - user
  - currency_id
  - foreign_currency_id
  - budget_id
  - category_id
  - source_id
  - destination_id
  - bill_id

**Comment by JC5** [comment]
Thanks for letting me know!

- This will not be changed. This may lead to rounding errors. Users are free to do this themselves when presenting the amount to the users.
- All ID's are strings, and will be displayed and presented as such. I spotted some mistakes here, and they'll be updated.
- This is to be compliant with the [specs](https://jsonapi.org/format/#document-resource-objects). When submitting data you're free to use integers (`4` versus `"4"`). However, I understand this feels inconsistent so I'll update the JSON API docs for submissions as well.

The API docs should be updated momentarily, although it may be a while for the CDN to update.

**Comment by forcaeluz** [comment]
- Thanks for the clarification. I will do the extra formatting on my side then.
- My guess was indeed that the design was to have all the id's as strings.

I'm using the openapi generator to generate Rust code for the API, and the generated code is strict when it comes to what is accepted. My problems are all in the data I receive, not in what I send. I changed the generated code by hand, but if the inconsistency is not there in the next version, my work to update to the next API version becomes easier :)  

Thanks for the quick fixes!
