### ISSUE TITLE
Problem with recurring transactions

### ISSUE THREAD

**Issue by zynexiz** [firefly-iii/firefly-iii#4774]
I have some issues with recurring transactions and assigning a category to it. When the transaction itself is added, the category is left out even if there is a category assigned to the recurring transaction itself. Also, I can't remove the category altogether (leave the text input blank) for the recurring transaction. If blanket out, it will revert to last saved category.

OS: CentOS 8 Stream
PHP Version: 7.4.19
Apache: Apache/2.4.37 (centos)
Firefly III: v5.5.11

**Comment by JC5** [comment]
Nice find, both issues will be fixed in the next release :+1:
