### ISSUE TITLE
Spectre Importer Install Failure

### ISSUE THREAD

**Issue by daprofessa19** [firefly-iii/firefly-iii#4781]
I am running Firefly III version 5.4.6

OK, so I was eventually able to upgrade Firefly III to the latest version that is packaged for YunoHost. Only to learn that the Spectre importer, which I use a lot, is now decoupled from the main software.

Well anyway, I'm trying to follow the instructions for installing the Spectre importer. I have successfully installed composer, but the next command in the documentation fails with the following error.

Composer version 2.0.13 2021-04-27 13:11:08

Command I ran:

composer create-project firefly-iii/spectre-importer --no-dev --prefer-dist spectre-importer 2.1.2

Output:

[InvalidArgumentException]
  Could not find package firefly-iii/spectre-importer with version 2.1.2 in a version installable using your PHP version, PHP extensions and Composer version
  .

**Comment by JC5** [comment]
What version of PHP are you running?

**Comment by daprofessa19** [comment]
PHP 7.3.28-1+0~20210503.84+debian10~1.gbp6819da (cli) (built: May  3 2021 11:59:15) ( NTS )

**Comment by JC5** [comment]
Sorry, you'll need 7.4 for the Spectre importer to work.

**Comment by daprofessa19** [comment]
Do you know how I should do this? Generally, I update system packages though the YunoHost interface, but of course I have root access to the server as well. I can also see that my system has PHP version 8.0 installed. But running php, executes that 7.3 version.

**Comment by JC5** [comment]
It can be loaded on a different machine, as long as it can reach Firefly III.
