### ISSUE TITLE
Layout v2: Transfers - foreign (destination) currency is not auto-selected

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#4782]
**Steps to reproduce**

1. New transfer
2. Source account: Select a USD account
3. Destination account: Select a EUR account

**Actual**

"(no currency)" is selected as the foreign currency.

**Expected**

EUR is selected as the foreign currency.

**Extra info**

* Firefly III 5.5.11 
* Chrome 90.0.4430.212

Note that it does not happen in the [v1 layout](https://demo.firefly-iii.org/transactions/create/transfer).

---

**v1 Screenshot**

![v1](https://user-images.githubusercontent.com/226712/119162040-99831c80-ba62-11eb-9df3-3f89f0b30d98.jpg)

---

**v2 Screenshot**

![v2](https://user-images.githubusercontent.com/226712/119162045-9ab44980-ba62-11eb-8981-eea3941b0a13.jpg)

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
Fixed in the new release.
