### ISSUE TITLE
New transaction - current balance of the account only appears after 2nd selection

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#4783]
**Steps to reproduce**

1. [New transaction](https://demo.firefly-iii.org/transactions/create/transfer)
2. Select a source or destination account (auto-complete then hit enter, or click)

**Actual**

The current balance (i.e. `... ($1.23)`) does not appear until selecting it a second time.

**Expected**

The current balance appears the first time.

**Extra info**

Happens in both v1 and v2.

* Firefly III 5.5.11 
* Chrome 90.0.4430.212

**Screen Recording**

![Screen Recording 2021-05-21 at 7 23 58 PM_gifski](https://user-images.githubusercontent.com/226712/119170468-f2a37e00-ba6b-11eb-8f87-e92a4ae2e876.gif)

**Comment by JC5** [comment]
It's not expected to, and I'll pick it up for the new layout.
