### ISSUE TITLE
"Include in net worth" option not avaliable/always ticked for expense accounts with layout v2

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#4797]
I am running Firefly III version 5.5.11 and I just saw that the checkbox "**Include in net worth**" when creating a expense account in **layout v2** is **gone**.
Honestly I never understood why I would do that anyway cause when I spend money on something (what would mean that it is "transfered to the expense account") that money of cause is not part of my own net worth anymore. So **I always unchecked this** option. So maybe correct me if I got something wrong in gerneral.
**BUT: When I create a new account** (with the new layout) **and then edit it** (where the old layout still comes up) **the box is ticked**!
So, I always have to create a new account using v2, then edit it to call the old layout and then uncheck the box. 

What leads me to two specific questions:
- what happens if  "Include in net worth" is ticked?
- if the old layout is completely disabled in the future, is this box always checked?

Thanks in advance for helping me with this question :)

**Comment by JC5** [comment]
That button does nothing for expense accounts.

**Comment by Styleflix** [comment]
okay, thanks. That explains it ^^
