### ISSUE TITLE
Recurring transaction "first date" is off by one week for weekly transaction with skips

### ISSUE THREAD

**Issue by aldenrogers** [firefly-iii/firefly-iii#4798]
**Bug description**
I am running Firefly III version 5.5.11, and my problem is that the "first date" selected in the UI doesn't match the date when a recurring transaction will occur (as displayed in "next due" when outside of the edit page), for weekly transactions with skipping.

**Steps to reproduce**
1. Create a recurring transaction
2. Pick some first date (e.g. June 2, 2021)
3. Set "Type of repetition" to "Every week on DAY" (e.g. Wednesday)
4. Set a nonzero "Skip" (e.g. 1 or 2)
5. Put whatever for the transaction information

The "Expected withdrawals" will show the next occurrence to be one week (even if skip is more than 1) after the selected "first date." In my example, this is Wednesday June 9.

**Extra info**
I'm running Firefox on linux. I noticed this on my local installation, but verified and tested more thoroughly on the demo site (5.6.0-alpha.1).

**Comment by JC5** [comment]
Nice find, thanks, will be fixed in the next release :+1:

**Comment by aldenrogers** [comment]
Awesome, thanks for all your work on this project!
