### ISSUE TITLE
[CSV-Importer] Mapping list not in alphabetical order

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#4807]
**Bug description**
I am running Firefly III version 5.5.11 & CSV 2.5.2, and my problem is:

When CSV-importer fetches the list of accounts to do the manual mapping, the list provided in the drop down is not sorted alphabetically. This was the case some versions ago but not anymore.
It seems the list of expenses accounts (for example) is starting with some of the latest ones added in alphabetical order, then it lists all the rest in alphabetical. But this small subset at the beginning should be part of the complete list and placed correctly.

**Steps to reproduce**
Not sure as I have only my instance to access and don't think you have a demo version of CSV-importer.
I would say after multiple runs of CSV-importer when it creates new entries for the mapping (and new expense or revenue accounts) this should appear.
I'm using CSV-importer for months now and almost never add new entries manually except for cash expenses (which is more rare than ever :) )

**Extra info**
Running the docker version on my synology with MariaDB.

Is it possible to use the debug page on CSV-importer too?

**Comment by MacPaille** [comment]
After checking this happens for both expense and revenue accounts in the list and it seems to show first the latest entries added with the CSV-importer.

Seems something goes wrong in the sorted list you are getting from FF via the API

**Comment by JC5** [comment]
It's currently using the "order" variable but this will be dropped for expense and revenue accounts in the next release.

**Comment by MacPaille** [comment]
What does this order variable do? Once dropped what will be the sorting of the list then?

**Comment by JC5** [comment]
It' used for asset accounts and liabilities only, and allows the user to sort accounts in the UI. It used to be available for other types of accounts but it's about to be removed. It will fall back to alphabet first.

**Comment by MacPaille** [comment]
Do you have an ETA on this? I suppose we can close this ticket as solution is already on its way :)

**Comment by JC5** [comment]
The bot will pick it up, I hope it's part of the next release. No ETA I'm afraid.

**Comment by JC5** [comment]
Whoops

**Comment by MacPaille** [comment]
No problem. As anyway all accounts are in the list it's not really a problem for me. Just as I have almost 600 mappings currently sometimes it's difficult to find the one I need :)

Thanks for the quick reply as always!

**Comment by MacPaille** [comment]
Hey JC5. Still no ETA when this list will be fixed?

**Comment by JC5** [comment]
2.6.1 is now released and includes the alphabetical list :+1:

**Comment by MacPaille** [comment]
I confirm it works well thanks a lot! 👍
