### ISSUE TITLE
Yunohost Support

### ISSUE THREAD

**Issue by emansih** [firefly-iii/firefly-iii#4808]
I was wondering what is the support status for Yunohost? 

One of my users is [facing issues while using Yunohost](https://github.com/emansih/FireflyMobile/issues/164). It appears that oauth does not return a valid redirect URI. 

When attempting to use PAT, it fails because [Yunohost is shipping Firefly III v5.4.6](https://github.com/YunoHost-Apps/firefly-iii/issues/39). 

Thanks.

**Comment by JC5** [comment]
It's in the process of being updated, actually 😁 . I'm not chasing this myself, @anmol26s is picking this up:

https://github.com/YunoHost-Apps/firefly-iii/pull/40
