### ISSUE TITLE
Does Firefly III support importing expense entries?

### ISSUE THREAD

**Issue by MetaBliss** [firefly-iii/firefly-iii#4822]
I am running Firefly III version 5.5.11.

Hi James, hope you're doing well.

I had a quick question for you. I currently have a "master tracker" in excel where I track every single transaction/item as an expense. This excel file has with the following fields:
- Date of Transaction
- Aggregate Vendor (e.g., Grocery Store, Health Food Store, Dollar Store)
- Specific Vendor (e.g., specific store name under the aggregate vendor - Krogers, Dollarama, etc)
- Region/Location (e.g., location of store or transaction - Dallas, Hamilton, etc)
- ID Category for transaction (e.g. GR for Groceries, VEH for vehicle related, CLT - for clothing related)
- Aggregate Item - high level category for the specific item I purchased (e.g., Fruits, Toys and Video Games) 
- Specific Item being purchased (e.g.,  Pears, Mario 64)
- Amount of the purchase (e.g., $6.99)
- Quantity of the purchased item (e.g., 1-N number)
- Buyer - person who bought it (e.g., John, Jane)
- Method of Payment (e.g., Credit Card, Cash, Points, etc)
- Notes

Can the firefly CSV Importer be used to import this kind of excel file (which I would turn into a .CSV file) to track all of my expenses? I was hoping I could import my entries in excel into Firefly because I saw Firefly has a "transactions" section. Firefly has a nice dashboard, so I'd love to be able to leverage some data analytics capabilities to see my expenditures over time. 

From what I've read online it seems like it can import bank statements but my tracker has much more detail in other areas the bank would not track and some of my purchases aren't on credit card , they could be cash as well so rather than painstakingly updating each entry, I'd like to reuse my existing tracker and import the data into firefly.

Please let me know if I can leverage my existing expense tracker (I have a similar tracker for payments coming in. The expenses is for payments going out, specifically what I bought, when and from who).

**Description**

**Extra info**

**Comment by JC5** [comment]
Welp lets continue on reddit i guess.

**Comment by MetaBliss** [comment]
Hi James, sorry I didn't understand your message. I only cross posted on Reddit cause I wasnt sure which would be more appropriate way to reach you and get a response to this question. Can you please advise? I'd love to leverage firefly for my data.
