### ISSUE TITLE
missing cron job for docker container

### ISSUE THREAD

**Issue by JonasB2497** [firefly-iii/firefly-iii#4823]
Hi,
I am using Firefly version 5.5.11 and have set it up with the official docker container (fireflyiii/core:latest) and mariadb.
It seems like there is no cron job active. The Recurring Transactions page shows the "missing cron job" banner and no transaction was made. I have already looked inside the container and in the Dockerfiles but haven't seen anything relevant there.

It would be useful to have the cron job integrated so that the user does not have to do it manually.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/advanced-installation/cron/#cron-jobs-in-docker

**Comment by JonasB2497** [comment]
Thank you for the link. I must have overlooked it.
