### ISSUE TITLE
v2 - Deleting multiple tags in one edit will only remove one tag

### ISSUE THREAD

**Issue by bartekd123** [firefly-iii/firefly-iii#4827]
**Bug description**
I am running Firefly III version 5.5.11, and my problem is:
When there are multiple tags on a transaction, editing the transaction deleting multiple tags at one time and submitting results in only one tag being removed.

**Steps to reproduce**
- Edit a transaction, and add 3 tags (I added one called 1 another called 2 and another called 3 for simplicity)
- Hit Update Transaction
- Re-open the transaction, and delete tags 1 and 2 back to back
- Hit Update Transaction
- Go back into it, you will see that tags 2 and 3 still exist (even though 2 was deleted above)
- Delete tags 2 and 3 and update transaction
- See that tag 3 is still there

**Extra info**
Docker
only happens in the new V2 UI

**Comment by JC5** [comment]
Thanks, I'll pick it up :+1:

**Comment by JC5** [comment]
Fixed in the new release.
