### ISSUE TITLE
Adding an attachment to a transaction gets the submission button stuck in a loop. [V2]

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#4835]
**Bug description**
I am running Firefly III version 5.5.12, and my problem is:

When I add an attachment to a transaction and submit the transaction, it gets stuck loading. This happens on both new transactions and old ones. It works fine in V1.

The transaction does actually get submitted. Firefly-iii just won't let you know it.

**Steps to reproduce**

1. Start making or editing a transaction.
2. Add an attachment to the transaction.
3. Submit the transaction.
4. See that the button spins endlessly.

![image](https://user-images.githubusercontent.com/21091510/120891079-96486e80-c5d4-11eb-94fe-98fe6d061023.png)

**Extra info**

Debug information generated at 2021-06-05 08:04:22 America/New_York for Firefly III version **5.5.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.12 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.5 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-06-01 00:00:00 |
| Session end | 2021-06-30 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 |

**Bonus points**

- [x] I searched and nobody reported this bug before
- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for letting me know, I'll check it out. Single attachment?

**Comment by death2cupbots** [comment]
> Single attachment?

Yes? It happens when I'm adding the first attachment to something or if I'm adding a second one later.

**Comment by Styleflix** [comment]
I can confirm this bug for my environment too. I wanted to open a case for several days now but always was too lazy ^^
Some additional information:
- after creating the transaction the loop appears. When interrupting the process by opening another page after like 3 seconds (while the process is still loading), the transaction gets saved but without the attachment
- when I then edit the transaction again and select the file for upload and save it, the loop appears again BUT when I give it about 5 seconds and open another page again (e.g. Expenses) the file is successfully saved - even though I interrupted the process

**Comment by JC5** [comment]
Fixed in the new release
