### ISSUE TITLE
V2 UI caches API requests so that changes aren't visible in the UI

### ISSUE THREAD

**Issue by alex6480** [firefly-iii/firefly-iii#4838]
**Bug description**
API requests on the account index page are cached so that any changes aren't visible in the new UI. 

**Steps to reproduce**
Create an account and go to the account index.
Change something on the account (like renaming it) and go back to the index.
The change will not be visible because the page uses the cached API result from the last visit

If you clear the cache (Indexed DB) the changes will be visible upon refreshing the page

**Extra info**

**Bonus points**

- I searched and nobody reported this bug before

**Comment by JC5** [comment]
This is all in progress, including a routine to reset the cache.

**Comment by JC5** [comment]
Pushed some code to develop, the idea is that an added cache key will make sure the cache can be invalidated whenever necessary.
