### ISSUE TITLE
Unable to set the opening balance for an asset account to zero?

### ISSUE THREAD

**Issue by jaylenw** [firefly-iii/firefly-iii#4846]
I am running Firefly III version 5.5.12.

**Description**

I created a new asset account and entered the incorrect initial opening balance. I then proceeded to change the opening balance to $0 and was unable to. I am able to increase and decrease the opening balance but can not set the opening balance to zero. All of transactions related to the account occur after the opening balance date. Am I doing something wrong? Thank you.

**Extra info**
 

Debug information generated at 2021-06-07 20:15:35 America/Los_Angeles for Firefly III version **5.5.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.12 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.6 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 751e6efd-b869-4187-b624-fbe693ccda2f |
| Using docker? | true |
| Telemetry | true |
| Layout |  |
| System TZ | America/Los_Angeles |
| Browser TZ | America/Los_Angeles |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-04-01 00:00:00 |
| Session end | 2021-06-30 00:00:00 |
| Session first | 2020-05-11 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 |

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
Yes
- I added a screenshot of the edit account page. If I were to change the opening balance to zero and click "Update asset account", the opening balance will remain at one.
![Screenshot from 2021-06-07 20-13-45](https://user-images.githubusercontent.com/6505395/121117388-e7bb4e00-c7cc-11eb-9c74-41055fff015c.png)

- I added log files 
No

- I was able to replicate the issue on the demo site.
Yes

**Comment by JC5** [comment]
Mmm, you can't set it to zero I see, but clearing both fields works on the demo site. Does that work for you as well?

**Comment by jaylenw** [comment]
Hello @JC5 thanks for looking into this! 

Clearing both fields on the demo site and my own instance does not work after clicking "Update asset account" for me. I see the following below. The input field reverts back to the previously saved value.

![tried-to-leave-opening-balance-blank](https://user-images.githubusercontent.com/6505395/121289955-ab562380-c89a-11eb-9fce-9a51dc4adae8.png).

And if I were to create a new asset account with the "Opening balance field" blank, the account creates successfully with no issues. Once I add a value to the  "Opening balance field" other than zero it saves with no issue. Once I enter zero into the "Opening balance field" and click "Update asset account" it remains at the previous saved value.

**Comment by JC5** [comment]
Weird. I'll make sure the code is a little more forgiven in an update. Thanks for letting me know!

**Comment by jaylenw** [comment]
@JC5 I added this video below to help explain what I am seeing.

https://user-images.githubusercontent.com/6505395/121292047-2967f980-c89e-11eb-8b75-3d098443c6b4.mp4

**Comment by jaylenw** [comment]
> Weird. I'll make sure the code is a little more forgiven in an update. Thanks for letting me know!

Oh okay! Thank you!!

**Comment by JC5** [comment]
I see what you mean in the video, thanks!

My Firefly III has a little X next to the date so I tend to clear that one too. But that's not enough, and it shouldn't be necessary in the first place.

If you set the amount to "" or 0, it should be removed. Will be picked up! :+1:
