### ISSUE TITLE
Store more version tags in docker hub

### ISSUE THREAD

**Issue by stavros-k** [firefly-iii/firefly-iii#4847]
**Bug description**
Please store at least 3 or more docker tags in docker hub. 
We at truecharts(https://github.com/truecharts/apps) (helm/k8s based apps for truenas scale) use static tags (not :latest) 
And update them once a week with github actions. 
With only one tag available right now it breaks the app until its updated again. Because the 5.5.11 tag no longer available.

**Comment by JC5** [comment]
I removed the old versions because of a security finding. Otherwise, they will stay available :+1:

**Comment by Ornias1993** [comment]
> I removed the old versions because of a security finding. Otherwise, they will stay available 👍

Please in the future: Don't.
You're breaking EVERY downstream that uses fixed versioning all at once. Including all helmcharts.
It's best practice.

What one does is file an advisory, not delete history.

**Comment by JC5** [comment]
I appreciate the issue, but I'm not leaving an insecure version of Firefly III online if I can help it. Luckily this doesn't happen very often.

**Comment by Ornias1993** [comment]
> I appreciate the issue, but I'm not leaving an insecure version of Firefly III online if I can help it. Luckily this doesn't happen very often.

Thank you for clearifying that.
With this attitude, we will be forced to deprecated supplying a helm-chart for  FireFly-III because we cannot guarantee our users it would stay working.

**Comment by JC5** [comment]
If I have a pressing security issue I'll be in touch, how would that work?

**Comment by JC5** [comment]
I'm happy to stick with best practices, and I am happy to be educated on what works and what doesn't. Thank you. I'll make sure old versions stay up.

If you need somebody to work on your communication skills, let me know.

**Comment by Ornias1993** [comment]
> If you need somebody to work on your communication skills, let me know.

Als jij je zooi verkloot voor anderen, kun je in elk geval een grote mond met persoonlijke aanvallen voor je houden.

**Comment by stavros-k** [comment]
Anyway, if in the future you found a security issue, and decide to delete recent tags (or not, it's up to you as you are the maintainer) 
Please, let me know if you can (or remember to do so) so I can also trigger our tag updates and let our users also know that there is a security issue and they should update.

Thanks
