### ISSUE TITLE
Missing docker images (same as #4010)

### ISSUE THREAD

**Issue by SerialVelocity** [firefly-iii/firefly-iii#4856]
**Bug description**
I am running Firefly III version `5.5.11`, and my problem is:

My host restarted a while about 4.5 days and all my transactions stopped importing.

Root cause: The `5.5.11` image disappeared from `fireflyiii/core` so firefly never started back up

**Steps to reproduce**

- Try to pull `5.5.11` from `fireflyiii/core`

This happened in the past (#4010) but wasn't as critical for me as it didn't affect my automated importing of transactions.

**Comment by JC5** [comment]
Yes, I'm aware. My apologies for the inconvenience. The image contained a critical security issue and I decided to remove it. It will not happen in the future again, not even should a similar issue occur.
