### ISSUE TITLE
LDAP sync to local user

### ISSUE THREAD

**Issue by gador** [firefly-iii/firefly-iii#4861]
I am running Firefly III version 5.5.11

**Description**

I've used Firefly in the past with a local user, using the `eloquent` login provider.
Now I've switched to LDAP. I can login with LDAP, but even with the setting of `ADLDAP_SYNC_FIELD: mail`, I cannot access the originally created (local) user with the same email.

In the user list there are now two users (id 1 and id 20) with the same username (my email adress). Is it possible to sync those, or use LDAP to sign into the local accout?

I have a ton of rules etc. in firefly and really do not want to recreate those..

Thanks in advance!

**Comment by JC5** [comment]
Weird. It's supposed to pick up on the local user. What happens when you delete the second user and try again.

Also, what happened to the other 18 users?
