### ISSUE TITLE
Shouldn't the split actions apply only to it?

### ISSUE THREAD

**Issue by lguima** [firefly-iii/firefly-iii#4863]
I am running Firefly III version 5.5.12.

**Description**
Clicking on Delete action under Actions menu in Split item header got the whole transaction deleted.

Thinking about UX, the actions location takes the user think that it's applied to it, not to the whole transaction, since there's another Actions menu for that.

**Does make sense to leave only actions related to Split items in their respective Actions menus?**

![firefly-split-item](https://user-images.githubusercontent.com/1562097/122680154-3f41bc80-d1c4-11eb-9b3b-2785bd40ef8d.PNG)

**Comment by JC5** [comment]
Good call, I’ll pick it up for the new layout 👍
