### ISSUE TITLE
Saving transaction doesn't save all information correctly (Tags, Notes) - v2 layout

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#4864]
**Bug description**
I am running Firefly III version 5.5.12 and my problem is that in some cases saving a transaction does not save some information.
To be more specific:
- When I enter more than 3 tags, after saving the transaction, the last tag is removed (e.g. I enter 4 Tags, only 3 are saved. When I enter 6, 5 are saved)
- Sometimes (didn't figure out when specificly) the last character in the Notes field is missing (e.g. I enter "this is a test" only "this is a tes" gets saved)

**Steps to reproduce**
Tags-Issue:
- Create a transaction
- Enter more than 3 tags
- click save

Notes-Issue:
- Create a transaction
- Enter something in the notes field
- click save
(does not reproduce every time)

**Extra info**
Im am using the v2 layout, also docker and an apache reverse proxy

**Bonus points**
- I searched and nobody reported this bug before
- I was NOT able to replicate it on the demo site https://demo.firefly-iii.org/ (maybe because of the old layout)

**Comment by JC5** [comment]
Thanks for letting me know, I'll check it out
