### ISSUE TITLE
Switch pie charts to percentages

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#4865]
**Description**

I was thinking of a minor tweak for the Firefly iii UI where I can choose whether the pie charts display the amount of money for the corresponding category, budget, account, etc. or the percentage

**Solution**
Implemeting a switch for toggling between amount of money and percentages. Could be located in the v2 layout where I can also adjust the time span or alternatively in the settings. For docker environments it also could be adjustable via the .env file.

**Comment by JC5** [comment]
I'm going to drop the pie charts entirely, but I'll see if I can add something like this. It's not going to be an option though, it either works or it doesn't.

**Comment by Styleflix** [comment]
You gonna drop them entirely? That's a pity to hear. I actually like the overview - it always gives me a good sense of how much I spent on a particular category, for example.
But lets see what your future updates will bring us :D
Thanks for the reply anyway

**Comment by JC5** [comment]
Probably something like [treemaps](https://www.google.com/search?q=treemap+chart&tbm=isch) or a [sankey diagrams](https://www.google.com/search?q=sankey+diagrams&tbm=isch) 👍🏻

**Comment by Styleflix** [comment]
oh that sounds cool too :D

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6304
