### ISSUE TITLE
Paperclip icon doesn't get removed after removing the attachment

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#4866]
**Bug description**
I am running Firefly III version 5.5.12 and my problem is that when I delete an attachment of a transaction, the paperclip icon stays in the transactions list in front of the transaction.

**Steps to reproduce**
- Create transaction
- Add attachment
- See paperclip icon in the transactions list
- Edit the transaction and remove the attachment
- Open up the transactions list again and see that the paperclip icon is still in front of that transaction

**Bonus points**
- I searched and nobody reported this bug before

**Comment by JC5** [comment]
v1 or v2? If it's v1 I'm not going to fix it :P

**Comment by Styleflix** [comment]
Oh sorry, forgot to mention that. It's v2. Otherwise I wouldn't have created a bug report too ;)

**Comment by JC5** [comment]
Ah yes, but it's the old-style layout right?

**Comment by Styleflix** [comment]
Ah, of course. Since the expenses page still appears with the old layout. My bad - didn't think of that tbh ^^

**Comment by JC5** [comment]
Haha no worries!
