### ISSUE TITLE
Cannot login to LDAP without ADLDAP_ADMIN

### ISSUE THREAD

**Issue by francescocarzaniga** [firefly-iii/firefly-iii#4876]
**Bug description**
I am running Firefly III version 5.5.12, and my problem is:

I cannot login using OpenLDAP if I do not populate admin credentials. I did not understand from the documentation whether this is intended or not, but it is unusual behaviour, I should be able to bind with current user instead of admin.

**Steps to reproduce**
Configure Firefly as from the documentation for OpenLDAP.
Populate admin credentials, login with normal user works.
Delete credentials, login no longer works.

**Extra info**
It seems that Firefly believes there is no username and password in the login input. Indeed debug logging shows:

```
if (is_null($username) && is_null($password)) {
    // If both the username and password are null, we'll connect to the server
    // using the configured administrator username and password.
    $guard->bindAsAdministrator();
} else {
    // Bind to the server with the specified username and password otherwise.
    $guard->bind($username, $password);
}
```
with `bindAsAdministrator()` being chosen in the if clause.

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files

**Comment by JC5** [comment]
Thanks for letting me know. What you're pointing out is code from the library I'm using, and there's not much I can change about it. I am migrating to a new one however and you can check out some details here:

https://old.reddit.com/r/FireflyIII/comments/ny4i1c/help_me_test_the_new_ldap_login_code/
