### ISSUE TITLE
Last activity date on asset accounts page [v2]

### ISSUE THREAD

**Issue by dealanis** [firefly-iii/firefly-iii#4898]
**Bug description**
I am running Firefly III version 5.5.12, and my problem is:

Searched around but couldn´t find something related to this..

The Asset Accounts page is missing the "last activity" date on the new v2 layout. This was a big reference for me to quickly identify or order accounts by it and target outdated ones and bring all of them to date. Also but not that important, really missing the period dates on the top bar now hided on a menu.

**Steps to reproduce**
Asset accounts page on v1
![image](https://user-images.githubusercontent.com/1350480/124855735-06009f00-df6f-11eb-92bf-7704a11b9a1c.png)

Asset accounts page on v2
![image](https://user-images.githubusercontent.com/1350480/124856296-e0c06080-df6f-11eb-9fd3-c4a97db8d021.png)

**Comment by JC5** [comment]
It's there in my version, but maybe I added it after releasing 5.5.12. So no worries, it'll be there!

**Comment by dealanis** [comment]
That's great! thank you!
