### ISSUE TITLE
"Could not render view" when creating rule triggers

### ISSUE THREAD

**Issue by Tordarus** [firefly-iii/firefly-iii#4899]
**Bug description**
I am running Firefly III version 5.5.12, and my problem is:
I cant add new triggers when creating a new rule. It only shows the warning "Could not render view."
Every time I click the add trigger button, another instance of this text is appended.

**Steps to reproduce**
Click on Automation -> Rules -> New Rule. The "Could not render view" text is already visible on the screen once.

**Extra info**
OS: Linux Mint 20
Browser: Firefox 89.0.1

Debug information generated at 2021-07-08 12:45:06 Europe/Berlin for Firefly III version **5.5.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.12 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.16 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | fddc0eb0-d3ff-4d95-8381-0bb3d8821c92 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-07-01 00:00:00 |
| Session end | 2021-07-31 00:00:00 |
| Session first | 2019-11-01 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0 |

**Bonus points**
- The log files do not show any stack trace
- I searched and nobody reported this bug before
- I was not able to replicate it on the demo site
- Disabling all Firefox add-ons or using chromium could not solve the issue either
- Screenshot with open debug console:
![screenshot](https://user-images.githubusercontent.com/1444581/124910234-a8f6fe80-dfeb-11eb-8e5f-bb76b5d4d632.png)

**Comment by JC5** [comment]
Could you share your log files? They should contain the error.

**Comment by Tordarus** [comment]
Sure thing but I couldn't find any errors in there.
Here is the log file for today. I tried to trigger the error multiple times, but it doesn't seem to log them in any way.

```
[2021-07-09T14:12:53.876477+02:00] local.INFO: AUDIT: Show login form (1.1). (95.163.170.4 -> GET:https://finance.tordarus.net/login) [] []
[2021-07-09T14:12:56.034539+02:00] local.INFO: AUDIT: User is trying to login using "tordarus@protonmail.com" (95.163.170.4 -> POST:https://finance.tordarus.net/login) [] []
[2021-07-09T14:12:57.637555+02:00] local.INFO: AUDIT: User "tordarus@protonmail.com" has been logged in. (95.163.170.4 (tordarus@protonmail.com) -> POST:https://finance.tordarus.net/login) [] []
[2021-07-09T14:12:57.950933+02:00] local.INFO: AUDIT: User visits homepage. (95.163.170.4 (tordarus@protonmail.com) -> GET:https://finance.tordarus.net) [] []
```

**Comment by JC5** [comment]
There should also be a log that contains what Firefly III is doing. Check out:

https://docs.firefly-iii.org/firefly-iii/faq/other/#how-do-i-enable-debug-mode

**Comment by Tordarus** [comment]
Sorry for answering so late. But I was able to fix this issue on my own. There were some files in the storage directory with wrong file permissions. Firefly wasn't able to read those files. After recursively setting all file permissions, everything is working again
