### ISSUE TITLE
Reconcile account based upon optional date field

### ISSUE THREAD

**Issue by pwsoftwaredesigns** [firefly-iii/firefly-iii#4900]
**Description**
Add the ability to reconcile an account based upon a date field other than the main transaction date (e.g. "Processing date).  This would be useful because, for example, as I buy something, I add it to firefly under the date I actually made the purchase.  However, if this happens to be on a month boundary (e.g. May 31st), the transaction will not appear in my bank statement until the next month (e.g. June 1st). This causes a problem when reconciling to the bank statement for a particular month of transactions.

**Solution**
Add a drop-down to the reconcile account page to choose what date field to search/sort by.

**What are alternatives?**
Unknown.  But perhaps there is a way to approach this problem already in firefly? (please let me know if there is)

**Comment by JC5** [comment]
I'll see what I can do but probably not. I know about the issue but it's a lot of work for a small fix.
