### ISSUE TITLE
Reconcile accounts page should remember dates and amounts for the current session

### ISSUE THREAD

**Issue by pwsoftwaredesigns** [firefly-iii/firefly-iii#4902]
**Description**
When reconciling an account, it is often necessary to edit/add/remove a transaction then continue reconciling using the same date range and start/end amounts.  However, once you leave and re-enter the reconcile account page, it forgets the dates and amounts.

**Solution**
For the duration of the login session, remember the values entered in the reconcile accounts date and amounts fields.

**Comment by JC5** [comment]
It's getting an overhaul in the new release, and this was on my list already :+1:
