### ISSUE TITLE
Add rule triggers for optional fields

### ISSUE THREAD

**Issue by pwsoftwaredesigns** [firefly-iii/firefly-iii#4903]
**Description**
It would be useful to have rule triggers available for optional fields.  For example, I wanted to add a rule for the "Processing Date" field if it is empty, but could find no available triggers for this.

**Comment by JC5** [comment]
Good idea, it's on the list.

**Comment by pwsoftwaredesigns** [comment]
I wanted to add something to this suggestion and will use "Processing Date" as an example.  I use the "Date" field to store when I actually made the purchase and the "Processing Date" field to store the date that it posted within my bank statement. Usually, the processing date is two days after the purchase date unless that happens to fall on a weekend, in which case the processing date will be the following Monday.  I am wondering if the trigger rules allow (or can be made to allow) for math/script operations to be performed to automatically set the field based upon the aforementioned conditions.
