### ISSUE TITLE
Add confirmation button for current account balance

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#4906]
**Description**

It would be great to have a Firefly III feature for confirming the ccurrent balance of an asset accounts that later on I can be sure that the balance at a specific time was correct.
For example I sometimes forget to add a transaction after I bought something. Or when I create one I select the wrong account. Later on I recognise that the actual balance for my bank account or my cash wallet is not matching the balance in firefly but then it mostly takes some time to figure out when the mistake happened.

**Solution**

If there was a button to confirm the current balance for an account (for example after checking the accutal bank account or counting the bills in my cash wallet) it would be a lot easier to find mistakes after they happend.
After clicking the button, there could appear an entry in the transactions list showing the correct and confirmed balace at this time

**Comment by JC5** [comment]
Sorry, all I can offer you is the reconciliation function and the audit report.
