### ISSUE TITLE
Re-enabling introduction guidance returns "undefined" on some pages

### ISSUE THREAD

**Issue by kittenswolf** [firefly-iii/firefly-iii#4912]
**Bug description**
I am running Firefly III version 5.5.12 (latest as of writing), and every time I click the question mark icon in the upper right side on the index page and click "You can also re-enable the introduction guidance.", a browser popup appears reading:
![grafik](https://user-images.githubusercontent.com/26834699/125206247-964c2600-e286-11eb-9811-80259cace5df.png)

In the network tab, I can see the following activity:

![grafik](https://user-images.githubusercontent.com/26834699/125206278-c267a700-e286-11eb-8fe0-8dd232552521.png)

This function is also broken on other pages, such as `/recurring/create` and `/piggy-banks`. However, it works on (at minimum) `/accounts/expense`.

**Steps to reproduce**
See above

**Extra info**
Strangely, this functionality worked briefly and broke after only a few hours when I tried it again. I did not change anything with the setup.

I am using Firefox 89.0.2 (latest as of writing) and Windows 10.
Debug information generated at 2021-07-11 18:22:53 UTC for Firefly III version **5.5.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.12 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.6 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | bc37c766-5311-4e98-b4b2-144952b576df |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ |  |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-07-01 00:00:00 |
| Session end | 2021-07-31 23:59:59 |
| Session first | 2021-07-11 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0 |

**Bonus points**
Relevant log excerpt:
```
<my IP> - - [11/Jul/2021:18:24:31 +0000] "POST /json/intro/enable/index/ HTTP/1.1" 301 526 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
<my IP> - - [11/Jul/2021:18:24:31 +0000] "GET /json/intro/enable/index HTTP/1.1" 200 2902 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
```

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
Not really an idea why it doesn't work, I added some debug logging. Do you run on a port different from 443 or 80, perhaps?

**Comment by kittenswolf** [comment]
Indeed, I run it on port 8080

**Comment by JC5** [comment]
Thanks. I'm not going to fix this, I'll just make sure it doesn't happen in the new layout.
