### ISSUE TITLE
use payment date instead of transaction date durring reconciliation

### ISSUE THREAD

**Issue by Vaarlion** [firefly-iii/firefly-iii#4920]
**Description**

Some of my transaction use payment date when the purchase date is earlier than the billing date (example ChargeMap EV charging bill)
When doing reconciliation, the transaction don't show up while the selected time-frame include the payment-date date
I would like to be able to have it show up so i can avoid doing a reconciliation over a large time-frame.

**Solution**

having no idea of what's happening in the backend, i would think reconcile could 'just' use that date instead for it's math ?

**What are alternatives?**

i could create a "purchased date" and put the actual transaction date to the billing date, but this is significantly harder as i need to set a date when creating the transaction, which i mostly can't guess at that time.

**Additional context**

**Bonus points**

no bonus point :D

**Comment by JC5** [comment]
I'll see what I can do for the next layout and this feature :+1:

**Comment by Vaarlion** [comment]
sorry i didn't see https://github.com/firefly-iii/firefly-iii/issues/4900 while doing some search in the existing issue
