### ISSUE TITLE
Best way to extend CSV Importer

### ISSUE THREAD

**Issue by csrui** [firefly-iii/firefly-iii#4921]
Hi there,

I have tested Firefly and CSV importer and I like it. 
I might be able to spare some hours for contributions to this project so I have two questions.

- Why are you removing the custom banks options from the importer and are they going somewhere else?
- How would I go about adding something extendable like that to format (cut the fat) CSVs from banks? I would like an importer to handle all CSV processing and not need to have extra tools for that. 

The two questions are more or less just one but I feel it’s starting point for discussion.

**Comment by JC5** [comment]
Hey, thanks for the questions.

Converting a CSV file into JSON to submit to Firefly III is a fun excercise with plenty of challenges and bugs to fix and exceptions to handle. If you run into anything, feel free to create a PR or suggest a fix!

I want to replace all bank-specific options and replace them with generic options that everybody can use. For example, the ability to split a column based on a specific value, merge columns together or replace data in columns. I'm not sure yet how to do this and how to present it to the user. If you have ideas, let me know.

However, I'm not going to commit to the nightmare that is extending the CSV importer to fix all of the terrible stuff banks do to their CSV files. I'm not going to take upon my shoulders the added burden of all of those banks out there that seem to believe they can create the most insane incompatible CSV files and get away with it. It's not my problem. This includes, but is not limited to:

- Adding lots of whitespace 
- Adding extra header lines
- add text to the start or the end of the file
- format numbers to be human readable
- not including enough information to make transactions unique

If you need fixes like these before your files can be processed, you need to talk to your bank.

Hope that gives you an answer.
