### ISSUE TITLE
Allow external URL to be configured

### ISSUE THREAD

**Issue by Flightkick** [firefly-iii/firefly-iii#4933]
**Description**

I would like to run Firefly III behind a reverse proxy under a specified path, e.g. `/firefly`.
Currently, this gives some issues. The application can be reached but redirects will have their `Location` header set with root `/` as the base url.
This results in:
 `https://mydomain.nl/firefly` redirecting to `https://mydomain.nl/login`
instead of:
 `https://mydomain.nl/firefly` redirecting to `https://mydomain.nl/firefly/login`

Some reverse proxies support rewriting the Location header from the response but setting the external url on application level would be nicer.

**Solution**
Laravel supports setting the root URL. Since Firefly already has a directive for `APP_URL` in it's config, I'd propose using that config.
I've already got a solution available, will post the PR after posting this issue for reference.

**What are alternatives?**
- Possibly passing a X-Forwarded-* header to Laravel but no official RFC compliant solutions exist for a base path so these would be custom implementations.
- Accepting some reverse proxies might not be able to host firefly under a custom path and fall back to a subdomain instead.

**Additional context**
I was specifically trying to get this to work with Traefik. Stumbled upon this issue: https://github.com/firefly-iii/firefly-iii/issues/2279
The solution from the PR should solve that as well. You only need to configure Traefik to strip the base path before forwarding it to Firefly.

**Bonus points**

Here's a drawing of Firefly III, thanks for confirming that I made a correct choice by not pursuing a career in art. It's cursed.
![image](https://user-images.githubusercontent.com/8693699/126771873-d78a5dd0-1454-48eb-9c5c-4e14911d6473.png)

**Comment by JC5** [comment]
No. See https://github.com/firefly-iii/firefly-iii/discussions/4534
