### ISSUE TITLE
Images in the readme are broken

### ISSUE THREAD

**Issue by Flightkick** [firefly-iii/firefly-iii#4935]
**Bug description**
Images in the readme refer to `https://www.firefly-iii.org/static/screenshots/` these resources do not seem to be served anymore. Which has caused the images to break.

**Steps to reproduce**
Check the readme at: https://github.com/firefly-iii/firefly-iii

**Extra info**
I've prepared a PR with a proposed solution. This issue is for reference/tracking.

**Comment by JC5** [comment]
Fixed :+1:
