### ISSUE TITLE
Rule trigger "Description contains ..." does not match values with double spaces

### ISSUE THREAD

**Issue by caseymullineaux** [firefly-iii/firefly-iii#4938]
I am running Firefly III version 5.5.12.

**Description**

When a transaction is saved that contains multiple consecutive spaces in its description, it cannot be matched to a rule trigger if the value of the trigger also includes those spaces.

At a guess, it looks like when the query runs, it's escaping or trimming the space characters which alters the value of the search causing it to return no results.

**Extra info**

_Screenshot 1:_
The transaction has been imported from CSV and has been saved with multiple consecutive spaces in the description (in this case three of them)
![image](https://user-images.githubusercontent.com/25874787/126889286-c5d4eb58-7642-440a-97c0-8ebcb29ec463.png)

_Screenshot 2:_
Wherever this transaction is displayed within other areas of Firefly III, the additional spaces look to have been removed.
![image](https://user-images.githubusercontent.com/25874787/126889328-e18d642a-6af4-45b9-9ecc-4cd57f75e9db.png)

_Screenshot 3:_
When entering my search criteria (including the additional space characters) it _appears_ to find the transactions I want this rule to apply to. However, notice the absence of additional space characters in the suggestions.
![image](https://user-images.githubusercontent.com/25874787/126889026-8f029997-7639-47ab-a2e4-46756f59c98f.png)

_Screenshot 4:_
Looking for matching transactions on a trigger value that includes the additional spaces returns no results.
Looking for matching transactions on a trigger value that is suggested by the UI (as shown above) also returns no results.
![image](https://user-images.githubusercontent.com/25874787/126889039-99b8aa65-1fcb-4f44-9438-96cf06ab2735.png)

_Screenshot 5:_
The transaction can be searched and found successfully if the trigger value does not seek to look for a value that contains multiple space characters
![image](https://user-images.githubusercontent.com/25874787/126889603-9395ee3b-e43e-4143-8e95-759d7d3774de.png)

--> 

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- [X] I added a screenshot
- [ ] I added log files 
- [X] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Thanks for the extensive issue!

So first of all, the fact that spaces aren't displayed is a "limitation" of HTML. It will always bring back the number of visible spaces back to 1. This is why the suggestions and other fields will not show these extra spaces, even when they are found. 

Ultimately though, the [library](https://github.com/gdbots/query-parser-php) I use to search filters away multiple spaces. This isn't something I can fix.

**Comment by caseymullineaux** [comment]
Bugger.

For what it's worth, I was able to get around the issue by encapsulating the search term in double quotes.
