### ISSUE TITLE
Themes and Credit Card

### ISSUE THREAD

**Issue by hiagodotme** [firefly-iii/firefly-iii#4946]
I am running Firefly III version 5.5.12.

**Description**
First, the project is very well built, congratulations! I think it would be nice to add the option for the user to choose your template, the AdminLTE itself already provides several.

I would like to know if there is an example of how I can control credit cards.

**Comment by JC5** [comment]
Thanks! I'm working on a new layout, but themes won't be an option. Dark mode will be, if it's available.

What are you looking for in regards to credit cards, exactly?

**Comment by JC5** [comment]
Just add it as a normal asset account is the easiest.

**Comment by davidzlewis** [comment]
@JC5 I was having the same question. I did see adding it as an asset account, but then when you fill in the balance and virtual balance, it shows up as an account to draw money from with a positive balance, assuming I have credit left on the card. I was a bit confused at first on which was which for the balance and total credit. I feel like this would be better suited as a liability, where it could be classified as a debt. Would it be possible to also include the monthly minimum payment as an auto generated bill from that as well?

**Comment by JC5** [comment]
Not yet, but I'm picking up stuff like that after the new layout. In the mean time, use the virtual balance to indicate your limit.

**Comment by maniacaris** [comment]
> @JC5 I was having the same question. I did see adding it as an asset account, but then when you fill in the balance and virtual balance, it shows up as an account to draw money from with a positive balance, assuming I have credit left on the card. I was a bit confused at first on which was which for the balance and total credit. I feel like this would be better suited as a liability, where it could be classified as a debt. Would it be possible to also include the monthly minimum payment as an auto generated bill from that as well?

I'm a new user and struggled with wrapping my head around it too. The way I use credit cards, it's may as well be convenient cash with extra perks (i.e. rewards/cash back/points). The credit limit is irrelevant. When I make a purchase on my credit card, I "withdraw" the amount from the credit card and send it nowhere (don't use the expense accounts feature). When I make payments, I transfer the money from my checking account to my card, which brings the balance back up to zero. JC might have different ideas but this is what has been working for me.
