### ISSUE TITLE
Docker image fireflyiii/core:latest points to 5.5.12 instead of 5.5.13

### ISSUE THREAD

**Issue by siccovansas** [firefly-iii/firefly-iii#4949]
**Bug description**
It seems that the Docker image `fireflyiii/core:latest` points to 5.5.12 instead of 5.5.13.

**Steps to reproduce**
Run `docker run --rm -it fireflyiii/core:latest bash` and see a message saying:
> Thank you for installing Firefly III, v5.5.12!

As always, thanks for developing Firefly!

**Comment by JC5** [comment]
Really? That's silly of me. Will pick it up!

**Comment by JC5** [comment]
Fixed :+1:
