### ISSUE TITLE
Reports - Expense details also shows transfers

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#4952]
**Bug description**
I am running Firefly III version 5.5.12, and my problem is:

In /reports/default/, in the expenses box, when clicking on the information icon, the popup shows transfers between my accounts.

I was expecting to see only expenses.
It works ok for income.

**Extra info**
I'm using docker.

**Bonus points**

- I have added a screenshot of the demo site. (double bonus point? :) )
![image](https://user-images.githubusercontent.com/1318140/127541385-363609ab-ff7d-4c4b-b813-76dd9b837d7b.png)

**Comment by JC5** [comment]
Thanks for letting me know. I'm going to pick this up in the new layout :+1:
