### ISSUE TITLE
CSV Importer: BIC and IBAN in one column? (Triodos CSV)

### ISSUE THREAD

**Issue by Grovespaz** [firefly-iii/firefly-iii#4958]
I am running Firefly III CSV Importer version 2.6.0.

**Description**
Hi, I'm exploring Firefly III. My ING statements imported just fine, but there's no configuration yet for Triodos (a different Dutch bank) so I'm looking into creating one.
However, I noticed that Triodos lumps the BIC and IBAN into one column. Is this something that the CSV importer is already able to handle or would this require a code change?

**Extra info**
Examples of column data:
```
"ABNANL2A NL38ABNA0566198479"
"INGBNL2A NL27INGB0000026500"
"DEUTDEFF DE88500700100175526303"
```

**Bonus points**
- I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by JC5** [comment]
This isn’t something the CSV importer can handle unfortunately, it’s something you’ll have to clean up before you import your file.

**Comment by Grovespaz** [comment]
Would you accept a pull request adding a column type?

**Comment by JC5** [comment]
No. For the time being, I'm not accepting any pre-processing PR's. I hope to introduce a generic column thing in the near future.

**Comment by Grovespaz** [comment]
Alright, thank you :)
Is there an issue I can track for that? I could close this one then.

**Comment by JC5** [comment]
Created https://github.com/firefly-iii/firefly-iii/issues/4970 :+1:
