### ISSUE TITLE
Automatic monthly budget amounts not showing up

### ISSUE THREAD

**Issue by TitaniumCoder477** [firefly-iii/firefly-iii#4960]
I am running Firefly III version 5.5.13.

**Description**
Yesterday I deployed a brand new instance of Firefly, and I setup my bills and budgets. Today, being the 1st of the month, I expected my budgets, which are setup with monthly automatic amounts, to show. But they are still all zero. Did I do something wrong? (It looks like I did everything correctly based on https://docs.firefly-iii.org/firefly-iii/concepts/budgets/)

**Extra info**
Server: Debian 10
Browser: Brave (based on Chromium)

Debug information generated at 2021-08-01 12:02:06 America/New_York for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.9 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | d0d25ff4-b55a-4380-bdb2-5fa8afef59ac |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-08-01 00:00:00 |
| Session end | 2021-08-31 23:59:59 |
| Session first | 2021-07-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36 |

Figure 1: Screenshot of budget configured for 80 monthly
![image](https://user-images.githubusercontent.com/26101661/127777685-67b45b16-1709-4111-b8b5-6e2eca718479.png)

Figure 2: Screenshot of budgets configured for automatic monthly amounts but not showing anything
![image](https://user-images.githubusercontent.com/26101661/127777711-2cd1c82b-5776-4a40-8ab9-3a2fde5ecb97.png)

**Bonus points**
- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added screenshots

**Comment by JC5** [comment]
Is the cron job running?

**Comment by TitaniumCoder477** [comment]
Hmmm. I don't seem to have one. I checked under root and www-data. Is there another account I should be checking?

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/advanced-installation/cron/
