### ISSUE TITLE
Search should be case insentitive

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#4961]
**Bug description**
I am running Firefly III version 5.5.12, and my problem is that `Bank Of America` is not found when I type `bank of america`.

**Steps to reproduce**
The search and auto-fill are case sensitive, that does not really make sense for such an application and would be actually really convenient if that would NOT be the case (kinda no pun intended....)

**Comment by JC5** [comment]
Please read the faq and use the search.

**Comment by chevdor** [comment]
Thanks for the fast answer.
Reading the FAQ I see:

> This happens when the underlying database is Postgres, which is case sensitive by default. You may run into this when searching for FLO doesn't yield flower.
> There's not much i can do about this.
 
I think this is a little light and while I am no Postgresql expert, I am pretty sure other projects need and manage to do case insensitive searches. Also if the issue is the default settings, maybe we can change the defaults ?

For instance, are you aware of any issue using Postgres v12 and benefit from the native support for case insentive collations ?

**Comment by JC5** [comment]
What are you asking exactly?

**Comment by chevdor** [comment]
> are you aware of any issue using Postgres v12 and benefit from the native support for case insentive collations ?

**Comment by JC5** [comment]
Feel free to set it up for your database, I know of no issues.

**Comment by chevdor** [comment]
I will give it a shot then. It sounds like it could be a simple solution to fix the issue. If this topic landed in the FAQ, I guess I am not the first to ask.

**Comment by JC5** [comment]
No you're not. So far, I found little else except "write custom queries for postgres" which isn't possible unfortunately. So I'm curious to hear what you'll find!

**Comment by JC5** [comment]
Indeed, that works, also for other query languages. Dropping stuff to lower case isn't feasible for specific languages where the lower case character (and meaning) is different.

**Comment by emam0** [comment]
How about creating an additional column for the "searchable_name"? so in addition to the column `name` where you store the value as the user have entered it, you always save the lower-case value to the `searchable_name` column. This gives you the benefit of making any arbitrary input sanitation (e.g. remove punctuation or convert accented characters to non-accented, replace consecutive spaces with single space, etc...), and as long as you run the same input sanitation on the search input you'll be able to make the search feel more natural to the user.
It's a common trick used when you need to process user input in a consistent manner while preserving the original format for user communication.

**Comment by JC5** [comment]
A separate search index / engine may also be something to look at.
