### ISSUE TITLE
Payment providers / aggregators cause "wrong" opposite account matching

### ISSUE THREAD

**Issue by Grovespaz** [firefly-iii/firefly-iii#4969]
I am running Firefly III version 5.5.12.

**Description**
We often buy goods through webshops. It's become common for Dutch webshops to route such payments through a payment provider such as Mollie (which will fulfill a role similar to Stripe or Paypal). Due to the nature of the iDeal payment system, the opposite IBAN will therefor have Mollie's IBAN filled in in the CSV export.
However, the ING bank exports will have the name of the webshop in the opposite account name.

This leads to statement exports like this:

| Opposite account name | Opposite account IBAN |
|-------------------------|------------------------|
| Webshop A                   | NL51DEUT0265262461 |
| Webshop B                   | NL51DEUT0265262461 |
| Webshop A                   | NL51DEUT0265262461 |
| Webshop C                   | NL51DEUT0265262461 |

However, Firefly will change all of these transactions to contain the name of Webshop A, leading to a whole mess when categorizing our transactions.
What is the best way to solve a situation like this? Is it to create a rule that blanks out the destination IBAN for each of these payment providers and hope they don't change account numbers at some point without me discovering? Or is there a more clever way?

**Bonus points**
- I have read the FAQ at https://bit.ly/FF3-FAQ

**Comment by Grovespaz** [comment]
This issue was accidentally submitted while I was still drafting it, so if you got an email notification it may be incomplete. Sorry about that.

**Comment by JC5** [comment]
If you ignore the shop's IBAN, you could map by name perhaps?

I know that most banks are slowly planning to change these references to the actual shop behind them. So the problem may solve itself in the near future.

**Comment by Grovespaz** [comment]
The issue is that a lot of shops use this, even shops I haven't bought from yet. If I have to be on the lookout with each import it becomes quite a menual chore.

Could I instead set up a rule that clears the IBAN when it's that IBAN? Or will the match already have occured at that point?

**Comment by Grovespaz** [comment]
I've switched to my own importer that's more tailored to my situation. Thanks for the thoughts.
