### ISSUE TITLE
Ability to copy values from on field to another using rules

### ISSUE THREAD

**Issue by niklas152** [firefly-iii/firefly-iii#4975]
**Description**
Hello, I would like Firefly III rules to be able to copy values from one field to another.  
E.g., when I set a new description for a transaction imported, I would still like to keep the original one by copying / appending it to the note field of the transaction beforehand. That way, any additional inforamtion which might have been part of the description is not lost.

**Solution**
An rule action such as "{Copy, Append} description to note". Maybe even the other way round, or for other fields as well.

**What are alternatives?**
At the moment, I can either not have rules set the description but instead do it manually, after also manually copying the description to the note field, or have a rule set the description but thereby overwritting all information that was there before.

**Comment by JC5** [comment]
See also #3040 and #1862. Basically, I keep the rule engine a bit simple on purpose, so it's always easy to use for people. 

Adding it as an action is not a bad idea but I am keeping it on hold for now. I'm going to need a new or another interface to make sure that 100+ actions don't make it very confusing.

I'll write it down as a future improvement :+1:

**Comment by JC5** [comment]
This will be part of 5.8.0, other improvements are on hold for the time being.
