### ISSUE TITLE
Credit Utilization Metric

### ISSUE THREAD

**Issue by mehalter** [firefly-iii/firefly-iii#4976]
**Description**

I would love the ability for Firefly III to compute and show credit utilization for my credit card asset accounts. I enjoy how I am able to manage my credit cards in Firefly III, but this is the final piece before Firefly III provides me with everything I need without making manual calculations on a regular basis.

**Solution**

It would be nice to have a field for credit limit when setting up an asset account with the credit card role. Once this is set, it would be trivial to calculate credit utilization as the absolute value of the negative balance on the card over the credit limit. Similarly, it would be nice to include maybe a new report type (or integrate it into one of the report types) to see the credit utilization across my credit cards and my overall credit utilization.

**Comment by JC5** [comment]
Thanks for the compliments. You can set up a virtual balance, that will show you how much money is left.

For the reports, I'm working on a new layout and more / new reports are part of it.

**Comment by mehalter** [comment]
Thank you for the reply. The virtual balance is great at only showing me amount of money left, but it's almost more useful on a  day to day basis to see it going in the negative from 0 to -(credit limit) to see how much money I owe. Instead of how much money I technically could spend. Would there be any way to present both of this information? or have a button that could toggle the "using virtual balance" and "not using virtual balance"? This would be extremely powerful in helping me see how much credit I have left and also think about "how much money do I owe right now". Thanks again for all this information!

**Comment by JC5** [comment]
No. You'll have to do that bit of math in your head.

**Comment by mehalter** [comment]
Would this be a possible feature in the future?
