### ISSUE TITLE
Allow multiple types of transactions in the same split entry?

### ISSUE THREAD

**Issue by maxloo2** [firefly-iii/firefly-iii#4978]
# Main Question

Nowadays it is very common (at least from where I am from) to have one person pay the bill and others would pay that person back via online payment. 

For example, me and 4 other friends went dinner, and we ordered $20 each, I would pay the $100 bill and my friends would pay me $20*4. 

I was trying all my money and I found that I could not create split bill that consists of both expense and transfer. I expected that it would allow me to, say, create a split for $20 to (cash) and $80 to my online payment account, which I also track with firefly.

I am actually new to this app(?) and I am not quite sure if the current design was explained before or is it intended at all, but if there is indeed a reason for that, is there an alternative or solution to my situation? 

[my transactions for one bill]
![image](https://user-images.githubusercontent.com/4709356/128558318-de625f90-cdc8-448b-b061-4b661064c1ae.png)

My workaround now is to create 2 separate entries to handle the amount that I actually had to paid (deducted from my total worth) and the amount that is "transferred" from, say, my cash wallet account to my online payment account.

[my current workaround + my expected result]
![image](https://user-images.githubusercontent.com/4709356/128556036-d97a77ec-e817-48dc-9cbe-cb116f4070ac.png)

However, my workaround is actually making it very difficult to track my money, especially when I have to pay food delivery bill for my colleagues and I am receiving money via cash, online payments and bank transfers.

[the situation that gave me headache]
![image](https://user-images.githubusercontent.com/4709356/128558029-59eec458-d826-4979-a2ed-b93916616e8c.png)

I would like to be able to see the actual amount of money that went out of that particular account in one glance, and have the ability to expand that transaction and see where the money went.

```
Transaction Total: $100:
$10 -> (cash): Lunch
$60 -> bank
$30 -> online payment
```

# Bonus Question
Is there any plan to let us customize more of what to be displayed in the dashboard page? Right now we can only choose which account to be shown but I wonder if it is possible to display reports instead. 

I am tracking all the movements of my money in all my different accounts, and I found that the dashboard is not very helpful in terms of tracking my spending habit. 

I would like to have it only show the total amount spent on, for example, food and transportation, instead of having every single transactions counted towards the graphs and made them very difficult to use as references.

**Comment by JC5** [comment]
> Nowadays it is very common (at least from where I am from) to have one person pay the bill and others would pay that person back via online payment.

https://docs.firefly-iii.org/firefly-iii/faq/financials/#what-do-i-do-with-people-who-pay-me-back

> Is there any plan to let us customize more of what to be displayed in the dashboard page?

No, nothing is planned at the moment.

**Comment by JC5** [comment]
>  Allow multiple types of transactions in the same split entry?

No, sorry. It's always just one type. This is not a database limit per se but a usability and complexity issue.

**Comment by maxloo2** [comment]
> > Allow multiple types of transactions in the same split entry?
> 
> No, sorry. It's always just one type. This is not a database limit per se but a usability and complexity issue.

Hi, thank you so much for the quick reply, but may I just ask what kind of usability issue would occur if this is allowed?

**Comment by JC5** [comment]
> Hi, thank you so much for the quick reply, but may I just ask what kind of usability issue would occur if this is allowed?

All of them.
