### ISSUE TITLE
Searches and Auto-fills are too strict being case-sensitive

### ISSUE THREAD

**Issue by maxloo2** [firefly-iii/firefly-iii#4979]
As topic, I would like the searches and auto-fills to be "smarter" and actually recognize that when I am typing "credit card" it show also show results for "Credit Card". If there is a reason to keep it this strict can we at least have an option to turn it off or have "fuzzy" enabled?

**Comment by JC5** [comment]
Use the search please.

**Comment by maxloo2** [comment]
> Use the search please.

Sorry if I sound stupid but I am not sure what you mean by that, I am new to firefly and I hope I am not missing something important here.

I believe that I am using the search function already, and let me try to explain my situation with screenshots:

![image](https://user-images.githubusercontent.com/4709356/128563259-54856c58-8c9b-4858-9fc0-4207a6a594ba.png)

![image](https://user-images.githubusercontent.com/4709356/128563286-9d4937a0-7e25-42ea-b81a-2ab73350b752.png)

is this the correct search page that I should be in? or am I supposed to create new rule?

**Comment by maxloo2** [comment]
nevermind I just realized what you were actually referring to... it is 4 am in the morning here and I guess my brain already stopped working properly after long day of coding and stuff, please forgive me for my stupidity ;(
