### ISSUE TITLE
"chained" transaction (for online payment that is linked to bank account)

### ISSUE THREAD

**Issue by maxloo2** [firefly-iii/firefly-iii#4980]
I am pretty sure this feature is very unimportant but I would still love to request for it. the idea of a "chained" transaction is that we would be able to configure in "automation' and have it add another transaction when some rules are triggered. 

my scenario is that I have linked my bank account with an online payment platform, and whenever I run out of money in it would prompt me to transfer money (with a single click) into the account and continue with the payment. 

since I would like to track all the transactions for all my accounts, I am currently manually inserting 2 transactions, one from my bank account to the online payment account, and another one from the online payment account to (cash).

it would be awesome if the transaction from my bank account to my online payment account can be inserted automatically. for example, the rules could be something like this:

```js
const my_transaction; 
if (source_account === 'online_payment') {
  create_transaction({
    source_account: 'bank',
    amount: my_transaction.amount - source_account.current_balance
  })
}
```

this is just an example for my exact scanario, if we are able to have more freedom in customizing the rules then people who are tech savvy enough and have a very specific situation may configure their own automation to automatically insert transactions.

**Comment by JC5** [comment]
Feel free to build something using the API. I can't build a custom language parser for a feature like this, it's overkill.

https://api-docs.firefly-iii.org/
