### ISSUE TITLE
Update transaction_journals via http REST API

### ISSUE THREAD

**Issue by soraxas** [firefly-iii/firefly-iii#4981]
I am running Firefly III version 5.5.13

**Description**

Is it currently possible to update the transaction journals via the REST API? My usecase is that I want to change a transaction from a deposit/withdrawal to a transfer (which is possible via rules in the web) via the REST API. I am writing some python script to do some more comprehensive processing of my historical data, and was using the HTTP api. By looking at https://api-docs.firefly-iii.org/ it seems like there are no PUT request for transaction journals but by sniffing at the https://github.com/firefly-iii/firefly-iii/blob/adc52f7b63a20e81bd0c7cb941e2f777beb8071a/app/TransactionRules/Actions/ConvertToTransfer.php it looks like you'd need to update the transaction journal to change transaction type?

Or is there an easier way to change deposit/withdrawal to a transfer via HTTP api? Thanks heaps!

**Extra info**

**Comment by JC5** [comment]
There is currently no endpoint to change the type of a transaction journal. This is on my list and will be part of the new layout.

**Comment by JC5** [comment]
Everything else to change a transaction is in place though.

**Comment by soraxas** [comment]
Hi @JC5! Will the REST API endpoint for converting transaction type be part of the roadmap to the upcoming v2 layout release?
