### ISSUE TITLE
Hide certain account(s) in the main plot

### ISSUE THREAD

**Issue by soraxas** [firefly-iii/firefly-iii#4982]
**Description**

Thanks again for the amazing work! Would it be possible to hide some accounts in the main line-plot that display in the main page? (the one that shows your current month/last 3 months/... of assets accounts). Kind of similar to, and goes hand-in-hand with the **Include in net worth** checkbox option in the accounts settings.

The reasons are that:

1. I have multiple bank accounts and some of them might previously have transactions but are no longer actively used. They would mostly be straight lines hovering at zeros in the plot which will clutter the interface.
2. I had set up an investment account of which I "transfer" money from my other accounts to that account. While it's good to keep track of how much I had invested via that "investment account", that amount would be highly disruptive to that plot, because it's not actually tracking the fluctuation and it makes the y-axis of the plot disproportional (because the "investment account" has a high value and would only be accumulative, while my other daily accounts would hover on the much lower ends of the plots).

**Solution**

An option in the account settings that allows one to hide amounts in the main plot, similar to unchecking the "**Include in net worth**" option on the same page.

**What are alternatives?**

No alternative currently exists. A related option is the "**Include in net worth**" option. Making an account inactive can hide the plot, but would completely disable the ability to perform additional options on that account (e.g. transferring money from other accounts to that disabled account).

**Comment by JC5** [comment]
Check your preferences.

**Comment by soraxas** [comment]
Thanks heaps @JC5 for your quick reply! I was only checking the various accounts' settings but didn't realise these options would be in the account preference.

Logically I'd argue that those options should be grouped with the "Include in net worth" option (either all in the account preference or reside individually within the account settings), as they are targeting similar features. Eitherway, it works for me now, thanks again!
