### ISSUE TITLE
Docs outdated with move to PHP 8

### ISSUE THREAD

**Issue by Kline-** [firefly-iii/firefly-iii#4983]
**Bug description**
I am running Firefly III version 5.5.12, and my problem is:

I didn't realize the requirements moved from PHP 7.4 to PHP 8 until I went to upgrade to 5.5.13. This feels like a fairly major change in requirements to be omitted from the changelog, and the [self hosted install](https://docs.firefly-iii.org/firefly-iii/installation/self_hosted/) docs still reference PHP 7.4 as well.

I rolled myself back to 5.5.12 without issue, but a mention of the new PHP requirement might save someone else a headache down the road :)

**Steps to reproduce**
Self-hosted install of 5.5.13.

**Extra info**
Debug information generated at 2021-08-08 11:52:06 America/Chicago for Firefly III version **5.5.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.12 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.21 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 6b07050a-647c-43e7-b130-b98bd6cac3ff |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| System TZ | America/Chicago |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-08-01 00:00:00 |
| Session end | 2021-08-31 23:59:59 |
| Session first | 2019-05-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; CrOS x86_64 13904.97.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.167 Safari/537.36 |

**Comment by JC5** [comment]
I thought 5.5.13 would still accept 7.4. What did you run into, exactly?

The only change between 5.5.13 and 5.5.12 is one line of code that shouldn't be major version dependent:

https://github.com/firefly-iii/firefly-iii/commit/07abfd78e186e20a0c066dc7246409a30ad1aad7

**Comment by Kline-** [comment]
I just checked the tags and this looks like my bad for following the [straight from GitHub](https://docs.firefly-iii.org/firefly-iii/installation/upgrade/#straight-from-github) upgrade directions with a blind pull.

The root composer.json in main has bumped PHP to 8, but the tagged version for 5.5.13 is still on 7.4. Might recommend changing the `git pull` to `git pull origin <tag>`.

**Comment by JC5** [comment]
Will do :+1:
