### ISSUE TITLE
"All transactions without a budget" doesn't allow for pagination

### ISSUE THREAD

**Issue by Grovespaz** [firefly-iii/firefly-iii#4985]
**Bug description**
I am running Firefly III version 5.5.13, and my problem is:

When I view transactions without a budget and click "show transactions without grouping them by date", a large list appears (/budgets/list/no-budget/all).
When I want to page through this list (to pick out transactions I could make rules for), I'm redirected to the date-filtered list (/budgets/list/no-budget?page=2) instead of the full list (which should be /budgets/list/no-budget/all?page=2, which works)/

1:
![afbeelding](https://user-images.githubusercontent.com/2829264/128714543-90a5a8a9-3d10-4a92-8591-3099b26559f9.png)
2:
![afbeelding](https://user-images.githubusercontent.com/2829264/128714566-2e6fcb4e-b86b-4902-a199-5fb1b1dfcd0c.png)

**Steps to reproduce**
1. Have enough transactions without a budget to exceed one page
2. Go to /budgets/list/no-budget/all
3. Click "Show transactions without grouping them by date"
4. Observe no results.

**Bonus points**

- I searched and nobody reported this bug before
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/ _(after creating a few more transactions)_

**Comment by JC5** [comment]
Thanks, this is something I intend to pick up in the new layout.
