### ISSUE TITLE
Future values

### ISSUE THREAD

**Issue by hiagodotme** [firefly-iii/firefly-iii#4986]
I am running Firefly III version 5.5.12.

**Description**
Is it possible for me to register amounts that I will still receive without impacting my account balance?

**Comment by hiagodotme** [comment]
Wouldn't it be nice to have a field with the paid/received option? This would be good even for recurring transactions, I place amounts from people who owe me, but I get lost to know which ones have already paid me and which ones haven't.

**Comment by hiagodotme** [comment]
Firefly III would only consider completed transactions in calculations. The system could also send emails informing me that there are transactions pending for the day (making it easy and reminding me to charge).

**Comment by JC5** [comment]
Meh. I don’t want to add “future planning” so that’s a no I’m afraid.

**Comment by hiagodotme** [comment]
@JC5 but do you find this feature useful? I can implement it.

**Comment by JC5** [comment]
No, but thank you for the offer.
