### ISSUE TITLE
Budgeted Amount Includes Inactive Budgets

### ISSUE THREAD

**Issue by carsonbird** [firefly-iii/firefly-iii#4987]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:

In Budgets, in the "Total available budget in US Dollar" section, the "Budgeted (see below)" amount includes the current totals of budget items that have "Active" unchecked. I assume it shouldn't be.

**Steps to reproduce**
1. Create a budgeted item that has some form of auto-budgeting (sets an amount every period, or adds an amount every period).
2. Allow the budget to accrue an amount (or change the budgeted amount for an item)
3. Uncheck the budget item's "Active" setting, so that it doesn't appear in the Budget list, but instead, appears in a section at the bottom labeled "Inactive Budgets".
4. Notice how the "Total Budgeted" amount mentioned in the description is looking at inactive budget items to obtain it's sum.

**Extra info**
Debug information generated at 2021-08-09 23:07:31 UTC for Firefly III version **5.2.5**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.5 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stdout |
| PHP version | 7.4.5 |
| Display errors | Off |
| Session start | 2021-08-01 00:00:00 |
| Session end | 2021-08-31 00:00:00 |
| Session first | 2020-03-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Login provider |   |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 |

**Bonus points**
- I couldn't find a similar bug report.
- I have not added stack trace files. I can provide them if necessary - however, I run this on Heroku and would have to spend some time figuring out how to obtain them. So, if they're really necessary for this bug, let me know (I imagine the problem here is something simple like, a forgotten 'where active=true' clause in a DB query or something)
- I have added a screenshot from the demo site. Notice how the total budgeted does not reflect the total amounts visible in the active budget. That's because the "Groceries" item, seen at the bottom in the "inactive budgets" section, has a budget of like, $100,000.

![image](https://user-images.githubusercontent.com/47391698/128785859-1b0e1155-e403-4ac5-89f2-82d17113ec94.png)

- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for the expansive report, I'll pick it up in the new layout :+1:

**Comment by JC5** [comment]
Wait, you're running 5.2.5, upgrade first then please.

**Comment by carsonbird** [comment]
Sounds good. I'll do that and let you know the results. I will mention, though, that this issue was also occuring on the demo site, which is running 5.6.0-alpha.1.

Thanks for all your hard work!
