### ISSUE TITLE
Can't select liability account from imported transactions?

### ISSUE THREAD

**Issue by xzaz** [firefly-iii/firefly-iii#4988]
**Bug description**
I am running Firefly III version 5.5.12 and my problem is:

I cant select liabilities any more as a destination account

**Steps to reproduce**
- Import a transaction from the importer
- Try to change the destination account to a liability account.

**Extra info**
Debug information generated at 2021-08-10 09:15:41 UTC for Firefly III version **5.5.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.12 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | e3659b1c-f565-4840-9a9e-b0056ee83252 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ |  |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-08-01 00:00:00 |
| Session end | 2021-08-31 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0 |

- I wasnt able to replicate it on the demo site https://demo.firefly-iii.org/ since it is V2 front end I think

**Comment by JC5** [comment]
What's the transaction type and the current type of the destination?

**Comment by xzaz** [comment]
Type: Withdraw (Uitgave). Account type of the current destination isn't set. I can only set Expense accounts not Liabilities.  Yhe I was a little bit vague on the demo site thingy. I mean, I cant reproduce it on the demo site because the bug is bound to V2 I think. So since the demo site is V1 i can't reproduce it there.

**Comment by JC5** [comment]
I see what you mean. The autocomplete only searches for the orginal specified account type. It's a bug!

**Comment by JC5** [comment]
Should be fixed in the new layout!
