### ISSUE TITLE
Layout V2: Cannot edit source field of the split transaction

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#4992]
**Steps to reproduce**

1. Create split transaction with at least two splits
2. Save the transaction
2. Open that transaction again for editing
3. Note that source account can only be edited on the first split (other splits just say `The first split determines the value of this field`)
4. Change the source account of the first split
5. Save

BUG: Firefly will error out with 422: `{"message":"The given data was invalid.","errors":{"transactions.0.source_id":["All accounts in this field must be equal."]}}`

Only way I found to change this is to manually edit the request JSON, copying `source_id` field to the second transaction.

**Debug**

Debug information generated at 2021-08-15 08:44:19 UTC for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 1c789eff-ec96-4172-80d7-9ab04aabfda8 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ |  |
| Browser TZ | Europe/Ljubljana |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-08-01 00:00:00 |
| Session end | 2021-08-31 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0 |

**Comment by JC5** [comment]
What type of transaction, please?

**Comment by matejdro** [comment]
Withdrawal

**Comment by JC5** [comment]
Thanks. Should be fixed in the next release :+1:
