### ISSUE TITLE
Best practice for transfer in spectre-importer

### ISSUE THREAD

**Issue by soraxas** [firefly-iii/firefly-iii#4997]
Thanks for the great tool and wonderful work on this management tool! I have a question on spectre-importer and I hope this is the correct place for it.

## Description
Say I have **AccA** and **AccB** where they are some sort of linked accounts in a bank (e.g. an Everyday account and a saving account, where every out-going transaction must go through **AccA**).

When transferring in-between **AccA** and **AccB** they might have different description:

| **Account** | **Description** | **source_name** | **destination_name**  |  **External ID** | **Internal reference**
|-------------|-----------------|-----------------|-----------------------|--|--|
| AccA | Internal transfer TSFR FROM ACC B   | _(unknown source account)_ | AccA | XXX | XXY |
| AccB | Internal transfer - Receipt 382741  | AccB | _(unknown destination account)_ | YYY | YYX |

where this is `AccB => AccA`, and the _(unknown source account)_ / _(unknown destination account)_ are what **spectre** returns.

-------------------------

Now it's easy to select one withdrawal/deposit and convert it to a transfer, then delete the other one.  That 
 results into something like this:

| **Account** | **Description** | **source_name** | **destination_name**  |  **External ID** | **Internal reference**
|-------------|-----------------|-----------------|-----------------------|--|--|
| N/A | Internal transfer  | AccB | AccA | XXX | XXY |

---------------------------

This is great and all. However, if I were to import from spectre again (say a few weeks later) and happens to overlap with this transfer, the importer would not be able to detect duplicates (which is very understandable).

From what I can tell the duplication detection is probably some combinations of a hash value between the description/amount/date/external id/internal ref? Even if we were to keep the original description, there would still be discrepancy between desc of withdrawal and deposit. So I wanted to ask what is the best way to allow the importer to detect duplications for transactions that had been linked into a transfer?

One idea might be that (assuming we purely rely on external id on duplication detection), we can make external id into a list/set of ids such that 

| **Account** | **Description** | **source_name** | **destination_name**  |  **External ID** | **Internal reference**
|-------------|-----------------|-----------------|-----------------------|--|--|
| N/A | Internal transfer  | AccB | AccA | { XXX,YYY } | XXY |

and when we import transactions from spectre, if the external id is either XXX and YYY, we will conclude that both of them are duplications of the existing transfer.

**Comment by JC5** [comment]
> However, if I were to import from spectre again (say a few weeks later) and happens to overlap with this transfer, the importer would not be able to detect duplicates (which is very understandable).

Actually, this is the part that isn't relatable. What changed in the meantime to the transfer, that the Spectre importer (or rather, Firefly III itself) would not be able to pick up on?

**Comment by soraxas** [comment]
The following is the same scenario as above but visualised:

After importing from spectre, it creates:
```
Transaction #1: (withdrawal)      A      ->  (unknown)
Transaction #2: (deposit)     (unknown)  ->     B
```
where T1 belongs to A and T2 belongs to B asset account. They both have same amount but different desc.


I then convert T1 from a withdrawal to a transfer, and delete T2.
```
[CONVERTED] Transaction #1: (transfer)      A      ->   B
[DELETE]    Transaction #2
```


Using spectre later on will import the same transactions that were converted / deleted.

**Comment by JC5** [comment]
Thanks. The duplication check should at least ignore transaction 1 when it runs again, is that correct?

**Comment by soraxas** [comment]
I had tested it just then and I think that is correct

**Comment by soraxas** [comment]
Hi so would that be a legit current limitation (of cannot merge withdrawal+deposit into a transfer) in spectre, and would the proposed idea of having multiple external id solves this issue? (maybe a one to many associations in the db for transaction_id->external_id?)

**Comment by soraxas** [comment]
So after a bit of digging (I'm not familiar with php so please correct me if I am wrong), I think `spectre-importer` (and likely any importer) prevents duplication by setting the flag `error_if_duplicate_hash = true` when sending API request.

That in turn should trigger error if there are existing same `import_hash_v2` value in the `data` field of `journal_meta` table. https://github.com/firefly-iii/firefly-iii/blob/10545f3e1baf5c53097392887f38469ffb75cab5/app/Factory/TransactionJournalFactory.php#L155

When I performed the scenario that I've described above, the transaction that I had deleted appears again (which seems to indicate that your call  at https://github.com/firefly-iii/firefly-iii/blob/10545f3e1baf5c53097392887f38469ffb75cab5/app/Factory/TransactionJournalFactory.php#L336 returns empty results). However, when I check for the data entries inside the database, 
![image](https://user-images.githubusercontent.com/22362177/133872790-c011c7d4-457d-4373-b6b8-d27a8e159ad3.png)
it does indeed contain both entries, with all identical data/hash (except `original_source`).

Based on the observation, I guess because you  were  using **soft delete** here https://github.com/firefly-iii/firefly-iii/blob/10545f3e1baf5c53097392887f38469ffb75cab5/app/Models/TransactionJournalMeta.php#L62
that's why the query returns an empty result and did not detect the entry that was marked delete?

-----------------------

##  Expected behaviour

Having said all that, I guess the expected behaviour would be that spectre-import (or any other importer) should not keep trying to re-add entries that were manually deleted (i.e. should not ignore rows in `journal_meta` table where `deleted_at != null`)?

**Comment by JC5** [comment]
You're absolutely right, that's a pretty amazing bug. Nice find!

It was always meant that re-imports of deleted transactions would not work. Somewhere down the line, the function was lost due to the addition of the soft-delete. I'm adding a check and this should not happen with the next release onwards.

**Comment by soraxas** [comment]
Awesome! Thanks James:)
