### ISSUE TITLE
Show budget in expenses overview

### ISSUE THREAD

**Issue by Compizfox** [firefly-iii/firefly-iii#5002]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [an idea that won't be implemented](https://docs.firefly-iii.org/firefly-iii/support/features/#ideas-that-wont-be-implemented)

### Description

Currently, the expenses overview shows the following columns: | Description | Amount | Date | Source account | Destination account | Category

The budget is not a column in this table. In order to see the budget linked to a expense, I have to click on it and view it in detail. This makes it quite cumbersome to go through my expenses and for example see which ones don't have a budget assigned yet.

### Solution

Would it be possible to include the budget as a column in the expenses overview?

**Comment by JC5** [comment]
Not in the current layout no, but I'll include it in the new one. There's limited space so it's probably going to be an option.

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/6304
