### ISSUE TITLE
Zero based budgeting

### ISSUE THREAD

**Issue by rubenvitt** [firefly-iii/firefly-iii#5006]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [an idea that won't be implemented](https://docs.firefly-iii.org/firefly-iii/support/features/#ideas-that-wont-be-implemented)

### Description

**What I want Firefly-iii to do**

Add the ability to switch budgeting style between "normal" budgeting and zero based budgeting.

**Why I think it's good for Firefly-iii to do it**

I learned to love YNAB, but it's kind of too expensive and my data is being stored on (for me) unknown servers. There are some other open source alternatives, but Firefly is the far best option for budgeting.

I really understand you with the introduction of one budgeting style in order to remove complexity at the first stage. I read through your whole guide on how to do budgeting and fully understand your point. I really wanted to use this app, but can't get the mindset in my head after using YNAB.

Generally I think it will make Firefly-iii far more better, if users can switch the budgeting style which they want to use.

I read through the closed issue https://github.com/firefly-iii/firefly-iii/issues/4690 and your linked doc-article, but wanted to get in touch a second time - also because it hasn't reached the not-to-implement-list for now.

### Solution

"Every dollar has a job".

**Comment by JC5** [comment]
It's not going to happen, sorry.

**Comment by kgehmlich** [comment]
@rubenvitt I'm in more or less the same boat. I love YNAB's approach, but I don't love having my finances in the cloud. That said, I also understand why @JC5 would be reticent to introduce a completely different paradigm to Firefly III.

I'm considering starting a new FOSS project for self-hosted zero-based budgeting. Want to be a beta tester if I do?
