### ISSUE TITLE
Operation automation - every 2 weeks task

### ISSUE THREAD

**Issue by lukou31** [firefly-iii/firefly-iii#5011]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [an idea that won't be implemented](https://docs.firefly-iii.org/firefly-iii/support/features/#ideas-that-wont-be-implemented)

### Description

Hi everyone.

I'm just starting to use Firefly-3.  This tool is very powerfull. I have to automate some operations. I live in Canada and my salary is given by my company every 2 weeks.  Currently I can't add that opeation to the automation list. It's sad !

### Solution

I would like to have the choice of "every 2 weeks" in the "type of repetition"  selection box.

### What are alternatives?

No alternative

**Comment by JC5** [comment]
Set "skip" to 1.
