### ISSUE TITLE
Creating transactions via rules

### ISSUE THREAD

**Issue by Sebb767** [firefly-iii/firefly-iii#5014]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [an idea that won't be implemented](https://docs.firefly-iii.org/firefly-iii/support/features/#ideas-that-wont-be-implemented)

### Description

I'd like to be able to create rules that create another transaction. Example use cases:

- I'd like to have PayPal as a separate account. This, however, would need me to create two transactions: One My Account -> Paypal and one Paypal -> Vendor. It would be awesome to have a rule that could take a transaction from A to B tagged `paypal`, edit the transaction to be from A to Paypal and then create a second transaction from Paypal to B. 
- My credit cards gives me 1% rebate on fuel. This is listed as a separate transaction. I'd like to have a rule that creates the rebate transaction for every transaction tagged `fuel`.

### Solution

I'd like a rule action that is 'create new transaction'. As parameter you'd give the rule destinations with some possible placeholders (or a template? -> #4917 ). Once the rule matches, the transaction is created.

### What are alternatives?

For now, as far as I can tell, the options are to either create the transactions manually or have a script search matching transactions via the API.

### Additional context

I know this is a rather complex request (you'd need to be able to do some type of transaction templating in the rules and prevent recursion), but it would probably be useful in quite a few scenarios. I went through the open (and some closed) issues and googled, but nothing came up, so I thought I'd simply create a feature request and see what people think :)

**Comment by JC5** [comment]
No, that is way beyond what the rule engine is for. If you want to do something like that, use the API.

**Comment by Sebb767** [comment]
Fair enough. Thank you anyway! :)
