### ISSUE TITLE
docker volume permission issue

### ISSUE THREAD

**Issue by hppyworld** [firefly-iii/firefly-iii#5021]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Bug description
The containers start but all checks fails with "permission denied". for volume with uid:gid 1000:1000, 

Version: 5.5.13

Steps to reproduce
My Dockerfile is as follows:

version: "3.7"

services:
  firefly_app:
    container_name: firefly_app
    image: fireflyiii/core:version-5.5.13
    user: "1000:1000"
    restart: always
    depends_on:
      - mysql
    volumes:
      - /deploy/data/firefly/storage_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 8401:8080

### Expected behaviour

should able to use external volume specific path for docker

### Actual behaviour

permission denied when using docker volume with specific path on local system with uid:gid 1000:1000

### Steps to reproduce

1. run docker-compose up 

### Debug information

```yaml
permission denied for directory
```

**Comment by JC5** [comment]
The internal web server currently runs under www-data:www-data, no matter what you do. Sorry.

**Comment by hppyworld** [comment]
@JC5 thanks for quick reply. 
can you please then tell how to map external volume with specific path ? 
basically i want to use specific path for volume for docker container. 
Thanks.

**Comment by JC5** [comment]
Any folder should be fine, check out which user the www-data is and give it permission to that folder.

It works it will just always be under the www-data user.

**Comment by hppyworld** [comment]
thanks.
