### ISSUE TITLE
V2: Issues with entering transactions

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#5025]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [an idea that won't be implemented](https://docs.firefly-iii.org/firefly-iii/support/features/#ideas-that-wont-be-implemented)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Okay, first things first: I know this issue is very similar to #4609, but I have some other thoughts on how entering transactions could be improved in V2.

Having read #4618, I know that you will probably work on the pages later again, but I wanted to plug in my ideas/issues anyways.

1. I usually enter multiple transactions at once (e.g. one or two times per week), which is why the "return here to create another one" checkbox is very awesome! However, V2 changed the layout of the form, which means that on a 16:9 monitor, I can't see the top where the message "The transactions has been stored" appears. This sometimes confuses me and I don't whether I have actually stored the transaction and have to scroll up the page to check.
2.  The auto-suggestions are way better now in V2, but they sometimes also block the view on other elements (most notably the Description box, which is now full-width and therefore blocks almost the entire page). Some of the boxes feel too wide now as well, esp. the category and amount boxes 😅
3. You can't quick-create a withdrawal/expense from the dashboard for a specific account anymore.

### Solution

I'll use the same numbers as above to provide my suggestions:

1. Either add an animation to the submit button, which can emphazise that the transaction has in fact been stored (like a check mark inside a button for a sec or something). Alternatively, you could also scroll to the page top (and while we're at it, also select the first input field again for more keyboard-friendlyness).
2. Maybe a more subtile way to display suggestions? I personally don't have a great design idea for this, but maybe you'll be able to figure out a less intrusive way to display them 😄
3. Add the buttons to the new dashboard as well, or add another feature to pre-fill an account

### Additional context

I know that most of V2 is most probably still subject to change, I simply wanted to address the main problems I currently have with the new transaction layout so you know about them. However, I really like the new design in general and can't wait to finally see the finished version of it! 😍

**Comment by JC5** [comment]
I'll pick it up, great ideas! 👍

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/6304
