### ISSUE TITLE
e.createElementVNode is not a function on the whithdrawal screen

### ISSUE THREAD

**Issue by ebanDev** [firefly-iii/firefly-iii#5028]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I click on "create new whithdrawal", I get this blank screen and the error `e.createElementVNode is not a function`
![image](https://user-images.githubusercontent.com/57091497/131250040-26b668f7-ead2-446f-8775-feef58aabfcf.png)

### Expected behaviour

Well... I excepted the create new whithdrawal page to show correctly 😅.

### Actual behaviour

I get a blank page.

### Steps to reproduce

1. Create an Heroku account
2. Deploy [this](https://elements.heroku.com/buttons/firefly-iii/firefly-iii) Heroku App
3. Go through the onboarding etc, click on the "create new whithdrawal" button.

### Debug information

```yaml
Debug information generated at 2021-08-29 12:20:29 UTC for Firefly III version **5.6.0-alpha.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.0-alpha.2 |
| Firefly III API | 1.5.3 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 5c3eaf70-cd82-4e44-afed-4f02d25aefb2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| System TZ | UTC |
| Browser TZ | Europe/Paris |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| DB version | 17 (exp. 17) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-08-01 00:00:00 |
| Session end | 2021-08-31 23:59:59 |
| Session first | 2021-08-29 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0 |
```

**Comment by JC5** [comment]
Yes, this will happen in the develop branch unfortunately. It's something in the build.

**Comment by JC5** [comment]
I'm labeling this "wontfix" not because I won't fix it, but because it generally fixes itself again.
