### ISSUE TITLE
User invitations (for when registration off)

### ISSUE THREAD

**Issue by Valinwolf** [firefly-iii/firefly-iii#5031]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [an idea that won't be implemented](https://docs.firefly-iii.org/firefly-iii/support/features/#ideas-that-wont-be-implemented)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to request something similar to #3660, but more of an invitation system that works even when the registration is off that way admins can allow friends to register without having to open it completely up to the world.

### Solution

An invitation system independent of the current registration system.

### What are alternatives?

Better user management, as suggested by #3660?

### Additional context

It's pretty annoying to have to turn it off wait for your buddy to register and turn it back off. It would be much nicer to just be able to punch in his/her email and have them open that link that was emailed to them. Obviously there would need to be an automatic expiration of the link, which could be done without cron and such by implementing a simple expiration date/time and a check on the invitation accept page.

**Comment by JC5** [comment]
I'll write it down 👍

**Comment by JC5** [comment]
Note to self: if the user is not an admin, the admin must confirm the invite.

**Comment by JC5** [comment]
Fixed in 5.8.0
