### ISSUE TITLE
generated recurring transactions miss the category

### ISSUE THREAD

**Issue by frank-bg** [firefly-iii/firefly-iii#5036]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

- when you create a recurring, there is an option to select the category for the transactions that will be generated
- when the cron generate the transaction, the selected category for that recurring is missing

### Expected behaviour

generated transactions must keep the category of recurring

### Actual behaviour

generated transactions miss the category of recurring

### Steps to reproduce

1. create a recurring, selecting a category
2. run the cron: `artisan firefly-iii:cron --force --date=YYYY-MM-DD`
3. the generated transaction miss the category

### Debug information

Debug information generated at 2021-09-02 05:04:37 Europe/Amsterdam for Firefly III version **5.5.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.3 |
| Firefly III API | 1.5.1 |
| PHP | 8.0.5 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | c68f70af-e9cf-4905-9f65-ff210073effa |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite, sqlsrv |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2021-09-02 04:47:40 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0 |

**Comment by JC5** [comment]
Please make sure you're running the latest version of Firefly III. I believe this is already fixed.

**Comment by frank-bg** [comment]
oh, i see. it's not yet in stable version

8a8aa7ca71025f496da923abfca01ef0757d58e3
