### ISSUE TITLE
Reconciliation transactions count as expenses in default financial report

### ISSUE THREAD

**Issue by zxyrepf** [firefly-iii/firefly-iii#5043]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Reconciliations (positive and negative) are added to the expenses bar on the "Income vs. expenses" chart of the default financial report for the current year.

### Expected behaviour

I would expect, that reconciliations should not affect the income or expenses.

### Actual behaviour

They do increase the expenses bar on the main default financial report chart.

### Steps to reproduce

1. Create a reconciliation with a big enough difference to spot it on the graph (doesn't matter if positive or negative)
2. Visit the default financial report "Current year, all accounts"

### Debug information

Reproducible on demo instance. Reconciliations are currently created for October.

**Comment by JC5** [comment]
I don't consider this a bug, myself. Why would they be excluded?
