### ISSUE TITLE
tag_is query appears to be broken for tags that don't exist

### ISSUE THREAD

**Issue by Venefyxatu** [firefly-iii/firefly-iii#5044]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Searching for a tag does not exist (either never defined or was deleted) will return a result set containing all transactions. Once the tag has been added to a single transaction only this transaction will be returned, or no transactions if the transaction containing the tag was deleted.

Once you delete the tag, searching for it will once again return all transactions.

### Expected behaviour

Searching for tag_is:"omgbbq" should only return transactions with this specific tag, or an empty result set if the tag does not exist.

### Actual behaviour

Searching for tag_is:"omgbbq" returns all transactions if the tag does not exist.

This also impacts rules, e.g. a strict rule with two triggers:

1. (A) tag is...    omgbbq
2. Destination account name is...    Checking Account

This will trigger on any transaction with Checking Account as destination account.

### Steps to reproduce

Both ways work on the demo site:

1. Search for tag_is:"omgbbq" (make sure to use a tag that doesn't exist)
2. All transactions will be shown in the result set, none of them have this unlikely tag.

Alternatively, to see the impact on automation rules:

1. Define a new rule with settings:
   - Strict: True
   - Triggers:
       - (A) tag is...: omgbbq
       - Destination account name is...: Checking Account
   - Actions:
       - Add tag: oops
2. Either trigger the rule and check a transaction with destination account Checking Account (it will only have the new tag), or use the preview functionality to see which transactions would be affected.

### Debug information

Debug information generated at 2021-09-04 18:52:14 Europe/Brussels for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | dae8592d-813e-4792-888e-8f0bd84ac203 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| System TZ | Europe/Brussels |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | nl_NL |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2021-09-04 18:25:10 |
| User ID | 1 |
| User language | en_US |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 |

### Additional info

Workaround: define the tags you want to use before relying on rules searching for them.

**Comment by JC5** [comment]
Yes, most of the queries with a value that may be in the database display this behaviour. Ultimately, it's to do with the fact that the entire (part of) your search query is dropped if the tag doesn't exist. And when the search query is empty, all transactions are returned.

I'll pick it up, thanks for the extensive bug report!

**Comment by JC5** [comment]
In the next release any invalid search (non-existing accounts, tags, etc) will result in NO results being returned.

**Comment by JC5** [comment]
5.6.0 is out.
