### ISSUE TITLE
Can't create a new currency

### ISSUE THREAD

**Issue by schklom** [firefly-iii/firefly-iii#5045]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Same issue and fix as in https://github.com/firefly-iii/firefly-iii/issues/943.

### Expected behaviour

I didn't think I would need to manipulate the database to create a new currency.

### Actual behaviour

It turns out I did need to.

### Steps to reproduce

Same as in https://github.com/firefly-iii/firefly-iii/issues/943

### Debug information

Debug information generated at 2021-09-05 02:58:53 UTC for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | f605877b-60d7-441f-b579-ff01855dadd2 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| System TZ |  |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start |  |
| Session end |  |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0 |

**Comment by JC5** [comment]
Thanks for opening a new issue. Without more information, like logs from the original installation, I'm afraid this is a "wontfix" for me. I was never able to find the original root cause four years ago, and without more info, I don't expect to find it now.

Since it happens so very rarely, I'm going to consider this a fluke.
