### ISSUE TITLE
[CSV-Importer] mapping file not complete

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#5047]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hello,

As I'm using the CSV Importer for 99% of my transactions I really love the mapping file. But I think there is an issue.
My current list contains 741 mappings. I'm using this file and when showed the list to do the mapping I already feel some of them should already be mapped but are not.

Anyway when I'm done manually do the mapping for the ones needed and I download the file from the tool right before starting the import I see the mapping list contains around 492 lines. Even if mine I used as input has 741...

I'm manually copy/pasting the ones at the top of the list for this run and use a bash script to sort and remove duplicate from my original list, but shouldn't it be exporting the complete list?
Maybe there is a bug and the tool has a max number of records it can handle?

I know I'm maybe pushing this tool to its limits a lot of times but it's so useful to use it coupled with the rules. At each run I'm doing less and less manual stuff except the reconciliation 😄 

### Expected behaviour

When exporting the mapping list at least all the ones used as input should be present. If new mapping have been done they have to be added to the list

### Actual behaviour

Seems the tool only export around 492 records max

### Steps to reproduce

1. Use an import file that has more than 492 mappings
2. Export the mapping file before starting the transactions import
3. Open the file and look how much lines are present for the mapping

### Debug information

Sorry I don't have it. When would be the best time to run the /debug for this scenario?

**Comment by JC5** [comment]
I'm pretty sure it only exports the ones you've actually used in your (current) file, but I can't be sure. I'll look into it, there should be no limit. I know there are no limits in the code.

**Comment by MacPaille** [comment]
I thought so too but it's always around 492 lines. And it's all alphabetically sorted because I compared 2 runs and less lines where appearing as I had new ones above.

**Comment by MacPaille** [comment]
I just did a test now. My input file has 740 mapping records. I just imported 9 transactions.
Out of this 9 I had 8 different accounts from which 6 where already mapped correctly. So I added 2 new mappings in the GUI.

From the JSON file I downloaded only the first 500 mappings are included. All the others do not appear.
Could it be you are manipulating the text? I have a LOT of times multiple records for the same account as the bank is playing with different ways to write the same thing. Sometimes multiples spaces, sometimes tabs etc...

**Comment by MacPaille** [comment]
I confirm I did import transactions again today and added new mappings to the list. Still the exported file is limited to 493 first records of the list.

In fact it's more all the mappings I did for the session are top of the list, then all the rest of my list up to the 493 lines...

BTW it would maybe be better to also have that mapping list sorted alphabetically.

**Comment by JC5** [comment]
I think there is a working version in the `develop` branch and in the `develop` Docker tag, and I look forward to your feedback.

**Comment by JC5** [comment]
Mmm, let me check.

Was the example already present in the file or lifted over "fresh" from Firefly III?

**Comment by JC5** [comment]
I can't replicate this; up to 16 spaces is preserved.

**Comment by JC5** [comment]
Could it be that the entries in Firefly III have a different number of spaces? If that is the case, the Firefly III entry would overrule the JSON entry. But then again, there would be no automatic match.

In the `develop` branch and in the `develop` image the spaces are better visible in the example and mapping files. Not in de drop-downs, unfortunately.

**Comment by MacPaille** [comment]
I almost never keep these names as is in FF as they are either all capitals or with names not super good. Also I have multiple different versions for the same expense account. So the names I use in FF are completely different from the ones I get in the CSV. That's why the mapping with the account ID is super important and the best solution :-)

**Comment by JC5** [comment]
I keep ending up with the same number of spaces. What I did was:

- I changed 1642 into 18, a local account ("AliExpress")
- I created a CSV with a transaction that has `Coolblue               ROTTERDAM` in the expense account name column. You can't see the spaces but it's a copy/paste.
- If I import this over the user interface I see that the import config is unchanged, or unchanged enough not to warrant any significant changes. I do this by keeping track of the files in `storage/uploads`. The spaces are there.
- At the end of the import, the download also has the same number of spaces in `Coolblue               ROTTERDAM`.

Weird, right? Is your process different?

**Comment by JC5** [comment]
I'm going to close this, if you don't mind.

**Comment by MacPaille** [comment]
Sorry I did not run any import since then. I plan to do tomorrow and see if now this works or not. I4ll always keep a backup of my version of the file to make sure I can revert if needed :)

**Comment by MacPaille** [comment]
So far I'm now using the version of the mapping list from the file I downloaded from the tool and no issues.
I still have to copy/paste all the listing to all my files as I have multiple accounts and each one has its own config file... That's why having this mapping list independant from the account config file would be the best idea :)

Thanks for the fix on this! You can definitely close this ticket

**Comment by JC5** [comment]
:+1: 

Separating the mapping file will be a chore but it's on the list!
