### ISSUE TITLE
Rules don't update if account names change

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#5060]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I was wondering why some rules didn't trigger correctly in my automations, and it turns out I edited a related account name, and the rule didn't update it.

It seems like rules might not actually be referencing account IDs, or perhaps are just not pulling the updated info. 

### Expected behaviour

For a rule such as "Destination account name is 'Test 1'", I would expect Test 1 to change if I edit the account name.  

### Actual behaviour

If I edit "Test 1" to "Test 2", the rule will still check for "Test 1". 

### Steps to reproduce

1. Create expense account "Test 1"
2. Create a rule. Condition: Destination account name is "Test 1" 
3. Rename expense account to "Test 2"
4. You will see that the rule will still be referencing "Test 1" (which doesn't exist anymore).

### Debug information

Debug information generated at 2021-09-06 15:43:44 Europe/Stockholm for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 5d944787-b68d-4379-b252-fe43600e9986 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Stockholm |
| Browser TZ | Europe/Stockholm |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-07-01 00:00:00 |
| Session end | 2021-09-30 00:00:00 |
| Session first | 2015-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0 |

**Comment by JC5** [comment]
Yes, this may happen. Unfortunately I can't catch this particular change in names, because you could have both an expense AND asset account with the same same. Ergo, I can't know for sure if the "test 1" account should be changed to "test 2" or not.

So this is in place, for piggy banks, budgets, categories and everything but not for destination / source account names.

As such, I'm afraid I must tag this a "wontfix".

**Comment by AlexKalopsia** [comment]
But expense and asset would have different IDs right? Wouldn't it be possible to assign IDs (Similarly to when you link transactions)? 
But yeah, no problem if this is not doable, perhaps might be worth throwing a warning message if you edit an account that appears on rules.

**Comment by JC5** [comment]
Unfortunately no, due to the flexibility of the rule engine the data is saved as text fields. That's why it's saved twice.

But I like the warning, and I'll edit the issue!

**Comment by JC5** [comment]
The engine has been updated and should be able to update all rule actions/triggers.
