### ISSUE TITLE
SEND_TELEMETRY flag does not work in docker image

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#5063]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Setting `SEND_TELEMETRY` to true does not seem to enable the telemetry

### Expected behaviour

 `/admin/telemetry` page should display telemetry info

### Actual behaviour

`/admin/telemetry` page displays `Telemetry is disabled.`

### Steps to reproduce

Run Firefly via docker and add `-e SEND_TELEMETRY=true` to the docker command line

### Debug information

Debug information generated at 2021-09-08 15:29:27 UTC for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 1c789eff-ec96-4172-80d7-9ab04aabfda8 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ |  |
| Browser TZ | Europe/Ljubljana |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2017-12-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0 |

### Additional info

If I execute `docker container exec firefly /bin/sh -c 'echo $SEND_TELEMETRY'` on the docker machine, it will print out `true`, so variable itself is definitely set.

**Comment by JC5** [comment]
I appreciate you want to submit telemetry!

SEND_TELEMETRY doesn't work for anybody. I quietly killed the feature by disabling the flag in Firefly III.

The telemetry I collected was useful, but ultimately not a primary driver for Firefly III development. So I removed support, and the related code and documentation will be gone with the next version of Firefly III.

**Comment by matejdro** [comment]
I see. Well, it looks like I decided to enable it at just the wrong time.
