### ISSUE TITLE
Lock reconciled transactions

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#5070]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [an idea that won't be implemented](https://docs.firefly-iii.org/firefly-iii/support/features/#ideas-that-wont-be-implemented)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- In rules (maybe a checkbox)
- In edit / API calls

### Solution

Lock the transaction. Possibly amount only, but I'm thinking all fields.

**Comment by bverkron** [comment]
Would really love this feature. YNAB is the only software I've used so far that has this (but I'm trying to move away from YNAB) and it's been a life saver a few times.

**Comment by pwsoftwaredesigns** [comment]
I also think this would be a beneficial feature.  Perhaps only the "critical" fields like

- date
- description
- source
- destination
- amount

Should be locked, while all other fields (e.g., notes, budget, category, attachments, etc.) remain unlocked

**Comment by JC5** [comment]
This is now in place for Firefly v6.1.0. The demo site will feature this in ~24hrs.
