### ISSUE TITLE
Disable Warning for time spans of configure threshold

### ISSUE THREAD

**Issue by Syphdias** [firefly-iii/firefly-iii#5071]
### Description

Every time I look at a bigger time range (>50 days) this banner pops up:
> Warning! 92 days of data may take a while to load. (Close)

It is pretty annoying since it draws my attention every time and it does not stay hidden after I dismiss it.

The loading not not even take that long – even with ~2500 transactions (good job, btw). I realize that this might not be a lot of transaction for people and they need to limit their transactions to <50 days for decent performance. But since I don't have that many I would like to not constantly see the banner.

### Solution

Make it configurable to completely disable the warning or increase the amount of time threshold which triggers the warning. You could also use a threshold of 0 to disable it if you wanted to provide both options.

### What are alternatives?

Remember that I ignored the message and not show it again even if I change the date range to be bigger.

Without a "fix":
- Ignore the yellow banner
- Inject JS with a plugin to remove the banner from the DOM

**Comment by JC5** [comment]
It's it coming back in the new layout. Due to various optimizations (thx!) the warning is no longer relevant.

I'm marking this a wontfix but that's because it'll disappear in due course.

**Comment by Syphdias** [comment]
Great to hear! Can't be too long if I look at #4618 :wink:
