### ISSUE TITLE
Wrong reconciliation with transfers

### ISSUE THREAD

**Issue by cestpasphoto** [firefly-iii/firefly-iii#5082]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Let's assume I have created a transfer between account A and account B. During reconciliation of account A, if I check such transfer and validate, firefly automatically assumes that this transfer is also reconciliated for account B.

### Expected behaviour

Both banks have different delays so such transfer may appear in listing of bank A but not in bank B.
So I would expect such transfer as part of account B not to be automatically reconciliated.

### Debug information

Debug information generated at 2021-09-13 09:29:42 Europe/Amsterdam for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | dbe22797-fb84-4568-bdb7-38a55d9035d7 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-13 00:00:00 |
| Session end | 2021-09-19 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0 |

**Comment by JC5** [comment]
Thanks for the feedback, I've written it down as an enhancement. It will be part of the new layout I expect :+1:

**Comment by JC5** [comment]
Sorry, this will not be changed. Unfortunately, a transfer is always reconciled on both ends.
