### ISSUE TITLE
CSV-import  : Allow import for file with any encodage

### ISSUE THREAD

**Issue by jup31** [firefly-iii/firefly-iii#5084]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

For me this topic has been discussed on #3312 but it could be more "wife compliant" if the ANSI file furnish by some banks could be integrated without using a manual modification. Notepad ++ or sublime text or any other manual solution to ensure it's an UTF-8 file before importing are a little bit hard to apply by anyone.

### Solution

We could had an option in the json file to defined a specific encodage and use it to read the file.

### What are alternatives?

Add a systematic and automatic conversion to UTF-8 before reading the file ?

**Comment by jup31** [comment]
I see that it's league/csv that it's used. [I found here that it could support conversion](https://csv.thephpleague.com/)

```
use League\Csv\Reader;
use League\Csv\XMLConverter;

//load the CSV document from a SplFileObject
$file = new SplFileObject('/path/to/your/csv/file.csv', 'r');
$csv = Reader::createFromFileObject($file);

$converter = XMLConverter::create()
    ->rootElement('csv')
    ->recordElement('record', 'offset')
    ->fieldElement('field', 'name');

$dom = $converter->convert($csv);
$dom->formatOutput = true;
$dom->encoding = 'iso-8859-15';

echo '<pre>', PHP_EOL;
echo htmlentities($dom->saveXML());

```

**Comment by jup31** [comment]
`use League\Csv\Reader;

$reader = Reader::createFromPath('/path/to/my/file.csv', 'r');
//let's set the output BOM
$reader->setOutputBOM(Reader::BOM_UTF8);
//let's convert the incoming data from iso-88959-15 to utf-8
$reader->addStreamFilter('convert.iconv.ISO-8859-15/UTF-8');
//BOM detected and adjusted for the output
echo $reader->getContent();`

**Comment by jup31** [comment]
We could had a field on json that can store the 'iso-8859-15' value to allow any conversion type.

**Comment by JC5** [comment]
I dropped this in the past because conversion through PHP is not reliable. I will see if this has changed.

**Comment by jup31** [comment]
Don't find where to insert it correctly in your code for testing purpose.

**Comment by jup31** [comment]
Maybe we could use [function mb-detect-encoding](https://www.php.net/manual/fr/function.mb-detect-encoding.php) to detect the source charset encoding and then convert it using the method hereupper.

**Comment by JC5** [comment]
I'll put it on the list but auto-detection is tricky and error prone.

**Comment by JC5** [comment]
The new data importer will feature this! Keep an eye on Twitter for more info.
