### ISSUE TITLE
Bulk edit

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#509]
Hi, I would find it very helpful to have something like a bulk edit for transactions, where the user should be able to change values for all selected transactions.
So if I select a number of transactions and click the non-yet existing bulk edit button, change f.e. the category just once and click update -> all selected transactions should get the new value.

This would be helpful after big imports or if one does add an new category and want to change the accounts or category for a lot of old transactions.

**Comment by JC5** [comment]
There is a bulk edit available. Bottom right of most transaction lists.

**Comment by xpfgsyb** [comment]
Yep, but there I need to change one transaction per line. Or do I oversee something? So if I want to change 50 transactions to the same value that means to select 50 fields, paste the same value 50 times, click save. I thought of the possibility to change X transactions, that were selected before, with just one line, to the same value. Something like that:
![edit](https://cloud.githubusercontent.com/assets/24813122/21582637/f56983c2-d060-11e6-9542-2e784f990987.jpg)

Plus a list of the transactions the user is going to change and a big warning about what the user is going to do :)

**Comment by JC5** [comment]
Ah, I see what you mean. 

I'm not a big fan to be honest, it seems to me quite a narrow use case for quite a lot of code. 

If you need to change a lot of of transactions, could you fix something up with rules? Especially when transactions are imported, you should be able to create a (set of) rule(s) that "catch" the transactions involved. 

You can do very narrow selection and rule actions involve almost everything the user can do. Let me know what you think!

**Comment by xpfgsyb** [comment]
That's a great idea. I missed that rules can be executed on existing transitions... I think I'm able to "fix" the imported data with rules then. Very useful - thank you!
