### ISSUE TITLE
5.6.0 and layout v2 - not listing all transactions in accounts

### ISSUE THREAD

**Issue by elmig** [firefly-iii/firefly-iii#5092]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

after upgrade to 5.6.0, not all transactions appear in account's transaction list.

### Expected behaviour

Accounts have all transactions listed

### Debug information

Debug information generated at 2021-09-17 17:27:30 Europe/Lisbon for Firefly III version **5.6.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.0 |
| Firefly III API | 1.5.3 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | e1f50d51-8bde-47c6-a9d0-c746ac375e76 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Lisbon |
| Browser TZ | Europe/Lisbon |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | pgsql |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2020-08-28 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | pt_PT |
| Attempt at "pt_PT.utf8" | 'pt_PT.utf8' |
| Attempt at "pt_PT.UTF-8" | 'pt_PT.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0 |

### Steps to reproduce

With version 5.6.0 and layout 2 - Created a transaction and appeared on expense list but not on account. Changing for layout 1 the transaction appears. Only seen this behavior with 5.6.0.

**Comment by JC5** [comment]
It could be the cache, it's set to be pretty strong.

Press the refresh button over on the account list, then try again. The button on the transaction list should alert TODO and won't work. But the one over at `/accounts/asset` should work just fine.

**Comment by elmig** [comment]
No changes after pressing the button

**Comment by JC5** [comment]
I can't replicate this. New transactions show up as expected.

**Comment by elmig** [comment]
I took some screenshots: https://imgur.com/a/EM1ugKn

See transaction underlined in v2 and then v1.

Let me know any hint to debug this.

**Comment by JC5** [comment]
Thanks for the screenshots. You could try in a private window to see if it's cache related perhaps?

**Comment by elmig** [comment]
I tried in private window and the usual session i use, and today it appears.

Any ideas on what could have caused this with layout v2 and not with v1 ?

**Comment by JC5** [comment]
I suspect the cache is set to be too aggressive, but I'll dive into it.

**Comment by JC5** [comment]
The cache issue is one in ongoing development, I'm not going to treat this as a bug. As more pages are built in the new layout better cache mechanisms will be developed.

**Comment by matejdro** [comment]
How is this not a bug? It does not display transactions.

**Comment by JC5** [comment]
It's a bug in the sense that a house not having a roof when you're still building the foundations is a bug.

**Comment by matejdro** [comment]
I see. Thanks for the explanation.

I will be switching to the v1 layout for now, but I will be right back to giving you v2 feedback as soon as this is resolved.
