### ISSUE TITLE
Posting a transaction via API responds with Sign-in

### ISSUE THREAD

**Issue by Cludch** [firefly-iii/firefly-iii#5099]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have been using a small script to create a simple transaction using the API.
However, since a few weeks, I noticed that the transactions are not created.
After some investigation, I have found out that the api endpoint `POST /api/v1/transactions` always responds with the sign-in page. The API bearer token seems to be valid, because a `GET` request against the same endpoint, successfully returns all transactions.

### Expected behaviour

The API endpoint should return with a error message or successfully create the transaction.

### Debug information

Debug information generated at 2021-09-19 13:35:07 Europe/Berlin for Firefly III version **5.6.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.0 |
| Firefly III API | 1.5.3 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 97c80e72-a3d2-483b-8b0d-0ca4c561abe2 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | warning, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** 

### Steps to reproduce

Using the example payload from the [api docs](https://api-docs.firefly-iii.org/#/transactions/storeTransaction) and posting this with a valid bearer token to the specified endpoint.

### Additional info

I am using the latest release 5.6.0.
The issue seem to be with both the default authentication guard and also with the `remote_user_guard`.

If there is anything, I can test to produce further helpful information, please tell me and I will give my best to provide you with the information.

**Comment by JC5** [comment]
Make sure you add Accept: application/json and it should return the correct error, and not the HTML page.

**Comment by Cludch** [comment]
I really missed that one. Sorry for bothering and thanks a lot for your support and great work!

**Comment by JC5** [comment]
No problem, glad to hear it works!
