### ISSUE TITLE
Transactions filter

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#510]
Hi, the current search does only show 20 transactions with a few details. Sometimes it's helpful to find more results with more details, so I would love to have a filter in the "transactions (everything)" view, where one can filter by the shown fields (description, amount/date range, from/to account, category, …).

**Comment by xpfgsyb** [comment]
Okay, I'm looking forward to the better search :)

**Comment by JC5** [comment]
This is now [live](https://firefly-iii.nder.be/) at the demo site and will be in the upcoming release. See also the [help text](https://github.com/firefly-iii/help/blob/master/en_US/search.index.md).

**Comment by xpfgsyb** [comment]
Good work! Plus some UI work instead of the print_r of the array and it will be a cool feature.

I think it would be helpful to have the help text somewhere in the near of the search box. Maybe show the modifiers when the user hover over the search box or the textbox is active or so, because I guess that many people won't remember just the one modifier they need at the moment. And I'm not sure if amount_less and amount_more is the best choice - what do you think about amount_min and amount_max?

**Comment by JC5** [comment]
Apologies, I thought I already pushed the new view!

Which I will expand with your suggestions, but probably somewhere during the next release. As for the search terms, why not both? ^^

**Comment by JC5** [comment]
Alright I'm closing old issues. I think is is implemented pretty well, could you re-open this issue or create a new one when you think of something you're missing?
