### ISSUE TITLE
new user bug: redirect to route `new-user.index` fails because of return type on index function

### ISSUE THREAD

**Issue by sirtimbly** [firefly-iii/firefly-iii#5103]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After successfully setting up Firefly for the first time and creating my first user, the home controller attempted to redirect me to the `new-user` route. Unfortunately, returning this redirect resulted in a type error.

```
TypeError
HTTP 500 Internal Server Error
Return value of FireflyIII\Http\Controllers\HomeController::index() must be an instance of FireflyIII\Http\Controllers\mixed, instance of Illuminate\Http\RedirectResponse returned
Exception
TypeError
in /volume1/web/firefly/app/Http/Controllers/HomeController.php (line 115)
        $types = config('firefly.accountTypesByIdentifier.asset');        $count = $repository->count($types);        Log::channel('audit')->info('User visits homepage.');        if (0 === $count) {            return redirect(route('new-user.index'));        }        $subTitle     = (string)trans('firefly.welcome_back');        $transactions = [];        $frontPage    = app('preferences')->getFresh('frontPageAccounts', $repository->getAccountsByType([AccountType::ASSET])->pluck('id')->toArray());        /** @var Carbon $start */
```

### Expected behaviour

Should have redirected to the new user route.

### Debug information

Debug information generated at 2021-09-20 16:06:06 America/Denver for Firefly III version **5.6.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.0 |
| Firefly III API | 1.5.3 |
| PHP | 7.4.9 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | bbfe0cb3-5dd3-40e2-b73a-209c19babd89 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| System TZ | America/Denver |
| Browser TZ | America/Denver |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 |

### Steps to reproduce

0. Set up new installation, 
1. migrate fresh new database, 
2. Visit the web site for the first time, create new user and click submit
3. See error message about route redirect

### Additional info

Removing the `mixed` return type on this line https://github.com/firefly-iii/firefly-iii/blob/cf16398794763c6458713ad28eb665d4b20d188d/app/Http/Controllers/HomeController.php#L108
allowed me to get through to the new user route for the first time.

**Comment by JC5** [comment]
You need php 8.0
