### ISSUE TITLE
Changing the date range on a v1 page makes the account screen in V2 misleading

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#5104]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

In 5.6.0 (v2), if you change the date range on a v1 page (e.g. reconciliation), and then go to an account page (like you do after you finish reconciling) the account page claims to be using the date range from v1, but is actually using the date range from v2.

### Expected behaviour

The date range on the account page should accurately reflect the date range used by the listed transactions.

### Debug information

Debug information generated at 2021-09-20 22:13:13 America/New_York for Firefly III version **5.6.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.0 |
| Firefly III API | 1.5.3 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-08-20 00:00:00 |
| Session end | 2021-09-19 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 |

### Steps to reproduce

1. Be in V2
2. Take note of what your V2 date range is
3. Go to a V1 page (such as reconciliation)
4. Change the date range so that it is different from the V2 date range
5. Go to an account page
6. See how the date range shown at the top of the screen does not accurately reflect the date range being used by the transaction table.

### Additional info

I bet this would be really apparent with an account chart.

You cannot change the date range on the transaction page itself, so this bug is actually hard to really demonstrate if you don't go through the steps yourself.

**Comment by JC5** [comment]
Ah good call, the title is generated by PHP (and uses your session data), while the page uses local storage. They can drift. Will pick it up!

**Comment by JC5** [comment]
Will be fixed in the next release.

**Comment by death2cupbots** [comment]
I also noticed the subscriptions (aka bills) screen seems to be stuck in July. Does this fix that, or do you want me to submit a new bug report?

**Comment by JC5** [comment]
Please open a new one, it's easier to keep track that way. Thanks!
