### ISSUE TITLE
Paperclip icon for transactions with attachments in v2 layout

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#5108]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I sadly recognized that after updating to 5.6 the (overall good looking) v2 layout style for the expenses page doesn't have an indicator for transactions with attachments anymore. In v1 there used to be the paperclip icon in front.
I kinda used it pretty often to orientate among the long list of transactions (which may sound odd, I know)

### Solution

Adding an some kind of indicator again. Maybe a separate (hideable?) column.

### What are alternatives?

Opening each transaction one by one to see the attachment in the opened details

### Additional context

I know Firefly is no tool that gets developed according to specific whishes of single users. And I don't know how many users really want that back and how much work it is to re-implement it.
But I thought I give it a try and ask for it :D

**Comment by JC5** [comment]
Yes, that's missing. I'll write it down!

**Comment by JC5** [comment]
Fixed in the next release.
