### ISSUE TITLE
LDAP authentication broken with docker on latest version

### ISSUE THREAD

**Issue by ROB-ernst** [firefly-iii/firefly-iii#5109]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After upgrading to version 5.6.0 and correcting the LDAP settings in my .env file according to [the documentation](https://docs.firefly-iii.org/firefly-iii/advanced-installation/authentication/), I cannot login to my Firefly III instance. I get an "Error 500" with the message "Authentication user provider [ldap] is not defined."

Downgrading my image to version 5.5.13 and reverting the changes in .env will result in a working instance.

### Expected behaviour

Allow login to my instance based on the previously working LDAP authentication.

### Debug information

The /debug page cannot be reached, same Error 500.

### Steps to reproduce

I did some digging and it seems that, contrary to what the documentation says, the docker image in fact does not automatically install the required LDAP packages. As far as I can tell, the installation should happen in the `entrypoint.sh` script in the docker image (hosted on [Azure](https://dev.azure.com/Firefly-III/_git/MainImage?path=/entrypoint.sh)). To me, it looks like it checks the environment variable `LOGIN_PROVIDER` and compares it to `ldap` (line 97). Furthermore, the script still refers to the (outdated?) LDAP libraries and does not use the ones listed in the documentation.

According to the documentation, however, `LOGIN_PROVIDER` is not needed anymore and we should instead use `AUTHENTICATION_GUARD=ldap`. This, however, does not trigger installation of any LDAP packages, which is confirmed in the docker logs where I see the message `Will not download LDAP packages.`. Further down, however, I see the message 

```
In CreatesUserProviders.php line 42:
                                                       
  Authentication user provider [ldap] is not defined. 
```

What I tried:
1. Set the environment variable `LOGIN_PROVIDER` to `ldap` -- Docker tries to install the adldap-packages, but fails:

```
Using version ^6.1 for adldap2/adldap2-laravel
./composer.json has been updated
Running composer update adldap2/adldap2-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - grumpydictator/firefly-iii is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - roave/security-advisories dev-master conflicts with roave/security-advisories dev-master.
    - roave/security-advisories is locked to version dev-master and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
```

2. Supply a modified entrypoint.sh script to the docker image (with this code, as suggested in the documentation):

```
# install LDAP only when necessary.
if [[ $LOGIN_PROVIDER == "ldap" ]]; then
#   composer require adldap2/adldap2-laravel --no-install --no-scripts --no-plugins --no-progress
  composer require directorytree/ldaprecord-laravel --no-install --no-scripts --no-plugins --no-progress
  composer install --no-dev --no-scripts --no-plugins --no-progress
fi
```

This fails as well, giving me the following output in the docker logs:

```
Using version ^2.4 for directorytree/ldaprecord-laravel
./composer.json has been updated
Running composer update directorytree/ldaprecord-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - grumpydictator/firefly-iii is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - roave/security-advisories dev-master conflicts with roave/security-advisories dev-master.
    - roave/security-advisories is locked to version dev-master and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
```

So, I'm out of luck and ideas. 

Thank you for your support!

**Comment by JC5** [comment]
Thanks for letting me know. I could use debugging this using the `develop` tag. Is that OK?

**Comment by ROB-ernst** [comment]
Yes, of course!

**Comment by JC5** [comment]
The latest [develop](https://hub.docker.com/layers/fireflyiii/core/develop/images/sha256-a1eea7cb2c4ac8954155f9db4664d767ff5705bc5d51efcd90f7ac90b8e6c980?context=explore) tag should install the right packages. Have not been able to test this myself yet, but know I'm working on it.

**Comment by ROB-ernst** [comment]
I just tried, doesn't work, unfortunately. The docker log file snippet:

```
Using version ^2.4 for directorytree/ldaprecord-laravel
./composer.json has been updated
Running composer update directorytree/ldaprecord-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - grumpydictator/firefly-iii is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - roave/security-advisories dev-master conflicts with roave/security-advisories dev-master.
    - roave/security-advisories is locked to version dev-master and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
```

Similarly, when I use `docker exec -it ff_iii_app bash` to get a bash shell inside the container, and try to manually install the required packages, I get the following errors:

```
root@fdd71a9d4928:/var/www/html# composer require directorytree/ldaprecord-laravel --no-install --no-scripts --no-plugins --no-progress

Using version ^2.4 for directorytree/ldaprecord-laravel
./composer.json has been updated
Running composer update directorytree/ldaprecord-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - grumpydictator/firefly-iii is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - roave/security-advisories dev-master conflicts with roave/security-advisories dev-master.
    - roave/security-advisories is locked to version dev-master and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

root@fdd71a9d4928:/var/www/html#
```

**Comment by nebulade** [comment]
I came here to report the same. I am trying to update the Cloudron package. In our case the Dockerfile build errors with the same at https://git.cloudron.io/cloudron/firefly-iii-app/-/blob/master/Dockerfile#L23

What the additional required packages?

**Comment by JC5** [comment]
Let me find out what's wrong and keep you posted. My apologies for the inconvenience :+1:

**Comment by JC5** [comment]
I believe the current `develop` tag will successfully install the necessary packages. I appreciate your feedback.

**Comment by ROB-ernst** [comment]
Great, thank you! It's working just fine now.

**Comment by JC5** [comment]
No problem! Allow me to keep this open until 5.6.1 is released 👍

**Comment by JC5** [comment]
Wait, that may not be necessary. @nebulade, @ROB-ernst, would you mind pulling 5.6.0 fresh and see if that fixes the issue?

**Comment by ROB-ernst** [comment]
I just tried pulling 5.6.0 - it doesn't work. Log output:

```
Using version ^2.4 for directorytree/ldaprecord-laravel
./composer.json has been updated
Running composer update directorytree/ldaprecord-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - grumpydictator/firefly-iii is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - roave/security-advisories dev-master conflicts with roave/security-advisories dev-master.
    - roave/security-advisories is locked to version dev-master and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
```

**Comment by nebulade** [comment]
I can confirm using the `develop` branch fixes the LDAP insallation issue, however same as @ROB-ernst this is not the case for the 5.6.0 release.

**Comment by JC5** [comment]
Mmmm, sorry about that :(

I will do some extra checks before I bother you again!

**Comment by nebulade** [comment]
All good, we are very glad you are looking into it :) 
Let us know if there is anything we can provide to help.

**Comment by JC5** [comment]
Thanks guys! 

This will be fixed in 5.6.1, which I will verify before the release goes out. The change I made to the necessary packages is in `develop`, which you tested successfully.

**Comment by JC5** [comment]
5.6.1 is out, and I believe this to be fixed. :+1:

**Comment by nebulade** [comment]
Perfect, the ldap install works now! Now having to see if and how existing user records can be migrated.

**Comment by JC5** [comment]
What migration?

**Comment by nebulade** [comment]
To the new implementation. I wasn't sure if we need to map users differently. So far I found out that I don't seem to be able to specify a custom LDAP filter anymore. Apparently there is `ADLDAP_AUTH_FILTER` to be set, but as far as I can tell this is not used for non-AD.
The filter seems to always be `(&(objectclass=top)(objectclass=person)(objectclass=organizationalperson)(objectclass=inetorgperson)(username=<loginname>))` which is wrong in the Cloudron case.

Should I open a new issue instead of continuing here?

**Comment by JC5** [comment]
Yes please do. I can set up the right code and refer to the correct issue.
