### ISSUE TITLE
Right-align numbers

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#511]
Hi, are the numbers left-aligned for a special purpose? In my opinion they should be right-aligned in tables (transactions, bills, reports, ...) for better readability.

**Comment by JC5** [comment]
That's a good idea, it should not be difficult to implement. Thanks!

**Comment by JC5** [comment]
Done! You can see the result at the [demo site](https://firefly-iii.nder.be/). Next release should be end of the week

**Comment by xpfgsyb** [comment]
Like it :)
But I found two places where the numbers are still left-aligned:
- categories / some category / month list on the right
- reports

**Comment by JC5** [comment]
Darn, and I thought I had them all. I've just refreshed the demo site, check it out. I think this is everything.

**Comment by xpfgsyb** [comment]
Everything except the piggy banks. But then you got them all I think.
