### ISSUE TITLE
Subscriptions (a.k.a. bills) screen stuck in July in V2

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#5114]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

In 5.6.1 (v2) (but also present in 5.6.0), the subscriptions screen (aka the bills screen) only displays transactions from July, regardless of what your date setting is. V1 displays correctly.

### Expected behaviour

It should follow the date range Firefly-iii is currently set to. So, for example, if the rest of the site is displaying September, the subscriptions screen should also show September.

### Debug information

Debug information generated at 2021-09-25 08:52:14 America/New_York for Firefly III version **5.6.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.1 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 |

### Steps to reproduce

1. Be in V2.
2. Have ~~bills~~ subscriptions which have payments from July or earlier associated with them, but also some from August or September.
3. Go to the subscriptions page.
4. See that you can only see information as if the selected date range were July.

### Additional info

I'm only able to change the date range on the main page now in V2. I'm imagining that's intentional design, but it makes testing difficult.

This happens on both my desktop and laptop. I tried using the clear cache button, but it didn't fix the problem.

**Comment by JC5** [comment]
Thanks, I'll check it out!

**Comment by JC5** [comment]
Fixed in the new release :+1:
