### ISSUE TITLE
Charts and Treemaps not working in 5.6.0/1 with v2 layout

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#5115]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I open the transactions page or an account the sections for charts and treemaps are not showing any content.
This was already partly discussed [here](https://github.com/firefly-iii/firefly-iii/issues/5100). But since this is a seperate issue I thought I create a new one.

### Expected behaviour

Maybe I am getting this whole feature wrong but I expected the sections to show some graphics and charts about the accounts or spendings - like the old charts in v1 layout did. I also tried draging accounts to the treemap area abd then dropping them. But apparently this didn't work either.

### Debug information

Debug information generated at 2021-09-25 20:38:03 Europe/Amsterdam for Firefly III version **5.6.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.1 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | de5a88fc-4cc6-4da2-a5d0-c468a4b1529f |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2020-10-30 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0 |

### Steps to reproduce

1. open the transactions page or a specific account
2. look at the treemap or charts area at the top of the page
3. don't see any graphics there

### Additional info

![treemaps1](https://user-images.githubusercontent.com/81714586/134782919-8efb689f-c004-4b20-9387-7f4595853a00.png)
![treemaps2](https://user-images.githubusercontent.com/81714586/134782920-0a6882f6-1014-480d-a0b3-ac5474ee30f6.png)
![treemaps3](https://user-images.githubusercontent.com/81714586/134782923-619915d8-0504-481e-8730-dc1ed20f969e.png)
![treemaps4](https://user-images.githubusercontent.com/81714586/134782921-d695afe9-187f-4ec5-811c-b2b46bb9aba7.png)

**Comment by JC5** [comment]
The layout is very much in beta. It's a reminder for myself.

**Comment by Styleflix** [comment]
okay, good to know ^^
so, at the moment there are no charts or visualisations for accounts or transcations when v2 is enabled (?)

**Comment by JC5** [comment]
Only on the dashboard.

**Comment by steakhutzeee** [comment]
Jumping in in the discussion for the following issue:

My new transactions are correctly listed in the dashboard.

The revenues are updated correctly on the /deposit page.

The expenses on the /withdrawal page are not updated instead.

**Comment by Styleflix** [comment]
I noticed the same behaviour about newly added transactions not showing up in the withdrawals list after adding them. But there is an reload button that says "TODO". So I think we just have to be patient for the v2 ui beeing in a final state. Sometimes it helps re-adjusting the time span and then opening the withdrawals page again. Or logging in and out.
