### ISSUE TITLE
Icon for transfer transactions missing in v2 layout

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#5116]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

This is just a minor cosmetic thing but I thought I report it anyway.
In a list of transactions the icon for transfer transactions is still missing when the v2 layout is active.

### Expected behaviour

While for expenses and revenues the are ingoing and outgoing arrows there is no icon for transfer transactions.

### Debug information

Debug information generated at 2021-09-25 21:04:47 Europe/Amsterdam for Firefly III version **5.6.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.1 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | de5a88fc-4cc6-4da2-a5d0-c468a4b1529f |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2020-10-30 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0 |

### Steps to reproduce

1. Open the transfer transcations list or an account with transfer transcations
2. Look at the front of the transactions
3. See that there is no arrow icon for transfer transcations 

### Additional info

![indicator](https://user-images.githubusercontent.com/81714586/134783402-b3f8a5e5-1dfe-42a0-8524-0d11756fc00b.png)

**Comment by JC5** [comment]
Thanks for letting me know!

**Comment by JC5** [comment]
Fixed in the next release.
