### ISSUE TITLE
Automatic Credit card transfers

### ISSUE THREAD

**Issue by WorldTeacher** [firefly-iii/firefly-iii#5125]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like a way to have my credit card set back to 0 each month, either by a rule or by inputting an asset account from which the credit card would get its money.

### Solution

As far as I understand, using a credit card in Firefly III right now requires you to create an expenses transaction (from the credit card to the expense account) and a transfer transaction from your savings account (or wherever your credit card gets its money from) to the credit card. While it is easy to create these 2 transactions, I think having a way to automatically pull the money at the end of the month would make displaying/using a credit card easier.

### What are alternatives?

Creating both an expenses transaction as well as a transfer transaction. (As far as I know, might've missed something)
While it is easy, a way to automate it would be handier, I think.

### Additional context

(continuation from Solution, as I think this might not be for the solution, just a random thought)

![image](https://user-images.githubusercontent.com/41587052/134900851-5b50831c-af40-4dac-9c33-e05c88e9a293.png)
As shown in the image, a credit card will already ask for a monthly payment date, so I thought "Why not create a date, on which the credit card pulls the amount of money it needs in order to get back to 0" (at least that's how my credit card works, not sure if that's how other banks work with their credit cards)
If that's too hard to make (or impossible with the methods) another thought was to be able to create a rule, which would, when triggered, create a transfer from the savings account to the credit card (because right now, it is not possible to get money to the credit card, it doesn't show up in the destination account)

If I got anything wrong or misunderstood some mechanics, please correct me.

**Comment by JC5** [comment]
I'll write it down as an enhancement. I like the idea but I have no idea yet how to do it. Code wise it's easy but it has to be manageable and configurable etc.

**Comment by WorldTeacher** [comment]
Thanks for the fast answer 
Take your time, it won't do any good if a feature is implemented but no one knows how to use it

**Comment by Styleflix** [comment]
I want to add that a similar use case (not completely the same) is about PayPal accounts. My PayPal is connected to my bank account. And everytime I pay something using PayPal, PayPal uses my bank account if there is no credit left in my PayPal account.
Which means I mostly have to create two transactions in Firefly. One for the expense transaction of the PayPal account and one transfer transaction from my bank account to PayPal.
If there was a feature that implemented this logic, it would be very cool.

But if it's too complicated to design a feature like that, it's not a problem. Since it's nothing that doesn't already works with some extra steps. But if implemented for credit card accounts, I thought it wouldn't take much to apply it on PayPal accounts too.

**Comment by WorldTeacher** [comment]
> I want to add that a similar use case (not completely the same) is about PayPal accounts. My PayPal is connected to my bank account. And everytime I pay something using PayPal, PayPal uses my bank account if there is no credit left in my PayPal account.
> Which means I mostly have to create two transactions in Firefly. One for the expense transaction of the PayPal account and one transfer transaction from my bank account to PayPal.
> If there was a feature that implemented this logic, it would be very cool.

In theory, once the credit card system is created, you could configure it to work for paypal (I think) . I use paypal too, but I just write "paid via paypal" in the notes area and add a tag "paypal". This works fine for me, given that I don't use PayPal that much.

**Comment by Styleflix** [comment]
I use it quite often and since PayPal has it's own balance (e.g. when someone sends me money via paypal) I wanted it to have an extra account in Firefly too. So going with the two seperate transactions is the only propper way for me at the moment.

**Comment by WorldTeacher** [comment]
I'll probably do that once I'm paying more with Paypal, will see when the time comes.

**Comment by michelebossa** [comment]
Hi all,
I'm trying this tool and i have two credit card at Moment i need to made at begining of month a transfers from my bank  ti credit card to have a 0 balance right? There is no automatic transaction.

I think if it is missed will be a correct and nice features to add.

Thanks

**Comment by wisewtf** [comment]
Hey everyone!

Any news on this feature? I only just recently installed Firefly and I don't see anything that resemble enabling this feature on the current version of the software.

I have set up an asset account as a credit card, and picked a payment date. Right now it's obviously running in the red, because I started the balance from 0. What I worry is that it won't reset the next month and I'll have to adjust the opening balance every month? Or mud the statistics by doing a transaction?

I would appreciate some clarification on the matter, if possible. 

Thank you!

**Comment by JC5** [comment]
So where is the money coming from when you reset to zero? It just magically appears? Get me one of those cards!

**Comment by wisewtf** [comment]
> So where is the money coming from when you reset to zero? It just magically appears? Get me one of those cards!

That's exactly what happens when you're not using a revolving credit card. The plafond resets and you get charged for the total amount spent the previous month. Meaning I have to track that entire amount and then reset the asset to 0, exactly like the card does.

**Comment by JC5** [comment]
Yes, so you pay for it yourself. That was my point. So, why not create a transfer from your asset account to the credit card with the exact amount? Assuming that's the source of the reset.

I was actually planning on cancelling this feature. I've already learned there are dozens of ways to settle credit cards and I'm not going to build options for each of them.

**Comment by wisewtf** [comment]
> Yes, so you pay for it yourself. That was my point. So, why not create a transfer from your asset account to the credit card with the exact amount? Assuming that's the source of the reset.
> 
> 
> 
> I was actually planning on cancelling this feature. I've already learned there are dozens of ways to settle credit cards and I'm not going to build options for each of them.

That's fair. Thank you for your time.
