### ISSUE TITLE
Unable to use clone functionality from search menu

### ISSUE THREAD

**Issue by JakeMHughes** [firefly-iii/firefly-iii#5134]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Unable to use clone functionality from search menu. Cloning from other menus seems to work fine. 

### Expected behaviour

I expect it to create a new transaction but instead it takes me back to the dashboard ( I dont see any errors in browser console either)

### Debug information

Debug information generated at 2021-09-28 21:28:26 Etc/UTC for Firefly III version **5.6.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.1 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 1c66aa77-0d30-4317-8563-7845bbba86d3 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| System TZ | Etc/UTC |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 |

### Steps to reproduce

(this works on demo site as well)
1. Search for an item (used 'Bla' for demo)
2. Click actions drop down menu
3. Select Clone

**Comment by JC5** [comment]
Indeed, I'll pick it up :+1:
