### ISSUE TITLE
Transaction Autofill boxes double autofill (v2)

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#5135]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

At least as recently as 5.6.0, when you are making a transaction in V2, if you have a description or a category (or possibly accounts or tags) that is entirely at the start of a second description or category and the longer description or category comes first in the suggestion list, the autofill will select the longer choice when you select the shorter one if you select it with the keyboard.
![autofill](https://user-images.githubusercontent.com/21091510/135201160-dc91b5e7-ab4f-4c33-bc05-14af703afe49.gif)

### Expected behaviour

It should fill in the suggestion I picked.

### Debug information

Debug information generated at 2021-09-28 23:43:04 America/New_York for Firefly III version **5.6.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.1 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-08-20 00:00:00 |
| Session end | 2021-09-19 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 |

### Steps to reproduce

1. Be in V2
2. Have 2 descriptions or categories that start the same, but one has extra stuff at the end (e.g. AA and AA A)
3. Have the longer option appear first on the suggestion list (have it be used in a more recent transaction)
4. Start typing the shorter option out and see that both options appear, with the longer option first
5. Select the shorter option with your keyboard and then press enter
6. See that the longer option has been selected.

**Comment by JC5** [comment]
I'll see what I can do, but it's 100% a library, and I may not have the options to control it.

**Comment by JC5** [comment]
I can't replicate this, with the entries I have it keeps selecting the right one.

**Comment by death2cupbots** [comment]
I just did a little more testing and it looks like it only happens in browsers like Chrome and Brave. I'm not seeing it happen in Firefox.

**Comment by JC5** [comment]
https://www.loom.com/share/40d09c75f5764565a46dfe1d20c32112

Chrome Version 95.0.4638.69 (Official Build) (x86_64) on MacOS Montery

**Comment by death2cupbots** [comment]
Oh, it should be more like "Saving" and "Saving some money." The longer option has to start with the entire text of the shorter option.

I'm seeing this in Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit) on Windows 10. I can check my Linux versions when I get on my desktop.

**Comment by JC5** [comment]
And now we wait:

https://github.com/mattzollinhofer/vue-typeahead-bootstrap/issues/137

**Comment by death2cupbots** [comment]
Oh perfect! Hope they can fix it!

**Comment by JC5** [comment]
Closed for v3. No worries, all tickets are in my bookmarks.
