### ISSUE TITLE
Same Budget for every month?

### ISSUE THREAD

**Issue by schwalberich** [firefly-iii/firefly-iii#514]
Hello,

is it possible to have the budgets with the same Values as in the previous month?
I for myself calculate my budget once and use the same for every following month,
but it is quite annoying to have two tabs open at the same time, where one shows me my
current month/budget and another showing me the same for the previous month.

Best Regards

**Comment by JC5** [comment]
No. It's incredibly difficult to reliably generate new values for future months, weeks or other periods. I've tried it in the past and there are always horrible bugs. So you're stuck setting them manually once  a month.
