### ISSUE TITLE
[CSV-Importer] - import tag with duplicate

### ISSUE THREAD

**Issue by TWART016** [firefly-iii/firefly-iii#5141]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi,

I have a csv file from last 30 and last 90 days. That means 30 days are double.

First I import 30 days file which works fine. The tag `CSV Import on [timestamp]` will be created and mapped to the transactions from the import.
After that I import 90 days file. The transaction will be imported, but not the duplicated files (detection method: content-based). That's all fine. The tag `CSV Import on [timestamp]` will be created but NOT mapped to the transactions

Otherwise. Is it possible to apply a specific tag a while an import?

Importer v2.6.1
Frontend 5.6.0

### Expected behaviour

The tag `CSV Import on [timestamp]` should be mapped to the new imported transactions

### Debug information

-

**Comment by JC5** [comment]
OK so in the case of the second set of transactions, the 60 days that are not duplicated don't get the right tag?

**Comment by TWART016** [comment]
I found the problem. I had to increase the time range to several months. 

Is it possible to apply a specific tag a while an import or rename the default created tag?

**Comment by TWART016** [comment]
The tag was created and mapped corretly. By default I just can see data from this month. On the top right I extended to a custom range.

Renaming of the default tag works fine. It would be great if I can add a tag for all transaction inside an import job.
