### ISSUE TITLE
Bill Creation Issues (v2)

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#5142]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am running Firefly III 5.6.1 (v2) and when I go to create a new bill, it does not bring me to create a new rule and it does not show up on the list of bills.

### Expected behaviour

It should ask me to create a rule and appear on the list of bills.

### Debug information

Debug information generated at 2021-09-30 14:55:09 America/New_York for Firefly III version **5.6.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.1 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 |

### Steps to reproduce

1. Be in V2
2. Create a new bill
3. Fill in Name, Minimum Amount, Maximum Amount, and Start Date
4. Select "Store New Bill"
5. Be brought back to whatever screen you were last on (or the bill screen sometimes)
6. See that you have not created a new rule and the bill has not been added to the new list.

### Additional info

It does save the bill.
It does not seem to matter when the date is.

If this is really 2 bugs, I can split this into 2 issues if you'd like.

**Comment by JC5** [comment]
Thanks for letting me know, I'll check it out. The rule creation flow will be some time.

**Comment by JC5** [comment]
Page will get a small refresh in the new release, you can see what I plan to do.

**Comment by JC5** [comment]
Closed for v3. No worries, all tickets are in my bookmarks.
