### ISSUE TITLE
Asset account notes emptied

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#5143]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hey JC5,

Today I have noticed the Notes part of my asset accounts are empty. I'm using version 5.6.1. I had saved the information related to my account like the login I have to use for the online banking, my card number, expiration date etc... For my credit cards all the information like expiration and CVC code...

All that is now empty. I checked mysql dump and the information is still present in the notes table. Is there something broken here?

Thanks!

### Expected behaviour

My notes field populated with info from the database

### Debug information

I'm adding /debug to my account page but I get an HTTP 404

**Comment by JC5** [comment]
Click the version number for debug information. In 5.6.1, I can't replicate this.

**Comment by death2cupbots** [comment]
I poked around and V2 doesn't seem to have anywhere to display account notes right now and when you go to edit the account, the notes don't show. The notes are still there in V1, though, and you can save notes on accounts in V2 and they'll show up in V1.

**Comment by MacPaille** [comment]
Indeed I confirm the notes part is fine in v1 layout. But it's empty in v2.
Is it a known issue? Now I feel I may have read something about that somewhere...

Don't think the debug info on the edit page of my account will really help...
Debug information generated at 2021-10-01 06:41:59 Europe/Brussels for Firefly III version **5.6.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.1 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 23c4e719-c4b6-4e7c-9596-758253dfff31 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Brussels |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-10-01 00:00:00 |
| Session end | 2021-10-31 23:59:59 |
| Session first | 2006-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 |

**Comment by MacPaille** [comment]
Indeed I forgot to mention interface v2... Feel free to close this issue as it's a WiP you may have tracking of it somewhere else 👍

**Comment by JC5** [comment]
No worries, it's on the list!
