### ISSUE TITLE
Remove rule triggers/actions broken

### ISSUE THREAD

**Issue by Alaksin** [firefly-iii/firefly-iii#5144]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When editing a rule, if I try to remove a trigger or action, only the delete icon gets removed, the rest of the row stays. When pressing save the trigger/action may or may not be removed, it's a lucky roll. Most of the times only one trigger/action is removed even if I remove several.

### Expected behaviour

The whole row should be removed and when saving the deleted triggers/actions should be removed from the rule

### Debug information

Debug information generated at 2021-10-01 09:35:48 Asia/Kuala_Lumpur for Firefly III version **5.6.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.1 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 6ec83b7f-8f96-4c74-b42c-97b6c8e09ab6 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | Asia/Kuala_Lumpur |
| Browser TZ | Asia/Kuala_Lumpur |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-10-01 00:00:00 |
| Session end | 2021-10-31 23:59:59 |
| Session first | 2017-08-25 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0 |

### Steps to reproduce

1. Edit a rule, preferable with several triggers/actions
2. Remove some triggers/actions in random order
3. Save

**Comment by JC5** [comment]
I see what you mean. For the time being, click on the red part of the button.
