### ISSUE TITLE
Error in handling custom date range

### ISSUE THREAD

**Issue by schwalberich** [firefly-iii/firefly-iii#515]
Hello,

I found an issue with showing custom date ranges.
If I do set a time range to e.g. 23. January to 16. February everything's good and shows
me my Graphs, Transactions and everything.
Then if I want to go back to "normal" I face two problems:
- If I checked a date range beginning in January I can't just click on January in the time box as it's already highlighted
- If I click a month in the time box, it doesn't show me the complete month but unstead my custom range begging in the month (With the example above if I click March I have the time range 23. March - 16 June but not as expected only the complete March)

Best Regards

**Comment by JC5** [comment]
I know, it gets stuck on a period as long as you previously selected: 1-7 jan, 1-7 feb, etc.

Best thing you can do at the moment is pick a custom range which is exactly one month. That resets it back to one month.
