### ISSUE TITLE
Currencies should not be comma separated in locales with comma as separator

### ISSUE THREAD

**Issue by EmmanuelMess** [firefly-iii/firefly-iii#5150]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

"Net worth: u$d xx,xx, $ x.xxx" should not be comma separated, it should use semicolon, as my locale is es_ar. 

### Expected behaviour

"Net worth: u$d xx,xx; $ x.xxx"

### Debug information

Debug information generated at 2021-10-01 12:42:53 Europe/Amsterdam for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 7cb34eb9-5c74-45eb-b8bd-518fec9cbe55 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-10-01 00:00:00 |
| Session end | 2021-10-31 23:59:59 |
| Session first | 2021-10-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | es_AR |
| Attempt at "es_AR.utf8" | 'es_AR.utf8' |
| Attempt at "es_AR.UTF-8" | 'es_AR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0 |

### Steps to reproduce

1. Use multiple currencies (have accounts with those currencies) and have es_ar locale.

**Comment by JC5** [comment]
Please make sure you install the necessary locale packages.

**Comment by JC5** [comment]
Sorry now I see what you mean. The amounts are separated with a comma. It has nothing to do with locales, it's the style I have chosen to separate these items. It's not something that can be configured.

**Comment by EmmanuelMess** [comment]
> Sorry now I see what you mean. The amounts are separated with a comma. It has nothing to do with locales, it's the style I have chosen to separate these items. It's not something that can be configured.

It should be, it is confusing.
