### ISSUE TITLE
Can't set different currency for account

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#516]
I've created multiple accounts and some of them have different currency than default one set in the app. There is a currency selector in the account details, but whatever currency I select it always falls back to the default one.
Issue is probably related to #305.

**Comment by JC5** [comment]
I know, it's a work in progress. Supporting different currencies at the same time is pretty difficult. Support will slowly extend over time. :)

**Comment by skibbipl** [comment]
OK, I hope the currencies support will appear soon, as it's a pretty showstopper for me right now. I need this on a daily basis.
Anyway I'll keep using the app and will spam you with more issues :)
