### ISSUE TITLE
v2 source and destination accounts don't get cleared when reset after submission

### ISSUE THREAD

**Issue by aronwk-aaron** [firefly-iii/firefly-iii#5164]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

In v2

After storing a transaction, source and destination account do not get cleared when "Reset form after submission" is checked.

Additionally, this causes issues since some accounts can have their amount in their name, making that account invalid (since you just changes the amount with the transaction that) and throwing different, not clear errors.

### Expected behaviour

source and destination account get cleared when "Reset form after submission" is checked, when submitting a transaction

### Debug information

Debug information generated at 2021-10-09 18:39:02 America/Chicago for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 9f428eb2-dc92-4371-af1d-79e9779c3d49 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/Chicago |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-10-01 00:00:00 |
| Session end | 2021-10-31 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0 |

### Steps to reproduce

1. make a transaction
2. check "After storing, return here to create another one." and " Reset form after submission"
3. Source and Destination account don't get cleared

**Comment by JC5** [comment]
Fixed in the new release.
