### ISSUE TITLE
V2: Selecting an autofill option should take you to the next field

### ISSUE THREAD

**Issue by aronwk-aaron** [firefly-iii/firefly-iii#5165]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Currently, when selection an autofill option in v2, it drops your cursor back into the field that you just autofilled.

### Solution

instead it would be nice to drop it down to the next field so that it's already where you need to be.

### Additional context

When keying in many transaction, I have to press tab 2-3 times to get to the next field. kinda annoying. The form flow was a bit better in v1, but I really like the looks and style of v2, so it would be great to enhance the form flow for people like me who input a lot at once, and who are keyboard power users. I typically don't use the mouse, except to scroll on my account page that I'm keying in transaction from

**Comment by JC5** [comment]
Yeah the auto-complete drops the focus entirely when you select something. If you put it back, it will open the dropdown again. Jumping to the next field would be a good alternative, thanks!

**Comment by JC5** [comment]
Auto switch to next field is done for the accounts, the others not yet.
