### ISSUE TITLE
V2: previous autofill steals cursor after clink on next field after an autofill

### ISSUE THREAD

**Issue by aronwk-aaron** [firefly-iii/firefly-iii#5166]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

when making a transaction:
clicking on amount after autofilling destination account, it selects the destination account field instead of the amount field.

### Expected behaviour

Clicking on the amount field should select the amount field and put the cursor in it

### Debug information

Debug information generated at 2021-10-09 19:30:36 America/Chicago for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 9f428eb2-dc92-4371-af1d-79e9779c3d49 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/Chicago |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-10-01 00:00:00 |
| Session end | 2021-10-31 23:59:59 |
| Session first | 2014-07-15 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0 |

### Steps to reproduce

1. Select an autofill from the dropdown on the destination account field
2. click in the amount field
3. it goes back up to the destination account field instead of the amount field

### Additional info

This is probably an issue with autofill in other places too

**Comment by JC5** [comment]
I can't seem to replicate this in Firefox (Mac). It selects the amount just fine.

**Comment by cestpasphoto** [comment]
I have a similar issue, when _entering_ either destination or source accounts on firefox for mac. See this very short [screencast](https://ufile.io/gem99mcf).

**Comment by aronwk-aaron** [comment]
I'll see about getting a recording of it happening and post it on YT

**Comment by aronwk-aaron** [comment]
https://youtu.be/uGH4jws-EZ8
Also to note, This is on the same version I was running when making this ticket
I can try checking out the develop branch and seeing if the behavior is fixed there.
 #5165 may have fixed this as well

**Comment by JC5** [comment]
Should be fixed in the next release!
