### ISSUE TITLE
Clone and Edit button

### ISSUE THREAD

**Issue by aronwk-aaron** [firefly-iii/firefly-iii#5167]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

An additional option to clone for dropping you into editing the transaction you just cloned

### Solution

Clone and edit button on transaction under the clone button

### Additional context

This would be a nice addition, since most of the time when I'm cloning something, I need to edit the date and/or the amount, but not the other fields.
would be a nice way to enhance the workflow

**Comment by JC5** [comment]
Hey, thanks for the suggestion. I think such a button wouldn't be a good addition. I believe the choice between "clone" and "clone and edit" would destroy any muscle memory and speaking for myself, I don't mind having the choice to edit *after* cloning the transaction.
