### ISSUE TITLE
Polish translation + some issues

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#517]
I've started translating Firefly to Polish. Can you enable Polish translation in Crowdin?
Also I've found that some strings cannot be translated, for example:
![obraz](https://cloud.githubusercontent.com/assets/4746858/21587088/9937cfbe-d0d8-11e6-822a-c9c642ce7f01.png)
![obraz](https://cloud.githubusercontent.com/assets/4746858/21587098/b44c7340-d0d8-11e6-9819-2b84163138fd.png)

**Comment by JC5** [comment]
I've fixed the first one, and another tag I happened to come across.

The "default rules" rule group is generated when you first visit the Rules-page. If your installation was in English at the time, the group will have an English title. But the translation files have a translation for this title.

I've added Polish to Crowdin. All I need from you is the word "Polish" in Polish.

**Comment by skibbipl** [comment]
Can I rename somehow "Default rules" in the database?

**Comment by JC5** [comment]
There is an edit button next to the title. Check for the three dots.
