### ISSUE TITLE
Convert new IP email to new login

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#5173]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Currently, the `New login on Firefly III` email is sent when a new IP is detected. It happens even if it's the same browser and session, and the user didn't enter the credentials. I sometimes receive it multiple times a day with my current set of connections.

### Solution

I'd rather much prefer to have it on actual new logins. As an additional input, I think this is the industry practice. Or at least I can confirm that big names like Google send it if I enter my credentials on new devices/browsers, rather than on IP changes.

**Comment by JC5** [comment]
That is in fact, *exactly* where [the code](https://github.com/firefly-iii/firefly-iii/blob/main/app/Providers/EventServiceProvider.php#L74) is now. So either that event is fired way too often or Laravel has another idea of what "logging in" actually is.

I noticed the same and blamed Cloudflare. I'll look into it!
