### ISSUE TITLE
Inconsistent state of deleted transaction

### ISSUE THREAD

**Issue by lucmos** [firefly-iii/firefly-iii#5176]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The transaction appears in lists but does not exist when clicking on it/editing or deleting. The amount displayed in the asset overview is wrong.

### Expected behaviour

The deleted transaction should not be taken into account for the total in the assets and should not be displayed.

### Debug information

Debug information generated at 2021-10-15 13:16:05 Europe/Rome for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b663ba32-207b-4d9f-9dea-a0f08dc6ae2b |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Rome |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | alert, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | 192.168.1.3 |

| User info | Value |
| --- | --- |
| Session start | 2021-10-01 00:00:00 |
| Session end | 2021-10-31 23:59:59 |
| Session first | 2021-01-16 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0 |

### Steps to reproduce

Not sure how to reproduce. These are the steps I did:

1. Update to 5.6.2
2. Clone a transaction from yesterday to replicate it today
3. Delete the cloned transaction

I noticed some problems here, and I repeated steps 2. and 3. two times.

### Additional info

Now I have the following:

1. Assets -> asset accounts -> myaccount
2. The last transaction is there, but:
  a.  The expense is not taken into account in the asset total
  b.  If I click on the transaction it does not open, the lists reload, without that transaction displayed. If I repeat 1. it appears again. A page refresh is not enough to make the transaction reappear
  c. If I click on transaction menu -> edit or delete I get an error 404

I have similar behaviour of the views from the destination account.

---

I already tried cleaning the cache with all the following from #3456:

-   Browse to /flush to clear your cache.
-   Execute command: docker exec [container] php artisan cache:clear
-   Remove + recreate the container.

**Comment by JC5** [comment]
If you press the refresh button that you see in the account list, the offending transaction will disappear.

**Comment by lucmos** [comment]
> It’s a browser cache thing. I’m not really focusing on those while the layout is in beta.
I see

> If you press the refresh button that you see in the account list, the offending transaction will disappear.

Unfortunately, it doesn't though. But I confirm is some problem with caching. I restored an old version of the db/files and that transaction is still there, even though others (correctly) disappeared.

**Comment by JC5** [comment]
Ok.

**Comment by JC5** [comment]
Mmm. Try clearing the browser cache or for now, back to v1
