### ISSUE TITLE
export - start / end parameter

### ISSUE THREAD

**Issue by TWART016** [firefly-iii/firefly-iii#5178]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I can export my transaction with the command: 
`/usr/local/bin/php /var/www/html/artisan firefly-iii:export-data --token=MYTOKEN --export-transactions --force --export_directory=/var/www/html//storage/upload/ --end 2021-10-16`

Without the `--end` parameter the export is empty
With just the `--start=2021-09-06` parameter the export just contains values with the date 2021-09-06

### Expected behaviour

Without the parameter `--start `and `--end` the export should contain all transactions

With just the parameter `--start` it should contain the values from the date till today
With just the parametet `--end` it should contain all values from first transaction till the date.

help:

```
 --start[=START]                        First transaction to export. Defaults to your very first transaction. Only applies to transaction export.
 --end[=END]                            Last transaction to export. Defaults to today. Only applies to transaction export.

```

### Debug information

-

**Comment by JC5** [comment]
> Without the parameter --start and --end the export should contain all transactions

Fixed!

> With just the parameter --start it should contain the values from the date till today

Works as expected, but that could be due to the previous fix.

> With just the parametet --end it should contain all values from first transaction till the date.

Works as expected, but that could be due to the previous fix.

**Comment by TWART016** [comment]
Hi, 

looks good in the developer tag.
