### ISSUE TITLE
Missing httpOnly Cookie Attribute

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#519]
Hi, my regularly security scan complains that Firefly do send cookies without httpOnly attribute. Would it possible to change this?

**Comment by JC5** [comment]
The Firefly configuration is incorrect here. I'll push 4.3.1 tonight to fix it.

**Comment by xpfgsyb** [comment]
Oh, my next scan is in a week, so it wouldn't *that* urgent for me :)
Thank you.
