### ISSUE TITLE
Fully spent budgets do not have a progress bar on V2 dashboard

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#5192]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am running 5.6.2 (V2) and when I have a budget with $0 remaining, the budget progress bar disappears and it appears as if you have not done any spending. If you overspend on the budget, the progress bar returns and becomes orange.

### Expected behaviour

The bar should remain present, filled to maximum, still green (probably) and say spent $x of $x, where both x's match and are the amount set for the budget.

### Debug information

Debug information generated at 2021-10-20 22:28:03 America/New_York for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-10-01 00:00:00 |
| Session end | 2021-10-31 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 |

### Steps to reproduce

1. Be on V2
2. Have a budget with an amount set.
3. Have 1 or more transactions assigned to that budget within the time period of the budget.
4. Go to the dashboard.
5. Scroll down to the budget section.
6. See that no bar is present on the budget in question.

### Additional info

This is a fully spent budget and a budget with no spending:
![image](https://user-images.githubusercontent.com/21091510/138201069-0e60cf17-d34e-407e-a32e-a83fa8b90848.png)
These progress bars both look exactly the same, but should show completely different values.

**Comment by JC5** [comment]
<img width="826" alt="Screenshot 2021-10-30 at 16 01 41" src="https://user-images.githubusercontent.com/5889984/139536044-318ba0b9-cc2f-4b20-96c7-d0006215f35d.png">

Fixed!
