### ISSUE TITLE
Update to 4.3.1 breaks decimal point in number_format

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#521]
Hi, the latest changes in app/Support/Amount.php in 4.3.1 break number formatting in tables, at least in my two instances, while your demo instance does look okay. Numbers are okay in graphs like in "Your accounts" in the dashboard.

I searched around and found that localeconv['mon_decimal_point'] is empty on all client systems I were able to try (several browsers on different Linux distributions, Windows 7, Android 6+7). Therefore I guess this will affect more people.

Do you know how to fix this? Are there settings on the server that can affect this?
A workaround in the code could be to implement a fallback to localeconv['decimal_point'] if localeconv['mon_decimal_point'] is empty.

**Comment by JC5** [comment]
Check if the linux installation you are running has the correct language package installed for the language you are using.

`mon_decimal_point` in [Amount.php](https://github.com/firefly-iii/firefly-iii/blob/master/app/Support/Amount.php#L56) is filled by the localeconv function which is a built-in PHP function.

Possibly, the list of language-codes isn't extensive enough to support your system. These can be found in the language files. Examples are [here](https://github.com/firefly-iii/firefly-iii/blob/master/resources/lang/en_US/config.php#L13) and [here](https://github.com/firefly-iii/firefly-iii/blob/master/resources/lang/nl_NL/config.php#L13).

**Comment by JC5** [comment]
To extend on this answer: which _client_ system you use does not matter, so "linux installation" can mean two things.

It's the _server_ that needs to be configured correctly. On the demo-server I run Ubuntu, and I used the following command to support the default languages:

`sudo apt-get install -y language-pack-en-base language-pack-nl-base language-pack-de-base language-pack-pt-base`

**Comment by xzaz** [comment]
Here I get the same error:
``` Type error: number_format() expects parameter 2 to be integer, null given ```

I did run `dpkg-reconfigure locales` on my Debian instance. Didn't help. Language pack is installed.

**Comment by JC5** [comment]
On the command line:

`git checkout develop`
`git pull`

Open `.env`, and change `APP_LOG_LEVEL` to debug. Your logs should start to contain `formatAnything(). Will set locale to`.

Copy and paste one of those log lines. Let's see what FF is up to.

**Comment by xpfgsyb** [comment]
Thank you for the tips. On my Debian 8.6 server it helped to configure the necessary locales by running ``dpkg-reconfigure locales`` (or alternatively edit /etc/locale.gen and ``run locale-gen``). Necessary means the language code that's configured in the browser. So if the browser is set to request pages in en_GB, one need to enable en_GB on the server too.

@xzaz: Your error is a little different. You should be able to solve it by clearing the cache with the command ``php artisan cache:clear``. That helped me.

**Comment by JC5** [comment]
I'm not sure if Firefly uses en_GB anywhere. Firefly doesn't use browser requests to determine the language.

**Comment by xzaz** [comment]
@xpfgsyb You are right, cache:clear did it. Should have tried it. Is your problem with the decimal placing fixed now, this time I got the exact same issue you have or had.

**Comment by xpfgsyb** [comment]
Okay, what code do you map English? en_US? I played with en_US before too but disabled it later, maybe it was just a side effect that it worked afterwards. I activated en_US again just to be sure. However, the decimal character does work for me now.

Btw, clearing the cache solved a lot of problems for me in the last days. Mostly after an import when I saw a lot of "wrong" (cached) numbers, but today after the update too. Maybe it would be worth to add this to the upgrade process or as a first-aid command :)

**Comment by xzaz** [comment]
en_US yes. No luck.

@JC5 
Can't switch to the develop branch, `git branch -v -a` doesn't list the branch. Fetching / pull doesn't help.

**Comment by xpfgsyb** [comment]
The map question was for JC5... My way was to enable the locale, then restarted Apache and cleared cache.

**Comment by xzaz** [comment]
Yep; i'm running Nginx + php-fpm. Needed to restart php-fpm.

**Comment by JC5** [comment]
Did you run `php artisan migrate`?

**Comment by xzaz** [comment]
@JC5 Yes

**Comment by JC5** [comment]
Oh, I forgot: run `php artisan firefly:upgrade-database`

**Comment by xzaz** [comment]
Thanks, that fixes the pages. As I can see only MONEY OUT and MONEY IN on the dashboard isn't showing the decimal place.

**Comment by JC5** [comment]
In order to support multiple decimal places (for #506) I had to switch from [NumberFormatter](http://php.net/manual/en/class.numberformatter.php) to a [localeconv](http://php.net/manual/en/function.localeconv.php) / [number_format](http://php.net/manual/en/function.number-format.php). I think your problems originated from the "lack" of local currency information (which in case of localeconv comes from another source).

I've updated the upgrade instructions to reflect the "clear cache" and "upgrade database" routine.

Have I missed any other problems in this thread?

**Comment by xzaz** [comment]
Yes, ensure with `dpkg-reconfigure locales` that the language is installed, then reboot Apache or Nginx (webserver).

**Comment by xpfgsyb** [comment]
In this thread we had three problems:
- Immediately after the update Firefly didn't load correctly, as number_format got NULL as second parameter (decimal places). Fixed by clearing the cache.
- Missing locale on the server and therefore no decimal character since version 4.3.1. Fixed by enabling/installing the language, restarting the web server and clearing the cache.
- @xzaz needed to migrate the database in an extra step. I didn't need this step - I think ``php artisan migrate --env=production`` did that already for me when I answered yes. Default answer is no. What was your input xzaz?

I think it would be helpful to mention the language thing in the installation guide or it's FAQ. Unfortunately there are a lot of different Linux distributions out there, so this section will take some time until all systems are covered. For Ubuntu you posted the right way @JC5, but on Debian it works a bit different (see my [comment](https://github.com/firefly-iii/firefly-iii/issues/521#issuecomment-270358499) above), even if Ubuntu is based on Debian. Something like a language mapping information would be useful too, like for English in Firefly install en_US, for German de_DE and so on. Please replace the system languages to the right values if I'm wrong.

Just as a note: installing a language on the server could be a complicate/impossible task for users of shared web hosting, but I don't know if this is a common environment.

**Comment by JC5** [comment]
Cool, thanks for the write-up!

* The update routine now includes the clear-cache routine.
* The locale thing is included in the installation routine, and there's a warning when switching languages in `/preferences`.
* There is a note to answer Yes in the installation and upgrade guides.

Some systems are covered in the FAQ, but not all of them. I expect to see issues here, or people Googling themselves.

Firefly isn't running on many shared webhosters, because the installation routine requires composer and ssh access which they rarely provide.

**Comment by xzaz** [comment]
@xnyhps I did that, my answer was YES. I had a small different problem with the migration though, but that was unrelated to this issue.

**Comment by elohmeier** [comment]
I'm having the same issue with the Dockerfile included in the repo.
Tried to fix it in the Dockerfile by installing the "locales"-package and adding the following:
```RUN locale-gen en_US.UTF-8 en_us; locale-gen de_DE.UTF-8 de_de; locale-gen nl_NL.UTF-8 nl_nl; locale-gen pt_BR.UTF-8 pt_br; DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales```

But this didn't help, even after restarting the webserver and doing the "cache:clear" command.

Do you have ideas how to fix this issue in the Dockerfile?

**Comment by JC5** [comment]
No, I have no idea. I know little about Docker and I haven't provided the Dockerfile.

**Comment by zjean** [comment]
@elohmeier @JC5 I had problems upgrading my firefly instance as well. It turned out that the linux user I used to perform the upgrade had no permissions to delete the files in the cache directory of firefly. A `php artisan cache:clear` did not return any arrors though.

**Comment by JC5** [comment]
There's an undocumented feature. If you surf to `/flush` the cache is also a cleared, along with your session in many cases.

**Comment by elohmeier** [comment]
Thanks for your help, I was able to fix this in the docker context by generating the locales at image creation time. See the referenced PR #534

**Comment by JC5** [comment]
Merged, thanks!

**Comment by dzaikos** [comment]
@JC5:

> Possibly, the list of language-codes isn't extensive enough to support your system. These can be found in the language files. Examples are [here](https://github.com/firefly-iii/firefly-iii/blob/master/resources/lang/en_US/config.php#L13) and here.

I just started using this software and ran into the same issue with missing decimal places. In my case the above linked `en_US/config.php` file does not match FreeBSD's naming convention. If I add `en_US.UTF-8` to the `locale` key it works properly:

    'locale'          => 'en, English, en_US, en_US.utf8, en_US.UTF-8',

I can submit a pull request but given how simple of a change this is, it might just be easier for you to add it.

**Comment by JC5** [comment]
Good call, I'll update it asap!
