### ISSUE TITLE
Write recurring transactions on forehand

### ISSUE THREAD

**Issue by zynexiz** [firefly-iii/firefly-iii#5213]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Before I migrated to Firefly I used Skrooge (Linux banking app), and it had one feature that I miss here. When doing a recurring transaction it could write the transaction X days before it happened, if a bill was on due at the 25th, it would be added to the database on fx the 15th it you had the settings to write it 10 days before. 

It's a very good feature to keep track of what transaction are going to occur in the future in stead of having to look thru all recurring events, especially to check that you actually have coverage on your account for it. My bank also has this kind of feature, so I can see what transaction is coming in the near future.

### Solution

Add an option, either global one or for each recurring transaction, how many days before the transaction should be added to the database.

### What are alternatives?

None that I know of..

**Comment by wocodes** [comment]
I can give this feature a shot @JC5

**Comment by JC5** [comment]
No thanks, that's alright. I'll work on this after other things are finished. Firefly III is basically in a feature freeze right now.

**Comment by JC5** [comment]
See also https://github.com/firefly-iii/firefly-iii/issues/5754

**Comment by JC5** [comment]
This will be part of 5.8.0. A little button will appear next to future iterations:

<img width="455" alt="Screenshot 2022-12-29 at 15 26 40" src="https://user-images.githubusercontent.com/5889984/209967384-e10b9d0d-90e0-4512-ae31-594f7fccc7d0.png">

If you press it, the transaction for that future date will be created *with todays date*. When the future date comes to pass, no transaction will be created.

In this screenshot, I created 3 transactions for the 24th of February, March and April. They are saved with today's date, ie. December 29. On the dates in the future, there will be no transactions created for this recurrence.
