### ISSUE TITLE
Contradictory error message and behavior when using date_before and date_after in search

### ISSUE THREAD

**Issue by alexklibisz** [firefly-iii/firefly-iii#5218]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I use `date_before` and `date_after` modifiers in a search, the search works correctly, but the results show both:
1. a warning that the modifiers were note applied
2. a confirmation that the modifiers were applied

![image](https://user-images.githubusercontent.com/8015228/139555811-831b22e4-e06d-4a1a-a359-6ca71509c89b.png)

### Expected behaviour

It should not show the warning.

### Debug information

Debug information generated at 2021-10-30 15:15:41 America/New_York for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | e1cc6dba-0dbc-4d29-b747-a26a86557361 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-10-01 00:00:00 |
| Session end | 2021-10-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 3 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 |

### Steps to reproduce

1. Search for something using the date_before and/or date_after filters.

**Comment by JC5** [comment]
Lol nice find, ill check it out
