### ISSUE TITLE
Adding month dynamically to transaction name

### ISSUE THREAD

**Issue by ryan77627** [firefly-iii/firefly-iii#5219]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I'm creating some rules for automatic transactions that will occur monthly, one of these is my rent. Right now, the transction will be created called "Property Rent". In the past, when I did this manually, I had them titled "Property Rent (October)" or such.  I'd like to be able to dynamically add the month to the name of transactions to help keep me keep track of them. I searched through issues and the month but couldn't find anything regarding this.

### Solution

Given my rent is due the 1st of the month, is there any way to dynamically add that to recurring transactions? Something like "Property Rent ({month})" would be added as "Property Rent (October)" for whatever the month is. I'm aware of shortcomings of this, so I'd be open to discussing this idea to come up with something better. Things like "What if you want to add the name of the previous/next month" for whatever reason (maybe rent is due by end of month instead of beginning). How would that happen? Or, what exactly *should* be turned into a dynamic label? Just month name? Other things (I can't think of any I would personally need but I'm sure there's some)

### What are alternatives?

I could program something and use the API to add the transaction my own way, but I don't trust myself to code it, then maintain it, and most importantly it would be the only thing outside of firefly that comes in, and I'd rather have everything consolidated within firefly so I know what's from where, if that makes sense.

### Additional context

I'm sure this is a big ask, since it would require adding some kind of parsing to the transaction name field, so I'd be open to hear what you and others think about this.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4917

This would allow you to set up such fields.
