### ISSUE TITLE
Allow lower amounts than 0.01

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#522]
Hi, when I want to add a new transaction in a currency with more than 2 decimal places I can't add it if the amount is below 0.01.
I think the lowest amount should be defined by the decimal places of the currency instead of being 0.01. F.e. for Bitcoin with it's 8 decimals the lowest amount should be 0.00000001. Hope this is doable.

**Comment by JC5** [comment]
Good point, I hadn't thought of that. I'll update it as soon as possible.

**Comment by JC5** [comment]
![screen shot 2017-01-06 at 19 42 29](https://cloud.githubusercontent.com/assets/5889984/21728793/47877bd8-d448-11e6-9fce-feb49692601e.png)

Will be live during the next release.

**Comment by xpfgsyb** [comment]
mtgox - hopefully not ;)
Thank you!
