### ISSUE TITLE
"Expenses to account" screen will also contain all recent transactions (regardless of the account)

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#5222]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When you open "Expenses to account" from the financial report, list of transactions will also contain list of all recent transfer transactions (regardless of the account they were made to).

### Expected behaviour

List should only contain expenses that were made to that account.

### Debug information

Debug information generated at 2021-11-01 06:13:12 UTC for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 1c789eff-ec96-4172-80d7-9ab04aabfda8 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| System TZ |  |
| Browser TZ | Europe/Ljubljana |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2021-11-30 23:59:59 |
| Session first | 2017-12-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0 |

### Steps to reproduce

1. Open reports
2. Generate Default financial report
3. Scroll to the Expenses section
4. Press on the `i` button next to any of the expense accounts

**Comment by JC5** [comment]
Thanks for letting me know, I'll pick it up!

**Comment by JC5** [comment]
Has been fixed :+1:
