### ISSUE TITLE
ServiceWorker registration failed

### ISSUE THREAD

**Issue by arthurgeek** [firefly-iii/firefly-iii#5229]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm using Firefly via Docker container and I have an nginx proxy in front of it. I access Firefly via HTTPS, and there's an error in the console about ServiceWorker register.

`ServiceWorker registration failed:  DOMException: Failed to register a ServiceWorker: The origin of the provided scope ('http://my.url') does not match the current origin ('https://my.url').`

As you can see, it tries to register the serviceworker for the non https URL.

My proxy config contains: `proxy_set_header X-Forwarded-Proto $scheme;`, the `APP_URL` env contains the https URL and `TRUSTED_PROXIES` is the IP address of my proxy.

### Expected behaviour

The service worker should register successfully.

### Debug information

Debug information generated at 2021-11-01 20:44:30 UTC for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 7698523d-6437-4014-a4ac-2df7a1e79e41 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ |  |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | 192.168.1.150 |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2021-11-30 23:59:59 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 |

**Comment by JC5** [comment]
But other links are correct? You can login and navigate etc?

**Comment by arthurgeek** [comment]
Yes, I can login and navigate without any issues.

Looking at the source code, the form links are correct (they use the https), the `<base href>` is also using https.

It looks like all Javascript calls are not, I get this error while navigating: `Refused to connect to 'http://my.url/json/something' because it violates the following Content Security Policy directive: "connect-src 'self'".`. 

Charts are also not working, same issue, it tries to load `/chart` with HTTP.

**Comment by arthurgeek** [comment]
So, changing the `TRUSTED_PROXIES` value to `**` instead of my proxy IP address solved.

Is that supposed to be this way?

**Comment by JC5** [comment]
No, but I don't know why it is that way. I'm leaning on Laravel for this one.

**Comment by JC5** [comment]
I've simplified the code a bit just in case. You can try the develop branch to see if it works!
