### ISSUE TITLE
PDF Reports

### ISSUE THREAD

**Issue by dabenzel** [firefly-iii/firefly-iii#523]
Hey,
first of all thank you for this nice 'APP'. I'm using it for the financial booking of our fire brigade.

At the end of the year, our finances are checked. Therefore it would be nice to have a printable PDF with every booking per account. Is this possible for the future?

Thanks in advance!

**Comment by JC5** [comment]
There is an audit report, you can find it under `/reports`. You can select the accounts you want and the period and then there will be a list of transactions in that period. You can select the columns you want to see as well.

It is not optimized for printing but I think this is what you mean, right?

**Comment by dabenzel** [comment]
Yes, it would be good, if these generated reports could be in a printable
layout. For my option a simple income/outcome comparison with the
'remaining balance' would be good.

Such as:
Date | Income Value | Outcome Value | Balance | Description

I hope you understand what I mean ^^

Am 05.01.2017 08:06 schrieb "James Cole" <notifications@github.com>:

**Comment by JC5** [comment]
This is already possible using the audit report. You should try it on the demo site. Print the page and save it to PDF. 

https://firefly-iii.nder.be/reports/audit/1/20170101/20170131

**Comment by dabenzel** [comment]
Thanks! I haven't seen it!
