### ISSUE TITLE
Month to date as a default date range

### ISSUE THREAD

**Issue by MattFaz** [firefly-iii/firefly-iii#5234]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Requesting an additional date range that can be set as the default which shows the current month up to the current date. As an example, today (for me) would show Nov 01 - Nov 03.

If the current date was Nov 20 it would show Nov 01 - Nov 20, etc.

![Screen Shot 2021-11-03 at 9 47 56 am](https://user-images.githubusercontent.com/10377148/139962256-4ccb1ba2-0a0b-46f3-8525-df26b2a6b454.png)

### Solution

Month to date as a range, showing the current month up to the current date (but no further).

### What are alternatives?

Currently I can manually set a custom range, but I would need to update it each day.

**Comment by JC5** [comment]
I'll write it down for the new layout :+1:

**Comment by shimabuku** [comment]
If you are going to work on a month to date, can you also add a year to date option?

**Comment by JC5** [comment]
Will be part of 6.0.0. If you run into problems, please open a new ticket.

**Comment by shimabuku** [comment]
Thank you to everyone involved for fulfilling this request.
