### ISSUE TITLE
Missing data, visuals etc. - but back-end data is there

### ISSUE THREAD

**Issue by chrismast** [firefly-iii/firefly-iii#5236]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

He guys,
I use Firefly III for a long time now, just had a 3 months break and got back to my servers and wanted to catch-up on transactions.
When I opened firefly III it showed me though that a whole bunch of data (i.e. out of July) is missing, at least visually.
Running a report shows that there are transaction for the account (i.e. in July).
I also checked entering a new transaction via the telegram bot, and it also shows up in the reporting section, but again, not in the account or transaction views.
Also, there seem to be some artefacts on the accounts view as well and for instance, I cannot even select any time duration in the accounts view (it just defaults to April 2021).
It seems that my new GUI is stuck in April 2021 somehow.
Attaching 2 screenshots showing what I currently see:

![KBank2](https://user-images.githubusercontent.com/63285062/140059967-5e68a7e6-9702-4ef0-9627-98054ceb753b.JPG)

![Kbank](https://user-images.githubusercontent.com/63285062/140059960-89a4f082-9ff9-42c5-a5ea-097ad0744558.JPG)

I do run the latest firefly version in my LXC (as before).
Also tried a catch clean, but no change.

Any idea what could go wrong here?

### Expected behaviour

Show my historical data etc.

### Debug information

Debug information generated at 2021-11-03 19:32:55 Asia/Bangkok for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 0b6484f5-23d6-4d19-b42a-d6f7c7213dca |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Asia/Bangkok |
| Browser TZ | Asia/Bangkok |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2021-11-30 23:59:59 |
| Session first | 2016-06-09 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 |

**Comment by JC5** [comment]
The v2 layout is very much in beta so this isn't really a surprise. I'm working to make it as reliable as v1, but until it's the default setting, please don't use it as your daily driver.

**Comment by chrismast** [comment]
Thanks JC! As always quick and point on. Changed the .env back to v1 and it works.
Just surprised as I was using v2 for quite a while before without issues.
Anyway, thanks again!
