### ISSUE TITLE
419 Page Expired using Export Data option

### ISSUE THREAD

**Issue by achembarpu** [firefly-iii/firefly-iii#5237]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am trying to export my transactions as a CSV, by using the "Export Data" option in the Firefly III interface (not command line). However, the download is an HTML file called `export.html` which says "419 Page Expired". No other visible errors.

### Expected behaviour

The download is a CSV file instead, with a filename of `datetime_transaction_export.csv`.
This has worked for me innumerable times before on this version (5.6.2) and previous ones.

### Debug information

Debug information generated at 2021-11-03 16:07:40 Europe/Amsterdam for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 26d3fa69-1d7a-46ed-a481-5a687d7313e1 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | info, docker_out |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-10-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2017-08-20 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15 |

### Steps to reproduce

As described above, no extra steps.

### Additional info

I have a feeling I'm reaching some row limit? Or other such issue leading to a longer export time.
I checked the docker logs for firefly, mysql, and redis - no errors emitted before/after clicking the Export button.

**Comment by JC5** [comment]
Not really sure. It works for me ™️ , with over 8 years of transactions. Does it work over the command line?

**Comment by achembarpu** [comment]
I was able to try this in Chrome, instead of Safari, and it appears to work fine. Tried again in Safari, and it breaks.
Maybe it's hitting a Safari-specific timeout then. I'll try to do some more debugging and isolate the issue.

**Comment by JC5** [comment]
I see it in Safari as well, I'll do some research. Nice find!

**Comment by JC5** [comment]
This seems to be a bug in Safari that I can't fix from my end. Sorry about that.
