### ISSUE TITLE
Splitting Expences causes Categories Problems

### ISSUE THREAD

**Issue by worldworm** [firefly-iii/firefly-iii#524]
When I add an expence, for example 50€, the Bargraph found in Dashboard for this categorie will display 50€ (if theres no other expence), but when i split the expence (for example 25€ and 25€ and give them the same categorie), then there are 50€ for this one categorie in the Dashboard and 50€ labeld as 'no categorie'

**Comment by JC5** [comment]
Yes, I can confirm the problem. I'm working on a fix!

**Comment by JC5** [comment]
The problem should be fixed. You can experiment with it on the [demo site](https://firefly-iii.nder.be/).
