### ISSUE TITLE
Set budget bug

### ISSUE THREAD

**Issue by marco-ragusa** [firefly-iii/firefly-iii#5240]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I try to set a budget, the page is redirected to a blank json. I tested on the demo (Version 5.6.2) site and I have the same issue.

### Expected behaviour

Redirect to the budget page

### Debug information

Debug information generated at 2021-11-05 10:22:44 Europe/Rome for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 216223af-2971-406a-abfb-d5c8a486bf65 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Rome |
| Browser TZ | Europe/Rome |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | it_IT |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2021-11-30 23:59:59 |
| Session first | 2021-09-01 00:00:00 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0 |

### Steps to reproduce

![set_budget_bug](https://user-images.githubusercontent.com/7346348/140487070-ee6d4a72-6a77-4215-a3f7-f71e9883a96c.gif)

### Additional info

The form contains only a simple POST method

```
<form style="display: inline;" id="income" action="https://demo.firefly-iii.org/budget-limits/store" method="POST">
<div class="modal-body">
...
<div class="form-group">
<select class="form-control" name="transaction_currency_id">
<option label="Euro" value="1">Euro</option>
...
</select>
</div>
<div class="form-group">
<input step="any" class="form-control" id="amount" value="" autocomplete="off" name="amount" type="number">
</div>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
<button type="submit" class="btn btn-primary">Set budgeted amount</button>
</div>
</form>
```

**Comment by JC5** [comment]
I see what you mean, nice find, i;ll pick it up!
