### ISSUE TITLE
Show running balance

### ISSUE THREAD

**Issue by Tuxie** [firefly-iii/firefly-iii#5241]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I imported a few thousand transactions from YNAB into an empty Firefly III installation, and while it looks like the import was successful at a first glance, the account balances are _way_ off. I want to go through them to fix what went wrong, but comparing the transaction in Firefly III with the transactions in YNAB is very hard without being able to see the running balance.

### Solution

Have a balance column in the transactions list to see what the account balance was at that point in time.

**Comment by death2cupbots** [comment]
You can get a running balance if you do a transaction history overview (audit) from the reports page.
