### ISSUE TITLE
Edit Bugets: Auto-budget amount contains too much zeros

### ISSUE THREAD

**Issue by RogerSik** [firefly-iii/firefly-iii#5245]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When editing a budget the "Auto-budget amount" containts too much zeros:
![zero](https://user-images.githubusercontent.com/165814/140612276-6965c8cf-59de-4fae-8ee0-867dd5a6264f.png)

### Expected behaviour

Only 2 zeros

### Debug information

Debug information generated at 2021-11-06 14:59:34 Europe/Berlin for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 6b0db7be-1613-4621-bbf8-440d0c7f52fc |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2021-11-30 23:59:59 |
| Session first | 2021-11-05 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.40 |

### Steps to reproduce

1. Create budget with auto budget
2. Edit budget

### Additional info

Firefly (tag latest) and mariadb 10.6 as docker image used

The demo site also have this issue

There seems a similar closed issue 2876 but which affected the editing of transaction. Which i can't reproduce the problem.

**Comment by JC5** [comment]
I noticed as well, thanks for opening the issue!

**Comment by Dpons039** [comment]
I have detected the same thing when massively editing transactions.

This is an screenshot from the demo itself where I was able to reproduce it.
![image](https://user-images.githubusercontent.com/3227283/140740273-215e41e6-1c8d-4681-8d17-0b9ab6fe3512.png)

**Comment by JC5** [comment]
All fixed!
