### ISSUE TITLE
Tags report

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#525]
I'm trying to find a way how to monitor my overall expenses. Let's say I'm particularly interested in tracking my entertainment and transportation expenses. I've created several categories:
- bus tickets
- train tickets
- plane tickets
- taxis
- cinema
- games
- books / magazines

For every transaction in transport categories I put a "transport" tag and in entertainment categories I set "entertainment" tag. I would like to see by the end of the month percentage of overall expenses for transport and entertainment. The easiest way would be to have a report where I can select tags (just like in categories report). Or maybe I'm doing my bookkeeping wrong?

**Comment by JC5** [comment]
Writing a proper tag-report is on my list of todo's. It would look like the category / budget report, but focussed on tags.

**Comment by JC5** [comment]
The next release of Firefly will (finally) have this report. Currently, it looks a lot like the category and budget reports, but it can be extended of course. 

![tag report between february 2017 and february 2017 reports firefly iii](https://cloud.githubusercontent.com/assets/5889984/23319515/29af2aba-fad7-11e6-9342-e4afd19867bc.png)

**Comment by skibbipl** [comment]
Looks OK, will definitely try it with my data.

**Comment by JC5** [comment]
I'm cleaning up. Could you re-open this issue or open another one if you find bugs, or when you see a cool feature? Thanks! :+1:

**Comment by JC5** [comment]
I thought that was fixed ages ago. I'll check it out this weekend.
