### ISSUE TITLE
YNAB Import: Unable to select liability account 

### ISSUE THREAD

**Issue by Dpons039** [firefly-iii/firefly-iii#5250]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

YNAB Import: Unable to select liability account, they are not displayed on the dropdown menu. I have tried adding the accounts on the JSON but it doesn't make any difference as they are removed when all the accounts appear with the dropdown selection.

### Expected behaviour

You're also able to import the Loans/debs/mortgage accounts from YNAB.

### Debug information

Those messages appear during import:
Could not find a valid source account when searching for ID "0" or name "".
Could not find a valid destination account when searching for ID "0" or name "".

### Steps to reproduce

1. create an account on YNAB and add any transfer transaction
2. create a liability account on FireflyIII
3. try to import the account from YNAB that has the transfer

**Comment by JC5** [comment]
Which dropdown are you talking about exactly?

**Comment by Dpons039** [comment]
Hello JC5,

The dropdown appears on the page http://xxxx/import/configure only shows Asset Accounts.

If I select Map data, on the new page that appears for the mapping http://xxxx/import/mapping I can choose the Liability accounts created on Firefly III but since I haven't selected the accounts on the initial configuration page it fails during the import with the messages mentioned earlier.

**Comment by JC5** [comment]
Thanks, it's on the list!

**Comment by JC5** [comment]
Hey, I'm not going to spend more time on the YNAB importer unfortunately, so this issue will be closed. The [data importer](https://github.com/firefly-iii/data-importer) should be capable of importing CSV files from YNAB, but the importer itself will not be maintained anymore. 

My apologies for the inconvenience.
