### ISSUE TITLE
Tag clicking double adds the Text

### ISSUE THREAD

**Issue by worldworm** [firefly-iii/firefly-iii#526]
When adding a transaction and adding a tag, typing the first letters that it is shown and clicking on it to add it to the list, the tag will be added and also the words again behind it. 

This is annouying when adding multiple tags, cause you have to delete the text first before adding the next one (and sometimes deleting too much :) )

Thanks for your help <3

![2017-01-05 14_46_07-add a new deposit transactions firefly iii](https://cloud.githubusercontent.com/assets/13227454/21682600/d3de0e2e-d355-11e6-8aba-bed8898672d8.png)

**Comment by JC5** [comment]
I believe I have been able to fix this, on the demo site. 

Go [here](https://firefly-iii.nder.be/transactions/create/withdrawal) and try it out. Let me know if it works as intended!

**Comment by worldworm** [comment]
Yes, now it works

**Comment by JC5** [comment]
Cool!
