### ISSUE TITLE
Credit Line and Credit Card authorized amount

### ISSUE THREAD

**Issue by Geek-MD** [firefly-iii/firefly-iii#5261]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Credit Cards and Credit Lines use a concept called "authorized amount" with is the amount of credit allowed by the financial institution which leans the money. Haven't seen this feature on assets accounts.

BTW, credit lines are "almost" the same as credit cards, but I would like to be able to call it "credit line" instead of "credit card".

Any chance to let users edit assets categories?

Thanks in advance

### Solution

Add authorized amount feature to credit accounts.
Let user edit assets accounts.

**Comment by JC5** [comment]
I use the virtual amount to set the allowed credit. 

The asset categories aren't editable but they're due an update. I'll put it on the list.

**Comment by Geek-MD** [comment]
Hmmm it seems that many users administrates credit cards and credit lines as positive balance... They are credit (debt), so in my opinion they must be treated as negative balance. If I use virtual amount to set the allowed credit, using negative numbers, net value breaks and shows wrong information.

**Comment by JC5** [comment]
This isn't going to be added. If you want to remember the authorized amount, please use the account notes.
