### ISSUE TITLE
Piggy Banks: add an option for a piggy without a goal (target amount)

### ISSUE THREAD

**Issue by macuros** [firefly-iii/firefly-iii#5269]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello,

I'd like to see an option to have a piggy without a target amount. That way I can set monthly amount, but with no target. 

### Solution

Already described above.  Not all my piggies have a target, just a monthly amount. Currently, I set the target amount for 10 years, that way I get the suggested monthly amount the right value. I really like the suggested amount feature.

**Comment by JC5** [comment]
Not a bad idea, I'll put it on the list!

**Comment by macuros** [comment]
Great! Looking forward.

**Comment by ultrara1n** [comment]
+1 for me, i've got some piggy banks without a fixed montly target or without a target at all. 
currently im setting the goal to a high amount, but the resulting diagrams looks weird, as there is no goal to achieve

**Comment by macuros** [comment]
Hmm, thanks for adding that, but I'm not sure how to set a piggy bank without the target date. I would like to set aside fixed amount every month, or even add a bit more.
