### ISSUE TITLE
New upgrade procedure fails with PDO Exception

### ISSUE THREAD

**Issue by webenhanced** [firefly-iii/firefly-iii#527]
I have a running system on firefly-iii v3.7.2.3 and I was attempting to use the recently added update instruction (which uses composer create-project).

After changing the cli php ver to 7.0.14, the instructions work fine until
` php artisan migrate --env=production `

Output is:
` [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: alter table `transactions`
   add `identifier` smallint unsigned not null default '0')
  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'
  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'`

Is this a mysql compatibility issue? Server mysql version is v5.1.73-7.el6 (VPS with Centos6.8 on Plesk panel 12.5.30).

In phpMyAdmin, the created_at field is defined:
created_at 	timestamp 			No 	0000-00-00 00:00:00 

I need help diagnosing this issue :-)
Graham

**Comment by JC5** [comment]
Mmmm, although MySQL 5.1 is pretty old it shouldn't be a problem. Is the "No" in your definition "allow null?"?

It's especially strange since the error comes up when the table is edited, not when data is entered into the table.

- What's the full stacktrace?
- What happens when you create a new database and migrate into that?

**Comment by webenhanced** [comment]
> Is the "No" in your definition "allow null?"?

Yes it is. I went into phpMyAdmin and captured the sql to alter the three _at fields:-

`ALTER TABLE `transactions` CHANGE `created_at` `created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00';`

"updated_at" is the same definition as "created_at".

`ALTER TABLE `transactions` CHANGE `deleted_at` `deleted_at` TIMESTAMP NULL DEFAULT NULL();`

> It's especially strange since the error comes up when the table is edited, not when data is entered into the table.

Firefly-iii v3.7.2.3 was running under php 5.6 fastcgi.
To do the composer and php artisan stuff, I changed the CLI php version to 7.0 so composer would run.
I have not changed the fastcgi version to php7 yet, I was going to wait until the upgrade completed then change to php7 before opening the website.

I'll have to get back to you on a stack trace for the pgp artisan command (I guess that is what you are after). I'll have to find where that is on the system.

**Comment by webenhanced** [comment]
When you say "stack trace" is the Exception trace sufficient. I am talking about the one I see when using:

`$ php artisan -vvv migrate --env=production`

(note the -vvv)

**Comment by webenhanced** [comment]
Here is the exception trace:

```
Exception trace:
 () at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php:761
 Illuminate\Database\Connection->runQueryCallback() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php:717
 Illuminate\Database\Connection->run() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php:481
 Illuminate\Database\Connection->statement() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:83
 Illuminate\Database\Schema\Blueprint->build() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:229
 Illuminate\Database\Schema\Builder->build() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:130
 Illuminate\Database\Schema\Builder->table() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:237
 Illuminate\Support\Facades\Facade::__callStatic() at /firefly-iii-updated/database/migrations/2016_10_09_150037_expand_transactions_table.php:38
 ExpandTransactionsTable->up() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:162
 Illuminate\Database\Migrations\Migrator->runUp() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:130
 Illuminate\Database\Migrations\Migrator->runMigrationList() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:97
 Illuminate\Database\Migrations\Migrator->run() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:65
 Illuminate\Database\Console\Migrations\MigrateCommand->fire() at n/a:n/a
 call_user_func_array() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Container.php:508
 Illuminate\Container\Container->call() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
 Illuminate\Console\Command->execute() at /firefly-iii-updated/vendor/symfony/console/Command/Command.php:254
 Symfony\Component\Console\Command\Command->run() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
 Illuminate\Console\Command->run() at /firefly-iii-updated/vendor/symfony/console/Application.php:821
 Symfony\Component\Console\Application->doRunCommand() at /firefly-iii-updated/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at /firefly-iii-updated/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at /firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /firefly-iii-updated/artisan:35
```

I have removed the host specific directory portion of the filenames for privacy and readability.

**Comment by JC5** [comment]
From my Googling:

> You probably have NO_ZERO_DATE enabled in your MySQL configuration. Setting this to off will allow you to create the table (or alternatively remove the default 0 value or change it to CURRENT_TIMESTAMP.

What you could also try, is editing `config/database.php` and set strict to `false` in the mysql array.

> Ah, I have found the issue a fix, probably.

> My "old" database.php config file does not have strict set to false ('strict' => false) as laravel/laravel does. When I add that line to the mysql config, all migrations work just fine (in my case)...

> Edit: I noticed it doesn't matter what the value of strict is, as long as it's present it won't fail (checked on clean Laravel install).

Although the strict value is indeed present, setting it to `false` may work.

**Comment by webenhanced** [comment]
In the database.php file of the original installation (v3.7.2.3), strict was set to false. And in the -updated version it is indeed set to true.

I changed to false in the -updated version and ran the php artisan command again. I did not get the same exception. This time with a duplicate column in transaction_currencies. I will restore the DB to the original data and start again.

**Comment by webenhanced** [comment]
Hmmm, now I am getting the following exception:-

```
[Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
```

So I upgraded mysql to 5.5 and tried again. Same error.

```
$ mysql -V
mysql  Ver 14.14 Distrib 5.5.52, for Linux (i686) using readline 5.1
```

If I run the artisan command again without restoring the DB, I get the duplicate column name error so part of the DB has been migrated.

Here's the mysql part of the database.php file:-

```
        'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE', 'forge'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
            'engine'    => null,
        ],
```

Here is the redacted .env file (I have merged old version one into this -updated one):-

```
APP_ENV=production
APP_DEBUG=false
APP_FORCE_SSL=false
APP_FORCE_ROOT=
APP_KEY=SomeRandomStringOf32CharsExactly
APP_LOG_LEVEL=warning
APP_URL=http://money.xxxxxxxxxxxxx

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=xxxxxxxxxxxxx
DB_USERNAME=xxxxxxxxxxxxx
DB_PASSWORD=xxxxxxxxx

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

DEFAULT_CURRENCY=AUD
DEFAULT_LANGUAGE=en_AU

COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false

REDIS_HOST=localhost
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.xxxxxxxxxxxxxxxxx
MAIL_PORT=25
MAIL_FROM=graham@xxxxxxxxxxx
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

SEND_REGISTRATION_MAIL=true
SEND_ERROR_MESSAGE=true
SHOW_INCOMPLETE_TRANSLATIONS=false

GOOGLE_MAPS_API_KEY=
ANALYTICS_ID=
RUNCLEANUP=true
SITE_OWNER=graham@xxxxxxxx

BLOCKED_DOMAINS=

PUSHER_KEY=
PUSHER_SECRET=
PUSHER_APP_ID=

```

Seems to be some strange goings on.

**Comment by webenhanced** [comment]
Just adding.....

I used this composer command to create the -updated version of firefly.

`$ composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated`

Is this any different to firefly-iii/firefly-iii ?

**Comment by webenhanced** [comment]
Another thought is to upgrade incrementally. v3.7 is fairly old now, would it be better to upgrade to (say) 3.10 then 4.0 before upgrading to the latest? Would that be better?

**Comment by JC5** [comment]
I think the best idea is to create a new database and installation next to the old one, and change the fields and tables in the old database to match the new one. Then, configure the new installation to use the old database. If these databases match (but one is empty) you should be fine.

The enum error is a known error in Doctrine and the migrations were completely rewritten in 4.something for exactly that reason. Upgrading step-by-step is not going to work.

**Comment by webenhanced** [comment]
Sounds like a good plan to me. Thanks for the advice. I'll let you know how it goes.

**Comment by JC5** [comment]
The budget_limits table now has an end_date as well as a (renamed) start_date. Just leave end_date empty.

When you run `php artisan firefly:upgrade-database` it will fix those.

**Comment by webenhanced** [comment]
Thanks James. This worked, although I had a couple of difficulties.

Here's what I did...

- Upgraded php CLI to v7.0
- Renamed firefly-iii directory to firefly-iii-3.7
- Renamed firefly DB to firefly_3.7
- Created new DB named firefly (with same dbuser - luckily I have admin access to phpMyAdmin)
- $ `composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist`
- merged firefly-iii-3.7/.env into firefly-iii/.env (but forgot about the APP_KEY= entry ... oops)
- $ `php artisan migrate --seed --env=production`
- Using phpMyAdmin, exported new firefly DB structure only and used the SQL file in an editor as a reference
- Adjusted each column in each table of the firefly_3.7 DB with new definitions to match the newly created firefly DB
- Removed, added, or edited all the CONSTRAINTS using phpMyAdmin "Relation View"
- Removed no longer used tables and columns
- Renamed firefly DB to firefly_4.3dist
- Copied firefly_3.7 DB to a new firefly (so now we are using the original DB with 4.3 structure updates)
- $ `php artisan cache:clear`
- $ `php artisan firefly:upgrade-database` (this did something to the entries in budget_limits table)
- Changed hosting PHP to v7.0.14
- Navigated in the browser to the site.

By this time I was pretty tired (around midnight). First thing that happened (after logging in) was an "Ooops" error trying to decrypt preferences:26 which was a new `preferences` entry created at some time during the login (I think). I scanned the .env file and noted that the new install automatically add a base64: KEY to the APP_KEY entry and changed it back to the 3.7 variety "SomeRandomStringOf32CharsExactly" and tried again after restoring the DB from a backup and a cache:clear. Got an error decrypting `preferences`:2 and went looking in the DB for what might be the problem.

In my tired state I had just removed both of the *_encrypted columns from `preferences` and so there was no encrypted "data". So I copied the `preferences` table from the old firefly_3.7 DB and re-did the structure changes. Only this time I removed the data column and renamed the `data_encrypted` column to `data`. Now I had the encrypted preference values in the table.

Ran another cache:clear and restarted browser, navigated to the URL and got the login prompt. This time the login was successful. Yeehaa! Its working.

I hope I have included all the steps and I have documented it here in case others need help migrating from such an old version to 4.3.

Thanks heaps for your help along the way.

Cheers, Graham

**Comment by webenhanced** [comment]
I was wondering if there is a way (via export/import or other means) to change the APP_KEY entry to the more modern base64: style and restore the DB encrypted data using that key?

Do you have any hidden scripts that might do that?

**Comment by JC5** [comment]
Wow, thanks for this write-up! I really feel I must apologize for making you go through all this!

I will extend the upgrade guide with your story. It may help people in the future.

As for the base64 thing. Technically, it is indeed not necessary to "upgrade" your key because it does not really add any security. However, if you wish, do the following on the command line:

`php -a`

In the new terminal, enter this command:

`echo base64_encode("abcde");`

Instead of `abcde` you fill in your app key.

The resulting string, _preceded with_ `base64:` can safely be put into your `.env` file.

**Comment by webenhanced** [comment]
No need to apologize. Open source projects have these issues occasionally. In hindsight, I  think there could be a better way of doing it. The main difficulty was the enum fields and the multi column indexes, so removing them first MAY have allowed an SQL alter table script to be written based on the structure dump from phpMyAdmin.

Thanks for base64 info.

And thanks for providing Firefly III.

**Comment by JC5** [comment]
You're welcome! :D 

I've written new [upgrade instructions](https://firefly-iii.github.io/upgrade-guide/) that include your guide!

**Comment by webenhanced** [comment]
I am just re-opening this to find out where the new upgrade instructions went?

**Comment by JC5** [comment]
Which url exactly? I can set up a redirect. 

https://firefly-iii.github.io/using-upgrading.html

**Comment by webenhanced** [comment]
OK that link is good. The link you added in your comment of jan 15 was https://firefly-iii.github.io/upgrade-guide/ which failed. I think that was its URL when I started doing the upgrade.

**Comment by JC5** [comment]
I see it now, thanks. Both links should now work.
