### ISSUE TITLE
Deleting tags in polish language fails

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#528]
While testing polish translation I've tried to delete an unused tag.
![obraz](https://cloud.githubusercontent.com/assets/4746858/21717261/3e30a24a-d410-11e6-81bb-0ccf26b22d34.png)
Unfortunately error appears:
```
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:
An exception has been thrown during the rendering of a template ("Unable to choose a translation for "The only transaction connected to this tag will not be deleted.|All 0 transactions connected to this tag will spared deletion." with locale "pl_PL" for value "0". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples").") in "/var/www/firefly/resources/views/tags/delete.twig" at line 28.
```
I was able to delete the tag by swithing to English language. Not sure if it's related to translation or maybe there is some bug in the app?

**Comment by JC5** [comment]
That's very strange, because there is no translation present for that sentence in Polish. Aka, it should fall back on the default sentence in English.

I'll look into it!

**Comment by JC5** [comment]
Found the problem, will be fixed in the next release!
