### ISSUE TITLE
[CSV Importer] Error 500 with dev branch

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#5285]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Today I did a pull of the latest code of the dev branch on the csv importer (v2.7.0). When I try to import a csv file without any account mapping I get a HTTP 500. In the logs I have this (I copied only the start of the exception):

[2021-11-14 16:44:54] production.ERROR: compact(): Undefined variable $jobBackUrl {"exception":"[object] (ErrorException(code: 0): compact(): Undefined variable $jobBackUrl at /var/www/html/app/Http/Controllers/Import/RunController.php:106
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/app/Http/Controllers/Import/RunController.php(106): compact()
...

### Expected behaviour

Import of CSV works

### Debug information

Don't have the debug page on the importer

**Comment by MacPaille** [comment]
After more testing this happens only with the configurations that do not use account mapping. Maybe it will help finding what path the application takes to have this error.
When importing CSVs with mapping it's all working.
When trying with CSV without mapping it fails when I click on Submit on the Define Roles page.

**Comment by JC5** [comment]
Nice find, i pushed a fix to the develop branch. Do you need the docker image as well?

**Comment by MacPaille** [comment]
I'm only using the docker image so yes please :) I can validate the fix as soon as it's available

**Comment by JC5** [comment]
Done!

**Comment by MacPaille** [comment]
I confirm it works well :) Thanks!
