### ISSUE TITLE
Automation for multiple accounts

### ISSUE THREAD

**Issue by YukiRed** [firefly-iii/firefly-iii#5287]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Let say I have 1 asset account, and 3 savings account. I want it to auto transfer some percentage of the deposit into those 3 savings account. So:

- Automate transaction for assets, expenses, revenue, liabilities account.

### Solution

To automate the when I want to auto move money between accounts

**Comment by JC5** [comment]
Something to build with the [API](https://api-docs.firefly-iii.org/) perhaps?

**Comment by YukiRed** [comment]
I didn't know it got api so I'll might test it out.
Although the problem with api is needing another thing to manage it which is troublesome

**Comment by JC5** [comment]
Sure but if I have to build it Firefly III has a feature for 1 user, which is equally troublesome 😉

**Comment by YukiRed** [comment]
also true, then no need for the troubles.
