### ISSUE TITLE
Nordigen-Importer: No description being used

### ISSUE THREAD

**Issue by p-rintz** [firefly-iii/firefly-iii#5290]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Importing with nordigen-importer will fail with Revolut bank with the error of "description will need to be filled out" for every single transaction. (Translated to English via German, so the English wording is probably a bit different)

I am not sure if its simply different for Revolut, but the description inside the json download from nordigen is in "remittance_information_unstructured_array".

### Expected behaviour

Import does not fail, and is done including the descriptions.

### Debug information

Debug information generated at 2021-11-15 23:37:36 Europe/Amsterdam for Firefly III version **5.6.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.4 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 31c3e9eb-8e94-40f4-ab3d-5a2dc90c15fe |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2021-11-30 23:59:59 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0 |

### Steps to reproduce

1. Start import for Revolut bank
2. Import fails with "missing description"

### Additional info

Following is an example of one single transaction:

```
    {
      "additional_information": "",
      "additional_information_structured": "",
      "balance_after_transaction": "",
      "bank_transaction_code": "",
      "booking_date": "2021-08-11T00:00:00+02:00",
      "check_id": "",
      "creditor_agent": "",
      "creditor_id": "",
      "creditor_name": "",
      "currency_exchange": [],
      "debtor_agent": "",
      "debtor_name": "",
      "entry_reference": "",
      "key": "booked",
      "mandate_id": "",
      "proprietary_bank": "",
      "purpose_code": "",
      "remittance_information_structured": "",
      "remittance_information_structured_array": [],
      "remittance_information_unstructured": "",
      "remittance_information_unstructured_array": [
        "Apple Pay Top-Up by *1234"
      ],
      "transaction_id": "12341234123123123123123123123123123",
      "ultimate_creditor": "",
      "ultimate_debtor": "",
      "value_date": "2021-08-11T00:00:00+02:00",
      "account_identifier": "",
      "debtor_account": {
        "iban": "",
        "currency": ""
      },
      "creditor_account": {
        "iban": "",
        "currency": ""
      },
      "transaction_amount": {
        "amount": "100.00",
        "currency": "EUR"
      },
      "end_to_end_id": ""
    },
```

**Comment by JC5** [comment]
I may have a fix in the develop image for the nordigen importer. Could you check it out?

**Comment by p-rintz** [comment]
Sure, I will try it out, thanks.

**Comment by p-rintz** [comment]
Yes. That worked for the description issue. Though now the import will run through all transactions and then never seems to end and will run forever with the logs simply showing: "/import/sync/status?syncIdentifier=asdbasdasdv12312"

Should I open a different issue for that?

**Comment by JC5** [comment]
I expect that the importer crashes at some point during the import. Before it starts looping there should be some logs and/or errors.

**Comment by p-rintz** [comment]
If its expected, thats fine. It imported everything fine it seems, before it got stuck in the loop.

Ill see if I can get you those logs some time soon, if it helps.

Ill close this issue for now then, as this is solved.
