### ISSUE TITLE
Budgets: Add option to add/remove money or move money to another budget

### ISSUE THREAD

**Issue by micheh** [firefly-iii/firefly-iii#5293]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Currently, when I want to add or remove some money from a budget, I have to manually calculate the new budgeted amount. If I want to transfer some money from one budget to another, the new budgeted amount has to be calculated twice (once for the budget from where the money is removed and once for the budget where the money is added). I think it would be nice to have a more easy way to add or remove money from/to a budget or even add the possibility to move money from one budget to another.

### Solution

The solution could be comparable to the piggy banks with two buttons to add or remove money (implemented for the "Saved so far" amount). Ideally there would also be a third button to move money to another budget.

### What are alternatives?

Calculate the new amount manually and enter it in the input field.

**Comment by JC5** [comment]
Meh, it doesn't feel too difficult to do this manually. I can keep a note to check out the possibilities in the new layout, but no promises.

**Comment by micheh** [comment]
Would it be an idea to execute a math expression parser when an amount input field loses focus?
Let's say you enter `34.6+7.7` into the input field. Once the input field loses focus, the math expression parser is executed and will replace the input field value with the final amount `42.3`. This way you wouldn't need an external calculator and don't have to add new buttons etc. into the layout.

For example: https://www.npmjs.com/package/math-expression-evaluator
