### ISSUE TITLE
Pressing Enter when selecting a description or category on a new transaction does not advance the form (V2)

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#5296]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

In 5.6.3 on the V2 layout, when you create a new transaction, if you hit 'enter' on an autofill suggestion for the description or category, it does not advance the cursor automatically to the next box. It does do this when you are selecting a source account or destination account in this manner.

### Expected behaviour

I'd expect consistency in how the form functions: either advance the form in every scenario or don't advance it in any of them.

### Debug information

Debug information generated at 2021-11-16 21:40:01 America/New_York for Firefly III version **5.6.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.3 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2021-11-30 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 |

### Steps to reproduce

1. Be on V2
2. Start a new transaction
3. Select either the description box or category box with your mouse (because tabbing to them is too tedious)
4. Use your arrow keys to select an autofill option and then press Enter
5. Notice that the cursor disappears completely
6. Go to either the source or destination account boxes and repeat step 4.
7. Notice that the cursor advances to the next box.

**Comment by death2cupbots** [comment]
Oh I see it's just not done yet according to #5165

**Comment by JC5** [comment]
Indeed, but let's leave this open or i keep forgetting it. :D

**Comment by JC5** [comment]
Unfortunately, I cant jump away from category to tags because the library I use doesn't have a reference to its input. But the description will jump.
