### ISSUE TITLE
The V2 transaction form should start with the description box preselected.

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#5297]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

23 tab presses are currently required to get to the start of the transaction form in V2. In V1, the number of required tab presses was 0. The forms would be more accessible with the first box being preselcted.

### Solution

Have the first box on a V2 form be preselected (like it is in V1)

### What are alternatives?

You have to press tab a silly number of times to get to the start of the form.

**Comment by JC5** [comment]
Will do!

**Comment by JC5** [comment]
This will auto expand the box so its not going to be a feature. However, the tabindex is better so just 2 tabs are necessary.
