### ISSUE TITLE
V2 Asset account transactions view not allowing changing dates

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#5298]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Using the small dragon icon from the dashboard or the asset accounts list (i.e. /accounts/asset) does allow to choose for a Date range to show the transactions.
Using the same icon when showing the transactions of a specific account (i.e /accounts/show/1543) does not allow it. Meaning I have to go back to on of the other pages, change the range then go back to my transactions to see them for the dates I want...

Even if I use multiple tabs I still have to completely refresh my accounts/show page as the small refresh button on the page does not make use of that new selected range

### Solution

Allow changing the date range also on the accounts/show page

**Comment by JC5** [comment]
Thanks, I'll check it out.

**Comment by JC5** [comment]
There will be a better way to navigate between dates in a future version of the layout. Closed for now.
