### ISSUE TITLE
Net worth and Income vs. expenses charts are for displaying only on currency

### ISSUE THREAD

**Issue by nbbn** [firefly-iii/firefly-iii#5299]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Net worth and Income vs. expenses charts are for displaying only on currency. On Y axis there are values in your default currency. When you have multiple currencies in your assets, they are treated nominally as your default currency, e.g. net worth is show on chart as 10k EUR (default currency) + 10k USD = 20k EUR (not true, as my valid net worth should be around 10kEUR + 10kUSD*exchange_rate. This is annoying especially in case of change of net worth over time. You spend EUR and you see less change than in your less value currency (e.g. USD)

### Expected behaviour

I think there can be a database of currency exchange rates so historical net worth and incomes/expenses can be displayed in your main currency. Or at least there should be some default predefine fixed exchange rates to be defined in currencies config. (e.g. I could say 1USD = 0.9 EUR for all reports and all periods.

### Debug information

Debug information generated at 2021-11-17 19:59:01 UTC for Firefly III version **5.6.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.4 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 2808c177-f52b-44b9-b6a6-d63dffa7f6fb |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ |  |
| Browser TZ | Europe/Warsaw |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-11-17 00:00:00 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0 |

### Steps to reproduce

1. Own assets in different currencies,
2. navigate to Reports -> Default financial report -> Current year, all accounts 
3. Look on net worth chart, value will be not true, as currencies other than main one will be exchanged with rate 1. (e.g. 1k eur = 1k usd)

**Comment by mvicomoya** [comment]
+1

I wonder how difficult would it be to pull live exchange rates for your enabled currencies at page load time and apply such exchange rates to any outputs on the frontend that uses them. E.g. net worth number, income vs. expenses charts...

Basically, always have a real view of your multi-currency balances in terms of your default currency.

**Comment by JC5** [comment]
Hi, that's a good idea and something that I will look into for the new release. 

@mvicomoya There used to be a feature that did that, the table is still in your installation. But it comes with a massive maintenance burden so I dropped it. It will not come back.

Since there are several tickets with the same idea, I'm going to close this one.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/#automated-currency-conversion-so-everything-is-in-euros-or-dollars

**Comment by nbbn** [comment]
Well, I think even ability to define default fixed exchange rate (it's popular in international companies to do all financial planning with assumption that e.g. 1EUR=0.8GBP). IMO it could be good idea to put this in settings -> currencies (maybe with default 1 is it is currently). This fixed rate would be used only in reporting, infoboxes, etc. to do not mix with transactions. In real life transactions exchange rates from your bank/exchange are applied, and as far as I know, in Firefly III you specify amounts on both sides of transaction e.g. 14.23EUR = 10.12GBP, not exchange rate (in Gnucash you can specify both).
