### ISSUE TITLE
Update Problems handling the post-update-cmd event

### ISSUE THREAD

**Issue by worldworm** [firefly-iii/firefly-iii#530]
Hi there,

run into a problem updating everything.

Error:

Script php artisan firefly:upgrade-instructions handling the post-update-cmd event returned with an error

                                                                                                        
  [RuntimeException]                                                                                    
  Error Output: PHP Fatal error:  Class TwigBridge\Twig\Loader contains 1 abstract method and must the  
  refore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSourceConte  
  xt) in /var/www/%DOMAIN%/vendor/rcrowe/twigbridge/src/Twig/Loader.php on line 24            
  PHP Fatal error:  Uncaught InvalidArgumentException: View [emails.error-html] not found. in /var/www  
  /%DOMAIN%/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137               
  Stack trace:                                                                                          
  #0 /var/www/%DOMAIN%/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79):   
  Illuminate\View\FileViewFinder->findInPaths('emails.error-ht...', Array)                              
  #1 /var/www/%DOMAIN%/vendor/laravel/framework/src/Illuminate/View/Factory.php(174): Illumi  
  nate\View\FileViewFinder->find('emails.error-ht...')                                                  
  #2 /var/www/%DOMAIN%/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(430): Illumin  
  ate\View\Factory->make('emails.error-ht...', Array)                                                   
  #3 /var/www/%DOMAIN%/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(310): Illumin  
  ate\Mail\Mailer->getView('emails.error-ht...', Array)                                                 
  #4 /var/www/%DOMAIN%/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(186): Illumin  
  ate\Mail\Mailer->addContent(Object(Illuminate\Mail\Message), 'emails.error-ht...', 'emails.error-te.  
  ..', NULL in /var/www/%DOMAIN%/vendor/laravel/framework/src/Illuminate/View/FileViewFinder  
  .php on line 137

**Comment by JC5** [comment]
I know what causes it. At which point did you get this error? During installation? During upgrade?

The solution: open `composer.json` and add `"twig/twig": "1.30.0",` before the line `"rcrowe/twigbridge": "0.9.*",`. Then, run these commands:

- `rm -rf vendor/ composer.lock`
- `composer update --no-dev --no-scripts`
- `composer update --no-dev`

**Comment by worldworm** [comment]
Thanks, it is working now and updated everything to 4.3.

**Comment by JC5** [comment]
The next version of Firefly will do this automatically. You may have to checkout composer.lock from Github to make sure you get the latest version.
