### ISSUE TITLE
Nordigen Importer: Account for pending transactions

### ISSUE THREAD

**Issue by sebastianklein96** [firefly-iii/firefly-iii#5300]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Some online banks (to my knowledge at least DKB, N26, possibly others) will show not yet completed card payments as pending in their web UI. Those will reflect in the balance displayed in the web UI. 

Said transactions will not be visible to the Nordigen API though and are therefor not available for the Nordigen Importer to process. This results in a balance discrepancy between the banks web UI balance and Firefly III account balance.

### Solution

Allow the user to check a box labeled "Account for pending transactions".

Said box triggers following mechanism during import:
- first check the config if "Account for pending transactions" is enabled. If that is the case, search for and remove the old "Pending transactions" transaction
- then persist all newly picked up transactions as usual
- afterwards importer grabs actual account balance via ​/api​/v2​/accounts​/{id}​/balances​/ (resulting JSON contains array of balance objects, use the most recent one)
- Importer checks account balance of Firefly III account (FA) mapped to Nordigen account (NA)
- if balance FA != balance NA: create an artificial transaction called "Pending transactions" and set its value to the difference between FA and NA (it would be beneficial if the transaction could not be modified by the user afterwards)
- persist said transaction into FA

**Comment by JC5** [comment]
Sorry no, I'm not going to introduce system magic to account for this difference. Wait for the transaction to clear.

**Comment by sebastianklein96** [comment]
Alright, no problem. Thanks for the answer!
