### ISSUE TITLE
Nordigen Wise import infinite loop

### ISSUE THREAD

**Issue by kgyl** [firefly-iii/firefly-iii#5303]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Starts importing an Wise account and gets stuck in infinite loop.

### Expected behaviour

Should import all transactions from 4 accounts and end the process.

### Debug information

Debug information generated at 2021-11-21 12:23:57 Europe/Budapest for Firefly III version **5.6.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.4 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | d5b69ace-f59d-4ceb-9ea9-a7ab94cfb740 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| System TZ | Europe/Budapest |
| Browser TZ | Europe/Budapest |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2021-11-30 23:59:59 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 |

Information from nodgen_import log:
[2021-11-21 11:18:24] production.DEBUG: [5/5] Done sending transaction.  
[2021-11-21 11:18:24] production.DEBUG: Done with App\Services\Nordigen\Sync\SendTransactions::send  
172.21.0.1 - - [21/Nov/2021:11:18:19 +0000] "POST /import/sync/start?syncIdentifier=RwXIhHELTOM2ArfN HTTP/1.1" 200 207 "http://localhost:8081/import/sync" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
172.21.0.1 - - [21/Nov/2021:11:18:24 +0000] "GET /import/sync/status?syncIdentifier=RwXIhHELTOM2ArfN HTTP/1.1" 200 1525 "http://localhost:8081/import/sync" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
172.21.0.1 - - [21/Nov/2021:11:18:24 +0000] "GET /import/sync/status?syncIdentifier=RwXIhHELTOM2ArfN HTTP/1.1" 200 1525 "http://localhost:8081/import/sync" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
172.21.0.1 - - [21/Nov/2021:11:18:25 +0000] "GET /import/sync/status?syncIdentifier=RwXIhHELTOM2ArfN HTTP/1.1" 200 1525 "http://localhost:8081/import/sync" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
172.21.0.1 - - [21/Nov/2021:11:18:25 +0000] "GET /import/sync/status?syncIdentifier=RwXIhHELTOM2ArfN HTTP/1.1" 200 1525 "http://localhost:8081/import/sync" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
172.21.0.1 - - [21/Nov/2021:11:18:26 +0000] "GET /import/sync/status?syncIdentifier=RwXIhHELTOM2ArfN HTTP/1.1" 200 1525 "http://localhost:8081/import/sync" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
172.21.0.1 - - [21/Nov/2021:11:18:26 +0000] "GET /import/sync/status?syncIdentifier=RwXIhHELTOM2ArfN HTTP/1.1" 200 1525 "http://localhost:8081/import/sync" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
172.21.0.1 - - [21/Nov/202

### Steps to reproduce

1. no config
2. authorized Wise for 4 accounts (USD, EUR, GBP, HUF)
3. assigned correct currency accounts to them
4. click to import 
5. auto mapping
6. gets stuck in infinite loop after importing 5 transactions

**Comment by JC5** [comment]
Unfortunately, your logs don't include enough details to tell me if and why there is an infinite loop.

**Comment by kgyl** [comment]
What would you need?

**Comment by JC5** [comment]
Logs of the import process. The snippet you share starts of well but then it's only http requests.
