### ISSUE TITLE
Database limits to 4 decimals

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#531]
Hi, the database seems to only store 4 decimals.
Is it just my database and the upgrade to 4.3.1 wasn't completely successful or a general problem?

> +------------------------+----------------------+------+-----+---------+----------------+
> | Field                  | Type                 | Null | Key | Default | Extra          |
> +------------------------+----------------------+------+-----+---------+----------------+
> ....
> | amount                 | decimal(14,4)        | NO   |     | NULL    |                |

It's the same on two instances, one is still version 4.3.1, the other is version 4.3.2.

**Comment by JC5** [comment]
Mmm. Well, you can safely changed it manually to decimal(22,12).

**Comment by xpfgsyb** [comment]
Yep, did that and it's fine for me now.

If somebody else has the same problem:
Connect to mysql: `mysql -u user -p`
Switch to the firefly database, change if your setup differs: `use firefly;`
Check the actual column type of amount: `SHOW COLUMNS FROM transactions;`
If the type is decimal(14,4), change it with this command: `ALTER TABLE transactions MODIFY COLUMN amount decimal(22,12);`
Recheck if the type is ok now: `SHOW COLUMNS FROM transactions;`
Exit: `exit;`

**Comment by JC5** [comment]
Updated the upgrade guide!

https://firefly-iii.github.io/upgrade-guide/
