### ISSUE TITLE
Nordigen Import - Incorrect Transaction date imported

### ISSUE THREAD

**Issue by Gradecak** [firefly-iii/firefly-iii#5311]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

From what I can tell, currently the Nordigen importer uses the the `valueDate` field to determine the transaction date when importing to Firefly III. 

As this field is optional it would be ideal to have the choice to determine transaction dates based on the `bookingDate` field or `valueDate` field

Additionally, if a `valueDate` is missing, the data import filtering will not work correctly (from what I could tell).

### Solution

Ideally this would be an automatic fallback, or potentially a toggle in the configuration?

### What are alternatives?

Currently I have to manually edit transactions after import in order for them to appear in the correct date, and also delete any transactions that were imported beyond the range I intended

### Additional context

I would be happy to help out with this if you accept PR's and could nudge me in the right direction :slightly_smiling_face:

**Comment by JC5** [comment]
Could you share an example transaction with the values that Nordigen returns?

I appreciate the help! For now, no PR's. I'm working on a universal data importer (see [here](https://github.com/firefly-iii/data-importer)) that already includes all Nordigen code. I hope to release that instead of a new version of the Nordigen one.

**Comment by Gradecak** [comment]
>Could you share an example transaction with the values that Nordigen returns?

Of course, here's a snippet of a Nordigen transaction data (grabbed from their web data explorer with some info redacted :slightly_smiling_face: )

```
            {
                "bookingDate": "2021-11-20",
                "creditorName": "XXX VBARS B",
                "endToEndId": "NOTPROVIDED",
                "remittanceInformationUnstructured": "XXX<br>Pasvolgnr: 901 19-11-2021 13:18<br>Transactie: F8F746 Term: CT472851<br>Valutadatum: 20-11-2021",
                "transactionAmount": {
                    "amount": "-7.30",
                    "currency": "EUR"
                },
                "transactionId": "010203519019484070000000"
            },
```
This is just one example, but it would appear that for all the transactions gotten from my bank `valueDate` is not set. 
Also looking [at the transaction nordigen docs](https://nordigen.com/en/docs/account-information/output/transactions/) it seems to confirm that `valueDate` might not always be present

>I appreciate the help! For now, no PR's. I'm working on a universal data importer (see here) that already includes all Nordigen code. I hope to release that instead of a new version of the Nordigen one.

That's really awesome I'll keep an eye out on that!

**Comment by JC5** [comment]
:+1:

**Comment by Gradecak** [comment]
In the interim, would it be possible to share the Dockerfile used to generate the current docker images? I can't seem to find it in the repo and it would help me greatly deploying the patched fork until the universal data importer is ready.

**Comment by JC5** [comment]
https://dev.azure.com/Firefly-III/_git/ImportToolImage

**Comment by JC5** [comment]
Will be fixed in the new data importer.

**Comment by diegombeltran** [comment]
Hello, JC5, first of all thank you for your work and time with this amazing project. Please let me know if I should open a new GitHub issue.

I read the code and it looks like if valueDate exists, Firefly3 chooses this over bookingDate. I realized that, for my bank, the correct date returned is bookingDate. Is there any way to choose this over valueDate? Maybe a selector?

Thank you again.

**Comment by JC5** [comment]
I'll see what I can do.

**Comment by JC5** [comment]
Just for the heck of it I've switched them around in the latest `develop` build. Looking at the slightly ambiguous description in the docs it would fit better.

It won't be an option I'm afraid.

**Comment by diegombeltran** [comment]
Works as expected. Amazing!!
