### ISSUE TITLE
CSV Importer with Y-m-d h:m:s timestamp results in transaction with incorrect date

### ISSUE THREAD

**Issue by DanielHouston** [firefly-iii/firefly-iii#5312]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

An export from Revolut in csv, with date/time in the `Y-m-d h:m:s` format, results in transactions created far into the future. In the case of a date of 2021-08-02 01:15:04, we get a transaction on June 2nd 2025
![image](https://user-images.githubusercontent.com/665785/142856146-46eb191e-7750-4823-9e94-8bd4e93fac2d.png)
(Please ignore the incorrect source account. Used this empty Asset account for testing)

### Expected behaviour

I would expect the date/time after importing to firefly iii to match the values as expressed by the string in the input csv. 2021-08-02 01:54:02 should be 2nd August 2021 @ 01:54:02

### Debug information

Debug information generated at 2021-11-22 11:49:33 UTC for Firefly III version **5.6.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.4 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | ebca99ec-a71d-4c4c-a0d4-0a189a81d798 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ |  |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2027-02-28 00:00:00 |
| Session first | 2019-11-10 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36 |

### Steps to reproduce

1. Export transactions from Revolut as CSV files
2. Import to firefly iii via the csv importer with default importing settings
3. Explore transactions by increasing period range to a few years in the future

### Additional info

I have a gut feeling this maybe as the csv uses a string representation of the date/time rather than an epoch timestamp?
Find below the csv values used for testing

```
Type,Product,Completed Date,Description,Amount
CARD_PAYMENT,Current,2021-08-02 01:54:02,Sainsburys,-52.7
TRANSFER,Current,2021-08-03 12:20:47,Depositing savings,-0.37
```

**Comment by JC5** [comment]
To be sure, your import configuration is `Y-m-d H:i:s, right?

**Comment by DanielHouston** [comment]
No, you're right, I'm an idiot here and only checked that the string in the importer UI looked reasonable (ie. looks like a real date time to me!) before proceeding.

In case someone finds this in the future; `Y-m-d h:m:s` is going to have what you might expect the minutes field, replaced with the Month. as JC points out, `Y-m-d H:i:s` is the correct import configuration to include the timestamp infromation here
