### ISSUE TITLE
Nordigen Importer: ignore duplicate transactions config not respected

### ISSUE THREAD

**Issue by Gradecak** [firefly-iii/firefly-iii#5322]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

`ignore_duplicate_transactions` config key is not respected by the importer

### Expected behaviour

specifying `ignore_duplicate_transactions: false` should import transactions even if duplicates are detected

### Debug information

N/A

### Steps to reproduce

1. Run importer
2. Delete Imported transactions form firefly iii
3. Set `ignore_duplicate_transactions` to `false`
4. Run importer
5. Duplicate transactions are not imported

### Additional info

I believe [this line](https://github.com/firefly-iii/nordigen-importer/blob/c99a97222b09429c3390153fe6a137b6dadfb066/app/Services/Nordigen/Sync/GenerateTransactions.php#L201) is the culprit as it doesn't read the configuration `isIgnoreDuplicateTransaction` field

**Comment by JC5** [comment]
Yep, that's still on my list!

**Comment by JC5** [comment]
This will be fixed in the new data importer!

https://github.com/firefly-iii/data-importer
