### ISSUE TITLE
On transaction edit return to referring page

### ISSUE THREAD

**Issue by jasonwinget** [firefly-iii/firefly-iii#5323]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

After editing a transaction refer to the specific page of transactions that called the edit. 

### Solution

If you are on page 3 of your checking account transaction list, then edit a transaction you should return to page 3 after you update the transaction.

**Comment by JC5** [comment]
What are you running into, exactly? This has been a feature since like 2005.

**Comment by jasonwinget** [comment]
Typically there is a ?page=999 _GET variable in the URL on page load.  When you go to edit a transaction and save back to the list the page= is not present in the callback URL.  So you go from page XX to page 1 always because it lacks the variable.

Steps:

1. Go to page >1 in your checking account transaction list (for example page 3)
2. Choose any transaction and edit it.
3. Save the transaction.
4. You will be returned to page 1 of the checking account and will not be directed to page 3.

**Comment by JC5** [comment]
Ah yes, this will be fixed in the new layout, not in the old one. Sorry about that.
