### ISSUE TITLE
Automatic Currency Conversion for informational purposes

### ISSUE THREAD

**Issue by Geek-MD** [firefly-iii/firefly-iii#5324]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Automatic currency conversion for information purposes, not for accurate accounting. The main currency I use is CLP, but I also make buys at Amazon that are payed with a Credit Card in USD.

I know that bank will use a custom conversion rate which is different than market conversion rate, but when comparing USD asset with CLP asset on assets graph, USD asset is too close to zero line, so graph is useless under that conditions.

So converting that asset to default currency for information purposes would be a good add in.

### Solution

Convert foreign or not default currencies to default currency for graphic information purposes.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/
