### ISSUE TITLE
Editing negative initial balance on credit card asset, changes automatically to positive balance 

### ISSUE THREAD

**Issue by Geek-MD** [firefly-iii/firefly-iii#5325]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Credit card and credit lines must be registered as negative entries because they are are debt. Initial balance may be negative when you owe money to the bank.

If I edit initial balance, negative values changes automatically to positive values, which is a bug.

### Expected behaviour

Editing a negative initial balance must remain as negative.

### Debug information

It's not a debug bug

**Comment by JC5** [comment]
Oh nice, I'll check it out!

The debug info is useful to know which version and environment you're running Firefly III on.
