### ISSUE TITLE
Automation Trigger: Internal Reference contains..., begins with...., ends with...

### ISSUE THREAD

**Issue by jasonwinget** [firefly-iii/firefly-iii#5326]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Automation triggers for "Internal Reference" only has a "is..." trigger.  

### Solution

Please expand with contains, begins with, and ends with to complement the other triggers.

### Additional context

![image](https://user-images.githubusercontent.com/3647696/143725304-ef4b2deb-601b-4226-9cb0-8ac07d8d3327.png)

**Comment by JC5** [comment]
I'll write it down!
