### ISSUE TITLE
V2 Button text on delete account is confusing

### ISSUE THREAD

**Issue by 3ssen** [firefly-iii/firefly-iii#5327]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm using 5.6.4. When trying to delete an account the texts indicate it is your account. Not only the expense account.

See attached image:
Home / Crediteuren / Pay / Verwijder je account
!Verwijder je acount
Button: Verwijder je account

### Expected behaviour

Change text from "verwijder je account" to "verwijder account"

### Debug information

not needed

### Steps to reproduce

1. Go to /accounts/expense
2. Click on actions -> delete

### Additional info

![image](https://user-images.githubusercontent.com/2758036/143763345-6ef26d47-6c14-4b16-b0a2-f1999f526e4f.png)

**Comment by JC5** [comment]
Thanks, I'll pick it up!

**Comment by JC5** [comment]
Fixed in the new release.
