### ISSUE TITLE
V2 expense accounts list is not updated after deleting account

### ISSUE THREAD

**Issue by 3ssen** [firefly-iii/firefly-iii#5328]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When deleting an account from te expense accounts list it still remains on the accounts list.

A click on the account sends you back to the account list page.

### Expected behaviour

The account list should be updated. The deleted account should not be in the list.

### Debug information

not needed

### Steps to reproduce

1. Go to accounts list and delete an account
2. See the account in the list

**Comment by JC5** [comment]
Same bug 

https://github.com/firefly-iii/firefly-iii/issues/5298
