### ISSUE TITLE
Transactions list on lengthy descriptions

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#533]
Hi,
just a little cosmetical issue ;-) The buttons on the left of each transaction jump to another row when the description gets long and this doesn't look that nice.
I have a lot of long descriptions because I usually import my bank statements.

https://firefly-iii.nder.be/accounts/show/1
![image](https://cloud.githubusercontent.com/assets/441924/21817825/d5f284d8-d765-11e6-8b5d-819ad05dc82b.png)

**Comment by JC5** [comment]
Mmm, that's actually a tricky one. I can force the buttons to a certain width to fix it, but I'll have to do some googling to make sure I use the correct CSS. I'm not sure a pixel-width (which would be my goto code) will fix it up nicely. 

But it'll look better in the next release for sure.
