### ISSUE TITLE
Deleting the final split on a new transaction makes the form disappear (V2)

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#5335]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When you are creating a new transaction in V2, if you have more than one split, deleting the last split makes the whole form disappear. If you have 2 or more splits remaining, you can select one of those splits to get the form back. If you only have one split remaining, you must create a new split in order to get the form back.

![image](https://user-images.githubusercontent.com/21091510/143888689-5df735be-dbb6-4395-94e3-aa9284002164.png)

Deleting the first split or any of the middle splits just brings you to the next remaining split.

### Expected behaviour

Once you've deleted a split, the form should return you to a still existing split.

### Debug information

Debug information generated at 2021-11-29 09:46:54 America/New_York for Firefly III version **5.6.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.5 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Telemetry | false |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-11-01 00:00:00 |
| Session end | 2021-11-30 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 |

### Steps to reproduce

1. Start a new transaction (doesn't matter which type)
2. Add a split
3. Delete the new added split (i.e. Split 2)
4. See that the form has disappeared

### Additional info

So I guess the form just shifts all the splits left once it deletes one and it technically stays on the same split. Could you maybe have it return to the primary split instead? This is what happens when deleting a split on an existing transaction.

**Comment by JC5** [comment]
> So I guess the form just shifts all the splits left once it deletes one and it technically stays on the same split.

Something like that, although it should re-render the entire form. Wouldn't be surprised if all splits are gone if you press the wrong button. Thanks for letting me know. I thought I fixed this one earlier 😁

**Comment by JC5** [comment]
Fixed in the next release!
