### ISSUE TITLE
Data-importer fails to read CSV delimiter correctly

### ISSUE THREAD

**Issue by Snyaify** [firefly-iii/firefly-iii#5339]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When i'm trying import data from csv, and building new config, after choosing csv file i'm trying to set CSV delimiter - A Semicolon.   On next step when dialog box promt me to map column to operations, i see that CSV delimiter is changed back to "," and i see a mess (see attached screenshot)
[screenshot](https://trashcan.be4free.ru/cePA6/CEViquda79.jpg)

### Expected behaviour

in csv-importer with same config all fine:
[screenshot](https://trashcan.be4free.ru/cePA6/LIHuBahA46.jpg)

### Debug information

can't find how to check debug page in data-importer :(

### Steps to reproduce

You can see steps in attached video link:
[Video](https://trashcan.be4free.ru/cePA6/feyOfIgO06.mp4)

**Comment by JC5** [comment]
Thanks for letting me know. I'll check if the [data importer](https://github.com/firefly-iii/data-importer) has the same issue and get back to you.

**Comment by JC5** [comment]
This will be fixed in the new data importer :+1:. 0.2.0 will be released this weekend!
