### ISSUE TITLE
Date format on form fields is `mm/dd/yyyy` and doesn't seem to change with site or browser locale

### ISSUE THREAD

**Issue by dklymenk** [firefly-iii/firefly-iii#5340]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The date field on form field is always in format mm/dd/yyyy (en_US) even though I have en_GB in both the firefly settings and in my browser. 

### Expected behaviour

The date format should reflect site settings or user's browser locale.

### Debug information

Debug information generated at 2021-12-01 14:47:09 Europe/Istanbul for Firefly III version **5.6.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.5 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 69983e38-bb04-4116-a78e-f892264cf46b |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| System TZ | Europe/Istanbul |
| Browser TZ | Europe/Istanbul |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_GB |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-12-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2020-12-19 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 |

### Steps to reproduce

1. Go to https://demo.firefly-iii.org/transactions/create/withdrawal
2. The date format is mm/dd/yyyy
3. Go to https://demo.firefly-iii.org/preferences
4. Set language to en_GB or pretty much any other language+locale that doesn't use mm/dd/yyyy as a date format.
5. Go back to https://demo.firefly-iii.org/transactions/create/withdrawal
6. The date format is still mm/dd/yyyy

**Comment by JC5** [comment]
The format of the date field is defined by your browser and OS language settings.

**Comment by dklymenk** [comment]
> The format of the date field is defined by your browser and OS language settings.

Ok, this my a screenshot from my browser settings panel.
![DeepinScreenshot_select-area_20211201134628](https://user-images.githubusercontent.com/64093836/144236078-b553efbf-23b2-42c8-bbc4-e392962d2591.png)

And here is one to show my system locale:
![DeepinScreenshot_select-area_20211201134601](https://user-images.githubusercontent.com/64093836/144236142-10cb391d-e87f-41eb-a6d2-6ea265eccf4a.png)

When I get `navigator.language` in my browser console I get en_GB too.
![DeepinScreenshot_select-area_20211201154121](https://user-images.githubusercontent.com/64093836/144236379-b5016f01-4e06-46cd-a0ef-62df712fb44c.png)

If I change the locale via dev tools to something like ru_RU, the form field is still in us format.
![DeepinScreenshot_select-area_20211201154403](https://user-images.githubusercontent.com/64093836/144236575-7104d394-8c46-4d88-8e34-f17d44d34c34.png)

I have the exact same settings in firefox and observe the same issue there.

Also you are saying "browser and OS language settings", but which one is it exactly? Where should I look to find the setting it is looking for?

**Comment by JC5** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by dklymenk** [comment]
Turns out I have had `export LANG=en_GB.utf8` in my `.bashrc` and apparently starting any program on my system sources it even if I don't specifically start it from terminal.

Thanks for forwarding me in the right direction.
