### ISSUE TITLE
Extend importer with external URL field

### ISSUE THREAD

**Issue by kruemelro** [firefly-iii/firefly-iii#5342]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be usefull if i could import data into the external URL field of a transaction. 

Background:
i pipe all my transactions through a nodeRed flow to clean them up. Afterwards i generate a csv which will be handed to the csv importer. Many companys have the order or customer number in the description of the transaction. It's easy to extract them and build a url which will directly go to your order.

For Examle:
Amazon transaction description:
111-2222222-3333333 AMZN Mktp DE XA ANOTHERCUSTID
URL for Amazon Order Info in Germany:
https://www.amazon.de/gp/your-account/order-details/ref=ppx_yo_dt_b_order_details_o03?ie=UTF8&orderID=111-2222222-3333333

### Solution

Extend Importer with external_URL Field

### Additional context

It's already possible to import the url into the note field. But the note field open Links in the same tab. The external_URl field opens in a new tab.

**Comment by JC5** [comment]
I'll add it to the [data importer](https://github.com/firefly-iii/data-importer)!
