### ISSUE TITLE
[v2] Swap the budget status bar colors

### ISSUE THREAD

**Issue by e46forlife** [firefly-iii/firefly-iii#5352]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

The color of the bars associated with budge line items on the home page are confusing to me.  Currently, the bar is RED if you exactly hit a budget amount, and ORANGE if you exceed a bugeted amount.  This is confusing to me on first glance.  I attached an example of what I am describing in the picture below.

![image](https://user-images.githubusercontent.com/90415753/144677398-e3254718-bdb7-483c-8d59-4a9649535966.png)

### Solution

I would suggest changing these colors.  Personally I would want it to simply be GREEN if amount spent <= amount bugeted and RED if amount spent is > amount bugeted.

### What are alternatives?

Alternatively, perhaps the color can change based on user defined conditionals in the preferences page?

### Additional context

Love the program overall!  Keep it up :)

Dan

**Comment by JC5** [comment]
Thanks for the compliments!

It will not be a preference. The idea was that the red bar will shrink in favor of the orange (or vice versa) so you see how much you overspent. I'll check it out!

**Comment by e46forlife** [comment]
> Thanks for the compliments!
> 
> It will not be a preference. The idea was that the red bar will shrink in favor of the orange (or vice versa) so you see how much you overspent. I'll check it out!

So that is how the total budget bar for the month works in the budget tab, and I am perfectly fine with that!  

To be more specific, the issue I described above is referring to the bars associated with an individual budget item on the Dashboard page in the section called “Custom timed budgets.” The individual budget bars in that section are only ever fully red or fully orange if the budget line item is >= the budgeted amount, it does not have the same behavior as the total budget bar in the budget tab. 

Hopefully that makes sense? Again, love the tool, thanks so much!

**Comment by JC5** [comment]
<img width="659" alt="Screenshot 2021-12-10 at 15 42 55" src="https://user-images.githubusercontent.com/5889984/145591922-6dfbdccc-fa5b-4b17-9592-9a0b28c98566.png">


Will be fixed in the next release.

**Comment by e46forlife** [comment]
Awesome! Thank you so much!
