### ISSUE TITLE
Could not find package grumpydictator/firefly-iii with version 5.6.5 in a version installable using your PHP version, PHP extensions and Composer version.

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#5357]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am trying to upgrade an existing firefly-iii instance and I am running into this error.  I am running the host on a: 

Fedora 34
PHP 7.4.26 (cli) (built: Nov 16 2021 15:31:30) ( NTS )
Composer 2.1.14 2021-11-30 10:51:43

I have the same error using both commands with or without --prefer-dist:
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated 5.6.5
composer create-project grumpydictator/firefly-iii --no-dev firefly-iii-updated 5.6.5

If I run the command without version, it will install version 5.5.13.
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated

Thanks in advance

### Expected behaviour

installed latest version withour error

### Debug information

N/A

### Steps to reproduce

composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated 5.6.5

**Comment by JC5** [comment]
Firefly III requires php 8.0. minimum I'm afraid. Hence the error.

**Comment by lverissimo** [comment]
Good reason! Thank you.

**Comment by lverissimo** [comment]
working with php 8! thanks
