### ISSUE TITLE
iCal endpoint to integrate with any calendar app?

### ISSUE THREAD

**Issue by Upgreydd** [firefly-iii/firefly-iii#5358]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- I'd like to have a link to add to my calendar app to have incoming payments from `bills` there. 

### Solution

Endpoint with a token to generate a calendar with incoming events 

### What are alternatives?

None

**Comment by JC5** [comment]
No sorry, that's not something I want to add to Firefly III. If you want to, you can use the API to collect the necessary information and generate an iCal File.
