### ISSUE TITLE
UTF-8 Encoding problem with German Language

### ISSUE THREAD

**Issue by dabenzel** [firefly-iii/firefly-iii#536]
Hey There!

We have a problem with the german "umlaute" like ä,ö,ü. I think in the language file its (in the case shown in the picture below) `März` and not `M&auml;rz`.

I haven't found this term in the Crowdin project. 

![firefly utf8 problem](https://cloud.githubusercontent.com/assets/2480235/21962573/07a2a9ce-db29-11e6-9531-6d54a5f2cd8f.PNG)

**Comment by JC5** [comment]
Hi dabenzel,

You're right, these string are not in the Crowdin project. They're generated by PHP itself using, ultimately, the [sprintf](http://php.net/manual/en/function.strftime.php) function. 

I suspect this is a local problem. The [demo site](https://firefly-iii.nder.be/) does not seem to suffer this problem. I may have a solution that will force these strings to be utf8, although they already should be.

Could you run the following command on your server, and post the output?

`locale -a`

**Comment by dabenzel** [comment]
Hi JC5,
output was the following:
´
C
C.UTF-8
de_AT.utf8
de_BE.utf8
de_CH.utf8
de_DE.utf8
de_LI.utf8
de_LU.utf8
POSIX
´

**Comment by JC5** [comment]
Alright so your server supports de_DE.utf8. That's important. Could you verify that the page is actually sent to you in utf8?

Open the file [resources/lang/de_DE/config.php](https://github.com/firefly-iii/firefly-iii/blob/master/resources/lang/de_DE/config.php#L13) and change line 13 to this:

`'locale'          => 'de, Deutsch, de_DE.utf8',`

**Comment by dabenzel** [comment]
After changing this line it worked! Can you tell me where the problem was?

**Comment by JC5** [comment]
I think it _was_ in the translations, but not as straight-forward as the word "März". I believe the "de_DE" instruction that you removed forced your installation to use the "de_DE.utf8" instruction. It was the second match, now it's the first.

Since everything else is also utf8, it looks good.

I'll update the translation. Next release the problem should be gone!

**Comment by Faisal-Zulfiqar510** [comment]
This may help you
https://github.com/neitanod/forceutf8

**Comment by JC5** [comment]
@laufhannes, what exactly is the problem? Are translated strings badly encoded, or are the dates badly encoded?

**Comment by JC5** [comment]
Also please open a new issue for this. I won't further reply to this one.
