### ISSUE TITLE
Data importer (duplicate transations and convert to utf-8)

### ISSUE THREAD

**Issue by Snyaify** [firefly-iii/firefly-iii#5367]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I create a configuration file to import from CSV, I remove the option "Convert to UTF-8", as well as "Do not import duplicate strings when importing", while Data-importer still tries to convert the file to UTF-8 (it is unclear why, the option is disabled) and does not allow me to import a transactional transaction, because it believes that there is a duplicate of this transaction, although there is no duplicate. You can see the video below:
[Video](https://trashcan.be4free.ru/cePA6/RoLUjOTi59.mp4)

### Expected behaviour

There is no need to convert the file to UTF-8 and also check transactions for duplicates because the corresponding options are disabled in the configuration file

### Debug information

the re is nothin to post, all info in video above

**Comment by JC5** [comment]
I can't watch the video from here. I will check the settings to see if and when the conversion kicks in.

Do you have a configuration file and some example CSV lines you can share?

**Comment by Snyaify** [comment]
> I can't watch the video from here. I will check the settings to see if and when the conversion kicks in.
> 
> Do you have a configuration file and some example CSV lines you can share?

Sure, here you go
[csv](https://trashcan.be4free.ru/cePA6/xAXuyoPa38.zip)

**Comment by JC5** [comment]
Can you attach them separately to the GitHub post please? Thanks.

**Comment by Snyaify** [comment]
> > I can't watch the video from here. I will check the settings to see if and when the conversion kicks in.
> > Do you have a configuration file and some example CSV lines you can share?
> 
> Sure, here you go [csv](https://trashcan.be4free.ru/cePA6/xAXuyoPa38.zip)

[Data importer.zip](https://github.com/firefly-iii/firefly-iii/files/7660912/Data.importer.zip)
[Tinkof.zip](https://github.com/firefly-iii/firefly-iii/files/7660913/Tinkof.zip)

**Comment by JC5** [comment]
Thanks! Both issues will be resolved in the next release of the data importer, version 0.3.0.
