### ISSUE TITLE
[Layout v2] Missing date range selector on Accounts page

### ISSUE THREAD

**Issue by Syphdias** [firefly-iii/firefly-iii#5372]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

As mentioned in https://github.com/firefly-iii/firefly-iii/discussions/5370, in Layout v2 the option to change the date range is missing for the Accounts page:
![image](https://user-images.githubusercontent.com/16988672/145209391-cc2c3335-073b-481b-9857-991fcb76ea14.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/16988672/145209485-56348eac-922c-4507-8767-dd97f162b5fd.png)

### Debug information

Debug information generated at 2021-12-08 13:37:32 Europe/Berlin for Firefly III version **5.6.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.5 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | fd915216-470f-46b1-8459-a68fb47d6e4a |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | de_DE |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2014-09-14 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 |

### Steps to reproduce

1. Use Layout v2 (duh)
2. Go to "Accounts" > "Asset accounts"
3. Click on the name of an asset account
4. Click on the Dragon in the top right-hand corner

**Comment by JC5** [comment]
This page will not get the selector but instead some buttons at the bottom. I expect most pages will lose the date range thing except the index and some overview pages, like the budgets, accounts and bills.

**Comment by Syphdias** [comment]
Why at the bottom? Seems a bit inaccessible to me

**Comment by JC5** [comment]
Idk I make this up as I go along 😁  I'll find a nice spot to make sure the account overview works!

**Comment by Syphdias** [comment]
I am wondering what the use-case for this page is if you cannot filter it in any way. I mean you could make the column filter I guess. :thinking:
