### ISSUE TITLE
Notes for budgets

### ISSUE THREAD

**Issue by Stealth0059** [firefly-iii/firefly-iii#5373]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I am just starting with Firefly III version 5.6.5. While experimenting with budget I realised that an optional field for notes would be nice so you can describe more what is included in this budget. 

### Solution

Please add a optional field for notes in the "Create budget" and "Edit budget" screen like it was already requested and implemented for piggy banks here https://github.com/firefly-iii/firefly-iii/issues/350.

**Comment by JC5** [comment]
Sure thing, I'll put it on the list!

**Comment by JC5** [comment]
This is possible in the next major release, but it's API only. They will become visible and editable in the new layout.
