### ISSUE TITLE
Layout v2 issues

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#5377]
The v2 layout is very much in **alpha**. Please don't use it or consider it complete in any way.

If you feel an issue needs my attention, please reply to this ticket.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5375

**Comment by Syphdias** [comment]
> If you feel an issue needs my attention, please reply to this ticket.

You obviously know that some sites did not get any treatment yet (e.g. search), or that the bulk actions are not there yet.
What kind of feedback are you looking for? Feedback on usability? Feedback on looks? Issues for missing features or sited? Issues on bugs in the functionality?

I'll rephrase: What can we do as users to help you?

**Comment by JC5** [comment]
Yes, all of it. Documenting what issues I know about and don't know about would take as much time as building the layout. I know about pages not being finished, and I know about missing features.

Anything else, just drop it in this ticket so it doesn't take up the entire list of issues. But it will be a work-in-progress for some time.

**Comment by Syphdias** [comment]
I totally understand that this takes time. I checkout v2 every once in a while until I hit a blocker – this time it was pages not loading and bulk actions.

**Comment by JC5** [comment]
5.6.6: the source account field keeps stealing focus making typing impossible

**Comment by death2cupbots** [comment]
> * 5.6.6: the source account field keeps stealing focus making typing impossible

But you _can_ paste text in as a workaround.

**Comment by death2cupbots** [comment]
(5.6.6) Pressing TAB in the amount field in a split transaction (split 2 or later) brings you to the tags field instead of the currency dropdown. This skips over the currency dropdown, foreign amount, budget, bill, and category boxes.

**Comment by gthbusrr** [comment]
- 5.6.8 - Create Transaction Page
  - Pressing TAB in the `category` field should move to `tags` field, it now moves to who knows where 😂 
  - Impossible to create transaction link on split transaction except the first one
  - Clicking the linked transaction will lead to `404`. (Wrong URL, should be `/transactions/show/xxx`, `/transaction/show/xxx` used instead.)

**Comment by death2cupbots** [comment]
> * Pressing TAB in the `category` field should move to `tags` field, it now moves to who knows where 😂

Just keep pressing TAB, you'll get there eventually!

**Comment by Skaronator** [comment]
5.6.8: The navbar active item doesn't work for transfers but works for withdrawal and deposit.

withdrawal:
![image](https://user-images.githubusercontent.com/2886913/147411970-c3e3b977-5610-48b7-9069-3dd4a9e65917.png)

deposit:
![image](https://user-images.githubusercontent.com/2886913/147411974-05c32784-8b07-445e-a8b5-3aa9ed523e74.png)

transfers:
![image](https://user-images.githubusercontent.com/2886913/147411979-7bb2e935-2372-49a0-9568-9774b1e69037.png)

**Comment by niklas2810** [comment]
Something happened with the `amount` field on the create transaction page. I used to be able to input amounts separated by comma for euros/cents, now this isn't possible anymore. On the transaction details page, the value is still separated by a comma.

Create transaction (when I press comma, nothing happens):
![image](https://user-images.githubusercontent.com/30748216/147665000-50d607e9-8db8-4440-8e49-1f6a3ac8def5.png)


Transaction details:
![image](https://user-images.githubusercontent.com/30748216/147664950-761edee5-ba05-401e-af88-1432645f1484.png)

Maybe you made some changes to the input validation? It's not a huge deal for me, but it's annoying when trying to enter cent values. Especially confusing is that the details page still shows the amount separated by a comma.

**Comment by JC5** [comment]
The input field takes after your browser settings, I can't change that unfortunately.

**Comment by JC5** [comment]
Closed for v3. No worries, all tickets are in my bookmarks.
