### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by SignumPL** [firefly-iii/firefly-iii#538]
While executing command 
`composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist`
the following error is thrown:

`Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan firefly:github-move
PHP Fatal error:  Uncaught Error: Call to undefined function bcscale() in /var/www/firefly-iii/bootstrap/app.php:26
Stack trace:
#0 /var/www/firefly-iii/artisan(18): require_once()
#1 {main}
  thrown in /var/www/firefly-iii/bootstrap/app.php on line 26
Script php artisan firefly:github-move handling the post-install-cmd event returned with an error
  [RuntimeException]
  Error Output: PHP Fatal error:  Uncaught Error: Call to undefined function bcscale() in /var/www/firefly-iii/bootstrap/app.php:26
  Stack trace:
  #0 /var/www/firefly-iii/artisan(18): require_once()
  #1 {main}
    thrown in /var/www/firefly-iii/bootstrap/app.php on line 26
`

**Comment by JC5** [comment]
[You haven’t enabled or installed the BCMath module](https://firefly-iii.github.io/installation-guide-faq/)
