### ISSUE TITLE
5.5.6 Doesn't Show Imported Txs (maybe some sort of caching?)

### ISSUE THREAD

**Issue by alexklibisz** [firefly-iii/firefly-iii#5384]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I imported some txs via csv-importer 2.6.1. The individual txs are accessible via links from th csv-importer, but not from the account page for the account where they were imported.

### Expected behaviour

The newly-imported txs should appear on the corresponding account page.

### Debug information

Debug information generated at 2021-12-11 11:31:38 America/New_York for Firefly III version **5.6.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.6 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | e1cc6dba-0dbc-4d29-b747-a26a86557361 |
| Using docker? | true |
| Layout | v2 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-12-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 3 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 |

### Steps to reproduce

Here are the txs after completing the import

![image](https://user-images.githubusercontent.com/8015228/145684080-e27450d3-51fc-455f-bd15-1205b964493b.png)

I can click on one of the txs and it clearly exists

![image](https://user-images.githubusercontent.com/8015228/145684184-ce05f0f5-1e47-4b6d-b3dc-3d9f913f56a2.png)

But when I go to the account landing page, it's not there. The tx was on Dec. 9, whereas the latest shown tx is on Dec. 4.

![image](https://user-images.githubusercontent.com/8015228/145684162-0f8d3780-2bcc-4b06-89dc-5cb39b41b760.png)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5377

Caching in v2 is pretty aggressive. Use the little reload buttons when you see them.

**Comment by alexklibisz** [comment]
Where are the reload buttons?
