### ISSUE TITLE
Wrong reconciliation preview in multi-currency situation

### ISSUE THREAD

**Issue by mgorfer** [firefly-iii/firefly-iii#5388]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After creating a transfer between accounts with different currencies, the reconciliation preview of the receiving account shows a wrong number. The value shown in the `Overview of reconciliation` (after pressing the `Store reconciliation` button) shows the `Difference` correctly as 0.00.

### Expected behaviour

The reconciliation preview should display the same (correct) value, which is shown in the `Overview of reconciliation` view.

### Debug information

Debug information generated at 2021-12-12 14:59:33 Europe/Amsterdam for Firefly III version **5.6.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.6 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 830c5399-828b-4491-860b-ee129563f17b |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-12-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2021-11-15 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 |

### Steps to reproduce

1. In the demo site, create a transfer from `Checking Account (€)` to `Checking account in GBP (£)` with the amount of €1 and foreign currency £2 (this is not the real exchange rate).
2. Reconcile the `Checking account in GBP` with a balance of £2.00 and select the transfer. The preview in the top right corner shows -£1.00.
3. Press the `Store reconciliation` button to open the `Overview of reconciliation`, where the `Difference` is shown as £0.00.
4. Opening the reconciliation again still shows -£1.00, even though the balance is correct.

**Comment by JC5** [comment]
Thanks for letting me know! I'm working on a new layout where this issue should be gone. Until then, I'm afraid you'll have to learn to live with this one.
