### ISSUE TITLE
Sidebar icons not showing when collapsed

### ISSUE THREAD

**Issue by mcardielo** [firefly-iii/firefly-iii#5393]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When you collapse the sidebar the icons of the sections are not showed

Example not collapsed
![imagen](https://user-images.githubusercontent.com/842262/145854031-a9cc3eb8-d85b-425f-872c-beab89ed2612.png)

Example collapsed
![imagen](https://user-images.githubusercontent.com/842262/145854100-e4e1be0a-cb36-4752-91c3-919a1c12d910.png)

### Expected behaviour

To show the icons or thumbnails of the sections when the sidebar is collapsed

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.6 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | cf489f7d-cd97-4449-8598-3c699a684d9d |
| Using docker? | true |
| Layout | v1 |
| System TZ | America/Mexico_City |
| Browser TZ | America/Mexico_City |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | en_US |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

### Steps to reproduce

1. Clic on the burger menu icon
2. See the collapsed sidebar

**Comment by JC5** [comment]
Thanks for letting me know. I'm working on a new layout where this issue will no longer be present.
