### ISSUE TITLE
Invalid source account error during import

### ISSUE THREAD

**Issue by 0099FF** [firefly-iii/firefly-iii#5397]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When importing transactions into a Liability account using the [data importer](https://github.com/firefly-iii/data-importer), all transactions throw the following errors:
```
(2)transactions.0.source_id: Could not find a valid source account when searching for ID "0" or name "". (original value: "(not found)")
(2)transactions.0.source_name: Could not find a valid source account when searching for ID "0" or name "". (original value: "(not found)")
```

### Expected behaviour

The transactions are imported successfully and appear under the liability.

### Debug information

Debug information generated at 2021-12-16 for Firefly III version **5.6.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.6 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 07212570-31f6-4ce4-913e-6ae19e5507c3 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Australia/Sydney|
| Browser TZ | Australia/Sydney|
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2016-01-01 00:00:00 |
| Session end | 2021-12-16 00:00:00 |
| Session first | 2016-01-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0 |

### Steps to reproduce

1. Create a new loan liability within Firefly III.
![image](https://user-images.githubusercontent.com/20736095/146204546-1af40750-0d03-4ddd-9d20-39dd62d98649.png)

2. Open the Firefly III Data Import Tool (`v0.3.0`) or CSV Import Tool (`v2.6.1`) and begin a new import using [import_files.zip](https://github.com/firefly-iii/firefly-iii/files/7720271/import_files.zip). Ensure the `Default import account` is set to the liability account created in step 1.
3. Continue the import until you reach the import routine section. Start the import process and observe as each line generates an error.

### Additional info

As an aside I've been using the CSV Import Tool for a couple of years now but tested out the new(?) Data Import Tool for this ticket. Will the CSV Import Tool see continued support in the future or should I (and others) migrate over to the Data Import Tool?

**Comment by JC5** [comment]
Hi! Thanks for letting me know, and thank you for adding a test case. I will pick it up! Could you add the files separately (not as a zip)? Thanks!

The CSV importer will be decommissioned so a migration will be necessary in the future.

**Comment by 0099FF** [comment]
GitHub surprisingly doesn't support uploading `.json` files which is why I used the zip file 😅. I've uploaded them separately here (the `.json` extension has been swapped to `.txt` for the import config file).

[import_data.csv](https://github.com/firefly-iii/firefly-iii/files/7720554/import_data.csv)
[import_config.txt](https://github.com/firefly-iii/firefly-iii/files/7720557/import_config.txt)

**Comment by JC5** [comment]
I submitted a fix to the `develop` branch / `develop` Docker image.

Could you verify if it worked? It works for me ™️ .

**Comment by 0099FF** [comment]
Just tested your changes and they are working for me too! Thanks for the super fast turn around 😃

**Comment by JC5** [comment]
Cool! Will be part of 0.4.0!

**Comment by MacPaille** [comment]
@JC5 Now I'm starting my import from Nordigen I have the same issue but only on the source_name that is a transfer from one of my other accounts to the one I'm importing the transaction:

Line #1:
(2)transactions.0.destination_id: Could not find a valid destination account when searching for ID "1544" or name "". (original value: "1544")
(2)transactions.0.destination_name: Could not find a valid destination account when searching for ID "1544" or name "". (original value: "(not found)")

I checked and I also have the mapping done correctly before in the logs:
production.DEBUG: Updated mapping of "MY_ACCOUNT_NAME" to ID "1544"
(for sure I have renamed my account to MY_ACCOUNT_NAME for this copy/paste :) )

Regular deposit/withdrawals are fine but all the transfer between accounts are failing...

**Comment by JC5** [comment]
Send me some logs over email please :+1:

**Comment by MacPaille** [comment]
Logs of the data-importer or my FF instance? Or both?

Also is there a way to make the container logs persistent on a mapped volume? I can only copy/paste the Synology logs from the interface and it's really not easy...

**Comment by JC5** [comment]
You should be able to map /var/www/storage/logs, that should do it.

I'm curious about the data importer, initially. My first guess is, it's trying to create a "deposit" with two asset accounts which will fail. The latest build is 42 (see the startup logs), try that one (develop image).

**Comment by MacPaille** [comment]
Mapping /var/www/storage/logs does not help, nothing in that folder. Maybe I also have to set an env variable?

Anyway was using build 39 from develop branch I updated to latest one, no difference. I copy/pasted my 2566 lines of logs I'll clean them and will send by email.

**Comment by MacPaille** [comment]
@JC5  I have send the logs by email. Do you want me to open a new issue for this tracking?

**Comment by JC5** [comment]
The correct directory is `/var/www/html/storage/logs` (see the added /html). If you map that one, the logs should appear. My apologies for the confusion.

I received your logs but it looks like Synology doesn't pass everything, so it's kind of inconclusive. I hope that mounting the directory will help!

**Comment by MacPaille** [comment]
Indeed that works better with the correct path haha. I have sent the logs again, not sure you see a difference. Is there another flag to set to have even more lines?

**Comment by JC5** [comment]
I just build nr 43, which has some lines added to it. I hope that will narrow it down!

**Comment by MacPaille** [comment]
OK I made it work with build 42!!! I did change my account details to register the IBAN number without the spaces. On the account list FF does show it with spaces as usual for IBAN accounts, but I had it set also with spaces inside the accounts themselves. Just by removing them it seems it was able to identify my account.

The idea came while looking into the logs where it was saying it found multiple IBAN numbers and all of them were in a all attached string without spaces.

Maybe would be good to allow people to enter IBAN only without spaces in their account details?

**Comment by JC5** [comment]
Good one, I'll check it out. I can fix this from the importer by removing all spaces. Thanks for the pointer!

**Comment by MacPaille** [comment]
For sure I would say even better to also cure it in FF itself. If the tool needs to compare IBAN numbers without spaces better to make sure they are in the correct format.

I'll continue my imports and revert back if anything new comes from it :)
