### ISSUE TITLE
Transfer finder

### ISSUE THREAD

**Issue by mpfl** [firefly-iii/firefly-iii#5401]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Unfortunately it seems that transaction data imported from Spectre for my Australian bank accounts does not include the metadata required for Firefly III to automatically match withdrawals with deposits to make transfer.

My only solution at the moment is to manually convert half of the transactions to transfers, and manually delete the other half.

### Solution

It would be great if Firefly could have some sort of "transfer finder" that matches withdrawals and deposits based on:

- Value
- Date (optional and within a definable range for transfers that don't work immediately)
- Description (optional because they don't always match))

If a match is found, the pair can be quickly combined into a single transfer transaction with a single click

### What are alternatives?

Of course the ideal solution is for Spectre to be able to retrieve better transaction metadata, but I imagine that would require my bank to change its practices and that probably won't happen in my lifetime.

### Additional context

Happy to answer any questions.

**Comment by JC5** [comment]
This is pretty out of scope for me, but a solution may be present already. The rules engine under `/rules` has no trouble looking for transactions based on given input. 

If your deposits / withdrawals have certain properties they match on, you can delete them or update them.

You won't be able to compare transactions with eachother, that's something I can't help you with.
