### ISSUE TITLE
[data-import] Importing from a date range is not working correctly

### ISSUE THREAD

**Issue by p-rintz** [firefly-iii/firefly-iii#5402]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The 'Import a specific range' import option is broken as it will always *only* import the start date.

Setting this:

![firefly_issue](https://user-images.githubusercontent.com/13933258/146398746-6d14b914-c7cc-4b5e-891f-b285efadf715.png)

Will lead to this debug log: (and imports only from the start date)

```
[2021-12-16 16:21:10] local.DEBUG: isReadyForNordigenStep("configuration")  
[2021-12-16 16:21:10] local.DEBUG: Now running App\Http\Controllers\Import\ConfigurationController::postIndex  
[2021-12-16 16:21:10] local.DEBUG: Now in updateDateRange()  
[2021-12-16 16:21:10] local.DEBUG: Range is "range", both will be created from a string.  
[2021-12-16 16:21:10] local.DEBUG: dateNotBefore is now "2021-11-27", dateNotAfter is "2021-11-27"  
```

### Expected behaviour

That is uses the start and end date to set the import date range.

### Debug information

Debug information generated at 2021-12-16 16:22:54 Europe/Berlin for Firefly III Data Importer version **0.3.0**.

| Scope | Version |
| --- | --- |
| FIDI | 0.3.0 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | false |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.7113.93 Safari/537.36 |

### Steps to reproduce

1. Try to import with any date range
2. Import only transactions from the start date, nothing in the range.

**Comment by JC5** [comment]
Nice find, should fix another issue I saw as well.
