### ISSUE TITLE
[data-importer] ING Germany description quirk

### ISSUE THREAD

**Issue by p-rintz** [firefly-iii/firefly-iii#5403]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Im using Nordigen as the import for an ING Germany Account.

Sadly the transactions look like this:

`[2021-12-16 16:39:20] local.DEBUG: Submitting to Firefly III: {"apply_rules":true,"error_if_duplicate_hash":true,"transactions":[{"type":"withdrawal","date":"2021-11-30","amount":"999.0000000000000000","description":"mandatereference:,creditorid:,remittanceinformation:Wohngeld - Philipp Rintz","order":0,"currency_code":"EUR","tags":[],"category_name":null,"category_id":null,"external_id":"000007120123123123","internal_reference":"","source_id":11,"destination_name":"Removed for Ticket","destination_iban":"DE123123123123123123123123"}]}`

Which means that "mandatereference:,creditorid:,remittanceinformation:" as a String is prepended to every single transaction that gets imported.

Im not really sure if you can classify this as a bug, as its not really any bug from your side, but its hugely annoying when this gets imported. Feel free to close this if there is nothing you can/want to do.

I thought of creating a rule to remove this string from any transaction that appears, but this doesnt seem to be possible currently. So I guess unless you have another Idea, this might also be a feature request for creating that kind of rule.

### Expected behaviour

That *mandatereference:,creditorid:,remittanceinformation:* isnt being prepended to every transaction imported... ☹️ 

### Debug information

Debug information generated at 2021-12-16 16:46:30 Europe/Berlin for Firefly III Data Importer version **0.3.0**.

| Scope | Version |
| --- | --- |
| FIDI | 0.3.0 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | false |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.7113.93 Safari/537.36 |

**Comment by JC5** [comment]
Could you find in your logs an entry for "Nordigen transaction from array"?

Please send me the original over email: james@firefly-iii.org

**Comment by p-rintz** [comment]
Ive sent you the information via email.

**Comment by JC5** [comment]
Thanks. Unfortunately the data is delivered to me "broken". I sent you a follow up question and will raise an issue with Nordigen.

**Comment by JC5** [comment]
It seems "what you see is what you get", I depend on Nordigen on this and can't fix this for you. Sorry :(

**Comment by p-rintz** [comment]
Is there any way to fix this via rules? (or any other way for me to change the descriptions automatically?)

From what I could see, I cant use variables or the like in rules, so I cant keep the original message, while removing part of it.

**Comment by JC5** [comment]
I haven't heard back yet. You could contact them through your own profile page at Nordigen, if you want to expedite matters.

The rule engine is limited in this regard. Depending on your own tech level, you could use the API to update the transactions after they've been created.

**Comment by p-rintz** [comment]
Guess ill have to look into that if Nordigen doesnt fix it. Thank you. You can close the issue if you'd like.

**Comment by JC5** [comment]
Will do, thanks for reporting.
