### ISSUE TITLE
Privacy mode

### ISSUE THREAD

**Issue by yohancourbe** [firefly-iii/firefly-iii#5404]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- Add a option to enable a "privacy mode" that would blur all the sensitive data of a page (typically the amounts)
- Allows to showcase Firefly to friends and family without disclosing details of your accounts
- Allows to work on public area where people could do shoulder surfing

### Solution

Toggle a css class such as this one

```
.textshadow .blurry-text {
   text-shadow: 0 0 32px white;
   color: transparent;
}
```

**Comment by JC5** [comment]
I'm not really interested in adding a privacy mode. For a demo you can use the [demo site](https://demo.firefly-iii.org/), shoulder surfing isn't really something I can do something about, I would have to blur basically everything.
