### ISSUE TITLE
Date ranges don't work properly for rules on bills

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#5405]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Rules have been changed to be more performant and use sql queries directly. Also, date-based triggers were added in 5.2.6. However, the date range triggers don't seem to work as documented.
E.g. I have 2 bills, one for me, one for my wife, both are triggered at different times of the year, so I create 2 bills with their own rule and want to use date-based triggers. I use xxxx-02-01 with "date after"and xxxx-03-31 with "date before". The documentation indicates this should trigger for every year (see https://docs.firefly-iii.org/firefly-iii/pages-and-features/rules/#semi-specific-dates), but that doesn't happen. It will trigger when transactions are added, but it doesn't work properly when you re-run rules on the detail page of a bill.
In the logs I see the year is always replaced by the year of the current day:

```
today at 10:28:52 PM[2021-12-16 22:28:52] local.DEBUG: Now in updateCollector("date_after", "xxxx-02-01")  
today at 10:28:52 PM[2021-12-16 22:28:52] local.DEBUG: "date_after" is not an alias.  
today at 10:28:52 PM[2021-12-16 22:28:52] local.DEBUG: Value for date_after is "xxxx-02-01"  
today at 10:28:52 PM[2021-12-16 22:28:52] local.DEBUG: "xxxx-02-01" is not a day range.  
today at 10:28:52 PM[2021-12-16 22:28:52] local.DEBUG: "xxxx-02-01" is not a month range.  
today at 10:28:52 PM[2021-12-16 22:28:52] local.DEBUG: "xxxx-02-01" is not a year range.  
today at 10:28:52 PM[2021-12-16 22:28:52] local.DEBUG: "xxxx-02-01" is a month/day range.  
today at 10:28:52 PM[2021-12-16 22:28:52] local.DEBUG: parseMonthDayRange: Parsed "xxxx-02-01" into "2021-02-01"  
today at 10:28:52 PM[2021-12-16 22:28:52] local.DEBUG: Set "date_after" using collector with value "xxxx-02-01" (2021-02-01 - 2021-02-01)
```

### Expected behaviour

Transactions from all years are still selected when running the rules again, on all transactions, on a bill detail page. Even when using  date based transactions.

### Debug information

Debug information generated at 2021-12-16 22:53:36 Europe/Brussels for Firefly III version **5.6.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.6 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 91f8b90e-4a5b-4e53-b590-1366bd11a760 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Brussels |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-12-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2019-12-25 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 |

### Additional info

Is there a way to improve this? Maybe by using YEAR, MONTH, DAY in the query as parts of the date and getting to a query like: WHERE MONTH(`date`) BETWEEN '02' AND '03' AND DAY('date') BETWEEN '01' AND '31'? I don't know how feasible that is with illuminate though.

**Comment by JC5** [comment]
I see what you mean, I'll pick it up!

> Is there a way to improve this? Maybe by using YEAR, MONTH, DAY in the query as parts of the date and getting to a query like: WHERE MONTH(date) BETWEEN '02' AND '03' AND DAY('date') BETWEEN '01' AND '31'? I don't know how feasible that is with illuminate though.

What would be the improvement?

**Comment by JC5** [comment]
> Is there a way to improve this? Maybe by using YEAR, MONTH, DAY in the query as parts of the date and getting to a query like: WHERE MONTH(date) BETWEEN '02' AND '03' AND DAY('date') BETWEEN '01' AND '31'? I don't know how feasible that is with illuminate though.

That's feasible, but it's a pretty complicated rewrite.

**Comment by JC5** [comment]
Actually that may not be *that* hard. Are you able to do some debugging later this weekend?

**Comment by daften** [comment]
Yes, should be fine, I'm at home most of the time, just gone sunday afternoon and saturday evening.

**Comment by JC5** [comment]
I pushed some new code to the `develop` branch as well as the `develop` docker image. I would be much obliged.

**Comment by daften** [comment]
@JC5 Just tested it and it seems to work fine. Ran it against the "latest" docker container and against the "develop" container and in the latest one the date ranges work as I expect, for my cases at least.

Thanks for the quick fix! I'll leave it up to you if this is closable or if you'd like additional verification on this.

**Comment by JC5** [comment]
No problem! I've marked it as fixed, I hope to release a new version over the weekend.

**Comment by JC5** [comment]
5.6.7 is out :+1:
