### ISSUE TITLE
Data Import Upload Corrupts asset accounts

### ISSUE THREAD

**Issue by acatenac** [firefly-iii/firefly-iii#5406]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

I am still doing preliminary testing so it may have been my actions that caused the error ...  I am using the Docker Data Importer which worked immediately where I could not get the server based Data Importer to work. It appears that the asset accounts table or cache was corrupted.
After importing a 2 record file  I got the the error below  .. I will be doing some additional testing ... I can roll back a VM snapshot and try some other configurations.
Any suggestions welcomed
Thank You

 Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/22/b0/22b0281db1e3353d4e060ca082878220cb34e74e): Failed to open stream: No such file or directory

More information
Please collect more information in the storage/logs directory where you will find log files. If you're running Docker, use docker logs -f [container]. You can read more about collecting error information in the FAQ.

### Expected behaviour

Expected records to be loaded to asset account table

### Debug information

 How do you access the debugging info

### Steps to reproduce

Use Docker data importer
Import 2 credit transactions

Date,Description,Debit,Credit
2021-12-1,"Online Banking transfer to confirmation# 2536499670",,"1700.22",
2021-12-1,"Citi Cards Bill Payment",,"1500.63",

### Additional info

.

**Comment by JC5** [comment]
It's just a cache error. Browse to `/flush` to clear it.
