### ISSUE TITLE
SQLSTATE[HY0000] [2002] php_network_getaddresses: getaddrinfo failed

### ISSUE THREAD

**Issue by runlevel-4** [firefly-iii/firefly-iii#5408]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

This error occurs during the composer process.  I've updated my install script to include php8.0 and firefly v5.6.5 in the composer command per the install documentation.

![php_network_address_err](https://user-images.githubusercontent.com/90661907/146791323-8d241015-34ba-46d3-91fd-af623c121839.png)

### Expected behaviour

The /public directory to preset the login page (this used to work with my old install script on php7 and firefly v5.4)

### Debug information

![php_network_address_err](https://user-images.githubusercontent.com/90661907/146791540-5a23b3a0-6fa6-4d47-a244-6a7ec3f7a86c.png)

### Steps to reproduce

1. Run composer command:
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 5.6.5

**Comment by JC5** [comment]
I'm not sure if this is a bug, to be honest. Nothing really changed in the code.

What's the current version of the script? Is there a link I can see?

**Comment by runlevel-4** [comment]
All good, I found the issue...really stupid lol.  For some reason the edited .env file that I use was not in my github directory.  I re-created it, got passed the composer config step, and now it works :)

**Comment by runlevel-4** [comment]
All good, I found the issue...really stupid lol.  For some reason the edited .env file that I use was not in my github directory.  I re-created it, got passed the composer config step, and now it works :)
