### ISSUE TITLE
Understanding difference between categories, budgets, and tags

### ISSUE THREAD

**Issue by craftyguy** [firefly-iii/firefly-iii#541]
I'm trying out firefly-iii, and I'm having some difficulty understanding what the differences are between categories, budgets, and tags.

To help demonstrate this, take [this transaction on your demo site for a 'grocery' item](https://firefly-iii.nder.be/transactions/show/494). It has description set to "Groceries", category set to "Daily Groceries" and Budget set to "Groceries". I understand that budgets have ceilings, and withdrawals marked for a particular budget will add to the budget's total spent. Categories and tags seem redundant in that case, and seem like they are, themselves, serving identical purposes.

Do you have any documentation that explains the differences? If not, if you explain it here then I would be more than happy to submit a pull request or submit a more formal description that you could put on your site!

**Comment by JC5** [comment]
Ah, a difficult question!

The [website](https://firefly-iii.github.io/) has some information on [budgets](https://firefly-iii.github.io/budgets/), [categories](https://firefly-iii.github.io/categories/) and [tags](https://firefly-iii.github.io/tags/), and the difference between [categories and tags](https://firefly-iii.github.io/categories-and-budgets/). The most important difference is that income cannot have a budget.

The examples on the demo site aren't the best. Budget "groceries" and category "daily groceries" are quite the same. Personally though, I also use the category "personal care" for stuff like shampoo and deodorant, which is also stored under budget "groceries". In that sense, the category is a kind of "sub-budget".

You could also choose to use the category for another angle all together, storing transactions in categories "normal expenses" and "exceptional expenses", showcasing the difference between what you usually spend on life and what isn't.

Between you and me, tags are also redundant. Although they have some advanced features which tags shouldn't really have, they too can be used to indicate a "category" of some sorts. But you know, tags are cool and one of Firefly's least used but most asked for feature is tags. So it goes.

So yes, in many cases, budgets, categories and tags are "redundant", and are used to indicate the same thing: the 'category' of the expense. Having said that, I find it useful to split work-related expenses (budget: work) further using categories (car, public traffic, lunch, etc). Whenever possible I tag stuff I can get reimbursed which also gives a nice overview to send to my boss.

Does that answer your question?

**Comment by skibbipl** [comment]
After month of using Firefly I've worked out following workflow. I use tags to mark transactions related to global expense category - like entertainment, transportation or health. Categories are more detailed expense categories - like movies, books, games (all goes to entertainment tag). I use budgets to keep my regular expenses in reasonable boundaries - like I'll not spent more than 100$ for books per month.

**Comment by craftyguy** [comment]
@JC5 @skibbipl 

Thank you both very much for the explanation, this helps a lot! I'm just starting out, so it won't be too painful to change how I use these tools (tags, categories) to track my spending.
