### ISSUE TITLE
Error 500 on Nordigen import in importer 0.4.0

### ISSUE THREAD

**Issue by FredericMa** [firefly-iii/firefly-iii#5416]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm using the self-hosted data importer.
In version 0.4.0 I get the following error when importing via Nordigen, after selecting my country and bank and clicking Submit:
```
[2021-12-22 09:43:09] local.ERROR: Access level to App\Http\Request\Request::date() must be public (as in class Illuminate\Http\Request) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Access level to App\\Http\\Request\\Request::date() must be public (as in class Illuminate\\Http\\Request) at /var/www/data-importer/app/Http/Request/Request.php:179)
[stacktrace]
#0 {main}
"}
```

In the browser I get a 500 on `http://instance.url/import/selection`:
![image](https://user-images.githubusercontent.com/7840263/147063797-7b16bb80-f98c-492a-b259-b944834d4fcc.png)

### Expected behaviour

I expected getting forwarded to the Nordigen authentication page.

### Debug information

Debug information generated at 2021-12-22 09:53:13 Europe/Amsterdam for Firefly III version **5.6.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.8 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | ffa93b84-c45f-4537-8a35-b12497df989d |
| Using docker? | false |
| Layout | v1 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, sqlite |
| Current driver | sqlite |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-12-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2021-11-19 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 |

### Steps to reproduce

1. Click `Import from Nordigen`.
2. Click Upload.
3. Select country and bank (Belgium and AXA Bank) in my case.
4. Click submit.
5. Error 500 appears.

**Comment by JC5** [comment]
Thanks for letting me know, I'll check it out. I may release 0.4.1 later today.

**Comment by JC5** [comment]
Final question: the importer also has a `debug` page. Could you share that one as well?

**Comment by FredericMa** [comment]
Sure! I didn't know that. Here it is:

Debug information generated at 2021-12-22 10:29:29 Europe/Amsterdam for Firefly III Data Importer version **0.4.0**.

| Scope | Version |
| --- | --- |
| FIDI | 0.4.0 |
| Build | (unknown) |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | false |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 |

**Comment by JC5** [comment]
I have pushed a fix to the `develop` branch. Is that something you could test for me?

**Comment by FredericMa** [comment]
I tested it and it works again.
Thanks for the quick fix!

I did have a few duplicate transactions imported but that probably because of this: `The importer will prefer 'bookDate' over 'valueDate'`? I'm using content based detection.
Is there an easy way to get them out again? Maybe editing the sqlite db directly?

**Comment by JC5** [comment]
Just delete them through Firefly III, and they will not be imported again.

**Comment by FredericMa** [comment]
Roger that, thanks!
