### ISSUE TITLE
Search filter for empty notes (maybe notes_are_empty or notes_are:"")

### ISSUE THREAD

**Issue by alexklibisz** [firefly-iii/firefly-iii#5421]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to have a search filter for transactions that have empty notes.

### Solution

This would let users find transactions that have no notes and add notes to them. For example, I would like to find all transactions with "Amazon" in the description and no notes, and then add a description with the order contents.

### What are alternatives?

I've tried to do this with `notes_are:""`, but it doesn't seem to work as I expected:

![image](https://user-images.githubusercontent.com/8015228/147300947-8cd48fc2-f5bf-4135-bd65-c18e07dafe66.png)

**Comment by JC5** [comment]
Use "no_notes:true"
