### ISSUE TITLE
Duplicate transaction created

### ISSUE THREAD

**Issue by Kage1** [firefly-iii/firefly-iii#5425]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I manually created a expense transaction. Overnight my transactions imported through Plaid importer. The imports occured, but instead of matching up to the existing transaction a dupe was created.

### Expected behaviour

The existing transaction is matched up with the imported one and not duplicated.

### Debug information

Debug information generated at 2021-12-24 15:04:41 America/Chicago for Firefly III version **5.6.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.8 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 501afd5f-da21-4030-b12c-bd041aaa2181 |
| Using docker? | true |
| Layout | v1 |
| System TZ | America/Chicago |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-12-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2020-09-30 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.113 Safari/537.36 |

### Steps to reproduce

1. Create a new manual expense transaction.
2. Let PLAID import the transaction as normal
3. Both now existing with the same name and amount. 

### Additional info

A debug output of both transactions is available, but would rather not post here in case of sensitive info.

**Comment by JC5** [comment]
I ran into this problem when I built the original CSV importer, and I decided not to try and match transactions on date, description, accounts and amount. I've seen several edge cases where I assumed a transaction was a duplicate, where users complained it wasn't. One example was a user buying two candy bars in the same minute, and the importer assumed it was a duplicate. Transferring money twice, correcting previous transactions, such things would quickly become a "duplicate".

Right now, the data importer has two duplication detection methods:

1. Use a known field like the "external_id" and match it. If matched, don't import.
2. Make Firefly III do it.

If Firefly III has to do duplicate detection, it'll simply [hash the entire submitted transaction](https://github.com/firefly-iii/firefly-iii/blob/main/app/Factory/TransactionJournalFactory.php#L302) and see if it has the hash already. That way, a duplicate is only detected if the transaction is *exactly* the same. This option is turned off when you're using the GUI, but the data importer enables it by default.

To make sure your plaid transaction is matched as a duplicate, make sure you submit the exact same thing as the plaid importer would have done. Amount, accounts, date, description, notes, external_id, everything.

In all other cases, Firefly III can't be sure and will err on the side of caution.
