### ISSUE TITLE
Deleting transaction from transaction list will redirect you back to edit screen of said transaction, resulting in 404

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#5426]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Deleting transaction from transaction list will redirect you back to edit screen of said transaction, resulting in 404 error

### Expected behaviour

Firefly should probably stay on list of transactions

### Debug information

Debug information generated at 2021-12-25 06:28:01 UTC for Firefly III version **5.6.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.6 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 1c789eff-ec96-4172-80d7-9ab04aabfda8 |
| Using docker? | true |
| Layout | v1 |
| System TZ |  |
| Browser TZ | Europe/Ljubljana |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-12-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2017-12-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0 |

### Steps to reproduce

1. Open list of transactions (for example "all transactions for account" page)
2. Click Actions button on any transaction
3. Select Delete
4. Confirm deletion

**Comment by JC5** [comment]
I can't replicate this.

**Comment by matejdro** [comment]
Huh, I also can't replicate this anymore. Will reopen if it happens again and I manage to gather more info.
