### ISSUE TITLE
HTTP 500 Error, unable to install.

### ISSUE THREAD

**Issue by alfiemellor** [firefly-iii/firefly-iii#543]
Keep getting HTTP Error 500. Tried 3-4 times now on Ubuntu Server 16.10 and now 16.04. From a fresh VM with on the install only open-ssh server installed and LAMP server (have done it without this and installed apache etc manually but same problem). This is everything I done (I'm fairly noob at Linux so I may be missing something obvious).
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install php7.0-bcmath
sudo apt-get install php7.0-mcrypt
sudo apt-get install php7.0-intl
sudo apt-get install php7.0-mbstring
sudo apt-get install unzip

mysql -u root -p
CREATE DATABASE firefly;
show databases;
create user firefly;
grant all on firefly.* to 'firefly'@'localhost' identified by 'SUPERSECRET';
exit

curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
cd /var/www/html/
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist
```
Here it complains about permissions says:
[ErrorException]
mkdir() : Permission denied
So I do:
`sudo chown -R $USER:$USER /var/www/html/`
Not sure if this is 'secure' but it works, now its installed. Now moving on:
```
cd firefly-iii/
php artisan key:generate
nano .env
```
Here I add the DB information, I'll add other stuff in here once I get it working. Next I do:
`php artisan migrate --seed --env=production`

It says Migration table created successfully. Now when I navigate to http://192.168.0.85/firefly-iii/public/
I just get a HTTP 500 Error. So yeah, I probably missed something obvious but there you go, Thanks.

**Comment by JC5** [comment]
There should be something in your logs that says why you are getting a 500 error. Check storage/logs.

**Comment by alfiemellor** [comment]
There wasnt anything in storage/logs. I did
`sudo a2enmod rewrite`
and edited the apache2 config file as in your installation guide to include
`AllowOverride All`
Then did a restart:
`sudo service apache2 restart`

Tried accessing again and get HTTP 500, I can browse to /firefly-iii/ and see the index fine but click on public folder and get the error. The vendor folder is there also.

**Comment by JC5** [comment]
Try the chown command but with www-data instead of $user

**Comment by alfiemellor** [comment]
Okay nice I can get to the login screen, registered an account and then got:
Whoops looks like something went wrong.
Looking at storage/logs shows nothing.

**Comment by alfiemellor** [comment]
Okay, got home and now its working. Not sure what changed to go from above but thank you. Seems to be great so far, appreciate the support and for developing this.

**Comment by JC5** [comment]
You're welcome!
