### ISSUE TITLE
[data-import] Hosted data import site appears to be down

### ISSUE THREAD

**Issue by awesomeaiden** [firefly-iii/firefly-iii#5438]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely you, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When attempting to access the publicly hosted data importer, the site fails to load.  Happens across multiple devices and multiple internet connections.

### Expected behaviour

The publicly hosted data importer site is accessible

### Debug information

No debug page available as site is down

### Steps to reproduce

1. Try to access https://data-importer.firefly-iii.org/
2. Website is not accessible ("This site can't be reached: DNS_PROBE_FINISHED_NXDOMAIN")

**Comment by JC5** [comment]
Thanks, I'll pick it up! I hope to get it up and running again before the new year.

**Comment by JC5** [comment]
https://data-importer.firefly-iii.org/
