### ISSUE TITLE
Calculate internal debt

### ISSUE THREAD

**Issue by Asteliks** [firefly-iii/firefly-iii#5439]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be great if we could have some kind of internal money splitting tool or something like that. For example: Alice buys toilet paper for the whole family and some candy with her own money. The tool would registers that the family ows Alice the cost of the toilet paper but not the candy.

I've seen some solutions in other programs but to be honest nothing is as good as Firefly and I would love to have this here making it the complete tool for home money management.

### Solution

Some solutions that I've found are:

- https://ihatemoney.org/
- https://github.com/nymanjens/facto

![image](https://user-images.githubusercontent.com/62251475/147499164-6be4b3a8-a2cd-4b1e-8e28-24015aae24d3.png)

**Comment by JC5** [comment]
Sorry no, that's not a feature that fits Firefly III.

**Comment by Asteliks** [comment]
:'(
