### ISSUE TITLE
Datepicker does not appear

### ISSUE THREAD

**Issue by welbert** [firefly-iii/firefly-iii#544]
After follow [Installation Guide](https://firefly-iii.github.io/installation-guide/).

If I select or click on any date field, the date selection does not appear (First picture). Except on reports (Second picture). It's a bug or i forgot to install something?

![without-datapicker](https://cloud.githubusercontent.com/assets/7155838/22394289/d3ec712e-e4fa-11e6-81f2-c8c4997e53d4.JPG)

![reports](https://cloud.githubusercontent.com/assets/7155838/22394315/c1bd9e28-e4fb-11e6-8b4a-4e5d87abfa8f.JPG)

**Comment by JC5** [comment]
Currently the date picker only appears on date fields in browsers that support the input type "date", which I believe are Opera and Chrome. The next release of firefly will include a date picker for all other browsers as well. Stay tuned tuned!

**Comment by welbert** [comment]
Truth, Chrome works, but on firefly demo site, Firefox has date picker
![demosite](https://cloud.githubusercontent.com/assets/7155838/22396907/2865fff2-e543-11e6-937d-3858cfd9a852.JPG)

Anyway, i'll wait for new release, thanks for answer

**Comment by JC5** [comment]
Yes,  the demo site is always ahead :)
