### ISSUE TITLE
0,021385479 imported as 21.385.479 instead of 0,021385479

### ISSUE THREAD

**Issue by angelbarrera92** [firefly-iii/firefly-iii#5440]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely you, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

While importing a CSV row like:

```csv
Fecha y hora;Operación;Cantidad;Balance del inversor;Balance de la cartera;Préstamos de cartera
2021-07-30 23:37:22;Los intereses pagados por  préstamo №13589233;0,021385479;0;24,80138548;975,22
```
The amount `0,021385479` is imported as `21.385.479`.

### Expected behaviour

The right value should be `0,021385479`

### Debug information

Debug information generated at 2021-12-28 08:12:58 Europe/Madrid for Firefly III version **5.6.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.8 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 4b0b9769-b424-453d-9f82-37e746102309 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Madrid |
| Browser TZ | Europe/Madrid |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | es_ES |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-07-27 00:00:00 |
| Session end | 2021-12-28 00:00:00 |
| Session first | 2021-10-01 00:00:00 |
| User ID | 1 |
| User language | es_ES |
| User locale | es_ES |
| Attempt at "es_ES.utf8" | 'es_ES.utf8' |
| Attempt at "es_ES.UTF-8" | 'es_ES.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0 |

### Steps to reproduce

Using the CSV importer with the following CSV row:

```
Fecha y hora;Operación;Cantidad;Balance del inversor;Balance de la cartera;Préstamos de cartera
2021-07-30 23:37:22;Los intereses pagados por  préstamo №13589233;0,021385479;0;24,80138548;975,22
```
And the configuration file looking like:

```json
{
    "date": "Y-m-d H:i:s",
    "default_account": 16,
    "delimiter": "semicolon",
    "headers": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "specifics": [],
    "roles": [
        "date_transaction",
        "description",
        "amount",
        "_ignore",
        "_ignore",
        "_ignore",
        "currency-symbol"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "duplicate_detection_method": "classic",
    "ignore_duplicate_lines": true,
    "ignore_duplicate_transactions": true,
    "unique_column_index": 0,
    "unique_column_type": "internal_reference",
    "version": 2
}
```

**Comment by JC5** [comment]
Nice find. This will be fixed in the next release of the [data importer](https://github.com/firefly-iii/data-importer). The CSV importer will not be updated unfortunately.

**Comment by angelbarrera92** [comment]
> Nice find. This will be fixed in the next release of the [data importer](https://github.com/firefly-iii/data-importer). The CSV importer will not be updated unfortunately.

That was fast!
Just discovered the `data-importer`. Seems like is compatible with the csv-importer right?
I'll move my deployment to use the `data-importer`. Thanks!
