### ISSUE TITLE
UX enhancements when editing transactions

### ISSUE THREAD

**Issue by tanc** [firefly-iii/firefly-iii#5441]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

When editing transactions my current workflow is quite difficult compared to similar software. I often find I need to edit recent transactions individually to add notes, add a category etc. Usually I do this from a transactions listing of some kind, like the `/reports/audit/` page). My workflow is:

1. Open the transaction in a new tab so I don't lost my place in the listing
2. Choose the edit action from the actions list
3. Edit the transaction
4. Save the transaction
5. Close the tab
6. Go back to the tab with the listing and potentially refresh it if I want to see the change

If I don't open the transaction in a new tab and instead edit and save it in the same tab I will most likely not be taken back to where I expect to be (where I was before) in the listing. This causes me some confusion as I try to find my previous location. This is worse when on paged results as if I'm taken back to the listing it will be on the first page.

### Solution

I feel like this workflow could be optimised in the following way:

1. When on a list of transactions (e.g. `/reports/audit/`) I would like to edit a single transaction in a modal dialog, triggered by an edit button/link alongside the transaction in the listing.
2. The modal dialog would open directly on the edit form for the transaction
3. Saving the transaction would trigger an ajax reload of the listing which replaces the current results without a page refresh

This would reduce the amount of clicks to edit transaction data and page loads while helping the user from getting lost/confused.

### What are alternatives?

I believe the alternative that is already considered or implemented in V2 layout is: #5323 (return to referring page)

This second approach isn't ideal as the position in the transaction listing will be lost when returning to it but at least the user will be taken back to where they were before they edited the transaction. This is especially important when editing transactions from a paged set of results. So I would say this is the minimum needed to achieve a better experience with the modals being an enhancement on top.

### Additional context

Nothing else other than to say well done and thank you for this software!

**Comment by JC5** [comment]
Thanks for the compliments!

I'm working on a new layout where this will be easier to do (and easier for me to implement). I can't accommodate every workflow unfortunately, but inline editing is definitely on my list.

**Comment by tanc** [comment]
Awesome to hear! I'm just digging around in the code now and happily noticed a decoupled approach using VueJS, something I'm competent with, so once you're at a stage where the bulk of your v2 work is done I'm happy to help with bug fixes and tweaks.

**Comment by JC5** [comment]
Very cool. I'm currently looking at the Quasar framework to do most of the heavy lifting (lots of v2 code is "vanilla vue" and it's a PITA).  If you have tips, let me know!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6304
