### ISSUE TITLE
[Data-importer] Optional config file for Nordigen/Spectre

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#5453]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After choosing Nordigen or Spectre to import transactions you can add an optional config file. If you don't have any you still have to click on Upload to go to the next page (which happens at least once the first time you try the import for an account...).

![image](https://user-images.githubusercontent.com/31923233/147697258-78babd87-524a-4d02-b3a3-b067ec68b8a0.png)

### Expected behaviour

We should have a Skip button or something like this to go to the next step without a config file.

### Debug information

No debug needed, it's a UI issue

### Steps to reproduce

Using data-importer click Import from Nordigen or Import from Spectre button. At the next screen you only have the Upload button available even if you want to import without a config file...

![image](https://user-images.githubusercontent.com/31923233/147697320-864d141f-7c29-44b4-a33b-ed42541442a9.png)

**Comment by JC5** [comment]
I could make it say “next”?

**Comment by MacPaille** [comment]
Next or whatever :) Maybe set it to Next but if the person select a file to upload the Next becomes Upload? Or just next would be enough :)
