### ISSUE TITLE
Lates CSV Importer version breaks csv imports

### ISSUE THREAD

**Issue by Shamp0o** [firefly-iii/firefly-iii#5456]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Watchtower upgraded my CSV Importer docker container to version 3.0.0. Now the import via the CLI fails with the following error message:
```
ERROR in line #1: transactions.0.source_id: Could not find a valid source account when searching for ID "0" or name "". (original value: "(not found)")
ERROR in line #1: transactions.0.source_name: Could not find a valid source account when searching for ID "0" or name "". (original value: "(not found)")
```
I suppose ID "0" refers to the default account given in the config (.json) file. In my case the entry is `"default_account": 1`  so ID should probably say "1".

Downgrading to version 2.6.1 fixes the issue.

### Expected behaviour

The import process finishes without error messages. 

### Debug information

Debug information generated at 2021-12-30 14:40:47 Europe/Amsterdam for Firefly III version **5.6.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.8 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 74d49c05-40f2-490b-810b-2e5013d1452e |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Vienna |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-12-01 00:00:00 |
| Session end | 2021-12-31 23:59:59 |
| Session first | 2013-07-09 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0 |

### Steps to reproduce

1. Upgrade (docker) CSV Importer to the latest versoin (3.0.0)
2. Import transactions via the CLI using a config file (.json)
3. Watch import process fail with above error message

### Additional info

I just saw that the CSV Importer is no longer maintained and replaced by the Data Importer so I'm aware that this issue is probably not going to be fixed but the bug might also affect the Data Importer (haven't tried yet). 

For now version 2.6.1 of the CSV Importer is working for me but at some point I will have to make the switch to the Data Importer. I wasn't able to find any migration guides. Is the Data Importer backwards compatible or do I have to rewrite my scripts I use for importing transactions?

**Comment by JC5** [comment]
I'd like you to try this on the data importer, or send me an example file + config at james@firefly-iii.org

Which commands do your scripts call?

**Comment by DavyHuijgens2MD** [comment]
I have exactly the same errors with the Data Importer V0.4.1

Line #0:
(2)transactions.0.source_id: Could not find a valid source account when searching for ID "0" or name "". (original value: "(not found)")
(2)transactions.0.source_name: Could not find a valid source account when searching for ID "0" or name "". (original value: "(not found)")

I just installed it yesterday but am not able to get any transaction imported.

**Comment by JC5** [comment]
Thanks for letting me know. I would appreciate it if you could share or send to me directory, an example CSV line and your config file.

**Comment by DavyHuijgens2MD** [comment]
Hi James,

Volgens mij ben je Nederlands toch?

Bijgevoegd een mapping en csv met 2 regels, de data is iets aangepast en algemener gemaakt.

Ik heb ook geprobeerd met postman via de api een transactie aan te maken, dit lukt echter ook niet, de response geeft gewoon een lijst van de huidige transacties. Kan het zijn dat het aan de api kant zit ipv in de data importer?

Succes met uitzoeken.

Groeten,

Davy

**Comment by JC5** [comment]
Do me a favor and reply to james@firefly-iii.org, your reply had ended up on GitHub.

**Comment by daften** [comment]
I had the same problem, I reverted to 2.6.1 for the CSV importer, and that worked for me. Gonna try the data importer next 😁

**Comment by Shamp0o** [comment]
> Which commands do your scripts call?

Just the artisan import script given in the [documentation](https://docs.firefly-iii.org/csv/usage/command_line/)
```
# self hosted
php artisan importer:import file.csv file.json

# docker
docker exec -it <container> php artisan importer:import file.csv file.json
```

I've just sent you an email with the example files.

**Comment by JC5** [comment]
Thanks for sending over the files, I'll check it out asap. 

In the data importer, the order of files is reversed:

https://docs.firefly-iii.org/data-importer/usage/command_line/

**Comment by JC5** [comment]
All examples I've seen are fixed or work, on the latest `develop` branch / `develop` Docker tag. I would appreciate your feedback, otherwise I'll find some time tomorrow to release a new Data Importer so everybody has these fixes :+1:

**Comment by Shamp0o** [comment]
I'll give it a go once the new docker image is up. I just tried the data-importer but got the same issue there. 

On a different note, you might want to include the environment variable `IMPORT_DIR_WHITELIST` in your docker run command on [this](https://docs.firefly-iii.org/data-importer/install/docker/) page. Without this, I don't think it's possible to get the CLI import working.

**Comment by JC5** [comment]
> I just tried the data-importer but got the same issue there.

Could you send me (again if necessary) the configuration file + CSV file that gives you troubles?

> Without this, I don't think it's possible to get the CLI import working.

It's not, thanks!

**Comment by JC5** [comment]
Another fix will be released to remedy another edge case. Thanks everybody for helping me debug this!
