### ISSUE TITLE
[Data-Importer] Issue with caching Nordigen connection

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#5457]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After having used FIDI with Nordigen multiple times I can see a problem with caching the connection.

First time you try to use it it asks for which country/bank you want to establish a connection, which is fine as expected. But after having imported my transactions I'd like to be able to switch to another banks (I have 5 accounts in total from 3 different banks). But clicking on start over and then select Nordigen will just start again for the same account for which the connection has been established previously.

But this is maybe due to Nordigen itself and you may not be able to do anything...

### Expected behaviour

Either start over button also flush the bank account connectivity or we need another button to flush that provider caching.

### Debug information

No debug needed I suppose

**Comment by MacPaille** [comment]
My bad it seems it's because this caching is done in the config file I'm using again. Can be ignored then 😄

**Comment by JC5** [comment]
:+1:
