### ISSUE TITLE
Add current account balance

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#5460]
### Support guidelines

- [ ] Find the account balance information in the account balance information from Nordigen
- [ ] Display info in configuration page.
- [ ] Find the account balance information in the account balance information from Salt Edge
- [ ] Display info in configuration page.

### Description

Hey @JC5 
As transaction import is more and more automated with Nordigen/SaltEdge I don't even need to connect to my bank portal to export my transactions. But that also means I do not connect anymore to check my account balance which I need to reconcile my accounts.

As FIDI is already calling the /transactions API to get them all, would it be possible to also add a call to the /balances (at least for Nordigen, don't know how it is for SaltEdge) that would allow FIDI to show the current account balance once the transactions are imported? So I can use this value to directly reconcile once my transactions are imported.

Thanks!

### Solution

Fetch the account balance from SaltEdge/Nordigen while importing the transactions to show it at the end of the import.

**Comment by JC5** [comment]
Not easily, no. The second step of the import process is the same for Spectre, Nordigen, CSV and any future importers. I'm not going to add custom code for each importer during that process.

I can show the balance on the configuration page though?

**Comment by MacPaille** [comment]
That would a solution indeed. Not possible to pass the value to the next page and if it is set to show it?
Anyway having it on the config page is already nice. Thanks!
