### ISSUE TITLE
The UI is broken and HTML is visible instead of elements.

### ISSUE THREAD

**Issue by filipproch** [firefly-iii/firefly-iii#5464]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The UI is broken and HTML is visible instead of elements.

### Expected behaviour

No HTML visible on the site.

### Debug information

Debug information generated at 2022-01-02 00:50:07 Europe/Prague for Firefly III version **5.6.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.8 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.13 |
| Host | FreeBSD |

| System info | Value |
| --- | --- |
| Installation ID | 509cd9af-3f83-4641-a142-3c7ccb0630e9 |
| Using docker? | false |
| Layout | v1 |
| System TZ | Europe/Prague |
| Browser TZ | Europe/Prague |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | cs_CZ |
| Attempt at "cs_CZ.utf8" | false |
| Attempt at "cs_CZ.UTF-8" | 'cs_CZ.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 |

### Steps to reproduce

1. Prepare MySQL, PHP, Apache2 on FreeBSD (according to https://unixcop.com/install-lamp-on-freebsd-12-x/ )
2. Install PHP extensions
3. Install Firefly according to (https://docs.firefly-iii.org/firefly-iii/installation/self_hosted/ )
4. Configure DocumentRoot to the public folder, enable AllowRewrite

### Additional info

![image](https://user-images.githubusercontent.com/1387116/147862553-7e655ec0-381d-4197-8d81-430f474a6aed.png)
![image](https://user-images.githubusercontent.com/1387116/147862556-0c8e0abf-8379-4a21-beef-1664b152616c.png)
![image](https://user-images.githubusercontent.com/1387116/147862558-3c93ccf8-6827-410b-93f6-7a502f63b629.png)
![image](https://user-images.githubusercontent.com/1387116/147862560-1b57d666-b58a-43dd-90a7-49a3a01d41a3.png)

**Comment by JC5** [comment]
That's a bug, thanks for letting me know! I will release a new version soon that should remedy this :+1:
