### ISSUE TITLE
Unable to disable Euro currency

### ISSUE THREAD

**Issue by jcalonso** [firefly-iii/firefly-iii#5467]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

This issue is still present on version 5.6.8 :
https://github.com/firefly-iii/firefly-iii/issues/2515

Cannot delete or disable a Euro currency.
Also worth mentioning that if you try to *disable* the currency it wont give any error, just  a page reload but the currency will be still enabled. Only when trying to delete shows the error.

### Expected behaviour

Euro currency can be deleted or disabled if no account are using it.

### Debug information

Debug information generated at 2022-01-02 12:06:46 Asia/Kuala_Lumpur for Firefly III version **5.6.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.8 |
| Firefly III API | 1.5.5 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 0ca6ffe5-3cf7-42eb-ad47-565b07ab130a |
| Using docker? | true |
| Layout |  |
| System TZ | Asia/Kuala_Lumpur |
| Browser TZ | Asia/Kuala_Lumpur |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first | 2021-12-16 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0 |

**Comment by JC5** [comment]
>  Also worth mentioning that if you try to disable the currency it wont give any error, just a page reload but the currency will be still enabled. Only when trying to delete shows the error.

This will be fixed in the new release, and it'll also tell you why it can't be disabled (yet).

<img width="920" alt="Screenshot 2022-01-02 at 08 03 11" src="https://user-images.githubusercontent.com/5889984/147868752-f37b6b1d-9267-43a6-8d9b-4edc0b245a31.png">

**Comment by jcalonso** [comment]
Cheers! :+1:
