### ISSUE TITLE
php artisan migrate --seed --env=production (Twig problem)

### ISSUE THREAD

**Issue by ubje** [firefly-iii/firefly-iii#547]
When I try to run the command on a new install I get a warning.

[InvalidArgumentException]
Cannot instantiate Twig extension 'Twigbridge\Extension\Laravel\Session':The only supported cyphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

What can I do to tun the command without these errors?

**Comment by JC5** [comment]
It is a bug that is related to Twig, and I thought it was fixed. Did the other steps go as planned?

Can you visit the login screen already?

**Comment by ubje** [comment]
Not sure about the other steps First I tried the command without sudo and got lots of permission errors. Later I tried with sudo and only gee this error.

No, if I go to /firefly-iii/public the screen stays white.

**Comment by JC5** [comment]
What do you mean, not sure? Either the installation guide up to this point worked, or it didn't.

Which command did you try without sudo? Was it the migration command? It should not be necessary to do so.

**Comment by ubje** [comment]
The steps went fine till I came to the migrate command. And I only had to answer 'yes' one time, thought there were maybe more, so I said not sure.

First time I ran the migrate command without sudo and got this in the attached file. Didn't know how to paste it properly.

[firefly-error.txt](https://github.com/firefly-iii/firefly-iii/files/742016/firefly-error.txt)

**Comment by JC5** [comment]
Ah yes. Try this in the Firefly III directory

`chmod -R 777 $USER:$USER ./`

**Comment by ubje** [comment]
Now I only got the warning about Twig, but when I go to the webpage I see the message

Whoops, looks like something went wrong.

**Comment by JC5** [comment]
Ok, remove the files in `storage/logs` and refresh the page. If it still gives the error, run this command:

`chmod -R 777 www-data:www-data ./storage`

If that does not work, the directory `storage/logs` should hold a new log file with the error that is causing the "whoops".

**Comment by ubje** [comment]
I did the commands only the last one I used chown for www-data.
After removing the log and refresh the page I have this log.
[firefly-iii-2017-02-01.txt](https://github.com/firefly-iii/firefly-iii/files/744121/firefly-iii-2017-02-01.txt)

**Comment by JC5** [comment]
Ok, it is a user rights problem for sure.

When you do the chown / chmod actions for your own username (`$USER`) the web server cannot write any logs and will stop working.

When you do this for the web server (`www-data`) you yourself cannot run any commands.

What you can do is this

`usermod -a -G www-data $USER`

Then login / logout.

Then run these commands:

`sudo chown -R www-data:$USER /var/www/firefly-iii` (or wherever it is installed)
`sudo chmod -R 777 /var/www/firefly-iii/`

That should allow both the webserver and the local user access to the logs dir.

**Comment by ubje** [comment]
I removed the log files again, entered the commands. Instead of logout/login I restarted.

When I try to open the webpage I see the same results in the log file, and same whoops message.

**Comment by JC5** [comment]
Open `.env`, and change APP_DEBUG=false to APP_DEBUG=true

Then visit the site.

I don't understand why you see an error in your log file, complaining that it cannot write to the log file!

**Comment by ubje** [comment]
I changed the env file, but still the same

**Comment by JC5** [comment]
There should be at least more error logging under the message. Otherwise I have no idea what you're doing.

**Comment by ubje** [comment]
No, I deleted the log file. Tried to open the page but no matter what the log file has the same details.

**Comment by ubje** [comment]
I started over again, this time I used ubuntu 16.04 server. Had to combine the installation guide for 14.04 and 16.04 so all php modules were loaded. Now it is ok and I can register my account.

**Comment by JC5** [comment]
Ok, very strange. I'm closing this issue but I'll keep trying to replicate your problem!
