### ISSUE TITLE
Bulk delete expense accounts

### ISSUE THREAD

**Issue by taker218** [firefly-iii/firefly-iii#5476]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be nice to have the possibility to delete multiple expense accounts at once.

Or have a button to delete all expense accounts without any transaction associated, so you could get rid of accounts added by faulty imports easier.

### Solution

It would make it easier to delete multiple not used accounts at once.

**Comment by JC5** [comment]
Perhaps in the new layout, but zero promises. Bulk deleting expense accounts doesn't happen *that* often. Building a routine for it isn't worth the time at the moment.
