### ISSUE TITLE
Credit card - Split purchases in monthly payments

### ISSUE THREAD

**Issue by roliveira2015** [firefly-iii/firefly-iii#548]
I believe is not common in some countries (specially the US) to have a purchase in your credit card split in several non-interest installments. But in Brazil is very common, and credit cards here are mainly used to do that. Say you buy a TV for R$1000. At the very time of the purchase, either in a physical store or online, you get to choose to split the total amount in 10 montlhy equal payments of R$100. And your credit card bill will reflect this each month.

How do I keep track of that in Firefly III? I tried to build up a rule, but couldn't figure it out. I thought about creating a bill with the installments, but I couldn't forge in my mind the right way to have the due amounts bound to my credit card transactions. Say my credit card bill this month is R$200, and half of this value is the installment relative to the TV purchase. In order to zero the negative balance in my credit card asset account, I would make a transfer transaction from my checking account, right? How do I make this transaction reflect the total amount of my credit card and also be related to the bill I created for the TV installments?

And also, I would like to have the future installments visible in a way that I can forecast my monthly expenses. All this with the correct budgets ans categories...

Is that possible?

I burned my neurons trying to figure out how to make Firefly work that way, and that's why I'm hoping some of you guys would have a better understanding of the system in this aspect.

Thanks in advance!

**Comment by JC5** [comment]
Is the balance of the credit card -1000,-? Or is the balance of the credit card -100,- every month?

1. If it is the first, you could spend 1000,- in one withdrawal from the credit card, and fill that gap with 10 transfers of 100,- each.
2. If it is the second, you should make it a withdrawal from your credit card every month for 100,-. For example "payment of TV" to "Big Store". This can be matched with a bill. You repay it with a transfer of 100,- to your credit card.

The other half of the monthly credit card bill would not be included in this, and would consist of regular expenses.

At the moment, you cannot keep track of future expenses and payments.

**Comment by roliveira2015** [comment]
OK!

My situation is the second you described. And I think that making a withdrawal match to a bill can work for me. It won't be as automatic as I thought, but I believe it'll work.

In my spare time I will try and go through the source code and see if I can create an action that will automatically set the bill and the duration of it triggered by some option during the first transaction creation.

Thank you very much!
