### ISSUE TITLE
Piggy bank increase/decrese amount on transaction

### ISSUE THREAD

**Issue by SloCompTech** [firefly-iii/firefly-iii#5482]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I looked at the other opened issues and also some of the closed ones, but I didn't find exact match.

Every period (September, start of a school year) I set amounts for budget or fund to constrain myself how much I can spend on certain things. But since budgets are monthly, they are useless to me, because I need to limit myself over period of a year or so.

### Solution

The solution includes #5269.  Since it was said in one of the issues that making budgets over flexible period is  hard to implement I'm proposing different solution.

- Make Piggy bank target amount optional (if not set, disable progress bar)
- Add option to link piggy bank to the transaction like a budget (on create: increase/decrease piggy bank amount, on edit increase/decrease piggy bank amount for difference, on delete increase/decrease piggy bank amount)
- If piggy bank amount is changed don't recalculate anything, leave it as it is.

**Comment by JC5** [comment]
I'm working on both of these things, and I hope to show them off in the new layout:

- https://github.com/firefly-iii/firefly-iii/issues/5269 to be able to have piggy banks with no amount
- to be able to more easily set budgets over a year or another period.

It will not be possible to increase / decrease piggy banks with anything other than transfers.

**Comment by SloCompTech** [comment]
Glad to hear it. Looking forward to it.

**Comment by JC5** [comment]
> If piggy bank amount is changed don't recalculate anything, leave it as it is.

I'm not sure what this means but all the other features are implemented.
