### ISSUE TITLE
Setup CronJob for data-importer from Nordigen

### ISSUE THREAD

**Issue by AndreiGavriliu** [firefly-iii/firefly-iii#5484]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,

first of all, happy new year!

Yesterday, I've tried to move my firefly-iii to my kubernetes cluster. I checked the kubernetes repo, downloaded the files, updated them, created all objects, and apparently it works. I also created a Nordigen account and imported 3 Months worth of transactions, all were successful. Now, I wanted to add a cronjob, so I do not have to click through the importer every day. For this, I followed the documentation and, basically got stuck.

When running this via terminal, I get an error (which is confusing, since the docs say `You can also import from Nordigen or Spectre, in which case a JSON file is enough`
```
curl \
--location \
--request POST 'http://[redacted]/autoupload?secret=firefly-iii' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer [redacted]' \
--form 'json=@"/[redacted]/Desktop/import-nordigen.json"'

{"message":"The given data was invalid.","errors":{"csv":["The csv field is required."]}}
```

I'm sure there is something I'm missing, but what/where? 
If I understand correctly, based on the `https://github.com/firefly-iii/kubernetes/blob/main/ingress-firefly-iii-cron.yaml` I could use a busybox container to post the json file which should trigger the import, right?

Cheers,
Andrei

### Expected behaviour

Create a cronjob which automatically downloads nordigen data and imports them based on the import-config.json

### Debug information

Debug information generated at 2022-01-04 06:25:38 Europe/Amsterdam for Firefly III Data Importer version **0.5.0**.

| Scope | Version |
| --- | --- |
| FIDI | 0.5.0 |
| Build | 53 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/Berlin |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0 |

### Additional info

the /debug page from the importer has an extra newline which breaks formatting:

```
| Scope | Version |
| --- | --- |
| FIDI | 0.5.0 |
| Build | 53
 |
| PHP | 8.0.13 |
| Host | Linux |
```

**Comment by JC5** [comment]
That's a bug, nice find!

And the debug page will also be fixed :+1:
