### ISSUE TITLE
Bills appear in the financial report as "not charged (yet)" even though they have already been paid

### ISSUE THREAD

**Issue by Santobert** [firefly-iii/firefly-iii#5485]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The default financial report lists some bills as "Not charged (yet)" even though the have been paid already. By selecting that specific bill it can be seen that it have been paid.

https://demo.firefly-iii.org/reports/default/41,6,1,40,5,42,4,2,3/previousMonthStart/previousMonthEnd
![grafik](https://user-images.githubusercontent.com/15657682/148041031-d0621aa7-3723-4eb0-8b4f-175431abdae9.png)

https://demo.firefly-iii.org/bills/show/1
![grafik](https://user-images.githubusercontent.com/15657682/148041127-1f703d26-7998-4621-b3db-288fcea0ff12.png)

In this example, the bill was not yet fully paid. But the same effect occurs with my own instance and with fully paid bills.

### Expected behaviour

Paid bills show up in the default financial report

### Debug information

Debug information generated at 2022-01-04 10:54:42 Europe/Berlin for Firefly III version **5.6.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.9 |
| Firefly III API | 1.5.5 |
| Build | 66 , 02-01-2022 08:12:35 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 8c693697-9c90-4d86-979a-9f695f0ccb16 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first | 2021-08-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0 |

**Comment by JC5** [comment]
Cal you tell me what the start date and the period of the bill is?

**Comment by Santobert** [comment]
The start date was months before the range of the financial report. The bill repeats monthly.

**Comment by JC5** [comment]
But it works as expected. The bill was paid in January but the report is until December 31st. So it wasn't paid in December.

**Comment by Santobert** [comment]
I'm very sorry. It seems the example is badly chosen. With my own instance I've bills that are monthly paid and the respective payments don't show up in monthly reports.

The following is the monthly Netflix subscription with my own instance. As you can see, the transaction is connected with the bill, but it says "not charged" in the report.

> Default financial report between December 1, 2021 and December 31, 2021 

![Screenshot_20220104-124327~2](https://user-images.githubusercontent.com/15657682/148054462-e58ecc98-f856-45f0-a723-800406f20f96.png)

![Screenshot_20220104-124847](https://user-images.githubusercontent.com/15657682/148054722-01bbe993-42c3-48b8-bad2-9631118c5e22.png)

**Comment by JC5** [comment]
Thanks for the extra clarification!

I think I know the issue, but I'm aware its counter intuitive.

Change the start date of the bill to the first of the month, not the second of the month. Maybe that will help!

**Comment by Santobert** [comment]
That's indeed somewhat counter intuitive 😄 
After I have changed the date to the first of the month, the bills show up in the financial reports. This may work for bills that are due at the beginning of the month, but not for bills that are due in the middle of the month or any other specific date.
Is it possible, this issue will be fixed in the future?
Thank you very much

**Comment by JC5** [comment]
The period during which the bill will mark itself as paid (or not) starts at the start date, and lasts exactly one period. In other words:

- Monthly, 1st to 1st
- Monthly, 2nd to 2nd
- Monthly, 12th to 12th

The net effect is that a bill that you set up on the 12th will be considered "paid" on the 9th of the *next* month as well.

This behavior will not change, but it'll be harder to mistake these things in a new layout I'm working on. As such, this is a "wontfix" but it will actually be fixed 😉

**Comment by Santobert** [comment]
Thanks for tue feedback. It's kind of unfortunate, because I really liked to see when some bill will be booked. But thank you anyways

**Comment by JC5** [comment]
I know the feeling. I have the same challenge.
