### ISSUE TITLE
[Link transaction] Duplicate text in dropdown 'this transaction'

### ISSUE THREAD

**Issue by Eppin** [firefly-iii/firefly-iii#5486]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

There are 2 `relates to` options in the dropdown box when linking a transaction. While the value in HTML is different: `1_inward`, `1_outward`. I've tried to search/edit these strings in Crowdin, but I was unable to find it (perhaps because I'm unfamiliar with Crowdin).

### Expected behaviour

There should be different texts for the `relates to`.

### Debug information

Demo site running 5.6.9

### Additional info

![image](https://user-images.githubusercontent.com/96589679/148071600-e187b7b5-5a7c-4559-a967-45d1994d6ad4.png)

**Comment by JC5** [comment]
The reason it lists "relates to" twice, is because the relationship is the same in both directions. A relates to B and B relates to A.

In the past, I had a filter that would correct it but somebody complained because technically, they could only make A>B relationships and never B>A.
