### ISSUE TITLE
Budgets with a specific renew date

### ISSUE THREAD

**Issue by poudenes** [firefly-iii/firefly-iii#5497]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hi All,

I have some budgets added with "fixed amount every period"
I would like to have the option that this period will start (in my case) 15th of every month.

My salary comes at the 14th and then I have the budget started next day.

### Solution

You can have your own start of the budgets

### What are alternatives?

Accept the budget will start every 1st of month. So different way of thinking

**Comment by JC5** [comment]
Firefly III has been designed around the month instead of an arbitrary paycheck date.

https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/personal-finances/

**Comment by poudenes** [comment]
Make sense :)
