### ISSUE TITLE
Daterangepicker is not working

### ISSUE THREAD

**Issue by worldworm** [firefly-iii/firefly-iii#550]
Hello,
I upgraded to 4.3.3 and the Datepicker in the right upper corner isn't there.
Thanks for your Help

(sorry for the bold text, not sure why markdown ist formatting this)
Javascript Error:
```
ReferenceError: currencySymbol is not defined
https://xyz/js/ff/firefly.js
Line 114
---
jQuery.Deferred exception: dateRangeConfig is not defined
@https://xyz/js/ff/firefly.js:26:5
g/</j@https://xyz/js/lib/jquery-3.1.1.min.js:2:29946
g/</k<@https://xyz/js/lib/jquery-3.1.1.min.js:2:30262
undefined
---
jQuery.Deferred exception: dateRangeConfig is not defined
@https://xyz/js/ff/firefly.js:26:5
g/</j@https://xyz/js/lib/jquery-3.1.1.min.js:2:29946
g/</k<@https://xyz/js/lib/jquery-3.1.1.min.js:2:30262
undefined
---
ReferenceError: noDataForChart is not defined
https://xyz/js/ff/charts.js
Line 259
```

**Comment by JC5** [comment]
Try control f5 to clear

**Comment by JC5** [comment]
...  Your browser cache. Apologies, I am on my phone.

**Comment by worldworm** [comment]
Thanks for your quick answer

control f5 didn't worked
I also reinstalled everything (followed everything here https://firefly-iii.github.io/upgrade-guide/)
Clearing cache and cookies didn't helped
Using an other browser didn't helped
Another device didn't helped also.

**Comment by JC5** [comment]
No problem! Which browsers did you use? Which operating system? Could you post the content of `/javascript/variables.js`?

**Comment by worldworm** [comment]
I tried Internet Explorer and Firefox on Windows 7, Firefox on Android.

Iam not sure which variables.js you mean

**Comment by JC5** [comment]
Surf to that URL. For example on the demo site:

https://firefly-iii.nder.be/javascript/variables.js

But on your own site.

**Comment by worldworm** [comment]
I already tried this, but it said "The requested URL /javascript/variables.js was not found on this server." (Apache)

**Comment by JC5** [comment]
But the rest of firefly works? That doesn't make it sense. What is the URL of the login page for example?

**Comment by JC5** [comment]
I may be have found the problem and I'll see if I can't fix it soon. In the meantime, please tell me the full URL of the login page, of the reports page and of the page with withdrawals so I can confirm the issue.

**Comment by worldworm** [comment]
Yes, everything else is working fine.
I compared i think equal to every URL to the demo site and i found no differences.

/transactions/create/withdrawal
/reports
/login

**Comment by JC5** [comment]
Ok, so there are no extra directory paths, like `/firefly-iii/` or `/public/` or something like that? Also no `index.php` in the URL?

Could you post a part of the source code of Firefly?

Go to the index (when you are logged in) and do right-click, view source (works in almost any browser).

Go to the bottom of the page, and you should find this line:

`<script src="js/lib/jquery-3.1.1.min.js" type="text/javascript"></script>`

Please post everything below that line in a reply.

**Comment by worldworm** [comment]
Right, my apache points directly into the firefly-iii/public/ folder. so mysub.domain.de points to it.
The index.php is not shown in the url

Here is the code

<script src="js/lib/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="lib/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="js/lib/moment.min.js" type="text/javascript"></script>
<script src="js/lib/daterangepicker.js" type="text/javascript"></script>
<script src="lib/adminlte/js/app.min.js" type="text/javascript"></script>
<script type="text/javascript" src="js/lib/accounting.min.js"></script>
<script src="js/lib/bootstrap-tour.min.js" type="text/javascript"></script>
<script src="javascript/variables.js" type="text/javascript"></script>
<script type="text/javascript" src="js/ff/firefly.js"></script>
<script type="text/javascript" src="js/ff/help.js"></script>
    
    <script type="text/javascript">
        var showTour;
                showTour = false;
                var billCount = 2;

        // uri's of charts:
        var accountFrontpageUri = 'https://mysub.domain.de/chart/account/frontpage';
        var accountRevenueUri = 'https://mysub.domain.de/chart/account/revenue';
        var accountExpenseUri = 'https://mysub.domain.de/chart/account/expense';
    </script>

    <script type="text/javascript" src="js/lib/Chart.bundle.min.js"></script>
    <script type="text/javascript" src="js/ff/charts.defaults.js"></script>
    <script type="text/javascript" src="js/ff/charts.js"></script>
    <script type="text/javascript" src="js/ff/index.js"></script>

**Comment by JC5** [comment]
Maybe it's the dot. I'll try something tonight. I use nginx personally so I have to change some things.

**Comment by worldworm** [comment]
Iam not sure if it will help you, but better than nothing :)
I downgraded back to my working Version (4.3.1)

/javascript/variables.js
also shows Not found

Here is the code

```
<script src="js/lib/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="lib/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="js/lib/moment.min.js" type="text/javascript"></script>
<script src="js/lib/daterangepicker.js" type="text/javascript"></script>
<script src="lib/adminlte/js/app.min.js" type="text/javascript"></script>
<script type="text/javascript" src="js/lib/accounting.min.js"></script>
<script src="js/lib/bootstrap-tour.min.js" type="text/javascript"></script>

<script type="text/javascript">

    // date range picker configuration:
    var dateRangeConfig = {
        startDate: moment("2017-02-01"),
        endDate: moment("2017-02-28"),
        linkTitle: "February  1, 2017 - February 28, 2017",
        URL: "https://yxc.de/daterange",
        firstDate: moment("2016-08-01"),
        currentPeriod: "February 2017",
        previousPeriod: "January 2017",
        nextPeriod: "March 2017",
        everything: 'Everything',
        customRangeLabel: 'Custom range',
        applyLabel: 'Apply',
        cancelLabel: 'Cancel',
        fromLabel: 'From',
        toLabel: 'To',
        ranges: {"current":["2017-02-01","2017-02-28"],"previous":["2017-01-01","2017-01-31"],"next":["2017-03-01","2017-03-31"]}
    };
    
    var language = "en_US";
    var currencyCode = 'EUR';
    var currencySymbol = '\u20AC';
    var mon_decimal_point = ".";
    var mon_thousands_sep = ",";
    var frac_digits = 2;
    var noDataForChart = 'There is not enough information (yet) to generate this chart.';
    var showFullList = 'Show entire list';
    var showOnlyTop = 'Show only top 10';


</script>

<script type="text/javascript" src="js/ff/firefly.js"></script>
<script type="text/javascript" src="js/ff/help.js"></script>
    <!-- show tour? -->
    <script type="text/javascript">
        var showTour;
                showTour = false;
                var billCount = 3;

        // uri's of charts:
        var accountFrontpageUri = 'https://yce/chart/account/frontpage';
        var accountRevenueUri = 'https://yc.de/chart/account/revenue';
        var accountExpenseUri = 'https://ycrm.de/chart/account/expense';
    </script>

    <script type="text/javascript" src="js/lib/Chart.bundle.min.js"></script>
    <script type="text/javascript" src="js/ff/charts.defaults.js"></script>
    <script type="text/javascript" src="js/ff/charts.js"></script>
    <script type="text/javascript" src="js/ff/index.js"></script>
```

**Comment by worldworm** [comment]
@JC5 
Problem is there again in 4.3.4
Everything is the same as in 4.3.3 
(/javascript/variables.js will show not found, the code is also the same)

Hope you can help again

**Comment by JC5** [comment]
Ok could you post the configuration of your Apache server and the source of the page?

4.3.4 actually has a different URL for the Javascript file because I was afraid that the dot would be the problem. Could you compare your source code (index page, view source) with the one below? It should be like this:

```html
<script src="js/lib/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="lib/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="js/lib/moment.min.js" type="text/javascript"></script>
<script src="js/lib/daterangepicker.js" type="text/javascript"></script>
<script src="lib/adminlte/js/app.min.js" type="text/javascript"></script>
<script type="text/javascript" src="js/lib/accounting.min.js"></script>
<script src="js/lib/bootstrap-tour.min.js" type="text/javascript"></script>
<script src="https://firefly-iii.nder.be/javascript/variables?ext=.js" type="text/javascript"></script>
<script type="text/javascript" src="js/ff/firefly.js"></script>
<script type="text/javascript" src="js/ff/help.js"></script>
    <!-- show tour? -->
    <script type="text/javascript">
        var showTour;
                showTour = false;
                var billCount = 2;

        // uri's of charts:
        var accountFrontpageUri = 'https://firefly-iii.nder.be/chart/account/frontpage';
        var accountRevenueUri = 'https://firefly-iii.nder.be/chart/account/revenue';
        var accountExpenseUri = 'https://firefly-iii.nder.be/chart/account/expense';
    </script>
```

So the URL actually is `https://firefly-iii.nder.be/javascript/variables?ext=.js` or similar and I need to know a lot more about your installation before I know why it doesn't work.

**Comment by worldworm** [comment]
after 3 days of searching i think i found something

I reinstalled my whole server 4 times.
Everytime firefly works fine after i startet with my other instalations
I found that that ubuntu packet "graphite-web" is producing this problems.

Tommorow i will try to test which packet of this instalation will cause this problem

Here are more information about this packet (i think one of the Dependencies might cause the problem, not graphite iteself (more about that tomorrow))
 (apt-cache showpkg graphite-web)
Package: graphite-web
Versions:
0.9.15+debian-1 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages) (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-i386_Packages) (/var/lib/dpkg/status)
 Description Language:
                 File: /var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages
                  MD5: d194dc951df04c82ac612f6b137edef8
 Description Language: en
                 File: /var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_xenial_universe_i18n_Translation-en
                  MD5: d194dc951df04c82ac612f6b137edef8


Reverse Depends:
  graphite-carbon,graphite-web
  syslog-ng-mod-graphite,graphite-web
Dependencies:
0.9.15+debian-1 - python:any (3 2.8) python:any (2 2.7.5-5~) adduser (0 (null)) python-cairo (0 (null)) python-django (4 1.6-1~) python-simplejson (0 (null)) python-django-tagging (4 1:0.4-1~) python-tz (0 (null)) python-pyparsing (0 (null)) libjs-scriptaculous (0 (null)) libjs-prototype (0 (null)) python-whisper (4 0.9.15-1~) python-memcache (0 (null)) libapache2-mod-wsgi (0 (null)) python-ldap (0 (null)) python-mysqldb (0 (null)) graphite-carbon (0 (null))
Provides:
0.9.15+debian-1 -
Reverse Provides:

**Comment by JC5** [comment]
Installing the package doesn't seem to give my Ubuntu dev-server any trouble, but it could be the problem. 

If you can confirm the new url doesn't work either (`/javascript/variables?ext=.js`) I can see if we can't debug this together.

The 404 generated by Firefly looks like this. This error means Apache is correctly sending you to Firefly but there is no page for the URL:

![screen shot 2017-02-11 at 16 25 09](https://cloud.githubusercontent.com/assets/5889984/22854889/c39021ea-f076-11e6-86c8-e446d7742bc4.png)

This is different from the [default Apache 404 page](https://www.google.nl/search?q=apache+default+404&source=lnms&tbm=isch&sa=X).

**Comment by worldworm** [comment]
Hi there, i tried a lot the last hours. I found that the packet „javascript-common“ should cause the problems

Here is the "log" of my search

`Clean Ubuntu 16.04 Installation

sudo apt-get update && sudo apt-get upgrade --assume-yes && sudo apt-get install --assume-yes vim apache2 apache2-doc mysql-server libapache2-mod-php7.0 php7.0 php7.0-mysql php7.0-mbstring php7.0-intl php7.0-bcmath php7.0-mcrypt php7.0-curl php7.0-zip
install composer
installed firefly (with mysql)
put firefly into „html“ example apache folder, edited the defaultsite to /var/www/html/public/
Firefly is working now, the datapicker is visible
/javascript/variables.js shows „Sorry, the page you are looking for could not be found.“ (same as /abc)
/javascript/variables?ext=.js shows 
„// date range picker configuration:
var dateRangeConfig = {
    startDate: moment("2017-02-01"),
    endDate: moment("2017-02-28"),
    linkTitle: "February  1, 2017 - February 28, 2017",
    URL: "sdfsdf/daterange",
    firstDate: moment("2017-02-12"),
    currentPeriod: "February 2017",
    previousPeriod: "January 2017",
    nextPeriod: "March 2017",
    everything: 'Everything',
    customRangeLabel: 'Custom range',
    applyLabel: 'Apply',
    cancelLabel: 'Cancel',
    fromLabel: 'From',
    toLabel: 'To',
    ranges: {"current":["2017-02-01","2017-02-28"],"previous":["2017-01-01","2017-01-31"],"next":["2017-03-01","2017-03-31"]}
};

var language = "en_US";
var currencyCode = 'EUR';
var currencySymbol = '\u20AC';
var mon_decimal_point = ".";
var mon_thousands_sep = ",";
var frac_digits = 2;
var noDataForChart = 'There is not enough information (yet) to generate this chart.';
var showFullList = 'Show entire list';
var showOnlyTop = 'Show only top 10';
var accountingConfig = {"pos":"%s%v","neg":"-%s%v","zero":"%s%v"};
“
Now i tried a bit with the graphite-web dependencies and tracked it down to this =
Apt-get install libjs-scriptaculous 
Refreshing the my site and the datapicker is gone
/javascript/variables.js  and /javascript/variables?ext=.js shows the apache error „The requested URL /javascript/variables.js was not found on this server.“ 
But /abc shows the Sorry, the page you are looking for could not be found.“ from firefly

apt-get remove --auto-remove libjs-scriptaculous

hit F5 and everything is working again

BUT,thats not everything

This package libjs-scriptaculous  also has dependencies, i tracked it down to „libjs-prototype“ (datapicker diapperas here too)

Dependencie of „libjs-prototype“  is „javascript-common“ (datapicker disapperas here too)

There are no other dependencies for „javascript-common“ so i think this the end of my search

`

**Comment by JC5** [comment]
I just found out that this package overrules the /javascript/ path:

https://anonscm.debian.org/cgit/pkg-javascript/javascript-common.git/tree/javascript-common.conf?id=769fc5db10bf82c16cd05b0f6ddf890d07500e93

**Comment by JC5** [comment]
I've updated the FAQ to mention this issue.
