### ISSUE TITLE
Accept different PostgreSQL database schemas

### ISSUE THREAD

**Issue by tjmv** [firefly-iii/firefly-iii#5503]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

PostgreSQL can use a database schema to logically split objects. The name defaults to `public`, but having the option to change it can be very useful to make organizing apps more manageable.

### Solution

Simply make it an environment variable:
https://github.com/firefly-iii/firefly-iii/blob/main/config/database.php#L112
```PHP
'schema'      => envNonEmpty('PGSQL_SCHEMA', 'public'),
```

**Comment by JC5** [comment]
Good idea, done!
