### ISSUE TITLE
[Data Importer] cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by xEtarusx** [firefly-iii/firefly-iii#5508]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When running an import from a *.tsv (tab separated) file I get cURL errors after random lines. The line number where it fails changes with each run so there is no error in a specific line. I tried multiple files with different content.

### Expected behaviour

The import should finish without any cURL errors.

### Debug information

Debug information generated at 2022-01-08 11:33:12 Europe/Berlin for Firefly III version **5.6.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.9 |
| Firefly III API | 1.5.5 |
| Build | 66
, 02-01-2022 08:12:35 CET
 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | e6d0eb38-d5a7-4636-b340-dcfaff88ff28 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first | 2022-01-03 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 |

### Steps to reproduce

I can reproduce it with my *.tsv files but I don't wanna share those here.

### Additional info

Log error:

fireflyiii-data-importer | [2022-01-08 11:28:01] production.INFO: Now processing line 182/248.
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now in App\Services\CSV\Conversion\Routine\PseudoTransactionProcessor::processPseudoLine
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now running task App\Services\CSV\Conversion\Task\Amount
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now at the start of processAmount("0.00")
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Transaction["amount_negated"] value is not NULL ("-5.990000000000"), assume this is the correct value.
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Amount is now -5.990000000000.
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Amount -5.990000000000 is negative, so this is probably a withdrawal.
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now running task App\Services\CSV\Conversion\Task\Tags
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now running task App\Services\CSV\Conversion\Task\Currency
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Set currency to 1 because it was NULL or empty.
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now running task App\Services\CSV\Conversion\Task\Accounts
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now in Accounts::process()
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now processing transaction 1 of 1
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now in Accounts::processTransaction()
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now in findAccount {"transaction_type":"withdrawal","id":null,"name":"Hannah Girokonto","iban":null,"number":null,"bic":null,"direction":"source"}
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Default account is #302 ("Sonstiges")
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Find by name.
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Going to search account with name "Hannah Girokonto"
fireflyiii-data-importer | [2022-01-08 11:28:01] production.ERROR: cURL error 6: Could not resolve host: predator.box (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://predator.box:8085/api/v1/search/accounts?query=Hannah+Girokonto&field=name&page=1
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now in setConversionStatus(conv_errored)
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Found "conv-Lhfv9N3eMFoE" in the session
fireflyiii-data-importer | [2022-01-08 11:28:01] production.DEBUG: Now in startOrFindConversion(conv-Lhfv9N3eMFoE)

**Comment by JC5** [comment]
This is not related to the TSV files, but I have no clue what it could be. Especially because it fails at random moments. I assume the "predator.box" url is correct?

**Comment by xEtarusx** [comment]
I run a home server with custom dns server which points predator.box to my home server. Firefly runs on http://predator.box:8085 and the importer on http://predator.box:8086.
Not sure why it just randomly fails, but sometime I can get it through without any errors.
But currently I'm only testing with less data to get used to firefly. I guess when I'm gonna import all my data it'll never go through, sadly.

**Comment by JC5** [comment]
Does the DNS server get all calls? Does it b0rk out maybe?

**Comment by JC5** [comment]
If the system that hosts Docker has multiple DNS servers configured, either through DHCP or through Docker, it'll randomly fail because DNS1, DNS2 etc are called randomly, not in order.

**Comment by xEtarusx** [comment]
Oh not, it really was the dns. Didn't thought about it earlier.

I use PiHole as DHCP and DNS server and it seems like it has a default rate limiter with 1000 requests per minute per client. PiHole even had a notification about a client beeing rate limited.

Than the error was on my system, not your code. Sorry for the trouble.

**Comment by JC5** [comment]
No problem, glad to hear it works now!
