### ISSUE TITLE
Data importer (CSV) simply doesn't work

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#5509]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When i use the data importer with a CSV file and use the same configuration as I used in the CSV importer before (mapping data and so on), it says it imported transactions, however, nothing is imported in firefly. If I click start job again I get a lot of these messages:
```
Line #15:
(2)transactions.0.source_id: Could not find a valid source account when searching for ID "0" or name "". (original value: "(not found)")
(2)transactions.0.source_name: Could not find a valid source account when searching for ID "0" or name "". (original value: "(not found)")
```
and some transactions are imported. However the IBAN isn't mapped correctly. It doesn't seem to strip spaces from both sides when doing a mapping, so my checking account isn't recognized and the transaction source (or target) is mapped to a revenue or expense account, instead of an asset account.

### Expected behaviour

I'd expect the importer to work the same as it did in the CSV importer (2.6.1, 3.0.0 doesn't work well for me either)

### Debug information

Debug information generated at 2022-01-08 19:02:54 Europe/Brussels for Firefly III version **5.6.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.9 |
| Firefly III API | 1.5.5 |
| Build | 66
, 02-01-2022 08:12:35 CET
 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 91f8b90e-4a5b-4e53-b590-1366bd11a760 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Brussels |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first | 2019-12-25 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 |

### Steps to reproduce

I honestly don't know what in the data causes this and can't give files without giving away personal information :s

**Comment by JC5** [comment]
I'm aware of the issue with IBANs with spaces in them. If you remove them in Firefly III they should match again, and the import should continue as expected. I hope to release the fix tomorrow in Firefly III v5.6.10

**Comment by daften** [comment]
Thanks for the quick reply (as always) James!
I'll test again later this week when I've got more transactions to import and let you know if everything is fixed. I think there's 2 bugs working together here, the other one had already been reported but was considered fixed, if I remember correctly (#5456)

**Comment by JC5** [comment]
Everything I've been sent "works for me", except for this IBAN thing, which is the last fix.

**Comment by JC5** [comment]
5.6.10 is out, which should pick up the IBAN's and auto fix them

**Comment by JC5** [comment]
Also 0.6.2 is out. I'm going to presume this is fixed, but please reply or open a new ticket if you run into anything.
