### ISSUE TITLE
Adding (bank)Accounts or changing (bank)assets account 

### ISSUE THREAD

**Issue by t-me** [firefly-iii/firefly-iii#551]
Hello All,

I have just installed Firefly |||.
Now i want to add a Bank(assets) account.

i get an error at "Account role"

`Any extra options resulting from your choice can be set later.
The selected account role is invalid.`

when i first loged in i made a assets account on de "Dashboard" when i want to change it the above error also appears.

Thanks for helping

**Comment by JC5** [comment]
Yes, you're right, you've found a bug!

Since this is bug nr. 2 in the current release, I will push a fix tonight!

**Comment by JC5** [comment]
This means you'll have to upgrade to 4.3.4, but then it should be fixed!

**Comment by t-me** [comment]
Thanks for the quick reply and fix :)
