### ISSUE TITLE
Custom link transaction is displayed on transaction with `firefly.` prefix

### ISSUE THREAD

**Issue by DanielNetoP** [firefly-iii/firefly-iii#5510]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I've started to use custom link transactions and I've noticed that the description on the transaction layout is prefixed by `firefly.` as can be seen on the image below:
![image](https://user-images.githubusercontent.com/10155766/148660996-1ecd861e-4b52-41fe-8fb5-2b3de5b1e171.png)

### Expected behaviour

Text of the description (inward/outward) without the `firefly.` prefix on the description.
I've done a installation from scratch to make sure that was not because of my install.

### Debug information

Debug information generated at 2022-01-08 21:44:54 Europe/Lisbon for Firefly III version **5.6.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.9 |
| Firefly III API | 1.5.5 |
| Build | 66
, 02-01-2022 08:12:35 CET
 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b12af349-1b75-4d20-84d2-8535dedc7894 |
| Using docker? | true |
| Layout |  |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | sqlite |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first | 2022-01-08 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 Firefox/95.0 |

### Steps to reproduce

1. Create custom transaction link
2. Link a transaction with this newly created transaction link.
3. See the description on the transaction page regarding the linked transactions.

**Comment by JC5** [comment]
Nice find, that's probably a bug. I'll pick it up.

**Comment by DanielNetoP** [comment]
Just updated for the new version and it looks great, thank you 👍
