### ISSUE TITLE
How do i initialize the database?

### ISSUE THREAD

**Issue by nwwy** [firefly-iii/firefly-iii#552]
Since the Docker Tutorial takes a while, i wanted to install firefly-iii the "normal" way.
I have created a database 'fireflyiii' and a user 'fireflyiii' in my mysql server and changed the settings in the .env file.

Now when i try to open https://*****/firefly-iii/public/ i just get the following Errors:

`QueryException in Connection.php line 770:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fireflyiii.configuration' doesn't exist (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)`

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fireflyiii.configuration' doesn't exist`

I thought firefly-iii creates the database tables itself when it has access to the mysql server on the first run. Do i have to create the tables? And is there a .sql dump file that i can import? In the Installation guide was nothing mentioned about this so i think this is not normally the way to do it.

**Comment by JC5** [comment]
I just realized I completely forgot this step in the installation guide. I will update the guide!

On the command line, run:

```bash
php artisan migrate:refresh --seed
```

**Comment by nwwy** [comment]
Thanks for you answer. Now i have the following tables in the mysql database.

`+------------------------------+`
`| Tables_in_fireflyiii         |`
`+------------------------------+`
`| account_meta                 |`
`| account_types                |`
`| accounts                     |`
`| attachments                  |`
`| available_budgets            |`
`| bills                        |`
`| budget_limits                |`
`| budget_transaction           |`
`| budget_transaction_journal   |`
`| budgets                      |`
`| categories                   |`
`| category_transaction         |`
`| category_transaction_journal |`
`| configuration                |`
`| export_jobs                  |`
`| import_jobs                  |`
`| jobs                         |`
`| journal_meta                 |`
`| limit_repetitions            |`
`| migrations                   |`
`| notes                        |`
`| password_resets              |`
`| permission_role              |`
`| permissions                  |`
`| piggy_bank_events            |`
`| piggy_bank_repetitions       |`
`| piggy_banks                  |`
`| preferences                  |`
`| role_user                    |`
`| roles                        |`
`| rule_actions                 |`
`| rule_groups                  |`
`| rule_triggers                |`
`| rules                        |`
`| sessions                     |`
`| tag_transaction_journal      |`
`| tags                         |`
`| transaction_currencies       |`
`| transaction_journals         |`
`| transaction_types            |`
`| transactions                 |`
`| users                        |`
`+------------------------------+`
`42 rows in set (0,00 sec)`


But when i try to go to https://*******/firefly-iii/public/ it redirects me to https://********/firefly-iii/public/login and then i get an 404 Error.

This is the content of my web root and my public folder:

(ssh) flipp@phobos : ~/www/firefly-iii
[0] % ls -l
insgesamt 280
drwxrwxr-x 21 www-data www-data   4096 Jan 30 11:18 app
-rwxr-xr-x  1 www-data www-data   1646 Jan 30 11:18 artisan
drwxrwxr-x  3 www-data www-data   4096 Jan 30 11:18 bootstrap
-rw-rw-r--  1 www-data www-data  13969 Jan 30 11:18 CHANGELOG.md
-rwxr-xr-x  1 www-data www-data   2649 Jan 30 11:18 composer.json
-rw-rw-r--  1 www-data www-data 172362 Jan 30 11:18 composer.lock
drwxrwxr-x  2 www-data www-data   4096 Jan 30 11:18 config
-rw-rw-r--  1 www-data www-data    131 Jan 30 11:18 crowdin.yaml
drwxrwxr-x  5 www-data www-data   4096 Jan 30 11:18 database
drwxrwxr-x  2 www-data www-data   4096 Jan 30 11:18 docker
-rw-rw-r--  1 www-data www-data   2004 Jan 30 11:18 Dockerfile
-rwxr-xr-x  1 www-data www-data    556 Jan 30 11:18 gulpfile.js
-rw-rw-r--  1 www-data www-data    656 Jan 30 11:18 LICENSE
-rwxr-xr-x  1 www-data www-data    400 Jan 30 11:18 package.json
-rwxr-xr-x  1 www-data www-data   1298 Jan 30 11:18 phpunit.coverage.xml
-rwxr-xr-x  1 www-data www-data   1281 Jan 30 11:18 phpunit.xml
drwxrwxr-x  7 www-data www-data   4096 Jan 30 11:18 public
-rw-rw-r--  1 www-data www-data   3096 Jan 30 11:18 README.md
drwxrwxr-x  6 www-data www-data   4096 Jan 30 11:18 resources
drwxrwxr-x  2 www-data www-data   4096 Jan 30 11:18 routes
-rwxr-xr-x  1 www-data www-data    789 Jan 30 11:18 server.php
drwxrwxr-x 10 www-data www-data   4096 Jan 30 11:18 storage
drwxrwxr-x  4 www-data www-data   4096 Jan 30 11:18 tests
-rwxr-xr-x  1 www-data www-data   2515 Jan 30 11:18 test.sh
drwxrwxr-x 31 www-data www-data   4096 Feb  5 11:29 vendor

(ssh) flipp@phobos : ~/www/firefly-iii
[0] % cd public

(ssh) flipp@phobos : ~/www/firefly-iii/public
[0] % l
insgesamt 148K
drwxrwxr-x  7 www-data www-data 4,0K Jan 30 11:18 .
drwxrwxr-x 14 www-data www-data 4,0K Feb  5 12:14 ..
-rw-rw-r--  1 www-data www-data  15K Jan 30 11:18 android-chrome-192x192.png
-rw-rw-r--  1 www-data www-data  32K Jan 30 11:18 android-chrome-512x512.png
-rw-rw-r--  1 www-data www-data  11K Jan 30 11:18 apple-touch-icon.png
-rw-rw-r--  1 www-data www-data  222 Jan 30 11:18 browserconfig.xml
drwxrwxr-x  3 www-data www-data 4,0K Jan 30 11:18 css
-rw-rw-r--  1 www-data www-data 1,5K Jan 30 11:18 favicon-16x16.png
-rw-rw-r--  1 www-data www-data 2,3K Jan 30 11:18 favicon-32x32.png
-rw-rw-r--  1 www-data www-data  15K Jan 30 11:18 favicon.ico
drwxrwxr-x  2 www-data www-data 4,0K Jan 30 11:18 fonts
-rwxr-xr-x  1 www-data www-data  553 Jan 30 11:18 .htaccess
drwxrwxr-x  2 www-data www-data 4,0K Jan 30 11:18 images
-rw-rw-r--  1 www-data www-data 1,9K Jan 30 11:18 index.php
drwxrwxr-x  4 www-data www-data 4,0K Jan 30 11:18 js
drwxrwxr-x  5 www-data www-data 4,0K Jan 30 11:18 lib
-rw-rw-r--  1 www-data www-data  395 Jan 30 11:18 manifest.json
-rw-rw-r--  1 www-data www-data  11K Jan 30 11:18 mstile-150x150.png
-rw-rw-r--  1 www-data www-data   25 Jan 30 11:18 robots.txt
-rw-rw-r--  1 www-data www-data 3,2K Jan 30 11:18 safari-pinned-tab.svg

**Comment by JC5** [comment]
Did you change AllowOverride None to AllowOverride All?

If you did, run these commands:

```
sudo a2enmod rewrite
sudo service apache2 restart
```

**Comment by nwwy** [comment]
Im running nginx so i skipped the apache steps.

**Comment by JC5** [comment]
Ok good. How is your config compared to [the example one](https://firefly-iii.github.io/static/nginx.txt)?

**Comment by nwwy** [comment]
Not so much different i think. Just a little bit more with the SSL Stuff.
http://pastebin.com/ZS6U1zhM

**Comment by JC5** [comment]
Make sure it is like this:

```
try_files $uri $uri/ /index.php$is_args$args;
```

**Comment by nwwy** [comment]
Tried it, still 404 on the public/login redirect. I guess i wait for the docker container. :D

**Comment by JC5** [comment]
That's very strange. Do the other relevant things match as well? Because if they do, I have no idea why it would 404 :(

**Comment by nwwy** [comment]
I am using this now, and still get a 404. Error. Hmmm really strange .... :/

	server {
	        listen 80;
	        root /var/www/html;
	        index index.php;

	        server_name mydomain.de;

	        location / {
	                try_files $uri $uri/ /index.php$is_args$args;
	        }

	        client_max_body_size 300M;

	    location ~ \.php$ {
	            try_files $uri =404;
	            fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
	            fastcgi_index index.php;
	            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	            include fastcgi_params;
	    }

	        location ~ /\.ht {
	                deny all;
	        }
	        location ~ /\.git {
	                deny all;
	        }
	}

**Comment by JC5** [comment]
Try to move the root to firefly-iii/public, just to see what happens. I think the `/index.php` does not work because of that.

I just noticed my dev server has a different "location /":

```
	location / {
        try_files $uri $uri/ /index.php?$query_string;
        autoindex on;
        sendfile off;
	}
```

But it might only work when you move the root.

**Comment by nwwy** [comment]
Even with this one i get an 404 Error. I think i try to delete the firefly-iii folder and install everything again. maybe something went wrong during the composer setup.

    server {
            listen 80;
            root /var/www/html/firefily-iii/public;
            index index.php;

            server_name mydomain.de;

            location / {
                try_files $uri $uri/ /index.php?$query_string;
                autoindex on;
                sendfile off;
            }

            client_max_body_size 300M;

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }

            location ~ /\.ht {
                    deny all;
            }
            location ~ /\.git {
                    deny all;
            }
    }

**Comment by JC5** [comment]
Strange, strange! I'm glad it works now. Let me know if I can do anything else for you!

**Comment by nwwy** [comment]
It works, but only if i point the root directory to `/var/www/html/firefly-iii/public` wich is not an option. I tried to merge the configs but i just wont work from a subdirectory. I think i have to use another domain, where i can use it from a subdomain or a spare domain i have. Thanks for your help and your great project. :)

**Comment by JC5** [comment]
Try this. Copy this part:

```
        location / {
            try_files $uri $uri/ /index.php?$query_string;
            autoindex on;
            sendfile off;
        }
```
and change it to this
```
        location /firefly-iii/public {
            try_files $uri $uri/ /index.php?$query_string;
            autoindex on;
            sendfile off;
        }
```

Maybe you have to change the `/index.php` to `/firefly-iii/public/index.php`

**Comment by nwwy** [comment]
I already tried it and im at 404 again. Here is my not working config right now.

    server {
            listen 80 default_server;
            listen [::]:80 default_server;

            # Follow Symlinks
            disable_symlinks off;

            server_name mydomain.de;
            return 301 https://$server_name$request_uri;

    }

    server {
            root /var/www/html;

            listen 443 ssl http2 default_server;
            listen [::]:443 ssl http2 default_server;
            include snippets/ssl-dyn.conf;
            include snippets/ssl-params.conf;

            # Lets Encrypt Check
            # https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
            location ~ /.well-known {
                    allow all;
            }

            charset utf-8;

            # Add index.php to the list if you are using PHP
            index index.html index.htm index.nginx-debian.html index.php;

            location / {
                    # First attempt to serve request as file, then
                    # as directory, then fall back to displaying a 404.
                    #try_files $uri $uri/ =404;
                    try_files $uri $uri/ /index.php$is_args$args;
            }

            location /firefly-iii/public {
                try_files $uri $uri/ /index.php?$query_string;
                autoindex on;
                sendfile off;
        }

        client_max_body_size 300M;

            # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
            #
            location ~ \.php$ {
                    include snippets/fastcgi-php.conf;
            #
            #       # With php7.0-cgi alone:
            #       fastcgi_pass 127.0.0.1:9000;
            #       # With php7.0-fpm:
                    fastcgi_pass unix:/run/php/php7.0-fpm.sock;
                    #try_files $uri =404;
                    #fastcgi_index index.php;
                    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                    include fastcgi_params;
            }

            # deny access to .htaccess files, if Apache's document root
            # concurs with nginx's one
            #
            location ~ /\.ht {
                    deny all;
            }


            location /firefly-iii/.env {
                    deny all;
            }
    }

**Comment by JC5** [comment]
Woohoo! :D

**Comment by nwwy** [comment]
Ok, found a little bug after testing it a few minutes.

After registering my test account and entering values for the initial accounts, i wanted to edit the "Opening balance" Field and it wont let me cause the Account Role is invalid.

http://i.imgur.com/3R8yiLP.png

It happens too when i select any other value from the dropdown menue.

Initaly i wanted to just change the Name from "Haushalt savings account" to "Sparbuch" and the opening balance to something else.

Its no Problem, i just delete the account and enter the real value we have in our savings account on the first startup.

**Comment by t-me** [comment]
@nwwy see this  commit [b0d93621a8538867ab1cd500ce76361c5396b56b ](https://github.com/firefly-iii/firefly-iii/commit/b0d93621a8538867ab1cd500ce76361c5396b56b ) that will fix your problem.

**Comment by nwwy** [comment]
Thank you very much =)

**Comment by JC5** [comment]
Yes, I believe that fix is already live, in version 4.3.4

**Comment by nwwy** [comment]
When i reinstalled with `composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist --no-suggest` i had to edit the change by hand to get it working. I have Version 4.3.3 installed right now. So its not the latest version with composer.

**Comment by JC5** [comment]
Packagist often forgets to update the pointer to the latest version. I have to remember to to it manually.

I've just told it to update so it should be on 4.3.4 now. The upgrade routine is on the website but it's pretty straight forward: just install it (in a different directory) and [move over some stuff](https://firefly-iii.github.io/upgrade-guide/).

**Comment by nwwy** [comment]
Upgrade worked. Some minor things to improve in the guide are:
* `cd ..` after `php artisan firefly:upgrade-database` and before `mv firefly-iii firefly-iii-old` cause when you do it step by step you are still in the firefly-iii directory.
* And it gives a Error 500 cause i dosent belong to www-data if you upgrade with another user account so this here is missing at the end.
    * `sudo chown -R www-data:www-data /var/www/firefly-iii`
    * `sudo chmod -R 775 /var/www/firefly-iii/storage`

**Comment by JC5** [comment]
I will update the guide, thank you for this!
