### ISSUE TITLE
[data importer] add log for get account api call results

### ISSUE THREAD

**Issue by vabene1111** [firefly-iii/firefly-iii#5529]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

i had an issue with the spectre importer and you pointed me to the logs where i could see the transaction api results. Today nordigen added support for DKB and i tried out their importer, sadly no accounts were shown. 

I went to the logs and saw the following output 

```
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Now in App\Http\Controllers\Import\ConfigurationController::getNordigenAccounts  
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Now at App\Services\Nordigen\TokenManager::getAccessToken  
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens  
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Nordigen token is valid until 2022-01-13 16:31:10  
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Nordigen token is valid.  
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Request parameters will be set to:   
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: authenticatedGet(https://ob.nordigen.com/api/v2/requisitions/<REDACTED>
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Return JSON result of authenticatedGet  
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Found 0 accounts.  
fireflyiii_import_1  | [2022-01-12 16:31:37] local.DEBUG: Now creating Nordigen account lists
```

after that i tested DKB on nordigens website and it was broken there as well, but maybe it would help to analyze future problems if the API result of the get accounts api would also be logged. Or maybe a warning could be shown on the UI if no accounts were found :thinking: 

### Solution

add log message or UI hint

### What are alternatives?

This is definitely only a minor low priority thing, you can always manually go to nordigen/sepctre and test the apis

**Comment by JC5** [comment]
No problem, I can add something like it. Let me write it down as a bug so I can give it some prio. Thanks for the suggestion!

**Comment by JC5** [comment]
What's missing from the logs is the least interesting part, the identifiers. Nevertheless, they'll be logged now.
