### ISSUE TITLE
Documentation missing around IMPORT_DIR_WHITELIST for importer and Nordigen Tokens

### ISSUE THREAD

**Issue by dabeeeenster** [firefly-iii/firefly-iii#5534]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

First up - thanks for the Nordigen work - it's amazing and means I can automate seemingly everything in terms of importing transactions. Great work 🎉

I got tripped up on a couple of things. 

Firstly, I used to auto import csv files with the docker importer. I had to add `-e IMPORT_DIR_WHITELIST=/import` to my `docker run` command which took some searching and looking in the code. This should be added to the docs somewhere? 

Secondly, I'm not sure what happens if/when my Nordigen tokens expire. It looks like they are good for 90 days - what happens after that? I have been running the importer with the following:

```
docker run \
      --rm -e FIREFLY_III_ACCESS_TOKEN=xxx \
      -e FIREFLY_III_URL=https://xxx \
      -e WEB_SERVER=false \
      -e NORDIGEN_ID=XXXXXXX \
      -e NORDIGEN_KEY=XXXXXX \
      -v $PWD:/import \
      -e IMPORT_DIR_WHITELIST=/import \
    fireflyiii/data-importer:develop
```

And this is working perfectly, but I'm not sure what the process would be after the tokens expire. Do I have to go through and regenerate all of the config files for each account? Again it would be great if this was in the docs

### Expected behaviour

More documentation about the above

### Debug information

There werent any errors in the process

### Steps to reproduce

- Create Nordigen Account
- Start web importer
- Go through auth flow for an account and save the config
- Run the config via docker without the web server running

**Comment by JC5** [comment]
I've made sure the documentation is updated.

As for the second point, I'm just not sure. I can't fake it through the sandbox. The Data Importer will fail gracefully but I don't know how Nordigen will report back. We'll have to wait it out together.

**Comment by dabeeeenster** [comment]
Awesome thanks @JC5 - the Nordigen-backed importer is amazing! Just a shame I'm assuming we will have to refresh all the tokens, but I guess that's part of the open banking spec...
