### ISSUE TITLE
Data importer with CSV file fails

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#5541]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I try to import a CSV file that works with CSV importer 2.6.1, with the same configuration. Now when I run it, every line shows an error, despite the transactions being fine. This is the message: Line #0: transactions.0.description: Internal exception: Created zero transaction journals. ...

### Expected behaviour

The transactions to be imported (or detected as duplicate) properly.

### Debug information

This is the error from the data importer logs:
```
production.ERROR: Submission error: 0 ["Internal exception: Created zero transaction journals."] 
```

I also see this:
```
production.DEBUG: Group is empty, may not have been stored correctly.
```

This is what I see in Firefly:
```
today at 21:53:06[2022-01-14 21:53:06] local.WARNING: Not a valid source. Need more data.  
today at 21:53:06[2022-01-14 21:53:06] local.ERROR: Could not validate source or destination.  
today at 21:53:06[2022-01-14 21:53:06] local.ERROR: Source: Need to get a valid source account ID and/or valid source account name to continue.  
today at 21:53:06[2022-01-14 21:53:06] local.ERROR: The createJournal() method returned NULL. This may indicate an error.  
today at 21:53:06[2022-01-14 21:53:06] local.WARNING: Group repository caught group factory with an exception!  
today at 21:53:06[2022-01-14 21:53:06] local.ERROR: Created zero transaction journals.  
today at 21:53:06[2022-01-14 21:53:06] local.ERROR: #0 /var/www/html/app/Repositories/TransactionGroup/TransactionGroupRepository.php(362): FireflyIII\Factory\TransactionGroupFactory->create()
today at 21:53:06#1 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(94): FireflyIII\Repositories\TransactionGroup\TransactionGroupRepository->store()
today at 21:53:06#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->store()
today at 21:53:06#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
today at 21:53:06#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
```

**Comment by JC5** [comment]
Thanks for the Firefly III logs.

Does the line before say `Now in validateWithdrawalSource` or `Now in validateGenericSource`? Or neither?

Either way, it seems that the source of the transaction is invalid; both the ID and the name submitted evaluate to NULL. At that point (run Firefly III with [debug mode](https://docs.firefly-iii.org/firefly-iii/faq/other/#how-do-i-enable-debug-mode) on for more information) Firefly III can't find or validate the source account. The source account cannot be created so it'll fail and throw an exception.

This is surprising because the default account from your configuration is usually enough to prevent this.

If you would, send me one or two uncensored lines and your configuration at james@firefly-iii.org and I'll see if I can replicate it.

**Comment by daften** [comment]
I'll have to check the logs again, cause the container was automatically recreated on saturday night after my issue was created (watchtower updated it to 0.6.5). I'll check next import I do.

I'll send some data next time I do an import in firefly too!

**Comment by JC5** [comment]
The log line I mention would be coming from Firefly III, so it might still be there. Either way, curious to see some examples!

**Comment by daften** [comment]
I had the mail ready expecting the import to fail, but for my freelance account it works, I didn't need to import with my personal account, will do that this weekend at the latest normally. If that works, I'll close this issue.

**Comment by JC5** [comment]
Any news on this one?

**Comment by daften** [comment]
@JC5  Just tried and it worked perfectly now. Very weird, I swear it failed two weeks ago, but no issue no, so I'll close this one. Sorry for the inconvenience!

**Comment by JC5** [comment]
Not an inconvenience at all, glad to hear it works!

**Comment by daften** [comment]
Just figured out why it failed. If there's a revenue or expense account with the same IBAN, I get the errors. I think I cleaned up my accounts for myself, and not for my wife, so I got it on her import now. So it's easy to fix, but at some point I think those were created by imports through the old CSV importer.
