### ISSUE TITLE
Docker image - Error 500 sqlite database not found

### ISSUE THREAD

**Issue by alexbelgium** [firefly-iii/firefly-iii#5542]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm running the dockerhub firefly/core:latest image using sqlite with fireflyiii.
All initialization goes well, and the sqlite database populates based on the app initialization.
I've run the requested code which runs without issues :
```
touch ./storage/database/database.sqlite
php artisan migrate --seed
php artisan firefly-iii:upgrade-database
```
However, there is an Error 500 on webui with a message that the sqlite database does not exist.

### Expected behaviour

App working

### Debug information
App log: attached
[log.txt](https://github.com/firefly-iii/firefly-iii/files/7874750/log.txt)

Files: 
/config/addons_config/fireflyiii/database/database.sqlite exists with owner www-data:www-data and chmod 777
[database.sqlite.zip](https://github.com/firefly-iii/firefly-iii/files/7874785/database.sqlite.zip)

Env. values :
All defaults of the official fireflyiii/core:latest images with the addition of 
TRUSTED_PROXIES="**"
DB_CONNECTION=sqlite
APP_KEY="CHANGEME_32_CHARS_EuC5dfn3LAPzeO"

Webui :
>  Whoops! An error occurred.
> Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:
> Could not poll the database: Database (/config/addons_config/fireflyiii/database/database.sqlite) does not exist. (SQL: select "id", "name", "data" from "configuration" where "name" = is_demo_site and "configuration"."deleted_at" is null limit 1)

### Additional info

I'm running it through an addon that I have made for Home Assistant here : https://github.com/alexbelgium/hassio-addons/tree/master/fireflyiii

**Comment by JC5** [comment]
In your logs, the error is this:

```
[2022-01-15 11:25:37] local.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"Could not poll the database: Database (\/var\/www\/html\/storage\/database\/database.sqlite) does not exist. (SQL: select \"id\", \"name\", \"data\" from \"configuration\" where \"name\" = is_demo_site and \"configuration\".\"deleted_at\" is null limit 1)","time":"Sat, 15 Jan 2022 11:25:37 +0100","file":"\/var\/www\/html\/app\/Support\/FireflyConfig.php","line":73,"code":0,"version":"5.6.10","url":"http:\/\/192.168.178.23:3473","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/97.0.4692.71 Safari\/537.36 Edg\/97.0.1072.62","json":true}  

```

Could that be the problem? 

I can't tell from the add-on where you mount `/config/addons_config/fireflyiii/` and where you mount it to. But that's my inexperience. Could it be it's mounted in the wrong place?

**Comment by alexbelgium** [comment]
I'm sure the path is correct, as firefly correctly touches the database, and initializes it in the previous steps... When I log on the container using portainer, ln -s /config/addons_config/fireflyiii shows that the database is accessible from within the container, with owner www-data:www-data and chmod 777... So the database seems available, as the knit steps work! I really don't understand what happens

**Comment by JC5** [comment]
I see that. But `ln -s /config/addons_config/fireflyiii` doesn't prove anything to me. `bash` into the container and go to `/var/www/html/storage/database`. That's where the database file is expected to be.

After the init step, is the container destroyed or recreated using a different command?

**Comment by JC5** [comment]
I'm running HA myself btw, is the current branch in your repo testeable?

**Comment by alexbelgium** [comment]
Yes! When I initially wrote the addon a couple weeks ago, I had 3 working ways to connect : mariadb addon autodiscovery, sqlite and external database. With the current version in my repo, sqlite gives me error 500 but the other connection methods were confirmed to work by other users.

Thanks very much!

**Comment by alexbelgium** [comment]
> I see that. But `ln -s /config/addons_config/fireflyiii` doesn't prove anything to me. `bash` into the container and go to `/var/www/html/storage/database`. That's where the database file is expected to be.
> 
> After the init step, is the container destroyed or recreated using a different command?

The init step is part of my launch script (https://github.com/alexbelgium/hassio-addons/blob/master/fireflyiii/rootfs/etc/cont-init.d/99-run.sh#L119) : 
```bash
# Install database
bashio::log.info "Updating database"
php artisan migrate --seed
php artisan firefly-iii:upgrade-database

bashio::log.info "Please wait while the app is loading !"

/./usr/local/bin/entrypoint.sh
```

For the database location, i had used "export DB_DATABASE=/config/addons_config/fireflyiii/database/database.sqlite" to force it to use the addon true location. My normal code gives the same error but makes a symlink with the normal directory (https://github.com/alexbelgium/hassio-addons/blob/468b99032ecd960e7700cc43b809b4547d6e3ba1/fireflyiii/rootfs/etc/cont-init.d/99-run.sh#L40): 
```bash
    export DB_CONNECTION=sqlite
    #export DB_DATABASE=/config/addons_config/fireflyiii/database/database.sqlite
    # Creating database
    mkdir -p /config/addons_config/fireflyiii/database
    rm -r /var/www/html/storage/database
    ln -snf /config/addons_config/fireflyiii/database /var/www/html/storage
    chown -R www-data:www-data /config/addons_config/fireflyiii
    chown -R www-data:www-data /var/www/html/storage
    chmod -R 777 /var/www/html/storage/database
    touch /var/www/html/storage/database/database.sqlite
```

**Comment by JC5** [comment]
I think that if you call entrypoint.sh none of the env variables are transferred. Could you try something like `sh entrypoint.sh` or `DB_DATABASE=/bla entrypoint.sh`?

**Comment by alexbelgium** [comment]
Thanks for your support, I'll continue investigating. 

I tried your suggestions and it did not work, so I've reverted my code to a moment where it _did_ work several weeks ago, and am trying to re-add my code element by element to see at which point it started to fail... I'll close the issue as it comes from my addon implementation and not your app itself. If I pinpoint the issue I'll post it in this thread if it can help other people in the future.

Btw, you have developed an incredible app, congratulations and thanks very much !!!

**Comment by JC5** [comment]
No problem, let me know if I can help. I might be able to detect or report these issues from entrypoint.sh, making future debugging easier.

**Comment by JC5** [comment]
> Btw, you have developed an incredible app, congratulations and thanks very much !!!

Thank you! Much appreciated 😄

**Comment by alexbelgium** [comment]
Thanks ! 

I've continued to explore, and the addon is now working as expected with sqlite when I install the addon on one machine (VM on amd64) but still fails with the same error of "database not found" on another (rpi4 with armv8).

The addon is the same on both machines, installed directly from my repo. On both machines, the database.sqlite can be seen at the right location, as seen by going in the container with portainer and doing "ls -l /var/www/html/storage/database". The issue starts when I symlinked the storage folders. I think the issue is probably with parents directories permissions, I'll continue investigating.

On HA os, I need to symlink the storage directory, as only /config, /share, /media and /data can be made persistent, and HA doesn't accept easily custom mapping of docker volumes.

I'll note here when I'll find the final cause for this error :)

**Comment by alexbelgium** [comment]
Ok I've got it.
I was symlinking : /config/addons_config/fireflyiii/database to /var/www/html/storage/database.
                                          |                        |> /fireflyiii/database was correctly chmodded to 755
                                          |> but not /addons_config

When I chmodded 755 to /addons_config, the "database not found" error disappeared !

Thanks for your support :-)

**Comment by JC5** [comment]
No problem, glad to hear you found it!
