### ISSUE TITLE
file_put_contents ... Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by phil4096** [firefly-iii/firefly-iii#5546]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Adding a new tag to existing recurring transaction - no other changes.  Crashed with 500 error
_file_put_contents(/var/www/html/firefly/storage/framework/cache/data/22/85/22858964d1bbd942377a23a29d9f167a0beea4dc): Failed to open stream: No such file or directory_
which is true, as directory 85 does not exist inside directory 22.

### Expected behaviour

Expected to update the data and continue.

### Debug information

Debug information generated at 2022-01-16 14:05:51 Europe/London for Firefly III version **5.6.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.10 |
| Firefly III API | 1.5.5 |
| Build | (unknown), (unknown) |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 17615147-32f7-412f-a755-b69f5f1059f7 |
| Using docker? | false |
| Layout | v1 |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_GB |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 |

### Steps to reproduce

1. create a recurring transaction
2. create a tag
3. edit the above transaction to add the tag (no other tags present)
4. click Save button.
I cannot now get into the system to try it again - get the same error page after login.

### Additional info

Seems to work ok on demo system, but I did also have to add a transaction description for it to save.
I can no longer use the system - I just get the same error after login (with cleared cookies).

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/faq/self_hosted/#unable-to-write-to-cache-directory
