### ISSUE TITLE
SQL error in transactions section

### ISSUE THREAD

**Issue by roliveira2015** [firefly-iii/firefly-iii#555]
Going in the Transactions->Withdrawals or Transactions->Deposit menu on left, it gives me this SQL error three times:

```
PDOException in PDOStatement.php line 91:

SQLSTATE[42000]: Syntax error or access violation: 1104 The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay
```

Transfers section is working, though.

I'm not sure if this is a problem with any mySql config in my server, or this is somenthing in the code itself.

I'm using version 4.3.2

Thanks!

**Comment by JC5** [comment]
The mysql server you use is set too conservatively. I suggest searching the web for the two suggested configuration settings, and changing either of them. 

The queries are big, but they are not impossible to handle.
