### ISSUE TITLE
Commas and dots not visible

### ISSUE THREAD

**Issue by tonylemeunier** [firefly-iii/firefly-iii#556]
Hi,

I have installed last firefly-iii version with no problem.

Unfortunetly once connected on the front page and configured first account and his balance, no commas and dots appears on any numbers. 

Let's see for 7,923.61 € :
<img width="536" alt="capture d ecran 2017-02-09 a 21 42 36" src="https://cloud.githubusercontent.com/assets/21359472/22802353/c320a0c0-ef10-11e6-9f93-7b0184b2fad3.png">

What I did wrong ?

Best regards,
Tony.

**Comment by JC5** [comment]
https://firefly-iii.github.io/installation-guide-faq/

It's probably a missing language pack :)

**Comment by tonylemeunier** [comment]
Thanks a lot it's working !
Nice job for the app ;)

Best Regards,
