### ISSUE TITLE
[FIDI] Import additionalInformation field

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#5570]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I'm using latest develop FIDI version with latest stable version of FFIII. I noticed today my bank fee to have taken cash (0.5€) have not been identified by my rules when imported via Nordigen as previously when I was importing with a CSV.

When looking into the transaction I see the field remittanceInformationUnstructured is used for the description of the transaction and additionalInformation does contain the information about the type of transaction (like contactless payment, bancontact, fee for the cash etc...).

Would it be possible to map this field additionalInformation to the notes of the created transaction?

### Solution

Map this field additionalInformation to the notes of the created transaction

**Comment by MacPaille** [comment]
In fact after checking my rules it's just the destination account that was set to (unknown destination account) instead of my previous (no name).
But anyway I checked and I was mapping that additional info field to the notes in my CSV config file. Which I think should be the default also for the Nordigen (maybe Spectre too) imports

**Comment by JC5** [comment]
Could you send me an example at james@firefly-iii.org?

**Comment by MacPaille** [comment]
Mail sent

**Comment by JC5** [comment]
Appreciate it, will be done!

**Comment by MacPaille** [comment]
Thanks!

**Comment by JC5** [comment]
The `develop` tag should support this, let me know your feedback.

**Comment by MacPaille** [comment]
Thanks for the quick fix! I'll tell you tonight after my automatic import has run.

**Comment by JC5** [comment]
There's a good chance you will run into duplicates, keep that in mind.

**Comment by MacPaille** [comment]
I know I did not delete the previous transaction. But it seems my bank add that additionalinfo field to all trnsactions. So I'll see the new ones imported tonight if the notes are populated correctly.

**Comment by MacPaille** [comment]
I confirm it did work fine. It imported again all my last 15 days transactions as now it has more data with the note. I cleaned the duplicates.

Thanks!
