### ISSUE TITLE
Setting an opening balance > 0 without date omits it silently

### ISSUE THREAD

**Issue by elamperti** [firefly-iii/firefly-iii#559]
If a new account is opened with an opening balance > 0 and the date is left undefined, the account is created successfully but the opening balance is silently omitted. There's no warning nor error, so it may go unnoticed. 

Is confusing too, as when I went to change the opening balance after creating the account I didn't read the other fields and tried just setting it and saving (which didn't work and it wasn't obvious why).

**Comment by JC5** [comment]
Yes, it is. Good find. The idea is that both are necessary. A warning of some sorts should be implemented. I'll get right on it.

**Comment by JC5** [comment]
Fixed! Will be live in the next release.

**Comment by elamperti** [comment]
@JC5 awesome! Thank you :blush:
