### ISSUE TITLE
Rules - Reorder groups by "Drag & Drop"

### ISSUE THREAD

**Issue by top-cg** [firefly-iii/firefly-iii#5591]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello,
It is possible to reorder rules inside a Group using a "drag & drop", but this is not possible to reorder groups by "drag & drop".
The only actual option is using the menu > move up / down.
I'm currently running 12 groups ... translating in maximum of 24 actions to move a group from the last position (default place when created) to the top.

### Solution

Add the ability to reorder by drag & drop directly on the page /rules.

To check if "option 2" is not better on the long run as group location seems to be more likely to be needed on creation.

### What are alternatives?

As the main page contains already a drag & drop for rules, this is maybe complex to add a drag & drop for groups.

A solution is to manage the position inside a group options menu (/rule-groups/edit/00).

**Option 1 (drag & drop)** 
Adding inside the menu of a group (/rule-groups/edit/00), the list of the groups with the ability to drag & drop. I have a doubt this will work in the creation menu (adding a future rule in a list of existing rule + ability to move things seems complex).

**Option 2 (new option of groups - bomb proof?)**
Inside the menu of a group (/rule-groups/edit/00), add a filed-name "set position after" and a field-value to enter or select a "group name". The group being edited with be placed, based on "set position after". 
It should also work in the menu (/rule-groups/create) but a default position will have to be set (last ? frist ?).
Downside ... if you want to have the group placed "first", you still have to use the "up / down" but this time limited to a max of 2 actions (menu > up). 
As moving groups is not super common, this is maybe the most efficient solution. 

### Additional context

Version used : 5.6.10

not related but seems to be the only "drag + rules" existing subjects :
[https://github.com/firefly-iii/firefly-iii/issues/4042](url)
[https://github.com/firefly-iii/firefly-iii/issues/3440](url)

**Comment by JC5** [comment]
I'm not going to add drag and drop to rule groups in this layout.
