### ISSUE TITLE
Rules - Rules history storage & transaction menu udpate

### ISSUE THREAD

**Issue by top-cg** [firefly-iii/firefly-iii#5592]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Reading [https://github.com/firefly-iii/firefly-iii/issues/5059](url) it make me realized how much i'm missing an audit track of the rules actions. I'm still in the 1st setup of the app, so i have still in my head more or less all the rules i set and understanding an error stays still easy ... but in 1 year not sure ... and tracking an error will be hard. 

And i'm saying easy but i'm currently trying to deal with transfers with the bank modifying the description on the sender account ... and this is so complex to manage across all my accounts i was obliged to set my own audit track using flags. It works but this is not easy at all to manage and if i'm starting to use it on a large scale, it will pollute my tag list.

So may i suggest to store the "rules history" and to provide access to such data in the transactions details ?

### Solution

Inside a transaction menu : /transactions/show/332

- Add a bloc named "Rules history"
- List all rules actions
- Ordered by date (yyyy.mm.dd - hh:mm:ss)
- For each action, provides the rule code (/rules/edit/**83**) and if possible it is name + link access the rule edition menu

I suppose it is possible to create a table in the DB storing all of that and associate:
- date (yyyy.mm.dd - hh:mm:ss)
- rule code (/rules/edit/83)
- transaction code (/transactions/show/332)

Having such data in hands can offer plenty of order options ... link a new menu / report : audit of rules and could have us a journal listing everything ...

Imagine what you can do with ...

transaction 332 was modified by rule 83 at 2022.01.23 08:38:46
transaction 332 was modified by rule 13 at 2022.01.23 08:38:46
transaction 405 was modified by rule 28 at 2022.01.23 08:38:46
transaction 154 was modified by rule 11 at 2022.01.23 08:38:46
 
Yeap ... you added a new rule (83) but an old rule (13) is passing behind crushing to effort to zero.

If created, better to offer a button to erase "rules history" (/profile/ delete data) or to locate this history in a table of the DB we can clear as running the early testing phases running rules many time is common.

**Comment by JC5** [comment]
> and this is so complex to manage across all my accounts

This is the problem. I will happily put "audit history" on the roadmap, but this is the problem. If you're less anal about getting all your transactions perfect the problem disappears.

**Comment by top-cg** [comment]
Thanks the answer.

To deal with my current problem (transfers) flags are making the job (i wish i will have discover that before ! this is very nice to have on initial debug) ... and to solve my issue in the future, i will have a "code" in the bank transfer giving me the destination account (as the source is known). The only part here i refuse to automate is the final step : delete the transaction is the destination account now in double with the transfer generated by changing the Withdrawal into a Transfer. Tags will help me to check the transfer is correct before deleting by hand.

The audit history is something else ... 

I'm seeing it as the long run helper ... after few months / years in the software, i don't think i will add new rules. Maybe i will update some (new supermarket, new store, ...) but not anymore creating complex stuff (like dealing with transfers). So the audit history is much more a reply to : dam' why adding "AVIA" to the rule dealing "fuel" is sending the transaction is salary ! This one is true story ... my wife company name contains "avia" and the rule pass after. This one can't be solved ... so i just added a flag "to review".

**Comment by JC5** [comment]
5.8.0 will show you audit log entries for rules. It may not be enough to restore the transaction to the before/after state, but you get a pretty good idea of what happened.

**Comment by top-cg** [comment]
> 5.8.0 will show you audit log entries for rules. It may not be enough to restore the transaction to the before/after state, but you get a pretty good idea of what happened.

Oh my goodness ... 
Thanks a lot man !
