### ISSUE TITLE
Rules - Position in the Rules page is lost after editing a rule

### ISSUE THREAD

**Issue by top-cg** [firefly-iii/firefly-iii#5593]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If you update a rule (ie. you were on the page rules (/rules) and opened a rule to edit it (/rules/edit/83), once the edition is finished, you are always ending on the top of the page rules (/rules).

When you have a long list of the rules, this can be annoying.

This issue linked to the one detailed in https://github.com/firefly-iii/firefly-iii/issues/3440. The position in the page /rules is not retained.

This is maybe linked to the "Success! Updated rule with title " message which is disclosed on the top of the page (forcing the navigator to go back on top ?)

### Expected behaviour

- After editing a rule
- When coming back in the /rules page
- Having the page position set on the edited rule position

### Debug information

n/a

### Steps to reproduce

1. open /rules
2. edit a rule (/rules/edit/83) with "Return here" not checked
3. save the changes
4. check if you came back on the top of /rules or if you can back to the position of the rule you edited

### Additional info

version : 5.6.10

**Comment by JC5** [comment]
Open the edit screen in a new tab instead.

**Comment by top-cg** [comment]
This is working solution.
Closed.
Thanks.
