### ISSUE TITLE
Missing enum types in API Schema

### ISSUE THREAD

**Issue by jafin** [firefly-iii/firefly-iii#5600]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

OpenAPI YML is missing some enums

The RuleTrigger Type is missing types in the OpenApi schema
- source_account_is
- destination_account_is
- source_account_starts

The RuleAction type is missing:
- delete_transaction

### Expected behaviour

YAML should have complete list of enums

### Debug information

N/A

### Steps to reproduce

Generate OpenAPI Client using YML from 1.5.4 schema @ https://api-docs.firefly-iii.org/
Notice that some of the types are missing.

### Additional info

PR relates to https://github.com/firefly-iii/api-docs-generator/pull/38

**Comment by JC5** [comment]
Thanks, I've merged them and I'll regenerate the logs. That was due anyway.
