### ISSUE TITLE
Search operators for `external_url` field

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#5606]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be helpful to be able to search for transactions by `external_url`. In particular, I'd like to be able to filter for transactions with a blank `external_url` as part of an import tool.

### Solution

A search operator similar to the `no_notes:true` operator would be very helpful.

**Comment by JC5** [comment]
- https://github.com/firefly-iii/firefly-iii/issues/5326
- https://github.com/firefly-iii/firefly-iii/issues/4903
