### ISSUE TITLE
Support `external_url` in `transaction` API

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#5607]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

The `transaction` API spec does not appear to support the `external_url` field. This would be helpful for integrations that augment transactions by linking them to external invoices & information pages.

### Solution

Support `external_url` in `TransactionSplit` & `TransactionSplitUpdate` API models

**Comment by JC5** [comment]
It's not in the spec or it's not supported at all?

**Comment by GeorgeHahn** [comment]
I did a quick test on the transaction update API and this looked like it's not supported.

**Comment by JC5** [comment]
Thanks, I'll pick it up!

**Comment by JC5** [comment]
`external_url` should work on the demo, and the API docs include the field (see repos).

5.6.11 will be released soon-ish to make sure all these fixes make it to everybody.

**Comment by GeorgeHahn** [comment]
LGTM on the demo. Thanks!
