### ISSUE TITLE
API: TransactionStore account ID nullability

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#5609]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The `TransactionStore` model marks `source_id` and `destination_id` as nullable, yet they are both required fields. This causes generated APIs to mark them as optional (depending on the language).

### Expected behaviour

Expected required IDs to be non-nullable for better client codegen

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.10 |
| Firefly III API | 1.5.5 |
| Build | 75, 09-01-2022 08:36:35 CET |

### Additional info

I'm happy to PR this change if you confirm it's correct.

**Comment by JC5** [comment]
Nice find. I've removed them from the list of required fields, although the API will fail if you omit either or both, depending on the transaction type.

**Comment by GeorgeHahn** [comment]
Awesome, thank you!
