### ISSUE TITLE
API: Updating transaction with invalid splits appears to delete the transaction

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#5610]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Submitting a transaction update that splits the transaction but omits source & destination IDs for the splits returns a success code and appears to delete the transaction.

### Expected behaviour

The API should return a validation error

### Debug information

Ran on https://demo.firefly-iii.org/

### Steps to reproduce

1. Create a non-split transaction (manually or via the API).
2. Issue an API request to update the transaction and add splits. The splits should contain description and amount but lack source and destination IDs.
3. Note that the API response indicates success.
3. Observe that the transaction is no longer visible in the transaction list.

I can provide Rust sample code for this if desired.

**Comment by JC5** [comment]
That could be a bug. If you have the JSON, I'd be much obliged.

**Comment by GeorgeHahn** [comment]
Totally! My original investigation was somewhat incorrect. The `PUT` to update the transaction does fail, but the transaction then disappears.

<details>
  <summary>Original transaction</summary>
  
```
{
	"data": {
		"type": "transactions",
		"id": "463",
		"attributes": {
			"created_at": "2022-01-24T06:27:16+01:00",
			"updated_at": "2022-01-24T06:27:16+01:00",
			"user": "1",
			"group_title": null,
			"transactions": [{
				"user": "1",
				"transaction_journal_id": "468",
				"type": "withdrawal",
				"date": "2022-01-24T06:27:16+01:00",
				"order": 0,
				"currency_id": "1",
				"currency_code": "EUR",
				"currency_name": "Euro",
				"currency_symbol": "\u20ac",
				"currency_decimal_places": 2,
				"foreign_currency_id": "0",
				"foreign_currency_code": null,
				"foreign_currency_symbol": null,
				"foreign_currency_decimal_places": 0,
				"amount": "20.000000000000000000000000",
				"foreign_amount": null,
				"description": "Groceries",
				"source_id": "6",
				"source_name": "Cash wallet",
				"source_iban": null,
				"source_type": "Asset account",
				"destination_id": "44",
				"destination_name": "Groceries McGroceriesFace",
				"destination_iban": null,
				"destination_type": "Expense account",
				"budget_id": "0",
				"budget_name": null,
				"category_id": "0",
				"category_name": null,
				"bill_id": null,
				"bill_name": null,
				"reconciled": false,
				"notes": null,
				"tags": [],
				"internal_reference": null,
				"external_id": null,
				"original_source": "ff3-v5.6.10|api-v1.5.5",
				"recurrence_id": null,
				"recurrence_total": null,
				"recurrence_count": null,
				"bunq_payment_id": null,
				"external_uri": null,
				"import_hash_v2": "0d50d7b429523e4d56dcdae1e3d115508f4a006b3735045b2c717a7de67ceb6b",
				"sepa_cc": null,
				"sepa_ct_op": null,
				"sepa_ct_id": null,
				"sepa_db": null,
				"sepa_country": null,
				"sepa_ep": null,
				"sepa_ci": null,
				"sepa_batch_id": null,
				"interest_date": null,
				"book_date": null,
				"process_date": null,
				"due_date": null,
				"payment_date": null,
				"invoice_date": null,
				"longitude": null,
				"latitude": null,
				"zoom_level": null,
				"has_attachments": false
			}]
		},
		"links": {
			"self": "https:\/\/demo.firefly-iii.org\/api\/v1\/transactions\/463",
			"0": {
				"rel": "self",
				"uri": "\/transactions\/463"
			}
		}
	}
}
```
</details>

PUT:
```json
{
	"group_title": "API test",
	"transactions": [{
		"amount": "10.00",
		"description": "Split pt. One"
	}, {
		"amount": "5.00",
		"description": "Split pt. Two"
	}]
}
```

<details>
  <summary>Response: http 500</summary>

```
<!DOCTYPE html>
<html>
<head>
<base href="https://demo.firefly-iii.org/">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Firefly III | 500 Error</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="v2/plugins/local-fonts/gf-source.css" nonce="upFHUFl3dd/gcosExrfJaA==">
<link rel="stylesheet" href="v2/css/app.css" nonce="upFHUFl3dd/gcosExrfJaA==">
</head>
<body>
<div class="container-fluid">
<div class="row">
<div class="col-12">
<div class="error-page">
<h2 class="headline text-danger">500</h2>
<div class="error-content">
<h3><span class="fas fa-exclamation-triangle text-danger"></span> Whoops! An error occurred.</h3>
<p>
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:
</p>
<p class="text-danger">
Call to a member function transactions() on null
</p>
<h4>
More information
</h4>
<p>
Please collect more information in the <code>storage/logs</code> directory where you will find log files. If you're running Docker, use <code>docker logs -f [container]</code>.
You can read more about collecting error information in <a href="https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode">the FAQ</a>.
</p>
<h4>
Get help on GitHub
</h4>
<p>
You're more than welcome to open a new issue <strong><a href="https://github.com/firefly-iii/firefly-iii/issues">on GitHub</a></strong>.
</p>
<ol>
<li>Use the search!</li>
<li>Include the information <a href="https://demo.firefly-iii.org/debug">from this debug page</a>.</li>
<li>Tell us more than &quot;it says Whoops!&quot;</li>
<li>Include error logs (see above).</li>
<li>Tell us what you were doing.</li>
</ol>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
```
</details>

Subsequent requests for this transaction fail with a 404.

**Comment by JC5** [comment]
I'll pick up the 500, and clarify the API docs. 

To make this work, you must submit the individual split ID's or the API will assume you're creating new splits, in favor of the old ones (they would be deleted).

**Comment by GeorgeHahn** [comment]
I think I understand - the two new splits are invalid and are therefore not inserted, and then the original transaction is dropped because that split ID is not included in the update.

For context, the integration I'm working on will take single-split transactions and break them into many splits (importing receipts and splitting by item).

Would it be possible to perform the update atomically? It would be very nice to avoid any rollback or two-stage application code to restore things if an error occurs.

**Comment by JC5** [comment]
I'm now trying to see if I can catch this during the creation of the splits, yes.

A validation rule is already in place to make sure you reach that point, but you never know what the future brings in this regard.

**Comment by JC5** [comment]
Fixed. A validation rule is in place. You can circumvent it by submitting bogus for the "source_number" field. You may run into another validation rule if you do that but regardless; if no transactions can be created or updated, the routine will fail silently.

I could also error out at this point but other values will get updated (ie. the group title) so it feels best to do it like this. No doubt this results in issues in the future ("THE api is bRokeN") but the errors in the logs should be clear enough.

The demo site is up to date.

**Comment by GeorgeHahn** [comment]
This is getting caught, but the handing behavior looks a bit funky. I'm sending the same `PUT` as before. The demo site returns a `302` redirect to `/` and a subsequent redirect to `/login`. Is that expected?

**Comment by JC5** [comment]
Mmm, that would normally point to authentication issues. If you did this on the whole hour (8:00) you may have run into a reset.

I'll check it out!

**Comment by JC5** [comment]
Mmm, I'm getting a 422 as expected on the demo site.
