### ISSUE TITLE
API spec request: Extract duplicate enums to separate models

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#5611]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I noticed this on the transaction `type` enum. It is currently duplicated for `TransactionSplitStore` and `TransactionSplit`. It looks like this is true for a few other enums.

### Solution

Extract duplicate enums for better usability in generated client code.

### Additional context

I'm happy to PR this to the API spec repo if you like the idea.

**Comment by JC5** [comment]
Done, the CDN should pick up the file today.

**Comment by JC5** [comment]
https://github.com/firefly-iii/api-docs/blob/main/firefly-iii-1.5.5.yaml

**Comment by GeorgeHahn** [comment]
This looks great and definitely helps clean up the generated models. Thank you!

**Comment by JC5** [comment]
No problem, anything you need!
