### ISSUE TITLE
Add Rules Trigger or Search Operator for "Missing Tag"

### ISSUE THREAD

**Issue by jordantoth** [firefly-iii/firefly-iii#5636]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to be able to find transactions that do not have a given tag. If there were a "missing tag" rule trigger I could accomplish this by adding a strict mode rule that adds a specific tag when a transaction is missing each tag in the group. Similarly, if there were a search operator for this I could search all transactions for ones missing all of the tags in the group. 

### Solution

Add a new Rules Trigger or Search Operator that matched when the given tag is not present on a transaction. If this is too close to the "More Complicated Rules Engine"  I understand, though I think this extremely close conceptually to the existing "Has no tag(s)" trigger.

### What are alternatives?

As far as I'm aware, the only alternative currently is to manually step through each transaction to see if it has the given tag.

**Comment by JC5** [comment]
Not a bad idea, it's on the list!
