### ISSUE TITLE
Refactor API YAML to assist in working with 3rd party OpenAPI Generator.

### ISSUE THREAD

**Issue by jafin** [firefly-iii/firefly-iii#5637]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Refactor `oneOf` fields in YAML API Schema into a wrapper class to assist in working with 3rd party OpenAPI Client tool generators.

### Solution

https://github.com/firefly-iii/api-docs-generator/pull/39

**Comment by JC5** [comment]
Done :+1:
