### ISSUE TITLE
Transaction Pager Not Working

### ISSUE THREAD

**Issue by dzaikos** [firefly-iii/firefly-iii#564]
I recently installed Firefly III version 4.3.4. After creating some accounts (asset, revenue, and expense) and entering some transactions I can only view transactions that are on the first page anytime the transactions are listed (so Accounts > Asset accounts > click account name and scroll down the page). When I click the pager number (2, 3, etc.) it reloads the page with what appears to be the proper URL (`https://example.org/accounts/show/1?page=2`) but the pager still has page 1 as active and the transactions listed are for page 1.

No errors in any logs (except something about no piggy bank).

I have the default date range as 3-months (quarterly), but changing this value doesn't seem to resolve anything. I've set the transactions per page to 50; increasing this to an absurd number lets me view the transactions I need, but obviously I would prefer the pager to work.

**Comment by JC5** [comment]
I've tried to replicate your problem, but it seems to work just fine on the [demo site](https://firefly-iii.nder.be/accounts/show/1?page=4).

The default range is three months, and the page length is 5 (so there are plenty of pages). Seems to work as intended.

**Comment by dzaikos** [comment]
Ugg...

Too many late nights setting up things. Added `$is_args$args` to my nginx location {} and it works.

Sorry. Please close.

**Comment by JC5** [comment]
No problem, glad it works!
