### ISSUE TITLE
Adding locale-gen to Docker entrypoint

### ISSUE THREAD

**Issue by trallen** [firefly-iii/firefly-iii#5648]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

The current documentation suggests that, for Docker installations, when extra locales are needed, the locates should be added  to /etc/locale.gen, locale-gen should be run, and Apache reloaded.

The difficulty with this is that every time the container is restarted, the updated /etc/locale.gen is lost, and the commands need to be re-run.

### Solution

One way around this would be to run locale-gen in the Docker entrypoint script, before starting Apache. If the user needs a specific locale, they could mount a custom locale.gen file with something like 'docker run -v locale.gen:/etc/locale.gen fireflyiii/core:latest'; when the entrypoint runs, it should build the necessary locales. This wouldn't address instances where a specific language-pack is needed, but the default locales package has fairly broad coverage.

One downside of this could be a long rebuild time every boot in cases where /etc/locale.gen is empty. It might be necessary to provide a skeleton /etc/locale.gen in the Dockerfile containing some default locales to reduce the start time.

**Comment by JC5** [comment]
You could combine it with a Docker specific environment that triggers it. I'll check it out, thanks!

**Comment by JC5** [comment]
A new environment variable called will trigger a new build of the locales. Use `DKR_BUILD_LOCALE=true`.

If necessary, you can add your own locales to a locale.gen file as you suggested.
