### ISSUE TITLE
bug: (Schema): Set default values explicitly when indicated in documentation

### ISSUE THREAD

**Issue by jafin** [firefly-iii/firefly-iii#5658]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When the schema comment indicates a default value is set, be explicit in the schema.
PR https://github.com/firefly-iii/api-docs-generator/pull/40

### Expected behaviour

When a default value is indicated, then the generated API client should set it to match, requires API to be explicit by having the `default: <value>` field set

### Debug information

N/A

**Comment by JC5** [comment]
Merged :+1:
