### ISSUE TITLE
When setting a rule action via API with Active = false, a few unexpected things occur.

### ISSUE THREAD

**Issue by jafin** [firefly-iii/firefly-iii#5659]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

## Concern
There is no distinction between active/inactive rule actions in the UI.  Perhaps because in UI this does not make sense because a Rule cannot be marked inactive? (only via API?).

### Expected behaviour

- Does it make sense to have a rule action state of active/inactive if there is no way in the UI to modify this?
- Should the UI expose this active/inactive toggle somewhere?

### Debug information

N/A

### Steps to reproduce

- Use the API to write a rule action, (accidentally) set the `Active` state to `false`.
- In the UI, Observe that the rule is visible in the Ruled/Edit page
- Trigger the rule.
- Observe that the inactive rules do not trigger (correct?).
- If the Rule is saved via the "Update Rule" button, rule action becomes active again.

**Comment by JC5** [comment]
I see some mixups of "rules" and "rule actions" in your post but yes, the API has more features than the UI, generally speaking. In a similar vein, the API allows you to create split recurring transactions which the UI will happily ignore and delete.

The API and Firefly III support active/not active [rules](https://github.com/firefly-iii/firefly-iii/blob/main/app/TransactionRules/Engine/SearchRuleEngine.php#L379), [rule triggers](https://github.com/firefly-iii/firefly-iii/blob/main/app/TransactionRules/Engine/SearchRuleEngine.php#L184) and [rule actions](https://github.com/firefly-iii/firefly-iii/blob/main/app/TransactionRules/Engine/SearchRuleEngine.php#L461).

The UI however, does not. 

I'm working on a new layout where this will be handled better.

**Comment by jafin** [comment]
@JC5 ,  apologies, I meant 'rule actions' throughout.   
It's no big deal, just thought I'd mention it in case it was unexpected.  Sounds like it's known so closing.
