### ISSUE TITLE
Current balance should reflect todays balance in asset accounts 

### ISSUE THREAD

**Issue by zynexiz** [firefly-iii/firefly-iii#5662]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

When listing all asset accounts, the column "current balance" shows the amount in relation to what time period is selected (last 30 days, today etc). IMO this should show the current balance until today's date, not the future balance (or whatever time period is selected). Using "last X days" shows the current balance until today, this should be the case no mater the time period selected. Now it's a bit confusing when I reconcile the account. Haven't tried the new UI layout, so not sure if this is just for first version of the UI or both.

Also, and this is of course from my point of view, I haven't really found any use of the balance difference. It doesn't tell my much more than the difference from the start to the end of the period. Some might find it useful though? A different approach would be like Skrooge (that I used before) have it, where the balance is calculated including all future transactions. That way you easily see if you are low on found for that account after all expenses are paid. 

### Solution

Could be different solutions. Either change the columns to reflect the above changes, or create some configuration so you can select what kind of columns you want to display. That way the users could choose the preferred way to display the balances, as it is now or the above suggestion fx.

### What are alternatives?

None that I know of, except needing to change the time period ever time I login.

**Comment by JC5** [comment]
Sorry, this will stay as it is. The “balance” box will disappear in the future though.

**Comment by zynexiz** [comment]
Ok, then I know :)
