### ISSUE TITLE
View [v1.auth.mfa] not found.

### ISSUE THREAD

**Issue by SBarkovskiy** [firefly-iii/firefly-iii#5663]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hey everyone!

Hope you are doing great!

After setting up the MFA got the error:
**View [v1.auth.mfa] not found.**

Thank you

### Expected behaviour

Regarding the guide - https://docs.firefly-iii.org/firefly-iii/advanced-installation/authentication/

MFA should be set without any issues.

### Debug information

Debug information generated at 2022-01-30 15:25:14 UTC for Firefly III version **5.6.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.12 |
| Firefly III API | 1.5.5 |
| Build | 88, 30-01-2022 07:14:31 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 381d673e-d669-46a8-8b8e-4d0229255832 |
| Using docker? | true |
| Layout |  |
| System TZ |  |
| Browser TZ | Europe/Moscow |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first | 2022-01-30 14:15:54 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 |

### Steps to reproduce

1 - Log in on freshly installed via Docker FireFly III 5.6.12
2 - Go to Profile and try to set MFA
3 - After putting the first six-digit number got the immediate error - **View [v1.auth.mfa] not found.**

**Comment by JC5** [comment]
Ah nice, apologies. This will be fixed in 5.6.13, which I'll release shortly!
