### ISSUE TITLE
Financial reports broken since latest version.

### ISSUE THREAD

**Issue by pedrom34** [firefly-iii/firefly-iii#5664]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hey James, just to inform you:
the financial reports are broken since at least v. 5.6.11
When selecting the whole year 2021, firefly-III only generates a report for the 31/12/2021.

### Expected behaviour

Firefly-III should generate a report for the whole year 2021 when selecting that period.

### Debug information

Debug information generated at 2022-01-30 17:28:42 Europe/Paris for Firefly III version **5.6.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.13 |
| Firefly III API | 1.5.5 |
| Build | (unknown), (unknown) |
| PHP | 8.0.15 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 9f78083c-1aae-4faf-8530-f0ac2894d1e1 |
| Using docker? | false |
| Layout | v1 |
| System TZ | Europe/Paris |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | 192.168.0.1 |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first | 2019-06-05 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0 |

### Steps to reproduce

1. Reports
2. Default report
3. All accounts
4. from 1/1/21 to 31/12/21 as a date range
5. Submit
6. Report is generated for 31/12/21 only

### Additional info

I can reproduce the bug on the demo site.

**Comment by JC5** [comment]
Indeed. You'll have to change the URL for the time being. I'll release a fix next week!
