### ISSUE TITLE
Bring Back V2 or add "Time" field to V1

### ISSUE THREAD

**Issue by gthbusrr** [firefly-iii/firefly-iii#5665]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hi, I totally understand that you are planning to stop supporting V2 and work on V3. However, one of the feature that V1 lacks is that I have no way (or I might have missed it, please advice) to add a time to my purchses. 

### Solution

Bring Back V2 or add Time field to V1

**Comment by JC5** [comment]
No, sorry. I appreciate the feature as well but adding stuff to v1 won’t make v3 appear any faster.

**Comment by gthbusrr** [comment]
Hi, I understand, but given that V2 is working well for some people and we'll have to deliberately change an env variable manually, can we have V2 back as an option for now? Maybe a obnoxious banner saying no updates/bug fixes will be entertained on the homepage like there has been. Thanks a lot~~~
