### ISSUE TITLE
Improve API error response  to api/v1/rules/{id}/trigger to return a 400 instead of 500 when invalid parameters are issued

### ISSUE THREAD

**Issue by jafin** [firefly-iii/firefly-iii#5670]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Using the API to call `/api/v1/rules/{id}/trigger`  
If I send invalid date formats (ie date with timestamp) when the correct format is date (`YYYY-MM-DD`)  then the server should respond with a 400 (ideally describing what fields were invalid), at present, the server will error 500 but does describe the issue in the response payload as `InvalidFormatException`.

The parameters I pass to cause the error (invalid due to an issue with clientgen tool)
```
?start=2000-01-01T00%3a00%3a00.0000000&end=2022-01-31T09%3a42%3a16.7159002%2b10%3a00
```

```text
Error response
The error was of type "Carbon\Exceptions\InvalidFormatException".

This error occurred in file "/var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php" on line 676 with code 0.
URL is: http://localhost:8050/api/v1/rules/68/trigger?end=2022-01-31T09%3A42%3A16.7159002%2B10%3A00&amp;start=2000-01-01T00%3A00%3A00.0000000
User agent: OpenAPI-Generator/1.0.0/csharp

The full stacktrace is below. If you think this is a bug in Firefly III, you can forward this message to james@firefly-iii.org. This can help fix the bug you just encountered.

If you prefer, you can also open a new issue on https://github.com/firefly-iii/firefly-iii/issues.

The full stacktrace is below:

#0 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(699): Carbon\Carbon::rawCreateFromFormat()
#1 /var/www/html/app/Api/V1/Requests/Models/Rule/TriggerRequest.php(58): Carbon\Carbon::createFromFormat()
#2 /var/www/html/app/Api/V1/Requests/Models/Rule/TriggerRequest.php(45): FireflyIII\Api\V1\Requests\Models\Rule\TriggerRequest->getDate()
#3 /var/www/html/app/Api/V1/Controllers/Models/Rule/TriggerController.php(132): FireflyIII\Api\V1\Requests\Models\Rule\TriggerRequest->getTriggerParameters()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Api\V1\Controllers\Models\Rule\TriggerController->triggerRule()
```

Perhaps this is a broader topic, and if an InvalidFormatException is caught for any endpoint consider if returning a 400 response is more aligned than a 500?

**Comment by JC5** [comment]
Yes, it should return a 422 instead of a 500. If you find any others, let me know :+1:

**Comment by JC5** [comment]
Since the date format you submitted is valid, the 422 didn't fire. Other code broke down. Should be fixed in the next release.

**Comment by jafin** [comment]
@JC5 ok, I'll take a look at the next release, I thought it was the date format, as I recomposed the query using dates with format `YYYY-MM-DD` and I recall it succeeded.  Either way, I will check in the next update. Thank you.

**Comment by jafin** [comment]
Updated to 5.6.14. All working, even with the full DateTime sent in parameters.
