### ISSUE TITLE
Running Rules on Existing Transactions Does Nothing

### ISSUE THREAD

**Issue by winsomniak** [firefly-iii/firefly-iii#568]
I setup some rule groups and running them on existing transactions does not seem to update anything. I tried using the little checkbox icon as well as the anchor in the rule group dropdown.

![image](https://cloud.githubusercontent.com/assets/11396781/22918501/7f0aba42-f23f-11e6-8968-821c7548420f.png)

**Comment by JC5** [comment]
The rule will only trigger when the whole set of triggers is matched. That may be the problem.

**Comment by JC5** [comment]
Apologies, what you could try is setting the "stop processing when trigger hits" checkbox for each of your triggers. This should enable the "OR" functionality you're looking for.

But use the little checkbox first to validate if your rules would actually trigger anything.

**Comment by winsomniak** [comment]
Ah ok, will try that. Thanks!

**Comment by winsomniak** [comment]
No luck, the rules are still not firing off. I did confirm that transactions match the criteria with the little checkbox.

![image](https://cloud.githubusercontent.com/assets/11396781/22920815/c02c68e8-f24b-11e6-9e7d-2dab4dede418.png)

**Comment by JC5** [comment]
OK, so your rule matches a transaction (or set) when you verify them with the check box, but running the rules on existing transactions does not change those transactions.

I'll give you some pointers later today. For now, I would suggest tomorrow keep the rules simple.

There is only one rule engine in firefly, meaning that there is just one method that firefly uses to match transactions and rules. So if the checkbox finds a match, every other part of firefly will also find a match. 

Question is if the transaction trigger is correct (on create or on update) and if the "run on existing transactions" routine verifies the correct set of transactions.

**Comment by winsomniak** [comment]
Yeah, I was able to get something to work by using  a 1:1 trigger/action setup but nothing complicated.

The real problem I am having is that I want to use processing rules like "strip # followed by numbers from destination account". You haven't implemented a special markup or regex in these fields have you?

**Comment by JC5** [comment]
No. What you could do is set up Firefly not to encrypt stuff. Open the `.env` file and change `USE_ENCRYPTION=true` to false.

Then, after the import, transaction descriptions are readable in the table `transaction_journals` and can be updated by any tool.

**Comment by JC5** [comment]
Yep. One way encryption (often called "hashing") would be pointless: once hashed, I couldn't even show you the transaction.

It's two way encryption: the key is in your `.env` file and the method used is AES-256.
