### ISSUE TITLE
Duplicate detection in Data Import tool broken after docker version update

### ISSUE THREAD

**Issue by cloudhaus** [firefly-iii/firefly-iii#5683]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am using Firefly iii together with the Data Import tool. I normally generate a 90 day CSV export from my banks. When this CSV is imported using the Data Importer into Firefly iii it correctly keeps track of duplicates.

When I upgrade Firefly iii by updating the version in my docker-compose.yaml this duplicate detection no longer works. The next time I import a 90 day CSV after the version upgrade it imports all transactions again and not just the new ones. 

### Expected behaviour

After Firefly iii version upgrade the Data Importer should not import transactions already in Firefly iii. 

### Debug information

Debug information generated at 2022-02-01 09:13:58 America/New_York for Firefly III version **5.6.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.13 |
| Firefly III API | 1.5.5 |
| Build | 93, 30-01-2022 17:08:11 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | f2c05d8d-b771-4712-b239-482f2cb33c4b |
| Using docker? | true |
| Layout | v1 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 00:00:00 |
| Session first | 2021-12-27 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15 |

**Comment by JC5** [comment]
I need more information. I'm not aware of any changes that broke the duplicate detection. The duplicate detection in Firefly III hasn't changed significantly for years. I can't tell if this happens every time you upgrade or just this once. Either way, there's not much I can do about it now.

I can only help you further if you can share some logs from before / after. Usually, the cause is not Firefly III but the Data Importer. This tool is under active development and sometimes changes in the Data Importer break the duplicate detector, because transactions are submitted in a different way to Firefly III.

**Comment by ThijmenStar** [comment]
I have the same issue, after downgrading the fireflyiii/data-importer image it worked again

**Comment by JC5** [comment]
As you can read in the change log of the data importer, some changes and features may break the duplicate detection of Firefly III. 

This is always mentioned in the release notes.

**Comment by cloudhaus** [comment]
I experience the issue when I update the Firefly iii docker image (not the data-importer). It happens only on the first import of a CSV. Everything doubled. It is easy to fix as the new transactions (mostly duplicates) are tagged. I just have to delete the doubles then everything is fine again on subsequent imports. I guess it serves me right for always doing a 90 day CSV export from the banks. 

There have been a few core image updates recently (thank you!) which has made it come to light for me. 

firefly docker-compose
image: fireflyiii/core:version-5.6.13

importer docker-compose
image: 'fireflyiii/data-importer:version-0.7.0'

I do appreciate this software being available. I am coming from Gnucash which was too much software for me. The next time there is an update to fireflyiii I will look at the logs.

**Comment by JC5** [comment]
Alright, thanks for letting me know. If you could keep an eye on the logs I'd appreciate it. It shouldn't happen but it's always possible. It may also be the export from your bank, I've seen that happen as well. One example: the "moment of export" is a row in the CSV, which breaks detection.

Either way, the data importer does not need persistence. The duplicate detection comes in two flavours. This is configurable in the data importer (configuration page):

- Content based. **Firefly III** will search for duplicates based on the entire transaction. You can [debug the process](https://docs.firefly-iii.org/data-importer/errors/duplicate_transactions/) if you have a duplicate transaction that is not yet deleted.
- Identifier-based. The **Data Importer** will search for possible duplicates using the external_id field before submitting transactions.

https://docs.firefly-iii.org/data-importer/usage/configure/#duplicate-transaction-detection

**Comment by MacPaille** [comment]
I have to check at next update but I saw the same behavior after upgrading FF from 5.6.11 to 5.6.13. But impact was limited as I only import last 10 days from Nordigen. By removing all the older transactions is correctly finds the duplicates with the new ones.

I'll keep an eye at next update. From what I checked it's mainly the transactions hash that is different (I'm using content based). Could it be something that is generated again at update time that is used to calculate that hash?

**Comment by JC5** [comment]
You can use the debug function from the documentation (see above) to compare transactions. The hash will be different, otherwise it wouldn't be a duplicate. But I'm curious to see which other fields are different too. 

>  Could it be something that is generated again at update time that is used to calculate that hash?

I don't know what you mean exactly but Firefly III doesn't use date or time fields to make the comparison for exactly this reason. The hash is generated only once, when the transaction is received. It's never updated again, not even when you edit the transaction in the UI later on.

**Comment by JC5** [comment]
> Could there be something that changes as parameter of this computation so the hash is different the next time you import the same transaction after an update?

Not after an update, that has been taken care of years ago. It's literally the first thing I did when I made it.

**Comment by JC5** [comment]
Besides, a lot of people use the data importer, and I would have heard from more people if it broke between every version. Firefly III is now big enough that if one user has a bug, it's rarely a bug. It could still happen of course but the odds aren't in your favor. 

https://docs.firefly-iii.org/data-importer/errors/duplicate_transactions/

I expect the issue to be among these common causes. When it comes to duplicates, the following scenario is entirely possible and something I've seen before. You won't be able to spot this until you look really closely to your logs:

- Bank adds "download date" to transaction notes (changes every night)
- User imports transaction notes into "notes" field. 
- User has a rule to delete the "notes" field
- User has duplicate transactions because the notes are different every night.

This isn't something you can spot using the `/debug/` view.

**Comment by niklas152** [comment]
Hi, I just had the same behaviour after upgrading from 5.6.10 to 5.6.13. Using the firefly-iii-fints-importer on two different bank accounts, both resulted in full duplication of previously (yesterday) imported transactions.
There was no update to firefly-iii-fints-importer, and no previous update to firefly-iii itself has caused this problem.

**Comment by JC5** [comment]
Very weird. Especially in between those releases nothing significantly changed. Keep me in the loop, if you have logs please share them.

**Comment by poudenes** [comment]
Today had same issue... Balance was different in Firefly and bank. Checked transactions and there where lots of duplicates.
Removed them and balance are correct again. Sorry no logs

**Comment by MacPaille** [comment]
Did not update today but 2 transactions were imported as duplicates base on the same CSV between the 2 FIDI runs. Source data did not changed.
Have sent the debug json of the 2 transactions by email

**Comment by JC5** [comment]
Thanks. Next up, the debug logs of Firefly III when it receives the transaction.

**Comment by JC5** [comment]
Or send me the transactions and your config file, if you would. That would help me debug things.

**Comment by MacPaille** [comment]
I have sent the CSV with the transaction and the json for that account.

I'm checking for the FF logs if I can provide anything. For FIDI I only have the latest run as it always overwrite the logs

**Comment by Piramidowy** [comment]
Same issue here. Today's CSV import generated a lot of duplicates. What is even more weird, after removing all transactions tagged with last import, I'm unable to import them one again - Data import tool says that all transactions are duplicates. I've checked IDs and it doesn't exist in FF.

**Comment by MacPaille** [comment]
> Same issue here. Today's CSV import generated a lot of duplicates. What is even more weird, after removing all transactions tagged with last import, I'm unable to import them one again - Data import tool says that all transactions are duplicates. I've checked IDs and it doesn't exist in FF.

That is normal as they are not removed from the DB but set in a deleted state. So you won't be able to import them except if you run again the import and set duplicate detection to false for that run...

**Comment by Piramidowy** [comment]
This way I'll end up with duplicates one again, won't I? So there is no way to fix it without removing duplicates manually?!

**Comment by poudenes** [comment]
Every import get a TAG.. you can select that one, and remove the ones you already have and keep the new ones?

**Comment by MacPaille** [comment]
> This way I'll end up with duplicates one again, won't I? So there is no way to fix it without removing duplicates manually?!

Indeed. Each time I'm getting duplicates I just delete them all.? But I limit the number of duplicates I can get by keeping my CSVs at minimal size. For my accounts imported with Nordigen I ask to import only last 6 days.

I also find it easier to identify the ones to delete as I reconcile my accounts very often, so you easily see the ones imported the latest that do not have the small V for reconciled.

> Every import get a TAG.. you can select that one, and remove the ones you already have and keep the new ones?

I do not import with tags so can't use that 😄

**Comment by JC5** [comment]
> Same issue here. Today's CSV import generated a lot of duplicates. What is even more weird, after removing all transactions tagged with last import, I'm unable to import them one again - Data import tool says that all transactions are duplicates. I've checked IDs and it doesn't exist in FF.

So what you're telling me here is a clue to the root cause. And spoiler alert: duplicate detection works fine. Otherwise you would have been able to import them twice or three times in a row. But you can't. In other words: duplicate detection works fine.

---

The only issue I can think of that could cause this, is that during the first run, a new expense account is created, say, "store X". This only happens when you've never been in that store or if you've deleted "Store X" between two runs.

The first time you import data the Data Importer generates something like this:

`{"destination_id":null,"destination_name":"Store X"}`

The second time, it recognizes the store and will import this:

`{"destination_id":123,"destination_name": null}`

That causes a duplicate.

---

I can only know if this is happening for you guys if you collect debug logs on the side of Firefly III, where it stores what it receives from the data importer. You can drop them in the mail if you want: james@firefly-iii.org

**Comment by JC5** [comment]
Of course, I will research if this is indeed a cause of duplicates and I'll try to fix it if I can :+1:

**Comment by poudenes** [comment]
Today did a import again and now it shows that I already have records so they are marked as duplicates and leave them away..... strange

**Comment by JC5** [comment]
I had a possible theory but that's not the case. 

A known cause is that if you change your configuration (change things on the mapping page) it may break duplication.

**Comment by JC5** [comment]
I received some examples from @MacPaille but I was not yet able to replicate the issue: duplicates are detected properly as expected. Possible causes such as reconciling transactions or changing the mapping (outside of the relevant transaction) also do not trigger the issue.

**Comment by cloudhaus** [comment]
I just did an experiment. I stopped fireflyiii with `docker-compose down` then restarted it with `docker-compose up -d` as usual. 

I ran an import with a 90 day CSV and everything worked as planned. It correctly picked up the new transactions and ignored the ones previously imported. 

I only get the issue after I have upgraded fireflyiii docker image in the docker-compose. I get the issue only once after that where every transaction in the 90 day CSV is duplicated. After that everything is back to normal with subsequent imports.

I eagerly awai the next version to test this out again.

thanks to all

**Comment by JC5** [comment]
A new version should be released over the weekend, I am curious about the results.

**Comment by MacPaille** [comment]
I'm curious too :) Anyway all the next runs I'll do I will pay attention to what is happening and fetch any logs I can.

**Comment by MacPaille** [comment]
Did run the import today after FF update, no duplicates. Will still keep an eye open on this

**Comment by cloudhaus** [comment]
I just upgraded from 13 to 14. NO DUPLICATES! I imported a 90 day CSV download from the bank and correctly only one transaction was entered into fireflyiii. What a mystery. In any case I'm happy to be back to normal. Thank you for this great software. I do appreciate it.

**Comment by poudenes** [comment]
Hi All,

It seems that this is still going on. When I import data and change things from those records. description. mostly and next day I import again include the day I already did I see those records back with description that is imported.

When I change things like category and budget then everything is ok. 

I think it will check on amount, withdraw, description. When this is different then it will import it again.
If this is correct then you can't add records in advanced manual when you buy something and want it in Firefly. The import will add this same line also with description received from the bank.

Maybe im wrong, but this is what I see. :) I created a workaround to import all bank info automatic in morning at 6:00 so I see what my status is...

**Comment by JC5** [comment]
1. If you create transactions manually it will probably never match the import from your bank. This is not something I can help. There are often more details in the import than there are in your manual transactions. Therefore the duplicate detection will almost always fail. 
2. if you change transactions after they are created, the duplicate detection will still work just fine.

**Comment by MacPaille** [comment]
OK I have updated my FF from 5.6.14 to 5.6.16 this morning and tonight's FFDI run ALL my transactions are imported again. So updating clearly breaks duplicate detection.

Which info would you need to troubleshoot?

**Comment by JC5** [comment]
Looking at the code changes between 5.6.14 and 5.6.16, there are changes that could result in a different hash.

**Comment by JC5** [comment]
This is the only relevant change i could find. It fixes a bug but could lead to different hashes.

https://github.com/firefly-iii/firefly-iii/compare/5.6.14...5.6.16#diff-fc883629310637252ff2b4b6a54de049cff172d207b206a576b50e37d4a0a8da

**Comment by MacPaille** [comment]
So nothing special to do. I think next time I'll limit the transactions to 1 day after an update 😄
