### ISSUE TITLE
Add second tag on docker images (SemVer) (without the `version-`

### ISSUE THREAD

**Issue by stavros-k** [firefly-iii/firefly-iii#5687]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Would be nice if docker images got also a tag without the `version-` portion e.g. `5.6.13`
That would help CI's like https://github.com/renovatebot/renovate, easily spot the updated image :)

(Not asking to drop your current tagging method, just add a second tag to the same image.)

Thanks

### Solution

Add second tag to images.

**Comment by JC5** [comment]
No, I'm sure renovatebot can learn to work with `version-x.x.x`.

**Comment by stavros-k** [comment]
And people can learn spreadsheets to manage their budgets.. Anyway not here to argue.
Sure renovate can work with the current scheme, if every one who uses it takes the extra step.

Thought it would be better to make it easier for everyone.

Anyway thanks for your answer, and providing the app.
