### ISSUE TITLE
CSV Import Headers Labels "Column 1" "Column 2" etc

### ISSUE THREAD

**Issue by winsomniak** [firefly-iii/firefly-iii#569]
CSV import does not retain the column headers. This makes it more difficult to cross reference them when mapping to firefly values.

![image](https://cloud.githubusercontent.com/assets/11396781/22919264/acf4bc06-f243-11e6-9b3f-e34d6672ad46.png)

**Comment by JC5** [comment]
I assume your CSV file does have named headers? I believe I never got around to fixing this. But I will!

**Comment by winsomniak** [comment]
Yes I have actual headers haha

Cool project. I am looking forward to showing my wife with fancy visualizations how much we spend on clothing, cosmetics and Starbucks!

**Comment by JC5** [comment]
Fixed! The upcoming release will show header names.
