### ISSUE TITLE
Transaction not found by search under specific conditions

### ISSUE THREAD

**Issue by wi6436** [firefly-iii/firefly-iii#5695]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello,

I have a strange issue, which affects the search in Firefly III and the triggering of automatic actions. A transaction, which matches the search criteria is not found under specific conditions. The issue appeared to be intermittent at first, but I have finally found detailed steps to reproduce it reliably starting from a clean docker installation.

I would be very happy if you could have look. Many thanks! :)

### Expected behaviour

Entering into the "Search..." field the query

destination_account_contains:"PAYPAL"

should deliver a list of all transactions containg the word "PAYPAL" in the name of the destination account.

### Debug information

Entering the query above yields an empty or an incomplete list of transactions. I have observed this issue only under the following conditions:

1) The number of registered expense accounts is > 25. Only transactions, which send money to one of the expense accounts, which are in excess of 25, are missing in the returned transaction list.

2) The names of all or most of the registered expense accounts consist of 3 separte words each, separated by spaces.

### Steps to reproduce

1.) Start from a clean docker installation.
2.) Create an asset account "my_account":
3.) Create 26 expense accounts with the following names: "VISA PAYPAL A",  "VISA PAYPAL B" ,"VISA PAYPAL C",...,"VISA PAYPAL Z".
4.) Create a transaction, which transfers 1,00€ from "my_account" to "VISA PAYPAL Z".
5.) Search for the transaction created in (4) by entering the query <destination_account_contains:"PAYPAL"> into the search field.
6.) Due to the bug, Firefly III doesn't find the transaction, but returns an empty list.

After editing the transaction to send the money to one of the other destination accounts (i.e. not the 26th destination account) or, alternatively, deleting one of the unused destination accounts, the search works perfectly and finds the transaction.

**Comment by JC5** [comment]
The search generates one giant query. So this will be database related. Which database are you testing this with?

**Comment by wi6436** [comment]
Hi James,

thanks for your reply. It's the mariadb docker image. I'm using the docker-compose.yml file from here: https://raw.githubusercontent.com/firefly-iii/docker/main/docker-compose.yml

**Comment by JC5** [comment]
I found the issue, and a fix will be part of the next release. Nice work 👍

**Comment by wi6436** [comment]
I'm happy that you found it so quickly! Thanks for the bug fix :)
