### ISSUE TITLE
Documentation is not linked when clicking the help icon

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#5699]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When you click the help icon on any page, it brings up a message that tells you the help text is not yet available in your language:
![image](https://user-images.githubusercontent.com/21091510/152283312-a7cde462-68f3-4a1f-b8c6-63524f2e638d.png)
I thought it used to link to the documentation. Was that just a V2 thing? Could you either make it link to the documentation or change the message?

### Expected behaviour

A link to the relevant documentation should appear. Or just a link to the documentation in general.

### Debug information

Debug information generated at 2022-02-02 23:55:05 America/New_York for Firefly III version **5.6.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.13 |
| Firefly III API | 1.5.5 |
| Build | (unknown), (unknown) |
| PHP | 8.0.15 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 33fe0fbe-cfee-496b-81fa-a926233790d2 |
| Using docker? | false |
| Layout | v1 |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-02-01 00:00:00 |
| Session end | 2022-02-28 00:00:00 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 |

### Steps to reproduce

1. Be on your firefly iii site.
2. Click the question mark icon
3. See the not very helpful help box appear.

### Additional info

I just spent half an hour trying to figure out why my category report was broken and then I found out someone had already reported it :disappointed:

**Comment by JC5** [comment]
Sorry to hear about the category report :(

The repository with help text is offline, so the page is not working. I'll make it has some text instead.

**Comment by JC5** [comment]
I pushed a fix to the demo site, pretty simple because of the new layout which is coming anyway.
