### ISSUE TITLE
Docker: InvalidArgumentException

### ISSUE THREAD

**Issue by Aeny202** [firefly-iii/firefly-iii#570]
Seems I've ran into some trouble here. 
At first I tried setting firefly up using shoentoon's comments from here https://github.com/firefly-iii/firefly-iii/issues/537.
This didn't work so I scrapped that idea and checked out the develop branch and followed the instructions over here: https://firefly-iii.github.io/installation-guide-docker/ 

Both times I managed to hit the same error when executing the step “init-database”. 

```
docker exec fireflyiii_firefly-app_1 php artisan migrate:refresh --seed

                                       
  [InvalidArgumentException]           
  View [emails.error-html] not found.  
                                       

```
docker ps
```docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
9e9d0bb0d83c        firefly-iii         "docker-php-entryp..."   32 minutes ago      Up 4 minutes        0.0.0.0:80->80/tcp   fireflyiii_firefly-app_1
40fdbb00822f        mysql:8             "docker-entrypoint..."   32 minutes ago      Up 16 minutes       3306/tcp             fireflyiii_firefly-db_1
```
When attached to the app container I can see the http requests coming through: 
```
docker start -i fireflyiii_firefly-app_1
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message
[Tue Feb 14 18:16:05.054408 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/7.1.1 configured -- resuming normal operations
[Tue Feb 14 18:16:05.054496 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.122.10 - - [14/Feb/2017:18:16:15 +0000] "GET / HTTP/1.1" 500 210 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
192.168.122.10 - - [14/Feb/2017:18:16:27 +0000] "GET / HTTP/1.1" 500 210 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```
But no webpage is loaded.

Tried a quick Google search, I also searched through the issues here but didn't see anything relevant. My apologies if I missed something. If you need any logs that I missed then please ask. 

EDIT: Added only logfile in storage/logs

[firefly-iii-2017-02-14.txt](https://github.com/firefly-iii/firefly-iii/files/774991/firefly-iii-2017-02-14.txt)

**Comment by JC5** [comment]
I have to look into this later, but I do know the invalid argument exception is probably a secondary error. The actual problem is something else. 

Is there something in the /storage/logs directory?

**Comment by Aeny202** [comment]
@JC5 Added the log in OP.

**Comment by JC5** [comment]
Bingo! 

`Type error: strlen() expects parameter 1 to be string, boolean given`

This is a something I can fix. You'll have to work without docker for the moment, but I will fix it for the next version. Keep an eye on this repository this weekend :)

**Comment by Aeny202** [comment]
I took the liberty to retest this, this particular issue is now solved for me in the develop branch.

For future reference make sure if you had encountered this error before that you remove all old images and containers first, else docker-compose does not seem to rebuild them thus not incorporating the fix.

Thanks for the quick fix. :)
