### ISSUE TITLE
WHOOPS 500 when using pulldown menu use json file

### ISSUE THREAD

**Issue by poudenes** [firefly-iii/firefly-iii#5700]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I added the JSON_CONFIGURATION_DIR to my config so I can use the pulldown menu to select my .JSON files
When I select one, first step is running. At the moment to start importing I get a "WHOOP 500" message.
```
Whoops! 500 :(
Sorry, the Firefly III Data Importer broke down.

Error message
redirectToCorrectNordigenStep: Cannot handle Nordigen step "submit"

More information
The error occurred in /var/www/html/app/Http/Middleware/IsReadyForStep.php:389.

Please collect more information in the storage/logs directory, where you will find log files. If you're running Docker, use docker logs -f [container]. You can read more about collecting error information [in the FAQ](https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode).

Get help [on GitHub](https://github.com/firefly-iii/firefly-iii/issues)
You're more than welcome to open a new issue on GitHub.

Use the search!
Include the information [from this debug page](http://192.168.100.24:3474/debug).
Tell us more than "it says Whoops!"
Include error logs (see above).
Tell us what you were doing.
```

### Expected behaviour

To go on with the import.

### Debug information

n/a

### Additional info

The error pops up with 1 of the 2 json files. Both work when I select them with upload. Both copy/paste in the folder to use them as pulldown menu options.

**Comment by JC5** [comment]
Thanks! I'll check it out and fix it :+1:

**Comment by poudenes** [comment]
Additional info:
I checked the 2 files. They totally identical only `"accounts", "nordigen_bank", "nordigen_requisitions" `are different. Rest are totally same.
