### ISSUE TITLE
Search for specific amount of money

### ISSUE THREAD

**Issue by poudenes** [firefly-iii/firefly-iii#5703]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Would be nice to have a search option. 

### Solution

So you can search for specific amount of money (example: 15,87) So you can see all transactions with this value.

### What are alternatives?

search the whole transaction list. Or on specific bill

**Comment by JC5** [comment]
You can already do this with “amount:12.34”

**Comment by poudenes** [comment]
Wow, that was a fast implementation :) ... Sorry for the request. Didn't know this ! Thanks!
