### ISSUE TITLE
Allow zero-amount transactions?

### ISSUE THREAD

**Issue by wi6436** [firefly-iii/firefly-iii#5709]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Firefly III doesn't allow importing transactions with the amount 0,00. While it seems to not make sense having zero-amount transactions at first, my bank actually deposits such zero-amount transactions often. This happens for example to inform that the overdraft fees of the past quarter have been 0,00. My importer stumbles across these kind of transactions and I have to use workarounds, like deleting those transactions beforehand or using 0,01 as amount, but this is not nice and probably it wouldn't hurt to have zero-amount transactions in Firefly III.

### Solution

Would it be possible to allow the creation of such 0,00 transactions or is there a particular reason to forbid these?

**Comment by JC5** [comment]
Haha absolutely not. A zero-amount transaction makes zero sense, pun intended.

I can look into making the importer (CSV, Nordigen or Spectre?) skipping these without erroring out, but otherwise no, they will not be supported.
