### ISSUE TITLE
Import transactions: Date is always today

### ISSUE THREAD

**Issue by sirrahd** [firefly-iii/firefly-iii#571]
I just set up Firefly-III on FreeBSD, really looking forward to giving it a try! I'm having an issue where the dates on all imported transactions become today.

Dates seem to be identified properly from the CSV file before import; they are converted from the n/j/Y format in the file to Y-m-d on the 'Define Column Roles' page, and I don't see any errors on the import progress page or in the logs. Is this a known issue or any idea where to look to debug this further? Thanks for taking a look at this.

What my dates look like before import on the 'Define Column Roles' page:

![image](https://cloud.githubusercontent.com/assets/1222112/22947924/ac4ecbc0-f2ca-11e6-9fa9-b7d33b99e8f3.png)

**Comment by sirrahd** [comment]
Oops, my dumb mistake. Was looking at the CSV in Excel it was changing the date format on load.

**Comment by JC5** [comment]
No problem! Glad you took the time to write such an extended bug report!
