### ISSUE TITLE
Automated money adding to Piggy Banks

### ISSUE THREAD

**Issue by Asteliks** [firefly-iii/firefly-iii#5711]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would love Firefly III to automate the process of adding a certain amount of money every month to my piggy bank. For example I would love to automatically set aside 50 Euro every month for future electronics expenses. 

Technically this could also be used as a simplified depreciation tool for home users but I digress.

### Solution

Adding the option to add a set amount of money every month to a certain piggy bank.

**Comment by JC5** [comment]
You can create a recurring transfer that can add money to a piggy bank automatically. Other automation isn't possible, or you'll have to use the API.

**Comment by Asteliks** [comment]
Yes and no unfortunately the recurring transfer cannot be to the same account and I want my account to stay true to the bank account.
