### ISSUE TITLE
Wrong budgeted amount for yearly budget 

### ISSUE THREAD

**Issue by rciupei** [firefly-iii/firefly-iii#5719]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I've added a new yearly budget (2400 eur) and also added a test expense for January (i.e. 180 eur). I'm in the monthly view for February and the amount for left is still the total amount (2400). Once I change the budgeted amount, even by 1, the amount changes to the correct one (total - 180 eur), but after a refresh/navigation away is back to the whole amount. I've recreated the issue on the demo site. 
It's a minor thing so maybe you can look at it or include it in v3. 
And thanks for the great work! :)

### Expected behaviour

1. Initial screen 
![image](https://user-images.githubusercontent.com/23429709/152687605-12c22ac5-7e93-4370-a7c2-3a8c6ca6bde1.png)
2. Change budgeted amount by 1 (now is 2401)
![image](https://user-images.githubusercontent.com/23429709/152687629-d6f0ff81-c332-46d8-9bf2-f4ec1d842114.png)
3. Decrease 1 (2400 again) - this is the expected view - remaining 2220 eur
![image](https://user-images.githubusercontent.com/23429709/152687653-71d559ed-989d-4c0d-8868-616f6551cb24.png)

### Debug information

demo website

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/discussions/5680
