### ISSUE TITLE
Enabling 2fa doesn't work

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#572]
Hi,
When I try to enable 2fa for my account and I enter the code after scanning the QR code, I get an error:

> [2017-02-16 18:34:50] testing.ERROR: PragmaRX\Google2FA\Exceptions\InvalidCharactersException: Invalid characters in the base32 string. in G:\xampp2\htdocs\firefly_develop\vendor\pragmarx\google2fa\src\Google2FA.php:289
Stack trace:
#0 G:\xampp2\htdocs\firefly_develop\vendor\pragmarx\google2fa\src\Google2FA.php(104): PragmaRX\Google2FA\Google2FA->validateSecret('')
#1 G:\xampp2\htdocs\firefly_develop\vendor\pragmarx\google2fa\src\Google2FA.php(172): PragmaRX\Google2FA\Google2FA->base32Decode('')
#2 G:\xampp2\htdocs\firefly_develop\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(221): PragmaRX\Google2FA\Google2FA->verifyKey(NULL, '458989')
#3 G:\xampp2\htdocs\firefly_develop\app\Validation\FireflyValidator.php(71): Illuminate\Support\Facades\Facade::__callStatic('verifyKey', Array)

It's because the $secret that's been retrieved from the session is empty.
I think, it's becaus it is flashed to the session in PreferencesController::code and the Javascript controller comes in and clears the session variable .
I think reflashing the session in the JavaScriptController (or some middleware) might solve this.
A quick insert in the JavaScriptController fixes it for me:
`public function __construct()
	{
		Session:reflash();
	}
`

I see that the Session::flash construct is used multiple times in the code, so maybe it has some other caveats,

**Comment by JC5** [comment]
Nice catch. That javascript controller sure introduces a lot of problems. It'll be fixed in the next release!
