### ISSUE TITLE
`no_external_url` filter has an error

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#5724]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The `no_external_url` filter is currently returning a 500 error for all queries.

`FireflyIII\Helpers\Collector\GroupCollector::FireflyIII\Helpers\Collector\Extensions\{closure}(): Argument #1 ($q1) must be of type FireflyIII\Helpers\Collector\Extensions\Builder, Illuminate\Database\Eloquent\Builder given, called in /var/www/demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php on line 277`

### Expected behaviour

No error

### Debug information

Demo site & local 5.6.14

### Steps to reproduce

https://demo.firefly-iii.org/search?search=no_external_url%3Atrue&go=

**Comment by JC5** [comment]
Weird, I specifically tested this scenario. Oh well, I'll pick it up! Should be a part of a new release over the weekend.
