### ISSUE TITLE
Percentage split for income/revenue

### ISSUE THREAD

**Issue by xMdb** [firefly-iii/firefly-iii#5730]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I'd like to see support for percentage split for income/revenue, so you are able to divvy up funds towards piggy banks/budgets easily.

### Solution

The feature will add the ability to automatically divvy up funds into budgets and/or piggy banks by percentage. For example, here is my current split:

5% Charity fund
5% Drums 
5% NAS
10% Free spending/shopping
10% Subscriptions
65% Savings

As for now, I have to manually divide these into the relevant budgets/piggy banks for every piece of income I get. It would be handy to have a feature like this. 

Thank you.

**Comment by JC5** [comment]
No, sorry. You'll have to do this yourself.
