### ISSUE TITLE
Link in email are not the same of firefly-iii resource path

### ISSUE THREAD

**Issue by marco-ragusa** [firefly-iii/firefly-iii#5736]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

My installation run under nginx reverse proxy under the sub dir https://my-ip/firefly.
When i try to send an email for the password reset, i noticied that the link inside does not contain the sub dir /firefly

Ex. https://my-ip/**firefly**/yadayadyada-password-reset

I tryed to use APP_URL in my docker env configuration but it dosen't work

### Expected behaviour

The links inside the email contains the subdir of the server

### Debug information

Debug information generated at 2022-02-08 11:17:49 Europe/Rome for Firefly III version **5.6.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.14 |
| Firefly III API | 1.5.5 |
| Build | 96, 05-02-2022 10:01:49 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 17cece58-fbdf-4c53-8ecb-10b1ec4bb930 |
| Using docker? | true |
| Layout |  |
| System TZ | Europe/Rome |
| Browser TZ | Europe/Rome |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | it_IT |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-02-01 00:00:00 |
| Session end | 2022-02-28 23:59:59 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0 |

### Steps to reproduce

1. Run firefly under nginx reverse proxy like my repo https://github.com/marco-ragusa/compose-secure-firefly
2. Send a reset password email

**Comment by JC5** [comment]
Reverse proxy's and subdirectories are a tricky combination, and this will never work right I'm afraid. Sorry.
