### ISSUE TITLE
Asset account sorting fails if drag and drop done on second (or any other than first) page on account list

### ISSUE THREAD

**Issue by BluePerfectOne** [firefly-iii/firefly-iii#5737]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In Home > Asset accounts page, if you have more than one pages of accounts, rearranging accounts in later pages (first page works just fine) will have funny consequences - all the accounts are rearranged I think unintentionally.

I would assume the code only assumes first page and does not take into account the page you're in at the moment.
This issue can be overcome by setting the Page size setting in preferences so there's no second pages, but maybe this is worth fixing also.
Other lists seem not to be affected, but I think only asset accounts (and perhaps Liabilities) are not sorted alphabetically and are handled differently.

### Expected behaviour

When dragging an account also on later pages, the account should stay on the same page. Also the ordering of the rest of the accounts should not change.

### Debug information

Debug information generated at 2022-02-08 13:41:14 Europe/Helsinki for Firefly III version **5.6.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.10 |
| Firefly III API | 1.5.5 |
| Build | 75, 09-01-2022 08:36:35 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 9c00b154-d7a5-44d6-a752-73a55dc369cc |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Helsinki |
| Browser TZ | Europe/Helsinki |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-02-01 00:00:00 |
| Session end | 2022-02-28 23:59:59 |
| Session first | 2022-01-14 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 |

### Steps to reproduce

1. Go to page "Home > Asset accounts"
 - Example: http://localhost/accounts/asset
2. Have number of asset accounts be > than the Page size setting (in preferences)
3. Go to any other page on the account list than the first one, so second or third maybe
 - Example: http://localhost/accounts/asset?page=2
4. Rearrange this list of accounts by dragging and dropping
5. Go to first page on the asset account list, and observe how the dragged account is now on first page, and all the accounts have been rearranged

**Comment by JC5** [comment]
Thanks for letting me know. I'm not going to fix this, I'm working on a new layout where this will work well.
