### ISSUE TITLE
Notification framework (slack, email etc)

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#5752]
Also needs a refactor on notifications. Right now there are four or five notifications going out with no clear idea what you can set. Some are user-specific, and some are system-specific. 

Migrate to Laravel's notification framework and make this an admin setting. Use the env file to set up two channels max and somewhere in admin enable each feature: user login, created transactions, budget alerts, stuff like that.

**Comment by sotiris-bos** [comment]
Can notifications for bills or expected expenses also be added?

Like set a due date for a payment and have firefly send notifications when the payment is about to expire?

**Comment by JC5** [comment]
Fixed in 5.8.0
