### ISSUE TITLE
Allow to Uncheck all accounts when applying rule

### ISSUE THREAD

**Issue by GurjinderSingh** [firefly-iii/firefly-iii#5767]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

When we try to apply rule against certain or all accounts, on page  "Apply rule "Rule based on transaction" all accounts selected by Default and with full Firefly date history. if one wants to run against only one account then we have to unCheck all accounts manually.

/rules/select/{rule-number-here}

### Solution

add button to un check or check all accounts listed with HTML and JavaScript.

### What are alternatives?

un check by default all accounts

**Comment by niklas152** [comment]
Hi, first of all, disclaimer:

**Never, NEVER, run code in your browser (or elsewhere) which someone send you, unless you are 100% certain you understand what it does. The below code is therfore provided "as is" and without warranty of any kind, use at your own risk and responsibility.**

With that out of the way, one possibility to achieve an uncheck-all button as you describe it would be an JavaScript bookmarklet.  
On the apply rule page, as of now (i.e., this will stop working if that ever changes), every accounts check box has an name-attribute with the value "accounts[]". This can be used to select all these checkboxes usings JavaScripts `document.getElementsByName()` function. You can then run a function on each of these checkboxes, in which you set the `.checked` attribute to false, unchecking them:

```
// get all the checkboxes on the page by their name
let checkboxes = document.getElementsByName("accounts[]");
// run a function on each of these checkboxes
checkboxes.forEach(function(elem, elemIdx, elemList) {
    // in that function, set the .checked attribute to false
    elem.checked = false;
})
```

To have this available as a "button" of sorts, create a bookmark in your browser (preferably somewhere where you can easily click it, e.g., the bookmarks bar) and as the target URL insert the code above as oneline, wrapped by `javascript:(function() { <code here> }());` - this tells your browser that the bookmark contains JavaScript code to run. Clicking that bookmark will now run the code above, unchecking all checkboxes.  
Below is a full example for what to but into the URL field of the bookmark, again, use at your own disclosure.

```javascript:(function() { document.getElementsByName("accounts[]").forEach(function(elem, elemIdx, elemList) { elem.checked = false; }); }());```

**Comment by GurjinderSingh** [comment]
thank you, I didn't thought about it :D. I can code well in JavaScript but got limited by imaginations 


Thank you
