### ISSUE TITLE
External URL Missing

### ISSUE THREAD

**Issue by ballj** [firefly-iii/firefly-iii#5768]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After upgrading to `5.6.13` - although it could have been before this.

I have noticed that the external_url field doesnt seem to display any of the urls previously entered. Other properties such as internal reference display correctly however `external_url` is missing.

If I create a new transaction and enter a url, the external_url is displayed correctly when the transaction is saved.

This looks to be because the old transactions are listed as `external_uri` in the journal_meta name field, and new transactions are `external_url`

### Expected behaviour

All URL/URIs are displayed.

### Debug information

N/A

### Steps to reproduce

1. Create transaction with URL on an older version.
2. Upgrade to 5.6.13
3. Test if URL is visible.

**Comment by JC5** [comment]
Nice find, thanks for letting me know. I forgot to extend a corrective action, which will be included in the next release.
