### ISSUE TITLE
Renaming Destination account won't update Rule mapping

### ISSUE THREAD

**Issue by diamant-x** [firefly-iii/firefly-iii#5769]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Updates on the Description name of an account (tested at least with Liabilities accounts) won't propagate to Rules assignments.
As the setup of the rule had an autocomplete on the first time, it signaled that it recognized which account it was and should potentially establish a link.

### Expected behaviour

When changing the description of an account, it changes in the rules.

### Debug information

No debug.

### Steps to reproduce

1. Create a Loan account with name X
2. Create a rule with action, assign source account to X. Let the rule suggest and autocomplete the account in question to ensure is a link, not a 'String' thing.
3. Change the Loan account name.
4. Error occurs, check the existing rule and the account name still figures the old one.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5060
