### ISSUE TITLE
Spent amount in liabilities is doubled

### ISSUE THREAD

**Issue by morremeyer** [firefly-iii/firefly-iii#5770]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When following the documentation for [liabilities as creditor](https://docs.firefly-iii.org/firefly-iii/concepts/accounts/#creditor), specifically:

> If you want to borrow your friend more money, you also need two transactions:
>
> 1. A withdrawal from your asset account into the liability.
> 2. A withdrawal from the liability to your friend (an expense account).

Say I lent a friend 100 €, the following happens:

* The transaction from the asset account to the liability is a withdrawal of 100 €
* The transaction from the liability to the expense account is a withdrawal of 100 €
* In the account overview for the liability, both transactions are shown as Withdrawals. As a result, the spent sum is displayed as 200 €, not 100 €. 
* In the liability, the Transactions list shows a sum of 0 €, but to transactions of -90 €.
* In the log on the right, for „February 2022“, it shows „Spent -180 €“

I understand why the transaction from the asset account to the liability is a withdrawal, as it's money that is removed from my assets.

It is then withdrawn again, this time from the liability, to the actual friend who I'm giving the money to.

### Expected behaviour

In the liability, I'd expect the transaction from the asset account to be a deposit as it is deposited into the liability. This might also be solvable by allowing to transfer into liabilities, but this might carry other implications.

In any case, I'd expect it to be a positive amount so that the liability itself is balanced (the current balance already correctly shows a balance of 0 € and an amount of 100 € in „Amount Due“).

### Debug information

Debug information generated at 2022-02-13 23:29:05 Europe/Berlin for Firefly III version **5.6.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.14 |
| Firefly III API | 1.5.5 |
| Build | 96, 05-02-2022 10:01:49 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 9bf1a04a-1c50-47c8-80af-82872d6995ee |
| Using docker? | true |
| Layout |  |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_GB |
| Default locale | de_DE |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-02-01 00:00:00 |
| Session end | 2022-02-28 23:59:59 |
| Session first | 2020-02-02 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0 |

### Steps to reproduce

1. Create a liability with a balance of 0
2. Withdraw any amount into the liability from an asset account
3. Withdraw the same amount to some expense account

**Comment by JC5** [comment]
Yep, I hoped nobody would notice, it's not an often-used feature 😅 .

I'll pick it up as a bug. At some point one of the transactions has to be ignored, or moving money to such a liability will have to be a transfer. I expect it to be the latter. 

Thanks for letting me know, I'll pick it up!

**Comment by morremeyer** [comment]
I like the idea of making it a transfer.

I have a gut feeling that it fits better with the current code than just ignoring one transaction, but I'm also not a PHP developer.

**Comment by JC5** [comment]
The transaction from your asset account to the liability will remain a withdrawal due to other constraints, but it'll be ignored in sums like these.

**Comment by maxfire2008** [comment]
This issues seems to persist for split transactions.

**Comment by JC5** [comment]
I'm gonna need a little bit more than that.

**Comment by maxfire2008** [comment]
When you create a split transaction
Part 1. Bank Account -> Friend $10 E.G gift
Part 2. Bank Account -> Friend's liablity $10 E.G you want them to pay back this part

Then you move $10 from the Friend's liablity -> Friend.

This displays in balance as -$30 when I think it should appear as -$20.

### Steps to reproduce
1. Create a liability with a balance of 0
2. Withdraw any amount into the liability from an asset account in a split transaction with the other part going anywhere
3. Withdraw the same amount to some expense account

**Comment by JC5** [comment]
Ah yes. You mean the balance box on the top of the page, right? That box is going to disappear in future versions, so that particular sum will not be corrected until then. Sorry for the inconvenience.
