### ISSUE TITLE
Nordigen import converts all transactions from Triodos bank to deposits

### ISSUE THREAD

**Issue by jurjendijkstra** [firefly-iii/firefly-iii#5788]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Using "import from Nordigen" where the bank is Triodos in the Netherlands, all transactions are imported as deposits. 

This is caused by function GenerateTransaction, it assumes deposit when the amount is greater than 0. Triodos always writes amounts greater than zero so the assumption withdrawal/deposit has to be based on other attributes.

### Expected behaviour

Transaction is a deposit when it has a debtor.
Transaction should be a withdrawal when it has a creditor OR when the proprietaryBankTransactionCode is "BA". 

In addition, when proprietaryBankTransactionCode is "BA" then Triodos does not specify the debtor, but in that case the debtorName can be parsed from the description. 

### Debug information

I don't think debug info is necessary in this case.

### Additional info

I have changed the sourcecode and will post a pull request. The change works fine for me, but chances are that my changes are not generic enough for other banks.

**Comment by jurjendijkstra** [comment]
I have just posted a pull request:  https://github.com/firefly-iii/data-importer/pull/57

If you want I can also give you a fragment of output from Nordigen with transactions from Triodos NL. Just let me know if you'd like that, then I will anonimize a fragment.

**Comment by JC5** [comment]
This is something you have to take up with Nordigen, not with the data importer. I'm not going to add bank-specific fixes.

**Comment by jurjendijkstra** [comment]
I will keep the bank-specific fork then.

**Comment by JC5** [comment]
I'll contact Nordigen about this.

**Comment by jurjendijkstra** [comment]
That's nice, thanks. I think that Triodos bank is doing something wrong (or different than other banks) and I don't expect that the bank will change their output soon. But I do not have accounts with other banks so I can't really compare.

**Comment by JC5** [comment]
It's the same with other banks, and one of the perks of using nordigen is that they will do the normalization.

**Comment by JC5** [comment]
This should now be working correctly, as per Nordigen in my mail.

**Comment by jurjendijkstra** [comment]
Yes they did it, I am amazed and so quickly too, wow. 

I can delete my fork now except for 1 thingy: I parse creditorName from description if creditorName is missing. That happens a lot when the payment is made on a payment terminal in a store.

I don't suppose one can enter a php expression in the "Action Value" field in an automation trigger, to set destination account to an expression which takes a substring of description? 

Else would you consider to accept a PR that gets creditorName from description when creditor is missing? It goes like:

            $entry->creditorName = explode("\\", $transaction['description'])[0];
            if (str_starts_with($entry->creditorName,'CCV*')) {
                $entry->creditorName = substr($entry->creditorName, 4);
            }

Thanks, have a nice weekend

**Comment by JC5** [comment]
No. But you can do that without a new feature, it just takes a few more rules.

**Comment by jurjendijkstra** [comment]
I don't see how, but ok, we can close this issue.

**Comment by Stooovie** [comment]
I have the same issue with Komercni Banka in Czech Republic. All amounts are positive, deposits and withdrawals are distinguiushed by creditorName (withdrawals) and debtorName (deposits). How do I fix this? Can I fix this not being a software developer? Thanks.

**Comment by JC5** [comment]
You can contact nordigen at support@nordigen.com about this.

**Comment by Stooovie** [comment]
I have no idea what I'd even ask them... I guess FFIII is way over my head. Thanks.

**Comment by JC5** [comment]
Here, I wrote the email for you. No need to thank me:

> I have an issue with Komercni Banka in Czech Republic. All amounts are positive, deposits and withdrawals are distinguished by creditorName (withdrawals) and debtorName (deposits). How do I fix this? Can I fix this not being a software developer? Thanks.

**Comment by Stooovie** [comment]
Unfortunately that's where my journey with Firefly ends:
`Unfortunately, there is nothing we can do about how the information is presented, since this is how the bank sends the data.
`

**Comment by JC5** [comment]
Sorry about that :(

Perhaps Triodos can fix their own data quality issue?

**Comment by jurjendijkstra** [comment]
Nordigen already did it for Triodos. Bummer they don't want to do the same for Komercni Banka. Is it perhaps possible they did not understand the problem?

**Comment by Stooovie** [comment]
This is what I sent to Nordigen's support:

> I'm trying to use the Nordigen API in the Firefly III open-source money tracking app to track my personal finances. 
> 
> My issue is, the app expects withdrawals to be negative numbers in "amount" but my bank (Komercni banka in Czech Republic) doesn't do that. Instead of using negative/positive amounts, the transaction is a deposit when there's a "debtorName" and a withdrawal when there's a "creditorName". Firefly III developer tells me I should contact your support to approach this issue. What can I do to fix this?

**Comment by kabukimandelux** [comment]
I've got the exact same issue with my bank. I guess there are no news regarding this? Seems to be more widespread. Would be awesome to cover this in the importer.
