### ISSUE TITLE
'Du' instead of 'Sie' in German translation / Additional German version for Du?

### ISSUE THREAD

**Issue by gathurian** [firefly-iii/firefly-iii#5795]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

The German translation is using 'Sie' and 'Ihre' in the translation, which is pretty formal. Nowadays, most applications use 'Du' and 'Deine' for a more informal/casual user experience. 

### Solution

I have seen that you are using crowdin for translation, where German is already 100% translated. Is there a possibility to add a second version, where the more informal tone is used, or is this not something that is wanted anyway?

**Comment by JC5** [comment]
Please feel free to correct the German translation, and flag entries if they are "approved". I specifically requested it to be informal at the time (other translations use informal words as well) but that knowledge may have been lost along the way.
