### ISSUE TITLE
can't remove foreign amount from transaction

### ISSUE THREAD

**Issue by kylrth** [firefly-iii/firefly-iii#5798]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I edit a transaction to remove a foreign amount using the trash icon, it doesn't actually remove the foreign amount.

### Expected behaviour

The foreign amount would disappear after removing it with the trash can icon and clicking "Update transaction".

### Debug information

Debug information generated at 2022-02-20 09:50:05 America/Toronto for Firefly III version **5.6.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.14 |
| Firefly III API | 1.5.5 |
| Build | 96, 05-02-2022 10:01:49 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | e8bb0cc8-68ce-4ca2-bfb4-d29a1a4bbc25 |
| Using docker? | true |
| Layout |  |
| System TZ | America/Toronto |
| Browser TZ | America/Toronto |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-02-01 00:00:00 |
| Session end | 2022-02-28 23:59:59 |
| Session first | 2021-10-30 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 |

### Steps to reproduce

1. Create a transaction with both domestic and foreign amounts.
2. Save the transaction.
3. Open it again to edit through the action menu.
4. Click the trash icon next to the foreign amount.
5. Click "Update transaction".
6. Observe that the foreign amount has not been removed.

**Comment by JC5** [comment]
Set the amount to zero, that should work. A fix will be part of the new release.

**Comment by evanre** [comment]
Hey @JC5 could you please take a look at it one more time? It looks as if it's still here. Was able to reproduce it on demo site:
- Create a transaction, Choose EUR Asset with amount of 1.17eur, and 1gbp as foreign value. Save
- Edit created transaction, change Asset account to GBP one, change amount from 1.17 to 1, remove foreign value. Save
- After update the foreign value stays there:
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/12615906/173119878-b406e851-e445-46db-9750-627bee125d34.png">

**Comment by JC5** [comment]
Set to 0 works fine for me. Emptying the value and the currency also works for me. Only the bin button doesn't seem to work.

**Comment by evanre** [comment]
Do I do something wrong? Can't remove the foreign amount, only while creating a new transaction.
https://user-images.githubusercontent.com/12615906/173123806-334745bf-2fe2-47de-8c84-026dd1e1741c.mp4

**Comment by JC5** [comment]
I don't know. I do the exact same thing in Firefox and Chrome and it clears out fine. What OS / browser are you on?

**Comment by evanre** [comment]
Tried on macOS (Vivaldi, Chrome), iOs (Safari), Winsows 10 (Vivaldi) 😃
