### ISSUE TITLE
Pagination on All transactions without budget

### ISSUE THREAD

**Issue by krin-san** [firefly-iii/firefly-iii#5806]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

On "All transaction without budget" page navigating to any but 1st page resets "/all" filter.

### Expected behaviour

"/all" filter should remain while browsing through pages.

### Debug information

Debug information generated at 2022-02-21 11:46:38 Europe/Berlin for Firefly III version **5.6.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.14 |
| Firefly III API | 1.5.5 |
| Build | (unknown), (unknown) |
| PHP | 8.0.15 |
| Host | FreeBSD |

| System info | Value |
| --- | --- |
| Installation ID | d72559d7-4b8d-4045-a5d4-3ec6e0db4b3e |
| Using docker? | false |
| Layout | v1 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | ru_RU |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-02-01 00:00:00 |
| Session end | 2022-02-28 23:59:59 |
| Session first | 2021-06-23 00:00:00 |
| User ID | 2 |
| User language | ru_RU |
| User locale | ru_RU |
| Attempt at "ru_RU.utf8" | false |
| Attempt at "ru_RU.UTF-8" | 'ru_RU.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0 |

### Steps to reproduce

1. Have at least 1 budget created
2. Have at least 51 transactions without assigned budget for pagination to work (can be reduced by changing "Page size" on "Settings -> Layout" page)
3. Navigate to Budgets page
4. Click on "Transactions without budget" link
5. Click on "Show all transactions ..." link
6. Navigate to 2nd page

### Additional info

Reproducible on Demo website: https://demo.firefly-iii.org/budgets/list/no-budget/all
Resets to https://demo.firefly-iii.org/budgets/list/no-budget?page=2
Workaround: Manually add "/all" in url: https://demo.firefly-iii.org/budgets/list/no-budget/all?page=2

**Comment by JC5** [comment]
Nice, will be fixed in the next release :+1:
