### ISSUE TITLE
Allow import of more than 90 days

### ISSUE THREAD

**Issue by krehl** [firefly-iii/firefly-iii#5807]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to be able to import more than 90 days using the Nordigen import.

### Solution

The user agreement endpoint has a field to enable this, but it has to be populated before the consent of the user is granted.

**Comment by JC5** [comment]
I'll put it on the list :+1:

**Comment by krehl** [comment]
I implemented the functionality myself and will create a PR after cleaning up the code :) Just FYI so that there is no double work in case someone can wait for the PR. Looking forward to your feedback.
