### ISSUE TITLE
Docker installation help

### ISSUE THREAD

**Issue by binxycraft** [firefly-iii/firefly-iii#581]
Hello. I am attempting to deploy firefly-iii with docker. I have over 30 other docker containers running on my server self-hosting other various things and really like the ease of use docker provides with upgrades and cross-compatibility. I map all of the important data to my host, and all of my containers run on the same docker network and are accessed via a reverse proxy (which is also a docker container, and provides letsencrypt certs). I do see that docker support is in early days here but wanted to see if any docker experts could help me get this one running. I do not use docker compose since I never really needed to. All of my containers are one command, and the ones that have databases are just pointed to them with a static IP. That said I wouldn't be against using it for this but I do have specific needs for my setup. I did get this working at some point with docker compose and default settings but it broke after registration. Since then I have only received 500 errors.

Here is my attempted setup without docker compose:
Pulled release 4.3.6 and extracted
```
cd firefly-iii-4.3.6
docker build -t firefly-iii .
```

```
docker run -d \
--name db_firefly \
-e MYSQL_DATABASE=firefly_db \
-e MYSQL_USER=firefly_db \
-e MYSQL_PASSWORD=secret \
-e MYSQL_RANDOM_ROOT_PASSWORD=yes \
-v /docker/db_firefly:/var/lib/mysql \
--network=dockernet \
--ip 172.18.0.X \
--restart=on-failure \
mysql:8
```

Typically I would use MariaDB but since the compose file used mysql:8 I figured it was the safer route.

```
docker run -d \
--name firefly \
-e FF_DB_HOST=172.18.0.X \
-e FF_DB_NAME=firefly_db \
-e FF_DB_USER=firefly_db \
-e FF_DB_PASSWORD=secret \
-e FF_APP_KEY=SomeRandomStringOf32CharsExactly \
-e FF_APP_ENV=production \
-v /docker/firefly:/var/www/firefly-iii/storage \
-p 9898:80 \
--network=dockernet \
--ip 172.18.0.Y \
--restart=on-failure \
firefly-iii
```

IPs/DB password have been changed.
Typically I would remove "-p 9898:80 \" after testing and access only via my reverse proxy which uses 172.18.0.X:80
I then run:
`docker exec firefly php artisan migrate:refresh --seed`
Which displays:
```
**************************************
*     Application In Production!     *
**************************************

Command Cancelled!
```

So it seems like that isn't even necessary.

I am wondering if there is anything obviously wrong with this setup? 
I have checked the logs on both containers and nothing seems to really indicate an error. I can post them if necessary.

**Comment by JC5** [comment]
Try `docker exec firefly php artisan migrate:refresh --seed --force`, it will not prompt for input.

**Comment by binxycraft** [comment]
I have it working!
Two steps:
1) I had to remove:
`-v /docker/firefly:/var/www/firefly-iii/storage \`
I was trying to model this off one of the docker compose files. I am not sure if this volume is key for persistent storage when re-installing or upgrading or if I should only be concerned about the database though.
2) As JC5 suggested:
`docker exec firefly php artisan migrate:refresh --seed --force`

```
Migration table not found.
Migration table created successfully.
Migrated: 2016_06_16_000000_create_support_tables
Migrated: 2016_06_16_000001_create_users_table
Migrated: 2016_06_16_000002_create_main_tables
Migrated: 2016_08_25_091522_changes_for_3101
Migrated: 2016_09_12_121359_fix_nullables
Migrated: 2016_10_09_150037_expand_transactions_table
Migrated: 2016_10_22_075804_changes_for_v410
Migrated: 2016_11_24_210552_changes_for_v420
Migrated: 2016_12_22_150431_changes_for_v430
Migrated: 2016_12_28_203205_changes_for_v431
Seeding: AccountTypeSeeder
Seeding: TransactionCurrencySeeder
Seeding: TransactionTypeSeeder
Seeding: PermissionSeeder
```
I am now able to access the website at my dockerhostIP:9898 - seems to be a bit messed up through my reverse proxy but I can figure that out. Maybe I need to set FF_APP_URL or whatever it is.

**Comment by binxycraft** [comment]
Final notes:
I remove the firefly-iii container completely and started it again from scratch and all the data I entered was still there and my account was still active so I believe the data is persistent since the database is. My reverse proxy still does not display the page correctly. It points to 172.18.0.Y and all of my containers are setup in a similar fashion but none of the others seem to have this issue. I did try changing the APP_URL in the .env file inside my docker container to the URL the reverse proxy gives which is https://xxx.yyy.com but it did not seem to do anything. The page looks like this:
http://imgur.com/a/dQV5w
It is not the biggest deal since I can access it through port 9898 on the host but I would rather keep that port closed so if anyone has an ideas let me know!

**Comment by JC5** [comment]
Try changing `APP_FORCE_ROOT=` to your desired host name and protocol.

**Comment by binxycraft** [comment]
Thanks for the fast responses!
I went ahead and set both APP_URL and APP_FORCE_ROOT to https://firefly.domain.com but it still looks the same. It also does redirect to https://firefly.domain.com now when I access it via http://hostIP:9898 (still with the weird layout). I am using an incognito tab to avoid cache issues.

**Comment by JC5** [comment]
There might be something in this issue?

https://github.com/firefly-iii/firefly-iii/issues/566

**Comment by windhamwong** [comment]
I have worked out the issue. Please try this:
`APP_FORCE_ROOT=.`
