### ISSUE TITLE
Search query with no_notes:true breaks after editing transaction

### ISSUE THREAD

**Issue by krin-san** [firefly-iii/firefly-iii#5810]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Searching for transactions with `no_notes:true` doesn't return transactions which notes were changed and then removed (Notes field empty). This probably happens because `no_notes:true` checks for `notes:null` while an empty edited Notes field saves an empty string `notes:""`.

### Expected behaviour

Either: `no_notes:true` shows both transactions without a note `notes:null` and with empty notes.
Or: Removing Notes field content in edited transaction saves `notes:null` instead of an empty string.

### Debug information

Debug information generated at 2022-02-23 10:04:12 Europe/Berlin for Firefly III version **5.6.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.14 |
| Firefly III API | 1.5.5 |
| Build | (unknown), (unknown) |
| PHP | 8.0.15 |
| Host | FreeBSD |

| System info | Value |
| --- | --- |
| Installation ID | d72559d7-4b8d-4045-a5d4-3ec6e0db4b3e |
| Using docker? | false |
| Layout | v1 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | ru_RU |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-02-01 00:00:00 |
| Session end | 2022-02-28 23:59:59 |
| Session first | 2021-06-23 00:00:00 |
| User ID | 2 |
| User language | ru_RU |
| User locale | ru_RU |
| Attempt at "ru_RU.utf8" | false |
| Attempt at "ru_RU.UTF-8" | 'ru_RU.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0 |

### Steps to reproduce

1. Search for existing transactions with `no_notes:true` filter: https://demo.firefly-iii.org/search?search=coffee+no_notes%3Atrue
2. Add a note to the first transaction in search results
3. Refresh search page – transaction is gone, obviously
4. Remove the note from the edited transaction
5. Refresh search page again

### Additional info

https://github.com/firefly-iii/firefly-iii/blob/main/app/Helpers/Collector/Extensions/MetaCollection.php#L490
Edited transaction on Demo website: https://demo.firefly-iii.org/transactions/show/307

**Comment by JC5** [comment]
Nice find, and the solution is presented as well! 😍 

Will pick it up! 👍🏻

**Comment by krin-san** [comment]
Was it fixed? I still see the same behavior after an update.

Created 3 transactions on Demo page: 1 without note, 1 with initial note and 1 with initial note manually removed.
This should show 2 transactions https://demo.firefly-iii.org/search?search=%235810+test+no_notes%3Atrue
And that should show only 1: https://demo.firefly-iii.org/search?search=%235810+test+any_notes%3Atrue

**Comment by JC5** [comment]
Apparantly not, I'll check what happened.

**Comment by JC5** [comment]
A fix will be part of the new release.

**Comment by krin-san** [comment]
Queries above now work as expected on 5.6.16.
@JC5, thank you for fixing it!
