### ISSUE TITLE
Allow a skip of greater than 31 days for bills

### ISSUE THREAD

**Issue by patleclair19** [firefly-iii/firefly-iii#5812]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

My phone plan is on a 90 day basis (not the same as 3 months), but I can't create a bill for it because the form says "The skip must be less than or equal 31":

![image](https://user-images.githubusercontent.com/65136194/155372387-bbc2e4a8-3fdf-465d-b80a-168e43099ba1.png)

### Solution

Changing the form validation to allow a skip of up to 90 days would allow these bills to be entered.

**Comment by JC5** [comment]
Or, set it to 30 days and skip 2.

**Comment by JC5** [comment]
Wait that doesn't work. Sorry about that. This will not change in the foreseeable future.
