### ISSUE TITLE
Allow transactions with same source and destination

### ISSUE THREAD

**Issue by dneez** [firefly-iii/firefly-iii#5815]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hi.
My bank is using a transaction with my IBAN as both source and destination for interest payments.
Right now these are discarded with error "source and destination are the same" when importing.
I would like to have an option to import those.

### Solution

Have an option to allow transactions with the same source and destination.

### What are alternatives?

Currently I create these manually using fake IBAN as source.

**Comment by JC5** [comment]
This will not be possible. Since your bank pays the interest, they're the source of the money and they should adjust the transaction.
