### ISSUE TITLE
Installatie op windows / xampp - no suggest option does not exist

### ISSUE THREAD

**Issue by StefKalders** [firefly-iii/firefly-iii#583]
Ik ben de installatie aan het volgen op een xampp server. Bij het installeren met composer.

Ik krijg dan de volgende foutmelding: 

`The "--no-suggest" option does not exist.`

Als ik de no suggest option verwijder begint ie wel gewoon met installeren maar geeft op het einde deze fout:
```

> php artisan key:generate
**************************************
* Application In Production! *
**************************************

Do you really wish to run this command? (yes/no) [no]:
>

[Symfony\Component\Console\Exception\RuntimeException]
Aborted


Script php artisan key:generate handling the post-create-project-cmd event returned with error code 1
```

**Comment by JC5** [comment]
Alright the `--force` option  does not apply, because I had the wrong command in mind.

You can run it manually, and then enter "yes". You can re-run the installation up to the point where you get the error, then enter the command by hand.

`php artisan key:generate`

The `--no-suggest` has been removed from the installation guide, it does not belong there indeed!

**Comment by StefKalders** [comment]
That worked. Firefly is running now, thanks! I did encounter the following during the initialization the database part:

```
C:\xampp\htdocs\firefly-iii>php artisan migrate:refresh --seed
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migration table not found.
```

after typing yes a few times it migrated and seeded, but it was a bit confusing.

Thanks again for the help and the work!

**Comment by JC5** [comment]
It is confusing, I agree. The reason you get these questions is because the `.env` file mentions the environment is "production".

I will upgrade the installation guide and the example `.env` file so this is handled better.

Thanks for the feedback, and let me know when you have more questions :+1:
