### ISSUE TITLE
Recurring transaction at end of the month

### ISSUE THREAD

**Issue by ChrisCarini** [firefly-iii/firefly-iii#5830]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hi @JC5 !

I would like to add a `Recurring transaction` that is at the end of each month (ie, Feb 28th, Mar 31st, Apr 30th, etc), but there appears to be no option to specify 'end of the month' in the 'type of repetition' drop down. Could this possibly be added?

### Solution

On the `Recurring transactions` page, the `Type of repetition` drop down would have a "Every month on the last day" option.

### What are alternatives?

None, as far as I can tell. 😢 

### Additional context

I know my bank will pay out interest on the last day of every month, and I would like to create a 'one cent' recurring transaction to make adding this transaction easier for me (I would only have to go in and edit the precise amount of interest paid out by my bank, with the rest of the fields accurately set).

**Comment by ChrisCarini** [comment]
**UPDATE re: _What are alternatives?_**

I just thought of an alternative - for each account, I could create a separate 'recurring transaction' for every month, each set to "Every year on X" option (ie, one for "Every year on Jan 31st", one for "Every year on Feb 28th", one for "Every year on Mar 31st", etc etc... for all 12 months).

Creating a yearly recurring transaction for each month is pretty sub-ideal for me, as I have many accounts I would like to do this for (say 10), and that requires creating 12 of these for each account (120, if I had 10 accounts I want to do this for).

**Comment by JC5** [comment]
What's your use case exactly?

**Comment by ChrisCarini** [comment]
@JC5 - I want a transaction on each of my bank accounts to record the monthly interest (which is paid on the last day of the month). Creating a recurring transaction would make this process much easier for me.

**Comment by JC5** [comment]
Alright, I'll see what I can do.

**Comment by ChrisCarini** [comment]
Awesome, thank you! 😄

**Comment by JC5** [comment]
Sorry, I had to check this.

This already happens correctly. If you set up a recurring transaction on the 31st, 30th or 29th and the month does not have that day, it will be automatically corrected to the correct day.

**Comment by ChrisCarini** [comment]
Sounds good - I have just created several reoccurring transactions set to start on 2022-03-31 (and set to `Every month on the 31(st/nd/rd/th) day`), and will check that transactions are created on 2022-03-31, and 2022-04-30. I will set a reminder for myself to follow up on 2022-05-01 to check the 2022-04-30 transactions are created as expected. I will reply back with my findings - thank you, once again, @JC5 !

**Comment by ChrisCarini** [comment]
As promised, following up here - as it is now May 1st, i can confirm that two reoccurring transactions were created on the desired days (March 31st, and April 30th). All is well.
