### ISSUE TITLE
net worth predictions / estimates  based on repeated income/outcome

### ISSUE THREAD

**Issue by aiddroid** [firefly-iii/firefly-iii#5838]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- I really hope firefly-iii have a net worth prediction based on repeated income/outcome for working class people.Maybe it's not very exactly, but really helpful for finacial management.

### Solution

Use a chart for net worth prediction.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/#prediction-forecasting-future-gazing
