### ISSUE TITLE
Can only add one transaction per tag

### ISSUE THREAD

**Issue by Zsub** [firefly-iii/firefly-iii#584]
At least for the balancing and partially balanced tags. Will do some more research and update this issue with my findings, as both types should allow more than one transaction.

**Comment by JC5** [comment]
Balancing act tags accept one withdrawal and one transfer, maximum. Advance payment tags accept one withdrawal and any number of deposits.

**Comment by Zsub** [comment]
I know, but even though I add the balancing tag to the withdrawal and save the withdrawal, the tag does not get added to the withdrawal. The balancing tag also only shows the transfer, not the withdrawal.

**Comment by JC5** [comment]
Aha! I didn't realize. Let me know, I will look into it!

**Comment by JC5** [comment]
I think the tags work as intended, but the lists don't display all transactions: the transaction collection routine is probably broken.

**Comment by Zsub** [comment]
Ok so I missed your previous comment about the one withdrawal 😳

Thus it is expected a balancing tag won't work for me in this way. Sorry for the noise!

**Comment by JC5** [comment]
No problem!
