### ISSUE TITLE
Recuring transactions set to occur on every 31st won't run on feb 28 / different dates as well

### ISSUE THREAD

**Issue by WorldTeacher** [firefly-iii/firefly-iii#5841]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Sometimes, the recurring transactions don't trigger as they should.
I have a transaction (1) to occur on every 2nd of the month and "Create the transaction on the next Monday instead", as well as one (2) that should trigger on every 31st of the month "Created the transaction on the previous Friday"

Alternate Title (because of transactions being skipped): Add a way to check if a recurring transaction that should've triggered a few days ago, was actually triggered (see logs.txt for details)

### Expected behaviour

The transactions should trigger every month.

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.16 |
| Firefly III API | 1.5.5 |
| Build | 107, 28-02-2022 17:46:44 CET |
| PHP | 8.0.16 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | fe9a88e7-efbd-4106-a117-e83781c3bf62 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-03-01 00:00:00 |
| Session end | 2022-03-31 23:59:59 |
| Session first | 2021-08-25 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0 |

### Steps to reproduce

1. Create transaction to repeat on 31st
2. Wait
3. See it sometimes not working

### Additional info

[log.txt](https://github.com/firefly-iii/firefly-iii/files/8164309/log.txt) <- This is the log of my crontab firing, (or not... as seen on Feb. 28th) 
Transaction (1)
![image](https://user-images.githubusercontent.com/41587052/156237022-d588b5c4-2864-4d7d-9a05-d083cc46f498.png) Transaction description
![image](https://user-images.githubusercontent.com/41587052/156237055-ac9bed5d-e9fd-45cc-b1a4-a76f01a3cf9c.png) Expected Withdrawals according to Firefly
![image](https://user-images.githubusercontent.com/41587052/156237203-c86ad438-ca76-448f-9150-684f65af60f5.png) The transactions that happened

Transaction (2) This could be explained by the crontab not firing because of something that appears to have happened on my server that day
![image](https://user-images.githubusercontent.com/41587052/156237322-fa09bc5f-99f4-40ea-8b3a-9f5239ba5bbe.png)
![image](https://user-images.githubusercontent.com/41587052/156237338-a4feceef-7142-4a6d-a392-066eb77d9332.png)
![image](https://user-images.githubusercontent.com/41587052/156237348-58c4b7cd-5727-4051-aec4-5a8b4eafddb4.png)

**Comment by JC5** [comment]
Since there are no log entries on February 28th, I'm going to assume this is your mistake, not mine. Especially since I can spot this error on the 28th: `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` Sorry about that.

You can force the cron job to run on a specific day by using `php artisan firefly:cron --force --date=2022-02-28` where you can ofcourse, change the date as you see fit.

> Add a way to check if a recurring transaction that should've triggered a few days ago, was actually triggered 

You already seem to have found a way to check this. 😉

**Comment by WorldTeacher** [comment]
>  Add a way to check if a recurring transaction that should've triggered a few days ago, was actually triggered
> 
> You already seem to have found a way to check this. 😉
What I meant by that was a feature for Firefly, which checks if a transaction, which was supposed to be triggered, was actually triggered and if not, trigger it (though I can see that being hard to code)

> Since there are no log entries on February 28th, I'm going to assume this is your mistake, not mine. Especially since I can spot this error on the 28th: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? Sorry about that.

Yeah, I wrote sth along the lines of that over at my Gitter question

Would that `PHP artison...` work in Docker on Unraid?
Right now, I'm using a plugin to fire the cronjobs every few hours, and it only fails when the docker is offline (it was back then on feb 28, I checked some other log, all of my Dockers were down.

**Comment by JC5** [comment]
> What I meant by that was a feature for Firefly, which checks if a transaction, which was supposed to be triggered, was actually triggered and if not, trigger it (though I can see that being hard to code)

it’s not hard to code but it’s not something that’s useful. I mean, if i were to write code that could make 100% sure that a transaction gets created when it’s created and be fail-safe too, why not use that code in the first place?

and if I were to write a check that would run in hindsight it needs either the same crown mechanism as the first check (which is subject to the same failures) or write a second type of check which would be prone to it’s own problems and maintenance load.

**Comment by WorldTeacher** [comment]
okay, thanks for letting me know ^^
