### ISSUE TITLE
Static colors of bills pie chart on dashboard

### ISSUE THREAD

**Issue by yannik-b** [firefly-iii/firefly-iii#5846]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Currently the "Bills" pie chart on the dashboard has blue and green color. When you have paid and unpaid bills, the blue part shows unpaid bills, the green part shows paid bills. That's good - you can see, how much is unpaid on the first look. 

In my opinion it is not so simple anymore when ALL bills are either paid or unpaid. In this case the color of the whole pie is always blue. So, essentially, the pie chart tells me "All bills share the same state", but it shows not "All your bills are unpaid" or "All your bills are paid, well done!", I have to hover over the pie to see that.

### Solution

I'd like to have a static green color for "paid" bills and the static blue color for "unpaid" bills, so I can look at the pie chart and see all green, so I know "Yes, all paid".

**Comment by JC5** [comment]
I’m going to drop this pie chart in the new layout, and I won’t be able to fix it until then.
