### ISSUE TITLE
Not possible to re-add currency after removing it.

### ISSUE THREAD

**Issue by therealeldaria** [firefly-iii/firefly-iii#5852]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I removed all currencies that I thought I would not need. (I know stupid)
However now I wanted to add Pound sterling again, but it tells me "The code has already been taken."

### Expected behaviour

If currency is removed I should be able to add it again.

### Debug information

Debug information generated at 2022-03-06 20:22:05 Europe/Stockholm for Firefly III version **5.6.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.16 |
| Firefly III API | 1.5.5 |
| Build | 113, 02-03-2022 19:39:22 CET |
| PHP | 8.0.16 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | e5214ce2-c15d-410d-98d2-74d9c8820ae2 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Stockholm |
| Browser TZ | Europe/Stockholm |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | sv_SE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-03-01 00:00:00 |
| Session end | 2022-03-31 23:59:59 |
| Session first | 2022-02-13 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 |

### Steps to reproduce

1. Remove one or more currencies.
2. Try to add a currency that already existed.
3. Error message

**Comment by therealeldaria** [comment]
I was able to fix it by "undeleting" them in the database.
update transaction_currencies set deleted_at = NULL;

**Comment by JC5** [comment]
Thanks, that’s something that should be possible without having to resort to database queries.

**Comment by JC5** [comment]
Closing "fixed" issues for upcoming release.
