### ISSUE TITLE
Use Nordigen existing notes

### ISSUE THREAD

**Issue by cocox** [firefly-iii/firefly-iii#5853]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I will be usefull that with nordigen integration you can choose from bank accounts already linked in nordigen. Now, when you put the secret id and key, it asks you to add a new bank. It should retrieve allreary added ones.

### Solution

List nordigen banks to link them

**Comment by JC5** [comment]
Good idea, I'll write it down!

**Comment by diamant-x** [comment]
One doubt about this, when you say 
"choose from bank accounts already linked in nordigen"
Do you mean the connections done in the nordigen website? As per nordigen documentation, those connections aren't 'added to your account' but just linked in the website. It's right in their dashboard note:
![image](https://user-images.githubusercontent.com/7346338/163142031-958dd68c-3e3b-4761-8a39-158d9554a683.png)

Maybe I misunderstood. Thanks!

**Comment by JC5** [comment]
No you're right, I can't access those.
