### ISSUE TITLE
Filter reconciled operations

### ISSUE THREAD

**Issue by RaijinDS** [firefly-iii/firefly-iii#5862]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I find that it would be useful to be able to filter the reconciled and unreconciled transactions.

### Solution

This could be a new keyword in the search engine.

Ex : is_reconciled:true

**Comment by JC5** [comment]
:+1:

**Comment by JC5** [comment]
Is available in 5.8.0 as `reconciled:true`
