### ISSUE TITLE
"Firefly III is unable to format monetary amounts because your server is missing the required packages. There are instructions how to do this." Wiki page link broken.

### ISSUE THREAD

**Issue by YosypC** [firefly-iii/firefly-iii#5870]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The link "[instructions how to do this](https://github.com/firefly-iii/help/wiki/Missing-locale-packages)." is broken.

### Expected behaviour

Maybe it should point to [this one](https://docs.firefly-iii.org/firefly-iii/advanced-installation/locales/)?

### Debug information

Not needed, I guess

**Comment by JC5** [comment]
Ah yes, i will pick this up!

**Comment by demianrey** [comment]
what system do you use?

**Comment by YosypC** [comment]
> what system do you use?

Server on Debian 11
Clients Firefox on W10 and Android 9

**Comment by demianrey** [comment]
> > what system do you use?
> 
> Server on Debian 11 Clients Firefox on W10 and Android 9

I have Ubuntu and it solved by installing this:
`apt install locales-all`

**Comment by JC5** [comment]
Don't do that. That installs a billion languages while you just need the one. It takes a lot of room as well.

**Comment by demianrey** [comment]
> 

so what would be the command?, check and the locales-all package size is 220Mb, and on my server it didn't take even 1 minute to install

**Comment by JC5** [comment]
Just install the language you need.

**Comment by JC5** [comment]
Closing "fixed" issues for upcoming release.
