### ISSUE TITLE
Reactivated accounts are not displayed on the startpage

### ISSUE THREAD

**Issue by AntiiHeld** [firefly-iii/firefly-iii#5874]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I deactivate and reactivate an existing account, it still does not appear on the home page. I created a short YouTube video because my English is not so good and I am not so familiar with bug reports. I hope this is ok as well.

### Expected behaviour

That the account is displayed again on the home page when I activate it.

### Debug information

Debug information generated at 2022-03-10 08:49:51 Europe/Berlin for Firefly III version **5.6.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.16 |
| Firefly III API | 1.5.5 |
| Build | (unknown), (unknown) |
| PHP | 8.1.2 |
| Host | WINNT |

| System info | Value |
| --- | --- |
| Installation ID | cf1a3ec6-56d1-4e36-a920-8be3534f9a3f |
| Using docker? | false |
| Layout | v1 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-03-01 00:00:00 |
| Session end | 2022-03-31 23:59:59 |
| Session first | 2022-02-22 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de-DE |
| Attempt at "de-DE.utf8" | 'de-DE.utf8' |
| Attempt at "de-DE.UTF-8" | 'de-DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0 |

### Steps to reproduce

[I have created a short YouTube video in which I show the Bug.](https://www.youtube.com/watch?v=mx1S_wNobio)

### Additional info

I was also able to reproduce this error on the Firefly demo page.

**Comment by JC5** [comment]
You can change which accounts you want on the front page in your preferences. They are not added by default.
