### ISSUE TITLE
Uploading file fails silently 

### ISSUE THREAD

**Issue by simon-watiau** [firefly-iii/firefly-iii#5883]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

(First, thanks for your amazing work !) 

**Reproduced on the demo website:**
When uploading a file too big, it fails silently.
no error, just the file is not on the transaction.

**Not reproduced on the demo website:**
On my local installation (behind a nginx reverse proxy) the upload icon shows up next to the transaction, but when opening the details the file is not there.
I do have a line in the `attachments` table, but without md5, mime type, size and with uploaded=0 and the file is not in the upload folder.

### Expected behaviour

I expected an error on upload preventing me from continuing.

### Debug information

```
[...] client intended to send too large body: 1368393 bytes, [...] "POST /api/v1/attachments/27/upload HTTP/1.1" [...]
```

### Steps to reproduce

1. upload a large file (tested with a 1.4MB pdf file)

**Comment by JC5** [comment]
Thanks for the compliments! This is a bug, but it won't be fixed until the new layout unfortunately.
