### ISSUE TITLE
Recurring transactions over the weekend.

### ISSUE THREAD

**Issue by hiagodotme** [firefly-iii/firefly-iii#5907]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi all, I create a recurring transaction for the 20th (Sunday now). But in the weekend option I marked to create the previous Friday. The date preview shows today 18, but it only created the day's explicit transactions. I'm on the latest version 5.6.16.

### Expected behaviour

Hope the feature works or that I identify where I'm going wrong.

### Debug information

There are no errors in the logs

### Steps to reproduce

1. create a weekend transaction.
3. in the selectbox inform to create a Friday before.
3. in the metadata put non-existent tags and a non-existent category.
5. when running cron it will not work.

**Comment by JC5** [comment]
The first date for this recurring transaction is 2022-03-20, but by changing the day to the Friday before) will change the date to 2022-03-18.

That’s before the 20th and before the first date. So this recurring transaction will not fire in march (despite the promise). 

Edit it and set the first date to 2022-02-20. Then it will work if you run the cron again (with force).

**Comment by hiagodotme** [comment]
I was reading the source code, came to complement my issue and saw your answer. Thanks.
