### ISSUE TITLE
Direct links from dashboard to categories

### ISSUE THREAD

**Issue by paulens12** [firefly-iii/firefly-iii#5908]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

The dashboard contains a very useful category chart but it's not interactive.

### Solution

There is a lot of potential for improvement in various screens in Firefly to make it more interactive: sorting, filtering, etc. I'm suggesting merely adding a few hyperlinks and that would be a huge step forward requiring (hopefully) little effort.

The idea is to make each category in the main dashboard chart clickable - clicking on a category would jump to the transaction list for that particular category (`/categories/show/<id>`).

### What are alternatives?

As it stands now, the same functionality can be achieved by clicking the "Categories" button and then the category title. However, that's 2 clicks and 2 page reloads when it could be 1.

Besides, it can be hard to find the right category in the list especially if you have to go through this navigation repeatedly or just have visually similar category names.

### Additional context

The titles (painted over in red) and/or the bars could be clickable. From UX perspective I think it's best if they both are - for high bars it's easier to click the bar, for low bars it's easier to click the title.
![image](https://user-images.githubusercontent.com/3685325/158997271-a98f49b0-3b3c-4e2a-920d-b37356bbfb77.png)

**Comment by JC5** [comment]
I’m working on a new layout where stuff like this is possible. As such it’s a “wontfix” for now but rest assured this will be possible in the future.
