### ISSUE TITLE
Drop LDAP support

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#5911]
See title. Sorry guys.

**Comment by viharm** [comment]
Is there anything we can do to help?

**Comment by JC5** [comment]
What did you have in mind?

**Comment by viharm** [comment]
> What did you have in mind?

It would be good to know why LDAP was dropped. Then, if needed maybe one us in the community can help with a PR or something.

**Comment by JC5** [comment]
I dropped LDAP support because I was solving authentication- and protocol related puzzles already solved by authentication tools like Keycloak and Authelia.

Despite excellent support from an LDAP package creator I wasn't able to replicate or solve the issues the community presented me with. Since no solution seemed to be forthcoming I dropped the problem alltogether. 

The code of Firefly III is simpler and lighter for it, it requires less packages and less maintenance, and the burden of getting exotic LDAP servers to work is now with the user, not with me.

**Comment by viharm** [comment]
Understood. It is, of course, your prerogative. However you pointed out that the burden is with the user. Would you be able to point out how the user could integrate with LDAP? Is there an authentication mechanism I could modify to work with my _OpenLDAP_ directory server?

**Comment by JC5** [comment]
Not inside Firefly III, no. One way would be to set up Authelia with LDAP and use the remote user option.

- https://docs.firefly-iii.org/firefly-iii/advanced-installation/authentication/#remote-user
- https://www.authelia.com/docs/configuration/authentication/ldap.html

**Comment by viharm** [comment]
Awesome! I read up on Authelia, and it looks great! Definitely worth a try. Once done, I'll post an example configuration for inclusion in the docs. Thanks.

**Comment by HappyHepo** [comment]
As I'm currently using LDAP authentication, how can i switch to remote user without creating a new user?
Is it sufficient to supply the same username?

**Comment by JC5** [comment]
Yes, the same username is enough.
