### ISSUE TITLE
Upgrading from 4.3.3 fails

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#592]
I'm trying to upgrade from 4.3.3 to 4.3.6. Unfortunately I'm getting following error:
```
php artisan migrate --env=production
PHP Fatal error:  Uncaught ReflectionException: Class Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables does not exist in /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php:749
Stack trace:
#0 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): ReflectionClass->__construct('Illuminate\\Foun...')
#1 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('Illuminate\\Foun...', Array)
#2 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('Illuminate\\Foun...', Array)
#3 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Application->make('Illuminate\\Foun...')
#4 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#5 /var/www/firefly-dev in /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 749
```
Rolling back to 4.3.4 works fine. So 4.3.5 messes with my setup.

**Comment by JC5** [comment]
Which procedure did you follow, exactly? It might be necessary to do a composer update in between somewhere.

**Comment by skibbipl** [comment]
I use official git way of upgrading:
```
git pull
rm -rf bootstrap/cache/*
php artisan migrate --env=production
php artisan cache:clear
php artisan firefly:upgrade-database
```
At which step I should use `composer update`? Can you update the documentation?

**Comment by JC5** [comment]
I can, and I will. The problem is caused by the upgrade to Laravel 5.4, which isn't backwards compatible. 

The command I meant was composer install, and it has to be run twice.

This should work:

* `git pull`
* `rm -rf bootstrap/cache/*`
* `rm -rf vendor/`
* `composer install --no-scripts --no-dev`
* `composer install --no-dev`
* `php artisan migrate --env=production`
  * Answer yes when asked.
* `php artisan cache:clear`
* `php artisan firefly:upgrade-database`

**Comment by skibbipl** [comment]
Yup, this worked like a charm. Thanks!
Note to myself - read changelogs.
