### ISSUE TITLE
Invert Rule Trigger

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [firefly-iii/firefly-iii#5920]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to apply a rule only if certain things are _not_ present. For example, I would like to tag all transactions where the description contains "Tesla", but only if they do not also contain "Loan". 

### Solution

Add the ability to invert any trigger. When inverted is set on "Description contains: loan" it will only run when the description _does not_ contain "loan".

The UI could look similar to:
![image](https://user-images.githubusercontent.com/1719461/159327730-58934639-f3f1-429e-9086-3ab7eb9f3fbb.png)

This rule would tag a transaction with the description of "Tesla Inc Supercharger", but not "Transfer to Tesla Loan".

### What are alternatives?

I can't find any alternative in the documentation for what I'm trying to do, if I missed something please point it out.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Will there be an option for does not contain? 


I'm still setting everything up, but Firefly is damn impressive.

**Comment by Adrian-at-CrimsonAuzre** [comment]
> Sorry no, the list is long enough as it is.

That's why I think having an invert option would be useful, instead of options like "Has a bill" and "Has no bill", you would select "Has a bill" and check the invert box. You can get twice the options without actually having to list them.

**Comment by JC5** [comment]
You have to understand I still have to program and maintain both options.

**Comment by Adrian-at-CrimsonAuzre** [comment]
I understand. Were I a PHP dev instead of a Django dev I would offer to help.
