### ISSUE TITLE
Showing Notes in Transactions -> withdrawal or deposits

### ISSUE THREAD

**Issue by lopiv2** [firefly-iii/firefly-iii#5924]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be a nice idea to show the Transaction Notes in the withdrawal list, just because when you import data from CSV for example, descriptions are not very descriptives sometimes, and If you add a rule finding movements by Description, you would be able to add some notes to these transactions and display them in the list.

### Solution

A new field to the withdrawal list or deposits to show the notes, because right now it is not showing.

**Comment by JC5** [comment]
I won't be able to do this in the current layout, but the new layout I'm working on currently will be able to do it.
