### ISSUE TITLE
Feature Request: Option to show/hide categories and tags in net worth

### ISSUE THREAD

**Issue by klejejs** [firefly-iii/firefly-iii#5925]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Currently, accounts in Firefly have this nice checkbox to "Include in net worth" their values. It would also be nice to add this possibility to categories and tags.
I have some transactions that are just "going through" and they do not impact my real statistics, so it would be nice to hide those.

### Solution

Add the "Include in net worth" checkbox for categories and tags.

### What are alternatives?

Are there any? I'd be happy to hear about them in case I have missed already existing functionality.

**Comment by JC5** [comment]
No, that's not something I'm going to add, sorry.

**Comment by klejejs** [comment]
Ok, I understand! Would you accept a PR for this functionality, or is it so that you don't want this to be implemented at all?

**Comment by JC5** [comment]
No that's alright, thanks. I have to rewrite lots of code over there so I'd rather get around to it in due course myself.

**Comment by klejejs** [comment]
Ok, thanks! Does that mean that "wontfix" tag is for the near future?
I won't have much time in the next few weeks but after that, I can look into it.
