### ISSUE TITLE
Replace drop-down-field in creation of recurring transactions

### ISSUE THREAD

**Issue by DunklerPhoenix** [firefly-iii/firefly-iii#5929]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

On the page /recurring/create the fields ffInput_source_id and ffInput_destination_id are select fields.

### Solution

It would be nice if these select fields are input fields with the same auto-fill feature as in creating withdrawal or deposits

**Comment by JC5** [comment]
Sorry, this behaviour will remain the same.

**Comment by DunklerPhoenix** [comment]
👌
