### ISSUE TITLE
[Suggestion] Budgets and spending graph

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#593]
I find this chart a little bit misleading. I often cannot tell on first sight whether I overspent money or I'm still in the budget. What I suggest is to modify graph to display something like this:
![obraz](https://cloud.githubusercontent.com/assets/4746858/23264662/6f9ad5c4-f9e2-11e6-9478-811f2436a9d3.png)
It's a stacked bar chart. If spending is less or equal to budget put the budget bar in the background. If spending is over the budget put the spending bar in the background and the budget bar over it.
However I'm not sue if chart.js supports this kind of manipulations on charts.

**Comment by JC5** [comment]
Yeah that chart is far from perfect. Your idea is what I had in mind originally but I never managed. I'll see what's possible.

**Comment by JC5** [comment]
Alright I've updated the chart a bit, you can see what it would look like on the [demo site](https://firefly-iii.nder.be/).

**Comment by skibbipl** [comment]
This is exactly how I imagined it. But perhaps you could make the yellow bar more "redish"? After all overspending budget should raise red flag.

**Comment by JC5** [comment]
It's a single set of colours for all charts (to keep the colours consistent), and I need to tinker with them for just one chart. I have to see what works. Personally, I don't think the yellow is too bad.

**Comment by skibbipl** [comment]
OK, I thought it can be configured separately. No problem.

**Comment by nhaarman** [comment]
I modified this snippet in `BudgetController/frontpage.php`:

```php
/** @var Budget $budget */
        foreach ($budgets as $budget) {
            // get relevant repetitions:
            $limits   = $this->repository->getBudgetLimits($budget, $start, $end);
            $expenses = $this->getExpensesForBudget($limits, $budget, $start, $end);
            foreach ($expenses as $name => $row) {
                $chartData[0]['entries'][$name] = $row['spent'] - $row['left'];
                $chartData[1]['entries'][$name] = $row['left'];
                $chartData[2]['entries'][$name] = $row['overspent'];
            }
        }
```
To be exact, I subtraced `left` from `spent` in the chart. This way the height of the bars is always at the budget limit, and the `spent` + `left` bars fill this (i.e. `spent + left == budgetlimit`).
When you spent too much in the budget, the bar now grows higher than the budget limit with that overspent amount.

This is what I see would be the correct behavior for these charts.

**Comment by JC5** [comment]
You're right! The chart does not do that. But it used to. So it seems you have fixed a bug! ;-).

I'll get right on it.

**Comment by nhaarman** [comment]
Awesome! Thanks :)
