### ISSUE TITLE
Replace drop-down-field for selecting bills

### ISSUE THREAD

**Issue by DunklerPhoenix** [firefly-iii/firefly-iii#5930]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

On all creating pages where bills can be set select-fields are used.

### Solution

It would be nice if these select fields are input fields with the same auto-fill feature as in selecting bank accounts, just for bills

**Comment by JC5** [comment]
Sorry, this behaviour will stay the same.

**Comment by DunklerPhoenix** [comment]
Okay :)
