### ISSUE TITLE
Request for reporting functionality

### ISSUE THREAD

**Issue by alei643** [firefly-iii/firefly-iii#5931]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

When I use the report function, I find that the transfer is recorded in the income category. 
I think the transfer should be counted separately.

### Solution

same

**Comment by JC5** [comment]
If you add the destination account to the report, the transfer will not be reported at all. Otherwise, this behaviour will not change.
