### ISSUE TITLE
Multiple currency accounts makes balance card hard readable

### ISSUE THREAD

**Issue by DunklerPhoenix** [firefly-iii/firefly-iii#5932]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Accounts in multiple currencies make the balance card in overview very hard readable.

Maybe this happens because a transfer between own multi currency accounts are not count as deposit.

![k6oJA8Uy1R](https://user-images.githubusercontent.com/1261305/160273814-9d25102e-d7c9-438a-b7e1-53869eded6a7.png)
![chrome_lWRBBEmyxY](https://user-images.githubusercontent.com/1261305/160273872-c8e81bdd-d9bd-44a3-aabb-d6c7f61152ae.png)

### Expected behaviour

Balance card should be more readable with multiple currencies

### Debug information

Debug information generated at 2022-03-27 10:38:45 Europe/Zurich for Firefly III version **5.6.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.16 |
| Firefly III API | 1.5.5 |
| Build | 113, 02-03-2022 19:39:22 CET |
| PHP | 8.0.16 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | f5ec621d-3ef9-4779-8d7c-d8a219fe3354 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Zurich |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-03-01 00:00:00 |
| Session end | 2022-03-31 23:59:59 |
| Session first | 2022-03-24 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36 |

### Steps to reproduce

1. Create accounts in multiple currencies
2. Generate income for main account
3. Transfer Money from main account to second currency account
4. Make a withdrawal from second currency account
5. Look at the balance card

**Comment by JC5** [comment]
I know. The card will be removed in the new layout. Until then it will be hard to read. Sorry about that.
