### ISSUE TITLE
Create transaction, edit, back, and delete results in 404

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#5949]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Consecutive edit, back, and delete actions on a transaction result in a 404 Not Found page.

### Expected behaviour

The transaction list?

### Debug information

Both 5.7.0 at https://demo.firefly-iii.org/, and my own 5.6.16

### Steps to reproduce

1. Create/clone transaction
2. Click on the link in the "... created" success alert
3. Dropdown > Edit
4. Navigate back without updating
5. Dropdown > Delete

**Comment by JC5** [comment]
Nice find, will be fixed in 5.7.0 :+1:
