### ISSUE TITLE
Migrate to piggy bank without amount removes saved sum

### ISSUE THREAD

**Issue by ultrara1n** [firefly-iii/firefly-iii#5958]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm trying to use the new no target amount feature for piggy banks by migrating my piggy banks with target amount to ones without target amount.
By doing this, the already saved sum is set to 0.
This may be useful if you decrease your target but not if you remove the target completely.

### Expected behaviour

Just set the target to 0 and leave the saved sum as it is.

### Debug information

Debug information generated at 2022-04-03 14:25:02 Europe/Amsterdam for Firefly III version **5.7.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.0 |
| Firefly III API | 1.5.6 |
| Build | 149, 03-04-2022 12:22:59 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2022-03-10 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 |

### Steps to reproduce

1. Edit existing piggy bank
2. Set target amount to 0
4. Save

**Comment by JC5** [comment]
Nice find, should be fixed in the next release :+1:
