### ISSUE TITLE
Strange words in reports - italian lenguage

### ISSUE THREAD

**Issue by marco-ragusa** [firefly-iii/firefly-iii#5965]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

if you have set the language to Italian, you will find strange date formt under /reports ex (AMAMAMAM, PMPMPMPM ecc...)

![immagine](https://user-images.githubusercontent.com/7346348/161690802-167dc1b8-1ec0-40b6-bf8e-fb5cfd48edc4.png)

### Expected behaviour

dates written in the right way

### Debug information

Debug information generated at 2022-04-05 08:18:55 Europe/Rome for Firefly III version **5.7.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.1 |
| Firefly III API | 1.5.6 |
| Build | 153, 04-04-2022 05:56:25 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Rome |
| Browser TZ | Europe/Rome |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | it_IT |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2021-09-01 00:00:00 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0 |

### Steps to reproduce

1. go to https://demo.firefly-iii.org
2. change language to italian under /preferences
3. go to /reports

**Comment by JC5** [comment]
The strings are badly translated by the original translator. This was never noticed because they were not used. I will restore them for the next release. Thanks for letting me know!

**Comment by lucavallerini** [comment]
My bad, I misunderstood the instructions when they were translated. I corrected all translations on Crowdin regarding dates and times: on the weekend I will fire up a local instance and check that everything works correctly.
