### ISSUE TITLE
/admin/test-message throws error: TypeError when sending email Argument #5 ($port) must be of type ?int, string given

### ISSUE THREAD

**Issue by wouterdt** [firefly-iii/firefly-iii#5977]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The application shows an errorpage when trying to send a test email. I dont think it's a configuration issue as i've provided the option MAIL_PORT as environment variable

docker run -d -v firefly_iii_upload:/var/www/html/storage/upload -p 80:8080 -e APP_KEY=<removed>-e DB_HOST=192.168.1.16  -e DB_PORT=3307 -e DB_CONNECTION=mysql -e DB_DATABASE=firefly-iii -e DB_USERNAME=firefly-iii -e DB_PASSWORD=*removed* fireflyiii/core:latest -e MAIL_MAILER=smtp -e MAIL_HOST=smtp.scarlet.be -e MAIL_PORT=465 -e MAIL_FROM=*removed* -e MAIL_USERNAME=/admin/test-message      -e MAIL_PASSWORD=*removed* -e MAIL_ENCRYPTION=ssl  

Debug information generated at 2022-04-08 16:50:13 UTC for Firefly III version **5.7.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.1 |
| Firefly III API | 1.5.6 |
| Build | 153, 04-04-2022 05:56:25 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2021-01-04 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0 |

### Expected behaviour

Recieve an email or not a HTTP 500 error page

### Debug information

2022-04-08T16:56:07.570516+00:00] local.INFO: AUDIT: User sends test message. (192.168.2.112 (*removed*@gmail.com) -> POST:http://192.168.2.132/admin/test-message) [] []
[2022-04-08 16:56:07] local.ERROR: Exception is: {"class":"TypeError","errorMessage":"Symfony\\Component\\Mailer\\Transport\\Dsn::__construct(): Argument #5 ($port) must be of type ?int, string given, called in \/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Mail\/MailManager.php on line 174","time":"Fri, 08 Apr 2022 16:56:07 +0000","file":"\/var\/www\/html\/vendor\/symfony\/mailer\/Transport\/Dsn.php","line":28,"code":0,"version":"5.7.1","url":"http:\/\/192.168.2.132\/admin\/test-message","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko\/20100101 Firefox\/98.0","json":true,"method":"POST"}
[2022-04-08 16:56:07] local.ERROR: Symfony\Component\Mailer\Transport\Dsn::__construct(): Argument #5 ($port) must be of type ?int, string given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php on line 174 {"userId":1,"exception":"[object] (TypeError(code: 0): Symfony\\Component\\Mailer\\Transport\\Dsn::__construct(): Argument #5 ($port) must be of type ?int, string given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php on line 174 at /var/www/html/vendor/symfony/mailer/Transport/Dsn.php:28)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(174): Symfony\\Component\\Mailer\\Transport\\Dsn->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(160): Illuminate\\Mail\\MailManager->createSmtpTransport()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(119): Illuminate\\Mail\\MailManager->createSymfonyTransport()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(94): Illuminate\\Mail\\MailManager->resolve()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(72): Illuminate\\Mail\\MailManager->get()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(505): Illuminate\\Mail\\MailManager->mailer()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\\Mail\\MailManager->__call()
#7 /var/www/html/app/Handlers/Events/AdminEventHandler.php(70): Illuminate\\Support\\Facades\\Facade::__callStatic()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php

### Steps to reproduce

1. Start docker image with given parameters
2. Administration -> Send Test message

**Comment by JC5** [comment]
I can't replicate this. Even when I hardcode the port to a string, it doesn't fail. However, I invite you to try this on the `:develop` tag where I've pushed a possible catch.

**Comment by JC5** [comment]
Thanks for the details, I appreciate it!
