### ISSUE TITLE
Verified transactions.

### ISSUE THREAD

**Issue by therealeldaria** [firefly-iii/firefly-iii#5979]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I miss a function to confirm transations from bank statements.

So I add transactions usually as they happen or from recipts.
Then I go every other weeks or so to see at the bank account if any other transactions that did not have a recipt, like automatic withdrawals and others.

But it becomes tricky as it is easy to loose track of which transactions have been confirmed.
So far I tried to use the checkmark on the transactions list.

But if I then find a missing entry and try to add it all the checks are gone and I have to start over.

So it would be nice to have a way to mark a transaction as verified.

### Solution

An option to mark the transaction as verified.

### What are alternatives?

Manually keeping track of missing transactions and verified transactions.

**Comment by JC5** [comment]
You can reconcile accounts, is that what you need?

https://docs.firefly-iii.org/firefly-iii/advanced-concepts/reconcile/

**Comment by therealeldaria** [comment]
That was exactly what I was looking for.
Thank you.
