### ISSUE TITLE
Typed property must not be accessed before initialization

### ISSUE THREAD

**Issue by newalphamedia** [firefly-iii/firefly-iii#5981]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Installed FireFly III and Data-Importer on my Homestead installation on my local machine.

Using data importer tool via Firefly would fail with no error shown and if I hit back and then tried again, it would say importing but never finish. I turned on debugging and could see the error - so I tried using command line which results in the same errors regardless.

**Resulting Error:**
`Cannot assign string to property GrumpyDictator\FFIIIApiSupport\Model\Preference::$data of type array`

I could see that it was trying to pass a string value (on line: **$preference->data = $array['attributes']['data'];**) being currency e.g. "USD", but it expected an array.

So, I updated the file and replaced line 32 "**public array $data;**" with "**public $data;**"

This allows the importer to proceed - while it appears data is imported (I am unsure if all is) this results in the **next error**:

```
In PostTransactionResponse.php line 63:
  Typed property GrumpyDictator\FFIIIApiSupport\Response\PostTransactionResponse::$transactionGroup must not be accessed before initialization
```

### Expected behaviour

Not sure what to expect.

### Debug information

_php artisan importer:import json csv_

_... imports lines_

`[2022-04-10 14:47:57] local.DEBUG: Transaction #3 is unique.
[2022-04-10 14:47:57] local.DEBUG: Going to map data for this line.
[2022-04-10 14:47:57] local.DEBUG: No base url in getBaseUrl(), will return config variable.
[2022-04-10 14:47:57] local.DEBUG: No access token in hasAccessToken(), will return config variable.
[2022-04-10 14:47:57] local.DEBUG: Submitting to Firefly III: {"group_title":null,"error_if_duplicate_hash":true,"transactions":[{"type":"withdrawal","date":"","currency_id":13,"currency_code":null,"amount":"0","description":"(empty description)","source_id":1,"source_name":null,"destination_id":null,"destination_name":"(no name)","amount_debit":null,"amount_credit":null,"amount_negated":null,"original_source":"jc5-data-import-v0.9.5","tags":[],"source_iban":null,"source_number":null,"source_bic":null,"destination_iban":null,"destination_number":null,"destination_bic":null}]}
[2022-04-10 14:47:57] local.ERROR: Typed property GrumpyDictator\FFIIIApiSupport\Response\PostTransactionResponse::$transactionGroup must not be accessed before initialization {"exception":"[object] (Error(code: 0): Typed property GrumpyDictator\\FFIIIApiSupport\\Response\\PostTransactionResponse::$transactionGroup must not be accessed before initialization at /home/vagrant/www/firefly-iii-data-importer/vendor/firefly-iii/api-support-classes/src/Response/PostTransactionResponse.php:63)
[stacktrace]
#0 /home/vagrant/www/firefly-iii-data-importer/app/Services/Shared/Import/Routine/ApiSubmitter.php(273): GrumpyDictator\\FFIIIApiSupport\\Response\\PostTransactionResponse->getTransactionGroup()
#1 /home/vagrant/www/firefly-iii-data-importer/app/Services/Shared/Import/Routine/ApiSubmitter.php(88): App\\Services\\Shared\\Import\\Routine\\ApiSubmitter->processTransaction()
#2 /home/vagrant/www/firefly-iii-data-importer/app/Services/Shared/Import/Routine/RoutineManager.php(92): App\\Services\\Shared\\Import\\Routine\\ApiSubmitter->processTransactions()
#3 /home/vagrant/www/firefly-iii-data-importer/app/Console/AutoImports.php(374): App\\Services\\Shared\\Import\\Routine\\RoutineManager->start()
#4 /home/vagrant/www/firefly-iii-data-importer/app/Console/Commands/Import.php(130): App\\Console\\Commands\\Import->startImport()
#5 /home/vagrant/www/firefly-iii-data-importer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\Import->handle()
#6 /home/vagrant/www/firefly-iii-data-importer/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /home/vagrant/www/firefly-iii-data-importer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /home/vagrant/www/firefly-iii-data-importer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /home/vagrant/www/firefly-iii-data-importer/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#10 /home/vagrant/www/firefly-iii-data-importer/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#11 /home/vagrant/www/firefly-iii-data-importer/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#12 /home/vagrant/www/firefly-iii-data-importer/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#13 /home/vagrant/www/firefly-iii-data-importer/vendor/symfony/console/Application.php(1015): Illuminate\\Console\\Command->run()
#14 /home/vagrant/www/firefly-iii-data-importer/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#15 /home/vagrant/www/firefly-iii-data-importer/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#16 /home/vagrant/www/firefly-iii-data-importer/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#17 /home/vagrant/www/firefly-iii-data-importer/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#18 /home/vagrant/www/firefly-iii-data-importer/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 {main}
"}

In PostTransactionResponse.php line 63:

  Typed property GrumpyDictator\FFIIIApiSupport\Response\PostTransactionResponse::$transactionGroup must not be accessed before initialization
`

**Comment by newalphamedia** [comment]
Could it be for the first error mentioned, that if only 1 currency is set in Options under Firefly, the importer expects array but string is given? In my case, I only had 1 currency set at the time.

**Comment by JC5** [comment]
Which version?

**Comment by newalphamedia** [comment]
Data importer 0.9.5
Firefly 5.7.1

**Comment by JC5** [comment]
Thanks. I found the issue. If you could test this on the `develop` branch I would be very grateful. Are you using Docker?

**Comment by newalphamedia** [comment]
Nope, using [https://laravel.com/docs/9.x/homestead](url)

Did you make changes to firefly-iii/api-support-classes ? It's currently loading in the @dev on my copy. I could just update my local copy of that?

**Comment by newalphamedia** [comment]
Testing myself now. I have duplicate transaction errors now instead, so I'll see if I can figure out the setting to stop those and see if importer issues resolved.

**Comment by newalphamedia** [comment]
Ok I set IGNORE_DUPLICATE_ERRORS=true in the env and allowed duplicate setting on the importer (via web-based importer tool) and I get these errors instead.

Line #2: Could not create transaction. Unexpected empty response from Firefly III. Check the logs.

No data appears to be imported (I cannot see the transactions loaded in)

**Comment by newalphamedia** [comment]
I created a new record in the CSV to test with:

The import routine has finished 🎉. Done!
Warning(s)
Line #2: Line #2 may have had its currency changed (from ID #1 to ID #13). This happens because the associated asset account overrules the currency of the transaction.
Message(s)
Line #2: Created withdrawal [#6 "DUMMY RECORD"](http://firefly-iii.test/transactions/show/6) (AUD 150)

Note that I did change my currency for testing but this shouldn't impact anything here.

I can see the DUMMY RECORD transaction has been added. However, my previous transactions were not.

**Comment by JC5** [comment]
> Did you make changes to firefly-iii/api-support-classes ? It's currently loading in the @dev on my copy. I could just update my local copy of that?

I updated both, so be sure to update the data importer and the packages.

> Ok I set IGNORE_DUPLICATE_ERRORS=true in the env and allowed duplicate setting on the importer (via web-based importer tool) and I get these errors instead.

The `IGNORE_DUPLICATE_ERRORS=true` is not the setting that disabled the duplicate detection, so you can ignore that one. It does [something else instead](https://github.com/firefly-iii/data-importer/blob/main/.env.example#L73).

> ** another quick update. I deleted the DUMMY RECORD and I am unable to re-import the record. The site will say it's "done" but no transaction is imported.

Duplicate transactions aren't imported. This includes deleted records. If you wish to (re-)import duplicate transaction, make sure you configuration allows for it (set it in the UI or use a JSON file). You can also delete them from the Firefly III database.

**Comment by newalphamedia** [comment]
Ok thank you for clarifying that. I updated everything and allowed for duplicate import via the UI and this worked. I did have to run the UI importer twice (first time it said "done" but nothing was imported, and second time said messages "lines created" and the records were imported.).

**Comment by JC5** [comment]
Glad to hear it works, thanks for letting me know about the bug!
