### ISSUE TITLE
Wrong title in side boxes in transaction view 

### ISSUE THREAD

**Issue by Moc** [firefly-iii/firefly-iii#5983]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Just updated to 5.7.1, on the right hand side in 'Transactions' view (withdrawals and deposits) the boxes listing an overview of the past period (month, quarter, half a year?) now shows as "2" and "4". See screenshot for a better illustration of what I'm talking about (yellow marking). 

![image](https://user-images.githubusercontent.com/577978/162616258-e8e76e30-aa1f-429d-9657-02a01354cbf0.png)

### Expected behaviour

I think before it would either state the month(s) or quarter or something?

### Debug information

Debug information generated at 2022-04-10 14:20:45 Europe/Amsterdam for Firefly III version **5.7.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.1 |
| Firefly III API | 1.5.6 |
| Build | (unknown), (unknown) |
| DB version | 18 (exp. 18) |
| PHP | `8.1.1` |
| Host | `WINNT` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-07-01 00:00:00 |
| Session first | 2019-01-01 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl-NL |
| Attempt at "nl-NL.utf8" | 'nl-NL.utf8' |
| Attempt at "nl-NL.UTF-8" | 'nl-NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 |

**Comment by JC5** [comment]
Which language are you using?

**Comment by Moc** [comment]
> Which language are you using?

Dutch

**Comment by JC5** [comment]
Can you reproduce it on the demo site? Which URL is it visible on?

**Comment by Moc** [comment]
> Can you reproduce it on the demo site? Which URL is it visible on?

Hmm, it doesn't appear on the demo site. Didn't check that before, sorry. Need to figure out what's wrong on my local install then. 

It's a localhost environment, not online. Visible in `/transactions/withdrawal` (same for deposits and transfers).

**Comment by JC5** [comment]
I guess sharing the debug info *is* relevant :)

**Comment by Moc** [comment]
> I guess sharing the debug info _is_ relevant, could you do that please?

Ha you got me there :) I should have known better. Updated the original issue report with the debug info.

**Comment by JC5** [comment]
PHP8.1 on Windows is really outside my comfort-zone, sorry about that. I'm not sure which locale settings to call to make it work. It should be calling date formats with just "nl" but it doesn't seem to work on Windows as it does on Linux.

**Comment by Moc** [comment]
> PHP8.1 on Windows is really outside my comfort-zone, sorry about that. I'm not sure which locale settings to call to make it work. It should be calling date formats with just "nl" but it doesn't seem to work on Windows as it does on Linux.

Yeah I figured it had something to do with that weird combination ;) The only clue I can give thusfar is that the issue appeared after upgrading from 5.6.16 to 5.71.

**Comment by JC5** [comment]
I know what changed in the mean time, i replaced (ironically) a deprecated function that has to do with date parsing (`formatLocalized` is now `isoFormat`)

**Comment by Moc** [comment]
@JC5 I've been debugging this a bit, and I think the issue is that the locale is set to nl_NL.utf8 which does not work on Windows. It should be `nld_nld`. I haven't been able to figure out yet where to set this correctly. I would have expected the Carbon library to figure it out as well... 

I've tried changing it in `.env` (`DEFAULT_LOCALE=nld_nld`) but it does not get processed all the way. Apparently the end result still is `nl-NL.UTF-8`. Is this perhaps because of `getLocaleArray()`?

I know it's a very specific environment configuration on my part, and it's not your biggest concern but perhaps you can point me in the right direction. That would be much appreciated.

**Comment by Moc** [comment]
Actually, I'm not sure if that's the issue. A simple test code like below works properly. Back to debugging it is.... 

```
use Carbon\Carbon;

$now = Carbon::now()->locale('nl');
echo $now->monthName; // returns "juli"
```

**Comment by Moc** [comment]
Sorry, I hope you don't see this as spam. I think there's multiple issues:

1) Dutch locale on Windows is `nld_nld`. 
This would solve the following issue: 
FF Demo site: ![image](https://user-images.githubusercontent.com/577978/181908152-28900b77-8403-4ba0-a731-891e82d8c7eb.png)

My localhost: ![image](https://user-images.githubusercontent.com/577978/181908129-9cd227a4-fd25-4566-b6e1-8177d62589eb.png)

Notice how on my localhost it incorrectly says `ste`. I believe this is due to the wrong locale setting. 

2) In my original issue report, the boxes on the side use the value of `'half_year_js'` in `/resources/lang/nl_NL/config.php`, which is 
```
'half_year_js'             => 'Q YYYY',
```
This works correctly, as `Q` shows the right quarter number. 

Before it used to be 
```
 //'half_year'               => '%B %Y',
 ```
Which then translated to `juli 2022`. 

Also see: 
```
$now = Carbon::now()->locale('nl');
echo $now->isoFormat("Q YYYY"); // 3 2022
echo strftime("%B %Y", time()); // juli 2022
```

**Comment by JC5** [comment]
Check out the third tab in /preferences, is that the one you mean?

**Comment by JC5** [comment]
Feel free to open a new issue btw. That may be easier. I generally don't monitor old tickets.

**Comment by Moc** [comment]
@JC5 I created https://github.com/firefly-iii/firefly-iii/issues/6271 which I think is a bug. 

I'm still digging into the first issue I described: my install using ordinal date references (e.g. `1st` rather than `1`). Will open up a new issue if I think it's a bug.
