### ISSUE TITLE
Exception when running import from command line

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#599]
Hello,

I'm trying to run an import from the command line but every time the import throws the attached error.

[stacktrace_import_error_firefly_25-2.txt](https://github.com/firefly-iii/firefly-iii/files/801464/stacktrace_import_error_firefly_25-2.txt)

I'm using the latest release:  4.3.6

Best Regards

**Comment by JC5** [comment]
It means the import you're trying to start does not exist. I've improved the error message for the next release, but please tell me your process so I know what's happening.

**Comment by leander091** [comment]
Hmm strange.
I did configure the import the way it should be. The import job is also stored in the database. 
I'm trying to run the import with the following command: `sudo  -u http php artisan firefly:start-import wnLgXaxBKlYA` after I switched to the root of the application. 


![import](https://cloud.githubusercontent.com/assets/5831104/23339254/9bfc4664-fc1e-11e6-9510-48c567fd768f.PNG)
[import-configuration-2017-02-25_github.txt](https://github.com/firefly-iii/firefly-iii/files/801911/import-configuration-2017-02-25_github.txt)

**Comment by JC5** [comment]
Ok, that was question two: is the import routine in the database?

With the basics covered, I have to look into it and see what's happening. I hope I can give you an update today, otherwise it'll have to be in the beginning of next week.

**Comment by leander091** [comment]
Can you give an update about this problem?

**Comment by JC5** [comment]
Nothing yet, but I'm working on this other bug so let's see if I can't find anything!

**Comment by JC5** [comment]
Found and fixed! Until the next release is live, you can fix it yourself. Find this file, and this line in your own Firefly III installation:

https://github.com/firefly-iii/firefly-iii/blob/master/app/Console/Commands/Import.php#L61

Replace the line with this code:

```php
$job    = ImportJob::where('key', $jobKey)->first();
```
