### ISSUE TITLE
Add closing balance to transaction

### ISSUE THREAD

**Issue by HritwikSinghal** [firefly-iii/firefly-iii#5991]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

hi, can we have a closing balance value on every transaction (for asset accounts). So If i have 100$, and register a transaction for 10$, in that transaction summary page, it should also show that closing balance after this transaction was 90$. 

It is a super helpful feature to keep track of closing balances after every transaction

### Solution

add a closing balance feature to firefly III

### Additional context

it can be calculated based diff from last transaction. And if any old transaction is updated, it will update every new transaction after it for that asset account. Considering that most of us dont update TX after registering them, it should not be of much complexity. (an O(n) solution would suffice)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5751
