### ISSUE TITLE
"Firefly III is unable to format monetary amounts because your server is missing the required packages." on NGINX with existing locale in DEFAULT_LOCALE

### ISSUE THREAD

**Issue by meulie** [firefly-iii/firefly-iii#5992]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Fresh install, on NGINX, PHP 8.1

The error message suggests it's my server (and not Firefly III) that is missing a package, but I can't figure out how to proceed after reading https://docs.firefly-iii.org/firefly-iii/advanced-installation/locales/

locale -a gives me:
```
C
C.UTF-8
en_GB.utf8
en_US.utf8
nb_NO.utf8
nl_NL.utf8
POSIX

```
So nb_NO.utf8 is present...

### Expected behaviour

I'd expect that error not to be there ;)

### Debug information

Debug information generated at 2022-04-12 12:51:14 Europe/Oslo for Firefly III version **5.7.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.1 |
| Firefly III API | 1.5.6 |
| Build | (unknown), (unknown) |
| DB version | 18 (exp. 18) |
| PHP | `8.1.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Oslo |
| Browser TZ | Europe/Oslo |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_GB |
| Default locale | nb_NO.UTF8 |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2022-04-12 12:36:36 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | false |
| Attempt at "en_GB.UTF-8" | false |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 |

### Steps to reproduce

Fresh install

### Additional info

swordfish

**Comment by JC5** [comment]
Something seems to be broken in your installation. You report you have `en_GB.utf8` installed yet trying to apply `en_GB.utf8` yields FALSE (see your debug output).

**Comment by meulie** [comment]
> Your logs should contain the error:
> 
> ```
> Could not set locale. The following array doesnt work
> ```
> 
> I would like to know the whole line, please.

`[2022-04-19 07:59:22] local.ERROR: Could not set locale. The following array doesnt work:  ["no_NO.utf8","no_NO.UTF-8"] `

which makes sense, I think. There's
nb_NO.UTF-8 UTF-8   &
nn_NO.UTF-8 UTF-8

in locale.gen, but no no_NO.

**Comment by JC5** [comment]
Try selecting the correct locale from this list in your preferences. That may work:

<img width="821" alt="Screenshot 2022-04-19 at 17 11 35" src="https://user-images.githubusercontent.com/5889984/164036493-efa5a8d7-7d62-482f-ae10-073835be6929.png">
