### ISSUE TITLE
Display the current value of crypto accounts in the default currency

### ISSUE THREAD

**Issue by meulie** [firefly-iii/firefly-iii#5995]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I see in Firefly III how many coins I have, but not their current value in my default currency

### Solution

Obtain the exchange rate automagically from a reliable(?) site and display the current worth of the coins in default currency.

**Comment by JC5** [comment]
- https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/#automated-currency-conversion-so-everything-is-in-euros-or-dollars
- https://github.com/firefly-iii/firefly-iii/issues/5532
