### ISSUE TITLE
Decimal points not respected when using custom currency

### ISSUE THREAD

**Issue by kdelwat** [firefly-iii/firefly-iii#600]
Before setting up my initial accounts, I created a new currency (Australian Dollars) with the same settings as USD and set it as default. However, the process of adding initial funds and transactions seems to ignore the decimal point, leading to inputs like $165.20 being converted to $16520.

I have read the [FAQ](https://firefly-iii.github.io/faq-technical.html) and set my locale using `dpkg-reconfigure locales`, with locale set to `en_AU UTF-8`. I have also installed `language-pack-en-base`.

Are there any further steps I must take to resolve this problem?

**Comment by JC5** [comment]
Firefly tries to use en_US, which should be installed with language-pack-en-base. Run `locale -a` and see if en_US or  en_US.utf8 are listed.

You should make sure you restart Apache / nginx or the machine itself just to be sure.

**Comment by kdelwat** [comment]
Thanks for the help. `en_US.utf8` is definitely installed, and I have restarted the server, but the problem persists.

**Comment by JC5** [comment]
Cool. I'll write some test scripts tonight you can run to see what your PHP installation is doing. That should tell us what's going wrong.

**Comment by JC5** [comment]
Run this code, put it in locale.php in /public/ and browse to your Firefly III installation, /locale.php

```
<?php

$locales = [];

$locales['default'] = localeconv();

$system = setlocale (LC_ALL, null);
$locales[$system] = localeconv();


$set = ['en', 'English', 'en_US', 'en_US.utf8', 'en_US.UTF-8'];

foreach($set as $entry) {
	$result = setlocale (LC_ALL, $entry);
	$locales[$result] = localeconv();
}

setlocale(LC_ALL, $set);
$locales['full'] = localeconv();


echo '<pre>';
print_r($locales);
```

Could you post the result?

**Comment by kdelwat** [comment]
Thank you for your help so far! I received the following output:

```
Array
(
    [default] => Array
        (
            [decimal_point] => .
            [thousands_sep] => 
            [int_curr_symbol] => 
            [currency_symbol] => 
            [mon_decimal_point] => 
            [mon_thousands_sep] => 
            [positive_sign] => 
            [negative_sign] => 
            [int_frac_digits] => 127
            [frac_digits] => 127
            [p_cs_precedes] => 127
            [p_sep_by_space] => 127
            [n_cs_precedes] => 127
            [n_sep_by_space] => 127
            [p_sign_posn] => 127
            [n_sign_posn] => 127
            [grouping] => Array
                (
                )

            [mon_grouping] => Array
                (
                )

        )

    [C] => Array
        (
            [decimal_point] => .
            [thousands_sep] => 
            [int_curr_symbol] => 
            [currency_symbol] => 
            [mon_decimal_point] => 
            [mon_thousands_sep] => 
            [positive_sign] => 
            [negative_sign] => 
            [int_frac_digits] => 127
            [frac_digits] => 127
            [p_cs_precedes] => 127
            [p_sep_by_space] => 127
            [n_cs_precedes] => 127
            [n_sep_by_space] => 127
            [p_sign_posn] => 127
            [n_sign_posn] => 127
            [grouping] => Array
                (
                )

            [mon_grouping] => Array
                (
                )

        )

    [0] => Array
        (
            [decimal_point] => .
            [thousands_sep] => 
            [int_curr_symbol] => 
            [currency_symbol] => 
            [mon_decimal_point] => 
            [mon_thousands_sep] => 
            [positive_sign] => 
            [negative_sign] => 
            [int_frac_digits] => 127
            [frac_digits] => 127
            [p_cs_precedes] => 127
            [p_sep_by_space] => 127
            [n_cs_precedes] => 127
            [n_sep_by_space] => 127
            [p_sign_posn] => 127
            [n_sign_posn] => 127
            [grouping] => Array
                (
                )

            [mon_grouping] => Array
                (
                )

        )

    [full] => Array
        (
            [decimal_point] => .
            [thousands_sep] => 
            [int_curr_symbol] => 
            [currency_symbol] => 
            [mon_decimal_point] => 
            [mon_thousands_sep] => 
            [positive_sign] => 
            [negative_sign] => 
            [int_frac_digits] => 127
            [frac_digits] => 127
            [p_cs_precedes] => 127
            [p_sep_by_space] => 127
            [n_cs_precedes] => 127
            [n_sep_by_space] => 127
            [p_sign_posn] => 127
            [n_sign_posn] => 127
            [grouping] => Array
                (
                )

            [mon_grouping] => Array
                (
                )

        )

)
```

**Comment by JC5** [comment]
Alright, something is definitively wrong with your installation. The "default" array indicates the locale settings without changing anything. The C array is the system default (it's usually C, and it's equal to "default").

The 0 array is only created when the following code breaks:

```
$result = setlocale (LC_ALL, $entry);
```
Because [$result should be the same as $entry](http://php.net/manual/en/function.setlocale.php):

> Returns the new current locale, or FALSE if the locale functionality is not implemented on your platform, the specified locale does not exist or the category name is invalid.

In other words, your (web server) installation does not yet recognize any of the given locales:

> 'en', 'English', 'en_US', 'en_US.utf8', 'en_US.UTF-8'

In most cases, there is a 0-array because only Windows will recognize "English". But there should be a "en_US" array and in most cases an "en_US.UTF-8" array.

So in your case, I suspect:

> the locale functionality is not implemented on your platform, the specified locale does not exist

**Comment by kdelwat** [comment]
Thank you for your help. In my case, the problem turned out to be failing to restart php7.0-fpm on Ubuntu after changing locale. I'm sorry to bother you with an issue that was ultimately unrelated to the software!

**Comment by JC5** [comment]
Don't sweat it, we didn't know that when you opened the ticket, did we? Glad you got it working!
