### ISSUE TITLE
Reconciliation options won't show right result when buying foreign exchange

### ISSUE THREAD

**Issue by pitaohc** [firefly-iii/firefly-iii#6000]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I own two account, one Chinese Yuan, one US Dollar. A transaction about buying US Dollar by Chinese Yuan has been recorded. Like the following pic.
![buy](https://user-images.githubusercontent.com/36119151/163234050-67dc799a-7888-404d-a50a-0392bdaa0d02.png)
The problem is when I reconcile the US Dollar Account, the program calculate the reconciliation options with the value of Chinese Yuan not US Dollar.
 The following pictures show the change.
![291](https://user-images.githubusercontent.com/36119151/163234864-833d4e99-0be4-485f-a737-d75da252732d.png)
![380](https://user-images.githubusercontent.com/36119151/163234929-8b5bab67-8c6b-4b04-a8ed-4b0f7fa647a0.png)

### Expected behaviour

I think the reconciliation page should consider the condition about **buying foreign exchange**. In this case, the transaction includes two value. One is major **Amount**. The another is **Foreign Amount**. Could the code check the major amount is same  currency as the account reconciled. If not, it will calculate the reconciliation options by foreign amount. In my condition, it will be **291.46$ + 14$ = 305.46$**.

### Debug information

Debug information generated at 2022-04-14 01:03:16 Asia/Shanghai for Firefly III version **5.7.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.1 |
| Firefly III API | 1.5.6 |
| Build | 153, 04-04-2022 05:56:25 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Asia/Shanghai |
| Browser TZ | Asia/Shanghai |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | zh_CN |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | zh_CN |
| User locale | zh_CN |
| Attempt at "zh_CN.utf8" | 'zh_CN.utf8' |
| Attempt at "zh_CN.UTF-8" | 'zh_CN.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36 |

### Steps to reproduce

1. create tow different currency accounts.(Like Chinese Yuan and US Dollar)
2. create a transfer from an accounts to the other.
3. reconciling **the destination account**.

**Comment by JC5** [comment]
I see it. Nice find, that's a bug. Will be fixed in the next release.

**Comment by JC5** [comment]
I have everything, thank you. I will close the issue when the new release is out 👍
