### ISSUE TITLE
The has_no_attachments in transactions is not returning all the transactions

### ISSUE THREAD

**Issue by CosmoRing** [firefly-iii/firefly-iii#6009]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In the search functionality there is a `has_no_attachments:true` that search's for transactions with no attachments.
Transactions that had attachments (it had attachments but where deleted) are not showing up.

This happens on the website and on the API.

### Expected behaviour

Even if the transaction had attachments, currently there isn't any, so it should include those transactions.

### Debug information

Debug information generated at 2022-04-17 12:58:14 Europe/Lisbon for Firefly III version **5.7.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.2 |
| Firefly III API | 1.5.6 |
| Build | 159, 12-04-2022 20:46:45 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Lisbon |
| Browser TZ | Europe/Lisbon |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | pt_PT |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | remote_user_guard  |
| Headers | HTTP_REMOTE_USER,   |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2021-01-30 00:00:00 |
| User ID | 1 |
| User language | pt_PT |
| User locale | pt_PT |
| Attempt at "pt_PT.utf8" | 'pt_PT.utf8' |
| Attempt at "pt_PT.UTF-8" | 'pt_PT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36 |

### Steps to reproduce

1. Create a transaction.
2. Add an attachment to that transaction.
3. Delete the attachment from the transaction
4. Use search functionality and see that the transaction in the search result when has_no_attachments:true is added.

**Comment by JC5** [comment]
Nice find, I'll pick it up 👍
