### ISSUE TITLE
No data in expenses list

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#601]
The is no data on transactions/withdrawal list:
![obraz](https://cloud.githubusercontent.com/assets/4746858/23339021/64991e72-fc19-11e6-9c29-f1b700975c5b.png)
Shouldn't be there some data?

**Comment by JC5** [comment]
Yeah there should be, but I haven't got around to it yet. Especially for transfers, the amounts are fairly meaningless. So I left them empty for the time being.

In my personal case, the total amount of expenses and/or income are quite meaningless: I have a shared account as well so any totals in these boxes would also show the transactions coming from and going to shared accounts. 

Having said that, it shouldn't be difficult to calculate these amounts.

**Comment by JC5** [comment]
This is fixed, see #595
