### ISSUE TITLE
Select date range

### ISSUE THREAD

**Issue by alei643** [firefly-iii/firefly-iii#6010]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I've been importing a lot of historical bills lately.When I want to check my billing records for a certain period of time, I found date ranges cannot be entered by keyboard, If I need to query historical bills I had to manually click the mouse many times.
like this:
![1650242306(1)](https://user-images.githubusercontent.com/38073408/163739820-97e3c0d6-9a19-4fce-a4e3-2864abb1def3.jpg)

### Solution

Is it possible to change the red part of the picture to a text input box？
For example, when I look up the bill for April 2020, I can enter it directly without having to click the mouse all the time

**Comment by JC5** [comment]
I never meant for the frontpage to be used like that. If you want to check out your history, browse to the /transactions/* pages or /reports to go back to the past more easily.
