### ISSUE TITLE
Error 500 with Allowed memory size exhausted

### ISSUE THREAD

**Issue by lorenzschmid** [firefly-iii/firefly-iii#6023]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have a Firefly instance installed via Docker which is working fine for a couple of months already. Since updating to the newest version 5.7.2 after which I also added quite a few new transactions I receive frequently an error 500 when trying to access Firefly. When looking into the logs I see:

```
[php:error] [pid 416] [client redacted_ip:51848] PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 182464112 bytes) in /var/www/html/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php on line 113
```

This does not happen on all pages, e.g. I can always access the `/admin` interface but the main page `/` or when adding new transaction the instance returns the error. When I destroy the Docker container and mount it again, I am error-free for around a day (even on the previously broken pages) before the error returns.

Since the error appears "randomly" I am not sure where it comes from. I am definitely not trying to mass-import transaction as in #1852 which also reported a "Allowed memory size exhausted".

### Expected behaviour

Being able to access Firelfy normaly and without an error 500.

### Debug information

Debug information generated at 2022-04-23 09:01:52 Europe/Zurich for Firefly III version **5.7.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.2 |
| Firefly III API | 1.5.6 |
| Build | 159, 12-04-2022 20:46:45 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Zurich |
| Browser TZ | Europe/Zurich |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | remote_user_guard  |
| Headers | HTTP_REMOTE_USER, HTTP_REMOTE_EMAIL  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-06-30 00:00:00 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15 |

```
Truncated from this point <----|[2022-04-23 02:00:11] production.INFO: It has been 1d after since the recurring transactions cron-job has fired. It will fire now!  
[2022-04-23 02:00:11] production.INFO: Will now fire recurring cron job task for date "2022-04-23 02:00:10".  
[2022-04-23 02:00:12] production.INFO: Marked the last time this job has run as "2022-04-23 02:00:10" (1650672010)  
[2022-04-23 02:00:12] production.INFO: Done with recurring cron job task.  
[2022-04-23 02:00:12] production.INFO: It has been 1d after since the auto budget cron-job has fired. It will fire now!  
[2022-04-23 02:00:12] production.INFO: Will now fire auto budget cron job task for date "2022-04-23".  
[2022-04-23 02:00:12] production.INFO: Done with auto budget cron job task.  
[2022-04-23 02:00:12] production.INFO: It has been 1d after since the bill warning cron-job has fired. It will fire now!  
[2022-04-23 02:00:12] production.INFO: Will now fire bill warning job task for date "2022-04-23 02:00:10".  
[2022-04-23 02:00:12] production.INFO: Marked the last time this job has run as "2022-04-23 02:00:10" (1650672010)  
[2022-04-23 02:00:12] production.INFO: Done with bill warning cron job task.  

```

**Comment by JC5** [comment]
Try setting debug mode to see what the error stack trace is. As far as I can see it ends in a script that's not mine (a library) but the fact that it tries to allocate more than half a gigabyte of ram is very weird.

https://docs.firefly-iii.org/firefly-iii/faq/other/#how-do-i-enable-debug-mode

**Comment by JC5** [comment]
Weird, I've never seen it before. But the Docker container doesn't store the logs inside the container by default.

**Comment by JC5** [comment]
Oh wow. Sorry, this is a first for me as well. The permissions look good. Generally speaking, 664 for www-data, which is exactly what you have. 

What folders have you mapped inside the Docker container?

**Comment by JC5** [comment]
Ah, that may be a clue. If you run the cron job as root, it may change those rights. Although the loop you describe is a first for me, it could explain things:

https://docs.firefly-iii.org/firefly-iii/advanced-installation/cron/#cron-jobs-in-docker

**Comment by JC5** [comment]
These kinds of loops are notoriously difficult to debug. I would love to, but unless more people run into this problem I'm going to skip out of it. Thanks for bearing with me, I appreciate the compliments!
