### ISSUE TITLE
Can't save reconcile - Request Header too large

### ISSUE THREAD

**Issue by DunklerPhoenix** [firefly-iii/firefly-iii#6030]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

It's not possible to save a reconcile with too many open positions in docker container.

### Expected behaviour

Saving should be possible 

### Debug information

Debug information generated at 2022-04-27 09:13:05 Europe/Zurich for Firefly III version **5.7.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.2 |
| Firefly III API | 1.5.6 |
| Build | 159, 12-04-2022 20:46:45 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Zurich |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2022-03-24 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 |

### Steps to reproduce

1. Use Docker container
2. make a reconcile where many transactions are unchecked
3. Saving button does not work
4. Console says 431 

### Additional info

The url that get called while pressing the save button is:

`https://domain.com/accounts/reconcile/1/overview/2022-04-01/2022-04-30?startBalance=24.56&endBalance=364.3&startDate=2022-04-01&startEnd=2022-04-30&journals%5B%5D=58&journals%5B%5D=183&journals%5B%5D=182&journals%5B%5D=181&journals%5B%5D=171&journals%5B%5D=170&journals%5B%5D=169&journals%5B%5D=167&journals%5B%5D=166&journals%5B%5D=164&journals%5B%5D=163&journals%5B%5D=162&journals%5B%5D=158&journals%5B%5D=59&journals%5B%5D=161&journals%5B%5D=144&journals%5B%5D=143&journals%5B%5D=142&journals%5B%5D=141&journals%5B%5D=140&journals%5B%5D=139&journals%5B%5D=138&journals%5B%5D=137&journals%5B%5D=136&journals%5B%5D=135&journals%5B%5D=134&journals%5B%5D=133&journals%5B%5D=132&journals%5B%5D=131&journals%5B%5D=130&journals%5B%5D=129&journals%5B%5D=128&journals%5B%5D=127&journals%5B%5D=101&journals%5B%5D=100&journals%5B%5D=99&journals%5B%5D=98&journals%5B%5D=97&journals%5B%5D=96&journals%5B%5D=95&journals%5B%5D=94&journals%5B%5D=93&journals%5B%5D=92&journals%5B%5D=91&journals%5B%5D=87&journals%5B%5D=90&journals%5B%5D=89&journals%5B%5D=85&journals%5B%5D=73&journals%5B%5D=71&cleared%5B%5D=180&cleared%5B%5D=179&cleared%5B%5D=176&cleared%5B%5D=175&cleared%5B%5D=160&cleared%5B%5D=157&cleared%5B%5D=125&cleared%5B%5D=123&cleared%5B%5D=122&cleared%5B%5D=70`

It shows only "request header too large"

**Comment by JC5** [comment]
Are you running a reverse proxy in front of Apache?

**Comment by DunklerPhoenix** [comment]
Didn't thought about this. Yes I'm running traefik as proxy.
But I had never a problem with request headers in traefik even if they are big. Running about 40 different services over it.

I'm not even sure if traefik has a limit there

**Comment by JC5** [comment]
Haha this will indeed be a POST in future versions. I'm working on a new layout where this is the case.

**Comment by DunklerPhoenix** [comment]
Ah tiptop.
Then sorry for this issue here. I'll close it :)

Have a great day
