### ISSUE TITLE
Rule trigger using Notes does not work

### ISSUE THREAD

**Issue by ykktrcb7** [firefly-iii/firefly-iii#6035]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

when creating a rule based on fields. The trigger based on note filter does not work or react when I start typing.
![image](https://user-images.githubusercontent.com/81748597/165903520-81b2481f-52fb-48ce-ad89-5f4cb37a2d21.png)

### Expected behaviour

Filter by notes.

### Debug information

no debug page

### Steps to reproduce

1. create rule
2. set trigger based on notes

**Comment by JC5** [comment]
There is no auto-complete for notes.

**Comment by ykktrcb7** [comment]
Understood, then we can consider it solved. Was a misunderstanding of behavior from my side.

**Comment by JC5** [comment]
:+1:
