### ISSUE TITLE
Transfer to account and assign piggy bank without goal is emptying the piggy bank

### ISSUE THREAD

**Issue by ultrara1n** [firefly-iii/firefly-iii#6040]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello there!
After migrating almost all of my piggy banks to ones without a goal amount, the new month is coming and i'm starting my monthly process.
I've done a simple transfer from Account A to Account B with an amount of 5 Euros and using Piggy Bank A (No goal amount, currently at 290 Euros).
After doing this transfer, the whole piggy bank is emptied.
I've made two screenshots, one of the piggy bank and one of the related transfer:
https://abload.de/img/screenshot2022-04-30299kj7.jpg
https://abload.de/img/screenshot2022-04-302qqjjc.jpg

### Expected behaviour

Well, the piggie banks should not be emptied but the transfered amount should be added to the existing one.

### Debug information

Debug information generated at 2022-04-30 22:13:21 Europe/Amsterdam for Firefly III version **5.7.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.2 |
| Firefly III API | 1.5.6 |
| Build | 159, 12-04-2022 20:46:45 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2022-03-10 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 |

**Comment by JC5** [comment]
That's probably a bug, thanks for letting me know!
