### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by Dagur** [firefly-iii/firefly-iii#6041]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I prefer not to set up a database server. Would it be possible to add support for sqlite instead?

### Solution

Easier setup

### What are alternatives?

MySQL and PostgresQL

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/faq/self_hosted/#i-want-to-use-sqlite
