### ISSUE TITLE
[Error 500] Internal Firefly III Exception when importing a transaction that has a rule to delete the transaction when created

### ISSUE THREAD

**Issue by rkkoszewski** [firefly-iii/firefly-iii#6047]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm using the Firefly III API to import transactions into my Firefly instance. I have there 2 bank accounts from which I often perform transfers between them. To easier track those transactions between my accounts, I set up a couple of rules that convert the deposit transaction in account A to a "Transfer" that links from account B to A, and for account B I have a rule that just deletes the entry, to avoid duplicates. This seems to work fine but seems to trigger an internal error in Firefly during the import when triggers are enabled during import (Which is desired).

### Expected behaviour

The import should not fail. The transaction should be imported and deleted after being created (Having a result that the entry will be detected as duplicate). 

### Debug information

%

### Steps to reproduce

1. Create a rule that deletes a transaction with a specific title.
2. Import a transaction using the Firefly III API which uses the specific title from the rule.
3. Enjoy your Internal Firefly III Exception.

**Comment by JC5** [comment]
Are you using the firefly iii data importer?

**Comment by JC5** [comment]
A fix will be out for the data importer that (also) suffers from this issue.

**Comment by rkkoszewski** [comment]
> Are you using the firefly iii data importer?

I'm not using the Firefly III data importer (It's a custom implementation). The issue is on Firefly's side. From what I read from your commit I should look for error code 200032 when I get the exception and just ignore it? Or are there any drawbacks from this?

Just out of curiosity, why is this even considered an exception? The transaction is modified as part of the automation, so this is a expected situation.

**Comment by JC5** [comment]
> From what I read from your commit I should look for error code 200032 when I get the exception and just ignore it? Or are there any drawbacks from this?

Yes, and no. The error code will be part of Firefly III v5.7.4.

> Just out of curiosity, why is this even considered an exception? The transaction is modified as part of the automation, so this is a expected situation.

It's "expected". The code that handles the rules is out of band with the code that collects transactions. When you submit a transaction, one part of Firefly III will return the ID of said transaction. In the meantime it gets deleted by a rule. To separate these concerns the code that collects transactions doesn't know about rules deleting transactions; all it knows it's supposed to serve a transaction that no longer exists. If that happens, it can guess the transaction was deleted (hence the error) but if the transaction gets deleted for some other reason you'll see the same error.

So if you POST a transaction and it gets deleted before it can even be served to you, you may get a 200032.

**Comment by rkkoszewski** [comment]
Alright, makes sense. Thank you for taking the time for looking into the issue and taking your time to explain what is going on. Closing the issue as solved. Best regards!
