### ISSUE TITLE
CSV importer duplicate detection ignores deleted flag

### ISSUE THREAD

**Issue by vabene1111** [firefly-iii/firefly-iii#6048]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If you delete a transaction previously imported and run the same import again it detects the deleted transaction as a duplicate. Probably same issue as #5956

### Expected behaviour

if a transaction is deleted the importer should not consider it a duplicate

### Debug information

message from the CSV importer 
`Line #0: transactions.0.description: Duplicate of transaction #1147. (original value: "transaction text")`

database

`transaction_journals`
| id | created\_at | updated\_at | deleted\_at | user\_id | transaction\_type\_id | bill\_id | transaction\_currency\_id | description | date | interest\_date | book\_date | process\_date | order | tag\_count | encrypted | completed | transaction\_group\_id | user\_group\_id |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1150 | 2022-05-02 20:50:54 | 2022-05-02 20:51:39 | 2022-05-02 20:51:39 | 1 | 1 | NULL | 1 | transaction text | 2022-04-04 00:00:00 | NULL | NULL | NULL | 0 | 0 | true | true | 1147 | NULL |

`transaction_groups`
| id | created\_at | updated\_at | deleted\_at | user\_id | title | user\_group\_id |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1147 | 2022-05-02 20:50:54 | 2022-05-02 20:51:39 | 2022-05-02 20:51:39 | 1 | NULL | NULL |

`transactions`
| id | created\_at | updated\_at | deleted\_at | account\_id | transaction\_journal\_id | description | amount | identifier | transaction\_currency\_id | foreign\_amount | foreign\_currency\_id | reconciled |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2278 | 2022-05-02 20:50:54 | 2022-05-02 20:51:39 | 2022-05-02 20:51:39 | 28 | 1150 | NULL | -4.000000000000 | 0 | 1 | NULL | NULL | false |
| 2279 | 2022-05-02 20:50:54 | 2022-05-02 20:51:39 | 2022-05-02 20:51:39 | 32 | 1150 | NULL | 4.000000000000 | 0 | 1 | NULL | NULL | false |

### Steps to reproduce

1. import a CSV file
2. delete those transactions
3. import again with duplicate detection on

### Additional info

i think #5956 might have had the same issue

also thank you very much, still love firefly :)

**Comment by JC5** [comment]
This is by design, always has been.

https://docs.firefly-iii.org/data-importer/help/faq/#why-cant-i-import-duplicate-transactions

**Comment by vabene1111** [comment]
i am sorry, i tought i read it correctly, sorry for bothering you
