### ISSUE TITLE
Adding Japanese(ja_JP.UTF-8 UTF-8) to locale.gen

### ISSUE THREAD

**Issue by seiji1978** [firefly-iii/firefly-iii#6050]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I'm using Firefly III by docker container image. And I set language configuration to japanese. 
( Japanese is enabled at #4959. Thank you!)

Every time I create a new Firefly III container, Firefly III norify me below:

> Invalid server configuration
> Firefly III is unable to format monetary amounts because your server is missing the required packages...

So I have to run below commands in the container every time.

```
echo "ja_JP.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
service apache2 reload
```

### Solution

I would like to add japanese locale setting "ja_JP.UTF-8 UTF-8" to locale.gen on BaseImage.
I think /conf/locale.gen on BaseImage sholud be edited.

**Comment by JC5** [comment]
Yes, I'll make sure it gets included. It should have been already.
