### ISSUE TITLE
Invoice field empty when create recurring transaction from transaction 

### ISSUE THREAD

**Issue by DunklerPhoenix** [firefly-iii/firefly-iii#6059]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If you create an recurring transaction from an transaction then the invoice field is empty and does not load any invoices

### Expected behaviour

Invoices should be loaded there

### Debug information

Debug information generated at 2022-05-06 10:25:10 Europe/Zurich for Firefly III version **5.7.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.5 |
| Firefly III API | 1.5.6 |
| Build | 180, 05-05-2022 06:05:01 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.5` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Zurich |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-06 00:00:00 |
| Session end | 2022-05-06 00:00:00 |
| Session first | 2022-03-24 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 |

### Steps to reproduce

1. create transaction
2. open transaction
3. Select "create recurring transaction from transaction" (idk how it's called in english)
4. invoice field does not load any invoices and says "no invoices created yes" (idk how it's called in english)

**Comment by DunklerPhoenix** [comment]
Sorry I worked a bit too much the last days.

Here are screenshots in english
![chrome_MX7E76QnHg](https://user-images.githubusercontent.com/1261305/167404958-06000f80-4d83-4759-ba3a-2f06a80f229e.png)

If you click on "Create recurring transaction based on transaction"
Then the BILL field (sorry again for that :P) is empty even if bills exist.

![chrome_HJKlUboGHE](https://user-images.githubusercontent.com/1261305/167405129-af7fff69-e9e5-4d49-a352-93fc5d1da7c9.png)

**Comment by JC5** [comment]
Thanks, I'll check it out. And my days have been equally busy, I could have guessed the field easily enough 😁
