### ISSUE TITLE
Dashboard Graph showing incorrect data

### ISSUE THREAD

**Issue by Shagon94** [firefly-iii/firefly-iii#6063]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When using multiple currencies the graph shows incorrect data. To show what I mean here's an example, say I have 2 accounts:

- One for EUR
- One for another currency that's a larger ratio of conversion  (e.g. 1 Euro equals 137.72 Japanese YEN, so a 1:137 in this case)

Account 1 has 1000 EUR.
Account 2 has 100,000 YEN.

100,000 YEN is around 725 euros.

## Current outcome

Graph showing that yen is at 100,000 EUR instead of ~725 EUR:

![Untitled](https://user-images.githubusercontent.com/9140783/167248494-49398a56-2919-49e6-82bf-2b4177e822cb.png)

### Expected behaviour

Graph has a point showing yen point at around ~725 EUR.

### Debug information

This is replicated on https://demo.firefly-iii.org/

### Steps to reproduce

1. Create EUR account with 1000 EUR
2. Create YEN account with 100,000 YEN
3. Go to dashboard page
4. See incorrect graph

**Comment by JC5** [comment]
The left bar will always display the primary currency. When you hover over the data point, the amount will display correctly. Sorry, this can't be helped.

**Comment by Shagon94** [comment]
Couldn't the value on the graph be multiplied by a number representing the exchange rate to give an approximate value?

The graph showing the primary currency is fine, the datapoint itself showing 100,000 EUR isn't.

My understanding is that the actual datapoint on the graph when hovered over can say 100,000 YEN but the datapoint should not be on 100,000 EUR.

**Comment by Opisek** [comment]
Isn't this related to [this thread](url) about letting the user set an exchange rate for their currencies? That suggestion was accepted and placed on the roadmap already. From my understanding, letting the user set exchange rates would automatically fix the problem with this graph. It's what I am currently waiting after reading the linked thread, as the data becomes instantly skewed, as soon as one uses more than just a single currency and effectively renders the graph useless as a means to visually assess one's finances. In this regard, is this problem really a "wontfix" or would the (re)introduction of exchange rates be a suitable fix, whenever that update may come?
