### ISSUE TITLE
First transaction of a category doesn't work if it's split.

### ISSUE THREAD

**Issue by dzaikos** [firefly-iii/firefly-iii#607]
If the very first use of a category is within a split transaction, attempts to view all transactions in that category fail with this error:

`Type error: Return value of FireflyIII\Repositories\Category\CategoryRepository::firstUseDate() must be an instance of Carbon\Carbon, string returned`

**Comment by JC5** [comment]
Yes, this was discovered by somebody else as well, in a slightly different context. The next release will have a fix.
