### ISSUE TITLE
Feature Request - Piggy Bank - link to transaction

### ISSUE THREAD

**Issue by bartekd123** [firefly-iii/firefly-iii#6073]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I use piggy banks, where money gets added on each paycheck and those are saved to pay for non-standard bills (ones that happen quarterly, yearly, etc). Money gets added until it is removed, then keeps being added to.

This feature request would be having transactions link directly to a piggy bank addition/removal. This would have 2 benefits
 - When you go into a piggy bank to see the details of it, where it normally shows transactions, it should show the description, or a link back to the transaction that adds/removes funds
 - You don't need to manually add/remove funds from a piggy bank as a separate step

### Solution

2 things
 - In the transaction, you can check a box to add/remove this transaction from a piggy bank (where it links to the piggy bank)
 - Within the piggy bank, under the section "transactions" have it link back to that transaction

### What are alternatives?

If the above is not possible, maybe another thing that would be helpful that would achieve almost the same thing, is allowing a note when adding/removing funds from the piggy bank. That way when you make a note, it shows up under the piggy bank "transactions"

### Additional context

The closest feature request to this one that I saw was https://github.com/firefly-iii/firefly-iii/issues/5525 not sure if it can be worked on in tandem (if my request is considered a good or possible feature).

**Comment by JC5** [comment]
This already exists. You can link transfers (and transfers only) to a piggy bank when you create a new transaction. As soon as the form says "you're creating a transfer" the piggy bank option will appear.

**Comment by bartekd123** [comment]
Oh I didn't know that. Is there any way of linking it after the fact? I import my transactions from my bank which creates the transfer automatically. Maybe have a checkbox that says "add/remove from piggy bank" and when you check it, it asks which piggy. When you save the transaction, adds/removes the amount (and shows it in the piggy bank so can see in the future). 

Typing that up, might be too much work for you, and I know you are busy. Maybe something to consider after you are done with the v3 layout?

**Comment by JC5** [comment]
You could create a rule that does it for you, I believe it will create the link too.

**Comment by bartekd123** [comment]
Problem is there are multiple piggy’s for the same main account. Rule wouldn’t know which one to link it to, so for me, it would have to be a manual process after it is already a transfer.

**Comment by JC5** [comment]
Mmm sorry :/

**Comment by bartekd123** [comment]
No problem. Thanks James.
