### ISSUE TITLE
Adding custom columns at transaction table

### ISSUE THREAD

**Issue by Aerics84** [firefly-iii/firefly-iii#6074]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be nice to add more columns to the transaction table.
Like im really missing the "notes" after the description, because often if i pay by credit card the usage case i can see only in the notes field.

### Solution

Adding settings to add database columns to the transactions overview table.

### What are alternatives?

Hardcode the note databse field to the transaction overview after the description.

**Comment by JC5** [comment]
Thanks for the suggestion! It's not going to happen in this release, but it's on my list to be customized in the new layout.

https://github.com/firefly-iii/firefly-iii/issues/5751

**Comment by jonathanathe** [comment]
Forgive me for speaking here after opening this ticket so long ago, but I have the doubt if the field that the colleague asks for, for example, could be set to "Notes" as it would make it easier for me to identify the purchase made.

And also to ask if there is still a long way to go before this option is available.

![image](https://github.com/firefly-iii/firefly-iii/assets/34164094/e745fcca-81fd-4776-b646-a41170999b44)

Thank you very much!

**Comment by PuckStar** [comment]
I would really like this.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6304
