### ISSUE TITLE
Add support for merging transactions into a split transaction

### ISSUE THREAD

**Issue by GGG-KILLER** [firefly-iii/firefly-iii#6075]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Adding a feature where in the transaction list screen, when multiple transactions are selected, they can be merged into a single split transaction would be pretty nice.

### Solution

This would allow me to (when importing the CSV from my credit card company) to merge the individual transactions from paying something in installments or when paying taxes over an international purchase into a single split transaction (which is my current workflow).

### What are alternatives?

Currently the only alternative is to turn one of the transactions into a split transaction and then copy over the information from other transactions (including the internal reference) and then deleting the original transaction that I'm merging into the other.

**Comment by JC5** [comment]
Good idea!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6304
