### ISSUE TITLE
Ability to filter categories in search

### ISSUE THREAD

**Issue by niklas152** [firefly-iii/firefly-iii#6086]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

At the moment, the search only allows to positively filter by categories (i.e., category_{is,contains,starts,ends}.  
I would like to be able to negatively filter for categories as well, such as category_is_not, similiar as it already works for tags.

### Solution

Add filter like 'category_is_not' which works similiar / the same as the already existing 'tag_is_not'.

### What are alternatives?

Manually list all categories you expect to be in your search with 'category_is' except the ones you do not want - so not really feasible once you have many categories.

**Comment by JC5** [comment]
There will not be extra filters at this time, but I'll keep this ticket and see if I can make an inverse button. Somebody suggested it before, and at the time I didn't want to do it. But either all filters have a "does not do X", or none have it. The current inconsistency isn't useful.

**Comment by niklas152** [comment]
Alright, an inverse button sounds like a good solution. Thank you!

**Comment by JC5** [comment]
Will be in 5.8.0
