### ISSUE TITLE
Rules are broken

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#610]
I'm trying to setup a simple rule on latest Firefly 4.3.6:
If destination account is A or B or C set category to X. Unfortunately it doesn't work. Here is example rule:
![obraz](https://cloud.githubusercontent.com/assets/4746858/23578342/cbfd0870-00d4-11e7-93d6-0c9acf6ff41e.png)
Unfortunately it doesn't work. Where I'm doing a mistake?
Also I'm getting following error while testing rules:
```
Firefly III ran into an error: Undefined offset: 1
The error was of type "ErrorException".
The error occured on/at: Sat, 04 Mar 2017 11:17:06 +0000.
This error occured in file /var/www/firefly/app/Http/Controllers/RuleController.php on line 536 with code 0. 
```

**Comment by JC5** [comment]
The rules do not fire on "or", so setting multiple triggers on the same value will not work. All the triggers must match.

I was able however, to find and fix the ErrorException you received! I was planning on releasing 4.3.7 this weekend.

**Comment by skibbipl** [comment]
So what's for is "stop processing other triggers" flag?

**Comment by JC5** [comment]
Pointless, really, I'll admit. :P
