### ISSUE TITLE
List future transactions in /account/show view

### ISSUE THREAD

**Issue by hairlesshobo** [firefly-iii/firefly-iii#6100]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I want to start off by saying thank you for this app. Very nice interface, clean and to the point, runs great, clearly written by someone who can appreciate a professional project. Thanks!

I would love for the view at `/accounts/show/xx/` to have a simple table list of future transactions. I am *not* looking for these transactions to be included in any way in the balance, net worth calculation, etc. I simply would like a separate table that lists individual transactions in or out of an account for the selected time period. For example, if it is the 20th of May, I would like the list to just show anything that is setup as a `recurring transaction` to or from the account in question to be listed with the amount the transaction is for.. something like the following would be outstanding.

| Description          | Amount | Date                   | Source account | Destination account             | Category |
|------------------|---------|----------------|-----------------|----------------------------|----------|
| Phone Bill             | -314.16 | May 28th 2022 |  Checking           | Expensive Phone Company | Bills |
| Vacation Savings | -75.00 | May 31th 2022 |  Checking           | Savings | Dream Planning |

### Solution

I realize that, according to [what it's not](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/), this app is not and will not ever be a future-planning sort of tool. I realize and can appreciate the complexities that would go into accurately predicting future balances and that is not what I am requesting. I feel this would help give additional visibility into scheduled, upcoming transactions without being responsible in any way for future balance prediction. I see this as being closely related to the "bills" view, but on an account-specific level. I have quite a lot of scheduled transactions that are not "bills" but instead transfers to other accounts, and therefore the bills view does not work for those.

### What are alternatives?

The best I can currently do is to go to the recurring transaction view and carefully look through it for upcoming transactions. The recurring transactions view does not appear to be sortable or filterable so it just displays in whatever order it is returned by the API.

### Additional context

Thank you in advance for your time and consideration on this request!

**Comment by JC5** [comment]
No I don't think so, I don't want to clutter the view.
