### ISSUE TITLE
Can't reconcile when reaching a certain number of line

### ISSUE THREAD

**Issue by gTamatea** [firefly-iii/firefly-iii#6105]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello,
When I try to reconcile an account, When I select a certain number of lines, I get an error status 500 (the reconcile page doesn't pop up). When I remove a few line, I get a status 200 with the pop up. I don't really understand why there is a problem. I can reconcile but I have to use a low number of line.

### Expected behaviour

Before an update (I can't remember from witch version), I could reconcile as many line as I had to. I mean the popup showed correctly.

### Debug information

The bug doesn't create any line in the debug file. But I can see this error un the debug of edge : 

WORKING
`
**Général**
URL de la demande: https://firefly.xxx.xxx/accounts/reconcile/4/overview/2021-11-26/2021-12-20?startBalance=1682.3&endBalance=566.22&startDate=2021-11-26&startEnd=2021-12-20&journals%5B%5D=2330&journals%5B%5D=2352&journals%5B%5D=2334&journals%5B%5D=2327&journals%5B%5D=2318&journals%5B%5D=2351&journals%5B%5D=2320&journals%5B%5D=2319&journals%5B%5D=2350&journals%5B%5D=2349&journals%5B%5D=2340&journals%5B%5D=2326&cleared%5B%5D=2342&cleared%5B%5D=2341&cleared%5B%5D=2178&cleared%5B%5D=2186
Méthode de demande: GET
Code d’état: 200  (de service worker)
Stratégie de point d’accès: no-referrer

**En-têtes de réponse**
cache-control: no-cache, private
content-length: 6159
content-security-policy: default-src 'none'; object-src 'none'; script-src 'unsafe-eval' 'strict-dynamic' 'self' 'unsafe-inline' 'nonce-Y59LvDbZZZdBXy0+XsHlUg=='   ; style-src 'unsafe-inline' 'self'; base-uri 'self'; font-src 'self' data:; connect-src 'self' ; img-src data: 'strict-dynamic' 'self' *.tile.openstreetmap.org ; manifest-src 'self'; form-action 'self'
content-type: application/json
date: Thu, 26 May 2022 20:26:15 GMT
feature-policy: geolocation 'none'; midi 'none'; sync-xhr 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none'
referrer-policy: no-referrer
server: openresty
strict-transport-security: max-age=63072000;includeSubDomains; preload
x-content-type-options: nosniff
x-frame-options: deny
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block

**En-têtes de demande**
En-têtes provisoires sont affichées.
En savoir plus
Accept: application/json, text/javascript, */*; q=0.01
Referer
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Microsoft Edge";v="101"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
X-CSRF-Token: FyjYViOy2kuwUkCSj9Ch0iNvyKDuLW0WHzNe70TX
X-Requested-With: XMLHttpRequest
`

BUG
`
**Général**
URL de la demande: https://firefly.xxx.xx/accounts/reconcile/4/overview/2021-11-26/2021-12-20?startBalance=1682.3&endBalance=566.22&startDate=2021-11-26&startEnd=2021-12-20&journals%5B%5D=2330&journals%5B%5D=2352&journals%5B%5D=2334&journals%5B%5D=2327&journals%5B%5D=2318&journals%5B%5D=2351&journals%5B%5D=2320&journals%5B%5D=2319&journals%5B%5D=2350&journals%5B%5D=2349&journals%5B%5D=2340&journals%5B%5D=2326&journals%5B%5D=2348&journals%5B%5D=2347&journals%5B%5D=2325&cleared%5B%5D=2342&cleared%5B%5D=2341&cleared%5B%5D=2178&cleared%5B%5D=2186
Méthode de demande: GET
Code d’état: 500  (de service worker)
Stratégie de point d’accès: no-referrer

**En-têtes de réponse**
content-length: 576
content-type: text/html
date: Thu, 26 May 2022 20:26:25 GMT
server: openresty
strict-transport-security: max-age=63072000;includeSubDomains; preload

**En-têtes de demande**
En-têtes provisoires sont affichées.
En savoir plus
Accept: application/json, text/javascript, */*; q=0.01
Referer
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Microsoft Edge";v="101"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
X-CSRF-Token: FyjYViOy2kuwUkCSj9Ch0iNvyKDuLW0WHzNe70TX
X-Requested-With: XMLHttpRequest
`

### Steps to reproduce

1. Select some line to reconcile
2. Click on Reconcile (Stocker le rapprochement)
3. No popup
4. Remove some line
5. Click on Reconcile (Stocker le rapprochement)
6. Popup display correctly

**Comment by JC5** [comment]
Yes, this is a known issue. Several issues about this can be found. I hope to fix this in the new layout, thanks!
