### ISSUE TITLE
Custom import tag

### ISSUE THREAD

**Issue by bpmb82** [firefly-iii/firefly-iii#6108]
### Support guidelines

- [ ] Determine acceptable format and placeholders.
- [ ] Add to Configuration object.
- [ ] Process after upload instead of default tag.

### Description

I would like to be able to add custom tags for every import. Currently, we have the built in 'Data Import $DATE' tag for imports but I would like to customize this tag.

Being able to customize the tag will allow me to decide what kind of import it is and create specific rules to handle them. As an example, I could create a separate import for every account I have and delete transfers between my own account to remove any duplicates.

This would allow me to run a single Fidi instance with the following command to automate the imports:
`php artisan importer:import /configs/*.json`

I would have multiple .json files in that folder, each defining a specific custom tag for that specific account.

### Solution

The possibility to remove any duplicate entries you might have because of transfers between your own accounts.

Probably a lot of other stuff but this is my specific interest.

### Additional context

https://github.com/firefly-iii/firefly-iii/discussions/6107

**Comment by JC5** [comment]
It's on the list!

**Comment by JC5** [comment]
This is part of 1.3.0
