### ISSUE TITLE
Adding initial bank with balance results in Error 500

### ISSUE THREAD

**Issue by nineff** [firefly-iii/firefly-iii#6113]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Even though this is a 500 error, I think it is not related to wrong or missing configuration.
I set up Firefly-iii manually following [these instructions](https://docs.firefly-iii.org/firefly-iii/installation/self_hosted/)

Upon the first usage, I was able to setup a user and password and was invited to enter the name and balance of the first bankaccount. After i entered the value (including a fraction). I got the 500 Server error with the following message:

`bcadd(): Argument #2 ($num2) must be of type string, float given` 

I think the error might be related to localization since I'm using the german version which has different Decimal- and Thousands separators than the default english version.

### Expected behaviour

No error on entering the first bank account value

### Debug information

The logfile is here: https://gist.github.com/nineff/8adb7bc9869a6ff24e01d4b3bba750d9

### Additional info

OS: Arch linux 64 bit

**Comment by JC5** [comment]
Which version of Firefly III?

**Comment by nineff** [comment]
> Which version of Firefly III?

5.7.6

**Comment by nineff** [comment]
I just tested the en_US locale and I still get the same error. 
Also I should mention I'm using SQLite as database backend, PHP 8.1.6

**Comment by JC5** [comment]
Thanks. I see a possible issue, a fix will be out soon!
