### ISSUE TITLE
Wrong source/deposit account when saving transaction

### ISSUE THREAD

**Issue by arn4** [firefly-iii/firefly-iii#6114]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I add a new transaction using a source/destination account that I never used before, instead of creating a new one with the name I typed, Firefly changes it to an exiting one, during the saving process.

### Expected behaviour

I expetct that a new account with the given name is created instead of picking an existing one.

### Debug information

Debug information generated at 2022-05-30 14:24:21 Europe/Rome for Firefly III version **5.6.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.15 |
| Firefly III API | 1.5.5 |
| Build | 106, 28-02-2022 08:34:56 CET |
| PHP | 8.0.16 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 8c5d2bcd-f069-4b18-9575-1d9d401fb345 |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Rome |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | warning, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-11-02 00:00:00 |
| Session end | 2022-05-30 00:00:00 |
| Session first | 2021-11-02 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15 |

### Steps to reproduce

1. Go to New transaction page, suppose you want to create a withdrawal, but the same applies for deposits.
2. In destination account write a name you never used before (not click n anything in the suggestion dropdown)
3. Put random stuff in al others fields (price, source, category etc..) they do not matter
4. Save the transaction
5. If now you go to the newly created transaction you will see that the deposit account is wrong (for me always the same one, previously created)

### Additional info

I noticed that if I put the flag "Save and create a new one" the page will be already filled with last transaction data, even the deposit account field. Altought, when saving it always go to the wrong one.

I've been using Firefly since November, and at the beginning it was working properly, as in the expected behaviour. It's a copuple of months that is doing like this, also tried to update, but nothing changed

**Comment by JC5** [comment]
I can't replicate this on the demo site, sorry.

**Comment by arn4** [comment]
Do you have any suggestion on how can I investigate? Is there some kind of reset I can do and see if it fix?

**Comment by arn4** [comment]
Just tried Firefox: the same things happened

**Comment by arn4** [comment]
Just updated and it seems to work! My bad, sorry...

Not sure why I was not receiving notification of new updates available, next time I'll check manually before opening an issue

**Comment by JC5** [comment]
No problem!
