### ISSUE TITLE
Docker images to also be tagged on their major and minor version

### ISSUE THREAD

**Issue by karvounis** [firefly-iii/firefly-iii#6117]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like the Docker images of Firefly-iii, found in [DockerHub](https://hub.docker.com/r/fireflyiii/core), to be tagged on their major and minor versions. Right now, the new patch releases do not create a newer version of the minor and major release. You can find the list of available tags [here](https://hub.docker.com/r/fireflyiii/core/tags).
Currently, the tags follow the format: `fireflyiii/core:version-X.Y.Z`. For every patch release, a new docker image is going to be created and be tagged as `fireflyiii/core:version-X.Y.<Z + 1>`. I am missing the functionality to only specify a major or minor version in my Docker-compose files.

### Solution

I would like to have the opportunity to use a Docker image with a tag that only cares about the major or minor version. For example, in my docker-compose setup I would specify `fireflyiii/core:version-X.Y` or `fireflyiii/core:version-X` and I would get the latest tag for version `X.Y` (we do not care about the Z value) and latest tag for version `X` (we do not care about the Y or Z versions) respectively.
This approach to Docker image tagging is a widespread convention that a lot of companies do.

**Comment by JC5** [comment]
Not a bad idea, I'll see what I can cobble together!

**Comment by karvounis** [comment]
Cool! Looking forward to it!

**Comment by JC5** [comment]
https://hub.docker.com/repository/docker/fireflyiii/core/tags?page=1&ordering=last_updated 👍🏻

**Comment by karvounis** [comment]
Cheers @JC5 !
