### ISSUE TITLE
Rules which use "Category is" trigger do not display clean text on rules page

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#612]
I've noticed that when viewing the Rules overview in the **Rules trigger when** column most work like this:

> Destination account is "Car insurance & tax"

However if you use the "Category is" trigger it displays:

> firefly.rule_trigger_category_is

Teeny tiny flaw

**Comment by JC5** [comment]
Nice catch though! Fixed, will be live in the next release.
