### ISSUE TITLE
Cannot create trigger rules for field values with multiple spaces

### ISSUE THREAD

**Issue by nicklozon** [firefly-iii/firefly-iii#6121]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Rule Triggers do not respect when the field value has multiple spaces. I.e. "Description is.." on value "Meow Mix&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PAY"

### Expected behaviour

Multiple spaces do not prevent the trigger rule from properly matching on the field.

### Debug information

Debug information generated at 2022-05-31 22:20:23 America/Toronto for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 190, 31-05-2022 06:23:12 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Toronto |
| Browser TZ | America/Toronto |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_CA |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-05-01 00:00:00 |
| Session end | 2022-05-31 23:59:59 |
| Session first | 2022-01-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36 |

### Steps to reproduce

1. Create a transaction with a description containing multiple spaces. I.e. "Meow Mix&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PAY"
2. Select the `Create rule base on transaction` from the Actions menu from the Transaction Details page
3. Remove all trigger rules except `Description is..`
4. Click `See matching transactions`
5. No results returned

Example demo site transaction: https://demo.firefly-iii.org/rules/create-from-journal/441

### Additional info

I've narrowed the issue down to the query parser library which converts any consecutive whitespace characters to a single space: https://github.com/gdbots/query-parser-php/blob/v2.0.2/src/Tokenizer.php#L92

Even though it's a "phrase" query, the library doesn't allow multiple spaces...I'm guessing it may be an elasticsearch nuance.

Here are the lines of code where firefly pulls the scrubbed value from the query parser: https://github.com/firefly-iii/firefly-iii/blob/249b2c63d8fcd9dded737e2ca8426e6e72507f8d/app/Support/Search/OperatorQuerySearch.php#L210

Here is where the value inevitably ends up being used and doesn't work: https://github.com/firefly-iii/firefly-iii/blob/249b2c63d8fcd9dded737e2ca8426e6e72507f8d/app/Helpers/Collector/GroupCollector.php#L171

**Comment by JC5** [comment]
I know. I'm not going to fix it. See this discussion for some tips:

https://github.com/firefly-iii/firefly-iii/discussions/6096
