### ISSUE TITLE
Integration with Paperless-ng for attachment management

### ISSUE THREAD

**Issue by ShenZhouHong** [firefly-iii/firefly-iii#6135]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Paperless-ng ([Github](https://github.com/jonaswinkler/paperless-ng), [Documentation](https://paperless-ng.readthedocs.io/en/latest/)) is an open source, self-hosted document management system that allows users to organise scanned documents. Users upload scanned documents to Paperless-ng, which automatically converts them to PDF files, performs OCR, and indexes them for easy search and categorisation. Paperless-ng is a powerful tool that is commonly used within the same demographic as Firefly III users (privacy aware, self-hosters), and many people already use Paperless-ng for receipt management.

This feature request proposes an optional integration of Firefly III with Paperless-ng. This way, when a user uploads an attachment for a transaction on Firefly III, the same attachment is automatically uploaded to Paperless-ng. This offers value to the user, because Firefly III by itself does not offer any sophisticated means of managing attachments, making it difficult to search through past receipts.

Currently, users who use both Firefly III and Paperless-ng must manually upload the same attachment to both services.

### Solution

The feature could be implemented in the following manner. Paperless-ng provides an extensive, and [well-documented REST API](https://paperless-ng.readthedocs.io/en/latest/api.html), with support for token-based authentication. A Options page can be added to Firefly III which allows the user to configure this optional integration.

Within this page, the user can add their Paperless-ng endpoint and API token, as well as configure some settings. For example, the user can set whether or not Firefly III should upload only PDFs to Paperless-ng, or PDFs and image files and office documents as well (which Paperless-ng also supports) Once configured, every time a transaction is saved with attachment(s), Firefly III will perform a POST request to the Paperless-ng API, with the uploaded attachment. 

This way, when new transactions are added, the receipts will be automatically made available in Paperless-ng. In the future, should the user need to search for a receipt, they can use Paperless-ng to search through the history of uploaded attachments. This integration should also allow the user to share metadata with Paperless-ng, such as automatically assigning uploaded documents with the same tag as the original transaction.

### Additional context

Some additional considerations for the implementation.

Paperless-ng attempts to convert newly uploaded documents to PDF, and also attempts to perform OCR upon them. The resulting saved documents that paperless-ng makes available are different from the original uploads, which do not have searchable/selectable text on them (and might not be PDFs in the first place).

A more sophisticated integration will also proceed to update the attachments on Firefly III with the converted and OCR'ed versions of the attachments. However, this refinement on the feature is more difficult to implement, because Firefly III will have to have some means to query Paperless-ng for the OCR'ed documents. Paperless-ng needs time to OCR uploaded documents, requiring more time for documents with more text (and on slower hardware). So in order for Firefly III to update the attachments to the OCR'ed versions, Firefly III must query Paperless-ng at some set interval.

**Comment by marcelbrueckner** [comment]
I support this feature request. I'm using both applications and would appreciate an integration.

Just be aware that paperless-ng has been abandoned and is superseded by https://github.com/paperless-ngx/paperless-ngx

**Comment by JC5** [comment]
That's a great idea, but I'm not going to make such an integration part of Firefly III. Adding such an integration puts the maintenance burden of Paperless-ng's changes, and whatever direction they wish to go into with their project, on *me*. Any integration with third party app $x$ will be a tightly coupled affair. I'm not going to pull that into my project. This doesn't just apply to Paperless-ng but also to its various forks and any other open source programs.

But to there is a flexible plugin system that can tie into Firefly III. Just like Paperless-ng, Firefly III features a well-documented [REST API](https://api-docs.firefly-iii.org/) that includes support for webhooks. 

I believe that with both API's in place, anybody who is interested in building a coupling between the two projects has everything they need.

**Comment by ShenZhouHong** [comment]
Thank you very much for both of your responses. @marcelbrueckner I believe I have confused Paperless-ngx with Paperless-ng. I am actually using Paperless-ngx myself as well.

@JC5 Thank you for your response. I understand and appreciate the reasons for your decision. I will close the issue for now, and re-open it should I develop my own third-party integration that fulfills this feature.

**Comment by ShenZhouHong** [comment]
@marcelbrueckner 
I ended up taking @JC5 's suggestion, and used Firefly III's native webhooks support to create a plugin that automates the uploading of transaction attachments on to Paperless-ngx. Specifically, I ended up using [n8n](https://n8n.io/), an open source and self-hostable workflow automation tool (e.g. Zapier, IFTTT).

![n8n-integration-final](https://user-images.githubusercontent.com/6318461/172068991-ca5f646e-4767-4802-9c2e-3e2d3c9499d6.png)

I created a new workflow on n8n, and configured it to listen to webhooks from Firefly III. Every time a new transaction is added, or an existing transaction is updated, Firefly III sends the transaction data to n8n's webhook endpoint. There, n8n ingests the provided data, and if the transaction has attachments, it will automatically retrieve and upload said attachments to Paperless-ngx.

This whole process uses Firefly III webhooks, personal auth tokens, and Paperless-ngx's REST API. It works well, is seamless and invisible to the end user, and requires only moderate configuration- assuming that n8n is available. I am currently self-hosting an instance of n8n, but I believe a free hosted version is available as well.

I will write a more detailed tutorial on my website later, but in the meantime here are some specific steps in the configuration process to enable such a setup.

## Generating a Personal Authentication Token on Firefly III

First, you must generate a personal authentication token on your instance of Firefly III. That can be done under the `Home > Profile > OAuth` tab of your Firefly III installation. We will need this token to register webhooks.

## Registering Webhooks on Firefly III using curl

Next, we must register two webhooks on Firefly III. A webhook is a special URL that is given to Firefly III, where Firefly III will send data to upon an user-defined event. Firefly III's documentation on webhooks [can be found here](https://docs.firefly-iii.org/firefly-iii/pages-and-features/webhooks/).

Unfortunately, as of time of writing (2022-06-05) Firefly III does not have a GUI web interface that allows you to register webhooks. We can only register webhooks using the raw API. The easiest way to do so is to use CURL:

### Register an On-Update Webhook

```
curl -X POST 'https://[firefly domain name]/api/v1/webhooks' \
  -H 'accept: application/vnd.api+json' \
  -H 'Authorization: Bearer [Personal Auth Token]' \
  -H 'Content-Type: application/json' \
  -d '{
  "active": true,
  "title": "Paperless-ngx Integration (via n8n) On Update",
  "trigger": "TRIGGER_UPDATE_TRANSACTION",
  "response": "RESPONSE_TRANSACTIONS",
  "delivery": "DELIVERY_JSON",
  "url": "[n8n Webhook URL]"
}'
```

### Register an New Transaction Webhook

```
curl -X POST 'https://[firefly domain name/api/v1/webhooks' \
  -H 'accept: application/vnd.api+json' \
  -H 'Authorization: Bearer [Personal Auth Token]' \
  -H 'Content-Type: application/json' \
  -d '{
  "active": true,
  "title": "Paperless-ngx Integration (via n8n) On New",
  "trigger": "TRIGGER_STORE_TRANSACTION",
  "response": "RESPONSE_TRANSACTIONS",
  "delivery": "DELIVERY_JSON",
  "url": "[n8n Webhook URL]"
}'
```

You will be able to find the `[n8n Webhook URL]` by creating webhook nodes on n8n, and copying the URL from there.

Other useful webhook-related curl commands:

### Get list of all webhooks

```
curl -X GET 'https://[firefly domain name/api/v1/webhooks' \
  -H 'accept: application/vnd.api+json' \
  -H 'Authorization: Bearer [Personal Auth Token]' \
  -H 'Content-Type: application/json'
```

### Update an existing webhook
For instance, to set it's `"active"` property to `false`. 

```
curl -X PUT 'https://firefly.hong.io/api/v1/webhooks/[Webhook ID]' \
  -H 'accept: application/vnd.api+json' \
  -H 'Authorization: Bearer [Personal Auth Token]' \
  -H 'Content-Type: application/json' \
  -d '{
  "active": true,
  "title": "Paperless-ngx Integration (via n8n) On New",
  "trigger": "TRIGGER_STORE_TRANSACTION",
  "response": "RESPONSE_TRANSACTIONS",
  "delivery": "DELIVERY_JSON",
  "url": "[n8n Webhook URL"
}'
```

## Authenticating HTTP requests against Firefly III using Personal Auth Token

After setting up the webhooks, the majority of the nodes on the n8n workflow consists of sending HTTP requests to Firefly III. This way, we use Firefly III's API. In order to do so, we must have n8n authenticate against the API. You'll have to fill out a Header Auth field like this:

![Screenshot 2022-06-05 at 23-37-24 n8n - ▶️ Firefly III to Paperless-ngx Integration](https://user-images.githubusercontent.com/6318461/172069646-6124ed83-3bfd-45b5-9f80-b49aae3f5525.png)

I hope this information is sufficient to let you create your own automation task. You'll have to do your own implementation of the n8n workflow, as this is unfortunately not a comprehensive guide. If I have time, I'll write a tutorial about this process in the future, but I hope that in the meantime I've covered the most difficult parts of implementing such a plugin.

**Comment by ShenZhouHong** [comment]
To @marcelbrueckner and others who are seeking to accomplish the same integration:

I have created a tutorial documenting the process in creating an n8n automation workflow to automatically upload attachments from Firefly III to Paperless-ngx. Feel free to check it out below!

https://shen.hong.io/guide-to-workflow-automation-using-n8n-to-manage-receipts/
