### ISSUE TITLE
Additive Budget is smaller than usual amount

### ISSUE THREAD

**Issue by simphide** [firefly-iii/firefly-iii#6148]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I've set a budget to accumulate if it is not completly spent. I noticed that the amount for this month is smaller than the usual budget (probably because I spent more than the budget last month).
 

Budget:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/8183517/172708078-4ea39c69-5eb1-49d0-91c2-fa1b24b3d2bd.png">

Settings:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/8183517/172708182-75f68458-08d9-4fa9-bddb-b42bad270db5.png">

Edit: I just took a look and it is definetly the overspent amount minus the usual amount:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/8183517/172709421-3ee1c661-9dd7-4abb-8070-02450e54524f.png">

### Expected behaviour

The amount is set to the normal budget (167,5)

### Debug information

Debug information generated at 2022-06-08 22:12:36 Europe/Berlin for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 193, 01-06-2022 06:18:57 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-06-01 00:00:00 |
| Session end | 2022-06-30 23:59:59 |
| Session first | 2021-09-30 00:00:00 |
| User ID | 2 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36 |

### Additional info

I don't have any logs since I already restarted the container stack...

**Comment by JC5** [comment]
Nice find, this will be fixed in the next release :+1:
