### ISSUE TITLE
Mass edit improvements

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#615]
Add budget. Make inputs smaller.

**Comment by BoiDLi** [comment]
Hello,

I would like to benefit from this feature.  I upgraded my install to 4.3.7 but can't seem to find it.
Is this commit done in a version that is not released yet?

Thank you,

Yoann

**Comment by JC5** [comment]
It's not yet released, but I will do so pretty soon.

**Comment by JC5** [comment]
This is now fixed in 4.3.8

**Comment by BoiDLi** [comment]
Thank you very much! It's a pleasure to see how fast you react.

Regs,

Yoann
