### ISSUE TITLE
Bills / Budget options request

### ISSUE THREAD

**Issue by tamimology** [firefly-iii/firefly-iii#6151]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- In Bills, it would be good to have an option with an exact amount for the current )comming) bill. Min/Max is good to have, but once the bill is issued, we do have some time to pay, and we can have the exact amount entered in the bill, and keep the min/.max for the next one. This min/max can be auto-calculated based on the average exact amounts paid over a year or 6 months time.
- 
- In Budgets, it is also good to have the date range for this budget, i.e. my budgets are based from 15th of the current month till the 14th of the next month, while in Firefly, it is rolled over each beginning of month (confuses me and misleads my calcualteions)

### Solution

described above

**Comment by JC5** [comment]
Sorry, the bill behaviour will not change.

Budgets can be set to go from the 14th to the 15th, though this is not possible through the user interface. You could cobble something together using the API. Generally speaking though, I recommend you to start budgeting per month regardless of when your paycheck arrives.
