### ISSUE TITLE
Allow creation of splits via rule action

### ISSUE THREAD

**Issue by davidclemens** [firefly-iii/firefly-iii#6154]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

As far as I can see, splits can "only" be created manually, when editing a transaction (expenses, income or transfers). It would be very useful to be able to do this via the action part of a rule.

### Solution

I'm aware that this suggestion is close to the section "More complicated rules, like AND or OR, copy/pasting values, etc" in [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/), but hear me out:

Incorporate an action "add split".

If I see this correctly, the actions are kept simple and "only" accept one `Action value`. To work with this "constraint", the `Action value` would be the amount of the new split. Each split created this way would get a default name, that is predicatable (e.g. `<date>_split-01`). With another rule, these default names could then be changed subsequently.

If on the other hand, it would be relatively easy to add a second `Action value` per action, the first one could be the amount and the second one the description.

### What are alternatives?

Manually adding splits to each transaction.

### Additional context

In our case, we import transactions via the [FinTS importer](https://github.com/bnw/firefly-iii-fints-importer).
For the monthly transaction of the warm rent ("Warmmiete"), we'd like to split it into the net rent ("Kaltmiete"), heating and service charges ("Betriebskosten"), to have categories and tags properly assigned and easily calculate whole year sums.

Another analogous scenario for us would be the case described in #6155. 

Thanks for your great work on this. It is a tremendous help to us!

**Comment by JC5** [comment]
No, sorry. This is one of those things that rules will not be doing. I understand the use case though. You could use webhooks perhaps? They're not yet in the UI but you can use the API to access them. Tools like n8n may be capable of updating the transaction in the way you want it.
