### ISSUE TITLE
Allow to split a transaction into a mix of expense or revenue splits

### ISSUE THREAD

**Issue by davidclemens** [firefly-iii/firefly-iii#6155]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Right now, when adding splits to a transaction, they have to be of the same type (either expense, income or transfer).
It'd be helpful, if e.g. a transaction of the net-salary (income) could be split into the gross-salary (income) and all the deductions (expenses), like taxes, insurance, etc.. This would allow more detailed per-category tracking.

### Solution

Allow inversing the direction of the money between the two accounts that are part of the (split-)transaction.

To stay with the example from above:

Transaction "Salary 06/2022": Employer-Account -> 2000€ -> `My-Account`

could be split into:

- 1 "Gross-Salary": Employer-Account -> 3200€ -> `My-Account`
- 2 "TaxA": `My-Account` -> 225€ -> State-Account
- 3 "InsuranceA": `My-Account` -> 105€ -> InsuranceA-Account
- i (...) 
- n "Net-Salary":  Employer-Account -> 2000€ -> `My-Account`

Maybe in the UI it could be implemented with a button that allows to swap the `Source Account` and the `Destination Account` fields for each split independently. Of course one of the two has to remain `My-Account`.

### What are alternatives?

Create individual transactions. However, this would only be a work-around.

### Additional context

I hope the scenario is understandable. I'm happy to clarify, if neccessary.

Thanks a lot for looking into this and the amazing project!

**Comment by JC5** [comment]
That's not going to be an option, sorry.
