### ISSUE TITLE
The ability to link transactions

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#616]
To replace advance payment tag and balancing act tags. And maybe other features.

**Comment by Zsub** [comment]
One ability I would like is to link multiple expenses and withdrawals. As a practical example, suppose I travel for my work, maybe I attend a conference. I will have to pay the conference in advance. While most costs are covered by that, there will be some costs that are not included, such as lunches. I have been granted a partial advance from my employer. When I am back, I will try and recoup all expenses from my employer.

This means that there are multiple expenses, all of which are related to that trip. The fact I have received a partial advance means I will receive at least two withdrawals from my employer. Therefore there are multiple transactions (of both types), all of them related, that I would like to link.

I'm not sure if I would like to see those expenses and withdrawals in my overviews, or if there is a certain way this should work :)

**Comment by JC5** [comment]
@Zsub @flow7 

The demo site now features transaction linking. Under the options menu for each transaction is the option to link transactions. This doesn't actually DO anything except link them but it works.

You'll be able to add your own link types as well (not possible on the demo site.

https://firefly-iii.nder.be/

Check it out, and let me know what you think.
