### ISSUE TITLE
Can't assign same account number to expense and revenue accounts

### ISSUE THREAD

**Issue by SvbZ3r0** [firefly-iii/firefly-iii#6165]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I can't create a revenue account when there is an expense account with the same account number. It says, "It looks like this account number is already in use."

### Expected behaviour

As per the documentation, one expense account and one revenue account can share account numbers.

### Debug information

Debug information generated at 2022-06-15 08:10:54 Asia/Calcutta for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 196, 09-06-2022 18:30:26 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Asia/Calcutta |
| Browser TZ | Asia/Calcutta |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `192.168.0.101` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-06-01 00:00:00 |
| Session end | 2022-06-30 23:59:59 |
| Session first | 2013-07-24 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Create an expense account with an A/c number
2. Try to create a revenue account with the same A/c number.

I have tried it the other way around too.

### Additional info

Account number; not IBAN. My country doesn't use IBAN, so I can't test if the problem exists with IBAN too.

**Comment by JC5** [comment]
That's a bug, thanks!

**Comment by sporkbyspork** [comment]
I think I have the same issue with a brand new installation:

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 196, 09-06-2022 18:30:26 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

I successfully imported transactions from my primary account (asset).
Then I wanted to create a second asset account.
As the primary account has "revenue" from the second one and vice versa, I can not create the second account.
