### ISSUE TITLE
Add Docker Health check

### ISSUE THREAD

**Issue by AlexisTonneau** [firefly-iii/firefly-iii#6167]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I'm using Docker to host my firefly instance. The startup task is pretty long, so it would be useful to add a Docker healthcheck  instruction to let users know when it's ready without needing ti check logs.

### Solution

Just add a curl command to the healthcheck to check if it's alive.

**Comment by AlexisTonneau** [comment]
I was refering to the [built-in Docker health check](https://docs.docker.com/engine/reference/builder/#healthcheck) feature. My idea is to add an healthcheck instruction to the Dockerfile. It is not covering the same thing that the `health` endpoint.

**Comment by JC5** [comment]
Cool, I'll check it out.

**Comment by apollo13** [comment]
I was just wondering why firefly didn't "start". The current health check definition of https://dev.azure.com/firefly-iii/BaseImage/_git/BaseImage/commit/8f336c4f24e12a1e419a289d37a9f2d90bc8d9a8?refName=refs%2Fheads%2Fmain means that the container is not usable for the first 5 minutes when used with proxies like traefik. I think an interval of 1m is probably a better default.

**Comment by JC5** [comment]
I guess somebody will have to tell the Traefik devs there is a difference between "starting" and "unhealthy".

**Comment by rhuanbarreto** [comment]
In k8s there are startup, readiness and liveness probes. Where should I use the /health or the / endpoint?
