### ISSUE TITLE
Incomplete without categorical data

### ISSUE THREAD

**Issue by alei643** [firefly-iii/firefly-iii#6168]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In categories page,When I click no categories, the firefly displays all the records that are not classified. At this point I choose a time from the right side of the page, All records within this time period are displayed. But when I clicked on the page number, no record was listed.

There are actually multiple pages of records, but only one page can be displayed,the rest of the records cannot be displayed 

### Expected behaviour

none

### Debug information

Debug information generated at 2022-06-18 06:57:21 UTC for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 193, 01-06-2022 06:18:57 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Asia/Shanghai |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-06-01 00:00:00 |
| Session end | 2022-06-30 23:59:59 |
| Session first | 2016-01-01 00:00:00 |
| User ID | 1 |
| User language | zh_CN |
| User locale | zh_CN |
| Attempt at "zh_CN.utf8" | 'zh_CN.utf8' |
| Attempt at "zh_CN.UTF-8" | 'zh_CN.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0 |

**Comment by JC5** [comment]
Nice find, I'll pick it up!
