### ISSUE TITLE
When changing date of transaction, piggy bank event date is not updated accordingly

### ISSUE THREAD

**Issue by ultrara1n** [firefly-iii/firefly-iii#6169]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If you create a transaction with an associated piggy bank and change the date of the transaction afterwards, the date of the piggy bank is not updated accordingly.
![Create transaction](https://abload.de/img/screenshot2022-06-18177km3.jpg)
![Event entry](https://abload.de/img/screenshot2022-06-181cgjce.jpg)
![Date changed](https://abload.de/img/screenshot2022-06-181y7kk8.jpg)
![Event date same](https://abload.de/img/screenshot2022-06-181g4jm1.jpg)

### Expected behaviour

The date of the piggy bank should updated accordingly to the connected transaction.

### Debug information

Debug information generated at 2022-06-18 14:23:46 Europe/Amsterdam for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 193, 01-06-2022 06:18:57 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-06-01 00:00:00 |
| Session end | 2022-06-30 23:59:59 |
| Session first | 2022-03-10 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36 |

**Comment by JC5** [comment]
That's true. It's also not going to change, sorry.

**Comment by ultrara1n** [comment]
May I ask why?

**Comment by JC5** [comment]
It's just a convenience feature to quickly add money to a piggy bank. It's not meant to be historically accurate.

**Comment by ultrara1n** [comment]
Okay, but this seems not to only affect changes of the date but also changes of the amount.
If i change the screenshotted transaction to 150 Euro, this is also not updated in the corresponding piggy bank event and the piggy bank total is the same as before.

**Comment by ultrara1n** [comment]
Then you are getting states like this
![Screenshot](https://abload.de/img/screenshot2022-06-181ndkvp.jpg)
