### ISSUE TITLE
Search query with open/close parens does not return known-valid matches

### ISSUE THREAD

**Issue by skorvek** [firefly-iii/firefly-iii#6170]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Search in description containing open and close parentheses does not match transactions

### Expected behaviour

Search for description is  or contains or starts with "Requested transfer to SCOTT J KORVEK (MANASQUAN BANK Checking xxxx)" where xxxx is part of my account number returns 0 matches.  Truncating the query to "Requested transfer to SCOTT J KORVEK (MANASQUAN BANK" works  - removing the closing parens is what allows non-zero matches.

### Debug information

Debug information generated at 2022-06-18 21:33:02 America/New_York for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 196, 09-06-2022 18:30:26 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | production |
| App debug mode | true |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-06-01 00:00:00 |
| Session end | 2022-06-30 23:59:59 |
| Session first | 2001-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.125 Safari/537.36 |

### Steps to reproduce

Search on the full transaction text
Truncate the search string

**Comment by JC5** [comment]
It finds the result just fine in my case, I can't replicate this.

![Screenshot from 2022-06-19 06-23-13](https://user-images.githubusercontent.com/5889984/174465750-f0fd2433-390e-4bd8-b532-581c0ccfa564.png)

**Comment by skorvek** [comment]
Yeah,  I am starting to think the parens was a red herring.  I have had this issue a few times now where I adjust a rule template (what gets pre-populated when creating a rule from a transaction) and truncate the description, usually to remove some index or other irrelevant text from the match. Then I check and I have no matches (after touching no other rule parameters yet) when I should have plenty- if nothing else the initial transaction which prompted the rule.  I can then go an add back the rest of the text exactly as it was (caps, spacing, etc) but still no matches.

Might it have to do with the spaces?  I'll post examples as I find them- I've had several yesterday.

**Comment by JC5** [comment]
Multiple spaces are filtered out by the underlying library, and you won't be able to search for them. So if you have something like this:

```
"word    lots of  spaces   another word"
```

The search will not be able to find the whole string. Only the individual words.

**Comment by JC5** [comment]
I'm afraid not. The importer will import as-is and the search can't handle multiple spaces between words. I'm working on a solution. Until then, you have to filter out the spaces yourself OR search word for word (so multiple `description_contains` in a row).

**Comment by skorvek** [comment]
Would a rule help here?  I'd have to make a rule for each problematic description but if I can get it to match in the rule description, I can replace the text in the rule action. Of course then the text wouldn't be dynamic, but in this case it wouldn't matter.

**Comment by JC5** [comment]
If you can find the offending transaction(s) with multiple description_contains searches (see the dropdown when you create a role), then yes.
