### ISSUE TITLE
Add the "Add Attachment" option to the actions dropdown menu next to transactions to make attachment uploads faster

### ISSUE THREAD

**Issue by ShenZhouHong** [firefly-iii/firefly-iii#6179]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

A picture of the actions dropdown menu:

![Screenshot 2022-06-20 at 12-48-32 All expenses between June 1st 2022 and June 30th 2022 » Transactions » Firefly III](https://user-images.githubusercontent.com/6318461/174576390-a02a20be-ce25-48c6-a2ea-ff984f49ee5e.png)

A common workflow for Firefly III users is to create transactions throughout the day, as expenses are accrued. Receipts are saved by the user in their wallet, and when they return home at the end of the day, they scan their receipts and update their transactions by attaching their scans to the relevant entries.

However, the user experience for adding attachments to existing transactions is a little clumsy. Starting at the transaction screen, the user must take multiple steps to get to the file upload picker:

1. Click on the Action dropdown menu
2. Click on the Edit option
3. Wait for page refresh, as the user is redirected to the transaction edit page.
4. Click on the "Browse Button"

This experience requires at least four steps, and requires two more additional steps (a page refresh, and clicking on the transaction sidebar entry) for the user to return back to the transaction screen. *This makes for a total of six steps.* This is okay if you only have one or two transactions to update, but for the workflow mentioned above, it is common for the user to come home with four or five different receipts to upload, and possibly even more.

The fact that it takes so many steps to complete this action degrades the user experience for this particular workflow, and the workflow is not even an unusual one, which means it could potentially impact many users. Thankfully, the solution is simple.

### Solution

Simply add an "Add Attachment" option to the existing actions dropdown menu next to transactions.

The option should directly launch the File Upload Picker, as if the user directly clicked on the Browse button for that transaction. When the user selects and uploads a file, *preferably Firefly III should not trigger a page refresh at all*. This way, when the user has a list of attachments to upload, they can simply remain in the Transactions page, and click on Actions > Add Attachment for every entry one after the other. 

### What are alternatives?

The most difficult part of this solution is to have Firefly III not trigger a page refresh after the attachment is uploaded. This is preferred, so the user does not have to wait for the page to update, and can simply go down their list of transactions uploading attachments one after the other.

However, when an attachment is uploaded, Firefly III must display the small paperclip icon next to the transaction. If this update could be done using JavaScript without refreshing the page, that is ideal.

Even if it were not possible, triggering a page refresh on upload is still better than the previous process of six steps, with two page refreshes in the process.

**Comment by JC5** [comment]
I was planning on extending these lists in the new layout, and this is a good idea to add!

**Comment by ShenZhouHong** [comment]
Awesome! Looking forwards to seeing it in the new layout.

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/6304
