### ISSUE TITLE
Emergency Stop button for import tool

### ISSUE THREAD

**Issue by skorvek** [firefly-iii/firefly-iii#6180]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I've had some problems with data import- not a problem with the system, but other data file problems not caught prior to starting an import (like Excel "helpfully" displaying m/d/y on a date field in a CSV field where the underlying data is really m/d/Y or not catching that the amount column is negated or reusing a common import file config and forgetting to change the import account, etc, etc.)

This requires me to delete transactions.  What I've noticed is that even though I've hit "Start over" and even "reauthenticate" the importer keeps on parsing that file until it's finished.

### Solution

I'd like a "stop import" button while the parser is running to terminate the current job when I realize an issue.

**Comment by JC5** [comment]
The "beauty" of PHP is that the active script will keep running in the background, even when you cancel the request. There's not much I can do but to recommend you to import smaller batches.
