### ISSUE TITLE
Toggle All accounts on manual rule run dialog

### ISSUE THREAD

**Issue by skorvek** [firefly-iii/firefly-iii#6181]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

When running a rule manually, the application criteria defaults to all dates inclusive and all accounts.  While for many rules I specify an account or other limiting criteria to prevent unintended consequences, I often want to be double sure (or have written a more general rule but at that point want to selectively apply it) and have to deselect all accounts except one or two. 

### Solution

Add a "select/deselect all" button to the rule application criteria dialog that toggles on/off all accounts listed on the page.

**Comment by JC5** [comment]
I have already planned this to be easier in the new layout :+1:
