### ISSUE TITLE
Cloning a withdrawal with a split creates a deposit

### ISSUE THREAD

**Issue by skorvek** [firefly-iii/firefly-iii#6186]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I've taken a withdrawal from an asset account to a liability and created a split transaction. Cloning it to create the next entry creates a deposit and messes up the accounts.

### Expected behaviour

Cloning a split withdrawal should create another split withdrawal without changing accounts.

### Debug information

Debug information generated at 2022-06-23 08:59:17 America/New_York for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 196, 09-06-2022 18:30:26 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | production |
| App debug mode | true |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-06-01 00:00:00 |
| Session end | 2022-06-30 23:59:59 |
| Session first | 2001-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.125 Safari/537.36 |

### Steps to reproduce

- Create or import a withdrawal from an asset account (checking account) to a liability (mortgage).
  - Asset account balance decreases by withdrawal amount.
  - Liability account balance moves closer to zero.
- Split the withdrawal into a principal payment and interest payment
  - Split 1: Source is asset account (checking) destination is liability (mortgage) for principal amount
  - Split 2: Source is asset account (checking) destination is expense account (interest)
- Dates are the same, categories and tags vary, budget is household bills, bill is mortgage bill
- Save
  - Success message.
  - Transaction type appears as withdrawal with all the correct details as above
- From the transaction detail page, choose clone
  - New transaction is of type deposit with current date
  - The first split is correct: source is checking account destination is liability
  - The second split is incorrect: source is an income account (interest income) and destination is the checking account
  - The liability transaction list will show a transfer symbol next to the deposit with blue text. Clicking to see the detail will bring up the entire transaction listed as "deposit"
 
The issue cannot be corrected- as the transaction editor now shows split 1 correctly as above, and split 2 as a deposit with the destination fixed as the checking account. So only the source can be changed and that is expecting a revenue account.

### Additional info

In this case the revenue account being pulled in incorrectly is "Interest Income" and the expected expense account is "Mortgage Interest Collings" so not clear how that could even happen on a code level.

I followed your documentation guide in choosing which transaction to create

[https://docs.firefly-iii.org/firefly-iii/support/transaction_types/](https://docs.firefly-iii.org/firefly-iii/support/transaction_types/)

So Asset to Liability is loan payment
Asset to Expense - normal expense  

I am not keen to create asset to liability and then a separate transaction loan to expense account (listed as paying your loanshark in the docs). That will make the graph oscillate and make it hard to see the % of each payment to principal as now I have 2x as many transactions as occurred. This loan doesn't add separate transactions for interest like a credit card or home equity line of credit would. There's one transaction on the register and it's split as I'm trying to do which is very common in US mortgage statements.

Regardless- I would not expect the above behavior at all.

**Comment by JC5** [comment]
I can't replicate this on the demo site. These transactions are perfect copies.

https://demo.firefly-iii.org/transactions/show/460
https://demo.firefly-iii.org/transactions/show/461

**Comment by skorvek** [comment]
What other information can I provide- I did this 6 times before filing a report and can reliably reproduce it.  Screenshots?

**Comment by JC5** [comment]
> I was not aware that a rule could act on a split and create an invalid condition.

That shouldn't have happened, and I'll pick that up as a bug!
