### ISSUE TITLE
Intro popup stops working after the first time.

### ISSUE THREAD

**Issue by dseegers** [firefly-iii/firefly-iii#6188]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After closing the intro popup, it is no longer possible to use it again. Here you will get an undefined message.

### Expected behaviour

After closing the intro popup, you click `You can also turn the introduction popups back on.` and you will get back the into popup

### Debug information

Undefined

### Steps to reproduce

1. Go to contract (xx domain/bills)
2. Finish the intro 
3. Reload the page 
4. Click on the questionmark 
5. See undefined message in a popup

### Additional info

Version: 5.7.9
Lang: Dutch

**Comment by dseegers** [comment]
![image](https://user-images.githubusercontent.com/6848396/175538985-edc9f0ba-38dc-4c5b-816d-83a8151e5e12.png)
![chrome_M37610I7wN](https://user-images.githubusercontent.com/6848396/175539276-f3283daf-11fa-4551-8d51-0f3b3411d01c.gif)

**Comment by JC5** [comment]
I know :(

It happens on certain installations. Since I'm working on a new layout, I'm not going to fix it. Sorry about that.
