### ISSUE TITLE
Provide a phar build

### ISSUE THREAD

**Issue by Dialga** [firefly-iii/firefly-iii#6189]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Please provide a .phar build of firefly-iii.
This will be handy as a single file, drop in deployment using the php builtin server.

### Solution

Use https://github.com/box-project/box/ to build a .phar.

**Comment by JC5** [comment]
Sorry, I'm not really interested or motivated to supply a phar installation file.
