### ISSUE TITLE
Migrated install to new server, throwing error on login

### ISSUE THREAD

**Issue by dfiel** [firefly-iii/firefly-iii#619]
Hello,

I recently migrated my Firefly install and database to another server, by exporting the database and importing it, and copying over the firefly directory from the old server to the new one.

When trying to log in, I get this message:

Type error: number_format() expects parameter 2 to be integer, null given

Full stack trace here:
https://gist.github.com/dfiel/7e1e3c0c708dfa8a007c3f692589e5a3

What would cause this?

Thanks,
     dfiel

**Comment by JC5** [comment]
In your database, open the table `transaction_currencies`. It should have the field `decimal_place`, right below `symbol`.

If it's there, check if the rows in the table have a value in this row. If not, or when it's NULL, fill in the number 2.

**Comment by dfiel** [comment]
My database looks like this: 
![image](https://cloud.githubusercontent.com/assets/7292540/23833339/73b5386c-071a-11e7-974c-23fafb2bbf09.png)

I still get the error as soon as I log in.

**Comment by JC5** [comment]
Alright, run the following commands to clear all caches and what-not:

```
php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan twig:clean
php artisan view:clear
```

Otherwise I have no idea, the code as far as I can trace it back includes the field you seem to be missing (hence the NULL).

The error you post refers to a file in /views/twig/. The one with the long name. If the error persists, include this file as well if you would.

**Comment by dfiel** [comment]
I ran those commands, and they all completed except for php artisan twig:clean.

It gives this output:
![image](https://cloud.githubusercontent.com/assets/7292540/23872500/e7c2859e-0804-11e7-91a7-3ed7e6b566e4.png)

Trying to access Firefly gives the same error.

I tried to find the twig folder it references, but the folder seems to be empty:
![image](https://cloud.githubusercontent.com/assets/7292540/23872528/0246551c-0805-11e7-9fec-3724d4ae9843.png)

**Comment by JC5** [comment]
Well that's good, `view:clear` must have taken care of that.

Your stacktrace refers to a file in this directory: `/storage/framework/views/twig/b5/...`

If the error occurs again, please post the content of this file too.

**Comment by dfiel** [comment]
I can't post the content of the file, as the file no longer exists.

**Comment by JC5** [comment]
So the problem is fixed?

**Comment by dfiel** [comment]
No, I get the exact same error when logging in.

**Comment by JC5** [comment]
The folder /storage/frameworks/views should be filled again. The stack trace will point to a (new) twig file.

**Comment by dfiel** [comment]
[Here](https://gist.github.com/dfiel/8147981398a48496bff21decd153c7ab) is the contents of the php file.

**Comment by JC5** [comment]
Ok, I think I found it but I need your help to debug it.

Find the file [app/Support/Amount.php](https://github.com/firefly-iii/firefly-iii/blob/master/app/Support/Amount.php#L262) and go to line 262.

Replace the content between the brackets (so between `{` and `}`) with the following code:
```php

        $cache = new CacheProperties;
        $cache->addProperty('getDefaultCurrency');
        if ($cache->has()) {
            return $cache->get(); // @codeCoverageIgnore
        }
        $currencyPreference = Prefs::get('currencyPreference', config('firefly.default_currency', 'EUR'));
        $currency           = TransactionCurrency::where('code', $currencyPreference->data)->first();

        if (is_null($currency)) {
            throw new FireflyException(sprintf('No currency found with code "%s"', $currencyPreference->data));
        }

        $cache->store($currency);

        return $currency;

```

If you are unsure what to do, [this is what the function should look like](https://github.com/firefly-iii/firefly-iii/blob/develop/app/Support/Amount.php#L262).

After you have done so, run these commands to clear the caches:

```
php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan view:clear
```

Then, try again.

**Comment by dfiel** [comment]
I downloaded the new Amount.php from the link you posted onto the server, ran the commands, and I get the same error.

**Comment by JC5** [comment]
Alright, [here's a version with a lot of debug commands](https://github.com/firefly-iii/firefly-iii/blob/develop/app/Support/Amount.php). Replace the content of Amount.php with this version, and also open your `.env` file and set `APP_LOG_LEVEL` to `debug`.

Then, run the cache clearing commands again. When the error occurs again, the error in the log file should be preceded by a lot of debug information. Could you post that information?

**Comment by JC5** [comment]
File was updated slightly just now.

**Comment by dfiel** [comment]
Sorry that I didn't get back to you earlier.

I uploaded the new Amount.php, cleared the cache, and now I'm able to log in! Seems like whatever you did fixed it. I'm going to mess around with it this weekend and see if I run into any more problems.

**Comment by dfiel** [comment]
Just took a closer look at the page, and it seems like some graphs aren't loading.

Budgets and Spending looks like this:
![image](https://cloud.githubusercontent.com/assets/7292540/24068331/8c61b2a4-0b62-11e7-832f-26532fa82be3.png)

and the Dev Console shows this:
![image](https://cloud.githubusercontent.com/assets/7292540/24068339/9aaf78aa-0b62-11e7-89d5-da9766fec2ab.png)

**Comment by JC5** [comment]
Try a hard refresh, clearing your browser cache. Depending on your previous version, you may have some old JS in your cache.
