### ISSUE TITLE
[Helm] data-importer - Not possible to configure volume for configuration files

### ISSUE THREAD

**Issue by mmalyska** [firefly-iii/firefly-iii#6195]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Currently it's not possible to setup configuration files in data-importer chart.

### Solution

I would like to have option to import files.
In my case It would be from `Secrets` because I'm using Nordigen as source and there is secret part.
But in general usecase as CSV it would be enough to use simple `ConfigMap`.

### What are alternatives?

There is non, as there is no option to mount volumes.

**Comment by JC5** [comment]
What do you think @morremeyer, is this something that can be added?

**Comment by mmalyska** [comment]
Hi, is there any update on this?

**Comment by rarosalion** [comment]
I've just come across this issue as I have discovered the same limitation. Without modifying the helm charts directly I'm unable to add [pre-made configuration files](https://docs.firefly-iii.org/data-importer/help/config/) to the import pods.

While there are a few different solutions to this issue, if you were to modify the helm charts to allow custom volumeMounts, end users could add additional configs via secrets/configmaps/nfs mounts/etc (whatever they prefer). This might also allow other customisation without significantly altering the helm charts in future. The bitnami helm charts allow this via a "extraVolumeMounts" value.

**Comment by morremeyer** [comment]
This will be possible with https://github.com/firefly-iii/kubernetes/pull/46

**Comment by JC5** [comment]
It's merged! Thanks again for the efforts, @morremeyer!

**Comment by mmalyska** [comment]
Thank you! That's what I needed.
