### ISSUE TITLE
API: get_available_budgets - returns no data and creates new budget time period

### ISSUE THREAD

**Issue by sgofferj** [firefly-iii/firefly-iii#6198]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I do have budgets defined.
I'm calling `https://firefly-url/api/v1/available_budgets?page=1` as per documentation. The return is empty:
```
data: array[0]
meta: object
  pagination: object
  total: 0
  count: 0
  per_page: 50
  current_page: 1
  total_pages: 1
links: object
  self: "https://firefly-url/api/v1/available_budgets?&page=1"
  first: "https://firefly-url/api/v1/available_budgets?&page=1"
  last: "https://firefly-url/api/v1/available_budgets?&page=1"
```
If I add start and stop, the GET API call will create an additional budgeted time from start to stop inside of FF3 but still not return any data.
`https://firefly-url/api/v1/available_budgets?start=2022-06-28&stop=2022-06-28&page=1`
created an additional budgeted time from 28-06-2022 to 28-06-2022 with the same amount as was budgeted for the current month.

### Expected behaviour

The API call should return a list of the budgets as described in the documentation.

### Debug information

Debug information generated at 2022-06-28 17:53:12 Europe/Helsinki for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 196, 09-06-2022 18:30:26 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Helsinki |
| Browser TZ | Europe/Helsinki |
| App environment | local |
| App debug mode | true |
| App cache driver | redis |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-06-01 00:00:00 |
| Session end | 2022-06-30 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36 |

### Steps to reproduce

Call the available_budgets endpoint

**Comment by JC5** [comment]
Are you confusing "available budget" and "budgets"? I can't replicate this.

<img width="1246" alt="Screenshot 2022-06-28 at 16 59 12" src="https://user-images.githubusercontent.com/5889984/176212538-dac3c316-9664-485f-9208-5db491ca710f.png">

**Comment by sgofferj** [comment]
No. I haven't even noticed total available budget yet because it doesn't show anything in my firefly :scream:
I have multiple budgets (lower part in your screenshot) configured.
I called the API endpoint from NodeRED (I'm learning how to use the API atm) as described and it didn't return anything.

I recently updated over several releases in one jump. Haven't been using FF3 in a while because real-life-stress. Could that be an issue caused byt the update?

**Comment by sgofferj** [comment]
In any case, what happened when I called the API was that where in your screenshot's lower part is "groceries", I suddenly had a second row with the start-stop date range showing the same amount that I set for the whole month.

**Comment by sgofferj** [comment]
Just happened again...
![Screenshot_20220629_103409](https://user-images.githubusercontent.com/3258466/176379030-feba30c9-34c4-4c00-a58a-ed382840ec10.png)

**Comment by sgofferj** [comment]
And this time there was only a get account API call without date...

**Comment by sgofferj** [comment]
OK, I found that problem. For some reason, the period for that budget was set to daily. I assume that was my mistake. Apologies for the wild goose chase.

The problem of the API endpoint returning no data remains.

**Comment by sgofferj** [comment]
I guess, I owe you a case of beer or something... That "edit" button for "available budgets" was too small for my old eyes to see and I didn't set any available budget. I assumed it would be calculated automatically from all separate budgets. I saw it, set it and now everything works as expected.
