### ISSUE TITLE
Withdrawals in piggybanks

### ISSUE THREAD

**Issue by forcaeluz** [firefly-iii/firefly-iii#620]
In on of my piggy banks, I see some withdrawal transactions. Apparently that happens when you started a transfer (there you can select the piggy bank), but then you change your mind and make a withdrawal. (This also happens on the demo site).

In my case, I usually select the "return to this page" checkbox when filling all the entries once a week. So that I don't need to go through the dashboard after every entry. But after I registered one transfer to a savings account, all the withdrawals afterwards are also accounted in the piggy bank.

**Comment by JC5** [comment]
Mmm, I see it. I thought I fixed this a long time ago.

But it will be fixed in the next release, thanks for opening the issue!

**Comment by forcaeluz** [comment]
Thanks for fixing. One question, with the fix, do I still need to clean-up the wrong data I have now myself, or will the update clean that up for me?

**Comment by JC5** [comment]
I'll keep in mind to write something for the "clean database" routine Firefly III already possesses. That will make sure it's fixed when you upgrade.

**Comment by forcaeluz** [comment]
Great! Thanks for fixing, and of course, thanks for firefly! It's really useful!

**Comment by JC5** [comment]
New version will have a "clean" routine.

**Comment by forcaeluz** [comment]
The link between the transaction and the piggy banks are gone, but the amounts of those transactions still influence the value of "saved so far". What I did now was to use the "-" button to correct the saved so far value to what I actually have saved so far. So this is not an issue for me any more, but I though, for the completeness of the item, to let you know that the clean-up still left some data behind. And again, thanks for the fix.

**Comment by JC5** [comment]
Yes, I know. I can't help it I'm afraid. Because I cannot know whether or not it has been fixed already by the user itself, I tried to fix as few things as possible lest I actually break more.
