### ISSUE TITLE
Rollover budget wasn't updated

### ISSUE THREAD

**Issue by earthling-slavlius** [firefly-iii/firefly-iii#6203]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In June there was a rolling budget set.
![image](https://user-images.githubusercontent.com/52633018/176889784-39029c2d-8ace-46cc-9bcf-1360017dfcff.png)
![image](https://user-images.githubusercontent.com/52633018/176889872-c7259c39-e475-4f0b-a818-f57f03536f38.png)

### Expected behaviour

I expected to see 1st July rolling amount (42). Instead, it is empty.
![image](https://user-images.githubusercontent.com/52633018/176890185-1d95b18f-e91a-4526-b0b2-22877273bcad.png)

 

### Debug information

Debug information generated at 2022-07-01 13:52:21 Europe/Berlin for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 196, 09-06-2022 18:30:26 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-07-01 00:00:00 |
| Session end | 2022-07-31 23:59:59 |
| Session first | 2022-07-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37 |

**Comment by JC5** [comment]
What was the output from the cron job?

**Comment by earthling-slavlius** [comment]
Sorry. The issue was with my cron.
