### ISSUE TITLE
Extend Groups concept to Accounts pages

### ISSUE THREAD

**Issue by skorvek** [firefly-iii/firefly-iii#6204]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I've seen a few questions about grouping things, all are closed.  Looking at the accounts lists hurts my head and I cannot glean any useful information from those pages.  Alpha sort is fine, until you get to a lot of accounts. 

The ability to group bills and piggy banks is great- I am able to segregate them as I desire, and even get a nice subtotal for that group.  Same for the rules- although that goes a bit further since you can run a group of rules at once. 

### Solution

This is a feature request to be able to add the group field to the account editing page and then display the accounts grouped on the accounts pages, like is done on the other mentioned pages.

Nothing more- I've already got categories and budgets and tags on the transactions.

**Comment by JC5** [comment]
[It's already on my list to extend it to everything 👍🏻 ](https://github.com/firefly-iii/firefly-iii/issues/5753)
