### ISSUE TITLE
Recurring withdrawal, deposit and transfers

### ISSUE THREAD

**Issue by nwwy** [firefly-iii/firefly-iii#621]
After using Firefly III for a few Months now i feel the need for a recurring withdrawal and deposit feature.
Every month i have to manually enter things like Car Insurance, Domains, Reserve, Cellphone, ISP Bill and Salary.
The Amounts are always the same and never change (Expect when i get a Raise or buy a new Cellphone or so). It would be really nice if there was a checkbox when creating a new withdrawal, deposit or transfer that for example  just says "Repeat every Month/2 Weeks/Custom Range" and then every Month at the same date it just does its thing. Otherwise i reall really like Firefly III and use it for everything now. :) Thanks for this great project.! 👍

**Comment by JC5** [comment]
Thanks for the compliments! I appreciate it 👍 

Firefly III will not feature the ability to automatically create new transactions, such as monthly bills, salary deposits or transfers.

Altough I see the convenience of having these transactions created for you, that's not the point of this tool. I believe that if you are serious about changing your financial habits, you should be aware of what happens on your accounts. The money you spend and the money you earn. By entering each transaction manually, you will _feel_ what you spend.

Of course, there are shortcuts. You can import transactions from your online bank account and you can clone transactions so all the fields are pre-filled. But that's it.

**Comment by benyanke** [comment]
Is there any way you'd reconsider this? I _feel_ my mortgage every month, but it won't be changing for the forseeable future, so there's not a clear UX advantage to making users reenter...

**Comment by JC5** [comment]
Once my todo list is a lot shorter, perhaps. It really has no priority.

**Comment by benyanke** [comment]
I get that - we're all busy.

Would you be open to a PR it I can find some time to do it?

**Comment by benyanke** [comment]
And btw, thank you for the excellent tool. It is very well done.

**Comment by JC5** [comment]
Thanks for the compliments, I appreciate them!

I shall have to think about how to implement this first before I can accept PR's. It looks like it's going to be a big one and I'd rather have the idea fleshed out before I can start. I'll keep you in the loop when the time is there.

**Comment by viharm** [comment]
This appears linked to #359 & #2282 .

I am using Fiefly III v4.8.2, and it has a recurring transactions functionality, just can't get recurring deposts to work. Have added a screenshot in #359.

**Comment by viharm** [comment]
Apologies for the false alarm. As @JC5 pointed out in [his comment](https://github.com/firefly-iii/firefly-iii/issues/359#issuecomment-570930878) in #359, I forgot to set the transaction type as a deposit.
