### ISSUE TITLE
Cannot import transactions without description

### ISSUE THREAD

**Issue by JelmerBerghs** [firefly-iii/firefly-iii#6210]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When importing with firefly importer with nordigen, it fails to import transactions that dont have a description.
![image](https://user-images.githubusercontent.com/22679293/176998021-9b78afaf-972a-4d32-89c1-5b746ac42ba7.png)

### Expected behaviour

It imports trnasactions with an empty description

### Debug information

Debug information generated at 2022-07-02 13:04:45 Europe/Brussels for Firefly III Data Importer version **0.9.9**.

| Scope | Version |
| --- | --- |
| FIDI | 0.9.9 |
| Build | 141, 02-05-2022 19:53:58 CEST |
| PHP | 8.0.17 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | Europe/Brussels |
| Browser TZ | Europe/Brussels |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44 |

### Steps to reproduce

-  Open Firefly data importer
- Import with nordigen

**Comment by BerghsJelmer** [comment]
accidently checked "its me".
Its not on my end

**Comment by JC5** [comment]
Thanks, I'll check it out. If the description is empty it should replace it with something like "(no description)".

**Comment by JelmerBerghs** [comment]
> Thanks, I'll check it out. If the description is empty it should replace it with something like "(no description)".

Thanks alot for responding and checking it out.
The solution you suggest would indeed be perfect. I guess i can change it to something else myself with rules/mapping?

**Comment by JC5** [comment]
I'm afraid not, it needs the transaction to be created before it can apply rules.

**Comment by JelmerBerghs** [comment]
> I'm afraid not, it needs the transaction to be created before it can apply rules.

Oh yeah thats what i meant. After its imported/created, it goes through the rules

**Comment by JC5** [comment]
Fixed in the new data importer :+1:
