### ISSUE TITLE
Feature suggestion: Assign income to budget (I know - duplicate - please read my reasoning)

### ISSUE THREAD

**Issue by sgofferj** [firefly-iii/firefly-iii#6217]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to be able to assign incomes to budgets. I know that this has been discussed before several times but hear (read) me out.

Use case examples:
- User orders something from ebay and it never arrives. User gets refund.
- User orders something online and sends it back. User gets (partial) refund.
- User borrows something to a friend and friend pays it back.

### Solution

I see two possibilities:
1. Allow assigning incomes to budgets.
2. When using "this transaction (partially) pays for", automatically correct the budget used in the original transaction.

### What are alternatives?

1. Manually increase the respective budget by the transaction amount.
2. Don't assign any budget to the transaction in the first place.

Why I don't like those:
1. A budget is a budget is a budget. If I adjust it whenever it seems convenient, it doesn't make much sense to define it in the first place, does it?
2. That falls a little in the same category. If I e.g. define a budget for "free for spending", everything that doesn't fit in any other budget should go in there. Otherwise it's also kinda cheating the whole budget idea.

**Comment by sgofferj** [comment]
Additional use case ideas:

Rule: Income - when sender="Grandma" and description contains "<child name>" add to budget "<child name> toys"

**Comment by JC5** [comment]
Still no, sorry.
