### ISSUE TITLE
Wrong date formatting in transaction overview when using de_DE translation

### ISSUE THREAD

**Issue by xEtarusx** [firefly-iii/firefly-iii#6234]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello, I just setup a new instance of Firefly and added a transaction with two sub-transactions/splits.
When I check the overview page of that transaction the date field looks a bit weird to me as there is a "u0" in the date.. I think there is something broken with the date formatting here. 
I'm using Firefly with the de_DE translation.

"Datum: 16. Juli 2022 u0 00:00:00"
![image](https://user-images.githubusercontent.com/4696990/179359108-7548cb2a-81c1-4337-b62c-1ffc338b6052.png)

I then switched to en_US and checked it there. The date there looks correctly formatted: "July 16th, 2022, @ 00:00:00".
So I think the @-Symbol is messed up in the german (de_DE) translation.

### Expected behaviour

Valid date format like: "Datum: 16. Juli 2022, @ 00:00:00" or "Datum: 16. Juli 2022, 00:00:00"

### Debug information

Debug information generated at 2022-07-16 16:32:16 Europe/Berlin for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 196, 09-06-2022 18:30:26 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-07-01 00:00:00 |
| Session end | 2022-07-31 23:59:59 |
| Session first | 2022-07-16 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36 |

**Comment by JC5** [comment]
That particular string is translated here: https://crowdin.com/translate/firefly-iii/141/en-de?filter=basic&value=0

If you could submit a correct version, that would be great. Thanks!

**Comment by JC5** [comment]
It turned out to be an easy fix, I submitted it myself. You can still correct my attempt if necessary.
