### ISSUE TITLE
Data Importer use single Column for 2 Roles

### ISSUE THREAD

**Issue by Vilhjalmr26** [firefly-iii/firefly-iii#6241]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to be able to in the import configuration to be able to map a single column to two different roles.
In this case, I use a single column as both the description and the destination account.  Currently I have to Duplicate the column in the csv before importing, which works, but would be simpler if dual definition could be done.

### Solution

Could add an additional role box next to each column that would allow inserting an additional role drop down

### What are alternatives?

Could instead add a way within rules to get a value.  So I could add a rule to when the transaction is created with an empty description copy the dest account to the description.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4970
