### ISSUE TITLE
Firefly data importer stuck in health: starting

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#6243]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since version 0.19.3, the docker container stays in "health: starting". When I revert to 0.19.2, everything is fine.

The output of the entrypoint.sh script (docker logs) seems fine:
```
Now in entrypoint.sh for Firefly III Data Importer
Script:        1.6 (2022-02-17)
User:          'root'
Group:         'root'
Working dir:   '/var/www/html'
Build number:  149
Build date:    18-07-2022 17:55:54 CEST
Now parsing _FILE variables.
done!
Firefly III data importer v0.9.13
PHP: cli 8.1.8 Linux
Will now run Apache web server:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
[Tue Jul 19 13:27:41.566916 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Tue Jul 19 13:27:41.566966 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

This has a big impact, since I use traefik with labels, and now that is not initialized. Is there additional info I can give to help debug this? Can I find the Dockerfile somewhere?

### Expected behaviour

The docker starts correctly.

### Debug information

Can't access that

**Comment by JC5** [comment]
That's probably a bug in the base image, I can rebuild it. I'll keep you in the loop!

**Comment by JC5** [comment]
I rebuilt 0.9.13, let me know.

**Comment by JC5** [comment]
Works for me on Firefly III:develop, which uses the same base image. Keep in mind it'll take 5 minutes before the health check kicks in.

**Comment by daften** [comment]
For the old image, it was always fine after about 1 min, now it took longer, but it's working fine now. Thanks!

**Comment by muammercakir** [comment]
Hey @JC5, I have the same issue with the latest version **develop** of the image **fireflyiii/core**. It stuck in state **health: starting**.
