### ISSUE TITLE
data-importer: external url attribute is mapped incorrect

### ISSUE THREAD

**Issue by kruemelro** [firefly-iii/firefly-iii#6244]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

the external URL is defined in the import config but not imported

### Expected behaviour

The external URL should be imported

### Debug information

With Version 5.6.15 the external URL Attribute was renamed in firefly from **external_uri** to **external_url**. ([Changelog](https://github.com/firefly-iii/firefly-iii/blob/main/changelog.md#5615---2022-03-01))

The data-importer still maps this to external_uri. This is configured in ([csv.php](https://github.com/firefly-iii/data-importer/blob/main/config/csv.php#L550)).

I did a quick test and the URL is imported again after changing the value in csv.php

**Comment by JC5** [comment]
I pushed a fix to the `develop` branch, it'll be part of a new release soon :+1:
