### ISSUE TITLE
Bulk Add Replaces Tags

### ISSUE THREAD

**Issue by derekprovance** [firefly-iii/firefly-iii#6245]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When updating entries in bulk, if you set the budget, and add a new tag, the operation is a replace instead of an addition

### Expected behaviour

A tag should be added after the bulk operation completes, instead of replacing the existing tags

### Debug information

Debug information generated at 2022-07-20 23:01:39 UTC for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | (unknown), (unknown) |
| DB version | 18 (exp. 18) |
| PHP | `8.0.20` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | America/Chicago |
| App environment | production |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-07-01 00:00:00 |
| Session end | 2022-07-31 00:00:00 |
| Session first | 2014-03-07 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Select N number of entries to edit in bulk
2. Set the budget category to anything
3. Add an existing tag, and select "Add these tags"

**Comment by JC5** [comment]
Tried it on the demo site, seems to work just fine.

**Comment by derekprovance** [comment]
Hey @JC5 , confirmed that it worked on the demo site as well. Looks to be something specific with my instance then.
