### ISSUE TITLE
PiggyBank Suggested Per Month Ignores StartDate

### ISSUE THREAD

**Issue by rickdoesdev** [firefly-iii/firefly-iii#6254]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If a PiggyBank is time banded with a TargetDate and a StartDate, the Suggested Per Month calculation ignores the StartDate and calculates as if you're actively contributing money to this bucket now. So a piggy bank set to start  6 months from now and finish in 12 months from now is dividing amount by 12, not by 6 as it should do.

### Expected behaviour

If a piggy bank has a start date in the future, the suggested per month should be based on the time band of the piggy bank's lifetime, not from now til the end of the piggy bank's life time.

If a $6000 piggy bank is time banded to start 6 months from now, and its target date is set for 6 months after that, then the suggested per month should be $1000 per month, corresponding to the 6 months lifespan of the bank.

### Debug information

Debug information generated at 2022-07-22 06:14:10 UTC for Firefly III version **5.5.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.12 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 44a002cf-13c1-487a-ace0-95baef260b19 |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| System TZ |  |
| Browser TZ | Australia/Melbourne |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_AU |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2022-07-01 00:00:00 |
| Session end | 2022-07-31 23:59:59 |
| Session first | 2021-07-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_AU |
| Attempt at "en_AU.utf8" | 'en_AU.utf8' |
| Attempt at "en_AU.UTF-8" | 'en_AU.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0 |

### Steps to reproduce

1. Create a piggy bank with a target date set to 12 months from now and a value of 6000
2. Edit the piggy bank to set a start date to 6 months from now, creating a piggy bank with a lifetime of 6 month
3. Look at the piggy bank table and see suggested monthly payment reflects 6000 / 12 not 6000 / 6

### Additional info

I'm aware that I'm running a slightly older version, but the  `public function getSuggestedMonthlyAmount(PiggyBank $piggyBank): string` in PiggyBankRepository has not changed in latest main branch between my version 5.5.12 and latest 5.7.10

I've patched this functionality on my local instance and it works as I'd expect it to, and I'm happy to raise a PR against the latest 5.7.10 after I've updated,  if this would be acceptable to JC5

```
diff --git a/app/Repositories/PiggyBank/PiggyBankRepository.php b/app/Repositories/PiggyBank/PiggyBankRepository.php
index e2bc94f19..327bc1f93 100644
--- a/app/Repositories/PiggyBank/PiggyBankRepository.php
+++ b/app/Repositories/PiggyBank/PiggyBankRepository.php
@@ -336,8 +336,9 @@ class PiggyBankRepository implements PiggyBankRepositoryInterface
             return $savePerMonth;
         }
         if (null !== $piggyBank->targetdate && $repetition->currentamount < $piggyBank->targetamount) {
-            $now             = Carbon::now();
-            $diffInMonths    = $now->diffInMonths($piggyBank->targetdate, false);
+            $now             = Carbon::now(); 
+            $startDate       = null !== $piggyBank->startdate && $piggyBank->startdate->gte($now) ? $piggyBank->startdate : $now; 
+            $diffInMonths    = $startDate->floatDiffInRealMonths($piggyBank->targetdate, false);
             $remainingAmount = bcsub($piggyBank->targetamount, $repetition->currentamount);
 
             // more than 1 month to go and still need money to save:
```

(Note the usage of floatDiffInReal months, as otherwise my example above of a Jan1 - June 30 startdate and targetdate winds up being int truncated to 5 months instead of 6 months. I feel like this might actually be a bug that happens with the existing Carbon::now approach anyway, which would be solved by this patch if accepted. Example being setting up your budget for the year on Jan 1st with a target date of Jun 30, you have the same problem as you would if comparing against the startdate)

**Comment by rickdoesdev** [comment]
I could also see an argument that if the start date hasn't come up, then we should show 0 for the suggested amount to save, as we're not actively saving anything to it yet, but I personally find it useful to see how much I will need to be setting aside for that goal in the future so I can ensure I have realistic expectations of how much I'll be allocating during that period across various savings targets

**Comment by JC5** [comment]
This looks good, feel free to submit a PR. I would prefer the previous method, without the float. By rounding down the months number of months the calculation is more stable. I don't consider this a bug.

Yes the date range between 1-jan and 30-jun is technically "about 6 months" and not 5. It's the user's discretion to change the date to 1-jul to get the expected 6 months. 

Using the float would be more accurate (ie 5.9 months), but if your piggy bank is indeed active over a period of 3.5 months, the number of complete months over which you can save money is 3 months. Otherwise, it wouldn't be a monthly amount. It would be "amount to save per 0,85 month" which makes little sense and isn't intuitive.

**Comment by rickdoesdev** [comment]
Hmm now that I think about it more, I'm thinking this might need a little more UX thought.

With the change here, we now get to see what time boxed calculations should be for future planning, but the way the table displays it still feels as if this is something active and we're meant to be contributing to everything

![image](https://user-images.githubusercontent.com/4494839/180420769-725c1e1a-f4d1-4ab7-9c43-2d54dbfe9beb.png)

If we remove the value completely for things that aren't yet "started" we have a clear idea of what we're currently saving up for and what we aren't, but lose the ability to forecast upcoming plans

![image](https://user-images.githubusercontent.com/4494839/180420565-bb378b5e-2ec4-434b-adc2-d302663a0183.png)

Thoughts @JC5 ?

**Comment by rickdoesdev** [comment]
Actually my problem is solved by just using separate groups for "Active" and "Inactive" since the summary row for "active" will tell me what I need to know, so I'm happy with my PR if you are

**Comment by JC5** [comment]
Sounds good. And it's an interesting dilemma. I wrote it down for the new layout, because that's where I'm saving up things like this.
