### ISSUE TITLE
Allow mapping of Generic Credit/Debit column

### ISSUE THREAD

**Issue by Vilhjalmr26** [firefly-iii/firefly-iii#6258]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Not 100% sure if this is a bug or feature request.

When using a generic Credit/Debit Indicator Role, it currently appears to use specific, hard coded values to determine what is a debit, and everything else is credit.

I have a bank that uses Charge and Payment.  I thought it would be as simple as mapping the column values to Credit and Debit, but when "Map Data" was selected, it gave me no mapping options in the next step.

### Solution

Add the ability to map values on the generic Credit/Debit indicator role so that any value is supported.  This would also allow indicators from other languages to be handled without having to change the underlying code again.

### What are alternatives?

Alternatively, I would say the app should disable the Map Data checkbox for a Role if it does not allow Mapping, to make that limitation clear.

**Comment by JC5** [comment]
Sorry, this will not be changed. At the moment, there are like 5 options I added over the course of 10 years. So this is less work.

I'll see what I can about dynamically changing the checkbox, that's not a bad idea.

**Comment by JC5** [comment]
What's the difference between a charge and a payment? They feel synonymous.

**Comment by Vilhjalmr26** [comment]
In this case, a Payment is money into the account (Credit), and a Charge is money out of an account (Debit).  Obviously a case of poor wording on the banks end, and I wouldn't request that be added.  I just wasn't sure if not having the mapping was intended or not.  So yeah, I can definitely just add a filter on my end to modify my csv before I import.  but I think disabling checkbox for things that don't import would be good just for clarity.
