### ISSUE TITLE
Imported deposits have Source Account = (no name)

### ISSUE THREAD

**Issue by jesta030** [firefly-iii/firefly-iii#6259]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Importing my bank's CSV results in deposits with "Source Account" = "(no name)" even though withdrawals work flawlessly and the corresponding columns in the CSV are given the relevant "Opposing Account (*)" roles.

### Expected behaviour

The "Opposing Account Name" and "Opposing Account IBAN" roles should be used to identify the "Source Account" of a deposit

### Debug information

Debug information generated at 2022-07-22 18:59:25 Europe/Berlin for Firefly III version **5.7.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.10 |
| Firefly III API | 1.5.6 |
| Build | 222, 21-07-2022 17:05:02 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-07-01 00:00:00 |
| Session end | 2022-07-31 23:59:59 |
| Session first | 2022-07-04 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0 |

### Steps to reproduce

1. Upload CSV with FIDI
2. Configure FIDI
3. Convert, Import to Firefly-III
4. In Firefly-III, "Opposing Account (*)" roles are used for "Destination Account" of withdrawals but not "Source Account" of deposits.

### Additional info

**FIDI config:**

```
{
    "version": 3,
    "source": "fidi-0.9.14",
    "created_at": "2022-07-22T17:56:06+02:00",
    "date": "d.m.Y",
    "default_account": 21,
    "delimiter": "semicolon",
    "headers": true,
    "rules": false,
    "skip_form": true,
    "add_import_tag": true,
    "roles": [
        "account-name",
        "account-iban",
        "account-bic",
        "_ignore",
        "date_transaction",
        "_ignore",
        "opposing-name",
        "opposing-iban",
        "opposing-bic",
        "category-name",
        "description",
        "amount",
        "_ignore",
        "_ignore",
        "_ignore",
        "_ignore",
        "_ignore",
        "_ignore",
        "_ignore"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "duplicate_detection_method": "classic",
    "ignore_duplicate_lines": true,
    "unique_column_index": 0,
    "unique_column_type": "internal_reference",
    "flow": "file",
    "identifier": "0",
    "connection": "0",
    "ignore_spectre_categories": false,
    "map_all_data": false,
    "accounts": [],
    "date_range": "",
    "date_range_number": 30,
    "date_range_unit": "d",
    "date_not_before": "",
    "date_not_after": "",
    "nordigen_country": "",
    "nordigen_bank": "",
    "nordigen_requisitions": [],
    "nordigen_max_days": "90",
    "conversion": false,
    "ignore_duplicate_transactions": true
}
```

**CSV Sample (some columns removed):**

```
Account Name;IBAN Account;BIC Account;Bank name;Date initiated;Date transferred;Opposite Name;IBAN Opposite;BIC Opposite;Type;Description;Amount;Currency
My Account;DE97000000000000000000;GENXXXXXXXXX;My Bank;18.07.2022;18.07.2022;BANK AG;DE92000000000000000000;GENXXXXXXXX;Withdrawal;Hey yo!;-103,34;EUR
My Account;DE97000000000000000000;GENXXXXXXXXX;My Bank;14.07.2022;14.07.2022;Good Friend;DE34000000000000000000;HELXXXXXXXX;Deposit;Test data;311,52;EUR
```

| Account Name | IBAN Account | BIC Account | Bank name | Date initiated | Date transferred | Opposite Name | IBAN Opposite | BIC Opposite | Type | Description | Amount | Currency |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| My Account | DE97000000000000000000 | GENXXXXXXXXX | My Bank | 18.07.2022 | 18.07.2022 | BANK AG | DE92000000000000000000 | GENXXXXXXXX | Withdrawal | Hey yo! | -103,34 | EUR |
| My Account | DE97000000000000000000 | GENXXXXXXXXX | My Bank | 14.07.2022 | 14.07.2022 | Good Friend | DE34000000000000000000 | HELXXXXXXXX | Deposit | Test data | 311,52 | EUR |

**Comment by JC5** [comment]
Mmm, thanks for the detailed report, I'll check it out.

**Comment by JC5** [comment]
Found it. For the time being you can use the `develop` tag of the data importer, I hope to release a fix at the end of the weekend. Thanks for letting me know about the issue :+1:

**Comment by jesta030** [comment]
Wow, thanks for the quick fix! That's awesome!
