### ISSUE TITLE
Sort by clicking on pie charts

### ISSUE THREAD

**Issue by pwsoftwaredesigns** [firefly-iii/firefly-iii#6265]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

When viewing the list of transactions, you have three pie charts listed at the top of the page: Categories, Budgets, and Destination Accounts.  Would it be possible to have firefly filter by those when a section of the pie chart is clicked?

### Solution

For example, if I click on the "Restaurant" section of the "Budget" pie chart, the view should show only the transactions in the "Restaurant" budget.

### Additional context

I am using version 5.7.9

**Comment by JC5** [comment]
Hi, thanks for the suggestion!

It is a good idea, but won't be possible unfortunately. There is almost no interaction (no events) coming from those charts so I can't really respond to events (people clicking). It's been suggested in the past. 

I have it on my list for the new layout tho.
