### ISSUE TITLE
How do I take care of irregular bills?

### ISSUE THREAD

**Issue by coencoppens** [firefly-iii/firefly-iii#627]
Hi,

Is it possible to configure an irregular bill?

By irregular, I mean a bill that follows the following pattern (Dutchies might recognise it's Evides):
* January: € 20,-
* February: no bill
* March: no bill
* April: € 60,-
* May: € 20,-
* June: € 20,-
* July: € 20,-
* August: € 20,-
* September: € 20,-
* October: € 20,-
* November: € 20,-
* December: € 20,-

As you can see, the default bill is € 20,-. However, the company uses February and March to calculate a final settlement that arrives in April.

Thanks in advance for any help,
Coen

**Comment by JC5** [comment]
You'll have to accept that there are no values for February and March. I have several bills that arrive 8 and 10 times a year, and I just leave it eb.

I've been thinking about some kind of "log an exception to this bill"-thing, but it seems a lot of hassle for such a minor inconvenience.

It will become more relevant to build something to account for such irregular bills, when bills get nice reports that make such exceptions visible.

**Comment by xzaz** [comment]
I know what this is about. I'm doing what @JC5 is saying. Just ignore it.

**Comment by coencoppens** [comment]
I think ignoring it is the way to go, especially since I saw the following happening when the bill didn't get matched in a month:
![image](https://cloud.githubusercontent.com/assets/2962964/24567077/762a5bb2-165c-11e7-9b53-940946b767ce.png)

Which is perfectly workable for me since I know the reason it won't get payed.

Thanks for the responses! :-)
