### ISSUE TITLE
Wrong date parsing in box titles (transaction view) when setting "View range" to "six months". 

### ISSUE THREAD

**Issue by Moc** [firefly-iii/firefly-iii#6271]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When setting the "View range" preference to "Six months". The incorrect box titles (date reference) is shown on the transaction overview page in the box titles on the right hand side. 

See screenshot of demo website, with the box titles I refer to marked in yellow. 

![image](https://user-images.githubusercontent.com/577978/182018845-144b931c-fc38-463e-8584-500800608238.png)

### Expected behaviour

I think it should use the ` 'half_year_fns' => "'H{half}', yyyy",` format as specified in `resources/lang/en_US/config.php`. 
The two top box titles would then display something like `H1, 2022` and `H2, 2022`

(Currently it uses the ` 'half_year_js'             => 'Q YYYY',` format). 

As a sidenote, the `Three months (quarter)` View range setting works as expected. It shows the   `'quarter_fns'   => "'Q'Q, yyyy",` format, e.g. `Q1, 2022`). 

### Debug information

As the bug is also reproducible on the firefly-iii.org demo website, I suspect this debug info is not needed. Correct me if I'm wrong, obviously :) 

### Steps to reproduce

1. In `/preferences`, `Layout` tab (3rd tab), set the `View range` setting to `Six months`. 
2. Navigate to to `/transactions/withdrawal`. 
3. On the right hand side you'll see the boxes with incorrect date (quarter) reference.  It should be half a year. 

### Additional info

Discovered this related to possible locale setting issues in my environment. See https://github.com/firefly-iii/firefly-iii/issues/5983

**Comment by JC5** [comment]
I've updated the source string to be `'\QQ YYYY'`. This will trickle down to other translations and fix the issue. It looks like all languages suffered from this issue.

Unfortunately, there is no half-of-year indicator available.
