### ISSUE TITLE
Category monthly information

### ISSUE THREAD

**Issue by xzaz** [firefly-iii/firefly-iii#628]
On the category page there is a `spent` and `earned` calucation for that month. Could you subtract those two? And may be a option to show this into the diagram. 

I have a 'view' problem with the category because sometimes in my situation I give say €100,- but then I get it back the next day or week. This gives a strange outcome on the `Overview (all periods)` graph.

**Comment by JC5** [comment]
Should not be hard to add, let me see!

**Comment by JC5** [comment]
Alright the commit is there and it's live. Was it what you expected? If so, we can close this issue.

**Comment by xzaz** [comment]
I'll say; close it!
