### ISSUE TITLE
Add option to classify transfer as a bill

### ISSUE THREAD

**Issue by klejejs** [firefly-iii/firefly-iii#6283]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- Currently, as far as I can tell, only withdrawals can be classified as bills.
- When I pay my credit card bill, it resets my credit card account to the initial sum, thus it is just like a transfer, rather than an expense

### Solution

When creating a transfer, bill field option is also available

### What are alternatives?

I have noticed that I can work around this issue by creating a withdrawal to some withdrawal account and then adding a rule to first add bill to the newly created withdrawal and then convert it to transfer to my credit card account. This works, however, I feel like it is a janky solution as I can then see the transfer in bills section, but I cannot see the bill field or edit it if I try to edit the transfer transaction.

**Comment by JC5** [comment]
No, sorry. This behavior will not change. I have the same setup. Since all the individual expenses on my credit card are already linked to a bill where necessary, I consider the transfer just a chore, nothing else.
