### ISSUE TITLE
Sum of piggy banks

### ISSUE THREAD

**Issue by forcaeluz** [firefly-iii/firefly-iii#629]
When you look into the piggy banks page, where you have a list of piggy banks but also information about the account status. The sum in the account status seems to consider the first piggy bank twice. If I reorder the piggy banks, and update the page, the sum also changes, and is always 2x the first, + the sum of the rest. This also happens on the demo site.

**Comment by JC5** [comment]
Indeed! Nice find!

I've fixed this in the development version and it'll be live in the next release.

**Comment by JC5** [comment]
It's live!
