### ISSUE TITLE
Icons and manifest keeps absolute on composer install

### ISSUE THREAD

**Issue by welbert** [firefly-iii/firefly-iii#630]
After upgrade to 4.3.8 with composer,  icons and manisfest.json keeps absolute, same on demo site.

Screenshot of https://firefly-iii.nder.be/
![image](https://cloud.githubusercontent.com/assets/7155838/24833384/ebbc6d7e-1c9d-11e7-8d1c-128d734fa463.png)

**Comment by welbert** [comment]
Problem is this [merge](https://github.com/firefly-iii/firefly-iii/commit/19ff2484fd1fc5e6f2798f9c4c1441a8ef26f8b4), did not get any modified files

**Comment by JC5** [comment]
I'm not sure what went wrong but I've committed the change again.
