### ISSUE TITLE
Tracking loans

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#631]
Let's say I pay monthly for rent, but half of the money should be returned to me by another person. So I want to split my transaction between two accounts: expense one and asset (loan). Any tips how to track it in firefly?

**Comment by JC5** [comment]
Mmm, not really. Both the expense and the income can be tracked, but only could be tracked using a bill. Firefly isn't really equipped to track loans yet. It's on the todo list, but it needs fleshing out and I haven't had the time yet.

**Comment by nhaarman** [comment]
@skibbipl I'm using Splitwise for such joined expenses, and I have created a separate 'Splitwise' account for this. Whenever I pay for someone else, I create a transaction for my part to the expense account, and another transaction for the other person from my main pay account to the Splitwise account.

So for example, if I pay $200 for me and Person X to Company Y, I create two transactions:

 - $100 from my pay account to Company Y
 - $100 from my pay account to the Splitwise account.

When Person X decides to pay me back:

 - $100 from Splitwise to my pay account

**Comment by skibbipl** [comment]
That's not a bad idea, perhaps I can adapt it to my needs. Thanks for the tip.
