### ISSUE TITLE
Negative transactions on expense accounts

### ISSUE THREAD

**Issue by tomazsustar** [firefly-iii/firefly-iii#632]
I would find it useful to be able to enter negative transaction on expenses account. My wife often does clothes shopping online. And she often sends back half of the box, which gets refunded. But this not the only case when things get refunded. I this case I would naturally substract the refunded amount from the expense account. It is not a revenue account, since I did not earn money, I have just spend less...

**Comment by tomazsustar** [comment]
Or maybe another transaction type "Refund" would also do.

**Comment by JC5** [comment]
No. Expense accounts track expenses, and nothing else. Refunds come from a revenue account (with the same name) and behave accordingly.

Firefly doesn't judge. Income is income, no matter the source. We can both come to the conclusion that it's not really income, but Firefly cannot, and it must try to stay as far away as possible from such conclusions.

What Firefly _does_ need, is some kind of report page thing where you _can_ join such accounts in a single overview. Kind of like the budget, category and tag-reports. That should give you an overview of such transactions.

**Comment by tomazsustar** [comment]
I just think it must be up to the user how he wants to do his accounting, not up to the software. I think the user must be given a possibility to create a transaction from any account to any account. Maybe even to configure his own transaction and account types.

**Comment by JC5** [comment]
Yes, it's called Excel and you can do whatever you want to. 😉

**Comment by tomazsustar** [comment]
It could also be called firefly pro ;)
