### ISSUE TITLE
Reconciliation is regarded as expense in report

### ISSUE THREAD

**Issue by nhaarman** [firefly-iii/firefly-iii#6333]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When a reconciliation is made, adding an amount to an account, this amount is regarded as an expense in the Income vs. expenses report.

### Expected behaviour

The reconciliation is not an expense, so it should not show up in the report as expense.

### Debug information

Debug information generated at 2022-08-09 20:24:15 Europe/Amsterdam for Firefly III version **5.7.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.10 |
| Firefly III API | 1.5.6 |
| Build | 231, 26-07-2022 19:41:51 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-08-01 00:00:00 |
| Session end | 2022-08-31 23:59:59 |
| Session first | 2017-03-31 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36 |

### Steps to reproduce

Reproducible on the Demo site:

1. Head over to https://demo.firefly-iii.org/accounts/reconcile/1/index to start reconciling the account "Checking Account"
2. Fill in an absurdly high amount as end balance:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/3015152/183733795-05df1cb3-23d6-4a1c-8ff7-ede490b6dde2.png">

 3. Store reconciliation, creating a correction:
 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/3015152/183733909-7e36c6e5-77a9-403b-8d12-aab4ea74d0ff.png">

 4. Head over to https://demo.firefly-iii.org/reports/default/allAssetAccounts/currentYearStart/currentYearEnd, and observe a high expense amount:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/3015152/183734027-e168f4d5-67f1-466f-8d4a-668cdee0bfaf.png">

**Comment by JC5** [comment]
Aha, in the chart. Thanks, I'll pick it up 👍
