### ISSUE TITLE
Unable to import large csv

### ISSUE THREAD

**Issue by githubcdr** [firefly-iii/firefly-iii#6337]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The php memory limit does not allow large csv file imports

### Expected behaviour

working import

### Debug information

```
[Thu Aug 11 09:54:35.608243 2022] [php:error] [pid 79] [client 172.17.0.1:60754] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 350240768 bytes) in /var/www/html/storage/framework/views/twig/3e/3e60f3a44e72614df402645bbe63b34c.php on line 221, referer: http://localhost:8081/import/roles
[2022-08-11 11:54:35] production.ERROR: Allowed memory size of 536870912 bytes exhausted (tried to allocate 350240768 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 536870912 bytes exhausted (tried to allocate 350240768 bytes) at /var/www/html/storage/framework/views/twig/3e/3e60f3a44e72614df402645bbe63b34c.php:221)
[stacktrace]
```

**Comment by JC5** [comment]
The Docker container can only claim so much memory. How large is your file?

**Comment by githubcdr** [comment]
Hi,

I noticated the php memory_limit is pretty low. Running a docker container with --memory 8G triggers the same error.

**Comment by JC5** [comment]
512 is pretty low? Today I learned haha. 

I'll pick it up but in the mean time, you'll have to do some tinkering yourself to import the file. Although I generally do not recommend importing large batches in the first place.

**Comment by JC5** [comment]
Fixed, new build is live.
