### ISSUE TITLE
Data-importer: Welcome page submits form to incomplete URL

### ISSUE THREAD

**Issue by riversdev0** [firefly-iii/firefly-iii#6354]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Despite [better advice](https://github.com/firefly-iii/firefly-iii/discussions/5350), when self-hosting the FIDI tool on the same Apache virtual host as Firefly, the HTML `Form` tag `action` attribute lacks a trailing slash after the path.  I acknowledge that FIDI wasn't intended to be run on the same virtual host, nor in a sub-directory.  However, I suspect a trivial number of seconds of analysis from the author could probably enable this ability.  I was not able to locate the spot in the code myself, which is why I'm reaching out for help.

### Expected behaviour

In an ideal world, the app would be completely agnostic of its own location on the server, both with respect to the host header and the request path.  And, it turns out, the app has nearly achieved that goal (yay!).

### Debug information

Debug information is likely not relevant to this issue.  I can absolutely provide anything you might need, if you let me know what you want to see.

### Steps to reproduce

1. Install a self-hosted instance of Firefly directly on Linux with Apache, following the guidance provided [here](https://docs.firefly-iii.org/firefly-iii/installation/self_hosted/).  The app goes into `/var/www/firefly-iii`.
1. Install a self-hosted instance of the Data Importer on the same server, following the guidance provided [here](https://docs.firefly-iii.org/data-importer/install/self_hosted/).  The app goes into `/var/www/data-importer`.
1. Configure Apache with a virtual host where the `DocumentRoot` is `/var/www/firefly-iii/public`.  Add this line to the virtual host: `Alias /importer /var/www/data-importer/public`.
1. Point your web browser at the data importer.  For example, `http://firefly.hh.local/importer/`.  Be sure to use the trailing slash.
1. Observe the page successfully loads.  Click the 'Import File' button.  The page reloads exactly as it was.
![image](https://user-images.githubusercontent.com/7363202/185699933-b0ac7ec2-d7cb-4417-b144-528b9aab292e.png)
1. Open the bowser's Inspector; click the 'Network' tab.  In the web app, click the 'Import File' button again.  On the 'Network' tab, you can see that a POST was generated to '/importer'.  The response was a 301 to '/importer/'.
![image](https://user-images.githubusercontent.com/7363202/185700043-06fddc4e-7742-4944-a7a6-85a421f2a7a3.png)
1. In the browser's Inspector, click the 'Inspector' tab.  Observe the URL in the form `action`.  Edit the URL so that it includes a trailing slash.
![image](https://user-images.githubusercontent.com/7363202/185700124-68cb4b9e-1bb3-476e-83bb-90808534fbb8.png)
![image](https://user-images.githubusercontent.com/7363202/185700159-96bc9aed-77db-4b6e-b733-aa774cdca8e4.png)
1. In the web app, click the 'Import File' button again.  Observe that it proceeds to the file upload screen.
1. (Optional) Proceed with file upload, import, and verification.  It works!

### Additional info

I am happy and willing to submit a pull request to add detection logic for hosting in a sub-directory.  But, I am not able to locate the relevant code section.  I also attempted to fix this using the `.htaccess` file, but I did not have success detecting a POST and avoiding the `[R]` flag.

**Comment by JC5** [comment]
I'm not really sure what you expect me to do.

**Comment by JC5** [comment]
Thanks, I pushed a fix to the develop branch. Let me know if it works for you. 👍🏻

**Comment by riversdev0** [comment]
Yes, that solution works!  I also tested for regression using a dedicated domain name, as well as pointing the `DocumentRoot` to the folder above `public` (which doesn't have a redirect like Firefly does), and everything appears to work the same as previously or better.  Thank you so much!
