### ISSUE TITLE
API Spec: Enum update

### ISSUE THREAD

**Issue by mukundv** [firefly-iii/firefly-iii#6355]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If you add a rule with a trigger of `Notes contain..` 
<img width="715" alt="image" src="https://user-images.githubusercontent.com/8457697/185702151-38db01bb-b2eb-40e9-b403-0e2e1d078acd.png">

and call the `/api/v1/rules/{id}` api, it returns a trigger type of `notes_contains`

```
{
  "data": {
    "type": "rules",
    "id": "5",
    "attributes": {
      "created_at": "2022-08-19T22:23:51+02:00",
      "updated_at": "2022-08-19T22:23:51+02:00",
      "rule_group_id": "1",
      "rule_group_title": "First rule group",
      "title": "Notes_contains",
      "description": "",
      "order": 5,
      "active": true,
      "strict": true,
      "stop_processing": false,
      "trigger": "store-journal",
      "triggers": [
        {
          "id": "15",
          "created_at": "2022-08-19T22:23:51+02:00",
          "updated_at": "2022-08-19T22:23:51+02:00",
          "type": "notes_contains",
          "value": "something",
          "order": 1,
          "active": true,
          "stop_processing": false
        }
      ],
      "actions": [
        {
          "id": "10",
          "created_at": "2022-08-19T22:23:51+02:00",
          "updated_at": "2022-08-19T22:23:51+02:00",
          "type": "add_tag",
          "value": "sometag",
          "order": 1,
          "active": true,
          "stop_processing": false
        }
      ]
    },
    "links": {
      "0": {
        "rel": "self",
        "uri": "/rules/5"
      },
      "self": "https://demo.firefly-iii.org/api/v1/rules/5"
    }
  }
}
```
However, the enums on the api spec v1.5.6 has `notes_contain` in the `RuleTriggerKeyword.yaml`. This should be fixed so that the generators respect `notes_contains` as one of the trigger keywords. 
Happy to create PR on the API repo if required. 

### Expected behaviour

Enums should have `notes_contains` instead of `notes_contain`

### Debug information

NA

**Comment by JC5** [comment]
Thanks, feel free to submit a PR!

**Comment by JC5** [comment]
New entry is up, fixed :+1:
