### ISSUE TITLE
See future bank transactions

### ISSUE THREAD

**Issue by twitram** [firefly-iii/firefly-iii#6359]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Currently on dashboard charts future transactions created in rules are not calculated.

### Solution

Is this a function already possible?

Otherwise when this function will be available.

It is this function which prevents me from leaving Microsoft Money 2005.
I use the deadline graph a lot in money.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/#prediction-forecasting-future-gazing
