### ISSUE TITLE
Data-importer: Imported transfers are always set positive

### ISSUE THREAD

**Issue by riversdev0** [firefly-iii/firefly-iii#6377]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I use the importer to create transfers between my Asset accounts from a CSV file, the transfers always seem to be positive, even when the CSV specifies a negative amount.  There is another _issue_ related to this, which is #4071, but that issue is confusing because there is mention of the behavior being expected, and also mention of the issue being related to the layout.

### Expected behaviour

The importer should detect and respect the direction of a transfer.

### Debug information

The debug info doesn't seem relevant to this issue, but I can absolutely provide it upon request.

### Steps to reproduce

1. In Firefly, create 1 Revenue account, and 1 Expense account.  I named mine the following: `Inheritance` (revenue), and `Charity` (expense).
2. In Firefly, create 3 Asset accounts.  I named mine the following: `US Bank Checking`, `Capital One 360`, and `Capital One Money Market`.
3. Assemble a CSV that looks like the following:
```
Date,Description,Opposing Acct,Amount
2022-08-20,Getting an inheritance,Inheritance,2000
2022-08-20,Paying it back,Inheritance,-150
2022-08-20,Donating to charity,Charity,-500
2022-08-20,The charity refunding a portion,Charity,45
2022-08-20,Saving Me Some Money,Capital One 360,-212
2022-08-20,Pulling from reserves,Capital One 360,35
2022-08-20,Saving Me Some Money,Capital One Money Market,-313
2022-08-20,Pulling from reserves,Capital One Money Market,45
```
4. Import the CSV through the Data Importer, where the `Default import account` is `US Bank Checking`, and configure the `Role`s like this:
![image](https://user-images.githubusercontent.com/7363202/187035022-156110cd-039a-4790-8b51-3e2d7b21d3f5.png)
5. When your import is done, it will look like the following.  Notice that the direction of the 4 _income_ and _expenses_ is always correct, while the direction of the 4 _transfers_ is always positive.
![image](https://user-images.githubusercontent.com/7363202/187035110-aa700e3f-3854-4dda-a3fb-73f97fa30418.png)

### Additional info

While testing, I made a CSV where all the amounts were positive, but with a credit column and a debit column.  It looked like this:
```
Date,Description,Opposing Acct,Credit Amount,Debit Amount
2022-08-21,Saving Me Some Money,Capital One 360,,212
2022-08-21,Pulling from reserves,Capital One 360,35,
2022-08-21,Saving Me Some Money,Capital One Money Market,,313
2022-08-21,Pulling from reserves,Capital One Money Market,45,
2022-08-21,Getting an inheritance,Inheritance,2000,
2022-08-21,Paying it back,Inheritance,,150
2022-08-21,Donating to charity,Charity,,500
2022-08-21,The charity refunding a portion,Charity,45,
```
And this:
![image](https://user-images.githubusercontent.com/7363202/187035238-a7c8eb7c-3c05-4e3d-99b3-1c4b5e4d5b6e.png)
But the results were exactly the same:
![image](https://user-images.githubusercontent.com/7363202/187035456-af66810c-1b7f-4a9e-b3ec-296baa346ebd.png)

**Comment by JC5** [comment]
I see what you mean, thanks for letting me know.

**Comment by JC5** [comment]
Found and fixed. Thanks for letting me know. I hope to push a new release after the weekend, use :develop until then.

**Comment by riversdev0** [comment]
Confirmed, your Fix resolves the issue I was seeing.  Thanks!  This issue can be closed.

I guess I'll have to learn how to perform an upgrade pretty soon!  :)

**Comment by JC5** [comment]
No problem. Let me reopen this until the new version is out, in case other people have the same issue.
