### ISSUE TITLE
Some foreign currencies not list for setting on new transactions

### ISSUE THREAD

**Issue by tmllull** [firefly-iii/firefly-iii#6379]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I've tried to activate a foreign currency (by default I use EUR, and I want to add US Dollar), but when I try to add on a new transaction, not appears in the list.

### Expected behaviour

The list of foreign currencies show all activated currencies.

### Debug information

Debug information generated at 2022-08-27 22:31:19 Europe/Madrid for Firefly III version **5.7.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.10 |
| Firefly III API | 1.5.6 |
| Build | 242, 14-08-2022 06:31:47 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Madrid |
| Browser TZ | Europe/Madrid |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | es_ES |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-08-01 00:00:00 |
| Session end | 2022-08-31 23:59:59 |
| Session first | 2022-08-01 00:00:00 |
| User ID | 1 |
| User language | es_ES |
| User locale | es_ES |
| Attempt at "es_ES.utf8" | 'es_ES.utf8' |
| Attempt at "es_ES.UTF-8" | 'es_ES.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0 |

### Steps to reproduce

Activate a new currency (US Dollar in this case).
![imagen](https://user-images.githubusercontent.com/5560652/187046876-3a030d8a-8a06-4ae0-9ac2-e4c5c11e91fd.png)

Though I activated from the currencies options, when I try to add on a new transaction, not appears in the list.
![imagen](https://user-images.githubusercontent.com/5560652/187046889-d0c011ac-2abe-4dab-bee4-b219841a936c.png)

I tried to add another currency, just to check it (I added British Pound), and this currency appears on the list.
![imagen](https://user-images.githubusercontent.com/5560652/187046898-1e4f2f56-6dca-4e50-8796-8037533ce88e.png)

So, my question is if there is any other configuration I missed, or it's a problem with this feature.

Thanks a lot for!

### Additional info

I want to congratulate to you for this amazing application. I found it a few days ago, and I'm impressed.

**Comment by JC5** [comment]
I see that the currency page has some issues, so that it may not always reflect the current state. Be sure to refresh the page properly. I see no issues with the dropdown myself.

**Comment by tmllull** [comment]
Hi @JC5, I tried with another browser and cant see the US Dollar currency. I tried too to activate more than one currency and appears all but not US, and another check I've done was change my language to English, but without success. I've no idea what can causing this issue...

**Comment by JC5** [comment]
Try this to debug the issue.

- Go to the page to create a new withdrawal, and open your console (usually ctrl-shift-i).
- Go to the "Network" tab. 
- Refresh the page, press F5

In the list of files, there should be one marked "currencies". Click it, and see if you can find the Response. Copy/paste it here.

**Comment by tmllull** [comment]
Hi again @JC5, here is the response (I've modified the URL from my instance):

`{
  "data": [
    {
      "type": "currencies",
      "id": "13",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-08-22T22:41:23+02:00",
        "default": false,
        "enabled": false,
        "name": "Australian dollar",
        "code": "AUD",
        "symbol": "A$",
        "decimal_places": 2
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/13"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/13"
      }
    },
    {
      "type": "currencies",
      "id": "23",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-08-22T22:41:23+02:00",
        "default": false,
        "enabled": false,
        "name": "Bitcoin cash",
        "code": "BCH",
        "symbol": "\\u20bfC",
        "decimal_places": 8
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/23"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/23"
      }
    },
    {
      "type": "currencies",
      "id": "9",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-08-22T22:41:23+02:00",
        "default": false,
        "enabled": false,
        "name": "Brazilian real",
        "code": "BRL",
        "symbol": "R$",
        "decimal_places": 2
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/9"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/9"
      }
    },
    {
      "type": "currencies",
      "id": "10",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-08-22T22:41:23+02:00",
        "default": false,
        "enabled": false,
        "name": "Canadian dollar",
        "code": "CAD",
        "symbol": "C$",
        "decimal_places": 2
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/10"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/10"
      }
    },
    {
      "type": "currencies",
      "id": "26",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-08-22T22:41:23+02:00",
        "default": false,
        "enabled": false,
        "name": "Swiss franc",
        "code": "CHF",
        "symbol": "CHF",
        "decimal_places": 2
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/26"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/26"
      }
    },
    {
      "type": "currencies",
      "id": "7",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-09-06T16:59:30+02:00",
        "default": false,
        "enabled": false,
        "name": "Dansk krone",
        "code": "DKK",
        "symbol": "kr.",
        "decimal_places": 2
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/7"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/7"
      }
    },
    {
      "type": "currencies",
      "id": "15",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-09-06T16:59:33+02:00",
        "default": false,
        "enabled": false,
        "name": "Egyptian pound",
        "code": "EGP",
        "symbol": "E\\u00a3",
        "decimal_places": 2
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/15"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/15"
      }
    },
    {
      "type": "currencies",
      "id": "24",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-08-22T22:41:23+02:00",
        "default": false,
        "enabled": false,
        "name": "Ethereum",
        "code": "ETH",
        "symbol": "\\u039e",
        "decimal_places": 12
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/24"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/24"
      }
    },
    {
      "type": "currencies",
      "id": "1",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-08-23T12:26:47+02:00",
        "default": true,
        "enabled": true,
        "name": "Euro",
        "code": "EUR",
        "symbol": "\\u20ac",
        "decimal_places": 2
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/1"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/1"
      }
    },
    {
      "type": "currencies",
      "id": "3",
      "attributes": {
        "created_at": "2022-08-22T22:41:23+02:00",
        "updated_at": "2022-09-06T16:59:49+02:00",
        "default": false,
        "enabled": false,
        "name": "British Pound",
        "code": "GBP",
        "symbol": "\\u00a3",
        "decimal_places": 2
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "\\/currencies\\/3"
        },
        "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies\\/3"
      }
    }
  ],
  "meta": {
    "pagination": {
      "total": 27,
      "count": 10,
      "per_page": 10,
      "current_page": 1,
      "total_pages": 3
    }
  },
  "links": {
    "self": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies?&page=1",
    "first": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies?&page=1",
    "next": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies?&page=2",
    "last": "https:\\/\\/firefly.mydomain.com\\/api\\/v1\\/currencies?&page=3"
  }
}`

Thanks for your time!

**Comment by JC5** [comment]
I know what the issue is, but I haven't fixed it in this release. To fix it temporarily, delete (not just disable) any currency you're not using. Try to keep at most 10 currencies in your system. That should fix it.

**Comment by tmllull** [comment]
Hi! Thanks for your suggestion, that solved the problem!

![imagen](https://user-images.githubusercontent.com/5560652/189093888-46d5f924-6a65-44b9-9998-c92b6dc27482.png)

When a saw the logs I suppose that the problem was in this "only" 10 elems.

Thanks again for your help, and I want to congratz to you for your job, You're doing an amazing app!
