### ISSUE TITLE
Startpage deformed

### ISSUE THREAD

**Issue by worldworm** [firefly-iii/firefly-iii#638]
Hi there.
I updated a few days ago to 4.4.0. After the update i noticed that the whole startpage is deformed. The section "Budgets and spending" and "Bills" and "Categories" was too big that for example my Budgets and spending with over 3500€ has a size that 500€ on the x graph fit on one site and you need to scroll down a lot. This problem was also visible on your demo site. Now i updated to 4.4.2 and there is the same problem. But on your demo site everything is now perfect
![bildschirmfoto am 2017-05-01 um 20 54 09](https://cloud.githubusercontent.com/assets/13227454/25590486/0c8b06bc-2eb1-11e7-8e92-f0d78e49e542.png)

Hope you can help.
Thanks :)

**Comment by worldworm** [comment]
Ok a few other test
btw the screenshot above was taken in firefox

here a few test from internetexplorer

here a screen from my site
![1](https://cloud.githubusercontent.com/assets/13227454/25590823/42aadd16-2eb2-11e7-986d-4606a58ba365.PNG)

and from your demo
![2](https://cloud.githubusercontent.com/assets/13227454/25590830/48e26ff0-2eb2-11e7-9acb-39fa8d0543c6.PNG)

I think here in ie my site looks a bit better, for example the whole bills section is a lot smaler than in firefox

**Comment by JC5** [comment]
Yes, I've noticed the same issue. It has to do with an update to the chart library. The demo site has been fixed already. I'll push an update today!

**Comment by JC5** [comment]
I'm struggling with some translation issues but the new release should be live soon.
