### ISSUE TITLE
New version banner conflicts with new transaction message

### ISSUE THREAD

**Issue by elliot-gh** [firefly-iii/firefly-iii#6381]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm on Firefly III 5.7.9 (docker) on the old UI, and when creating a new transaction it redirected me to the dashboard with a success banner mentioning a new update is available. However the banner link goes to the new transaction, instead of linking to a new update patch notes.

### Expected behaviour

I'm not quite sure if this is intended behavior, but what I expect to happen is that the banner should either show the standard transaction created message, or link to the new version notes, or perhaps show both banners. (I'm seeing on /admin/update-check that the new version banner doesn't have a link at all, so it might be ideal to make it link to the GitHub release?)

### Debug information

Debug information generated at 2022-08-28 15:17:26 America/Los_Angeles for Firefly III version **5.7.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.9 |
| Firefly III API | 1.5.6 |
| Build | 193, 01-06-2022 06:18:57 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Los_Angeles |
| Browser TZ | America/Los_Angeles |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `172.28.0.1` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-08-01 00:00:00 |
| Session end | 2022-08-31 23:59:59 |
| Session first | 2020-08-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Use Firefly III on version older than current, such that a new version is available. 
2. Successfully create new transaction and get redirected to dashboard.
3. Banner shows new version message, but links to the new transaction instead.

### Additional info

The screenshot below shows the URL in the banner when hovering over it.
![image](https://user-images.githubusercontent.com/5415760/187096834-c1b691c1-c785-4483-a94c-bc490d79d47b.png)

**Comment by JC5** [comment]
Haha nice. Thanks for letting me know. A happy coincidence I'm not going to do anything about, I think.
