### ISSUE TITLE
Weird translation in sidebar when using 6 months time ranges

### ISSUE THREAD

**Issue by timaschew** [firefly-iii/firefly-iii#6396]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Usually I see there the current month or year or Q1, Q2, Q3, Q4 (for a 3 month range), but for a 6 month range it shows me this string: `4upmrtpm3`

<img width="219" alt="Screenshot 2022-08-31 at 22 18 44" src="https://user-images.githubusercontent.com/110870/187775117-e755f798-82d3-4099-ad21-45c230fab361.png">

I guess the translation placeholders are broken or something like that.

### Expected behaviour

In German it would be something like:

- `Erstes Halbjahr`
- `Zweites Halbjahr`

### Debug information

Debug information generated at 2022-08-31 22:25:52 Europe/Berlin for Firefly III version **5.7.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.10 |
| Firefly III API | 1.5.6 |
| Build | 242, 14-08-2022 06:31:47 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-07-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2021-08-24 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0 |

### Steps to reproduce

1. Switch language to German
2. Go to `/preferences` and choose 6 month time range
3. Go to `/transactions/withdrawal/` and check the right sidebar

### Additional info

I didn't find that string on crowdin.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6271
