### ISSUE TITLE
Ignore garbage at the beginning of CSV

### ISSUE THREAD

**Issue by Zirafarafa** [firefly-iii/firefly-iii#6404]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

As in #2735, I have a CSV with additional information at the start of the file.  For this particular bank export, it always has a fixed number of lines before the csv header fields.

Would you consider adding an additional CSV data import option to ignore a configurable number of starting lines?

### Solution

This would allow additional csv files to be directly imported without having to preprocess them

### What are alternatives?

Users have to manually preprocess these files, which adds to import burden.

### Additional context

My header looks like:

```
Created on 02.09.2022 12:31:57 CEST,,,,
Bookings,,,,
Account,"Private account,XX11 1234 1234 1234 1234 0,Account Holder",,,
Balance,"10.00 CHF",,,
Booking Entries from 03.08.2022 - 02.09.2022 ,,,,
Booking Date,Text,Debit,Credit,Balance
```

**Comment by JC5** [comment]
This is already on the list somewhere, let me look it up at a later moment. 👍

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5789
