### ISSUE TITLE
DB tabel 'role_user' is not populated when signing in using remote_user_guard

### ISSUE THREAD

**Issue by brujoand** [firefly-iii/firefly-iii#6408]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When the first user logges into FFIII using remote_user_guard they are not assigned the 'owner' role as described in the documentation: https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/security/

### Expected behaviour

The first user to sign in should be granted the role 'owner'

### Debug information

Debug information generated at 2022-09-04 08:38:10 Europe/Oslo for Firefly III version **5.6.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.14 |
| Firefly III API | 1.5.5 |
| Build | 96, 05-02-2022 10:01:49 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 50c6fa62-d669-4951-9cac-e3e05f0d2ada |
| Using docker? | true |
| Layout | v1 |
| System TZ | Europe/Oslo |
| Browser TZ | Europe/Oslo |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-09-01 00:00:00 |
| Session end | 2022-09-30 23:59:59 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15 |

### Steps to reproduce

1. Create a custom property mapping in Authentik and create a proxy for FFIII using the property mapping.
2. Configure FFIII to use the remote_user_guard and the header provided by Authentik for `AUTHENTICATION_GUARD_HEADER`
3. Login to FFIII through the Authentik proxy

### Additional info

The Authentik property_mapping:
```json
return {
    "ak_proxy": {
        "user_attributes": {
            "additionalHeaders": {
                "X-AUTH-USER": request.user.email
            }
        }
    }
}
```

I've verified that the the user id is propagated and FFIII allows me to login as "me@mydomain.com"

| id |     created_at      |     updated_at      |        email        |                           password                           | remember_token | reset | blocked | blocked_code | objectguid | mfa_secret | domain | user_group_id |
|----|---------------------|---------------------|---------------------|--------------------------------------------------------------|----------------|-------|---------|--------------|------------|------------|--------|---------------|
|  1 | 2022-09-03 22:53:24 | 2022-09-03 22:53:24 | me@mydomain.com | <random_string> |                |       |       0 |              |            |            |        | |

The `role_user' table however is empty. By adding my user to the 'role_user' table by referencing the owner role the problem is solved.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6150
