### ISSUE TITLE
A bill past its end date is still accounted for

### ISSUE THREAD

**Issue by NathanPERIER** [firefly-iii/firefly-iii#6409]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If you set an end date for a repeating bill, and then select a time frame that is past that end date, the value of the bill is still accounted for in the total of bills to pay during the time frame. It is also the case if we select a time frame that is before the initial date of the bill.

I have verified this on the demo instance and on my personal instance.

### Expected behaviour

The bill should probably be counted as inactive when the selected time frame is before the initial date or after the end date. In that case, the value should not be added to the total of bills to pay during that time frame.

I am not sure how the extension date should be taken into account however.

### Debug information

Debug information generated at 2022-09-04 14:21:53 UTC for Firefly III version **5.7.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.10 |
| Firefly III API | 1.5.6 |
| Build | 242, 14-08-2022 06:31:47 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-09-01 00:00:00 |
| Session end | 2022-09-30 23:59:59 |
| Session first | 2021-06-01 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0 |

### Steps to reproduce

1. Create a monthly-repeating bill with an end date (e.g. 2nd of August).
2. Select a time frame that starts during the month that is after the month of the end date (e.g. 1st of September - 30th of September). That bill is still accounted for.
3. Then, select a time period that ends before the initial date of that bill. The bill is also accounted for.

### Additional info

I am not 100% sure that this is a bug, it is possible that these dates are not intended to influence the total amount of bills to pay during a time period, but I couldn't find any clear statement for this. I apologize in advance if that is an intended behaviour.

Also, I have been using FireflyIII for more than a year and it has been very helpful. If this is indeed a bug and we reach a common agreement on when bills should be accounted for (depending on the initial date, the end date and the extension date), I would be interested in contributing to the project by fixing the issue.

**Comment by JC5** [comment]
Thanks for the compliments!

The end date is a brand new field, and I'm not yet sure what to do. Since bills can also be activated by the user (and deactivated) I'm inclined not to respond to the end date. If the user wants to deactivate the bill, the "active" field seems the logical place. The end date is just a reminder.
