### ISSUE TITLE
Command Line importer:import not respecting date_range

### ISSUE THREAD

**Issue by EorlBruder** [firefly-iii/firefly-iii#6412]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I import on the command line (importer:import) with `date_range` set to `partial` and the `date_range_number` set to e.g. `1` (with `date_range_unit` as `d`), this get's ignored by the importer, which then imports everything.

### Expected behaviour

I'd expect the importer to only import things from the last day.

### Debug information

Debug information generated at 2022-09-05 14:45:17 Europe/Berlin for Firefly III Data Importer version **0.9.15**.

| Scope | Version |
| --- | --- |
| FIDI | 0.9.15 |
| Build | 166, 14-08-2022 15:47:03 CEST |
| PHP | 8.1.9 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0 |

### Steps to reproduce

1. Create an `import.json`. In there have these three lines:
```
date_range: "partial",
date_range_number: 1,
date_range_unit: "d",
```
2. Run an import via the command line. In my case I'm using `docker-compose run --rm --entrypoint php fidi artisan importer:import /import-configs/import.json`
3. The importer will import anything it gets

### Additional info

I've looked at issue #5980 and think this has a similar cause. Looking at the debug logs, I can't find any log messages like your mentioned: 

```
[2022-04-09 21:01:04] production.DEBUG: Range is partial, after is NULL, dateNotBefore will be calculated.
[2022-04-09 21:01:04] production.DEBUG: dateNotBefore is now "2022-04-06"
```

Furthermore, looking at the fix in https://github.com/firefly-iii/data-importer/commit/497ec7fe990af1689c490a02e1527c2caeb25770 I think this never was applied to the importer.

I think, if this was added to the import-command, everything should work as expected: https://github.com/firefly-iii/data-importer/blob/main/app/Console/Commands/Import.php 

Unfortunately, due to unrelated issues with auth I'm not getting the command run in a docker-compose-exec environment, where I could test my theory. 

As a workaround for now I'm setting `date_not_before` to a sensible value, so the import doesn't try importing everything from the last 90 days, but only the month of September - though I'd prefer having less manual intervention and attempts to import duplicates.

**Comment by JC5** [comment]
Ah, nice find. I'll see if I can replicate it and get back to you! :+1:

**Comment by JC5** [comment]
Could you see if this works for you on the `:develop` tag?

**Comment by EorlBruder** [comment]
For me nothing has changed, but I have a feeling your change hasn't applied in the docker-image. 

First I tried running it in my setup with the develop tag, with unchanged result. I then looked into the container and saw that nothing has changed in the Import.php (so the line added in f9b6d28  isn't there). To make sure it's not some weird cache issue, I pulled the image on a new machine and there also couldn't find the changes. As in dockerhub the image is marked as last built 14h ago.

**Comment by JC5** [comment]
That's weird, the build ran successfully.

https://dev.azure.com/Firefly-III/ImportToolImage/_build/results?buildId=996&view=logs&j=841706e3-baec-53ae-61de-0aa49ced9bf4&t=eaa42b2f-81c7-5787-5300-f90c25c9e2c7&l=1000

Oh well, I'll check it out later.

**Comment by EorlBruder** [comment]
After the newest build ran through, it now worked.

With the new image everything works as expected. Thanks for the quick fix!
