### ISSUE TITLE
Add template placeholders to recurring transactions

### ISSUE THREAD

**Issue by bastantoine** [firefly-iii/firefly-iii#6414]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello!

Like many people using Firefly (I think 😅), I'm using the recurring transactions feature. I use it mainly to track monthly transactions, like rent, public transportation card, energy...
The problem that I'm facing is that every transaction created by the reccuring rule have the exact same infomations (except for the date) : same amount, same description, same notes... so it may be a bit difficult to quickly see for which month a given transaction applies to.

### Solution

I propose to add some kind of placeholder feature to the transaction description, so that a part of the description can be dynamically filled, based on the context the transaction is created in.

This could allow for example to fill the name of the current month, the current year, or even the current day (though I couldn't find any real use case for the last one). There could also be other placeholders, but I couldn't find any use case either.

For example, the reccuring transaction defined with description `Rent %{month} %{year}` would generate the following transactions:
- `Rent July 2022`
- `Rent August 2022`
- `Rent September 2022`
- ...

**Proposed placeholders**
- `year`: the current year in long form (ex: 2022)
- `year:short`: the last two digits of the year (ex: 22)
- `previous-year`: the last year in long form (ex: 2021)
- `previous-year:short`: the last two digits of the last year (ex: 21)
- `month`: the name of the current month (ex: September)
- `month:short`: the two-digits value of the month (ex: 09)
- `previous-month`: the name of the previous month (ex: August)
- `previous-month:short`: the two-digits value of the previous month (ex: 08)
- `day`: the two-digits value of the current day (ex: 06)

The month names should be translated in the user language.

### What are alternatives?

I could manually edit the transactions each month, but this kinda defeat the purpose of the recurring transactions.

**Comment by JC5** [comment]
Sorry, no, I'm not going to add this. I like the idea but it's a lot of effort for a very small improvement. Plus,

> so it may be a bit difficult to quickly see for which month a given transaction applies to.

Transactions have a date that's visible in practically every view.

**Comment by bastantoine** [comment]
Understood, thanks for the quick reply.

> Transactions have a date that's visible in practically every view.

Yes I know, but sometimes the transaction is added on the month N to cover the bill of the month N-1, or even sometimes at the end of the month N for the month N-1, so I wanted this feature to help me understand the transactions quickly.

I'll figure out an other way (or even if I really need this 😅).
