### ISSUE TITLE
Reccuring payment templates

### ISSUE THREAD

**Issue by ClementNerma** [firefly-iii/firefly-iii#6429]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hi there!

I've been using Firefly for a bit more than a year and a half and been enjoying it a lot! Everything's working great and I find it very intuitive to work with.

I have a feature request though, that would help me gain quite some time. I'm surprised it hasn't already been suggested but as I can't find any information on this subject in the issues, I'll open up a new one here.

I'd like to have a feature when I can create a 'template' for a specific expansive or income, which I could then trigger once in a while. For instance, I have subscriptions that I don't pay the exact same day each month, so I can't set up a reccuring payment with a fixed date.

### Solution

An idea could be to simply have the same form as traditional expanses and incomes (without the "date" field of course), save the template from these date, and then be able to select a template when creating an expanse or income. The form would then filled with the template's data, with today's date.

Would that be possible? I think it could be really helpful for some people (I personnally have to manage a dozen of reccuring payments each month).

Thanks in advance for your answers!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4917

See this topic :+1:
