### ISSUE TITLE
Rules > new "Description matches regex" trigger

### ISSUE THREAD

**Issue by tomaskir** [firefly-iii/firefly-iii#6432]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

In Rules, the current `Description ...` triggers are not flexible enough, and require many duplicate rules to be created in case the description is the only difference.

A single new trigger `Description matches regex` would help a lot to cut down on duplicate rules.

### Solution

Add a new trigger `Description matches regex`

### What are alternatives?

This has been discussed in #1281 as a general regex support, but this request is not that complex. The Strict vs. Non-strict mode (#1338) is not a good solution, since it's global to all rules.

### Additional context

This small trigger addition would allow me to cut down the number of rules I have by about a half. Since it's just a single new trigger among many others already existing, I don't think it violates any principles of Firefly.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/#more-complicated-rules-like-and-or-or-copypasting-values-etc

**Comment by tomaskir** [comment]
> https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/#more-complicated-rules-like-and-or-or-copypasting-values-etc

With all due respect - I don't think this applies to a request for a new trigger. This is not a request to add complicated logic or to change how Rules work in Firefly. This is a request for a single new trigger.

> For Firefly III, the current features of the engine will not be expanded. If you have a suggestion, please consider that your suggested trigger or action is simple.

Considering there are already triggers like `Description starts with` and `Description ends with`, I think a `Description matches regex` trigger is within the Firefly philosophy on how Rules work.

**Comment by JC5** [comment]
Sorry, it's not going to happen.

**Comment by ohare93** [comment]
> The rule engine could be a lot more complex. Things like conditional rules, if-then-else, regular expressions or variables. These are all technically possible. **However, the rule engine must also be usable and easy to be introduced to.** Most rule engines, even the filters in GMail, are very complex because of user demands and as a result, nobody uses them any more.

This explanation is incredibly strange and unsatisfying while also suggesting users are dumb.

Adding in an extra filter or an action built on Regex would add no complexity to new users. It would simply be one more option in a dropdown that they'd never use. _If you really believe it would add some extra complexity and/or make people use the tools less then there are ways to fix that issue without throwing the baby out with the bathwater._ Hide these extra filters/actions by default, and add a checkbox for "Advanced Rules" either under Administration / Profile or in a config value for running the application which will enable their use. Boom, now there is no issue for new users. Is there an issue remaining with this approach?

**Comment by ohare93** [comment]
![image](https://user-images.githubusercontent.com/1471350/195841975-c6e74583-d25a-4989-afe8-a461d11cc5d1.png)

I can imagine a pain point about adding this feature may:

> But then there would need to be an extra 'X matches Regex' for each existing option!

So here's an even simpler (and new user friendly) option to add this feature: simply include this feature inside the 'X contains...' option. If one populates the "Trigger on Value" field with 'test' then the normal existing matching rules would apply. To change it to a Regex match you simply write '/test/' (standard regex syntax) and it would be a regex match. No extra options needed, no hidden functionality, and no overly complex usage for new people. Hidden feature can just be mentioned in the docs.

**Comment by JC5** [comment]
Thanks man, I appreciate the feedback. But, alas, what you see is what you get.

**Comment by ohare93** [comment]
What I see if needlessly simple and your reasons for not improving it (yourself or via a PR from someone else) are incredibly lacking. My suggestions are ways to counter the UX problems you stated in the linked docs as the reasons for not implementing this feature. Why not accept such a feature if those issues are fixed? Or do you not believe they are/would be?

(I'm not asking for an online essay to win this silly internet debate - it is just that a simple "no" with no reason is extremely unsatisfying)
