### ISSUE TITLE
Data loss on Redeployment on Kubernetes via helm chart

### ISSUE THREAD

**Issue by koeberlue** [firefly-iii/firefly-iii#6435]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Given a deployment via the helm chart, whenever the database pod restarts, all data is lost.

### Expected behaviour

All data should be restored whenever the pod is restarted.

### Debug information

| Name | Version |
| -- | -- |
firefly-iii-stack | 0.7.0
firefly-db | 0.1.0
firefly-iii | 1.3.3
importer | 1.3.0

Installed with:
```
helm install --no-hooks
```

### Steps to reproduce

1. Deploy firefly-iii using the helm chart
   1. I needed to disable hooks and the cronjob because I do not have a server for backups available
1. Delete the pod running the postgresdb
   1. It will automatically be recreated by kubernetes 
1.  Open your firefly-iii instance to see that all data is erased

### Additional info

If I understand correctly, the helm hooks and the backup cron job are used to circumvent this specific bug.

This seems to be a known issue with postgres running on kubernetes: https://github.com/docker-library/postgres/issues/696

For debugging I manually changed the deployment definition on my local cluster and got it working by applying these changes:

`firefly-db-deploy.yml` (I only included the changes necessary):

```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: {{ template "firefly-db.fullname" . }}
        env:
          - name: PGDATA
            value: /firefly-iii/data
        volumeMounts:
          - name: db-storage
            mountPath: /firefly-iii
            # Note: no subPath is set. I'm not sure if it is needed
`

This might be a breaking change though, because I had to manually delete the existing volume claim. Renaming the volume claim might be a reasonable solution for this

**Comment by JC5** [comment]
Thanks for letting me know. I appreciate the work-around but this is a breaking change I'm not really comfortable making.

> the backup cron job are used to circumvent this specific bug.

Why didn't this work for you?

**Comment by koeberlue** [comment]
Personally I did not have any server running where I could upload the backup to. I just wanted to play around with the helm chart a little bit and if I'm not mistaken I would have to setup some kind of nginx deployment just for these backups.

But I also think that the current backup mechanism could be a little bit problematic. The reason I stumbles across this bug was me getting some CPU reosurce problems on my cluster. So kubernetes decided to kill (amingst others) the postgresql pod. After the resource problems settled down, the postgres pod restarted itself. But, as far as I can see, there is no mechanism to restore the backup in such a situation. You van test it by manually deleting the postgres pod and waiting for it to reboot. 

Even worse: if the postrges pod restarts, the next backup cron job would then override the existing backup with an empty dump removing all data forever.

Thinking about my proposed change: I think if the volume claim would be renamed as part of the next release, it should even be a non-breaking change. The upgrade hook would restore the backup as before and helm would remove the old volume claim. So as a user I shouldn't even notice any difference.

**Comment by JC5** [comment]
That's a lot of maybe's. I'll ask around.

**Comment by JC5** [comment]
@morremeyer, could you read along?

**Comment by morremeyer** [comment]
I'll take a look sometime next week.

**Comment by koeberlue** [comment]
> That's a lot of maybe's. I'll ask around.

That's a good point. So I created a small script to verify that this bug indeed exists. It will do the following:

1. Start minikube
2. Create a backup server
3. Install firefly-iii
4. Prompt you for creating a user
5. Delete the postrges pod
6. Prompt you for verifying that the user does not exist any more

If anyone is interested in reproducing, here is the script:

(Prerequisites: `minikube`, `helm`, `kubectl`)

```
#!/bin/sh

minikube start

# setup simple backup server
helm repo add http-folder https://aureliengasser.github.io/charts
helm repo update
helm install --namespace firefly-iii --create-namespace --wait my-http-folder http-folder/http-folder

# install firefly-iii
helm repo add firefly-iii https://firefly-iii.github.io/kubernetes
helm repo update
helm install --wait --wait-for-jobs \
  --namespace firefly-iii --create-namespace \
  --set firefly-db.configs.BACKUP_URL=my-httpserver \
  --set firefly-db.configs.RESTORE_URL=my-httpserver \
  --set firefly-db.configs.DB_HOST=firefly-iii-firefly-db \
  --set firefly-db.storage.class=standard \
  --set firefly-iii.config.env.APP_KEY=mWt6CSw8O3EgA1FN0isf2hrhj7DxvfaP \
  --set firefly-iii.config.env.DB_HOST=firefly-iii-firefly-db \
  --set firefly-iii.service.type=NodePort \
  --set importer.enabled=false \
  firefly-iii firefly-iii/firefly-iii-stack

# Create a new user
printf "\n\n"
printf "Go to this url and create a new user: "
minikube service firefly-iii --url --namespace firefly-iii

# Force a recreation of the database pod by deleting it
printf "%s " "After you created a user, press enter to continue..."
read -r ans

# Note: Spontaneous deletion of running pods is kind of normal on kubernets. See https://12factor.net/disposability
kubectl delete pod -l pod-label=firefly-iii-firefly-db-pod --namespace firefly-iii

# Verify that the user is gone
printf "\n\n"
printf "Go to this url again and verify that the user is gone now: "
minikube service firefly-iii --url --namespace firefly-iii
printf "Note: you might have to refresh the site until it is reachable\n"
```

**Comment by koeberlue** [comment]
I tried to change the helm chart to prevent this from happening and created https://github.com/firefly-iii/kubernetes/pull/48. It fixed the bug successfully in my environment. It was also a non breaking change.

**Comment by morremeyer** [comment]
I haven't gotten around to analyze this in detail yet, but I'm confused as to why data would be deleted by restarting the database pod.

For this to happen, the pod would need to delete the data somehow - which apparently happened in earlier versions of the image but seems to be fixed now?

As a note, we're still planning to replace the database chart with the bitnami one to reduce maintenance here, so I'm not too inclined to debug the helm hook too much - automatically restoring the database like this is an antipattern in my personal and professional opinion.

**Comment by JC5** [comment]
Thanks again for checking this out, @morremeyer. It sounds as if the PR and issue can be closed.

**Comment by koeberlue** [comment]
Thanks for looking into this. Unfortunately the postgres image still has this issue when you mount data to `/var/lib/postgresql/data`: https://github.com/docker-library/postgres/issues/404

> we're still planning to replace the database chart with the bitnami one

That's great to hear. Looking forward to this.

> automatically restoring the database like this is an antipattern in my personal and professional opinion

I agree with you. I assume the hooks were added to circumvent _this_ very issue in the first place.

So in case anyone is stumbling on this issue and until the bitnami dabasase chart is implemented, I would suggest looking into this PR to keep your data safe in the meantime: https://github.com/firefly-iii/kubernetes/pull/48/
