### ISSUE TITLE
Layout broken on small screens when the month name is too long

### ISSUE THREAD

**Issue by bastantoine** [firefly-iii/firefly-iii#6436]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I visit an instance of Firefly on my smartphone (iPhone 11), the text of the date range shown on the header breaks the layout because the name of the month is too long 😅.

Because a picture is worth a thousands words, you can find two screenshots of the problem below. Note that the problem occurs at least for French, English (the only languages shown below).

![IMG_0025](https://user-images.githubusercontent.com/8548006/190659419-0c93bd2d-d476-48ed-9e31-4b0e33cb4d68.jpeg)

![IMG_0027](https://user-images.githubusercontent.com/8548006/190659423-819438e8-e900-4eb7-b37c-87633e36ed51.jpeg)

### Expected behaviour

Well a layout not broken 😇.

### Debug information

Debug information generated at 2022-09-16 16:25:21 Europe/Paris for Firefly III version **5.7.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.1 |
| Firefly III API | 1.5.6 |
| Build | 153, 04-04-2022 05:56:25 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Paris |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | fr_FR |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-09-01 00:00:00 |
| Session end | 2022-09-30 00:00:00 |
| Session first | 2021-12-27 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15 |

### Steps to reproduce

Simply change the language to French or English, and visit it on a device with a narrow screen.

I've tested on Chrome, this breaks with a width under 380px with French and English.

**Comment by JC5** [comment]
Thanks for letting me know. I'm not going to fix this. I'm working on a new layout and this is not really breaking anything.

**Comment by bastantoine** [comment]
> this is not really breaking anything

On narrow screens, this prevents seeing, and thus using, the search bar in the side menu, so I'd say that this does break something, as this prevents from properly using all the features.
