### ISSUE TITLE
Add WebAuthn (Fido2) support

### ISSUE THREAD

**Issue by SteffoSpieler** [firefly-iii/firefly-iii#6437]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like Firefly III to support a security key as an second factor.
Firefly already supports TOTP-two-factor-auth, so why not also adding security keys?

### Solution

Make it possible to add, name and remove (mutliple) security keys and let users login with a security key.

### Additional context

I know this feature already had two issues, but the ["project" link you added in those comments](https://github.com/firefly-iii/firefly-iii/issues/2519#issuecomment-526569326) isn't working anymore and I haven't seen this feature in your new project view.

If you don't want this feature, then please tell us here so nobody creates another issue about this accidentally.

Either way, have a great day! :D

**Comment by JC5** [comment]
If you want to use a security key, use Authelia as an authentication proxy.
