### ISSUE TITLE
Add rule trigger "Any transaction" for creating a rule that matches any transaction without a workaround

### ISSUE THREAD

**Issue by welles** [firefly-iii/firefly-iii#6457]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I import my transactions automatically via the importer and Nordigen. Any newly created transaction is marked with an "INBOX" tag, which shows me that I have to manually review the transaction to see if its category and/or bill are set correctly. After that I remove the tag.
Currently there seems to be no way to apply a rule to "any" transaction without a workaround.

### Solution

Create a new rule trigger "Any transaction" that just acts as a general "true" in the filter. If combined with other filters (which would be nonsensical) it is ignored by virtue of "&& true" always being redundant. (I'm going out on a limb here and guessing thats how the triggers work.)

### What are alternatives?

Currently I have to use exclusive triggers in a non-strict rule, like "Has any category" and "Has no category" combined, which does the job but is just kind of ugly.
Another alternative is of course using the tags created by the importer, but I don't like that I can't set the name of that tag and that a new tag is created on each importer run.

### Additional context

Thanks for the great work on this tool!

**Comment by JC5** [comment]
Not a bad idea. I personally use "Was created after" to include everything. I'll write it down :+1:

**Comment by JC5** [comment]
5.8.0 will have this. `exists:true` or `exists:false`.
