### ISSUE TITLE
No Amount field in New Transfer (After upgrading to 4.4.3)

### ISSUE THREAD

**Issue by tpetrauskas** [firefly-iii/firefly-iii#646]
![image](https://cloud.githubusercontent.com/assets/15208933/25843180/349b0f86-34af-11e7-946c-d1b9079ed59d.png)

Amount field is not visible, but after changing it's display state from none to default and entering value - it's not working either and it creates transfer without amount.

![image](https://cloud.githubusercontent.com/assets/15208933/25843545/583dd990-34b0-11e7-9f24-f8795e8e023e.png)

This is what I had to do manualy.

**Comment by JC5** [comment]
Try a hard refresh. Ctrl F5. I'll verify what happens when the amount is empty.

**Comment by tpetrauskas** [comment]
Already tried that, also cleared both **app** and **browser** cache.

**Comment by JC5** [comment]
I'm sorry, I can't reproduce this issue, and the JS files involved haven't been changed since that release. It also should not be possible to store a transaction without an amount. Which I also cannot reproduce.

**Comment by tpetrauskas** [comment]
I found that program searches JS files using these addresses, but it cannot find it.

![222](https://cloud.githubusercontent.com/assets/15208933/25930587/bc920186-360f-11e7-9dee-553a721e0901.png)

Checked if Rewrite module is enabled, everything is alright. Also double checked that modules are installed and enabled (according to the [https://firefly-iii.github.io/using-installing.html](https://firefly-iii.github.io/using-installing.html)):
- PHP BCMath Arbitrary Precision Mathematics
- PHP Internationalization extension
- PHP MBstring
- PHP Curl
- PHP Zip

Here I compared my server with your Demo instance:

![111](https://cloud.githubusercontent.com/assets/15208933/25930586/bc794ed4-360f-11e7-987e-b45854e66a7e.png)

Visiting Dashboard:

![image](https://cloud.githubusercontent.com/assets/15208933/25930580/b1afefb2-360f-11e7-8f20-413d8eeced26.png)

**Comment by tpetrauskas** [comment]
This is what I found in logs:

[Thu May 11 06:27:06.872745 2017] [autoindex:error] [pid 11302] [client xxx.xxx.xxx.xxx:63236] AH01276: Cannot serve directory /usr/share/javascript/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive

This is default configuration of Apache/2.4.18 (Ubuntu).

![image](https://cloud.githubusercontent.com/assets/15208933/25931235/c3540ae2-3613-11e7-8e93-d305ddae3c10.png)

After entering **a2disconf javascript-common** and restarting Apache2 - it works perfectly! But this is workarround.

In my opinion best it would be to change JavascriptController's name to avoid these situations where default server configuration breaks the application.

[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=553173](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=553173)
[http://stackoverflow.com/questions/21706067/apache-doesnt-serve-files-in-javascript-directory-why](http://stackoverflow.com/questions/21706067/apache-doesnt-serve-files-in-javascript-directory-why)
[https://serverfault.com/questions/274254/cannot-access-javascript-folder](https://serverfault.com/questions/274254/cannot-access-javascript-folder)

**Comment by JC5** [comment]
Yes, I thought about that, and then I realized how useless this package is (you didn't even know you had it let alone what it did). 

I will accept the occasional bug report if it means I can can get rid of one instance of this package. I am not sure what idiot came up with the idea to hijack the `/javascript` URL but I'm not going to change anything.

**Comment by tpetrauskas** [comment]
Maybe could you note this "**a2disconf javascript-common**" in the installation guide so everyone will know how to fix this issue?

**Comment by JC5** [comment]
Will do!

**Comment by tpetrauskas** [comment]
Since this is solved I'm closing this issue.
