### ISSUE TITLE
Yearly Recurring Transaction dates issue on Spanish language

### ISSUE THREAD

**Issue by tmllull** [firefly-iii/firefly-iii#6460]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When add a new "Yearly Recurring Transaction", with Spanish language, the repetition date not works as expected (apparently).

### Expected behaviour

With Spanish language selected, when I add a new "Recurring Transaction", and select "Every year" repetition, the date that appears on dropdown not shows the correct date. For example, if I select 25th of September as a first day, the recurring yearly date is "0 of september"

![imagen](https://user-images.githubusercontent.com/5560652/192098503-7271bbe5-dbd3-4d87-9d2d-c39407d11079.png)

if I select 30th, shows "5 of september".

![imagen](https://user-images.githubusercontent.com/5560652/192098529-7a613262-1f23-4626-902a-9fc794cd4c16.png)

The point is that when you save it, on the resume list, the repetition column shows the same "wrong dates", but the "next occurrence" show the correct date, so I don't know when the transaction will be added (wrong or correct date):

![imagen](https://user-images.githubusercontent.com/5560652/192098831-69ec3565-3dc6-4082-b2a1-724deef42ffc.png)

I checked to change language to English (and Italian too) and the dates apparently works fine:

![imagen](https://user-images.githubusercontent.com/5560652/192098868-65923b34-e14a-4738-a847-9427c74804ab.png)

### Debug information

Debug information generated at 2022-09-24 14:51:17 Europe/Madrid for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | 255, 11-09-2022 07:30:27 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Madrid |
| Browser TZ | Europe/Madrid |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | es_ES |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-09-01 00:00:00 |
| Session end | 2022-09-30 23:59:59 |
| Session first | 2022-08-01 00:00:00 |
| User ID | 1 |
| User language | es_ES |
| User locale | es_ES |
| Attempt at "es_ES.utf8" | 'es_ES.utf8' |
| Attempt at "es_ES.UTF-8" | 'es_ES.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 |

### Steps to reproduce

1. Change language to Spanish
2. Add new "Recurring Transaction"
3. On first date, select any date
4. On "repetition type", select "yearly". The date on dropdown will be wrong
5. Extra: save the transaction and check the resume.

**Comment by JC5** [comment]
Thanks for letting me know. It's a translation issue, it'll be fixed in the next release :+1:

**Comment by tmllull** [comment]
Thanks for your time, and quick responses!
