### ISSUE TITLE
broken link on the message shown when browsing to ../public

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#6461]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I invoke the firefly page for my website (https://mywebsite.com/firefly-iii/) instead of the .../firefly-iii/public/ folder, I get the security warning message. That message directs to the following link that no longer exists. https://github.com/firefly-iii/help/wiki/Configure-your-webserver-correctly.

### Expected behaviour

Obtain security message, with support available at a link that is valid

### Debug information

Debug information generated at 2022-09-25 17:15:46 UTC for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | (unknown), (unknown) |
| DB version | 18 (exp. 18) |
| PHP | `8.0.23` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Lisbon |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2014-03-20 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | pt_PT |
| Attempt at "pt_PT.utf8" | 'pt_PT.utf8' |
| Attempt at "pt_PT.UTF-8" | 'pt_PT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0 |

### Steps to reproduce

Access https://yours.com/firefly-iii/

**Comment by JC5** [comment]
Thanks, I'll pick it up. Also, please fix this on your own installation.
