### ISSUE TITLE
PUT /api/v1/accounts/{id} updating "current_balance" does not work as expected

### ISSUE THREAD

**Issue by mjb2k** [firefly-iii/firefly-iii#6465]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Been trying to use the API to update my current_balance for an account and so far it has eluded me and I believe it's a bug.

I saw an earlier issue regarding a similar problem for updating virtual balance, https://github.com/firefly-iii/firefly-iii/issues/6053, but this problem still persists for current_balance.

### Expected behaviour

I expect the current balance to change for my account.

### Debug information

Debug information generated at 2022-09-25 23:58:45 America/New_York for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | 255, 11-09-2022 07:30:27 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-09-01 00:00:00 |
| Session end | 2022-09-30 23:59:59 |
| Session first | 2022-09-16 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15 |

### Steps to reproduce

Put in below, but basically making simple curl requests to the API and finding that the result fails to change what I desire.

### Additional info

Here's my curl request:

```
curl -k --location --request PUT 'https://local.firefly3.mjb2k/api/v1/accounts/6' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer $PAT' \
--header 'Content-Type: application/json' \
--data-raw '{
    "current_balance": "48884"
}'
```

and here's my results (with limited info to maintain privacy):
```
{
  "data": {
    "type": "accounts",
    "id": "6",
    "attributes": {
      "created_at": "2022-09-16T18:04:02-04:00",
      "updated_at": "2022-09-25T23:46:31-04:00",
      "active": false,
      "order": 3,
      "name": "account",
      "type": "asset",
      "account_role": "defaultAsset",
      "currency_id": "8",
      "currency_code": "USD",
      "currency_symbol": "$",
      "currency_decimal_places": 2,
      "current_balance": "43888.14",
      "current_balance_date": "2022-09-25T23:59:59-04:00",
      "notes": null,
      "monthly_payment_date": null,
      "credit_card_type": null,
      "account_number": "123456789",
      "iban": null,
      "bic": "",
      "virtual_balance": "0.00",
      "opening_balance": "12345",
      "opening_balance_date": "2022-09-16T00:00:00-04:00",
      "liability_type": null,
      "liability_direction": null,
      "interest": null,
      "interest_period": null,
      "current_debt": null,
      "include_net_worth": true,
      "longitude": null,
      "latitude": null,
      "zoom_level": null
    },
    "links": {
      "0": {
        "rel": "self",
        "uri": "/accounts/6"
      },
      "self": "https://local.firefly3.mjb2k/api/v1/accounts/6"
    }
  }
}
```

Interestingly I can actually set the current_balance by changing the virtual_balance:
```
curl -k --location --request PUT 'https://local.firefly3.mjb2k/api/v1/accounts/6' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer $PAT' \
--header 'Content-Type: application/json' \
--data-raw '{
    "current_balance": "48884",
    "virtual_balance": "100000"
}'
```

```
{
  "data": {
    "type": "accounts",
    "id": "6",
    "attributes": {
      "created_at": "2022-09-16T18:04:02-04:00",
      "updated_at": "2022-09-25T23:53:53-04:00",
      "active": false,
      "order": 3,
      "name": "account",
      "type": "asset",
      "account_role": "defaultAsset",
      "currency_id": "8",
      "currency_code": "USD",
      "currency_symbol": "$",
      "currency_decimal_places": 2,
      "current_balance": "143888.14",
      "current_balance_date": "2022-09-25T23:59:59-04:00",
      "notes": null,
      "monthly_payment_date": null,
      "credit_card_type": null,
      "account_number": "",
      "iban": null,
      "bic": "",
      "virtual_balance": "100000.00",
      "opening_balance": "48888.14",
      "opening_balance_date": "2022-09-16T00:00:00-04:00",
      "liability_type": null,
      "liability_direction": null,
      "interest": null,
      "interest_period": null,
      "current_debt": null,
      "include_net_worth": true,
      "longitude": null,
      "latitude": null,
      "zoom_level": null
    },
    "links": {
      "0": {
        "rel": "self",
        "uri": "/accounts/6"
      },
      "self": "https://local.firefly3.mjb2k/api/v1/accounts/6"
    }
  }
}

```

For now I am setting the opening balance to 0 and my virtual balance to the current value, but I am not sure this will fit my needs in some time because the values will change everyday and I would like my graph to reflect that, and I worry that by just changing the virtual balance it won't do that.

**Comment by JC5** [comment]
Current balance is read only. Submit transactions to change it.
