### ISSUE TITLE
Add support for American bank automatic imports in the Data Importer tool

### ISSUE THREAD

**Issue by ryuujinzero** [firefly-iii/firefly-iii#6477]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I noticed Nordigen and Spectre/Salt Edge do not support American banks. Can support for American banks be added by using Rocket Money or Mint's API?

### Solution

This would allow American users to automatically import their transaction data without the need to export a CSV and upload it manually.

**Comment by JC5** [comment]
Salt Edge used to support American banks, but they stopped doing so recently. 

Mint and Rocket Money do not offer API's that I know of.

**Comment by JC5** [comment]
If you know of a service that 

- offers American financial institutions
- is free for end users, or has low costs
- has an API that I can access

Please let me know.

**Comment by ameyp** [comment]
How about Plaid? It has an API for developers, it seems to support up to 100 institutions with live data for free, and supports a number of banks in America
