### ISSUE TITLE
Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by TheGreatBeginner777** [firefly-iii/firefly-iii#6485]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Just started with this app hosted on Yunohost. Started with creating Tags and after I tried to save 2nd tag this error pops up:

> Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:
> 
> file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/22/f5/22f531b36995db25d5ab927b50b8b05ed277f35c): Failed to open stream: No such file or directory

### Expected behaviour

Continue with adding Tags.

### Debug information

Debug information generated at 2022-10-02 20:09:34 Europe/London for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | (unknown), (unknown) |
| DB version | 18 (exp. 18) |
| PHP | `8.0.24` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-10-01 00:00:00 |
| Session end | 2022-10-31 23:59:59 |
| Session first | 2022-10-02 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Login to Firefly III
2. Other-Classification-Tags-Create a tag
3. Fill in data and tick box Return here, press Store new tag.
4. Do the same thing like in 3. for next tag.
5. Error...

### Additional info

I've read about closed issues of similar sort. I can see mentioning of deleting cache folder but I'm hesitant to do it since I'm not comfortable with it before asking here.

**Comment by JC5** [comment]
Deleting the directory may be a bit much, but you can clear your cache manually or by flushing to `/flush`.

https://docs.firefly-iii.org/firefly-iii/faq/self_hosted/#unable-to-write-to-cache-directory
