### ISSUE TITLE
Mass delete does not work

### ISSUE THREAD

**Issue by henrytrager** [firefly-iii/firefly-iii#649]
When trying to delete several transactions from "transactions>expenses" menu, I get the following message:
404 — Firefly III cannot find this page.

url accessed: https://firefly-iii.nder.be/transactions/transactions/mass/delete/568,561

--> https://firefly-iii.nder.be/transactions/mass/delete/568,561 works fine.

**Comment by JC5** [comment]
I'm not sure what you mean. As far as I can see it works like you say. Did you encounter the error in your own installation?

**Comment by henrytrager** [comment]
on my own installation but also on the demo site. Let me walk you through what I do.
After logging in, I go on the left menu: Transactions > Expenses.
On the bottom of the page, I select "select transactions", then I tick a couple of boxes and push "delete selected (2)
I then get the following message: "404 — Firefly III cannot find this page."

**Comment by JC5** [comment]
Mmm, that is very strange. The demo site works for me. Could you try reloading the page with shift-F5 or Shift Command R (apple)? It may be a cache thing.

The URL you mentioned (twice) works.

**Comment by henrytrager** [comment]
Reloading the page (ctrl+F5) does not fix the issue on Microsoft Edge (Microsoft Edge 38.14393.1066.0/ Microsoft EdgeHTML 14.14393). 

I have tested that functionality with Chrome and it works fine !

**Comment by JC5** [comment]
That is strange, they should behave the same. What is the URL that Edge is trying to make you go to?

**Comment by henrytrager** [comment]
Edge goes to https://firefly-iii.nder.be/transactions/transactions/mass/delete/568,561
whereas chrome goes to https://firefly-iii.nder.be/transactions/mass/delete/568,561

Please note that edit does not work as well:
Edge goes to https://firefly-iii.nder.be/transactions/transactions/mass/edit/232,231
chrome goes to https://firefly-iii.nder.be/transactions/mass/edit/232,231

**Comment by JC5** [comment]
Ah, I see! I did not notice the double "transactions". I'll see what I can do!

**Comment by JC5** [comment]
Fixed! And since a new release is imminent, I'm closing this issue.
