### ISSUE TITLE
/health route in data-importer

### ISSUE THREAD

**Issue by alexklibisz** [firefly-iii/firefly-iii#6492]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to monitor my data-importer installation. Currently I don't see a health route. 

### Solution

add a /health route.

### What are alternatives?

I could request the landing page, but:
* I prefer a simple 'OK' response, similar to the firefly-iii /health route.
* I prefer to deploy my data-importer behind a secured gateway and only expose a single route for monitoring.

**Comment by JC5** [comment]
Good idea!
