### ISSUE TITLE
[ERROR] Incorrect definition of table mysql.column_stats

### ISSUE THREAD

**Issue by angelbarrera92** [firefly-iii/firefly-iii#6499]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Checking the docker-compose logs I can see a few errors related to the DB schema:

```bash
Oct 04 08:39:40 firefly docker[1956]: firefly-db-1             | 2022-10-04  8:39:40 66 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
Oct 04 08:39:40 firefly docker[1956]: firefly-db-1             | 2022-10-04  8:39:40 66 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
```

I'm almost sure it does not impact the correct behavior of the application, but it could be a good idea to understand what is happening there. 

### Expected behaviour

No errors in the log :)

### Debug information

Debug information generated at 2022-10-04 08:47:26 Europe/Madrid for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | 255, 11-09-2022 07:30:27 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Madrid |
| Browser TZ | Europe/Madrid |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | es_ES |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-10-01 00:00:00 |
| Session end | 2022-10-31 23:59:59 |
| Session first | 2021-07-27 16:34:29 |
| User ID | 1 |
| User language | es_ES |
| User locale | es_ES |
| Attempt at "es_ES.utf8" | 'es_ES.utf8' |
| Attempt at "es_ES.UTF-8" | 'es_ES.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0 |

### Steps to reproduce

I can see these logs from startup

### Additional info

I am using the app for a year or so with a few updates, it works like a charm, the only issue I found during this time is this one.  So... amazing product folks!

**Comment by JC5** [comment]
Thanks for the compliments.

I think this is specific to the database container: I don't use the "mysql" database (there is always a database called "mysql" next to the "firefly" database). I'm not even sure I can reach that database from my container, since the "firefly" user does not have root access.

As such, I don't think there's much I can do about this. Is Firefly III running as expected?

**Comment by angelbarrera92** [comment]
> Thanks for the compliments.
> 
> I think this is specific to the database container: I don't use the "mysql" database (there is always a database called "mysql" next to the "firefly" database). I'm not even sure I can reach that database from my container, since the "firefly" user does not have root access.
> 
> As such, I don't think there's much I can do about this. Is Firefly III running as expected?

Yes, it is, I mean, as I can see, everything is working as expected. 

After following (to recover root password): https://gist.github.com/rordi/ab55c92848fd06884172ed22ae88d7df
Then: https://bytefreaks.net/applications/docker/incorrect-definition-of-table-mysql-column_stats-expected-column

**The issue was solved.**
My fear was that I miss some migration somewhere while updating firefly
