### ISSUE TITLE
Decimal commas gone

### ISSUE THREAD

**Issue by tomazsustar** [firefly-iii/firefly-iii#650]
Hi,

I have tried to migrate Firefly-iii to another server. Everything works as expected, only the decimal points and a comma for thousands are gone for all values. The values in the database are correct. Do you have an idea what could be the reason?

**Comment by JC5** [comment]
Your new server probably does not have the correct language packages installed.

**Comment by tomazsustar** [comment]
Hi, yes I have figured it out.  I installed Firefly to Raspberry Pi which has some issues with the locale settings. For some reason one needs to set locale to en_US.UTF-8 first, after that it is possible to select other setting and everything works as it should. http://daker.me/2014/10/how-to-fix-perl-warning-setting-locale-failed-in-raspbian.html

**Comment by JC5** [comment]
Good to hear it! :D
