### ISSUE TITLE
FIDI+Nordigen cannot handle transactions with amount of zero?

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#6500]
- [ ] Detect and ignore these transactions before they hit Firefly III.

Discussed in https://github.com/orgs/firefly-iii/discussions/6493

Make sure data importer warns and ignores zero amount transactions.

**Comment by GrigoriOH** [comment]
Would be great to see this in an upcoming version, as FIDI currently crashes with Nordigen for one of my accounts and CSV is a hassle, due to very limited information my bank puts into the exported files.
