### ISSUE TITLE
"Order by" on top of every table in all views showing tables.

### ISSUE THREAD

**Issue by stijn-dhondt** [firefly-iii/firefly-iii#6505]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

there is no order feature available on all views. 
would be nice to be able to order some views on date or ID or large to smallest expense.

### Solution

on top of every table view a order feature could be added to sort items that are available.

### What are alternatives?

no clue ;-)

### Additional context

none but should be quite clear i think...

**Comment by JC5** [comment]
Yes, this is on my list! Allow me to close this one and refer you to: https://github.com/firefly-iii/firefly-iii/issues/6304
