### ISSUE TITLE
Feature Request: double Y axis to represent secondary currency 

### ISSUE THREAD

**Issue by zmiguel** [firefly-iii/firefly-iii#6506]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I've recently started using firefly to keep track of my finances and while everything is great, there this one thing that is a bit annoying.

I'm currently living in Sweden and have accounts both in EUR and SEK, keep in mind that 1 EUR is ~10 SEK. This makes it so when looking at the graphs in the dashboard that have both EUR and SEK transactions it looks like I spent 10x more than I actually did because of the 10x value.

### Solution

I propose a solution for this: the use of a second Y axis for a secondary currency. The same has been suggested on #4335, but it has since been marked as stale, and it's locked.

You would configure your primary currency like you currently do, but you would have the option to configure a secondary currency, so you can better read graphs when the currencies have a big difference in value.

**Comment by JC5** [comment]
I have this on my list for the new layout. Let me point you to the ticket! :+1:

https://github.com/firefly-iii/firefly-iii/issues/6299
