### ISSUE TITLE
Edit transactions with multiple currencies not possible

### ISSUE THREAD

**Issue by tschager** [firefly-iii/firefly-iii#651]
A strange error occurs if a transaction between accounts with different currencies is modified:

> Undefined index: exchanged_amount 

Steps to reproduce on the [demo site](https://firefly-iii.nder.be/):

1. Create a new transaction from "Checking Account" to "Foreign Checking Account" with Amount (source)=123 and Amount (target)=100

2. Edit the transaction and change Amount (target) to some other value

BTW: The balance of the target account "Foreign Checking Account" is not correct, as Amount (source) of the above transaction is considered instead of Amount (target). The balance is 0 before the transaction, but £123.00 instead of £100.00 after the transaction.

**Comment by JC5** [comment]
I'll get right to it. I knew multi-currency would be buggy, I just hoped there were less bugs ;)

**Comment by JC5** [comment]
This is fixed in the upcoming version, you can test it on the demo site.
