### ISSUE TITLE
Set a color coding for Categories, Tags

### ISSUE THREAD

**Issue by didiermiller** [firefly-iii/firefly-iii#6511]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to be able to assign colors to categories and tags. This way you can spot which transaction is part of a category or tag much easier. It also helps when using colors to "group" certain categories.

This could also work well for budgets and contracts.

### Solution

The solution can be as simple as the one in github; it does not have to be anything fancy. A simple color picker on the edit screen of the categories to change the color. A piece of HTML code or CSS to apply on the right places.

**Comment by JC5** [comment]
I thought about this a bit but it's not going to be an option, sorry about that.
