### ISSUE TITLE
[FR] Support OIDC for user creation/management.

### ISSUE THREAD

**Issue by pinarruiz** [firefly-iii/firefly-iii#6514]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Although Firefly III has the [Remote User](https://docs.firefly-iii.org/firefly-iii/advanced-installation/authentication/#remote-user) authentication method, integrating OIDC to be able to use services like keycloak or authentik to create and/or manage users could be a great addition to the application.

### Solution

Support for OIDC authentication.

### What are alternatives?

Other ways of making this possible, that might be a future FR might be LDAP, SAML, or oauth

**Comment by JC5** [comment]
Why would it be a great addition to the application? At the moment 99% of the users use it for a single user.

**Comment by pinarruiz** [comment]
> Why would it be a great addition to the application? At the moment 99% of the users use it for a single user.

Adding new capabilities to Firefly III might bring new users to it, a colleague of mine and i would like to use the app, but since it lacks support for OIDC we are not using it, and maybe this is the case for some potential users too, maybe that is the reason why all users use it on a single user way.

Also, we can think about users that are not to good with tech, maybe a whole household or a company where someone deploys Firefly III and they already have this kind of authentication set up, having this feature will allow users to have a smooth experience not having to deal with creating a new account just for this service, also making life easier for the administrator of the app.

**Comment by JC5** [comment]
So what are you specifically missing from OIDC that you can't do with the Remote User feature?

**Comment by pinarruiz** [comment]
> So what are you specifically missing from OIDC that you can't do with the Remote User feature?

As far as i know (by the docs) there is no way of creating a user automatically with it, and also i will need to set up a proxy, might be nice that Firefly III can handle OIDC to create users, and also not need a proxy to make deployments easier.

**Comment by pinarruiz** [comment]
Sure, if thats is covered i think it should be added to the docs tho (unless i missed it),as the user creation is the most important feature for me. Would you accept a PR with OIDC support anyway? If i have the time i think i can implement it.

**Comment by pinarruiz** [comment]
Sure, thanks for being so quick :smile: Have a great day.
