### ISSUE TITLE
Rules not working for me, maybe I'm doing it wrong

### ISSUE THREAD

**Issue by linucksrox** [firefly-iii/firefly-iii#6515]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

While I could be doing something wrong, or misunderstanding something, I cannot get rules to trigger. I am trying to create 2 types of rules.
1. The first rule would be when a transaction comes in with a certain description and certain destination account, it would add the transaction amount to a specified piggy bank. When I run the matching transactions I get transactions listed there. But when I add a new transaction, nothing happens in the piggy bank. When I manually execute the rule, still nothing adds to the piggy bank.
2. The second rule would be whenever a withdrawal type transaction happens and is assigned to a specific category, remove that transaction amount from a specific piggy bank. Like the previous rule, I can create the rule and see matching transactions, but the rule never seems to trigger.

### Expected behaviour

Rules would trigger and modify the piggy bank amounts when new transactions match the rule criteria.

### Debug information

Debug information generated at 2022-10-06 18:10:46 UTC for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | 255, 11-09-2022 07:30:27 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | America/Detroit |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-10-01 00:00:00 |
| Session end | 2022-10-31 23:59:59 |
| Session first | 2022-06-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0 |

**Comment by JC5** [comment]
Rules related to piggy banks only work on transfers, that might be it.

**Comment by JC5** [comment]
Not using rules, I'm afraid. The next release has easy access to webhooks that you could use to manage these advanced splits and things. But it's not something that's native to Firefly III.

**Comment by linucksrox** [comment]
Awesome, I will keep doing it manually and really looking forward to a way to automate this part of my budget! Thanks for your help!
