### ISSUE TITLE
Changing the default docker compose database to Postgresql

### ISSUE THREAD

**Issue by Asteliks** [firefly-iii/firefly-iii#6523]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Currently the [default docker compose](https://raw.githubusercontent.com/firefly-iii/docker/main/docker-compose.yml) file uses mariadb. Should anyone want to move their server to the widely promoted [TrueNas Scale](https://www.truenas.com/truenas-scale/) and use server [Apps](https://www.truenas.com/docs/scale/scaletutorials/apps/usingapps/) delivered by [Truecharts](https://truecharts.org/) then that person runs into a problem. The Truecharts configuration of Firefly III uses only Postgresql [and the maintainers would rather not change that](https://github.com/truecharts/charts/issues/4014). So, in order to migrate one would need to be proficient in ETL or have some kind Firefly III of data migration tool that would for example work over the API.

### Solution

I can see two solutions:

- Currently the default docker compose file uses mariadb. I would like request switching to Postgresql so that future users will not run into this issue;
- Perhaps a simple tool will do that would use the current API to move between Firefly III instances.

Unfortunately, my limited skills do not allow me to see more options. Perhaps you can see a better solution

**Comment by JC5** [comment]
Migrating from one type of database to another is always a challenge, and if I change from mariadb to postgres no doubt some other widely promoted app service user is going to complain about having to migrate in the other direction. So that's a pass, thanks.

**Comment by Asteliks** [comment]
Yea, I know this is a hard topic and has been a pain for quite a while now. Would you have any suggestions how we can solve this?

**Comment by JC5** [comment]
Not really. There are several tools that allow you to migrate from one to the other, I can only suggest you use those.
