### ISSUE TITLE
Joining Hacktoberfest

### ISSUE THREAD

**Issue by Asteliks** [firefly-iii/firefly-iii#6524]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

There are no free T-shirts or tree planting events for creating PR to this repo.

### Solution

By simply adding a topic (tag) "hacktoberfest" we could join The [Hacktoberfest](https://hacktoberfest.com/). It is a fun yearly event that rewords people for submitting pull requests to opensource projects. Usually after 4 accepted PR people receive a free t-shirt or get to plant a tree. Joining the event: costs us nothing, could get more people supporting this repo and will reword the people that already are supporting this repo. At least ones a year.

**Comment by JC5** [comment]
Unfortunately I will not be joining Hacktoberfest this year. Perhaps next year again.
