### ISSUE TITLE
disable rules on manually edited transaction.

### ISSUE THREAD

**Issue by dtibi** [firefly-iii/firefly-iii#6526]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to suggest adding a way to disable running rules on specific transactions.

### Solution

maybe by adding a checkbox in the information edit page where if checked then the specific transaction will never be automated with rules

### What are alternatives?

adding a tag to all these transactions that if caught in rules will stop processing any other rules.
I hate this alternative. but its a valid workaround...
adding the checkbox near the place I edit the category would be best 😄 

### Additional context

I use rules to categorize transactions.
In the case where I categorize a transaction that is using some app to send a friend money. (like venmo, zelle, paypal ...)
So in general there are many reasons to send money to a friend. I categorize these transactions as "transfer".
but if I see a specific transfer that I recognize and know it should belong to a different category and I want to update it. 
I cant because the next time I will run all rules on my transactions it will undo my changes.
Adding this feature will allow me to overcome this issue 😄 

I'm sure there are more cases where you would like a transaction to never be automated after you made a change you don't want to be undone.

Also wanted to say fireflyiii is amazing!
This is just a suggestion.

**Comment by JC5** [comment]
Thanks for the compliments! I'll see what I can do about the option.

For now, you can also make your rule trigger on "has no tags" and then add a tag to the transactions you change manually.

**Comment by JC5** [comment]
Fixed in 5.8.0. Alpha version will be released soon.
