### ISSUE TITLE
Bug when trying to edit an old transfer

### ISSUE THREAD

**Issue by tomazsustar** [firefly-iii/firefly-iii#653]
I want to update some old transfer (created before 4.4.3) to correct the currencies (CHF -> EUR), but I get an error there:

Undefined index: exchanged_amount

Error

This error occured in file /var/www/html/firefly-iii/app/Repositories/Journal/JournalRepository.php on line 267 with code 0.

Stack trace

#0 /var/www/html/firefly-iii/app/Repositories/Journal/JournalRepository.php(267): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/html/f...', 267, Array)
#1 /var/www/html/firefly-iii/app/Http/Controllers/Transaction/SingleController.php(372): FireflyIII\Repositories\Journal\JournalRepository->update(Object(FireflyIII\Models\TransactionJournal), Array)
#2 [internal function]: FireflyIII\Http\Controllers\Transaction\SingleController->update(Object(FireflyIII\Http\Requests\JournalFormRequest), Object(FireflyIII\Repositories\Journal\JournalRepository), Object(FireflyIII\Models\TransactionJournal))
#3 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#4 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('update', Array)
#5 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Controllers\Transaction\SingleController), 'update')
#6 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()

**Comment by JC5** [comment]
Is related to this one: https://github.com/firefly-iii/firefly-iii/issues/651

I've found the problem and I've fixed it. I intend to do a new release this weekend.
