### ISSUE TITLE
Bloated Description Names with Nordigen

### ISSUE THREAD

**Issue by ohare93** [firefly-iii/firefly-iii#6539]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Import with Nordigen via DanskeBank results in long Descriptions with useless stuff. Such as

> Transfer of salaryEndToEndID: NOTPROVIDED
or
> To MadkontoWe have transferred the amount to:[[Account id]]EndToEndID: NOTPROVIDED 
or 
> Car service 2022We have  transferred the amount to:[[Business]][[Account id]]EndToEndID: NOTPROVIDED

### Expected behaviour

Normal names for the Descriptions:
> Transfer of salary
or
> To Madkonto
or 
> Car service 2022

There is also no option in the importer to set the Description.

### Debug information

Debug information generated at 2022-10-14 14:39:07 Europe/Copenhagen for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | 255, 11-09-2022 07:30:27 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Copenhagen |
| Browser TZ | Europe/Copenhagen |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-10-01 00:00:00 |
| Session end | 2022-10-31 23:59:59 |
| Session first | 2020-10-12 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0 |

### Steps to reproduce

1. Import via Nordigen through Danskebank.

**Comment by ohare93** [comment]
Here are a few examples that I think are helpful. Since this is financial info I have anonymised it and changed all the ids :+1: 


Me paying a business:
---
```
          {
                "transactionId": "ACB11327EEF997CC2A8789B0A2414BABC02CBE05231EF5F52C7CACAF5E942F50",
                "entryReference": "2791231207",
                "bookingDate": "2022-10-06",
                "valueDate": "2022-10-06",
                "transactionAmount": {
                    "amount": "-55.00",
                    "currency": "DKK"
                },
                "creditorName": "Restaurant China v )))) 79501",
                "remittanceInformationUnstructured": "Restaurant China v )))) 79501\nEndToEndID: NOTPROVIDED",
                "additionalInformation": "2791231207",
                "merchantCategoryCode": "5813",
                "internalTransactionId": "eb2bbff1f22f2ac88baaeeb23049e0c6"
            },
```

It seems that creditorName is what I want in this context.


Receiving monthly salary:
---

```
            {
                "transactionId": "7A59FE7559F401BBB7D7218921823901328EA6AC6055A60221C5658A802107FB",
                "entryReference": "4183150302",
                "bookingDate": "2022-09-30",
                "valueDate": "2022-09-30",
                "transactionAmount": {
                    "amount": "[[My salary]]",
                    "currency": "DKK"
                },
                "debtorName": "[[My employer]]",
                "debtorAccount": {},
                "remittanceInformationUnstructured": "Transfer of salary\nWe have received the following payment from:\n[[My employer]][[Employers full address]]\nEndToEndID: NOTPROVIDED",
                "additionalInformation": "4173150502",
                "internalTransactionId": "8dd6d28c4a748aed6301d9c340b45320"
            },
```

Seems to be no way to take out "Transfer of salary" from this one. But 'debotName' would be fine with me.


Me transferring money from one account to another
---
```
          {
              "transactionId": "2CD792D1C6CD4950356F97FFA488AE8A07212CE20E11B8184753B91718DC86B1",
              "entryReference": "344R228076",
              "bookingDate": "2022-10-07",
              "valueDate": "2022-10-07",
              "transactionAmount": {
                  "amount": "15000.00",
                  "currency": "DKK"
              },
              "debtorName": "[[MY FULL NAME]]",
              "debtorAccount": {},
              "remittanceInformationUnstructured": "From Personal\nWe have received the following payment from:\n[[MY FULL NAME]][MY FULL ADDRESS]]\nEndToEndID: NOTPROVIDED",
              "additionalInformation": "343R228066",
              "internalTransactionId": "b2f0ba4ef03a490a36e0711b2552ae65"
          },
```

Same as the above one, no way to get out my specific typed message "From Personal" but 'debtorName' would be fine too.

**Comment by JC5** [comment]
The problem is this isn't something I can customize. What you see is what you get. Either Nordigen or your bank will have to clean up the data.

**Comment by JC5** [comment]
Yes, the CSV importer can do that. The Nordigen uses a fixed set of columns.

**Comment by ohare93** [comment]
But it could... not do that. It is possible to change it. Right?

**Comment by JC5** [comment]
There are about 2500 financial institution's supported by Nordigen. I can't build in exceptions for all of them :(

**Comment by ohare93** [comment]
You don't have to nor am I asking you to do that. I want to be able to select debtorName / creditorName rather than remittanceInformationUnstructured to be the Description when I import. Just like I can do a similar mapping when I import a csv.

**Comment by ohare93** [comment]
Probably right here:
https://github.com/firefly-iii/data-importer/blob/8f00f7ce6993afbde6db9ac56541e08707ca4a8a/app/Services/Nordigen/Model/Transaction.php#L273
As an optional override to the function :man_shrugging:

**Comment by JC5** [comment]
Like I said, those are the kinds of things I don't want to add to the importer. This is something your bank needs to fix unfortunately.

**Comment by ohare93** [comment]
> Like I said, those are the kinds of things I don't want to add to the importer. This is something your bank needs to fix unfortunately.

What you said is 

> There are about 2500 financial institution's supported by Nordigen. I can't build in exceptions for all of them :(

You don't want to make explicit overrides for 2500 banks. A reasonable statement by itself. But entirely unrelated to what I am asking for.

Why not allow the user to override the default mappings for the bank import? As you said, you can't build in exceptions for all of them. So give users the tools to fix the strange formats of their own banks.
