### ISSUE TITLE
Bookmark reports in application

### ISSUE THREAD

**Issue by TuringTux** [firefly-iii/firefly-iii#6542]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I have a few configured reports I want to regularly check. It would be nice if they could be bookmarked within the application, as to keep everything in one place.

### Solution

The "reports" UI should contain another box with bookmarked reports that can be configured.

Alternatively, it could just be an editable Markdown text box that is rendered by default (similar to the notes feature) where I can store the links. The longer I think about it, the more I actually like this alternative.

### What are alternatives?

I can of course create a bookmark in my browser or write the links down in an external document.

However, it would be nice to have everything in one place within the application. This would also allow for easier cross-browser and -device access to the bookmarked reports (of course, most browsers allow to create accounts to sync bookmarks between devices, but having them directly in the app would be even nicer).

### Additional context

This is definitely only a small quality-of-life enhancement for (probably) a limited set of users.

If you have no time/resources to implement it, but are in general open to having such a feature, I can try to implement it myself and open a PR :)

**Comment by JC5** [comment]
I made reports "bookmarkable" for this specific reason, so that's a no from me, sorry about that.
