### ISSUE TITLE
Content in 'Notes' fields may result in invalid CSV files

### ISSUE THREAD

**Issue by marinbernard-pep06** [firefly-iii/firefly-iii#6544]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Issue #3392 made Firefly III include the `Notes` field to CSV files generated by the export function. Yet, insufficient content sanitization may result in mangled CSV files when the `Notes` field contains a multi-line string, or the double quote character. In that case, the field content is exported as-is in the CSV file, which becomes invalid.

### Expected behaviour

The generated CSV file should remain valid whatever the field's content might be. At a minimum:

- Spacing control characters (`LF`, `CR`, `FF`, `HT`, `VT`) should be replaced with a single space character
- Other control characters should be removed
- Commas (CSV field delimiter) should be removed/replaced
- Double quotes (CSV text delimiter) should be removed/replaced

### Debug information

Debug information generated at 2022-10-16 13:59:25 Europe/Paris for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | (unknown), (unknown) |
| DB version | 18 (exp. 18) |
| PHP | `8.0.24` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Paris |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | fr_FR |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2013-07-10 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54 |

### Steps to reproduce

1. Create a transaction with a multi-line text string in the `Notes` field
2. Export all transactions to a CSV file
3. Open the CSV file with a text editor
4. Note that the multi-line strings were rendered as-is

### Additional info

Ideally, the `Notes` field should be sanitized before being included to the exported CSV file. If that's not possible, it should be either removed or made optional in the export form: I think most users would probably agree to drop the `Notes` field to get a usable CSV file. As of now, a single multi-line record is enough to make the whole export function unusable.

If I can help with this, with a PR or anything, just let me know.

Many thanks!

**Comment by JC5** [comment]
I'm using a library. I see no issues with the exported CSV files. Since there is no real standard, I'm using [thephpleague/csv](https://github.com/thephpleague/csv). If you have a problem with the export, take it up with them. As far as I can tell, the CSV files are fine.

**Comment by marinbernard-pep06** [comment]
> Since there is no real standard

In fact there is a minimal standard ([RFC4180](https://www.rfc-editor.org/rfc/rfc4180.html)), which **does** allow the use of line breaks within a data field (See RFC4180 title 2.6), that's why the [thephpleague/csv](https://github.com/thephpleague/csv) library does not escape such constructs and let them through.

In the real world though, most tools dealing with CSV files are unable to deal properly with multi-line fields. AFAIK, recent versions of Excel or PowerShell do not, and I expect many other tools, including common *nix tools, to give up on such oddities.

Personally, I see no use for multi-line fields or duplicated delimiter characters in Firefly III CSV exports, so I think we should keep it simple, aim for maximal compatibility, and remove them. Furthermore, Firefly III used to generate _consensual_ CSV until #3392, so people which were using the export feature before the change would probably see it as a regression (even if quite debatable, I know).

Anyway, I understand your approach. But since we do need this feature to export journals to Excel, I'll fork and fix it in my own repo.

Thank you,

**Comment by JC5** [comment]
> Personally, I see no use for multi-line fields or duplicated delimiter characters in Firefly III CSV exports, so I think we should keep it simple, aim for maximal compatibility, and remove them. 

There is no "we" here. YOU don't see the use.

**Comment by marinbernard-pep06** [comment]
> There is no "we" here. YOU don't see the use.

Yes of course. Thanks for being so nice.
