### ISSUE TITLE
[Importer] Add possibility to set custom tag

### ISSUE THREAD

**Issue by finfa** [firefly-iii/firefly-iii#6551]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I'd like the importer to give the ability to add a custom tag to the transaction import.

### Solution

This could be a reatively simple way to solve the duplicate problem that occurs when importing transfers between two accounts, using a rule.

The rule would remove transactions based on the "source iban" (account A), "destination iban" (account B) and the "tag" (import B). This would remove all transfers imported from account B, keeping those from account A, effectively solving the duplication problem.

### What are alternatives?

Any alternative means that gives the ability to filter transactions based on the account from which the import came would also be fine.

### Additional context

Thank you for this well done program.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6108
