### ISSUE TITLE
Ability to have custom date periods - budgets, bills etc

### ISSUE THREAD

**Issue by ggoosen** [firefly-iii/firefly-iii#6552]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be nice to be able to track expenses, budgets etc on a custom period. Specifically one could be paid on the 15th of each month and as such you want to track all budgets on a 15th-15th period. 

In addition, the budgeting while it caters for ability to set "quarterly" budgeting you cant set the date on when that quarter starts. Some bills, energy, water, gas etc are billed quarterly but all track to different quaterly periods. 

### Solution

Allow for periods to be configured so that the app does not assume the nornmal period is monthly

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/#changing-the-monthly-cycle-to-another-day-of-the-month

**Comment by ggoosen** [comment]
> In addition, the budgeting while it caters for ability to set "quarterly" budgeting you cant set the date on when that quarter starts. Some bills, energy, water, gas etc are billed quarterly but all track to different quaterly periods.

Sorry i missed the fact that you had already addressed in the FAQ. Just have one question, does this thought process apply to budgets that are quarterly as well? A quarter is not always defined as from Jan-March or Fiscal year start + 3 months? 

Is there any workaround to having budgets for quarters that are not alligned with the fiscal or calendar year?
