### ISSUE TITLE
Add overview tiles to mobile view

### ISSUE THREAD

**Issue by dklinger** [firefly-iii/firefly-iii#6555]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hey,
would it be possible to add the below overview tiles to the mobile view when opening FireFly via Smartphone?
I am switching from using MoneyControl on iOS for 10 years to FireFly and would use it often on the Smartphone.
I really miss the overview Tiles, which are shown on the Desktop-View, on the mobile view as they show the most important info I would like to see in a very quick way. 
I also don't see any other possibility to quickly view the overall balance or the net worth on the Dashboard, without having the Tiles. So this info is missing on mobile.
![image](https://user-images.githubusercontent.com/2249766/197140827-d616a115-ab8d-452b-8fb4-b251b4e517a6.png)

### Solution

Add Tiles (or the info they contain, but in another way) to the mobile view

**Comment by JC5** [comment]
I'm working on a new layout where I'm adding this as well :+1: Keep an eye on #6299.
