### ISSUE TITLE
wrong value used in bill chart

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#6556]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The chart in the bill page (/bills/show/{id}) does use the wrong value. I think its best explained with this screenshot:

![image](https://user-images.githubusercontent.com/31184224/197353441-ecf3bfc7-1da8-4523-a0da-2898f11ddd19.png)

Bill settings:
![image](https://user-images.githubusercontent.com/31184224/197353724-f34563d5-2c84-40b8-be45-d6073cbd5b7e.png)

### Expected behaviour

The chart should use the value of the currency which the bill uses.

OR

It should always use the main currency of the firefly-iii instance.

### Debug information

**THE BUG DOES EXIST IN THE DEMO SITE TOO!**

Debug information generated at 2022-10-22 19:15:38 Europe/Berlin for Firefly III version **5.7.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.14 |
| Firefly III API | 1.5.6 |
| Build | 286, 18-10-2022 21:16:12 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-10-01 00:00:00 |
| Session end | 2022-10-31 23:59:59 |
| Session first | 2017-06-30 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 |

**Comment by JC5** [comment]
Thanks for letting me know, I'll check it out :+1:
