### ISSUE TITLE
Updating expense account resets currency back to default

### ISSUE THREAD

**Issue by schoentoon** [firefly-iii/firefly-iii#6558]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When updating any expense account (don't even have to change anything, just pressing "Update expense account" in the ui works). It will reset the currency back to the default currency of the user. This is especially annoying as you can only change the currency through the API and not through the web interface (that probably should be its own issue).

### Expected behaviour

I would expect it to not change the currency of the expense account at all and just leave it as is.

### Debug information

Debug information generated at 2022-10-23 13:57:28 Europe/Zurich for Firefly III version **5.7.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.14 |
| Firefly III API | 1.5.6 |
| Build | 286, 18-10-2022 21:16:12 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Zurich |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-10-01 00:00:00 |
| Session end | 2022-10-31 23:59:59 |
| Session first | 2022-08-29 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0 |

### Steps to reproduce

1. Make sure multiple currencies are enabled.
2. Change the currency of an expense account (have to do this through the API), which would be a basic `curl -X 'PUT' \
  'https://<url>/api/v1/accounts/147' \
  -H 'accept: application/vnd.api+json' \
  -H 'Authorization: Bearer <snip>' \
  -H 'Content-Type: application/json' \
  -d '{
  "currency_code": "EUR"
}'`
3. Go to the edit expense account page in the web interface and press "Update expense account"
4. Currency of the expense account is now reset back to the default :(

**Comment by JC5** [comment]
I'll check it out but expense accounts won't get or keep their own currency, so whatever I change: you'll lose the ability to set the currency of something that isn't an asset account or a liability.

**Comment by schoentoon** [comment]
My main annoyance is expense accounts reporting a "current balance" of 0CHF if I only ever made transactions to them with EUR. 
![2022-10-23_14-30](https://user-images.githubusercontent.com/417618/197392269-687f13e3-9f39-4ac5-ad00-012f1a30ac7a.png)

I only realized that expense accounts had their own currency set after an import created new expense accounts with the EUR type (and it actually showed this under current balance for them).

**Comment by JC5** [comment]
They should report under the main currency only, I'm working on improvements to show others as well.
