### ISSUE TITLE
Save import config file on the server side

### ISSUE THREAD

**Issue by meichthys** [firefly-iii/firefly-iii#6559]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Saving the import file configurations on the server side would help streamline the import process.

It’s not difficult at all, but currently to import I need to select the import file and also the configuration file which needs to be saved on my local machine.
It would be nice if the server could just have a drop-down for saved configurations that I could choose from instead of having to upload from my local machine each time.

### Solution

To implement this, we would need a server side storage location to store the saved configurations, and probably a drop-down list that would let the user select the configuration that matches the import file. 

As a bonus it would be nice if the drop-down could be selected automatically based on the name of the import file (For example if the saved configuration and the import file have the same name).

### What are alternatives?

The current setup works fine but the extra step of uploading the configuration file each time does take a while when importing dozens of files each month.

**Comment by JC5** [comment]
Ehm, this is already in place :)

**Comment by meichthys** [comment]
Oh wow nice! I guess i need to update!

**Comment by JC5** [comment]
https://docs.firefly-iii.org/data-importer/help/config/
