### ISSUE TITLE
Right-Align numbers to match monetary value digits

### ISSUE THREAD

**Issue by misterEarly** [firefly-iii/firefly-iii#6564]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like Firefly III to right-align numbers (transaction values etc) in views that show multiple transactions (for example "Expenses"), so that all digits representing the same monetary value are exactly above/below each other.

Screenshot from the demo website:
![grafik](https://user-images.githubusercontent.com/73235781/197572030-b2869408-e992-465b-90ec-f51163af8c68.png)

Screenshot from a GnuCash example, showing the desired behaviour:
![grafik](https://user-images.githubusercontent.com/73235781/197572278-1328b9a2-9d1f-40b9-9acc-7b370caed809.png)

### Solution

This would increase readability and give an easier overview of your transactions.

**Comment by JC5** [comment]
Should already be there. Will be fixed! :+1:
