### ISSUE TITLE
Default DocumentRoot

### ISSUE THREAD

**Issue by edasaki** [firefly-iii/firefly-iii#657]
Just spent about 20 minutes figuring this out and thought it might be worth mentioning on the install guide or FAQ page.
I was getting a 404, and with basically no web dev experience I had no idea why. Eventually it turned out that with the default installation of Apache (using CentOS), httpd.conf had the DocumentRoot set to /var/www/html instead of just /var/www. Works great now, looking forward to using firefly :)

**Comment by JC5** [comment]
Glad you got it to work!
