### ISSUE TITLE
Fields not cleared

### ISSUE THREAD

**Issue by IcyBow** [firefly-iii/firefly-iii#6581]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I identified two fields that are not cleared even if visually it looks like it. For example when clearing tags or location, visually it looks like the fields are now empty but when viewing the submitted data, they were not deleted. 

### Expected behaviour

While creating a second transaction (after ticking: After storing, return here to create another one.) and clearing the tags using the trash icon (on the tags fields) I would expect that the tags are deleted.
When editing an account and clearing it's location I would expect that the location is gone after saving.

### Debug information

Could not debug sorry.

### Tags

1. Create a transaction with a tag
2. Tick: After storing, return here to create another one.
3. Use the trash icon to delete the tags.
4. Save the second transaction
5. (Check second transaction still has the tag)

### Location

1. Create or edit an existing account setting a location on the map.
2. Save
3. Edit that same account and click: Clear location
4. Save a second time
5. (Check that account and see that the location was not deleted.

### Additional info

I saw this since I first used Firefly-III (5.6.8) but it still behaves the same on the actual version 5.7.14.
Thank you :)

**Comment by JC5** [comment]
Nice find, I'll pick it up!
