### ISSUE TITLE
webhook not fired after destroying transaction

### ISSUE THREAD

**Issue by johncant** [firefly-iii/firefly-iii#6589]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Firstly, please let me congratulate you on how awesome Firefly-iii is! I'm trying to build an integration with Grist that will be easy for people to set up and start using.

The issue I'm facing is:

Messages are not added for TRIGGER_DESTROY_TRANSACTION webhooks when a transaction is deleted via the UI.

### Expected behaviour

After deleting a transaction in the web UI, messages should be added for TRIGGER_DESTROY_TRANSACTION webhooks.

### Debug information

TODO - I'll reproduce the issue again on the demo site later and add this info.

### Steps to reproduce

1. Set up a personal access token on the demo site
2. Register two webhooks via the API:

This webhook demonstrates that webhooks are working generally:
```
curl -v -XPOST https://demo.firefly-iii.org/api/v1/webhooks -H'Content-Type: application/vnd.api+json' -H'Authorization: Bearer <token> -H'Accept: application/json' -d'{"url": "https://webhook.site/9b9da317-f84c-49b4-85dd-46ed452b41a3", "trigger": "TRIGGER_STORE_TRANSACTION", "delivery": "DELIVERY_JSON", "response": "RESPONSE_TRANSACTIONS", "active": true, "title": "store1"}' | jq
```
Output:
```
{
  "data": {
    "type": "webhooks",
    "id": "1",
    "attributes": {
      "created_at": "2022-10-31T23:13:24+01:00",
      "updated_at": "2022-10-31T23:13:24+01:00",
      "active": true,
      "title": "store1",
      "secret": "DMLcx4SxNMJOtpBNIR1jZwPc",
      "trigger": "TRIGGER_STORE_TRANSACTION",
      "response": "RESPONSE_TRANSACTIONS",
      "delivery": "DELIVERY_JSON",
      "url": "https://webhook.site/9b9da317-f84c-49b4-85dd-46ed452b41a3"
    },
    "links": {
      "self": "https://demo.firefly-iii.org/api/v1/webhooks/1",
      "0": {
        "rel": "self",
        "uri": "/webhooks/1"
      }
    }
  }
}
```

This webhook demonstrates that TRIGGER_DESTROY_TRANSACTION is not fired:
```
curl -v -XPOST https://demo.firefly-iii.org/api/v1/webhooks -H'Content-Type: application/vnd.api+json' -H'Authorization: Bearer <token>' -H'Accept: application/json' -d'{"url": "https://webhook.site/#!/466c13b6-e1d4-4a3d-baa9-132ce555da30", "trigger": "TRIGGER_DESTROY_TRANSACTION", "delivery": "DELIVERY_JSON", "response": "RESPONSE_TRANSACTIONS", "active": true, "title": "destroy1"}' | jq
```
Output:
```
{
  "data": {
    "type": "webhooks",
    "id": "2",
    "attributes": {
      "created_at": "2022-10-31T23:14:26+01:00",
      "updated_at": "2022-10-31T23:14:26+01:00",
      "active": true,
      "title": "destroy1",
      "secret": "ryQvjJD0VzUUMtMbKcHnjXK5",
      "trigger": "TRIGGER_DESTROY_TRANSACTION",
      "response": "RESPONSE_TRANSACTIONS",
      "delivery": "DELIVERY_JSON",
      "url": "https://webhook.site/#!/466c13b6-e1d4-4a3d-baa9-132ce555da30"
    },
    "links": {
      "self": "https://demo.firefly-iii.org/api/v1/webhooks/2",
      "0": {
        "rel": "self",
        "uri": "/webhooks/2"
      }
    }
  }
}
```

3. Create a transaction
4. Delete the transaction
5. Check that webhooks were received. Expected behaviour: Both webhooks delivered. Actual behaviour: Data only received for the TRIGGER_STORE_TRANSACTION webhook.
6. Check webhook messages:
7.
```
curl -v -XGET https://demo.firefly-iii.org/api/v1/webhooks/2/messages -H'Content-Type: application/vnd.api+json' -H'Authorization: Bearer <token>' -H'Accept: application/json' | jq
```
Output:
```
{
  "data": [],
  "meta": {
    "pagination": {
      "total": 0,
      "count": 0,
      "per_page": 50,
      "current_page": 1,
      "total_pages": 1
    }
  },
  "links": {
    "self": "https://demo.firefly-iii.org/api/v1/webhooks/2/messages?&page=1",
    "first": "https://demo.firefly-iii.org/api/v1/webhooks/2/messages?&page=1",
    "last": "https://demo.firefly-iii.org/api/v1/webhooks/2/messages?&page=1"
  }
}
```
I would probably expect to see messages in this output after deleting a transaction.

### Additional info

Thankyou!

**Comment by JC5** [comment]
Thanks for letting me know, I'll check it out as well later this week :+1:
