### ISSUE TITLE
Preferences links to broken page with danish locale

### ISSUE THREAD

**Issue by VortexDK** [firefly-iii/firefly-iii#6595]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Firefly III is set to danish locale, and most of interface is translated very well.
Clicking on the "indstillinger" (settings) -> preferences (untranslated) leads to broken page with this information:
file_get_contents(/var/www/html/resources/lang/da_DK/locales.json): Failed to open stream: No such file or directory 

I run both firefly and mariadb as docker containers

### Expected behaviour

Open the preference page in either danish or english

### Debug information

Debug information generated at 2022-11-02 18:45:41 Europe/Copenhagen for Firefly III version **5.7.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.14 |
| Firefly III API | 1.5.6 |
| Build | 286, 18-10-2022 21:16:12 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Copenhagen |
| Browser TZ | Europe/Copenhagen |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-11-01 00:00:00 |
| Session end | 2022-11-30 23:59:59 |
| Session first | 2022-10-31 16:37:16 |
| User ID | 1 |
| User language | da_DK |
| User locale | da_DK |
| Attempt at "da_DK.utf8" | 'da_DK.utf8' |
| Attempt at "da_DK.UTF-8" | 'da_DK.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0 |

### Steps to reproduce

From dashboard click settings -> preferences

### Additional info

I am currenlty trying to setup firefly import tool, but I am not able to make it connect to firelfy III, the error I get from the import is this:
cURL error 7: Failed to connect to localhost port 90: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:90/api/v1/about

my docker compose file:
version: '3.3'

networks:
  fireflyIII:

volumes:
  firefly_iii_upload:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/nick/Data/Firefly_III_Docker/firefly_upload

  firefly_iii_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/nick/Data/Firefly_III_Docker/firefly_db

services:

  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 90:8080
    networks:
      - fireflyIII
    depends_on:
      - mariadb

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: fireflyiiidb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=***************************
      - TZ=Europe/copenhagen
      - MYSQL_DATABASE=firefly
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=*******************
    volumes:
      - firefly_iii_db:/config
    networks:
      - fireflyIII
    ports:
      - 3306:3306
    restart: unless-stopped

  fidi:
    image: fireflyiii/data-importer:latest
    restart: always
    env_file: .fidi.env
    networks:
      - fireflyIII
    ports:
      - 91:8080
    depends_on:
      - app

**Comment by JC5** [comment]
Ah nice find. I'll pick it up for the next release 👍

**Comment by VortexDK** [comment]
thank you very much for the quick reply, I will look forward to it.
