### ISSUE TITLE
Transaction links not visible in /transactions/create/*

### ISSUE THREAD

**Issue by bdeshi** [firefly-iii/firefly-iii#6596]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Transaction link fields are not visible when I try to create a new transaction. I do have multiple transaction links configured.

This is affecting the demo site too, as the screenshots show.

![image](https://user-images.githubusercontent.com/3525376/199763836-c73ff515-6b77-4c31-a078-58d86b1973e6.png)
![image](https://user-images.githubusercontent.com/3525376/199763814-02b6efe5-5994-4dcc-8206-c5788dedff8c.png)

### Expected behaviour

Any available link types should be available when creating a new transaction.

### Debug information

Debug information generated at 2022-11-03 21:30:33 Asia/Dhaka for Firefly III version **5.7.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.15 |
| Firefly III API | 1.5.6 |
| Build | 298, 02-11-2022 05:00:04 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Asia/Dhaka |
| Browser TZ | Asia/Dhaka |
| App environment | production |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-10-01 00:00:00 |
| Session end | 2022-12-31 00:00:00 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0 |

### Additional info

<sup>a sidenote: the issue creation requirement "it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)" and its linked page say two opposite things, which one is it? 🤔</sup>

**Comment by JC5** [comment]
An option to edit them directly will be included in the new layout, for the time being the button indeed does nothing. I'll make sure the page is edited as well 😉
