### ISSUE TITLE
Edit existing split transaction's source

### ISSUE THREAD

**Issue by sasyor** [firefly-iii/firefly-iii#6597]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After editing a split transaction's Source account, the N+1 split transactions' Source account & currency won't work properly.

### Expected behaviour

N+1 split transactions' Source account & currency should update properly.

### Debug information

Debug information generated at 2022-11-03 21:45:43 Europe/Budapest for Firefly III version **5.7.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.15 |
| Firefly III API | 1.5.6 |
| Build | 298, 02-11-2022 05:00:04 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Budapest |
| Browser TZ | Europe/Budapest |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2019-06-02 00:00:00 |
| Session end | 2019-07-31 00:00:00 |
| Session first | 2022-11-03 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0 |

### Steps to reproduce

1. Create a split transaction with EUR:
![image](https://user-images.githubusercontent.com/66509092/199830594-bcab6e12-9727-45db-bbed-d4c96b935f7a.png)

2. The Expenses page will properly show it:
![image](https://user-images.githubusercontent.com/66509092/199830760-8271adfb-bcd5-48d3-a9f1-124bc64163d9.png)

3. Edit the split transaction:
  3.1. Change the Source account to a different currency (e.g. HUF)
  3.2. The N+1 split transactions' Source account won't change, so I clicked on the trash icon
  3.3. I filled out the currency change
  3.4. Save changes
![image](https://user-images.githubusercontent.com/66509092/199830825-26dd28ff-582b-408d-b571-6b5ca293744c.png)

4. The Expenses page shows that something is not right:
![image](https://user-images.githubusercontent.com/66509092/199831215-c6091ac3-bf27-4ca1-97f7-b872deb3b9fb.png)

**Comment by JC5** [comment]
Works fine for me?

**Comment by JC5** [comment]
I see what you mean! I'll check it out. Let me clear out a misconception first:

- Changing the currency of the account will not change the currency of the transactions.

**Comment by JC5** [comment]
Fixed. It's a system fix only, the form may still show the wrong currency. I'm working on a new layout.
