### ISSUE TITLE
Transfer between Asset accounts are counted twice

### ISSUE THREAD

**Issue by blacksd** [firefly-iii/firefly-iii#6604]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have two Asset Accounts, one personal and one shared. If I transfer money from the personal to the shared, I'll get two transactions:
* On the **personal** account, I'll have a withdrawal line `MONEY TRANSFER TO shared REF. some reason`
* On the **shared** account, I'll see a deposit line `MONEY TRANSFER FROM personal REF. some reason` 

Now, if I set the correct source and destination parameters and classify both as a transfer operation, in the end, they will be identical and I'll see a duplicate amount in every aggregation.

I tried linking the two transactions, but - as the message explained - other than tracking the link itself the count still stays doubled.

### Expected behaviour

I would like the system to recognize them as part of the same transaction. I'd like also to avoid deleting one of the two transactions because that will be re-imported during the next cycle. 

### Debug information

Debug information generated at 2022-11-05 20:27:34 Europe/Rome for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | 255, 11-09-2022 07:30:27 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Rome |
| Browser TZ | Europe/Rome |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-11-01 00:00:00 |
| Session end | 2022-11-30 00:00:00 |
| Session first | 2022-01-03 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 |

### Steps to reproduce

I think the issue is pretty self-explainatory, but
1. Create a withdrawal of 100$ in a personal asset account A related to a transfer to B
2. Create a deposit of 100$ in a shared asset account B related to the transfer from A
3. Convert both to a transfer
4. See that the transfer aggregated count for the period is 200$ (should be 100$)

### Additional info

Could this be addressed by leveraging some property from the transaction link?

**Comment by JC5** [comment]
> I'd like also to avoid deleting one of the two transactions because that will be re-imported during the next cycle.

It will not be imported twice, because deleted transactions are also checked when searching for duplicates (for this very reason)

Are you creating these transactions yourself or are you importing them?

**Comment by blacksd** [comment]
> It will not be imported twice, because deleted transactions are also checked

That is very neat, hats off for this simple but very effective trick🙇🏻

I'm importing transactions from Nordigen, but to get back more than 90 days I have to resort to CSV.

If you don't have time to address this, as a workaround I'll choose a standard (e.g. convert a transfer from the source account) and delete the matching incoming transaction. I wanted to raise this issue to gather feedback if any other user fell into the same case.

**Comment by florian-guillemard** [comment]
Hi,
I try to import from Nordigen 3 accounts and transfers between them are not detected because I use the "externe-id".
If i don't use "externe-id", when I auto-import, it will not detect double items.
I think I'm in trouble 😅

I don't understand your solution about "deleted ones"... 

Can you explain your workaround ?

NB : For starter, I will import CSV files too :)

**Comment by florian-guillemard** [comment]
@blacksd and @JC5 , can you explain ?

I really want to use Firefly and the auto-importer, but this "bug" with transfers counted twice is really annoying :( 

Thanks for your help,
