### ISSUE TITLE
Asset account that have been set to 'inactive' won't show up in the dashboard after being reset to 'active' 

### ISSUE THREAD

**Issue by pnnylss** [firefly-iii/firefly-iii#6607]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If an asset account is set to 'inactive' (eg. by unchecking the 'Active' flag found in Asset account -> edit), it disappears from the dashboard (graphs and account list) and that's ok;

When that same account is then reset to an 'active' state, it doesn't reappear in the dashboard (both graphs andaccount list);

### Expected behaviour

When an account is reset to an 'active' state from an 'inactive' one, it should be displayed in the dashboard (both graphs and account list);

### Debug information

Debug information generated at 2022-11-06 00:03:21 Europe/Amsterdam for Firefly III version **5.7.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.15 |
| Firefly III API | 1.5.6 |
| Build | (unknown), (unknown) |
| DB version | 18 (exp. 18) |
| PHP | `8.0.24` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Rome |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-11-01 00:00:00 |
| Session end | 2022-11-30 00:00:00 |
| Session first | 2022-08-25 00:00:00 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Go to 'asset account' and select 'edit' on an active account with funds in it
2. Uncheck the 'Active' flag and save
3. Go to the dashboard and look at the graph and the list: the 'inactive' account is gone
4. Go back to 'asset account' and select '[You have 1 inactive (archived) account, which you can view on this separate page.]'
5. Select 'edit' on the previously deactivated account
6. Set it to 'active' and save
7. Go to the dashboard and look at the graph and the list: the reactivated account is still missing

### Additional info

Only appereances of the dashboard appear affected, the 'Net worth' box shows the correct amount and so does the 'balance' box.

I've been able to reproduce it on the demo site.

I'm running a LAMP server on Debian 11.

Restarting the service nor the machine brought back the account to the dashboard.

**Comment by JC5** [comment]
Not a bug. Add them again in your preferences.

**Comment by pnnylss** [comment]
Thank you,

Sorry for the false flag, didn't see anything related in the documentation
