### ISSUE TITLE
Nordigen Import - allow user to choose valueDate or bookingDate as transaction date

### ISSUE THREAD

**Issue by finfando** [firefly-iii/firefly-iii#6609]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

After fixing #5311 Firefly III now selects `bookingDate` as a default date. In my case both dates are always included, but it is the `valueDate` which is the date the money was actually spent.

### Solution

It would be great if the user could select in the config form before the import which date (valueDate or bookingDate) is the one that data importer is supposed to use.

**Comment by JC5** [comment]
I'm sticking to the `bookingDate`, with the `valueDate` as a backup. This will not be an option.
