### ISSUE TITLE
has_attachments:true

### ISSUE THREAD

**Issue by sir-scanda** [firefly-iii/firefly-iii#6610]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I removed some attachments form inside my records. Still "has_attachments:true" shows all documents contains attachments including those with deleted ones. 

### Expected behaviour

Fix attachments tag/marker form database (probably)

### Debug information

???

### Steps to reproduce

1. add attachment
2. has_attachments:true - shows record
3. delete attachment
4. has_attachments:true - still shows record

**Comment by JC5** [comment]
Nice find, will be fixwed :+1:
