### ISSUE TITLE
Warranty expiration

### ISSUE THREAD

**Issue by sir-scanda** [firefly-iii/firefly-iii#6611]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be nice to have FIELD with warranty time (i.e. 2 years) and serach command to SHOW EXPIRED/NOT EXPIRED PRODUCTS. (only for those which has that field filled/checked). Also add EXPIRATION column. :)

### Solution

Solution adds Warranty functionality ie. to home devices

**Comment by JC5** [comment]
For that you'll need a product application, not a finance application. However, you could use one of the optional date fields?

**Comment by sir-scanda** [comment]
Hi. Thanks. I'm aware of that. I've tried to do that but field name/type cant be edited/changed (ie. warranty end date).. and how can i search by that filed?

However - FF3 is the best solution I've tested. Most important is - os independent.. I use MacOS, Windows, Linux and have no problem with using ... big +. Search could be mede simpler (ie. pull down list with more common names - show expenses from ... to ... etc.)

**Comment by JC5** [comment]
No you can't change the name, you'll have to learn to live with that. To search, use the regular date search functions.

* https://demo.firefly-iii.org/search?search=due_date_before%3A2022-01-01&go=
* https://demo.firefly-iii.org/search?search=due_date_before%3Atoday&go=

https://docs.firefly-iii.org/firefly-iii/pages-and-features/search/#the-date

**Comment by sir-scanda** [comment]
Ok. Will do that. Thanks. Wysłane z iPhone'aWiadomość napisana przez James Cole ***@***.***> w dniu 06.11.2022, o godz. 19:07:﻿
No you can't change the name, you'll have to learn to live with that. To search, use the regular date search functions.

https://demo.firefly-iii.org/search?search=due_date_before%3A2022-01-01&go=
https://demo.firefly-iii.org/search?search=due_date_before%3Atoday&go=

https://docs.firefly-iii.org/firefly-iii/pages-and-features/search/#the-date
