### ISSUE TITLE
chinese character become unreadable in export data

### ISSUE THREAD

**Issue by dongdaming1966** [firefly-iii/firefly-iii#6612]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

chinese character become unreadable in export data.
![Uploading image.png…]()

### Expected behaviour

export the data as same as seen in the website

### Debug information

...

**Comment by JC5** [comment]
So, this happens to you but it does not happen on the demo site?

**Comment by dongdaming1966** [comment]
it's same on the demo site.
i just add a new record
![image](https://user-images.githubusercontent.com/13404168/200299801-6846abd0-ea30-41f6-ad7f-77c00a5b6a82.png)

when i export the data i got
![image](https://user-images.githubusercontent.com/13404168/200299686-741b1e48-7be2-4a84-b9d2-d159fafda9d8.png)

**Comment by JC5** [comment]
In which program are you loading the data? The data is exported as UTF-8, you may have to ensure it is exported correctly.

**Comment by dongdaming1966** [comment]
i am using excel.  the problem is solved after convert into ANSI. thank you for help.
