### ISSUE TITLE
Add optional/configurable "Import data" option in Firefly menu

### ISSUE THREAD

**Issue by SamBouwer** [firefly-iii/firefly-iii#6618]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to have a confgurable shortcut added in the Firefly III menu to easily access the importer.

Mockup/example:

![image](https://user-images.githubusercontent.com/6918900/200420437-323dd7c6-fb79-47f6-b0ab-705e11b08a23.png)

### Solution

A configuration item could be added to allow the user to turn on this shortcut, and provide a URL where the importer is hosted 
(for example http://localhost:port or https://fidi.fire.fly), for example under Options > Preferences > Home screen:

![image](https://user-images.githubusercontent.com/6918900/200420795-a629c52c-26f0-4c88-959c-1b2eb81b15a9.png)

### What are alternatives?

Make a shortcut in your browser, use the history option, or just remember where it is hosted.

### Additional context

Let's be honest, clicking a menu option is easier to remember the URL ;)

**Comment by JC5** [comment]
> Make a shortcut in your browser, use the history option, or just remember where it is hosted.

This is a great suggestion, but this will have to do I'm afraid.
