### ISSUE TITLE
export tag#20 error

### ISSUE THREAD

**Issue by henrytrager** [firefly-iii/firefly-iii#662]
when I try to export data with start date = 01-Jan-2016, end date 06-Jun-2017
I get the following error message in the log:
[2017-06-05 22:48:47] production.ERROR: Cannot find tag #20  

Additional info if it can help: server time is [2017-06-05 22:48:47], real time is [2017-06-**06** 01:28:47]

when I change the end date to **05**-Jun-2017 it works perfectly

**Comment by JC5** [comment]
Alright, first update the server so the date and time is correct.

I've updated the error message, because it isn't really an error, just a notification. So tell me, is anything not working or do you just get the message?

**Comment by henrytrager** [comment]
It is not working, I get the message "The export failed. Please check the log files to find out why."

I can reproduce this behavior consistently now: it happens when end date > today.

**Comment by JC5** [comment]
Could you post the relevant log entry?

**Comment by JC5** [comment]
Found it! It's a normal error just not properly displayed to the user.

**Comment by henrytrager** [comment]
ok.
The log message was:
[2017-06-06 16:33:08] production.ERROR: Cannot find tag #26  
[2017-06-06 16:40:59] production.ERROR: Cannot find tag #23

**Comment by JC5** [comment]
A new release is on it's way so I'm closing this issue :)
