### ISSUE TITLE
Multiple Instances of Total Available Budget in Same Currency

### ISSUE THREAD

**Issue by derekprovance** [firefly-iii/firefly-iii#6622]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It'd be useful to create multiple budgets in the same currency. There is already the ability to set multiple budgets in different currencies, but there are use cases where setting multiple budgets in the same currency could be extremely helpful.

### Solution

An example would be if I had a monthly budget, and an investment budget that I'd like to keep track of. With the current system, the investment budget causes the already spent statistics to be skewed and unhelpful at tracking what was already spent.

### What are alternatives?

I'm not aware of any alternatives

**Comment by JC5** [comment]
That's a great idea, but there will only be one "total available amount" per period per currency.

**Comment by JC5** [comment]
The total budgeted amount is now automatically calculated, so this feature will not be implemented. Sorry about that.
