### ISSUE TITLE
Option to keep fields when creating transactions with form reset

### ISSUE THREAD

**Issue by JadElClemens** [firefly-iii/firefly-iii#6630]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like there to be an option, when serially creating transactions with the "Reset form after submission" option checked (both options under "Submission" are checked), to select certain fields that should not be reset when returning to the create transaction form.

### Solution

For serially inputting a bunch of transactions, there's often some element in common between transactions - most often, I'm looking through my accounts one at a time, so the source account most times will stay constant for dozens of transactions. The next most frequent would probably be the date, as the usual case is that I'm catching up and may have multiple transactions occur on the same date. It would be nice if I could optionally check some checkbox to keep these fields while all others are cleared when I'm finished creating a transaction.

### What are alternatives?

There are two:
1. Reset all fields and re-enter all data, including what is common with the previous transaction (often quicker)
2. Do not reset fields and clear/re-enter data that is _not_ in common with the previous transaction (often slower)

### Additional context

Some background: I don't use any kind of importer/API sync (if those exist) with Firefly - I always manually enter transactions as they happen or, if I've been lazy, go through bank/credit card statements line by line and input transactions that way. If I've been extra lazy, like right now, I have some four months' worth of transactions to review across half a dozen accounts.

For all of these transactions, I log in to one bank/credit card account and go through my accounts one-by-one, transaction-by-transaction, so for a bunch of transactions at a time I'll have the same source or destination account. Less often, but still very frequently, I have a bunch of transactions from the same day. Less often still, I tend to schedule a few credit card payments for the same day, so I might have a category or tags in common between those few transfers.

For the record - and I won't write up an issue for this one, because I think this may be the only use case - in my workflow, this feature would work really well in tandem with a swap source/destination account button so I can use this with both expenses/revenue (for bank accounts) or expenses/payments (for credit cards) ;)

**Comment by JC5** [comment]
Hey, thanks for a great suggestion. I know your pain, but I'm not going to build something to counter it. It's just too much work and maintenance compared to the speedup.
