### ISSUE TITLE
Ability to let withdrawals deduct directly from piggy banks

### ISSUE THREAD

**Issue by niklas152** [firefly-iii/firefly-iii#6631]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello James,

I have come across something which would be incredibly helpful to me (and hopefully others as well).
At the moment, I am using many (like, really a lot, 30+) "virtual" sub-accounts to keep track of regular, yet not monthly payments (i.e., quarterly insurances, yearly tickets, maintenance, etc.). I am using a single account for each to keep track of the progress and still have a stable per-month cash flow.
This, however, results in many many accounts. Now I thought about using piggy banks and a single account instead, where for each payment target there is one piggy bank tracking the savings progress for monthly incoming transfers (this already works). However, for that to actually work I would need the eventual withdrawal to be able to deduct its amount from the piggy bank, thus resetting it for the next cycle.

### Solution

Allowing withdrawals to have an assigned piggy bank (as transfers do), from which the withdrawal amount is then deducted.

### What are alternatives?

Manulllay creating a transfer away from the piggy bank account, use that to deduct from the piggy bank and have the actual withdrawal happen from that extra account instead.

### Additional context

While this has partly been [discussed ](https://github.com/firefly-iii/firefly-iii/discussions/4765) in the forum before, the usecase described there was a different one, so I hope this new context might be more appealing to you.

Also, again thank you for this amayzing tool :)

**Comment by JC5** [comment]
Not a bad idea, I'll see what I can do!

**Comment by AdalLS** [comment]
Could it also be possible to assign transfers to a piggy bank to a budget?

For example, I'm using the budget to decide how much money I'm able to save each month which will go in the piggy bank. However, since it is a transfer, it is not being shown in the budget overview and that amount remains marked as available.

**Comment by JC5** [comment]
No. Please don't hijack issues for unrelated questions.
