### ISSUE TITLE
Uses wrong value on transfer from different currency

### ISSUE THREAD

**Issue by sTiKyt** [firefly-iii/firefly-iii#6646]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Basically, I have liability saying I owe 80 UAH to someone, I'd like to pay this liability using EUR, so when I'm paying I'm also specifying how much it is in currency of debt, but it still takes EUR value even tho liability is in UAH, and I've specified UAH currency amount during transfer

### Expected behaviour

Instead of becoming 0 "Amount Due" became 77.87, even tho logically it's supposed to subtract UAH from UAH if i've specified it, it substracted EUR amount from UAH liability
![image](https://user-images.githubusercontent.com/35602029/201713955-ff40e1ed-fff0-4430-b4cc-0368dea9fd24.png)

### Debug information

Not required

### Steps to reproduce

So, this is transaction I've made: (never mind red color, made some non-related typo before):
![image](https://user-images.githubusercontent.com/35602029/201713550-87a402ff-cf93-4513-8f94-00ee15f387e1.png)

**Comment by JC5** [comment]
Ah nice find, I'll check it out!

**Comment by JC5** [comment]
This will be fixed in the next release. To recalculate your liabilities, edit them, change nothing, and submit the form.
