### ISSUE TITLE
GBP transactions appear as EUR in a GBP asset account

### ISSUE THREAD

**Issue by henrytrager** [firefly-iii/firefly-iii#665]
I have created a GBP current account and initiated the balance.

Somehow all imported transactions appear in EUR but the current balance shows in GBP and it is the correct one.

For information, my default currency is EUR.

**Comment by JC5** [comment]
Yes, until the next release this will keep happening, the display of currency information isn't consistent yet.

**Comment by JC5** [comment]
This should be fixed!
