### ISSUE TITLE
Debt functional requirements

### ISSUE THREAD

**Issue by markolzc** [firefly-iii/firefly-iii#6667]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

In the debt area, it's convenient if you can customize the debt direction

### Solution

It is possible to customize this debt direction option

### What are alternatives?

No

### Additional context

![image](https://user-images.githubusercontent.com/20659384/203210621-d4e9ff9e-22ce-4a2e-94eb-c763ad8e5a50.png)

**Comment by JC5** [comment]
What directions did you have in mind?

**Comment by markolzc** [comment]
I just want to be able to customize, rather than set the two items.
Not only show that I owe others, but others owe me.
I don't know. Do you know what I mean?
Ok, This is just my suggestion, thanks you feedback me

**Comment by markolzc** [comment]
![image](https://user-images.githubusercontent.com/20659384/203254912-eae5f391-0ed6-45f1-bd91-ea8d6758d882.png)
It could be in English, but I just want to be able to customize the options directory so that I can correspond to the correct description.

**Comment by JC5** [comment]
>  Not only show that I owe others, but others owe me.

"I am owed this debt" is the option you want.
