### ISSUE TITLE
Discounts

### ISSUE THREAD

**Issue by Solverz-0** [firefly-iii/firefly-iii#6669]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

**Feature -**
Add discount value field in a transaction

### Solution

**Reason -**
If you were to have a discount for a bill for some reason, then it would be good to see this in the transaction in case future you wonders why previous the bill transaction was less than it was supposed to be and does not panic thinking you have underpaid a certain month. :)

I have seen similar request was #3089 but I wanted to give this reasoning with bills tracking in mind.

### What are alternatives?

Keep track in notes but this gets *messy* sadly.

**Comment by Solverz-0** [comment]
> Mmmm, I don't see how adding it anywhere else would get less messy.

Sorry for the really late reply here.

So another example I have ran into for this is if you have two different bills but from the same company and you want to keep track of each bill separately in firefly and therefore use split transactions for this.

Bill A: 20
Bill B: 80
Discount: 60
Total charged from bank account: 40

Now how would I show the total cost for each bill in a split transaction?
I could not as even if I halved the discount and applied it to each bill, Bill A would be become neagtive, so having a discount field which applies to the whole split transaction would resolve this from my thought process.

Hope this makes sense 😄

**Comment by JC5** [comment]
In cases like these, I wouldn't "overthink" tracking and logging each single property of a transaction, especially in cases like these. For both you and me, it's a lot easier to simply but the details in the notes and be done with it.

There is an item on the backlog for custom fields, where stuff like this could be stored in the future. But for now, I'm closing this one. Thanks for the suggestion!
