### ISSUE TITLE
Sort Transactions by Headings

### ISSUE THREAD

**Issue by BlueTooth4269** [firefly-iii/firefly-iii#6673]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like for the transactions to be sortable by the headings (Amount, Name, Date, Destination Account, Category). 

### Solution

<img width="1203" alt="grafik" src="https://user-images.githubusercontent.com/17643409/203991103-706c8178-0239-455d-ae6d-18dbcf1aefca.png">

Just to make the table sortable. Especially sorting by amount is a useful feature.

**Comment by JC5** [comment]
See this ticket: https://github.com/firefly-iii/firefly-iii/issues/6304
