### ISSUE TITLE
Duplicate piggy bank withdrawal

### ISSUE THREAD

**Issue by AdalLS** [firefly-iii/firefly-iii#6695]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have two rules: 

1) one that checks transfers to an account associated with a piggy bank. When the transfer transaction is created it adds the amount to the piggy bank.

2) one that checks withdrawals from said accounts, if a note contains a specific keywords, it records that as a withdrawal from the piggy bank

However, the result is that it duplicates the withdrawals. Those with a link correctly go to the corresponding transaction. But as you can see from the picture below, it creates further transactions dated today which do not link to anything.

![image](https://user-images.githubusercontent.com/44591506/205442816-d74a8553-dab6-4225-8958-5c12be93be78.png)

### Expected behaviour

The system should correctly detect the deposits and the withdrawals without creating duplicate transactions.

### Debug information

Debug information generated at 2022-12-03 13:17:48 UTC for Firefly III version **5.7.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.15 |
| Firefly III API | 1.5.6 |
| Build | 298, 02-11-2022 05:00:04 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-12-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2017-06-13 00:00:00 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Create the two rules as described above.
2. Create transactions that would trigger the two rules.
3. Run those rules.
4. Check the piggy bank.

### Additional info

I have tried multiple times to delete the piggy bank and rerun the rules, but I always end up with duplicate transactions.

**Comment by JC5** [comment]
I see no entries in that list are duplicated. Is the amount that ends up in the piggy bank wrong?

**Comment by AdalLS** [comment]
Well, the first two withdrawals dated 3 December are exact duplicates of those on the 28/11 and 29/10.

There were no withdrawals occurring on 3 Dec from the piggy bank. Indeed there is no link, the date appears in black. The true withdrawals are those in blue.

**Comment by JC5** [comment]
How were the original transactions created?

**Comment by AdalLS** [comment]
They appear if Imported from the bank's csv file as well as if I run the corresponding rule manually (after deleting the piggy bank).

**Comment by JC5** [comment]
I'm not sure I understand exactly. Do you have a full set of logs for one of these imports?

**Comment by AdalLS** [comment]
Where can I find these logs?

I also am not sure how to explain it more concisely. It is very simple, the imported transactions are only the bottom four.  Those really wxiat. You can clearly see that those have blue links for the dates. If I click on them I go to the corresponding transactions.

However, after importing it also duplicated the last two withdrawals. You can clearly see that the amounts are the exact same. You should also be able to see that the respective dates are printed in black. They don't have a link and the date was the date on which I imported the data. 

But there are no real transactions that happened on that date. Indeed, they have no links.

**Comment by JC5** [comment]
You talk about two different things but you seem to call both of them "transactions". That's a little confusing.

Your logs can be found either in `./storage/logs` or in the output of the Docker container.

**Comment by AdalLS** [comment]
Well aren't both deposits and withdrawals, "transactions" in a general sense?

Anyway,  I have deleted the piggy bank, recreated it, and ran the two rules concerned and again it duplicated the two withdrawals with today's date. The logs starting just before I ran the rules are [pasted here](https://pastebin.com/ezfjJizK).

Here are the rules:

![image](https://user-images.githubusercontent.com/44591506/206854145-3716fdca-e251-4595-be6d-a836528cb6b0.png)
the above detects deposits to piggy bank and associates them to the correct one

![image](https://user-images.githubusercontent.com/44591506/206854230-61761a6b-4a67-48b7-b9d6-099661c02b53.png)
the above detects outgoing transfers from the account linked to the piggy bank.

Results after running these two rules above in succession:

![image](https://user-images.githubusercontent.com/44591506/206854262-f3ed3e81-d412-4036-aa02-2015084cd841.png)

As you see it again duplicated withdrawals using today's date. I would say that this is unlikely to be something that happens on import, but perhaps it is related to the actions ran after the rule is triggered. Hope this helps.

**Comment by JC5** [comment]
Thanks for the extra screenshots. Unfortunately the logs don't contain what I need to know. I'll see what I can do!

**Comment by JC5** [comment]
This should be fixed in the next release. :+1:

**Comment by AdalLS** [comment]
Hi, and thanks for releasing the new version. I have just tried to recreate the piggy bank and re-run the rules, but however this time it gives an error:

`
FireflyIII\TransactionRules\Actions\UpdatePiggybank::removeAmount(): Argument #1 ($piggyBank) must be of type FireflyIII\Models\PiggyBank, array given, called in /var/www/html/app/TransactionRules/Actions/UpdatePiggybank.php on line 91
`

Is there another way to link transactions to a piggy bank? When I edit the individual transaction, I don't see an option to do it there.

**Comment by JC5** [comment]
Could you open a new ticket please?
