### ISSUE TITLE
Bad HTML formatting

### ISSUE THREAD

**Issue by ArnyminerZ** [firefly-iii/firefly-iii#6700]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The HTML code doesn't close empty tags.

### Expected behaviour

For example, on the head of the first registration page, this is generated:
```html
<base href="http://localhost:8080/">
```
this should be the correct tag:
```html
<base href="http://localhost:8080/" />
```

### Debug information

.

### Steps to reproduce

1. Start Firefly
2. `curl http://localhost/register`
3. The source code is not valid.

**Comment by JC5** [comment]
This is valid HTML.
