### ISSUE TITLE
Cannot change opening balance - IBAN already in use

### ISSUE THREAD

**Issue by nebula2** [firefly-iii/firefly-iii#6705]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I receive an error when I try to change the opening balance:
![image](https://user-images.githubusercontent.com/5841525/206679695-0fe6f75d-4077-44c4-a3c3-4b1a3b121820.png)

I checked the database and I do have the iban twice in my db with different account types

![image](https://user-images.githubusercontent.com/5841525/206681373-6cdfdace-12dd-43ac-8311-7704b025263c.png)

But one is an asset account and the other is something else. 

### Expected behaviour

1. Did not change iban, so the call should at least go through and let me change the balance
2. Is it correct, that the iban should be unique across all accounts no matter what their account_type_id is?

### Debug information

Debug information generated at 2022-12-09 11:32:04 Europe/Berlin for Firefly III version **5.7.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.15 |
| Firefly III API | 1.5.6 |
| Build | 298, 02-11-2022 05:00:04 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-12-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2017-01-01 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.42 |

### Steps to reproduce

1. Create two accounts with the same iban. First the asset account and the other (revenue or expense).
2. Try updating starting balance on asset account

### Additional info

Workaround: Temporarily change the iban of the other account. Did that directly in db

**Comment by JC5** [comment]
> 1. Create two accounts with the same iban. First the asset account and the other (revenue or expense).

The system won't accept a second anything account when there is an *asset* account with that IBAN already. At least, I can't reproduce this on the demo site with the latest version.

Since I don't know how the second account was created (with ID 149) I can't debug this, but I'll see what I can do otherwise.

**Comment by nebula2** [comment]
> The system won't accept a second anything account when there is an _asset_ account with that IBAN already. At least, I can't reproduce this on the demo site with the latest version.
> 
> Since I don't know how the second account was created (with ID 149) I can't debug this, but I'll see what I can do otherwise.

Jeah, somewhere in the last two years this must have happened.
The duplicate revenue account came from csv importer back in the days.

**Comment by JC5** [comment]
>  The duplicate revenue account came from csv importer back in the days.

That makes sense, the check hasn't always been buggy. 

As such, I'm afraid I can't fix this. It's a bit of a rare thing to be happening, and I'd rather "force" the user to fix this than skipping over it once the account is saved.

**Comment by nebula2** [comment]
Okay, then I'll need to "migrate" the transactions to then delete the duplicate revenue/ expense account. 

It is correct, that the IBAN must be unique, no matter what the account type may be.

This works for me. Thank you for your time!

**Comment by JC5** [comment]
> It is correct, that the IBAN must be unique, no matter what the account type may be.

As a final comment: expense accounts and revenue accounts may share the same IBAN. For example, a store like Amazon may have both a revenue and an expense account (with the same name, so also the same IBAN).

Once an asset account (or liability) "takes" an IBAN, it cannot be used by other account types.
