### ISSUE TITLE
Custom ordering of liabilities does not persist

### ISSUE THREAD

**Issue by paulcalabro** [firefly-iii/firefly-iii#6709]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

You can arrange liabilities in any order you like by dragging and dropping them. You can also do the same with asset accounts (and maybe other accounts as well). If you refresh the page, however, the original ordering is restored. This does not appear to be the case with assets (this works as expected).

### Expected behaviour

If I sort the liabilities, I would expect that ordering to persist across page refreshes as well as any other places in the UI where it's appropriate. I noticed that sorting the asset accounts, for example, also affects the ordering on those accounts on the main page, which is nice.

### Debug information

Debug information generated at 2022-12-10 11:22:58 America/Phoenix for Firefly III version **5.7.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.15 |
| Firefly III API | 1.5.6 |
| Build | 298, 02-11-2022 05:00:04 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Phoenix |
| Browser TZ | America/Phoenix |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `192.168.128.0/16` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-12-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2014-09-15 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0 |

### Steps to reproduce

1. Click "Accounts" -> "Liabilities"
2. Sort the list
3. Refresh the page
4. Observe the original ordering is restored

**Comment by JC5** [comment]
Thanks for letting me know. I'm not going to fix this. I'm working on a new layout where this will be fixed.
