### ISSUE TITLE
Different currency values imported into main currency

### ISSUE THREAD

**Issue by Janhouse** [firefly-iii/firefly-iii#6710]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Using the import tool to import data for multi-currency accounts (tested with Nordigen) result in incorrectly imported entries. It takes the currency value and puts it in the default currency field, leaving the actual currency field empty. This results in broken - hard to track entries.

### Expected behaviour

It should handle different currencies of the same account like different accounts, one for each currency.

Since that can be quite time consuming to implement at this point - I would suggest dropping those entries altogether and warn the user. It's better to not have them than break everything and be impossible to track afterwards.

### Debug information

No debug

**Comment by Janhouse** [comment]
Example:
10 000 NOK (Norwegian krone) get imported as 10 000 EUR into multi-currency
account. It should be imported as 10 000 NOK instead.

Understanding that currently it does not support multiple currencies for
the same account, it should drop them altogether. Or at least convert to
main account currency at some exchange rate (but that would also be
incorrect and very bad).

**Comment by JC5** [comment]
There are several solutions to this problem, and dropping transactions isn't one of them. The importer will warn you that this will happen, that's all I can do.
