### ISSUE TITLE
Incorrect graph in dashboard with multi currency asset accounts

### ISSUE THREAD

**Issue by adyanth** [firefly-iii/firefly-iii#6713]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Having asset accounts in multiple currencies mess up the graph in the dashboard.

### Expected behaviour

Either leave the non default currency asset account out from the graph or (more complex) show correct axis labels for the currencies

### Debug information

N/A

### Steps to reproduce

1. Add an asset account with some balance (say $1000) in the default currency
2. Add an asset account with some balance (say €5000)
3. See the graph in the homepage show that you have 5000$

### Additional info

Happens in the demo site as well.

PS: Is the 3rd point in the issue template worded wrong? Should I be checking the box it's definitely me, not you?

**Comment by JC5** [comment]
There are several tickets about this. Thanks for reporting. A fix will be part of the new layout.
