### ISSUE TITLE
Fast modification of Transactions

### ISSUE THREAD

**Issue by Bond246** [firefly-iii/firefly-iii#6717]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- I would like to see a function where is possible to define categories and budgets directly in transaction overview
- I personally import all my transactions via FinTS and every transaction that hasn't been modified by a rule needs to categoriezed manually 
- to open every transaction, changing the categorie/budget and save my changes is very boring

### Solution

- there might be two solutions

## 1. having a "modify" button in transaction overview
  - using that button all listed transactions get dropdowns to select/input the categorie, budget and description
  - to save the changes pressing the "modify"-button again
## 2. preselecting a transaction
  - selecting a transaction 
  - then it gets in modification-mode and thinks like categorie, budget and description can be edit

**Comment by JC5** [comment]
It's not explicitly mentioned but this is on my roadmap for the new layout, so let me refer you to that issue: https://github.com/firefly-iii/firefly-iii/issues/6304
