### ISSUE TITLE
Cloning Transfer Doesn't Populate Amount Field

### ISSUE THREAD

**Issue by dzaikos** [firefly-iii/firefly-iii#672]
As the title says. Issue begin in 4.4.2. Cloning deposits or withdrawals does populate the amount field, but transfers between accounts is always blank.

Can confirm the issue exists in 4.5.0.

**Comment by JC5** [comment]
You're right! I'm working on a fix right now.

**Comment by JC5** [comment]
A new release is on it's way so I'm closing this issue :)
