### ISSUE TITLE
Nordigen - withdrawals are with positive transaction amount

### ISSUE THREAD

**Issue by vladonemo** [firefly-iii/firefly-iii#6721]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Data exported via Nordigen API from my bank always have positive transaction amount event if the transaction is actually withdrawal. The transaction is then not imported and fails with error that destination_id and source_id are the same.

In the sample data below you can see the amount being positive for both, but the the creditor/debtor acounts are swapped:
```json
{
    "transactions": {
        "booked": [
            {
                "transactionId": "a97edcce-6b9b-4742-1b5a-ef36cc765650",
                "endToEndId": "Rezerva",
                "bookingDate": "2022-12-09",
                "valueDate": "2022-12-09",
                "transactionAmount": {
                    "amount": "580",
                    "currency": "EUR"
                },
                "creditorName": "anonymized",
                "creditorAccount": {
                    "iban": "SK6383605207004200008871",
                    "bban": "5207004200008871"
                },
                "debtorAccount": {
                    "iban": "SK4002000000004500004555"
                },
                "remittanceInformationUnstructured": "Rezerva",
                "bankTransactionCode": "1504",
                "internalTransactionId": "075e4573bafc7a48702601352b89ba2a"
            },
            {
                "transactionId": "a97edcce-6b89-8337-6998-1afc84f6983e",
                "endToEndId": "Sporenie",
                "bookingDate": "2022-12-09",
                "valueDate": "2022-12-09",
                "transactionAmount": {
                    "amount": "1000",
                    "currency": "EUR"
                },
                "creditorAccount": {
                    "iban": "SK4002000000004500004555"
                },
                "debtorName": "anonymized",
                "debtorAccount": {
                    "iban": "SK3009000000000500007617",
                    "bban": "576827617"
                },
                "remittanceInformationUnstructured": "Sporenie",
                "bankTransactionCode": "1520",
                "internalTransactionId": "1bd0d8ddd8440adac502b50b2f7c41db"
            }]
    }
} 
```

### Expected behaviour

The importer would rely on the account IDs (IBAN) when parsing a transaction, not only on the amount

### Debug information

Line #0:
(2)transactions.0.destination_id: Source and destination are the same. (original value: "17")
(2)transactions.0.destination_name: Source and destination are the same. (original value: "(not found)")

### Steps to reproduce

a

**Comment by JC5** [comment]
This is a problem with Nordigen and you'll have to take it up with them. I can't fix this from my side. They've said that withdrawals should be negative amounts. If they're not negative it's a bug on their side, not a thing the data importer has to fix.

**Comment by vladonemo** [comment]
Thanks for the hint. I contacted Nordigen, as suggested by you @JC5. It is in fact a known issue to them. The problem is at my bank side. And they keep ignoring their requests, sadly.

I do understand that in the ideal world the fix is done at bank API. On the other hand, the importer is not useful in my scenario. According to your response the only option I'm left with is to patch the importer myself locally. 

Perhaps it would be possible to add some sort of a flexibility to the importer (in a form of a configuration rule perhaps) to workaround such issues and let users bridge the period until issues are properly addressed?
