### ISSUE TITLE
Transfer from account in GBP to account in EUR

### ISSUE THREAD

**Issue by henrytrager** [firefly-iii/firefly-iii#673]
I try to create a transfer from an account in GBP to an account in EUR but it shows up as a EUR transfer (my default currency)

**Comment by JC5** [comment]
Which version of Firefly? And where does it show up as an EUR transfer?

**Comment by henrytrager** [comment]
I am running Version 4.4.3
It shows up as a EUR transfer in both accounts without taking into account the GBP amount specified

**Comment by JC5** [comment]
Ah yes, it will indeed. This has been fixed in the latest version. Check out the [demo site](https://firefly-iii.nder.be/) to see how it works.

**Comment by JC5** [comment]
Fixed!
