### ISSUE TITLE
Ability to pull current transactions from bank via banking api

### ISSUE THREAD

**Issue by ChristianPe** [firefly-iii/firefly-iii#674]
First of all, thanks a lot for this great project! I love to use it. The problem is I love it so much, that I dont want to use the lame web UI from my bank anymore. So I thought it might be pretty awesome to implement an API like Subsembly FinTS API (only for german banks and will be .net core rdy soon) and pull the transactions every night. The rules feature might be enhanced by an "write email" action and this project would get a nifty anti-fraud tool.
Would be really great to see!

**Comment by JC5** [comment]
I'm holding out for the PSD2 to stabilise. Then, it'll depend on how banks move forward. But yes, that is something that I wish to build. I'm not sure what you mean by "write email" but some kind of import reporting would be present, yes.

See also https://firefly-iii.github.io/requested-features.html
