### ISSUE TITLE
Error when a rule tries to add or remove an amount from a piggy bank

### ISSUE THREAD

**Issue by AdalLS** [firefly-iii/firefly-iii#6742]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Related to issue #6695, Firefly III returns an error when running a rule with an action that would case it to add or remove an amount from the piggy bank.

The error is 
`FireflyIII\TransactionRules\Actions\UpdatePiggybank::addAmount(): Argument #1 ($piggyBank) must be of type FireflyIII\Models\PiggyBank, array given, called in /var/www/html/app/TransactionRules/Actions/UpdatePiggybank.php on line 97`

and occurs also with `removeAmount()`

### Expected behaviour

I would expect the transferred amount to be correctly added or removed from the related piggy bank.

### Debug information

Debug information generated at 2022-12-25 21:07:35 UTC for Firefly III version **5.7.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.16 |
| Firefly III API | 1.5.6 |
| Build | 316, 25-12-2022 07:50:13 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-12-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2017-06-13 00:00:00 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Create a piggy bank.
2. Create a rule that identifies a transfer and add the action of linking it to a piggy bank.
3. Run the rule.

**Comment by JC5** [comment]
Thanks for the new issue, I'll pick it up asap, with the holiday season and all.
