### ISSUE TITLE
How to install from Git?

### ISSUE THREAD

**Issue by flow7** [firefly-iii/firefly-iii#675]
Hey, I've just found firefly and am very impressed.
I installed it right away (well, took me a while) using the [Installation guide here](https://firefly-iii.github.io/using-installing.html).
Now, I've realised that my version is now "only" 3.10.4, where the demo site runs on 4.5.

In the future I'd love to upgrade easily using git - therefore I wonder, how to best install firefly immediately from git?
Thanks

**Comment by JC5** [comment]
I am very glad you like it! 

If you followed the installation guide it should get you the latest version. However, if this fails, you can do the following:

* Go to the parent directory of firefly-iii. If it is in `/var/www/firefly-iii`, go to `/var/www`.
* Run this command to get the latest version from Git:
* `git clone https://github.com/firefly-iii/firefly-iii.git firefly-iii-updated`
* It will put the latest version in `/var/www/firefly-iii-updated`.
* Use these commands to copy your local config and data:
* `cp firefly-iii/.env firefly-iii-updated/.env`
* `cp firefly-iii/storage/upload/* firefly-iii-updated/storage/upload/`
* `cp firefly-iii/storage/export/* firefly-iii-updated/storage/export/`

Use these commands to upgrade the database and install dependencies:

* `cd firefly-iii-updated`
* `composer install --no-dev --no-scripts --no-suggest`
* `rm -rf bootstrap/cache/*`
* `php artisan migrate --env=production`
* `php artisan cache:clear`
* `php artisan firefly:upgrade-database`

This is all a bit tricky but it should work!

**Comment by flow7** [comment]
Thanks for your very precise response.

I've tried hard - but I failed somewhere on the way and have now in the meantime tried multiple times to just re-do the whole thing, on separate subdomains and what-not. Keep running into mysql errors - damn it ;) I'll get back, when I have more - and energy to try again!
thx
