### ISSUE TITLE
Add the possibility of repeating the operation every two weeks or twice a month

### ISSUE THREAD

**Issue by Gsyltc** [firefly-iii/firefly-iii#6758]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

In North America, operations are often performed twice a month or every two weeks.

For example: 
Example for every 15 days
Mortgage: 26 installments spread over the year with a frequency of every 2nd Monday (ex: Mon 02/01/2023, Mon 16/01/2023, Mon 30/01/2023)
Payroll can also follow the same cycle (26 payments every 2 weeks).

Example for 2 times a month:
An operation can also occur twice a month such as on the 1st of the month and on the 16th of the month.

### Solution

The solution would be to add 2 new repetitions 

1°) Every 15 days :
- We define the repetition every 15 days
- We select a day of repetition (Mon-Sun)

The application creates triggers for these days over the year

2°) 2 times per month:
- We define the repetition to 2 times per month
- We select two days in the month

The application creates triggers for these days over the year

### What are alternatives?

Without this solution, it is necessary to create 1 invoice for each deadline in the year

Thanks

### Additional context

![firefly](https://user-images.githubusercontent.com/20156293/209880798-6587a6f2-019e-46b3-ac58-9c810528536a.png)

**Comment by Gsyltc** [comment]
I finally understood what the "ignore" function was for.
It allows you to process the kind of scenarios you want.

No need to make application changes.

Suggestion: It would be good to add a comment for the field, or even a note in the documentation to explain how it works

Thanks

**Comment by JC5** [comment]
In the English version this field is called "skip". It's also in the documentation. I'm glad to see you found it :)
