### ISSUE TITLE
Regex Matching for Textual Fields in Automation Rules

### ISSUE THREAD

**Issue by iamrecursion** [firefly-iii/firefly-iii#6759]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

One thing that I've found myself wanting when getting set up with Firefly is the ability to regexmatch and regexreplace when creating automation rules. 

I would imagine it working as follows:

- For any textual field in triggers there would be "matches <regex>" that takes a regex as user input.
- For removing tags in rule actions, I would love to match by regex.

### Solution

More flexible triggering of rules for the automation engine.

### What are alternatives?

It would be possible to script such automations externally using the Firefly API, but this is perhaps an extremely difficult way to get the feature working!

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/
