### ISSUE TITLE
docker deployment not working

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#676]
When starting using docker-compose as described in the docs I get
```
firefly-app_1  | AH00534: apache2: Configuration error: No MPM loaded.
```

**Comment by JC5** [comment]
Pinging @crash7, @schoentoon and @elohmeier 👍

**Comment by crash7** [comment]
Will check later today.

@simonsmiley to see the error you just run docker-compose? any particular configuration?

**Comment by simonsmiley** [comment]
just docker-compose.  
I reverted to deploying it on my host using nginx. So I don't really need the issue to be fixed anymore. In case you can't replicate it, I'm fine with just closing it

**Comment by crash7** [comment]
Couldn't reproduce this, but found that the development instructions on https://firefly-iii.github.io/using-docker.html aren't working (probably the mysql:8 image isn't the right one). I will check near the end of the week.
