### ISSUE TITLE
Wrong category IDs in reports

### ISSUE THREAD

**Issue by toerb** [firefly-iii/firefly-iii#677]
Hey, I have just looked through my first reports.

The category is sorted by amount of spendings.
The IDs used for the category link and for the little info icon on the right is just the line number not the real category ID which it should be.

To clarify this: the first entry in the list always has https://domain/categories/show/0 as link which throws a 404.
The second has https://domain/categories/show/1 and so on.

You can reproduce this issue by viewing [the demo site](https://firefly-iii.nder.be/reports/default/1,32,2,3/currentMonthStart/currentMonthEnd) and looking for the Categories table.

Best regards
Tobias

**Comment by JC5** [comment]
Nice find! It has been fixed on the demo-site, and a release will follow soon :).

**Comment by toerb** [comment]
It is indeed fixed on the demo site.

Thank you very much for developing such a nice software!

**Comment by JC5** [comment]
You're very welcome!

A new release is on it's way so I'm closing this issue :)
