### ISSUE TITLE
Credit card expenses with cashback

### ISSUE THREAD

**Issue by Gsyltc** [firefly-iii/firefly-iii#6773]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hi,

I would like to suggest the possibility to add, in the rules, the possibility to allow the calculation and addition of cashback in piggy banks.

In North America, the majority of credit cards are associated with a cashback that is stored in a piggy bank on the card and can be retrieved at any time.
In Europe, some cards like Revolut also have this cashback system.

Problem :
I think that the solution would be to make treatments when the transaction is created and not directly associated with the credit card.
It often happens that cashbacks are associated with the type of expenditure, and depend on the agreements of banks.
Example:
2% for travel agencies, and groceries at Wallmart or IGA (Canada)
1% for all restaurants, carburant chez Total ou Esso mais pas les autres
0.5% cashback for all other expenses.

For Revolut, it's a % for transactions in Europe and 1% for international transactions (could be based on Geolocation for example). 

### Solution

Although the solution is quite complex, here are some tips.
It requires some modifications for credit card type accounts: 
1°) The possibility to associate a cashback piggy bank
- Create the piggy bank manually, and associate it in a field in the credit card account
- The credit card account field will automatically create the associated piggy bank if the field is filled in

2°) Create an action "Add cashback" (or the name you think is best)
- This action is associated to the original account of the transaction, it retrieves the associated piggy bank to make the transaction
- The amount is calculated by the amount of the transaction and the value of the cashback which is entered in "Action value".

### What are alternatives?

create a manual transaction for each credit card expenditure

### Additional context

No additional content

Thanks you

**Comment by JC5** [comment]
Sorry to give you a double no, but this is not something I want to add to the rule engine.

**Comment by Gsyltc** [comment]
No soucy for the double no :)
No problem for that :) Have à nice day

**Comment by JC5** [comment]
You too :+1:
