### ISSUE TITLE
Improved credit card payment plans

### ISSUE THREAD

**Issue by Gsyltc** [firefly-iii/firefly-iii#6774]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello,

I would like to propose an improvement of the automatic management of credit card repayments.

In Europe, bank cards are deferred debits or "credit cards", the amount is automatically deducted at a fixed date (except American Express for example which is based on the American model)

In the North American model. The credit card has a payment date "limit" and also a date when the accounts are "frozen".
In addition, the credit card accounts are branded in the name of the bank but the account is held by Mastercard, Visa, etc. and not linked to the bank
For example: a Mastercard National Bank credit card can be paid from a TD or Desjardins account.

Example : 
I make my expenses during the month.
On the 20th of each month, the accounts are frozen, and this determines the amount of my next payment. The amounts spent from the 21st to the 20th of the next month will be counted for the next due date.
This does not correspond to the payment date. The payment date is the 10th of the following month. 
Here is an example of what this means
From January 21 to February 20 I make expenses on my AMEX card. On February 20th I have spent $3500. This amount is the amount I will have to pay for my next due date
On March 10th, it's the due date, I have to pay the 3500$ on a different account (example: Desjardins, TD, Manulife, BNC).
All my expenses made by AMEX from February 21st (until March 20th) will be payable on April 10th, etc.

### Solution

Add the ability to have a payment date and an account freeze date.

The freeze date would allow to keep the amount paid in the database for the next due date. On the due date, the amount will be deducted from an associated bank account

So there are several parameters to add:
- A field for the debtor account that will pay the credit card amount
- A field for the freeze date of the accounts
- A value in DB and a display field for the amount of the next due date.

### What are alternatives?

No alternative to date.

### Additional context

Although the credit card system is more complex than this, and I won't go into details, this kind of processing is still common. This is the system used by American Express in Europe as well.

Thanks

**Comment by JC5** [comment]
This has been discussed before and I will not be automating this.

**Comment by Gsyltc** [comment]
I understand, thanks for your reply and have a nice day :)

**Comment by JC5** [comment]
:+1:
