### ISSUE TITLE
Spread transaction-split form across multiple rows on mobile?

### ISSUE THREAD

**Issue by deanishe** [firefly-iii/firefly-iii#678]
The transaction split form is very tricky to use on mobile.

It stretches way off the page, breaking the layout, and the fields are so narrow, it's very hard to see what's in them.

![image](https://user-images.githubusercontent.com/747913/27517705-ece91254-59d0-11e7-8bbe-a3407910e86e.png)

In particular, the contents of the Amount field are invisible (the padding is greater than the width of the field?)

In both these screenshots, there is actually something in the Amount field immediately before the cursor.

![image](https://user-images.githubusercontent.com/747913/27517711-0e147b94-59d1-11e7-99e6-c73f01be43b6.png)

![image](https://user-images.githubusercontent.com/747913/27517715-1e94f098-59d1-11e7-865b-29c72a8bbe57.png)

**Comment by JC5** [comment]
Yep, I'm afraid those forms aren't particularly mobile-friendly.

Thanks for brining this to my attention. It is on the todo list!

**Comment by deanishe** [comment]
Awesome! I'm really enjoying Firefly so far. Lovely piece of software.

**Comment by deanishe** [comment]
Thanks. It's *much* easier to split transactions on my phone now.
