### ISSUE TITLE
Crash when try to edit a existing Asset accounts

### ISSUE THREAD

**Issue by MaoZ1993** [firefly-iii/firefly-iii#6785]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi Team

Happy New Year!

I encountered an issue when I trying to edit an existing asset account, once I click on Actions - Edit, it display an error page.
![Screen Shot 2023-01-01 at 1 23 35 am](https://user-images.githubusercontent.com/35769176/210139937-dd831061-7003-48e6-aee2-3b5af91ad48b.png)

Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

FireflyIII\Support\Steam::bcround(): Argument #1 ($number) must be of type ?string, int given, called in /var/www/html/app/Http/Controllers/Account/EditController.php on line 149

 

### Expected behaviour

It should jump to the account edit page

### Debug information

I'm using a third party add-on (https://github.com/alexbelgium/hassio-addons/tree/master/fireflyiii) on my HomaAssistant Server, I think it's based on docker but in HomaAssistantOS, docker logs -f command not works for me. If anyone could guide me how to retrieve the log from HomaAssistantOS Add-on?

### Additional info

My tech skill is entry-level, I'm happy to provide more details but I do need some guide...... Please let me know how I can help. Thanks!

**Comment by JC5** [comment]
Which version of Firefly III is this?

**Comment by MaoZ1993** [comment]
> Which version of Firefly III is this?

The version is 5.7.17, Thanks

**Comment by JC5** [comment]
Thanks, nice find. A fix will be part of the next release.

**Comment by itairaz1** [comment]
Hi, thank you for the fix
I'm getting the same error when trying to get accounts (GET /api/v1/accounts)
```Internal Firefly III Exception: FireflyIII\Support\Steam::bcround(): Argument #1 ($number) must be of type ?string, int given, called in /var/www/html/app/Transformers/AccountTransformer.php on line 118```
Will it fix this issue as well?

**Comment by JC5** [comment]
Thanks for letting me know, I'll include it as well.
