### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by MaoMaoCake** [firefly-iii/firefly-iii#6786]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hi, I saw in #4110 that dark mode support is coming since 2020 but there is nothing in the project cards and the issue is stale. Is this something that is being worked on? I'm open to helping implement the feature if needed. 

### Solution

Support Dark Mode or give me a vision so I can help Implement it.

**Comment by JC5** [comment]
I'm working on a new layout that supports dark mode 👍
