### ISSUE TITLE
Emotes possibly leading to 500 crash on budgets and piggy banks

### ISSUE THREAD

**Issue by kayserlein** [firefly-iii/firefly-iii#6787]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I set my new budgets for 2023 early in the morning of January 1st (~1 Am MEST] and went to bed but after I woke up again 10 hours later, all budgets had double entries for the amount and I cannot open their edit page anymore, leading to a 500 crash.

I assume this might be caused by me using emotes for quicker/easier recognition of certain categories at a glance, like this:

[🌐Internet]

Note: I also seem to be having the same issue with piggy banks. The site causes the same crash once I have saved a piggy bank.

Running this on a Synology DS1520+ in a VM through Home Assistant via the addon from u/alexbelgium: https://github.com/alexbelgium/hassio-addons/tree/master/fireflyiii

### Expected behaviour

No double entries for budgets and able to open edit pages

### Debug information

FireflyIII\Support\Steam::bcround(): Argument #1 ($number) must be of type ?string, int given, called in /var/www/html/app/Http/Controllers/Budget/EditController.php on line 106 

### Steps to reproduce

1. Create budget/piggy bank with an emote in front of it
2. Try to open the edit page of the budget

**Comment by JC5** [comment]
The emoji's are supported just fine, this is another issue that I hope to fix in the next release. Thanks for letting me know!
