### ISSUE TITLE
Tokens pages no longer works with remote_auth

### ISSUE THREAD

**Issue by angus51** [firefly-iii/firefly-iii#6788]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,
First thanks for this great tool.

I think the tokens page (Profiles/Oauth tab) no longer works since version 5.7.16 when http header auth is used.
On the popup requesting to set a personal token name, nothing happens when i click on create.
I revert back to version 5.7.15 (after dropping the database and clearing cookies), and it works.
I can reproduce it with 5.7.16 and 5.7.17 (dropping database/clearing cookies)
The POST request return 401 (not authorized). In fact, when i click on the profile button in the menu, 4 GET requests return 401 : /oauth/clients, /oauth/tokens/, oauth/personal-access-tokens, /oauth/scopes. The response body is {"message":"Unauthenticated","exception":"AuthenticationException"}
Thoses 401 response comes from firefly, and not my reverseproxy (as i see those responses in firefly logs)
I didn't test without http header auth
I also try removing APP_URL, doesn't change anything

Happy new year !!!
### Expected behaviour

Token are created when i click on create, just like it worked in 5.7.15

### Debug information

Debug information generated at 2023-01-01 13:06:12 UTC for Firefly III version **5.7.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.16 |
| Firefly III API | 1.5.6 |
| Build | 316, 25-12-2022 07:50:13 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | remote_user_guard  |
| Headers | HTTP_FFIII_USER,   |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-01-31 23:59:59 |
| Session first | 2023-01-01 13:04:39 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0 |

### Steps to reproduce

1) Install firefly with http remote header
2) Click on create new personal access token, doesn't works

### Additional info

Docker command that launch firefly : 
/usr/bin/docker run --name $NAME \
	--network=xxxxxxxxxxx --ip=xxxxxxxxxxxxxxx \
	-e APP_KEY=xxxxxxxxxxxxxxxxxxxxxxx \
	-e APP_URL=https://firefly.xxxxxxxxxx.xxx \
	-e "TRUSTED_PROXIES=**" \
	-e AUTHENTICATION_GUARD=remote_user_guard \
	-e AUTHENTICATION_GUARD_HEADER=HTTP_FFIII_USER \
	-e DB_HOST=xxxxxxxxxxxxxx \
	-e DB_PORT=3306 \
	-e DB_CONNECTION=mysql \
	-e DB_DATABASE=fireflyiii \
	-e DB_USERNAME=fireflyiii \
	-e DB_PASSWORD=xxxxxxxxxxxxxxxx \
	-e MAIL_MAILER=smtp \
	-e MAIL_HOST=mail.xxxxxxxxxxxxxx.xxx \
	-e MAIL_PORT=465 \
	-e MAIL_FROM=fireflyiii@xxxxxxx.xxx \
	-e MAIL_USERNAME=fireflyiii \
	-e MAIL_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
	-e MAIL_ENCRYPTION=ssl \
	--mount type=volume,source=firefly_upload,destination=/var/www/html/storage/upload,volume-opt=type=none,volume-opt=o=bind,volume-opt=device=/mnt/docker/volumes-secure/firefly/upload \
	fireflyiii/core:version-5.7.16

Apache configuration
<VirtualHost *:443>
	ProxyRequests off
	ServerName firefly.xxxxxxx.xxx
	OIDCProviderMetadataURL https://keycloak.xxxxxxxx.xxx/realms/xxxxxxxx.xxx/.well-known/openid-configuration
	OIDCClientID firefly
	OIDCClientSecret xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	OIDCRedirectURI https://firefly.xxxxxxxxxx.xxx/redirect_uri
	OIDCCryptoPassphrase xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	OIDCScope "openid email"
	OIDCRemoteUserClaim email
	RequestHeader set FFIII-User %{REMOTE_USER}s
	<Location />
		AuthType openid-connect
		Require valid-user
		ProxyPass http://xxx.xxx.xxx.xxx:8080/ KeepAlive=On  connectiontimeout=3600 timeout=3600
		ProxyPassReverse http://xxx.xxx.xxx.xxx:8080/
	</Location>
	<Location /api>
		Require all granted
	</Location>
	ProxyPreserveHost on
	RequestHeader set X-Forwarded-Proto https
	RequestHeader set X-Forwarded-Ssl on
	ProxyPassReverseCookieDomain xxx.xxx.xxx.xxx:8080 firefly.xxxxxxxxxx.xxx
	SSLEngine on
	SSLCertificateFile  /acme.sh/xxxxxxxxxx.xxx/fullchain.cer
	SSLCertificateKeyFile /acme.sh/xxxxxxxxxx.xxx/xxxxxxxxxx.xxx.key
</VirtualHost>

**Comment by JC5** [comment]
Yes, this is being discussed in various other tickets, but no issue was opened yet. I'll use yours to refer to the issue in the code.

**Comment by JC5** [comment]
I pushed a possible fix to the `develop` Docker image and code branch. Let me know if it works!

**Comment by angus51** [comment]
at docker image start, got some errors : 
`janv. 01 14:31:34 malcolm docker[311204]: PHP Fatal error:  Uncaught Error: Call to undefined function FireflyIII\Support\Authentication\apache_request_headers() in /var/www/html/app/Support/Authentication/RemoteUserGuard.php:83
janv. 01 14:31:34 malcolm docker[311204]: Stack trace:
janv. 01 14:31:34 malcolm docker[311204]: #0 /var/www/html/app/Support/Authentication/RemoteUserGuard.php(129): FireflyIII\Support\Authentication\RemoteUserGuard->authenticate()
janv. 01 14:31:34 malcolm docker[311204]: #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(340): FireflyIII\Support\Authentication\RemoteUserGuard->check()
janv. 01 14:31:34 malcolm docker[311204]: #2 /var/www/html/app/Exceptions/Handler.php(154): Illuminate\Auth\AuthManager->__call()
janv. 01 14:31:34 malcolm docker[311204]: #3 /var/www/html/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(46): FireflyIII\Exceptions\Handler->report()
janv. 01 14:31:34 malcolm docker[311204]: #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(198): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report()
janv. 01 14:31:34 malcolm docker[311204]: #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
janv. 01 14:31:34 malcolm docker[311204]: #6 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
janv. 01 14:31:34 malcolm docker[311204]: #7 {main}
janv. 01 14:31:34 malcolm docker[311204]:   thrown in /var/www/html/app/Support/Authentication/RemoteUserGuard.php on line 8`

and : 
``

**Comment by JC5** [comment]
Nice find. Try again in a few minutes. I think i fixed that one.

**Comment by angus51** [comment]
Now i have something like this at container start. I didn't even try to connect to. And my firefly importer is stopped.
`
 [2023-01-01 13:59:38] local.ERROR: No user in header "HTTP_FFIII_USER".
 [2023-01-01 13:59:38] local.ERROR: No user in header "HTTP_FFIII_USER".
 [2023-01-01 13:59:38] local.ERROR: No user in header "HTTP_FFIII_USER".
    FireflyIII\Exceptions\FireflyException
   The guard header was unexpectedly empty. See the logs.
   at app/Support/Authentication/RemoteUserGuard.php:90
      86▕             $userID = request()->server($header) ?? apache_request_headers()[$header] ?? null;
      87▕         }
      88▕         if (null === $userID) {
      89▕             Log::error(sprintf('No user in header "%s".', $header));
   ➜  90▕             throw new FireflyException('The guard header was unexpectedly empty. See the logs.');
      91▕         }
      92▕
      93▕         /** @var User $retrievedUser */
      94▕         $retrievedUser = $this->provider->retrieveById($userID);
   1   app/Support/Authentication/RemoteUserGuard.php:132
       FireflyIII\Support\Authentication\RemoteUserGuard::authenticate()
       +1 vendor frames 
   3   app/Exceptions/Handler.php:154
       Illuminate\Auth\AuthManager::__call()
`
It do that while image is starting, multiple times, just after : 
* Running upgrade commands... (5 times)
* Migrated attachment notes in 0.03 seconds (1 time)
* Verified empty groups in 0.03 seconds (1 time)
* Verified all transaction group and journal title lengths. / Took 0.02 seconds. (1 time)
* Verifying account preferences took 0.02 seconds (1 time)

But i can connect to firefly, and token creation works now. (there is no more 401 anywhere in firefox logs)

**Comment by JC5** [comment]
Thanks for the logs!

**Comment by angus51** [comment]
Thanks for the fix ;-) You don't need to do that today...

**Comment by JC5** [comment]
Not a problem, happy to do this! 

I just pushed a final fix, that hopefully also fixes the errors in the logs you mentioned before.

**Comment by angus51** [comment]
i will test that as soon the docker image is available (so in few minutes).
I'm not in a rush, i try to understand how nordigen import works

**Comment by angus51** [comment]
It works. There is no more error in the logs....
I will give up for today (nordigen imports doesn't work : my bank android application fails, and disallow me to register to nordigen, and my second bank return a pretty "unknow error" to nordigen).
