### ISSUE TITLE
Expected release

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#679]
Hi,
I am very curious about the coming release with the improved importer! Also I expect the Year Tag Report to be fixed, based on the commit that fixes the Monthly Tag Report (it now extends from support, and the Year report extends from the Month report.)
Is there an expected release date?

Thanks for all your work!

**Comment by JC5** [comment]
When it's done, but probably before HL3.

**Comment by JC5** [comment]
It's live 😉
