### ISSUE TITLE
Creation of link between transactions- Add amount in autocomplete list of transactions

### ISSUE THREAD

**Issue by RaijinDS** [firefly-iii/firefly-iii#6790]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello, 

This idea concerns the creation of link between transaction.
Actually, to select the transaction to link, the modal display an ID and the name of the transaction:
![image](https://user-images.githubusercontent.com/57623002/210211055-def3a287-51e0-4d95-b0b2-28d646bb2110.png)

It could be helpful to add the amount of transactions in the select list to be able to select the right transaction easily :
![image](https://user-images.githubusercontent.com/57623002/210211654-a308431c-acc8-493a-b647-dd0a0d56227e.png)

### Solution

It seems that it is sufficient to add an additional field (amount) in the feed request of this autocomplete list of transactions.

**Comment by JC5** [comment]
I'm working on a new layout where this will be improved, thanks for the suggestion!

See also: https://github.com/firefly-iii/firefly-iii/issues/6304
