### ISSUE TITLE
Dashboard - Your Accounts - Graph Hover Description

### ISSUE THREAD

**Issue by malcm** [firefly-iii/firefly-iii#6798]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In the Accounts Graph on the dashboard it is not possible to read more then 10 Accounts in the hover effect. So it is not possible to get to know which color is which account since the decription is missing.

![firefly-issue-account-overview](https://user-images.githubusercontent.com/9459039/210775383-a0511429-3b5e-4a08-b657-ab00acd93409.gif)

### Expected behaviour

The hover effect should come up at the location the mouse is (not fixed in the lower thrid of the canvas). Or come up in the upper quarter of the canvas that all accounts can fit.

### Debug information

not necessary for this issue

### Steps to reproduce

1. Create 11 accounts and have them enabled in the capital resources
2. Check the account graph on the dashboard

**Comment by JC5** [comment]
Sorry, I can't fix that. You'll have to select less accounts to be shown on the dashboard using the `/preferences` page.

**Comment by malcm** [comment]
Hey @JC5 thanks for your fast answer. Here are some remarks from my side. I think you just need to add the following to the tooltip configuration of the chart.

```
position: 'nearest',
xAlign: 'left',
yAlign: 'top'
```

position standard is average (see https://www.chartjs.org/docs/2.7.3/configuration/tooltip.html ). That is the reson that the hight is kind of fixed. When nearest is used I can read all accounts lower in the list when I hover over a high point and all accounts higher in the list when I hover over a low point.
xAlign and yAlign is maybe not yet supported due to old version 2.7.1 you use (4.1.1 is the latest).

In general the issue is solved whith running out tooltips in the higher versions. So maybe updating to Chart JS 4.1.1 can help. Try it out. Maybe you need to reload that side that the random data will be very low - https://www.chartjs.org/docs/latest/samples/tooltip/content.html

**Comment by malcm** [comment]
Ahh ok, nice. Then I will be patient :) Thank you for your effort with this project!

**Comment by JC5** [comment]
:+1:
