### ISSUE TITLE
sankeymatic graph in the reports section

### ISSUE THREAD

**Issue by somethingGoneWrong** [firefly-iii/firefly-iii#6809]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like firefly III can show in the reports area a sankeymatic type graph;
with the possibility of selecting limits within which to merge certain expenditure or revenue categories to simplify the reading of the chart itself.
For those unfamiliar with this type of graph, I report here a site where you can see a live example:
https://sankeymatic.com/build/

do you think it is something useful?

### Solution

I think is possible to implement on the reports page this type of chart using the selectors that currently work for classic bar charts.
To simplify the work one could use one of these javascript libraries, I write below those I found still in active development:
- https://github.com/d3/d3-sankey
- https://github.com/kurkle/chartjs-chart-sankey
- https://observablehq.com/@d3/sankey

**Comment by JC5** [comment]
I will track this in https://github.com/firefly-iii/firefly-iii/issues/6311

Until then: https://sankey.firefly-iii.org/
