### ISSUE TITLE
Different behavior of dates, incorrect payment_date timezone

### ISSUE THREAD

**Issue by adyanth** [firefly-iii/firefly-iii#6810]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The transaction's date field works fine, whereas the payment_date field does not consider timezones correctly, silently ignoring it.

### Expected behaviour

Expect all the date fields to behave similarly and consider the timezone.

### Debug information

Debug information generated at 2023-01-06 11:04:08 America/Los_Angeles for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Los_Angeles |
| Browser TZ | America/Los_Angeles |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | sqlite |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-01-31 23:59:59 |
| Session first | 2022-07-27 04:43:10 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15 |

### Steps to reproduce

1. Create a transaction with date and payment date set to an ISO format string in UTC time.
2. Check the transaction to see payment_date set to the same time stamp but in local time, whereas date is correctly converted to local time.

### Additional info

Here is what I set in the transaction body for the API call:
`'date': '2023-01-06T03:58:56+00:00', 'payment_date': '2023-01-06T03:58:20+00:00'`

Here is what I get from Firefly:
`'date': '2023-01-05T19:58:56-08:00', 'payment_date': '2023-01-06T03:58:20-08:00'`

See how the date was converted and the payment_date was not.

**Comment by JC5** [comment]
Nice find, I wasn't aware. I'll check it out!

**Comment by JC5** [comment]
This feature/enhancement/bug is now part of the first alpha of 5.8.0. This ticket will be closed. If and when you find issues, please do not reply but open a new GitHub issue or discussion instead.
