### ISSUE TITLE
Missing columns on bills page

### ISSUE THREAD

**Issue by basvdburg** [firefly-iii/firefly-iii#682]
Hello,

I am missing 2 columns on a specific bill. To be specific:

```
<td class="text-success" data-value="2017-06-26 00-00-00">
<td class=" hidden-sm hidden-xs" data-value="2017-07-26 00-00-00">
```

I am not sure how this issue is caused, since the bill is not much different then other bills. I also added a screenshot for clarification. I have 12 bills on the same page, and this is the only one causing problems.

![error-firefly-3](https://user-images.githubusercontent.com/307781/27639028-5d9efcb6-5c15-11e7-882a-c1ea24521791.png)

Thank you for your help. And also thank you for building/maintaining this software. I donated some money a couple of days ago, to also show my appreciation :)

**Comment by JC5** [comment]
I saw that! Thank you!

There is a big if-then clause that generates these two columns (the two dates). Let me see what could be the issue.

**Comment by JC5** [comment]
This may happen when the bill has been paid more times than the system expected it to be: ie. a monthly bill hits twice in a month or you have a year view and you view a monthly bill.

**Comment by JC5** [comment]
To debug, open the file [resources/views/list/bills.twig](https://raw.githubusercontent.com/firefly-iii/firefly-iii/develop/resources/views/list/bills.twig) and replace it entirely with the content behind the link.

If it works, reverse your changes and let me know!

**Comment by basvdburg** [comment]
I replaced the version of the file in the develop branch in my installation, but unfortunately it is not working :(

root@13731eee0035:/var/www/firefly-iii/resources/views/list# md5sum bills.twig
fff24b01d6f0d9653431ecdc69f9ef97  bills.twig

I am looking at a monthly overview of the bills. And the transaction within that bill has only occured once this month. So the situation you described above is not the case for me.

**Comment by JC5** [comment]
Yes, if you would!

```
<!--
            Some debug data:
            entry.paidDates.count(): {{ entry.paidDates.count() }}
            entry.payDates.count(): {{ entry.payDates.count() }}
            active: {% if entry.active %}true{% else %}false{% endif %}
            -->
```

Place this below line 64 and tell me what is says for the broken bills.

**Comment by basvdburg** [comment]
My apologies for the late response. But I see the following data in the HTML output.

```
 <!--
 Some debug data:
 entry.paidDates.count(): 0
 entry.paidDates set:
entry.payDates.count(): 0
active: true
 -->
```

**Comment by JC5** [comment]
I think I have found it, and I've submitted some code.

Could you see if this file is working? Same instructions as before.

https://raw.githubusercontent.com/firefly-iii/firefly-iii/b6be9e6ade5df3d084b6fbc00da21a2d11e5448d/resources/views/list/bills.twig

**Comment by basvdburg** [comment]
That does the trick! Thank you for the solution. My bills overview is now working properly :)

**Comment by JC5** [comment]
Fix is live!
