### ISSUE TITLE
Move the data in the "Description" field to the "Notes" Field using rules

### ISSUE THREAD

**Issue by TheRealRWJ** [firefly-iii/firefly-iii#6821]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

First of all Firefly 3 is great.
Thanks for your effort and time to create this awesome application.

Even though I am still missing something

Banks deliberately mess up the downloads because they want you to stay in their garden.
The download of my bank for example has  only 8 (tabs) fields per transaction record.
This messes things up pretty fast for me. I know you cant do anything about that.

Its a lot better when using Nordigen import
It would be nice though,  to be able to move the data in the "Description" field to the "Notes" Field, so I can create my own descriptions

Is this possible by changing the Nordigen import configuration file?

If not, I would like to file a feature request to move the Description data to the Notes field using rules.

### Solution

It would be nice though,  to be able to move the data in the "Description" field to the "Notes" Field.
ie using rules during the Nordigen import. so I can create my own 

### What are alternatives?

I did not find any decent alternatives instead of using the horrible download from  my bank

### Additional context

Thanks in advance.

RWJ

**Comment by JC5** [comment]
[That's a nice coincidence, this will be part of 5.8.0 and i](https://github.com/firefly-iii/firefly-iii/issues/4975)
