### ISSUE TITLE
Difference percentage in reports

### ISSUE THREAD

**Issue by Demaz93** [firefly-iii/firefly-iii#6825]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to have inside report in "Income vs Expense" panel also the difference in percentage.

### Solution

Add the percentage difference and not only the money value.

**Comment by JC5** [comment]
This will be something I can pick up here: https://github.com/firefly-iii/firefly-iii/issues/6310

But mind it may be a value you only say when hovering over the numbers, to save space.
