### ISSUE TITLE
Updating an existing transaction, "foreign_currency_id" gives 422

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#6828]
### Discussed in https://github.com/orgs/firefly-iii/discussions/6827

<div type='discussions-op-text'>

<sup>Originally posted by **adyanth** January 10, 2023</sup>
Doing the same as https://github.com/orgs/firefly-iii/discussions/6820, while updating a transaction after getting it from firefly, firefly complains about the `foreign_currency_id` field being set to 0. Refer the JSON in the linked discussion, this is being returned by firefly itself.

Deleting the field before the PUT call works well, but this looks to be an incorrect API behavior?</div>

**Comment by JC5** [comment]
Should now return NULL as expected.

**Comment by MGHollander** [comment]
I assume this will be fixed in version 6.0.0, right?

Any workaround till then? How can I remove the field before PUT?

**Comment by JC5** [comment]
Yes, this will be fixed in 6.0.0. 

> How can I remove the field before PUT?

By removing it from what you submit to Firefly III, I guess.
