### ISSUE TITLE
CSV import description base64 string

### ISSUE THREAD

**Issue by erroneousio** [firefly-iii/firefly-iii#685]
Following on from #669 it appears the import function is working but putting some other data into the description field. I've tested with some bigger CSVs (with 'real' data) as well as the example data I included in the mentioned issue and although all other fields import correctly, the description is always a base64 encoded string.

[Test import from export.csv.txt](https://github.com/firefly-iii/firefly-iii/files/1117161/Test.import.from.export.csv.txt)
[currency-id-configuration.json.txt](https://github.com/firefly-iii/firefly-iii/files/1117160/currency-id-configuration.json.txt)

Import is successful and I can view the transaction, however the description isn't quite right.

For above test data:

![image](https://user-images.githubusercontent.com/16657546/27762849-d3d2a4a6-5ebc-11e7-8d36-76c411bfcce7.png)

Original base64 string:

```
eyJpdiI6IkE1TWh2UTVYd3JBVk9zWWJ0bEYxb2c9PSIsInZhbHVlIjoiVEVJNkNNTEhFWlZcL1FTM2ZmNndncEE9PSIsIm1hYyI6ImEzMjJhMWE3ODNkNzYwNmM3ZmVlZmQ0M2YyYjc3YzIxZTU1NWU1MDliMzVkY2QzZmZlYTcwMzg2NTIwYzA4NzIifQ==
```

Decoded with `echo "<string>" | base64 -d`:

```
{"iv":"A5MhvQ5XwrAVOsYbtlF1og==","value":"TEI6CMLHEZV\/QS3ff6wgpA==","mac":"a322a1a783d7606c7feefd43f2b77c21e555e509b35dcd3ffea70386520c0872"}
```

Other data looks like this:
![image](https://user-images.githubusercontent.com/16657546/27762971-a0ce227c-5ebe-11e7-91ad-c0d3a8dba0f1.png)

**Comment by JC5** [comment]
That's a bad one!

Open the database, find those ID's in the table `transaction_journals`, and change `encrypted` from 0 to 1. That should fix them. I will push a fix in the weekend.

**Comment by erroneousio** [comment]
Work around confirmed, updated the table and it's now displaying correctly.

**Comment by JC5** [comment]
Fix is live!
