### ISSUE TITLE
Add FireFly iii to Umbrel AppStore to make it easier to self-host 

### ISSUE THREAD

**Issue by integer256** [firefly-iii/firefly-iii#6865]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to install FireFly iii in my Umbrel server

### Solution

Add Firefly iii to the Umbrel AppStore:

https://github.com/getumbrel/umbrel-apps/blob/master/README.md

Template of how to add it: 

https://github.com/getumbrel/umbrel-community-app-store

### Additional context

Umbrel is an OS for running a personal server in your home. Self-host open source apps like Nextcloud, Bitcoin node, and more. FireFly iii will be a great addition to the store. 

More information: https://umbrel.com/

**Comment by JC5** [comment]
I appreciate the idea, but I'm not going to do this. I have enough of a maintenance burden as it is with Firefly III itself. Feel free to add Firefly III yourself though!

**Comment by integer256** [comment]
Added to Umbrel here: https://github.com/getumbrel/umbrel-apps/pull/378

**Comment by JC5** [comment]
Nice :+1:
