### ISSUE TITLE
Liability created via API is not applying opening balance.

### ISSUE THREAD

**Issue by bradsk88** [firefly-iii/firefly-iii#6869]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I hit my instance of Firefly III (Version 5.7.18) with the following request, it results in a liability account with a zero balance. 

```json
{
  "name": "test liability @ 2023-01-16T04:41:04.249Z",
  "type": "liability",
  "opening_balance": "-12345.67",
  "opening_balance_date": "2023-01-16",
  "currency_code": "CAD",
  "liability_type": "debt",
  "liability_direction": "debit"
}
```

Result (In app)
![image](https://user-images.githubusercontent.com/2147630/212600610-b4658083-6fd9-43f2-b90c-90d48a73683d.png)

Result (from `192.168.0.124:4575/api/v1/accounts`
```
{
  "type": "accounts",
  "id": "66",
  "attributes": {
    "created_at": "2023-01-16T05:10:58+01:00",
    "updated_at": "2023-01-16T05:10:58+01:00",
    "active": true,
    "order": 2,
    "name": "test liability @ 2023-01-16T04:41:04.249Z,
    "type": "liabilities",
    "account_role": null,
    "currency_id": "10",
    "currency_code": "CAD",
    "currency_symbol": "C$",
    "currency_decimal_places": 2,
    "current_balance": "0.00",
    "current_balance_date": "2023-01-16T23:59:59+01:00",
    "notes": null,
    "monthly_payment_date": null,
    "credit_card_type": null,
    "account_number": "",
    "iban": null,
    "bic": null,
    "virtual_balance": "0.00",
    "opening_balance": "0.00",
    "opening_balance_date": null,
    "liability_type": "debt",
    "liability_direction": "debit",
    "interest": null,
    "interest_period": null,
    "current_debt": "0",
    "include_net_worth": true,
    "longitude": null,
    "latitude": null,
    "zoom_level": null
  },
```

### Expected behaviour

- The liability's current balance should equal the opening balance provided in the request.
- The liability should have an initial transaction to reach that balance and this should not require an additional API call.

### Debug information

Debug information generated at 2023-01-16 05:49:19 Europe/Madrid for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Madrid |
| Browser TZ | America/Regina |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-01-31 00:00:00 |
| Session first | 2022-12-07 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 |

### Steps to reproduce

See description

**Comment by JC5** [comment]
Nice find. This will be fixed in 6.0.0.

**Comment by JC5** [comment]
Whoops

**Comment by JC5** [comment]
Fixed in the new alpha :+1:
