### ISSUE TITLE
Old inactive recurring transactions do not lose categories when the categories are deleted

### ISSUE THREAD

**Issue by death2cupbots** [firefly-iii/firefly-iii#6870]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If you have a recurring transaction that is inactive and also quite old (like say 2020 old) and has been inactive since some time in 2020 (possibly), the category attached to that recurring transaction is not deleted when the category itself is deleted, so when you go to the recurring transactions page, it recreates the empty category.

### Expected behaviour

Deleted categories should be deleted from recurring transactions.

### Debug information

Debug information generated at 2023-01-15 23:48:33 America/New_York for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | (unknown), (unknown) |
| DB version | 18 (exp. 18) |
| PHP | `8.2.1` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-01-31 23:59:59 |
| Session first | 2019-06-17 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Have an old, inactive recurring transaction with a category that no longer exists.
2. Go to the recurring transactions page.
3. Go to the categories page.
4. Notice the deleted category has returned.

### Additional info

This doesn't seem to happen with new recurring transactions. It might need transactions attached though, so I'm going to run a test on that.

**Comment by JC5** [comment]
Nice find, this happens with new recurring transactions as well (for me), but I've updated the code just the same.

**Comment by JC5** [comment]
Whoops.

**Comment by JC5** [comment]
Fixed in the new release.
