### ISSUE TITLE
The dashboard could use a couple of links

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#688]
There are a lot of elements in the dashboard that only show data, but don't link to anything.
* Money in -> could link to a page showing all deposits in that period
* Money out -> all withdrawals 
* Bills to pay / paid -> to the filtered bills view
* Bills chart -> to bills overview
...

The ones I mentioned here are the ones that came to mind till now. I'm just starting to use firefly, so as time goes on, I might "want" more links

**Comment by JC5** [comment]
Haha yes, what you 'want' is not a bad idea at all. I'll see what I can do :)

**Comment by JC5** [comment]
This should be realised in the current release. Let me know if you see more opportunities.
