### ISSUE TITLE
Add auto-completion on the search field

### ISSUE THREAD

**Issue by Hugal31** [firefly-iii/firefly-iii#6883]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I find it difficult to remember the search keywords, such as `category_is`, and when doing a research I always end up looking at the documentation for the exact syntax.

### Solution

I would be great to have an auto-completion for at least the keywords (completion for the values, such as categories and tags would be a plus).

It could be displayed as a greyed text after the cursor, and a press on TAB would complete the rest of the word, such as in fish-shell or gmail.

### What are alternatives?

We also could have:
- Fuzzy matching on the words followed by a column
- An help text  (such as "do you mean `has_category` ?").

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5603
