### ISSUE TITLE
Graph shows values in the future

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#689]
The Graph on the dashboard shows values for the account that are in the future.  
If not enough historic data is available it should just be cut off.

![firefly](https://user-images.githubusercontent.com/1042898/27840156-1862d8f2-60f7-11e7-9f43-18a251d9adf4.png)

**Comment by JC5** [comment]
I know, but it stays. You can create transactions in the future that could influence the chart. Another chart library I used could indicate that the [future was uncertain](https://developers.google.com/chart/interactive/docs/roles) but I haven't found something like that in ChartJS.

**Comment by simonsmiley** [comment]
Didn't think about future transactions...
