### ISSUE TITLE
Rules with negated triggers

### ISSUE THREAD

**Issue by truppelito** [firefly-iii/firefly-iii#6890]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

First of all, thank you for such an amazing tool. I found it recently and now I'm definitely not going back to my Excel spreadsheet.

I read your paragraphs on ["More complicated rules, like AND or OR, copy/pasting values, etc"](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/) and I understand completely. However, I'd like to ask if you would consider adding a NOT operator to each trigger.

Consider the following situation. When I add a transation, I set its category. Most transations should be automatically added to a budget called "Monthly expenses", except transations which belong to (for ex.) 4 specific categories. Currently, to do this I must create a rule that adds a special tag (ex. "Do not add to monthly budget") if a transation has one of the 4 specific categories, then I need to add a second rule where the trigger is "No tag is *Do not add to monthly budget*" and the action is to set the budget to "Monthly expenses". Note that I need this two-rule process because there is a "No tag is x" rule but there isn't a "Category is NOT x" rule.

### Solution

My proposed solution is to add a checkmark (just like "Stop processing other triggers") to each line in the trigger table. When checked, the trigger is inverted. I think this is clear enough and does not add too much complexity. Also, this won't be entirely a new idea: there are already some "negative" items in the trigger options ("No tag is X", "Has no bill", "Has no category", etc), but these do not cover all cases, hence this feature request.

### What are alternatives?

Another option is to just add more items to the trigger list, i.e. next to "Category is...", add "Category isn't...". Personally, I don't like this idea as much. The list is already quite long, and once again, adding more items will still likely not cover all cases.

### Additional context

As a further improvement, the large list of options for each trigger in the rule system could be changed to have two lists of options instead. The first list would be populated with items like "Category", "Tag", "Bill", "Attachments", "Foreign amount", etc and the second list would be populated with items like "is empty", "is exactly", "starts with", "ends with", etc for things like Category, Bill, and "is exactly", "is less than", "is more than", etc for things like Foreign amount. These two lists would be two columns in the triggers table, instead of one column (whose header name currently is "Trigger"). The structure of each trigger would then be: "trigger value type" + "comparison" + "trigger value" + "negation checkmark" + "stop processing others checkmark".

Personally, I feel this would make the rule system easier to use, as currently I have to search through quite a large list, whereas in this new idea I would search through two smaller lists. But you also said clearly you didn't want to make the rule system too complex, so if you feel this is the case, then I understand if you deem this extra improvement as out of scope.

**Comment by JC5** [comment]
You're in luck, negative search and rule options will be part of the next layout!

As for your suggestion, I've some written down already in https://github.com/firefly-iii/firefly-iii/issues/6308 and I'll track your requests in that issue. Sounds good?

**Comment by truppelito** [comment]
That's awesome. Sounds good to me.
Thank you again for all this amazing work!
