### ISSUE TITLE
Default import configuration

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#690]
Feature request :)

Every time I import I always use the same import configuration file, could it be possible to add to preferences a default import config file?

**Comment by JC5** [comment]
It's possible but I'm currently focusing on improving the import process itself, not extending it.

**Comment by ragnarkarlsson** [comment]
absolutely, hence my opening line of "Feature request" aka this is totally not necessary and would only make my life easier and 5 seconds less effort importing stuff because I'm a lazy person ;)

**Comment by JC5** [comment]
Sounds like me though ;).
