### ISSUE TITLE
Exception in `authenticatedGet` has no method `getResponse` resulting in 500 error during data import from Nordigen

### ISSUE THREAD

**Issue by HarryU** [firefly-iii/firefly-iii#6909]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When importing adding a bank via Nordigen, I was getting a `500: internal server error`. The logs had the following error, during the `getAccountDetails(XXX)` call.

`production.ERROR: Call to undefined method GuzzleHttp\Exception\ConnectException::getResponse() {"exception":"[object] (Error(code: 0): Call to undefined method GuzzleHttp\\Exception\\ConnectException::getResponse() at /var/www/html/app/Services/Nordigen/Request/Request.php:124)`

### Expected behaviour

There should be no error.

### Debug information

Debug information generated at 2023-01-21 15:58:37 GMT for Firefly III Data Importer version **0.9.17**.

| Scope | Version |
| --- | --- |
| FIDI | 0.9.17 |
| Build | 177, 23-10-2022 15:04:13 CEST |
| PHP | 8.1.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | GMT |
| Browser TZ | Europe/London |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55 |

### Steps to reproduce

I'm not actually sure _what_ was causing the error.

### Additional info

I edited `app/Services/Nordigen/Request/Request.php`, moving [line 122 and 124](https://github.com/firefly-iii/data-importer/blob/de87fe01c87dea2cf329e5cfca8ba4803e283023/app/Services/Nordigen/Request/Request.php#L122) inside the `if` statement on [line 133](https://github.com/firefly-iii/data-importer/blob/de87fe01c87dea2cf329e5cfca8ba4803e283023/app/Services/Nordigen/Request/Request.php#L133) - this has fixed my issue - happy to create a PR if desired, but I've not tested what else this might impact.

**Comment by JC5** [comment]
Thanks for letting me know! It will fix the error, but what was the root cause? Do you have any insight into that?

**Comment by HarryU** [comment]
No, didn't get around to looking at what the exception was once I got past it - if I get a bit of time I'll try to look more in. Because the first thing that happened in the exception handling was a second exception, I didn't get a useful stacktrace or any helpful output.

**Comment by JC5** [comment]
A timeout could happen yes, Nordigen doesn't cache all data so it needs to contact your bank. You can increase the timeout in your .env file in the mean time.
