### ISSUE TITLE
Blank rows on CSV import

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#691]
I've just discovered that my installation 4.6.1 doesn't like imports of CSV which have effectively data empty rows, ie just an appropriate number of commas to indicate a line but no actual data.

My bank's default export includes an empty row at the top and after the header lines. Deleting these allows import to run normally.

**Comment by JC5** [comment]
Lol why would they do so?

I'll make sure that the importer skips such rows.

**Comment by ragnarkarlsson** [comment]
... poor code quality? 

👍

**Comment by JC5** [comment]
Alright the CSV reader should already catch completely empty rows but rows with comma's did create problems. I think I've caught most of them and I've added some reporting so you know what's up. The next release should include these fixes.

**Comment by JC5** [comment]
This should be fixed in the current release. Let me know if it isn't!

**Comment by ragnarkarlsson** [comment]
Can confirm this works as expected now, however I've unearthed something else ... will raise an issue momentarily.
