### ISSUE TITLE
Suggestion. Hiding non-default currency from dashboard, using 'Foreign amount' instead if it exists

### ISSUE THREAD

**Issue by xcme** [firefly-iii/firefly-iii#6916]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello,
There are a lot of currency-related issues, not sure if this idea has been already discussed. The problem is very similar to #3355. I agree with the author that it makes no sense to have on the same graph, lets say Euros and Forints. This doesn't provide relevant insight, as it was said. Actually, it ruins all the graphs because of incorrect proportions of the expenses.

Example:
I spent 4 EUR and 400 HUF. By default, the graph would show about 1% of expenses for EUR and approx 99% for HUF, wouldn't it? But in fact it should 80% for EUR and 20% for HUF because of the exchange rate. Thus, it's better not to show values in different dimensional scales at all, than show obviously incorrect information.

### Solution

My suggestion is to hide from the dashboard graphs every transaction with non-default currency if **it doesn't have** the _Foreign amount_ in the default currency filled in. But if it has, then this value has to be used instead.

If customers want to see such expenses on the graphs they should manually provide corresponding _Foreign amount_ for each such transaction. If it isn't done then it isn't supposed to be shown.

### What are alternatives?

As an alternative solution there could be different tabs for different currencies, but the idea is the same - not to mix incomparable values on the same graph.

Thanks

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/6299 for the work on the new layout. This will be a part of it.
