### ISSUE TITLE
Suggestion. Hiding data on charts and graphs if account is unticked in Preferences or is inactive

### ISSUE THREAD

**Issue by xcme** [firefly-iii/firefly-iii#6917]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello,
I have a couple of accounts where I have one transaction per month maximum. I unticked them in _Preferences_ and disabled in _Accounts_, but I still see:

- These accounts in _Default financial report_ in _Reports_
- These expenses in _Balance_ on the _Dashboard_
- These expenses included in the _Category_ chart on the _Dashboard_

May I hide them somehow? In case I need this info again I can simply activate/tick them back in _Accounts_/_Preferences_

### Solution

If account is disabled (inactive) or unticked in _Preferences_ then the all relevant data should disappear from _Dashboard_/_Charts_

Thanks

**Comment by JC5** [comment]
> May I hide them somehow?

No. Inactive accounts are hidden from the auto-complete box only. They are still a part of your finances. You can select the accounts you want to be included in the default financial report and exclude these accounts, if you so wish.

**Comment by xcme** [comment]
Got it. Thanks.
