### ISSUE TITLE
Question: How to re-balance my accounts?

### ISSUE THREAD

**Issue by flow7** [firefly-iii/firefly-iii#692]
Hi,
I've learned about firefly a couple of weeks ago and started experimenting with it, setting up my accounts, importing data (required a few resets and didn’t always work), setting up some rules, identifying bills etc ...
And now it roughly works - great.
However, the accounts' balance is now off, minus 2000€ approx - probably for a number of reasons, e.g. I imported way more withdrawals then earnings.

Any suggestions on how to easily re-balance my accounts? Just book a deposit with the difference from a fictional account?  thanks

**Comment by JC5** [comment]
You can correct this by creating or importing the missing transactions. Or, give your account an opening balance.
