### ISSUE TITLE
Importing / exporting of Rules (Maybe as JSON)

### ISSUE THREAD

**Issue by ameeno** [firefly-iii/firefly-iii#6924]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- I Would like the ability for firefly III to export and import rule sets.
I find the gui very clunky and gets in the way when setting up rules.

I'm not sure if i can modify rule sets via code and export it but i dont see any option.

### Solution

Allow option to export rules and also to import them using buttons on the rule page

### What are alternatives?

Manually making every rule.

### Additional context

I find myself going back and fourth on the rules pages to do simple things.

perhaps the documentation could be improved with examples for AND/OR features.

**Comment by JC5** [comment]
You can use the API to import/export rules as you see fit, but it'll be some effort. I hope to make rules easier to manage in the new layout.

**Comment by JC5** [comment]
I wrote a script that can do this (not finished yet) but honestly it's not easier than using the API directly. Feel free to use it and expand on it further.

https://gist.github.com/JC5/3084d91c424b5162ea93049fc62aa946
