### ISSUE TITLE
Import without asset account doesn't use default asset account option

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#694]
Importing a CSV which doesn't include a field specifically for the asset account does not appear to use the **_Default import account_** option set in step 1 (csv.initial_box_title) despite selecting a relevant asset account. Firefly-iii v4.6.2

**Comment by JC5** [comment]
Without looking at the code I know I didn't rebuild that. Will get right on it!

**Comment by tomazsustar** [comment]
Same here, using 4.6.2
