### ISSUE TITLE
Change currencies in Expense/Revenue accounts

### ISSUE THREAD

**Issue by barrelltitor** [firefly-iii/firefly-iii#6946]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

We need to be able to change currencies in these accounts. This was already reported, https://github.com/firefly-iii/firefly-iii/issues/3325 but the bot closed it for some reason since not enough people complained in a week. 

This HAS been discussed before, but the issue was closed about 3 years ago and nothing was done about it

### Solution

It should happen the same as for asset accounts

### What are alternatives?

Adding all currencies of an account on display instead of just the default one

**Comment by JC5** [comment]
Why?

**Comment by JC5** [comment]
Expense and revenue accounts will not be getting currency settings. It doesn't matter what currency you send to them (through withdrawals or from deposits). Your alternative:

> Adding all currencies of an account on display instead

Is indeed what I plan to add in the new layout.
