### ISSUE TITLE
Every euro is x100

### ISSUE THREAD

**Issue by siSSSou** [firefly-iii/firefly-iii#695]
I'm new at using Firefly and I don't understand this : every euro in my buget is multiplied by 100 : if I set 100 for a withdrawal, firefly sets 10000.
I don't know if it's a feature I don't understand or a bug.

I use last version of Firefly III (fresh install) on debian with Nginx.

**Comment by JC5** [comment]
You're missing a language package. 

https://firefly-iii.github.io/faq-technical.html
