### ISSUE TITLE
Updating transaction type via the API does not work

### ISSUE THREAD

**Issue by gccollect** [firefly-iii/firefly-iii#6950]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am trying to convert deposit transactions for which the source and destination accounts are known into transfer transactions using PUT /api/v1/transactions/{id} from the API for each one. The operation returns successfully (code 200) but the transaction type remains the same. The request appears to be correct, given that the tags are updated correctly. 

There doesn't seem to be any alternative way of changing the transaction type in the API.

### Expected behaviour

The type of transaction is changed to 'transfer'

### Debug information

Debug information generated at 2023-01-31 12:44:13 Europe/London for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_GB |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-01-31 23:59:59 |
| Session first | 2014-11-10 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 |

### Steps to reproduce

Call PUT /api/v1/transactions/{id} with a type different than the current one for transaction {id}

### Additional info

All I can see on the debug page which might be related is:
```[2023-01-31 12:42:20] local.WARNING: Not a valid source, cant find it. ["Asset account","Loan","Debt","Mortgage"] ```

**Comment by JC5** [comment]
You can't change transaction types like this. There is no conversion endpoint yet. It's on my list somewhere, I'll look it up.

**Comment by gccollect** [comment]
Thank you for confirming. So the only way using the API is to delete the transaction, then recreate it?

**Comment by JC5** [comment]
I'm afraid so. Or make a rule that's specific to the transaction with the action to change the transaction type.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6304
