### ISSUE TITLE
AutoBudget formula has recently been broken

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#6964]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

It appears https://github.com/firefly-iii/firefly-iii/commit/de3376c966bdc152c466f0491edd258de80d54eb is a breaking change for auto budgets (when using "add an amount every period" option)

Previously, new budget value was be calculated using:

`budget for new month =  budget for previous month - amount spent previous month + auto budget value`

But now, according to the new code, it seems to be calculated using this formula:

`budget for new month = budget for previous month - amount spent previous month + budget for previous month`

New code seems to double budget every month instead of adding supposed automatic value .

For example, if I have a budget that was set to 500€ last month, I spent 50€ last month and I have auto-budget set to 100€, I would expect this month's budget to be set to 550€ (50€ was subtracted for last month and then 100€ added at the start of this month). But with the new formula, this month's budget would be set to 950€.

### Expected behaviour

.

### Debug information

.

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by matejdro** [comment]
Can confirm, march budgets are fine.
