### ISSUE TITLE
Be more free with the source/destion accounts when choosing Splits

### ISSUE THREAD

**Issue by JokerGermany** [firefly-iii/firefly-iii#6967]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to choose the source and destination account freely in Split transaction.

### Solution

Use Case:
You pay a transaction with two different payment methods.
e.G. You pay something partly with a voucher and partly with the bank account.

### What are alternatives?

To be honest I use this very often because i often use discounted voucher as part of the payment.

And this is only the most obvious use case.
I like to be very detailed and then there are much more such cases.

=> I don't see any alternatives which aren't two different transactions which would be very odd for me.

**Comment by JokerGermany** [comment]
Thanks for your answer.

Could be an expert settings which isn't enabled by default ;)

**Comment by JC5** [comment]
Yeah that's exactly my point ;). A support burden *and* a maintenance burden.
