### ISSUE TITLE
[Feature Request] Auto completion while creating transactions

### ISSUE THREAD

**Issue by gthbusrr** [firefly-iii/firefly-iii#6978]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Right now, there are no real options for auto completeion / transaction cloning other than cloning individual transactions, especially if you wanna clone transactions from different `transaction_groups` into a single one.

(Say, I wanna clone `transaction_journal` ID 5 from `transaction_group` ID 2 and `transaction_journal` ID 44 from `transaction_group` ID 4 into a new `transaction_group`

### Solution

# Option 1
- When selecting a description from autocomplete dropdown, ability to autopopulate fields like `Category`, `tags`, `External URL` and `notes` using a pop up menu (Similar experience to when linking transactions?)

# Option 2
- Add autocomplete to fields like `External URL` and `notes`

### What are alternatives?

When creating a transaction that's existed before, I usually
1. Open a new tab and search for that similar transaction to make sure I apply all tags / notes properly
2. When I like to copy some formats like notes which I don't think I can search (Correct me if I'm wrong), I generally go directly to the database and search for it using quries.

### Additional context

I understand that rules exists. But sometimes, I wanna change some attributes based on past entries. Also, it's not realistic to create a rule for every single possible transaction that I made.

Thank you so much for your effort. It's just a suggestion. I fully appreciate your work and I can live with the alternatives.

**Comment by JC5** [comment]
There are several ideas that point in this direction, so I'm going to merge this with https://github.com/firefly-iii/firefly-iii/issues/4917
