### ISSUE TITLE
Optional "auto import" button to trigger FIDI automatic imports

### ISSUE THREAD

**Issue by AlanMW** [firefly-iii/firefly-iii#6988]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be nice if the firefly UI had a place to redirect to the FIDI url, or to have an auto import button, assuming the [importing over command line](https://docs.firefly-iii.org/data-importer/usage/command_line/) is configured for the environment.

### Solution

Could have a reference on the side below the export button. Or options to manually configure our own links.

![image](https://user-images.githubusercontent.com/29108267/217344855-9d2a5782-4ceb-472c-9ba9-90e02d38932e.png)

### What are alternatives?

Manually going to the FIDI UI or command line

**Comment by JC5** [comment]
Sorry no, you'll have to create a browser bookmark for this.
