### ISSUE TITLE
API Insight endpoints do not allow to fetch data for a single day

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7020]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm trying to get the summary balance (total expense/total withdrawal) for a single day only.

When trying an insight endpoint (for example `/api/v1/insight/expense/total`) with `startDate` = `endDate` = `2023-02-12` the API returns a 422 error.

When trying with one day offset (i.e. `startDate` = `2023-02-11` and `endDate` = `2023-02-12`), I get the summary for two days worth of data (as I would expect).

A quick check reveals that this is also true for `/api/v1/summary/basic`.

### Expected behaviour

The API should return the summary data of the provided day.

### Debug information

```| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |
```

Also reproducible in the current demo.

### Additional info

I'm not too much into PHP, but it looks like https://github.com/firefly-iii/firefly-iii/blob/main/app/Api/V1/Controllers/Insight/Expense/PeriodController.php#L54 would call setRange in https://github.com/firefly-iii/firefly-iii/blob/develop/app/Helpers/Collector/Extensions/TimeCollection.php#L775, which modifies `startDate` to be at midnight and `endDate` to be at 23:59:59, which would most likely result in the expected behavior.

I'm not sure where the sanity check is done which returns the API error which would need to be modified to solve this bug, sorry.

**Comment by JC5** [comment]
Nice find, will be fixed in 6.0.0.
