### ISSUE TITLE
Make editing things easier by reducing click distance (and maybe some menus)

### ISSUE THREAD

**Issue by tobiasschuerg** [firefly-iii/firefly-iii#7022]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I'd appreciate if the click distance for some things would be reduced to that they're more easily accessible.

Some examples:

- expense list: editing requires two clicks but should be reachable directly
- expense details: the page is rather empty so both menu options could all be shown as buttons or in a menu bar
- when showing a category `categories/show/n`, there is (as far as I see) no way to directly edit this category - instead you have to go to the category list and search for the category to edit

### Solution

In the **expense list**, always show the edit-icon and instead of the `actions`-buttons just show a horizontal ellipsis `⋯`. Maybe even only show options, when hovering the line.

In the **expense details**, show all options as (text-)buttons or as menu-bar.

For **categories**, accounts, etc add a button to direcly edit the thing viewed.

### What are alternatives?

Keep it as it is and do lots of unnecessary clicks ;-)

### Additional context

If unclear, I can of course, elaborate and provide screenshots...

**Comment by JC5** [comment]
There are several tickets dedicated to a new layout, where I plan to fix things like this. They've been mentioned before.

See https://github.com/firefly-iii/firefly-iii/issues/6301 and https://github.com/firefly-iii/firefly-iii/issues/6304
