### ISSUE TITLE
upgrade issue with multi currency transfers

### ISSUE THREAD

**Issue by tomazsustar** [firefly-iii/firefly-iii#703]
Whenever I run after upgrade, my multi currency transfers are changed after I run:

php artisan firefly:upgrade-database

I am transfering every month lets say 100 CHF from asset account 1 another asset account 2 which is in EUR. So it is lets say 90 EUR transfered to asset account (2) (CHF100=>EUR90) After each upgrade the values for all such transfers are changed and I get the message in the console that I have to verify those transfers. What happens is that the EUR value is corrected to the amount of CHF, so all transfers are corrected wrongly to  (CHF100=>EUR100)  

This has happened wit upgrade from upgrade 4.6.0 => 4.6.1 as well ass with 4.6.1=>4.6.2.

**Comment by JC5** [comment]
Does the 1st asset account have the currency preference set to CHF?
