### ISSUE TITLE
"Remove text from description" Rule

### ISSUE THREAD

**Issue by skyborgff** [firefly-iii/firefly-iii#7030]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- Add a "remove text from description" option in the rules.

In Portugal, if you use a card to pay, all the transactions come with "COMPRA CARTAO 1234567" appended, making the view a bit cluttered

### Solution

A remove text from description on the rules page

### What are alternatives?

keep living with a cluttered transaction view

**Comment by skyborgff** [comment]
the full description currently looks like this:
"COMPRA CARTAO 1234567 MCDONALDS SHOPPING CENTER X 1234-001 PLACE"
And i'd like to keep the identifiable information, and only remove the "COMPRA CARTAO 9357778" (Translates to Transaction with card 1234567)

**Comment by JC5** [comment]
Sorry, there is nu rule action to do that.

https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/#more-complicated-rules-like-and-or-or-copypasting-values-etc
