### ISSUE TITLE
Transaction for yearly bill not detected

### ISSUE THREAD

**Issue by Firefly1337** [firefly-iii/firefly-iii#704]
I'm trying to mark a yearly bill as paid but the automatic detection is not working for yearly bills. (and there does not seem to be a manual way to do it)

I tried setting different dates for my transaction and my bill, and also in any combination I can come up with (bill in past, transaction in past, bill in future, transaction in future, both, neither, same date etc. etc.) but nothing works.
Interestingly enough, once I set my yearly bill to monthly it immediately detects the correct transaction.
Unless I'm missing something, this seems to be a bug.

Unfortunately that's all I can provide as there are no logs or anything.
I tried version 4.5.0 and then upgraded to 4.6.2 (latest), same result.

**Comment by JC5** [comment]
Mmmm. I can't seem to reproduce this. I've created a bill with a "match" of "XX1234" and amounts between 1 and 100. 

Every transaction I create with XX1234 in the title gets linked to the bill. This happens when the bill is "yearly" as well.

Could you share some of the details you do the matching on?

**Comment by Firefly1337** [comment]
It's working now, but it is kind of weird.
I also tried matching for "XX1234" and that worked, so something still had to be wrong with my own bill. I had two "matches" set to my bill and I mistakenly assumed that "match" is an OR operation but in fact it is AND (in my defence, there does not seem to be any documentation on this :D).

But it was still weird because I know for a fact that I tested it with a single "match" first and it didn't work. But that was when I was still on version 4.5.0. Maybe I had another error (e.g. date related) and moved on too quickly for me to realize it.

Anyway, thank you for your help. You can close this issue now :)

**Comment by JC5** [comment]
No problem! Documentation is an issue, it doesn't mention the AND/OR thing. I'll get right on it!
