### ISSUE TITLE
Unable to use attachments on split transactions

### ISSUE THREAD

**Issue by jrhedman** [firefly-iii/firefly-iii#7051]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When adding a new transaction that has been split into multiple budgets/categories (such as after a trip from Walmart), after attaching the receipt to one or all listed splits, the option to view the attachment does not appear.

I'm unsure if either the attachment isn't uploaded or if the attachment was, but there's no option to view it.

### Expected behaviour

Preferably, an option to add an attachment to the whole transaction and not individual splits, but at a minimum, the ability to view an attached file to a split transaction.

### Debug information

Debug information generated at 2023-02-19 02:11:46 Europe/Amsterdam for Firefly III version **5.7.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.15 |
| Firefly III API | 1.5.6 |
| Build | (unknown), (unknown) |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-02-01 00:00:00 |
| Session end | 2023-02-28 00:00:00 |
| Session first | 2022-05-15 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Create a split transaction
2. Attach file to one or all the splits
3. Open the transaction and see no option to view/download the attached file.

### Additional info

I know I'm a few updates behind, but it doesn't look like this was addressed through 5.7.18 yet so I thought it might be good to report.

**Comment by JC5** [comment]
You're using Safari, right? Try another browser for the time being, I'll see what I can do.

**Comment by JC5** [comment]
I can replicate this, but it seems to be something in nginx. The request never properly arrives at Firefly III itself.
