### ISSUE TITLE
Error in FIDI when sending email with mailgun

### ISSUE THREAD

**Issue by pazaan** [firefly-iii/firefly-iii#7060]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have FIDI configured to use Mailgun.
The import itself goes just fine, but my cron job gets back a 500 from wget.
When I look at the FIDI logs, I see this:
```
[2023-02-20 13:40:35] local.ERROR: Class "Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory" not found {"exception":"[object] (Error(code: 0): Class \"Symfony\\Component\\Mailer\\Bridge\\Mailgun\\Transport\\MailgunTransportFactory\" not found at /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php:278)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(161): Illuminate\\Mail\\MailManager->createMailgunTransport()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(120): Illuminate\\Mail\\MailManager->createSymfonyTransport()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(95): Illuminate\\Mail\\MailManager->resolve()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(73): Illuminate\\Mail\\MailManager->get()
[2023-02-20 13:40:35] local.ERROR: Class "Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory" not found {"exception":"[object] (Error(code: 0): Class \"Symfony\\Component\\Mailer\\Bridge\\Mailgun\\Transport\\MailgunTransportFactory\" not found at /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php:278)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(161): Illuminate\\Mail\\MailManager->createMailgunTransport()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(120): Illuminate\\Mail\\MailManager->createSymfonyTransport()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(95): Illuminate\\Mail\\MailManager->resolve()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(73): Illuminate\\Mail\\MailManager->get()
```

I'm definitely also not getting the email.

### Expected behaviour

I receive an email from FIDI.

### Debug information

Debug information generated at 2023-02-20 14:01:53 Australia/Melbourne for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Australia/Melbourne |
| Browser TZ | Australia/Melbourne |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-02-01 00:00:00 |
| Session end | 2023-02-28 23:59:59 |
| Session first | 2000-09-22 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15 |

### Steps to reproduce

1. Set up FIDI to use mailgun using the `MAILGUN_DOMAIN`, `MAILGUN_SECRET`, `MAILGUN_ENDPOINT` environment variables, and set `MAIL_MAILER=mailgun`.
2. Fire a data import with the API (the example below shows `fidi`, because I'm doing this in `docker-compose`)
```
wget -qO- --post-data="" 'http://fidi:8080/autoimport?directory=/var/www/html/storage/configurations&secret=xxxxxxxxx'
```
3. Check the logs for FIDI. 

### Additional info

I'm running `fireflyiii/data-importer:latest` (`d56837468c0c`).

**Comment by JC5** [comment]
Nice find, I'll pick it up for the next release :+1:
