### ISSUE TITLE
Brave does not display line graph correctly

### ISSUE THREAD

**Issue by tekjoey** [firefly-iii/firefly-iii#7069]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When using Firefly-III through the Brave browser, the "Your accounts" line graph does not display properly. The dates along the bottom are not tilted, and hovering over an account line does not show the proper popup. This happens with both my own installation and the demo site. This does not happen when using Chrome, Edge, or Firefox.

![Screenshot](https://user-images.githubusercontent.com/53021430/220705672-3d42d3c4-7218-4e8c-a3c3-2a820ac27428.png)

### Expected behaviour

For the line graph to display properly, as it does with all other browsers.

### Debug information

Debug information generated at 2023-02-22 12:21:12 America/New_York for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-02-01 00:00:00 |
| Session end | 2023-02-28 23:59:59 |
| Session first | 2023-02-22 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 |

**Comment by JC5** [comment]
That's a shame. I'm not going to try and fix it. I'm working on a new layout and I want to focus my efforts on that.
