### ISSUE TITLE
Import explanation?

### ISSUE THREAD

**Issue by filipe-silva** [firefly-iii/firefly-iii#707]
Hello, I've tried using import but I just can't seem to make it work.

I made a csv with the following values; date, amount, description, then I selected the appropriated columns and checked "map these values", a new asset account is created with (no name).
What values do I need to have in my csv to sucefully import into my main asset account?
Or if possible what sql is needed to make import directly into database? I'm self hosting.

**Comment by JC5** [comment]
Which version are you running? You may have discovered a bug I was hoping nobody else would notice: https://github.com/firefly-iii/firefly-iii/issues/694

**Comment by JC5** [comment]
If the system does not match the transactions to the correct asset account one one side, and a new expense / revenue account on the other side, it's the same bug.

Try to [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode). When you import a file, a great number of details will be written to the debug log, which I would like you to share with me. That way, I can see what is happening exactly.

**Comment by filipe-silva** [comment]
Done and done, I imported one transaction to keep it simple. The log is attached, I changed the extension to txt because log extension is not allowed.

[firefly-iii-2017-07-19.txt](https://github.com/firefly-iii/firefly-iii/files/1159533/firefly-iii-2017-07-19.txt)

**Comment by JC5** [comment]
I think I see the bug. I will continue tomorrow and I should be able to fix it. Thank you for the logs and the extra information!

**Comment by JC5** [comment]
I have found the bug and it is fixed in the next release, which I hope to make available this weekend. Thank you for helping me find this!

As a bonus, here is the relevant part of the log file and how it should respond from now on:
```
[2017-07-21 02:30:27] local.DEBUG: Found NO existing accounts.  
[2017-07-21 02:30:27] local.DEBUG: Will try to find an asset account just in case.  
[2017-07-21 02:30:27] local.DEBUG: In findExistingObject() for Account  
[2017-07-21 02:30:27] local.DEBUG: Found NO existing accounts.  
[2017-07-21 02:30:27] local.DEBUG: Fall back to default account #1 "Checking Account"  
```

**Comment by filipe-silva** [comment]
Thanks! I'll keep a lookout for the new release and give you some feedback afterwards!
