### ISSUE TITLE
A small Chinese translation problem

### ISSUE THREAD

**Issue by MasterZhang007** [firefly-iii/firefly-iii#7076]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I found a small translation error in Chinese as the image below shows.

![image](https://user-images.githubusercontent.com/21271458/221120532-8bddc8e9-a88a-4100-ac6e-716eaf5ce992.png)

### Expected behaviour

Maximum should be translated as "最大" in Chinese.

### Debug information

No more information.

### Steps to reproduce

Chinese environment only:
1. Click Bills > Chart
2. Move your mouse over any item in the chart

**Comment by JC5** [comment]
Thanks for letting me know! You can submit translations at Crowdin: https://crowdin.com/project/firefly-iii

I'm not exactly sure which string this is, I can look it up later if necessary.

**Comment by MasterZhang007** [comment]
> Thanks for letting me know! You can submit translations at Crowdin: https://crowdin.com/project/firefly-iii
> 
> I'm not exactly sure which string this is, I can look it up later if necessary.

I tried to make it, but sorry, I can't locate the original string.

**Comment by JC5** [comment]
https://crowdin.com/translate/firefly-iii/142/en-zhcn?filter=basic&value=5#q=max-amount

Is now replaced with "最大"

**Comment by MasterZhang007** [comment]
thank you 👍
