### ISSUE TITLE
Calendar Week shown at wrong position in charts

### ISSUE THREAD

**Issue by ptrkb** [firefly-iii/firefly-iii#7079]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When showing Categories or the Accounts Detail Page (and probably some more) and selecting a date range starting January 1st 2022 + more than a year, the Week52 of year 2022 will be shown as the first value.
This also applies to your demo system, but only if you change the language to German. I'd guess it's something about the ISO Calendar Weeks, they often create problems for me...

![Bildschirm­foto 2023-02-24 um 21 29 22](https://user-images.githubusercontent.com/90598277/221285578-6c369b28-5c70-43d0-b3c7-7ceff3ad15dd.png)
![Bildschirm­foto 2023-02-24 um 21 31 36](https://user-images.githubusercontent.com/90598277/221285597-5da7437c-8e8a-4586-b783-e11fd169296c.png)

### Expected behaviour

CalendarWeek 52/2022 should be at the end of year 2022, not the beginning.

### Debug information

Debug information generated at 2023-02-24 21:34:23 Europe/Madrid for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Madrid |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2023-02-24 00:00:00 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15 |

### Steps to reproduce

In Demo System:
1. Change Language to German
2. Go to Konten -> Bestandskonten -> Select any account (alternatively Klassifizierung -> Kategorien -> Select any category)
3. Change Date Range to January 1st, 2022 to January 31, 2023
4. CW52 / 2022 is shown as first value

**Comment by JC5** [comment]
Week 52 includes January 1st. This is confusing but true.

**Comment by ptrkb** [comment]
> Week 52 includes January 1st. This is confusing but true.

That is true most of the time, but that should be Week52 of 2021 then, right? Week 52 of 2022 belongs to the end of 2022, not the beginning.

**Comment by JC5** [comment]
January 1st is in week 52, and it's in 2022. The fact that this particular week 52 starts in 2021 isn't part of the math.

I want to stress btw that I can't and won't fix this. I'm not going to mess around with [date and time libraries](https://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time).

**Comment by ptrkb** [comment]
I appreciate your quick responses, but I'd also appreciate if you'd look into my problem before brushing me off like that. I double-checked everything before creating an issue, and this is 100% wrong.

I created some more screenshots showing the issue, and this has nothing to do with changing date and time libraries. It's just sorted wrong.

Here is an extended version of the original screenshot. You can see, that there is a booking of 500 on January 5th, **2023**. This is not shown in 2023 (you can see the gap of that monthly payment). This is shown as CW52/2022 (which is the correct ISO Week representation of that week) at the beginning of 2022:
<img width="593" alt="Bildschirm­foto 2023-02-25 um 07 46 37" src="https://user-images.githubusercontent.com/90598277/221343208-1048c289-4eb2-4609-93f1-d8b8f53f7cde.png">

Here is the very same view when switched to English (US) language. Dashboard now starts with Week 1 2022, and the payment on January 5th, 2023 is shown at the proper place:
<img width="591" alt="Bildschirm­foto 2023-02-25 um 07 47 56" src="https://user-images.githubusercontent.com/90598277/221343305-c5b78856-0a2c-4bbe-91e8-d080f0cf091c.png">

**Comment by ptrkb** [comment]
One addition: Week52/2022 isn't the correct ISO Week, that would be 01/2023 for January 5th. But I wouldn't mind about this, as long as the dates are in order

**Comment by JC5** [comment]
> I appreciate your quick responses, but I'd also appreciate if you'd look into my problem before brushing me off like that. I double-checked everything before creating an issue, and this is 100% wrong.

Well, you never told we're talking about January 5th. So I'm glad we cleared that up. I'll see what I can find.

**Comment by ptrkb** [comment]
> > I appreciate your quick responses, but I'd also appreciate if you'd look into my problem before brushing me off like that. I double-checked everything before creating an issue, and this is 100% wrong.
> 
> Well, you never told we're talking about January 5th. So I'm glad we cleared that up. I'll see what I can find.

I didn't, because that was just an example I now found to pinpoint this, and the issue could be seen even in the demo system exactly like I wrote down in the first place. 
Anyways, thanks for looking into this. I appreciate your software, it's really helping me a lot.

**Comment by JC5** [comment]
Sorry, I never got the issue until you expanded on the problem. It still seems to be a library issue but now I know what to look for.

**Comment by JC5** [comment]
Found and fixed! Will be part of 6.0.0. Thanks for expanding on the issue, and your patience.

**Comment by ptrkb** [comment]
I tested this with the develop-version available on docker hub right now. Everything seems to be in the right order now, so I guess this fix is included there? I have some remarks, though. But here I'm really not sure if what I'm saying is valid:

- in your commit, it looks like you're now mixing non-ISO (w) with ISO (GGGG) week formats. I think that's what we see here - The first January 2022 booking is now Week 1, 2021.:
![Bildschirm­foto 2023-02-26 um 17 01 37](https://user-images.githubusercontent.com/90598277/221421948-92639778-5aee-4ea3-831e-f26467c5ce9c.png)
- I guess using W with GGGG should solve this? Although, I'm not sure what our American friends think about using ISO calendar weeks. I really hate this topic :)
- In general, it looks like everything is shifted one week to the past. The Booking of January 7th is shown in Week52/2021 (German) or Week1 (en_US), and I think this would be wrong in both systems.
![Bildschirm­foto 2023-02-26 um 17 00 32](https://user-images.githubusercontent.com/90598277/221422363-0a6b0855-5b3d-48bd-9c76-0deaeebef970.png)

Also, I don't really get why the German and en_US setting now show different calendar weeks now at all since the configs look the same right now, but I also don't really understand anything of your code so that's probably on me :)

**Comment by JC5** [comment]
That's an easy fix, thanks :+1:
