### ISSUE TITLE
Swagger API Docs: TransactionSplitUpdate: transaction_journal_id missing

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7082]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The doc makes a strong point to use `transaction_journal_id` [here](https://docs.firefly-iii.org/firefly-iii/api/specials), however it is missing from the `TransactionSplitUpdate` schema in the swagger documents.

Additionally, PUT requests to `/v1/transactions/{id}` without a `transaction_journal_id` and without creating a new split (i.e. updating a single transaction) fail without an error message, you are getting redirected to the login page instead.

### Expected behaviour

The field should be available in the Swagger Documentation.

Additionally, a proper error message would be great when the field is missing. Just redirecting to the login page was very confusing while debugging.

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

### Additional info

Since I cross-checked the requests the web page makes to the API, it seems also the `type` (deposit/withdrawal etc.) is missing from the swagger docs. However, test requests without the `type` attached succeed, so I guess it just uses the proper type for the source/target account combination?

**Comment by JC5** [comment]
Thanks for letting me know. I'll check it out. Until then:

- If you add `Accept: application/json` to your request you won't get redirected, but you'll get proper feedback.
- In PUT requests you don't need to put the type, if I remember correctly.

**Comment by JC5** [comment]
I've added the missing field to the docs (for API 2.0.0 onwards).
