### ISSUE TITLE
API Update Transaction: destination_id is required despite destination_name field

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7083]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi again,

playing some more with the API `PUT /v1/transactions/{id}`, a query like this won't change the destination account (testing with a deposit where `destination_name` is a valid asset account name): `{"transactions":[{"destination_name":"Asset Account","transaction_journal_id":"1234"}]}`

No error is returned. If other fields are present (for example `amount`), those fields are updated.

Giving both `source_name` and `destination_name`, neither will be updated (no matter if only source or destination or all have changed): `{"transactions":[{"source_name":"Source","destination_name":"Asset Account","transaction_journal_id":"1234"}]}`

To get the API to update, I must include a `destination_id` into the query - this works: `{"transactions":[{"destination_id":"1","transaction_journal_id":"1234"}]}`

### Expected behaviour

`destination_id` should not be required when `destination_name` is present.

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

**Comment by JC5** [comment]
I see what you mean, nice find. This will be fixed in 6.0.0
