### ISSUE TITLE
Swagger API Docs: TransactionSplitUpdate: type missing - required when adding new split.

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7085]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,

this is a follow-up to #7082 (thanks for fixing that btw!) and [your comment](https://github.com/firefly-iii/firefly-iii/issues/7082#issuecomment-1445321857) for `type`.

After playing some more with the API, I noticed that I always get `All splits must be of the same type.` when trying to add a new split via `PUT /v1/transactions/{id}` without the `type` parameter, even with `source_id` and `destination_id` set to proper account values where a type could be 'guessed':

`{"group_title":"TestSplit","transactions":[{"transaction_journal_id":"1234"},{"amount":"12.34","description":"New Split","order":1,"source_name":"Expense Account","source_id":"2","destination_id":"1","destination_name":"Asset Account"}]}`

The same call succeeds as soon as I add `type:"deposit"` to the second transaction.

### Expected behaviour

Either the field needs to be added to the swagger doc as well.

Or, I think the software does elsewhere, it could "guess" the transaction type based on the source/account IDs.

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

### Additional info

Sorry for all those bug reports, next time I'm stuck that long with a single API Call, I try to collect all feedback first before making a single bug report then :D

**Comment by JC5** [comment]
Haha not a problem, I'll expand the documentation. 😁
