### ISSUE TITLE
Add to piggy bank via API causes wrong Event History line

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#7093]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Posting `{"current_amount":{n}}` to `api/v1/piggy_banks/{b}` causes {n} to appear in the event history table of `piggy-banks/show/{b}`.

### Expected behaviour

In previous versions, {n} would not show up in the event history (current_amount). Rather, the amount added shows up in the event history, not the total.

### Debug information

Debug information generated at 2023-02-28 00:00:00 America/Phoenix for Firefly III version **6.0.0-beta.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0-beta.2 |
| Firefly III API | 2.0.0-beta.2 |
| Build | (unknown), (unknown) |
| DB version | 19 (exp. 19) |
| PHP | `8.2.2` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/xx |
| Browser TZ | America/xx |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 2097152 (2 MB) |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | pgsql |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-02-01 00:00:00 |
| Session end | 2023-02-28 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 5 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Steps to reproduce

1. Submit to API.
2. View event history.

**Comment by JC5** [comment]
Nice find, will be fixed in the final release.
