### ISSUE TITLE
Ability to record a breakdown of costs that contribute to a budget allocation

### ISSUE THREAD

**Issue by schtibal** [firefly-iii/firefly-iii#7096]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I agree with the "_a very good idea, but unfortunately..._" premise of sub-budgets, but it would be useful to be able to have some sort of record of why a budget number is what it is.

Eg, I have a broad annual budget for "Vehicles", which includes fuel, servicing, registration and insurance for 3 vehicles. For reporting, I can separate the costs by tags and/or categories. But I want to keep track of the makeup of that annual budget, I have to record it outside of Firefly.

### Solution

So my suggestion is to have a tabular form on the edit budget screen, which allows entry of pairs of description/amount which is only used to calculate and maintain a breakdown of what the total budget number is.

Eg:
"Vehicle rego" - $xxx
"Vehicle insurance" - $xxx
"Fuel" - $xxx

Or, at the very least, is to have a freeform notes field like in transactions or categories.

### What are alternatives?

Having to record this breakdown of items that contribute to the total budget allocation. or the thinking behind why that number was chosen outside of Firefly in a spreadsheet or other mechanism.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5523
