### ISSUE TITLE
Revenue accounts and graphs are only shown in USD, even if transacting with different currency.

### ISSUE THREAD

**Issue by xoomercom** [firefly-iii/firefly-iii#7098]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Revenue accounts are set to USD, there is no option to change.

When revenue transaction is completed this also erroneously shows graph in USD instead of the intended currency. 

### Expected behaviour

Add a field to set revenue account to specific currency and then show that currency on the graph? or show graph in the currency that the transactions are performed.

### Debug information

n/a

### Steps to reproduce

Create a revenue account.
Create revenue transaction (deposit) into account that's set with different currency.
On the transaction page click on revenue account to show activity.
Notice graph shows USD but the transaction was done in different currency.

### Additional info

Hope I am making sense, LMK if you need sample screenshots.

**Comment by JC5** [comment]
Revenue and expense accounts do not have their own currency but use the default currency. This is by design. I'm working on a new layout where these accounts can display multiple currencies. This has been requested repeatedly and is on my list. Thanks!

**Comment by xoomercom** [comment]
Thanks, correctly displaying multiple currencies would work.  Thanks much.

BTW, I'm on month 3 of using and I wanted to tell you BIG THANKS! - Your program is absolutely great!
