### ISSUE TITLE
Color difference on bills screen between expected or not is gone in dark mode

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#7104]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In light mode, you can easily see which bills are expected because the 'text-warning' class has a different color, and so does 'text-muted'.

In dark mode these colors are overridden, but only by the default dark mode color, there are no overrides for those classes in dark mode.

### Expected behaviour

I'd expect in dark mode there also to be an overridden color for those two classes, making it possible to see which bills are expected (but not paid yet) this period.

### Debug information

nothing needed, classes are above

### Steps to reproduce

Check the bills page

### Additional info

Very low prio issue

**Comment by JC5** [comment]
Nice find! Highest priority! 😉 

I'll pick it up 👍🏻
