### ISSUE TITLE
Getting 404 error for css

### ISSUE THREAD

**Issue by GaneshKandu** [firefly-iii/firefly-iii#7106]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,

I am trying to install firefly 6.0.0 but getting issue related to css and font load.

```
/v3-local/css/fonts.css?v=6.0.0
/v3-local/lib/fontawesome-free/css/all.min.css?v=6.0.0
/v3-local/lib/icheck-bootstrap/icheck-bootstrap.min.css?v=6.0.0
/v3-local/dist/css/adminlte.min.css?v=6.0.0
```

### Expected behaviour

it should load css and fonts.

### Debug information

I am trying to install on sub-directory of web root. ie. `` domain.com/ff-install``
not on VH setup

try install on sub-directory for debug. 

i want to know whether it's supported in sub folder and can be used without vhost.

**Comment by JC5** [comment]
The v3 layout is currently not supported in subdirectories.

**Comment by GaneshKandu** [comment]
> The v3 layout is currently not supported in subdirectories, sorry about that.
in future you plan to support ?

- how i can change layout to v1 for firefly 6.0.0 ?

i can see ``FIREFLY_III_LAYOUT=v1`` in firefly 6.0.0 is already v1.

**Comment by JC5** [comment]
Yes, I hope to fix this in the next release. Until then, it won't work.

**Comment by GaneshKandu** [comment]
Ok

**Comment by JC5** [comment]
Sorry about the confusion. Your fix was correct. I'll make sure to mention you in the changelog.
