### ISSUE TITLE
Update Notification Misreports

### ISSUE THREAD

**Issue by paulcalabro** [firefly-iii/firefly-iii#7112]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm seeing the following message within the UI:

```
You are running 5.7.18, which is newer than the latest release, v6.0.0. 
```

I believe it might be related to this code here:
https://github.com/firefly-iii/firefly-iii/blob/86d6a2f581f6066ec62f3416c8b1fabe3618bb9c/app/Services/FireflyIIIOrg/Update/UpdateRequest.php#L150

It might be because the version is prefixed with a `v`.

### Expected behaviour

I should be instructed to update my server.

### Debug information

Debug information generated at 2023-03-03 19:29:27 America/Phoenix for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Phoenix |
| Browser TZ | America/Phoenix |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `192.168.128.0/16` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2014-09-15 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 |

**Comment by JC5** [comment]
Nice find, I'll make sure it's fixed for the next release :+1:
