### ISSUE TITLE
Add Group Feature to Accounts

### ISSUE THREAD

**Issue by Chacsam** [firefly-iii/firefly-iii#7121]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Looking for an way to handle account sharing.

I have been exploring Firefly III for a few days and I must say it's a very nice app. 
I like its simplicity, nice interface, and local European touch (using wording and concepts close to home).
I have read and understood why shared account/multiple account don't work, so looking for an easy way to offer some easy multi-account display. 

### Solution

Would it be possible to extend the group concept to asset accounts and use it to easily filter dashboard & reports?

### What are alternatives?

Creating multiple accounts is no good solution as it would not ensure internal transfers consistency. (plus the burden of duplicating  other accounts, categories etc)

### Additional context

The concept of Shared Accounts is already a first step but doesn't offer enough granularity

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5753
