### ISSUE TITLE
Ability to toggle dark / light mode

### ISSUE THREAD

**Issue by gthbusrr** [firefly-iii/firefly-iii#7122]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- I would like to toggle Dark / Light modes
    - Right now, the lack of contrast in dark mode made it difficult to read. I wish there's a way that I can toggle between modes.

### Solution

A button next to the `+` button in the top right corner that toggles Dark / Light mode

**Comment by JC5** [comment]
Sorry no, you can use the toggle in your browser if you need it.

**Comment by gthbusrr** [comment]
@JC5 Toggling it in the browser will change the theme settings for all sites. Most sites let you toggle between dark / light mode.

I love dark mode in most things, just that I love light mode better on FF3.

Please, please, reconsider it.

**Comment by ngotchac** [comment]
Agreed, I couldn't find a way to disable dark mode for a single website on Firefox :/

**Comment by kenston** [comment]
I agree too that having an option in preferences will be better. As a temporary workaround I have to clone `skin-light.min.css` to `skin-dark.min.css`:
```
mv skin-dark.min.css skin-dark.min.css.bak
cp -p skin-dark.min.css skin-light.min.css
```
Now it works like light mode now in 6.0.2.
