### ISSUE TITLE
Liability Features

### ISSUE THREAD

**Issue by gthbusrr** [firefly-iii/firefly-iii#7123]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- Use different colour for positive, negative and zero Amount Due
- Allow sorting based on Amount Due
- (Maybe, allow a liability account to have multiple currencies like how existing accounts do)

### Solution

- Use red for negative Amount Due
- Use green / blue for positive Amount Due
- Use grey for zero Amount Due

- Allow sort by Amount Due (Like how reporting does)

### Additional context

- Current Liabilities View
    - <img width="398" alt="Screenshot 2023-03-04 at 13 53 37" src="https://user-images.githubusercontent.com/77537216/222923775-da6696d2-d1eb-4fcb-992a-16325bca8d6b.png">

- Current Reporting View (Sorted by `Difference`)
    - <img width="1460" alt="Screenshot 2023-03-04 at 13 54 17" src="https://user-images.githubusercontent.com/77537216/222923800-ba8203e5-a651-4f58-b7df-55003c19a899.png">

**Comment by JC5** [comment]
Sorry, I'm not going to expand the feature set in the current layout, as I'm working on a new one already. I'll keep this in mind when I'm working on https://github.com/firefly-iii/firefly-iii/issues/6303
