### ISSUE TITLE
Liability - Did not consier currency

### ISSUE THREAD

**Issue by gthbusrr** [firefly-iii/firefly-iii#7124]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

|Liability Account|Currency|Amount Due Shown|Actual Amount Due|
|:-:|:-:|:-:|:-:|
|A|Hong Kong Dollar|HK$100.00|C$100.00|

When I deposit C$100 from a C$ asset account to a HK$ liability account, the dashboard shows the Amount Due in the wrong currency

### Expected behaviour

Show amount due in the correct currency

### Debug information

Nil

### Steps to reproduce

1. Create a liability account in Currency A
2. Create a asset account in Currency B
3. Transfer money from asset account to liability account in Currency B

**Comment by JC5** [comment]
Thanks for reporting an issue. Did you include the amount in HK$ when you created the transaction?

**Comment by gthbusrr** [comment]
> Did you include the amount in HK$ when you created the transaction?

@JC5 No I did not

**Comment by gthbusrr** [comment]
# Transaction Creation `/transactions/create/withdrawal`
![Screenshot 2023-03-04 at 18 23 44](https://user-images.githubusercontent.com/77537216/222933149-764c3301-4988-4ea1-b418-4d388175e40a.png)

# Dashboard `/accounts/liabilities`
![Screenshot 2023-03-04 at 18 23 51](https://user-images.githubusercontent.com/77537216/222933153-6eee0a8c-9008-4403-a1d4-ce3614b7ffee.png)

# Details `/accounts/show/xxx`
<img width="1022" alt="Screenshot 2023-03-04 at 18 25 43" src="https://user-images.githubusercontent.com/77537216/222933191-8e8475b0-75fb-4cf2-9f64-a547878d2a52.png">

**Comment by JC5** [comment]
Thanks for the screenshots. Please make sure that you add the foreign amount. I will see if I can make it mandatory.
