### ISSUE TITLE
Foreign Currency got ignored when creating transaction from liability account to asset account

### ISSUE THREAD

**Issue by gthbusrr** [firefly-iii/firefly-iii#7125]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When creating a transaction from asset account to liability account, foreign currenct got ignored

# Account Info
|Name|Account Type|Currency|
|:-:|:-:|:-:|
|A|Asset|Canadian Dollar|
|B|Liability|Hong Kong Dollar|

# Transaction Info
|Source|Destination|Amount|Foreign Amount|
|:-:|:-:|:-:|:-:|
|B|A|HK$150|C$400|

<img width="2959" alt="Screenshot 2023-03-04 at 14 07 41" src="https://user-images.githubusercontent.com/77537216/222924605-315b529a-e46f-4a8a-8815-1d2742713f8f.png">
# Result     
<img width="1608" alt="Screenshot 2023-03-04 at 14 08 39" src="https://user-images.githubusercontent.com/77537216/222924609-e3138a23-1c56-4057-b241-b38581894ef4.png">

### Expected behaviour

<img width="1623" alt="Screenshot 2023-03-04 at 14 15 28" src="https://user-images.githubusercontent.com/77537216/222924635-e82dc1ba-6825-436b-b69d-6cca8cdadf9d.png">

### Debug information

<img width="1843" alt="Screenshot 2023-03-04 at 14 08 14" src="https://user-images.githubusercontent.com/77537216/222924649-93c1d46d-3dae-4d85-8e1b-25bab1de09c9.png">

### Additional info

Just a side note, should I ever create a transaction without info for the currency of the liability account, the amount due / the balance on the dashboard, the account view or in reports won't reference that transaction (AFAIK). Don't know if that's by design or a bug.

**Comment by JC5** [comment]
Nice find, I'll check it out!
