### ISSUE TITLE
Option to hide / show accounts in Dashboard Diagram

### ISSUE THREAD

**Issue by MilleniumEli** [firefly-iii/firefly-iii#7126]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

In the diagram on the Dashboard I would like to be have the option (e.g. via chebockes in the legend) to hide / show certain accounts. It would also be nice if I could display the total sum of all accounts.

P.S. Love the tool and thank you for the effort you put into it!

### Solution

Better usability. Especially when one account has a much higher balance than the other ones (e.g. savings account vs. day to day expenses) the diagram does not provide as much at-a-glance information as it could

**Comment by JC5** [comment]
You can hide accounts in your preferences :)

**Comment by MilleniumEli** [comment]
Thanks, I am aware of that. At least for my workflow it would still make sense to have the option directly on the Dashboard to quickly switch between accounts :) Might be a personal preference though...

**Comment by JC5** [comment]
Sorry, what you see is what you get :). Thanks for the compliments!
