### ISSUE TITLE
Delete unused accounts also purges Asset accounts 6.0.0

### ISSUE THREAD

**Issue by Kage1** [firefly-iii/firefly-iii#7127]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

WIth the 6.0.0 version a new purge accounts was added to clear out junk left over from imports. The option at Options -> Profile -> Delete and purge data -> Delete Unused Accounts also purges asset accounts. In this case there were two new asset account that were creating in ff3 and pending funding so they showed a zero balance. The Purge did clean out the Revenue and Expense accounts, but it also purged the new Asset accounts.

### Expected behaviour

Only purge Expense and Revenue accounts, there is no reason I can think of to purge an Asset account.

### Debug information

Debug information generated at 2023-03-04 00:00:00 America/Chicago for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Chicago |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-02-02 00:00:00 |
| Session end | 2023-03-04 23:59:59 |
| Session first | 2020-09-30 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Have an Empty asset account
2. Run the purge
3. Empty asset account is now gone

**Comment by JC5** [comment]
I'm sorry about the confusion, but the "delete unused accounts"-button does exactly what it promises. Luckily accounts are recreated quickly.

**Comment by JC5** [comment]
Reopened because I was wrong. The button will no longer remove liabilities and asset accounts.
