### ISSUE TITLE
Update tag pages

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#713]
- Remove tag types and references to them.
- Simple tag cloud + management page on index
- Ability to quickly show tag, show multiple tags in single view.

**Comment by JC5** [comment]
Can no longer use different tag types.

**Comment by cyberax17** [comment]
Hi, why is the feature of various tag types removed? Cheers

**Comment by JC5** [comment]
It's not really what tags are for: grouping transactions is OK but I added a lot of magical functionality. Special tag types with complex rules.

I'm currently working on the ability to link transactions. You can see this on the [demo site](https://firefly-iii.nder.be/). Log in, find a transaction and press "options". You can see the button "link transaction" which gives you the option to say (for example): "transaction A pays for B".

These links will (in the future) replace the special tag types. It's more flexible and more user friendly.
