### ISSUE TITLE
Reordering of assets are broken since v6.0.0

### ISSUE THREAD

**Issue by lflare** [firefly-iii/firefly-iii#7131]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Reordering of assets results in a new error message,

```
{"message":"Content-Type cannot be \"application\/x-www-form-urlencoded; charset=UTF-8\"","exception":"BadHttpHeaderException"}
```

![image](https://user-images.githubusercontent.com/22326991/222930672-2b6da63e-de43-4a25-883f-253de979447b.png)

### Expected behaviour

Reordering of assets should work normally.

### Debug information

This is irrelevant, I will be providing a fix shortly.

### Steps to reproduce

1. Create a couple of asset accounts in the v6.0.0 release.
2. Drag 'em around.
3. ???
4. Reordering does not work.

**Comment by JC5** [comment]
Nice find, and thanks for the fix! However, I've opted to fix this through `$.ajaxSetup()` so it's fixed for *all* endpoints that use similar code.

**Comment by lflare** [comment]
> Nice find, and thanks for the fix! However, I've opted to fix this through `$.ajaxSetup()` so it's fixed for _all_ endpoints that use similar code.

That's insufficient I think, it looks like `$.ajax` sends stuff directly as x-url-encoded, which means you still need to wrap `JSON.stringify({order: newOrder})`

**Comment by JC5** [comment]
It works fine for me though. What browser are you using?

**Comment by lflare** [comment]
> It works fine for me though. What browser are you using?

Hmm, it works, but I don't think it's the correct approach. As you can see below, the header is set correct, but the payload is distinctly not JSON.

![image](https://user-images.githubusercontent.com/22326991/222943853-c72ecf18-51b0-4d57-a9db-a2408d24968a.png)

![image](https://user-images.githubusercontent.com/22326991/222943839-47faf451-c308-4b13-b584-a22ba5ed2d3f.png)

**Comment by JC5** [comment]
I see what you mean, I didn't even notice. The endpoint isn't complaining but I've yet to reproduce it using Postman.

**Comment by lflare** [comment]
> I see what you mean, I didn't even notice. The endpoint isn't complaining but I've yet to reproduce it using Postman.

I just tested it live, while the endpoint isn't complaining, it isn't even saving the order. So it's returning a faux-200 status code.

**Comment by JC5** [comment]
I was about to update lol. I was wrong, you're right. `JSON.stringify()` is definitely necessary. Thanks for the pointer!
