### ISSUE TITLE
currency & foreign currency switched during CSV import

### ISSUE THREAD

**Issue by rel-thanu** [firefly-iii/firefly-iii#7138]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I don't think this is the same issue as #7125 or #7124 so I created a new issue. I apologise if it's the same!

### My accounts
| Name      | Currency |
| ----------- | ----------- |
| XYZ (CHF)     | CHF       |
| XYZ (USD)| USD        |

### CSV Import
- Default import account set to XYZ (USD)

| FIDI Role   	| Date       	| Opposing Account (Name) 	| Amount (Debit column) 	| Amount (Credit column) 	| Currency code (ISO 4217) 	| Amount (in foreign currency) 	| Foreign currency code (ISO 4217) 	|
|-------------	|------------	|-------------------------	|-----------------------	|------------------------	|--------------------------	|------------------------------	|----------------------------------	|
| CSV Headers 	| Booking    	| Description             	| Debit                 	| Credit                 	| Currency                 	| Foreign Amount               	| Foreign Currency                 	|
| CSV Row     	| 24.02.2023 	| XYZ (CHF)               	|                       	| 5'556.45               	| USD                      	| 5200                         	| CHF                              	|

### Result
Following transaction is created:
- Source: XYZ (CHF)
- Amount: CHF 5,556.45 ($5,200.00)
- Destination XYZ (USD)

### Expected behaviour

**Expected Transaction:**
- Source: XYZ (CHF)
- Amount:  CHF 5,200.00 (USD 5,556.45)
- Destination XYZ (USD)

### Debug information

Debug information generated at 2023-03-05 00:00:00 Europe/Amsterdam for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-12-31 23:59:59 |
| Session first | 2022-12-31 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Additional info

**My assessment**
I think it's switching the currency because the source account is in CHF, but the currency chosen is USD. Instead of switching only the currency, it should switch currency & the amount.

**Warning during import in FIDI**
Line #0: Line #0 may have had its currency changed (from "USD" to "CHF"). This happens because the associated asset account overrules the currency of the transaction.

**FIDI logs sending the transaction**
`[2023-03-05 15:13:11] local.DEBUG: Submitting to Firefly III: {"group_title":null,"error_if_duplicate_hash":true,"transactions":[{"type":"transfer","date":"2023-02-24 00:00:00","currency_id":null,"currency_code":"USD","amount":"5556.450000000000","description":"(empty description)","source_id":1,"source_name":null,"destination_id":5,"destination_name":null,"original-opposing-name":"FX CHF","foreign_amount":"5200.000000000000","foreign_currency_code":"CHF","original_source":"jc5-data-import-v1.0.2","tags":[],"source_iban":null,"source_number":null,"source_bic":null,"destination_iban":null,"destination_number":null,"destination_bic":null}]}`

**Comment by JC5** [comment]
Could you share a few example lines and your configuration file?

**Comment by JC5** [comment]
Never mind, managed to replicate it!
