### ISSUE TITLE
Import from Bunq API

### ISSUE THREAD

**Issue by Xeli** [firefly-iii/firefly-iii#714]
I've started using [Bunq](https://www.bunq.com) as my primary bank. They provide a pretty well documented [API](https://doc.bunq.com/), plus there are various (php) libraries which provide wrappers/bindings for the API. I am hoping to make adding transactions easier by using this API

The way I figured it might be implemented would be by storing a bunq API key and allow users to trigger the actual import whenever they want via some button. After the import is done it would react in the same way as importing via csv would go.

I would be happy to help with code to make this happen, would you be open to accepting code to implement this idea or have any ideas to improve upon the idea?

**Comment by JC5** [comment]
Hey Xeli, thanks for the suggestion! Yes, I use Bunq as well although it is not my primary bank.

As far as their API goes, I've seen it and I'm still on the fence about it. With the upcoming PSD2 directive I'm inclined to wait and see what other banks will do. I'm mainly curious about their workflow (authentication, authorization, etc.).  It will also be tricky to get users to configure the API, and it would become an advanced feature really fast: unlike tools like Mint or AFAS every user would need to get their own API key. 

Having said that, it's going to happen either way. So the first step (for me) would be to start experimenting and playing around. The workflow inside Firefly III would be need to be extended as well.

- The "import data"-screen changes to kind of list: CSV, Bunq, ABN, etc. CSV won't change.
- Each of those would have a one-time step ("needs configuration") where you enter your API key and what-not.
- There needs to be a (permanent) mapping from Bunq data to Firefly III data, with the interface to manage this.
- Something to fire the import, catch errors, show results.
- Command line thing to automate it.
- View to see history of import.

Could be quite a lot of work. But an experiment would simply be to see how the API works and what is available. I will hold off with integrating this into `develop` or even `master` but it sure is something to play with!

**Comment by JC5** [comment]
Unfortunately, the new model requires me to upgrade to bunq premium in order to get an API key.

Although I will continue to make the import routine ready for other bank as well as CSV files, there will be no bunq integration in the foreseeable future.

**Comment by JC5** [comment]
Apologies, this is not the case. I can still create an API key.

**Comment by Xeli** [comment]
You scared me :D

I didn't have much time last weekend to look at it, but from what I have read: PSD2 does not standardize any technology. So banks can pretty much roll out any software they want to comply. I've even heard things like sftp would be allowed... but this would also mean bunq's api already complies and odds are they won't change it drastically.

I have played around with some client side libraries for php. And perhaps we could use this call: https://doc.bunq.com/api/1/call/customer-statement-export/method/post

It gives back a csv or mt940. That might make the code pretty clean as we could reuse the existing csv import functionality.

**Comment by JC5** [comment]
Oh come on. The day before yesterday I was not able to create API keys. Yesterday I was, but I couldn't use it (needs to be verified in three hours).

Now, I get the "get bunq premium" popup again.

**Comment by JC5** [comment]
I've stopped working on this. I'll wait for more banks to come up with an API, see how this plays out.

**Comment by SpaceK33z** [comment]
@JC5 hi James, I was trying to use the Bunq import feature, which resulted in an error (` Cannot use type "bunq" for import job.`). According to this issue that is simply because the feature doesn't actually work yet. Is that still true?

**Comment by JC5** [comment]
That’s correct. I still have to get a new API key. In the next release the button will be invisible, until I have time to properly fix it. But even then it will probably be in beta for some time. I can only access the sand box so not all edge cases will be covered.

But don’t hold your breath, I don’t expect to get it working before January.
