### ISSUE TITLE
API Requests fail when Content-Type is "application/json; charset=utf-8" - ok without charset

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7140]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Starting with v6.0.0, previously possible requests fail when sending a `Content-Type: application/json; charset=utf-8` header:

`{"message":"Content-Type cannot be \"application\/json; charset=utf-8\"","exception":"BadHttpHeaderException"}`

The same request with `Content-Type: application/json` succeeds.

### Expected behaviour

The API should allow the charset parameter for Content-Type.

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 407, 02-03-2023 21:24:37 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

**Comment by JC5** [comment]
> The API should allow the charset parameter for Content-Type.

It should indeed! I'll pick it up!
