### ISSUE TITLE
Invalid redirect for v3 layout

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#7143]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi James!

First off, congrats for pulling off the v6.0.0 release, especially the dark mode is a super nice addition! 😍 

I came back to playing around with the v3 layout again, of course I won't open any issues regarding UI or sth yet since its still in development. However, I noticed a very strange redirect on my page:

- When I open `https://firefly.mydomain.com/v3/`, everything works fine.
- When I open `https://firefly.mydomain.com/v3`, I am redirected to `https://firefly.mydomain.com:8080/v3/` for some reason?

I'm using the Docker container behind a reverse proxy ([swag](https://github.com/linuxserver/docker-swag)). Do you have any clue why a redirection to Port 8080 could happen? My guess is that swag is redirecting the request to the Docker containers internal port, which is 8080, which leads Firefly III to believe that it's public port is 8080 as well.

### Expected behaviour

The redirect should respect the current port and only modify the path.

### Debug information

(Should not be relevant, but there you go)

Debug information generated at 2023-03-05 00:00:00 Europe/Berlin for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2020-05-15 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Steps to reproduce

1. Start a Docker instance behind a reverse proxy (e.g. swag).
2. Call the `/v3/` route, this should work as expected.
3. Call the `/v3` route, this should redirect to a different port.

### Additional info

I could not reproduce this on the demo site.

**Comment by JC5** [comment]
Thanks for the compliments! I'll check out the redirect 👍

**Comment by JC5** [comment]
This is not something specific to v3, all folders under the root redirect to an address with the port included. Some googling shows that this maybe a reverse proxy / Apache issue. I'll still try to fix this, but it's a bigger problem than v3 alone.

**Comment by JC5** [comment]
Since v3 is dropped, this is no longer relevant.

**Comment by niklas2810** [comment]
Hi James,

do you have any updates or suggestions on how to fix this issue? When trying out the new V2 layout, the same error resurfaces :( Navigating to `https://firefly.example.com/v2` redirects me to `https://firefly.example.com:8080/v2`, which is invalid of course. I'm still running Firefly III inside Docker (currently `v6.1.6`), but I switched to a new reverse proxy (which is still NGINX-based). 

My original theory for the origin of the bug still remains. Do you know if there is a way to change the port under which Firefly III is running inside the container? If yes, then I could change the port (e.g. via an environment variable) to 80 to test my theory. Side note: The original workaround of manually adding the second slash (`/v2/`) does _not_ work anymore. Now, I get a HTTP 403 Forbidden:

![grafik](https://github.com/firefly-iii/firefly-iii/assets/30748216/feab9125-16b4-4105-85d5-e6884b70945f)


Best wishes,
Niklas
