### ISSUE TITLE
Failed to open Debug Page

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#7144]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When opening the debug page for the first time after a restart, the page load fails due to a missing file (see stacktrace below).

```
Firefly III v6.0.0 ran into an error: file_get_contents(/var/www/html/storage/logs/ff3-cli-2023-03-05.log): Failed to open stream: No such file or directory.

The error was of type "ErrorException".

The error occurred on/at: Sun, 05 Mar 2023 17:39:57 +0100.

This error occurred in file "/var/www/html/app/Http/Controllers/DebugController.php" on line 191 with code 0. 
```

### Expected behaviour

The file should be ignored or created.

### Debug information

Stacktrace:
```
 #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/html/app/Http/Controllers/DebugController.php(191): file_get_contents()

-- truncated, let me know if you need more! The DebugController should be the interesting one though --
``` 

Debug information generated at 2023-03-05 00:00:00 Europe/Berlin for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2020-05-15 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Steps to reproduce

1. Create a fresh docker container (or clear you file system).
2. Open the debug page.

**Comment by JC5** [comment]
Indeed it should, nice find. Will pick it up.
