### ISSUE TITLE
Add sort feature during mapping of data (Data Importer)

### ISSUE THREAD

**Issue by rel-thanu** [firefly-iii/firefly-iii#7152]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

When importing a CSV file and mapping data (/import/mapping), it would be great to sort by not categorised rows. This will make the import process easier and more convenient.

### Solution

Automatically sort so that everything that is not mapped ("(do not map / automap)") is at the top.

### What are alternatives?

Manually go through the list and search for the rows that are not mapped yet.

**Comment by JC5** [comment]
Good idea, I'll write it down!

**Comment by JC5** [comment]
Before:

<img width="1309" alt="Screenshot 2023-08-20 at 06 27 18" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/91b02e70-9ece-484a-9b5f-c57a005e4991">

After:

<img width="1294" alt="Screenshot 2023-08-20 at 06 33 04" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/6f6fdac3-9c12-486b-8088-a5afc9d99f62">
