### ISSUE TITLE
Transactions with apotrophe's in their Description break "After store" options

### ISSUE THREAD

**Issue by aronwk-aaron** [firefly-iii/firefly-iii#7159]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When submitting a transaction with apotrophe in it's description, an error occurs with parsing. The error message in the console was related to create_transaction.

The transactions is stored, but the page does not redirect.

### Expected behaviour

The page should redirect to the intended endpoint

### Debug information

Debug information generated at 2023-03-06 00:00:00 America/Chicago for Firefly III version **6.0.0-beta.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0-beta.2 |
| Firefly III API | 2.0.0-beta.2 |
| Build | 395, 19-02-2023 11:39:58 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.2` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Chicago |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-02-01 00:00:00 |
| Session end | 2023-02-28 00:00:00 |
| Session first | 0007-01-27 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Steps to reproduce

1. create a transaction with an apotrophe in it's description. ex. `Wendy's`
2. fill in other details
3. check `After storing, return here to create another one.`
4. submit
5. see page not redirect and error in console

**Comment by JC5** [comment]
Nice find, I'll pick it up!
