### ISSUE TITLE
Rule triggers act as AND operator instead of OR?

### ISSUE THREAD

**Issue by sprucify** [firefly-iii/firefly-iii#716]
When I make a rule that needs to apply category "Car" to all my fuel expenses in the past I create multiple triggers in the rule.
Description contains: Shell
Description contains: Texaco
Description contains: BP

But it will not find results because it is probably searching as an AND operator for descriptions that contain all three words.

Is that intended behavior?

**Comment by JC5** [comment]
Yes it is. OR rules create uncertainty. AND rules do exactly what they say.

**Comment by sprucify** [comment]
Ok I understand.
So per brand a rule is the only option here.
Also no way to add multiple categories? :)

**Comment by JC5** [comment]
No, but you can add multiple tags :)

**Comment by JC5** [comment]
See for future developments: https://github.com/firefly-iii/firefly-iii/issues/1338
