### ISSUE TITLE
Rounding errors during import leading to duplicate transactions

### ISSUE THREAD

**Issue by deanpribetic** [firefly-iii/firefly-iii#7162]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am getting more duplicate entries in 6.0.0 due to rounding errors. I followed the procedure on the support pages and discovered that a transaction that is listed as `-11.20` in the .csv file is being imported once as:

`-11.200000000000000000000000`

and another time as

`11.199999999999999289457264`

Leading to the transaction being duplicated. 

### Expected behaviour

Expected behaviour is that both entries would be identified as `-11.20`, be flagged as a duplicate and then not imported.

**Comment by JC5** [comment]
Thanks for letting me know. Could you share some example lines and your configuration file please?

**Comment by JC5** [comment]
And some log files of the import please.

**Comment by deanpribetic** [comment]
Log file attached
[firefly_iii_fidi_1-2023-03-07T04-58-27.log.zip](https://github.com/firefly-iii/firefly-iii/files/10905602/firefly_iii_fidi_1-2023-03-07T04-58-27.log.zip)

**Comment by JC5** [comment]
Your log files do not seem to contain transactions that reflect this issue. Could you point me to a specific line in the file, in case I missed it?

**Comment by deanpribetic** [comment]
I can see several of the `-11.200000000000000000000000` entries at lines 5692, 5693, 5927. There are also some lines with 11.20 at 5690 and 5228-5232.

I couldn't find anything with `11.199999999999999 which is why it's odd. The `/debug/` pages definitely show the issue (see attached)

[id_95.txt](https://github.com/firefly-iii/firefly-iii/files/10905719/id_95.txt)
[id-66.txt](https://github.com/firefly-iii/firefly-iii/files/10905720/id-66.txt)

**Comment by JC5** [comment]
I see you share the debug output but it's not the original JSON. Do you have that as well?

Having said that, this issue may exist on the side of Firefly III itself. I'm curious, do you have logs of an import from the side of Firefly III itself?

**Comment by JC5** [comment]
Also, please share the output from the /debug page.

**Comment by deanpribetic** [comment]
Here is the debug JSON for transaction 66. Sorry, I deleted the other transaction!

[issue_66.json.txt](https://github.com/firefly-iii/firefly-iii/files/10906384/issue_66.json.txt)

How can I get the import side log from Firefly III?

**Comment by JC5** [comment]
No matter. I'll see what I can replicate before you need to search for logs.

**Comment by JC5** [comment]
I have nothing to report. I see that the amount is stored as "12.2" and "-12.2000000000" in a string.

What database are you using?

**Comment by deanpribetic** [comment]
I am using MariaDB (the `yobasystems/alpine-mariadb:latest` image). 

On line 40 of the issue_66.json.txt file there is this

<img width="564" alt="CleanShot 2023-03-08 at 07 25 43@2x" src="https://user-images.githubusercontent.com/4433093/223544258-d5f0e48c-1749-42b0-ab64-5561a39a19fe.png">

This is what I believe is causing the issue

**Comment by JC5** [comment]
Yes I see it. It's just that there is nothing in Firefly III that's rounding numbers. I'm at a loss right now. I'm sure I'll find it.

**Comment by deanpribetic** [comment]
I ran another import and got some more duplicates. I've isolated the transaction to a certain extent.

In the FIDI log it is identified as unique:

<img width="1234" alt="CleanShot 2023-03-08 at 16 10 06@2x" src="https://user-images.githubusercontent.com/4433093/223625082-2616c85c-926a-4a50-bd01-ea77b5886d91.png">

I have the two transactions attached as well. They have different hashes…not sure if that helps?

[id_72.json.txt](https://github.com/firefly-iii/firefly-iii/files/10917421/id_72.json.txt)
[id_110.json.txt](https://github.com/firefly-iii/firefly-iii/files/10917422/id_110.json.txt)

**Comment by JC5** [comment]
The detection method is "classic" which means it's not checked beforehand, it just gets submitted to Firefly III where it has to be determined if it is unique. I'll edit the logs to make it more clear. So that part depends on your import configuration.

**Comment by deanpribetic** [comment]
…actually…one thought. When I am importing I map the `DESCRIPTION` field from my bank to the `Opposing Account (name)` field in Firefly III. This would normally mean the `Description` field in Firefly III would have a value of `(empty description)`. However, after I import the rules I run will replace `(empty description)` with something else (e.g. `Groceries`)

Could it be possible that the comparison is seeing `(empty description)` and `Groceries` and flagging the new transaction as a duplicate?

**Comment by JC5** [comment]
No, because the hash is calculated before any rules are submitted, and it doesn't change when you change the transaction (using rules).

**Comment by JC5** [comment]
> How can I get the import side log from Firefly III?

https://docs.firefly-iii.org/firefly-iii/faq/other/#how-do-i-enable-debug-mode

I'm curious if you can catch one of these badly rounded transactions.

**Comment by deanpribetic** [comment]
I've turned those on - I will try another import tomorrow and send the logs across

**Comment by deanpribetic** [comment]
Hi - I won't get a chance to run another import today. However, I have had a thought that I'd like to test with you.

Remember…I am running mapping when I import and mapping the `DESCRIPTION` field from my bank with the `Opposing Account (name)` field in Firefly.

Let's say I run an import and there is a new `Opposing Account (name)` (ie one I haven't seen before). What I've been doing is leaving that as the field that the bank provides then cleaning it all up after the import.

Now, if I run a second import and there are some of the same transactions on there I have been mapping those to the appropriate account name (because I cleaned it up before). 

Would this potentially be flagged as a new transaction and thus create a duplicate?

**Comment by JC5** [comment]
No, because the hash used in the duplicate check doesn't change when you edit the transaction after it's imported.

**Comment by deanpribetic** [comment]
No…but would the hash for transaction 1 with Opposing Account Name of `OFFICEWORKS 0308` be different from a hash for transaction 2 with an Opposing Account Name of `Officeworks` if all the other details (amount, date) are the same?

**Comment by JC5** [comment]
Ah yes!

It would be, assuming that the change is made **before** the transaction is submitted to Firefly III.

**Comment by deanpribetic** [comment]
ah - I think we've got it. Not a bug then, I need to re-think my import workflow! 

Thanks so much for your patience and help with this, James.

**Comment by JC5** [comment]
Not a problem! Still curious about those rounding things. Are you doing some more processing on your end?

**Comment by deanpribetic** [comment]
Oh - no I am not. I had forgotten about those. I will keep an eye on it and see if changing my workflow fixes the issue.
