### ISSUE TITLE
Some links aren't rendered correctly when adding a new transaction

### ISSUE THREAD

**Issue by sharm294** [firefly-iii/firefly-iii#7165]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

It's a minor cosmetic issue but on my relatively new (and empty) installation of Firefly, if I go to add a new transaction, I see the following text under the bill dropdown: 

```
You seem to have no bills yet. You should create some on the <a href="bills">bills</a>-page. Bills can help you keep track of expenses.
```

Similarly, the budget dropdown has the same issue:

```
You seem to have no budgets yet. You should create some on the <a href="budgets">budgets</a>-page. Budgets can help you keep track of expenses.
```

In contrast, this text on the page has a correctly rendered link on the word `preferences`:

```
You can enable more transaction options in your preferences.
```

### Expected behaviour

The links should render correctly.

### Debug information

Debug information generated at 2023-03-06 00:00:00 America/Toronto for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

### Steps to reproduce

1. Have no existing bills or budget set up
2. Go to add a new transaction
3. Look at bills and budget dropdown areas

**Comment by JC5** [comment]
Yes, I know. I still have to fix them 😅 . Thanks for opening the issue!
