### ISSUE TITLE
Automation trigger "any transaction" also matches asset account opening balance transactions

### ISSUE THREAD

**Issue by welles** [firefly-iii/firefly-iii#7166]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I use a rule with the "any transaction" trigger to assign a "INBOX" tag to all newly imported transactions, to show me that I need to verify their information and assign budgets, bills, etc.
Unfortunately through the rule this tag has also been applied to the opening balance transaction of my asset account, which I cannot edit to remove the tag, since, when I click "Edit" on that transaction, it opens the editor for the account itself instead.

### Expected behaviour

The trigger "any transaction" should not apply to opening balance transactions, since they are not real transactions and cannot be edited.

### Debug information

Debug information generated at 2023-03-07 00:00:00 Europe/Berlin for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2023-03-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0 |

### Steps to reproduce

1. Create rule with only trigger "any transaction"
2. Set that rule to add a tag to the matched transactions
3. Execute the rule
4. Check the list of transactions with the tag. The opening balance transactions of your asset accounts will be in the list, which can not be edited

### Additional info

This presumably is a problem for all actions the rule would take. I only used a tag as an example because it is the behavior that I noticed the problem with.

**Comment by JC5** [comment]
Nice find, I'll pick it up!
