### ISSUE TITLE
Cannot mark account as active

### ISSUE THREAD

**Issue by NiceGuyIT** [firefly-iii/firefly-iii#717]
An asset* account cannot be marked as active. The demo site exhibits this behavior as well. This broke between 4.6.2 and 4.6.3 with the [Strict comparisons](https://github.com/firefly-iii/firefly-iii/commit/22144b78ea8a0c5c3b8292e6ce42badec25cd9e2) commit.

Note 1: Only asset accounts were tested. I haven't delved into other accounts yet.

**Comment by JC5** [comment]
Nice find, I'll fix it for the next release!

**Comment by JC5** [comment]
Pushed a fix, which will be included in the next release. Please note that the next FF3 release will require PHP7.1
