### ISSUE TITLE
Emojis are displayed as their raw unicode values

### ISSUE THREAD

**Issue by NullScope** [firefly-iii/firefly-iii#7172]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since 6.0.0 any new or updated transaction will show a lot of emojis as their raw unicode values instead of the browser's emoji. This is reproducible in the demo app

**Note:** In the examples below, all unicode characters are inside code blocks because they get transformed into the browser emoji

### Expected behaviour

Display the browser emoji instead of the unicode value, for example:
✈️ instead of `✈`

### Debug information

Debug information generated at 2023-03-08 00:00:00 Europe/Lisbon for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Lisbon |
| Browser TZ | Atlantic/Madeira |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | pt_PT |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2021-05-12 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0 |

### Steps to reproduce

1. Create new transaction with title "✈️ Airplane tickets"
2. Save transaction (any other info is irrelevant)
3. Transaction will be saved with the title "`✈` Airplane tickets" instead of the original one

### Additional info

Other emojis include a few generic arrow emojis as well (I use these in transfers) for example:
↕️ becomes `↕`

In Firefox, old transactions show the correct title, but in Chrome they already show up as wrong without updating them.

Here is an example of a split bill with the issue, note how the different emojis are used (Expense account was an already pre-v6.0.0 account). Also note that this isn't just about split bills, its just a real life example that I think best illustrates the issue at hand (with source account and values edited for privacy)
<img width="510" alt="imagem" src="https://user-images.githubusercontent.com/4614486/223747273-a51ce1c8-7fd8-44b0-99d0-f8604124710c.png">

**Comment by JC5** [comment]
Nice find, will be fixed in the next release :+1:

**Comment by NullScope** [comment]
Awesome, thank you so much!
