### ISSUE TITLE
Personal Token Creation Not Working

### ISSUE THREAD

**Issue by echofire26** [firefly-iii/firefly-iii#7173]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm in the process of installing Firefly III - Importer and go to create the "Personal Token" under: 
 Firefly III > Options > Profile > OAuth > 'Personal Access Tokens'.
The pop up starts and gives me the option to enter a name. I do and click create.  At that point nothing visually is generated that shows the key that is generated.  However, if I move away from the menu to another section like "Preferences" and then come back, something was generated and now there is a delete option
![create](https://user-images.githubusercontent.com/12430593/223760056-063e859a-a6fd-46a8-8fab-f8c04093fa55.jpg)
![result](https://user-images.githubusercontent.com/12430593/223760058-91e37096-00a9-452f-b6fe-25ad8f14305f.jpg)
.

### Expected behaviour

Based on the documentation, either another window or sub window should open with the appropriate key I'm supposed to use in the Importer setup.

### Debug information

...at this level and docker container environments I'm an absolute noob -- going to need instructions on how to get this --- sorry.

### Steps to reproduce

1. open Firefly
2. Go to the OAuth menu and choose the "Create" option and under "Personal Access Tokens."  
3. Enter a name for the token and click "Create"
4. Nothing happens....

**Comment by JC5** [comment]
Please see the other issue.

**Comment by JC5** [comment]
It's the same problem.

**Comment by echofire26** [comment]
Ok - and thanks -- sorry for the trouble - I'll try and read through that thread.

**Comment by JC5** [comment]
No problem. I'm on my phone. Try the mail_mailer thing. Should to the trick
