### ISSUE TITLE
Cron job fails with a 404 error

### ISSUE THREAD

**Issue by snyssen** [firefly-iii/firefly-iii#7177]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The cron job seems to fail repeatedly with the following error (which I receive by e-mail):

> Client error: `GET https://ff3exchangerates.z6.web.core.windows.net/2023/10/EUR.json` resulted in a `404 The requested content does not exist.`

I run the cron job with the following command:

```sh
docker exec firefly /usr/local/bin/php /var/www/html/artisan firefly-iii:cron
```

(`firefly` being the name of the Firefly III container)

### Expected behaviour

I am guessing the URL is outdated. I would expect the cron job to use a valid URL for fetching conversion rates.

### Debug information

Debug information generated at 2023-03-09 00:00:00 Europe/Brussels for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Brussels |
| Browser TZ | Europe/Brussels |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; WOW64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5504.206 Safari/537.36 |

### Steps to reproduce

1. Start Firefly with `ENABLE_EXTERNAL_RATES` set to true
2. Run the cron job using `/usr/local/bin/php /var/www/html/artisan firefly-iii:cron`
3. The cron job fails with a 404 error

### Additional info

You can find my whole docker-compose.yml (as a Jinja template for Ansible) [here](https://github.com/snyssen/infra-snyssen.be/blob/master/roles/container_firefly/templates/docker-compose.yml). I am also joining the full stack trace provided in the error e-mail, in case it helps:

```
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
#1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#5 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request()
#11 /var/www/html/app/Jobs/DownloadExchangeRates.php(105): GuzzleHttp\Client->get()
#12 /var/www/html/app/Jobs/DownloadExchangeRates.php(90): FireflyIII\Jobs\DownloadExchangeRates->downloadRates()
#13 /var/www/html/app/Support/Cronjobs/ExchangeRatesCronjob.php(83): FireflyIII\Jobs\DownloadExchangeRates->handle()
#14 /var/www/html/app/Support/Cronjobs/ExchangeRatesCronjob.php(70): FireflyIII\Support\Cronjobs\ExchangeRatesCronjob->fireExchangeRateJob()
#15 /var/www/html/app/Console/Commands/Tools/Cron.php(139): FireflyIII\Support\Cronjobs\ExchangeRatesCronjob->fire()
#16 /var/www/html/app/Console/Commands/Tools/Cron.php(80): FireflyIII\Console\Commands\Tools\Cron->exchangeRatesCronJob()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\Console\Commands\Tools\Cron->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\Container\Container->call()
#23 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\Component\Console\Command\Command->run()
#25 /var/www/html/vendor/symfony/console/Application.php(1022): Illuminate\Console\Command->run()
#26 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#27 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run()
#30 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#31 {main}
```

**Comment by JC5** [comment]
Nice find! Turns out it's me, not you. The GitHub action was disabled. I've since enabled it again and it should start working again. I've also made sure the script can handle this better in the future.

**Comment by JC5** [comment]
You just happened to catch me behind my PC lol. It could be that the cron will already start working. If not, 6.0.1 is released over the weekend. 👍
