### ISSUE TITLE
Recent transactions display across all accounts

### ISSUE THREAD

**Issue by gobeye** [firefly-iii/firefly-iii#7179]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to be able to review the most recent transactions added across all accounts in a single place whether they be withdrawals, deposits or transfers. I have regular bank import setup and while most of my setup is automated there is the occasional bit of editing required, this would be easier to complete in a single place.

### Solution

A single page or filter that could be used to display the most recent transactions (irrespective of type) across all accounts. The period that defines 'recent' could be user definable.

**Comment by JC5** [comment]
This is something that's on the list for the new layout: https://github.com/firefly-iii/firefly-iii/issues/6304
