### ISSUE TITLE
Pagination does not work

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#718]
When the list of transactions has enough items (and the pagination appears), when clicking on the page number, to go to the second page (for example), an error appears, and does not change the page.
I noticed that the "word" ---public--- is missing from the url link. Placing manualy the word in the url, the page appears correctly.
![error-page](https://user-images.githubusercontent.com/30444736/28589596-2e6ad2da-7155-11e7-9733-b43c6be98193.jpg)

**Comment by JC5** [comment]
I suspect I added a slash too many. Will be fixed!

**Comment by wtercato** [comment]
Okay.
I looked in the various files on the system where the function responsible for this feature is, but I did not find it.
If you can tell me where it is and how to correct it, I'll make the necessary changes myself.
Thank you very much.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/TransactionController.php#L81

https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/TransactionController.php#L89

https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/TransactionController.php#L96

I will probably replace these with the entire route, but I have to experiment first.

**Comment by wtercato** [comment]
Hello.
I made the suggested changes, and for now, it worked correctly.
Now you know the system better. Thank you very much.
See the picture as it was.
![link](https://user-images.githubusercontent.com/30444736/28629551-23b22880-71fe-11e7-8d51-22ccb8779dec.jpg)
![correct](https://user-images.githubusercontent.com/30444736/28629552-2518cc74-71fe-11e7-8d41-07ee778fd600.jpg)

**Comment by JC5** [comment]
You're welcome! The next release will also include this fix, but it will require PHP7.1 :)
