### ISSUE TITLE
Refill budget every two month

### ISSUE THREAD

**Issue by pawlakm** [firefly-iii/firefly-iii#7180]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello,
I would like to be able to add a fixed amount to a budget **every two month**
Could you please add this feature ?
Thank you in advance !

### Solution

Add two entries for budget "refill":
- every odd month
- every even month

### What are alternatives?

Currently I can add half the amount to a budget every month, however this makes things unclear as every two month there is "available" budget while this budget is to be reserved for the next month. If I spend money on this budget then everything may look "fine" while in reality I'm already overspending money.

### Additional context

Rationale: where I live multiple topics must be paid every two months, such as electricity, TV, phone, etc.

**Comment by JC5** [comment]
Thanks for the suggestion!

You won't be able to do this from Firefly III, and it will not be added. 

This is perfectly possible using the API though, but you'll have to script it yourself.
