### ISSUE TITLE
Have multiple frequencies for adding money to a single budget

### ISSUE THREAD

**Issue by pawlakm** [firefly-iii/firefly-iii#7181]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to be able for a single budget (for instance named "Telco") to configure multiple refill frequencies.
For instance I would like to:
- add 50.- every month
- add 80.- every quarter
- add 300 every 1st of March

### Solution

Enable amount splitting of the automatic amount added to a budget, each having its own frequency.

### What are alternatives?

Have multiple budgets, for instance "Telco 1: mobile phones", "Telco 2 : TV", Telco 3: yearly subscription" etc. Each having its own frequency. 
Unfortunately when havoing to do it for multiple budgets, it results in a multiplication of budgets which are unreadable.

### Additional context

I'm not asking for sub budgets, but for the ability to fill the budget on varioius frequencies, all adding a fixed amount to the same budget.
When spending money from the budget I want to use the budget name (in my example "Telco").

**Comment by JC5** [comment]
It is already possible to set multiple periods for a budget, but in the current layout it's a bit of a hassle. Change the Firefly III period in your preferences and then visit the budgets page. That will allow you to set budgets for different periods.

Keep in mind that the complexity you're looking for is not something I'm going to support from the UI, although it's perfectly possible to expand a single budget (or multiple budgets) in the way you describe. But you have to do it yourself using the API.
