### ISSUE TITLE
What date formats are supported in the importer?

### ISSUE THREAD

**Issue by nagyv** [firefly-iii/firefly-iii#7182]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I would like to use the importer to populate Firefly.

The following is an example transaction line from the CSV

```
type;booked_date;date;ID;amount;note_1;note_2;note_3;note_4;foreign_account;description;currency
Díj, jutalék;2023.02.28.;2023.02.28.;E00125735842001;-469,00;MobilBanking szolgáltatás;OneCard HK - havi díj;;;;OneCard HK - havi díj;HUF
```

The two date columns are configured as shown below:

<img width="1275" alt="Képernyőfotó 2023-03-09 - 21 20 03" src="https://user-images.githubusercontent.com/126671/224146051-8178d18e-3484-4cab-b905-bd5482a5fb09.png">

Firefly sets the date for today.

### Expected behaviour

Firefly should use the date from the `date` column.

### Debug information

Debug information generated at 2023-03-09 21:21:16 Europe/Budapest for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Budapest |
| Browser TZ | Europe/Budapest |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-02-07 00:00:00 |
| Session end | 2023-03-09 00:00:00 |
| Session first | 2020-12-13 00:00:00 |
| User ID | 1 |
| User language | hu_HU |
| User locale | hu_HU |
| Attempt at "hu_HU.utf8" | 'hu_HU.utf8' |
| Attempt at "hu_HU.UTF-8" | 'hu_HU.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Steps to reproduce

1. Create a CSV file with the provided lines
2. Import it to firefly, use the `date` column as `Date`
3. Check the date of the created transaction

### Additional info

I was looking for documentation on the accepted date format, but could not find it. I'm happy to open a PR to add this info to the doc.

**Comment by JC5** [comment]
This is in the documentation and on the configuration page itself. Good luck!

https://docs.firefly-iii.org/data-importer/how-to-use/configure-import/
