### ISSUE TITLE
Selecting date range locks date to today, v6.0.1

### ISSUE THREAD

**Issue by Kage1** [firefly-iii/firefly-iii#7186]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When selecting the date range selector at the top when selecting any other range except the preference default causes the interface to lock to today's date and can't be change further.

The data is all there and can be seen when selecting an asset account and selecting show all transactions.

I have my default for the dashboard to Last 30 days.

The only recovery I have found is restarting the container.

### Debug information

Debug information generated at 2023-03-10 00:00:00 America/Chicago for Firefly III version **6.0.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.1 |
| Firefly III API | 2.0.1 |
| Build | 413, 10-03-2023 19:20:57 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Chicago |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-10 18:43:01 |
| Session end | 2023-03-10 18:43:01 |
| Session first | 2020-09-30 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 |
```
Truncated from this point <----|[2023-03-10 18:53:13] local.ERROR: Cannot do endOfPeriod for $repeat_freq "last30"  
[2023-03-10 18:53:22] local.ERROR: Cannot do endOfPeriod for $repeat_freq "last30"  
[2023-03-10 18:53:36] local.ERROR: Cannot do endOfPeriod for $repeat_freq "MTD"  
[2023-03-10 18:53:43] local.ERROR: Cannot do endOfPeriod for $repeat_freq "MTD"  
[2023-03-10 18:53:48] local.ERROR: Cannot do endOfPeriod for $repeat_freq "MTD"  
[2023-03-10 18:53:51] local.ERROR: Cannot do endOfPeriod for $repeat_freq "MTD"  
[2023-03-10 18:53:56] local.ERROR: Cannot do endOfPeriod for $repeat_freq "MTD"  
[2023-03-10 18:54:12] local.ERROR: Cannot do endOfPeriod for $repeat_freq "last30"  
[2023-03-10 18:54:23] local.ERROR: Cannot do endOfPeriod for $repeat_freq "last30"  
[2023-03-10 18:54:28] local.ERROR: Cannot do endOfPeriod for $repeat_freq "last30"  
[2023-03-10 18:54:38] local.ERROR: Cannot do endOfPeriod for $repeat_freq "MTD"  
[2023-03-10 18:54:44] local.ERROR: Cannot do endOfPeriod for $repeat_freq "last30"  

```

### Expected behaviour

Allow date range selections

### Steps to reproduce

1. On the dashboard select a date range besides the default
2. Date is now locked to today

**Comment by JC5** [comment]
Nice find, will be fixed in the next patch!
