### ISSUE TITLE
Import job lost sight on withdrawals from saving account 

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#719]
Hello,

I'm trying to process the withdrawls and the deposits from my saving account to my expenses account. But the transaction is created as deposit instead of a transfer transaction.  The CSV contains lines like this to describe these transaction : 
"20170119","VAN Toprekening","Accountnumber","","GT","Bij","100,00","Internetbankieren",""

The transaction is registered like this in firefly:
![image](https://user-images.githubusercontent.com/5831104/28589336-e9c2469e-717d-11e7-83b7-ef685cef8d3b.png)

I'm kinda sure that this worked many versions ago
Is this a bug in the import routine or should i create a special kind of rule to correct this?

I'm using the latest available firefly version   

thanks in advance,

**Comment by JC5** [comment]
Could you run the import again with [debug mode enabled?](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode)

The log file should tell you what FF is doing with the line in question.

**Comment by leander091** [comment]
Hmm, this is the output based on the transaction amount and transaction id 

[2017-07-25 19:44:56] production.DEBUG: Annotated value {"role":"date-transaction","value":"20170607","mapped":null}
[2017-07-25 19:44:56] production.DEBUG: Annotated value {"role":"opposing-name","value":"Van Toprekening","mapped":null}
[2017-07-25 19:44:56] production.DEBUG: Annotated value {"role":"account-iban","value":"IBAN","mapped":1610}
[2017-07-25 19:44:56] production.DEBUG: Annotated value {"role":"_ignore","value":"GT","mapped":null}
[2017-07-25 19:44:56] production.DEBUG: Annotated value {"role":"ing-debet-credit","value":"Bij","mapped":null}
[2017-07-25 19:44:56] production.DEBUG: Annotated value {"role":"amount","value":"100,00","mapped":null}
[2017-07-25 19:44:56] production.DEBUG: Annotated value {"role":"_ignore","value":"Internetbankieren","mapped":null}

[2017-07-25 19:45:24] production.INFO: Imported new journal #12066 with description "(no description)" and amount EUR 100.
production.DEBUG: Linking journal #12066 to tag #6...
production.DEBUG: Looking for journal #12066 meta field "interest_date".
[2017-07-25 19:51:12] production.DEBUG: Looking for journal #12066 meta field "book_date".
[2017-07-25 19:51:12] production.DEBUG: Looking for journal #12066 meta field "process_date".
[2017-07-25 19:51:12] production.DEBUG: Looking for journal #12066 meta field "due_date".
[2017-07-25 19:51:12] production.DEBUG: Looking for journal #12066 meta field "payment_date".
[2017-07-25 19:51:12] production.DEBUG: Looking for journal #12066 meta field "invoice_date".
[2017-07-25 19:51:12] production.DEBUG: Looking for journal #12066 meta field "internal_reference".
[2017-07-25 19:51:12] production.DEBUG: Looking for journal #12066 meta field "notes".

**Comment by JC5** [comment]
There may be text before this line: `[2017-07-25 19:45:24] production.INFO: Imported new journal #12066 with description "(no description)" and amount EUR 100.`

**Comment by leander091** [comment]
Indeed there is, is there something where i should look for?

**Comment by JC5** [comment]
Just copy and paste everything until `imported journal #12065` so I can see what it was doing.

**Comment by leander091** [comment]
Could i send the file by mail? It is a rather big file with some personal information in it.

**Comment by JC5** [comment]
Of course. Please use my PGP key to encrypt the attachment, if you think it is prudent. 

https://firefly-iii.github.io/contact-information.html

**Comment by leander091** [comment]
I have sent the mail with the attachment.

**Comment by JC5** [comment]
Got it! When I have something, I'll let you know.

**Comment by JC5** [comment]
Starting at the line that goes:

```
Going to store object #99 with description "(no description)" 
```

In your file:

1. One mapping is done on the IBAN, ends on `88` and is mapped to an account-id ending with `10`.
2. Since the amount is positive, Firefly defaults to creating a deposit. 
3. FF3 searches for the "Van Toprekening" without a mapping (see below)

```
Find mapped account based on field "accountName" with value {"role":"opposing-name","value":"Van Toprekening","mapped":null} 
```

4. First attempt is to find a revenue account (since FF thinks this is a deposit). No dice:

```
Finding account of type 5 and name Van Toprekening.
Found nothing.
```
As a fallback it searches for an asset account (which _would_ make it a transfer). But alas.

```
Will try to find an asset account just in case.  
In findExistingObject() for Account  
Finding account of type 3 and name Van Toprekening  
Found nothing.  
```

So the first account is an asset account but the second one is created as a revenue account, making this a deposit:

```
Found no account of type Revenue account so must create one ourselves.
...
Created new account #1650 named "Van Toprekening" of type Revenue account.
```

If you map the "Van Toprekening" you should be fine.

**Comment by leander091** [comment]
Thanks for digging in to this. If i understand correctly I should link the the "Van Toprekening" to my asset account in the last step before the import actually starts?

**Comment by JC5** [comment]
Yes, that should do the trick!

Or, the asset account must be named (exactly) "Van Toprekening" and no such revenue account exists.

**Comment by leander091** [comment]
Thanks for your help, it's working the way it should.

**Comment by JC5** [comment]
I'm assuming that the opposing account is recognized as one of your asset accounts?

**Comment by leander091** [comment]
Indeed,  It creates an transfer from my expenses account to my  expenses account

![image](https://user-images.githubusercontent.com/5831104/29036240-eb152266-7b9e-11e7-9fb4-9d846629b362.png)

**Comment by JC5** [comment]
Yes, please. It shouldn't link the same account. Sorry for the late reply, this one slipped from my todo list.

**Comment by leander091** [comment]
I have sent the new log

**Comment by JC5** [comment]
Found it. The expense in question gets linked to your source account "ING Bank" because the expense in question gets written off by "ING Bank" as well.

I've added a routine that should prevent this. That should keep it falling back to an expense and not a transfer.

**Comment by JC5** [comment]
Release is live.
