### ISSUE TITLE
Using multiple browser tabs redirects to same page

### ISSUE THREAD

**Issue by TruffelNL** [firefly-iii/firefly-iii#7203]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When using multiple tabs in the browser, the tabs always redirect to the page of another tab after saving/editing/adding entries in firefly.
For instance I have multiple tabs open in my browser and in "Tab 1" I add a transaction (and leave it open, not saving it) while in the meaintime I add a categorie in "Tab 2" and save it. "Tab 2" is redirected to the page/url of "Tab 1". There is no text in the inputfields, but "Tab 2" shows the "add transaction" page.

### Debug information

Debug information generated at 2023-03-11 00:00:00 Europe/Amsterdam for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | nl_NL |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2020-02-06 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0 |

### Expected behaviour

I expect that different tabs adhere to the different breadcrumbs/history they have. I expect them to work the same as when I only have one tab open with Firefly. So after adding a transaction, I expect to return to the transaction overview screen. And for categories I expect to return to the categories overview screen.

### Steps to reproduce

1. Open two tabs with Firefly in your browser
3. Navigate one tab to the page for adding a transaction
4. Fill in transaction details (do not save/add)
5. In the second tab, navigatie to adding a category
6. Add a new category (do save this)
7. See the page being redirected to the "add transaction" screen

**Comment by JC5** [comment]
Yes I know. And no, I'm not going to fix this. The new layout will work better with multiple tabs.
