### ISSUE TITLE
Extend URL types possible in External URLs

### ISSUE THREAD

**Issue by muppie** [firefly-iii/firefly-iii#7204]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like the possibility to add other kinds of URLs in the External URL field other than "proper" URLs. I use Devonthink to store all my files, including receipts and invoices, and I would like to add that link (e.g. x-devonthink-item://17A225D9-C769-449D-8840-0D9D40842FD8) to the external URL field. Currently this is not possible. Message: The transactions.0.external_url format is invalid.

### Solution

Add the possibility to add other URLs other than http/https

### What are alternatives?

Currently I add the link in the Notes field but that messes with my mind when there is an external url field already present

### Additional context

.

**Comment by JC5** [comment]
It's on the list :)

**Comment by JC5** [comment]
The new release will allow you to set `VALID_URL_PROTOCOLS=https,something,whatever`, which will then be allowed as URL protocol.
