### ISSUE TITLE
Improve date range picking experience in dashboard

### ISSUE THREAD

**Issue by eruanno123** [firefly-iii/firefly-iii#7209]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

As a new Firefly III user, I imported all of my transaction data since 2011 into a self-hosted instance. However, I have noticed that selecting arbitrary date ranges in the past using the date picker is quite inefficient. The current calendar component suggests only the most common date ranges, such as "Month to date", and the "Custom range" option requires clicking and incrementing by one month at most, making it frustrating to select a distant range like 2013.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/3846502/224535794-1aa5c6b8-ed22-4e17-8ab2-afe9b0c7bd3e.png">

### Solution

After researching the closed issues, I found that the current calendar component being used in Firefly III is v-calendar, which supports the efficient selection of distant date ranges (see picture below). Therefore, I would like to request an upgrade to this component, or at least the addition of a feature that allows for keyboard input to edit date ranges.

<img width="227" alt="image" src="https://user-images.githubusercontent.com/3846502/224535674-20181f63-a1b7-452b-85a7-e345e04525a3.png">

OR

<img width="467" alt="image" src="https://user-images.githubusercontent.com/3846502/224536189-c3b2d252-c7d8-4b09-a541-62902db01312.png">

### What are alternatives?

The date range can be selected in the "Report" panel. But not in the dashboard.

**Comment by JC5** [comment]
This is something I plan to improve in the new layout. https://github.com/firefly-iii/firefly-iii/issues/6299

**Comment by eruanno123** [comment]
Great to hear!
Cheers
