### ISSUE TITLE
7138 still not fixed

### ISSUE THREAD

**Issue by rel-thanu** [firefly-iii/firefly-iii#7214]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi JC5, 

I just checked if issue #7138 was fixed, but is still not. Looking at the merge request, it seems to be only implemented for transactions of type "withdrawal" and "deposit", but not for a transfer transaction? 

I have attached a sample transaction + json so it's easier to verify. Or I could test it myself if it's in the develop branch so you don't have to push a new release everytime. :) 

[sample.zip](https://github.com/firefly-iii/firefly-iii/files/10951027/sample.zip)
-> Account ID 1 = Asset Account with CHF currency
-> Account ID 5 = Asset Account with USD currency

The error I receive now is: 
`Line #1: transactions.0.foreign_currency_code: This field value must match the currency of the destination account. (original value: "CHF").`

### Debug information

Debug information generated at 2023-03-12 15:00:46 Europe/Amsterdam for Firefly III Data Importer version **1.2.0**.

| Scope | Version |
| --- | --- |
| FIDI | 1.2.0 |
| Build | 198, 12-03-2023 11:16:01 CET |
| PHP | 8.2.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 |

**Comment by JC5** [comment]
I see it too, thanks! Working on it :+1:

**Comment by JC5** [comment]
Let me know if the latest code in the develop branch fixes it. Docker build 420 `develop`

**Comment by JC5** [comment]
Thanks, I think I found the root cause in the data importer. Try build 199 of the data importer, if you would. `develop`.

**Comment by JC5** [comment]
Glad to hear it, and no problem ofc!

**Comment by JC5** [comment]
v6.0.4 is out and includes the fix :+1:
