### ISSUE TITLE
Could not edit available budget since v6 release

### ISSUE THREAD

**Issue by fnouira** [firefly-iii/firefly-iii#7219]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since v6 release the pencil to edit available budget diapeared. I've also checked on the demo site and it's the same behaviour.

### Debug information

Debug information generated at 2023-03-13 00:00:00 Europe/Paris for Firefly III version **6.0.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.4 |
| Firefly III API | 2.0.1 |
| Build | 422, 12-03-2023 18:28:02 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Paris |
| Browser TZ | Europe/Paris |
| App environment | production |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `172.32.0.254` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | remote_user_guard  |
| Headers | HTTP_REMOTE_EMAIL, HTTP_REMOTE_EMAIL  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2016-10-14 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 |

### Expected behaviour

Reactivate the pencil next to available budget in budgets screen.

### Steps to reproduce

1. Open fireflyiii website
2. Go to /budgets
3. Try to edit available budget

**Comment by JC5** [comment]
This is not a bug. The functionality has been removed. The available budget will be calculated from the budgets set by the user.

**Comment by fnouira** [comment]
Thanks for your reply.
