### ISSUE TITLE
DataImporter does not accept any _FILE secrets or secrets in environment variables or API keys while the Firefly container does

### ISSUE THREAD

**Issue by JustEnoughDucks** [firefly-iii/firefly-iii#7222]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am running a firefly III instance for a long time. My bank after I moved has horrible manual .csv downloads, so I stopped running and maintaining it until I realized it was compatible with Nordigen. I updated and am now on Firefly III, v6.0.4.

I know that it is likely a configuration issue, but since I updated, my environment variable for the dataimporter does not connect anymore. 0 configuration change besides the update. I have `FIREFLY_III_URL` routed to the internal docker URL (192.168.90.20) and `VANITY_URL` set to the public available proxy URL. 

It can connect to the instance because if I leave the fields blank, it will go through the process of setting it up dynamically through OAuth and that works fine. It will also go through nordigen and to my bank if I choose the nordigen process since it will not recognize the file.

I have confirmed that the files are indeed loaded to /run/secrets and are correct within the container.

Compose file is under additional info.

There is little documentation on Nortigen/spectre besides a link, a small paragraph, and a disclaimer on their data collection, so I went through the process of creating a secret on their site and used that as the ID and KEY variables on my server.

What am I missing here? Do I have to just go through the process of setting OAuth certs and Nordigen secrets through the browser after it is loaded? Where are then my Nordigen secrets and the tokens stored?

### Debug information

Debug information generated at 2023-03-13 17:25:40 Europe/Amsterdam for Firefly III Data Importer version **1.2.1**.

| Scope | Version |
| --- | --- |
| FIDI | 1.2.1 |
| Build | 201, 12-03-2023 18:16:05 CET |
| PHP | 8.2.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/Brussels |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Expected behaviour

I expect that using FIREFLY_III_ACCESS_TOKEN_FILE will allow the dataimporter to access firefly iii

I expect using NORDIGEN_ID_FILE and NORDIGEN_KEY_FILE will use those secrets.

### Steps to reproduce

1. Generate API key and Nordigen secrets/keys
2. Put them into secret files
3. Load secret files in the dataimporter compose file
4. Spin up docker container
5. Try to access dataimporter web interface

### Additional info

```
version: "3.7"
services:

## Firefly III - Finance Manager

  ## Create a unique App Key which is a random 32 character string
    # date +%s | sha256sum | base64 | head -c 32 ; echo

  ## Suggested procedure to create new database:
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE firefly CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
    # GRANT ALL PRIVILEGES ON firefly.* TO 'firefly'@'firefly.mariadb' IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit

  firefly:
    container_name: firefly
    image: fireflyiii/core:latest
    restart: unless-stopped
    networks:
      web:
        ipv4_address: 192.168.90.20
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/firefly/export:/var/www/firefly-iii/storage/export
      - $USERDIR/docker/firefly/upload:/var/www/firefly-iii/storage/upload
      - $USERDIR/dockerconfig/firefly/upload:/var/www/html/storage/upload
      - $USERDIR/dockerconfig/firefly:/var/www/html/storage
    secrets:
      - firefly_db_password
      - firefly_app_key
    environment: # https://raw.githubusercontent.com/firefly-iii/firefly-iii/master/.env.example
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD_FILE=/run/secrets/firefly_db_password
      - APP_KEY_FILE=/run/secrets/firefly_app_key
      - APP_ENV=local
      - APP_LOG_LEVEL=info # debug, info, notice, warning, error, critical, alert, emergency
      - APP_URL=https://money.$DOMAINNAME
      - TRUSTED_PROXIES=**
      - SITE_OWNER=$MY_EMAIL
      - TZ=$TZ
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_DB="0"
      - REDIS_CACHE_DB="1"
#     - MAIL_DRIVER=smtp
#     - MAIL_HOST=protonmail-bridge
#     - MAIL_PORT=25
#     - MAIL_FROM=$PROTONMAIL_USER
#     - MAIL_USERNAME=$PROTONMAIL_USER
#     - MAIL_PASSWORD=$PROTONMAIL_PASS
#     - MAIL_ENCRYPTION=null
#     - CER_PROVIDER=ratesapi
      - SEND_TELEMETRY=false
#     - AUTHENTICATION_GUARD=remote_user_guard
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      ## HTTP Routers
      - "traefik.http.routers.firefly-rtr.entrypoints=https"
      - "traefik.http.routers.firefly-rtr.rule=Host(`money.$DOMAINNAME`)"
      - "traefik.http.routers.firefly-rtr.tls=true"
      ## Middlewares
#     - "traefik.http.routers.firefly-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.firefly-rtr.middlewares=chain-no-auth@file"
#     - "traefik.http.routers.photoprism-rtr.tls.passthrough=true" 
      ## HTTP Services
      - "traefik.http.routers.firefly-rtr.service=firefly-svc"
      - "traefik.http.services.firefly-svc.loadbalancer.server.port=8080"

## Firefly III CSV Importer
  dataimporter:
    container_name: dataimporter
    image: fireflyiii/data-importer:latest
    restart: unless-stopped
    depends_on:
      - firefly
    networks:
      - web
    secrets:
      - firefly_access_token
      - nordigen_id
      - nordigen_key
    environment:
      #- FIREFLY_III_ACCESS_TOKEN=$FIREFLY_ACCESS_TOKEN
      #- FIREFLY_III_ACCESS_TOKEN_FILE=/run/secrets/firefly_access_token
      - NORDIGEN_ID_FILE=/run/secrets/nordigen_id
      - NORDIGEN_KEY_FILE=/run/secrets/nordigen_key
      - NORDIGEN_SANDBOX=false
      - FIREFLY_III_URL=httpL//172.168.90.20
      - VANITY_URL=https://money.$DOMAINNAME
      - TRUSTED_PROXIES=**
      - SEND_TELEMETRY=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      ## HTTP Routers
      - "traefik.http.routers.csvimporter-rtr.entrypoints=https"
      - "traefik.http.routers.csvimporter-rtr.rule=Host(`csvimporter.$DOMAINNAME`)"
      - "traefik.http.routers.csvimporter-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.csvimporter-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.csvimporter-rtr.service=csvimporter-svc"
      - "traefik.http.services.csvimporter-svc.loadbalancer.server.port=8080"

secrets:
  firefly_db_password:
    file: $SECRETSDIR/FIREFLY_DB_PASSWORD
  firefly_app_key:
    file: $SECRETSDIR/FIREFLY_APP_KEY
  firefly_access_token:
    file: $SECRETSDIR/firefly_access_token
  nordigen_id:
    file: $SECRETSDIR/nordigen_id
  nordigen_key:
    file: $SECRETSDIR/nordigen_key

networks:
  web:
    external: true

```

**Comment by JC5** [comment]
The code for this hasn't changed in ages. Are you using Docker Swarm?

**Comment by JC5** [comment]
I've added some debug info to the `:develop` tag. Could you start the container and let me know what it says during boot?

**Comment by JustEnoughDucks** [comment]
thanks for that! Also, I am just using plain old docker compose. Not even a firefly .env file, just specifying environment variables in the compose file. 

I am assuming dataimporter develop?

```
Now in entrypoint.sh for Firefly III Data Importer
03/14/2023 6:58:56 PM
Script:        1.6 (2022-02-17)
03/14/2023 6:58:56 PM
User:          'root'
03/14/2023 6:58:56 PM
Group:         'root'
03/14/2023 6:58:56 PM
Working dir:   '/var/www/html'
03/14/2023 6:58:56 PM
Build number:  202
03/14/2023 6:58:56 PM
Build date:    14-03-2023 18:11:51 CET
03/14/2023 6:58:56 PM
Now parsing _FILE variables.
03/14/2023 6:58:56 PM
set FIREFLY_III_ACCESS_TOKEN from FIREFLY_III_ACCESS_TOKEN_FILE
03/14/2023 6:58:56 PM
set NORDIGEN_ID from NORDIGEN_ID_FILE
03/14/2023 6:58:56 PM
set NORDIGEN_KEY from NORDIGEN_KEY_FILE
03/14/2023 6:58:56 PM
done!
03/14/2023 6:58:58 PM
Firefly III data importer v1.2.1
03/14/2023 6:58:58 PM
PHP: cli 8.2.3 Linux
03/14/2023 6:58:58 PM
Will now run Apache web server:
03/14/2023 6:58:58 PM
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.90.18. Set the 'ServerName' directive globally to suppress this message
03/14/2023 6:58:58 PM
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.90.18. Set the 'ServerName' directive globally to suppress this message
03/14/2023 6:58:58 PM
[Tue Mar 14 17:58:58.333163 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) configured -- resuming normal operations
03/14/2023 6:58:58 PM
[Tue Mar 14 17:58:58.333204 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
03/14/2023 6:59:56 PM
127.0.0.1 - - [14/Mar/2023:17:59:56 +0000] "GET /robots.txt HTTP/1.1" 200 236 "-" "Firefly III Health Checker/1.0"
```

Now that I have an OAuth token, I think it is defaulting to using that. I will have to delete it and try again I think

**Comment by JC5** [comment]
Browse to `/flush` first, because authentication data is stored in your session.

Looking at the logs, i see it's setting values from _FILE variables correctly.

**Comment by JustEnoughDucks** [comment]
Thanks for your help. I flushed the authentication data and now the authentication errors went away. So maybe it was just holding bad authentication data for months somehow? I thought I deleted the volumes after I downed it, but possibly not.

Now I just get a:

`Tried "https://172.168.90.20/api/v1/about?" 5 times but failed: cURL error 28: Connection timed out after 31415 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://172.168.90.20/api/v1/about

so I'm not sure what that is about.
```
03/14/2023 7:59:01 PM
192.168.90.1 - - [14/Mar/2023:18:58:29 +0000] "GET /token/validate HTTP/1.1" 200 1335 "https://csvimporter.gerbhub.net/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0"
03/14/2023 7:59:04 PM
[2023-03-14 19:59:04] production.ERROR: Could not connect to Firefly III: Tried "https://172.168.90.20/api/v1/about?" 5 times but failed: cURL error 28: Connection timed out after 31415 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://172.168.90.20/api/v1/about  
```

**Comment by JC5** [comment]
That looks like a basic timeout, and since you're connecting to an IP + https, that might be the cause.

Could you open [a discussion](https://github.com/firefly-iii/firefly-iii/discussions/new?category=q-a) about this though? I believe this issue is solved.
