### ISSUE TITLE
Update checker displays wrong message when checking for updates from 5.7.18 to v6.0.4

### ISSUE THREAD

**Issue by Jmad12** [firefly-iii/firefly-iii#7223]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The update checker displays an incorrect message when checking for updates in 5.7.18

### Debug information

Debug information generated at 2023-03-13 19:09:57 Europe/Amsterdam for Firefly III version **5.7.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.18 |
| Firefly III API | 1.5.6 |
| Build | 346, 02-01-2023 16:12:50 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2023-01-22 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 |

### Expected behaviour

The update checker displays an incorrect message when checking for updates in 5.7.18

![image](https://user-images.githubusercontent.com/14036772/224790005-b242edeb-537b-4cd4-9ef0-806749d636a6.png)

The message reads

`You are running 5.7.18, which is newer than the latest release, v6.0.4.`

When it should read

`You are running 5.7.18, which is **older** than the latest release, v6.0.4.`

I assume this is due to the change in version formatting, adding the `v` before the version number.

### Steps to reproduce

1. On a fresh 5.7.18 install, go to /admin/update-check
2. Click on `Check now!`
3. The wrong message appears at the top of the ui

**Comment by JC5** [comment]
This has already been reported. I'm not sure which issue nr. Either way, it's fixed now but that won't help old releases. I'm aware of the problem.

**Comment by Jmad12** [comment]
I found it now. For doc purposes, it was issue #7112. Keep up the good work
