### ISSUE TITLE
Empty string when creating transaction and return here to create new one

### ISSUE THREAD

**Issue by blacktemplar** [firefly-iii/firefly-iii#7226]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since I updated to version 6.0.0 I get the following small glitch:

When I create a transaction, enter a title and all the details, then select "After storing, return here to create another one." and press "Submit" the transaction gets created successfully, but the text that appears doesn't contain the title.

I get a text a the top of the window saying 'Success! Transaction #xxxx ("") has been stored.' (see screenshot). Before version 6.0.0 it always printed the description of the transaction instead of the "".

![image](https://user-images.githubusercontent.com/3133334/224942965-abcd98f3-dd21-49e3-af5b-f5bd6fa97593.png)

### Debug information

Debug information generated at 2023-03-14 00:00:00 Europe/Vienna for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Vienna |
| Browser TZ | Europe/Vienna |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2020-03-25 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Expected behaviour

It should print something as follows:

Success! Transaction #xxxx ("description of the transaction") has been stored.

### Steps to reproduce

1. Click + and create new withdrawal
2. Enter transaction details including a description
3. Select "After storing, return here to create another one."
4. Click "Submit"

**Comment by JC5** [comment]
Thanks for reporting! Please upgrade to 6.0.4, I believe this is fixed already.

**Comment by blacktemplar** [comment]
Thanks for the quick response, stupid me, sorry for the spam in this case :(. I updated to 6.0.4 and it works now as expected :).
