### ISSUE TITLE
Unable to create a "After transaction update" webhook on 6.0.4

### ISSUE THREAD

**Issue by deanpribetic** [firefly-iii/firefly-iii#7227]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When creating (or editing) a webhook on page `/webhooks/create` if I select "After transaction update" as the Trigger the webhook will show "After transaction created" once the web hook is Submitted.

### Debug information

None

### Expected behaviour

Webhook would now have a trigger of "After transaction update"

### Steps to reproduce

1. Create a new webhook
2. Set the Trigger to "After Transaction update"
3. Submit the webhook

**Comment by deanpribetic** [comment]
Appears to be an off-by-one situation. If I change the trigger to "After transaction deleted" it now saves it as "After transaction updated"

**Comment by JC5** [comment]
Thanks for letting me know, I'll check it out 👍

**Comment by JC5** [comment]
> Appears to be an off-by-one situation. If I change the trigger to "After transaction deleted" it now saves it as "After transaction updated"

Close, but if you're interested: the dropdown triggers the current value, not the new value. Will be fixed in the next release. :+1:
