### ISSUE TITLE
Update message is unclear

### ISSUE THREAD

**Issue by EDOUNA** [firefly-iii/firefly-iii#7228]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The update message reads as follows: "You are running 6.0.0, which is newer than the latest release, v6.0.4.". This is a bit unclear, where implies that version 6.0.0 is newer than 6.0.4. Maybe replace the word _newer_ with _older_? Or change the sentence.

### Debug information

-

**Comment by JC5** [comment]
Several issues have been raised about this problem, and it's been fixed in future releases. Alas, I can't fix this for old releases which is ironic but true. Thanks for reporting.
