### ISSUE TITLE
Import - wrong date

### ISSUE THREAD

**Issue by ChristianPe** [firefly-iii/firefly-iii#723]
When trying to import a csv with more than 1 row, the transaction process date, the intereset date and the booking date are set to the current date of import, not the one specified in the csv. 
The first row in the import process is correct for some reason, any further row has the problem described above. The field with plain "date" is correct in any cases.

**Comment by JC5** [comment]
I'm sorry, I cannot confirm this. Which version are you running?

This is the result of importing three basic transactions:

```
date-transaction,date-rent,date-process,date-booking,description,amount
20170101,20170102,20170103,20170104,"Some test transaction 1",-12.34
20170105,20170106,20170107,20170108,"Some test transaction 2",-12.34
20170109,20170110,20170111,20170112,"Some test transaction 3",-12.34
```

![screen shot 2017-07-27 at 16 57 03](https://user-images.githubusercontent.com/5889984/28677058-b16dc2da-72ec-11e7-8219-75dbcf780f93.png)

**Comment by ChristianPe** [comment]
Im using the current master (2ddcf11). 

Looking at your example I guess I figured out what the problem is. Your date format is Ymd, mine is d.m.y which works well for the main date column, but seems to not work for the other ones in all cases (it was working in earlier versions though). 
When trying to import your example, everythings works fine. 
Try that one please:
`"date-book";"date-transaction";"description";"amount"
"16.01.17";"19.01.17";"test";"-3,49"
"17.01.17";"20.01.17";"test";"-3,49"
"18.01.17";"21.01.17";"test";"-3,49"`

Thank you for your great support 👍

**Comment by JC5** [comment]
You can change the date format when importing. I'm on mobile so I can't show you but it's there! 

And thanks!

**Comment by JC5** [comment]
Apologies, I think I misread your comment. Could you let me know if your issue has been solved?

You can change the date format in the first step of the CSV upload:

![screen shot 2017-07-29 at 08 18 05](https://user-images.githubusercontent.com/5889984/28742670-80ca9cb6-7436-11e7-83fb-9da2346000d3.png)

All date formats (rent, booking, etc) will be imported using this format.
