### ISSUE TITLE
Automated Import stop working

### ISSUE THREAD

**Issue by poudenes** [firefly-iii/firefly-iii#7235]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Worked perfect. But found out that within some days ago the automated import stop working

### Debug information

```
Script:        1.6 (2022-02-17)
User:          'root'
Group:         'root'
Working dir:   '/var/www/html'
Build number:  201
Build date:    12-03-2023 18:16:05 CET
Now parsing _FILE variables.
done!
Firefly III data importer v1.2.1
PHP: cli 8.2.3 Linux
Will launch auto import on /import directory.
No valid paths in IMPORT_DIR_ALLOWLIST, cannot continue.
Path "/import" is not in the list of allowed paths (IMPORT_DIR_ALLOWLIST).
```

```
docker run --rm \
-v /volumeUSB1/usbshare/docker/ff3_importer/automation:/import \
-e FIREFLY_III_URL=http://172.30.33.119:8080 \
-e FIREFLY_III_ACCESS_TOKEN=< MY TOKEN> \
-e NORDIGEN_ID=< NORDIGEN ID> \
-e NORDIGEN_KEY=< NORDIGEN KEY >2 \
-e IMPORT_DIR_WHITELIST=/import \
-e WEB_SERVER=false \
--net synology \
fireflyiii/data-importer:latest
```
```
pwd
/volumeUSB1/usbshare/docker/ff3_importer/automation
ash-4.4# ls -al -t
total 48
-rw-rw-rw-  1 poudenes users 1118 Mar  8 11:46 ing.json
-rwxrwxrwx  1 poudenes users 1114 Dec 30 09:06 rabobank.json
```

```
/volumeUSB1/usbshare/docker/ff3_importer
ash-4.4# ls -al -t
total 64
-rw-rw-rw-   1 poudenes users 1118 Mar  8 11:46 firefly_ing.json
drwxrwsrwx   3 poudenes users 4096 Mar  8 11:45 automation
-rwxrwxrwx   1 poudenes users 1114 Dec 30 09:06 firefly_rabobank.json
drwxrwsr-x   3       33    33 4096 Jul  5  2022 upload
```

### Expected behaviour

Everything seems good. In guide docker example is same so no new changes after a docker update.

**Comment by poudenes** [comment]
Found the error IMPORT_DIR_WHITELIST > IMPORT_DIR_ALLOWLIST
now its working again

**Comment by mattogodoy** [comment]
The same happened to me. I would like for these type of changes to be communicated as a warning in the app beforehand so it does not break automations.

**Comment by JC5** [comment]
They are. All you need to do is read the release notes.

**Comment by mattogodoy** [comment]
I get it, but with a breaking change like this, you usually support both variables for a while and show a warning in the meantime.
Don't get me wrong, I love the project and really appreciate your effort. It's just that it took me a long time to find the source of the problem and found it by chance in the release notes.
