### ISSUE TITLE
Add a sum of bills not yet paid in a given period

### ISSUE THREAD

**Issue by nick2k3** [firefly-iii/firefly-iii#7238]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

The bills page currently shows two sums:

Sum (Euro) (active and expected bills only) 
Expected monthly costs (Euro) (active bills only)

The list of bills above tracks which bills have been already paid or not.

What is missing though is a sum of what is still expected to arrive within the current month (although it could be extended to the period you are currently seeing).

### Solution

I propose to add another line:
Sum of remaining (unpaid) bills expected in this period:
= sum of active and expected bills - paid bills

### What are alternatives?

- identifying all the bills in the table which are marked as "Expected in... " which are within the desired period and sum them
- tracking the bills offline

### Additional context

It could be useful if one has many bills and an articulate paying schedule (with many quarterly or bi-monthly recurrence).

**Comment by JC5** [comment]
I'll see if I can add that in the new layout. See https://github.com/firefly-iii/firefly-iii/issues/6306
