### ISSUE TITLE
Docs homepage still have twitter link

### ISSUE THREAD

**Issue by drdada** [firefly-iii/firefly-iii#7247]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello,
I don't know if it's on purpose but the homepage of the doc still contain the twitter link instead of Mastodon
https://github.com/firefly-iii/docs/blob/main/docs/docs/firefly-iii/support/index.md

`- [Follow me around for news and updates on Twitter](https://twitter.com/Firefly_iii)`

### Debug information

N/A

**Comment by JC5** [comment]
Nice find, fixed :+1:
