### ISSUE TITLE
Firefly III: Add notification support for TG and WeChat Work etc.

### ISSUE THREAD

**Issue by realzsan3** [firefly-iii/firefly-iii#7260]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Firefly III hopes to support other communication tools when sending notifications of specific events, such as TG, WeChat; Slack is not very friendly to Chinese users, here is an example for reference, you can integrate mainstream API, or make it similar to postman’s call , Finally thank the author for his contribution, thank you https://raw.githubusercontent.com/ccwav/QLScript2/main/sendNotify.js

### Solution

add notifications for other im tools

**Comment by JC5** [comment]
Thank you for the suggestion. Unfortunately, this is out of my control. Only Laravel Notification channels are supported.

https://laravel-notification-channels.com/about/#suggesting-a-new-channel
