### ISSUE TITLE
The meny icons dissapear when the menu is collapsed

### ISSUE THREAD

**Issue by GabrielBarcia** [firefly-iii/firefly-iii#7261]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi

The browser is Chrome, and is setup in dark mode.
When the menu is collapsed from the top left, all icons or references dissapear, altough can be seen when highlighted.

Normal
![image](https://user-images.githubusercontent.com/4810944/226413550-0ab175e0-2e69-4c2a-ad2b-5ed50111e7fa.png)

When collapsed
![image](https://user-images.githubusercontent.com/4810944/226413734-582d4011-d647-4b6c-81c5-49d8ae26843e.png)

### Debug information

Debug information generated at 2023-03-20 00:00:00 Europe/Oslo for Firefly III version **6.0.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.5 |
| Firefly III API | 2.0.1 |
| Build | (unknown), (unknown) |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Oslo |
| Browser TZ | Europe/Oslo |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 2097152 (2 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 23:59:59 |
| Session first | 2020-01-25 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 |

### Expected behaviour

Expect the icons to be visible

### Steps to reproduce

1. Set the browser to dark mode
2. Colapse the main menu

### Additional info

This is clearly not big deal at all. It is reported because you may want to be aware of it :)

**Comment by JC5** [comment]
I see it, thanks! Will be fixed :+1:

**Comment by GabrielBarcia** [comment]
Works like a charm now. Thank you!
