### ISSUE TITLE
Suggestion: Show warning in list of bills when amount of transaction linked to bill falls outside expected range

### ISSUE THREAD

**Issue by welles** [firefly-iii/firefly-iii#7265]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Since bills have an expected minimum and maximum amount, I would love it if the bills page showed some kind of visual indicator when the amount that was actually paid for the bill in the linked transaction for the current period falls outside of those parameters.
This would tell me that either something unexpected happened when that bill was paid and I should review the receipt of that transaction, or that I need to update the parameters of the bill.
This visual indication could be something simple like a ⚠️ in the "Paid this period" column, but maybe a new column for "Amount paid this period" could also be useful.

### Solution

- Optional: Add new column "Amount paid this period" or expand "Paid this period" with amount paid
- Add warning indicator (e.g. ⚠️) somewhere to the bill if the linked transaction amount falls outside the bill's minimum/maximum amount

### What are alternatives?

This is a nive-to-have feature. Currently you can check the linked transaction for the actual amount paid and compare it to the expected amount, which takes a few clicks.

**Comment by JC5** [comment]
I'll see what I can do, perhaps in the new layout :+1:

**Comment by JC5** [comment]
Is on the list for https://github.com/firefly-iii/firefly-iii/issues/6306
