### ISSUE TITLE
Importing and tags

### ISSUE THREAD

**Issue by Elroban** [firefly-iii/firefly-iii#727]
I've been trying to get tags to be imported.
In my import CSV I tried both space seperated and comma seperated tags but none has been assigned after the import has run.

What I tried:
- Creating the tags before import
- Creating none of the tags before import
- Using tags as the last column within the import file
- Using tags not as the last column within the import file
- Mapping the tags with preregistered tags

None seems to be working.
As the demo site isn't allowing the import of files, I can't test there.

[Example.txt](https://github.com/firefly-iii/firefly-iii/files/1181183/Example.txt)

**Comment by JC5** [comment]
I'll spend some time on it this weekend and then the import should be able to handle tags. Please note that the next update of Firefly III will require PHP 7.1

**Comment by JC5** [comment]
I've pushed a fix which will be included with the next release. I'm going to close this issue to keep the list clean. Please let me know if something doesn't work as expected!
