### ISSUE TITLE
Make rule groups collapsible by clicking anywhere on the whole header

### ISSUE THREAD

**Issue by sharm294** [firefly-iii/firefly-iii#7272]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

#4031 made rule groups collapsible which is awesome but I'd like to be able to collapse/uncollapse the rule group by clicking anywhere along the header. Right now, the clickable button is on the far right which is pretty far away on my monitor from the rule group label on the left of the header.

### Solution

If the whole header is clickable, then you can more easily interact with the rule group as you're scanning down the text on the left.

### What are alternatives?

Use the existing button on the right to collapse/uncollapse the rule group.

**Comment by JC5** [comment]
Good idea, maybe in the new layout.
