### ISSUE TITLE
Change image (clip)

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#728]
Hello. When I attach a file, a signal (clip) appears indicating that this transaction has an attachment. Is it possible to change this image? I did not find her in the system ...!![](http://i.imgur.com/ZQwkiyN.jpg)

**Comment by JC5** [comment]
You can find all available icons here: http://fontawesome.io/icons/

Which icon did you have in mind?

**Comment by wtercato** [comment]
very cool.

I thought it was an image, but the clip is generated by a specific font ... I would like the clip to appear green, just that ...

thank you very much for the attention.
