### ISSUE TITLE
Set a default date range

### ISSUE THREAD

**Issue by damianeickhoff** [firefly-iii/firefly-iii#7283]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

So I've searched if this was asked before but couldn't find it. If it has, than sorry, you can close this!

What I'm missing is an option to set a default date range. I know I can set the date range in the right corner but that's just temporary. If I close Firefly, the next time I start it its back to the first of the month to the last of the month.

My financial month begins at the 24th. Me and my wife both getting our loan on that date so I want to know for example which contracts needs to be paid from the 24th till the 23th the next month. The 1st till the last day of that month doesn't give me the right insight. So setting a default date range would help me a lot so I don't have to set the custom date every time I'm using Firefly.

### Solution

Add an option to set an default date range which will stay selected after closing and opening Firefly and which will automatically move after the end of that custom date range has passed (like it does with the whole months).

### What are alternatives?

I don't think there is.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/#changing-the-monthly-cycle-to-another-day-of-the-month
