### ISSUE TITLE
currentMonthStart/currentMonthEnd not working for no-budget view

### ISSUE THREAD

**Issue by bradsk88** [firefly-iii/firefly-iii#7288]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Actual Behaviour
![image](https://user-images.githubusercontent.com/2147630/228129356-c2f77520-38c8-4141-b91a-4c9f0d849acf.png)

### Debug information

Debug information generated at 2023-03-28 00:00:00 Europe/Madrid for Firefly III version **6.0.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.5 |
| Firefly III API | 2.0.1 |
| Build | 424, 18-03-2023 14:53:12 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Madrid |
| Browser TZ | America/Regina |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 00:00:00 |
| Session first | 2022-02-09 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 |

### Expected behaviour

Navigating to this URL should show the "no-budget" transactions in the current month
```
/budgets/list/no-budget/currentMonthStart/currentMonthEnd
```

**Comment by JC5** [comment]
I don't think I ever implemented that so I'm not surprised. But I can see what I can do.

**Comment by bradsk88** [comment]
I can confirm I was using it on v5 :grin:
