### ISSUE TITLE
AH00141: Could not initialize random number generator

### ISSUE THREAD

**Issue by bzmjcster** [firefly-iii/firefly-iii#7290]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

(38)Function not implemented: AH00141: Could not initialize random number generator

### Debug information

(38)Function not implemented: AH00141: Could not initialize random number generator

### Expected behaviour

(38)Function not implemented: AH00141: Could not initialize random number generator

### Steps to reproduce

(38)Function not implemented: AH00141: Could not initialize random number generator

### Additional info

(38)Function not implemented: AH00141: Could not initialize random number generator

**Comment by JC5** [comment]
[Sorhttps://github.com/orgs/firefly-iii/discussions/7115](https://github.com/orgs/firefly-iii/discussions/7115)
