### ISSUE TITLE
Feature Request: Customize the Dashboard Report that generates the Balance Box (and link to report).

### ISSUE THREAD

**Issue by jwmay2012** [firefly-iii/firefly-iii#7294]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'd like to be able to customize the report that generates the Dashboard's `Balance` box. Specifically, I want the ability to include only specified asset accounts, or exclude some.
This would give better support for retirement accounts. 
Have retirement accounts in the net worth with full transaction history in their asset accounts available, without compromising the month to month usefulness of the Dashboard Balance and "default" monthly reports:
- Transfers from a checking account to an IRA asset account could be tracked and considered a negative (instead of net zero) to the monthly balance by excluding the IRA from the report powering the Dashboard.
- Income transactions from employer directly to a 401(k) could be tracked in an asset account (along with fees, dividends, etc), but excluded from the `Balance` box.
- Both accounts would be capable of being included in the Dashboard `Net Worth`, while excluded from the `Balance` box and the report linked by clicking `Balance`.

### Solution

How about add the ability to modify the underlying Report powering the Dashboard Balance box? 
Perhaps a copy of the `/preferences` `Home screen` page, but to choose accounts for the Balance Box default report? 

Another possible option that would create similar results for the homepage balance is to add an "exclude from balance" option as suggested by https://github.com/firefly-iii/firefly-iii/issues/1973. But I think the ability to customize the Dashboard reports is a more powerful solution.

I don't think we'd want to attach the `/preferences` `Home screen` selections to the `Balance` box, because then we should probably also tie it to the `Net Worth` calculation, and the whole point of this is to consider retirement account as NOT benefiting the montly `Balance` but still considered in the `Net Worth` report. Customizing the graphs reports, balance reports, and net worth reports separately seems like the better route to me.

You could also add a `Retirement` asset account type that behaves this way by default (excluded from Default Dashboard Balance). Or just add the `Retirement` type for fun and doesn't do anything in addition to the above.  :) 

### Scenario 1 - Checking asset account transfers to IRA:
I'm currently "solving" this by having my Checking withdrawals point to an IRA expense account, and then just modifying the virtual balance of an IRA asset account. 

But this prevents me from tracking dividends, income, fees, and the `returns` changes every month. In addition to raw contributions, I'd like to manually include a monthly `returns` transaction to keep the balance reconciled and accurate, and track changes over time. Since these would be considered "income" under the Dashboard Balance box calculation, the month to month usefulness of the dashboard would be disrupted. 

### Scenario 2 - Employer to 401(k) income:
There is no partial solution currently for this, AFAICT.
I can import all the detailed transactions just fine, and manually make `returns` adjustments like in Scenario 1, and this would get included in the Net Worth like I want, but then that's all considered income for the Dashboard Balance box.

The only solution here is to not track any of the transactions, and again, just create a 401(k) asset account with a virtual balance I update. No transaction history. 

### Additional context

Thanks for your work on Firefly and consideration! 😄

**Comment by JC5** [comment]
Thanks for the suggestions! The dashboard balance will be retired in the new layout, so unfortunately I can't take feature requests for it.
