### ISSUE TITLE
Available budget missing

### ISSUE THREAD

**Issue by AdalLS** [firefly-iii/firefly-iii#7296]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Yes, I know that issue #7219 has been closed because the functionality has been removed. 
However, the page in 6.0.5 still says on the left "Budgeted" and on the right "Available". Now the two amounts match.

However, would it be possible to restore that functionality? It was useful because you might be in a situation where you have X available money, but need to allocate Y amount of money to expenses that cannot be postponed. So seeing the difference was useful in trying to balance the remainder.

### Debug information

n/a

**Comment by JC5** [comment]
> However, would it be possible to restore that functionality? 

Sorry, this function will not be coming back.

**Comment by AdalLS** [comment]
Ok but then you should update the text displayed on that page as it still mentions the difference. That was the point of the issue.

As an aside, it would be nice if you could have maybe gauged support among users before removing features. Since it does not seem to have been replaced by a better system. Or is it in the plans?

**Comment by JC5** [comment]
Fair enough, I'll put it on my list. Keep in mind I removed it *because* i gauged support for it.
