### ISSUE TITLE
Hide inactive bills in overview page

### ISSUE THREAD

**Issue by C0nsultant** [firefly-iii/firefly-iii#7298]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

After 3+ years of continuous usage, the list of bills in my firefly-iii instance has grown significantly. In particular, there are currently 8 inactive bills that will almost certainly never be re-activated. I would like to keep these bills in the system to have the proper tracking across the linked transactions. With the current implementation, these permanently inactive but non-deleted bills will always be shown in the bill overview page.

Considering many other pages hide inactive objects on a separate page (e.g. accounts) or view (e.g. budgets), I kept hoping this would eventually also be the case for bills, but no luck so far.

### Solution

Hide inactive bills in the bill overview page (like in the accounts overview page) or display them in a different view (like in the budget view).

**Comment by JC5** [comment]
Good idea! Something to remember for the new layout. https://github.com/firefly-iii/firefly-iii/issues/6306

In the mean time, make a group called "old" and sort them at the bottom :+1:
