### ISSUE TITLE
API: Piggy Bank Update not working when no target amount is set

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7299]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When a piggy bank has no target amount, the following `PUT` call to `/api/v1/piggy-banks/<id>` resets the `current_amount` to 0 (the exact amount does not matter, 5 as an example):

`{"current_amount":"5.00"}`

As soon as I set a target amount (either including it in the same call, or setting it beforehand via the API/webinterface), the call works fine and it updates the piggy bank saved amount to 5.

Related to that: `target_amount` cannot be unset via the API, as it then complains that it should be greater than 0.

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.5 |
| Firefly III API | 2.0.1 |
| Build | 424, 18-03-2023 14:53:12 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

**Comment by JC5** [comment]
I can't replicate this. The following command works as expected.

```
curl --location --request PUT 'https://demo.firefly-iii.org/api/v1/piggy-banks/10' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer ey.......' \
--header 'Content-Type: application/json' \
--data '{"current_amount":"5.00"}'
```

Resetting the target amount doesn't work as it should, I'll pick that up.
