### ISSUE TITLE
Extra options for report drop down can stretch beyond lower limit of page

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#730]
Within Reports if the Extra options drop down has more than 5 selectable options they go off the bottom of the page and are not visible. 

Whilst there is a search box for filtering if there are several related categories (I have a dozen or so for related topic for instance which all start with the same first 8-10 characters) then this can be impossible to see the option you need.

Suggest that correct behaviour should be that the dropdown either becomes scrollable or is flipped to be a dropup

**Comment by JC5** [comment]
I'll see if I can fix that!

**Comment by JC5** [comment]
The library I use for the drop down is horribly outdated. I have to search for a new one. In the mean time, I've added a high div with no content to make the list visible. It's a hack but it works ;).

It will be live in the next release, which will require PHP7.1 minimum.
