### ISSUE TITLE
API: Piggy Bank Update not working when no target amount is set

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7308]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Reopening #7299 as the issue is not fixed.

Example from the demo site, default values, works as expected (call from your comment):

```
$  curl --location --request PUT 'https://demo.firefly-iii.org/api/v1/piggy-banks/10' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer ey...' \
--header 'Content-Type: application/json' \
--data '{"current_amount":"5.00"}'

{"data":{"type":"piggy_banks","id":"10","attributes":{"created_at":"2023-04-01T06:04:32+02:00","updated_at":"2023-04-01T08:08:18+02:00","account_id":"2","account_name":"Savings Account","name":"Fusce porta arcu sit amet ex tincidunt","currency_id":"1","currency_code":"EUR","currency_symbol":"\u20ac","currency_decimal_places":2,"target_amount":"50.00","percentage":10,"current_amount":"5.00","left_to_save":"45.00","save_per_month":"0","start_date":"2015-04-01T00:00:00+02:00","target_date":"2020-04-01T00:00:00+02:00","order":10,"active":true,"notes":null,"object_group_id":null,"object_group_order":null,"object_group_title":null},"links":{"self":"https:\/\/demo.firefly-iii.org\/api\/v1\/piggy_banks\/10","0":{"rel":"self","uri":"\/piggy_banks\/10"}}}}
```

After setting the target amount (via the demo website) to zero, and re-doing the call (no other changes in between, using `10.00` this time to expect a change):

```
$  curl --location --request PUT 'https://demo.firefly-iii.org/api/v1/piggy-banks/10' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer ey...' \
--header 'Content-Type: application/json' \
--data '{"current_amount":"10.00"}'

{"data":{"type":"piggy_banks","id":"10","attributes":{"created_at":"2023-04-01T06:04:32+02:00","updated_at":"2023-04-01T10:20:47+02:00","account_id":"2","account_name":"Savings Account","name":"Fusce porta arcu sit amet ex tincidunt","currency_id":"1","currency_code":"EUR","currency_symbol":"\u20ac","currency_decimal_places":2,"target_amount":"0.000000000000","percentage":null,"current_amount":"0.00","left_to_save":null,"save_per_month":null,"start_date":"2015-04-01T00:00:00+02:00","target_date":"2020-04-01T00:00:00+02:00","order":10,"active":true,"notes":null,"object_group_id":null,"object_group_order":null,"object_group_title":null},"links":{"self":"https:\/\/demo.firefly-iii.org\/api\/v1\/piggy_banks\/10","0":{"rel":"self","uri":"\/piggy_banks\/10"}}}}
```

Note how the second call returns `0.00` as `current_amount`. The website also reports zero for the piggy bank after the second call:

![image](https://user-images.githubusercontent.com/109872040/229275159-a0e3d1f9-bc33-4bdd-8912-e0d9346dd5bf.png)

There is no default piggy bank with a zero target amount on the demo website, so a manual change is required.

### Debug information

Demo Site (debug page not available)

**Comment by JC5** [comment]
I swear I tested that as well lol. Thanks for reopening the issue, it was auto-closed.
