### ISSUE TITLE
Poor contrast on dark theme success banner

### ISSUE THREAD

**Issue by elliot-gh** [firefly-iii/firefly-iii#7310]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After creating a transaction on dark theme, the success banner has a link to the new transaction that is nearly impossible to read:
![image](https://user-images.githubusercontent.com/5415760/229279450-aea33b37-120d-4076-9529-c4076a016e99.png)

### Debug information

Debug information generated at 2023-04-01 00:00:00 America/Los_Angeles for Firefly III version **6.0.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.6 |
| Firefly III API | 2.0.1 |
| Build | 441, 01-04-2023 08:04:21 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Los_Angeles |
| Browser TZ | America/Los_Angeles |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `172.28.0.1` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-04-30 23:59:59 |
| Session first | 2020-08-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 |

### Additional info

I really appreciate the continuous work on the dark theme!

**Comment by JC5** [comment]
Thanks! Ill pick it up!
