### ISSUE TITLE
API: budget-limits should accept startDate = endDate

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7311]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Currently, `v1/budget-limits` does not accept calls where `start` is equal to `end`, and throws an error that `end` should be after `start`. This means you're unable to get the budgets which are applying to the current day only.

### Debug information

Debug information generated at 2023-04-01 00:00:00 Europe/Vienna for Firefly III version **6.0.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.5 |
| Firefly III API | 2.0.1 |
| Build | 424, 18-03-2023 14:53:12 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

### Expected behaviour

Similar to other endpoints like the `v1/insight/*` ones, you should be able to fetch data which applies only to the current day.

### Additional info

I actually noticed this when trying to list the budgets for the current month _so far_, it errors out on the first day of a month (like today).

**Comment by JC5** [comment]
Ah nice find, it should accept that indeed.
