### ISSUE TITLE
Can't set available amount for all budgets over a period

### ISSUE THREAD

**Issue by schleiferjunge** [firefly-iii/firefly-iii#7318]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

On site `/budgets` can't set the available monthly amount (missing pencil icon).

<img width="835" alt="image" src="https://user-images.githubusercontent.com/52082704/229368962-409e10f7-7239-41b0-b76f-c3c4fe13f67d.png">

### Debug information

Debug information generated at 2023-04-02 00:00:00 Europe/Berlin for Firefly III version **6.0.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.6 |
| Firefly III API | 2.0.1 |
| Build | 441, 01-04-2023 08:04:21 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-04-30 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15 |

### Expected behaviour

Seeing a pencil icon to set the available budget amount.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/releases/tag/v6.0.0

See under "removed".
