### ISSUE TITLE
Inconsistent rule behavior with description matching

### ISSUE THREAD

**Issue by caseymullineaux** [firefly-iii/firefly-iii#7324]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm trying to do some simple categorization of transactions using rules. 
I've created a bunch of rules to match the description of a transactions, and use that to add a category and a tag as the actions.
Here's an example:
![image](https://user-images.githubusercontent.com/25874787/229405462-a14d3e66-3cc6-4978-97ec-87553db3c709.png)

After creating the rule in non-strict mode and previewing the rule from the rule list, it shows that there are no matching transactions.
![image](https://user-images.githubusercontent.com/25874787/229405655-73d5c4ac-a0e5-491e-a39e-537d35cfd877.png)
If I run the rule anyway, no transactions are modified.

If I then edit the rule and click the `See matching transactions` button, matching transactions are correctly displayed.
If I now turn strict mode on and leave everything else untouched, save the rule and run the preview from the rule list just like before, matching transactions are correctly displayed.
If I then edit the rule one more time and disable strict mode so it is exactly as it was when it was created, save the rule and the preview from the rule list, it now returns matching transactions as I would have expected when the rule was first created.
![image](https://user-images.githubusercontent.com/25874787/229408956-19af203b-a65d-472b-b08d-1d4211abe2b8.png)
Running the rule now correctly categorizes and tags the transactions as expected.

### Debug information

Debug information generated at 2023-04-03 00:00:00 Australia/Sydney for Firefly III version **6.0.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.6 |
| Firefly III API | 2.0.1 |
| Build | 441, 01-04-2023 08:04:21 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Australia/Sydney |
| Browser TZ | Australia/Sydney |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | en_AU |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-06-30 00:00:00 |
| Session first | 2020-12-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.0.0 |

### Expected behaviour

A rule that uses the `Description Contains` trigger will successfully match transactions without having to enable and disable strict mode on the rule after the rule is created.

### Steps to reproduce

1. Create a new rule with the `description contains` trigger
2. Preview the rule and observe no results returned
3. Modify the rule and enable/disable strict mode
4. Preview the rule and observe that results are now shown
5. Modify the rule and undo the change made in step 3 so the rule is now in the same state as when created
6. Preview the rule and observe that results are now shown

**Comment by JC5** [comment]
Thanks for letting me know! This is consistent with another issue I found regarding the rules, and I expect this is already fixed.

If you have the time, try this on the demo site. It should work as expected over there.

**Comment by caseymullineaux** [comment]
Tested on the demo site and confirm the issue does not exist there. 👍

**Comment by JC5** [comment]
Glad to hear it! Thanks for testing this. I'm not sure yet when the next release will be out but it should be within two weeks.

**Comment by caseymullineaux** [comment]
Awesome! I'll keep an eye out for the release.
Thanks very much for the quick response ⚡👍

**Comment by JC5** [comment]
This is now fixed and live.
