### ISSUE TITLE
Reconcile screen reporting a 431 Request Header Fields Too Large error

### ISSUE THREAD

**Issue by fnouira** [firefly-iii/firefly-iii#7327]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

First of all, thanks a lot for this awesome tool ...
After reconciling my asset account, I found that the Reconcile button does not work (no error message shown).
When I looked into my browser's console, I found that the action behinf the  button is returning a HTTP 431 error.

### Debug information

Debug information generated at 2023-04-04 00:00:00 Europe/Paris for Firefly III version **6.0.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.6 |
| Firefly III API | 2.0.1 |
| Build | 441, 01-04-2023 08:04:21 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Paris |
| Browser TZ | Europe/Paris |
| App environment | production |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `172.32.0.254` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-03-01 00:00:00 |
| Session end | 2023-03-31 00:00:00 |
| Session first | 2016-10-14 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 |

### Expected behaviour

Reconcile my account even if it's too many transactions (in my case it was 122 transactions)

### Steps to reproduce

1. Go To Reconcile screen
2. Try to reconcile too many transaction (122 transactions in my case)

### Additional info

Sample query:
https://fireflybaseurl/accounts/reconcile/1/overview/2023-03-01/2023-03-31?startBalance=0.00&endBalance=0.00&startDate=2023-03-01&startEnd=2023-03-31&journals%5B%5D=18958&journals%5B%5D=18957&journals%5B%5D=18956&journals%5B%5D=18955&journals%5B%5D=18954&journals%5B%5D=18951&journals%5B%5D=18950&journals%5B%5D=18946&journals%5B%5D=18949&journals%5B%5D=18948&journals%5B%5D=18947&journals%5B%5D=18945&journals%5B%5D=18938&journals%5B%5D=18937&journals%5B%5D=18936&journals%5B%5D=18935&journals%5B%5D=18932&journals%5B%5D=18931&journals%5B%5D=18930&journals%5B%5D=18929&journals%5B%5D=18928&journals%5B%5D=18927&journals%5B%5D=18924&journals%5B%5D=18923&journals%5B%5D=18926&journals%5B%5D=18925&journals%5B%5D=18922&journals%5B%5D=18921&journals%5B%5D=18920&journals%5B%5D=18919&journals%5B%5D=18918&journals%5B%5D=18917&journals%5B%5D=18916&journals%5B%5D=18913&journals%5B%5D=18915&journals%5B%5D=18914&journals%5B%5D=18910&journals%5B%5D=18912&journals%5B%5D=18911&journals%5B%5D=18909&journals%5B%5D=18908&journals%5B%5D=18907&journals%5B%5D=18906&journals%5B%5D=18905&journals%5B%5D=18904&journals%5B%5D=18903&journals%5B%5D=18902&journals%5B%5D=18901&journals%5B%5D=18900&journals%5B%5D=18891&journals%5B%5D=18899&journals%5B%5D=18898&journals%5B%5D=18897&journals%5B%5D=18896&journals%5B%5D=18895&journals%5B%5D=18894&journals%5B%5D=18893&journals%5B%5D=18892&journals%5B%5D=18890&journals%5B%5D=18889&journals%5B%5D=18885&journals%5B%5D=18883&journals%5B%5D=18882&journals%5B%5D=18888&journals%5B%5D=18887&journals%5B%5D=18886&journals%5B%5D=18857&journals%5B%5D=18856&journals%5B%5D=18855&journals%5B%5D=18854&journals%5B%5D=18853&journals%5B%5D=18852&journals%5B%5D=18884&journals%5B%5D=18881&journals%5B%5D=18866&journals%5B%5D=18880&journals%5B%5D=18879&journals%5B%5D=18878&journals%5B%5D=18877&journals%5B%5D=18876&journals%5B%5D=18875&journals%5B%5D=18872&journals%5B%5D=18871&journals%5B%5D=18870&journals%5B%5D=18869&journals%5B%5D=18868&journals%5B%5D=18867&journals%5B%5D=18865&journals%5B%5D=18864&journals%5B%5D=18861&journals%5B%5D=18860&journals%5B%5D=18862&journals%5B%5D=18849&journals%5B%5D=18863&journals%5B%5D=18851&journals%5B%5D=18850&journals%5B%5D=18848&journals%5B%5D=18847&journals%5B%5D=18846&journals%5B%5D=18845&journals%5B%5D=18844&journals%5B%5D=18843&journals%5B%5D=18842&journals%5B%5D=18840&journals%5B%5D=18841&journals%5B%5D=18839&journals%5B%5D=18838&journals%5B%5D=18837&journals%5B%5D=18836&journals%5B%5D=18835&journals%5B%5D=18830&journals%5B%5D=18827&journals%5B%5D=18829&journals%5B%5D=18828

**Comment by JC5** [comment]
Thanks for reporting! I'm aware this may happen. Use a smaller batch of transactions. I hope to fix this in the new layout :+1:

**Comment by fnouira** [comment]
Thanks for the workarround, it worked using a split by week.

**Comment by JC5** [comment]
:+1:
