### ISSUE TITLE
Minimum amount

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#733]
Hi, if I try to add a transaction of 0.009 BTC to Firefly it tells me that the minimum amount is 0.01.
I thought that that was fixed already in a previous version, but the problem seems to be back again. Can you fix this please (f.e. by checking for 'is not 0')?
Firefly version 4.6.3.1

**Comment by JC5** [comment]
Found it. Don't ask me why, but I did indeed put some removed code back.

It's a Chrome related issue though so use Firefox in the mean time. I believe it won't complain.

**Comment by xpfgsyb** [comment]
Firefox does the same. Tried it with GNU IceCat 52.1.0 (which is my main browser anyway) and Firefox 54.0.1, both on ArchLinux.

**Comment by JC5** [comment]
Ah, they caught up. Nice. But a browser without support for those fancy HTML5 should allow you to continue in the meantime.

**Comment by xpfgsyb** [comment]
Thank you for the tip about HTML5!
It seems that most browsers do support HTML5 well nowadays... After trying Firefox, IceCat, Chromium, QupZilla and Vivaldi I found that Gnome Web 3.24.3 is not fancy enough and does work :) Just as a tip for others who may find this ticket.
