### ISSUE TITLE
It would be useful to set a recurring transactions for each last day of the months

### ISSUE THREAD

**Issue by MDeLuise** [firefly-iii/firefly-iii#7336]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

As title says, it would be useful to set a recurring transactions for each last day of the months.

Currently the following options are available when the last day of month is selected:
<img width="630" alt="Screenshot 2023-04-06 at 17 48 42" src="https://user-images.githubusercontent.com/66636702/230431275-b6fdd444-8b75-447d-ac82-96b2efc7e330.png">

### Solution

There can be a new entry, available only if the last day of a month is selected, called "Every month on the last day".

### Additional context

It would be useful since sometimes the month end on the 28th, sometime on the 30th, and so on.

**Comment by JC5** [comment]
Plan it on the 31st and it will always correct itself to the last day of the month.
