### ISSUE TITLE
Photuris III app-style user selector

### ISSUE THREAD

**Issue by jonathanathe** [firefly-iii/firefly-iii#7337]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hello!

After using the web application I would like to see a feature found in the third party app "Photuris III" which allows you to select the account you want to view.

In my case I have an account for my personal expenses/income, but I also have a family account.

And it gets a bit annoying having to be offline and logging into the other account.

Thank you for your hard work on this project.

### Solution

The solution would be something similar to what the "Photuris III" app has. In the web version we have on the top right the email with which we have logged in. If we click on it, it does nothing. My solution would be that by clicking on this account you can switch to other accounts.

You would have to log in once and then you would only have to click on the account you want to view.

**Comment by JC5** [comment]
That's a great feature!

But instead of doing something similar, I'm already working on this: #7315 

You share the financial administration and not the entire account.
