### ISSUE TITLE
Expired invites

### ISSUE THREAD

**Issue by ErikCee** [firefly-iii/firefly-iii#7339]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

A while ago I invited someone; when the invitation url is hit, an error is shown with `Invalid code`. 
To resend an activation link you have to delete the old one first (otherwise the emailaddress is already used). Then a fatal error occurs: An email must have a "To", "Cc", or "Bcc" header.

### Debug information

Debug information generated at 2023-04-07 00:00:00 Europe/Amsterdam for Firefly III version **6.0.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 410, 04-03-2023 11:53:07 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | nl_NL |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-04-30 23:59:59 |
| Session first | 2022-12-27 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 |

### Expected behaviour

Be able to delete the invitation (or even better; resend/refresh it)

### Steps to reproduce

1. Create invitation
2. Delete invitation (expiry date has no impact)

**Comment by ErikCee** [comment]
Ah, see the second line:
```
192.168.1.xx - - [07/Apr/2023:20:05:11 +0200] "GET /v1/jscript/variables?ext=.js&v=6.0.0 HTTP/1.1" 200 4046 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
[2023-04-07 20:05:15] local.ERROR: Exception is: {"class":"BadMethodCallException","errorMessage":"Method FireflyIII\\Http\\Controllers\\Admin\\UserController::deleteInvite does not exist.","time":"Fri, 07 Apr 2023 20:05:15 +0200","file":"\/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php","line":68,"code":0,"version":"6.0.0","url":"http:\/\/firefly.my_hostname.com:8001\/admin\/users\/delete_invite\/1","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/111.0.0.0 Safari\/537.36","json":true,"method":"GET"}  
 .... 23 repititions ....
[2023-04-07 20:05:15] local.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"An email must have a \"To\", \"Cc\", or \"Bcc\" header.","time":"Fri, 07 Apr 2023 20:05:15 +0200","file":"\/var\/www\/html\/app\/Jobs\/MailError.php","line":94,"code":0,"version":"6.0.0","url":"http:\/\/firefly.my_hostname.com:8001\/admin\/users\/delete_invite\/1","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/111.0.0.0 Safari\/537.36","json":true,"method":"GET"}  
192.168.1.44 - - [07/Apr/2023:20:05:15 +0200] "GET /admin/users/delete_invite/1 HTTP/1.1" 500 4208 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
192.168.1.44 - - [07/Apr/2023:20:05:15 +0200] "GET /v1/lib/adminlte/css/skins/skin-blue-light.min.css?v=6.0.0 HTTP/1.1" 404 3796 "http://firefly.my_hostname.com:8001/admin/users/delete_invite/1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
```
I didn't change any mailsettings so I mail won't be working (maybe related to the errormessage obfuscating the root cause.

When looking through the code earlier today, I thought I found the `deleteInvite` method. Maybe I don't have the latest version or the reference isn't okay (php isn't my thing 😉 )

**Comment by JC5** [comment]
I just noticed yes, please upgrade to the latest version and you should be OK :+1:
