### ISSUE TITLE
Add savings rate information to overview and/or reports

### ISSUE THREAD

**Issue by sidyes** [firefly-iii/firefly-iii#7345]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to see my savings rate for all my accounts combined because this is one of the main features I am interested.

### Solution

Ideally, the savings rate is shown in the overview page next to the 4 top Widgets at the very top (or any other place that suits you):
![image](https://user-images.githubusercontent.com/11653185/230721703-ca10beb6-1e9e-486f-9746-692284630f0e.png)

In the financial report it would also be great to see that information as it fits to the `income vs expenses` widget:
![image](https://user-images.githubusercontent.com/11653185/230721811-45038428-c084-4d3b-965d-05fceb6ee054.png)

Also it would be nice to see the savings rate per month / year.

### What are alternatives?

Manual calculation looking at the numbers in firefly.

### Additional context

It is one of the key points of [FI/RE](https://www.fidelity.com/firestarter/savings-rate) which goes a bit in the direction of the budgets feature of firefly.

**Comment by JC5** [comment]
What do you mean with the savings rate? Like, the percentage?

**Comment by sidyes** [comment]
Yes, exactly. `rate = savings / income`, meaning if I earn 5k in March and spend 3k I would have saving rate of 40%.

**Comment by JC5** [comment]
Ah, that's something to remember for this epic: https://github.com/firefly-iii/firefly-iii/issues/6310 :+1:
