### ISSUE TITLE
Inconsistent rule behavior with description matching on rules created by the API

### ISSUE THREAD

**Issue by caseymullineaux** [firefly-iii/firefly-iii#7347]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Related to #7324

I can replicate the same problem outlined in #7324 after updating to 6.0.7 - but the key difference is that it only seems to happen on rules that are created via the API. 

I'm reading from a csv to create about 200-ish rules that simply match a transaction description and apply a category and tag.
All rules are created successfully, however when I preview a rule from the rule list, no results are returned.
 
Editing the rule and simply saving it without making changes seems to fix the rule. After saving, previews work correctly, as does actually executing the rule.

If I delete the rule and recreate it using the GUI, it seems to work fine.

Here's some sample code on how I'm creating the rules:
```python
import requests
import json
import csv

with open('categories.csv') as f:
    reader = csv.reader(f, delimiter=',')
    data = [row for row in reader]

for d in data[1:-1]:
    rule = {
        "title": d[0],
        "description": d[0],
        "rule_group_id": "2",
        "trigger": "store-journal",
        "strict": "false",
        "triggers": [
            {
                "type": "description_contains",
                "value": d[0]
            }
        ],
        "actions": [
            {
                "type": "set_category",
                "value": d[1]
            },
            {
                "type": "add_tag",
                "value": d[2]
            }
        ]
    }

    uri = 'http://firefly:8001/api/v1/rules'
    token = 'REDACTED'

    headers = {
        "content-type": "application/json",
        "authorization": f"Bearer {token}"
    }
    r = requests.post(uri, headers=headers, data=json.dumps(rule))
```

Here's a few example rows of the csv:
```
Text,Category,Tag
ATM WITHDRAWAL,Cash Withdrawl,Wants
BAKERY,Coffee & Café,Wants
```

### Debug information

Debug information generated at 2023-04-09 00:00:00 Australia/Sydney for Firefly III version **6.0.7**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.7 |
| Firefly III API | 2.0.1 |
| Build | 448, 08-04-2023 08:59:26 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Australia/Sydney |
| Browser TZ | Australia/Sydney |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | en_AU |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-06-30 00:00:00 |
| Session first | 2020-12-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.0.0 |

### Expected behaviour

Rules function the same whether they are created via the API or via the GUI

### Steps to reproduce

1. Create a rule via the API using the code provided
2. Observe that when previewing the rule in the list view, no results are returned
3. Observe that when previewing the rule in the edit view, results are returned correctly
4. Edit the rule, and save without making changes
5. Observe that the rule now works as expected

**Comment by JC5** [comment]
Thanks for reporting, I found the issue. The triggers and actions are stored with `active: false` which means they don't trigger. Wait for 6.0.8 or actively set `"active": true`.

**Comment by caseymullineaux** [comment]
Can confirm that setting `active: true` on rule definition when posting to the API resolves the issue.
