### ISSUE TITLE
Liability Account Creation Argument Error ($destination)

### ISSUE THREAD

**Issue by darylbart** [firefly-iii/firefly-iii#7355]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When trying to create a liability I receive the following error
```
FireflyIII\Factory\TransactionJournalFactory::getCurrencyByAccount(): Argument #4 ($destination) must be of type FireflyIII\Models\Account, null given, called in /var/www/html/app/Factory/TransactionJournalFactory.php on line 217
``` 
The page crashes with the attached screenshot. 
![Screenshot 2023-04-10 at 10 46 50 PM](https://user-images.githubusercontent.com/63500118/231042696-cbada50f-ede7-437e-b3cf-82fb57ca4b7f.png)
After refreshing the created items appears. 

Version 6.0.7

### Debug information

Debug information generated at 2023-04-11 00:00:00 Europe/Amsterdam for Firefly III version **6.0.7**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.7 |
| Firefly III API | 2.0.1 |
| Build | 448, 08-04-2023 08:59:26 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start |  |
| Session end |  |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4.1 Safari/605.1.15 |

### Expected behaviour

Page should not crash - should provide success message or redirect back to liabilities list page

### Steps to reproduce

1. Click liabilities tab 
2. Fill in required fields 
3. Submit

**Comment by JC5** [comment]
Nice find, I'll pick it up!
