### ISSUE TITLE
Add custom links to the navbar

### ISSUE THREAD

**Issue by Dan-Sun** [firefly-iii/firefly-iii#7357]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hey

Sometimes I need to switch between multiple accounts. At the moment it is only the way via the dashboard and scrolling the banks on the right side or via accounts -> asset account etc.

### Solution

Would be great to add some accounts just to the navbar.

![ff-account_navbar_links](https://user-images.githubusercontent.com/95150684/231310719-7c5580e4-1147-4ea1-815e-22863577a09d.png)

**Comment by JC5** [comment]
No, I think you could better use your browser's bookmarks for that.
