### ISSUE TITLE
Cant change account to active

### ISSUE THREAD

**Issue by wouterDeneyer** [firefly-iii/firefly-iii#737]
First of all, LOVE the application. 

I am using Firefly-III 4.6.3.1 with Apache2 & an external MySQL server. 
At the moment I have 5 asset accounts. 
When I want to add a new expense or revenue, only 4 are shown. 
When I check the 'Accounts' overview, I can see that one of them is inactive. 
But I am unable to mark is as active. 

Is this a known problem, or PEBCAK? 

Thanks!

EDIT: I manually changed the MySQL database with this query: 
UPDATE `Firefly`.`accounts` SET `active`='1' WHERE `id`=ACCOUNTID;

**Comment by JC5** [comment]
Thanks for the compliments! 

Yes, you can do this manually, you've discovered a known bug (see https://github.com/firefly-iii/firefly-iii/issues/726). I plan to release a new version this weekend, which will fix this. This will be version 4.6.4 which you can already test [on the demo site](https://firefly-iii.nder.be/). Please note that this version will require PHP 7.1.

**Comment by wouterDeneyer** [comment]
Awesome, thanks!
