### ISSUE TITLE
Regression: Budgets do not allow negative budgets

### ISSUE THREAD

**Issue by PsychoGame** [firefly-iii/firefly-iii#7372]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In the older pre 6.0.0 versions in the past I made use of negative budgets as well to highlight the budgets which were overspend and we needed to pay attention to.
In the latest 6.0+ versions I can't seem to enter a negative budget anymore, so I would say there is a regression somewhere.

### Debug information

Debug information generated at 2023-04-15 00:00:00 Europe/Amsterdam for Firefly III version **6.0.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.8 |
| Firefly III API | 2.0.1 |
| Build | 454, 15-04-2023 10:59:29 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-04-30 23:59:59 |
| Session first | 2023-02-10 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0 |

### Expected behaviour

Be able to use negative budgets as well to indicate budgets which are overspend in the corresponding month.

### Steps to reproduce

1. Create a budget category
2. Try to assign a negative budget to the corresponding category.
3. When reloading the budgets category it will have the negative value converted to the same amount, but positive.

**Comment by JC5** [comment]
That was never intended to be possible, so thanks for letting me know :).

**Comment by PsychoGame** [comment]
> That was never intended to be possible, so thanks for letting me know :).

Do you mean that negative budgetted values was kever intended to be possible?

**Comment by JC5** [comment]
Yes.
