### ISSUE TITLE
tag_is behaves like tag_contains

### ISSUE THREAD

**Issue by not1q84-1** [firefly-iii/firefly-iii#7377]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I m heavily using tags and related rules to structure my data. I recently found that one rule based on a tag was not working as expected and did find the reason today. I am using the _tag_is_ key to identify the transactions for the rule and expected it to be what the name states, i.e., it would differentiate between my two tags "**Auto**" and "Home **Auto**mation" - but it doesn't. Tested the same with _tag_is_ in the Search functionality with the same result. As usual: not really sure if this is a bug or a feature ;-).  But if it is a feature I would recommend to rename _tag_is_ into _tag_contains_

### Debug information

Debug information generated at 2023-04-16 00:00:00 Europe/Amsterdam for Firefly III version **6.0.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.5 |
| Firefly III API | 2.0.1 |
| Build | 424, 18-03-2023 14:53:12 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Asia/Singapore |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-04-30 23:59:59 |
| Session first | 2013-06-07 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.39 |

### Expected behaviour

When using the tag_is flag tags should be found / handled separately even if they are contained in each other. 

### Steps to reproduce

1. Create a tag Auto
2. Create a tag Automation
3. Tag two transactions respectively
4. Search for _tag_is:Auto_ - both transactions will be displayed
5. Same goes it you base rules on the respective tags

**Comment by JC5** [comment]
Nice find, that's a bug. Will be fixed in the next patch release :+1:

**Comment by not1q84-1** [comment]
Thanks a lot - helps to keep my complex model alive ;-) - and of course my Home automation  project's funding
