### ISSUE TITLE
Feature Request: Show sum (and time graph) on search results

### ISSUE THREAD

**Issue by tryffel** [firefly-iii/firefly-iii#7387]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi! I would like to get better insight on how money is spent between different tags and timeline. 
Also I think the search bar is really good, but it lacks certain statistics.
I think it would be helpful to provide basic statistics and timeline for search results.
For instance, I would like to see how much money I have spent in total and monthly for e.g. (category:food AND tag:travelling) or (category:leisure AND tag:travelling AND tag:clothes). 
Thank you!

### Solution

The absolute minimum:
- Provide sum of money that are in search results (now I can type whatever queries and get the sum)

Better:
- Provide daily/weekly/monthly graph for the search results, which shows money spent on each window (now I don't need to manually do many queries over time frames)

Finally, the ultimate solution would be to:
- Create reports based on the transactions found from the search bar (but the 2 first will do obviously)

### What are alternatives?

- Using the search bar, but it will only give the transactions and I need to get the sums some other way
- Using reports, but they don't allow the use case

**Comment by JC5** [comment]
I'm going to put this on the list together with https://github.com/firefly-iii/firefly-iii/issues/6311

Plenty of great ideas are collected already :+1:
