### ISSUE TITLE
Currency help popup

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#739]
Firefly 4.6.3.1
When opening currencies options https://firefly/currencies for the first time the help popup is missing meaningful data:
![firefly-currency_help1](https://user-images.githubusercontent.com/4746858/29067869-1d5cb402-7c3d-11e7-8d5a-7d692cadb40c.PNG)

**Comment by JC5** [comment]
I thought I had added them all, nice find!

**Comment by tannie** [comment]
Similar issue when I opened a piggybank account for the first time:
![screenshot_20170811-222440](https://user-images.githubusercontent.com/245128/29231515-c9de4982-7ee7-11e7-836f-80672fe6ab36.png)

**Comment by JC5** [comment]
Also fixed.
