### ISSUE TITLE
update request failed

### ISSUE THREAD

**Issue by rsedlmeier** [firefly-iii/firefly-iii#7395]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

http://192.168.2.222/firefly/admin/update-check has a minor error in its update script
the message is self-explanatory, see below:

Nachricht: Sie verwenden 5.7.18. Ihre Version ist neuer als die neueste Version (v6.0.8).
Message: You are using 5.7.18. Your version is newer than the latest version (v6.0.8).

### Debug information

self-explanatory bug

### Expected behaviour

update to version 6.0.8

### Steps to reproduce

just click on Update Check

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue+%22newer+than%22+is%3Aclosed
