### ISSUE TITLE
Node production/prod run scripts exit with errors

### ISSUE THREAD

**Issue by SierraKomodo** [firefly-iii/firefly-iii#7399]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Running `npm run prod`/`npm run production` produces an error message:

```
ERROR in ./resources/assets/js/webhooks/index.js 21:0-43
Module not found: Error: Can't resolve '../components/webhooks' in '/var/www/firefly/resources/assets/js/webhooks'
Did you miss the leading dot in 'resolve.extensions'? Did you mean '[".*",".wasm",".mjs",".js",".jsx",".json",".vue"]' instead of '["*",".wasm",".mjs",".js",".jsx",".json",".vue"]'?

webpack compiled with 1 error
```

### Debug information

N/A

### Expected behaviour

Node run scripts should not be giving errors.

### Steps to reproduce

1. Run the usual install steps
	1. `composer install`
	2. `npm install`
	3. `php artisan migrate`
2. Run `npm run production` or `npm run prod`
3. The error will appear during/just after the mix plugins stage.

### Additional info

This does not appear to affect the package's functionality - The website runs as expected with no errors.

This was encountered in releases v6.0.8 and v6.0.7 (Earlier versions of firefly-iii not tested) on a server running Ubuntu 22.04.2 LTS and the following software versions:

- PHP Version: 8.2.4
- Node Version: 12.22.9
- Composer Version: 2.2.6

**Comment by JC5** [comment]
I use yarn myself to build the JS dependencies. They come pre-build so you don't have to: `yarn upgrade && yarn prod`.

**Comment by seamus-giess** [comment]
Hello!

Just following up on this as I've recently run into the same issue as @SierraKomodo, just did a fresh clone, running through the regular steps for spinning up a laravel project and hit the same issue with the mix build steps.

Looks like its an issue with the use of Vue in this specific case. With `resources/assets/js/webhooks/index.js:21` needing to be changed from:
`import Index from "../components/webhooks";`
to
`import Index from "../components/webhooks/Index";`

Its a small fix, and probably just warrants a commit, but I find the disconnect between the installed Vue version and the import not failling for others probably warrants a more informed investigation than I'm capable of providing (Very lacking in Vue experience).

From my extremely precursory investigation it seems to be that the Vue interpreter doesn't seem to be picking up that `Index.vue` is the index file, seeming to be related to the capitalization of the file intended for import (if the file is renamed to `index.vue`  with the original line on `21` staying as is, it seems to work fine).
