### ISSUE TITLE
Deprecation errors during composer install

### ISSUE THREAD

**Issue by SierraKomodo** [firefly-iii/firefly-iii#7400]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Running `composer install` produces the following deprecation notices:

```
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Symfony/Component/Console/Command/DumpCompletionCommand.php:48
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Symfony/Component/Console/Command/DumpCompletionCommand.php:56
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Composer/Autoload/AutoloadGenerator.php:879
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Composer/Autoload/AutoloadGenerator.php:884
```

### Debug information

N/A

### Expected behaviour

Deprecation errors should be resolved at some point.

### Steps to reproduce

1. Run `composer install`

### Additional info

Occurs with v6.0.7 and v6.0.8 (Not tested on earlier versions) with the following software versions:

OS: Ubuntu 22.04.2 LTS
PHP: 8.2.4
Composer: 2.2.6

**Comment by JC5** [comment]
This happens when you run an old version of composer, or any of the installed dependencies. Note also where the error occurs: not in Firefly III code. As such, it's not a bug of mine :)
