### ISSUE TITLE
Adjust available budget

### ISSUE THREAD

**Issue by FeltenVanballenberghe** [firefly-iii/firefly-iii#7408]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Is it me, or is it not "clickable" anymore to adjust the amount. It now takes the amout of the total budget created.
![image](https://user-images.githubusercontent.com/83814030/233461328-0567cb24-2671-49a4-898b-c544244a2070.png)

### Debug information

Version 6.0.7
Php 8.2
Linux debian bullseye
Browser Opera - does not work on firefox neither

### Expected behaviour

Adjust the available budget per period

### Steps to reproduce

Adjust available budget by clicking in a selected period.
You can test it on the demo site too, same issue.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/7318

**Comment by FeltenVanballenberghe** [comment]
Oh...thx for the reply. Do you mind asking: but why? :) Calculated on what? Total budgetted amount? Total income for the selected period? Was I approching the tool wrong?

**Comment by tgkenney** [comment]
Stumbling on this issue as well.  It seems really odd that the Budgeted and Available amounts are just the same thing now.  There isn't an easy way to tell if your budgeted expenses are over the income you're expecting for the month now, unless I'm also approaching this concept wrong.

I know you removed it for being confusing, but I would definitely like an option back to be able to set the available amount for the month, even if it were just in the API or something
