### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by andy-nl** [firefly-iii/firefly-iii#741]
Hi,
maybe I am too stupid,
but how can I add a new user to the system?
I have already one which I created during installation via the web interface.
Is it possible to create another additional user?
Thanks for your advice in advance!

Cheers,
andy

**Comment by JC5** [comment]
Go to Options, Administration, Configuration options for Firefly III, and uncheck "single user mode".

**Comment by wprauchholz** [comment]
Hi, there is no link for 'administration' option.
Is there a change in feature to add an additional user?

**Comment by JC5** [comment]
Use a tool like phpmyadmin to access your database. 

Could you open the table roles? It should have two entries, one for "Site Owner" and the other for "Demo User". If so, remember the ID of the "Site Owner".

Open table role_user. It is probably empty. A new entry must be created. user_id must be 1, and role_id must be what you remembered previously (probably 1).

**Comment by wprauchholz** [comment]
Once I have done this, what are the next steps?

**Comment by JC5** [comment]
Then, you should be able to do this:

Go to Options, Administration, Configuration options for Firefly III, and uncheck "single user mode".

Once this button is unchecked, the /login page should show you the option to register a new account. That second account will not be made administrator, btw.
