### ISSUE TITLE
Dark mode system with light mode Firefly has some form/elements not rendered correctly

### ISSUE THREAD

**Issue by kenston** [firefly-iii/firefly-iii#7410]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In the demo site, if you set the theme as light mode in preferences even though your system is on dark mode, you now get the light mode, but with some issues on certain parts of the screen:

![image](https://user-images.githubusercontent.com/1872412/233577670-4b21a7ed-cbb8-45cf-b847-353dc91b3ff3.png)

The date period chooser and the tags appeared with dark elements.

### Debug information

-

### Expected behaviour

It should render nicely for light mode.

### Steps to reproduce

1. Have your system set to dark mode.
2. In Firefly preferences, set to light mode.
3. Create a transaction.

### Additional info

Version 6.0.8

**Comment by JC5** [comment]
Ah nice find, thanks!
