### ISSUE TITLE
Select all button in label screen

### ISSUE THREAD

**Issue by AdalLS** [firefly-iii/firefly-iii#7412]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

![image](https://user-images.githubusercontent.com/44591506/233706175-d365ad81-a099-4c4b-b08b-77250aed701a.png)

See above. A "select all" button would help those who like me like to remove all such data import labels and keep only those labels I explicitly created manually. Otherwise after a while it gets out of hand. 

### Solution

Add a "select all" button, ideally for each group of labels, as they seem to be grouped by year.

### What are alternatives?

If you want to delete them right now you have to click each one by hand.

**Comment by JC5** [comment]
Good suggestion! For now, you have to select them manually or set the importer not to create these tags on the configuration page or in your configuration file.

For a fix, this will be part of the new layout: https://github.com/firefly-iii/firefly-iii/issues/6317
