### ISSUE TITLE
API Transactions pagination works wrong way

### ISSUE THREAD

**Issue by Tarik02** [firefly-iii/firefly-iii#7427]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have database with 1739 transactions. I'm trying to use `/api/v1/transactions` method and I'm can't get information from pages after 18. In my case, I'm trying to make request `/api/v1/transactions?page=35&type=all`, as response I'm getting:
```json
    "meta": {
        "pagination": {
            "total": 1739,
            "count": 50,
            "per_page": 50,
            "current_page": 18,
            "total_pages": 35
        }
    },
```

### Debug information

Debug information generated at 2023-04-24 00:00:00 UTC for Firefly III version **6.0.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.8 |
| Firefly III API | 2.0.1 |
| Build | 454, 15-04-2023 10:59:29 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Kyiv |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `*` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-04-30 23:59:59 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0 |

### Expected behaviour

I would like to be able to get transactions from any page I want.

### Steps to reproduce

1. Fill database with large number of transactions.
2. Try to use `/api/v1/transactions` method with large page parameter.

**Comment by JC5** [comment]
Not one day ago somebody told me about this on [Gitter](https://app.gitter.im/#/room/#firefly-iii_firefly-iii:gitter.im). This should be fixed in the next patch release :+1:
