### ISSUE TITLE
Invalid chart for expense accounts

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#743]
As can be seen here, when viewing all transactions the chart doesn't show anything
https://firefly-iii.nder.be/accounts/show/15/all

**Comment by JC5** [comment]
Nice find, I'll get right on it.

**Comment by JC5** [comment]
Fixed!

**Comment by JC5** [comment]
Will be live in the next release, which should happen over the weekend and requires PHP7.1
