### ISSUE TITLE
Documentation Fix: Installation Links update

### ISSUE THREAD

**Issue by mindlessroman** [firefly-iii/firefly-iii#7436]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

A quick update as I was going through the documentation - some older links for installation!

### Debug information

n/a

### Expected behaviour

Clicking on docker link or the self-hosted link will take you to page in the site's documentation.

![image](https://user-images.githubusercontent.com/7254163/234905775-b26ab078-cfc4-42a3-801a-f6afd32bdd38.png)

### Steps to reproduce

1. Look in the [Getting Started section](https://github.com/firefly-iii/firefly-iii#getting-started).
2. Click the docker link.
3. Get to a 404 page.

**Comment by JC5** [comment]
Nice work, merged! :+1:
