### ISSUE TITLE
Is there a way to not run the intro popus on each update?

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#744]
I seem to get the popups after each new upgrade. Is there a way to disable that?

**Comment by JC5** [comment]
Although the library behind the popups recently changed you should not get them each upgrade.

**Comment by simonsmiley** [comment]
hmm.. I'll check to see if the next upgrade makes them appear again

**Comment by JC5** [comment]
Let me know, new version is live.

**Comment by simonsmiley** [comment]
looks like I'm not getting them. I guess my last update I transitioned to using git. Probably messed something up during that...
