### ISSUE TITLE
White border around Tags field while creating transaction in dark theme

### ISSUE THREAD

**Issue by elliot-gh** [firefly-iii/firefly-iii#7444]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When creating a transaction on v6.0.9, the Tags input field has a white border around it. This is also seen on the demo website. I am on Chrome 112.

Screenshot of demo:
![image](https://user-images.githubusercontent.com/5415760/235289921-83d31c62-c1ad-49ea-b230-e13c7099e914.png)

Screenshot of my own instance:
![image](https://user-images.githubusercontent.com/5415760/235289876-e470da26-2c74-4e0d-b748-c64dfb4eebf8.png)

### Debug information

Debug information generated at 2023-04-29 00:00:00 America/Los_Angeles for Firefly III version **6.0.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.9 |
| Firefly III API | 2.0.1 |
| Build | 466, 29-04-2023 06:55:07 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Los_Angeles |
| Browser TZ | America/Los_Angeles |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `172.28.0.1` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-04-30 23:59:59 |
| Session first | 2020-08-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Create a new withdrawal while in dark theme
2. Observe Tags input field has a white border while no other input fields do

**Comment by elliot-gh** [comment]
I think it's also worth noting that actually using tags seems to have a strange appearance.

Tag autosuggest:
![image](https://user-images.githubusercontent.com/5415760/235290005-4701a1e3-624e-456c-8890-07b31b346507.png)

Tag used:
![image](https://user-images.githubusercontent.com/5415760/235290015-cbdb703b-e828-4bfe-8354-4126593546d3.png)

**Comment by JC5** [comment]
Nice find, thx for reporting!
