### ISSUE TITLE
Ability to set month end to the last working day

### ISSUE THREAD

**Issue by Leah96xxx** [firefly-iii/firefly-iii#7445]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

It would be nice if we could set the month end to the last working day, rather than being stuck with the 1st to the 31st default. This would make doing things like budgeting between paydays and running monthly reports simpler, without having to manually enter out budgets each month and change the date range for literally everything.

The documentation says that a month is from the first day to the last day of the month. This is true when talking about calendar months, but not when dealing with personal finances. When you're talking about personal finances, a month is typically from payday to payday. Considering this has been brought up a few times, maybe it's time to reconsider the decision to force us to use calendar months.

### Solution

This would make doing things like budgeting between paydays and running monthly reports simpler, without having to manually enter out budgets each month and change the date range for literally everything.

### What are alternatives?

Without this, we have to manually change the date range every month for everything and be forced to manually input your budgets instead of using the auto-budget tool.

**Comment by Leah96xxx** [comment]
Also, on a side note, when viewing the budget screen in a custom date range, the available amount shows as £0.00. This causes the bars for budgeted and spent to not show. Let me know if I should open a separate bug for that.

Setting the date range back to the calendar month doesn't help there since that then shows 2 months worth of budgets instead of 1.

**Comment by JC5** [comment]
> Considering this has been brought up a few times, maybe it's time to reconsider the decision to force us to use calendar months.

Sorry, the answer is still [the same](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/#changing-the-monthly-cycle-to-another-day-of-the-month).

> Let me know if I should open a separate bug for that.

The fact that the amount shows zero makes sense, because the available amount is only calculated for whole months. But I'm curious to see what you run into that makes it show "2 months worth of budgets instead of 1". Is it twice the amount? Or something else?

**Comment by Leah96xxx** [comment]
> Sorry, the answer is still [the same](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/#changing-the-monthly-cycle-to-another-day-of-the-month).

> The fact that the amount shows zero makes sense, because the available amount is only calculated for whole months.

I'll be honest, over the other requests for this functionality, it just sounds like you're being stubborn about implementing something that many users would probably find incredibly useful.

> The fact that the amount shows zero makes sense, because the available amount is only calculated for whole months.

What I see is this:
![image](https://user-images.githubusercontent.com/88419550/235335298-e06f1b2f-344e-434a-9e1b-3e28cc1ee42b.png)

Only showing 2 of the budgets to keep it small but you get the idea. They all show 2 budgets, one for each date range, meaning the Budgeted amount bar is doubled.

**Comment by JC5** [comment]
> I'll be honest, over the other requests for this functionality, it just sounds like you're being stubborn about implementing something that many users would probably find incredibly useful.

You don't understand. Firefly III isn't a democracy and I'm not building it for my users. Firefly III is a tool I build for **my** pleasure and **my** own utility. Y'all free to use it and enjoy it, and if you have a good idea let me know. But I have the final say and when I'm not going to use a feature or I don't see the utility, it's a no. That's it. I started Firefly III with one user in mind (me) and I still do. Feel free to call me "stubborn" or whatever. I have no obligation to anybody. I gave you my answer and I'm going to change that.

> What I see is this when it's set to the calendar month

Yes, if you set two amounts for the budget, this will happen. A budget can have multiple (overlapping) amounts, ie. you can set both a monthly and a yearly budget amount for groceries. Available amounts are calculated per month. The overlapping amounts should be corrected using the amount per day. I'll see if I can replicate it to check the math.

**Comment by JC5** [comment]
> Only showing 2 of the budgets to keep it small but you get the idea. They all show 2 budgets, one for each date range, meaning the Budgeted amount bar is doubled.

This is a bug, and should be fixed in the next release. I hope you have a nice Sunday.
