### ISSUE TITLE
Bills "Next expected match" Incorrect

### ISSUE THREAD

**Issue by Solverz-0** [firefly-iii/firefly-iii#7446]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Best explained with example I saw today:

Todays Date: 30/04/2023
Bill Date: 01/05/2023

When I am on the Bills page in the Aprils date range the bill shows next expacted match to be May 1st, 2023, but if I change to May's date range the next expacted match shows as June 1st 2023 (which is incorrect).

### Debug information

Debug information generated at 2023-04-30 00:00:00 Europe/London for Firefly III version **6.0.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.9 |
| Firefly III API | 2.0.1 |
| Build | 466, 29-04-2023 06:55:07 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_GB |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-04-30 10:29:21 |
| Session first | 2022-09-09 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0 |

**Comment by JC5** [comment]
This is correct behavior, it will always calculate based on the current month.

**Comment by Solverz-0** [comment]
> This is correct behavior, it will always calculate based on the current month.

Sure, but in a recent previous version (I can find the version if needed) it would still show "expected in x days" if I changed the range to the following month, in this case May.

But now it acts as if may has been skipped, it is only happening to with a date of 1st May, and dates like 5th May show the expected in x days still.

**Comment by Solverz-0** [comment]
Additionally, other dates like 5th May, 15th May etc still show as next expected date, but dates with 1st May are showing 1st June.

**Comment by JC5** [comment]
> Additionally, other dates like 5th May, 15th May etc still show as next expected date, but dates with 1st May are showing 1st June.

Wait until May 5th and those will jump to June as well.

**Comment by Solverz-0** [comment]
> > Additionally, other dates like 5th May, 15th May etc still show as next expected date, but dates with 1st May are showing 1st June.
> 
> Wait until May 5th and those will jump to June as well.

Okay, but shouldn't there still be a message saying, expected in 1 day? Like for 5th may bills it says expected in x days?

**Comment by JC5** [comment]
It took me a moment, but you're right! Let me check out what's happening here.

**Comment by JC5** [comment]
Fixed, thanks for your patience!

**Comment by Solverz-0** [comment]
> Fixed, thanks for your patience!

Thank you!
