### ISSUE TITLE
Column names overlap with sort order in Reports page

### ISSUE THREAD

**Issue by venkivijay** [firefly-iii/firefly-iii#7453]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In the reports page, `Spent (average)` & `Total` columns are right aligned which is making the column names overlap with sort order `0..1` or `1..0`

![image](https://user-images.githubusercontent.com/30868354/235438554-d785cb9d-fc08-40ca-bd38-25182d29e462.png)

### Debug information

Debug information generated at 2023-05-01 00:00:00 Asia/Kolkata for Firefly III version **6.0.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.9 |
| Firefly III API | 2.0.1 |
| Build | 466, 29-04-2023 06:55:07 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Asia/Kolkata |
| Browser TZ | Asia/Kolkata |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 15:25:39 |
| Session end | 2023-04-30 15:25:39 |
| Session first | 2023-02-21 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0 |

**Comment by JC5** [comment]
Yep I know, thanks for reporting. I'm not going to fix it. I'm already working on a new layout and these small things aren't much of a priority :)
