### ISSUE TITLE
Editing a reconciled transaction removes the reconciliation flag when it need not

### ISSUE THREAD

**Issue by schtibal** [firefly-iii/firefly-iii#7455]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When editing a reconciled transaction, any edit removes the reconciled check - even if the edit has nothing to do with the account or amounts. Eg, editing tags, category or budget, or uploading an attachment.

This is sort of covered in #5070 but a subtly different way of thinking about it. 

### Debug information

N/A

### Expected behaviour

When a reconciled transaction is edited, but no changes are made to the account or amount, the reconciliation flag should not be unset.

### Steps to reproduce

1. Reconcile an account
2. Edit any non-financial information for a transaction (category, budget, tags, etc)
3. The transaction is now no longer reconciled

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5070
