### ISSUE TITLE
On import, add option to skip transactions that have already been deleted

### ISSUE THREAD

**Issue by schtibal** [firefly-iii/firefly-iii#7459]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to have an option on the data importer that allows the choice to either re-import transactions that have already been imported and subsequently deleted, or to ignore them.

In the scenario where a daily import is performed for, eg the past 10 days, the majority of transactions are duplicate and will be skipped. But there may be transactions which are not required - eg, a transfer between accounts may be manually created, and one half of the original transaction deleted. The subsequent imports should be able to skip this deleted transaction.

If there is a situation where a re-import is required, the option can be toggled to force the re-import of deleted transactions.

### Solution

Add a check-box to the data importer - "Re-import deleted transactions", defaulted to unchecked

**Comment by JC5** [comment]
I'm not sure what you're asking for.

> But there may be transactions which are not required - eg, a transfer between accounts may be manually created, and one half of the original transaction deleted. The subsequent imports should be able to skip this deleted transaction.

This already happens. Deleted transactions will not be re-imported. 

> If there is a situation where a re-import is required, the option can be toggled to force the re-import of deleted transactions.

This is something you can already do. Either tell the data importer to ignore duplicates. Also, in Firefly III, you can purge deleted transactions. This will have the effect that these transactions will be reimported.

**Comment by schtibal** [comment]
Captured link to gitter thread:

https://matrix.to/#/!epdtwMcKTscMlFxeBi:gitter.im/$Fz92_67PSp_hfeVciNCAPNrRWu7EWDEhuhb_Ur8iGVs?via=gitter.im&via=matrix.org&via=matrix.altisnetwork.com
