### ISSUE TITLE
Importing PayPal USD-transactions creates EUR amounts

### ISSUE THREAD

**Issue by tannie** [firefly-iii/firefly-iii#746]
When I import my PayPal csv with USD transactions into my FF PayPal account (set to EUR) it creates transactions with the USD amount but with a EUR symbol.

I mapped the USD in FF correctly (I think):
<img width="1001" alt="screenshot 2017-08-11 13 08 16" src="https://user-images.githubusercontent.com/245128/29211061-1172139c-7e97-11e7-9a19-cf2744e6623a.png">

But then it shows up as EUR anyway...
<img width="998" alt="screenshot 2017-08-11 13 07 16" src="https://user-images.githubusercontent.com/245128/29211065-16b4c4c6-7e97-11e7-899b-74a87d523163.png">

Am I doing it wrong?

Including the file used for import, with some info removed.
[PayPal.txt](https://github.com/firefly-iii/firefly-iii/files/1217675/PayPal.txt)

**Comment by JC5** [comment]
I'm fairly sure the import routine ignores your currency setting, for whatever reason. I'll get right on it!

**Comment by JC5** [comment]
The currency setting of the account overrules the imported transaction.

In the future, this will no longer be the case so you can add USD transactions to a EUR account. But realise that the currency conversion will be "off", being 1 on 1. Editing each transaction is necessary to fix this. This will only happen of course when your import file forces the currency to be different.

![screen shot 2017-08-12 at 07 36 59](https://user-images.githubusercontent.com/5889984/29238235-113f1952-7f31-11e7-8d04-9ef825fb292f.png)

**Comment by tannie** [comment]
No problem! The number of transactions in USD on my PayPal account various, most of them are in EUR, which is why I set the account to EUR. Having a visual reminder ( the amount has a double entry) helps me to quickly edit the actual EUR amount, which can vary based on when PayPal decides to transfer the money anyway.

Thanks!

**Comment by JC5** [comment]
Release is live.
