### ISSUE TITLE
Monthly bill payed in more that one transaction is assuming average

### ISSUE THREAD

**Issue by soloam** [firefly-iii/firefly-iii#7464]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When we have a bill to the month, and that bill is payed in 2 transaction, the system is making like it was 2 payments of 2 bills and calculating the average. This messes up the average value for the bill.

### Debug information

Not Relevant

### Steps to reproduce

From my point of view, it should assume that payment as one (sum of all payments for that bill) and add that value to the total to calculate the bill average

### Additional info

One example:

One Bill of 100€ that is payed with 2 transaction of 50€! The average should be 100, and the system is using both transaction and declaring that the average to that bill is 50.

Please note that this bill was not intended to be payed in 2, I was done this way only this month.

**Comment by JC5** [comment]
Yes, that's the way it works. You can choose to delete one transaction and add the amount to the original one.

**Comment by soloam** [comment]
Thank you @JC5. If that's the case I can live with it!

Thank you
Best regards
