### ISSUE TITLE
Rounding issue on piggy banks

### ISSUE THREAD

**Issue by simon-watiau** [firefly-iii/firefly-iii#7467]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Thanks for your work ! 

Sometimes piggy banks fail to add the mentioned available amount, but one cent lower works.

![output-onlinegiftools](https://user-images.githubusercontent.com/707532/236664872-bf6e6996-ffea-4a93-83c7-a3215b30ff73.gif)

### Debug information

Debug information generated at 2023-05-07 00:00:00 UTC for Firefly III version **6.0.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.9 |
| Firefly III API | 2.0.1 |
| Build | 466, 29-04-2023 06:55:07 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-05-01 00:00:00 |
| Session end | 2023-05-31 23:59:59 |
| Session first | 2019-11-29 01:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0 |

### Expected behaviour

I should be able to add the mentioned amount exactly

### Steps to reproduce

it seems to be a rounding error but I didn't find a scenario that works every time

**Comment by JC5** [comment]
Thanks! I'm aware of the issue. Not yet sure what the root cause is, unfortunately. If you can, you can force the database to use a normal amount of decimals, that should stop most issues (hopefully including this one).

1. Backup your database.
2. Run `php docker exec -it [firefly-iii-container] php artisan firefly-iii:force-decimal-size --token=[token]`

The Firefly III container name is usually `firefly-iii_app_1`, and the token can be found on your `/profile` page.
