### ISSUE TITLE
Deleting multiple selected transactions doesn't work

### ISSUE THREAD

**Issue by tannie** [firefly-iii/firefly-iii#747]
When I used the 'Select transactions' option, and then select several transaction for deletion I get:
<img width="665" alt="screenshot 2017-08-11 13 30 20" src="https://user-images.githubusercontent.com/245128/29211438-6a341578-7e99-11e7-833c-ababe946234c.png">

I happily press 'Delete selected permanently' and then get:
<img width="191" alt="screenshot 2017-08-11 13 30 38" src="https://user-images.githubusercontent.com/245128/29211445-79225fae-7e99-11e7-90b4-7cde22f0b063.png">

I have to manually delete the transactions, one by one (which works).

Bug?

**Comment by JC5** [comment]
You're right! The demo site suffers from this problem as well. I'll look into it :+1:
