### ISSUE TITLE
Budgets progress bar data and "Left to spend" in index page data not update after budget deletion

### ISSUE THREAD

**Issue by alim0x** [firefly-iii/firefly-iii#7478]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Budgets progress bar data and "Left to spend" in index page data not update after budget deletion.

### Debug information

try this problem in demo site.

v6.0.9, demo@firefly

### Expected behaviour

Budgets update after budget deletion.

### Steps to reproduce

1. check budgets now (use Euro for example), now it's 1400, used 349.92, 1400-349.92=1050.08 left.
![图片](https://user-images.githubusercontent.com/4954007/236974232-39584ee4-b7f8-4b7b-b554-de78ebfb278b.png)
![图片](https://user-images.githubusercontent.com/4954007/236974414-f2c29d5d-c341-40ea-a7ea-9faf73deccd6.png)

2. add new budget "NewBudget", 1000 Euro, now total budget in euro should be 2400, used 349.92, 2400-349.92=2050.08 left.
![图片](https://user-images.githubusercontent.com/4954007/236974680-468d6689-f702-4c95-a328-b7d914afe6f5.png)
![图片](https://user-images.githubusercontent.com/4954007/236974730-a3276f7a-188f-4604-bff3-917d20f38c36.png)
![图片](https://user-images.githubusercontent.com/4954007/236974756-ace4a9db-86d4-49a3-bf75-3b166522106f.png)

3. now delete budget "NewBudget", now total budget should be 1400, used 349.92, 1400-349.92=1050.08 left, BUT...
![图片](https://user-images.githubusercontent.com/4954007/236974925-734492b1-2daf-4987-bdf6-8589b9f6461b.png)
![图片](https://user-images.githubusercontent.com/4954007/236975003-54079fef-2895-4d1c-b08a-0af8423c6517.png)
![图片](https://user-images.githubusercontent.com/4954007/236975037-656a395f-a868-4fbc-afd2-19e7e8525a7b.png)
![图片](https://user-images.githubusercontent.com/4954007/236975104-9dbef8ef-289a-4c5b-b001-5c0d1c26dd66.png)

### Additional info

do flush in my local test env can solve this.

**Comment by alim0x** [comment]
and another test:

1. now Budget in Euro is 1300, used 282.45, 1300-282.45=1017.55 left. (for May 2023)
![图片](https://user-images.githubusercontent.com/4954007/236976591-aaa12e82-33a6-42c1-8fde-0a88d3d18bda.png)

and there is no budget for June 2023.
![图片](https://user-images.githubusercontent.com/4954007/236976757-10d9de43-31d7-41d8-b1bd-3373f0cab80f.png)


2. add "NewNewBudget" 10000, and apply for 2023-01-01~2023-12-31
![图片](https://user-images.githubusercontent.com/4954007/236977039-e06df374-732b-4c09-9bef-abcfc9a1648b.png)

3. the "10000 Euro" seems divide into 12 pieces for every month in 2023:
**_(1017.55+10000/12≈1850.88, but get 2149.32, no idea why 2149.32, and left to spend in index page get 1866.87?!)_**
![图片](https://user-images.githubusercontent.com/4954007/236977298-19c1c92f-1ef9-41c3-8c78-42974209422c.png)

and for june:
![图片](https://user-images.githubusercontent.com/4954007/236977563-4c87c6cf-e718-4935-94ab-f29ef853cf52.png)

5. delete "NewNewBudget", should be 1300, used 282.45, 1300-282.45=1017.55 left.
![图片](https://user-images.githubusercontent.com/4954007/236977820-14517b2c-9f1c-49a0-a8a4-8021b5ce9bba.png)
![图片](https://user-images.githubusercontent.com/4954007/236977900-656bb984-16f4-4c15-80c5-94fc5f746b1e.png)

6. and for june... and july
![图片](https://user-images.githubusercontent.com/4954007/236978062-af6f6de9-a325-4429-a614-828cd90de9b6.png)
![图片](https://user-images.githubusercontent.com/4954007/236978111-0ba448fc-1ec6-4a7a-a43a-8f6a586cf96c.png)

**Comment by JC5** [comment]
Thanks, I'll pick it up!

**Comment by venkivijay** [comment]
@JC5 The "Budgets and spending" chart on the home page doesn't update when I allocate more money to a budget. I think these issues are related.

**Comment by JC5** [comment]
That could simply be a cache issue too, browse to /flush to clear your cache.
