### ISSUE TITLE
The error cannot be recovered :(Firefly III has crashed

### ISSUE THREAD

**Issue by markolzc** [firefly-iii/firefly-iii#7479]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The mistake I made when I added revenue

file_put_contents(/var/www/html/storage/framework/cache/data/82/84/8284cdad9236abeb1a9f1ee6f1842389f7120efd): Failed to open stream: Permission denied

### Debug information

The error is located in the file
 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php Line 205, code 0

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/faq/self-hosted/#unable-to-write-to-cache-directory
