### ISSUE TITLE
Record the amount added to a budget at the start of a period

### ISSUE THREAD

**Issue by schtibal** [firefly-iii/firefly-iii#7484]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When incrementing a budget at the start of a new budget period, as well as recording the new budget amount, add a new column to the `budgets` database table that records the amount that was added. 

This will essentially create a snapshot of the amounts in `auto_budgets` at the time of incrementing, which is useful for historical reporting.

By querying the `auto_budgets` table, it is possible to quickly see if the anticipated income in a period will cover the budget allocated. But having this value, it will be also be possible to have an historical view of budget allocation.

### Solution

1. Add a new field `added_amount` to the `budgets` table
2. When budgets are automatically updated at the start of a period, populate the `added_amount` field with the amount that was added to arrive at this period's budget amount.
3.

**Comment by JC5** [comment]
I'm not entirely sure what you mean, but this recording already happens.

**Comment by schtibal** [comment]
That's great if it does - can you tell me where?

The `auto_budgets` table is a single row per budget, which records how much is allocated to each budget each period, and whether is incremented or set to the amount. It doesn't keep a history of what the auto amount was.

The `budget_limits` table has a new record created for each budget period, and it stores the available budget at the start of the period.

Eg, at the start of Jan, I create a budget that has $100 available, and auto-increment by $100 each month.
Through the month, I spend $80.
On the first of Feb, a new `budget_limits` record is created, with an amount of $120 (the remaining $20, plus auto-increment of $100).

How do I know that I added $100 to the available budget? I simply look at `auto_budgets`.

Its now later in the year, and I want to look back and see how much was added into each budget for each month. But that budget increment that I set to $100 back in Jan, I've now adjusted to $150. It's not that easy to look at the `budget_limits` table for February to see that the auto-increment process added $100. I have to calculate it from January's budget amount, then sum of all the January transactions for the budget, and February's budget amount.

Hope that makes a bit more sense?

**Comment by JC5** [comment]
Yes, but I'm not going to record that info. Sorry.

> Its now later in the year, and I want to look back and see how much was added into each budget for each month. 

What would this give you in terms of financial insight?
