### ISSUE TITLE
Allow arbitrary date ranges for "All transactions for budget" view

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#7486]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

1. Open any budget
2. Click on the budget name, to get the list of transactions
3. Change the date range in the top right to any arbitrary date range (not a whole month)
4. Actual list of transactions does not update, it still spans the entire month.

For example, I have a "Vacation" budget and I've just been on a trip from end of April to beginning of May. I would like to see a list of all transactions I've made during that time in Vacation budget. However, Firefly does not appear to allow that.

### Solution

Make date selection on the "All transactions for budget" work like other transaction list screens (such as " All expenses" or " All transactions for account" screens)

**Comment by matejdro** [comment]
Yes, but the budget report interface is not nearly as nice as having full list of transactions.

**Comment by JC5** [comment]
Budget views always follow the set limit range. If you want to see a custom range for a budget, set a custom-ranged budget limit. You can do that by going to `/budgets`, change the date on top of the page and then set an amount for your budget using the + button.

**Comment by matejdro** [comment]
But I'm not trying to change the budgets. I just want to see the transactions, budgets here are only filtering method.

**Comment by JC5** [comment]
Sorry, this is all there is.

**Comment by matejdro** [comment]
Would you be willing to accept PR for this?

**Comment by JC5** [comment]
No. I'm working on a new layout though, with more extensive reporting capabilities.
