### ISSUE TITLE
Log budget amounts

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#7487]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

This has happened to me several times so far:

Let's say that I want to increase budget A by 100€. Simple, copy current amount into calculator, increase it by 100€ and then paste the new value into Firefly... oops, I have accidentally pasted the new value into budget B, overwriting its previous value. Now I have no way of knowing what the previous value for budget B was and thus my budget is messed up.

### Solution

Ideally, budget numbers would not be directly editable and the only way of editing them would be creating transactions (similar to how accounts work). But I realise this would be a huge change, so a simple budget history table display (that would maybe display a rolling list of past 5 values of selected budget).

### What are alternatives?

Sometimes I take the screenshot of the entire page before editing, but its manual process that requires me to remember to do it. I was also thinking of making external backup that would periodically save budget values via API somewhere externally, but that would still only work for changes that fall between backup periods.

**Comment by JC5** [comment]
Sorry no, this isn't going to be added.
