### ISSUE TITLE
Request for amount left to split

### ISSUE THREAD

**Issue by tannie** [firefly-iii/firefly-iii#749]
Would it be possible to have the amount left-over in a split to show near the table of split-purchases?

I know right now it shows the total amount allocated next to the amount in the transaction information box, but I'd like to see what amount I still need to add to a split transaction.

Use-case example: I buy dogfood, groceries and a few giftcards at Albert Heijn. I'd like to have (at least) three splits in that case and seeing the amount leftover saves me from having to add up certain purchases based on the receipt I have.

Thanks for your effort 😄

**Comment by JC5** [comment]
Good idea, will be added in the next release. The next release requires PHP7.1

**Comment by JC5** [comment]
Release is live.
