### ISSUE TITLE
Sorting via table headers of the transactions

### ISSUE THREAD

**Issue by jobacademy-it** [firefly-iii/firefly-iii#7493]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi! It would be really perfect if you could sort the transactions in the list view. Best by clicking on the heading. Sorting then upwards or downwards. For example by Description from A to Z.

### Solution

Hi! It would be really perfect if you could sort the transactions in the list view. Best by clicking on the heading. Sorting then upwards or downwards. For example by Description from A to Z.

**Comment by JC5** [comment]
Thanks for your suggestion!

This has been suggested a few times already and is on my list 👍
