### ISSUE TITLE
Transfer transactions are duplicated in export

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#750]
It might be intended behavior in which case you can just close this issue.

When exporting everything, transfers between accounts are included twice, since both accounts are exported and the transaction involves both.

**Comment by JC5** [comment]
Yep, it's a bug! 

https://github.com/firefly-iii/firefly-iii/issues/655

**Comment by simonsmiley** [comment]
searched for duplicate and didn't find anything... ^^
