### ISSUE TITLE
Monthly date range stops on the current day

### ISSUE THREAD

**Issue by easypaskk** [firefly-iii/firefly-iii#7501]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Issue #7456 not resolved. Date ranges are not working, and the balance of the budgets are wrong.
![image](https://github.com/firefly-iii/firefly-iii/assets/104469672/1309f04a-d1d4-4172-95cf-6101409f5032)
![image](https://github.com/firefly-iii/firefly-iii/assets/104469672/68764949-88f9-44c6-8750-5ca73201609a)
![image](https://github.com/firefly-iii/firefly-iii/assets/104469672/5f18eb12-e9bc-4ae6-9ca0-bd6ef3ff3a5f)

### Debug information

```
[2023-05-14 09:47:01] production.DEBUG: Default set is [5,1,13,9,11,3,15,7,25,109]
[2023-05-14 09:47:01] production.DEBUG: Frontpage preference set is [5,25,109,9,11,1,13,3,7]
[2023-05-14 09:47:01] production.DEBUG: Regenerate chart.account.account-balance-chart from scratch.
```

### Additional info

Version [6.0.10]

**Comment by JC5** [comment]
Can you replicate this on the demo site?

**Comment by easypaskk** [comment]
> Pouvez-vous reproduire cela sur le site de démonstration ?

On the demo site, the choice of dates works well.
For example, if I click "today", I have the whole month selected.

**Comment by JC5** [comment]
Are the setting on the demo site the same as in your own `/profile` and `/preferences`?

**Comment by easypaskk** [comment]
> Le réglage sur le site de démonstration est-il le même que sur le vôtre `/profile`et `/preferences`?
Ok. The setting was "Month to date" instead of "One month".

What misled me was the French translation:
"Un mois" - "Ce mois-ci".

This is not very explicit in French.

This solves the problem of displaying periods, but I still have bugs in the budgets. I played too much I think with weekly and monthly budget periods and it breaks problem now.

I will install from scratch and get my data back.
I'm going to go back to a mariadb version because I don't like PostgreSQL's case-sensitive problems.

Thanks for your help. I am very happy to use your software.

Translated with www.DeepL.com/Translator (free version)

**Comment by JC5** [comment]
That explains it. I'm happy that the issue is (almost) resolved. If you are willing to look over the translations, I will share the links later. OK?

**Comment by easypaskk** [comment]
Yes thank you it's ok

**Comment by JC5** [comment]
https://crowdin.com/translate/firefly-iii/142/en-fr?filter=basic&value=0#q=MTD
