### ISSUE TITLE
Deposits in export should switch src and dst accounts

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#751]
Currently withdrawls are "correct". The amount is negative, src is a personal account and dst is an expense account.

Deposits however have positive amounts while src is still the personal account and dst is the expense account. This doesn't look right...

**Comment by JC5** [comment]
The columns aren't named right, so I've fixed this for the new release. The exporter always starts with the current asset account: whether it's the source or the destination is not important.

The other account is not the destination (or the source), it simply is the opposing account.

So it's always a matter of something that happens to the asset account.

**Comment by JC5** [comment]
This should be more clear in the current release.
