### ISSUE TITLE
Email message text is not visible in KMail with dark theme

### ISSUE THREAD

**Issue by eandersons** [firefly-iii/firefly-iii#7511]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Most of email message text is not visible when a dark theme is applied in KMail.

![image](https://github.com/firefly-iii/firefly-iii/assets/9976861/82fcab33-ba8b-45a7-b994-d354d6155b36)

Seems that text colour is inverted, but not background.

In K-9 mail (Android) dark theme is applied correctly (bright text on dark background), so this issue might be specific to KDE Plasma and KMail when a dark theme is used for the system.

### Debug information

-

### Expected behaviour

Message text is visible either by

- allowing background colour to be inverted (preferred);
- forcing text colour to be dark.

### Steps to reproduce

1. Have a Linux desktop with KDE Plasma desktop environment.
2. Apply system dark theme (in this case Breeze Dark).
3. Wait for an event that triggers sending email message(s) from Firefly III.
4. Open KMail and read an email message from Firefly III.

**Comment by JC5** [comment]
I'm using the default Laravel email templates, I don't think I can fix this.

**Comment by JC5** [comment]
Yes, I am. Check out: https://github.com/laravel/framework
