### ISSUE TITLE
Data importer link wrong

### ISSUE THREAD

**Issue by Night-Hunter-NF** [firefly-iii/firefly-iii#7512]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

the link below in the importer goes to a url that doesn't exist 
![image](https://github.com/firefly-iii/firefly-iii/assets/66358962/e58a80a2-f13e-47f3-bdd0-5eaf04831e61)

same for this link
![image](https://github.com/firefly-iii/firefly-iii/assets/66358962/ae854500-e6e4-4790-9329-9f1fcf3a24d9)

### Debug information

NA

### Expected behaviour

the link should go to where ever on the docs its supported to

**Comment by JC5** [comment]
Nice find, I'll pick it up!
