### ISSUE TITLE
Webhook: wrong JSON transaction amount

### ISSUE THREAD

**Issue by kjgwallstadtadmin** [firefly-iii/firefly-iii#7516]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I fire a webhook, the amount shows a negative value.

{{ $json.body.content.transactions[0].amount }}

For example the output is -30€ but it shoud be +30€ or only 30€

### Debug information

`
"transactions":
[
{
"user":
1,
"transaction_journal_id":
365,
"type":
"deposit",
"date":
"2023-05-17T00:00:00+02:00",
"order":
0,
"currency_id":
1,
"currency_code":
"EUR",
"currency_symbol":
"€",
"currency_decimal_places":
2,
"foreign_currency_id":
null,
"foreign_currency_code":
null,
"foreign_currency_symbol":
null,
"foreign_currency_decimal_places":
null,
"amount":
"-30.00",
"foreign_amount":
null,
"description":
"Testbuchung",
"source_id":
1,
"source_name":
"Cash account",
"source_iban":
null,
"source_type":
"Cash account",`

### Expected behaviour

The output amount from JSON {{ $json.body.content.transactions[0].amount }} shoud be positive

**Comment by JC5** [comment]
Nice find, should be fixed in the next release :+1:
