### ISSUE TITLE
Time related events cause a timeout

### ISSUE THREAD

**Issue by th3guard1an** [firefly-iii/firefly-iii#7522]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Creating a budget with "set a fixed amount every period", produces the following ERROR.
Creating a budge with "auto-budget" works normally and doesn't crash.
Refreshing the page jumps ahead of the timeout, creates the budget "correctly" (as far as I'm aware).
Deleting budgets with the "set a fixed amount every period" also causes a timeout/crash.

Seems to be caused by an error reading the time. (The debug also chart also erroneously claims to be generated at 00:00:00 Europe/Lisbon)

I have the corresponding locales utf8 installed:
root@firefly3:~# locale

LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

And in my .env have theses settings:

DEFAULT_LANGUAGE=en_US
DEFAULT_LOCAL=
TZ=Europe/Lisbon

### Debug information

Debug information generated at 2023-05-18 00:00:00 Europe/Lisbon for Firefly III version **6.0.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.10 |
| Firefly III API | 2.0.1 |
| DB version | 19 (exp. 19) |
| Docker | No |
| PHP | `8.2.6` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Lisbon |
| Browser TZ | Europe/Lisbon |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 2097152 (2 MB) |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-02-17 00:00:00 |
| Session end | 2023-05-18 23:59:59 |
| Session first | 2023-02-14 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | pt_PT |
| Attempt at "pt_PT.utf8" | 'pt_PT.utf8' |
| Attempt at "pt_PT.UTF-8" | 'pt_PT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0 |

```
Truncated from this point <----|al.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  
[2023-05-18 22:29:43] local.ERROR: Cannot do addPeriod for $repeat_freq "last90"  

```

**Comment by JC5** [comment]
Nice find, thanks! I'll check it out. 

The debug time is caused by a method that's called `today()`, it doesn't take time into account. That is a bug but unrelated.
