### ISSUE TITLE
Make the search match on all fields

### ISSUE THREAD

**Issue by corcom** [firefly-iii/firefly-iii#7524]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I think it would be great if when using the search it just matched on all possible text fields.
For example if we have a few transactions like this:

Desc, src, dst, date, amnt, famnt, bdgt, cat, tag, bill, notes
Test, a, b, 1/1/1900, 10, 0, c, d, e, f, g
a, test, b, 1/1/1900, 10, 0, c, d, e, f, g
b, a, test, 1/1/1900, 10, 0, c, d, e, f, g
c, a, b, 1/1/1900, 10, 0, test, d, e, f, g
d, a, b, 1/1/1900, 10, 0, c, test, e, f, g
e, a, b, 1/1/1900, 10, 0, c, d, test, f, g
f, a, b, 1/1/1900, 10, 0, c, d, e, test, g
g, a, b, 1/1/1900, 10, 0, c, d, e, f, test

Ideally if I search for "test" or even just "tes" i would want to get all of them.
Currently I would only get the first line.

I am aware of the advanced search options, I just think that when searching a simple term the default beahviour should be to partially match on all text fields

### Solution

Better and simpler searching.

**Comment by JC5** [comment]
No sory, this will not change.

**Comment by corcom** [comment]
Sure, but why not?
