### ISSUE TITLE
Concatenate large number of attachments within an account

### ISSUE THREAD

**Issue by tanmayparikh** [firefly-iii/firefly-iii#7540]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I use the account attachments to upload PDF copies of my monthly statements I receive from the bank. I have over 50 of them in there now and the asset account page has gotten quite long. See video attached.

https://github.com/firefly-iii/firefly-iii/assets/66541279/00a1bc53-43d1-4a32-816c-d20d36185fb4

### Solution

Option 1: Limit the max height of the attachment card and add a secondary scrollbar to scroll through the extra documents.
Option 2: Limit the max height of the attachment card and make the title "Attachments" navigate to a dedicated attachments page where one can view/search all attachments associated with the account.

**Comment by JC5** [comment]
This can be something for the new layout: https://github.com/firefly-iii/firefly-iii/issues/6301
