### ISSUE TITLE
Login screen display glitch

### ISSUE THREAD

**Issue by canoine** [firefly-iii/firefly-iii#7541]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello,

Not really important, but, since 6.0 version, the translated "log in" button is awful on my browser :
[![FFIII.jpg](https://i.postimg.cc/LXz6KVpY/FFIII.jpg)](https://i.postimg.cc/LXz6KVpY/FFIII.jpg)

I suppose there's a way to dynamically enlarge the frame. No ?

### Debug information

Debug information generated at 2023-05-23 00:00:00 Europe/Paris for Firefly III version **6.0.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.10 |
| Firefly III API | 2.0.1 |
| DB version | 19 (exp. 19) |
| Docker | No |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Paris |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, syslog |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 8388608 (8 MB) |
| Interface | fpm-fcgi |
| Default language | fr_FR |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-07-01 00:00:00 |
| Session first | 2020-07-31 00:00:00 |
| User ID | 2 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0 |

### Expected behaviour

A pretty little "one-line" log-in button. :)

**Comment by JC5** [comment]
Ah nice, i guess the box is a tad too small for some translations. I'll pick it up!

**Comment by canoine** [comment]
Thank you. :)
