### ISSUE TITLE
Version link doesn't work

### ISSUE THREAD

**Issue by memo-567** [firefly-iii/firefly-iii#7546]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After moving to a new server, and a new domain (restoring everything incl. database), and an upgrade to 6.0.10, everything works fine - as far I can see, except the version link at the lower right:

![firefly mv2k com -  2023 - 05 - 25  11 - 30](https://github.com/firefly-iii/firefly-iii/assets/58190287/19b08f0c-8752-47e0-a458-97d6385d8203)

### Debug information

Hoppla! Ein Fehler ist aufgetreten.
Leider konnte dieser Fehler nicht wiederhergestellt werden :(. Firefly III ist kaputt. Der Fehler ist:

`file_exists(): open_basedir restriction in effect. File(/var/www/counter-main.txt) is not within the allowed path(s):`

**Comment by JC5** [comment]
Should be fixed in the next release
