### ISSUE TITLE
Rule Fails to Convert "Withdrawal from X to Y" to "Transfer from Y to X"

### ISSUE THREAD

**Issue by CraftingGamerTom** [firefly-iii/firefly-iii#7547]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Attempting to convert a withdrawal from a credit card (AKA a credit card payment) into a transfer from a bank account to the credit card account. When I import and the rules run, it remains a Withdrawal rather than a transfer and has the wrong destination. 

It seems to be related to how Im attempting to change the source account then the transaction type (see additional info). However I believe I am forced to do this because of the expectation/requirement of the "Convert to Transfer" action value.

### Debug information

Debug information generated at 2023-05-25 00:00:00 America/New_York for Firefly III version **6.0.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.9 |
| Firefly III API | 2.0.1 |
| Build | 466, 29-04-2023 06:55:07 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-02-24 11:24:35 |
| Session end | 2023-02-24 11:24:35 |
| Session first | 2018-04-20 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 |

### Expected behaviour

After rule runs:
Type should be Transfer
Source is supposed to be "Cornerstone Checking"
Destination is supposed to be "CC - Amex - Blue Cash"

### Steps to reproduce

**WRITTEN REPRESENTATION**

1. Create 2 accounts
  - X = "Name - WIth - Dashes"
  - Y = "Simple Name"
2. Create a Withdrawal from X to "(no name)" (destination doesnt matter at this point)
3. Create Rule 
  - Assume Triggers that find the above transaction properly
  - Action: Set Source Account to: value="Y"
  - Action Convert transaction to transfer: value="X"
4. Run the rule

Expected:
Type : Transfer
Source : "X"
Destination : "Y"

What happen
Type : Withdrawal
Source : "X"
Destination : "Y"

**VISUAL REPRESENTATION**
![image](https://github.com/firefly-iii/firefly-iii/assets/10101712/f761b37f-0c38-479b-90ce-f460f1a6d1ac)
RESULTS IN
![image](https://github.com/firefly-iii/firefly-iii/assets/10101712/63c9b225-b301-4766-8357-cb24ed46cb2c)

### Additional info

**INFORMATION 1**
I used another account below to show that this works if the Source Account is not the same source from the start.
![image](https://github.com/firefly-iii/firefly-iii/assets/10101712/4d265245-615e-401f-8d0c-b3ce1787d111)
results in
![image](https://github.com/firefly-iii/firefly-iii/assets/10101712/28de87cb-7acf-4a2b-a23f-b2b759975c17)

**INFORMATION 2**
I noticed this log on my debug page (in the sensitive section)
```
[2023-05-25 12:23:25] production.ERROR: Journal #3709 has already has "CC - Amex - Blue Cash" as a source asset. ConvertToTransfer failed. (rule #42).  
```

**INFORMATION 3**

https://docs.firefly-iii.org/firefly-iii/features/rules/#:~:text=From%20a%20withdrawal%20to%20a%20transfer
>From a withdrawal to a transfer
>The money will be moved away from the original asset account, into another asset account. The "action value" you must provide must be the name of a valid destination asset account. If it does not exist, the action will fail.
>If you leave the action value empty, the action will fail.

At time of the action to change the type my original asset account should be X and the destination is Y

**INFORMATION 4**
**YES THIS EXISTS ON THE DEMO ACCOUNT**
Started with this transaction
![image](https://github.com/firefly-iii/firefly-iii/assets/10101712/b257ae6d-8f16-4924-835c-6e94d38f5d8b)
Created this rule
![image](https://github.com/firefly-iii/firefly-iii/assets/10101712/4a42e17a-4dc8-43db-a0c1-0421b426dc70)
![image](https://github.com/firefly-iii/firefly-iii/assets/10101712/2b9e26cc-051b-4fcd-8fe5-408930a4b2d4)

Running the rule resulted in this
![image](https://github.com/firefly-iii/firefly-iii/assets/10101712/b842d7fe-e306-431f-a139-e3ca196253ae)

**Comment by CraftingGamerTom** [comment]
Found a workaround (but it is a pain if you need to do this for a dozen credit cards...)

Break up the actions into two rules.

It seems the "Convert to Transfer" Action is not considering that the source account has changed in a previous Action. So it thinks the Source Account is the same as the intended transfer destination account.

So I broke up the rule into two rules:
Rule 1: Set the Source Account
Rule 2: Convert the transaction into a Transfer

![image](https://github.com/firefly-iii/firefly-iii/assets/10101712/ad818702-9c65-493d-bf56-582e5851d8fe)

**Comment by JC5** [comment]
Nice find, I'll check it out :+1:. It should be possible to do this in one rule.

**Comment by CraftingGamerTom** [comment]
Did some digging into the code

[Line 457 of SearchRuleEngine.php](https://github.com/firefly-iii/firefly-iii/blob/6d0906c37be1ea3e516b7484f3fc4101e2503e42/app/TransactionRules/Engine/SearchRuleEngine.php#L457)
```
$result      = $actionClass->actOnArray($transaction);
```

It gets a reference to the original transaction since we are looping through each action seemingly without updating $journal (which I imagine is by design?)

So when we get to [Line 110 of ConvertToTransfer.php](https://github.com/firefly-iii/firefly-iii/blob/6d0906c37be1ea3e516b7484f3fc4101e2503e42/app/TransactionRules/Actions/ConvertToTransfer.php#L110)

```
return $this->convertWithdrawalArray($journal, $opposing);
```

The contained account ids are the same

So when we get to the function [validateTransferSource in TransferValidation.php](https://github.com/firefly-iii/firefly-iii/blob/f711fcfd520858fe433e6388b16c5ef30951094f/app/Validation/Account/TransferValidation.php#L95)

```
private function convertWithdrawalArray(array $journal, Account $opposing): bool
    {
        if ($journal['source_account_id'] === $opposing->id) {
            Log::error(
                vsprintf(
                    'Journal #%d has already has "%s" as a source asset. ConvertToTransfer failed. (rule #%d).',
                    [$journal['transaction_journal_id'], $opposing->name, $this->action->rule_id]
                )
            );

            return false;
        }
```

The action cannot continue throwing `ConvertToTransfer failed` exception


-----

@JC5 
I imagine this is not at simple as updating the journal after each action? If we are not already doing that then seems like that could be dangerous or even break rules in production if we add it now. Suggestions on fixing? Id be happy to help - I have limited php experience though.

**Comment by JC5** [comment]
It's a little much to do this through an issue. Patience, I'll get to it over the weekend. Your debugging points me in the right direction, thanks!

**Comment by JC5** [comment]
Will be fixed in the next release :+1:
