### ISSUE TITLE
Account Creation Duplicate Checking fails for German Umlaut

### ISSUE THREAD

**Issue by not1q84-1** [firefly-iii/firefly-iii#7549]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When creating (expense) Accounts German Umlaute (ÄÖÜ) are ignored for duplicate checking (I assume). If an account with an Umlaut is Created (BÄCKEREI TEST) and subsequently an Account with the "normal" vowel shall be created (BACKEREI TEST) no new account is visible and the API returnes the existing Accounts data. 

### Debug information

Debug information generated at 2023-05-26 00:00:00 Europe/Amsterdam for Firefly III version **6.0.8**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.8 |
| Firefly III API | 2.0.1 |
| Build | 454, 15-04-2023 10:59:29 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-05-01 00:00:00 |
| Session end | 2023-05-31 23:59:59 |
| Session first | 2013-06-07 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.50 |

### Expected behaviour

Two separate accounts should be created if BÄCKEREI TEST and BACKEREI TEST are requested

### Steps to reproduce

1. Create a new account where the name includes a German Umlaut (like "ä Test") through the GUI
2. Account is created
3. Try to create another account new account by replacing the Umlaut in the name with the "normal" character (here "a Test") through the GUI
4. Click on save
5. No new account with name "a Test" is created. Existing Account ("ä Test") is NOT updated (creation and update have the same timestamp)

**Comment by JC5** [comment]
Thanks for reporting! I see what you mean. I'm not sure if I can fix this. I will do some research.

* I rely on the database to tell me if an account with this particular name exists. I'm not going to add customizations to this process.
* I can't yet tell why it would return a success message referring to another account.

**Comment by not1q84-1** [comment]
Fully understood - my assumption was that you have a duplicate check based on the account name implemented and this check is not working for this particular case (encoding, character set etc).

**Comment by JC5** [comment]
I can't really fix this I'm afraid, your assumption is correct: https://stackoverflow.com/questions/41102371/sql-doesnt-differentiate-u-and-%C3%BC-although-collation-is-utf8mb4-unicode-ci

The current default table "collation" doesn't see the difference. I'm not sure if this can be change in existing databases. All I can do (and will do) is making sure that Firefly III correctly complains about the name already being in use (even though it's not really) and report it to the user.

**Comment by not1q84-1** [comment]
Many thanks for the education and taking care - I didnt know that!

**Comment by JC5** [comment]
Neither did I. Apparantly both the Swedish and German collation see the difference correctly. I have it on my list to see if I can add a "convert to collation x"-command.
