### ISSUE TITLE
biweekly budgeting option

### ISSUE THREAD

**Issue by skorvek** [firefly-iii/firefly-iii#7551]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Option for a biweekly budget in the period dropdown.  I budget by pay periods in most cases, which in my case is biweekly.  Thus a monthly budget is a bit wonky, and weekly doesn't make sense either. No interest in an annual budget- too many variables and mid-year adjustments.

### Solution

26 periods per year to match with a biweekly pay period

### What are alternatives?

Weekly skip 1? (not really an option either)

**Comment by JC5** [comment]
That's a no, sorry. 

https://github.com/firefly-iii/firefly-iii/issues/3982

**Comment by skorvek** [comment]
1) your reply link to the closed issue goes to a dead link. If that is intended to answer something about your philosophy with the documents, saying this isn’t zero based budgeting, this doesn’t apply.2) you have weekly and monthly options, which are only for gauging the amount left in each envelope. What do you use them for? How often do you get paid?I understand your system is “opinionated“ and that’s fine. It’s your system you can do what you wish but your reply is rude and doesn’t explain anything.On May 26, 2023, at 09:34, github-actions[bot] ***@***.***> wrote:﻿
Hi there! This is an automatic reply. Share and enjoy
This issue is now closed. Please be aware that closed issues are not actively monitored. If you reply, you may get no response.

If the original bug is not actually fixed, please feel free to open a new issue. Please refer to this issue for clarity.
Follow-up questions can also be posted in a new discussion

Thank you for your consideration.

**Comment by JC5** [comment]
Oh darn, sorry about the dead link.

But I'm afraid I'm not going to add a biweekly option. Most of Firefly III depends on single periods: one week, month, year, etc. It's too much effort for me, for a rarely asked feature.

**Comment by skorvek** [comment]
That's a totally different answer, and one which perhaps someday could be solved with a pull request.

But perhaps I'm not explaining clearly- I certainly wouldn't create a zero-based budget, for similar reasons as you've outlined in your docs, plus it's way too much work to try to account for every penny. But the reality is I get paid every 2 weeks, as do many people.  So I add money to my envelopes every 2 weeks- anything else is impossible to manage in real life or in firefly.

I don't track expenses/budgets on a 2-week period- that's insane.  I don't track monthly budgets either.  But in Firefly, categories serve one purpose, accounts another, and budgets seem to roll it all up into larger chunks.  

I can use an account to find how much I spent at a specific store- or a specific transaction at that store if I need to, and similar transactions are categorized by purpose- like groceries. But I'll have a household expenses budget to track how much I can spend/am spending of my discretionary budget on things to keep the house running. I don't need a grocery budget, a clothing budget, a trinkets tupperware budget- I just have a "Household" budget.  Utilities and mortgage and property taxes and other things are in separate budgets- on separate periods. That budget is broken down by those categories, but don't need to be neatly divided into separate envelopes- that would venture into the "accounting" territory that you rail against in your documents.

That said- to continue the household budget example (there are others)- I don't spend the same amount weekly/biweekly/monthly- it's very lumpy.  I'm fortunate enough to not have to live paycheck to paycheck, but I do want to keep an eye on spending to ensure I reach my goals and spend wisely.  For example, we have chest freezers and a pantry.  So when something we need/use regularly is on sale, I'll buy a lot of it and put it in the pantry/freezer. And going to Costco is an irregular event- at which time we'll stock up.  So I'd like my household budget to be quarterly-  monthly isn't even "regular" enough.  

But again- the funds come in 26x a year so I need to add the money to the envelopes on that schedule.  AS your docs say- decoupled spending from income- which means you track outgoing in whatever period makes sense for that envelope, but you take your income and spread it among the envelopes, including the piggybanks.

In my case I'm only talking about the discretionary budget- as stated in another thread, fixed expenses are subtracted right out of the paycheck into a separate pot (separate banks, not just firefly). I do have a biweekly mortgage, as it helps keep interest down, but the mortgage liability is enough to track that- no need for a budget there.  

If there was an option to top up the envelopes biweekly, then the budget period used everywhere else in firefly could remain as is. But right now they're coupled.
