### ISSUE TITLE
Negative Budgets

### ISSUE THREAD

**Issue by cinderblockgames** [firefly-iii/firefly-iii#7559]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

It would be nice if budgets could go negative, since that's a real life situation.  How do people handle overspending without that functionality?

### Solution

Negative budgets!

### What are alternatives?

I don't know!

### Additional context

Some of our budgets go negative.  It's not great, but it happens, and money management should be able to reflect that.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/7372

**Comment by cinderblockgames** [comment]
@JC5 How do you handle going over your budget in a month?

Let's say I have $20 in my budget and I need to get meds for $25. How should that be handled in Firefly?

**Comment by Zyadon7** [comment]
> @JC5 How do you handle going over your budget in a month?
> 
> Let's say I have $20 in my budget and I need to get meds for $25. How should that be handled in Firefly?

This is my use case as well.  If I set a grocery or one family members allowance as a budget, we can try not to go over, but it's very possible and good to track.  The ability to "add an amount every period and correct for overspending" is awesome, so allowing budgets to be negative integers is the only thing I'm missing.
