### ISSUE TITLE
Updating an account's information marks it as inactive

### ISSUE THREAD

**Issue by ASBaj** [firefly-iii/firefly-iii#756]
Hi,

Firstly, fantastic product. Really loving Firefly for finance managing. By far the best open-source and self-hosted one around.

Slight issue; when updating the information of an account (expense, asset, etc), the checkbox "active" always becomes "inactive", regardless of whether it is checked or unchecked. The only current workaround appears to be to change the "active" column in the database.

If you could propose a fix to test out, that'd be great.

Thanks!

**Comment by leander091** [comment]
Duplicate from #737

**Comment by JC5** [comment]
Thanks for the compliment! The inactive account thing is a known bug, and it'll be fixed in the next release. I hope to push this today or tomorrow. Remember that this requires PHP7.1 👍
