### ISSUE TITLE
Add option to subtract piggy bank additions from Income vs. expenses report

### ISSUE THREAD

**Issue by Solverz-0** [firefly-iii/firefly-iii#7568]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Due to there being no built in way to manage annual bills or non-monthly bills in terms of putting money aside for them every month until these type of bills are due, I add the money monthly to piggy banks.
Now as this would be seen as me saving money in firefly, it is not seen as an expense even though the money is not really "mine" as it is for a non-monthly bill. 
This means that in the Default financial report, Income vs. expenses section, it does not take into account these bill savings and shows an incorrect value when using firefly for non-monthly (annual) bills in the way explained above.

### Solution

I know this has been requsted before:
Have a built in feature to manage non-monthly bills with saving. I say non-monthly instead of annual as there could be bills that are every 3 months, 2 months, 6 months etc and not just annual but would still need saving each month for.

This is what this feature request is about: (As I know there is already a feature request logged for a built in feature)
Until there is a builtin feature to do this, have the option to minus certain piggy banks monthly contributions from the income vs expense report.

### What are alternatives?

Using a calculater and going into each bill piggy bank manually and minusing the values from the income vs expense report difference value.
Prone to human error if there are a number of bill piggy banks.
If I wanted to back track a couple of months I have to recalulate everytime.

**Comment by JC5** [comment]
No, sorry. I won't add this. I'm not going to build intermediate features; I'd rather spend time on the feature itself. 

> Now as this would be seen as me saving money in firefly, it is not seen as an expense even though the money is not really "mine" as it is for a non-monthly bill.

You could do this by saving the money on another (virtual) asset account that you exclude from the reports. It will then be seen as an expense as you expect.

**Comment by JC5** [comment]
Those you can already do with the "skip" option, but if it's too irregular I can't do much I'm afraid. Closing this ticket, thanks!
