### ISSUE TITLE
 support Feishu v2 webhooks

### ISSUE THREAD

**Issue by fshuanglan** [firefly-iii/firefly-iii#7569]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

 firefly webhooks function  support Feishu v2

### Solution

 webhooks function support Feishu v2

**Comment by JC5** [comment]
Is already supported. What is your question?

**Comment by JC5** [comment]
https://www.feishu.cn/hc/en-US/articles/360040566333
