### ISSUE TITLE
Amount field is missing when creating manually transfer

### ISSUE THREAD

**Issue by tomwerf** [firefly-iii/firefly-iii#757]
Hi, It's nice to see that Firefly becomes better every day! I Realy love the product!

There is a small bug when you create manualy transfers:

At /transactions/create/transfer the amount field is a hidden field.
After pressing the "Store new tranfer", an error occured for a fery short time, and you will be redirected back to /transactions/create/transfer. (Guess the error is: Amount is mandetory)
So it's not possible to create a tranfer.

Second problem is: After pressing the Quickswitch buttons you will be redirected to /# instead of #

**Comment by JC5** [comment]
Can you replicate this on the demo site? Which version are you running? These are both errors I would have heard about earlier, I think.

Could you run the following commands on your machine? It may remove the cause:

```
sudo apt-get remove javascript-common
sudo service apache2 restart
```

**Comment by tomwerf** [comment]
Ai, it's working on the demo site. I should try that before  posting...
I've tried two versions: 4.6.3.1 and 4.6.4, both with multiple browsers.
Both installations where on the same server.

Removing javascript-common did the trick!
It's working now!
Thanks!

**Comment by JC5** [comment]
Good to hear it!
