### ISSUE TITLE
More tag rule/search filters

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#7571]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Begins with, ends with, contains, etc.

### Solution

See above

**Comment by prononext** [comment]
Yes specific Filter functionality on the transactions would be really nice. Like searching for specific transactions without category etc. And also make the header be clickable to sort acending and decending on the columns.
