### ISSUE TITLE
Paid bill shown in wrong currency

### ISSUE THREAD

**Issue by kwillno** [firefly-iii/firefly-iii#7572]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Bills nominated in foreign currency and paid on default currency are shown with mismatched currency-name and amount.   
The name of the foreign currency is shown along with the amount in default currency. This happens both in the "Bills to pay" and the pie-chart in the dashboard. 

### Debug information

Debug information generated at 2023-06-01 11:40:05 Europe/Amsterdam for Firefly III version **6.0.11**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.11 |
| Firefly III API | 2.0.3 |
| Build | 490, 27-05-2023 07:21:11 CEST |
| Base Build | 3, 29-04-2023 14:45:54 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.5` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Oslo |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-05-01 11:31:42 |
| Session end | 2023-05-31 11:31:42 |
| Session first | 2023-04-06 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0 |

### Expected behaviour

The "bills paid"-field should show the amount paid in bills for each currency separately with the correct amount for that currency. Maybe the amount in default currency could be in a parenthesis. 

### Steps to reproduce

1. Create bill in a currency other than default currency, with expected time in the past.
2. Pay the bill, filling in both foreign currency and default currency in the withdrawal form, with the date being in the past.
3. Go back to the dashboard and check in the "Bills to pay" -> "Paid" field. 

### Additional info

I have tested the steps for reproduction in the demo-instance and encountered the same problem.

**Comment by kwillno** [comment]
NOK, Norwegian krone. If i remember correctly I had to add it myself, so that might have something to do with it.

**Comment by JC5** [comment]
No that doesn't matter. I was able to replicate the issue and I'll pick it up!

You kids and your multi currency shenanigans! 😉

**Comment by JC5** [comment]
I believe this is fixed, and I invite you to check it out on the demo site :+1:

**Comment by kwillno** [comment]
Yep, seems to be fixed in the demo-instance.
