### ISSUE TITLE
Wrong URLs in .env.example

### ISSUE THREAD

**Issue by josephbadow** [firefly-iii/firefly-iii#7580]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description
While setting up a new Firefly III instance I came upon the configuration and found some URLs pointing in the wrong direction.

#### database
Current URL: https://docs.firefly-iii.org/support/faq
Replace with: https://docs.firefly-iii.org/firefly-iii/faq/self-hosted/#i-want-to-use-sqlite

#### mail
Current URL: https://docs.firefly-iii.org/advanced-installation/email
Replace with: https://docs.firefly-iii.org/firefly-iii/advanced-installation/email/#email

#### authentication
Current URL: https://docs.firefly-iii.org/advanced-installation/authentication
Replace with: https://docs.firefly-iii.org/firefly-iii/advanced-installation/authentication

### Debug information

No Debug information available

### Additional info

I'm happy to create a pull request for that, but I wasn't sure if you might like an issue first. Also, merging the request might be more work than just replacing the URL.

**Comment by josephbadow** [comment]
I found two more and updated my initial description.

**Comment by JC5** [comment]
Oh nice find! Feel free to open a PR!
