### ISSUE TITLE
A transfer from a collective bank transfer may appear twice

### ISSUE THREAD

**Issue by jurgenhaas** [firefly-iii/firefly-iii#7586]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

In Germany, we do have "Collective bank transfers", which is multiple transfers combined to one from the originating bank account, each contained item going to a different destination bank account. This is helpful for faster processing (only have to provide 1 TAN instead of many for each transfer) and on some banks this helps to reduce transfer fees. The source destination bank statement shows just one transfer, and that's OK for Firefly-iii two.

However, if one of the transfer destinations is an account, that I also manage in Firefly-iii, then that transfer appears in that account, and as it recognizes the destination bank account which doesn't seem to have that transfer, it includes that transfer automatically in the list of transfers, despite the fact this transfer isn't coming from the bank statement.

That leads to double counting of that transfer on the destination bank account for which the collective transfer has been issued. And the balance is therefore wrong.

I can't just delete that transfer in Firefly-iii because it is the same record for the source and destination bank account.

### Solution

This is a difficult one, and I don't think there is an easy solution, if any at all. The only thing I can't think of is to add an attribute to the transfer to tell Firefly-iii to handle the amount in a specific way, for either of the transfers on the source account:

- on the collective bank transfer: adjust the balancing amount manually
- on the duplicate transfer received by the destination bank account: ignore the amount on destination

This may be perceived as an edge case, but here we're facing this issue quite a lot.

**Comment by JC5** [comment]
You'll have to manually create a second (and third, and fourth, if necessary) and split the difference yourself. 

If your bank doesn't provide this information (through the data importer for example) there is nothing I can do.

**Comment by jurgenhaas** [comment]
OK, I could reduce the amount of the collective bank transfer by the amount of the one received value out of it, and keep a note about it. That would at least keep the balance right.
