### ISSUE TITLE
Message: You are running 5.7.15, which is newer than the latest release, v6.0.11.

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#7587]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

While not a big problem, something is off with comparing versions:
```
Message: You are running 5.7.15, which is newer than the latest release, v6.0.11.
```

Semver would say that 5.7.15<6.0.11, and not the opposite.

### Debug information

I am running 5.7.15

### Expected behaviour

Correct message

### Steps to reproduce

lauch the start page

**Comment by JC5** [comment]
Thanks for reporting. I know about this, there are several people who have pointed this out already. Please use the search.
