### ISSUE TITLE
API: v1/recurrences not able to handle bills on Store & Update

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7588]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When creating recurrences, the webinterface allows assigning bills, and the API also reports the assigned bill on the `GET v1/recurrences/ID` endpoint.

However, the `POST` and `PUT` endpoints are unable to set a bill. The only way is to do so is via the webinterface (which uses an internal endpoint and not the API to update the recurrence).

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.11 |
| Firefly III API | 2.0.3 |
| Build | 490, 27-05-2023 07:21:11 CEST |
| Base Build | 3, 29-04-2023 14:45:54 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.5` |
| Host | `Linux` |

**Comment by JC5** [comment]
That's correct, the bill_id (or _name) aren't part of the API yet. But I'm fairly sure that's not what you're asking. I'll pick it up!

**Comment by JC5** [comment]
Should be fixed on the demo site, although it still reports 2.0.3. Let me know!

**Comment by JC5** [comment]
I see that too, I'll pick it up :+1:. Thanks for the feedback!
