### ISSUE TITLE
API: PUT v1/recurrences fails when updating a split transaction

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7589]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When trying to update a recurring transaction with a split (currently not possible to create via the webinterface, only via the API), the calls will fail when the update has the same amount of splits than the original transaction with the error `Cannot match recurring transaction to existing transaction. Not sure what to do. Break.`

Looking at the code around https://github.com/firefly-iii/firefly-iii/blob/main/app/Services/Internal/Update/RecurrenceUpdateService.php#L245 it seems like it tries to find the *exact* same transaction (based on the values of `$fields` at https://github.com/firefly-iii/firefly-iii/blob/main/app/Services/Internal/Update/RecurrenceUpdateService.php#L330), meaning it's basically impossible to update any of those fields (including the amount).

### Debug information

Demo Page

### Steps to reproduce

1. Create a recurring transaction with two splits:
```bash
curl -X 'POST' \
  'https://demo.firefly-iii.org/api/v1/recurrences' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer ey...' \
  -d '{
  "title": "Recurrence Split Test",
  "type": "withdrawal",
  "first_date": "2023-06-01",
  "repeat_until": "2024-05-31",
  "active": true,
  "repetitions": [
    {
      "type": "monthly",
      "moment": "1",
      "skip": 0,
      "weekend": 1
    }
  ],
  "transactions": [
    {
      "description": "Split 1",
      "amount": "12.34",
      "currency_id": "1",
      "source_id": "1",
      "destination_id": "7"
    },
    {
      "description": "Split 2",
      "amount": "56.78",
      "currency_id": "1",
      "source_id": "1",
      "destination_id": "7"
    }
  ]
}'
```
2. Try to update the splits with a new amount:
```bash
curl -X 'PUT' \
  'https://demo.firefly-iii.org/api/v1/recurrences/ID' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer ey...' \
  -d '{
  "title": "Recurrence Split Test Update",
  "transactions": [
    {
      "description": "Split 1 new",
      "amount": "43.21",
      "currency_id": "1",
      "source_id": "1",
      "destination_id": "7"
    },
    {
      "description": "Split 2 new",
      "amount": "87.65",
      "currency_id": "1",
      "source_id": "1",
      "destination_id": "7"
    }
  ]
}'
```

**Comment by JC5** [comment]
Nice one, I'll check it out! Not many people use this feature 😎

**Comment by JC5** [comment]
Alright the first attempt to fix this is up on the demo site. I expect plenty of bugs, but:

- All but 1 transactions under a recurrence need an ID to match their counterpart, to be submitted in field `id` (`transactions.0.id`).
- By that logic: If your recurrence has a single transaction, no ID is needed. In any other situation, n-1, because the last one can be matched by inference.
- If you submit MORE transactions, ALL existing transactions need to have the `id` field so Firefly III will know which ones are new.
- If you submit LESS transactions, any transactions you skip will be deleted. To keep them, submit arrays with just the ID `{"id": 1234}`.
