### ISSUE TITLE
Data Importer: Can't map data when using config file

### ISSUE THREAD

**Issue by taker218** [firefly-iii/firefly-iii#7605]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I just updated to the latest version of the data importer (1.3.0) and up until now I was able to "remap" the data that was configured in the configuration file.
There is no checkbox in the import configuration screen.

This was quite handy when importing from my normal bank account when there would be new opposing accounts.

### Debug information

Debug information generated at 2023-06-05 09:33:53 Europe/Amsterdam for Firefly III Data Importer version **1.3.0**.

| Scope | Version |
| --- | --- |
| FIDI | 1.3.0 |
| Build | 209, 04-06-2023 19:40:27 CEST |
| PHP | 8.2.6 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/Berlin |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0 |

### Expected behaviour

I would have expected to be able to map the data just like before.

### Additional info

I tried it with an uploaded configuration file as well as one, I stored in the configuration directory (mapped via docker volume).

**Comment by JC5** [comment]
Thanks, I'll check it out! Could you share your configuration file with me?

**Comment by taker218** [comment]
Sure, could you give me your mail adress? Then I'll send it to you.

**Comment by JC5** [comment]
james@firefly-iii.org

**Comment by taker218** [comment]
I just had to reauthenticate my Nordigen account and saw that there wasn't a checkbox for "Map data" in the configuration dialogue, even without a config file.

**Comment by JC5** [comment]
Should be fixed in the next release :+1:
