### ISSUE TITLE
Data Importer: Save config file on server

### ISSUE THREAD

**Issue by taker218** [firefly-iii/firefly-iii#7606]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I just realised that I can use the configuration directory to save my config-files for the importer.
When I change something in the configuration file, I need to download it and replace the one on the server with the new one.

### Solution

I would be nice to have the ability to just save the configuration file directly on the server instead of downloading/replacing it.

### What are alternatives?

Downloading the new configuration file, renaming it so it matches the one on the server and replace it.

**Comment by JC5** [comment]
Depending on how you use the data importer, you can map a local file or write to the directory yourself. There will not be an option to upload and replace files.
