### ISSUE TITLE
Description based rules breaking with (space) usage.

### ISSUE THREAD

**Issue by th3guard1an** [firefly-iii/firefly-iii#7609]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have a set of rules in which I specify the contents on the description, (either with "description is" description contains"), and some simply do not work at all. 
Eg, "The bank transfer".
Expected behaviour: Descrition is "The bank transferr" = detection
Actual behaviour: Doesn't recognize any transaction with this description.

Workarround:

Description contains: "The"
Description contains: "bank"
Description contains: "transfer"

I can't be sure when this problem arrised.

### Debug information

Debug information generated at 2023-06-06 00:00:00 Europe/Lisbon for Firefly III version **6.0.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.10 |
| Firefly III API | 2.0.1 |
| DB version | 19 (exp. 19) |
| Docker | No |
| PHP | `8.2.6` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Lisbon |
| Browser TZ | Europe/Lisbon |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 2097152 (2 MB) |
| Interface | fpm-fcgi |
| Default language | pt_PT |
| Default locale | pt_PT |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `192.168.1.83` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-05-06 00:00:00 |
| Session end | 2023-06-05 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | pt_PT |
| Attempt at "pt_PT.utf8" | 'pt_PT.utf8' |
| Attempt at "pt_PT.UTF-8" | 'pt_PT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0 |

**Comment by JC5** [comment]
I can't replicate this. On the demo site, using "daily shot" as the trigger value works fine.

**Comment by BoGnY** [comment]
I've the same problem...
Trigger with "description contains" shown related transaction correctly, but when applied, no transaction changes....

Related transaction:
![image](https://github.com/firefly-iii/firefly-iii/assets/11542801/528785f5-05cb-4f51-a741-20c7b16ac1d4)

Rules applied:
![image](https://github.com/firefly-iii/firefly-iii/assets/11542801/0b18deca-a23d-4c39-81aa-1b507d37a894)

**Comment by JC5** [comment]
If your bank adds many spaces, that could be the problem. They are generally not visible in HTML but they may show up when you edit the transaction.

**Comment by BoGnY** [comment]
You means many spaces on description?
I've checked using phpmyadmin but there aren't many spaces, only one...

But, even trying "description contains" and "description starts" with only "`Commissioni`" related transactions are shown but rules don't change nothing..

Oh maybe I found the problem... I make some test 👍🏻

**Comment by BoGnY** [comment]
Mmmmmm seems problem is on date range or account id..

`SearchRuleEngine::find()` founds transaction:
[related transaction check.log](https://github.com/firefly-iii/firefly-iii/files/11744604/related.transaction.check.log)

`SearchRuleEngine::fire()` don't found transaction:
[rule applied.log](https://github.com/firefly-iii/firefly-iii/files/11744605/rule.applied.log)

The differences are operator (applied only on `fire()`):
```log
[2023-06-14 12:15:56] local.DEBUG: SearchRuleEngine:: add local added operator: date_after:"2022-12-28"  
[2023-06-14 12:15:56] local.DEBUG: SearchRuleEngine:: add local added operator: date_before:"2023-06-14"  
[2023-06-14 12:15:56] local.DEBUG: SearchRuleEngine:: add local added operator: account_id:"1,1,1,1"  
```

**Comment by JC5** [comment]
I see what you mean, it's a problem in the test / execute form. I'll pick it up!

**Comment by BoGnY** [comment]
I've tested and I confirm is fixed 👍🏻
