### ISSUE TITLE
Spanish Support

### ISSUE THREAD

**Issue by giansalex** [firefly-iii/firefly-iii#761]
It has been thought in Spanish
![captura](https://user-images.githubusercontent.com/14926587/29256891-6b0ed966-8073-11e7-984f-aebeb2b0debf.PNG)

**Comment by JC5** [comment]
Spanish is only 15% translated.

Open your `.env` file and change `SHOW_INCOMPLETE_TRANSLATIONS` to `true`. Then it will be visible.
