### ISSUE TITLE
Bills are linked twice in different months

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#7615]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Im using "Liabilities" to track some credit.
Im using a bill to track the monthly payment for these credit.
Im using a "Withdraw" targeting the liabilitiy to "pay" the credit.
Im linking the bill to the Withdraw.

I dont know when it started, but currently I see my withdraws linked to more than one month at once.
![Bildschirmfoto_2023-06-08_17-10-06](https://github.com/firefly-iii/firefly-iii/assets/4060372/bbecf9d2-dfce-41d7-976e-365044b19b49)
I already tried to remove all linked bills and re-created them - without luck.
![Bildschirmfoto_2023-06-08_17-10-48](https://github.com/firefly-iii/firefly-iii/assets/4060372/89e304bc-6d99-4b4e-8d2f-837affc3d307)
![Bildschirmfoto_2023-06-08_17-11-33](https://github.com/firefly-iii/firefly-iii/assets/4060372/7803c309-9619-40c7-aed0-7a8866b3e6a7)

### Debug information

Debug information generated at 2023-06-08 17:15:30 Europe/Berlin for Firefly III version **6.0.11**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.11 |
| Firefly III API | 2.0.3 |
| Build | 490, 27-05-2023 07:21:11 CEST |
| Base Build | 3, 29-04-2023 14:45:54 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.5` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-05-01 17:09:51 |
| Session end | 2023-05-31 17:09:51 |
| Session first | 2019-10-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62 |

### Expected behaviour

I would expect to only have one linked withdraw per month in the bills view.

**Comment by devfaz** [comment]
Hi, thanks for the quick reply. Its a bit hard to see. The "withdraw" is linked to the same bill in different months!

f.e. 

the bill for April is linked to withdraw of 30.Apr - thats fine,

![Bildschirmfoto_2023-06-13_11-12-30](https://github.com/firefly-iii/firefly-iii/assets/4060372/78107c7e-201b-4052-a195-0e550cf79184)

but the bill for may is linked to the withdraw of 30.May *AND* the 30.Apr - thats some kind of wired isnt it?

![Bildschirmfoto_2023-06-13_11-11-37](https://github.com/firefly-iii/firefly-iii/assets/4060372/71a97454-7049-4a8c-8e4e-9efcd2500831)

**Comment by devfaz** [comment]
How can I "unlink" the bill from a withdraw?

**Comment by devfaz** [comment]
Well, i removed the linked bill from the transaction, then the transaction was no longer linked to any bill. great!

But then I edited the transation again to re-link it (to a single month, date and payment date are equal 30.04.), but the transation got linked to the bill of Apr and May. :|

**Comment by devfaz** [comment]
- I cleared all bills from the transactions
- deleted the existing bill
- created a new monthly (1st of month) bill.
- switched the date-selector to the month I would like the bill to be linked to the transaction
- edited the transaction to link to the bill
- the bill got linked to the month of the transaction + in the next month

I dont have any way to remove this wrong/double link of the transaction from the bill.

I also detected a different (maybe related bug) #7649

**Comment by devfaz** [comment]
Already tried it on demo, but it run into maintenance mode ;) So currently without luck. Maybe its related to that fact, that my target for the withdraw is a liability.

**Comment by devfaz** [comment]
https://demo.firefly-iii.org/bills/show/10

was able to reproduce the issue in demo.firefly-iii.org. I think its related to "expected bill date" and the transaction date. If the transaction date is after the expected date, the bill seems to be linked in both months

**Comment by JC5** [comment]
But those are two different transactions. Linked to one bill. Right? One has "again" in the transaction title.

**Comment by JC5** [comment]
https://demo.firefly-iii.org/transactions/show/453

And

https://demo.firefly-iii.org/transactions/show/452

Two transactions.

**Comment by devfaz** [comment]
Lets try to give more details:

- open https://demo.firefly-iii.org/bills
- look for the Bill "RatePV"
- switch dates to "Jun 1st - Jun 30th" in the top right
- the Bill "RatePV" is marked as payed by a transaction of 31th of May
- switch dates to "May 1st - May 31th"
- also in this month the bill is marked as payed by the same transaction from may 31th

so we have 2 monthly bills marked as payed by a single transaction.

**Comment by JC5** [comment]
Ah, I see what you mean. This particular doesn't use the date from the top to change the view. I believe it's always the same regardless of the date at the top. But I'll check it out.

**Comment by JC5** [comment]
Yes, the view is always the same. This is not a bug as such. Thanks for helping me find it!

**Comment by devfaz** [comment]
Don't get what you want to say.

If I switch the date to any other month, the bill is not marked as paid in this month.

Also I would not expect to see 2 dates/links?!

What do I miss?
