### ISSUE TITLE
Error when creating a new Personal TOKEN

### ISSUE THREAD

**Issue by MrCaringi** [firefly-iii/firefly-iii#7619]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am trying to generate a new "Personal Access Tokens"

But the process fails:

![image](https://github.com/firefly-iii/firefly-iii/assets/47096567/f458d6c4-aabe-448a-ade4-e72e0d3f76c0)

### Debug information

![image](https://github.com/firefly-iii/firefly-iii/assets/47096567/764e8250-afd8-4537-8d0e-ed5def781d46)

Debug information generated at 2023-06-09 09:25:49 America/Monterrey for Firefly III version **6.0.11**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.11 |
| Firefly III API | 2.0.3 |
| Build | 490, 27-05-2023 07:21:11 CEST |
| Base Build | 3, 29-04-2023 14:45:54 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.5` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Monterrey |
| Browser TZ | America/Mexico_City |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-06-01 00:00:00 |
| Session end | 2023-06-30 23:59:59 |
| Session first | 2017-07-05 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0 |

### Expected behaviour

To get a message with the TOKEN string

### Steps to reproduce

1. access "profile" URL
2. select "OAuth" tab
3. Clic button "Create new token" in "Personal Access Tokens" section
4. Indicate the token name

**Comment by JC5** [comment]
What are your email settings?

**Comment by JC5** [comment]
Never mind, found and fixed.

**Comment by MrCaringi** [comment]
> Never mind, found and fixed.

excuse me, I update firefly to lastest version, but did worked:

```
firefly-iii-app | [Tue Jun 13 19:04:59.730510 2023] [php:error] [pid 234] [client 172.28.0.1:42814] PHP Fatal error:  Uncaught TypeError: Symfony\\Component\\Mailer\\Transport\\Dsn::__construct(
): Argument #2 ($host) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php on line 186 and defined in /var/www/html/vendor/sy
mfony/mailer/Transport/Dsn.php:28\nStack trace:\n#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(186): Symfony\\Component\\Mailer\\Transport\\Dsn->__construct()\n#1
 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(165): Illuminate\\Mail\\MailManager->createSmtpTransport()\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/M
ail/MailManager.php(123): Illuminate\\Mail\\MailManager->createSymfonyTransport()\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(98): Illuminate\\Mail\\MailManage
r->resolve()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(76): Illuminate\\Mail\\MailManager->get()\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Ma
il/MailManager.php(563): Illuminate\\Mail\\MailManager->mailer()\n#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\\Mail\\MailManager->__call(
)\n#7 /var/www/html/app/Jobs/MailError.php(85): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Fire
flyIII\\Jobs\\MailError->handle()\n#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()\n#10 /v
ar/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()\n#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Conta
iner/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()\n#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\Bo
undMethod::call()\n#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()\n#14 /var/www/html/vendor/laravel/framework/src/Ill
uminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()\n#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\P
ipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()\n#17 /var/www/html
/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()\n#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline
.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()\n#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipel
ine->Illuminate\\Pipeline\\{closure}()\n#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()\n#21 /var/www/html/vend
or/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()\n#22 /var/www/html/vendor/laravel/framework/src/Illuminate/
Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()\n#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()\n#24
 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(253): Illuminate\\Queue\\SyncQueue->push()\n#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php
(229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()\n#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue()\n#27 /v
ar/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\\Bus\\Dispatcher->dispatch()\n#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Fo
undation/helpers.php(388): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()\n#29 /var/www/html/app/Exceptions/Handler.php(223): dispatch()\n#30 /var/www/html/vendor/laravel/framework/s
rc/Illuminate/Foundation/Bootstrap/HandleExceptions.php(182): FireflyIII\\Exceptions\\Handler->report()\n#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExce
ptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#32 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Boo
tstrap\\{closure}()\n#33 {main}\n  thrown in /var/www/html/vendor/symfony/mailer/Transport/Dsn.php on line 28

**Comment by MrCaringi** [comment]
> > Never mind, found and fixed.
> 
> excuse me, I update firefly to lastest version, but did worked,
> 
> I have no SMTP configuration by the way.
> 
> ```
> firefly-iii-app | [Tue Jun 13 19:04:59.730510 2023] [php:error] [pid 234] [client 172.28.0.1:42814] PHP Fatal error:  Uncaught TypeError: Symfony\\Component\\Mailer\\Transport\\Dsn::__construct(
> ): Argument #2 ($host) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php on line 186 and defined in /var/www/html/vendor/sy
> mfony/mailer/Transport/Dsn.php:28\nStack trace:\n#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(186): Symfony\\Component\\Mailer\\Transport\\Dsn->__construct()\n#1
>  /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(165): Illuminate\\Mail\\MailManager->createSmtpTransport()\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/M
> ail/MailManager.php(123): Illuminate\\Mail\\MailManager->createSymfonyTransport()\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(98): Illuminate\\Mail\\MailManage
> r->resolve()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(76): Illuminate\\Mail\\MailManager->get()\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Ma
> il/MailManager.php(563): Illuminate\\Mail\\MailManager->mailer()\n#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\\Mail\\MailManager->__call(
> )\n#7 /var/www/html/app/Jobs/MailError.php(85): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Fire
> flyIII\\Jobs\\MailError->handle()\n#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()\n#10 /v
> ar/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()\n#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Conta
> iner/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()\n#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\Bo
> undMethod::call()\n#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()\n#14 /var/www/html/vendor/laravel/framework/src/Ill
> uminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()\n#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\P
> ipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()\n#17 /var/www/html
> /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()\n#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline
> .php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()\n#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipel
> ine->Illuminate\\Pipeline\\{closure}()\n#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()\n#21 /var/www/html/vend
> or/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()\n#22 /var/www/html/vendor/laravel/framework/src/Illuminate/
> Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()\n#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()\n#24
>  /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(253): Illuminate\\Queue\\SyncQueue->push()\n#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php
> (229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()\n#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue()\n#27 /v
> ar/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\\Bus\\Dispatcher->dispatch()\n#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Fo
> undation/helpers.php(388): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()\n#29 /var/www/html/app/Exceptions/Handler.php(223): dispatch()\n#30 /var/www/html/vendor/laravel/framework/s
> rc/Illuminate/Foundation/Bootstrap/HandleExceptions.php(182): FireflyIII\\Exceptions\\Handler->report()\n#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExce
> ptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#32 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Boo
> tstrap\\{closure}()\n#33 {main}\n  thrown in /var/www/html/vendor/symfony/mailer/Transport/Dsn.php on line 28
> ```

Hi @JC5 

excuse me, do you know how to overcome this problem?

The issue was closed, but it is not working with the last version
