### ISSUE TITLE
Issues with light mode

### ISSUE THREAD

**Issue by rchl** [firefly-iii/firefly-iii#7620]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

There are issues with colors of some form elements when light mode is selected in firefly preferences but dark mode is preferred system-wide.

### Debug information

Debug information generated at 2023-06-09 22:42:24 Europe/Oslo for Firefly III version **6.0.11**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.11 |
| Firefly III API | 2.0.3 |
| Build | 490, 27-05-2023 07:21:11 CEST |
| Base Build | 3, 29-04-2023 14:45:54 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.5` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Oslo |
| Browser TZ | Europe/Oslo |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | nb_NO |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-06-01 00:00:00 |
| Session end | 2023-06-30 23:59:59 |
| Session first | 2022-03-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0 |

### Expected behaviour

Light colors when using light theme.

### Steps to reproduce

2. In FireflyIII's Layout/Dark mode settings select `Always Light` and in the system settings (in my case OSX) set Dark mode as preferred setting
3. Go to Edit view for any rule in automation settings

This is the result I see:

![Screenshot 2023-06-09 at 22 47 00](https://github.com/firefly-iii/firefly-iii/assets/153197/9e6c798d-d4e3-453d-b8f3-9dcaeb8a0c81)

Note the text selection color having bad contrast and not enabled checkboxes being dark.

### Additional info

This reproduces both in Firefox and Chrome.

It looks like some dark mode rules are applied through the `@media (prefers-color-scheme: dark)` media rule but since light mode is forced in the settings those shouldn't be added in the first place.

**Comment by rchl** [comment]
Oh, it's especially bad in the "hint" notification boxes since it makes them unreadable:

![Screenshot 2023-06-09 at 22 55 49](https://github.com/firefly-iii/firefly-iii/assets/153197/1ffaebea-f1eb-44a9-a173-ba5a75a182a6)

**Comment by JC5** [comment]
Thansk for letting me know, I'll check it out!

**Comment by JC5** [comment]
I fixed all of them except the checkboxes, nothing I can find online seems to work.

**Comment by JC5** [comment]
I'm not going to fix the intro boxes btw, those will get a tune-up in the new layout anyway.
