### ISSUE TITLE
Bug: hide foreign currency fields if only one currency is enabled (possible regression)

### ISSUE THREAD

**Issue by jansepke** [firefly-iii/firefly-iii#7625]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

First thank you for this great tool, wanted to build something similar but then I found your solution.

4 years ago you implemented a feature request #2521 to hide the foreign currency field in the new transaction form if only one currency is enabled. But in this commit f6ecb143fe6f589e455d1c260775f86f37917805 you removed the implementation. Was there a specific reason?

### Debug information

.

**Comment by JC5** [comment]
I honestly can't remember, but I'm not going to fix it. I want to focus on the new layout.
