### ISSUE TITLE
Feature: disable unneeded parts (e.g. Budgets, Piggy Banks)

### ISSUE THREAD

**Issue by jansepke** [firefly-iii/firefly-iii#7626]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I like all the different features that Firefly offers. But I will only use some of them. Would you think about hidden some features from the UI so it is less cluttered and easier to use. For me it would be enough to hide them via ENV variable. I was thinking about hiding:

* Foreign currency in transaction form
* Piggy Banks
* Budgets

I would also be willing to take a look at the code and implement this myself if you are open for such a feature.

### Solution

Hide certain features completely from the UI

**Comment by JC5** [comment]
No. This is a huge maintenance and development burden.
