### ISSUE TITLE
Manually triggering webhook fails to execute

### ISSUE THREAD

**Issue by brujoand** [firefly-iii/firefly-iii#7636]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm in the process of writing a companion app that will massage the data imported by Nordigen. For this I'm relying on webhooks but I can't seem to trigger them.

I've verified that `$ALLOW_WEBHOOKS=true` in the container running Firefly, I've also verified that I can reach the webhook url from firefly. Both from the web ui and in a shell.

The webhook is set to trigger `After transaction creation` and responds with `Transaction details (JSON)`. But when I manually trigger the webhook and provide a valid transaction id nothing happens. There is no incoming request on my companion app, and no webhook related output in the logs. In the firefly web ui I'm redirected to the front page.

The endpoint `api/v1/webhooks/1/messages` shows 0 messeages, so to me this seems like it fails before even triggering. 

Manually creating a transaction did actually trigger the webhook to execute, and I got the request in my companion app. Is there some per transaction settings aswell for allowing webhooks? I couldn't find any fields for that under the transaction atleast. 

### Debug information

Debug information generated at 2023-06-11 00:00:00 Europe/Oslo for Firefly III version **6.0.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.9 |
| Firefly III API | 2.0.1 |
| Build | 466, 29-04-2023 06:55:07 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.4` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Oslo |
| Browser TZ | Europe/Oslo |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

### Expected behaviour

I would have expected to either see some log/ui output about why this failed, or to have the webhook url be hit with a request.

### Steps to reproduce

1. Create simple web server listening for post requests
2. Create webhook for created transactions with reference to server on step 1
3. Manually trigger webhook and provide a valid transaction id

### Additional info

The webhook in question:

```
{
  "data": {
    "type": "webhooks",
    "id": "1",
    "attributes": {
      "created_at": "2023-06-11T09:58:23+02:00",
      "updated_at": "2023-06-11T10:36:12+02:00",
      "active": true,
      "title": "Fireflayer clean new transactions",
      "secret": "supersecret",
      "trigger": "STORE_TRANSACTION",
      "response": "TRANSACTIONS",
      "delivery": "JSON",
      "url": "http://10.1.0.23:8080"
    },
    "links": {
      "self": "http://10.30.0.9:8080/api/v1/webhooks/1",
      "0": {
        "rel": "self",
        "uri": "/webhooks/1"
      }
    }
  }
}
```

Log output from triggering the webhook:
```
[2023-06-11T10:39:05.106211+02:00] local.INFO: AUDIT: User visits homepage. (10.133.64.239 (myuser) -> GET:https://firefly.mydomain.com) [] []
[2023-06-11 10:39:05] local.INFO: Update check is not enabled.
10.133.86.110 - - [11/Jun/2023:10:39:04 +0200] "GET / HTTP/1.1" 200 8688 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /v1/jscript/variables?ext=.js&v=6.0.9 HTTP/1.1" 200 3970 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /json/box/balance HTTP/1.1" 200 2952 "-" "Mozilla/5.0 (Macintosh; IntelMac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /chart/category/frontpage HTTP/1.1" 200 2834 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /chart/account/revenue HTTP/1.1" 200 2934 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /chart/budget/frontpage HTTP/1.1" 200 3014 "-" "Mozilla/5.0 (Macintosh;Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /json/frontpage/piggy-banks HTTP/1.1" 200 2843 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /chart/account/expense HTTP/1.1" 200 2933 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /chart/account/frontpage HTTP/1.1" 200 7115 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /json/box/net-worth HTTP/1.1" 200 2870 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /api/v1/summary/basic?start=2023-06-01&end=2023-06-30 HTTP/1.1" 200 1177 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
10.133.86.110 - - [11/Jun/2023:10:39:05 +0200] "GET /json/box/available HTTP/1.1" 200 2983 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
```

**Comment by JC5** [comment]
> Is there some per transaction settings as well for allowing webhooks?

There is, yes, but it should default to `true`. 

https://api-docs.firefly-iii.org/#/transactions/storeTransaction

**Comment by brujoand** [comment]
Ah, and since "ALLOW_WEBHOOKS" was previously "false" all existing transactions needs an update to allow webhooks. 

Works as expected then, my bad. Thanks!

**Comment by JC5** [comment]
Not a problem, glad to hear it!
