### ISSUE TITLE
New expense account created if original same-named expense account is set to 'not active'

### ISSUE THREAD

**Issue by tannie** [firefly-iii/firefly-iii#764]
When I have expense account set to 'not active' and then create a withdrawal and fill in the name of the expense account (or, I get a suggestion after typing the first few letters and select it), I end up with two expense accounts with the same name. One active, one inactive. 
I would expect the inactive account to become active again, and the withdrawal going into that account. I have tested this on the demo site and the same thing happens there, however, I did set the expense account to inactive manually. On my server I've had this experience with automatic inactive accounts.
Related to this: what is the idea behind setting accounts to inactive automatically? For speed?

Would it make more sense to activate the original account when I create a new transaction with that expense account name?

**Comment by JC5** [comment]
No accounts should be made inactive automatically. There's no such process. There was a bug that made editing them inactive. 

I'll look into these other things this week!

**Comment by JC5** [comment]
In the new release, the auto-suggest box will no longer suggest inactive accounts. If you type them in manually, they will be reactivated.

I wonder how your accounts came to be inactive. Were these accounts you manually edited?

**Comment by tannie** [comment]
I didn't edit accounts directly as far as I remember, but I did merge a couple and moved transactions from one expense account to another. I had imported a bunch of transactions (thousands... dating back to 2006 😉 ) and needed to do some cleanup, I didn't check after every change I made... 

It hasn't happened since the latest update and I'm still doing cleanup so I _think_ that whatever caused it got fixed, but I'll keep an eye on it, just in case.

**Comment by JC5** [comment]
Please do, and keep me posted. :+1: 

If you find anything else, don't hesitate to report it!
