### ISSUE TITLE
Locale for new nn_NO language needed on Docker image

### ISSUE THREAD

**Issue by SlimG** [firefly-iii/firefly-iii#7648]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm testing the new nn_NO language on the fireflyiii/core:develop docker image, and notice the following errormessage on the dashboard:

> Invalid server configuration: Firefly III is unable to format monetary amounts because your server is missing the required packages. There are instructions how to do this.

I managed to make the errormessage disappear by manually appending "nn_NO.UTF-8 UTF-8" to /etc/locale.gen and running "/usr/sbin/locale-gen" and restarting the container.

### Debug information

Invalid server configuration: Firefly III is unable to format monetary amounts because your server is missing the required packages. There are instructions how to do this.

### Steps to reproduce

1. Change language to nn_NO
2. Go to Dashboard

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/7642

**Comment by SlimG** [comment]
It looks like your fix did not appear in todays 6.0.15 release at docker hub. I'm getting the following errormessage on the dashboard:

Invalid server configuration: Firefly III is unable to format monetary amounts because your server is missing the required packages. There are instructions how to do this.
