### ISSUE TITLE
Edit of a bill will always show daily interval

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#7649]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If I edit a monthly bill, the interface shows this bill as "daily". The "next expected" is correct, so maybe just some display issue.

### Debug information

[demo.firefly-iii.org](https://demo.firefly-iii.org/bills/edit/10)

### Expected behaviour

the correct interval is shown

### Steps to reproduce

* create a monthly bill
* edit the monthly bill (try to change the monthly -> weekly)
* save
* edit the monthly bill (weekly is shown as daily)

**Comment by JC5** [comment]
I see what you mean, I'll check it out 👍
