### ISSUE TITLE
Is possible to install FF3 without composer and php?

### ISSUE THREAD

**Issue by muhahacz** [firefly-iii/firefly-iii#765]
Hello, weird question...
Is possible to install FF3 without composer and php? 

In environment, where you have standalone docker container with php-fpm, other container with nginx ...is really hard to install FF3.  Why to use custom docker image? (alpine linux, different architecture, etc ... )

For example, i can download Nextcloud in docker container, simple curl, no need other dependencies.
It is downloaded to volume, which is shared across nginx and php-fpm containers. This way i can run multiple applications and i dont need to run multiple php+nginx containers / per applications.

Thanks

**Comment by JC5** [comment]
If you have any machine with composer you can simply run the composer commands on that machine and copy the packages over.

**Comment by muhahacz** [comment]
Will it possible, that some day you will be providing fully packed version of Firefly? Even with part, that initialize the database? Thanks

**Comment by JC5** [comment]
Sorry, no.
