### ISSUE TITLE
Display Firefly-iii as standalone when added to Homescreen

### ISSUE THREAD

**Issue by Cryptec** [firefly-iii/firefly-iii#7653]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I´d love to have Firefly-iii as full-screen standalone app when added to homescreen on iOS or Android. For reference: https://developer.mozilla.org/en-US/docs/Web/Manifest/display

### Solution

i saw it´s already added in https://github.com/firefly-iii/firefly-iii/blob/main/public/manifest.webmanifest, but this seem to not work as it should (at least on iOS and ipadOS), didn´t tested it on Android.

**Comment by JC5** [comment]
It works fine for me. Have you tried it on the demo site?

**Comment by Cryptec** [comment]
Hi James, yes i also tried it on the Demo Site, same result. 
            Message ID: ***@***.***>

            
        

regards

**Comment by JC5** [comment]
So what are you expecting exactly? I can add the demo site to my Home Screen just fine. Do you have a site that works as you expect it to?

**Comment by Cryptec** [comment]
Sorry, i have to correct myself. It works on iOS as expected, only iPadOS do Not Display correctly. But to clarify we talking about the same. I can Add it Just Fine to every homescreen, and it Works as expected, but its Not Displayed as standalone (Full Screen, wothout Browser navbar). I have tested it with a Website i wrote on iPad, and this Site works just Fine in standalone. So maybe its a Bug.

**Comment by JC5** [comment]
What's the difference between the manifest files?

**Comment by Cryptec** [comment]
I cant find any differrences https://github.com/Cryptec/todolist/blob/main/Frontend/public/manifest.json.Weird. I tested it multiple times now but it doesn‘t work for firefly-iiiMessage ID: ***@***.***>

**Comment by JC5** [comment]
Sorry, then I don't know what it could be.

**Comment by JC5** [comment]
That's weird! I'm so glad you found it, I would never have thought of that. I'll see if I can fix that. Thanks for letting me know!
