### ISSUE TITLE
"Apply rules" uses bank account ID 1 for all bank accounts

### ISSUE THREAD

**Issue by luukdobber** [firefly-iii/firefly-iii#7659]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am unable to apply a rule or rule group to all my bank accounts (`rule-groups/select/<rule id>` page). The form submits bank account ID 1 for all bank accounts. The `value` attribute of the checkbox has an incorrect value of `1` in stead of the actual ID of the bank account:

```
<strong>Default asset accounts</strong><br />
<div class="checkbox" style="margin-left:2em;">
    <label>
        <input type="checkbox" name="accounts[]" id="291" value="1" checked>
        ASN Betaalrekening
    </label>
</div>
<div class="checkbox" style="margin-left:2em;">
    <label>
        <input type="checkbox" name="accounts[]" id="1" value="1" checked>
        ING Betaalrekening
    </label>
</div>
```

[This change](https://github.com/firefly-iii/firefly-iii/commit/0438fb5a2e1c8d0abc92a21bcc02af2b626616b1#diff-3fa15386c3807931464a4bcb34ea693f6989f01120a2729eed1be728087fa6cc) might have introduced this bug. I think the boolean argument for `Html.checkbox` or `Form.checkbox` is used for the `value` attribute and rendered as `1`. If I change the value to the correct ID using my browsers developer tools, the rules are executed correctly for the selected account.

### Debug information

Debug information generated at 2023-06-15 13:34:54 UTC for Firefly III version **6.0.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.13 |
| Firefly III API | 2.0.4 |
| Build | 506, 11-06-2023 16:24:57 UTC |
| Base Build | 6, 10-06-2023 16:13:33 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-06-01 00:00:00 |
| Session end | 2023-06-30 23:59:59 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15 |

### Expected behaviour

Firefly executes the rules for all selected bank accounts, not only the one that happens to have ID 1.

### Steps to reproduce

1. Make sure there is a bank account with an ID other than 1
2. Create a rule
3. Click on the "Apply rule" button for the rule
4. Select the bank account that doesn't have ID 1
5. Click "Execute"

The rule should have been applied on transactions for the selected bank account, but they will only be applied on the bank-account with ID 1.

**Comment by JC5** [comment]
I just had this discussion in another thread and this will be fixed in a new release 👍
