### ISSUE TITLE
Docker Persistance

### ISSUE THREAD

**Issue by inkonthebrink** [firefly-iii/firefly-iii#766]
Hi,

Any chance you have the volume names for running Docker with persistent volumes? I cna then mount them to the localhost volumes I have setup.
Also, any chance you can include NZD in the currency?

Cheers, 

Great app.

**Comment by JC5** [comment]
I'm not sure how that would work, I haven't created the docker images.

You can add NZD yourself, using the page at `/currencies`.

**Comment by inkonthebrink** [comment]
Ok, I'll investigate, if I can find a solution will post on this thread. Oh ok, thanks.
