### ISSUE TITLE
Editing transaction breaks firefly

### ISSUE THREAD

**Issue by ASBaj** [firefly-iii/firefly-iii#767]
Hi,

I'm having an issue with a particular transaction. When I attempt to edit it, I get the following error:

file_put_contents(/var/www/html/asbfireflyiii/storage/framework/cache/08/f1/08f12db264811520887c26ed515353aa777b781a): failed to open stream: No such file or directory 

This error appeared to occur when I originally edited the transaction. I changed the asset account.

**Comment by ASBaj** [comment]
Fixed. I ended up clearing the entire cache. When firefly generated a new cache, everything started working again.

**Comment by JC5** [comment]
Glad to hear it works! 👍
