### ISSUE TITLE
Sort Accounts

### ISSUE THREAD

**Issue by gpampuro** [firefly-iii/firefly-iii#7679]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like Firefly allows to sort the Asset Accounts in the Dashboard and the Accounts list.
The current order is just by the creation order or Account ID, but would be great to sort by name, role, balance, last activity or any column included in the table.

### Solution

Change the table layout to be able to sort by any of the columns included in the table.

**Comment by JC5** [comment]
Sorry, this feature was dropped in favor of the ability to do a custom sort.
