### ISSUE TITLE
Bill match on a transfer?

### ISSUE THREAD

**Issue by zikeji** [firefly-iii/firefly-iii#768]
So my bill is between X and X (where X and X are both the same) on the 18th, for example. I've set the auto match, and created a transfer from X account to Y account with the match as the description. However, this isn't picked up. And re-scanning transactions doesn't pick it up either.

Do transfers not count as bills?

**Comment by JC5** [comment]
No, bills are really linked to expenses only.

**Comment by zikeji** [comment]
How do I handle credit card payments in FireFly then? If I do a transfer from my debit account to my credit account, it isn't counted as revenue or expense (which makes sense, since I track credit transactions and wouldn't want to double count them). If I make a separate revenue and expense transaction, it solves the bill issue but creates a new issue (more revenue and expense knocked off).

**Comment by JC5** [comment]
Isn't the original payment linked to a bill?

Firefly used to have the possibility to at least _see_ the amount you were due on the credit card in a pie chart, but that code was horribly complex so I dropped it.

The way I do it myself:

- Any expense on the CC gets booked as a normal withdrawal, just from the credit card.
- These expenses could be linked to a bill, which works as it always does.
- The credit card drops into the negative (ie. -400) depending on what is removed from the card.

At the end of the month, my bank charges me the amount due. It's withdrawn from my main checking account. This is a transfer, bringing the amount on the CC back to zero.

Any bills have already registered when the original credit card payment was done.

**Comment by zikeji** [comment]
In this case the credit card is essentially a loan. I pay a static amount every month on it, and there are never expenses added to it. So it's nice to have the "Bills to Pay" and have it go down, while being able to track the remaining balance on the credit card.

However, while there isn't a button to mark a bill as paid (which would be nice, simply move the due date up a month), editing the bill and moving it forward a month does the trick.

Just couldn't find any documentation on how matches work and so forth.
