### ISSUE TITLE
Fortnightly Transactions

### ISSUE THREAD

**Issue by MitchWoodin** [firefly-iii/firefly-iii#7684]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'd like to be able to add fortnightly automated transactions. I get paid every two weeks so having this option would be extremely beneficial for my use case. 

### Solution

Adding another option to the transaction frequency dropdown. You have every week and monthly but having the option for every two weeks, or even custom range, would be good.

### What are alternatives?

Manually add recurring transactions

**Comment by JC5** [comment]
Set "skip" to 1.

**Comment by MitchWoodin** [comment]
Ahh I see that works. Thanks!
