### ISSUE TITLE
Low contrast ratio on .skin-firefly-iii .btn-info color with dark theme

### ISSUE THREAD

**Issue by MateusBMP** [firefly-iii/firefly-iii#7686]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

If using `a` tag with classes `btn` and  `btn-info`, the dark theme apply the color `#5fa4cc`  with the background `#00c0ef`. See a example in `/admin/update-check` and `/profile` routes, respectively:

![image](https://github.com/firefly-iii/firefly-iii/assets/42280089/1b0509ce-f861-40ca-9f67-5808737869ab)

![image](https://github.com/firefly-iii/firefly-iii/assets/42280089/c082441d-4346-4ae1-a6b3-81ddd7f1bd89)

The contrast ratio is too slow, see the Adobe Color Contrast Analyzer:

![image](https://github.com/firefly-iii/firefly-iii/assets/42280089/d591e5e2-ad3a-418d-8c5a-da5f26928118)

### Solution

If we use the original color from Bootstrap, the color has to be `#ffffff`. See the same examples with changed colors:

![image](https://github.com/firefly-iii/firefly-iii/assets/42280089/b3f51ad6-bab0-45f1-b45a-fa0a7a198a96)

![image](https://github.com/firefly-iii/firefly-iii/assets/42280089/ddbbf6ac-0b77-4f71-9c10-539b356ef417)

To make this change we need to update the file `public/v1/lib/adminlte/css/skins/skin-dark.css` adding this code:

```css
.skin-firefly-iii .btn-info {
  color: #fff;
}
```

Consequently, we need to update the file `public/v1/lib/adminlte/css/skins/skin-dark.min.css`.

The contrast will then be **2.15:1**, a little better than the original:

![image](https://github.com/firefly-iii/firefly-iii/assets/42280089/3339230c-afb3-4121-a4db-bfa6dc3918bf)

### What are alternatives?

Other option is apply the contrast suggestion for Adobe Colors: the color `#3e3e3e`:

![image](https://github.com/firefly-iii/firefly-iii/assets/42280089/ade87f64-7dbd-4352-a5da-d6fa4895e373)

![image](https://github.com/firefly-iii/firefly-iii/assets/42280089/4b56c0c9-d602-4f74-865e-312fc5e88803)

The contrast is better, but the color does not follow the pattern of the theme. Personally, I like the `#ffffff` color. See the new contrast ratio:

![image](https://github.com/firefly-iii/firefly-iii/assets/42280089/aedaaa95-d123-40c5-8307-99666d8ab3cc)

**Comment by MateusBMP** [comment]
The routes `/admin/update-check` and `/profile` are only ones I found that use this CSS tag.

**Comment by JC5** [comment]
Nice, thanks for picking it up!
