### ISSUE TITLE
Dark Mode: form-control border does not highlight on focus

### ISSUE THREAD

**Issue by brhubbar** [firefly-iii/firefly-iii#7694]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When in light mode, selecting/focusing a field on the transaction creator will highlight the border blue. This is especially useful when navigating with a keyboard, rather than a mouse. In dark mode, this highlight behavior is blocked by `skin-dark-min.css` with `.skin-firefly-iii .form-control` and `.skin-firefly-iii .form-group .input-group-addon, .skin-firefly-iii .input-group .input-group-addon, .skin-firefly-iii .form-group input, .skin-firefly-iii .input-group input, .skin-firefly-iii .form-group textarea, .skin-firefly-iii .input-group textarea`

### Debug information

Debug information generated at 2023-06-27 19:32:07 America/Chicago for Firefly III version **6.0.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.16 |
| Firefly III API | 2.0.4 |
| Build | 506, 27-06-2023 13:09:05 UTC |
| Base Build | 10, 21-06-2023 21:55:03 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Chicago |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-06-01 00:00:00 |
| Session end | 2023-06-30 23:59:59 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0 |

### Expected behaviour

In dark mode, field borders should highlight to indicate that they are active, as is seen in light mode. I can get this behavior by disabling two `border` settings in the css with the F12 inspector.

Expected (done with the inspector):

![image](https://github.com/firefly-iii/firefly-iii/assets/55867501/1cb83a70-f99f-44d0-8383-53bf8a5278a8)

Actual:

![image](https://github.com/firefly-iii/firefly-iii/assets/55867501/16668fbe-4c9b-44bb-9dbe-bf933d4b6b4f)

### Steps to reproduce

1. Open Firefly III
2. Create a new withdrawal
3. Select any field
4. Note the lack of highlighting
5. To get the expected highlighting, open the inspector (F12 for Firefox)
6. Use the element picker to select the "Description" form-control
7. Find the top two `border:` settings and uncheck them to disable
![image](https://github.com/firefly-iii/firefly-iii/assets/55867501/0986d611-1c90-446a-a65d-5d484abbf38c)

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
Fixed!
