### ISSUE TITLE
Rules edit always set rule group to default instead keep rule group previously set

### ISSUE THREAD

**Issue by BoGnY** [firefly-iii/firefly-iii#7695]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Rules edit always set rule group to default instead keep rule group previously set.

Every time I make a rule edit I have to remember to set rule group to the previously one.

### Debug information

Debug information generated at 2023-06-28 17:48:57 Europe/Rome for Firefly III version **6.0.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.13 |
| Firefly III API | 2.0.4 |
| DB version | 19 (exp. 19) |
| Docker | No |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Rome |
| Browser TZ | Europe/Rome |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 2097152 (2 MB) |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-04-01 00:00:00 |
| Session end | 2023-06-30 23:59:59 |
| Session first | 2021-08-15 00:00:00 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

### Expected behaviour

Editing a rule keep rule group to the previously set.

### Steps to reproduce

1. Create rule and set a rule group
2. Try edit the rule
3. Rule group is set to default

**Comment by JC5** [comment]
Could you upgrade to the latest version and tell me if this still happens?

**Comment by BoGnY** [comment]
yes, tomorrow I will try

**Comment by BoGnY** [comment]
No more happens on v6.0.16 👍🏻
