### ISSUE TITLE
Refunds should add funds to budget

### ISSUE THREAD

**Issue by DastardlyDino** [firefly-iii/firefly-iii#7697]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When processing a refund I do not see a way to be able to add the money back into a budget. This should be a feature. If my budget is $100 and I buy a toy for $10 I now have $90 left in my budget. If I decide to return the toy I get my $10 back which means I am back to my starting $100. But according to FireflyIII my budget is still $90. Shouldn't I be able to add the $10 back into my budget?

### Solution

Add a budget option to Revenue/Incomes.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/faq/financials/

**Comment by DastardlyDino** [comment]
Why is this feature marked as not planned? A major part for me being able to do personal fiance has been finding a program that works like my brian thinks. As far as I can tell, Firefly III pretty much checks all those boxes except for this one feature. I've been stuck using Excel before this because of that. Could this be added to the feature roadmap as a lower priority? I would really love to have this feature added. The two options listed on the docs that you linked just feel a bit clunky.
