### ISSUE TITLE
Allow users to sort accounts by fields (f.e. name)

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#7699]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I have seen there were some feature requests in the past for this issue and they got closed last week, because a custom sort got implemented. For sure, this is a nice and really useful feature, but

* if you have a lot of accounts (and multiple pages)
* try to figure out if you have similar named accounts (possible duplicates)
* its quite hard as the pages are not sorted at all and a similar named account may appear on totally different pages

For my special use-case a quick-filter (to limit the amount of listed accounts to accounts containing the given string) may help a bit, but scrolling threw a sorted list is more effective.

### Solution

Have a way to get any accounts-list sorted by name or a way to filter the list.

**Comment by JC5** [comment]
I'm working on this in the new layout.
