### ISSUE TITLE
Editing a Bill - Repitition dropdown is daily, not configured value

### ISSUE THREAD

**Issue by Foxtrek64** [firefly-iii/firefly-iii#7701]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When opening a bill for editing, the "Repeats" dropdown shows "daily" even if a different value is configured. It appears that this field is not pulling its value from the database, causing it to fall back to "daily" as a default value.

### Debug information

Debug information generated at 2023-06-30 17:33:56 Europe/Amsterdam for Firefly III version **6.0.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.13 |
| Firefly III API | 2.0.4 |
| Build | 506, 11-06-2023 16:24:57 UTC |
| Base Build | 6, 10-06-2023 16:13:33 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | UTC |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-06-01 00:00:00 |
| Session end | 2023-06-30 23:59:59 |
| Session first | 2022-06-18 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0 |

### Expected behaviour

Field should show the currently configured value.

### Steps to reproduce

1. Create a new bill. Set the "Repeats" dropdown to monthly or yearly.
2. Save the bill.
3. Edit the newly-created bill. "Repeats" dropdown now shows "daily" rather than previously selected value.

### Additional info

This issue requires users to notice that the repetition setting was changed, otherwise it gets saved with the new "daily" value which can cause issues with various calculations.

**Comment by JC5** [comment]
Please use the search and upgrade to 6.0.16. Thanks!
