### ISSUE TITLE
Piggy Bank and Bills Expected x second ago dates show incorrect values

### ISSUE THREAD

**Issue by Solverz-0** [firefly-iii/firefly-iii#7704]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I will explain with an example:

It is 30th June 11:30pm, I depoist funds into Piggy Bank by clicking on the + button on the Piggy banks page and it shows deposit date as 1st July instead of 30th June.

It is 30th June 11:30pm, I look at a bill due on July 1st in the Paid this period column. If I change the month at the top of the page from June to July, the bill says Expected 1 second ago even though it is still 30th June.

### Debug information

Debug information generated at 2023-07-01 01:30:55 Europe/London for Firefly III version **6.0.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.16 |
| Firefly III API | 2.0.4 |
| Build | 506, 27-06-2023 13:09:05 UTC |
| Base Build | 10, 21-06-2023 21:55:03 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_GB |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 01:28:35 |
| Session end | 2023-07-31 01:28:35 |
| Session first | 2022-09-09 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0 |

### Expected behaviour

Piggy bank deposits to show June 30th.

Bills Paid this period column to not think it is July 1st when it is still June 30th.

### Additional info

I think it is related to this Bug Report: #7446

**Comment by JC5** [comment]
> It is 30th June 11:30pm, I depoist funds into Piggy Bank by clicking on the + button on the Piggy banks page and it shows deposit date as 1st July instead of 30th June.

I can't replicate this. I can't help but notice however that you opened this ticket at 1:36 CEST but your debug information says "2023-07-01 01:30:55 Europe/London". That should say "2023-07-01 00:30:55 Europe/London"

> It is 30th June 11:30pm, I look at a bill due on July 1st in the Paid this period column. If I change the month at the top of the page from June to July, the bill says Expected 1 second ago even though it is still 30th June.

That's a bug, and it should be fixed in the next release :+1:

**Comment by tonicospinelli** [comment]
@Solverz-0 a new version was released. Could you validate this scenario?
