### ISSUE TITLE
Available budget not updated after deleting active budget

### ISSUE THREAD

**Issue by JoClaes** [firefly-iii/firefly-iii#7706]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I deleted an active budget that had a specific amount assigned to it.

After deleting the budget, I noticed that the available budget displayed on the main page and in the progress bar did not update. However, the available amount shown in the bottom-right corner of the budget page was correct.

I attempted to resolve it by using the suggested "/flush" url mentioned in ticket #7478. Unfortunately, this did not resolve the problem.

I found that the amount in the "available_budgets" table still contained the old value. 
As a solution, I manually adjusted the amount in the table, flushed the cache, and it successfully updated the main page and progress bar. 

### Debug information

Debug information generated at 2023-07-01 09:13:18 UTC for Firefly III version **6.0.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.15 |
| Firefly III API | 2.0.4 |
| Build | 506, 22-06-2023 03:58:31 UTC |
| Base Build | 10, 21-06-2023 21:55:03 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-07-31 23:59:59 |
| Session first | 2006-12-31 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
Fixed in the next release.
