### ISSUE TITLE
Suggest a directory for the compose file in the documentation 

### ISSUE THREAD

**Issue by WaleedMortaja** [firefly-iii/firefly-iii#7708]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Please provide a suggested directory to save the docker compose file(s) into, because the name of the directory becomes part of the docker container name. The name might be used in scripts like [the script that is recommend in the backup page](https://github.com/firefly-iii/docs/blob/4c6043d8fbcaa2133a694d34daaa7252eac5fcf2/docs/docs/firefly-iii/advanced-installation/backup.md?plain=1#L57C27-L57C27).

Different docker container names makes confusion like [here](https://gist.github.com/dawid-czarnecki/8fa3420531f88b2b2631250854e23381?permalink_comment_id=4612999#gistcomment-4612999) and [here](https://gist.github.com/marvindv/b83dc0228b0208ada1e40a7b882e042b/revisions)

### Solution

Edit the docs. Provide an example path for the docker compose file(s) so that it is assumed to be the default and consistent path between different installations. I personally suggest: `~/docker/firefly-iii`

### What are alternatives?

Use the `container_name` key in the docker compose file ([reference](https://docs.docker.com/compose/compose-file/05-services/#container_name))

**Comment by JC5** [comment]
Nah I don't think so. I think people are smart enough to think about this themselves.

**Comment by WaleedMortaja** [comment]
I still think it would be a good idea to suggest a path, or use `container_name`. However, I respect your opinion too.

**Comment by JC5** [comment]
Not a bad idea, I missed that one. Check out the Docker file, what do you think?

**Comment by WaleedMortaja** [comment]
It works as expected. Container names should be consistent now.
Thanks.
