### ISSUE TITLE
Expense Amount cannot be setted as 0

### ISSUE THREAD

**Issue by TaoChan1005** [firefly-iii/firefly-iii#7709]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I cannot set the Amount as 0.
<img width="390" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/42793494/bc32fcbd-05da-495a-9eaf-ae5fc5cf46e9">

### Debug information

None

**Comment by JC5** [comment]
That's by design :)
