### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by vClouds** [firefly-iii/firefly-iii#771]
running php artisan migrate:refresh --seed for fresh install results in nothing several times before showing "Migration table not found" error

tried with mysql and pgsql configurations in env file

php 7.1
firefly 4.6.4
psql 9.6

I'm not sure if sqlite configurations still there somewhere!!!
Please advise
Please introduce web-based configuration wizard.

**Comment by JC5** [comment]
The error "migration table not found" should not be a problem: when it's not found it will be created.

Do you get an error in your console or in the files in `storage/logs`?

**Comment by vClouds** [comment]
![screenshot from 2017-08-21 23-33-00y](https://user-images.githubusercontent.com/24693741/29535571-5ade0c0c-86cb-11e7-9fa4-b24433584c87.png)
Well, getting closer!
After several confirmations "yes" migration done and login page is loading normally, but after logging credentials, another broke error displaying <No currency found with code "EUR">.

Changing the default currency manually in /firefly-iii/app/Support/Amount.php does not resolve the issue.

App is loading, registration and confirmation mail to user is done smoothly; so what's the problem? default currency can be specified later from admin/settings panel etc.
Please advise, what to do next?
[firefly-iii-2017-08-21.log.txt](https://github.com/firefly-iii/firefly-iii/files/1239960/firefly-iii-2017-08-21.log.txt)

**Comment by JC5** [comment]
The database didn't get its initial values for whatever reason. What database did you try this on?

**Comment by vClouds** [comment]
I configured env file with mysql for MariaDB 10.1.25
I prefer pgsql but the command `php artisan migrate:refresh --seed` does not move forward

**Comment by JC5** [comment]
I'll set up some VM's to try it. They should all work just fine. What's your OS?

**Comment by JC5** [comment]
pgsql 9.4.13 works just fine locally.

![screen shot 2017-08-22 at 20 55 10](https://user-images.githubusercontent.com/5889984/29582266-5078be36-877c-11e7-8b7d-5339becb3954.png)
 
I'll try 9.6 next, but I'm not expecting any trouble.

**Comment by vClouds** [comment]
Well, done already with psql 9.6 on ubuntu 14.04 and 16.04 and it is working like a charm

I can relate the reported issue with the behavior of the command `php artisan migrate:refresh --seed` which continues after migrating tables with the below shown tasks
`Seeding: AccountTypeSeeder
Seeding: TransactionCurrencySeeder
Seeding: TransactionTypeSeeder
Seeding: PermissionSeeder
`
I think it was somehow broken and left platform with the fatal error of `No currency found with code "EUR"`
@JC5 Special thanks for your support

**Comment by JC5** [comment]
You're welcome! Let me know if I can help with anything else.

**Comment by j360b** [comment]
I encoutered the same '<No currency found with code "EUR">.' issue with MariaDB 10.2.8 while executing the `php artisan migrate:refresh --seed`. I think this was caused because the fill query couldn't execute, my cmd screen was displaying error message `1071 Specified key was too long; max key length is 1000 bytes`. 

 However after setting the charset of the database to latin1 and executing the `php artisan migrate:refresh --seed` several times, it finally works.
