### ISSUE TITLE
Total of all budgets is not updated when I change toe amount of one row

### ISSUE THREAD

**Issue by dethegeek** [firefly-iii/firefly-iii#7716]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When updating the amount in a budget, the sum of all budgets is not updated. I reproduce on the demo website

### Debug information

Debug information generated at 2023-07-04 15:40:59 Europe/Amsterdam for Firefly III version **6.0.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.16 |
| Firefly III API | 2.0.4 |
| DB version | 19 (exp. 19) |
| Docker | No |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 2097152 (2 MB) |
| Interface | cli-server |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-07-31 23:59:59 |
| Session first | 2020-08-11 12:12:54 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

### Expected behaviour

The total of all budgets should be increased or decreased when a budget changes

### Steps to reproduce

* Go to the page https://demo.firefly-iii.org/budgets
* add at least 2 budgets with an amount
* refresh the page with F5 to have a goos starting point to reproduce
* Observe the sum of all budgets in the bottom of the list
* update the amount of any budget 
* see the total is still the same

Screenshots from demo. Look the value €1 200 at the bottom of the list,

![image](https://github.com/firefly-iii/firefly-iii/assets/5788361/e7cf4979-f3bd-4485-883a-8cead2b850f4)

I update the 1st budget : instead of €800, I set it to €1 200, then press enter. The row's total is updated, but not the sum of all budgets

![image](https://github.com/firefly-iii/firefly-iii/assets/5788361/fb5d0ebf-574e-41ed-99d0-2c701bc9aa12)

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
The row is duplicate now that available amount is also calculated automatically, so I've dropped it.
