### ISSUE TITLE
Suggestion: add Google Translator in Crowdin

### ISSUE THREAD

**Issue by jinformatique** [firefly-iii/firefly-iii#772]
Hi,
In addition to propose Microsoft translation automatically, would it be possible to also add Google translation? Because most of the time, I am doing coy/paste from Google translation who seems much more accurate.

I already went ahead an contacted Crowdin support to know how to proceed and they gave me this link:

In order to work with Google Translator, project manager or owner have to obtain Google Translate API Key. Here is the link with the detailed instructions:
https://support.crowdin.com/configuring-machine-translation-engines/#google-translate

Thank you

**Comment by JC5** [comment]
Which languages are you translating exactly?

**Comment by jinformatique** [comment]
I am translating in French.

**Comment by JC5** [comment]
I'm not sure why you're doing the French translation when you just copy paste from Google Translator. I could do that myself. 

I can see it happening for special accounting terms or something like that but other than that I really don't see the point.

**Comment by jinformatique** [comment]
No don't be misunderstood, I use google translator, to have an idea, an a review what it gives me. Sometimes it's correct, but otherwise I improve it. Especially for long phrases, it's easier than having to type everything.
It's just that I see Microsoft translator at the bottom, giving translations as well and it's easier to click on a proposed translations to review or correct it, than to rewrite everything.
Sure it's accounting terms and it's not that easy to translate and of course the translator doesn't do all the work.
Be reassured, I don't just use google translator and copy/paste as is. I always verify what it gives me and double check with other tools when I need synonyms.

**Comment by JC5** [comment]
Ok good! You scared me for a moment. I will see what I can do!

**Comment by JC5** [comment]
Code added, should be visible.

**Comment by jinformatique** [comment]
Oh woaw this quick, you are amazing! This really helps.
Thanks

**Comment by JC5** [comment]
:+1:
