### ISSUE TITLE
Docker-compose-importer contains and error and the link to it from the docs results in a 404.

### ISSUE THREAD

**Issue by jessy100** [firefly-iii/firefly-iii#7728]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

https://github.com/firefly-iii/docker/blob/main/docker-compose-importer.yml contains the restart directive a second time on line 44, breaking the docker-compose file. Also the docker-compose-importer referenced on [this docs page ](https://docs.firefly-iii.org/firefly-iii/installation/docker/) results in a 404. 

### Debug information

debug info not applicable.

**Comment by JC5** [comment]
Thx! Both are fixed now. The second one could take a moment because of CDN caches.
