### ISSUE TITLE
Transaction table in transaction detail view is not responsive

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#773]
The table is too wide for small screens.
I suggest dropping some information on small screens that's not that important.
* delta columns
* source account

https://firefly-iii.nder.be/transactions/show/634

**Comment by JC5** [comment]
Yeah it's messy. I'll see what I can do.

**Comment by JC5** [comment]
Some code is live on the demo site. Check it out :)

**Comment by simonsmiley** [comment]
Looks good

**Comment by JC5** [comment]
Closed to clear the list.
