### ISSUE TITLE
Transaction graph may show transactions out of date range

### ISSUE THREAD

**Issue by dethegeek** [firefly-iii/firefly-iii#7730]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi

I found that when I view transactions of an account, the balance graph may show wrong balance at the latest represented point. The date of this point is out of the date range defined in the URL and the page title.

I reproduced on the demo, after observing it on my instance.

### Debug information

Debug information generated at 2023-07-07 11:23:20 Europe/Amsterdam for Firefly III version **6.0.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.16 |
| Firefly III API | 2.0.4 |
| Build | 506, 27-06-2023 13:09:05 UTC |
| Base Build | 10, 21-06-2023 21:55:03 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-07-31 23:59:59 |
| Session first | 2020-07-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

### Expected behaviour

The graph shall stop at the date range end, including this date. Example : 2023-01-01 to 2023-01-31 shall not show transaction in date of 2023-02-01.

### Steps to reproduce

1. Create a new account
2. set a initial balance of $1000 on 2023-01-01
3. create a few withdrawals of $50 on 2023-01-01, 2023-01-05, 2023-01-10, 2023-01-31 and 2023-02-01. 
4. Show the account log for 2023, January
5. See  that the last transaction in the log is on 2023-01-31 and the graph shows the transaction on 2023-02-01.

![image](https://github.com/firefly-iii/firefly-iii/assets/5788361/6c13296e-0853-44ba-8121-75684b713a47)

![image](https://github.com/firefly-iii/firefly-iii/assets/5788361/ced45b76-fa85-4d02-9737-b51cd00d5326)

I also believe that the graph should show the initial balance of $1000 on 2023-01-01, but this may be a bit hacky to do because the transaction on 2023-01-01 occurs at midnight in  the database (2023-01-01 00:00:00.

**Comment by JC5** [comment]
This is on purpose, for clarity.
