### ISSUE TITLE
Can we create a secondary classification for income and expenses？

### ISSUE THREAD

**Issue by mucrys** [firefly-iii/firefly-iii#7734]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like the firefly III can create secondary classification for income and expenses.
like this:
Expenses:
 1st classification: Auto consumption:
      2nd classification           charging fee
                                             Washing fee
                                              Parking fee
    etc.
    
    

### Solution

Just above.

### What are alternatives?

None

### Additional context

None

**Comment by JC5** [comment]
You can set a budget, add a category, and as many tags as you like.

**Comment by mucrys** [comment]
Thanks, So how to set a budget.
I just want to create  some secondary categories

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/#sub-categories-sub-budgets-sub-accounts
