### ISSUE TITLE
transaction list in split transaction shows incorrect amount

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#774]
The amount shown in the table is actually all splits, not the amount of the one split.

https://firefly-iii.nder.be/transactions/show/634

**Comment by simonsmiley** [comment]
Looks like you fixed it

**Comment by JC5** [comment]
I've spotted a small bug I have yet to address but it's a very small use case. Almost done!

**Comment by JC5** [comment]
Closed to clear the list.
