### ISSUE TITLE
Form action is "http" and not "https" behind reverse proxy

### ISSUE THREAD

**Issue by ollioddi** [firefly-iii/firefly-iii#7740]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi there.

I am noticing that i am having issues logging in, due to the form action in the frontend using HTTPS instead of HTTPS, which i am connected with.

I found some other issues regarding this, but the solution did not work.

I am using latest version with Traefik 2.0 reverse proxy.

The x-forward-proto is set by Traefik to HTTPS.

Any other suggestions? I can manually change it with developer tools to perform login, but it's not really that great.

Tested in both Firefox and Chrome. Interestingly, the debug info cannot see that any headers are set?

Thanks in advance.

### Debug information

Debug information generated at 2023-07-10 23:10:19 Europe/Madrid for Firefly III version **6.0.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.16 |
| Firefly III API | 2.0.4 |
| Build | 506, 27-06-2023 13:09:05 UTC |
| Base Build | 10, 21-06-2023 21:55:03 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Madrid |
| Browser TZ | Europe/Copenhagen |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start |  |
| Session end |  |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0 |

### Steps to reproduce

1. Go to url
2. Perform login without success
3. Inspect the form element action and see that is HTTP

**Comment by JC5** [comment]
Set the reverse_proxy environment variable to `*`. This is discussed in the docs, and I had expected you to find it using the search.
