### ISSUE TITLE
Unable to reconcile on 6.0.16

### ISSUE THREAD

**Issue by deanpribetic** [firefly-iii/firefly-iii#7742]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Running a reconciliation on an Asset account. All works as expected until I hit the "Store Reconciliation" button…then nothing happens.

### Debug information

Debug information generated at 2023-07-11 08:58:20 Australia/Melbourne for Firefly III version **6.0.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.16 |
| Firefly III API | 2.0.4 |
| Build | 506, 27-06-2023 13:09:05 UTC |
| Base Build | 10, 21-06-2023 21:55:03 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Australia/Melbourne |
| Browser TZ | Australia/Melbourne |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | warning, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-07-31 23:59:59 |
| Session first | 2019-08-07 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0 |

### Expected behaviour

I would expect the pop-up for finalising the reconcilliation to appear and allow me to close it out.

### Steps to reproduce

1. Go to reconcile an account
2. Enter the start and end dates and amounts
3. Check the relevant account boxes until the amount in the Reconciliation Box is zero
4. Hit `Store Reconciliation`

**Comment by JC5** [comment]
It works on the demo site. What errors do you see in the browser console?

**Comment by deanpribetic** [comment]
> It works on the demo site. What errors do you see in the browser console?

I'm not seeing any errors on the browser console…which is odd. I did some digging and found that I can replicate the error.

The account I am reconciling sends a statement every 3 months and is my daily transaction account…so it's high volume.

I found that when I attempt to reconcile the account and have marked off 424 transactions it works ok, but when I hit 425 transactions or above it will fail.

**Comment by JC5** [comment]
Ah yes, that's a known issue. The URL is too long. Reconcile in smaller batches.

**Comment by deanpribetic** [comment]
Oh yeah – i reckon I've raised this exact issue before. My bad!

**Comment by rayment** [comment]
> Ah yes, that's a known issue. The URL is too long. Reconcile in smaller batches.

Thank you, this solved my problem also. Would it be possible to introduce an alert that states this? Until I found this issue I was confused for a good half hour.
