### ISSUE TITLE
Add global description of split transactions as a prefix in destination accounts

### ISSUE THREAD

**Issue by GatoMiopia** [firefly-iii/firefly-iii#7749]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I use firefly to manage my home and personal finances.
I have a liability account for my GF, so when I pay for groceries I do a split transaction with my part to a Groceries expense account and her part for her liability account, and when she pays me back I do a transaction from the liability to my bank account.

The problem is, in the source's account page, the split transaction shows the global description + the splits description, but on the destination's account page, it just shows the split description. 

This makes it confusing as I use our names on the individual and "Groceries" in the global description.

### Solution

To add the global description either as it shows on the source's account page, as a split inside a transaction or as a prefix, as it's shown in the homepage under the account's section

**Comment by JC5** [comment]
Good point, I'll see what I can do :+1:

**Comment by JC5** [comment]
Fixed, part of the next release!
