### ISSUE TITLE
SOLVED: Decimal don't work

### ISSUE THREAD

**Issue by whoopsie** [firefly-iii/firefly-iii#775]
When is want to fill in E18.78 and save it it will be E1878.
If i want to change the amount of money that at views te correct value.

![screenshot from 2017-08-23 21 55 05](https://user-images.githubusercontent.com/9220578/29635672-f34a5db4-884d-11e7-9f23-7e8fc968fff3.png)

**Comment by whoopsie** [comment]
I already fixed it. Running it on Arch Linux and i didn't setup de locales right. In English it works just fine in dutch it won't. So found my problem and my solution.

**Comment by JC5** [comment]
Good to hear you fixed it!
