### ISSUE TITLE
"LEFT TO SPENT" is not correct when comparing to budget.

### ISSUE THREAD

**Issue by iszhi** [firefly-iii/firefly-iii#7752]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In the dashboard, there is a panel called "LEFT TO SPENT", 
![image](https://github.com/firefly-iii/firefly-iii/assets/33443222/a2dfec7a-c0bd-43a9-a0b3-ddd80854ab77)

I think that this should be the reflect from the budget. However, this is not. Can you explain the thery there?

![image](https://github.com/firefly-iii/firefly-iii/assets/33443222/8638d0d0-5d77-4b54-baa1-c20913c7a4a0)

### Debug information

See above.

**Comment by JC5** [comment]
Not sure. What happens when you browse to /flush?

**Comment by iszhi** [comment]
I didn't understand your question. Can you guide me more detail?

**Comment by JC5** [comment]
What happens when you browse to your-site.com/flush ?

**Comment by iszhi** [comment]
Then it become 
![image](https://github.com/firefly-iii/firefly-iii/assets/33443222/17e3d0f7-99e4-4207-88af-25dbcf0a92b2)
 I still didn't get it what does this value represent.

**Comment by JC5** [comment]
It represents the amount of money you have left according to the bars on the /budgets page.

**Comment by iszhi** [comment]
I think so too. But why I didn't get 538.01 from my budgets page? bug? or what?

**Comment by JC5** [comment]
I'm not sure. The "amount available" should also be 870. What happens when you change one of the amounts to (for example 371) and back to 370?

**Comment by iszhi** [comment]
It's 
![image](https://github.com/firefly-iii/firefly-iii/assets/33443222/b0ea8e19-03cf-4453-97a2-8fd41ffd1c13)
 and 
![image](https://github.com/firefly-iii/firefly-iii/assets/33443222/ae42e257-050a-4802-ac6e-5a35f3488433)

version: 6.0.10

**Comment by JC5** [comment]
Aha. Please upgrade to the latest version.

**Comment by iszhi** [comment]
After upgrade to 6.0.16 (latest), it's still the same. 
![image](https://github.com/firefly-iii/firefly-iii/assets/33443222/943e0ba9-e08a-429c-b54e-3cb3c07bd73f)
![image](https://github.com/firefly-iii/firefly-iii/assets/33443222/8cc20152-2a44-43a2-a96b-bd825efb7573)
Do you have any more solutions?

**Comment by JC5** [comment]
Did you try editing one budget and back again?

**Comment by iszhi** [comment]
Yes. As you suggested, I edit the 370 to 371. What I'm looking for is the "OVERSPENT" should not be 563.69, but "LEFT to SPENT" 279.21.

**Comment by JC5** [comment]
Yes I'm aware, but I still see that "available" and "budgeted" are different and those two should meet up after such a change. So change it back please, and tell me if these two amounts are equal.

**Comment by iszhi** [comment]
After changes back to 370, the two looks like this: 
![image](https://github.com/firefly-iii/firefly-iii/assets/33443222/9aa55893-f534-4065-8922-121568a678cc)
![image](https://github.com/firefly-iii/firefly-iii/assets/33443222/7c62bfc0-a93c-42ed-ba9f-34d4219357d0)

**Comment by JC5** [comment]
Sorry, I can't replicate this. I have the same setup but when I change 370 to 371 and back, both amounts change.

**Comment by iszhi** [comment]
I see. Leave me alone.

**Comment by JC5** [comment]
OK.
