### ISSUE TITLE
Add "Any Tag contains" trigger

### ISSUE THREAD

**Issue by watertrainer** [firefly-iii/firefly-iii#7754]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Add a trigger to the ruls, which would trigger, if any tag contains a certain string. This feature already exists for notes, why not for tags? I, specifically, would like this feature to be able to distingush imported transactions from manually created ones in the ruls, without having to add a custom tag/while still being able to have a different tag for every import.

### Solution

Adding a new trigger, which would trigger whenever any tag contains the provided string.

### What are alternatives?

Adding a trigger for "imported" would also provide the same functionality, although I would argue my feature is more general and not only usable for one specific circumstance.

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/7571
