### ISSUE TITLE
Paypal automatic withdrawal

### ISSUE THREAD

**Issue by cyberax17** [firefly-iii/firefly-iii#776]
Hi, 
I have a Paypal account which automatically takes the money spent from one of my other bank accounts after a few days. Is there any way to replicate this with FF without entering every of the two transactions manually?
Thanks & Cheers!

**Comment by JC5** [comment]
Unfortunately, no. Firefly III does not support the automated creation of transactions. In the future an import-routine may be created to automatically download transactions from Paypal, but there's no ETA on that yet.
