### ISSUE TITLE
Sum of split transactions in search 

### ISSUE THREAD

**Issue by zarko-a** [firefly-iii/firefly-iii#7760]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I was trying out split transactions and it doesn't seem that sum of split transactions can be found with `amount_exactly:N` search filter. 

I'm guessing this is because sum is not stored in the DB but it's rather calculated. 

Is there a way to search for the sum right now that I'm missing?
 If not would you consider adding support for this in the future?

### Solution

Being able to quickly find the "parent" transaction based on the amount that corresponds to bank or credit card statement. 

E.g. bank statement amount is X. It's stored in Firefly III as a split of Y and Z. If one wants to quickly find if the transaction was entered/imported by looking at the amount you need to remember how it was split in the first place. 

Either having a unique search filter that would include sum of split transactions or just having that as default behavior would useful for this scenario. 

Not sure how many people use amounts to search for transactions, but I do it pretty frequently.

### What are alternatives?

Pretty sure I couldn't find a way to accomplish this right now .

**Comment by JC5** [comment]
Indeed, the amount is calculated so it's not readily available. I'll see what I can do. It's on the list!

**Comment by zarko-a** [comment]
Thank you, and thank you for making Firefly III.

**Comment by JC5** [comment]
I'm going to merge this with https://github.com/firefly-iii/firefly-iii/issues/6323
