### ISSUE TITLE
500 error during OAuth2 attempt from Importer to Firefly (FireflyIII\\Support\\Preferences::getForUser(): Argument #1 ($user) must be of type FireflyIII\\User, null given)

### ISSUE THREAD

**Issue by lowercasename** [firefly-iii/firefly-iii#7762]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After authorizing the OAuth2 connection from the data importer at `https://firefly-importer.domain.com` to `https://firefly.domain.com`, I see the following error displayed in the browser with the URL `https://firefly-importer.domain.com/callback?...`:

> Error :(
> The server you tried to connect to responsed with an error.
> Server error: `POST http://firefly.domain.com/oauth/token` resulted in a `500 Internal Server Error` response: <!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta name="robots" content="noindex, nofollow, n (truncated...)

And the following error in the Docker logs for `firefly_iii_core`:

```
172.22.0.11 - - [19/Jul/2023:12:23:43 +0100] "GET /oauth/authorize?client_id=14&redirect_uri=http%3A%2F%2Ffirefly-importer.domain.com%2Fcallback&response_type=code&scope=&state=MY2ceMZ4mtbjEwkkAf0E8U7QX7VwcMqLt4YUcrmR&code_challenge=fcLONpmCN8rwtZxKblm1bGiQvU3PwLayA3V85uruhBs&code_challenge_method=S256 HTTP/1.1" 302 3356 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0"
[2023-07-19 12:23:44] local.ERROR: Exception is: {"class":"TypeError","errorMessage":"FireflyIII\\Support\\Preferences::getForUser(): Argument #1 ($user) must be of type FireflyIII\\User, null given, called in \/var\/www\/html\/app\/Notifications\/User\/NewAccessToken.php on line 97","time":"Wed, 19 Jul 2023 12:23:44 +0100","file":"\/var\/www\/html\/app\/Support\/Preferences.php","line":83,"code":0,"version":"6.0.18","url":"https:\/\/firefly.domain.com\/oauth\/token","userAgent":"GuzzleHttp\/7","json":true,"method":"POST"}
[2023-07-19 12:23:44] local.ERROR: FireflyIII\Support\Preferences::getForUser(): Argument #1 ($user) must be of type FireflyIII\User, null given, called in /var/www/html/app/Notifications/User/NewAccessToken.php on line 97 {"exception":"[object] (TypeError(code: 0): FireflyIII\\Support\\Preferences::getForUser(): Argument #1 ($user) must be of type FireflyIII\\User, null given, called in /var/www/html/app/Notifications/User/NewAccessToken.php on line 97 at /var/www/html/app/Support/Preferences.php:83)
[stacktrace]
#0 /var/www/html/app/Notifications/User/NewAccessToken.php(97): FireflyIII\\Support\\Preferences->getForUser()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(97): FireflyIII\\Notifications\\User\\NewAccessToken->via()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\\Notifications\\ChannelManager->send()
#5 /var/www/html/app/Handlers/Events/APIEventHandler.php(53): Illuminate\\Support\\Facades\\Facade::__callStatic()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): FireflyIII\\Handlers\\Events\\APIEventHandler->accessTokenCreated()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#8 /var/www/html/vendor/laravel/passport/src/Bridge/AccessTokenRepository.php(69): Illuminate\\Events\\Dispatcher->dispatch()
#9 /var/www/html/vendor/league/oauth2-server/src/Grant/AbstractGrant.php(464): Laravel\\Passport\\Bridge\\AccessTokenRepository->persistNewAccessToken()
#10 /var/www/html/vendor/league/oauth2-server/src/Grant/AuthCodeGrant.php(145): League\\OAuth2\\Server\\Grant\\AbstractGrant->issueAccessToken()
#11 /var/www/html/vendor/league/oauth2-server/src/AuthorizationServer.php(201): League\\OAuth2\\Server\\Grant\\AuthCodeGrant->respondToAccessTokenRequest()
#12 /var/www/html/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(52): League\\OAuth2\\Server\\AuthorizationServer->respondToAccessTokenRequest()
#13 /var/www/html/vendor/laravel/passport/src/Http/Controllers/HandlesOAuthErrors.php(24): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->Laravel\\Passport\\Http\\Controllers\\{closure}()
#14 /var/www/html/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(50): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->withErrorHandling()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->issueToken()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(159): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(90): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#30 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#44 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /var/www/html/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"}
172.22.0.11 - - [19/Jul/2023:12:23:43 +0100] "POST /oauth/token HTTP/1.1" 500 4883 "-" "GuzzleHttp/7"
```

The authorized application does appear to end up in the list of clients in Firefly, but the importer does not think it's connected (I guess because the flow was cut short):

<img width="954" alt="Screenshot 2023-07-19 at 12 31 57" src="https://github.com/firefly-iii/firefly-iii/assets/1748384/fd45594d-edbe-4dfc-acd4-c2741a2fc8fc">

### Debug information

Debug information generated at 2023-07-19 12:31:07 Europe/London for Firefly III version **6.0.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.18 |
| Firefly III API | 2.0.4 |
| Build | 537, 18-07-2023 05:11:37 UTC |
| Base Build | 12, 15-07-2023 18:56:37 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-07-31 23:59:59 |
| Session first | 2023-07-19 11:17:57 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0 |

### Expected behaviour

I expect for the OAuth2 flow to complete successfully and for my browser to be redirected back to the Importer.

**Comment by JC5** [comment]
Thanks for letting me know. I'm aware of this issue, it's fixed in `develop` and will be part of 6.0.19. If nothing else comes up, it should be released over the weekend.

**Comment by lowercasename** [comment]
Thank you!

**Comment by Jarige** [comment]
Thanks for fixing this! I can't see how long ago you've written your message about "should be released over the weekend" and whether you were referring to the past weekend or the next weekend. It only says "Commented last week".

I recently installed Firefly so unfortunately this issue is blocking me from using the importer to make an initial import of all my transactions. Is there any known workaround or do I need to wait until the fix is released? Without my transactions, well, not much can be done with Firefly without them, so I'll have to simply wait xD

So any estimate on when it'll be released?

**Comment by JC5** [comment]
As a rule, I try not to give estimates, precisely because of replies like these. My apologies. The release will be there when it's there.

**Comment by Jarige** [comment]
No need to apologize! I understand, I'll be patient. Was just trying to communicate that for new users, it's a blocking issue.

**Comment by josh817** [comment]
I would echo the issue OP is having. Just got to authenticating Data Importer and received roughly the same...
In browser:
_"Error :(
The server you tried to connect to responsed with an error.

Server error: `POST http://192.168.0.107:8003/oauth/token` resulted in a `500 Internal Server Error` response: <!DOCTYPE html> <html lang="en" class="auto"> <!-- TypeError: FireflyIII\Support\Preferences::getForUser(): Argument #1 (truncated...)"_

In the FireflyIII Core log:
"
[2023-07-28 05:53:34] local.ERROR: FireflyIII\Support\Preferences::getForUser(): Argument #1 ($user) must be of type FireflyIII\User, null given, called in /var/www/html/app/Notifications/User/NewAccessToken.php on line 97 {"exception":"[object] (TypeError(code: 0): FireflyIII\\Support\\Preferences::getForUser(): Argument #1 ($user) must be of type FireflyIII\\User, null given, called in /var/www/html/app/Notifications/User/NewAccessToken.php on line 97 at /var/www/html/app/Support/Preferences.php:83)

...

[2023-07-28 05:53:34] local.DEBUG: Now in Handler::render()  
[2023-07-28 05:53:34] local.DEBUG: Error "TypeError" has no Firefly III treatment, parent will handle.  
172.21.0.1 - - [28/Jul/2023:05:53:33 -0500] "POST /oauth/token HTTP/1.1" 500 1099500 "-" "GuzzleHttp/7"
"
Hopefully 6.0.19 fixes things for me too. Looking forward, thank you.
