### ISSUE TITLE
Autosuggestion for category/tags sometimes is case sensitive

### ISSUE THREAD

**Issue by Dinth** [firefly-iii/firefly-iii#7769]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

All my tags and category names are starting with an upper case letter for aesthetics, but unfortunately, often it breaks the autosuggestion feature when filling in category/tag name - i'm not getting auto-suggestions when im trying to type the the category/tag name starting with a lower case character.
It does happen most of the time, but not always - that's why I'm filling this as a bug report not feature request. 

### Debug information

Debug information generated at 2023-07-22 09:44:16 Europe/London for Firefly III version **6.0.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.18 |
| Firefly III API | 2.0.4 |
| Build | 537, 18-07-2023 05:11:37 UTC |
| Base Build | 12, 15-07-2023 18:56:37 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | DEFAULT_LANGUAGE=en_GB |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-07-31 23:59:59 |
| Session first | 2021-07-08 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0 |

### Expected behaviour

When starting to type the tag/category name with a lowercase, it should suggest a matching tag/category regardless of it starting with a lower case or upper case letter. 

### Steps to reproduce

1. Create a category "Bills"
2. Open an existing transaction in edit mode to add the category OR start creating a new rule adding the transaction to a category
3. In the category field start typing "bil" 
4. No autosuggestion

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/faq/other/#auto-complete-is-case-sensitive
