### ISSUE TITLE
Mention that "Amount is less/more than..." triggers also matches the exact amount

### ISSUE THREAD

**Issue by ryester19** [firefly-iii/firefly-iii#7771]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

A moment of brief confusion had me finding out that the "Amount is less/more than..." rule triggers acts more like a "less/more than or equals to" comparison. The names of those triggers should reflect how they actually behave.

### Solution

Rename the "Amount is less/more than..." triggers to "Amount is less/more than or equals to...", or something comparable

**Comment by JC5** [comment]
Will do, nice find! :+1:
