### ISSUE TITLE
Add wrapper script to Docker image for working with Artisan

### ISSUE THREAD

**Issue by ryester19** [firefly-iii/firefly-iii#7781]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Considering the importance of running Artisan commands under the www-data user in order to minimize permission issues, I think it would be beneficial to create a wrapper script that users can run in order to handle this automatically

### Solution

Add an executable script in /usr/local/bin, such as:
```
#!/bin/sh

su www-data -s /bin/sh -c "/var/www/html/artisan $*"
```

**Comment by JC5** [comment]
That's a great idea. It still feels kind of like a hack. If you have any resources to run a container under any user, preferably the local one, id me much obliged.

**Comment by ryester19** [comment]
> That's a great idea. It still feels kind of like a hack. If you have any resources to run a container under any user, preferably the local one, id me much obliged.

I wouldn't necessarily call a wrapper script a hack considering how widely used they are. I've seen the Linuxserver.io people use them before. On top of minimizing user error, it will also make running cli commands shorter.

Unless I'm misunderstanding you, the startup of the container needs root in order to complete some operations. For example, when you run the container as the www-data user (UID=33)
```
firefly-iii[540056]: In Filesystem.php line 862:
firefly-iii[540056]:
firefly-iii[540056]:   file_put_contents(/var/www/html/vendor/composer/autoload_psr4.php): Failed
firefly-iii[540056]:   to open stream: Permission denied
......
firefly-iii[540056]: chown: changing ownership of '/var/www/html/storage/build/.gitignore': Operation not permitted
firefly-iii[540056]: chown: changing ownership of '/var/www/html/storage/build/ebcdic.txt': Operation not permitted
firefly-iii[540056]: chown: changing ownership of '/var/www/html/storage/build/test-upload.csv': Operation not permitted
firefly-iii[540056]: chown: changing ownership of '/var/www/html/storage/build': Operation not permitted
firefly-iii[540056]: chown: changing ownership of '/var/www/html/storage/database/.gitignore': Operation not permitted
firefly-iii[540056]: chown: changing ownership of '/var/www/html/storage/database': Operation not permitted
firefly-iii[540056]: chown: changing ownership of '/var/www/html/storage/debugbar/.gitignore': Operation not permitted
firefly-iii[540056]: chown: changing ownership of '/var/www/html/storage/debugbar': Operation not permitted
```

**Comment by JC5** [comment]
> I wouldn't necessarily call a wrapper script a hack considering how widely used they are. I've seen the Linuxserver.io people use them before.

That doesn't make it any less of a hack. 

I'll Google around.
