### ISSUE TITLE
FEATURE: State, Address, City, CAP on Accounts

### ISSUE THREAD

**Issue by silenx** [firefly-iii/firefly-iii#779]
Hi,
i think is nice to have a form with state, city, cap, and address in the Asset, Expense and Revenue Account.

Regards

**Comment by JC5** [comment]
That's not a bad idea but purely cosmetic. What would be the point?

**Comment by silenx** [comment]
Example: Imagine that you travel a lot and you eat in mac donald, when you insert the expense you can fill City/State/etc or different view.
Yes, probably is more cosmetic, but you will have a super detailed item for every asset.

**Comment by JC5** [comment]
It's not the level of detail I'm going for. Who needs that to manage their finances? I see the entertainment value of course but I'm not going to build it.

**Comment by silenx** [comment]
Ok, no problem

**Comment by simonsmiley** [comment]
@silenx you could do something similar with the current version. Just enable "notes" for transactions and use this field.

@JC5 If you wanted to implement something like this, I would suggest one column for transactions, so you can enter a string as a location...

**Comment by silenx** [comment]
yes, i'm currently use notes for that.
