### ISSUE TITLE
Rule with multiple Any tag as trigger and strict mode on does not match any transaction

### ISSUE THREAD

**Issue by Bjornjansen12** [firefly-iii/firefly-iii#7792]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I using tags a lot to gain insight variable & fixed costs and essential & not-essential costs. Each transactions have 2 tags: variable or fixed costs and essential or not-essential.

There are 4 tag combinations possible:
fixed & essential costs = mortgage or insurange
fixed & not-essential costs = subscription for music streaming service
Variable & essential costs = barber
Variable & not-essential costs = Drinks with friends or take away.

Because it is not possible to group transactions on 2 different tags in the tag report, i'd like create another tag with another rules based on these tags as a workaround.

So I created a rule at least that need to add the tag "variable & not-essential costs" and has 2 different triggers:
Any tag is = variable
Any tag is = Not-essential

Actions: 
Add tag = variable & not-essential costs

In mandatory fields:
active = true
strict mode = true

I have multiple transactions which comply with these conditions but when looking for matching transactions, no transactions found. 

When set strict mode = false, then I've found transactions matching the conditions.

### Debug information

I'm running firefly iii (6.0.18) on Home Assistant (2023.7.3) and cannot find how I can enable debug mode. 
Found APP_DEBUG=true and APP_LOG_LEVEL=debug in documentation and paste it in the configuration page of the app but doesn't create a log. Sorry about that. 

### Expected behaviour

When:
In mandatory fields:
active = true
strict mode = true

2 different triggers are:
Any tag is = variable
Any tag is = Not-essential

Actions: 
Add tag = variable & not-essential costs

Then
Add tag "variable & not-essential costs" on all the transactions matching tags "variable" and "Not-essential".

### Steps to reproduce

1. Add tag "variable" and "Not-essential" to multiple transactions.
2. Create a tag "variable & not-essential costs".
3. create a rule which match de following conditions. 

In mandatory fields:
active = true
strict mode = true

2 different triggers are:
Any tag is = variable
Any tag is = Not-essential

Actions: 
Add tag = variable & not-essential costs

4. the run the new rule.

### Additional info

I've created an example in the demo database. 

Transaction: 
Drinks with friends
https://demo.firefly-iii.org/transactions/show/381

Rule
https://demo.firefly-iii.org/rules/edit/5

**Comment by JC5** [comment]
Thanks for letting me know. I fear the demo site will reset before I can look at it but I'll try to replicate and triage this over the weekend.

**Comment by JC5** [comment]
Should be fixed in the next release. The demo site should already do this correctly. Thanks for reporting!

**Comment by Bjornjansen12** [comment]
@JC5 thanks for your quick response and adjustment. I've tested in the demo environment and works perfectly. Looking forward to the next releases. Keep up the good work. Many thanks! Greetz.
