### ISSUE TITLE
Transaction list is not currency aware

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#780]
Firefly 4.6.3.1
I've spent in august money in 3 different currencies, but the summary includes only my main currency and it seems to use some kind of currency conversion as the number of transations is correct:
![tr](https://user-images.githubusercontent.com/4746858/29752037-bce50880-8b56-11e7-92a6-75f06c8afb7d.png)
I think list should include summary of all different currencies transactions:
![obraz](https://user-images.githubusercontent.com/4746858/29752059-1e24fc7c-8b57-11e7-9d80-3398cce435ee.png)

**Comment by JC5** [comment]
That's a good idea, I'll see what I can do!

**Comment by skibbipl** [comment]
Perhaps also there should be some indicator of number of transaction per currency.

**Comment by JC5** [comment]
In the alt-text I think, otherwise it would get very crowded.

**Comment by skibbipl** [comment]
Yeah, alt-text is good enough.

**Comment by JC5** [comment]
Currently visible on the demo site, but you'll have to make some transactions to see the full effect.

**Comment by skibbipl** [comment]
Looks great! 👍
