### ISSUE TITLE
Month-to-month report comparison

### ISSUE THREAD

**Issue by jelicicm** [firefly-iii/firefly-iii#7807]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

- It would be nice to be able to compare expenses on a screen that presents month-to-month expenses side by side. Basically, if I have categories to sort my expenses (e.g. Bank Loan, Health, Transportation, Food...), I'm able to generate a `Category Report` and see which part of my total sum of expenses for that month went to which of these categories. 
Now, to further learn about my spending habits, it would be great if I could compare two months side by side and see that I've, for example: spent $123 less on Food compared to last month, but I've spent $1200 more on taxi rides.
- This feature could be added to Reports page

### Solution

I believe functionality is detailed enough in the text box above.

### What are alternatives?

- I'm able to extract this information by generating Category Reports on monthly basis in separate browser tabs and comparing them "manually", but it would be a nice Quality of Life improvement to have it built in.
- Also, I can see such comparisons when visiting `/categories/show/XYZ`, but then there is a need to iterate through every category to see all trends, there is no single screen presentation.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6199
