### ISSUE TITLE
Currency symbol always is prefixed

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#781]
Not all currencies use prefixed currency symbols. Firefly always prefixes currency symbol.

**Comment by JC5** [comment]
Depends on the locale, not the currency.

**Comment by skibbipl** [comment]
Well, I use PL locale, and still currency symbol is prefixed. It should be suffixed. Also in multi currency mode some currencies will be prefixed and some suffixed. It should not be dependent on locale.

**Comment by JC5** [comment]
FF doesn't have the PL locale. Which language do you use? That's the locale FF uses.

As for currency display, it will remain dependent on the locale, not the currency.

**Comment by skibbipl** [comment]
Aaah OK, I use English language so it explains the behaviour. Anyway in multi currency mode I don't think this is a correct way of handling currency signs. If you would not like to keep this a an enhancement ticket than please close it.

**Comment by JC5** [comment]
You could start a Polish translation. That would include the Polish locale :wink:

**Comment by skibbipl** [comment]
In fact I did ;) It's not full, but most day to day strings are already translated. But this will not solve the issue.
