### ISSUE TITLE
Weird amount due in Liabilities list

### ISSUE THREAD

**Issue by stuzer05** [firefly-iii/firefly-iii#7810]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have a liability account where I loan money to a person. I transfer from my asset account to liability account thus managing my finances. The initial dept in liability account was 0.

These are all transactions. "John" is a debtor. He has 2 account in different currencies.
![image](https://github.com/firefly-iii/firefly-iii/assets/23124682/83ffbb13-b9ab-4de8-9f9a-8d78944f6525)

As the arrow shows, dept is currently 0, which is true. However, if  go to liabilities list, I see $400 in amount due. What is the reason for that?
![image](https://github.com/firefly-iii/firefly-iii/assets/23124682/5faec1f8-1100-4362-9ce9-6f755d0da45c)

Same problem with his another account.

### Debug information

Debug information generated at 2023-08-01 18:27:42 UTC for Firefly III version **6.0.19**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.19 |
| Firefly III API | 2.0.4 |
| Build | 553, 28-07-2023 14:22:29 UTC |
| Base Build | 13, 26-07-2023 07:34:31 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Uzhgorod |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2021-10-23 18:09:34 |
| Session end | 2023-08-01 18:09:34 |
| Session first | 2021-10-23 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0 |

### Expected behaviour

Amount due in the list should be 0 as in detailed review on top of the graph.

**Comment by JC5** [comment]
> However, if go to liabilities list, I see $400 in amount due. What is the reason for that?

I have no clue. I can't tell from the data you're showing me. Are you using multi-currency transactions, or are the transactions exclusively in one currency?

**Comment by JC5** [comment]
Nice find, it's a bug. I've fixed it for the next release :+1:

**Comment by stuzer05** [comment]
> Nice find, it's a bug. I've fixed it for the next release +1

Awesome! Thank you for your work!
