### ISSUE TITLE
highlight selected item for more clear view

### ISSUE THREAD

**Issue by alim0x** [firefly-iii/firefly-iii#7811]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

for now, firefly-iii have list view with selected items like this:

![selected current](https://github.com/firefly-iii/firefly-iii/assets/4954007/afb8711d-de20-4069-b9ed-9118c1c127fd)

and for reconciliation view, it's a bit clear than things above with dark and light lines:

![reconciliation](https://github.com/firefly-iii/firefly-iii/assets/4954007/fdc66460-bb26-4881-a572-c4d294d367a9)

but it's still not so clear to showing all items I have selected, especially when I want to selected some payment to check amount or so.

### Solution

draft to solve this problem:

![selected request](https://github.com/firefly-iii/firefly-iii/assets/4954007/78261ed1-5f90-40e0-8e93-2c7390457f67)

highlight selected lines will be more clear for user.

(and it will be perfect that showing total amount of items selected above list view, but only highlight selected lines will be helpful enough for now😊.)

**Comment by JC5** [comment]
What you see is what you get I'm afraid, but this is on the list for the new layout.
