### ISSUE TITLE
Add groups to recurring transactions

### ISSUE THREAD

**Issue by JonnyBnator** [firefly-iii/firefly-iii#7812]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to have the option of creating groups for recurring transactions.
They would function just like groups in bills or rules.

This would only be visible in the UI to increase readability, since with a growing list of recurring transactions, it get's messy.

### Solution

Increase readability by being able to group recurring transactions.

The same groups used in the bills section could be used, which would prevent creating a new db table etc.

### Additional context

Starting to use this tool I have already added 30 and some recurring transactions, and it already gets tedious looking through them. So I think implementing this feature would be rather straight forward but make the UI of the recurring transactions alot better.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5753
