### ISSUE TITLE
Possible sign error in Liabilities/Confusing value displayed

### ISSUE THREAD

**Issue by brhubbar** [firefly-iii/firefly-iii#7817]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I expect this is related to #7810, but I'm not confident, so opening a new issue. Feel free to close if I should post there instead.

When interacting with a debt liability, the sum represented above the "Chart of all transactions" for the liability adds payments against the debt to the initial value of the debt. 

For example, a $1000 debt with a $150 payment against it will show (in the /liabilities view) a correct $850 balance. In the account view (/accounts/show/###), the sum reads $1150.

![image](https://github.com/firefly-iii/firefly-iii/assets/55867501/3705073c-3e22-4ce3-acb4-65b936af4a7d)

![image](https://github.com/firefly-iii/firefly-iii/assets/55867501/5ca66fc1-2106-4ecd-a9e9-c8a0f9aa9fe2)

### Debug information

I tested this on the demo site, but here's my own install:

Debug information generated at 2023-08-04 07:54:02 America/Chicago for Firefly III version **6.0.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.18 |
| Firefly III API | 2.0.4 |
| Build | 537, 18-07-2023 05:11:37 UTC |
| Base Build | 12, 15-07-2023 18:56:37 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Chicago |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 07:43:35 |
| Session end | 2023-07-31 07:43:35 |
| Session first | 2022-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0 |

### Expected behaviour

I would expect the sum at the top of the chart to read one of the following:

- The balance of the debt at the end of the period shown, which I believe would be consistent with what other accounts display ($850 in the example above)
- The total amount that has been paid against the loan, which might be more useful considering that interest is not computed for loans, so the 'balance' may not be accurate ($150 in the example above)
- The total amount that has been paid against the loan in the period shown, which I feel is most intuitive in the context of that chart's title

### Steps to reproduce

1. [Go to the liabilities page](https://demo.firefly-iii.org/accounts/liabilities)
2. Create a new liability
    - Name it `Issue 7816`
    - Give it a balance of $1000
    - Set the start date to 08/01/2023
3. Create a new withdrawal
    - Withdraw $150 from `Checking` to `Issue 7816`
4. Observe the liabilities page and the account's view

### Additional info

I've noticed that this value matches what shows in the "Balance Difference" column on the liabilities page. I haven't been able to find anything in the docs explaining what that column means (I'll admit I haven't looked super hard). I accept the possibility that I'm just not understanding what that value is supposed to mean; it does not seem to correspond with the "Balance Difference" on asset accounts, which by my quick assessment represents the change in balance over the course of the period.

As a rambling aside, in that title of the "Chart of transactions... (####)" - a tooltip explaining which value (e.g. Balance vs. Balance Difference) is represented in (####) might be helpful. As I mentioned above, the title seems to suggest Balance Difference will be displayed, but Balance is actually shown (or add another spot so both are displayed).

**Comment by brhubbar** [comment]
Oh and, since I forgot my manners - thank you very much for making and maintaining Firefly. It's a wonderful tool and I've really enjoyed using it for the past year or so

**Comment by JC5** [comment]
Yes the "balance owed" and the "account balance" can be different. In all cases the balance due is what you're due / what you're owed. I'm not going to fix this in the current layout, it's on the list for the new one.

https://docs.firefly-iii.org/firefly-iii/financial-concepts/accounts/#liabilities
