### ISSUE TITLE
When adding a new transaction, the description does not show all descriptions

### ISSUE THREAD

**Issue by NiceGuyIT** [firefly-iii/firefly-iii#782]
The query used to pull the descriptions is limited to 100 rows. I consider my install small and the query returns about 230 records. The diff below fixed it. Ideally, this could be a parameter. At the very least, I think 100 is too small but I don't know if you want to make it 1000.

To reproduce in the demo site, try adding a withdrawal with the following descriptions. They don't show in the drop down even though there are previous transactions with the information.
* TV bill September
* Rent for October
* Water bill October
* TV bill September

Forgot to mention this is on version 4.6.4.

```diff
diff --git a/app/Http/Controllers/JsonController.php b/app/Http/Controllers/JsonController.php
index 849b0631f..0d5f78e58 100644
--- a/app/Http/Controllers/JsonController.php
+++ b/app/Http/Controllers/JsonController.php
@@ -292,7 +292,7 @@ class JsonController extends Controller
         $type  = config('firefly.transactionTypesByWhat.' . $what);
         $types = [$type];
 
-        $collector->setTypes($types)->setLimit(100)->setPage(1);
+        $collector->setTypes($types)->setLimit(1000)->setPage(1);
         $return = array_unique($collector->getJournals()->pluck('description')->toArray());
         sort($return);
```

**Comment by JC5** [comment]
The list is limited on purpose, just to give you quick hints of previous transactions. It's not really meant to go back very far. I can extend the limit but really I use it to quickly recreate "groceries" and "lunch" transactions.

I can go to 200 or 250 maybe, but more would defeat the purpose I think. I'll experiment and get back to you, OK?

**Comment by NiceGuyIT** [comment]
200 or 250 is good. I didn't expect you to bump it up to 1000.

Perhaps make this an enhancement request to make this configurable, similar to the way page size is configurable?

**Comment by JC5** [comment]
I'm not keen on adding options, so I'm going to set it to 250 for now. FF3 already has quite a lot of options and I try to add as few as possible :)

**Comment by JC5** [comment]
Closed to clear the list.
