### ISSUE TITLE
Definitive end date for bills

### ISSUE THREAD

**Issue by DamonCE** [firefly-iii/firefly-iii#7824]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Is it maybe possible to add a definitive end date of a specific bill, to make reports more accurate.

Example:
I have a health insurance bill monthly, I have had this for a year. Now I want to end it, because I moved my Health Insurance somewhere else.
I don't want to use the same bill for Health Insurance in general, as the company changed, it would give me a less good overview.

If I set the bill as inactive, it resets the bills, historically as well, so it looks like I didn't pay any bills in a month where I used this bill.
If I don't set the bill as inactive, it looks like I need to pay a lot more in the current months.

### Solution

Add a definitive end date of a bill, (as optional ofcourse)
Remove the bill from the expected field after this date. (And possibly from the bill overview/move it to a different category like "Ended bills"

### What are alternatives?

Use the same bill, even though the companies change and change the rule to allow for the change

**Comment by JC5** [comment]
> If I set the bill as inactive, it resets the bills, historically as well, 

So instead, what if the bill would be part of the reports, active or inactive?

**Comment by DamonCE** [comment]
If that can be combined with the box on the home page, historically (going back to homepage overview from a year ago for example), still saying the bill has been paid. Then I think that would be good.

**Comment by JC5** [comment]
Sounds like a job for https://github.com/firefly-iii/firefly-iii/issues/6306
