### ISSUE TITLE
Error when upgrading to 4.6.4 from 4.4.3

### ISSUE THREAD

**Issue by yverminck** [firefly-iii/firefly-iii#783]
Hello,

Today I realized I wasn't up-to-date with Firefly-iii so I went for an upgrade.
I used the "Installed Firefly using Git" from documentation as it was how I installed it the first time.

The installater complained that I didn't have the correct php version (7.0.22 iso 7.1). I installed php7.1 with it most common extensions and then added again curl and bcmath because it was still missing.
The installer then went fine, I followed all the steps which concluded by "Firefly III database is up to date."

Now, when i go to the /firefly-iii/public, I get the "Whoops, something went wrong error"
I tried a clean install "Installed Firefly using “create-project" as it installs it in a separated folder and the installation succeded as well, but still the same error.

My apache2 error log is attached.

I hope you can help me,

regards,

Yoann
[error.zip](https://github.com/firefly-iii/firefly-iii/files/1257000/error.zip)

**Comment by yverminck** [comment]
I just wanted to add that I already tried the re-chmod/re-chown as explained on the FAQ (even though, I suspect the error not to be related to permissions)

**Comment by JC5** [comment]
According to the error log you've sent, Apache is still linked to PHP7.0. Could you verify if the configuration of Apache is up to date? To check which version of PHP Apache is using, put the following code in a file called `phpinfo.php` and store this in `/firefly-iii/public/`. Browse to `/phpinfo.php` to see the results.

```
<?php
phpinfo();
```

**Comment by yverminck** [comment]
Hey James, thanks for the fast reply.

Indeed, it's still running php 7.0.22
I looked into enabling php7.1, but didn't succeed at the moment.
I did the following:
- php -v returns php7.1
- a2enmod php7.1 says that it is enabled and that I should restart apache
- upon restart, I'm still running php 7.0.22

I will keep looking into it, but if you have any idea in the meantime, it's welcome

**Comment by skibbipl** [comment]
Are you using php-fpm? Maybe the fpm proxy points to php7.0?

**Comment by yverminck** [comment]
I was running both version of php7.0 and php7.1.
At first, I wasn't too keen on disabling php7.0 as I have other websites running on that system.
But I finally disabled it and it everything is now working like a charm.

Thank you!

**Comment by JC5** [comment]
Nice!
