### ISSUE TITLE
Change description with creditor name

### ISSUE THREAD

**Issue by Kaysera** [firefly-iii/firefly-iii#7834]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I am importing data using Nordigen from N26 Bank in Spain. The current JSON returns

```JSON
{
    "transactionId": "aaaa-aaaa-aaaa",
    "bookingDate": "2023-08-07",
    "valueDate": "2023-08-07",
    "transactionAmount": {
        "amount": "-12.0",
        "currency": "EUR"
    },
    "creditorName": "CONFITERIA LA MODERNA",
    "remittanceInformationUnstructured": "-",
    "remittanceInformationUnstructuredArray": [
        "-"
    ],
    "additionalInformation": "bbbb-bbbb-bbbb",
    "bankTransactionCode": "cccc-cccc-ccc-ccc",
    "internalTransactionId": "ddddddddddd"
}
```

I'm not sure if it is N26 or Nordigen's fault, but the `remittanceInformationUnstructured` is filled with a dash, so there is no description. 

### Solution

A solution would be to create a rule that could write in the Description field whatever the Creditor name is.

### What are alternatives?

I'm not aware that any alternatives exist.

### Additional context

I'm currently using Firefly III 6.0.19 self-hosted using docker-compose. I'm also using Firefly III Data Import Tool v1.3.3.

**Comment by JC5** [comment]
At the bottom: https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/
