### ISSUE TITLE
Data Importer / API v1 Truncates long transaction descriptions

### ISSUE THREAD

**Issue by punkie909** [firefly-iii/firefly-iii#7835]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Whilst debugging a broken rule, I noticed that transactions with a long `description` imported via the importer got truncated to 254 characters.

I've been able to trace this back to
https://github.com/firefly-iii/firefly-iii/blob/c6e3fa2cc66859713c9401cd3d44b70f9739cff5/app/Factory/TransactionJournalFactory.php#L532-L537

Yet in the database the `description` field is 1024 chars long
https://github.com/firefly-iii/firefly-iii/blob/c6e3fa2cc66859713c9401cd3d44b70f9739cff5/database/migrations/2016_06_16_000002_create_main_tables.php#L552

Is there a reason to why `description` is truncated? Or should this be changed to 1024? Doing the latter fixed the issue on my system.

### Debug information

Debug information generated at 2023-08-08 16:50:58 Europe for Firefly III version **6.0.19**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.19 |
| Firefly III API | 2.0.4 |
| Build | 553, 28-07-2023 14:22:29 UTC |
| Base Build | 13, 26-07-2023 07:34:31 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe |
| Browser TZ | Europe |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_GB |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

**Comment by JC5** [comment]
Ah yes. It's pretty rare to have such long descriptions anyway. I'll check it out.
