### ISSUE TITLE
Data Importer password protection

### ISSUE THREAD

**Issue by M1scer** [firefly-iii/firefly-iii#7838]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

There is no way to protect the data importer web UI.

My importer is running at home and the web UI hast a seperate subdomain. So everyone in my LAN can access the importer.

### Solution

Add the option to protect the web UI of the data importer with a password.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/data-importer/installation/configuration/#authentication

This is already possible. Don't use an access token if others can reach the data importer as well, but use a client_id or set no authentication data. The data importer will authenticate users through Firefly III.
