### ISSUE TITLE
Show individual information for assests account

### ISSUE THREAD

**Issue by SmilingWorlock** [firefly-iii/firefly-iii#784]
Hello,

first: I have not worked with FF3 extensively, because I cant get the current version to install on my webspace (yet). But coming from YNAB 4 and not linking nYNAB, it seems to be perfect for me, and so far it looks fantastic.

However, one thing that already borthered me was that asset account overview shows the IBAN, not the account number. Only two of my accounts have an IBAN, but they all have account numbers of some sort (like credit card number, depot number etc.). 
Wouldn't it be better to have the field account number in the overview instead of IBAN? It could default to IBAN if one is present. Or better yet, make the fields customizable.

If you want to extend this further, one could make the options (or at least theirs names) you get when you enter a new asset account depending on the account type (Credit card -> Credit card number, Asset -> IBAN, savings account- > Number ....) I am not sure it would have any real use (yet), but I feel it would be a nice touch.

Best regards

**Comment by JC5** [comment]
Thanks for the compliments! :+1: 

I'm not going to make it customizable, but I like both ideas:

* More dynamic display of related account numbers
* More dynamic naming for account number types.

**Comment by JC5** [comment]
Instead of the account number, the CC will ask for a credit card number. The list of accounts will fall back to the account number when it's present.

**Comment by JC5** [comment]
Closed to clear the list.
