### ISSUE TITLE
Duplicated 'transactionId' from different bank account cause the discarding of all transactions except the first

### ISSUE THREAD

**Issue by BoGnY** [firefly-iii/firefly-iii#7840]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I've an automatic import every night with Nordigen, which import from 2 different bank account (same institution).

The problem is that there is the same `transactionId` in both bank account (**20230803-1**) which cause the discarding of other transactions except the first because identified as duplicated...

Importer version: **1.3.3**

### Debug information

Debug information generated at 2023-08-10 10:45:42 Europe/Rome for Firefly III version **6.0.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.18 |
| Firefly III API | 2.0.4 |
| DB version | 19 (exp. 19) |
| Docker | No |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Rome |
| Browser TZ | Europe/Rome |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 2097152 (2 MB) |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-09-30 23:59:59 |
| Session first | 2021-08-15 00:00:00 |
| User ID | 1 |
| User language | it_IT |
| User locale | it_IT |
| Attempt at "it_IT.utf8" | 'it_IT.utf8' |
| Attempt at "it_IT.UTF-8" | 'it_IT.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 |

### Expected behaviour

Same `transactionId` from different bank account should not identified as duplicated.

### Steps to reproduce

importer config file `import_firefly_bcc_conti_config_2023-06-13.json`:

```json
{
    "version": 3,
    "source": "fidi-1.3.0",
    "created_at": "2023-06-13T17:34:50+02:00",
    "date": "",
    "default_account": 1,
    "delimiter": "comma",
    "headers": false,
    "rules": true,
    "skip_form": false,
    "add_import_tag": false,
    "roles": [],
    "do_mapping": [],
    "mapping": [],
    "duplicate_detection_method": "cell",
    "ignore_duplicate_lines": false,
    "unique_column_index": 0,
    "unique_column_type": "external-id",
    "flow": "nordigen",
    "content_type": "unknown",
    "custom_tag": "",
    "identifier": "0",
    "connection": "0",
    "ignore_spectre_categories": false,
    "grouped_transaction_handling": "",
    "use_entire_opposing_address": false,
    "map_all_data": false,
    "accounts": {
        "3939b2b7-39cb-47aa-93b1-ACCOUNT-ZERO": 5,
        "3f7303d2-bc10-4bcd-9d67-ACCOUNT-ONE": 4
    },
    "date_range": "partial",
    "date_range_number": 7,
    "date_range_unit": "d",
    "date_not_before": "",
    "date_not_after": "",
    "nordigen_country": "IT",
    "nordigen_bank": "BCC_PORDENONESE_E_MONSILE_ICRAITRR9W0",
    "nordigen_requisitions": {
        "9fd41f8f-1312-4c05-a927-f5c15b8c4c56": "e5211b01-f05b-4968-b486-fd2206dabf73"
    },
    "nordigen_max_days": "10",
    "conversion": false,
    "ignore_duplicate_transactions": false
}
```

### Additional info

[importer.log](https://github.com/firefly-iii/firefly-iii/files/12310961/importer.log) (I can't paste here because is too long).

As seen, there are two transactions with `transactionId` **20230803-1** but they are from different bank account and the last one is discarged (wrongly) because duplicated.

**Comment by JC5** [comment]
> Same transactionId from different bank account should not identified as duplicated.

Sorry, this can't be helped. If the transaction ID is not actually unique, there isn't much I can do.

**Comment by BoGnY** [comment]
It's not possible to add a check like this:
when i'm importing `3939b2b7-39cb-47aa-93b1-ACCOUNT-ZERO` which is linked to firefly account 4, check `transactionId` uniqueness only in account 4? and not for all accounts transactions?

Or, is it possible to specify different field for uniqueness check?? For example `internalTransactionId` which is surely more unique than `transactionId` as it's an hash string instead a transaction date string?

[2023-08-05 02:00:16] local.DEBUG: Nordigen transaction from array {"transactionId":"**20230803-1**","entryReference":"20230803-1","bookingDate":"2023-08-03","valueDate":"2023-08-03","transactionAmount":{"amount":"3313","currency":"EUR"},"remittanceInformationUnstructured":"Emolumenti * STIPENDIO MESE LUGLIO 2023","proprietaryBankTransactionCode":"27//00","internalTransactionId":"**df695831e062214a2c43b0fe09d97123**","key":"booked"}

**Comment by JC5** [comment]
I'll see what I can do. Keep in mind that this could easily break the duplicate check for *other* users.

**Comment by BoGnY** [comment]
I've solved problem by changing duplicate detection methods from identifier-based to **content-based**
👍🏻
