### ISSUE TITLE
Docker `latest` Seems to have switched to a dev build

### ISSUE THREAD

**Issue by Ryonez** [firefly-iii/firefly-iii#7847]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The lasted tag on docker seems to point to a dev build, with a different, incomplete ui that is unable to even do transactions (unknown error when attempted).

### Debug information

Debug information generated at 2023-08-13 19:09:10 Pacific/Auckland for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| Build | 581, 12-08-2023 18:02:44 UTC |
| Base Build | 35, 30-07-2023 03:52:37 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Pacific/Auckland |
| Browser TZ | Pacific/Auckland |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-08-01 00:00:00 |
| Session end | 2023-08-31 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

### Expected behaviour

I was not expecting a ui change, none was announced. And the new UI is buggy, so I'm assume a dev build got into latest.

### Steps to reproduce

Use docker for this:
Be running on <=firefly-iii 6.0.19
Update to the latest tag (firefly-iii 6.0.20)

### Additional info

The dashboard? of the new UI:

![image](https://github.com/firefly-iii/firefly-iii/assets/16157130/2464fb74-ed44-4351-b9da-78038cb959a6)

For now, I've reverted back to firefly-iii 6.0.19 with now apparent issues.

**Comment by JC5** [comment]
What value do you have for FIREFLY_III_LAYOUT?

**Comment by Ryonez** [comment]
`FIREFLY_III_LAYOUT=v2`

I have not changed this recently.

**Comment by JC5** [comment]
Change it back to v1, which is the default value.

**Comment by Ryonez** [comment]
Thank you, that worked. (glances over at the issue being closed before confirmation it worked.)

I'm curious if there was documentation at some point recommending v2, as I've had this instance running for years with that config.
