### ISSUE TITLE
Composer is pulling old, buggy versions if php version is not right

### ISSUE THREAD

**Issue by SmilingWorlock** [firefly-iii/firefly-iii#785]
Hello,

I encountered several supposedly fixed bugs, because composer got me an old version, that was no good to use (php 7.0 got me 4.6.3, where all accounts are inactive once you touch them). I took me a while to figure that out. So for future users, it might be a good idea to change the installation guide to
`
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.6.4`

Than composer will check for php 7.1 and not get an old 7.0 version. If a user is so inclined to have firefly running on 7.0, they could still go back then. :) 

Best regards

**Comment by JC5** [comment]
Ah yes, that would make sure the installation "fails" when people have 7.0. I'll make sure the documentation is updated.

**Comment by JC5** [comment]
I've updated the documentation!
