### ISSUE TITLE
Keep track of unassigned money

### ISSUE THREAD

**Issue by SmilingWorlock** [firefly-iii/firefly-iii#786]
Hi,

Again, I just started testing firefly-iii coming from YNAB4. I hope you don't mind me putting all my thoughts forward.

I understand that firefly-iii wants to do as least automation as possible. I however think, this should not mean you have to switch back and forth between pages. So I'd like some way of keeping track of not assigned money (I do like the YNAB method). At the moment, I have to manually check: How much money to I earn this month? How much did I budget of that? How much did I put in a piggy bank? While I understand this keeps you thinking about your money, it seems to be error prone and commiting money at two points will lead to overspending.

Maybe two steps towards this could be:

Show a available for budgeting amount, which should be 
`balance - budgeted - expenses w/o budget - piggy banks `

Show in the available value in the piggy banks not as `balance - saved in piggy bank`, 
but as  `balance - budgeted - saved in piggy banks`

I am not sure, how the storage of transactions, budget and piggy banks is handled, especially with regard to flexible timeframes. I guess you would have to avoid recounting all transactions to get the values. But budgets are only monthly (right?), so this might be done on a monthly basis, too.

I tried looking into the code to help and provide some sort of sample implementation, but this is too advanced programming for me. 

Best regards

**Comment by JC5** [comment]
No no, please keep dumping your ideas.  The problem with automation is that it forces the user into a very specific workflow. I hate that about YNAB so I try to be as unassuming as possible. I realize that FF3 also does this but I hope to make as much "optional to use" as possible.

Budgets are flexible and can be set per day if you want to (see your preferences for your preferred period). What I do now on the budgets-page is show you a "bar" that allows you to set how much money is available to be budgeted each month. You can see this on the [demo site here](https://firefly-iii.nder.be/budgets).

This will allow you to keep track of the assigned amount of money, but it is *not* based on your income. You have to set this manually. Currently, the bar shows you how much money is left to be budgeted.

I'll keep this issue open, let me know how this could be handled. Personally, I think that the current method works pretty well. I like two aspects of your posts already, and those can be implemented fairly easily.

- Warn the user when he has not set a total budget amount for this month.
- Warn the user about non-budgeted budgets.
- Auto-update the monthly amount when income is created, unless the user edits this by hand.

I'm not sure yet how to include other transactions (and piggy banks) in the equation.

**Comment by SmilingWorlock** [comment]
I have seen the bars, but as you say, they are only based on what I enter, which may be a wrong number. Maybe revenue accounts (or even transactions, or the split parts of transactions) could get a "Count towards budget" flag. The available amount for budgeting would than be the sum of that transactions in a month (or even the previous, if you can implement that as an option). This allows users to freely choose how their available budget is created.

I now realized that piggy banks are tied to accounts. I think, this would create the need for linking budget amounts to a account, which is probably not a good idea. Is there a reason for the link between piggy bank and account? Are they just a value you increase or decrease, or are the actual actions of increasing / decreasing stored somewhere? 

I will think about this somemore. I will also try to not be so ynabby and assumptious. ;-)

**Comment by JC5** [comment]
Piggy banks are linked to an account. Their main goal is to divide the money in your savings account over a set of goals. If I have a 1000,- in my saving account, I could say:

300 for new couch, target amount is 500
300 for a new camera, target amount is 300
400 for a new car, target is 5000

**Comment by SmilingWorlock** [comment]
I see, so if I have 500, and budget 400 for food, I should not have 500 left for piggy banks, right. But that is happing right now. 

To add to my previous idea (Count towards budget flag). The auto-calculated "available to budget" value should have an offset amount, which would allow the user to

- freely modify the available to budget
- everytime I move money out or into a piggy bank, this value gets modified, so if I move money into the piggy bank, its gone from "available to budget"
- it could also hold the unassigned money from the past at the beginning of the month (balance - piggy banks), allowing unspent budget money to be budgeted again (because budgets don't carry over, which is a upcoming idea)

**Comment by JC5** [comment]
If you take the sum of all your accounts, and you're alone then yes, your idea could work.

I budget for shared accounts as well as my own which makes this a lot more complicated.

**Comment by JC5** [comment]
Thinking about this there's just no universal way of doing this. I don't like the idea of budgeting _all_ your money, that's really YNAB's spiel. I don't want to introduce that to FF3.

The features you're thinking about introduce a lot of "magic" in that regard, changing budgets and amounts and what-not. When you spend money, it counts towards a budget simply when you set a budget.

It all [matches how I do things](https://firefly-iii.github.io/about-grand-theory.html) but doesn't presume anything.

**Comment by SmilingWorlock** [comment]
I see, how implenting one thing requires implementing so many other things. That makes it so difficult. But I don't like the way of indicating my available money by actually moving it to another saving account. I have to many accounts for that. I will further play around with FF3, maybe I have another idea once I get better with it.

You could show the summed income stream for this and last period in the windows where you set the available budget. (Much like the money in, money out bar in the dash board)

**Comment by JC5** [comment]
That should at least give you a clear indication. How about some basic statistics of your previous incomes and expenses? That should make it easier to pick the "amount available".

Perhaps a little :information_source: button next to the "amount per budget" things that tells you what FF3 would suggest you do?

**Comment by SmilingWorlock** [comment]
Yes, a little information button would be a great help.  To come back around to the start of the issue, my main complaint was that I had to manually switch back and forth between pages (income, piggy bank, budget) to check how much money was put in where. Maybe you could have a hover-over button in the menu and header that just shows the most important values (like Income, Spent, Balance, Budgeted, stored in Piggy banks), so they are always available

**Comment by JC5** [comment]
This button exists for a while now, so the ticket can be closed.
