### ISSUE TITLE
FIDI multiple roles to 1 column

### ISSUE THREAD

**Issue by DamonCE** [firefly-iii/firefly-iii#7868]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like the data importer to map multiple roles to a specific column
It makes it easier to use the ING specific CSV within the data importer.

### Solution

You would be able to add multiple roles to a specific column.

For example in the ING CSV you have a column called `Naam / Omschrijving`
If I can match that column to both Opposing account (name) and Description, it would make it easier to work with

### What are alternatives?

Right now I duplicate the column and match it to both roles to get the wanted result.

### Additional context

![image](https://github.com/firefly-iii/firefly-iii/assets/46165452/3166ee6f-20f0-4fc3-b900-97f245aa7c84)

**Comment by JC5** [comment]
No sorry, one role to one column. 

You can edit the file yourself or use rules to copy from notes to description or vice versa.
