### ISSUE TITLE
Date role is missing from Data-Importer Role list

### ISSUE THREAD

**Issue by arcreigh** [firefly-iii/firefly-iii#7869]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Documentation points to use the Date Role for the date column when doing a CSV import. 

![image](https://github.com/firefly-iii/firefly-iii/assets/7982245/1b2c012f-3b1b-4745-b8db-a4d0c4bc86d6)

Unfortunately the Date field is missing so when I try to import my data the current date is utilized instead of the date from the CSV file.

### Debug information

n/a

### Expected behaviour

Date field should be present in the dropdown

### Steps to reproduce

1. Attempt to import CSV and be sure to include role definition.
2. Attempt to select Date role

Role is missing in list.

**Comment by JC5** [comment]
Use "transaction date". Can you show me where it says it's "date"?

**Comment by arcreigh** [comment]
First picture on https://docs.firefly-iii.org/data-importer/how-to-use/fine-tune-import/

I did wind up figuring out my issue and was able to import but docs should likely be updated with what the various fields mean to Firefly and how they are used within the app :) csv had '/' instead of '-' 

Brain was definitely on auto-pilot.

**Comment by JC5** [comment]
> but docs should likely be updated with what the various fields mean to Firefly and how they are used within the app

Eh, do you mean the text directly below the picture that explain what the various fields mean to Firefly III and how they are used within the app?
