### ISSUE TITLE
Budget values are always saved to the current month

### ISSUE THREAD

**Issue by SmilingWorlock** [firefly-iii/firefly-iii#787]
Hello,

I can enter a budget for this month and it gets saved. If I use the controls to switch to another month, I can enter values, but the are not retained for that month if I go to another month and then come back. 

I just noticed that the values are getting entered for the current month. So If I add 10€ to a budget in August and then go to September and enter 1€, if I go back to August there is 1€ in the budget. If I go back to September, there is 0€ in the budget.

Best regards

**Comment by JC5** [comment]
Whether it's coincidence or not, I found out about this a few days ago.  😮 

A work-around is to select the period for which you want to set a budget using the date-select thing in the top right corner. Then it will work perfectly. Make sure you use the /budgets URL when you do this!

The next release could be this weekend and will include a fix.

**Comment by JC5** [comment]
Closed to clear the list.
