### ISSUE TITLE
Importer rejects all transactions in CSV import since 1.3.4 update

### ISSUE THREAD

**Issue by DireMunchkin** [firefly-iii/firefly-iii#7871]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since the 1.3.4 update today I'm getting errors similar to these ones on all transactions I try to import:
```
Line #0:
- (2)transactions.0.destination_id: Source and destination are the same. (original value: "7")
- (2)transactions.0.destination_name: Source and destination are the same. (original value: "(not found)")
```

I'm using a saved config and CSV to import transactions from my credit card and bank. Normally I import without an destination account and then add destination later with rule sets. That doesn't explain why the source and destination is the same though. I'd expect something like `source: <bank account> destination: nil`.

I tried rolling back to 1.3.3 and confirmed that it still works on that version.

### Debug information

Debug information generated at 2023-08-20 20:59:15 Europe/Stockholm for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| Build | 581, 12-08-2023 18:02:44 UTC |
| Base Build | 35, 30-07-2023 03:52:37 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Stockholm |
| Browser TZ | UTC |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-08-01 00:00:00 |
| Session end | 2023-08-31 00:00:00 |
| Session first | 2022-12-18 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0 |

### Expected behaviour

I'd expect the import to work the same as in the last version.

### Steps to reproduce

1. Run importer 1.3.4
2. Import with attached config and transaction.

### Additional info

[Config and Transaction.zip](https://github.com/firefly-iii/firefly-iii/files/12388989/Config.and.Transaction.zip)

**Comment by JC5** [comment]
Thanks, nice find. This should be fixed in the latest develop branch. You can pull the `develop` Docker tag to see it in action.

Could you confirm if the develop version fixes the issue?

**Comment by DireMunchkin** [comment]
Yes, now it works. Thanks for the quick fix!

**Comment by JC5** [comment]
Not a problem! I shall push a release asap so others won't have this problem.
