### ISSUE TITLE
Data Import fails

### ISSUE THREAD

**Issue by mrfenyx** [firefly-iii/firefly-iii#7878]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The data importer returns the following error messages when trying to import transaction information:
```
Line #0:
(2)transactions.0.destination_id: Source and destination are the same. (original value: "1")
(2)transactions.0.destination_name: Source and destination are the same. (original value: "(not found)")
```

Here is a sample of the CSV that I am importing:
```
Kontonummer;Buchungsdatum;Valuta;Empfaenger 1;Empfaenger 2;Verwendungszweck;Betrag;Waehrung
20035794;30.06.2023;30.06.2023;;;LASTSCHRIFT Gemeinnuetzige Wikimedia Fo erdergesellschaft mbH Ihre Spende fuer Wikipedia;-5,00;EUR
```

Here is my import config file:
```
{
    "version": 3,
    "source": "fidi-1.0.2",
    "created_at": "2023-02-23T10:23:23+01:00",
    "date": "d.m.Y",
    "default_account": 1,
    "delimiter": "semicolon",
    "headers": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "roles": [
        "_ignore",
        "date_transaction",
        "_ignore",
        "_ignore",
        "_ignore",
        "description",
        "amount",
        "_ignore"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "duplicate_detection_method": "classic",
    "ignore_duplicate_lines": true,
    "unique_column_index": 0,
    "unique_column_type": "internal_reference",
    "flow": "file",
    "identifier": "0",
    "connection": "0",
    "ignore_spectre_categories": false,
    "map_all_data": true,
    "accounts": [],
    "date_range": "",
    "date_range_number": 30,
    "date_range_unit": "d",
    "date_not_before": "",
    "date_not_after": "",
    "nordigen_country": "",
    "nordigen_bank": "",
    "nordigen_requisitions": [],
    "nordigen_max_days": "90",
    "conversion": true,
    "ignore_duplicate_transactions": true
}
``` 

The same file format (CSV) was successfully imported until about the beginning of June, when I did my last import. Now, it throws the error. Any help / suggestions are welcome.

### Debug information

Debug information generated at 2023-08-21 12:52:12 Europe/Berlin for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| Build | 597, 17-08-2023 10:06:07 UTC |
| Base Build | 35, 30-07-2023 03:52:37 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | production |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-09-30 23:59:59 |
| Session first | 2022-11-30 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

Debug information generated at 2023-08-21 12:52:58 Europe/Berlin for Firefly III Data Importer version **1.3.4**.

| Scope | Version |
| --- | --- |
| FIDI | 1.3.4 |
| Build | 274, 20-08-2023 04:50:15 UTC |
| PHP | 8.2.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

**Comment by mrfenyx** [comment]
Here is some additional Debug info:
```
[2023-08-21 12:43:23] production.DEBUG: Submitting to Firefly III: {"group_title":null,"error_if_duplicate_hash":true,"transactions":[{"type":"transfer","date":"2023-07-31 00:00:00","currency_id":null,"currency_code":"EUR","amount":"5.000000000000","description":"LASTSCHRIFT Gemeinnuetzige Wikimedia Fo erdergesellschaft mbH Ihre Spende fuer Wikipedia","source_id":1,"source_name":null,"destination_id":1,"destination_name":null,"original_source":"jc5-data-import-v1.3.4","tags":[],"source_iban":null,"source_number":null,"source_bic":null,"destination_iban":null,"destination_number":null,"destination_bic":null}]} 
[2023-08-21 12:43:23] production.ERROR: Submission error: 0 ["Source and destination are the same."] 
```

I believe the issue might be related to the fact that the Bank Export doesn't contain an opposing account in the export so FIDI just takes ID "1" for that, which is also the ID of the account that I am importing the transactions for.

**Comment by JC5** [comment]
#7871
