### ISSUE TITLE
Support language variants (like de_AT)

### ISSUE THREAD

**Issue by Findus23** [firefly-iii/firefly-iii#788]
Hi,

I am very happy I found your software. Setup wasn't as difficult as I expected it to be but there was one thing I stumbled upon:

I have set the language settings to German, but the number formatting looked odd.
I have the following locale on my server:
```
➜  /var/www/firefly-iii locale -a          
C                                          
C.UTF-8                                    
de_AT.utf8                                 
en_US.utf8                                 
POSIX                                      
```
I noticed that `de_AT.utf8` was missing here and after adding it everything works perfectly:

https://github.com/firefly-iii/firefly-iii/blob/master/resources/lang/de_DE/config.php#L15

I guess people in Swiss are having the same issue with `de_CH.utf8` and I guess the same also exists in other languages.

Maybe you have an solution for this problem.

**Comment by JC5** [comment]
And by odd you mean "missing decimal separator and any formatting" or "formatted like de_DE"?

**Comment by Findus23** [comment]
Hi, 

Thanks for your response. 
I mean not formatted at all (or formatted like English)
I am not even sure how large the formatting differences between de and at are.

**Comment by JC5** [comment]
I was experimenting for a short time this morning, and my installation was able to format English-formatted numbers with only de_AT installed. However, I have to verify the exact situation, so I was just curious what happened in your case.

I hope to be able to share some debug information later on. Reason is, I want to avoid adding de_AT to the de_DE list because it could have undesired side-effects for people who have both de_AT and de_DE installed but prefer de_DE (which is often the case for language packs that just install everything).

**Comment by Findus23** [comment]
I think the numbers were formatted correctly but in the English fallback locale in my case .
I just got confused with the input field where Firefox displayed my system locale. 

What about adding the country to the language selection? E.g. list all locales that are available on the server and let the user select the one they like.

**Comment by JC5** [comment]
It would break the translations, but the idea of selecting a locale _and_ a language is a nice idea. I'll think about what would work!

**Comment by Findus23** [comment]
Another advantage would be for people who don't like the number format of their language (e.g. `,` as decimal separator in German)

And issues like #670, #650, #775 would also be easier noticeable as the locale wouldn't appear in the list. One could add a note next to the select `If your locale is missing make sure it is configured correctly on your server [link to explaination]`

**Comment by JC5** [comment]
Yeah the locale thing is in the installation guide and in the FAQ: people just don't read them. :P

**Comment by JC5** [comment]
I've added some warnings instead that tell the user no valid locale can be found. Allowing the user to choose very specific locales is off the table, as PHP does not support it.

Meaning, that I can do `locale -a` and I can make PHP call `locale -a`, but there is no universal way (Windows, shared hosts, restricted servers) of getting that list. There are some tricks I'd rather not try (simply set ALL locales and remember which ones work).

So it's going to be the warning, and nothing else I'm afraid.

**Comment by Findus23** [comment]
Hi, thanks for the update. Does this solve my initial issue? (Firefly is looking for de_DE, but my server only has de_AT)

**Comment by JC5** [comment]
No, I'm sorry, that's something I can't fix.

**Comment by Findus23** [comment]
No Problem.
If editing one file after updating is everything I have to do to use this great software, I'm happy.
