### ISSUE TITLE
Data Importer Source and destination are the same issue in newest vesrion

### ISSUE THREAD

**Issue by audifan88** [firefly-iii/firefly-iii#7880]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Using the new v.1.3.4 of the importer fails with error Source and destination are the same. I did see mention of this previously but feel this issue is new. I was banging my head against the wall as my CSV file imported fine the other day, in checking the updates I see there was an update 2 days ago and in testing v1.3.3 this is a non issue with the same CSV file. CSV contains 3 columns, date, description, and amount (-,+).

### Debug information

(2)transactions.0.destination_id: Source and destination are the same. (original value: "15")
(2)transactions.0.destination_name: Source and destination are the same. (original value: "(not found)")

### Expected behaviour

I expected the import to work the same as it did a few days ago.

### Steps to reproduce

Setup new firefly docker instance using mariadb. Create initial asset account with 0 balance. Create PAT for importer docker container and build that. Attempt to import CSV, using the same CSV I get the above errors on version 1.3.4, not on version 1.3.3.

### Additional info

I hope this is helpful but if there is more I can do to help please let me know.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/7871
