### ISSUE TITLE
Accounts are not searchable in transaction page

### ISSUE THREAD

**Issue by NoiTheCat** [firefly-iii/firefly-iii#7881]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When trying to create a new transaction, the drop-down list that appears to select a source account shows only the most recently created accounts, as well as "Initial balance account of ...". No other accounts are shown, searchable, or able to be properly input. This becomes an issue as soon as enough accounts are created, including expense accounts.

![image](https://github.com/firefly-iii/firefly-iii/assets/29664685/1575902f-20b3-4e4d-8214-0a0abec7d91d)

### Debug information

Debug information generated at 2023-08-22 10:22:14 Europe/Amsterdam for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| DB version | 20 (exp. 20) |
| Docker | No |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | America/Los_Angeles |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 39845888 (38 MB) |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | sqlite |
| Current driver | sqlite |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-08-01 00:00:00 |
| Session end | 2023-08-31 23:59:59 |
| Session first | 2023-08-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203 |

### Expected behaviour

Accounts list is filtered and the desired account is selectable.

### Steps to reproduce

1. Create a handful of expense and/or revenue accounts
2. Go to create a new withdrawal
3. Under Source, enter the name of an asset account
4. Notice that the list which popped up beneath the text box is not changing

### Additional info

I've noticed that this works as expected in the demo, so I have a suspicion that my choice of using sqlite as a database may be a factor. For what it's worth, I am also running this within a custom Docker container, installed by using the self-hosted guide as a reference.

Attempting to manually type in the name of the account and then submitting causes the error `Error! There was something wrong with your submission. Please check out the errors.` with no further explanation. The error returned according to the Network tab in the inspector is:
```
{
    "message": "The selected transactions.0.type is invalid.",
    "errors": {
        "transactions.0.type": [
            "The selected transactions.0.type is invalid."
        ]
    }
}
```

**Comment by JC5** [comment]
Are there any errors in the console related to the loading of the suggestions, while you type?

**Comment by NoiTheCat** [comment]
Nope, no errors. It seems to be otherwise working as expected, but it always returns the exact same values no matter what I type.

![image](https://github.com/firefly-iii/firefly-iii/assets/29664685/6ab3cf60-e2a9-4d81-813b-58034068e56c)

![image](https://github.com/firefly-iii/firefly-iii/assets/29664685/909c3b57-60c0-4551-a5ce-c2eb8921df2d)

**Comment by JC5** [comment]
Do you have some kind of a reverse proxy? Could it be filtering the query parameters?

- If you visit `/transactions/withdrawal?page=2`, you should get an empty list.
- If you visit `/search?search=test&go=`, it should search for "test"

**Comment by NoiTheCat** [comment]
It didn't work, which made me realize something... Seems I hadn't configured nginx correctly and it was dropping all the query parameters whenever there were any.
For the sake of completeness, this is how I have it configured now:
```
location / {
    try_files $uri $uri/ /index.php?$is_args$args;
}
```
The `$is_args$args` bit was crucial for getting everything to work as it should.

Thank you so much!
