### ISSUE TITLE
Missing Text on "Bills" page

### ISSUE THREAD

**Issue by M1scer** [firefly-iii/firefly-iii#7883]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have created some Bills and recognized some strange text. For me it looks like that this is just a placeholder to which no text has been assigned yet.

Same behavior in German, English (UK) and (US)

![grafik](https://github.com/firefly-iii/firefly-iii/assets/93549967/3732ed17-3f19-469d-a376-28e3d0729617)

### Debug information

Debug information generated at 2023-08-22 16:01:59 Europe/Berlin for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| Build | 597, 17-08-2023 10:06:07 UTC |
| Base Build | 35, 30-07-2023 03:52:37 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-08-22 23:59:59 |
| Session first | 2021-08-31 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0 |

**Comment by JC5** [comment]
Nice find, that's a placeholder indeed. I'll pick it up!
