### ISSUE TITLE
Edit selection individually - add column "tags"

### ISSUE THREAD

**Issue by M1scer** [firefly-iii/firefly-iii#7887]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to edit tags of multiple transactions and it would be nice to be able to do this in the "edit selection individually" mode.

### Solution

Add the column "Tags" to this view.

### What are alternatives?

Add an option to hide and show columns.

### Additional context

Two columns used to organize transactions are already present, only the column for tags is missing.

If you use all three options, you end up having to edit each transaction individually.

**Comment by JC5** [comment]
No room. Perhaps in the new layout, it's already on the list. Sorry.
