### ISSUE TITLE
Bulk edit adding tags does not work

### ISSUE THREAD

**Issue by Vivovix** [firefly-iii/firefly-iii#7897]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In bulk edit mode, adding tags does not work. The input fields stays greyed out. 

### Debug information

Debug information generated at 2023-08-27 13:37:43 Europe/Amsterdam for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| Build | 597, 17-08-2023 10:06:07 UTC |
| Base Build | 35, 30-07-2023 03:52:37 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-08-27 23:59:59 |
| Session first | 2023-07-03 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0 |

### Expected behaviour

When editing multiple transactions, adding a tag and confirming should add the tag to all transactions.

### Steps to reproduce

1. Select several transactions
2. Choose actions -> "Edit in bulk"
3. Type out a tag
4. Pick radio button option 'add these tags'
5. Click 'change these transactions'

### Additional info

 The same issue arises on the demo page.

**Comment by JC5** [comment]
It works fine for me.

**Comment by JC5** [comment]
Be sure to press "enter" after you add a tag.

**Comment by Vivovix** [comment]
Alright, that's on me :-). In regular editing, clicking anywhere in the screen when you have a tag typed adds the tag automatically. So I never actually hit the enter button before. Thank you.
