### ISSUE TITLE
Show total balance on dashboard

### ISSUE THREAD

**Issue by robin5210** [firefly-iii/firefly-iii#790]
Hello,

I use Firefly for doing the finances of our local youth club. However sometimes I want to know how much money we have in total as this is spread over multiple accounts. 

Is it possible to add a total balance to the dashboard? I assume this would be per currency as exchange rates tend to change.

**Comment by JC5** [comment]
Per currency would be a good idea overall, to update the boxes in case multiple currencies are involved. Generally speaking, exchange rates are only used (once) when transactions are stored, and they can be corrected by the user.

After that, the currency exchange rate isn't really relevant. If you have an account in USD and an account in EUR, you could display both of them in de box.

Speaking of boxes, I can't add just one. It won't work in the layout. Needs a second box as well. I'll have to think about what the second box could show before I can add the first one.

See also: https://github.com/firefly-iii/firefly-iii/issues/684

**Comment by robin5210** [comment]
Is there a technical reason boxes are to be added in multiples of two? Otherwise it may be an idea to allow the user to select the boxes he wants to see on the dashboard in the settings.

**Comment by JC5** [comment]
It's ugly because it breaks the layout or the boxes are uneven in size.

**Comment by JC5** [comment]
I've added this, you can see it on [the demo site](https://firefly-iii.nder.be/)!
