### ISSUE TITLE
Get Balance Chart Data Error: $period must be of type string (Stringable given)

### ISSUE THREAD

**Issue by victorbalssa** [firefly-iii/firefly-iii#7910]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When trying the new V2 chart endpoint: 
- https://api-docs.firefly-iii.org/?urls.primaryName=2.0.5%20(v2)#/charts/getBalanceChart

I got an error:

```
Internal Firefly III Exception: FireflyIII\\Support\\Navigation::preferredCarbonFormatByPeriod(): 

Argument #1 ($period) must be of type string, Illuminate\\Support\\Stringable given

called in /var/www/demo/app/Api/V2/Controllers/Chart/BalanceController.php on line 93
```

Where?:
- https://github.com/firefly-iii/firefly-iii/blob/main/app/Api/V2/Controllers/Chart/BalanceController.php#L93
- https://github.com/firefly-iii/firefly-iii/blob/main/app/Api/V2/Controllers/Chart/BalanceController.php#L251

A good old `->__toString();` seems to fix everything (on my end).

Thanks!

### Debug information

API endpoint json return:

```json
{
    "message": "Internal Firefly III Exception: FireflyIII\\Support\\Navigation::preferredCarbonFormatByPeriod(): Argument #1 ($period) must be of type string, Illuminate\\Support\\Stringable given, called in /var/www/demo/app/Api/V2/Controllers/Chart/BalanceController.php on line 93",
    "exception": "TypeError"
}
```

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
Fixed on the demo site and in the develop branch + Docker tag.
