### ISSUE TITLE
[Importer] Unreachable app:8080 using step-by-step in documentation with Docker compose

### ISSUE THREAD

**Issue by SoulRaven80** [firefly-iii/firefly-iii#7912]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Following the documentation and setting only minimal configuration, Firefly Importer cannot finish the handshake.

### Debug information

Debug information generated at 2023-08-30 18:38:06 Europe/Amsterdam for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| Build | 597, 17-08-2023 10:06:07 UTC |
| Base Build | 35, 30-07-2023 03:52:37 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | America/Chicago |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-08-01 00:00:00 |
| Session end | 2023-08-31 23:59:59 |
| Session first | 2023-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0 |

### Expected behaviour

Importer should be able to successfully connect to FireflyIII, instead an error page arise trying to connect to app:8080

### Steps to reproduce

On a base directory (Ubuntu)

```
mkdir fireflyiii
cd fireflyiii
curl https://raw.githubusercontent.com/firefly-iii/docker/main/docker-compose-importer.yml > docker-compose.yml
```

1. Only update **REPLACEME** in the cron url section (nano **_docker-compose.yml_** -> edit, save, exit)

```
curl https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.env.example > .env
curl https://raw.githubusercontent.com/firefly-iii/data-importer/main/.env.example > .importer.env
curl https://raw.githubusercontent.com/firefly-iii/docker/main/database.env > .db.env
```

2. Update **DB_PASSWORD** in **_.env_** and **MYSQL_PASSWORD** in **_.db.env_** to the SAME value  (nano **_.env_** -> edit, save, exit / nano **_.db.env_** -> edit, save, exit)
3. Change **FIREFLY_III_URL** in **_.importer.env_** to **http://app:8080** (nano **_.importer.env_** -> edit, save, exit)

```
docker compose up -d
```

4. Open Firefly III URL (port 80 from the default **_docker-compose.yml_** file)
5. Register new user
6. Open Firefly Importer URL (port 81 from the default **_docker-compose.yml_** file) and take note of the **Redirect URL** param
7. Get back to Firefly III page and create an **Oauth Client** in using the **Redirect URL** reported from step 6
8. Get back to Firefly Importer and complete the form (**Firefly III URL** and **Client ID** from step 7)
9. Click submit
10. Confirm authorization

Result: Error page
![Error](https://github.com/firefly-iii/firefly-iii/assets/6943133/99da0e99-9526-425d-bd82-cc5d8806e3aa)

### Additional info

Note the URL from the error page, as **https**://app:8080, when configuration files were updated using **http** (step 3)

**Comment by JC5** [comment]
If you just mentioned this on Gitter, this is now fixed in the documentation and the latest version of the data importer.

**Comment by JC5** [comment]
Since that version is not yet out, you can trial-run using the `develop` tag and this page:

https://github.com/firefly-iii/docs/blob/main/docs/docs/data-importer/installation/docker.md

**Comment by SoulRaven80** [comment]
Update:
Trying workarounds and found that the flow works when setting the Personal Access Token instead of the Client ID.
To do so, replace steps 6 onwards with:

... [Steps 1-5] ...
6. Go to Firefly III Profile page and create a **Personal Access Token** (within OAuth tab) and take note of it
```
docker compose down
```
7. Set the PAT from step 6 into **FIREFLY_III_ACCESS_TOKEN** var within **_.importer.env_** (nano **_.importer.env_** -> edit, save, exit)
```
docker compose up -d
```
8. Open Firefly Importer URL (port 81 from the default **_docker-compose.yml_** file)
9. Enjoy!

**Comment by ppp0l** [comment]
the solution proposed here needs to be more visible (maybe in the docs), I was almost giving up but this worked for me

**Comment by JC5** [comment]
This page was recently updated to take into account all the feedback. Please let me know at which step you gave up so I can fix it. Thanks!

https://docs.firefly-iii.org/data-importer/installation/docker/

**Comment by ppp0l** [comment]
I had followed the instructions in the docs until the autentication step on the importer page (where it requests for client id and you click submit), from there I couldn't get to the authorization request page and I had error 404  (I had looked into other threads, I tried to use the reset and reauthenticate buttons multiple times but I had no results).
Creating a Personal Access Token and modifying the corresponding attribute in .importer.env as above worked, instead.

**Comment by JC5** [comment]
Alright thanks!
