### ISSUE TITLE
Generated URLs' protocols are incorrect when not in an <a>-element 😕

### ISSUE THREAD

**Issue by baflo** [firefly-iii/firefly-iii#7913]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

So, I cannot check the last box, it might very well be me, but this is a strange behavior and I tried the different suggestions from the documentation and other issues.

I have my Firefly-III instance running behind an nginxproxymanager instance and it's reachable. However, some URLs in the HTML are rendered with an incorrect protocol. 

All URLs/links that are rendered in an anker, i.e. like `<a href="{{ route("index") }}">` are correct with `https://`. Others however, like `var accountFrontpageUrl = '{{ route('chart.account.frontpage') }}';` are rendered incorrectly with `http://` protocol.

I am not familiar with Laravel or Twig, but I tried to dig deep on this and found that this actually renders with `http://` in the first and `https://` in the second case:

```twig
{# Logo #}
&lt;a href="{{ route('index') }}" class="logo"&gt;
<a id="{{ route('index') }}" href="{{ route('index') }}" class="logo">
    {# mini logo for sidebar mini 50x50 pixels #}
    <span class="logo-mini">FF</span>
    {# logo for regular state and mobile devices #}
    <span class="logo-lg"><strong>Firefly</strong>III</span>
</a>
```

renders:

```html
&lt;a href="http://firefly.example.de" class="logo"&gt;
<a id="http://firefly.example.de" href="https://firefly.example.de" class="logo">
<span class="logo-mini">FF</span>
<span class="logo-lg"><strong>Firefly</strong>III</span>
</a>
```

### Debug information

Debug information generated at 2023-08-31 16:34:35 Europe/Berlin for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| Build | 597, 17-08-2023 10:06:07 UTC |
| Base Build | 35, 30-07-2023 03:52:37 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-08-01 00:00:00 |
| Session end | 2023-08-31 23:59:59 |
| Session first | 2023-01-04 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.62 |

### Expected behaviour

All `{{ route('...') }}` calls should return the same result.

**Comment by JC5** [comment]
See also: https://docs.firefly-iii.org/data-importer/faq/installation-errors/#i-get-page-load-errors-because-the-protocols-dont-match

**Comment by baflo** [comment]
Yep, it's eventually been the nginxproxymanager configuration. I haven't found out, yet, how to configure it in the UI correctly, but I could figure out that manually changing the configuration is the charm.

Just as clarification for others in the future: my Firefly-III instance is behind an nginxproxymanager container which itself is made public using a Cloudflare tunnel. I `curl`ed the proxy directly with `curl -k -H "Host: firefly.example.de" https://nginxproxymanager:443` and this returned https schemes at all places. However, when calling `curl -H "Host: firefly.example.de" http://nginxproxymanager:80` it returned `http` at all places. Only when calling `curl -k https://firefly.example.com` it was wrong.

So I think it's a combination of two issues:

1. I suppose the problem is the connection between tunnel service and nginx proxy manager which is using http, which makes Firefly-III think it's publicly available with http.
2. Probably it's Cloudflare which is replacing the `http` links in the HTML doc.

Somehow I will have to tell the proxy manager to always use `https`.

**Comment by JC5** [comment]
The nginx proxy manager talks to the Firefly III container. Can you configure it to add the following header when talking to the container? `X-Forwarded-Proto: https`.

**Comment by baflo** [comment]
Yes, I can do that in the UI. However it ends up like this in the final generated config: 

```
  location / {                                                                                                                                                                                             
    proxy_set_header Host $host;                                                                                                                                                                           
    proxy_set_header X-Forwarded-Scheme $scheme;                                                                                                                                                           
    proxy_set_header X-Forwarded-Proto  $scheme;                                                                                                                                                           
    proxy_set_header X-Forwarded-For    $remote_addr;                                                                                                                                                      
    proxy_set_header X-Real-IP          $remote_addr;                                                                                                                                                      
    proxy_pass       http://db21ed7f-fireflyiii:8080;                                                                                                                           
                                                                                                                                                                                                           
    proxy_set_header Upgrade $http_upgrade;                                                                                                                                                                
    proxy_set_header Connection $http_connection;                                                                                                                                                          
    proxy_http_version 1.1;                                                                                                                                                                  
                                                                                                                                                                                                           
    proxy_set_header X-Forwarded-Proto https;                                                                                                                                                                                                                                                                                                                                                                      
  }
```

There seems to be a default config, that's not so easy to override. I'll have another look tonight.

**Comment by JC5** [comment]
Well the header with $scheme seems to be what I was looking for. It seems the proxy manager is dynamic and responds to the port. If that works, you're basically done and we'll have solved the riddle ;)

**Comment by baflo** [comment]
I configured the tunnel to terminate at the proxy's port 443 and now it's working. It doesn't feel optimal, but it works. I'll.close the issue.

Thank you for the support, although it's been my fault :)

**Comment by JC5** [comment]
Glad to be of service!
