### ISSUE TITLE
"Pay Bill" Button

### ISSUE THREAD

**Issue by VPaulV** [firefly-iii/firefly-iii#7919]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi everyone,

Is it possible to introduce a "Pay Bill" button next to every bill I have. Currently, what I do is click on a bill, find a transaction from the previous month, and clone it. It works, but it involves quite a few clicks.

### Solution

I was wondering if you could spare some time to add a "Pay bill" button. This button would simply create a withdrawal transaction for a bill I have using my template. Each bill has a unique template with tags, price, categories, and the account from which the withdrawal should occur.

Thank you for considering it!

### Additional context

It is not a big deal, so if it is too much work please just close this request

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4917
