### ISSUE TITLE
Budgets: Total available amount always shows $0 for current week

### ISSUE THREAD

**Issue by ryester19** [firefly-iii/firefly-iii#7920]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

For the current week, the total budget available is always showing $0 for the week. The visualization bars also aren't rendered:

![image](https://github.com/firefly-iii/firefly-iii/assets/17807258/bd4d9aa8-2c47-402c-a410-eff9b882960e)

If you go back to the previous week, everything looks to be behaving correctly

![image](https://github.com/firefly-iii/firefly-iii/assets/17807258/899114b3-fb9d-4558-a368-abd11bdeb880)

I believe this is also affecting the Left to Spend box on the dashboard. For the current week, it only shows the amount spent, not the amount left to spend

![image](https://github.com/firefly-iii/firefly-iii/assets/17807258/e03a56a6-5552-4b42-962f-0b19452a8781)

### Debug information

Debug information generated at 2023-09-01 16:03:40 America/New_York for Firefly III version **6.0.22**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.22 |
| Firefly III API | 2.0.7 |
| Build | 630, 01-09-2023 17:55:37 UTC |
| Base Build | 37, 22-08-2023 14:10:40 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/New_York |
| Browser TZ | America/New_York |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-08-28 00:00:00 |
| Session end | 2023-09-03 23:59:59 |
| Session first | 2023-06-30 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0 |

### Expected behaviour

I should be seeing that $100 is available for between August 28th, 2023 and September 3rd, 2023. I should also be seeing on the dashboard in red that I overspent by $17.45 for the week

### Additional info

Below is the only budget I have. As far as I saw, it appears to be working correctly and the cron job is correctly creating a $100 budget every week

![image](https://github.com/firefly-iii/firefly-iii/assets/17807258/a6b421d6-03ed-4def-a53f-384f548815fc)

**Comment by JC5** [comment]
So this happens after the budget has been auto-created, right?

For now, increase the budget with 1, and then decrease it again. That should re-render the bars.

**Comment by ryester19** [comment]
> So this happens after the budget has been auto-created, right?
> 
> For now, increase the budget with 1, and then decrease it again. That should re-render the bars.

That is correct

Modifying the budgeted amount that week by $1 does fix the issue with both the Budgets page and the Left to Spend element on the Dashboard

**Comment by JC5** [comment]
I'm having a hard time replicating this, it works as expected. Could you collect Firefly III logs during Mondays run?

**Comment by ryester19** [comment]
Here are the debug logs from last night

[ff3-cli-2023-09-04.log](https://github.com/firefly-iii/firefly-iii/files/12515825/ff3-cli-2023-09-04.log)

**Comment by JC5** [comment]
Did you recently switch from a monthly view to a weekly view, perhaps?

**Comment by ryester19** [comment]
I might have while playing around at first. Assume that I did

**Comment by JC5** [comment]
Nice, found it. Will be fixed in the next release.
