### ISSUE TITLE
Upgrade 6.0.20 to 6.0.22 local.ERROR: Could not decrypt pub/private keypair.

### ISSUE THREAD

**Issue by Plutoaurus** [firefly-iii/firefly-iii#7921]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Attempting to upgrade from 6.0.20 to 6.0.22 i get 2 error messages.
I have tried using the install script as was used to originally install and the manual way from the docs.

The home page has no formatting when loaded,  tried ctrl+f5 and chmod&chown. I didnt do a full browser clean however. I may be missing something silly as really tired.

### Debug information

[2023-09-01 22:31:48] local.ERROR: Could not decrypt pub/private keypair.  
[2023-09-01 22:31:48] local.ERROR: The MAC is invalid.  

### Steps to reproduce

Follow upgrade instructions under
Created using composer "create-project"

**Comment by JC5** [comment]
The fact that the key doesn't load is annoying but not that big of a deal. You get no formatting, so the CSS doesn't load I guess. What's the value of `<base href="">` in the source of the page?

**Comment by Plutoaurus** [comment]
> The fact that the key doesn't load is annoying but not that big of a deal. You get no formatting, so the CSS doesn't load I guess. What's the value of `<base href="">` in the source of the page?

Correct. No CSS
http://*IP*/firefly-iii/public/

I have fully cleared the browser cache now. The logon page shows ok but when back to /home, no CSS again.

In the page source it links to CSS these, clicking on them takes you to a html page saying URL cannot be found
`"/v1/lib/bs/css/bootstrap.min.css?v=6.0.22"
/v1/lib/fa/css/font-awesome.min.css?v=6.0.22
/v1/lib/adminlte/css/AdminLTE.min.css?v=6.0.22
...`

The lower box on the debug page is also empty

Debug information generated at 2023-09-02 09:05:16 Europe/London for Firefly III version **6.0.22**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.22 |
| Firefly III API | 2.0.7 |
| DB version | 20 (exp. 20) |
| Docker | No |
| PHP | `8.2.9` |
| Host | `Linux` |


| System info | Value |
| --- | --- |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 2097152 (2 MB) |
| Interface | apache2handler |
| Default language | en_GB |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-09-01 00:00:00 |
| Session end | 2023-09-02 23:59:59 |
| Session first | 2009-08-01 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0 |

**Comment by Plutoaurus** [comment]
The CSS url
`view-source:http://*ip*/v1/lib/adminlte/css/AdminLTE.min.css?v=6.0.22`

Is it missing public?

**Comment by JC5** [comment]
That's on me. I'll pick it up!

**Comment by JC5** [comment]
Try installing "dev-main", should fix the issue for now.

**Comment by Plutoaurus** [comment]
Ta.
Not in at the mo but glad it wasnt just me doing something stupid.
I just restore from backup after each test failed so im back on 6.0.20 for now.
