### ISSUE TITLE
Date range selector not working on layout v2

### ISSUE THREAD

**Issue by fnouira** [firefly-iii/firefly-iii#7923]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm trying Layout v2 since v6.0.21 and I noticed that date range selector (top right of the page) is not working. 

Maybe that this is already under developement, but I created ths issue as a reminder.

Thanks

### Debug information

Debug information generated at 2023-09-02 10:55:19 Europe/Paris for Firefly III version **6.0.22**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.22 |
| Firefly III API | 2.0.7 |
| Build | 630, 01-09-2023 17:55:37 UTC |
| Base Build | 37, 22-08-2023 14:10:40 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Paris |
| Browser TZ | Europe/Paris |
| App environment | production |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `172.32.0.254` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-09-01 00:00:00 |
| Session end | 2023-09-30 23:59:59 |
| Session first | 2016-10-14 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

### Expected behaviour

Period may change when we choose a diffrent date range.

### Steps to reproduce

1. Go to home page
2. Select a diffrent date on top right selector
3. nothing happens

### Additional info

There is no debug information on backend side. But when I tried to see the link behind, it was pointing to '/#'.

**Comment by JC5** [comment]
I can't replicate this on the demo site.

**Comment by fnouira** [comment]
I don't have the same dashboard as Demo site.
here is a screenshot of what I see.
![image](https://github.com/firefly-iii/firefly-iii/assets/15313051/ad544201-f1d0-4ad8-9308-2cdf78dfe8e5)

**Comment by JC5** [comment]
Ah, you're running the v2 layout. Was that on purpose? I can't really guarantee things will work as expected unfortunately.

Either way, that also works fine for me. What are the errors in the browser console (ctr-shift-i)?

**Comment by fnouira** [comment]
I'm running v2 layout just for testing purpose :) I will switch back to v1 if it's not guaranteed to work.

For information, nothing happens in browser console neither :(

![image](https://github.com/firefly-iii/firefly-iii/assets/15313051/cd4728ce-01a6-403c-8488-474fd9f685ec)

Thanks for your feedbacks

**Comment by JC5** [comment]
Mmm, thanks. What happens in the console after you switch dates?

**Comment by fnouira** [comment]
yeah, the screenshot was taken after some changes on date range.

**Comment by JC5** [comment]
Thanks. I'll try safari later but I have no Windows unfortunately

**Comment by JC5** [comment]
Sorry, it seems to work fine in Safari (on a Mac as well). Without more details, I'm lost. Sorry about that.

**Comment by fnouira** [comment]
I'm using Brave (Chromium) ...
I will try other browser as well to check if it's related to by browser.

**Comment by fnouira** [comment]
Hello @JC5,
I think I figured out whats happening. Here are some steps to reproduce:
1. After a fresh installation, all is working fine on dashboard screen
2. Navigate to any of other v1 screens (bills for example)
3. Go back to dashbord, and now the selector will not work

I tried to debug using browser's developer tools, and here are my findings:
1. No errors on cosole tab
2. Nothing happening in Network tab
3. I think there is some missing data tags on html like you can see on screenshot below
![image](https://github.com/firefly-iii/firefly-iii/assets/15313051/7144cb0f-f0f5-4c85-921f-31bc69147837)

Hope this is helpful

**Comment by JC5** [comment]
Ah nice, I'll check it out! Thanks for the clarification :+1:

**Comment by JC5** [comment]
Mmmm. All I've spotted so far is that the cache is too strict and the dates can mismatch between v1 and v2. But it works. Tested in Chrome.
