### ISSUE TITLE
Bugets don't show correctly if buguet update per year

### ISSUE THREAD

**Issue by TaoChan1005** [firefly-iii/firefly-iii#7927]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have 2 annual bugets.  Last mounth, I logged some expense and it showed correctly. but this mounth, these bugets don't show 'spent' correctly.

<img width="1194" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/42793494/6236e196-6557-4d79-8bf4-33c21bca217f">

<img width="1192" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/42793494/a30695db-aa97-41a6-aa2f-5d81822613ce">

<img width="744" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/42793494/a8834889-eb45-4ef3-b7cd-3184d7e361de">

### Debug information

Debug information generated at 2023-09-03 14:35:48 Europe/Zurich for Firefly III version **6.0.22**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.22 |
| Firefly III API | 2.0.7 |
| Build | 630, 01-09-2023 17:55:37 UTC |
| Base Build | 37, 22-08-2023 14:10:40 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Zurich |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | remote_user_guard  |
| Headers | REMOTE_USER,   |
| Stateful domains |  |
| Session start | 2023-09-01 00:00:00 |
| Session end | 2023-09-03 23:59:59 |
| Session first | 2023-02-27 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

**Comment by JC5** [comment]
What's incorrect about them? That helps me narrow it down.

**Comment by TaoChan1005** [comment]
I had spent 800+CHF for the travel last month. It shows correctly in the chart, but in the buget page, it still shows 1000CHF(it should be 100+CHF)

**Comment by JC5** [comment]
Is it still wrong after you browse to `/flush`?

**Comment by TaoChan1005** [comment]
yes, It's still wrong. I tried to `ctrl+R` and use private mode~

**Comment by JC5** [comment]
Alright thanks, I'll check it out!

**Comment by JC5** [comment]
Sorry, I'm not going to fix this. This mix of budgets is currently very hard to manage. I'll pick it up for layout `v2`.
