### ISSUE TITLE
Rule names are checked against deleted rules

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#793]
So can't reuse names for deleted rules.

**Comment by nicoschreiner** [comment]
Hey, 

I think the same is true for budgets and categories. 
If you create a budget/category and delete it afterwards, you can't recreate it with the same name. 

I don't know if I should open a new issue or if it is enough to mention it here :)

**Comment by JC5** [comment]
Indeed. I'll pick it up as well!

**Comment by JC5** [comment]
Should be fixed on the demo site.

**Comment by nicoschreiner** [comment]
You are very fast!
Thanks

(btw the demo site is not working currently - there is an error after the log-in)

**Comment by JC5** [comment]
The error is fixed, turns out I forgot an include.

**Comment by nicoschreiner** [comment]
Works! :)

**Comment by JC5** [comment]
Closed to clear the list.
