### ISSUE TITLE
6.0.23 - Lots of links not relative and no graphs.

### ISSUE THREAD

**Issue by Plutoaurus** [firefly-iii/firefly-iii#7932]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Tried 6.0.23 this evening.
CSS now working however there's still alot links etc that are broke due to relative URL.
+ All graphs on the dashboard do not load.
+ debugger page unhappy, top box has lost all forwarding.

Any non expanding side menu links like dashboard,bills etc aren't correct.

Possible need to revert main/stable to 6.0.20.
I know your working hard on v2 but worried about those who aren't as on top of backups and can't revert.

### Debug information

6.0.23
Have reverted to .20 without grabbing this

**Comment by JC5** [comment]
If relative links are broken, your base url is broken too. A little more information please.

**Comment by JC5** [comment]
- For example, what is the `<base href="">` URL and what is it supposed to be? 
- I saw in you're previous issue you're running Firefly III straight from the `/public/` directory. Why?

**Comment by Plutoaurus** [comment]
Base href
http://IP/firefly-iii/public/
Which is correct and now working for css and some links, to open transaction menu on the sidebar for example.

Installed on a self hosted server using guide
https://docs.firefly-iii.org/firefly-iii/installation/self-hosted/
Which puts it in public.

**Comment by JC5** [comment]
So which urls exactly are failing?

**Comment by JC5** [comment]
Thanks for helping me find this. There were some bugs left in 6.0.23 and they will be fixed in the next release.

**Comment by hiltonmw** [comment]
Just wanted to share my experience with this issue, in case it helps with any other potential debugging.

Cheers - and thanks for making a fantastic product.
