### ISSUE TITLE
Reconciliation always shows different amount of money

### ISSUE THREAD

**Issue by mgorfer** [firefly-iii/firefly-iii#7933]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When doing a reconciliation, even though the difference is 0, Firefly always tells me, that the amount of money in my bank account is different from the amount in Firefly.

![image](https://github.com/firefly-iii/firefly-iii/assets/13124998/ff3092ab-c376-4117-9f8b-566502216783)

Additionally, the value on the right also does not show 0, even though it is displayed in the overview.
![image](https://github.com/firefly-iii/firefly-iii/assets/13124998/fa44af7d-c0e3-4ce7-99cb-7554d217324d)

### Debug information

Debug information generated at 2023-09-05 10:01:31 Europe/Vienna for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| Build | 597, 17-08-2023 10:06:07 UTC |
| Base Build | 35, 30-07-2023 03:52:37 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Vienna |
| Browser TZ | Europe/Vienna |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-09-01 09:32:49 |
| Session end | 2023-09-30 09:32:49 |
| Session first | 2021-11-15 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

**Comment by JC5** [comment]
Make a backup of your database, and then run this command: `php artisan firefly-iii:force-decimal-size`.

**Comment by mgorfer** [comment]
That worked perfectly. Thank you!

**Comment by JC5** [comment]
Glad to hear it!
