### ISSUE TITLE
Issues with the Oauth keys

### ISSUE THREAD

**Issue by TimGoll** [firefly-iii/firefly-iii#7934]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When trying to do anything I always run in an issue with the public/private keys used in firefly: `Internal Firefly III Exception: Unable to read key from file file:///home2/<user_name>/_subdomains/firefly/storage/oauth-public.key`

### Debug information

Debug information generated at 2023-09-05 10:49:14 Europe/Amsterdam for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| DB version | 20 (exp. 20) |
| Docker | No |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 2097152 (2 MB) |
| Interface | litespeed |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-09-01 00:00:00 |
| Session end | 2023-09-30 23:59:59 |
| Session first | 2023-09-04 13:28:35 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

### Expected behaviour

I installed the tool via the Softaculous app installed provided by my hoster. It is installed to its own subdomain. So it is firefly.domain.de, not domain.de/firefly. Softaculous says they provide no support and the issue is on your side, so I hope you're able to help me here.

The issue that pops up everywhere is the following: `Internal Firefly III Exception: Unable to read key from file file:///home2/<user_name>/_subdomains/firefly/storage/oauth-public.key`

If I navigate to this file to try to check its contents I can see that they are empty besides one line with `[private key]` and `[public key]`. Nothing else.

I tried googling this issue and every forum post about laravel passport mentions the following command: `php artisan passport:install`. But I can't run this as I don't have any terminal access on my webspace.

### Steps to reproduce

1. Install FireflyIII via Softaculous
2. Try to do anything

**Comment by JC5** [comment]
Mmm, tricky. The file can't be ready by Firefly III even though it's obviously there. What did your hoster say about the error? Do you have access to the folder when you browse to Firefly III?

**Comment by TimGoll** [comment]
I have full file access and can open them via FileZilla. Is that what you mean?

I did not contact my hoster. But I will try it if you think this is the best approach

**Comment by TimGoll** [comment]
Ah and about this:

> The file can't be ready by Firefly III even though it's obviously there

Maybe the issue is that the content of said file is just `[public key]` without an actual public key?

**Comment by JC5** [comment]
Wait the file says literally `[public key]`? I thought you censored that bit.

Delete the files, then visit Firefly III. What happens then?

**Comment by TimGoll** [comment]
A new file is created with the same content:

![image](https://github.com/firefly-iii/firefly-iii/assets/13639408/212b075f-67c5-40f6-93f7-a2f567a66679)

Nothing is censored here, this is the full file as it is generated for me. I will take a look at the logs, give me a moment

**Comment by JC5** [comment]
Weird. Do you have access to the database?

**Comment by JC5** [comment]
Check the table preferences. There should be a reference to the "oauth_private_key" (check the name column). What is the content of that field? Also `[[private key]]`?

**Comment by TimGoll** [comment]
I might be blind, but it seems to be missing:

![image](https://github.com/firefly-iii/firefly-iii/assets/13639408/78c70e8c-8b95-48a3-8d43-cc31f756c318)

**Comment by JC5** [comment]
My apologies, check out table `configuration` for the same.

**Comment by TimGoll** [comment]
There are keys

**Comment by JC5** [comment]
The text `[[public_key]]` is not mine and I guess its inserted by some kind of security scanner or something? The content of the file should just the key itself (from the database).

What you can try is to delete the files, also delete the two entries from the database and then visit Firefly III. It should generate (a) new key files on disk and (b) new entries in the database.

**Comment by TimGoll** [comment]
okay, the key file is now regenerated and actually looks like a key file. Nice. However I now get another error and I'm not sure if it is related or not:

![image](https://github.com/firefly-iii/firefly-iii/assets/13639408/20d69092-dcaa-4aa8-88f5-1be17136e74b)

**Comment by TimGoll** [comment]
Ah nevermind, it works now. I don't know why, maybe I needed a hard reload of the page and it was some caching issue? Thanks alot! I'd never have solved that myself

**Comment by JC5** [comment]
Not a problem! Keep me posted. I'm curious if it'll keep working 😅

**Comment by TimGoll** [comment]
I'm not sure if this is the right place to ask, but is there a way to use an older (hosted) version of the data importer? Because the Softaculous version always lags a few versions behind and is therefore incompatible with your hosted importer

**Comment by JC5** [comment]
Yes, if you use Docker you could use it yourself, it's not that complex to run.

**Comment by TimGoll** [comment]
Well then I will probably give it a go, thanks :)

**Comment by TimGoll** [comment]
I will give it a go sometime this week!
