### ISSUE TITLE
Balance in 'Amount due' in Liabilities is incorrect in some cases

### ISSUE THREAD

**Issue by krkadel** [firefly-iii/firefly-iii#7938]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Balance in 'Amount due' in Liabilities is incorrect in some cases, however, the 'accounts/show/' view the balance is correct.
See this example
This image is showing wrong balance (actually double the amount transacted)
![image](https://github.com/firefly-iii/firefly-iii/assets/26329436/af53cda3-09d5-49f6-b5ec-94db57b327ed)

This image shows correct balance
![image](https://github.com/firefly-iii/firefly-iii/assets/26329436/076e8fa0-b23c-4430-9d23-4ec1354d9ea5)

### Debug information

Debug information generated at 2023-09-06 16:51:13 for Firefly III version **v6.0.23**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.23 / v2.0.7 / 20(exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.4 / fpm-fcgi / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>52428800 (50 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Asia/Kathmandu + Asia/Katmandu</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td>https://finance.krk.com.np</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:credit_card: :wrench: :email:</td></tr><tr><td>Session start</td><td>2023-09-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-09-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The amount in liabilities (Accounts>Liabilities) page should be corrected. 
The calculation in liabilities show page (clicking on the liability account) is correct.

### Steps to reproduce

I had done some transactions of taking loan and repaying, after the repayment, the loan amount shows double the balance in liabilities page.

**Comment by JC5** [comment]
Could you please do the following?

1. [Enable debug mode](https://docs.firefly-iii.org/firefly-iii/faq/other/#how-do-i-enable-debug-mode) 
2. Run the following command on the command line: `php artisan firefly-iii:trigger-credit-recalculation`
3. Send me the logs over email (james@firefly-iii.org)

This will help me debug further. Thanks!

**Comment by phillippe** [comment]
I'm experiencing the same issue and it seems to only happen when "Liability in/out" is set to "I owe this debt to somebody else". Switching it to "I am owed this debt" seems to correct the balance (albeit negated).

**Comment by JC5** [comment]
Could you please open another ticket and include debug information?

**Comment by JC5** [comment]
Thanks to @Panzer1119's debug information, I believe this is now fixed. You can test this in the `develop` branch and `develop` tag.
