### ISSUE TITLE
Cashflow in Reports

### ISSUE THREAD

**Issue by naxels** [firefly-iii/firefly-iii#7939]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Cashflow to me is income - expenses for a given period, like the Dashboard balance shows when looking at a month's view.

Currently I cannot see this cashflow/balance on the reports, for example:
http://localhost/reports/default/1,2/currentYearStart/currentYearEnd

only shows the Earned/Spend in the chart and the Net Worth, but doesn't show the cashflow in a chart.

Sample where I miss it from the above report:
<img width="181" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/3195443/b8534e55-5568-449c-81b2-7e4765046af3">

### Solution

It would be wonderful if I'm able to view the cashflow per period in the data/charts on the default report (can't find a report that shows the cashflow, only the earned/spent). Another idea would be to add a seperate chart like Net Worth for cashflow and show it per period (like month for the default report in the description above).

### What are alternatives?

Look at the Dashboard and browse the 'balance' box month by month (my interest) to see the cashflow.

### Additional context

Thank you and keep up the good work :)

**Comment by JC5** [comment]
Sounds like a great idea! I'm going to lump this in with https://github.com/firefly-iii/firefly-iii/issues/6310 :+1:
