### ISSUE TITLE
Bad request when creating a recurring transaction

### ISSUE THREAD

**Issue by edersong** [firefly-iii/firefly-iii#7941]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi

I'm trying to create a recurring transaction. As soon I enter the form to create a recurring transaction, I get an alert about inability to load repetition suggestions. The error message is "Could not load repetition suggestions".
Noted that, even the DEFAULT_LANGUAGE and DEFAULT_LOCALE are set to pt_BR, the first date format is in en_US.

### Debug information

Tried changing DEFAULT_LANGUAGE and DEFAULT_LOCALE to es_ES or en_US but the error is still being reported.

Tried to reproduced on the demo server, but worked fine there.
Noted that demo server has Locale settings and mine not, even we are running the same version.

Here is a screenshot of the UI 
![image](https://github.com/firefly-iii/firefly-iii/assets/64137913/068964b5-b3b7-4944-9bc8-215f7248d173)
![image](https://github.com/firefly-iii/firefly-iii/assets/64137913/79417d18-f084-4f5e-99e9-e41bdd92ea66)
![image](https://github.com/firefly-iii/firefly-iii/assets/64137913/2e9ebee3-5e27-4e81-aa56-ebd01c4d20c3)

### Additional info
Container's locale output:
`
root@app:/var/www/html# locale -a
C
C.UTF-8
POSIX
bg_BG.utf8
ca_ES.utf8
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
el_GR.utf8
en_GB.utf8
en_US.utf8
es_ES.utf8
fi_FI.utf8
fr_FR.utf8
hu_HU.utf8
id_ID.utf8
it_IT.utf8
ja_JP.utf8
nb_NO.utf8
nl_NL.utf8
nn_NO.utf8
pl_PL.utf8
pt_BR.utf8
pt_PT.utf8
ro_RO.utf8
ru_RU.utf8
sk_SK.utf8
sl_SI.utf8
sv_SE.utf8
tr_TR.utf8
uk_UA.utf8
vi_VN.utf8
zh_CN.utf8
zh_TW.utf8
`

The issue started after last version upgrade.

**Comment by JC5** [comment]
Could you share the error from the logs and the output of the /debug page please?

**Comment by edersong** [comment]
Sure:

Debug information generated at 2023-09-08 14:39:58 for Firefly III version **v6.0.23**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.23 / v2.0.7 / 20(exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.9 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>636, base <span>#</span>37</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Madrid + Europe/Madrid</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>pt_BR + pt_BR</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:pig: :wrench: :clock130: :email:</td></tr><tr><td>Session start</td><td>2023-09-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-09-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>pt_BR</td></tr><tr><td>User locale</td><td>pt_BR</td></tr><tr><td>Locale(s) supported</td><td>pt_BR.utf8: :white_check_mark:<br>pt_BR.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36</td></tr></tbody></table>

**Comment by JC5** [comment]
And the error?

**Comment by edersong** [comment]
It didn't report any error, just a pop-up saying: "Could not load repetition suggestions. Please enter a valid date." and, after clicking OK, anything that I want to do on that page, the pop-up come back.

**Comment by JC5** [comment]
I expect your Docker container to report something when this happens. Could you check that?

**Comment by edersong** [comment]
From firefly docker:

09/08/2023 4:31:50 PM 192.168.xx.xx - - [08/Sep/2023:16:31:50 +0200] "GET /recurring HTTP/1.1" 200 8918 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
09/08/2023 4:31:50 PM 192.168.xx.xx - - [08/Sep/2023:16:31:50 +0200] "GET /v1/jscript/variables?ext=.js&v=6.0.23 HTTP/1.1" 200 3355 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
09/08/2023 4:31:52 PM 192.168.xx.xx - - [08/Sep/2023:16:31:51 +0200] "GET /recurring/create HTTP/1.1" 200 9733 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
09/08/2023 4:31:52 PM 192.168.xx.xx - - [08/Sep/2023:16:31:52 +0200] "GET /v1/jscript/variables?ext=.js&v=6.0.23 HTTP/1.1" 200 3355 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

From DB:
09/08/2023 2:31:59 PM 2023-09-08 12:31:59 8648 [Warning] Aborted connection 8648 to db: 'unconnected' user: 'unauthenticated' host: '192.168.96.3' (This connection closed normally without authentication)

**Comment by JC5** [comment]
Thanks! What's the error in the browser console?

**Comment by edersong** [comment]
Just it:

![image](https://github.com/firefly-iii/firefly-iii/assets/64137913/c1192cea-26f0-4ccb-a1ac-f9dc955c4ba6)

**Comment by JC5** [comment]
Press ctrl shift I. I'm curious what Firefly III is trying to do.

**Comment by edersong** [comment]
The error is:

app.js?v=6.0.23:2 Mixed Content: The page at 'https://firefly.mysite.com/recurring/create' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://firefly.mysite.com/recurring/suggest?date=2023-09-09&pre_select=&past=true'. This request has been blocked; the content must be served over HTTPS.

I'm running it Nginx Proxy Manager and Cloudflare Tunnel so disabled Force SSL option on NPM and it worked locally but externally I get "too many redirects" with that option disabled.
The root cause is that https://firefly.mysite.com/recurring/create page is under http:// only.

**Comment by JC5** [comment]
Alright so that's a configuration error, check out the discussions tab, more people seem to struggle with this. There was somebody recently with something similar.

**Comment by edersong** [comment]
Found a fix for it:
In Cloudflare Dashboard, website (the domain I have listed in cloudflare) > rules > page rules > create new rule > SSL: full or SSL: full strict.
With this setting, I can maintain Force SSL enabled in NPM and all is working fine.
Thank you for your guidance to solve the issue.

**Comment by edersong** [comment]
Found a fix for it:
In Cloudflare Dashboard, website (the domain I have listed in cloudflare) > rules > page rules > create new rule > SSL: full or SSL: full strict.
With this setting, I can maintain Force SSL enabled in NPM and all is working fine.
Thank you for your guidance to solve the issue.
