### ISSUE TITLE
Swagger API docs: Wrong type in some cases

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7944]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I guess due to the weak typing of PHP, some fields the API outputs are not according to the Swagger docs. This breaks strongly typed apps. The following are a couple of examples I found:

- Object `AutocompleteAccount`, field `currency_id`: Returned as int, not string
- Object `CategoryEarned`, field `currency_id`: Returned as int, not string
- Object `CategorySpent`, field `currency_id`: Returned as int, not string
- Object `TransactionSplit`, field `recurrence_id`: Returned as string, not int

`currency_id` is mostly a string everywhere else, so I guess changing the couple of instances to String is more consistent. Recurrence IDs are returned as strings in the `/v1/recurrence/` calls (and listed in the API as such in `RecurrenceRead`), so I guess that is rather a swagger api mistake.

### Debug information

Current Demo Page

### Additional info

Reporting as a bug here instead of in https://github.com/firefly-iii/api-docs-generator/ as the first examples require a code change to return the most likely expected type.

**Comment by JC5** [comment]
Nice find. Those should all be strings indeed. I shall pick them up. If you find more of them, let me know!
