### ISSUE TITLE
Foreign Currency Ignored in Transfer between Asset Accounts 

### ISSUE THREAD

**Issue by thiagobell** [firefly-iii/firefly-iii#7947]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have two asset accounts (both in euros). When I try to create a transfer between them with some foreign currency amount, this amount is just ignored.

The only related issue I could find is #7125. 

<img width="676" alt="Screenshot 2023-09-10 at 17 41 26" src="https://github.com/firefly-iii/firefly-iii/assets/4528857/53aba0a8-ed33-4109-bb7c-a893902db9c8">

### Debug information

Debug information generated at 2023-09-10 17:40:34 for Firefly III version **v6.0.23**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.23 / v2.0.7 / 20(exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.9 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>636, base <span>#</span>37</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>notice, daily / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_GB + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:pig: :ledger: :wrench: :clock130: :bookmark_tabs: :email:</td></tr><tr><td>Session start</td><td>2023-09-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-09-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The created transaction should contain the foreign amount

<img width="676" alt="Screenshot 2023-09-10 at 17 42 04" src="https://github.com/firefly-iii/firefly-iii/assets/4528857/403ea9dd-d294-4913-b082-0ac9e7d492a2">

### Steps to reproduce

POST /api/v1/transactions

{
  "transactions": [
    {
      "amount": "2.1",
      "description": "a transaction",
      "currency_code": "EUR",
      "destination_id": "68",
      "source_id": "1",
      "type": "transfer",
      "date": "2023-09-10T17:15:35.415996",
      "foreign_amount": "1.98",
      "foreign_currency_code": "GBP"
    }
  ]
}

### Additional info

Once I set the source and destination accounts in the create transaction form, it only allows me to pick Euros as foreign currency. However, once the transaction is created, I can modify the foreign currency and the corresponding amount freely.

**Comment by JC5** [comment]
What's your use case for wanting to do this?

**Comment by thiagobell** [comment]
The use case is if I make a purchase denominated in currency B with my bank card whose account is denominated in currency A. The idea here is to keep some information about the underlying currency exchange

**Comment by JC5** [comment]
But you said it's a transfer?
