### ISSUE TITLE
Missing date period selector

### ISSUE THREAD

**Issue by divvet** [firefly-iii/firefly-iii#795]
Hi,

Just updated to FFIII 4.6.4 and PHP 7.1 and noticed that the date period selector is missing(usually in the top right is missing) Not sure if I have missed out a PHP module or whether this is a bug. 

Any help would be appreciated.

**Comment by JC5** [comment]
Do ctrl-F5, the Javascript has changed and the old version might still be in your cache.

**Comment by divvet** [comment]
Yeah just logged in and found it had re-appeared. Sorry to waste your time 👍

**Comment by JC5** [comment]
No problem! Happy to help :)
