### ISSUE TITLE
Support ordering rules

### ISSUE THREAD

**Issue by eliasp** [firefly-iii/firefly-iii#7957]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I have created a quite long list of rule triggers to assign a certain budget based on the name of the destination account.
To reduce the potential for confusion and ease future maintenance of the list, I added the triggers alphabetically.

Two things turned out to be impossible (without recreating everything from scratch):
- add a trigger to the top of the list, which stops further processing if the source account doesn't match an expected value
- add a trigger at a certain position of the list to keep it maintainable by keeping the alphabetic order of conditions (destination account name)

### Solution

Allow to re-order the triggers (and maybe also the actions) comparable to how it is already possible for the accounts.

### What are alternatives?

Manually deleting all triggers and re-creating them from scratch.

**Comment by JC5** [comment]
I can't remember if it still works (and I can't test it right now) but in the rules index (/rules) you used to be able to drag and drop individual triggers. 

If this is no longer the case I'm afraid I won't be able to fix it though. I will keep it on my list for the new release. 

The database supports this though, so if you're hacky enough you can edit the database yourself.

**Comment by eliasp** [comment]
Thanks a lot for the feedback!
This works for the `/rules` index, but I'm looking to do it for within the rule itself (when editing it, e.g. `/rules/edit/5`) to re-order triggers and actions.

**Comment by JC5** [comment]
I know what you mean, but right now this is not available. I hope to reinstate this in the new layout, but this will be some time.
