### ISSUE TITLE
Best practices for creating a test/dev install.  

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#796]
Hello,

I was wondering which steps I could do to create a test install against the dev branch?

My guess was that I could use the instructions published when there was an alternate install method.  (Git without composer create project) 

Could you provide some info?

**Comment by JC5** [comment]
The easiest way to go about this is the following, I think.

`git checkout https://github.com/firefly-iii/firefly-iii.git`
`git checkout develop`
`cp .env.example .env`
`composer install`
`php artisan key:generate`

Edit the .env file to contain your database things. Then run

` php artisan migrate:refresh --seed`

**Comment by JC5** [comment]
I'm assuming you got it? :P

**Comment by leander091** [comment]
Yes, thanks for the information
