### ISSUE TITLE
Link a deposit to a bill

### ISSUE THREAD

**Issue by maxicasa** [firefly-iii/firefly-iii#7964]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Sometimes I need to associate a deposit to a bill.
For example when a I received a refund from bill company (ex. wrong payments or other issue).
At the moment, I have not found how to link a deposit to a bill. The only type of transaction with a bill link is the withdrawal. 

### Solution

Add a `bill` field in the Deposit view (when click edit on a transaction) as in the Withdrawal view.

**Comment by JC5** [comment]
Sorry no, this will not be added. Bills are tracked by withdrawals, I'm not going to make it more complicated than that.
