### ISSUE TITLE
DateRange preset "last year"

### ISSUE THREAD

**Issue by psi-4ward** [firefly-iii/firefly-iii#7966]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

UseCase: One needs to lookup transactions for ie tax application. In this case the date-range of the full previous year must be selected which is not very comfortable right now. 

### Solution

Add a "last year" preset to the DateRange component.

**Comment by JC5** [comment]
You can set the view range to "yearly" and then browse one year back.

**Comment by psi-4ward** [comment]
Sounds perfect, could you give me a hint where I can find it?

**Comment by JC5** [comment]
In your preferences under layout.
