### ISSUE TITLE
Missing transaction search on mobile

### ISSUE THREAD

**Issue by qck4fun** [firefly-iii/firefly-iii#7968]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When opening Firefly on a mobile phone I cannot search through transactions because the input field is missing. I've tested it in a browser simulating phone (iphone 12 pro) and it's not there, but when switching for example to iphone 12 pro max then the input field reappears.

I believe it has something to do with device's width only.. maybe it's a feature to not show it on smaller devices, but I was used to conveniently search through and now I can't :cry: 

### Debug information

Debug information generated at 2023-09-15 17:10:33 for Firefly III version **v6.0.23**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.23 / v2.0.7 / 20(exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.9 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>636, base <span>#</span>37</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Prague + Europe/Prague</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>info,/ (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:wrench: :bookmark_tabs: :email:</td></tr><tr><td>Session start</td><td>2023-09-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-09-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0</td></tr></tbody></table>

### Expected behaviour

Transaction search input field is visible and usable for searching through transactions even on smaller devices

### Steps to reproduce

1. open browser with your firefly instance
2. go to web developer tools
3. switch to responsive design mode
4. check left side menu when on iphone 12 pro vs. iphone 12 pro max for example

**Comment by JC5** [comment]
Yea sometimes there's just no room. Browse to /search instead :)

**Comment by ShanSanear** [comment]
But there was room for this in one of the earlier versions, without any changes to the UI in the meantime. I think last time I saw it was with 6.0.18.  
![image](https://github.com/firefly-iii/firefly-iii/assets/8857417/05359dea-d3b9-49b0-a269-734779ff7dc6)
If I remember correctly it was between "Dashboard" and "Financial control". Sure, not too much room for it but it was there to use, which is just easier than browsing to specific endpoint (to which to there is no link, and on mobile it is a bit harder).
Granted, rotating phone to landscape mode works, but then typing is more awkward.

Would it be possible in that case to at least have search button to quickly navigate to it?

**Comment by JC5** [comment]
Sorry, I'm not going to hack away in this layout anymore. I've been over promising and under delivering the new layout for plenty of time now, so that's what I'm going to focus on first.
