### ISSUE TITLE
Web interface removes date accuracy - loss of time

### ISSUE THREAD

**Issue by qstorey** [firefly-iii/firefly-iii#7969]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Firstly, thanks for maintaining firefly-iii.

I'm running into an issue where the time information is stripped from the transaction.

When you create a transaction via the REST API it is possible to specify the date and time for a transaction. However, if you update another attribute about the transaction via the web interface then the date remains but the time is set to 00:00:00.

### Debug information

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.23 / v2.0.7 / 20(exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.9 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, pgsql, <strong>*sqlite*</strong>, </td></tr><tr><td>Docker build</td><td><span>#</span>636, base <span>#</span>37</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Amsterdam</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>info,/ (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>*</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:pig: :ledger: :wrench: :bookmark_tabs: :email:</td></tr><tr><td>Session start</td><td>2023-08-21 00:00:00</td></tr><tr><td>Session end</td><td>2023-09-20 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0</td></tr></tbody></table>

### Expected behaviour

If I update any field on a transaction (besides the date field) then I would except the date field on the transaction not to be modified.

### Steps to reproduce

1. Create a transaction via the API
```bash
 curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $FIREFLY_ACCESS_TOKEN" https://<REDACTED>/api/v1/transactions -d '{"transactions": [{"type": "withdrawal","date": "2023-09-15T08:58:00+02:00","amount": "18", "description": "lidl", "source_id": "1", "destination_name": "Lidl"}]}'
```
2. Edit the transaction via the web interface. For example change the description.
3. Use the web interface to view the transaction details and look at the audit log entries block.

Audit log entries
Updated transaction date : September 15th, 2023, @ 08:58:00 → September 15th, 2023, @ 00:00:00

**Comment by JC5** [comment]
Yes, I'm aware. I do not consider this to be a bug. I'm working on a new layout where this is not an issue. Many API features are not supported by the current layout.

**Comment by webtroter** [comment]
@JC5 , we need a fix for this please.

It is a bug because everything works correctly with the time in the date field, only the web page client is problematic. Waterfly III works fine, Abacus works fine, the an API Client works fine.

The web page shouldn't remove something the user didn't ask for.

The date field shouldn't be edited if we didn't change it.

Can we maybe just get a checkbox on the edit page to indicate that we want the date updated. If not, DO NOT TOUCH the date field.
I added `r.transactions.forEach( t => delete t.date)` just after `var r=this.convertData()` in the submit method of the `edit_transaction.js` file. It seems to work, but its not super.

It's really annoying. I take time to enter my transactions on my apps (with the time so they are in the correct order), but when I use the web page to edit this transaction, we lose data.
