### ISSUE TITLE
Editi multiple transactions (or single) ends with wrong directed URL

### ISSUE THREAD

**Issue by plumped** [firefly-iii/firefly-iii#7970]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The forwarding for editing expenses dont work anymore.

### Debug information

Debug information generated at 2023-09-16 14:05:59 for Firefly III version **v6.0.24**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.24 / v2.0.8 / 20(exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.9 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>652, base <span>#</span>37</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Zurich + Europe/Zurich</td></tr><tr><td>App environment</td><td>local, debug: true</td></tr><tr><td>Logging</td><td>debug, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:wrench:</td></tr><tr><td>Session start</td><td>2023-09-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-09-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0</td></tr></tbody></table>

### Expected behaviour

Forward correct URL

### Steps to reproduce

1. Expenses
2. Select multiple 
3. Choose "Actions" in the Top
4. Edit single / multiple entries

forwards to https://xyz.comhttps//xyz.com/transactions/mass/edit/1540,1537

instead of just https//xyz.com/transactions/mass/edit/1540,1537

**Comment by JC5** [comment]
Nice find, I'll pick it up!
