### ISSUE TITLE
Bulk editing of transactions do not work

### ISSUE THREAD

**Issue by dtirer** [firefly-iii/firefly-iii#7971]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When i select several Expenses in the Transactions category, and then choose an option from the bulk actions menu like "Deleted Selected (x)", the URL redirect is formatted incorrectly.  

For example, if my firefly container is served at `https://app.firefly.com`, and I click the above listed action, it attempts to redirect to `https://app.firefly.comhttps://app.firefly.com/transactions/bulk/edit/x,y,z,a,b,c`

### Debug information

Debug information generated at 2023-09-18 04:38:41 for Firefly III version **v6.0.24**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.24 / v2.0.8 / 20(exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.9 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>652, base <span>#</span>37</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + UTC</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:email:</td></tr><tr><td>Session start</td><td>2023-06-01 04:26:16</td></tr><tr><td>Session end</td><td>2023-06-30 04:26:16</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/117.0</td></tr></tbody></table>

### Expected behaviour

It should redirect to the requested URL rather than appending that URL to current URL

### Steps to reproduce

1. navigate to Transactions -> Expenses
2. select 2 or more items in the list using the check-boxes
3. from the bulk "actions" button menu, select any one of the options (like "Deleted selected (x)")

### Additional info

I experience the same behavior on the demo site

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/7970
