### ISSUE TITLE
Amount due of "I owe this"-Liabilities is incorrect in some cases

### ISSUE THREAD

**Issue by Panzer1119** [firefly-iii/firefly-iii#7972]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The "Amount due" of a liability (where i owe money to someone else) is going down when i borrow money, but it is also going down when i pay back money.
The balance on the other hand is showing the correct value.

I checked it on the demo instance and it also shows the wrong value.

### Debug information

Debug information generated at 2023-09-18 10:34:07 for Firefly III version **v6.0.24**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.24 / v2.0.8 / 20(exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.9 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>652, base <span>#</span>37</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: true</td></tr><tr><td>Logging</td><td>debug, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:credit_card: :pig: :wrench: :clock130: :bookmark_tabs: :email:</td></tr><tr><td>Session start</td><td>2023-09-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-09-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The amount due calculation should treat a withdrawel from an asset account to the Liability as a positive value and not subtract it.

### Steps to reproduce

1. Create a "I owe this debt to somebody else"-Liability
2. Create a deposit from the liability to an asset account (when i create a Transfer from the liability to an asset account it automatically makes a Deposit out of it)
3. Create a withdrawel from an asset account to the liablity (when i create a Transfer from an asset account to the liability it automatically makes a Withdrawal out of it)
4. See balance adding both up correctly, but amount due shows the (negative) sum of the absolute values

### Additional info

This relates to firefly-iii/firefly-iii#7938.

I ran the command @JC5 suggested [here](https://github.com/firefly-iii/firefly-iii/issues/7938#issuecomment-1708152014): `php artisan firefly-iii:trigger-credit-recalculation`

```
[2023-09-18 10:35:24] local.DEBUG: Now processing account #210 ("Loan - I owe someone Money")
[2023-09-18 10:35:24] local.DEBUG: Start of debt is "0", so initial left of debt is "0"
[2023-09-18 10:35:24] local.DEBUG: Debt direction is "debit"
[2023-09-18 10:35:24] local.DEBUG: Found 2 transaction(s) to process.
[2023-09-18 10:35:24] local.DEBUG: [1/2] Processing transaction.
[2023-09-18 10:35:24] local.DEBUG: Left of debt is: 0
[2023-09-18 10:35:24] local.DEBUG: Amount of transaction is -500.000000000000000000000000
[2023-09-18 10:35:24] local.DEBUG: Case X (all other cases): 0 + -500.000000000000000000000000 = -500.000000000000
[2023-09-18 10:35:24] local.DEBUG: [2/2] Processing transaction.
[2023-09-18 10:35:24] local.DEBUG: Left of debt is: -500.000000000000
[2023-09-18 10:35:24] local.DEBUG: Amount of transaction is 100.000000000000000000000000
[2023-09-18 10:35:24] local.DEBUG: Case X (all other cases): -500.000000000000 + -100.000000000000 = -600.000000000000
[2023-09-18 10:35:25] local.DEBUG: Done processing account #210 ("Loan - I owe someone Money")
```

And it correctly sees the value of the payback transaction `Amount of transaction is 100.000000000000000000000000`~~, but then uses it's negative in the calculation: `-500.000000000000 + -100.000000000000`~~.

#### Diving into the code

I looked a little bit into the code and it seems `Case X` is always negating the `$usedAmount`: https://github.com/firefly-iii/firefly-iii/blob/88c145ac3eab4c7f90d68e1fce26cd1e6c7c7737/app/Services/Internal/Support/CreditRecalculateService.php#L336-L342

So that's why it negated the `100`, but then why is the first transaction not negated?
`Amount of transaction is -500.000000000000000000000000` -> `0 + -500.000000000000000000000000`

**Comment by JC5** [comment]
I'm going to merge this with an earlier ticket: https://github.com/firefly-iii/firefly-iii/issues/7938

With your debug details I should be able to solve this, thanks for the extensive ticket!
