### ISSUE TITLE
API: v1/transactions GET end not respected

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7974]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The "end" parameter of the v1/transaction GET query is not respected.

As you disabled cURL for the demo site, here a quick screenshot from the API doc site :D

![image](https://github.com/firefly-iii/firefly-iii/assets/109872040/bed957ff-5e76-454f-a8e9-9f9dbc21e0d0)

See "date" of the first shown result being 2023-09-20, but the requested "end" is 2023-09-18.

### Debug information

Demo Page

### Additional info

Reported by @zynexiz in https://github.com/dreautall/waterfly-iii/issues/144

**Comment by JC5** [comment]
That's weird, the code is so basic. I'll check it out!

And yes the curl user agent is blocked but it's easy to circumvent :wink:

**Comment by JC5** [comment]
API 2.0.9 (next release) should respect this. In all earlier API's, a start date needs to be present, even if it's 1900-01-01.
