### ISSUE TITLE
Getting 403'd While Checking for Available Upgrades

### ISSUE THREAD

**Issue by paulcalabro** [firefly-iii/firefly-iii#7976]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When clicking on the button to check for available updates, I'm seeing the following error message:

```
 Error! Guzzle: Client error: `GET https://version.firefly-iii.org/index.json` resulted in a `403 Forbidden` response: Just a moment... 
 ```

### Debug information

Debug information generated at 2023-09-19 08:49:32 for Firefly III version **v6.0.24**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.24 / v2.0.8 / 20(exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.9 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>652, base <span>#</span>37</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Phoenix + America/Phoenix</td></tr><tr><td>App environment</td><td>local, debug: true</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>192.168.128.0/16</td></tr><tr><td>Login provider & user guard</td><td>eloquent / remote_user_guard</td></tr><tr><td>Login headers</td><td>Remote-Email + </td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:credit_card: :pig: :bookmark_tabs: :email:</td></tr><tr><td>Session start</td><td>2023-09-12 00:00:00</td></tr><tr><td>Session end</td><td>2023-09-19 23:59:59</td></tr><tr><td>View range</td><td>last7</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0</td></tr></tbody></table>

### Expected behaviour

The app tells me if there's an available error message or not.

### Steps to reproduce

1. Click Options -> Administration -> Check for updates -> "Check Now!"

### Additional info

I'm also seeing this response via curl from my server hosted in AWS:

```
# curl https://version.firefly-iii.org/index.json -I 2>/dev/null | grep HTTP
HTTP/2 403
```

Other requests seem to work fine:

```
# curl https://www.example.com -I 2>/dev/null | grep HTTP
HTTP/2 200
```

If I try locally, those work fine as well:

```
 $ curl https://version.firefly-iii.org/index.json -I 2>/dev/null | grep HTTP
HTTP/2 200
```

The returned HTML from the 403'd response is:

```
<!DOCTYPE html>
<html lang="en-US">

<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
</head>

<body class="no-js">
    <div class="main-wrapper" role="main">
        <div class="main-content"><noscript>
                <div id="challenge-error-title">
                    <div class="h2"><span class="icon-wrapper">
                            <div class="heading-icon warning-icon"></div>
                        </span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div>
                </div>
            </noscript></div>
    </div>
    <script>(function () { window._cf_chl_opt = { cvId: '2', cZone: "version.firefly-iii.org", cType: 'managed', cNounce: '13326', cRay: '809308b67808c5a4', cHash: '68843ee5cb69a9a', cUPMDTk: "\/index.json?__cf_chl_tk=H56iu8Qnwc0ievc1RqHk7SbXoXpTuHwA1o4gzXD46gQ-1695139147-0-gaNycGzNCpA", cFPWv: 'b', cTTimeMs: '1000', cMTimeMs: '0', cTplV: 5, cTplB: 'cf', cK: "visitor-time", fa: "\/index.json?__cf_chl_f_tk=H56iu8Qnwc0ievc1RqHk7SbXoXpTuHwA1o4gzXD46gQ-1695139147-0-gaNycGzNCpA", md: "0mwOGgJSWG4wcLQBcQZj9IGk7HdAOlimIr8HUkSQsyM-1695139147-0-AVT4AIsXM0zuvFEum70QZ48FlOoX7ESiR9JiUOE3jfInUv-5iB40XcCu4vR3GEOr73Dftwhu-jkB6A7XnJgkid5NdxJuoWawzCtUq0ES9hjeXWjj_iEr2hlJpjKj5Al-ppsS4I4u859n0xn-_sVlNbRbxB4V9nmMgB_rycU1ymUvQR4JSoLiQYohxIplGae_6rP_QaBa1YwgVChmjnC8GZrW7LGya0yqmQQviV9DVn3jNC91fsT5wfcituT8OT64LRheEKueIh0fSFkk7jslFMD8CEButdBQNwmDHnkFq1pE1n0BYQuPmtwPiH3tnmGWkooGfUUZHmwPID783aR-LaFNTyST8uevwQw8aVXnw1YwuGktlh1dqw2GScxEl83hc0XC9n8HWYPsaQtxvIm20jBTdGzf33M5pfoIUbPstmkZ82yBql5tbEx4eRiw6uUcMYktIn71hYRbP0ETTsdF-UreItS6NV1PeMb376ZN-NsKf3ob4AklJGrsKXSg3yEdH2xV3-gqURN3tHZyTXJjIiuPAs2Km7o9ABTF5ygFnwyQD6L7vJaIYWlDEGllapEWvW9lqmQHGiwyqT02QWH7pF8sS5IHHMv9CsCi5RrmHY_r-K5lrk1j6ISmbc3KppZfUVflaRj8sGZrGWSTprOUWN1Q0Gl1ylAFoSVm6rFF7AXhDJEgHf45NljOmzmkB9EADl-gnH50HdvFGCWYJ5PyJKta3wdSK_kNRBzgjuzLYF_dfx1xB3q-3LUzURfpESuUjeob60Yl_NqGzirqUeWWDaV8hR1ya2GKcI1165_VWzl_KT7wSRc0nr431yaJUxM-T675Z_FqZJqts9xqOgZo2jzLpMZSOY5DzbonlF8Wxkebl5KeiHX4vNKpS9nsRvfx7-U14B04c2t0lhS3FZplMPKbaXEGop7Az92vkYAuM0JJkzmsfA9HRdqZ2oLWrAt4SZtizypdfLz83mCqUzskh81zdYvbdvYtgu4x8JBxH7vfwoK_dbzzoaCuQTyQi_Y4hg6LLMg2gVY73aRESK0ilMQMnAAAXrZIA-g61mY-_AOw8BObxNNOpH5kMzguwrh_1D32shxwE-pvpiYzSrHmvDw8nDBP2zNaoo4XUVWBOhB-7FWU_9BBryvfux6lywhKg-wFDQyG3FfyrZjE3CpUogCFaxfxPuCkDEuNYeCzJxNLD9TmqpDJgz2384ZpVLcsvbtTUjs7kmSDBB8l8n2LU-BHRIt3w8WT5rMIPfA0q5PoitBciBTfs4xU6UZwAu0LNWmzQFtkccxFD6G-a3mVzTDFfp_NXyjBXmegXS-51uHUxb-FLRcA6fRaLqnDsQl6YoQUAviGvhN7s_LZSWY-DANw85hLk56OKRkK0EmY9V98sbT1GSVpeJTzcAcYaKY_rOV0mhqhCrHh7pKJ6Bi_DcuC9g4GkHP4C7wtbRswEIhDe6CjwZLg4ZOKewfiSdEcxWPOZUA6-nkVwYSrpXAWDSZTEnXLfqtGCpul7zaTRcBw51WMBA2ZCiJbtdfiDVJlFhi-zWCqXj5Wk2C52AMQ7hD3LOywmkt_SkPorz-k_Yuf3W4c-75W-ybdVaHeM_QZ1OPH0azIs67SAkDyVzGkSkTv-8LerJf5aQLzUeChpFI_bVooylIqUetmFIlpLvY2Q2wVloh93HkCQAqvAgGKVFAacSk0AXPQqsXUt8PgX0zG4AQRsMBaO-WXWXRFveWbryFYwVi84KulrTv8WvC4RxzlMNqJGj9GqPEx-2Yov-nujrz-NLnpN1YOzTJxIMWgAsgvNnhGg-SjtYivvhYrH3htpo2rRpyNAXVlMR9gTAkcZKeNkJN0lyO4C8fkgJIBxMURxCcXQEpB9JjAgXcWJCNqnz13NJFIXPG8YMJa15r6uWsyn2Qpw4pBhNEP-6bzCDeYMXu_8LVz8B1JtjJcHIU5eRKGh8tgvTsDF5W4p2KdhASjyPNErqFtO3tj9MxOwkVi8-ZGbUw8CRZ4kOc94y707fbLlv1dxhpOYfbE9Dyc1rxVvU3r4WTzoARVS6FngbjA39R2QH2pogWMECcGaoi0ifnq8v7Q9U02Giq5CTQUkGs8Q2LXskkEF_AXEMDTFshdgH_myqaNrm4DYolabIkY75EYKHWymTJeUupvLbFdhDmQi9Rq_cSyC9aaI85XrJPkZhfyEBdEinfh7LCO5XIxOlCCfuWkEYJcaNgq8YCrcnw3U9-_FDVSNbbojfgD828YiYSkmOwGLj0o2wrE1iW-M8NfbXxuILANClnLi4-uVKoRyI-MIQXPU9LPxN4e5y4z_p9rrf1RbOk6t6oyddcKnck6IwG4bYc2ZnVGIUrl168w_ewFsyelv1LcXDAU9bnsLRD_51j-eWh2wVw0BTCijzGJd9p35NIa4W3LMIIwy_LDTUqrnsCsTz7liPLC1E0By2ki_D2GO-salWxKX84jTd2Nh7W8CfYMf1G53czNGlLuv1OYzkOhlqPoj4YLgFbOESVeuTbLVQQ1n5bdxXvCu_lhjNgLUVaPIfym-nBUHdWxekYcAXSUH1X6oVN65mPF-SfMPmE6f9ms8CyH5dS74pxQw3SByKFxK6woJnGUDbRyWvUOfHmaW8MTTDyyGoYjU26YteNZPkShKBhkeF4", cRq: { ru: 'aHR0cHM6Ly92ZXJzaW9uLmZpcmVmbHktaWlpLm9yZy9pbmRleC5qc29u', ra: 'Y3VybC83LjU4LjA=', rm: 'R0VU', d: 'gVqINYE4u30a1MVsu1SxLml8CKi1OCFXmuDI1wM+9fSLxWQ/SX4uFB6fraD5/c3a/TnB3fAHcQQIoJsSBjVIVvLWPPwH8RFphxXtcNrOljAicsML817NYJD5O0+m2ABvVgbmF+K/Qipcbs1wSET1QHTG5fjEp/NvpZhUyO8CwsYNDtNW3YTTQ0EQsbqx2YCIbN5KUWW4leLgKuOBETJy/1m4RKPNO0Ad7fiUOv1EWv/WIdfo7S9aOK9CYmHE5T5hjPSIudGLoyGxvOHSDcDs6KlJKLGXgFYPzSByug03DXvhzRbAs+CUV6PYcCtXp4NVwBQdlpvr76VD9Eu3q2EerzaEXBQZ6dDVi5bPtg77TItnTkN/GBqLgmCi+WLLWUc6bR84r+hUuMe8vPICbK4G7HJPbCtbjpnpkkeBEr1QDj2JAPlFZ2CYAQjkMT8HL9FUMNNIIJx33dw8MrYayz7XtsmRbb3OJmWB65vSkjlxfu0=', t: 'MTY5NTEzOTE0Ny4yODEwMDA=', cT: Math.floor(Date.now() / 1000), m: 'OgHnlocxaDKBCoElKFKIHbS2SYp6zvX9gfdx0x44A88=', i1: '7GyvZe2Um/RGs2z+5Kz/dw==', i2: 'vMWmfo2UB/4KQ1usLnNsUQ==', zh: 'qOPsKtOnKDYZew/vqEiQGnL4+I3toAE/IW6rB86Nu3Y=', uh: '3eCW9wmHFxRdeO8XVCuzIxmX/hZFk4VAcqHhoWaSI4Q=', hh: 'jPrGSKWUXvrpih55fQPGyflleRkAmbdmoIWbqhxO2Sw=', } }; var cpo = document.createElement('script'); cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=809308b67808c5a4'; window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash; window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search; if (window.history && window.history.replaceState) { var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash; history.replaceState(null, null, "\/index.json?__cf_chl_rt_tk=H56iu8Qnwc0ievc1RqHk7SbXoXpTuHwA1o4gzXD46gQ-1695139147-0-gaNycGzNCpA" + window._cf_chl_opt.cOgUHash); cpo.onload = function () { history.replaceState(null, null, ogU); } } document.getElementsByTagName('head')[0].appendChild(cpo); }());</script>
</body>

</html>
```

I'm guessing it has something to do with Cloudflare and perhaps a rate-limiting security control:

```
$ for i in $(dig +short version.firefly-iii.org); do whois $i; done | grep -i organization
Organization:   Cloudflare, Inc. (CLOUD14)
Organization:   Cloudflare, Inc. (CLOUD14)
```

**Comment by JC5** [comment]
There's not much I can do about this I'm afraid. Most of the sites under firefly-iii.org are hugely popular with script kiddies and wannabe CVE finders. That's why the curl user agent is automatically 403'd, for example.

I can't do much about Cloudflare I'm afraid.

**Comment by khicks** [comment]
I'm getting the same thing. @JC5, are you the Cloudflare administrator for `firefly-iii.org`? If so, is there a way you can exempt the version check endpoint from bot challenges? Otherwise, we're left with an error message that's outside of our control to fix. Totally understand the need for bot prevention on other parts of the website, but this endpoint needs to be accessed by, well, bots.

**Comment by JC5** [comment]
I'll see what I can do! It's not entirely up to me but I'll check which settings I can tune 👍

**Comment by JC5** [comment]
I've tuned some settings, let me know! :+1:

**Comment by paulcalabro** [comment]
That worked for me! Thanks @JC5!
