### ISSUE TITLE
Data-importer: missing currency code in nordigen accounts mapping

### ISSUE THREAD

**Issue by kesot** [firefly-iii/firefly-iii#7977]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When I use Nordigen for importing data from Revolut all the accounts have the same iban although they are recognized as different accounts in Nordigen so I could map them to different accounts in Firefly. But it's extremely hard to do because I need to manually figure out what account id matches which currency. 

### Solution

So the ask is to add currency code into mapping UI here:
![image](https://github.com/firefly-iii/firefly-iii/assets/8954238/967e8b7e-5721-40cf-ae1d-dd5a1dc27fd1)

**Comment by JC5** [comment]
Not a bad idea, I'll pick it up!

**Comment by JC5** [comment]
@kesot, @erwineverts, this should now be part of the `:deveop` Docker tag.

**Comment by erwineverts** [comment]
@JC5 Displayed nicely! I can't really test the currency because I only have EUR (what I expect).

Bedankt!

**Comment by patricksindelka** [comment]
Nice change, switched to develop for this.
The only issue with this is that all the Revolut currency accounts share the same IBAN. If you add the IBAN number to one of the asset accounts, the data importer will force to import all the transactions to that account, even if the currency does not match. So you have to remove the IBAN number from the asset account in Firefly.
But after removing the IBAN it is working great.
