### ISSUE TITLE
Data importer: failed transactions output

### ISSUE THREAD

**Issue by kesot** [firefly-iii/firefly-iii#7978]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When 3rd party api aka Nordigen or Spectre is used the line numbers are useless for troubleshooting cause you don't have the input csv to find them. 
And some banks, Revolut especially can sometimes provide bad data so that it is not importable by Firefly

### Solution

It would be nice to have a resulting csv for import output to download at least to match failed transactions by numbers and enter them manually.
Ideally, the csv would contain the result (added, duplicate skipped, deleted by rule, failed etc..) for each transaction and description.

One step further would be to have pre-import rules to fix the data on the fly.

**Comment by JC5** [comment]
I'm not a fan of CSV files, I'd rather build something user friendly. But I'll write it down as an enhancement and I'll think about a solution.

**Comment by kesot** [comment]
It's csv for input, why not to have the same format for out.
Also it's more estensible if you e.g. want to feed input csv into importer and then based on the results you need to either fix the source csv or build a new one to re-import. Say there are 1000 transactions failing because of the wrong transaction type or something like that. Showing them in UI will not be very helpful but having them as csv will allow you to run a simple script locally to fix them all and import back.

You can have both ofc nice UI and and option to download the results e.g.

**Comment by JC5** [comment]
Simple for you is not the same as simple for me. Sorry, this is off the list.
