### ISSUE TITLE
Search works only for lowercase

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#798]
Noticed on my installation, but also happens on demo. Searching for "[Rent](https://firefly-iii.nder.be/search?q=Rent)" results in 0 transactions, but "[rent](https://firefly-iii.nder.be/search?q=rent)" results in 20 transactions that all have "Rent" capitalized.

**Comment by JC5** [comment]
👍

**Comment by JC5** [comment]
Closed to clear the list.
