### ISSUE TITLE
API Failure: Asset accounts are not returned when requesting all accounts

### ISSUE THREAD

**Issue by baflo** [firefly-iii/firefly-iii#7985]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I had issues using firefly-iii-fints-importer, which always returns that a withdrawal conflicts with an existing asset account. After digging in the importer-code I found that it matches the IBAN of the transactions with the IBAN received from the F3-API endpoint `/v1/accounts`. So I tried that.

Turned out, it does not return asset accounts by default or with `type=asset`: 

```
> curl -H "Accept: application/json" -H "Authorization: Bearer eyJ0e...a3L-8" http://db21ed7f-fireflyiii:8080/api/v1/accounts\?type\=all \
    | jq '.data | map(select(.attributes.type=="asset")) | "Found accounts: \(. | length)"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 45134    0 45134    0     0  52646      0 --:--:-- --:--:-- --:--:-- 52603
"Found accounts: 0"
```

However, with `type=asset` the accounts are returned:

```
> curl -H "Accept: application/json" -H "Authorization: Bearer eyJ0eX...Za3L-8" http://db21ed7f-fireflyiii:8080/api/v1/accounts\?type\=asset \
    | jq '.data | map(select(.attributes.type=="asset")) | "Found accounts: \(. | length)"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4796    0  4796    0     0  22591      0 --:--:-- --:--:-- --:--:-- 22622
"Found accounts: 5"
```

### Debug information

Debug information generated at 2023-09-23 08:51:32 Europe/Berlin for Firefly III version **6.0.20**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.20 |
| Firefly III API | 2.0.6 |
| Build | 597, 17-08-2023 10:06:07 UTC |
| Base Build | 35, 30-07-2023 03:52:37 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.8` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-09-01 00:00:00 |
| Session end | 2023-09-30 23:59:59 |
| Session first | 2023-01-04 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.81 |

### Expected behaviour

API should return all accounts by default.

**Comment by JC5** [comment]
The asset accounts could be on page 2.

**Comment by JC5** [comment]
I tried this on the demo site and it works fine for me ™️ : 

<img width="1129" alt="Screenshot 2023-09-23 at 10 37 09" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/7dc7795e-7b7e-49ca-a9d9-a60ec3e922ae">

<img width="1364" alt="Screenshot 2023-09-23 at 10 37 28" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/6a22b90f-1b5f-4784-9a48-107de63583e4">

**Comment by baflo** [comment]
> The asset accounts could be on page 2.

🤦‍♂️
thx a lot...

**Comment by JC5** [comment]
Hah, classic. I made the same mistake when developing the data importer.
