### ISSUE TITLE
Deposit/Withdraw label next to data when mapping categories, tags or accounts in the Data Importer

### ISSUE THREAD

**Issue by xMrPhede** [firefly-iii/firefly-iii#7989]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to see a label that specify the transaction type next to the data when I'm mapping in the Data Importer. 
So probably that needs the Data Importer to split the deposit transactions and the withdraw transactions for every entry in the mapping window.

I would like a feature like this because often I have a Transaction that has a misinterpretable name and when mapping the category to which it belongs to, happens that I set a "Income Category" to a withdraw Transaction and viceversa.

Example 1:
I have only one Transaction in my CSV named "Amazon" which is a refund (so deposit) and amount is+10.00€.
When mapping I mistakenly set its Category to "Electronics", because I can't know if it's a deposit or a withdraw (obviously this happens when I have 50+ transactions in my CSV and it's not easily checkable) that means that is basically a guessing game.

Example 2:
I have 2 Transactions in my CSV named "Amazon", one is a refund, one is a payment with amounts +10.00€ and -35.00€.
Without the feature I'm asking for I wouldn't be able to set two different categories (let's say "Payback" for the refund and "Electronics" for the payment) for the deposit type transaction and for the withdraw type transaction but just one that would be certainly incorrect

### Solution

It would add a lot of time saving because it would be easier to map categories, tags and accounts. 
It would also let the users import their transactions without having to check them multiple times in the report or category sections to see if all transactions are correctly categorized.

### What are alternatives?

I created some rules to do that automatically, but you can't set that completely automatic so there is still some manual work to do afterwards once the rule has finished running.

The "kind of" solution I found is to create a new category called "Errors" and a rule that every time a new transaction is stored in a "Expense Category" automatically sets the category to "Errors". Then i manually reorder all of those misplaced transactions.

**Comment by xMrPhede** [comment]
To be clear, I don't want to map every single transactions, I would just like that the transactions that have the same entry name gets grouped into 2 different mapping selections with the same name but different label that indicates the transaction type.

Let's say I have 35 entries named "Revolut UAB", 6 of which are deposits and 29 of which are withdrawals.
I would like to see 2 mapping options (with labels that specify the type of transaction), one for that will apply a certain mapping to the 6 deposits and one that will apply another different mapping to the 29 withdrawals.

**Comment by JC5** [comment]
At that pint during the import there is no difference between withdrawals and income. The data importer doesn't know yet what it will be, it just shows you what it found in your import file. 

This is not a bad idea but it's not possible I'm afraid.

**Comment by xMrPhede** [comment]
Would it be possible if in the CSV the withdrawals are indicated with "-amount" and the deposits with "+amount"?

**Comment by JC5** [comment]
No because like I said, mapping isn't per transaction. It just puts all data together in one big mapping array. Mapped values can be used in both withdrawals and deposits.

**Comment by xMrPhede** [comment]
Yeah i got that, but what I was asking was a little different (maybe I wasn't very clear in my explanation, sorry :) ).

I know the Data Importer groups Transactions with the same entry name to map them all together, so instead of grouping them just for entry name, given that I select the Transaction's Amount in the setting page, maybe it could group Transactions for both negative or positive Amount and entry name. 

I hope now it's more understandable. Would that be possible or still it's technically undoable?

**Comment by JC5** [comment]
That's undoable I'm afraid.

**Comment by xMrPhede** [comment]
All right, thank you for the replies and for your work!
