### ISSUE TITLE
404 - Not found in translations

### ISSUE THREAD

**Issue by SlimG** [firefly-iii/firefly-iii#7990]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When translating, I stumbled upon a string containing a URL that does not work: https://docs.firefly-iii.org/about-firefly-iii/personal-finances

Translation string: 

`If you haven't already, please read the [grand theory](https://docs.firefly-iii.org/about-firefly-iii/personal-finances).`

### Debug information

Key: array['registered_doc_html']
array['registered_doc_html']
File: [email.php](https://crowdin.com/translate/firefly-iii/358/en-nnno)

### Expected behaviour

The link should work

**Comment by JC5** [comment]
Nice find, I will update the offending string of text.

**Comment by JC5** [comment]
Fixed.
