### ISSUE TITLE
Exception in API when calling chart

### ISSUE THREAD

**Issue by victorbalssa** [firefly-iii/firefly-iii#7992]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

when accessing `https://api-docs.firefly-iii.org/?urls.primaryName=2.0.8%20(v2)#/charts/getBalanceChart`

it uses the `BalanceChartRequest->getAccountList()` which throw (L.175):

- FireflyException('uses old administration ID check, needs to be updated.G')

https://github.com/firefly-iii/firefly-iii/blob/d4ecf44b08a103145cb0fac0f39e77591fbc3a8d/app/Support/Request/ConvertsDataTypes.php#L166-L176

I was wondering if we could update this endpoint to remove the error thrown?

### Debug information

x

**Comment by JC5** [comment]
Yes, perhaps we could 🤔

**Comment by JC5** [comment]
Fixed! :+1:
