### ISSUE TITLE
Show payment on liability account in positive instead of showing it in negative 

### ISSUE THREAD

**Issue by jdjo333** [firefly-iii/firefly-iii#7996]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When I make payment on liability account from an active account, the payment is in negative in the active account (this is normal) but in the liability account the same payment is show there too in negative... Normally, this should be in positive. 

### Solution

Simply make new code for passive account for showing the right value.

**Comment by JC5** [comment]
Transactions will always display in the same way, regardless of context.
