### ISSUE TITLE
Feature Request: Automatic Date Range in Nordigen Data Importer

### ISSUE THREAD

**Issue by SlimG** [firefly-iii/firefly-iii#7999]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I perform the following routine manually relatively often:

1. Go to Firefly Importer (Docker) webinterface
2. Click "Import from Nordigen"
3. Upload my .json configuration file and click next.
4. Set the "Date range from" to the the day after my last registrered transaction or transfer in Firefly.
5. Set the "Date range to" to the last full day that has happened.
6. Run

I am doing it this way so I have freedom to manually and automatically edit the description of the transactions and transfers after they are imported.

I am considering to automate this import. and based on my understanding if I want to retain this freedom, I'll need to create a script that generates a .json file with a specific date-range before feeding it to the future daily import-job.

### Solution

A new date-range option in the Nordigen Data Importer called something like:
> Full days since last transaction

Example:
> Time of last transaction or transfer: 2023.09.20 15:50
> Time right now: 2023.09.26 21:31
> Results in the date-range: 2023.09-21 -> 2023.09.25

**Comment by JC5** [comment]
This is already possible.

<img width="1093" alt="Screenshot 2023-09-27 at 06 29 39" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/9e684aa8-7aac-4cd7-b894-8114c7567387">

**Comment by SlimG** [comment]
That function goes back a static amount of days.
What I am suggesting is a similar function, except it goes back a dynamic amount of days based on when the last transaction or transfer happened in Firefly

**Comment by JC5** [comment]
Sorry no, what you see is what you're going to get I'm afraid.

**Comment by SlimG** [comment]
No problem! Thanks for the replies and good luck with the V2 UI :) Looking forward to even cooler graphs :)
