### ISSUE TITLE
Sugesstion: Replace empty chart in Default financial report with some message

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#800]
After generation of Default financial report there are two big white boxes with title "Chart". My first thought - they are loading so long, because I was generating report from 4 years. It turns out that you have to click category name in the tables above to display chart for selected category.

I'd like to suggest adding message "Click budget/category above to view chart" or something similiar when no chart is displayed.

**Comment by JC5** [comment]
Good idea!

**Comment by JC5** [comment]
Fixed, visible on the demo site!

**Comment by pkoziol** [comment]
Great, thanks!
It doesn't work for reports spanning more than 12 months, but I guess it will be fixed along with #801.

**Comment by pkoziol** [comment]
All good now. Closing.
