### ISSUE TITLE
Feature Request: Inform user when there no transactions found by Nordigen Data Importer

### ISSUE THREAD

**Issue by SlimG** [firefly-iii/firefly-iii#8000]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When I run the Nordigen Data Importer (v1.3.8), and there are no transactions to be imported. The Nordigen Data Importer throws the generic errormessage:

> The conversion could not be started, or failed due to an error. Please check the log files. Sorry about this :(

In the log I see the following clue that tells me this is due to no transactions found:

> [2023-09-27 00:08:56] local.DEBUG: Now generate transactions.  
> [2023-09-27 00:08:56] local.DEBUG: Going to parse account 341f18c2-b246-412b-934f-abbb2398f5af with 0 transaction(s).  
> [2023-09-27 00:08:56] local.DEBUG: Done parsing transactions.  
> [2023-09-27 00:08:56] local.DEBUG: Generated 0 Firefly III transactions.  
> [2023-09-27 00:08:56] local.DEBUG: Filtered down to 0 Firefly III transactions.  
> [2023-09-27 00:08:56] local.DEBUG: Conversion routine "nordigen" was started successfully.  
> [2023-09-27 00:08:56] local.ERROR: Zero transactions!  

### Solution

Replace the errormessage
> The conversion could not be started, or failed due to an error. Please check the log files. Sorry about this :(

with something more human readable like
> No transactions found in the selected date-range

**Comment by JC5** [comment]
Good idea :+1:
