### ISSUE TITLE
Import does not recognize debitor account - Nordigen import

### ISSUE THREAD

**Issue by FrodeMMeling** [firefly-iii/firefly-iii#8005]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am doing import of transactions from a Norwegian bank. Import works fine, its just many transactions are not detected as transfers between internal accounts.

Here is some log:
`sent on email`

So after conversion and import is done I have my Asset account with accountnumber : 2222222222222
And I hav ea revenue account with same account number: 2222222222222

I masked some numbers here so I may have mixed up something. but the essense is that my asset account is not detected as destination account.

### Debug information

`
sendt on email
`

### Expected behaviour

Transfer is created

**Comment by FrodeMMeling** [comment]
Here are tinker output after import:
> $account = Account::find(1);
= FireflyIII\Models\Account {#8557
    id: 1,
    created_at: "2023-09-27 14:52:19",
    updated_at: "2023-09-28 09:16:48",
    deleted_at: null,
    user_id: 1,
    user_group_id: 1,
    account_type_id: 3,
    name: "SPV - Frode - Kort",
    virtual_balance: "0.000000000000",
    iban: "NO5034957706241",
    active: 1,
    #encrypted: 0,
    order: 1,
  }

> $account->getAccountNumberAttribute();
= "22222222222"


> $account = Account::find(20);
[!] Aliasing 'Account' to 'FireflyIII\Models\Account' for this Tinker session.
= FireflyIII\Models\Account {#8508
    id: 20,
    created_at: "2023-09-28 09:26:16",
    updated_at: "2023-09-28 09:26:16",
    deleted_at: null,
    user_id: 1,
    user_group_id: 1,
    account_type_id: 5,
    name: "Frode Marton Meling",
    virtual_balance: null,
    iban: null,
    active: 1,
    #encrypted: 0,
    order: 0,
  }

> $account->getAccountNumberAttribute();
= "22222222222"

**Comment by FrodeMMeling** [comment]
> $account = Account::find(1);
= FireflyIII\Models\Account {#8557
    id: 1,
    created_at: "2023-09-27 14:52:19",
    updated_at: "2023-09-28 09:16:48",
    deleted_at: null,
    user_id: 1,
    user_group_id: 1,
    account_type_id: 3,
    name: "SPV - Frode - Kort",
    virtual_balance: "0.000000000000",
    iban: "NO9922222222222",
    active: 1,
    #encrypted: 0,
    order: 1,
  }

> $account->getAccountNumberAttribute();
= "22222222222"


> $account = Account::find(20);
[!] Aliasing 'Account' to 'FireflyIII\Models\Account' for this Tinker session.
= FireflyIII\Models\Account {#8508
    id: 20,
    created_at: "2023-09-28 09:26:16",
    updated_at: "2023-09-28 09:26:16",
    deleted_at: null,
    user_id: 1,
    user_group_id: 1,
    account_type_id: 5,
    name: "Frode Marton Meling",
    virtual_balance: null,
    iban: null,
    active: 1,
    #encrypted: 0,
    order: 0,
  }

> $account->getAccountNumberAttribute();
= "22222222222"

**Comment by JC5** [comment]
I can' t really tell from this info, but it's true that account numbers can't be used twice but the check isn't perfect.

Could you share with me the logs over mail?

https://docs.firefly-iii.org/data-importer/faq/general/#how-can-i-safely-submit-debug-information

**Comment by FrodeMMeling** [comment]
I sent you logs over mail.. Let me know if you need more debug info.

**Comment by JC5** [comment]
Could you run it again using the `develop` tag and send me the logs again? I think I found the issue.

**Comment by FrodeMMeling** [comment]
I ran it on Develop. docker images:
fireflyiii/data-importer          develop   623147b463ec   44 hours ago    544MB
fireflyiii/core                   develop   b29195f86246   2 days ago      585MB

Still no transfers beeing created.. 
Do you want more logs?

Is there a way to remove last import easily using a artisan command?

**Comment by JC5** [comment]
> Do you want more logs?

Yes please. If your configuration adds a tag to new imports that's the place where you can delete the transactions easily.

**Comment by FrodeMMeling** [comment]
ok. thanks.. I saw there was a newer import docker image.. rerunning import now with that image.. will send you logs on email:
Now running on:
`
REPOSITORY                        TAG       IMAGE ID       CREATED         SIZE
fireflyiii/core                   develop   b79c0cffcc6e   6 hours ago     585MB
fireflyiii/data-importer          develop   d9a7f1cda853   7 hours ago     544MB
`

**Comment by FrodeMMeling** [comment]
new logs sent on email

**Comment by JC5** [comment]
I'm building build nr 355, let me know if it works. The tool seems to have trouble recognizing account numbers, I hope this fixes it. Should be ready in 3 minutes from now.

**Comment by FrodeMMeling** [comment]
Works now.. Thanks.

**Comment by JC5** [comment]
Great! Thanks for helping me debug this. It will be part of the next release 👍

**Comment by JC5** [comment]
If there is even the tiniest difference Firefly III won't recognize the duplicate. There's not much I can do about that I'm afraid.

**Comment by FrodeMMeling** [comment]
Ok. but is there a way to link the two transactions? saying that this is a duplicate? I see there is a way to link?

**Comment by JC5** [comment]
If you delete one of them, it should no longer be imported again.
