### ISSUE TITLE
Expose HTTP port in Dockerfile

### ISSUE THREAD

**Issue by shalak** [firefly-iii/firefly-iii#8008]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Firefly's Dockerfile should expose the HTTP port. Thanks to this, tools like Traefik can automatically detect to which port it should reverse-proxy the traffic.

### Solution

```diff
diff --git a/Dockerfile b/Dockerfile
index 5b6d82c..1e5b275 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -18,4 +18,6 @@ RUN curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100

 COPY alerts.json /var/www/html/resources/alerts.json

+EXPOSE 8080
+
 ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
```

### Additional context

I was trying to setup an azure account and create a PR for [the deployment repo](https://dev.azure.com/Firefly-III/_git/MainImage), but something's broken for me on azure side (I cannot add any SSH keys there).

**Comment by JC5** [comment]
The port is exposed in the base image. 

https://dev.azure.com/Firefly-III/_git/BaseImage?path=/apache-8.2/Dockerfile

**Comment by shalak** [comment]
Docker doesn't seem to detect it though 🤔 Maybe the EXPOSE call is not inherited downstream?

**Comment by JC5** [comment]
What do you mean, Docker does not detect it? Simply running `docker run -d --publish-all fireflyiii/core:latest` shows port 8080.

**Comment by shalak** [comment]
Huh, you're right. According to `docker inspect --format='{{json .Config.ExposedPorts}}'` it indeed does. I must've been mistaken, maybe I jumped to conclusion too fast and Traefik would eventually automatically pick it up. Sorry for opening unnecessary issue.
