### ISSUE TITLE
POST /api/v1/accounts redirects to login page

### ISSUE THREAD

**Issue by jfk9w** [firefly-iii/firefly-iii#8009]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi, James! Fresh Firefly III user here. Unfortunately, this bug prevents me from appreciating the full power of it :(

Attempting to create an account via API causes redirect to login page. This is reproducible both with PAT and OAuth flow on my self-hosted instance, and though I have reproduced it only with PAT on demo website, I suspect the behavior would be the same. Interestingly, the authorization flow expectedly bounces me with 401 if I fail to specify headers correctly, so this is definitely not an authorization issue.

My first guess was that I somehow messed up in authorization, but `POST /api/v1/currencies` works as expected on my local instance.

### Debug information

Debug information generated at 2023-10-02 00:44:39 for Firefly III version **v6.0.26**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.26 / v2.0.9 / 20 (exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.10 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>674, base <span>#</span>38</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td> + Europe/Moscow</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>notice, stdout / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>ru_RU + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2023-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-10-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>ru_RU</td></tr><tr><td>User locale</td><td>ru_RU</td></tr><tr><td>Locale(s) supported</td><td>ru_RU.utf8: :white_check_mark:<br>ru_RU.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

`POST /api/v1/accounts` creates an account and returns a correct response as per [Swagger spec](https://api-docs.firefly-iii.org/).

### Steps to reproduce

1. Create either PAT or OAuth tokens.
2. Execute `POST /api/v1/accounts`.

### Additional info

Reproducible with PAT on demo website.

**Comment by JC5** [comment]
Did you add the "Accept: application/json" header to your request?

**Comment by jfk9w** [comment]
@JC5 Yep, that works. Thank you!
