### ISSUE TITLE
Sugesstion: Remember menu state

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#802]
Collapsing menu (sidebar) works only on current page. After clicking something or refreshing page menu is expanded again. This is quite annoying when browsing category with many pages. It would be great if menu state (collapsed/expanded) was remembered (in cookie/localStorage/database/something) for desktop version.

Also, search could be moved between menu-toggling icon and help icon when menu is collapsed (or maybe always if there is enough space?).

**Comment by JC5** [comment]
I'm not sure if admin-lte, the layout, supports it. I'm not going to hack it because it makes upgrading a pain.

**Comment by JC5** [comment]
https://github.com/almasaeed2010/AdminLTE

**Comment by pkoziol** [comment]
It doesn't support it. There are [some](https://github.com/almasaeed2010/AdminLTE/issues/896#issuecomment-264723101) [solutions](https://github.com/almasaeed2010/AdminLTE/issues/1240#issuecomment-258649098), but probably won't be any official for v2, because [they're working on v3](https://github.com/almasaeed2010/AdminLTE/issues/1232#issuecomment-258454151),
