### ISSUE TITLE
API v2 Feature Request: `/v2/chart/account/dashboard` should allow the application to select all accounts

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#8022]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

The API v2 endpoint for `/v2/chart/account/dashboard` currently says:

> By default it contains the users frontpage accounts OR all the user's asset accounts if this preference is empty.

### Solution

It would be great if this default behavior could be changed by a switch like `includeAllAccounts` or similar to include all accounts regardless of user preferences.

### What are alternatives?

I don't know of any other endpoint which reports data in a similar way to that one.

- `/v1/chart/account/overview` behaves exactly the same and also hides non-default accounts without option to include them.
- `/v2/chart/balance/balance` shows +/- on a given day (in a date range), no sum.

Theoretically, the user setting could be updated with an API call to include all accounts (`v1/preferences` endpoint), fetch the data, and be changed again to the old setting... That's not a nice solution :D

### Additional context

Requested for the v2 API since I guess that one is more likely to change than the v1 endpoint :)

**Comment by JC5** [comment]
Good idea, I'll write it down!

**Comment by JC5** [comment]
In 6.1.0 this should work:

`/api/v2/chart/account/dashboard?start=2023-10-01&end=2023-10-31&accounts[]=1&accounts[]=3`

**Comment by JC5** [comment]
No, not right now. I could add something like that, some other pages already have keywords that work like that. It would be another parameter though.
