### ISSUE TITLE
If possible, make a static header option

### ISSUE THREAD

**Issue by jdjo333** [firefly-iii/firefly-iii#8023]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

If possible, make a static header option
To allow to open the "+" menu at the top right and create operations without having to go up the entire page each time

Or otherwise make of this menu a floating button in the bottom right corner

### Solution

Better navigation

**Comment by JC5** [comment]
I'll write it down for the new layout, thanks!
