### ISSUE TITLE
Automation: Allow splitting of amount into/out of multiple piggie banks

### ISSUE THREAD

**Issue by Kage1** [firefly-iii/firefly-iii#8024]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Currently piggie banks are a bit annoying to deal with. I heavily use automation to classify transactions, set budgets, etc... on transaction import. The only option for piggy banks is to take the full amount of a transaction and put it into a single piggy bank or remove that amount.

Twice a month I transfer a bulk amount to savings for various uses, taxes, insurance, and the like. I can have up to 7 different piggy's that I would add to.

What i would like to do with in the automation is:

On a single transaction, with in the "Rule will" section, allow for multiple piggy bank entries that allow for referencing the piggy and specifying the mount to go into that bank.

For me, this would make piggy's more useful vs currently they are just there since they are a bit cumbersome to use.

### Solution

Add options to the Rule Will Actions for splitting a single transaction amount amongst multiple Piggy's when the transaction is processed.

A few questions to answer:
1. What would happen if a piggy is "full"?
2. What would happen if user entered piggy amount(s) exceeds the transaction value?
3. Could pulling out of a piggy work the same way? Maybe entering negative number...

### What are alternatives?

Do what's being done now... mostly ignoring them.

**Comment by JC5** [comment]
You'll have to use something like webhooks to do this I'm afraid. I can't make the rule engine more complex than it is now.
