### ISSUE TITLE
Sugesstion: Allow to set default account for new transactions

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#803]
I have 17 asset accounts (2 inactive, 2 for cash, 3 currency exchanges, 4 saving, PayPal and 5 ordinary). I'm mostly using one of them which name unfortunately starts with T. It means that every time when I'm creating new transaction I have to select my main account instead of default one which starts with B.

It would be great if there was some option to select default account for new transactions.

My ideas:
1. Checkbox "Default", after "Active" in editing asset account. It should be possible to set it only in one account at the time.
2. New account role: "Secondary asset account". Accounts with role "Default asset account" would be displayed first on the list then secondary then shared than saving and credit cards last. `<optgroup>` could be used to eaisly distinguish account types. I know it forces specific order which may be unwanted by others.
3. New account role (can't come up with good name) that moves accounts at the end of list. Something like _inactive-but-that-allows-creating-transactions_.
4. Or maybe just allow to freely reorder accounts just like transaction within single day.

**Comment by JC5** [comment]
There won't be a default account. There are some focus-issues caused by Javascript-triggers that make the focus (caret) jump around. Once that's fixed, it should be easy to select the account you want to use.

I'm not going to add new roles that have a layout function only, but the opt-groups are a nice touch.

**Comment by JC5** [comment]
Focus is fixed, opt-groups are added

**Comment by pkoziol** [comment]
Thanks!
