### ISSUE TITLE
Running account balance in /accounts/show

### ISSUE THREAD

**Issue by spoulson** [firefly-iii/firefly-iii#8032]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

The `/accounts/show` page should include a column with running balance.  Currently, this functionality only exists in the Transaction history overview report, but that is not the same view I'm using for maintaining my ledger.

I found this feature was previously requested in 2018 (https://github.com/firefly-iii/firefly-iii/issues/1497).  I consider this feature relevant and useful to myself and I suspect the general user base would appreciate it.

### Solution

- Add a column for running balance in `/accounts/show`.
- Column may be disabled in "Optional fields for transactions" section in Preferences.
- Column to be enabled by default.

### What are alternatives?

Run a Transaction history overview report even time I maintain my ledger.  This is inconvenient because the UI and functionality is not the same for browsing and editing transactions.

**Comment by JC5** [comment]
Yes this is part of what I plan to do for the new layout. I'll lookup the issue in a moment.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/5751
