### ISSUE TITLE
Simplify and improve mass-editing transactions

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#804]
Currently, only From, To, Category and Budget can be edited for multiple transactions and for each transaction you have to manually type value even if all transactions will have the same. In JIRA or Bugzilla (or both?) there is option to mass-edit bugs which allows to set same value for some field(s) for selected bugs or all bugs matching search query.

It would be extremely useful when starting using Firefly and importing transactions from bank. I had a lot of transactions that were made using debit card and had destination account set to my bank, but there was name of the company in the description - eg. Google Cloud. Similarly with all that fast online payments via companies that have account in every bank and provide API for receiving transactions, but again - real recipient name was in the description, so it was easy to create query matching them.

I worked around that by creating new rule with triggers and actions I wanted, then applying it manually and then deleting it. It works but could be easier.

**Comment by JC5** [comment]
Yes, but such a mass-edit feature/change is a lot of work for a very small use case. I suggest you use your workaround or copy/paste the values you wish the transactions to have.
