### ISSUE TITLE
Bills to pay amount is incorrect with bi-weekly bills

### ISSUE THREAD

**Issue by TyrionWarMage** [firefly-iii/firefly-iii#8044]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Bills to pay amount is incorrect with bi-weekly bills:

Monthly bill (already paid):
![grafik](https://github.com/firefly-iii/firefly-iii/assets/5308190/82be2b5c-ebdd-457b-bb89-13437215c11b)
![grafik](https://github.com/firefly-iii/firefly-iii/assets/5308190/29affb5e-d3c1-4f6e-a7cb-40d18607ec17)

Changed to bi-weekly (already paid once):
![grafik](https://github.com/firefly-iii/firefly-iii/assets/5308190/f6aa0924-ab28-40fa-bbd4-8f56f0339664)
![grafik](https://github.com/firefly-iii/firefly-iii/assets/5308190/e606e05f-b2da-496d-b554-498bfb17aeae)

Amount of "bills to pay" is raised by twice the bill sum, instead of once.

Selected range was Oct.1-31, bill paid on Oct.4.

### Debug information

Debug information generated at 2023-10-09 20:58:56 for Firefly III version **v6.0.26**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.26 / v2.0.9 / 20 (exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.10 / fpm-fcgi / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td> + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / remote_user_guard</td></tr><tr><td>Login headers</td><td>REMOTE_USER + </td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 3</td></tr><tr><td>User flags</td><td>:wrench: :bookmark_tabs: :email:</td></tr><tr><td>Session start</td><td>2023-10-05 00:00:00</td></tr><tr><td>Session end</td><td>2023-10-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0</td></tr></tbody></table>

### Expected behaviour

Bills to pay should be 271.56 in the bi-weekly scenario.

**Comment by JC5** [comment]
Nice find, I'll check it out!

**Comment by JC5** [comment]
Actually, this is correct. A bi-weekly bill that starts on April 4, 2023 has three moments in needs to be paid in October:

- 2023-10-03
- 2023-10-17
- 2023-10-31

Thanks for reporting!
