### ISSUE TITLE
Cannot reset Nordigen API misconfiguration

### ISSUE THREAD

**Issue by SebastianReitzner** [firefly-iii/firefly-iii#8045]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi!
So I have previously used the importer to provide data for my self hosted instance - since that was some time ago I wanted to feed new data to the system.
However the importer required me to reconfigure my Nordigen connection which I thought odd, but was open to do.
The issue is that the first configuration was some time ago and I might have gotten the ID/key mixed up or something, because the importer now only displays the following:
![image](https://github.com/firefly-iii/firefly-iii/assets/36883233/d81b43cd-d642-4aac-be79-aa106e40c3ce)
Sadly no amount of pressing 'Start over' or loading /flush cleared that up for me to try again, I couldn't find any help regarding this error nor did the general reset help.

### Debug information

Debug information generated at 2023-10-09 22:22:32 Europe/Madrid for Firefly III Data Importer version **1.3.8**.

| Scope | Version |
| --- | --- |
| FIDI | 1.3.8 |
| Build | 317, 01-09-2023 18:06:24 UTC |
| PHP | 8.2.9 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | Europe/Madrid |
| Browser TZ | Europe/Vienna |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | emergency, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

### Expected behaviour

Provided connection info is flushed or dumped after failed Nordigen import and the user can retry.

### Steps to reproduce

1. Try to import using Nordigen.
2. Fail to provide the correct ID/KEY configuration
3. Stay stuck on that error

### Additional info

If this is really just a Nording API issue like the error proposes, please just point me the right direction on what the issue is.

**Comment by SebastianReitzner** [comment]
Alternatively the Nordigen API has changed and needs adjustment on the importer side?

**Comment by JC5** [comment]
This user had something similar. I will investigate this over the weekend. 

https://github.com/firefly-iii/firefly-iii/discussions/8019#discussioncomment-7209206

**Comment by JC5** [comment]
Could you try running the latest `develop` tag, and see if this works?

**Comment by JC5** [comment]
@DSew20 this fix should also solve your original issue.
