### ISSUE TITLE
Liability account shows wrong total value

### ISSUE THREAD

**Issue by avee87** [firefly-iii/firefly-iii#8047]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I imported my transaction history from another system and my mortgage numbers are now displayed incorrectly. While all transactions seem correct and amount in account view matches what I expect, on "Liabilities" view it is completely different - i.e., as if all repayments increased debt as opposed to reducing it.
See screenshots:
![Screenshot 2023-10-10 at 09 33 53](https://github.com/firefly-iii/firefly-iii/assets/6134677/eccb9f58-8281-4e80-af6a-c25f726e03e3)
![Screenshot 2023-10-10 at 09 29 43](https://github.com/firefly-iii/firefly-iii/assets/6134677/13e0b4b4-1c08-4282-a48a-2571f9d27a86)

### Debug information

Debug information generated at 2023-10-10 09:37:29 for Firefly III version **v6.0.26**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.26 / v2.0.9 / 20 (exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.10 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>674, base <span>#</span>38</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td> + Europe/London</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_GB + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:credit_card: :wrench:</td></tr><tr><td>Session start</td><td>2023-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-10-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

Liability amount should be the same in the list of liabilities and account view

### Steps to reproduce

~~Unfortunately, I couldn't reproduce this by manually adding transactions on a test account~~
Reproduces only in release version, not on demo instance!

* Create a liability account with type Mortgage
* Create a £1000 withdrawal from that account - Amount due changes to "-£1000"
* Create a £100 transfer from some asset account to mortgage - Amount due changes to "-£1100" instead of "-£900" as expected
* Delete both transactions - Amount due stays "-£1100" instead of resetting to 0

**Comment by avee87** [comment]
Update: I used rules to migrate mortgage to asset account and it now shows correct amount. Maybe I just don't understand something about how to work with liabilities...

**Comment by JC5** [comment]
But you say it has no transactions.

**Comment by avee87** [comment]
I created another mortgage account and migrated all transactions there. Now it shows the correct amount inside but on the outside it's still a large (but slightly different) number.

**Comment by JC5** [comment]
There are some changes due in the next release that should improve the calculation of the balance.

**Comment by JC5** [comment]
These are already present on the demo site.

**Comment by avee87** [comment]
I did some more digging and I think the issue may be that importer creates transactions between asset accounts and liability accounts as withdrawals as opposed to transfers which somehow messes things up.

**Comment by JC5** [comment]
They're supposed to be withdrawals, that's not the issue.

**Comment by avee87** [comment]
Updated repro steps - apparently, it only reproduces on release version and not on demo.
