### ISSUE TITLE
No possibility to trigger rule for transactions without budget or category

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#805]
As I descibed in #804, I used rules to mass-edit transactions.

It's not possible to create rule that only modifies transactions without budget or category. "Budget is..." and "Category is..." doesn't accept empty value (which could mean that there is no budget or category set, but it might not be obvious for everyone) and there is no trigger "No budget set" nor "No category set". Same with tags.

**Comment by JC5** [comment]
No it isn't, but it's a nice addition. I'll write it down! 👍 

PS: I can see how you spent your Saturday evening ;)

**Comment by JC5** [comment]
Fixed. You can try this on the demo site!

**Comment by pkoziol** [comment]
Great, thanks!

PS: Should I close issues labeled as fixed after veryfing them?

**Comment by JC5** [comment]
I was waiting for you to confirm / verify. Either of us can close them ^^
