### ISSUE TITLE
Clicking on Page 2 button of a specific budget goes to show page 2 of everything

### ISSUE THREAD

**Issue by prudviraj14340** [firefly-iii/firefly-iii#8050]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have some budget where there were transaction which are more than 1 page when I click on that budget for example "December 2019" it shows me transaction in page wise while page 1 load all transactions fine but when I click on Page 2 button. Page redirects and shows me Budget of "everything" page 2.

### Debug information

Debug information generated at 2023-10-10 16:05:29 for Firefly III version **v6.0.26**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.26 / v2.0.9 / 20 (exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.10 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>674, base <span>#</span>38</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td> + America/New_York</td></tr><tr><td>App environment</td><td>local, debug: true</td></tr><tr><td>Logging</td><td>debug, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:credit_card: :wrench: :email:</td></tr><tr><td>Session start</td><td>2019-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2019-11-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

Page 2 of the specific budget shown

### Steps to reproduce

Click on budget which would show transactions in more than 1 page.
Click on page 2.

**Comment by JC5** [comment]
Nice find, I'll check it out!

**Comment by JC5** [comment]
Found and fixed.
