### ISSUE TITLE
Error 500 when deleting account/liability

### ISSUE THREAD

**Issue by Sharparam** [firefly-iii/firefly-iii#8051]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When deleting an account/liability, it will fail with a 500 error, attempting to delete it a second time will succeed.

The first time trying to delete, it will mention a single transaction that will be deleted as well, this is not mentioned on the second attempt. So it seems this one transaction is deleted on the first try, and the entire account only succeeds in deleting after that transaction is gone.

### Debug information

`/debug` is not accessible on demo version.

On my self-hosted instance (6.0.26), which also exhibits the problem, the debug info is:

Debug information generated at 2023-10-10 21:05:06 for Firefly III version **v6.0.26**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.26 / v2.0.9 / 20 (exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.10 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>674, base <span>#</span>38</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td> + Europe/Stockholm</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>redis</td></tr><tr><td>Default language and locale</td><td>en_US + sv_SE</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:credit_card: :pig: :wrench: :email:</td></tr><tr><td>Session start</td><td>2023-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-10-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0</td></tr></tbody></table>

### Expected behaviour

The account/liability and any associated transactions should be deleted as described in the deletion warning message.

### Steps to reproduce

(All these steps were carried out on the demo site)

 1. Create a new liability with an initial "amount owed"
    ![image](https://github.com/firefly-iii/firefly-iii/assets/551094/bb0ccef2-4a5d-4ed0-b556-2f4b2aff656c)
 2. Verify it looks accurate
    ![image](https://github.com/firefly-iii/firefly-iii/assets/551094/0375a857-3192-470b-b673-b9df6c0bed6f)
 3. Delete it
    ![image](https://github.com/firefly-iii/firefly-iii/assets/551094/a0d5060e-b2e0-4e9e-8e91-0489b33fc1a8)
 4. Confirm deletion, notice that it mentions one transaction will also be deleted
    ![image](https://github.com/firefly-iii/firefly-iii/assets/551094/2adde0ec-fde8-46bf-b6cf-f5e0eec6dd01)
 5. Deletion fails with a 500 error
    ![image](https://github.com/firefly-iii/firefly-iii/assets/551094/3d5cfae5-7390-4592-8518-5a0b54dc2679)
 6. Go to delete again, it no longer mentions a transaction, and deletion will be successful
    ![image](https://github.com/firefly-iii/firefly-iii/assets/551094/f7ef01b3-1587-48f1-91e7-617385508096)

### Additional info

The version I self-host is the latest release (6.0.26), which also exhibits the same problem.

**Comment by JC5** [comment]
Nice find, I'll pick it up!
