### ISSUE TITLE
CSV import: allow for Payer/Payee instead of Asset/Opposing account

### ISSUE THREAD

**Issue by Aypac** [firefly-iii/firefly-iii#8056]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Mockup:
![image](https://github.com/firefly-iii/firefly-iii/assets/10585956/ac427775-799c-45ce-be1b-1dcb2ef3d8be)

I would like Firefly III CSV importer to have elements in the mapping drop-down for Payer and Payee account, similar to Asset and Opposing account (see mockup above). If the amount is positive, they get mapped payee<>opposing | payer<>asset, if the amount is negative the other way around (payee<>asset | payer<>opposing ).

### Solution

Two of my banks indicate in the CSV columns Payer account and Payee account (i.e. if it is in incoming transaction, I'm the payee, but if it is outgoing transaction, I'm the payer). It is easy to tell them apart, as the outgoing amounts are negative, the incoming ones are positive.

### What are alternatives?

Currently, I need to edit the CSV file and switch them for one of the two cases.

**Comment by JC5** [comment]
Firefly III already does that based on the amounts. Could you share some CSV lines and you configuration with me?

**Comment by Aypac** [comment]
Thank you for your reply. I have a hard time reviewing the import as it only shows examples for the individual fields, not entire rows. But it seems like you're right, so my real issue is different.

Dutch ING has this header:
```"Date","Name / Description","Account","Counterparty","Code","Debit/credit","Amount (EUR)","Transaction type","Notifications"```
with negative amounts.

German DKB has this header:
```"Buchungsdatum";"Wertstellung";"Status";"Zahlungspflichtige*r";"Zahlungsempfänger*in";"Verwendungszweck";"Umsatztyp";"Betrag";"Gläubiger-ID";"Mandatsreferenz";"Kundenreferenz"```
Google translate:
```"Booking date"; "Value date"; "Status"; "Payer"; "Payee"; "Purpose of payment"; "Sales type"; "Amount"; "Creditor ID"; "Mandate reference"; "Customer reference"```
The german DKB does indeed not invert the amount, so I guess that works with you logic.

German MLP has this header:
```"Buchungstag";"Valuta";"Auftraggeber/Zahlungsempfänger";"Empfänger/Zahlungspflichtiger";"Konto-Nr.";"IBAN";"BLZ";"BIC";"Vorgang/Verwendungszweck";"Kundenreferenz";"Währung";"Umsatz";" "```
Translate:
```"Booking date";"Value date";"Client/payee";"Recipient/payer";"Account no.";"IBAN";"Bank code";"BIC";"Process/purpose";"Customer reference";" Currency";"Amount";" "```
But also without negative amounts, it just indicates "H" or "S" in the very last column (~in/out). So I run a small regex (```"(\d+,\d\d)";"S"```>```"-\1";""```) over it to replace the amount with a negative one for all rows that say "S".

So I guess my issue should have been:
- Indicate which one (asset/counterpart) is payee/payer because that is not so clear to me
- Allow for another column to invert the amount

**Comment by JC5** [comment]
> Allow for another column to invert the amount

This is already in place. The "Bank specific credit/debit indicator" does that.

[It should support "S"](https://github.com/firefly-iii/data-importer/blob/main/app/Services/CSV/Converter/BankDebitCredit.php#L51)

**Comment by JC5** [comment]
> Indicate which one (asset/counterpart) is payee/payer because that is not so clear to me

I expanded the docs to explain this. The text may not be visible yet, because it always takes some time for the CDN to refresh the content.

https://docs.firefly-iii.org/data-importer/how-to-use/fine-tune-import/#asset-account

**Comment by Aypac** [comment]
Thanks!
Sorry it looks like I abused this after all for a personal support. That was not my intention. I'll make a small donation as a thank you :) 

I will double-check if it all works now as soon as a I get around to it.

**Comment by JC5** [comment]
:+1:
