### ISSUE TITLE
Better overview of bills to be paid

### ISSUE THREAD

**Issue by TyrionWarMage** [firefly-iii/firefly-iii#8058]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Currently, it can become hard to determine which bills are outstanding, in case there are many bills in the list. 

### Solution

- Option to only show outstanding bills (active, next expected match in this period)
- Bills that are paid as well as outstanding should be shown as "Expected n days from now" as well, e.g 
![grafik](https://github.com/firefly-iii/firefly-iii/assets/5308190/61884182-7443-4b12-a5bb-6da2731ba76b) 
(Arguably, this may even be considered a bug)
- Should also show sum of outstanding bills (per section/overall)

### What are alternatives?

Sorting of bills by "paid this period" column. However, unclear how this would interact with the subsections.

**Comment by JC5** [comment]
I have some ideas for this for the new layout. I'm going to merge this with the epic: https://github.com/firefly-iii/firefly-iii/issues/6306
