### ISSUE TITLE
Newly created rules have "1" as description

### ISSUE THREAD

**Issue by avee87** [firefly-iii/firefly-iii#8069]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

This is a minor but annoying issue. For some reason when you create a rule with empty description it ends up with "1" which needs to be then manually removed.
Tested and reproduced on demo instance.
<img width="1116" alt="Screenshot 2023-10-17 at 17 48 32" src="https://github.com/firefly-iii/firefly-iii/assets/6134677/4dc385a1-77e0-406f-8699-4ad396d84bc9">

### Debug information

Debug information generated at 2023-10-17 17:44:43 for Firefly III version **v6.0.27**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.27 / v2.0.10 / 20 (exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.11 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>723, base <span>#</span>39</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/London + Europe/London</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_GB + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-10-17 00:00:00 (17 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span></td></tr><tr><td>Session start</td><td>2023-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-10-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36</td></tr></tbody></table>

### Steps to reproduce

1. Create a new rule, give it a name
2. Check "Stop processing" checkbox - this seems to be important!
3. Set dummy actions like "if description contains dfgadsfgxfg set description to asdfadsfgsdfgdsf"
4. Save rule and observe it has "1" in description row

Example rule: https://demo.firefly-iii.org/rules/edit/7

**Comment by Maxco10** [comment]
Hello,
I made a pull request for your issue. https://github.com/firefly-iii/firefly-iii/pull/8070

**Comment by Maxco10** [comment]
We can close this issue becuase my pull request has been merged and the fix will be avaiable in the next release.

**Comment by JC5** [comment]
I'll mark it as fixed and it will auto close when the release is out 👍
