### ISSUE TITLE
Nordigen Import - Unexpected empty response from Firefly III.

### ISSUE THREAD

**Issue by edent** [firefly-iii/firefly-iii#8071]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Tried to import a UK bank account into Firefly III using Nordigen. None of the transactions imported, the error message was:

> Could not create transaction. Unexpected empty response from Firefly III. Check the logs.

Error log shows:

```
[2023-10-17 21:25:25] local.DEBUG: Now in App\Services\Shared\Import\Status\SubmissionStatusManager::storeSubmissionStatus(conv-oSFRc7IFFImw): submission_running  
[2023-10-17 21:25:25] local.DEBUG: Group is empty, may not have been stored correctly.  
[2023-10-17 21:25:25] local.DEBUG: Now submitting transaction 61/61  
[2023-10-17 21:25:25] local.DEBUG: Duplicate detection method is "classic", so this method is skipped (return true).  
[2023-10-17 21:25:25] local.DEBUG: Transaction #61 is not checked beforehand on uniqueness.  
[2023-10-17 21:25:25] local.DEBUG: Going to map data for this line.  
[2023-10-17 21:25:25] local.DEBUG: Submitting to Firefly III: {
    "apply_rules": true,
    "error_if_duplicate_hash": true,
    "transactions": [
        {
            "type": "deposit",
            "date": "2022-09-17",
            "amount": "19.7",
            "description": "Bank credit PAYPAL 123456 78901234",
            "payment_date": "2022-09-17",
            "order": 0,
            "currency_code": "GBP",
            "tags": [],
            "category_name": null,
            "category_id": null,
            "notes": "",
            "external_id": "FEC2FF[REDACTED]",
            "internal_reference": "",
            "additional-information": "",
            "destination_id": 1,
            "source_name": "(unknown source account)"
        }
    ]
}
[2023-10-17 21:25:25] local.ERROR: Could not create transaction. Unexpected empty response from Firefly III. Check the logs.  
[2023-10-17 21:25:25] local.DEBUG: Add error on index #60 (line no. 61): Could not create transaction. Unexpected empty response from Firefly III. Check the logs.  
```

### Debug information

Debug information generated at 2023-10-17 22:39:28 for Firefly III version **v6.0.27**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.27 / v2.0.10 / 20 (exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.10 / litespeed / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>33554432 (32 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/London</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, daily / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2023-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-10-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0</td></tr></tbody></table>

### Expected behaviour

I'd like all the transactions imported :-)

### Steps to reproduce

1. Install Firefly III on server. Configure and validate. Get personal auth token.
2. Install Importer on server (different domain name). Configure with Nordigen keys & auth token.
3. On importer, select UK Bank "Nationwide", authenticate with Nordigen and Bank.
4. Keep clicking next

### Additional info

I've tried a couple of times and it has failed.  Same happens if I try to import a CSV.

I'm sure the Personal Access Token is working as the importer is able to see a list of my accounts.

**Comment by JC5** [comment]
Could you share the logs from Firefly III's side?

**Comment by edent** [comment]
There's nothing in `/storage/logs` - do I need to look elsewhere?

If I manually call the API, the transaction gets posted. For example:

```
curl -X 'POST' \
  'https://example.com/public/api/v1/transactions' \
  -H 'accept: application/vnd.api+json' \
  -H 'Authorization: Bearer ...' \
  -H 'Content-Type: application/json' \
  -d '{
    "apply_rules": true,
    "error_if_duplicate_hash": true,
    "transactions": [
        {
            "type": "deposit",
            "date": "2022-09-17",
            "amount": "19.7",
            "description": "Bank credit PAYPAL 123456 78901234",
            "payment_date": "2022-09-17",
            "order": 0,
            "currency_code": "GBP",
            "tags": [],
            "category_name": null,
            "category_id": null,
            "notes": "",
            "external_id": "FEC2FF[REDACTED]",
            "internal_reference": "",
            "additional-information": "",
            "destination_id": 1,
            "source_name": "(unknown source account)"
        }
    ]
}'
```

That works fine on the command line.

Is it that the API requires `/public/`? If so, wouldn't the other API calls fail?

**Comment by JC5** [comment]
It should not be under /public, but that's not something I can fix I'm afraid.
