### ISSUE TITLE
[Kubernetes/Helm Chart]: Add extraVolumes, extraVolumeMounts

### ISSUE THREAD

**Issue by Jauchi** [firefly-iii/firefly-iii#8075]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hello!

The helm chart does not allow you to specify custom Volumes.
This is needed, if the application, for example, needs certificate files mounted from a secret, or similar

### Solution

Add the following to the helm chart:

https://github.com/helm/charts/issues/11981

### What are alternatives?

All files need to be uploaded to uploads, which might be a security issue, depending on the kind of file uploaded there.

Also, for Kubernetes Users, the `_FILE` env variables become useless.

### Additional context

pinging @morremeyer because he is listed as maintainer for helm charts.

**Comment by JC5** [comment]
I believe there is already a ticket about this. I will look for it later. 

Either way, the user you mention no longer maintains the kubernetes files. Can you tell me where you found the reference?

**Comment by Jauchi** [comment]
> Either way, the user you mention no longer maintains the kubernetes files. Can you tell me where you found the reference?

I know that `extraEnv`, `extraVolumes` and `extraVolumeMounts` can be specified in most charts, since it allows you to add custom files and directories to containers (like `volumes` in docker), but it's missing here.
I came across an example when searching for how to do it in helm (maybe I was missing something).

I am by no means an expert in writing helm charts, I just use them a lot.
From what I understand, adding some documentation to [charts/firefly-iii/values.yaml](https://github.com/firefly-iii/kubernetes/blob/1086e2904c1790cb0371793fd05a319abcaab241/charts/firefly-iii/values.yaml) and the template code to [charts/firefly-iii/templates/deployment.yaml](https://github.com/firefly-iii/kubernetes/blob/1086e2904c1790cb0371793fd05a319abcaab241/charts/firefly-iii/templates/deployment.yaml) should do the trick.

**Comment by Jauchi** [comment]
Also found the issue your were probably referring to: #6195.
That's for the importer, I need basically the same thing for firefly-iii.

**Comment by JC5** [comment]
Fixed :+1:
