### ISSUE TITLE
Importer option to include opposing account name to end of description

### ISSUE THREAD

**Issue by L-E-0-N** [firefly-iii/firefly-iii#8077]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi, opposing account names get lost through importing when the IBAN is the same as an existing opposing account. 

For example:

Existing account: Mollie payment - NL01 RABO 1234 5678 90
Imported transaction: ASOS Clothing - NL01 RABO 1234 5678 90

In this instance, the ASOS Clothing opposing account name get lost because the IBAN is already existing under the name 'Mollie payment' which is a payment provider which a lot of different shops are using.

### Solution

Quick solution would be to add an extra option to the role configuration within the importer to add the account name BOTH as opposing account name AND to the end of the description. Similar to a rule configuration.

In the example above, the 'ASOS Clothing' account name would still be lost, but it's still discoverable through the description of the transaction. Which we can use within the ruling triggers for proper organisation :)

### What are alternatives?

Ideally Firefly would support multiple names of the same IBAN like the regular bank apps.

**Comment by JC5** [comment]
No. These kinds of exceptions are a dime a dozen. I can think of 15 different ways banks do this and i will not be adding options to parse them.

**Comment by L-E-0-N** [comment]
> No. These kinds of exceptions are a dime a dozen. I can think of 15 different ways banks do this and i will not be adding options to parse them.

Actually I got quite a few of them already just from this year alone. Similar cases for all these accounts:

Adyen
Pay.nl
Mollie
Stripe
Rabobank

These all include multiple transactions from different sources without any proper descriptions so within Firefly they will be unknown which is a shame.

**Comment by JC5** [comment]
I'm aware of the issue. But like I said, there are more banks than yours. They all have different ways of trying to handle this. Check out the ticket about the ultimate creditor field.
