### ISSUE TITLE
Cannot login until you confirm your email address.

### ISSUE THREAD

**Issue by Ksaehr** [firefly-iii/firefly-iii#8095]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I changed my email address and followed every step. I do not have a mail server configured for email messages. Nor do I wish to expose it to the outside world. How can I update and change user credentials without having to receive a confirmation email? I am currently logged out and do not wish to reinstall everything from scratch. 

### Debug information

I changed my email address and followed every step. I do not have a mail server configured for email messages. Nor do I wish to expose it to the outside world. How can I update and change user credentials without having to receive a confirmation email? I am currently logged out and do not wish to reinstall everything from scratch.

**Comment by Ksaehr** [comment]
I managed to sort it out. I just deleted the table for the user

**Comment by JC5** [comment]
That also works. 

https://docs.firefly-iii.org/firefly-iii/advanced-installation/email/#email

Set `MAIL_MAILER=log`  and set `APP_LOG_LEVEL=debug`
