### ISSUE TITLE
Bills with e.g. weekly skips over 3 are expecting payments too often

### ISSUE THREAD

**Issue by simphide** [firefly-iii/firefly-iii#8099]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Reoccuring bills that skip iterations seem to not work. They are expected every week eventhough they should only be expected every 3 weeks. It has been working in the past:
![image](https://github.com/firefly-iii/firefly-iii/assets/8183517/4dd10abe-e99a-4df1-9185-0a3355399b9d)

### Debug information

Debug information generated at 2023-10-26 18:12:38 for Firefly III version **v6.0.27**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.27 / v2.0.10 / 20 (exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.11 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>723, base <span>#</span>39</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + CET</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-10-26 00:00:00 (18 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>2 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-10-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The bill should only be expected on the 25th of October.

### Steps to reproduce

Create a reoccuring bills skipping some weeks.

**Comment by JC5** [comment]
Bills right? Not recurring transactions. I'll check it out!

**Comment by simphide** [comment]
> Bills right? Not recurring transactions. I'll check it out!

Yes bills, correct!

**Comment by simphide** [comment]
Hi @JC5 your fix seem to have worked!
![image](https://github.com/firefly-iii/firefly-iii/assets/8183517/4d762e03-8d13-4ad6-9ade-9f0f1993e12a)

The only problem that know occurs that bills that are not expected in the current time period are having the wrong "next occurance" date:
![image](https://github.com/firefly-iii/firefly-iii/assets/8183517/f8e37817-7484-4ba6-8937-e33401fbad51)

**Comment by JC5** [comment]
I can't tell from the information you've given me. What's the start date of the bill please?

**Comment by simphide** [comment]
The bill started on the first of October 2022 and should be expected on the first of January 2024 again (quarterly)

**Comment by Turnos** [comment]
> Hi @JC5 your fix seem to have worked! ![image](https://user-images.githubusercontent.com/8183517/279614614-4d762e03-8d13-4ad6-9ade-9f0f1993e12a.png)
> 
> The only problem that know occurs that bills that are not expected in the current time period are having the wrong "next occurance" date: ![image](https://user-images.githubusercontent.com/8183517/279614957-f8e37817-7484-4ba6-8937-e33401fbad51.png)

I have noticed the same. Bills that will not occur in this month, have not their "real" next occurence (e.g. 1st January 2024) but instead the current day displayed.

**Comment by JC5** [comment]
Could you at answer the same question please.

**Comment by JC5** [comment]
And one of you open a new ticket this is bloody annoying to do in a closed ticket, the bot is there for a reason.
