### ISSUE TITLE
Bulk edit does not work if one transaction's title has at least 256 characters

### ISSUE THREAD

**Issue by baflo** [firefly-iii/firefly-iii#8103]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Bulk edit like, for instance, on [this search's results](https://demo.firefly-iii.org/search?search=transaction_type%3AWithdrawal+AND+date_is%3A2023-10-28) fail silently without any change when at least one transaction has at least 256 characters.

On hitting "Update these transactions" it just reloads the page and resets all data without showing any error message.

![image](https://github.com/firefly-iii/firefly-iii/assets/834350/d1938f45-17e2-4def-82c2-3c1140259954)

### Debug information

Happens in the demo instance.

### Expected behaviour

Either print an error message or, more favourable, allow to update the values.

### Steps to reproduce

1. Create a transactions whose title has at least 256 characters.
2. Start a bulk edit which included the new transaction
3. Try and change some data
4. Hit "Update transactions"

**Comment by JC5** [comment]
Nice find, I'll check it out!
