### ISSUE TITLE
Bulk transactions editor, change description

### ISSUE THREAD

**Issue by stuzer05** [firefly-iii/firefly-iii#8104]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi!

I have many transaction with the same name and I want to refactor their descriptions. But in bulk editor there's no suck option available. Is it possble to add a description field?

Thanks!

### Solution

Add description field here, to replace (blank by default, means no change to description)
![image](https://github.com/firefly-iii/firefly-iii/assets/23124682/422bfbc9-743b-4848-b664-d602a328d69d)

**Comment by JC5** [comment]
No, but this is on the list for the new layout :+1:
