### ISSUE TITLE
API: `GET v1/bills` can report empty string for date field `next_expected_match`

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#8106]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The `v1/bills` GET call can return a response with an empty `next_expected_match` string, sample from the demo page:

```
GET https://demo.firefly-iii.org/api/v1/bills?limit=10&page=1&start=2023-10-29&end=2023-11-10

[...]
   {
      "type": "bills",
      "id": "6",
      "attributes": {
        "created_at": "2023-10-29T19:04:38+01:00",
        "updated_at": "2023-10-29T20:17:20+01:00",
        "currency_id": "1",
        "currency_code": "EUR",
        "currency_symbol": "€",
        "currency_decimal_places": 2,
        "name": "Quarterly bill",
        "amount_min": "10.00",
        "amount_max": "20.00",
        "date": "2015-01-01T00:00:00+01:00",
        "end_date": null,
        "extension_date": null,
        "repeat_freq": "quarterly",
        "skip": 0,
        "active": true,
        "order": 6,
        "notes": null,
        "object_group_id": null,
        "object_group_order": null,
        "object_group_title": null,
        "next_expected_match": "",
        "next_expected_match_diff": "today",
        "pay_dates": [],
        "paid_dates": []
      },
      "links": {
        "0": {
          "rel": "self",
          "uri": "/bills/6"
        },
        "self": "https://demo.firefly-iii.org/api/v1/bills/6"
      }
    },
[...]
```

### Debug information

demo site

### Expected behaviour

The field is nullable according to the swagger docs, so it should be null instead of empty string when there is no value to provide.

### Additional info

I found #1987, which complains about the API returning null for that field. I don't understand why that was an issue back then, null is a valid response (according to the swagger docs).

**Comment by JC5** [comment]
Nice find, I'll pick it up!
