### ISSUE TITLE
Data Importer timeout using web interface

### ISSUE THREAD

**Issue by Ganneff** [firefly-iii/firefly-iii#8107]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The data importer fails on larger CSV input files send via the webinterface, would be nice if it works.

### Debug information

Debug information generated at 2023-10-29 22:33:49 Europe/Berlin for Firefly III Data Importer version **1.3.8**.

| Scope | Version |
| --- | --- |
| FIDI | 1.3.8 |
| Build | 317, 01-09-2023 18:06:24 UTC |
| PHP | 8.2.9 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0 |

### Expected behaviour

Import to end successful

### Steps to reproduce

1. Get a large cvs file (in my case it has 577 statements included, plus one header line).
1. Have a matching json file for the importer config.
1. Use the web interface and let it work.
1. In a different window, watch the log output from the importer container.

After a while, the web interface will switch itself to "The conversion could not be started, or failed due to an error. Please check the log files. Sorry about this :("
But the log shows no error, in fact it continues with the conversion and ends it successfully. But as the web interface went broken, you can't submit anymore.

A workaround is to split the file into smaller ones. Then the conversion finishes and you can start the submission.

**Fun** enough, it now goes and submits the smaller number of transactions -- except the webinterface at some point again thinks "I've got enough of this, let me outa here" and shows "The submission could not be started, or failed due to an error. Please check the log files. Sorry about this :( ".
Except, the web is (of course) ***lying*** again, as the logs of the docker container admit. The submission happily continues, despite the web interface gone crazy. And *all* of the transactions successfully get created.

**Comment by JC5** [comment]
Yes, that may happen. This is usually a combination of browser impatience and server configuration. I'm not going to fix this.

Please use the command line interface or break up the file in smaller pieces.
