### ISSUE TITLE
Data importer: Sliding date range window/offset (nordigen)

### ISSUE THREAD

**Issue by tboby** [firefly-iii/firefly-iii#8113]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like the ability to configure the data importer to filter transactions from nordigen to a date range between 5 and 30 days ago. As far as I can tell [partial](https://github.com/firefly-iii/data-importer/blob/main/app/Services/Shared/Configuration/Configuration.php#L1046 ) only uses notBefore, but could be extended to use notAfter as well.

### Solution

The ability to create a single json config which covers a date range that automatically updates on a daily basis. 

### What are alternatives?

- Writing a script which updates the json config for importing every day
- The importer tries to detect pending transactions (I doubt the openbanking api is consistent enough)
- The importer deletes any transactions that are no longer present (against your approach)

### Additional context

My use case it this: My bank (Nationwide, UK) shows pending transactions immediately, which causes holds to show as withdrawals... the simple solution is to just wait a few days before pulling the transactions!

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6061
