### ISSUE TITLE
Swagger API docs: wrong type in bills API endpoint

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#8115]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Similar to #7944, running into an issue with the Swagger API docs on the Bills API: `Bill` has a field `paid_dates` where the Swagger API docs report that `transaction_group_id` and `transaction_journal_id` return as strings, whereas in reality they are returned as int.

Looking through the swagger docs both are usually returned as strings, so I guess the swagger doc is correct and the API just returns it "wrong".

### Debug information

demo page

**Comment by JC5** [comment]
Nice find, I'll check it out. It's probably a bug. Thanks for reporting!

**Comment by JC5** [comment]
That one has been reported already.
