### ISSUE TITLE
Missing administration panel

### ISSUE THREAD

**Issue by jleeong** [firefly-iii/firefly-iii#812]
Firefly v 4.6.4
Attempting to enable mutli user mode for the application following a previous closed issue #741 
Under `Options` there is no `Administration` panel to navigate to

**Comment by JC5** [comment]
In your database, there should be one entry in the `users` table and it must be you. If not, remember which ID your email address has (eg 1 or 2).

Open the table `roles` and check out the ID of the "owner" role (should be 2 but it may differ).

Add a new entry to the `role_user` table. `user_id` your user ID, `role_id` the ID of the owner role.

**Comment by jleeong** [comment]
Great worked perfectly thank you
