### ISSUE TITLE
Feature Request; Apply rule actions on selected transactions

### ISSUE THREAD

**Issue by Londoneye02** [firefly-iii/firefly-iii#8124]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Use case: You have imported transactions that don't fit the rules that you have set up. But you know that a particular transaction fits a rule. But you will not need to use it again (for example you have been abroad, and you have a transaction in a restaurant that you will never visit again because it is , let's say, Bermuda...  Then you need to manually edit the transaction and add the data you want e.g destination account, category, labels. 

It would be very nice if you can apply a rule, without having to edit the rule and update, but just apply the actions of the rule to the selected transaction. It would save a lot of time when editing random transactions

### Solution

Execute rule actions on a selected transaction (without having to match the rule trigger)

### What are alternatives?

edit transactions manually

or edit the rule

**Comment by JC5** [comment]
No. It would be very confusing to have an option to apply rules *without* using their triggers.
