### ISSUE TITLE
Apply a rule right after you create or modify it

### ISSUE THREAD

**Issue by Londoneye02** [firefly-iii/firefly-iii#8126]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Be (optionally) able to execute a rule right after you create or modify it. Then you save the time of looking through your list of rules for the one you just created to execute it from there 

### Solution

Add a checkbox in the options section of the rule:

"Apply rule after updating"

**Comment by JC5** [comment]
No. Perhaps in the new layout, but probably no.

**Comment by Londoneye02** [comment]
Just to try to give more arguments on this, think when you're dealing with new transactions that would fit in a previously existing rule. If you want to apply the rule to the new transactions you need to:

Edit the rule

Go back to the rules page and look for the same rule again, either by scrolling through (in my case) a long list of them, or by typing some keyword on the browser search tool. 

Click on the execute rule button

It leads you to check which accounts you need to use

Apply.

In my opinion, these are many clicks and time that could be saved with a single checkbox

**Comment by JC5** [comment]
Yes they could, but I'm not going to add checkboxes and options to placate every use case, that only makes it more confusing.
