### ISSUE TITLE
Changing the period in the header doesn't have impact on reports

### ISSUE THREAD

**Issue by baflo** [firefly-iii/firefly-iii#8128]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

On the start page, there are links to reports for "IN+OUT" as well as "NET WORTH". On these report pages the period selector in the header does not have any impact on the period. This is contrary to "bills" page and the "budgets" page.

### Debug information

Happens on current demo instance.

### Expected behaviour

The period selector should have impact or at least there should be a "period navigator" as on the "budgets" page.

**Comment by JC5** [comment]
I see what you mean for the net worth report, but you know you can generate your own reports from `/reports`, right?

**Comment by baflo** [comment]
Yes, I know. It's just that I'd expect the period selector to work here. 

What also works is to select the period from the start page and then go to "In+Out"/"Net worth".

**Comment by JC5** [comment]
Yes, sorry, it won't work there.

**Comment by baflo** [comment]
👌
