### ISSUE TITLE
login/register pages do nothing but refresh

### ISSUE THREAD

**Issue by benvh** [firefly-iii/firefly-iii#813]
Just installed firefly-iii and I can vistit the login/register pages.
When trying to register or login however the pages simply refresh without doing anything. Nothing shows up in the logs either... 

running on debian jessie + nginx. Followed the install guide up until the registration part...  (debug logging is enabled in .env file)

**Comment by JC5** [comment]
When you submit the form it should (but clearly it doesn't) always tell you what went wrong. These messages will not be logged, generally speaking.

You can see the form itself though, that works?

**Comment by benvh** [comment]
No output whatsoever. The page simply refreshes [my current deploy](https://money.coder.town) Ignore the invalid cert. I haven't properly configured that...

**Comment by JC5** [comment]
I'm getting a 503, unfortunately.

**Comment by benvh** [comment]
Sorry my bad... It's accessible now.

**Comment by JC5** [comment]
In your .env file, try setting "force https" and possible the root URL.

**Comment by benvh** [comment]
Apparently it was the "APP_FORCE_SSL" option... thanks a lot!
