### ISSUE TITLE
All transactions options page

### ISSUE THREAD

**Issue by ahmaddxb** [firefly-iii/firefly-iii#8134]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would be nice to have an all transactions option here
![image](https://github.com/firefly-iii/firefly-iii/assets/43728586/f2971185-75d0-4c6a-8385-ae4e8e06c765)

It is not really efficient bouncing amoung the current separation of each transaction type.

If there is a way to currenly achieve this now and you can edit transactions from this view please let me know.

### Solution

Make an all transaction option page and differentiate deposits widthdraw and transfers by symbols or different text colours.

e.g 
deposits = green or down arrow ⬇️
widthdraw = red or ⬆️
transfers = blue or ↔️

**Comment by JC5** [comment]
This is on my list for the new layout, see https://github.com/firefly-iii/firefly-iii/issues/6304
