### ISSUE TITLE
Reconciled transactions can't be  "store(d) as new" with modified accounts or amounts

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#8138]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

With the latest change to reconciled transactions, you can no longer "store as new" on reconciled transactions with modified accounts or amounts:

![image](https://github.com/firefly-iii/firefly-iii/assets/109872040/aa6153ab-5f9d-485a-a5e5-f4dbca3ffba2)

### Debug information

Demo Page

### Expected behaviour

As "store as new" makes no modification to the reconciled transaction, it shouldn't fail.

**Comment by JC5** [comment]
Nice find, I'll pick it up!
