### ISSUE TITLE
Error (Undefined offset) on deleting a budget

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#814]
Hey,

i have run into an error (see [exception.txt](https://github.com/firefly-iii/firefly-iii/files/1278161/exception.txt)) and like to inform you about it.

### Steps to reproduce

1. Create a budget
2. Create a withdrawal assigned to this budget
3. Show the overview of the "Asset account" linked to the withdrawal
4. Delete just the budget (not the withdrawal itself)
5. Show the overview of the "Asset account" linked to the withdrawal again
6. There is an error with the "Expenses by budget"-Graph and Firefly-III generates an e-mail with an exception (see [exception.txt](https://github.com/firefly-iii/firefly-iii/files/1278161/exception.txt))

![screenshot_20170905_183748](https://user-images.githubusercontent.com/31184224/30072099-8b14de60-9269-11e7-98cc-0eb9db2e1883.png)

I've tried this with the demo-site a few minutes ago and the same error occurred (at least the error with the graph - i don't know about the e-mail :))

Regards
Nico

**Comment by JC5** [comment]
Nice find, these are always tricky. Thanks for reporting this bug, it will be fixed in the next release.

**Comment by nicoschreiner** [comment]
Thanks!
