### ISSUE TITLE
Firefly fails to login on Yunohost on Azure

### ISSUE THREAD

**Issue by fybx** [firefly-iii/firefly-iii#8140]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I deployed Yunohost on an Azure virtual machine (which broke my connection over SSH 😭) and installed Firefly. I tried to register the first user, and Firefly broke, too :(

---

Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Expected response code "250/251/252" but got code "553", with message "553 5.7.1 <fyb@yuno.fybx.dev>: Sender address rejected: not logged in".

This error occured in file /var/www/firefly-iii/app/Jobs/MailError.php on line 103 with code 0.

---

It seems that the user is created, but it's not possible to log in. Trying to log in with previous credentials causes the same exception.

### Debug information

I can't access the debug page, it redirects to the login page.

### Expected behaviour

I want to log in.

**Comment by JC5** [comment]
This is not a bug but a configuration problem. Your email settings seem to be wrong.

**Comment by fybx** [comment]
Allowing SMTP and IMAP ports solved my issue. Thanks for simply pointing out the cause.
