### ISSUE TITLE
Display the display_name of Nordigen accounts

### ISSUE THREAD

**Issue by erwineverts** [firefly-iii/firefly-iii#8142]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like that Firefly Importer would show Nordigen display_name when it's there.

My bank shows my name in the account name field and in the display_name field the actual account name. Now it's imposible to distinguish my accounts from eachother. (The one's without IBAN of course)

### Solution

Show the display_name instead or next to the account name

### Additional context

The description in gocardless interface
```json
{
    "account": {
        "resourceId": "***",
        "bban": "***",
        "currency": "EUR",
        "name": "***My actual name***",
        "displayName": "car savings",
        "product": "***",
        "cashAccountType": "***",
        "usage": "PRIV"
    }
}
```

**Comment by JC5** [comment]
I'm going to merge this with https://github.com/firefly-iii/firefly-iii/issues/7977
