### ISSUE TITLE
In auto budget add option to add % of income

### ISSUE THREAD

**Issue by jurij-robba** [firefly-iii/firefly-iii#8155]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

First of all, thanks for the amazing software and all the work that goes into it. It truly is improvement over everything else i've been using before.

I have, what i hope is relatively simple feature request. Sometimes / often times i want to set budget (auto budget) to % of income. As in, long time ago i promised myself to spend 1% of everything i earn on books. I would like to keep track of my book budget. I am also paid hourly so my monthly income is far from set amount.

There are also other financial "models" and guides that often speak in terms of income. 10% to church / charity, 30 % to savings ect. setting that up in firefly is currently, best i can tell, not possible in any automatic way.

Again, thank you for all the effort.

### Solution

The way i expect this to work is to have set % amount and every time money arrives into account auto budget increases for that % of income.

### What are alternatives?

Current workaround: I have auto budget with rollover, add 0.1€ to it every month because 0 is not possible and then every month manually calculate money to be added.

**Comment by JC5** [comment]
Thanks for the compliments! It's a great idea but no, sorry. It's interesting but it also requires Firefly III to know which accounts to draw income from, what even defines income and all the options that come with it. It's a very small use case, and it's easier and more foolproof to just calculate it yourself.
