### ISSUE TITLE
Data importer - configurations additional fields (name/description/save first line)

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#8157]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I import from different sources and I use several json files with configurations inside my data importer directory.
Using filenames is not the best way to identify the configuration, and moreover it is not easy to be sure that the configuration is correct.

I'm suggesting to add some additional fields to better discriminate the saved configuration and possibly to check the file to be imported against a previous imported one.

I can provide a PR if you believe if could be useful.

### Solution

I'd suggest to apply these changes to the import form:
- add a name input field
- add a description textarea field
- add a 'save headers' checkbox field 

<img width="1120" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/115389/a32c107a-5ab4-4200-9b50-834c7b6e8f97">

- change the "skip form" subtext

<img width="1110" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/115389/c4ca4588-054e-4e96-ace5-3677baebea7c">

Then save the respective values inside the json configuration file.

Then, in the import file form:
- show the name value, pulled from inside the files, in the configuration dropdown

<img width="1134" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/115389/5561ac50-5562-4d61-bea4-ba05714d382c">

- when selecting a configuration, show the extended description text
<img width="1130" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/115389/847452f7-ce42-4eae-94a6-8fd04fb26d8f">

### What are alternatives?

Rename the files with an intelligible name?

### Additional context

The saved headerscould be used also to auto-match a configuration: select file, submit, highlight/preselect the configuration.

**Comment by JC5** [comment]
I don't really see the added value of these features to be honest. Adding a name and description feels superfluous because I believe the filename is perfectly fine to distinguish configuration files. 

I've not yet seen complaints of people who ran into the header-problem you describe, so I'm no sure why I should add the maintenance burden of a solution for a problem nobody seems to have.
