### ISSUE TITLE
Documentation about Google Maps API key is little incorrect

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#816]
Documentation says that:
> GOOGLE_MAPS_API_KEY - You may fill this in if you expect your Firefly III installation to contain and show over 10.000 tags.

which I ignored while configuring my installation, because I didn't expect to have that many tags. Today I wanted to set location for one tag, but map wouldn't load.

Turns out that, since June 22 2016, [Google requires API key for evey request](https://maps-apis.googleblog.com/2016/06/building-for-scale-updates-to-google.html). If not present, JavaScript will throw MissingKeyMapError with link to [the documentation](https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error).

I think that Firefly's documentation should link to page [Get a key](https://developers.google.com/maps/documentation/javascript/get-api-key) from Google's documentation.

**Comment by JC5** [comment]
Indeed it is! Thanks for telling me. I've updated the documentation accordingly.

**Comment by pkoziol** [comment]
Great. Thanks!
