### ISSUE TITLE
Bills on the first of the month not calculated in expected bill summation

### ISSUE THREAD

**Issue by derekprovance** [firefly-iii/firefly-iii#8163]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

On the bill page, when the date is set to the first of the month for any specific bill, it's no longer calculated in the `Sum (US Dollar) (all active expected bills only)` column. The next expected date is also Unknown.

<img width="515" alt="Screenshot 2023-11-15 at 09 31 40" src="https://github.com/firefly-iii/firefly-iii/assets/4622432/5c691e97-6c83-4ebe-957c-d5293a2972e0">
<img width="559" alt="Screenshot 2023-11-15 at 09 31 21" src="https://github.com/firefly-iii/firefly-iii/assets/4622432/07765a24-3ed5-43f2-8735-fd99c8f1bd5c">

A temporary workaround is setting the due date to the second day of the month

### Debug information

Debug information generated at 2023-11-15 16:33:37 for Firefly III version **v6.0.30**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.30 / v2.0.11 / 21 (exp. 21)</td></tr><tr><td>PHP version</td><td>8.2.9 / fpm-fcgi / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>20971520 (20 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + America/Denver</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>redis</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-11-08 18:45:48 (6 days ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has reconciled">:ledger:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-11-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-11-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

Bills due at the first of the month are calculated in the expected bill sum. 

### Steps to reproduce

1. Create a new bill
2. Set the due date for the first of the month
3. Profit

**Comment by derekprovance** [comment]
I've confirmed this is also happening on the demo site, in case it's helpful for initial investigation

**Comment by JC5** [comment]
Thanks, I'll check it out!

**Comment by JC5** [comment]
I can't replicate this unfortunately. It seems to work fine.

**Comment by derekprovance** [comment]
Hey @JC5 , if you go to the demo site, you can see it without changing anything. 

<img width="1476" alt="Screenshot 2023-11-21 at 12 16 39" src="https://github.com/firefly-iii/firefly-iii/assets/4622432/
<img width="1138" alt="Screenshot 2023-11-21 at 12 16 48" src="https://github.com/firefly-iii/firefly-iii/assets/4622432/f321058d-21fc-47c8-9058-186c5a32cf0d">
70a7a385-35f4-4bbb-8677-d2c31b1f8550">

Just go to Bills and look at the Expected bills sum, and click on Rent to see the unknown

**Comment by JC5** [comment]
Thanks. Only happens when a transaction is already linked for the current period. I'll see if I can make it jump to the next period instead.
