### ISSUE TITLE
Piggy bank "saved so far" not updated

### ISSUE THREAD

**Issue by rmu1987** [firefly-iii/firefly-iii#8167]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello,

I'm using FireflyIII version 6.0.30 and i just added money to my already existing piggy bank called "Reizen 2023".
The amount displayed under Piggy banks column: "Saved so far" (gespaard in Dutch) is different (€ 1.848,70) than what the graph shows when i open the piggy bank (2.034,81)

The 2.034.81 is the expected amount.

Also see the screenshot:
![Screenshot 2023-11-16 at 13 42 54](https://github.com/firefly-iii/firefly-iii/assets/68034778/6cea9f0e-06c6-49da-b0b8-fbc13d8f54cb)

Any idea what have gone wrong? My other piggy banks are not showing this behavior.

### Debug information

Debug information generated at 2023-11-16 13:44:34 for Firefly III version **v6.0.30**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.30 / v2.0.11 / 21 (exp. 21)</td></tr><tr><td>PHP version</td><td>8.2.12 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>751, base <span>#</span>40</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Amsterdam</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>debug, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-11-16 00:00:00 (13 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-11-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-11-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>nl_NL</td></tr><tr><td>User locale</td><td>nl_NL</td></tr><tr><td>Locale(s) supported</td><td>nl_NL.utf8: :white_check_mark:<br>nl_NL.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0</td></tr></tbody></table>

### Expected behaviour

I expected the amount saved (gespaard) to be 2.034,81 instead of 1.848,70

**Comment by JC5** [comment]
What happens when you browse to `/flush`?

**Comment by rmu1987** [comment]
I browsed to it, and it redirects me to the home page (no errors or something) i also tried other browsers (to check for caching issues) but nothing changed

**Comment by JC5** [comment]
Then I have no clue, I can't replicate this. What happens when you add the amount again?

**Comment by rmu1987** [comment]
I tried adding 100euro with the plus (+) sign, than the amount saved is € 1.948,70 (so 100euro more then before)

I then removed the 100euro and also removed the last added amount, and re-added this, but nothing changed, the graph shows the correct (expected) amount and the piggy bank itself shows less, just as the initial screenshot is showing.

Is there other info i could give you so you can troubleshoot this?

**Comment by JC5** [comment]
Check out https://docs.firefly-iii.org/firefly-iii/faq/other/#how-do-i-enable-debug-mode

And let me know if it reports anything strange when you try to add or remove amounts.

**Comment by rmu1987** [comment]
Hello,

I added 1000euro, and after that removed 1000euro, with a transaction like i would do normally.

The remove logging:

> [2023-12-01 16:14:48] local.DEBUG: Now in FireflyIII\Support\Request\ChecksLogin::authorize
> [2023-12-01 16:14:48] local.DEBUG: Request class has no acceptedRoles array
> [2023-12-01 16:14:48] local.DEBUG: Collect rules of TransactionStoreRequest
> [2023-12-01 16:14:48] local.DEBUG: Going to validate source_id
> [2023-12-01 16:14:48] local.DEBUG: Going to validate destination_id
> [2023-12-01 16:14:48] local.DEBUG: Going to validate piggy_bank_id
> [2023-12-01 16:14:48] local.DEBUG: Now in getTransactionsArray
> [2023-12-01 16:14:48] local.DEBUG: Transactions key exists and is array.
> [2023-12-01 16:14:48] local.DEBUG: Now going to validateOneTransaction
> [2023-12-01 16:14:48] local.DEBUG: Now in validateOneTransaction
> [2023-12-01 16:14:48] local.DEBUG: Now in getTransactionsArray
> [2023-12-01 16:14:48] local.DEBUG: Transactions key exists and is array.
> [2023-12-01 16:14:48] local.DEBUG: Added NO errors.
> [2023-12-01 16:14:48] local.DEBUG: Now done with validateOneTransaction
> [2023-12-01 16:14:48] local.DEBUG: Now in GroupValidation::validateDescriptions()
> [2023-12-01 16:14:48] local.DEBUG: Now in getTransactionsArray
> [2023-12-01 16:14:48] local.DEBUG: Transactions key exists and is array.
> [2023-12-01 16:14:48] local.DEBUG: Now in validateTransactionTypes()
> [2023-12-01 16:14:48] local.DEBUG: Now in getTransactionsArray
> [2023-12-01 16:14:48] local.DEBUG: Transactions key exists and is array.
> [2023-12-01 16:14:48] local.DEBUG: Now in validateForeignCurrencyInformation()
> [2023-12-01 16:14:48] local.DEBUG: Now in getTransactionsArray
> [2023-12-01 16:14:48] local.DEBUG: Transactions key exists and is array.
> [2023-12-01 16:14:48] local.DEBUG: Now in validateAccountInformation (TransactionValidation) ()
> [2023-12-01 16:14:48] local.DEBUG: Now in getTransactionsArray
> [2023-12-01 16:14:48] local.DEBUG: Transactions key exists and is array.
> [2023-12-01 16:14:48] local.DEBUG: Going to loop 1 transaction(s)
> [2023-12-01 16:14:48] local.DEBUG: Now in validateSingleAccount(0)
> [2023-12-01 16:14:48] local.DEBUG: Transaction type for validator is now "Transfer".
> [2023-12-01 16:14:48] local.DEBUG: Now in AccountValidator::validateSource() {"id":8,"name":"Vakantie spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: Now in validateTransferSource {"id":8,"name":"Vakantie spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: Now in findExistingAccount {"id":8,"name":"Vakantie spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: The search will be reversed!
> [2023-12-01 16:14:48] local.DEBUG: ID: Found Asset account account #8 ("Vakantie spaarrekening", IBAN "NLXXXXXXXXXXXXXXX")
> [2023-12-01 16:14:48] local.DEBUG: AccountValidator source is set to #8: "Vakantie spaarrekening" (Asset account)
> [2023-12-01 16:14:48] local.DEBUG: Valid source!
> [2023-12-01 16:14:48] local.DEBUG: Now in AccountValidator::validateDestination() {"id":3,"name":"Vermogens Spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: Now in validateTransferDestination {"id":3,"name":"Vermogens Spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: Now in findExistingAccount {"id":3,"name":"Vermogens Spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: The search will be reversed!
> [2023-12-01 16:14:48] local.DEBUG: ID: Found Asset account account #3 ("Vermogens Spaarrekening", IBAN "NLXXXXXXXXXXXXXXX")
> [2023-12-01 16:14:48] local.DEBUG: AccountValidator destination is set to #3: "Vermogens Spaarrekening" (Asset account)
> [2023-12-01 16:14:48] local.DEBUG: Now in sanityCheckReconciliation
> [2023-12-01 16:14:48] local.DEBUG: Now in sanityCheckForeignCurrency()
> [2023-12-01 16:14:48] local.DEBUG: Source: #8 "Vakantie spaarrekening (Asset account)"
> [2023-12-01 16:14:48] local.DEBUG: Destination: #3 "Vermogens Spaarrekening" (Asset account)
> [2023-12-01 16:14:48] local.DEBUG: Both accounts have the same currency, continue.
> [2023-12-01 16:14:48] local.DEBUG: Now in validateEqualAccounts()
> [2023-12-01 16:14:48] local.DEBUG: Now in getTransactionsArray
> [2023-12-01 16:14:48] local.DEBUG: Transactions key exists and is array.
> [2023-12-01 16:14:48] local.DEBUG: Now in validateGroupDescription()
> [2023-12-01 16:14:48] local.DEBUG: Now in getTransactionsArray
> [2023-12-01 16:14:48] local.DEBUG: Transactions key exists and is array.
> [2023-12-01 16:14:48] local.DEBUG: Now in API StoreController::store()
> [2023-12-01 16:14:48] local.DEBUG: get all data in TransactionStoreRequest
> [2023-12-01 16:14:48] local.DEBUG: Date object: 2023-12-01T00:00:00+01:00 (Europe/Amsterdam)
> [2023-12-01 16:14:48] local.DEBUG: Now in TransactionGroupFactory::create()
> [2023-12-01 16:14:48] local.DEBUG: Now in TransactionJournalFactory::create()
> [2023-12-01 16:14:48] local.DEBUG: Start of TransactionJournalFactory::create()
> [2023-12-01 16:14:48] local.DEBUG: Now creating journal 1/1
> [2023-12-01 16:14:48] local.DEBUG: The hash is: 4751279117fb17fa55943222c7a20191f19d014b4f62537bc2df78b06a5b5364 {"type":"transfer","date":"2023-12-01 00:00:00","order":null,"currency_id":null,"currency_code":"","foreign_currency_id":null,"foreign_currency_code":"","amount":"1000","foreign_amount":"","description":"Test2","source_id":8,"source_name":"Vakantie spaarrekening","source_iban":"","source_number":"","source_bic":"","destination_id":3,"destination_name":"Vermogens Spaarrekening","destination_iban":"","destination_number":"","destination_bic":"","budget_id":null,"budget_name":"","category_id":null,"category_name":"","bill_id":null,"bill_name":"","piggy_bank_id":6,"piggy_bank_name":"","reconciled":false,"notes":"","tags":null,"internal_reference":"","external_id":"","recurrence_id":null,"bunq_payment_id":"","external_url":"","sepa_cc":"","sepa_ct_op":"","sepa_ct_id":"","sepa_db":"","sepa_country":"","sepa_ep":"","sepa_ci":"","sepa_batch_id":"","interest_date":null,"book_date":null,"process_date":null,"due_date":null,"payment_date":null,"invoice_date":null}
> [2023-12-01 16:14:48] local.DEBUG: In errorIfDuplicate(4751279117fb17fa55943222c7a20191f19d014b4f62537bc2df78b06a5b5364)
> [2023-12-01 16:14:48] local.DEBUG: Now looking for a transaction type.
> [2023-12-01 16:14:48] local.DEBUG: Tried to search for "transfer", came up with "Transfer". Will return it.
> [2023-12-01 16:14:48] local.DEBUG: Now in findCurrencyNull()
> [2023-12-01 16:14:48] local.DEBUG: Searching for currency with code ...
> [2023-12-01 16:14:48] local.DEBUG: Grabbing default currency for this user...
> [2023-12-01 16:14:48] local.DEBUG: Final result: EUR
> [2023-12-01 16:14:48] local.DEBUG: Now in findCurrencyNull()
> [2023-12-01 16:14:48] local.DEBUG: Searching for currency with code ...
> [2023-12-01 16:14:48] local.DEBUG: Found nothing
> [2023-12-01 16:14:48] local.DEBUG: Now in FireflyIII\Factory\TransactionJournalFactory::validateAccounts
> [2023-12-01 16:14:48] local.DEBUG: Transaction type for validator is now "Transfer".
> [2023-12-01 16:14:48] local.DEBUG: Now in AccountValidator::validateSource() {"id":8,"name":"Vakantie spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: Now in validateTransferSource {"id":8,"name":"Vakantie spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: Now in findExistingAccount {"id":8,"name":"Vakantie spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: The search will be reversed!
> [2023-12-01 16:14:48] local.DEBUG: ID: Found Asset account account #8 ("Vakantie spaarrekening", IBAN "NLXXXXXXXXXXXXXXX")
> [2023-12-01 16:14:48] local.DEBUG: AccountValidator source is set to #8: "Vakantie spaarrekening" (Asset account)
> [2023-12-01 16:14:48] local.DEBUG: Valid source!
> [2023-12-01 16:14:48] local.DEBUG: Source seems valid.
> [2023-12-01 16:14:48] local.DEBUG: Now in AccountValidator::validateDestination() {"id":3,"name":"Vermogens Spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: Now in validateTransferDestination {"id":3,"name":"Vermogens Spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: Now in findExistingAccount {"id":3,"name":"Vermogens Spaarrekening","iban":null,"number":null}
> [2023-12-01 16:14:48] local.DEBUG: The search will be reversed!
> [2023-12-01 16:14:48] local.DEBUG: ID: Found Asset account account #3 ("Vermogens Spaarrekening", IBAN "NLXXXXXXXXXXXXXXX")
> [2023-12-01 16:14:48] local.DEBUG: AccountValidator destination is set to #3: "Vermogens Spaarrekening" (Asset account)
> [2023-12-01 16:14:48] local.DEBUG: Source info: {"id":8,"name":"Vakantie spaarrekening","iban":"","number":"","bic":"","currency_id":1}
> [2023-12-01 16:14:48] local.DEBUG: Destination info: {"id":3,"name":"Vermogens Spaarrekening","iban":"","number":"","bic":"","currency_id":1}
> [2023-12-01 16:14:48] local.DEBUG: Now calling getAccount for the source.
> [2023-12-01 16:14:48] local.DEBUG: Now in getAccount(source) {"id":8,"name":"Vakantie spaarrekening","iban":"","number":"","bic":"","currency_id":1}
> [2023-12-01 16:14:48] local.DEBUG: Transaction = Transfer, source account should be in: Asset account, Loan, Debt, Mortgage. Direction is source.
> [2023-12-01 16:14:48] local.DEBUG: Found "account_id" object: #8, "Vakantie spaarrekening" of type Asset account (1)
> [2023-12-01 16:14:48] local.DEBUG: Already have account #8 ("Vakantie spaarrekening"), return that.
> [2023-12-01 16:14:48] local.DEBUG: Already have account #8 ("Vakantie spaarrekening"), return that.
> [2023-12-01 16:14:48] local.DEBUG: Already have account #8 ("Vakantie spaarrekening"), return that.
> [2023-12-01 16:14:48] local.DEBUG: Now calling getAccount for the destination.
> [2023-12-01 16:14:48] local.DEBUG: Now in getAccount(destination) {"id":3,"name":"Vermogens Spaarrekening","iban":"","number":"","bic":"","currency_id":1}
> [2023-12-01 16:14:48] local.DEBUG: Transaction = Transfer, destination account should be in: Asset account, Loan, Debt, Mortgage. Direction is destination.
> [2023-12-01 16:14:48] local.DEBUG: Found "account_id" object: #3, "Vermogens Spaarrekening" of type Asset account (1)
> [2023-12-01 16:14:48] local.DEBUG: Already have account #3 ("Vermogens Spaarrekening"), return that.
> [2023-12-01 16:14:48] local.DEBUG: Already have account #3 ("Vermogens Spaarrekening"), return that.
> [2023-12-01 16:14:48] local.DEBUG: Already have account #3 ("Vermogens Spaarrekening"), return that.
> [2023-12-01 16:14:48] local.DEBUG: Done with getAccount(2x)
> [2023-12-01 16:14:48] local.DEBUG: Now in getCurrencyByAccount()
> [2023-12-01 16:14:48] local.DEBUG: Now in getCurrency()
> [2023-12-01 16:14:48] local.DEBUG: Currency is now #1 (EUR) because of account #8 (Vakantie spaarrekening)
> [2023-12-01 16:14:48] local.DEBUG: Now in getCurrency()
> [2023-12-01 16:14:48] local.DEBUG: Currency is now #1 (EUR) because of account #3 (Vermogens Spaarrekening)
> [2023-12-01 16:14:48] local.DEBUG: Date: 2023-12-01T00:00:00+01:00 (Europe/Amsterdam)
> [2023-12-01 16:14:48] local.DEBUG: Created new journal #1183: "Test2"
> [2023-12-01 16:14:48] local.DEBUG: Created transaction #2365 (EUR -1000.000000000000, account Vakantie spaarrekening), part of journal #1183
> [2023-12-01 16:14:48] local.DEBUG: Account already has IBAN information, will not update.
> [2023-12-01 16:14:48] local.DEBUG: Created transaction #2366 (EUR 1000, account Vermogens Spaarrekening), part of journal #1183
> [2023-12-01 16:14:48] local.DEBUG: Account already has IBAN information, will not update.
> [2023-12-01 16:14:48] local.DEBUG: Now in findCategory()
> [2023-12-01 16:14:48] local.DEBUG: Searching for category with ID #0...
> [2023-12-01 16:14:48] local.DEBUG: Searching for category with name ...
> [2023-12-01 16:14:48] local.DEBUG: Found category result is null? true
> [2023-12-01 16:14:48] local.DEBUG: Will now store piggy event.
> [2023-12-01 16:14:48] local.DEBUG: Searching for piggy information.
> [2023-12-01 16:14:48] local.DEBUG: Found piggy based on #6, will return it.
> [2023-12-01 16:14:48] local.DEBUG: Now in PiggyBankEventCreate for a Transfer
> [2023-12-01 16:14:48] local.DEBUG: Found repetition
> [2023-12-01 16:14:48] local.DEBUG: Now in getExactAmount(6, 6, 1183)
> [2023-12-01 16:14:48] local.DEBUG: Piggy bank #6 currency is EUR
> [2023-12-01 16:14:48] local.DEBUG: Currency will draw money out of piggy bank. Source currency is EUR
> [2023-12-01 16:14:48] local.DEBUG: Use normal amount
> [2023-12-01 16:14:48] local.DEBUG: The currency is EUR and the amount is -1000.000000000000
> [2023-12-01 16:14:48] local.DEBUG: Will add/remove -1000.000000 to piggy bank #6 ("Reizen 2023")
> [2023-12-01 16:14:48] local.DEBUG: addAmountToRepetition: -1000.000000000000
> [2023-12-01 16:14:48] local.DEBUG: Remove amount.
> [2023-12-01 16:14:48] local.DEBUG: addAmount [a]: Trigger change for negative amount.
> [2023-12-01 16:14:48] local.DEBUG: Created piggy bank event for piggy bank #6 with amount -1000.000000000000
> [2023-12-01 16:14:48] local.DEBUG: Create piggy event.
> [2023-12-01 16:14:48] local.DEBUG: Now in storeTags()
> [2023-12-01 16:14:48] local.DEBUG: Tags is not an array, break.
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "sepa_cc", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "sepa_ct_op", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "sepa_ct_id", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "sepa_db", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "sepa_country", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "sepa_ep", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "sepa_ci", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "sepa_batch_id", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "external_url", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "interest_date", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "book_date", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "process_date", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "due_date", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "payment_date", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "invoice_date", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "recurrence_id", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "internal_reference", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "bunq_payment_id", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "import_hash", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "import_hash_v2", with value "4751279117fb17fa55943222c7a20191f19d014b4f62537bc2df78b06a5b5364".
> [2023-12-01 16:14:48] local.DEBUG: Going to create new meta-data entry to store "import_hash_v2".
> [2023-12-01 16:14:48] local.DEBUG: Will update value and return.
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "external_id", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "original_source", with value "ff3-v6.0.30|api-v2.0.11".
> [2023-12-01 16:14:48] local.DEBUG: Going to create new meta-data entry to store "original_source".
> [2023-12-01 16:14:48] local.DEBUG: Will update value and return.
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "recurrence_total", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "recurrence_count", with value "".
> [2023-12-01 16:14:48] local.DEBUG: Going to store meta-field "recurrence_date", with value "".
> [2023-12-01 16:14:48] local.INFO: Will not run rules on group #1180
> [2023-12-01 16:14:48] local.DEBUG: FireflyIII\Handlers\Events\StoredGroupEventHandler::triggerWebhooks
> [2023-12-01 16:14:48] local.INFO: Will not fire webhooks for transaction group #1180

I dont see anything strange in it. (I renamed the IBAN numbers myself)

I also removed 10euro and added 10 euro by hand using the + and - signs at the piggy bank:

> [2023-12-01 16:17:52] local.DEBUG: addAmount [a]: Trigger change for negative amount.
> [2023-12-01 16:17:52] local.DEBUG: Created piggy bank event for piggy bank #6 with amount -10.000000000000
> [2023-12-01 16:17:52] local.DEBUG: Now in resetOrder
> [2023-12-01 16:17:58] local.DEBUG: Left on account: 204.650000000000 on 2023-12-01
> [2023-12-01 16:17:58] local.DEBUG: Saved so far: 1838.700000000000
> [2023-12-01 16:17:58] local.DEBUG: Left to save: 1964.170000000000
> [2023-12-01 16:17:58] local.DEBUG: Maximum amount: 204.650000000000
> [2023-12-01 16:17:58] local.DEBUG: Compare <= 0? -1, so true
> [2023-12-01 16:17:58] local.DEBUG: addAmount [b]: Trigger change for positive amount.
> [2023-12-01 16:17:58] local.DEBUG: Created piggy bank event for piggy bank #6 with amount 10

At the moment the Graph and table are still showing the same information as before (the initial screenshot) and when i added the amount the amount "gespaard" was 1000 more, and the graph also (so 3034,81)

At my other piggy banks the amount "gespaard" and the graph display the same amount.

**Comment by JC5** [comment]
So the amounts are correct, but the chart is broken, right?

**Comment by JC5** [comment]
Two things happen when you add or remove money to a piggy bank:

1. The amount is increased or decreased. 
2. A "piggy bank event" is created (with date, and optionally a reference to the transaction)

This doesn't happen unless there is room for the money. Your logs indicate this is so:

```
[2023-12-01 16:17:58] local.DEBUG: Maximum amount: 204.650000000000
[2023-12-01 16:17:58] local.DEBUG: Compare <= 0? -1, so true
[2023-12-01 16:17:58] local.DEBUG: addAmount [b]: Trigger change for positive amount.
```

So unless you have logs to indicate otherwise I have very little to go on in terms of debugging. The amount on the right ("Gespaard") is the amount that Firefly III believes is in the piggy bank. That's the primary amount. The piggy bank events are just for the chart and are NOT used for any math.

**Comment by JC5** [comment]
Thanks, be sure to open a new ticket when something happens.
