### ISSUE TITLE
Multiple users on the same stack!

### ISSUE THREAD

**Issue by vClouds** [firefly-iii/firefly-iii#817]
firefly 4.6.4 on psql 9.6.5

`admin@domain.com` were used to initiate the stack as `site owner` with such current/saving accounts and custom `currency` set as default.

Registering another `user1@domain.com` upon unchecked `Single user mode` and `Is demo site` by the `admin` is somehow opening isolated different stack, in other words, completely different books does not show the current/saving accounts added by the `admin` user.

The above behavior is good for completely separate users' accounts from `cloud` points of view, but does not qualify with `collaboration` perspectives and `Administration` panel does allow admin to set others as admin.

Please advise on how multiple users can access the same stack for adding bookings and/or transactions on the same accounts?

Below are the records of users, roles and role_user tables.
![screenshot from 2017-09-08 00-25-05x](https://user-images.githubusercontent.com/24693741/30183917-3a7d2096-942d-11e7-9c5f-4e9acc93033b.png)
![screenshot from 2017-09-08 00-24-40x](https://user-images.githubusercontent.com/24693741/30183915-3a77b93a-942d-11e7-9130-b09139a84a70.png)
![screenshot from 2017-09-08 00-24-01x](https://user-images.githubusercontent.com/24693741/30183916-3a7a5ca8-942d-11e7-96d9-1fdbde6579c9.png)

**Comment by JC5** [comment]
Firefly III does not support shared "stacks". Each user has its own separated administration. See also the [often requested features](https://firefly-iii.github.io/requested-features.html) under "Can we share data amongst users?"

**Comment by Acvarium** [comment]
How it can be, that akaunting has this feature (users can be assigned to the companies and work in collaboration) and yet it is such a core problem for you?

**Comment by Acvarium** [comment]
I like your tool better than Akaunting, but without this feature it is useless for me

**Comment by JC5** [comment]
Are you interested in an explanation from a useless application?
