### ISSUE TITLE
Category bar graph labels are hidden quite aggressively.

### ISSUE THREAD

**Issue by saua** [firefly-iii/firefly-iii#8171]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The category labels on the x axis of the category graph on the dashboard side are hidden quite aggressively as the browser window gets narrower in relation to the number of categories to show.

### Debug information

Debug information generated at 2023-11-17 10:37:47 for Firefly III version **v6.0.30**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.30 / v2.0.11 / 21 (exp. 21)</td></tr><tr><td>PHP version</td><td>8.2.12 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>751, base <span>#</span>40</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Vienna + Europe/Vienna</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / remote_user_guard</td></tr><tr><td>Login headers</td><td>HTTP_X_AUTHENTIK_EMAIL + HTTP_X_AUTHENTIK_EMAIL</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-11-17 00:00:00 (10 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-11-17 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The labels should be shown as long as reasonable and not hidden as early as they are.

### Steps to reproduce

1. have a high number of used categories in the current time span (can also be reproduced with only a few, but then only on very narrow browser windows)
2. navigate to the dashboard and scroll to the category bar chart, if necessary
3. (if on desktop) reduce the width of the browser window until labels on the bar charts disappear

### Additional info

Obviously at some point some labels need to be hidden (can't seriously display 1000 labels there), but as a rough guess there could be at least twice as many labels as there actually are displayed on the bar graph without overlapping or becoming unreadable.

I suspect the behaviour of hiding labels aggressively is some default based on the assumption that the labels are somehow in some definite order (like increasing numeric values) where missing data is easier to "guess" by the user, but that doesn't apply to categories at all.

**Comment by JC5** [comment]
This is something the chart library does, and it not configurable unfortunately.

**Comment by saua** [comment]
I even tried to look into it, but my JS isn't strong enough to tell, but I was afraid that the answer would be something like that ...

**Comment by JC5** [comment]
Sorry :(
