### ISSUE TITLE
Negative balance allowed to transfer to piggy bank

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#818]
Negative bank balance allowed to be transferred to piggy bank. See screenshot:

![screen shot 2017-09-08 at 13 33 36](https://user-images.githubusercontent.com/3742238/30210104-639f0ec6-949b-11e7-95ff-b131917a9a70.png)

**Comment by JC5** [comment]
I could change the display to say "zero", but personally I like to see it when my piggy banks are "overfilled". This could also happen when you create and fill some piggy banks and then empty the account without updating the piggy bank.

**Comment by gavu** [comment]
I get your point, and you are right. Also, the logistics behind the empty-account-without-piggy-back-update scenario is a bit overkill, however... the following option should not be available as it does not really make any sense:

“The maximum amount you can add is: €-121.16.“

This happens when trying to add to a piggy-bank from a negative account

**Comment by JC5** [comment]
Ah yes, that is confusing indeed. I'm not sure if it is feasible to calculate that amount beforehand (since each piggy could be linked to a different account this may prove resource-heavy) but the view could certainly be better!
