### ISSUE TITLE
Documentation update for Nordigen/GoCardless

### ISSUE THREAD

**Issue by Violin1208** [firefly-iii/firefly-iii#8180]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Looking to integrate a third party API and was looking at Nordigen. However, it seems that Nordigen is now defunct and replaced by Gocardless.

I *think* that the GoCardless product is compatible for now with FF3 and that the tool has been ported accross. If this is the case, could we have the FF3 Docs updated to show that we show be signing up to GoCardless and not Nordigen?

### Solution

Replace Nordigen references in the docs with GoCardless (assuming this is the one we support in FF3)

### What are alternatives?

Remove Nordigen completely.

**Comment by JC5** [comment]
Feel free to open a PR!
