### ISSUE TITLE
Ignore upper/lower case for suggestions

### ISSUE THREAD

**Issue by nottheend** [firefly-iii/firefly-iii#8187]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

- the displayed suggestions for source and destination accounts are very helpful entering a transaction
- often, I don't remember the exact official spelling of a company (i.e. upper or lowercase)
- => the account is not shown and I create unwillingly a new account for the same company

### Solution

make suggestions for source and destination independent of upper or lowercase in spelling of the account

### What are alternatives?

Keep it as is

### Additional context

It would be mainly helpful for withdrawals and the source account

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/faq/other/#auto-complete-is-case-sensitive
