### ISSUE TITLE
Select which date to use for Nordigen import

### ISSUE THREAD

**Issue by Vargash** [firefly-iii/firefly-iii#8188]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

It would be useful to have a configuration dropdown for the Nordigen importer to select which date to use as the "Transaction Date" between `bookingDate` and `valueDate`

### Solution

Set a dropdown with the possible date fields, and using a default fallback date (not editable) in the case the selected one is unavailable; in this way there should be enough flexibility to manage most of banking institutes transaction date systems.

### What are alternatives?

Alternatively, a rule action able to switch (at transaction creation time) the available dates could do the trick, but I assume that this would be harder to implement than the date choice at configuration time.

**Comment by JC5** [comment]
Sorry, this will not be an option. You can use webhooks if you want to switch dates around, the rules don't support it.
