### ISSUE TITLE
Feature Request: Implement Automatic Summation for Split Amount Inputs

### ISSUE THREAD

**Issue by VPaulV** [firefly-iii/firefly-iii#8193]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to propose a new feature for the handling of numerical inputs, specifically for scenarios where users input amounts in a split format. The idea is to enhance the user experience by allowing the input of amounts in a format like "25+25+10", which the system would then automatically sum up to derive the final value (in this example, 60).

### Solution

- The input field should accept a string of numbers separated by the '+/-/*/%' sign.
- Upon submission, the system should parse this string and calculate the sum of the individual numbers.
- The final calculated value should then be used as the input value for the system's processing.

### Additional context

I believe this feature would greatly improve the usability of the system for scenarios involving multiple, smaller amount inputs that need to be summed up. Thank you for considering it!

**Comment by JC5** [comment]
Sorry, no. 

https://github.com/firefly-iii/firefly-iii/issues/535
