### ISSUE TITLE
Display issue with the next expected date of yearly bills

### ISSUE THREAD

**Issue by DireMunchkin** [firefly-iii/firefly-iii#8195]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

There's a display issue with yearly bills, that are not due in the month. Their Next expected match will be today's date, instead of when it's actually expected. It's then hard to see when a yearly bill is expected to come due.

### Debug information

Debug information generated at 2023-11-25 16:36:39 for Firefly III version **v6.0.30**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.30 / v2.0.11 / 21 (exp. 21)</td></tr><tr><td>PHP version</td><td>8.2.12 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>751, base <span>#</span>40</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Zurich + UTC</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-11-25 00:00:00 (16 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-11-01 16:32:26</td></tr><tr><td>Session end</td><td>2023-11-30 16:32:26</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; rv:120.0) Gecko/20100101 Firefox/120.0</td></tr></tbody></table>

### Expected behaviour

I'd like it to display the actual next expected match date, even if it falls outside of this month.

### Steps to reproduce

1. Make a yearly bill that is next expected not in this calendar month.
2. Go to Bills page, select date range today.
3. This bill is displayed as "Paid this period: Not expected this period" "Next expected match: <today's date>"
4. Select a date range when the bill is due in.
5. The next expected match is correctly displayed.

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
Should be fixed in the next release :+1:

**Comment by DireMunchkin** [comment]
Thanks!

**Comment by sequent5** [comment]
Today I upgrade FireflyIII to latest version(docker version),all bill next expected match display current date(27/11/2023) regardless of whether the billing cycle is yearly or monthly.

**Comment by JC5** [comment]
Great stuff, thanks. Is the issue also fixed when you upgrade to "develop"?

**Comment by sequent5** [comment]
Not '"develop", just latest stable,I will try "develop" tomorrow

2023年11月27日 20:53:54 James Cole ***@***.***>:

**Comment by JC5** [comment]
Could you give me some more details on the blank bills? Start of date, period, skip value, etc.

**Comment by DireMunchkin** [comment]
I switched to `develop` and the original issue I reported looks solved.

**Comment by sequent5** [comment]
a bill screenshot contain period and skip value,  Start day of first row bill is 15/11/2023, the third row is 2/2/2023. Hope it's helpful.Thanks for your excellent work.

2023年11月27日 22:52:38 James Cole ***@***.***>:
