### ISSUE TITLE
Increase bill skip from 31 to a higher number

### ISSUE THREAD

**Issue by SlimG** [firefly-iii/firefly-iii#8208]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

My passport expire every 5 years, so I'd like to renew it two months ahead of expiry.

I tried to create a monthly recurring bill which skips 58, but the errormessage says the maximum skip value limit is 31

### Solution

Increase the maximum bill skip value limit from 31 to a higher number than 58

### What are alternatives?

I am not familiar with any alternatives

**Comment by JC5** [comment]
Why not every five years but scheduled two months before it expires?

**Comment by SlimG** [comment]
Are you suggesting I keep a schedule in an app outside of Firefly to work around this, or are you referring to a feature for recurring bills "5 years - 2 months" withing Firefly that I'm not aware of?

**Comment by JC5** [comment]
> Are you suggesting I keep a schedule in an app outside of Firefly to work around this,

Yes, actually. But if you insist on using Firefly III, what's wrong with a 5 year schedule that runs 2 months before the end of your passport's end date?

**Comment by SlimG** [comment]
Here is an example of what I think your suggestion is on how to solve it in Firefly III, and the problem I see:

1. 2023.06.01 Start of yearly recurring bill with 4 skips
2. 2023.08.01 First passport purchased
3. 2028.06.01 Bill recurring and second passport purchased 
4. 2028.08.01 First passport expire
5. 2033.06.01 Second passport expire at the same time as bill recurring. This is my challenge

When ordering a new passport, I pay for it immediately, but have to wait for a varying amount of weeks before I get the new one. This is why I renew the passport two months ahead.

Using monthly recurring bills with 57 skips (Not 58 as I said earlier) would solve this challenge for me.

**Comment by JC5** [comment]
I'm afraid the limit will remain 31.
