### ISSUE TITLE
Add custom delimiter to import and encoding to import config file

### ISSUE THREAD

**Issue by enboig** [firefly-iii/firefly-iii#8212]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

My bank uses "|" as a delimeter, and encode files with "ISO 8859-15".

### Solution

The form could accept "custom delimeter" and "file encoding" to make proper conversions before importing.

### What are alternatives?

Right now I have to open the .txt file to _search&replace_ and _save-as_ every time.

### Additional context

This could be added in an advanced section, if you think it could "intimidate" most users, or they could even be only configurable editing json import configuration file.

**Comment by JC5** [comment]
No, sorry. There will be no custom delimiter support. 

The data importer can convert files to UTF8, does that not work for you?

**Comment by enboig** [comment]
As I will have to search&replace, I will make a script to do both things before uploading the file.
Thanks
