### ISSUE TITLE
能否搞一个APP呢？这样记帐更方便

### ISSUE THREAD

**Issue by oemsys** [firefly-iii/firefly-iii#8215]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

能否搞一个APP呢？这样记帐更方便

### Solution

能否搞一个APP呢？这样记帐更方便

**Comment by JC5** [comment]
Please don't open a new issue in English.
