### ISSUE TITLE
Search page: link help page

### ISSUE THREAD

**Issue by nottheend** [firefly-iii/firefly-iii#8221]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

- I would like to use the search as a noop.
- if firefly-iii would have linked the help[ page with the operators explained](https://docs.firefly-iii.org/firefly-iii/features/search/), I would have been able to find the transaction
- however, I overlooked the hint to the operators and didn't find my transaction

### Solution

- link the [help page for the search](https://docs.firefly-iii.org/firefly-iii/features/search/)
- possibly highlight the link

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/6312 :)
