### ISSUE TITLE
Dockerfile uses hardcoded version

### ISSUE THREAD

**Issue by DieBauer** [firefly-iii/firefly-iii#823]
The Dockerfile uses the commando `composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.6.4` to 'install' firefly in the container. 

This uses the distributed firefly-iii composer project version 4.6.4 which is hardcoded in the docker file (https://packagist.org/packages/grumpydictator/firefly-iii).

This behaviour was recently changed in https://github.com/firefly-iii/firefly-iii/commit/88d3db4dc8583abf56f3c86f37d64383381f37eb#diff-3254677a7917c6c01f55212f86c57fbfL38

**Comment by JC5** [comment]
I've merged your PR, thanks!
