### ISSUE TITLE
Icon for PWA

### ISSUE THREAD

**Issue by lokesh-krishna** [firefly-iii/firefly-iii#8233]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Presently, installing the app using Chrome on Android results in an icon that seems to use the favicon on top of a white background.

### Solution

A dedicated PWA version of the icon so that the icon isn't overlaid on a white background.

### Additional context

![Screenshot_20231205-121037~2](https://github.com/firefly-iii/firefly-iii/assets/20235646/8559f23a-feec-4e70-bdfd-6beccc7478c0)

Vikunja here is also a PWA but has a proper icon while Firefly's icon is overlaid on a white background to create the icon.

**Comment by JC5** [comment]
I see what you mean. I'll pick it up!
