### ISSUE TITLE
Feature Request: Usability Dashboard customization

### ISSUE THREAD

**Issue by pogora** [firefly-iii/firefly-iii#8234]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Customize the look of the Dashboard. Hiding/collapsing, reordering items and charts.
This would make it much easier to use especially on smart phones.

### Solution

First off great work on the app. Although I tried it a few months ago and instantly deleted it cause I was overwhelmed by the UI, I am now back and using it daily. It's a very powerful tool (once you spent a day or two figuring out how it works)
Add the ability to modify what is displayed on the Dashboard.

One or some of these would be really nice to have and make it much easier to use on mobiles.

- A little button to show/hide the graphs. 
- Option to select which items are shown
- Or an option to switch for a Mobile view that auto hides all the graphs
- The ability to re-order the items on the Dashboard

**Comment by JC5** [comment]
Thanks for the compliments!

Unfortunately, this will not be an option. Too much work and maintenance burden.

**Comment by pogora** [comment]
Oh that's too bad. I figured it would be a bit of work, so I had no illusions about this coming any time soon. 
Thank you for considering/responding though.
