### ISSUE TITLE
Improve logging output from docker "fireflyiii/data-importer:latest"

### ISSUE THREAD

**Issue by cruzzoe** [firefly-iii/firefly-iii#8237]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I use this on a daily basis to import feeds to my ff3 instance.
I'd like to able to notify myself should transactions be imported.
This is easy to do if I can clearly see from the docker logs if anything has been imported.
At present, there are quite a lot of debug lines, and also some unclear lines which I have no idea what they mean.

For example, even when there are no imports it refers to items in the array. Are you able to help me either a) understand the existing logging lines or b) change the logging to make it a bit more intuitivate?

Would really appreciate this feature!

### Solution

See above

### What are alternatives?

NA

### Additional context

NA

**Comment by JC5** [comment]
The use case for debug logging is pretty narrow, ie. for my debug purposes. What would you like to know?

**Comment by cruzzoe** [comment]
So would like to be able to see how many transactions were imported after duplicates were ignored. I think number of transactions is logged but these might all be ignored if they are existing in ff3 already.

Id like to see; "number of new transactions imported to ff3"

**Comment by JC5** [comment]
You can use the notification settings for that, right?

**Comment by cruzzoe** [comment]
Thank you. Sounds great!

**Comment by JC5** [comment]
This is now fixed.
