### ISSUE TITLE
Podman support (port clash)

### ISSUE THREAD

**Issue by bertmelis** [firefly-iii/firefly-iii#8238]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'd like to set up Firefly 3 using Podman instead of Docker. Both containers would be in a pod where they share the same network namespace. Because of this, they cannot bind to the same port. So this setup is not possible now.

### Solution

It would help a lot if (for example) the importer container would be able to listen on (again, for example) 8081. A env variable would be handy here so we won't be breaking existing systems.

### What are alternatives?

alternatively, I can run both containers separately, not in a pod. Technically perfectly valid, but I would like to keep things together that belong together.

### Additional context

https://podman.io/

**Comment by bertmelis** [comment]
My github-google skills let me down. Apparently there was already a request with a blunt "not going to happen" here: https://github.com/firefly-iii/firefly-iii/issues/8222

😢

**Comment by JC5** [comment]
Unless the containers also share IPs there's no reason why they can't both use 8080.

**Comment by bertmelis** [comment]
Podman isn't a reverse proxy, it is a container engine just like Docker but under the hood it works differently. I don't want to explain all the differences between Podman and Docker (I myself am not an expert by far). The main point is that containers in a pod (= group of containers) share the same namespace, **network** and security context. So when the firefly3-core container binds to port 8080, the importer container cannot.

So if you launch firefly with `podman-compose`, it creates a pod, adds all the containers to that pod and runs them. First come, first serve so the importer tool fails because port 8080 is already taken by the core container.

I can perfectly run firefly3 and the importer using Podman. Just not in a pod. This makes networking cumbersome. And all it would need to enable this is a configurable (or different, but that would be a breaking change) port. Maybe my mind just isn't aligned with the firefly3 architecture.

PS Is firefly on kubernetes tested with core, database and importer in a single unit?

**Comment by bertmelis** [comment]
As long as you just run different containers, nothing matters. They all behave like separate machines. You obviously cannot publish two containers to the same port on the host. That's why you publish core to 8080 and importer to 81.

Containers grouped together in a pod (which happens also on Kubernetes!) all get the same IP. so now they not only cannot publish ports to the same port on the host, but also cannot expose on the same port inside the pod.

In fact, Firefly3 will not work on kubernetes when the importer tool is added.

I might pursue another solution: I can mount a volume to the importer container with a custom apache config. That way I can specify whatever port I want, right?

**Comment by JC5** [comment]
> In fact, Firefly3 will not work on kubernetes when the importer tool is added.

I'm not entirely sure how, but I believe the current Kubernetes stack includes the importer. Perhaps these are different pods?

- https://github.com/firefly-iii/kubernetes/blob/main/charts/firefly-iii-stack/Chart.yaml

> I can mount a volume to the importer container with a custom apache config. That way I can specify whatever port I want, right?

Yes you can. See [here](https://dev.azure.com/Firefly-iii/_git/ImportToolImage?path=/Dockerfile) and [here](https://dev.azure.com/Firefly-iii/_git/BaseImage?path=/apache-8.2/Dockerfile) (line 303 + 310).
