### ISSUE TITLE
Error in the doc

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#8247]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The paths in the doc are wrong in https://docs.firefly-iii.org/firefly-iii/faq/self-hosted/
Section `I want to use SQLite?`

Precisely the following section:
> In order to install the database, the file /storage/database/database.sqlite must exist. When it does not exist, you can use  this command on Linux to create it:
>
> touch ./storage/database/database.sqlite

Should read:
> In order to install the database, the file /var/www/html/storage/database/database.sqlite must exist. When it does not exist, you can use  this command on Linux to create it:
>
> touch /var/www/html/storage/database/database.sqlite

### Debug information

n/a

**Comment by JC5** [comment]
Nice find, that's an old page. I'll make sure it gets deleted.

**Comment by chevdor** [comment]
The page is actually useful and if you fix the paths, it works well.
I can make the PR if you want but I am not familiar with how/where/how the doc of the project is managed.

I would suggest to keep the Sqlite doc as it is very useful. 
More on that later but I am actually seeing a MUCH better perf using Sqlite than Postgres, even with redis enabled.
I am now testing a migration from postgres to sqlite.

**Comment by JC5** [comment]
No need to panic, just another URL:

https://docs.firefly-iii.org/references/faq/install/#i-want-to-use-sqlite

Let me know if other links are broken.

**Comment by chevdor** [comment]
Ok, the link you mention seem to be the same content so with the fix abobe, it will work.
I did not run into any issue following the doc once the paths were adjusted so `/var/www/html/storage/database/`

**Comment by JC5** [comment]
Nice, that solves it.
