### ISSUE TITLE
README links are broken

### ISSUE THREAD

**Issue by wcampbell0x2a** [firefly-iii/firefly-iii#8252]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The following links on the readme go to a 404 page: 2. You can [install it on your server](https://docs.firefly-iii.org/firefly-iii/installation/self-hosted/).(https://github.com/firefly-iii/firefly-iii/blob/0b22b056bcd944c8a05f0e51e8375a0667f036a3/readme.md?plain=1#L131)

### Debug information

N/A

**Comment by JC5** [comment]
Thanks for letting me know. I'll pick it up.

**Comment by d-volution** [comment]
"You can [run it using Docker](https://docs.firefly-iii.org/firefly-iii/installation/docker/)." in the README doesn't work either
I think the new page is https://docs.firefly-iii.org/how-to/firefly-iii/installation/docker/

**Comment by JC5** [comment]
In the mean time, all links are fixed. I'll release the new version asap so people stop erroring out.
