### ISSUE TITLE
Link's decriptions are hardcoded

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#826]
I've updated from version 4.6.4 to 4.6.5 and added two link types in transaction links configuration.

I named them (in Polish equivalents):
- link with id=1 as "returns/is returned by"
- link with id=2 as "relates to"

Everything is OK on page /admin/links/show/$ID - I see "$source_transaction_decription $my_link_description_in_polish $destination_transaction_description".

The problem is in transaction's details on /transactions/show/$ID.
For transactions linked with link_id=1 I see:
> This withwdrawal **relates to** ...
> This deposit **relates to** ...

For transactions linked with link_id=2 I see:
> This withwdrawal **(partially) refunds** ...
> This deposit **is (partially) refunded by** ...

That corresponds to link descriptions from demo site, so I guess that i should have 4 predefined links (maybe I would if I performed clean install) and they should be translated using Crowdin.

**Comment by JC5** [comment]
Damn, I forgot that a migration doesn't seed new data. I'll build a routine for the next release. Yes, they're hard-coded.

**Comment by pkoziol** [comment]
BTW, I tried to manually create links from LinkTypeSeeder.php, but got form validation error saying that "The inward and outward must be different" when I've tried to create "Related" link.

**Comment by JC5** [comment]
Yeah the seed routine does not go past the validator. I'll set something up.

**Comment by pkoziol** [comment]
What if somebody already created custom link types that have ID in range 1-4?
Looks like code from 0bcc010de86042251bb967dd8283736ba8ca4d0c will insert links with auto_incremeted IDs, so they not necessarily will get ID=1,2,3,4 and translations still won't work.

**Comment by JC5** [comment]
Basically, them I'm screwed. Given the way I introduced this I have no choice but to pick another system for the translations and let go of the hard-coded ID's. This was a bad idea anyway (hard-coded ID's are always a bad idea) but I hoped I could get away with it ;).

**Comment by pkoziol** [comment]
Couldn't you update ID of custom existing link types to ID = ID + 4?

**Comment by JC5** [comment]
I've recreated the translations in more flexible way that will fix this problem. In the future, FF will check if the link things exist already in the format FF expects and if so, it will reuse those.

Since the system depends on them they will not be editable but the ID's are no longer hard-coded.
