### ISSUE TITLE
Excel-like data table on mass edit page

### ISSUE THREAD

**Issue by kopach** [firefly-iii/firefly-iii#8260]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like Firefly to have more excel-like table on mass edit page instead of just form. So, it's possible to navigate between inputs/cells with keyboard (e.g. cell down with arrow down) and do auto-population of similar data automatically

Compare those behaviors (with auto populate)

![2023-12-15 22 51 10](https://github.com/firefly-iii/firefly-iii/assets/8749624/533c60a3-a4c9-4203-b4f0-0c1e5bced173)

![2023-12-15 22 49 43](https://github.com/firefly-iii/firefly-iii/assets/8749624/4c6557c3-7ed1-4feb-958a-bb5ad2ef8410)

Same is true for navigation

![2023-12-15 22 57 32](https://github.com/firefly-iii/firefly-iii/assets/8749624/a94b047a-377b-4bf3-aeda-5b1540fd3433)

![2023-12-15 22 57 55](https://github.com/firefly-iii/firefly-iii/assets/8749624/1109bf5e-9c65-42bc-a70e-c9b2d5ec08f3)

### Solution

Use table libraries like ag-grid to represent mass edit data
See main example here https://www.ag-grid.com/example/

![2023-12-15 23 04 04](https://github.com/firefly-iii/firefly-iii/assets/8749624/c64719b3-59ca-4bd0-bc0b-cecafe8079f2)

**Comment by JC5** [comment]
Something to be considered for https://github.com/firefly-iii/firefly-iii/issues/6304
