### ISSUE TITLE
Tables checkbox multi-select

### ISSUE THREAD

**Issue by kopach** [firefly-iii/firefly-iii#8261]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Would be great to have multiselect functionality in Firefly III tables for faster edit

![2023-12-15 23 24 13](https://github.com/firefly-iii/firefly-iii/assets/8749624/d4ee1ccf-f025-4ad7-8eaa-5b3473101625)

### Solution

Add JS script to extend current functionality of tables

Here is working script (I'm using it via Tampermonkey)

```js
// ==UserScript==
// @name         Multi-Select Checkboxes in Firefly III tables
// @description  Hold shift and click to select multiple checkboxes in Firefly III tables
// @version      1
// @author       https://github.com/kopach
// @match        https://demo.firefly-iii.org/transactions/withdrawal
// @icon         https://www.firefly-iii.org/assets/favicon/favicon-32x32.png
// @grant        none
// ==/UserScript==

(function () {
  let lastChecked = null;

  document.addEventListener('click', function (event) {
    if (event.target.type === 'checkbox' && event.shiftKey) {
      let checkboxes = Array.from(
        document.querySelectorAll('input[type="checkbox"]')
      );
      let start = Math.min(
        checkboxes.indexOf(lastChecked),
        checkboxes.indexOf(event.target)
      );
      let end = Math.max(
        checkboxes.indexOf(lastChecked),
        checkboxes.indexOf(event.target)
      );

      checkboxes.slice(start, end + 1).forEach(function (checkbox) {
        checkbox.checked = event.target.checked;
      });
    }

    if (event.target.type === 'checkbox') {
      lastChecked = event.target;
    }
  });
})();

```

### What are alternatives?

Using libraries like Ag-Grid for tabled data

**Comment by JC5** [comment]
Something for this epic: https://github.com/firefly-iii/firefly-iii/issues/6304
