### ISSUE TITLE
Run rule after updating

### ISSUE THREAD

**Issue by tmeekes** [firefly-iii/firefly-iii#8264]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

It would be a great tweak if there was some sort of selection option to run a rule immediately after updating it.

### Solution

Possibly as an additional checkbox in the "options" section at the bottom, below the "return here" option.

### What are alternatives?

You can run a rule from the "Rules" page, but that's usually an added click after updating the rule - it doubles the time taken to go through a series of rules and run them after updating them.

### Additional context

![image](https://github.com/firefly-iii/firefly-iii/assets/19932540/b7dd1a65-233b-4667-946e-673cd00fdea8)

**Comment by JC5** [comment]
I'll consider this for https://github.com/firefly-iii/firefly-iii/issues/6308
