### ISSUE TITLE
Stop Processing on rule triggers no longer prevents the actions from being applied

### ISSUE THREAD

**Issue by CtrlZvi** [firefly-iii/firefly-iii#8271]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The stop processing checkbox on rule triggers does not prevent rule actions from being run.

### Debug information

Debug information generated at 2023-12-19 05:18:05 for Firefly III version **v6.1.0**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.0 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.0 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>852, base <span>#</span>67</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + America/Los_Angeles</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>debug, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-12-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-12-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0</td></tr></tbody></table>

### Expected behaviour

If a rule trigger with stop processing checked passes (and it is not the last rule trigger), the actions will not be run as per [the documentation](https://docs.firefly-iii.org/how-to/firefly-iii/features/rules/#stop-processing).

### Steps to reproduce

1. Create a new asset account, call it Test 1
2. Create a new asset account, call it Test 2
3. Create a new withdrawal that transfers 1 from Test 1 to the (cash) account, give it Test 1 as a description
4. Create a new withdrawal that transfers 1 from Test 2 to the (cash) account, give it Test 2 as a description
5. Create a new rule
    1. Uncheck strict mode
    2. Add the "Source account ID is exactly.." trigger with the id of Test 2 and check "stop processing other triggers"
    3. Add the "Description starts with.." trigger with a value of "Test"
    4. Add the "Add tag .." action with a value of "Test"
6. Run the rule manually over the Test 1 and Test 2 accounts
7. Notice that both of the transactions (created in steps 3 and 4) have the Test tag indicating that despite being told to stop processing triggers for Test 2 before all triggers were hit, actions were still applied.

### Additional info

If I'm reading the code correctly, it looks like this functionality [used to work](https://github.com/firefly-iii/firefly-iii/blob/91234545454be399625c78916310954d54457087/app/TransactionRules/Processor.php#L335) but was broken with [the migration to the new rules engine](91234545454be399625c78916310954d54457087)

**Comment by JC5** [comment]
Nice find, I'll check it out!

**Comment by JC5** [comment]
You indicate you set "Uncheck strict mode". In those cases, every trigger is checked individually. So, even when you set "stop processing other triggers", all triggers will be checked. 

This is a little confusing, so I will update the documentation. Non-strict rule can trigger on any trigger so it is pointless to stop processing other triggers.
