### ISSUE TITLE
Expected bill next month but shown as not expected

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#8277]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

![image](https://github.com/firefly-iii/firefly-iii/assets/1318140/266c85df-1520-423e-9f5f-e71f29cf5dbd)
When a bill is expected on the first day of the month it is shown as not expected for the selected month.

### Debug information

Issue shown on the demo website

### Steps to reproduce

go to https://demo.firefly-iii.org/bills
change period to January

**Comment by jlauwers** [comment]
I just tried the last docker develop. It's the same. (since I saw another fixed issue about bills)
The month sum is also missing this amount.

**Comment by JC5** [comment]
Thanks, found and fixed!
