### ISSUE TITLE
Net worth is empty in the dashboard due to division by zero

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#8278]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

![image](https://github.com/firefly-iii/firefly-iii/assets/226712/1f8d885f-a4b0-4fdd-824c-263c8ea77342)

I upgraded to 6.1.0 (IIRC from 6.0.30) a few days ago. According to the error emails, a couple of XHR requests are raising `DivisionByZeroError`:

- `/json/box/net-worth`
- `/api/v1/summary/basic?end=2023-12-31&start=2023-12-01`

 In both cases, it's the same code:

> Firefly III v6.1.0 ran into an error: Division by zero.
> The error was of type "DivisionByZeroError".
> This error occurred in file "/var/www/html/app/Support/Http/Api/ExchangeRateConverter.php" on line 88 with code 0.

And similar stack traces:

```
#0 /var/www/html/app/Support/Http/Api/ExchangeRateConverter.php(88): bcdiv()
#1 /var/www/html/app/Support/Http/Api/ExchangeRateConverter.php(66): FireflyIII\Support\Http\Api\ExchangeRateConverter->getRate()
#2 /var/www/html/app/Support/Steam.php(458): FireflyIII\Support\Http\Api\ExchangeRateConverter->getCurrencyRate()
#3 /var/www/html/app/Support/Steam.php(546): FireflyIII\Support\Steam->balanceConverted()
#4 /var/www/html/app/Helpers/Report/NetWorth.php(100): FireflyIII\Support\Steam->balancesByAccountsConverted()
...
```

The full traces are not the same, but that is apparently due to the request handling. I attached them in any case.

[stack_trace_net-worth.txt](https://github.com/firefly-iii/firefly-iii/files/13733618/stack_trace_net-worth.txt)
[stack_trace_summary_basic.txt](https://github.com/firefly-iii/firefly-iii/files/13733619/stack_trace_summary_basic.txt)

### Debug information

Debug information generated at 2023-12-21 02:52:03 for Firefly III version **v6.1.0**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.0 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.0 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>852, base <span>#</span>67</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Istanbul + Europe/Istanbul</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>172.17.0.1</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span></td></tr><tr><td>Session start</td><td>2023-12-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-12-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</td></tr></tbody></table>

**Comment by JC5** [comment]
Wow, that's... interesting. I wonder where the zero came from. Thanks!
