### ISSUE TITLE
amount for a expense doesn't take care about coma

### ISSUE THREAD

**Issue by ndecaris** [firefly-iii/firefly-iii#828]
hello firefly community,

i have a strange stuff. when i put a expense with a amount including decimal i put a coma to separate unit and decimal, i can save the expense (so coma character is good), but when i see the account, the expense lost is coma. number of decimal for the currency is ok.
any idea ?

thank in advance

**Comment by JC5** [comment]
You're probably missing the correct locales for your selected language. The [FAQ](https://firefly-iii.github.io/faq-technical.html) has a solution.
