### ISSUE TITLE
Cryptocurrency decimals view

### ISSUE THREAD

**Issue by Greg-Bush** [firefly-iii/firefly-iii#8280]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hello!

I have some asset accounts with traditional currencies (first 2 lines on the screenshot below) along with cryptocurrencies (last 2 lines on the screenshot).

![Screenshot 2023-12-21 at 14 06 53](https://github.com/firefly-iii/firefly-iii/assets/44202486/7c65d771-9348-460b-8abc-387663f648ef)

And it looks like cryptocurrencies  stand out with extra zeroes at the end.

So I'm wondering is there better view for decimals places greater then 2. For example with a reduction in zeros at the end for them, either aligning numbers in a way as a decimal part would grow to the right, and an integer part would grow to the left.

### Solution

A better view for currencies in account list regarding cryptocurrencies peculiarities.

**Comment by JC5** [comment]
Sorry, this is a disadvantage for crypto currencies I'm not going to fix.

**Comment by Greg-Bush** [comment]
Would you accept a PR if I implement this small feature?

**Comment by JC5** [comment]
No, sorry about that. This is not about me fixing it as opposed to anyone else, this is about this not getting a fix. 

1. It's not a monetary standard to reduce visible decimals for these kinds of number, so I'd rather not customize this.
2. It gives me a relatively large maintenance burden for a very small problem.
3. I'm working on a new layout where these kinds of problems can be solved better.

**Comment by Greg-Bush** [comment]
I was thinking about small temporary js function located in only one place.
But if new layout is already in develop process I look forward release with interest.
Thank you!
