### ISSUE TITLE
Database CPU utilization after v6.1.0 upgrade

### ISSUE THREAD

**Issue by gpampuro** [firefly-iii/firefly-iii#8281]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After upgraded the docker to the version 6.1.0 I started to have performance issues and the application is very slow.

### Debug information

Checking the server utilization I found that the mariadb service has more than 180% CPU utilization. If I restart the service everything is OK, until I do the first login to Firefly app.

Checking MariaDB logs I found that there are a lot of queries trying to get information from the currency_exchange_rates table. As I have information since 2009 and the currency_exchange_rates table storing the exchange rates, the queries never ends so it is impossible to continue using the application because the database is processing the queries. I know that the exchange rate is not implemented yet, but something changed and now it is impacting my performance.

Probably it is impacting me as I have almost 150 currencies (110 enabled), 150 assets accounts (47 actives), more than 42.000 transactions and the currencies exchange rates table completed (141.000 entries) with the exchanges per currency per day (some of them are stocks or prices that I was tracking).

For your reference, this is one example of the mysql logs and this is repeating many many times.
186 Prepare  select * from `currency_exchange_rates` where `currency_exchange_rates`.`user_id` = ? and `currency_exchange_rates`.`user_id` is not null and `from_currency_id` = ? and `to_currency_id` = ? and `date` <= ? and `currency_exchange_rates`.`deleted_at` is null order by `date` desc limit 1
                   186 Execute  select * from `currency_exchange_rates` where `currency_exchange_rates`.`user_id` = 1 and `currency_exchange_rates`.`user_id` is not null and `from_currency_id` = 25 and `to_currency_id` = 8 and `date` <= '2021-04-05' and `currency_exchange_rates`.`deleted_at` is null order by `date` desc limit 1
                   184 Execute  select * from `currency_exchange_rates` where `currency_exchange_rates`.`user_id` = 1 and `currency_exchange_rates`.`user_id` is not null and `from_currency_id` = 25 and `to_currency_id` = 8 and `date` <= '2021-04-05' and `currency_exchange_rates`.`deleted_at` is null order by `date` desc limit 1

Please let me know if there is anything I can do on my end to try to understand or solve the issue.

Thanks!

**Comment by JC5** [comment]
Hahaha holy shit. I'll see what I can do but this is ridiculous.

**Comment by JC5** [comment]
Alright this is still insane but a fun challenge. The exchange rate converter has seen some improvements in the `:develop` branch, and it should report about it like so:

```
[2023-12-22 06:03:34] local.INFO: ExchangeRateConverter ran 3 queries.  
```

Could you upgrade to the `:develop` tag and keep an eye out for these entries? I wonder what your record will be.

The docker image will be ready about 25m from now.

**Comment by gpampuro** [comment]
Thanks!! with the :develop tag is working perfect, no more high CPU consumption and MySql is not running all the queries as before. I fully support the currency exchange so please let me know if I can help you with some tests.
Thanks for your fast support and quick fix!
