### ISSUE TITLE
Update transaction via API do not update the "updated_at" parameter

### ISSUE THREAD

**Issue by Timmy93** [firefly-iii/firefly-iii#8282]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi, I just discovered this platform few days ago. Congratulations it looks really good and stable, thank you very much for your work!

I'm testing the platform on docker and I'm creating a (new) component that keeps in sync Splitwise and Firefly III (soon on Github).
I'm using the `latest` container of both `firefly_iii `and `data_importer`

Unfortunately, when I update a transaction using the [Update Transaction API](https://api-docs.firefly-iii.org/?urls.primaryName=2.0.10+%28v1%29#/transactions/updateTransaction) the transaction is correctly updated but tehe `updated_at` date remain the same of `created_at`.

Here you can see from the debugger the 2 date that do not change (Note that ID is the same and the amount is changed by 0.01)
Before update:
![image](https://github.com/firefly-iii/firefly-iii/assets/10899430/2006901a-52f5-4601-b3dd-09199b217f6b)
After update:
![image](https://github.com/firefly-iii/firefly-iii/assets/10899430/9d185ba1-eded-4733-a997-b88901305133)

### Debug information

Debug information generated at 2023-12-22 00:34:44 for Firefly III version **v6.1.0**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.0 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.0 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>852, base <span>#</span>67</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Rome + Europe/Rome</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>it_IT + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-12-21 00:00:00 (1 day ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 2</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-11-21 17:47:36</td></tr><tr><td>Session end</td><td>2023-12-21 17:47:36</td></tr><tr><td>View range</td><td>YTD</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0</td></tr></tbody></table>

### Expected behaviour

I expect that when I successfully call the [Update Transaction API](https://api-docs.firefly-iii.org), the parameter: `updated_at` is changed to current time while `created_at` remain unchanged.

### Steps to reproduce

1. Create a transaction
2. Edit that transaction
3. Check that the two date are unchanged

**Comment by JC5** [comment]
Nice find, I'll pick it up!
