### ISSUE TITLE
Button in date field of transactions is missing

### ISSUE THREAD

**Issue by curcas** [firefly-iii/firefly-iii#8287]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The date picker button is missing on the date field on the transactions.
In the dark layout the button is available.

![image](https://github.com/firefly-iii/firefly-iii/assets/7355150/db56db1e-e697-467e-9db3-c1edb61821a9)

### Debug information

Debug information generated at 2023-12-23 15:48:34 for Firefly III version **v6.1.0**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.0 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.0 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>852, base <span>#</span>67</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Zurich + Europe/Zurich</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>debug, stdout / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-12-23 00:00:00 (15 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span></td></tr><tr><td>Session start</td><td>2023-12-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-12-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The date picker should be visible.

### Steps to reproduce

1. Change the layout to light
2. Create a transaction
3. See the missing button

**Comment by JC5** [comment]
It's right there. I can see i fine.

**Comment by curcas** [comment]
For me it looks like this:
![image](https://github.com/firefly-iii/firefly-iii/assets/7355150/e5f777a6-891c-4126-bb10-619420a38d56)

But when I remove the background-color on the .form-control class it looks like this:
![image](https://github.com/firefly-iii/firefly-iii/assets/7355150/ce67acfe-61d0-491a-ba17-4e69a8fa3102)

So somehow the button is "hidden" but it's still clickable even though it's not visible.
I cleared the cache and there is no browser plugin hiding anything.

Any idea what else I could check?

**Comment by JC5** [comment]
Is it also broken on the demo site?

https://demo.firefly-iii.org/transactions/create/withdrawal

**Comment by curcas** [comment]
It's also broken on the demo site with Chrome and Edge (which I never us so no plugins at all).

**Comment by curcas** [comment]
I found out why it's hidden: My Windows is in dark mode.

Firefly is in light mode.
Windows is in dark mode.

When I change Windows to light the button appears but when I switch it back to dark it disappears in Chrome and Edge.

**Comment by JC5** [comment]
Ahh check. Not much I can do about that I'm afraid.

**Comment by curcas** [comment]
I think it could be solved with the color-scheme property in CSS.

I tried it on the date/checkbox/number/upload fields (color-scheme: light) and they all look much better with the light layout.

**Comment by JC5** [comment]
Yes that proves it's already in place, otherwise the font wouldn't respond to it. I see the effect in Chrome only. It also renders some buttons in dark mode, no clue why. This all works fine in Firefox. I'm not going to fix anything.
