### ISSUE TITLE
Handling of debts (incoming/outgoing)

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#829]
Hi, 

this is more of a question than a feature request.

How could I handle debts?

For example, last night, some friends came over, I payed with my credit card, and got cash back:

Outgoing: 60 Euros from asset account (credit card)
Incoming: 40 Euros **cash** (should I create a "**cash** asset account"?)
Remaining: 20 Euros - someone did not have enough cash on him

If I owe someone money, I could create a bill, and have it always remind me I owe money, but how do I handle incoming debts? they are not actually revenue account as there is no balance

Is there some workflow/workaround you have in mind?

Thanks,
Andrei

**Comment by JC5** [comment]
Cash is handled when you do not fill in anything. You can try this when you make a new withdrawal and don't fill in the expense account.

Honestly I have no proper solution yet. There was a lot of magic within FF3 to handle these kinds of things but most of it has been removed again.

Strictly speaking I'm not sure if Firefly III should handle such cases but its an everyday part of finances.

What I suggest is to register each transaction separately. Don't use split transactions. Create the expense (60) and the "deposits" separately (perhaps it was 20/10/10)? This is the most "pure" way of representing what happened. When I have thought of a solution, I will update this issue.

**Comment by gavu** [comment]
Maybe marking transactions with a "followup" flag and a date? 

e.g.: I lent someone 20euros, till next week, I would then create the following transaction:

```
transaction_date => '2017-09-11 18:02:00'
transaction_type => 'expense'
sum => 20
name => 'someone owes me money'
asset_account => 'my checking account'
[...], 
followup_flag => true
followup_date => '2017-09-18 18:02:00'
```
(I did not check the actual db column names, but I hope you get the whole picture)

and as an extra feature, a cron-job that sends you a reminder email that someone owes you money

**Comment by gavu** [comment]
I see you labeled this as a discussion so I'm adding my (temporary) solution here.

1. Create an incoming transaction for the full amount
2. Split transaction into owing parts (persons/groups)
3. Tag settled debt as "Debt incoming (settled)"
4. Tag open debts as "Debt incoming (open)"
5. To keep track, search by transaction category

It works only partly, because you already "receive" the entire debt in this master transaction, you cannot receive only parts of it, can you? maybe mark parts of the transactions as resolved?
