### ISSUE TITLE
When no transaction within date range you get a error

### ISSUE THREAD

**Issue by poudenes** [firefly-iii/firefly-iii#8293]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

On one of my accounts there was nothing happened for couple of days. So the automation stop and don't run the second one.
After I send 0,01 cent to my other account the error is gone. Everything work again.

### Debug information

Only have the error message when I tried it manual:

The conversion could not be started, or failed due to an error. Please check the log files. Sorry about this :(
Error(s)
	•	Line #0: Zero transactions found at GoCardless

### Expected behaviour

Ignore the error and proceed with the other automation task

### Steps to reproduce

1. Leave one account alone for couple of days
2. let the automation do their work
3. When errors appear send 0,01 cent to the account
4. automation is working again.

**Comment by JC5** [comment]
Nice find, this will be fixed in the next release :+1:
