### ISSUE TITLE
(Reopened) Net worth is empty in the dashboard due to division by zero

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#8297]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Sorry for not verifying #8278 earlier. Now I can't reopen it. It persists in v6.1.1, with the same error (`DivisionByZeroError`) & endpoints:

- `/json/box/net-worth`
- `/api/v1/summary/basic?end=2023-12-31&start=2023-12-01`

Similar stack trace:

```
#0 /var/www/html/app/Support/Http/Api/ExchangeRateConverter.php(131): bcdiv()
#1 /var/www/html/app/Support/Http/Api/ExchangeRateConverter.php(66): FireflyIII\Support\Http\Api\ExchangeRateConverter->getRate()
#2 /var/www/html/app/Support/Steam.php(440): FireflyIII\Support\Http\Api\ExchangeRateConverter->prepare()
#3 /var/www/html/app/Support/Steam.php(522): FireflyIII\Support\Steam->balanceConverted()
#4 /var/www/html/app/Helpers/Report/NetWorth.php(96): FireflyIII\Support\Steam->balancesByAccountsConverted()
```

I debugged it using Tinker (which could be nice to include in the default installation). I'm missing some currency rates. I'm unsure how they should be filled in. `artisan cache:clear` didn't help.

I'd also be fine with an option to disable net worth calculation or currency conversion since I don't think I'm using either.

### Debug information

Debug information generated at 2023-12-27 21:01:20 for Firefly III version **v6.1.1**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.1 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>872, base <span>#</span>68</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Istanbul + Europe/Istanbul</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>172.17.0.1</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span></td></tr><tr><td>Session start</td><td>2023-12-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-12-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</td></tr></tbody></table>

**Comment by JC5** [comment]
Nice find. I'll see if I can push a fix to the `:develop` tag.

What's "Tinker"? That's kind of a generic name for a tool.

**Comment by JC5** [comment]
Should be fixed in the latest `:develop`, let me know!

**Comment by halilim** [comment]
> What's "Tinker"? That's kind of a generic name for a tool.

Ah, I meant the Laravel's REPL: https://laravel.com/docs/10.x/artisan#tinker


> Should be fixed in the latest :develop, let me know!

Ok, it's working after https://github.com/firefly-iii/firefly-iii/commit/b32d9aab34fc100682a87a559a71efdf61deb67b, thank you!

**Comment by JC5** [comment]
Nice, thanks for reporting (again)!
