### ISSUE TITLE
Piggy bank account status not clear/incorrect

### ISSUE THREAD

**Issue by rmu1987** [firefly-iii/firefly-iii#8299]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When using piggy banks without a target amount the "account status" table is not clear/incorrect. 
(don't know for sure if this is a bug or a feature so change if needed)

Example three piggy banks on the same Savings account:
**1. House:**
- Saved: 2000
- Target amount: 0
- Left to save: 0 (because there is no target)

**2. Solar Panels:**
- Saved: 5000
- Target: 5000
- Left to save: 0

**3. Other:**
- Saved: 500
- Target: 1000
- Left to save: 500

Account status will be:
**Savings account:**
- Balance: 7500
- Left for piggy banks: 0
- Sum of piggy banks: 6000
- Saved so far: 7500
- Left to save: -1500

### Debug information

-

### Expected behaviour

Using the example above i would expect the "account status" to be like:

**Savings account:**
- Balance: 7500
- Left for piggy banks: 0
- Sum of piggy banks: 8000 (saved amount of the piggy bank without target + the target amount of the 2 piggy banks with a target)
- Saved so far: 7500
- Left to save: 500

Because then it will be in line with the table above (the table "piggy banks") which also states that there is still 500 to be saved.

Or add an additional column like: "Sum of piggy banks without target" displaying how much you saved in the piggy banks without a target.

Then the "account status" will look like:
**Savings account:**
- Balance: 7500
- Left for piggy banks: 0
- Sum of piggy banks (with target): 6000
- Sum of piggy banks without target: 2000
- Saved so far: 7500
- Left to save: 500

**Comment by JC5** [comment]
No. The sum of your piggy banks will not include the total saved amount, if there is no goal for the piggy bank.

**Comment by JC5** [comment]
Left to save refers to the account to which the piggy banks are pointing.

**Comment by JC5** [comment]
Let me link to https://github.com/firefly-iii/firefly-iii/issues/6307, so I can remember to make this more clear in the new layout :)

**Comment by JC5** [comment]
:+1:
