### ISSUE TITLE
Customizable report type for IN+OUT THIS PERIOD button on dashboard.

### ISSUE THREAD

**Issue by pensionars** [firefly-iii/firefly-iii#8300]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like the IN+OUT THIS PERIOD button in the dashboard to lead to a custom budget report.

### Solution

IN + OUT THIS PERIOD would link to the budget report that is generated under BUDGET REPORTS with INCLUDED ACCOUNTS. 

### What are alternatives?

Alternative would be for liabilities not included in net worth to not shown in the report that you access by clicking IN+OUT on the dashboard.

### Additional context

I have a main sum and interest liabilities in separate accounts that I would like to exclude from my budget report. If I include them in my budget report the IN OUT balance is wrong because my interest payment is withdrawn from my main account and simultaniosly a negative balance in my interest liability.

**Comment by JC5** [comment]
For now, you'll have to make a bookmark to this report, but it's something to add to the new layout.
