### ISSUE TITLE
Tag page includes untagged split tx parts

### ISSUE THREAD

**Issue by likuilin** [firefly-iii/firefly-iii#8311]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If a transaction is split and one part of the split has "Tag A" and the other has "Tag B", both parts appear under the page for Tag A, and the sum incorrectly includes both of them.

### Debug information

N/A (reproducible on demo)

### Expected behaviour

The tag page (/tags/show/###/all) should only display and sum the parts of a split transaction that are tagged with that tag, not un-tagged parts of the split.

### Steps to reproduce

1. Start on demo.firefly-iii.org
2. Create a split expense transaction. Tag one part of the split "Tag A" and the other part "Tag B"
3. View the tag page for "Tag A"
4. See both halves of the split transaction and a sum that includes both values

### Additional info

This issue did not present on 6.0.30, but does on 6.1.1.

This does not happen if the second part is not tagged "Tag B", probably because of the number-of-tags check in the filter.

**Comment by likuilin** [comment]
#8304 touches on the same parts, I'm not sure if this issue is fixed by that but it might be.

**Comment by JC5** [comment]
Nice find, I'll check it out!
