### ISSUE TITLE
Automatically uncheck `Include in net worth` when creating revenue/expense accounts

### ISSUE THREAD

**Issue by DenuxPlays** [firefly-iii/firefly-iii#8321]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When you create a revenue or expense account the field `Include in net worth` is enabled by default.
I guess that most people do not want to include the balance from these accounts into their net worth.
Also this is kind of confusing when you do not spot it on creation.

![image](https://github.com/firefly-iii/firefly-iii/assets/83671398/2c71d17c-9863-4bfe-98f5-e39db0580ca1)

### Debug information

As this is not a bug more a UX thing there is no debug information to include.

### Expected behaviour

Checkbox should only be set to true by default if you create a Asset account (or maybe a liabilities account)

### Steps to reproduce

1. create a new revenue/expense account
2. take a look at `optional fields` and see that `Include in net worth` is checked by default

**Comment by JC5** [comment]
Nice find!

Those accounts are not included anyway, but I agree this field can be confusing. I'll make sure it's hidden in the future.

**Comment by DenuxPlays** [comment]
> Nice find!
> 
> Those accounts are not included anyway, but I agree this field can be confusing. I'll make sure it's hidden in the future.

If those accounts aren't included then the checkbox should be removed.

**Comment by JC5** [comment]
> I'll make sure it's hidden in the future.

**Comment by DenuxPlays** [comment]
> > I'll make sure it's hidden in the future.

Sorry my bad...
