### ISSUE TITLE
Transform Next Button In Hint Popup To Done button

### ISSUE THREAD

**Issue by maureenferreira** [firefly-iii/firefly-iii#8330]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When you navigate to a page for the first time in Firefly, a popup with a brief explanation of what each part of the page is for and how to use it ('hints'), and the only ways to dismiss these hints are to:
- Press the "Skip" button (which appears on all slides of the hint other than the last).
- Press the "Done" button (which only appears on the last slide of the hint).
- Click anywhere outside the popup. 

My proposal is this:
- Get rid of the dedicated "Done" button which appears on the last slide of the hints.
- Get rid of the dedicated "Skip" button which appears on all slides of the hints other than the last.
- Add an easily-clickable and easily-noticeable **`X`** button in the upper right-hand corner of the popup which functions to dismiss the popup.
- Make it so the "Next" button in the popup is, instead, a "Done" button only on the last slide of the popup, so that the user has a more natural way to dismiss the popup once they've finished reading it.

This would make it so the user can dismiss the hint popup by:
- Clicking anywhere outside the popup.
- Clicking the "Done" button on the last slide of the popup.
- Clicking the **`X`** button in the top right-hand corner of the popup.

### Solution

A less clunky feeling hint popup dismissal system.

### What are alternatives?

None that I'm aware of.

### Additional context
Some example images:
![image](https://github.com/firefly-iii/firefly-iii/assets/142938968/0efd2cce-b704-4809-9901-cc48e1108059)
![image](https://github.com/firefly-iii/firefly-iii/assets/142938968/d540325f-12aa-438a-85c9-f1e8c61756ab)

**Comment by JC5** [comment]
Great idea! I'll remember this for the new layout. I'm going to refer to #6312 and close this.
