### ISSUE TITLE
Add "Left for piggy banks" of assets account in the main overview

### ISSUE THREAD

**Issue by cabe1214** [firefly-iii/firefly-iii#8336]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I have 3 Bank accounts supervised with Firefly, and also a couple of piggy banks linked to each of them. 
I found myself often looking in the piggy banks section to see how much of the X€ are really available for expenses. 

It would be an improvement to have the option to show in the diagram of the overview page (with dashed line with the same colour of each account) the amount of money each account has "left" after deducting the reserved money of all piggy banks linked to that account. It is the same value as it is shown in the piggy banks sections under "Left for piggy banks". 

### Solution

Better overview about the "available" money you have, considering that you "blocked" part of that money in some piggy banks. 

### What are alternatives?

You can go to the piggy bank section and check it.

**Comment by JC5** [comment]
Good idea, I'll think about it for the new layout.

I'll link this issue to https://github.com/firefly-iii/firefly-iii/issues/6299 and close this one.
