### ISSUE TITLE
Feature request: Providing a daily budget

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#834]
Since you already have the current balance (money_in - money_out) on the dashboard, in my opinion, a small "widget" providing the daily budget allowed to be spent. 

Here's a sample of the code I was thinking about.
```
// date stuff
$date = array();
$date['current_day'] 	= date('d');
//$date['current_day']	= 1; //uncomment this to test code manually
$date['days_in_month'] 	= date('t');
$date['days_left'] 		= $date['days_in_month'] - $date['current_day'];
$date['days_left'] 		= $date['days_left'] + 1; //fixes division by zero error on last day of month

// financial stuff
$finance = array();
$finance['money_out'] 				= 33425;
$finance['money_in']				= 54362;
$finance['money_in_all_accounts']	= $finance['money_in'] - $finance['money_out'];
//$finance['money_in_all_accounts'] 	= 11234; //uncomment this to test code manually

if ($finance['money_in_all_accounts'] >= 0) {
	$finance['daily_budget'] = $finance['money_in_all_accounts'] / $date['days_left'];
} else {
	$finance['daily_budget'] = 0; // it doesn't make any sense to divide a negative value, there's nothing left to spend
}

if ($finance['money_in_all_accounts'] >= 0) {
	echo "you need to survive ".$date['days_left']." more days with the remaining €".$finance['money_in_all_accounts']."<br/>";
	echo "this means you need to spend less than €".$finance['daily_budget'].' per day';
} else {
	echo "wooops! you're broke dude!, you have a debt of €".$finance['money_in_all_accounts']. '<br/>';
	echo "you can spend exactly 0 today, 0 tomorrow, and 0 for the rest of the month";
}
```
Hope you will consider this, it is literally the most important feature I was hoping to find you your app.

Thanks,
Andrei

**Comment by JC5** [comment]
That is not a bad idea! In order to work, I'm thinking of the following (to make it manageable):

- The amount available would be set on the [budgets page](https://firefly-iii.nder.be/budgets) under "Available between September 1, 2017 and September 30, 2017".
- That amount would decrease by expenses, both expenses with a budget and expenses _without_ a budget. This is tricky however. If I have budgeted 1000 in total and spend money outside of my budgets, should it count?

Firefly III had something like this in the past and on the whole it's not a terribly useful feature: assuming your total budget is 1000 and the month has 30 days, you can spend 33 every day. However, when rent is 500 and it's paid on the first day, this amount drops to 16 immediately. 

Having said that, it is still nice to have an indication of what you can spend.

**Comment by gavu** [comment]
Glad you like it. I do get your ideas regarding the budgets, however, I think, as budgets can be “ignored” by under/overspending them, the value indicated should really be based on real/existing amounts. 

You mentioned that adding rent, decreases from 33 to 16. Without a whole lot of automation (to automatically deduct the next batch of bills) this would be almost impossible to achieve, and as you said, the user should be really hands-on managing his money. On the 1st of the month you have 3000euros (100/day) - “yuhuuu, party”, but then you add the bills and get to have 1000euros (33/day) or less - “damn, I’m eating cat food again.” but at least the user is prepared mentally

**Comment by JC5** [comment]
The problem with all accounts is that there are users who also manage shared accounts, so not all money is "theirs". Having a lot of savings would also skew those amounts. 

Using the bills to "soften the blow" is a very good idea. Then, it needs a popup of some kind to explain how the amount is calculated.

**Comment by gavu** [comment]
Is there any chance you would consider implementing this feature? I have some more ideas about what values you could implement to calculate an accurate value for the user.

**Comment by JC5** [comment]
Yes, but I haven't had the time yet.

**Comment by gavu** [comment]
And you do not have time to add new features to your free/opensource project? This is highly unacceptable! 

*insert-sarcasm-emoticon-here*

**Comment by JC5** [comment]
The demo site uses the monthly budget (see /budgets) to show you what you can spend per day.

**Comment by gavu** [comment]
Hi, it looks good, although, I'm not really sure how to work with budgets yet. anyway, I pulled the latest code:

1. set a budget (300euros)
2. assigned some transactions
3. went to the dashboard: overshot by 350 euros -> Left to spend **€0.00** / Per day: **€0.00**
4. added 400euros
5. went to the dashboard: 50 euros left to spend -> Left to spend **€0.00** / Per day: **€0.00**

Could you explain more how this works?

1. what is the formula behind it?
2. does it "ignore" the net worth?

**Comment by JC5** [comment]
Set the total amount available for the current period on the budgets page. This is the amount that gets reflected on the homepage. Make sure this amount of money is divided over your budgets (optional).

![screen shot 2017-09-28 at 11 44 21](https://user-images.githubusercontent.com/5889984/30960171-86960720-a442-11e7-8b14-ed12515b50f0.png)

![screen shot 2017-09-28 at 11 45 45](https://user-images.githubusercontent.com/5889984/30960202-9a5d1974-a442-11e7-93f2-dc2a0383a012.png)

![screen shot 2017-09-28 at 11 44 25](https://user-images.githubusercontent.com/5889984/30960288-e187b476-a442-11e7-9d57-615bc3ce4bd5.png)

![screen shot 2017-09-28 at 11 44 26](https://user-images.githubusercontent.com/5889984/30960293-e60adfd2-a442-11e7-8a05-37ef7abea674.png)

Spend some money. Make sure it has a budget. It will be reflected:

![screen shot 2017-09-28 at 11 46 53](https://user-images.githubusercontent.com/5889984/30960242-bef0e20c-a442-11e7-99e9-78f3a2faa829.png)

The formula is simply all your expenses with a budget. Stuff outside of your budgets is ignored. Your net worth is not updated, it will only become less once you actually spend the money, not when you budget it.

**Comment by gavu** [comment]
Here are the details on my test-system:

Before setting budgets:

- Net Worth: €1,705.35
- Left to spend: €0.00
- Per day: €0.00

After setting budgets:

![issue834_dashboard](https://user-images.githubusercontent.com/3742238/30961652-27a7cd8e-a447-11e7-9e43-c94dd97784e4.PNG)
- Net Worth: €1,705.35
- Left to spend: €0.00
- Per day: €0.00

![issue834_budgets_dashboard](https://user-images.githubusercontent.com/3742238/30961660-2c424d92-a447-11e7-9dfb-053e2532b16f.PNG)
- Budgeted: 700
- Available between September 1, 2017 and September 30, 2017: €0.00
- Spent between September 1, 2017 and September 30, 2017: €-636.39

![issue834_budgets_list](https://user-images.githubusercontent.com/3742238/30961662-2ea60ea2-a447-11e7-9e10-3aee3be80baa.PNG)
- Name: Monthly
- Budgeted: 700

I am confused :)

**Comment by JC5** [comment]
Click "0,00" at "available in" ;)

**Comment by gavu** [comment]
now I'm really confused :) do I have to do this every time?

**Comment by gavu** [comment]
I hope you don't mind me budging in like this and trying to re-organize your project, but here's what I understand, and what I would like to see:

### Piggy banks
- should be more active ($amount_planned / $piggy_bank_duration = $amount_daily)
- every week I import my bank-transactions into FF. Piggy Bank transactions (from now on PBs) are not bank transactions, thus, PBs should be "cash", this means, every time I put something in PBs, I need to extract real cash, in order to be reflected in the real-life bank statement. If I do not extract cash from the ATM, it creates inconsistencies between the bank statements and the net worth produced by FF
- in my opinion, to have it really reflect over real-life (cash), FF and Bank, the PBs should be more active/involved in the money-managemet, and thus, added to the daily budget you just released. For example: `( <incomes> - <paid bills> - <upcoming bills> - <expenses> ) / <days in current month> x <days till next month>`
- now you have a real daily budget which you can compare to that in your bank. to add the PBs, you simply do the substract the $amount_daily (calculated at the beginning) from the above daily budget

### Bills
- automatic matching - awesome
- should be payable in advance (you said you fixed it somehow, got a notification, did not get to test it yet)
- It would be great if on the dashboard (being the first thing you see when you check your finances), I could have a short overview of my upcoming expenses ("_oh crap! - forgot to pay the water bill_" or "_damn! no party this week, I see I still need to pay my car-repair bill_")

### Budgets
- great feature for planning stuff, should be a bit more transparent, as you cannot always go with the budget, maybe at some point you'd like to have the nice glass of wine instead of that drain-pipe-tasting-red-liquid.
- It's a bit confusing:
  - I can create budgets and assign as much as I want, even if there is not enough money in my account
  - I can go over budgets, even if there is not enough money in my account
  - I can "Update (expected) available amount" even though there will never be that much money in my account. 
- I would call the last 3 features "cheating"

### Incomes
- would be great if I could plan my incomes a bit. For example: _should I go on this trip? oh look, right now I'm broke, but my income should be transferred in 2 days_

I do not mean to *highjack* your ideas, it's just that, in my opinion these would be helpful to have

have a few :beers: on me :sweat_smile:

**Comment by JC5** [comment]
How do you use piggy banks at the moment? Do you use them to budget for stuff, like daily or monthly stuff? The primary goal is to divide the money in your savings account. I'm not sure what you mean with $amount_daily. Is it the amount of money you should save to reach the piggy bank's target amount on a specific date?

I use piggy banks to remember what I want to save money for. They are all linked to my savings account and the money in it is divided over them. For example, I have 1000,- in my savings account. It's divided over 3 piggy banks: a new couch, new camera and an emergency fund. Every time I can spare money I transfer it to my savings account, and fill the piggy banks.

A short overview of upcoming bills is possible, I'll see what I can do! To pay them in advance may be possible in the future but I've yet to build it. It will probably mean putting the process date in the future but I'm not sure yet. It would add magic to Firefly and I'm generally not a fan of it.

And yes, you can cheat with budgets. This is on purpose. The idea is that you set the total amount at "Available in" (yes, you must do this every month) and plan the upcoming month accordingly: This works best when you plan ahead: use your income from september to plan for october. You can do this with money you don't have because nothing stops you from budgeting, even an empty account.

Planned incomes is somewhere on the list, but it's not yet very high. Plenty of things to build ;)

Thanks! :D

**Comment by gavu** [comment]
### Piggy banks
> _How do you use piggy banks at the moment? Do you use them to budget for stuff, like daily or monthly stuff? The primary goal is to divide the money in your savings account. I'm not sure what you mean with $amount_daily. Is it the amount of money you should save to reach the piggy bank's target amount on a specific date?_
> _I use piggy banks to remember what I want to save money for. They are all linked to my savings account and the money in it is divided over them. For example, I have 1000,- in my savings account. It's divided over 3 piggy banks: a new couch, new camera and an emergency fund. Every time I can spare money I transfer it to my savings account, and fill the piggy banks._

Finally understood them - nice workaround, I have to admit it! Until now I had another "plan" in mind, piggy banks should be "invisible" micro-transactions, kind of like, every day, the app automatically "blocks" the needed daily amount to save the required amount. But your hands-on approach is actually more "bank-statement" friendly as you involve your savings account too (I thought, and I apologize for misunderstanding, that piggy banks are not actually connected to bank accounts and thus you'd need to extract cash - my mistake)

### Bills

> _A short overview of upcoming bills is possible, I'll see what I can do! To pay them in advance may be possible in the future but I've yet to build it. It will probably mean putting the process date in the future but I'm not sure yet. It would add magic to Firefly and I'm generally not a fan of it._

maybe during the matching workflow add a short info like "_did you just pay another bill? should I skip the next one?_" (it would mean you would have to store the next_occurrence for every bill in the db)

### Budgets
> _And yes, you can cheat with budgets. This is on purpose. The idea is that you set the total amount at "Available in" (yes, you must do this every month) and plan the upcoming month accordingly: This works best when you plan ahead: use your income from september to plan for october. You can do this with money you don't have because nothing stops you from budgeting, even an empty account._

true, is it possible to skip budgeting but still have that Left to spend: €0.00 / Per day: €0.00 feature?

I do not see myself using it any time soon since it makes cheating possible - cheating does not actually reflect the reality of your financial situation. But maybe that's just me and I'll get it later - like I did with the Piggy Banks - Note to self: **RTFM**

### Incomes
> _Planned incomes is somewhere on the list, but it's not yet very high_

there is still hope

> _Plenty of things to build ;)_

is there a roadmap? can we vote on the importance of features?
