### ISSUE TITLE
Safari showing empty dashboard values and js errors in console

### ISSUE THREAD

**Issue by lmaced0** [firefly-iii/firefly-iii#8342]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When opening Firefly using Safari the dashboard and the "Your accounts" graph sometimes fail to show the values and stay empty. When that happens, a bunch of errors are printed on the console.

This happens specially when navigating away from the main dashboard page to other links in the left sidebar then going back.

Error is reproducible in Firefly's demo URL. Not persistent to my setup.

### Debug information

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.4 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>891, base <span>#</span>68</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + America/Denver</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>172.20.0.0/24</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-01-03 10:00:04 (9 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15</td></tr></tbody></table>

```
Truncated from this point <----|[2024-01-03 18:50:40] local.INFO: IsValidPositiveAmount: "5000" is a valid positive amount.  
[2024-01-03 18:50:40] local.INFO: Ignore search operator "user_action"  
[2024-01-03 18:50:40] local.INFO: Ignore search operator "user_action"  
[2024-01-03 18:50:40] local.INFO: Ignore search operator "user_action"  
[2024-01-03 18:50:40] local.INFO: Ignore search operator "user_action"  
[2024-01-03 18:56:31] local.ERROR: Set is not an array! ""  
[2024-01-03 19:15:25] local.INFO: User is trying to login.  
[2024-01-03 19:19:02] local.INFO: User is trying to login.  

```

### Expected behaviour

Dashboards and graphs are empty vs. showing their balance.
The only dashboard that remains working regardless is the "In + Out this Period"

### Steps to reproduce

1. On Safari, open Firefly
2. If Dashboards are populated, navigate away from that page to another page from the left side bar (like Budgets, for example)
3. Then, navigate back to Dashboard
4. If dashboard is not empty by then, repeat a couple more times that it should cause them to be empty

To fix the issue you gotta refresh the screen a few times (F5 or Cmd+R)

![Screenshot 2024-01-03 at 12 48 24 PM](https://github.com/firefly-iii/firefly-iii/assets/83371481/ecadfb2e-216b-46ab-97e1-71ce8909b027)

### Additional info

Interestingly, this only happens on the non-incognito window of Safari, but does not seem to be a cache issue.
I was going crazy with this to make sure I wasn't the issue, so I installed macOS from scratch and without logging in to anything, I was able to reproduce this on the vanilla version.
Here's a video of the issue on macOS: https://www.youtube.com/watch?v=nPc8YLOX8V0

Issue also happens on iPhone that also uses Safari's engine.
Here's a video of the issue on iOS: https://youtube.com/shorts/CcMWumfoRbk

I opened #7953 before but closed because I thought it was an issue with my config, I was using a beta version of Safari at the time. I'm now currently on the latest prod version of everything.

**Comment by JC5** [comment]
Thanks. I'll see what I can find. I've been refreshing the page for a few minutes now, but I got nothing.

Since you're in the console, what's the return for "variables" when you get the error?

<img width="1051" alt="Screenshot 2024-01-03 at 21 36 21" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/176c51a5-0269-4335-a564-a03df858e473">

**Comment by lmaced0** [comment]
variables doesn't seem to exist when I get the error

![Screenshot 2024-01-03 at 1 48 44 PM](https://github.com/firefly-iii/firefly-iii/assets/83371481/866d4029-ab0f-4193-bc1f-ac3537e148f9)

**Comment by lmaced0** [comment]
Ran a few more times in the demo instante and got more errors

![Screenshot 2024-01-03 at 1 54 14 PM](https://github.com/firefly-iii/firefly-iii/assets/83371481/83555776-e992-423f-905e-9f4d7221dac6)

**Comment by JC5** [comment]
All of those errors have the same cause, so that's not the interesting part. Check under "network". What does it say for the "variables" URL when the page fails?

I have no success replicating this issue. Do you have any extensions?

**Comment by lmaced0** [comment]
To reproduce maybe you're just refreshing the page? Refreshing actually fixes the problem.
This happens when moving between pages on the left side bar and going back the Dashboard (like from Budgets to Dashboard for example). I don't have any extensions and I'm able to reproduce it on a vanilla install of [macOS](https://www.youtube.com/watch?v=nPc8YLOX8V0). It's also happening on [iOS](https://youtube.com/shorts/CcMWumfoRbk) where there is no extensions

This is what I get in Network. variables is also missing there and a few other values.

This is what I get with the error:
![Screenshot 2024-01-04 at 10 11 48 AM](https://github.com/firefly-iii/firefly-iii/assets/83371481/db1c1e20-9865-4e5e-9cb3-46d25abf3482)

This is after refreshing a few times to make the error go away:
![Screenshot 2024-01-04 at 10 15 34 AM](https://github.com/firefly-iii/firefly-iii/assets/83371481/ceb5fcd2-7420-4555-97fa-eca8e20b97cf)

**Comment by JC5** [comment]
Found it. It's a bug in Safari.

You can solve it by setting `COOKIE_SAMESITE=""`.

**Comment by lmaced0** [comment]
Is this just an empty `COOKIE_SAMESITE` env value? Not doing it for me. :/ I'm getting the same errors even after clearing cookies, cache and all.

**Comment by JC5** [comment]
That makes sense. The v1 layout uses a "JS file" that's actually rendered by Firefly III, v2 does not. I expected the same site thing to work though, that's what the internet tells me :(
