### ISSUE TITLE
Unable to generate Personal Access Tokens

### ISSUE THREAD

**Issue by coltondick** [firefly-iii/firefly-iii#8343]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm in the process of trying to generate a Person Access Token, whenever I click `Create` nothing happens. 

I've reviewed all of the closed issues and have adjusted `MAIL_MAILER` and set it to `log`, although emails are working correctly, and the issue persists. 

I have enabled `APP_DEBUG=true` and I've attempted to create a PAT again and this time an error is displayed in the browser console: 

```
Uncaught (in promise) 
Object { stack: "B@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:31572\n7218/Ae.xhr</</h/<@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:45492\nh@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:45637\nEventHandlerNonNull*7218/Ae.xhr</<@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:45926\n7218/Ae.xhr<@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:44615\nDe@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:48604\nrequest@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:52232\n7218/</Pe.prototype[e]@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:52526\n7218/n/<@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:26528\ngetTokens@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:343586\nprepareComponent@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:343535\nmounted@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:343473\nGe@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:19092\nFn@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:26919\ninsert@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:30532\nT@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:65782\n7760/vr@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:67216\n7760/t.prototype._update@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:42644\ni@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:73887\nget@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:24904\nxn@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:24843\n7760/Ti.prototype.$mount/<@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:73911\n7760/Ti.prototype.$mount@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:74122\n7760/t.prototype._init@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:41159\nTi@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:38832\n@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:352663\n@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:352747\n@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:352751\n", message: "Request failed with status code 401", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…} }
​
code: "ERR_BAD_REQUEST"
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
message: "Request failed with status code 401"
​
name: "AxiosError"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
response: Object { data: {…}, status: 401, statusText: "", … }
​
stack: "B@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:31572\n7218/Ae.xhr</</h/<@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:45492\nh@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:45637\nEventHandlerNonNull*7218/Ae.xhr</<@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:45926\n7218/Ae.xhr<@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:44615\nDe@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:48604\nrequest@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:52232\n7218/</Pe.prototype[e]@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:52526\n7218/n/<@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:26528\ngetTokens@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:343586\nprepareComponent@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:343535\nmounted@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:343473\nGe@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:19092\nFn@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:26919\ninsert@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:30532\nT@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:65782\n7760/vr@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:67216\n7760/t.prototype._update@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:42644\ni@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:73887\nget@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:24904\nxn@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:24843\n7760/Ti.prototype.$mount/<@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:73911\n7760/Ti.prototype.$mount@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:74122\n7760/t.prototype._init@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:41159\nTi@http://firefly.colton.sh/v1/js/app_vue.js?v=6.1.1:2:38832\n@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:352663\n@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:352747\n@http://firefly.colton.sh/v1/js/profile.js?v=6.1.1:2:352751\n"
​
<prototype>: Object { constructor: B(e, t, o, a, n), toJSON: toJSON(), stack: "", … }
4
```

### Debug information

Debug information generated at 2024-01-03 12:47:28 for Firefly III version **v6.1.1**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.1 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>872, base <span>#</span>68</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Vancouver + America/Los_Angeles</td></tr><tr><td>App environment</td><td>local, debug: true</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>debug, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0</td></tr></tbody></table>

### Expected behaviour

For a Personal Access Token to be generated. 

### Steps to reproduce

1. Login to Firefly III 
2. Navigate to `/profile`
3. Click on the `OAuth` tab 
4. Under Personal Access Token click `Create New`
5. Enter in a name for the PAT 
6. Click `Create`

**Comment by JC5** [comment]
This works fine for me on the demo site. Could you upgrade to 6.1.4 and drop your cookies?

**Comment by coltondick** [comment]
I've upgrade to 6.1.4 and dropped my cookies as you've suggested. However, the issue still persists. 

I've just set `APP_ENV=production` and `TRUSTED_PROXIES=**`, and now I am able to generate PATs.
