### ISSUE TITLE
Data-importer 1.4.0+ does not show report after import process

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#8344]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Using data-importer 1.4.0 does not seems to show in page the report at the end of the process. If you go back after the process ended it will print it correctly (while trying to reload the page continuously).

It can be replicated in the demo site:

https://github.com/firefly-iii/firefly-iii/assets/115389/b3cc6d41-86ee-4088-a3da-4d29c636bd71

### Debug information

Tested in docker, both :latest and :develop images show the same behaviour. Tested on macOS, latest Firefox, Safari and Chrome, private browsing to avoid issues.

1.3.12 works as expected (tested locally)

### Expected behaviour

Show the report at the end of the import phase.

### Steps to reproduce

Run an import, see the missing report at the end.

Attached below are the files used to record the video
[demo.csv](https://github.com/firefly-iii/firefly-iii/files/13823813/demo.csv)
[import_config_2023-10-29.json](https://github.com/firefly-iii/firefly-iii/files/13823814/import_config_2023-10-29.json)

**Comment by JC5** [comment]
This should be fixed in the latest `:develop` Docker image, let me know if it works!

**Comment by psychowood** [comment]
Re-tested in the demo site, confirmed working. Thanks!
