### ISSUE TITLE
Data-importer 1.4.0+ does not apply import tag to all transactions imported from GoCardless

### ISSUE THREAD

**Issue by pvieira84** [firefly-iii/firefly-iii#8347]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since the last update to data importer I've been seing cases where not all impoorted transactions through GoCardless get assigned the import tag, even though I have selected it in my config file.
I cannot identify a pattern for this to happen but it happens with different GoCardless Requistions / FF3 Account combinations

This was working properly in the previous version (maybe related with the introduction of pending/booked tags?)

Here are the config files for the affected accounts (I've masked some data):
[account1_config_2023-11-06.json](https://github.com/firefly-iii/firefly-iii/files/13829038/account1_config_2023-11-06.json)
[account2_config_2023-11-06.json](https://github.com/firefly-iii/firefly-iii/files/13829039/account2_config_2023-11-06.json)

### Debug information

No debug info from data importer

### Expected behaviour

Import tag to be added to each imported transaction

**Comment by JC5** [comment]
I'll need to see some logs before I can do anything about it.

**Comment by pvieira84** [comment]
Would you please help undertand from where to collect the logs?

**Comment by JC5** [comment]
Of course! This page should have all the instructions:

https://docs.firefly-iii.org/how-to/general/debug/

I am curious to see if you can pinpoint in the logs an entry that has not tag, but should have one. We can take it from there.

Send them to me at james@firefly-iii.org for some privacy 😁 .

**Comment by pvieira84** [comment]
I've just sent you the email with the logs ;)

**Comment by JC5** [comment]
The problem was solved and is fixed now.
