### ISSUE TITLE
categories of split transactions are not shown in the category list

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#835]
I use this to handle my incoming and outgoing debts, I have created an outgoing transaction "I bought pizza for everyone" for the amount of e.g. 60 euros (because that money had been substracted from my account) and then created an incoming transaction for the same amount, which I then split into different parts (for each group/person owing me money). For those who payed me back, I used the "Debts Incoming (Solved)" category, and for thos who still owe me, I used the "Debts Incoming (Open)" category.

When checking who still owes me something, I went to the category page to open the "Debts Incoming (Open)" category and noticed the "Last activity" field sais "never" but when clicking on it the transactions are listed

Here's how to reproduce it:

1. create a transaction with Category-A
2. split this transaction into 2 sepparete ones, using Category-B and Category-C
3. go to https://my.host.name/categories
4. for Category-B and Category-C, the "Last activity" field is empty
5. opening https://my.host.name/categories/show/<ID of Category-B> shows part of the split transaction. 

I recreated it on your demo website: https://firefly-iii.nder.be/categories

**Comment by JC5** [comment]
Nice find! The "last activity date" only searches for journals (unsplit transactions).

**Comment by gavu** [comment]
I have the feeling that some day I'll be blocked from reporting bugs and feature requests if I keep going at this rate 😨

**Comment by JC5** [comment]
On you're no record holder yet. @pkoziol is not doing too bad either 😉

**Comment by JC5** [comment]
Fixed on the demo site!

**Comment by JC5** [comment]
Closed to clean the list.
