### ISSUE TITLE
Quick filter on day/week/month

### ISSUE THREAD

**Issue by epacke** [firefly-iii/firefly-iii#8350]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

First of all, amazing work! I was up and running in no time and started to categorise my transactions and started to drive my wife crazy with all the questions around what's what on the bank account (which is ironic since budget stuff was her idea). 😄 

Anyway, when categorising and identifying transfers I think it'd be a great idea to have a dropdown somewhere which can handle quick filters.

#### Scenario:
I've just imported 5 years worth of transactions from 5 bank accounts and identify something that could be a transfer. My method right now would be to go to the date picker and pick a range which is +-7 days from the date of the possible transfer. Then I'd jump between all accounts and see if the same figure is there. If it is, convert to a transfer.

Picking the time range takes a bit too long since (at least I don't think so) there's no good way to iterate year by year and you have to go month by month.

I'm gonna go ahead and attempt on a Chrome extension to solve this right now but I think that it'd save people quite a lot of time if something similar existed.

### Solution

Either add a drop down in the table which could hava a placeholder of Quick filter and give the option to filter on day, week, month.

### What are alternatives?

Something like this:
<img width="1217" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/17186619/690e2411-80a6-4252-9846-0504914becd8">
<img width="1216" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/17186619/40c1964c-a582-4a9a-bb2b-3f24116d8fd7">

Does take up a bit of table real estate though.

Or add a quick filter in the transaction details?
<img width="739" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/17186619/e5ca3693-8d93-4689-b54a-db07b33d18d0">

### Additional context

I'm gonna go ahead and attempt on a Chrome extension to solve this right now but I think that it'd save people quite a lot of time if something similar existed.

Again, thanks for sharing Firefly, it was super fun to organise my finances! ❤️

**Comment by JC5** [comment]
Thanks for the suggestion!

There is no quick link yet, but I'll close this issue and refer to https://github.com/firefly-iii/firefly-iii/issues/6304. I'm working on a new layout where I hope to add fancy buttons like that.

For now, you can do it manually in the search box: 

```
before:2023-01-01
after:2024-01-01
after:"start of this week" before:"end of this week"
```

Of course you can combine them:

```
after:"start of this week" before:"end of this week"
```

For more info: https://docs.firefly-iii.org/references/firefly-iii/search/#date-and-time

**Comment by JC5** [comment]
And thanks of course for the compliments ❤️

**Comment by epacke** [comment]
Closing issue as suggested.

**Comment by JC5** [comment]
Drop me a line at james@firefly-iii.org or open [a discussion](https://github.com/orgs/firefly-iii/discussions) and I'll point you in the right direction!
