### ISSUE TITLE
drag and drop attachment additions to open transaction

### ISSUE THREAD

**Issue by tallguyjenks** [firefly-iii/firefly-iii#8351]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

i would like firefly3 to have the capability to add attachment by dragging and dropping a file onto the browser tab when a transaction is in edit mode 

![image](https://github.com/firefly-iii/firefly-iii/assets/29872822/58184585-14a9-4c15-931d-5fa47be297c0)

and to be able to just drag and drop the attachment onto the transaction rather than clicking `choose files`

![image](https://github.com/firefly-iii/firefly-iii/assets/29872822/e19034d2-24b1-472d-896f-b754fc5dd02e)

### Solution

i would like to be able to drag and drop file attachments onto the transactions rather than opening the file picker modal any time i want to add attachments to a transaction.

i add the receipt to every transaction and repeat this action hundreds of times a month and this would make things much faster and expedient

### What are alternatives?

clicking the `choose files` button and opening the file picker (tedious when you add 100's of attachments a month)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6304
