### ISSUE TITLE
Modifying the direction of a transfer between liabilities yields no effect

### ISSUE THREAD

**Issue by Ezwen** [firefly-iii/firefly-iii#8352]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

_Here I assume that a liability is always money that I owe to someone else._

Currently in Firefly it is possible to transfer an amount from one liability A to a liability B, which works as I would expect : the amount I owe to A is reduced, and the amount I owe to B increases.

For example, if I owe 100 to A and 100 to B, and transfer 50 from A to B, then I now owe 50 to A and 150 to B.

However, if I modify the very same transfer after it has been created, and exchange the source and destination (ie. the transfer is now from B to A), this yields no effect on the amounts in A and B. 

For example, if I reverse the transfer of 50 from A to B, then I **still** owe 50 to A and 150 to B.

### Debug information

Debug information generated at 2024-01-06 13:59:18 for Firefly III version **v6.1.4**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.4 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>891, base <span>#</span>68</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Paris + Europe/Paris</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stdout / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>fr_FR + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-01-06 00:00:00 (13 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>2 of 2</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0</td></tr></tbody></table>

### Expected behaviour

I expect the transfer effect to be reversed (ie. in the example given above, I expect to owe 150 to A and 50 to B.

### Steps to reproduce

I've reproduced the issue from a freshly created Firefly account in the following way : 

- Create a new _Liability_ A, balance of 0, configured as "Debt" and "Owe this debt"
- Create a new _Liability_ B, balance of 0, configured as "Debt" and "Owe this debt"
- Create a new _Deposit_ of 100 from A towards the asset account (to create a debt)
- Create a new _Deposit_ of 100 from B towards the asset account (to create a debt)
- Create a _Transfer_ of 50 from A to B
  - Observe that A is now at 50 and B now at 150
- Modify the transfer created in the previous item, and make it from B to A
    - Observe that A is still at 50 and B still at 150

**Comment by JC5** [comment]
Hey, thanks for reporting. I see what you mean, I'll pick it up!

**Comment by Ezwen** [comment]
Thanks for the blazing fast fix!

It seems this was not included in 6.1.6 after all?

**Comment by JC5** [comment]
What you described was fixed and works perfectly fine on the demo site.

**Comment by Ezwen** [comment]
Hm, I upgraded my instance to 6.1.6, and I encountered this case:

- I create liability X, and borrow 100 from it
- I create liability Y and borrow 100 from it
- I transfer 5 from X to Y

Expected: 
- X = 95
- Y = 105

Result : 
- X = 95
- Y = 95

WDYT?

**Comment by Ezwen** [comment]
I tried the exact same thing on the demo site, and indeed there it does work!

I suppose the demo site is running the `develop` branch, which still need to be merged in `master` to be included in the next release?

**Comment by JC5** [comment]
“main”, not master. But you’re right! You’ll have to wait for the next release.
