### ISSUE TITLE
Firefly III disallows negative foreign currency amounts since 6.1.2

### ISSUE THREAD

**Issue by DireMunchkin** [firefly-iii/firefly-iii#8355]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I noticed that since a few updates ago I can no longer import foreign currency amounts that are negative. This is something I'd like to do since my bank reports debits in foreign currency with a negative amount.

I tried rolling back a few versions, and it looks like 6.1.1 is the last version which allows this, all the later ones will reject it with a message saying that foreign amounts need to be positive.

### Debug information

Debug information generated at 2024-01-07 16:49:14 for Firefly III version **v6.1.1**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.1 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>872, base <span>#</span>68</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + UTC</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-01-07 00:00:00 (16 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; rv:121.0) Gecko/20100101 Firefox/121.0</td></tr></tbody></table>

### Expected behaviour

I'd like to also be able to import a negative number, so I can import debits in foreign currency.

### Steps to reproduce

1. On Firefly III 6.1.2 or later.
2. Import the provided CSV using the provided import config.
  [2023_12_account_statements.csv](https://github.com/firefly-iii/firefly-iii/files/13854229/2023_12_account_statements.csv)
  [Neon Import Config.json](https://github.com/firefly-iii/firefly-iii/files/13854230/Neon.Import.Config.json)
3. Firefly III will disallow saving the transaction.

**Comment by JC5** [comment]
Thanks for letting me know! That's annoying indeed. This behavior will not change however, so I'll make sure the importer adapts.

**Comment by DireMunchkin** [comment]
Yeah one way to fix it would be to add something like a foreign amount (negated) column to the importer if you want to keep that validation rule.

**Comment by JC5** [comment]
Well, I think we can do without an extra type. The foreign amount always "follows" the regular amount, so as long as you set the amount columns to the right type, the foreign amount column will do the same thing.

Should be an easy fix!
