### ISSUE TITLE
Uncaught ReferenceError: submitTransaction is not defined in 6.1.6

### ISSUE THREAD

**Issue by AvengerDr** [firefly-iii/firefly-iii#8359]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When pressing "update" in the new modify transaction screen, the console displays 

```Uncaught ReferenceError: submitTransaction is not defined
    at [Alpine] submitTransaction() (eval at <anonymous> (http://***.synology.me:nnnn/build/assets/vendor-4332182f.js:15:1104), <anonymous>:3:16)
    at vendor-4332182f.js:15:1587
    at tryCatch (vendor-4332182f.js:11:11190)
    at vendor-4332182f.js:15:44189
    at a (vendor-4332182f.js:15:32107)
    at vendor-4332182f.js:15:33195
    at HTMLButtonElement.<anonymous> (vendor-4332182f.js:15:32129)
```

When loading the page, the console also shows error for 
```
Uncaught ReferenceError: tag is not defined
    at [Alpine] tag (eval at <anonymous> (vendor-4332182f.js:15:1104), <anonymous>:3:32)
    at vendor-4332182f.js:15:1587
    at tryCatch (vendor-4332182f.js:11:11190)
    at vendor-4332182f.js:15:38360
    at n (vendor-4332182f.js:15:19847)
    at Object.effect2 [as effect] (vendor-4332182f.js:15:19559)
    at effect$3 (vendor-4332182f.js:11:3435)
    at vendor-4332182f.js:11:3603
    at Function.handler2 (vendor-4332182f.js:15:38354)
    at n (vendor-4332182f.js:15:3381)
```

### Debug information

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.6 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>901, base <span>#</span>3</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v2</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-05-05 00:00:00 (8 months ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has reconciled">:ledger:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>it_IT</td></tr><tr><td>User locale</td><td>it_IT</td></tr><tr><td>Locale(s) supported</td><td>it_IT.utf8: :white_check_mark:<br>it_IT.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The transaction should be updated. Nothing happens. In this specific case it was a transfer.

### Steps to reproduce

1. Select Modify on a transaction.
2. Press update.

**Comment by JC5** [comment]
Thanks for letting me know! The v2 layout is under constant development. Try the latest develop build.

**Comment by JC5** [comment]
See also: https://github.com/firefly-iii/firefly-iii/issues/8361
