### ISSUE TITLE
Weird validation errors

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#836]
Tried to [split some withdrawal](https://firefly-iii.nder.be/transactions/split/edit/649), but got validation error:
> The interest date is not a valid date.

because input contained rrrr-mm-dd (I use Chrome and OS with Polish locale).

Similar thing when just [editing transaction](https://firefly-iii.nder.be/transactions/edit/650):
> The interest date is not a valid date.
> The notes must be at least 1 characters.

I thought that notes were optional?

**Comment by JC5** [comment]
Is this in the dev version?

**Comment by pkoziol** [comment]
Yes, in whatever version that is on demo site.

**Comment by JC5** [comment]
Laravel 5.5 has changed validation rules, and it should work again now!

**Comment by pkoziol** [comment]
Editing transactions works, but splitting does not. It shows "Be right back" (from 500.twig probably).

**Comment by JC5** [comment]
Should be fixed now, thanks for the heads-up!

**Comment by pkoziol** [comment]
Great! Now I know context for [1 new string](https://crowdin.com/translate/firefly-iii/all/en-pl#h=dc727151e5d55dde1e950767cf861ca533528) on Crowdin, but can't translate it, because of type in string ID 😛

**Comment by JC5** [comment]
Crowdin should pick this up within an hour ;)
