### ISSUE TITLE
Additionnal reconcile link

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#8369]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Currenlty, once you are done with a reconiliation, FF comes back to the account's page.
https://firefly.foo.bar/accounts/show/999

In this page, there is no shortcut to reconcile any further and the user needs to go back to the accounts' list, select the account and reconcile.

### Solution

It would be much more convenient to have also a reconcile link on the account's page.
Even better would be a link "keep going" that reconcile the same account and prefills the date for the next month.

### What are alternatives?

Extra clicks

**Comment by JC5** [comment]
Done!  A "keep going" link will be something to add in the new release.

**Comment by chevdor** [comment]
Oh my! Awesome, thank you !!
