### ISSUE TITLE
Export button disabled after error

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#837]
I was playing around with attachments and noticed I can export my transactions as csv and include the uploaded attachments

How to reproduce:
1. Go to https://firefly-iii.nder.be/export
2. Change "End of export range" to something in the future (I wanted to include 2 transactions happening next week)
3. Click "Export" -> throws unformatted error with no alert css: "export_end_range: The export end range must be a date before 2017-09-14."
4. Change "End of export range" to "yesterday" -> Export button is disabled

-> I wanted to use this function to maybe create a manual backup of my records, I noticed the files in /firefly-iii/storage/upload have been renamed to at-*.data and cannot be opened (encrypted?)

-> Is there a backup/restore - disaster recovery plan?

**Comment by JC5** [comment]
Yes. There is a JS thing that disabled that button after a form is submitted. It should be enabled again when there is an error. But i see that the export has more issues, I'll have to look into it.

Attachments are encrypted indeed and stored as `at-*.data`. The only disaster recovery is "make sure you backup your data" ;)

**Comment by gavu** [comment]
Is there any possibility to add a cronjob on the server to access https://budget.gavriliu.com/export and trigger it with some default values? I am a big fan of backups, however, if they are encrypted, they do not really help that much :)

**Comment by JC5** [comment]
I've updated the export code, and it should work just fine. Clear your cache just to be sure. An export cron job should not be difficult to create.

**Comment by JC5** [comment]
This should be included in the next release. You could test this on the development branch or take my word for it. I expect it to be buggy, I've built the happy path and I expect that users will have exotic combinations of records and attachments.

```
php artisan firefly:create-export --user=1 --token=token --with_attachments --with_uploads

Export is running...
The export has finished! You can find the ZIP file in this location:
/sites/FF3/firefly-iii/storage/export/export-2017-09-14_19-19-24.zip
```

To keep it simple and manageable there are no further options to the export. The token is new, you can check this out on the demo site.

**Comment by gavu** [comment]
I will take your word for it, I like living on the edge :). I will give it a test once it is released, there's no hurry, I am still destroying my installation with imports and tests
