### ISSUE TITLE
Bulk delete expense accounts

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#8371]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

See https://github.com/firefly-iii/firefly-iii/issues/5476
cc @taker218

Bulk deletion of "Never" used expense accounts is actually something that is often needed is your use the imported to fetch data from your Bank. Some banks will generate an expense account for each Amazon transaction for instance.
I personally have plenty of those to delete after I batch edited the transactions. So a batch deletion, or even a suggested batch deletion of "Never" used expense accounts would be a huge time saver.

<img width="1474" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/738724/200868c6-b205-404b-b37c-7a57e3b26e22">

### Solution

I think the solution could be in 2  steps:
- allow selection of multiple expense accounts, then deletion
- allow deletion of all Never used expense accounts

### What are alternatives?

click click click click... clik... :)
I wonder btw if someone made a console app such as `k9s` that could work async, that would be such a time saver....

**Comment by JC5** [comment]
Check out your profile, final tab :)

**Comment by chevdor** [comment]
:) I **just** ran into it (and into a few issues using it), that can help indeed as workaroud with a little bash-ery.
Here is the RTFM link for the next one wondering: https://docs.firefly-iii.org/references/firefly-iii/third-parties/apps/

**Comment by JC5** [comment]
:+1:
