### ISSUE TITLE
Error Graph Income vs. expenses Reports page

### ISSUE THREAD

**Issue by nicolopozzato** [firefly-iii/firefly-iii#8374]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi, when i view the Report page and use the "All-time, all accounts" link the first grap h (Income vs. expenses) it's wrong.

In the demo site the problem is the same, if you use the link All-time, the graph shows only 2022/2023 and not also 2024, same for my local installation i don't see the 2024 bars.

### Debug information

Debug information generated at 2024-01-11 12:35:40 for Firefly III version **v6.1.6**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.6 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>901, base <span>#</span>68</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Rome + Europe/Rome</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>it_IT + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-01-11 00:00:00 (12 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>it_IT</td></tr><tr><td>User locale</td><td>it_IT</td></tr><tr><td>Locale(s) supported</td><td>it_IT.utf8: :white_check_mark:<br>it_IT.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

Normally the graph has to show all the year.
If for testing I select from 01/01/2023 to 31/12/2024 now i get the 2024 bars, but if I use the Alltime link the 2024 bars don't show up.

### Additional info

I talk about the demo:
- All-time, all accounts link in the reports page https://demo.firefly-iii.org/reports/default/41,6,1,40,5,42,4,2,3,44/20221201/currentMonthEnd
2024 not in the graph

- https://demo.firefly-iii.org/reports/default/6,4,1,5,44,41,40,42,2,3/20221201/20241231
This time i input the date, 2022-12-01 to 2024-12-31
2024 show up

If I edit the all time all account link changing the currentMonthEnd to currentYearEnd it works
https://demo.firefly-iii.org/reports/default/41,6,1,40,5,42,4,2,3,44/20221201/currentYearEnd
2024 showup
This chages the Net worth graph with showing all the other month of 2024. That's a little useless.

**Comment by JC5** [comment]
I see what you mean, I'll check it out!

**Comment by JC5** [comment]
This should be fixed in the next release, thanks again for reporting!
