### ISSUE TITLE
Query on multiple tags returns duplicates

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#8377]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If you have a transaction with 2 tags `foo` and `bar`, then run a search query such as `tag:foo tag:bar`, the result shows:

- `Firefly III found 1 transaction in 2.224 seconds.` which is correct
- but then it shows the same transaction twice, as it would be 2 transactions

### Debug information

no relevant

### Expected behaviour

The result does not show duplicates

### Steps to reproduce

1. create a transaction with at least 2 tags: `foo` and `bar`
2. not sure if you need a few transactions with only one of the tags above, I don't think so
3. run the query: `tag:foo tag:bar`
4. Observe that Firefly confirms finding a single transaction
5. Observe that the list contains 2 transactions... actuall the same transaction, shown twice

### Additional info

v6.1.6

**Comment by JC5** [comment]
Nice find, I see it too! I'll pick it up :+1:
