### ISSUE TITLE
Ability to delete unused tags

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#838]
While testing the app, I created dozens of tags, which I no longer need, and would really like to have them removed. Is there any user-friendly way of doing this? or should I just delete them from the database?

**Comment by MacPaille** [comment]
I'm currently testing the product to migrate to it and while testing I ran into the same issue. Only way I found is to delete all the records in the database.
Would it be possible to add the possibility to delete tags?

**Comment by pkoziol** [comment]
When you open tag details there are two boxes with three vertical dots in the corner. Clicking them shows menu with option to delete the tag.

![Screenshot showing said menu](https://i.imgur.com/qfDJ7pT.png)

**Comment by MacPaille** [comment]
Didn't saw that before, really good :)
But would it be possible to have some kind of batch deletion to delete multiple like the transactions?

**Comment by gavu** [comment]
Did not see it either, maybe missed it because of the design-inconsistency?

- categories:
  - **can** be deleted in the category list (which is a table)
  - **cannot** be deleted in the category details view
- tags:
  - **cannot** be deleted in the tags list (which is a list)
  - **can** be deleted in the tag details view

**Comment by pkoziol** [comment]
@MacPaille: Maybe it would be possible.
@gavu: You're right, but I'm against adding buttons to the tag list. Maybe it would be better to replace this menu hidden under three vertical dots with buttons like in transaction details? I'll be easier to find/notice.

But... I don't know @JC5 vision and how much work it requires. I just report many issues here 😉

**Comment by JC5** [comment]
I've added extra buttons so the delete / edit options are more noticeable.

I'm not going to create a mass-delete tag thing (it's a really small use case, sorry).

**Comment by JC5** [comment]
Closed to clean the list.
