### ISSUE TITLE
Reconciliation thru last day of month excludes transactions on last day of month

### ISSUE THREAD

**Issue by brhubbar** [firefly-iii/firefly-iii#8384]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When selecting an account to reconcile, the fields automatically populate with 

| Start Balance | | End Balance| |
|-|-|-|-|
|Date | Balance | Date | Balance |
|MM/01/YYYY | Balance end of MM-1/END/YYYY | MM/END/YYYY | Balance end of MM/END/YYYY |

If my transactions are right, the reconciliation will balance if I select every transaction with a date MM/xx/YYYY. However, the reconciliation page prevents me from selecting transactions on MM/END/YYYY. This seems to only be the case for the last day of the month (e.g. reconciling thru 12/28/2023 allows me to select transactions on 12/28/2023, but a reconciliation thru 12/31/2023 does not allow me to select transactions on 12/31/2023).

### Debug information

Debug information generated at 2024-01-13 11:54:31 for Firefly III version **v6.1.6**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.6 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>914, base <span>#</span>78</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Chicago + America/Chicago</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-01-12 00:00:00 (1 day ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-11-01 11:35:24</td></tr><tr><td>Session end</td><td>2023-11-30 11:35:24</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0</td></tr></tbody></table>

### Expected behaviour

When reconciling my balance from `12:00:00AM MM/01/YYYY` through `11:59:59PM MM/END/YYYY`, I should be able to reconcile transactions which occurred on `MM/END/YYYY`

### Steps to reproduce

Links go to the demo site.

1. Create a transaction on 12/31/2023
2. Set the view setting in the top button to December 1, 2023 - December 31, 2023 (you can also skip this and set the dates manually)
3. Go to the [accounts view](https://demo.firefly-iii.org/accounts/asset)
4. Select the account and [start a reconciliation](https://demo.firefly-iii.org/accounts/reconcile/1/index). This will autofill December 1 - December 31. You can do this manually instead.
5. Observe that the transaction on the 31 does not have a check box

### Additional info

End of the month, unexpected behavior:

![image](https://github.com/firefly-iii/firefly-iii/assets/55867501/48af353c-8687-47fc-b5ef-1987b19337e8)

Other day in the month, expected behavior:

![image](https://github.com/firefly-iii/firefly-iii/assets/55867501/3f02beca-4ccb-4f12-8c8b-852b86acc632)

**Comment by JC5** [comment]
Thanks for letting me know! I'm already working on a new layout and by extension, on a new version of this form. As such, I won't be able to fix this particular bug.

See also: https://github.com/firefly-iii/firefly-iii/issues/6302

**Comment by JC5** [comment]
I will make sure of course, it doesn't happen in the new version ;)
