### ISSUE TITLE
Data Importer stops Autoimport of multiple Nordigen/GoCardless files if one has zero transactions

### ISSUE THREAD

**Issue by rerobade** [firefly-iii/firefly-iii#8386]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,

today I've upgraded my firefly instance to fireflyiii/core:version-6.1.6 and fireflyiii/data-importer:version-1.4.0. After the upgrade the autoimport of a directory (it contains multiple Nordigen/GoCardless configurations) failed after importing a Nordigen/GoCardless file with 0 transactions and error

> 2024-01-13 21:37:11: Conversion index (error) 0: Zero transactions found at GoCardless
2024-01-13 21:37:11: Too many errors in the data conversion (1), exit.

### Debug information

Debug information generated at 2024-01-13 22:46:20 Europe/Berlin for Firefly III Data Importer version **1.4.0**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.4.0</td></tr><tr><td>Build</td><td><span>#</span>, base <span>#</span>67</td></tr><tr><td>System</td><td>PHP 8.3.0, Linux, apache2handler</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Berlin, Europe/Berlin</td></tr><tr><td>Environment</td><td>production</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td></td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</td></tr></table>

### Expected behaviour

Even if one Nordigen/GoCardless Configuration returns an empty set of transactions the autoimport should continue to import the other files as well.

### Steps to reproduce

1. Setup data-importer and config directory with at least one Nordigen/GoCardless file and other files for autoimport
2. Ensure that the "zero transaction" Nordigen/GoCardless config is not process as last file
3. Start the autoimport via ```curl --location --request POST 'http://fidi:8080/autoimport?directory=/configurations&secret=****'```
4. check the output and see the some similar error like 

```html
2024-01-13 22:45:03: Going to convert from file /configurations/nordigen_CB_Rene_import_config_2023-12-30.json using configuration /configurations/nordigen_CB_Rene_import_config_2023-12-30.json and flow "nordigen".
2024-01-13 22:45:12: Conversion index (error) 0: Zero transactions found at GoCardless
2024-01-13 22:45:12: Too many errors in the data conversion (1), exit.
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="color-scheme" content="light dark">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="http://docker-prod-01:32780/css/bootstrap-dark.min.css?version=1.4.0">
    <link href="http://docker-prod-01:32780/fa/css/all.min.css" rel="stylesheet">

    <meta name="theme-color" content="#111111" media="(prefers-color-scheme: light)">
    <meta name="theme-color" content="#eeeeee" media="(prefers-color-scheme: dark)">

    <title>500 error :(</title>
</head>
<body>
<div class="container">
    <div class="row mt-3">
        <div class="col-lg-10 offset-lg-1">
            <h1>Whoops! 500 :(</h1>
            <p>
                Sorry, the Firefly III Data Importer broke down.
            </p>
            <h2>Error message</h2>
            <p class="text-danger">
                Import exception (see the logs): Too many errors in the data conversion.
            </p>
            <h2>More information</h2>
            <p>
                The error occurred in <code>/var/www/html/app/Http/Controllers/AutoImportController.php:88</code>.
            </p>
            <p>
                Please collect more information in the <code>storage/logs</code> directory, where you will find log files.
                If you're running Docker, use <code>docker logs -f [container]</code>.
                You can read more about collecting error information <a href="https://docs.firefly-iii.org/how-to/general/debug/"
                                                                        target="_blank">in the FAQ</a>.
            </p>
            <h2>Get help on GitHub</h2>
            <p>
                You're more than welcome to open a new issue <strong><a href="https://github.com/firefly-iii/firefly-iii/issues">on GitHub</a></strong>.
            </p>
            <ol>
                <li>Use the search!</li>
                <li>Include the information <a href="http://docker-prod-01:32780/debug">from this debug page</a>.</li>
                <li>Tell us more than &quot;it says100  4288    0  4288    0     0    211      0 --:--:--  0:00:20 --:--:--  1013100  4288    0  4288    0     0    211      0 --:--:--  0:00:20 --:--:--  1322
 Whoops!&quot;</li>
                <li>Include error logs (see above).</li>
                <li>Tell us what you were doing.</li>
            </ol>

        </div>
    </div>
</body>
</html>
```

### Additional info

Before the upgrade I used data-importer 1.3.12 which worked like expected and did not have this issue. So I was going through your releasenotes and found #8000 and after a closer look also this commit [482d093](https://github.com/firefly-iii/data-importer/commit/482d093e5d0236ca2ecb44f119896ab0936dadab) in which you added an error if zero transactions are returned.
I'm not sure why you see it as an error to get no transactions back. For me it is only an info or a warning because it is expected to get sometimes 0 transactions for some accounts as not all have daily transactions. E.g. we have our saving accounts at another bank which normally are only having transactions once or twice per month.
So currently version 1.4.0 makes data-importer not usable for me without creating some workaround to process each file separately. So I would be happy if you can fix this, please :-)

Thanks and Regards
René

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/8293
