### ISSUE TITLE
Initial balance transactions cannot be edited

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#839]
I wanted to have no uncategorised transactions, so tried to add a "Monthly correction" category to the "Initial balance for [...]" transactions

How to reproduce:

1. Open category "Without category"
2. Click "Select transactions"
3. Select "Initial balance for [...]"
4. Click "Edit selected" (I have selected 3)

Message:

> There are 3 messages:
> You cannot edit the opening balance of an account.
> You cannot edit the opening balance of an account.
> You cannot edit the opening balance of an account.

Error:

> Error! You have selected no valid transactions to edit.

Possible solutions:

1. Hide them from the "Without category" list
2. Remove the select-box from the "Initial balance for [...]" transactions in the list

**Comment by JC5** [comment]
Nice catch. They should be filtered out indeed. I've updated the code to remove them. 👍

**Comment by JC5** [comment]
Closed to clean the list.
