### ISSUE TITLE
Invalid redirect for v2 layout

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#8392]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi James!

Opening this because of the GitHub Bot comment in #7143.

I wanted to start playing around with the new v2 layout since the transaction form is implemented, but get the same error as before. When trying out the new V2 layout, the same error resurfaces :( Navigating to https://firefly.example.com/v2 redirects me to https://firefly.example.com:8080/v2, which is invalid of course. I'm still running Firefly III inside Docker (currently v6.1.6), but I switched to a new reverse proxy (which is still NGINX-based).

My original theory for the origin of the bug still remains. Do you know if there is a way to change the port under which Firefly III is running inside the container? If yes, then I could change the port (e.g. via an environment variable) to 80 to test my theory. Side note: The original workaround of manually adding the second slash (/v2/) does not work anymore. Now, I get a HTTP 403 Forbidden:

![grafik](https://github.com/firefly-iii/firefly-iii/assets/30748216/eae9e8d9-d7aa-481d-af31-cbf609cc2c35)

I'm using the Docker container behind an NGINX-based reverse proxy. Do you have any clue why a redirection to Port 8080 could happen? My guess is that swag is redirecting the request to the Docker containers internal port, which is 8080, which leads Firefly III to believe that it's public port is 8080 as well.

### Debug information

Debug information generated at 2024-01-14 18:51:53 for Firefly III version **v6.1.6**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.6 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>914, base <span>#</span>78</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2022-10-19 03:00:01 (1 year ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 2</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0</td></tr></tbody></table>

### Expected behaviour

Should stay on the same port that was called. Since we are running in a containerized environment and the server receives the original request URL, I'd call this a server issue, but can of course understand if there currently is no capacity or need to fix this.

### Steps to reproduce

1. Setup any webserver as a reverse proxy for Firefly III (should run under port 80/443)
2. Run Firefly III as a docker container (or via port 8080).
3. Navigate to `/v2` (using the reverse proxy, so port 80/443). It will redirect to port 8080, which is not publicly available.

**Comment by niklas2810** [comment]
Oh, and sorry about the invalid cron job (although I don't think that's the source of the issue). Turns out my cron job was pinging the demo site, however that happened... 😅

![grafik](https://github.com/firefly-iii/firefly-iii/assets/30748216/50f60209-291d-4c94-84f2-6ecd49e72e4f)

**Comment by JC5** [comment]
The v2 layout isn't hosted under /v2/, you'll have to change `FIREFLY_III_LAYOUT=v2`.

I know about the redirect issue. It's something to do with the built-in Apache but since /v3/ no longer exists and v2 doesn't need the redirect, I've decided not to try and fix it.

But you did explain some mysterious log entries I kept seeing on the demo site. I thought somebody was testing things 😁
