### ISSUE TITLE
Choose amount format for import

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#840]
I'm currently testing the product to migrate from my old AceManager which is not updated for a LOOONG time.
I'm a French speaking Belgian and my locales are , for the decimal separator and a . for the 1000 separator.
I think it would be a nice addition to ask these 2 values like you do with the date format on the first step of the importer.
Do you think you could implement that?

**Comment by JC5** [comment]
Did you try it already? As far as I can tell, it works already.

![screen shot 2017-09-14 at 10 36 07](https://user-images.githubusercontent.com/5889984/30420002-9910db74-9938-11e7-8c42-a39774883b7a.png)


![screen shot 2017-09-14 at 10 35 58](https://user-images.githubusercontent.com/5889984/30420014-9c335cbe-9938-11e7-95e6-9c2dabe6e91e.png)

**Comment by MacPaille** [comment]
I tested with your example and it works, so I'll investigate more to understand the issue in my file.
Thanks!

**Comment by JC5** [comment]
Yes, I am curious what it could be, and perhaps if FF could accommodate for it.

**Comment by MacPaille** [comment]
After more test, it's only working if the amount value is between " ". As I open my export CSV to Excel to transform some fields "the withdraw amount is not negative) it removes all the " " when I save it again. When I import that version it doesn't recognize the , ad decimal separator and for example 24.5 become 245.

Is it an expected behavior?

**Comment by JC5** [comment]
Are the values in the file separated by `,` or by `;`? You must select the correct one when importing.

For example, consider this CSV row:

`a,b,c,d,12,45`

When entries are separated using the comma, Firefly III will assume both `12` and `45` are separated values. This is usually prevented (as in your file) by using quotes:

`a,b,c,d,"12,45"`

However, Excel has a different strategy and uses the `;` to separate values.

`a;b;c;d;12,45`

Could you open your CSV file in Notepad and check what kind of separator it uses? This must be reflected when importing your data:

![screen shot 2017-09-15 at 06 57 01](https://user-images.githubusercontent.com/5889984/30467163-22677c52-99e3-11e7-9597-c3264325a851.png)

**Comment by MacPaille** [comment]
Excel saves it with ; and I correctly set it in firefly for the import ;)
The previous of what is in each column while importing is very useful for that!

**Comment by JC5** [comment]
Ok good, but that means something is still going wrong, I think. Could you share one line of your CSV file with me, and the import configuration from the page just before you start the import?

With that, I can see why Firefly III is making the mistake. Thanks!

**Comment by MacPaille** [comment]
I'm updating this ticket, sorry for the delay I didn't had time to test more...
By converting the file to UTF-8 the import works well, but I still found one issue. If the amount contains a comma for decimal separator, it seems required to have 2 digits after it.
For example importing 4,50 is OK but if the value is 4,5 it will import as 45 euros...

It's an issue for me as my CSV export does not set the 2 digit after the comma if it's a multiple of 10...

**Comment by MacPaille** [comment]
Found the solution, after forcing Excel to set the format as number it adds the 2 digits after the comma. But maybe it would be good to still do something if the number does not contain 2 digits after the comma?

**Comment by JC5** [comment]
That's a nice case! I thought it was possible to do this. But I'll check it out and get a fix for the next version

**Comment by JC5** [comment]
I've found the issue. The next release of Firefly III should be able to correctly convert "4,5" to "4.50". Up until then, you'll have to change this by hand. Keep an eye on the Github repository so you know when the next release is due!

**Comment by MacPaille** [comment]
Thanks for the quick fix :)
