### ISSUE TITLE
New credit card payment plans

### ISSUE THREAD

**Issue by SplinterHead** [firefly-iii/firefly-iii#8403]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

In the setup for a credit card account, there is a section for payment plans, currently this has only one option - "Full payment every month". It would be cool to have some other options

* Set amount every month
* Minimum monthly payment

### Solution

Minimum amount would need to take a percentage of the balance AND the minimum amount (for if the balance is very low)

i.e Credit cards tend to have a clause of "Minimum payment is 0.5% of balance or £25, whichever is more"

**Comment by JC5** [comment]
It's just a visual indicator right now, I'm not really planning to do anything with it. But I'll write it down!

**Comment by SplinterHead** [comment]
Could it create a new Bill to keep track of when it's paid and also to help budget remaining balances? It seems like you'd have enough information for it

**Comment by SplinterHead** [comment]
@ptourne I think you should raise a new feature request for that, it's a little out of scope for what I was thinking with this issue. Also, it might get lost in the comments

**Comment by SplinterHead** [comment]
@elChapoSing when creating or editing an asset account, you can choose between a few options for what the account role is 

<img width="682" alt="Screenshot 2024-02-01 at 14 23 13" src="https://github.com/firefly-iii/firefly-iii/assets/2191445/fea089b9-67c0-467b-baed-dc2f0ef9c5b0">

**Comment by elChapoSing** [comment]
Ah OK I was searching in the liabilities account - got it thank you !
And does it actually behave as you would expect by negating all numbers or do you have to find a way to do that manually ?

**Comment by SplinterHead** [comment]
@elChapoSing What do you mean by negating numbers, are you talking about having a negative Opening Balance? That's the only negative number

I've got rules set up to do the following:
*Note:* I have auto imports for both main and Credit Card accounts
- Find a transfer from main account to "Credit Card" and change that transaction to a transfer (balance on CC gets closer to 0 - ie £-50, transfer £25, new balance is £-25)
- Find the corresponding transaction on the CC statement and delete it (as the transfer now represents that)

Purchases on my Credit Card still increase the negative balance (further from 0), its personal preference that I like it represented like that. I haven't played with Liabilities all that much, just for a car and student loans

**Comment by elChapoSing** [comment]
What I meant is when a charge shows up on my credit card, I want it represented as a negative number so my net assets are correctly summed up.
I am importing from my bank directly so I'll have to see how it behaves.
Will look into rules - thks for the pointer - might be as simple as making sure all transactions imported from the credit card show as withdrawals instead of deposits

**Comment by SplinterHead** [comment]
@elChapoSing charges on Credit Cards should show as negative by default, they're classed as a withdrawal

**Comment by elChapoSing** [comment]
Ok cool thank you - will play around with it!

**Comment by JC5** [comment]
Credit card payment plan options will be dropped in a future release. The fields are not used in Firefly III.
