### ISSUE TITLE
Import file with accented caracters

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#841]
Hello,

As French speaker I'm proud that our langage contains so much special characters like é è à ê ô ï etc...
I tested a lot of things but the importer does not support these, even if I change the encoding of the csv file.
Would it be possible to support these?
Thanks!

**Comment by JC5** [comment]
I'm not sure what the problem could be, since FF3 supports accented characters just fine. I've tested this, and it seems to work in my own test installation.

Are you sure all of your files (and the server) are in utf-8?

**Comment by MacPaille** [comment]
I suppose it's my bad. After having converted to UTF-8 using notepad++ the import works well.
Thanks for the help!

**Comment by JC5** [comment]
I'm glad it works! 👍
