### ISSUE TITLE
Getting `Unexpected data found.` trying to import via GoCardless/Nordigen

### ISSUE THREAD

**Issue by dabeeeenster** [firefly-iii/firefly-iii#8414]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm running FIrefly `6.1.6` and the importer via Docker. I upgraded the importer from tag `1.3` to `1.4.1` and am now seeing errors. Reverting back to `1.3` works. 

```
[2024-01-18 09:45:07] production.ERROR: Unexpected data found.
Trailing data {"exception":"[object] (Carbon\\Exceptions\\InvalidFormatException(code: 0): Unexpected data found.
Trailing data at /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:690)
[stacktrace]
#0 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(713): Carbon\\Carbon::rawCreateFromFormat()
#1 /var/www/html/app/Services/Nordigen/Model/Transaction.php(109): Carbon\\Carbon::createFromFormat()
#2 /var/www/html/app/Services/Nordigen/Response/GetTransactionsResponse.php(47): App\\Services\\Nordigen\\Model\\Transaction::fromArray()
#3 /var/www/html/app/Services/Nordigen/Request/GetTransactionsRequest.php(67): App\\Services\\Nordigen\\Response\\GetTransactionsResponse->__construct()
#4 /var/www/html/app/Services/Nordigen/Conversion/Routine/TransactionProcessor.php(109): App\\Services\\Nordigen\\Request\\GetTransactionsRequest->get()
#5 /var/www/html/app/Services/Nordigen/Conversion/RoutineManager.php(99): App\\Services\\Nordigen\\Conversion\\Routine\\TransactionProcessor->download()
#6 /var/www/html/app/Console/AutoImports.php(378): App\\Services\\Nordigen\\Conversion\\RoutineManager->start()
#7 /var/www/html/app/Console/AutoImports.php(192): App\\Console\\Commands\\AutoImport->startConversion()
#8 /var/www/html/app/Console/AutoImports.php(101): App\\Console\\Commands\\AutoImport->importFile()
#9 /var/www/html/app/Console/Commands/AutoImport.php(90): App\\Console\\Commands\\AutoImport->importFiles()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoImport->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#16 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#18 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#19 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#20 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#22 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#23 {main}
"}

In Creator.php line 690:

  Unexpected data found.
  Trailing data
```

### Debug information

Debug information generated at 2024-01-18 08:46:59 for Firefly III version **v6.1.6**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.6 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>914, base <span>#</span>78</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + Europe/London</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The importer runs and imports transactions

### Steps to reproduce

1. Run importer tag `1.4.1` with a nordigen/gocardless import file 
2. See error posted above

**Comment by JC5** [comment]
Nice find! I haven't seen this myself yet (I also use Nordigen).

Could you share with me the debug logs of an import run up until the error? You can send them to me over email

https://docs.firefly-iii.org/how-to/general/debug/

**Comment by JC5** [comment]
Alright, I think I know what the cause is, I expect I can fix this for the next release of the data importer.

**Comment by JC5** [comment]
Could you run your import using the `:develop` branch? I expect it has been fixed there.

**Comment by dabeeeenster** [comment]
Yep all good here!
