### ISSUE TITLE
Reconciled flag lost on batch (indiv+bulk) edits

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#8415]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I found #5070 which partly answers my question.

After edited some entries, I see that I am losing some 'reconciled' flags.
My edit were mostly around editing, after reconciliation, the following:
- tags
- category
- budget
- bill
- description

According to the issue above, the fields resetting the `reconcilied` flag are:
- date
- description
- source
- destination
- amount

So the real issue I am running into is that editing the **description** resets the `reconciled` flag.

While I think most fields above do make sense locking, I don't think locking the **description** is beneficial.

### Debug information

n/a

### Expected behaviour

Editing a description should not void the `reconciled` flag.

### Steps to reproduce

- reconcile a tx
- notice that the reconciled flag is set
- edit the description
- notice that the reconciled flag is now unset

**Comment by JC5** [comment]
Thanks, I'll check it out!

**Comment by JC5** [comment]
I can't replicate this issue. Please clarify how you edit transactions

**Comment by chevdor** [comment]
I tested a simple description edit and indeed, the flag remains.
It smells like some edge cases and not the issue I initially suspected. I ran a few tests.

So here are a few tests:
- edit description: flag remains ✅
- add tag: flag remains ✅
- remove tag: flag remains ✅
- bacth edit / individually (of a single tx) and add category: the flag is removed ❌
- single edit and add category: flag remains ✅
- batch edit / individually  (of a single tx) and edit the description: the flag is removed ❌
- batch edit / bulk (of a single tx) and add a Category: the flag is removed ❌
- batch edit / bulk (of a single tx) and add a tag: the flag is removed ❌

So the issue seems to be related to batch edit and affects:
- edit selected individually
- edit selected in bulk

**Comment by JC5** [comment]
Nice work, I'll pick it up!
