### ISSUE TITLE
Unable to create rule with trigger having type has_no_budget via the API 

### ISSUE THREAD

**Issue by tailg8nj** [firefly-iii/firefly-iii#8418]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am able to create a rule using the UI having a trigger type of `has_no_budget`, but when I try to do so via the API, I cannot find a suitable value for the `value` property.

### Debug information

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.6 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>901, base <span>#</span>68</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + America/New_York</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</td></tr></tbody></table>

### Steps to reproduce

```sh
curl -X POST http://localhost:80/api/v1/rules \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "Accept: application/json" \
  -H 'Content-Type: application/json; charset=utf-8' -v \
  --data-binary @- << EOF
    {
        "rule_group_id": "1",
        "title": "Budget Store Everything Else",
        "order": 1,
        "active": true,
        "strict": true,
        "stop_processing": true,
        "trigger": "store-journal",
        "triggers": [{
            "type": "has_no_budget",
            "value": "",
            "order": 1,
            "active": true,
            "stop_processing": true
        }],
        "actions": [{
            "type": "set_budget",
            "value": "Everything Else",
            "order": 1,
            "active": true,
            "stop_processing": true
        }]
    }
EOF
```

I get the following error:

```
{"message":"The triggers.0.value must be at least 1 characters.","errors":{"triggers.0.value":["The triggers.0.value must be at least 1 characters."]}}
```

I've also tried omitting the `value` property on the trigger and also setting it to `null`.

### Additional info

When I create a rule with a trigger of `has_no_budget` using the UI and then fetch with the API, I see:

```sh
curl -X GET http://localhost:80/api/v1/rules \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "Accept: application/json"
```

```json
{
    "data": [{
        "type": "rules",
        "id": "1",
        "attributes": {
            "created_at": "2024-01-18T17:25:12+01:00",
            "updated_at": "2024-01-18T17:25:12+01:00",
            "rule_group_id": "1",
            "rule_group_title": "Default rules",
            "title": "Budget Store Everything Else",
            "description": "",
            "order": 1,
            "active": true,
            "strict": true,
            "stop_processing": true,
            "trigger": "store-journal",
            "triggers": [{
                "id": "2",
                "created_at": "2024-01-18T17:25:12+01:00",
                "updated_at": "2024-01-18T17:25:12+01:00",
                "type": "has_no_budget",
                "value": "",
                "order": 1,
                "active": true,
                "stop_processing": false
            }],
            "actions": [{
                "id": "1",
                "created_at": "2024-01-18T17:25:12+01:00",
                "updated_at": "2024-01-18T17:25:12+01:00",
                "type": "set_budget",
                "value": "Everything Else",
                "order": 1,
                "active": true,
                "stop_processing": false
            }]
        },
        "links": {
            "self": "http:\/\/localhost\/api\/v1\/rules\/1",
            "0": {
                "rel": "self",
                "uri": "\/rules\/1"
            }
        }
    }],
    "meta": {
        "pagination": {
            "total": 1,
            "count": 1,
            "per_page": 50,
            "current_page": 1,
            "total_pages": 1
        }
    },
    "links": {
        "self": "http:\/\/localhost\/api\/v1\/rules?limit=50&page=1",
        "first": "http:\/\/localhost\/api\/v1\/rules?limit=50&page=1",
        "last": "http:\/\/localhost\/api\/v1\/rules?limit=50&page=1"
    }
}
```

**Comment by JC5** [comment]
Have you tried submitting `"value": "true",`?

The return value should also be `"true"`, I'll correct that, and add this to the documentation.

**Comment by tailg8nj** [comment]
Can confirm `"true"` works. Thanks for the quick response!
