### ISSUE TITLE
No decimals/comma's

### ISSUE THREAD

**Issue by derkommandant** [firefly-iii/firefly-iii#842]
Hi,

I've just running Firefly III, but noticed that I can't add decimals behind numbers. Also no numbers show decimals. In the settings it says that their should be 2 decimals for euros
For example:
If I a make a debit of 2,1 euros and I enter it, becomes 210 euros.

Any idea on how to solve this?

**Comment by JC5** [comment]
https://firefly-iii.github.io/faq-technical.html

Under "Decimal points are missing, numbers are off, stuff like that"
