### ISSUE TITLE
Broken batch application of non-strict rules with triggers with stop processing

### ISSUE THREAD

**Issue by alexschlueter** [firefly-iii/firefly-iii#8427]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When a non-strict rule has multiple triggers with stop processing checked, triggering a batch application (for example through "see matching transactions") will not apply to transactions for which the first trigger is false, but a subsequent trigger is true.

### Debug information

Debug information generated at 2024-01-19 23:20:32 for Firefly III version **v6.1.6**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.6 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>914, base <span>#</span>78</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: true</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>debug, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-01-19 00:00:00 (23 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 3</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has reconciled">:ledger:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0</td></tr></tbody></table>

### Expected behaviour

Every transaction for which one of the triggers applies should be acted upon in a non-strict rule.

### Steps to reproduce

1. Create a non-strict rule
2. Add two triggers with stop processing checked
3. Create a transaction which only matches trigger 1 and a second transaction which only matches trigger 2
4. Click "See matching transactions" or "Apply ... to a selection of your transactions"
5. Check if transaction 2 was processed

### Additional info

I believe this is due to the early break statement in SearchRuleEngine->findNonStrictRule here: https://github.com/firefly-iii/firefly-iii/blob/7db21612a03443e86248aec4537fef58aa7294bf/app/TransactionRules/Engine/SearchRuleEngine.php#L337

This will break out of the loop over all triggers, which means that no transactions can be found for which the first trigger is false, but the second one is true.

**Comment by JC5** [comment]
So when you tell it to stop processing other triggers, it stops processing other triggers, that's the bug?

**Comment by alexschlueter** [comment]
Maybe I'm confused about the meaning of "stop processing" for triggers? I understood [the documentation](https://docs.firefly-iii.org/how-to/firefly-iii/features/rules/#stop-processing-other-triggers) from the perspective of a single transaction being checked against the triggers one by one, and if a trigger with "stop processing" applies, the following triggers are not checked. Although I understand that that would make it pointless for non-strict rules.
Your [comment on this issue](https://github.com/firefly-iii/firefly-iii/issues/8271#issuecomment-1863355384) seemed like it was confirming my understanding.
As it is coded now, isn't it also inconsistent between when the two transactions are first created one after the other vs when the rule is applied to both at the same time?

**Comment by JC5** [comment]
Yes there are (by "design") things that are inconsistent in the rule engine, especially with triggers. The search for transactions is often limited. 

For your example, I created a rule that has two triggers: starts with A, starts with B.

1. When applying the rule to ALL transactions, it only finds "A", and will never find B.
2. I can make it find B, by excluding the account that holds A
3. I can also make it find B, by creating a new transaction B, because in those cases the rule engine only checks the newly created transaction.

I'll expand the documentation on this.
