### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#843]
Just found some missing translations, thought I'd add them here:

1. just below the import progress bar: "firefly.import_status_job_running"
2. https://my.host.name//transactions/mass/delete/[...]: "list.total_amount" (table header)

**Comment by JC5** [comment]
I've added them, thanks!

**Comment by gavu** [comment]
Just found another one

https://my.host.name/tags/show/17/all: firefly.total_result

**Comment by JC5** [comment]
Also fixed!

**Comment by gavu** [comment]
...aaand another one

/import/file/status/Qy0Gtk6CcOfn: Home / Import / **firefly.import_file** / Import status (Breadcrumbs)

**Comment by JC5** [comment]
Closed to clean the list of issues. That particular translation has been added, btw ;)
