### ISSUE TITLE
The Opening/ Virtual Balance must less than or equal 100001709

### ISSUE THREAD

**Issue by binhtran1604** [firefly-iii/firefly-iii#8431]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi, 

Im getting the warning message while creating new Asset account, if I put in the opening balance or either virtual balance over 100001709 then get the warning message.

![CleanShot 2024-01-21 at 10 59 42](https://github.com/firefly-iii/firefly-iii/assets/66913866/a3bfd855-0805-46c9-9fc8-a8b4f6287e27)

I tried to check 

### Debug information

Create any new asset account with opening/ virtual balance, any account role (saving, credit card ...), type the number over 100001709 then the warning come, asset account will not save ****

### Expected behaviour

Asset account does not limit to 100001709 (~ 100m), this limitation is still small base on some kind of currency.

### Steps to reproduce

1. Create new asset account
2. Choose any account role 
3. Give the opening/ virtual balance a number greater than 100001709

**Comment by JC5** [comment]
Which currency are we talking about?

**Comment by JC5** [comment]
For now; set the maximum amount, and create deposits until you reach the desired balance.

**Comment by binhtran1604** [comment]
> Which currency are we talking about?

Vnd or usd still same result, I still not try with other currencies but I think still same 


> For now; set the maximum amount, and create deposits until you reach the desired balance.

Thanks, It’s ok as a temporary solution, but I just wonder will it going to increase in the future or stay as of now

**Comment by JC5** [comment]
I'll pick it up!
