### ISSUE TITLE
may be a wrong calculation

### ISSUE THREAD

**Issue by PterX** [firefly-iii/firefly-iii#8433]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

<img width="941" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/1871048/e5395a42-4364-476b-ac77-e12c52826016">

### Debug information

<img width="1363" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/1871048/ca74aaea-9cb8-4b9b-bb8e-4b93119f4ae6">

The value of Amount due should be the same as Balance difference here

<img width="1115" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/1871048/da47a673-8bd7-422e-920c-67e6a2f06540">

Then when debugging, I saw that the above expression did not match the log. The result was correct after changing it.

**Comment by JC5** [comment]
Could you share the logs please?

**Comment by PterX** [comment]
> Could you share the logs please?

Sorry, I have released my development environment

**Comment by JC5** [comment]
I can't replicate the problem. The comments are wrong, that is true. But the math seems to be right. Your PR would make it worse, not better.

**Comment by PterX** [comment]
> I can't replicate the problem. The comments are wrong, that is true. But the math seems to be right. Your PR would make it worse, not better.

I think this is a problem. Do you need the log before modification or after modification? I can do it again.

**Comment by JC5** [comment]
Before, please.

**Comment by PterX** [comment]
[Uploading ff3-cli-server-2024-01-21.log…]()

**Comment by PterX** [comment]
[ff3-cli-server-2024-01-21.log](https://github.com/firefly-iii/firefly-iii/files/14001639/ff3-cli-server-2024-01-21.log)

**Comment by JC5** [comment]
What kind of a transaction is the 10.000 one?

**Comment by PterX** [comment]
> What kind of a transaction is the 10.000 one?

Is transferout to another loan account

**Comment by JC5** [comment]
Thanks for the logs, I have found the issue indeed. It was in a different place than you suggested, please see my commit above this comment.

**Comment by PterX** [comment]
> Thanks for the logs, I have found the issue indeed. It was in a different place than you suggested, please see my commit above this comment.

This is best. Maybe I don’t fully understand your code. I will take the time to read it again.
