### ISSUE TITLE
v6.1.7 - Not expected this period

### ISSUE THREAD

**Issue by poudenes** [firefly-iii/firefly-iii#8442]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since last update to v6.1.7 I see in overview of bills some bills with "Not expected this period" But they are for every month.
They are active, and there is no skip value added.

### Debug information

Debug information generated at 2024-01-22 12:07:31 for Firefly III version **v6.1.7**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.7 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>933, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Amsterdam</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-03-01 12:05:17</td></tr><tr><td>Session end</td><td>2024-03-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15</td></tr></tbody></table>

### Expected behaviour

That this message is not appear when the bills configured for every month.

### Additional info

<img width="1227" alt="Screenshot 2024-01-22 at 12 10 41" src="https://github.com/firefly-iii/firefly-iii/assets/4399532/29938836-23a5-43c3-8f66-688158f9b9b1">

**Comment by JC5** [comment]
Your view is set to March, so this is not entirely unexpected when January and February aren't finished yet. Firefly III won't calculate into the future all too far.

**Comment by JC5** [comment]
Try browsing to /flush.

**Comment by poudenes** [comment]
Same output. (Screenshot)

**Comment by JC5** [comment]
Could you get a screenshot of a bill and include the top bar please? feel free to censor amounts, email addresses or names.

**Comment by poudenes** [comment]
Here you are! I send you one screenshot. The other bills have exact same information. Different amount and names.

<img width="1255" alt="Screenshot 2024-01-23 at 08 56 11" src="https://github.com/firefly-iii/firefly-iii/assets/4399532/60463d5b-ecd3-4ea4-9048-23eeed90b00f">

**Comment by JC5** [comment]
<img width="1236" alt="Screenshot 2024-01-23 at 20 26 21" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/10b08d55-1d17-46e0-b60e-3a68d47cea86">

Mmmm. I got nothing. Let me share some debug instructions, send me the results if you would to james@firefly-iii.org

**Comment by JC5** [comment]
Never mind, i found the issue. Thanks for letting me know, that was a tricky one! It'll be fixed in the next release.

**Comment by poudenes** [comment]
Ahh good to hear. I was planning to do the whole debug for you. Happy that you found the issue.

**Comment by JC5** [comment]
When it's done.

**Comment by poudenes** [comment]
2 Bills has been payed now. The February part is gone. The January part is still there. So for month January those 2 bills are not paid in overview. (maybe important for this issue above)
