### ISSUE TITLE
There is an extra X ending symbol here

### ISSUE THREAD

**Issue by PterX** [firefly-iii/firefly-iii#8446]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

                            <span class="text-info money-transfer">
https://github.com/firefly-iii/firefly-iii/blob/ec59f80fe3c18d408382e4916dec9d95eb45b556/resources/views/list/groups.twig#L64

There is an extra X ending symbol here

### Debug information

view above

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
Let's wait for the next release, then it can be closed.
