### ISSUE TITLE
Chart shows only a warning sign due to erroneous dates (years way in the past)

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#8453]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I just ran into an issue after importing some data from CSV.
My charts were all showing just a:
<img width="36" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/738724/54e799e5-67f5-4ed7-9e55-14200eec8520">

### Debug information

I figured out that, durring the import, some tx what should have been from `2004` were imported as `0004`. 
This is not due to the import but to errors in my CSV data.
After batch editing those few entries, the issue resolved itself.

### Expected behaviour

The user should make no mistake... sure :)

I see a few options that could be helpful, not sure which one is the easiest to implement:
- during import, raise warnings for "crazy" transactions like before `1900` maybe or older than 100 years old.
- show a message instead of the warning that there may be an issue with some dates

### Steps to reproduce

- Take a working env.
- Edit one date to `0004` instead of `2024` for instance.
- reload the page

### Additional info

I think this is super edge case and probably no worth spending too much time but a warning during import may put the user on track and save a few issues from landing here.

**Comment by chevdor** [comment]
It came with a little delay so I did not immediately see the error but I did get actually a fairly good error per email:

> Hi there,
> 
> Firefly III v6.1.7 ran into an error: Date range out of range..
> 
> The error was of type "FireflyIII\Exceptions\FireflyException".
> 
> The error occurred on/at: Wed, 24 Jan 2024 16:15:32 +0100.
> 
> This error occurred in file "/var/www/html/app/Api/V1/Requests/Data/DateRequest.php" on line 50 with code 0.

If we know the date is out of range, this could be picked up during import to ensure that no crazy data lands on the DB.
An elegant solution would be to add a `warning` tag on those imported transaction, allowing the user to quickly find and fix them.

**Comment by JC5** [comment]
I appreciate the idea, but this is a problem most users are more than capable of solving themselves without me adding all kinds of checks and balances. I don't think there's added value.

**Comment by chevdor** [comment]
Yeah, fair enough, seeing the email warning is rather specific, I am closing the issue.
