### ISSUE TITLE
PWA webmanifest missing from select pages

### ISSUE THREAD

**Issue by absentbri** [firefly-iii/firefly-iii#8455]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have noticed that some (perhaps newer?) pages do not include the webmanifest for PWA support. 

These include pages such as Login and Dashboard (which, are kind of the most important to have this present IMO). Other pages such as Bills or Budget present the manifest just fine.

This is potentially just an oversight of a/the (new?) templating system where it doesn't have the include such is present in https://github.com/firefly-iii/firefly-iii/blob/ec59f80fe3c18d408382e4916dec9d95eb45b556/resources/views/partials/favicons.twig#L4

Potentially splitting the manifest link tag into a separate partial and including it in the PWA template also (https://github.com/firefly-iii/firefly-iii/blob/ec59f80fe3c18d408382e4916dec9d95eb45b556/resources/views/pwa.twig)? or further down the chain in the system itself...

### Debug information

Present up to and including v6.1.7

### Expected behaviour

PWA manifest to be presented with all pages, including login and dashboard.

**Comment by JC5** [comment]
The webmanifest is present on the dashboard. This is easy to verify on the demo site. What makes you think it isn't?

The fact that it's not present on the login and register pages is correct, and that's easily fixable.

**Comment by absentbri** [comment]
Thanks for the prompt reply @JC5 

The Demo site appears to be on the V1 dashboard, not the V2 one... this is why, I expect, it's not aligned with my V2 findings.
While I understand V2 is a WIP, this is, I feel a valid point to raise (early)

**Comment by absentbri** [comment]
This is a screenshot of the network loaded assets on the v2 dashboard on my instance, for context
<img width="874" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/16235510/e205c757-e715-4437-bc2e-50b005c09ee0">
