### ISSUE TITLE
Piggy bank "saved so far" incorrect

### ISSUE THREAD

**Issue by rmu1987** [firefly-iii/firefly-iii#8456]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Im using piggy banks and running FireflyIII version 6.1.7 in Docker.

I just removed money from my Piggy bank called "Reizen 2024", this piggy bank is never used before to withdraw money from.
- The piggy bank started with 5000
- I just removed 192,95
- The "saved so far" is updated to 4614,10 (so it seems Firefly removed the amount 2 times)
- The graph is displaying 4807,05, this is the correct amount (like: 5000-192,95=4807,05)
![Screenshot 2024-01-25 at 10 20 20](https://github.com/firefly-iii/firefly-iii/assets/68034778/29752e0d-25b5-4ed8-873a-807ab2bee09e)

Other information like the "Event history" does not show this, it is displaying one transaction. When i click the transaction:
![Screenshot 2024-01-25 at 10 24 04](https://github.com/firefly-iii/firefly-iii/assets/68034778/19164177-670a-4702-bbf0-dac6996f69b2)

Unfortunatly the debug logging was Off when i did the withdrawal.
I had this issue before with another piggy bank (Reizen 2023) which is removed when 2024 started. See #8167

### Debug information

Debug information generated at 2024-01-25 10:26:14 for Firefly III version **v6.1.7**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.7 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>933, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Amsterdam</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>debug, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-01-25 00:00:00 (10 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0</td></tr></tbody></table>

### Expected behaviour

I expect the amount displayed in the graph (4807,05) to be visible as "saved so far".

**Comment by JC5** [comment]
Weird!

Like last time, the chart is always _secondary_ to the piggy bank. The amount "saved so far" is correct. Even when it's wrong. But it's a clue to what's happening, so thanks! I'll try to replicate the issue.

**Comment by JC5** [comment]
Sorry, I can't seem to replicate this. Without (debug) logs there's not much more I can do I'm afraid.

**Comment by JC5** [comment]
james@firefly-iii.org 👍

**Comment by JC5** [comment]
I can only replicate this when I:

- Select a piggy bank when creating the transaction
- AND a rule also has the action to remove money from the piggy bank.

Is this what you do as well?

**Comment by JC5** [comment]
Great, problem solved. I'm not going to add a fix, I'll put a disclaimer in the documentation.

**Comment by JC5** [comment]
No I'm afraid not, but you can always add the amount manually to the piggy bank though.
