### ISSUE TITLE
Budgets - missing summary from the bottom

### ISSUE THREAD

**Issue by g7xtr** [firefly-iii/firefly-iii#8457]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I just updated to the latest version,  6.1.7 from 6.0.30. When I went to see my budget page, I was missing the summary part in the bottom of the budget page.
It looks like this in v6.0.30 with the summary:
![firefly-iii-6 0 30_edited 2024-01-25 10-03-23](https://github.com/firefly-iii/firefly-iii/assets/53793210/46ea5a2c-5536-42f7-acb5-e6d1cda46837)

In v6.1.7 there is no summary:
![firefly-iii-6 1 7_edited 2024-01-25 10-04-27](https://github.com/firefly-iii/firefly-iii/assets/53793210/3a3f7166-0149-4776-be7b-1c0a300db219)

I understand that there is a bar in the top which can be used to calculate where you are with the spending, however it was nice to have the summary in the bottom.

### Debug information

Debug information generated at 2024-01-25 10:10:00 for Firefly III version **v6.1.7**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.7 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>933, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + Europe/London</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span></td></tr><tr><td>Session start</td><td>2024-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-01-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0</td></tr></tbody></table>

### Expected behaviour

I would like to have back the summary in the bottom of the page as it was in v6.0.30:
![firefly-iii-6 0 30_edited 2024-01-25 10-03-23](https://github.com/firefly-iii/firefly-iii/assets/53793210/46ea5a2c-5536-42f7-acb5-e6d1cda46837)

**Comment by JC5** [comment]
Yes that's on purpose. The top bar reflects the same info.

**Comment by g7xtr** [comment]
Would it be possible to put the difference between the "Budgeted" and "Already spent" amount up there? Really that's the only info I'm missing and I do check that quite regularly.

**Comment by JC5** [comment]
That info is in the bars, or are you talking about something else?

**Comment by g7xtr** [comment]
I'm talking about the **difference** between the budget and the Already spent amount.
So I would like to see that my budget is £100, I spent £90, so the difference is £10.

Something similar to this:
![Desired-outcome 2024-01-27 16-57-11](https://github.com/firefly-iii/firefly-iii/assets/53793210/160f3011-80dc-4bba-9e6a-d79592661975)

**Comment by JC5** [comment]
Ah yes, I'll see what I can do.
