### ISSUE TITLE
Show balance in category totals

### ISSUE THREAD

**Issue by mzeising** [firefly-iii/firefly-iii#8461]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

- the dashboard shows a bar graph with the sums of all categories
- it only sums the expenses and earnings are ignored
- this is annoying and misleading

### Solution

- the dashboard should show the balance of the categories

**Comment by JC5** [comment]
Yes, I know. I don't really miss it.

I'll write it down for the new layout. 

https://github.com/firefly-iii/firefly-iii/issues/6299
