### ISSUE TITLE
Visually indicate transaction input source type (manual vs automated recurring vs imported)

### ISSUE THREAD

**Issue by ekroyman** [firefly-iii/firefly-iii#8465]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I can't easily tell where I left off to enter manual transactions. It has become worse since automating as many of those transactions as possible. I used to be able to easily see exactly where I left off, but now with automation, I cannot tell without looking in detail at each transaction (or discovering at reconcile) and taking far too long to do so compared to when input was only manual.

### Solution

A possible solution would be a visual indicator built-in to firefly, like a small icon or row color change unique to the input type. Then, I could easily see where the manual transactions left off.

### What are alternatives?

For now I've prepended the tag (auto) to every description the auto recurring transactions have, but this seems like a hack.

### Additional context

Thank you for this software and your consideration of this enhancement.

**Comment by JC5** [comment]
It will not be possible to add a visual indicator, but I hope that custom fields will make it easier in the future to add such an indicator.

https://github.com/firefly-iii/firefly-iii/issues/7007
