### ISSUE TITLE
Allow to look at data imported from the API before importing it

### ISSUE THREAD

**Issue by rchl** [firefly-iii/firefly-iii#8466]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'm wondering whether it's possible to use index-based duplicate detection logic when importing from GoCardless. There doesn't seem to be any way to look at the data received from the API (or the one that Importer ends up converting it to).

### Solution

During the import, provide at some point a way to look at or download the data received from the API so that it would be possible to make informed decision about which de-duplication method to use.

Or possibly auto-select the best value based on the fact that it's known that it's a GoCardless import and don't even give an option to change it.

### What are alternatives?

Research GoCardless API manually to figure out what data is being sent. Though I'm not sure that would help because Importer seems to have a step that converts the data to a different format before importing.

**Comment by rchl** [comment]
This should have been reported in the importer repo...

**Comment by JC5** [comment]
What problem would this solve?

**Comment by rchl** [comment]
In the past I've ended up with duplicate transactions when importing data from GoCardless and I believe it was due to content-based de-duplication not handling some cases where transaction is initially reported with a different name (maybe even different value) but some days later changing, once the transaction has been completed.

I wonder if that's something that would be solved by using index-based de-duplication.

**Comment by JC5** [comment]
That depends. If the identifier doesn't change. Otherwise, no.

**Comment by rchl** [comment]
That's why I'm asking to be able to look at the data to make an informed decision.

Or if the API makes some guarantees about that (but I assume it rather depends on the bank) then I'm suggesting to not even expose the option to choose de-duplication method.

**Comment by JC5** [comment]
No sorry, that's too much work and maintenance for this future.

>  (but I assume it rather depends on the bank)

This is the problem, I'm afraid.

**Comment by rchl** [comment]
What about the other suggestion where I've mentioned that the importer could expose raw data after it was converted to importable format. I guess it would be in this step:

![Screenshot 2024-01-31 at 22 48 08](https://github.com/firefly-iii/firefly-iii/assets/153197/78e9491f-62f2-498d-b353-2826810cba57)

Though... that step is after the de-duplication options are chosen so not sure if the converted content depends on that...

**Comment by JC5** [comment]
No, sorry.
