### ISSUE TITLE
Repeat interest statistics

### ISSUE THREAD

**Issue by PterX** [firefly-iii/firefly-iii#8474]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The current interest expense is stored as a disbursement from the loan to the expenditure account. This will cause the interest to be included twice when the disbursements are counted.

### Debug information

The current interest expense is stored as a disbursement from the loan to the expenditure account. This will cause the interest to be included twice when the disbursements are counted.

**Comment by JC5** [comment]
I'm not sure I understand what you mean.
