### ISSUE TITLE
Search: clicking on the search-icon renders error page

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#848]
How to reproduce

1. do not type anything in the search form (left nav-bar)
2. click on the magnifying glass / search icon

Error:

> Whoops! An error occurred.
> Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> 
> Type error: Argument 1 passed to FireflyIII\Support\Search\Search::parseQuery() must be of the type string, null given, called in /var/www/firefly-iii/app/Http/Controllers/SearchController.php on line 57
> 
> More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.
> 
> If you cannot find the cause of this error or when you need some help, please open a ticket on Github.

**Comment by JC5** [comment]
Nice. Found and fixed!

**Comment by JC5** [comment]
Closed to clean the list of issues.
