### ISSUE TITLE
Automatic categorizing

### ISSUE THREAD

**Issue by Se7enair** [firefly-iii/firefly-iii#8480]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

To automate the categorisation of transactions I have to builde rules. Many categories, many rules. To much for my taste ;)

### Solution

Ad a auto categorize feature with keywords.
Every category contains some keywords. If one of them is found e.g. in the description or recipient, the category is added to the transaction.

There must be a check, that every keyword is contained in only one category.

### What are alternatives?

I know, I can add rules for that. But I need one role for every category. And inside one line per keyword for every data field. So if I use five keywords, this doubles to 10 entries per rule and then per category. With 20 categories....

Another solution could be a extension to rules. So that I can add more then one entry for eg. descriptions contains.
description: keyword1, keyword 2, keyword 3,...
recipient: recipient 1, recipient 2, ...

**Comment by JC5** [comment]
Sorry no, this is a problem you must solve yourself. For example, by using a webhook.

**Comment by Se7enair** [comment]
How can I use a webhook for that? Or do you mean I have to Build my own App and implement it via webhook?

**Comment by JC5** [comment]
The latter, yes. You could write something in Python, php, whatever you need and process your tags and transactions that way. Or, alternatively, use the API and talk to Firefly III directly.
