### ISSUE TITLE
Transaction table has problem with long words

### ISSUE THREAD

**Issue by Se7enair** [firefly-iii/firefly-iii#8484]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have a issue with long words in description on the transaction table. Maybe also in other tables?
I think this happens as soon as there are to many characters, where to many depends on the screen size.

Maybe there is a possibility to make a new line as soon as there are to many characters. I know it’s difficult to determine how many are to many.
Or limit how many characters are shown.

### Debug information

<img width="820" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/1680106/2241f7d4-ac21-445b-bf9e-dfe1c4575426">

### Expected behaviour

Table should show in total 

### Steps to reproduce

1. make transaction with a few long words in the description
2. Go to transaction table

### Additional info

Screenshot is from demo

**Comment by JC5** [comment]
I don't really care, to be honest.

**Comment by Se7enair** [comment]
It is not. When I import transactions from my bank, they are as long as this.

<img width="1180" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/1680106/cfbabf71-6822-4406-8311-6fb7c440baf1">

If there is a way to get rid of this, without manually edit every description, I am also fine with that.
I need support here, and would be happy if someone can assist me or fix this for everyone. Thank you!

**Comment by JC5** [comment]
I have something in mind for this for the new layout, but I won't be able to fix this one, sorry.

**Comment by xzaz** [comment]
I'v noticed the same; but it is a core issue at the payment provider OR the bank. Just give a normal description instead of some weird payment ID in the description field. Specially online payments have these.
