### ISSUE TITLE
Drawing from the account which has been used for Piggy banks

### ISSUE THREAD

**Issue by jjussif77** [firefly-iii/firefly-iii#8485]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Im using one account only for the piggy panks. All my salary is arriving there. 
In the beginning of any month im doing takeout from the "piggy" account. 
No i can see different amounts on the Dashboard and Piggy banks.
In the past they have been the same.
![Dasboard](https://github.com/firefly-iii/firefly-iii/assets/114191383/14f1a40d-eb47-4622-ab77-053b50056ca4)
![Piggy](https://github.com/firefly-iii/firefly-iii/assets/114191383/d690e832-ea49-4381-97e3-d8d1fb561269)

### Debug information

I would add debug information if i knows where to find it. 
I can provide them if someone can show me how. 
Application version is 6.1.7

**Comment by jjussif77** [comment]
Hello!
Im sorry, issue fixed itself and i made a panic without any need. 
Today i wanted to take out the debug information and noticed that the software has corrected the amount in the piggy banks.
Sorry again!

**Comment by jjussif77** [comment]
Hello!
Im sorry, issue fixed itself and i made a panic without any need.
Today i wanted to take out the debug information and noticed that the software has corrected the amount in the piggy banks.
Sorry again!

**Comment by JC5** [comment]
Not a problem, thanks for letting me know!
