### ISSUE TITLE
CSV Data Importer does not automap IBAN numbers to existing asset accounts

### ISSUE THREAD

**Issue by dawid-czarnecki** [firefly-iii/firefly-iii#8486]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm trying to import a bank transfer between two asset accounts. The source account is not specified in the column so should be the default one. When I select the "do not map / automap" the transaction is imported as a withdrawal.
After restoring database from the last backup, reimporting again with manual mapping, the transaction is correctly imported as a transfer.

### Debug information

Sample CSV file with sanitized IBAN number and transaction ID:
```csv
Data transakcji;Data księgowania;Dane kontrahenta;Tytuł;Nr rachunku;Nazwa banku;Szczegóły;Nr transakcji;Kwota transakcji (waluta rachunku);Waluta;Kwota blokady/zwolnienie blokady;Waluta;Saldo po transakcji;Waluta
2024-01-20;2024-01-20; Dawid Czarnecki ; Przelew;PL82********************3825 ;Bank name X; ;123456789012345678;-300;PLN;;;1.11;PLN
```

Not working configuration file:
```json
{
    "version": 3,
    "source": "ff3-importer-1.4.2",
    "created_at": "2024-02-01T10:01:06+01:00",
    "date": "Y-m-d",
    "default_account": 1,
    "delimiter": "semicolon",
    "headers": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "roles": [
        "date_transaction",
        "date_book",
        "opposing-name",
        "description",
        "opposing-number",
        "_ignore",
        "_ignore",
        "external-id",
        "amount",
        "currency-code",
        "_ignore",
        "_ignore",
        "_ignore",
        "_ignore"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": [],
    "duplicate_detection_method": "cell",
    "ignore_duplicate_lines": true,
    "unique_column_index": 7,
    "unique_column_type": "external-id",
    "flow": "file",
    "content_type": "csv",
    "custom_tag": "",
    "identifier": "0",
    "connection": "0",
    "ignore_spectre_categories": false,
    "grouped_transaction_handling": "",
    "use_entire_opposing_address": false,
    "map_all_data": true,
    "accounts": [],
    "date_range": "",
    "date_range_number": 30,
    "date_range_unit": "d",
    "date_not_before": "",
    "date_not_after": "",
    "nordigen_country": "",
    "nordigen_bank": "",
    "nordigen_requisitions": [],
    "nordigen_max_days": "90",
    "conversion": true,
    "ignore_duplicate_transactions": false
}
```

Existing asset account:
![asset-account](https://github.com/firefly-iii/firefly-iii/assets/17339154/7041928b-0cf6-480b-abd2-b11c0879def6)

Automap import:
![automap](https://github.com/firefly-iii/firefly-iii/assets/17339154/2fab9e8e-86f9-4d39-8d17-f86e88ac0f8e)

Withdrawal created:
![withdrawal-created](https://github.com/firefly-iii/firefly-iii/assets/17339154/8db585e3-68e7-403e-9b43-76866ec9e85b)

Withdrawal transaction created:
![withdrawal-transaction](https://github.com/firefly-iii/firefly-iii/assets/17339154/1801b907-85b9-4574-a031-5a4447f87178)

Expense account created:
![expense-account](https://github.com/firefly-iii/firefly-iii/assets/17339154/bcbd41c5-e778-4416-956d-7ca42a11e899)

---
Here are the details of the manual IBAN mapping and correct transfer import.
Working configuration file:
```json
{
    "version": 3,
    "source": "ff3-importer-1.4.2",
    "created_at": "2024-02-01T10:04:51+01:00",
    "date": "Y-m-d",
    "default_account": 1,
    "delimiter": "semicolon",
    "headers": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "roles": [
        "date_transaction",
        "date_book",
        "opposing-name",
        "description",
        "opposing-number",
        "_ignore",
        "_ignore",
        "external-id",
        "amount",
        "currency-code",
        "_ignore",
        "_ignore",
        "_ignore",
        "_ignore"
    ],
    "do_mapping": [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ],
    "mapping": {
        "4": {
            "PL82291000060000000001863825": 19
        }
    },
    "duplicate_detection_method": "cell",
    "ignore_duplicate_lines": true,
    "unique_column_index": 7,
    "unique_column_type": "external-id",
    "flow": "file",
    "content_type": "csv",
    "custom_tag": "",
    "identifier": "0",
    "connection": "0",
    "ignore_spectre_categories": false,
    "grouped_transaction_handling": "",
    "use_entire_opposing_address": false,
    "map_all_data": true,
    "accounts": [],
    "date_range": "",
    "date_range_number": 30,
    "date_range_unit": "d",
    "date_not_before": "",
    "date_not_after": "",
    "nordigen_country": "",
    "nordigen_bank": "",
    "nordigen_requisitions": [],
    "nordigen_max_days": "90",
    "conversion": true,
    "ignore_duplicate_transactions": false
}
```

Manual mapping:
![manual-mapping](https://github.com/firefly-iii/firefly-iii/assets/17339154/52c71b96-92b8-471f-a25a-74d8f8952059)

Transfer created:
![transfer-created](https://github.com/firefly-iii/firefly-iii/assets/17339154/b84835c3-e965-47d1-be90-3d5e957bd9df)

### Expected behaviour

Transaction imported as a transfer.

### Steps to reproduce

1. Replace `*` characters in the sample CSV with 20 digits
2. Create asset account with the IBAN number from the CSV file
3. Load the CSV file and the "not working configuration file" to the Data Importer
4. Click next/submit on the rest of the import stages.

### Additional info

Firefly version: 6.1.7
Data Importer version: 1.4.2

This issue seem to be identical to this one: https://github.com/firefly-iii/firefly-iii/issues/3317
I couldn't comment there so I'm creating a new one.

**Comment by JC5** [comment]
It looks like you're using "Opposing account (account number)" but you should be using "Opposing account (IBAN)".

**Comment by dawid-czarnecki** [comment]
You are absolutely right. Thanks for spotting the error on my side!
I selected account number instead of IBAN because some account numbers are not IBAN in that bank export.
