### ISSUE TITLE
Search: enable bulk edit results

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#849]
After importing about 1000 entries, although, I did my best preparing the imports, there are still some transfers I'd like renamed, re-arranged.

Right now, the only possibility is by month, or by category/tag (if provided during the import), revenue/expense account. A neat feature would be to allow users to bulk change search results, the basics, description, accounts, categories, tags, etc

**Comment by JC5** [comment]
That requires some custom javascript to get the correct URI but it's certainly possible!

**Comment by JC5** [comment]
First version is committed.
