### ISSUE TITLE
Support setting custom date range in preferences

### ISSUE THREAD

**Issue by limpep** [firefly-iii/firefly-iii#8498]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Currently, in preferences ⇾ view range, you can only select predefined data range. 

### Solution

Allow users to set a custom date range instead within perferences.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/explanation/more-information/what-its-not/#changing-the-monthly-cycle-to-another-day-of-the-month

**Comment by limpep** [comment]
> You can't tell Firefly III to go from the 23rd to the 22nd of the next month.

Why? We get a month starts on the 1st, but this is why we are asking for a custom range

Hence, why I created this feature request
