### ISSUE TITLE
Wrong version number after update to v6.1.8

### ISSUE THREAD

**Issue by memo-567** [firefly-iii/firefly-iii#8499]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Updating v6.1.7 to v6.1.8 does not update the version number

### Debug information

`Creating a "grumpydictator/firefly-iii" project at "./firefly-iii-updated"`
`Installing grumpydictator/firefly-iii (v6.1.8)`

No errors.
![20240203-1750](https://github.com/firefly-iii/firefly-iii/assets/58190287/baace3ac-73ea-4da1-a075-4b528c825a14)

**Comment by prbt2016** [comment]
Hello ,

Getting same issue while installing 6.1.8, it shows 6.1.7 . 

Any ETA for 6.1.9?.

Regards.
