### ISSUE TITLE
Tutorials still appearing

### ISSUE THREAD

**Issue by viktorjamrich** [firefly-iii/firefly-iii#850]
The tutorials are still appearing on some pages,
even though I've gone through them to the end.

Not sure, but may have something to do with the encryption -
I've turned off the encryption in the config after most of my data have already been imported.

version 4.6.3.1

**Comment by JC5** [comment]
Yes, incidentally they'll pop up again. But I must admit, I havent run into this in the latest version. At the time of writing, its 4.6.5
