### ISSUE TITLE
Bulk delete page links to wrong tx

### ISSUE THREAD

**Issue by likuilin** [firefly-iii/firefly-iii#8501]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

On the bulk delete confirmation page, the transaction descriptions link to the wrong transaction

### Debug information

Reproducible on demo

### Expected behaviour

The tx description links to the right transaction

### Steps to reproduce

1. Go to https://demo.firefly-iii.org/accounts/show/1
2. Check checkboxes next to three ordinary transactions
3. Actions -> Delete selected (3)
4. Click on a description
5. Notice it is the wrong transaction or 404

### Additional info

The URL is generated using the `transaction_journals` id instead of `transaction_groups` id :)

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by likuilin** [comment]
Can confirm the above commit fixes it on my pinned version, feel free to cherry-pick it. Let me know if you want a PR with it rebased to your develop.

**Comment by JC5** [comment]
Nice work, merged!
