### ISSUE TITLE
Change color of Bills between expected or not 

### ISSUE THREAD

**Issue by deadly667** [firefly-iii/firefly-iii#8503]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

It will be good to have different color for Bills which are "Expected" and "Not expected this period". I saw that there where already issue for that and it was "fixed". Situation are the same in the light and dark mode.

In case that it's only me then for record I'm using latest Google Chrome on Ubuntu OS. 

![image](https://github.com/firefly-iii/firefly-iii/assets/20419998/184eede9-59ad-4685-895a-e9ec5ccfbdc4)

### Solution

Different color for Bills which are "Expected" and "Not expected this period".

**Comment by JC5** [comment]
Good idea. Something to pick up in the new layout, I think.

https://github.com/firefly-iii/firefly-iii/issues/6306
