### ISSUE TITLE
Wrong Version Supported

### ISSUE THREAD

**Issue by paulcalabro** [firefly-iii/firefly-iii#8506]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I think the version number wasn't bumped for `6.1.8`.
I've confirmed I'm running the correct image for my container:

```
                "org.opencontainers.image.authors": "James Cole <james@firefly-iii.org>",
                "org.opencontainers.image.base.name": "docker.io/fireflyiii/base:apache-8.3",
                "org.opencontainers.image.created": "2024-02-03T19:19:20+01:00",
                "org.opencontainers.image.description": "Firefly III - personal finance manager",
                "org.opencontainers.image.documentation": "https://docs.firefly-iii.org/",
                "org.opencontainers.image.licenses": "AGPL-3.0-or-later",
                "org.opencontainers.image.revision": "eb2bb6bab45623f78001ba344aa720e0cc38518c",
                "org.opencontainers.image.source": "https://dev.azure.com/Firefly-III/_git/MainImage",
                "org.opencontainers.image.title": "Firefly III",
                "org.opencontainers.image.url": "https://github.com/firefly-iii/docker",
                "org.opencontainers.image.vendor": "James Cole <james@firefly-iii.org>",
                "org.opencontainers.image.version": "v6.1.8",
```

The app still report version `6.1.7`.

### Debug information

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.7 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>951, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Phoenix + America/Phoenix</td></tr><tr><td>App environment</td><td>local, debug: true</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>172.22.0.0/16</td></tr><tr><td>Login provider & user guard</td><td>eloquent / remote_user_guard</td></tr><tr><td>Login headers</td><td>Remote-Email + </td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-01-28 00:00:00</td></tr><tr><td>Session end</td><td>2024-02-04 23:59:59</td></tr><tr><td>View range</td><td>last7</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0</td></tr></tbody></table>

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/8499

**Comment by paulcalabro** [comment]
Ahh, sorry missed that because it had a "v" in front. Didn't return any results for "6.1.8".
