### ISSUE TITLE
Import immediately timed out

### ISSUE THREAD

**Issue by viktorjamrich** [firefly-iii/firefly-iii#851]
I've imported my data from a CSV file.

Everything went fine, including the mapping until the end of the import,
where I could either continue or copy & paste the command directly to the server.

When chosen to continue normally, an error with Timeout message appeared **immediately**.

When copied & pasted the command a ran it on the server, everything went fine and import was successful.

version 4.6.3.1

**Comment by JC5** [comment]
The error could be in the logs, but I advise you to install or upgrade the latest version.
