### ISSUE TITLE
Archive inactive bills instead of keep them with active ones

### ISSUE THREAD

**Issue by fnouira** [firefly-iii/firefly-iii#8512]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hello,
The bills handeling is really great. 
As of today, I do not delete expired bills but I deactivate them instead.
This have many benefits like:
- Keeping the bills history
- I could get back to an old bill to duplicate it manually (get inspired of what I did before) - duplicate a bill feature will also be welcome :)
- If I update a transaction related to a deleted bill, I will have errors (no errors if the bill is deactivated).

After a long time doing this, I got a long page with all of the bills together and it's really heavy to find active onces.

### Solution

Like what's  done on passive accounts page, it will better to put inactive bills on a separate page like archive with a little link on the bottom of page to load (or navigate) those bills.

### What are alternatives?

Today, I have no alternatives. I use "Ctrl + F" to find the bill I want.

**Comment by JC5** [comment]
I group them in a group "inactive", and put that at the bottom.

**Comment by fnouira** [comment]
Seems to be a good alternative
