### ISSUE TITLE
Gocardless Import: additionalInformation saved into Notes

### ISSUE THREAD

**Issue by shrippen** [firefly-iii/firefly-iii#8518]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like the importer to save data provided in "additionalInformation" by GocardLess to be saved into the Notes field of the transaction.

### Solution

Copy content of field "additionalInformation" to notes

**Comment by JC5** [comment]
Is already in place.

**Comment by shrippen** [comment]
Correct, sorry.
