### ISSUE TITLE
Edit account actually deactivates it

### ISSUE THREAD

**Issue by viktorjamrich** [firefly-iii/firefly-iii#852]
When editing an account, changing some options and then hitting the green "Update asset/expense/... account" button, the changes are saved but **Active** is set to false regardless whether the Active checkbox is checked or not. The account becomes deactivated.

I had to go directly to the database and set the account's Active field to 1.

version 4.6.3.1

**Comment by JC5** [comment]
Thanks for reporting this! It's fixed in the current version, and I advise you to upgrade.
