### ISSUE TITLE
Split Transaction Withdrawal different source accounts

### ISSUE THREAD

**Issue by pogora** [firefly-iii/firefly-iii#8520]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Currently when creating a split withdrawal it is only possible to add different Destination accounts. (Not sure what the practical use case is for this).
It is NOT possible to have a different source account. This is a rather common case imo. i.e. Paying for something in part in cash and in part from checking / credit card account, ...

### Solution

If the transaction type is Withdrawal then allow different source accounts. 
The ability to edit the destination account isn't really necessary imo. (Have yet to come across a case where I pay with my Card to 2 different companies at the same time). So this could be locked instead?

### What are alternatives?

If there are ways around this I'd be happy to use them instead. But thus far I have not been able to find a solution. Especially when there are Gift Cards involved.

**Comment by JC5** [comment]
Hi!

You can read more about [split transactions](https://docs.firefly-iii.org/explanation/financial-concepts/transactions/#what-are-split-transactions) in the documentation. Split transactions as you suggest them, will not be added to Firefly III. You will have to make two transactions instead.
