### ISSUE TITLE
Total buget bar is missing when using SQLite

### ISSUE THREAD

**Issue by matlink** [firefly-iii/firefly-iii#8521]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
  - found https://github.com/firefly-iii/firefly-iii/issues/7920 but looks like it does not solve the issue
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The total budget bar is missing at the top of the budget page

### Debug information

![Screenshot 2024-02-05 at 20-49-45 Budgets » Firefly III](https://github.com/firefly-iii/firefly-iii/assets/4450078/20c78d06-969e-4e66-a193-074c46fb54a8)

Version 6.1.7. I've tried 6.1.9 in a fresh docker environment and it's the same.

Debug information generated at 2024-02-06 14:16:03 for Firefly III version **v6.1.7**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.1.7 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.1 / fpm-fcgi / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*sqlite*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Paris + Europe/Paris</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>fr_FR + equal</td></tr><tr><td>Trusted proxies</td><td>*</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-02-06 04:00:13 (10 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td></td></tr><tr><td>Session end</td><td></td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>fr_FR</td></tr><tr><td>User locale</td><td>fr_FR</td></tr><tr><td>Locale(s) supported</td><td>fr_FR.utf8: :white_check_mark:<br>fr_FR.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0</td></tr></tbody></table>

### Additional info
- self-hosted
- alpine linux & firefox

**Comment by matlink** [comment]
@JC5 I've updated the debug informations

**Comment by JC5** [comment]
I can't replicate this, sorry. The bar appears just fine.

What happens when you change the budget you have to 175 and then back to 150?

**Comment by matlink** [comment]
I see the available amount refreshing but still being 0.
A weird thing when I see the tutorial is it tells me to set the total budget amount but I see nowhere to set it : 
![Screenshot 2024-02-06 at 21-39-37 Budgets » Firefly III](https://github.com/firefly-iii/firefly-iii/assets/4450078/fb53dfea-deb0-472b-bbb3-08d734c8ca53)

**Comment by JC5** [comment]
Mmm, it's something SQLite specific, I think I can replicate it now. I'll pick it up from here, thanks!

**Comment by matlink** [comment]
Thank you! I'll try in the next release!
