### ISSUE TITLE
Can't edit transaction in mass-edit mode

### ISSUE THREAD

**Issue by mcardielo** [firefly-iii/firefly-iii#8525]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I select some transactions and try to update them in the mass-edit function, an "enter valid value" error message appears in the date field, the transactions can be updated after I select a new date or time.

### Debug information

Debug information generated at 2024-02-06 10:21:07 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>957, base <span>#</span>40</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Mexico_City + America/Mexico_City</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + en_US</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-02-06 00:00:00 (10 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has reconciled">:ledger:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-01-07 10:08:58</td></tr><tr><td>Session end</td><td>2024-02-06 10:08:58</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15</td></tr></tbody></table>

### Expected behaviour

The mass-edit for the transactions should work without the need to update the date field.

### Steps to reproduce

1. select two or more transaction
2. select the mass-edit option
3. update the category field
4. apply the changes

**Comment by JC5** [comment]
I can't replicate this, it works fine.

**Comment by mcardielo** [comment]
I @JC5 , I checked and this happends only for the transactions created using the API.

**Comment by JC5** [comment]
All transactions are created using the API. Could you elaborate a little bit?

**Comment by mcardielo** [comment]
You are right, sorry, I mean that this affects the transactions created via API out of the Web UI

Here is the audit log from a transaction created with the Web UI
```
2024/02/06 12:33:51,stdout,"[2024-02-06 12:33:51] local.INFO: AUDIT: Store new transaction over API. (172.17.0.1 (m*@c*.com) -> POST:http://192.168.100.5:8082/api/v1/transactions) {"group_title":"","error_if_duplicate_hash":false,"apply_rules":true,"fire_webhooks":true,"transactions":[{"type":"withdrawal","date":"2024-02-06 12:33:00","order":null,"currency_id":null,"currency_code":"","foreign_currency_id":null,"foreign_currency_code":"","amount":"1","foreign_amount":"","description":"test ff","source_id":27,"source_name":"Efectivo","source_iban":"","source_number":"","source_bic":"","destination_id":4,"destination_name":"","destination_iban":"","destination_number":"","destination_bic":"","budget_id":null,"budget_name":"","category_id":null,"category_name":"","bill_id":null,"bill_name":"","piggy_bank_id":null,"piggy_bank_name":"","reconciled":false,"notes":"","tags":null,"internal_reference":"","external_id":"","original_source":"ff3-v6.1.9|api-v2.0.12","recurrence_id":null,"bunq_payment_id":"","external_url":"","sepa_cc":"","sepa_ct_op":"","sepa_ct_id":"","sepa_db":"","sepa_country":"","sepa_ep":"","sepa_ci":"","sepa_batch_id":"","interest_date":null,"book_date":null,"process_date":null,"due_date":null,"payment_date":null,"invoice_date":null}],"user":1} "
```

And here is the audit log from a transaction created not using the Web UI
```
2024/02/06 12:33:43,stdout,"[2024-02-06 12:33:43] local.INFO: AUDIT: Store new transaction over API. (192.168.100.5 (m*@c*.com) -> POST:http://192.168.100.5:8082/api/v1/transactions) {"group_title":"","error_if_duplicate_hash":false,"apply_rules":true,"fire_webhooks":true,"transactions":[{"type":"withdrawal","date":"2024-02-06 12:33:36","order":null,"currency_id":null,"currency_code":"","foreign_currency_id":null,"foreign_currency_code":"","amount":"1","foreign_amount":"","description":"test","source_id":null,"source_name":"Efectivo","source_iban":"","source_number":"","source_bic":"","destination_id":null,"destination_name":"Amazon","destination_iban":"","destination_number":"","destination_bic":"","budget_id":null,"budget_name":"","category_id":null,"category_name":"","bill_id":null,"bill_name":"","piggy_bank_id":null,"piggy_bank_name":"","reconciled":false,"notes":"","tags":null,"internal_reference":"","external_id":"","original_source":"ff3-v6.1.9|api-v2.0.12","recurrence_id":null,"bunq_payment_id":"","external_url":"","sepa_cc":"","sepa_ct_op":"","sepa_ct_id":"","sepa_db":"","sepa_country":"","sepa_ep":"","sepa_ci":"","sepa_batch_id":"","interest_date":null,"book_date":null,"process_date":null,"due_date":null,"payment_date":null,"invoice_date":null}],"user":1} "
```

There are differences on the audit log, however both transactions were correctly created in the firefly instance.

**Comment by JC5** [comment]
Mmm, that's weird. There seems to be not that many differences between the two. And the only field that seems relevant, is formatted the same. The date, see?

<img width="1329" alt="Screenshot 2024-02-06 at 20 16 00" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/fb3911f2-4fbd-4afd-b211-f62f6966cb16">


1. Could you get a screenshot of the error?
2. What browser/OS are you on?

**Comment by mcardielo** [comment]
I'm using Safari on iPad

<img width="1373" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/842262/b2c206db-f979-4531-80c6-05b89b5b3270">

**Comment by JC5** [comment]
Can you replicate this on the demo site? Because I can't, unfortunately.

**Comment by mcardielo** [comment]
I'm trying to create the transaction with the API but I get a 403 http response

this is the API request:

```bash
curl -X 'POST' 'https://demo.firefly-iii.org/api/v1/transactions' -H 'accept: application/vnd.api+json' -H 'Content-Type: application/json' -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiYWNhMWVlZDc1OTM2ODI5YzQ2NTBjYTEyNmQ0MDQ5YThjMDRjOGEwNzUwMjIzNzE4NWRhYTFiYjgxYTllODdlMjhjM2Q4NzlmZTlhNTVmMTIiLCJpYXQiOjE3MDczMTk5ODYuNzk1NjY4LCJuYmYiOjE3MDczMTk5ODYuNzk1NjcxLCJleHAiOjE3Mzg5NDIzODYuMzUwODk4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.CFNvmHuTXTtoApVqmcrAKBACEOb_gYasjCJtUmSH-RRPxsjeeygSwPkD20GVWk5k-Q5-wgkBe3TbnZtt705EwFVtR1_DjZ8ajNAaDkLthzHGityoaspgAcgaNn6vhTh_zV25sYKeL9x-GQHX7cNk5EtGLye72psdqsnnMZtapX2ugA1COOLZeb6XTGy6ic_KghbGbloKHLs1MklyLU7gOlW_0-McQUZoQX8yUQNMW4meFyIadjnWmXi62w-xLGmB94Eu_B9bJsp5u6X_CCXzfH8mLXaXMEuDNLlLFiNuV_Cdp5NLWr7TV92nezwQqETceM9vKRG1Ksj7vqT4e_q6cUv8x3Sbhct_xRgpaDvMNvhJ_DLONWpmOKsMDmKC19ot_6qO3h6DwPAGa85uTGc7kqDPpQWBb3QNc59rjSOl7xDhiFzRSFAO0dSasgroKeGTIq_laM2Zjc1HxwgfgoeOKhr7ew4RI0szVLDgYne2YScdiaRX1u3VWbhQRnZajafHp3i9B7Oh0ZyplS9ayMa5_HbYZZbpyLAV_h8vF1rF2uLMbz1ICVp5L5myn4JoR-xCafbMyu5bhlkLC_0tBd9DnfQ4TmMI3YkJCXzt6PBJmLlpfo7Bo1lxKke2fRySOtfekJlXB4t1kTfDSS3wqsMYcUiN-EIQSTrsRFDhgYCHcmU' -d '{"error_if_duplicate_hash":false,"apply_rules":true,"transactions" [{"type":"withdrawal","date":"2024-02-07T09:25:46-05:00","amount":"1","description":"test api not web","destination_name":"amazon","source_name":"Cash Wallet"}]}'
```

**Comment by JC5** [comment]
Use a different user agent. The curl agent is blocked because of spam. Use "-A".
