### ISSUE TITLE
Rules: "See matching transactions" shows less than it actually finds

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#853]
As discussed in #846, I tried to bulk rename some transactions and stumbled upon rules (awesome feature btw!)

How to reproduce:

1. Create a rule
2. Set trigger
3. Click "See matching transactions". It shows a modal with a few transactions
4. Set up the rest of the rule
5. Save it
6. Go to the overview and run it. It runs on a lot more of the transaction.

The trigger is correct, it matches perfectly and updates everything as expected, however, there are a few issues with the whole process

1. Translation for form.rule_group_id on the edit page is missing
2. When clicking on the "See matching transactions" there should be a "loading"-gif or something hinting that the system is running a big query and you should wait - I clicked multiple times and got multiple modals
3. After running the rule, there should be a modal or something saying "I found these transactions, are you sure you want to update them?"

other than that, you saved me from a lot of powershell scripting to do exactly what your rules were doing 👍

**Comment by JC5** [comment]
1. Will be fixed!
2. Can be fixed, but it'll have to wait, I'll keep this open.
3. I could add a modal but the list could be huge. I could add a confirmation dialog?

**Comment by gavu** [comment]
1. Awesome!
2. Great 
3. Good idea. It’s an extra step to confirm the changes

**Comment by JC5** [comment]
As far as I can tell the rules function perfectly, but I've added some logging. The demo-box will show less than there are, it warns you of this. I've added a spinner to tell you it's doing something.
