### ISSUE TITLE
Translation in Portuguese Portugal

### ISSUE THREAD

**Issue by r1bas4** [firefly-iii/firefly-iii#8530]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The error messages are not translated correctly into Portuguese.
What firefly shows: Erro! There was something wrong with your submission. Please check out the errors below.
What it should show: Erro! Algo correu mal com o envio dos dados. Por favor verifique e corrija os erros abaixo.

### Debug information

Not helpful

### Expected behaviour

What it should show: Erro! Algo correu mal com o envio dos dados. Por favor verifique e corrija os erros abaixo.

### Steps to reproduce

Get any type of error on Firefly with the language set to Portuguese (not Brazilian, actual Portuguese). I noticed it on the transactions screen, might be wrong in other places as well.

**Comment by r1bas4** [comment]
Also on the main screen (dashboard I guess?), it says DENTRO+FORA ESTE PERIODO, which means inside+outside this period. I would suggest changing it to RECEITAS+DESPESAS ESTE PERIODO

**Comment by JC5** [comment]
Translations are managed on crowdin. You can submit translations, raise issues and discuss things. 

Please visit: https://crowdin.com/project/firefly-iii/pt-PT
