### ISSUE TITLE
Can we make SEPA fields searchable to use them as rule triggers/conditions

### ISSUE THREAD

**Issue by arminreh** [firefly-iii/firefly-iii#8537]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hey,

thanks for providing a great personal finance tool.

I have interesting information stored in some of the SEPA fields and am trying to use them in a new rule.
My goal.
- If source account is "(no name") and sepa_info of some kind = "Foobar"
- Set source account to "Foobar related account"

### Solution

I am failing to make this work, because there are no search values beyond sepa_ct.
I wonder if it would be possible to extend this to also make the other sepa info fields usable in the same way?
Would you be open to me adding this in a PR and are there any pitfalls I should be aware of?

### What are alternatives?

If the feature is not there I would consider:
- storing the sepa information in the notes field instead, so it is available for these kinds of queries

### Additional context

The "first" SEPA field search functionality has been added here:  https://github.com/firefly-iii/firefly-iii/pull/6677
A potential starting place?

**Comment by JC5** [comment]
Good idea, it's on the list! No need to open a PR :)

**Comment by JC5** [comment]
Sorry, the SEPA fields are going to be dropped in a future release in favor of custom fields. As such, the information in them will be migrated automatically in due time.
