### ISSUE TITLE
FiDi: Do not send e-mail if zero transactions are found

### ISSUE THREAD

**Issue by Hoempi** [firefly-iii/firefly-iii#8539]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like the Firefly III Data Importer to not send an e-mail if the only error is `Line #1: Zero transactions found at GoCardless`

### Solution

I would like to have a new option in the config file to enable or disable the sending of e-mail if the only error is the one mentionend above.

### What are alternatives?

Currently I have to filter it in my e-mail client.

**Comment by JC5** [comment]
Sorry no, you'll have to keep filtering the mails yourself.

**Comment by Hoempi** [comment]
Okay, thanks for the quick reply, though. I just thought it would be similar to the option to not report duplicate lines to get cleaner e-mails.
