### ISSUE TITLE
new gocardless connection string, old string will be deprecated

### ISSUE THREAD

**Issue by siemdejong** [firefly-iii/firefly-iii#8541]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Today, I got an email from gocardless:

> Dear user,
> 
> We are contacting you to make sure you are using an up-to-date base_url for the GoCardless Bank Account Data API.
> This small but important change which should be easy to make for anyone in your team who has access to the production setup of your service. The new connection string should be:
> https://bankaccountdata.gocardless.com/api/v2/
> 
> The legacy URLs such as ob.nordigen.com and ob.gocardless.com will stop working on the 20th of February.

Therefore, from February 20, this will be a bug at https://github.com/firefly-iii/data-importer/blob/db12d4b6f400f4096a826952a050958084a0e9d7/config/nordigen.php#L28, I guess.

If I understand correctly, that line should change into:
```
    'url'                   => 'https://bankaccountdata.gocardless.com/api/v2/,
```

### Debug information

-

**Comment by JC5** [comment]
I got the same mail, thanks for opening an issue. I'll pick it up!

**Comment by JC5** [comment]
Fixed by @JcMinarro

**Comment by poudenes** [comment]
Got same email. :)
