### ISSUE TITLE
mariadb update crashed the firefly

### ISSUE THREAD

**Issue by fate8383** [firefly-iii/firefly-iii#8565]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Could not poll the database: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers (Connection: mysql, SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)

This error occured in file /var/www/html/app/Support/FireflyConfig.php on line 65 with code 0.

More information

Please collect more information in the storage/logs directory where you will find log files. If you're running Docker, use docker logs -f [container]. You can read more about collecting error information in [the FAQ](https://docs.firefly-iii.org/how-to/general/debug/).

Get help on GitHub

You're more than welcome to open a new issue [on GitHub](https://github.com/firefly-iii/firefly-iii/issues).

Use the search!
Include the information [from this debug page](https://firefly-rpi2.fatucloud.gosprout.org:1081/debug).
Tell us more than "it says Whoops!"
Include error logs (see above).
Tell us what you were doing.

### Debug information

Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Could not poll the database: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers (Connection: mysql, SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)

This error occured in file /var/www/html/app/Support/FireflyConfig.php on line 65 with code 0.

More information

Please collect more information in the storage/logs directory where you will find log files. If you're running Docker, use docker logs -f [container]. You can read more about collecting error information in [the FAQ](https://docs.firefly-iii.org/how-to/general/debug/).

Get help on GitHub

You're more than welcome to open a new issue [on GitHub](https://github.com/firefly-iii/firefly-iii/issues).

Use the search!
Include the information [from this debug page](https://firefly-rpi2.fatucloud.gosprout.org:1081/debug).
Tell us more than "it says Whoops!"
Include error logs (see above).
Tell us what you were doing.

### Additional info

I am not sure, i tried to lower the version of MariaDB and still i am getting that error, using docker compose.

**Comment by fate8383** [comment]
firefly latest version
mariadb tried 11.3 11.3.2

**Comment by fate8383** [comment]
mariadb LTS tag worked

**Comment by JC5** [comment]
https://github.com/orgs/firefly-iii/discussions/8564
