### ISSUE TITLE
Add new transaction type Loan interest

### ISSUE THREAD

**Issue by PterX** [firefly-iii/firefly-iii#8567]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)

### Description

According to the firefly documentation I read, recording loan interest is now accomplished by recording a withdraw from the loan account to the expense account. When you check the expenditure records in this way, you will find that both interest expenditures and principal and interest expenditures are included, which will be larger than the actual expenditure amount.

### Solution

Add new transaction type interest expense

When recording interest, record an interest expense journals in the original transaction group. Interest expenses will no longer be included twice in the summary calculation.

### What are alternatives?

transaction_journals

transaction_types
> Liability interest

account_types
> Liability interest account

**Comment by JC5** [comment]
Sorry, there will not be an extra transaction type.

**Comment by PterX** [comment]
I understand that you have your considerations, but I regret the current situation.

**Comment by PterX** [comment]
> Sorry, there will not be an extra transaction type.

Please tell me how to build the front-end vue code for this project. I want to try to implement it in my branch.

**Comment by JC5** [comment]
Yes, please open a discussion for that. I shall close this with a reference to https://github.com/firefly-iii/firefly-iii/issues/6304
