### ISSUE TITLE
User modification - few errors

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#857]
1\. Changing e-mail doesn't seem to work in Options > Administration > All users > Edit. I typed new e-mail without changing anything else, got success message, but e-mail stayed the same. Should it be possible to change e-mail? If yes then there is a bug, if not maybe input should be disabled/readonly?
2. Missing translation for submit button: `firefly.update_user`
3. Missing translation for success message: `firefly.updated_user`

Other not important observarions as probably 99% of Firefly III would have single user:
4. No possibility to change e-mail other than Options > Administration > All users > Edit. For example as non-admin in Options > Profile. But I can delete account there! 😄 
5. No possibility to delete users by admin. Have to change their password, log in as them and delete account.

**Comment by JC5** [comment]
The user admin is a rarely used feature for most people, but I'll write it down and get it fixed!

**Comment by JC5** [comment]
I've implemented and fixed these things, but it's not visible on the demo site. Will be live in the next release!
