### ISSUE TITLE
Transfers to Liabilities are showing as Withdrawals

### ISSUE THREAD

**Issue by hanscl** [firefly-iii/firefly-iii#8572]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I paying back money to a liability with a transfer, as described under the "You owe money" section of the docs (https://docs.firefly-iii.org/how-to/firefly-iii/finances/liabilities/), the balance of the liability is correctly decreased, but the transaction is showing as a withdrawal, i.e. as a negative amount, just like the initial amount owed and any other increases in the debt. The transaction is showing just like it is on the source account - as a negative number with an outgoing arrow (pointing left). This has been observed in my environment and reproduced in the test environment.

![image](https://github.com/firefly-iii/firefly-iii/assets/6536978/73b9b726-ac65-4b96-b15e-85576c8ec64c)

### Debug information

The app does not generate an error, so below only shows debug-level output of what happens when creating the transfer and opening the liability account afterwards

127.0.0.1 - - [22/Feb/2024:15:07:56 +0100] "GET /health HTTP/1.1" 200 1776 "-" "Firefly III Health Checker/2.2"
192.168.178.20 - - [22/Feb/2024:15:08:00 +0100] "GET /transactions/create/transfer HTTP/1.1" 200 7626 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:01 +0100] "GET /v1/jscript/variables?ext=.js&v=6.1.9 HTTP/1.1" 200 4036 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:01 +0100] "GET /api/v1/preferences/transaction_journal_optional_fields HTTP/1.1" 200 1454 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:01 +0100] "GET /api/v1/autocomplete/budgets?limit=1337 HTTP/1.1" 200 955 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:01 +0100] "GET /api/v1/autocomplete/bills?limit=1337 HTTP/1.1" 200 1015 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:01 +0100] "GET /api/v1/currencies?page=1 HTTP/1.1" 200 9558 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:01 +0100] "GET /api/v1/autocomplete/piggy-banks-with-balance?limit=1337 HTTP/1.1" 200 955 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:04 +0100] "GET /api/v1/autocomplete/transactions?query=Test HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:04 +0100] "GET /api/v1/autocomplete/transactions?query=Test HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
127.0.0.1 - - [22/Feb/2024:15:08:06 +0100] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.56 (Debian) (internal dummy connection)"
127.0.0.1 - - [22/Feb/2024:15:08:07 +0100] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.56 (Debian) (internal dummy connection)"
192.168.178.20 - - [22/Feb/2024:15:08:06 +0100] "GET /api/v1/autocomplete/transactions?query=Test%20Tra HTTP/1.1" 200 955 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:07 +0100] "GET /api/v1/autocomplete/transactions?query=Test%20Transfer HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:08 +0100] "GET /api/v1/autocomplete/transactions?query=Test%20Transfer%20A HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:08 +0100] "GET /api/v1/autocomplete/transactions?query=Test%20Transfer%20Ass HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:09 +0100] "GET /api/v1/autocomplete/transactions?query=Test%20Transfer%20Asset%20t HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:10 +0100] "GET /api/v1/autocomplete/transactions?query=Test%20Transfer%20Asset%20top HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:10 +0100] "GET /api/v1/autocomplete/transactions?query=Test%20Transfer%20Asset%20to HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:12 +0100] "GET /api/v1/autocomplete/transactions?query=Test%20Transfer%20Asset%20to%20Liabili HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:12 +0100] "GET /api/v1/autocomplete/transactions?query=Test%20Transfer%20Asset%20to%20Liability HTTP/1.1" 200 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:12 +0100] "GET /api/v1/autocomplete/accounts?types=Asset%20account,Revenue%20account,Loan,Debt,Mortgage&query= HTTP/1.1" 200 3080 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:15 +0100] "GET /api/v1/autocomplete/accounts?types=Asset%20account,Cash%20account,Debt,Expense%20account,Initial%20balance%20account,Loan,Reconciliation%20account,Mortgage&query= HTTP/1.1" 200 4504 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
127.0.0.1 - - [22/Feb/2024:15:08:21 +0100] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.56 (Debian) (internal dummy connection)"
[2024-02-22 15:08:23] local.WARNING: Transaction type is "Opening balance", so do nothing.
192.168.178.20 - - [22/Feb/2024:15:08:22 +0100] "POST /api/v1/transactions?_token=# HTTP/1.1" 200 2714 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:23 +0100] "GET /accounts/show/7/all?transaction_group_id=34&message=created HTTP/1.1" 200 13082 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:24 +0100] "GET /v1/jscript/variables?ext=.js&v=6.1.9&account=7 HTTP/1.1" 200 4040 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:25 +0100] "GET /chart/account/period/7/2024-01-01/2024-02-22 HTTP/1.1" 200 4609 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:46 +0100] "GET /accounts/liabilities HTTP/1.1" 200 7875 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:46 +0100] "GET /v1/jscript/variables?ext=.js&v=6.1.9 HTTP/1.1" 200 4036 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:48 +0100] "GET /accounts/show/22 HTTP/1.1" 200 10195 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:49 +0100] "GET /v1/jscript/variables?ext=.js&v=6.1.9&account=22 HTTP/1.1" 200 4040 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:49 +0100] "GET /chart/account/expense-budget/22/20240101/20240222 HTTP/1.1" 200 3042 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:49 +0100] "GET /chart/account/income-category/22/20240101/20240222 HTTP/1.1" 200 2918 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:49 +0100] "GET /chart/account/period/22/2024-01-01/2024-02-22 HTTP/1.1" 200 4481 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:08:49 +0100] "GET /chart/account/expense-category/22/20240101/20240222 HTTP/1.1" 200 3137 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
127.0.0.1 - - [22/Feb/2024:15:08:57 +0100] "GET /health HTTP/1.1" 200 1776 "-" "Firefly III Health Checker/2.2"
192.168.178.20 - - [22/Feb/2024:15:09:14 +0100] "GET /transactions/show/34 HTTP/1.1" 200 8695 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
192.168.178.20 - - [22/Feb/2024:15:09:15 +0100] "GET /v1/jscript/variables?ext=.js&v=6.1.9 HTTP/1.1" 200 4036 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

### Expected behaviour

I believe this should be a positive amount and the arrow should be incoming (pointing right), i.e. the opposite of withdrawals from the liability and the matching transaction on the source account.

### Steps to reproduce

1. Create a liability
2. Create a transfer from any asset account (e.g. a bank account) to the liability
3. Optionally create an expense from the liability to an expense account to further show that both the deposit and the withdrawals are shown in negative numbers and with the outgoing arrow.

**Comment by PterX** [comment]
https://github.com/firefly-iii/firefly-iii/issues/8567

we both have same question ^.^

**Comment by JC5** [comment]
Yes, thanks for noticing!

Withdrawals are always shown as negative. This is already on my list for the new layout. But context-dependent display of the amount is very tricky right now. I hope to pick this up in https://github.com/firefly-iii/firefly-iii/issues/6304.

**Comment by hanscl** [comment]
@JC5 Thanks for your response. I just started using firefly a few days ago ... I'm quite impressed with the software so far and I think it fits my use case very well. The balance of the liability is correct, which is the crucial part and I am excited to moving all my personal finance stuff over from my spreadsheets. Thanks for your hard work on the new layout, looking forward to it 👍🏻

**Comment by JC5** [comment]
👍💪
