### ISSUE TITLE
Creating rule from bill no longer pre-fills triggers and actions

### ISSUE THREAD

**Issue by jpelgrom** [firefly-iii/firefly-iii#8575]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After storing a new bill, you're redirected to a screen to create an associated rule. Previously this used to be pre-filled with triggers and actions for that rule, but on the latest version it no longer is.

### Debug information

Below is the information from my instance, but I've also reproduced this on the demo site just now (which shows version develop/2024-02-08).

Debug information generated at 2024-02-22 23:04:41 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, pgsql, <strong>*sqlite*</strong>, </td></tr><tr><td>Docker build</td><td><span>#</span>957, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Amsterdam</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-02-22 16:17:03 (6 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-02-01 22:45:15</td></tr><tr><td>Session end</td><td>2024-02-29 22:45:15</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0</td></tr></tbody></table>

### Expected behaviour

The previous behavior (last year) entered a name, triggers for currency, amount and description contains, and an action that linked the transaction to the bill. This allowed you to save the rule with no or minimal edits.

Now, it seems to no longer work correctly: only the title is pre-filled and you have to manually add the amount, description contains, link to bill.

### Steps to reproduce

1. Create a new bill and enter a name, minimum amount and maximum amount. Other values can be left empty/default.
2. Store the new bill.
3. You're redirected to the new rule page. Notice that only the title is pre-filled with bill information.

### Additional info

I tried looking at the code and fix it myself but could only find code cleanup commits in the blame and didn't spot any obvious errors :(

The "may contain private info" box on /debug only has notes about cron jobs, no errors and/or traces.

**Comment by JC5** [comment]
I see what you mean, I'll pick it up!
