### ISSUE TITLE
Display Bug: foreign currency is red & negative in deposits

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#8578]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In the transaction detail view, the foreign amount is red (and shows a minus in front) for deposits:
![image](https://github.com/firefly-iii/firefly-iii/assets/109872040/d19e86e9-cb1b-4d26-813c-833ab2e4a08e)

The other fields or sums don't seem to be affected, so just a display bug.

### Debug information

Current Demo Page

**Comment by JC5** [comment]
Nice find, I'll pick it up!
