### ISSUE TITLE
CSV importer uses "contains" to detect duplicates in External ID

### ISSUE THREAD

**Issue by RobinWeitzel** [firefly-iii/firefly-iii#8582]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When doing a CSV import using "External ID" to detect duplicates Firefly seems to check "contains" instead of "equals" causing transactions being mistakenly labeled as duplicate.

### Debug information

Debug information generated at 2024-02-24 11:14:36 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>957, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Los_Angeles + Europe/Vienna</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / remote_user_guard</td></tr><tr><td>Login headers</td><td>Remote-Email + </td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2024-02-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-02-29 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

Both transactions are imported

### Steps to reproduce

Create a CSV file for import, containing at least the following fields:
xxx,ID,xxx
xxx,5682,xxx
xxx,682,xxx
Run a csv import using the Firefly importer.
Use the ID column to identify duplicates.

### Additional info

Error shown in importer
![image](https://github.com/firefly-iii/firefly-iii/assets/12135433/a5fcf83c-1f37-41ae-9f90-45768113ee50)

Transaction that the link leads to:
![image](https://github.com/firefly-iii/firefly-iii/assets/12135433/805e30c6-9ac6-41fa-a4fc-76a9857295ca)

**Comment by JC5** [comment]
Nice, I'm pretty sure you're right 😅. I'll pick it up!

**Comment by JC5** [comment]
Found and fixed :)

**Comment by RobinWeitzel** [comment]
Thanks, appreciate your work :)
