### ISSUE TITLE
Bills paid are inconsistent between default finance report and bill view

### ISSUE THREAD

**Issue by DireMunchkin** [firefly-iii/firefly-iii#8592]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I notice I have several bills that show as paid in the Bills view, but unpaid in the default finance report. So there seems to be some inconsistency there.

### Debug information

Debug information generated at 2024-02-28 12:19:51 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>957, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + UTC</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-02-28 00:00:00 (12 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-02-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-02-29 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; rv:123.0) Gecko/20100101 Firefox/123.0</td></tr></tbody></table>

### Expected behaviour

I'd expect a bill to either have a payment or not and be the same in both views.

### Steps to reproduce

1. Add bill.
2. Add transaction paying the bill, I.E linked to it.
3. Open default finance report.
4. Scroll down to bills table.
5. Bill shows as unpaid.

### Additional info

This seems to be a bit inconsistent on a per bill basis for me, some show as paid in the default finance report as well, but most do not.

**Comment by JC5** [comment]
Could you help me with a reproducible example?

**Comment by DireMunchkin** [comment]
Hello, sorry for my late reply - I played around reproducing this issue a bit and it doesn't seem to happen if you add the bill transaction with today's date. 

I can detail some more steps with screenshots, does this help?

Steps as follows:
1. Add test bill.
![Screenshot from 2024-03-03 11-40-30](https://github.com/firefly-iii/firefly-iii/assets/1665676/163b5a97-320b-4ac6-a0fd-a8e1a6ebec01)

2. Add back-dated transaction paying this bill.
![Screenshot from 2024-03-03 11-43-04](https://github.com/firefly-iii/firefly-iii/assets/1665676/147cb6db-91ca-4922-8090-383ab1c02452)

3. Bill is correctly displayed as paid in the Bills view.
![Screenshot from 2024-03-03 11-43-46](https://github.com/firefly-iii/firefly-iii/assets/1665676/1dca0053-379b-4e59-a44d-bb40c4ffa3d6)
 
4. Bill is incorrectly displayed as unpaid in default finance report.
![Screenshot from 2024-03-03 11-44-30](https://github.com/firefly-iii/firefly-iii/assets/1665676/7c14d3bc-27cc-436c-b495-77c8e251b663)

**Comment by DireMunchkin** [comment]
OK, I tried that and now I get the result I was expecting. Thanks!
