### ISSUE TITLE
Budgets having Yearly and Monthly budgets; the yearly budgets vanish after a month

### ISSUE THREAD

**Issue by EricVanCaenenberghe** [firefly-iii/firefly-iii#8594]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

At the end of last year I made my budgets for the coming year. Setting monthly budgets and some Yearly budgets for the first time (I know what I going to spend but it is highly irregular, predictable but some months nothing other months rather amounts).
In the budget overview of January I saw the full budget of year and consumed a small portion. The available budget of the month was enormous.
In the budget overview of February there was no budget anymore for that yearly budget (0) so I got automatically an overspend.

### Debug information

No debug is purely the way the system works; the monthly calculations and the representation

### Expected behaviour

The monthly budget overview should separate budgets that are made for more extended period from the monthly budget.
The yearly budget should remain visible for all months indicating what was consumed in previous month(s) and what is consumed in the actual month.

### Steps to reproduce

1. create a yearly budget starting in the next period 5000
2. create a monthly budget starting in the next period 1000
3. available budget of the month 6000
4. consume the yearly budget by 1000 leaving 4000
5. consume the monthly budget by 1000 leaving 0
6. budget 6000 available budget 4000
7. evolve to the next month
8. yearly budget is 0
9. monthly budget is 1000
10. available budget of the month is 1000

**Comment by JC5** [comment]
How are you creating a yearly period?

**Comment by EricVanCaenenberghe** [comment]
![Schermafdruk van 2024-02-28 20-45-23](https://github.com/firefly-iii/firefly-iii/assets/29582047/8ee47a67-f783-4c0f-b5f8-3b657efd7666)

**Comment by JC5** [comment]
What do you mean with "create a yearly budget **starting in the next period** 5000"?

**Comment by EricVanCaenenberghe** [comment]
As a monthly budget starts (if the cron job is active) each first day of the month, I assume that a yearly budget starts the first day of the year. So I created the yearly budget before the first day of the year. In my case the budget that I saw in January was populated by the cron job of fireflyiii, same for February, no manual manipulation on my side of the budgets in January and February.

**Comment by JC5** [comment]
I'm still a little unclear about this part:

1. evolve to the next month
2. yearly budget is 0
3. monthly budget is 1000
4. available budget of the month is 1000

What does it mean?

**Comment by JC5** [comment]
I can't replicate that. When I create a yearly budget like you describe, it's visible every month on the `/budgets` page.

**Comment by EricVanCaenenberghe** [comment]
The budget as a line is visible but it has no budget amount. Trying to visualize the initial example.
in January overal budget 6000 used 0
budget line 1 (yearly) 0/5000
budget line 2 (monthly) 0/1000

in February overall budget 1000 used 0
budget line 1 (yearly) 0/0
budget line 2 (monthly) 0/1000

while in a quarterly overview
January
Q1 overall budget  8000 used 0
budget line 1 (yearly) 0 / 5000
budget line 2 (monthly) 0 / 3000

February
Q1 overall budget 8000 used 2000
budget line 1 (yearly) 1000 / 5000
budget line 2 (monthly) 1000 / 3000

**Comment by JC5** [comment]
Could you share a screenshot?

**Comment by EricVanCaenenberghe** [comment]
3 screenshots the first one is a monthly view the concerning budget is showing 0 (the progress bar take in account the 0); 2 (for the sake of completness) other screenshots are a quarterly view on the same budget split. In this quarterly view the foreseen yearly budget is popping up.
![printscreen 2024-03-21 monthly view](https://github.com/firefly-iii/firefly-iii/assets/29582047/ac2fa3b4-125c-4cf9-b5e6-0379bacca855)
![printscreen 2024-03-21 quarterly view 1](https://github.com/firefly-iii/firefly-iii/assets/29582047/cdcd9399-5d07-4615-80ab-675cbeacc829)
![printscreen 2024-03-21 quarterly view 2](https://github.com/firefly-iii/firefly-iii/assets/29582047/d5c52ec1-fe8f-401d-825f-d76eacfb77f6)

**Comment by JC5** [comment]
Ah, i think i see what you mean. The budget list shows all budget lines that apply to the current period, even when they are overlapping in some way.

**Comment by EricVanCaenenberghe** [comment]
Sorry I disagree, 
Why does it show in a monthly overview 0 and in the quarterly view the full amount of the yearly budget?
Also, but I'm not able show this anymore -will we'll have to wait another 9 months ;-) - in the monthly overview of January the progress bar of available budget of January took in account the full yearly budget while in the monthly overview of February the yearly budget was not taken in account.

possible expected behaviours for the monthly overviews progress bars budget
1: do not take in account the budgets that span more then a month
2: do take in account all type of budgets but then show also the spend amount of previous periods that are part of that budget
 
expected behaviour overview: monthly overview matching the quarterly overview
a line for the budgets that span more then a month(1) with as budgetted amount the full budget of the period(2); and for "spend": the amount spend in the previous periods + amount spend in the actual period(3).
(1) present in both cases
(2) is 0 in the monthly overview, is the full yearly budget in the quarterly overview
(3) is only the amount spend in the actual period that is shown in the overview when the overview shows a monthly period; this is what a the quarterly budget is showing
.

**Comment by JC5** [comment]
Good points. I'll think of something, and pick it up with the efforts for the new layout im building. 

I'll close this with a reference to https://github.com/firefly-iii/firefly-iii/issues/6305.
