### ISSUE TITLE
Multiuser implementation

### ISSUE THREAD

**Issue by r1bas4** [firefly-iii/firefly-iii#8595]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to see a better multiuser environment. Yes, I know it's on the "Missing Features" page, but it would be great if multiuser was better implemented.

### Solution

Add a better multiuser system.

**Comment by JC5** [comment]
[Yes thanm](https://github.com/firefly-iii/firefly-iii/issues/6331)
