### ISSUE TITLE
Show dates on homepage transactions

### ISSUE THREAD

**Issue by MaoMaoCake** [firefly-iii/firefly-iii#8596]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi, I wolud like to have the ability to see when a transaction is done on the home screen. I do understand that some people may no want this but it could be hidden behind a toggle switch

### Solution

Add a toggle to enable dates to be shown beside the transaction

### Additional context

here's my "artistic" impression
![Screenshot from 2024-02-29 17-15-57](https://github.com/firefly-iii/firefly-iii/assets/55589246/dd9e8e8c-59a8-44d5-aae7-d135ae98df8b)

**Comment by JC5** [comment]
Not right now I'm afraid, but perhaps in the new layout!

https://github.com/firefly-iii/firefly-iii/issues/6299
