### ISSUE TITLE
Reconciliation Selection Box Not Displaying When Ending Balance Selected for February 29th

### ISSUE THREAD

**Issue by yong-s** [firefly-iii/firefly-iii#8597]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When selecting February 29th as the end date for the reconciliation page's ending balance, the corresponding selection box for reconciliation is not visible.

### Debug information

 version **v6.1.9**.

**Comment by yong-s** [comment]
As shown in the screenshot below, when I select February 29th as the end date, the reconciliation range below does not include transactions for February 29th. The selection of February 29th in the screenshot is due to changing the end date to March 1st.
<img width="946" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/47684798/598b5911-0a8c-4e72-94bb-ef1a5db92a0a">

**Comment by yong-s** [comment]
As shown in the screenshot below, when I select February 29th as the end date, the reconciliation range below does not include transactions for February 29th. The selection of February 29th in the screenshot is due to changing the end date to March 1st.
<img width="946" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/47684798/598b5911-0a8c-4e72-94bb-ef1a5db92a0a">

**Comment by JC5** [comment]
Ah nice, I'll check it out.
