### ISSUE TITLE
Link Credit Card to Bank Account

### ISSUE THREAD

**Issue by ChrisWin22** [firefly-iii/firefly-iii#8602]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like Firefly iii to have Credit Cards and the Bank Account that pays off the credit card to be linked. 

### Solution

This would allow you to see how much is truly left in your account while keeping your transactions in the correct location. The amount of the linked Bank Account would be the current Bank Account balance - Amount on all linked Credit Cards. 

### What are alternatives?

Currently I am saying all Credit Card transactions are coming from the Bank Account that pays it off directly. This is fine but doesn't give the full picture. It would be nice to use the Credit Card asset account while still being able to easily see how much I have remaining in my Accounts as if I had everything paid off. A separate view that you could open would also work to quickly see what your true amount in the account is.

**Comment by JC5** [comment]
No, this isn't going to happen, sorry.
