### ISSUE TITLE
Piggy bank progress bar display incorrectly based on window width

### ISSUE THREAD

**Issue by SlimG** [firefly-iii/firefly-iii#8603]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When Expanding and contracting the width of the browser while looking at piggy banks, the bar displaying the visual percentage does not reflect the correct state when browser window is made narrow.

Example from narrow browser window:
![bilde](https://github.com/firefly-iii/firefly-iii/assets/50249/5fa5302a-baf7-465d-bc28-69d9d78de190)

Example from wide browser window:
![bilde](https://github.com/firefly-iii/firefly-iii/assets/50249/7a526b93-cf61-4062-a58f-805502d36627)

### Debug information

Debug information generated at 2024-03-01 21:28:33 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>957, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Oslo + Europe/Oslo</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>nn_NO + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-03-01 00:00:00 (21 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 2</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-03-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-03-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>nn_NO</td></tr><tr><td>User locale</td><td>nn_NO</td></tr><tr><td>Locale(s) supported</td><td>nn_NO.utf8: :white_check_mark:<br>nn_NO.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The percentage of the piggy bank being correctly displayed by the visual progress bar

### Steps to reproduce

1. Go to /piggy-banks
2. Find a piggy bank with a progress bar more than 0% and less than 100%
3. Expand and contract the browser window while paying attention to the visual representation of the progress bar

### Additional info

Tested in Ubuntu 23.10 on Firefox 123.0 (64-bit) and Google Chrome 119.0.6045.123 (64-bit)

**Comment by JC5** [comment]
Thanks for reporting. I'm not going to fix this though. Im working on a new layout.
