### ISSUE TITLE
Data Importer Vanity URL with Docker not being shown

### ISSUE THREAD

**Issue by Jademalo** [firefly-iii/firefly-iii#8607]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The Data Importer `VANITY_URL` is not being used, and instead it is just showing `FIREFLY_III_URL`.

### Debug information

Debug information generated at 2024-03-02 13:45:32 Europe/Amsterdam for Firefly III Data Importer version **1.4.4**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.4.4</td></tr><tr><td>Build</td><td><span>#</span>, base <span>#</span>80</td></tr><tr><td>System</td><td>PHP 8.3.3, Linux, apache2handler</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Amsterdam, Europe/London</td></tr><tr><td>Environment</td><td>local</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td></td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0</td></tr></table>

### Expected behaviour

I'd expect the URLs on the data importer page to link to my vanity URL for ease of use, but it just displays the URL set in `FIREFLY_III_URL`

### Steps to reproduce

1. Set up Firefly with Docker as per [the guide](https://docs.firefly-iii.org/how-to/data-importer/installation/docker/) with the exception of changing the port forwarded from docker to `82` to prevent a conflict (80 and 8080 are both in use locally on the machine)
2. Set the `VANITY_URL` to `http://scotty-server.local:82`, which is the address I can access Firefly on
3. Run docker compose, and navigate to `http://scotty-server.local:81` to use the Importer

### Additional info

The top two lines of my `.importer.env` are as follows;

```
# Firefly Data Importer (FIDI) configuration file

# Where is Firefly III?
#
# 1) Make sure you ADD http:// or https://
# 2) Make sure you REMOVE any trailing slash from the end of the URL.
# 3) In case of Docker, refer to the internal IP of your Firefly III installation.
#
# Setting this value is not mandatory. But it is very useful.
#
# This variable can be set from a file if you append it with _FILE
#
FIREFLY_III_URL=http://app:8080

#
# Imagine Firefly III can be reached at "http://172.16.0.2:8082" (internal Docker network or something).
# But you have a fancy URL: "https://personal-finances.bill.microsoft.com/"
#
# In those cases, you can overrule the URL so when the data importer links back to Firefly III, it uses the correct URL.
#
# 1) Make sure you ADD http:// or https://
# 2) Make sure you REMOVE any trailing slash from the end of the URL.
#
# IF YOU SET THIS VALUE, YOU MUST ALSO SET THE FIREFLY_III_URL
#
# This variable can be set from a file if you append it with _FILE
#
VANITY_URL=http://scotty-server.local:82
```
However, the importer clearly isn't using the vanity url;
![image](https://github.com/firefly-iii/firefly-iii/assets/386846/5256f757-7ab6-4c49-b130-22fa386b0681)

I've tried making various changes to the env file, and if I change `FIREFLY_III_URL` then it reflects those changes, but it seemingly refuses to use the vanity url.

**Comment by JC5** [comment]
Did you press "start over"?

**Comment by Jademalo** [comment]
Yes, and I've tried `docker compose down` to rebuild the containers. I've also tried a different browser.

Changes to `FIREFLY_III_URL` seem to reflect, so I don't think the issue is browser caching.

**Comment by JC5** [comment]
Then I'm not sure, I'll check it out.

**Comment by JC5** [comment]
Fixed in the next release, it's just a visual glitch.

**Comment by Jademalo** [comment]
Fantastic, thanks for the quick work!
