### ISSUE TITLE
Converting imported transaction to transfer validation

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#861]
I was trying to convert a imported transaction to a transfer (credit card payment).

1. Source account (revenue account) fails validation
2. Destination account (asset account) fails validation
3. Source account (asset account) fails validation
4. firefly.invalid_convert_selection translation is missing

I know I selected the wrong "Source account (asset account)" but the validation offers no hints/explanations

**Comment by JC5** [comment]
The idea was that if you select the wrong account, the account field (whichever one it was) would light up and show you the error. For this reason, every possible account field (point 1, 2 and 3) lights up with an error.

However, I am pretty sure that the red error bar mentions all three of them, which isn't really user friendly.

I can't fix the multiple messages at the moment but I can add the error to the translation strings, making it clear what is going on.

**Comment by gavu** [comment]
Sorry. Closed by mistake

Now I understand how you designed it. It also was an error on my side, i should have read wgat the help-text explained :)

**Comment by JC5** [comment]
Had time to check it out. The combination as it is right now is not too bad, combined with actual help text.
