### ISSUE TITLE
Some minor color issues

### ISSUE THREAD

**Issue by rumpff** [firefly-iii/firefly-iii#8613]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have found a few theme specific color issues, for each of them the system theme was set to dark

### Debug information

Debug information generated at 2024-03-03 05:57:41 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>957, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Amsterdam</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-03-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-03-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0</td></tr></tbody></table>

### Expected behaviour

1: (Dark mode) In options \ preferences the fiscal year calendar icon has a white border, while the date picker (and every other button) does not
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/f8127dfb-7561-4fe5-9003-266c8e3e8100)

potiential fix: use same color as the date selection `#272c30`

![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/39a60756-3580-4b1d-95ef-bcb004fae790)

2: (Dark mode) In options \ administration the Clear cache button text has very bad contrast with the yellow button
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/2b1996b0-e244-4e2d-a78c-104b4f9ea207)

potiential fix: use pure white for the text
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/be39f7c7-d8e1-4726-ab41-e9dbdd7d77ce)

3: (Dark mode) In options \ preferences if you hover over the selected tab title it dims down instead of every tab instead of the selected tab like in light mode, also the color makes it difficult to read due to the contrast
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/ff8dd54f-e05f-432b-995d-0c1b8f232a92)

potiential fix: Use same hover behaviour like in light mode, and change the color to a brighter color. for example `#717478` (this is the old unhovered color with the same brightness difference (33%) as used in the light mode)
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/da05a78b-a6cc-424e-92d1-449c4bf6ecbe)

4: (Dark mode) Larger dividers, like the ones in bills, classification \ groups, options \ currencies, options \ profile \ oauth, are bright white
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/185394e6-67da-4553-bcf9-65a130924046)

potiential fix: Use the same color as the other thinner borders `#353c42`
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/4b3cf9d3-cd8d-490a-b3ca-48786d999df0)

5: (Dark mode) The color of trash buttons icon clashes with the red button
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/06236579-e3c2-4986-a60d-b228aa30de29)

potiential fix: Change icon color to pure white
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/b3fd919e-4361-4dcd-b5b4-9f645f6e5637)

6: (Dark mode) The borders in options \ preferences are bright white
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/85fce6b4-48f4-4eed-ad8a-4e60c4067ee9)

potiential fix: Change color to universal border color `#353c42`
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/aa44291d-1280-4147-8ef3-b808f1d342e3)

7: (Light mode) When the system theme is in dark mode, but firefly is set to light mode checkboxes and tickboxes still have a dark background 
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/036f5d9e-8dee-4d05-8afb-3e0fb0b5a21e)

potiential fix: Use light background
![image](https://github.com/firefly-iii/firefly-iii/assets/22770561/0ab358f7-6a8f-4e59-9445-cc0013edf273)

**Comment by JC5** [comment]
Nice, thanks. Any CSS tips for the check boxes are welcome, I have not yet been able to make them consistently light.

**Comment by rumpff** [comment]
it might be easier to make a custom checkbox instead of relying on the broswer's native checkbox/tickbox

**Comment by JC5** [comment]
Maybe in the new layout then 😀
