### ISSUE TITLE
Create right now option for recurring transaction missing during weekend

### ISSUE THREAD

**Issue by Transportman** [firefly-iii/firefly-iii#8616]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Recurring transactions which occur during the weekend with the setting to have the transaction created on the next Monday do not have the "Create right now" option during the weekend if the regular occurance date has already passed.

### Debug information

Debug information generated at 2024-03-03 10:09:53 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>957, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Amsterdam</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-03-03 00:00:00 (10 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span></td></tr><tr><td>Session start</td><td>2024-03-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-03-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0</td></tr></tbody></table>

### Expected behaviour

The option to create the transaction right now if the transaction has not yet been created because of the Weekend setting

### Steps to reproduce

1. Create a recurring transaction for which the next occurence will be on a Saturday and set Weekend to "Create the transaction on the next Monday instead"
2. Go to the transaction on the Sunday in between
3. Future withdrawals have the option to be created right now but the one that has not yet been created because of the weekend is not present

**Comment by JC5** [comment]
Could you add a screenshot? It works fine for me.

**Comment by Transportman** [comment]
This is how I set up the recurring transaction:
![image](https://github.com/firefly-iii/firefly-iii/assets/47077527/6c4aac7d-711b-435f-83ad-f2123504b0cf)

This is the overview for that recurring transaction
![image](https://github.com/firefly-iii/firefly-iii/assets/47077527/513362b1-be9e-4f41-93ff-9c66062684ec)

The recurring transaction schedule would have created it yesterday (Saturday March 2nd) but as that is in the weekend, it will be created tomorrow on Monday March 4th. This is correct according to the settings, but the expected withdrawals does not show this transaction and blocks me from manually creating it now.
