### ISSUE TITLE
Feature requests: recurring incomes && batch processing && export system for backup

### ISSUE THREAD

**Issue by TheGammelgalopper** [firefly-iii/firefly-iii#863]
So after some hiccups I got the system to work on my server and entered my financial data of the last two months. It is pleasure to use and wonderful to look at!
That auotmagical data presentation works like a charm!

During my first use I found three things that might be worth having. It could be that the fetaures are already in there (somewhere) but I just didn't find them yet...

### Recurring incomes
So there is this thing that you have bills and it tells you what will substracted in the next month.
I would like to have a feature which tells you what will be added in the next month and that feature also actually adds it.
Lets say you get 100$ a month from someone and you know that you will get this every month. It would be nice if there was an option to automatically add this amount every month/week/year.

### "Batch processing"
Lets say you have many transactions already entered and now decide to change one or two values for every transaction. Maybe a button like "Save and edit next transaction in line" would solve this. 

### Backup Export
So I know that you can export the data. But is it also possible to export everything (including the configuration) to backup the system / to migrate to another firefly system on another server?

**Comment by JC5** [comment]
Thanks for the compliments!

Recurring income is a feature request and I'm not yet sure about how to do it. Making recurring transactions in any form of shape actually fit your agenda is very hard. Let alone recurring income.

Batch processing is available. Just press "Select transactions" in the bottom corner. Then select transactions and mass-edit them. If you want to automate this, check out the Rules section. Given certain parameters all your transactions can be changed. Rules will fire automatically but can also run on existing transactions.

It's possible to export everything by opening your favorite database editor and exporting the firefly database.

**Comment by TheGammelgalopper** [comment]
Well that is the least I can do right now! 

So lets hope, that this will work somehow... I wish you luck!

Ah ok it is down there, wasn't expecting this option to be at the bottom. The mass-edit option is very good! Suits my needs very good.

Yeah, the database option, I totally missed that, but firefly only uses one database (I think) so even I should be able to do that!

Thank you a lot!

**Comment by JC5** [comment]
You're welcome! :D

**Comment by Aquariu** [comment]
Dear all,

I'm trying to clean up the mess I've put in my db by messing with the import stuff. Specifically, I would like to delete all transactions imported with a given key. Is there any special reason why the "Select Transaction" button is not visible in the Tag view (i.e. in the list of transaction with a given Tag) ?

Kind regards,

**Comment by TheGammelgalopper** [comment]
@Aquariu you should probably file a new issue for this! It helps other people to find this problem better, if they have the same issue and look for a solution.

This issue is already closed.
