### ISSUE TITLE
Rules not triggerd with Tags longer than 36 Characters

### ISSUE THREAD

**Issue by sn0west** [firefly-iii/firefly-iii#8631]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Tags over 36 Character do not trigger rules. 
I've tested it in the demo site as well.

### Debug information

Debug information generated at 2024-03-05 18:30:43 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>957, base <span>#</span>78</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Zurich + Europe/Zurich</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-03-05 00:00:00 (18 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-03-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-03-05 23:59:59</td></tr><tr><td>View range</td><td>MTD</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36</td></tr></tbody></table>

### Expected behaviour

I setup a lot of rules that should be triggerd when some defined tags are assigned to a transaction. 
In some case it works fine and in some not. 

### Steps to reproduce

1. Create a long tag more than 36 characters
2. Create a new rule that is triggerd with this tag
3. Create a new transaction with this tag
4. Check if the rule has been executed as  planed

**Comment by JC5** [comment]
Sorry but this works just fine for me.

**Comment by JC5** [comment]
I think I spotted the tag you created on the demo site. There's a chance that this tag isn't triggered because there are multiple spaces between the words. HTML makes those invisible, but they are there regardless.

**Comment by sn0west** [comment]
This Tag works fine on my setup.

H9.1 - Nahrungsmittel - Getränke

Just to let you know, I think I will set it up slightly diferent and set the rule to "if the tag starts with" so I can just put the numbers like h9.1 or h9.2 because this are important for me. 

So that the whole tag at a certain length do not wotk anymore is not the end of the world.

**Comment by JC5** [comment]
Like I said, the tag works regardless of length and I suspect your tag has extra spaces in it. 

If this solves your issue, I will close the ticket.

**Comment by sn0west** [comment]
What do you mean extra spaces. I have tags with spaces too and they work fine. 
Yes no problem, close it. But I still think there is a problem there. And I think the workaround will work, I still have to trst it in real life transactions :-)

Thanks anyway for beeing so quick. I realy like firefly.

**Comment by JC5** [comment]
> What do you mean extra spaces. I have tags with spaces too and they work fine.

Multiple spaces in a row, that's the issue.
