### ISSUE TITLE
No search results returned when using `tag_contains` and `tag_starts`

### ISSUE THREAD

**Issue by Call-Me-G-Now** [firefly-iii/firefly-iii#8632]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

No search results returned when using `tag_contains` and `tag_starts`.
`tag_is` and  `tag_ends`do return the correct results.

### Debug information

Debug information generated at 2024-03-05 23:05:40 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.2 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>957, base <span>#</span>79</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Amsterdam</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>debug, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span></td></tr><tr><td>Session start</td><td>2024-01-01 21:30:00</td></tr><tr><td>Session end</td><td>2024-03-05 21:30:00</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0</td></tr></tbody></table>

### Expected behaviour

Return results based on searchquery.
`tag_contains:xx` : match any `xx` at any position in a tag
`tag_starts:xx` : match any tag where the first two chars are `xx`, case insensitive.

### Steps to reproduce

1. Create tag "Data"
2. assign label to 1 transaction
3. search using `tag_is:Data` -> shows the transaction
4. search using `tag_ends:ata` -> shows the transaction
5. search using `tag_starts:Dat` -> does not show the transaction "Found 0 transactions"
6. search using `tag_contains:at` -> does not show the transaction "Found 0 transactions"

**Comment by JC5** [comment]
How many tags do you have that start with `Dat` or contain `at`?

If there are multiple such tags, Firefly III expects all of them to be present in the transaction.

**Comment by Call-Me-G-Now** [comment]
> How many tags do you have that start with `Dat` or contain `at`?
> 
> If there are multiple such tags, Firefly III expects all of them to be present in the transaction. This will be fixed in the next release.

I have multiple (from each import). I understand your explanation, it wasn't logical to me. Thanks for the fix!
