### ISSUE TITLE
Investments, GICs, Insurance (without live tracking)

### ISSUE THREAD

**Issue by joel72265** [firefly-iii/firefly-iii#8639]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

New Feature:  If you can add this feature I think it would be useful to many peoples personal finance.. It does not need to pull live data but just keep track of an individuals investment details like maturity, email reminders .... maybe there are others have better ideas.

I did notice a similar request years ago but wanted to suggest it again https://github.com/firefly-iii/firefly-iii/issues/2313[](url)

### Solution

Request to ADD this feature

**Comment by JC5** [comment]
https://docs.firefly-iii.org/explanation/more-information/what-its-not/#stock-and-portfolio-management
