### ISSUE TITLE
firefly behind apache reverse proxy

### ISSUE THREAD

**Issue by Moltenkore** [firefly-iii/firefly-iii#864]
I'm trying to get firefly to work behind an apache reverse proxy but I'm having some issues trying to find and edit the env to change the URL. At the moment it keeps trying to redirect to localhost which is of course wrong.

I've installed firefly via docker compose but I'm unsure where the env is pulled from and stored once it is in place.

I've also changed the port to only be accessible via localhost so I can just reverse proxy (https) from my domain to it. 
```
...
ports:
      - "127.0.0.1:8153:80"
...
```

Any help is appreciated.

Update: 
Setting either APP_URL or APP_FORCE_ROOT doesn't seem to do anything even after a `php artisan config:cache` inside the container.

Setting the port as shown above will cause it to still request from localhost, setting to `8153:80` will cause it to request from that port specifically which is no use behind a reverse proxy.

Update 2: On digging it's related to #566 

Update 3: Added `ProxyPreserveHost On` to my apache config on my reverse proxy side and now it's requesting from the right domain but still trying to request non-secure content. ~~Also a problem cropped up with slashes.~~

```
Mixed Content: The page at 'https://money.mydomain.com/login' was loaded over HTTPS, but requested an insecure script 'http://money.mydomain.com/js/ff/guest.js'. This request has been blocked; the content must be served over HTTPS.
login:1 Mixed Content: The page at 'https://money.mydomain.com/login' was loaded over HTTPS, but requested an insecure favicon 'http://money.mydomain.com/favicon-32x32.png'. This content should also be served over HTTPS.
favicon-32x32.png/:1 GET https://money.mydomain.comfavicon-32x32.png/ net::ERR_NAME_NOT_RESOLVED
login:1 Mixed Content: The page at 'https://money.mydomain.com/login' was loaded over HTTPS, but requested an insecure favicon 'http://money.mydomain.com/favicon-16x16.png'. This content should also be served over HTTPS.
favicon-16x16.png/:1 GET https://money.mydomain.comfavicon-16x16.png/ net::ERR_NAME_NOT_RESOLVED
```
Update 4: Slash problem fixed, I forgot to stick in a slash on redirect from non-HTTPS.

**Comment by gavu** [comment]
I don’t know how your apache host file looks like but maybe this would help:

https://help.nextcloud.com/t/solved-apache-missing-slash-in-domain/4033

**Comment by JC5** [comment]
Try this:

Set APP_FORCE_SSL=true and  APP_FORCE_ROOT=httpS://your.site

**Comment by Moltenkore** [comment]
@JC5 tried that already (first update), doesn't work. It just ignores the two variables.

**Comment by JC5** [comment]
That shouldn't happen. The next version of FF doesn't use those variables though, so I can't really look into it. The whole process improves because Laravel has improved.

**Comment by manmademagic** [comment]
I've been doing some testing and it looks like the Dockerfile doesn't copy .env.docker to the correct location.
The entrypoint.sh doesn't find .env.docker, but continues without an error using the default .env file

Adding the following line, after the last COPY command, should resolve the issue:
`COPY .env.docker /var/www/firefly-iii/.env.docker`

You can also then modify the .env.docker file as follows, and then pass your APP_URL and APP_FORCE_SLL as the respective environment variables to the container
```APP_ENV=${FF_APP_ENV}
APP_DEBUG=false
APP_FORCE_SSL=${FF_FORCE_SSL}
APP_FORCE_ROOT=${FF_FORCE_ROOT}
APP_KEY=${FF_APP_KEY}
APP_LOG=daily
APP_LOG_LEVEL=warning
APP_URL=${FF_APP_URL}

DB_CONNECTION=mysql
DB_HOST=${FF_DB_HOST}
DB_PORT=3306
DB_DATABASE=${FF_DB_NAME}
DB_USERNAME=${FF_DB_USER}
DB_PASSWORD=${FF_DB_PASSWORD}```

**Comment by Moltenkore** [comment]
That did it, thanks! @manmademagic

**Comment by cusco** [comment]
Hello,

I've just tried to set both APP_FORCE_SSL=true and APP_FORCE_ROOT=https://mysite.com
I can inspect the docker image and see that those environment variables are set

I can see the web login page, but css files are being blocked by the browser as it is trying to source them as http:// instead of https://

Is there something else one must do?
