### ISSUE TITLE
Piggy banks | Display "suggested per month" total for asset accounts

### ISSUE THREAD

**Issue by 0styx0** [firefly-iii/firefly-iii#8643]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Add a "suggested per month" total for each asset account in the piggy bank page

### Solution

Adding a "suggested per month" on the account level adds symmetry to the piggy bank page, as Firefly already displays this information for individual piggy banks and for piggy bank groups

### What are alternatives?

1. Putting all piggy banks into one group. Firefly already displays the total of all piggy banks within the group
    - Con: Using groups in this manner means one can only have one group
2. Manually summing together the suggested amount from all (i.e multiple) piggy banks or groups
   - Con: Tedious and error prone

### Additional context

Mock-up of the feature proposal:
![firefly-suggested-per-month-account-example](https://github.com/firefly-iii/firefly-iii/assets/18606569/51485766-bceb-4ca0-b397-3d50fafe92fe)

My usecase: I store money bookmarked via my piggy banks in one bank account dedicated to that purpose, and transfer the suggested amount into that account each month. Since I exclude that account from counting in my net worth within Firefly, I can get a more accurate picture of my finances

**Comment by JC5** [comment]
Nice, something to remember for https://github.com/firefly-iii/firefly-iii/issues/6307
