### ISSUE TITLE
Crashes during initial setup with PG 16 dbs

### ISSUE THREAD

**Issue by Lysholm** [firefly-iii/firefly-iii#8648]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since PG 15 the 'public' schema is without grants on them by default resulting in the initial setup failing.

This can be worked around by having a super user grant those necessary privileges, but in security conscious setups (clod provided or default percona/pg-db deployment ie.) that's not viable.

Changing the default schema in firefly would be ideal but I guess that might be a bit of an unkind upgrade. Documenting the limitation and how to use the env variable added with https://github.com/firefly-iii/firefly-iii/issues/5503 would be nice. I can do a PR if you give me a hint where you'd prefer it documented.

### Debug information

Don't get to this point service never readies up.

### Steps to reproduce

1. Install PG 16
2. Try starting latest firefly

**Comment by JC5** [comment]
I have no idea what you're talking about, sorry.

**Comment by Lysholm** [comment]
@JC5 PGSQL_SCHEMA is set to 'public' by default. Since PG 15 only a user with "SUPERUSER" role can write there, unless specifically granted access on that schema.

**Comment by JC5** [comment]
Ah, postgresql, got it! 

Let me think about it. Perhaps a note in .env.example is enough.

**Comment by JC5** [comment]
If you could extend this comment, that would be perfect.

https://github.com/firefly-iii/firefly-iii/blob/main/.env.example#L114
