### ISSUE TITLE
kubernetes helm chart firefly-iii-stack expects storageClass nfs-client to be deployed

### ISSUE THREAD

**Issue by NerdyShawn** [firefly-iii/firefly-iii#8651]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The default values of the helm chart **firefly-iii/firefly-iii-stack** should probably just use an available default storageClass instead of hardcoded to **class=nfs-client** where not all user clusters may have a class specifically named this available.

```c
k get sc 
NAME                    PROVISIONER    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
civo-volume (default)   csi.civo.com   Delete          WaitForFirstConsumer   true                   70d

k get pvc -n firefly-iii 
NAME                                   STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
firefly-iii-firefly-db-storage-claim   Pending                                                                        nfs-client     5m52s
firefly-iii                            Bound     pvc-9dd277bd-71ac-432d-84a8-fc50ad73b3af   1Gi        RWO            civo-volume    5m52s
```

### Debug information

HTTP ERROR 500

No database for the app pod to connect to
```c
kubectl port-forward -n firefly-iii svc/firefly-iii --address 0.0.0.0 3000:80
Forwarding from 0.0.0.0:3000 -> 8080
```

### Expected behaviour

I would expect the helm chart to just leverage any default deployed storageClass available for pvc's instead of specific to **nfs-client**.

### Steps to reproduce

Deploy the helm chart of charts, the **firefly-iii-stack** manifest to a kubernetes cluster. 
```c
 helm upgrade -i firefly-iii firefly-iii/firefly-iii-stack -n firefly-iii --create-namespace
Release "firefly-iii" does not exist. Installing it now.
NAME: firefly-iii
LAST DEPLOYED: Sat Mar  9 11:13:19 2024
NAMESPACE: firefly-iii
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

### Additional info

I was able to deploy the default values of the chart into an on-prem cluster that does have an nfs-client which satisfies the pvc requests to avoid the forever Pending state.

This is what the stack chart is using
```c
 helm show values firefly-iii/firefly-iii-stack | grep storage -A 3
  storage:
    class: nfs-client
    accessModes: ReadWriteMany
    dataSize: 1Gi
```

**Comment by JC5** [comment]
Thanks for the suggestion! Feel free to open a PR with the necessary changes.

**Comment by NerdyShawn** [comment]
Ok thanks assembling a PR now on the stack values. The other accessModes option **ReadWriteMany** might also be a bit presumptuous as not all storageClasses will support **ReadWriteMany** as well so I think that might be better undefined and let the end user override if they need it.

**Reference:**
- https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by NerdyShawn** [comment]
Ok I threw a PR together right quick. My first time looking at the codebase, I'm new to the software but excited to get this deployed in a few clusters at different locations for our users. Thanks!
- https://github.com/firefly-iii/kubernetes/pull/69
