### ISSUE TITLE
Default financial report - inverted sum in some popups

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#866]
Report: https://firefly-iii.nder.be/reports/default/1,32,2,3/20170801/20170831
As you know, clicking (i) shows nice popups with list of transactions, but...

Popups opened from tables "Revenue / income" and "Expenses" have sum with opposite sign (and color) that summed up transactions.

![image](https://user-images.githubusercontent.com/3846677/30759159-6c0edfe2-9fd5-11e7-8f79-955d23deec9e.png)

![image](https://user-images.githubusercontent.com/3846677/30759170-7afac49e-9fd5-11e7-85a2-7995eefba384.png)

Tables "Budgets", "Categories", "Budgets (split by account)" are OK.

**Comment by JC5** [comment]
Nice find, I'll find them and fix them!
