### ISSUE TITLE
Graph error on Reports

### ISSUE THREAD

**Issue by nicolopozzato** [firefly-iii/firefly-iii#8663]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm writing for a follow up on this #8374 issue.

As last time the error is present both in my local installation and in the demo.

Open the demo, fo in reports, then in the "All-time, all account" https://demo.firefly-iii.org/reports/default/41,6,1,40,5,42,4,2,3/20230201/currentMonthEnd

You can see the first graph "Income vs. exprenses" it's wrong. I don't see any 2025 transactions, but why the 2025 year is present in the graph?
The other card after that are correct (without the 2025 column)

### Debug information

Debug information generated at 2024-03-11 13:51:26 for Firefly III version **v6.1.10**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.10 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.3 (64bits) / apache2handler / Linux aarch64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1003, base <span>#</span>81</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Rome + Europe/Rome</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>it_IT + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-03-04 00:00:00 (1 week ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-03-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-03-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>it_IT</td></tr><tr><td>User locale</td><td>it_IT</td></tr><tr><td>Locale(s) supported</td><td>it_IT.utf8: :white_check_mark:<br>it_IT.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

Don't se the 2025 empty columns in the Income vs. exprenses graph

**Comment by JC5** [comment]
Nice find, I'll check it out!

**Comment by JC5** [comment]
I just realised you also submitted the previous issue, hah. Should be fixed now.
