### ISSUE TITLE
Error sum transaction on reports

### ISSUE THREAD

**Issue by nicolopozzato** [firefly-iii/firefly-iii#8664]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The sum in the report page is not correct if i use the All time, all account link

### Debug information

Debug information generated at 2024-03-11 14:06:20 for Firefly III version **v6.1.10**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.10 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.3 (64bits) / apache2handler / Linux aarch64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1003, base <span>#</span>81</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Rome + Europe/Rome</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>it_IT + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-03-04 00:00:00 (1 week ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-03-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-03-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>it_IT</td></tr><tr><td>User locale</td><td>it_IT</td></tr><tr><td>Locale(s) supported</td><td>it_IT.utf8: :white_check_mark:<br>it_IT.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

If I have a transaction in the future (next month) the "all-time, all account" is not correct.

I suspect the error is the currentMonthEnd in the link https://demo.firefly-iii.org/reports/default/41,6,1,40,5,42,4,2,3/20230201/currentMonthEnd

### Steps to reproduce

1 - add a big income in the next month for simple view
2 - go in the reports and use the all-time all account (you see that the income added in 1. is not in the sum)
3 - use a custom report (example from 1-1-2024 to 31-12-2024) and you see the correct sum.
4 - the current year is correct because it show all the month of this year.

### Additional info

I think that the currentMonthEnd is not correct at 100%, even a currentYearEnd is not 100% accurate (if i insert something next year i think that the "all time" is all time present, past and future)
The current url is more like "past up until this month" and not a true "all-time"

**Comment by JC5** [comment]
Could you be a little more specific? I'll check it out but I need more details.

**Comment by JC5** [comment]
On what date, exactly, do you make the transaction?

I know the date loop for any reporting period can be wonky, so that's where I'll try to find the solution.

**Comment by nicolopozzato** [comment]
> On what date, exactly, do you make the transaction?

You can use the demo site.
Today is the 11-03-2024
create an income on the 15-04-2024 of 3000$ in the normal account

If then you use the alltimeallaccount you don't see this 3000$ income.
If you use the this year report it's correct, in april you see the 3000$.

**Comment by JC5** [comment]
Yes I see what you mean, this will not be fixed. If the transaction is after "currentMonthEnd", it's not part of the report.
