### ISSUE TITLE
Not possible to upload CSV file as an attachment

### ISSUE THREAD

**Issue by dbtdsilva** [firefly-iii/firefly-iii#8668]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Attaching a CSV to a specific tag fails silently. It shows 'Success! Updated tag...', the same happens through the API, a 204 is received.

### Debug information

Debug information generated at 2024-03-13 17:28:19 for Firefly III version **v6.1.10**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.10 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.3 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, pgsql, <strong>*sqlite*</strong>, </td></tr><tr><td>Docker build</td><td><span>#</span>1003, base <span>#</span>81</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Zurich + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2023-03-14 00:00:00</td></tr><tr><td>Session end</td><td>2024-03-13 23:59:59</td></tr><tr><td>View range</td><td>last365</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36</td></tr></tbody></table>

```
Truncated from this point <----|[2024-03-13 17:08:57] local.ERROR: File "montepio_savings_2021_Extractos_007100059422_20220221_20240221.csv" is of type "text/csv" which is not accepted as a new upload.  
[2024-03-13 17:24:36] local.ERROR: File "montepio_savings_2021_Extractos_007100059422_20220221_20240221.csv" is of type "text/csv" which is not accepted as a new upload.  
[2024-03-13 17:25:42] local.ERROR: File "montepio_savings_2021_Extractos_007100059422_20220221_20240221.csv" is of type "text/csv" which is not accepted as a new upload.  

```

### Expected behaviour

Whenever a file is uploaded, to either show a success message and the file is visible afterward or not fail silently.

### Steps to reproduce

1. Go to tags;
2. Create a new tag / modify an existing one;
3. Choose a file in the "Attachments" field that is a CSV.

**Comment by JC5** [comment]
Thanks, I'll pick it up!
