### ISSUE TITLE
Need to disable php7.0 after upgrade

### ISSUE THREAD

**Issue by wouterDeneyer** [firefly-iii/firefly-iii#867]
Hi! 

Just something you could maybe put in the "Upgrade Instructions for 4.6.5"? 

After installing php7.1, I was getting erros all over the place. 
I first uninstalled php7.0 packages that weren't used anymore. 
Then I had to run:
`sudo a2dismod php7.0`
`sudo a2enmod php7.1`
`sudo service apache2 restart`

Thanks!

(loving the software btw ;-) )

**Comment by JC5** [comment]
I've added your commands as an example to the website, thanks!
