### ISSUE TITLE
Import gocardless "merchantCategoryCode"

### ISSUE THREAD

**Issue by tboby** [firefly-iii/firefly-iii#8691]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

The gocardless/nordigen API includes `merchantCategoryCode`, which seems to be pretty well completed for my UK banks.

It would be useful if this field was mapped into transactions on import.

### Solution

With the merchant code it would be possible to automatically map to categories. Actually doing that is outside the scope of this request, but if this was implemented then a 3rd party app could do the mapping.

### What are alternatives?

None that I know of

**Comment by JC5** [comment]
I'll pick it up, thanks! Will probably become a tag.
