### ISSUE TITLE
Date selector does not apply filters properly

### ISSUE THREAD

**Issue by electricmessiah** [firefly-iii/firefly-iii#8699]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I just noticed something. When I click 'Today' in the date filter on the Dashboard it shows over 90 days of data along with a warning that 91 days of data may take a while to load. If I clear the cache, I get the same results. I've changed settings on Layout and keep getting odd results. If I set to year to date, and then click 'Today', it shows Jan 1, 2024 only, but that's not TODAY. 

I'm running v6.1.9 via Docker/latest. Is this a known issue or just a quirky way that it was intended to work? 
today

### 
**JC5 (James Cole)
probably a bug, i hope to improve the date selector in the new layout**

### Expected behaviour

Date selection filters should display data from the chosen dates.

### Steps to reproduce

Use the date selector at the top of the dashboard. One day does not reflect one day. Other filters produce erratic results.

**Comment by JC5** [comment]
Thanks for opening an issue. Which date setting does this happen with? 1 month? YTD? 1 quarter?

**Comment by electricmessiah** [comment]
> Thanks for opening an issue. Which date setting does this happen with? 1 month? YTD? 1 quarter?

Sure.. As I stated in the opening, it's the 'Today' filter that doesn't work correctly.
- Layout set to: 90 days
- Dashboard Date Selector Shows: Dec 22, 2023 - Mar 21, 2024
- Set Dashboard Date Selector to "Today" and nothing changes.
- Now Set Dashboard Date Selector to any other range except 'Today'  and the date selector works.
- Now Set Dashboard Date Selector to "Today" and it shows the wrong range.

**Comment by JC5** [comment]
I can't replicate this, although sometimes it feels buggy. It will not work until all data is loaded on the page you're looking at. When it works however, it seems to work fine.

I'm building a new layout, so I think I'm not going to deep-dive this.

**Comment by JC5** [comment]
One day... ;)
