### ISSUE TITLE
Broken URL to the Administration page

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#870]
Clicking on the "Administration" link redirects to https://my.host.name/home

> An email message will be sent to your old AND new email address. For security purposes, you will not be able to login until you verify your new email address. If you are unsure if your Firefly III installation is capable of sending email, please do not use this feature. You can test this in the [Administration](https://my.host.name/admin).

Could not test it on the demo site because of the following warning:

> Warning! The feature you try to access is not available to demo users.

**Comment by JC5** [comment]
The downside of using the develop branch is that not all features are
complete when I commit them ;).

**Comment by gavu** [comment]
The downside of using the master branch was that I could not import my data, so I can live with a broken URL 😆

**Comment by JC5** [comment]
I'll get right on it :)

**Comment by JC5** [comment]
If the link refers to the home page, you aren't an admin in your own installation. Open table `role_user` and give yourself role 1, which should be the owner role (see table `roles`).
