### ISSUE TITLE
Errors during update

### ISSUE THREAD

**Issue by nloshka404** [firefly-iii/firefly-iii#8705]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

firefly-iii]# php artisan firefly-iii:upgrade-database

   INFO  Running migrations.  

  2016_06_01_000001_create_oauth_auth_codes_table ........................................................................................ 11ms FAIL
[2024-03-21 12:29:25] local.ERROR: Exception is: {"class":"Illuminate\\Database\\QueryException","errorMessage":"SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (Connection: mysql, SQL: create table `oauth_auth_codes` (`id` varchar(100) not null, `user_id` bigint unsigned not null, `client_id` bigint unsigned not null, `scopes` text null, `revoked` tinyint(1) not null, `expires_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)","time":"Thu, 21 Mar 2024 12:29:25 +0300","file":"\/var\/www\/buh.x512.ru\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":795,"code":"42S01","version":"6.1.12","url":"https:\/\/b.x512.ru","userAgent":"Symfony","json":true,"method":"GET","post":""}  
[2024-03-21 12:29:26] local.ERROR: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (Connection: mysql, SQL: create table `oauth_auth_codes` (`id` varchar(100) not null, `user_id` bigint unsigned not null, `client_id` bigint unsigned not null, `scopes` text null, `revoked` tinyint(1) not null, `expires_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (Connection: mysql, SQL: create table `oauth_auth_codes` (`id` varchar(100) not null, `user_id` bigint unsigned not null, `client_id` bigint unsigned not null, `scopes` text null, `revoked` tinyint(1) not null, `expires_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB) at /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795)
[stacktrace]

### Debug information

Debug information generated at 2024-03-21 12:33:04 for Firefly III version **v6.1.12**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.12 / v2.0.12 / 23 (exp. 23)</td></tr><tr><td>PHP version</td><td>8.3.4 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2147483648 (2147483648 bytes)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Moscow + Europe/Moscow</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>ru_RU + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-03-21 03:00:07 (9 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 2</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has reconciled">:ledger:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span></td></tr><tr><td>Session start</td><td>2024-02-20 12:31:22</td></tr><tr><td>Session end</td><td>2024-03-21 12:31:22</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>ru_RU</td></tr><tr><td>User locale</td><td>ru_RU</td></tr><tr><td>Locale(s) supported</td><td>ru_RU.utf8: :white_check_mark:<br>ru_RU.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36</td></tr></tbody></table>

**Comment by nloshka404** [comment]
The web application works normally and there are no errors. The question is what might not work with such errors?

**Comment by nloshka404** [comment]
Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (Connection: mysql, SQL: create table `oauth_auth_codes` (`id` varchar(100) not null, `user_id` bigint unsigned not null, `client_id` bigint unsigned not null, `scopes` text null, `revoked` tinyint(1) not null, `expires_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
    791▕         // If an exception occurs when attempting to run a query, we'll format the error
    792▕         // message to include the bindings with SQL, which will make this exception a
    793▕         // lot more helpful to the developer instead of just the database's errors.
    794▕         catch (Exception $e) {
  ➜ 795▕             throw new QueryException(
    796▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    797▕             );
    798▕         }
    799▕     }

      +32 vendor frames 

  33  app/Console/Commands/Upgrade/UpgradeDatabase.php:91
      Illuminate\Console\Command::call()

  34  app/Console/Commands/Upgrade/UpgradeDatabase.php:46
      FireflyIII\Console\Commands\Upgrade\UpgradeDatabase::callInitialCommands()

**Comment by JC5** [comment]
Did you happen to install 6.1.11 before you installed 6.1.12?

**Comment by nloshka404** [comment]
The update was performed from version 6.1.10 to 6.1.12

**Comment by nloshka404** [comment]
can't you jump from 6.1.10 to 6.1.12? IS IT NECESSARY TO INSTALL ALL RELEASES SEQUENTIALLY?

**Comment by JC5** [comment]
Which commands did you run prior to `php artisan firefly-iii:upgrade-database`

> can't you jump from 6.1.10 to 6.1.12? IS IT NECESSARY TO INSTALL ALL RELEASES SEQUENTIALLY?

You can jump from 4.7.0 to 6.1.12 if you want.

**Comment by nloshka404** [comment]
So I missed only one version 6.1.11 and from version 6.1.10 I played to 6.1.12
Is it so critical not to miss an updated version?

**Comment by JC5** [comment]
I just told you it does not matter that you skipped a version.

Which commands did you run prior to `php artisan firefly-iii:upgrade-database`?

**Comment by nloshka404** [comment]
> I just told you it does not matter that you skipped a version.
> 
> Which commands did you run prior to `php artisan firefly-iii:upgrade-database`?
https://docs.firefly-iii.org/how-to/firefly-iii/upgrade/self-managed/
Then run the following commands:


php artisan migrate --seed
php artisan firefly-iii:decrypt-all
php artisan cache:clear
php artisan firefly-iii:upgrade-database
php artisan firefly-iii:laravel-passport-keys
php artisan cache:clear

**Comment by JC5** [comment]
Run `rm database/migrations/2016_06_01_00000*oauth*.php`, that should remove the migrations.

**Comment by nloshka404** [comment]
firefly-iii]# rm database/migrations/2016_06_01_00000*oauth*.php
rm: невозможно удалить 'database/migrations/2016_06_01_00000*oauth*.php': Нет такого файла или каталога

**Comment by nloshka404** [comment]
migrations]# ls
2016_06_16_000000_create_support_tables.php              2018_01_01_000004_create_oauth_clients_table.php                  2020_07_24_162820_changes_for_v540.php
2016_06_16_000001_create_users_table.php                 2018_01_01_000005_create_oauth_personal_access_clients_table.php  2020_11_12_070604_changes_for_v550.php
2016_06_16_000002_create_main_tables.php                 2018_03_19_141348_changes_for_v472.php                            2021_03_12_061213_changes_for_v550b2.php
2016_08_25_091522_changes_for_3101.php                   2018_04_07_210913_changes_for_v473.php                            2021_05_09_064644_add_ldap_columns_to_users_table.php
2016_09_12_121359_fix_nullables.php                      2018_04_29_174524_changes_for_v474.php                            2021_05_13_053836_extend_currency_info.php
2016_10_09_150037_expand_transactions_table.php          2018_06_08_200526_changes_for_v475.php                            2021_07_05_193044_drop_tele_table.php
2016_10_22_075804_changes_for_v410.php                   2018_09_05_195147_changes_for_v477.php                            2021_08_28_073733_user_groups.php
2016_11_24_210552_changes_for_v420.php                   2018_11_06_172532_changes_for_v479.php                            2021_12_27_000001_create_local_personal_access_tokens_table.php
2016_12_22_150431_changes_for_v430.php                   2019_01_28_193833_changes_for_v4710.php                           2022_08_21_104626_add_user_groups.php
2016_12_28_203205_changes_for_v431.php                   2019_02_05_055516_changes_for_v4711.php                           2022_09_18_123911_create_notifications_table.php
2017_04_13_163623_changes_for_v440.php                   2019_02_11_170529_changes_for_v4712.php                           2022_10_01_074908_invited_users.php
2017_06_02_105232_changes_for_v450.php                   2019_03_11_223700_fix_ldap_configuration.php                      2022_10_01_210238_audit_log_entries.php
2017_08_20_062014_changes_for_v470.php                   2019_03_22_183214_changes_for_v480.php                            2023_08_11_192521_upgrade_og_table.php
2017_11_04_170844_changes_for_v470a.php                  2019_12_28_191351_make_locations_table.php                        2023_10_21_113213_add_currency_pivot_tables.php
2018_01_01_000001_create_oauth_auth_codes_table.php      2020_03_13_201950_changes_for_v520.php                            2024_03_03_174645_add_indices.php
2018_01_01_000002_create_oauth_access_tokens_table.php   2020_06_07_063612_changes_for_v530.php
2018_01_01_000003_create_oauth_refresh_tokens_table.php  2020_06_30_202620_changes_for_v530a.php

**Comment by JC5** [comment]
If the migrations are gone, then there should no longer be an error when you run the commands from the update page:

https://docs.firefly-iii.org/how-to/firefly-iii/upgrade/self-managed/

**Comment by nloshka404** [comment]
> If the migrations are gone, then there should no longer be an error when you run the commands from the update page:
 firefly-iii]# php artisan migrate --seed

   INFO  Running migrations.  

  2016_06_01_000001_create_oauth_auth_codes_table ........................................................................................ 20ms FAIL
[2024-03-22 08:00:58] local.ERROR: Exception is: {"class":"Illuminate\\Database\\QueryException","errorMessage":"SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (Connection: mysql, SQL: create table `oauth_auth_codes` (`id` varchar(100) not null, `user_id` bigint unsigned not null, `client_id` bigint unsigned not null, `scopes` text null, `revoked` tinyint(1) not null, `expires_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)","time":"Fri, 22 Mar 2024 08:00:58 +0300","file":"\/var\/www\/buh.x512.ru\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":795,"code":"42S01","version":"6.1.12","url":"https:\/\/b.x512.ru","userAgent":"Symfony","json":true,"method":"GET","post":""}  
[2024-03-22 08:01:02] local.ERROR: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (Connection: mysql, SQL: create table `oauth_auth_codes` (`id` varchar(100) not null, `user_id` bigint unsigned not null, `client_id` bigint unsigned not null, `scopes` text null, `revoked` tinyint(1) not null, `expires_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (Connection: mysql, SQL: create table `oauth_auth_codes` (`id` varchar(100) not null, `user_id` bigint unsigned not null, `client_id` bigint unsigned not null, `scopes` text null, `revoked` tinyint(1) not null, `expires_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB) at /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795)
[stacktrace]
#0 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Illuminate\\Database\\Connection->run()
#2 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(110): Illuminate\\Database\\Connection->statement()
#3 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(439): Illuminate\\Database\\Schema\\Blueprint->build()
#4 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(281): Illuminate\\Database\\Schema\\Builder->build()
#5 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\\Database\\Schema\\Builder->create()
#6 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/passport/database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php(14): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(493): Illuminate\\Database\\Migrations\\Migration@anonymous->up()
#8 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(410): Illuminate\\Database\\Migrations\\Migrator->runMethod()
#9 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(419): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#10 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->runMigration()
#11 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#12 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(756): Illuminate\\Console\\View\\Components\\Task->render()
#13 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->write()
#14 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(181): Illuminate\\Database\\Migrations\\Migrator->runUp()
#15 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(124): Illuminate\\Database\\Migrations\\Migrator->runPending()
#16 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(88): Illuminate\\Database\\Migrations\\Migrator->run()
#17 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#18 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#19 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#20 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#24 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
#25 /var/www/buh.x512.ru/firefly-iii/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#26 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\\Component\\Console\\Command\\Command->run()
#27 /var/www/buh.x512.ru/firefly-iii/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#28 /var/www/buh.x512.ru/firefly-iii/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#29 /var/www/buh.x512.ru/firefly-iii/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#30 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
#31 /var/www/buh.x512.ru/firefly-iii/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}

[previous exception] [object] (PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists at /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:580)
[stacktrace]
#0 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(580): PDOStatement->execute()
#1 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(788): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Illuminate\\Database\\Connection->run()
#4 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(110): Illuminate\\Database\\Connection->statement()
#5 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(439): Illuminate\\Database\\Schema\\Blueprint->build()
#6 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(281): Illuminate\\Database\\Schema\\Builder->build()
#7 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\\Database\\Schema\\Builder->create()
#8 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/passport/database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php(14): Illuminate\\Support\\Facades\\Facade::__callStatic()
#9 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(493): Illuminate\\Database\\Migrations\\Migration@anonymous->up()
#10 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(410): Illuminate\\Database\\Migrations\\Migrator->runMethod()
#11 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(419): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#12 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->runMigration()
#13 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#14 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(756): Illuminate\\Console\\View\\Components\\Task->render()
#15 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->write()
#16 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(181): Illuminate\\Database\\Migrations\\Migrator->runUp()
#17 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(124): Illuminate\\Database\\Migrations\\Migrator->runPending()
#18 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(88): Illuminate\\Database\\Migrations\\Migrator->run()
#19 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#20 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#21 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#22 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#24 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#25 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#26 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
#27 /var/www/buh.x512.ru/firefly-iii/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#28 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\\Component\\Console\\Command\\Command->run()
#29 /var/www/buh.x512.ru/firefly-iii/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#30 /var/www/buh.x512.ru/firefly-iii/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#31 /var/www/buh.x512.ru/firefly-iii/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#32 /var/www/buh.x512.ru/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
#33 /var/www/buh.x512.ru/firefly-iii/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#34 {main}
"} 

   Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (Connection: mysql, SQL: create table `oauth_auth_codes` (`id` varchar(100) not null, `user_id` bigint unsigned not null, `client_id` bigint unsigned not null, `scopes` text null, `revoked` tinyint(1) not null, `expires_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
    791▕         // If an exception occurs when attempting to run a query, we'll format the error
    792▕         // message to include the bindings with SQL, which will make this exception a
    793▕         // lot more helpful to the developer instead of just the database's errors.
    794▕         catch (Exception $e) {
  ➜ 795▕             throw new QueryException(
    796▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    797▕             );
    798▕         }
    799▕     }

      +34 vendor frames 

  35  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by JC5** [comment]
Sorry, I'm out of ideas. It looks like your installation is migrating files that do not exist. Ghost files? I have no solution for that.

**Comment by nloshka404** [comment]
Will this prevent the system from working in the future?
So everything seems to be working, no errors have been identified yet.

**Comment by JC5** [comment]
No, it should work just fine! I'm just really surprised by the fact that the migration files keep coming back.

**Comment by BoGnY** [comment]
for some reason you have duplicated migration files..

in your error you are trying to migrate `firefly-iii/vendor/laravel/passport/database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php` but probably you have already migrated `firefly-iii/database/migrations/2018_01_01_000001_create_oauth_auth_codes_table.php`

**Comment by BoGnY** [comment]
same error.. founded the problem:


```log
Copying directory [vendor/laravel/passport/database/migrations] to [database/migrations] .................................................... DONE
```

this cause duplication files because it copies `2016_06_01_000001_create_oauth_*` files when `2018_01_01_000001_create_oauth_*` already exists

**Comment by JC5** [comment]
That problem should be fixed in v6.1.12, I wasn't able to replicate this behavior.

**Comment by BoGnY** [comment]
yes 👍🏻..
for me was caused by mine script upgrade that was calling old command for upgrade `php artisan passport:install` instead the new one `php artisan firefly-iii:laravel-passport-keys`

**Comment by nloshka404** [comment]
Well, the fact that everything works means it’s just an error during updates that was simply ignored, but the system as a whole works correctly and stably

**Comment by nloshka404** [comment]
We will assume that with the next updates everything will work as expected. Thank you!
