### ISSUE TITLE
Duplicate detection: Explicitly set external id field name for non csv import

### ISSUE THREAD

**Issue by kesot** [firefly-iii/firefly-iii#8706]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

First off, the UX for external id based duplicate detection could be better: 
- The "Unique column type" allows two options "External identifier" "Additional information" it's not clear what do they mean. Does "external identifier" validate the type to be a guid? what does it do if it's not a guid? What kind of data type is "Additional information"? 
- What property of the json config is it mapped to?

The ultimate ask is to have the option to explicitly set the name of the field that is used by the institution as an identifier. I see there is a unique_column_index which is probably intended for reliable csv format where you would have the same column in the same order all the time but when doing import from e.g. Nordigen I have no idea how it is converted to csv if ever and I would not rely on the order or count of the columns in such case. 

### Solution

Add it to data importer ui as an additional text input when identifier based duplicate detection is selected

**Comment by JC5** [comment]
Heya,

Great suggestions. First for your questions:

> The "Unique column type" allows two options "External identifier" "Additional information" it's not clear what do they mean. Does "external identifier" validate the type to be a guid? what does it do if it's not a guid? What kind of data type is "Additional information"?

It doesn't have to be a guid, it can be anything. In the case of Nordigen, this refers to a data field in the API, that could be clarified.

> What property of the json config is it mapped to?

https://docs.firefly-iii.org/references/data-importer/json/

> The ultimate ask is to have the option to explicitly set the name of the field that is used by the institution as an identifier.

No. What you see is what you get.

**Comment by JC5** [comment]
I've added some extra information to the documentation regarding the duplicate detection.

https://docs.firefly-iii.org/references/data-importer/duplicate-detection/

**Comment by kesot** [comment]
so if nordigen output has 2 fields internalTransactionId (generated by nordigen) and entryReference provided by the bank how do I set which field to use?

**Comment by JC5** [comment]
Like I said, I pick the field.
