### ISSUE TITLE
Searchable dropdowns for rule wizard

### ISSUE THREAD

**Issue by kesot** [firefly-iii/firefly-iii#8707]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When creating a rule dropdowns are not searchable. It's a pain expecially for triggers if you don't know which one exactly you need. e.g. I tried looking for 'tag is any' but alphabetically could not find it so I had to read them all and it's a lot of options I must say.

### Solution

Something like react-select or select2 would do. idk what is the ui framework.

**Comment by JC5** [comment]
Great ide, I'll write it down for https://github.com/firefly-iii/firefly-iii/issues/6308 !
