### ISSUE TITLE
Rules: Ability to append variables to description

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#871]
I have rules to rewrite all my bank transactions. It would be nice to append or prepend variable information.

e.g. 

Original transaction: 
`EC-GAA/POS BAHNHOF KIOSK <redacted text> <redacted date time> Uhr C <some more redacted text>`

Rule now: 
- match "BAHNHOF"
- set description: `<redacted revenue account> Bill`

Rule w/ variable text
- match "BAHNHOF"
- set description: `<redacted revenue account> Bill (%month%)`

```
%month% = date("F");
```

**Comment by simonsmiley** [comment]
implementing this comes with security risks. At least if generic php code is allowed.

**Comment by gavu** [comment]
I did nor mean to actually create “alias” functions to the already existing php ones. I am sure there are ways to secure such functions

**Comment by JC5** [comment]
I'm sorry but no. That's a lot of complexity for a very small use case.

**Comment by gavu** [comment]
that is true
