### ISSUE TITLE
Upgrade to v6.1.12 fails on self-managed host fails during `artisan migrate` steps

### ISSUE THREAD

**Issue by versvs** [firefly-iii/firefly-iii#8715]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Trying to upgrade from v5.6.* to v6.1.12 on a self-managed host is throwing an error when `php artisan migrate --seed` is executed:

```
# php artisan migrate --seed

In Container.php line 906:

  Target class [hash] does not exist.


In Container.php line 904:

  Class "hash" does not exist

```

All previous steps have been reviewed and the php user has access to all files with the right permissions.

### Debug information

Unfortunately I don't have the /debug path available since my system is now not working.

The key info that I remember now is:

* Self-managed host
* PHP 8.3 on Ubuntu
* MySQL as database

### Expected behaviour

I would expect the artisan CLI to run successfully the migration of the database model to the one used by the new Firefly III v6.1.12

### Steps to reproduce

1. Download the v6.1.12 release
2. Unzip it on top of your existing Firefly III install
3. Ensure the owner and permissions of all files are right (aka that the user who owns the apache process can work with them correctly)
4. In the terminal, navigate to the root folder of your project
5. Run `php artisan migrate --seed`
6. Receive the "target class [hash] does not exist" message

### Additional info

I am unsure whether this is a defect on the new v6.1.12 or not, but Artisan seems to be running properly, just finding an issue in one of the newly downloaded files.

Thank you for your support!

**Comment by versvs** [comment]
Solved it doing the upgrade differently as proposed in the manual guide.

nstead of using the Unzip instruction excluding the storage folder, I did unzip everything in a new folder, then copied manually the `.env` file and the `storage/` folder from the previous install. Now artisan identified everything properly and the instance is correctly upgraded to v6.1.12.

**Comment by JC5** [comment]
Thanks for letting me know! I saw somebody else with the same problem, I think I'm getting an idea of what happens, but no clue yet. Since you fixed this, the issue can remain closed, but I will use it as a hint for the next release.

Thanks again!
