### ISSUE TITLE
Include hash (sha256) in the release information

### ISSUE THREAD

**Issue by ovv** [firefly-iii/firefly-iii#8716]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Please include a hash (sha256 or other) of the generated zip file in the release description

### Solution

Validate downloaded archive integrity

**Comment by JC5** [comment]
Sure thing, I'll pick it up!
