### ISSUE TITLE
Ability to duplicate column on import

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#872]
I am planing to start everything from scratch, using only FF's import feature. Until now, I duplicated the "description" column and matched it to the "sepa debet" field (correct me if I'm wrong, can't find your reply at the moment)

Would it be possible to copy the description field into the notes field? It is of great help if you ever want to check the transactions for errors or re-config your rules for the future

**Comment by JC5** [comment]
I can extend the rules to include note-related actions?

**Comment by gavu** [comment]
Great idea, but, just to be sure the rule does not delete any already existing notes, maybe create 2 separate rules:

1. overwrite notes
2. append to notes

**Comment by JC5** [comment]
You can see the result on the demo site. :)

**Comment by gavu** [comment]
I can't really find it, I can see Append/Prepend/Set notes to... but did not find a way to actually specify the source. What am I doing wrong?

**Comment by JC5** [comment]
I can't make you copy them from other fields, I'm afraid, but they can trigger based on content.
