### ISSUE TITLE
Arrow for selecting the month in the Dashboard

### ISSUE THREAD

**Issue by Ircghost** [firefly-iii/firefly-iii#8727]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to have the ability to switch between months on the Dashboard page with the use of arrows, next to the ability to use the already existing dropdown.

![afbeelding](https://github.com/firefly-iii/firefly-iii/assets/36815609/3e07456f-7873-4812-b019-7ee9272ef809)

![afbeelding](https://github.com/firefly-iii/firefly-iii/assets/36815609/ed4ed81e-f185-4af3-ab94-befab84023cc)

Thanks for considering!

### Solution

The arrows to switch between months already exists in the budget page, and is very convenient.

### What are alternatives?

The dropdown, but that's an extra click.

**Comment by JC5** [comment]
Good idea, thanks! Perhaps in the new dashboard.

https://github.com/firefly-iii/firefly-iii/issues/6299
