### ISSUE TITLE
Question: how to handle transfers via imports/rules

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#873]
my csv line where I transfer funds from one account to the other looks like this:

`<account_number>;<date>;<date>;<recipient_1=empty>;<recipient_2=empty>;<description_containing_recipient_iban>;<amount>;<currency>`

if I import CSV form Account_A, I get an outgoing transaction
if I import CSV form Account_B, I get an incoming transaction

How can I "merge" these transactions into a transfer automatically? If I don't, the balance won't match

**Comment by JC5** [comment]
There is no dedicated field for the receiver's name or IBAN when it's a transfer?

**Comment by gavu** [comment]
unfortunately no, however, that should not be a problem, I can "create" one via PowerShell. I use it for #872 already. 

But even if I do have sender/recipient fields, will FF ignore if the amount/date/sender/recipient are identical and create a transfer?

**Comment by gavu** [comment]
If I add 2 more columns in the CSV file as follows:

Account_A.CSV:
- Asset account (IBAN) = IBAN_of_Account_A
- Opposing account (IBAN) = IBAN_of_Account_B

Account_B.CSV:
- Asset account (IBAN) = IBAN_of_Account_B
- Opposing account (IBAN) = IBAN_of_Account_A

will the importer "merge" these 2 transactions into a transfer?

**Comment by JC5** [comment]
Yes, it should. It came up earlier and there's a check for it.
