### ISSUE TITLE
Bill with past end date shown as expected this period

### ISSUE THREAD

**Issue by DMNh** [firefly-iii/firefly-iii#8743]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have a bill with an end date which is now in the past. This bill is still shown as an expected bill.

### Debug information

Debug information generated at 2024-04-02 11:16:09 for Firefly III version **v6.1.10**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.10 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.3 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1003, base <span>#</span>81</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + UTC</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-04-02 00:00:00 (11 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-04-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-04-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; rv:124.0) Gecko/20100101 Firefox/124.0</td></tr></tbody></table>

### Expected behaviour

The bill would not be shown as expected as its end date has passed.

### Steps to reproduce

1. Create a recurring bill with an end date in the past
2. View the bills page

### Additional info

![image](https://github.com/firefly-iii/firefly-iii/assets/8442033/7715474d-1970-420b-bc4b-c146d78bb388)
![image](https://github.com/firefly-iii/firefly-iii/assets/8442033/5ceb4642-9c02-4a17-a095-e87c7d81bdde)

**Comment by JC5** [comment]
Unless a bill is actually made inactive, it will still be expected.

**Comment by DMNh** [comment]
I see, thanks for the quick response. So I would need to manually mark the bill as inactive?

Is there any chance of bills automatically being marked inactive once the end date is reached, or is it simply a cosmetic field?

**Comment by JC5** [comment]
It's cosmetic, it serves as a reminder.
