### ISSUE TITLE
Add Sum totals to searches

### ISSUE THREAD

**Issue by kaipee** [firefly-iii/firefly-iii#8754]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like Firefly to have a Sum totals displayed, similar to the "Meta data" section on tags, when showing search results.

Often I add tags and categories so that I am able to perform searches to see how much has been spend on certain things. This takes place os custom reports, which aren't implemented, but lacks the ability to see overall how much has been spent.

### Solution

Add Sum totals, similar to the "Meta data" section on tags, when showing search results.

**Comment by JC5** [comment]
Thanks for the suggestion! I'm going to pick this up in #6323
