### ISSUE TITLE
"Success! Deleted 0 transaction(s). " after trying to delete several transaction.

### ISSUE THREAD

**Issue by Aquariu** [firefly-iii/firefly-iii#876]
In my account view (anyone of my accounts) or in the more general "Expance" Transcations view, I select one or many transactions. I choose the red delete button. And I confirm on the next screen

This leads to this "Success! Deleted 0 transaction(s)." green message. No transaction is actually deleted. When going back to the same screen, all the transactions are there. I find nothing in the debug logs that would be related to this.

Firefly-iii version: 4.6.3.1

**Comment by JC5** [comment]
This one has been fixed in the latest version for sure :)

**Comment by Aquariu** [comment]
THen I'll update :) 
I'll also update the issue description to add the version.
