### ISSUE TITLE
Perform balance check after the import

### ISSUE THREAD

**Issue by dawid-czarnecki** [firefly-iii/firefly-iii#8769]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

In theory after Data Importer performs the import, bank account balance should be the same as firefly account balance.
It would be great if Data Importer performs this check or provides information about bank and firefly balances side by side. This would be of course possible only if the source provides this information (csv for example may not unless there is a column like "balance after the transaction").

This is similar to the following feature request: https://github.com/firefly-iii/firefly-iii/issues/5460

### Solution

I'm interested to see this information in the API output (or logs) so I'll focus on that.
After the import (`/autoimport` Data Importer endpoint) is successful, there are new lines of output like with structure similar to the following:
```
Account ABC has correct balance of 1000 USD
Account DEF has incorrect balance. Firefly balance: 10.50 EUR. Expected balance: 20 EUR.
Account XYZ has incorrect balance. Firefly balance: 0 EUR. Expected balance: unknown.
```
The last line is a situation when the import source doesn't provide account balance.

### What are alternatives?

I wrote a script to extract the same information from logs. This requires a lot of kung-fu on logs and is prone to errors whenever log format changes or some connection error happens.
Basically this information currently can be extracted from Data Importer log lines that look like the following for Nordigen import:

```
[2024-04-06 11:00:18] local.DEBUG: authenticatedGet(https://bankaccountdata.gocardless.com/api/v2/accounts/XXXXXXXXXXXXX/details/)
[2024-04-06 11:00:30] local.DEBUG: getAccountDetails: Collected information for account {"resourceId":"XXXXXXXXXXXXX","iban":"IBANIBANIBAN","currency":"PLN","ownerName":"YYYYY","cashAccountType":"CACC"} 
...
[2024-04-06 11:00:30] local.DEBUG: authenticatedGet(https://bankaccountdata.gocardless.com/api/v2/accounts/XXXXXXXXXXXXX/balances/)  
...
[2024-04-06 11:00:31] local.DEBUG: Create Balance from array {"balanceAmount":{"amount":"1.72","currency":"PLN"},"balanceType":"interimAvailable","referenceDate":"2024-01-24"} 
```

All above log lines provide information about the specific bank account details along with the downloaded balance.

**Comment by JC5** [comment]
It depends a little bit on your GoCardless output, but in the latest develop branch, you can expect something like this:

```
production.DEBUG: The importer has collected 2 account(s) to report the balance difference on.
production.DEBUG: Report balance difference between Nordigen account "020623a9-54e9-4dc3-a2c1-xxxx" and Firefly III account #2.
production.DEBUG: Nordigen account has 1 balance entry (entries)
production.DEBUG: Now comparing balance entry #1 of 1
Balance comparison: Firefly III account #2: Balance OK
production.DEBUG: Report balance difference between Nordigen account "69abbab6-f069-4df8-a237-xxxx" and Firefly III account #11.
production.DEBUG: Nordigen account has 1 balance entry (entries)
production.DEBUG: Now comparing balance entry #1 of 1
Balance comparison: Firefly III account #11: Balance OK
Done!
```

Things to note:

- GoCardless accounts may have multiple balances, so the message may repeat itself (and be conflicting)
- A mismatched balance will look like this: `Balance comparison: Firefly III account #1: Nordigen reports EUR 12.34, Firefly III reports EUR 12.35`
- Both the OK message and the "not OK" message may be preceded by: `Balance comparison: Firefly III account #1: Currency mismatch` and/or `Balance comparison: Firefly III account #1: Date mismatch`

The `production.DEBUG` lines will show the details.

**Comment by dawid-czarnecki** [comment]
That looks awesome!
Can you add a balance name (or type) so it's possible to distinguish multiple balances?

**Comment by JC5** [comment]
I've added the type, it's all the info I got. But it's there!
