### ISSUE TITLE
HTTP ERROR 500 for some Tags

### ISSUE THREAD

**Issue by MaxMapo** [firefly-iii/firefly-iii#8772]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

if I click on some tags the page goes into error, while others correctly show the page with the associated transactions.
I noticed that from tags 1 to 29 they don't work, from 30 onwards everything is ok 
https://mysite/tags/show/15

### Debug information

Debug information generated at 2024-04-09 23:37:12 for Firefly III version **v6.1.13**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.13 / v2.0.13 / 23 (exp. 23)</td></tr><tr><td>PHP version</td><td>8.3.4 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Rome + Europe/Rome</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>it_IT + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-04-09 03:00:02 (18 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has reconciled">:ledger:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-04-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-04-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>it_IT</td></tr><tr><td>Locale(s) supported</td><td>it_IT.utf8: :white_check_mark:<br>it_IT.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36</td></tr></tbody></table>

**Comment by JC5** [comment]
What error did you see exactly?

**Comment by MaxMapo** [comment]
Just an empty page …

**Comment by JC5** [comment]
https://docs.firefly-iii.org/how-to/general/debug/

**Comment by MaxMapo** [comment]
[ff3-apache2handler-2024-04-10.log](https://github.com/firefly-iii/firefly-iii/files/14935108/ff3-apache2handler-2024-04-10.log)
attached the LOG file after pressing the "sanitarie" TAG

**Comment by JC5** [comment]
Sorry, I see no errors in these logs. Are you hosting Firefly III on your own server?

**Comment by MaxMapo** [comment]
Yes, it’s in self hosting.

**Comment by JC5** [comment]
Sorry, I'm out of ideas. Without an error message of some kind, it's impossible for me to diagnose and debug this.

**Comment by crifpeguy** [comment]
Don't know if this will help, but when I had a 500 error with a blank page on a self-hosted install and nothing in the error logs it ended up being that my PHP memory limit was too low.

**Comment by MaxMapo** [comment]
Great, I increased the PHP memory limit from 128M to 256M and now it works. Thank you @crifpeguy

**Comment by JC5** [comment]
:+1: Nice!
