### ISSUE TITLE
Data Importer: Import transactions with tags rather than add tags right after transactions are imported

### ISSUE THREAD

**Issue by dawid-czarnecki** [firefly-iii/firefly-iii#8780]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

This feature request is a reference to the blue "Rules" annotation from here: https://docs.firefly-iii.org/tutorials/data-importer/gocardless/#import-tag

I'm creating a webhook that relies on the custom tag from different import configs. Depending on this tag the transaction is removed or not.
In the current Data Importer implementation the webhook doesn't see the tag (Webhook sees: `"tags":[]`) as it's added after the transaction create process.

### Solution

Data Importer creates imported transactions with custom tag right away during the creation process. It doesn't add the custom tag after the transaction is created.

### What are alternatives?

I don't see an alternative as webhooks has no knowledge whether the transaction was created with the Data Importer or not.

**Comment by JC5** [comment]
This will not be changed. But, you could set the webhook to respond to changed transactions, that should catch it.

**Comment by dawid-czarnecki** [comment]
Right, that makes sense. Thanks, I will test it.
