### ISSUE TITLE
Display the archived liabilities link when the active list is empty

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#8793]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When there are no active liabilities, the link to the archived liabilities disappears (I'm not sure if this should be categorized as a bug instead).

| With an item | Empty list (after archiving the last one) |
| :---: | :---: |
| ![image](https://github.com/firefly-iii/firefly-iii/assets/226712/a4cf87e8-758d-4026-8679-885b4c717e5d) | ![image](https://github.com/firefly-iii/firefly-iii/assets/226712/42f19470-fc48-482c-9ce6-c084a2f88156) |

Screenshots were taken from the demo on `develop/2024-04-15`.

### Solution

Show the archived liabilities link in all cases

**Comment by JC5** [comment]
I'll pick this up in https://github.com/firefly-iii/firefly-iii/issues/6301
