### ISSUE TITLE
Update Instructions for PI

### ISSUE THREAD

**Issue by 514amir** [firefly-iii/firefly-iii#8795]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The docker instructions on a pi should have steps to use Postgres instead of mariadb because I don't see an arm/7 version of mariadb but there is one for Postgres.

### Debug information

Get a message when doing docker compose saying no manifest arm/7 rpresent

### Expected behaviour

Firefly should start up and do the migrations

### Additional info

I fixed this by altering the .env file to pull pgsql insteadd of mariadb, changed the volume, added correct entries to .db.env I also manually created a firefly shema, granted privileges and fixed the search path

**Comment by JC5** [comment]
I'll see what I can add to the instructions, thanks!
