### ISSUE TITLE
Disable registration

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#880]
Is it possible to disable the registration? I'm running a personal firefly instance and don't want to grant the registration possibility to everyone. Blocking the registration page in nginx serves as a workaround but it might be nice to have this is a configuration option

**Comment by JC5** [comment]
Have you tried registering a second user? Check out the administration.
Multi user is disabled by default.

**Comment by skuzzle** [comment]
That was quick. I see, registering is indeed not possible. Just in case: How would I turn it on if I wanted to add another user?

**Comment by JC5** [comment]
There should be an option under /administration. :-)

**Comment by Findus23** [comment]
Just so I understand it correctly:
If I want to use my instance for two people, I should enable multiuser, let the other person register, and then re-disable multiuser, so nobody else can register.

Maybe it's less confusing if the option is called `disable registration` or something like this (Unless of course it does something else)

**Comment by JC5** [comment]
Doesn’t the text explain what it does? I thought it was pretty clear.

**Comment by Findus23** [comment]
While it does explain that disabling it enables registration, it doesn't make it clear what happens if there are two user and I check it again. Does it delete the second user (after all it is a **single**-user-mode)?
Or are both users kept and further registrations disabled? (What I would need)

**Comment by JC5** [comment]
Yeah that’s true. I’ll see what I can do!
