### ISSUE TITLE
New Rule Capability: Set category (or other parameter) based on previous similar transaction

### ISSUE THREAD

**Issue by dgossghub46** [firefly-iii/firefly-iii#8802]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hello, I would like to request a new option in the rule functionality to allow categories to be set based on how they were set for previous similar transactions. When a transaction is created, and the triggers are met, some parameter(s) will be set to match those parameters for other transactions in the database. 

For instance, about 90% of my transactions are the same month to month, and should be categorized the same way. As the rules are currently structured, I would need to set up a ton of rules, one for each description, to automatically categorize. I think that just setting it to what it was last time will be an administratively light way to automatically categorize most transactions to a good enough level of precision.

### Solution

The rules engine would introduce a new "action value" called "set to recent similar transaction" or thereabouts.

### Additional context

Great product, thanks for putting it together!

**Comment by JC5** [comment]
Sorry no, this is literally impossible. "Similar" is way too vague to be generalized for all Firefly III users. 

If you need complex rules, consider using webhooks to manage these kinds of edits to your transactions.

**Comment by dgossghub46** [comment]
Sorry, poor choice of words using "similar". I think I was trying to make it too general. 

How about this: for a new transaction, look for the most recent transaction that has the same description. If it exists, set the category of the new transaction to that of the old transaction. 

In the meantime I'll check out the webhooks, thanks.

**Comment by dgossghub46** [comment]
Ok thanks for your consideration.
