### ISSUE TITLE
Arrow key changes currency instead of asset accout

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#881]
Hey,

I found a "Bug" (well, not really a bug, but something which is a bit annoying to me :D).

Steps to reproduce:
1. Create a new _Deposit_
2. Select the field _Revenue account_
3. Press "Tab"
4. Select a different _Asset account_ with the "down (or up) arrow key" on the keyboard

Now the curreny-symbol of the input-field _Amount_ has been selected and changed and you can't use the arrow keys to select the next asset account. Instead it selects a different currency.
It works with a new _Withdrawl_ or _Transfer_.

I think this could be because on the _Deposit_-Page the curreny-symbol of the input-field _Amount_ is the next field after _Asset account_. This isn't the case on the other pages. Maybe the curreny-symbol is stealing the input of the arrow keys :D 

I can reproduce this with the current version on the demo page.

**Comment by JC5** [comment]
Well that sure is annoying enough to be a bug. I've seen it myself in action and it's time it gets fixed!

**Comment by JC5** [comment]
Oh, one question: is this in Windows?

**Comment by nicoschreiner** [comment]
No.
I tested it with
- Chromium Version 61.0.3163.79 (Official Build) Built on Ubuntu , running on neon 16.04 (64-bit)
- Firefox 55.0.2 (64-bit)

**Comment by nicoschreiner** [comment]
I just tested it with Windows as well:
- Chrome Version 61.0.3163.100 (Offizieller Build) (64-Bit)
- Internet Explorer 11.608.15063.0
- Microsoft Edge 40.15063.0.0

-> it didn't work

**Comment by JC5** [comment]
Fixed in the dev-branch ([and on the demo site](https://firefly-iii.nder.be/login)).

**Comment by nicoschreiner** [comment]
Thanks. You are very quick :D 

It works on my Linux-PC with Chromium (Version 61.0.3163.79), but the currency symbol still changes :(

And it doesn't work here:
- Linux
   - Firefox 55.0.2 (64-bit)
- Windows
   - Chrome Version 61.0.3163.100 (Offizieller Build) (64-Bit)
   - Internet Explorer 11.608.15063.0
   - Microsoft Edge 40.15063.0.0

**Comment by JC5** [comment]
It changes when the associated accounts are linked to another currency. So that could be the case? Check out /accounts/edit/x to see which currency they're linked to

**Comment by nicoschreiner** [comment]
Sorry! I didn't think of this...
Then it works, of course :D 

But there is still the thing, that it doesn't work at all with the other browsers mentioned. (The same effect as I reported.) It only work in Chromium on Linux. At least this is what I get if I test this...
Which browser did you use to test this?

**Comment by nicoschreiner** [comment]
Ok... Never mind. It cleared the cache and now it works... Sorry

**Comment by JC5** [comment]
No problem :D
