### ISSUE TITLE
Unable to login - Vite - Error 500 after upgrade to 6.1.14 from 6.1.13

### ISSUE THREAD

**Issue by Maxco10** [firefly-iii/firefly-iii#8813]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I just updated to 6.1.14 version from 6.1.13 and I am not able to perform a login because I am getting the error page.

Reading the log, I can see that file is using a wrong path.

![immagine](https://github.com/firefly-iii/firefly-iii/assets/6735404/7966cf67-080c-4d01-be3e-7d6fd56df5ef)

![immagine](https://github.com/firefly-iii/firefly-iii/assets/6735404/29ecb03a-2b35-4199-99ac-984b79b2a83f)

### Debug information

Update from 6.1.13 to 6.1.14

Sorry for poor debug information but I am not able to reach debug page.

### Expected behaviour

See the login page.

### Steps to reproduce

1. Upgrade from firefly version to 6.1.14 from 6.1.13
2. Visit the page

### Additional info

Looking the demo site, I suppose that the issue is a wrong path bacause I am using firefly into a subfolder of my server.

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
Sorry, I can't seem to replicate this. Firefly III works equally wel in normal directories and subdirectories.

**Comment by Maxco10** [comment]
@JC5, I am using the guide to upgrade on documentation site.
The same guide from many versions ago.

**Comment by JC5** [comment]
I believe you, but I can't replicate the issue, like I said. Try reinstalling instead: backup your `storage` directory and `.env`, remove everything else, and reinstall Firefly III. Then, restore the .env file and storage directory.

**Comment by Maxco10** [comment]
@JC5, done! Same issue.

Any idea?

**Comment by JC5** [comment]
Is a `vite.config.js` in the root of your Firefly III directory? There should not be one.

**Comment by Maxco10** [comment]
@JC5 Exactly, the `vite.config.js` is missing on root.

**Comment by JC5** [comment]
Good, it's not supposed to be there. So that works well at least. I was afraid it would have been left behind.

**Comment by Maxco10** [comment]
@JC5 I honestly don't know what happened. I solved it by doing a clean install by migrating keys, database and storage.

I close the ticket.

**Comment by JC5** [comment]
Weird! But I'm glad to hear it's fixed!

**Comment by irgendwie** [comment]
Sorry for hijacking. Unfortunately, I'm running into the same issue here:

```
2024/04/24 15:06:27 [error] 30209#30209: *34 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Unable to locate file in Vite manifest: resources/assets/v2/sass/app.scss. in /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Vite.php:781
Stack trace:
#0 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Vite.php(299): Illuminate\Foundation\Vite->chunk()
#1 /usr/share/webapps/firefly-iii/storage/framework/views/e7361de51f1a9bbf68a4594c3d4320bf.php(65): Illuminate\Foundation\Vite->__invoke()
#2 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(123): require('...')
#3 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#4 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#5 /usr/share/webapps/firefly-iii/vendor/laravel/fra" while reading response header from upstream, client: redacted, server: redacted, request: "GET /login HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "redacted"
```

Established session still work, API access still works (e.g. using external client). Only fresh logins won't work.

**Comment by Maxco10** [comment]
@irgendwie I solved with a clean installation and copy and paste my .env, keys, database and storage.

**Comment by irgendwie** [comment]
@Maxco10 What do you mean by clean installation? I already tried "upgrading" my installation again by following the updated documentation (https://docs.firefly-iii.org/how-to/firefly-iii/upgrade/self-managed/) - so, making a backup, starting with a fresh folder, copying storage and .env. The database is external, so not really keen on redeploying it. The key(s) should be stored in storage, right?

**Comment by zynexiz** [comment]
Actually just run into the same issue here to when trying to upgrade it with my script. Had to revert back to 6.1.13.

**Comment by irgendwie** [comment]
Fixed by issuing `php artisan view:clear` (see https://github.com/firefly-iii/firefly-iii/issues/8821).
