### ISSUE TITLE
Sort sort

### ISSUE THREAD

**Issue by Poachedegg** [firefly-iii/firefly-iii#8816]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When I keep accounts, I usually plan bills according to categories, but when I select the report to view the categories, I find that the categories cannot be sorted according to the size of the amount

### Solution

More intuitive report, from the amount of large to small order, more clear the direction of the amount

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6310


I'll pick it up in this issue about the new layout :)
