### ISSUE TITLE
Problem with apache reverse proxy after updating to 4.6.6

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#882]
Hey,

yesterday I updated my Firefly-III installation from 4.6.4 to 4.6.6 and run into a problem. Maybe someone can help me with this. I don't can make it work...

### Problem
Firefly-III uses my internal server hostname as the base URL. Instead it should use the public URL.
You can see the problem in this screenshot:
![fireflyiii-base-url](https://user-images.githubusercontent.com/31184224/31057872-181c30e4-a6ea-11e7-95d5-7d326ecb3234.png)

This is obviously wrong, because this server isn't accessible from externally. Therefore Firefly-III doesn't work correctly (Well, it doesn't work at all if i try to use the public URL. There are no CSS and JS-Files, because Firefly-III tries to load this from the internal server).
If i use the internal URL everything works correctly.

In version 4.6.4 there was a option _APP_FORCE_ROOT_ which helped a little bit. It still redirected to the internal URL after a login, but if I reloaded the page (public URL) I was logged in and everything worked as expected.
Unfortunately this parameter doesn't seem to work anymore (as @JC5 already mentioned in issue #864).

#### relevant part of my .env file
```
APP_ENV=production
APP_DEBUG=false
APP_NAME=FireflyIII
APP_KEY=XXX
APP_LOG=daily
APP_LOG_LEVEL=warning
APP_URL=https://xxx.example.com
```
(of course i changed _APP_URL_ to the correct public URL :D)

#### What I have already tried
- Add _APP_FORCE_ROOT_ anyway
- Add the code which forced the URL in the previous version to app/Providers/AppServiceProvider.php. But this just throws a error if I access the page and i haven't had time to dig more into this possible solution...
```php
<?php
   // some code
public function boot()
{
   // force root URL.
   $forcedUrl = env('APP_FORCE_ROOT', '');
   if (strlen(strval($forcedUrl)) > 0) {
      URL::forceRootUrl($forcedUrl);
   }
   // force https urls
   if (env('APP_FORCE_SSL', false)) {
      URL::forceScheme('https');
   }
}
```

### Server Setup
There are two apache reverse proxies in my setup:
- a internal one (which serves the pages for the external server)
- a external one (which is the one which serves the pages at the end)

Here is a picture of it:
![fireflyiii-server-setup](https://user-images.githubusercontent.com/31184224/31058030-5c50f21a-a6ed-11e7-984f-3c5fe1e3ecc3.png)

#### config for internal reverse proxy (private in picture)
```
<VirtualHost *:50006>
        ServerName internal-reverse-proxy.example.com

        ErrorLog /var/log/apache2/hosts/fireflyiii-error.log
        CustomLog /var/log/apache2/hosts/fireflyiii-access.log combined

        SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/internal-reverse-proxy.example.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/internal-reverse-proxy.example.com/privkey.pem

        ProxyRequests Off
        SSLProxyEngine On

        ProxyPass "/" "https://internal-firefly-instance/" connectiontimeout=5 timeout=10 retry=60
        ProxyPassReverse "/" "https://internal-firefly-instance/"
</VirtualHost>
```

#### config for public reverse proxy
```
<VirtualHost *:443>

        ServerName xxx.example.com

        ErrorLog /var/log/apache2/hosts/fireflyiii-https-error.log
        CustomLog /var/log/apache2/hosts/fireflyiii-https-access.log combined

        #SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/xxx.example.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/xxx.example.com/privkey.pem

        # HSTS
        Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"

        SSLProxyEngine on
        ProxyRequests Off
        ProxyPass "/" "https://internal-reverse-proxy.example.com:50006/" connectiontimeout=5 timeout=10 retry=60
        ProxyPassReverse "/" "https://internal-reverse-proxy.example.com:50006/"

</VirtualHost>
```

There should be nothing wrong with the server configuration, because it worked before and with there are no problems with other applications.

Many thanks in advance!

**Comment by JC5** [comment]
Laravel changed the way this works. I haven't dug into this yet, but reverse proxies are now supported out of the box:

- https://laravel.com/docs/5.5/requests#configuring-trusted-proxies
- https://laravel-news.com/trusted-proxy
- https://github.com/fideloper/TrustedProxy

**Comment by nicoschreiner** [comment]
Thank you so much! I thought I would never get this running, but it was easier than I though. Your Links helped me a lot.
I can't believe that I didn't found them myself...

I ended up setting the `$proxies` variable to `**` in the file `<BASE_DIR>/firefly-iii/app/Http/Middleware/TrustProxies.php` and it started working. Even better than before (There is no redirect to the internal URL as it was with the earlier version).

Setting it to `**` does the following thing (according to the [GitHub-Repository](https://github.com/fideloper/TrustedProxy) for the TrustedProxy Package):
> The "**" character is syntactic sugar within TrustedProxy to trust not just any proxy that connects directly to your server, but also proxies that connect to those proxies, and all the way back until you reach the original source IP. It will mean that $request->getClientIp() always gets the originating client IP, no matter how many proxies that client's request has subsequently passed through.

#### The file I edited
```php
class TrustProxies extends Middleware
{
    /**
     * The current proxy header mappings.
     *
     * @var array
     */
    protected $headers
        = [
            Request::HEADER_FORWARDED         => 'FORWARDED',
            Request::HEADER_X_FORWARDED_FOR   => 'X_FORWARDED_FOR',
            Request::HEADER_X_FORWARDED_HOST  => 'X_FORWARDED_HOST',
            Request::HEADER_X_FORWARDED_PORT  => 'X_FORWARDED_PORT',
            Request::HEADER_X_FORWARDED_PROTO => 'X_FORWARDED_PROTO',
        ];
    /**
     * The trusted proxies for this application.
     *
     * @var array
     */
    protected $proxies = '**';
}
```

Just if someone else does have the same problem :smiley:

**Comment by nicoschreiner** [comment]
Maybe it would be nice to have a variable in the `.env` file for this?
What do you think?

**Comment by JC5** [comment]
To set the value for `protected $proxies`?

**Comment by nicoschreiner** [comment]
Yes, because otherwise the setting will be lost if there is an update of Firefly-III.
But of course this is just a "nice-to-have" feature and not really necessary :D

**Comment by JC5** [comment]
No that's a good idea! I've pushed an update and it will be included in the next release.
