### ISSUE TITLE
Error 500 after upgrade from v6.1.13 to v6.1.14 or v6.1.15

### ISSUE THREAD

**Issue by zynexiz** [firefly-iii/firefly-iii#8821]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I read the previous bug about this, when upgrading to v6.1.14 and the issue still persists for v6.1.15 (tried both). I use a upgrade script I have created that basically do a clean installation (and copies .env and storage to the new location), but both versions fail to upgrade. If I'm logged in while doing the upgrade the session works, but the login page trow error 500.

### Debug information

[error.log](https://github.com/firefly-iii/firefly-iii/files/15108547/error.log)
Error log from my server

**Comment by JC5** [comment]
I'm sorry, I still have no solution. Are you also running Firefly III in a subdirectory?

**Comment by zynexiz** [comment]
No, i'm running it directly thru a subdomain I configured.

**Comment by JC5** [comment]
Could you share with me (over mail) your configuration and webserver configuration?

james@firefly-iii.org

**Comment by zynexiz** [comment]
Is it the .env file you thinking of for the configuration?

**Comment by BoGnY** [comment]
try deleting vite manifest file and rebuilt it.
manifest searchs an old path that not exists (`resources/assets/v2/sass/app.scss`) but the correct path is `resources/assets/v2/src/sass/app.scss`...

have you extracted archive as noted [here](https://docs.firefly-iii.org/how-to/firefly-iii/upgrade/self-managed/#straight-from-github)?? starting from 6.1.13 git pull can't be used.. I've made a similar error because I use an upgrade script as you and I haven't updated it the first time 😞 

😄

**Comment by JC5** [comment]
Yes. But also whichever webserver is in front of Firefly III

**Comment by mvanrompuy** [comment]
Also willing to help with providing info. Running firefly from a subdomain served over nginx.

Same issue: 6.1.13 worked, 6.1.15 doesn't on my desktop browser, I'm referred to the login page and I get the above mentioned error.

I still have a valid session on my phone, there 6.1.15 works..

**Comment by JC5** [comment]
Same question to you. I have a hard time replicating this. Could you share with me (over mail) your Firefly III configuration (docker compose file, .env file, etc) and your webserver configuration?

[james@firefly-iii.org](mailto:james@firefly-iii.org)

**Comment by zynexiz** [comment]
> Yes. But also whichever webserver is in front of Firefly III

Sorry for the late response, been knocked out for some days with the flue here. I'll strip some info from the .env and send it to you. I'm running Apache on Arch Linux.

**Comment by zynexiz** [comment]
Btw, here's the script I created for updating the application (some paths revoked). Worked really good until now :)

#!/bin/bash

# If not user http, run it as that user
if [ $USER != "http" ]; then
  SELF_NAME=`basename $0`
  SELF_PATH=$(dirname $(readlink -f $0))
  sudo -u http "$SELF_PATH/$SELF_NAME"
  exit
fi

# Get latest version of firefly
latestversion=$(curl -s https://api.github.com/repos/firefly-iii/firefly-iii/releases/latest  | grep -oP '"tag_name": "\K(.*)(?=")')
installedversion=`cat <path to http root>/firefly-iii/version`

if [ $installedversion == $latestversion ]; then
  echo 'Already latest version ('$installedversion')'
  exit
fi

echo 'Version '$installedversion' installed, new version '$latestversion

# Download and unpack the new version and copy files from old instance
cd <path to http root>
echo -n 'Downloading and unpacking Firefly III version '$latestversion'... '
wget -q https://github.com/firefly-iii/firefly-iii/releases/download/$latestversion/FireflyIII-$latestversion.zip
unzip -q -o FireflyIII-$latestversion.zip -d ./firefly-iii-update
cp firefly-iii/.env firefly-iii-update/.env
cp -r firefly-iii/storage ./firefly-iii-update
echo "done."

# Install latest version
cd firefly-iii-update
php artisan migrate --seed
php artisan firefly-iii:decrypt-all
php artisan cache:clear
php artisan firefly-iii:upgrade-database
php artisan firefly-iii:laravel-passport-keys
php artisan cache:clear

cd ..
# Remove old version of firefly-iii
if [ -d "firefly-iii-old" ]; then
  rm -r firefly-iii-old
fi

# Serve the new version
mv firefly-iii firefly-iii-old
mv firefly-iii-update firefly-iii
rm FireflyIII-$latestversion.zip

echo $latestversion | tee /srv/http/firefly-iii/version > /dev/null

**Comment by JC5** [comment]
Mmm. Thanks for your config files.

An alternative solution, clear your browser cache of browse to https://example.com/build/manifest.json and do a hard refresh (ctrl F5 usually does it).

**Comment by zynexiz** [comment]
As I wrote in the mail, I have set Firefox (or well, LibreWolf really) to clear the browser when i close it. So I don't really think it's on the browser side in this case.
![scrdump](https://github.com/firefly-iii/firefly-iii/assets/22789493/d47fd931-6ed6-4c9e-93d6-0bb07a2e560f)

**Comment by zynexiz** [comment]
One odd think I just notices is this line in the logs; `[2024-04-25 12:53:43] local.ERROR: Exception is: {"class":"Illuminate\\View\\ViewException","errorMessage":"Unable to locate file in Vite manifest: resources\/assets\/v2\/sass\/app.scss. (View: \/srv\/http\/firefly-iii\/resources\/views\/layout\/v2\/error.blade.php) (View: \/srv\/http\/firefly-iii\/resources\/views\/layout\/v2\/error.blade.php)","time":"Thu, 25 Apr 2024 12:53:43 +0200","file":"\/srv\/http\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Vite.php","line":781,"code":0,"version":"6.1.15","url":"https:\/\/ff.zoik.se\/login","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:124.0) Gecko\/20100101 Firefox\/124.0","json":true,"method":"GET","post":""}`

Seems to think that resources/assets/v2/sass/app.scss don't exists. But when looking it does exist in my file system, so I'm not sure why it throws this error really.

**Comment by JC5** [comment]
Exactly, nor do I. But we'll get to the bottom of this!

**Comment by JC5** [comment]
That error is especially weird since there is NO reference to that path in v2/error.blade.php.

Sorry, I have to ask. Are you sure you've copied over all the files correctly?

**Comment by zynexiz** [comment]
> Exactly, nor do I. But we'll get to the bottom of this!

Oh, I think I might have look for the path on the old installation. I just updated it again, and not the path don't exist at all.

![Screenshot_20240427_170406](https://github.com/firefly-iii/firefly-iii/assets/22789493/131f9e40-7024-4731-be2b-e4d55783e410)

**Comment by zynexiz** [comment]
> That error is especially weird since there is NO reference to that path in v2/error.blade.php.
> 
> Sorry, I have to ask. Are you sure you've copied over all the files correctly?

I actually redo the installation completely (if you look at the script). I don't reuse any old code, just download the zip-file and unpack it, copy .env and data to the new path. Might be something missing the zip-file?

**Comment by mvanrompuy** [comment]
> > Exactly, nor do I. But we'll get to the bottom of this!
> 
> Oh, I think I might have looked for the path on the old installation. I just updated it again, and now the path don't exist at all.
> 
> ![Screenshot_20240427_170406](https://github.com/firefly-iii/firefly-iii/assets/22789493/131f9e40-7024-4731-be2b-e4d55783e410)

This is indeed what I'm seeing as well. There's an intermediate 'src' folder that is different from the path in the error log.

**Comment by zynexiz** [comment]
Thats the weird part, looking in the error.blade.php, it doesn't have that path anymore so I'm not sure whats going on. I use Redis cache, so that might be a part of the issue. I'm looking into it now.

**Comment by JC5** [comment]
> I actually redo the installation completely (if you look at the script). I don't reuse any old code, just download the zip-file and unpack it, copy .env and data to the new path. Might be something missing the zip-file?

I had to check, but in both zip files the file is there. There is a notable difference between .13 and .15, which is the manifest result path:

<img width="936" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/2097c809-acfd-4007-bb6f-b884fb9a709d">

However, I'm not yet sure why these are so different.

**Comment by zynexiz** [comment]
> > I actually redo the installation completely (if you look at the script). I don't reuse any old code, just download the zip-file and unpack it, copy .env and data to the new path. Might be something missing the zip-file?
> 
> I had to check, but in both zip files the file is there. There is a notable difference between .13 and .15, which is the manifest result path:
> <img alt="image" width="936" src="https://private-user-images.githubusercontent.com/5889984/326187536-2097c809-acfd-4007-bb6f-b884fb9a709d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMzE0NzMsIm5iZiI6MTcxNDIzMTE3MywicGF0aCI6Ii81ODg5OTg0LzMyNjE4NzUzNi0yMDk3YzgwOS1hY2ZkLTQwMDctYmI2Zi1iODg0ZmI5YTcwOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMTUxOTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGEyZjVjZTFiYzM5NGY4ZGEyZDA3NmYyNDUzYjczNDg2M2VlOWQwMjZiMjU1OTRhMzU5MmFiMmJkNDFhZGY1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WuH5VHVhq_HCJPiqgvtIEVFQxYHsBOXGSUrDv_2RRyQ">
> 
> However, I'm not yet sure why these are so different.

I saw the difference to, but that shouldn't trow this error. I looked in the new file, and the new path is indeed there. But the error in the logfile points to the old path which don't make any cense at all IMO.

**Comment by JC5** [comment]
Mmmm, `php artisan cache:clear` should catch it, but what happens when you do `php artisan view:clear`?

**Comment by zynexiz** [comment]
> php artisan view:clear

You are kidding me! That worked :smile:
Need to add that to my script! Nice catch :)

**Comment by JC5** [comment]
I have no clue, I thought they would be the same! :D I shall update the documentation right away!

**Comment by zynexiz** [comment]
> I have no clue, I thought they would be the same! :D I shall update the documentation right away!

Apparently they do something different haha.. I added that line to my script, and now the update works smooth again :)

**Comment by JC5** [comment]
Nice, thanks for helping me find this. The documentation is updated and a new run should put it online in a few mins. 

@mvanrompuy, let me know if this works for you as well.

**Comment by mvanrompuy** [comment]
Not at home, but just tried a new session on my phone. Seems to fix it for me as well. 😄 Thanks for spending the time on figuring this out!

**Comment by zynexiz** [comment]
> Nice, thanks for helping me find this. The documentation is updated and a new run should put it online in a few mins.
> 
> @mvanrompuy, let me know if this works for you as well.

NP :) Glad to help. If you want you can provide my update script to update it a bit smoother. Can make some changes to provide variables to the www root in that case.
