### ISSUE TITLE
Comma in tag-name

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#883]
Hey,

I found a bug with the naming of tags.

Steps to reproduce:
1. create a new tag (i didn't find the button to do this in the current version, so let's rename a existing tag)
2. (re-)name it to: "Test with commas (thing1, thing2, thing3)"
3. create a new _Withdrawl_, _Deposit_ or _Transfer_
4. try to assign the new / renamed tag here
5. see what happens
![fireflyiii-tag-with-comma](https://user-images.githubusercontent.com/31184224/31058470-5e646454-a6f4-11e7-8b44-3e7d4229ffe3.png)

I don't really have a suggestion to fix this as the comma is the split character for the tag-input-field (I think).
If I type "," in the input field it splits the text to a new tag. Maybe it would be better to just use the enter key (is this the correct english-word for it? :D), which does the same as if i type a comma - it splits the Tag.
![fireflyiii-tag-enterkey](https://user-images.githubusercontent.com/31184224/31058532-92241676-a6f5-11e7-9457-090ecac4da2c.png)

I can reproduce this with the current version on the demo page.

**Comment by JC5** [comment]
Tags with commas are not supported, that's all I can say really.

**Comment by nicoschreiner** [comment]
Thanks for your response :smiley: 

Maybe than there should be a message if a user tries to rename a tag and inserts a not supported character?

**Comment by JC5** [comment]
I'll see what works. You're the first one to mention it and so far, it's only the comma that is forbidden. I might just do nothing at all 😉

**Comment by nicoschreiner** [comment]
Oh, then I would be really sad, haha :D 
But you are right... It's not a really bad thing and maybe it's not worth the time to fix it.

**Comment by JC5** [comment]
Yeah I'm going to leave it as-is. But I appreciate your reports, so if you find anything, keep them coming!
