### ISSUE TITLE
Data Importer importing duplicates from CSV

### ISSUE THREAD

**Issue by deanpribetic** [firefly-iii/firefly-iii#8838]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I upgraded to version v1.5.2 of the Data Importer. I ran my daily import from CSV and it is ignoring the `"ignore_duplicate_transactions": true` setting from the config file for the data import. 

I usually export the CSV from my bank account for the last 7 days so I don't miss anything. All previous versions this worked as expected.

### Debug information

Debug information generated at 2024-04-30 07:50:01 Australia/Melbourne for Firefly III Data Importer version **1.5.2**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.5.2</td></tr><tr><td>Build</td><td><span>#</span>628, base <span>#</span>83</td></tr><tr><td>System</td><td>PHP 8.3.6, Linux, apache2handler</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Australia/Melbourne, Australia/Melbourne</td></tr><tr><td>Environment</td><td>local</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td>*</td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0</td></tr></table>

### Expected behaviour

I would expect that most of the transactions would be duplicates

**Comment by deanpribetic** [comment]
Hey James - I just did another import and it correctly ignored duplicates…not sure what to make of that. Happy for you to close the ticket though.

**Comment by JC5** [comment]
Mmmm. Running your example twice gives me all kinds of duplication errors. Did you upgrade to 1.5.2 recently?

**Comment by deanpribetic** [comment]
Yes - on Monday afternoon

**Comment by JC5** [comment]
Aha. I suspect there's a difference between 1.4.4 and 1.5.2. My apologies, I thought there was no impact on the import process. The problem should resolve itself.
