### ISSUE TITLE
Rules: Click on last (empty) priority button in overview link to hompage

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#884]
How to reproduce:

1. Go to rules
2. Scroll to the last rule
3. Click on the empty button -> redirects to https://my.host.name/#

![2017-10-02 13_43_22-rules firefly iii](https://user-images.githubusercontent.com/3742238/31075919-21c4df4a-a778-11e7-9bda-389aed7e0b09.png)

Maybe add a "disabled" property to the `<a>`?

**Comment by JC5** [comment]
Nice find, fixed :)
