### ISSUE TITLE
Budget page crash

### ISSUE THREAD

**Issue by JcMinarro** [firefly-iii/firefly-iii#8840]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I access to the Budget page, the app crash and show a "500 error".
It looks like it is due a division by zero on the template that is going to be rendered.
I'm just posting a screenshot (It is in Spanish, but I think it can help with the error)
![Screenshot from 2024-04-30 10-10-05](https://github.com/firefly-iii/firefly-iii/assets/4047514/3bc8209a-acb0-47c2-a4eb-3090adc23d6d)

It only happen when I go to Budget page selecting as the date range the current month.
If I access with a different date range, it works as expected

### Debug information

Debug information generated at 2024-04-30 10:03:37 for Firefly III version **v6.1.12**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.12 / v2.0.12 / 23 (exp. 23)</td></tr><tr><td>PHP version</td><td>8.3.4 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1037, base <span>#</span>82</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Madrid + Europe/Madrid</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>es_ES + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-04-29 22:00:00 (10 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-04-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-04-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>es_ES</td></tr><tr><td>User locale</td><td>es_ES</td></tr><tr><td>Locale(s) supported</td><td>es_ES.utf8: :white_check_mark:<br>es_ES.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36</td></tr></tbody></table>

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by NiklasMM** [comment]
I'm on 6.1.15 and get this error too. 

When I click on budgets, I get 5 error emails. The first is about a division by zero error:

```
 Firefly III v6.1.15 has encountered an error: An exception has been thrown during the rendering of a template (‘Division by zero’).

The error was of type ‘ErrorException’.

The error occurred: Tue, 30 Apr 2024 20:59:04 +0200.

This error occurred in the file ‘/var/www/firefly-iii/resources/views/budgets/index.twig’ in line 322 with the code 0. 
```

The others seem to be follow up errors:

```
 Firefly III v6.1.15 has encountered an error: Unable to locate file in Vite manifest: resources/assets/v2/sass/app.scss. (View: /var/www/firefly-iii/resources/views/layout/v2/error.blade.php) (View: /var/www/firefly-iii/resources/views/layout/v2/error.blade.php).

The error was of type ‘Illuminate\View\ViewException’.

The error occurred: Tue, 30 Apr 2024 20:59:04 +0200.

This error occurred in the file ‘/var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Vite.php’ in line 781 with the code 0. 

```

**Comment by JC5** [comment]
Thanks! That gives me the line on which the error occurs. Still not good, but it allows me to pinpoint it. 

For the second error, try running "php artisan view:clear".

**Comment by JC5** [comment]
Alright, there is no division by anything on line 322. What happens when you run `php artisan view:clear`? It could be a weird cache thing.

**Comment by NiklasMM** [comment]
Ok running `php artisan view:clear` fixes both issues thanks!
