### ISSUE TITLE
Split recurring transaction gets wrong (split) titles

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#8844]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I know it's not officially supported in the UI, but using the API you can create split recurring transactions. Unfortunately though, the complete transaction and every single split gets the title of the first split. Given the split transaction provided below under additional info, once executed there would only be "Split 1 TX" in all title fields, "Split 2 TX" & "Split TX Title" are not used. All other fields (Amount, Category, Bill, Budget) are fine. 

Looking at past transactions, this behavior seemed to have changed between June & July 2023; it was working fine for a transaction on June 1st, not fine anymore on July 1st (funny enough at the same time, also the order of the transactions changes, i.e. since then "Split 2 TX" is the first split to be saved)

### Debug information

Debug information generated at 2024-05-01 10:46:10 for Firefly III version **v6.1.15**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.15 / v2.0.14 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.6 (64bits) / apache2handler / Linux aarch64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1074, base <span>#</span>83</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-04-30 23:17:02 (9 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-04-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-05-01 23:59:59</td></tr><tr><td>View range</td><td>last30</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr></tbody></table>

### Additional info

Output of query to `api/v1/recurrences/5`. Only slightly changed to hide some information.

```json
{
  "data": {
    "type": "recurrences",
    "id": "5",
    "attributes": {
      "created_at": "2023-01-24T20:30:37+01:00",
      "updated_at": "2024-05-01T01:17:04+02:00",
      "type": "withdrawal",
      "title": "Split TX Title",
      "description": "",
      "first_date": "2023-02-01",
      "latest_date": "2024-05-01",
      "repeat_until": null,
      "apply_rules": true,
      "active": true,
      "nr_of_repetitions": null,
      "notes": null,
      "repetitions": [
        {
          "id": "5",
          "created_at": "2023-01-24T20:30:37+01:00",
          "updated_at": "2023-01-24T20:30:37+01:00",
          "type": "monthly",
          "moment": "1",
          "skip": 0,
          "weekend": 4,
          "description": "An jedem 1. Tag des Monats",
          "occurrences": [
            "2024-05-01T00:00:00+02:00",
            "2024-06-03T23:59:59+02:00",
            "2024-07-01T23:59:59+02:00",
            "2024-08-01T23:59:59+02:00",
            "2024-09-02T23:59:59+02:00"
          ]
        }
      ],
      "transactions": [
        {
          "id": "25",
          "currency_id": "1",
          "currency_code": "EUR",
          "currency_symbol": "€",
          "currency_decimal_places": 2,
          "foreign_currency_id": null,
          "foreign_currency_code": null,
          "foreign_currency_symbol": null,
          "foreign_currency_decimal_places": null,
          "source_id": "1",
          "source_name": "Assets",
          "source_type": "Asset account",
          "destination_id": "61",
          "destination_name": "Expenses",
          "destination_type": "Expense account",
          "amount": "12.00",
          "foreign_amount": null,
          "description": "Split 1 TX",
          "tags": [],
          "category_id": "14",
          "category_name": "Split 1 Category",
          "budget_id": "5",
          "budget_name": "Split 1 Budget",
          "piggy_bank_id": null,
          "piggy_bank_name": null,
          "bill_id": "4",
          "bill_name": "Split 1 Bill"
        },
        {
          "id": "28",
          "currency_id": "1",
          "currency_code": "EUR",
          "currency_symbol": "€",
          "currency_decimal_places": 2,
          "foreign_currency_id": null,
          "foreign_currency_code": null,
          "foreign_currency_symbol": null,
          "foreign_currency_decimal_places": null,
          "source_id": "1",
          "source_name": "Assets",
          "source_type": "Asset account",
          "destination_id": "61",
          "destination_name": "Expenses",
          "destination_type": "Expense account",
          "amount": "34.00",
          "foreign_amount": null,
          "description": "Split 2 TX",
          "tags": [],
          "category_id": "13",
          "category_name": "Split 2 Category",
          "budget_id": "5",
          "budget_name": "Split 2 Budget",
          "piggy_bank_id": null,
          "piggy_bank_name": null,
          "bill_id": "9",
          "bill_name": "Split 2 Bill"
        }
      ]
    },
    "links": {
      "0": {
        "rel": "self",
        "uri": "/recurring/5"
      },
      "self": "https://actual.hostname/api/v1/recurrences/5"
    }
  }
}
```

**Comment by JC5** [comment]
Nice, I'll pick it up!

**Comment by JC5** [comment]
Fixed!
