### ISSUE TITLE
Show upcomming transactions

### ISSUE THREAD

**Issue by M1scer** [firefly-iii/firefly-iii#8845]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to see scheduled transactions (based on invoices) in the chronological order in which they need to be paid next.
The transactions should only be displayed as a reminder. 
No calculations about future account balances are necessary.

### Solution

I have seen something similar in ActualBudget, here the invoices are displayed as transactions in the list of actual transactions.

![image](https://github.com/firefly-iii/firefly-iii/assets/93549967/d4c748c6-dbb4-41df-9fad-e4614481f437)

An additional list next to the invoices would also be conceivable, which lists the pending transactions in chronological order.

**Comment by JC5** [comment]
THis has been suggested before, and will be a part of the new layout. THanks!

https://github.com/firefly-iii/firefly-iii/issues/6304
