### ISSUE TITLE
Send slack notification when a transaction is created or updated manually

### ISSUE THREAD

**Issue by Administratoor** [firefly-iii/firefly-iii#8848]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like Firefly III to send notifications to the configured slack webhook url when I:

- create a new transaction manually or 
- update an existing transaction. 

This should be configurable via checkbox in the settings section.

### Solution

This would be a nice addition to automaticly generated transaction notices where this behavior is already implemented. You would get the possibility to have a "changelog" in your desired slack-channel. 
**Big plus:** Your family can see the transaction you've created directly in slack. (e.g. payed for lunch with cash)

### What are alternatives?

**Not really an alternative, but an existing behavior:** 
Actually only failed rule actions inform about transactions, where for example a "link_to_bill" action could not be performed because the transaction was manually linked to a bill.

**Comment by JC5** [comment]
No, sorry. This can be done using webhooks if you want, but you'll have to develop something yourself to translate between Firefly III data and Slack data.
