### ISSUE TITLE
Oops! An Error Occurred The server returned a "500 Internal Server Error". Login page

### ISSUE THREAD

**Issue by nloshka404** [firefly-iii/firefly-iii#8850]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Error 500 occurs when logging in

### Debug information

Error 500 occurs when logging in

### Additional info

Error 500 occurs when logging in

**Comment by Maxco10** [comment]
you should give a look to this issue: https://github.com/firefly-iii/firefly-iii/issues/8821

**Comment by nloshka404** [comment]
Mmmm, php artisan cache:clear should catch it, but what happens when you do php artisan view:clear?THANK YOU! It's working! 02.05.2024, 14:40, "Maxco10" ***@***.***>: you should give a look to this issue: #8821—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>  -- С уважением,Александр Вяткин+7 (987) ***@***.***://x512.ru

**Comment by Maxco10** [comment]
Please close the issue :)

**Comment by nloshka404** [comment]
Mmmm, php artisan cache:clear should catch it, but what happens when you do php artisan view:clear?
THANK YOU! It's working!
