### ISSUE TITLE
Make rules non-uppercase sensitive

### ISSUE THREAD

**Issue by JRTax** [firefly-iii/firefly-iii#8854]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Rules in version 6.1.15 are case sensetive.

For example, when I create an rule with the following settings:
Description contains: REWE

And I create an transaction called Rewe, the rule doesn't trigger because it doesn't match the rule I've created

### Solution

Make it so it has to match an certain word

**Comment by JC5** [comment]
Hey, thanks for opening an issue. This is not something I can fix for you. 

Here's a different question, with the same answer. 

https://docs.firefly-iii.org/references/faq/firefly-iii/using/#auto-complete-is-case-sensitive
