### ISSUE TITLE
Automation not work 

### ISSUE THREAD

**Issue by poudenes** [firefly-iii/firefly-iii#8855]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

There is a contract of "Rabobank". When I test the automation it is seeing the payment. When I want execute the automation its not edit and not see it. (it worked in past)

### Debug information

If you are running into problems, you can use the information in this box as debug information. Please copy-and-paste into a new or existing [GitHub issue](https://github.com/firefly-iii/firefly-iii/issues). It will generate a beautiful table that can be used to quickly diagnose your problem.

If you copy/paste the box below into a GitHub issue it will generate a table. Please do not surround this text with backticks or quotes.

[Back to the index](http://192.168.100.62:3485/)

You may also share the content of the box below. You can also copy-and-paste this into a new or existing [GitHub issue](https://github.com/firefly-iii/firefly-iii/issues). However, the content of this box may contain private information such as account names, transaction details or email addresses.

[Back to the index](http://192.168.100.62:3485/)

### Additional info
#
#
#
**When testing the automation**
<img width="1073" alt="Screenshot 2024-05-03 at 19 19 39" src="https://github.com/firefly-iii/firefly-iii/assets/4399532/7ed46cd9-85d8-4714-ae75-30034aaeb6af">

#
#
#
**When execute the automation**
<img width="550" alt="Screenshot 2024-05-03 at 19 19 56" src="https://github.com/firefly-iii/firefly-iii/assets/4399532/46cc1cda-5dec-48d5-9ec6-ef00053cc059">

#
#
#
**The contract itself**
<img width="1063" alt="Screenshot 2024-05-03 at 19 20 11" src="https://github.com/firefly-iii/firefly-iii/assets/4399532/02fcab2c-ac2f-49ea-99dc-6d09d356bea6">
#
#
#
**The automation**
<img width="1111" alt="Screenshot 2024-05-03 at 19 23 19" src="https://github.com/firefly-iii/firefly-iii/assets/4399532/601c823c-7385-4b6f-9967-e763641b48b0">

**Comment by poudenes** [comment]
But when I do a test I see the transaction. When I want execute the automation it doesn't see the latest transaction and nothing changed

**Comment by poudenes** [comment]
There is something different going on. 
Today 6,50 was taken from my back account 03-05-2024. But interest date is 01-05-2024
The whole transaction wasn't imported by FireFly Importer.

Did a manual import with 4 days back. It doesn't see the transaction at all....

**Comment by JC5** [comment]
Sorry, is this another problem altogether or the same problem or what?

**Comment by poudenes** [comment]
No I checked some more info and this issue can be closed. Will create a new one with my last post.
