### ISSUE TITLE
API Account Search all fields

### ISSUE THREAD

**Issue by mrahmadt** [firefly-iii/firefly-iii#8857]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When using API to search for account (/v1/search/accounts), it will be nice to be able to search in all fields (such as notes)

I'm using field notes to store account metadata that I need to process from my script (this way I can modify account metadata directly from FireFly-III UI 

### Solution

Search options similar to https://docs.firefly-iii.org/references/firefly-iii/search/

### What are alternatives?

I have to get all accounts and loop over each one to check if field notes contain or start with something to get specific accounts

**Comment by JC5** [comment]
Thanks for the suggestion! This will not be changed I'm afraid. But a *new* API endpoint will support it in the future (/v2/). Subscribe to https://github.com/firefly-iii/firefly-iii/issues/6301
