### ISSUE TITLE
A single Account constantly loses its Account NUmber / IBAN 

### ISSUE THREAD

**Issue by ypsilonkah** [firefly-iii/firefly-iii#8858]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have four accounts set up in Firefly. All are filled in with IBAN and BIC with different roles:
1. Default asset account
2. Savings account
3. Shared asset account
4. Savings account

Account No. 3 however keeps "forgetting" its IBAN every now and then (sometimes within a day). I reenter the IBAN and save the changes. Some time later, it's gone again.
How can I provide logs or debug output? Thanks!

### Debug information

Debug information generated at 2024-05-04 16:19:52 for Firefly III version **v6.1.15**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.15 / v2.0.14 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.6 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1074, base <span>#</span>83</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-05-03 22:00:00 (16 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-05-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-05-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0</td></tr></tbody></table>

### Expected behaviour

Once set up, the account should keep the assigned IBAN and not remove it.

### Steps to reproduce

1. Create account (shared savings, if it matters)
2. Enter IBAN
3. Wait
4. IBAN is gone

**Comment by JC5** [comment]
Thanks for opening an issue! 

I've never heard about something like this. This is impossible to debug unless you know what happens when you "wait". 

Can you replicate this in a consistent way?

**Comment by JC5** [comment]
Ah, now we're getting closer. The spaces / no spaces thing may be a hint, I'll check it out for sure.

**Comment by JC5** [comment]
Alright, so the next release of Firefly III will be way more strict with spaces. You may still lose IBANs when you update Firefly III, because it will filter out any duplicates it may find, spaces or not. Your logs will reflect this.

Either way, it should not be an issue going forward, but I would appreciate your feedback.
