### ISSUE TITLE
Import find duplicate where there is none

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#886]
Hello,

I'm currently testing the import of my old data from CSV files account after account.
I have a strange behavior as it find a duplicate transaction where there is none.
Here is the output of artisan
[duplicates.txt](https://github.com/firefly-iii/firefly-iii/files/1349245/duplicates.txt)

So I imported all the transactions between my regular account and Saving account 1. Then I do the same with saving account 2 and he finds duplicate transactions. I don't understand as nothing is the same (not the source account, not the amount, not the description)...

**Comment by JC5** [comment]
In the current version, the duplicate detector is a little too enthousiast. There's a fix that will repair this until the new release is out.

Find the file `firefly-iii/app/Import/Storage/ImportStorage.php` and replace the contents [with this code](https://raw.githubusercontent.com/firefly-iii/firefly-iii/develop/app/Import/Storage/ImportStorage.php).

That should make the false duplicates disappear again. 

I'm sorry you ran into this, and I hope this fixes it!

**Comment by MacPaille** [comment]
I replace the PHP code by the one you gave me but now I have this error:

>
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method FireflyIII\Import\Object\ImportBill::setAmount()
>

**Comment by JC5** [comment]
Mmm, that function exists.

- Could you get me the stack trace for that error from the log files? 
- Which version are you running?

**Comment by MacPaille** [comment]
Nevermind I was still in version 4.6.5. Upgraded to 4.6.6 now it works.

**Comment by MacPaille** [comment]
I tried the new version of the code and it seems the opposite. It creates a lot of duplicates now :)
As I was in version 4.6.5 I'm currently trying with the regular version of the importer to see how it works.

**Comment by JC5** [comment]
Make sure you enable debug logging, it will tell you what is happening.

**Comment by MacPaille** [comment]
Did my tests with debug mode on. When using regular code from the release I sees duplicate where they are not.
When using the code you gave me here it doesn't see any duplicates and create real duplicates in the DB...

Can you give me you email address so I can provide you the debug output? I don't want to add it here as it contains info on my transactions...

**Comment by JC5** [comment]
With instructions as to how to encrypt stuff:

https://firefly-iii.github.io/contact-information.html

**Comment by MacPaille** [comment]
I sent you an email with a link to download the debug files

**Comment by JC5** [comment]
Thanks for the file! I believe I have found the issue. You could update the file I pointed to again ([the code has been updated](https://raw.githubusercontent.com/firefly-iii/firefly-iii/develop/app/Import/Storage/ImportStorage.php)) but you are free to wait until this weekend, when I plan to release the new version.

Thanks for all your efforts! 👍

**Comment by MacPaille** [comment]
Thanks for the updated file, it works much better but I still have transactions not imported, I'll export again the debug logs :)

**Comment by JC5** [comment]
I look forward to them 👍

**Comment by MacPaille** [comment]
I updated the zip containing the logs, you can use the same link and password to download it again.
Import of my first account transactions is OK (I have one duplicate but it's a real one :) ) but when I import the second with some transfers with the first one I miss transactions because the final amount on the account is not correct.

**Comment by JC5** [comment]
I got it! 
The first file seems to import OK. It finds one duplicate transaction, which will not be imported. In your database, it is journal #2461. The amount is -10 and the date is 2010-07-23. The first file contains this transaction but your database has it already, and it is skipped.

In your file, search for this line:

```
production.ERROR: Cannot import row #2457
```

The second file also has two rows which are already imported based on the hash value (ie. another file has contained _the exact same row_ already).

```
[2017-10-05 05:43:20] production.INFO: Row #889 has already been imported.
[2017-10-05 05:43:33] production.INFO: Row #1174 has already been imported.
```

The second file also contains a lot of double transfers, which I cannot be sure if they are OK. Search for this line:

```
production.ERROR: There already is a transfer imported
```

The duplicate transfer seems to get triggered correctly (it really is double) but it could be that the import file is not detailed enough.

**Comment by MacPaille** [comment]
The first file it's normal I checked already it's a duplicate I entered in 2010 :) Not the time to correct it I just recreate it manually.
For the second file there should be duplicate inside. I'l have a closer look if I can see something...

**Comment by MacPaille** [comment]
I looked a bit deeper in the transactions and I'm facing a case where I have 2 times the same deposit transaction (same amount, same source account, same description) but for 2 different destination account.
Even if I select the correct Default import account (which then are 2 different accounts for each import) it sees it as a duplicate...
Would there be a way to avoid this? I think it's maybe due to that I still have duplicates...

**Comment by MacPaille** [comment]
I did more tests and found the solution. In my CSV I added a column to each line with the name of my account to which the CSV is linked. In the mapping part I mapped that name to my account. Then everything is working as expected.

That is strange as I also set the default import account so this should have had the same behavior no?

**Comment by JC5** [comment]
>  but for 2 different destination account.

Is the text of each destination account the same, or is it different? And is it storing your deposits as deposits or as transfers?

> That is strange as I also set the default import account so this should have had the same behavior no?

The default import account is used as a "fallback" but it is not used to see if the line is different. So if you have two files:

Account A:
```
description,date,amount,store
Groceries;2017-10-04,15.23,Walmart
```
Account B:
```
description,date,amount,store
Groceries;2017-10-04,15.23,Walmart
```

It will assume the lines are equal. This is annoying in your case but it cannot be helped, I'm afraid.

**Comment by MacPaille** [comment]
My previous tool exported the content of each account in a separate csv without any information on the source account. So when I import them I was expecting the default import account to link the csv content to that account.

That's for sure a specific case so adding manually a column were I set the account solved it.

Thanks for the support on this issue from the start :)
