### ISSUE TITLE
Empty webhooks page

### ISSUE THREAD

**Issue by mrahmadt** [firefly-iii/firefly-iii#8863]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Getting empty webhook page with no error in logs (new installation)

webhook enabled
cache cleared
logout/login again

$ grep -i hook .env
Some objects have room for an URL, like transactions and webhooks.
Firefly III supports webhooks. These are security sensitive and must be enabled manually first.
ALLOW_WEBHOOKS=true

$ php artisan cache:clear

   INFO  Application cache cleared successfully. 

![image](https://github.com/firefly-iii/firefly-iii/assets/957921/ffb3c26a-04a8-4348-88f3-14f5211f47c3)

### Debug information

Debug information generated at 2024-05-05 19:04:52 for Firefly III version **v6.1.15**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.15 / v2.0.14 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.6 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Asia/Riyadh + Asia/Riyadh</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2024-05-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-05-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0</td></tr></tbody></table>

### Expected behaviour

Able to create new webhook, view existing webhooks

**Comment by JC5** [comment]
Thanks for reporting this! I am aware of the issue. It will be fixed in the next release 👍

**Comment by mrahmadt** [comment]
Thanks @JC5

**Comment by mrahmadt** [comment]
Not sure if it's related, FYI, API call to [POST] /api/v1/webhooks will return html login page

happy to open another issue if it's another bug

**Comment by JC5** [comment]
You need to add `Accept: application/json` to your request.

**Comment by mrahmadt** [comment]
Thanks @JC5 , any plan when is the next release?
