### ISSUE TITLE
SQL Integrity constraint violation when inserting into budget_limits

### ISSUE THREAD

**Issue by HedgehogRidingAnOwl** [firefly-iii/firefly-iii#8867]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

This issue does not occur on the demo site. 

When attempting to set an amount for a budget I receive a 500 internal server error. 
`SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: budget_limits.repeat_freq (Connection: sqlite, SQL: insert into "budget_limits" ("budget_id", "start_date", "end_date", "amount", "transaction_currency_id", "updated_at", "created_at") values (1, 2024-05-01 00:00:00, 2024-05-31 00:00:00, 234, 1, 2024-05-08 08:23:39, 2024-05-08 08:23:39)) `, triggering in `vendor/laravel/framework/src/Illuminate/Database/Connection.php` on line 813.

After the error I deleted and reinitialized the database, which did not fix the issue. 

The specific window used to set the budget amount, in case my phrasing isn't specific enough.
![image](https://github.com/firefly-iii/firefly-iii/assets/35278972/0f063313-ce7f-43b9-b460-130fe5926d7c)

Appreciate any help

### Debug information

Debug information generated at 2024-05-08 08:22:37 for Firefly III version **v6.1.15**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.15 / v2.0.14 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.6 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*sqlite*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/New_York + America/New_York</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2024-05-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-05-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0</td></tr></tbody></table>

### Additional info

New installation using nginx on Ubuntu 20.04 following self-managed server installation instructions.

**Comment by JC5** [comment]
Mmmm. I'm having a hard time replicating this, even in SQLite. 

So you click on the (+), and then this happens? Do you have a amount set for another currency already, or none at all?

**Comment by HedgehogRidingAnOwl** [comment]
Clean, install with a single budget item. Budget item is completely vanilla with all fields left blank except the name. 

gif triggering the issue:
![firefox_S37jIkqQRH](https://github.com/firefly-iii/firefly-iii/assets/35278972/76ec0f76-6205-4158-899d-80292656e8d6)

**Comment by JC5** [comment]
Mmmm, I'm not sure how to replicate it but I think I know the cause. Since you're running a self-hosted installation you could edit the file yourself (see the commit just above my reply) and reinstate the database. It should then work as expected!

**Comment by HedgehogRidingAnOwl** [comment]
Made the suggested change and reinstated the DB, issue seems resolved. Thank you!
