### ISSUE TITLE
OAuth Client Redirect URL doesn't accept url's containing '_'.

### ISSUE THREAD

**Issue by guilhermenovais** [firefly-iii/firefly-iii#8868]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When trying to register an OAuth Client using an URL containing '_', the server responds with 422. There is no error displayed on the screen. The following error is printed to console.
![image](https://github.com/firefly-iii/firefly-iii/assets/61892041/957da9a3-ecb9-4e16-ad52-99c413b6d47f)

### Debug information

Debug information generated at 2024-05-08 14:23:58 for Firefly III version **v6.1.15**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.15 / v2.0.14 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.6 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1074, base <span>#</span>83</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Sao_Paulo + America/Sao_Paulo</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>*</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2024-05-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-05-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0</td></tr></tbody></table>

### Steps to reproduce

1. Open the Create Client dialog on OAuth screen;
2. Enter a URL containing the underscore character;
3. Click the Create button.

**Comment by JC5** [comment]
I can't replicate this. It works fine for me, and it works fine on the demo site as well. 

Can you see what the 422 contains, exactly?

**Comment by guilhermenovais** [comment]
Here are the request and the response. I forgot to mention that Firefly is running behind a reverse proxy.

## Raw Request
POST /oauth/clients HTTP/2
Host: firefly.test.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
X-Requested-With: XMLHttpRequest
X-CSRF-TOKEN: x-csrf-token
X-XSRF-TOKEN: x-xsrf-token
Content-Length: 98
Origin: https://firefly.test.com
DNT: 1
Connection: keep-alive
Cookie: google2fa_token=2fatoken; XSRF-TOKEN=token; laravel_token=laraveltoken
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
TE: trailers

{"errors":[],"name":"importer","redirect":"http://firefly_importer.test.com","confidential":false}

## Raw Response
HTTP/2 422 
server: openresty
date: Wed, 08 May 2024 17:51:35 GMT
content-type: application/json
cache-control: no-cache, private
x-frame-options: deny
content-security-policy: default-src 'none'; object-src 'none'; script-src 'unsafe-eval' 'strict-dynamic' 'nonce-Q6Ops0pwMJSLOV7wgu2iNw=='; style-src 'unsafe-inline' 'self'; base-uri 'self'; font-src 'self' data:; connect-src 'self' ; img-src 'self' data: 'nonce-Q6Ops0pwMJSLOV7wgu2iNw==' ; manifest-src 'self'; form-action 'self'
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
referrer-policy: no-referrer
x-permitted-cross-domain-policies: none
x-robots-tag: none
feature-policy: geolocation 'none'; midi 'none'; sync-xhr 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none'
set-cookie: XSRF-TOKEN=token; expires=Wed, 08 May 2024 19:51:35 GMT; Max-Age=7200; path=/; samesite=lax
set-cookie: firefly_session=session; path=/; httponly; samesite=lax
X-Firefox-Spdy: h2

**Comment by JC5** [comment]
Host names with an underscore in them are not valid as per RFC 1123. So it may work here and there but your mileage may vary. 

Try a dash instead of a underscore.
