### ISSUE TITLE
SQL Error Table link_types does not exist

### ISSUE THREAD

**Issue by Aquariu** [firefly-iii/firefly-iii#887]
Dear all,

Since earlier today, for unknown reasons, I got an exception when clicking on any transaction, either from one particular account view or from the Expense
```
 (3/3) QueryException

SQLSTATE[42S02]: Base table or view not found: 1146 La table 'firefly.link_types' n'existe pas (SQL: select * from `link_types` order by `name` asc)
```

I didn't do anything manually on the db. In firefly, I just added and applied a couple of simple rules.

What I did do however, was to create a Transfer, and then to delete it. 

The log has all the trace of the request. Do you wish to see it ?
I did check in the database though, and indeed, the table firefly.link_types does not exist.

I tried the following:
```
php artisan cache:clear
php artisan firefly:upgrade-database

```
neither helped. 
I there a way I can restore the lost table without loosing everything ?

Kind regards,

Olivier

PS: here's the complete trace as displayed by the "Whoops" page

> (3/3)                                         QueryException                                                                          SQLSTATE[42S02]:  Base table or view not found: 1146 La table 'firefly.link_types'  n'existe pas (SQL: select * from `link_types` order by `name` asc)
> --
> in Connection.php (line 647)
> at Connection->runQueryCallback('select * from `link_types` order by `name` asc', array(), object(Closure))in Connection.php (line 607)
> at Connection->run('select * from `link_types` order by `name` asc', array(), object(Closure))in Connection.php (line 326)
> at Connection->select('select * from `link_types` order by `name` asc', array(), true)in Builder.php (line 1705)
> at Builder->runSelect()in Builder.php (line 1690)
> at Builder->get(array('*'))in Builder.php (line 462)
> at Builder->getModels(array('*'))in Builder.php (line 446)
> at Builder->get()in LinkTypeRepository.php (line 107)
> at LinkTypeRepository->get()in TransactionController.php (line 166)
> at TransactionController->show(object(TransactionJournal), object(JournalTasker), object(LinkTypeRepository))
> at call_user_func_array(array(object(TransactionController), 'show'), array('tj' => object(TransactionJournal), object(JournalTasker), object(LinkTypeRepository)))in Controller.php (line 55)
> at Controller->callAction('show', array('tj' => object(TransactionJournal), object(JournalTasker), object(LinkTypeRepository)))in ControllerDispatcher.php (line 44)
> at ControllerDispatcher->dispatch(object(Route), object(TransactionController), 'show')in Route.php (line 203)
> at Route->runController()in Route.php (line 160)
> at Route->run()in Router.php (line 572)
> at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransactionController.php (line 54)
> at TransactionController->FireflyIII\Http\Controllers\{closure}(object(Request), object(Closure))in Pipeline.php (line 131)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Controller.php (line 97)
> at Controller->FireflyIII\Http\Controllers\{closure}(object(Request), object(Closure))in Pipeline.php (line 131)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Binder.php (line 55)
> at Binder->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Range.php (line 78)
> at Range->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in AuthenticateTwoFactor.php (line 70)
> at AuthenticateTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 53)
> at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
> at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
> at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
> at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
> at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
> at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Sandstorm.php (line 46)
> at Sandstorm->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
> at Pipeline->then(object(Closure))in Router.php (line 574)
> at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
> at Router->dispatchToRoute(object(Request))in Router.php (line 511)
> at Router->dispatch(object(Request))in Kernel.php (line 176)
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
> at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
> at Pipeline->then(object(Closure))in Kernel.php (line 151)
> at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
> at Kernel->handle(object(Request))in index.php (line 57)
> 

> (2/3)                                         PDOException                                                                          SQLSTATE[42S02]: Base table or view not found: 1146 La table 'firefly.link_types' n'existe pas
> --
> in PDOConnection.php (line 79)
> at PDOConnection->prepare('select * from `link_types` order by `name` asc')in Connection.php (line 319)
> at Connection->Illuminate\Database\{closure}('select * from `link_types` order by `name` asc', array())in Connection.php (line 640)
> at Connection->runQueryCallback('select * from `link_types` order by `name` asc', array(), object(Closure))in Connection.php (line 607)
> at Connection->run('select * from `link_types` order by `name` asc', array(), object(Closure))in Connection.php (line 326)
> at Connection->select('select * from `link_types` order by `name` asc', array(), true)in Builder.php (line 1705)
> at Builder->runSelect()in Builder.php (line 1690)
> at Builder->get(array('*'))in Builder.php (line 462)
> at Builder->getModels(array('*'))in Builder.php (line 446)
> at Builder->get()in LinkTypeRepository.php (line 107)
> at LinkTypeRepository->get()in TransactionController.php (line 166)
> at TransactionController->show(object(TransactionJournal), object(JournalTasker), object(LinkTypeRepository))
> at call_user_func_array(array(object(TransactionController), 'show'), array('tj' => object(TransactionJournal), object(JournalTasker), object(LinkTypeRepository)))in Controller.php (line 55)
> at Controller->callAction('show', array('tj' => object(TransactionJournal), object(JournalTasker), object(LinkTypeRepository)))in ControllerDispatcher.php (line 44)
> at ControllerDispatcher->dispatch(object(Route), object(TransactionController), 'show')in Route.php (line 203)
> at Route->runController()in Route.php (line 160)
> at Route->run()in Router.php (line 572)
> at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransactionController.php (line 54)
> at TransactionController->FireflyIII\Http\Controllers\{closure}(object(Request), object(Closure))in Pipeline.php (line 131)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Controller.php (line 97)
> at Controller->FireflyIII\Http\Controllers\{closure}(object(Request), object(Closure))in Pipeline.php (line 131)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Binder.php (line 55)
> at Binder->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Range.php (line 78)
> at Range->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in AuthenticateTwoFactor.php (line 70)
> at AuthenticateTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 53)
> at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
> at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
> at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
> at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
> at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
> at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Sandstorm.php (line 46)
> at Sandstorm->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
> at Pipeline->then(object(Closure))in Router.php (line 574)
> at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
> at Router->dispatchToRoute(object(Request))in Router.php (line 511)
> at Router->dispatch(object(Request))in Kernel.php (line 176)
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
> at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
> at Pipeline->then(object(Closure))in Kernel.php (line 151)
> at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
> at Kernel->handle(object(Request))in index.php (line 57)

> 1/3)                                         PDOException                                                                          SQLSTATE[42S02]: Base table or view not found: 1146 La table 'firefly.link_types' n'existe pas
> --
> in PDOConnection.php (line 77)
> at PDO->prepare('select * from `link_types` order by `name` asc', array())in PDOConnection.php (line 77)
> at PDOConnection->prepare('select * from `link_types` order by `name` asc')in Connection.php (line 319)
> at Connection->Illuminate\Database\{closure}('select * from `link_types` order by `name` asc', array())in Connection.php (line 640)
> at Connection->runQueryCallback('select * from `link_types` order by `name` asc', array(), object(Closure))in Connection.php (line 607)
> at Connection->run('select * from `link_types` order by `name` asc', array(), object(Closure))in Connection.php (line 326)
> at Connection->select('select * from `link_types` order by `name` asc', array(), true)in Builder.php (line 1705)
> at Builder->runSelect()in Builder.php (line 1690)
> at Builder->get(array('*'))in Builder.php (line 462)
> at Builder->getModels(array('*'))in Builder.php (line 446)
> at Builder->get()in LinkTypeRepository.php (line 107)
> at LinkTypeRepository->get()in TransactionController.php (line 166)
> at TransactionController->show(object(TransactionJournal), object(JournalTasker), object(LinkTypeRepository))
> at call_user_func_array(array(object(TransactionController), 'show'), array('tj' => object(TransactionJournal), object(JournalTasker), object(LinkTypeRepository)))in Controller.php (line 55)
> at Controller->callAction('show', array('tj' => object(TransactionJournal), object(JournalTasker), object(LinkTypeRepository)))in ControllerDispatcher.php (line 44)
> at ControllerDispatcher->dispatch(object(Route), object(TransactionController), 'show')in Route.php (line 203)
> at Route->runController()in Route.php (line 160)
> at Route->run()in Router.php (line 572)
> at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransactionController.php (line 54)
> at TransactionController->FireflyIII\Http\Controllers\{closure}(object(Request), object(Closure))in Pipeline.php (line 131)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Controller.php (line 97)
> at Controller->FireflyIII\Http\Controllers\{closure}(object(Request), object(Closure))in Pipeline.php (line 131)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Binder.php (line 55)
> at Binder->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Range.php (line 78)
> at Range->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in AuthenticateTwoFactor.php (line 70)
> at AuthenticateTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 53)
> at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
> at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
> at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
> at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
> at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
> at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Sandstorm.php (line 46)
> at Sandstorm->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
> at Pipeline->then(object(Closure))in Router.php (line 574)
> at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
> at Router->dispatchToRoute(object(Request))in Router.php (line 511)
> at Router->dispatch(object(Request))in Kernel.php (line 176)
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
> at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
> at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
> at Pipeline->then(object(Closure))in Kernel.php (line 151)
> at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
> at Kernel->handle(object(Request))in index.php (line 57)
>

**Comment by JC5** [comment]
As per [the upgrade instructions](https://firefly-iii.github.io/using-upgrading.html), please run the following commands.

```
php artisan migrate --env=production
php artisan firefly:upgrade-database
php artisan firefly:verify
```

That should fix it!

**Comment by Aquariu** [comment]
It did work :)
... although I have no idea why that table was gone in the first place. I upgraded to 4.6.5 before the week-end, starting from scratch, and... this was working fine.

Anyway, thanks for the easy solution!
