### ISSUE TITLE
Demo strangeness

### ISSUE THREAD

**Issue by Resonanz** [firefly-iii/firefly-iii#8882]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I want New Zealand dollars only. So I turn off all other currencies.

Then I look at transactions and they are being displayed in Euros !!!

The tick box settings are very odd btw. They should have a check, and the tick should show that the currency is enabled.

### Debug information

NA.

### Expected behaviour

NZD, not Euros.

### Steps to reproduce

Turn off all currencies except NZD.

Loot at symbol next to transactions. It is Euros.

**Comment by JC5** [comment]
Hey, thanks for opening an issue. I think there are some things to learn here:

- Changing the default currency does not change the currency of existing transactions.
- Changing the default currency does not change the default currency of existing accounts

In the current version of Firefly III, the default currency is used in the Y-axis of charts, even when the transactions or accounts displayed are in another currency. I hope to fix this in a new release.
