### ISSUE TITLE
Allow easily moving money between budgets

### ISSUE THREAD

**Issue by hermitgames** [firefly-iii/firefly-iii#8885]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like Firefly to allow moving money between budgets. To be clear, I do not mean addapting to Zero Based budgeting, but my budgets are a bit... fluid, during the month. Sometimes I need to move from a category to another, and I do have a  "whatever else" budget where I put my available budgeting money (separate from my total money) until I can be bothered to move it.

As of now, I need to open a calculator and start substracting from one budget and adding to another.

### Solution

It would allow moving money between budgets in a simple way.

### What are alternatives?

Making calculations outside of firefly and readjusting budgets.

**Comment by JC5** [comment]
This is a great idea, but I'm afraid you'll have to keep using your calculator for this.
