### ISSUE TITLE
Currency Exchange Rate

### ISSUE THREAD

**Issue by mrahmadt** [firefly-iii/firefly-iii#8886]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I can see we have Currency Exchange Rate API already defined at https://github.com/firefly-iii/firefly-iii/blob/34baea66a7e7d2e6b17082be725c501b5d0e1d12/app/Support/Http/Api/ExchangeRateConverter.php

### Solution

Can we export a route for it? I don't see it in API documentation https://api-docs.firefly-iii.org

**Comment by JC5** [comment]
The code is in place but it's way too soon to expose it in an API. 

Keep an eye on this issue: https://github.com/firefly-iii/firefly-iii/issues/6314
