### ISSUE TITLE
Debounce / Abort autocomplete requests

### ISSUE THREAD

**Issue by gthbusrr** [firefly-iii/firefly-iii#8888]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When creating a transaction, focusing on fields will trigger an _autocomplete_ request. However, since my server is slow, it'll take a second or two to complete. I usually just type in some keywords to the field and have it filter that way.

The problem is that the first request where `query=` is empty will complete AFTER my actual keyword filtered request where `query=keyword`.

### Debug information

Debug information generated at 2024-05-15 13:04:01 for Firefly III version **v6.1.15**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.15 / v2.0.14 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.6 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1074, base <span>#</span>83</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Toronto + America/Toronto</td></tr><tr><td>App environment</td><td>local, debug: true</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>redis</td></tr><tr><td>Default language and locale</td><td>en_GB + en_GB</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-05-15 14:09:39 (2 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-05-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-05-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0</td></tr></tbody></table>

### Expected behaviour

Debounce / abort previous autocomplete requests

### Steps to reproduce

1. Create transaction
2. Focus on field
3. Type something
4. You'll see filtered result in autocomplete
5. You'll lose filtered result and get unfiltered result

**Comment by JC5** [comment]
Sorry, I use a standard library that I can't really edit. There's not much I can do about this.

**Comment by gthbusrr** [comment]
@JC5 I'm not proficient in VueJs nor JS but I suspect the requests are triggered [here](https://github.com/firefly-iii/firefly-iii/blob/34baea66a7e7d2e6b17082be725c501b5d0e1d12/resources/assets/v1/src/components/transactions/AccountSelect.vue#L141). I think adding an `AbortController` signal to the axios call would be possible.

**Comment by JC5** [comment]
Yes, if I could keep track of all the previous requests. Sorry, this will not be fixed I'm afraid.
