### ISSUE TITLE
add rules active “no active” or "call XXX rules"

### ISSUE THREAD

**Issue by alexblair** [firefly-iii/firefly-iii#8889]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When setting rules, performance issues often arise due to the inability to perform regularization or complex logic. After consulting the help document, I adopted the rule groups approach for pre filtering to reduce the number of rule executions and improve efficiency.

However, currently when setting trigger conditions, strict and non strict mixing cannot be achieved, resulting in the inability to implement the following rule logic (for example, I tried to represent this logic with pseudocode, and the following syntax does not belong to any programming language)

if (case1===ture){
   case2  or  case3
}else{
   case 4
}

### Solution

For this, I hope to optimize the triggering conditions and actions of rules.
The routes that can be tried are:

**WAY 1:**
1. Allow strict and non strict mixing of rules, i.e. AND and OR parallelism. This approach is once and for all, but it may increase the complexity of program development.
2. 
**WAY 2:**
1. Allow **"no active"** or **"call XXX rules"** when setting up active
**No active:** Used for purely judging logical rules, such as exiting the remaining rules of this group if they meet the requirements of the rules.
**Call XXX rules:** This may be simpler, allowing for the invocation of existing rules and more direct implementation of rule processing.

**Comment by JC5** [comment]
Thanks for opening an issue. Your suggestions will not be implemented I'm afraid. 

If your use case regarding transaction processing is this complex, I suggest you use webhooks and implement the logic you need that way.

**Comment by JC5** [comment]
Sure, but processing is impossible because rules change transactions. Since it can't be predicted what and when rules change transactions, batch processing means transactions are skipped or processed when they shouldn't be.

**Comment by alexblair** [comment]
agree this.
 thanks  ^_^
