### ISSUE TITLE
Be right back message

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#889]
I was playing with the import of my transactions and when I tried to access my account I got this message "Be right back".
I restored my DB backup to start fresh and now I get this message right after login. Can you tell me how to debug this issue?

**Comment by JC5** [comment]
I believe your log files will contain a TokenMismatchException. Clear your cookies and run the following commands on the command line to clear Firefly's cache:

```
php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan twig:clean
php artisan view:clear
```

I believe the top command is sufficient but you never know.

**Comment by MacPaille** [comment]
This line gives me an error:  php artisan twig:clean
[ReflectionException]
  Method TwigBridge\Command\Clean::handle() does not exist

Now I can access my interface but when I click on Asset accounts I still get the be right back page...

**Comment by JC5** [comment]
That line is normal, it's a library that has not yet been upgraded.

What do the logs tell you in `storage/logs`?

**Comment by MacPaille** [comment]
Just gives me lines when I launch the clean commands. Nothing when I access the website.
[log.txt](https://github.com/firefly-iii/firefly-iii/files/1351649/log.txt)

**Comment by JC5** [comment]
OK, what happens when you [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) and run this on the command line?

```
php artisan up
```

Is there more info in the logs when you get the BRB error?

**Comment by MacPaille** [comment]
Here is the debug logging. Anything useful for you? Only thing I did is clicking on Asset accounts
[laravel-2017-10-03.log](https://github.com/firefly-iii/firefly-iii/files/1351692/laravel-2017-10-03.log)

I also get this on the browser:
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/0a/7e/0a7ee6429aec629ca6e876b8df5202af67bb055e): failed to open stream: No such file or directory

**Comment by JC5** [comment]
Something seems to be wrong with the file permissions. Is the folder where Firefly is installed editable / writable by the webserver?

It also seems you haven't yet configured the email server but that's a secondary problem.

**Comment by MacPaille** [comment]
Much better :)

My bad I forgot to set the rights correctly using
`sudo chown -R www-data:www-data firefly-iii`
`sudo chmod -R 775 firefly-iii/storage`

As the upgrade procedure creates a new folder and you move it to the place of the other, I think this part should be done at every upgrade (and not only if you get errors).

My bad I didn't paid enough attention.

**Comment by JC5** [comment]
No problem, I'm glad it works now! 👍
