### ISSUE TITLE
Data Importer: GoCardless API base URL change

### ISSUE THREAD

**Issue by simon-77** [firefly-iii/firefly-iii#8892]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I use the firefly-iii data-importer with GoCardless provider (previousely Nordigen) and got a warning E-Mail yesterday, that I am still using the old base URL for their API.

### Debug information

Docker:
    image: fireflyiii/data-importer:version-1.5.2

### Expected behaviour

Data-importer will use the new base URL for GoCardless:
`https://bankaccountdata.gocardless.com/api/v2/.`

### Steps to reproduce

- use firefly-iii data-importer via GoCardless service
- log-in with GoCardless account
- import some data
- on the next day, received e-mail from GoCardless to GoCardless account e-mail subject: _Actione required: Bank account data API base url change_

### Additional info

E-Mail from 8. March 2024, informing about Base URL change:

> Dear user,
> 
> The planned URL change we have initially informed you of several weeks ago is proceeding on 26.03.2024.
> Please make sure the base URL of your integration with the GoCardless Bank Account Data API is https://bankaccountdata.gocardless.com/api/v2/ 
> While this date may include some buffer, we cannot guarantee older URLs will work past this date.
> 
> If you are using any of our 4 official open-source libraries, they have been updated, published and can be found here:
> https://developer.gocardless.com/bank-account-data/libraries
> Take note that we take no responsibility for updating any unofficial or custom libraries. Check their code or contact the maintainer if you are in doubt.
> 
> Additionally, subscribe to our statuspage if you wish to be informed about any upcoming maintenances:
> https://status.nordigen.com/
> 
> Please reply to this email should you have any questions, and we will be happy to assist you within office hours.
> 
> Best regards,
> Bank Account Data Team
>

**Comment by JC5** [comment]
The URL was changed 3 months ago.

https://github.com/firefly-iii/data-importer/commit/a8a1ac46c9e4960c6d2bd4526fe6c7348d88b2cb
