### ISSUE TITLE
API: `reconciled: false` does not have precedence

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#8893]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Dealing with changes to reconciled transactions using the API is a bit unexpected.

When editing a reconciled transaction via `PUT api/v1/transactions/1234`, as soon as the request has any "protected" field the API call will fail with an error that the transaction is reconciled.  This is true even when `reconciled: false` is submitted in the request, or if the "protected" field value is not changed.

### Debug information

Demo Page

### Expected behaviour

1. When the request contains `reconciled: false`, it should un-reconcile the transaction and then proceed any changes made in the same request. Currently, a `reocnciled: false` request is needed, followed by a separate request to actually update any fields.
2. Even for reconciled transactions, if the request contains "restricted" fields such as `amount`, but that field is not changed compared to the stored value, the request should not fail but proceed to update any other fields if applicable.

### Additional info

Looking at the web page, all fields seem to be filtered out of the update request when the transaction is reconciled to not fail according to the second point above. If this is the way you intend it to be, then consider this request only for the first point above (as this is quite annoying), and I'll implement something similar like the web page in the app!

**Comment by JC5** [comment]
I'll check it out, thanks!

**Comment by JC5** [comment]
Assuming you want to update protected fields.

- If you submit `"reconciled": true` to any unreconciled transaction, that will be the last time you can edit it. After that, it will complain.
- Submitting `"reconciled": false` allows you to overrule this, and your updates will be saved. The transaction will be unreconciled as well.
- Even if you leave the value the same, Firefly III will complain about trying to update reconciled transactions. The validator can't check existing values, i have enough spaghetti code as it is.
