### ISSUE TITLE
Allow selecting a full year more easily

### ISSUE THREAD

**Issue by SteffoSpieler** [firefly-iii/firefly-iii#8896]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'd love to have a full-year selection in the date range selection of firefly. Currently, there is just an option for the current year.

### Solution

Add a button (like the "custom range") just for "Full Year". There you can then select one of the latest years (current Year, current Year -1, current Year -2, ..., <Number Input Field>).

### What are alternatives?

Selecting the first day of the first month of the desired year in the "custom range" selection, then the last day of the last month of the desired year.

**Comment by JC5** [comment]
Good idea!

Something to remember for https://github.com/firefly-iii/firefly-iii/issues/6299, but don't hold your breath.
