### ISSUE TITLE
Import shows following error: Cannot change source account of journal #* because no asset account with name * exists

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#890]
I did not enable debug logging since I am running it on a RPi2 and it really slows my system down. Is there something to worry about? should I re-import everything with debug log on? 

```
[...]
[2017-10-03 10:25:40] production.WARNING: There already is an account named "(no name)" of type "Expense account".
[2017-10-03 10:25:44] production.WARNING: There already is an account named "(no name)" of type "Expense account".
[2017-10-03 10:25:45] production.ERROR: Cannot change source account of journal #2284 because no asset account with name "Dirk Rossmann GmbH" exists.
[2017-10-03 10:25:47] production.WARNING: There already is an account named "(no name)" of type "Expense account".
[2017-10-03 10:25:49] production.WARNING: There already is an account named "(no name)" of type "Expense account".
[...]
```

FYI: running the latest develop branch

**Comment by Aquariu** [comment]
My understanding is that this is perfectly normal. 

The expense account is indeed already created by a previous import or any transaction creation. It's already there so doesn't need to be created again for each transaction creation. 

The check needs to happen, though, because if the account didn't exist (like for the first ever transaction creation) then it would need to be created before the transaction.

**Comment by gavu** [comment]
But why does it check for an `asset account` named like the shop I bought some stuff from?

This happens with most, if not all, the expense accounts.

I renamed the transaction using the following rule:
- Name:  "Dirk Rossmann GmbH"
- Description contains: "rossmann"
- Set destination account to: "Dirk Rossmann GmbH"
- Set source account to: "Dirk Rossmann GmbH"
- Add category: "Home"
- Add tat: "Rule: Dirk Rossmann GmbH"

(I added source and destination account information because I received some refunds)

**Comment by JC5** [comment]
If the transaction in question is a withdrawal or a transfer, the action "set source account to" will only accept existing asset accounts.

If the transaction in question is a deposit or a transfer, the action "set destination account to" will only accept existing asset accounts.

Your rule should be split in two: one for deposits and one for withdrawals. Use the "transaction type is" trigger.

**Comment by gavu** [comment]
Now I understand, thanks for the explanation. Because I have about 40 rules, I would hate it to double the mount. Is it OK if I leave it like this? will there be any inconsistencies / failed imports / ignored transactions?

**Comment by JC5** [comment]
It's no problem. The other action(s) will fire just fine. It will give you the error and continue with the next action.

**Comment by gavu** [comment]
Awesome, thanks!

**Comment by JC5** [comment]
Having forty rules does explain the lack of speed though 😉

**Comment by gavu** [comment]
I like a clean/ordered system. I rename all of my normal/daily transactions via rules to find them easier.
