### ISSUE TITLE
Bulk remove multiple expense accounts 

### ISSUE THREAD

**Issue by JcMinarro** [firefly-iii/firefly-iii#8903]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I have multiple credit cards that I use to buy.
Every supermarket (Even the same supermarket on different days) uses different descriptions for the transactions. 
I have some rules on the importer and in Firefly rules section to define the proper "expense account", but it can't always be done. 
Periodically, I post-process automatically imported transactions to ensure they have the proper expense account, budget, category, and so on. 
Then, from time to time, I got a long list of "never used expense accounts" within the "expense accounts section" that I needed to remove one by one. It is a bit of a "tedious process" because for every account I need to confirm the action. I understand this process needs a double-check verification process to not remove important data, and I like it is already implemented that way. But I would like to be able to select multiple accounts and perform remove actions over them (Of course, with the double-check verification)

![Screenshot from 2024-05-20 12-21-20](https://github.com/firefly-iii/firefly-iii/assets/4047514/7a4716a2-278f-4c9e-8c76-baeaff04ec41)

Related suggestion: https://github.com/firefly-iii/firefly-iii/issues/5168

### Solution

Provide a multi-selection option, similar what Firefly already have on the "Transactions section", allowing to remove the selected accounts.
![Screenshot from 2024-05-20 12-23-01](https://github.com/firefly-iii/firefly-iii/assets/4047514/8b6eaa30-53c3-4be7-aa2c-3a7019d0cecd)

**Comment by JC5** [comment]
This option already exists, and can be found on the last tab of your Profile page (`/profile`).

Be careful which button you press!

**Comment by JcMinarro** [comment]
Ohhhh Shit!!!!
I accidentally press on "Remove all expense accounts" :face_exhaling: :facepalm: 
Just after seeing no confirmation dialog was shown an immediately went to portainer to stop my containers.
Hopefully only ~2000€ transactions has been removed :sweat_smile: 

I just opened a DB browser and I can see transactions/accounts are marked as "deleted_at", but they seem are not totally removed. 
Am I right?
I can identify which rows have been removed after clicking this button because the `deleted_at` is right from today, and I didn't delete anything else today.  Am I right?

If I want to recover them, should I only "remove" the `deleted_at` field for every row on `transaction_journals`, `transactions` and `accounts` table?
Is there anything else I would need to do to recover them?

**Comment by JcMinarro** [comment]
Ok.
I was able to recover transactions by updating the `deleted_at` field of the following tables:
- `transaction_journals`
- `transactions`
- `accounts`
- `attachments`
- `audit_log_entries`
- `journal_meta`
- `notes`
- `transaction_groups`

In my case transactions were deleted after `2024-05-20 12:36:24.000`, so I used the following SQL 
```
UPDATE firefly.transaction_groups
	SET deleted_at=NULL
	WHERE deleted_at>'2024-05-20 12:36:24.000';
UPDATE firefly.transactions
	SET deleted_at=NULL
	WHERE deleted_at>'2024-05-20 12:36:24.000';
UPDATE firefly.accounts
	SET deleted_at=NULL
	WHERE deleted_at>'2024-05-20 12:36:24.000';
UPDATE firefly.attachments
	SET deleted_at=NULL
	WHERE deleted_at>'2024-05-20 12:36:24.000';
UPDATE firefly.audit_log_entries
	SET deleted_at=NULL
	WHERE deleted_at>'2024-05-20 12:36:24.000';
UPDATE firefly.journal_meta
	SET deleted_at=NULL
	WHERE deleted_at>'2024-05-20 12:36:24.000';
UPDATE firefly.transaction_groups
	SET deleted_at=NULL
	WHERE deleted_at>'2024-05-20 12:36:24.000';
```

Hope it will help anyone who removed transactions by error
