### ISSUE TITLE
Dashboard shows "firefly.bills_paid"

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#891]
Hey,

I found a small thing:
The title tag says "firefly.bills_paid" on the Dashboard (for _bills to pay_)
![firefly-text-error-1](https://user-images.githubusercontent.com/31184224/31122932-248c698e-a83e-11e7-8f94-5d7b5b56a1a6.png)

I checked this on the demo-page. It is there too.

Greetings
Nico

**Comment by JC5** [comment]
Thanks! I've updated the code and the next release should include the actual text. The demo site will be updated momentarily.
