### ISSUE TITLE
Dashboard shows "firefly.left_to_spend_per_day"

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#892]
Hey,

I found a small thing:
The title tag says "firefly.left_to_spend_per_day" on the Dashboard (for _left to spend_)
![firefly-text-error-2](https://user-images.githubusercontent.com/31184224/31123039-9553f7b8-a83e-11e7-9bcb-212cb05a63f0.png)

I checked this on the demo-page. It is there too.

Greetings
Nico

**Comment by JC5** [comment]
Thanks! I've updated the code and the next release should include the actual text. The demo site will be updated momentarily.
