### ISSUE TITLE
Deleted categories still appears in "Edit selected in bulk" mode

### ISSUE THREAD

**Issue by theRolento** [firefly-iii/firefly-iii#8924]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Deleted categories appears in "Edit selected in bulk" mode, in the category field.
If you confirm a deleted category on the transaction, the category is then created again (it reappears in \categories list)

### Debug information

Wrong debug my bad

### Expected behaviour

Deleted categories should not appear in the field by autocomplete

### Steps to reproduce

1. Create a category
2. Delete the created category
3. Go edit in bulk a transaction
4. Check "category" field

### Additional info

![immagine](https://github.com/firefly-iii/firefly-iii/assets/74258012/85b63c93-fc25-422d-9a4d-939d666603fa)
![immagine](https://github.com/firefly-iii/firefly-iii/assets/74258012/1f9e5e99-a993-4517-bf05-52fe82d00141)
![immagine](https://github.com/firefly-iii/firefly-iii/assets/74258012/1b339b8b-9cf6-4bf5-9078-d2e92af22394)
![immagine](https://github.com/firefly-iii/firefly-iii/assets/74258012/75d53fc4-c03a-41a5-a3df-13867829e2bc)

**Comment by JC5** [comment]
Yes, these lists are cached in your browser. I can't prevent this from happening, sorry.

**Comment by theRolento** [comment]
> Yes, these lists are cached in your browser. I can't prevent this from happening, sorry.

Understood
