### ISSUE TITLE
Converting deposit to transfer can set incorrect transaction currency

### ISSUE THREAD

**Issue by avee87** [firefly-iii/firefly-iii#8927]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have a use case when I convert a bank-imported transaction to a transfer from a different currency.
However, when I do that in Firefly via "convert to transfer" it keeps the transaction currency as receiving account rather than changing it to source account currency with optional "foreign amount".

### Debug information

Reproduced on demo instance, no debug there

### Expected behaviour

Converted transfer should have source account currency

### Steps to reproduce

1. Create a deposit on account A (GBP)
2. Open the transaction and click "Convert to transfer"
3. Set source account to account B (EUR)
4. Observe the transaction now being in GBP with no way to change it to EUR->GBP

Example transaction on demo instance: https://demo.firefly-iii.org/transactions/show/469

**Comment by JC5** [comment]
Nice find. I'll, pick it up!

For now, you can fix this by reselecting the "Checking account" from the drop down, after which it will change GBP to EUR correctly, and require you to enter an amount in GBP.
