### ISSUE TITLE
Reconciliation does not include transactions on the last day of month-end

### ISSUE THREAD

**Issue by yong-s** [firefly-iii/firefly-iii#8937]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Today, when I was reconciling on the last day of the month, I selected May 1-31, and when I clicked on Start Reconciliation, I realized that the transactions on the 31st were not counted, and when I selected May 1-June 1 and clicked on Start Reconciliation, the records on the 31st were counted!

### Debug information

Debug information generated at 2024-05-31 20:25:22 for Firefly III version **v6.1.16**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.16 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.6 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1086, base <span>#</span>83</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Asia/Shanghai + Asia/Shanghai</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>redis</td></tr><tr><td>Default language and locale</td><td>zh-CN + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-05-30 16:00:00 (20 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr>

### Expected behaviour

When I was reconciling on the last day of the month today, I selected May 1-31, and when I clicked on Start Reconciliation, I wanted the transactions from the 31st to be calculated in

### Steps to reproduce

1.Asset accounts Select an account
2.Click to reconcile this account
3.Select dates May 1-31 to begin reconciliation

### Additional info

The record that was not counted was a transfer record from that account to another account.

**Comment by JC5** [comment]
What do you mean with "not counted"?

**Comment by yong-s** [comment]
> What do you mean with "not counted"?
Transactions recorded on May 31 were not included in the reconciliation period, resulting in significant differences after reconciling the data

**Comment by JC5** [comment]
I can't replicate this, sorry. All transactions are present and accounted for.

**Comment by yong-s** [comment]
> The record that was not counted was a transfer record from that account to another account.
I found that only the records of such transfers were not counted, the others for that day were.
I will look at it again at the end of next month when I reconcile.
thank u！
