### ISSUE TITLE
Asset account overview lists IBAN under Account number

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#894]
in asset account details, IBAN and account number are separate fields

**Comment by JC5** [comment]
That’s by design. It shows either the IBAN or the account number, whichever is present. I believe it prefers the IBAN over the account number.

**Comment by gavu** [comment]
It does. I have both entered. Just an idea, maybe change the headers to "Account number/IBAN" or something? I thought it was a bug

**Comment by JC5** [comment]
I'm not a fan of the "double header", so I think I'm going to leave it like this. After all, an IBAN is an account number too.

Thanks for reporting, once again. I'm pretty sure you're record holder now ;)
