### ISSUE TITLE
API v2 documentation missing previously documented endpoints

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#8946]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

With the recent api documentation update to v2.1.0 with FF3 v6.1.6, a ton of endpoint documentation had been removed - basically everything except `autocomplete` endpoints. As the features are still in the code, I guess this is just a documentation issue.

### Debug information

-

### Additional info

Also pretty obvious on the swagger site: https://api-docs.firefly-iii.org/?urls.primaryName=2.1.0%20(v2)#/

**Comment by JC5** [comment]
Yes I know, I'm working on it. Since these endpoints aren't released or final, please stay tuned.
