### ISSUE TITLE
To have a rule triggered both on create AND on update

### ISSUE THREAD

**Issue by fabianonetto** [firefly-iii/firefly-iii#8948]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

- I would like to have the option to create a rule that runs is triggered when a transaction is created AND when it is updated. It only allows to select 1 option as of now

### Solution

To replace the current dropdown with a couple of checkboxes and adjust the rule engine 
![image](https://github.com/firefly-iii/firefly-iii/assets/15900163/1bc9e26a-9da4-44ff-b203-a9ee2d0bbe80)

### What are alternatives?

To create 2 rules with the same conditions and actions with different triggers

**Comment by JC5** [comment]
No, this will stay as it is due to database limitations. Sorry.
