### ISSUE TITLE
Attached file while editing

### ISSUE THREAD

**Issue by Elmagenta** [firefly-iii/firefly-iii#8953]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When you open a transaction to modify it there is no way to see if there is already an attached file to it you get only the prompt to upload a file that will override the one who is already in the transaction.

### Solution

Add the ability to see if there is already an attached file to a transaction while you are modifying it. 

### What are alternatives?

Add a paper clip icon like the one on the rows on Expenses to the Transactions under Asset Account

### Additional context

I found myself in the situation of checking all the transactions on one of my asset account and i was not seeing any paper clip like the ones on the Expenses tab. This got me thinking that no one of my attached file was saved and i reuploaded some of them, discovering later that it's just not shown neither on the modifying page nor on the transaction list of the asset account but the files are actually uploaded.

**Comment by JC5** [comment]
Good idea!

I'll remember this for https://github.com/firefly-iii/firefly-iii/issues/6304 :)
