### ISSUE TITLE
Wrong calculation of transaction without category

### ISSUE THREAD

**Issue by anarion80** [firefly-iii/firefly-iii#8954]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When showing transactions without category for a current month, the right hand side pane does not seem to show the correct number and total for those transactions. The previous months data seem to be correct though:

![firefly_without_category](https://github.com/firefly-iii/firefly-iii/assets/2185791/84a123d9-aeaf-4bbc-beff-ab3a13f25fb9)

This is all for the same source account, different destination accounts

### Debug information

Debug information generated at 2024-06-05 10:51:33 for Firefly III version **v6.1.16**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.16 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.6 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1086, base <span>#</span>83</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Warsaw + Europe/Warsaw</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 2</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-05-01 09:19:10</td></tr><tr><td>Session end</td><td>2024-05-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0</td></tr></tbody></table>

### Expected behaviour

I would expect the number of transactions for the given example would be 20, and the total would be -1933,59

### Steps to reproduce

1. Go to Classification/Categories
2. Click on Without a category
3. Click on current/last month

**Comment by JC5** [comment]
Thanks for reporting!

First, browse to `/flush`, then try again. The information is cached, so that could be it.

**Comment by anarion80** [comment]
Hello. Flushed and unfortunately no change.

**Comment by anarion80** [comment]
However!

When I select current month (so June), where I have no transactions, the number and totals are correct!:
![image](https://github.com/firefly-iii/firefly-iii/assets/2185791/0e1ce5ef-7ee6-45bc-99cf-7dc22c0f8632)

So looks like perhaps the calculation is off by a month?
