### ISSUE TITLE
Weird line appears above the UI when clicking on matching transactions for a rule

### ISSUE THREAD

**Issue by avee87** [firefly-iii/firefly-iii#8958]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

<img width="230" alt="Screenshot 2024-06-07 at 17 11 06" src="https://github.com/firefly-iii/firefly-iii/assets/6134677/532d3e62-5c89-4d2f-b00d-8399967b8c17">

### Debug information

Reproduced on demo instance, no debug there

### Steps to reproduce

1. Go to the list of rules
2. Click on matching transactions button (beaker)
3. Observe

Here's a permalink to demo instance with repro: https://demo.firefly-iii.org/search?search=description_is%3A%22Some+random+description+bla+bla%22+amount_is%3A%222321%22+destination_account_is%3A%22Cafe+Central%22&rule=2

**Comment by JC5** [comment]
That looks like forgotten debug information. Thanks for spotting it!
