### ISSUE TITLE
Deleting transactions from accounts/show/*/all returns to dashboard

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#896]
... instead of accounts/show/*/all

**Comment by JC5** [comment]
Most, if not all delete routines will do this when they return to a `/show/` URL because in most cases, that URL is invalid. I'll try to fix it.

**Comment by gavu** [comment]
Got it, also wanted to ask about deleting transactions from within tag-related pages, but this would explain the redirect in general. Thanks

**Comment by JC5** [comment]
OK, I've pushed something for the next release that will make sure that Firefly III will properly refer back to the account or tag page if possible. If the previous page is deleted (such as when you delete a transaction from the `/transactions/show` it will still refer back to the index.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
