### ISSUE TITLE
Account total for a period shows the grand total 

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#8967]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I find this confusing. Example: the Cafe Central expense account. The default (one month) view (https://demo.firefly-iii.org/accounts/show/17) shows the grand total, the same as the "All" view (https://demo.firefly-iii.org/accounts/show/17/all).

![image](https://github.com/firefly-iii/firefly-iii/assets/226712/3fa2207e-c288-4623-9b12-918472e237e3)

### Debug information

Not available on the demo app

### Expected behaviour

The one-month view shows the monthly total (€36.43 in this case)

**Comment by JC5** [comment]
It shows the balance, yes. All account views show the account balance. This is not a bug :)

**Comment by halilim** [comment]
I guess I expected to see the total for the period :) I noticed that there are monthly totals on the right-side panel in month boxes, that should cover the monthly use case.

Oh, and maybe I thought the search results and account details were the same and recalled that I have a [User](https://chromewebstore.google.com/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld) script for adding it - I might suggest this as a feature in the future:

![image](https://github.com/firefly-iii/firefly-iii/assets/226712/3c57ab48-9e9f-4ec8-bf34-57926befc7be)
