### ISSUE TITLE
500 when editing transactions

### ISSUE THREAD

**Issue by stuzer05** [firefly-iii/firefly-iii#8968]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

```sql
SQLSTATE[42703]: Undefined column: 7 ERROR: column tags.zoomLevel does not exist LINE 1: ...latitude", "tags"."longitude" as "tag_longitude", "tags"."zo... ^ HINT: Perhaps you meant to reference the column "tags.zoomlevel". (Connection: pgsql, SQL: select "transaction_groups"."id" as "transaction_group_id", "transaction_groups"."user_id" as "user_id", "transaction_groups"."user_group_id" as "user_group_id", "transaction_groups"."created_at" as "created_at", "transaction_groups"."updated_at" as "updated_at", "transaction_groups"."title" as "transaction_group_title", "transaction_groups"."created_at" as "group_created_at", "transaction_groups"."updated_at" as "group_updated_at", "transaction_journals"."id" as "transaction_journal_id", "transaction_journals"."transaction_type_id", "transaction_journals"."description", "transaction_journals"."date", "transaction_journals"."order", "transaction_types"."type" as "transaction_type_type", "source"."id" as "source_transaction_id", "source"."account_id" as "source_account_id", "source"."reconciled", "source"."amount" as "amount", "source"."transaction_currency_id" as "currency_id", "currency"."code" as "currency_code", "currency"."name" as "currency_name", "currency"."symbol" as "currency_symbol", "currency"."decimal_places" as "currency_decimal_places", "source"."foreign_amount" as "foreign_amount", "source"."foreign_currency_id" as "foreign_currency_id", "foreign_currency"."code" as "foreign_currency_code", "foreign_currency"."name" as "foreign_currency_name", "foreign_currency"."symbol" as "foreign_currency_symbol", "foreign_currency"."decimal_places" as "foreign_currency_decimal_places", "destination"."account_id" as "destination_account_id", "categories"."id" as "category_id", "categories"."name" as "category_name", "budgets"."id" as "budget_id", "budgets"."name" as "budget_name", "tags"."id" as "tag_id", "tags"."tag" as "tag_name", "tags"."date" as "tag_date", "tags"."description" as "tag_description", "tags"."latitude" as "tag_latitude", "tags"."longitude" as "tag_longitude", "tags"."zoomLevel" as "tag_zoom_level", "source_account"."name" as "source_account_name", "source_account"."iban" as "source_account_iban", "source_account_type"."type" as "source_account_type", "dest_account"."name" as "destination_account_name", "dest_account"."iban" as "destination_account_iban", "dest_account_type"."type" as "destination_account_type" from "transaction_journals" left join "transaction_groups" on "transaction_journals"."transaction_group_id" = "transaction_groups"."id" left join "transactions" as "source" on "source"."transaction_journal_id" = "transaction_journals"."id" and "source"."amount" < 0 left join "transactions" as "destination" on "destination"."transaction_journal_id" = "transaction_journals"."id" and "destination"."amount" > 0 left join "transaction_types" on "transaction_types"."id" = "transaction_journals"."transaction_type_id" left join "transaction_currencies" as "currency" on "currency"."id" = "source"."transaction_currency_id" left join "transaction_currencies" as "foreign_currency" on "foreign_currency"."id" = "source"."foreign_currency_id" left join "category_transaction_journal" on "category_transaction_journal"."transaction_journal_id" = "transaction_journals"."id" left join "categories" on "category_transaction_journal"."category_id" = "categories"."id" left join "budget_transaction_journal" on "budget_transaction_journal"."transaction_journal_id" = "transaction_journals"."id" left join "budgets" on "budget_transaction_journal"."budget_id" = "budgets"."id" left join "tag_transaction_journal" on "tag_transaction_journal"."transaction_journal_id" = "transaction_journals"."id" left join "tags" on "tag_transaction_journal"."tag_id" = "tags"."id" left join "accounts" as "source_account" on "source_account"."id" = "source"."account_id" left join "account_types" as "source_account_type" on "source_account_type"."id" = "source_account"."account_type_id" left join "accounts" as "dest_account" on "dest_account"."id" = "destination"."account_id" left join "account_types" as "dest_account_type" on "dest_account_type"."id" = "dest_account"."account_type_id" where "transaction_journals"."user_id" = 1 and "transaction_journals"."user_id" is not null and "transaction_groups"."deleted_at" is null and "transaction_journals"."deleted_at" is null and "source"."deleted_at" is null and "destination"."deleted_at" is null and "transaction_types"."type" in (Withdrawal, Deposit, Transfer, Reconciliation) and "transaction_journals"."id" in (2848, 1761) and "transaction_journals"."deleted_at" is null order by "transaction_journals"."date" desc, "transaction_journals"."order" asc, "transaction_journals"."id" desc, "transaction_journals"."description" desc, "source"."amount" desc)

This error occured in file /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 813 with code 42703.
```

### Debug information

Debug information generated at 2024-06-12 10:11:41 for Firefly III version **vdevelop/2024-06-10**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>develop/2024-06-10 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.7 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1096, base <span>#</span>84</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + Europe/Kiev</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 2</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-06-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-06-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36</td></tr></tbody></table>

### Steps to reproduce

![image](https://github.com/firefly-iii/firefly-iii/assets/23124682/462b4190-8db2-4ce2-bcc8-bd0e9a043837)

**Comment by JC5** [comment]
Weird. Does the column exist in your database?

**Comment by stuzer05** [comment]
> Weird. Does the column exist in your database?

Yeah. I've migrated from mariadb to posgres not so long ago. Column is present and named in lowercase `zoomlevel`

**Comment by JC5** [comment]
There you go then. Change it into a capital L and you should be fine.
