### ISSUE TITLE
Rules: how to apply to "everything"?

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#897]
Currently, via web-interface, I can only apply to a limited time span `The start date must be a date after 2016-12-31.`

Is it possible to apply rules via terminal? to go around timeout issues?

**Comment by JC5** [comment]
The start date is based on the most early transaction, so it should not be necessary to go for an earlier date. If you login and logout, it might be updated (in case you have transactions that are from before this date).

**Comment by gavu** [comment]
Logout/Logout worked, I now have the first transaction as a start date, thanks

**Comment by gavu** [comment]
The rules now show the correct starting date but I cannot run the second rule:
`Maximum execution time of 300 seconds exceeded`

Right now, I only have 2 possibilities
1. Restart everything, create the rules *before* importing the data
- what happens if I create or edit rule? which would have to run through all the transactions?
2. Extending the timeout to... 3000 seconds?
- not sure how my RPi would handle this, I could give it a try

**Comment by JC5** [comment]
If the rule times out it'll be stopped somewhere half-way. It's hard to say where exactly.

I suggest configuring your installation to have no timeout (php.ini) and run the rule again.

A command line option for rules is possible but you're pushing it. The next thing that's going to happen is that you run out of memory.

**Comment by gavu** [comment]
true, I changed the timeouts for apache and php to 3000, until now, all rule are working as expected. Anyway, this is an issue only when adding new rules or editing them, so no issues for normal uses.

thanks!
