### ISSUE TITLE
Missing translations in search

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#899]
There are not translated strings "Query" and "Search" on: https://firefly-iii.nder.be/search?q=&search=

BTW, transaction links are impossible to correctly translate into Polish. We have three different ending for verbs depending on noun's gender. Unfortunately "transfer" has different gender than "withwdrawal" or "deposit" 😞

**Comment by JC5** [comment]
I've merged the PR, thanks!

As for the translations, that can't be helped I'm afraid. I'll have to find out how (if) other tools do this, such as JIRA.
