### ISSUE TITLE
404 importer documentation page

### ISSUE THREAD

**Issue by Johnnyyr** [firefly-iii/firefly-iii#8996]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The https://docs.firefly-iii.org/data-importer/ pag runs in to 404.

### Debug information

404

**Comment by JC5** [comment]
Where did you find the link?
