### ISSUE TITLE
[Feature Request] Login with External OAuth2 Support

### ISSUE THREAD

**Issue by chez14** [firefly-iii/firefly-iii#8997]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Since we selfhost many things, password management becomes an issue. I really wish Firefly III support OAuth login (login with Authentik, Zitadel, Keycloak, Google, etc, anything that supports OAuth2 Protocol), so that I don't have to remember (or manage) $n$ passwords.

### Solution

I think implementing generic OAuth 2 will be quite straightforward since it is a standardized format.

If this is feature is approved, i'd like to send a PR for this to be implemented. My plan is to:
- Either of the following:
  - Introduce environment variables that store the OAuth credentials and its configuration
  - Create a new section on the settings in Administration panel, to add new OAuth Client. (this means we can add more than one OAuth Credentials.)
- Add new section on User's Profile Settings, something called "Account connections", then connect the external oauth token there.
- In the login page, add a new button called "Login with [OAuth provider name].

More technical details:
- Will try to use [`league/oauth2-client`](https://packagist.org/packages/league/oauth2-client) to generate the Authorization URL, help with PKCE challenge, and exchange the auth code to token and resolve profile.
- Will pick `uid` to link with user from the resolved token, not by email.

Will this be okay for me to send PR with those details? What do you think?

Thank you!

### What are alternatives?

There's no alternative for this feature yet. I don't want my Firefly III to be my IDP, instead i want firefly to use the IDP I provided.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/how-to/firefly-iii/advanced/authentication/#remote-user-authentication

**Comment by chez14** [comment]
Oh... my bad, I didn't Google hard enough. Sorry for the spam. I'll try this first.

Thank you!

**Comment by JC5** [comment]
Not a problem!
