### ISSUE TITLE
Making splitting into one transfer easier

### ISSUE THREAD

**Issue by floli** [firefly-iii/firefly-iii#9002]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

We are frequently withdrawing money as part of a expense (e.g. we buy stuff at a supermarket for 20€ and additionally withdraw 50€ -> resulting in one transaction of 70€)
One of my most common tasks when going through my transfers is to split these transfers, so that 20€ goes to the supermarket's account (expense) and 50€ to my wallet (transfer).

Making these changes is a bit hard in the UI.

Thanks a lot!

### Solution

Some dialogue like "Split off transfer" that asks for an amount to split off and a target account (an assert account). After confirmation it also corrects the amount of original transfer. The split is a duplicate of the original account (same date, external identifier etc.) maybe with a modified description.

### What are alternatives?

My current workflow is:
1. Duplicate transaction
2. Change date in duplicated transaction (it is set to today, not the date of original transaction)
3. Change amount of duplicated transaction
4. Save
5. Convert duplicated transaction to transfer
6. Change amount of original transaction

### Additional context

A real split that consists of an expense and transfer is not going to happen, as the data model does not seen to support it (https://github.com/firefly-iii/firefly-iii/issues/6155)

**Comment by floli** [comment]
If you can advise an easier workflow to achieve the same, or a command line tool that uses the API to achieve that, I would be grateful as well!

**Comment by JC5** [comment]
This is actually pretty complex to make easier, so it will probably not happen. But if you have some tech skills, you could use the webhooks feature to do this for you, which is what I do for several things.

**Comment by avee87** [comment]
Out of curiosity, what is the value of having strictly defined transaction types? Can't withdrawal/deposit/transfer be derived from source and destination account types?

**Comment by JC5** [comment]
Sure, but if you want to select transactions by the type but first have to collect all accounts, it doesn't get any faster.
