### ISSUE TITLE
Add Account Saldo to Transaction Lists of Account

### ISSUE THREAD

**Issue by cutec-chris** [firefly-iii/firefly-iii#9007]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Its a bit hard to check where differences occour, i think in most accounting solutions display of the saldo is standard. Would be good to have here too, or do i dont see the option ?

### Solution

Add an Saldo row to Bookings ideally also to the database, and respect in importer. In my bank csv thers an saldo field, so the balance would be always correct, and musnt be fixed by Fake bookings if there are bookings missing.

**Comment by JC5** [comment]
There are several tickets already open that suggest this. It's on my list!

**Comment by cutec-chris** [comment]
The Transaction History Report (audit), could be an possibility in meantime for anyone who needs something like this
