### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Division by zero").

### ISSUE THREAD

**Issue by versvs** [firefly-iii/firefly-iii#9008]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

While assigning amounts to budgets for the active period, I accidentally clicked the Arrow Up/Down when trying to get the focus to enter the amount manually. Then the /budget view broke. Firefly III can still be used as long as I don't go into /budget or any subpage there.

Error message:

> Firefly III - 500 Internal Server Error :(
> Whoops! An error occurred.
> Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:
> 
> An exception has been thrown during the rendering of a template ("Division by zero").
> 
> This error occured in file /my/path/resources/views/budgets/index.twig on line 327 with code 0.

### Debug information

Debug information generated at 2024-06-30 09:18:26 for Firefly III version **v6.1.12**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.12 / v2.0.12 / 23 (exp. 23)</td></tr><tr><td>PHP version</td><td>8.3.6 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + Europe/Madrid</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-06-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-06-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The allocated amount for the clicked budget to be increased/decreased by 1 when the controls on the right side of the input are clicked.

### Steps to reproduce

1. Go to /budget
2. Select a period for which you have not set the amounts for your budgets yet (value at 0)
3. Click the arrow down/up. Since I hit it accidentally, I'm not sure whether it was one or the other, but given the divide by error message, I guess you press the arrow down first, to try to decrease the allocated amount for that specific budget by 1.
4. Budget view should now be broken

### Additional info

May you need more details, please, let me know. I have not seen this error reported, maybe I failed while searching.

**Comment by versvs** [comment]
Checking the template, maybe it is because I'm editing this in the last day of the month for the current month or something. Commenting out line 327 and 350  in the budget template that's failing (similar use of `activeDaysLeft` in both lines ) seems to get it running again, yet at the cost of not printing into the screen the commented line.

**Comment by JC5** [comment]
Could you upgrade to the latest version please?

https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue+division+by+zero+is%3Aclosed

**Comment by versvs** [comment]
Solved by upgrading to 6.1.16
