### ISSUE TITLE
Incorrect Amount Calculation in Reconciliation for Bank Account A

### ISSUE THREAD

**Issue by realzsan3** [firefly-iii/firefly-iii#9009]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

There is a bug in the reconciliation process where the transferred amount from bank account A to credit card account B is not included in the reconciliation for account A unless the transfer date is set to the previous day, while the reconciliation for account B is always correct.

### Debug information

Debug information generated at 2024-06-30 22:56:25 for Firefly III version **v6.1.17**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.17 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.8 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1099, base <span>#</span>85</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Asia/Shanghai + Asia/Shanghai</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>redis</td></tr><tr><td>Default language and locale</td><td>zh-CN + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-06-29 16:00:00 (22 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table>

### Expected behaviour

The transferred amount should be included in the reconciliation for bank account A regardless of the transfer date.

### Steps to reproduce

1. Transfer an amount from bank account A to credit card account B.
2. Perform reconciliation for credit card account B.
3. Perform reconciliation for bank account A.
4. Observe the amount calculation on the reconciliation interface.
5. Change the transfer date to the previous day.
6. Perform reconciliation for bank account A again.

### Additional info

I also noticed this issue on the last day of last month; here is  the [issue](https://github.com/firefly-iii/firefly-iii/issues/8937) I reported at that time.

**Comment by JC5** [comment]
Thanks for the details, I'll check it out once again.

**Comment by JC5** [comment]
I still can't replicate this. It works as expected. Please include ALL debug information.

**Comment by yong-s** [comment]
I successfully reproduced this bug in the demo. You can select "Saving Account" on this page [asset](https://demo.firefly-iii.org/accounts/asset) click "Reconcile this account," choose today's date 7/5 for the end balance, then click "Start reconciling," and finally click "Store Reconciliation." You will see the message: `Your Firefly III ledger has more money in it than your bank claims you should have. There are several options. Please choose what to do. Then, press "Confirm reconciliation".`The expected result is that this amount should have already decreased, and it should not prompt me to "Clear the selected transactions, and create a correction removing -€350.00 from this asset account."

**Comment by JC5** [comment]
Sorry, the demo site resets all the time. Did you create transfer dated on 05-07-2024?

**Comment by yong-s** [comment]
It is easy to reproduce: simply perform a transfer operation on the same day and then try to reconcile the account.

**Comment by JC5** [comment]
My problem is that it's right there, all the time :(

**Comment by yong-s** [comment]
I'm not sure if this requirement is correct. I just reproduced it again. Here is the[Accounts](https://demo.firefly-iii.org/accounts/reconcile/2/index). Choose today's date, 7/7, for the end balance date. After I click "Start reconciling," this amount should have already been removed. I shouldn't need to remove it manually.

**Comment by yong-s** [comment]
This is the result for the 7th. 
<img width="1186" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/47684798/60da92de-d4d3-4cab-8ce5-e061c1f4be3e">
This is the result for the 8th. 
<img width="1170" alt="image" src="https://github.com/firefly-iii/firefly-iii/assets/47684798/543c78a9-a173-477b-93af-2303aa17ec52">

I think it should be the same as the result for the 8th.

**Comment by JC5** [comment]
Ah, I see we misunderstand one another. Or rather, I you. I will check it out.

**Comment by yong-s** [comment]
Sorry, my English is poor, and I rely entirely on ChatGPT for translations, so there may be some misunderstandings in my requests. Please forgive me for not having studied English well before.

**Comment by JC5** [comment]
Thanks for your patience. The issue has been found. The next release will fix it.
