### ISSUE TITLE
Tags: Tags added via rules can include ","

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#901]
How to reproduce:
1. Create a rule
2. Add action: Add Tag = "something with a, character"
3. Search transaction, tag is: "something with a, character"

"," is a delimiter when tagging manually, right? maybe add a jQuery validation when adding tags via rules

**Comment by JC5** [comment]
Some people just want to watch the world burn, I guess ;).

**Comment by gavu** [comment]
I was not prepared for such a comment :)

**Comment by gavu** [comment]
in addition, if you edit the transaction, the JS displaying the tags, on the right, "corrects" them

**Comment by JC5** [comment]
Yep. The comma is the separator so if you sneak one in, the display will split them. Even when they're originally with a comma. You could start with a tag "a,b" and after editing, end up with "a" and "b".

"a,b" would still exist just pretty much unusable. 

It's a bug, technically, but catching all the places where a user might inject a comma is not very high on my todo-list 😉

**Comment by nicoschreiner** [comment]
And he is the second one mentioning this :P
(see Issue #883)

**Comment by JC5** [comment]
That too. No record this month ;)
