### ISSUE TITLE
Documentation - Fix Markdown on Transaction Types

### ISSUE THREAD

**Issue by s38b35M5** [firefly-iii/firefly-iii#9015]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

On the [Transaction Types](https://docs.firefly-iii.org/references/firefly-iii/transaction-types/) page of the FFIII documentation, there is a typo in the markdown with an extra open parenthesis in the "Deposits" section.

It reads:
`If you want to store cash deposits, be sure to read [how to manage cash]((../../how-to/firefly-iii/finances/cash.md).`

### Debug information

N/A

### Expected behaviour

It should be adjusted to: `If you want to store cash deposits, be sure to read [how to manage cash](../../how-to/firefly-iii/finances/cash.md).`

### Steps to reproduce

1. Go to https://docs.firefly-iii.org/references/firefly-iii/transaction-types/#deposits
2. Note the malformed link in the final sentence of the Deposits paragraph

**Comment by JC5** [comment]
Feel free to open a PR for these kinds of things!

**Comment by s38b35M5** [comment]
> Feel free to open a PR for these kinds of things!

Quite embarrassed to admit I don't know how! I will look into it and do my best!

**Comment by s38b35M5** [comment]
🤞🏼 
Hope I did this right, but please smack me down if I did it all wrong, @JC5

**Comment by s38b35M5** [comment]
Thx. Now, I'm a master of single-character edits. 

Thanks for the chance to mess with code revision at the lightest scale possible. Now my github user activity matrix isnt 100% issues!

**Comment by JC5** [comment]
Solved! 😁
