### ISSUE TITLE
Documentation - Typo in title of "How to Track Cash" page

### ISSUE THREAD

**Issue by s38b35M5** [firefly-iii/firefly-iii#9016]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

There is a simple typo in the header/title of the cash page at https://docs.firefly-iii.org/how-to/firefly-iii/finances/cash/

It reads: `How to tack cash`

### Debug information

N/A

### Expected behaviour

It was likely intended to read, "How to track cash"

### Steps to reproduce

1. Go to https://docs.firefly-iii.org/how-to/firefly-iii/finances/cash/
2. Word in title is mis-spelled

**Comment by JC5** [comment]
Feel free to open a PR for these kinds of things!

**Comment by JC5** [comment]
Solved! 😁
