### ISSUE TITLE
Rules: "After updating, return here" - empty trigger/actions fields

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#902]
is it a bug or works as designed?

**Comment by JC5** [comment]
No, it should recreate the old triggers and actions but I never got around to it.

**Comment by gavu** [comment]
until them, maybe hide the checkbox. Right now, if you fill everything out, select the checkbox, save, return and change the title or something on top of the page (so you do not notice the missing trigger/actions) you lose everything - except the new title

**Comment by JC5** [comment]
Fixed!
