### ISSUE TITLE
Incorrect "Expected Withdrawals" for Daily Recurring Transactions

### ISSUE THREAD

**Issue by xMarcii** [firefly-iii/firefly-iii#9021]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello dear developers,

I have encountered a small but annoying problem that somewhat hinders my use of Firefly-III.

When creating a recurring transaction and setting the "Type of repetition" to "daily," the data shown in "expected withdrawals" is completely incorrect.

### For example, if I set the start date to today (July 5th, 2024):
![image](https://github.com/firefly-iii/firefly-iii/assets/47897650/ade3d5b3-dc6f-419f-8dda-051f9177627c)

### The expected withdrawals are as follows:
![image](https://github.com/firefly-iii/firefly-iii/assets/47897650/a696fc62-75cd-458a-aed5-597dad1a1751)

### If I choose a date in the future, such as July 25th, 2024:
![image](https://github.com/firefly-iii/firefly-iii/assets/47897650/2f3ecda5-c861-430c-9c7e-13198663c6cb)

### The expected withdrawals are:
![image](https://github.com/firefly-iii/firefly-iii/assets/47897650/c4bf4436-f4a7-4815-b9b3-ad3d713bf781)

It seems the expected withdrawals are always a few days before the chosen date. I can't understand why the number of days varies for different dates.

Additionally, if I click on "create right now" for any of the preceding days, I get an error message:

"Message: No new transaction was created. Perhaps it was already fired for this date?"
![image](https://github.com/firefly-iii/firefly-iii/assets/47897650/75d68bd5-f1ef-4015-9438-4839f6a5501c)
(I pressed on all 5 Buttons from top to bottom but only the last one with the initially set "first date" could be created successfully)

This happens even if the date is in the future and no transaction is scheduled.

Thank you for looking into this issue!

Best regards,
Marcel

### Debug information

I tested this on the newest version on my private Debian12 VPS with Docker Compose and also on the official Demo Site!

### Expected behaviour

Normally, if i set the "first date" to 05.07.2024, the first expected withdrawal should be 06.07.2024. You can also only successfully press the button "create right now" one the initially set date, so there has to be a problem

### Steps to reproduce

1. Create recurring transaction
2. Set "first date" to any date but preferrably today
3. Set "type of repetition" to "every day"
4. Look at the expected Withdrawal tab

**Comment by JC5** [comment]
Nice, fixed.
