### ISSUE TITLE
Current Month/Year should show dates untill the end of the month

### ISSUE THREAD

**Issue by soloam** [firefly-iii/firefly-iii#9024]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When we select current month or current year the date should be until the end. Now if I select current month and it's day 5 and and I have bills on day 20 for example, on the home page I see expected bills zero, and I would like to see reflected what I have to pay until the end of the month.

### Solution

As stated, when selecting the current month/year/trimester it should show the date until the end of that period to show all the expected bill.

This is the main enhancement, as a bonus, the graph should show the expected bills effect on the accounts, or a new box with the estimated situation if the expected bills, withdraws or deposits occur. I have to always go to a spreadsheet or a calculator to make this estimations.

### What are alternatives?

If not both solutions, at least the first one

### Additional context

That's all

Thank you

**Comment by JC5** [comment]
What date did you give the bill, exactly?

**Comment by soloam** [comment]
Any date over today actually! For example if today I go to the Dashboard and set current moth, it shows 1 to 5 of July and any bill outside this range (most of them) don't show on the bills square!

To see them I have to select custom range and set 1 of July to 31 of July 

Thank you

**Comment by JC5** [comment]
What date did you give the bill, exactly?

**Comment by soloam** [comment]
This is the bill:

![image](https://github.com/firefly-iii/firefly-iii/assets/11949987/e712393a-cbea-4a9f-be7e-98c5be625766)

Select Current month
![image](https://github.com/firefly-iii/firefly-iii/assets/11949987/348d60d8-d828-494a-b191-02479c0272ee)

It stops on the 5th
![image](https://github.com/firefly-iii/firefly-iii/assets/11949987/98ad4490-5f03-4f0b-93d2-cffacefbf6ce)

Zero bills.... and it should show this one
![image](https://github.com/firefly-iii/firefly-iii/assets/11949987/4c0312cc-b3a9-4624-acb9-9201deaf36e3)

**Comment by JC5** [comment]
Alright so if you set the date of the bill in the middle of the month, its period will roll over halfway during the montb. So set it to the 1st of the month and it should work correctly.

**Comment by soloam** [comment]
But the due date is 20 of July, not 1 of July! I would like to have the information of the due date. The thing here is that if you select that you want the current month, the current month shout be from the start of the month to the end of the month, not from the start of the month to today!

**Comment by JC5** [comment]
Sorry, this is what it is.

**Comment by soloam** [comment]
Ok, in that case issue closed to me! Thank you
