### ISSUE TITLE
Add option within Firefly to use a 24 hour clock format across the whole site 

### ISSUE THREAD

**Issue by Goldensliv** [firefly-iii/firefly-iii#9038]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

The menu for adding a new transaction is always in 12-hour format and so far I haven't found a way to consistently change that across the entire site, so I believe adding an option specifically for time/date formats would make cross referencing transactions much easier.

### Solution

A setting in the preferences menu to choose time, date, etc. formats that overrides any browser locale setting.

### What are alternatives?

Currently with my browser's locale set to a place using 24hr format the transactions appear with the proper format, but the menu for creating new transactions do not.
![Screenshot__](https://github.com/firefly-iii/firefly-iii/assets/53317831/b6b4ea5a-69e0-41b1-8b48-16d169d712df)
![Screenshot_20240710_114708](https://github.com/firefly-iii/firefly-iii/assets/53317831/b2647f2d-d7a9-4cda-a0d7-b1293542808e)

**Comment by JC5** [comment]
Sorry, this is browser specific and I cannot change it.
