### ISSUE TITLE
Error updating transactions from within a specific tag

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#904]
How to reproduce:
1. Go to a tag
2. Selected, in my case, all transactions
3. Changed all descriptions - had a small typo

> Whoops! An error occurred.
> 
> Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> 
> Undefined index: notes
> 
> More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.
> 
> If you cannot find the cause of this error or when you need some help, please open a ticket on Github.

Let me know if you need debug logs

**Comment by JC5** [comment]
Nice find, fixed!

**Comment by gavu** [comment]
I confirm, test successful
