### ISSUE TITLE
Minor issue in AutoImport.php - does not catch a 'bad path' error

### ISSUE THREAD

**Issue by Terry-JF** [firefly-iii/firefly-iii#9044]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

If the directory path passed into AutoImport.php does not exist then the script fails with a variable type mismatch error rather than the script giving a meaningful error to the user. At line 71, the 'realpath' function will return 'false' in the $directory variable if the directory path does not exist and this is not caught prior to using $directory as a string at line 72.

### Debug information

See the screen output provided in original Q&A discussion post.

### Expected behaviour

I would expect the AutoImport.php script to check the value of $directory and give a sensible error message if this is not a string type.

**Comment by JC5** [comment]
Nice, I'll pick it up!
