### ISSUE TITLE
Transaction icons

### ISSUE THREAD

**Issue by nprzy** [firefly-iii/firefly-iii#9048]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'd like the ability to see icons with a logo related to my transactions. For example, a transaction at Burger King might be represented with a Burger King icon next to it.

### Solution

When creating a transaction, I'd like the ability to supply an icon URL. Then when viewing that transaction the icon URL can be used to display an image. I do not propose that Firefly fetch/store that icon, only reference it in a cross-site fashion in an `<img>` tag.

### What are alternatives?

I've considered that rather than attaching icons to each individual transaction, the icons could be associated to expense and asset accounts. However for my use case this would make icons more difficult to use. It would reduce the flexibility to use different icons for different transactions associated with the same account. And it would potentially introduce some ambiguity on which icon to render for a transaction, the one from the expense account or the one from the asset account.

### Additional context

I've recently started ingesting transactions from my banks via the [Plaid API](https://plaid.com/docs/api/products/transactions/#transactionsget). That API provides icon URLs that could be easily included in the Firefly transaction records.

Example: https://plaid-merchant-logos.plaid.com/burger_king_155.png

**Comment by JC5** [comment]
No, sorry. 

- Firefly II has had icons in the past, and it mainly adds noise.
- Loading eternal icons is not going to happen I'm afraid.
- Icon sets shipped with Firefly III will always have a maintenance and upkeep burden.

**Comment by nprzy** [comment]
Fair enough. I can respect the desire to not add additional noise to the web UX and of course I'd never propose maintaining/shipping an icon set with the product.

> Loading eternal icons is not going to happen I'm afraid.

I am curious about this. May I ask the motivation? Purely privacy concerns around leaking URLs to a third party, or something else?

**Comment by JC5** [comment]
Privacy and security. SVG images can carry Javascript, for example.

**Comment by nprzy** [comment]
Thanks for the clarification. I'd think the security concerns could be addressed with a strong [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) to block external Javascript and only allow external images from the domain(s) that the Firefly III deployment owner expects. And the privacy concerns could be addressed with a `same-origin` or `no-referrer` [`Referrer-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy). But even with all the proper security features in place I can see how opening the door to external assets could still be a can of worms better left unopened and I'm not going to push the issue. Thanks again!
