### ISSUE TITLE
Rule not matching transaction description

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#906]
I have the following transactions:
```
EC-GAA/POS CA  <timestamp> Uhr C EC-TERMINAL6702***   E2E-ID  ***
EC-GAA/POS CA  <timestamp> Uhr C EC-TERMINAL6702***   E2E-ID  ***
EC-GAA/POS CA  <timestamp> Uhr C EC-TERMINAL6702***   E2E-ID  ***
EC-GAA/POS CA  <timestamp> Uhr C EC-TERMINAL6702***   E2E-ID  ***
EC-GAA/POS CA  <timestamp> Uhr C EC-TERMINAL6702***   E2E-ID  ***
EC-GAA/POS CA  <timestamp> Uhr C EC-TERMINAL6702***   E2E-ID  ***
EC-GAA/POS CA <redacted>/// 02   <timestamp> Uhr C KF03    EC-TERMINAL 6705*** E2E-ID ***
EC-GAA/POS CAFE <redacted> GB  <timestamp> Uhr C EC-TERMINAL6544***   E2E-ID  ***
```

I need to match all *except* the last one. My triggers are:
* Description starts with: "EC-GAA/POS CA"
* Description contains: "TERMINAL6702"

I get no matches. AFAIK, the triggers use the AND operator, right?

**Comment by JC5** [comment]
It works for me. Make sure you've turned off "stop processing other triggers".

![screen shot 2017-10-06 at 13 08 23](https://user-images.githubusercontent.com/5889984/31275451-88eaf69c-aa97-11e7-8865-8d042a15fd71.png)
![screen shot 2017-10-06 at 13 08 44](https://user-images.githubusercontent.com/5889984/31275452-88ecfad2-aa97-11e7-8722-0090c80aabae.png)

**Comment by gavu** [comment]
Create/edit rule
![2017-10-06 13_15_54-edit rule _c a mode gmbh co kg_ rules firefly iii](https://user-images.githubusercontent.com/3742238/31275805-ef56d576-aa98-11e7-8544-4934afd51ee5.png)

Check rule
![2017-10-06 13_17_17-rules firefly iii](https://user-images.githubusercontent.com/3742238/31275816-f684afe4-aa98-11e7-8189-3b03696018b5.png)

Results are (it should not find anything):
![2017-10-06 13_20_50-search results for _6702_ search firefly iii](https://user-images.githubusercontent.com/3742238/31275898-724fcdd4-aa99-11e7-9e15-57075177a815.png)

**Comment by gavu** [comment]
Got it! sorry for the wrong report.

I had a weird character before the "EC-GAA..." part. Are you trimming the inputs?

**Comment by JC5** [comment]
When it's over the web yes, when creating them. Otherwise. no.

**Comment by JC5** [comment]
See also this file: https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Requests/Request.php#L41
