### ISSUE TITLE
Line chart is difficult to select

### ISSUE THREAD

**Issue by marcelweikum** [firefly-iii/firefly-iii#9063]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

The first graph shown in the dashboard is the line graph "Your accounts".  The points are selectable and show the actual data of different lines, but they are really difficult to hit, since you have to point directly on it. This is hard on PC aswell as Mobile...

I tinkered a little bit with Chart.js and found out you can make them snap to the nearest x - axis.
The config I tested with is this one:

```
const config = {
  type: 'line',
  data: data,
  options: {
    interaction: {
      intersect: false,
      mode: 'nearest',
      axis: 'x',
    },
```

And this one would go into the line chart config:

https://github.com/firefly-iii/firefly-iii/blob/f52978e71fb3d97cf24e1ae412f0f685dfe531eb/resources/assets/v2/src/support/default-chart-settings.js#L65-L97

Additionally to this more snappier approach, there could be a vertical line for the currently hovered date something like this sketch:

![image](https://github.com/user-attachments/assets/29c61049-c16b-477e-9cdf-822ad0862e88)

### Solution

Maybe use the config or a similar one, that snaps to the nearest x-axis entry for better user experience

### What are alternatives?

There are more alternatives than that. But in my opinion this is the most user friendly one.

See more on. https://www.chartjs.org/docs/latest/samples/tooltip/interactions.html

**Comment by JC5** [comment]
Nice, I'll check it out!

**Comment by JC5** [comment]
This is not available in the version of Chart.js I'm using, so I'm afraid this is something you're going to have to live with. I have some upgrades planned in the future.
