### ISSUE TITLE
Add a rule for rounding and percentages

### ISSUE THREAD

**Issue by marcelweikum** [firefly-iii/firefly-iii#9066]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hey James,

there is an Feature from my Bank, and I know several other Banks have it too, its called „Everyday Round Up“.

As soon as you make an payment with your Card, it will Transfer the missing amount of the next Full 1$ or Next 5$ and Transfer it to another Account.

It would be nice to set this as rule and not make a transaction twice for every Card payment.

Additionally: someone Else has mentioned this in another issue with adding fees as a Rule, but the fees are commonly just percentages of the amount, so percentages as Rules would be a nice Feature too

Best Regards,
Marcel

### Solution

Make an Option for a rule with percentages and rounding up and get the difference

**Comment by JC5** [comment]
No, sorry, there will be no such rule action. However, you could give this script a try:

https://github.com/JC5/autosave
