### ISSUE TITLE
Consider including debian package `locale-all` in Docker image

### ISSUE THREAD

**Issue by macourteau** [firefly-iii/firefly-iii#9069]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to use the Firefly III Docker image with the `en_CA` locale, but it's not one of the included locales:
```
# locale -a
C
C.UTF-8
POSIX
bg_BG.utf8
ca_ES.utf8
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
el_GR.utf8
en_GB.utf8
en_US.utf8
es_ES.utf8
fi_FI.utf8
fr_FR.utf8
hu_HU.utf8
id_ID.utf8
it_IT.utf8
ja_JP.utf8
nb_NO.utf8
nl_NL.utf8
nn_NO.utf8
pl_PL.utf8
pt_BR.utf8
pt_PT.utf8
ro_RO.utf8
ru_RU.utf8
sk_SK.utf8
sl_SI.utf8
sv_SE.utf8
tr_TR.utf8
uk_UA.utf8
vi_VN.utf8
zh_CN.utf8
zh_TW.utf8
```

### Solution

Including the `locale-all` debian package in the Docker image would fix the issue.

**Comment by JC5** [comment]
Hey,

Sorry, but that's a 200MB package, so that's not going to happen. The Docker container comes with locale files for the installed languages, other languages are up to you to install.

**Comment by macourteau** [comment]
I see, thanks for the fast reply - that's understandable. :)

Instead, perhaps `en_CA.UTF-8 UTF-8` and `fr_CA.UTF-8 UTF-8` could be added to /etc/locale.gen (with `locale-gen` run as a build step afterwards) so it's included in the image? At the moment, the UI lets me choose Canadian Dollar as a currency for accounts, but there's no locale for it installed and so the UI says "Invalid server configuration:  Firefly III is unable to format monetary amounts because your server is missing the required packages. There are instructions how to do this.".

I haven't checked if other built-in currencies are missing a locale, so not sure if CAD is the only currency that's missing a locale.

**Comment by macourteau** [comment]
(per https://github.com/firefly-iii/firefly-iii/issues/9069#issuecomment-2241628852, will open a new issue with my comment above, sorry for the churn)
