### ISSUE TITLE
More buttons/options on transactions list

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#907]
Because I quite often clone different transactions I would really love to have a clone button on the transaction list:
![obraz](https://user-images.githubusercontent.com/4746858/31278022-b3b51ebe-aaa3-11e7-8581-f9ecd0be9d5b.png)
Or maybe there could be a dropdown menu instead of edit button with more actions available?

**Comment by JC5** [comment]
Most lists are already quite crowded, and I'm actually thinking about removing buttons rather than add them at this point. A drop-down could work, I'll have to test it.

**Comment by JC5** [comment]
Fixed. See https://demo.firefly-iii.org/accounts/show/1

The buttons are moved to the left and hidden behind a dropdown. This is less convenient for quickly editing and deleting transaction, but it gives room for almost all of the other actions.

**Comment by skibbipl** [comment]
Perfect, new UI is a way better than current one. Thanks!
