### ISSUE TITLE
Deposits / Withdrawals showing incorrectly between accounts

### ISSUE THREAD

**Issue by MrBogger** [firefly-iii/firefly-iii#9073]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

A withdrawal in one account is showing as a withdrawal in the opposing account. A deposit in one account is showing as a deposit in the opposing account also. Monthly calculations on the right hand side are calculated incorrectly as well.

### Debug information

Not collected.

### Expected behaviour

When a withdrawal is displayed in one account, the opposing account should show the transaction as a deposit.

### Steps to reproduce

1. Create a transaction between any account, not a transfer though
2. Check opposing account transaction list
3. Monthly total expense/revenue is calculated incorrectly.

### Additional info

<img width="1196" alt="Screen Shot 2024-07-22 at 17 19 28" src="https://github.com/user-attachments/assets/c8ce63c3-3e04-45ae-b556-71bca2934282">
Main Checking Account Transactions
<img width="1180" alt="Screen Shot 2024-07-22 at 17 19 52" src="https://github.com/user-attachments/assets/5cdb3139-4355-4a10-8c1e-ae87f7565310">
AMEX Credit Card Debt Account
<img width="1196" alt="Screen Shot 2024-07-22 at 17 20 09" src="https://github.com/user-attachments/assets/89120a1f-85f3-4546-b0fe-fb20e7166452">
The House Account

**Comment by JC5** [comment]
A liability does not "earn" money when you send money to it, it's still an expense.
