### ISSUE TITLE
[Suggestion] Buttons for quick month selection on the navbar

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#908]
I find switching months from dropdown menu a bit tedious. Perhaps you can add small left and right arrows for going backwards and forward from current month?
![obraz](https://user-images.githubusercontent.com/4746858/31278276-a0b90374-aaa4-11e7-9532-8244e90a7889.png)

**Comment by JC5** [comment]
No. There's a quick link to the previous/next month in the menu itself, and I want to keep the bar empty.
