### ISSUE TITLE
Line graph showing only primary currency when multiple currencies are available

### ISSUE THREAD

**Issue by marcelweikum** [firefly-iii/firefly-iii#9082]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hey,

When you have multiple asset accounts with different currencies, especially if one of the currencies is significantly weaker than the other, the line graph only displays one currency on the index, making the entire graph difficult to read. As shown in the attached images (Image 1: dashboard and image 2: reports), this causes the weaker currency to stand out while making the stronger currency appear as a nearly straight line.

![image](https://github.com/user-attachments/assets/0a70550c-aef5-485e-8e2a-9a16df07e4e8)
![image](https://github.com/user-attachments/assets/fab8d11d-0b5a-41d2-a3a5-5be08ef97465)

### Debug information

I tested this one the demo site as well as on mine:

Debug information generated at 2024-07-25 10:13:40 for Firefly III version **v6.1.19**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.19 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.9 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1113, base <span>#</span>86</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + Europe/Berlin</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-07-24 22:00:00 (10 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-07-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-07-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

Maybe multiple indexes or multiple graphs for different currencies.

### Steps to reproduce

1. Create asset account with USD/EUR and make the start balance 1000
2. Create asset account with a weaker currency like JPY with the actual exchange rate 165148,6
3. See that the graph now shows the line at 165148,6 USD/EUR instead of JPY, unless you hover over it

**Comment by JC5** [comment]
Yes, this is known and documented. Thanks for reporting!

I expect this to be better in the new layout :)

**Comment by marcelweikum** [comment]
Oh sorry, I have actively searched for an issue and infos but found nothing...

@JC5 Do you have more information about the new layout? Like a roadmap or a list of features?

Thank you very much!
