### ISSUE TITLE
API Call for bills/nextExpectedMatch does not update

### ISSUE THREAD

**Issue by marcelweikum** [firefly-iii/firefly-iii#9084]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hey James,

I've encountered some unexpected behavior while tinkering with a mobile app for Firefly III using the API. I have a few observations and issues I'd like to share.

### **Overview**
I have four images showcasing the behavior:

**1:** Two demo bills (one daily and one yearly) set to 26.07.2024, both unpaid.
**2:** The same two demo bills, but this time marked as paid.
**3:** Details of Demo Bill 1 when opened.
**4:** Details of Demo Bill 2 when opened.

### Image 1: Two demo bills (one daily and one yearly) set to 26.07.2024, both unpaid.
![image](https://github.com/user-attachments/assets/60367b0b-b1db-4bbb-b69f-07e022362f42)

### **Demo Bill 1 unpaid API call:**

```json
{
    "data": {
        "type": "bills",
        "id": "10",
        "attributes": {
            "created_at": "2024-07-26T10:42:12+02:00",
            "updated_at": "2024-07-26T10:42:31+02:00",
            "currency_id": "9",
            "currency_code": "USD",
            "currency_symbol": "$",
            "currency_decimal_places": 2,
            "name": "Demo Bill 1",
            "amount_min": "5000.00",
            "amount_max": "5000.00",
            "date": "2024-07-26T00:00:00+02:00",
            "end_date": null,
            "extension_date": null,
            "repeat_freq": "daily",
            "skip": 0,
            "active": true,
            "order": 2,
            "notes": null,
            "object_group_id": null,
            "object_group_order": null,
            "object_group_title": null,
            > "next_expected_match": "2024-07-26T00:00:00+02:00",
            "next_expected_match_diff": "today",
            "pay_dates": [
                > "2024-07-26T00:00:00+02:00",
                "2024-07-27T00:00:00+02:00",
                "2024-07-28T00:00:00+02:00",
                "2024-07-29T00:00:00+02:00",
                "2024-07-30T00:00:00+02:00",
                "2024-07-31T00:00:00+02:00",
                "2024-08-01T00:00:00+02:00",
                "2024-08-02T00:00:00+02:00",
                "2024-08-03T00:00:00+02:00",
                "2024-08-04T00:00:00+02:00",
                "2024-08-05T00:00:00+02:00",
                "2024-08-06T00:00:00+02:00",
                "2024-08-07T00:00:00+02:00"
            ],
            "paid_dates": []
        },
        "links": {
            "0": {
                "rel": "self",
                "uri": "/bills/10"
            },
            "self": "https://demo.firefly-iii.org/api/v1/bills/10"
        }
    }
}
```

### **Demo Bill 2 unpaid API call:**

```json
{
    "data": {
        "type": "bills",
        "id": "11",
        "attributes": {
            "created_at": "2024-07-26T10:42:29+02:00",
            "updated_at": "2024-07-26T10:42:31+02:00",
            "currency_id": "9",
            "currency_code": "USD",
            "currency_symbol": "$",
            "currency_decimal_places": 2,
            "name": "Demo Bill 2",
            "amount_min": "5000.00",
            "amount_max": "5000.00",
            "date": "2024-07-26T00:00:00+02:00",
            "end_date": null,
            "extension_date": null,
            "repeat_freq": "yearly",
            "skip": 0,
            "active": true,
            "order": 1,
            "notes": null,
            "object_group_id": null,
            "object_group_order": null,
            "object_group_title": null,
            > "next_expected_match": "2024-07-26T00:00:00+02:00",
            "next_expected_match_diff": "today",
            "pay_dates": [
                > "2024-07-26T00:00:00+02:00",
                "2025-07-26T00:00:00+02:00",
                "2026-07-26T00:00:00+02:00",
                "2027-07-26T00:00:00+02:00",
                "2028-07-26T00:00:00+02:00",
                "2029-07-26T00:00:00+02:00",
                "2030-07-26T00:00:00+02:00",
                "2031-07-26T00:00:00+02:00",
                "2032-07-26T00:00:00+02:00",
                "2033-07-26T00:00:00+02:00",
                "2034-07-26T00:00:00+02:00"
            ],
            "paid_dates": []
        },
        "links": {
            "0": {
                "rel": "self",
                "uri": "/bills/11"
            },
            "self": "https://demo.firefly-iii.org/api/v1/bills/11"
        }
    }
}
```

### Image 2: The same two demo bills, but this time marked as paid.
![image](https://github.com/user-attachments/assets/471041fd-b153-49ec-a33e-f87e28daa8d3)

### **Demo Bill 1 paid API Call:

```json
{
    "data": {
        "type": "bills",
        "id": "10",
        "attributes": {
            "created_at": "2024-07-26T10:42:12+02:00",
            "updated_at": "2024-07-26T10:42:31+02:00",
            "currency_id": "9",
            "currency_code": "USD",
            "currency_symbol": "$",
            "currency_decimal_places": 2,
            "name": "Demo Bill 1",
            "amount_min": "5000.00",
            "amount_max": "5000.00",
            "date": "2024-07-26T00:00:00+02:00",
            "end_date": null,
            "extension_date": null,
            "repeat_freq": "daily",
            "skip": 0,
            "active": true,
            "order": 2,
            "notes": null,
            "object_group_id": null,
            "object_group_order": null,
            "object_group_title": null,
            > "next_expected_match": "2024-07-26T00:00:00+02:00",
            "next_expected_match_diff": "today",
            "pay_dates": [
                > "2024-07-26T00:00:00+02:00",
                "2024-07-27T00:00:00+02:00",
                "2024-07-28T00:00:00+02:00",
                "2024-07-29T00:00:00+02:00",
                "2024-07-30T00:00:00+02:00",
                "2024-07-31T00:00:00+02:00",
                "2024-08-01T00:00:00+02:00",
                "2024-08-02T00:00:00+02:00",
                "2024-08-03T00:00:00+02:00",
                "2024-08-04T00:00:00+02:00",
                "2024-08-05T00:00:00+02:00",
                "2024-08-06T00:00:00+02:00",
                "2024-08-07T00:00:00+02:00"
            ],
            "paid_dates": []
        },
        "links": {
            "0": {
                "rel": "self",
                "uri": "/bills/10"
            },
            "self": "https://demo.firefly-iii.org/api/v1/bills/10"
        }
    }
}
```

### **Demo Bill 2 paid API Call:**

```json
{
    "data": {
        "type": "bills",
        "id": "11",
        "attributes": {
            "created_at": "2024-07-26T10:42:29+02:00",
            "updated_at": "2024-07-26T10:42:31+02:00",
            "currency_id": "9",
            "currency_code": "USD",
            "currency_symbol": "$",
            "currency_decimal_places": 2,
            "name": "Demo Bill 2",
            "amount_min": "5000.00",
            "amount_max": "5000.00",
            "date": "2024-07-26T00:00:00+02:00",
            "end_date": null,
            "extension_date": null,
            "repeat_freq": "yearly",
            "skip": 0,
            "active": true,
            "order": 1,
            "notes": null,
            "object_group_id": null,
            "object_group_order": null,
            "object_group_title": null,
            >"next_expected_match": "2024-07-26T00:00:00+02:00",
            "next_expected_match_diff": "today",
            "pay_dates": [
                >"2024-07-26T00:00:00+02:00",
                "2025-07-26T00:00:00+02:00",
                "2026-07-26T00:00:00+02:00",
                "2027-07-26T00:00:00+02:00",
                "2028-07-26T00:00:00+02:00",
                "2029-07-26T00:00:00+02:00",
                "2030-07-26T00:00:00+02:00",
                "2031-07-26T00:00:00+02:00",
                "2032-07-26T00:00:00+02:00",
                "2033-07-26T00:00:00+02:00",
                "2034-07-26T00:00:00+02:00"
            ],
            "paid_dates": []
        },
        "links": {
            "0": {
                "rel": "self",
                "uri": "/bills/11"
            },
            "self": "https://demo.firefly-iii.org/api/v1/bills/11"
        }
    }
}
```

### Image 3: Details of Demo Bill 1 when opened.
![image](https://github.com/user-attachments/assets/03e95ea2-d2da-4803-9ee2-cedde54ae6e8)
### Image 4: Details of Demo Bill 2 when opened.
![image](https://github.com/user-attachments/assets/f4bcd674-6db2-4b2d-86b3-123aeebc5e16)

### Issues
- Next Expected Match Not Shown for Non-Daily Bills:
For bills that are not recurring daily, the next_expected_match is not shown in the bills dashboard. However, if you open the bill, you can see the next_expected_match.
Example: Image 2 shows Demo Bill 2 without next_expected_match, but Image 4 shows it opened with the next_expected_match.

- Next Expected Match Does Not Change in API Calls:
The next_expected_match does not update correctly for API calls. For example, the JSON for Bill 2 (both unpaid and paid) is identical, as is the case for Bill 1.
Example: Comparing the JSON for unpaid and paid bills, next_expected_match remains the same, which should not be the case.
If you open a bill, the correct "nextExpectedMatch" is shown, but not in API Calls.

Could you please look into these issues and let me know if there's something I might be missing or if this is a bug?

Thanks!

### Debug information

Debug information generated at 2024-07-26 11:31:11 for Firefly III version **v6.1.19**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.19 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.9 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1113, base <span>#</span>86</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + Europe/Berlin</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-07-25 22:00:00 (11 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-07-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-07-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

As I understand it, the nextExpectedMatch should work the same way it is displayed in the Bills Overview when you open a bill, like these:

### Image 3: Details of Demo Bill 1 when opened.
![image](https://github.com/user-attachments/assets/03e95ea2-d2da-4803-9ee2-cedde54ae6e8)
### Image 4: Details of Demo Bill 2 when opened.
![image](https://github.com/user-attachments/assets/f4bcd674-6db2-4b2d-86b3-123aeebc5e16)

### Steps to reproduce

1. Create a bill with $5000.
2. Make an API call for that bill and look for nextExpectedMatch.
3. Make a transaction that fully pays the bill.
4. Make an API call for that bill and look for nextExpectedMatch.
5. Observe that there is no difference, even though it should show the new date, as the old nextExpectedMatch was fulfilled.

**Comment by JC5** [comment]
>  For bills that are not recurring daily, the next_expected_match is not shown in the bills dashboard. However, if you open the bill, you can see the next_expected_match.

Nice, this will be fixed in the next release.

>  If you open a bill, the correct "nextExpectedMatch" is shown, but not in API Calls.

I expect you aren't adding the `start=2024-07-01` and `end=2024-07-31` parameters, which are added under the hood, to make this data available: https://api-docs.firefly-iii.org/#/bills/listBill

**Comment by marcelweikum** [comment]
> I expect you aren't adding the `start=2024-07-01` and `end=2024-07-31` parameters, which are added under the hood, to make this data available: https://api-docs.firefly-iii.org/#/bills/listBill

I am using Restman to send http GET for this Endpoint: https://demo.firefly-iii.org/api/v1/bills and the nextExpectedMatch is ALWAYS the creation date, no matter if paid or not

**Comment by JC5** [comment]
I'm not sure what you mean. But I see the code works as expected when I send, for example:

```
curl --location 'https://host.example/api/v1/bills/16?start=2024-07-01&end=2024-07-31' \
--header 'Authorization: Bearer eyJ0....'
```

**Comment by marcelweikum** [comment]
Ah, I see!
But does the start and end date even matter?
Could be arbitrary, it's just for the nextExpectedMatch to be sent, right?

Thank you for the infos!

**Comment by JC5** [comment]
Basically, it gives the math some limits, to prevent it from calculating 4 year's worth of daily occurrences. If you need a guide, I would wrap it around the current month. So either the first of this months until the last, or simply +15 days and -15 days or something like that.
