### ISSUE TITLE
[Suggestion] Net Worth – call money checkbox

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#909]
Hi and thank you for the new overview boxes in 4.6.6. I really like the Net Worth box as it gives a quick impression of the current total worth. But I would love it even more if I could differ between total worth and total call money. For me that make a difference as I track long tied money too which can’t spent shortly.

So my wish would be to have another checkbox like “is active?” to control if an account is counted to the total call money or not. The call money value could be added below the line in the Net Worth box as that’s empty space currently.

I hope I described it well and that you find this idea helpful for others too :)

**Comment by JC5** [comment]
I like the idea, but the current level of "complexity" is as far as it goes for financial control. Adding more options like this one is not on the table at this point I'm afraid.
