### ISSUE TITLE
The link for SaltEdge's supported banks in the documentation is wrong

### ISSUE THREAD

**Issue by ACasset** [firefly-iii/firefly-iii#9102]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The [gocardless-salt-edge](https://github.com/firefly-iii/docs/blob/main/docs/docs/explanation/data-importer/about/gocardless-salt-edge.md) documentation contains a link to SaltEdge's supported banks : `https://www.saltedge.com/products/spectre/countries?channel%5B%5D=non_regulated`

The parameter is not correctly handled and the banks list on the page is therefore wrong.

The link should simply be to `https://www.saltedge.com/products/spectre/countries?channel=non_regulated`

### Debug information

N/A

**Comment by JC5** [comment]
Nice, thanks!
