### ISSUE TITLE
Default Currency does not apply to Accounts.

### ISSUE THREAD

**Issue by chrisgriff1512** [firefly-iii/firefly-iii#9103]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

With the currency for the profile set to default to US Dollar and an Account is set to US Dollar, the UI still shows the Euro symbol for that account. 

### Debug information

Debug information generated at 2024-07-31 17:44:15 for Firefly III version **v6.1.19**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.19 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.9 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1113, base <span>#</span>86</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + America/New_York</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2024-07-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-07-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

With the US Dollar set as the Default and all other currencies disabled, the GUI should show the US Dollar symbol $ in the widgets and action buttons for the accounts added. 

### Steps to reproduce

1.) Set the currencies to default to US Dollar and disable the Euro:
![Currencies](https://github.com/user-attachments/assets/37fbc48d-c5b3-42de-a325-f0bbfc90fca6)
2.) Add an account that is set to use the US Dollar: 
![Accounts](https://github.com/user-attachments/assets/65944f2f-556f-4ead-9136-40a2f49d2acd)
3.) Go to the Dashboard and look at the networth and the transaction buttons. They will display the Euro.
![TransActionEuro](https://github.com/user-attachments/assets/b5f28384-4e02-48a7-872d-b52724247801)
![NetworthWidgetEuro](https://github.com/user-attachments/assets/88bce3f6-68ff-4a10-b017-ee71d797477d)

### Additional info

This is a fresh install and the only thing I've done is add an account.

**Comment by JC5** [comment]
Sorry, but I can't replicate this. What happens when you browse to `/flush`?

**Comment by chrisgriff1512** [comment]
When I pointed my browser to /flush, the page refreshed, but there was no change with the euro symbol sticking around.

**Comment by JC5** [comment]
Sorry, I'm not sure what it could be. The net worth is independent from the currency preference, it uses the accounts balances to calculate the net worth. As such, enabling or disabling currencies doesn't influence the net worth.

In regards to the account buttons, I have an equal amount of trouble repeating what I see in the screenshots.

Can you replicate the issue on [the demo site](https://demo.firefly-iii.org/)?

**Comment by chrisgriff1512** [comment]
I can indeed. I think it should still be set to USD and the items in my screen shot mirror what is on the Demo Page

**Comment by chrisgriff1512** [comment]
This is a screen shot of my dashboard:
![image](https://github.com/user-attachments/assets/85a1474e-dea2-4ee5-8e5e-55a639401d3f)

I've logged out and logged back in and still the same.

**Comment by chrisgriff1512** [comment]
It looks like if you disable the Euro and Enable the US Dollar and set the USD as the default, the drop down gets set to US Dollar, but the changes to the system do not occur until you press the "Update Asset Account". I've had to do the same to the other accounts and now they are showing up as the US Dollar.

**Comment by JC5** [comment]
Ah yes. This is to be expected, because setting the default currency does NOT update existing accounts. However, it should not be possible to disable currencies when accounts still have it set as their currency. I'll pick it up!

**Comment by chrisgriff1512** [comment]
awesome, Thanks for your help!
