### ISSUE TITLE
Inactive accounts are inaccessible when no active accounts of that type exist

### ISSUE THREAD

**Issue by codemicro** [firefly-iii/firefly-iii#9106]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When viewing an account listing page (in this example, liabilities), if you have any inactive accounts but no active accounts of that type, you cannot access the link to list all your inactive accounts without first creating an account. Eg:

![image](https://github.com/user-attachments/assets/7b1c4f17-7108-45df-934c-c767fab4c953)

### Debug information

Not included the whole debug output because it contains a bit more info about my setup than I'd like to share that isn't relevant but I'm on **v6.1.19** using the **v1 layout** (as you can see haha).

### Expected behaviour

A link a little like this one to be shown alongside the "create your first liability!" popup

![image](https://github.com/user-attachments/assets/a066dcf5-6718-47f0-9a71-0d93be008100)

### Additional info

I was going to submit a PR instead of just opening an issue for this but it looked slightly less trivial than I expected it to be and I'm not well-versed in PHP - though, from what I can tell, this would affect all types of accounts, not just liabilties like in this example.

:)

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
Fixed in v6.1.22

**Comment by codemicro** [comment]
Funny coincidence, I was just thinking about this yesterday. Thanks!
