### ISSUE TITLE
Add budget option to transfers

### ISSUE THREAD

**Issue by jkano** [firefly-iii/firefly-iii#9112]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi! 

First of all, great tool! I've been using Firefly for over a year and it's my main tool for finances mgmt and expenses tracking. 

Now let me explain my use case:

Last month I opened a second Savings account where I'm going to save money for a house. Monthly I'm going to transfer some money from my **main** account to this **Home Savings** account (i.e. $1000). Everything is working correctly (Net worth is correct, in + out this period is showing as it should).

In my budget, I have 1 row that is called **Home savings** which is for $1000. I added this inside my budget because this is like a bill that I will "pay" monthly but instead of a normal withdrawal is a transfer to my **Home Savings** account.

But when I create a transfer I cant assign a budget to this transfer, so it's not counting inside my budget and the budget is incorrectly saying for example: "Spent -$300, between August 1st, 2024 and August 31st, 2024, leaving $5800.

This budget message should say "Spend -$1300, between..." because the $1000 of the transfer should be included in my budget.

I tried doing a workaround:

1. Created a $1000 withdrawal from **main** savings account to an expense account and assign the **Home savings** budget.
2. Created a $1000 Deposit from a dummy account to my secondary savings account **Home savings".

But when doing that, now in the dashboard, the In + Out this period is incorrect, as it thinks that I had an extra $1000 deposit.

So, do you know how can I assign a budget to a transfer? Is this doable? Or do you know a workaround to use that don't mess with budget or the dashboard calculations.

Again, thanks for the great tool! 

### Solution

Adding a budget option to transfers may help some users to add transfers that they make between their own accounts to a budget so they can keep track of their budget correctly.

**Comment by JC5** [comment]
Sorry, transfers will not get the option to add a budget to them.

**Comment by MaxZachner** [comment]
I was going to ask the same thing. It would be really cool if you could budet transfers.
Alternatively maybe there could be something like a tag you can attach to transactions to exclude them from the report infographics and the displayed income.
I understand though that internally the math has to work out so it is probably not trivial.

Is there another way to have an overview over say a 50:30:20 split budget that includes savings "expenses" that are technically just a transfer?
