### ISSUE TITLE
View date in mobile transactions list

### ISSUE THREAD

**Issue by halilim** [firefly-iii/firefly-iii#9122]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

In a mobile transaction list, I often find myself clicking on a transaction only to see the date in the detail view.

### Solution

Show the date. If as a new column, I guess the table would no longer fit (`.table-responsive`?).

Alternatively, it can be another line in the description column. But I'm unsure if that would look any good.

Speaking of space, I also imagined merging source and destination e.g. Src -> Dest, but I'm no designer at all :)

**Comment by JC5** [comment]
Hey, thanks for opening this ticket! These are great ideas, and I'm currently working on a new layout that should have better support for mobile phones. Stay tuned 😁
