### ISSUE TITLE
Accidentally creating a transaction of very small year causes server errors

### ISSUE THREAD

**Issue by spoulson** [firefly-iii/firefly-iii#9125]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I had accidentally entered a non-plausible year "0008" for a transaction date.  Once this transaction was created, the Reports page would show pre-set ranges for years 0008 to present, creating a very large scrolling page.  In attempts to correct this obvious mistake, I attempted to view my account where I knew I created the transaction and set date range to Everything.  This results in a server error.

To fix the data entry mistake I was able to launch a custom docker service on my docker-compose.yaml to install and run `mysqlclient` package and log into the database as `fireflyiii`.  I was able to find and update the transaction in the `transaction_journals` table.  The Reports page wasn't immediately fixed.  But, the next day things were back to normal with a plausible starting year (2021).

### Debug information

Debug information generated at 2024-08-06 13:40:45 for Firefly III version **v6.1.18**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.18 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.8 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1104, base <span>#</span>85</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/New_York + America/New_York</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-08-06 04:00:00 (13 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-07-07 00:00:00</td></tr><tr><td>Session end</td><td>2024-08-06 23:59:59</td></tr><tr><td>View range</td><td>last30</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

I would've expected the create transaction page to not allow implausible years older than, say, 1900.

### Steps to reproduce

# Reports page usability issue
1. Create two transactions on an account with date "01-01-0008" and another one with current date.
2. Browse to Reports page `/reports`.
3. Observe very long scrolling page of pre-sets ranging years 0008 to 2024.

# Inability to edit transaction issue
1. Create a transaction on an account with date "01-01-0008".  Oops!  Now you need to edit it to fix the date.
2. View the transactions page on that account `/accounts/show/<account-id>`.
3. Change date range to Everything.
4. Observe server error page.

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

The reports page is a basic loop, it goes from the oldest to the newest transaction. 

The script that parses dates from URL parameters (i.e. from "20240801" it will extract August 1st, 2024) does not recognize the year 8 AD. As a result, the charts do not work. The page itself (`/accounts/show/x`) still works fine, at least it does for me.

I'm not going to fix these issues. They are minor and easily fixed by editing the transaction.
