### ISSUE TITLE
Data importer confuses thousands separator for decimal separator when decimal separator is missing.

### ISSUE THREAD

**Issue by hdmbn** [firefly-iii/firefly-iii#9132]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

For example, 31.422 which can be a normal transaction value in the Crypto world, is considered as 31,422.00 by the data importer.

### Debug information

local.DEBUG: Start with amount "31.422"  
local.DEBUG: Stripped "31.422" to "31.422"  
local.DEBUG: No decimal point, try to find a dot.  
local.DEBUG: Found decimal point at position 2, length of string is 6, diff is 4.  
local.DEBUG: Thousands separator seems to be a dot, decimal separator must be a comma.  
local.DEBUG: Converted amount from "31.422" to "31422".  
local.DEBUG: Final NUMERIC value is: "31422"  
local.DEBUG: Stored column #3 with value "31422" and role "amount_credit" in field "amount_credit"

**Comment by JC5** [comment]
Which version of the data importer are you using?

**Comment by hdmbn** [comment]
## 1.5.3 - 2024-07-28

**Comment by HamzaMehyar** [comment]
I have been having this issue too
 Firefly III Data Importer, v1.5.3 
I have tried different combination of formats and none of them worked:
original format -> how the data formatter percieves it
1,500.514 -> 1.501$
1.500,512 -> 1.501$
1500.513 -> 1500513$

**Comment by hdmbn** [comment]
To prevent confusion during data import, append three extra zeros to decimal numbers, for example, format 31.422 as 31.422000.

**Comment by HamzaMehyar** [comment]
Yep that fixed it, Thank you both :fire: .
I still beilive the current behaviour is buggy though, the formats I tried are all standard format and should be detected by the importer.

**Comment by JC5** [comment]
Hey everybody, thanks for commenting. I'm afraid that this behavior will not change, and adding decimals to the import is the solution you'll have to go for.

>  I still beilive the current behaviour is buggy though, the formats I tried are all standard format and should be detected by the importer.

Unfortunately, there are more currencies where "1.000" represents 1000 than there are currencies where "1.000" represents 1.

See also: https://github.com/firefly-iii/firefly-iii/issues/8404

Thanks.

**Comment by HamzaMehyar** [comment]
no problem, the solution was hard to find though, maybe we should add it to the [data fields role documentation?](https://docs.firefly-iii.org/references/data-importer/roles/)

**Comment by hdmbn** [comment]
Why not adding options to import config to declare what is decimal separator?

**Comment by JC5** [comment]
Because the problem isn't big enough.
