### ISSUE TITLE
Light Mode Toggle: Help Box Doesn't Update

### ISSUE THREAD

**Issue by peterPain01** [firefly-iii/firefly-iii#9137]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Change to light mode but the help box does not change

### Debug information

![image](https://github.com/user-attachments/assets/020b28cf-a366-4efb-b398-81ff1748f776)

### Steps to reproduce

1. Change theme from Dark to Light

**Comment by JC5** [comment]
Hey, thanks for reporting! 

I'm aware of the issue, but unfortunately the library that provides the box isn't maintained anymore. I'm afraid I'm not going to fix this.
