### ISSUE TITLE
'Today' indicator in dashboard graph

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#914]
I'd find it helpful if the account overview would contain some kind of an indicator to show the current day if it is contained in the current time range. 
![image](https://user-images.githubusercontent.com/317179/31307780-10b440e6-ab6b-11e7-8358-4a5a7979f225.png)

**Comment by gavu** [comment]
+1 :)

**Comment by JC5** [comment]
If the library chart has something for it, absolutely. Not a vertical line though. I'll look into it!

**Comment by JC5** [comment]
This will be featured in the next release, and you can see it already on [the demo site](https://firefly-iii.nder.be/). 

For the time being, this will be the only chart with a today indicator but others could follow.

**Comment by skuzzle** [comment]
Looks great. Just the way I imagined it :)
