### ISSUE TITLE
Dashboard 'Today' option chooses 1st of month (not current date)

### ISSUE THREAD

**Issue by PAS-BC** [firefly-iii/firefly-iii#9140]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The Dashboard page has a 'date picker' to the right of the '?' link.
Selecting the 'Today' item displays 'August 1st, 2024 - August 1st, 2024' - but the date today is 16th August 2024.
All the other date range choices work as intended.

### Debug information

Debug information generated at 2024-08-16 16:33:34 for Firefly III version **v6.1.19**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.19 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.9 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1113, base <span>#</span>86</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Australia/Sydney + Australia/Sydney</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_GB + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-08-15 14:00:00 (16 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-08-01 16:32:37</td></tr><tr><td>Session end</td><td>2024-08-01 16:32:37</td></tr><tr><td>View range</td><td>MTD</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

Selecting 'Today' should display the current date.
So for today, which is 16th August 2024, I would expect to see:
August 16th, 2024 - August 16th, 2024

### Steps to reproduce

Left-click on the 'Date range' text at top of the Dashboard page.
Open the drop down list of options.
Left-click on 'Today'

Instead of the current date displaying, the 1st day of the month is displayed as a 'range'.

**Comment by JC5** [comment]
Thanks, I'll check it out. What view range do you normally use?

**Comment by PAS-BC** [comment]
Hi James,

I usually use the current month, but I have just spent the last 3 days getting all my YNAB data sorted out in FF and starting to explore.

 

Cancelled YNAB sub today – woohoo 😊

 

I am just amazed at the depth of sophistication you have put into FF – I happened to click on the title links on the Dashboard last night – amazed at all the reports that appeared.

**Comment by JC5** [comment]
That's a great compliment, thanks!

I found the issue, it should be fixed in the next release. Not sure when it's going to be yet though.

**Comment by PAS-BC** [comment]
Aha, I’m just pleased I found a bug.

You may hear from me again LOL

 

tl:dr I was a Quality Auditor in my last role b4 ‘retiring’, though now busier than ever on my HomeLab journey amongst other things.

Must send you more coffee 😊
