### ISSUE TITLE
Importer importing transactions backwards, withdrawals are shown as deposits and visa versa

### ISSUE THREAD

**Issue by Kage1** [firefly-iii/firefly-iii#9144]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The FF3 importer as of the last update is importing transactions backwards. Withdraws it's importing as deposts and deposts it's classifying as withdrawals.

### Debug information

Debug information generated at 2024-08-17 16:46:49 Europe/Amsterdam for Firefly III Data Importer version **1.5.3**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.5.3</td></tr><tr><td>Build</td><td><span>#</span>643, base <span>#</span>86</td></tr><tr><td>System</td><td>PHP 8.3.9, Linux, apache2handler</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Amsterdam, America/Chicago</td></tr><tr><td>Environment</td><td>production</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td></td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36</td></tr></table>

### Expected behaviour

Withdrawals and deposts are handled as such and not reversed

### Steps to reproduce

Latest CSV from the bank.
Using my stanard import template
import the file
deposits and withdrawas are reversed in FF3

### Additional info

Logs redacted

```
FF3 Importer log
The submission routine has finished 🎉. Errors and messages can be seen below.

Message(s) from the import process
Line #0: Created deposit #3741 "PAYPAL <snip>" (USD 37.13)    **THIS IS ACTUALLY A WITHDRAWAL
Line #1: Created deposit #3742 "<aDeposit>" (USD 50.45)  ** THIS IS CORRECT
...
Line #17: Created withdrawal #3758 "PWP<snip>" (USD 10)  **THIS IS ACTUALLY A DEPOSIT
```
```
Bank Import CSV
Details,Posting Date,Description,Amount,Type,Balance,Check or Slip #
DEBIT,08/16/2024,"PAYPAL <snip>           08/16",-37.13,DEBIT_CARD,,,
CREDIT,08/16/2024,<aDeposit>,50.45,ACH_CREDIT,,,
...
DEBIT,08/12/2024,"PWP*<snip>               08/09",10.00,DEBIT_CARD,,,

```
Updated with a sample credit transaction that was correctly processed.

**Comment by JC5** [comment]
Thanks for reporting! 

It depends a lot on your configuration to determine if this is a bug, and changes may always occur in between versions. Could you share your import configuration please?

**Comment by Kage1** [comment]
[import_config_2024-01-13.json](https://github.com/user-attachments/files/16646648/import_config_2024-01-13.json)

See attached for the config.

As a side note I did imports on the previous version with no issues. I upgraded this morning and the issue started occuring. The config attached was last updated in January '24.

**Comment by Kage1** [comment]
After more testing I think I have narrowed down the issue. My bank provides a credit/debit indicator as well as a positive value for a deposit and a negative value as a debit. I had the Bank credit/debit indicator mapped to the field in my CSV. It appears, with the change noted below, is causing the importer to invert the amount value.

With the change in commit [9fa6afa](https://github.com/firefly-iii/data-importer/commit/9fa6afa47d1b7de87792a41b423191789339dad5) all of the array values were changed to lowercase and then forcing a match in lowercase from an import file. Based on the way the $negative array was previously used, the values were entered to be matched exactly as presented for the various banks.

Before the change the mapped indicator wasn't doing anything since it was case sensitive. Post change the indicator is matching and inverting the already correct positive or negative value. 

The quick fix was to remove the bank credit/debit indicator, but I can see this happening again to others since the [documentation](https://docs.firefly-iii.org/references/data-importer/roles/#bank-specific-creditdebit-indicator) indicates this is how it should be configured.

Is it possible the #9fa6afa change exposed an issue in the import routine when both credit/debit indicators are present as well as positive/negative values? e.g. if "debit" is present & the value is a negative then take as it is and visa versa.

**Comment by JC5** [comment]
If you have an amount field in your csv file which is correctly positive/negative according to the "direction" of the transaction, as well as a debet/credit column this is exactly what will happen because the latter overrules the first. 

The debet/credit column assumes the amount is always the same (i.e. always positive or always negative) and will correct the amount accordingly. If this isn't the case, you run into this issue. 

I don't consider this a bug. Please ignore the column in future imports. I will update the release notes to reflect the fact the debet/credit indicator responds to new terms.

**Comment by Kage1** [comment]
Sounds good, thanks for the info. I can confirm that updating my config to not map the credit/debit indicator does allow my csv to import successfully.
