### ISSUE TITLE
Can't initialize database

### ISSUE THREAD

**Issue by TomWis97** [firefly-iii/firefly-iii#915]
Hello,

Firefly-iii seems to be unable to setup the database for the first time for me. When I execute the `php artisan migrate:refresh --seed` command inside the Docker container, I get the following error:

![FireflyIII\Models\TransactionCurrency::validationMessages must return a relationship instance.](https://i.imgur.com/RNf3bFL.png)

I'm running Firefly-III in a Docker container using the Dockerfile provided in the repository. I have the following environment variables set: 
- FF_DB_HOST
- FF_DB_NAME
- FF_DB_USER
- FF_DB_PASSWORD
- FF_APP_KEY
- FF_APP_ENV

Firefly-iii seems to be able to write to the MySQL database. It creates 45 tables.

**Comment by JC5** [comment]
I haven't seen this error myself, I'll try and replicate it.

**Comment by JC5** [comment]
I've seen the bug myself, I can replicate it. I believe I have a fix, which I will include in the next release.

**Comment by JC5** [comment]
See also the new instructions:

https://firefly-iii.github.io/using-docker.html

**Comment by TomWis97** [comment]
Awesome, thank you very much!

With the new instructions for Docker, shouldn't [these](https://firefly-iii.github.io/using-installing.html) also be updated?

Also, I have two tips for the Docker support. The Dockerfile contains a lot of instructions. Every instruction generates a separate "layer" in the Docker image. Example: instead of
```RUN composer install --prefer-dist --no-dev --no-scripts
RUN composer dump-autoload
RUN php artisan firefly:instructions install
RUN php artisan optimize```
you should do
```RUN composer install --prefer-dist --no-dev --no-scripts && \
composer dump-autoload && \
php artisan firefly:instructions install && \
php artisan optimize```

I haven't found an official Docker image for Firefly III on the Docker Hub. We're supposed to build the image ourselves. Distributing the image through the Docker Hub simplifies the process of getting it up and running. Docker Hub has support for support for [automated builds](https://docs.docker.com/docker-hub/builds/). An automated build assures that the image in the Docker Hub is up-to-date with the latest version of Firefly III, because it automatically builds an new image with every push to the repo.

Should I open a new issue for these two points? Should this issue be closed?

**Comment by JC5** [comment]
Whoops I closed this without looking into your final comment @TomWis97, and I apologize.

Looking at issue #919, I will see if I can't combine these two problems and create an official Docker image.
