### ISSUE TITLE
Transfers to dates in the future

### ISSUE THREAD

**Issue by fib1985** [firefly-iii/firefly-iii#9152]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Future transfers are immediately accounted for and the related balances updated. Could be possibile to hold the money until the effective transaction date?

### Solution

Could be possibile to hold the money until the effective transaction date?

**Comment by JC5** [comment]
Hi, thanks for opening an issue!

I'm not going to add support for this. It's up to you to decide which date to use.
