### ISSUE TITLE
Schedule automatic import internally

### ISSUE THREAD

**Issue by UltraBlackLinux** [firefly-iii/firefly-iii#9154]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'd like to request that a tool automatically import data from my bank using the importer is integrated into the importer docker container.
As far as I'm aware, currently the only way to automatically import data using the importer is using an external cron job. I'd like to reduce complexity as far as possible and thus not rely on any external tools to manage container-specific features.

### Solution

Integrate cron, or maybe a custom solution into the importer container and let the user specify the schedule and importer configuration file.

Any logs could be displayed on the importer's own interface.

**Comment by JC5** [comment]
Hi, thanks for opening an issue!

I also like to reduce complexity as far as possible, so I will not be adding a cron job to the data importer Docker container. It has a single purpose (to service the data importer) and anything else is externalized. 

You are of course free to build something on top of the current container. Tools like supervisor can make the current container multi-task capable.

**Comment by UltraBlackLinux** [comment]
the problem with that being that the container is no longer independent. If I were to set up a cronjob I'd need to make changes to the hosting system, which makes it not only hard to keep track of what belongs to a container but also increases the maintenance burden for something that could just run by itself.

I'm generally not fond of having to handle anything related to a container's feature set outside of the container.

**Comment by JC5** [comment]
There is a cron capable container in the standard docker-compose.yml. 

If that's also not what you want, I'm not sure what to tell you.

**Comment by UltraBlackLinux** [comment]
I had in fact completely forgotten about that container, thanks for the reminder.

I'm running into some slightly confusing parts though. Since I now need to use requests to control the importer since cron is not bundled with it, I'll need to use this command to start the spectre import:
```
curl --location --request POST 'https://data-importer.example.com/autoupload?secret=YOURSECRETHERE' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer ey....' \
--form 'json=@"/local/path/to/json.json"'
```
I find this quite confusing though. I think the json is the config.json that I'm supposed to use, and I'd assume the `Authorization` header contains the personal access token I'd generated in the firefly III interface. But I don't get the `secret=YOURSECRETHERE` part. What kind of secret? I have everything configured in the env file but it appears like I cannot just issue a POST request to have FF-III read that out and handle everything itself, just like `php artisan importer:auto-import /path/to/your/files` would?

**Comment by JC5** [comment]
Glad to hear it works, I'll pick up your feedback for the documentation (and perhaps a better error :))
