### ISSUE TITLE
internal_reference_is does not correctly match numeric internal references

### ISSUE THREAD

**Issue by Lrns123** [firefly-iii/firefly-iii#9155]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Performing a search using `internal_reference_is` does not seem to work correctly when using numeric references, even when quoted in the search query. This issue is also causing the importer to not detect duplicates anymore when using such internal references ids (e.g. such as those as provided by Nordigen/GoCardless).

### Debug information

Debug information generated at 2024-08-19 14:14:29 for Firefly III version **v6.1.19**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.19 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.9 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1113, base <span>#</span>86</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Amsterdam</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / remote_user_guard</td></tr><tr><td>Login headers</td><td>HTTP_X_AUTHENTIK_EMAIL + </td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-08-18 22:00:00 (14 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 2</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-08-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-08-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0</td></tr></tbody></table>

### Expected behaviour

Given the following transaction: 
![transaction_example](https://github.com/user-attachments/assets/cea79a6d-6c8d-4486-94ff-040d5d8deddf)

I would expect a search for that reference number to match that transaction, yet it does not:
![missing_search](https://github.com/user-attachments/assets/00f84c49-d089-42e3-bacb-3970208fbfd9)

This functionality worked properly before 6.1.19.

### Steps to reproduce

1. Create transaction with (large) numeric internal reference id
2. Perform a search for `internal_reference_is:"<id>"`
3. No matches are found

### Additional info

The problem seems to be caused by this commit: https://github.com/firefly-iii/firefly-iii/commit/0cbd22426d73e7565226a329bd5d60eb9d01d1bc

Changing that line from `$this->query->where('journal_meta.data', '=', $internalReference);` to `$this->query->where('journal_meta.data', '=', json_encode($internalReference));` seems to solve the problem.

**Comment by JC5** [comment]
Nice find, and I get the solution for free! 🎉  I'll pick it up!

**Comment by cruzzoe** [comment]
Was just about to raise an issue but I think this might be related to what I am seeing too.

**Inside my importer json config.**
    "duplicate_detection_method": "cell",
    "ignore_duplicate_lines": true,
    "unique_column_index": 8,
    "unique_column_type": "internal_reference",
    
The above used to previously pick up duplicates. 
Now I have many duplicates ending up in ff3. 

Note, I build my own internal reference in python, but use the docker importer image. Is there any quick way I can remove the duplicates I've ended up with?

**Comment by cruzzoe** [comment]
I've downgraded to 6.1.18. This has removed the duplicates issue for me. Otherwise, every time I ran my upload, I got an additional transaction for every transaction for the last 100+ days. I'd love for this to be fixed in 6.1.20 otherwise I can't upgrade from this version. Appreciate you're busy and the work you do.

**Comment by cruzzoe** [comment]
Any chance for some help on this one? I've still got hundreds of duplicates which I can't manually remove from the UI.

I'm happy to remove from the database but it's unclear to me what will break if I do that...

I'm surprised it's only me that suffers from this issue. Does no one else rely on internal_id attr ?
