### ISSUE TITLE
Budget overview inconsistencies

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#916]
I was trying to set budgets for the current month, and as this is the first time I'm doing this, I was looking at my history and noticed some inconsistencies, big ones:

Chart of all transactions for budget Auto
![screen shot 2017-10-07 at 22 21 17](https://user-images.githubusercontent.com/3742238/31311523-29c6b04e-abae-11e7-9bbf-106656cfdedd.png)

List of all transactions (from the same budget page)
![screen shot 2017-10-07 at 22 21 41](https://user-images.githubusercontent.com/3742238/31311541-8ab26f88-abae-11e7-80e9-ecb964932866.png)

**Comment by JC5** [comment]
Run a default financial report. Is the amount the same? What does the (i) button tell you?

I would think such gross inconsistencies have been noticed before, so I'm curious what is going on.

**Comment by gavu** [comment]
Default financial report
* Date: 06.2017
* Accounts: all

Budgets:
![screen shot 2017-10-08 at 10 02 01](https://user-images.githubusercontent.com/3742238/31315065-14e9b510-ac10-11e7-895a-b5443e92b68d.png)

Category (in this case matches the budget name):
![screen shot 2017-10-08 at 10 02 25](https://user-images.githubusercontent.com/3742238/31315069-25ca9d2c-ac10-11e7-83ea-ee2ea574dca0.png)

**Comment by JC5** [comment]
I have no idea. They all call on the exact same function. The data ranges could differ though.

Delete all log files and run `php artisan ca:cl` on the command line. Then, visit this URL:

`/chart/budget/frontpage`

The log file should tell you what FF3 has collected to draw the chart. It does this X times for each budget.

Then, clear the cache again, remove the log files if necessary (against clutter) and visit this URL:

`/report-data/budget/general/1,2,3/20171001/20171031`

1,2,3 should be all your asset accounts. The result in the logs should be similar. Possibly a budget amount has been set against a different time range.

**Comment by gavu** [comment]
`/chart/budget/frontpage`
```
{"count":3,"labels":["Auto (October  1, 2017 and October 31, 2017)","Auto (October  1, 2017 and December 31, 2017)","Clothing (October  1, 2017 and December 31, 2017)","Fun","Home","Shopping (October  1, 2017 and December 31, 2017)"],"datasets":[{"label":"Spent in budget","type":"bar","data":["0","0","0","0","0","0"]},{"label":"Left to spend","type":"bar","data":["120.000000000000","150.000000000000","50.000000000000","100.000000000000","2000.000000000000","200.000000000000"]},{"label":"Overspent","type":"bar","data":["0","0","0","0","0","0"]}]}
```

`/report-data/budget/general/1,3,2,4/20170601/20170630`
```

Budget | Date | Budgeted | Spent |   | Left | Overspent
-- | -- | -- | -- | -- | -- | --
Auto |   | €0.00 | €-101.09 |   | €0.00 | €0.00
Clothing |   | €0.00 | €-121.64 |   | €0.00 | €0.00
Home |   | €0.00 | €-2,116.43 |   | €0.00 | €0.00
Shopping |   | €0.00 | €-1,124.92 |   | €0.00 | €0.00
(no budget) |   | €0.00 | €-1,164.39 |   | €0.00 | €0.00
Sum |   | €0.00 | €-4,628.47 |   | €0.00 | €0.00
```

Went back (to check if anything changed after the cache cleared), same inconsistencies, browser cache cleared too, no changes

FYI: This is not a fresh install. 
1. I imported all transactions
2. Updated all the rules/bills/budgets
3. Deleted all transactions via web by hand (took a while)
4. Imported all transactions back so the rules organise them like I want them to be
5. ... this is where I wanted to really work with budgets

Could it be, there are still some rows in the db that are added to the sum?

**Comment by gavu** [comment]
I could export some data out of the db for you, or at run some queries if it helps

**Comment by JC5** [comment]
I see three different date ranges in your code. Could that be the issue?

* Auto (October  1, 2017 and October 31, 2017)
* Auto (October  1, 2017 and December 31, 2017)
* 2017-06-01 2017-06-30

**Comment by gavu** [comment]
`/chart/budget/frontpage` generates for the current quarter, I guess, I set it to default in my preferences?

but the screenshots and the `/report-data/budget/general/1,3,2,4/20170601/20170630` are for june, the month where I found the issue

**Comment by gavu** [comment]
I would reset everything re-import all transactions but there is absolutely no way I would recreate all rules and bills by hand. A few days ago, I tried to cheat by creating a secondary environment and just copy the “bills*” and “rules*” tables, but then the import failed - I guess it was because of the encrypted information in the bills tables

**Comment by JC5** [comment]
If the app_key is the same it shouldn't fail. Keep that one consistent, and the user, and nothing should happen.

As far as I can tell the budget code is consistent across the board but it can be confusing. 

`/budgets`

The bars are based on your preferred range and the selected one (ie. quarter, 1-oct/31-dec). The amounts (called limits) you set for budgets are set for an entire range. See the table `budget_limits`. These limits can overlap if you create overlapping limits (for example, by setting FF to a monthly range). Expenses can fall into multiple limits if this happens.

`/budgets/show/x/x`

The chart for a specific budget limit (watch the URI) is daily by default. It shows all transactions within the range of the limit.

`/budgets/show/x`

The chart for a budget is per range-period (ie. per month or per quarter) and NOT per budget limit. This can be confusing but shows a more consistent overview of budget expenses. The boxes on the right are per budget limit.

**Comment by gavu** [comment]
I will start a fresh instance tomorrow, and copy the bills and rules tables. I will then import the transactions and let you know how it goes.

**Comment by gavu** [comment]
I did the following:

1. Created a new environment
2. Used the original key
3. Moved the following tables:

- accounts
- account_meta
- account_types
- bills
- budgets
- budget_limits
- rules
- rule_actions
- rule_groups
- rule_triggers

import failed ending:
```
Error importing line #1418: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`firefly`.`transactions`, CONSTRAINT `transactions_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `accounts_orig` (`id`) ON DELETE CASCADE) (SQL: insert into `transactions` (`account_id`, `transaction_journal_id`, `transaction_currency_id`, `amount`, `foreign_currency_id`, `foreign_amount`, `updated_at`, `created_at`) values (1, 1419, 1, 2773.01, , , 2017-10-08 17:46:50, 2017-10-08 17:46:50))
```

now I noticed that by renaming the original tables to eg. accounts_orig, the foreign keys did not match any more. Is it safe to delete the transactions by hand from the db? or should I create import/export sql statements from the bills/accounts/rules tables?

**Comment by gavu** [comment]
export/import also fails:

> INSERT INTO `firefly`.`rules`(`id`, `created_at`, `updated_at`, `deleted_at`, `user_id`, `rule_group_id`, `title`, `description`, `order`, `active`, `stop_processing`) SELECT `id`, `created_at`, `updated_at`, `deleted_at`, `user_id`, `rule_group_id`, `title`, `description`, `order`, `active`, `stop_processing` FROM `firefly_bkp`.`rules`
> 
> MySQL said:
> 
> #1452 - Cannot add or update a child row: a foreign key constraint fails (`firefly`.`rules`, CONSTRAINT `rules_rule_group_id_foreign` FOREIGN KEY (`rule_group_id`) REFERENCES `rule_groups` (`id`) ON DELETE CASCADE)

**Comment by gavu** [comment]
When I created the new environment, I forgot to copy the budget tables and started the import. The importer does not create the budgets, it only links them. Therefore, I must start all over... again... and it only took from 08:15 to 15:15 to import everything *facepalm*

**Comment by pkoziol** [comment]
<offtopic>Wow... how much data you must have (or how slow server :P) that import took 7 hours :O</offtopic>

**Comment by gavu** [comment]
3k+ transactions
~40 rules, each has about 6 actions
~20 bills

I am running a ultra powerfull RPi3 :)

**Comment by JC5** [comment]
If it really takes too much time, you could consider running it on your own PC, then transferring the imported database. 

The main bottleneck is memory, I think. Remind me every now and again to think about it. All these PHP objects are easy to build but hard to limit in memory usage.

**Comment by gavu** [comment]
I am still importing... but even now, it just doesn't look good. Here are the screenshots:

List of all transactions to the *Auto* budget (total: 101.09)
![916-transactions](https://user-images.githubusercontent.com/3742238/31501450-95f63180-af6a-11e7-856d-475a12585e2e.png)

Monthly overview (total 352.85)
![916-month](https://user-images.githubusercontent.com/3742238/31501456-9d9a09f2-af6a-11e7-8db1-8e992b6f2c42.png)

4 different periods, the last 2 are identical, but all have different amounts
![916-periods](https://user-images.githubusercontent.com/3742238/31501453-99e422e8-af6a-11e7-9865-f7f29d3867e7.png)

**Comment by JC5** [comment]
I’ll try to add debug lines to the journal collector so you can see what it is doing, and write some queries to see what the DB is doing.

**Comment by JC5** [comment]
```
select transaction_journals.* from transaction_journals
left join transaction_types ON transaction_types.id = transaction_journals.transaction_type_id
left join budget_transaction_journal ON budget_transaction_journal.transaction_journal_id = transaction_journals.id
where transaction_types.type != "Withdrawal" and budget_transaction_journal.budget_id is not null 

```

What do you get when you run this?

**Comment by gavu** [comment]
```
--
-- Dumping data for table `transaction_journals`
--

INSERT INTO `transaction_journals` (`id`, `created_at`, `updated_at`, `deleted_at`, `user_id`, `transaction_type_id`, `bill_id`, `transaction_currency_id`, `description`, `date`, `interest_date`, `book_date`, `process_date`, `order`, `tag_count`, `encrypted`, `completed`) VALUES
(493, '2017-10-12 07:07:35', '2017-10-12 11:58:59', NULL, 1, 2, NULL, 1, 'eyJpdiI6InVxeThSQldpUGJlYjFPV2NmVGlCbFE9PSIsInZhbHVlIjoiVDc0RytsWlVEc0VaTnlRZUE4bHlQUT09IiwibWFjIjoiYjU3N2ZmNzBjMjA3YTllMmU4ZTg5ZDBiNzgyNDhkMjA0MDgzNTUxMGU5NjkzZTc5YTg4MjNiM2M5ZDRiMTQzNSJ9', '2016-04-28', NULL, NULL, NULL, 0, 3, 1, 1);
```

**Comment by JC5** [comment]
Alright, you have at least one deposit with a budget it shouldn't have. You can fix it by editing it, then submitting it again. The rule code has been changed to prevent this from happening. 

I'm searching for bugs in the views you've taken screenshots of but nothing substantial so far.

**Comment by gavu** [comment]
You were right, I edited transaction 493, saved it and then the SQL returned zero results. The funny thing is, it was a cash deposit, to my wife's account, and it was assigned the budget "Shopping"... that ***must*** have been my wife work 😆

**Comment by gavu** [comment]
Would it help if I provided access to my DB, or a full DB dump? (I would change account details and important financial information, of course)

**Comment by JC5** [comment]
There are inconsistencies when dealing with cash transactions. I'm onto something. I'll keep you posted.

**Comment by JC5** [comment]
I've pushed some new code. Could you check it. Make sure you clear your caches.

**Comment by gavu** [comment]
I ran ```php artisan ca:cl``` and cleared browser cache, no change

**Comment by JC5** [comment]
OK, then the database dump is all I can suggest right now.

**Comment by gavu** [comment]
I’ll take a look through the data tomorrow, see what I need to rename/hide and send you an email. Thanks!

**Comment by gavu** [comment]
@JC5 , I've sent you an email with the dump

**Comment by JC5** [comment]
I may have found the problem and I've pushed a fix. I'm fairly sure the chart is correct but I'm careful. Could you verify?

**Comment by gavu** [comment]
The chart looks good, I'll keep an eye out for other inconsistencies. 

The only thing remaining is the right side - the monthly details (should I open a new issue?)

![screen shot 2017-10-15 at 14 10 50](https://user-images.githubusercontent.com/3742238/31584705-80e5187e-b1b3-11e7-9d6f-31934477a834.png)
- red rectangles: there are some divs, with hover css, which do not seem to "do" anything
- blue rectangles: identical timelines
- blue arrows: identical timelines show different amounts

**Comment by JC5** [comment]
Its ok, I’ll check it out :)

**Comment by JC5** [comment]
The red bars will be removed in the next update, I've added some if-statements.

The inconsistent amounts can occur occasionally when the system creates, for whatever reason, a double "budget limit". This shouldn't happen of course but is fairly harmless.

In the code I've just pushed, changing a budget limit will remove any extra entries.

Set your installation to Sep1-Sep30 using the date range bar. Then go to `/budgets` and change the amount for this budget to 15 or something. The double entry should be removed.

**Comment by gavu** [comment]
I did and it worked, now, I do have to say I had to change it to about 25 different values, refreshing the page every second time until the value finally stuck. I opened the browser console but could not find anything. Maybe my RPi is just too slow...

anyway, I declare the issue as fixed :) I can finally set my budgets correctly. THANKS!

**Comment by JC5** [comment]
It does a post in the background, be patient ;-).

If it doesn't work, delete the entries from your database. When the budget_id, start_date and end_date are equal, you may remove one of them (table budget_limits).

Thanks for helping me out!

**Comment by gavu** [comment]
Good idea. Will check it out next time.

No problem, it's a fun project :)

**Comment by JC5** [comment]
Closed, a new release is live.
