### ISSUE TITLE
Make notification sending asynchronous and support additional channels

### ISSUE THREAD

**Issue by realzsan3** [firefly-iii/firefly-iii#9161]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When notifications are enabled, after copying and editing a transaction, subsequent operations will only proceed after the notification has been sent (synchronously). This means that further actions are blocked until the notification process is completed. In certain scenarios (such as issues with Discord connectivity), the notification may not be sent promptly, causing delays in subsequent operations. Additionally, it would be beneficial to support other notification methods, such as Telegram, to provide more reliable notification options.

### Debug information

none

### Expected behaviour

1. Notifications should be sent asynchronously to ensure that subsequent operations are not blocked.
2. Support for multiple notification methods (such as Telegram) should be added, allowing users to choose the most reliable notification channel according to their needs.

### Steps to reproduce

1. Enable notifications.
2. Copy and edit a transaction.
3. Notice that subsequent operations are delayed until the notification is sent (synchronously), and existing notification channels may be unstable.

### Additional info

Suggested Solution:

1. Change notifications to be sent asynchronously, ensuring that subsequent operations are not affected by notification delays.
2. Add support for other notification channels, such as Telegram, to provide more flexible notification options.

**Comment by JC5** [comment]
Great idea, it's on the list.

I will not support telegram, however. If you want that, you'll have to use the API or webhooks.

**Comment by realzsan3** [comment]
I can use webhooks, e.g. https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getMe, is it supported？
[Telegram Bot API](https://core.telegram.org/bots/api#making-requests)

> Great idea, it's on the list.
> 
> I will not support telegram, however. If you want that, you'll have to use the API or webhooks.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/how-to/firefly-iii/features/webhooks/

You can't just send it to Telegram, you have to write something to convert the Firefly III JSON to a Telegram compatible message.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/8307
