### ISSUE TITLE
UX Improvements for creating new bookings

### ISSUE THREAD

**Issue by ftraxler** [firefly-iii/firefly-iii#9169]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'm actually typing a lot of bookings at once, so I've encountered a few things which could improve productivity by changing minimal stuff in the UX.

The "new transfer" form could have some UX boosts to speed up entering new bookings

### Solution

  Improve the UX for the form while creating a new booking
   - When clicking into the input field with auto complete options consider to select all text per default to just delete and type the other value, or expand all content without filtering. Currently I have to click into the field, delete the content, type new e.g. category.
     This affects both account fields and the category fields
     Example: I only see the currently selected category and need additional steps to change
     ![image](https://github.com/user-attachments/assets/5c77824c-adb6-454d-af46-ec498bcef5d1)

   - When typing a title, it suggest the titles by latest entry first. Consider sorting alphabetically with shortest text first
     Example: I need to create "Amazon" booking but I always see the latest entry with more infos and sometimes accidentally select it.
     ![image](https://github.com/user-attachments/assets/2a90e613-77a7-433d-8867-320c3efec2e8)

### Additional context

Of course these are just suggestions, and I totally understand that you will not solve everything.
Please feel free to consider at least the input form suggestions :)

**Comment by JC5** [comment]
Thanks for your suggestions!

I'm going to link you to https://github.com/firefly-iii/firefly-iii/issues/6304, where I'm collecting these improvements for the new Firefly III layout.
