### ISSUE TITLE
Dashboard 'Your Accounts' shown accounts inconsistencies

### ISSUE THREAD

**Issue by Wr0ngName** [firefly-iii/firefly-iii#917]
Hi,

Firstly, great job on the app, really a piece of work!

I have spotted a strange behavior based on the Expenses Accounts, or something that is not mentionned in the documentation:

- When created from the inline form while creating a new expense (_Add a new withdrawal_ page), it is not shown on the 'Your Accounts' chart displayed on the Dashboard.
- When created from the dedicated form however (_Create a new expense account_ page), this same account is then appearing on the chart, with a positive projection, quite messy.

I sadly don't have time to analyse the origin, but I do believe there are two assignations and they differ somewhat.

Keep it up!!

**Comment by JC5** [comment]
Nice find, I never thought to check it! I've fixed this, and since a new release was due anyway I've pushed v4.6.7 just now. You should be able to upgrade, and that issue (and many others) will be gone.
