### ISSUE TITLE
Overspending auto-budget that go negative the next month

### ISSUE THREAD

**Issue by Niols** [firefly-iii/firefly-iii#9188]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi, and thank you for this great piece of software :-)

I am happy to see that Firefly handles auto-budgets that roll over from one month to the next. However, I sometimes end up overspending my budgets and then I like to remove this amount from the budget of the next month. And sometimes I overspend so much that the amount for the next month should be negative. I wish Firefly would allow that.

### Solution

I think Firefly could easily allow for budgets to go negative. This could happen either globally or maybe on a per-budget basis. Note that doing that globally would a priori not break anything considering that there is currently no way to go negative except by putting that manually.

Then it is only a matter of either updating “Add an amount every period and correct for overspending” to not cap at 1, or to add a new “Add an amount every period and correct for overspending, going into negative” auto-budget type.

### What are alternatives?

I don't really need the auto-budget feature. It is a nice convenient but I am happy to report the budget amounts myself for the next month. However, this is also not possible because one cannot manually set a budget to be negative. This would however be totally sufficient for me and is maybe more accessible. Should I open a separate issue?

### Additional context

Actually, the _interface_ lets you enter a negative amount in the budget, so I first believed that it was possible. However, once I updated the budget page, I discovered that my negative number had been interpreted as its absolute value! Which I found quite surprising. See for instance the following screenshot where, on entering a negative amount in the Health category, there is more money left than what was spent in the month. Updating the page after that would show a budget of 1.60 €.

![image](https://github.com/user-attachments/assets/582387f5-fb16-4f62-ba7d-321ee5f74678)

**Comment by JC5** [comment]
Hey, great question! And thanks for the compliments :) 

This will not be a feature. I appreciate the need so see how much you need to correct your budgets with, but negative budget amounts will not become an option.

**Comment by 2IIZ** [comment]
Hi, I was just thinking the same as Niols. Why can't a budget be negative? Is it a technological limitation or more of a financial one?

It would be a great feature, as people like to carry their budget from month to month. If we have a fixed salary, I don't see why it shouldn't be possible to have a negative budget, since our budget is based on our income.
