### ISSUE TITLE
Twig error during Docker build

### ISSUE THREAD

**Issue by ms32035** [firefly-iii/firefly-iii#919]
Running `docker build .` ends with an error
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
production.ERROR: Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': No application encryption key has been specified. {"exception":"[object] (InvalidArgumentException(code: 0): Cannot instantiate Twig extension 'TwigBridge\\Extension\\Laravel\\Session': No application encryption key has been specified. at /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/ServiceProvider.php:236)"} []

  [InvalidArgumentException]
  Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': N
  o application encryption key has been specified.
```
It looks as a regression introduced by #915 

The image build should not be dependent on any encryption key, cause this makes the key public.

**Comment by JC5** [comment]
That could be, although I am pretty sure I tested this. But you never know!

I'll look into it!

**Comment by JC5** [comment]
https://firefly-iii.github.io/using-docker.html

**Comment by JC5** [comment]
I've pushed a new release that should fix this as well.

**Comment by Jumanjii** [comment]
Still have the same error ;-(

**Comment by JC5** [comment]
Did you remove the old images?

**Comment by Jumanjii** [comment]
Don't really need. First pull 4 hours ago.

**Comment by JC5** [comment]
Are trying to run it using docker, or docker-compose?

**Comment by Jumanjii** [comment]
Ok. I try it on local and it worked ^_^
Sorry for that, i will investigate why it dont on my remote mediavault.
By the way, congratulation, really nice work ! :-)

**Comment by JC5** [comment]
No problem, I'm glad it works!

I just realised the problem is probably the absence of a `.env` file when you use docker and not docker-compose.

If you create this file yourself, filling in the details as the [installation guide](https://firefly-iii.github.io/using-installing.html) says, it should work as well!

**Comment by Jumanjii** [comment]
So yes I can confirm : it was the docker run that was trigger the error :+1:
