### ISSUE TITLE
data importer via gocardless EU - details of the account is not imported anymore after last two versions

### ISSUE THREAD

**Issue by fate8383** [firefly-iii/firefly-iii#9194]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi, it used to have account name and a bit more details than just account number when imported via gocardless, now it only grabs account number (IBAN and local). I happen to have an account which holds many currencies in the same number so you can imagine I test try each one now either it is EURO or USD or else...I have named the accounts on the Bank end and this was being imported before which helps a lot. Would this be possible to have back importing account names?

### Debug information

not a bug so some feature changed recently.

### Expected behaviour

grab account names from go cordless import 

### Steps to reproduce

n/a

### Additional info

n/a

**Comment by JC5** [comment]
Hi, thanks for opening an issue.

I have no influence over the details that GoCardless provides, sorry. If this has changed recently you must take it up with GoCardless I'm afraid.

**Comment by Administratoor** [comment]
Hi for me it looks like you want to set `GOCARDLESS_GET_ACCOUNT_DETAILS=true` in your .env file.
This was introduced in this version https://github.com/firefly-iii/data-importer/commit/fb1905951b4c0c6bccbe0f06c36c5be2b096ded4 to save Api requests.

**Comment by JC5** [comment]
Aha, you mean the details you see in the UI itself?

**Comment by fate8383** [comment]
> Hi for me it looks like you want to set `GOCARDLESS_GET_ACCOUNT_DETAILS=true` in your .env file. This was introduced in this version [firefly-iii/data-importer@fb19059](https://github.com/firefly-iii/data-importer/commit/fb1905951b4c0c6bccbe0f06c36c5be2b096ded4) to save Api requests.

this makes sense :) sorry I didn't see that I had to adjust the .env it just stopped working, maybe if we left is default as true then I wouldn't have noticed. It is correct that also it was checking balance and it stopped doing that. I will adjust and test now.

**Comment by fate8383** [comment]
fantastic, edited .env with those mentioned above and all is golden again! Thanks

**Comment by JC5** [comment]
Ah nice, I'll pick this up so FALSE will also work in the UI.

**Comment by fate8383** [comment]
> Ah nice, I'll pick this up so FALSE will also work in the UI.

Didn't understand that :) so I can remove from .env entries and it will still work after you change it?

**Comment by JC5** [comment]
Exactly!
