### ISSUE TITLE
Data importer error: `sleep: Argument must be greater than or equal to 0`

### ISSUE THREAD

**Issue by fpringle** [firefly-iii/firefly-iii#9199]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After connecting to GoCardless, the importer crashes with error:
```
sleep(): Argument #1 ($seconds) must be greater than or equal to 0
app/Services/Nordigen/Request/Request.php :407
```

### Debug information

Debug information generated at 2024-09-04 15:55:52 Europe/Amsterdam for Firefly III Data Importer version **1.5.4**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.5.4</td></tr><tr><td>Build</td><td><span>#</span>653, base <span>#</span>88</td></tr><tr><td>System</td><td>PHP 8.3.10, Linux, apache2handler</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Amsterdam, Europe/Berlin</td></tr><tr><td>Environment</td><td>local</td></tr><tr><td>Debug mode</td><td>true, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td>*</td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36</td></tr></table>

### Expected behaviour

Importer should procede to the page where I can choose account, mappings etc.

### Steps to reproduce

1. Open importer
2. Click "Import from GoCardless"
3. Upload a config file or click "Next" and input bank details + authenticate (I've had the error both ways)
4. Error

### Additional info

Here are the logs from the data importer (account details redacted):
[importer-logs.txt](https://gist.github.com/fpringle/48a5ac1b9fcb275bdcd46244944164fd)

**Comment by JC5** [comment]
Thanks for opening an issue!

Please upgrade to v1.5.5.

**Comment by fpringle** [comment]
Thanks @JC5! And thanks for creating such an awesome open-source project :)
