### ISSUE TITLE
Problem on Installation - Step 2

### ISSUE THREAD

**Issue by DeltaKiloz** [firefly-iii/firefly-iii#920]
I have an issue with Step 2 of your installation when I attempt to execute the composer command: 
![firefly](https://user-images.githubusercontent.com/5963159/31419266-da1d590a-ae08-11e7-8d51-4f3508135f36.PNG)

**Comment by JC5** [comment]
Firefly III requires PHP 7.1.

**Comment by DeltaKiloz** [comment]
I thought I had fully upgraded it, but indeed I had not. That solved the above error, thanks!
