### ISSUE TITLE
Piggy Bank link to an existing transfers 

### ISSUE THREAD

**Issue by moimoi333** [firefly-iii/firefly-iii#9203]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Is it possible to link transfers with a piggy bank after it has been created, in edit mode? 
My transactions are imported from data importer, and I'd like to link transactions with piggy banks as in #6073 but on existing transferts. 

### Solution

Add piggy bank selector in transfert edit page

**Comment by JC5** [comment]
Hi, thanks for opening an issue.

This is not possible, and will not be added. Sorry about that.

**Comment by moimoi333** [comment]
is there any solution when converting the transaction into a transfer?
