### ISSUE TITLE
Synchronise account transactions through API importation

### ISSUE THREAD

**Issue by F-DXI** [firefly-iii/firefly-iii#9210]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'd like Firefly or data-importer to synchronize account transactions from the GoCardless API.

### Solution

I had a limitation with the GoCardless importation and my bank. Pending transactions is imported with an ID from the Data-importer and when it becomes a booked one, the ID from my bank changes and the transaction is created again generating a duplicate.

The feature would work like this : 
Based on a check box that says *synchronize this account* on the Firefly account or maybe in the Data-importer itself, the requested feature would verify all transactions with the duplicate control field from data-importer on the same period than the GoCardless API and act like the following : 
- Transaction exists in API and doesn't in Firefly --> Data-importer creates the transaction
- Transaction exists in both API and Firefly --> No action
- Transaction doesn't exist in API but does exist in Firefly --> Delete the transaction from Firefly

That way, Firefly would be the closest to the bank account data.

### What are alternatives?

As I read in a discussion here, you could add a rule that delete automatically the pending transactions on import. In this case, you would never see a pending transaction in Firefly and would only have booked transactions.

Or like I did, create your own dirty python script that request directly API from GoCardless and Firefly to apply this logic =D

**Comment by JC5** [comment]
Hi, great question!

You'll have to keep using the Python script I'm afraid, I'm not going to build this.
