### ISSUE TITLE
Liability amount due calculated incorrectly on liabilities list when the liability is settled with a transfer to another liability

### ISSUE THREAD

**Issue by uumas** [firefly-iii/firefly-iii#9225]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When creating a transfer from one liability account to another, the amounts due for those accounts on /accounts/liabilities get calculated in reverse.

### Debug information

Confirmed this on demo.firefly-iii.org, no debug info available

### Expected behaviour

see reproduction step 4

### Steps to reproduce

1. Create liability liab1 with amount 20€
2. Create liability liab2 with no opening balance
3. Create a 20€ transfer from liab2 to liab1
4. Amount due on liab1 should be 0 and on liab2 20€, but on /accounts/liabilities page it shows 40€ on liab1 and -20€ on liab2

**Comment by JC5** [comment]
This will be fixed in Firefly III v6.1.22

**Comment by mattheweigand** [comment]
I'd like to report that this is fixed in the development branch and my account balances are beautifully zero.

**Comment by uumas** [comment]
Oh, yeah fixed in stable too <3
