### ISSUE TITLE
Revenue Transaction | Assign To Bill

### ISSUE THREAD

**Issue by Barrow1990** [firefly-iii/firefly-iii#9229]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When you have assigned a transaction to a bill via a rule you have the option for link to bill on the transaction.
If you have a generic transaction you can't manually assign it to a bill.

Specific Scenario:
I have loan account that happened to take double payments.
This has been created as a transfer as I have the liability available.
The refund just happens to come in as "Cheque Deposit"
This been to generic means I can't really automate this but actually just manually change the item.

### Solution

Add option on the transaction to assign to a bill

### What are alternatives?

Create a specific rule to create the link

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

I'm not sure what you want. Could you elaborate?

**Comment by Barrow1990** [comment]
Closing this out as the item in question is visible if I tick the "transaction links"
I would of expected it to have its own item in the preferences panel

**Comment by JC5** [comment]
Mmm, interesting! 

It should not be under "transaction links". I still don't know what you are looking for exactly. But I will investigate! 🕵️

**Comment by Barrow1990** [comment]
> Mmm, interesting!
> 
> It should not be under "transaction links". I still don't know what you are looking for exactly. But I will investigate! 🕵️

Apologies for not giving enough information.

The original issue was that I couldn't see the Bill option on an expense.
This was an issue I wasn't aware of and it was hidden behind the "transaction links" button on the preference page.

I then found that I wanted to assign a revenue type transaction to a bill but it doesn't have this option under the revenue type transaction.

So this issue is now related to a revenue transaction.

**Comment by JC5** [comment]
Revenue transactions cannot be linked to bills. This will not change.

**Comment by Barrow1990** [comment]
Thank you for your response.
