### ISSUE TITLE
Composer error upgrade to 4.6.7 from 4.6.5

### ISSUE THREAD

**Issue by dzaikos** [firefly-iii/firefly-iii#925]
FreeBSD 10 jail running PHP 7.1. I'm upgrading from 4.6.5 to 4.6.7 (but 4.6.6 produces the same error); I run the composer command:

    composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated 4.6.7

And get the following error:

```
 php artisan firefly:instructions install
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v4.6.7!                                |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
> @php artisan key:generate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > 
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Aborted                                                 
                                                          

Script @php artisan key:generate handling the post-create-project-cmd event returned with error code 1
```

I have a stack trace if that helps.

I'm not entering *no* at that prompt. The script shows it but immediately aborts with the message that follows it.

Thoughts?

**Comment by JC5** [comment]
You have found a bug! Thanks for reporting this!

The core of the issue is that the `.env.example` file has this line:

```
APP_ENV=production
```

It should be:

```
APP_ENV=local
```

When the value is `production`, most commands will ask for confirmation. And since you have no keyboard to enter yes or no (the system executes the command) it will stop.

You can run the following command to try again (and enter "yes"):

```
php artisan key:generate
```

It should return with something like:

```
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Application key [base64:5s6gAzHlgle//Ebl5cckfav98/++C5ZYvoHk5/Kaq1I=] set successfully.
```

Then, you can continue with the upgrade guide.

Let me know if it works!

**Comment by dzaikos** [comment]
Yes, running `php artisan key:generate` works.

Thanks!

**Comment by JC5** [comment]
I've pushed a new release which should fix this!
