### ISSUE TITLE
Transfers are not included in Category/Tag reports

### ISSUE THREAD

**Issue by ThePMO** [firefly-iii/firefly-iii#9250]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Transfers are not included in Category and Tag reports. 

### Debug information

not available in demo

### Expected behaviour

A Category or Tag report that includes only one! account should list all transfers as expenses or incomes depending on the direction. 
A Category or Tag report that includes multiple accounts should list all transfers to accounts that are NOT included in the report as expenses or incomes depending on the direction, and ignore transfers between accounts included in the report

### Steps to reproduce

1. open the demo
2. Add a Category/Tag to a transfer
![Screenshot 2024-09-18 200957](https://github.com/user-attachments/assets/6fdae340-233a-44f9-9e38-b820897a335b)
3. Verify, that transfer is correctly summed in default financial report
![Screenshot 2024-09-18 201124](https://github.com/user-attachments/assets/ddb65712-c26d-43fa-b5f4-b7ae1822c213)
![Screenshot 2024-09-18 201400](https://github.com/user-attachments/assets/7c8aa0b9-4f8c-4c8a-b779-d6bd764b44f3)
4. Open the Category/Tag report for the same Date Range for the same account with the Category/Tag from step 2
![Screenshot 2024-09-18 201201](https://github.com/user-attachments/assets/0e8644cc-f8c0-4ce2-a761-ebdf73ac97f4)
5. See that Sum is different, transfer is not included
![Screenshot 2024-09-18 201311](https://github.com/user-attachments/assets/748b38e1-ebcb-4d32-937d-64d809f4f22d)

**Comment by JC5** [comment]
Hi, thanks for opening an issue!

This is not a bug, and will not be fixed. Transfers between accounts in a report will always be ignored.

**Comment by ThePMO** [comment]
May I ask why? How can I analyse cross-account transfers?

**Comment by JC5** [comment]
This will be improved in the new layout. I have to rewrite the reports from the ground up anyway. Thanks for bringing it to my attention, I will pick it up in https://github.com/firefly-iii/firefly-iii/issues/6311
