### ISSUE TITLE
Link to piggy bank not stored when creating transaction via [POST] /v1/transactions

### ISSUE THREAD

**Issue by brot** [firefly-iii/firefly-iii#9253]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When sending request to [POST] /v1/transactions and setting the "piggy_bank_name" to a valid piggy bank name in the TransactionSplitStore object, the transaction will be created, but there is no link to the piggy bank stored. 
Also the piggy bank doesn't know anything about this transaction

### Debug information

Debug information generated at 2024-09-21 18:02:13 for Firefly III version **v6.1.19**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.19 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.9 (64bits) / apache2handler / Linux aarch64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1113, base <span>#</span>86</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Vienna + Europe/Vienna</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-09-20 22:00:00 (18 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-09-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-09-21 23:59:59</td></tr><tr><td>View range</td><td>MTD</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0</td></tr></tbody></table>

### Expected behaviour

If I set the "piggy_bank_name" I want the created transaction linked to the given piggy bank

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

Are you aware that this will only work for transfers?

**Comment by brot** [comment]
Hi @JC5 

Thanks for the quick feedback.
No, I'm not aware that this will only work for transfers, because it's possible to add a withdrawal in the UI and link a piggy bank. This works fine.
Why is this different when creating a transaction via API?

**Comment by JC5** [comment]
Mmm, not a clue. The UI also uses the API. If you can mimic that, you're fine.

**Comment by brot** [comment]
@JC5 After activating DEBUG log and reading some code, I found the problem.
The piggy-bank was assigned to an account which was not part of the transaction. Therefore there was no new piggy bank event.

**Comment by JC5** [comment]
Nice, thanks for sharing!
