### ISSUE TITLE
Laravel log file is owned by root and cannot be accessed. results in "Whoops"

### ISSUE THREAD

**Issue by Aquariu** [firefly-iii/firefly-iii#926]
This is not really an issue in Firefly itself but a kind reminder to other people who could make the same mistake I did. I write this here so that it can be useful to someone else.

Please find below the content of the `storage/logs` directory

```
14:31 root@falken /var/www/firefly-iii/storage/logs # ll
total 64K
-rw-r--r-- 1 www-data www-data 960 oct.  10 22:59 laravel-2017-10-10.log
-rw-r--r-- 1 www-data www-data 56K oct.  12 20:55 laravel-2017-10-12.log
-rw-r--r-- 1 root     root     714 oct.  14 11:19 laravel-2017-10-14.log
```
As you can see, the php process, run as user `www-data` cannot access the file in write mode because it is owned by root and this results in:
```
 (1/1) UnexpectedValueException

The stream or file "/var/www/firefly-iii/storage/logs/laravel-2017-10-14.log" could not be opened: failed to open stream: Permission denied
```
This happens when navigating the left menu to the Budget section.
If I manually change the file ownership so www-data and empty cache (`php artisan cache:clear`) then everything seems back to normal.

I tracked this error to the script I use to automatically import my banking data to Firefly. The script I wrote is owned and run by root via a cronjob. Obviously, all the `php artisan firefly:create-import` lines seem to log something to this file and this results in the error seen above. I'll update the cronjob to execute php as the www-user and expect that it will fix the issue. At least I can see already that the log script stays owned by www-data/

Kind regards,

Olivier

**Comment by gavu** [comment]
Automatic import? Sounds yummy. If I may ask, what exactly are you importing, do you have direct access to your bank’s transactions? I would also like to achieve something similar, however, I did not manage to automatically download them... yet

**Comment by Aquariu** [comment]
I use the [boobank](http://weboob.org/applications/boobank) software (part of the weboob package) to collect the banking data. It's available as a debian package in my repos do I didn't need to download anything, just `apt-get install weboob`, in my case.

First I use boobank in interractive mode to gather the account numbers, and save the credentials for the user running the thing on your computer/server. This is called the bank backend in boobank (don't remember exactly the command line options, but the man page was very informative).

Then download each account csv once, and manually import them in firefly via the web interface. Be sure to save a separate json file for each and every account! (so that the automated import puts the transactions in the correct account)

Then, in a simple bash script, I create a directory with today's date to save the csv files from the bank, go to the firefly install directory, and for each account I call boobank to download the operations in a csv file, and use the command line interface to firefly to import the csv file in Firefly using the correct account-specific json file and the user's token.
The result looks like this:
```
#!/bin/bash
mkdir -p /path/to/csv/firefly/$(date +"%Y_%m_%d")
cd /path/to/firefly/install
echo "first account"
boobank -b <bank backend name saved previously > history <account umber> -n <number of operations to download> -f csv -O /path/to/csv/firefly/$(date +"%Y_%m_%d")/$(date +"%Y_%m_%d")_account_1.csv
sudo -u www-data php artisan firefly:create-import /path/to/csv/firefly/$(date +"%Y_%m_%d")/$(date +"%Y_%m_%d")_account_name_1.csv /path/to/json/account1.json --user=1 --type=csv --start --token=<your user's firefly token>
```

And repeat those last three lines for each and every account from this or another bank, adapting to your needs.
You can run this script manually or you can programm it to run daily, weekly, monthly... whatever suits you, with a cronjob: Open your cron settings as root (`crontab -e`) and add:
`0 5 * * 1 sh /path/to/your/script/boobank-download.sh`
And hopefully it should run every week. (which is more than enough for me)

**Comment by JC5** [comment]
I've pushed a fix for this, which will rewrite the log files names according to their use (cli, fpm, apache2handler, etc). That should fix this problem partly and make it even less likely to happen.
