### ISSUE TITLE
Update data-importer to reflect aquisition of Nordigen by Gocardless

### ISSUE THREAD

**Issue by gene1wood** [firefly-iii/firefly-iii#9272]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The [data-importer README](https://github.com/firefly-iii/data-importer/blob/db34064e05ad2a8776c75e033a636ee2bd76801a/readme.md#L35) still refers to Nordigen and links to a site that no longer exists.

https://gocardless.com/en-us/g/gc-nordigen/

You may want to update this (and any other references or documentation) to talk about Gocardless instead of Nordigen

### Debug information

This is an issue on the data-importer documentation so there's no debug info

**Comment by JC5** [comment]
Thanks for opening an issue! I'll pick it up.
