### ISSUE TITLE
Long wait when editing a transaction

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#9275]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The edit transaction dialog may take a long time to save the transaction. 

### Debug information

No need.

### Expected behaviour

Be fast.

### Steps to reproduce

Edit a transaction.

### Additional info

Caused by an inefficient running balance column calculation.

**Comment by rluetzner** [comment]
Could this also explain why the data-importer takes multiple minutes per line to add a transaction?

I only run it once every few months and while it was never super fast, I definitely noticed a severe slowdown today. I'm still trying to import a CSV with about 200 lines. The first attempt timed out eventually after importing 60 lines or so.

**Comment by JC5** [comment]
That's quite possible yes. I hope the next release will fix this, and it will come out tomorrow.

**Comment by rluetzner** [comment]
Awesome. Thanks for all the hard work. I love using Firefly. 🙂

**Comment by rluetzner** [comment]
Can confirm that the issue I saw was related. At least it's fixed with the latest release. 🙂

Imports are now just as quick as before.
