### ISSUE TITLE
Sorting bills

### ISSUE THREAD

**Issue by jenwirth** [firefly-iii/firefly-iii#9276]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

There's a closed issue that never made it to the new design i think: #3936 . 

It would be really helpful if one could sort the bills in order to see what upcoming bills there are next

### Solution

Add sortable columns to the bills table.

### What are alternatives?

use a browser plugin that sort tables

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

I'm going to merge this with https://github.com/firefly-iii/firefly-iii/issues/6306
