### ISSUE TITLE
Update to v6.1.20 changed Balance of Account

### ISSUE THREAD

**Issue by JeuJeus** [firefly-iii/firefly-iii#9278]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

With the update from version v6.1.19 to v6.1.20 the Account balance of my main account changed.
The Balance is miscalculated i.e. several hundreds of euros are missing.
Reverting to the previous version does fix the calculation, with the balance now exactly matching my remaining budget (which should be the same the way i handle accounting, not generally applicable).

This seems to stem either from some miscalculation in the frontend or some payment now being included for calculcation that was previously missing?
Therefore this could either be a bug or intended behavior (i found nothing related to that in the changelog).

Due to only a single number involved i have nothing to attach at the moment, but can provide further information.

### Debug information

Debug information generated at 2024-09-28 16:15:36 for Firefly III version **v6.1.20**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.20 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.11 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1123, base <span>#</span>90</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + Europe/Berlin</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + de_DE</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-09-27 22:00:00 (16 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td></td></tr><tr><td>Session end</td><td></td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The balance of my main account should not change on version changes.

### Steps to reproduce

Upgrade Docker Image for firefly app from  v6.1.19 to v6.1.20.

**Comment by JC5** [comment]
I see what you mean, thanks for opening an issue. This should be resolved with tomorrow's release of 6.1.21.

**Comment by JeuJeus** [comment]
Thank you very much for not only the quick response but the timely fix!

**Comment by JC5** [comment]
Sure thing, sorry for breaking things!
