### ISSUE TITLE
Error on composer script

### ISSUE THREAD

**Issue by DeltaKiloz** [firefly-iii/firefly-iii#928]
Did a fresh install, running the composer command:

`composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.6.7`

And reviewed the following error:

![firefly_error](https://user-images.githubusercontent.com/5963159/31581231-2ead8020-b134-11e7-8502-7b41d87d5e9f.PNG)

**Comment by JC5** [comment]
See https://github.com/firefly-iii/firefly-iii/issues/925

**Comment by DeltaKiloz** [comment]
Should this have been fixed in your last update? It look like it still loads APP_ENV=production from the .env.example into .env after just now doing another fresh install. I still get the error after doing the composer command.

**Comment by JC5** [comment]
Did you run the command using `4.6.8` at the end?

**Comment by DeltaKiloz** [comment]
That did the trick, however I'm getting an HTTP 500 error now when browsing to http://IP/firefly-iii/public , and the storage/log folder is empty. Anything else I can look at to narrow down what my issue is?

**Comment by JC5** [comment]
Check out the Apache logs or the nginx logs, those usually have more
details. Make sure your www-data user is owner of the firefly directory and
has write access.
