### ISSUE TITLE
Dashboard graph doesn't show negative sign in tooltips

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#929]
When hovering a dot in the main dashboard graph, negative amounts show up with no minus sign in the tooltip

**Comment by JC5** [comment]
They do for me, I'm afraid. It also seems to work on the demo site.

Which language are you using Firefly III in?

**Comment by skuzzle** [comment]
I was using english. When I change to German, the amounts show up correctly with minus sign.

**Comment by JC5** [comment]
Could you surf to this file, and copy and paste the content? Make sure Firefly III is set to the broken language.

`/jscript/variables?ext=.js&v=4.6.x`

You don't have to copy the token on the last line.

**Comment by skuzzle** [comment]
```
// date ranges
var ranges = {}
    ranges["October 1, 2017 - October 31, 2017"] = [moment("2017-10-01"), moment("2017-10-31")];
    ranges["September 2017"] = [moment("2017-09-01"), moment("2017-09-30")];
    ranges["November 2017"] = [moment("2017-11-01"), moment("2017-11-30")];
    ranges["Everything"] = [moment("2017-10-01"), moment("2017-10-15")];

// date range meta configuration
var dateRangeMeta = {
    title: "October 1, 2017 - October 31, 2017",
    uri: "https://firefly.projectpolly.de/daterange",
    labels: {
        apply: "Apply",
        cancel: "Cancel",
        from: "From",
        to: "To",
        customRange: "Custom range"
    }
};

// date range actual configuration:
var dateRangeConfig = {
    startDate: moment("2017-10-01"),
    endDate: moment("2017-10-31"),
    ranges: ranges

};


var language = "en_US";
var currencyCode = 'EUR';
var currencySymbol = '\u20AC';
var mon_decimal_point = ".";
var mon_thousands_sep = ",";
var frac_digits = 2;
var noDataForChart = 'There is not enough information (yet) to generate this chart.';
var showFullList = 'Show entire list';
var showOnlyTop = 'Show only top 10';
var accountingConfig = {"pos":"%s%v","neg":"(%s%v)","zero":"%s%v"};
```

**Comment by JC5** [comment]
Ultimately, this depends on the version of the [icu library](http://site.icu-project.org/) your system is compiled against. I can't find an example with negative numbers ([this one doesn't have them](https://ssl.icu-project.org/icu-bin/locexp?_=en_US)) but when those rules define parentheses as a negative indicator, Firefly III will use them.

I know what your next question is going to be and unfortunately I can't change this from Firefly III.
