### ISSUE TITLE
Repetition counts ignored for recurring transactions

### ISSUE THREAD

**Issue by Syncena** [firefly-iii/firefly-iii#9294]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

As mentioned in this [discussion](https://github.com/orgs/firefly-iii/discussions/9293), repetition counts for recurring transactions are being ignored.

Summary: the repetition count is not shown when viewing the recurring transaction, and transactions will continue to be posted beyond the desired number of repetitions.

### Debug information

Debug information generated at 2024-10-01 17:26:01 for Firefly III version **v6.1.21**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.21 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.4 (64bits) / fpm-fcgi / NetBSD evbarm</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/London + Europe/London</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / audit_daily</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_GB + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-10-01 04:00:01 (12 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 2</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td></td></tr><tr><td>Session end</td><td></td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :x:<br>en_GB.UTF-8: :x:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15</td></tr></tbody></table>

### Expected behaviour

Repitition counts for recurring transactions should be honoured.

### Steps to reproduce

See screenshots in discussion thread linked in Description

**Comment by Otanga-Otieno** [comment]
@Syncena Are you using the --force flag when calling the cron job?

**Comment by Syncena** [comment]
No. This is the crontab line I'm using:

`0 5 * * * /usr/pkg/bin/php /u0/www/firefly-iii/current/artisan firefly-iii:cron`

**Comment by JC5** [comment]
I can't replicate this. I would like to see some logs before I continue.

- I created a daily recurring transaction. Max runs, 3x. 
- After kicking off the cron job 3 times (without `--force`) I get the error I expect.
- After this point, the UI also refuses to create more transactions.

I have added the count and max to the UI.

**Comment by Syncena** [comment]
Wife is reporting that the problem persists. What log settings would be useful so help diagnose the issue?

**Comment by JC5** [comment]
Let's start with some screenshots. Could you replicate this shot for me? Can be found at `/recurring/edit/x`

![Image](https://github.com/user-attachments/assets/38b7e3fc-1fa9-4eb6-971f-a8575d89d078)

Naturally, I expect the repetition settings to be the same without you changing them.

Also interesting is the number of transactions in this list. Can be found at `/recurring/show/x`

![Image](https://github.com/user-attachments/assets/66dead3d-7cec-47da-a309-5b44d0a4fcad)

**Comment by Syncena** [comment]
Screenshot of /recurring/edit/x for a recurring transaction started in July this year, with repetition count set to 4.

![Image](https://github.com/user-attachments/assets/dc78667f-5756-4cbb-8cf8-e74861212c27)

So this recurring transaction should be done and dusted as of October. However, here's the corresponding screenshot for /recurring/show/x (split in two as it required scrolling):

![Image](https://github.com/user-attachments/assets/0f570e76-98fa-4b23-bfab-80fcbc4b095a)

![Image](https://github.com/user-attachments/assets/3b6f365b-7508-465c-8860-e56551864f19)

As you can see, "Expected deposits" indicates more transactions will occur over the coming months.

**Comment by JC5** [comment]
So it displays more transactions, but did it actually create them?

**Comment by Syncena** [comment]
Yes, the additional transactions will be created, at least according to my wife. We can wait until Nov 12 to prove her right if you want.

**Comment by JC5** [comment]
Thanks for explaining what the issue is, I will pick it up right away. No need to wait for November 12, as I just explained the important part works as expected. 

I will make sure the list is trimmed as well.

**Comment by Syncena** [comment]
Thanks for the quick fix! Do you plan to apply the patch the v6.1 branch?
