### ISSUE TITLE
Rules > Rule > Action

### ISSUE THREAD

**Issue by EricVanCaenenberghe** [firefly-iii/firefly-iii#9303]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

upgrade from 6.1.19 to 6.1.21 apparently the number of possible actions have been reduced, and no longer possible actions have been replaced by other actions.
The replacement action has not the same result as the initial action.

Used action:
Action
Add text as prefix in the description
Action-value
"some_text"

Result
some_text followed by the old description

Replacement action:
Action
replace description with 
Action-value
\="some_text"~description

Result
\="some_text"~description
literrally

### Debug information

The problem did not occur interactively.
The incorrect result was visible at the first execution of data-importer after the upgrade of the core to 6.1.21.

### Expected behaviour

Possibility 1. the migration action should end up with a correct formula
Possibility 2. the formula injected is good but should function correctly

The formula in the action value should end up as result
some text followed by the old description

### Steps to reproduce

1. have version 6.1.19 (or lower?)
2. upgrade to version 6.1.21
3. import transactions via data-importer 1.5.5
4. the imported transactions should use the rule that changes the description

**Comment by EricVanCaenenberghe** [comment]
above description misses some details in the replacement action due to the special characters in the action-value.
I have attached a print-screen of the actual representation of the action value
![Image](https://github.com/user-attachments/assets/12d2320f-362d-4588-b258-51bba3825f3e)

**Comment by JC5** [comment]
Thanks for opening an issue, I'll check it out. 

I won't be able to repair this automatically. Remove the backslash in front of the rule action and it should work as expected.

**Comment by JC5** [comment]
Also, a fix is now in place that prevents these backslashes from being placed back again.
