### ISSUE TITLE
Receipt OCR

### ISSUE THREAD

**Issue by IamSAB** [firefly-iii/firefly-iii#9304]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to upload a image of receipt to Firefly and parse the
- total amount
- currency
- cash account (guessed from means of payment)
- expense account (store name)

and store the extracted receipt image (optimized, cutted, resized) as an attachement.

In addition you can do
- split transactions
- add tags / categories

based on the parsed expense item and add them to the notes so you can search transactions for bought items.

### Solution

Best this functionality is available as an API so that mobile apps e.g. Waterfly III can implement it.

PHP options available are Tesseract or one could use a free/paid available API such as OCRspace/tabScanner.

**Comment by JC5** [comment]
Hi, thanks for opening an issue!

This will not be part of Firefly III I'm afraid. 

See #6135 for a similar question.
