### ISSUE TITLE
[Feature Request] Import with Credit/Debit Columns in CSV file

### ISSUE THREAD

**Issue by 4oo4** [firefly-iii/firefly-iii#931]
I'm trying to figure out how to import transactions, since the format my bank gives me for my CSV doesn't map nicely to what Firefly expects. I saw that someone asked the same question in #557, and it looks like Firefly can only do one Amount column with both credits and debits versus having separate Credit/Debit mappings.

While I can certainly edit the CSV I download from my online banking to make it work, I was wondering if it would be possible for Firefly to understand Credits/Debits from a statement instead? Having to manually edit the CSV files introduces a great deal of room for error and makes it a pain to import data on a regular basis.

I've worked in the finance industry for a few years, and from what I can tell the Credits/Debits format seems pretty standard for bank statements in the US. If Firefly was aware of that, it would make it a lot more useful for anyone whose bank statements are formatted that way.

EDIT: In the meantime, I found a way to format things nicely with bash and csvkit:

```
paste -d, <(csvcut -c 6 "Transactions.csv") <(csvcut -c5 "Transactions.csv" \
| awk '{print ($1) ? ($1 * -1) : $1}') | sed ''s/\"\",//g; s/,0//g'' \
| csvjoin "Transactions.csv" - > Transactions-Formatted.csv
```
Broken down:
 * This grabs a Credits Column (in my case, it was the 6th column, you put this as the value for the `-c` argument)
  `<(csvcut -c 6 "Transactions.csv")`
 * This grabs the Debits Column (in my case, column 5), and uses awk to make the numbers negative:
  `<(csvcut -c5 "Transactions.csv" | awk '{print ($1) ? ($1 * -1) : $1}') `
 * Combine Credits/Debits with `paste`:
  `paste -d,`
 * Pipe it through `sed` to remove unneeded quote marks, zeros, and blank values from each column
 ` sed 's/\"\",//g; s/,0//g'`
 * Append merged credits/debits column onto output csv:
  `| csvjoin "Transactions.csv" - > Transactions-Formatted.csv`

**Comment by JC5** [comment]
I shall make sure Firefly III becomes aware of it. I'm thinking of two extra selection options for the amount:

* Amount (debet). Will assume the amount is related to an expense ("negative")
* Amount (credit). Will assume the amount is related to an income ("positive")

Of course, this will also mean that Firefly III will ignore the empty column.

**Comment by 4oo4** [comment]
That sounds great, thank you!

**Comment by JC5** [comment]
OK, so the next release of Firefly III will have two new import options, amount (credit) and amount (debet):

![screen shot 2017-11-18 at 20 10 26](https://user-images.githubusercontent.com/5889984/32983907-8eb326cc-cc9c-11e7-96be-61bcad56688e.png)

If your CSV file has _no data at all_ in the opposite column, then the import should work:

```
date-transaction,description,asset,opposing,amount_debet,amount_credit
20170101,"Expense 1",Rabobank,AH,-11.11,
20170101,"Expense 2",Rabobank,AH,22.22,
20170101,"Income 1",Rabobank,Boss,,33.33,
20170101,"Income 2",Rabobank,Boss,,-44.44,
```

Amounts can be positive or negative, they will end up as debet (expense) or credit (deposit) respectively.

![screen shot 2017-11-18 at 20 10 26](https://user-images.githubusercontent.com/5889984/32983925-d19ff104-cc9c-11e7-93a2-3cc6fff653d9.png)


I invite you to test this when the next version drops (end of the month) and I hope it will work as expected.

**Comment by 4oo4** [comment]
Will do, thanks again!

**Comment by 4oo4** [comment]
Finally got a chance to test it in 4.6.11, it works great! There was however one small typo I noticed:
![firefly_screenshot](https://user-images.githubusercontent.com/15698835/34089441-a1a03758-e375-11e7-91fc-57ca295d72ad.png)


Cheers

**Comment by JC5** [comment]
Ah, nice find, I shall fix it!

**Comment by lastlink** [comment]
firefly seems to have great support for debit and credit. I made a csv parser in dotnet to help format bank statements for 2 major us banks. I was using environment and variable files so there's a lot of room to customize. https://github.com/lastlink/firefly_tools. I allow the ability to do a search to convert accounts and also create a budget column from keywords.
