### ISSUE TITLE
Wrong Date on Imported Data with Data Importer

### ISSUE THREAD

**Issue by cprpolo** [firefly-iii/firefly-iii#9313]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi! 
I'm trying to import transactions from a csv file and they all appeared with the Transaction Date of the importing day:

here is an example 
![Image](https://github.com/user-attachments/assets/31847701-55e1-406e-b3ac-3aaed877e87e)

my csv is in this format:
![Image](https://github.com/user-attachments/assets/483e30b0-49c2-4e3d-8b6f-678ff06f20ff)

and this is the config file for import:

{
    "version": 3,
    "source": "ff3-importer-1.5.6",
    "created_at": "2024-10-05T12:30:51+01:00",
    "date": "m-d-Y",
    "default_account": 1,
    "delimiter": "comma",
    "headers": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "roles": [
        "account-number",
        "date_transaction",
        "description",
        "note",
        "_ignore",
        "amount_debit",
        "amount_credit",
        "_ignore",
        "currency-code",
        "_ignore",
        "_ignore",
        "_ignore"
    ],
    "do_mapping": [
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false
    ],
    "mapping": {
        "0": {
            "931012 - 34893083": 1
        },
        "8": {
            "EUR": 1
        }
    },
    "duplicate_detection_method": "none",
    "ignore_duplicate_lines": false,
    "unique_column_index": 0,
    "unique_column_type": "internal_reference",
    "flow": "file",
    "content_type": "csv",
    "custom_tag": "Data Importer",
    "identifier": "0",
    "connection": "0",
    "ignore_spectre_categories": false,
    "grouped_transaction_handling": "",
    "use_entire_opposing_address": false,
    "map_all_data": true,
    "accounts": [],
    "date_range": "",
    "date_range_number": 30,
    "date_range_unit": "d",
    "date_not_before": "",
    "date_not_after": "",
    "nordigen_country": "",
    "nordigen_bank": "",
    "nordigen_requisitions": [],
    "nordigen_max_days": "90",
    "conversion": true,
    "ignore_duplicate_transactions": false
}

### Debug information

Let me know what you need

### Expected behaviour

That it imports the correct date of the transaction not the date of the import

### Steps to reproduce

1. Open Data importer
2.  Choose the csv file
3. Choose the config file (or configure it manually with the wizard)
4. Start the job
5. Wait until it completes

### Additional info

It happens with multiple csv files, not only this one

**Comment by JC5** [comment]
https://docs.firefly-iii.org/references/faq/data-importer/import/#all-transactions-are-imported-as-today

**Comment by cprpolo** [comment]
Yes, tried with format
n-j-Y
And still no change

**Comment by cprpolo** [comment]
likely i need n/j/Y
Apologies 👎

**Comment by JC5** [comment]
Not a problem!
