### ISSUE TITLE
[data importer] Change import mail order

### ISSUE THREAD

**Issue by dudu7731** [firefly-iii/firefly-iii#9326]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi, 

I think it would be smart to have inserted transactions via data importer first instead of errors.

I would like to keep errors in mail but i have to scroll through a lot of duplicates to see what i have imported to check it.

### Solution

just format import mail with messages first and errors after that

**Comment by JC5** [comment]
You can also disable the duplicate errors, would that work?

https://github.com/firefly-iii/data-importer/blob/main/.env.example#L110

**Comment by JC5** [comment]
No, but I'm not going to. I want users to notice the errors right away.
