### ISSUE TITLE
Net Worth calculation

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#933]
Hey,

there is something wrong with the _Net Worth_ Info-Box. It doesn't update corresponding to the selected time-period.

Steps to reproduce:
1. Create a new empty account (than it's easier to notice this).
2. Create a new empty bank-account.
3. Create a _deposit_ to the bank-account with a date in the future (for example the next month).
4. Go to Dashboard -> _Net Worth_ is zero (which is ok, because in the currently selected time-period the deposit isn't "active" yet).
5. Change the time-period to the period the _deposit_ takes place. -> The _Net Worth_ is still zero.

I don't think that this is intended, because the bills and the other info-boxes are updated corresponding to the selected time-period.

Greetings
Nico

**Comment by JC5** [comment]
Indeed! The net worth box always takes into account today, no matter which period you're viewing. You can see this [here](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/Json/BoxController.php#L169). I shall fix it asap and it will be repaired in the next release.

**Comment by JC5** [comment]
I've pushed a fix for this bug and it'll be included in the next release.

**Comment by nicoschreiner** [comment]
Thanks!
You are very fast. As always :smiley:
