### ISSUE TITLE
Default transaction import without year to current year

### ISSUE THREAD

**Issue by mokkun** [firefly-iii/firefly-iii#9340]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When importing data into Firefly III using the data importer, if a year is not specified in the CSV file (m/d format), the imported transaction will be placed in the year of 1970 by default. It is very unlikely that this would be the user expectation when importing a list of transactions where the transaction date field does not contain the year portion.

### Solution

What I'd like to propose is to default the year to the current year instead of 1970, since that is the most likely year that the transaction occurred.

### What are alternatives?

Manually edit the CSV file and insert the current year.

**Comment by JC5** [comment]
Sounds like a good idea. Incidentally, that's a terrible export format, without the year 😁 .
