### ISSUE TITLE
Support chaging DB connection timeout

### ISSUE THREAD

**Issue by rayslava** [firefly-iii/firefly-iii#9342]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

It would be good to have possibility of changing the DB timeout, technically it's just adding new envvar `DB_TIMEOUT` and forwarding it to `PDO::ATTR_TIMEOUT`.

### Solution

Currently my tiny home setup not always can reply in 30 seconds which leads to firefly deployment restart and makes setup non-functional for some time. Just increasing the timeout solves the issue.

**Comment by JC5** [comment]
Hey, thanks for opening an issue. 

That's a no, I'm afraid. I'm not going to make this an environment variable.
