### ISSUE TITLE
Save Custom Reports

### ISSUE THREAD

**Issue by paulcalabro** [firefly-iii/firefly-iii#9343]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

It would be create if I could save custom reports.
E.g. I like to periodically review specific accounts for a given report type. I know I can save the bookmark, but it would be nice to have an option to save the report inside the app.

### Solution

There would be a button to save the current report after it renders.
There would be a way to list and load existing reports.

### What are alternatives?

Bookmarking the report outside of the app.

**Comment by JC5** [comment]
Het, thanks for opening an issue. 

What would be the difference between this, and loading a bookmark?

**Comment by digitlength** [comment]
Saving in-app allows for that custom report to be available across any device which logs into Firefly III.

Bookmarks - without extra external configuration - do not cross devices.

**Comment by JC5** [comment]
I understand that, but no. I'm afraid I'm not going to add this feature.
