### ISSUE TITLE
Importing transaction with huge external id throws error

### ISSUE THREAD

**Issue by diogotcorreia** [firefly-iii/firefly-iii#9347]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Data importer cannot import a transaction with an external_id with length greater than 255 characters (the actual external_id of this transaction is 482 characters):

```
Result of your import on 2024-10-12 @ 23:58:52
Errors

    Line #1: transactions.0.external_id: The transactions.0.external_id may not be greater than 255 characters. (original value: "g1Ypjgd-snip-this-is-a-482-char-string-snip-hQuog")

-snip-

Enjoy!
Firefly III Data Importer, v1.5.6
```

### Debug information

Debug information generated at 2024-10-13 18:12:43 for Firefly III version **v6.1.21**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.21 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.12 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1131, base <span>#</span>91</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Lisbon + Europe/Stockholm</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has reconciled">:ledger:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-12-31 00:00:00</td></tr><tr><td>View range</td><td>3M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0</td></tr></tbody></table>

Debug information generated at 2024-10-13 18:13:25 Europe/Lisbon for Firefly III Data Importer version **develop/2024-10-12**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>develop/2024-10-12</td></tr><tr><td>Build</td><td><span>#</span>670, base <span>#</span>91</td></tr><tr><td>System</td><td>PHP 8.3.12, Linux, apache2handler</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Lisbon, Europe/Stockholm</td></tr><tr><td>Environment</td><td>production</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td>**</td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0</td></tr></table>

### Expected behaviour

I'd expect that either firefly accepts this long of an ID, or that it truncates it (or an option to do so). Unfortunately the ID of this transaction is out of my control as it comes directly from my bank through GoCardless.

**Comment by JC5** [comment]
Hey, thanks for opening an issue. 

I have some choice words about this, but I will trim the external ID.

**Comment by JC5** [comment]
Those words are not for you of course, but for whatever bank things that an ID of half a kilobyte is a normal thing to do.

**Comment by diogotcorreia** [comment]
Thank you for fixing this, really appreciate your work!

> I have some choice words about this
> Those words are not for you of course, but for whatever bank things that an ID of half a kilobyte is a normal thing to do.

You're not the only one, banks drive me crazy sometimes 🙃

**Comment by Philip2809** [comment]
Hey! Using version 1.5.6 and still getting this error:
```
Line #0: transactions.0.external_id: The transactions.0.external_id may not be greater than 255 characters. (original value: "g1YpjgdQSOaI_c_0mQeiCdw9OnodcXTlV_nuT0AnQz9oUK54YLCT9Utv9vhuP0ngqW5ZZRUxUXRtp4t6oXOgwol3VBc8NqO3YYQk7RpU7_Qh0P3b-Rkc-wT99OccPe2WuSdDdVxzZF_lV7BiiBrQ0jm4c6O82aK0DvNjF3--JLKbBb2MzZkS1Ug57gLaLwDuiOkF5SG5gaq-ECLbqHzPJzhu2T2hWiRTHs9VQKNyCOpKYbqCJrDGrRfZCprOuuLF1QGSlfaTCSsCqfi6SrGOtYzw08fdha-0lwiF7_koiJuUoe61s1wv-SCkO3fBvNe6RwwPzXSzAOySXSdF-L0EPQsjK0kFHzoS4pVBkYsFPW0-18U0i6WUOAFa52oiJYjNidMRCw87lcuJczC8fkE-uR1FX2s_pGFunNCpshD5mWOIo-IsMKvfhL9AFrJplTWXZ270J__2r1CJxhqRv1lJTlqA1XYAri8trD55zH-l37nPqy_a6nfao3eG_XRhMnagw2Ed-MqgPPJRjr1-pzuU2vgG6MDSimocPpl-eSxKM22D7cn3mI18m5amDhlR00NEL1PnPXs_lFkg9mbNcE_Skg")
```
I get this for all of my transactions execpt for like 2.

Also, I had a bug where I get an error after I have selected my account, I went to the debug page, went back to index and when I clicked to connect with gocardless again it worked, however I got this error. Can open a separate issue for this.

**Comment by JC5** [comment]
Yeah I haven't actually pushed anything to production lol. 

Also I have another fix in mind, please be a little bit patient :-)

**Comment by Philip2809** [comment]
Ahh, I missunderstood how the milestone were used, sorry, didn't mean to put this in a hurry or anything! Awesome project you have built btw! Thank you and keep up the good work!

**Comment by JC5** [comment]
Haha crap no worries, sorry for sounding so grumpy. I did indeed give this ticket the wrong milestone 😬
