### ISSUE TITLE
Category typeahead behaves differently when in single transaction and bulk edit flows

### ISSUE THREAD

**Issue by avee87** [firefly-iii/firefly-iii#9352]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Currently when I edit a single transaction typeahead pre-selects the category so pressing enter confirms it and selects the first option.
![Image](https://github.com/user-attachments/assets/6a5f2701-5209-4458-a9a2-77846004784c)
However, when I bulk edit, pressing enter saves the currenty entered letters as potentially a new category - often resulting in, for example, something like "bi" being saved on transactions as opposed to "Bills".
![Image](https://github.com/user-attachments/assets/11ede510-360b-484e-a83c-06900139bdbf)

The same probably applies to other fields by in my workflow the category is the most common and annoying...

### Solution

Use the same typeahead and behaviour for both flows.

**Comment by JC5** [comment]
Hey, thanks for opening an issue!

Sorry, but I will not be updating these ancient libraries. I am working on a new layout where this should work as expected.

**Comment by avee87** [comment]
Do you have any estimate when the new layout may land? I could take a stab at updating the existing components in the short term.

**Comment by JC5** [comment]
Go ahead :)
