### ISSUE TITLE
404error when importing via Webinterface

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#936]
Hi,

just reset everything (again), was working on automating the imports. Did a `git pull` and now I get the following error

> **File not found**
> 
> Firefox can’t find the file at https://my.host.name/import/file/initialize.
> 
>     Check the file name for capitalization or other typing errors.
>     Check to see if the file was moved, renamed or deleted.

How to reproduce:
1. go to import
2. add the csv file
3. add the config json file
4. click next -> voila

there's no debug info in `ff3-apache2handler-2017-10-17.log`

**Comment by JC5** [comment]
I think that's a local configuration problem, not a Firefly III error. The Firefly III [404 page looks like this](https://firefly-iii.nder.be/asdsada). Plus, the URL seems to work locally.

**Comment by gavu** [comment]
I re-cloned it to make sure I did not break anything, and still get the same error. I have a simple port-forwarding setup on my router, so no reverse-proxy stuff.

I checked:
* browsing everything else works, just the import part fails
* folder permissions are set correctly (chmod+chown)
* php artisan ca:cl
* IE/FF/Chrome
* alternative networks

**Comment by gavu** [comment]
Sorry, the error was on my side. My VeraCrypt container dis-mounted but remained cached, somehow, and delivered empty-non-existent files, and it might have broken my browser, not the app.

sorry again about that

**Comment by JC5** [comment]
Glad to hear you found it. Quite a unique bug!
