### ISSUE TITLE
Date incorrectly shown

### ISSUE THREAD

**Issue by enboig** [firefly-iii/firefly-iii#9360]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In some dates writen in catalan, what should be a `'` is a `&#039;` but it ins not rendered.

### Debug information

It is the demo site

### Expected behaviour

"1r d&#039;octubre, 2024" should be "1r d'octubre, 2024"

### Steps to reproduce

1. enter the demo sites
2. Configure it in "Catalan" language.
3. Look the date.

### Additional info

I was able to find [#1027](https://github.com/firefly-iii/firefly-iii/issues/1027); but no open issues related to this.

**Comment by JC5** [comment]
Nice find, this should be fixed in the next release.
