### ISSUE TITLE
[Feature Request] Display all items in the category dropdown.

### ISSUE THREAD

**Issue by yunyuyuan** [firefly-iii/firefly-iii#9367]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

![Image](https://github.com/user-attachments/assets/65583847-4ec4-4b44-874b-40af6ff8bad4)

Currently, it only shows 10 items, even though the API returns all categories.

I often forget which category I need to select, so I prefer it to display all items.

### Solution

It would be great if we could set the maximum number of items to display in the settings,thanks!

**Comment by JC5** [comment]
Het, thanks for opening an issue. 


If you start typing in the box, the list will shrink down to the category you are looking for, if it indeed exists. Otherwise, Firefly III will create it.

**Comment by yunyuyuan** [comment]
@JC5 Thanks for the reminder. However, I sometimes am not sure which category is the best, so I need to see all the categories in the dropdown to make a selection.

Search functionality isn’t very effective for Chinese, as it consists of only a few characters.🤣

**Comment by JC5** [comment]
Ah, I get it. But sorry, the dropdown can't be made longer. I will remember this for the future layout.

**Comment by yunyuyuan** [comment]
Anyway, For those who currently have this requirement, under Docker you can do the following to remove the dropdown restrictions:

```sh
docker exec CONTAINER_NAME sed -i 's/"item-key":\s*"name"/&,limit:9999/' /var/www/html/public/v1/js/create_transaction.js
```
