### ISSUE TITLE
[Feature Request] Piggy Banks status in dashboard

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#937]
Piggy banks are a neat feature... if you don't forget about them. Would it be possible to add a small widget (like the "Bills"), maybe above/below "Bills" with some small progress bars reflecting the status of your savings?

**Comment by JC5** [comment]
Mmm, that could work. Any piggy bank with more than 0 in it, otherwise it could be many of them (in my case ;)).
