### ISSUE TITLE
Setting monthly budgets

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#938]
I don't know if it's a bug or a well hidden/unfinished feature:

![monthbuttongroup](https://user-images.githubusercontent.com/3742238/31720545-23a05a1e-b417-11e7-9658-6a88f48c2ec8.png)
* clicking on 1 goes to 2017-09-01
* clicking on 2 goes to 2017-10-01
* clicking on 3 goes to 2017-11-01

but, somehow, I managed to get to 2017-10-17 and set a budget for that day - don't ask how or why - can't really answer that
* clicking on 1 goes to 2017-09-17
* clicking on 2 goes to 2017-10-17
* clicking on 3 goes to 2017-11-17

went back to "yesterday", set all the budgets to "0", now when I go to the dashboard I see the following
![dashboardbudgetsandspendingswidget](https://user-images.githubusercontent.com/3742238/31720827-f1780388-b417-11e7-82ab-ffc8641fea34.png)

I have a few questions about this:
1. Without looking into the database, is there any way to find out for which day I set up the budget?
2. Is this a feature/bug/works-as-designed?

**Comment by gavu** [comment]
Update:

I checked the database, the limits have been duplicated, but have different dates. I redacted the ID's since they are used in URLs
![phpmyadmin-budget_limits](https://user-images.githubusercontent.com/3742238/31723659-c9e8b77e-b41f-11e7-8366-81ac353ea927.png)

**Comment by JC5** [comment]
It could happen when you use a custom date range combined with a monthly view. It should jump over to the next month however.

As for the double entries: it's something I can't really help. If the webinterface is too quick for the database (RP3...) it will keep creating new entries because it thinks none exist. I could create a "unique" index inside the database to block them but it might break user's databases.

**Comment by gavu** [comment]
You are right, I should move to a decent machine. In the meantime, I deleted those 2017-10-01 -> 2017-12-31 rows and ran `php artisan ca:cl`

Now I see this:
![phpmyadmin-budget_limits_2](https://user-images.githubusercontent.com/3742238/31726317-e6b61552-b426-11e7-8960-b328855627ff.png)

![dashboardbudgetsandspendingswidget_2](https://user-images.githubusercontent.com/3742238/31726321-ea164bcc-b426-11e7-987b-0bc71a04cc4d.png)

**Comment by gavu** [comment]
I fixed it, I just deleted all budget_limits entries from the database cleared FF cache and re-entered the limits via web interface. I would close this, as it is related only to really slow systems. Or do you want to add some server-sided checks / unique id's first?

**Comment by JC5** [comment]
I've committed an extra clean up routine :+1:

**Comment by gavu** [comment]
Thanks! This way I got to learn how the system works :)
