### ISSUE TITLE
Budget and Bill field on Recurring transactions not updating

### ISSUE THREAD

**Issue by HHUBSS** [firefly-iii/firefly-iii#9389]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In recurring transactions, I have set the "Budget" and "Bill" fields to something. But when I update it to "(none)", it doesn't update. Meaning it remains where I set it to something.

![Image](https://github.com/user-attachments/assets/2656d273-25db-4b95-a4da-b00e514d37b9)

### Debug information

-

**Comment by JC5** [comment]
I see what you mean, thanks! I'll pick it up :)
