### ISSUE TITLE
Store sidebar position

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#939]
The sidebar/menu can be collapsed but resets after each refresh. Maybe store the position in the database (Options -> Preferences -> Layout), or in a cookie?

**Comment by JC5** [comment]
Once I can take the time to take you up on your layout related offer I will certainly take this into account! :+1:

**Comment by pkoziol** [comment]
Just a quick reminder that I found and linked two possible sollutions in #802 ;)

**Comment by JC5** [comment]
I know, I ignored you :wink:
