### ISSUE TITLE
Rules are bad configured after docker restart containers

### ISSUE THREAD

**Issue by JcMinarro** [firefly-iii/firefly-iii#9395]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Some of my rules moved the "old description" to the notes before updating the description.
This functionality was recently updated introducing placeholders that can be used to concatenate multiple fields, which is very cool.

Without any change from my side, my old rules were updated, and started to use this new placeholders feature.
The problem is that the pattern used was wrong, Firefly III migrated them to use `\=notes~" "~description` instead of `=notes~" "~description`

I started to see some of my transactions was formated with a wrong "note data". Instead of contains the value of notes plus the value of description, it was the literal "=notes~" "~description".

After that, I went across all my rules removing `\` characters to proper use of the placeholders pattern. Sadly, after restarting my containers, the rules come back to `\=notes~" "~description` pattern again.

### Debug information

Debug information generated at 2024-10-25 00:59:45 for Firefly III version **v6.1.21**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.21 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.12 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1131, base <span>#</span>91</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Madrid + Europe/Madrid</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>es_ES + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-10-23 22:00:00 (1 day ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-12-31 00:00:00</td></tr><tr><td>Session end</td><td>2024-10-24 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>es_ES</td></tr><tr><td>User locale</td><td>es_ES</td></tr><tr><td>Locale(s) supported</td><td>es_ES.utf8: :white_check_mark:<br>es_ES.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

- Migration process from old implementation to the new placeholder pattern implementation shouldn't add `\` character at the beginning.
- Migrated rules shoulnd't be reprocessed

**Comment by JC5** [comment]
Hey, thanks for opening an issue!

As luck would have it, I fixed this a few days ago, and it should be part of the next release.

**Comment by JcMinarro** [comment]
> Hey, thanks for opening an issue!
> 
> As luck would have it, I fixed this a few days ago, and it should be part of the next release.

Cool!!!!
Thanks you
