### ISSUE TITLE
Data Importer Accepts Selection of Multiple Files AND Trigger all Rules in Group

### ISSUE THREAD

**Issue by chboishabba** [firefly-iii/firefly-iii#9406]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hi I'm loving the tool, and thank you all contributors!!
I'm wondering if it could be enabled to select multiple files simultaneously within the DataImporter (my banks only outputs CSV containing a max number of transactions) as I'm up to csv 20 or so...
I'm also not sure if it's user error (rules set up for creation of transactions vs update) but it appears sometimes rules which correctly apply to a transaction is not being automatically applied. In any case, it would be helpful to be able to trigger all rules within a given rule group.

### Solution

1. Enable multifile picker within file uploader in DataImporter
2. Add 'Trigger All Rules in Group' to rule group hamburger.

**Comment by JC5** [comment]
Hi,

Multi file upload is on the list already somewhere. Running all rules in a group is a good idea, I'll pick it up!

**Comment by chboishabba** [comment]
Cheers! Apologies, I find github's issue search quite confusing but did
attempt to check.

**Comment by JC5** [comment]
![Image](https://github.com/user-attachments/assets/0e6cfa24-bcb6-4fb1-91ce-7e88a26c6ed3)

And since your other ask is already possible, I'm closing this issue :-)
