### ISSUE TITLE
Linking Transaction to Bill doesn't mark as paid for 31st

### ISSUE THREAD

**Issue by harrhunt** [firefly-iii/firefly-iii#9416]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When creating a withdrawal and linking it to a bill, the bill is not marked as paid if the transaction date is set for the 31st after 12:00 AM. Setting to the 30th correctly marks the bill as paid as well as setting to the 31st at 12:00 AM. However, setting it to October 31st 12:01 AM or later does not mark the bill as paid (still says expected `x` weeks ago). Confirmed this same behavior on both my local instance (6.1.21) and the demo site (Used the existing Health Insurance Bill on the demo site).

### Debug information

Debug information generated at 2024-10-31 12:01:49 for Firefly III version **v6.1.21**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.21 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.12 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1131, base <span>#</span>91</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Boise + America/Denver</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, daily / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-10-31 06:00:00 (12 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 2</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-10-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0</td></tr></tbody></table>

### Expected behaviour

Should mark the Bill as paid anytime on the 31st since it is still within the current month.

### Additional info

![Image](https://github.com/user-attachments/assets/e76ff661-e63a-4eea-be9a-7f72408bcf77)

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

This depends on the start date of the bill. What is it, exactly ?

**Comment by harrhunt** [comment]
Hello, thanks for the quick response!

(On the demo site) It was initially set to 2015-01-01, but I changed it to all of the following with the same results (still says expected not paid).

- 2015-01-02
- 2015-01-15
- 2015-01-30
- 2015-03-31 (in case it had to do with Jan only having 30 days)

**Comment by JC5** [comment]
Nice, I'll check it out!

**Comment by joaovitoriasilva** [comment]
Hello. I have the same issue:
Screenshots attached 
![Image](https://github.com/user-attachments/assets/c728c7ce-ba58-46c6-843d-3ea26c2f13c7)
![Image](https://github.com/user-attachments/assets/0d5a2c41-e0b3-496a-a054-44a190896b3b)
![Image](https://github.com/user-attachments/assets/044a642f-0d35-4139-bf8e-ba6ee5a60074)

**Comment by JC5** [comment]
Thanks, this should be fixed in the next release.
