### ISSUE TITLE
Allow creating budget as percentage of income

### ISSUE THREAD

**Issue by subin-chella** [firefly-iii/firefly-iii#9419]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to have a feature to create a budget as a percentage of income for a given period (e.g., monthly).

### Solution

Example: I want to set up my budget each month as follows:

50% for expenses
30% for savings and investments
10% for luxury spending
10% for self-improvement
Based on the total income for that month, the budget should automatically adjust. For example, if my income for November is $1,000, then my expense budget would be $500. Similarly, the other budgets would adjust automatically.

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

This is a great way of managing your finances, but I won't add code to Firefly III to automate this. You'll have to do the math yourself.

**Comment by subin-chella** [comment]
okay. Thanks for your reply.
I thought it could save everyone's time as we don't need to recalculate and adjust the budget every month manually. 
As we are not going to implement. Closing the ticket. Thanks again
