### ISSUE TITLE
Splitting transactions don't understand new format of notes

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#942]
When splitting transaction notes textarea contains JSON array with notes objects or just empty array "[]".

**Comment by JC5** [comment]
Fixed, thanks for noticing!

**Comment by gavu** [comment]
I tried it today and got the following error:

> Type error: Argument 2 passed to FireflyIII\Repositories\Journal\JournalRepository::updateNote() must be of the type string, null given, called in /var/www/firefly-iii/app/Repositories/Journal/JournalRepository.php on line 338

**Comment by JC5** [comment]
I’ll take a look at it :+1:

**Comment by gavu** [comment]
I was able to split my transaction. Thanks! 👍

**Comment by pkoziol** [comment]
Verified on demo. "[]" no longer appears.
