### ISSUE TITLE
Allow bills to have introductory rates

### ISSUE THREAD

**Issue by jonnywright** [firefly-iii/firefly-iii#9431]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like Firefly to be able to create bills which might have an introductory rate. For example, the first 6 months of an 18 month contract might be half price.

Service providers often offer introductory rates (e.g. £x.xx for the first a months, then £y.yy for the next b months). It would be great if you could setup a bill to take this kind of dual-rate into consideration. I appreciate that there needs to be a line drawn with how flexible the Bills feature is, but (certainly in the UK) this specific approach is quite common.

### Solution

In the Bills feature, allow the user to set the Bill value to a specific amount for the first X months, and then another value for the subsequent months. 

### Additional context

I appreciate that the Min and Max amounts go part way to achieving this, but for bills of known value (such as TV/internet/cable etc) this feature would be useful.

**Comment by JC5** [comment]
Hi, thanks for opening an issue.

Sorry, but this will not be a feature. You will have to use the min/max amounts :)
