### ISSUE TITLE
2-Step Authentication failed

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#944]
I tried to enable 2-Step auth and encountered the following error:

> Call to undefined function BaconQrCode\Renderer\Image\imagecreatetruecolor()

**Comment by JC5** [comment]
You need the GD extension, I believe.

**Comment by gavu** [comment]
You are right. The qr-code was generated now. Thanks

**Comment by gavu** [comment]
Just a suggestion. Maybe a “info” page would help where you parse the existing php information for required modules and their status

**Comment by JC5** [comment]
I'll update the composer file to make the gd extension mandatory. The tricky part of an info page is that when you don't have the requirements, the info-page wil break :D
