### ISSUE TITLE
Accounts summary chart - Stacked Line Chart option

### ISSUE THREAD

**Issue by cgrandine** [firefly-iii/firefly-iii#9442]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Add a toggle or setting to enable a "stacked" line graph for the "Your Accounts" summary on the main dashboard.

Example:
https://r-graph-gallery.com/web-stacked-area-chart-inline-labels_files/figure-html/unnamed-chunk-4-1.png

### Solution

This would improve the account summary line chart by giving you insight into how much you have in each account AND give you an immediate glance at your total networth. I find this much more useful than a regular line chart.

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

I'm not a fan of stacked charts in this context so I'm afraid this will not become an option.
