### ISSUE TITLE
Budget report on inactive budget gives a 404

### ISSUE THREAD

**Issue by adyanth** [firefly-iii/firefly-iii#9443]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Trying to run a report on an inactive budget gets a 404 page. This also happens on the demo site.

### Debug information

Debug information generated at 2024-11-08 00:58:37 for Firefly III version **v6.1.21**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.21 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.12 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1131, base <span>#</span>91</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Denver + Asia/Calcutta</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-11-07 07:00:00 (1 day ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has recurring transactions">:clock130:</span></td></tr><tr><td>Session start</td><td>2024-11-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-11-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15</td></tr></tbody></table>

### Expected behaviour

I get to see the report for an inactive budget.

### Steps to reproduce

1. Create a budget
2. Add expenses to the budget
3. Make the budget inactive (uncheck the active box)
4. Run a budget report, which allows selecting the inactive budget (rightly so).
5. See a 404 page

### Additional info

```log
10.42.0.37 - - [08/Nov/2024:00:52:45 -0700] "POST /reports HTTP/1.1" 302 2835 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15"
[2024-11-08 00:52:45] local.WARNING: BudgetList fallback to 404.
[2024-11-08 00:52:45] local.WARNING: GracefulNotFoundHandler cannot handle route with name "reports.report.budget"
10.42.0.37 - - [08/Nov/2024:00:52:45 -0700] "GET /reports/budget/5,8,10,12,91,1,6,73,105,3/2/20240801/20241130 HTTP/1.1" 404 7016 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15"
```

**Comment by adyanth** [comment]
While at it, is there a way to export the report into a CSV? Or the list of transactions in the report/budget? Usecase being I'd like to provide a copy of the expenses to others.

**Comment by adyanth** [comment]
I reactivated the budget, tried a command line export, shows up empty:

```
root@firefly-cd69578b6-mh2st:/var/www/html# php artisan firefly-iii:export-data --export-budgets --export_directory=/tmp/ --token REDACTED --start=2024-08-01 --end=2024-11-30 --accounts=1,12,91 --export-transactions --force
  [!] File "/tmp/2024_11_08_budgets.csv" exists already but will be replaced.
  [✓] Wrote budgets-export to file "/tmp/2024_11_08_budgets.csv".
  [✓] Wrote transactions-export to file "/tmp/2024_11_08_transactions.csv".
root@firefly-cd69578b6-mh2st:/var/www/html# ls /tmp
2024_11_08_budgets.csv  2024_11_08_transactions.csv
root@firefly-cd69578b6-mh2st:/var/www/html# cat /tmp/2024_11_08_budgets.csv 
user_id,budget_id,name,active,order,start_date,end_date,currency_code,amount
root@firefly-cd69578b6-mh2st:/var/www/html# 
```

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

1. Yes, inactive budgets will give a 404. This will not change.
2. I'll check if I can replicate this, thanks for letting me know.

**Comment by adyanth** [comment]
If that is the intended behavior, I would expect the report budget selection list to not include those at least, which would atleast let the user know something is off with that budget. A 404 while the selection looks correct is not the best UX.

Thanks for looking into it this quick!

**Comment by JC5** [comment]
Nice, I wasn't aware they were listed there. I'll pick it up!
