### ISSUE TITLE
Transaction doesn't show up when attaching HTML file

### ISSUE THREAD

**Issue by Marc928132** [firefly-iii/firefly-iii#9447]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

When attaching a HTML file to a withdrawal, said withdrawal doesn't show up in the "All expenses between..." list under Accounting>Transaction>Expenses.
I does show up at (all?) other places like the dashboard or the charts under Accounting>Transaction>Expenses.
When opening the transaction from one of these other places like the dashboard the attached HTML file is not there.

Firefly III version 6.1.21 via Docker on Unraid accessed via Firefox 132.0.1

### Solution

-

**Comment by JC5** [comment]
Hi, thanks for opening an issue.

Right now, `text/html` files are not allowed for uploading. I'll pick this up for the next release, and make sure you get a nice error if you upload anything forbidden. 

Also, the issue of not showing the transactions will be fixed.

Thanks for reporting!
