### ISSUE TITLE
Total amount not reflecting actual total amount on account with foreign currency

### ISSUE THREAD

**Issue by karma-riuk** [firefly-iii/firefly-iii#9449]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I've got three accounts: 
- GBP
- CHF
- EUR

The amount described by firefly on the GBP account is wrong. Below you will find some screenshots of October 2024, this is the only moment in time I used the GBP account, so all of the possible transactions are the ones below.

As you can see, the total amount says it's at **-£94.32**, but it should be **£5.68**
![Image](https://github.com/user-attachments/assets/69e6f0a1-8650-4bec-a64c-c96b92c24cb6)

If we look at the summary table:

![Image](https://github.com/user-attachments/assets/8b771350-ac56-4e82-a0ad-a78400af6f14)

We see that there money spent and the earned / transferred in is correct (i.e. coherent with the transactions below and coherent with the actual money in the account IRL).

If we sum the GBP values of earned and transferred in, we have 

£120.00 + £336.24 = £456.24

Now if we substract the spent money to the money that came in:

£456.24 - £450.56 = £5.68

Which, again, is coherent with the transactions below and with the statement report from the bank.

So I'm very confused by the fact that firefly says that the amount in the account is **-£94.32**

I transferred money from CHF and EUR to GBP and received money from an outside source. The **entire** list of transactions on the GBP account is in the following: 

![Image](https://github.com/user-attachments/assets/c1747379-c8ad-40be-8f45-2b3847aee11f)

Is there anything I'm missing? I'm just trying to align the numbers from the real account with firefly.

The weird thing is that back when I logged the transactions, everything seemed to be aligned. I only realized now (a couple of weeks after the fact) that the account went "negative". It might be because a bug in an update (I've got firefly on docker with watchtower that updates it automatically).

### Debug information

Debug information generated at 2024-11-09 12:10:15 for Firefly III version **v6.1.22**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.22 / v2.1.0 / 25 (exp. 25)</td></tr><tr><td>PHP version</td><td>8.3.13 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1147, base <span>#</span>92</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Zurich + Europe/Zurich</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_GB + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-11-08 23:00:00 (12 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>2 of 2</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-10-01 11:38:53</td></tr><tr><td>Session end</td><td>2024-10-31 11:38:53</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36</td></tr></tbody></table>

**Comment by JC5** [comment]
Your math is correct, but it's difficult to say why it ends up with this amount. The difference between what it is, and what it should be is exactly 100,-. My best guess is that it's missing a transaction when counting. Perhaps it's date related.

When you change the transaction from October 14th (100GBP) to 50 GBP, does the balance difference change accordingly?

**Comment by karma-riuk** [comment]
Yes, but weirdly it goes in the opposite direction. I would expect that removing £50 with make the balance even more in the red, but no. It goes from -£94.32 to **-£44.32**. That might be the source of the error.

**Comment by karma-riuk** [comment]
Wow okay, I guess you were right, it was date related. When switching back to the original £100 of the transaction, I set the time of the transaction to 1 minute before and now everything is correct. No idea of what happened, but it works.

Thanks for the help :)

**Comment by JC5** [comment]
Not a problem, but this is something I would like to check out for my own curiosity. Could you tell me the date before and after please?

**Comment by karma-riuk** [comment]
Ofc 

![Image](https://github.com/user-attachments/assets/dd53b2b7-d214-441a-af65-ea208f3fefb1)

Note: the first date edit was made probably on the moment I inputted the transaction (not sure what happened, it might've been the app from which i added the transaction, (waterfly III) but I'm not sure). The second edit was the one I did now.
