### ISSUE TITLE
Clear cache not working

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#945]
Hello,

I just updated to 4.6.8. As I'm testing my setup with HTTPS behind a reverse proxy, I wanted to make sure the cache was clean.

I received these commands in another support ticket:
`php artisan cache:clear`
`php artisan config:clear`
`php artisan route:clear`
`php artisan twig:clean`
`php artisan view:clear`

But now when I launch them I have this error:

> [Symfony\Component\Debug\Exception\FatalThrowableError]
> Class 'FireflyIII\Providers\URL' not found

It this a bug or the commands have changed?

**Comment by JC5** [comment]
Do you have a stacktrace in your log files? I know that `twig:clean` may give an error but not this one.

**Comment by MacPaille** [comment]
I don't understand why but now the commands are working...
And as you say the twig:clean give an error but that's ok :)
