### ISSUE TITLE
Leading Backslash Added to Expressions After Container Upgrade

### ISSUE THREAD

**Issue by AlixANNERAUD** [firefly-iii/firefly-iii#9450]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,
When upgrading the Firefly container, my rules containing expressions are modified, and a leading `\` is added, making the expressions invalid and considered as regular text. For example, `=substr(description, 10)` is modified to `\=substr(description, 10)`.

### Debug information

Debug information generated at 2024-11-09 14:07:30 for Firefly III version **v6.1.21**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.21 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.12 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1131, base <span>#</span>91</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Etc/UTC + Europe/Paris</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>redis</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-10-29 00:00:00 (1 week ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span></td></tr><tr><td>Session start</td><td>2024-08-11 00:00:00</td></tr><tr><td>Session end</td><td>2024-11-09 23:59:59</td></tr><tr><td>View range</td><td>last90</td></tr><tr><td>User language</td><td>fr_FR</td></tr><tr><td>User locale</td><td>fr_FR</td></tr><tr><td>Locale(s) supported</td><td>fr_FR.utf8: :white_check_mark:<br>fr_FR.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0</td></tr></tbody></table>

### Expected behaviour

There should not be a leading `\` when the migration is applied.

### Steps to reproduce

1. Create a rule using an expression (e.g., `=substr(description, 10)`).
2. Update the container.
3. Check the rules containing expressions; they should contain a leading `\`.

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

Yes, this has been fixed in 6.1.22. The command may have run twice, but it should not do so again. Unfortunately, you must correct the rule actions manually.

Please refer to https://github.com/firefly-iii/firefly-iii/issues/9395
