### ISSUE TITLE
Append description to notes expression keeps breaking on update.

### ISSUE THREAD

**Issue by DiscoSlug** [firefly-iii/firefly-iii#9459]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

On each update, my append description to notes keeps changing to an expression that does not work. Below where (backslash) is to denote the backslash symbol, which is not showing up in the text below.

On the first expression update, my Append description to notes rule changed to the new expression: Set notes to (backslash)=notes~" "~description  

I went through and fixed every rule to Set notes to "=notes~" "~description"; This worked similar to previous non-expression rule. The back slash was breaking the rule and adding the expression directly to the notes in full ""(backslash)=notes~" "~description"". 
** don't know why this is strikethrough.

On the final update, all expressions were set back to have the back slash, breaking the rule again. 

### Debug information

Not sure how to grab debug from the update

### Expected behaviour

Written expressions shouldn't have been changed.

**Comment by JC5** [comment]
Hi, thanks for opening an issue.

Please see https://github.com/firefly-iii/firefly-iii/issues/9450
