### ISSUE TITLE
Problem with locales on Rapsberry Pi

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#946]
Hello,

I just setup firefly on my Raspberry Pi under raspbian. When I login it shows me this error message:
Invalid server configuration:  Firefly III is unable to format monetary amounts because your server is missing the required packages. There are instructions how to do this.

Thing is language-pack do not exist in raspbian, so I have this error all the time.

I used the dpkg-reconfigure locales to enable fr and nl locales, but the error is still present.
I is mandatory to have these packages?

**Comment by JC5** [comment]
Yes, it's mandatory to have these packages. You'll need the packages for your local language at least.

You should be able to run `sudo raspi-config` and add more locales. 

To get the correct response from Firefly III, make sure that the command `locale -a` lists the languages in the translations. I've updated the wiki page [to reflect this](https://github.com/firefly-iii/help/wiki/Missing-locale-packages).

**Comment by MacPaille** [comment]
rapsi-config gives me the same menu as the dpkg-reconfigure.
Here is the output of local -a
`be_BY@latin`
`be_BY.utf8@latin`
`C`
`C.UTF-8`
`en_GB.utf8`
`fr_BE`
`fr_BE.iso88591`
`nl_BE`
`nl_BE.iso88591`
`POSIX`

So why is firefly still complaining? I need to add all the locales he needs to use?

**Comment by JC5** [comment]
You need two things:

- nl_NL and fr_FR, since Firefly III is based on those locales.
- The .UTF8 or .utf-8 variants.

That should fix them.

**Comment by MacPaille** [comment]
Still same issue. I also installed the pt and de locales and rebooted. Do you have any hint on what to test next?

**Comment by MacPaille** [comment]
If I choose French of Dutch as language in Preferences the message disappear. If I want to keep English the message appears again. Which locale is needed for EN version?

**Comment by JC5** [comment]
I was under the impression you wanted French or Dutch. For English you need en_US.utf8

**Comment by MacPaille** [comment]
Will keep it in French and help if I see translation errors :)
Anyway with the en_US and a reboot now it works. Thanks a lot!

**Comment by JC5** [comment]
:+1:

**Comment by Aquariu** [comment]
> Will keep it in French and help if I see translation errors :)
I can garantee you there are some ... I wrote them!
