### ISSUE TITLE
Data Importer authorize responds with "empty"

### ISSUE THREAD

**Issue by adiba** [firefly-iii/firefly-iii#9461]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Using docker.  
I just installed firefly + the data importer, modified the config, set the client id with callback url `http://localhost:81/callback`.

Visiting `http://localhost:81/` shows an authorize button. Clicking it just shows the word "empty" on the page, the url being `http://localhost:81/callback?code=...`

Going to `http://localhost:81/` shows the authorize button again.

### Debug information

Debug information generated at 2024-11-12 11:22:43 Europe/Amsterdam for Firefly III Data Importer version **1.5.7**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.5.7</td></tr><tr><td>Build</td><td><span>#</span>677, base <span>#</span>92</td></tr><tr><td>System</td><td>PHP 8.3.13, Linux, apache2handler</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Environment</td><td>local</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td></td></tr></table>

### Expected behaviour

Authorization successful

**Comment by jflorido94** [comment]
Im having the same problem, and I have the container of firefly at 8080 port
