### ISSUE TITLE
Self hosted : version problem after upgrade in 6.1.22

### ISSUE THREAD

**Issue by dudu7731** [firefly-iii/firefly-iii#9462]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,

After upgrading to 6.1.22, the version in application is still 6.1.21 

API says : 
`curl -s  -X GET -H 'Content-Type: application/json' -H "accept: application/vnd.api+json" -H "Authorization: Bearer $FIREFLY_III_ACCESS_TOKEN" "$FIREFLY_III_URL/api/v1/about" | jq -r`
`
{
  "data": {
    "version": "6.1.21",
    "api_version": "2.1.0",
    "php_version": "8.3.13",
    "os": "Linux",
    "driver": "mysql"
  }
}
`

Mysql says 
`MariaDB [firefly_test]> select * from configuration where name='ff3_version'
    -> ;
+----+---------------------+---------------------+------------+-------------+----------+
| id | created_at          | updated_at          | deleted_at | name        | data     |
+----+---------------------+---------------------+------------+-------------+----------+
| 36 | 2024-09-11 16:05:14 | 2024-11-12 13:41:43 | NULL       | ff3_version | "6.1.22" |
+----+---------------------+---------------------+------------+-------------+----------+
1 row in set (0,002 sec)
`

GUI says : 
![Image](https://github.com/user-attachments/assets/6d7d4be4-5246-41b7-9ba8-765a13109a55)

Commands passed for upgrade 
php artisan migrate --seed
php artisan firefly-iii:decrypt-all
php artisan cache:clear
php artisan view:clear
php artisan firefly-iii:upgrade-database
php artisan firefly-iii:laravel-passport-keys

I think i missed something .... perhaps a cache ? 

### Debug information

Debug information generated at 2024-11-12 15:37:31 for Firefly III version **v6.1.21**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.21 / v2.1.0 / 25 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.13 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>20971520 (20 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Paris + Europe/Paris</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>redis</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-11-10 18:16:46 (1 day ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-11-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-11-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>fr_FR</td></tr><tr><td>User locale</td><td>fr_FR</td></tr><tr><td>Locale(s) supported</td><td>fr_FR.utf8: :white_check_mark:<br>fr_FR.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0</td></tr></tbody></table>

```


### Expected behaviour

_No response_

### Steps to reproduce

1 : upgrade files from 6.1.21
2 : pass command to upgrade 
php artisan migrate --seed
php artisan firefly-iii:decrypt-all
php artisan cache:clear
php artisan view:clear
php artisan firefly-iii:upgrade-database
php artisan firefly-iii:laravel-passport-keys



### Additional info

_No response_

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

Please make sure you followed the upgrade instructions to the letter. I haven't been able to replicate this.

**Comment by dudu7731** [comment]
i copied the files and kept storage 

then passed php artisan commands, please help

**Comment by dudu7731** [comment]
it was a shitty link ... 
Linux issue

**Comment by JC5** [comment]
What do you mean? 

I changed nothing in the code.

**Comment by dudu7731** [comment]
i had to rename after upgrade my directory adding a "s" to upload ....

it's a bit weird, storage you deliver with github has a good directory : 
```

root@firefly:/opt/data-importer-test# ll /var/www/test/data-importer/v1.5.6/storage.ori/
total 48
drwxrwxr-x  2 www-data www-data 4096 23 avril  2024 uploads
drwxrwxr-x  2 www-data www-data 4096 23 avril  2024 submission-routines
drwxrwxr-x  2 www-data www-data 4096 23 avril  2024 logs
drwxrwxr-x  2 www-data www-data 4096 23 avril  2024 jobs
drwxrwxr-x  6 www-data www-data 4096 23 avril  2024 framework
drwxrwxr-x  2 www-data www-data 4096 23 avril  2024 debugbar
drwxrwxr-x  2 www-data www-data 4096 23 avril  2024 conversion-routines
drwxrwxr-x  2 www-data www-data 4096 23 avril  2024 configurations
drwxrwxr-x  3 www-data www-data 4096 23 avril  2024 app
drwxr-xr-x 11 www-data www-data 4096 14 sept. 06:33 storage
drwxrwxr-x 12 www-data www-data 4096 18 sept. 15:31 .
drwxr-xr-x 12 www-data www-data 4096  4 oct.  19:40 ..
root@firefly:/opt/data-importer-test# ll /var/www/test/data-importer/v1.5.7/storage.ori/
total 44
drwxr-xr-x  2 www-data www-data 4096  9 nov.  06:51 uploads
drwxr-xr-x  2 www-data www-data 4096  9 nov.  06:51 submission-routines
drwxr-xr-x  2 www-data www-data 4096  9 nov.  06:51 logs
drwxr-xr-x  2 www-data www-data 4096  9 nov.  06:51 jobs
drwxr-xr-x  6 www-data www-data 4096  9 nov.  06:51 framework
drwxr-xr-x  2 www-data www-data 4096  9 nov.  06:51 debugbar
drwxr-xr-x  2 www-data www-data 4096  9 nov.  06:51 conversion-routines
drwxr-xr-x  2 www-data www-data 4096  9 nov.  06:51 configurations
drwxr-xr-x  3 www-data www-data 4096  9 nov.  06:51 app
drwxr-xr-x 11 www-data www-data 4096  9 nov.  06:51 .
drwxr-xr-x 12 www-data www-data 4096 12 nov.  16:40 ..
```

but my former install worked with a "upload" dir (install migrated from a previous docker installation version 1.5.5)

after upgrade i had this message : 
`Make sure that directory "/var/www/test/data-importer/v1.5.7/storage/uploads" exists and is writeable`
