### ISSUE TITLE
Remove references to external resources

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#947]
Especially Google fonts, possibly other resources.

**Comment by pkoziol** [comment]
I don't know that browsers Filefly supports, but this won't work in IE 11 as [it doesn't support WOFF 2.0](https://caniuse.com/#feat=woff2).

**Comment by JC5** [comment]
Why am I not surprised 😭 

But it's just a font, IE11 users have more to worry about ;).
