### ISSUE TITLE
Default Financial report: Income vs Expense has missing months when multiple currencies are used

### ISSUE THREAD

**Issue by thomase1234** [firefly-iii/firefly-iii#9477]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,

I had an issue on my instance where the Income vs Expense graph didn't contain all data. I think this is related to the fact that I have btoh EUR and USD accounts. I was able to replicate the issue on the demo instance.
Have a look at the graph on this report and compare it with Net Worth. You'll notice there are transactions in EUR for every month of this year. However, I only get columns for the months that have a USD transaction. I did manually create these 2 transactions.
https://demo.firefly-iii.org/reports/default/6,4,1,5,41,40,42,2,3/20240101/20241231

Broken graph:
![Image](https://github.com/user-attachments/assets/46aa29b1-18de-4737-b8cc-79ddd3ffd2bc)

Evidence of transactions every month.
![Image](https://github.com/user-attachments/assets/d25df23a-7e1b-4bcb-be30-d12ba135c99a)

I did create these 2 transactions.
https://demo.firefly-iii.org/transactions/show/456
![Image](https://github.com/user-attachments/assets/90d2853b-8d9c-44df-9401-d12ff8b5e647)
https://demo.firefly-iii.org/transactions/show/457
![Image](https://github.com/user-attachments/assets/71190b64-245d-4078-bbb9-853ea8212f2a)

### Debug information

This is the demo instance.
https://demo.firefly-iii.org/reports/default/6,4,1,5,41,40,42,2,3/20240101/20241231

### Expected behaviour

I expect the monthly columns to be available for every month because there are EUR transactions on every month. 

### Steps to reproduce

1. Wait until the data for the demo instance is cleaned. I think this is on top of every hour.
2. Create a 100 USD transaction.
3. Look at the Default financial report. Include all accounts and the whole year 2024. 
4. The top graph will only contain the last month.

**Comment by JC5** [comment]
Nice find, I'll check it out!
