### ISSUE TITLE
/health endpoint randomly failing on k8s

### ISSUE THREAD

**Issue by eliottness** [firefly-iii/firefly-iii#9480]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Around 5-10 minutes after a firefly container as started, the `/health` endpoint stops responding `OK`. This leads the kubernetes scheduler to kill the pod and restart it, which slowly leads the pod to transition to `CrashloopBackoff`, and thus becoming unavailable. 

### Debug information

Debug information generated at 2024-11-18 20:51:23 for Firefly III version **v6.1.22**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.22 / v2.1.0 / 25 (exp. 25)</td></tr><tr><td>PHP version</td><td>8.3.13 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1147, base <span>#</span>92</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Paris + Europe/Paris</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>fr_FR + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / remote_user_guard</td></tr><tr><td>Login headers</td><td>X-authentik-email + X-authentik-email</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-11-17 23:00:00 (20 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 3</td></tr><tr><td>User flags</td><td><span title="Has reconciled">:ledger:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-12-31 00:00:00</td></tr><tr><td>View range</td><td>3M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0</td></tr></tbody></table>

### Expected behaviour

I would expect the endpoint `/health` to continue returning `OK`.

### Steps to reproduce

1. Setup a Rancher (or minikube) cluster
2. Use the helm chart setup described here: https://firefly-iii.github.io/kubernetes/
3. Wait and look for `Unhealthy` k8s events.

### Additional info

Since there is no relevant logs each times a pod get killed this took me a while to unearth this.

Here is the kubernetes event even through it should be fairly useless:
```
Unhealthy: Liveness probe failed: Get "http://10.42.2.67:8080/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Killing: Container firefly-iii failed liveness probe, will be restarted 
```

I can only do wild guesses but this could be a rate limiting issue maybe... ?
The only current workaround is editing manually the deployment manifest and remove all health checks.

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

I know nothing about kubernetes, so I won't be able to do anything kubernetes-related about this. But I'm surprised: the health checkpoint times out, and the rest doesn't? Because they're all tied to the same code, there's no rate limiting or anything.

**Comment by NerdyShawn** [comment]
is this the stack chart? If you check the app pod logs does it give more detail, for example I think mine was having issues referencing the postgres database, and hence why the app pod would never go healthy.

**Comment by JC5** [comment]
That could be the issue, sure. Could you share some more details?

**Comment by NerdyShawn** [comment]
I've been sorting through a # of issues on this chart recently and hope to help on some of the chart efforts, but I think this particular issues the app pod never goes healthy is if you look a app svc  logs, its referncing service `firefly-db` which doesn't exist.
```c

k logs -n firefly svc/firefly-iii | grep firefly-db | tail -n 1
[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo for firefly-db failed: Name or service not known at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)
```
The default service names from the chart it doesn't align with what the app pod is looking for which the db is actually named in my case `firefly-iii-firefly-db` .
```c
k get svc -n firefly-iii 
NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
firefly-iii              ClusterIP   10.43.88.229   <none>        80/TCP     17m
firefly-iii-firefly-db   ClusterIP   10.43.221.9    <none>        5432/TCP   17m
firefly-iii-importer     ClusterIP   10.43.191.66   <none>        80/TCP     17m
```

This app is expecting what is in its env variable, but the stack chart sets a different dbhost I believe. Essentially some inconsistencies in naming of things in different locations.
- https://github.com/firefly-iii/kubernetes/blob/866e7427c96416535c63d3b2333121d6c870e1b7/charts/firefly-iii-stack/values.yaml#L19
- https://github.com/firefly-iii/kubernetes/blob/866e7427c96416535c63d3b2333121d6c870e1b7/charts/firefly-iii/README.md?plain=1#L94-L95
- https://github.com/firefly-iii/kubernetes/blob/866e7427c96416535c63d3b2333121d6c870e1b7/charts/firefly-db/templates/firefly-db-svc.yml#L5

**Comment by JC5** [comment]
If you can create a PR to fix these, I would really appreciate it!
