### ISSUE TITLE
[API] add optional start and end variable to listEventByPiggyBank

### ISSUE THREAD

**Issue by Administratoor** [firefly-iii/firefly-iii#9485]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I use the API and want to get the events for a specific piggy-bank in a defined timeframe. (From **start** to **end** date)

https://api-docs.firefly-iii.org/#/piggy_banks/listEventByPiggyBank

### Solution

Add optional **start** and **end** variable to piggy_banks/listEventByPiggyBank like it exists for transactions e.g. this one:
https://api-docs.firefly-iii.org/#/transactions/listTransaction

### What are alternatives?

If the feature will not be implemented, one will have to get all events for a specific piggy-bank and loop over the events and write a compare function to find only those entries in a specific timeframe.

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

One will have to keep doing that for the time being, but I'll write it down for the v2 API: https://github.com/firefly-iii/firefly-iii/issues/6307

Thanks!
