### ISSUE TITLE
Data Importer "AxiosError: Request failed with status code 504"

### ISSUE THREAD

**Issue by cj0nes** [firefly-iii/firefly-iii#9486]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello,

I am importing a ~1500 line CSV using Data Importer. The conversion runs fine and then import runs for a little bit. Then the import throws the attached error at me. I have `tail`ed the log file and the import actually continues to run despite this error.

I have not found any indication of this error in the log file. I suspect it is a GUI bug since the import continues on the backend.

![Image](https://github.com/user-attachments/assets/c1fb4806-f298-4a60-ac2d-08f1505a4d93)

Additionally, I notice in the GUI, that the "Messages from the import process" duplicates itself with another listing of actions below the original one that threw the error and no longer spits messages out as it's importing.

### Debug information

Debug information generated at 2024-11-22 16:27:58 Europe/Amsterdam for Firefly III Data Importer version **1.5.6**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.5.6</td></tr><tr><td>System</td><td>PHP 8.3.10, Linux, fpm-fcgi</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Amsterdam, America/Chicago</td></tr><tr><td>Environment</td><td>production</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td></td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0</td></tr></table>

**Comment by JC5** [comment]
Hey, thanks for opening an issue. 

This is a known limitation of the UI. It's a good idea to import smaller batches when you're using the UI or use the command line instead.
