### ISSUE TITLE
Transactions created at midnight on the first day of a month are not listed correctly

### ISSUE THREAD

**Issue by Neroxeles** [firefly-iii/firefly-iii#9491]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Transactions created at midnight on the first day of a month are not listed correctly. See also graphics below. I have also tested this again on a fresh Docker instance.

### Debug information

Debug information generated at 2024-11-23 20:30:30 for Firefly III version **v6.1.23**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.23 / v2.1.0 / 25 (exp. 25)</td></tr><tr><td>PHP version</td><td>8.3.13 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1152, base <span>#</span>92</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td></td></tr><tr><td>Session end</td><td></td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0</td></tr></tbody></table>

### Expected behaviour

For example, if I create a transaction on the first day of November at midnight, it should also be listed for November.

### Steps to reproduce

1. Create a transaction on the first day of November at midnight.
2. Go to the Dashboard page or to transactions -> expenses.
3. Select Nov 1, 2024 to Nov 30, 2024 as the time window.

### Additional info

![Image](https://github.com/user-attachments/assets/6f4ef3e8-14b2-4f38-bc4f-a1470daf6da9)
Created transaction

![Image](https://github.com/user-attachments/assets/fd118274-45be-4ba2-ad2e-ffe274bd2e15)
Dashboard

![Image](https://github.com/user-attachments/assets/223d2de5-b78b-43a8-b6c8-215926f3eddd)
Transactions -> Expenses (November)

![Image](https://github.com/user-attachments/assets/da2fe437-8cc7-4e34-aa3c-a686342b89eb)
Transactions -> Expenses (October)

**Comment by JC5** [comment]
Indeed, nice find. I will push 6.1.24 to fix this. Once it has been released, editing the transaction should make it show up again.
