### ISSUE TITLE
'Attempt to read property "user" on null' error when running `php artisan firefly-iii:upgrade-database` on updating to v6.1.24

### ISSUE THREAD

**Issue by ChrisCarini** [firefly-iii/firefly-iii#9497]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello,

I am getting the below error when running through the upgrade procedure (upgrading from `v6.0.30` to `v6.1.24`).

```
...
  [i] This command has already been executed.
      Now executing firefly-iii:liabilities-600
  [i] This command has already been executed.
      Now executing firefly-iii:budget-limit-periods

   ErrorException 

  Attempt to read property "user" on null

  at app/Handlers/Events/Model/BudgetLimitHandler.php:134
    130▕                 if (0 !== bccomp($amount, '0')) {
    131▕                     app('log')->debug(sprintf('Will create AB for period %s to %s', $current->format('Y-m-d'), $currentEnd->format('Y-m-d')));
    132▕                     $availableBudget = new AvailableBudget(
    133▕                         [
  ➜ 134▕                             'user_id'                    => $budgetLimit->budget->user->id,
    135▕                             'user_group_id'              => $budgetLimit->budget->user->user_group_id,
    136▕                             'transaction_currency_id'    => $budgetLimit->transaction_currency_id,
    137▕                             'start_date'                 => $current,
    138▕                             'start_date_tz'              => $current->format('e'),

  1   app/Handlers/Events/Model/BudgetLimitHandler.php:134
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Attempt to read property "user" on null", "/home/my_user/firefly.domain.com/firefly-iii/app/Handlers/Events/Model/BudgetLimitHandler.php")

  2   app/Handlers/Events/Model/BudgetLimitHandler.php:251
      FireflyIII\Handlers\Events\Model\BudgetLimitHandler::updateAvailableBudget(Object(FireflyIII\Models\BudgetLimit))

my_user@my_host:~/firefly.domain.com/firefly-iii$ 
```

### Debug information

n/a - page does not load.

### Expected behaviour

This error does not occur, and things are handled as 'cleanly' as possible (whatever that means here; unsure even after trying some basic debugging).

### Steps to reproduce

1. Run through the below script manually, one command at a time:
```
#!/bin/bash

set -e

BACKUP_POSTFIX=$(date "+%Y-%m-%d_%H%M%S")

# Pull the PHP_BINARY from environment variables.
if [[ -z "${PHP_BINARY}" ]]; then
  echo "PHP_BINARY is not set. Run 'export PHP_BINARY=/usr/local/php83/bin/php' and try this script again."
  exit 1
else
  echo "Using PHP path: $PHP_BINARY"
fi

echo "Get latest version of firefly..."
latestVersion=$(curl -s https://api.github.com/repos/firefly-iii/firefly-iii/releases/latest  | grep -oP '"tag_name": "\K(.*)(?=")')

echo "Downloading latest version (${latestVersion})..."
wget "https://github.com/firefly-iii/firefly-iii/releases/download/${latestVersion}/FireflyIII-${latestVersion}.zip"
wget "https://github.com/firefly-iii/firefly-iii/releases/download/${latestVersion}/FireflyIII-${latestVersion}.zip.sha256"

echo "Verifying checksum..."
sha256sum -c "FireflyIII-${latestVersion}.zip.sha256"
if [ $? -ne 0 ]; then
  echo "Checksum failed. Exiting..."
  exit 1
fi

echo "Backing up the old installation..."
mv firefly-iii "firefly-iii-backup-${BACKUP_POSTFIX}"

echo "Unzipping the new version..."
unzip -o "FireflyIII-${latestVersion}.zip" -x "storage/*" -d ./firefly-iii

echo "Changing permissions of the storage directory..."
mkdir ./firefly-iii/storage
chmod -R 775 ./firefly-iii/storage

echo "Copy the .env file..."
cp "./firefly-iii-backup-${BACKUP_POSTFIX}/.env" ./firefly-iii/.env

echo "Copy the storage directory..."
cp -r "./firefly-iii-backup-${BACKUP_POSTFIX}/storage" ./firefly-iii

echo "Running upgrade commands..."
pushd ./firefly-iii
$PHP_BINARY artisan migrate --seed
$PHP_BINARY artisan firefly-iii:decrypt-all
$PHP_BINARY artisan cache:clear
$PHP_BINARY artisan view:clear
$PHP_BINARY artisan firefly-iii:upgrade-database
$PHP_BINARY artisan firefly-iii:laravel-passport-keys
popd

echo "Successfully upgraded Firefly-iii to version ${latestVersion}"
```

2. When running `$PHP_BINARY artisan firefly-iii:upgrade-database`, the above error is seen.

### Additional info

What's strange, I started trying to debug this (trying to make the best sense I can without being that familiar with the code base) by looking at my DB to see if anything obvious stood out. Nothing really did, even after I tried doing some joins between what seemed to be the two relevant tables. I then added some `echo` statements in various places (my attempt at enabling debug logging did not work the way I expected; no debug logs were printed. Guessing I was doing something wrong). When running `$PHP_BINARY artisan firefly-iii:upgrade-database` multiple times, I noticed that the command seemed to pick up where it left off, except skip over any 'bad' rows in the `budget_limits` table - specifically, it seemed to have issues with any row that had a `transaction_currency_id` equal to `NULL`. This seemed a bit suspect, the only relation I could see is that the corresponding `budgets` entries all had a `deleted_at` entry (whereas the rest were all `NULL`). It's strange that the error is seeming complaining that `user` is null, since all of the rows have a (valid) user id associated with them.

Extra odd (and, maybe/hopefully of some use) it seems like line 68 (`$user        = $budget->user;`) was returning the correct user; I was partially inclined to change `$budgetLimit->budget->user->id` to `$budget->user->id` (as well as `user_group_id`) and re-run the script and hope for the best, but I was unsure of the ramifications of doing so, so I opted to not do this.

Eventually, I ran `$PHP_BINARY artisan firefly-iii:upgrade-database` a bunch of times, and was able to get it to complete successfully (but this was non-obvious until I added echo 'debug' statements). I'm not sure if any of the migrated data is missing/invalid/incorrect/inconsistent now or not, but I'd love to know, if possible.

**Comment by JC5** [comment]
Hey, thanks for opening an issue. Excellent debugging, I found the issue in no time. It turns out the reference to the user object could indeed be null at that point, hence the error. It's rare so it rarely shows up but it shouldn't give you issues.

A fix will be part of the next release :).
