### ISSUE TITLE
Unable to read key from file

### ISSUE THREAD

**Issue by mamob07** [firefly-iii/firefly-iii#9503]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I get this error every time I try to add a new transaction :
`
Unable to read key from file file:///www/wwwroot/<website_path>/storage/oauth-public.key
`

### Debug information

Debug information generated at 2024-11-27 17:33:46 for Firefly III version **v6.1.19**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.19 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.12 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>52428800 (50 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Rome + Europe/Rome</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, daily / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>it_IT + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2024-11-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-11-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>it_IT</td></tr><tr><td>User locale</td><td>it_IT</td></tr><tr><td>Locale(s) supported</td><td>it_IT.utf8: :white_check_mark:<br>it_IT.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

A new transaction should be created according to the data I entered.

### Steps to reproduce

1. New transaction tab
2. Fill required fields
3. Enter

### Additional info

This is the content of the file:
`
[[public_key]]
`
In the database, instead, I can see the key

There is a similar closed issue ([#7934](https://github.com/firefly-iii/firefly-iii/issues/7934)) but I don't understand if I have to delete the entire row in the database or just the content of the "data" column.

**Comment by mamob07** [comment]
> Hey, thanks for opening an issue!
> 
> If you delete both files (also the private variant) they should be restored correctly from the database.

I tried what you say but the files created are as before. So one `[[public_key]]` and the other one `[[private_key]]`
As I said before I think this is the same as the [#7934](https://github.com/firefly-iii/firefly-iii/issues/7934) issue, but I didn't understand if I have to delete the entire row in the database or just the content of the "data" column.

**Comment by JC5** [comment]
Sorry, I have no clue. You can delete the entire row, that should work fine.

Either way, I suspect it may be a virus scanner or something that replaces these keys?

**Comment by mamob07** [comment]
I solved. I had to run the command `php artisan passport:install --force` to replace keys.
