### ISSUE TITLE
UI for advanced search

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#9504]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would really appreciate an advanced search feature for firefly iii with a better accessibility, like a coresponding UI.
I wanted to use advanced search paramters (like "notes_contain") for a long time and just realised that this is possible, after taking a look at the documentation (https://docs.firefly-iii.org/references/firefly-iii/search/).
While the features are already there (which is really nice) it would be perfect to have a UI with fields where you can select the field you like to search or perform a full-text search.

### Solution

Development of an UI for advanced searches.

### What are alternatives?

Using the serach parameters manually.

### Additional context

I know this might be not a thing with the highest priority but maybe it can be implemented somewhere in the future, maybe with the v2 UI.

**Comment by JC5** [comment]
Yes, please see https://github.com/firefly-iii/firefly-iii/issues/6323 for this :)
