### ISSUE TITLE
Command line import doesn't update balance

### ISSUE THREAD

**Issue by Edubits** [firefly-iii/firefly-iii#951]
I am running Firefly III version 4.6.9

#### Description of my issue:
When executing a csv import from the command line  (using `php artisan firefly:create-import`) the transactions are imported correctly and are visible in the overview. However the balance of the affected asset account is not updated. After adding a transaction manually through the UI the balance is updated. 

#### Steps to reproduce 

1. Import a csv file through the command line 
2. Check the balance in the UI of the affected asset account
3. Notice it's not updated
4. Create a transaction through the UI for this account
5. Notice the balance is updated correctly now

**Comment by gavu** [comment]
I had the same issue with the charts, on the previous release. Did a `php artisan ca:cl` and everything looked better

**Comment by Edubits** [comment]
That would mean clearing the full cache after each import, is that what happens with an import through the UI as well?

**Comment by JC5** [comment]
Yes, it should be, but not clearing the cache when importing over the command line is an oversight on my part. I will include a fix for the next release!

**Comment by Edubits** [comment]
Thanks @JC5!
