### ISSUE TITLE
Date selector does not respect the Locale settings

### ISSUE THREAD

**Issue by fgnix** [firefly-iii/firefly-iii#9511]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In the transaction editor, the date selector field follow the "Languages" setting instead of "Locale settings"

### Debug information

Firefly version is 6.1.24

### Steps to reproduce

1. Set "Locale settings" to "German"
2. Leave "Languages" to English (GB)

Dates in the date editor are sill in the MM/DD/YYYY format

1. Set "Locale settings" to "German"
2. Set also "Languages" to "German"

Dates in the date editor are now in the correct DD/MM/YYYY format

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

This is not a bug. Firefly III uses the "dateline-local" field to render dates and leaves it entirely to your browser. Set your browser to your locale and you should see the results you expect. 

Please see the search for more info, this gets asked fairly regularly.
