### ISSUE TITLE
Every other Weekly Repetitions

### ISSUE THREAD

**Issue by samuelbarata** [firefly-iii/firefly-iii#9514]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I'd like to be able to add an expense that repeats every other week

### Solution

When creating a Recurring Transaction have a repetition type of
`Every Other Week` and an option to select on which day it starts.

### What are alternatives?

Creating a transaction Every Week on Monday with half the amount.
This is a bad option because:
- Transactions will never match bank statement
- Transaction cycle might not start on a Monday

### Additional context

My gym membership is due every other week on a Wednesday

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

The solution is to select "weekly" and set the "skip" option to 1.
