### ISSUE TITLE
"Remove money from piggy bank" form generates error

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#952]
I am running Firefly III version 4.6.9 

#### Description of my issue:

Empty amount field in "Remove money from piggy bank" form generates error:

#####  when removing:
> Type error: Argument 2 passed to FireflyIII\Repositories\PiggyBank\PiggyBankRepository::canRemoveAmount() must be of the type string, null given, called in /var/www/firefly-iii/app/Http/Controllers/PiggyBankController.php on line 329 

##### when adding:
> Type error: Argument 2 passed to FireflyIII\Repositories\PiggyBank\PiggyBankRepository::canAddAmount() must be of the type string, null given, called in /var/www/firefly-iii/app/Http/Controllers/PiggyBankController.php on line 290 

#### Steps to reproduce 

1. Go to Piggy-Banks
2. Click on the "+" or "-" sign to add or remove money
3. Leave the amount-field **empty**!
4. Click "Add" or "Remove"

**Comment by JC5** [comment]
It's fixed on dev, and will be included in the next update. The upgrade to Laravel 5.5 will have left more fields broken, when nothing is filled in. Let me know when you spot one!

**Comment by gavu** [comment]
Good to know, I'll try to go through all the forms I can find and report them here

**Comment by gavu** [comment]
I went through (hopefully) the entire demo install, and did not find any forms that crash when provided empty values (yet). I did however stumble upon a missing translation:

![2017-10-25 11_50_09-edit rule _your first default rule_ rules firefly iii](https://user-images.githubusercontent.com/3742238/31992714-4fba9f24-b97b-11e7-9241-46eebb5e2b05.png)

**Comment by JC5** [comment]
Nice find!

Those are [translatable](https://github.com/firefly-iii/firefly-iii/blob/master/resources/lang/de_DE/validation.php#L70), it's just that they don't become much prettier when translated: the Laravel validation framework isn't really built to handle these kinds of complex forms. The `.1` things are unavoidable.

**Comment by gavu** [comment]
Maybe hide the ".1" with jQuery when validating?

**Comment by JC5** [comment]
Closed, a new release is live.
