### ISSUE TITLE
ReportSum Integrity Check fails due to empty foreign_amount

### ISSUE THREAD

**Issue by SircasticFox** [firefly-iii/firefly-iii#9532]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,

I think I encountered a bug in Firefly. I started noticing an error, when starting the instance with the firefly-iii:report-sum integrity check. I've a single user and report-sum calculated an empty string "". Beeing non zero it failed. While everything worked, the error was still annoying me a little bit.

So I looked up the reportSum function and saw that it's the SUM of the amount and foreign_amount column. But since I don't use foreign_amount this is empty. So I temporarily removed the SUM of foreign_amount and now the report-sum check succeeds again.

Therefore the report-sum check returns an empty string, when adding the SUM of amount (0) and SUM of foreign amount ("").
I don't know if this might be because of postgres, but wanted to share nevertheless.

Thanks for the great project and all the work.

 

### Debug information

Unraid
Firefly 6.1.24
PGSQL 15.10

### Expected behaviour

The report-sum integrity check should not fail if the foreign_amount column is empty.

**Comment by JC5** [comment]
Nice find. The fix for one bug causes another haha. I'll pick it up!
