### ISSUE TITLE
Additional chart view ranges

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#954]
I am running Firefly III version 4.6.9

#### Description of my issue:

Possibility to view the following:
* One week (since same day last week)
* One month (since same day last month)

#### Steps to reproduce 

For the current ranges, the "One week" range makes no sense on Mondays and "One month" on the 1st of every month. Same goes for "Three months (quarter)", which I used for a while but that only occurs once every 3 months. It would be nice to be able to see how/what I spent last week, even on Mondays, without changing the date range for the entire system

**Comment by JC5** [comment]
You're looking for something like "last 7 days" or "last 30 days"?

**Comment by gavu** [comment]
Yes. Exactly...

**Comment by gavu** [comment]
I don't know if you decided or not to implement this, but I just had an idea, maybe just add one more radio field with a text input. Something like

...
(   ) One day
(   ) One week
(   ) Last [____] days


Where the user can type in the desired amount of days

**Comment by JC5** [comment]
I've added options for the last 30 days and last 7 days. They're visible on the demo site.

For other ranges, you'll have to use the "custom" range.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
