### ISSUE TITLE
[Enhancement] Link Github Repo to Dockerhub

### ISSUE THREAD

**Issue by alazare619** [firefly-iii/firefly-iii#955]
I would like to see you link the repo to dockerhub. This would allow for automatic dockerfile generation and would be able to simply the docker compose/run process drastically as you could just pull the image vs the entire repo. The image would automatically generate whenever you updated master as well.

**Comment by alazare619** [comment]
@JC5

**Comment by JC5** [comment]
I already have a [Docker account](https://hub.docker.com/r/jc5x/firefly-iii/) somewhere, and I think it builds just fine. Other users have these images as well. Have you tried them?

**Comment by alazare619** [comment]
Yes the docker file with the make command works but if the image was on
docker hub users can just do a docker pull then

**Comment by JC5** [comment]
What do you use for the database?

**Comment by alazare619** [comment]
You can use Dr pull to pull the latest MySQL:8

**Comment by alazare619** [comment]
if you login to dockerhub and copy your readme.md of the main directory you can go to settings and link to github repo you will just have to enter your credentials once that is done i can do initial testing. Many big projects have their docker files hosted on dockerhub that use seperate databases from their projects i.e. guacamole and bitwarden for instance.

**Comment by JC5** [comment]
I’ll check it out! Thanks!

**Comment by alazare619** [comment]
Once you push a change to master on github dockerhub will see the changes and rebuild the docker image so the next time a user just has to do docker pull firefly-iii and it automatically updates their local copy with all the changes in your repo. Its really neat and 100% automated :)

**Comment by JC5** [comment]
https://hub.docker.com/r/jc5x/firefly-iii/

**Comment by alazare619** [comment]
Awesome now docker files (the compose) can be pointed to that and will automatically update when a new image is pulled will make updating 100% automated for end users. I'll do some testing and report back :) thanks for being so receptive :)

**Comment by JC5** [comment]
Of course, of course!

By that, you mean the various docker-compose files in the root, right? I'd love your pointers 👍

**Comment by alazare619** [comment]
Yes in a nut shell, users would no longer to git clone the repo all they would need is a directory with 2 docker compose files (that shouldnt change) all they would need to do is create the 2 docker compose files then docker-compose up (after seeding the sql table the first time)

**Comment by alazare619** [comment]
Sorry for not getting back to you sooner. IRL has been pretty crazy this past few days. Here is the one docker compose file. It will start firefly-iii pull the current build which is synced to dockerhub which is inturn synced to github on the master branch. It will start mysql 8 and create the db. User will need to edit the compose file accordingly still and on the first run of firefly-iii they will need to execute the php artisian docker-compose exec commands but after that it will update on its on without having to clone github etc....  If you want I can do a PR to make it all "official"
https://gist.github.com/alazare619/d74bb58671c807723b2a3b324f9919c7

**Comment by JC5** [comment]
Don't worry, I know how it is. If you make the pull request to the develop branch, it would really make it your contribution and mark you as a contributor as well. Plus, then I will be sure it is done right.

**Comment by alazare619** [comment]
https://github.com/firefly-iii/firefly-iii/pull/961

**Comment by alazare619** [comment]
This PR issue may be closed as pr has been submitted and moved to develop. Thanks @JC5

**Comment by JC5** [comment]
Indeed. Thanks! The file will move to the master branch with the next release. I expect it to be this weekend.
