### ISSUE TITLE
Timezone for Kazakhstan, for example, Asia/Almaty is still +6

### ISSUE THREAD

**Issue by DelmorS** [firefly-iii/firefly-iii#9555]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When setting Asia/Almaty as default timezone for Firefly instance, for example, in .env file for docker compose, you can notice, that time is still shown as +6, though, on March of 2024 default time for entire Kazakhstan was changed to be +5. 

### Debug information

Debug information generated at 2024-12-17 09:33:40 for Firefly III version **v6.1.24**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.24 / v2.1.0 / 25 (exp. 25)</td></tr><tr><td>PHP version</td><td>8.3.13 (64bits) / apache2handler / Linux aarch64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*pgsql*</strong>, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1153, base <span>#</span>92</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Asia/Tashkent + Asia/Oral</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>ru_RU + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-12-16 19:00:00 (9 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span></td></tr><tr><td>Session start</td><td></td></tr><tr><td>Session end</td><td></td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>ru_RU</td></tr><tr><td>User locale</td><td>ru_RU</td></tr><tr><td>Locale(s) supported</td><td>ru_RU.utf8: :white_check_mark:<br>ru_RU.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0</td></tr></tbody></table>

### Expected behaviour

Time for Asia/Almaty and all other Kazakhstan timezones should be set to +5

### Steps to reproduce

It can be noticed, when creating any new transaction, for example, expenditure - usually your current realtime is shown, and timezone is written. For Asia/Almaty it will be +1 hour from current realtime of Kazakhstan.

**Comment by JC5** [comment]
Hi,

Thanks for opening an issue. 

This is part of the underlying operating system that runs Firefly III and not something I can fix unfortunately.

**Comment by JC5** [comment]
I'm sure it has. But the timezones are provided by the container. There's still very little I can do about that.

**Comment by DelmorS** [comment]
> I'm sure it has. But the timezones are provided by the container. There's still very little I can do about that.

I was able to look inside **firebase_iii_core** container file system, and in zoneinfo I found, that Almaty timezone has the same time of +5, as for parent Ubuntu system

```
root@firefly-app:/usr/share/zoneinfo/Asia# more Almaty
TZif2           5       ?{ܵ??0'}? ?
????i?v??g??X??I?|:? l+?!\?"L

<+05>-5
```
And the same for **firebase_iii_db** (i use postgre)

Could you please give me a hint, when I open any transaction, and it shows its time aligned according to Timezone, based on which values time is calculated? Maybe it is based on timezones of target device? Or may be I am just checking in wrong place..

**Comment by JC5** [comment]
Perhaps it is a browser setting? It fills in the local date and time.

**Comment by DelmorS** [comment]
> Perhaps it is a browser setting? It fills in the local date and time.

Yes you were right! I installed special extension, which allows changing Timezone per page, and when I updated it to Asia/Tashkent, everything worked correctly. Thank you again for your tip!
