### ISSUE TITLE
currentMonthStart/currentMonthEnd not supported by REST API

### ISSUE THREAD

**Issue by gccollect** [firefly-iii/firefly-iii#9556]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Running the command:
`curl 'GET' 'http://localhost:8003/api/v1/summary/basic?start=currentMonthStart&end=currentMonthEnd' -H 'accept: application/vnd.api+json' -H 'Authorization: Bearer [token]' -H 'Content-Type: application/json'`
Returns `The start is not a valid date. The end is not a valid date.`

While running the command:
`curl 'GET' 'http://localhost:8003/api/v1/summary/basic?start=20241201&end=20241231' -H 'accept: application/vnd.api+json' -H 'Authorization: Bearer [token]' -H 'Content-Type: application/json'`
Returns the expected result

So it would appear that the REST API unlike the base app does not support currentMonthStart, currentMonthEnd, etc. Any chance this could be supported?

### Solution

It would allow the user to use the same date shortcuts (i.e. currentMonthStart, currentMonthEnd, etc.) in the REST API as in urls

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

API users will have to calculate their own dates I'm afraid.
