### ISSUE TITLE
Firefly III mixes the "MobilePay" accounts

### ISSUE THREAD

**Issue by dlegranddk** [firefly-iii/firefly-iii#9561]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

In Denmark (but also other countries), we have a "MobilePay" service ([website](https://www.mobilepay.dk/)) for payments between people and also with companies.

So if I send 10 kroners to "John Doe", 20 kroners "Jane Doe" and 100 kroners to a company "FooBar", I will see in my bank account
* 10 kroners to "MobilePay John Doe"
* 20 kroners to "MobilePay Jane Doe"
* 100 kroners to "MobilePay FooBar"

The issue is when importing from GoCardLess, the reconciliation of the account goes to the wrong expense account, the last example I have is paying to MobilePay FooBar will end up with a destination account MobilePay John Doe which has been used for the last time in 2023.

The MobilePay FooBar account exists as well in the expense accounts as it's a monthly payment. I would expect the issue is with this "MobilePay " prefix of the creditor account.

### Debug information

I'm not sure how much data I could provide, at least the GoCardLess initial transaction

{
                "transactionId": "XXXX",
                "entryReference": "XXXXX",
                "bookingDate": "2024-12-18",
                "valueDate": "2024-12-18",
                "bookingDateTime": "2024-12-18T00:00:00Z",
                "valueDateTime": "2024-12-18T00:00:00Z",
                "transactionAmount": {
                    "amount": "-100.00",
                    "currency": "DKK"
                },
                "creditorName": "MobilePay FooBar",
                "creditorAccount": {
                    "bban": "XXXX"
                },
                "remittanceInformationUnstructured": "MobilePay FooBar\nEndToEndID: mf-XXXXX",
                "additionalInformation": "XXXX",
                "merchantCategoryCode": "XXXX",
                "internalTransactionId": "XXXX"
            }

### Expected behaviour

Import transaction with the CreditorName "MobilePay FooBar"
The Destination account is either reused or created "MobilePay FooBar"

### Additional info

This defect isn't urgent for me, Firefly III saves me a lot of time anyway and I created some rules to manage the most important "MobilePay" transactions, I thought to report it as there is probably an underlying issue and as at least the trend is to go to cashless economy, these creditor names sharing a prefix might get more popular.

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

This is not the result of the importing "mixing things up", that's not how it works. 

The service probably uses the same IBAN/BBAN behind each different name. Firefly III distinguishes accounts based on the account number, not the name. So whichever account has the account number, that's the name you will see. 

I see this in my own imports as well. I have no solution yet.

**Comment by dlegranddk** [comment]
Indeed, I was seeing unique bbans in the latest GoCardLess transaction file so I haven't thought of that, sorry.
So the best solution would actually for MobilePay company to have unique bban instead of somehow reusing them. Meaning, I'll just need to create more rules to fix it on my side :)
As I know building a regular expression parser, on the transaction rules, isn't a feature you want to develop, I'll try one day to understand how to implement such a feature in a good manner and completely optional as I could do "If Description/Account starts with MobilePay, match the string ^MobilePay [^\\n]+ and then Set Destination Account based on name (find or create)".

In the meantime, I close the issue as it isn't a Firefly III one, thanks again for your good work and looking forward for all the nice features you are developing :)
