### ISSUE TITLE
Make cron container timezone aware

### ISSUE THREAD

**Issue by haithcockce** [firefly-iii/firefly-iii#9565]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

The cron container defaults to the UTC timezone making crontab
entries and jobs relative to UTC rather than the timezone designated
in .env.  The cron container should pull in the tz variable and set the 
timezone in the container so the crontab and cron jobs are timezone
aware. 

### Solution

```
commit d8aea654cc99a907b0903799756886ac0b2102d0 (HEAD -> make-cron-tz-aware)
Author: Charles Haithcock <haithcockce@pm.me>
Date:   Sat Dec 21 13:46:46 2024 -0700

    Make cron container timezone aware
    
    The cron container defaults to the UTC timezone making crontab
    entries and jobs relative to UTC rather than the timezone designated
    in .env. This change adds the tzdata database to the cron container
    and sets the timezone to the value set in .env.

diff --git a/docker-compose.yml b/docker-compose.yml
index 25816b7..425e4b4 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -31,7 +31,13 @@ services:
     image: alpine
     restart: always
     container_name: firefly_iii_cron
-    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME;echo\" | crontab - && crond -f -L /dev/stdout"
+    env_file: .env
+    command: sh -c "
+        apk add tzdata 
+        && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
+        | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME;echo\"
+        | crontab - 
+        && crond -f -L /dev/stdout"
     networks:
       - firefly_iii
```

I tried submitting a branch for a pull request to the docker repo but I can't seem to do so.

**Comment by JC5** [comment]
Hey,

Thanks for opening an issue. I like this idea. Feel free to open a PR, there are no settings that prevent this.

**Comment by JC5** [comment]
Did you get an error or something? Let me know!

**Comment by haithcockce** [comment]
Thankfully figured it out; user error (as usual) influenced by my first time contributing to an upstream project rather than company-internal workflows!

**Comment by JC5** [comment]
Fixed with merge, thanks!
