### ISSUE TITLE
Can't set budget on future months

### ISSUE THREAD

**Issue by brentdur** [firefly-iii/firefly-iii#957]
I am running Firefly III version x.x.x 

#### Description of my issue: 

If I got to a month in the future and set the budget for that month it changes my budget for the current month.

#### Steps to reproduce 

Open budget to October, set a budget to say $50. Go to November, the budget should say $0, adjust it to $1 and go back to October. It will have changed to $1. Go back to November, it will be at $0.

**Comment by JC5** [comment]
Thanks for reporting this. Which version of Firefly are you running? I can’t reproduce this on the demo site, and if i recall correctly, a similar bug has been fixed in a previous version.

**Comment by gavu** [comment]
I tried it too, can't reproduce it either (using 4.6.9)

**Comment by brentdur** [comment]
Oh whoops. Thought I was running off master but docker was using a previous build
