### ISSUE TITLE
Show the split transactions as grouped in Reconcilation

### ISSUE THREAD

**Issue by th1k4n** [firefly-iii/firefly-iii#9570]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I was quite a user for the reconciliation function from firefly III as for cross checking from my bank statements, but the statements always shows the overall amount, instead of the split amounts from the reconciliation functions.   
There are group feature to show one split transaction in many parts from Firefly III, but just not in reconciliation function only.

Current Reconciliation part
![Image](https://github.com/user-attachments/assets/dc49f081-db93-4e5d-a399-4f04e718f66e)
  

### Solution

The constraint from the split transactions had locked the source assets account to be the same.  
The proposed solution would just be reusing the grouping feature to the reconciliation functions, maybe an extra checkbox for the feature if wanted to be optional for user. 

Like this in asset account:
![Image](https://github.com/user-attachments/assets/9c7f2ed1-97b1-44ff-a32a-b36c5418b9db)  

### What are alternatives?

- read manually from the account's page manually for the overall amount
- doing sum per each split transactions manually to compare with the bank statements

**Comment by JC5** [comment]
Hi, thanks for opening an issue.

Several issues already exist regarding this topic.

Please see #6302
