### ISSUE TITLE
Option to send Reports via Email

### ISSUE THREAD

**Issue by mrcsdl** [firefly-iii/firefly-iii#9577]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hey,

i like this tool a lot. What would be awsome if there is a function that you can send your reports directly to your mail or if possible even a selected one.

that would make my life so much easier.

### Solution

Nicer workflow if using reports, sending them directly to your email

### What are alternatives?

Print it out and send it via email as an pdf or so

### Additional context

merry christmas

**Comment by JC5** [comment]
Hi, thanks for opening an issue. 

Sorry, this will not go on the list. Too much work for too little gain. 

Merry Christmas to you too :)

**Comment by mrcsdl** [comment]
no worries. Greetings from Germany :)
