### ISSUE TITLE
[Feature Request] Ability to add notes to bills

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#959]
I am running Firefly III version 4.6.9 

#### Description of my issue:

Ability to add notes to bills. I would add notes like
* Customer identification (e.g. number, id)
* Contract cancellation requested at
* Contract cancellation accepted at
* Contract expires automatically at
...

**Comment by gavu** [comment]
And attachments. I’d love to have some way to keep track of my contracts and cancellations!

**Comment by JC5** [comment]
Attachments and notes could work.

**Comment by JC5** [comment]
Will be included in the next release!
