### ISSUE TITLE
Search function does not find all transactions

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#963]
I am running Firefly III version 4.6.9

#### Description of my issue:

I exported all the transactions to see what I can rename/organize using rules to have a better overview
I found the following transactions which were not matched by one of the rules (it was e trigger mistake on my side). I fixed the rule, the transactions were renamed/organized correctly, however the search function does not find two (or maybe more) of them:

All expenses between July 1, 2016 and July 31, 2016
![2017-10-30 12_00_26-all expenses between july 1 2016 and july 31 2016 transactions firefly iii](https://user-images.githubusercontent.com/3742238/32167715-0ee090d8-bd6a-11e7-8ac7-1384efb93100.png)

Number of transactions found: 20
![2017-10-30 11_58_31-search results for _fuel_ search firefly iii](https://user-images.githubusercontent.com/3742238/32167706-0758b3fe-bd6a-11e7-9acf-91b7601c3e99.png)

#### Other important details (log files, system info):

As you can see, the search does not return any transactions from 2016. I have tried the following:
1. renamed a transaction from "Fuel" to "Fuels" and back to "reset" it
2. did a `artisan ca:cl`

**Comment by JC5** [comment]
The search has [a hard-coded limit of 20](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/SearchController.php#L80).

You can use date-ranges to search in ranges of time (per year or per month). I shall make the limit something you can configure.

**Comment by gavu** [comment]
I tried to set the date ranges in the navbar (search ignores them), or directly in the search form `fuel on:2016-07-18` but the latter one returns nothing. I am sure I am doing something wrong here, can you help? how do I have to format the search string?

**Comment by JC5** [comment]
It seems to work for me but I’ll have to debug at a later moment. I’ll get back to you.

**Comment by gavu** [comment]
Just an update:

I have tried the following:
* `fuel on:2016-07-18` => returned 0 results
* `fuel on:2016-10-23` => returned 1 result (correct match)

**Comment by JC5** [comment]
I've pushed a few changes that should fix this. Reason it didn't return anything is probably because it couldn't find it within 30 seconds. This has been improved making _most_ searches doable within 30 seconds.

**Comment by gavu** [comment]
I can confirm, it returned all the entries matching "fuel" - thanks!

**Comment by JC5** [comment]
Closed, a new release is live.
