### ISSUE TITLE
[Feature Request] Add "Current month" option in date selector

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#964]
I am running Firefly III version 4.6.9 

#### Description of my issue:

While looking through different periods, I find it annoying to have to return to the present by setting a custom date for the current month in the navigation. If possible, please add a "Current month" button somewhere in there too

![2017-10-30 13_59_04-daterange selector](https://user-images.githubusercontent.com/3742238/32172448-e38187a0-bd7b-11e7-91fd-ca5aaf91916f.png)

**Comment by JC5** [comment]
Current period, denoted as "Today" will be included in 4.6.12!

**Comment by gavu** [comment]
Looks great, thanks!

**Comment by JC5** [comment]
Closed to clean up the list.
