### ISSUE TITLE
Feature Request for QFX Support

### ISSUE THREAD

**Issue by alazare619** [firefly-iii/firefly-iii#965]
Just an idea. QFX/OFX is a standards compliant format supported by most large banks. QFX was designed around the OFX standard. It was put into use as alot of canadian banks and european countries do not allow 3rd party software to download transactions from a bank directly. I will attach a scrubed example in a reply. QFX is nothing more then xml with different component tags.

The feature and enhancement this would bring if a user chose a QFX for example they would not need to do the column selection etc as QFX has to adhere to a very strict styling standard.

**Comment by JC5** [comment]
OFX and QFX are file types I want to support in the future, yep. OFX is also XML, right?

**Comment by alazare619** [comment]
Yes each is built upon the previous. XML > OFX > QFX

OFX being open file exchange was orginally developped for apps like quicken to login to the bank and download. It is based upon XML

QFX because of regulations is built upon OFX and was designed for users to login and download a file and import into quicken.

**Comment by kevinjqiu** [comment]
I use QFX from my financial institutions whenever I can. It's a standard so there's fewer ambiguities than, say, CSVs.

I have a local branch that implements this feature using the [OFX parser](https://github.com/asgrim/ofxparser) library but it's still rough around the edges - I'm new to firefly and still learning how the code is setup.

**Comment by JC5** [comment]
I saw it, nice!

Current progress is stalled: I want to wait for the [PSD2](https://en.wikipedia.org/wiki/Payment_Services_Directive) developments. I see several trends, both in API's and file import/export formats. The long term goal is to support as much as possible.

**Comment by eduedp** [comment]
I also would appreciate very much this future feature. Do you have an ETA?
All the banks I own an account use OFX to export transactions.

**Comment by jtbayly** [comment]
Since I don't see any evidence of PSD2 having any impact on US-based banks and providers, and OFX/QFX is already supported by all my current providers, I'd like to add my voice to those asking for this to be added. Right now, as far as I can tell, it's the only real option for users in the USA. None of the other import methods work. Even QIF would be a vast improvement over where things stand right now.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937520

**Comment by jtbayly** [comment]
Does this mean that there are no plans currently to support OFX/QFX? (The main project will only add an API and *if* somebody ever gets around to writing a plugin for OFX/QFX, then it will be a separate project?) 

In other words, are there currently no immediate plans to make this project useable by consumers using US-based banks?

**Comment by JC5** [comment]
The project is perfectly usable, thank you very much. 

An import routine for OFX/QFX is on my backlog, as are plenty of other things. And like I said, I want to separate the import functionality from the main code base. 

Personally I don’t believe in personal finance management by simply importing your financial administration in yet another app. If you want to manage your finances and change your expense pattern you’ll have to become more aware of your finances. You’ll never get there by importing your stuff and looking at yet another set of charts. 

I would suggest you start entering your transactions manually, starting today. Don’t import your history, but look at what’s happening right now. That will give you all the insight you need.

**Comment by JC5** [comment]
But feel free to build something and I’ll happily promote you in the readme.

**Comment by jtbayly** [comment]
Apologies for my wording. I know that there are good reasons to manually enter transactions for many people. However, it is just extra busywork for me. There is a whole category of people not looking to get their finances under control but rather keep them under control. Automation is key to that, in my experience. 

I like your program.

Cheers.

**Comment by hockeymikey** [comment]
Why would I ever want to manually enter all of my transactions?! I can use Excel if I want to waste my time with that. I want to make everything automatic and be able to track all of my accounts in one handy view. Maybe some people need to enter data to be able to analyze and manage their money better, but the rest of us have more important things to do.
