### ISSUE TITLE
Column "Left" doesn't update on Budget-Page

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#968]
#### Description of my issue

If you update the amount for a budget on the budget-page, the "status"-bars will be updated, but the column "Left" won't be updated. If you update the page, the values are correct.

#### Steps to reproduce 

1. Go to Budget-Page
2. Change the amount of money for any budget
3. The Status-Bars do update
4. The "Left" column doesn't

![image](https://user-images.githubusercontent.com/31184224/32266252-f1ad8a24-bee6-11e7-95b5-b2efeef65239.png)

I can reproduce this on the demo-page.

**Comment by JC5** [comment]
Indeed. That would be a nice addition!

**Comment by JC5** [comment]
This is now fixed and works as requested on the demo site: https://firefly-iii.nder.be/

**Comment by nicoschreiner** [comment]
Thanks!
