### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by fibaxx** [firefly-iii/firefly-iii#969]
Hello,
i am doing a fresh install of firefly 4.6.9.

At the database step, after i put in 

> php artisan migrate:refresh --seed

i am getting three errors

```
[Illuminate\Database\QueryException]
could not find driver (SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations)
```

```
[Doctrine\DBAL\Driver\PDOException]
could not find driver
```

```
[PDOException]
could not find driver
```

If i go to the website in browser, i get the error
`Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)`

Ubuntu Server 16.04, PHP 7.1.11 with Apache, MySQL
The Database was created manually and the correct credentials are in the .env file.

**Comment by JC5** [comment]
Your PHP installation is broken. You still have PHP7.0 or even PHP5.6 packages lingering.

Create a new file called `pi.php` and place it in `firefly-iii/public`. Put this in it:

```
<?php
phpinfo();
```

I expect it to report back either PHP7.0 or PHP5.x

Make sure you install php-mysql or php7.1mysql packages so MySQL is recognized.

**Comment by fibaxx** [comment]
Okay that make sense.

I created the file and saw a php version 7.0.
Then i used 
`sudo apt-get purge php7.0-common`
and after that
`a2enmod php7.1`
and now it works.

Thank you for your help!

**Comment by JC5** [comment]
:+1:

**Comment by filipe-silva** [comment]
Hi, so don't quite understand how but I seems to haver this error when I try to update from 4.8.1.5 to 4.8.2.
I ran the script as I did many other times sucessfully and this happened:

`[2019-12-15 21:57:14] production.ERROR: could not find driver (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE') at /var/www/firefly-iii/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/firefly-iii/firefly-iii-updated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 0): could not find driver at /var/www/firefly-iii/firefly-iii-updated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)`

I have php 7.3 installed and only that. For more than 5 months haven't even touched it.

I was hoping someone could help me figure this out...

**Comment by filipe-silva** [comment]
Hi.
Solved it. Just gonna post what my problem was, maybe it will help someone else.

What happened was my .env file reseted somehow and lost all settings for my database, and the db type was set to pgsql, instead of mysql.

**Comment by JC5** [comment]
Glad to hear you managed to fix it. I hadn't had the time yet to reply.
