### ISSUE TITLE
Questions about reports

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#973]
I am running Firefly III version 4.6.10 

#### Description of my issue:

1. Is it possible to generate reports (PDFs) via CLI? I'd like to send myself a weekly/monthly report and store it for backup/future reference
2. I generated a report, for last month, and noticed one of my bills does not have an "Under" value

![screen shot 2017-11-01 at 22 17 35](https://user-images.githubusercontent.com/3742238/32298412-8558a720-bf52-11e7-8ba3-bd0adc53e799.png)

Bill details are:
Matching on [REDACTED] between €85.00 and €95.00. Repeats firefly.repeat_freq_half-year.
Bill is active | No
Bill will automatically linked to matching transactions | No
Next expected match | May 1, 2018
Average bill amount (2017) | €90.00
Average bill amount (overall) | €90.00

P.S. just noticed a missing translation for firefly.repeat_freq_half-year on the bill details page

**Comment by JC5** [comment]
I can replicate the bill issues, so those I will fix.

I can't help you with the PDF export, generating PDF's is best done using your browser. Personally, I have a bunch of links for each year/month that I can revisit at my leisure (bookmarks). Perhaps there is a trick to make Chrome to this automatically. Visit a page, print as PDF?

**Comment by gavu** [comment]
That's actually a great idea. Thanks for the tip.

**Comment by JC5** [comment]
Closed, a new release is live.
