### ISSUE TITLE
Question about bills

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#974]
I am running Firefly III version 4.6.10 

#### Description of my issue:

On the dashboard, the Bills widgets tell me I still have €493.50 to pay this month. On the Bill page, I have the following unpaid bills:

| # | Amount Min | Amount Max |
| -- | -- | -- |
| 1 | 1 | 500 |
| 2 | 25 | 65 |
| 3 | 25 | 50 |
| 4 | 40 | 60 |
| 5 | 20 | 100 |
| 6 | 1 | 100 |

How are the remaining bills calculated?

**Comment by JC5** [comment]
(Amount min + amount max) / 2.

So (501/2)+(90/2)+(75/2)+(100/2)+(120/2)+(101/2) = 493.5

**Comment by gavu** [comment]
Wouldn't be a user more on the safe side if he would prepare for the worst, meaning, the max amount he would have to pay?

**Comment by JC5** [comment]
But the max amount could be high just to catch outliers. So by taking the average amount it all works out.

**Comment by gavu** [comment]
So is the min amount and that is actually the one that causes the problems. For example, I am paying my credit card bills, those bills get smaller every month.

E.g. 
2017-10 => 300
2017-11 => 290
...
2018-12 => 180
2019-01 => 170

if I keep changing the min/max values, and re-scan the transactions, I lose the old ones, as they will not match anymore. If I keep them, and think in advance, the very last bill would be 10, meaning, min=10 and max=300

**Comment by JC5** [comment]
That's a unique use case, but you have more of those 😉 

In this example, do you pay 10 every month, or 300,290,etc every month?

**Comment by gavu** [comment]
It is a good question, I don't really know the exact formula, all I know is, the bills keep getting lower. I can also pay in advance. 

If I have a debt of e.g. 5000, the monthly bill would be, let's say 500. and if I pay 1000 in advance, the next bills would be 20% lower

Anyway, as you said, I have a lot of special cases. My mom always used to say I'm a special snowflake 🤣
