### ISSUE TITLE
Make "Quickswitch" translatable

### ISSUE THREAD

**Issue by Findus23** [firefly-iii/firefly-iii#976]
This is quite minor, but in my opinion it would be nice to make the String "Quickswitch" translatable:
https://github.com/firefly-iii/firefly-iii/blob/aea6575358ea74322d8a58a42e8a51711fac8bef/resources/views/transactions/single/create.twig#L20

**Comment by JC5** [comment]
I never realized it wasn’t! :D

**Comment by Findus23** [comment]
@pkoziol 
Thanks for the quick fix.
