### ISSUE TITLE
Default financial report does not support multiple currencies

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#978]
I am running Firefly III version 4.6.8, but problem also exists on 4.6.10 on demo site.

#### Description of my issue:
In _Default financial report_, should, _Account balances > Sum of sums_ match _Income vs. expenses > Difference_? I guess it should, but mine is off by ~10% (that's why I noticed).

I don't know how it could be easily solved. For tables Account balances and Income vs. expenses probably there could be multiple rows with Sum of sums and Difference for each currency, but I've no idea what to do with the rest of them.

For now, maybe you could add something like:

> Warning! Generating report for accounts with multiple currencies may return strange results.

at the top of the report. Similar to:

> Warning! 1036 days of data may take a while to load.

#### Steps to reproduce 

1. Make [transfer](https://firefly-iii.nder.be/transactions/show/689) from Checking Account (€10.00) to Foreign Checking Account (£8.87).
2. Generate [Default financial report for current month](https://firefly-iii.nder.be/reports/default/1,32,2,3/20171101/20171130).
3. Sum of sums (€-861.98) don't match Difference (€-860.85).

**Comment by JC5** [comment]
Indeed, a tricky one. Such a warning combined with the multiple rows should at least make it clear. Thanks for reporting this!

**Comment by JC5** [comment]
Let's label this an enhancement so the bot doesn't kick in.

**Comment by JC5** [comment]
The next release of Firefly III will be able to handle multiple currencies better, although most sums will still be in the user's default currency. This is something that I can't really help. But most entries will show the currency of the actual transaction(s) if at all possible.

I can't do much yet with the budget related boxes in the reports. That requires a change in the budget database code. I've prepped some migrations but it'll take a few versions to take hold with everybody. Like with the other issue, I have some things lined up for budgets.

I'm marking this as fixed for the next release.

**Comment by JC5** [comment]
Closed pending the next release this weekend.
