### ISSUE TITLE
Having less then 5% on a piggy bank breaks the progressbar on the Dashboard

### ISSUE THREAD

**Issue by Tim-Frensch** [firefly-iii/firefly-iii#980]
I am running Firefly III version 4.6.10

Firefox 57b

**Description of my issue:**

If you have less then 5% give or take in a piggy bank the progress bar doesn't show the amount saved.
The amount is shown in white and is only visible when the progress bar is further then 5-10% depending on the amount.

![2017-11-03 21_17_32-what s playing_ firefly iii](https://user-images.githubusercontent.com/7996312/32394187-90028af2-c0dc-11e7-957c-01a34ab7cf55.jpg)

And if the language is set to Dutch the amount completely disappears.
** Chrome doesn't remove the amount completely. Just Firefox.

![2017-11-03 23_08_35-hoe staat het er voor_ firefly iii](https://user-images.githubusercontent.com/7996312/32397824-05c2b3d4-c0ec-11e7-944f-8868505f15b0.jpg)

**Comment by JC5** [comment]
Indeed! I shall push a fix. It will be visible on the demo site and go live with the new release. 

The reason the Dutch text disappears is because Dutch has a space between the currency symbol and the amount.
