### ISSUE TITLE
"guzzle" is abandoned

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#982]
I am installing Firefly III version 4.6.10 

#### Description of my issue:

I was installing the latest FF to a dev environment - to play around with the code got the following warning from composer:

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead`

**Comment by JC5** [comment]
I know. It's a dev-package for code coverage that has an old reference. It's fairly harmless, especially since no production packages depend on this.

You can follow the discussion here: https://github.com/php-coveralls/php-coveralls/issues/203
