### ISSUE TITLE
Docker installation results in 500 response

### ISSUE THREAD

**Issue by andreipoe** [firefly-iii/firefly-iii#983]
I am running Firefly III version 4.6.10.

#### Description of my issue:

I have followed the Docker installation instructions, but I am unable to obtain a working setup. I have tried the suggestions in Issues #581, #566 and #864, but they did not help.

I am running Docker behind an nginx reverse proxy, but I am not able to access firefly directly from the host either (using curl). In both cases, I get a 500 response. Even more, I still get 500 if using curl from _within the container_ itself.

#### Steps to reproduce 

1. Clone the repository.
2. (_Optional_) Attempt changes suggested in the issues mentioned above.
2. As per the [Docker installation guide](https://firefly-iii.github.io/using-docker.html), run the commands:

```
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
docker-compose exec firefly-app php artisan migrate:refresh --seed --force
docker-compose exec firefly-app php artisan firefly:upgrade-database
docker-compose exec firefly-app php artisan firefly:verify
```

4. Attempting to connect to Firefly results in a 500 response.

**Comment by JC5** [comment]
That sucks! Is there anything in the log files? Check out storage/logs. When I know the nature of the 500-error I can investigate further.

**Comment by andreipoe** [comment]
Hi, thanks for the quick reply. The logs were initially empty, but I realised this was a permissions issue (not having done `chown www-data` on my Docker volume mount point).

Once I did that, I got to a broken log in page that said "Be right back" . I checked other issues and I did the `artisan *:clear` commands suggested in #889. Now, that message is gone, but the error I am seeing is:

```
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

file_put_contents(/var/www/firefly-iii/storage/framework/sessions/QbdSh4Bk3Aou4tdWlcNfMM1gSWZsukNctPy42AZ9): failed to open stream: No such file or directory
```

Here's what is in `storage/logs/ff3-apache2handler-2017-11-05.log`:

```
[2017-11-05 19:26:35] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/sessions\/QbdSh4Bk3Aou4tdWlcNfMM1gSWZsukNctPy42AZ9): failed to open stream: No such file or directory","time":"Sun, 05 Nov 2017 19:26:35 +0000","file":"\/var\/www\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Filesystem\/Filesystem.php","line":122,"code":0,"version":"4.6.10"}
[2017-11-05 19:26:36] local.ERROR: file_put_contents(/var/www/firefly-iii/storage/framework/sessions/QbdSh4Bk3Aou4tdWlcNfMM1gSWZsukNctPy42AZ9): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/firefly-iii/storage/framework/sessions/QbdSh4Bk3Aou4tdWlcNfMM1gSWZsukNctPy42AZ9): failed to open stream: No such file or directory at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)"}
```

... and in `storage/logs/ff3-cli-2017-11-05.log` (although this may be from the "Be right back" error, since the time stamp is a bit older):

```
[2017-11-05 19:22:56] local.ERROR: Method TwigBridge\Command\Clean::handle() does not exist {"exception":"[object] (ReflectionException(code: 0): Method TwigBridge\\Command\\Clean::handle() does not exist at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:135)"}
```

Here is what the page looks like: 

![image](https://user-images.githubusercontent.com/6793243/32418353-11ef3df6-c260-11e7-8948-441b9ea9b810.png)

**Comment by JC5** [comment]
It looks like a permissions issue, which you should be able to solve making the storage dir writable. I am however, surprised that this is not the case by default. Could you try and find out if that solves it? I'll make sure this dir is made to be writable.

**Comment by andreipoe** [comment]
`storage/framework` was writable, but there was no `sessions` directory inside here. I manually created it and the error message went away. 

However, the page still only has the basic HTML elements as above and no formatting. Chrome tells me it is "trying to load scripts from unauthenticated sources", and if I allow it, then I get the same page as on the demo instance. Perhaps this is a different issue though?..

**Comment by JC5** [comment]
Strange, it should have been there. If the scripts are being loaded it means the URL's Firefly III is generating are http, and not https. Check if you have set the TRUSTED_PROXIES (see also the issues you are refering to).

**Comment by andreipoe** [comment]
> If the scripts are being loaded it means the URL's Firefly III is generating are http, and not https

Yes, I have confirmed this using the browser console.

>  Check if you have set the TRUSTED_PROXIES

I have tried both setting it to my server's IP address and to `**`, but neither helped.

**Comment by JC5** [comment]
I'm verifying if the docker install used the correct .env file. Did you see these issues already? https://github.com/firefly-iii/firefly-iii/issues/921 https://github.com/firefly-iii/firefly-iii/issues/882

They might have some answers as well.

**Comment by andreipoe** [comment]
I've managed to get it working now by rebuilding the Docker image. Previously, I was changing the values of the variable in the file inside the container, then restarting the container; however, that didn't seem to be enough. 

It's worth noting that I manually added `COPY .env.docker /var/www/firefly-iii/.env.docker` to the Dockerfile, as someone mentioned in a previous issue. 

It now seems to be working fine and all serving over https. Thanks for the help with this!

**Comment by JC5** [comment]
I'm glad you got it working. I've seen more issues with the .env file but I haven't been able to reproduce them. It seems the .env file used inside the docker container is the correct one. But I've added this command as well, just to be on the safe side.

If you need anything, just open an issue :).
