### ISSUE TITLE
Documentation/upgrade for using env with docker?

### ISSUE THREAD

**Issue by DracoMilesX** [firefly-iii/firefly-iii#984]
I was wondering if it was possible to download the .env file and mount it into the docker container and get the environment variables filled in like this?

Kinda similar to how it is done for monicahq

**Comment by JC5** [comment]
I'm sure it is, but I don't use docker myself so I wouldn't even know where to start. If you have some pointers, I'd love to get started!

**Comment by DracoMilesX** [comment]
I think a good start point would be to check at the dockerfile for Monicahq.
Will try myself somethings later then as well to see what I can do.

https://github.com/monicahq/monica/blob/master/Dockerfile
https://github.com/monicahq/monica

If I am not mistaken FireFly-III and MonicaHQ pretty much use the same programming? So technically just replacing somethings would get you started and from their troubleshoot further

**Comment by JC5** [comment]
I'm not really sure what it is they do to "download the .env and mount it". As far as I can tell they do no strange things with the .env file.

As far as I know, the environment variables are only filled in when you use the docker compose command. When you pull the image or build it manually you must provide the .env file yourself.
