### ISSUE TITLE
Could not decrypt preference #7. If this error persists, please run "php artisan cache:clear" on the command line. 

### ISSUE THREAD

**Issue by acecombat2** [firefly-iii/firefly-iii#986]
I am running Firefly III version 4.6.10 on wamp windows 7

#### Description of my issue:

Can't login after registered account, fresh re-installation with new database. it works before without api key for mapbox and email details.
 
#### Steps to reproduce 

APP_ENV=local
APP_DEBUG=true
APP_NAME=FireflyIII
APP_KEY=base64:cXwaVi2L2KKhLxtOI4zx+L7s306fZLXt/AsEF3cPg7s=
APP_LOG=daily
APP_LOG_LEVEL=warning
APP_URL=http://localhost
TRUSTED_PROXIES=

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=firefly (own custom db name)
DB_USERNAME=db username
DB_PASSWORD=db password

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_FROM=mygmail
MAIL_USERNAME=mygmail
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=ssl

SEND_REGISTRATION_MAIL=true
SEND_ERROR_MESSAGE=true
SHOW_INCOMPLETE_TRANSLATIONS=false

CACHE_PREFIX=firefly

SEARCH_RESULT_LIMIT=50
EXCHANGE_RATE_SERVICE=fixerio

MAPBOX_API_KEY=(Inserted Api Key from google site)
ANALYTICS_ID=
SITE_OWNER=(My email)
USE_ENCRYPTION=true

PUSHER_KEY=
PUSHER_SECRET=
PUSHER_ID=

DEMO_USERNAME=
DEMO_PASSWORD=

Log:

Whoops! An error occurred.

Unfortunately, this error was not recoverable. Firefly III broke. The error is:

Could not decrypt preference #7. If this error persists, please run "php artisan cache:clear" on the command line.
Error

This error occured in file D:\Software\wamp64\www\firefly-iii\app\Models\Preference.php on line 66 with code 0.
Stack trace
#0 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(438): FireflyIII\Models\Preference->getDataAttribute('eyJpdiI6ImU5MU9...')
#1 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(340): Illuminate\Database\Eloquent\Model->mutateAttribute('data', 'eyJpdiI6ImU5MU9...')
#2 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(313): Illuminate\Database\Eloquent\Model->getAttributeValue('data')
#3 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1344): Illuminate\Database\Eloquent\Model->getAttribute('data')
#4 D:\Software\wamp64\www\firefly-iii\app\Support\Preferences.php(160): Illuminate\Database\Eloquent\Model->__get('data')
#5 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(221): FireflyIII\Support\Preferences->lastActivity()
#6 D:\Software\wamp64\www\firefly-iii\app\Support\CacheProperties.php(52): Illuminate\Support\Facades\Facade::__callStatic('lastActivity', Array)
#7 D:\Software\wamp64\www\firefly-iii\app\Support\Amount.php(234): FireflyIII\Support\CacheProperties->__construct()
#8 D:\Software\wamp64\www\firefly-iii\app\Support\Amount.php(223): FireflyIII\Support\Amount->getDefaultCurrencyByUser(Object(FireflyIII\User))
#9 D:\Software\wamp64\www\firefly-iii\app\Http\Middleware\Range.php(121): FireflyIII\Support\Amount->getDefaultCurrency()
#10 D:\Software\wamp64\www\firefly-iii\app\Http\Middleware\Range.php(81): FireflyIII\Http\Middleware\Range->configureView()
#11 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 D:\Software\wamp64\www\firefly-iii\app\Http\Middleware\AuthenticateTwoFactor.php(80): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 D:\Software\wamp64\www\firefly-iii\app\Http\Middleware\Authenticate.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 D:\Software\wamp64\www\firefly-iii\app\Http\Middleware\Sandstorm.php(60): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): FireflyIII\Http\Middleware\Sandstorm->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Router.php(647): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Router.php(622): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Router.php(588): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#44 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Router.php(577): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#45 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#46 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#47 D:\Software\wamp64\www\firefly-iii\vendor\fideloper\proxy\src\TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 D:\Software\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 D:\Software\wamp64\www\firefly-iii\public\index.php(74): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}

**Comment by acecombat2** [comment]
Update: now is all running with slight solvable problem.

**Comment by JC5** [comment]
It said "you have no currency with code EUR" or something similar? In that case, you may not have run the migration code.
