### ISSUE TITLE
Empty transaction list under specific tag after import

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#987]
I am running Firefly III version 4.6.10 

#### Description of my issue:

I noticed that, when deleting import tags, the tag details contain the correct amounts, but no transactions are listed (I do not know if this is related to your last enhancement https://github.com/firefly-iii/firefly-iii/commit/33d89d52c2fefddebc0f4c9d2830d2105c033358)

#### Other important details (log files, system info):
![screen shot 2017-11-07 at 20 40 10](https://user-images.githubusercontent.com/3742238/32514097-43211ff0-c3fc-11e7-8ef9-860cba001398.png)

**Comment by JC5** [comment]
And there i thought i fixed them all :).

**Comment by gavu** [comment]
is it related to the above mentioned commit?

**Comment by JC5** [comment]
Yes, it is.

**Comment by gavu** [comment]
... and I promised myself I would wait until the next release to report bugs (as I am still using the `develop` branch). If you're interested, I did find one, or more broken SQL joins :)

On `https://my.host.name/accounts/show/1` and `https://my.host.name/transactions/deposit` the tables show a `1` instead of the correct opposing account name (the link - `opposing_account_id` - is correct)

**Comment by JC5** [comment]
... and I told myself I was going to find these bugs myself, since you reported one I had spotted already. But here you are reporting all kinds of things I missed. Keep it coming please :grin:

**Comment by JC5** [comment]
I can't replicate that one though. Could you clear your cache to be sure?

**Comment by gavu** [comment]
I’ll have to come back to you on that one a bit later. I’m on my way to work now.

**Comment by JC5** [comment]
Found and fixed, I was the one with cache issues it seems :o
