### ISSUE TITLE
Ability to not create tags for empty imports

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#988]
I am running Firefly III version 4.6.10 

#### Description of my issue:

I have created a cronjob, which automatically downloads and imports transactions from the bank into FF.
I did create a check to see if the import file is empty (contains only headers) to skip the import. FF however, creates a import tag even if all transactions in an import file have been skipped due to duplicates. Would it be possible to create an option to not create import tags for empty and/or skipped imports? 

Either hard-code it into the workflow or add it as an option in the settings page

**Comment by simonsmiley** [comment]
If I were you, I would do the duplicate checking in the cronjob, not in firefly. You have more knowledge about that than firefly does, so the results should be better. Use the timestamp, and last couple of transactions to make sure you only have new ones

**Comment by gavu** [comment]
@simonsmiley, I did think about that, and I am modifying the data between the bank export and the import (transfer descriptions, asset and opposing IBAN, etc), however, the FF rules are easy to use and more visual (triggers, actions, priority, and so on)

**Comment by JC5** [comment]
Checking for duplicates is fairly advanced in FF so it's OK to rely on it. As such, it's reasonable to ask not to create tags when nothing has been imported. Should be an easy fix.

**Comment by Aquariu** [comment]
That's awesome ! I was also considering asking something like that. Like Gavu I have a daily import of transaction, except that my bank always give me a fixed number of transaction in the CSV file, so I can't easily skip the import.

Question: 
1) Is there a command line parameter to skip tag creation durign import (`php artisan firefly:create-import`) ? 
2) Is there a way to massively delete old unused tags (even tags that have transactions linked to them without deleting the transactions) ?

Kind regards,
Olivier

**Comment by JC5** [comment]
Hi Olivier,

1. In the future, it will never generate a tag when importing 0 journals.
2. Yes, you can delete tags without deleting the transaction. But there is no mass-delete for tags. I can write  a query for you, but run it at your own risk :wink:. Stay tuned.

**Comment by JC5** [comment]
This query will at least show you the unused tags:

```
select tags.id from tags
left join tag_transaction_journal ON tags.id = tag_transaction_journal.tag_id
where tags.user_id = 1
and tags.deleted_at is null 
and tag_transaction_journal.tag_id is null
```

You can then delete them by running
```
update tags SET deleted_at = NOW() where id IN (1,2,3,4)
```
