### ISSUE TITLE
Showing historical records for all months doesn't scale

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#989]
In the detail views of accounts, categories and budgets, historical data for all past months is shown.

This obviously doesn't scale. If you want to keep the layout, I would opt for a max. of 5 previous months. Otherwise a graph might be a good option to show everything

**Comment by JC5** [comment]
It's not half-bad, actually. I'm at five years now and a lot of charts scale up surprisingly well. But I agree.

A maximum number of months isn't viable: you'd want to show _whatever_ period of time in a useful manner. Between 0 - 12 months, it could be as is. But 12-48 months? 48+? I feel they need their own solution and I don't know yet what it could be.

I'll think about it and I would appreciate your input :).

**Comment by simonsmiley** [comment]
I don't mean the charts but this section https://imgur.com/a/jHaUj

Screenshot taken from the demo page... It makes the page so long, I don't think anyone can actually use this. If this is converted to a chart, it would take less space and be more readable

**Comment by gavu** [comment]
Maybe create accordions for each year (opening one closes all others) ?

**Comment by JC5** [comment]
Ah yeah, good point! Those are quite long indeed. I know my demo-screenshots are often 10K+ pixels. I'll get right on it :-)

**Comment by JC5** [comment]
I'm moving this one to the next release. For more details, see issue #1040.

**Comment by JC5** [comment]
Alright in the mean time, many lists already support going back years and years and years (see also #1040). So the original issue is fixed, and I would like to ask you to bug me in #1040 about any problems you see with weird charts, bad scaling or long lists. Is that OK?
