### ISSUE TITLE
Report page enhancements for access and display

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#990]
I am running Firefly III version 4.6.10 

#### Description of my issue:

I know this came up in a previous thread, can't remember which one, but I thought this would be a neat feature worth discussing/voting

Ability to access report pages with additional parameters:
* token: the user-token from the profile page
* view: print (https://adminlte.io/themes/AdminLTE/pages/examples/invoice-print.html)

> final url would be something like https://my.host.name/reports/default/1,3/20171001/20171031?token=hhet265rdwquyreuq653erq&view=print

This would allow the user to send reports programmatically by cron jobs / scheduled tasks

**Comment by JC5** [comment]
I see what you're doing here :wink:

I can't overrule the auth-system with the token, so either way the print view cannot be generated using a token alone. You would need a session of some kind. But a dedicated print CSS for at least the reports could be very useful. I'll check it out!

**Comment by gavu** [comment]
It was only one of those weird shower-ideas :)

**Comment by gavu** [comment]
Do you have any knowhow on using wget or curl with FF? I’m trying to log in and go to the reports page. Wget throws a authentication timeout error and curl redirects to the login page...

**Comment by JC5** [comment]
You'll have to:

- GET the login form, and save the cookie and CSRF token.
- POST the login form with your username and password, token and cookie.
- POST 2FA if you use it. (so interactive because you can't program this beforehand)
- Save the final cookie from the response somewhere.
- Use the cookie when requesting the report.

Then it should work. ;-)

**Comment by Aquariu** [comment]
gavu, I'm interrested in this as well. If you manage to generate reports with a cronjob, I'd like to know how to do it.

Kind regards,

Olivier

**Comment by gavu** [comment]
@Aquariu, I'll keep you informed, right now I am having issues with wget and curl. One ignores the cookies/session file and the other one throws an authentication timeout error. I'll look into it and post a solution here as soon as possible

**Comment by simonsmiley** [comment]
If you really want to use it often, I recommend writing a python script using requests. should make it way easier for you to use...

**Comment by gavu** [comment]
@simonsmey, last time I used python to build something, was about 10years ago. Any input/suggestion would be greatly appreciated :)

**Comment by simonsmiley** [comment]
@gavu everything you need should be included [here](http://docs.python-requests.org/en/master/user/quickstart/)

**Comment by JC5** [comment]
The CSS has special code for a print layout, but this is still very browser dependent. You can run Chrome in headless and make it print pages but it seems to ignore your profile. Nevertheless, that is the direction I would go for.

There is no "view=print" mode available, the CSS simply has the print-mode included all the time, and your browser renders it when you print.

But this works from the command line already (on my mac):

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --print-to-pdf="test.pdf" https://firefly-iii.nder.be
```

The result is a PDF file:

![screen shot 2017-11-18 at 20 43 47](https://user-images.githubusercontent.com/5889984/32984156-375c3792-cca1-11e7-9aeb-4a1fcae6fd46.png)

Several solutions exist that tie-in to this functionality.

* https://github.com/fraserxu/electron-pdf
* https://www.google.nl/search?q=firefox+render+page+and+print+pdf+command+line
* https://www.google.nl/search?q=make+website+pdf+command+line&oq=make+website+pdf+command+line
* https://superuser.com/questions/592974/how-to-print-to-save-as-pdf-from-a-command-line-with-chrome-or-chromium
* https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by gavu** [comment]
Is there any chance of adding a `view=print` option to the generated reports page? This should not contain any headers/menus/breadcrumbs etc. just the tables and the charts

I don’t know exactly how this works, but maybe the view would also need full URL to the `css` and `js` files

**Comment by JC5** [comment]
The print view is CSS based: when you view the HTML page using the "print" media instead of the "screen" media (your browser does this when printing) those bars disappear. The HTML still contains the nav-bars etc., they're just not rendered.
