### ISSUE TITLE
Budget page not showing spending information

### ISSUE THREAD

**Issue by ncicovic** [firefly-iii/firefly-iii#992]
I am running Firefly III version 4.6.10

On a budget page I have no information about spending. "Spent" column is always at 0.00 for every budget even though there is spending for specific budgets.

I didn't find any error messages in the debug log file. Any idea what could be wrong?

![budget1](https://user-images.githubusercontent.com/33590048/32695894-18d01a34-c768-11e7-97ca-7e0340754edf.png)

![budget2](https://user-images.githubusercontent.com/33590048/32695893-18b2300a-c768-11e7-834b-73a7ed06de82.png)

![budget3](https://user-images.githubusercontent.com/33590048/32695916-b08e508e-c768-11e7-85c5-60b639d9258f.png)

**Comment by JC5** [comment]
You've found a bug: it seems transactions that go towards a cash account are not counted towards the budget in this particular view.

You will have to do without a correct overview for the time being, although the budget report (see page `/budgets`) works, and other views work as well.

When I push a new release (somewhere next week, I expect) it will be fixed :)

**Comment by ncicovic** [comment]
Thank you James,

and thank you for this exceptional project.

**Comment by JC5** [comment]
You're welcome! :+1:
