### ISSUE TITLE
Slow render times for /tags page

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#993]
I am running Firefly III version 4.6.10 

#### Description of my issue:

I am aware RPi is really slow, but the /tags page is way slower than anything eles, maybe the there's place for improvements?

#### https://my.host.name/
 Name | Offset (ms) | Duration (ms)
-- | -- | --
App cache | 1100 | 0
DNS lookup | 1100 | 0
TCP connection | 1100 | 0
TCP request | 1105 | 2180
TCP response | 3285 | 94
Processing | 3287 | 1079
onload event | 4366 | 2

#### https://my.host.name/tags
 Name | Offset (ms) | Duration (ms)
-- | -- | --
App cache | 0 | 8
DNS lookup | 8 | 1
TCP connection | 9 | 4
TCP request | 13 | 53
TCP response | 66 | 35831
Processing | 35856 | 1048
onload event | 36904 | 1

#### Steps to reproduce 

I can't currently reproduce it on the demo site since there are only 4 tags, and I have about 70+. I used [this addon](https://addons.mozilla.org/en-US/firefox/addon/apptelemetry/)

**Comment by JC5** [comment]
I can't be sure at the moment, but I suspect various queries are very slow, an effect which gets worse and worse when more tags are involved. I'll check it.

**Comment by JC5** [comment]
Yep. Massive queries. I'll optimize the view.

**Comment by JC5** [comment]
I've pushed a fix!

**Comment by gavu** [comment]
It works great. Even on my crappy RPi. Great job!
