### ISSUE TITLE
Ability to clone split transactions

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#998]
It's only cloning the first split

**Comment by JC5** [comment]
Indeed it is. I'll write it down!

**Comment by simonsmiley** [comment]
it won't be that easy to implement. You will probably need to add a view that allows creating split transactions from the start, if you want to keep the same functionality as for "normal" transactions

**Comment by JC5** [comment]
Yep. :D  

Which would also be useful for normal split transactions of course so there's that :)

**Comment by JC5** [comment]
Will be a part of 4.8.0 because of the new transaction structure.

https://github.com/firefly-iii/firefly-iii/projects/5#card-19937456
